### ISSUE TITLE
Erroneous space materials 

### ISSUE THREAD

**Issue by klokoy** [IfcOpenShell/IfcOpenShell#10]
When using the IfcConverter to convert the duplex house (with only space included) some spaces are not transparent. I see the same in other models as well. In solibri I see that theese spaces are a different colour then the other (I think they use a different geometry) but they are transparent.

<img width="734" alt="screen shot 2015-11-30 at 15 51 47" src="https://cloud.githubusercontent.com/assets/973082/11474809/63dd29d8-977a-11e5-92ff-6dae9ff3aa7f.png">

**Comment by aothms** [comment]
The reason for this is that these spaces do not have any colour (IfcSurfaceStyle) associated with their representations. Solibri is kind enough to give you a transparent default color, but IfcOpenShell doesn't. You can clearly identify colours that are derived from the IFC file by the name they are assigned in the OBJ or DAE file.
