### ISSUE TITLE
Issue building HDF5 branch

### ISSUE THREAD

**Issue by bigdoods** [IfcOpenShell/IfcOpenShell#100]
Hi Thomas,

I have followed the instructions and as I didnt install openCollada, I have gone into the cmake.txt file and changed the value to include open cascade to OFF then rebuilt the make file. I have tried to make and I receive the following Error: 

Scanning dependencies of target IfcParse
[  2%] Building CXX object CMakeFiles/IfcParse.dir/home/john/badbim/IfcOpenShell-HDF5/src/ifcparse/IfcParse.cpp.o
In file included from /home/john/badbim/IfcOpenShell-HDF5/src/ifcparse/IfcParse.cpp:43:0:
/home/john/badbim/IfcOpenShell-HDF5/src/ifcparse/../ifcparse/IfcHdf5File.h:25:19: fatal error: H5Cpp.h: No such file or directory
compilation terminated.
CMakeFiles/IfcParse.dir/build.make:54: recipe for target 'CMakeFiles/IfcParse.dir/home/john/badbim/IfcOpenShell-HDF5/src/ifcparse/IfcParse.cpp.o' failed
make[2]: *** [CMakeFiles/IfcParse.dir/home/john/badbim/IfcOpenShell-HDF5/src/ifcparse/IfcParse.cpp.o] Error 1
CMakeFiles/Makefile2:167: recipe for target 'CMakeFiles/IfcParse.dir/all' failed
make[1]: *** [CMakeFiles/IfcParse.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

It looks like there is a file missing? 

Thanks,

John

**Comment by iras** [comment]
Restore the cmaketext file and use this line below instead.

'cmake -DCOLLADA_SUPPORT=False ../'

**Comment by bigdoods** [comment]
Hi,

I have just tried what you said and it has given me the same error. When I run the command. Here is the output:

```
$cmake -DCOLLADA_SUPPORT=False ../
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
-- Boost include files found in /usr/include
-- Boost libraries found in /usr/lib/x86_64-linux-gnu
-- Looking for opencascade include files in: /usr/include/opencascade
-- Use OCC_INCLUDE_DIR to specify another directory
-- Header files found
-- Looking for opencascade library files in: /usr/lib
-- Use OCC_LIBRARY_DIR to specify another directory
-- Library files found
-- No ICU include directory specified
-- No ICU library directory specified
-- ICU libraries found
-- Looking for C++ include limits
-- Looking for C++ include limits - found
-- Looking for C++ include climits
-- Looking for C++ include climits - found
-- Looking for C++ include limits.h
-- Looking for C++ include limits.h - found
-- Looking for C++ include fstream
-- Looking for C++ include fstream - found
-- Looking for C++ include fstream.h
-- Looking for C++ include fstream.h - not found
-- Looking for C++ include iomanip
-- Looking for C++ include iomanip - found
-- Looking for C++ include iomanip.h
-- Looking for C++ include iomanip.h - not found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Looking for C++ include iostream.h
-- Looking for C++ include iostream.h - not found
-- Found SWIG: /usr/bin/swig2.0 (found version "2.0.12") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.10") 
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.10") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/john/badbim/IfcOpenShell-HDF5/cmake/build

```
I originally tried changing my env variables like in the build instructions but have just opened a new terminal session and re-cloned the repo just to be sure about everything, then tried it again.

**Comment by iras** [comment]
I just recompiled `master` and there are errors. The current build is broken.

**Comment by Michal-sk** [comment]
I dont see any errors in that build, your build file is created. Now all you have to do is continue the installation instructions.

**Comment by aothms** [comment]
Closing this issue as it seems to have been solved. Feel free to reopen it upon any future issues.
