### ISSUE TITLE
BlenderBIM assign IFC class to multiple objects not working Blender 2.9

### ISSUE THREAD

**Issue by Kristoffernegendahl** [IfcOpenShell/IfcOpenShell#1003]
Hi Dion (and other volunteers)

I'm on Windows, Blender 2.9.0, and current release of blenderBIM "blender28-bim-200912-win"

When setting IFC class properties via the "Assign IFC Class" button, only the first element in the list is assigned.

![Assign_multiple_objects_not_working_290](https://user-images.githubusercontent.com/3524250/93450420-3d199d00-f8d6-11ea-8323-b58e0ea2390f.gif)

As I understand this was working previously https://youtu.be/uhypG45pqD0?t=1186 so it might be a versioning issue.

**Comment by Moult** [comment]
@Kristoffernegendahl you are in the object properties menu. That menu only affects the active object.

You will need to go to the scene tab and use the options there.

![image](https://user-images.githubusercontent.com/88302/93452215-80e2c580-f91b-11ea-81c7-5cb4d691c1c7.png)

**Comment by Kristoffernegendahl** [comment]
Ahh, my bad, thanks for the fast reply
