### ISSUE TITLE
BlenderBIM: Box representation does not respect project units, resulting in missing annotations

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1007]
Files: https://github.com/OpeningDesign/OD_Library/tree/2bbdcc252db719ed26956ed94b9489577b85ed7e/BIM/BlenderBIM

Version: 0.0.200912

![image](https://user-images.githubusercontent.com/507113/93716096-28861080-fb33-11ea-8ee9-8d2172ff65e5.png)

**Comment by theoryshaw** [comment]
might be related to: https://github.com/IfcOpenShell/IfcOpenShell/issues/1004#issuecomment-695764504

**Comment by Moult** [comment]
Yeah this is likely related, there were two new changes that would've fixed this in the latest version, that are getting confused with the older version:

 1. The default setting below, which should be enabled

![image](https://user-images.githubusercontent.com/88302/93723635-8e31d580-fbe3-11ea-9430-56c76649b869.png)

2. In the old version, annotation representations were accidentally purged when you pressed save if you didn't have one of them enabled at the time of saving. This was really a terrible bug, but for example in your file I think that's what happened. Trying to switch the door to the annotation representation shows that there is no annotation stored. Unfortunately just need to recreate a new door to fix that, or you can manually draw in a new annotation shape.

**Comment by theoryshaw** [comment]
1. That file had those settings.
![image](https://user-images.githubusercontent.com/507113/93773692-f71a4d00-fbe5-11ea-9381-7b7b17df0fce.png)

2. I deleted all those doors/windows and added a new dumb door...
![2020-09-21_08-43-53](https://user-images.githubusercontent.com/507113/93774212-9dfee900-fbe6-11ea-807f-0c67df482c07.gif)

 

Version: 0.0.200912

**Comment by Moult** [comment]
Very, very odd. Can we do a screenshare? Ping me on IRC whenever - I think I need to see exactly what's going on to figure this one out...
