### ISSUE TITLE
IFC nodes for Sverchok

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1010]
Visual programming nodes for IFC! Let's do it!

This issue is simply a redirect to https://github.com/nortikin/sverchok/issues/3574 - in case anybody wants to suggest ideas / test / whatever while it's getting started :)

**Comment by JitQL** [comment]
I was installing Sverchok and read your post. I'm here! Trying to learn.

Would this be a way to create models with sverchock and have a node to attach to final output so it is classified as IFC?

Like an array of cilinders would become an array of Columns instead?

I believe this to be the logic of Rhino/Grasshoper/Visual Arq:

https://www.visualarq.com/

Or is this another concept?

**Comment by Moult** [comment]
Well, the BlenderBIM Add-on can already do what you're asking - the parametric modifiers within Blender can all output IFC data arbitrarily

However, these nodes let you do it with parametrically modeled geometry, just like in Grasshopper, i.e., with a node-based UI. Basically very similar to @jmirtsch 's geometry gym, or at least how I imagine it to be, since I haven't actually used his add-on too much.

But this will also connect to all of the IfcOpenShell utils. E.g:

 - Building a parametric subset of elements from an ifc file for IfcQuery? You can do it visually now!
 - Manipulating the inputs and outputs of a clash detection with IfcClash? Go go go!
 - Parametrically visualise the results of BIMTester MicroMVD auditing? Yep.
 - Patch an IFC file yourself? Mix and match the IfcPatch recipes with your own scripts!

**Comment by JitQL** [comment]
This is starting to sound too good to be true.

There must be a catch. :)

**Comment by Moult** [comment]
Closing, as first release imminent.
