### ISSUE TITLE
[BlenderBIM] Add-on preferences button 'Visit Documentation' not user-oriented (v0.0.200912)

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#1012]
The __initially encountered documentation should be for new prospective users__, rather than only for developers. Even if it just says *there is currently no user-level documentation, click here for internals* that would be a vast improvement on the current situation, which is ... 'offputting' to new users, to say the least.

I am very happy to volunteer to write user-level documentation and provide the requisite tedious screenshots ... if it's possible to throw it in a markdown file, as per [MeasureIt-ARCH](https://github.com/kevancress/MeasureIt_ARCH).

Let me know.

**Comment by globalcitizen** [comment]
Seems there is some documentation on the Wiki right now.

A wiki's benefit is that collaborative editing is easy for people unfamiliar with git.

The issues are:
1. It is unversioned (not associated with a software release) and thus always going to be out of date or wrong for some subset of users. While this could be worked around with versioned wiki pages, the reality is this will be a mess.
2. It is not distributed with the software. This means in practice that it may be unavailable to users (eg. to users while offline).
3. Longer term, whatever process is used for internationalisation (i18n) management within the BlenderBIM source code cannot be applied simultaneously to documentation and associated tooling; eg. for language-as-a-feature release management, tracking new major-version relevant translation tasks, etc.

Other format options:
 - Markdown in git.
    - Benefits are: easy to navigate, familiar format for programmers. Relatively light weight.
    - Drawbacks: large images hard to include, presentation width limited, tends to be Github-linked only (due to dialects)
 - Something more exotic in git, like LaTeX derivates.
    - Benefits: Could generate ultra professional PDF files, print-ready beautiful documentation and reference plans for arbitrary page sizes.
    - Drawbacks: Complexity means many people will not contribute. In practice, this probably doesn't matter as they can open Github issues for documentation changes.
 - User interface accessible documentation in git
    - Benefits: Users can get help directly from Blender
    - Drawbacks: Unknown feasibility, unfamiliar format, some people are used to or prefer segregated documentation (less explorative more rote or reference style learning modes).

**Comment by Moult** [comment]
When the BlenderBIM Add-on migrates from its alpha version to a beta version late this year, then this will be revisited.

**Comment by Moult** [comment]
A status update on this. Beta version is likely to be delayed to next year, given the vast amount of changes which have been occurring (especially with the rewrite, 4D + 5D features, and new parametric systems in place). However, that said, it still makes sense to address this issue even though we are still in alpha - at least to set up a foundation, and the content can be filled up later during beta.

There are experiments underway to set up Sphinx-based developer docs. If this goes well, I want to introduce four sections:

 - Highly technical, generated typical API-like developer oriented docs with code examples, function signatures, etc.
 - "Reference" or "Dictionary" style documentation for powerusers methodically documenting each feature available via the UI
 - "Tutorial" or "Cookbook" style documentation for regular users to get them up and running and get a feel of the software.
 - Further reading section, a curated catalogue to the wider world of community-created content and other channels including other media like video tutorials, etc.
