### ISSUE TITLE
[SegFault] Remove entity 

### ISSUE THREAD

**Issue by fluider** [IfcOpenShell/IfcOpenShell#1017]
Hi,

I'm running into segmentation faults when trying to remove products from model, e.g. using the ifc4 and 2x3 fzk house.
My system: C++, v0.6.0b0, Ubuntu 20.

```
void fct(IfcParse::IfcFile *model) {
    auto walls = model->instances_by_type("IfcWall");
    for (auto &wall : *walls) 
        model->removeEntity(wall);    
}
```

> terminate called after throwing an instance of 'IfcParse::IfcException'
>   what():  Instance #75347 not found

Occurences of that number in 12 lines e.g.:

> **#75347**= IFCWALLSTANDARDCASE('3Ttjr$59XEWfWN1WUHjelZ',#12,'Wand-Ext-OG-4',$,$,#75290,#75342,'C0070317-136B-4A93-BD-CC-3B8478F23A5C',$);
> 
> #22361= IFCRELDEFINESBYTYPE('3ST22ejWkEoOTOyxpks2dy',#12,$,$,#21966,#27421,#31470,#32407,#60012,#67536,#67828,**#75347**),#22346);
> 
> #35172= IFCRELCONTAINEDINSPATIALSTRUCTURE('3w5Kjolx7vw_AxKOfOc7wq',#12,$,$,(...,**#75347**,...),#35065);

Am I using the function in a wrong way?

Best

Addition: If I break the loop after one remove, there is no seg fault. Do I have to update the model somehow after each iteration? 
In the main function the model looks like this:
`IfcParse::IfcFile *model = new IfcParse::IfcFile(ifc_path);`
I found this relating issue: [https://github.com/IfcOpenShell/IfcOpenShell/issues/275](https://github.com/IfcOpenShell/IfcOpenShell/issues/275)

**Comment by aothms** [comment]
> Addition: If I break the loop after one remove, there is no seg fault

This is the clue. And probably this needs to be fixed in IfcOpenShell, or somehow appropriate warnings need to be added. But with this approach you're removing elements from a vector while iterating over the same vector. In IfcConvert we use the following work around:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcconvert/IfcConvert.cpp#L1317

**Comment by lcpt** [comment]
I have had a similar problem (removing an element from a container while iterating on it). Maybe this can help:

https://stackoverflow.com/questions/4713131/removing-item-from-vector-while-iterating

**Comment by fluider** [comment]
Thanks to both of you. Because of the "black box" character of external libraries as IfcOS, we sometimes forget the basic C++ rules ;)

**Comment by aothms** [comment]
> "black box"

Yes, exactly. So feel free to add a comment somewhere so that we can begin to open up this box a bit.

**Comment by fluider** [comment]
I did :)
