### ISSUE TITLE
does this repo support convert geometry data(like brep) to ifc file?

### ISSUE THREAD

**Issue by Elliotloststh** [IfcOpenShell/IfcOpenShell#1021]

**Comment by Moult** [comment]
Yes :) Are you looking for Python code or C++ code?

**Comment by Elliotloststh** [comment]
Thanks for your quick reply，C++ code

**Comment by aothms** [comment]
Have a look at
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/examples/IfcAdvancedHouse.cpp

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op wo 30 sep. 2020 08:33 schreef ZigZag <notifications@github.com>:
