### ISSUE TITLE
decimal places IfcCartesianPoint

### ISSUE THREAD

**Issue by fluider** [IfcOpenShell/IfcOpenShell#1023]
Hi!

As shown in the AdvancedHouse example TopoDS_Shapes can be written to ifc using 

`IfcSchema::IfcProductDefinitionShape* building_shape = IfcGeom::serialise(STRINGIFY(IfcSchema), building_shell, false)->as<IfcSchema::IfcProductDefinitionShape>();`

Is it possible to control the number of decimal places, to prevent this:
`#80016=IFCCARTESIANPOINT((6.6599999889741,0.299999999999994,3.37320508075698));`

I looked into the code, maybe this can be done here?
[https://github.com/IfcOpenShell/IfcOpenShell/blob/b4f4d9b3c5f495943d26462cf7b052b57e53b608/src/ifcgeom/IfcGeomSerialisation.cpp#L21](https://github.com/IfcOpenShell/IfcOpenShell/blob/b4f4d9b3c5f495943d26462cf7b052b57e53b608/src/ifcgeom/IfcGeomSerialisation.cpp#L21)

I could help to implement, but I'm currently not sure how to do it. For example if the integer has to be passed top down or if we can create some kind of global variable.

Best

**Comment by aothms** [comment]
The code is here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcWrite.cpp#L73

This is for constructed data. Parsed data is written as is (I think...)

I don't oppose accepting code for this, but I do recommend reconsidering this. Rounding numbers could have some very unfortunate consequences like making faces no longer planar (deviating more than the tolerance) and therefore errors when reopening.

**Comment by fluider** [comment]
Thank you for the quick reply. I understand your concerns regarding invalidating planes. 
Rounding the points to a precision of 1e-6 is what I aim for. I think thats also the precision OCC uses by default. This would be my goal considering my previous example line:

`#80016=IFCCARTESIANPOINT((6.66,0.3,3.373205));`

I understand, that there is currently no way to do it and that you don't want to include it. Could you think of a workaround? Only thing I can imagine is editing all IfcCartesianPoints afterwards in the ascii file. OCC doesn't allow changing precision of coordinates as far as I know. You would have to trsf the vertices.

Best

**Comment by aothms** [comment]
Well a static member would always work I guess.

Maybe a `static boost::optional<size_t> decimal_places` in https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcWrite.h#L51 that you initialize somewhere from your code. Pass it to the visitor with `get_value_or(std::numeric_limits<double>::digits10)` here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcWrite.cpp#L252

**Comment by fluider** [comment]
No progress made on this at the moment. I suspect that I have to do the changes at another spot in ifcopenshell, because it couldn't see any effect even when hardcoding the precision in std::string format_double(const double& d). I will look again.

**Comment by aothms** [comment]
It's working for me:

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> f.createIfcCartesianPoint((0.11111111111111111111111111111111111,0.222222222222222222222222222222,0.33333333333333333333333333333333333))
#1=IfcCartesianPoint((0.11,0.22,0.33))
>>> f.write("test.ifc")
>>> print(open("test.ifc").read())
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2020-10-14T12:21:58',(),(),'IfcOpenShell 0.6.0b0','IfcOpenShell 0.6.0b0','');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCCARTESIANPOINT((0.11,0.22,0.33));
ENDSEC;
END-ISO-10303-21;

```

But as I said

> This is for constructed data. Parsed data is written as is (I think...)

```
(py35) $ git diff src\ifcparse
diff --git a/src/ifcparse/IfcWrite.cpp b/src/ifcparse/IfcWrite.cpp
index 9be3bbd0..e83ce957 100644
--- a/src/ifcparse/IfcWrite.cpp
+++ b/src/ifcparse/IfcWrite.cpp
@@ -73,7 +73,7 @@ private:
        std::string format_double(const double& d) {
                std::ostringstream oss;
                oss.imbue(std::locale::classic());
-               oss << std::setprecision(std::numeric_limits<double>::digits10) << d;
+               oss << std::setprecision(2) << d; //  std::numeric_limits<double>::digits10) << d;
                const std::string str = oss.str();
                oss.str("");
                std::string::size_type e = str.find('e');
```

Did you properly rebuild and reinstall the module?

**Comment by Anish-Russel** [comment]
Hello @aothms,
What about TokenArgument::toString() [IfcOpenShell/src/ifcparse/IfcParse.cpp +871] function. It looks like it also converts double to string.

**Comment by aothms** [comment]
Does it? I thought it just grabs the text from the underlying token stream https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcParse.cpp#L599 But I might remember wrongly, it's been a while and there have been various pull requests on this.

token.value_double appears to be only read here when interpreting as double https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcParse.cpp#L539

But as I said, the approach I hinted at above only applies to constructed data. Which is the code path followed by `IfcGeom::serialise()` as @fluider is referring to.

**Comment by fluider** [comment]
Hi Thomas,
we are rounding the doubles that shall be written to IFC now beforehand. To introduce an argument controlling the specific entities and number of digits in the IfcOpenShell code seemed not feasible.
Thank you for your suggestions to change the number of digits read in!
