### ISSUE TITLE
Relative placement serialization

### ISSUE THREAD

**Issue by fluider** [IfcOpenShell/IfcOpenShell#1024]
Hi, I have a question on the serailization of TopoDS_Shapes and their placement.

I have a TopoDS_Shape (wall), e.g. with a z bbox from 10m to 20m and an IfcBuildingStorey that is located at z=10m. In "reality", the wall is on the slab of the storey.

Now, when serializing the shape by stating the storey as the relative placement, the coordinates (IfcCartesianPoint) are still showing 10m and 20m. Because of the relative placement I would like to have 0m and 10m for IfcCartesianPoint in the Ifc file.

I found some threads showing how to calculate the global position in python, but is there a reversed way in C++, automatically trsf-ing the TopoDS_Shape after passing the relative placement? Or could you provide some help, so that I know how to start?

Best

**Comment by aothms** [comment]
This is something that generally needs some work. OCCT is able to store a hierarchy of placements in the TopLoc_Location associated with TopoDS_Shape::Location. But we currently don't make use of that.

If you have a gp_Trsf for the IfcBuildingStorey. You would just have to Invert that and Move() the shape accordingly. This is similar to how openings are processed. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomFunctions.cpp#L768

**Comment by fluider** [comment]
Thank you. I tried the following code and it seemed to work in a first test:

```
        gp_Trsf T;
        IfcGeom::MAKE_TYPE_NAME(Kernel) k;
        k.convert(Storey->ObjectPlacement(), T);
        T.Invert();
        Shape = BRepBuilderAPI_Transform(Shape, T).Shape();
```

But I had to include 
```
#define IfcSchema Ifc4
#include <IfcGeom.h>
```
to run it.

I want to keep the code independent from the schema (only runtime decisions). Is it possible to access convert using agnostic geom? IfcGeom::Kernel k and then convert only accepts 1 or 3 arguments (and then segfaults).

**Comment by aothms** [comment]
You can copy the logic from the SvgSerializer: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/serializers/SvgSerializer.cpp#L1118 so use convert_placement() on a Kernel constructed with a reference to the file.

**Comment by fluider** [comment]
Thank you, Thomas. It works great!
