### ISSUE TITLE
Selectors do not allow whitespace for prop(set) names

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#1027]
@Moult 

`pset_or_qto` does not allow whitespace. What are your thoughts on this? It's not unimaginable that whitespace exists, see below for example from Duplex A model:

```
#18867=IFCPROPERTYSET('3EpSZEZKf0rgESpRd9Ot_i',#1,'PSet_Revit_Identity Data',$,(#8230));
                                                                      ^ space
```

* I can imagine ignoring spaces is desired  (https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/util/selector.py#L113)
* And quoting prop names undesired. 
* Maybe one potential work around to just treat spaces|underscores as equivalent when matching here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/util/selector.py#L229

Thoughts? If you don't disagree with my workaround I can implement it.

**Comment by Moult** [comment]
Good idea! Please go ahead!

**Comment by Moult** [comment]
Spaces are now supported
