### ISSUE TITLE
Who uses IfcOpenShell?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1028]
It'd be good to know which players are using IfcOpenShell under the hood. Name dropping would help project some confidence in potential users (and, ahem, investors?) :)

Those I know already:

 - FreeCAD
 - Tridify
 - BlenderBIM Add-on
 - BIMServer
 - BIMSurfer

Guessing perhaps Xeokit? I also read somewhere that Autodesk used IfcOpenShell as a converter for the early days of Forge.

**Comment by xeolabs** [comment]
@Moult yes, xeokit users are using ````IfcConvert```` within their pipelines - full tutorial here: 
https://github.com/xeokit/xeokit-sdk/wiki/Creating-Files-for-Offline-BIM

**Comment by Francois-Thierry** [comment]
We also use IfcOpenShell at [BIMData.io](bimdata.io) to perform a lot of IFC manipulations (3D Conversions, Optimization, Split, Merge, Export...).
We love it, it is awesome !
Thank you so much guys for all the amazing work that you put in it !

**Comment by Moult** [comment]
Fantastic!

@aothms what are your thoughts on a little revamp of the IfcOpenShell.org website to include these logos?

**Comment by klokoy** [comment]
[Areo](http://areo.io/) uses `IfcConvert` within our 3D model pipeline.

**Comment by Doncassino** [comment]
At [TriDyme](https://www.tridyme.com) we are working with it and [code_aster](https://www.code-aster.org/) in order to improve structural analysis integration in BIM process.
Great job!!!

**Comment by Moult** [comment]
@Doncassino have you seen IFC2Code_Aster by @Jesusbill ? https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifc2ca You guys should work together!

**Comment by Doncassino** [comment]
@Moult and @Jesusbill, yes we saw it few weeks ago and we will be happy to work on it.

**Comment by Jesusbill** [comment]
> @Moult and @Jesusbill, yes we saw it few weeks ago and we will be happy to work on it.

Sounds great @Doncassino , let's have a talk soon!

**Comment by jakob-beetz** [comment]
Happy IfcOpenShell user for many years. Many research prototypes.  Thanks for the AMAZING work!
Hope this counts too:
-  Have been using it for years in MSc-education of Architecture, Civil Engineering and Construction & Robotics tracks at RWTH Aachen University and TU Eindhoven. 
-  Will include a Jupyter Notebook with IFCOpenShell in the mandatory bachelor track for 2nd year Arch students starting next summer term to replace desktop edu tool https://github.com/jakob-beetz/IfcOpenShellScriptingTutorial. Will publish notebooks as Open Educational Resource
- Blender / BlenderBIM mandatory for 1st year BSc students of arch in first year. 
-  will be replacing old *cough* Dynamo scripts for semi-automatic model-checking of ~250 proprietary *cough* student models with IfcOpenshellBased modelchecker extending https://github.com/jyrkioraskari/mvdXMLChecker resp. https://github.com/opensourceBIM/mvdXMLChecker. 
- Voluntary use of FreeCAD in assignments. 
- Term research projects for MSc students for "Architectural Informatics" . 
- Recurring

**Comment by Moult** [comment]
@jakob-beetz fantastic! You might be interested in this page: https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples - I use this to train people in IfcOpenShell, it usually takes an hour to go through the crash course whilst explaining IFC concepts. It might be helpful to your IfcOpenShell scripting tutorial!

I use the BlenderBIM Add-on to teach this. I see you've got a custom tool, but thought you might like to know that the BlenderBIM Add-on can also function as this. Instructions are [here](https://wiki.osarch.org/index.php?title=Using_the_Python_console_with_BlenderBIM_Add-on). It supports an Python interactive shell, can run Python scripts, and also comes with batteries included (IfcOpenShell, bcfplugin, fcl for clash detection, OCC, svgwrite, ifcdiff, ifccsv, ifcclash...), and of course is cross platform :)

For the model checker, have you seen [MicroMVDs](https://wiki.osarch.org/index.php?title=Using_MicroMVDs_for_exchange_requirements) ? We've been using them to specify contractual requirements and automatically check them.

**Comment by Moult** [comment]
@jakob-beetz one more thing that may interest you - I've building visual programming nodes for IFC in Blender - https://github.com/IfcOpenShell/IfcOpenShell/issues/1010 - this may be a useful educational tool. Let me know what you think :)

**Comment by SigveMartin** [comment]
We used IfcConvert in the 3D pipeline when we started Rendra (rendra.io). I think it is still in good use there. 

I have also used ifcopenshell python module in courses for BIM technicians [content here](https://github.com/bimfag/intro-python-bim) : and for creating different scripts.

**Comment by aothms** [comment]
https://twitter.com/SigveMartin/status/1314845041207246849

**Comment by aothms** [comment]
Also @juancarlosgermano from https://augin.app/en/ might want to comment.

**Comment by aothms** [comment]
> @aothms what are your thoughts on a little revamp of the IfcOpenShell.org website to include these logos?

My priority is more on use cases and technical examples. I had naively and secretly hoped that logos on the website could be some sort of revenue channel 💰

I find the python.org website reasonable in that sense (although I also feel that their adoption level they don't need to convince people with "control flow" in their language). And I really prefer a cleaner design with less gradients. I can probably publish the repo for the IfcOpenShell.org website. It's flask website (for getting the builds from github API).

**Comment by aothms** [comment]
@johanrd might also want to comment. He has helped tremendously in quality assurance with isolated cases and expected outcomes.

**Comment by aothms** [comment]
@Stinkfist0 and @otsoa if they're still around perhaps...

**Comment by juancarlosgermano** [comment]
@Moult we are happily using IFCOpenShell at Augin (augin.app - augmented reality platform for BIM models), it´s been almost 2 years and these days we process more than 400 ifc models a day. The work of Thomas is amazing, and thanks for his great work with IFCOpenShell we were able to launch Augin. I´m a big fan of this great tool. By the way, @aothms , i will be happy to share IFCOpenSHell logo in augin´s website, in our partner section, please send me the offcial logo by e-mail. Regards to all.

**Comment by otsoa** [comment]
@aothms Yes we do use IfcOpenShell at [Tridify](https://tridify.com)  👍

**Comment by Moult** [comment]
I was trying to find out the "birthdate" of IfcOpenShell, and from the sourceforge history the oldest activity I've found is mid 2011. How close was I, @aothms ? :)

**Comment by aothms** [comment]
Close, that's what I remember as well. I tend to say June 1st but might be
conflating with my own birthday.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 15 okt. 2020 01:38 schreef Dion Moult <notifications@github.com>:

**Comment by johanrd** [comment]
@Moult and @aothms (and everyone, really): **Congrats to BlenderBIM for the buildingSMART awards 2020 for Technology Excellence** :tada:

Also wanted to share that the winner of **Project Delivery Exellence – Construction**, is powered by IfcConvert:) [All contractors in Project Celcius have the IFC model as the top legal contract](https://www.youtube.com/watch?v=T1KWHD6Xh7w), and uses [StreamBIM](https://streambim.com/) to work exclusively with tablets, smartphones and big screens on site. Cheers! :tada:

**Comment by aothms** [comment]
Congrats @johanrd and team! Great work. Thanks for mentioning!

**Comment by aristotls** [comment]
Thanks for the work on IfcOpenShell. We are using IfcOpenShell at Fachhochschule Nordwestschweiz FHNW (University of Applied Sciences and Arts Northwestern Switzerland) in several research projects, currently e.g.
* ifc-data-checker https://github.com/idibau/ifc-data-checker / https://pypi.org/project/ifc-data-checker/ in context to a bim-profile-server
* geodata-transformation-service (transformation of geoservices data to ifc) for the integration of natural hazard data into ifc
* transformation of geological data into ifc

We are also planning to use it in our MSc education in Virtual Design and Construction starting next automn.

**Comment by claimred** [comment]
IfcOpenShell is pretty great, thanks for your hard work. It always is "reference implementation" in my head. At [@rengasoftware](github.com/rengasoftware) we use IfcOpenShell tools internally. Moult [introduced](https://forums.buildingsmart.org/t/cli-tools-to-help-development/2525) them to us on buildingsmart forums.

- @Moult's ifcdiff for automatic CI testing pipeline
- ifcopenshell-python for writing custom testing scenarios
- ifcconvert to quickly visualize things
- ifcopenshell & ifcopenshell-python for research & prototypes

**Comment by Moult** [comment]
Closing bug (which wasn't really a bug!) :) I'd like to invite anybody else who'd like to tell the world that they use and support IfcOpenShell to edit this public wiki page: https://wiki.osarch.org/index.php?title=IfcOpenShell#Softwares_powered_by_ifcopenshell

Maybe we should come up with little button graphics that they can use on their website :)
