### ISSUE TITLE
Asterisk sign problem

### ISSUE THREAD

**Issue by arzezniczak** [IfcOpenShell/IfcOpenShell#103]
Hello.
I have a IFC file from Solibri IFC Optimizer.
[IFC 3_optimized.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/365642/IFC.3_optimized.zip)
I'm trying to read attribute Name from IfcProject instance with code like this:
```cpp
const IfcSchema::IfcRoot *root = static_cast<const IfcSchema::IfcRoot*>(instance /*this is instance with IfcProject*/);
if (root->hasName())
    return root->Name();
```
`root->hasName()` is returning `true` but when I'm calling `root->Name()` I'm getting exception:
```
class IfcParse::IfcInvalidTokenException
Token * at 5248629 invalid string
```

This is how IfcProject instance in this IFC file look like:
`#94908=IFCPROJECT('2MB33tRp9A69zGFxGcIs2R',#8,*,*,*,$,$,(#14),#94769);`
As you can see instead of `$` sign as Name attribute or `IfcLabel`, there is aterisk `*` sign.

In IFC Implementation FAQ I found this:
> The * character encodes so-called omitted parameters.  These are attributes which are defined as a regular explicit attribute in a supertype but redefined as a derived attribute in a subtype (and the record in the IFC file is an instance of the subtype).

I'm thinking where is this Name attribute defined then? Or maybe it's not and that's why this exception is thrown?

**Comment by aothms** [comment]
Hi,

I would advise reporting this issue back to Solibri, or the originating authoring tool in case these issues precede the optimization step.

The asterisk is reserved for cases like this:

~~~
ENTITY IfcGeometricRepresentationContext
 SUPERTYPE OF (ONEOF
	(IfcGeometricRepresentationSubContext))
 SUBTYPE OF (IfcRepresentationContext);
	CoordinateSpaceDimension : IfcDimensionCount;
	Precision : OPTIONAL REAL;
	WorldCoordinateSystem : IfcAxis2Placement;
	TrueNorth : OPTIONAL IfcDirection;
 INVERSE
	HasSubContexts : SET [0:?] OF IfcGeometricRepresentationSubContext FOR ParentContext;
END_ENTITY;

ENTITY IfcGeometricRepresentationSubContext
 SUBTYPE OF (IfcGeometricRepresentationContext);
	ParentContext : IfcGeometricRepresentationContext;
	TargetScale : OPTIONAL IfcPositiveRatioMeasure;
	TargetView : IfcGeometricProjectionEnum;
	UserDefinedTargetView : OPTIONAL IfcLabel;
 DERIVE
	SELF\IfcGeometricRepresentationContext.WorldCoordinateSystem : IfcAxis2Placement := ParentContext.WorldCoordinateSystem;
	SELF\IfcGeometricRepresentationContext.CoordinateSpaceDimension : IfcDimensionCount := ParentContext.CoordinateSpaceDimension;
	SELF\IfcGeometricRepresentationContext.TrueNorth : IfcDirection := NVL(ParentContext.TrueNorth,SELF.WorldCoordinateSystem.P[2]);
	SELF\IfcGeometricRepresentationContext.Precision : REAL := NVL(ParentContext.Precision,1.E-5);
 WHERE
	WR31 : NOT('IFC2X3.IFCGEOMETRICREPRESENTATIONSUBCONTEXT' IN TYPEOF(ParentContext));
	WR32 : (TargetView <> IfcGeometricProjectionEnum.USERDEFINED) OR 
             ((TargetView =  IfcGeometricProjectionEnum.USERDEFINED) AND 
              EXISTS(UserDefinedTargetView));
END_ENTITY;
~~~

I.e on a schema-level, four fields from `IfcGeometricRepresentationContext` are marked as derived in subtype `IfcGeometricRepresentationSubContext`. This only happens in a handful of places in IFC.

On an instance level then an IFC file *has* to have these four attributes marked as derived in the file, e.g:

~~~
#106=IFCGEOMETRICREPRESENTATIONSUBCONTEXT('ADT_Extended_BaseCurve','MODEL',*,*,*,*,#5,$,.MODEL_VIEW.,$);
~~~

In other cases usage of the asterisk is not allowed.

Hope that helps,

Kind regards,
Thomas
