### ISSUE TITLE
Union of IfcRevolvedAreaSolid and IfcExtrudedAreaSolid doesn't work using create_shape

### ISSUE THREAD

**Issue by giovannivelludo** [IfcOpenShell/IfcOpenShell#1034]
The [file](https://github.com/IfcOpenShell/IfcOpenShell/files/5366907/endplate.txt) causing the issue. Other viewers display the section of the difference between two ellipsoids (id 49) correctly. I'm using Blender 2.90.1 and BlenderBIM 200912 on Linux. Debug log:
```
/home/giovanni/.config/blender/2.90/scripts/addons/blenderbim/bim/__init__.py:329
/home/giovanni/.config/blender/2.90/scripts/addons/blenderbim/bim/__init__.py:329
Switching to fully guarded memory allocator.
Blender 2.90.1
Build: 2020-09-29 00:05:18 Linux Release
argv[0] = blender
argv[1] = --debug
Read prefs: /home/giovanni/.config/blender/2.90/config/userpref.blend
read file 
  Version 280 sub 39 date unknown hash unknown
/run/user/1000/gvfs/ non-existent directory
Warning: class BIM_OT_copy_attributes_to_selection contains a property which should be an annotation!
    assign as a type annotation: BIM_OT_copy_attributes_to_selection.prop_base
    assign as a type annotation: BIM_OT_copy_attributes_to_selection.prop_name
    assign as a type annotation: BIM_OT_copy_attributes_to_selection.sub_props
    assign as a type annotation: BIM_OT_copy_attributes_to_selection.collection_element
Warning: class BIM_OT_add_annotation contains a property which should be an annotation!
    assign as a type annotation: BIM_OT_add_annotation.obj_name
    assign as a type annotation: BIM_OT_add_annotation.data_type
Info: Deleted 1 object(s)

Starting import process :: 0.00
Load diff :: 0.00
Purge diffs :: 0.00
Load existing rooted elements :: 0.00
Caching file :: 0.00
Loading file :: 0.00
Setting file :: 0.00
Set vendor worksarounds :: 0.00
Calculate unit scale :: 0.00
Patching ifc :: 0.00
Set units :: 0.00
Create contexts :: 0.00
Create project :: 0.00
Create classifications :: 0.00
Create constraints :: 0.00
Create doc info :: 0.00
Create doc refs :: 0.00
Create spatial hierarchy :: 0.00
Create type products :: 0.00
Create aggregates :: 0.00
Create opening collection :: 0.00
Process element filter :: 0.00
Georeferencing ifc :: 0.00
Creating groups :: 0.00
Creating grids :: 0.00
Creating native products :: 0.00
Creating meshified products :: 0.09
Relating openings :: 0.00
Placing objects in spatial tree :: 0.00
Add project to scene :: 0.00
Mesh cleaning :: 0.00
Import finished in 0.10 seconds
Saved session recovery to '/tmp/quit.blend'

Blender quit
```

**Comment by giovannivelludo** [comment]
In this other [file](https://github.com/IfcOpenShell/IfcOpenShell/files/5367386/051200ALR1A.txt) the same geometry is rendered correctly.

**Comment by Moult** [comment]
I think this issue is best suited for @aothms 

The two files don't seem to be identical. In the file where it works, it is purely a revolved area solid. In the file where it doesn't work, it is a union of a revolved area solid _and_ an extruded area solid. Each of the two sub components of the boolean union can be generated correctly, but the union itself fails.

Here's a screenshot of the subcomponents.

![2020-10-25-165117_662x349_scrot](https://user-images.githubusercontent.com/88302/97099944-a0bb9500-16e2-11eb-8833-8845c8d01c30.png)

**Comment by aothms** [comment]
Indeed, the boolean results fails the subsequent checks we do. I remember issues with this before with periodic curves, that the topology is not entirely correct.

I implemented a quick work-around that in case a union fails we just emit the operands separately as a compound. 

I don't remember the details precisely, but it might be that generic IfcBooleanResult is also not in 2x3 CoordinationView, only the subtype IfcBooleanClippingResult.

**Comment by Moult** [comment]
Thanks @aothms ! Will mark as fixed when bot build is available to verify.

**Comment by giovannivelludo** [comment]
Thanks for fixing this, by the way both IfcBooleanResult and IfcBooleanClippingResult are part of 2x3 CV 2.0

**Comment by Moult** [comment]
Confirming as fixed

![2022-10-01-115628_299x167_scrot](https://user-images.githubusercontent.com/88302/193378603-aad4d83f-a8d2-4004-9152-f28abdd363b3.png)
