### ISSUE TITLE
Convert anomaly finder into IfcPatch recipe

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1041]
https://github.com/AECgeeks/ifc_machine_learning_paper_2015

Coming across that codebase, it could be useful as an automated check to spot oddities in the file. Any objections into me turning it into a utility, perhaps included as a recipe in IfcPatch, IfcDiff, or somewhere where it might belong so that users can easily execute it?

Also, any chance of reading the original paper? It seems to be paywalled?

**Comment by Moult** [comment]
Ping @aothms ?

**Comment by aothms** [comment]
I don't know if it's really production ready for that. It may also be beneficial to train over multiple models, etc. I'll send you the paper. There have also been improvements published by others, that one is open access https://www.sciencedirect.com/science/article/pii/S2288430018300149

**Comment by Moult** [comment]
Cheers. I'll close the issue, but thanks for the paper! When I get a bit more of a mature data-set here, I'll revisit this and see if something comes out of it :)
