### ISSUE TITLE
Differences between hash method and ifcdiff?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1042]
Ping @johltn ! I read your excellent article on http://academy.ifcopenshell.org/calculate-differences-of-ifc-files-with-hashing/

A very similar (if not identical) method is implemented here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcdiff/ifcdiff.py - using my fork of deepdiff as a dependency. Are there any smarts from that paper that can be merged into the IfcDiff utility?

**Comment by johltn** [comment]
Hi @Moult 

Thanks for your message, sure I'll have a look and compare both approaches.

**Comment by EAzari** [comment]
@johltn good to see your both recent articles are about "compression algorithms"
Good start to improve IfcOpenShell and BlenderBIM

CC: @aothms @Moult

**Comment by aothms** [comment]
I don't know how deepdiff is implemented, but by using hashes we can compare "sets" of elements efficiently. It's essentially comparing "forests", sets of trees (where the IFC graph of resource values is expanded into a tree, but that is fine, it doesn't make a semantic difference). Even when we eliminate the GlobalId values from the data it can recover identical elements from two models.

**Comment by EAzari** [comment]
@aothms haha, I like what you think :) as you know in the computer graphics exactly the example is a forest and its trees ;)
Also, the hash table let's has access to data everywhere inside the tree
This is one of the reasons I believe IFC is designed badly, because has a deep tree, and the shallow tree is better

**Comment by Moult** [comment]
@aothms yes, I believe the premise is the same. The deepdiff library has a a sublib called deephash (which you can trigger if you want to see the hashes themselves). [deepdiff seems to use deephash](https://github.com/seperman/deepdiff/blob/master/deepdiff/diff.py#L233-L249) and seems to provide a wrapper with a [ton of options](https://github.com/seperman/deepdiff/blob/master/deepdiff/diff.py#L104-L141). Some of these are quite useful - especially callbacks and the exclude regex paths - the ones I think are useful are then re-exposed to the user in ifcdiff. The excludes are used to eliminate step IDs, and user configurable things like owner histories.

I guess my question was whether there were differences I've missed, or whether any more convenience functions or optimisations could be added to ifcdiff borrowing from the smarts in @johltn 's approach.
