### ISSUE TITLE
Conda builds don't include IfcOpenShell util module

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1044]
Reported by user here: https://community.osarch.org/discussion/264/ifcopenshell-util-not-found

@aothms can I help fix this? How?

**Comment by aothms** [comment]
I see there is some activity on the repo two days ago https://github.com/conda-forge/ifcopenshell-feedstock/commits/master maybe check again?

**Comment by eibre** [comment]
After a fresh install it seems to work! Thanks
