### ISSUE TITLE
BlenderBIM: Flipping between drawings doesn't work then in isolate mode (that is using the "/" Key)

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1048]
Flipping between drawings doesn't work then in isolate mode (that is using the "/" Key)
![image](https://user-images.githubusercontent.com/507113/97246089-82c95f80-17ca-11eb-9e7a-ecb35f95159b.png)

**Comment by Moult** [comment]
Just to make sure I understand, can you record or screenshare?

**Comment by theoryshaw** [comment]
Sure.
https://www.dropbox.com/s/sxu5krnuswwn9jm/2020-10-28_10-17-10.mp4?dl=0

**Comment by Moult** [comment]
Note to self: https://devtalk.blender.org/t/solved-adding-new-objects-from-python-while-in-local-view/4703
