### ISSUE TITLE
BlenderBIM: order the drawings alphabetically 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1049]
Possible to order the drawings alphabetically? Helps organize things when there's a lot of drawings.

![image](https://user-images.githubusercontent.com/507113/97250916-ee182f00-17d4-11eb-843f-c55b11ce35a6.png)

**Comment by Moult** [comment]
Note to self: https://sinestesia.co/blog/tutorials/amazing-uilists-in-blender/

I think Blender has alphabetical sorting built-in :)

![2020-10-27-185911_243x178_scrot](https://user-images.githubusercontent.com/88302/97272891-a651e000-1886-11eb-854c-7e905e1b7e25.png)

**Comment by theoryshaw** [comment]
Ha... noobie in the house.
