### ISSUE TITLE
leftover WARNING from #99

### ISSUE THREAD

**Issue by iras** [IfcOpenShell/IfcOpenShell#105]
Hi,

just reminding there was a last warning while compiling with gcc from #99.

`[ 97%] Building CXX object ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o
/home/i/git/IfcTest/src/ifcgeomserver/IfcGeomServer.cpp: In instantiation of ‘T sread(std::istream&) [with T = int; std::istream = std::basic_istream<char>]’:
/home/i/git/IfcTest/src/ifcgeomserver/IfcGeomServer.cpp:58:32:   required from here
/home/i/git/IfcTest/src/ifcgeomserver/IfcGeomServer.cpp:53:18: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  return *((T*)buf);
                  ^
/home/i/git/IfcTest/src/ifcgeomserver/IfcGeomServer.cpp: In instantiation of ‘T sread(std::istream&) [with T = double; std::istream = std::basic_istream<char>]’:
/home/i/git/IfcTest/src/ifcgeomserver/IfcGeomServer.cpp:299:32:   required from here
/home/i/git/IfcTest/src/ifcgeomserver/IfcGeomServer.cpp:53:18: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/home/i/git/IfcTest/src/ifcgeomserver/IfcGeomServer.cpp: In instantiation of ‘T sread(std::istream&) [with T = unsigned int; std::istream = std::basic_istream<char>]’:
/home/i/git/IfcTest/src/ifcgeomserver/IfcGeomServer.cpp:315:26:   required from here
/home/i/git/IfcTest/src/ifcgeomserver/IfcGeomServer.cpp:53:18: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
`

**Comment by Stinkfist0** [comment]
There's probably no need for issues for compiler warnings, there are maybe also 4 left on MSVC too.

**Comment by aothms** [comment]
Ok, I don't get this warning, but I guess it should be resolved to work around any potential alignment/aliasing issues. Does it go away by using a union?

~~~
template <typename T>
union data_field {
	char buffer[sizeof(T)];
	T value;
};

template <typename T>
T sread(std::istream& s) {
	data_field<T> data;
	s.read(data.buffer, sizeof(T));
	return data.value;
}
~~~

**Comment by iras** [comment]
Yes it does go away by using a union. 👍

**Comment by iras** [comment]
See #108.

By the way, how do you bing a new pull request to an existing issue?

**Comment by aothms** [comment]
Ok, good to hear.

Not sure about the specifics, but I think if you type something like `Fixes #{issue nr}` somewhere in the pull request description, the issue will be closed automatically when the pull request is merged.

**Comment by aothms** [comment]
Writing `Fixes #{issue nr}` in a comment didn't do the trick though.
