### ISSUE TITLE
Segfault with IfcConvert

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1054]
I'm generating a lot of IFC files, possibly they are not all 100% valid, but these three reliably produce a segfault with IfcConvert: [segfault.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5454714/segfault.zip)

    $ IfcConvert tmp8st03n9y.ifc tmp8st03n9y.ifc.dae
    IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.4.0.beta)
    Scanning file...
    Done scanning file   
    Parsing input file took 0 seconds
    Creating geometry...
    [#######################################           ]Segmentation fault (core dumped)

    $ IfcConvert tmpfs3_2dtk.ifc tmpfs3_2dtk.ifc.dae
    IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.4.0.beta)
    Scanning file...
    Done scanning file   
    Parsing input file took 0 seconds
    Creating geometry...
    [################################################# ]Segmentation fault (core dumped)

    $ IfcConvert tmp_xihyy8a.ifc tmp_xihyy8a.ifc.dae
    IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.4.0.beta)
    Scanning file...
    Done scanning file   
    Parsing input file took 0 seconds
    Creating geometry...
    [##########################################        ]Segmentation fault (core dumped)

Linux, v0.6.0 git snapshot, opencascade 7.4.0

**Comment by aothms** [comment]
There are things like `#8787=IFCCARTESIANPOINT()` where the attribute count is wrong. This caused uninitialised reads. This is fixed now. Thanks for the report.

**Comment by Moult** [comment]
Tested and confirmed fixed.
