### ISSUE TITLE
Source code compilation

### ISSUE THREAD

**Issue by whwlei** [IfcOpenShell/IfcOpenShell#1055]
parse_ifcxml.cpp:7:27: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
                           ^
Libxml2 is already installed

[root@localhost libxml2-2.9.4]# find / -name "parser.h"
/usr/include/libxml2/libxml/parser.h
/usr/local/include/libxml2/libxml/parser.h
/usr/local/libxml2-2.9.4/include/libxml/parser.h

**Comment by aothms** [comment]
Yes that's a bit of an open issue in the cmake configuration. My recommendation is to add `-DIFCXML_SUPPORT=Off` when invoking cmake.

**Comment by whwlei** [comment]
At present, make -j cannot be completed in the environment of ubuntu14.4 and centos 7.6 according to the documentation

**Comment by aothms** [comment]
ubuntu 14.4 is six years old. I don't think it's an immense effort to make it work, we also had to support a recent old gcc on OSX for a long time. The v0.6.0 is just C++11. 

Travis has been on 16 for a long time, but recently upgraded to 18. https://github.com/IfcOpenShell/IfcOpenShell/commit/8f43a65b74b96d461b367527ee46924fe3d81042#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485 I think 16 would still work, it was mostly for the dependencies IIRC.

Personally I'm on 18 and occasionally use 20.

Do you need ubuntu 14? I'd be happy to assist in ironing out the issues if you take the lead, but I don't have the time to take the initiative on this.

**Comment by whwlei** [comment]
We are mainly developing under the environment of centos7.6. I can solve related problems in this environment. Can you support me, thank you

**Comment by aothms** [comment]
Sure, just past the build errors here and we'll resolve them. In the end it'd be great if you can submit the fixes as a Pull Request.

**Comment by whwlei** [comment]
After the repair is complete, I will submit the repair program.
