### ISSUE TITLE
BlenderBIM: error while activating different 'drawing styles'

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1056]
video: https://www.dropbox.com/s/ape52s908hnpueg/2020-10-28_23-34-33.mp4?dl=0

**Comment by theoryshaw** [comment]
Unfortunately, that didn't seem to work on my end
https://www.dropbox.com/s/m808kpufiro3zgf/2020-10-29_01-07-50.mp4?dl=0

**Comment by Moult** [comment]
This is what happens when you commit code before even re-reading it :)

**Comment by theoryshaw** [comment]
Unfortunately, that still doesn't seem to work on my side.

**Comment by theoryshaw** [comment]
I take that back, operator error.
