### ISSUE TITLE
How to use the units utils?

### ISSUE THREAD

**Issue by sharon-br** [IfcOpenShell/IfcOpenShell#1058]
Hey,
I'm having trouble understanding how to use the units converter under the ifcopenshell.util.unit module
I tried reading the logic and also using it with some examples but none of it made sense to me - is there some code example for this?

The main usage for me is to get the units in the context in the IfcProject file, and when I iterate over my IFC file and get the BaseQuenenties to convert the length, area, and volume from the IFC units to feet, square feet, and cubic feet.

Another question it that topic that might not be related in a straightforward way is that in one of the IFC files I have the only object I get in the UnitsInContext.Units is: `(#25=IfcConversionBasedUnit(#26,.LENGTHUNIT.,'inch',#27),)`
How should I treat that? If I query for the SI units like this: `f1.by_type('ifcsiunit')` I do get some objects but looks like they are not related to the IfcProject itself.

Thanks.

**Comment by Moult** [comment]
I hear that in a future version of IFC, units will be removed, and this'll make life easier... but until then...

The code in the util unit may need cleaning or improvement to handle more cases (see below). Suggestions are welcome!

You are correct that the way to find units is checking `UnitsInContext.Units`. You'll loop through that, and `LENGTHUNIT` will provide length units, `AREAUNIT` for areas, etc.

Once you've found the unit (we'll call `foo`), let's say `LENGTHUNIT`, there are two options:

 1. It is an `IfcSIUnit`. In this case, use `ifcopenshell.util.unit.get_prefix_multiplier(foo.Prefix)`. That will give you the value to multiply by to convert to meters.
 2. It is an `IfcConversionBasedUnit`. In this case, use `foo.ConversionFactor.ValueComponent.wrappedValue` to figure out the conversion.
 3. It is something else, like money / derived / conversion based with an offset. I haven't written code for this yet, but will need to.

To handle conversions, you can use `ifcopenshell.util.unit.convert`.

```
def convert(value, from_prefix, from_unit, to_prefix, to_unit):
    """Converts between length, area, and volume units

    :param value: The numeric value you want to convert
    :type value: float
    :param from_prefix: A prefix from IfcSIPrefix. Can be None.
    :type from_prefix: string
    :param from_unit: IfcSIUnitName or IfcConversionBasedUnit.Name
    :type from_unit: string
    :param to_prefix: A prefix from IfcSIPrefix. Can be None.
    :type to_prefix: string
    :param to_unit: IfcSIUnitName or IfcConversionBasedUnit.Name
    :type to_unit: string
    """
```

**Comment by sharon-br** [comment]
What should I do in the case where I find IfcConversionBasedUnit for the length unit, but there is no unit for area and volume, how should I approach that?

**Comment by Moult** [comment]
@sharon-br if there is no defined unit for area or volume, and yet area or volume measurements existing the file, then the unit is undefined. I think you can do whatever you want in this scenario and nothing is strictly more correct than the other.

I could be wrong about this, so if somebody finds a strict rule in the spec please let me know.

In the spec, I couldn't find an explicit definition for `Q_LENGTH`, `Q_AREA` and `Q_VOLUME`, but there is `IfcLengthMeasure`, `IfcAreaMeasure`, and `IfcVolumeMeasure` which has a note saying units are usually mm, m2, and m3 respectively. I think that's the most "official" hint I can find of how to treat this situation.
