### ISSUE TITLE
IfcConvert feature request: Option to preserve IFC GUID in .glb output

### ISSUE THREAD

**Issue by jensmtg** [IfcOpenShell/IfcOpenShell#1059]
I'm trying to make 3D viewer where clicking elements can present information about the given element from an `.xml` derived from the same ifc, but the `.glb` data uses a different set of identificators. (Full length uuids instead of compressed ifc guids.)

**Comment by aothms** [comment]
This exists. That's `--use-element-guids`.

**Comment by jensmtg** [comment]
You're right. Not sure how i missed that... Well, great news anyway!

**Comment by Moult** [comment]
Closed as resolved.
