### ISSUE TITLE
BlenderBIM: Qto quantities update in the background

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1061]
Would be nice if the Qto quantities updated in the background, verses manually refreshing them.

**Comment by Moult** [comment]
The way I currently know how to do this is a bit expensive. I've asked the community if there is a better approach: https://blenderartists.org/t/how-to-run-python-code-when-object-is-edited/1263651

**Comment by Moult** [comment]
An update that in the future, there will be an explicit "Edit Geometry" operation in Blender so that IFC authoring happens on-the-fly. The trigger for edit geometry will also solve this issue. This'll take a little while to occur, so don't hold your breath.

**Comment by Moult** [comment]
Bump that the "Edit geometry" operation is now explicit, so this now becomes possible to do. Haven't done it yet, though :)

**Comment by ChubbyQuark** [comment]
Would this also allow a report window in Blender to display a dynamic list of filtered and/or grouped IFCelements? Is there a Bounty Source set up for this?

**Comment by Moult** [comment]
@ChubbyQuark currently there is no spreadsheet feature available in the stable release of Blender. When Blender's built-in spreadsheet becomes stable, we will definitely integrate. For now, you can use the IFCCSV tool, found in the scene properties.

**Comment by ChubbyQuark** [comment]
Amazing, didn't realise that feature was under development. 

IFCCSV export is really useful, is it possible to also export the IFC class values? I've only managed to export IFC attribute values.

**Comment by ChubbyQuark** [comment]
Just checked the 2.93 experimental build and currently the spreadsheets feature only allows querying of individual meshes. Do you think this can be customised so multiple meshes or objects can be queried and grouped by properties?

**Comment by Moult** [comment]
@ChubbyQuark you can use the "type" attribute to export the class. I really should document all this. Perhaps you can help document?

As for the experimental builds I think what is shown in the UI might be different to how it is exposed via Python. I haven't had time to look at this yet. Perhaps @ecke101 has looked at it :)

**Comment by ChubbyQuark** [comment]
More than happy to help document! I'm trying to understand and learn the UI, processes and workflows using test files and live, non critical projects. What format and where would be best to host the documentation?

**Comment by Moult** [comment]
@ChubbyQuark if you'd like to document "a bit here, a bit there", for now, a great place to put information is on https://wiki.osarch.org/

However, if you're up for taking a serious role in documentation, and creating official documentation, this involves you really becoming a BlenderBIM Add-on power user and writing docs that others can rely on as a source of truth. This will be best documented in https://ifcopenshell.github.io/docs/ . This requires dedication from your end, but I will be happy to support :)

**Comment by ChubbyQuark** [comment]
I'll start with the Wiki which will give me time to gain a deeper understanding of BlenderBIM and OpenShell.  I'm keen to devote as much time as possible and help out where I can. Really admire the work the community is doing on this.

**Comment by Moult** [comment]
... and happy to announce that this is now fully possible. I've implemented some basic quantities for walls now: https://github.com/IfcOpenShell/IfcOpenShell/commit/bfe9213f67daee1fb235ea385e8173a6ee6bda31

Other object types will be slowly implemented as I get around to them (walls first, probably slabs next, then columns/beams, then doors/windows is my predicted todo list).

**Comment by ChubbyQuark** [comment]
Great news and fantastic work.

I've got a build from a couple of days ago but will update to the latest.

Regarding documentation, what's the best way to track current and most
useful features to document? Conscious I could he chasing my tail due to
the rapid development of the addon.

**Comment by Moult** [comment]
Development is rapid in some aspects but not others.I think we can find a strategy to prevent chasing updates :)
