### ISSUE TITLE
BlenderBIM: UI suggestion for bring up camera object.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1062]
A UI suggest for bringing up camera panel. 

I go to the camera object a lot, and this would help.

![image](https://user-images.githubusercontent.com/507113/97663190-e364d080-1a46-11eb-9d45-554a2e64bf3e.png)

**Comment by Moult** [comment]
Awesome work by @htlcnn ! Closing bug as fixed!
