### ISSUE TITLE
BlenderBIM fails to open IFC4 file

### ISSUE THREAD

**Issue by DuncanLithgow** [IfcOpenShell/IfcOpenShell#1065]
Blender 2.9.2 with BlenderBIM Add-on 201025 fails to open this file
http://openifcmodel.cs.auckland.ac.nz/Model/Details/348

Fails only the first time. On subsequent tries it goes fine. I've seen this happen a few times. If someone would just check this it might be my weak system that's the problem.

**Comment by Moult** [comment]
Could not replicate :)
