### ISSUE TITLE
Mising subtractions for beam (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#1076]
1. Convert [1076--beam--missingSubtraction.ifc](https://github.com/IfcOpenShell/files/blob/master/1076--beam--missingSubtraction.ifc) with 96b8bc638b82f3d9583aaebcd8d8a0e338a67009 (or any other version) (OCCT 7.3.0p4), and experience failing opening subtraction:
``` 
#7=IfcBeam('3rBoW2CGT9ee8hHrIsM3Dt',#8,'','','',#454,#13,'')
[Warning] {3rBoW2CGT9ee8hHrIsM3Dt} Subtraction yields unchanged volume:
#25=IfcBooleanResult(.DIFFERENCE.,#31,#353)
[Error] Triangulation missing for face
[Error] Triangulation missing for face
```
<img width="81" alt="Screenshot 2020-11-04 at 15 31 25" src="https://user-images.githubusercontent.com/4601554/98124238-36a9a980-1eb3-11eb-9093-db1b6c4c56f8.png">

2. Expected geometry from Solibri:
<img width="81" alt="Screenshot 2020-11-04 at 15 35 05" src="https://user-images.githubusercontent.com/4601554/98124335-58a32c00-1eb3-11eb-96ab-7b201fc00079.png">

**Comment by Moult** [comment]
Seems fixed in latest :) Closing

![2022-10-01-114721_557x420_scrot](https://user-images.githubusercontent.com/88302/193378350-e1fb5b6e-4a96-4457-b484-415baf583071.png)
