### ISSUE TITLE
Code licensing

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1082]
IfcOpenShell itself is LGPL-3, but I think that doesn't work for some of the subcomponents, as some of the components have additional dependencies. For example, I _think_ (not sure, I'm not a lawyer) the BlenderBIM Add-on needs to become GPL-3 or later (see [compatibility matrix](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility)) because it uses some GPL-3 code.

I thought I'd try to work it out here:

 - ifcopenshell-python: lark (MIT) **Result: LGPL-3**
 - ifc2ca: numpy (BSD-3) **Result: LGPL-3**
 - ifcbimtester: behave (BSD-2), pystache (MIT) **Result: LGPL-3**
 - ifcclash: code taken from trimesh (MIT), numpy (BSD-3), fcl (BSD-3) **Result: LGPL-3**
 - ifccobie: odfpy (GPL-2 or later, or Apache v2), xlswriter (BSD) **Result: GPL-2 or later**
 - ifccsv: nothing? **Result: LGPL-3**
 - ifcdiff: deepdiff (MIT) **Result: LGPL-3**
 - ifcpatch: nothing I think, depends on the recipe.  **Result: LGPL-3**
 - ifcsverchok (GPL-3) **Result: GPL-3**
 - blenderbim: bpy (GPL-2 or later?), taken some code from MeasureIt (GPL-3 or later) **Result: GPL-3**

I don't know about the C++ modules like IfcConvert, or IfcMax.

Thoughts? Am I totally confused about this license stuff? If this makes sense and people agree with the resulting license, I think this should be documented somewhere in case people have questions.

Progress:

- [x] bcf
- [x] blenderbim
- [x] bsdd
- [x] ifc2ca
- [x] ifc4d
- [x] ifc5d
- [x] ifcbimtester
- [x] ifcblender
- [x] ifccityjson
- [x] ifcclash
- [x] ifccobie
- [ ] ifcconvert
- [x] ifccsv
- [x] ifcdiff
- [x] ifcfm
- [ ] ifcgeom
- [ ] ifcgeom_schema_agnostic
- [ ] ifcgeomserver
- [ ] ifcjni
- [ ] ifcmax
- [x] ifcopenshell-python
- [ ] ifcparse
- [x] ifcpatch
- [x] ifcsverchok
- [ ] ifcwrap
- [ ] qtviewer
- [ ] serializers

**Comment by CyrilWaechter** [comment]
According to [GPL FAQ](http://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) I think ifccopie result is also LGPL-3.
The rest looks ok to me.

**Comment by Moult** [comment]
Ping @aothms 

I just read this page: https://www.gnu.org/licenses/identify-licenses-clearly.html - does this mean we should explicitly pick "only" or "or later"? I assume we want to pick "or later" as much as possible?

Also, in this PR: https://github.com/IfcOpenShell/IfcOpenShell/pull/1122 @berndhahnebach adds some license headers. @aothms  what is your opinion on per-file license headers? I personally have not ever used them as I personally find the headers unnecessarily repetitive. However, I see that you've used them (but some files are missing them), and I can see arguments for using them.

If we do want to use them, can we standardise on the format? E.g. right now it talks about LGPL or later, but we need to be careful to say "GPL or later" for the BlenderBIM Add-on code.

Also, I noticed that in the PR: https://github.com/IfcOpenShell/IfcOpenShell/pull/1122/files - @berndhahnebach has actually added in names of authors and email addresses. What's the reason for this? Do we need it? (by the way, in the PR it mentions FreeCAD, that should probably be removed?)

**Comment by berndhahnebach** [comment]
> by the way, in the PR it mentions FreeCAD, that should probably be removed?)

https://github.com/IfcOpenShell/IfcOpenShell/pull/1123

**Comment by berndhahnebach** [comment]
It is just the way it is done in FreeCAD. I am fine with everything, even remove them at all. 

BTW: in the new bimtester header it states Version 2 or later. Should this be explicit Version 3?

cheers bernd

**Comment by aothms** [comment]
I agree, LGPL-3.0-or-later is probably the sanest choice.

I tend to agree that author information in source files is typically unneeded. We have this information in git and that somebody wrote something in the past is not a real indication that he wants to be bothered with it later.

**Comment by berndhahnebach** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/pull/1125

**Comment by Moult** [comment]
To wrap this up, can I propose adding a "LICENSE" or "COPYING" (which is your preference?) file to each dir in `src/` with the relevant license, and then adding a license table in the top level readme?

**Comment by aothms** [comment]
LICENSE appears to me as a bit more modern. It's also what Github creates for you when you select a license during creation of a new repo https://github.com/aothms/test

**Comment by pachi** [comment]
Take into consideration that, for GNU licenses, the preferred file name for licenses is COPYING or COPYING:LESSER, by https://www.gnu.org/licenses/gpl-howto.html and a reference to this files may appear in the license content or existing headers.
This makes some sense, as copyleft licenses are designed around copy rights and not use rights (in the same way as many commercial licenses do).

**Comment by Moult** [comment]
Resurrecting this issue in my occasional attempt to purge out old bugs :)

I've been following the steps described here: https://www.gnu.org/licenses/gpl-howto.html - as such I've decided to follow their recommendations to the letter. Here are the steps I'm following:

 1. Get a copyright disclaimer from your employer or school. <-- hey, probably a good idea!
 1. Give each file the proper copyright notices. Make sure to clearly identify which versions of the license users can use. <-- Hmm, as much as I don't like them, there seems to be a legal reason to do so, in particular that is where the license is actually stated, and clarified which package the source file actually belongs to: "The way developers state their choice is in the license notice that goes at the start of each source file. That's where the GPL says the decision is stated."
 1. Add a COPYING file with a copy of the GNU GPL or GNU AGPL. <-- Done!
 1. Also add a COPYING.LESSER file with a copy of the GNU LGPL, if you use that. <-- Done!
 1. Put a license notice in each file. <-- This is a bit confusing and muddled up with step 2. Basically two things need to be put in each file, a copyright notice, and a license notice. The copyright notice includes some dates and the name of one or more copyright holders. If we wanted we could include the names of all git contributors for that file. However, reading this https://www.gnu.org/prep/maintain/maintain.html#Copyright-Notices suggests that we can have a "main" copyright holder. Therefore I propose to make @aothms the default copyright holder for all the main stuff, I'll be the default copyright holder for blenderbim/utils, and @LaurensJN for CityJSON, @Jesusbill  for ifc2ca, @TestPrab for bcf etc. Then, if anybody makes any significant contributions to that file, they can add themselves if they want. If someone creates a new file, they default as the copyright holder as expected.
 1. (Optionally) make the program display a startup notice. <-- Eh.
 1. (If using the AGPL) make the program offer copies of its source code. <-- Not applicable.

So I've put the COPYING/COPYING.LESSER and updated the readme, so now we just need a sweep of all source files to check for the copyright statement and the license statement.

By the way, in my commit I did a diff with the existing COPYING and the one provided on the GNU site (e.g. https://www.gnu.org/licenses/lgpl-3.0.txt ) just to double check, and noticed that the official one uses https, so I tweaked it.

Let me know what you guys think, and if it all looks good, we can begin the per-file sweep.

**Comment by aothms** [comment]
Looks good to me, there are tools to help with these kind of things, but I'm not sure how well they work https://github.com/cloudposse/copyright-header

**Comment by Moult** [comment]
A bit more reading which I found useful. I am not a lawyer, so following FSF's recommendations to the letter seems to be safest decision :)

 - https://www.gnu.org/licenses/gpl-faq.html#LicenseCopyOnly
 - https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile

**Comment by Moult** [comment]
I made a start on this and the top post now has a todo list. In particular:

 - @Jesusbill can you confirm full name and email for the header for ifc2ca?
 - @LaurensJN can you confirm full name and email for the header for ifccityjson?
 - @aothms I'm not looking at the C++ code, but I've included those dirs in the checklist anyway so we can make sure we are comprehensive.

I used the copyright-header script suggested by @aothms . Here's a sample command for those who want to get started, which will insert LGPL3-or-later recursively from the current working directory:

```
$ copyright-header --license LGPL3 --copyright-holder "Dion Moult <dion@thinkmoult.com>" --copyright-year "2021" --copyright-software bSDD --copyright-software-description "Python bSDD library" -a ./ -o ./
```

**Comment by Jesusbill** [comment]
@Moult great work. My reference is: Ioannis P. Christovasilis<ipc@aethereng.com>

**Comment by LaurensJN** [comment]
@Moult Looks all good! My full name is Laurens J.N. Oostwegel <l.oostwegel@gmail.com>

**Comment by Moult** [comment]
@aothms I noticed the existing boilerplate in C++ and IfcOpenShell python (e.g. [this](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblender/io_import_scene_ifc/__init__.py)) contains license, but not copyright. I assume we should add a copyright like "Copyright (C) 2011, 2012, 2013, 2104 ... 2020, 2021 Thomas Krijnen <foo@bar.com>".

I'm a little hesitant to write a script for this because I'm afraid of borking C++ code even if it is just comments, and I suspect some files are generated perhaps? Let me know how you think I should proceed.

I'm holding off on BCF and OpenCDE stuff for the moment until GSoC calms down, and and will address ifcopenshell-python when I know how to properly add your copyright :)

**Comment by Moult** [comment]
Pinging @myoualid @Jesusbill  @Gorgious56 @qwiglydee  feel free to add yourself to the copyright anywhere you wish :) I just ran a blanket license insertion on the BlenderBIM Add-on codebase, which unfortunately lacks the fidelity of giving credits on the particular portions you guys are hacking on, so please don't hesitate to fix!

**Comment by qwiglydee** [comment]
@Moult i ain't hacking with it anymore. 😕
i can't even find my code...

**Comment by Moult** [comment]
@qwiglydee no worries :) Most of your code (if not all) I think is now here: https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/blenderbim/blenderbim/bim/module/drawing - if you'd like, I can add your name on your behalf to the code I recognise that you worked on. If you're ok with this, let me know full name / email you'd like in the format of "John Doe <john@doe.com>" :)

**Comment by qwiglydee** [comment]
@Moult my code seems only be in `annotation.py`, `decoration.py`, `gizmos.py`, `shaders.py`.
I'm ok with my brand-name QwiglyDee `<qwiglydee@gmail.com>` or "Maxim Vasilyev" if you need real names anyway.
Thanks.

**Comment by Moult** [comment]
Bump :)

https://github.com/IfcOpenShell/IfcOpenShell/issues/1082#issuecomment-899871148

**Comment by aothms** [comment]
> and I suspect some files are generated perhaps?

Yes, maybe we need to differentiate these more clearly? No copyright on those? A more easily distinguishable header to state that people shouldn't make changes to these? Or maybe we should just remove them from the repo. If we allow python as a compile time dependency we can generate them on the fly from cmake as custom targets.

> and and will address ifcopenshell-python when I know how to properly add your copyright :)

- [ ] @Moult If you have the script setup it'd be great if you can process it as "Thomas Krijnen" <thomas@aecgeeks.com>
- [ ] @aothms will take care of the C++ stuff. Just with `sed -i` probably.
- [ ] @aothms For 0.7 I will probably remove the generated files from the repo.

**Comment by Moult** [comment]
For the record this incantation can strip the existing copyright headers if necessary.

```
find . -type f -exec perl -pi -0777 -e 's/#{79}[^\^]+?#{79}//m' {} \;
```

**Comment by Moult** [comment]
I've finished everything Python. I left the ids.xsd untouched. Your name is on everything except for api/util. If there are exceptions we can fix it up as we go along :)

I'm happy to close this bug, I reckon everything at least has copyright headers covered now. The C++ could be improved with a name and date (In the future, I should write a little script that updates the dates based on Git history), but not a big issue I reckon :)

Oh and that Perl multiline regex (-0777) can also perhaps help if you want to do any C++ replacements.
