### ISSUE TITLE
Ifcopenshell master compile problem in centos 7.6

### ISSUE THREAD

**Issue by whwlei** [IfcOpenShell/IfcOpenShell#1084]
**hi, Thomas Krijnen
      I have installed cmake-3.6.2, gcc 4.8.5, g++ 4.8.5, boost 1.53, OpenCOLLADA 1.6.68, opencascade-7.4.0 in the environment of centos 7.6, and when compiling Ifcopenshell, the following error appears:**

/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp: In member function ‘virtual void SvgSerializer::write(const IfcGeom::BRepElement<double, double>*)’:
/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp:378:29: error: ‘class boost::optional<std::vector<boost::variant<horizontal_plan, horizontal_plan_at_element, vertical_section> > >’ has no member named ‘emplace’
      deferred_section_data_.emplace();
                             ^
/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp: In member function ‘void SvgSerializer::write(const geometry_data&)’:
/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp:415:96: warning: missing initializer for member ‘horizontal_plan::next_elevation’ [-Wmissing-field-initializers]
    section_heights_storage.push_back(horizontal_plan{ data.storey, data.storey_elevation,  +1. });
                                                                                                ^
/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp:464:22: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
   if (operation_type && (*operation_type == "SINGLE_SWING_LEFT") || (*operation_type == "SINGLE_SWING_RIGHT")) {
                      ^
/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp: In member function ‘void SvgSerializer::setSectionHeight(double, IfcUtil::IfcBaseEntity*)’:
/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp:1145:16: error: ‘class boost::optional<std::vector<boost::variant<horizontal_plan, horizontal_plan_at_element, vertical_section> > >’ has no member named ‘emplace’
  section_data_.emplace();
                ^
/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp: In member function ‘void SvgSerializer::setSectionHeightsFromStoreys(double)’:
/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp:1151:16: error: ‘class boost::optional<std::vector<boost::variant<horizontal_plan, horizontal_plan_at_element, vertical_section> > >’ has no member named ‘emplace’
  section_data_.emplace();
                ^
[ 88%] Building CXX object CMakeFiles/Serializers.dir/home/wanglei/ifcdev/IfcOpenShell/src/serializers/XmlSerializer.cpp.o
[ 89%] Building CXX object CMakeFiles/Serializers.dir/home/wanglei/ifcdev/IfcOpenShell/src/serializers/util.cpp.o
make[2]: *** [CMakeFiles/Serializers.dir/home/wanglei/ifcdev/IfcOpenShell/src/serializers/SvgSerializer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Serializers.dir/all] Error 2
make: *** [all] Error 2

**If you use boost_1_74, the following error occurs:**
CMakeFiles/IfcConvert.dir/home/wanglei/ifcdev/IfcOpenShell/src/ifcconvert/IfcConvert.cpp.o：在函数‘__gnu_cxx::__normal_iterator<char const*, std::string> boost::re_detail_107400::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::string>, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::re_detail_107400::re_set_long<unsigned int> const*, boost::re_detail_107400::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)’中：
IfcConvert.cpp:(.text._ZN5boost16re_detail_10740016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcSsEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SB_SB_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10740016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcSsEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SB_SB_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x17c)：对‘boost::re_detail_107400::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const’未定义的引用
IfcConvert.cpp:(.text._ZN5boost16re_detail_10740016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcSsEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SB_SB_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10740016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcSsEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SB_SB_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x473)：对‘boost::re_detail_107400::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [IfcConvert] 错误 1
make[1]: *** [CMakeFiles/IfcConvert.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 99%] Linking CXX shared module _ifcopenshell_wrapper.so

**Comment by tpaviot** [comment]
Try upgrading boost to 1.57 or newer

**Comment by aothms** [comment]
> If you use boost_1_74, the following error occurs:

> __gnu_cxx17__normal_iterator

How did you install boost 1 74 then? Seems to be some incompatibility in C++ abi.

**Comment by whwlei** [comment]
Because the version of cmake does not match the version of boost, it has been modified to boost 1.60 and cmake 3.6.2, and the compilation is successful
