### ISSUE TITLE
continuous integration, delivery

### ISSUE THREAD

**Issue by tpaviot** [IfcOpenShell/IfcOpenShell#1087]
At pythonocc, we moved to the MS azure solution to test builds for linux/osx/win. I used to work with both travis/appveyor (before travis add missing windows support and appveyor add pissins osx/linux support) for years, but MS azure quickly appeared to be highly superior in terms of performances (speed, timeout), user interface, monitoring, settings etc.

on my ifcopenshell fork, I created a branch on top of ````v0.6.0```` named ```azure-ci``` (https://github.com/tpaviot/IfcOpenShell/tree/azure-ci) that adds MS Azure support. Build ogs are at https://dev.azure.com/tpaviot/ifcopenshell/_build

This branch relies on an update of the conda recipe as well as the cmake files.

This is a work in progress, I will hopefully open a PR when all configuration options can be built (ifcxml, collada support, json etc.)

**Comment by aothms** [comment]
This looks amazing. Let me know where I can pitch in.

**Comment by tpaviot** [comment]
Work is going on quicky, everything is almost completed. I still have to fix the Windows build (an issue with dynamic libraries I guess, python cannot load the ifcopenshell module), and enable ifcxml support.

IMO nlohman/json.hpp should be added to the code base, in a /src/third_party subdirectory. Indeed it's quite strange to have to curl/wget the json hpp file from the gh project page and sudo/cp to the /usr/include. When this header is added to the code base, then GLTF_SUPPORT should be enabled by default.

**Comment by CyrilWaechter** [comment]
@tpaviot As github actions are now used for this purpose I feel like this issue can be closed. What do you think ?

**Comment by tpaviot** [comment]
@CyrilWaechter right
