### ISSUE TITLE
IfcSverchok by type dropdown should allow for a manual class

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1091]
Ping @htlcnn on this line: https://github.com/IfcOpenShell/IfcOpenShell/commit/322f3773e491501c2e0dd45eafb6f61bea4d9494#diff-1a7b592bb8e14fbf356b9d95fcde6cc68affd94b05d3d20d83679cceb77f01a0R13

The "By Type" node should allow the user to choose any IFC class they can think of. I didn't spot this before but the way you've implemented it, only `IfcElementType` classes are shown in the dropdown. Unfortunately there are hundreds of classes in the IFC schema so a single dropdown for all classes is not practical from a UI perspective. I think this is why I simply left it as a text box when I first built it :)

What I can recommend is maintaining a text box, which is empty by default. If the user fills it in, then it runs the "By Type" node using the value in the text box. Otherwise, it shows two dropdowns, the first being a product filter, and the second being a class filter. Exactly the same as in the class assignment UI:

![2020-11-09-154209_297x52_scrot](https://user-images.githubusercontent.com/88302/98501034-368a1f00-22a2-11eb-839e-62f1917b81f1.png)

This would allow a balance between user convenience and full power of being able to manually type any IFC class.

**Comment by htlcnn** [comment]
@Moult sorry I did not get what you intended to make with that node. I thought that all available IfcElementType are in your schema already. Now I'm still confused what should I do with the node. What kind of input does it accept, IfcElementType or IfcElement?

**Comment by Moult** [comment]
@htlcnn that node should accept all IFC classes in the schema (even things like `IfcApplication`). That node simply is a graphical representation of `ifcopenshell.open('foo.ifc').by_type(ifc_class)`.

Hope it makes sense?

**Comment by htlcnn** [comment]
@Moult https://github.com/IfcOpenShell/IfcOpenShell/pull/1092 I hope that matches your idea

**Comment by Moult** [comment]
@htlcnn that looks perfect! Amazing job!

@aothms would it make sense to give @htlcnn commit access to IfcOpenShell? He can follow similar rules to me, i.e. don't touch the C++ nor the ifcopenshell-python module without your permission?
