### ISSUE TITLE
GLTF and GLB import in open cascade

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1100]
https://community.osarch.org/discussion/299/open-cascade-forum-gltf-and-glb-import-in-open-cascade

Does this mean that IfcConvert can skip the DAE step when feeding things like BIMSurfer?

**Comment by aothms** [comment]
> Does this mean that IfcConvert can skip the DAE step when feeding things like BIMSurfer?

It can already for two years outside of OCCT https://github.com/IfcOpenShell/IfcOpenShell/blame/v0.6.0/src/serializers/GltfSerializer.h

Use `IfcConvert in.ifc out.glb`

**Comment by Moult** [comment]
Ah OK :) Does this new development make the code any easier in IfcConvert?

Feel free to close if this has no impact :)

**Comment by aothms** [comment]
No, not really. Ifcopenshell doesn't store colors for example in
opencascade data model. So reusing the framework of the existing
triangulated serializers makes more sense in our case.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op vr 13 nov. 2020 09:16 schreef Dion Moult <notifications@github.com>:

**Comment by Moult** [comment]
Cheers :) closing!
