### ISSUE TITLE
blenderbim: ifc import - filter by category/class/product? lark error: "No terminal defined"

### ISSUE THREAD

**Issue by fbpyr** [IfcOpenShell/IfcOpenShell#1101]
First of all, thank you so much on all your work on Blender-BIM and IfcOpenShell! 
Blender-BIM is truely fantastic to work with! (spent the last couple of years in rvtAPI)

**Is there a way in BlenderBIM - that I might have missed - to filter certain IfcClasses
 from being imported into Blender or just import just specific ones?**

(I got some large IFCs from third parties and would only need walls slabs voids 
and FlowSegments for my collision check tool. The import errors out on some 
Grid elements from ArchiCAD mode - will create a separate issue)

I assume it is possible, as I discovered `ifc_import_filter` and `ifc_selector`, 
but could not figure out how the string for ifc_selector would need to be formed. 

It says it would accept only string or binary, but when I feed strings to it, 
it complains about a missing terminal. 
Apparently it needs a specific search string, but unfortunately the lark tutorials 
I found, did not get me much further.  ( Is there maybe a utility I can feed regex in? 😉   )

```python
import bpy
import logging
import blenderbim.bim.import_ifc
from pathlib import Path

IFC_PATH = Path("p:/ath_/_to_/_ifc_model.ifc")

ifc_import_settings = blenderbim.bim.import_ifc.IfcImportSettings.factory(
    bpy.context,
    str(IFC_PATH),
    logging.getLogger('ImportIFC'),
)

ifc_import_settings.ifc_import_filter = "WHITELIST"
ifc_import_settings.ifc_selector = "{'IfcWall', 'IfcSlab'}"
ifc_importer = blenderbim.bim.import_ifc.IfcImporter(ifc_import_settings)
ifc_importer.execute()
```

resulting error:
```
...AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\lark\parsers\xearley.py", line 115, in scan
lark.exceptions.UnexpectedCharacters: No terminal defined for '{' at line 1 col 1

{
^

Expecting: {'AT', 'HASH', 'DOT', 'STAR', 'LPAR'}
```

**Comment by fbpyr** [comment]
I found the lark grammar in:
`...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py`
With it and further helpful explanation by @Moult I found here:
https://github.com/IfcOpenShell/IfcOpenShell/issues/748
I got the ifc import filter limited to specific IfcClasses to work:

```python
import bpy
import logging
from blenderbim.bim import import_ifc
from pathlib import Path


def selected_import_ifc(ifc_file_path, filter, query):
    ifc_import_settings = import_ifc.IfcImportSettings.factory(
        bpy.context,
        str(ifc_file_path),
        logging.getLogger('ImportIFC'),
    )
    ifc_import_settings.ifc_import_filter = filter
    ifc_import_settings.ifc_selector = query
    ifc_importer = import_ifc.IfcImporter(ifc_import_settings)
    ifc_importer.execute()


ifc_path = Path("p:/ath_/_to_/_ifc_model.ifc")
selected_import_ifc(ifc_path, "WHITELIST", ".IfcWall | .IfcSlab") # only get walls and slabs
```

**Comment by Moult** [comment]
![image](https://user-images.githubusercontent.com/88302/99044583-192bbc80-25e4-11eb-967d-3236f2ac8440.png)

**Comment by Moult** [comment]
Glad you got it resolved! I posted a screenshot in the comment above which shows you how to do this via the UI. Simply set those settings prior to importing your file. The import will go much, much quicker.

Also, the query syntax is documented here: https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#IFC_Query_Syntax

**Comment by Moult** [comment]
Also I see you're doing collision detection. Have you tried out the IfcClash feature? :)

**Comment by fbpyr** [comment]
@Moult thank you so much!! 
The query syntax list is very helpful!!

Thank you also for the clash pointer - I found the IfcClash 
(amongst other nice features) just yesterday. 
Unfortunately I had my basic logic for clash detection 
via bboxes and aggregating the data in voids and csv 
already working (started in rvt, then FreeCAD, 
then blenderbim ), but will check it out nonetheless! 🙂 

Even though I got the filtering to work, it seems that 
does not help to skip erroneous elements s in #1103 
@Moult do you have an idea/pointer there, too?

**Comment by Moult** [comment]
@fbpyr the import filter only applies to products right now. The spatial tree and grids are not filtered. That would explain why you're still experiencing that bug despite the filter. I will investigate that bug.
