### ISSUE TITLE
blenderbim Error: Collection 'IfcGrid/Grid' already in collection 'IfcBuildingStorey/EG' even with IfcGrid import filtered

### ISSUE THREAD

**Issue by fbpyr** [IfcOpenShell/IfcOpenShell#1103]
`[ Blender 2.90.1  - BlenderBIM 201025 - Win10 ]`
When importing a specific IFC file (made by ArchiCAD, downloaded from a trimble platform), 
even with .IfcGrid blacklisted as below, it still errors out at the grids:

```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "<blender_console>", line 18, in selected_import_ifc
  File "%APPDATA%\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 403, in execute
    self.place_objects_in_spatial_tree()
  File "%APPDATA%\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 1720, in place_objects_in_spatial_tree
    self.place_object_in_spatial_tree(self.file.by_guid(global_id), obj)
  File "%APPDATA%\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 1733, in place_object_in_spatial_tree
    self.spatial_structure_elements[container.GlobalId]['blender'].children.link(grid_collection)
RuntimeError: Error: Collection 'IfcGrid/Grid' already in collection 'IfcBuildingStorey/EG'
```

Used import filtered ifc snippet, similar to #1101 
```python
import bpy
import logging
from blenderbim.bim import import_ifc
from pathlib import Path


def selected_import_ifc(ifc_file_path, filter, query):
    ifc_import_settings = import_ifc.IfcImportSettings.factory(
        bpy.context,
        str(ifc_file_path),
        logging.getLogger('ImportIFC'),
    )
    ifc_import_settings.ifc_import_filter = filter
    ifc_import_settings.ifc_selector = query
    ifc_importer = import_ifc.IfcImporter(ifc_import_settings)
    ifc_importer.execute()


ifc_path= Path("p:/ath_/_to_/_ifc_model.ifc")
selected_import_ifc(ifc_path, "BLACKLIST", ".IfcWall | .IfcSlab | .IfcGrid | .IfcDoor | .IfcWindow | .IfcBuildingElementProxy")
```

So I wonder:
Why would the IfcGrid be a problem in place_objects_in_spatial_tree, 
if it is to be skipped by the import settings?
Is there a way to tell the importer to skip and report erroneous elements?

**Comment by Moult** [comment]
@fbpyr can you send me a copy of your IFC file so I can replicate your issue? dion@thinkmoult.com if it is private.

The importer filter only filters products at the moment, not grids or spatial elements.

**Comment by fbpyr** [comment]
Ah I see, thank you!
For what it's worth:
* Solibri does not show any geometry for these grid elements either. (but also shows no error)
* FreeCAD just seem to hang for hours on import.

It seems like the first the grids is a nested construct:
```
Grid #5847914=IfcGrid('2EDZhXAIhd8kMZ1L32A0yQ',#12,'Grid',$,$,#5847417,#5847911,(#5847682,#5847692,#5847662,#5847742,#5847752,#5847592,#5847762,#5847772,#5847542,#5847902,#5847892,#5847882,#5847872,#5847862,#5847842,#5847832,#5847822),(#5847852,#5847782,#5847792,#5847732,#5847722,#5847712,#5847702,#5847802,#5847812,#5847424,#5847442,#5847452,#5847462,#5847472,#5847482,#5847492,#5847502,#5847512,#5847522,#5847532,#5847552,#5847562,#5847572,#5847582,#5847602,#5847612,#5847622,#5847632,#5847642,#5847652,#5847672),$)
Grid #5848095=IfcGrid('2iWw9hlXYJpTqutEdD$MRz',#12,'Grid',$,$,#5848066,#5848092,(#5848073,#5848083),(#5848073),$)
Grid #5848150=IfcGrid('1xH4n2wkkCZrsOuPqg$eOu',#12,'Grid',$,$,#5848111,#5848147,(#5848118,#5848128,#5848138),(#5848118),$)
Grid #5847995=IfcGrid('00tLV9kFa8cWxnv0UKd2QB',#12,'Grid',$,$,#5847976,#5847992,(#5847983),(#5847983),$)
Grid #5848049=IfcGrid('3qISUCD$3u93Bty_f68mLN',#12,'Grid',$,$,#5848010,#5848046,(#5848017,#5848027,#5848037),(#5848017),$)

```

As I do not get any errors when reading the model with ifcopenshell, would it be possible 
to "just pass" the wall and floor objects from ifcopenshell to blenderbim ifc import?

🤔  Hm, I fear I cannot send you the model, less because it is semi-big (~150MB), 
but as it is from a running project, which has some restrictions on it. 
I would love to send the grids as excerpt - is this possible with ifcopenshell (or other tools?) 
( for model subsets we usually have simplebim here, but I would need to get the license back 
(was tricky in the past) besides I am not sure if it alters the grids.)

Are there any ifcopenshell debug commands I could run? 
Or would a short video conference session work?

**Comment by Moult** [comment]
@fbpyr there is now an "extract element" IfcPatch recipe to help debugging, but I have never tried it with grids.

Let's do a short videoshare. I'll be online now at https://meet.jit.si/openbim

**Comment by fbpyr** [comment]
thank you for this fun video debug session!! 👍 🙂
