### ISSUE TITLE
Did I mess up the test directory during a PR merge?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1108]
Ping @aothms - I recently merged https://github.com/IfcOpenShell/IfcOpenShell/pull/1106

I thought it only touched BlenderBIM Add-on related code, but if you check under the "Files changed" tab I just noticed it actually bumps `test/input`. I haven't looked at this submodule before and I don't know if this change is good or bad. Can you check to make sure I didn't screw something up with the `test/input` submodule?

Sorry if it screwed something up, hopefully it is an easy revert to fix?

**Comment by aothms** [comment]
That's the pain of submodules. In particular @johanrd does a lot of great stuff in the https://github.com/IfcOpenShell/files which is linked as a submodule in test/input. So the files repo updates frequently and it's not always synced in the main IfcOpenShell repo. I think @Krande's PR might have moved the submodule a bit back in time. I just pushed https://github.com/IfcOpenShell/IfcOpenShell/commit/47cd183e61783304014e5d74d2a5c94a1c1e1ea3 to move it forward (beyond the state before the PR) so no worries.
