### ISSUE TITLE
Does IfcOpenShell support presentation layer to polygons mapping?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1109]
Looking over @Krande 's implementation of presentation layers, I just realised that layers are mapped to representation items. This means that similar to how IfcOpenShell has a mapping of styles to polygons, to implement this fully in the BlenderBIM Add-on I think I'd also need a mapping of presentation layers to polygons. Is this implemented somewhere?

**Comment by aothms** [comment]
I didn't check the implementation in BlenderBIM, I think @Stinkfist0 did the implementation in C++ https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom_schema_agnostic/Kernel.cpp#L197 by only looking at the association of layer to specifically only **representation**. I don't remember the details but while the schema supports association to arbitrary items, I think this is "deprecated" or "frowned upon"

**Comment by Moult** [comment]
Cheers - closing bug as presentation layers to representations are now implemented. Layers to items are not implemented, and no plans to do so for now.
