### ISSUE TITLE
BlenderBIM Ifc Slab obj gets created but without geometry

### ISSUE THREAD

**Issue by fbpyr** [IfcOpenShell/IfcOpenShell#1114]
From an ArchiCAD model IFC, a specific IfcSlab gets created, but not its mesh/geometric representation. 
(Behaviour on import in other applications: 
* solibri the slab appears - looks ok
* lexocad imports it but complains about: defect geometry, shape is not valid, no valid representation
* revit only gave only warnings on overlapping floors, does not create it
)
Other IfcSlabs of the same model seems to be created as expected. 

When I IfcImport it with a whitelist on its GlobalId, I get the following traceback:

```
Traceback (most recent call last):
  File "...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 134, in execute
    ifc_importer.execute()
  File "...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 483, in execute
    self.add_project_to_scene()
  File "...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 1323, in add_project_to_scene
    .children[self.aggregate_collection.name]
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1
```

I tried various Ifc import settings but with the same result of the slab not being imported. 
Is there a way to understand better what is happening / wrong with the element?

**Comment by Moult** [comment]
In the IFC debug panel, you can specify a STEP ID for the particular IFC Slab element, then you can try create shape from STEP ID. See if any object pops up. If no object pops up, you can dive deeper into the representation (try the new IFC inspector feature just below it) and see where the shape creation fails.

If the shape creation fails, it is likely a bug with IfcOpenShell. The element needs to be isolated. You can use the IfcPatch ExtractElement recipe to extract just that element and see if you can reproduce the error.

Any possibility of sharing the file, or if not, screensharing?

**Comment by fbpyr** [comment]
Thank you so much for the quick response @Moult !
Unfortunately it is the same non-shareable file from last time - 
but a screen share session would be amazing! 🙂 

Unfortunately for today I just got placed some urgent stuff on my desk, 
so would be great if we could do the screen share tomorrow? 
I will send you an email to see if it would fit your schedule..

**Comment by Moult** [comment]
@fbpyr no worries - tomorrow Sydney time in the morning works, else after 3pm works too. Email is dion@thinkmoult.com

**Comment by Moult** [comment]
Bug is in the IFC file - strange non-manifold faceted brep was defined in a boolean operation. Closing :)

**Comment by Moult** [comment]
Just want to say thanks again for the screenshare - it led to multiple commits polishing the new material system: https://github.com/IfcOpenShell/IfcOpenShell/commits/v0.6.0

**Comment by fbpyr** [comment]
great to hear it led to BlenderBIM/OpenIFCShell becoming even more awesome!! 
(BlenderBIM already puts some other overprized-proprietariy-closed-source 
applications to shame in many regards! 😁 )

it was once again a great debug session! I am learning a lot in each of them, so:
thank **you** for all your time, knowledge & explanations!
