### ISSUE TITLE
Regression: Out of memory (137) on wall (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#1116]
1. Convert [1116--wall--segfault.ifc](https://github.com/IfcOpenShell/files/blob/master/1116--wall--segfault.ifc) with 808ef1a (OCCT 7.5.0) and experience that the coversion consumes a lot of memory, and exits with out of memory code 137:

```
#1890=IfcWallStandardCase('0bpwdOI5XEHPOF7dogAc94',#1,'Basic Wall',$,'Basic Wall',#10463,#3831119,'')
[Warning] {0bpwdOI5XEHPOF7dogAc94} No material and surface styles for:
#1890=IfcWallStandardCase('0bpwdOI5XEHPOF7dogAc94',#1,'Basic Wall',$,'Basic Wall',#10463,#3831119,'')
[Notice] {0bpwdOI5XEHPOF7dogAc94} Boolean operation yields non-manifold result
[Notice] {0bpwdOI5XEHPOF7dogAc94} Boolean operation yields non-manifold result
Exit code 137
```

2. Convert the same file with 6cbf8cc8db0ea684c635c5b9d8e583d8620d32da (OCCT 7.3.0) and experience no hard fail, although failing opening subtractions:
```
[Error] {0bpwdOI5XEHPOF7dogAc94} Opening subtraction failed for 3 openings
#1890=IfcWallStandardCase('0bpwdOI5XEHPOF7dogAc94',#1,'Basic Wall',$,'Basic Wall',#10463,#3831119,'')
```
<img width="171" alt="Screenshot 2020-11-19 at 12 51 44" src="https://user-images.githubusercontent.com/4601554/99662788-03941800-2a66-11eb-8437-204f883c0b91.png">

3. Expected geometry from Solibri:

<img width="171" alt="Screenshot 2020-11-19 at 12 49 57" src="https://user-images.githubusercontent.com/4601554/99662598-c3cd3080-2a65-11eb-9ecd-78b7dce6a535.png">

The OOM is probably related to the intersection of the two openings, as removing either of them makes the file convert successfully.

**Comment by Moult** [comment]
Works now :)

![2023-02-14-152050_608x417_scrot](https://user-images.githubusercontent.com/88302/218638528-18924043-13ca-4142-a60e-9759ea3cd1cd.png)
