### ISSUE TITLE
My desktop flooded with .brep files

### ISSUE THREAD

**Issue by Shaddy-ElDesouky** [IfcOpenShell/IfcOpenShell#1121]
Hello @Moult first I have to thank you very much for you're great effort, this is a Game changer, can't wait until I actually have a complete product out of it.

I  was struggling to find tutorials for BlenderBim until I found your channel https://peertube.social/accounts/moult/ 
I watched most of the demo videos and I was interested specifically in section planes and creating Drawings, I don't remember trying something else(not sure) and then I found the flood of 3660 .brep files, the bright side is that I discovered that my desktop can actually carry them all and a side scroller appeared at the right :) . I panicked for a moment until I remembered that I'm not on Windows :)
OS: Kubuntu 20.04.1 
Blender: 2.90.1
BlenderBim: 0.0.201025
![Desktop brep files](https://user-images.githubusercontent.com/73293717/99906044-54617600-2cdd-11eb-8064-beeb42ae9725.png)

I used this ifc file to try section planes

[20200820IFC4_Convenience_store_Renga_4.1.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5579674/20200820IFC4_Convenience_store_Renga_4.1.ifc.zip)

**Comment by Moult** [comment]
There are some resources here that may help: https://wiki.osarch.org/index.php?title=BlenderBIM_Add-on - it's not particularly organised, but it's a start.

The BlenderBIM Add-on does not have any code that generates files with the extension `.brep` that I know of, and when it does generate files, it stores it in the add-on's data folder. So I can't really explain what you're seeing. Maybe you were experimenting with another software at the same time? What is the content of these files?

**Comment by aothms** [comment]
That would have been me, sorry... See commit

**Comment by Moult** [comment]
Ruh-roh! @aothms should I republish the latest version with a particular bot build to prevent users running into this issue?

**Comment by aothms** [comment]
It seems IfcOpenBot is stuck again. I'll give her a gentle nudge this afternoon.

**Comment by Moult** [comment]
Bot bump :)

**Comment by aothms** [comment]
There was a power outage causing the build machine to stop. I think she's almost ready now though

![afbeelding](https://user-images.githubusercontent.com/1096535/100721816-1e4c8200-33c0-11eb-8bf7-3aa12b6aa789.png)

**Comment by Moult** [comment]
Bump :)

**Comment by aothms** [comment]
ah crap, reboot tonight

**Comment by aothms** [comment]
She's getting weird errors on windows. Maybe some file handle leaking. I
disabled a bunch of python versions and tried again.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op vr 4 dec. 2020 01:27 schreef Dion Moult <notifications@github.com>:

**Comment by aothms** [comment]
Still no luck

![afbeelding](https://user-images.githubusercontent.com/1096535/101756652-84c75380-3ad6-11eb-8d74-75c802dd41b3.png)

The incompetence is staggering. I'll check again tonight.

**Comment by aothms** [comment]
@Moult https://github.com/IfcOpenBot/IfcOpenShell/commit/7ae685dbffb7db3443090d8388a5a84849447590#commitcomment-45519447 

It's using completely new build system so we need to double check

**Comment by Moult** [comment]
Closing as fixed! Awesome stuff!
