### ISSUE TITLE
ADD DESCRIPTION HELP

### ISSUE THREAD

**Issue by bbrangeo** [IfcOpenShell/IfcOpenShell#1128]
Hi 

propose to complete  line  ==> https://github.com/IfcOpenShell/IfcOpenShell/blob/acb518613bb93b1370941c0fdaf7796d11eec2a5/src/ifccsv/ifccsv.py#L177

with 
```
parser.add_argument("-a", "--arguments", nargs="+", help="Specify attributes that are part of the extract, BaseQuantities.*Volume")

```

**Comment by Moult** [comment]
I'm not sure if it's less confusing. Perhaps a better approach would be to specify that it uses the Ifc Query syntax. The IFC query syntax is documented on the OSArch wiki.
