### ISSUE TITLE
Segmentation fault on FlowSegment element

### ISSUE THREAD

**Issue by triamazikamno** [IfcOpenShell/IfcOpenShell#1140]
IfcConvert is failing on some IfcFlowSegment elements. I've isolated one of them and put in a small test file:
```
# IfcConvert -vv test.ifc test.obj                 
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.5.0)
[Notice] exclude entities IfcOpeningElement IfcSpace
Scanning file...
Done scanning file   
Parsing input file took 0 seconds
[Debug] Begin processing
#63=IfcFlowSegment('0QZPRrHmT4JuvEGUizlYit',#2,'W1','PFSP/CU 4x25/10mm²','IfcCableSegment.CABLESEGMENT',#57,#49,$)
Segmentation fault
```

[test.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5629332/test.zip)

**Comment by aothms** [comment]
Thanks for this file.

It's a sweep along a polyline but the curvature radius of the polyline is waaay to small for the radius of the pipe. This is not allowed by the standard.

> The segments of the Directrix shall be long enough to apply the Radius. In case of an arc segment forming part of the Directrix, its radius shall be greater then the disk Radius

https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcgeometricmodelresource/lexical/ifcsweptdisksolid.htm

![afbeelding](https://user-images.githubusercontent.com/1096535/101021890-d6209180-3570-11eb-9c44-97743b2d1e5b.png)

Given the four successive points A B C D from the polyline. You can compute the angles, bisector, intersection and orthogonal length x of the segment to the intersection point.

```
import ifcopenshell
import numpy

f = ifcopenshell.open("test.ifc")

R = f[48].Radius
pts = f[56].Points
coords = numpy.array([p.Coordinates for p in pts])

for i in range(len(coords)):
    
    try:
        a, b, c, d = coords[i:i+4]
    except ValueError as e:
        break
    
    L = numpy.linalg.norm(c - b)
    print("L =", L)
    
    ba = a - b
    bc = c - b
    ba /= numpy.linalg.norm(ba)
    bc /= numpy.linalg.norm(bc)
    
    alpha = numpy.arccos(ba @ bc)
    print("a =", alpha / 3.141592653 * 180.)
    
    cb = b - c
    cd = d - c
    
    cb /= numpy.linalg.norm(cb)
    cd /= numpy.linalg.norm(cd)
    
    beta = numpy.arccos(cb @ cd)
    print("b =", beta / 3.141592653 * 180.)
    
    x = L / ((1/numpy.tan(alpha / 2.) + 1/numpy.tan(beta / 2.)))
    print("x =", x)
    print()
```

Radius = 0.013,  max radius based on segment length and angle = 0.0018489045046184288. So the pipe self-intersects.

---

So, I can imagine some combination of IfcOpenShell OCCT will definitely fail. What versions did you use though as currently the latest version of v0.6.0 did not segfault for me.

**Comment by triamazikamno** [comment]
Thanks for the investigation!

I've tried multiple combinations, all of them failed:
1. 0.6.0b0 (OCC 7.5.0), built from 9281c8fbce70dd13720c311025284921a4b9ba20 with 2 versions of opencascade:
  a) standard package included in debian 10
  b) custom built from f136d2a3ac89b3203affef1f04da6fde9d60bf7e
2. 3b0585ae4bc0751ec99a30b2b4159c9ff7e5a925 + OCCT v7.3.0p4
3. fc5fcef0791e55c1bbb7f8d03b7b64c4d66b152c + OCCT v7.5.0

**Comment by Moult** [comment]
```
 dion  tmp  /home/dion/tmp/IfcConvert -vv test.ifc test.obj                                                                                                                                                                            :) 
IfcOpenShell IfcConvert v0.7.0-07ee62eb9 (OCC 7.5.3)
[Notice] [2023-02-14 15:17:38] exclude entities IfcOpeningElement IfcSpace
Scanning file...
Done scanning file   
Parsing input file took 0 seconds
[Debug] [2023-02-14 15:17:38] Begin processing
#63=IfcFlowSegment('0QZPRrHmT4JuvEGUizlYit',#2,'W1','PFSP/CU 4x25/10mm²','IfcCableSegment.CABLESEGMENT',#57,#49,$)
[1]    19609 segmentation fault  /home/dion/tmp/IfcConvert -vv test.ifc test.obj
```

Segfaults for me with latest bot build.

**Comment by Moult** [comment]
Closing as no longer segfaults on latest bot build.
