### ISSUE TITLE
BlenderBIM IFC export problem 

### ISSUE THREAD

**Issue by dhulsegge** [IfcOpenShell/IfcOpenShell#1141]
Hello,

First i imported an IFC, i did some name conversions to the mesh objects. After that i reexported the file as IFC and the following message appeared. If you need more specific information you can always ask me.

location: <unknown location>:-1
D pid(16564) tid(15492) 14:07:09 EdgeSnapFeature::PostExitSizeMove: WM_TWINVIEW_SHOW_GRIDLINES -> off
Python: Traceback (most recent call last):
  File "C:\Users\dhe2\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\operator.py", line 109, in execute
    ifc_exporter.export(context.selected_objects)
  File "C:\Users\dhe2\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\export_ifc.py", line 1374, in export
    self.relate_objects_to_material_sets(set_type)
  File "C:\Users\dhe2\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\export_ifc.py", line 3189, in relate_objects_to_material_sets
    [self.ifc_parser.products[product_index]["ifc"]],
IndexError: list index out of range

location: <unknown location>:-1

**Comment by Moult** [comment]
This may have already been fixed - there were a series of fixes from the last release to do with the latest material system. Is it possible to share your file (dion@thinkmoult.com if it is private) or retry your process with the latest v0.6.0 branch?

**Comment by Moult** [comment]
Bump. Ping @dhulsegge ?

**Comment by Moult** [comment]
Closing bug as likely fixed, and missing test case to reproduce.

**Comment by dhulsegge** [comment]
@Moult  i have sended you an email on 17-12-2020 also with example data, maybe it went in your spam?
