### ISSUE TITLE
Building by build-all.py create a very large executable

### ISSUE THREAD

**Issue by solar-core** [IfcOpenShell/IfcOpenShell#1143]
Hello! I am building IfcOpenShell using python build-all.py in nix folder using python [2.7.18] (python3 not working, have some errors) so the result in executable [IfcConvert] in this folder is about 964 Megabyte. This is very large file. If i look [here](http://ifcopenshell.org/ifcconvert) the IfcConvert is about 15 Megabyte. How can i change my 964MB into 15MB? 😊

**Comment by aothms** [comment]
set the BUILD_CFG=Release environment variable for that. Debugging symbols would be stripped then.

**Comment by solar-core** [comment]
Thank you, will try this now.

**Comment by aothms** [comment]
PS if you find incompatibilities with py3 and feel comfortable fixing them, feel free to send a PR.

**Comment by solar-core** [comment]
Ok, thanks, will try to contribute and fix this issue in my free time.
