### ISSUE TITLE
BlenderBIM: Locating the drawing within the IfcProject when created

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1147]
When 'Add Drawing', is it possible to locate it within the project?

Going from...
![image](https://user-images.githubusercontent.com/507113/101288540-cdbc9680-37bc-11eb-8326-7c1d04e38fd8.png)

... to something like this perhaps?....
![image](https://user-images.githubusercontent.com/507113/101288543-d01ef080-37bc-11eb-93b8-a70de5348160.png)

**Comment by Moult** [comment]
The short answer is no. These groups are not part of the spatial tree, so right now they kinda just exist in the IFC dataset, but not connected in any meaningful way.

The longer answer is that there may be a convention that may be established to connect it to the spatial tree. I have yet to investigate what this would be.

Currently a low priority, unfortunately.

**Comment by theoryshaw** [comment]
cool. good to know. thx.
