### ISSUE TITLE
error: 'Init' is not a member of 'IfcParse::IfcFile' when compiling with USE_MMAP

### ISSUE THREAD

**Issue by hawkaa** [IfcOpenShell/IfcOpenShell#1149]
Hi there,

I am trying to compile the current head of the v0.6.0 branch in a Dockerfile, but I can't seem to get the `USE_MMAP` to work. I get the following error:

```sh
/IfcOpenShell/src/ifcparse/IfcParse.cpp: In constructor 'IfcParse::IfcFile::IfcFile(const string&, bool)':
/IfcOpenShell/src/ifcparse/IfcParse.cpp:1307:18: error: 'Init' is not a member of 'IfcParse::IfcFile'
 1307 |  return IfcFile::Init(new IfcSpfStream(fn, mmap));
      |                  ^~~~
/IfcOpenShell/src/ifcparse/IfcParse.cpp:1307:49: error: returning a value from a constructor
 1307 |  return IfcFile::Init(new IfcSpfStream(fn, mmap));
      |                                                 ^
make[2]: *** [CMakeFiles/IfcParse.dir/build.make:245: CMakeFiles/IfcParse.dir/IfcOpenShell/src/ifcparse/IfcParse.cpp.o] Error 1
```

Dockerfile:
```dockerfile
FROM ubuntu:20.10 as builder

RUN apt-get update && apt-get install --yes git
RUN git clone https://github.com/IfcOpenShell/IfcOpenShell.git

RUN cd IfcOpenShell && git checkout e1fa6fb3
RUN apt-get install --yes cmake g++ libboost-all-dev
RUN apt-get install --yes liboce-foundation-dev \
    liboce-modeling-dev liboce-ocaf-dev liboce-visualization-dev \
    liboce-ocaf-lite-dev
RUN cd IfcOpenShell && mkdir build && cd build && \
    cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ -DCOLLADA_SUPPORT=0 -DIFCXML_SUPPORT=0 -DBUILD_IFCGEOM=0 \
    -DBUILD_IFCPYTHON=0 -DBUILD_EXAMPLES=0 -DBUILD_GEOMSERVER=0 -DUSE_MMAP=1
# Wish we could use MMAP but it triggers a bug witnh the current git commit
RUN cd IfcOpenShell/build/ && make
```

**Comment by aothms** [comment]
Indeed. `IfcFile::Init` should be renamed `initialize_` as it is 4 lines down. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcParse.cpp#L1307 Care to test and send in a Pull Request?

Mmapping sounds nice in theory, but keep in mind in this case it will only mmap the actual file contents, not the parse tree or any geometry constructs derived from it. Depending on your use case it may mean it doesn't have that significant of an effect.

**Comment by hawkaa** [comment]
> Indeed. `IfcFile::Init` should be renamed `initialize_` as it is 4 lines down. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcParse.cpp#L1307 Care to test and send in a Pull Request?

Okay, I guess I can try. I'm actually not in C and C++ space, and not too familiar with the compiler toolchains, makefiles and CMake,  I just happen to know how to compile binaries for my docker images. But I will try when I have time.

> Mmapping sounds nice in theory, but keep in mind in this case it will only mmap the actual file contents, not the parse tree or any geometry constructs derived from it. Depending on your use case it may mean it doesn't have that significant of an effect.

We're running IfcConvert in AWS lambda. If the lambda times out while IfcConvert runs,  we have no way to clean up. Which technically  shouldn't be a problem in lambdas, but  it is clear to us that the temporary directory is reused between invocations, such that the disk fills up. We wanted to test whether a memory mapped file could work for this.

**Comment by aothms** [comment]
> Which technically shouldn't be a problem in lambdas, but it is clear to us that the temporary directory is reused between invocations, such that the disk fills up.

This sounds brittle, but in my naive understanding not something affected by mmapping the file. Maybe what you're after is the constructor that takes a void* and length. https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcParse.cpp#L194 

The Python wrapper uses this a `ifcopenshell.file.from_string()` method https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcopenshell-python/ifcopenshell/file.py#L126 https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcwrap/IfcParseWrapper.i#L537

Unfortunately not all of IfcConvert is accessible from Python, so it's not a fully end-to-end solution, but maybe it's a step somehow in the right direction.

Thanks for the PR though :)

**Comment by hawkaa** [comment]
> This sounds brittle, but in my naive understanding not something affected by mmapping the file

Yes, this has dawned  on us as well. Thanks for the answer! Hopefully the PR was helpful.
