### ISSUE TITLE
Draw dimension markers (arrows) and dimension text on dimension objects

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1150]
When a new dimension object is created, there should be a mode which displays these decorations in bgl.

The text should just use bgl text, no need for fancy fonts / etc.

The drawing mode should be toggle-able on/off.

![2020-12-07-211448_1920x1080_scrot](https://user-images.githubusercontent.com/88302/101338560-401e9b00-38d1-11eb-8a15-bbd32b30c236.png)

**Comment by qwiglydee** [comment]
There is no bgl text in Blender. There is built-in font-renderer [blf](https://docs.blender.org/api/current/blf.html) with some direct rendering to viewport.
I assume you mean this lib to use for the text.

**Comment by Moult** [comment]
@qwiglydee you are correct :) Sorry!

**Comment by Moult** [comment]
@qwiglydee AWESOME WORK! You rock! I made a minor tweak to support multiple dimension objects and other curve types, which there could be.
