### ISSUE TITLE
Missing materials when importing IFC files generated in Archicad 21

### ISSUE THREAD

**Issue by DeGutsch** [IfcOpenShell/IfcOpenShell#1151]
Hallo,

As prevoisly discussed in the Blender Artists forum, there is a problem when importing IFC files created in archicad 21. When importing the result is inconsistent, because while all objects show a correct IFC Material in the object properties tab, some are missing the corresponding material in the object material tab.

Archicad, IFC and Blender files:

[Test BlenderBIM.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5658071/Test.BlenderBIM.zip)

**Comment by Moult** [comment]
@DeGutsch thank you! However, you are missing the IFC file in your zip. Can you please upload it?

By the way, what you've described _may_ be actually correct behaviour and _not_ a bug. The Object properties shows the IFC material data, whereas the Blender material tab actually shows the IFC "style" data. In IFC, the material and the style are two different things.

**Comment by DeGutsch** [comment]
Zip file updated, thanks.

I can imagine that it can be _correct_, but seems to me like not so logical because some objects are so and some others not. Should this information not be consistent across objects?

**Comment by Moult** [comment]
@DeGutsch Cheers. I just checked, and indeed it is not a bug. For some objects, ArchiCAD has assigned a material, but no style. There's nothing technically wrong with this - this is allowed behaviour. It doesn't have to be consistent, it's up to the BIM modeler / author. Maybe there is a setting in ArchiCAD which affects this.

**Comment by DeGutsch** [comment]
I see, that's a bummer, cause I tested all archicad IFC exporters and coud not find a way to correct this.

Thanks for your help. that was fast!
