### ISSUE TITLE
Make dimension decorator arrows larger in perspective view

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1157]
Ping @qwiglydee In ortho the size is good, but in perspective mode, the arrows are a bit too small. Can this be increased? (it's OK for it to be hard-coded - it is merely a representation guide)

![2020-12-11-111527_377x365_scrot](https://user-images.githubusercontent.com/88302/101845223-472ffc80-3ba2-11eb-9f21-d4464c3e8726.png)
![2020-12-11-111522_431x403_scrot](https://user-images.githubusercontent.com/88302/101845227-47c89300-3ba2-11eb-93cc-4b4680b08b49.png)

**Comment by qwiglydee** [comment]
oh. that happens exactly because they're hardcoded for ortho.

i'll look into it.

**Comment by qwiglydee** [comment]
The hardcoded scale factor doesn't work well, when a dimension curve is pushed far away in z direction.
In the workflow with snapping dimensions to geometry vertices this situation seems to be quite common.

Also, the arrows heads in perspective view are not aligned to view plane.

Proper solution needs explicit perspective correction of the arrow size (from window-scale pixel size) and orientation (aligned to view plane).
