### ISSUE TITLE
Create decorator for equal dimensions

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1158]
Ping @qwiglydee based on the work you did for the dimension arrows, it would be awesome to create an extension to support "equal dimensions". Basically the only difference between an equal dimension and a regular dimension is the object name, and instead of displaying a length, it always displays the string "EQ", regardless of the actual dimension length.

![image](https://user-images.githubusercontent.com/88302/101845606-33d16100-3ba3-11eb-8281-2805c201ce58.png)

**Comment by qwiglydee** [comment]
Ok.
Leaving a comment to hereby expressly consent to get assigned for abovementioned task.
