### ISSUE TITLE
Can provide commit access to @qwiglydee ?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1160]
Ping @aothms - @qwiglydee is helping code for the BlenderBIM Add-on :D Is it possible to give him commit access? It would be more convenient than him creating PRs and managing branches.

He will only touch stuff in `src/ifcblenderexport/` - nothing else should be touched. @qwiglydee how does this sound?

**Comment by aothms** [comment]
![afbeelding](https://user-images.githubusercontent.com/1096535/101981617-92afdc80-3c6e-11eb-8e51-b8855206fede.png)
 
Invitation sent. Thanks for helping out @qwiglydee and welcome!
