### ISSUE TITLE
BlenderBIM: have dimension decorations show imperial units

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1164]
This might be planned already.

![image](https://user-images.githubusercontent.com/507113/101995162-b1719b80-3c8d-11eb-8d83-27d93534327c.png)

**Comment by Moult** [comment]
It is planned.

**Comment by qwiglydee** [comment]
@Moult, I assume it should use the same value-to-text logic, as in svg exporter, right?

**Comment by Moult** [comment]
@qwiglydee correct - I've assigned it to you. The function is already written - this is what you need to call:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/helper.py#L155

**Comment by qwiglydee** [comment]
@Moult is there any advantage of that over
 `bpy.utils.units.to_string`?

The latter is implemented in C (`source/blender/blenkernel/intern/unit.c`) and seems more appropriate to get called for each frame update.

**Comment by Moult** [comment]
@qwiglydee good point. Use the bpy tool :)
