### ISSUE TITLE
Building with Python 3.9

### ISSUE THREAD

**Issue by lgtrombetta** [IfcOpenShell/IfcOpenShell#1167]
I am trying to build from master with Python 3.9 and it fails. I am not sure, but it might be similar to #757. 

I also checked 
https://anaconda.org/conda-forge/ifcopenshell/files 
but there is no build there for 3.9.

**Comment by aothms** [comment]
> master

I recommend the v0.6.0 branch.

What's the error? What platform are you on?

**Comment by lgtrombetta** [comment]
I use the ifcopenshell-git package from the AUR. Sometimes it doesn't build but currently it does. I will close this issue.

**Comment by Moult** [comment]
By the way, the IfcOpenBot now has builds for Python 3.9 :)
