### ISSUE TITLE
Selector not work good with boolean values

### ISSUE THREAD

**Issue by c4rlosdias** [IfcOpenShell/IfcOpenShell#1168]
select does not seem to get along very well with boolean values for false:
![Capturar](https://user-images.githubusercontent.com/57261862/102016224-99a62000-3d3e-11eb-99e1-249ac2c88603.PNG)

**Comment by Moult** [comment]
@c4rlosdias great catch! This is the code that does filtering: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/util/selector.py#L196-L211

Would you like to have a shot at fixing it? This line looks suspicious to me, maybe it should be if element_value is None instead? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/util/selector.py#L207

**Comment by c4rlosdias** [comment]
hello Dion,
that's exactly it: element_value
 I changed the line here to:
`if element_value is None:`
 and it worked perfectly! Thank you very much!

**Comment by Moult** [comment]
@c4rlosdias would you like to try submitting a PR? It's a good learning opportunity if you plan to contribute in the future!

**Comment by c4rlosdias** [comment]
sorry for the ignorance, but what is a PR?

**Comment by Moult** [comment]
@c4rlosdias PR = pull request. Basically, to contribute back, just "fork" the IfcOpenShell repository, make the change, and the Github website will guide you on creating a "Pull Request", which basically says "hey Dion, I made this change, can you review / approve the change" so that your code edits will be saved in the main repository.

**Comment by c4rlosdias** [comment]
Oh! Sorry for my bad english!
I think I managed to do that!

**Comment by Moult** [comment]
@c4rlosdias this page may help: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests

When you've successfully created a PR, you should be able to see it here: https://github.com/IfcOpenShell/IfcOpenShell/pulls - then I can approve the change.

**Comment by c4rlosdias** [comment]
Thanks for your patience!

**Comment by Moult** [comment]
@c4rlosdias good progress so far! I see you've created PR: https://github.com/IfcOpenShell/IfcOpenShell/pull/1169 but you've reverted your change. Therefore, under the "files changed" tab of that site, there are no changes to be made. You have a few options:

 1. Make your change again - just reapply your changes and commit :)
 2. Start from scratch - it might be cleaner - delete the fork, then 1) create a new fork, 2) edit the line of code, 3) commit, 4) create a pr
 3. There are more advanced techniques on how to clean up the commits called squashing, if you're feeling adventurous)

**Comment by c4rlosdias** [comment]
Ok, I think I got it

**Comment by Moult** [comment]
@c4rlosdias awesome! I've merged your PR! Thank you so much!
