### ISSUE TITLE
Generate schema documentation from IfcDoc baseline files

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#117]
Looks like some kind of encoding bug in the code generator?

**Comment by aothms** [comment]
Yes, the comments come from an old MS Access dump that used to be online. These days however the documentation is provided officially as a part of IfcDoc, with documentation strings encoded in an IFC-like (10303-21) encoded file.

The code generator should probably be rewritten to use this new documentation, which would also be a good point to look into these encoding issues. There is a good chance they were introduced when I exported the MS Access db to .csv.

**Comment by aothms** [comment]
Available here

http://www.buildingsmart-tech.org/specifications/specification-tools/ifcdoc-tool/ifcdoc-baselines

**Comment by Moult** [comment]
I suspect this bug is no longer relevant as the new IFC documentation has entirely new tooling, of which IfcOpenShell plays a part. So... maybe this can be closed?

**Comment by aothms** [comment]
God yes
