### ISSUE TITLE
How to describe deduct relation between building element in IFC?

### ISSUE THREAD

**Issue by Elliotloststh** [IfcOpenShell/IfcOpenShell#1174]
a column and a wall overlap，deduct relation decides overlap part belong to which one.
i cant find the answer on google, so is there posibility to describe it in IFC?

thanks a lot!

**Comment by Moult** [comment]
@Elliotloststh I don't fully understand. Do you mean deduct like a boolean difference, or deduce as in deciding a particular "IfcRel*" class? Can you try rephrase your question?

**Comment by aothms** [comment]
I think what you're looking for is `IfcRelInterferesElements` with the 

ImpliedOrder | : | Logical value indicating whether the interference geometry should be subtracted from the RelatingElement (if TRUE), or whether it should be either subtracted from the RelatingElement or the RelatedElement (if FALSE), or whether no indication can be provided (if UNKNOWN).
-- | -- | --

I don't know to what extent this is implemented in software. The geometric subtraction for this relationship is not implemented in IfcOpenShell (but is implemented for IfcRelVoidsElements, which is generally much more used).

**Comment by Elliotloststh** [comment]
> I think what you're looking for is `IfcRelInterferesElements` with the
> 
> ImpliedOrder	:	Logical value indicating whether the interference geometry should be subtracted from the RelatingElement (if TRUE), or whether it should be either subtracted from the RelatingElement or the RelatedElement (if FALSE), or whether no indication can be provided (if UNKNOWN).
> I don't know to what extent this is implemented in software. The geometric subtraction for this relationship is not implemented in IfcOpenShell (but is implemented for IfcRelVoidsElements, which is generally much more used).

this solve my question，thank you!
