### ISSUE TITLE
ifcopenshell.org partially down

### ISSUE THREAD

**Issue by josenxx** [IfcOpenShell/IfcOpenShell#1180]
I just tried to access http://ifcopenshell.org/python to download the Python zip file. However, I'm receiving an internal server error when I try to access the site as well as other sub pages like /ifcconvert. The index page seems to be working, though. Just wanted to make you aware of that.

**Comment by Moult** [comment]
I can replicate this.

@aothms let me kn0w if there is anything I can do to help. It might be good to take the opportunity to update the site to mention the new offerings?

**Comment by josenxx** [comment]
The most urgent thing is to make the site back online. Somebody mentioned this problem in the forum three days ago.

**Comment by aothms** [comment]
Thanks for reporting. Due to IfcOpenBot being down I guess the issue was we had to scroll through too many commits and were getting rate limited by the Github API. @Moult you're completely right. First start would be publishing the code, but it needs some cleaning first. I'll try to prioritize it.

**Comment by josenxx** [comment]
Thank you sir. The site is back. I am runing issue in to running the build-deps.cmd

**Comment by berndhahnebach** [comment]
does it mean I do not need to search on IfcOpenBot for the latest builds but use the one from http://ifcopenshell.org/python instead?

**Comment by aothms** [comment]
> does it mean I do not need to search on IfcOpenBot for the latest binaries but use the one from http://ifcopenshell.org/python instead? On FreeCAD forum I do still tell people they should search and download from IfcOpenBot ...

Yes, if it's working.

**Comment by Moult** [comment]
Can this be closed?

**Comment by josenxx** [comment]
Yes

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Dion Moult <notifications@github.com>
发送时间: Tuesday, January 26, 2021 6:15:27 PM
收件人: IfcOpenShell/IfcOpenShell <IfcOpenShell@noreply.github.com>
抄送: Xiaorui Xue <xue39@purdue.edu>; Author <author@noreply.github.com>
主题: Re: [IfcOpenShell/IfcOpenShell] ifcopenshell.org partially down (#1180)


Can this be closed?

―
