### ISSUE TITLE
Provide commit access to @berndhahnebach

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1182]
@berndhahnebach has been hacking on the BIMTester codebase, increasing its portability, adding translations to French and German, and also using it real life and adding new MicroMVDs... I think he has a good grasp of the codebase and is also a FreeCAD contributor :) 

Ping @aothms would it be possible to give him commit access? He won't be touching the C++ side of the code.

**Comment by aothms** [comment]
Sure @berndhahnebach has been a long time regular. Welcome to the team Bernd.

**Comment by berndhahnebach** [comment]
its a honor to join the team
