### ISSUE TITLE
IFC Rail and BIMTester

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1186]
Pinging @aothms and @rbertucat !

Firstly, this is great! It's excellent that BIMTester can help in the implementation testing for IFC Rail! I've merged your PR, and I'm liking the improvements. A couple of things I thought I'd create an issue on.

 1. The PR deletes the submodule mvd and input. I've reverted those two files so hopefully it'll be fixed (@aothms can confirm this). In future PRs maybe double check that changes are local to the codebase.
 2. Have you seen https://wiki.osarch.org/index.php?title=Using_MicroMVDs_for_exchange_requirements ? In general, each set of definitions in BIMTester correlate to a MicroMVD (see the list of MicroMVDs). Would you be interested in developing MicroMVD usecases of exchanging IFC Rail related information? If so, this is a task that requires continual refinement, so maybe it'd be best if you got direct commit access?
 3. Have you seen the cool work @berndhahnebach has been doing in creating a standalone GUI, increasing portability of BIMTester, as well as translation into French and German (and there is a volunteer available for Dutch too)? Maybe there is room for collaboration?

Just a few ideas :)

**Comment by berndhahnebach** [comment]
I have problems with this new code ... this does not work for me on latest ifcopenshell 

https://github.com/IfcOpenShell/IfcOpenShell/blob/05d835410daa23c2116d691db3d277e61bfea5e6/src/ifcbimtester/bimtester/features/steps/utils.py#L2

```
$ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell.express
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ifcopenshell.express
```

**Comment by aothms** [comment]
You need a fairly recent version of ifcopenshell. Recently the parser was
moved into the module to help the rail team quickly evaluate the RCs. Is
that the reason?

Op za 19 dec. 2020 14:04 schreef Bernd Hahnebach <notifications@github.com>:

**Comment by berndhahnebach** [comment]
I pulled latest source before compile and install ifcopenshell.

**Comment by berndhahnebach** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/05d835410daa23c2116d691db3d277e61bfea5e6/src/ifcopenshell-python/ifcopenshell/express/__init__.py#L11

the above would like to  open the file with write access int the installation directory ... 

`PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/ifcopenshell/express/express_parser.py'`

**Comment by aothms** [comment]
Yeah that could be a problem. Guess we have to commit the file being
generated. Feel free to go ahead with that or I'll pick it up soonish.

Op za 19 dec. 2020 15:46 schreef Bernd Hahnebach <notifications@github.com>:

**Comment by berndhahnebach** [comment]
I am on the way at the weekend...

**Comment by aothms** [comment]
@berndhahnebach that's a better plan indeed, see 7d756138f2edb549bda8e22d94d1bb9df101c0bf

**Comment by rbertucat** [comment]
> Pinging @aothms and @rbertucat !
> 
> Firstly, this is great! It's excellent that BIMTester can help in the implementation testing for IFC Rail! I've merged your PR, and I'm liking the improvements. A couple of things I thought I'd create an issue on.
> 
> 1. The PR deletes the submodule mvd and input. I've reverted those two files so hopefully it'll be fixed (@aothms can confirm this). In future PRs maybe double check that changes are local to the codebase.
> 2. Have you seen https://wiki.osarch.org/index.php?title=Using_MicroMVDs_for_exchange_requirements ? In general, each set of definitions in BIMTester correlate to a MicroMVD (see the list of MicroMVDs). Would you be interested in developing MicroMVD usecases of exchanging IFC Rail related information? If so, this is a task that requires continual refinement, so maybe it'd be best if you got direct commit access?
> 3. Have you seen the cool work @berndhahnebach has been doing in creating a standalone GUI, increasing portability of BIMTester, as well as translation into French and German (and there is a volunteer available for Dutch too)? Maybe there is room for collaboration?
> 
> Just a few ideas :)

Thanks @Moult!

1. Not sure what happened with the submodules - I had conflicts at some point and overlooked those. Thanks for fixing them.
2. Yes, it was very helpful to get started. If BIMTester gets adopted by the IFCRail working group, documenting the features there would make sense eventually as as having direct commit access.
3. His work was very helpful to get started as well. Thanks @berndhahnebach! What really helped was seing real features and the GUI is nice. We've started to bring it to another level (this is work in progress in our fork). There is room for collaboration for sure!

**Comment by berndhahnebach** [comment]
An improved gui would be cool ... What did you add?

**Comment by berndhahnebach** [comment]
> @berndhahnebach that's a better plan indeed, see [7d75613](https://github.com/IfcOpenShell/IfcOpenShell/commit/7d756138f2edb549bda8e22d94d1bb9df101c0bf)

works great :+1:   weekend is over here too ... :-(

**Comment by berndhahnebach** [comment]
found another issue ... 
what is a .gitignore useful here ?  https://github.com/IfcOpenShell/IfcOpenShell/blob/26d537cb4f715166d407ecaba8b810b1289c2201/src/ifcbimtester/.gitignore

A user should just not make his build dir here IMHO, or do I miss something?

**Comment by Moult** [comment]
Maybe the gitignore is for the `pyinstaller` command results?

**Comment by Moult** [comment]
Closing issue, as there is no issue to be solved here :)

Ping @rbertucat and @berndhahnebach I've moved a _lot_ of stuff around (and broke the GUI in the process, since I don't have PySide on my computer to test and fix it) - let me know what you think about the changes - perhaps we can continue discussion on https://community.osarch.org/discussion/322/bimtester-improvements-as-well-as-standalone-gui-and-freecad-module#latest
