### ISSUE TITLE
'file' object has no attribute 'schema'

### ISSUE THREAD

**Issue by Maozerhouni** [IfcOpenShell/IfcOpenShell#1188]
Hi,

When running the ifcpatch, that raises an AttributeError : 'file' object has no attribute 'schema'.

I use it in PyCharm Terminal, on windows.

This is the line I run : `python ifcpatch.py -i C:\Users\TOSHIBA\Downloads\ORI_BAT_DOE_CEA_M3
D_T2_A-Modified.ifc -r Optimise`

**Comment by aothms** [comment]
Probably old version. Later versions of v0.6.0 have schema attribute.

**Comment by Maozerhouni** [comment]
I use it with Python 3.6. Is the latest version the one in Github or in ifcopenshell.org ?

**Comment by Maozerhouni** [comment]
The IfcOpenShell/file.py I have has no difference with file.py in the src/ifcopenshell-python/ifcopenshell folder.

**Comment by aothms** [comment]
> The IfcOpenShell/file.py I have has no difference with file.py in the src/ifcopenshell-python/ifcopenshell folder.

Which branch?

> I use it with Python 3.6. Is the latest version the one in Github or in ifcopenshell.org ?

Github is source code. Builds are being pushed to the ifcopenshel.org website frequently. Use the latest v0.6.0

```
>>> import ifcopenshell
>>> ifcopenshell.version
'0.6.0b0'
>>> f = ifcopenshell.file()
>>> f.schema
'IFC4'
```

**Comment by Maozerhouni** [comment]
Yes, you were right. I updated it. Thanks.

**Comment by Moult** [comment]
Closing issue :)
