### ISSUE TITLE
BlenderBIM: IfcElementAssembly objects should not be represented by Blender collection instances.

### ISSUE THREAD

**Issue by Timdaviesuk** [IfcOpenShell/IfcOpenShell#1194]
## Current behaviour
An IfcElementAssembly is imported by creating a collection within an *Aggregates* collection. This collection is then instanced into the spatial structure it is contained within, and the original collection is hidden.

![CurrentBehaviour](https://user-images.githubusercontent.com/61473857/102792168-0a34e880-43a0-11eb-95bd-8184b9c2f29d.png)

## Expected behaviour
A user would expect a logical breakdown structure of a model.

Therefore the collection representing the IfcElementAssembly should exist directly within the spatial structure, and not instanced from else where, see below.

![ExpectedBehaviour2](https://user-images.githubusercontent.com/61473857/102808550-6146b780-43b8-11eb-9c8a-490ef124f497.png)

## Drawbacks of current behaviour
* Individual parts of an assembly can not be selected or manipulated within the 3D viewport.
* From the outliner it is difficult to find which items are in an assembly.
* IfcElementAssemblies are unique objects within a model and therefore would never be instanced multiple times. Instancing doesn't seem to make much sense here.
* Different behaviour to other tools that simply show the breakdown structure.
* Nested IfcElementAssemblies become very difficult to understand.

**Comment by Moult** [comment]
As the individual part cannot be selected, that's why there is the "edit aggregate" and "save aggregate" button. Agree though that it is clunky.

All your points are valid. There is one thing which worries me - aggregates _may_ be used multiple times. The collection instance was the way to solve that. Admittedly, I haven't seen this in the wild, though.

Maybe I should just go for it and implement your suggestion, which I agree is much more elegant.

**Comment by Timdaviesuk** [comment]
Thanks for the response!

I'm wondering in what scenario the same IfcRelAggregates instance could be used multiple times? Wouldn't that imply that you have multiple instances of the same rooted object?

The IFC spec says that IfcRelDecomposes and its subtypes can't be cyclic either.

The only small issue I see is handling the differences between IfcRelAggregates and IfcRelNests.

IfcRelNests is mostly for non-physical objects like tasks and schedules where there is an "implied order", but can *technically* be used for physical objects. It mentions nesting ports, but in this case the IfcRelNests could be derived from the use of ports.

In my opinion, the reality is that the vast majority of physical groups in AEC do not have an implied order and so IfcRelAggregates can be safely assumed to be the default grouping mechanism for any IfcElement.

**Comment by Moult** [comment]
@Timdaviesuk the aggregated whole itself is a rooted IFC element, so you don't have multiple instances of the same rooted object. You'd have multiple instances of the rel aggregates, I believe.

I'll re-read the spec and consider what you've written later tonight or tomorrow.

**Comment by Timdaviesuk** [comment]
@Moult The IfcRelAggregates is also a rooted entity so I'm fairly sure you'd only ever have one of those too.

Some relationships like IfcRelDefines are a bit more ambiguous in that the same rooted property set can be referenced by different objects (and even the same property can be referenced by multiple property sets) but I don't think that's the case for IfcRelAggregates.

**Comment by aothms** [comment]
> I'm wondering in what scenario the same IfcRelAggregates instance could be used multiple times? Wouldn't that imply that you have multiple instances of the same rooted object?

There is also potentially decompositions on the type level and IfcRelDefinesByObject https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/link/ifcreldefinesbyobject.htm

**Comment by Timdaviesuk** [comment]
@aothms Thank you for pointing me to that page. My interpretation of that scenario does mean that you could have multiple instances of the same object, in different locations, but with the same GlobalId. I can see how that can happen, basically like creating a nested family in Revit. I would agree in that scenario a collection instance does make sense.

I can't say I've seen that implemented in an IFC model before, but with regards to the original issue I would still say the expected behaviour of IfcElementAssemblies is that they should in the main Blender Outliner tree and not be instanced.

**Comment by Moult** [comment]
@Timdaviesuk so, since it is theoretically possible for multiple instances of the same aggregate, that's why I've built it the way I have... any thoughts on how to reconcile your desired feature without sacrificing the correctness of the spec?

**Comment by Timdaviesuk** [comment]
@Moult Sorry for the delay in responding, but I think I was wrong above when I said that the scenario described by @aothms means there would be multiple instances of an aggregate.

I can go into more detail, but basically each instance would have its own IfcRelAggregates.

Therefore, I'm fairly sure again there's no scenarios in which an IfcRelAggregate relationship could be used more than once, meaning you wouldn't need instancing.

**Comment by Moult** [comment]
@Timdaviesuk I think you are right, I think I must've got myself confused back when I first implemented it and somehow I remembered it as being possible to have an element being to multiple aggregates.

Sounds good - I will implement your suggestion, which makes perfect sense!

**Comment by Timdaviesuk** [comment]
Awesome, I have access to many models with 1000s of aggregate relationships so will give it a test as soon as its ready.

**Comment by Moult** [comment]
Feel free to apply the patch in that commit to see the impact in imports, but keep in mind this _will_ break exports if you're still using the stable release. The reason I didn't also implement it for exports is because exporting is now being completely rewritten from scratch. See #1222.

**Comment by theoryshaw** [comment]
Are there currently any ifc structures that would create 'collection instances' upon import?

It seems there should.  I kind of liked that aggregates were instanced collections.

**Comment by Timdaviesuk** [comment]
Thing is, if you have more than one instance of an aggregate, that means you have more than one object existing with the same GlobalId, which is not allowed.

Collection instances could maybe be used for non-rooted entities, such as ShapeRepresentations.

**Comment by theoryshaw** [comment]
could IfcMappedItem be used to translate objects into collection instances, I wonder?

**Comment by Timdaviesuk** [comment]
I'd imagine so yes, IfcMappedItems are pretty much meant for instancing, in that you can reference the same geometry in multiple places.
