### ISSUE TITLE
Annotation decoration should be configurable, with the default being red

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1197]
White works well when the background is dark, but doesn't work well in a rendered view of a drawing where the background is white. See image:

![2020-12-22-135841_573x347_scrot](https://user-images.githubusercontent.com/88302/102843726-ef28ae00-445d-11eb-9e26-a0e89965b0cc.png)

One option is to detect the background colour, but there are quite a few settings to check, so I'm thinking a similar solution is to change the default to red. This'll work for both dark and white backgrounds. Also, would be good to add a setting in the UI for the user to configure the colour just in case red is bad for the user. The colour picker can be next to the should draw dimensions checkbox. Example code for a colour picker is this:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/ui.py#L2523
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/prop.py#L1509-L1511

**Comment by qwiglydee** [comment]
There are `DocProperties.drawing_styles` and they seem like the proper place to put that option, along with other `space.overlay.stuff`.
But I don't see any way of customizing them. (I'd naively expect them to appear in 'Themes' blender preferences tho)

Should I put the option there maybe?

There are sume other options possible to customize:
- ARROW_ANGLE
- ARROW_SIZE
- CIRCLE_SIZE
- DASH_SIZE
- DASH_RATIO

**Comment by Moult** [comment]
@qwiglydee I think for now it doesn't need to be a drawing style, since these viewport annotations are simply loose representations of what'll finally be shown. The drawing generation actually emits just lines, and all the markers are styled later on client-side via CSS - so the viewport decorators will never fully represent what the final drawing will be - it's just there as an indicator.
