### ISSUE TITLE
IfcConvert returns no geometry with normal IFC files when the flag "--include --entities IfcSpace" is added.

### ISSUE THREAD

**Issue by iras** [IfcOpenShell/IfcOpenShell#12]
Hi,

I used IfcConvert with an IFC file somehow coming from AutoCAD. The file seems to use primarily IfcSpace and its geometry can't be converted unless using the flag  "--include --entities IfcSpace". I added such flag and the geometry came out nearly OK, so far so good.

I kept the "--include --entities IfcSpace" flag for other IFC files which normally don't need the flag and the result was no geometry at all this time. I removed the "--include --entities IfcSpace" flag and the geometry came out all right instead.

It looks as if the "--include --entities IfcSpace" flag somehow stops the usual IfcBuilding/IfcBuildingStorey/IfcSite from being processed. Could that be the case? I used IfcOpenShell r339.

**Comment by Stinkfist0** [comment]
`--include --entities IfcSpace` means "include *only* spaces". In order to get regular geometry + spaces, use `--exclude entities IfcOpeningElement`. But yes, this is a bit counterintuitive.

**Comment by iras** [comment]
Thanks a lot, Ali.

Yes that looks a "teensy" bit counterintuitive.
