### ISSUE TITLE
Cannot Run IfcOpenHouse.cpp

### ISSUE THREAD

**Issue by josenxx** [IfcOpenShell/IfcOpenShell#1202]
Thanks for the help from community. I am able to compile IfcOpenShell in my computer. I am using this fork: https://github.com/ahladik/IfcOpenShell Now I started to try to run "IfcOpenHouse.cpp" in the example folder.
Here is the error message.
```
  E:\PROGRA~1\VS\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\IfcOpenHouse.dir\IfcOpenHouse.obj /FdCMakeFiles\IfcOpenHouse.dir\ /FS -c ..\..\..\IfcOpenHouse.cpp
C:\Users\josen\Source\Repos\IfcOpenShell\src\examples\IfcOpenHouse.cpp(24): fatal error C1083: Cannot open include file: 'TColgp_Array2OfPnt.hxx': No such file or directory
  [3/6] Building CXX object CMakeFiles\IfcAdvancedHouse.dir\IfcAdvancedHouse.obj
  FAILED: CMakeFiles/IfcAdvancedHouse.dir/IfcAdvancedHouse.obj 
  E:\PROGRA~1\VS\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\IfcAdvancedHouse.dir\IfcAdvancedHouse.obj /FdCMakeFiles\IfcAdvancedHouse.dir\ /FS -c ..\..\..\IfcAdvancedHouse.cpp
C:\Users\josen\Source\Repos\IfcOpenShell\src\examples\IfcAdvancedHouse.cpp(24): fatal error C1083: Cannot open include file: 'TColgp_Array2OfPnt.hxx': No such file or directory
  ninja: build stopped: subcommand failed.
```
I run into three issues. First, the program cannot include some files. I searched them in the repository, but I cannot find them any where.
```
#include <TColgp_Array2OfPnt.hxx>
#include <TColgp_Array1OfPnt.hxx>
#include <TColStd_Array1OfReal.hxx>
#include <TColStd_Array1OfInteger.hxx>

#include <Geom_BSplineSurface.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <Standard_Version.hxx>

#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
```
Cmake also give me an error.  
![Screenshot 2020-12-22 162922](https://user-images.githubusercontent.com/10823996/102911007-7881b580-4449-11eb-8074-05e7c9fe8e8c.png)

I clicked "generate" and here is the error 
![Screenshot 2020-12-22 163011](https://user-images.githubusercontent.com/10823996/102911034-81728700-4449-11eb-8674-d0befd237955.png)
I also got hundreds of errors like this.
![Screenshot 2020-12-22 163041](https://user-images.githubusercontent.com/10823996/102911069-8d5e4900-4449-11eb-87c4-f66ab2620bca.png)
I am really sorry that I just keep asking help from the community and never contribute any code. I am a graduate student in construction. I need to process IFC for me research and I really do not know a lot about programming.

**Comment by josenxx** [comment]
@aothms @ahladik

**Comment by aothms** [comment]
I see all sorts of include errors on your screenshot, so it's not just occt, but also boost.

> Now I started to try to run "IfcOpenHouse.cpp" in the example folder.

When you say "run". What are you actually doing. Are you familiar with how CMake and the generated Visual Studio Solution works?

> C:\Users\josen\Source\Repos\IfcOpenShell\src\examples\IfcAdvancedHouse.cpp(24)

From this line it appears you're doing odd.

We would expect to see something like this:

```
1>------ Build started: Project: IfcOpenHouse, Configuration: RelWithDebInfo Win32 ------
1>IfcOpenHouse.cpp
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

On you file system after run-cmake.bat there will be a IfcOpenShell.sln file in 

IfcOpenShell\build-vs2019-x64\ (depending on visual studio version and platform)

Open that sln and then right click on examples > IfcOpenHouse [Set as startup project] and then click the green triangle to build and start the executable.

**Comment by josenxx** [comment]
I run the run-cmake.bat and run it to this error.
Running CMake for IfcOpenShell.
Python path configuration:
  PYTHONHOME = 'C:\Users\josen\source\repos\IfcOpenShell\deps-vs2019-Win32-installed\Python34'
  PYTHONPATH = (not set)
  program name = 'c:\programdata\anaconda3\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'c:\\programdata\\anaconda3\\python.exe'
  sys.base_prefix = 'C:\\Users\\josen\\source\\repos\\IfcOpenShell\\deps-vs2019-Win32-installed\\Python34'
  sys.base_exec_prefix = 'C:\\Users\\josen\\source\\repos\\IfcOpenShell\\deps-vs2019-Win32-installed\\Python34'
  sys.executable = 'c:\\programdata\\anaconda3\\python.exe'
  sys.prefix = 'C:\\Users\\josen\\source\\repos\\IfcOpenShell\\deps-vs2019-Win32-installed\\Python34'
  sys.exec_prefix = 'C:\\Users\\josen\\source\\repos\\IfcOpenShell\\deps-vs2019-Win32-installed\\Python34'
  sys.path = [
    'c:\\programdata\\anaconda3\\python38.zip',
    'C:\\Users\\josen\\source\\repos\\IfcOpenShell\\deps-vs2019-Win32-installed\\Python34\\DLLs',
    'C:\\Users\\josen\\source\\repos\\IfcOpenShell\\deps-vs2019-Win32-installed\\Python34\\lib',
    'c:\\programdata\\anaconda3',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000369c (most recent call first):
<no Python frame>

I am not really familar with cmake.

**Comment by aothms** [comment]
You have a very confusing Python setup:

> Python path configuration:
> PYTHONHOME = 'C:\Users\josen\source\repos\IfcOpenShell\deps-vs2019-Win32-installed\Python34'
> PYTHONPATH = (not set)
> program name = 'c:\programdata\anaconda3\python.exe'

How did you get this output? 

But anyway this is not related to IfcOpenShell.

> Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
> Python runtime state: core initialized
> ModuleNotFoundError: No module named 'encodings'

You can uninstall the python in C:\Users\josen\source\repos\IfcOpenShell\deps-vs2019-Win32-installed\Python34 and then set the following environment variables to use the anaconda interpreter. And then run cmake.

set PY_VER_MAJOR_MINOR=38
set PYTHONHOME=c:\programdata\anaconda3

**Comment by Moult** [comment]
Ping @josenxx we'll need a bit more feedback to help troubleshoot your issue :) Is it possible to provide more information about your system environment?

If no response after a week there's not much we can do so propose closing.
