### ISSUE TITLE
Modify add_annotation operator to support creating "Breakline" annotations

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1208]
Add a new button for a new operator in the tool bar. Feel free to copy code from the existing buttons / operators. The button will be called "Breakline" and use the `FCURVE` icon.

The `add_annotation` operator needs to be modified for this to support this new feature.

Currently add_annotation only has support for adding text, or adding lines (both path and mesh lines). For the Breakline operator, it needs to create or reuse an object called `IfcAnnotation/Break`, and instead of creating just a line, it needs to be a mesh, and it needs to create a plane. The plane should be a 2:1 rectangular ratio, always directly facing the camera (see the existing code to add lines on how it ensures the line is always in camera units).

Specifically, the order of the vertex indices of the plane also matters. I've shown the order of the vertex indices below. The size of the plane is not too important - but it is relative to the camera, so something similar to as shown is good.

![image](https://user-images.githubusercontent.com/88302/102948219-869f0700-4519-11eb-8f3e-754e06586993.png)

**Comment by Moult** [comment]
Oops - vertex indices 2 and 3 should be swapped.

**Comment by qwiglydee** [comment]
@Moult so, what is desired front-facing of the plane? 
with the clockwise ordering it'll look forward with (invisible) back side towards the camera. is it what desired?

**Comment by Moult** [comment]
@qwiglydee good point. Reverse the ordering so that the front face is towards the camera. The important part is that the top two vertices have indices 0 and 1, since later on a decorator needs to be drawn there.
