### ISSUE TITLE
Windows/MSVC: possibility to build official latest Open Cascade (7.0.0) instead of OCE

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#121]
FYI this is incoming soon.

**Comment by aothms** [comment]
Nice, I have tested on linux and it seems to work rather flawlessly, just needs a `-std=c++11`.
https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L448

You need to be authenticated to download it though, or are there other ways besides: https://www.opencascade.com/sites/default/files/private/occt/OCC_7.0.0_release/opencascade-7.0.0.tgz ? (Is it even allowed to require authentication when downloading LGPL software btw?)

**Comment by Stinkfist0** [comment]
Yeah, the sign-in is awkward, and for now we'll need to instruct the user to use a web browser for downloading downloading the package and its (minimal) dependencies [1] prior to running the build script. I wonder if we (you;) could ask to host copies on these files on some IfcOpenShell server perhaps?

[1]
https://www.opencascade.com/sites/default/files/private/occt/3rdparty/freetype-2.5.5-vc14-64.zip
https://www.opencascade.com/sites/default/files/private/occt/3rdparty/tcltk-86-64.zip

**Comment by aothms** [comment]
I just recalled I think you can get public snapshots from their gitweb: 
E.g. http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V7_0_0;sf=tgz

Surprisingly though this seemed to be different from the official release on the website.

tcl and freetype are not really necessary for our usage of OpenCascade since we don't need visualisation or draw. Wonder how much effort it would take to patch them out.

**Comment by Stinkfist0** [comment]
OCE doesn't have Tcltk dependency at all so it should not be a hard requirement. It would appear to be used only be TKDraw project.

**Comment by Stinkfist0** [comment]
OK, Draw and Tcltk was easy to get rid off ( -DBUILD_MODULE_Draw=0), but cannot see similar option for Font, at least by a quick glance.

**Comment by aothms** [comment]
I think that's true. I think it is part of TKService, which is pretty high up in the dependency chain. Freetype seemes to come with CMakeLists.txt, but I haven't checked it myself [1].

[1] http://download.savannah.gnu.org/releases/freetype/ft265.zip

**Comment by Stinkfist0** [comment]
Thanks, I'll give it a shot with downloads from these locations.

**Comment by Stinkfist0** [comment]
The work will be happening here https://github.com/Tridify/IfcOpenShell/tree/win_occt_7.0.0
