### ISSUE TITLE
"Add grids" should project and crop into drawing

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1216]
This is a little complicated one which needs a bit of coordinate math. I'll try and describe it the best that I can.

Sometimes, some of the grids are not inside the boundary of the camera object which represents the drawing. When this is the case, the grids must be automatically adjusted to fit within the camera boundaries. To do this, there are a few edge cases to check when projecting onto the camera.

Here's a simple example. I've added a grid object, then a new drawing. Then, I moved the drawing camera so that only part of the grid was within the camera boundary.

![image](https://user-images.githubusercontent.com/88302/103160222-3c25cf00-4826-11eb-9a25-aeaaa5045883.png)

When the "Add Grid" button is pressed, if the camera is perspective, just copy over the grids, and then finish. Nothing else needs to be done.

If the camera is orthographic, the two vertices of each grid axis (note: there will only be two, no less, no more) will be projected from their global coordinate positions to the 2D camera screen coordinates. I've written a function for this already here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/svgwriter.py#L591-L597 - it converts a global `point` to a local 2D coordinate (ignore Z ordinate) that is relative to the camera object. (see definition of the projection variable here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/operator.py#L2706 )

Refactor this function into a helper.py module, as it'll be used in future tasks quite heavily. This type of analysis will be pretty common.

So, once projecting the vertices of each grid axis, based on the camera ORTHO size, you will discover that both vertices of grid axis `A` and grid axis `1` lie completely outside the drawing boundary. In this scenario, those two axes will _not_ be copied into the drawing IfcGroup collection.

Then, for all the remaining grid axes (2, 3, B, C) you will find one vertex inside the drawing boundary, and another outside. Copy these objects into the drawing group, and then some modifications need to be made. The vertex inside remains unchanged, but the vertex outside needs to slide along the grid axis until it is _inside_ the drawing boundary, as viewed from the camera.

Hope that makes sense.

Then there is the question of how far in the drawing boundary it should be... the answer is it should be 15mm inside the drawing boundary. 15mm can be calculated by looking at the ortho size of the camera as well as the drawing scale. For example, a landscape camera (check BIMCameraProperties.raster_x BIMCameraProperties.raster_y to know landscape vs portrait) with a camera ortho_scale property of 50 means that the landscape dimension is 50 meters or 50,0000mm (in metric). Then, the drawing scale BIMCameraProperties.diagram_scale if set to 1:100 means that the drawing will be 50,000mm / 100 = 500 mm wide.

Here is the final result after all these changes:

![image](https://user-images.githubusercontent.com/88302/103160403-d38c2180-4828-11eb-9c3d-82f9b0acef90.png)

Later on there will be some interesting situations on what happens if the grids are perpendicular to the camera or overlapping, but that'll come in a future issue.

**Comment by qwiglydee** [comment]
@Moult  I guess I still don't get the idea of `project_point_onto_camera` and how it will be used in other tasks.

What I do for grid clipping:

1. transform geometry into camera local coords using model/view matrices of camera and grid object
2. clip grid segments in local camera coords (keeping them straight in z)
3. transform result back to grid local coords to put them back into 3d scene

I don't see any need of special projecting utility here.
Do I miss something?

**Comment by qwiglydee** [comment]
Here is how it looks with totally scewed camera:
![Screenshot from 2021-01-04 11-42-28](https://user-images.githubusercontent.com/285128/103501847-0a45e580-4e82-11eb-938f-1188759f8cd3.png)

**Comment by Moult** [comment]
I think your solution is good :) Closing issue!
