### ISSUE TITLE
Draw decorators for grids

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1218]
Grids axis should have a decoration drawn - it should look like a circle with its center at each vertex. There should also be text drawn at this point. The text value should be taken from the grid `AxisTag` attribute.

![image](https://user-images.githubusercontent.com/88302/103160479-c7ed2a80-4829-11eb-8d63-4b2e76f10508.png)

![image](https://user-images.githubusercontent.com/88302/103160490-071b7b80-482a-11eb-82dc-dcd11daf889e.png)

**Comment by qwiglydee** [comment]
@Moult should the lines themselves be outlined also?

**Comment by Moult** [comment]
@qwiglydee yes :)

**Comment by qwiglydee** [comment]
@Moult in freecad they are decorated with dash-dot pattern.
I assume it's some bim convention, and should be used here as well, innit?

**Comment by Moult** [comment]
@qwiglydee yes, you are right :) sorry. It's actually a long dash and a short dash, there is no dot. Here's what it looks like:

![2020-12-29-213036_797x798_scrot](https://user-images.githubusercontent.com/88302/103277457-229aa800-4a1d-11eb-9942-96be2bdb8217.png)

**Comment by qwiglydee** [comment]
I put labels in screen-space scale and orientation, just like all other labels.
Grid looks somewhat weird in perspective view. Not sure if it's ok.

![Screenshot from 2020-12-29 21-42-30](https://user-images.githubusercontent.com/285128/103291955-68587000-4a1f-11eb-96f9-662044baa78b.png)

**Comment by Moult** [comment]
@qwiglydee looks amazing! Go ahead and commit / close bug :D

**Comment by Moult** [comment]
So currently I assume you have implemented drawing decorators for grid axes inside the current drawing collection.

Can this be modified so that grid decorators are also shown for grid axes in any "IfcGrid/*" subcollection? Ideally implemented in a way that it only looks for it once (I assume it needs to loop through all bpy.data.collections to find relevant collections) so it doesn't slow the system down?

Grids are a bit special in that they're needed also in regular 3D modeling, not just drawings.

**Comment by qwiglydee** [comment]
@Moult decorations are object-based and handler scans for all relevant objects (by name, like 'IfcGridAxis/*') in the drawing collection.
It could be refactored to accept the target collection as a parameter (which now with lots of decorators makes more sense anyway), and  enabled for any other collection.

However, since the objects can be added/removed, handler has to scan for them every time. I'm not sure I can intercept and handle adding/removing new objects of desired types (maybe, manually trigger an event from `add_annotation` or `add_grid` or whatever, to rescan collection).

**Comment by qwiglydee** [comment]
@Moult anyway, how do you expect it to work from users perspective?

There's one switch to turn decorations on/off and it's related to (active) drawing.
Another switch for grid in main collection?

**Comment by Moult** [comment]
Hmm, I'm trying to think of what other objects might also be shown in the main spatial tree other than grids... for now, let's just close the bug. In the future maybe tackle this again.
