### ISSUE TITLE
Blender turns off when adding BlenderBIM addon LINUX

### ISSUE THREAD

**Issue by Rokorps** [IfcOpenShell/IfcOpenShell#1223]
Hello,
I downloaded the blenderbim zip file for linux, and installed it with addons>install, and then try to add it by just marking it and when I do it, blender just turns off and addon is not being added.
OS Ubuntu 20.10

Thank You for Your help,
Rokas

**Comment by Rokorps** [comment]
Okay, I have downloaded addon directly from ifcopenshell.org website and it seems that it works fine. 
BUT the zip file from ifcopenshell.org website (~17MB) is 10x smaller than from blenderBIM (~170MB) . << Why?

**Comment by Moult** [comment]
@Rokorps the one from ifcopenshell.org is heavily outdated, please use the one from blenderbim.org.

Any errors in the console?

**Comment by Rokorps** [comment]
Hey,
I do not get any errors, just it turns of instantly when trying to enable.
Here is the video how it looks like:

https://user-images.githubusercontent.com/18393730/103751773-79057900-5011-11eb-92b6-3e8fead3a8fd.mp4

Thank You for Your help and service

**Comment by Rokorps** [comment]
But it seems that it is blender error itself or OS, because also when trying to enable PDT addon same thing happens

**Comment by Moult** [comment]
@Rokorps try run it from console. Also try with the downloaded .tar.gz file from Blender.org itself, don't install from your repo. That might help narrow it down.

**Comment by Moult** [comment]
Bump? Will close in 10 days.

**Comment by Moult** [comment]
Closing bug due to lack of feedback. Also likely upstream / OS-specific issue.
