### ISSUE TITLE
BlenderBIM: Imported IfcOpeningElements slightly larger than the wall

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1226]
Currently it appears, upon import, the  IfcOpeningElements is sized the exact width of the wall, and is coplanar with the base of the wall, and per Blender, does not boolean with the wall correctly.  Could a fix for this include, slightly increasing the size of IfcOpeningElements so the boolean works correctly? 

![2021-01-03_10-21-38_blenderBlender_ DDropboxGitLabFreeMVD_WorkFlowRandoblender](https://user-images.githubusercontent.com/507113/103483593-ee710f80-4dad-11eb-99f1-c9a3c1c47f2f.png)
![2021-01-03_10-22-35_blenderBlender_ DDropboxGitLabFreeMVD_WorkFlowRandoblender](https://user-images.githubusercontent.com/507113/103483596-f0d36980-4dad-11eb-85f7-17f93ceb3971.png)

**Comment by Moult** [comment]
Yeah this needs to be implemented as a vendor workaround I suspect - short answer is that it's not good practice to have coplanar booleans. The booleans in the latest Blender release has improved this somewhat, but it still sometimes doesn't work. Putting this on the backburner as I'm doing a huge rewrite now.

**Comment by aothms** [comment]
Yes, but unfortunately coplanar boolean ops is pretty common. The geometric tolerance in IFC explicitly allows this and most BRep CAD libraries have no issues with this. But the mesh-based implementations suffer. I guess we should consider implementing this in C++.

**Comment by Moult** [comment]
Perhaps this may be a good candidate to bring to the attention of Howard upstream, who is implementing "exact" booleans. @theoryshaw can you provide him with upstream bugreports and sample files?

**Comment by theoryshaw** [comment]
Sure, happy to help out.  Would suggest a technical introduction from you guys, however.

**Comment by Moult** [comment]
I think just file a bugreport for Blender with your example and see what Howard's answer is. Probably mention that the new Blender exact boolean would probably be able to handle it.

**Comment by theoryshaw** [comment]
coo. will do.

**Comment by Moult** [comment]
This commit goes back to using IfcOpenShell for booleans by default, so this is fixed :)

https://github.com/IfcOpenShell/IfcOpenShell/commit/aa41f698c1666b8e8cf20e288f9a11236331a6ec
