### ISSUE TITLE
Is there code that handles removing an element including its dependencies?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1228]
Let's say I have an IfcWall, or IfcShapeRepresentation, or IfcRepresentationItem, or anything that I might want to remove. I can do `ifc_file.remove(element)`, but that only removes the element itself, and doesn't recurse down to its dependencies. For example, I'd also want to remove the object placement, or representations of that IfcWall. However, I'd want to remover it intelligently, so that if the representation is mapped, the other mapped items remain unaffected. Or if there is a cartesian point used elsewhere, that won't get removed.

To solve this, I expect I'd need to build a graph and do a bit of voodoo. Is there already code out there that helps in this or maybe has solved it already, maybe something in C++?

I'm also curious is there can ever be a generic solution to this? E.g. for deleting a wall, it needs to consider what it does to opening elements and the products that fill those openings... are those products that fill the openings deleted too, or do they simply lose the fill relationship and become contained of the spatial element that the wall was contained in? Does this need to be considered case by case? Given that example, I would say ... yes?

Also, ideally performance should be reasonable - I've come across issues doing removes especially on large files.

**Comment by aothms** [comment]
I think I have done similar things in the past. From memory:

```
subgraph = list(ifc_file.traverse(inst))
subgraph_set = list(subgraph)
for ref in subgraph[::-1]:
    if len(set(ifc_file.get_inverse(ref)) - subgraph_set) == 0:
         ifc_file.remove(ref)
```

So in short iterate over the traversed references in reverse order (so that you delete the leaf nodes first). With get_inverse() you check that all instances that use `ref`  are part of the subgraph. Only nodes that will be deleted point to it, so it can safely be deleted. Otherwise it is kept.

Not tested :)

**Comment by Moult** [comment]
Very clever code! I've copied it, and if it turns out that I start using it everywhere, I think it is a strong candidate to be included in the ifcopenshell util module! Thanks so much for your help!

**Comment by aothms** [comment]
> so I add a check for ref.id()

Yes that's the proper thing to do.

> traverse won't pick up inverse relationships which sometimes are important

Yes. I consider this a bit of a flaw in the schema. StyledBy should have just been a forward relationship. So that a forward search gives you a meaningful demarcation of the element.
