### ISSUE TITLE
Create new "Add References" operator underneath add grid

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1234]
Find all other SECTION_VIEW perpendicular cameras named `IfcGroup/*`, and create a new `IfcAnnotation/Section` object as a path object with a single segment with 2 points. Decorate using the triangle/circle intersection. Path I think points in +X direction of camera.

For each SECTION_VIEW camera, there should be a new IfcAnnotation/Section object, don't combine.

Later on, other types of cameras will be considered, but will have different decorators and different object names.

![2021-01-05-215848_1051x505_scrot](https://user-images.githubusercontent.com/88302/103638572-3441f980-4fa1-11eb-854f-90e57db738af.png)

**Comment by qwiglydee** [comment]
The decorations dont look good in 3d view (non-aligned with drawing camera) though.
![Screenshot from 2021-01-13 06-21-10](https://user-images.githubusercontent.com/285128/104387815-7c958480-556a-11eb-8a1a-aa8bd348a7b3.png)

Perhaps, for 3d view they should be disabled or rendered in some other way, maybe similar to built-in blender camera representation or something?

**Comment by Moult** [comment]
They look OK to me :) Don't worry that the circle / triangle symbol isn't pointing perfectly perpendicular to the line, that's not important from a user perspective.
