### ISSUE TITLE
Switch text direction for upside-down decoration labels

### ISSUE THREAD

**Issue by qwiglydee** [IfcOpenShell/IfcOpenShell#1238]
![Screenshot from 2021-01-05 20-25-51](https://user-images.githubusercontent.com/285128/103652132-3d2cce00-4f95-11eb-9d7f-b9f9df408f2c.png)

It would be better to keep text orientation more straight and readable, while keeping position of the labels.

**Comment by Moult** [comment]
Closing as not relevant to the direction in which viewport annotations are heading :) they are now primarily viewed in the camera.
