### ISSUE TITLE
Make decorations to hide behind other objects

### ISSUE THREAD

**Issue by qwiglydee** [IfcOpenShell/IfcOpenShell#1239]
![Screenshot from 2021-01-05 20-35-52](https://user-images.githubusercontent.com/285128/103652684-06a38300-4f96-11eb-9ae8-5b81fe287b71.png)

They better should be aware of z-depth, like in MeasureItARCH.
Maybe, also to respect x-ray view and become more pale just like other normal lines.

**Comment by Moult** [comment]
Closing as no longer relevant - annotations are always drawn on top and this is desired behaviour.
