### ISSUE TITLE
Ifc file import bug

### ISSUE THREAD

**Issue by Edralos** [IfcOpenShell/IfcOpenShell#1242]
![image](https://user-images.githubusercontent.com/32432267/103671676-84a66080-4f7b-11eb-83d0-00679d839f46.png)
![image](https://user-images.githubusercontent.com/32432267/103672321-6f7e0180-4f7c-11eb-9c58-7f8d7d1b4f48.png)

This is what I get by importing an ifc file.

Although, exporting it to .obj then import the obj file is shows no problem whatsoever.

Blender version : 2.91.0
blenderbim version : 0.0.201207

**Comment by Moult** [comment]
That looks like a Blender bug, perhaps related to your graphics card. What happens if you save out as a blend file, then open it as a blend file? But just to be sure, can you also share your ifc file? If private, send to dion@thinkmoult.com

**Comment by Edralos** [comment]
Saving and opening as blend file shows the same problem.
Here is one of the files I use.
[20160125Trapelo - Existing-Trapelo_Design_Intent.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5775152/20160125Trapelo.-.Existing-Trapelo_Design_Intent.zip)

**Comment by Moult** [comment]
I think it is specific to Blender and your graphics card. Can you try on another machine? I can open the IFC without any issues.
![2021-01-06-214446_1920x1080_scrot](https://user-images.githubusercontent.com/88302/103759860-72562080-5068-11eb-957b-8acf78ff2c7d.png)

**Comment by Edralos** [comment]
You're right !! I also tried it with another machine and it worked too. Though I still have no idea on how to deal with this problem on my machine... I tried getting the last deiver for my GPU but to no effect.

**Comment by Moult** [comment]
Awesome! I would recommend filing a Blender bugreport: https://wiki.blender.org/wiki/Process/Bug_Reports :) The Blender devs should be able to help! Good luck!
