### ISSUE TITLE
Can .xml connect to .glTF?

### ISSUE THREAD

**Issue by HWAZWD** [IfcOpenShell/IfcOpenShell#1245]
I've got two files,one is .xml and the other is .glTF.Now I load the .gltf file with Three.js,I was wondering when clicking a part of the model,how can I get the corresponding information stored in the .xml file?If not,any suggestions? Thanks a lot!

**Comment by aothms** [comment]
The IDs are the same. Just IFC uses a base64 encoding mechanism. In python you have ifcopenshell.guid.compress() / expand(). There is also a Javascript implementation here https://github.com/AECgeeks/BIMsurfer2/blob/master/bimsurfer/src/Utils.js#L54

In general you might want to consider switching to https://github.com/AECgeeks/BIMsurfer2. It also uses threejs. But solves the issue of integrating with XML (and 2D SVG). You might also want to consider https://github.com/AECgeeks/ifc-pipeline which includes BIMsurfer2 and a Python based processing queue for the model conversion.

**Comment by HWAZWD** [comment]
@aothms  Thanks a lot,that's working!

**Comment by theRealSuperMario** [comment]
Is there any way you can toggle if you want base64 encoding or not in the output file when running `IfcConvert`? 

Me personally, I just want all the ids to be the same, regardless of the implementation details and output file formats.

Maybe that's just my personally taste, but I don't see a point in allowing this inconsistency in the first place, even if IFC is the format that does the weird thing. If the pipeline starts with IFC, the ids should just be kept in the same format throughout the pipeline.

What do you think?

**Comment by aothms** [comment]
The reasoning is that the glTF serializer is quite new. The previous approach to get glTF was through collada serializer and then collada2gltf. So I prefer these flows to be compatible. 

> I wrote a tiny script which just converts the guids back to base64, and it works fine

But isn't that the point? It doesn't matter much. It's just a preference of whether you choose consistency within the geometric output formats, or choose resemblance with IFC.
