### ISSUE TITLE
Crash with OCCT7

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#126]
`IfcConvert.exe --enable-layerset-slicing Duplex_A_20110907_optimized.ifc` crashes with OCCT7.

**Comment by aothms** [comment]
This issue appears to be resolved with the following fix:
https://github.com/IfcOpenShell/IfcOpenShell/commit/8efd9757b75744d06ce2e82f0a0a533c3ffe295a

Screenshot with offending element:
![layerset slicing crash](https://cloud.githubusercontent.com/assets/1096535/18168612/ddc4629c-7056-11e6-8730-883c272a9d40.png)

Being the center wall of the apartment one might expect its layers to be symmetrical. This might be a clue of where to look in more detail.

@Stinkfist0 Can you check whether with the commit above layerset slicing works better on you models? I observed the same issue as you described. No matter how I tried to isolate the offending element, I was never able to reproduce the issue on the element in isolation or with connecting elements.

**Comment by Stinkfist0** [comment]
Great that the crash is fixed, but testing the patch quickly and it would appear that this doesn't fix the problems I was having with slicing.
