### ISSUE TITLE
45 degree pipe bend mission on ifc parsing

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#1269]
Attache a simple ifc. The 45 degree pipe bend is missing in ifcopenshell, but Ifc++ does show it. 

[Project_IfcDuctFitting.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/5834625/Project_IfcDuctFitting.ifc.txt)

![Screenshot_20210119_093644](https://user-images.githubusercontent.com/6129869/105008905-22009a80-5a3a-11eb-820a-6bda01d64441.png)

**Comment by berndhahnebach** [comment]
view.ifcopenshell.org log ... 

`Error | Failed to convert: | #285=IfcSurfaceCurveSweptAreaSolid(#269,#284,#274,0.,45.,#281) | #307=IfcDuctFitting('0ZawzjP15FrvbpUmVoS3EJ',#42,'M_Round  Elbow:1 D:202272',$,'M_Round Elbow:1  D',#306,#300,'202272',.NOTDEFINED.)`

**Comment by aothms** [comment]
Good one @berndhahnebach I was waiting for a good reference for this to implement. I've added support for it, but it's lacking quite a bit of error handling.

**Comment by berndhahnebach** [comment]
![Screenshot_20210128_075238](https://user-images.githubusercontent.com/6129869/106101240-e488c500-613d-11eb-9d99-b18f58f4b84b.png)
