### ISSUE TITLE
IfcOpenBot has disappeared?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1275]
https://github.com/IfcOpenBot gives me a 404? :(

**Comment by FreakTheMighty** [comment]
@aothms any updates on this?

**Comment by Moult** [comment]
If it helps anyone, this is the last build the bot did before it was MIA.

Hi,

I've created the following builds for your commit:

|\
 | Linux | Win | macOS |
| --- | --- | --- | --- |
| Blender py37 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-37-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-37-v0.6.0-3bbdc3f-linux32.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-37-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-37-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-37-v0.6.0-3bbdc3f-macos64.zip) |
| Blender py38 | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-38-v0.6.0-3bbdc3f-linux32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-38-v0.6.0-3bbdc3f-linux64.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-38-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-38-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-38-v0.6.0-3bbdc3f-macos64.zip) |
| Blender py39 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-39-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-39-v0.6.0-3bbdc3f-linux32.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-39-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-39-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcblender-python-39-v0.6.0-3bbdc3f-macos64.zip) |
| IfcConvert | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcConvert-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcConvert-v0.6.0-3bbdc3f-linux32.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcConvert-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcConvert-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcConvert-v0.6.0-3bbdc3f-macos64.zip) |
| IfcGeomServer | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-3bbdc3f-linux32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-3bbdc3f-linux64.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-3bbdc3f-macos64.zip) |
| Python 27 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27-v0.6.0-3bbdc3f-linux32.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27-v0.6.0-3bbdc3f-macos64.zip) |
| Python 27u | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27u-v0.6.0-3bbdc3f-linux32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27u-v0.6.0-3bbdc3f-linux64.zip) |\
 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27u-v0.6.0-3bbdc3f-macos64.zip) |
| Python 32 | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-32-v0.6.0-3bbdc3f-linux32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-32-v0.6.0-3bbdc3f-linux64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-32-v0.6.0-3bbdc3f-win64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-32-v0.6.0-3bbdc3f-win32.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-32-v0.6.0-3bbdc3f-macos64.zip) |
| Python 32u | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-32u-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-32u-v0.6.0-3bbdc3f-linux32.zip) |\
 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-32u-v0.6.0-3bbdc3f-macos64.zip) |
| Python 33 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-33-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-33-v0.6.0-3bbdc3f-linux32.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-33-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-33-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-33-v0.6.0-3bbdc3f-macos64.zip) |
| Python 34 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-34-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-34-v0.6.0-3bbdc3f-linux32.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-34-v0.6.0-3bbdc3f-win64.zip) |\
 |
| Python 35 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-35-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-35-v0.6.0-3bbdc3f-linux32.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-35-v0.6.0-3bbdc3f-win64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-35-v0.6.0-3bbdc3f-win32.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-35-v0.6.0-3bbdc3f-macos64.zip) |
| Python 36 | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-36-v0.6.0-3bbdc3f-linux32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-36-v0.6.0-3bbdc3f-linux64.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-36-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-36-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-36-v0.6.0-3bbdc3f-macos64.zip) |
| Python 37 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.6.0-3bbdc3f-linux32.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.6.0-3bbdc3f-macos64.zip) |
| Python 38 | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-38-v0.6.0-3bbdc3f-linux64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-38-v0.6.0-3bbdc3f-linux32.zip) | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-38-v0.6.0-3bbdc3f-win32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-38-v0.6.0-3bbdc3f-win64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-38-v0.6.0-3bbdc3f-macos64.zip) |
| Python 39 | [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-v0.6.0-3bbdc3f-linux32.zip) / [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-v0.6.0-3bbdc3f-linux64.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-v0.6.0-3bbdc3f-win64.zip) / [32bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-v0.6.0-3bbdc3f-win32.zip) | [64bit](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-v0.6.0-3bbdc3f-macos64.zip) |

Kind regards,\
IfcOpenBot

---\

**Comment by aothms** [comment]
Account has been flagged by @Github. Frankly this has been happening a lot to me lately for various accounts, but typically it gets restored quickly after a support ticket.

**Comment by FreakTheMighty** [comment]
@aothms thanks for the update, bummer. @Moult thank you for the build links, that is indeed helpful and good to know that the download links aren't broken.

**Comment by FreakTheMighty** [comment]
@aothms I wonder, is there any reason the build bot doesn't just post builds to this repo?

**Comment by aothms** [comment]
Yes I guess that would have been possible, I was trying to avoid spamming contributors with notifications, but it turned out I think they still get the notification even when the comment was on a fork they are not watching.

In this case it would probably still mean though that the commit comments for a flagged account would not be visible to other users.

Still no word from Github.

**Comment by aothms** [comment]
The flag has been removed and the repo is visible again

**Comment by Moult** [comment]
Hooray!
