### ISSUE TITLE
IfcOpenShell does not recognize serialization of SELECT (4.3)?

### ISSUE THREAD

**Issue by GiuMn** [IfcOpenShell/IfcOpenShell#1276]
I've been using BIMTester integrated with IfcOpenShell to validate an IFC file for IFC Rail, and I've come across a problem.

It seems that IfcOpenShell does not recognize the serialization of [SELECT ](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/link/ifcfacilityparttypeselect.htm)for IfcFacilityPart. In particular,  STEP serializes the SELECT for the PredefinedType by wrapping the value with the class name. 

I tried modifying the IFC file by writing the predefined type argument as an Enum (as it was in IFC 4.2) and passes the validation.
Is it possible to fix this?

Here an **Example**:

*this is how the STEP file should be written in 4.3*
=IFCFACILITYPART(‘2rZAYplcf7Hu4GBw_FfuTH’,$,'CircularQuay’,$,$,$,$,$,$,**IFCMARINEPARTTYPEENUM(.BERTHINGSTRUCTURE.),**.NOTDEFINED.);

*this is how it was done in 4.2 and it is recognized by IfcOpenShell*
= IFCFACILITYPART('0AS_KCenrFxQym6$QHvEr5',$, 'T1', $, $, $, $, $, .ELEMENT., **.TRACKSTRUCTUREPART.,** .LONGITUDINAL.);

**Comment by aothms** [comment]
That's true, it's not the select that's the problem, but the select of enumeration. That's a new modelling construct in 4.3 and does not work well with how enumeration is implemented in IfcOpenShell and how selects specify their members. I'm aware of this issue, It's on my list to fix this, but I need to find a way without braking changes in the APIs.

**Comment by GiuMn** [comment]
@aothms Thanks for the reply. Please keep us updated on this.

**Comment by aothms** [comment]
I've made some progress on this issue:

* 08576e28 fixed boxed enum validation
* b3f581d7 Handle boxed enum creation in Python
* 89d6b3d2 Fixes for RC2 changes re IfcPoint and IfcSegment
* d2bf2cf4 Pick RC2 definitions where required
* 43b2982d fix char encoding issue in source
* e750a134 Add generated rc2 schemas
* 6bbbc528 prep for 4x3_rc2
* 7f4a4367 regen schema
* e6592ca7 conversion rules for first citizin enum types #1276

The following script now runs successfully, i.e create the aforementioned IfcFacilityPart and validate it.

```
import logging
import ifcopenshell
import ifcopenshell.validate

logger = logging.getLogger("validate")
logger.setLevel(logging.DEBUG)

f = ifcopenshell.file(schema='IFC4X3_RC2')
f.createIfcFacilityPart(
    ifcopenshell.guid.new(),
    PredefinedType=f.createIfcMarinePartTypeEnum('BERTHINGSTRUCTURE'),
    UsageType='NOTDEFINED')
f.write('test.ifc')

print(f[1])

ifcopenshell.validate.validate(f, logger)
```

**Comment by aothms** [comment]
The latest builds on the website should have this functionality available now

**Comment by rbertucat** [comment]
OK we could confirm this was fixed. The issue can be closed.

@aothms is there any documentation supporting the `validate` function please?

**Comment by aothms** [comment]
@rbertucat I've added a bit. Let me know if you miss something or have clarifying questions. https://github.com/IfcOpenShell/IfcOpenShell/commit/3eacd809b0dc0c4d03d4675f3f64a509cb27789f

**Comment by JHJHJHJH** [comment]
Hi @aothms,

I met with a similar problem with enums for [IfcSpatialZone](http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcSpatialZone.htm) `PredefinedType`.

![image](https://user-images.githubusercontent.com/37946266/190287538-1da74bcf-546c-4887-8c49-b07185cbf099.png)

Will IfcSpatialZone be supported?

**Comment by Moult** [comment]
@JHJHJHJH IfcSpatialZone in 4.3 does not have a select of enums, so there is no issue?

```
>>> e = f.createIfcSpatialZone(PredefinedType='RESERVATION')
>>> e
#2=IfcSpatialZone($,$,$,$,$,$,$,$,.RESERVATION.)
```

**Comment by JHJHJHJH** [comment]
Odd, do i have to set the schema version ? Im getting the same error when i do the same as you.

Im using v0.6.0, could that be the reason ?
![image](https://user-images.githubusercontent.com/37946266/190339411-04be5c23-8b1d-4edb-9555-3ef8f5763980.png)

**Comment by Moult** [comment]
v0.6.0 is pretty (very) ancient :) Try upgrade https://blenderbim.org/docs-python/ifcopenshell-python/installation.html

**Comment by JHJHJHJH** [comment]
Installed latest, and set `schema_identifier` to IFC4x3. Working for me now !

**Comment by aothms** [comment]
Also note that all three situations where there were selects of enum have since been removed from the final 4.3 schema https://github.com/buildingSMART/IFC4.3.x-development/issues/90

Also support has been implemented for it some time ago https://github.com/IfcOpenShell/IfcOpenShell/issues/1276#issuecomment-778802255
