### ISSUE TITLE
Binaries for max2017x64

### ISSUE THREAD

**Issue by deshudiosh** [IfcOpenShell/IfcOpenShell#1279]
Hi. I am not really very well into this compilation stuff. Is there any chance someone will provide use-ready max2017 plugin files?

**Comment by aothms** [comment]
Michaelson Britt has been working on reviving and rebuilding the
IfcOpenShell IFC importer for @Autodesk 3ds Max https://t.co/0fMepSTV8D

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 28 jan. 2021 16:40 schreef deshudiosh <notifications@github.com>:

**Comment by Moult** [comment]
It's great to see that the Max code is updated for recent Max versions like 2023. @aothms what would you suggest as an official stance on the Max code? Could we revive development via spacefrog and give him commit rights? Do we mention it somewhere in the docs / download page? Or do we completely cut all ties with the Max thing? (right now, the website has zero mention of it, though the README.md still mentions it)

**Comment by Moult** [comment]
Closing as binaries are documented and available since 2015. https://blenderbim.org/docs-python/ifcmax.html
