### ISSUE TITLE
BlenderBIM: crashes when reassigning class

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1281]
blender28-bim-210131-win
2.91

video: https://www.dropbox.com/s/6qrp22xwjtwzo6c/2021-01-31_14-23-45.mp4?dl=0

**Comment by Moult** [comment]
Cannot reproduce. Can you check your addons folder i.e. on windows AppData/Roaming/Blender Foundation/2.91/scripts/addons/ and in there do you see a folder called ifcopenshell? If so, delete it. It sounds like you may not have the latest IfcOpenShell for some reason.

**Comment by theoryshaw** [comment]
delete that folder?

![image](https://user-images.githubusercontent.com/507113/106696575-a1e24500-65a2-11eb-9724-6c71d1ab3277.png)

**Comment by Moult** [comment]
Hmmmmm... nope. Let's screenshare sometime.

**Comment by Moult** [comment]
Closing, as @aothms seems to have fixed it in the latest build! :D
