### ISSUE TITLE
BlenderBIM: dumb IFC objects don't have assigned class

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1283]
blender28-bim-210131-win
2.91

video: https://www.dropbox.com/s/ro1fghgkjjhe0xo/2021-01-31_14-31-21.mp4?dl=0

**Comment by Moult** [comment]
Ah yes, this was a change in the workflow that I don't really think is a good idea... I'll try to find a good workflow solution.

**Comment by theoryshaw** [comment]
Seems like it's still an issue: https://www.dropbox.com/s/z9de6hmybrq9jub/2021-02-21_08-53-33.mp4?dl=0

2.91 - 210221-win

**Comment by theoryshaw** [comment]
nevermind, i see you have to start an IFC project first.
