### ISSUE TITLE
IfcAnnotationFillArea not supported

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1291]
The file shown in #1142 has an IfcAnnotation using an IfcAnnotationFillArea. It seems to be a simple curve object - is there a reason that create_shape fails on it? Creating the curve would be sufficient, I believe.

**Comment by aothms** [comment]
Just not property implemented. Would be a nice task to wet your feet in C++. You're right it's basically equivalent to an arbitrary pdef with voids https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcRegister.h#L101 https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomFaces.cpp#L458

**Comment by Moult** [comment]
Closing as fixed :)
