### ISSUE TITLE
Is there a way to query the schema for possible associated types?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1300]
E.g. an IfcWall may be typed by an IfcWallType, and vice versa. Can I discover this relationship programmatically?

In IFC4 an intelligent guess may be made, but it isn't always straightforward, and in IFC2X3 there are tricky situations.

Edit: the usecase is to allow the user within the BlenderBIM Add-on to easily create a product from a type product, or to help guide the user on the correct type product to assign to a product.

**Comment by aothms** [comment]
I think this is only encoded in the where rules (with occasional typos https://github.com/stepcode/stepcode/pull/373/files) so I don't have high hopes for this, but let's root for https://github.com/opencax/GSoC/issues/31

**Comment by Moult** [comment]
It seems as though this is missing in IFC2X3? I may need to just make something up :)

https://forums.buildingsmart.org/t/where-are-correct-type-relationships-described-in-ifc2x3/3345

**Comment by Moult** [comment]
I built a hacky thing just for a quick solution, but happy to rebuild later if/when https://github.com/opencax/GSoC/issues/31 gets solved :)

**Comment by aothms** [comment]
@Moult 

We do have where rule tokenization, so we can add a (let's say) where_rule_by_name() function to the schema decls that just spits out the where rule as a string. Maybe it makes the solution a little bit hacky as you don't need to pregenerate jsons, but can just do it from the internal schema rep in ifcopenshell? Let me know if you're interested and I can quickly add that.

Also a quick heads up that 4.3 introduced select types for predefinedtype. So the type of PredefinedType is actually a Select which selects among a handful of Enums.
