### ISSUE TITLE
Can I set a mandatory attribute as null?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1301]
If I create an element, mandatory attributes start as null. However, if they do get assigned to a non-null value, I am not allowed to set them back to null.

Little minimal case to trigger the error in code snippet below.

The usecase for this is to aid in deep element removals. Sometimes, I want to delete deeply, especially in the representation tree, but it may be referencing a context, or mapped representation that I don't want it to consider for deletion in the tree. My little workaround was to create a temporary dummy element and assign to that, and then the remove_deep() call will delete it nicely. However, if I could simply set it back to null, that would be more elegant.

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> w = f.createIfcWall()
>>> w.GlobalId = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/ifcopenshell/entity_instance.py", line 112, in __setattr__
    self[self.wrapped_data.get_argument_index(key)] = value
  File "/usr/lib/python3.7/site-packages/ifcopenshell/entity_instance.py", line 127, in __setitem__
    self.wrapped_data.setArgumentAsNull(idx)
  File "/usr/lib/python3.7/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 1584, in setArgumentAsNull
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsNull(self, i)
RuntimeError: Attribute not set
```

**Comment by aothms** [comment]
So what do you recommend? I have mixed feeling about removing the last bit of type checking that we actually do.

Shouldn't we rather have have add an optional set of elements to `remove_deep()` which will then retain elements in this set?

**Comment by Moult** [comment]
@aothms on second thoughts, this is swapping one workaround for another, so I agree that changing `remove_deep()` is a better approach.

 Closing bug :)
