### ISSUE TITLE
IfcConvert parse the GlobalID to COLLADA not working

### ISSUE THREAD

**Issue by alikucukavci** [IfcOpenShell/IfcOpenShell#1303]
Hi there, 

I am trying to build an application that can 
1. convert an IFC file to DAE
2. convert DAE to GLTF
3. visualize GLTF in Three js (3D viewer)

When I convert from IFC to DAE and try to lookup any IFC GlobalId's in the DAE file, I find nothing. It seems like the DAE file got new ID's. **How can I parse any information (GUID, or other metadata) to the DAE file?** 

I tried with   
1. IfcConvert duplex.ifc duplex.dae --include arg GlobalId
2. IfcConvert -v --use-element-guids duplex.ifc duplex.dae

But it is not working. Can anyone tell me if it is possible and how to write that correctly in IfcConvert?

A picture of the 3D viewer is shown below. I am trying to console.log the name and ID of the loaded GLTF file in ThreeJS and which gives something that cannot be found in the IFC file. 
 ![Duplexhouse](https://user-images.githubusercontent.com/22770558/107214558-5698be00-6a0a-11eb-9fb6-6ce00cebd007.PNG)

**Comment by aothms** [comment]
Ifc globalids are not valid XML ids, so we reverse the base64 encoding. https://technical.buildingsmart.org/resources/ifcimplementationguidance/ifc-guid/ https://github.com/AECgeeks/BIMsurfer2/blob/master/bimsurfer/src/Utils.js#L54

--use-element-guids does encode the global ids as (invalid) xml ids directly in the file though, can you explain how that did not work.

**Comment by alikucukavci** [comment]
Hi aothm, 

My bad. 
I looked at the wrong place before. Tried --use-element-guids again and now it is working. 

Picture of ThreeJS showing it is working now :) 
![Duplexhouse](https://user-images.githubusercontent.com/22770558/107220050-2f45ef00-6a12-11eb-93b0-7a534aea757b.PNG)

**Comment by Gipfel** [comment]
> Hi aothm,
> 
> My bad. I looked at the wrong place before. Tried --use-element-guids again and now it is working.
> 
> Picture of ThreeJS showing it is working now :) ![Duplexhouse](https://user-images.githubusercontent.com/22770558/107220050-2f45ef00-6a12-11eb-93b0-7a534aea757b.PNG)

Hey there, could you please help me out?
It isn't really working for me. I am working on Windows ad that is the command I run:
IfcConvert.exe -v --use-element-guids R22.ifc test.glb
and it's still not keeping it as a GUID..

Thanks in advance !
