### ISSUE TITLE
BUG: IFC 4.3 Validation

### ISSUE THREAD

**Issue by GiuMn** [IfcOpenShell/IfcOpenShell#1304]
I am trying to validate a file through IfcOpenShell Python validate function, which I know has a mistake.
For some reason, IfcOpenshell reports an error, but it seems that it cannot show what the error is.

Attached is the message I receive when trying to to run validation and also the ifc file used as a test. 

[file_test_bug.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/5944848/file_test_bug.txt)
![validation message](https://user-images.githubusercontent.com/71768195/107245157-20216a00-6a2f-11eb-8fa2-f004943916d6.PNG)

**Comment by aothms** [comment]
This is already fixed, you can just replace validate.py on your system with the latest version from the repo https://github.com/IfcOpenShell/IfcOpenShell/commit/500467b3a8140b106016992c651f0e114be9af7c

**Comment by rbertucat** [comment]
OK we could confirm this was fixed. The issue can be closed

**Comment by GiuMn** [comment]
issue fixed. Closed issue
