### ISSUE TITLE
Trying to understand the mapping of connector coordinates

### ISSUE THREAD

**Issue by MikkiSeidenschnur** [IfcOpenShell/IfcOpenShell#1310]
Hello,

This is my first time posting here, so excuse me if this is irrelevant. 

For the past couple of months, I have been working on creating a class hierarchy of a pipe system based of an IFC extracted from Revit. Picture seen below.
![image](https://user-images.githubusercontent.com/20814326/107385939-aa330680-6af3-11eb-8f07-f6f66e2cede0.png)

I've specifically created a class, for connection information and following coordinates class:

``` python
class Connector:
    def __init__(self, connector_tag, coordinates):
        self.connector_tag = connector_tag
        self.coordinates = coordinates>
```

``` python 
class Coordinates:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z
```

In the connector class, I want to extract the coordinates of the "IfcRelConnectsPorts", as the end of that pipe segment. And this is somewhat successful. 

I use this mapper to map the connections

``` python 
def connection_mapper(ifc_file):>
    component_connections_lookup = {}
    connectors_by_port = ifc_file.by_type("IfcRelConnectsPorts")

    for connector in connectors_by_port:
        init_in = {"inport": [], "outport": []}
        init_out = {"inport": [], "outport": []}
        
        outport_tag = connector.RelatedPort.Name
        inport_tag = connector.RelatingPort.Name

        outport_only_tag = outport_tag.split("_")[1]
        inport_only_tag = inport_tag.split("_")[1]

        if outport_only_tag not in component_connections_lookup:
            component_connections_lookup[outport_only_tag] = init_out

        if inport_only_tag not in component_connections_lookup:
            component_connections_lookup[inport_only_tag] = init_in
        
        coordinates = get_coordinates(connector)

        c_in = mapper_classes.Connector(outport_only_tag, coordinates)
        c_out = mapper_classes.Connector(inport_only_tag, coordinates)

        add_if_not_in_list(component_connections_lookup[inport_only_tag]["inport"], c_in)
        add_if_not_in_list(component_connections_lookup[outport_only_tag]["outport"], c_out)
```

I then use this path to retrieve the coordinates

``` python 
def get_coordinates(connector):

    coordinates = (connector.ObjectPlacement
                            .RelativePlacement
                            .Location
                            .Coordinates)

    x = coordinates[0]
    y = coordinates[1]
    z = coordinates[2]

    return mapper_classes.Coordinates(x, y, z)
```

The major problem here, is that sometimes I need to get the connection coordinates by the path:

``` python 
(connector.ObjectPlacement
                   .RelativePlacement
                   .Location
                   .Coordinates)
```

and sometimes I need to use the path:
``` python 
(connector.ObjectPlacement
                   .PlacementRelTo
                   .RelativePlacement
                   .Location
                   .Coordinates)
```

and I can't figure out what the difference is. 

So I guess my question is: What is the behavior of this ObjectPlacement option, in relation to `IfcRelConnectsPorts`. 

I know this question might be a bit weird and unrelated, but I'm at a loss with the IFC documentation to figure out how this works. 

Best Regards
Mikki Seidenschnur

**Comment by aothms** [comment]
`ObjectPlacement` is an IfcLocalPlacement which consists a { a 'parent' placement (PlacementRelTo) , and a transformation  (RelativePlacement) } the whole set of placements forms a tree that should more or less follow the decomposition hierarchy (Site > B > Storey > Elem > Port).  So it appears that sometimes you want the position of the port, sometimes of the parent element? 

It appears though that connector is of type IfcRelConnectsPorts which does not have a ObjectPlacement (it's not a product/element). So that's confusing to me. There is also IfcRelConnectsPorts.RealizingElement that might have an ObjectPlacement. Is that somehow related perhaps?

**Comment by MikkiSeidenschnur** [comment]
I don't think that the `IFCRELCONNECTSPORTS` have any information in `RealizingElement`, but I will check it as soon as I have the files handy tomorrow. Will let you know what I find out. 

My problem is mainly that I can't figure out why it sometimes uses the absolute placement compared to the relative placement, and sometimes it doesn't. I can't seem to find any pattern as to why it's using one over the other at certain times in my example.

**Comment by aothms** [comment]
Sometimes that's also the case. Exporters are not perfect, especially in the more 'advanced' not directly visible cases. Try to really connect some evidence with snippets from the file and contact the authoring tool for input.

**Comment by MikkiSeidenschnur** [comment]
Ok, I will close this for now, thanks for helping out!
