### ISSUE TITLE
Import second IFC model gives error

### ISSUE THREAD

**Issue by jc4d** [IfcOpenShell/IfcOpenShell#1313]
Everytime I try to import a second ifc file, blender throws me this error:
Is this a limitation or a bug?

Python: Traceback (most recent call last):
  File "C:\Users\*******\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\operator.py", line 163, in execute
    ifc_importer.execute()
  File "C:\Users\*******\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\import_ifc.py", line 319, in execute
    self.load_existing_rooted_elements()
  File "C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\import_ifc.py", line 1105, in load_existing_rooted_elements
    self.existing_elements[self.file.by_id(obj.BIMObjectProperties.ifc_definition_id).GlobalId] = obj
AttributeError: 'NoneType' object has no attribute 'by_id'

location: <unknown location>:-1

**Comment by Moult** [comment]
I believe this has already been fixed in https://github.com/IfcOpenShell/IfcOpenShell/commit/04a2949d75c837ee38b51451b5e3bb0e4e3d5e8c - the fix will be out in the next release, or you can patch it now yourself.

If that patch doesn't work for you, let me know :)

A heads up that I am extremely busy this week and do not have time to address these bugs immediately, but thank you so much for your report and I will certainly fix them!

**Comment by jc4d** [comment]
Thanks for the fast response :)
I opened the import_ifc.py and changed it following your fixing and reloaded Blender. Sadly didn't work, I bet I did something wrong :D

![image](https://user-images.githubusercontent.com/35140348/107634221-dd030900-6c71-11eb-84c3-7493e6223ac9.png)

**Comment by Moult** [comment]
@jc4d it looks like you did it correctly ... did the error message change? If it is still broken, send me a message on the OSArch live chat (https://osarch.org/) during Sydney waking hours or let's organise a time during sydney waking hours to screenshare and debug this. We can meet online using https://meet.jit.si/openbim

**Comment by jc4d** [comment]
The only thing that changed is the line were the error happens, now is in the line 321

Python: Traceback (most recent call last):
  File "C:\Users\jcfna\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\operator.py", line 163, in execute
    ifc_importer.execute()
  File "C:\Users\jcfna\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\import_ifc.py", line 321, in execute
    self.load_existing_rooted_elements()
  File "C:\Users\jcfna\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\import_ifc.py", line 1105, in load_existing_rooted_elements
    self.existing_elements[self.file.by_id(obj.BIMObjectProperties.ifc_definition_id).GlobalId] = obj
  File "C:\Users\jcfna\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 65, in __getattr__
    "entity instance of type '%s' has no attribute '%s'" % (self.wrapped_data.is_a(), name))
AttributeError: entity instance of type 'IfcProductDefinitionShape' has no attribute 'GlobalId'

location: <unknown location>:-1

I'm contacting you via the Osarch livechat

**Comment by Moult** [comment]
@jc4d ah that sounds as though you had existing IFC elements in there from a totally different IFC file, and then are now importing from yet another IFC file. That can cause your bug. I'll put out a fix.

**Comment by jc4d** [comment]
@Moult Yes, I first import one ifc file and then I try to import a seconf ifc file to the same blender file where the first one is imported and this is the problem. Sorry if I wasn't clear enough before :)

**Comment by Moult** [comment]
@jc4d the general approach I've taken is to have 1 Blend file = 1 IFC file, and then link it all into a master Blend file. Is that something you might consider?

**Comment by jc4d** [comment]
Is what we have been trying to avoid since we normally deal with +15 separated ifc files and doing my hand, importing each one saving each one and the manually looking for the rigth collection is so much time consuming that budget timed projects will go into that only.
I tried dragging many files into one blender file but only one is brougth.

**Comment by Moult** [comment]
This is now fixed, but keep in mind that the current design only allows a single IFC file to be in memory at once. This is an annoying limitation but not critical to fix this bug. For the moment, you will need to browse to the appropriate IFC file in the IFC Project panel if you want to view data from that particular project.

The situation will be improved in coming releases, but at least for now it works.

By the way, there is a "Link IFC" feature in the Annotation Panel (a terrible UI decision, I know) in the "N" properties of the 3D viewport where if you browse to a Blender file with an IFC imported into it already, it'll link it into your current project. It's not fully automated as you've suggested, but at least it is partially automated. Again, this is something that is planned to be improved.
