### ISSUE TITLE
BlenderBIM Importing model 1,000x too far away

### ISSUE THREAD

**Issue by tldddd** [IfcOpenShell/IfcOpenShell#1315]
When importing the attached model the location is offset by 1,000x. This causes the model to be imported a very long way from the origin and therefore doesn't import correctly due to being a long way from the origin. The model loads correctly in all other model viewers tested.

The IFC file unit settings are in millimeters
`#4357 = IFCSIUNIT(*, .LENGTHUNIT., .MILLI., .METRE.);`

An example point is:
`#714=IFCCARTESIANPOINT((1746700.,-13884.8375616912,5966306.84638379));`
This is roughly 1.7km, -13m, 5.9km. There are no other local placement transforms.

The Blender unit settings before import are:
![Pre-import settings](https://user-images.githubusercontent.com/33082902/107617508-f42d0100-6c47-11eb-8e2a-91014e02c039.png)
However changing these before import has no affect on where the model is placed.

Once imported an example point is at:
![Import coordinates](https://user-images.githubusercontent.com/33082902/107617525-fbeca580-6c47-11eb-8107-d707ebd1d402.png)

This is roughly -1,744km 10km, -5,962km. Due to the very large distance from the origin the geometry has not imported correctly either.

I can manually change the Blender scale settings to make the numbers correct, but that doesn't fix the problem of the model coming in too far away and the geometry being wrong.

See attached example IFC file. I've had to strip out a lot of data in order to upload it here, so that's why the STEP file may look a little odd, but I promise it's not affected the import issue.

[Slab.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5964001/Slab.zip)

**Comment by jc4d** [comment]
It just happened to me as well in a current project. Sadly I have to rely on other apps to bring ifc models into Blender.

**Comment by Moult** [comment]
Blender attempts to autodetect poorly geolocated models but sometimes, such as in this case, it fails. I will add an import option to specify a custom offset to accommodate this. I will also see if I can make the guessing mechanism faster.

A heads up that I am extremely busy this week and do not have time to address these bugs immediately, but thank you so much for your report and I will certainly fix them!

**Comment by Moult** [comment]
@jc4d can you share your file where you encountered a similar issue? Then I can fix it.

**Comment by Moult** [comment]
A heads up that you can use the ExtractElements IFC Patch recipe as a great way to strip out single or a subset of elements for debugging scenarios just like this.

**Comment by jc4d** [comment]
> 
> 
> @jc4d can you share your file where you encountered a similar issue? Then I can fix it.

I will ask tomorrow at the office if I can share a small file since we deal with sensitive information.

**Comment by Moult** [comment]
Fixed. I suspect this should also fix your issue @jc4d . Sorry, it was a regression in this release.
