### ISSUE TITLE
TopoDS_Solid Sphere Serialization failed!

### ISSUE THREAD

**Issue by Anish-Russel** [IfcOpenShell/IfcOpenShell#1316]
Hello,
I created a Speare using open cascade functions and tried to serialize it using the _**IfcGeom::serialise**_ function. But it fails. I have inserted the code below. Am I doing anything wrong? Can anyone guide me?

`int sub_routine() {
Standard_Real R = 30;
TopoDS_Solid Sphere = BRepPrimAPI_MakeSphere(R);
IfcUtil::IfcBaseClass *serial = IfcGeom::serialise("Ifc2x3", Sphere, false);
if (serial == nullptr) {
       std::cerr << "[Error] " << str << " serialization failed!" << std::endl;
       return;
}
std::cerr << "[Success] " << str << " serialization Passed!" << std::endl;
}`

Note: 
          IfcOpenshell Version: v0.6.0
          Opencascade version: 7.4.0

**Comment by aothms** [comment]
You cannot serialize a sphere in Ifc2x3, the entities (Advanced BRep) are simply not there in the schema. You have to use IFC4 or higher or use tesselate(). Periodic surfaces might work, but are not fully implemented yet in terms of proper IfcSeamCurve and PCurves, which might be necessary by some importing applications (if you can find them, adv brep is not well supported yet in software).
