### ISSUE TITLE
Can't install blenderbim v0.0.210131

### ISSUE THREAD

**Issue by bluetw** [IfcOpenShell/IfcOpenShell#1318]
I keep getting an
`AttributeError: module 'parse' has no attribute 'Parser'`

I've tried installing it on a 2.82 and 2.91 version of blender, I get the same errors.
I've tried installing it on clean, newly installed versions of blender, still no luck.
I've also tried clearing the addons folder, same error. 

I'm running Ubuntu 18.04

**Comment by Moult** [comment]
A few people have reported this and it puzzles me.

Can you screenshot what's inside your Blender add-ons dir (on Windows this is `C:\Users\you\AppData\Roaming\Blender Foundation\2.91\scripts\addons`), as well as what's inside the `blenderbim/libs/site/packages/` folder? Do you see a `parse.py` file there? Do you see a `blenderbim/libs/site/packages/parse_type/` folder? Can you also screenshot what's in there?

Can you search for all files called `parse.py` in your addons folder, and paste it as a zip here for me to see?

You may be interested in joining the OSArch.org live chat where you can catch me online to screenshare and hopefully I can crack it over a screenshare.

**Comment by bluetw** [comment]
I'm not exactly sure how the install function on blender works, but installing any addons using the GUI doesn't unpack the contents in the `/scripts/addons` folder, but instead in the `~/.config/blender/2.x/scripts/addons/blenderbim` folder. This may be a side effect of using multiple versions of blender via unpacking their zip files instead of installing with a package manager, but once again, I don't know enough about how blender works.

That aside, here is a screenshot of `/blender-2.91.2-linux64/2.91/scripts/addons`:
![blender_addons](https://user-images.githubusercontent.com/77814539/107895558-c1984680-6f6e-11eb-981d-e4fc3be9a434.png)

This is what's inside the `~/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages`:
![blenderbim_site-packages](https://user-images.githubusercontent.com/77814539/107895905-d88b6880-6f6f-11eb-9e1b-27d7d602597e.png)

Yes, there is both a `parse.py` and `~/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/parse_type` folder. Here's what's inside the `parse_type` folder:
![blender_parse-type](https://user-images.githubusercontent.com/77814539/107896397-1b9a0b80-6f71-11eb-9210-905bff3ec444.png)

Within the `/blender-2.91.2-linux64/2.91/scripts/addons`, there is no `parse.py` file.
Inside `~/.config/blender/2.91/scripts/addons/blenderbim`, there are two `parse.py` files. The first one is in `/site/packages`, while the other one is in `/site/packages/parse_type`. They are attached in a zip file, both named respectively.  
[parse.py.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5979070/parse.py.zip)

I'll give that a try if other solutions fail.  Thank you!

**Comment by Moult** [comment]
So far everything looks fine to me. @bluetw would you be available for a screenshare? I'm available during Sydney waking hours. When works best for you? We can meet on https://meet.jit.si/openbim

**Comment by bluetw** [comment]
Sure! Are you available around 5pm Sydney time tomorrow? Thank you!

**Comment by Moult** [comment]
@bluetw yes. Alternatively, I am online for the remainder of tonight. You can go to the live chat at osarch.org and send me a message.

If that doesn't work for you, happy to be online at the jitsi link at 5pm tomortow.

**Comment by johntedharvey** [comment]
Hi guys.
Has this been resolved yet?
I have the same issue.
regards
John Harvey

**Comment by Moult** [comment]
@johntedharvey no - I will be online at https://meet.jit.si/openbim at 5pm Thu Feb 18 Sydney Australia timezone to screenshare and debug with @bluetw . If you are able to screenshare with me earlier than that during a Sydney waking hour, let me know and I'll be online. I'm going to sleep now, but will be available 8:30am onwards tomorrow.

**Comment by johntedharvey** [comment]
Hi Dion.

Thank you for your reply. I will be in touch.

regards
John

**Comment by bluetw** [comment]
Hey @Moult, the most peculiar thing happened today. I had to restart my pc a couple of times and the addon now works on blender 2.92. Unfortunately, it still shows the same error in 2.82. I've installed nothing, nor have I tinkered with any of my settings/installations. What could a possible problem be? Was it really just as simple as turning my computer on and off?

**Comment by Moult** [comment]
@bluetw perhaps... i'll be online in a couple minutes at https://meet.jit.si/openbim so hopefully you can demonstrate the problem on 2.82 and that can help narrow it down.

**Comment by Moult** [comment]
A short explanation to those who come across this - the Blender-OSM add-on defines a module named parse, which clashes with the parse module required by behave (pulled in by BIMTester). We can't fix the name clash, at least I'm not aware of a solution as none of this code is part of the BlenderBIM Add-on, so at the very least we can prevent an installation failure and warn users.

**Comment by aothms** [comment]
Maybe there is way you can temporarily hack the `sys.path` (not to be confused with $PATH) to exclude other addon directories when doing the blenderbim import statements. And then restore the path afterwards. Also you might have to hack `sys.modules` to force it reimport the behave.parse when the OSM.parse already is loaded. It's ugly, but I think there must be a way to get this to work.

**Comment by johntedharvey** [comment]
Hi Dion.

Thanks for copying me in on this.
I haven't had a chance to read through yet. I Will do this tomorrow.

regards
John Harvey

**Comment by Moult** [comment]
I'm generally against magic hacks - given that this is BIMTester, not the core BlenderBIM functionality, and that it's pretty uncommon (i.e. only OSM, which is not vital to be loaded all the time too) - I'll try to leave it without hacks as long as possible.
