### ISSUE TITLE
BlenderBIM: Have the imperial dimension decorations show fractions in 3d viewport

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1321]
This is somewhat of a minor priority, but thought I'd log nonetheless, as it's might be a good first issue

![image](https://user-images.githubusercontent.com/507113/107882458-170d1e80-6eaf-11eb-8bd5-7699599f445a.png)

**Comment by Moult** [comment]
There was a conscious decision not to do this, due to the potential lag it may cause as it needs to be calculated on each frame update, see: https://github.com/IfcOpenShell/IfcOpenShell/issues/1164

We may revisit this in the future.

**Comment by Moult** [comment]
Ping @qwiglydee can you check how painful this actually is in terms of performance? Can we live with the Python implementation? Maybe this is worth an upstream bug?

**Comment by qwiglydee** [comment]
> Ping @qwiglydee can you check how painful this actually is in terms of performance? Can we live with the Python implementation? Maybe this is worth an upstream bug?

The function itself is 5.5 times slower. 
It slows down rendering by 8%. Quite noticeable, but definitely not severe.

The bottleneck is text labels rendering.
Overall handler execution time profile looks like this: handler stuff: 8%, extracting data: 5%, drawing: 27%, labeling: 48%, formatting (bl.utils, imperial): 12%

**Comment by Moult** [comment]
Let's try for an upstream bug. @theoryshaw  could you open one?

**Comment by Moult** [comment]
@theoryshaw basically say that blender's imperial dimensions as formatted by bpy.utils.units.to_string don't follow imperial conventions. Give them the example of 2' 5.5" and say it should be 5' - 5 1/2", and explain how it should follow 1/2^n increments depending on chosen precision.

**Comment by theoryshaw** [comment]
Gotta.  Will do.  Thought you were talking about Python performance, or something--thus confused. :)

**Comment by theoryshaw** [comment]
https://developer.blender.org/T86310

**Comment by Jesusbill** [comment]
There was a typo: 2' 5.5" should be 2' - 5 1/2" not 5' - 5 1/2"

**Comment by theoryshaw** [comment]
Thanks Ioannis.  I fixed it.

**Comment by Moult** [comment]
ping @ecke101 - what do you reckon? Straightforward patch?

**Comment by ecke101** [comment]
> 
> 
> ping @ecke101 - what do you reckon? Straightforward patch?

I looked at it when the task was created but it wasn't that easy because the same conversion function was used for user input if I remember correctly.

**Comment by Moult** [comment]
Note to self: I'd like to consider retesting this using the `@lru_cache` decorator, potentially that would solve the performance problem and we can go and use the same function for drawing display and viewport display.
