### ISSUE TITLE
Encoding error : wstring_convert::to_bytes

### ISSUE THREAD

**Issue by bdaniere** [IfcOpenShell/IfcOpenShell#1322]
Hi,

I'm encountering encoding problems when opening IFC files.
Problems were not detected at the time of reading but prevent some treatments afterward:
(I've put the few errors in a sample_wall.ifc as an attachment)
[simple_wall.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5989597/simple_wall.zip)

```
ifc_file = ifcopenshell.open("/home/simple_wall.ifc")
ifc_file[4]

  File "ifcopenshell_tools/ifcopenshell/entity_instance.py", line 164, in __repr__.
    return repr(self.wrapped_data)
  File "ifcopenshell_tools/ifcopenshell/ifcopenshell_wrapper.py", line 1659, in __repr__.
    return _ifcopenshell_wrapper.entity_instance___repr__(self)
RuntimeError: wstring_convert::to_by
```

For the moment, these blocking problems concern 3 characters :
     - "°": I added it on the IfcWall instance n° 45
     - "Ø": I added it on the IfcPerson instance n° 4
     - "é": I added it on the IfcWindow instance n° 124

This error is then found with IfcConvert (IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)) :

```
...
terminate called after throwing an instance of 'std::range_error'.
  what(): wstring_convert::to_bytes
```

  Do you have an idea of how to solve/counteract the problem? 
  Thank you

**Comment by aothms** [comment]
It's not valid in IFC(-SPF) to have character bytes above 0x7e. It's strictly ASCII. It needs to be encoded in a special way using code pages or \X2  / \X4 for unicode, see below:

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> f.createIfcPerson('°')
#1=IfcPerson('°',$,$,$,$,$,$,$)
>>> f.write('test.ifc')
>>> print(open('test.ifc').read())
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2021-02-17T15:02:37',(),(),'IfcOpenShell 0.6.0b0','IfcOpenShell 0.6.0b0','');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCPERSON('\X2\00B0\X0\',$,$,$,$,$,$,$);
ENDSEC;
END-ISO-10303-21;
```
