### ISSUE TITLE
Create a gizmo for extrusion depth

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1324]
Inputs are a coordinate (let me know if global vs local is better for you), and a vector, and a magnitude.

**Comment by theoryshaw** [comment]
Whatever these gizmos are, would be nice if there was a way to modify them en masse, if possible. 
Perhaps drawing some marque around them, and then moving them. 
![2021-02-17_17-58-08_blenderBlenderblender](https://user-images.githubusercontent.com/507113/108284057-12b06200-714a-11eb-82a9-d8f2a7355f44.png)

**Comment by htlcnn** [comment]
@theoryshaw is that visible when you enter Edit Mode, select the faces and use Move tool on the left?

**Comment by Moult** [comment]
@htlcnn that is valid for meshes, but not valid for parametric IFC geometry (not even Blender modifiers), of which the gizmos are addressing.

**Comment by theoryshaw** [comment]
perhaps a way to assign what it's relative to.

sorry, couldn't help myself. :)

![image](https://user-images.githubusercontent.com/507113/108302045-cfb1b700-7168-11eb-891b-4f59049474ea.png)

**Comment by qwiglydee** [comment]
> @htlcnn that is valid for meshes, but not valid for parametric IFC geometry (not even Blender modifiers), of which the gizmos are addressing.

This should be another pseudo-mode.
We can implement it with modal operators, similar to those already exist:
![Screenshot_20210218_191303](https://user-images.githubusercontent.com/285128/108356387-a5bacc00-721e-11eb-930a-69b7d803a92b.png)

I believe there's no need to mess with edit mode with all the vertices and stuff, and yet another internal mesh representation.

**Comment by qwiglydee** [comment]
@Moult 
Perhaps, it would be better if I work not on gizmo alone, but on operator to create and modify an extrusion straight in IFC. 
Because I need to have some real use cases in mind (and not rely on my Blender-centric ideas).

**Comment by qwiglydee** [comment]
Here's what I have almost working (with simulatoin of parametric extrusion using blender stuff) 
![Screenshot_20210224_150303](https://user-images.githubusercontent.com/285128/108966948-750ce380-76b1-11eb-90f1-bac71d60d8a3.png)

And here's how I imagine the gizmo in other potential use cases.
![Screenshot_20210223_123150](https://user-images.githubusercontent.com/285128/108967064-9a99ed00-76b1-11eb-81ae-e18033c5bde7.png)

**Comment by theoryshaw** [comment]
Looks great.

Does your indented roadmap include a way to select multiple gizmos with a selection box, for example, and 'dragging' or entering their value together?

![image](https://user-images.githubusercontent.com/507113/109012543-be404180-7677-11eb-8478-d0727aacb4fc.png)

**Comment by qwiglydee** [comment]
> Does your indented roadmap include a way to select multiple gizmos with a selection box, for example, and 'dragging' or entering their value together?

It's possible to apply some modifications to all selected objects, the same way as standard operators work in Blender.

It would help if you tell what are particular use cases where it's useful.
Perhaps, constraints/relations between objects would solve the problem better.

**Comment by theoryshaw** [comment]
One particular use case, illustrated below, is if you wanted to extrude all the objects by 2ft, for example.  Doing something like this would be a lot easier if you could select all the extrusion gizmos, and move them in one operation, verses having to select every single extrusion individually and changing the extrusion depth.  

![image](https://user-images.githubusercontent.com/507113/109088270-bebaf580-76d4-11eb-9d11-dd3907233962.png)

![image](https://user-images.githubusercontent.com/507113/109088654-705a2680-76d5-11eb-966e-010119cf0076.png)

**Comment by qwiglydee** [comment]
https://user-images.githubusercontent.com/285128/109492607-ce17b580-7abd-11eb-99e6-eb0e6d8f0fcb.mp4

Main issues unresolved or yet unexplored:

1. Grouped gizmos doesn't work well together: non-active one disappears.
Perhaps, the guides and the handle have to be combined into single gizmo with more complicated structure and several shaders.

2. Mouse tracking doesn't go quite well. 
Logic is copied from builtin arrow_3d gizmo, perhaps missed something.
It needs to get reimplemented from scratch.

3. Nice 2d viewport-aligned dot for the handle doesn't work with default highlighting/selection.
I put ugly 3d dot made up of 3 orthogonal circles.
Perhaps there should be full-3d sphere.

4. Custom selection/highlighting scheme doesn't seems to work (which prevents resolution of 1)
Need to debug blender code.

5. Font rendering using blf is totally screwed up with some transform matrices behind the scenes.
A solution could be to pre-render text into image texture.

6. Nice tool-like popup with input fields
Need to bind gizmo to an operator (which seems natural, but doesn't work straightforward).
Or to invoke floating panel implicitly from GizmoGroup, using some WindowManager API.

**Comment by qwiglydee** [comment]
https://user-images.githubusercontent.com/285128/109529660-88241700-7ae8-11eb-9110-c860c3b7bb02.mp4

**Comment by theoryshaw** [comment]
looking good.  Possible for this gizmo to snap to other objects in the scene?  For example, have it snap to the height of the other existing walls?

**Comment by qwiglydee** [comment]
@theoryshaw 
There is indeed 'snapping' mode available for gizmos. But there's no api to implement it in python, other than scanning whole scene or something crazy like that. 
Some built-in gizmos use internal snapping utilities available only in C.

I don't think it's possible without patching Blender. 

Maybe, some workaround could be implemented. 
Like, scanning and caching heights of all nearby object.

**Comment by Moult** [comment]
I'm curious whether or not the tricks used in CAD Transform's snap by @s-leger or https://github.com/Shriinivas/blenderbezierutils by @Shriinivas can help fix snap.

**Comment by s-leger** [comment]
CAD Transform rely on scene raycast for mesh snap.
Gizmos where ment to drive "simple" operators in a modal fashion (tool mode), at this time not found a reliable way to allow multiple gizmos selection, would rather apply the operators to selected objects, using active as the driver for operation.

As conclusion, as eye candy gizmos may look at first glance, the convoluted current implementation and inherent limitations make me feel that my old own plain .gpu based gizmos allow some required freedom and are way easyer to implement.

**Comment by Moult** [comment]
Closing issue as it now works, even though admittedly there are some outstanding issues. I need some time to review and think whether there is a better approach.
