### ISSUE TITLE
ifcopenshell-python ifcopenshell.geom.createshape makes incorrect shape

### ISSUE THREAD

**Issue by RobinVanTol** [IfcOpenShell/IfcOpenShell#1325]
I was having inconsistent values when saving the size of groups of ifc objects, upon further investigation i found that the shape made by the ifcopenshell.geom.createshape using PYTHON_OPEN_CASCADE = true, to show what i mean i added a screenshot of the shape made by ifcopenshell
![image](https://user-images.githubusercontent.com/38659478/108339277-864c8080-71d7-11eb-91c2-c97e208bd787.png)

as well as this image which is how solibri shows the same element
![image](https://user-images.githubusercontent.com/38659478/108339260-7df44580-71d7-11eb-9c38-295758281439.png)

As im new to using ifcopenshell any help would be greatly appreciated.
I will try to make a minimal ifc file containging only this item for it to be locally reproducible, however i dont know how to do this yet so it may take some time.
If needed i could also send the script used to generate the first image to see if i am doing something wrong.

**Comment by aothms** [comment]
Upon seeing those two screenshots I don't have a clue where to start. 

> however i dont know how to do this yet so it may take some time.

@Moult has an https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcpatch/recipes/ExtractElements.py script for that.

**Comment by Moult** [comment]
@RobinVanTol ah yeah sorry for the undocumented usage. IfcPatch is a little wrapper that lets you run predefined "recipes" to modify an IFC file in a predetermined way. I've now added documentation here:

https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcpatch

Let me know if it isn't clear enough. I do need to document each recipe in more detail in the future.

**Comment by RobinVanTol** [comment]
@Moult That helps a ton, thanks a lot. I made a file that only contains ifc door elements and this is already much smaller however it's still a 50 mb ifc file, i would like to reduce it further if possible, could you specify how i would get a single ifc object by guid, further explanation on what the arguments can be in the readme would also be nice.

**Comment by Moult** [comment]
@RobinVanTol the readme links to https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#IFC_Query_Syntax which describes the query syntax. To query a single GlobalId, just prefix it with a `#`, like `#2MLFd4X2f0jRq28Dvww1Vm`.

Other recipes have different arguments, so indeed I need to spend some time and document them all.

Good catch about the log. Would you be interested in helping to write documentation for ifcpatch?

**Comment by RobinVanTol** [comment]
@Moult ah, i missed that link, my bad, with that it wasn't difficult. 

@aothms  I've made a small ifc file containing the element that is displayed incorrectly, in the zip i also added a small script that shows how i visualize the element just in case there is a mistake there

[demo.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6027800/demo.zip)

**Comment by RobinVanTol** [comment]
Is this sufficient for you to start looking into it? Is there something i can do to help/make it easier?

**Comment by aothms** [comment]
What versions are you using?

On my end it looks similar to the Solibri screenshot you shared

![afbeelding](https://user-images.githubusercontent.com/1096535/110329146-8690ac80-801c-11eb-983b-50a338efc031.png)


Use the latest v0.6.0 version wherever possible

**Comment by RobinVanTol** [comment]
I'm using python 3.8.8, pythonOCC-core 7.4.1 and i reinstalled ifcopenshell v0.6.0 using conda. Im still having the same issue.

**Comment by aothms** [comment]
Conda channel is not frequently updated, just download the zip from the website then http://ifcopenshell.org/python

**Comment by Moult** [comment]
Using latest IfcOpenBot build, as well as in the BlenderBIM Add-on, I get the same screenshot as @aothms . Here's another screenshot inside Blender:

![2021-03-09-200004_518x823_scrot](https://user-images.githubusercontent.com/88302/110445385-25e39b80-8112-11eb-8ce0-12eabbd7ae0d.png)

**Comment by RobinVanTol** [comment]
Thank you, using the version from http://ifcopenshell.org/python displays it correctly

**Comment by aothms** [comment]
You can also try ifcopenshell form this channel btw perhaps https://anaconda.org/tpaviot/ifcopenshell
