### ISSUE TITLE
Python 2 doenst have the ModuleNotFoundError, which cause the program to crash with a NameError, using ImportError works

### ISSUE THREAD

**Issue by RobinVanTol** [IfcOpenShell/IfcOpenShell#1326]
https://github.com/IfcOpenShell/IfcOpenShell/blob/a0f79cc0db2404a77d1ff794cdd3b87fe822aa3c/src/ifcopenshell-python/ifcopenshell/geom/occ_utils.py#L32

**Comment by aothms** [comment]
Nice find. Can you submit a Pull Request for this? Thanks.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 18 feb. 2021 13:52 schreef RobinVanTol <notifications@github.com>:

**Comment by RobinVanTol** [comment]
i dont have permission to push a new branch to make a pr with

**Comment by aothms** [comment]
The procedure is that you create your own fork on github and push to that.
Creating a PR is a matter of a single click on github then. Thanks

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 18 feb. 2021 16:38 schreef RobinVanTol <notifications@github.com>:
