### ISSUE TITLE
BlenderBIM: The IFC structure in past BlenderBIM files is not recognized upon opening in Blender.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1336]
The IFC structure in past BlenderBIM files is not recognized upon opening in Blender.

random file example: https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/93d2fb7c652fd03e2adc07284bb338171d40c7a9/Random%20Tests/Wall_Zigzag/from_Blender/Wall_Zigzag_01.blend

2.91 - 210221-win

![image](https://user-images.githubusercontent.com/507113/108629600-5810b000-7426-11eb-9779-51421d390271.png)

**Comment by Moult** [comment]
Did you export an IFC? You need to have an IFC exported, otherwise, it is just a Blender file.

**Comment by theoryshaw** [comment]
![giphy](https://user-images.githubusercontent.com/507113/108858774-29274500-75b2-11eb-9ec3-b65f3032aa99.gif)
