### ISSUE TITLE
BlenderBIM: improving connection between attributes in 'Object Properties' and the 'Outliner'

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1337]
When changing the name in (2) it automatically changes it for (1), but does not do the inverse. That is, changing (1) doesn't automatically change (2).

![image](https://user-images.githubusercontent.com/507113/108637791-cae35080-7451-11eb-8a23-dbd25813426f.png)

**Comment by theoryshaw** [comment]
doesn't seem like this is fixed
https://www.dropbox.com/s/f3kq6ha39exta6t/2021-03-14_09-09-47.mp4?dl=0

**Comment by Moult** [comment]
Interesting. Ping @ecke101 subscribing to the Blender message bus seems to trigger on name changes via F2 rename as well as changing the name in the object properties... but _not_ in the outliner. Maybe this is out of scope of the message bus? Thoughts of any way to subscribe to this event?

**Comment by ecke101** [comment]
That doesn't seem right. I made a bug report: https://developer.blender.org/T86613

**Comment by ecke101** [comment]
The patch mentioned in the link above is commited now so I guess this can be closed.

**Comment by Moult** [comment]
Thanks so much @ecke101 and @theoryshaw !
