### ISSUE TITLE
Documentation on how to use IfcClash

### ISSUE THREAD

**Issue by harrycollin** [IfcOpenShell/IfcOpenShell#1338]
Hello everyone,

I was interested in using IfcClash, but being new to relatively Python I'm not sure how to do that. How does it relate to IfcOpenShell in this repository? Does it get compiled with it or is it a separate tool? 

Any help on this would be really appreciated :)

**Comment by Moult** [comment]
ifcclash uses IfcOpenShell, as well as another library called fcl. At the moment, the easiest way to use it is through the BlenderBIM Add-on UI. This might help: https://www.youtube.com/watch?v=99i4leHzUC4

If you're interested in running it via Python, or via CLI, indeed, we need to write some documentation for it! Ping @fbpyr ... keen? :)

**Comment by fbpyr** [comment]
@Moult sure, 🙂 
@harrycollin here is how it could be done in scripts within blenderBIM (which I also used for an BB addon) : 
https://wiki.osarch.org/index.php?title=BlenderBIM_Add-on_code_examples#Clash_Detection

@Moult  let me know, if it should move somewhere else or need to be linked differently.

**Comment by harrycollin** [comment]
@Moult @fbpyr Thank you! I will check this out.

**Comment by harrycollin** [comment]
If we could write some documentation on how to use it outside of Blender it would be great! As @Moult mentioned - even running it via CLI / Python. I can see in the example that Blender's APIs (bby and bmesh) are used throughout - does IfcOpenShell have what it takes to run this without Blender? I understand this was initially written to work with Blender so I apologise if it's unreasonable.

**Comment by Moult** [comment]
@harrycollin ah those examples that @fbpyr linked to are a little misleading - they are examples specifically on how to use IfcClash with Blender objects. However, if you are using IfcClash just with IFC, then no need to use any Blender. IfcClash by itself has no dependency on Blender.

@fbpyr I recently wrote some docs on IfcPatch that look like https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcpatch - would you be interested in writing the same as a README.md for IfcClash?

**Comment by harrycollin** [comment]
@Moult is there any news on this? :)

**Comment by Moult** [comment]
@harrycollin sorry, no - let me ping @fbpyr to see if he's interested. Otherwise, I'll make some time and write some initial docs.

**Comment by harrycollin** [comment]
@Moult Thank you! :)

**Comment by messiosmarios** [comment]
Hey @Moult & @fbpyr great work with this and a brilliant suggestion @harrycollin. I'm looking forward to seeing an example/ documentation of the IfcClash simply with IFC with no attachments to Blender 🚀

**Comment by harrycollin** [comment]
So I figured out how to run IfcClash from the CLI. I didn't previously see the block of code right at the bottom of the file which allowed it to be easily run from a CLI. I did have some trouble getting everything set up though. I'm on Windows 10 and python-fcl (one of the packages used) wasn't playing well and refused to install. I ended up having to use WSL with Ubuntu to install and run the clashing. For those getting started make sure you follow the additional installation instructions for python-fcl [here](https://github.com/BerkeleyAutomation/python-fcl#installation).

**Comment by Moult** [comment]
@harrycollin glad you cracked it! In fact, would you like to write some docs about it?

By the way, the BlenderBIM Add-on actually packages all the deps already for you for Python 3.7 (and potentially above - haven't checked), so you can just copy it from the BlenderBIM Add-on download in the `lib/site/packages` folder.

**Comment by harrycollin** [comment]
@Moult I'd be happy to write some initial docs, although it's not straightforward for Windows users. As for the site-packages I didn't think about that. I will give it try on Windows with the existing packages. 

I'd still need someone else to make documentation on the clashsets if it's not already written. I managed to get some results but the viewpoints were completely off, not even getting close to the building in some cases. I'm not sure if this due to misuse or something else.

**Comment by EdgarWesterhoven** [comment]
I would be very interested to know how to use this as well. On the mainpage for ifcopenshell this IFCclash does not have an aterisk (so not part of the default package, correct). Whilst in this section it seems to be part of the blenderbim-addon, correct? 

Anyway I am facing the issue that when I setup a clash test that I get an error: OSError: Unable to open file for reading, location: <unkonwn location>:-1

**Comment by Moult** [comment]
@EdgarWesterhoven IfcClash is indeed a separate package, but it is bundled with the BlenderBIM Add-on as we provide a graphical interface to it.

Your error sounds as though it is failing at the very beginning of trying to load your IFC file. Can you check that you are indeed loading an IFC file? Another random guess, if you're on Linux or Mac and you've downloaded IFC files from BIM360, keep in mind the file permissions are a bit messed up and quite a few people have reported this issue to me. Doing chmod 644 on the files will fix it.

**Comment by EdgarWesterhoven** [comment]
I have not been on MAC / Linux for a while .... On the PC I can get most of the stuff to work, however some things remain a bit more challenging.

IfcClash is working for the setup and the initial test, trying to load the results back in presents me wiht the following 
![image](https://user-images.githubusercontent.com/40623427/146201581-2d8e53c1-3412-4b41-9008-5c8178cd867d.png)

**Comment by pichosan** [comment]
Hello, I'm trying to use IFC CLASH within Blender, and I am able to create BCF files containing the clashes created with the IFC CLASH tool, but I'm having a hard time exporting the clash sets with a JSON format, it only allows to export in BCF format. How can I visualize the items in the BCF file inside Blender?
