### ISSUE TITLE
IfcOpenBot build for Python 3.9

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1340]
In the upcoming Blender version 2.93, Blender will start using Python 3.9. Is it possible to bump the build bot for this?

**Comment by aothms** [comment]
Am I missing something?

![afbeelding](https://user-images.githubusercontent.com/1096535/109001697-85b75c80-76a5-11eb-9a40-772281688e0d.png)

It;s there for quite a while I thought.

The bot is having some difficulties with Windows though :(

https://github.com/IfcOpenBot/IfcOpenShell/commit/25d86a50c5632712578a99d035be8d1e3201ea6e

**Comment by Moult** [comment]
Ah, I'm blind :)

Thanks so much!
