### ISSUE TITLE
Geometry iterator takes 20 minutes to process 80MB file

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1341]
Sorry I can't be more informative than this, but I have emailed you the file @aothms - I notice it stays at 1 core for a significant time before spinning up to using the rest of the CPUs as well, this is not what I have experienced in other files. Loading the file takes 5.4s, which makes sense, but the iterator takes a very long time.

Tested with XBim Xplorer and loads in a couple of minutes.

```
Start
Loaded in  5.417848110198975
Finished in  1232.4066445827484
```

Minimum code:

```
import time
import ifcopenshell
import ifcopenshell.geom


start = time.time()
print("Start")
f = ifcopenshell.open("/home/dion/drive/bim/ifcs/test.ifc")

print("Loaded in ", time.time() - start)
start = time.time()

settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, f)
iterator.initialize()
while True:
    shape = iterator.get()
    if not iterator.next():
        break

print("Finished in ", time.time() - start)
start = time.time()
```

**Comment by Moult** [comment]
Bump?

**Comment by hamdi-99** [comment]
have you find a solution ? i am facing the same issue @Moult

**Comment by Moult** [comment]
@hamdi-99 note this is a very specific question about why it is stuck at one core. Are you also experiencing that symptom?

**Comment by Moult** [comment]
Also, this may in theory be solved in v0.7.0 due to the inverse optimisation in #1674. Unfortunately I haven't yet been able to test v0.7.0. So feel free to ignore this bug and focus on v0.7.0 first, then hopefully I'll be able to test it without it segfaulting/erroring out on v0.7.0 and confirm if the error persists.

**Comment by aothms** [comment]
The way I usually go about these issues is running IfcConvert with -vv (double v) on the file. It will provide extra verbose logging and notify when an element begins processing. With https://github.com/IfcOpenShell/IfcOpenShell/commit/99cd952c9811c749ca11cbeacd0d60aef425c756 there is also timestamps now. That way at least we can figure out if there is a single element taking prohibitively long. (note that -vv takes extra long as it will also validate every brep).

@Moult I also ironed out a couple of 0.7 segfaults in the meantime, but didn't yet look at the issue with inverses.

**Comment by Moult** [comment]
Cheers! I'm going to close this bug since this is basically a duplicate of #1674.
