### ISSUE TITLE
Referenced before assignment

### ISSUE THREAD

**Issue by ecke101** [IfcOpenShell/IfcOpenShell#1344]
It seems there is a case where the obj variable is read without being assigned in blenderbim\bim\module\attribute\operator.py at line 73. Unfortunately I don't really know what I did to trigger that error. I will update if it comes up again.

```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\erab\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\module\attribute\operator.py", line 73, in execute
    oprops = obj.BIMObjectProperties
UnboundLocalError: local variable 'obj' referenced before assignment
```

**Comment by Moult** [comment]
Note to self: this is due to an incomplete implementation at `module/material/ui.py:L170`. I guess I forgot to build the function.
