### ISSUE TITLE
IFC Object Material list disappears

### ISSUE THREAD

**Issue by ecke101** [IfcOpenShell/IfcOpenShell#1345]
When I try to change IFC Object Material in Object properties from IfcMaterial to any other option, the whole listbox disappears.

![bild](https://user-images.githubusercontent.com/249736/109219690-357cef00-77b8-11eb-9038-810018f9caf5.png)

![bild](https://user-images.githubusercontent.com/249736/109219765-547b8100-77b8-11eb-96db-043c9257403f.png)

```
location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "C:\Users\erik\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\module\material\ui.py", line 54, in draw
    self.material_set_data = Data.constituent_sets[self.product_data["id"]]
KeyError: 477988
```

**Comment by Moult** [comment]
Note to self: this is probably due to a constituent set being removed and the old IFC data cache isn't refreshed. I need to come up with a better cache refreshing strategy.

**Comment by Moult** [comment]
I was wrong, this is actually due to borked constituent set assignment. Fixed in https://github.com/IfcOpenShell/IfcOpenShell/commit/e89d540236235f24b0098b62b3afafb2f988002e
