### ISSUE TITLE
IfcGridPlacement not supported

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1346]
I didn't see an issue about this already, although it was mentioned in #1133, and because it came up in [this Twitter thread](https://twitter.com/IsConsense/status/1364961114862321664) I decided to create a dedicated bugreport to track this :)

**Comment by Moult** [comment]
Any pointers on where in the C++ to start poking around to implement this? :)

**Comment by aothms** [comment]
IIRC, currently we just have the abstract type mapped https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/mapping.i#L164

So we need to account for different types in the function body https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcGeomHelpers.cpp#L432

We can also create more granular mappings for the different types of placement.
