### ISSUE TITLE
ifcpatch ExtractElements recipe misses the material

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#1347]
see forum topic: 

https://community.osarch.org/discussion/464/ifcpatch-extractelements-recipe-misses-the-material

**Comment by aothms** [comment]
Note that it's material (HasAssociations, I think) but also the styling on the representation items. For the latter you can do a file.traverse() and then filter on is_a(IfcRepresentationItem) and on those follow the StyledByItem attribute.

**Comment by Moult** [comment]
Closing, as this was fixed a while back when IfcPatch ExtractElements was upgraded to use the project.append_asset API.
