### ISSUE TITLE
Graphical issue with IfcExtrudedAreaSolidTapered and IfcArbitraryProfileDefWithVoids

### ISSUE THREAD

**Issue by Krande** [IfcOpenShell/IfcOpenShell#1348]
Hi,

in the attached example I have tried to make a Cylindrical profile with a tapered cross section
[cone_ex.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6048511/cone_ex.zip)

However I am unable to render the hole inside the cylinder in Blender 2.92 (using BlenderBIM v0.0.210221 on windows).

![image](https://user-images.githubusercontent.com/9642232/109278948-70fbd580-7819-11eb-8cfd-61bd22a0e17d.png)

No errors are printed to the system console when I click "validate IFC file". The hole is represented somehow, but in Blender it is not represented when translucency is off.

![image](https://user-images.githubusercontent.com/9642232/109278898-5d506f00-7819-11eb-8981-a9f338f9dcbb.png)

FYI the same is present when I try this in XBim

![image](https://user-images.githubusercontent.com/9642232/109278874-545f9d80-7819-11eb-817b-f2ca161221eb.png)

Could this be fixed by utilizing some of the "exact" boolean functionalities in Blender perhaps or is this something else?

Best Regards
Kristoffer

**Comment by aothms** [comment]
Could be something else, does it work better if you convert the file using IfcConvert?

**Comment by Krande** [comment]
I converted the ifc to ".glb" using IfcConvert and it seems that the same error occurs

![image](https://user-images.githubusercontent.com/9642232/109287576-0ac88000-7824-11eb-9ce5-9d00fa553472.png)

Am I using the IFC classes wrong somehow?

**Comment by Moult** [comment]
Checked with the IFC Debug tool and I was unable to create_shape on the individual profiles (as well as the outer loop and inner loop) that make up the extruded area solid. I didn't investigate further though.

**Comment by aothms** [comment]
It's just that this class isn't implemented very well in ifcopenshell, but I've added condition that fixes processing in your case. It would have worked with CircleHollowProfileDef because those were already in the condition.

**Comment by Krande** [comment]
Since a workaround is in place I think it is OK to close this issue.
