### ISSUE TITLE
IfcDocumentSelect cannot be instantiated

### ISSUE THREAD

**Issue by TristanLecallier** [IfcOpenShell/IfcOpenShell#1353]
Hi,
I'm trying to link an object with an external document.
So I created the entities : IfcDocumentReference and IfcDocumentInformation. But when I want to create the entity IfcDocumentSelect I have the following error : 

![image](https://user-images.githubusercontent.com/46968115/109780113-f9f28280-7c06-11eb-8584-01301559e4ea.png)

Here is my code : 

```
import ifcopenshell
import uuid

file = ifcopenshell.open(r'D:\3D Objects\Piece A.ifc')
create_guid = lambda: ifcopenshell.guid.compress(uuid.uuid1().hex)
owner_history = file.by_type("IfcOwnerHistory")[0]
doc_path= r"D:\Photos\a_photo.png"

ifc_document_information = file.createIfcDocumentInformation(create_guid(), 'Test Document', 'Test description', doc_path, None, None, None, None, None, None, None, None, None, None, None, None, None )
ifc_document_reference = file.createIfcDocumentReference(doc_path, ifc_document_information.Identification, None, 'Description', ifc_document_information)
ifc_document_select = file.createIfcDocumentSelect(ifc_document_reference, ifc_document_information)
```

I can't figure out what's wrong in my code.
Does anyone have an idea ?
Thanks !

Tristan

**Comment by aothms** [comment]
IfcDocumentSelect is a SELECT / tagged union / sum datatype (how ever you want to call it). So it's **either** a IfcDocumentInformation **or** a IfcDocumentReference, it's not both (it's not a tuple / product datatype).

Whenever a IfcDocumentSelect expected you supply a IfcDocumentInformation or IfcDocumentReference

**Comment by TristanLecallier** [comment]
Aaaah ok ! Thanks for the quick answer, I misunderstood the documentation...
