### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ecke101** [IfcOpenShell/IfcOpenShell#1355]
I've been playing around a bit with loading Ifc-files and it seems like OCCT is pretty slow. Is there something that can be done to improve performance? It seems like IfcOpenShell is around 10-40x slower compared with IfcPlusPlus for example. Maybe there's a reason for this I have missed?

**Comment by aothms** [comment]
The reason is indeed OCCT, in particular for detailed explicit meshes in IFC there is a lot of overhead in piping it through OCCT's data model. In 0.7 (probably pushed back to 0.8) we will have some additional geometry libraries side by side.

**Comment by Moult** [comment]
I would _love_ to see faceted breps and polygonal face sets that don't have voids to just bypass OCC :) I reckon that would be a huge speedup, and incredibly relevant to Blender users in particular!

**Comment by Moult** [comment]
Closing as duplicate of #841.
