### ISSUE TITLE
Wheels for Python 3?

### ISSUE THREAD

**Issue by mristin** [IfcOpenShell/IfcOpenShell#1356]
Hi,
Please apologize if this is a duplicate issue. I could not find ifc open shell on pypi.org. Is there a wheels package available so that it can be readily installed, say, with `pip3 install ifc-open-shell`?

If not, would you like me to make a pull request and help you create the wheel packages?

**Comment by aothms** [comment]
There isn't currently anything available on pypi, but that would surely be great.

There is work on (ana)conda packages using azure: https://github.com/IfcOpenShell/IfcOpenShell/issues/1327

Github actions using CTest https://github.com/IfcOpenShell/IfcOpenShell/pull/1307

The current build infrastructure (ssh and ansible) is here https://github.com/IfcOpenShell/IfcOpenBot

What do you have in mind? (I prefer ifcopenshell as the name as that's the toplevel package users import)

**Comment by mristin** [comment]
Thanks for such a quck and detailed reply!

> What do you have in mind?

It would be great to continuously release binary packages for major platforms so that users can just type:

```
pip3 install ifcopenshell
```

For example, using GitHub workflow and adding the binaries to the package automatically on the release.

**Comment by mristin** [comment]
It is probably as simple as: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by aothms** [comment]
Note sure. Keep in mind IfcOpenShell is mostly written in C++ and has huge dependencies (e.g Open CASCADE). These need to be compiles and interfaced with SWIG to be used in Python. Have a look at the three approaches I referenced above.

**Comment by mristin** [comment]
Thanks, I will!

Some links for my future reference:
https://thomastrapp.com/blog/building-a-pypi-package-for-a-modern-cpp-project/#swig-and-__init__py
https://pypi.org/project/cibuildwheel/

**Comment by Moult** [comment]
Closing as resolved :) See #2132 #2293
