### ISSUE TITLE
Installation on Windows Fails: No module named 'OCC.Core'

### ISSUE THREAD

**Issue by wassimj** [IfcOpenShell/IfcOpenShell#1358]
I am testing on Blender 2.92 (Windows 10), I follow the instructions to download BlenderBIM-AddOn zip file and then preferences Add-ons to install it. When I click on activate, I get an error
ModuleNotFoundError: No module named 'OCC.Core'

**Comment by Moult** [comment]
This sounds strange. Did you perhaps download a build that is for Python 3.9? Can you try again by clicking the official download link on the blenderbim.org website and not download something from the builds folder?

**Comment by Moult** [comment]
Closing as commit should resolve this. Users have to explicitly run the operator to trigger import.
