### ISSUE TITLE
IfcConvert 0.4 to 0.5, what is the equivalent of --force-ccv-face-orientation

### ISSUE THREAD

**Issue by klokoy** [IfcOpenShell/IfcOpenShell#136]
In IfcConvert 0.4 we used --force-ccv-face-orientatin, but this is not awailable in 0.5. Is there an equivalent options we can use?

This image shows the errors we see.  
With IfcConvert 0.5: `IfcConvert --sew-shells model.ifc model.dae`

![screen shot 2016-09-21 at 10 55 32](https://cloud.githubusercontent.com/assets/973082/18704393/08934234-7fea-11e6-9512-b5c437c1810b.png)

With IfcConvert 0.4: `IfcConvert --sew-shells --force-ccw-face-orientation model.ifc model.dae`

![screen shot 2016-09-21 at 11 02 26](https://cloud.githubusercontent.com/assets/973082/18704651/14c1548c-7feb-11e6-89b2-9d0a474da0f2.png)

**Comment by aothms** [comment]
An equivalent of this option became the default in 0.5.0. I see however there are some issues with the faces with holes. Both in the sink, as in the little box behind it. A recent master build of IfcOpenShell would perform a bit better, but I am leaving the issue open to fix these issues.

For future reference: the model is `Duplex_MEP_20110907_optimized.ifc` and the sink in question is `2h405XijT83A$BX7w5ki4y` (or `product-ab100161-b2d7-480c-afcb-847e85bac13c-body` when converted).

![Duplex MEP](https://cloud.githubusercontent.com/assets/1096535/18711665/4669c18e-800b-11e6-8249-74b64cb38952.png)

**Comment by Stinkfist0** [comment]
FWIW, I'm encountering this problem with pretty much every IFC file created with MagiCAD so far.

**Comment by aothms** [comment]
Ok, I had another go add making this a bit more robust: #147 I would be grateful if you can check on your own personal files.

Note that the result is not necessarily as expected:

![cw-ccw](https://cloud.githubusercontent.com/assets/1096535/19516263/7dcfdcfc-95fb-11e6-996d-f8d3f857e74a.png)

But my impression is that it does follow CCW ordering

![cw](https://cloud.githubusercontent.com/assets/1096535/19516264/7dd57b94-95fb-11e6-9892-bb211ec8eb3d.png)

`#172418=IFCPOLYLOOP((#15517,#16572,#10064,#14597));`

![ccw](https://cloud.githubusercontent.com/assets/1096535/19516261/7dcc404c-95fb-11e6-8ee1-701e137046b3.png)

`#184702=IFCPOLYLOOP((#15517,#16817,#15276,#10445,#24481,#29236,#16928,#14597));`

With `--sew-shells` the orientation is as expected. Even for the two knobs now, which are together actually one shell which is not allowed.

![sew](https://cloud.githubusercontent.com/assets/1096535/19516260/7dcbef5c-95fb-11e6-8864-3c0c3b85489c.png)

![nosew](https://cloud.githubusercontent.com/assets/1096535/19516262/7dce15e8-95fb-11e6-9d37-5ba6ee916ad9.png)

**Comment by Stinkfist0** [comment]
Great, I'll give it a test spin right away.

**Comment by Stinkfist0** [comment]
The new code seems to work great for my models at least (old conversion on the left, new on the right):
![image](https://cloud.githubusercontent.com/assets/227876/19517870/6dcb3aac-960c-11e6-8c3b-965eacbdbac8.png)
