### ISSUE TITLE
BlenderBIM scene and IFC requires manual operations to stay in sync

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#1360]
Hi,
In Blender wehn I duplicate a wall, the new one get the same GlobalId and the same Name as the original one. It should get a new GlobalId and the Blender name of the Object.

A second problem is after moving an element, we have to click:
  Object Properties --> Transform --> Edit Object Placement
If you don't the element stay at his first position.
A greater problem is after deleting the element. It stays somewhere in memory and it's not possible to delete it in the ifc file.

It would be great if  by clicking to get the hierarchy of a new project we get a collection to store the IfcTypeProduct.

Thank you for your commitment. BlenderBIM is just incredible!

**Comment by Moult** [comment]
You can use Shift-E as a shortcut to easily update the placement, or edit a mesh.

Instead of deleting the element, you need to click the "X" button in the Object Properties -> IFC Class panel. Then it'll be deleted from the IFC file.

In the hierarchy of a new project, there is already a collection called "Types" which stores type products.

Hope that helps :)

**Comment by vuicBABS** [comment]
thank your for the response. But it still not ok.

We are interested to use the blenderbim addon to build model from scratch (without archipack or other addon).
If we build a new mesh (shift-A) and put in the right IfcSpatialContainer it's ok. The problem comes when we want to move the element. If we don't update the mesh representation (Shift-E) the new position is not updated. It's ok if you just want to move one or two elements but if you want to build a model from scratch and use it during the elaboration of the all project the risk is to high to forget to update the mesh after all the modification.
A second problem comes when we want to duplicate the elements. It would be really fast to make a model whith the duplicate tool (Shift-D) and even faster with Shift-E. But after duplicating an element and changing the name and the GlobalId the addon change the name and the globalId of the first element. And I have 2 elements with same name and same GlobalId. And in the Ifc file I have only one element.

For deleting wit "X" it's ok. But there is a risk to delete element with "DELETE" and not to delete really an element.

When I create a new Project the collection "Type" doesn't appear in the hierarchy. It's only a small details but would be nice to have it.

Cordialy

**Comment by vuicBABS** [comment]
Hi Moult,
I saw my mistake. I created the elements outside the model. After importing, I have to change for each element the IFC Spatial Container (even if I put the element under the Ground Floor collection). It would be great if the field is automaticaly updated.
It's the same with the Attributes and the properties. It would be great to be able to change the an attribute or a property to more element at the same time.
thank you for your attention and for the great job! We appreciate.

**Comment by Moult** [comment]
The current process is incredibly manual and therefore annoying for users. First, a little history - the BlenderBIM Add-on started off as a "build in Blender" then import / export translation. This meant you could build a Blender scene just like you would in native Blender, and the translator would handle the rest. This led to very nice workflows people doing projects just in Blender. However, the translation model led to huge data loss, and most projects involve software that isn't Blender, and there were lots of usecases where you were not authoring from scratch, but only modifying portions of the model. As translations were not scalable, the entire software was rebuilt from the ground-up with a totally new paradigm: native IFC authoring. However, this disconnected Blender from the IFC editing, and that is why if you want changes in Blender to reflect in IFC, you currently need to do a manual operation - e.g. press a button, or press a hot-key, and keep track of the changes yourself. In short, this new paradigm is better is almost every single way ... except for the complexity of syncing the Blender scene.

These manual operations to sync the scene, however, are only temporary UX issues. There are technical solutions to these problems, which I plan to implement, but haven't yet! We'll keep this bugreport open as I address these, so a huge thank you to reporting this bug!

For the record, here are the manual things you need to watch out for:

 - Moving an object. Use Shift-E -> Edit object placement. (Also available in Object Properties under Transform)
 - Editing an object's geometry as a mesh. Edit the Blender object normally, then use Shift-E -> Update mesh representation. Warning: this will also convert non-mesh geometry into meshes. Sometimes, this is what you want. Sometimes, it is not. For convenience, updating the mesh representation will also edit the object placement.
 - Editing an object's geometry as a mesh which has openings. Same as before, but before you edit the mesh, you need to go into Mesh Properties and click on Dynamic Voids. By default, voids (openings) are baked. This converts it into a dynamic Blender boolean for you to edit the un-voided mesh.
 - Editing an object's geometry as a parametric thing. In this case, the UI totally sucks, but you can go into the Mesh Properties, then press "Get Representation IFC Parameters". Then, type in the new parametric inputs, then press the refresh button next to the input you changed. This is really horrific.
 - Putting an object into another container in the spatial tree. Use Shift-E -> Update Spatial Container
 - Creating new parametric geometry from a mesh. For now, the UI also totally sucks, but you can just model a simple _single_ mesh extrusion, then in the Mesh Properties, click Update Mesh as X Extrusion, where X is Rectangle, Circle, or Arbitrary.
 - Deleting an object. Press the "X" in the Object Properties, IFC Class panel. Then it's an extra step to delete the Blender object.
 - Copying an object. Copy it as normal in Blender, then press the "Copy" button in the Object Properties, IFC Class panel.
 - Pressing undo. Pressing undo in Blender doesn't change IFC at all.

As I address these, I will update this bugreport.

**Comment by ChubbyQuark** [comment]
Hi Moult, 
The GlobalId duplication also occurs if a face/faces are separated from a mesh. Current work around I've found is to generate a new id and also follow the steps you outlined above.

**Comment by Moult** [comment]
@ChubbyQuark separating faces from a mesh is akin to copying an object. Just separate, and then press the "copy" button.

**Comment by ChubbyQuark** [comment]
OK, makes sense. Thank you.

**Comment by theoryshaw** [comment]
Yes, @vuicBABS thanks for posting this issue.  I learned a little as well.

**Comment by Moult** [comment]
Todo:


 - [ ] Create an "authoring" mode. When enabled, BlenderBIM will assume you are authoring and will help you keep things in sync. If disabled, BlenderBIM will assume you're doing something else and will rely on you to keep sync. All other TODO items will only happen when authoring mode is enabled.
 - [ ] Save the IFC when you save the Blender file automatically
 - [ ] Write all changed object placements upon IFC export, so you no longer need to manually update placements
 - [ ] Use edit mode tracking to log whether you've edited geometry
 - [ ] Automatically edit geometry at export time of all objects in the edit mode tracking log, then clear the log
 - [ ] Auto delete objects in Blender when you unassign their IFC class
 - [ ] Editing simple parametric extrusions and should retain their parametric behaviour, this should remove the need for gizmo UIs for most editing, and make it so you don't need to use the horrible slider UI either

**Comment by vuicBABS** [comment]
Thank you for the post.
It could be good to have a tool like the "format painter". So you choose an reference element and copy his attribues, properties and material to a second one.
So it's easy to organise a model with reference elements and copy them or use the format painter to updates quickly the parameters.
Thank you very much for this addon. It's very nice.

**Comment by Moult** [comment]
@vuicBABS there was historically a "copy to" feature to copy particular attributes or properties to another object. This is one of the features that I didn't get around to re-implementing after the rewrite. Feel free to create another bugreport with that request so that we can track progress of me implementing it :)

**Comment by theoryshaw** [comment]
Hi, i noticed when an object is copied, you still have to manually copy the class/guid.  Is this currently in the roadmap to remove this additional step?

![image](https://user-images.githubusercontent.com/507113/119386095-ae42f880-bc8c-11eb-9505-66018c868c33.png)

**Comment by Moult** [comment]
I don't know how :( I have the same wish as you.

**Comment by theoryshaw** [comment]
haha... we can dream.

**Comment by Moult** [comment]
@theoryshaw thanks to help from @s-leger there is now a solution :D
