### ISSUE TITLE
Thoughts on making a standalone BCF python package?

### ISSUE THREAD

**Issue by Krande** [IfcOpenShell/IfcOpenShell#1365]
Hi,

I am looking for a format to store views and comments and access in multiple contexts using vanilla python. In that respect I see BCF being a suitable candidate (or if anyone else has a better suggestion I would love to hear them :) !?).

Anyways, in order to make more use the BCF package currently located in `src/bcf` if thought I would propose I create a github actions auto-pipeline in a same way as I did for blenderbim, but instead of creating a release it would publish a package to pypi/conda. 

If this sounds like something you would be interested in let me know and we can discuss package name and distribution (pip v conda). I noticed that there already exists a bcf package on pip (https://pypi.org/project/bcf/) so a rename would be needed I guess? Or maybe we could use our own channel on conda?

Let me know what you think?

**Comment by aothms** [comment]
I created https://github.com/IfcOpenShell/bcf my current approach is then later to add it as a submodule to the ifcopenshell-python source, same for mvd and the pure python spf parser (in progress)

**Comment by aothms** [comment]
> does it make sense to bundle it with ifcopenshell-python?

I leave it up to you. I think submodule inside ifcopenshell-python + optional/recommended deps in conda/pip should work for xmlschema/requests would work.

**Comment by Moult** [comment]
Sounds good - happy to do so. I've leave you to migrate the code and add the submodule as you have the structure in mind :) Let me know if I can help in any way.

**Comment by Krande** [comment]
@aothms Maybe I misunderstood :) Would you like me to port over the `src/bcf` code folder to the new bcf repo? (which I would be happy to help with:) )

@Moult Maybe a bit off topic, but I was thinking it would be really neat to have a standalone python package for 2D drawings as well. Would it be worthwhile to make an agnostic wrapper for the drawing system for BlenderBIM? I mean something like turning the current [svgwriter.py](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/svgwriter.py) into a standalone package and create a BlenderBIM layer on top of that package? What do you think? It could potentially help speed up the development of the drawing system by allowing you to run\test the underlying package in a vanilla python environment?

**Comment by aothms** [comment]
> @aothms Maybe I misunderstood :) Would you like me to port over the src/bcf code folder to the new bcf repo? (which I would be happy to help with:) )

Haha maybe I misunderstood. I don't have a preference. We can also keep this for the GSoC submission and make it a proper BCF API implementation and all.

**Comment by Moult** [comment]
@Krande about the off-topic thing, actually that is the plan. The plan was to firstly switch to IfcConvert which is already standalone and already has a ton of SVG features, and with a few tweaks can be used as a powerful base. Then, I want to strip out all my annotation formatting and style management code from Blender. This way it can be used for FreeCAD too, or easily run on a server (I've done bulk document generation with it already for an infra project, so clearly there is a usecase for it!). We're still in step 1 - modifying IfcConvert to understand camera positions, cut planes, and drawing boundaries. See #1153.

Maybe we hold off moving the code just until we see if there if there is any GSoC interest not to confuse the student :)

**Comment by Krande** [comment]
That sounds good to me! We keep the BCF repo as is.

I will take a look at what you guys are doing with IfcConvert then and see if I can contribute in some way :)

Since the original question has been answered I will close this then!
