### ISSUE TITLE
Can create_shape work for IfcTopologyRepresentation?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1372]
I tried it and it seems as though it doesn't, but just thought I'd double check. Also, are there any other functions which can be used to create shape for individual edges?

If not, no worries, as topology representations are quite straightforward I reckon.

**Comment by aothms** [comment]
I see no reason why it would not work, but if it's a topological edge INCLUDE_CURVES needs to be set.

**Comment by Moult** [comment]
Ah sorry my bad!
