### ISSUE TITLE
GetMaterials of Wall 

### ISSUE THREAD

**Issue by pierrenavarra** [IfcOpenShell/IfcOpenShell#1373]
Hi.
In python, I'd like to get all materials names and thikness for a wall geting by this GlobalID.
How to do that?
Thx
At the moment, my code is : 
~~~
ifc = ifcopenshell.open('R:/RECHERCHE/PLAY-TOWN/IFC/GABARIT-TO-UNREAL.ifc')
wall = ifc.by_id('2vqlphVF16xfSeMa2EYNAU')
for assoc in wall.HasAssociations: #how to go through associations and get MaterialLayers?

~~~

**Comment by Moult** [comment]
For questions like this which aren't bugs, perhaps a better avenue would be the [IfcOpenShell forums](https://sourceforge.net/p/ifcopenshell/discussion/) or [OSArch Community Forums](https://community.osarch.org).

Your start is correct:

```
for assoc in wall.HasAssociations:
    if assoc.is_a("IfcRelAssociatesMaterial"):
        material_select = assoc.RelatingMaterial
        layers = None
        if material_select.is_a("IfcMaterialLayerSet"):
            layers = material_select.MaterialLayers
        elif material_select.is_a("IfcMaterialLayerSetUsage"):
            layers = material_select.ForLayerSet.MaterialLayers
        if not layers:
            continue
        for layer in layers:
            print(layer, layer.LayerThickness)
```

Keep in mind some objects may not have materials layers.

**Comment by pierrenavarra** [comment]
Hello Moult. 
Thx for answering me.
Ok, I'll put my post in ofcOpenShellForum next time.
Thx for your code.
How tdo you know that assoc get the RelatigMaterial property?
Is ther a documentation here?
Thx

**Comment by Jesusbill** [comment]
> How do you know that assoc get the RelatigMaterial property?

because `assoc.is_a("IfcRelAssociatesMaterial")`?

For documentation look in buildingSmart docs: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/ (link for IFC4). For example click on the fields indicated and then search by type
![image](https://user-images.githubusercontent.com/6861582/111013253-07460480-839f-11eb-927c-2e56995d7792.png)

**Comment by pierrenavarra** [comment]
Ok I underestand now. Thx  Jesusbill
