### ISSUE TITLE
build fails to find gp_Pnt.hxx dep

### ISSUE THREAD

**Issue by pablo-mayrgundter** [IfcOpenShell/IfcOpenShell#1374]
It seems newer builds of BlenderBIM don't support OSX 10.13 anymore (#1369), so trying to build myself, but run into a compile problem finding an include from OpenCascade:

sysinfo
```
pablo@top:~/web-ifc> sw_vers
ProductName:	        Mac OS X
ProductVersion:      10.13.6

pablo@top:~/IfcOpenShell> brew info opencascade
opencascade: stable 7.5.0
3D modeling and numerical simulation software for CAD/CAM/CAE
https://dev.opencascade.org/
/Users/pablo/brew/Cellar/opencascade/7.5.0_1 (9,453 files, 169MB) *
  Built from source on 2021-02-23 at 16:02:05
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/opencascade.rb
License: LGPL-2.1-only
==> Dependencies
Build: cmake ✔, doxygen ✔, rapidjson ✔
Required: freeimage ✔, freetype ✔, tbb ✔, tcl-tk ✔
pablo@top:~/IfcOpenShell> git log -1
commit f57aa77ac2416713ff2936c94626ac642ade5850 (HEAD -> v0.6.0, origin/v0.6.0, origin/HEAD)
...
pablo@top:~/IfcOpenShell/build> cmake ../cmake
-- BINDIR: bin
-- INCLUDEDIR: include
-- LIBDIR: lib
-- Boost  found.
-- Found Boost components:
   system;program_options;regex;thread;date_time
-- Boost include files found in /Users/pablo/brew/include
-- Boost libraries found in
-- Looking for Open CASCADE include files in: /Users/pablo/brew/Cellar/opencascade/7.4.0_1/include/opencascade
-- Looking for Open CASCADE library files in: /Users/pablo/brew/Cellar/opencascade/7.4.0_1/lib
-- Required Open Cascade Library files found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/pablo/IfcOpenShell/build
```
build failure:
```
pablo@top:~/IfcOpenShell/build> make -j 7
[  0%] Building CXX object CMakeFiles/IfcParse.dir/Users/pablo/IfcOpenShell/src/ifcparse/Ifc2x3-schema.cpp.o
[  1%] Building CXX object CMakeFiles/IfcParse.dir/Users/pablo/IfcOpenShell/src/ifcparse/Ifc4-schema.cpp.o
...
[ 18%] Built target IfcParse
[ 19%] Built target IfcParseExamples
[ 20%] Building CXX object CMakeFiles/IfcGeom_ifc4x3_rc2.dir/Users/pablo/IfcOpenShell/src/ifcgeom/IfcGeomCurves.cpp.o
[ 20%] Building CXX object CMakeFiles/IfcGeom_ifc4.dir/Users/pablo/IfcOpenShell/src/ifcgeom/IfcGeomCurves.cpp.o
[ 21%] Building CXX object CMakeFiles/IfcGeom_ifc4x3_rc2.dir/Users/pablo/IfcOpenShell/src/ifcgeom/IfcGeomFaces.cpp.o
[ 22%] Building CXX object CMakeFiles/IfcGeom_ifc4x2.dir/Users/pablo/IfcOpenShell/src/ifcgeom/IfcGeomCurves.cpp.o
[ 22%] Building CXX object CMakeFiles/IfcGeom_ifc2x3.dir/Users/pablo/IfcOpenShell/src/ifcgeom/IfcGeomCurves.cpp.o
[ 23%] Building CXX object CMakeFiles/IfcGeom_ifc4x3_rc1.dir/Users/pablo/IfcOpenShell/src/ifcgeom/IfcGeomCurves.cpp.o
/Users/pablo/IfcOpenShell/src/ifcgeom/IfcGeomFaces.cpp:28:10: fatal error: 'gp_Pnt.hxx' file not found
#include <gp_Pnt.hxx>
         ^~~~~~~~~~~~
...
```

check that the file is actually in the directory found by cmake:
```
pablo@top:~/IfcOpenShell/build> head -20 ~/brew/Cellar/opencascade/7.5.0_1/include/opencascade/gp_Pnt.hxx
// Copyright (c) 1991-1999 Matra Datavision
// Copyright (c) 1999-2014 OPEN CASCADE SAS
//
// This file is part of Open CASCADE Technology software library.
//
// This library is free software; you can redistribute it and/or modify it under
// the terms of the GNU Lesser General Public License version 2.1 as published
// by the Free Software Foundation, with special exception defined in the file
// OCCT_LGPL_EXCEPTION.txt. Consult the file LICENSE_LGPL_21.txt included in OCCT
// distribution for complete text of the license and disclaimer of any warranty.
//
// Alternatively, this file may be used under the terms of Open CASCADE
// commercial license or contractual agreement.

#ifndef _gp_Pnt_HeaderFile
#define _gp_Pnt_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Handle.hxx>
```

**Comment by aothms** [comment]
I don't understand. How with just `cmake ../cmake` (i.e no other configuration) is cmake able to find the header folder in your home directory `~/brew/Cellar/opencascade/7.4.0_1`. 

Can you run with `make VERBOSE=1` to see the paths (`-I`) actually being passed to the compiler?

What if you run with `cmake ../cmake -DOCC_INCLUDE_DIR=/Users/pablo/brew/Cellar/opencascade/7.4.0_1/include/opencascade`, does it make a difference?

If you're available to help fix the automated OSX builds so that they run on your platform, that would also be a massive help. OSX is just a hard platform to accommodate as an open source project. Ultimately, the binaries produced by the script in `./nix/build-all.py` when ran on a newer version of macOS, should also work on older versions. The `-mmacosx-version-min` [0] was supposed to take care of that, but maybe it's no longer working on the version where the build script is currently ran [1].

[0]
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/nix/build-all.py#L458

[1]
~~~
ProductName:    Mac OS X
ProductVersion: 10.15.6
BuildVersion:   19G2021
~~~

**Comment by pablo-mayrgundter** [comment]
Ah, that found it.. and I missed it the first time.  I must have had 7.4 environment variables still hanging around from an early build.. I couldn't reproduce my problem.  But yes,  using your cmake flag is required and that worked.

Waiting to test in Blender to make sure this works.. will close this when I can confirm.

**Comment by plaes** [comment]
> Ah, that found it.. and I missed it the first time. I must have had 7.4 environment variables still hanging around from an early build.. I couldn't reproduce my problem. But yes, using your cmake flag is required and that worked.
> 
> Waiting to test in Blender to make sure this works.. will close this when I can confirm.

Yeah, I recently improved cmake's OpenCascade lookup and this does not work that well with existing cmake cache generated before this patch was merged.

**Comment by pablo-mayrgundter** [comment]
Ok, that make sense.  I did delete the cmake directory to reset.

However, I tried the reinstall method Dion suggested, to copy in my .so into the plugin directory on top of his distribution package, but that didn't work.  So I guess this bug is solved and I will close it, but still having trouble getting a working build for OSX 10.13.6.. I'll open a separate bug for that (#1386)
