### ISSUE TITLE
Is there a strategy for recursive element remove efficiently?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1376]
This question is basically a combination of #1228 and #944. In short, I want to remove an object from an IFC file. That object has a representation which needs to be removed. That's in theory OK, since from the feedback from #1228 I have code which does just that. However, related to #944, this object's representation is a faceted brep which has well over 100,000 vertices. So, uh, I press the button in Blender, and after 10 minutes my computer runs out of memory and swap so I don't know how long it'll take to finish :)

Thoughts? There needs to be a practical way for users to achieve this usecase of "let's delete an object", and more often than not the huge polycount object is the one you want to delete ;) Perhaps if it is known that a remove_deep is being performed, we can tell remove() to bypass a bunch of checks and "just do it"?

**Comment by aothms** [comment]
Can you prepare an file and script and then we run in the profiler to see what is taking the time. I'm pretty sure we can create some sort of low level batch delete functionality that does not update all the mappings in between each call to remove() and also folds more of the functionality in a single call in C++ (similar to what we did for https://github.com/IfcOpenShell/IfcOpenShell/blob/e1b68dafa469e1f7549f4df500266075db2030a0/src/ifcopenshell-python/ifcopenshell/entity_instance.py#L275)

**Comment by Moult** [comment]
I have dumped a bunch of monkeys into two samples files.

On my machine:

 - [monkey25.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6134223/monkey25.ifc.txt) (25 monkeys): 8-9 seconds - STEP ID 12580
 - [monkey50.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6134229/monkey50.ifc.txt) (50 monkeys): 33 seconds (so not linear, I guess) - STEP ID 25080

I forgot to measure memory usage, but it's quite significant too.

Also a bit off-topic but I guess if you feel motivated to profile the import process too, the 25 monkeys takes a good ~160 seconds to import into BlenderBIM which is crazy long :)

Test case:

```
import time
import ifcopenshell
import ifcopenshell.util.element

class Usecase:
    def __init__(self, file, settings=None):
        self.file = file
        self.settings = {"representation": None}
        for key, value in settings.items():
            self.settings[key] = value

    def execute(self):
        start = time.time()
        dummy_context = self.file.create_entity("IfcRepresentationContext")
        for subelement in self.file.traverse(self.settings["representation"]):
            if subelement.is_a("IfcRepresentationItem") and subelement.StyledByItem:
                [self.file.remove(s) for s in subelement.StyledByItem]
            elif subelement.is_a("IfcRepresentation"):
                subelement.ContextOfItems = dummy_context
                self.purge_representation_inverses(subelement)
        self.purge_representation_inverses(self.settings["representation"])
        print(time.time() - start)
        start = time.time()
        ifcopenshell.util.element.remove_deep(self.file, self.settings["representation"])
        print(time.time() - start)

    def purge_representation_inverses(self, element):
        for inverse in self.file.get_inverse(element):
            if inverse.is_a("IfcPresentationLayerAssignment"):
                assigned_items = set(inverse.AssignedItems)
                if len(assigned_items) == 1:
                    self.file.remove(inverse)
                else:
                    assigned_items.remove(element)
                    inverse.AssignedItems = list(assigned_items)

f = ifcopenshell.open('monkey25.ifc')
Usecase(f, {"representation": f.by_id(12580)}).execute()
```

**Comment by aothms** [comment]
I tried to hack something together, resulting in a significant reduction but it still takes some secs

The issue is suppose we delete the polyline `#1`

```
#1=POLY((#2,#3,#4,#5));
#2=POINT();
#3=POINT();
#4=POINT();
#5=POINT();
```

remove_deep() will sort them so that the points will get deleted first, but after deleting `#5`, the poly needs to be updated to remove the dangling reference to `#1=POLY((#2,#3,#4))` until finally the points are deleted and we have a `#1=POLY(())` which is then deleted last.

I now have batch() mechanism that will defer the actual deletion until a call to unbatch() when it will follow the exact same code paths with the single exception that we have access to the full set of ids to be deleted so that we don't waste effort on keeping the attribute values in line on `#1` since we know it will eventually be deleted anyway.

Re importing: that's a known issue I'd say #841

**Comment by Moult** [comment]
Awesome! A few seconds is still great! I'll wait for the bot build and let you know how it goes!

**Comment by Moult** [comment]
Is there any reason why one might prefer to use the regular remove_deep instead of remove_deep_batched?

**Comment by aothms** [comment]
I just left it there in case of bugs and all, but in principle no
