### ISSUE TITLE
Git clone of OpenCascade returns a 404 Error when using win>build-Deps

### ISSUE THREAD

**Issue by seb-esser** [IfcOpenShell/IfcOpenShell#1378]
I am trying to install the dependencies using `win\build-deps.cmd`. Cloning OpenCascade returns a 404 Page not found to me. Perhaps a rather recent change in the OpenCascade URLs but does anybody have a short-term resolution to exchange the URL instead of installing OCCT manually? 

https://github.com/IfcOpenShell/IfcOpenShell/blob/d56869d34161322e0fd16c5222a1e5390f7a2fbd/win/build-deps.cmd#L278

Thanks in advance

**Comment by aothms** [comment]
I noticed yesterday the docs were gone. Indeed it seems most of the technical resources are gone, even on the new site https://www.opencascade.com/open-cascade-technology/ the links to dev portal result in a 404.

In the mean time I pushed a temporary copy here https://github.com/aothms/OCCT/tree/V7_3_0p3

**Comment by aothms** [comment]
Just got word back from them there is an official mirror as well: https://github.com/Open-Cascade-SAS/OCCT

**Comment by aothms** [comment]
It appears the official github mirror didn't have tags so the build scripts would still fail.

The original anonymous access is also restored now:

``` $ git clone https://git.dev.opencascade.org/repos/occt.git occt
Cloning into 'occt'...
remote: Enumerating objects: 277968, done.
...
```
