### ISSUE TITLE
measuring progress while loading file

### ISSUE THREAD

**Issue by jf---** [IfcOpenShell/IfcOpenShell#138]
while loading large IFC files, it could be cool to be able to set a callback, for tracking progress. this would make it easy to have a progress bar updating while loading the file

**Comment by Stinkfist0** [comment]
While on the subject, I have been thinking that it would be nice to outsource the "progress bar" printing in IfcFile to the application code (e.g. IfcConvert) - at least personally I library functions that "spam" stdout with a bit poor design.

**Comment by aothms** [comment]
@jf--- I am going to make an educated guess you are talking specifically about `ifcopenshell.geom.app` here? Coincidently I did do a recent commit by which the progress is printed to stdout now [1]. If you have ideas to make this less obscure with PyQT signals, would be happy to hear them.

[1] https://github.com/IfcOpenShell/IfcOpenShell/commit/efd6eb7f97a4363eb5103507decc62980911ca35#diff-bbb24e356eb79b640d55050d95ecb646R242

@Stinkfist0 Sure. A callback function could be the solution here as well. In fact, we can just seek to the end of the file first to get its length, map this "Scanning file" pass also to a [0, 100] range, and send that over a user-supplied `std::function<void(int)>`.

**Comment by jf---** [comment]
👍 for th callback idea, that would be great. would that range  include the time required for reconstructing the geometry from the parsed IFC file? i guess that's what will take most time

**Comment by Moult** [comment]
I guess this one is solved with iterator.progress() and can be closed? :)

**Comment by Moult** [comment]
Going to answer "yes" and close it :) Someone feel free to reopen/ping if I'm wrong.
