### ISSUE TITLE
IfcOpenBot seems to be asleep :)

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1383]
Last build seems to be a while ago :)

**Comment by aothms** [comment]
See #1378 the OCCT repo is currently unavailable causing all the build script to fail

**Comment by Moult** [comment]
@aothms thanks! I suspected there might be a correlation! I'll just keep watch :)

**Comment by aothms** [comment]
For testing purposes you should be able to use the docker images form github actions (as you referred to in another issue) They are pushed to dockerhub aecgeeks/ifcopenshell (as I couldn't get other things to work).

I don't know how familiar you are with Docker but I guess it ought to be possible to install Blender in it as well and register the BlenderBIM addon, feel free to have a go at modifying the Dockerfile. Or even a working python interpreter would be nice of course. Not sure on the status of that.

Also, the dockerfile is built against liboce it seems which is outdated. Not sure of the latest packaging work on opencascade at the moment but I think there are newer packages floating around.

**Comment by Moult** [comment]
Ah right - it's more because I use the download links to package a new release for end-users. I guess I could rewrite my packaging script to extract it from Docker but it is a bit of extra work :)

**Comment by aothms** [comment]
Yeah no that's not really an option I guess because the Docker build
heavily relies on the package manager so it has more dependencies. I was
only thinking about testing.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op ma 15 mrt. 2021 08:21 schreef Dion Moult ***@***.***>:

**Comment by Moult** [comment]
Is bot awake? :)

**Comment by aothms** [comment]
She's not running autonomously yet. I just scheduled a new build after the changes for #1153.

**Comment by Moult** [comment]
Ah ok, will close this bug :)

**Comment by htlcnn** [comment]
@aothms I see IfcOpenBot has posted new builds for master branch instead of v0.6.0. Is that intentional?
I have to use latest v0.6.0 build to parse ifc file and use `by_type` function. Latest master build's `by_type` function returns empty list.
