### ISSUE TITLE
Tessellation (PolygonalFaceSet) seems significantly slower than FacetedBrep

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1391]
Sample file containing identical meshes:

 - [test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6153676/test.ifc.txt) (faceted brep)
 - [test2.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6153677/test2.ifc.txt) (polygonal face set)

```
# Faceted brep test.ifc
Loaded in  0.030386924743652344
Finished in  1.4439947605133057

# Tessellation test2.ifc
Loaded in  0.017094135284423828
Finished in  8.179852962493896
```

Sample code:

```
import time
import ifcopenshell
import ifcopenshell.geom


start = time.time()
f = ifcopenshell.open("/home/dion/test.ifc")

print("Loaded in ", time.time() - start)
start = time.time()

settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, f)
iterator.initialize()
while True:
    shape = iterator.get()
    if not iterator.next():
        break

print("Finished in ", time.time() - start)
start = time.time()
```

**Comment by aothms** [comment]
Yes that's because triangulated/polygonal faceset don't use the `faceset_helper` we have in place for facetedbrep. We should unify this.

**Comment by Moult** [comment]
Closing bug, as with new fixes the times are roughly equal. Hooray! :D :D :D
