### ISSUE TITLE
Edit wall -> Extrude -> Escape mangles object

### ISSUE THREAD

**Issue by plaes** [IfcOpenShell/IfcOpenShell#1396]
When trying to extrude a wall, and cancelling, the wall is still modified a bit.

How to reproduce (Blender 2.91.2 + 20210311):
* Add -> Mesh ->  "Dumb Wall"
* Select object (this is another small bug, as by default in Blender when adding a new mesh, you end up with the new object as selected)
* Go to edit mode (TAB)
* Extrude (E) (notice how object gets mangled a bit)
* Press escape - this should cancel the operation, but instead object ends up messed up a bit.

![image](https://user-images.githubusercontent.com/91895/111839428-71acf680-8903-11eb-96ae-350b0d5f46a4.png)

**Comment by Moult** [comment]
Lack of wall selection is a bug. The escape behaviour is correct, this is vanilla blender and that is how blender works. In blender if you escape an extrusion it doesn't cancel, it simply resets the extrusion location. The coincident point trips up the solidify modifier. This is normal.
