### ISSUE TITLE
MTL transparency parameters.

### ISSUE THREAD

**Issue by iras** [IfcOpenShell/IfcOpenShell#140]
@aothms Hi, I have noticed that the [transparency value](https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/WavefrontObjSerializer.cpp#L66-L70) for the MTL file might be computed incorrectly.

Both 'd' (dissolve) and 'Tr' (transparency) are set to be the same value and that seems to contrast with what found in the [Wikipedia .obj format](https://en.wikipedia.org/wiki/Wavefront_.obj_file) page where Tr = 1 - d  (not that the wikipedia is the necessarily correct on that)

I can amend the code and push it if you think that's the case.

**Comment by iras** [comment]
@aothms Additionally, I can't seem to find anywhere the parameter 'D' (capital d). Can that be removed altogether?

**Comment by aothms** [comment]
I think you raise a good point. So, to add another source of confusion, the Blender OBJ importer treats `d` and `Tr` as independent attributes for dissolve and **translucency**. Another indication to stay away from what is output now.

~~~
                    elif line_id == b'd':  # dissolve (transparency)
                        context_material.alpha = float_func(line_split[1])
                        context_material.use_transparency = True
                        context_material.transparency_method = 'Z_TRANSPARENCY'
                        context_material_vars.add("alpha")
                    elif line_id == b'tr':  # translucency
                        context_material.translucency = float_func(line_split[1])
~~~

I guess the most sensible thing to do is keep only `d` and verify whether this correctly imports in some (arbitrary) list of applications. I have checked 3ds max and Blender, and so far both are fine with just `d`. Model is here [1] [2] for others to check.

[1] http://ifcopenshell.org/obj_test/cube.obj
[2] http://ifcopenshell.org/obj_test/cube.mtl

#### 3ds max
![3ds max](https://cloud.githubusercontent.com/assets/1096535/19212007/4b38d696-8d49-11e6-8cf8-799bd90c32c0.png)
#### blender
![blender](https://cloud.githubusercontent.com/assets/1096535/19212006/4b30fac0-8d49-11e6-93a3-380d5ef36900.png)

**Comment by iras** [comment]
@aothms Good idea. Rourke's docs on MTL format http://paulbourke.net/dataformats/mtl/ doesn't even mention 'Tr' as an MTL parameter.

Would you like me to remove lines 68 and 70 and push the change?
