### ISSUE TITLE
IfcOpenBot seems to build with WITH_IFCXML not set?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1404]
Initially mentioned by @CyrilWaechter in #854 I also noticed that `ifcopenshell.ifcopenshell_wrapper.parse_ifcxml` doesn't exist after a user tried to import an IFCXML file. Is this due to a build setting with IfcOpenBot?

**Comment by aothms** [comment]
Very strange. Has this ever worked? It seems that SWIG does not generate the wrapper function (my guess is due to a change in SWIG when upgrading to 4?) The only way I got it to work (and which is maybe better) is to always generate the function but throw an exception when compiled without XML.

**Comment by Moult** [comment]
Thanks so much! It did work in the past once a upon a time :)
