### ISSUE TITLE
IfcOpenBot links seem to be named wrongly?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1405]
Looking at https://github.com/IfcOpenBot/IfcOpenShell/commit/ff7219b5577892e19b4f80d7ad07db2b4aadb3db#commitcomment-48770718 for Blender py37 you can see that it says 32bit twice, as well as windows 64bit twice, and macos only seems to have 32bit. The URLs seem to be correct, though, as I see linux32 vs linux64, so I'm guessing this is purely a cosmetic glitch, and that the build actually did work :) Just thought I'd mention it :)

**Comment by aothms** [comment]
Thanks, yes https://github.com/IfcOpenShell/IfcOpenBot/commit/8d221e79d5d8f5a9e567d2cb3633a44d2ce6f96a was very misguided, but it's fixed now by https://github.com/IfcOpenShell/IfcOpenBot/commit/4cfc261e68706de3125a6b96c936f948f4cce69c - this code is unreadable :(

It was only cosmetic in the table formatting.

**Comment by Moult** [comment]
My eyes! :D
