### ISSUE TITLE
Infinite IfcConvert (example file)

### ISSUE THREAD

**Issue by Amoki** [IfcOpenShell/IfcOpenShell#1411]
Hi,

This model (we extracted breaking elements in a smaller IFC file) is mostly 23BM of `IFCCARTESIANPOINTLIST3D` and makes IfcConvert stuck with 100% CPU on them.

[infinite_convert.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6243534/infinite_convert.zip)

Other BIM services can convert them without problems.

It has been tested with on commit https://github.com/IfcOpenShell/IfcOpenShell/commit/49ea774 (15th march)
with command `IfcConvert /tmp/infinite_convert.ifc /tmp/test.glb --use-element-guids -y --enable-layerset-slicing --include entities IfcObject --exclude entities IfcOpeningElement --verbose --verbose`

**Comment by aothms** [comment]
I've overhauled the handling of the tesselated items to use the same mechanism as we have for the old ifc2x3 connected faceset. It'll be more efficient [don't expect miracles though, for detailed meshes there is still the price we have to pay for using a heavy brep modeller] and robust (some topology checks before creating shapes and more). It needs to be properly tested though. It's a fundamental change on common representation types.

**Comment by aothms** [comment]
cf68cf6f5c380fdfcbd93371c42fab466f31c7ca
3f9e5ca806f06cf9507975f655f21f2c21fdd0a7

**Comment by Moult** [comment]
Ping @Amoki can you try again and see if this issue can be closed?

**Comment by aothms** [comment]
Yes indeed, handling of tesselated items has since improved

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op di 8 jun. 2021 05:35 schreef Dion Moult ***@***.***>:

**Comment by Amoki** [comment]
Yep Sorry!
This bug has been fixed :)
