### ISSUE TITLE
import/export not working

### ISSUE THREAD

**Issue by stefbulcke** [IfcOpenShell/IfcOpenShell#1413]
Hi,

First of all, my compliments for the promising work!  This might be the game-changer in the architectural CAD-world.  I know it's hard work - my deepest respect for that -, but a lot of people might be waiting for this kind of breakthrough... 

I do work with Bricscad and recently started testing Blender en BlenderBim.  The learning curve (or adapting curve ;-) ) is quite steep, by my goodness, what a difference in quality and possibilities .  

So, I thought why not trying to help just a tiny little bit.  

My (first...) remark concerns the import/export functionality.  If I export a ICF file, and then import it in an other (new) file, the changes made in the first (saved) file are lost.  Somehow it seems the program always exports the previously imported data, or the cube for that matter  if you started from scratch.

I might be overlooking something(s), but I can't get this right (for now) ...

grtz
and enjoy Easter

![Schermafbeelding 2021-04-03 om 19 06 38](https://user-images.githubusercontent.com/36689761/113486315-5ec52500-94b2-11eb-9728-c04ecf0c8c38.png)
![Schermafbeelding 2021-04-03 om 19 10 24](https://user-images.githubusercontent.com/36689761/113486318-5ff65200-94b2-11eb-9419-22778e588bd2.png)
![Schermafbeelding 2021-04-03 om 19 11 22](https://user-images.githubusercontent.com/36689761/113486320-61c01580-94b2-11eb-94dc-ddbd3fcdc9e4.png)
![Schermafbeelding 2021-04-03 om 19 11 32](https://user-images.githubusercontent.com/36689761/113486321-6258ac00-94b2-11eb-957d-9678e19a8ff5.png)

**Comment by Moult** [comment]
G'day! There was a new release, give that a shot and hopefully your problems disappear ;)

History of what is affecting you: https://github.com/IfcOpenShell/IfcOpenShell/issues/1360

**Comment by stefbulcke** [comment]
Hi,

Thanks for the reply and the redirection which I've read.  
Whatever I do (manual updating) importing always returns the last/previous version (or the cube).
But no probs, I 'll await further releases.

Keep up the good work!

**Comment by Moult** [comment]
@stefbulcke that should not be the case.

 1. Upgrade to new version.
 2. Brand new file, single cube.
 3. Export IFC.
 4. Edit cube.
 5. Export IFC.

That should change the cube.

**Comment by stefbulcke** [comment]
Hi Dion,


Thanks for the swift answer.  
I downloaded BlenderBim only a few days ago and redownloaded it yesterday once again (just to be sure...).
You'll see the specs in the SS.

Whatever I do, I always get the cube back.
I followed your steps meticulously without changing anything and exported the IC immediately.
As I saw online this should create a new project, but I always get an error (see SS).

I noticed the problem when I imported a project I'm working on (see SS).  It imported very wel but changes never got exported.  I always get the original ICF back.

grtz

![Schermafbeelding 2021-04-05 om 10 04 44](https://user-images.githubusercontent.com/36689761/113553561-419a6e80-95f8-11eb-8451-5a1dea73f348.png)
![Schermafbeelding 2021-04-05 om 10 05 40](https://user-images.githubusercontent.com/36689761/113553564-43643200-95f8-11eb-8c2f-fcc0efbbeb24.png)
![Schermafbeelding 2021-04-05 om 10 06 41](https://user-images.githubusercontent.com/36689761/113553567-44955f00-95f8-11eb-9ae3-af2d4c4d083f.png)
![Schermafbeelding 2021-04-05 om 10 11 21](https://user-images.githubusercontent.com/36689761/113553569-452df580-95f8-11eb-8fa1-7a8f8ebe0fde.png)

**Comment by Moult** [comment]
The latest version is v0.0.210404. Yours is still the previous version.

**Comment by stefbulcke** [comment]
Even with the latest version...

1.  When exporting from a blank file, an error is always presented (SS)
2.  When creating the project, assigning the Class, updating the Mesh... sometimes an error is thrown (SS)
3. when importing in new file always "The Cube"...
4. when duplicating an object, it is not in the ICF...

The project-structure seems to be OK but somehow it always and only takes the original cube, nothing more.
If I imported a large file, that went OK, but it never changed the original ICF data.

Hope that is somewhat helpfull.

grtz

![Schermafbeelding 2021-04-05 om 11 47 53](https://user-images.githubusercontent.com/36689761/113561635-30a42a00-9605-11eb-8a3a-e83765356dc4.png)
![Schermafbeelding 2021-04-05 om 11 46 38](https://user-images.githubusercontent.com/36689761/113561645-339f1a80-9605-11eb-9f82-934b3f6fbd68.png)
![Schermafbeelding 2021-04-05 om 11 08 28](https://user-images.githubusercontent.com/36689761/113560443-4a447200-9603-11eb-8880-67c5097d47f6.png)
![Schermafbeelding 2021-04-05 om 11 41 40](https://user-images.githubusercontent.com/36689761/113560833-f1c1a480-9603-11eb-8057-8dfb188c2998.png)
![Schermafbeelding 2021-04-05 om 11 39 44](https://user-images.githubusercontent.com/36689761/113560836-f2f2d180-9603-11eb-9e19-e60e06dfab2b.png)
![Schermafbeelding 2021-04-05 om 11 40 26](https://user-images.githubusercontent.com/36689761/113560838-f38b6800-9603-11eb-8dbb-c09266438cb6.png)
![Schermafbeelding 2021-04-05 om 11 30 14](https://user-images.githubusercontent.com/36689761/113560178-ddc97300-9602-11eb-802e-09a1d3989a74.png)

**Comment by Moult** [comment]
Hmm, this doesn't seem to be progressing well at all. I'm online right now, can you catch me online on the OSArch.org live chat? We can screenshare and sort it out. If not, catch me online during some waking hours 8am-9pm Sydney time and let's figure this out. I suspect this is a bit of miscommunication happening here, and I'd like to learn what I can do to prevent other users from running into this.

**Comment by stefbulcke** [comment]
Found you on KiwIrc...
using this for the first time, so give me some credit...;-)
