### ISSUE TITLE
Ifcclass not associated with object 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1415]
any clue why the ifcclass doesn't show up for the walls in the following model? 

That last screen capture is of a 'dumb wall' i added to the model. 

Files: https://gitlab.com/openingdesign/heck_residence/-/tree/df34ccc3845e659595d2daf444b2f36547e2d0ac/Models%20and%20CAD

![image_20210404145037](https://user-images.githubusercontent.com/507113/113519971-77d2e200-9555-11eb-9df8-c28a64d609ad.png)

![2021-04-03_08-38-49_ShareXShareX_-_Region_captureShareX_20210404145045](https://user-images.githubusercontent.com/507113/113519948-540f9c00-9555-11eb-9baa-0557a152b429.png)

**Comment by Moult** [comment]
The IFC file it is linking to has no data. If you check the IFC files in https://gitlab.com/openingdesign/heck_residence/-/tree/df34ccc3845e659595d2daf444b2f36547e2d0ac/Models%20and%20CAD you will see they are almost empty.

**Comment by theoryshaw** [comment]
yes, just noticed that already. 
related discussion: https://matrix.to/#/!glDiVjFmJULvbfLcht:matrix.org/$CRjz61ZfLuf16mEJbf2ZlVZNi3RPZhXRAU9kB319UGM?via=matrix.org&via=t2bot.io

@Moult, as I understand it, the BlenderBIM file is inextricably linked to the BlenderBIM file.  That is, they need to be transmitted together.  You cannot reconjure the IFC file from the isolated BlenderBIM file, correct?

**Comment by Moult** [comment]
The IFC file is the source of truth. Everything is stored in IFC. Blender is nothing but an authoring client, which is editing either a portion or the whole of the IFC, so your Blend file is simply a snapshot of your current authoring / editing session. So correct, you cannot reconjure the IFC from the isolated Blend file.

If you want to transmit your BIM model to another, you can either transmit just the IFC, or the IFC + the Blend file, if you wanted to give your recipient a bit of insight as to what aspects you were authoring, or if you have Blender-specific data on top (e.g. non-BIM design experimentation, overlays, greasepencil annotations, etc), but the Blend file is unnecessary.

At best, you could create a fresh IFC from the Blend file, but that IFC would contain nothing but a superficial spatial structure, geometry, and names, but no other meaningful data.
