### ISSUE TITLE
can't edit cost schedule

### ISSUE THREAD

**Issue by aldomontanari** [IfcOpenShell/IfcOpenShell#1416]
![imagen](https://user-images.githubusercontent.com/32773354/113636812-a0d49f00-9649-11eb-99c2-1754d23ddb14.png)
when I press the edit button, a new cost schedule is created
blender 2.93.0 Alpha
blenderbim version 210405-py39

link to file:
https://github.com/aldomontanari/PruebasOSBIM/blob/eebc8ac7127bea9f0f43be7540690bc7210d3ab0/Piloto_Estructural_blenderBIM/b293_bbim210405.blend

**Comment by Moult** [comment]
Not a bug. Feature not yet built.

**Comment by Moult** [comment]
Ping yassine sigma to implement :)
