### ISSUE TITLE
Build fails on missing pthread.h on win 64 plattform

### ISSUE THREAD

**Issue by DrorSegev** [IfcOpenShell/IfcOpenShell#142]
Build dep works fine.
run-cmake "Visual Studio 10 2010 Win64" fails with error:

cmake version - 3.6.2

CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\IfcOpenShell-master\build-vs2010-x64\CMakeFiles\CMakeTmp\cmTC_dc659.vcxproj] 
Logs attached

[CMakeFiles.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/518346/CMakeFiles.zip)

Thanks
Dror

**Comment by DrorSegev** [comment]
Please ignore - the problem was ICU

**Comment by aothms** [comment]
Thanks for the update. Care to elaborate what fixed your issue in case others run into the same? Would be appreciated.

**Comment by DrorSegev** [comment]
The build-dep command downloaded icu-55.1-vs2010.7z  but did not extract it to deps-vs2010-x64-installed/icu . this caused run-cmake to quit with error about **UNICODE**/ But in the error log the lat log was about pthread (which you can ignore).
Anyway I've manually extracted the icu file (lib->lib, include->include) and it worked like a charm!

DR
