### ISSUE TITLE
Importing Tessellation meshes is slow and generates additional geometry

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1421]
Attached are two versions of the same IFC mesh, this mesh has:

- 1948 unique vertices
- 2251 faces, consisting of:
  - 1977 quad faces
  - 274 triangles

A simple conversion to triangles would return 1977*2 + 274 = 4228 triangles

[_test_tessellation.ifc.gz](https://github.com/IfcOpenShell/IfcOpenShell/files/6269744/_test_tessellation.ifc.gz) is a Tessellation constructed using IfcCartesionPointList3D, IfcIndexedPolygonalFace and IfcPolygonalFaceSet. IfcConvert takes 6.5 seconds to process this into a DAE file with 4240 triangles, there are more triangles than expected and additionally the resulting mesh is non-manifold in blender.

[_test_brep.ifc.gz](https://github.com/IfcOpenShell/IfcOpenShell/files/6269743/_test_brep.ifc.gz) is a Brep constructed using IfcCartesianPoint, IfcFace and IfcClosedShell. It is a much larger file because this format is very inefficient. IfcConvert takes 3 seconds to process this into a DAE file with 4228 triangles, this is the expected result.

In principle, the Tessellation should be simpler to process since there is no need to identify and merge duplicate points, but the result is slower and less accurate.

**Comment by Moult** [comment]
See #1391 and #841

**Comment by Amoki** [comment]
Can https://github.com/IfcOpenShell/IfcOpenShell/issues/1411 be related to it too?
The example model uses Tessellation too.

**Comment by brunopostle** [comment]
Tessellation handling seems ok here using current git

**Comment by Moult** [comment]
@brunopostle does "ok" refer to speed or the additional geometry issue?

**Comment by brunopostle** [comment]
@Moult Speed with Tessellation seems to be almost exactly the same as IfcClosedShell Brep. The geometry issues are fixed, at least the test mesh that was becoming non-manifold before is now ok.

**Comment by Moult** [comment]
Awesome! Closing issue :D
