### ISSUE TITLE
Support for more IfcProperty types

### ISSUE THREAD

**Issue by LaurensJN** [IfcOpenShell/IfcOpenShell#1422]
Currently, the only IfcPropery type that is implemented is the IfcPropertySingleValue (at least what I'm aware of, please correct me if I'm wrong). 

I was wondering if there are any plans to implement other types such as IfcPropertyEnumeratedValue or IfcPropertyListValue, or even IfcComplexProperty? Many Psets have an enumerated, bounded or list value so it would be helpful to correctly add these to IFC models.

**Comment by Moult** [comment]
It is planned. Perhaps it should be sooner rather than later.

**Comment by LaurensJN** [comment]
That'd be terrific! 
Perhaps I should have specified that I was aiming this question at the IfcOpenShell library itself, not necessarily BlenderBIM. Although that'd go hand-in-hand anyway.

**Comment by Moult** [comment]
@LaurensJN FWIW, the ifcopenshell.util.element.get_psets() does accommodate complex properties, from memory, so perhaps that can be useful in the meantime?

**Comment by LaurensJN** [comment]
Thank you! I figured out how it is possible with pure IfcOpenShell. This is currently how I'd add complex properties now, until something is implemented in BlenderBIM. I used just a random example of adding colour property to a wall here: 

```python
import ifcopenshell

ifcfile = ifcopenshell.open("foo.ifc")

wall = ifcfile.by_type('IfcWall')[0]
RGB = {'red': 255, 'green': 0, 'blue': 0}
property_values = []
for colour, val in RGB.items():
    entity = ifcfile.create_entity('IfcInteger', val)
    property_values.append(ifcfile.createIfcPropertySingleValue(colour, f'{colour} component of RGB', entity, None))
ifcfile.create_entity('IfcComplexProperty', 'Colour', None, 'Colour', property_values )
ifcfile.write('bar.ifc')
```

output:
```
#16608=IFCPROPERTYSINGLEVALUE('red','red component of RGB',IFCINTEGER(255),$);
#16609=IFCPROPERTYSINGLEVALUE('green','green component of RGB',IFCINTEGER(0),$);
#16610=IFCPROPERTYSINGLEVALUE('blue','blue component of RGB',IFCINTEGER(0),$);
#16611=IFCCOMPLEXPROPERTY('Colour',$,'Colour',(#16608,#16609,#16610));
```

**Comment by Moult** [comment]
Cheers, in that case, I will keep this bug open, and tag it as BlenderBIM Add-on related, as someone else in the past has asked for complex property support.

**Comment by Moult** [comment]
Bump and ping @LaurensJN out of curiosity, what is your usecase for IfcComplexProperty? Are you coming across files which have this data in them? Which applications are producing these files?

**Comment by LaurensJN** [comment]
We had no practical usecase, only academic. It was the most appropriate for the data model we made for semantic enrichment of HBIM (historical/heritage BIM) models, in some way better than using PropertySets instead. So the only application that we used that produced these files is IfcOpenShell actually :)

One example is the use of a fuzzy date with two IfcDate single properties (start/end of period), that can express annotations such as 'from the beginning of the 17th century' in a way that you can actually query them, while not knowing the exact year that an element is from. Currently in IFC there is no format that adequately defines this kind of data format. I hope that is clear?

**Comment by Moult** [comment]
Hmm, what's wrong with two separate properties for StartDate and EndDate? If it's fuzzy, perhaps you may also need StartDatePrecision and EndDatePrecision? Just throwing out ideas.

**Comment by aothms** [comment]
@LaurensJN @berndhahnebach what are your thoughts on complex properties? In terms of handling them in UI. Etc.

To me it seems a bit much (a) multiple property sets (b) a lot of IfcValue options (c) complex property decomposition. 

I think they are mostly in the structural domain. Do you see alternatives (moving them to separate psets, other IfcValue types, ...)?

**Comment by Moult** [comment]
A note that for the COBie specification, it is required that all complex properties (e.g. current/voltage/phase combo, or in australia we have a fire rating combo made out of three parts) be split up into distinct simple properties. Just thought that might help the discussion.

**Comment by Moult** [comment]
Another note that currently for schedules (both derived and arbitrary) we currently store it in externally referenced ODS/CSV files which can be then printed on sheets for documentation. However, with the tabular properties, this could be done directly in IFC...

**Comment by LaurensJN** [comment]
@aothms maybe an idea is to treat it as some sort of namespace? I think that is what a lot of other IFC viewers would do (so complex property ConstructionPeriod and single value StartDate would be treated as single value Construction.StartDate while complex property DemolitionPeriod and single value StartDate would be treated as single value Demolition.StartDate)? 

Reason for not having Psets instead of complex properties is because you cannot have the same propertyset twice for an element. In the above example we had complex property Period that was used for both construction & possible demolition dates (in the case of heritage buildings you'd like to know what might have been built in history and already demolished). So either that means you'd make a propertyset ConstructionPeriod and a propertyset DemolitionPeriod and give those the same properties, or you'd make one complex property Period that can be reused. In the case that we had, where we wanted to formalize our data structure, the latter just made more sense. 

Eventually, if heritage BIM grows bigger and gets some attention by BuildingSMART, I think for these kind of cases you'd want something like a separate entity in IFC like there the IfcTimePeriod now for scheduling (and many more variants that are more sophisticated, but I think @Moult knows that better than I do, considering all the progress in scheduling 😄 ). But I don't think we're just there yet.

**Comment by Maozerhouni** [comment]
Hello,
We have been working on this issue at work. I hope this feedback will help the discussion :
- One of the problems we faced regarding ComplexProperty is that the schema don't limit the possible depth. So in theory, you can have a complex property that nests a complex property, that nests another complex Property. Keeping a three aspect seemed much more preferable for us than the namespace strategy (which is used by ArchiCAD and Revit)
- ComplexProperty nests other complexProperty or SingleProperties. A question raised was if we should consider 'double' linking SingleProperties with IfcElement. This depends on weather ComplexProperty represents an agregation of different properties (for example, an adress.) or properties of a subelement of the object (which is the main use today)

**Comment by Moult** [comment]
Yes the potential unlimited nesting could be a little nasty, but practically probably not too big of a concern. After all tons of schemas allow unlimited nesting.

i'm increasingly of the opinion that we should build support for this, and "see what happens" in the real world. I'm hesitant to drop it with the same logic that caused the drafting entities to be dropped.

**Comment by aothms** [comment]
As you are aware there are some strong voices in the community to remove complex properties from the schema. Before investing effort in implementing them (and arbitrary nesting of them, which seems like a paradigm that isn't supported well if I look at the current UI of other tools) I would at least wait and see what their status is after the infra/building reconciliation fixes in 4.3

**Comment by Moult** [comment]
Agreed, I'll hold off a while longer. I'd personally support limiting the nesting (maybe it's enough as a documentation note?), but I'd be wary about removing things like table or range properties.

**Comment by Moult** [comment]
A reference for anyone following this is this issue upstream: https://github.com/buildingSMART/IFC4.3.x-development/issues/134

**Comment by Moult** [comment]
Closing as upstream has deprecated this, so no point in implementing.
