### ISSUE TITLE
IFC with IFC DateAndTime causing import failures

### ISSUE THREAD

**Issue by ASeau** [IfcOpenShell/IfcOpenShell#1423]
Hi all, I'm trying make use of blender to generate a timeline animation for modeling a construction process. The goal is to generate an IFC Tree that is categorized by the time the element is meant to be "constructed".    

However, when importing an IFC 2x3 file modified with IFC DateAndTime which is added using an external program (Synchro4D), the program fails at an AttributeError. The original IFC file not modified with IFC DateAndTime data imports fine so that's probably not the issue here. Any pointers to ignore (simply read in as a new object maybe) or alternative workarounds is highly appreciated. 

> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 165, in execute
>     ifc_importer.execute()
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 329, in execute
>     self.calculate_model_offset()
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 481, in calculate_model_offset
>     site = self.find_decomposed_ifc_class(project, "IfcSite")
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 565, in find_decomposed_ifc_class
>     results.extend(self.find_decomposed_ifc_class(part, ifc_class))
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 565, in find_decomposed_ifc_class
>     results.extend(self.find_decomposed_ifc_class(part, ifc_class))
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 558, in find_decomposed_ifc_class
>     rel_aggregates = element.IsDecomposedBy
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 67, in __getattr__
>     "entity instance of type '%s' has no attribute '%s'" % (self.wrapped_data.is_a(), name)
> AttributeError: entity instance of type 'IfcDateAndTime' has no attribute 'IsDecomposedBy'
> 
> location: <unknown location>:-1

The IFC file in mention:
[timedataadded.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6273936/timedataadded.zip)

**Comment by Moult** [comment]
@ASeau your zip file seems corrupted. Can you please reupload?

**Comment by ASeau** [comment]
I've added a .txt in case the zip format is still not working. Thanks! 
 
[timeaddedifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6283585/timeaddedifc.zip)
[ifc2x3.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6283586/ifc2x3.txt)

**Comment by Moult** [comment]
@ASeau ah, this is not a bug in the add-on. It seems your file is invalid. You have identical step IDs:

```
#115= IFCBUILDING('2aY7$55vH7YA__osmtQjFc',#41,'',$,$,#32,$,'',.ELEMENT.,$,$,#111);
...
#115= IFCDATEANDTIME(#113,#114);
```
