### ISSUE TITLE
Correct way to remove complete Psets

### ISSUE THREAD

**Issue by AlexanderNitsch** [IfcOpenShell/IfcOpenShell#1424]
I'm trying to delete some Property Sets from multiple objects, but I have yet to find a way to do this properly.

Currently I'm trying the following, but this leaves me with a corrupted ifc file.

```
ifc = ifcopenshell.open(filepath)
    all_elements = ifc.by_type(element_type)
        for element in all_elements:
        if element.is_a('IfcTypeObject'):
            if element.HasPropertySets:
                for definition in element.HasPropertySets:
                    if SOME CONDITION:
                        ifc.remove(definition)
        else:
            for relationship in element.IsDefinedBy:
                if relationship.is_a('IfcRelDefinesByProperties'):
                    definition = relationship.RelatingPropertyDefinition
                    if SOME CONDITION:
                        ifc.remove(ifc.by_guid(definition.GlobalId))
```
                    
If I save this ifc file and try to get the psets of elements with ifcopenshell.util.element.get_psets(element), I get multiple empty definitions back ( Like remains of the Psets that I wanted to delete).
In my final Code I want to only delete some Psets (f.e. based on name)

How would I go about cleanly removing complete Psets.

Thank you!

**Comment by Moult** [comment]
You can use the new API, which still is not finished but is evolving rapidly, and the more users testing it, the more we can make it robust for people to do more with less code!

```
ifcopenshell.api.run("pset.remove_pset", ifc, product=element, pset=definition)
```

**Comment by AlexanderNitsch** [comment]
Thank you for your fast reply, that looks like a much more elegant way of doing it.

Is there an easy way to install a version that supports this new api already, preferably with conda?

**Comment by Moult** [comment]
@AlexanderNitsch just grab it from github - the api folder is just python. https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcopenshell-python/ifcopenshell/api

**Comment by aothms** [comment]
Also see https://github.com/IfcOpenShell/IfcOpenShell/issues/1293#issuecomment-806457609 since propertysets are shared between objects you might be deleting the same object multiple times.

**Comment by TristanLecallier** [comment]
Hi @Moult !
 Does this code : `ifcopenshell.api.run("pset.remove_pset", ifc, product=element, pset=definition)` suppose to remove ifcPropertySingleValue linked to the pset ?
 Thanks !

**Comment by Moult** [comment]
@TristanLecallier yes it does

**Comment by TristanLecallier** [comment]
Ok thanks. In my test it does not I don't know why. On the other hand, the IfcRelDefinesByProperties linked to the pset is removed (with the pset of course).
Before removal my IFC file looks like :
`#229= IFCPROPERTYSINGLEVALUE('NominalWidth',$,IFCLENGTHMEASURE(0.25),$);
#233= IFCPROPERTYSINGLEVALUE('Perimeter',$,IFCLENGTHMEASURE(38.),$);
#234= IFCPROPERTYSINGLEVALUE('NetFootprintArea',$,IFCAREAMEASURE(90.),$);
#235= IFCPROPERTYSINGLEVALUE('NetVolume',$,IFCVOLUMEMEASURE(22.5),$);
#236= IFCPROPERTYSET('2NJ8tNEfXE6hVT70E6Mv39',#42,'BaseQuantities','',(#229,#233,#234,#235));
#248= IFCRELDEFINESBYPROPERTIES('1Itp43xFvAtuhzw93KCxei',#42,$,$,(#211),#236);`

After : 
`#229=IFCPROPERTYSINGLEVALUE('NominalWidth',$,IFCLENGTHMEASURE(0.25),$);
#233=IFCPROPERTYSINGLEVALUE('Perimeter',$,IFCLENGTHMEASURE(38.),$);
#234=IFCPROPERTYSINGLEVALUE('NetFootprintArea',$,IFCAREAMEASURE(90.),$);
#235=IFCPROPERTYSINGLEVALUE('NetVolume',$,IFCVOLUMEMEASURE(22.5),$);`

I used the same code : `ifcopenshell.api.run("pset.remove_pset", ifc_file, product=element, pset=propertySet)`

Do you have any idea ?

**Comment by aothms** [comment]
Are the properties referenced by other psets as well?

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op wo 23 mrt. 2022 13:23 schreef TristanLecallier ***@***.***

**Comment by TristanLecallier** [comment]
No, only with the deleted pset...

**Comment by Moult** [comment]
@TristanLecallier sorry I replied from my phone yesterday I should've mentioned that I only built that capability 3 days ago :) https://github.com/IfcOpenShell/IfcOpenShell/commit/e909f254329e18b7b62853eb3d28f0daa6a6d969

Sorry for the confusion.

**Comment by TristanLecallier** [comment]
Thanks @Moult, with this implementation, I have now this error : 
`could not convert to integer : 3221225477. Path ' exitCode'. 
value too big or too small for Int32`

Here my test file : 
[testBQ.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8339683/testBQ.zip)

**Comment by aothms** [comment]
You're probably trying to delete a pset twice, or something else. With the following script I don't experience any issue:

~~~py
import ifcopenshell
import ifcopenshell.api
ifc = ifcopenshell.open("testBQ.ifc")
for definition in ifc.by_type("IfcPropertySet"):
    if definition.PropertyDefinitionOf:
        elems = definition.PropertyDefinitionOf[0].RelatedObjects
        assert len(elems) == 1
        element = elems[0]
        ifcopenshell.api.run("pset.remove_pset", ifc, product=element, pset=definition)
ifc.write("result.ifc")
~~~

**Comment by TristanLecallier** [comment]
You are right, thanks a lot @aothms !
