### ISSUE TITLE
[BlenderBIM Addon] Error on wikilab import

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#1430]
## System infos
- OS : GNU/Linux (Manjaro)
- Blender version: 2.92
- bim addon version : 210413

## Steps to reproduce
1. Import [wikilab.ifc](https://github.com/uncreatednet/wikilab-ufabc/blob/master/wikilab.ifc)
2. => No crash but you get error message below

## Error message
```python
Python: Traceback (most recent call last):
  File "/home/cyril/.config/blender/2.92/scripts/addons/blenderbim/bim/operator.py", line 163, in execute
    ifc_importer.execute()
  File "/home/cyril/.config/blender/2.92/scripts/addons/blenderbim/bim/import_ifc.py", line 371, in execute
    self.clean_mesh()
  File "/home/cyril/.config/blender/2.92/scripts/addons/blenderbim/bim/import_ifc.py", line 995, in clean_mesh
    obj.select_set(True)
RuntimeError: Error: Object 'IfcBuildingElementProxy/Parede de fundação.001' can't be selected because it is not in View Layer 'View Layer'!


location: <unknown location>:-1
```

**Comment by Moult** [comment]
@CyrilWaechter not a bug, as the IFC is invalid. That particular element is this line:

```
#75=IFCBUILDINGELEMENTPROXY('1B1hP013GHvujW093rt3ko',#5,'Parede de funda\X4\000000E7000000E3\X0\o','',$,#72,#74,$,.ELEMENT.);
```

The element is an aggregate, but also has a representation and material. This is not allowed in IFC:

> By default the following constraints apply to an element being decomposed by Element Decomposition:
> 
>     Body Geometry — composite is constructed from the sum of the Body Geometry of the parts;
>     the composite shall not have an own Body Geometry, body geometry is provided at the parts;
>     the composite shall not have an own Material assignment, material is assigned to the parts.

So basically, if you're an aggregate, you don't get to have your own body / material.
