### ISSUE TITLE
New developer for costing / sequencing features

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1434]
Ping @aothms just added @myoualid who I have been pair programming with weekly who is hacking on costing / sequencing features for ifcopenshell.api and the relevant BlenderBIM Add-on UI.

Let me know if there are any issues :) I will be reviewing all of his commits in the near future until he is comfortable to be independent. He will not touch any C++ or other features without a PR / discussion.

**Comment by aothms** [comment]
Really cool. I heard Blender is going to get a spreadsheet editor and it already has a full blown animation capabilities obviously. BlenderBIM is going to provide real immediate concrete value here where there isn't a lot of "competition" yet I think. Welcome to the team @myoualid let me know if you have questions / comments
