### ISSUE TITLE
brep data gets lost in newer version of ifcopenshell

### ISSUE THREAD

**Issue by RobinVanTol** [IfcOpenShell/IfcOpenShell#1442]
I found ifc instance which no longer processes correctly in newer ifcopenshell versions.

I dont see how ifc indicates different sub versions since they are all version 6.0.0 for example. As such I will add the two versions I used. 
[ifcopenshell_versions.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6369572/ifcopenshell_versions.zip)

Switching between these two versions gave the following results

![ifcopenshell new](https://user-images.githubusercontent.com/38659478/115959016-589ef300-a50a-11eb-8250-e188850e0db2.png)
![ifcopenshell old](https://user-images.githubusercontent.com/38659478/115959017-59d02000-a50a-11eb-90e5-cf4af7e77679.png)

With the newer version giving no results.

The script used to produce these results:

[check_faces.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6369579/check_faces.zip)

If needed, I can provide an extract of the ifc file such that you can reproduce these results, however for privacy reasons I can't share this publicly so let me know how I should send it to you.

**Comment by aothms** [comment]
please send to models@ifcopenshell.org

**Comment by RobinVanTol** [comment]
I've sent you the ifc file

**Comment by aothms** [comment]
Yep, you're right there were a couple of (old) functionalities interacting that shouldn't have.

**Comment by RobinVanTol** [comment]
does this commit fix the script i sent, i got the latest release for py3.7 but with that im still having the same issue, and i dont know how to get the new release for python 2.7 to test in the environment i set up for this bug

**Comment by aothms** [comment]
@RobinVanTol did you try this version? https://github.com/IfcOpenBot/IfcOpenShell/commit/81ad6894782e91c7e007bcae16347f35f36b084b#commitcomment-50792889

**Comment by RobinVanTol** [comment]
no i was using the releases page from ifcopenshel/ifcopenshell this version indeed solves my issue thank you, if i may ask should i always look under ifcopenbot/ifcopenshell to get the latest version?

**Comment by aothms** [comment]
The web site should be synced, but it isn't fully automated yet.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op di 18 mei 2021 10:39 schreef RobinVanTol ***@***.***>:

**Comment by Moult** [comment]
Closing bug as solved, unless I misunderstood :)
