### ISSUE TITLE
"has no attribute register" prevents plugin activation

### ISSUE THREAD

**Issue by theRealSuperMario** [IfcOpenShell/IfcOpenShell#1446]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/6517465/116306424-53a9a000-a7a5-11eb-89ff-74f6e81a1145.png">

Surprisingly, the add-on worked for more than a year - and then it started crashing. Not sure what I got wrong here. So if anyone has any thoughts, I would be very happy.

**Comment by TristanHehnen** [comment]
Hi, I'm having the same issue, presumably.
![grafik](https://user-images.githubusercontent.com/34650649/117132892-c1f0f280-ada3-11eb-9809-1161b72b7905.png)

I'm on Windows 10 and just downloaded the most recent Blender LTS (2.83.13).

**Comment by TristanHehnen** [comment]
On further inspection, there seems to be a conflict with another addon that I'm using: [blenderfds](https://github.com/firetools/blenderfds).

After removing said addon, I'm able to install LfcOpenShell and am able to import ifc files into Blender.

**Comment by TristanHehnen** [comment]
And here is the link to a mirror issue with blenderfds:
https://github.com/firetools/blenderfds/issues/9

**Comment by Moult** [comment]
@theRealSuperMario have you tried clearing your Blender Add-ons folder and starting again? Given that you had an old version, the packaging has changed somewhat so trying from a blank state is a good way to debug. I suspect that your issue is different to @TristanHehnen .

**Comment by Moult** [comment]
Closing issue as likely due to fragments from older version.
