### ISSUE TITLE
Building 0.6.0 with OCCT 7.5.2

### ISSUE THREAD

**Issue by ahladik** [IfcOpenShell/IfcOpenShell#1449]
Hello,
I have discovered a bug in the generation of the oriented bounding boxes of OCCT, so I thought to rebuild IfcOpenShell 0.6.0 using the latest version 7.5.2 instead of 7.3.0p3, hoping that the problem has been fixed.

Unfortunately, the build process stops with the following message:

> error: can't open patch 'C:/dev/IfcOpenShell/IfcOpenShell-0.6.0/win/patches/V7_5_2.patch': No such file or directory

How could I solve the problem?

**Comment by ahladik** [comment]
Thank you very much! The build was successful, now I will check if the OCCT bug is fixed...

**Comment by aothms** [comment]
Did you report the bug? https://tracker.dev.opencascade.org/my_view_page.php

**Comment by ahladik** [comment]
I would like to. It repeats with specific geometries that don't seem to have anything particularly special, though. It could result from a combination of geometry and applied transformations.
Is there an easy way to generate a simple example in an appropriate format? Will the simple BRepTools::Dump() suffice?

**Comment by aothms** [comment]
BRepTools::Write() is preferable since that's the computer-readable format.

That's what I typically do. A couple of .brep files (BRepTools::Write) and then a small C++ script to highlight the problem.

**Comment by aothms** [comment]
FreeCAD or the OCCT Draw "Test harness" for example. https://dev.opencascade.org/doc/overview/html/occt_user_guides__test_harness.html

**Comment by ahladik** [comment]
Thanks, quite helpful!

**Comment by ahladik** [comment]
It seems that OpenCascade has a rather cumbersome procedure for reporting bugs. I'm a registered user and from what I read you don't have to sign the confidentiality agreement just to report a bug, however I can't seem to access the Mantis system. I get an error message every time. Nerve-wracking.

**Comment by ahladik** [comment]
OK, I asked them and they authorized me.
