### ISSUE TITLE
update links to issue tracker

### ISSUE THREAD

**Issue by thorade** [IfcOpenShell/IfcOpenShell#145]
You should update the links on this page:
http://blog.ifcopenshell.org/2011/08/ifcopenshell-needs-your-help.html

and close at least the following feature requests:
https://sourceforge.net/p/ifcopenshell/feature-requests/21/
https://sourceforge.net/p/ifcopenshell/feature-requests/25/

**Comment by aothms** [comment]
Done, thanks for the reminder.
