### ISSUE TITLE
IfcPolygonalFaceSet fails on create_shape

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1450]
See attached file. Element step id 69, with representation step id 67.

Ping @CyrilWaechter who helped find this issue with a student learning the BlenderBIM Add-on.

[tessellation.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6408438/tessellation.ifc.txt)

**Comment by aothms** [comment]
I've overhauled the handling of the tesselated items to use the same mechanism as we have for the old ifc2x3 connected faceset. It'll be more efficient [don't expect miracles though, for detailed meshes there is still the price we have to pay for using a heavy brep modeller] and robust (some topology checks before creating shapes and more). It needs to be properly tested though. It's a fundamental change on common representation types.

The file processes now, but appears a bit odd at one opening. Not sure what's up with that, if somebody wants to have a look that'd be appreciated. Maybe @Moult  you can double check what you get with BlenderBIM's internal processing?

cf68cf6f5c380fdfcbd93371c42fab466f31c7ca
3f9e5ca806f06cf9507975f655f21f2c21fdd0a7

**Comment by CyrilWaechter** [comment]
@Moult on my side, something is going wrong after:
```python
Starting import process :: 0.00
Load diff :: 0.00
Purge diffs :: 0.00
Loading file :: 0.35
Setting file :: 0.00
Calculate unit scale :: 0.00
Calculate model offset :: 0.00
Set units :: 0.00
Create project :: 0.00
Create spatial hierarchy :: 0.00
Create aggregates :: 0.00
Create aggregate tree :: 0.00
Create opening collection :: 0.00
Process element filter :: 0.00
Parsing native elements :: 0.06
Create grids :: 0.00
Done creating geometry
Create native products :: 0.00
```
It looks like it falls in an infinite loop. Process never end.

**Comment by CyrilWaechter** [comment]
@Moult I do not know what was modified but it looks like it is fixed. Model now import correctly and wall geometry is now created as expected.

**Comment by Moult** [comment]
@CyrilWaechter cool :) I've been changing all sorts of stuff, so let's just close the issue :)
