### ISSUE TITLE
Installing on Ubuntu

### ISSUE THREAD

**Issue by ArashMassoudieh** [IfcOpenShell/IfcOpenShell#1451]
I am trying to use IfcOpenShell through FreeCAD Python portal. I was able to successfully install the library and it works fine with my Python compiler independently. But when I type "import ifcopenshell" in the python portal in FreeCAD, I get the following error. Any help will be greatly appreciated: 

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/arash/IfcOpenShell-build/ifcopenshell/__init__.py", line 58, in <module>
    from .file import file
  File "/home/arash/IfcOpenShell-build/ifcopenshell/file.py", line 27, in <module>
    from . import ifcopenshell_wrapper
  File "/home/arash/IfcOpenShell-build/ifcopenshell/ifcopenshell_wrapper.py", line 15, in <module>
    from . import _ifcopenshell_wrapper
ImportError: libboost_regex.so.1.71.0: cannot open shared object file: No such file or directory_

The library (.so file) is in /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.71.0. Please note that I added the folder where the ifcopenshell_wrapper.py and _ifcopenshell_wrapper.so are to the sys.path. 

Any help will be greatly appreciated.

**Comment by CyrilWaechter** [comment]
It says that `/usr/lib/x86_64-linux-gnu/libboost_regex.so.1.71.0` is missing. Make sure that package [libboost-all-dev](https://packages.ubuntu.com/hirsute/libboost-all-dev) is installed.

**Comment by Moult** [comment]
Ping @ArashMassoudieh can you confirm whether that helped your issue?

**Comment by Moult** [comment]
Ping @ArashMassoudieh can you confirm if this has been fixed? If still no response after a month we can probably close this bug, as @emirhg responded to @CyrilWaechter 's suggestion positively.
