### ISSUE TITLE
Blender: copying a view makes others disappear

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1452]
video: https://www.dropbox.com/s/kstrxp5hi87x34p/2021-05-06_22-28-44.mp4?dl=0

files: https://gitlab.com/openingdesign/boathouse_monona/-/tree/52a94a7ad0a78cced4f73e96259cd915cd01ba29/Models%20and%20CAD

![image](https://user-images.githubusercontent.com/507113/117395067-eee4f880-aebc-11eb-8dfa-349d3dcee529.png)

**Comment by theoryshaw** [comment]
Hi, any thoughts on this one?  This one is unfortunate--because I copy views (or want to) copy them all the time.  Prevents having to set up a view from scratch each time.

**Comment by Moult** [comment]
I think this commit fixes it: https://github.com/IfcOpenShell/IfcOpenShell/commit/b8e20ec1a54f27c3e449236e5393ac349ee15306

**Comment by theoryshaw** [comment]
Confirmed, so far!  This is huge.
