### ISSUE TITLE
blenderbim decoupling blender logick from ifcopenshell one

### ISSUE THREAD

**Issue by s-leger** [IfcOpenShell/IfcOpenShell#1453]
At this time, it is nearly impossible to use blenderbim operators from outside as there are mix of blender's and pure ifc operations.

Some samples 
- bim.assign_class Operator also may create collections and move related objects to collections, rename objects and add some random magick making assuptions that objects are dumb ones by default - especially at project creation.
- bim.add_opening  create a boolean modifiers, however at this time geometry nodes boolean is way more effective to handle many holes, and other logick may also alredy handle the boolean part. 

Renaming objects on the fly will trigger "rename" handler, still not certain it is an isse at this point.

The "at class assignment" concept to keep virtual file in synch with scene approach make sense in blenderbim context, but it also require to "pollute" external code with blenderbim one and may not always be suitable / desirable from outside point of view. It also make pretty hard to assign / remove things on the fly at export time in order to provide a "for dumb" single button working exporter.

Proposed solution
At least keep operator's logick outside the operator itself as importable functions, and keep blender's operations apart from ifc ones, so it is possible to re-use core logick without actually re-implement when blender's operations are handled in a different way.

**Comment by Moult** [comment]
@s-leger operator logic is already outside the operator. You can call ifcopenshell.api.run("...") to perform every single IFC-related action that any operator performs. This way, you can build your IFC data model your way quite rapidly without ever needing to call any BlenderBIM operators.
