### ISSUE TITLE
Export Mystery

### ISSUE THREAD

**Issue by Rokorps** [IfcOpenShell/IfcOpenShell#1457]
Hello,
I am using blenderbim on blender. In versions 210221 and 210404 when I try to export anything, it exports always the same file, as it was imported. If I change positions of objects or even delete them, IFC exported is still the same as it was imported. Even if I choose only 1 object or even choose nothing, still, the same as imported.

I am using windows 7, python 3.7. Blender versions are 2.90 2.92, same thing happens.

Thank You for support,
Rokas

**Comment by Rokorps** [comment]
Does anyone have idea why this is happening?

**Comment by Moult** [comment]
Sorry for the delay. Can you try one of the py37 releases from here: https://github.com/IfcOpenShell/IfcOpenShell/releases and see what results you get? Be sure to uninstall the old add-on, restart blender, and remove the old add-on before installing the new version.

**Comment by Moult** [comment]
If you're online now, can you join the OSArch.org live chat and ping me there? We can screenshare and further debug what is happening.

**Comment by Moult** [comment]
Sorry for the long delay. I watched your screen recording you emailed me and the behaviour is as designed.

Basically, once you create or import an IFC file, that file is shown in the IFC Project panel. When you press export, that file will simply be overwritten with the changes you have made. You should not clear that field unless you know what you're doing (I've fixed the scary error message though) - the BlenderBIM Add-on needs to function with an IFC file. Whether you have one object selected or zero objects selected makes no difference - it will simply export whatever changes you've made to the file within the Blender scene.

I also noticed you had many objects outside the spatial hierarchy, this is not good practice and many viewers will not show the new objects.

Closing bug, as I cannot identify any incorrect behaviour so far :)
