### ISSUE TITLE
spacial.remove_container : pure virtual method called

### ISSUE THREAD

**Issue by s-leger** [IfcOpenShell/IfcOpenShell#1459]
Running 
ifcopenshell.api.run("spatial.remove_container", file, **{"product": product})
lead into crash reporting a pure virtual method called
looks like it is linked to reading product.ContainedInStructure

**Comment by Moult** [comment]
A crash may occur if you are holding an IFC element in memory that has been removed and are trying to access it. Can you share some code to help isolate this?

**Comment by s-leger** [comment]
Basically i'm trying to remove relationships from product like rel_fill, rel_void, aggregate and spacial container regardless of object's class / relationship so it is generic.

```python
    def ifc_remove_product(o):
        element_id = o.BIMObjectProperties.ifc_definition_id
        if element_id != 0:
            file = IfcStore.get_file()
            product = file.by_id(element_id)
            # will also remove filling if any
            ifcopenshell.api.run("void.remove_opening", file, **{"opening": product})
            # ifcopenshell.api.run("void.remove_filling", file, **{"element": product})
            print("spatial.remove_container")
            # XXX Disabled to prevent crash
            # ifcopenshell.api.run("spatial.remove_container", file, **{"product": product})

            if o.parent and o.parent.BIMObjectProperties.ifc_definition_id:
                print("aggregate.unassign_object")
                relating_object = file.by_id(o.parent.BIMObjectProperties.ifc_definition_id)
                # SEGMENTATION_ERROR
                # ifcopenshell.api.run("aggregate.unassign_object", file,
                #    **{"product": product, "relating_object":relating_object}
                #)
            # takes care of all representations
            # but no other relationships / object placement
            print("root.remove_product")
            # SEGMENTATION_ERROR
            # ifcopenshell.api.run("root.remove_product", file, **{"product": product})
            print("done")
            AggregateData.load(IfcStore.get_file(), element_id)
            VoidData.load(IfcStore.get_file(), element_id)
            IfcStore.unlink_element(product)
```

**Comment by Moult** [comment]
The crash is because you are doing:

```
ifcopenshell.api.run("void.remove_opening", file, **{"opening": product})
```

That line removes the opening (which is `product`). So when you then try to access the `product` variable again to remove the container, it doesn't exist, so it crashes.

Are you sure that `product` is the opening?

A better solution is to use this usecase:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/root/remove_product.py#L25

However as you can see by the TODO comment that I haven't yet gone around to removing other relationships.
