### ISSUE TITLE
blenderBIM ui still rely on object's names

### ISSUE THREAD

**Issue by s-leger** [IfcOpenShell/IfcOpenShell#1460]
While it is possible to create and export properly objects with dumb names, blenderbim ui still rely on ifcClass/name convention for eg re/assign class.
Is it a desired behaviour, or only temporary not working as expected ?

**Comment by Moult** [comment]
Correct the UI still relies on it. It is only temporary and will slowly be removed as native authoring matures. Is there something you'd like me to remove sooner rather than later?

In the future, there will be an option to use this method of scene organisation, or for the user to have their own.

**Comment by s-leger** [comment]
I guess editing class at least should be supported for predefined type, but will wait for full support and stick to proper naming in the meantime to prevent errors.

**Comment by Moult** [comment]
The UI in the majority of places now no longer has this restriction. So this can be closed. It was an expensive technical debt to pay, so let me know if I missed any spots :)
