### ISSUE TITLE
Compilation fails at IfcParseExamples.cpp

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1461]
This is with the current v0.6.0 branch (3f9e5ca), it was ok a week ago. The log is from arm64, but it fails also with x86_64:
 
    [ 54%] Linking CXX executable IfcParseExamples
    cd /builddir/build/BUILD/IfcOpenShell-0.6.0/cmake/aarch64-redhat-linux-gnu/examples && /usr/bin/cmake -E cmake_link_script CMakeFiles/IfcParseExamples.dir/link.txt --verbose=1
    /usr/bin/g++ -lxml2 -DNDEBUG -O3 -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -rdynamic CMakeFiles/IfcParseExamples.dir/IfcParseExamples.cpp.o -o IfcParseExamples  -Wl,-rpath,/builddir/build/BUILD/IfcOpenShell-0.6.0/cmake/aarch64-redhat-linux-gnu ../libIfcParse.so.0.6.0 -lboost_system -lboost_program_options -lboost_regex -lboost_thread -lpthread -lboost_date_time -lboost_chrono -lboost_atomic -lxml2
    /usr/bin/ld: CMakeFiles/IfcParseExamples.dir/IfcParseExamples.cpp.o: in function `Ifc2x3::IfcBuildingElement::list::ptr IfcParse::IfcFile::instances_by_type<Ifc2x3::IfcBuildingElement>()':
    IfcParseExamples.cpp:(.text._ZN8IfcParse7IfcFile17instances_by_typeIN6Ifc2x318IfcBuildingElementEEENT_4list3ptrEv[_ZN8IfcParse7IfcFile17instances_by_typeIN6Ifc2x318IfcBuildingElementEEENT_4list3ptrEv]+0x30): undefined reference to `IfcParse::IfcFile::instances_by_type(IfcParse::declaration const*)'
    /usr/bin/ld: IfcParseExamples.cpp:(.text._ZN8IfcParse7IfcFile17instances_by_typeIN6Ifc2x318IfcBuildingElementEEENT_4list3ptrEv[_ZN8IfcParse7IfcFile17instances_by_typeIN6Ifc2x318IfcBuildingElementEEENT_4list3ptrEv]+0xa0): undefined reference to `IfcEntityList::begin()'
    /usr/bin/ld: IfcParseExamples.cpp:(.text._ZN8IfcParse7IfcFile17instances_by_typeIN6Ifc2x318IfcBuildingElementEEENT_4list3ptrEv[_ZN8IfcParse7IfcFile17instances_by_typeIN6Ifc2x318IfcBuildingElementEEENT_4list3ptrEv]+0xbc): undefined reference to `IfcEntityList::end()'
    /usr/bin/ld: IfcParseExamples.cpp:(.text._ZN8IfcParse7IfcFile17instances_by_typeIN6Ifc2x318IfcBuildingElementEEENT_4list3ptrEv[_ZN8IfcParse7IfcFile17instances_by_typeIN6Ifc2x318IfcBuildingElementEEENT_4list3ptrEv]+0xf0): undefined reference to `IfcParse::declaration::is(IfcParse::declaration const&) const'
    /usr/bin/ld: CMakeFiles/IfcParseExamples.dir/IfcParseExamples.cpp.o: in function `main':
    IfcParseExamples.cpp:(.text.startup+0xbc): undefined reference to `Logger::SetOutput(std::ostream*, std::ostream*)'
    /usr/bin/ld: IfcParseExamples.cpp:(.text.startup+0x118): undefined reference to `IfcParse::IfcFile::IfcFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    /usr/bin/ld: IfcParseExamples.cpp:(.text.startup+0x1e0): undefined reference to `IfcEntityInstanceData::toString[abi:cxx11](bool) const'
    /usr/bin/ld: IfcParseExamples.cpp:(.text.startup+0x250): undefined reference to `IfcParse::declaration::is(IfcParse::declaration const&) const'
    /usr/bin/ld: IfcParseExamples.cpp:(.text.startup+0x290): undefined reference to `IfcParse::IfcFile::~IfcFile()'
    /usr/bin/ld: IfcParseExamples.cpp:(.text.startup+0x374): undefined reference to `IfcParse::IfcFile::~IfcFile()'
    /usr/bin/ld: IfcParseExamples.cpp:(.text.startup+0x3e0): undefined reference to `IfcParse::IfcFile::~IfcFile()'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `IfcEntityList::push(IfcUtil::IfcBaseClass*)'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `vtable for IfcParse::named_type'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `IfcEntityInstanceData::setArgument(unsigned int, Argument*, IfcUtil::ArgumentType)'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `vtable for IfcWrite::IfcWriteArgument'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `IfcWrite::IfcWriteArgument::set(boost::shared_ptr<IfcEntityListList> const&)'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `IfcEntityInstanceData::getArgument(unsigned int) const'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `IfcWrite::IfcWriteArgument::set(boost::shared_ptr<IfcEntityList> const&)'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `vtable for IfcEntityInstanceData'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `IfcEntityInstanceData::getInverse(IfcParse::declaration const*, int) const'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `IfcWrite::IfcWriteArgument::set(IfcUtil::IfcBaseClass* const&)'
    /usr/bin/ld: ../libIfcParse.so.0.6.0: undefined reference to `IfcParse::schema_definition::schema_definition(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<IfcParse::declaration const*, std::allocator<IfcParse::declaration const*> > const&, IfcParse::instance_factory*)'
    collect2: error: ld returned 1 exit status

**Comment by brunopostle** [comment]
Compilation is ok if I roll back to ce76d27

**Comment by aothms** [comment]
IfcParseExamples is also built on CI and it appears fine https://travis-ci.org/github/IfcOpenShell/IfcOpenShell/builds/770801486#L1121

It seems you have undefined references to everything, e.g IfcFile, IfcEntityList, ...

Do you have the complete build log? Did you try a make clean first?

**Comment by brunopostle** [comment]
I'm building in a fresh chroot each time, so the sources are clean.

This is a [successful build](https://download.copr.fedorainfracloud.org/results/bpostle/IfcOpenShell/fedora-34-x86_64/02182199-IfcOpenShell/builder-live.log.gz) with ce76d27

This is a [failed build](https://download.copr.fedorainfracloud.org/results/bpostle/IfcOpenShell/fedora-34-x86_64/02181960-IfcOpenShell/builder-live.log.gz) with 3f9e5ca

**Comment by aothms** [comment]
Thanks. It appears many files are missing from compilation (e.g IfcParse.cpp). It is related to this https://github.com/IfcOpenShell/IfcOpenShell/commit/34386ea27c80cf6e4a1589a891ba6a843b9ba4a6#diff-6857e85a31ef258bd57de3cd5fb1e0c31239cd93e0a16fba07dba83864bec5b6R580 something I just put in.

What is your cmake version?

**Comment by aothms** [comment]
Maybe it needs to be `NOT "${s}"` instead of just `NOT s`

**Comment by brunopostle** [comment]
I'm building for fedora 32, 33, 34 (and 35), so I see the same issue with cmake 3.17.4, 3.19.7 and 3.20.2

**Comment by aothms** [comment]
Ok, I think I figured it out, see commit, (contrary to e.g python) glob gave an absolute path, so the 0.6.0 in your path caused the exclusion of the files.

**Comment by brunopostle** [comment]
Yes, this seems to fix it: https://download.copr.fedorainfracloud.org/results/bpostle/IfcOpenShell/fedora-34-x86_64/02182477-IfcOpenShell/builder-live.log.gz
