### ISSUE TITLE
AttributeError: module 'ifcopenshell.util' has no attribute 'pset'

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1462]
I'm probably doing something wrong here, trying to add a pset to an object using the python api:

        entity = ifcopenshell.api.run(
            "root.create_entity",
            ifc,
            ifc_class="IfcSpace",
            name="My Space",
        )
        pset = ifcopenshell.api.run(
            "pset.add_pset", 
            ifc, 
            product=entity, 
            Name="Pset_SpaceCommon"
        )
        ifcopenshell.api.run(
            "pset.edit_pset", 
            ifc, 
            pset=pset, 
            properties={"IsExternal": True}
        )

This is the error:

      File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/__init__.py", line 10, in run
        return usecase_class(ifc_file, **settings).execute()
      File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/pset/edit_pset.py", line 13, in execute
        self.load_pset_template()
      File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/pset/edit_pset.py", line 24, in load_pset_template
        self.psetqto = ifcopenshell.util.pset.get_template("IFC4")
    AttributeError: module 'ifcopenshell.util' has no attribute 'pset'

**Comment by Moult** [comment]
Can you check you have the latest util module from the ifcopenshell python code master?

**Comment by brunopostle** [comment]
I get the same error with ce76d27

**Comment by Moult** [comment]
Maybe I need to `import ifcopenshell.util.pset` here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/pset/edit_pset.py#L1

**Comment by aothms** [comment]
Yes probably, that's the unfortunate thing about the global python module caching. If in your own script you have imported ifcopenshell.util.pset then it gets added to the global sys.modules dict and others that import simply ifcopenshell will inherit it?

**Comment by brunopostle** [comment]
Thanks, now it runs but I don't get the `IsExternal` property, so I must be doing something wrong:

<pre><font color="#33C7DE">#85</font>=<font color="#E9AD0C">IFCSPACE</font>(<font color="#C061CB">&apos;02jm2twNzElBmlmpEW0tq2&apos;</font>,<font color="#87FFAF">$</font>,<font color="#C061CB">&apos;My Space&apos;</font>,<font color="#87FFAF">$</font>,<font color="#87FFAF">$</font>,<font color="#33C7DE">#105</font>,<font color="#33C7DE">#100</font>,<font color="#87FFAF">$</font>,<font color="#87FFAF">$</font>,<font color="#87FFAF">$</font>,<font color="#87FFAF">$</font>);
<font color="#33C7DE">#86</font>=<font color="#E9AD0C">IFCPROPERTYSET</font>(<font color="#C061CB">&apos;0dj4qp9Ln9Zwp4Qs9D6tvN&apos;</font>,<font color="#87FFAF">$</font>,<font color="#C061CB">&apos;Pset_SpaceCommon&apos;</font>,<font color="#87FFAF">$</font>,());
<font color="#33C7DE">#87</font>=<font color="#E9AD0C">IFCRELDEFINESBYPROPERTIES</font>(<font color="#C061CB">&apos;0A2ofxSAbEYOtTUAPirtzJ&apos;</font>,<font color="#87FFAF">$</font>,<font color="#87FFAF">$</font>,<font color="#87FFAF">$</font>,(<font color="#33C7DE">#85</font>),<font color="#33C7DE">#86</font>);
</pre>

**Comment by Moult** [comment]
That's because I'm was too indecisive and never standardised on whether or not I should canonicalise usecase settings to be Pythonic or match the IFC capitalisation.

Short answer: you need `Properties` with a capital `P`.

Long answer: I need to sit down and standardise everything to prevent silly issues like this in the future. What are your preferences?

**Comment by brunopostle** [comment]
For me, since everything in the IFC spec namespace is capitalised, I would expect anything with a capitalised name to be a reserved word derived from the IFC docs, like "IsExternal". Lower case "properties" implies python API (but I only started learning python this year, so what do I know).

The API supports both in some cases, in my code above I'm using "Name" and "name", and it seems to work.

**Comment by aothms** [comment]
In C++ we have things like IfcParse and IfcGeom IfcGeomRepresentationItm
causing a lot of confusion on what comes from ifc and what are ifcopenshell
data structures. I plan to rectify this in 0.7. My preference: lowercase
all the things.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op wo 12 mei 2021 14:27 schreef Dion Moult ***@***.***>:

**Comment by Moult** [comment]
Sounds good, I will keep this issue open to remind me to standardise all kwargs to be "Pythonic". The only exceptions will be when you pass in a dict of attributes which you expect to translate directly to the IFC spec.
