### ISSUE TITLE
bcf.bcfxml

### ISSUE THREAD

**Issue by ekswathi** [IfcOpenShell/IfcOpenShell#1465]
Latest test builds not able to enable. The following error shows up 
 import bcf.bcfxml
ModuleNotFoundError: No module named 'bcf.bcfxml'

**Comment by Moult** [comment]
This is correct. It is in the process of being refactored. Ping @TestPrab

**Comment by TestPrab** [comment]
@ekswathi  Hey, I am working on that issue, will be resolved by today or tomorrow at max.
