### ISSUE TITLE
[IfcConvert] How to export entities from a ifc file by GuIDs?

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#1474]
I tried this command, but it did not work.
'''
IfcConvert.exe tmp.ifc test.glb --include=arg GlobalId "0Ssfy6$$D9jg7tqiq9cliF" --use-element-guids
'''
The GuID ("0Ssfy6$$D9jg7tqiq9cliF" ) is in the tmp.ifc.
The results I got show the following.
'''
PS D:\code\bimsc> D:\code\IfcConvert-v0.6.0-517b819-win64\IfcConvert.exe tmp.ifc test.glb --include=arg GlobalId "0Ssfy6$$D9jg7tqiq9cliF" --use-element-guids
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
Scanning file...
Done scanning file
Parsing input file took 2 seconds
'''

**Comment by aothms** [comment]
Is that the full output? It appears the process did not finish as it didn't print the message saying how many elements were emitted. What happens when you run the conversion without command line arguments. Or `IfcConvert.exe tmp.ifc test.glb -vv` for additional log output?

**Comment by CrossStyle** [comment]
@aothms, I think I know what's going on. I first used PowerShell to run this command. However, the PowerShell does not recognize the character "$$" and the results show the following.

````
PS D:\code\bimsc> D:\code\IfcConvert-v0.6.0-517b819-win64\IfcConvert.exe tmp.ifc test1.glb --include=arg GlobalId "0Ssfy6$$D9jg7tqiq9cliA" --use-element-guids -v
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
Scanning file...
Done scanning file
Parsing input file took 1 second

Log:
[Notice] exclude entities IfcOpeningElement IfcSpace
[Notice] include GlobalId values "0Ssfy6\.\.\/bimscD9jg7tqiq9cliA"
[Notice] No geometrical elements found or none succesfully converted
````
So, I ran the command using Command Prompt and it worked.
```
D:\code\bimsc>D:\code\IfcConvert-v0.6.0-517b819-win64\IfcConvert.exe tmp.ifc test1.glb --include=arg GlobalId 0Ssfy6$$D9jg7tqiq9cliA --use-element-guids -v
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
A file 'test1.glb' already exists. Overwrite the existing file?
y
Scanning file...
Done scanning file
Parsing input file took 2 seconds
Creating geometry...
Done creating geometry (1 objects)

Log:
[Notice] exclude entities IfcOpeningElement IfcSpace
[Notice] include GlobalId values "0Ssfy6\$\$D9jg7tqiq9cliA"


Conversion took 2 seconds
```
Finally, thank you for your help.
