### ISSUE TITLE
Brainstorming general solutions to the "undo" problem

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1475]
I have never designed an undo system before, so I just wanted to brainstorm if there were any "general" solutions which were able to save states prior to a change actioned by the IfcOpenShell Python API, and then optionally store it in an ordered list, and then restore that state if the user selects it.

Actions may be:

 1. Editing: element.Name = 'foo'
 2. Adding: ifc_file.create_entity("IfcFoo")
 3. Removal: ifc_file.remove(element)

Complex actions (remove_deep, copy_deep, etc) are basically just the three fundamental actions just repeated.

Naturally, the undo stack should store the final result of the element, such that if I do ifc_file.createIfcRootedFoo(ifcopenshell.guid.new(), ...) - the GlobalId does not change. Similarly, since STEP IDs are used to sync objects in the Blender client to the the IFC dataset, STEP IDs should be preserved.

Not an urgent issue to solve, but something I probably can't ignore forever :)

A naive suggestion would be that a flag can be set to start recording state changes. e.g. ifc_file.begin_transaction(). Then, the transaction consists of an ordered list. Each item in the list is either an "edit", an "add", or a "remove". The "edit" will store the element prior to the edit, the "add" will store the new element, and the remove will store the old element. Then, when all the operations are finished, state recording finishes e.g. undo = ifc_file.end_transaction(). This undo object can then call undo.restore() or something.

In theory this could be implemented in Python by wrapping all calls. This is however just my naive Wednesday morning idea of how undo systems work. I should probably do more research on it.

Thoughts?

Edit: Here's a TODO list to track undo support for operations.

 - [x] non-module operators (e.g. import / export) @moult
 - [x] aggregate @moult
 - [x] attribute @moult
 - [x] augin @moult
 - [ ] bcf
 - [x] bimtester @moult
 - [x] boundary @moult
 - [x] clash @moult
 - [x] classification @Jesusbill 
 - [x] cobie @moult
 - [x] constraint @Jesusbill 
 - [x] context @moult
 - [x] cost @myoualid 
 - [x] covetool @moult
 - [x] csv @Jesusbill 
 - [x] debug @moult
 - [x] diff @moult
 - [x] document @Jesusbill 
 - [x] drawing @moult
 - [x] geometry @moult
 - [x] georeference @moult
 - [x] group @moult
 - [x] layer @Jesusbill 
 - [x] material @moult
 - [x] model @moult
 - [x] owner @Jesusbill - TODO `attributes` special undo
 - [x] patch @Jesusbill 
 - [x] project @moult
 - [x] pset @moult
 - [x] pset_template @moult
 - [x] qto @moult
 - [x] resource @myoualid 
 - [x] root @moult
 - [x] search @Jesusbill
 - [x] sequence @myoualid 
 - [x] spatial @moult
 - [x] structural @Jesusbill 
 - [x] style @moult
 - [x] type @moult
 - [x] unit @moult
 - [x] void @moult

**Comment by htlcnn** [comment]
The idea of wrapping an action around a Transaction is somehow similar to Revit API. If that was implemented, parallel working would be considered to handle differently like the Central-Local model workflow in Revit.
I suggest there was an event system that monitor all actions, along with the transaction system. The result of each action like you described: add/modify/delete will be added to a database so that it can be undo later.
For adding: save new object's ID (I just heard every object in Blender has an RNA information)
For modifying: save the old value and new value
For deleting: deleting a property/value is just like modifying. Deleting an object: somehow serialize it and save the serialized information to database.
Undo system will start from scratch after saving, meaning that you can not undo after you save the file. That would help reduce memory I guess.
Just my two cents. Thanks!

**Comment by Moult** [comment]
@htlcnn yes, the jargon "transaction" was actually stolen from the Revit API. I haven't done research yet on what a more agnostic term would be.

Piping all API calls (i.e. IFC manip calls) through the IfcOpenShell API run() function now makes an event system possible. I've recently added some pre/post listener callbacks so that parametric editing is possible. So yes, this may certainly be a way to go :)

**Comment by CyrilWaechter** [comment]
> @htlcnn yes, the jargon "transaction" was actually stolen from the Revit API. I haven't done research yet on what a more agnostic term would be.

Transaction word is as far as I know a very agnostic term used a lot in database context. See [Transaction processing](https://en.wikipedia.org/wiki/Transaction_processing) on wikipedia.

I do not remember precisely how Blender handle this but I think @htlcnn is right about RNA stuff and it looks to work fantastically. In FreeCAD using transactions is very much optional which allows some fast computing stuff but leads in my opinion to very unpleasant behavior for common users. Not being able to undo everything is very frustrating for me and I assume many other users.

**Comment by aothms** [comment]
Don't laugh at me for this, but one way would be to serialize the file to disk. We can make this more efficient perhaps by some sort of logic to store only data that was changed, added or deleted before the last disk write. Perhaps some sort of threading so that we don't luck up the BlenderUI.

A proper implementation would require a lot of C++ work. Adding or deleting instances perhaps not so much, but being able to rollback changes in attribute values gives me nightmares.

**Comment by Moult** [comment]
@aothms actually I was also considering that! Even independent of "undo", an incremental write will make writes / saves much more efficient. When working on a 300mb file, the disk write operation still feels pretty long. So implementing an incremental write is... amazing.

For rolling back changes in attribute values does sound tricky. Maybe when implementing adding/deleting and incremental writing, it may inspire a solution for changing attributes? Maybe changing attributes may be as simple as a serialised string that is stored.

No rush in solving this right now - but good to keep the discussion :) Drawings, stable geometry and walls and basic IFC support comes first! :D

**Comment by aothms** [comment]
> rolling back changes in attribute values does sound tricky.

Well, maybe serializing to disk makes that also easier (my second paragraph was about implementing transactions purely in memory in C++). Because we can depend on the fact that parsed instances with duplicate ids are simply overwritten.

If we have a file now:

```
#1=IFCPERSON('Dion',$,$,$);
#1=IFCPERSON('Thomas',$,$,$);
```

Only Thomas will get stored.

So we for every instance in the file we should just store a flag that says whether it has been added or changed since the last write.

Deletion though... I'm not so sure about, but perhaps it isn't highest priority. Maybe unlinking them from the spatial tree is enough (although contrary to most viewers IfcOpenShell would still process them).

**Comment by Moult** [comment]
Unlinking from the spatial tree is not enough unfortunately since the BlenderBIM Add-on will still often consider these in certain scenarios. Admittedly some of these scenarios should be redesigned so this does not happen, but that is not the reality right now. For example, editing load groups may be done independently of linking them back to the project - the project link happens later in the workflow. Same for work calendars. A user may want to organise calendars, or reassign them from one work plan (i.e. the thing that gets declared to project) to another.

Another scenario is project libraries - officially IFC project library assets must be declared, but since nobody does project libraries, we cheat and just get a list by_type() of various assets we're looking for, including type products, materials, profiles, etc.

Do step files have comments? Can they be used for deletion?

**Comment by aothms** [comment]
They do have comments, but they're not stored or parsed. So that would actually be quite a bit of work.

I would say then can invent our own data section or something to signal deletions. Like:

(1)

  DATA;
  #1=IFCPERSON('Dion',$,$,$);
  #2=IFCPERSONANDORGANIZATION(#1,$,$);
  ENDSEC;

(2)

  DATA;
  #3=IFCPERSON('Thomas',$,$,$);
  #2=IFCPERSONANDORGANIZATION(#3,$,$);
  ENDSEC;
  DELETE;
  #1=IFCPERSON('Dion',$,$,$);
  ENDSEC;

So in transaction checkpoint (2) instead of overwriting the instance is deleted. It might work?

**Comment by aothms** [comment]
Where the name change would look like this instead, so the IfcPandO does not need to be re-emitted.

(1)

    DATA;
    #1=IFCPERSON('Dion',$,$,$);
    #2=IFCPERSONANDORGANIZATION(#1,$,$);
    ENDSEC;

(2)

    DATA;
    #1=IFCPERSON('Thomas',$,$,$);
    ENDSEC;

**Comment by Moult** [comment]
Yes, this makes sense! I assume, then, that over time, these extra data sections will build up in the file, and then we just need to "compress / apply" it to allow other IFC apps to consume it?

**Comment by aothms** [comment]
Exactly.

> Undo basically then just removes the previous data section.

Well, not remove, because you want to redo, but it would mean remove the current file obj from memory and open a new one reading all sections up to n-1. 

This would mean though that everything related to the file (instances etc.) would be invalidated. And the file need to be relinked to BlenderBIM. How much of an issue is that?

**Comment by Moult** [comment]
Well pressing undo in Blender would trigger this function as well as change the Blender step ID links, so I think it wouldn't be a big issue. Needs testing but not unsolvable.

**Comment by theoryshaw** [comment]
+1

**Comment by Jesusbill** [comment]
> Not an urgent issue to solve, but something I probably can't ignore forever :)

Starts to be a major issue to deal with in my eyes

**Comment by Moult** [comment]
I agree, unfortunately although I can work on the Blender side of this (grouping transactions, undo/redo event hooks), I suspect the guts of the solution is something within @aothms' realm. I think @aothms is a bit swamped right now, and I have no idea how difficult or easy this thing is.

**Comment by aothms** [comment]
Plus, we don't really know how scalable/usable the file-based serialization really is.

Maybe we also need to keep a more actual DB implementation on the table. Implementing transactions in IfcOpenShell C++ we can probably rule out. But perhaps there is some open source transactional key-value store that we can consider as an optional in-memory storage system for IfcOpenShell (that would be kind of what the open source bimserver has with BerkelyDB).

**Comment by Moult** [comment]
Not sure if I'm interpreting it correctly, but you're suggesting:

 1. IFC file is imported and translated into some form of NoSQL DB
 2. IfcOpenShell Python API no longer queries in-memory model, but instead queries NoSQL DB
 3. Write / edit functions from Python API can be within a transaction for the NoSQL DB
 4. Write function will then translate from NoSQL to STEP serialisation if required to produce IFC-SPF?

**Comment by aothms** [comment]
Almost, but except that it's a bit more hidden to the user. It's a just an alternative storage model for the IfcOpenShell file class (C++ IfcFile) so 2. is taken care of by the C++ code and the existing python/api code doesn't need to be touched.

**Comment by Moult** [comment]
Here's another really dumb approach, which will break pretty easily right now from this test script, but just to see if something like this approach is feasible.

Basically, here I'm doing it explicitly in Python, but in C++, I assume this could happen hidden to user upon calls to create_entity, remove, and setattr(inst, x, y). Right now I also have an id offset hack because I can't control the IDs from Python I believe, and I'm not serialising attributes that refer to instances (so now it'll likely just crash).

But perhaps this is an easier approach than creating a new storage model which sounds like a ton of work. Basically there would be an ordered list of transactions which you can move your way through via individual transaction's undo() and redo() functions.

Thoughts?

```
import ifcopenshell


class Transaction:
    def __init__(self, ifc_file):
        self.file = ifc_file
        self.operations = []
        self.id_offset = 0

    def store_create(self, element):
        self.operations.append({'action': 'create', 'id': element.id(), 'type': element.is_a()})

    def store_edit(self, element, attribute, value):
        self.operations.append({'action': 'edit', 'id': element.id(), 'attribute': attribute, 'old': getattr(element, attribute), 'new': value})

    def store_delete(self, element):
        self.operations.append({'action': 'delete', 'value': element.get_info()})

    def undo(self):
        for operation in self.operations[::-1]:
            if operation['action'] == 'create':
                element = self.file.by_id(operation['id'] + self.id_offset)
                element.GlobalId = 'x' # hack, otherwise ifcopenshell gets upset
                self.file.remove(element)
            elif operation['action'] == 'edit':
                element = self.file.by_id(operation['id'])
                setattr(element, operation['attribute'], operation['old'])
            elif operation['action'] == 'delete':
                e = self.file.create_entity(operation['value']['type'])
                self.id_offset += 1
                for k, v in operation['value'].items():
                    try:
                        setattr(e, k, v)
                    except:
                        pass

    def redo(self):
        for operation in self.operations:
            if operation['action'] == 'create':
                x = self.file.create_entity(operation['type'])
                self.id_offset += 1
            elif operation['action'] == 'edit':
                element = self.file.by_id(operation['id'] + self.id_offset)
                setattr(element, operation['attribute'], operation['new'])
            elif operation['action'] == 'delete':
                element = self.file.by_id(operation['value']['id'] + self.id_offset)
                self.file.remove(element)


f = ifcopenshell.file()
transaction = Transaction(f)
wall = f.createIfcWall()
transaction.store_create(wall)
print('01')
print(f.wrapped_data.to_string())
transaction.undo()
print('02')
print(f.wrapped_data.to_string())
transaction.redo()
print('03')
print(f.wrapped_data.to_string())

f = ifcopenshell.file()
wall = f.createIfcWall()
transaction = Transaction(f)
transaction.store_edit(wall, 'Name', 'foo')
wall.Name = 'foo'
print('04')
print(f.wrapped_data.to_string())
transaction.undo()
print('05')
print(f.wrapped_data.to_string())
transaction.redo()
print('06')
print(f.wrapped_data.to_string())

f = ifcopenshell.file()
wall = f.createIfcWall()
wall.GlobalId = ifcopenshell.guid.new()
transaction = Transaction(f)
transaction.store_delete(wall)
f.remove(wall)
print('07')
print(f.wrapped_data.to_string())
transaction.undo()
print('08')
print(f.wrapped_data.to_string())
transaction.redo()
print('09')
print(f.wrapped_data.to_string())
```

**Comment by aothms** [comment]
> I'd have to wrap all calls though which isn't fun.

I'm thinking. Basically the only calls that have to be wrapped are:

- entity_instance.__setattr__
- file.create_entity / file.__getattr__ (which maps to create_entity)
- file.remove

One thing we could do is:

- subclass file and entity_instance to transactioned_file and transactioned_entity_instance
- transactioned_file basically embeds your Transaction class above
- transactioned_file make sure it always returns transactioned_entity_instance instances instead of regular entity_instance (you can see that file already decorates everything it returns with entity_instance e.g [0], so it wouldn't be a lot of work, we just need to make configurable which class it uses to decorate the return values

[0] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/file.py#L142

One other thing: if it helps I'm quite sure we can provide a low-level function to reset the internal file id counter. That way maybe you don't need to mess with this self.id_offset?

**Comment by Moult** [comment]
Agreed, there are only a few calls that need to be wrapped.

I assume the benefit of subclassing into a transactioned_file is so that only crazy people like us who are doing native authoring incur the overhead of recording transactions? If so, why subclass? Why not just do a begin_transaction and end_transaction which needs to be created anyway? So if you don't begin a transaction, you don't incur the overhead.

And yes, I believe with a low-level function to manipulate the internal file id counter (either set manually, or recalculate), I can recode this to be a bit more robust, as well as extend it to handle more complex scenarios like attributes that reference instances, or inverse references.

Do you think there is anything fundamentally wrong with this approach? The approach seems pretty basic, which maybe is a good thing? I cannot immediately spot any scaling issues as well but performance / optimisation is not my strength. It's basically the same operation, just in reverse, or repeating, and I guess you need to store the data in memory but that's just how all undos work anyway I assume.

**Comment by aothms** [comment]
subclassing might be necessary because you cannot end up in the situation where you have regular entity_instance instances and transactioned_entity_instance. So at creation of the file you need to have this setup correctly.

I think performance might be pretty bad at first similarly to how we had to create this remove_batched()

> either set manually, or recalculate

That I can slide in anytime. Which do you prefer?

**Comment by Moult** [comment]
Recalculate probably leaves less room for error. Maybe put it in and see what it makes the code look like.

How might performance be improved? The only way I can think of is batching it, e.g. if the user knows he creates an entity and setattrs 10 times, it gets grouped into a single remove call on undo and a single create_entity() call on redo? Is there a speed boost in implementing this in C++ (it can be certainly prototyped in Python first)?

**Comment by aothms** [comment]
> How might performance be improved?

Let's see how it goes. I'm mostly concerned about the updates to inverse attributes. 

Btw. have you prototyped how this works with setting attributes with entity instance references?

Ok, I've sneaked a quick commit in:

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>>
>>> f.createIfcCartesianPoint((0.,0.))
#1=IfcCartesianPoint((0.,0.))
>>> f.remove(f[1])
>>>
>>> f.createIfcCartesianPoint((0.,0.))
#2=IfcCartesianPoint((0.,0.))
>>> f.remove(f[2])
>>>
>>> f.wrapped_data.recalculate_id_counter()
>>>
>>> f.createIfcCartesianPoint((0.,0.))
#1=IfcCartesianPoint((0.,0.))
>>>
```

I'll trigger a new build

**Comment by Moult** [comment]
Nah I haven't prototyped any further than what I posted here - I'll continue the experimental code once the new build is up and we can see how complex it gets with inverse attributes :)

Fingers are crossed!

**Comment by Moult** [comment]
I've just created https://github.com/IfcOpenShell/IfcOpenShell/pull/1539 to see how this would work. I didn't end up subclassing, as it didn't seem to be necessary, but perhaps I missed something.

The updated code now handles instance attributes and inverses, as well as a history.

I realised that the entity_instance doesn't have access to the file object. The history is stored on the file object, so I had to store it in a hacky way.

It also doesn't work if an element is removed that isn't the latest ID. E.g. if I have element 1, 2, and 3, and I remove 2, then when I undo, it'll recreate it as 4. I think a much better solution is to somehow have something like `create_entity("IfcFoo", id=2, ...)`. Is that possible? Then `recalculate_id_counter()` will no longer be necessary. I haven't done much battle testing since this latest ID restriction prevents any more complex usages.

Here is a sample script which uses the new undo/redo feature:

```
import ifcopenshell

def debug(f, message):
    print('>>> ' + message)
    for e in f:
        print(e)

f = ifcopenshell.file()
f.begin_transaction()
owner = f.createIfcOwnerHistory()
wall = f.createIfcWall('asdf', owner)
slab = f.createIfcSlab('asdf2', owner)
f.remove(slab)
owner.State = 'LOCKED'
f.end_transaction()
debug(f, 'Original')

f.undo()
debug(f, 'Undo')

f.redo()
debug(f, 'Redo')

new_owner = f.createIfcOwnerHistory()
wall = f.by_id(2)
wall.OwnerHistory = new_owner

f.begin_transaction()
f.remove(new_owner)
f.end_transaction()
debug(f, 'Original 2')

f.undo()
debug(f, 'Undo 2')

f.redo()
debug(f, 'Redo 2')
```

And the output with debug prints:

```
>>> Original
#2=IfcWall('asdf',#1,$,$,$,$,$,$,$)
#1=IfcOwnerHistory($,$,.LOCKED.,$,$,$,$,$)
UNDOING OPERATION {'action': 'edit', 'id': 1, 'index': 2, 'old': None, 'new': 'LOCKED'}
UNDOING OPERATION {'action': 'delete', 'inverses': {}, 'value': {'id': 3, 'type': 'IfcSlab', 'GlobalId': 'asdf2', 'OwnerHistory': {'type': 'single', 'id': 1}, 'Name': None, 'Description': None, 'ObjectType': None, 'ObjectPlacement': None, 'Representation': None, 'Tag': None, 'PredefinedType': None}}
UNDOING OPERATION {'action': 'create', 'value': {'id': 3, 'type': 'IfcSlab', 'GlobalId': 'asdf2', 'OwnerHistory': {'type': 'single', 'id': 1}, 'Name': None, 'Description': None, 'ObjectType': None, 'ObjectPlacement': None, 'Representation': None, 'Tag': None, 'PredefinedType': None}}
UNDOING OPERATION {'action': 'create', 'value': {'id': 2, 'type': 'IfcWall', 'GlobalId': 'asdf', 'OwnerHistory': {'type': 'single', 'id': 1}, 'Name': None, 'Description': None, 'ObjectType': None, 'ObjectPlacement': None, 'Representation': None, 'Tag': None, 'PredefinedType': None}}
UNDOING OPERATION {'action': 'create', 'value': {'id': 1, 'type': 'IfcOwnerHistory', 'OwningUser': None, 'OwningApplication': None, 'State': None, 'ChangeAction': None, 'LastModifiedDate': None, 'LastModifyingUser': None, 'LastModifyingApplication': None, 'CreationDate': None}}
>>> Undo
>>> Redo
#2=IfcWall('asdf',#1,$,$,$,$,$,$,$)
#1=IfcOwnerHistory($,$,.LOCKED.,$,$,$,$,$)
>>> Original 2
#2=IfcWall('asdf',$,$,$,$,$,$,$,$)
#1=IfcOwnerHistory($,$,.LOCKED.,$,$,$,$,$)
UNDOING OPERATION {'action': 'delete', 'inverses': {2: [(1, 'single')]}, 'value': {'id': 3, 'type': 'IfcOwnerHistory', 'OwningUser': None, 'OwningApplication': None, 'State': None, 'ChangeAction': None, 'LastModifiedDate': None, 'LastModifyingUser': None, 'LastModifyingApplication': None, 'CreationDate': None}}
>>> Undo 2
#3=IfcOwnerHistory($,$,$,$,$,$,$,$)
#2=IfcWall('asdf',#3,$,$,$,$,$,$,$)
#1=IfcOwnerHistory($,$,.LOCKED.,$,$,$,$,$)
>>> Redo 2
#2=IfcWall('asdf',$,$,$,$,$,$,$,$)
#1=IfcOwnerHistory($,$,.LOCKED.,$,$,$,$,$)
``

**Comment by Moult** [comment]
For scalability, in the BlenderBIM Add-on, very few actions are actually done in bulk since we are natively authoring. So I think the only issues would be in undoing things like batched remove.

**Comment by Moult** [comment]
Ah two more things I noticed which may or may not be important. Firstly:

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> w = f.createIfcWall()
>>> f.remove(w)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dion/tmp/transactiontest/ifcopenshell/file.py", line 321, in remove
    return self.wrapped_data.remove(inst.wrapped_data)
  File "/home/dion/tmp/transactiontest/ifcopenshell/ifcopenshell_wrapper.py", line 1557, in remove
    return _ifcopenshell_wrapper.file_remove(self, entity)
RuntimeError: Invalid cast
```

To fix this I have to always specify a GlobalId. Not a big issue, as we can avoid it very easily.

Secondly, this try except here: https://github.com/IfcOpenShell/IfcOpenShell/pull/1539/files#diff-7bb9f4f41edc728931a8a084e39411fc704d910a650230895371323feee9bca4R93-R96 is probably super inefficient, but is necessary in case the element they are undoing has borked data (e.g. a required attribute is set to None). Perhaps we can simply say that anybody relying on undo/redo must have valid data. Alternatively, maybe there is something less expensive than try/catch.

**Comment by aothms** [comment]
> is probably super inefficient

Is it? I kind of foresaw this one, as it's really a bit assymetric in the IfcOpenShell API, that you construct invalid data, but later no longer modify to be invalid data.

> To fix this I have to always specify a GlobalId. Not a big issue, as we can avoid it very easily.

Hm yes, let me fix that here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcParse.cpp#L1903 It's also a bit assymetric as during parsing we do skip over this issue, but throw an exception when deleting.

> Also, setattr misses calls like element[0] = 'foo', but I don't really mind that actually :)

Yeah I personally use these kind of things sometimes for arbitrarily accessing relationships, where the attribute names are different but the order is consistent.

**Comment by Moult** [comment]
> Yeah I personally use these kind of things sometimes for arbitrarily accessing relationships, where the attribute names are different but the order is consistent.

Yes, typically quantities, but not a big deal I reckon.

What are the chances of a `create_entity(id=N, ...)`? I think that's the thing I need to proceed with testing this on more real life applications.

**Comment by aothms** [comment]
> What are the chances of a create_entity(id=N, ...)? I think that's the thing I need to proceed with testing this on more real life applications.

I think it's relatively overseeable, but we might want to consider a mapping of id -> id anyway as it is in the end probably more useful in the scenario of collaborative synchronous editing. But I'll try to get to it soon regardless.

**Comment by Moult** [comment]
Awesome! I'll hold off any further testing until then because it's a bit impractical right now :) I didn't quite understand what you meant by mapping of id -> id but that's OK :)

Can't wait!

**Comment by aothms** [comment]
I mean that without the dependency on fixed ids, but instead some mapping to automatically renumber like you had earlier, it might mean that we can also merge transactions.

**Comment by Moult** [comment]
From very initial tests for implementing undo within Blender, it seems to work pretty smoothly. I believe (may be wrong) that any performance concerns lie in storing undo state for many operations, with an extra penalty for remove operations since it needs to check for inverse attributes.

So a good way to stress test it is on performing many operations in a single transaction, undoing them, then redoing them. So with a monkey subdivided 3 levels, it gives about 31,500 polygons. This results in 62,413 stored IfcOpenShell operations (create / edit / delete) to add its shape representation in the `geometry.add_representation` API usecase. Results:

 - Vanilla (un-transactioned, no undo/redo capability) operation: 2.9s
 - Transactioned operation: 5.3s
 - Undoing: 5s
 - Redoing: 4.5s

This is pretty acceptable performance, I reckon. Yes, it is a 80% time increase to transact the operation, but in reality:

 1. If you're creating meshes with 31,500 polygons in your BIM model, it's probably unnecessary 99% of the time.
 2. If it is necessary, 5.3s isn't the end of the world.
 3. This penalty only occurs on a transactioned operation. The way the BlenderBIM Add-on works is that it actually _doesn't_ do expensive operations like representation item updating on the fly, instead, it does it on file save. So if the first time it takes you 5.3s to create a big mesh, subsequent edits will only occur on file save/export, which will be untransactioned, and will take the vanilla 2.9s.

**Comment by Moult** [comment]
Here's a TODO list to track undo support for operations.

 - [ ] aggregate
 - [ ] attribute
 - [ ] augin
 - [ ] bcf
 - [ ] bimtester
 - [ ] boundary
 - [ ] bsdd
 - [ ] clash
 - [ ] classification
 - [ ] cobie
 - [ ] constraint
 - [ ] context
 - [ ] cost
 - [ ] covetool
 - [ ] csv
 - [ ] debug
 - [ ] diff
 - [ ] document
 - [ ] drawing
 - [ ] geometry
 - [ ] georeference
 - [ ] group
 - [ ] layer
 - [ ] material
 - [ ] model
 - [ ] owner
 - [ ] parametric
 - [ ] patch
 - [x] project
 - [ ] pset
 - [ ] pset_template
 - [ ] qto
 - [ ] resource
 - [ ] root
 - [ ] search
 - [ ] sequence
 - [ ] spatial
 - [ ] structural
 - [ ] style
 - [ ] type
 - [ ] unit
 - [ ] void

**Comment by Moult** [comment]
Whoops I did "squash and merge" which probably wasn't a smart move, but for the record https://github.com/IfcOpenShell/IfcOpenShell/commit/6b0a58db7dec353dbf931aee7add92e3d97ef77e is the commit to look at and the only ifcopenshell-python files that were touched were file.py and entity_instance.py. The rest of Blender / BlenderBIM Add-on stuff.

**Comment by Jesusbill** [comment]
Will start with structural on my end

**Comment by Moult** [comment]
Just a heads up @myoualid @Jesusbill that one issue you might need to look out for in particular (since I've just run into it) is when entity attributes are set via index. E.g. `element[0] = 'foo'`. This happens here and there. If this happens, you need to manually store the edit in the transaction.

E.g. before:

```
element.GlobalId = 'foo' # hooray! it is tracked!
element[0] = 'foo' # not tracked
```

... after ...

```
element.GlobalId = 'foo' # hooray! it is tracked!
if element.wrapped_data.file.transaction:
    element.wrapped_data.file.transaction.store_edit(element, 0, 'foo') # manually track it!
element[0] = 'foo' # yay, it is tracked now
```

**Comment by aothms** [comment]
In the end `__setattr__()` calls `__setitem__()` so ideally the transaction logic is moved to that function. https://github.com/IfcOpenShell/IfcOpenShell/blob/8a917dc050276320840f53299511b04a11ba9772/src/ifcopenshell-python/ifcopenshell/entity_instance.py#L123

Is there a reason why the `store_edit()` call isn't in `__setitem__()`. It has access to the same index, value pair.

**Comment by Moult** [comment]
Ah yes, good point! I'll look at fixing it so that it works.

By the way @aothms I'm running into problems with batch and unbatch for remove_deep undos / redos. I suspect because the batching does something with the get_inverse function. Here's a minimal example, do you think you can look at it and see if there is a solution?

```python
import ifcopenshell

f = ifcopenshell.file()
a = f.createIfcIndexedPolygonalFace((1,2,3))
b = f.createIfcIndexedPolygonalFace((4,5,6))
c = f.createIfcPolygonalFaceSet()
c[2] = (a, b)

f.begin_transaction()
f.batch()
print(f.get_inverse(b))
f.remove(b)
print(f.get_inverse(a))
f.remove(a)
f.remove(c)
f.unbatch()
f.end_transaction()

f.undo()
f.redo()
```

**Comment by Moult** [comment]
@aothms at a crude guess, perhaps batch() could trigger an is_batched flag, and then the store remove would batch the get inverse call too. Is that sufficient? I haven't tested it, and I don't know what other magic batch invokes, so this is just a guess at a potential solution.

**Comment by Moult** [comment]
I created a preliminary implementation to support batched uh, removes, I guess (haven't tested how batching affects other operations). It seems to work in my tests, but I don't have a strong understanding of how batching work under the hood, so let me know if you spot anything funky.

**Comment by Moult** [comment]
The BCF module is put on hold for undo support, because undo redo support is not built in the underlying BCF lib for either BCF-XML or BCF-API.

Implementing undo for BCF XML requires a bit of work, but now is probably not the best time given the work by @TestPrab , and also because there is no support for v3 in the GUI, and implementing consistent support for undo redo in BCF-API need a good long hard think (do we batch API calls? Do we call the API on each undo and redo? Urgh)

**Comment by Moult** [comment]
I'm super happy to close this issue and want to thank @aothms @Jesusbill and @myoualid for making this a reality :D 

I'm amazed at how fast we were able to pull this together, and it is making Native IFC authoring so much more of a pleasure. I'm sure there are things we missed, which of course BCF is one of the known ones. But perfect is the enemy of the good, and I'm sure we'll continue to refine and catch things as time goes on!

Cheers everyone!
