### ISSUE TITLE
Issue with Double door Single Swing ifc door

### ISSUE THREAD

**Issue by greeshmaunni1990** [IfcOpenShell/IfcOpenShell#1477]
Hi I am working on an ifc file and I am trying to create maneuvering boxes for the doors. Some doors are single panel  and some doors are double panel. What I am trying to achieve here is to create two separate boxes for the double panel doors. In order to do that I want to check on which direction the door panel is  swinging and I could not achieve this. If anyone could give some hints it would be helpful. Thank you

**Comment by aothms** [comment]
It all depends on how much information you have available which is not very consistent for doors and windows.

E.g do you have this https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcarchitecturedomain/lexical/ifcdoorpanelproperties.htm ?

How is the geometry modelled? Is it multiple representation items? Or even a decomposition into parts?

**Comment by greeshmaunni1990** [comment]
Hi,
I am new to ifc concept. I used the attribute PanelPosition from IfcDoorPanelProperties which is returning NOTDEFINED. Is that supposed to be like that?    
The model is decomposed into parts
Thank you

**Comment by aothms** [comment]
> Is that supposed to be like that?

Well, it can be like that.

>  The model is decomposed into parts

That surely helps. 

Did you look at this: https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcsharedbldgelements/lexical/ifcdoortypeoperationenum.htm Take special note to the positive Y-axis for the opening direction, but I'm tbh not entirely sure how this is handled in case of decompositions into parts

**Comment by greeshmaunni1990** [comment]
Hi 
I had been through this link. They are saying we can determine the direction of swing at Ifcdoor or IfcDoorStandardCase. for Double door Single Swing. But I am getting an error when I used ifcdoor.OperationType. Also is it possible to determine the swing using Pset_DoorPanelSwingning?

**Comment by aothms** [comment]
> But I am getting an error when I used ifcdoor.OperationType.

It's an optional attribute

> Also is it possible to determine the swing using Pset_DoorPanelSwingning?

I've never heard of that.

These are the predefined property sets https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifckernel/lexical/ifcpredefinedpropertyset.htm

The standardized propertysets for IfcDoor are here under "Property Sets for Objects" https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcsharedbldgelements/lexical/ifcdoor.htm

**Comment by Moult** [comment]
Isn't the direction the door swing is local +Y?

**Comment by greeshmaunni1990** [comment]
@Moult hi I have read that the position is in +y axis. But I dont know how to implement that for double door single swing

**Comment by aothms** [comment]
@greeshmaunni1990 in my experience it works best if you describe the problems you're facing as precise as possible and list the things you have tried that failed. "I don't know how to..." is very open ended and likely will not get better answers then already given here.

**Comment by greeshmaunni1990** [comment]
@aothms I am trying to create maneuvering boxes for all doors in my model as I have mentioned. It is all done for Single doors. But when it comes for double door I have to find which Side of the door is in Swinging and create the box accordingly. I have used the attribute PanelPosition in IfcDoorPanelProperties acording to this:
https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcsharedbldgelements/lexical/ifcdoorpanelproperties.htm but it was returning NOT DEFINED. My objective is to identify which door panel is opening to the left and which to the right

**Comment by Moult** [comment]
@greeshmaunni1990 do you already have panels? If so, the one with a smaller local x swings left towards positive y, and the one with a larger local x swings right towards positive y.

**Comment by greeshmaunni1990** [comment]
@Moult Thank you. I will check into it
