### ISSUE TITLE
sverchok not getting by GUID

### ISSUE THREAD

**Issue by nortikin** [IfcOpenShell/IfcOpenShell#1479]
here is json for import:
https://gist.github.com/0ea4e52dfa5ba86c8964bd7042827696
add your ifc file and check - it not getting GUID of wall
![image](https://user-images.githubusercontent.com/5783432/119181879-e115a280-ba7a-11eb-9cd6-38f5c30d3652.png)
exec:
```python
append(str(V1[0])[-39:-3])
```

**Comment by aothms** [comment]
The guid shown on the right is not according to IFC's base64 encoded format, which is probably what the By Guid node expects assuming it simply mimics ifcopenshell.file.by_guid(). 

My guess from `str(V1[0])[-39:-3])` is that you're somehow getting another attribute that contains an actual hexadecimal formatted guid (some tools do that) in probably the Tag attribute.

Does it work if you use `V1[0].GlobalId` for the exec statement? That would be the typical way to get the guid, the first attribute of the element.

**Comment by nortikin** [comment]
> Does it work if you use `V1[0].GlobalId` for the exec statement? 
`append([V1[0][0].GlobalId])` works. extra level needed

`append([i.GlobalId for i in V1[0]])` at the end

**Comment by aothms** [comment]
Wonderful.

IFC can be a strange beast modelled on top of rather ancient standards (but amazing it exists nonetheless). If you have any questions let us know.

**Comment by nortikin** [comment]
@aothms yes, question - is there breaf example for IFcsverchok to embed to examples menu  of sverchok?

**Comment by aothms** [comment]
I hope @Moult can get back to you with something. He's the main author of ifc sverchok.

**Comment by Moult** [comment]
Sorry for the late reply. I'm a bit hesitant of investing more time into IfcSverchok until either I get a bit more spare time, or someone who is a visual node guru wants to work on it with me. Right now, the nodes implemented are really the bare minimum nodes - and higher level abstracted nodes are required to do anything useful - so right now it's more of a toy than a tool.

My intention is that the IfcOpenShell API can be autogenerated into IfcSverchok nodes, which would instantly give hundreds of high-level nodes for users.

**Comment by nortikin** [comment]
> My intention is that the IfcOpenShell API can be autogenerated into IfcSverchok nodes, which would instantly give hundreds of high-level nodes for users.

great idea!

**Comment by nortikin** [comment]
@Moult where is API in plain format?

**Comment by nortikin** [comment]
@Moult i see it as for example Wall node with extended props panel containing flags for hidden sockets that will be displayed as flagged.
 for example, x,y,z dimentions, construction, material, baseline direction etc.

**Comment by Moult** [comment]
@nortikin IfcOpenShell API code is here: https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcopenshell-python/ifcopenshell/api

The problem is right now settings are passed via expanded kwargs (e.g. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/project/create_file.py#L6) - this means that it is harder to write code that automatically detects node inputs.

Node inputs is an IFC file object, plus zero or more settings, depending on the API usecase.

All API usecases can be run using the run function of the API. E.g. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/project/create_file.py can be called with https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/module/project/operator.py#L19-L21

So calling API is already standardised, but kwargs is hard to detect, so ... I need to clean up kwargs, maybe add some docstrings or type hints to make it easier.

**Comment by Moult** [comment]
Maybe a single "IfcOpenShell API" node is all that is needed actually - no need to generate hundreds of nodes (each file in that API dir could in theory be a node). The user can type the name of the API call as the first node input, the IFC file as the second node input, and then another input for a list of setting names to pass into, then all additional inputs must correspond to the list of settings.

Perhaps it is easier than I thought.

**Comment by Moult** [comment]
Ideally though it is still pretty close to "programming". For visual scripting to truly be beneficial, someone with visual scripting experience needs to write some helper functions and automatic casting especially for geometry vectors so that they can be easily used with nodes.

**Comment by aothms** [comment]
> Maybe a single "IfcOpenShell API" node is all that is needed actually 

Not so sure about that, it would make discoverability and type safety pretty hard. But granted, I'm not a visual programming user much.

Things like mypy apparently also aren't really good with `*args` and `**kwargs`.

But I think this hints at an underlying problem of the API, we will run into this also when generating documentation and porting the API to other languages, etc.

**Comment by Moult** [comment]
Yeah the single node is just to "get it working" to experiment, and later on I think it needs to be tailored more for visual programming. Perhaps only some api calls are auto generated, etc, others are combined or wrapped in helpers or higher level things. Dunno. Need a  node guru and maybe to get some inspiration from geometry gym.

But yes it is a fundamental problem I need to solve. Explicit kwargs and type hints and docstrings should go a long way. I'll get around to it...

**Comment by Moult** [comment]
For those interested, we had our first meeting to start bringing API nodes, and you can follow the discussion here too https://community.osarch.org/discussion/606/sverchok-ifc-nodes-create-ifcwall#latest

**Comment by luzpaz** [comment]
Any more traction on this. This feature seems like a game changer, especially if we can get https://github.com/nortikin/sverchok/pull/3674 merged

**Comment by nortikin** [comment]
> Any more traction on this? This feature seems like a game changer, especially if we can get [nortikin/sverchok#3674](https://github.com/nortikin/sverchok/pull/3674) merged

merged

**Comment by Moult** [comment]
No further progress on the IfcSverchok nodes, though there is a potential GSoC entry here: https://wiki.osarch.org/index.php?title=User:Mdjska
