### ISSUE TITLE
IfcConvert crash when encountering IfcDirection(0.,0.,0.)

### ISSUE THREAD

**Issue by farialima** [IfcOpenShell/IfcOpenShell#148]
An IFC with this line:
`#685062=IFCDIRECTION((0.,0.,0.));`

will cause IfcConvert to crash with this error:
`Done scanning file`
`terminate called after throwing an instance of 'Standard_ConstructionError'`

This is of course not a valid direction, but we have encountered in files (file created by `The EXPRESS Data Manager Version 5.02.0100.07`). 

In our case, the invalid IfcDirection was only used as 3rd argument to an IfcAxis2Placement3D  ( RefDirection ), which is optional; so just removing it would have made it possible to just skip it.

In anycase, I guess it should not crash

**Comment by aothms** [comment]
Thanks. Most exceptions are caught, but not during the initial scanning of placements to approximate a model bounding box. Fixed now.
