### ISSUE TITLE
Are derived attributes supported?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1485]
I'm not sure if "derived attributes" is the right terminology, but an example of one is the "TotalThickness" attribute thing that an IfcMaterialLayerSet has.

**Comment by aothms** [comment]
> I'm not sure if "derived attributes" is the right terminology

It is

> supported?

It isn't.

Any logic from the express schema is currently unsupported. I think it's the case for most implementations.

**Comment by Moult** [comment]
Cheers :) Closing issue, good to have it on the tracker for future searches!
