### ISSUE TITLE
BlenderBIM: an 'undo' (redo) does not export in an IFC file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1487]
As you'll see in the following video, an 'undo' of a deleted object, does not export out properly in an IFC file...

video:https://www.dropbox.com/s/9kbdg5tveqbr5zn/2021-05-25_23-08-04.mp4?dl=0

**Comment by theoryshaw** [comment]
Whoops, just read [this](https://github.com/IfcOpenShell/IfcOpenShell/issues/1475) issue.  Seems these issues are related. 

I'm kinda noticing that 'undo' seems to break a lot of stuff relative to IFC export.

**Comment by Moult** [comment]
Yes basically pressing undo / redo can cause all sorts of funky broken sync issues right now, all related to #1475. Once solved (which needs to happen sooner rather than later), these problems should all go away and result in a much more stable user experience.

**Comment by Jesusbill** [comment]
Just a note that I have, too, faced the consequences of using undo with BlenderBIM, losing in some cases the connection to the ifc file. My solution for now is to work incrementally staging the blend and ifc files in git, so that I can go back if I face any issues during export

**Comment by theoryshaw** [comment]
Thanks for reporting. 
Unfortunately for me, this is somewhat of a showstopper for me authoring in BlenderBIM. I run into too many syncing errors due to undo-ing. 
I guess i undo a lot! :)

**Comment by Jesusbill** [comment]
It is only natural that you need to undo when authoring, it does seem like a prime feature to deal with as soon as possible.
Could a bounty funding be a way to go here?

**Comment by theoryshaw** [comment]
> Could a bounty funding be a way to go here?
if you start one,  i'll add to it!.. and spread the word.

**Comment by Moult** [comment]
Not sure if bounty is worth it for this one, but once the fundamentals are in place, it's a bit of a tedious task to go through every. single. operator. in. each. module... so uh, @Jesusbill and @myoualid both of you are very welcome to join in on this fun when the time comes.

Closing this issue to reduce the conversation happening from 3 places to 2 places: https://github.com/IfcOpenShell/IfcOpenShell/issues/1475 and https://github.com/IfcOpenShell/IfcOpenShell/pull/1539

**Comment by Jesusbill** [comment]
@Moult sounds great, let me know when the time comes and I'll be more than happy to do some low-level tedious tasks
