### ISSUE TITLE
Geometry conversion fails for some IfcPolygonalFaceSet, IfcExtrudedAreaSolid, IfcExtrudedAreaSolid, IfcRevolvedAreaSolid

### ISSUE THREAD

**Issue by hlg** [IfcOpenShell/IfcOpenShell#1490]
This IFC file contains a couple of `IfcDuctFitting`, `IfcDuctSegment`, and `IfcPipeFitting` that fail to be converted to BREP: [tzb_ifc4.zip](https://github.com/opensourceBIM/BIMsurfer/files/4091172/tzb_ifc4.zip). The issue was reported with the IfcGeomServer (https://github.com/opensourceBIM/BIMserver/issues/1100), but also appears with IfcConvert for example.

There are 28 products currently failing, with representation items of types `IfcPolygonalFaceSet`, `IfcExtrudedAreaSolid`, `IfcExtrudedAreaSolid`, `IfcRevolvedAreaSolid`. A number of the `IfcExtrudedAreaSolids` have invalid extrusion depth of 0. For the `IfcPolygonalFaceSets`, the sewing seems to fail in some cases.

Could you have a look at these geometries?

**Comment by aothms** [comment]
> For the IfcPolygonalFaceSets, the sewing seems to fail in some cases.

Just a quick note that this has recently been completely reworked. https://github.com/IfcOpenShell/IfcOpenShell/commit/cf68cf6f5c380fdfcbd93371c42fab466f31c7ca#diff-b63441256aea2fa75200fcb5529a16eb2c64299b1881c08b4ac13775f510437f

**Comment by hlg** [comment]
I checked again all remaining issues and found that have geometry with either IfcCircleHollowProfileDef.WallThickness or IfcExtrudedAreaSolid.Depth of zero, while according to the schema, both attributes should be of type IfcPositveLengthMeasure, hence greater than zero. I would be happy to close this as I would not expect IfcOpenShell to change the behaviour.

**Comment by aothms** [comment]
@hlg now in v0.8 it's easier to define settings that propagate easily to the geometry handling routines. We used to have some settings called "permissive extrusions" that allowed extrusions depths of 0 (result is face) and negative (result is an extrusion in opposite direction). Previously this was a compile time setting. We can now more easily bring these back as settings that users can set at runtime.

In general we might need to review the IfcGeomServer setting module. In the protocol we have something to set settings, but it's based on integers from an enum, but the settings names in IfcOpenShell are no longer an enum.
