### ISSUE TITLE
BlenderBIM: annotation is positioned off the geometry

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1503]
This might be known already, but just logging. 

video: https://www.dropbox.com/s/7v8g0j0e7mhhwg8/2021-05-28_21-57-19.mp4?dl=0
![image](https://user-images.githubusercontent.com/507113/120056154-1df41300-c000-11eb-8703-8a44d63fa4eb.png)

**Comment by Moult** [comment]
So I believe this should be fixed now :)

**Comment by theoryshaw** [comment]
ha... not even going to test! :)
Excited about the latest 2d stuff!
