### ISSUE TITLE
ModuleNotFoundError: No module named 'ifcopenshell.api'

### ISSUE THREAD

**Issue by wassimj** [IfcOpenShell/IfcOpenShell#1505]
I installed a fresh copy of the latest BlenderBIM add-on build for Windows (version (0, 0, 210517))
When I try to activate it in Blender 2.92, I get the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\__init__.py", line 23, in <module>
    from .bim import *
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\__init__.py", line 9, in <module>
    from . import handler, ui, prop, operator, gizmos
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\handler.py", line 4, in <module>
    import ifcopenshell.api.owner.settings
ModuleNotFoundError: No module named 'ifcopenshell.api'
```
What am I missing? Does it need an additional separate installation of ifcopenshell? I have ifcopenshell-python-37-v0.6.0-517b819-win64 installed in an anaconda virtual environment and I load it for an experimental method in Topologic. Is it conflicting? Thanks.

**Comment by wassimj** [comment]
If I remove Topologic (and thus its loading of ifcopenshell) and re-start, then BlenderBIM loads correctly. Sadly, Topologic stops loading if BlenderBIM is loaded.

**Comment by Moult** [comment]
The api namespace is pure Python so you can just download it from github. Perhaps the anaconda build you're on doesn't have it.

BTW why does topologic conflict with the blenderbim addon? The new blenderbim add-on builds no longer require occ at all.

**Comment by wassimj** [comment]
Will try. Regarding Topologic not loading, I am at my wit’s end. I don’t know enough about the environment to figure it out. I would be happy to jump on a zoom session to show you the error. Perhaps it is a trivial issue that I am not aware of.

**Comment by Moult** [comment]
Let's try a screen share and see if we can get it working. In theory I don't see a problem. Send me an invite sometime during Sydney waking hours at dion@thinkmoult.com

**Comment by Moult** [comment]
@wassimj I noticed you popped into the chat once or twice but left within a minute or so. I think you need to stay much longer (e.g. wait at least an hour), as well as ping myself (mention my username Moult) and that'll help me realise you're online.

**Comment by wassimj** [comment]
Oh sorry about that. I am not familiar with that chat program (plus I am using it through a web browser.. I think it times out?)

**Comment by Moult** [comment]
If it is tricky to catch me online, would you prefer to setup a more traditional meeting date and time with a video call link?

**Comment by Moult** [comment]
Sorry for the delay, I've booked Sydney tomorrow monday 7pm :) See you then!

**Comment by wassimj** [comment]
Thanks. See you tomorrow


________________________________

**Comment by Moult** [comment]
Closing bug as now resolved and both add-ons coexist happily!

**Comment by prav8000** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\__init__.py", line 23, in <module>
    from .bim import *
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\__init__.py", line 9, in <module>
    from . import handler, ui, prop, operator, gizmos
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\handler.py", line 4, in <module>
    import ifcopenshell.api.owner.settings
ModuleNotFoundError: No module named 'ifcopenshell.api'



I get the same error . Past couple of weeks wasted so much time to install this add on .  Could you please let us know this add on works with  Blender 2.93.4 ?   and paste clear installation instructions here . Thanks in advance

**Comment by Moult** [comment]
@prav8000 https://blenderbim.org/install-blenderbim.html are the official stable install instructions. If you still have issues, please post your error message, or alternatively you can join in on the OSArch live chat and do a screenshare session.

**Comment by wassimj** [comment]
> Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable mod = **import**(module_name) File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim__init__.py", line 23, in from .bim import * File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim__init__.py", line 9, in from . import handler, ui, prop, operator, gizmos File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blenderbim\bim\handler.py", line 4, in import ifcopenshell.api.owner.settings ModuleNotFoundError: No module named 'ifcopenshell.api'
> 
> I get the same error . Past couple of weeks wasted so much time to install this add on . Could you please let us know this add on works with Blender 2.93.4 ? and paste clear installation instructions here . Thanks in advance

I am wondering why my name is in the files that were not found? Are you trying to install Topologic? If so, please contact me privately. The installation is not trivial and the software is still in beta. There must have been some badly written hardwired link.

**Comment by aothms** [comment]
@wassimj I think @prav8000 just copied your test  from the first post of this issue.

**Comment by wassimj** [comment]
@aothms oh sorry! ok then.

**Comment by BelyaevaDaria** [comment]
Good afternoon. I have the same error:
ModuleNotFoundError: No module named 'ifcopenshell.api.pset.data'
Please tell me how to fix.

**Comment by Moult** [comment]
@BelyaevaDaria how did you trigger that error? That is very old code which has been deleted. Have you followed https://blenderbim.org/install-blenderbim.html  ?

**Comment by BelyaevaDaria** [comment]
Good afternoon. I can't open your application - "page not found".
I need to load the missing ifc parameters in the ifc file, and all ifc parameters from cvs have values. I found BlenderBim and ifcopenshell tools. Learned that BlenderBim has a private custom pset. However, in python, I can't help but notice. Tell me, please, where to get up-to-date information and the correct code to solve your problem.

**Comment by Moult** [comment]
Apologies for the wrong link, yes the link you used is correct. I don't understand your question, what missing IFC parameters? What CSV? Not sure what private custom pset you're referring to.
