### ISSUE TITLE
BlenderBIM: Cannot install addon in Blender 2.93

### ISSUE THREAD

**Issue by RadityaRaksi** [IfcOpenShell/IfcOpenShell#1509]
Cannot install it in Blender 2.93. [I've] tried some builds to install with, still don't work.

**Comment by MatthewBoynton** [comment]
I have just had the same problem.
![image](https://user-images.githubusercontent.com/44595738/120567377-f6180b80-c454-11eb-8619-883f1ff1697b.png)

**Comment by Moult** [comment]
If you are on Blender 2.93, the build from the website is not yet ready for it - it only works on Blender 2.92 and less. I will do another stable release soon which will address this.

For now you can download an experimental developer build from https://github.com/IfcOpenShell/IfcOpenShell/releases - choose your operating system and make sure it says "py39" in the name.

**Comment by arcdipesh** [comment]
blenderbim-210306 python-39 version works actually.

![image](https://user-images.githubusercontent.com/50439654/120578263-3d969b80-c445-11eb-9894-1656f82b78cc.png)

**Comment by Moult** [comment]
@arcdipesh I'd recommend not using that build and instead one from the releases page here https://github.com/IfcOpenShell/IfcOpenShell/releases - that build is quite old :) Don't worry, there will be a new stable release soon!

**Comment by MatthewBoynton** [comment]
Thankyou. I tried the 210602 py37 and it didn't work but then saw there was a 210602 py39. That works :)

**Comment by johninvirtual** [comment]
**Blender 2.93 uses python-3.9** . So install bim-xxxxxx-py39 version as @MatthewBoynton suggested

**Comment by Moult** [comment]
Closing issue, as latest stable release v0.0.210605 now ships for Blender 2.93 and up. For those still on Blender 2.92 and below, the developer builds on Github will still build the py37 version for a while.
