### ISSUE TITLE
BlenderBIM: weird extrusions when trying to edit mesh

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1510]
When [this](https://www.dropbox.com/s/oyw143lnuwlzym5/20210603%20-%20Extrusion%20Problem.ifc?dl=0) file is imported into BlenderBIM, it does wacky stuff like the following...

video: https://www.dropbox.com/s/6em4z2w56j384xk/2021-06-03_21-39-13.mp4?dl=0

**Comment by Moult** [comment]
Seems as though the new dumb slab feature was trying to be too clever! Whoops!
