### ISSUE TITLE
BlenderBIM: wall split tool is a little wonky.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1512]
Per the video below, split tool seems inconsistent. 
file [here](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/aeef95daac1dcb0fd7fae62eec44fba4a1005559/Random_Tests/Wall_Types/from_Blender)

video: https://www.dropbox.com/s/e0qcbsgqv0yehmw/2021-06-05_08-23-07.mp4?dl=0

**Comment by Moult** [comment]
Ah perhaps I should mention the split wall tool uses the 3D cursor to decide where to split. You can change the 3D cursor by pressing shift-RMB. It can snap and stuff to midpoints too. Just move it roughly (no need to be exact) and it'll split based on it.
