### ISSUE TITLE
Allow customisable generated element names

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#1514]
The new version of the BLENDERBIM addon is simply impressive.
Would it be possible to link the names of the instances to their type.
For example, an IfcWallType = Generic 200mm would generate new walls named: IfcWall/Generic 200mm.001, IfcWall/Generic 200mm.002, ..., IfcWall/Generic 200mm.abc
Thank you guys!

**Comment by Moult** [comment]
Although technically feasible (and pretty easy to do so), this is a bit of an interesting one.

Logically, the Name attribute is used for a primary identifier, such as if you coded it in a schedule. So for example, in a window schedule, you would have W01, W02, W03 as instances of windows, and this annotation will be labeled on paper documentation, and will be shown in a column in a window schedule table, and so the text "W01" and so on will be in the "Name" field.

Therefore for walls, the majority of walls (to be semantically accurate) actually do _not_ have a Name i.e. the Name field is NULL. There are some exceptions, such as Precast Panel walls where you do want to itemise the walls, but for most standard blockwork, in-situ concrete, or partition walls, they are not itemised, so the name field should be blank.

Duplicating the type name in another field may be considered poor structured data practice. For humans in the UI, it makes us feel happy to see the names, but for computers, it's not quite "correct".

What do you reckon?

**Comment by vuicBABS** [comment]
We think it's unfortunate not to use the name field systematically to help identify the different elements.

If we increase the amount of information, it will help even more to find more quickly the information. For example, let's imagine that we have 100 walls and we have to apply a treatment on a part of the elements with a special insulation.
If the walls to be treated are called:
- IfcWall/Wall.009
- IfcWall/Wall.034
- IfcWall/Wall.078

Now if we use the information in the elementType that these elements have some insulations, it is more easy to find them if they are called:
- IfcWall/Wall-Insulation120mm.002
- IfcWall/Wall-Insulation120mm.005
- IfcWall/Wall-Insulation120mm.011

The blenderbim addon systematically assigns a name to elements. We propose to increase this level of detail. And why to make a difference between windows, wall, slab or air filter?

Of course it's only our point of view and we respect the decision of the community if you think in another way.

**Comment by Moult** [comment]
I guess if you wanted to isolate all walls of a particular type, you'd just use the select by type feature shown below - does that help?

![image](https://user-images.githubusercontent.com/88302/121141756-ab482a80-c87e-11eb-886e-7c5fdd664543.png)

**Comment by vuicBABS** [comment]
There is always a way to find the solution. In our project we will continue to give a more specific name to our element. We didn't find better than the IfcElementType with an index. But it's ok. We can live with it.

**Comment by Moult** [comment]
I will keep this issue open, since default naming is a useful feature. The user should have the option to choose how they want things to be named by default, following naming patterns and schemes. Changing the default will only make some users happy, but not others. This will allow users to customise it to their needs. When I have created this feature, I will update this bug :) It is a great suggestion!

**Comment by vuicBABS** [comment]
Dion, you are the best (and I mean it sincerely)!

**Comment by Moult** [comment]
I apologise for the delay in resolving this, but at last we can close the bug :)
