### ISSUE TITLE
After reopening blender file, no more connexion with IFC

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#1515]
Hi,

After reopening a blender file, the different elements are no longer recognized as IFC elements. The authoring tool is empty and does not allow me to add new elements based on my ElementTypes.

Do I have to export the .ifc file before leaving the BLENDER file?

Thank you.

PS. I'm using blender28-bim-210609-py39-win

**Comment by Moult** [comment]
Yes, you need to export the IFC file. All the data is only stored in the IFC file, the Blender file is merely a saved preloaded "view" of the IFC, which may view all, none, or some of the geometrical elements.

**Comment by vuicBABS** [comment]
Ok! I'll do it again. It's so quick with blender and the addon that it's not a problem.

**Comment by vuicBABS** [comment]
I've done a part of the model one again and I always have an issue.
before leaving I go in the file menu and export to .ifc.
But the ifc file is not updated. 
what is the right sequence to do?

**Comment by Moult** [comment]
Can we screenshare?

**Comment by vuicBABS** [comment]
Of course. I send you my coordinates on linkedin

**Comment by vuicBABS** [comment]
Sorry for the post. I found my mistake. The elements were not in the right space container. Now everything is alright. One more time the problem was between the screen and the chair back...

**Comment by Moult** [comment]
Ah sorry for not responding - I was caught up in another call. Glad it got resolved!
