### ISSUE TITLE
build IfcOpenShell to dll

### ISSUE THREAD

**Issue by wizztjh** [IfcOpenShell/IfcOpenShell#152]
I am thinking of building a dll for Unity.

https://msdn.microsoft.com/en-us/library/a90k134d.aspx

I am doing some research on this. Is it possible to do it? What function that you think should be accessible by dll?

I might send a pull request when I am done. I don't see any contruibution guide. Anything that I should take note of?

**Comment by aothms** [comment]
There have recently been PRs to export symbols for the `IfcParse` and `IfcGeom` libraries: #76 #115 Are you talking about the introduction a more general "libIfcConvert" or "libIfcOpenShell"? I would welcome that, but perhaps for interfacing with Unity `IfcParse` and `IfcGeom` are sufficient?

There are coding conventions [1], but not rigorously followed, as we are awaiting the refactoring planned for the subsequent release.

[1] https://github.com/IfcOpenShell/IfcOpenShell/wiki/Coding-Conventions

**Comment by Stinkfist0** [comment]
The easiest way to access a native DLL from C# is to have a pure C API for the DLL. IfcOpenShell doesn't have such at the moment. Alternative way is to use C++/CLI, but I have no experience in that.

**Comment by aothms** [comment]
@wizztjh any updates?

**Comment by wizztjh** [comment]
@aothms I tried a few times but failed. No update from me. Created a Revit plugin to pull information instead.

**Comment by aothms** [comment]
@wizztjh ok, good to hear then you got sth else working
