### ISSUE TITLE
How to split a ifc file?

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#1520]
I can get the geometry with this code, but I lose the material. Is there a correct way to do this?

```
import ifcopenshell
if __name__ == '__main__':
    ifc_file = r"D:\code\ifc_file\20210219Architecture.ifc"
    ifc = ifcopenshell.open(ifc_file)
    products = ifc.by_type("IfcProduct")
    project = ifc.by_type('IfcProject')
    site = ifc.by_type('IfcSite')
    building = ifc.by_type('IfcBuilding')
    storey = ifc.by_type('IfcBuildingStorey')
    for floor in range(len(storey)):
        new = ifcopenshell.file(schema=ifc.schema)
        seg = storey[floor]
        new.add(project[0])
        new.add(site[0])
        new.add(building[0])
        new.add(seg)
        for item in seg.ContainsElements[0].RelatedElements:
            new.add(item)
        new.write("storey/%s.ifc" % floor)
```

**Comment by CyrilWaechter** [comment]
Hello,

You have examples in ifcpatch recipes: https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcpatch/ifcpatch/recipes.
You apparently try to split your IFC by building storey. There is already an ifcpatch recipe for this: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcpatch/ifcpatch/recipes/SplitByBuildingStorey.py

**Comment by CrossStyle** [comment]
@CyrilWaechter 

Many thanks. It solved my problem.
