### ISSUE TITLE
[BlenderBIM] Material Psets not read from IfcProjectLibrary

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#1522]
# Steps to reproduce
1. Create an IfcProjectLibrary
2. Create an IfcWallType
3. Create an IfcMaterial with Psets info like density, thermal conductivity etc…
4. Create an IfcMaterialLayerSet with material from step 3 as only layer
5. Export
6. From a new blender file create an IfcProject
7. Open IFC Project Library
8. Append library element IfcWallType from step 2
9. Assign material to default cube and check psets -> No Psets

# Example file
Example file containing an IfcProjectLibrary: [example_v103.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6641956/example_v103.ifc.zip)

**Comment by Moult** [comment]
Just a note on the approach I took - I did try a more generic "let's traverse all inverse relationships" approach, but although it works well for project libraries, the fact is that right now, project libraries are very rare, and I want the solution to work for appending assets from regular IfcProjects too (yes, you can just load any random IFC file and use it as a library). As a result, I am using a "whitelist" approach to approve relationships that we want to follow. There are likely going to be quite a few more that we need that we will discover, so keep me posted if you find any. There are also those we want to _not_ follow, like we probably don't want to append the presentation layer system or IFC groups.
