### ISSUE TITLE
How to extract the external entities of the building?

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#1523]
Hello,

Is there an existing method to extract the exterior entities of a [building](https://github.com/CrossStyle/BIM-Viewer/blob/main/local_app/house.ifc), such as facades, windows, doors and roofs, etc.? I can extract some of the entities with the following code, but it doesn't work well.

```
import OCC.Core.Bnd
import OCC.Core.BRepBndLib
import OCC.Core.BRep
import OCC.Core.BRepPrimAPI
import ifcopenshell
import ifcopenshell.geom
import numpy as np

settings = ifcopenshell.geom.settings()
settings.set(settings.USE_PYTHON_OPENCASCADE, True)
settings.set(settings.USE_WORLD_COORDS, True)
ifc_file = ifcopenshell.open(r"D:\code\ifc_file\house.ifc")
products = ifc_file.by_type("IfcProduct")
outputShape = []
for product in products:
    if product.is_a("IfcOpeningElement"):
        continue
    if product.Representation:
        try:
            shape = ifcopenshell.geom.create_shape(settings, product).geometry
            tmpDict = dict()
            tmpDict['shape'] = shape
        except:
            continue
        tmpDict['entity'] = product
        bbox = OCC.Core.Bnd.Bnd_Box()
        OCC.Core.BRepBndLib.brepbndlib_Add(shape, bbox)
        bounding_box_center = ifcopenshell.geom.utils.get_bounding_box_center(bbox)
        tmpDict['coord'] = [bounding_box_center.X(), bounding_box_center.Y(), bounding_box_center.Z()]
        print("Bounding box center: %.2f %.2f %.2f" % (
            bounding_box_center.X(),
            bounding_box_center.Y(),
            bounding_box_center.Z()))
        outputShape.append(tmpDict)

occ_display = ifcopenshell.geom.utils.initialize_display()
entityDict = dict()
shapeDict = dict()
coordArray = np.zeros((len(outputShape), 3))
for idx in range(len(outputShape)):
    entityDict[outputShape[idx]['entity'].GlobalId] = outputShape[idx]['entity']
    shapeDict[outputShape[idx]['entity'].GlobalId] = outputShape[idx]['shape']
    coordArray[idx] = outputShape[idx]['coord']

minX, maxX = min(coordArray[:, 0]), max(coordArray[:, 0])
minY, maxY = min(coordArray[:, 1]), max(coordArray[:, 1])
minZ, maxZ = min(coordArray[:, 2]), max(coordArray[:, 2])
for idx in range(len(outputShape)):
    coord = outputShape[idx]['coord']
    inX = coord[0] + 0.2 >= maxX or coord[0] - 0.2 <= minX
    inY = coord[1] + 0.2 >= maxY or coord[1] - 0.2 <= minY
    inZ = coord[2] + 0.2 >= maxZ or coord[2] - 0.2 <= minZ
    if inX or inY or inZ:
        shape = outputShape[idx]['shape']
        ifcopenshell.geom.utils.display_shape(shape)
occ_display.FitAll()
ifcopenshell.geom.utils.main_loop()
```
The results I got.
![externalEntities](https://user-images.githubusercontent.com/43562257/121794066-df816980-cc37-11eb-9311-722fef713af0.PNG)
The house as it was.
![house](https://user-images.githubusercontent.com/43562257/121794098-35561180-cc38-11eb-8588-52d3f90939ea.PNG)

**Comment by aothms** [comment]
If you're into some experimenting and like a geometric approach, I think currently the best bet is to use https://github.com/opensourceBIM/voxelization_toolkit. 

You have to create a script, something like:

```
file = parse("fzk_haus.ifc")
surfaces = create_geometry(file)
voxels = voxelize(surfaces)
external = exterior(voxels)
shell = offset(external)
export_ifc(file, shell, surfaces, "exterior.ifc")
```

and then execute that with voxec

**Comment by CrossStyle** [comment]
@aothms I am not familiar with C++, is there a user guide for this library?

**Comment by aothms** [comment]
You can probably use it without touching C++ and use the language of which I showed an example above. voxec is the interpreter for that language. But more importantly, no, there isn't any documentation, there will be at some point, but we simply don't have the resources for it now.

**Comment by CrossStyle** [comment]
@aothms Hello, I am having a problem running the code you provided.

![image](https://user-images.githubusercontent.com/43562257/122157150-ec52c700-ce9c-11eb-981c-39e0631f73cc.png)
```
# code in a.txt
file = parse("duplex.ifc")
surfaces = create_geometry(file)
voxels = voxelize(surfaces)
external = exterior(voxels)
shell = offset(external)
export_ifc(file, shell, surfaces, "exterior.ifc")
```

**Comment by aothms** [comment]
Ok, I guess you're having a slightly older version of the code. It doesn't matter a lot. Just replace with

```
file = parse("duplex.ifc")
surfaces = create_geometry(file)
voxels = voxelize(surfaces)
external = exterior(voxels)
shell = offset(external)
x = export_ifc(file, shell, surfaces, "exterior.ifc")
```

**Comment by CrossStyle** [comment]
@aothms I have changed the code but the problem is still not solved. The voxec I used is v0.2.3.
![image](https://user-images.githubusercontent.com/43562257/122177180-f33b0300-ceb7-11eb-9a33-d8e30e5a3417.png)

**Comment by aothms** [comment]
your file needs to end in exactly one newline.

when you `cat`, the next line starting with `(base)` needs to come right below the last line of the file `x = export_ifc...`

**Comment by aothms** [comment]
also, I'm a bit worried about those quotes, it has to be exactly `0x22` ascii. 

![afbeelding](https://user-images.githubusercontent.com/1096535/122180689-f1a61680-ce88-11eb-8471-5eb6292a262e.png)

https://en.wikipedia.org/wiki/ASCII

**Comment by CrossStyle** [comment]
@aothms I used a line-break to end the file and it worked. Many thanks!

**Comment by CrossStyle** [comment]
@aothms BTW, Is there a function or method that can extract the interior entities?

**Comment by aothms** [comment]
Maybe something like 

```
interior=invert(exterior)
interior2=subtract(interior, shell)
export_ifc(..., interior2, ...)
```

didn't test
