### ISSUE TITLE
BlenderBim - Project library - Material are not imported

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#1525]
I've just tried the project library. I'm sure it's very nice tool but for that time it doesn't import the material with the elements.

**Comment by Moult** [comment]
I think this was fixed here: https://github.com/IfcOpenShell/IfcOpenShell/commit/feac60134039b50ae8a71e61b21cc6f7dd518fdc have you tried the daily releases?

**Comment by vuicBABS** [comment]
It's crazy!
