### ISSUE TITLE
IfcConvert svg: tessellation of svg arcs or curves?

### ISSUE THREAD

**Issue by fbpyr** [IfcOpenShell/IfcOpenShell#1527]
@aothms  : When creating svg space plans, is there a way/option I may have missed (or is already planned to support (?)), to tessellate the arcs or curves of the svg path into simple segmented/tessellated lines?

**Comment by aothms** [comment]
--svg-write-poly

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcconvert/IfcConvert.cpp#L395

Use the latest build available here https://github.com/IfcOpenBot/IfcOpenShell/commit/81ad6894782e91c7e007bcae16347f35f36b084b#comments

**Comment by fbpyr** [comment]
Fantastic!! 🎉 ☺️ 
Again: Thank you so much!! 🙂
