### ISSUE TITLE
Batched remove seems to fail on this file

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1531]
Sample code to reproduce:

```
import ifcopenshell
import ifcopenshell.util.element
f = ifcopenshell.open('/home/dion/drive/bim/purgetest.ifc')
e = f.by_id(4801)
ifcopenshell.util.element.remove_deep(f, e)
```

I've sent the purgetest.ifc file to models@ifcopenshell.org :)

**Comment by Moult** [comment]
Bump - any ideas?

**Comment by Moult** [comment]
I just sent another file to models@ifcopenshell.org to replicate this, with this code:

```
ifcopenshell.util.element.remove_deep(f, f.by_id(128761))
```

I seem to notice that the unbatch() function fails if during the remove deep, something is removed that has an inverse element that was also removed in the remove deep loop. I don't really understand why, though.

I've checked to make sure that this is unrelated to transactions.

**Comment by aothms** [comment]
I think it's fixed, I'll start a new build

**Comment by Moult** [comment]
Awesome thanks! I'll test when the build is up and let you know how it goes!

**Comment by Moult** [comment]
Tested and confirmed that new build indeed fixes it! Thanks so much!
