### ISSUE TITLE
ifc export blank

### ISSUE THREAD

**Issue by tatenda-b** [IfcOpenShell/IfcOpenShell#1532]
first export was successful with one ifc building storey; i then added a second building storey element named first floor and re-exported the ifc file. The file now opens with no 3D information in ifc viewers. Could not find a way to revert the changes  whatever i do with the model now it always shows a blank ifc file. 

![ifcerror1](https://user-images.githubusercontent.com/46367854/122731070-365ff200-d27b-11eb-9b3c-89d5477a1a87.PNG)
![ifcerror2](https://user-images.githubusercontent.com/46367854/122731086-395ae280-d27b-11eb-8061-fce24de9cc95.PNG)

**Comment by Moult** [comment]
It looks like your walls objects are not in the building storey collection. Try taking your objects out of the structure/walls collections and move it into the IfcBuildingStorey/X collections instead.
