### ISSUE TITLE
Can't install Blenderbim addon 

### ISSUE THREAD

**Issue by bigotes423** [IfcOpenShell/IfcOpenShell#1535]
After downloading the latest verision of Archipack I am no longer allowed to download and flag the latest version of Belenderbim ![image](https://user-images.githubusercontent.com/68729427/122985789-e0846a80-d39e-11eb-9ddd-24aed006becb.png)

**Comment by Moult** [comment]
The latest version of the BlenderBIM Add-on requires Blender 2.93 and above. If you are still under 2.93, you can download a py37-win release from here: https://github.com/IfcOpenShell/IfcOpenShell/releases
