### ISSUE TITLE
BlenderBIM - IfcBuilding not correctly exported for more than one building

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#1536]
Hi,
Something goes wrong when I make a project with more than one IfcBuilding in a same file.
I've tried 2 things:
- IfcBuilding has the geometry of the building
- An IfcBuilding collection with a IfcBuildingProxy for the geometry of the building

both solution export a reduced building (building in Ifc file is about 5 time smaller).

you can see on the first imagewhat I would expect (3 buildings) and the result after exporting in the second image (viewer = bimvision).

![20210623 - 3 Buildings in blender](https://user-images.githubusercontent.com/40517234/123090835-e6269280-d428-11eb-87fb-821119849c5a.PNG)
![20210623 - 3 Buildings in bimVision](https://user-images.githubusercontent.com/40517234/123090847-e9218300-d428-11eb-837f-2f0529870d43.PNG)

**Comment by vuicBABS** [comment]
I've just tried to join all the 3 objects in one. I created 1 Ifcbuilding. I assigned a BuildingProxyElement class an this object I created and put it under the IfcBuilding.
And when I open the ifc file in bimvision I have the same problem. I ask me if there is some problem when the geometry of the element is complex.

**Comment by Moult** [comment]
I need more information to solve this one, like perhaps a test file, or a screenshare. Would you be available for a screenshare? I'm in the Sydney timezone. You can catch me online on the OSArch live chat.

**Comment by vuicBABS** [comment]
Ok, I'll try the chat tomorrow (I'm on the other side of the planet).
I found some strange stuff.

I made a model with 3 parts. Each part should be the enveloppe of a building. the enveloppes are modeled using faces. I merged all the nodes together. Enveloppes have no thickness. I have a separate model with all the details. Theses 3 parts are just there to give an information of the neighborhood.

All the buildings are inside an only IfcBuilding element and I assigned them an IfcFurniture class (just to make a test).

I see that the 2 buildings (furnitureelement) on the side have no own geometry and I don't know why. And the box of the part in the middle has not the right proportions.
![20210624-HasOwnGeometry](https://user-images.githubusercontent.com/40517234/123237984-6d820d80-d4de-11eb-906f-982085eacbf4.PNG)
![20210624-HasOwnGeometry-2](https://user-images.githubusercontent.com/40517234/123238606-e5e8ce80-d4de-11eb-9fae-db5c5728dea6.PNG)

In Blender, under IFC Representation, the building in the middle has informations for box and body and the 2 other have only information for box.
![20210624-IFC Representations1](https://user-images.githubusercontent.com/40517234/123238852-20eb0200-d4df-11eb-8077-59dcc164c019.PNG)

![20210624-IFC Representations](https://user-images.githubusercontent.com/40517234/123238038-770b7580-d4de-11eb-9de9-2f7244e3abeb.PNG)

I give you the model in attachment:
[20210624-Buildings-D.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6707969/20210624-Buildings-D.zip)

**Comment by vuicBABS** [comment]
Today I created the model again. And that time it works. I have no idea why. The model is easier with less point thant the first one. 
![20210625-Capture](https://user-images.githubusercontent.com/40517234/123393085-0c217380-d59e-11eb-9927-2bf3718136e3.PNG)


if you are interesting with the model...
thank you one again for this amazing addon. It's really more than just an addon. It's a revolution.
[20210625-Buildings.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6714618/20210625-Buildings.zip)
