### ISSUE TITLE
IfcDerivedProfileDef results in no geometry

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1540]
Hi, I'm trying to use `IfcDerivedProfileDef` with an `IfcArbitraryClosedProfileDef`, but I get no geometry even if I set the `IfcCartesianTransformationOperator2D` to no transform.

This is the error (with IfcOpenShell compiled from git today):

    $ IfcConvert _test.ifc _test.dae
    IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.5.0)
    Scanning file...
    Done scanning file   
    Parsing input file took 0 seconds
    Log:
    [Error] {22_N5GUz5A8REoM6XXNcwZ} Error in: TopoDS::Face
    Failed to convert:
    #81=IfcSurfaceCurveSweptAreaSolid(#80,#68,#74,0.,1.,#75)
    [Error] {22_N5GUz5A8REoM6XXNcwZ} Error in: TopoDS::Face
    Failed to convert:
    #87=IfcSurfaceCurveSweptAreaSolid(#86,#68,#74,0.,1.,#75)
    [Error] {22_N5GUz5A8REoM6XXNcwZ} Error in: TopoDS::Face
    Failed to convert:
    #93=IfcSurfaceCurveSweptAreaSolid(#92,#68,#74,0.,1.,#75)
    [Error] {15Q_hcoYnFbuXvcLZCMit3} Error in: TopoDS::Face
    Failed to convert:
    #175=IfcSurfaceCurveSweptAreaSolid(#174,#163,#168,0.,1.,#169)
    [Error] {15Q_hcoYnFbuXvcLZCMit3} Error in: TopoDS::Face
    Failed to convert:
    #181=IfcSurfaceCurveSweptAreaSolid(#180,#163,#168,0.,1.,#169)
    [Error] {15Q_hcoYnFbuXvcLZCMit3} Error in: TopoDS::Face
    Failed to convert:
    #187=IfcSurfaceCurveSweptAreaSolid(#186,#163,#168,0.,1.,#169)

Test file: [_test.ifc.gz](https://github.com/IfcOpenShell/IfcOpenShell/files/6721949/_test.ifc.gz)

This is the expected geometry:

![Screenshot from 2021-06-27 17-39-34](https://user-images.githubusercontent.com/1747315/123552894-51959a80-d770-11eb-8aa1-17ace6949df9.png)

**Comment by aothms** [comment]
Yes, there was something silly in the handling of derived profile. Should be fixed now https://github.com/IfcOpenShell/IfcOpenShell/commit/10bf875e92c6b94d863c2e413ea1734bae73dfa1

**Comment by brunopostle** [comment]
Thanks, 10bf875 fixes it here, and transforms behave as expected, closing
