### ISSUE TITLE
Objects contained in different building stories

### ISSUE THREAD

**Issue by motjokk** [IfcOpenShell/IfcOpenShell#1542]
Hi,

regarding IfcConvert. 

Objects defined on one floor, that stretches to the next floor are not created on all inflicted floors. Any option that can help me?

**Comment by Moult** [comment]
An object may only be contained (`IfcRelContainedInSpatialStructure`) on a single building storey. However, it may be referenced by multiple storeys (`IfcRelReferencedInSpatialStructure`).
