### ISSUE TITLE
BlenderBIM: Error when clickin IFC-related command

### ISSUE THREAD

**Issue by dedicos** [IfcOpenShell/IfcOpenShell#1543]
Hi, I'm sure I'm missing a point in the whole setup; but when I click any IFC-related command I get an error like this:

```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\owner\operator.py", line 315, in execute
    ifcopenshell.api.run("owner.add_organisation", IfcStore.get_file())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Lib\ifcopenshell\api\__init__.py", line 46, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Lib\ifcopenshell\api\owner\add_organisation.py", line 17, in execute
    return self.file.create_entity("IfcOrganization", **data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Lib\ifcopenshell\file.py", line 227, in create_entity
    self.wrapped_data.add(e.wrapped_data, eid)
TypeError: add() takes 2 positional arguments but 3 were given

location: <unknown location>:-1
```
Any suggestion what the problem might be? Using latest versions of Blender(2.93)and BlenderBIM (210605)

**Comment by Moult** [comment]
This is related to #1475. Right now, I'm working on building in undo support. Therefore, if there is any version mismatch between the BlenderBIM Add-on and ifcopenshell you will run into this problem. Either run master for both for now, or stable for both. Sorry for the inconvenience, but soon after this feature becomes a bit more stable I will fix the builds.

**Comment by dedicos** [comment]
Sorry to open this again, what would be the correct ifcopenshell version to use with the latest blenderbim? I would just copy that to the Python38 Lib directory, right?

**Comment by Moult** [comment]
You can get the latest blenderbim from the daily builds, and but you will need to replace the ifcopenshell that it is shipped with with the latest ifcopenshell. You can get the latest ifcopenshell from build bot comments here: https://github.com/IfcOpenBot/IfcOpenShell/commits/v0.6.0 - but even that is still out of date from a Python perspective - you'll need to download `file.py` and `entity_instance.py` from here: https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcopenshell-python/ifcopenshell

So sorry that so many parts are moving right now, just bad timing I guess.

**Comment by Moult** [comment]
Also I'm a little uncertain about the Python38 folder you have - Blender 2.93 should use its own Python 3.9, not 3.8, so there could be a version conflict which could make this already confusing issue even more confusing. The ifcopenshell shipped with Blender should be in `C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell`

**Comment by dedicos** [comment]
I uninstalled Python 3.8, but still Blender tries to look up something in the Python38 folder. Any idea how to "shift" to the 3.9 folder?

**Comment by dedicos** [comment]
`['C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\scripts\\startup', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\scripts\\modules', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\python39.zip', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\DLLs', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\lib', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\bin', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\python\\lib\\site-packages', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\scripts\\freestyle\\modules', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\scripts\\addons\\modules', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\modules', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\scripts\\addons', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons', 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\scripts\\addons_contrib', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages\\ifcopenshell', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages\\svgwrite', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\ifcopenshell\\lib\\windows\\64bit\\python3.9', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages\\odf', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages\\odf', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages\\odf', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages\\odf', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages\\odf', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages\\odf', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blenderbim\\libs\\site\\packages\\odf', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\ifcopenshell\\express']`

**Comment by Moult** [comment]
So it seems you have got your Python38 at the very end there for some reason. Have you got any other addons installed that might be doing this?

**Comment by dedicos** [comment]
Alright, I uninstalled, reloaded ifcopenshell and everything. It seems I'm on the "bleeding edge" now as I get a "transaction error" or others.

**Comment by Moult** [comment]
The latest build blenderbim-210701 resolves the IfcOpenBot build, but you still need to manually replace the file.py and entity_instance.py. Can you try that?

**Comment by dedicos** [comment]
Manually replace by which file? from the ifcopenshell?

**Comment by dedicos** [comment]
seems to work now. Thank you!

**Comment by Moult** [comment]
Cheers, this might be moving a bit over the next week or so as we continue to implement undo support across operations, so keep watch for anything funky :)
