### ISSUE TITLE
BlenderBIM: applying IfcMaterial in bulk

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1546]
Would be nice to apply an IfcMaterial in bulk.  Perhaps there is, and i'm missing something. 

video: https://www.dropbox.com/s/6gudt3uqjq7xnbh/2021-07-03_07-46-55.mp4?dl=0

file: https://gitlab.com/openingdesign/mudroom/-/tree/c695629f68b05a054f8257603b9a868c317e9592/Models%20and%20CAD

**Comment by Moult** [comment]
The proper workflow is that the material is assigned to the type object, not the individual instances. That way, you shouldn't ever need to assign in bulk except in rare classes. Hope it makes sense?

**Comment by theoryshaw** [comment]
There's a couple workflows, in my opinion, where bulk assignment would be used pretty frequent. 

- In early stages of design, when modeling more freely and fast, where stuff is not necessarily defined, and categorized properly, but you'd still like to apply working palette of materials across multiple objects. 
- 3D details like [this](https://github.com/OpeningDETAIL/Newport_Beach_CA_Residence/blob/master/Transfer/20190320%20-%20Internal%20-%20Markups/Newport_Beach_CA_Residence%20-%20TEMPLATE%20-%20Sheet%20-%20A6-1-1%20-%20DETAILS.pdf), where you have objects, like flashing, that can't be 'typed', bulk assignment would come in handy.

**Comment by Moult** [comment]
I would argue that flashing could be typed, as per the architecture specifications, but definitely flashing isn't the only scenario, and I totally agree with your first point. Let's keep this issue open until I provide a good solution :)

**Comment by Jesusbill** [comment]
+1 from me in this issue, I reckon it will be useful also for structural models
