### ISSUE TITLE
IFC Constraint - Add Objective Bug

### ISSUE THREAD

**Issue by Jesusbill** [IfcOpenShell/IfcOpenShell#1549]
While trying and testing IFC Constraint undo operations I get an error when adding an objective on a new fresh ifc project.

```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/home/jesusbill/.config/blender/2.92/scripts/addons/blenderbim/bim/module/constraint/operator.py", line 89, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/jesusbill/.config/blender/2.92/scripts/addons/blenderbim/bim/ifc.py", line 163, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/jesusbill/.config/blender/2.92/scripts/addons/blenderbim/bim/module/constraint/operator.py", line 95, in _execute
    bpy.ops.bim.enable_editing_constraint(constraint=result.id())
  File "/home/jesusbill/blender-2.92.0-linux64/2.92/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/jesusbill/.config/blender/2.92/scripts/addons/blenderbim/bim/module/constraint/operator.py", line 62, in execute
    new.data_type = data_type
TypeError: bpy_struct: item.attr = val: Attribute.data_type expected a string type, not tuple

location: /home/jesusbill/blender-2.92.0-linux64/2.92/scripts/modules/bpy/ops.py:132
```

With some basic debugging I see that `data_type` from [this operation](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/module/constraint/operator.py#L53) is not always a string but can be a tuple as well. In fact the error comes when we get a tuple and by printing it I get values like below, so it may be that "entity" value appears only in the tuple? (not sure about this).

```
string
string
enum
string
select
string
string
('list', 'entity')
```

I am not aware of all the specifics so not sure what is the best solution. If the result is a tuple then data_type should be defined as a string (of the second element?) but do all tuples have essentially the second element as "entity" or not?

**Comment by Moult** [comment]
Ah yes, just bad code. Perhaps replace it with https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/helper.py#L37

**Comment by Jesusbill** [comment]
yeap, it's done

**Comment by Moult** [comment]
Ah I kinda meant just use blenderbim.bim.helper.import_attributes(...) to replace the entire function, but that's OK, it's fixed.
