### ISSUE TITLE
Potential synergy with FreeCAD trails / turns

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1552]
Ping @civilx64 and @RickBrice - FreeCAD has a "Trails" workbench which contains a bunch of features related to infra / civil. I've reached out to the developer @joelgraff here: https://community.osarch.org/discussion/640/freecad-trails-workbench-transportation-and-geomatics#latest - to see if there are any potential synergies, and how this might integrate with FreeCAD.

Would either of you be interested in a meetup with Joel to do a bit of show and tell on both sides of the fence to see if there are any opportunities?

**Comment by civilx64** [comment]
Yes, I would be interested in collaborating. The Trails workbench appears to support LandXML import of alignments which I had envisioned for BlenderBIM as well. Potentially we could isolate and share a low-level submodule between projects while keeping separate respective UI bindings for FreeCAD and Blender.

**Comment by Moult** [comment]
Awesome! Would you be able to make the proposed meeting time at 8am Friday July 9 Sydney time at https://meet.jit.si/openbim ?

**Comment by joelgraff** [comment]
I can do that.  And yes, I've implemented the LandXML spec inasmuch as I need to import horizontal alignments.  I won't say the code is clear or even worth porting, but it's there. :)  Shouldn't be a big deal to write a more agnostic importer, though I really tried to eliminate dependencies on third-party libs and FreeCAD as much as I could.

**Comment by civilx64** [comment]
I can join on mobile roughly 15 mins after the top of the hour.

**Comment by Moult** [comment]
Great, see everyone then!
