### ISSUE TITLE
BlenderBIM: broken connection btwn Blender file and IFC file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1553]
As I understand it, the following Blender and IFC are connected. @Jesusbill created them. 

However, when you open them in Blender, as you can see from the video, the IFC connection seems to be broken. 
Am i missing something?

files: https://gitlab.com/openingdesign/mudroom/-/tree/c695629f68b05a054f8257603b9a868c317e9592/Models%20and%20CAD

video: https://www.dropbox.com/s/i28ybwfo2guz88r/2021-07-06_14-37-41.mp4?dl=0

![image](https://user-images.githubusercontent.com/507113/124657359-07936f80-de68-11eb-98d3-75b729e35311.png)

**Comment by Jesusbill** [comment]
Thanks @Moult ! I was making sure I can export a correct IFC that I can then import in BlenderBIM without loss or problems, but I hadn't checked what happens if the paths change and one wants to relink the file.
