### ISSUE TITLE
BlenderBim - add loading bar when opening file ?

### ISSUE THREAD

**Issue by Asgatlat** [IfcOpenShell/IfcOpenShell#1558]
is it possible to add a loading bar or something else to show the progression ?
it would be nice, to be sure that is loading and not crashing

**Comment by s-leger** [comment]
May show progress percent in cursor icon, using window_manager.progress_xx things.

**Comment by Moult** [comment]
You can toggle the system console and view the progress in there. Does that help? I will also look at showing percent in the cursor icon.

**Comment by Asgatlat** [comment]
the percent progress in cursor icon could be a good feature
