### ISSUE TITLE
Some geom functionality broken after file attribute on entity_instance constructor

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#1560]
@Moult it took me a while to realize (Travis has been a bit silent with us) but after the recent changes some of the geometry handling is broken

![afbeelding](https://user-images.githubusercontent.com/1096535/125168022-accd8100-e1a3-11eb-9da4-1f482d6bd384.png)

https://app.travis-ci.com/github/IfcOpenShell/IfcOpenShell/builds/232369835#L1977

geom.tesselate() / serialize() don't have have a reference to a file so the constructor fails, at that time they also aren't yet added to a file. So there's nothing we can feed the constructor other than None.

tree.select / select_box() in this case there probably is an underlying file but we just don't know it. I can probably fix that.

Can we default the file parameter in entity_instance() to None? Maybe gracefully handle this with a human readable error message in the transaction handling?

**Comment by Moult** [comment]
Ah good catch! Yes I guess for now just feed it None, and we don't use transactions with these functions I believe. Do you think there is a better solution than the "put file in constructor" so that we don't run into similar issues in the future? I'm happy with your fix.

**Comment by aothms** [comment]
> and we don't use transactions with these functions I believe

I agree. I think we can close this with the quick fix. As discussed earlier, we can get the C++ file from C++, but it's not the wrapped ifcopenshell.file. This is clearly a downside of the double layered approach, but without it we wouldnt have been able to prototype transactions so quickly, so I think we also cannot get away with that. We can solve it a bit better if the need arises I guess. Thanks for having a look.
