### ISSUE TITLE
Assigning new type to instance changes all assignments of old type

### ISSUE THREAD

**Issue by dedicos** [IfcOpenShell/IfcOpenShell#1562]
When I create multiple instances of a certain construction type and want to assign a different type to one of them, all the instances change to the new type. Is this intended? Or can I assign a new type in a different way?

Edit: just saw that the type defining geometry changes, too, so that should not be the case.

**Comment by Moult** [comment]
I cannot recreate this error unfortunately. Can you share an IFC or a schedule a screensharing session to debug? I'm in the Sydney timezone usually available between 8am and 8pm.

**Comment by dedicos** [comment]
Please see [Screencast](https://youtu.be/Memrlieju8c[](url)).

**Comment by Moult** [comment]
Thanks for the screencast and bugreport! That instantly allowed me to debug and fix! Sorry for the late fix!
