### ISSUE TITLE
Missing template for classification

### ISSUE THREAD

**Issue by dedicos** [IfcOpenShell/IfcOpenShell#1563]
The documentation (https://blenderbim.org/docs/blenderbim/scene.html) states that there is a csv file for classification definitions in a "class" directory. I don't see that; can this file be provided in a future release?

**Comment by Moult** [comment]
The docs are outdated. Would love a contributor to help rewrite it :)

Classifications are now loaded using IFC project libraries, and a couple are shipped out of the box at `/path/to/blender/2.93/scripts/addons/blenderbim/bim/schema/classifications`

More can be downloaded here https://github.com/moult/ifcclassification
