### ISSUE TITLE
BlenderBIM: Parenting to Container

### ISSUE THREAD

**Issue by dedicos** [IfcOpenShell/IfcOpenShell#1565]
I would like to link the position of the objects to a spatial container (or even better, have the option to nest other coordinate systems as local placements) so I can move all elements of a storey by their coordinate systems. However, if I parent an object to an empty axes object the ifc export crashes. Even if I undo the operation I can no longer export an IFC.

**Comment by Moult** [comment]
I assume you're talking about within blender, since in IFC placements are already related.

You don't need to use parenting. Just  right click on the collection for the storey and select all objects, then you can move them all in one go.

**Comment by Moult** [comment]
I'll test tomorrow to see if I can recreate your crash though. Crashes should definitely be fixed. If you have a screen cast of a minimal example that will speed up the fixing process.

**Comment by dedicos** [comment]
> I assume you're talking about within blender, since in IFC placements are already related.
> 
> You don't need to use parenting. Just  right click on the collection for the storey and select all objects, then you can move them all in one go.

Just learnt about parenting, so that sounded like a nice feature. But it's true, to stick with the "container = placement" paradigm the selection workflow would be sufficient.

Adding another storey would just mean copying the default one I guess?

**Comment by Moult** [comment]
Yes, you can just copy the default one, but it didn't auto create a collection tree for you which was a pretty poor user experience. Now it does.

I couldn't recreate your crash, though. It may be due to using an old (or stable) build where undo was actually not implemented (yes, it's true!).
