### ISSUE TITLE
Bimtester examples are broken

### ISSUE THREAD

**Issue by Nitschi** [IfcOpenShell/IfcOpenShell#1568]
Are the examples in [`v0.6.0/src/ifcbimtester/examples/steps/`](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcbimtester/examples/steps) still up to date?

The files seem to import some modules that do not exist anymore (or I can't find), especially the module "utils".
There is a modul "util" in [`v0.6.0/src/ifcbimtester/bimtester`](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcbimtester/bimtester) , but it does not contain "IfcFile" and other methods that the example steps try to import.

All the best,

Alex

**Comment by Moult** [comment]
Nah the examples folder is very poorly named and is actually old code that I never migrated yet to the newer system. Don't trust anything in there. You'll want to look in https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcbimtester/bimtester/features/steps  instead.

I'll get around to it :) or would you like to help contribute?

**Comment by Nitschi** [comment]
Thanks for the info :)
I might try my luck on one or two of the pset test cases, but I don't have time for much more than that.

Hope that helps.

**Comment by Moult** [comment]
Thanks for your commit!

**Comment by berndhahnebach** [comment]
related: https://community.osarch.org/discussion/comment/9590/#Comment_9590 ...

These examples have all been stopped to run after Moults big changes in Spring 2021. The time being most of them have been changed and have been extended. 

How do we proceed with these old examples? Should we adapt them and merge them back into BIMTester or remove them?

cheers bernd

**Comment by Moult** [comment]
Ideally I'd like to adapt them and merge them back into BIMTester.

**Comment by berndhahnebach** [comment]
OK. Most of them are examples I have coded for the use here in the company. The ones I need I have adapted already. Should I merge them into main repo and delete the merged ones in examples ?

**Comment by Moult** [comment]
Yes, please do :)

**Comment by berndhahnebach** [comment]
started to move some ... https://github.com/IfcOpenShell/IfcOpenShell/compare/bb9eba07c04cbd222ac0d7a6db7f372c9496bdd4...82d136b9b3179f84abb463c960c686a5c1e0ee6a

**Comment by Moult** [comment]
I think in the original context of this question, this is now superseded by IDS / IfcTester.
