### ISSUE TITLE
BlenderBIM - PSets showing up with a delay

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#1575]
When I add a property set, it takes about 10-20 seconds until it shows up in the UI (or, shows up several times as I hit the button more than once). Latest build (210719)

**Comment by Moult** [comment]
Is it a large file?

**Comment by dedicos** [comment]
No, test file with only one cube. Everything else is quite performant.

**Comment by Moult** [comment]
Can't replicate here. Tested both on Linux and Windows. Using Blender 2.93? Which OS? Is it always slow, or only the first time you add a pset, and the second time you add another pset it is fast?

**Comment by Moult** [comment]
In addition, perhaps you can start by commenting out various lines of code to see what is slow. Don't worry if you break things, the point is to see what makes it take a long time to show up.

When you press the "+" button to add a pset, this is the code that executes: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/module/pset/operator.py#L259-L284 - comment out lines to see which one is the culprit. The function on L275 then runs this code: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/pset/add_pset.py#L12-L66 - similarly, comment out stuff from there to isolate any slow lines.

When you've figured out which line is slow, that'll give me an idea of how to fix it :)

**Comment by Moult** [comment]
Bump? :)

**Comment by Moult** [comment]
Bumpity bump. Will close if cannot be recreated within 2 weeks.

**Comment by TZwielehner** [comment]
Doesn't occur again right now. Can be closed then, thanks.
