### ISSUE TITLE
Performance optimisation.

### ISSUE THREAD

**Issue by saq1410** [IfcOpenShell/IfcOpenShell#158]
Hi,
I am new to this so need some help. I am converting an IFC file to DAE format. initially it was taking lot of time to convert for the big IFC file and the size of the resultant file was huge. I have build the master version of the IfcOpenShell and after reading the performance #47 I came to know about caching. So in Ifcgeom.h i have remove d the comment #define NO_CAHCHE. i.e from //#define NO_CACHE to #define NO_CACHE. is it the correct way for implementing caching. Thank you.

**Comment by aothms** [comment]
Hi,

> i.e from //#define NO_CACHE to #define NO_CACHE

This disables caching altogether.

If you feel your model would benefit from more aggressive caching (i.e. maintain longer in memory), you can set the `clear_interval` [1] to a higher value.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomIterator.h#L373

Hope that helps,

Kind regards,
Thomas

**Comment by Stinkfist0** [comment]
Also passing `-DENABLE_BUILD_OPTIMIZATIONS=1` for CMake invocation is recommended if the best performance is wanted (in the expense of debugging capabilities).

**Comment by saq1410** [comment]
Hi,
Thanks for your help. I have increased the clear_interval but I guess there are not much of similar objects. Thats why not getting considerable difference. Some of the objects taking a lot of time to triangulate. 
  converting a file having 31441 items to convert. The first 10800 objects get created in 2 or 3 min after that each object taking a 10 to 15 minutes to convert :( . 

Hi Ali,
      Thanks. But I m not using CMake. Is there another way to do the same what you have suggested.

**Comment by Stinkfist0** [comment]
@saq1410 Sorry, I don't follow. CMake is a prerequisite to build IfcOpenShell (as is, I'd guess one could alternative/manual approach for generating build files but that would be a lot of work).

**Comment by saq1410** [comment]
@Stinkfist0 yeah you are right. Actually I have generated the binaries that is visual studio project files from CMake at the start. But when I used the same code in another machine it was showing some wierd errors. So I just deleted the all CMake files and it worked fine after that.

**Comment by Moult** [comment]
The OP seems to have been able to build IfcOpenShell successfully, and given there are no test files provided for us to retest / debug this in 2022, I'm closing this bug.
