### ISSUE TITLE
IfcPatch - invalid instance name

### ISSUE THREAD

**Issue by dedicos** [IfcOpenShell/IfcOpenShell#1582]
I try to get my head around the IfcPatch tool. However, every recipe I try throws a different error.

When I use the ExtractElements recipe:
`python -m ifcpatch -i walls.ifc -o result.ifc -r ExtractElements -a ".IfcWall"`
I get
`RuntimeError: Token $ at 274 invalid instance name`

When I use the MergeProject recipe:
`python -m ifcpatch -i walls.ifc -o result.ifc -r MergeProject -a ["C://Users//abc//win_doors.ifc"]`
I get
`OSError:` Unable to upen file for reading`
[win_doors.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6865545/win_doors.ifc.txt)

That might be a Windows path thing, but no matter what combination I try I'm out of luck. (txt extension added for uploading reasons only. result.ifc is an empty file)
[win_doors.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6865546/win_doors.ifc.txt)
[walls.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6865547/walls.ifc.txt)

**Comment by aothms** [comment]
The first error points you at character offset 274 in the file. You can use notepad++ for example to go there 

![afbeelding](https://user-images.githubusercontent.com/1096535/126748050-b34bc46c-e91b-4d78-adfc-3a5660e1bc7d.png)

```
#1=IFCPROJECT('2WkLgexjb5reKYn42kBR21',$,$,$,$,$,$,$,$);
                                                     ^
```

These kind of attributes on IfcProject are not optional. 

```
RepresentationContexts 	 :  	SET [1:?] OF IfcRepresentationContext;
UnitsInContext 	 :  	IfcUnitAssignment; 
```

For correct function of these script the file needs to be valid. You can file validity errors with

```
python -m ifcopenshell.validate wall.ifc
```

>  OSError: Unable to upen file for reading

That's a more generic error unrelated to ifcopenshell. I don't where it's called do you have the full stack trace?

**Comment by dedicos** [comment]
Thanks for the notepad tip! Playing around with the native ifc creation still leads to None values at certain points, I have to consider that more thoroughly :)

**Comment by Moult** [comment]
For the second error your command should be (not sure about the slash directions on windows, but definitely remove the square brackets):

```
python -m ifcpatch -i walls.ifc -o result.ifc -r MergeProject -a "C:/Users/abc/win_doors.ifc"
```

The square brackets are only used in the BlenderBIM GUI via JSON. In a shell, don't use the square brackets.

**Comment by dedicos** [comment]
Arrgh... Found out the reason for  the "unable to open" problem: the IFC files where stored directly in my user's directory  (C:\users\abc\), and that didn't work. I moved it to "Documents" and it opened without a problem.
