### ISSUE TITLE
BlenderBIM: automatically update 'depth' representation.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1588]
Would be nice if the 'depth' attribute automatically updated, opposed to having to click the 'Update Representation' button every time.

video: https://www.dropbox.com/s/plwo6lsma76yq44/2021-07-25_13-17-26.mp4?dl=0

**Comment by theoryshaw** [comment]
I guess it would require automatically updating the placement as well. 

video: https://www.dropbox.com/s/o1a0x7c4c2ksbnx/2021-07-25_13-59-55.mp4?dl=0

**Comment by Moult** [comment]
Cheers, yes, both are indeed bugs. By the way, the proper place to edit this is in the IFC Object Material panel and editing the IFC material profile set. Within it, you can edit the profile attributes. There was a bug where sometimes it wouldn't show up, but now that's fixed.

**Comment by Moult** [comment]
Just got the placement left to go!
