### ISSUE TITLE
Tracking native architectural authoring

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1590]
To date, the majority of usecases for the BlenderBIM Add-on have been models authored in other software, and then augmented / analysed / etc in the BlenderBIM Add-on.

Obviously, the goal is that you can author directly in Blender. All the tools are almost already there, but aren't integrated. So in theory you could author directly, but it is an incredibly painful process and not practical. To make this real, this involves building more parametric tools, stress testing the parametric relationships (e.g. #1588), and creating a UX which allows for rapid, pain-free authoring.

The BIM Workspace Tool is at the heart of this. Here's a list in rough order of how I'm tackling it.

- [x] Walls
- [x] Slabs
- [x] Layer based things
- [x] Covering
- [x] Columns
- [x] Beams
- [x] Profile based things
- [x] Members
- [x] Openings
- [x] Door
- [x] Window
- [x] Furniture
- [x] Pile
- [ ] Stair

If something is marked as ready, it's ready for you to start stress testing and bug reporting and trying out as a native modeling tool. Please help and break it :)

**Comment by Moult** [comment]
@theoryshaw et all :) Would you mind playing around with walls / slabs / columns / beams / openings and trying to break them :) For furniture you should be able to bring in models from other files.

[blenderbim-demo-library.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6957860/blenderbim-demo-library.ifc.txt)

**Comment by theoryshaw** [comment]
Will do. :)

**Comment by Moult** [comment]
New demo library :)

[blenderbim-demo-library.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6978749/blenderbim-demo-library.ifc.txt)

**Comment by theoryshaw** [comment]
nice.. possible to create an osarch gitlab repo to track this? 
https://gitlab.com/osarch

**Comment by Moult** [comment]
@theoryshaw in the future yes, for now, it is a generated library using this script while I work out some of the kinks of generating libraries: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/generate_demo_library.py

**Comment by theoryshaw** [comment]
Sounds good.  Possible to start an imperial library, as well.  Sorry. :)

**Comment by Moult** [comment]
Not just yet, I will though :)

Here's an updated library with a window if you want to test the ability to add windows. Select a wall, place the cursor on the wall, then add a window, and it should insert the window with an appropriate opening in the selected wall.

[blenderbim-demo-library.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6991761/blenderbim-demo-library.txt)

**Comment by Plae-Blue-Dot** [comment]
Works great! Nice to have a window tool and starting to feel like a real Bim program, one thing it's doing right now:
- It seems to load an duplicate instance of the window at the origin/plane axis empty in addition to the 3d cursor (adds it to the types collection
![image](https://user-images.githubusercontent.com/78321676/129942264-a76313e3-419a-494a-bc50-d03d1a1d836b.png)

**Comment by theoryshaw** [comment]
I think that's by design.  That's where the types live.  The idea would be to hide the 'types' collection.

**Comment by Moult** [comment]
Yes it needs to hide the types collection by default. That collection is where all the types live by default.

**Comment by Moult** [comment]
The latest release contains a bunch of fixes, and the libraries are now hosted in the repo so I can update them as I find more issues. Please let me know if you find any bugs!

**Comment by Moult** [comment]
Closing bug as the main building blocks are there for initial testing and feedback. However, it is still not mature. I will open a new tracking bug with a strategy to methodically ensure the robustness of native authoring.
