### ISSUE TITLE
BlenderBIM : Assigning a Spatial Container resets the active object state

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1598]
Using BlenderBIM v 210726
![image](https://user-images.githubusercontent.com/25156105/127160871-34a1096c-9f31-4725-87b0-b81c7171b521.png)

I assigned a spatial container to an object and it correctly moved the object in the corresponding collection. The object is still selected, but it isn’t active anymore, so the Property editor jumps to the Scene properties right afterwards, disrupting the workflow.  It’s a little User Experience annoyance.

**Expected behavior** : Keep the active object as active after the operator’s execution.

**Comment by Moult** [comment]
This sounds like a pretty straightforward bug to fix and a great way to get started in contributing in the assign container operator. Would you like to give it a shot and submit a PR?

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/module/spatial/operator.py#L9 is the code you'd need to poke I think.

**Comment by Gorgious56** [comment]
@Moult Alright, I'm on it. 
I have experience coding in python but not so much on contributing with teams. 
So, I add a pull request here on github once I think I'm done and you can review it ?

**Comment by Moult** [comment]
@Gorgious56 yep :) create a fork, do your changes there, create a pull request when you're done. When you've done a few PRs and are comfortable, we can give you direct access to this repository so you can make and break as you see fit :D

**Comment by Gorgious56** [comment]
@Moult Nice ! I _think_ I managed to do it without messing things up too much ^^ 
https://github.com/IfcOpenShell/IfcOpenShell/pull/1601
 I did at first create a pull request on my own fork which is not what I intended to do and I messed up the indentation and fixed it but, oh well...
 
Please tell me if there are established guidelines on coding, comments, branch naming conventions, etc so I can make the review process easier for you.

**Comment by Moult** [comment]
Awesome and great work! The guidelines on coding are basically we use "black" as a code formatter with a line width of 120 characters. No branch naming conventions - we are currently developing live on v0.6.0, as we are still in alpha. When we mature enough for a beta release, we will establish conventions for branches. In general, comments are good where things are not obvious. Naming and refactoring is preferred to comments.
