### ISSUE TITLE
BlenderBim No transparency on windows

### ISSUE THREAD

**Issue by Asgatlat** [IfcOpenShell/IfcOpenShell#1600]
hi,

on a IFC file, BlenderBim (blender28-bim-210727-py39-win) seems not to display transparency of windows instead with other IFC viewer : 

![image](https://user-images.githubusercontent.com/86599367/127288301-2e888eeb-82e5-4900-b0df-5d6810981b94.png)

![image](https://user-images.githubusercontent.com/86599367/127288342-fa7855b9-1038-4268-b184-1708147a63fa.png)

**Comment by Moult** [comment]
It looks as though the transparency works fine, but simply that you have an IfcSpace (which is non transparent) within it. Simply select the IfcSpace, and use the select icon (the arrow shaped one in the screenshot below) to select all spaces, then press "H" to temporarily hide them.

If that isn't the issue, you may need to share your file with me or let's organise a screenshare.

![2021-07-28-183212_345x74_scrot](https://user-images.githubusercontent.com/88302/127291012-499ba9e3-3b1e-469e-be67-d9e58ed9e798.png)

**Comment by Asgatlat** [comment]
it works, thank you
![image](https://user-images.githubusercontent.com/86599367/127292229-d10670ef-6447-4d2b-8141-6c0d466ab46f.png)
