### ISSUE TITLE
BlenderBIM: Classifications

### ISSUE THREAD

**Issue by edwinguerra** [IfcOpenShell/IfcOpenShell#1602]
Classification systems seem to have changed since I last used them. I tried going here: https://github.com/Moult/IfcClassification/tree/master/ifc

to load OmniClass, but got a bunch of errors. Am I missing something?

**Comment by Moult** [comment]
I just tested this and it seems to work. What error were you experiencing?

**Comment by Moult** [comment]
Will close in a week if no progress :)

**Comment by edwinguerra** [comment]
I just re-downloaded latest everything and you are correct, it works.
