### ISSUE TITLE
[IfcConvert] glb and dae conversion result size difference

### ISSUE THREAD

**Issue by ketourneau** [IfcOpenShell/IfcOpenShell#1605]
Hi,

When we convert ifc to glb without parameters we got 5.9 Mo glb file size result.
`IfcConvert file.ifc output.glb`

But when we use `--use-world-coords` with `--center-model-geometry` parameters we got 38.1 Mo glb file size result.
`IfcConvert file.ifc --use-world-coords --center-model-geometry output.glb`

Since the geometry is centered, we expect to get the same glb file size result (5.9 Mo).

[file.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6899386/file.ifc.zip)

**Comment by aothms** [comment]
`--use-world-coords` makes it impossible to use geometry instancing. That explains the difference.

**Comment by ketourneau** [comment]
Ok thank you for the answer !
