### ISSUE TITLE
pyrna_enum_to_py: current value '0' matches no enum

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1608]
I see many thousands of these warning messages running ifcopenshell.api methods within blender, but can't track down the source:

    WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1499 pyrna_enum_to_py: current value '0' matches no enum in 'BIMOwnerProperties', '', 'user_person'
    WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1499 pyrna_enum_to_py: current value '0' matches no enum in 'BIMOwnerProperties', '', 'user_organisation'

To reproduce, open the blender text editor and run this code:

```python
import ifcopenshell

run = ifcopenshell.api.run
ifc = run("project.create_file")

run("owner.add_person", ifc)
run("owner.add_organisation", ifc)

project = run(
    "root.create_entity",
    ifc,
    ifc_class="IfcProject",
    name="My Project",
)
```

**Comment by Moult** [comment]
@Gorgious56 would you like to tackle this one? One place it is definitely due to is in the BlenderBIM Add-on "N" panel. Basically the EnumProperty for bpy.data.scenes["Scene"].BIMTypeProperties.ifc_class and bpy.data.scenes["Scene"].BIMTypeProperties.relating_type are empty so it gets upset.

**Comment by Gorgious56** [comment]
@Moult I'll check it out !

**Comment by Gorgious56** [comment]
That's a bit more involved than I initially thought. Turns out dynamic enums which are not populated tend to throw out warning messages as if it were candybars when we try to access them.


https://github.com/IfcOpenShell/IfcOpenShell/pull/1613

**Comment by Gorgious56** [comment]
Ideally one would need to access the enum's `items` method before accessing it to see if they're empty or not. I don't really know how to solve this gracefully since that would add a level of complexity, needing to import the module in every occurence, and it also means the items list will be created twice everytime we want to access the dynamic enum... I'm really stumped there is no easier way to check if a dynamic enum is empty in Blender...

**Comment by brunopostle** [comment]
Note that I'm using a large part of the IfcOpenShell API, but the only enum warnings I see are the two above (user_person & user_organisation). So this may not be a general issue with enum handling, it could be a problem with just these two.

**Comment by Gorgious56** [comment]
@Moult I _think_ I fixed the errors in the Authoring panel with https://github.com/IfcOpenShell/IfcOpenShell/pull/1620 but not the warning messages in the OP. 
I couldn't replicate the issue : I get the warning messages printed once for each one but never again after that. @brunopostle  would be nice to pinpoint what UI element(s) cause the warnings to be printed out

**Comment by brunopostle** [comment]
@Gorgious56 the warnings occur with ifcopenshell.api commands, I'm not doing anything to the UI or even clicking on anything, i.e. this code produces lots more of the same warnings (note, I also removed the owner.add_person and owner.add_organisation code which doesn't seem to make any difference to the warnings):

```python
import ifcopenshell

run = ifcopenshell.api.run
ifc = run("project.create_file")

project = run(
    "root.create_entity",
    ifc,
    ifc_class="IfcProject",
    name="My Project",
)

site1 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site1")
site2 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site2")
site3 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site3")
site4 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site4")
site5 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site5")
```

Whereas this that does more or less the same thing using lower-level ifcopenshell functions doesn't:

```python
import ifcopenshell

run = ifcopenshell.api.run
ifc = run("project.create_file")

ifc.createIfcProject()
ifc.createIfcSite()
ifc.createIfcSite()
ifc.createIfcSite()
ifc.createIfcSite()
ifc.createIfcSite()
ifc.createIfcSite()

**Comment by brunopostle** [comment]
The same code runs fine as a command-line script outside blender, no warnings:

```python
#!/usr/bin/python3

import ifcopenshell.api

run = ifcopenshell.api.run
ifc = run("project.create_file")

project = run(
    "root.create_entity",
    ifc,
    ifc_class="IfcProject",
    name="My Project",
)

site1 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site1")
site2 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site2")
site3 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site3")
site4 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site4")
site5 = run("root.create_entity", ifc, ifc_class="IfcSite", name="My Site5")

**Comment by brunopostle** [comment]
If I uninstall blenderbim (but with ifcopenshell available), the same code runs in the blender text editor without warnings.

**Comment by Gorgious56** [comment]
AFAICT, the only other part of the blenderBIM code other than a UI element that could cause these errors is this handful of lines : 
https://github.com/IfcOpenShell/IfcOpenShell/blob/2137b340636fb7c2ec5eda1765b5f7f44062075d/src/blenderbim/blenderbim/bim/handler.py#L212
But commenting these out still leads to warnings in the console so I'm lost 😕

**Comment by Moult** [comment]
You found the right location, but commenting it out probably didn't work as it is registered as a persistent on load handler, so the old code still persisted :)

A short explanation: when you edit things in IFC, IFC keeps track of who edited what last (kinda like HEAD on version control, but no further history). This is known as "OwnerHistory" in IFC. The API doesn't know who your active user or organisation is to log these changes, so it relies on you to overload the "get_person" and "get_organisation" function of the API in your authoring script, or in this case, the BlenderBIM Add-on environment. That's why there is an on load handler which sets up these two functions to read from Blender's property to define the "active user" and "active organisation".

**Comment by Gorgious56** [comment]
OK, nice to learn that. I didn't notice the `@persistent` decorator, that makes sense !
