### ISSUE TITLE
api.type.assign_type creates identical IfcMaterialLayerSetUsage entries for a single IfcMaterialLayerSet

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1616]
Each time I assign a IfcMaterialLayerSet to an object, a duplicate IfcMaterialLayerSetUsage entry is created:

    #13451=IFCSLABTYPE('3BVA7VSsbFOO2cfhbjeaSg',$,'living-floor',$,$,$,$,$,$,.FLOOR.);
    #13452=IFCMATERIALLAYERSET((#13454,#13455),$,$);
    #13453=IFCRELASSOCIATESMATERIAL('24xZazJRf9uROUKJw2_2eo',$,$,$,(#13451),#13452);
    #13456=IFCRELDEFINESBYTYPE('2TtaEnxqP5Gvtej4d$emsu',$,$,$,(#13450,#13506,#13554,#13602,#13652,#13702),#13451);
    #13457=IFCMATERIALLAYERSETUSAGE(#13452,.AXIS3.,.POSITIVE.,0.,$);
    #13507=IFCMATERIALLAYERSETUSAGE(#13452,.AXIS3.,.POSITIVE.,0.,$);
    #13555=IFCMATERIALLAYERSETUSAGE(#13452,.AXIS3.,.POSITIVE.,0.,$);
    #13603=IFCMATERIALLAYERSETUSAGE(#13452,.AXIS3.,.POSITIVE.,0.,$);
    #13653=IFCMATERIALLAYERSETUSAGE(#13452,.AXIS3.,.POSITIVE.,0.,$);
    #13703=IFCMATERIALLAYERSETUSAGE(#13452,.AXIS3.,.POSITIVE.,0.,$);

I assume the same happens with IfcMaterialProfileSet

I tried to figure-out how to fix this, but don't really understand :(

**Comment by Moult** [comment]
Can you share some code as to how this occurs? I cannot replicate it.

There are some assumptions currently which create some constraints on when and where usages can happen but I can't judge whether it relates.

**Comment by brunopostle** [comment]
This code produces duplicate IfcMaterialLayerSetUsage entries:

```python
#!/usr/bin/python3
import ifcopenshell.api

run = ifcopenshell.api.run
file = run("project.create_file")
myelement_type = run(
    "root.create_entity",
    file,
    ifc_class="IfcSlabType",
    name="My Slab Type",
    predefined_type="USERDEFINED",
)
run(
    "material.assign_material",
    file,
    product=myelement_type,
    type="IfcMaterialLayerSet",
)
entity = run("root.create_entity", file, ifc_class="IfcSlab", name="My Slab")
run(
    "type.assign_type",
    file,
    related_object=entity,
    relating_type=myelement_type,
)
entity2 = run("root.create_entity", file, ifc_class="IfcSlab", name="My Slab 2")
run(
    "type.assign_type",
    file,
    related_object=entity2,
    relating_type=myelement_type,
)
file.write("_test.ifc")

**Comment by Moult** [comment]
I don't see an issue, here's the output with some line breaks and formatting for clarity:

```
DATA;
/* The type has a layer set. Cool. */
#1=IFCSLABTYPE('3ST0GTOR54Gham63KKhQaH',$,'My Slab Type',$,$,$,$,$,$,.USERDEFINED.);
#2=IFCMATERIALLAYERSET($,$,$);
#3=IFCRELASSOCIATESMATERIAL('1OvlTGm7T3GRVnS0DtWHYm',$,$,$,(#1),#2);

/* The type has two occurrences */
#5=IFCRELDEFINESBYTYPE('3AFnWouCjBl9ZFto5tI9Zl',$,$,$,(#4,#8),#1);

/* The slab has a material layer set usage */
#4=IFCSLAB('2Ohk_lskv6p9KYqunLVqYb',$,'My Slab',$,$,$,$,$,$);
#6=IFCMATERIALLAYERSETUSAGE(#2,.AXIS3.,.POSITIVE.,0.,$);
#7=IFCRELASSOCIATESMATERIAL('1U0UNQtFX51vB2AnB9LY51',$,$,$,(#4),#6);

/* The slab has a material layer set usage */
#8=IFCSLAB('06xBEkgOD3S8vQJdw4C7GI',$,'My Slab 2',$,$,$,$,$,$);
#9=IFCMATERIALLAYERSETUSAGE(#2,.AXIS3.,.POSITIVE.,0.,$);
#10=IFCRELASSOCIATESMATERIAL('1yw1jWW5j4SRD7XuFs6EOQ',$,$,$,(#8),#9);
ENDSEC;
```

See here for relevant doc quote from the IfcMaterialLayerSetUsage page - I added some emphasis on how usages cannot be shared but the set is:

> The IfcMaterialLayerSetUsage is always assigned to an **individual occurrence** object (and only to relevant subtypes of IfcElement). The IfcMaterialLayerSet, referenced by ForLayerSet, can however be **shared** among several occurrence objects. If the element type is available (in other words, an instance of the relevant subtype of IfcElementType exists), then the IfcMaterialLayerSet can be assigned to the element type. The assignment between a subtype of IfcElement and the IfcMaterialLayerSetUsage is handled by IfcRelAssociatesMaterial.

**Comment by brunopostle** [comment]
Thanks, I see that now, sorry for the noise. It didn't occur to me that the usage wasn't associated with the type, but is applied separately to every object. Closing
