### ISSUE TITLE
Fail to import MappedRepresentation geometry

### ISSUE THREAD

**Issue by ifcwebserver** [IfcOpenShell/IfcOpenShell#162]
Hello Thomas,

Some user has uploaded an IFC file to www.ifcwebserver.org 
for some reason the IfcBlender plugin was not able to import the geoemtry.
can you please have a look at this file to find out why the geometry is not imported.

Other IFC viewers show the geometry without a problem

File:  https://dl.dropboxusercontent.com/u/9691311/ChillerTestFile.ifc

Thank you

**Comment by aothms** [comment]
It imports successfully using the current code base. Released binaries on the web are unfortunately rather old. If I am not mistaken previously a single invalid face would fail the entire shell.

![chillertestfile ifc](https://cloud.githubusercontent.com/assets/1096535/21054661/d230960a-be2e-11e6-82a0-282f8549c9d8.png)
