### ISSUE TITLE
data missing when parsing the data from a function

### ISSUE THREAD

**Issue by Fleakad** [IfcOpenShell/IfcOpenShell#1624]
I have a problem when trying to passing data from/to functions. I am trying to get the elements according to a flag indicating the type (so far I have 4 types, columns, walls, slabs, and beams). I call a function to do it, and return a vector of generic elements to iterate later. When I iterate the elements list from the file everything is ok and the vector gets populated. The problem comes when I go back to the main function (inside the same class). The vector has the same size and it contains the main object pointer, but the data inside is somehow missing. If I take a look with VS2019, I can see that all the fields are ?????. I guess it is because the pointers inside the "main" pointer are in a different scope? Does anybody have any idea how I can fix this. I really need to access the elements from different functions and methods, and I would like to avoid bad coding practices (I have a limited coding knowledge already to introduce even more bad things)

here is the method to get the list of elements that I am using: 

                 std::vector<IfcSchema::IfcBuildingElement*> getBuildingElements(const dataTypes::ElementType& elementType)
			{
				std::vector<IfcSchema::IfcBuildingElement*> elementsList;

				IfcParse::IfcFile ifcFile(m_ifcFileName.string());
				if (ifcFile.good())
				{
					switch (elementType)
					{
					case dataTypes::ElementType::WALL:
					{
						IfcSchema::IfcWall::list::ptr walls = ifcFile.instances_by_type<IfcSchema::IfcWall>();
						for (IfcSchema::IfcWall::list::it it = walls->begin(); it != walls->end(); ++it)
						{
							IfcSchema::IfcBuildingElement* element = *it;
							elementsList.push_back(element);
						}
						break;
					}
					case dataTypes::ElementType::SLAB:
					{
						IfcSchema::IfcSlab::list::ptr slabs = ifcFile.instances_by_type<IfcSchema::IfcSlab>();
						for (IfcSchema::IfcSlab::list::it it = slabs->begin(); it != slabs->end(); ++it)
						{
							IfcSchema::IfcBuildingElement* element = *it;
							elementsList.push_back(element);
						}
						break;
					}
					case dataTypes::ElementType::COLUMN:
					{
						IfcSchema::IfcColumn::list::ptr columns = ifcFile.instances_by_type<IfcSchema::IfcColumn>();
						for (IfcSchema::IfcColumn::list::it it = columns->begin(); it != columns->end(); ++it)
						{
							IfcSchema::IfcBuildingElement* element = *it;
							elementsList.push_back(element);
						}
						break;
					}
					case dataTypes::ElementType::BEAM:
					{
						IfcSchema::IfcBeam::list::ptr beams = ifcFile.instances_by_type<IfcSchema::IfcBeam>();
						for (IfcSchema::IfcBeam::list::it it = beams->begin(); it != beams->end(); ++it)
						{
							IfcSchema::IfcBuildingElement* element = *it;
							elementsList.push_back(element);
						}
						break;
					}
					default:
						break;
					}
				}			

				return elementsList;
			}

**Comment by aothms** [comment]
Indeed, the `IfcParse::IfcFile` is allocated inside the function. When the function returns the IfcFile goes out of scope and deletes all the instances it contains.

It seems this is a member method of a class. So instead of `IfcParse::IfcFile ifcFile(m_ifcFileName.string());` inside the function. Move it to the file parsing to the constructor and reference the file in this function.

**Comment by Fleakad** [comment]
Thanks for the comment

I originally had it like you are saying, member variable with the ifcfile, open it in the constructor, and wasn't giving any compilation errors. But when i was trying to do the query "instances_by_type", I was getting a runtime error with an access violation. Looked like the list was empty, despite of having plenty of elements.

I will try again, but I have no clue why that was happening. Do I have to do something special when creating the ifcfile? Maybe I need to put it in a shared pointer?

**Comment by aothms** [comment]
Nothing special no, happy to have another look to the other approach you had before.

**Comment by Fleakad** [comment]
thank you @aothms. Here is a more detailed description of the situation:

So roughly what I have for my class is this:

     class IFCManager
		{
		private:
			std::shared_ptr<IfcParse::IfcFile> m_ifcFile;
			boost::filesystem::path m_ifcFileName;
			double m_lengthUnit;
		public:
			IFCManager(const boost::filesystem::path& filename) : m_ifcFileName(filename)
			{
				IfcParse::IfcFile ifcFile(m_ifcFileName.string());
				m_ifcFile = std::make_shared<IfcParse::IfcFile>(ifcFile);
				m_lengthUnit = obtainLengthUnit();				
			}
			
			IfcUtil::IfcBaseClass* getElement(const std::string label, const bool UIDsearch = true)
			{
				if (UIDsearch)
				{
					return getElementByUID(label);
				}
				else
				{
					IfcSchema::IfcBuildingElement::list::ptr elementsList = m_ifcFile->instances_by_type<IfcSchema::IfcBuildingElement>();

					for (IfcSchema::IfcBuildingElement::list::it it = elementsList->begin(); it != elementsList->end(); ++it)
					{
						const IfcSchema::IfcBuildingElement* element = *it;

						if (element->hasName())
						{
							std::cout << element->Name() << std::endl;
							if (element->Name().compare(label))
							{
								return getElementByUID(element->GlobalId());
							}
						}
					}
					
					return nullptr;
				}				
			}
		private:

			std::vector<IfcSchema::IfcBuildingElement*> getBuildingElements(const dataTypes::ElementType& elementType)
			{
				std::vector<IfcSchema::IfcBuildingElement*> elementsList;

				switch (elementType)
				{
				case dataTypes::ElementType::WALL:
				{
					IfcSchema::IfcWall::list::ptr walls = m_ifcFile->instances_by_type<IfcSchema::IfcWall>();
					for (IfcSchema::IfcWall::list::it it = walls->begin(); it != walls->end(); ++it)
					{
						IfcSchema::IfcBuildingElement* element = *it;
						elementsList.push_back(element);
					}
					break;
				}
				case dataTypes::ElementType::SLAB:
				{
					IfcSchema::IfcSlab::list::ptr slabs = m_ifcFile->instances_by_type<IfcSchema::IfcSlab>();
					for (IfcSchema::IfcSlab::list::it it = slabs->begin(); it != slabs->end(); ++it)
					{
						IfcSchema::IfcBuildingElement* element = *it;
						elementsList.push_back(element);
					}
					break;
				}
				case dataTypes::ElementType::COLUMN:
				{
					IfcSchema::IfcColumn::list::ptr columns = m_ifcFile->instances_by_type<IfcSchema::IfcColumn>();
					for (IfcSchema::IfcColumn::list::it it = columns->begin(); it != columns->end(); ++it)
					{
						IfcSchema::IfcBuildingElement* element = *it;
						elementsList.push_back(element);
					}
					break;
				}
				case dataTypes::ElementType::BEAM:
				{
					IfcSchema::IfcBeam::list::ptr beams = m_ifcFile->instances_by_type<IfcSchema::IfcBeam>();
					for (IfcSchema::IfcBeam::list::it it = beams->begin(); it != beams->end(); ++it)
					{
						IfcSchema::IfcBuildingElement* element = *it;
						elementsList.push_back(element);
					}
					break;
				}
				default:
					break;
				}
				
				return elementsList;
			}
			
			IfcUtil::IfcBaseClass* getElementByUID(const std::string UID)
			{			
				return m_ifcFile->instance_by_guid(UID);
			}
			
			double obtainLengthUnit()
			{
				auto unit = m_ifcFile->getUnit("LENGTHUNIT");
				return unit.second;
			}
			
		};

I changed the ifc parser to be in a shared pointer member variable (I originally have it without the pointer)
What I am experiencing in this way is:

- when I call `getElement` using the GUID it works (well, doesn't crush, but the data returned to the main is also empty)
- when I call `getElement` using the ID or looking for the label of the element (like the human readable string i.e wall1, column1, etc) I get a a runtime error in this line: `IfcSchema::IfcBuildingElement::list::ptr elementsList = m_ifcFile->instances_by_type<IfcSchema::IfcBuildingElement>();`
- when I call `obtainLengthUnit` in the constructor it returns the right value and works perfectly

the runtime error I get with `instances_by_type` is: this one
      The thread 0x40c has exited with code 0 (0x0).
      Exception thrown at 0x00007FF67DC00E26 in Project.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
Visual Studio is telling me it happens in _IfcEntityList.h_ in line 49: `for (it i = begin(); i != end(); ++i) if (all || (*i)->declaration().is(U::Class())) r->push((U*)*i);`

This is the status of the variables at crushing point:
![image](https://user-images.githubusercontent.com/82029299/127993156-3d9ff0a0-aa1c-465d-bddc-9f38967726ae.png)

As you can see, all the content inside the main pointers, like fields or subpointers are empty, or cannot load the data (the ones that appear as ????. That is the same behaviour I am experiencing when I was querying the parser with the local variable and the return to the main function.
I am sure I am doing something wrong, but my limited skills don't let me find the problem.

If you (or someone else) can help me it would be amazing.

Thanks

**Comment by aothms** [comment]
IfcParse::IfcFile ifcFile(m_ifcFileName.string());
			m_ifcFile = std::make_shared<IfcParse::IfcFile>(ifcFile);

relies on the copy constructor. we should probably forbid using the copy constructor similar to std::ofstream

for now just change the code to

			m_ifcFile = std::make_shared<IfcParse::IfcFile>(m_ifcFileName.string());

In this case it's ]not necessary to use a shared ptr, but it doesn't significantly hurt

**Comment by Fleakad** [comment]
Thanks a lot @aothms!! now it works properly
I am closing the issue
