### ISSUE TITLE
Alternative ways to calculate clear opening width

### ISSUE THREAD

**Issue by greeshmaunni1990** [IfcOpenShell/IfcOpenShell#1629]
I am implementing code where it requires to calculate the clear opening width of doors and doorways. I was taking the panel width from IfcDoorPanelProperties to calculate clear width. But most of the files I am working with is returning panel width as None. Is there any alternative methods to calculate clear opening width?

**Comment by aothms** [comment]
The OverallWidth on window/door/opening is quite reliably present I think. Then you just need an approach for the frame width.

A geometric approach looking at the dimensions of the largest face in the door geometry I think can also be quite reliable. (perhaps use OpenCascade UnifySameDomain first)

**Comment by greeshmaunni1990** [comment]
Thank you.
Is calculating the BREP shape of the door be a correct approach?

**Comment by aothms** [comment]
That's what I suggested with 

> A geometric approach looking at the dimensions of the largest face in the door geometry I think can also be quite reliable. (perhaps use OpenCascade UnifySameDomain first)

Whether you favour semantics (property sets) or geometry is mostly a personal preference

**Comment by greeshmaunni1990** [comment]
Thank you for the response

**Comment by Moult** [comment]
Closing as question answered.
