### ISSUE TITLE
Wall geometry sticking out - again

### ISSUE THREAD

**Issue by larsmoa** [IfcOpenShell/IfcOpenShell#163]
This issue looks very much like #6 (although it does not seem to be a regression as I am able to convert the file in #6 without problems with the latest revision). Is this some other problem related to fuzzy boolean operations?

File [Wall.ifc.gz](https://github.com/IfcOpenShell/IfcOpenShell/files/603235/Wall.ifc.gz) is converted successfully, but the result includes a wall that is not visible in other IFC viewers (see screenshots below). The wall doesn't have any thickness - it seems only one side of the wall is writtent to the result.

From IfcOpenShell:
![image](https://cloud.githubusercontent.com/assets/6741854/20478405/3696e904-afda-11e6-84c5-12c242de32cc.png)

From Solibri Model Viewer:
![image](https://cloud.githubusercontent.com/assets/6741854/20478412/3f2f045c-afda-11e6-88f3-0ef221b2d0ab.png)

**Comment by aothms** [comment]
Actually Solibri also does not come to a valid solution, if you observe carefully there is a large gap in the mesh.

![solibri_gap](https://cloud.githubusercontent.com/assets/1096535/21073457/efb9c358-bede-11e6-8d55-658d71afa732.png)

The reason for this is an incredibly narrow subtraction operand (0.4 mm wide), polyline provided below.

~~~
#1942 = IFCPOLYLINE((#1914, #1943, #1944, #1945, #1946, #1914));
#1914 = IFCCARTESIANPOINT((0., 0.));
#1943 = IFCCARTESIANPOINT((0., 4.30640639432568E-1));
#1944 = IFCCARTESIANPOINT((-200., 4.30640639432568E-1));
#1945 = IFCCARTESIANPOINT((-2959.99147151655, 4.30640639432568E-1));
#1946 = IFCCARTESIANPOINT((-2959.99147151654, 0.));
~~~

Now technically this should actually work, 0.4mm within the modelling tolerance specified in the file (0.01mm). But it seems Open Cascade (and Solibri) get confused on what is inside and outside when applying the subtraction.

I can only fix this with a small hack. For this particular subtraction operand (`IfcPolygonalBoundedHalfSpace`) I have increased the tolerance by which the polyline gets discarded and only the first operand is returned. I.e. you will get several errors for this file now, but the result will be correct:

~~~
[Error] {30j8mchHX2IAUgufZb6e_N} Not enough points retained from:
#1942=IfcPolyline((#1914,#1943,#1944,#1945,#1946,#1914))
[Error] {30j8mchHX2IAUgufZb6e_N} Failed to convert:
#1937=IfcPolygonalBoundedHalfSpace(#1938,.F.,#1941,#1942)
[Error] {30j8mchHX2IAUgufZb6e_N} Failed to convert SecondOperand of:
#1917=IfcBooleanClippingResult(.DIFFERENCE.,#1918,#1937)
~~~

**Comment by larsmoa** [comment]
Thank you! :) I will test the new revision next week.
