### ISSUE TITLE
Sample python code for export IFC file.

### ISSUE THREAD

**Issue by tsubasa-kennedy** [IfcOpenShell/IfcOpenShell#1634]
this is not a issue, but i need your help...

(what i want to do)
Windows 10(x64), Blender(for Windows) and BlenderBIM.
3D file format conversion by using NOT blender GUI but pythons script only, such as (import STL file) -> (export IFC file).
I have no idea how to implement python code for this conversion ..

i found this url site, https://blenderbim.org/blenderbim-tutorial.html
and have confirmed this on blender GUI.

please advise to me if there is any sample python code.

**Comment by Moult** [comment]
It sounds like you're doing something similar to https://github.com/IfcOpenShell/IfcOpenShell/issues/1632 - I'm curious what this is part of?

Although using Blender is possible in background mode, it's probably completely unnecessary. There are STL libraries (here's the top hit on duckduckgo: https://pypi.org/project/numpy-stl/) which you can use, then use the ifcopenshell.api to create the IFC file. It would be very welcome to add an stl-based add_representation usecase. The more geometry engines we can create adaptions of add_representation for, the better!

**Comment by tsubasa-kennedy** [comment]
ok, i'm not persist to whether background mode or not, but i can understand import IFC.
as the bigger problem for me, i need sample python code how to use export IFC. thanks !

**Comment by Moult** [comment]
@tsubasa-kennedy exporting IFC is not a straightforward exercise. IFC is not just a geometry container like most other formats. Indeed, it contains geometry, but also a lot of metadata that you need to make decisions on. This is beyond the scope of a bugreport to go through unfortunately.

That said, a good place to start is https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples and then watch this video too: https://www.youtube.com/watch?v=h2Rv9iu7yDk

In the second half of the video, 15 lines of API code is given as an example of how to create a new IFC file code with pure Python. You can use this as a starting point to learn. Also feel free to reach out on https://community.osarch.org/ with any further detailed programming questions you might have - including code of what you've tried already, where it worked, where it didn't, and so on.

Hope it helps :)

**Comment by tsubasa-kennedy** [comment]
thank you very much.
it may be so difficult for me to understand export IFC, but i will try it.
