### ISSUE TITLE
BlenderBim cannot create SVG

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#1636]
![image](https://user-images.githubusercontent.com/78321676/128772724-4c4dc968-e6f8-4118-8a4f-75cbe2bae76e.png)
the above error appears when attempting to create a drawing

**Comment by Moult** [comment]
Drawings are a work in progress but as a quick fix just change line 274 to read "bpy.context" instead of just "context".

**Comment by Plae-Blue-Dot** [comment]
Thanks @Moult I have attempted that and it seemed to work however it gives another error:
![image](https://user-images.githubusercontent.com/78321676/128821248-3427bee2-db87-4b58-9072-f01c472d2e9d.png)
No stress I can wait for it, I just thought since the new drawing operator is in I could give it a spin.

**Comment by Moult** [comment]
@Plae-Blue-Dot actually the new drawing operator code is there, but not yet exposed to users - because right now it relies on a v0.7.0 build which has a few steps to swap in and out: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/module/drawing/operator.py#L237-L240

Might have to wait a while longer. Your second error however seems unrelated, it seems to do with your SVG command preferences in the addon preferences. What have you got it set to? Try clearing that preference entry.

**Comment by Plae-Blue-Dot** [comment]
Ahh it worked! You were right. So we are actually still using the old drawing operator? alright I'll leave it till v0.7.0

**Comment by Moult** [comment]
Sort of - using a half new, half old operator :)

**Comment by Plae-Blue-Dot** [comment]
So things are changing fast. but here is a fairly large issue not certain if it is just user error
I've attempted to recreate it every day for the last 3 days,

Attempted native authoring:
1 - I always start by loading a png to trace
2 - Create IFC file + save
3 - Load elements from the IFC library to use
4 - Draw walls, doors and windows using the BIM tool, sometime just scaling them



1) The walls only show their original size + position in SVG

model:
![image](https://user-images.githubusercontent.com/78321676/140394138-edb0d14b-7f6e-454f-b531-8b82013a4992.png)

svg:
![image](https://user-images.githubusercontent.com/78321676/140393544-f3ea51c3-7924-4adc-8c7a-a7a12d8536ec.png)


2) When it does display the walls properly (I don't load a png to trace), the door swings 2d representation no longer displays (I'm using the door from the IFC library)

model:
![image](https://user-images.githubusercontent.com/78321676/140395211-e757a30d-6f09-45e3-bebe-5b21e7777afa.png)

svg:
![image](https://user-images.githubusercontent.com/78321676/140395050-f480952e-6f00-4d2b-a1eb-0dd15f944b30.png)


3) The material no longer changes when renamed? (Does the new system just work differently?)
model (concrete IFC material is selected + blender material named concrete): 
![image](https://user-images.githubusercontent.com/78321676/140396210-33543b62-856a-4452-8aec-c5cef2d30542.png)

SVG (Wall still displays as black): 
![image](https://user-images.githubusercontent.com/78321676/140395898-34c3228a-c689-4843-abb4-a687b873fc8c.png)

**Comment by Moult** [comment]
1. This is because I'm still halfway implementing geometry caching. Not yet publicly committed.
2. Same - working locally, still WIP.
3. Same - working locally, still WIP.

I'm waiting for a few bugs to get sorted out on the C++ side with a new bot build then I can release code.

**Comment by Plae-Blue-Dot** [comment]
@Moult Ahhh got it, epic. I'll continue to send in when I find new stuff

**Comment by Moult** [comment]
I was wrong about (2) - that is because the door in the library doesn't have a door swing. Will fix.

**Comment by Moult** [comment]
Try again now? :)

**Comment by Plae-Blue-Dot** [comment]
@Moult It works!
![image](https://user-images.githubusercontent.com/78321676/140870238-16a05c28-b298-4a9c-8c50-014d0da94929.png)

**Comment by Plae-Blue-Dot** [comment]
Issue with cutting representation with window Boolean:
Model:
![image](https://user-images.githubusercontent.com/78321676/141737643-fdd5ebea-7dc2-4f37-9338-9b400a0d6d64.png)
SVG
![image](https://user-images.githubusercontent.com/78321676/141737698-30aa7fa9-e49e-4240-8757-1d373240de06.png)

Using: blenderbim-211114-py39-win

On the bright side the transform issue with the tracing images seems to be gone!

Model:
![image](https://user-images.githubusercontent.com/78321676/141738736-a69d4c9f-0d7d-4f36-ab82-380618c1e4e8.png)
SVG:
![image](https://user-images.githubusercontent.com/78321676/141738779-4205f3d7-0382-438b-a95b-41af38566e23.png)

**Comment by Moult** [comment]
I just tested windows and it works for me. How can I replicate your issue?

**Comment by Plae-Blue-Dot** [comment]
I've tried it with another PC was able to replicate it and realised the issue is my project units being set to mm not metres. For some reason it messes with the svg?

Once I used metres it displayed as expected:
![image](https://user-images.githubusercontent.com/78321676/141748563-f7e44ccf-2664-4058-8e95-63410af7227f.png)

The process for both was the same:
1. Create IFC project
2. Load Library
3. Make wall
4. add door & window
5. add and scale camera/drawing
6. create svg

**Comment by brunopostle** [comment]
> Once I used metres it displayed as expected:

Possibly this is the wrong place to note this: the default height for sectioning windows appears to be 1m above floor level, but kitchen window cills are often higher than this, so they don't display in the plan. 1.2m would be a better default

**Comment by aothms** [comment]
> Possibly this is the wrong place to note this

I indeed don't think BlenderBIM uses the IfcOpenShell serializer defaults

> 1.2m would be a better default

I've heard that before. Feel free to make the change in SvgSerializer.h setSectionHeightsFromStoreys(offset=...) and the help text in IfcConvert.cpp

**Comment by Moult** [comment]
Yeah the BlenderBIM Add-on actually uses 1.5m as the default cut plane. That reminds me, also the wrong place to discuss, but @aothms what might be the process to implement the equivalent of what Revit calls a "Plan region"? https://knowledge.autodesk.com/support/revit/learn-explore/caas/CloudHelp/cloudhelp/2021/ENU/Revit-DocumentPresent/files/GUID-231E2653-8369-4F02-A78E-8A66AF4E4CEE-htm.html

@Plae-Blue-Dot I really appreciate your help debugging and I struggled to replicate the issue exactly but I think you're right that it was due to a unit conversion bug - which has deeper implications than drawings so it's good that it's caught! These two commits should make things smoother:

 - https://github.com/IfcOpenShell/IfcOpenShell/commit/ddb8abff0f2d9c1b662830add1e7e2d5eb53b54b
 - https://github.com/IfcOpenShell/IfcOpenShell/commit/18719c16dfb569293771e7bcf9d36f762d090db0

**Comment by aothms** [comment]
> Plan region

That'd bascially be a more advanced shape to feed in the `should_cut` logic. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/SvgSerializer.cpp#L1010

![afbeelding](https://user-images.githubusercontent.com/1096535/142158088-627372f0-3f0f-4964-a402-1d667240dcec.png)

The question is what to in a situation above where both cut planes (or one of them) partly intersects with the building element. We can create a face between the regions R0 R1 but this will create artefacts. Is it an option to think about the region as a set of elements, and then still in serializer code compute bounding boxes to cover those elements? I can see some issues though with long elements that extend in both regions.

**Comment by Plae-Blue-Dot** [comment]
> @Plae-Blue-Dot I really appreciate your help debugging and I struggled to replicate the issue exactly but I think you're right that it was due to a unit conversion bug - which has deeper implications than drawings so it's good that it's caught! These two commits should make things smoother:
> 
> * [ddb8abf](https://github.com/IfcOpenShell/IfcOpenShell/commit/ddb8abff0f2d9c1b662830add1e7e2d5eb53b54b)
> * [18719c1](https://github.com/IfcOpenShell/IfcOpenShell/commit/18719c16dfb569293771e7bcf9d36f762d090db0)

It seems that's fixed it! New project in millimetres comes out correctly (blenderbim-211117-py39-win):

![image](https://user-images.githubusercontent.com/78321676/142159220-4cabba00-af56-4855-9d80-c8c2825e422d.png)

**Comment by Plae-Blue-Dot** [comment]
Issue with moving window and updating boolean cut in svg (blenderbim-211118-py39-win):

Original position svg:
![image](https://user-images.githubusercontent.com/78321676/143678165-017517d1-d959-4d40-8b5c-2080ae1e5fb8.png)

Moved model position:
![image](https://user-images.githubusercontent.com/78321676/143678172-d9214c1c-34ff-4c7f-b47d-6eefbd586fe8.png)

New svg (boolean cut representation hasnt moved)
![image](https://user-images.githubusercontent.com/78321676/143678180-93e65e24-363f-447a-aa1e-cd396b511726.png)

**Comment by Plae-Blue-Dot** [comment]
issue with Window scaling:

For some reason when exporting to Ifc or printing/creating drawings, the scaled window returns to its previous size, 
model scaled window:
![image](https://user-images.githubusercontent.com/78321676/143678393-2a676558-262d-4927-bd14-5ce4e00ba2cb.png)
Model once drawing is created:
![image](https://user-images.githubusercontent.com/78321676/143678410-dd0353ab-0fe6-4872-afab-1fc99ea2b32d.png)
SVG:
![image](https://user-images.githubusercontent.com/78321676/143678432-ae09727a-526b-4e9f-983f-1c510bba22a0.png)

**Comment by Moult** [comment]
This is on purpose, it has detected that the object is scaled, whereas the original IFC type is not scaled, and has fixed the discrepancy. Basically you should never be scaling in object mode.

**Comment by Plae-Blue-Dot** [comment]
I see, when you edit in edit mode it changes the instance of the window, 

even then it wouldn't reflect because the 2d representation would need to be updated as well, 
Model:
![image](https://user-images.githubusercontent.com/78321676/186106918-84b49a5b-3b03-48c1-ab85-841a77bd9cea.png)

SVG:
![image](https://user-images.githubusercontent.com/78321676/186106940-1ffbbd79-a4cb-44c1-8a69-5f936c0a19bc.png)

thanks for coming back to it Moult

**Comment by Moult** [comment]
I think this is now fixed.

**Comment by Plae-Blue-Dot** [comment]
With the new boolean system and regen updating the openings does work, thanks Moult
