### ISSUE TITLE
Blender ID collision for bim.assign_resource and bim.unassign_resource

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1637]
Ping @myoualid both resource/operator.py and sequence/operator.py have a bim.assign_resource and bim.unassign_resource. There can only be one. My advice is to rename the sequence/operator.py one to something else, since technically it is a variation of assign_process.

Currently because they collide it causes an error when unregistering modules.

**Comment by myoualid** [comment]
You're right - since it's a variation of assign_process: 
- duplicate classes within sequence/operator are now deleted
- code is now incorporated within bim.assign_process and bim.unassign_process of sequence/operator.py

**Comment by myoualid** [comment]
See commit [ca20d94](https://github.com/IfcOpenShell/IfcOpenShell/commit/ca20d94d66e48c037a0e6bf30bf161bacfb98655)
