### ISSUE TITLE
get location from IfcObjectPlacement

### ISSUE THREAD

**Issue by Fleakad** [IfcOpenShell/IfcOpenShell#1638]
I am trying to get the location of the different elements I have in an IFC file.
Once I get the element I want (i.e wall, slab, column, etc), I think that the placement/location is coming using ```element->ObjectPlacement()```, is that right? (I am checking if it has an object placement before hand, just in case)

in case that is ok (which seems it is as I can print the data inside the ```IfcObjectPlacement``` and looks like the data I need), how do I get the data inside it?

the print of the object placement returns a  _#818=IfcLocalPlacement(#149,#817)_ , which is the data I want, but then when I want to access to data inside ```#818```, I cannot get anything.

inside ```IfcObjectPlacement``` I can only access ```objectPlacement->PlacesObject()``` and ```objectPlacement->ReferencedByPlacements()```. The later returns a list of size 0, and the first one returns a list with 1 element which is the original element  (a wall in this case _#847=IfcWall('1JMjYabfzCH9po57TAAhNT',#42,'Wall1',$,'Basic Wall:Wall-Ext_102Bwk-75Ins-100LBlk-12P',#818,#843,'320381',.NOTDEFINED.)_ )

I tried to cast the data using the ```.as<>``` method into a local placement, axis2placement2d, axis2placement3d, gridplacement, but all of those casts fail so I cannot get the data.

I tried with other elements in the IFC, just in case this one was generated wronly, but no luck.

Can you tell me if I have a problem in the IFC file, or I am doing something wrong to access the data I want to get?

**Comment by aothms** [comment]
> local placement

99.99% of the cases is IfcLocalPlacement, are you sure this is not the case? Except for infra which uses IfcLinearPlacement, IfcGridPlacement I have only ever seen in the official buildingsmart example for it.

> I tried to cast the data using the `.as<>` method into a local placement, axis2placement2d, axis2placement3d, gridplacement, but all of those casts fail so I cannot get the data.

`.declaration().name()` will give you the concrete type name.

You can also defer the calculation to IfcOpenShell, which has the additional advantage that it will take care of the recursive nature of IfcLocalPlacement.

```
IfcGeom::Kernel kernel(f);
gp_Trsf trsf;
if (kernel.convert_placement(*product->get("ObjectPlacement"), trsf)) {
    // do something
}
```

This will get you a opencascade transformation object https://dev.opencascade.org/doc/occt-6.9.1/refman/html/classgp___trsf.html

**Comment by Fleakad** [comment]
I don't seem to have the option to obtain the local placement from the IfcObjectPlacement
this what it is contained in the object:
![image](https://user-images.githubusercontent.com/82029299/128856171-275803a6-6f40-4cf4-ad88-f66471f5f4db.png)

I have no luck with the caster, it returns an empty pointer, and the ```.declaration().name()``` from the IfcObjectPlacement returns and IfcObjectPlacement.

but....
are you telling me IfcOpenShell can handle all the recursive problems of reading an IFC file? I would need to do it with to obtain the coordinates of the elements and the shape of it, if that can be done automatically with the library it would be great.

what is the ```f``` inside the kernel declaration?

**Comment by aothms** [comment]
>  are you telling me IfcOpenShell can handle all the recursive problems of reading an IFC file? I would need to do it with to obtain the coordinates of the elements and the shape of it, if that can be done automatically with the library it would be great.

This is one of the main purposes of IfcOpenShell. Have a look at what IfcConvert does. It uses IfcGeom::Iterator to loop over all geometric objects and dump their coordinates.

> I don't seem to have the option to obtain the local placement from the IfcObjectPlacement

> I have no luck with the caster, it returns an empty pointer, and the .declaration().name() from the IfcObjectPlacement returns and IfcObjectPlacement.

That would be very odd. IfcObjectPlacement is an abstract class. Perhaps there is something wrong with your file.

> I tried to cast the data using the `.as<>` method into a local placement, axis2placement2d, axis2placement3d, gridplacement, but all of those casts fail so I cannot get the data.

Just another thought. .as<> is early bound so you need to use the correct schema there.

> what is the f inside the kernel declaration?

f -> IfcParse::IfcFile*

product -> IfcBaseEntity* of type IfcProduct

**Comment by Moult** [comment]
A very minor comment just in case that if your task could use Python instead, the Python bindings also have this capability (i.e. recursive resolution of various things). If not, feel free to ignore :)

**Comment by Fleakad** [comment]
> 
> 
> A very minor comment just in case that if your task could use Python instead, the Python bindings also have this capability (i.e. recursive resolution of various things). If not, feel free to ignore :)

sadly no, I have to use C++ for this one.

thanks @aothms. using the IfcGeom gave me the location that I needed.

Now I have to try to get the shape (or the vertices coordinates). I will have a look. By any change, is it something similar as the location?

Is there any place with examples or explanation of how to use the library? I was doing it everything doing the iteration by myself and computing all the transformations (which is not the best option) as I didn't know it can be done by the library automatically.

**Comment by aothms** [comment]
IfcConvert.cpp was once intended as documentation of how to use the library, but it completely grew out of hand into a useful application with a ton of options so it isn't as readable anymore.

An additional complication is that, for the date model of geometry, IfcOpenShell is a pretty thin wrapper around Open CASCADE, which is in itself a really complex library with impenetrable documentation. 

The question you're asking is a also a bit harder due to complexity of the IFC schema. An element can have multiple representations. 

Using this same IfcGeom::Kernel

You can do something like this. 

```
// from your own code
IfcUtil::IfcBaseEntity *product, *representation;

// conversion settings
IfcGeom::IteratorSettings st;
// return OpenCASCADE shape
st.set(IfcGeom::IteratorSettings::DISABLE_TRIANGULATION, true);

// convert
auto elem = kernel.convert(st, representation, product);

// flatten into compound
auto compound = elem->geometry().as_compound()
    // move into position, multiple elements can share geometry with different placement
    .Moved(elem->transformation().data());

// explore vertices and print point
// from here on it's solely OpenCASCADE
TopExp_Explorer exp(compound, TopAbs_VERTEX);
for (; exp.More(); exp.Next()) {
	auto P = BRep_Tool::Pnt(TopoDS::Vertex(exp.Current()));
	std::cout << P.X() << " " << P.Y() << " " << P.Z() << std::endl;
}
```

Hope that helps.

**Comment by Fleakad** [comment]
really thank you a lot @aothms 
I think that is what I need. Just to make sure I understand it properly, ```product``` and ```representation``` would be:
```IfcSchema::IfcWall wall``` <- wall element read from the IFC file
```IfcSchema::IfcRepresentation representation = wall.getRepresentation()``` <- representation inside the wall

Or I am getting it wrong.

I tried that way, and ```elem``` is a null pointer, so I guess that it is not what it is expecting

**Comment by aothms** [comment]
`getRepresentation()` probably doesn't exist. You need to find an actual IfcRepresentation. I think you can typically use `kernel.find_representation(wall, "Body")`

**Comment by Fleakad** [comment]
Got you!
That method doesn't exist, but I fixed it iterating inside the ```wall.Representation()``` list and using each element inside it.

Thanks a lot for your valuable help. It saved me uncountable hours of suffering dealing with the IFC

**Comment by aothms** [comment]
> Thanks a lot for your valuable help. It saved me uncountable hours of suffering dealing with the IFC

No problem. I'm in the process of converting the old academy.ifcopenshell.org to a new static system using markdown for posts. If you ever feel like writing down your experiences in a tutorial so others can also benefit that would be greatly appreciated. https://github.com/IfcOpenShell/academy/tree/main/posts Especially C++ content is still pretty rare unfortunately.

**Comment by Fleakad** [comment]
Hi, sorry for the very late response, I have been on holidays.
I will take a look at that. Would be happy to collaborate in anything that I can. I am unsure if I can help much explaining how to use the library, just really did some basic things, but no problem to do it
