### ISSUE TITLE
AttributeError: 'list' object has no attribute 'is_a'

### ISSUE THREAD

**Issue by gverhaar** [IfcOpenShell/IfcOpenShell#164]
I am trying to using the following code to traverse through the structure and learn about names and options:

```python
products = ifc_file.by_type("IfcProduct")
for product in products:
    element = product
    for attr in range(len(element)):
        print " : ".join((element.is_a(), str(attr), element.attribute_name(attr), str(element[element.attribute_name(attr)])))  

element = ifc_file.by_type("IfcPolyline")
for attr in range(len(element)):
    print " : ".join((element.is_a(), str(attr), element.attribute_name(attr), str(element[element.attribute_name(attr)])))  
```

For IfcProduct this works ok, but for IfcPolyline I get the error:
`AttributeError: 'list' object has no attribute 'is_a'`

Any reason why not all fields have attribute_name?

(I need to grab the Polyline (including IfcCartesianPoints) that belong to a IfcReinforcingBar)

**Comment by aothms** [comment]
`ifc_file.by_type("IfcPolyline")` returns a list of IfcPolyline instances which you store in `element`. `element.is_a()` is therefore raising the error. Also, use the named attributes [1] for clarity.

~~~
for ln in ifc_file.by_type("IfcPolyline"):
  print ln
  for pt in ln.Points:
    print pt.Coordinates
~~~

This is not likely going to be a complete solution. You will probably need to start at the `IfcReinforcingBar`s themselves and descend into the graph structure to apply the transformation on an element level `IfcReinforcingBar.ObjectPlacement` and geometrical level in `IfcSurfaceCurveSweptAreaSolid.Position` (depending on what exact geometrical representation items are used to represent the element).

[1] http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcgeometryresource/lexical/ifcpolyline.htm
