### ISSUE TITLE
BlenderBIM: applying an IFCMaterial directly or through a ifcmateriallayerset should also apply the associated blender material to the object. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1640]
Similar to #1585 
I feel UI-wise, applying an IFCMaterial directly or through a ifcmateriallayerset should also apply the associated blender material to the object. 
https://www.dropbox.com/s/q6xrqe9ow3adwdx/BB-color-ifcwalltype2021-08-10_21-36-58.mp4?dl=0

**Comment by theoryshaw** [comment]
When wall is spawned, the wall does not take on the Blender material. 
Only when you massage the width, does it take on the Blender material. 
---
BTW, would it be possible to give me Github permissions to reopen issues? Peace.

![2021-08-15_10-15-22](https://user-images.githubusercontent.com/507113/129483403-dd668814-f92a-4840-be45-20ba2681d9ee.gif)

**Comment by Moult** [comment]
Sorry @theoryshaw I need some guidance on how to recreate this. Any step by step?

**Comment by Moult** [comment]
Bump? Ping @theoryshaw

**Comment by theoryshaw** [comment]
Looks like this was fixed somewhere along the way.  Sorry for the delay, took some time getting my head back into this issue.
