### ISSUE TITLE
BlenderBIM: profile manager and editor

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1641]
from: https://community.osarch.org/discussion/691/blenderbim-assign-a-ifcarbitraryclosedprofiledef-to-a-ifcmaterialprofileset

@Moult said...

> _In short, we need to build a little profile manager first, similar to how Revit or other BIM programs have profiles. Maybe add a bugreport for this, since it's been on the to-do list for a while since we discussed with @Jesusbill way back that it is also super useful for structural._

**Comment by theoryshaw** [comment]
This might be a tall order, but would be nice if this 'profile editor' would happen in the particular blender view that the extrusion cuts though.  That way, while editing the profile, you can snap to other things in the scene. Editing a profile, in scene, is more helpful sometimes than pulling that profile out into an editor that's dissociated, spatial, with other objects around it.

**Comment by MarcelP102** [comment]
Look at the Blender add-on called Grid Modeler for inspiration. Similar grid protected in the context would be helpful to sketch the profile as @theoryshaw suggested.

**Comment by Moult** [comment]
It's doable, but would require a bit of "reverse engineering" code - code that intelligently converts meshes into parameterised curves or profiles.

**Comment by theoryshaw** [comment]
Just learned about https://github.com/hlorus/geometry_sketcher from [this](https://community.osarch.org/discussion/719/cad-add-on-in-blender-and-other-useful-add-ons) conversation.

seems pretty awesome. 

Seems like it could be a good candidate for the foundation of the profile editor. 

video demo: https://twitter.com/hlorus1/status/1438913270098939904

**Comment by Moult** [comment]
100% agree!

**Comment by theoryshaw** [comment]
related, perhaps: https://community.osarch.org/discussion/810/bb-having-geometry-sketcher-act-as-the-in-world-interface-for-ifcprofiledef/

**Comment by theoryshaw** [comment]
related: https://github.com/hlorus/geometry_sketcher/issues/14

**Comment by Moult** [comment]
This has now been implemented.

> This might be a tall order, but would be nice if this 'profile editor' would happen in the particular blender view that the extrusion cuts though.

This is also possible (but not yet exposed in the UI, pending a redesign to make profile editing not limited to structural elements). If you edit a profile in the profile manager, it'll appear at the origin, isolated from everything. If you edit a profile with an active object selected that uses the profile, the profile will appear "in-place" which you can then use the snap to things in the scene. You can trigger the `enable_editing_extrusion_profile` operator manually for now because it's hidden in the UI.
