### ISSUE TITLE
Can create_shape work on profiles?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1649]
Ping @aothms :) For now, create_shape only processes representations, but it would be good to also process profiles. This would allow us to build a graphical profile editor without first creating "dummy" or "placeholder" representation items.

**Comment by aothms** [comment]
good idea, closed via https://github.com/IfcOpenShell/IfcOpenShell/commit/4cb59009b4bd239c4ec5bb70ecb905e0dbe25409
