### ISSUE TITLE
Can IfcOpenShell return information for Bending Shapes?

### ISSUE THREAD

**Issue by gverhaar** [IfcOpenShell/IfcOpenShell#165]
I am trying to understand if IfcOpenShell could help me to grab  the Bending Shapes from the IFC file.

I know the information is stored in the IFCPOLYLINE with corresponding IFCCARTESIANPOINTs
```
95= IFCPOLYLINE((#97,#99,#101,#103,#105,#107,#109,#111,#113,#115,#117));
#97= IFCCARTESIANPOINT((0.,0.,0.));
#99= IFCCARTESIANPOINT((982.116098092115,0.,0.));
#101= IFCCARTESIANPOINT((985.806272277749,0.,0.1737379990727277));
#103= IFCCARTESIANPOINT((989.5074251916399,0.,0.5718208697235241));
#105= IFCCARTESIANPOINT((993.1767690911661,0.,1.198652753820625));
#107= IFCCARTESIANPOINT((996.7726992359726,0.,2.0444504226557));
#109= IFCCARTESIANPOINT((1000.309764926028,0.,3.109933227386136));
#111= IFCCARTESIANPOINT((1003.800925900287,0.,4.401752841619327));
#113= IFCCARTESIANPOINT((1007.205259782333,0.,5.907579419769718));
#115= IFCCARTESIANPOINT((1010.487913371018,0.,7.602204991786948));
#117= IFCCARTESIANPOINT((1428.012701892219,0.,248.6602540378444));
```

I need to convert this to Vector Information in order to import this with a BVB file
> VectorData:1000,A-30,500

(meaning: line of 1000 then bend of 30º then line of 500)

Any help/information is much appreciated. Does IfcOpenShell have functions that can return this information? 

PS: I am working in Python

**Comment by aothms** [comment]
Hi,

There is nothing directly implemented for this purpose. Your options are:
* to use the parser to iterate over the polyline points and do the math yourself
* to use pythonOCC, which might be a bit overkill for this purpose, some pointers below:

Create a topological wire from the polyline:
~~~
import ifcopenshell.geom
s = ifcopenshell.geom.settings()
s.set(s.USE_PYTHON_OPENCASCADE, True)
s.set(s.INCLUDE_CURVES, True)
ifcopenshell.geom.create_shape(s, ifc_file[95])
~~~

Then the following classes and methods can help to proceed

* `OCC.BRepTools.BRepTools_WireExplorer` to explore edges of the wire in order
* `OCC.BRep.BRep_Tool.Curve` to obtain a curve for each edge
* `OCC.Geom.Handle_Geom_Line.DownCast` to cast this curve to a line (`Handle_Geom_Line`)
* `handle_geom_line_instance.GetObject().Location().Direction()` to get a direction (`gp_Dir`) for this line
* `gp_dir_instance.AngleWithRef()` to get the signed angle with the previous edge curve direction vector and reference direction (positive Z = `OCC.gp.gp_DZ()`)



Hope that helps,

Kind regards,
Thomas
