### ISSUE TITLE
IFCMaterialLayerSetUsage

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#1650]
![layerset error](https://user-images.githubusercontent.com/79401028/129447683-b67e5ae4-a3c6-488a-a258-e1758c0e58fc.JPG)

With BlenderBIM 0.210801 appear this error when i'm trying to set layer thikness in IfcMaterialLayerSet

**Comment by Moult** [comment]
This has been fixed. Wait for tomorrows build and try again with tomorrow's github build.
