### ISSUE TITLE
BlenderBIM: suggested UI on differentiating type and instance parameters of an IfcMaterialLayerSet. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1651]
It seems you can change the thickness, for example, of a layer set when an instance is selected. and it doesn't change the type thickness--which is a confusing UI.

It seems like the IfcMateralLayerSet attributes should be hidden (or visually frozen) when a instance is selected, and a user can only change it via the type element. 

Or checkbox that you have to toggle on to really make sure you know that you're instance parameters are overriding the type parameters.

**Comment by Moult** [comment]
An instance should rarely have an IfcMaterialLayerSet. It should in 99% of cases have an IfcMaterialLayerSetUsage, which points to the type's IfcMaterialLayerSet. Therefore, it should change the type's IfcMaterialLayerSet thickness.

If this is not the case, let's screenshare and let me see what's actually happening.

**Comment by Moult** [comment]
Bump?

**Comment by theoryshaw** [comment]
Hi.. sorry, life. :)

video: https://www.dropbox.com/s/fxxmek934n46g7o/2021-09-09_12-18-29.mp4?dl=0

In the first part of the video I change the type's thickness. Awesome. 

In the latter part, I change the instance's thickness, and the type thickness changes.

I guess it's somewhat a confusing UI.  I guess I would expect that i could not change the type thickness by selecting the instance.

Relatively minor UI observation.

**Comment by Moult** [comment]
Yeah I guess this is a UX thing - it is working as intended and this is how IFC works. As long as an instance is part of a type, it always references the types layer settings - you're never changing the instances thickness. The indicator for this is that the instance has the name "IfcMaterialLayerSet**Usage**", which means that it **uses** the layer set of the type.

This is also how it works in Revit, isn't it? You never really edit the wall's layers, you edit the wall type's layers.
