### ISSUE TITLE
BB: support copy and pasting from one file to another

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1654]
I'm sure this is a tall order, but logging here to track nonetheless, for discussion and roapmapping.

Copying and pasting content from one project to another is a frequent workflow in any BIM app, would be ideal if BB supported this as well some day.

**Comment by Moult** [comment]
Imagining we were able to track the originating IFC file's location, a copy and paste would need to load the other IFC file prior to pulling in any data. In short, this would mean as soon as you press ctrl-v, your computer could very well hang for 5-20 seconds (at least the first time) which is a pretty poor experience.

A nicer solution would be the decouple the IfcStore from the Blender process, so multiple Blenders could access it simultaneously. This is similar to how multiuser might work.

Just thinking out loud. No solutions yet.

**Comment by theoryshaw** [comment]
> Just thinking out loud. No solutions yet.

Any revelations, as of late? :)

**Comment by Moult** [comment]
Closing as copy pasting now implements virgin Blender geometry, and there is also now the visual append from linked model function.
