### ISSUE TITLE
BB: IFC CSV Export should not fail with 'Unable to parse IFC SPV header'

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#1659]
I have created a "simple" model with Archicad 25 and exported it as an IFC4 RV file.

When trying to create a CSV file with BlenderBIM (blenderbim-210816-py39-macos) ,
the error 'Unable to parse IFC SPV header' is displayed.

No CSV file is created.

[SimplyTwoRooms ARC -- IFC4 RV BIMvs.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6991326/SimplyTwoRooms.ARC.--.IFC4.RV.BIMvs.ifc.zip)

![Bildschirmfoto 2021-08-16 um 11 05 04](https://user-images.githubusercontent.com/1941141/129544194-f1138684-5ff8-41f5-bc13-5acdd8ec4837.png)

**Comment by Moult** [comment]
@kurb70 your selector needs to be `.IfcWall` (there should be a `.` symbol to select classes).

**Comment by kurb70** [comment]
Unfortunately, specifying ".IfcWall" does not change anything.
The same error message appears.

This message also appears if I do not specify an IFC selector.

For me, the error message also points to another problem. The information in the header of the IFC file seems to be the problem.
![Screenshot 2021-08-19 at 10 52 11](https://user-images.githubusercontent.com/1941141/130040255-41aa7bbe-25df-4a71-9476-5cafe5abbab4.png)

**Comment by Moult** [comment]
In that case, it is perhaps specific to your file. Can you send me your file to test with? Or at least copy paste your header in text form here so I can try to replicate it?

**Comment by kurb70** [comment]
I have noticed that you have published a model at https://github.com/Moult/blenderbim-demo-house/blob/master/house.blend. 

The CSV export does not work with this model either. The error message "Unable to parse IFC SPV header" appears again.

**Comment by kurb70** [comment]
BTW My IFC4 file is attached to my initial comment.

**Comment by Moult** [comment]
@kurb70 that house model is ancient and is not an IFC. If you are able to get an IFC out of it, that suggests that you may be using an older version of the BlenderBIM Add-on, or an older version of IfcOpenShell. I have tested with your model and it indeed works fine on my machine.

What happens if you try with a fresh Blender add-ons directory (i.e. clear everything (make a backup) and reinstall from the web.

If still stuck, happy to screenshare on the OSArch.org live chatroom to debug :)

**Comment by kurb70** [comment]
FYI Currently I'm using 0.0.210816 with Blender 2.93.2 (2.93.2 2021-08-04) on macOS 11.5.2 (20G95).

I will download the the version from today and retry it.

Thank you for your kind offer to make a screenshare. If it doesn't work out, I will be happy to come back to you.

**Comment by kurb70** [comment]
@Moult Unfortunately, the same behaviour as before. I gladly accept the offer of a screenshare session. I have contacted you via Matrix and suggested a meeting date.

**Comment by Moult** [comment]
@kurb70 I didn't see a message but please let me know a time and date during the Sydney timezone (I'm available 8am-8pm typically but hours may be flexible) and we can meet using a system like https://meet.jit.si/openbim

**Comment by kurb70** [comment]
@Moult I suggest doing an online screensharing session today.
FYI I sent an email a few minutes ago. Maybe it is in you spam folder :)

**Comment by Moult** [comment]
@kurb70 OK, I will be online in 40 minutes time at https://meet.jit.si/openbim

**Comment by Moult** [comment]
Closing issue. Issue was that the browse file input field was named "CSV IFC File" which didn't adequately describe that you were meant to select the IFC file for it.
