### ISSUE TITLE
Refactor IfcPatch extract docs

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1663]
Would it be possible to move https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/module/patch/helper.py into `ifcpatch/__init__.py` similar to how IfcSverchok has an extract docs method bundled with it? This will allow any interface, not just the BlenderBIM Add-on, to benefit from dynamically generated hints. In the future, this can be connected to IfcSverchok nodes. This might also simplify the extract docs code to no longer need the parent module arg.

**Comment by Gorgious56** [comment]
The `ifcpatch.extract_docs` method is now pretty much module and class agnostic and could be used in higher level hierarchy to extract docs in other modules pretty easily I think. :)

**Comment by Moult** [comment]
Thanks so much!
