### ISSUE TITLE
IfcPatch doesn't correctly distinguish between type hinted and non type hinted recipes

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1664]
I think these lines are problematic:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcpatch/ifcpatch/__init__.py#L35-L39

For example, if `args["arguments"] = ["foo"]` and the recipe signature is `def __init__(self, src, file, logger, args=None)` then it will call `def __init__(self, src, file, logger, "foo")` and so when the recipe asks for `self.args[0]` it will get `f` which breaks the recipe.

You can test this using the Migrate recipe, using the json string `["IFC4"]` to test.

Perhaps a `has_docs()` is required alongside the refactored `extract_docs()` (see other bugreport)

**Comment by Gorgious56** [comment]
Oh, right, I totally forgot I did that :) It was a simple hacky way I found but as you pointed out it easily breaks apart. I'm on it !

**Comment by Gorgious56** [comment]
This is a temporary solution, since it assumes that if `Patcher.__init__` has a docstring, the arguments are type-hinted, when only one or the other could be true and lead to unexpected unpacking, or no unpacking. Leaving it open since it's not totally fixed for now.

**Comment by Moult** [comment]
I think the solution is fine. The implication of a docstring = type hinted is a good enough restriction.
