### ISSUE TITLE
Optimising geometry iterator initialisation

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1674]
Typically with models coming from Tekla, I am finding that geometry iteration is extremely slow. I've dealt with hundreds of megabytes of IFCs from Revit, but Tekla seems to be able to pack a lot more into smaller files, though I'm not yet sure how. My computer will struggle to import an 80MB Tekla file, but will happily churn through a 300MB Revit file.

I'd like to investigate ways to optimise the iterator in this scenario, otherwise Tekla files become a bit unworkable.

I've only started code-diving, but this is my first time looking at this aspect, so I could be totally off the mark.

It seems as though the `iterator.initialize()` is already slow. It seems to spend a huge amount of time in [collect](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomIteratorImplementation.h#L394) even before multiprocessing begins.

A few random sample files, I've also highlighted a count of by_type("IfcRepresentation") that has a non zero "OfProductRepresentation" or "RepresentationMap" in case it is useful:

Source | Stage | STEP Lines | IfcRepresentations | % | OfProductRepresentation | RepresentationMap
--- | --- | --- | --- | --- | --- | ---
Revit | Consultant | 569435 | 7647 | 1.34 | 6903 | 744
Revit | Trade | 1911426 | 48038 | 2.51 | 45883 | 2155
Tekla | Steel | 1184489 | 308607 | 26.05 | 308603 | 4

The first one initialises in 1.2 seconds. The second in 165 seconds (not linear, it seems). The third I gave up waiting.

Note 99% of the IfcRepresentations in the Revit files are Body. However, Tekla exports a Body, Axis, and CoG for everything. Therefore, out of 308603, only 106568 are body.

Thoughts? I will continue to look, but thought I'd post what I had started looking at.

Edit: happy to provide some sample files if it helps :)

**Comment by Moult** [comment]
If I add `if ((*jt)->ContextIdentifier() == "Body") { ... }` [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomIteratorImplementation.h#L345) it cuts it down to 106568 and it processes in 318 seconds, which seems a bit more reasonable.

**Comment by Moult** [comment]
Just checked, and it takes about 2 minutes to show up on BIMCollab Zoom on Windows, versus 2 hours on Blender on Linux. There must be something fundamentally different in the strategy they are using.

**Comment by Moult** [comment]
Still only focusing on the `try_get_next_task` call (sorry, C++ reading is still slow for me, and all this mapped representation stuff tends to make my head explode). It seems as though the vast majority of that 318 seconds is caught up in the [reuse_ok_](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomIteratorImplementation.h#L684) call. Haven't checked why yet, and `ifcproducts->size()` seems to be 1 most of the time.

**Comment by aothms** [comment]
Not really at work today but inverses are notoriously slow, that's why a whole time back @Stinkfist0 implemented this caching of inverse attribute specifically for mapped item handling. Maybe something broke it since or it needs additional work to make it suitable for this case. 

> and ifcproducts->size() seems to be 1 most of the time.

Judging from the amount of IfcRepresentation that appears to be expected.

Thanks for taking the time to look into this. I will likely find some time for this tomrorow.

**Comment by Moult** [comment]
I saw #47 and played with the cache level just for fun (changed from 64 to 512) and it had no impact.

Looking again deeper, it seems as though the performance killer in `try_get_next_task` boils down to this line of code: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomFunctions.cpp#L1811 - i.e. if I comment out https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomFunctions.cpp#L1812-L1827 the function still takes 317s, but once I comment out L1811 (and the subsequent lines remain commented) then it drops down to 1.5s.

From what I understand, you're saying that representations _cannot_ be reused if its products have different materials assigned. This makes sense (actually, perhaps not in Blender, since we handle material style fallbacks in a special way), but this doesn't apply if there is only a single product.

Therefore, with a very tiny understanding of the big picture of the iterator, I propose two changes:

 1. A representation filter when looping through subcontexts. Most viewers only want to view certain contexts at a time and not others. This leads to a 3x speed up in the case of Tekla collection (and also less multiprocessing tasks too), since they store a Body, Axis, and CoG for everything. Here is my crude hack to test it :)

```
                    if ((*jt)->ContextIdentifier() == "Body") {
                        representations->push((*jt)->RepresentationsInContext());
                    }
```

 2. I added this dumb if statement in the reuse_ok function as per the logic above:

```
                if (products->size() > 1) {
                    associated_single_materials.insert(kernel.get_single_material_association(product));
                    if (associated_single_materials.size() > 1) return false;
                }
```

Also, I changed `return associated_single_materials.size() == 1;` to just `return true;` at the end, but I don't fully understand this check. Why is it checking `==1`? Isn't `==0` also correct? Why can't use reuse a representation if its product has no material?

By the way, just out of curiosity I ran this to see why the has associations call was so long.

```
    print("Loaded in ", time.time() - start)
    start = time.time()
    i = 0
    for p in f.by_type("IfcProduct"):
        i += 1
        x = p.HasAssociations
    print(f"Looped {i} in ", time.time() - start)
```

And got this result:

```
Loaded in  7.128430604934692
Looped 208461 in  292.00663113594055
```

Surprisingly, it seems ... faster in Python compared to C++? This makes no sense to me.

Anyway, hope it was food for thought. I'm fumbling around a bit here and my profiling / debugging capabilities in C++ right now are limited to `std::cout << "This code runs" << std::endl;` :D 

This is the code I'm using to recompile my changes in case there is a smarter way:

```
$ cmake --build . -j 8 --target _ifcopenshell_wrapper # my memory almost maxes out during this command
$ cmake --install .
```

**Comment by aothms** [comment]
> I saw #47 and played with the cache level just for fun (changed from 64 to 512) and it had no impact.

That's not the caching I meant. Sorry I was short on time the other day. I meant this one. https://github.com/IfcOpenShell/IfcOpenShell/pull/482

> and my profiling / debugging capabilities in C++ right now are limited to std::cout << "This code runs" << std::endl; :D

Barking up the wrong tree here, but Microsoft Visual Studio Community Edition is a really good tool.

> From what I understand, you're saying that representations cannot be reused if its products have different materials assigned. This makes sense (actually, perhaps not in Blender, since we handle material style fallbacks in a special way), but this doesn't apply if there is only a single product.

I agree, also not in collada. Collada also does the material binding on the node (=element) level and not at the mesh level. I would love to have these things configurable (same for triangles/quads/ngons/ngons with inner bounds) etc. But I get very little input/demand for this. In practice it's probably doesn't make a huge difference anyway. It's more conceptual.

> Why is it checking ==1? Isn't ==0 also correct?

This is ugly, but it's explained in the comment above:

```c++
// Note that this can be a nullptr (!), but the fact that set size should be one still holds
```

So in the case of no materials get_single_material_association() returns `nullptr` which is added to the set. When all products do not have a material associated the set contains only `nullptr`, size = 1, ok for reuse.

> `if (products->size() > 1) {`

If this optimization can work I think it's a relatively safe fix, but I would change it to. `if (products->size() > 1) { return true }` at the top of the function. I'm not entirely sure if it should be return true or return false. It seems insignificant as reuse of a single product is meaningless, but the result from reuse_ok_ is later used to determine what to do with representation maps. return true I think means the behaviour of the function is not altered but we get apparently a quick and cheap optimization.

> A representation filter when looping through subcontexts

I think that's fair. We're already filtering on ContextType, are you saying we better just filter on ContextIdentifier? Or both? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomIteratorImplementation.h#L267 I'm always a bit scared of these things as I really dislike the string labels here and the risk for breaking things is not little. I'd suppose we only should do this if it is still a really significant performance difference after the products==1 optimization in reuse_ok(). 

If you share the sample files I can also run it through the profiler.

**Comment by Moult** [comment]
Thanks for the explanation! Just a quick reply before I head to sleep.

Yes indeed I think a filter on context identifier also makes sense. It does not have to be enabled by default, but certainly the default expectation of an architectural authoring app to prioritise Body, an annotation tool to prioritise annotation, structural tools to prioritise reference, etc I think certainly cuts down the work a lot. I'm happy to attempt to write a PR for this, if you had a preference on how it should be implemented (e.g. iterator argument vs iterator setting). In the Blender import, I actually have to run a check in the iterator that says "if we already have a body, skip this iteration" - which when there are an extra 200,000 objects to skip, it adds up.

Cheers, also happy to include in the PR the code for `if (products->size() > 1) { return true }`.

I've sent the file I'm looking at - it would be good to verify that the bottlenecks are actually experienced by you too, and not just on my machine.

Assuming this helps `try_get_next_task` I guess the next step is to look at https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomIteratorImplementation.h#L402-L415 - I'll continue my slow code dive. I would love to see the whole mesh / ngon stuff resolved but I'm sure it'll be a while until I hit that portion of the code.

**Comment by aothms** [comment]
sThis is the call tree that msvc gives us for a the first couple of minutes of processing. It shows nearly all time is spent in getInverse() in three occasions including the one (but not limited to) your case. It's only the first couple of minutes so likely not fully representative.

![afbeelding](https://user-images.githubusercontent.com/1096535/130332928-3e670e53-2e90-46cf-afed-98d2ca841190.png)

That inverses are slow in IfcOpenShell is mostly known. The reason is that the map we build at parsing isn't sufficient. The map stored during parse needs to be filtered for attribute index and type every time an inverse attribute is requested (hence the caching). This makes returning inverse attributes somewhat linear in nature. Apparently in this particular file especially problematic. It likely has a lot of associations or something.

My proposal is to apply some bandaids in 0.6 as we described in this issue. In 0.7 I will address the root cause by getting the datastructures built during parsing sufficient to immediately resolve the inverse attributes.

**Comment by aothms** [comment]
I committed something on 0.7 that appears to work. Given that it's so low level I don't have the guts to backport it to 0.6. It seems to resolve the performance anomaly you observed.

**Comment by Moult** [comment]
Great! do you think it is worth me still creating a PR (just thinking, maybe the subcontext filter is still relevant) (and if so, how would you like the subcontext specified?) Or what do you think the timeline is for a v0.7.0 switch?

**Comment by aothms** [comment]
> Or what do you think the timeline is for a v0.7.0 switch?

that's up to you for blenderbim

> do you think it is worth me still creating a PR?

Yes, especially the products==1 fix in reuse_ok() I'd say. The subcontext thing I find a bit risky.

**Comment by Moult** [comment]
I'm happy to switch anytime you think it is stable :) If it already is, I might switch after the next release. Would I lose anything that isn't ported yet?

**Comment by aothms** [comment]
New builds are up https://github.com/IfcOpenBot/IfcOpenShell/commit/88f7d307b87d475e28d8d3550a4a996c71cca812#commitcomment-55316018. Stability will likely still be slightly less than 0.6 for some time, but I think already the benefits outweigh the costs. 

Still need to get the OSX build going for 0.7 though is linux 32 bit required?

**Comment by Moult** [comment]
32 bit isn't required I think. Great progress! I'll switch once there are OSX builds (since the Makefile distributes for all three OSes)

**Comment by Moult** [comment]
So very happy that thanks to @aothms' latest segfault fixes, I am now able to actually start importing geometry using v0.7.0.

I have also built some graphical features to allow the user to configure what portion of the file (e.g. filtered by type, or by spatial container) that they want to import. This will allow users to bring in portions of a file, unload portions, segment them easily into linked files for massive federated models, etc.

This Tekla file I'm testing with in particular is symptomatic of almost every single Tekla file I've received, so hopefully if the iterator can be optimised, it'll benefit a huge amount of people (and make it actually practical to use a Tekla model). I think there is something fundamentally off that needs work, considering that BIMCollab Zoom displays everything in under 2 minutes, whereas we're in the couple of hours range.

I also want to confirm that there is no particular element / representation that is slow or holding up the iterator. I tested this using create_shape on everything manually. Every shape is roughly equal. This means that the process as a whole is slow.

In this test file, there are about 133 objects with representations per floor. So I'm using that as an arbitrary way to benchmark improvements.

On v0.6.0:

Floors | Iterator time (seconds)
--- | ---
1 | 18
2 | 30
3 | 42
4 | 53
10 | - (didn't measure)

On v0.7.0, here are some very promising results, a **speed up of 35%** compared to v0.6.0, I assume due to @aothms improvements in inverse handling:

Floors | Iterator time (seconds)
--- | ---
1 | 13
2 | 22
3 | 33
4 | 39
10 | 95

However, I readded my suggestion here https://github.com/IfcOpenShell/IfcOpenShell/issues/1674#issuecomment-903038829 to filter not just by context type but by context identifier as well. This results in an _additional_ **speed up of 250%** on the v0.7.0 branch! These results will affect every single model which has extra contexts that we don't bother displaying by default. So I think it is worth adding this feature in. Perhaps something like in addition to include=, exclude= in Python the context type and context identifier can be exposed e.g. context_type="Model", context_identifier="Body". I'm happy to have a shot at implementing this, but there were quite a few things which confused me in the wrapper and the iterator constructor - so any hints on where to look and poke around would help :) Anyway, here are the results:

Floors | Iterator time (seconds)
--- | ---
1 | 4.8
2 | 8
3 | 11
4 | 14
10 | 34

What I've further discovered is that let's say I'm importing 4 floors of objects. Of those 14 seconds, 99% of the time is spent in `collect()` - the `process_concurrently()` is actually very fast. In particular, I've discovered the 14 seconds seems to be entirely spent in this line of code which does the element filtering https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcGeomIteratorImplementation.h#L672

I attempted to code dive but failed pretty hard. It seems to me that first, we get all representations. Without the "Body" subcontext filter, this is about 300,000 representations being looped. With the filter, it's down to 100,000. Then for each of the 100,000 we get (typically, since they are not reused) a single product. So time is still linear. Then boost::all loops through `filters_` which also size 1, so still linear, I guess. Then, I'm not quite sure what code is executed - I thought it might be entity_filter but I got a bit lost.

**Comment by Moult** [comment]
OK I had a fresh attempt at code diving and I think I now see how the filter code works. I guess I was surprised to find its actually an attribute filter, not an entity filter.

The bottleneck now actually seems to lie in https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom_schema_agnostic/IfcGeomFilter.h#L97-L101 (by the way, the size of values was 1198 GlobalIds when filtering for 4 floors - note there are 133 representations per floor, but also non-representation stuff like aggregate IfcElementAssembly which is very typical in Tekla where everything is an aggregate assembly).

Seeing that we're only filtering by GlobalId, I don't see the need for `boost::regex_match`. I did a lot of aggressive data type changes (which I'm sure broke a ton of stuff) just to test my theory and changed patterns and values all to simple std::strings and sets of std::strings. My new `match_values` now only does `return values.find(str) != values.end();`

With these changes, the collection time basically drops to zero. Check out these new results which is an additional **speed up of 1,000%**:

Floors | Iterator time (seconds)
--- | ---
1 | 0.5
2 | 0.75
3 | 0.95
4 | 1.15
10 | 3.15
20 | 12.5

(note that "Iterator time" also includes the time needed to create the Blender objects - just because it's easier for me to test this way, and Blender has another optimisation problem where the more objects you have, the slower it is to create more objects, so we will see slower and slower returns, but that's another problem [tackled here in progress](https://developer.blender.org/D9892)).

I hope this analysis makes sense and it isn't just "my machine" or "this file". I think it is generic and affects everyone (others have also told me about Tekla files in OSArch). Perhaps this suggests creating a new filter subclass that is more optimised for the iterator?

**Comment by aothms** [comment]
Hi @Moult  thanks this is super insightful.

> I readded my suggestion to filter not just by context type but by context identifier as well. This results in an additional speed up of 250% on the v0.7.0 branch!

I'm still really puzzled by this. But  then let's go ahead and commit this on 0.7 :) I wouldn't add extra flags for it, just have it depend on the existing EXCLUDE_SOLIDS_AND_SURFACES INCLUDE_CURVES thing. (which could probably benefit from some adjustments, but I mean just under one mechanism).

> I thought it might be entity_filter but I got a bit lost.

It is. It's one of these creatures. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom_schema_agnostic/IfcGeomFilter.h#L43 But come to think of it. I see some boost::regex. But the entity_filter itself https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom_schema_agnostic/IfcGeomFilter.h#L210 should be fast.

After you commit I'll run it through the profiler again.

**Comment by aothms** [comment]
Edit: oops I missed your 2nd reply. Ah, yes **you** are using the guids. (I was just running IfcConvert). Yes then totally let's not use the guids but rather the instance ids!

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/geom/main.py#L103

- [ ] Thomas: create instance id filter as `set<unsigned int>`
- [ ] Thomas: connect to `include=` in python

**Comment by Moult** [comment]
Woohoo! Yes it is perhaps best if you handled the filtering (unless you think it is merely a copy paste of an existing filter as a new subclass and therefore not too tricky as a learning opportunity) - and I would assume as you suggest an ID check could in theory be even faster than a string check.

Tomorrow I'll have a crack at adding a setting for a subcontext. I'm not sure why you're puzzled, it seems straightforward to me that when I'm only interested in Body reps, its less work to loop through other types?

**Comment by aothms** [comment]
I just never expected that this looping through context in the iterator was somehow significant in processing time. After all, it's not that extra geometry interpretation happens right?

**Comment by Moult** [comment]
I think it does queue (collect) and process extra shapes. Then after that I have to write code like this to then cull it out https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/import_ifc.py#L592 - I think I reported bugs in the past about this double processing behaviour but I can't find them now (searching on a phone).

**Comment by aothms** [comment]
Ah ok, yeah sorry, that explains. Hm then maybe we do need another setting, or unify the EXCLUDE_SOLIDS_AND_SURFACES INCLUDE_CURVES  behaviour with a list of context strings.

**Comment by Moult** [comment]
Perhaps a new INCLUDE CONTEXT TYPE and INCLUDE CONTEXT IDENTIFIER can be added which accept a set of strings (and later on, include target view, and target scale, which is super useful for building a workflow around scale dependent annotations)...

Or, maybe just a whole new INCLUDE CONTEXT which accepts a list of context IDs (or entities directly) to filter by which seems more elegant than polluting with a lot of separate settings. Then all the older include curve exclude solid surface stuff can be removed?

**Comment by Moult** [comment]
For the record, this will also solve https://github.com/IfcOpenShell/IfcOpenShell/issues/771 and https://github.com/IfcOpenShell/IfcOpenShell/issues/1290 which have some similarities with this thread.

**Comment by aothms** [comment]
> IDs (or entities directly) 

Something that also works with strings would be nice for the symmetry with IfcConvert.

Have a look at https://github.com/IfcOpenShell/IfcOpenShell/commit/38a0c7106057004d2df77b4bf77713c83589a5bb

**Comment by Moult** [comment]
If you're already poking in the code feel free to go ahead and implement as you know best how it can work similarly with ifcconvert :) Ican read your commit after to learn. I won't be on a computer until  tomorrow.

**Comment by Moult** [comment]
By the way no hard numbers (yet) but I am also running some other pretty involved IFC operations (recursive object placement editing, work schedule task trees, inherited calendar calculations) and I have noticed a significant speedup (far, far more than 35%) on the v0.7.0 branch :) I think users will certainly notice the benefits! A huge kudos!

I didn't find time today to create a PR for the context filter sorry, it might have to wait a few days - got swamped :)

**Comment by aothms** [comment]
Thanks! But defo no worries on time, I also spent a bit too much time on this and need to look into some other things as well.

**Comment by Moult** [comment]
Closing as fixed (I think) :)
