### ISSUE TITLE
BlenderBim : Displaying empty dynamic enums consistency

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1675]
There is an occurence (the only one I think ?) where a property that has an empty dynamic enum displays in a specific fashion to let the user know about it.

![image](https://user-images.githubusercontent.com/25156105/130194395-5c704ee0-15aa-4144-b063-9a41025e4a42.png)

This is done by using a dummy EnumProperty on the PropertyGroup
```
class BIMTypeObjectProperties(PropertyGroup):
    is_editing_type: BoolProperty(name="Is Editing Type", update=updateTypeDropdowns)
    relating_type_class: EnumProperty(items=getApplicableTypes, name="Relating Type Class")
    relating_type: EnumProperty(items=getRelatingTypes, name="Relating Type")
    # This is purely a UX thing
    blank_relating_type: EnumProperty(items=[("None", "No Types Found", "")], name="Relating Type")
```

Then the UI module decides which enum to display :

```
            if type_prop.getRelatingTypes(None, context):
                row.prop(props, "relating_type", text="")
                row.operator("bim.assign_type", icon="CHECKMARK", text="")
            else:
                row.prop(props, "blank_relating_type", text="")
```

I wonder if it wouldn't be easier code-wise to display a simple label instead of using a dummy EnumProperty ? That way the property class definition doesn't have to suffer for a UI problem, and the information is conveyed nonetheless.

```
            row.prop(props, "relating_type_class", text="")
            if type_prop.getRelatingTypes(None, context):
                row.prop(props, "relating_type", text="")
                row.operator("bim.assign_type", icon="CHECKMARK", text="")
            else:
                row.label(text="No Types Found")
```

![image](https://user-images.githubusercontent.com/25156105/130194930-a8cdb5a4-fbf2-4e62-a426-f9def472b6d1.png)

Or maybe with an icon ?

![image](https://user-images.githubusercontent.com/25156105/130195097-fd4f56bf-1218-4930-98a5-8b20c8ac2e46.png)

That would help making the display of all empty dynamic enums to be consistent, without adding too much boilerplate code. I know it may not be a high priority topic but thought it would help polish the UX. :) I'm willing to work on it if need be.

**Comment by Moult** [comment]
In fact, in IFC4, there is a Many:1 mapping of elements to their relevant element type. Therefore, the first dropdown may be omitted completely in IFC4 in theory.

In IFC2X3 however, the first dropdown is still required :(

Feel free to remove the hacky UX enum :) I guess I put it there because it just looked nicer, but I no longer have any attachment to it. Sayonara! :D

**Comment by Moult** [comment]
BTW another UX thing is that I've started to distinguish between icon="X" for delete and icon="CANCEL" for disable. In older code, you will still see icon="X" in use - feel free to change if you come across them - I've been slowly swapping them out as I come across them too.

**Comment by Gorgious56** [comment]
Alright, I'm on it ! :)

Yay for the icon change, that was bothering me a bit too ^^ What do you think of the "REMOVE" icon and where it should be used ? ![image](https://user-images.githubusercontent.com/25156105/130200684-75e4ed8a-631a-4844-ae05-87678f28c5eb.png)

**Comment by Moult** [comment]
I use the remove icon when an object reference is removed from a list or another object, but the object itself remains.

**Comment by Gorgious56** [comment]
I _think_ I revisited all instances of possible empty dynamic enums display in recent commits (there were not that many after all) so I'll go ahead and close.
