### ISSUE TITLE
Can't enable BlenderBIM add on

### ISSUE THREAD

**Issue by Suhaibd** [IfcOpenShell/IfcOpenShell#1681]
Hi,

I can't enable the BlenderBim add-on, attached is the error I'm getting. Any thoughts? 

![Error](https://user-images.githubusercontent.com/89345727/130357284-cbe72413-b72f-4d0e-92dc-72ae78588f15.jpg)

**Comment by Gorgious56** [comment]
Hello, could you try with Blender 2.93 ? https://www.blender.org/download/
The Python version was recently bumped from 3.7 to 3.9 which I suspect is where the error comes from.

**Comment by Moult** [comment]
The official blenderbim.org website only ships the add-on for Blender 2.93. If you still want to use an older version, you can download a `py37` (python 3.7) release from https://github.com/IfcOpenShell/IfcOpenShell/releases
