### ISSUE TITLE
LENGTHUNIT conversion does not work on project libraries

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1684]
Related to #1247, I recently ran into this issue, caused by this assumption: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcParse.cpp#L2249

Naturally, converting length units from project libraries is super useful so that a project library in meters won't appear tiny in a project in millimeters :) and will also address some problems already found by @theoryshaw who uses imperial

Before I attempt to hack away some C++, I guess I'd like to confirm the approach. In theory there may be _multiple_ IfcProjectLibraries (see diagram in docs for IfcTaskType). So perhaps it should first check for an IfcProject, then if it is > IFC2x3 (do you need this check in C++?) then it'll find a IfcProjectLibrary (or, an IfcContext?) as a fallback. (note multiple IfcProjectLibrary seems to only occur when you have an IfcProject first - not in a standalone library, where it serves as a "root/entry" entity). Does this approach sound sane?

**Comment by aothms** [comment]
```
try by_name(IfcContext)
catch by_name(IfcProject)
```

is the most succinct I can think of. I'm fine with any reasonable alternative.

Or if you want to be sure of the multiple libraries thing, then we need to traverse to the correct project but that seems prohibitively hard for an arbitrary IFC instance.

**Comment by Moult** [comment]
Closing as fixed!
