### ISSUE TITLE
What to do with duplicate IDs?

### ISSUE THREAD

**Issue by cmeeren** [IfcOpenShell/IfcOpenShell#169]
I have an IFC file that I'm converting to Collada (DAE) using IfcConvert 0.5.0. In the IFC file, there are three IfcCovering entities that have the same ID. When converting to Collada, this results in three `<library_geometries>/<geometry>` elements and three `<visual_scene>/<node>` elements that have the same ID (but are otherwise not equal).

I'm not sure about the IFC spec, but duplicate IDs seems to be an invalid state for a Collada file. Are duplicate IDs allowed in IFC files, and if so, should IfcOpenShell handle this better?

**Comment by arzezniczak** [comment]
I have similiar problems with duplicated GUIDs comming from Archicad 20. As far as I know - it's not allowed to have more than one object with the same GUID in one IFC file ([_A Globally Unique Identifier [...] provides a way of uniquely identifying an object_](http://www.buildingsmart-tech.org/implementation/get-started/ifc-guid)

**Comment by aothms** [comment]
> So, to uniquely identify any object all GUIDs must be unique.

That is also the idea the IfcOpenShell code base is structured around. For example there is a mapping in the `IfcParse::IfcFile` class from GUID (`std::string`) to a single `IfcRoot*` [1]. 

It wouldn't be overly hard though to detect duplicate guids in the parser (as the mapping is constructed anyway). Either as a simple boolean flag on the `IfcFile` class to signify the presence of duplicate guids, or a `std::set` containing the exact duplicated ids. In the geometry serializers this can then be taken into account and the node ids can be further postfixed, for example with the numerical entity instance name (`IfcGeom::Element::id()`) [2].

Pull requests welcome!

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcParse.cpp#L1069
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomElement.h#L103

**Comment by aothms** [comment]
So, how should we deal with this? For me it is not a high priority issue as I can always hide behind the 'garbage in, garbage out' principle. Duplicate GlobalIds being considered garbage then. But if there are proposals (or better yet, working code) to work around this, I'd happily include it.

**Comment by cmeeren** [comment]
I'm leaning towards the "garbage in" principle. I actually don't think it should be IfcConverter's responsibility to fix this. If needed, one can create another tool to fix the original IFC file before sending it to IfcConvert.

**Comment by arzezniczak** [comment]
> one can create another tool to fix the original IFC file before sending it to IfcConvert
That's what I've done in my case. I have preprocessing part where I search for this duplicated GUIDs but my solution is not universal - I'm only looking for this specific kind of duplicates from Archicad (wall connections), and I'm "fixing" this by generate new GUIDs, and save new IFC file. For my task this is fine for now. But few days ago I've found another case of this problem - this time IFC file is from Revit (that's suprising for me) but duplicated GUIDs are in other place (walls and openings with the same GUID).

I think I will need a more universal solution, but I don't know when I will got time for this task.

**Comment by aothms** [comment]
With some lines of Python it would be fairly trivial to provide a quick preprocessor fix. Untested:

~~~python
import uuid
import ifcopenshell

ifc_file = ifcopenshell.open(...)
guids = set()

for p in ifc_file.by_type("IfcRoot"):
    if p.GlobalId in guids:
        p.GlobalId = ifcopenshell.guid.compress(uuid.uuid1().hex)
    guids.add(p.GlobalId)

ifc_file.write(...)
~~~

**Comment by Moult** [comment]
I've been dealing a lot with this recently with files from all sorts of tools - both invalid GlobalIds and duplicate GlobalIds - I've now written a patch recipe so it is a reusable thing that users can run without the need for coding knowledge.
