### ISSUE TITLE
get_info() and get_info_2() produce different output

### ISSUE THREAD

**Issue by benihildebrand** [IfcOpenShell/IfcOpenShell#1692]
When evaluating get_info() and get_info_2(), I noticed that for the same IfcProduct, the output generated was slightly different even when using the same parameters.

Python Script Snippet:
```python
import ifcopenshell
ifc = ifcopenshell.open('XXX')
products = ifc.by_type('IfcProduct')
print(products[401].get_info(include_identifier = True, recursive = True, return_type = dict, ignore = []))
print(products[401].get_info_2(include_identifier = True, recursive = True, return_type = dict, ignore = []))
```

I then copied both outputs produced, 'sorted' the JSON (JSTool Plug-In in Notepad++) and then did a line-by-line comparison.

As per the screenshot below, everything was identical except for IfcDirection and IfcCartesianPoint.

I would have expected the output to be identical.

Unfortunately I'm unable to share the file to reproduce this output but I'm happy to try bug fixes locally and report back if the issue is resolved.

![image](https://user-images.githubusercontent.com/33851715/130758953-2e7c5a13-9608-4c62-8cbb-2312a9a2f64b.png)

PS: I'm using ifcopenshell version: 0.6.0b0 on Windows 10 with Python 3.9.1 (Miniconda).

**Comment by aothms** [comment]
Are you able to share the model confidentially with models@ifcopenshell.org or just the element in question? extracted with:

```
f = ifcopenshell.open(...)
g = ifcopenshell.file(schema=f.schema)
g.add(f[...])
g.write("single_element.ifc")
```

**Comment by benihildebrand** [comment]
I tried to extract the element in question and stored it in a separate file. 
However, the file generated cannot be opened in BlenderBIM so I presume the source file used when reporting this problem may somehow broken. I'll try to reproduce it with a different file and will post an update here.

**Comment by aothms** [comment]
> However, the file generated cannot be opened in BlenderBIM so I presume the source file used when reporting this problem may be broken

Not necessarily. The approach in the code above doesn't produce a very valid file. Most importantly it misses an IfcProject and spatial structure. So I'm not surprised if it doesn't open.

**Comment by Moult** [comment]
@benihildebrand by the way, perhaps https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcpatch/ifcpatch/recipes/ExtractElements.py might help extract elements but at the same time maintain the spatial tree of the file - this will allow it to be openable in IFC apps.

**Comment by Moult** [comment]
@benihildebrand bump - by the way you can try just sharing a new file with the element added using the `g.add()` code snippet shown. It may not matter that it won't open - it might be enough to reproduce and debug the error.

**Comment by benihildebrand** [comment]
Hi, I tried to reproduce the problem with the same file as before (using the latest build [v0.7.0-b9ea741](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-38-v0.7.0-b9ea741-linux64.zip)). I was unable to reproduce it.

I subsequently tried to process a number of sample files that I had available for testing and wanted to perform a comparison of the get_info() and get_info_2() output for both of them, trying to identify any discrepancies.

I was unable to do that because get_info_2() always ran out of memory after half a dozen or so files (running in a Jupyter notebook within Databricks on Azure). When using get_info() instead and no other code changes, memory use remained constant.

Here is a screenshot showing the memory usage and increases as additional files are being processed.
![image](https://user-images.githubusercontent.com/33851715/145741608-f18a5315-ed27-47db-b66b-26a9c98931a8.png)

I'm unsure if that's a known issue or not. If not, I can create a sample script to reproduce the problem and post here.

**Comment by aothms** [comment]
No thanks @benihildebrand it wasn't known. I didn't really check how to do memory management in python c code and I made the wrong assumptions.

It could be that there is still small leaks (somebody should check actually for the entire API), but at least the dramatic explosion is fixed.

@Moult maybe take note as well, could be related to your experiments that in some of the experiments you couldn't reproduce or consistently reproduce maybe you were just swapping as a result of this.

**Comment by benihildebrand** [comment]
Great, thank you for the quick response and resolution. 

If you kick off another build, I'll grab the latest version and check it out. I'll then also run the comparison between get_info() and get_info_2() to verify if there are any discrepancies between the output produced.

**Comment by Moult** [comment]
> @Moult maybe take note as well, could be related to your experiments that in some of the experiments you couldn't reproduce or consistently reproduce maybe you were just swapping as a result of this.

Noted, I'll try again and let you know :)

**Comment by benihildebrand** [comment]
Thank you for the new build.

When running [v0.7.0-482788a4](https://github.com/IfcOpenBot/IfcOpenShell/commit/482788a46fb3288bd7d1d504743e787f9e0486f4#commitcomment-63973776) in a Databricks cluster on Azure, I noticed a discrepancy in the output produced by get_info() compared to get_info_2().

It affects 'SelfIntersect' that is set to a value (i.e. 'UNKNOWN') when using get_info() but it is 'null'  when using get_info_2().


A script to reproduce this issue with sample file (Element = 0):

```python
import ifcopenshell
import requests
import json

fileContent = requests.get("http://openifcmodel.cs.auckland.ac.nz/_models/231110AC11-FZK-Haus-IFC.ifc")

dbutils.fs.put("file:/local_disk0/tmp/myfile.ifc", fileContent.text, overwrite = True)

ifc = ifcopenshell.open("/local_disk0/tmp/myfile.ifc")

products = ifc.by_type('IfcProduct')

elementNo = 0

old = products[elementNo].get_info(include_identifier = True, recursive = True, return_type = dict, ignore = [])
new = products[elementNo].get_info_2(include_identifier = True, recursive = True, return_type = dict, ignore = [])

old_json = json.dumps(old, sort_keys = True, indent = 4)
new_json = json.dumps(new, sort_keys = True, indent = 4)

old_json == new_json
```

**Comment by aothms** [comment]
You're right @benihildebrand an unfortunate result of how the code is currently structured. I committed a fix.

**Comment by benihildebrand** [comment]
The memory issue reported [above](https://github.com/IfcOpenShell/IfcOpenShell/issues/1692#issuecomment-992047291) is resolved as per the screenshot below (running ifcopenshell-python-38-v0.7.0-4c40fc1-linux64.zip).

![image](https://user-images.githubusercontent.com/33851715/150031936-9cfdf9db-63b3-4965-b81b-bfb3f68b766d.png)

**Comment by benihildebrand** [comment]
Hi, when comparing some more files, I spotted another discrepancy in the output between 
get_info() and get_info_2().

'**Orientation**' doesn't seem to be set correctly (tested using v0.7.0-000e3acb) for the element with Global Id = '_3Ep4r0uuX5ywPYOUG2H2A4_'.

To reproduce the issue, use the IFC file from here:
https://raw.githubusercontent.com/mvaerle/python-ifc/master/testdata/MergeTest.ifc

![image](https://user-images.githubusercontent.com/33851715/151083473-2fa4603f-1de2-4e07-81d9-290fcf106cc8.png)

**Comment by aothms** [comment]
In this particular case the file is not valid:

~~~
#59=IfcFaceOuterBound(#54,.U.)
~~~

The attribute type is BOOLEAN (IfcBoolean in IFC4) so should be .T. | .F.

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifctopologyresource/lexical/ifcfaceouterbound.htm

In this particular case it seems get_info() stays closer to the parsed site. get_info_2() takes into account the schema more. It'd be nice if this were more consistent but on invalid data I don't have huge drive to fix this.

validate.py will catch this error

~~~
$ python -m ifcopenshell.validate MergeTest.ifc
Validating MergeTest.ifc
In #59=IfcFaceOuterBound(#54,.U.)
'UNKNOWN' not valid for <attribute Orientation: <boolean>>
~~~

**Comment by benihildebrand** [comment]
Hi, I didn't know that this particular file wasn't valid and can understand that this won't be fixed as per your comment above. Other than that, I didn't see other discrepancies in the sample comparisons that I performed.
So I think we can close this now.
Thank you.

**Comment by aothms** [comment]
Thanks for taking the time @benihildebrand for the continued investigations
