### ISSUE TITLE
get_info_2() fails silently for some IFC Products - Data issue?

### ISSUE THREAD

**Issue by benihildebrand** [IfcOpenShell/IfcOpenShell#1693]
Python 3.9.1 (Miniconda) running IFC Open Shell v0.6.0b0 on Windows 10.

To reproduce:
- From BIM Vision (https://bimvision.eu/download/), download the sample model "Skladanie – zbrojenie" (left image in the middle row)
- Save the following Python code in a .py file, adjust path to downloaded IFC file, and execute.

```python
import ifcopenshell

print("ifcopenshell version: "+str(ifcopenshell.version))

# From BIM Vision Downloads -> Example IFC Models (https://bimvision.eu/download/)
# "Skladanie – zbrojenie" from http://www.download-datacomp.com.pl/bimvision/models/ASPWRZ-MAD-konstrukcja-zbrojenie.ifc

# IFC Product 2 works, but 3 fails
my_number = 3

ifc = ifcopenshell.open('C:/Temp/IFC Sample Files/ASPWRZ-MAD-konstrukcja-zbrojenie.ifc')
products = ifc.by_type('IfcProduct')

print("Attempt 1 - get_info()")
x1 = products[my_number].get_info(include_identifier = True, recursive = True, return_type = dict, ignore = [])
print(x1)

print("")

print("Attempt 2 -  get_info_2()")
x2 = products[my_number].get_info_2(include_identifier = True, recursive = True, return_type = dict, ignore = [])
print(x2)

print("")
print("----")
print("Done")
```

The Python console will output the IFC details when calling get_info() but it seems to stop processing (failing silently) when trying to call get_info_2 for the same element with the same parameters.

Note that the final Print statements are not showing in the console.

![image](https://user-images.githubusercontent.com/33851715/130778647-21f2e102-78b1-4507-bc21-1c3abb4833c2.png)

.

However, when trying to retrieve the details for e.g. the 2nd Product (change "my_number" variable from 3 to 2 and re-run), both get_info() and get_info_2() return data and the final Print statements are also executed.

![image](https://user-images.githubusercontent.com/33851715/130778994-f7f885ed-9d0a-4ed3-9697-76d116c8fd1e.png)

**Comment by aothms** [comment]
Well get_info_2() isn't as well tested (or used). It's mostly a prototype to investigate potential performance improvements.

This is a easy fix though it seems attributes derived in subtypes and select values weren't taken into account. See commit.

Are you able to build a new version yourself or do you wait for builds to be provided on the website?

**Comment by benihildebrand** [comment]
I haven't built it myself before so I'd prefer to wait for a build to be available (Ideally a build to install using "conda").
I'll report back if the issue is resolved. Thank you.

**Comment by aothms** [comment]
I've started a new build for the 0.6 branch. It won't be published to conda though. So you have to move it to your site packages folder manually.

**Comment by aothms** [comment]
Here it is https://github.com/IfcOpenBot/IfcOpenShell/commit/5485177888497c6ca7bdcebfebb15067bcfc9e55#comments

**Comment by benihildebrand** [comment]
Thank you. I downloaded the Python 3.9 for Win file and extracted it to the Site Packages folder. I deleted all existing files/folders including the \_\_pycache\_\_ folder before coping the new files across.
![image](https://user-images.githubusercontent.com/33851715/132143052-fff27a39-5b13-46ad-8668-d3f07fd28354.png)

![image](https://user-images.githubusercontent.com/33851715/132143069-e27a0d68-647c-4fe1-bb1c-06d98b799528.png)

Unfortunately I'm still able to reproduce the problem. Below is an output of the same script used when reporting the problem initially. No output is being produced for the get_info_2() command.

![image](https://user-images.githubusercontent.com/33851715/132143125-9635faba-dd19-4b6d-afb1-51a1dc9ec32c.png)

**Comment by aothms** [comment]
Apologies, somehow the windows builds for this commit appear to be wrong (they're for 0.7 which didn't have this fix yet merged in). That's why the builds aren't published also on the web yet, the new build system is still somewhat experimental.

I'll start a new build.

**Comment by aothms** [comment]
This time the build went through ok https://github.com/IfcOpenBot/IfcOpenShell/commit/f898893607c7cda3a54ac04faaf7a985c8240a4d#commitcomment-56082883

**Comment by benihildebrand** [comment]
Thank you so much. I can confirm that the issue is resolved in the latest build mentioned (tested in Python 3.9 x64 on Windows 10).

![image](https://user-images.githubusercontent.com/33851715/132487705-e5e0ac2a-e47c-48bb-8395-8362d4506dfc.png)
