### ISSUE TITLE
Purpose of #define SHARED_PTR?

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#17]
I was thinking of looking into OS X and/or Clang support in the near future. The codebase seems good with the exception TR1 (now part of C++11) features shared_ptr (and array) inclusion juggling between Boost, MSVC, and GCC TR1 implementations. As Boost is a mandatory requirement, all of this seems quite unnecessary. On a related noted, there would a small optimization opportunity by using make_shared for shared_ptr allocations throughout the codebase.

**Comment by aothms** [comment]
You're correct. This SHARED_PTR stuff is a remnant of before boost was mandatory. Also, the official OS X builds were built on an ancient macbook with a peculiar version of gcc, which iirc had issues with both make_shared as well as make_pair.

You're suggestion is to rename everything to boost::shared_ptr and ::array, or require C++11? I think I would be in favour of the first option, but not sure if there are optimizations that runtime libs can make if you stick to std:: variants.

**Comment by Stinkfist0** [comment]
Yeah, using `boost::` explicitly would be good. Picking up different implementations on compiler basis for certain classes can also cause some problems as there can be small differences between std and boost implementations (e.g., IIRC, boost has `operator <` for `weak_ptr`, but standard version is missing it). Also I think the `std::tr1` namespace will be removed completely in the next Visual Studio version, etc. The `array` use cases seem totally trivial and could be replaced with C arrays or couple explicit floats.
