### ISSUE TITLE
IfcConvert: symbol lookup error:

### ISSUE THREAD

**Issue by ghost** [IfcOpenShell/IfcOpenShell#170]
IfcConvert: symbol lookup error: IfcConvert: undefined symbol: _ZN17GeomAdaptor_Curve11NbIntervalsE13GeomAbs_Shape

when I run IfcConvert (with or without parameters)
I compiled it on Ubuntu 16.04.1 LTS following your instructions.

Any advice is welcome, thanks!

**Comment by jf---** [comment]
looks like not linking properly with your opencascade  kernel

**Comment by bimmib** [comment]
as I said, I copy pasted the instructions for compiling (all of them, openCascade included). And I did it twice...  Do you have any ideas? maybe I should use a branch or some other commit that you have tested and can confirm it works?

**Comment by aothms** [comment]
Some more details are necessary in order to resolve this. E.g. which instructions exactly, there are many possible approaches (`apt-get install liboce-*` vs compiling yourself vs. `./build-all.py`). Please also paste some build output here. We have Travis CI reporting the build is working fine after all.

**Comment by bimmib** [comment]
I've created a virtual machine with Ubuntu 16.04.1 and used the following instructions:

$ sudo apt-get install git cmake gcc g++ libboost-all-dev libicu-dev
$ sudo apt-get install liboce-foundation-dev liboce-modeling-dev liboce-ocaf-dev liboce-visualization-dev liboce-ocaf-lite-dev


$ sudo apt-get install libftgl-dev libtbb2 libtbb-dev libgl1-mesa-dev libfreetype6-dev
$ git clone https://github.com/tpaviot/oce.git
$ cd oce
$ mkdir build && cd build
$ cmake ..
$ make -j
$ sudo make install

$ sudo apt-get install libpcre3-dev
$ git clone https://github.com/KhronosGroup/OpenCOLLADA.git
$ cd OpenCOLLADA
Using a known good revision, but HEAD should work too:
$ git checkout 064a60b65c2c31b94f013820856bc84fb1937cc6
$ mkdir build && cd build
$ cmake ..
$ make -j
$ sudo make install

sudo apt-get install python-all-dev swig

$ cd /path/to/IfcOpenShell
$ mkdir build && cd build
$ cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ \
      -DOPENCOLLADA_INCLUDE_DIR="/usr/local/include/opencollada" \
      -DOPENCOLLADA_LIBRARY_DIR="/usr/local/lib/opencollada"  \
      -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/
$ make -j

$ sudo make install


Then,

$ wget ftp://ftp.dds.no/pub/ifc/Munkerud/Munkerud_hus6_BE.zip
$ unzip Munkerud_hus6_BE.zip
$ ./IfcConvert Munkerud_hus6_BE.ifc
$ less Munkerud_hus6_BE.obj


During the compilation, there were no errors - just a few warnings. Also it didn't find libxml* but I installed it with apt-get and it worked. I you want I can repeat these steps and save the output to a file.

**Comment by Stinkfist0** [comment]
I'd suspect this is most likely related to different OCE versions; can you try building OCE yourself and see what happens?

**Comment by bimmib** [comment]
ok.... i didn't observe that... I thought liboce* it's part of 'prerequisites'. So, I purged all the oce libs installed via apt-get and recompiled oce.

Then run ifc's cmake like this:

 cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ \
      -DOPENCOLLADA_INCLUDE_DIR="/usr/local/include/opencollada" \
      -DOPENCOLLADA_LIBRARY_DIR="/usr/local/lib/opencollada"  \
      -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ \
      -DOCC_INCLUDE_DIR="/usr/local/include/opencascade" \
      -DOCC_LIBRARY_DIR="/usr/local/lib"

and.... (i think is the same ZN11 error)

libIfcGeom.a(IfcGeomWires.cpp.o):IfcGeomWires.cpp:(.text+0x51a2): more undefined references to `Standard_Transient::DecrementRefCounter() const' follow
libIfcGeom.a(IfcGeomWires.cpp.o): In function `IfcGeom::Kernel::convert(Ifc2x3::IfcPolyline const*, TopoDS_Wire&)':
IfcGeomWires.cpp:(.text+0x51da): undefined reference to `NCollection_BaseSequence::ClearSeq(void (*)(NCollection_SeqNode*, opencascade::handle<NCollection_BaseAllocator>&))'
IfcGeomWires.cpp:(.text+0x51f2): undefined reference to `Standard_Transient::DecrementRefCounter() const'
IfcGeomWires.cpp:(.text+0x52b0): undefined reference to `Standard_Transient::DecrementRefCounter() const'
libIfcGeom.a(IfcGeomWires.cpp.o): In function `opencascade::handle<BRep_TVertex>::EndScope()':
IfcGeomWires.cpp:(.text._ZN11opencascade6handleI12BRep_TVertexE8EndScopeEv[_ZN11opencascade6handleI12BRep_TVertexE8EndScopeEv]+0xd): undefined reference to `Standard_Transient::DecrementRefCounter() const'
collect2: error: ld returned 1 exit status
CMakeFiles/IfcConvert.dir/build.make:304: recipe for target 'IfcConvert' failed
make[2]: *** [IfcConvert] Error 1

**Comment by bimmib** [comment]
Update: I managed to compile and test it on a new virtual machine using the oce* libs from Ubuntu's repository.  You can close the ticket. Thanks for the help!

PS. can you please update the doc and create a separate, more visible section for installing vs compiling OCE (for stupid and lazy people like me who don't read the whole doc before starting :) )

**Comment by aothms** [comment]
@bimmib thanks for the update. So if I understand correctly, your issue comes from having the oce libs/include files on your machine from both the package manager, as well as one you compiled yourself. Somehow then the version included when compiling is different from the version being linked against, which caused the conflict.

I will make a note.
