### ISSUE TITLE
IfcConvert ==> SVG (v0.7.0)

### ISSUE THREAD

**Issue by bbrangeo** [IfcOpenShell/IfcOpenShell#1706]
Hi,

How can I adjust the nin overlay?
I would only like an svg with the section and another with the elevation ?

SVG 
here is my command line :

`./IfcConvert home.ifc home.svg --svg-xmlns --svg-project --svg-poly --exclude=entities IfcOpeningElement IfcRoof --bounds=1024x4024 --model --plan`
<img width="1038" alt="Capture d’écran 2021-08-30 à 09 57 38" src="https://user-images.githubusercontent.com/769760/131305957-e2c0c4d2-040c-4032-9a9d-eaf94b461fb3.png">

SVG 
here is my command line :

`./IfcConvert home.ifc home.svg --svg-xmlns --svg-project --svg-poly --exclude=entities IfcOpeningElement IfcRoof --auto-elevation  --bounds=1024x4024 --draw-storey-heights=left --elevation-ref=DRAWING`

<img width="1283" alt="Capture d’écran 2021-08-30 à 09 45 06" src="https://user-images.githubusercontent.com/769760/131304504-32e22912-7434-44a0-94f5-e70e8e1713c7.png">

SCRENSHOT 1
<img width="445" alt="Capture d’écran 2021-08-30 à 09 44 38" src="https://user-images.githubusercontent.com/769760/131304513-2bb63ce5-56a0-457f-a836-3f76e1ecbc33.png">

SCRENSHOT 2
<img width="656" alt="Capture d’écran 2021-08-30 à 09 44 32" src="https://user-images.githubusercontent.com/769760/131304515-926382e5-4d89-42dc-acd7-f3eac66ae575.png">

SCRENSHOT 3
<img width="783" alt="Capture d’écran 2021-08-30 à 09 44 24" src="https://user-images.githubusercontent.com/769760/131304516-74f6958f-b607-4d07-bafd-1edb90ca0bc4.png">

**Comment by aothms** [comment]
> How can I adjust the nin overlay?

Don't really understand the question. For fine grained control I recommend writing a script. With the addDrawing() call you precisely specify what kind of drawing plane goes to which svg file.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/draw.py
