### ISSUE TITLE
Windows build script and spaces in path

### ISSUE THREAD

**Issue by LukasMHD** [IfcOpenShell/IfcOpenShell#171]
Sorry if this is a stupid issue, but everytime i try to compile the project for windows i get this error message.
I installed git and cmake and added them to path, which brought me a step further but now this happens: 

> "this script fetches and builds all IfcOpenShell dependencies
> 
> Generator not passed but VisualStudioVersion=14.0 environment variable detected:
> using `Visual Studio 14 2015` as the generator.
> build-type-cfg.cmd: Warning: BUILD_CFG not specified - using the default RelWithDebInfo
> 
> Script configuration:
> * CMake Generator       = `Visual Studio 14 2015`
>   - Passed to CMake -G option.
> * Target Architecture   = x86
>   - Whether were doing 32-bit (x86) or 64-bit (x64) build.
> * Dependency Directory  = C:\Users\...\Documents\IfcOpenShell-master 1 \IfcOpenShell-master\deps
>   - The directory where IfcOpenShell dependencies are fetched and built.
> * Installation Directory = C:\Users\...\Documents\IfcOpenShell-master 1 \IfcOpenShell-master\deps-vs2015-x86-installed
>   - The directory where IfcOpenShell dependencies are installed.
> * Build Config Type     = RelWithDebInfo
>   - The used build configuration type for the dependencies.
>     Defaults to RelWithDebInfo if not specified.
> * Build Type            = Build
>   - The used build type for the dependencies (Build, Rebuild, Clean).
>     Defaults to Build if not specified. Rebuild/Clean also uninstalls Python (if it was installed by this script).
> * IFCOS_USE_OCCT        = FALSE
>   - Use the official Open CASCADE instead of the community edition.
> * IFCOS_INSTALL_PYTHON  = TRUE
>   - Download and install Python.
>     Set to something other than TRUE if you wish to use an already installed version of Python.
> * IFCOS_USE_PYTHON2     = FALSE
>   - Use Python 2 instead of 3.
>     Set to TRUE if you wish to use Python 2 instead of 3. Has no effect if IFCOS_INSTALL_PYTHON is not TRUE.
> * IFCOS_NUM_BUILD_PROCS = 4
>   - How many MSBuild.exe processes may be run in parallel.
>     Defaults to NUMBER_OF_PROCESSORS. Used also by other IfcOpenShell build scripts.
> 
> Der Befehl "C:\Users\...\Documents\IfcOpenShell-master" ist entweder falsch geschrieben oder
> konnte nicht gefunden werden.
>  1. Install PowerShell (preinstalled in Windows >= 7) and make sure 'powershell' is accessible from PATH.
>   - https://support.microsoft.com/en-us/kb/968929
>  2. Install Git and make sure 'git' is accessible from PATH.
>   - http://code.google.com/p/tortoisegit/
>  3. Install CMake and make sure 'cmake' is accessible from PATH.
>   - http://www.cmake.org/
>  4. Visual Studio 2008 or newer (2013 or newer recommended) with C++ toolset.
>   - https://www.visualstudio.com/
>  5. Run this batch script with Visual Studio environment variables set.
>   - https://msdn.microsoft.com/en-us/library/ms229859(v=vs.110).aspx
> 
> Warning: You will need roughly 8 GB of disk space to proceed (VS 2015 x64 RelWithDebInfo).
> 
> If you are not ready with the above press Ctrl-C to abort
> Drücken Sie eine beliebige Taste . . ."

**any help is greatly appreciated.**

**Comment by aothms** [comment]
@Stinkfist0 @klacol

A wild guess: Is there a space somewhere in the path where IfcOpenShell resides? Not sure whether that is supported. I know @klacol has been working on this [1], but unfortunately it hasn't made it back upstream yet.

[1] https://github.com/IfcOpenShell/IfcOpenShell/pull/48/commits/7c0793ef6602b200f6fe4216548d2a0fcd21bb97

**Comment by Stinkfist0** [comment]
Yeah, I'm suspecting spaces, should really fix this, it should be trivial.

**Comment by LukasMHD** [comment]
That did the Trick, I just moved the folder up a couple of levels. it was probably the spaces, yes. Thanks a bunch!

**Comment by Stinkfist0** [comment]
I'll fix the script for spaces in path now.

**Comment by Stinkfist0** [comment]
The batch files were pretty easy to fix but I ran into problems with the add_debug_variants() function in CMakeLists.txt which needs to be resolved.

**Comment by aothms** [comment]
@Stinkfist0 I see. Perhaps you can use `CMAKE_CURRENT_SOURCE_DIR` to work around this. E.g. replace all occurrences of it with a specific token to temporarily mask the spaces. Not sure if that helps and whether I understood the problem correctly.

I am also fine with skipping `add_debug_variants()` if there are spaces in `CMAKE_CURRENT_SOURCE_DIR` and leave a note to the user. If I understood correctly they will get a working release build (?) which should be what most users are after.

**Comment by aothms** [comment]
@Stinkfist0 thoughts? What is the quickest way to get this resolved? Like I said, I am fine with a note that `add_debug_variants()` does not work on paths with spaces.

**Comment by Moult** [comment]
It seems as though spaces are now allowed so this can be closed: https://blenderbim.org/docs-python/ifcopenshell/installation.html#compiling-on-windows-visual-studio
