### ISSUE TITLE
Refactoring for mature native authoring, TDD, and scalability of the codebase.

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1711]
As a self-professed TDD enthusiast who embarrassingly didn't write a single test, I've run out of excuses :)

During the first year of the BlenderBIM Add-on, it was a monolithic import / export function. This was untestable and due to my lack of IFC knowledge at the time I was not clever enough to modularise it and all the IFC entities seemed rather spaghetti-like.

With the best of intentions, at the beginning of this year the add-on was rebuilt from scratch designed to be testable. Yet, I still did not write tests. Unfortunately, the Blender UI is not fun to test, and the IfcOpenShell API is basically a database / repository layer, which requires data to test. Writing database tests are [not fun](https://stackoverflow.com/questions/145131/whats-the-best-strategy-for-unit-testing-database-driven-applications). Essentially I was lazy and now I'm paying the price. However, I think that the IfcOpenShell API has matured enough that we can now use the API itself to write tests, which'll make test writing more fun.

Here's an unscientific roll through the last few bugfixes and categorising them by testable layer based on the test pyramid. Note that it's slightly less pyramid shaped because @Gorgious56 went crazy on the operator layer and focused on those problems in particular. Not all of these bugs could've been caught from tests, but they could've benefited from tests. All of these fixes have brought us closer to native authoring.

Bug in Blender UI:
bcda3d8e ("Minor fix", 2021-08-29)
52f4b564 ("Minor fix. It seems as though StructRNA of type Scene may be removed during undo/redo, which results in handlers failing.", 2021-08-22)

Bug in Blender operators:
0ed38a41 ("Fix #1707. Fix bug where project library browser could self reference.", 2021-08-31)
dd0a3d04 ("Minor fix.", 2021-08-27)
3c235208 ("Fix #1679. Again.", 2021-08-22)
8178dd33 ("Fix #1679", 2021-08-22)
616f2841 ("Minor fix", 2021-08-21)
6c6d4c04 ("Fix #1672. Bug where style attributes couldn't be edited.", 2021-08-20)
11e36bf7 ("Minor fix", 2021-08-20)
29cda050 ("Fix error when adding opening with None object", 2021-08-19)
95f2d939 ("Fix error when filling opening with None object", 2021-08-19)

Bug in API:
4accf306 ("Add transaction support for adding elements. See #1709.", 2021-08-31)
0a2afa48 ("Fix bug where element replacement would sometimes fail leading to various problems.", 2021-08-30)
9d4f0730 ("Fix typo in material style assignment code", 2021-08-30)
6b33b23a ("Fix bug when copying objects, don't copy their decomposition to prevent invalid IFCs.", 2021-08-30)
6e3484fd ("Fix https://github.com/IfcOpenShell/IfcOpenShell/issues/1695 : (#1697)", 2021-08-26)
8fa1a998 ("Fix bug where the pset templates with multiple applicable entities only checked the first entity", 2021-08-25)
6db1a8a8 ("Minor fix", 2021-08-22)
6c6d4c04 ("Fix #1672. Bug where style attributes couldn't be edited.", 2021-08-20)
b5ff3cd8 ("Fix error due to typo", 2021-08-19)

With this logic, I propose that a methodical, test driven approach is the way to effectively and efficiently accelerate the maturity of native authoring.

I propose that all new IfcOpenShell API, Util and Core (i.e. transaction system) changes must be test-driven from now on. Similarly, all new operator level changes must also be test driven from now on. I'm happy to ignore UI testing still, as UI bugs are very rare and UI tests are expensive.

I'd also like to prioritise testing on removal usecases, and a few complex ones like copy_class. We already know these are incomplete and there are TODO notes on deep purging littered here and there.

I'll edit this post later with a methodical test coverage todo list so this can act as a tracker.

Edit:

 - IfcOpenShell-python tests: **619 / 500 (100%)** as of 2023-02-01
 - BlenderBIM Add-on Core tests: **267 / 601 (44%)** as of 2023-02-01
 - BlenderBIM Add-on Tool tests: **536 / 601 (89%)** as of 2023-02-01
 - BlenderBIM Add-on Integration tests: **466 / 601 (78%)** as of 2023-02-01
 - BlenderBIM Add-on Data classes: **45 / 45 (100%)** as of 2023-02-01
 - Total: **1933 / 2348 (82%)** as of 2023-02-01

Note: for IfcOpenShell we have two targets. One is a traditional test coverage we can measure. However it only measures what we test, so it can be artificially high. The second one is based on the number of files, with an arbitrary assumption that we need to write at least 2 tests per file (most files are a single API usecase, except for utils and core). A quick `find . -type f -iname "*.py" | wc -l` as a ballpark figure multiplied by 2 gives 500 tests.

Note: for the BIM module `len(dir(bpy.ops.bim))` = 601, so assuming we get one test per operator (which is an obvious underestimate), we need 601 tests. However, as we cannot measure code coverage as these are tested through Blender operators, we'll use this number as I can't think of anything better. As long as the discipline of TDD is kept, this number will always go up anyway and in time traditional coverage metrics won't matter anyway.

Note: for the Tool module, we assume each operation uses at least one tool. So again, we strive for the same number of tests. Again, in some ways this is an underestimate and in some ways it is an overestimate, so it is simply a number to work towards.

When these arbitrary targets are reached, this bug will be closed. It doesn't mean the job is done, as testing is an ongoing process. However it simply means 1) the system architecture enables testing, and 2) we have proven a strong discipline for clean code. As the system matures, I expect test counts to be in the thousands.

**Comment by Moult** [comment]
Ping @atomczak in the spirit of fast running tests, can we remove the network calls in `test_ids`? Perhaps we can have a make call to fetch sample data (which can be used not just for `test_ids` but also for other more complex integration tests too) and the test suites no longer have that responsibility?

With the network calls, currently it adds about 3 seconds just to run `test_ids` on my computer which seems a little disproportionate.

**Comment by aothms** [comment]
> and the test suites no longer have that responsibility?

I'd say git submodules in this case. Since they are anyway calls to a git repo. I know submodules are awful, but we have relied on them in the past.

**Comment by Moult** [comment]
Cheers, should I use the existing test files repo or start a new one?

**Comment by aothms** [comment]
No preference, you can also just for @atomczak  repo and put in under the IfcOpenShell org I guess

**Comment by Moult** [comment]
Now that there are a few tests rolling in (109) for ifcopenshell-python, it is possible to track coverage a bit more meaningfully. Right now, test coverage is about 32% (which is an overestimate, as coverage analysis only tracks modules we call from test suites, but over time it will get more and more accurate). I've edited the first post for the goal which is 90%. I'll keep this posted and update whenever there are significant milestones. About half of the past bugfixes since TDD was introduced were caught using TDD, so life is good. These tests are now part of the IfcOpenShell CI.

I have yet to figure out an objective way to measure Blender operator test coverage. I also have yet to know whether or not it is useful to introduce an intermediary layer between Blender and the BlenderBIM Add-on. So far, it seems unnecessary. These tests are not yet part of the CI setup.

**Comment by atomczak** [comment]
> Cheers, should I use the existing test files repo or start a new one?

Sorry, I missed that conversation. The idea with external repository was that when a user downloads IfcOpenShell, he doesn't download test ifc/xml files. There might be a better solution I presume. @Moult, should I move those test files somewhere else?

**Comment by Moult** [comment]
@atomczak nothing wrong with an external repository, but the tests should not download the files. As @aothms suggests a git submodule will work well but I haven't gotten around to it. More than happy for you to set it up :)

**Comment by atomczak** [comment]
@Moult
but submodule within test folder will cause test files to be downloaded together with IfcOpenShell, won't it?

**Comment by aothms** [comment]
When developers cloning the repository they can clone with --recursive to get all submodules or can initialize them later selectively. The default is to clone without any submodules.

What end-users download from the website is packaged by the CMake install script [1] which will not include these files assuming we keep them out of the `src/ifcopenshell-python/` folder.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcwrap/CMakeLists.txt#L91

**Comment by atomczak** [comment]
ok, added this submodule with test files in my IDS branch. Will create a PR after implementing new IDS 0.4.3.

**Comment by Moult** [comment]
A heads up that in the latest commit, I am starting to decouple Blender from the BlenderBIM Add-on.

In other words, in the past, the BlenderBIM Add-on was tightly coupled to Blender. This created a variety of problems:

 1. You could only run tests through the UI. This makes tests inflexible (it has to cater to how Blender operators works).
 2. You could only run tests through Blender. This makes tests slow. This discourages test running and makes TDD impractical. (roughly 10-20 times slower, it seems, and definitely more than 10 seconds)
 3. You cannot measure test coverage as code is indirectly called through operators.
 4. All business logic goes through operators. Operators cannot return values and have restricted data types for their signatures. This led to rather nasty workarounds for us to introduce operator parameters and extra logic to fetch data created from an operator without knowing how the execution actually went.
 5. Difficult for other add-ons or scripters to interact with the BlenderBIM Add-on, as they had to always call operators or go directly to the IfcOpenShell with nothing in-between.
 6. Added unnecessary complexity in the undo / redo system as we had to nest operators. This allows us to no longer nest operators.
 7. Abstract domain logic is not decoupled from concretions. This decreases code readability, in addition to all the other problems listed.
 8. UI logic (Data calls - this will also be rearchitected as it has a series of problems) and domain logic not separated.
 9. Easier multi-version support of all dependencies in the future (Blender versions, IfcOpenShell versions)

I struggled a bit with this because I unfortunately find testing (and especially mocking) in Python to be quite inelegant. I've attempted to improve this with a minimum amount of magic and taken a lot of inspiration from Ruby's RSpec, PHP's PHPSpec, and PHP's Prophecy, which I think makes describing domain level code significantly easier. However, I hope the new architecture I am proposing will resolve all of the 9 problems above.

Here's a high level description:

 - blenderbim.core: abstract domain logic of blenderbim capabilities, and how it interacts with blender, ifc, and other systems. Fully decoupled from everything. BDD in a spec-like manner, with Prophecy style mocking. Full suite Red-Green-Refactor whilst developing is intended.
 - blenderbim.bim: blender-specific UI delivery mechanism. BDD with Gherkin, with only partial testing run whilst developing due to speed. Full test suite will likely only run during CI in the future.
 - ifcopenshell.api: effectively a clever repository. Regular TDD happens here.
 - ifcopenshell.util / core ifcopenshell: Regular TDD happens here.

**Comment by Moult** [comment]
Last commit now allows for filtering of the Gherkin tests. E.g. to run everything do `make test-bim`. You can use pytest to manually filter, such as `pytest test/bim -m "owner"` to run tests only specific to the owner module.

**Comment by Moult** [comment]
I thought I'd write a bit about the new data classes that the UI now reads from. This is the final bit of the refactor that I also wanted to achieve. This resolves the following list of problems I've faced with the existing Data architecture:

 1. In the past, Data classes had two responsibilities: UI caching, and a kinda lazy shortcut for data extraction in operators or props. This mixing of responsibilities is bad design.
 2. Due to the previous point, but also due to another problem where the Data class was not specific to a singular UI, but rather acted as a "god model" for all data relating to everything relevant to the module as a whole. This added overhead and complexity.
 3. Because Data classes were not specific to a single UI widget, UI code had to become extra smart to know how to pick and choose from the Data classes. Smart UI is not good. Dumb UI is good.
 4. Data classes were refreshed using semi consistent loading functions (some global, some object specific). This inconsistency in interface is no good.
 5. Data classes were refreshed by operators. This means that after you run an operation, you have to know which UI elements it needs to refresh. This was fine in the past, but less so now that we are doing fun parametric stuff. For example, something like removing a person in the owner module would actually affect relationships in work schedules, document information, resource approvals, etc ... clearly numerous other UI panels. We don't want to reload everything, and we also don't want operators to have to know about other modules. This problem in particular leads to lots of bugs users probably don't even know about yet (but will be increasingly more important as we implement better deep purges especially).
 6. If Data classes have BlenderBIM UI specific stuff (which arguably you might say it does), it shouldn't belong in ifcopenshell's namespace.

So, the new solution:

 1. Only UI is allows to talk to Data, nothing else. Only one responsibility. This simplifies operator and prop code.
 2. No god models. One data class designed for a single UI widget template.
 3. UI code must be dumb. Only primitive variables, boolean predicates, and simple list loops allowed. No other if statements, no objects, no dictionaries.
 4. Move new data classes into blenderbim module namespace.
 5. Consistent load function. Always `is_loaded` and `load()`. Nothing else.
 6. Set is_loaded to false every time _any_ operation occurs across any module. Visible UI widgets (panels, workspaces, etc) will reload once, and once only. Invisible UI widgets do nothing, and wait until they become invisible, as reload checks only occur in the draw function.

**Comment by aothms** [comment]
Wonderful work @Moult. With more and more people getting their hands dirty it'll be essential.

**Comment by Moult** [comment]
Pinging @chunchk and @htlcnn (I can't remember who - I vaguely recall one of you asking me about performance implications of the refactor).

**Comment by htlcnn** [comment]
@Moult sorry IIRC I did not ask you about that :)

**Comment by Moult** [comment]
Cheers, all good with it :)

**Comment by Moult** [comment]
A month and a bit later, just another status update that we've now just covered another milestone: 1,000 tests!

It could be just my imagination but I get the "gut feel" that recently things seem a lot more stable, and that recent issues are less and less about core/tool/integration but instead more about UI (or simply incomplete or new features - but not actual bugs). I've also definitely avoided a few regressions with the protection of the test suite :)

**Comment by Moult** [comment]
Another status update! Naturally the number of newly created tests will slow down as over time instead of creating new tests we just edit existing tests. That said, we've now hit 1,500 tests! I can also say for sure that over the past number of commits the tests have successfully protected against several potential regressions, so it's definitely still doing its job and the investment is well made!

**Comment by Moult** [comment]
Finally closing this as we now have hit our arbitrary test target and tests continue to grow. Hooray! Also continue to add value, given that just a few days ago tests caught a critical mistake I made :)
