### ISSUE TITLE
Can the series of utilities based on IfcOpenShell be released to  releases page with the sourcecode ？

### ISSUE THREAD

**Issue by hxboxy-xh** [IfcOpenShell/IfcOpenShell#1713]
in http://ifcopenshell.org/，we can download the products， but dont know the products from which version code？
like this i dont know  the exe from which version code
![image](https://user-images.githubusercontent.com/32007375/131435159-47785448-2fd5-423e-b8d3-69eadab58cb6.png)

**Comment by aothms** [comment]
You can check the URL to which it points e.g

[https://s3.amazonaws.com/ifcopenshell-builds/IfcConvert-v0.6.0-517b819-win32.zip](https://s3.amazonaws.com/ifcopenshell-builds/IfcConvert-v0.6.0-517b819-win32.zip)

**517b819** is then the commit hash.

Unfortunately this hash is not known internally in the executable/module. It's only part of the zip archive.

**Comment by hxboxy-xh** [comment]
![image](https://user-images.githubusercontent.com/32007375/132442616-d900633e-5ad0-411d-855e-345dab52a47f.png)
the exe show 0.6.0b0, so it from the tag 0.6.0b0?

**Comment by aothms** [comment]
No just since the tag. In 0.7 I will find a way to get the commit hash into the build

**Comment by aothms** [comment]
help text also depends on compilation options. what's the actual difference. 

For 0.7 we now lookup the branch and sha during build process https://github.com/IfcOpenShell/IfcOpenShell/commit/3bebfcd8a7fe200d8c7b7b652b66883bed8434c4

**Comment by hxboxy-xh** [comment]
help text has  “--svg-no-css                          Don't emit CSS style declarations” from the code of blenderbim-210910 tag，
and no in ifcconvert.exe in blenderbim-210910-py37-win.zip

**Comment by Moult** [comment]
I can confirm it works :)

```
>>> import ifcopenshell
>>> ifcopenshell.version
'v0.7.0-d99caf15'
```

@hxboxy-xh I didn't quite understand your last post, sorry. Why are you looking at that tag? Those tags are for the BlenderBIM Add-on releases, not IfcOpenShell.
