### ISSUE TITLE
API changes for 0.7

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#1714]
All, as you might have picked up we're in the process of jumping ship from the v0.6.0 branch to the v0.7.0 branch for most development efforts. We have quite slow development cycles. This probably means that if you have some irks with the API (C++ or Python) that you'd like to get addressed, **now** would be a good time to propose so.

- [x]     Logical -> boost tribool
- [x]      C++ Optional attribute access function to return boost::optional<> as opposed to hasName() etc.
- [x]     Link IfcOpenShell/svgfill into IfcConvert
- [x]      Caching of breps and triangulations using HDF5
- [ ]      Fairly extensive restructuring and renaming mostly on the C++ side to get things finally a bit consistent (see below)
- [x]      More efficient inverse attribute mapping. Now we have a map int -> int, so the attribute index and entity type need to filtered later on and make this (int, int, type) -> int, so that the mapping can feed the inverse attribute function directly.
- [x]     Proper handling of inverse attributes on attribute reassignment (only deletion was recently fixed) [edit tk: #1332]
- [x] Proper select implementation.

**Fairly extensive restructuring and renaming mostly on the C++ side to get things finally a bit consistent**

I'm thinking of the following things:

- [ ] Lower case namespaces such as `namespace ifcopenshell { namespace data ` instead of `namespace IfcParse`
- [ ] Merge IfcParse IfcUtil IfcWrite namespaces (the disctinction isn't relevant anymore)
- [x] Rename classes IfcEntityList -> aggregate_of_instance
- [ ] Rename everything related to Argument to attribute_value
- [ ] Try to do something about Material and SurfaceStyle. Combine into separate more general class like `appearance` so that we can also adapt it later for font and line styles. By value semantics so that we can forego of the global map of styles in kernel.

**Proper select implementation**

I considered a couple of options and tentatively think virtual inheritance is our best bet.

* `std::variant<>`. This means that the select instance is quite different from a regular entity/type instance. E.g can't access it's own data or utility functions, can't use the inherited functions from `base` such as `is()` `as<>()`, which it should be able to because all variant members will inherit from it.
* A regular typed schema class for select definitions and non-explicit constructors to cast from concrete classes to the select type. This means one would have different instances for the same data and hence difficulties with equality / identity.
* virtual inheritance. It means that the direction of definition is opposite from the express schema definition. E.g `ifcab = select(ifca, ifcb)` would result in `class ifcab : public virtual base {}; class ifca : public virtual base, public virtual ifcab {}`. But otherwise I couldn't figure out downsides. I don't think the small performance hit due to virtual inheritance from base will be measurable.

**Comment by Moult** [comment]
I'm not sure if this counts as an API irk but handling non-voided breps without OpenCascade (or...CGAL?) for a supposed huge speed boost would be a joy. If HDF5 support was stable, would this mean faster read/write times? Potentially Python access to maxId as described in the other bug report?

**Comment by aothms** [comment]
These are fairly incremental new features. I was thinking backwards incompatible things. The API is super adhoc, surely we must be able to think of things to ease use?

> If HDF5 support was stable, would this mean faster read/write times?

Potentially. ODA was fairly disappointed when they implemented it, so it remains to be seen on real world usage.

> handling non-voided breps without OpenCascade

Can you describe what it would look like? There are already the geom settings DISABLE_OPENING_SUBTRACTION and DISABLE_BOOLEAN_RESULT

- [ ] Python access to maxId

**Comment by Moult** [comment]
Bump, curious what the status of this is?

**Comment by aothms** [comment]
Completely forgot about this issue, thanks for reminder. Everything apart from the C++ refactoring appears to be done, moving that to 0.8.
