### ISSUE TITLE
blenderbim hard olca dependency

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1716]
blenderbim doesn't start without olca:

```
  File "/usr/share/blender/2.93/scripts/addons/blenderbim/bim/module/lca/prop.py", line 21, in <module>
    import olca
ModuleNotFoundError: No module named 'olca'
```

I tried building olca, it depends on java 8, eclipse, and a large number of maven packages, so not straightforward in a typical linux packaging context.

Can we have a check for olca and skip this functionality if it isn't found?

**Comment by brunopostle** [comment]
Looking closer, the olca python module only has minimal (request module) dependencies, so there is no need for all the java stuff so long as you don't need the functionality, closing..

**Comment by Moult** [comment]
Yes just for clarification olca merely is a Python client to the OpenLCA (Java) IPC Server. So all the Python module does is send some network requests to a local server.
