### ISSUE TITLE
Latest 0.6 branch can't parse IFC4x3_RC4 schema?

### ISSUE THREAD

**Issue by sylvainmarie** [IfcOpenShell/IfcOpenShell#1718]
Hello,
I naively pulled the [IFC4x3RC4](http://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC4-voting/EXPRESS/IFC4x3_RC4.exp) schema and hit 'run' (`schema = ifcopenshell.express.parse('IFC4x3_RC4.exp')` ) but to my surprise this didn't as smooth as expected:

`Exception: No declared type for <ENTITY IfcSurfaceFeature
 SUBTYPE OF(IfcFeatureElement);
    PredefinedType : optional IfcSurfaceFeatureTypeEnum;
 INVERSE
    AdheresToElement : IfcRelAdheresToElement FOR RelatedSurfaceFeature;
 WHERE
    HasObjectType : notexists(PredefinedType) or (PredefinedType <> IfcSurfaceFeatureTypeEnum.USERDEFINED) or exists(self\IfcObject.ObjectType);
END_ENTITY;
`

Removing the INVERSE statement in the schema makes IFCOS happy, but I'm not sure it's a good idea 😄 

Any pointers anyone ? 🤔 
Thanks!

(Tested with [#5485177](https://github.com/IfcOpenBot/IfcOpenShell/commit/5485177888497c6ca7bdcebfebb15067bcfc9e55#comments) )

**Comment by aothms** [comment]
I guess this is the same issue I reported earlier. Can you try a "newer RC4"?

https://github.com/bSI-InfraRoom/IFC-Specification/issues/200

**Comment by sylvainmarie** [comment]
Thanks for the pointer!
Indeed, the schema was invalid (oops). A freshly generated schema solves this false positive.
