### ISSUE TITLE
installing on Anaconda does not distribute the files

### ISSUE THREAD

**Issue by aahoo** [IfcOpenShell/IfcOpenShell#172]
System info: Anaconda 3.5 x64 Windows 10 installed in C:\Anaconda3

My installation procedure:

Installed [Visual C++ build tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) and cmake.

Then:
```
git clone https://github.com/IfcOpenShell/IfcOpenShell.git
cd IfcOpenShell/win
set VSINSTALLDIR="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
set IFCOS_INSTALL_PYTHON=FALSE
build-deps.cmd vs2015-x64
```
In `win/BuildDepsCache-x64.txt` file changed the following parameters:
```
PY_VER_MAJOR_MINOR=35
PYTHONHOME=C:\Anaconda3
```
Then:
```
run-cmake.bat vs2015-x64 -DUSE_IFC4=1 -DBUILD_IFCPYTHON=0
build-ifcopenshell.bat
install-ifcopenshell.bat
```
It took some hours for the whole thing to finish. The build and installation folders in IfcOpenShell source folder look fine. But, when I try to import IFCopenShell in Python, it doesn't work. I checked the Anaconda folder, and I couldn't find any trace of IFCopenShell installation.

**Comment by Stinkfist0** [comment]
`-DBUILD_IFCPYTHON=0` - this disables build and installation of the Python parts, so you need to have it `1` instead.

**Comment by aahoo** [comment]
Thank you @Stinkfist0. It fixed the issue.
