### ISSUE TITLE
Accesing geometry in IFC

### ISSUE THREAD

**Issue by devngc** [IfcOpenShell/IfcOpenShell#1720]
Hi @Moult @aothms 

I am using ifcopenshell to access information (currently, geometry only) inside an IFC file. I am using the following code to access geometry;

```
import ifcopenshell
import ifcopenshell.geom

ifc = ifcopenshell.open("some.ifc")
columns = ifc.by_type("IfcColumn")
column = columns[0]

settings = ifcopenshell.geom.settings()
settings.set(settings.USE_BREP_DATA, True)
settings.set(settings.USE_WORLD_COORDS, True)
ifc_shape = ifcopenshell.geom.create_shape(settings, column)
brep = ifc_shape.geometry.brep_data
print(brep)
```

**Questions**
1. Is there a better way to access geometry?
2. I see that the geometry comes in open cascade format. What is the best way to read this open cascade format so that I can read information life vertices, faces, etc?

**Comment by Jesusbill** [comment]
`ifc_shape.geometry` should have `verts`, `edges` and `faces` attributes, perhaps you need not set `USE_BREP_DATA` to True

**Comment by aothms** [comment]
Yes just USE_BREP_DATA=True in itself isn't very useful. It is used behind the scenes when use PythonOCC (https://academy.ifcopenshell.org/posts/using-ifcopenshell-and-pythonocc-to-construct-new-geometry/) so my recommendation is to either use that or as @Jesusbill said, use the default settings and get meshed data that you can use using pure python.

**Comment by Moult** [comment]
Hey @devngc I would recommend using the multicore iterator for its speed. It gives you vertices, faces, and materials.

Code sample here: https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#Geometry_processing

**Comment by devngc** [comment]
Thank you all for your responses @Jesusbill @aothms @Moult  . The triangulated mesh works. However, I am still interested in knowing if there's a way to get un-triangulated faces. I am working on creating a converter from IFC to another format and would like to minimize the number of faces I serialize.

**Comment by aothms** [comment]
There is with (Python)OCC and TopExp_Explorer is the tool to explore the topology of subshapes, so you iterate with that over the faces, inner and outer wires, BRepTools_WireExplorer to get to edges and vertices etc.

**Comment by Moult** [comment]
@devngc alternatively, if you work within the Blender environment (I understand you're porting IFC to Honeybee-JSON so this may not work for you) the limited dissolve works.

**Comment by devngc** [comment]
Thank you all! I was able to use the Part module of FreeCAD to extract Breps. I appreciate your help.
![office](https://user-images.githubusercontent.com/20086924/134221421-ace688c7-3c74-412a-bb98-61e2dd3feebd.jpg)
![Family house](https://user-images.githubusercontent.com/20086924/134221433-7cac94c2-3130-4f0f-b4d8-dba3721950c8.jpg)

**Comment by devngc** [comment]
Hey @aothms, you can definitely count on me to do that. I am new to this OSArch community and I have started liking it. I would like to get more involved and writing this first article sounds like a good starting point to me. Thank you for asking!

**Comment by AlonSpinner** [comment]
I have been able to work with ifcopenshell and pythonocc after solving some issues.
Documented my work pretty much step by step. You are welcome to view it
Aplogizes for the code 
https://github.com/AlonSpinner/IFC-Demos

**Comment by aothms** [comment]
@AlonSpinner I didn't manage yet to take a detailed look, but our tutorial repo supports ipy notebooks. It'd be awesome if some of your works make it up there :)

result:

https://academy.ifcopenshell.org/

repo:

https://github.com/IfcOpenShell/academy

An .ipynb in the posts/ folder with some metadata suffices 

e.g https://raw.githubusercontent.com/IfcOpenShell/academy/main/posts/ifcopenshell-optimizer-tutorial.ipynb

~~~json
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  },
  "nikola": {
   "category": "",
   "date": "2020-09-28 14:56:00 UTC+02:00",
   "description": "",
   "link": "",
   "slug": "ifcopenshell-optimizer-tutorial",
   "tags": "",
   "title": "IfcOpenShell Optimizer tutorial",
   "type": "text",
   "author": "Johan Luttun"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
~~~

**Comment by Moult** [comment]
Closing as I think this has been resolved and @devngc has been able to work with IFC geometry.
