### ISSUE TITLE
lxml package not found

### ISSUE THREAD

**Issue by atomczak** [IfcOpenShell/IfcOpenShell#1727]
When trying to run BIMTester on IDS file I get 'lxml' import error.

![image](https://user-images.githubusercontent.com/22922395/132344441-b53becda-5ee8-4b1a-81f6-9eedf131d087.png)

When I add that package manually to "...\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages" it still says: 
 
![image](https://user-images.githubusercontent.com/22922395/132344710-d4ca5103-9edf-40a2-9303-7d7e81f1b255.png)

**Comment by atomczak** [comment]
added requirements.txt and edited conda yaml file. Let me know if I can help from the IDS side.

**Comment by aothms** [comment]
I think this should be done in the blenderbim makefile https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/Makefile#L144

**Comment by Moult** [comment]
FYI the error you got is likely that you didn't use the correct lxml (don't get the .tar.gz source) built for your platform / python version combo.
