### ISSUE TITLE
Sorting element RelatingMaterial.Materials with shape geometry

### ISSUE THREAD

**Issue by MAX4ARCH** [IfcOpenShell/IfcOpenShell#1728]
Hello, is there any solution to sort element RelatingMaterial.Materials with  shape geometry?

```
bricklist = ifc_file.by_type('IfcBuildingElement')
for brick in bricklist:
   shape = geom.create_shape(settings, brick)
   for assoc in brick.HasAssociations:
   if hasattr(assoc.RelatingMaterial, 'Materials'):
      for mat in assoc.RelatingMaterial.Materials:
         matl.append(assoc.RelatingMaterial.Name)
      else:
         matl.append(assoc.RelatingMaterial.Name)
```
Also tried with 
`brick.HasAssociations[0].RelatingMaterial.Materials[x].Name` where x goes with `for color in shape.geometry.materials:` x = x + 1

I can get shape.geometry.materials, but this doesn't give me "building material" name only surface name:
![image](https://user-images.githubusercontent.com/6853921/132485365-ea308fc0-05fb-4872-b6cc-bf5ea9b42bac.png)

Here what I get with RelatingMaterial.Materials
![image](https://user-images.githubusercontent.com/6853921/132485525-09c96e7a-9b5e-4ae7-8f89-be415b19ccb1.png)

I also tried with iterator and got the same result

**Comment by aothms** [comment]
Hi, this depends on the type of `RelatingMaterial`. If this is just an IfcMaterialList (it seems so, I guess) https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/schema/ifcmaterialresource/lexical/ifcmateriallist.htm then I don't think there is a lot you can do. 

> I can get shape.geometry.materials, but this doesn't give me "building material" name only surface name:

Perhaps you can still go from surface style to material. If you iterate over all materials and look at their `HasRepresentation` attributes you might be able to uncover the relationship from surface style to material.

**Comment by MAX4ARCH** [comment]
Aothms, thank you very much, finally I figured that out with your recomendation. 

Made a while loop inside `for color in shape.geometry.materials` with checking of `brick.HasAssociations[0].RelatingMaterial.Materials[x].HasRepresentation[0].Representations[0].Items[0].Styles[0][0][0].Name.lower()` with `' '.join(color.name.split('surface-style-')[1].replace('---',' #dash# ').split('-')[1:]).replace('#dash#','-')` . 

At the end it looks little dirty but it worked out!

**Comment by MAX4ARCH** [comment]
I have next issue with the materials: 
I got relating material name sorting based on the same geometry material color name working, but now I'm trying to get the same work with "Override Surfaces"(Archicad for example), which gives me different color name. Could you point me again to where to look at?

**Comment by MAX4ARCH** [comment]
Almost solved with: `brick.Representation.Representations[0].Items[x].StyledByItem[0][1][0][0][0]`, going to update and close this post after.

**Comment by MAX4ARCH** [comment]
Finally I found a way to get the id with: `brick.Representation.Representations[0].Items[x].StyledByItem[0].Styles[0].Styles[0].__dict__['id']`
Please correct me here if there is a cleaner solution

**Comment by Moult** [comment]
@MAX4ARCH not all styles have a corresponding material. It may be in that in ArchiCAD it generates a style which only relates to geometry, not material.
