### ISSUE TITLE
New entity created with ID 0

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1732]
I am performing some scripted file cleanups (changing geometric precision, changing shape representations, deep removal of old shape representations). After I finish the cleanup, I noticed that a simple `ifc_file.createIfcColourRgb()` creates an IfcColourRgb with an ID of 0.

I am struggling to debug it and don't know where to look. Any hints? I'll keep on looking, but if I knew what might be suspicious it would help tremendously :)

I cannot replicate it on blank files or simple files.

**Comment by aothms** [comment]
Will it constantly assign 0 as the ID, or will it later increment again to 1?

There is the possibility in theory that the counter would overflow, practically I don't think this will happen.

Other option is just memory corruption, some low level C++ issue that caused data to be written were it shouldn't have. Although if you don't experience any other issues, it's a very very precise corruption.

I also wouldn't rule out the transaction code in python. Since there we implemented the logic to explicitly set ids.

It could also be perhaps the IFC graph somehow got a bit corrupted so that the C++ IfcFile::addEntity() somehow partially fails or behaves wrongly. 

In particular there is the IfcFill::entity_file_map which is kind of broken by design and it could be that this is what we're seeing now. Instances don't have an intrinsic identity and we don't (want to?) compare by value. So when you add() the same instance multiple times, deduplication happens based on the memory pointer address (which can get recycled when data is deleted). If this causes the issue (most likely) we probably need to have a global auto incrementing integer in the instances and use this for identity (so some extra memory usage)

**Comment by Moult** [comment]
To see whether it constantly assigns 0 as the ID or later increments it, I checked like this:

```
                colour = self.file.createIfcColourRgb(None, 0, 0, 0)
                print('the colour is', colour)
                colour = self.file.createIfcColourRgb(None, 0, 0, 0)
                print('the colour is 2', colour)
                colour = self.file.createIfcColourRgb(None, 0, 0, 0)
                print('the colour is 3', colour)
```

... and I got this result. Sometimes, all three would be perfectly normal. In some cases, the 2nd one would be abnormal, but 1st and 3rd would be normal, but maybe it's just luck.

```

the colour is #29299=IfcColourRgb($,0.,0.,0.)
the colour is 2 #0=IfcColourRgb($,0.,0.,0.)
the colour is 3 #29300=IfcColourRgb($,0.,0.,0.)

[ ... snip ... ]

the colour is #96364=IfcColourRgb($,0.,0.,0.)
the colour is 2 #96365=IfcColourRgb($,0.,0.,0.)
the colour is 3 #96366=IfcColourRgb($,0.,0.,0.)

[ ... snip ... ]

the colour is #96369=IfcColourRgb($,0.,0.,0.)
the colour is 2 #0=IfcColourRgb($,0.,0.,0.)
the colour is 3 #96370=IfcColourRgb($,0.,0.,0.)
```

**Comment by Moult** [comment]
I also disabled transactions by returning on [this function](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/file.py#L207). Same result. Note that no undo or redo occurs.

**Comment by Moult** [comment]
I can also confirm that if I don't do my file cleanup (specifically, I am updating shape representations, which I guess include styles) then I don't run into this problem. I also seem to run into it on larger files (but by large I'm talking 2-3mb files, so not large at all), compared to smaller files (~600kb).

To further this mystery, here's what I tried:

```
        print('test1', self.file.createIfcColourRgb())
        print('test2', self.file.createIfcColourRgb())
        print('test3', self.file.createIfcColourRgb())
        print('test4', self.file.createIfcColourRgb())
        print('test5', self.file.createIfcColourRgb())
        print('test6', self.file.createIfcColourRgb())
        print('test7', self.file.createIfcColourRgb())
        print('test8', self.file.createIfcColourRgb())
        print('test9', self.file.createIfcColourRgb())
        print('test1', self.file.createIfcPerson())
        print('test2', self.file.createIfcPerson())
        print('test3', self.file.createIfcPerson())
        print('test4', self.file.createIfcPerson())
        print('test5', self.file.createIfcPerson())
        print('test6', self.file.createIfcPerson())
        print('test7', self.file.createIfcPerson())
        print('test8', self.file.createIfcPerson())
        print('test9', self.file.createIfcPerson())
```

Only IfcColourRgb is affected, not IfcPerson. This happens statistically often enough that I'm pretty sure it's not a luck thing. There seems to be a preference to the class type of IfcColourRgb.

Also, when it does happen (note: sometimes, it goes perfectly without issues), only the _second_ IfcColourRgb has an ID of zero. Never the first, never other ones ... always the second. Like this:

```
test1 #96759=IfcColourRgb($,$,$,$)
test2 #0=IfcColourRgb($,$,$,$)
test3 #96760=IfcColourRgb($,$,$,$)
test4 #96761=IfcColourRgb($,$,$,$)
test5 #96762=IfcColourRgb($,$,$,$)
test6 #96763=IfcColourRgb($,$,$,$)
test7 #96764=IfcColourRgb($,$,$,$)
test8 #96765=IfcColourRgb($,$,$,$)
test9 #96766=IfcColourRgb($,$,$,$)
test1 #96767=IfcPerson($,$,$,$,$,$,$,$)
test2 #96768=IfcPerson($,$,$,$,$,$,$,$)
test3 #96769=IfcPerson($,$,$,$,$,$,$,$)
test4 #96770=IfcPerson($,$,$,$,$,$,$,$)
test5 #96771=IfcPerson($,$,$,$,$,$,$,$)
test6 #96772=IfcPerson($,$,$,$,$,$,$,$)
test7 #96773=IfcPerson($,$,$,$,$,$,$,$)
test8 #96774=IfcPerson($,$,$,$,$,$,$,$)
test9 #96775=IfcPerson($,$,$,$,$,$,$,$)
```

Notice no ID is skipped (e.g. 96759, 0, 96760...).

If it helps, this is the line of code that triggers the error (obviously without my print statement tests): https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/style/edit_surface_style.py#L35 - however it doesn't seem limited to that function in that file, I can create the entities in the execute() function with the same bug.

That `edit_surface_style` usecase is run when I export in Blender (it syncs Blender colours with IFC colours). If before I export (but after I run my cleaning script) I go into the Blender python interactive console and fetch the session's IFC file and createIfcColourRgb over there (say for i in range(1,100)) I cannot recreate the bug, so perhaps to trigger it I first have to access something in a particular order in the IFC file.

**Comment by aothms** [comment]
Quite strange that it has a preference for entity types, that's not in line with what I expect with the entity_file_map thing, memory address collisions shouldn't happen based on types (unless they do, compilers can do whatever they want of course)

Hope it's not too much to ask the following:

* create a function in IfcFile like `void clear_entity_map() { entity_file_map.clear(); }`
* call this function once after you're done with your "file cleanup" in python and before your "colour creation"
* observe whether the problem still persists

**Comment by aothms** [comment]
As promised https://github.com/IfcOpenShell/IfcOpenShell/commit/7661899e9d6e72bd72e72c14ed128bd05a40ee40

**Comment by Moult** [comment]
I don't fully understand the mechanics behind it, but are you saying that once I migrate to v0.7 this'll be fixed?

If so, hooray! I'll look to migrate this week and retest, as well as close this bug :)

**Comment by aothms** [comment]
Yes, I hope so. The mechanism is that pointer addresses will get recycled, but the auto incrementing id in IfcBaseClass will not. The assumption is that the issue is caused by collisions with prior added instance addresses, which is I'd say very likely. But I didn't find a way to verify the fix.

**Comment by aothms** [comment]
@Moult were you able to a quick test?

**Comment by Moult** [comment]
Sorry not yet, since I'm waiting on #1734 which doesn't allow my script to be run :( and it looks rather tricky ... #1734 also blocks a basic project creation operation in the BlenderBIM Add-on (since it creates and manages subcontexts), so I've been unable to roll out v0.7.0.

**Comment by Moult** [comment]
Awesome! I can confirm that it seems to be fixed now (at least in my test script it has) :) Thanks so much!
