### ISSUE TITLE
blenderbim error viewing IFC Connected Structural Members

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1733]
The [attached model](https://github.com/IfcOpenShell/IfcOpenShell/files/7148545/tmpfub5ghzg.ifc.zip) has twelve structural curve connections.

If I select any of these curve connections and expand **IFC Connected Structural Members**, then I see two or three members in the list as expected. This list changes (as expected) as I select different curve connections.

If I then select one of the previously selected curve connections, I get this error:

```
location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/addons/blenderbim/bim/module/structural/ui.py", line 154, in draw
    rel = Data.connects_structural_members[rel_id]
KeyError: 1299

**Comment by aldomontanari** [comment]
@brunopostle Following this, I don't get any error but **IFC Connected Structural Members** just dssapear from the list the second time I select an IFCStructuralCurveConnection.
I'm using blender v 3.0 and belnderBIM v 0.0.210820

**Comment by Moult** [comment]
I should mention that I think we need a better solution for the data state machine. Especially with parametric behaviour, we either need to purge everything on each operation, or rely on operators being more and more defensive. Neither are very nice solutions.

The correct architecture would be a complete state machine with no overlaps between modules that acts as a source of truth on what an IFC element is.
