### ISSUE TITLE
BB: Linking IFC only shows blender files.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1736]
might be missing something, but dialog box doesn't seem to allow filtering for IFC files... only Blender files.
https://www.dropbox.com/s/k6q7grafo9h696q/2021-09-14_09-19-44.mp4?dl=0

blenderbim-210913

**Comment by Moult** [comment]
Yes this is by design. Right now, 1 Blender hosts 1 primary IFC. For the moment, to link that primary IFC, you navigate to its Blender file.
