### ISSUE TITLE
Blenderbim tests assume startup file contains a cube

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1745]
Most tests that are related to blender objects assume there is a cube in the default startup file.
See https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/test/bim/module/void/test_operator.py#L100
I modified mine (File > Defaults > Save startup file) so that it contains no object at startup, so these tests fail when trying to select the cube.

A few ideas to fix this :
- Run a test blend file from within the test folder so we know for sure what it contains
- Create and use a brand new object for tests
- Test if the cube exists, and if not create it

I can contribute to make the changes if you feel like it's worth it.

**Comment by Moult** [comment]
Let's not make assumptions, you're absolutely correct :) Perhaps just modify the tests to say "Given I add a cube"

**Comment by Gorgious56** [comment]
Alright ! 
Oh the joys of getting objects by name :)
If the startup file does already contain the default cube, then the newly added cube will be named "Cube.001".
Adding another one, and it will be named "Cube.002".

 So maybe we can use

        Given I add a cube
        When the object "Cube" is selected # This either selects the default cube is there is one or the newly created one

But this becomes awkward : https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/test/bim/module/root/test_operator.py#L124-L126
I think it still works, although in one case we get a leftover cube that won't be used in the test.
This leaves us with only one assumption which I guess we can live with :
- There can be any number of objects which name begins with "Cube" in the startup file, but they must all be of type `MESH`

OR alternatively we could add a definition like `Given I add a cube named {name}` and then we know for sure the name is respected.

**Comment by Moult** [comment]
If `test.bim.bootstrap.NewFile` purged all objects, then we always start empty :)
