### ISSUE TITLE
BB: a way to do a 'save as' to another IFC file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1749]
Would be nice to have a way to do something similar to a 'save as', and resave the IFC to another file, with a different name. 

Is a small potatoes feature request, but nice. 
![image](https://user-images.githubusercontent.com/507113/134546818-502aa68f-261c-4a17-8387-1e1919731a33.png)

**Comment by Gorgious56** [comment]
Just to be clear on the feature request, the new saved file should act as the active current file on the project, right ?

**Comment by theoryshaw** [comment]
correct.  sorry, missed your reply.
