### ISSUE TITLE
Info method to list all the attributes and values

### ISSUE THREAD

**Issue by aahoo** [IfcOpenShell/IfcOpenShell#175]
I have written this convenience function that aggregates all the attributes and values of an entity. I thought you might consider adding it as a method to entities. `try/except` is used because some attributes do not exist.

```python
def info(obj):
  _info = {}
  try:
    _info["id"] = obj.id()
    _info["type"] = obj.is_a()
  except:
    pass
  for i in range(len(obj)):
    try:
      _info[obj.attribute_name(i)] = obj[i]
    except:
      pass
  return _info
```

**Comment by aothms** [comment]
Hi, thanks for this. Perhaps a more pythonic way to approach something like this would be to add a `__dict__` property to the `entity_instance` class that would basically invoke your method.

That way people can invoke the builtin `vars()` function. See the example below:

~~~
>>> class A(object):
...     def _make_dict(self): return {'a': 1}
...     __dict__ = property(_make_dict)
...
>>> vars(A())
{'a': 1}
~~~

A pull request would be very welcome! :)
