### ISSUE TITLE
Blenderbim: RuntimeError No schema named IFC4

### ISSUE THREAD

**Issue by spl1inter** [IfcOpenShell/IfcOpenShell#1752]
Hi guys,

Back again with a new chapter, since MSYS2 has blender 2.8+ I downloaded and backported [that](https://packages.msys2.org/package/mingw-w64-x86_64-blender?repo=mingw64)..

There were a few (undocumented)dependencies going from ifcopenshell to full blenderbim ( nothing impossible to compile on MinGW64-MSYS2 but, again, obviously _packaged_ previously to someone's personal Linux bias... ;)  So all that done and _still I get this error in Blender which you will understand but means nothing to me..
![blenderbim_mingw-error_001](https://user-images.githubusercontent.com/41893923/134586135-f9df6459-b582-44bf-9060-b443fd716ae7.png)

Edit.. somehow the image window cut the last line although I'm staring at it on screen... the bit missing then is..
`RuntimeError: No schema named IFC4`

I can bet a couple of guesses but none of them are consistent with the coding standard here. At the end of the day I thought that this was, after all, just a plugin..

**Comment by Moult** [comment]
I unfortunately don't know anything about MSYS2, but I see you're on a much older version of Blender. Can I first confirm that you are grabbing one of the releases from the daily builds that have `py37` in the name? I'd like to confirm exactly how you are installing the BlenderBIM Add-on.

**Comment by spl1inter** [comment]
I was compiling from the source release of the 0.7.0 branch cloned maybe two weeks ago..

Following the error for myself I found the actual problem using an interactive prompt inside your code:
```
>>> ifcopenshell._ifcopenshell_wrapper.schema_by_name("IFC4")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No schema named IFC4
>>> ifcopenshell._ifcopenshell_wrapper.schema_by_name("IFC4x3_rc4")
<schema IFC4X3_RC4>
```
So bingo. Not only can Windows dll only carry _no more than two schemas at a time_, one of those schemas **_must_** be "4" if you are even considering trying blenderbim. The whole situation is very obscure.

**Comment by brunopostle** [comment]
@spl1inter the v0.7.0 branch is not ready for running blenderbim, and certainly wasn't two weeks ago. You need to be using the v0.6.0 branch

**Comment by spl1inter** [comment]
That's the impression I have as well. Unfortunately the 0.6.0 branch is unusable in MinGW without significant dllexport and template reworking. I was forced to stay on 0.5.0 branch for this reason until 0.7.0 became available. I understand from the git record that 0.7.0 is now the main branch so this should at least be interesting for you..

**Comment by Moult** [comment]
I recall there was a bug where the IFC4 schema wasn't compiled. Does this help: https://github.com/IfcOpenShell/IfcOpenShell/issues/1705#issuecomment-916705332 ?

**Comment by spl1inter** [comment]
Like I said, windows monolithic geom dll only has room enough for two schemas. 'IFC4' wasn't compiled because [I didn't select it](https://github.com/IfcOpenShell/IfcOpenShell/issues/1029#issuecomment-871650453).

**Comment by Moult** [comment]
The reason the BlenderBIM Add-on requires the IFC4 schema right now is because it uses the property set templates from IFC4 as a default (none exist for IFC2X3, sadly). But yes, as this isn't exactly a bug, and 4.3 isn't released, this can be closed.
