### ISSUE TITLE
BB: automatically updating the representation 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1756]
related to #1748

Would streamline modeling and authoring if the 
![image](https://user-images.githubusercontent.com/507113/134787283-698e1c5a-5151-4d07-8e76-68df57c1453c.png)
automatically updated upon manually changing the extrusion depth. 
Or at least provide a preference to do this.

**Comment by Gorgious56** [comment]
When you say "manually" changing the extrusion depth, are you talking about changing the actual vertices position in edit mode or tweaking the field in the properties panel ?

**Comment by theoryshaw** [comment]
Hi, changing the vertices position in edit mode.

**Comment by theoryshaw** [comment]
Like this: https://www.dropbox.com/s/rtktvud4diut510/2021-09-29_20-49-22.mp4?dl=0

**Comment by Moult** [comment]
If the issue is actually getting a real time feedback of the new extrusion depth, the Blender dimensions side panel already provides this information.

**Comment by theoryshaw** [comment]
>  So updating the geometry every time you toggle edit mode (note there is no cheap way to check whether you actually did make a change, or if you just toggled edit mode) is very expensive. 

Dumb question, how about 'updating the representation' automatically after you exit out of edit mode?

Because I click 'Update Representation' a lot! :)  It might be expensive, but don't you have to do it regardless, when you change something?  In other words, what are the use cases where you edit geometry, and not want it to update the representation?

95% of the time, I'm only editing one object--so it's typically not that expensive, I would gather. 

---

Or, how about bulk updating the representation of all the objects in the scene when you hit 'export'?  I'm sure this is expensive, but peeps are used to waiting on a 'save'.

**Comment by Moult** [comment]
You don't need to click update representation unless you're just about to switch representation. It should auto sync on export as you've described.

**Comment by Moult** [comment]
Bump - potentially with the new fixes this should also now be solved?

**Comment by theoryshaw** [comment]
Yes it exports out correctly!

The only other suggestion, is somewhat a UI suggestion.
https://www.dropbox.com/s/5dzrnzqo3duir8d/2021-11-06_12-32-39.mp4?dl=0

Would expect the IfcExtrudedAreaSolid/Depth to update as well.

**Comment by Moult** [comment]
Geometry is only synchronised automatically during export, so unfortunately the parameters will not auto update. If you want it synchronised prior to export, you can press the "Update Representation" manually.
