### ISSUE TITLE
v0.7.0 SONAME is still set to 0.6.0

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1760]
In CMakeLists.txt `VERSION "0.6.0" SOVERSION "0.6"` is still set in multiple places.

**Comment by Moult** [comment]
This sounds like a suspiciously easy fix, is there any reason we don't just replace it to 0.7.0? @aothms

**Comment by aothms** [comment]
I guess we should find an approach to unify the places where version is currently being defined. E.g also in IfcParse.cpp

**Comment by Moult** [comment]
Is this resolved in 0.8.0?
