### ISSUE TITLE
[Solved] How to deal with IfcNonNegativeLengthMeasure or other 'Select' types

### ISSUE THREAD

**Issue by sylvainmarie** [IfcOpenShell/IfcOpenShell#1762]
Hi,
I am using the new-ish IFC4x3 schema (IFC4X3_RC4 dated September 3rd 2021, generated from https://github.com/bSI-InfraRoom/IFC-Specification/commit/467dabf65ccc300b1c552abeff8dbdf16496e560), I'm trying to create some IfcCurveSegment.

When requesting the class definition for IfcCurveSegment:
```
mySchema = ifcopenshell.ifcopenshell_wrapper.schema_by_name("IFC4X3_RC4")  
curveDef = mySchema.declaration_by_name("IfcCurveSegment") 
print(curveDef.all_attributes())
```
I get some reassuring info:
```
(<attribute Transition: <enumeration IfcTransitionCode: (CONTINUOUS, CONTSAMEGRADIENT, CONTSAMEGRADIENTSAMECURVATURE, DISCONTINUOUS)>>, <attribute Placement: <entity IfcPlacement>>, <attribute SegmentStart: <select IfcCurveMeasureSelect: (<type IfcNonNegativeLengthMeasure: <type IfcLengthMeasure: <real>>> | <type IfcParameterValue: <real>>)>>, <attribute SegmentLength: <select IfcCurveMeasureSelect: (<type IfcNonNegativeLengthMeasure: <type IfcLengthMeasure: <real>>> | <type IfcParameterValue: <real>>)>>, <attribute ParentCurve: <entity IfcCurve>>)
```
which leads me to think I can use IfcNonNegativeLengthMeasure (which actually stands for 'real') to define the SegmentStart attribute.

Alas, when creating a CurveSegment :
```
curve_segment = ifcfile.createIfcCurveSegment("CONTSAMEGRADIENTSAMECURVATURE", some_axis_placement, 0.3, 400., some_line) 
```

I get this error I don't understand:
```
raise ValueError(
ValueError: Expected EntityInstance for attribute IfcCurveSegment.SegmentStart, got 0.3
```

Any help appreciated :-)

**Comment by aothms** [comment]
You can use it, but it's a select of IfcNonNegativeLengthMeasure | IfcParameterValue, both 'real'. So you need to fully qualify it as 

~~~
ifcfile.createIfcCurveSegment("CONTSAMEGRADIENTSAMECURVATURE", some_axis_placement,
    ifcfile.createIfcNonNegativeLengthMeasure(0.3),
    400., some_line) 
~~~

~~~
<attribute SegmentStart: <select IfcCurveMeasureSelect: (<type IfcNonNegativeLengthMeasure: <type IfcLengthMeasure: <real>>> | <type IfcParameterValue: <real>>)>>
~~~

This is the case for all select definitions in the schema. They always need to be passed as instances in IfcOpenShell.

**Comment by sylvainmarie** [comment]
Perfect, thank you for the almost immediate answer :-)
