### ISSUE TITLE
get_psets "swallows" psets that have the same name

### ISSUE THREAD

**Issue by Nitschi** [IfcOpenShell/IfcOpenShell#1763]
Unfortunately I have an ifc file that contains elements which have multiple psets with the same name.
This lead to the util.get_psets(element) method to return only one of the psets because the keys are the same.

Concerns this file: [element.py](https://github.com/IfcOpenShell/IfcOpenShell/blob/768b754a0b4ccc82e2288037289aa16ce9e26afa/src/ifcopenshell-python/ifcopenshell/util/element.py)

Are there any ideas how to solve this?
My first thought was something like this, but it would change the return type to Dict[str : List[ str ]]:

```
def get_psets(element):
    psets = defaultdict(list)
    try:
        if element.is_a("IfcTypeObject"):
            if element.HasPropertySets:
                for definition in element.HasPropertySets:
                    psets[definition.Name] += get_property_definition(definition)
        else:
            for relationship in element.IsDefinedBy:
                if relationship.is_a("IfcRelDefinesByProperties"):
                    definition = relationship.RelatingPropertyDefinition
                    psets[definition.Name] += get_property_definition(definition)
    except Exception as e:
        import traceback

        print("failed to load properties: {}".format(e))
        traceback.print_exc()
    return psets
```

If this is to obscure I can write my own version and use that, but I thought I would report the potential error anyway.

**Comment by Moult** [comment]
If your IFC contains multiple psets with the same name, it is invalid. This is written in the specification as per 5.1.4.5 IfcUniqueDefinitionNames, so this feature is behaving as expected.

You might want to report a bug to the vendor who created the file?

**Comment by aothms** [comment]
>  My first thought was something like this, but it would change the return type to Dict[str : List[ str ]]:

Yes I wouldn't propose to change the API to accomodate invalid files, but if you'd just merge the dictionaries for duplicate propertysets and log a warning that a merge has occured I wouldn't be opposed of a Pull Request to incorporate that. It's better than silently overwriting, even if the file is to blame.

Something like: (untested)

~~~
di = psets.get(definition.Name, None)
if di is not None: # log warning
else: di = {}
di.update(get_property_definition(definition))
psets[definition.Name] = di
~~~

**Comment by Nitschi** [comment]
The problem with my ifc file seems to be deeper than initially thought.
Bimvision shows the duplicate psets, while Open IFC Viewer and ifcopenshell does not come accross them (not even if I debug within the get_psets() method)

My proposed solution would therefore not work in this case. as the second pset would not show up when iterating over the "HasPropertySets" and "IsDefinedBy".

For later reference if something like merging Psets would actually be needed the code below should work and behaves as expected as far as I can tell from one example I created.

If someone has time for a PR they can test and use this:

```
def get_psets(element):
    psets = {}
    try:
        if element.is_a("IfcTypeObject"):
            if element.HasPropertySets:
                for definition in element.HasPropertySets:
                    if definition.Name in psets:
                        print(f"Warning: Invalid File: Element Psets with same name will be merged")
                        psets[definition.Name].update(get_property_definition(definition))
                    psets[definition.Name] = get_property_definition(definition)
        else:
            for relationship in element.IsDefinedBy:
                if relationship.is_a("IfcRelDefinesByProperties"):
                    definition = relationship.RelatingPropertyDefinition
                    if definition.Name in psets:
                        print(f"Warning: Invalid File: Element Psets with same name will be merged")
                        psets[definition.Name].update(get_property_definition(definition))
                    psets[definition.Name] = get_property_definition(definition)
    except Exception as e:
        import traceback

        print("failed to load properties: {}".format(e))
        traceback.print_exc()
    return psets
```

**Comment by Nitschi** [comment]
Note that if the Psets have entries with the same Pname, the entry from the Pset occurring last overwrites the values from previous psets. It basically pushes the problem one level down...
