### ISSUE TITLE
BlenderBIM - BIM Life Cycle Assessment freezes Blender

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1764]
Opening the "BIM Life Cycle Assessment" panel freezes Blender - Only way to continue is to terminate in task manager

Blender Version: 2.93.2
BB Version: 210930

**Comment by Moult** [comment]
Thanks, will fix but for a temporary workaround, it can only be opened if and only if you already have an OpenLCA IPC server running. The port can be set in the add-on settings.
