### ISSUE TITLE
Should removing an element ensure cardinality is correct in IfcOpenShell core?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1766]
```python
>>> import ifcopenshell
>>> ifcopenshell.version
'v0.7.0-7155f7ce'

>>> f = ifcopenshell.file()
>>> p = f.createIfcPerson()
>>> r = f.createIfcActorRole()
>>> p.Roles = [r]
>>> f.remove(r)
>>> p.Roles
()
```

The cardinality of `IfcPerson.Roles` is `? L[1:?]`. Should the remove() call be intelligent enough to preserve the correctness of the cardinality? I.e. should it instead make p.Roles = None?

I can understand if this is too complex (e.g. what is the cardinality is `L[1:?]` instead?). I have been writing code to handle these scenarios in the IfcOpenShell API, but it would be good to know whether or not it belongs upstream in C++ or downstream in Python, or if a general solution is even possible.

**Comment by aothms** [comment]
> should it instead make p.Roles = None

At least given that we have the full schema present, it's possible. For this case specifically it's just near [0] `checking instance_list->size()` and `related_instance->declaration().as_entity()->all_attribute()[i]->is_optional()` and `->type_of_attribute()` etc. That would be a bit ad hoc, ideally it'd be a bit more general and configurable, but then the complexity skyrockets out of control.

[0] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcParse.cpp#L2035

> e.g. what is the cardinality is L[1:?] instead?

Throw an exception? Also that is not impossible. Just as easy basically, just need to make sure it doesn't leave us in an incorrect state. Maybe some sort of "strict mode" users can enable to enforce integrity?

I don't know, I don't have strong opinions on this. But in general we should help people write files as valid as possible.

**Comment by Moult** [comment]
Cheers. PR submitted. Indeed I cannot think of a general solution, but hopefully the PR will make cases more valid in a lot more situations. I'll keep a close eye on the remove API code and see if any other good strategies emerge. This at least will allow me to remove about half of the special handling code I have in the API.

**Comment by Moult** [comment]
In the future, a strict mode would definitely be something to consider. For now, I don't think it's a big issue, as after all as we create objects cardinality is not enforced as well. BTW tests now document this behaviour.
