### ISSUE TITLE
Readme examples are outdated or have broken links

### ISSUE THREAD

**Issue by m-clare** [IfcOpenShell/IfcOpenShell#1770]
The [sample links](https://github.com/IfcOpenShell/IfcOpenShell#usage-examples) provided for testing out IfcOpenShell are either outdated schema or broken.

```{bash}
$ wget ftp://ftp.dds.no/pub/ifc/Munkerud/Munkerud_hus6_BE.zip
$ unzip Munkerud_hus6_BE.zip
$ ./IfcConvert Munkerud_hus6_BE.ifc
$ less Munkerud_hus6_BE.obj
```

Running this command results in: ```ifcopenshell.SchemaError: Unsupported schema: IFC2X2_FINAL```. On looking at my build results for ```v0.7.0```, it appears that the oldest Serializers that are built are ```ifc2x3```, so I don't know if this is just a build config issue and 2x2 should be built.

```{bash}
$ wget -O duplex.zip https://portal.nibs.org/files/wl/?id=4DsTgHFQAcOXzFetxbpRCECPbbfUqpgo
```

Results in:
```{bash}
zsh: no matches found: https://portal.nibs.org/files/wl/?id=4DsTgHFQAcOXzFetxbpRCECPbbfUqpgo
```

**Comment by aothms** [comment]
Judging from the page here [0] I think Duplex moved to [1]

[0] https://www.wbdg.org/bim/cobie/common-bim-files
[1] https://portal.nibs.org/files/wl/?id=O9inoVWDytV4P3UTS7iIdqhVKcTyVlcs

We can also replace the Munkerud example with duplex I guess. 

Would you care to make these changes?

You're right, 2x2 was never really supported, but in earlier versions we still parsed files of unknown schema identifiers.

**Comment by m-clare** [comment]
On closer inspection, the wget link does work, but the ```?``` needs to be escaped. I submitted #1774 to fix the other link.
