### ISSUE TITLE
Do we still want to maintain python 2.7 on 0.7.0?

### ISSUE THREAD

**Issue by Amoki** [IfcOpenShell/IfcOpenShell#1776]
It complexifies the build, many tools (BCF, bsdd) are python3 only.
I'm currently updating `build-all.py`, I can submit a PR for this file.

EDIT: Same question for python < 3.6 which are already unmaintained. The end of life of python 3.6 is scheduled for 2021-12-23. (source: https://devguide.python.org/#status-of-python-branches)

**Comment by aothms** [comment]
Hi @Amoki I just merged https://github.com/IfcOpenShell/IfcOpenShell/pull/1777 it kept 2.7 and 3.5 though. For 0.7 I'm fine with everything. Let's just eliminate up to and including 3.6. At the very least it'll reduce the build time significantly for the IfcOpenBot builds. I think there is also some old remnants regarding PyUnicode PyBytes that can be discarded when no longer supporting <= 3.2

**Comment by Amoki** [comment]
OK, I'm removing python <= 3.5.
I'm also replacing `%` and `.format()` with f-strings and improving configuration with some more env variables.

**Comment by aothms** [comment]
That'd be great. There is some weird stuff in there, e.g get_os() calling `uname` instead of using the native python `platform` module. 

A lot of try except instead of os.environ.get(key, **default**)

In the long run I'd also be very interested in the ability to run it on Windows.

No pressure though, just listing some of my own concerns for the future.

**Comment by Amoki** [comment]
I'm not using Windows, I won't be able to help on that but `os.getenv()` and stuff like that will be included :)

Is svgfill required to build IfcOpenShell or I can make it optional?

OpenCOLLADA is a required dependency on IfcGeom in targets and I'd like to make it optional. Should it be enabled or disabled by default?

**Comment by aothms** [comment]
> Is svgfill required to build IfcOpenShell or I can make it optional?

I think it should be optional, but currently it isn't in the code. I can work on that.

> OpenCOLLADA is a required dependency on IfcGeom in targets and I'd like to make it optional. Should it be enabled or disabled by default?

What do you mean by default? You mean through env vars? I guess if you want that kind of control from the outside we should look at argparse or something?

**Comment by Amoki** [comment]
> I think it should be optional, but currently it isn't in the code. I can work on that.

Could be awesome. svgfill seems to have its own dependencies and my first attempt to build it failed.

> What do you mean by default? You mean through env vars? I guess if you want that kind of control from the outside we should look at argparse or something?

Through env var at first, but yes, I think an argparse could be really useful!

**Comment by Amoki** [comment]
What is the purpose of building many python versions?
The most common python use-case is IMHO to install IfcOpenShell in the current python environment (system or virtualenv) to use ifcopenshell-python module.

**Comment by aothms** [comment]
Yes this is selfishly mostly/only for creating the builds on the website. I.e IfcOpenBot relies on this: https://github.com/IfcOpenShell/IfcOpenBot/blob/master/nix.sh#L106

**Comment by Amoki** [comment]
What about x86 versions?
The last x86 only real CPU is a Pentium 4 of 2002 and some Atom from 2008. I don't think anyone wants to use IfcOpenShell on these.

**Comment by aothms** [comment]
I agree.

**Comment by Moult** [comment]
Sounds like this discussion was resolved with support for >=py3.5 and no support for x86. Closing :)
