### ISSUE TITLE
build-deps.cmd warning seems out of sync

### ISSUE THREAD

**Issue by ssg3d** [IfcOpenShell/IfcOpenShell#1788]
On running build-deps.cmd, one gets this warning irrespective of the options chosen:
Warning: You will need roughly 8 GB of disk space to proceed (VS 2015 x64 RelWithDebInfo).
In this case I was building VS2017 Release config.
I think the stuff in brackets can be done away with since all options are already listed by this command.
Also, some way of automatically proceeding would be nice, like a build-deps.cmd -y <other params> flag.

**Comment by aothms** [comment]
> build-deps.cmd -y

You can do this with `echo y | build-deps.cmd`  but I agree with your point :)

>  warning irrespective of the options chosen

It's just an indication of the order of magnitude of the space that is required. It's probably also outdated as the size of the code base has increased drastically. It is indeed not related to the options. If you have more recent data (for one or more platforms, it'd be cool if you can add them).

**Comment by ssg3d** [comment]
> echo y | build-deps.cmd
This works great, thanks Thomas!
> If you have more recent data (for one or more platforms, it'd be cool if you can add them).
I'm not too familiar with cmake so I'd prefer to pass on this one, hope you dont mind.
