### ISSUE TITLE
no more update in the "lastest update" website

### ISSUE THREAD

**Issue by Asgatlat** [IfcOpenShell/IfcOpenShell#1789]
hi,
it seems that the update frame in the website is reading change from the 0.6 branch instead of the 0.7 (see lastest update in the screenshot) : 
![image](https://user-images.githubusercontent.com/86599367/136757099-4671a2bc-8111-4d1d-9d50-b4dbf5f1d040.png)

**Comment by Moult** [comment]
Thanks for the heads up! Fixed.
