### ISSUE TITLE
BB: object placement not remembered

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1792]
Vid: https://www.dropbox.com/s/yplmsquaupybvz3/2021-10-12_13-30-32.mp4?dl=0

Files: https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/c0cbecd41b62ed6b5934126d6440b8f474740784/Random_Tests/Column/from_Blender

blenderbim-210922-py39-win.zip

**Comment by Moult** [comment]
Sorry, I introduced the bug here: https://github.com/IfcOpenShell/IfcOpenShell/commit/2b82eaf01940df87d5e847c46aa076cdf08f9474#diff-00788f2e8ef2aa310e4f90c7e30f605199337f5591d88db87b2b7c4a025f9af3 - will fix.
