### ISSUE TITLE
BB: some strange scaling things

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1795]
vid: https://www.dropbox.com/s/2t3w240t3fxvq97/2021-10-13_11-35-59.mp4?dl=0

files: https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/4b619928f4f45daee3cb615b99b0b31742ca89f1/Random_Tests/Column_Profile_Rectangle/from_Blender

blenderbim-211012

**Comment by Moult** [comment]
Serve me right for building the BlenderBIM Add-on layer before first testing the underlying IfcOpenShell layer :)
