### ISSUE TITLE
Obtaining the latitude and longitude to compute the bounding box of the ifc object

### ISSUE THREAD

**Issue by kenseii** [IfcOpenShell/IfcOpenShell#1797]
Hello

Is there a way of extracting/transforming the coordinates from an ifc file to mappable coordinates using ifcopenshell?
After obtaining data by type "IFCCARTESIANPOINT" i transformed them with `proj` to a latLong format but the bounding box was quite larger than the correct bbox.

I saw in the code/other issues that the `RefLatitude` key is mentioned but i cant find it in my file so i am wondering if i need to add it or if there is another way of getting the position without editing the file.

Thank you

PS: I think the docs about building ifcopenshell+opencada on mac might not be updated but that might be a topic for another issue.

**Comment by Moult** [comment]
IFC cartesian points can be all sorts of things. They can represent an individual vertex of the geometry of an element, or the "origin point" of an element, or the insertion point of a parametrically extruded profile, or something else entirely. I'm not exactly sure what your question is?
