### ISSUE TITLE
Issues compiling IFCOS on windows for SVG Converter

### ISSUE THREAD

**Issue by Fredh512** [IfcOpenShell/IfcOpenShell#18]
Hi everyone,
As advised by Stinkfist, I'll continue explaining my issues here instead of Sourceforge. (https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/9dde835a/#9ffc )

My config : Windows 10 ; Visual Studio 14 2015 using Visual Studio 2015 x64 Native Tools Command Prompt; CMAKE v 3.4.1 and the latest code from https://github.com/IfcOpenShell/IfcOpenShell.
CMAKE started but an error occurred. Don't have a clue why and the CMakeOutput.log didnt help.
Here's the code : 

C:\IfcOpenShell\IfcOpenShell\win>run-cmake "Visual Studio 14 2015 Win64"

vs-cfg.cmd: Warning: BUILD_CFG not specified - using the default RelWithDebInfo
Le système ne peut trouver le fichier BuildDepsCache-x64.txt.

Script configuration:
  CMake Generator = "Visual Studio 14 2015 Win64"
  All arguments   = "Visual Studio 14 2015 Win64"

Dependency Environment Variables for IfcOpenShell:
   BOOST_ROOT              = C:\IfcOpenShell\IfcOpenShell\deps\boost
   BOOST_LIBRARYDIR        = C:\IfcOpenShell\IfcOpenShell\deps\boost\stage\vs2015-x64\lib
   ICU_INCLUDE_DIR         = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\icu\include
   ICU_LIBRARY_DIR         = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\icu\lib
   OCC_INCLUDE_DIR         = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\oce\include\oce
   OCC_LIBRARY_DIR         = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\oce\Win64\lib
   OPENCOLLADA_INCLUDE_DIR = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\OpenCOLLADA\include\opencollada
   OPENCOLLADA_LIBRARY_DIR = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\OpenCOLLADA\lib\opencollada
   PYTHONPATH              = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\Python34
   PYTHON_INCLUDE_DIR      = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\Python34\include
   PYTHON_LIBRARY          = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\Python34\libs\python34.lib
   SWIG_DIR                = C:\IfcOpenShell\IfcOpenShell\deps-vs2015-x64-installed\swigwin

   CMAKE_INSTALL_PREFIX    = C:\IfcOpenShell\IfcOpenShell\installed-vs2015-x64

Running CMake for IfcOpenShell.
-- The C compiler identification is MSVC 19.0.23506.0
-- The CXX compiler identification is MSVC 19.0.23506.0
-- Check for working C compiler using: Visual Studio 14 2015 Win64
-- Check for working C compiler using: Visual Studio 14 2015 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 14 2015 Win64
-- Check for working CXX compiler using: Visual Studio 14 2015 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   program_options
--   regex
--   thread
--   date_time
-- Boost include files found in C:/IfcOpenShell/IfcOpenShell/deps/boost
-- Boost libraries found in C:/IfcOpenShell/IfcOpenShell/deps/boost/stage/vs2015-x64/lib
-- Looking for opencascade include files in: C:/IfcOpenShell/IfcOpenShell/deps-vs2015-x64-installed/oce/include/oce
CMake Error at CMakeLists.txt:74 (MESSAGE):
  Unable to find header files, aborting

-- Configuring incomplete, errors occurred!
See also "C:/IfcOpenShell/IfcOpenShell/build-vs2015-x64/CMakeFiles/CMakeOutput.log".

An error occurred

Thank you for your help.

Sincerely,

Fred

**Comment by Stinkfist0** [comment]
How did `build-deps.cmd` go? If I guess right, `Le système ne peut trouver le fichier BuildDepsCache-x64.txt.` means that BuildDepsCache-x64.tx does not exist, but the file should exist after successful run of `build-deps.cmd`. How does the contents of `C:/IfcOpenShell/IfcOpenShell/deps-vs2015-x64-installed/oce/include/oce` look like?

**Comment by Fredh512** [comment]
Hi Stinkfist,
Good news, seems like it's working. I checked the contents of the file you mensionned and effectively, it wasn't complete (for an unknown reason as i didnt get any error message). Deleted everything and started over and everything went smoothly. Build-deps, run-Cmake, build-ifcopenshell and install-ifcopenshell too. 
IfcConvert in *C:\IfcOpenShell\IfcOpenShell\installed-vs2015-x64\bin* seems like to work correctly to. I will try investigate deeper if the SVG converter is working as it should be.
Thank you very much for your time and help.

Sincerely,
Fred

**Comment by Stinkfist0** [comment]
Nice to hear. I've tried SVG and it works, just note that all of the storeys are inserted in the same image so you'll need and SVG editor to e.g. get separate files for different storeys. Also using e.g. `--bounds 512x512` was useful, otherwise the resolution of the SVG will be huge.

**Comment by Fredh512** [comment]
Yes thanks, I' ve already read this from Thomas on SourceForge. Tried it and works fine. 
After a brief analysing of the SVG created, i can see the ID path of the IfcSpace are random. 
For example : 
*<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="product-cb250794-3ce3-474e-95ef-0e22800bac7c">
        <g id="product-product-f4499821-9e68-4bb5-a43f-c39d0d9e8d0e-body">
            <path style="stroke:black; fill:none;" d="M16.2111,160.76 L16.2111,97.2665 L78.4887,97.2665 L78.4887,160.76 L16.2111,160.76"/>
        </g>
        <g id="product-product-f4499821-9e68-4bb5-a43f-c39d0d9e8d07-body">
            <path style="stroke:black; fill:none;" d="M16.2111,224.253 L16.2111,162.111 L78.4671,162.111 L79.28,162.111 L98.6174,181.448 L98.6174,182.261 L98.6174,224.253 L16.2111,224.253"/>
        </g>
        <g id="product-product-f4499821-9e68-4bb5-a43f-c39d0d9e8d04-body">
            <path style="stroke:black; fill:none;" d="M166.839,224.253 L99.9683,224.253 L99.9683,182.24 L166.839,182.24 L166.839,224.253"/>*

Do you think it could be possible to make the ID of the space corresponding to the "Name" or "LongName" of the space in the Ifc file ? 
Maybe i should open a new topic? On sourceforce perhaps? 

Thanks again,
Fred

**Comment by Stinkfist0** [comment]
I have created `--use-guids` and `--use-names` which control the naming of the OBJ or DAE serialized objects for IfcConvert at my old fork . These switches should be applied for SVG too, but my old fork doesn't have the SVG code.

**Comment by Fredh512** [comment]
Nice. So can i add these options to my SVGserialized? Or is it maybe easier to add the SVGserialized to your old fork? Sorry i don't really understand what's represant in term of work and time applying these switches.

**Comment by Stinkfist0** [comment]
For now, it might be the easiest for you to simply hack the code to your own clone, see 
https://github.com/Tridify/IfcOpenShell-SourceForge/commit/6c9b9bf4a4d447d644145d16045238d5946cb005 and https://github.com/Tridify/IfcOpenShell-SourceForge/commit/2b8c45ccb21f8cdbaaaf90ac69a9de43992f33a9

**Comment by Fredh512** [comment]
Hi Stinkfist, 
Thank you for the codes, I spent some time on mine last week and succeded to format the SVG with the names (and guids) quite well.
For example on my SVG: 
*<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="product-cb250794-3ce3-474e-95ef-0e22800babaa">
<g Type="-0101">
            <path style="stroke:black; fill:none;" d="M413.383,149.955 L413.383,224.253 L264.63,224.253 L264.63,149.955 L413.383,149.955"/>
</g>
<g Type="-0102">
            <path style="stroke:black; fill:none;" d="M16.2111,224.253 L16.2111,182.246 L121.702,182.246 L121.702,224.253 L16.2111,224.253"/>*

It's good but what I'd like to have is indeed the "Longname" instead of the "name" and to add the "name" and "description" in the svg path.
Something like that : 
*<g Type="Longname">
            <path Name ="Name" Description ="Description" style="stroke:black; fill:none;" d="M413.383,149.955 L413.383,224.253 L264.63,224.253 L264.63,149.955 L413.383,149.955"/>
</g>*
The principal issue here is the "Longname" and "Description" aren't defined. I tried to add the variables "Longname" in the *IfcGeomElement*, *ifcGeomIteratorSettings* and *IfcGeomFunctions* but it's not working. I guess i missed something but cant really understand why and where thoses variables are defined.
Thank you for your help.
Fred

**Comment by aothms** [comment]
Hi Fred,

LongName is not an attribute of IfcProduct but one of its subtype. Therefore, e.g Spaces can have a LongName, but Walls cannot. The IfcGeom::Element describes generic products and therefore not all attributes are there.

There are two things you could do:

1 Add the things you want to IfcGeom::Element, populate here https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomFunctions.cpp#L955 and add members and modify constructors here https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomElement.h#L72

2 Use the getFile() function https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomIterator.h#L269 and IfcGeom::Element::id() https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomElement.h#L83 to obtain a reference to the instance as it is defined in the file and access whatever attribute you like.

In both approaches you will have to cast the IfcProduct or IfcBaseClass instance to subtypes in order to access the more specific attributes.

Hope that helps,

Kind regards,
Thomas

**Comment by Fredh512** [comment]
Hi Thomas,
Thanks for the answer. Actually i did the first method and got the error : 

*C:\IfcOpenShell\IfcOpenShell\src\ifcgeom\IfcGeomFunctions.cpp(962): error C2065: 'description': undeclared identifier [C:\IfcOpenShell\IfcOpenShell\build-vs2015x64\IfcGeom.vcxproj] 
C:\IfcOpenShell\IfcOpenShell\src\ifcgeom\IfcGeomFunctions.cpp(963): error C2065: 'longname': undeclared identifier [C:\IfcOpenShell\IfcOpenShell\build-vs2015-x64\IfcGeom.vcxproj]*

I think I correctly add and modified "decription" and "longname" in *IfcGeomElement.. That's why I asked if I should declare the variables somewhere else?
In IfcGeomFunctions : 
*return new BRepElement<P>(
		product->entity->id(),
		parent_id,
		name, 
		product_type,
		guid,
		context_string,
		description,
		longname,
		trsf,
		shape
	);*

About the second method, I'm afraid, i didnt really understand. Do you mean that i can directtly work in SVGserializer and ask for the "Description" and "LongName" with the getFile() function and the reference from IfcGeom::Element::id() (would be *const std::string& longname() const { return _longname; }* and *const std::string& descriptionconst { return _description; }*.

Thanks again!
Best regards,
Fred

**Comment by Stinkfist0** [comment]
Instead of adding new data members to IfcGeomElement, a better way (although requiring more code) might be to output SVG using GUIDs and then also output the XML file (which has the GUIDs available too), and then retrieve the wanted data from the XML and insert it to the SVG file.

**Comment by aothms** [comment]
`undeclared identifier` means in this case there is no variable in your scope with this name, see how this is done for `name` and `guid` https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomFunctions.cpp#L880

Since LongName is an attribute of SpatialStructureElement, you'll need to cast to a subtype first. Something like the following (untested).

    std::string longname;
    if (product->is(IfcSchema::Type::IfcSpatialStructureElement)) {
        longname = static_cast<IfcSchema::IfcSpatialStructureElement*>(product)->LongName()
    }

Let's forget about the 2nd approach, since you're here already.

**Comment by Fredh512** [comment]
Hi Thomas, 
Since *Description* is (if I'm not mistaken and as shown here : http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcproductextension/lexical/ifcspace.htm) is an attribute just as *Name*, i first tried to add *Description* only to test the solution. 

*const std::string name = product->hasName() ? product->Name() : "";
const std::string guid = product->GlobalId(); 
const std::string description = product->hasDescription() ? product->Description() : "";*

And modified constructors in *IfcGeomElement.h.*
No more errors in IfcGeomFunctions.cpp BUT : 
`<addr>`C:\IfcOpenShell\IfcOpenShell\build-vs2015-x64\ifcwrap\IfcPythonPYTHON_wrap.cxx(8763): error C2661: 'IfcGeom::Element<P>::Element': no overloaded function takes 8 arguments [C:\IfcOpenShell\IfcOpenShell \build-vs2015-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]
C:\IfcOpenShell\IfcOpenShell\build-vs2015-x64\ifcwrap\IfcPythonPYTHON_wrap.cxx(9216): error C2661: 'IfcGeom::Element<double>::Element': no overloaded function takes 8 arguments [C:\IfcOpenShell\IfcOpenShell\build-vs2015-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]`<addr>`

Thanks.

**Comment by Fredh512** [comment]
Hi Stinkfist,
Sure your solution is viable. I already think about it and concluded it would be a loss of time to developp a personnal tool that would do what IFCOS could do too. Well, didn't know it would be that complicated at the end of last week. Anyway, i think these new options can be usefull to some people and are worth implementig on IFCOS...
Why exactly do you think it could be a better approach?

**Comment by Stinkfist0** [comment]
@Fredh512 It would be more dynamic solution, as the GUID (which will be added in any case) can be used to retrieve all possible data, instead of fixing the available data (and adding new data members and new command switch again and again every time new needs rise).

**Comment by aothms** [comment]
@Fredh512 That error is related to the IfcOpenShell Python wrapper and not related to IfcConvert. You can safely ignore it for your purposes. You can set `-DBUILD_IFCPYTHON=OFF` when invoking CMake for IfcOpenShell or you can simply open the .sln file in Visual Studio and build IfcConvert manually. Make sure to set the correct configuration (e.g Debug/Release/RelWithDebugInfo).

**Comment by Stinkfist0** [comment]
BTW currently one must pass the CMake generator also, when invoking CMake via run-cmake.bat: `run-cmake.bat "Visual Studio 14 2015 Win64" -DBUILD_IFCPYTHON=OFF`. I'll try to make this a bit nicer in the near future.

**Comment by Fredh512** [comment]
Thank you very much both of you. Without the Python wrapper, i succedded to add `Description` and `LongName`. I can now use them instead of `unique_id` with the SVG converter. 
For the records, the call for `LongName` in *IfcGeomFunctions.cpp* was simply (after a lot of tries): 

`const std::string name = product->hasName() ? product->Name() : "";`
`const std::string guid = product->GlobalId();`
`const std::string description = product->hasDescription() ? product->Description() : "";`
`const std::string longname = static_cast<IfcSchema::IfcSpatialStructureElement*> (product)->LongName();`

I will now try to add `Name` and `Description`in the Space path and format the BuildingStorey path as I'd like. I'll let you know.

Thanks again!
Kind regards, 
Fred

**Comment by aothms** [comment]
Thanks for posting the code so that others can benefit. Keep in mind though that not necessarily all products passed to this function will be spaces. The default when converting to SVG is to only include spaces, but if you would invoke the executable like this `IfcConvert in.ifc out.svg --include --entities IfcWall IfcWindow` then walls and windows would be processed by this function, which are not IfcSpatialStructureElement and the code will crash.

It is better to make this cast conditional, something like this:
~~~
std::string longname = "";
if (product->is(IfcSchema::Type::IfcSpatialStructureElement)) {
    longname = static_cast<IfcSchema::IfcSpatialStructureElement*> (product)->LongName();
}
~~~
