### ISSUE TITLE
BB: Locate the IfcOpeningElement inside the IfcWindowType definition.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1806]
Currently, if you have 50 instances of a windowtype and you want to change the width of the window, for example, you have to change the width of 50 instances of the IfcOpeningElement, since IfcOpeningElement is not part of the IfcWindowType definition

Would be nice if you could put the IfcOpeningElement inside the IfcWindowType definition somehow. 

Maybe this is already possible, and i'm missing something.

**Comment by theoryshaw** [comment]
Is there currently a way to type IfcOpeningElements in the schema?

**Comment by brunopostle** [comment]
An IfcWindow has a width and height attribute, but an an IfcWindowType doesn't. Blenderbim derives the opening from the window bounding box, but this only works when the window has no projections.

**Comment by theoryshaw** [comment]
projections?  like a non-cube IfcOpeningElement like the following?
![2022-04-21_15-42-04_Blender_ DDropboxGitLabThe_SteadModels_and_C_blender](https://user-images.githubusercontent.com/507113/164549057-9a2c2be9-03ef-47f8-8420-7828e03cb98a.gif)

**Comment by theoryshaw** [comment]
related potentially: https://community.osarch.org/discussion/964/bb-not-restricting-ifcopeningelements-into-the-ifcopeningelements-collection

**Comment by brunopostle** [comment]
> projections? like a non-cube IfcOpeningElement like the following?

I have windows that have cills that project sideways as well as forward, so the bounding box is larger than the opening. Also not all openings are rectangular, so it would be good if the Window Type had the possibility of having an arbitrary opening geometry associated with it.

**Comment by Moult** [comment]
As a minor workaround for now you can use the "Copy Representation" feature to copy the geometry of one modified IfcOpeningElement to all the other instances. Of course selecting them is still a pain :(

**Comment by theoryshaw** [comment]
related: https://community.osarch.org/discussion/992/blenderbim-ifcopeningelement#latest

**Comment by theoryshaw** [comment]
related: https://community.osarch.org/discussion/993/writing-a-blenderbim-tutorial-at-epfl-stuck-on-ifcwindow-and-ifcopeningelement
