### ISSUE TITLE
IfcConvert yields zero geometry for certain IfcFaceBasedSurfaceModel when --sew-shells is enabled

### ISSUE THREAD

**Issue by larsmoa** [IfcOpenShell/IfcOpenShell#181]
I have a few IFC files with IfcFaceBasedSurfaceModel-geometry that IfcConvert successfully converts, but outputs no geometry for when `--sew-shells` is enabled. When `--sew-shells` isn't enabled the result is as expected.

Without `--sew-shells`:
![image](https://cloud.githubusercontent.com/assets/6741854/21974641/370c3dde-dbc8-11e6-95e6-2446b8bfa057.png)

Please find the IFC files attached here: [IfcFaceBasedSurfaceModels.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/707507/IfcFaceBasedSurfaceModels.zip)

**Comment by aothms** [comment]
Hm this was a somewhat peculiar case, where there the shapes consist of several `IfcConnectedFaceSets` with all a single face. This caused the sewing algorithm to succeed (for each single-face-shell individually) and return a valid result, but not of the expected type (shell).

This has been fixed. However, this particular case, the `--sew-shells` option will not have any meaningful effect as every face is separated.

~~~
#31 = IFCFACEBASEDSURFACEMODEL((#32, #50, #62, #75, #79, #88, #92, #101, #107, #119, #123, #136, #142, #150, #155, #159, #165, #171, #175, #184, #196));
#32 = IFCCONNECTEDFACESET((#33));
#33 = IFCFACE((#34));
...
~~~
