### ISSUE TITLE
Proposed improvement to remove_deep

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1812]
Here is a simple subgraph shown three times. The first with letters for explanation purposes, the second using the existing remove_deep functionality, and the third using a newly proposed replacement for remove_deep.

Given a subgraph starting with element `A`, where `A` has _no inverses_ (otherwise, unbatching fails in my proposal), imagine we want to perform a deep removal. The existing remove_deep algorithm traverses the subgraph backwards (`F`, then `E`, etc) each time checking there are any inverses outside the subgraph. If all inverses are part of the subgraph, it can be deleted. Deleted elements are marked as `X`.

This creates an issue, such as where element `C` only has semantic meaning if `D` exists. For example, if `C` is an extruded area solid, and `D` is a profile def. Therefore, if `C` is referenced elsewhere, it is preserved, but it doesn't help much because `D` is deleted.

I propose a different approach, to instead remove_deep traversing the subgraph forwards instead of backwards. If the element has inverses outside the subgraph, the entire branch is no longer considered for deletion. This should also in theory lead to faster remove deeps, as well as preserving the assumption that an element only makes sense together with all of its subelements.

Am I making a mistake? Is this logic sound?

```
A──►B──►C──►D──►E──►F
        ▲       ▲
    G───┘   H───┘

X──►X──►0──►X──►0──►X
        ▲       ▲
    0───┘   0───┘

X──►X──►0──►0──►0──►0
        ▲       ▲
    0───┘   0───┘
```

Here is sample code for a make-believe scenario of the graph above. Currently, batch and unbatch throws an error but I don't fully understand the rules of when I can and can't batch, so hopefully that can be sorted out later if the premise is sound.

```python
import ifcopenshell
ifc = ifcopenshell.file()

A = ifc.createIfcProductDefinitionShape()
B = ifc.createIfcShapeRepresentation()
C = ifc.createIfcExtrudedAreaSolid()
D = ifc.createIfcArbitraryClosedProfileDef()
E = ifc.createIfcIndexedPolyCurve()
F = ifc.createIfcCartesianPointList3D()

G = ifc.createIfcShapeRepresentation()
H = ifc.createIfcArbitraryClosedProfileDef()

A.Representations = [B]
B.Items = [C]
C.SweptArea = D
D.OuterCurve = E
E.Points = F

G.Items = [C]
H.OuterCurve = E

print('A', A)
print('B', B)
print('C', C)
print('D', D)
print('E', E)
print('F', F)
print('G', G)
print('H', H)
    
print('Remove')
ifcopenshell.util.element.remove_deep(ifc, A)
# To try out the proposal
#ifcopenshell.util.element.remove_deep2(ifc, A)

for e in ifc:
    print(e)
```

**Comment by Moult** [comment]
I've added in batching support now thanks to your suggestion (though I inverted the subgraph first). All the tests still seem to pass.

Upon rereading this code I'm also a bit suspicious about how also_consider is meant to work, whether it is meant to work as merely an addition to remove_deep (in which case we should traverse it too and remove_deep on it too) or merely as another way of adding additional whitelisted inverses.

I have no idea - but it's only used once in the code for removing representations, so for now it can stay as is. When more usecases emerge I think the function signature and documentation can be revisited to be more coherent.

I think we can close this :)

**Comment by Moult** [comment]
I've got a ~80MB model here, which I'm running remove_deep2() on some (well, a lot actually) shape representations. On average, it takes about 0.66 seconds to remove deep a shape representation.

I discovered when I _removed_ batch() and unbatch() then it only took 0.26s on average. Am I going crazy? When is batching beneficial and when isn't it?

**Comment by aothms** [comment]
Pff I've no clue. If you can whip up some test files I can have a look. Are we really only talking about the calls to batch or it there also some sorting/traversing being eliminated?

**Comment by Moult** [comment]
Sent (private) model to models@ifcopenshell.org and here are some shape rep IDs to test with:

```
ifcopenshell.util.element.remove_deep2(ifc, ifc.by_id(882826))
ifcopenshell.util.element.remove_deep2(ifc, ifc.by_id(882824))
ifcopenshell.util.element.remove_deep2(ifc, ifc.by_id(882822))
ifcopenshell.util.element.remove_deep2(ifc, ifc.by_id(882820))
```
