### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ketourneau** [IfcOpenShell/IfcOpenShell#1814]
We got segmentation fault error when we try to convert a ifc to dae (with IfcConvert 0.6.0 & 0.7.0)
`IfcConvert test.ifc test.dae`

[test.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/7379266/test.ifc.zip)

This is what the object looks like :
<img width="721" alt="Capture d’écran 2021-10-20 à 10 01 07" src="https://user-images.githubusercontent.com/39763266/138052633-64f947a7-ec58-452f-967c-8a8592aa3b1e.png">

**Comment by aothms** [comment]
Thanks, precision issue. Should be fixed. The whole IfcIndexedPolyCurve thing isn't as battle tested yet as the 2x3 definitions.
