### ISSUE TITLE
Branch v0.7.0 doesn't build, because 'patch does not apply'

### ISSUE THREAD

**Issue by regis-longchamp** [IfcOpenShell/IfcOpenShell#1821]
I'm trying to build IOS on branch v0.7.0 (commit 9ae2c63), but it doesn't build.
After running these commands in win directory with VS 2019 developer command prompt on Windows 10

set IFCOS_USE_OCCT=FALSE
set IFCOS_INSTALL_PYTHON=False
build-deps.cmd vs2019-x64

the build fails with the following error message:

Cloning into 'C:\IfcOpenShell\IfcOpenShell\_deps\mpfr'...
remote: Enumerating objects: 65561, done.
remote: Counting objects: 100% (1934/1934), done.
remote: Compressing objects: 100% (850/850), done.
remote: Total 65561 (delta 1044), reused 1330 (delta 676), pack-reused 63627
Receiving objects: 100% (65561/65561), 15.02 MiB | 16.31 MiB/s, done.
Resolving deltas: 100% (49695/49695), done.
Updating files: 100% (1468/1468), done.
Checking out mpfr revision 2ebbe10fd029a480cf6e8a64c493afa9f3654251.
HEAD is now at 20d84f264 Merge branch 'master' of https://github.com/BrianGladman/mpfr
Updating files: 100% (1401/1401), done.
Note: switching to '2ebbe10fd029a480cf6e8a64c493afa9f3654251'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 2ebbe10fd Merge branch 'master' of github.com:BrianGladman/mpfr
HEAD is now at 2ebbe10fd Merge branch 'master' of github.com:BrianGladman/mpfr
error: patch failed: build.vc15/lib_mpfr/lib_mpfr.vcxproj:25
error: build.vc15/lib_mpfr/lib_mpfr.vcxproj: patch does not apply

An error occurred

Build ended at 14:47:34,07. Time elapsed 1:21:37.03.

**Comment by Moult** [comment]
Ping @regis-longchamp any updates on this issue?

If no further feedback, propose closing as nothing we can do without response in a week.
