### ISSUE TITLE
Geometry conversion error in ifcConvert when 'IfcFlowFitting', 'IfcSurfaceStyle', 'IfcFlowSegment' elements don't have a Name field

### ISSUE THREAD

**Issue by farialima** [IfcOpenShell/IfcOpenShell#183]
if an element of type 'IfcFlowFitting', 'IfcSurfaceStyle', or 'IfcFlowSegment' has no "Name" field (i.e. "*" in the IFC) then the geometry generation fails for the geometry element it belongs to. 

However, the IFC spec doesn't require these element to have a 'Name' field - it is marked as OPTIONAL , eg. http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcpresentationappearanceresource/lexical/ifcsurfacestyle.htm

Furthermore, the error is not really clear, something like : 
```
[Error] {2l1T6xB2rSHv2y8gtCye3T} Token * at 2832 invalid string
Failed to convert:
#94=IfcShapeRepresentation(#96,'Body','SweptSolid',(#70))
```
where the GUID is the one of the element in error.

**Comment by aothms** [comment]
In IFC-SPF `$` is the token for an optional attribute set to null. `*` signifies inherited attributes derived in a subtype (only the case in 2 or 3 entities in the IFC schema). Perhaps exceptions can be caught at a more granular level, but the situation you describe *is* a syntax error.
