### ISSUE TITLE
BlenderBim-211027 Test Scale and Rotation

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#1836]
Blender being an organic mesh modeling tool. it is very easy for users to forget to apply scale and rotation after creating or modifying an object. The exported ifc file will currently export the object as defined without applying scale and rotation, in most cases giving an undesired result. WISIWIG is great.. 

Maybe implement a check of Scale/Rotation before applying ifcClass. Maybe display a warning and exit Apply ifcClass routine.   

BTW it does not help to apply Scale/Rotation after an ifcClass has been set. 
However if You Apply Scale/Rotation after an ifcClass has been set, and make a Shift-D copy of same object, the first object will export without Scale/Rotation being applied, the copy will export as expected.

**Comment by Moult** [comment]
By the way, scale should be the only issue - rotation should work.
