### ISSUE TITLE
Styles in iterator with negative RGB values.

### ISSUE THREAD

**Issue by Bilnake** [IfcOpenShell/IfcOpenShell#1843]
I'm parsing a IFC file using iterator. Some elements in IFC file are returning style with negative RGB values. 

Script example:

```
iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
iterator.initialize()
element = iterator.get()
style = element.styles
print(style):  ((-1.0, -1.0, -1.0, 1.0),)
```
and style_ids are (-1,))

Open this IFC in other softwares like Solibri, those elements are with normal colors. There are any reason for this behavior ?

**Comment by aothms** [comment]
Yes, it simply means that there isn't a style associated to this representation item and no material associated to the product. Solibri will likely colour the element then based on it's internal mapping of element types to colour.

You can use settings(APPLY_DEFAULT_MATERIALS=True) to have similar behaviour.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcGeomRepresentation.cpp#L49

**Comment by Bilnake** [comment]
Ok. Now I understand the meaning of negative values. But I couldn't use the APPLY_DEFAULT_MATERIALS=True. I tried:

```
settings = ifcopenshell.geom.settings()
settings.set(settings.USE_PYTHON_OPENCASCADE, True)
settings.set(settings.APPLY_DEFAULT_MATERIALS, True)

iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
iterator.initialize()
element = iterator.get()
shape = element.geometry

canvas = qtDisplay.qtViewer3d()
canvas.InitDriver()
display = self.canvas._display

ifc_display = display.DisplayShape(shape)[0]
```
and everything was shown brown.

I was using the style to extract the color and use it as an argument in the display, like this:
```
style = element.styles
color = Quantity_Color(*style, 1)
ifc_display = display.DisplayShape(shape, color=color)[0]
```
In DisplayShape, is possible use "material=some material". What does APPLY_DEFAULT_MATERIALS setting do exactly? Is it applicable in this case?

**Comment by aothms** [comment]
If you want to use styles in ifcopenshell python, you have to use the geom.utils, or adapt your code to do the same

```
ifcopenshell.geom.utils.initialize_display()
ifcopenshell.geom.utils.display_shape(element)
```

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/geom/occ_utils.py

**Comment by aothms** [comment]
It actually checks for values < 0 and has it's own colour mapping https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/geom/occ_utils.py#L161

**Comment by Bilnake** [comment]
Thank you very much @aothms . Now I can create something similar to use in my case.
