### ISSUE TITLE
Add Dumb wall missing

### ISSUE THREAD

**Issue by alessandrodausilio** [IfcOpenShell/IfcOpenShell#1844]
Blender Version: blender-2.93.1-linux-x64
BlenderBIM : blenderbim-210829-py39-linux

The add 'Dumb Wall' button is missing.

![Kazam_screenshot_00002](https://user-images.githubusercontent.com/75832788/139525836-d7087879-01be-47d6-95ab-1114c132a8c7.png)

**Comment by Moult** [comment]
The feature has changed. There is no longer a dumb wall (and the others will also disappear soon). Instead, we can now handle standard case parametric walls in IFC.

Try loading a project library (try the demo library here https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/blenderbim/libraries ) and importing some wall types, then use the BIM tool (see the green cube on the sidebar) to add instances of that wall type.

**Comment by alessandrodausilio** [comment]
Thanks for clarifying! Keep the good work on :)

**Comment by Moult** [comment]
This might help: https://twitter.com/theoryshaw/status/1453748046332825604

Note I highly recommend the BIM tool with the shortcuts - it is quite a fast workflow in contrast to what's shown in the beginning of the video which is quite manual.
