### ISSUE TITLE
List of modules with and without its own data

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#1848]
Following this closed PR (#1833), i write here the modules that have `ui.py` which still speak to a `Data class` in `ifcopenshell.api`, ones that have already been migrated to a new `blenderbim.bim.module.* data class` and modules that haven't a `ui` with `data class`

MODULES WITH ui that speaks from  `ifcopenshell.api data `class`

ALL DONE!

MODULES WITH `blenderbim.bim.module.* data class`
- aggregate
- attribute
- boundary
- constraint
- context
- cost
- classification
- group
- layer
- spatial
- geometry
- georeference
- material
- model
- owner
- profile
- pset
- pset_template
- resource
- root
- sequence
- structural
- spatial
- style
- system
- type
- unit
- void

MODULES WITHOUT `data class`
- augin
- bcf
- bimtester
- clash
- cobie
- covetool
- csv
- debug
- diff
- document
- drawing
- lca
- misc
- patch
- project
- qto
- search

**Comment by Moult** [comment]
This is really excellent and it shows that we are much further along than originally thought. I've updated the list with difficulty ratings off the top of my head. Perhaps @Jesusbill can also help hack on some like the structural one.

**Comment by Jesusbill** [comment]
@Moult yes I should start working on this, nice work @maxfb87

**Comment by maxfb87** [comment]
Thanks @Jesusbill .
I would like to help with this refactoring , i need only to figure out how to handle the operator.py calls to data and after that i think i can help with that

**Comment by Moult** [comment]
Cheers, here's the guidelines:

 1. One blenderbim.bim.module.foo.data.WidgetNameData class per widget. e.g. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/context/data.py#L27
 2. Widget draw function always calls if not WidgetNameData.is_loaded: WidgetNameData.load(). This triggers loading if and only if the widget is visible. The is_loaded and load() is always the same with no variation allowed. e.g. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/context/ui.py#L38-L39
 3. Operators that call ifcopenshell.api.foo.Data.load() will have that call removed. Instead, a new Operator function can be created which calls `refresh_ui_data()` then all operators must inherit from it. e.g. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/context/operator.py#L28-L35
 4. In complex scenarios where the operator actually does more than a data load (such as [this](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/classification/operator.py#L35) which @maxfb87 unfortuantely ran into) it must be dealt with in a case by case basis - but the operator must not talk to the data class. The operator must instead talk or store its data in another system, which the data class will also read from. E.g. Operator --> Other System <-- Data. In this particular scenario, a similar pattern to the [brick store](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/tool/brick.py#L132-L137) can be used.

**Comment by Moult** [comment]
A heads up that the updated developer guide contains a very extensively commented demo module which teaches the entire code architecture. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/docs/blenderbim/developer_guide.rst

**Comment by maxfb87** [comment]
Thanks @Moult, the guide is very useful! I'll continue trying with refactor "georeference module", but i'm not sure i can make it.

**Comment by maxfb87** [comment]
Hey @Moult, i have tried to refactor the georeference module following the guide and i created a PR.
Let me know if i made mistakes or something can be better.
Massimo

**Comment by Moult** [comment]
Finally.
