### ISSUE TITLE
Wrong boolean clipping difference result

### ISSUE THREAD

**Issue by arzezniczak** [IfcOpenShell/IfcOpenShell#185]
Hello,
I've got simple IFC example (see attachment) where IFCBOOLEANCLIPPINGRESULT(.DIFFERENCE., ...) result in OBJ output seems to be wrong. I'm a bit supprised since this exaple is based on really simple shapes.
Screenshot (left - original, right - IFCOpenShell mesh result):
![image](https://cloud.githubusercontent.com/assets/20474251/22928597/8e9db900-f2b7-11e6-9597-ec5a4dcecc1f.png)
[p7_3.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/774016/p7_3.zip)

**Comment by aothms** [comment]
Yeah, these seemingly trivial cases can upset Open Cascade if clipping volumes are within the tolerance distance. I have made the tolerance handling a bit more adaptive (which is to say, keep increasing tolerance until a valid result is obtained) and it seems to work well.
