### ISSUE TITLE
Model geometry conversion glitch - walls not clipped?

### ISSUE THREAD

**Issue by xeolabs** [IfcOpenShell/IfcOpenShell#1850]
Hi, I've got a model that's not converting correctly - see those walls poking through the roof. 

Seems like an issue in IfcConvert/IfcOpenShell - our IFC expert confirms that the IFC model is OK.

I'm using IfcConvert-v0.6.0-517b819-linux64.
 
[211015_Herterichstr_export (1).zip](https://github.com/IfcOpenShell/IfcOpenShell/files/7452306/211015_Herterichstr_export.1.zip)
![image](https://user-images.githubusercontent.com/83100/139656724-f6f18204-dae8-442f-8f51-fe5fd7ab1f7a.png)

**Comment by aothms** [comment]
> our IFC expert confirms that the IFC model is OK.

Yeah ok is always relative in the world of IFC. Modelling walls like this (extrusion of a composite profile) is definitely my least favourite. Either do a decomposition or use the material layer set I'd say. This is the least of both worlds.

After the fix, all walls seem to process correctly.

![afbeelding](https://user-images.githubusercontent.com/1096535/139863792-67fcf2ba-ccf4-43ae-b24b-435c94e45416.png)

**Comment by xeolabs** [comment]
Cool thanks Thomas, I'll get them to fix those walls and re-export.
