### ISSUE TITLE
Did something break in terms of boolean subtraction?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1853]
Using this IfcOpenBot build https://github.com/IfcOpenBot/IfcOpenShell/commit/93c5906ad7f363fd1b1d9e49eb28d10212ce9173 if I have an opening voiding an element, IfcOpenShell correctly applies the subtraction as shown:

![2021-11-04-175528_295x293_scrot](https://user-images.githubusercontent.com/88302/140270608-9924d83b-55f3-4d8a-a43f-ce3e6ac560c7.png)

However on my local build on the latest commit, I get this result (i.e. extra vertices around the subtraction but nothing actually subtracted):

![2021-11-04-175638_471x463_scrot](https://user-images.githubusercontent.com/88302/140270663-37d827a7-b7b8-4482-af06-d24c4aafbe8f.png)

Did something break on my local machine when I compiled it, or is this a bug that occurred between that bot build and now?

**Comment by aothms** [comment]
I did recently do 8e529f3f10e9d68ac48a3b542a22f5ab2dffd277 and 8e529f3f10e9d68ac48a3b542a22f5ab2dffd277

I know see that perhaps I was a bit overeager with this particular line https://github.com/IfcOpenShell/IfcOpenShell/commit/8e529f3f10e9d68ac48a3b542a22f5ab2dffd277#diff-0f2b19713fb3b835d26ebe343d81d11a17f2167adcccf85e745d57eb8dceb991L601 maybe that should remain true actually. The thing is that fuse argument does two things, fuse the 2nd operands items, but also call ensure_fit_for_subtraction() and that last bit should probably not have been eliminated. My guess is that you have an opening as a faceset and then ensure_fit_for_subtraction() is probably necessary.

**Comment by Moult** [comment]
I just tried changing it to true but unfortunately it had no impact :( By the way - this was caught from running the test suite :)

**Comment by aothms** [comment]
Ah wait yes, that's IfcBooleanResult, not opening element. I'm not sure anything changed then, and there was also the issue where the SVG cut didn't work for you. Maybe there is something funky on your side or related to os or compiler. How can I reproduce this?

**Comment by Moult** [comment]
About to sleep so I'll try build the known working commit and see if its something on my side tomorrow. If it isn't, I'll create a small script to replicate. Did my svg cut fix make sense? It seemed an unrelated issue.

**Comment by Moult** [comment]
@aothms I can confirm that the bug is not to do with my os/compiler because it breaks on this commit: https://github.com/IfcOpenShell/IfcOpenShell/commit/8e529f3f10e9d68ac48a3b542a22f5ab2dffd277

A bit of digging shows that if I revert this hunk https://github.com/IfcOpenShell/IfcOpenShell/commit/8e529f3f10e9d68ac48a3b542a22f5ab2dffd277#diff-0f2b19713fb3b835d26ebe343d81d11a17f2167adcccf85e745d57eb8dceb991L876-R902 then it works again. I believe this problem is caused because a polygonal face set is always considered to be a compound shape so this if statement always evaluates to true: https://github.com/IfcOpenShell/IfcOpenShell/commit/8e529f3f10e9d68ac48a3b542a22f5ab2dffd277#diff-0f2b19713fb3b835d26ebe343d81d11a17f2167adcccf85e745d57eb8dceb991R895 so it ends up looping through the 6 faces of my cube and I don't quite understand then what happens.

Hopefully that helps narrow down the issue :)

**Comment by aothms** [comment]
> I don't quite understand then what happens.

Then you get the image you showed in your first issue description ;)

> Hopefully that helps narrow down the issue :)

Yes thanks, brilliant. Hopefully https://github.com/IfcOpenShell/IfcOpenShell/commit/10b502512ff791c7e25c8c7b516a7175a466341e helps.

**Comment by aothms** [comment]
Usually there are two indirections of compound actually, IfcRepresentation with IfcBasedBaseSurfaceModel and then IfcConnectedFaceSet and we only explode one. That's why I didn't catch this on my tests.

> this was caught from running the test suite

Any progress on running this on CI?

**Comment by Moult** [comment]
Confirming as fixed! And yes I will find some time to add it to the CI.

**Comment by Moult** [comment]
Thanks so much! Also thanks @myoualid who helped debug this today :)
