### ISSUE TITLE
BB Nested Assemblies Test

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#1857]
Experimenting w Assemblies, built a wall with nested assemblies. Not sure if intended, but works 99%. 
Adds a redundant Empty in ifc file, don't know why. If importing ifc to fresh blend file, deleting the 'redundant  Empty' and doing same loop export ifc, import to fresh blend, The redundant Empty shows up again.. Strange?
Attached Blend / ifc
[t10.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/7490652/t10.zip)

btw Still have trouble assigning Materials and Styles..

**Comment by Moult** [comment]
@cadgiru I looked at the files and couldn't see anything wrong with the nested assemblies. What do you mean by redundant empty?

If you are referring to the empties inside each aggregate as shown in the screenshot, this is normal. The rule in IFC is that an aggregate is not allowed to have its own geometry - it is an "empty" which then contains other objects which may or may not have geometry.

![2021-11-10-140110_807x633_scrot](https://user-images.githubusercontent.com/88302/141041957-2bc4bdba-f323-4d9a-97d3-155418391a08.png)

**Comment by cadgiru** [comment]
At the bottom of Outliner we get an Empty ifcColumn/Assembly.. Can' see what tis relates to..
![t10](https://user-images.githubusercontent.com/42599252/141110223-64e8fd5f-7a63-4e69-acb8-0e85ba27e9f9.JPG)
.

**Comment by Moult** [comment]
Ahh I didn't see that. I guess it's just an empty created by accident somehow (not sure if user error or bug). If I delete it, and reexport, then reimport, it disappears as expected.

**Comment by cadgiru** [comment]
No big deal, just another test file. Nitty Gritty 
On Windows I have tried the same several times, last just now. It does not disappear.  Will try w same file on Linux.
