### ISSUE TITLE
BB wish list Add selection to ifcAssembly

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#1858]
Currently we can only add objects one by one to an assembly. 
Hoping it will be a low hanging fruit to be able to add a selection to an assembly, similar to how assigning ifcClass to a selection currently works.

**Comment by cadgiru** [comment]
Basically a UI request, related to #1867

**Comment by Moult** [comment]
So what happens right now if you just select a bunch of objects and drag and drop them inside the assembly collection? That should work, I think?

**Comment by Moult** [comment]
Closing as confirmed via chat that drag and drop solves the issue :)
