### ISSUE TITLE
blenderbim brickschema dependencies

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1860]
Latest blenderbim requires `brickschema`, this package is very specific about which versions of its dependencies it requires. 

For example fedora 34 and later ship with `xlrd-2.0.1`, but all versions of `brickschema` require `xlrd < 2.0.0`. Similarly, I can't satisfy required versions of `rdflib`, `flask`, `jinja2`, `typer`, `click-spinner`, `requests`, and others.

Installing `brickschema` with pip fails for the same reasons.

I've hacked-up rpm packages of `owlrl`, `pyshacl` and `brickschema` that install without full dependency checking, so at least I can build IfcOpenShell and blenderbim packages again, but the `brickschema` functionality is probably broken.

Can `brickschema` be made an optional dependency? i.e. import it within a try/except

**Comment by Moult** [comment]
Good point - also a good reminder that my current method of bundling via Makefile could be significantly improved with perhaps a requirements.txt file with explicit versions, and perhaps optional vs mandatory vs dev deps (but I'm not too familiar with Python packaging so I'll have to read up on it).
