### ISSUE TITLE
GlobalId not found

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1861]
I might've already reported this somewhere, but I can't recall :)

```python
import ifcopenshell
f = ifcopenshell.file()
w = f.createIfcWall('foo')
w.GlobalId = 'bar'
f.by_guid('bar') # Instance with GlobalId bar not found
```

I'm coming across this issue because I'm trying to invalidate cache entries and also read from the existing SVG ifc:guid - I didn't run into this problem much in the past because the BlenderBIM Add-on always uses STEP IDs, not GlobalIds, but I can't use that method this time with drawings and cache.

**Comment by Moult** [comment]
I ran into this again today, ended up just using [step IDs](https://github.com/IfcOpenShell/IfcOpenShell/commit/e97d427e9f35ae9a00b2066db887a575834d7353#diff-84a51bb6e3dd5dcf1060381cfa319cd64e6f4b819e5208387d0e74d73dcf77a5R725) instead but curious if this is just an inconvenience or a symptom of something deeper?

**Comment by aothms** [comment]
When you first reported this I had some plans to generically implement actions on attribute changes and instance additions, but now I decided to just quickly imperatively put it in there.

**Comment by Moult** [comment]
Confirming as fixed! Thanks so much!
