### ISSUE TITLE
BB:  incorrectly created pset_template files will bug the ui

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1870]
If a pset_template has been made with errors, it will bug the dropdown in the ui so that other templates are no longer accessible.  In my case, I had a template file with un-escaped apostrophes. 

The end result looks like this:
![pset_templates](https://user-images.githubusercontent.com/83825269/141087030-179828b6-a953-44aa-b576-410b7e839d6d.gif)

**Comment by vulevukusej** [comment]
```
Python: Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\bim\module\pset_template\ui.py", line 76, in draw
    pset_template = Data.pset_templates[int(props.pset_templates)]
ValueError: invalid literal for int() with base 10: ''

location: <unknown location>:-1
```

**Comment by Moult** [comment]
I'm not sure I personally want to support syntax errors in IFC files, so I don't think this is a bug. But if you want to commit a try catch, happy to have the code :)

**Comment by vulevukusej** [comment]
I knew you were gonna say this :) , and I agree with you in part.  I think the corrupted ifc file should not be accepted, however the other templates should not be affected.  In any case, I´ll write some code for this ;)

**Comment by vulevukusej** [comment]
Decided against fixing this, since clicking again on the second drop-down loads the pset properly.
