### ISSUE TITLE
BB:  Newly added psets don't show up in UI (v.211110)

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1871]
I recently updated to v211110 and I noticed that when I try to add psets to an object, nothing happens in the UI.  Adding a material seems to trigger a refresh of the UI though.  
![bug new version](https://user-images.githubusercontent.com/83825269/141100110-acec4f99-a101-4640-8935-52490e74c39d.gif)
.

**Comment by Moult** [comment]
Yes - with half the UI migrated to new data classes and half the UI still on the old API data classes, and also that it's not possible to write UI tests for this, I'm sorry this cropped up. I told it to refresh after every IFC operation, but I can't really recall why I didn't do that originally... it seems like the logical thing to do...
