### ISSUE TITLE
BB: Properties added to a pset through the api do not show up in the pset editable ui

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1874]
After using the api to generate a mapping key for iTWO, the new property is visible in the ui, but if I try to edit the properties in the ui the property disappears. 
![image](https://user-images.githubusercontent.com/83825269/141305641-13799e23-1756-46b3-ab77-953b8802279b.png)

I suspect this is because I am adding the property to a pset that was derived from a template?  I also suspect the feedback here will be that I shouldn't be editing standard psets :-)

**Comment by Moult** [comment]
Yes - when you edit a pset that is templated, this rather unique feature will enforce the template when editing. Untemplated psets on the other hand have no restriction (for better or worse). In theory we can change the code to support template + arbitrary, but then we should also somehow distinguish the arbitrary properties so users know when they deviate from a template. I personally think templates are super important in enforcing data quality in our industry, so I'm not quite sure how I feel about this one.

**Comment by vulevukusej** [comment]
Yeah I thought about this a little bit, and I think the easy and sensible option is to just create a new non-standard pset, thereby leaving the integrity of the template in tact.  I'll close the issue.
