### ISSUE TITLE
bb generate_demo_library.py

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#1876]
With bb-211114 Unable to run generate_demo_library.py (Latest commit a1b462a on Sep 1)

Traceback (most recent call last):
  File "\generate_demo_library..py", line 193, in <module>
  File "\generate_demo_library..py", line 119, in generate
  File "\generate_demo_library..py", line 153, in create_type
AttributeError: 'NoneType' object has no attribute 'data'
Error: Python script failed, check the message in the system console

**Comment by Moult** [comment]
The commit you're linking to is old. Have you tried with the latest `generate_demo_library.py` file? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/generate_demo_library.py - and it needs to be run from the https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/demo-library.blend file

**Comment by Moult** [comment]
Closing as should be working with latest file.
