### ISSUE TITLE
IFC2x3 - applicable types for IfcFlowTerminal, IfcFlowFitting etc.

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#1879]
I want to apply an IfcOutletType to an IfcFlowTerminal instance (which in IFC2x3 should be valid, iirc), but I cannot select it from the dropdown.  Same applies for CableCarrierFittings (type of IfcFlowFitting).

**Comment by aothms** [comment]
Not sure about the UI, but, in the json mapping at least, the relationship is established https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/entity_to_type_map_2x3.json#L200-L212

**Comment by TZwielehner** [comment]
When I use the BlenderBIM tool to Add Type Instance, these types also lead to an error ('NoneType object has no attribute 'data')

**Comment by TZwielehner** [comment]
I had an issue with yesterday's build, tried again with today's. Types show up now, but I still get the "NonType" error. An instance is placed but only with the default dummy cube.

**Comment by Moult** [comment]
Seems to work here - perhaps we can screenshare on the OSArch live chat to see what's happening on your end?

![2021-11-17-093501_625x528_scrot](https://user-images.githubusercontent.com/88302/142077271-385c5c3b-69ed-4510-863f-adbda8b330c2.png)

**Comment by Moult** [comment]
Ping @TZwielehner

**Comment by Moult** [comment]
Closing due to lack of response, and seems to work on my end.
