### ISSUE TITLE
Unused build dependencies

### ISSUE THREAD

**Issue by Amoki** [IfcOpenShell/IfcOpenShell#1880]
Many dependencies are defined here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/nix/build-all.py#L222 but `yacc` never seems to be used. Is it still relevant? Are there more dependencies that may be removed?
cc @aothms

**Comment by aothms** [comment]
I don't even remember why yacc is there. At first glance I don't see others that can be eliminated.

**Comment by Moult** [comment]
@Amoki could you help remove yacc for some closure on this bug? :)
