### ISSUE TITLE
OCC 7.6

### ISSUE THREAD

**Issue by bimworld** [IfcOpenShell/IfcOpenShell#1883]
Is there already experience with the new OCC 7.6 release? Is it safe to use with OpenShell?

**Comment by aothms** [comment]
Haven't tried yet myself, read in the change notes that some depricated apis were removed, maybe ifcopenshell doesn't compile with it out of the box. Did you try?

**Comment by bimworld** [comment]
Ok, I tested. It's giving an error for Poly_Triangulation. 

> error: ‘class Poly_Triangulation’ has no member named ‘Nodes’; did you mean ‘Node’?
  199 |        const TColgp_Array1OfPnt& nodes = tri->Nodes();


Seems like the function Nodes() was removed ([7.5.0](https://dev.opencascade.org/doc/occt-7.5.0/refman/html/class_poly___triangulation.html#a8ce816a24ff688376f32a488d8b5ca70))

**Comment by aothms** [comment]
Yep, apparently the array is internal now and we need to access elements using `Node(int)` and `UVNode(int)`. https://dev.opencascade.org/doc/occt-7.2.0/refman/html/class_poly___triangulation.html#ac271c2b96f2e7f49901d3cbf2d3e7f5a This is available from 7.2 onwards. I'm fine with requiring 7.2 minimal for IfcOpenShell 0.7. Are you interested in making these changes?

**Comment by bimworld** [comment]
Im using v0.6.0.

Is this correct? 
```
    TColgp_Array1OfPnt nodes(1, tri->NbNodes());
    for (int i = 1; i <= tri->NbNodes(); i++)
        nodes(i) = tri->Node(i);
```

**Comment by aothms** [comment]
In the case below it's a const reference because that is the return type of Poly_Triangulation. So your proposal is ok. It's not the most performant because you're creating a copy, but it's probably not noticeable.

I will rebase on 0.7 if you send in a Pull Request. Thank you for your effort.

**Comment by bimworld** [comment]
Ok i tried, see https://github.com/IfcOpenShell/IfcOpenShell/pull/1887

With this, the old error is gone. There is something new:

> In file included from /usr/local/include/opencascade/Adaptor3d_HCurve.hxx:156,
>                  from /usr/local/include/opencascade/BRepAdaptor_HCompCurve.hxx:24,
>                  from /home/fluid/Downloads/IfcOpenShell-0.6.0/src/ifcgeom/IfcGeomWires.cpp:95:
> /usr/local/include/opencascade/Adaptor3d_HCurve.lxx: In member function ‘opencascade::handle<Adaptor3d_HCurve> Adaptor3d_HCurve::Trim(Standard_Real, Standard_Real, Standard_Real) const’:
> /usr/local/include/opencascade/Adaptor3d_HCurve.lxx:77:22: error: could not convert ‘Adaptor3d_Curve::Trim(((Standard_Real)First), ((Standard_Real)Last), ((Standard_Real)Tol))’ from ‘handle<Adaptor3d_Curve>’ to ‘handle<Adaptor3d_HCurve>’
>    77 |   return Curve().Trim(First,Last,Tol);
>       |          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~
>       |                      |
>       |                      handle<Adaptor3d_Curve>

Im totally not familiar with handle stuff. So maybe someone else can continue.

**Comment by aothms** [comment]
I also never understood the difference between Adaptor3d_Curve and Adaptor3d_HCurve tbh.

It appears this error is obtained solely by importing BRepAdaptor_HCompCurve.hxx

Looking at https://github.com/Open-Cascade-SAS/OCCT/find/V7_6_0 it seems that file doesn't exist anymore? Maybe it's there as an artefact of some older build step or something.

Can you reproduce this error on an empty file with just the include? That would be something to report to OCCT https://tracker.dev.opencascade.org/my_view_page.php

The change in IfcOpenShell would be to remove the HCompCurve include and just pass the Adaptor3d_Curve (without H) to Approx_Curve3D https://dev.opencascade.org/doc/refman/html/class_approx___curve3d.html

This would then need to be inside an `#if OCC_VERSION_HEX >= 0x70600` because I don't think this change would be backwards compatible.

**Comment by bimworld** [comment]
As already said, I have no idea and I'm not confident with handles. I tested for you without the include and removing the "H":

```
		BRepAdaptor_CompCurve cc(w, true);
		//Handle(Adaptor3d_HCurve) hcc = Handle(Adaptor3d_HCurve)(new BRepAdaptor_HCompCurve(cc));
		// @todo, arbitrary numbers here, note they cannot be too high as contiguous memory is allocated based on them.
		Approx_Curve3d approx(cc, getValue(GV_PRECISION), GeomAbs_C0, 10, 10);
```

This leads to

> IfcGeomWires.cpp:489:71: error: no matching function for call to ‘Approx_Curve3d::Approx_Curve3d(BRepAdaptor_CompCurve&, double, GeomAbs_Shape, int, int)’
>   489 |   Approx_Curve3d approx(cc, getValue(GV_PRECISION), GeomAbs_C0, 10, 10);

should be 

> Approx_Curve3d (const Handle< Adaptor3d_Curve > &Curve, const Standard_Real Tol3d, const GeomAbs_Shape Order, const Standard_Integer MaxSegments, const Standard_Integer MaxDegree)

**Comment by aothms** [comment]
BRepAdaptor_CompCurve is a subtype of Adaptor3d_Curve but you need to pass a handle.

I'm also not entirely sure as I haven't checkout 7.6 yet.

* Perhaps BRepAdaptor_CompCurve defines an `operator new` to return a handle. Then it might be sufficient to change `cc` to `auto cc = new BRepAdaptor_CompCurve(w, true)`.
* Otherwise we need to construct the handle ourselves maybe `Handle(BRepAdaptor_CompCurve) cc(new BRepAdaptor_CompCurve(w, true));`
* Hopefully handles support inheritance, I'm not fully sure if not we can probably get away with `Handle(Adaptor3d_Curve) cc(new BRepAdaptor_CompCurve(w, true));` to instantiate the more general handle type.

I have quite good hopes for the first option.

**Comment by bimworld** [comment]
Do you know why the pull request CI fails? I looked until 7.3.0 and there are attributes Node() and UVNode()?

> home/runner/work/IfcOpenShell/IfcOpenShell/src/ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/IfcGeomRepresentation.h:213:36: error: ‘class Poly_Triangulation’ has no member named ‘UVNode’; did you mean ‘UVNodes’?

**Comment by aothms** [comment]
CI still runs against OCE from the package manager which is OCCT 6.9.

IfcOpenShell 0.6 is also intended to remain compatible with OCCT <7

That's why I mentioned I'd rebase your PR onto 0.7. But also there CI needs to be updated to run OCCT >7

**Comment by aothms** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/commit/461b78665a726e91954cfea4e2658213b0da4161

**Comment by luzpaz** [comment]
Related: https://github.com/conda-forge/ifcopenshell-feedstock/pull/20

**Comment by adrianinsaval** [comment]
what's the status of this? is 0.7 compilable with occ 7.6 which is the PR mentioned here?

**Comment by Natcheuma** [comment]
Hello @aothms, 
Has anyone been able to figure out the issue in the meantime? I just discovered Ifcopenshell and followed the installation steps as given in the readme (ubuntu 20.04). But I got the following two errors:
-- IfcGeomRepresentation.h:212:31: error: ‘class Poly_Triangulation’ has no member named ‘Node’; did you mean ‘Nodes’? coords.push_back(tri->Node(i).Transformed(loc).XYZ());
-- ‘class Poly_Triangulation’ has no member named ‘UVNode’; did you mean ‘UVNodes’? const gp_Pnt2d& uv = tri->UVNode(I);
Thanks

**Comment by m-clare** [comment]
@Natcheuma and @aothms, I also just upgraded to a new M1 mac and am now getting the same errors on build:
```
/Users/maryannewachter/workspaces/open_source/IfcOpenShell/src/ifcgeom/../ifcgeom/IfcGeomRepresentation.h:198:47: error: no member named 'Nodes' in 'Poly_Triangulation'
                                                        const TColgp_Array1OfPnt& nodes = tri->Nodes();
                                                                                          ~~~~~^
/Users/maryannewachter/workspaces/open_source/IfcOpenShell/src/ifcgeom/../ifcgeom/IfcGeomRepresentation.h:199:47: error: no member named 'UVNodes' in 'Poly_Triangulation'
                                                        const TColgp_Array1OfPnt2d& uvs = tri->UVNodes();
                                                                                          ~~~~~^

```
Opencascade install details as follows:

```
maryannewachter@Maryannes-MBP build % brew info opencascade
opencascade: stable 7.6.2 (bottled)
3D modeling and numerical simulation software for CAD/CAM/CAE
https://dev.opencascade.org/
/usr/local/Cellar/opencascade/7.6.2 (9,454 files, 168.3MB) *
  Poured from bottle on 2022-06-12 at 15:50:38
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/opencascade.rb
License: LGPL-2.1-only
```

**Comment by Moult** [comment]
Bump @aothms

**Comment by aothms** [comment]
7.6 compatibility is in. The latest conda builds are also against 7.6
