### ISSUE TITLE
BIMTester, if translated feature fails, behave does not catch the exception

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#1888]
tested on https://github.com/IfcOpenShell/IfcOpenShell/commit/04535d27ecc1af7bcb25f340b4d9f323355885a5

If features in other languages than englisch are used and they fail there are problems ... 

find python code here to run the example ... https://community.osarch.org/discussion/comment/9690/#Comment_9690

try Englisch feature file with column example: add the following test and run bimtester ...
```gherkin
Scenario: Properties
 * All "IfcBuildingElement" elements have an "MyProperty" property in the "MyPset" pset
```
the test will fail because  "MyPset.MyProperty" does not exist in the ifc. In the html report is says ...

```
All "IfcBuildingElement" elements have an "MyProperty" property in the "MyPset" pset 0.0s

Assertion Failed: All 1 IfcBuildingElement elements are missing the property MyProperty in the pset.
```

try German feature file with column example: add the following test and run bimtester ...
```gherkin
Szenario: Attribute
 * Alle "IfcBuildingElement" Bauteile haben das Attribut "MyProperty" im PSet "MyPset"
```
the test will fail but the exception is not catched. In in the html report is says ...

```
Alle "IfcBuildingElement" Bauteile haben das Attribut "MyProperty" im PSet "MyPset" 0.02s

Substep info: Assertion Failed: All 1 IfcBuildingElement elements are missing the property MyProperty in the pset.
Traceback (of failed substep):
File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.20.xxxxx\bin\lib\site-packages\behave\model.py", line 1329, in run
match.run(runner.context)
File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.20.xxxxx\bin\lib\site-packages\behave\matchers.py", line 98, in run
self.func(context, *args, **kwargs)
File "C:\Users\BHA\Desktop\IfcOpenShell\src\ifcbimtester\bimtester\features\steps\attributes_psets\en.py", line 11, in step_impl
eleclass_has_property_in_pset(
File "C:\Users\BHA\Desktop\IfcOpenShell\src\ifcbimtester\bimtester\features\steps\attributes_psets\en.py", line 81, in eleclass_has_property_in_pset
assert_elements(
File "C:\Users\BHA\Desktop\IfcOpenShell\src\ifcbimtester\bimtester\util.py", line 108, in assert_elements
assert False, message_all_falseelems.format(elemcount=elemcount, ifc_class=ifc_class, parameter=parameter)
```

If at this code line the method is called instead the english test it works fine ... https://github.com/IfcOpenShell/IfcOpenShell/blob/04535d27ecc1af7bcb25f340b4d9f323355885a5/src/ifcbimtester/bimtester/features/steps/attributes_psets/de.py#L9

should be changed to
```python
    #context.execute_steps(f'* All "{ifc_class}" elements have an "{aproperty}" property in the "{pset}" pset')
    from bimtester.features.steps.attributes_psets.en import eleclass_has_property_in_pset
    eleclass_has_property_in_pset(
        context,
        ifc_class,
        aproperty,
        pset
    )
```
Than the test fails too but the exception is catched like on English feature file example ...
```
Alle "IfcBuildingElement" Bauteile haben das Attribut "MyProperty" im PSet "MyPset" 0.0s

Assertion Failed: All 1 IfcBuildingElement elements are missing the property MyProperty in the pset.
```

**Comment by berndhahnebach** [comment]
Could someone confirm the problem?

It would be cool if behave would catch the exeption because the use of "context.execute_steps(the englisch step)" is much smarter then calling the method directly IMHO.

**Comment by berndhahnebach** [comment]
https://github.com/behave/behave/issues/981

**Comment by berndhahnebach** [comment]
The exceptions are raised, thus it works fine. I did describe it bad. My misstake. What I would like to have is to omit the traceback prints. See the linked issue on behave repository. ATM this is a limitation of behave. Thus I will close it for now,

**Comment by aothms** [comment]
> What I would like to have is to omit the traceback prints

Luckily in Python there are always crazy hacks you can do like temporarily reassigning sys.stderr

~~~
>>> import sys,io
>>>
>>> a = b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'b' is not defined
>>>
>>> sys.stderr, old_stderr = io.StringIO(), sys.stderr
>>>
>>> a = b
>>>
>>> sys.stderr = old_stderr
>>>
>>> a = b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'b' is not defined
>>>
~~~

^ the middle traceback is suppressed by reassigning stderr
