### ISSUE TITLE
ifcopenshell - editing a pset property and changing value type results in error

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1889]
If I attempt to edit the pset property value as well as value type (String -> Boolean), I get an error message:

Example:
```
element = ifc.createIfcWall()    
pset = ifcopenshell.api.run("pset.add_pset", ifc, product=element, name="Pset_Name")
ifcopenshell.api.run("pset.edit_pset", ifc, pset=pset, properties={"foo": "foobar"})
psets = ifcopenshell.util.element.get_psets(element)
ifcopenshell.api.run("pset.edit_pset", ifc, pset=ifc.by_id(psets["Pset_Name"]["id"]), properties={"foo": True})  
```

Error Message:
`ValueError: Expected String for attribute IfcLabel.wrappedValue, got True.`

This can obviously be circumvented by checking whether the new value is of the same type as the existing, but I wonder whether it might be better if the command just changed the value type?  Or is this not wanted?

**Comment by aothms** [comment]
I can imagine the behaviour is to updating psets from models so that you retain IfcIdentifier/IfcLabel/IfcText. That's probably a good thing. So I would just check the output of `old_value.attribute_type(0)` and see if corresponds to `new_value`

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/api/pset/edit_pset.py#L82-L83

**Comment by vulevukusej** [comment]
Ok, and if I wanted to change the type I would go about removing the property instance first, and then creating a new instance - or do you recommend a better approach?

**Comment by vulevukusej** [comment]
Just to give you a use case to understand why I want this:   We receive models sometimes where a parameter should be boolean, but the modeller has instead written "true" or "false" as a text parameter.  I want to iterate through the model objects and change the parameter to a boolean.

**Comment by vulevukusej** [comment]
What my current workaround is:

`for definition in ifc_element.IsDefinedBy:
                        if definition.is_a('IfcRelDefinesByProperties'):
                            prop_set = definition.RelatingPropertyDefinition
                            if prop_set.Name != prop.pset_name:
                                continue
                            for hasprop in prop_set.HasProperties:
                                if hasprop.Name != prop.property_name:
                                    continue
                                self.file.remove(hasprop)
                    #after deleting the existing property, re-add the property with the new value type
                    ifcopenshell.api.run("pset.edit_pset", self.file, pset=self.file.by_id(psets[prop.pset_name]["id"]), properties={prop.property_name:value})`

**Comment by aothms** [comment]
I didn't test this, but perhaps you could allow both of the following (maybe already possible), either a native python type or a IFC schema datatype:

ifcopenshell.api.run("pset.edit_pset", ifc, pset=pset, properties={"foo": "foobar"})

ifcopenshell.api.run("pset.edit_pset", ifc, pset=pset, properties={"foo": ifc.createIfcText("foobar")})

**Comment by vulevukusej** [comment]
Ok i'll give that a quick go.

**Comment by vulevukusej** [comment]
Nope, didn't work:
