### ISSUE TITLE
Convert IFC to 3ds MAX by MAXScript

### ISSUE THREAD

**Issue by eryar** [IfcOpenShell/IfcOpenShell#189]
For building the 3ds Max plug-in, it is need 3ds Max SDK, and the 3ds MAX SDK have dependency with the 3ds MAX version.

So I suggest to convert IFC to 3ds MAX by generate MAXScript file, and then build the model in 3ds MAX by run the MAXScript. This will have no dependency with 3ds MAX version.

Best Regards,
Shing Liu

**Comment by aothms** [comment]
Thanks for this suggestion, I agree that maintaining the 3ds max importer and interface is not feasible. The amount of users is small and the profile of a proprietary software package doesn't match well with the ambitions of IfcOpenShell.

A conversion to MAXscript on the other hand is not likely to be very feasible either. Keep in mind IfcOpenShell and its dependencies form a large C++ code base.

In the long run 3ds max users can use IfcConvert to convert their models to Collada prior to importing in 3ds max. This is functionally equivalent to the direct conversion and offers a wide variety of conversion settings that will never be made available in the limited plugin importer UI.
