### ISSUE TITLE
Functionality to easily add/edit properties and values

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1890]
I created a little addon for myself.  I'm hesitant to add it as a pull request though since I'm not sure:
a) whether this is desired as part of the main BB plugin
and b) under which panel to put it in case it's desired:

The plugin allows the user to:

1. Bulk rename any parameter that is of type:  "IfcBuildingElement"
2. Add a single, custom property to all selected objects
3. Change the value and value-type of any parameter (again for all selected objects)

![image](https://user-images.githubusercontent.com/83825269/142879659-74747d75-51f8-430b-b4ec-714e3398eb0a.png)

Feedback?

**Comment by Moult** [comment]
This looks great! Please feel free to commit.
