### ISSUE TITLE
The bimtester gui does not work

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#1893]
Most of the bimtester gui seams to still use the old run module before the big changes in spring. No wonder it does not work. 

AFAIR @rbertucat had a improved GUI. If this improves GUI we do not fix the current one. I can just not find this improved Gui.

cheers bernd

**Comment by Moult** [comment]
Pinging @rbertucat - more than happy to deprecate the old GUI and have his more active code take the lead on development :)

**Comment by berndhahnebach** [comment]
fixed: 1a5b5dd3036caea894834c0032360fcb53e4108d

I leave it open for a while because I am still interested in getting the improved GUI into BIMTester

**Comment by Moult** [comment]
Let's close it in a week if still no response :) In the future @rbertucat is always welcome to contribute.

**Comment by berndhahnebach** [comment]
ok

**Comment by rbertucat** [comment]
sorry guys, I have no bandwidth right now to work on that - @berndhahnebach the code of the 'improved' GUI is there: https://github.com/IFCRail/IfcOpenShell. Keep in mind that this was mainly developed to support the specific use case of IFCRail at that time, so it might not be a good fit for any use case.

**Comment by berndhahnebach** [comment]
Where?

The guiwidget in this repository has no changes ... https://github.com/IFCRail/IfcOpenShell/commits/v0.7.0/src/ifcbimtester/bimtester/guiwidget.py

**Comment by rbertucat** [comment]
https://github.com/IFCRail/IfcOpenShell/blob/v0.7.0-bt-plus/src/ifcbimtester/guiplus.py is the main class containing the changes. We haven't changed the existing one.
Thanks

**Comment by berndhahnebach** [comment]
> https://github.com/IFCRail/IfcOpenShell/blob/v0.7.0-bt-plus/src/ifcbimtester/guiplus.py is the main class containing the changes. We haven't changed the existing one. Thanks

Great! I somehow missed this ... I will have a look at this gui. 

cheers bernd

**Comment by Moult** [comment]
@berndhahnebach feel free to close this issue when you believe all meaningful changes have been merged :)
