### ISSUE TITLE
File segfaults with geometry caching

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1894]
I've got a rather large private file (~330mb) that seems to segfault when geometry caching is enabled. I'm struggling to replicate it since with this minimal snippet, it also segfaults with geometry caching disabled, although I can't see what I've done wrong. I've sent the file to models@ifcopenshell.org

```python
import time
import ifcopenshell
import ifcopenshell.geom
import multiprocessing
f = ifcopenshell.open('segfault-file.ifc')
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, f, multiprocessing.cpu_count())
cache = ifcopenshell.geom.serializers.hdf5('cache.h5', settings)
iterator.set_cache(cache)
iterator.initialize()
total = 0
while True:
    total += 1
    if total % 250 == 0:
        print("{} elements processed in {:.2f}s ...".format(total, time.time() - checkpoint))
        checkpoint = time.time()
    shape = iterator.get()
    if shape:
        product = f.by_id(shape.guid)
        #print(product)
    if not iterator.next():
        break
print("Done creating geometry")
```

**Comment by aothms** [comment]
I let it run a couple of times and didn't find anything odd. Could be related to #1895 perhaps.

If not, I've added a

~~~
ifcopenshell.ifcopenshell_wrapper.turn_on_detailed_logging()
~~~

That maybe gives some clues in the console about what's going on.

**Comment by Moult** [comment]
Hmm, I think it's just my machine. I pulled the latest, cleared my build folder and tried again and now it works, as well as a bunch of other smaller files that were segfaulting. Maybe there were some old build artefacts when I was trying to write some C++ (even though my git status showed I had reverted those changes). Sorry for the noise and thanks for investigating! :)
