### ISSUE TITLE
BlenderBIM: Change the `IfcExtrudedAreaSolid/Depth` value of multiple, similar objects, at the same time.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1900]
Would be nice to bulk change the `IfcExtrudedAreaSolid/Depth` value of multiple, similar objects (walls, mostly), at the same time.

**Comment by Gorgious56** [comment]
Hey is this a feature request for the Blenderbim interface or ifcopenshell in general ?

**Comment by theoryshaw** [comment]
Sorry, yes, it would be BlenderBIM. I'll change the title for clarify.

**Comment by Moult** [comment]
This is now possible via the BIM tool.
