### ISSUE TITLE
edit_pset - still results in error when changing data_type

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1909]
So the current, updated code looks like this:

```
def update_existing_property(self, prop):
        if prop.Name not in self.settings["properties"]:
            return
        value = self.settings["properties"][prop.Name]
        if value is None:
            prop.NominalValue = None
        elif isinstance(value, ifcopenshell.entity_instance):
            prop.NominalValue = value
        else:
            primary_measure_type = self.get_primary_measure_type(prop.Name, old_value=prop.NominalValue, new_value=value)
            prop.NominalValue = self.file.create_entity(primary_measure_type, value)
        del self.settings["properties"][prop.Name]
```

Unfortunately, if you try to change a property that is IfcBoolean into, let's say a string (IfcLabel) - it won't work and you will still get an Error.

Changing line 10 in the code to:

```
primary_measure_type = self.get_primary_measure_type(prop.Name, new_value=value)
```

seems to fix this.  If you agree that this is OK I will submit a PR, otherwise please let me know what I'm inadvertently breaking by changing this code :)

**Comment by Moult** [comment]
That line of code shouldn't be triggered if you are using explicit entities. See this test case: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/test/api/pset/test_edit_pset.py#L127-L149

Is that test case the same as what you are attempting, or are you doing something else?

**Comment by vulevukusej** [comment]
No I´m not passing an explicit entity into "pset.edit_pset".  I thought it was quite handy that I didn't have to do this, because in my edited version of the code, primary_measure_type would return the new type and then proceed to create a new entity based on this new type.  I´m guessing you would rather that I create the new entity first, and then pass it into ifcopenshell.api.run("pset.edit_pset".........

**Comment by vulevukusej** [comment]
closed, since the error is due to not passing an explicit entity.
