### ISSUE TITLE
Is it possible to do integration of IFC Viewer in iOS ?

### ISSUE THREAD

**Issue by Tamil-Arya** [IfcOpenShell/IfcOpenShell#191]
Hi, i have one scenario as i have to view the IFC file into my iOS app ( ex: building blue print IFC file ). Is there any way please comment here,.

**Comment by aothms** [comment]
It'll surely be possible, but not a trivial effort. Have a look at how others have incorporated C++ code into their Objective-C programs. Considering the memory footprint and processing time involved with viewing IFC BIM models, other apps typically use a web-based components or do preprocessing of the models for easier visualisation in the authoring software.

Hope that helps,

Kind regards,
Thomas

**Comment by Tamil-Arya** [comment]
Thanks, For your reply. I understood your concepts but i tried more way along with C++ code of BIM. even though i couldn't find any useful idea as well link. If you have any code about C++ with use of Obj C. Please share the link or Code. 

Thanks & Regards 
Tamil
