### ISSUE TITLE
BB Partial loading

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#1913]
Test case an [example file](https://www.opensourcewood.com/pages/Idea.aspx?i=369) downloaded off the net. It opens ok in BB. Loading with decomposition, I get all kind of issues. ifcAssembly will only load the ifcAssemblyClass and not the contained objects. Trying other decomposition, like for instance a specific Storey will crash BB. 

Not sure if this is the way to test, since quality of downloaded file is unknown?

**Comment by Gorgious56** [comment]
Could you go to Window > Toggle System Console and copy / paste any error message you see there (if any :) )

**Comment by Moult** [comment]
Filtering by class will only select items of that class, so the behaviour you describe about filtering assemblies only bringing in assemblies and not their contained objects is normal behaviour.

I've fixed the decomposition bug. I didn't get a crash though... maybe its related to the other set of crashes we're getting over in #1906. I'm noticing it more and more.
