### ISSUE TITLE
Access the internal attribute information of each entity

### ISSUE THREAD

**Issue by keleisi2001** [IfcOpenShell/IfcOpenShell#1915]
Take IfcMaterial and IfcMaterialLayer as examples. When I tried to get the "Name" information of IfcMaterial and the "thickness" information of IfcMaterialLayer, the program told me that the entity does not have this attribute. However, there is a "name" tag in IfcXML. This confuses me. Attached are the screenshots.

What should I do if I want to read "200" and "20" in IFCMATERIALLAYER? Attribute access? Or is it cutting the string?

![layer_thickness](https://user-images.githubusercontent.com/55388367/144620891-e9324b70-ba09-4b28-ad05-a380bfdf94d0.png)
![LayerThickness in IfcXML](https://user-images.githubusercontent.com/55388367/144620899-9e2506f7-ce91-4235-bb86-7781eecba393.png)
![material](https://user-images.githubusercontent.com/55388367/144620902-4f68e226-1606-4f67-afa8-6721ed2d2942.png)
![LayerThickness in Ifc](https://user-images.githubusercontent.com/55388367/144621468-cc5289b4-bb80-4cf6-bdff-22d0de6ccea0.png)

**Comment by aothms** [comment]
The error is

~~~
AttributeError: 'list' object has no attribute 'name'
                ^^^^^^
~~~
         
by_type() returns a list. The **elements** in that list have a Name attribute. Capital N.

try e.g

`print([m.Name for m in materials])`

or

`print(materials[0].Name)`

**Comment by keleisi2001** [comment]
> print(materials[0].Name)

Fine. All the attribute information has been obtained so far

**Comment by Moult** [comment]
Closing as fixed :)
