### ISSUE TITLE
Exception on trying to enable Import-Export: BlenderBIM v 2.92.0 OSX 11.6

### ISSUE THREAD

**Issue by lmwald** [IfcOpenShell/IfcOpenShell#1916]
<img width="1123" alt="Screenshot 2021-12-05 at 15 20 33" src="https://user-images.githubusercontent.com/49959862/144752722-705bc3d6-0981-4d35-85fc-509bcf7c4b17.png">

**Comment by Moult** [comment]
If you are using Blender <2.93, you will need to download a Py37 version available here: https://github.com/IfcOpenShell/IfcOpenShell/releases

**Comment by lmwald** [comment]
Thanks this worked.

Should I use Blender 3?

Here
<https://drive.google.com/file/d/15kHpd51RyhkNWwo4MlgctaXhwfpinyj-/view?usp=sharing>
is a link a simple model 2.93. Section tool not working properly. Any ideas?

rgds

Louis

**Comment by lmwald** [comment]
I tried blenderbim-211031-py39-macos with Blender 3.

Not much luck. Did not work at all.

rgds

Louis

**Comment by Moult** [comment]
@lmwald I cannot access your file. Can you please share it with dion@thinkmoult.com ?

**Comment by Moult** [comment]
Reopening issue - but please in the future create a new issue so it's easier to track.

**Comment by lmwald** [comment]
Apologies. Attached is a zip with the blend file.

[Cup Section.blend.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/7693098/Cup.Section.blend.zip)

**Comment by Moult** [comment]
Your cup object is not a closed mesh (it is merely a surface which is not closed), and so therefore it is physically impossible to cut a section. Only solids can have sections cut through it.

![2021-12-22-111411_332x293_scrot](https://user-images.githubusercontent.com/88302/147013853-45d88f33-3274-4d2e-924d-13d1705ea12e.png)
