### ISSUE TITLE
Blender 3 BUG  Node: IFC for Sverchok

### ISSUE THREAD

**Issue by odds57** [IfcOpenShell/IfcOpenShell#1918]
Traceback (most recent call last):
File "E:\Blender 3\3.0\scripts\modules\addon_utils.py", line 351, in enable
mod=_import_(module_name)
File"C:\Users\Odd\AppData\Roaming\Blender Foundation\Blender\3.0\Scripts\addons\ifcsverchok\_init_.py", line 16, in <module>
import sverchok
ModuleNotFoundError: No module named 'sverchok'

**Comment by Gorgious56** [comment]
Did you download and install the sverchok add-on ?

**Comment by odds57** [comment]
No, but I get a mail :These add-ons are not shipped with Blender anymore
so Thank you for this message
