### ISSUE TITLE
IfcConvert crashes when run

### ISSUE THREAD

**Issue by TripleSnail** [IfcOpenShell/IfcOpenShell#192]
IfcConvert crashes with any input. Even --help is enough to crash it:
```
➜  bin git:(master) ✗ ./IfcConvert --help                   
IfcConvert: /***/ios-pristine/src/ifcconvert/../ifcconvert/../ifcgeom/../ifcgeom/IfcGeomFilter.h:149: void IfcGeom::string_arg_filter::assert_arguments(): Assertion `it->second < base->getArgumentType(it->second) == IfcUtil::Argument_STRING && "Argument type not string"' failed.
[1]    14309 abort (core dumped)  ./IfcConvert --help
```

The binary was compiled from a freshly cloned repository with `python build-all.py`

I'm on Ubuntu 16.04

**Comment by TripleSnail** [comment]
The same happens when I don't use the build script but install the dependencies with apt and by invoking cmake like in README

**Comment by Stinkfist0** [comment]
Shouldn't assertions be disabled/no-ops when doing Release/RelWithDebInfo (which should be the default for the project on *nix) build. In any case, this assert() is my doings, will check it right now.

**Comment by aothms** [comment]
I was also under the impression that RelWithDebInfo would add a `-DNDEBUG` to the command line which should render the `assert()` as a noop. I did get a compile time warning about this assertion typo, but forgot to follow up on it. Thanks for the report @TripleSnail and thanks for the quick fix @Stinkfist0.
