### ISSUE TITLE
UI Rethink

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1920]
I know it's currently not a priority since the focus is on functionality, however, I thought it might me a decent quality of life improvement if we grouped some of the panels into broader panel groups, and then nest panels under them.  Below is how it currently looks when all panels are activated, and it`s a little daunting.  
![image](https://user-images.githubusercontent.com/83825269/144882349-175cd6c7-85b4-4fb0-9b39-12a18873bf11.png)

Even after toggling some of the Modules on/off, it's still difficult to move across panels.  Just in the example above, some potential panel groups could be:

-IFC Geometry and Spatial Structure
- ---Voids
- ---Representations
- ---Spatial Container

-IFC Data Management
- ---Property Sets
- ---Quantity Sets
- ---Bulk Property Editor
- ---Classification References

Another benefit is that it reduces the amount of "IFC" prefixes everywhere.

If this is something that makes sense, feel free to assign the issue to me and I'll make a draft pull request.

**Comment by Gorgious56** [comment]
Ideally I think we would have a whole (or even several) new property docks for ifc data, like we have for scene, world, modifiers, etc. but unfortunately its not possible unless modifying the underlying source code (and distributing a fork of Blender...) .

I think if we can sub-group panels smartly as you suggested it will make the interface less overwhelming and easier to navigate. We would need to think of a way to keep the number of clicks to the absolute minimum though.

**Comment by Moult** [comment]
Sverchok creates a whole new panel. Is it possible to create a new properties panel somehow?

**Comment by Gorgious56** [comment]
AFAIK It's only possible to add custom node editors using the python API

**Comment by Moult** [comment]
Happy to have UI PRs :) Also something perhaps to look into is a BIM application template.

**Comment by Gorgious56** [comment]
@Moult I just stumbled upon this hackity monstrosity to emulate a new custom editor https://devtalk.blender.org/t/add-custom-spaces-in-python-api/19971/7

**Comment by Moult** [comment]
Oh wow that's pretty funky, but not something I'd like to pour effort into personally. Maybe @vulevukusej you can do a small mockup of your subpanel idea?
