### ISSUE TITLE
BlenderBim : Adding a Structural Analysis model throws error

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1923]
Adding a new Structural Analysis model throws an error.

![image](https://user-images.githubusercontent.com/25156105/145032251-2decab23-6ab2-4159-8787-4c456c064a4d.png)

```

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\structural\operator.py", line 267, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\ifc.py", line 243, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\structural\operator.py", line 280, in _execute
    bpy.ops.bim.add_subcontext(context="Model", subcontext="Reference", target_view="GRAPH_VIEW")
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.bim.add_subcontext" error, could not be found
```

It comes from this line in the code https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/structural/operator.py#L280

It complains that `bim.add_subcontext` operator was never defined. I digged a bit in the code to see if it was not a typo but could not find anything related to adding a subcontext. There is a `bim.add_context` [operator](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/context/operator.py#L35-L51) but it seems it's more related to geometric representation ?

**Comment by Moult** [comment]
The original name "add_subcontext" was chosen in the very early versions of the BlenderBIM Add-on, where the contexts were fixed as "Model" and "Plan" and you could only ever add a subcontext. Since then, we now support managing both contexts and their subcontexts, and so it is now deprecated in favour of "add_context".
