### ISSUE TITLE
mpfr-checking error on build-deps.cmd

### ISSUE THREAD

**Issue by Ttofuuu** [IfcOpenShell/IfcOpenShell#1926]
![image](https://user-images.githubusercontent.com/49158715/145174166-2659885c-6623-4b05-a3cf-c756252a11f3.png)
I'm fresh to IFCOS, and I've tried several times to run the build-deps.cmd file, but it came to error every time when clonning the mpfr checking. 
So what should I do to avoid errors happened like this?

**Comment by aothms** [comment]
This is also reported and discussed here, it has a fix in this comment:

https://github.com/IfcOpenShell/IfcOpenShell/issues/1914#issuecomment-985783861

If you find the time, maybe you can send in a PR with ^ change so that more people don't run into this.

**Comment by Ttofuuu** [comment]
> This is also reported and discussed here, it has a fix in this comment:
> 
> [#1914 (comment)](https://github.com/IfcOpenShell/IfcOpenShell/issues/1914#issuecomment-985783861)
> 
> If you find the time, maybe you can send in a PR with ^ change so that more people don't run into this.

That's useful! I deleted old 'mpfr' file in '_deps' directory then 'build-deps.cmd' again, and new problems come out like error MSB8036. It seems I didnt run the 'build-deps.cmd' in a right way. I'm using x86x64 Cross Tools Command Prompt for VS 2019 to run this cmd, would you help me to figure out the right way to use VS 2019 to build IFCOS?
Soon I'll send a PR to fix the mpfr problem.

**Comment by Ttofuuu** [comment]
> > This is also reported and discussed here, it has a fix in this comment:
> > [#1914 (comment)](https://github.com/IfcOpenShell/IfcOpenShell/issues/1914#issuecomment-985783861)
> > If you find the time, maybe you can send in a PR with ^ change so that more people don't run into this.
> 
> That's useful! I deleted old 'mpfr' file in '_deps' directory then 'build-deps.cmd' again, and new problems come out like error MSB8036. It seems I didnt run the 'build-deps.cmd' in a right way. I'm using x86x64 Cross Tools Command Prompt for VS 2019 to run this cmd, would you help me to figure out the right way to use VS 2019 to build IFCOS? Soon I'll send a PR to fix the mpfr problem.

finally i update vs2019 to add the msvc v141 to build up the depends!!
but another problem comes up:
[CMakeError.log](https://github.com/IfcOpenShell/IfcOpenShell/files/7675903/CMakeError.log)
`Determining if the include file pthread.h exists failed with the following output:`
`Change Dir: D:/ifcOpenShell/IfcOpenShell-0.7.0/IfcOpenShell-0.7.0/_build-vs2019-x64/CMakeFiles/CMakeTmp`
i'll then google it

**Comment by Ttofuuu** [comment]
the src/svgfill directory is empty, so i go downloading it again and finally get the solution file. thanx alot!

**Comment by aothms** [comment]
> the src/svgfill directory is empty, so i go downloading it again and finally get the solution file. thanx alot!

Yeah a lot of people run into this. Either `clone --recursive` or afterwards, `git submodule update --init --recursive`.

Maybe we should add a line in CMakeLists.txt that checks this first and advises users what to do.
