### ISSUE TITLE
BB Crash report

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#1935]
Trying to load a 2x3 ifc file , (same result in 2.93 and 3.0) BTW it loads without issues in BimSync and Solibri
Win 10, blenderbim-211210-py39-win
[211210Crash.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/7692030/211210Crash.txt)

**Comment by Moult** [comment]
I think this is a duplicate of #1906 which I am seeing increasingly in more files. Hopefully it gets solved soon, potentially once the next IfcOpenBot build is out.

**Comment by cadgiru** [comment]
BTW maybe not of concern.. But Originator 
IFC file generated by GRAPHISOFT ARCHICAD 23.0.0 NOR FULL Windows version

**Comment by cadgiru** [comment]
Tried same file on NAME="Ubuntu" VERSION="20.04.3 LTS, Blender 3.0, bb211210
Sadly same result

**Comment by Moult** [comment]
Hmm, I hoped that would fix it. Can you send me the file dion@thinkmoult.com to see if I can replicate the crash?

**Comment by Moult** [comment]
@cadgiru bump - did I get a file?

**Comment by Moult** [comment]
Bump :)

Also, when you tried the new build, before importing, in your blenderbim add-ons folder, can you be sure to delete all `*.h5` files in your `bim/data/cache/` folder?

**Comment by Moult** [comment]
Closing until this can be replicated or retested.
