### ISSUE TITLE
IfcOpenBot builds ifcopenshell.version is truncated to -hash and misses branch

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#1937]
Check either https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/cmake/CMakeLists.txt#L796-L819

Or https://github.com/IfcOpenShell/IfcOpenBot

Reported by @Moult

**Comment by Moult** [comment]
Confirming as fixed! Woohoo!
