### ISSUE TITLE
When will the (ifcopenshell-python) 0.7.0 stable? latest? version be uploaded to this site http://ifcopenshell.org?

### ISSUE THREAD

**Issue by PlumpMath** [IfcOpenShell/IfcOpenShell#1939]
http://ifcopenshell.org
Isn't it the stable version?
It would be nice if the precompiled python module was also uploaded.

I use both nix (macos) and nixos (linux).
In the previous version of 0.6.0, the build was successful, but now it has changed, and the latest version is difficult to build.

build log:
https://github.com/NixOS/nixpkgs/issues/150504

Thanks,

**Comment by aothms** [comment]
For the time being look at https://github.com/IfcOpenBot/IfcOpenShell/commits/v0.7.0

Looking at the error log most seems to relate to cgal

~~~
�[1m/nix/store/7l4sscn4qbc6jbc57m2nihjcz02ab32a-cgal-5.3/include/CGAL/float.h:21:10: �[0m�[0;1;31mfatal error: �[0m�[1m'CGAL/utils.h' file not found�[0m
~~~

which is odd, it's just, maybe it's resolved if you take into account this

~~~
 �[1m/nix/store/7l4sscn4qbc6jbc57m2nihjcz02ab32a-cgal-5.3/include/CGAL/stddef.h:10:2: �[0m�[0;1;31merror: �[0m�[1mYou have added .../path/to/CGAL-x.y/include/CGAL to the INCLUDE path. You should use .../path/to/CGAL-x.y/include instead.�[0m
#error You have added .../path/to/CGAL-x.y/include/CGAL to the INCLUDE path. You should use .../path/to/CGAL-x.y/include instead.
~~~

**Comment by PlumpMath** [comment]
with brew install cgal and edit derivation...

-DCGAL_INCLUDE_DIR=${lib.getDev cgal}/include #(brew cgal path hang it.)
-DHDF5_SUPPORT=OFF

solved it

I don't know how to do upstream and PR, so I don't know how to ask the nix community; g,.g;
I need to learn ifcopenshell and blenderbim quickly... I'm not an architecture major, so I'm not sure about BIM, but thank you for making it. I am a Korean who is working alone in developing BEMS 3D software at the small company I work for. (I haven't applied it to work yet, but I've been watching this project long time.)

Thanks :)

**Comment by PlumpMath** [comment]
Right now, it can be installed with just cgla (without cgal.dev), but you have to configure mrperf and other things well.  It's easy if you just write the umbilical cord.  What I'm curious about is ifcopenshell, to be exact, a Revit replacement tutorial where you should see blenderbim from the beginning.  In Korea, we do not think about anything other than Revit.  The two original authors of ifcopenshell, please tell us about it.

**Comment by Moult** [comment]
@PlumpMath did the precompiled binaries work for you?

> What I'm curious about is ifcopenshell, to be exact, a Revit replacement tutorial where you should see blenderbim from the beginning.

This is a lot of work. But we are chipping away at it. If you help with testing and feedback, we can get there faster.

**Comment by Moult** [comment]
We now build for a number of channels and the documentation clearly illustrates how to install from all channels, so this can be closed.
