### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#194]
VS 2017 was just released. As we currently depend on the precompiled ICU on Windows/MSVC, we must wait for the new builds to appear at https://www.npcglib.org/~stathis/blog/precompiled-icu/

**Comment by aothms** [comment]
Hm yeah, ideally we'd compile ICU from source some day. In particular the data file contains a lot of unnecessary data for us, as we are only interested in some code pages defined in ISO 8859-x. This bloats up the executable size tremendously. I guess this isn't very high on either of our lists.

**Comment by Stinkfist0** [comment]
Yup, I have already put up an issue for https://github.com/IfcOpenShell/IfcOpenShell/issues/80

**Comment by Stinkfist0** [comment]
VS 2017 has built-in CMake support which looks pretty great. I will be looking forward for implementing support for that.

**Comment by aothms** [comment]
Hopefully wouldn't diverge from the original CMake codebase (you need cmake with msft specific patches now?), but it surely would be a treat to have proper win32, x64, debug, release environments within one solution.

**Comment by Stinkfist0** [comment]
I was mostly thinking simply additional feature that for VS >= 2017, that user can "build-deps VS 2017 x64" && "build-deps VS 2017 x86" and then "Open folder in Visual Studio" and stuff would work.

**Comment by Stinkfist0** [comment]
Also we might need to update Boost to the most recent (not yet released) 1.64, but I'll see if I can the currently used version (1.59) to compile with the latest MSVC.

**Comment by aothms** [comment]
Updating boost should be fine. We either need to keep using `-DBOOST_OPTIONAL_USE_OLD_DEFINITION_OF_NONE` which is defined in the CMake file, or fix this issue I believe in IfcOpenHouse.cpp where a copy of `boost::none` is created for the sake of brevity.

**Comment by Stinkfist0** [comment]
Updating Boost to 1.63.0, skipping ICU, and couple minor tweaks and I can get things rocking with VS 2017.

**Comment by Stinkfist0** [comment]
VS 2017 build available now at the website, but only for the latest ICU version, at least for now, so need to update to that.

**Comment by aothms** [comment]
> couple minor tweaks

@Stinkfist0 would it be a big effort quickly outline these major tweaks? I have some more people pondering upon VS2017.

**Comment by thorade** [comment]
Sorry to bother you: 
As #206 is on master, does it mean I can use it? 
Do I have to manually delete the boost and ICU directory before building the deps?
Boost 1.94 has by now been released, on April 19th.

**Comment by Stinkfist0** [comment]
Yes, currently one must manually delete the old directories in order to trigger fetching and building of the newer versions. Should probably document this somewhere.

**Comment by Stinkfist0** [comment]
Oh, and
```
30 April 2017 – NOTE: ICU 59.x upstream no longer supports any compilers prior to MSVC 2015. For older compilers the latest version is 58.2, which you can download from the Precompiled ICU (Past Builds) page.
```

However, the script currently uses 58.2 and we should not have immediate need for updating it, so it shouldn't be a problem if somebody is using an older Visual Studio.
