### ISSUE TITLE
(Feature suggestion) IFC Validation

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1940]
Just wondering whether there is something available already or planned that performs something similar to the "IFC Validation" tool in Xbim Xplorer?  

![image](https://user-images.githubusercontent.com/83825269/145777243-d57a8390-cd35-4f5f-a411-d9be21e318a7.png)

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/validate.py

Doesn't do where rules though

**Comment by vulevukusej** [comment]
Ah great, that still looks good though, thanks for the heads up!

**Comment by Moult** [comment]
A small note that it is also available in the IFC debug panel in the BlenderBIM add-on using the "Checkmark" icon :)

**Comment by vulevukusej** [comment]
you're absolutely right, I completely missed that, cheers!
