### ISSUE TITLE
Umlauts (ÄÜÖß) in dynamic enumerations

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1941]
Using umlauts in dynamically generated enums results in the symbols not being represented correctly.  There appears to be a workaround according to [https://blender.stackexchange.com/questions/216230/is-there-a-workaround-for-the-known-bug-in-dynamic-enumproperty](https://blender.stackexchange.com/questions/216230/is-there-a-workaround-for-the-known-bug-in-dynamic-enumproperty)

Thanks for the link @Gorgious56.  When I have time I'll create a pull request to address this.

**Comment by Moult** [comment]
So this is now fixed and can be closed?

**Comment by vulevukusej** [comment]
Yup fixed
