### ISSUE TITLE
create_entity does not escape quotation strings

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1944]
I'm not sure if I am doing this wrong, or if this is indeed a bug.  When I try to create an entity with "IfcLabel", the resulting step object doesn't escape the quotation strings, so I end up getting errors in my ifc file:

```
>>> import ifcopenshell
>>> vukas = 'my name is "Vukas"'
>>> ifc = ifcopenshell.file()
>>> test = ifc.create_entity("IfcLabel", vukas)
>>> test
IfcLabel('my name is "Vukas"')
```

**Comment by aothms** [comment]
Only ' needs to be escaped in an IFC string literal. Can you explain exactly the issue? Also note that the string representation you see in your session is not the same as what's written to file. E.g casing is different (and perhaps also escaping of quotes).

**Comment by vulevukusej** [comment]
It appears you're correct :).  I tested this with a small file and it worked, so I guess something else was causing me issues.  Thanks anyway!
