### ISSUE TITLE
Error Booleanoperation -> Wall missing 

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#1948]
Hi,

the Appended IFC from Archicad ist not working correctly.
The composite wall should be high like the windows.

![image](https://user-images.githubusercontent.com/1086380/146564357-9f43c82b-5fae-4bdb-9797-c7f254378950.png)

What happens here? I tried it with 0.7.0 Branch with OpenCascade 7.5.3

[test.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/7735959/test.zip)

**Comment by aothms** [comment]
I had slightly different output. But also wrong.

It's the old problem again of overlapping faces. Frankly I thought OCCT got quite good at handling those, not sure where this is different.

In the end I decided to implement the oldest trick in the book: when possible process the boolean in 2D. (Collapse to 2d face when possible, boolean in 2D, extrude).

Some todo's:
- now only local Y is checked as extrusion direction, that only works for walls
- for non-overlapping inner and outer bounds, BRepBuilderAPI_MakeFace should be even faster
- check performance improvement, but also measure the overhead for the 2D checks when 3D is used

I also did a bunch of other fixes related to booleans.

https://github.com/IfcOpenShell/IfcOpenShell/commit/03d4782cb79d38d1d5cf99d7793e2f0dd4ec7d31
https://github.com/IfcOpenShell/IfcOpenShell/commit/bd008bdefe20ff80abff002c9366fadcb685f0cb
https://github.com/IfcOpenShell/IfcOpenShell/commit/e9bb70f56b599db7158fcf687da696486059bcb2
https://github.com/IfcOpenShell/IfcOpenShell/commit/09631e9565334ce3f55bca3ec8982917d59b5c86
https://github.com/IfcOpenShell/IfcOpenShell/commit/6b0b64b869ca2635f69781e86b2f60d4a0567d49
https://github.com/IfcOpenShell/IfcOpenShell/commit/20dcb68009519934c0c84beeee77a7e3c5b6cc84

**Comment by ninichki** [comment]
Oh perfect, at the first regard it's working fine, now.

Thanks

**Comment by Moult** [comment]
This can be closed as fixed?

**Comment by ninichki** [comment]
Hi, thank's for your work

But the second Layer of the wall is not realy correct:

![image](https://user-images.githubusercontent.com/1086380/149780686-2786d41b-fac3-47c0-b983-d368382c93a0.png)

Maybe, you know, what's the reason.

In Solibri it looks like this;

![image](https://user-images.githubusercontent.com/1086380/149780842-733e7ffe-00c2-41de-8f8b-7f0a17ce7112.png)

**Comment by Moult** [comment]
Reopening and ping @aothms

**Comment by Moult** [comment]
@aothms perhaps this should be added to the list of unit tests ping @johanrd ?

**Comment by aothms** [comment]
> ping johanrd ?

He moved to a new position somewhere free of the pain and suffering of IFC. He can't actively contribute to ifcopenshell anymore.

The procedure to enrich files with geometric validation quantities so that files effectively become unit tests is documented here https://github.com/IfcOpenShell/files#file-name-conventions

It'd be great if we can find someone to pillage the recent issues and uplift them to unit tests. Not just this one.

**Comment by Moult** [comment]
Ah ok. What about @johltn (sorry I may have mixed up the Johans!) who is setting up the test runner things for Epic Games?

**Comment by ninichki** [comment]
Hi @aothms, thank's for your fast reaction,

now it's a little bit strange:

The openings are too big or small:
![image](https://user-images.githubusercontent.com/1086380/150754820-8ef2b28c-032a-4eb2-b9a2-fca04bed4242.png)

In Solibri:
![image](https://user-images.githubusercontent.com/1086380/150755180-e4c0cca5-e062-420e-91e4-a5dca3529c8c.png)

You know what's the reason for that?

**Comment by aothms** [comment]
I don't get a result like that. What's the exact details of your platform (os, compiler) and occ version?

![afbeelding](https://user-images.githubusercontent.com/1096535/150757805-4befb3ad-4162-4fab-ac59-6ef7b4d26b0c.png)

**Comment by ninichki** [comment]
Ok, thank's i'll will take a look. Maybe merging got an error

**Comment by johltn** [comment]
I made a PR to add the files https://github.com/IfcOpenShell/files/pull/3

**Comment by ninichki** [comment]
Ok, for me is everything for this wall ok, now.
Thanks

**Comment by Moult** [comment]
Closing as fixed.
