### ISSUE TITLE
BlenderBIM: IfcOpeningStandardCase not working with "Add opening command"

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#1951]
Hi guys,

To create an opening, it seems that the addon has a problem with openings of type IfcOpeningStandardCase. It works fine with IfcOpeningElement.

As a reminder, here is the procedure to create an opening:
1. Create the element of type IfcOpeningElement and position it correctly.
2. Select the created element and the element receiving the opening (a wall for example).
3. Go to the menu ObjectProperties --> IfcVoids
4. Click on "Add Opening".

Warning. It seems that the NetSideArea value of the walls is not updated. The opening areas are not removed from the total area.

Thank you to all the developper. The addon is always better!
Merry Christmas to all of you!

ps: I use blender 3.0.0 and blenderBIM 0.0.211203

**Comment by Moult** [comment]
Indeed https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/model/wall.py#L870

**Comment by Moult** [comment]
Very sorry for the delay, this must've slipped my todo list.
