### ISSUE TITLE
BlenderBIM: NetSideArea of walls or slabs is not reduced by the area of openings

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#1952]
Hi guys,

The areas of the wall or slab elements are not reduced by the areas of the opening type elements.

thx.

**Comment by Moult** [comment]
Indeed https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/model/wall.py#L870

**Comment by vuicBABS** [comment]
Hi Dion
Now it works with the wall but not with the slabs.
thank you in advance

**Comment by vulevukusej** [comment]
@vuicBABS hey there, i recently added a bunch of new qto formulas, maybe they can help?  Let me know what exactly you're trying to calculate and I'll point you to the right qto

**Comment by vuicBABS** [comment]
![image](https://user-images.githubusercontent.com/40517234/193257514-dc89f5ce-c835-423b-9c4e-2e2a18fdb026.png)
thank you for your comment.
Qto_SlabBaseQuantities are are correct when the slabs have no openings. Once I place an opening (see image), the quantities are set to zero, except for the thickness and perimeter.
I think the code was adapted for walls but not for the other elements like the slabs (or maybe beams, columns, ...)

**Comment by vulevukusej** [comment]
@vuicBABS can you share the file, or even just the slab element?  I'd like to have a look.  I recently added a bunch of new qto's which you might find interesting: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/pset/qto_calculator.py

**Comment by vuicBABS** [comment]
[modele 3.blend.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9684178/modele.3.blend.zip)

**Comment by vulevukusej** [comment]
@vuicBABS the quantities work fine after clicking on "guess quantities": 
![image](https://user-images.githubusercontent.com/83825269/193294810-83290530-6639-4c4c-bd65-1f553b662fb0.png)

You could also use some of the new qto methods, which allow you to account for openings:
```
import bpy
from blenderbim.bim.module.pset.qto_calculator import QtoCalculator

qto = QtoCalculator()
o = bpy.context.active_object

print(qto.get_net_top_area(o, angle=45, ignore_internal=False))
print(qto.get_gross_top_area(o, angle=45))
```

This yields results of 169.0 and 172.0 respectively.

**Comment by vuicBABS** [comment]
Thank you Vukas. It works almost well. Your code works perfect but take a look on the picture. GrossArea = NetArea and I have an opening of 3m2. Your calculator shows the right answer but not the UI.
And it would be great to have the same for the volume. I try to play with the IfcItemCost and it's important to have the right volume too.
Thank you for your help. This addon is very cool!

**Comment by vuicBABS** [comment]
Without opening I have 8 fields.
![image](https://user-images.githubusercontent.com/40517234/193318617-29753cfa-397f-4754-9dd3-7ef46444befe.png)

With an opening I only have 6 fields and the information are set to 0.
![image](https://user-images.githubusercontent.com/40517234/193318934-6bdfb75b-6783-4291-9e9e-bf1e369a887c.png)

After trying the guess quantities the addon guess wrong. But you are right the new methods do the job. I'm patient. And I'll wait it arrives in the UI.
For the moment we don't use blender in production but the time will arrive.

thank you for your responses.

**Comment by Moult** [comment]
The guess quantities was a very old, basic heuristic driven method. I think the next step would be for someone (@vulevukusej ?) to start mapping the list of buildingSMART Qtos to his new Qto calculator methods, that way the BlenderBIM Add-on will be able to auto calculated them (or manually, via UI button) correctly for any entity.

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/alphabeticalorder-quantity-sets.htm there's 93 qsets in total :)

**Comment by Moult** [comment]
Thanks to the huge work done by @maxfb87  @vulevukusej  this is now solved :)

**Comment by maxfb87** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/issues/2533
