### ISSUE TITLE
BlenderBIM: Suggestion: Support for IFC2X3 for 4D/5D capabilities

### ISSUE THREAD

**Issue by garylzimmer** [IfcOpenShell/IfcOpenShell#1956]
After feedback from my issue here
https://github.com/IfcOpenShell/IfcOpenShell/issues/1954

I decided to break this into it's own issue to be tracked separately.

Since proper support might not be possible due to a lack of 4D/5D parameters in the IFC2X3 spec, a first goal could be to have an option in the importing function to auto-run the upgrade recipe to migrate to IFC4 format.

**Comment by garylzimmer** [comment]
Also, if there was a way to see what version IFC spec the file is using before committing to the importing, that would also be helpful

**Comment by Moult** [comment]
Sorry, would you mind adding your suggestion for IFC schema data prior to importing in another issue? Just trying to stem the flood of reports :)

**Comment by aothms** [comment]
> Also, if there was a way to see what version IFC spec the file is using before committing to the importing, that would also be helpful

~~~
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> f.schema
'IFC4'
~~~

**Comment by garylzimmer** [comment]
@aothms Thanks for that! I'm still exploring the ifcOpenShell scripts, they seem very useful! Does blender provide a way to incorporate that kind of functionality into the import dialog box?

**Comment by Moult** [comment]
Prior to building the interface for this, you can use @aothms 's snippet, but you might want to do `f = ifcopenshell.open('/path/to/file.ifc')` instead.

The thing about putting this in the UI is that it may result in reading the file, which we don't want since a 300mb file can easily be quite a while to read. Perhaps to implement this efficiently we need to first grab the first N bytes to cover the header, then just parse the SPF header and nothing else... but that will break for other serialisations. Not sure.

**Comment by garylzimmer** [comment]
@Moult Sorry about blowing up your inbox, I just got so excited by the possibilities of an Open Source AEC project that I could contribute to! I'm not sure what else you are looking for as far as the schema data. From your own site:

> The classes available for you to use are different for each IFC version. In general, IFC4 has many more classes, and the upcoming IFC5 will include even more for infrastructure and landscape projects. It is not advisable to use IFC2x3, for the simple reason that it lacks many useful IFC classes.
This tool below lets you type what type of object you have, and it will try and find the right IFC class for you. It will recommend IFC4 classes. We do not encourage the use of IFC2x3 files.

If this is the intent, why not add a pop-up window after importing IFC2x3 file that would suggest you run the upgrade recipe to IFC4, give a few reasons as to why it should be done, and make it as simple as a button press?

This seems like a good first step in supporting IFC2x3 and encouraging adoption of the newer standard.

**Comment by aothms** [comment]
> Perhaps to implement this efficiently we need to first grab the first N bytes to cover the header, then just parse the SPF header and nothing else... but that will break for other serialisations. Not sure.

In C++ we have this https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcParse.cpp#L1468-L1492

We just need to break out initialize_() into two parts and create maybe a global function like `std::string read_schema(const std::string& filename)` for convenience. It would be automatically available in python. As you know I don't really care about other serializations. The question from @garylzimmer still stands though is it actually useful?

> Does blender provide a way to incorporate that kind of functionality into the import dialog box?

**Comment by Moult** [comment]
Thanks for your suggestion @garylzimmer ! Thanks to @Gorgious56 's new feature (https://github.com/IfcOpenShell/IfcOpenShell/pull/1980) now there is a button you can upgrade to IFC4 if it comes across an IFC2X3 file.
