### ISSUE TITLE
BlenderBIM: Suggestion: Implement Progress Bar or Open Debug Log on Any Import/Export/Conversion Task

### ISSUE THREAD

**Issue by garylzimmer** [IfcOpenShell/IfcOpenShell#1957]
My production IFC files are easily >1GB and importing or converting them takes a significant amount of time. Ideally I would like any sort of feedback from Blender as to if the process is on-going or what it is doing. I hate just seeing the window half-frozen with the waiting cursor!

**Comment by garylzimmer** [comment]
Never contributed to a project of this scope and activity level before! Is it okay if I leave this helpful snippet here?
https://blender.stackexchange.com/questions/1050/blender-ui-multithreading-progressbar

**Comment by Moult** [comment]
If you toggle the system console in Blender (or in Linux, just open from a console) you should see some basic logs being shown during import.

Also, are you sure you don't see a black box with some numbers (which represent percentage loaded) where your cursor is?

**Comment by garylzimmer** [comment]
![image](https://user-images.githubusercontent.com/10817594/148103820-6a841edf-3102-409d-a042-e74fc16faa77.png)
To give you an idea of my usual experience importing. This screen has been sitting like this for at least 5 minutes with no change. The IFC4 file was exported from Revit 2019 and is about ~300MB

**Comment by Moult** [comment]
Good that the debug log can show, as for the progress indicator, maybe when Windows makes the screen not responding, the indicator no longer shows? Not sure, and unfortunately not much I can do about it since progress indicators is handled by Blender upstream. Let me get back to you to see if I can recreate this on Windows.

**Comment by Moult** [comment]
@Gorgious56 do you experience spinning wheels / Blender not showing the progress bar updating on Windows when loading a big IFC model?

**Comment by Gorgious56** [comment]
I don't have ifc files that size to test it with but I think it's a Blender related problem I'm not sure an add-on can solve. I think it's the geometry processing time that blocks the interface, there has been some improvements in this regard in the last versions though.

One could use the widget that goes from 0 to 100 in the interface (I think it's used in the obj importer) but in my experience it freezes and bugs out after some time, too.

**Comment by Moult** [comment]
Actually re-reading this it seems as though everything did behave as expected - just that the particular model @garylzimmer tested with happened to have some heavy objects in the final 90% that made it seem to freeze (maybe he should enable native meshes in the advanced mode and that might solve it).

We already use the cursor that goes from 0 -> 100 but given enough time on Windows, it'll freeze and so you'll need to rely on the console. That's just how Blender deals with it, not something we can control.

So not sure if there is any reasonable task to achieve here - we've already done what we can.
