### ISSUE TITLE
BlenderBIM: Suggestion: Update website to suggest other helpful Open Source plugins in the A/E/C space for Blender

### ISSUE THREAD

**Issue by garylzimmer** [IfcOpenShell/IfcOpenShell#1958]
Some suggestions pulled from here:
https://wiki.osarch.org/index.php?title=AEC_Free_Software_directory#OpenBIM_Management

We could do some testing and give a list of what plugins work out of the box with BlenderBIM and might be suggested

https://blender-archipack.gumroad.com/l/nQVcS
^Entire reason for this suggestion, this plug in IS CRUCIAL in migrating from proprietary CAD software!
(Demo here: https://www.youtube.com/watch?v=TWEoZghkalc)

https://github.com/s-leger/archipack/wiki
https://speckle.systems/tag/blender/
https://github.com/domlysz/BlenderGIS
https://www.zammedev.com/home/wip_projects/blender2godot
https://blendermarket.com/products/pcv
https://creativedesigner3d.com/blender-add-ons/
https://github.com/kevancress/MeasureIt_ARCH/releases
https://aachman98.itch.io/sorcar

**Comment by Moult** [comment]
I believe some of these are already listed on this page: https://blenderbim.org/download.html - however, there is currently a redesign happening for the IfcOpenShell and BlenderBIM Add-on websites, so I'll be sure to mention this bugreport when the time comes to redesign this page.

If you're a webdev hacker, maybe you could help chip in?
