### ISSUE TITLE
message "wire not closed --> stop split" out of place? 

### ISSUE THREAD

**Issue by iras** [IfcOpenShell/IfcOpenShell#196]
Hi,

I've just observed a couple of IFC files which reported this error next to the progress bar.

`[########################################          ]wire not closed --> stop split `

The conversion seems to complete and report the usual error breakdown at the end but I'm left wondering whether 'wire not closed --> stop split' is just an out-of-place message or if the conversion actually stopped because of the unclosed wire. Any ideas?

**Comment by aothms** [comment]
These are messages from opencascade. I thought with more recent versions they had removed most of the direct writing to stdout. The message seems to originate from [1]. But I would have thought `OCCT_DEBUG` not to be defined on production build. Seems it relates to a face with a boundary not being closed. Perhaps a flaw in the model that would go unnoticed in other viewers.

I would be interested to know more, perhaps we can identify this situation earlier and provide a more meaningful error message.

[1] https://github.com/tpaviot/oce/blob/bf969787b6e4ee81612d42e10d0e3f1633ed6b7b/src/ShapeFix/ShapeFix_Face.cxx#L2430

**Comment by iras** [comment]
Thanks @aothms!

Yes, it is _very probably_ related to an old opencascade dependency a more recent build of IfcOpenShell is relying on. I closed the issue.
