### ISSUE TITLE
2D Boolean improvements

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#1960]
See https://github.com/IfcOpenShell/IfcOpenShell/issues/1948 we now have the possibility to process boolean operations in 2D. But the code is still a bit experimental and we need to be better understand the advantages and disadvantages.

- now only local Y is checked as extrusion direction, that only works for walls
- for non-overlapping inner and outer bounds, BRepBuilderAPI_MakeFace should be even faster
- check performance improvement, but also measure the overhead for the 2D checks when 3D is used
- make configurable

**Comment by Moult** [comment]
I didn't see any options to enable/disable this "new" boolean mode, or does it happen automagically?

**Comment by aothms** [comment]
Currently automagically, but yes, it should be configurable. I'll add it to the list

**Comment by aothms** [comment]
> check performance improvement, but also measure the overhead for the 2D checks when 3D is used

https://github.com/IfcOpenShell/IfcOpenShell/issues/1973

**Comment by aothms** [comment]
## Results

| file                                           |           |   --no-2d-boolean |
|------------------------------------------------|-----------|-------------------|
| wall-openings-non-intersecting-rect-circle.ifc | 0.0521031 |         0.155463  |
| wall-openings-intersecting-inner-bounds.ifc    | 0.240754  |         0.860764  |
| wall-openings-intersecting-with-outer.ifc      | 0.203969  |         0.441404  |
| wall-openings-recesses.ifc                     | 0.217648  |         0.20261   |
| wall-openings-non-orthogonal.ifc               | 0.196422  |         0.197255  |
| wall-openings-contained-in-other.ifc           | 0.037811  |         0.109311  |
| wall-openings-outside-of-outer.ifc             | 0.0344232 |         0.0914762 |
| wall-openings-touching-outer.ifc               | 0.0444514 |         0.0858948 |

wall-openings-non-intersecting-rect-circle.ifc

![1](https://user-images.githubusercontent.com/1096535/148688220-b928ad78-930e-4b7b-852d-329a9db1b475.png)

wall-openings-intersecting-inner-bounds.ifc

![2](https://user-images.githubusercontent.com/1096535/148688222-3dccba0b-24fb-415d-861e-463fca5826c3.png)

wall-openings-intersecting-with-outer.ifc

![3](https://user-images.githubusercontent.com/1096535/148688223-ce06ec80-5f71-49a9-a76c-07fc024d822b.png)

wall-openings-recesses.ifc

![4](https://user-images.githubusercontent.com/1096535/148688224-6adb8fd4-5182-4b05-93d4-a0d5ce1e8ed0.png)

wall-openings-non-orthogonal.ifc

![5](https://user-images.githubusercontent.com/1096535/148688225-3c0040f9-ce38-4ca0-b4da-a32ddb10ea49.png)

### checks

For all cases the detailed log messages are captured to ensure the correct code path is followed.

File | Message | Occurences
-----|---------|-----------
1 | "Processed fully in 2D"                                | 1
2 | "Intersecting boundaries"                              | 1
3 | "Intersecting boundaries"                              | 1
4 | "No second operands can be processed as 2D inner bounds" | 1
4 | "Operand B creates a through hole"                     | 0
5 | "Operand B 1/6 is an extrusion"                        | 0
6 | "Subtraction operand contained in other"                | 1
6 | "Subtraction operand outside of outer bound"           | 0
8 | "Intersecting boundaries"                               | 1

**Comment by Moult** [comment]
Super awesome! 2-3x the speed boost!

**Comment by Moult** [comment]
Closing as nothing more seems to be done here, but it's awesome!
