### ISSUE TITLE
ifc.add(element) with style/color for creating a new ifc from an old one

### ISSUE THREAD

**Issue by AlonSpinner** [IfcOpenShell/IfcOpenShell#1962]
Hi Thomas,

I have been learning how to size down IFC files by story level.
The problem I have is that when I try to visualize the new IFC, it shows without any color.
I tried adding the color elements but it did not change the outcome.

below is a short clip of the code that does create a new IFC file with only the elements of the first floor.

Thanks,
Alon
```
import ifcopenshell, ifcopenshell.geom
from ifcopenshell.util.selector import Selector

ifcPath="../data/Duplex_A.ifc"
ifc = ifcopenshell.open(ifcPath)

selector = Selector()
elements = selector.parse(ifc, '@ #1xS3BCk291UvhgP2dvNMKI | .IfcColourRgb') #elements in Level 1

ifcNew = ifcopenshell.file(schema=ifc.schema)
ifcNew.add(ifc.by_type("IfcProject")[0]) 
for element in elements:
    ifcNew.add(element)
ifcNew.write('ifcNew_Duplex_A.ifc')
```

**Comment by Moult** [comment]
Using "add" is not sufficient because it misses a lot of data from inverse relationships. The appropriate method would be to use the IfcOpenShell API "append_asset" function https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/api/project/append_asset.py which unfortunately currently is only designed for assets (types, materials, etc) not occurrences, but the code could be improved.

Would you be interested in helping add that function?

**Comment by aothms** [comment]
There is also the ExtractElements recipe that is relevant.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcpatch/ifcpatch/recipes/ExtractElements.py#L51-L63

At least that one considers openings, but at the very least to have consistent geometrical output, one also needs to traverse the material associations (`element.HasAssociations`) and the geometric item styles `([i.StyledByItem for i in ifc.traverse(element) if i.is_a("IfcGeometricRepresentationItem"))`.

Note that for `element.HasAssociations` the IfcRelAssociatesMaterial is actually a 1-to-many relationship, so adding it blindly to the file will also add the other elements that are referenced in the relationship. So better recreate it with `ifcNew.createIfcRelAssociatesMaterial()` and providing the appropriate subset for `RelatedObjects`.

Unfortunately nothing is simple in IFC ;) but I agree with @Moult we should finally provide a good API for this common task so any help is welcome here :)

**Comment by AlonSpinner** [comment]
I had a little trouble getting my head around your posts.
Unfortunately, I have my hands full, so I'll look for a bypass on this current problem, but I intend to use ifcopenshell extensively in my research, so hopefully when time goes by this looks achievable, and then I'll be glad to contribute :)

**Comment by Moult** [comment]
@AlonSpinner decided to hack on this one today and now you can do this and effectively use your old IFC as a library:

```python
ifcopenshell.api.run("project.append_asset", new_ifc, library=old_ifc, element=element)
```

If you want, you can also use the ExtractElement IfcPatch recipe which will also kindly replicate the relevant spatial hierarchy for you too.

```
$ ifcpatch -i input.ifc -o output.ifc -r ExtractElements -a ".IfcWall"
```

**Comment by AlonSpinner** [comment]
Nice!
Thanks! :)
