### ISSUE TITLE
ImportError: IfcOpenShell not built for 'windows\64bit\python3.7'

### ISSUE THREAD

**Issue by iammix** [IfcOpenShell/IfcOpenShell#1965]
Hello community,

I create a new environment with conda and I tried to install ifcopenshell using the commands from https://anaconda.org/conda-forge/ifcopenshell

However, when I try to run a source code that I have it raises the following error:

**ImportError: IfcOpenShell not built for 'windows\64bit\python3.7'**

I tried also python3.8 and python3.9. Always the same problem occurs.

Thanks in advance.

**Comment by iammix** [comment]
Update: The problem occurs when I try to run the code from PyCharm IDE.
Executing the source code from the terminal works fine.

**Comment by aothms** [comment]
> Update: The problem occurs when I try to run the code from PyCharm IDE.
> Executing the source code from the terminal works fine.

So are you sure then the interpreter used by PyCharm is what you think it is and all these things below print expected values:

~~~
import os
import sys

if hasattr(os, "uname"):
    platform_system = os.uname()[0].lower()
else:
    platform_system = "windows"

if sys.maxsize == (1 << 31) - 1:
    platform_architecture = "32bit"
else:
    platform_architecture = "64bit"

python_version_tuple = tuple(sys.version.split(" ")[0].split("."))

print(sys.executable, platform_system, platform_architecture, *python_version_tuple)
~~~

**Comment by iammix** [comment]
Yes, the sys.executable prints out the correct location of the python interpreter, and all the other variables are correct too.

**Comment by iammix** [comment]
@aothms I found what's going on.
It is PyCharm's [issue](https://youtrack.jetbrains.com/issue/PY-35141?_ga=2.178982372.1743129298.1641541567-1374306226.1638798029). In short, if your Anaconda directory is different than C:\users\<username>\anaconda3 there are some problems that can be raised.

**Comment by aothms** [comment]
Ah happy that you figured it out 👍
