### ISSUE TITLE
ifcopenshell.util.element get_quantities doesn't work

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#1967]
Hi guys,

I have a problem with the ifcopenshell.util.element. Here is the message:

AttributeError                            Traceback (most recent call last)
<ipython-input-12-b735ad27113f> in <module>
      1 #En utilisant la fonction get_psets de ifcopenshell.util.element
----> 2 print(iue.get_quantities(bd0))

~\Anaconda3\lib\site-packages\ifcopenshell\util\element.py in get_quantities(quantities)
     36     results = {}
     37     for quantity in quantities:
---> 38         if quantity.is_a('IfcPhysicalSimpleQuantity'):
     39             results[quantity.Name] = quantity[3]
     40     return results

AttributeError: 'str' object has no attribute 'is_a'

**Comment by aothms** [comment]
I assume you're passing it a building element or similar (`bd0`?). That's not what the function is intended for. It's basically only for internal usage in get_property_definition() https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/element.py#L34 

So get_quantities really assumes a list of IfcPhysicalSimpleQuantity. In your case it starts iterating over the building element attributes. First attribute is GlobalId, which is a `str`, hence the error message.

So I think what you wanted was `iue.get_psets(bd0, qtos_only=True)`

These functions are in desperate need of some docstrings to explain their usage. Any help appreciated :)

**Comment by vuicBABS** [comment]
Thank you. It's clear now. I wrote these lines and it does well now:

for definition in bd0.IsDefinedBy:
    if definition.RelatingPropertyDefinition.is_a("IfcQuantitySet"):
        print(iue.get_quantities(definition.RelatingPropertyDefinition.Quantities))
