### ISSUE TITLE
Loading express schemas

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1969]
What am I doing wrong?

```python
$ wget https://github.com/buildingSMART/IFC4.3.x-output/blob/master/IFC.exp
>>> schema = ifcopenshell.express.parse('/path/to/IFC.exp')
>>> ifcopenshell.register_schema(schema)
>>> ifcopenshell.file(schema='IFC4X3_DEV_7036edb')

#! Traceback (most recent call last):
#!   File "<blender_console>", line 1, in <module>
#!   File "/home/dion/.config/blender/3.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 201, in __init__
#!     self.wrapped_data = ifcopenshell_wrapper.file(*args)
#!   File "/home/dion/.config/blender/3.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 4207, in schema_by_name
#!     return _ifcopenshell_wrapper.schema_by_name(arg1)
#! RuntimeError: No schema named IFC4X3_DEV_7036edb
```

**Comment by aothms** [comment]
Fixed, register_schema() registered the name verbatim, whereas get_schema() takes uppercase. So it wasn't able to find it.

Just for completeness sake in case others are reading along:

(a) that URL is the path to the HTML render use below instead:

wget https://raw.githubusercontent.com/buildingSMART/IFC4.3.x-output/master/IFC.exp

(b) the schema name in that repo will change with commit sha over time so use

`schema=schema.schema_name`

**Comment by Moult** [comment]
Thanks! :) And yes sorry about the bad URL.

**Comment by aothms** [comment]
> `schema=schema.schema_name`

I think it should be `schema.schema.name()`
