### ISSUE TITLE
Cannot assign attributes using parsed express schema

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1974]
One step closer... but no cigar :)

```python
>>> import ifcopenshell
>>> f = ifcopenshell.file(schema='IFC4X3_DEV_7036edb')
>>> f
<ifcopenshell.file.file object at 0x7fa600c9cb50>

>>> f.schema
'IFC4X3_DEV_7036edb'

>>> f.create_entity('IfcProject')
#1=IfcProject($,$,$,$,$,$,$,$,$)

>>> f.create_entity('IfcProject', **{'GlobalId': ifcopenshell.guid.new()})
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/3.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 284, in create_entity
    e[idx] = arg
  File "/home/dion/.config/blender/3.0/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 179, in __setitem__
    super(entity_instance, self).__setattr__("method_list", _method_dict[self.is_a(True)])
KeyError: 'IFC4X3_DEV_7036edb.IfcProject'
```

**Comment by aothms** [comment]
Oops, yes that was the new thing optimizing getattr

Should work now.

~~~
>>> import ifcopenshell
>>> import ifcopenshell.express
>>> schema = ifcopenshell.express.parse('IFC.exp')
>>> ifcopenshell.register_schema(schema)
>>> f = ifcopenshell.file(schema=schema.schema.name())
>>> f.createIfcProject(ifcopenshell.guid.new())
#1=IfcProject('2Fv81LdL9BFBrMg19yZuPD',$,$,$,$,$,$,$,$)
~~~

**Comment by aothms** [comment]
Just a word of caution for everybody reading along here. You can't generate geometry off of these schema files. That's only supported for the schemas built in during compilation, because we rely on earlybound definitions in the geometry modules.

**Comment by Moult** [comment]
Hmm, what I'd like to do is start trying to use IFC4.3 to see how much works out of the box and run the existing test suite on it. For example the missing ReferencedByPlacement attribute was an immediate showstopper because it broke coordinate updating. But if geometry doesn't work, then how would I test it? (because I need to patch the express in case I run across other showstopper bugs like ReferencedByPlacement)

**Comment by aothms** [comment]
Well I guess most of the tests don't depend on ifcopenshell.geom? It'd be a nice starting point?

We had this supposedly easy way of compiling in support for a specific schema using cmake, but it hasn't been tested for years https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/cmake/CMakeLists.txt#L585-L640

The difficult thing is that in C++ we still don't have a good way to loop over defined schemas at compile time. So the list of schemas is essentially hardcoded. So you can use the CMake trick to replace an existing schema at best at the moment.

It's a great effort, let me know how I can help.

**Comment by Moult** [comment]
8 failed, 300 passed in 2.38s :)

The 8 failures (apart from the obligatory "create file" error, because I overrode the default schema to be IFC4X3_RC4), are all the same error:

```
E           AttributeError: entity instance of type 'IFC4X3_RC4.IfcLocalPlacement' has no attribute 'ReferencedByPlacements'
```

It would be nice if there could be a hotfix to patch just that one error. If so, then I could run another several hundred tests which do more complex authoring actions (the unit tests for IfcOpenShell's API after all are pretty specific).

What I could also do, if that were patched, is to offer IFC4X3_RC4 as a public release for users to start trying to break.

Promising start!

**Comment by Moult** [comment]
How would I get that fix in IfcOpenShell such that IFC4X3_RC4 has the ReferencedByPlacements attribute?

**Comment by aothms** [comment]
Download the express and rename the schema id to IFC4X3_RC4 then invoke the code generation [0] and move (replace) the generated .cpp and .h into the src/ifcparse folder. Then rebuild IfcOpenShell.

[0] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/express/README.md#command-line-usage-for-code-generation

**Comment by Moult** [comment]
Assuming the latest schema (to be ISO) is IFC4X3, I've now rerun the tests and there are 5 errors but all errors make sense and just need a few tweaks to support IFC4X3 :)

```
FAILED test/test_file.py::TestFile::test_creating_a_new_file - AssertionError: assert 'IFC4X3' == 'IFC4'
FAILED test/api/project/test_create_file.py::TestCreateFile::test_run - AssertionError: assert 'IFC4X3' == 'IFC4'
FAILED test/api/root/test_create_entity.py::TestCreateEntity::test_handling_predefined_types - AssertionError: assert None == 'NOTDEFINED'
FAILED test/api/root/test_create_entity.py::TestCreateEntity::test_setting_default_values_for_validity - RuntimeError: Entity with name 'IfcDoorStyle' not found in schema 'IFC4X3'
FAILED test/api/sequence/test_edit_task_time.py::TestEditTaskTime::test_editing_a_start_date_and_duration_with_a_calendar - AttributeError: entity instance of type 'IFC4X3.IfcWorkTime' has no attribute 'Start'
```

So pretty awesome!

**Comment by Moult** [comment]
Actually which is the latest? IFC4X3 or IFC4X3_TC1?

**Comment by aothms** [comment]
IFC4X3_ADD1, needs a fairly recent ifopsh build

**Comment by Moult** [comment]
Cheers, all seems to be good then :)
