### ISSUE TITLE
BlenderBim 220110 cannot be activated in Blender

### ISSUE THREAD

**Issue by Asgatlat** [IfcOpenShell/IfcOpenShell#1977]
hi,
i get this error when i try to activate blenderbim-220110-py39-win plugin in Blender3.0  
![image](https://user-images.githubusercontent.com/86599367/148767724-ea833669-30cd-43b3-96e3-be09dec9ab91.png)

**Comment by Moult** [comment]
@Asgatlat sorry we are still waiting for the next bot build to be ready after the holiday break (ping @aothms) until that happens. the daily builds won't be usable.

**Comment by benjamindahl** [comment]
Is it possible to get a version of blenderbim that works with apple silicon and blender 3.0, too? 

cheers
b

**Comment by Moult** [comment]
@benjamindahl see #1702

**Comment by Moult** [comment]
Closing as next build should have the latest IfcOpenShell module :)
