### ISSUE TITLE
The UI panel bike shed bug :)

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1981]
So I tried out the new panel + subpanel system today. Like the new direction! Some very minor meaningless comments:

 - Shorter titles. Sometimes Blender is on lower resolution screens and names get cut off. "IFC Collaboration and Data Exchange" could just be "IFC Collaboration" for example.
 - I'd prefer panels to disappear when not applicable such as before an IFC project exists. Otherwise it pollutes Vanilla Blender.
 - Would prefer the "IFC Project Setup" to panel to be open by default. It is the most important panel to be visible to newcomers and the first thing you look for.
 - Similarly would prefer the IFC Object attributes to be open by default as well as ordered first. On my machine "IFC Geometry and Spatial Structure" is ordered first which feels weird since the IFC Class is usually the first thing you look for.
 - IFC Systems not be under IFC utilities. It should be in its own top level panel for IFC Services (mech, elec, hyd, fire, comms)

Very low priority and feel free to disagree, you've been using the new layout longer than I have :)

**Comment by vulevukusej** [comment]
some nice points!

**Comment by Moult** [comment]
As mentioned by cadgiru in the chat BIMTester should be in the scene properties not object properties.

**Comment by Moult** [comment]
The IFC Representations panel seems to have disappeared... it's usually under object properties. Any ideas?

**Comment by vulevukusej** [comment]
@Moult - It's landed under scene properties - IFC Geometry and Spatial Structure.  I'll make a commit today to fix + above points.

**Comment by Moult** [comment]
Closing as no more big issues are jumping out at me. If something does crop up in everyday usage we can deal with it then :)
