### ISSUE TITLE
Dynamic tooltips for attribute and property descriptions

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1982]
Here's a fun challenge if someone is up to it. It would be nice to have tooltips which annotate various things in IFC. There's two challenges to this: 1) getting the descriptions to use for tooltips, and 2) doing dynamic tooltips in Blender.

For the second, @Gorgious56 has done some sleuthing and this reregistration seems to be the way to go: https://community.osarch.org/discussion/comment/9204/#Comment_9204

For getting the tooltips, I wrote this little script a while back which scrapes the downloaded HTML docs from technical.buildingsmart.org. It's annoying we have to do this, but buildingSMART doesn't give these descriptions in any other parsable way.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/extract.py

I also produced https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/schema/entity_descriptions.json and https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/schema/enum_descriptions.json somehow from somewhere.

Property descriptions can be extracted from pset template definitions.

**Comment by vulevukusej** [comment]
This does sound like fun - If nobody makes a start on this before Feb I'll gladly look into it!

**Comment by aothms** [comment]
> but buildingSMART doesn't give these descriptions in any other parsable way.

(a) Best would be to use the translation files https://github.com/buildingSMART/IFC4.3.x-output/blob/master/IfcActorResource.pot#L17-L18 That's what they are intended for after all :) and you'll even get i18n tooltips once the translation team gets going.

(b) Alternatively there is markdown https://github.com/buildingSMART/IFC4.3.x-development/blob/master/docs/schemas/shared/IfcSharedBldgElements/Entities/IfcWall.md

You can use this code to parse the attribute definitions according to the heading convention https://github.com/buildingSMART/IFC4.3.x-development/blob/master/code/md.py

It's a different version of the schema, but I think it's better to use this than scraping the HTML.

(c) If you insist on having the correct schema I would look at the IFC doc repo which has tags/branches for all current schemas https://github.com/buildingSMART/IFC/blob/Ifc4.0.2.2/Sections/Shared%20element%20data%20schemas/Schemas/IfcSharedBldgElements/Entities/IfcWall/Documentation.md

**Comment by Moult** [comment]
Ah nice! Good to see things will be easier in IFC4.3. In IFC4 / IFC2X3 I didn't know there was the IFC doc repo, I'll be sure to check it out.

So maybe that extract.py script needs to be written to instead scrape the doc repository :)

**Comment by DuncanLithgow** [comment]
This would be so great for IFC education and understanding. I know it would help me 😄

**Comment by vulevukusej** [comment]
> (a) Best would be to use the translation files https://github.com/buildingSMART/IFC4.3.x-output/blob/master/IfcActorResource.pot#L17-L18 That's what they are intended for after all :) and you'll even get i18n tooltips once the translation team gets going.

I'll give this a shot. Never seen or parsed a .pot file before - some quick googling led me to the gettext python module - Am I roughly on the right track with using that? 

@Moult - I wasn't being courteous by waiting until Feb 😄, I just need to find the time somewhere

**Comment by Moult** [comment]
@vulevukusej I've never parsed it either but yes gettext sounds likely.

**Comment by Gorgious56** [comment]
I'd like to explore another idea in concurrency, because all in all I'm not a fan of either hacking a re-registration at runtime and the fact that tooltips are limited in terms of UX. For attributes or classes that need a little more information than what can be contained in a single sentence. 

How about adding a question mark button next to the attribute fields, that the user would click to learn more about it ? It would open a popup window. It could contain information formatted as we see fit, it could be filled in at the time the attribute is created and never changed afterwards. We could add an ifc class inheritance hierarchy, links to the docs, possible usecases, default values, synonyms, etc.

Of course we would still need to parse the docs and it looks like this is where the bulk of the work for this feature proposal will go to.

Cheers

**Comment by Moult** [comment]
Definitely - can you think of a solution that won't litter the UI with "?" icons everywhere? Or maybe we have a "Disable help" mode for advanced users in the add-on settings? Would love to see a mockup.

**Comment by Gorgious56** [comment]
Yep good point a simple option in preferences to enable or disable "newbie mode" would do it I think. Just need to elegantly display it in the UI and fetch the relevant information without hiccups. :)

**Comment by Gorgious56** [comment]
I think to prevent having "?" icons everywhere I can leverage the right click > online documentation that's kinda builtin Blender. I'll look into it.

**Comment by Moult** [comment]
Good idea! @Andrej730 is off sick right now but he's in the middle of extracting predefined types docs so that would help provide some closure to this feature too :)

**Comment by Gorgious56** [comment]
Sounds good ! Just posting these for reference :

https://blender.stackexchange.com/questions/27071/add-manual-and-python-reference-links-for-custom-operators
https://docs.blender.org/api/current/bpy.utils.html?highlight=register_manual_map#bpy.utils.register_manual_map
https://blender.stackexchange.com/questions/91377/adding-a-documentation-reference-for-a-custom-object-attribute

Also the builtin python template > Addon Add Object

```
bl_info = {
    "name": "New Object",
    "author": "Your Name Here",
    "version": (1, 0),
    "blender": (2, 80, 0),
    "location": "View3D > Add > Mesh > New Object",
    "description": "Adds a new Mesh Object",
    "warning": "",
    "doc_url": "",
    "category": "Add Mesh",
}


import bpy
from bpy.types import Operator
from bpy.props import FloatVectorProperty
from bpy_extras.object_utils import AddObjectHelper, object_data_add
from mathutils import Vector


def add_object(self, context):
    scale_x = self.scale.x
    scale_y = self.scale.y

    verts = [
        Vector((-1 * scale_x, 1 * scale_y, 0)),
        Vector((1 * scale_x, 1 * scale_y, 0)),
        Vector((1 * scale_x, -1 * scale_y, 0)),
        Vector((-1 * scale_x, -1 * scale_y, 0)),
    ]

    edges = []
    faces = [[0, 1, 2, 3]]

    mesh = bpy.data.meshes.new(name="New Object Mesh")
    mesh.from_pydata(verts, edges, faces)
    # useful for development when the mesh may be invalid.
    # mesh.validate(verbose=True)
    object_data_add(context, mesh, operator=self)


class OBJECT_OT_add_object(Operator, AddObjectHelper):
    """Create a new Mesh Object"""
    bl_idname = "mesh.add_object"
    bl_label = "Add Mesh Object"
    bl_options = {'REGISTER', 'UNDO'}

    scale: FloatVectorProperty(
        name="scale",
        default=(1.0, 1.0, 1.0),
        subtype='TRANSLATION',
        description="scaling",
    )

    def execute(self, context):

        add_object(self, context)

        return {'FINISHED'}


# Registration

def add_object_button(self, context):
    self.layout.operator(
        OBJECT_OT_add_object.bl_idname,
        text="Add Object",
        icon='PLUGIN')


# This allows you to right click on a button and link to documentation
def add_object_manual_map():
    url_manual_prefix = "https://docs.blender.org/manual/en/latest/"
    url_manual_mapping = (
        ("bpy.ops.mesh.add_object", "scene_layout/object/types.html"),
    )
    return url_manual_prefix, url_manual_mapping


def register():
    bpy.utils.register_class(OBJECT_OT_add_object)
    bpy.utils.register_manual_map(add_object_manual_map)
    bpy.types.VIEW3D_MT_mesh_add.append(add_object_button)


def unregister():
    bpy.utils.unregister_class(OBJECT_OT_add_object)
    bpy.utils.unregister_manual_map(add_object_manual_map)
    bpy.types.VIEW3D_MT_mesh_add.remove(add_object_button)


if __name__ == "__main__":
    register()
```

**Comment by Moult** [comment]
@Andrej730 has done the new doc function :) https://github.com/IfcOpenShell/IfcOpenShell/commit/f2c2fa8dceeb9ae65ca844d7faa8383b095875a2 possible to swap over to that and purge the old method? (potentially that might also mean purging the now obsolete JSON, I haven't' checked if it's used anywhere else)

**Comment by Gorgious56** [comment]
Nice! I'm on it. JSON is also used there https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/prop.py#L133

**Comment by Moult** [comment]
Ah OK don't purge the Json then I'll need to investigate further about that usage. Almost certain it can be recoded.

**Comment by Gorgious56** [comment]
@Moult How do I get the ifc class from a predefined type attribute ? For example [there](https://github.com/IfcOpenShell/IfcOpenShell/blob/4533b74d65985b1b6d38ae1af4a6096c44b1e011/src/blenderbim/blenderbim/bim/module/root/data.py#L89-L92) I can get `IfcActuatorTypeEnum` from `attribute.type_of_attribute().declared_type().name()` and then remove the last 8 characters to get `IfcActuator` but it's ugly and I'm having trouble finding a clean way to get `IfcActuator` ?

**Comment by Gorgious56** [comment]
![84cb54eb28861d39ba4f7127e3bbd6ef](https://user-images.githubusercontent.com/25156105/198299277-68cc1cba-ab43-48bb-b1cc-9dcfdd774196.jpg)

**Comment by Gorgious56** [comment]
@Moult I've got a new problem, I want to populate the attribute description [there](https://github.com/IfcOpenShell/IfcOpenShell/blob/17a872a8d8595a44dda31bb3210958c2c5715490/src/blenderbim/blenderbim/bim/prop.py#L136-L153) but I don't know how to fetch the ifc class at this point in the code.

**Comment by Moult** [comment]
@Gorgious56 ah looking at it now that only reads from `enum_items`, so the correct approach would be to see where `enum_items` is being populated and populate it there. Sometimes, `enum_items` will contains regular IFC attributes which have descriptions, and at other times it will contain hardcoded data (which we can start adding descriptions to), and at other times it will contain arbitrary user data (which may or may not have descriptions).

**Comment by Moult** [comment]
Feel free to close if fixed @Gorgious56 :)

**Comment by Gorgious56** [comment]
Yes I think this can be closed. 

Cheers !
