### ISSUE TITLE
Stl export doen not include ifc facade correctly (blenderbim)

### ISSUE THREAD

**Issue by GuyMador2022** [IfcOpenShell/IfcOpenShell#1983]
Hello 

when i tried to export stl for cfd use to stl 
the file does not exported with balconies on facade 

the stl is straten. 

i need the blconies to be seen on stl. 

is it a known bug or i configure something wrong ?

**Comment by Moult** [comment]
Have you got a sample file?

I assume you are importing an IFC into Blender, then exporting it to STL using Blender's features?

**Comment by GuyMador2022** [comment]
what do you mean by sample file ? how could i share it ? 

should i upload to google drive and share a link ? 

what files should i share ? 

Thank you, 

guy

**Comment by Moult** [comment]
@GuyMador2022 you'll need to describe the things you are doing step by step as well as supply any files needed to recreate your issue. You are free to share your files any way you wish (note that if on google drive you need to allow public access) or you can share it privately to dion@thinkmoult.com

**Comment by Moult** [comment]
Ping @GuyMador2022 can you please help provide some sample files to recreate this issue or further descriptions of what you are doing?

Will close in one week if no response.

**Comment by Moult** [comment]
Closing due to no response, so unable to understand what the issue is.
