### ISSUE TITLE
Error by enabling Addon blenderbim-220104-py39-win

### ISSUE THREAD

**Issue by kubeczek77** [IfcOpenShell/IfcOpenShell#1984]
Hi,

I wanted to test the IFC Bulk Property Editor but I get an error by enabling developer version Addon ver. 220104-py39-win (installation successful)
My blender version is blender-2.93.7-windows-x64

Can someone tell me why is that? With the official addon installation and enabling I dont have any problems, but there is no Bulk Property Editor there (yet?)

![blender error](https://user-images.githubusercontent.com/97618233/149176409-48a7c83c-63f1-4fa6-a77d-bc868d63b9e9.JPG)

**Comment by Moult** [comment]
Sorry, we're still waiting for the bot to come back from the holidays before we can provide a testing build for users. See #1959.

**Comment by kubeczek77** [comment]
> Sorry, we're still waiting for the bot to come back from the holidays before we can provide a testing build for users. See #1959.

Hi, thank you for the answer. When will it be? Where and how can I check if the testing build is available?

**Comment by Moult** [comment]
Sorry, that is a question for @aothms

**Comment by aothms** [comment]
We need a fix for the issue here https://github.com/IfcOpenShell/IfcOpenShell/issues/1975 (first comment only) as the OSX build also depends on clang so will probably fail without.

**Comment by Moult** [comment]
One step closer! https://github.com/IfcOpenShell/IfcOpenShell/commit/81016f3110df536b43ba16ddd196f56a65a2e390

**Comment by Moult** [comment]
Closing as next build should have the latest IfcOpenShell module :)

**Comment by kubeczek77** [comment]
When und where is the next build to find?

Dion Moult ***@***.***> schrieb am Mi., 19. Jan. 2022, 02:24:

**Comment by Moult** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/releases

**Comment by kubeczek77** [comment]
Hi, thank you for the link. Build from 20.01 has no ifc bulk editor and
build from 21.01 unfortunately bo version for windows. Can it be that in
20.01 there is no bulk editor yet or am I doing sth wrong?
Thanks!

Dion Moult ***@***.***> schrieb am Fr., 21. Jan. 2022, 05:25:

**Comment by kubeczek77** [comment]
Hi, thank you for the link. Build from 20.01 has no ifc bulk editor and
build from 21.01 unfortunately bo version for windows. Can it be that in
20.01 there is no bulk editor yet or am I doing sth wrong?
Thanks!

Dion Moult ***@***.***> schrieb am Do., 13. Jan. 2022, 06:01:

**Comment by Moult** [comment]
You should be able to find the bulk editor in the object properties, below the object property sets.

**Comment by kubeczek77** [comment]
I found it in IFC Utilities. Thank you :)
