### ISSUE TITLE
Strategies to getting adjacent objects

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1985]
I have a series of duct, pipe, and cable segments and fittings. These are geometrically connected, but the connection information via ports and system assignment in IFC does not exist.

I'm wondering if it is possible to derive what's connected to what (directionality doesn't matter) purely using geometric analysis.

I have tried `tree.select_box(element)` and played with various tolerances of extend with only successes in simple models. I've also noticed that sometimes the object placements of these elements are somewhere within the element (like in a fitting), whereas sometimes they are far away. Also, sometimes select_box gives me results back I don't quite expect.

For example, in this screenshot the bright orange selected one has select_box() applied to it, and the dark orange ones are the result. The pipe clamp, fitting, and round penetration object makes sense. But I'm not sure how select_box somehow selected the adjacent pipes which are not touching it at all.

![2022-01-13-163809_474x401_scrot](https://user-images.githubusercontent.com/88302/149272273-fc7f2897-b596-4572-aeb4-bce8ccb5041e.png)

Maybe the select_box can be part of culling a small sample set of objects, then more detailed clash detection can occur? Or any ideas for another approach that might work better?

**Comment by aothms** [comment]
If you can isolate this into a unit test (just the two pipes) I think it'd be a nice case to further investigate.

But yes regardless, select_box() can never be the complete solution.

(a) You can rely on the tree itself and use `select(extend=_some_positive_number_)` that way the occt brep distance algo is used so you get shapes within an exact distance from brep and not bbox

(b) But even then you'll have to classify the connection. In C++ you could create a tree with shape_A faces. Use shape_B faces to select in the tree to get pairs of touching faces. Then sample their normals to see that they are opposite. Classify their shape to see if they are approximately circular or hollow circular. (Possibly use occt normal projection to get exact co-planar faces and do boolean intersection). In Python only the spatial product tree is available, not the generic tree (which is a template class in C++, not easily interfaces), so you'll have to resort on bruteforce to find candidates of touching faces.

**Comment by Moult** [comment]
Hmm, am I doing it right? With select_box I get results, but not with select.

```python
import ifcopenshell
import blenderbim.tool as tool
import multiprocessing

def get_selected():
    return tool.Ifc.get_entity(C.active_object) # returns entity instance from Blender object

def create_tree(tree):
    s = ifcopenshell.geom.settings()
    f = tool.Ifc.get()
    iterator = ifcopenshell.geom.iterator(s, f, multiprocessing.cpu_count(), include=f.by_type('IfcElement'))
    iterator.initialize()
    while True:
        tree.add_element(iterator.get_native())
        shape = iterator.get()
        if not iterator.next():
            break
        
#f = tool.Ifc.get()
#tree = ifcopenshell.geom.tree()
#create_tree(tree)
tree.select(get_selected(), extend=1000) # Returns empty list []
```

**Comment by aothms** [comment]
For me the following script works:

~~~py
import ifcopenshell
import ifcopenshell.geom

import multiprocessing

f = ifcopenshell.open("Duplex_A_20110907_optimized.ifc")
tree = ifcopenshell.geom.tree()


def get_selected():
    return f.by_type("IfcWall")[0]

def create_tree(tree):
    s = ifcopenshell.geom.settings()
    iterator = ifcopenshell.geom.iterator(s, f, multiprocessing.cpu_count(), include=f.by_type('IfcElement'))
    iterator.initialize()
    while True:
        tree.add_element(iterator.get_native())
        shape = iterator.get()
        if not iterator.next():
            break
        
create_tree(tree)
for d in [0.01, 0.1, 1.0, 1000.]:
    print(d, len(tree.select(get_selected(), extend=d)))
~~~

Prints:

~~~
0.01 19
0.1 22
1.0 36
1000.0 208
~~~

so as the distance increases the amount of elements as well.

You can also get the individual element distances btw with tree.distances( ) after calling select().

**Comment by cadgiru** [comment]
Are you looking for a general function, or specifically connected items. For connected MEP items, just an idea... Find they are often organized / grouped by system, so selecting by system might be preferable as opposed to box select?

**Comment by Moult** [comment]
@cadgiru unfortunately though I am looking to connect MEP elements, in this situation all system relationships have been lost. This is a very common problem with Revit. In short, when the consultants finish work, the subcontractors replace ducts, pipes, and cable trays with individual fabrication segments so they can get sheet metal cuts. However, in this process, most of the model is rebuilt, and Revit does not support any of the intelligent system information for these fabrication elements.

This is a huge industry problem - all the work done with months and years of consultants during design phase in smart BIM systems (even that is a nice to have) is lost in the construction phase with fabrication BIM models simply because "Revit doesn't support it". The calcs are done in a spreadsheet elsewhere.

@aothms I tried your code snippet and it works in the Duplex model. However, it doesn't work in my huge model. I extracted a few elements and was able to recreate it. Is this potentially a bug?

```
import ifcopenshell
import ifcopenshell.geom
import blenderbim.tool as tool

import multiprocessing

# Use this if you want to play with the active Blender session IFC
#f = tool.Ifc.get()
f = ifcopenshell.open('/home/dion/mep-test.ifc')
tree = ifcopenshell.geom.tree()


def get_selected():
    return f.by_id(7270)

def create_tree(tree):
    s = ifcopenshell.geom.settings()
    iterator = ifcopenshell.geom.iterator(s, f, multiprocessing.cpu_count(), include=f.by_type('IfcElement'))
    iterator.initialize()
    while True:
        tree.add_element(iterator.get_native())
        shape = iterator.get()
        if not iterator.next():
            break
        
create_tree(tree)
for d in [0.01, 0.1, 1.0, 1000.]:
    print(d, len(tree.select(get_selected(), extend=d)))
```

See attached 
[mep-test.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/7878521/mep-test.txt)

**Comment by aothms** [comment]
Hm indeed, there were a couple of remaining checks that should only have affected extend<0. You could have solved this with setting SEW_SHELLS to true, but it's also fixed in the code now.

**Comment by Moult** [comment]
Fantastic! This method works very well. I was able to trace through various ducts, pipes, through equipment like fans and dampers, and cable trays.

I think if this is combined with some system parameters on the non-fabrication elements (e.g. the actual pumps, fans, and terminals) we can recreate the system topology that is lost during construction stage.

Thanks so much for the quick fix! Closing the bug. An IfcPatch recipe might come out of this!

**Comment by Moult** [comment]
Quick question, it takes a few seconds on some of the more complex situations (flexi pipe, any pumps with funky geometry). I assume this method uses a form of box intersection first to cull the results, so it is already as fast as can be?

**Comment by aothms** [comment]
Yes box selection always goes first https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcGeomTree.h#L215

**Comment by aothms** [comment]
> so it is already as fast as can be?

Probably not though. 

There all sorts of other things that we should experiment with:

* https://dev.opencascade.org/doc/refman/html/class_b_rep_extrema___shape_proximity.html
* https://dev.opencascade.org/doc/occt-7.5.0/refman/html/class_b_v_h___tree.html
* Using the current tree but more granular boxes for faces.

Etc.

But it's not very high on my list. I think the current performance is acceptable but indeed not very competitive.
