### ISSUE TITLE
Issue with running docker container for ifcopenshell using python linux

### ISSUE THREAD

**Issue by rahulkhandepts** [IfcOpenShell/IfcOpenShell#1991]
Hello Team,

I'm trying to build and run docker container with ifcopenshell. I could successfully create docker image but at the time of execution I get error: 
Her is my docker file:
![docker](https://user-images.githubusercontent.com/44163707/149760377-ee3c1e12-48ed-4519-a6b5-d0e9212a6427.png)

FROM python:3.9.5-alpine3.12
#Copy Python 3.9 linux 64 
COPY ./ifcopenshell /ifcopenshell
RUN cp -r /ifcopenshell /usr/local/lib/python3.9/site-packages
COPY ./app /app
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN apk update && apk add --virtual build-deps gcc python3-dev musl-dev && apk add --no-cache mariadb-dev
RUN apk add libc6-compat
RUN apk upgrade musl
#RUN ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2
RUN pip install -r requirements.txt
EXPOSE 80
EXPOSE 5000
ENTRYPOINT [ "python3" ]
CMD [ "main.py" ]

**Comment by rahulkhandepts** [comment]
Team, I did some changes to docker file(highlighted in bold below):

FROM python:3.9.5-alpine3.12
#Copy Python 3.9 linux 64 
COPY ./ifcopenshell /ifcopenshell
RUN cp -r /ifcopenshell /usr/local/lib/python3.9/site-packages
COPY ./app /app
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN apk update && apk add --virtual build-deps gcc python3-dev musl-dev && apk add --no-cache mariadb-dev
RUN apk add libc6-compat
RUN apk upgrade musl
**RUN ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2**
RUN pip install -r requirements.txt
EXPOSE 80
EXPOSE 5000
ENTRYPOINT [ "python3" ]
CMD [ "main.py" ]

Now error is changed. Here is the snapshot:
![image](https://user-images.githubusercontent.com/44163707/149762494-e33e0555-727e-4506-b2b0-324e686a2727.png)

**Comment by aothms** [comment]
I think this is a fairly frequent problem when using alpine/musl libc with software not specifically built for it.

The easiest solution would be using an image based on some debian derivative. Is this an option for you?

**Comment by rahulkhandepts** [comment]
Thanks for the response. Yes we can give a try. Can you please share more information about exact debian derivative?

**Comment by Moult** [comment]
@rahulkhandepts how'd it go using the debian derivative?

**Comment by rahulkhandepts** [comment]
> @rahulkhandepts how'd it go using the debian derivative?

@Moult using ubuntu:20.04 helped us and we are able to run application in container
