### ISSUE TITLE
replace_attribute in util can lead to mistakes

### ISSUE THREAD

**Issue by Maozerhouni** [IfcOpenShell/IfcOpenShell#1994]
Hi,

the function replace_attribute, available in util.element takes three parameters : element, old, new. Old being the old value of an attribute, and new being the value that should replace it.
It s a little bit odd, as the function never explicitly call the attribute. it parses the element and replace any attribute having the old value with the new value.
It seems to me that it would be more pertinent if it called the attribute by its name. according to the schema.

Code should look something like (in Python)
```
def replace_attribute(element,attribute_name,value):
    types = type(objet.__getattr__(attr))
    if type(value) == types:
        objet.__setattr__(attr,valeur)
```

**Comment by Moult** [comment]
The purpose of the `replace_attribute` function is that very often you have an element that is referenced maybe once, twice, or in a list in another entity. This lets you quickly swap an old entity for a new entity that you've created, commonly when purging subgraphs, or splicing together graphs. It's used in a few places in the API, as well as in a number of IfcPatch recipes.

What you're describing is equivalent to `element.name = "value"`, yes? (or `setattr(element, name, value)`)

I'm not quite sure what your code is suggesting?

**Comment by Maozerhouni** [comment]
yes, it is equivalent to setattr(element, name, value)
I see your usecase. Yes, in this case, the current function is more pertinent.
