### ISSUE TITLE
Section Cutaways don't work with Blender 3.0

### ISSUE THREAD

**Issue by amurrayc** [IfcOpenShell/IfcOpenShell#1995]
When I apply a section cutaway in 3.0 everything disappears in material preview or rendered mode in the viewport.  In 2.93.5 it works fine.

I'm running Linux (NixOS) and see the same effect on a desktop with a Vega 56 GPU and a laptop with Intel integrated graphics.

**Comment by Moult** [comment]
Thanks for catching this bug. Would you mind testing to see if the fix does anything for Blender 2.93 as well?

I think I need a shader guru ( @Gorgious56 ) to fully understand the implications of this.

**Comment by amurrayc** [comment]
Yes, that appears to fix it in 3.0 and 2.93.5 still works.  That was quick!

**Comment by Gorgious56** [comment]
@Moult I have to say I don't fully understand the intent behind this input value node, is it meant to be an offset to the clipping plane ? I would try and get rid of it and set the compare node value to 0 instead : https://github.com/IfcOpenShell/IfcOpenShell/blob/595c72e08dfb9dded86e2b7a26831ebeb180ec12/src/blenderbim/blenderbim/bim/operator.py#L166    `compare.inputs[1].default_value = 0`

But you'll get the opposite clip plane direction as the one you have now, so you'd have to invert it :


    invert = group.nodes.new(type="ShaderNodeInvert")

and then 


    group.links.new(compare.outputs[0], invert.inputs[1])
    group.links.new(invert.outputs[0], group_output.inputs[""])

**Comment by Moult** [comment]
@Gorgious56 the absolute truth is I stole the shader from some site online and maybe I understood how it worked then, but I certainly don't anymore. Have you tried looking at the setup graphically in Blender's node editor? Also note that these shaders are designed to stack, so something that could seem redundant could be stubbing in a potential input node for stacking perhaps? (Try adding multiple section planes).

**Comment by Gorgious56** [comment]
Alright, I can definitely help put some order into this then. 
Could you confirm the desired behavior of this shader, as I understood from looking at it in the node editor :
Clip all the shading of the object if it's below the origin of a target object along its local Z axis, and apply a white shader on backfacing polygons ?

![BSE_85](https://user-images.githubusercontent.com/25156105/150489959-48435647-fb9f-4bc3-b2ad-307758e9ed68.gif)

**Comment by Moult** [comment]
@Gorgious56 that's exactly it. The backfacing colour is configurable by the user (I've set it to red in the Blender interface) but that doesn't change the logic. Also, the shaders must stack.
