### ISSUE TITLE
How to update from 0.6.0 to 0.7.0

### ISSUE THREAD

**Issue by Maozerhouni** [IfcOpenShell/IfcOpenShell#1999]
Hi, I am trying to update the version I have of IfcOpenshell from 0.6.0 to 0.7.0

I have installed msys

I have run the commands following the instructions.
as a result of the last command $ ./install-ifcopenshell.sh, It doesn't work and I get : *** No rule to make target 'install'. Stop.
How to solve this ?
NB : as a result of the previous command, I got that OpenCascade files were not found. but as it was optional, I guessed it won't be an issue. (even though I don't understand why it didn't find it, as geom is working fine on the 0.6.0 version)

**Comment by Maozerhouni** [comment]
trying with Visual Studio : 
I get the error : 
Cloning Open CASCADE 7.5.3 into ...
cloning into 
git: 'remote-https' is not a git command. See 'git --help'.
The most similar command is  remote-http
Checking out Open CASCADE 7.5.3 revision V7_5_3
Updating files : 100% (1450/1450) done.
Head is now at 0bdb4b9f Smart annotation variables for drawings now reimplemented. See #1153 
error : pathspec 'V7_5_5" did not match any file(s) know to git

An error occured

**Comment by aothms** [comment]
1

Yes, we don't have a lot of resources to keep the msys stuff up to date. I'd be happy to assist and get it working. It's likely just missing the couple additions added in v0.7 such as hdf5 mpir mpfr cgal. mpir and mpfr might be challenge though on msys, maybe it's more wise to use gmp mpfr in that case. Another possible route is to simply make sure compilation proceeds without these dependencies.

2

It doesn't seem `remote-https` is in any way contained in this repository. Can you elaborate on what happened? Same for `V7_5_5`. Can you remove the `@echo off` from the build-scripts to see the commands being invoked?

The build-deps installs swig in a specific path and referencing that on my system it's `./_deps-vs2017-x64-installed/swigwin`. Do you have something similar on your end? It's likely that if the build script terminated prematurely it simply didn't get to that step.

**Comment by luzpaz** [comment]
@aothms is there any in-progress development to port ifcopenshell to latest swig (4.0.2) going on?

**Comment by CyrilWaechter** [comment]
@luzpaz On Arch based distro you should use [ifcopenshell-git](https://aur.archlinux.org/packages/ifcopenshell-git). The maintainer `Nahouhak` is actually me. So if it doesn't work send me a message.

**Comment by Moult** [comment]
In an effort to get some closure on this @Maozerhouni have you tried with these latest build instructions? https://blenderbim.org/docs-python/ifcopenshell/installation.html - you can see that OpenCascade is not optional. We might need a bit more feedback to make this a useful issue though.

**Comment by Maozerhouni** [comment]
Hello,
I kept the 0.6.0 version until last week, when I updated to 0.7.0. I used the pip instruction that was put in github. It seems to work fine.
