### ISSUE TITLE
When would shape.id have a comma in it?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2002]
I assumed that if I took shape.id (or shape.geometry.id, depending on how I call `create_shape`) and did `shape.id.split('-')[0]` I would always get an integer of the STEP ID of the representation (or representation item, profile, etc). It looks that way in the code: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomFunctions.cpp#L1837

However, @CyrilWaechter brought up a situation where if I have an IfcCurveBoundedPlane (a representation item) and do create_shape on that, then the returned shape.id is `5,889` that is, it has a comma in it.

What portion of the C++ would cause this? Should it be modified so that it is consistent with L1837 in the link above?

**Comment by aothms** [comment]
I'd say, probably coming from python, that the relevant line is here. L1837 only does full products.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcwrap/IfcGeomWrapper.i#L457

> returned shape.id is 5,889 that is, it has a comma in it.

I have the feeling that it's probably a thousands separator. `boost::lexical_cast` there probably takes the current locale and cyril likely has a local defined with a thousands separator. 

I guess we have to replace all boost::lexical_cast() and std::to_string() instances with something like

~~~C++
template <typename T>
std::string to_locale_invariant_string(const T& t) {
  std::ostringstream oss;
  oss.imbue(std::locale::classic());
  oss << t;
  return oss.str();
}
~~~

**Comment by CyrilWaechter** [comment]
I discovered this morning while teaching that it could also contains a space which produce similar issue.
```python
File "<path_to_blender_addons>\blenderbim\bim\import_ifc.py", line 1615, in link_mesh
ValueError: invalid literal for int() with base 10: '58 055'
```
@Moult Is blenderbim-220201 shipped with 36a7985 or above ? If so issue needs to be reopened.

**Comment by Moult** [comment]
@CyrilWaechter it isn't shipped with the fix. But we should definitely double check regardless. Can you compile yourself? If not, we can wait for the next bot build and retest your file.

**Comment by CyrilWaechter** [comment]
It occurred on windows. I have no build setup on windows.

I see that there was some work done on CI (See #1625 and #1666). Not sure why it is on hold.

**Comment by Moult** [comment]
@CyrilWaechter a bot build is out https://github.com/IfcOpenBot/IfcOpenShell/commit/883b8a523c63027f2f6c91650385d47edba5521b perhaps you can try to recreate your issue (you'd need to swap out the IfcOpenShell module with the bot build - but take care only to swap out the pyd stuff not the api/utils).

**Comment by CyrilWaechter** [comment]
@Moult I confirm that it is fixed with https://github.com/IfcOpenBot/IfcOpenShell/commit/883b8a523c63027f2f6c91650385d47edba5521b
