### ISSUE TITLE
problemn installing in anaconda

### ISSUE THREAD

**Issue by javieerao** [IfcOpenShell/IfcOpenShell#2005]
Hi

i install the package in anaconda using the anaconda terminal with 

`pip install git+https://github.com/IfcOpenShell/IfcOpenShell`

But when the installation was finished, the package was recognized as unknown.

I tried downloading the zip and using

`pip install c:/user.....zipl`

and the result was the same. 

![image](https://user-images.githubusercontent.com/80270070/151161438-b724cca9-2047-47fd-94a8-ef03585cf8d0.png)

**Comment by aothms** [comment]
IfcOpenShell is a binary module so it doesn't install that easily. You can get archives from here https://github.com/IfcOpenBot/IfcOpenShell/commit/000e3acb2bf16ff0863ab91b208b7dbda56f8b59#comments or use one of the conda channels where it's available such as `conda-forge`.

**Comment by Moult** [comment]
There are new conda builds so this can be resolved :) https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#conda
