### ISSUE TITLE
[IfcPatch] The latest version of IfcPatch seems not working.

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#2007]
I run the following code and it just returns an empty IFC file.

```
import ifcpatch


ifcpatch.execute({
    "input": "../ifc_model/house5.ifc",
    "output": "output.ifc",
    "recipe": "ExtractElements",
    "log": "ifcpatch.log",
    "arguments": ['.IfcWall'],
})
```

I found that the function  ifcopenshell.api.run returns a null object. Can anyone help with this problem? Many thanks.

`new_element = ifcopenshell.api.run("project.append_asset", self.new, library=self.file, element=element)`

**Comment by Moult** [comment]
I just tested the patch code you put and it works fine for me. If you're still experiencing issues, perhaps send your file, or let's do a screenshare? I'm online on the OSArch.org live chat during the Sydney timezone.

Append_asset also works for me. Perhaps you are using the stable release of the BlenderBIM Add-on from last year where it didn't have support for appending products? You might want to use a Github daily build.

**Comment by CrossStyle** [comment]
@Moult The code I used was installed using conda (like the code below). 

`$ conda install -c conda-forge -c oce -c dlr-sc -c ifcopenshell ifcopenshell`

The installed version of IfcOpenShell is version 0.60. Is this the latest version? Or maybe I should build the v0.7.0 version myself.

**Comment by aothms** [comment]
https://github.com/IfcOpenBot/IfcOpenShell/commit/000e3acb2bf16ff0863ab91b208b7dbda56f8b59#comments

**Comment by Moult** [comment]
@CrossStyle yep as @aothms mentioned that's the latest bot build. Just grab the one for your Python version and stick it in your sys.path and that should be good.

The version you're using is pretty (very) old unfortunately.
