### ISSUE TITLE
[IfcConvert] Error when parsing ifc to xml

### ISSUE THREAD

**Issue by ketourneau** [IfcOpenShell/IfcOpenShell#2009]
Hi !

We got error when we try to convert a .ifc file (from our customer) to xml 

> Log:
[Error] [2022-01-28 09:40:56] Token $ at 191018 invalid string
[Error] [2022-01-28 09:40:56] Token $ at 191033 invalid instance name

We identify the bug, it's a wrong IFCRELDEFINESBYPROPERTIES line

> #4645= IFCRELDEFINESBYPROPERTIES($,$,$,$,(#865),$);

Would it be possible not to stop the conversion but to ignore this and show a warning ?

[04_surface_projet.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/7957108/04_surface_projet.ifc.zip)

**Comment by aothms** [comment]
Hm yes, there is some sort of tradeoff between supporting invalid files and the impact on the code.

It's not impossible, but in the way how IfcOpenShell is structured it's also pretty hard to come up with a general solution except for try-catching almost every line.

Have a look at the commit, next time feel free to propose the change yourself.
