### ISSUE TITLE
Bim authoring tool throws error when no ifc project is active

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#2010]
**Issue**

This line https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/model/data.py#L42 throws `AttributeError: 'NoneType' object has no attribute 'by_type'` when no ifc project is active.

**Steps to reproduce**

- Brand new file, click on the BIM authoring tool icon in the viewport : ![image](https://user-images.githubusercontent.com/25156105/151552156-94e5fd08-a895-4a6c-a8c3-3576e86c6511.png)
- Error in console

**Possible solution**

I think the solution is to check if an ifc file is available on the start of the `draw_settings` method, return early if not :

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/model/workspace.py#L54

OR to add an `if` clause on the line that throws error and return an empty `classes` set if no file is available ?

**Comment by Moult** [comment]
Yeah, if no IFC file is available, it probably shouldn't display at all.

**Comment by Gorgious56** [comment]
This seems it's a very simple fix but I'm wondering about the best course of action. I understand we should keep the Data loading at the very start of the UI draw method. What do you think of :

```
    def draw_settings(context, layout, tool):
        if not AuthoringData.is_loaded and IfcStore.get_file():
            AuthoringData.load()

        row = layout.row(align=True)
        if not IfcStore.get_file():
            row.label(text="No IFC Project", icon="ERROR")
            return

```

**Comment by Moult** [comment]
Why not in poll like every other UI thing?

**Comment by Gorgious56** [comment]
Well yeah that's what I thought at first but AFAIK there is no `poll` method for `bpy.types.WorkspaceTool`...

**Comment by Moult** [comment]
Oh. Well in that case, your solution looks just fine :)
