### ISSUE TITLE
BB: assigning available contexts to an object

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2012]
When i click on this...
![](https://community.osarch.org/uploads/editor/pv/ehr5qhj962fc.png "")

I would expect a dropdown or something to select the contexts that have been assigned here...
![](https://community.osarch.org/uploads/editor/8y/5t4quno9600x.png "")
As you can see there, it only add Tessellation context.

from an older version of BB...
![](https://community.osarch.org/uploads/editor/w6/z7h13x0pkebf.gif "")

Am i missing something?

**Comment by Moult** [comment]
Good catch! The tests indirectly caught this back in Dec 10 [here](https://github.com/IfcOpenShell/IfcOpenShell/commit/de4659570a913482359f631bb19e88854334d125) but I was not clever enough to recognise it at the time.

Unfortunately tests cannot directly catch this type of bug as it is a UI bug.
