### ISSUE TITLE
[v0.7.0] Failed to export IFC file ( '.T.' instead of '#id' or '.F.' instead of '$')

### ISSUE THREAD

**Issue by Fed80** [IfcOpenShell/IfcOpenShell#2018]
Hi. I'm using v0.7.0/src/ifcparse source files (Boost v.1.67.0) to create an IFC model and export it to an IFC file.
Regardless of the scheme I use, the exported file contains several errors in parameters of IFC lines that I will expose below.
This problem was not occurring when I was using version 0.5.0.
What could have gone wrong? Thanks in advance.

----------------------------------------------------------------

Example 1:

CODE:

```
[...]
IfcSchema::IfcSite * site = file.addSite();
[...]
```

IFC file:

```
#13=IFCDIRECTION((1.,0.,0.));
#14=IFCDIRECTION((0.,0.,1.));
#15=IFCCARTESIANPOINT((0.,0.,0.));
#16=IFCAXIS2PLACEMENT3D(#15,#14,#13);
#17=IFCLOCALPLACEMENT($,.T.);
#18=IFCSITE('3MxM7e27XE4Qx11uERnfUi',#5,$,$,$,#17,$,$,.ELEMENT.,$,$,$,$,$);
```

I expected line 17 to be like this: (like in 0.5.0 version)

`#17=IFCLOCALPLACEMENT($,#16);`

----------------------------------------------------------------

Example 2:

CODE:

```
[...]
IfcSchema::IfcPropertySingleValue * prop = new IfcSchema::IfcPropertySingleValue("MyProperty", null, new IfcSchema::IfcBoolean(true), 0);
[...]

```
IFC file:

`#9=IFCPROPERTYSINGLEVALUE('MyProperty',$,.T.,.F.);`

I expected IFC line 9 to be like this: (like in 0.5.0 version)

`#9=IFCPROPERTYSINGLEVALUE('MyProperty',$,IFCBOOLEAN(.F.),$);`

----------------------------------------------------------------

**Comment by aothms** [comment]
Yes, you're right, these were issues related to changes wrt to how select types are handled. This changed in v0.7 to use virtual inheritance to properly support them in the type system. Second argument of the `#17` signature is a select `IfcAxis2Placement = SELECT(IfcAxis2Placement2D, IfcAxis2Placement3D)` which wasn't property captured. Same for prop single value, which has a IfcValue as a type for nominal value. Should be fixed now.
