### ISSUE TITLE
How to use IfcRelAggregates to connect two elements and write it to a .ifc file?

### ISSUE THREAD

**Issue by carlblack1987** [IfcOpenShell/IfcOpenShell#2019]
I have wrote a C++ program to export the content to a .ifc file.
I created two entities and they have compose/decompose relations like this:

ENTITY IfcFillerSection
 SUBTYPE OF (IfcRailwaySubgradeProfile);
	Position : IfcBoolean;
	FillerLayers : LIST [1:?] OF IfcFillerLayer;
END_ENTITY;

ENTITY IfcFillerLayer
 SUBTYPE OF (IfcRailwaySubgradeProfile);
	Position : IfcBoolean;
	FillerLayerType : IfcLabel;
	FillerType : IfcLabel;
END_ENTITY;

However, someone told me that I shall not define entities in this way. I should use IfcRelAggregates to interpret this kind of one-to-many relation. I googled this entity while I can hardly find any C++ code examples.
So, how should I use the entity IfcRelAggregates to connect two elements (in C++ code) and write this relation to a .ifc file?
Thank you very much.

**Comment by aothms** [comment]
I'm not following you entirely. It seems like you're creating your own schema extension?

Indeed, you can use the existing aggregation/decomposition/nesting concepts to express this. It seems like your relationship has an order (you chose LIST) so you'd use 

If you use IfcHierarchyHelper (not required) you could write something like:

    file.addRelatedObject<typename Schema::IfcRelNests(my_section, my_layer);

otherwise you do

    IfcSchema::IfcFillerLayer::list::ptr parts(new aggregate_of<IfcSchema::IfcFillerLayer>());
    parts->push(my_layer);
    new IfcSchema::IfcRelNests(guid, ownerhist, None, None, my_section, parts)

**Comment by carlblack1987** [comment]
Yes, I added some new entities to express a subgrade and filler layers of it. A segment of a subgrade may includes several fille layers.
For example, a segment of the mileage from 100 meter to 200 meter has:
Filler layer 1 (material: cracked rock, thickness: 1m);
Filler layer 2 (material: concrete, thickness: 0.5m);
Filler layer 3 (material: mixture filler, thickness: 0.7m);
Hence, I wanted to express this hierarchy in IFC, and I chose LIST to represent the relations. However, an expert told me that this kind of relation shall be expressed by aggregation in IFC.
Thank you very much for your advice. But I still have some questions.
I try the first way you provided, the pseudocode is as follow:
_for each (IDMFillerSectorUnit ^ flrSection in subgrade->fillerSectorUnits) {
    IfcFillerSection ifcsector = new IfcFillerSection;
    for each (IDMFillerLayerUnit ^ flrLayer in flrSection->fillerLayerUnits) {
        IfcFillerLayer ifclayer = new IfcFillerLayer;
		file.addRelatedObject<typename Schema::IfcRelAggregates(ifcsector, ifclayer, file.getSingle<IfcSchema::IfcOwnerHistory>());
	}
}_
The code is correct and the relations recorded by IfcRelAggregates are written to file successfully.
However, the content in .ifc file is a little confusing:
**#205=IFCRELAGGREGATES('0h7qh0OOvEAPP5SdSrLMkQ',#5,$,$,#175,(#204,#0,#0));**
The upper line is a relation for connecting a filler section (#175) to its filler layers (#204,#0,#0), and there are three filler layers. But only the #204 is the correct ID of a filler layer, the latter two are expressed by #0. Is there something wrong with my code?

**Comment by carlblack1987** [comment]
I have just figured it out.
This issue is due to the fact that some elements are actually not written to the .ifc file.
I manually add these elements by using file.addEntity. Now it is OK.
**#465=IFCRELAGGREGATES('1goxawYLzARuOpNzSfsalx',#5,$,$,#464,(#423,#497,#535));**
