### ISSUE TITLE
Retrieve the hierarchy of the ifc file : first floor, second floor, ...

### ISSUE THREAD

**Issue by Skyndia** [IfcOpenShell/IfcOpenShell#202]
Hi everyone. 
First, thank you for your work here.

I need to convert ifc file to unity readable files, but retrieving the full hierarchy of the building (ground floor, .. ), and the type of the objects (window, door, wall, ..).

Is it possible to achieve this with IfcConvert in its current state, or is it in progress ? 

Thank you for reading.

**Comment by Stinkfist0** [comment]
Yes, but one needs to write importer for Unity which the geometry information (OBJ or DAE) and IFC data (XML) together.

**Comment by Skyndia** [comment]
Ok thanks, but is it possible to directly get a DAE file with the right hierarchy ? I would like to avoid storing and parsing the xml file.

**Comment by Stinkfist0** [comment]
Should be possible, although the code could get quite complex. For now the different serializers are written so that they simply "stream" arbitrary number of objects from the IFC file into the chosen output format.

**Comment by aothms** [comment]
The Blender importer has an option to reconstruct the hierarchy [1]. It would be nice to have this exposed to more output formats, but not something I have the time for at the moment. Pull requests welcome!

Alternatively, it should be fairly trivial also to merge the DAE and XML files into some post processing script.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcblender/io_import_scene_ifc/__init__.py#L175

**Comment by Skyndia** [comment]
Ok thank you, I'll see if I have the time to add this feature.

**Comment by thorade** [comment]
Not sure if it helps: 
We are using Archicad and Cinema4D and fbx to get our models nto Unity, 
following this blog post mostly:
http://cad-3d.blogspot.de/2014/10/getting-bim-data-into-unity-part-1.html
But, that also does not preserve the hierarchy.

Would you recommend DAE or OBJ over FBX?

**Comment by aothms** [comment]
@thorade this is implemented now by @Skyndia see https://github.com/IfcOpenShell/IfcOpenShell/pull/211

**Comment by stefkeB** [comment]
FWIW, as the writer of the (old) blogpost cited above... I have been able to reconstruct the full IFC hierarchy from the OBJ and XML files as generated from IfcConvert inside Unity.

I used an OBJreader as it was able to load geometry at runtime. And then parsed the XML file with a custom C# script.

I'm planning to share the results in a later blog post.

**Comment by aothms** [comment]
> I used an OBJreader

Using DAE has the added advantage that typically geometry for reoccurring instances can be reused. Depending on the file this may potentially be quite advantageous.

> I'm planning to share the results in a later blog post.

Looking forward :)

**Comment by Stinkfist0** [comment]
Yeah, from experience I can recommend DAE over OBJ for Unity. However, I did ran into problems couple of times with large/complex DAEs and I used OBJ as a workaround in the past.

**Comment by aothms** [comment]
> I did ran into problems couple of times with large/complex DAEs

Not every XML parser seems to be equipped for the crazily long textnode values for detailed mesh positions/normals. I occasionally had to switch do single precision to cut down on the text node size. No experience with Unity though.

**Comment by Stinkfist0** [comment]
Yeah, and in the case of Unity, the actual underlying importer/parser is the Autodesk FBX SDK (I could reproduce the errors with a standalone importer that is available).

**Comment by Plauine** [comment]
> I'm planning to share the results in a later blog post.

Hi @stefkeB, did you share your result yet?

**Comment by Moult** [comment]
@Skyndia would the latest BlenderBIM Add-on be able to help in any way? It reconstructs the spatial hierarchy and has quite a few options for filtering and so on.

**Comment by stefkeB** [comment]
> > I'm planning to share the results in a later blog post.
> 
> Hi @stefkeB, did you share your result yet?

http://cad-3d.blogspot.com/2018/09/getting-bim-data-into-unity-part-9.html

**Comment by Moult** [comment]
The BlenderBIM Add-on has a variety of ways of reconstructing the spatial decomposition tree which you can configure, and can be saved as DAE or a few other ways that Unity can read, so I guess this can be closed.
