### ISSUE TITLE
Counting faces of elements

### ISSUE THREAD

**Issue by denizmaral** [IfcOpenShell/IfcOpenShell#2020]
I tried to follow that [article](https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#Geometry_processing) to count faces of all elements. I created in Blender some stupid stuff and deleted some of them. When I list all elements, I get only 3 elements but when I want to collect facesCount it gives me the information of deleted objects.

![grafik](https://user-images.githubusercontent.com/55183821/152560101-7cb1d78e-bcd0-450a-8a8f-7d897a6c3424.png)

[ifcopenshell.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8004329/ifcopenshell.zip)

**Comment by Moult** [comment]
I'm not sure what the question is. What code are you running to count faces? What are the steps you are doing?

**Comment by denizmaral** [comment]
> I'm not sure what the question is. What code are you running to count faces? What are the steps you are doing?

Hi Dion,
I followed your workflow. In your workflow you showed how we can get face vertices. The biggest vertex+1 gives me the amount of the faces. It works well but if I create some objects in Blender and then delete them, they are not getting removed from Database. Can you please try on my IFC file? 
facesAnzahl stands for amount of faces.

**Comment by Moult** [comment]
What database are you referring to? How are you creating objects in Blender? How are you deleting them? I'm also not sure how the biggest vertex+1 gives you the number of faces - that doesn't sound right. Maybe coincidentally it does in your scenario.

**Comment by denizmaral** [comment]
I created some cubes and then assign them IfcWall class. I manipulated the geometry (increased the faces). It might be right about max(faces)=biggest vertex (actually index) and plus 1 to get amount. It works but it shows more outputs than amount of elements. I deleted elements with Blender command (X). Can you see my code in my post?

**Comment by Gorgious56** [comment]
Iif you want to get the number of faces, assuming you only have triangulated geometry, you can get it with
`faces_count = len(faces) / 3` since a triangle is represented by exactly 3 vertex indices.

Also it's easier if you post code snippets as text so we can use it to troubleshoot your issue :)

**Comment by Moult** [comment]
@denizmaral sorry but the code you wrote still doesn't quite make sense. If you add faces in the BlenderBIM Add-on, it won't immediately show up in your IFC data until you save. Does that help?

**Comment by denizmaral** [comment]
@Gorgious56 here is the code. I copied from OSArch and added some stuff to collect vertices.
`import multiprocessing
import ifcopenshell
import ifcopenshell.geom

totalFace = []

try:
    ifc_file = ifcopenshell.open(r"C:\Users\dmaral\Documents\ifcopenshell.ifc")
except:
    print(ifcopenshell.get_log())
else:
    settings = ifcopenshell.geom.settings()
    iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
    if iterator.initialize():
        while iterator.next():
            shape = iterator.get()
            element = ifc_file.by_guid(shape.guid)
            faces = shape.geometry.faces # Indices of vertices per triangle face e.g. [f1v1, f1v2, f1v3, f2v1, f2v2, f2v3, ...]
            verts = shape.geometry.verts # X Y Z of vertices in flattened list e.g. [v1x, v1y, v1z, v2x, v2y, v2z, ...]
            totalFace.append(max(faces)+1)
`

@Moult I add faces and then export to IFC. After I enter that code it gives me the faces of deleted objects too

**Comment by Moult** [comment]
@denizmaral sorry I lost track of this issue. You've just shown the same code as the original post, I still don't understand why you're doing max(faces)+1, as faces is a list of vertex indices per triangle face. You want to change totalFace = 0, and then do totalFace += len(faces) / 3 as @Gorgious56 suggested in the while loop.
