### ISSUE TITLE
Looking for help converting code from Python to C++

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#2023]
I've been using ifcopenshell-python, but it doesn't run efficiently enough, so I'm considering converting these python code to c++. But I am new to C++ and I have encountered some problems in the process.

```
import ifcopenshell
import ifcopenshell.geom
import multiprocessing
from OCC.Core.Quantity import Quantity_Color, Quantity_TOC_RGB
from OCC.Display.SimpleGui import init_display
from OCC.Core.Bnd import Bnd_Box
from OCC.Core.BRepBndLib import brepbndlib_Add

settings = ifcopenshell.geom.settings()
settings.set(settings.USE_PYTHON_OPENCASCADE, True)
settings.set(settings.USE_WORLD_COORDS, True)


def ifc_visualization(_ifc_file):
    display, start_display, add_menu, add_function_to_menu = init_display()
    iterator = ifcopenshell.geom.iterator(settings, _ifc_file, multiprocessing.cpu_count())
    i = 0
    if iterator.initialize():
        while iterator.next():
            try:
                to_update = i % 20 == 0
                shape = iterator.get()
                entity = _ifc_file.by_guid(shape.data.guid)
                if entity.is_a('IfcSite') or entity.is_a('IfcSpace'):
                    continue
                bbox1 = Bnd_Box()
                brepbndlib_Add(shape.geometry, bbox1)
                bbmin, bbmax = [0.] * 3, [0.] * 3
                bbmin[0], bbmin[1], bbmin[2], bbmax[0], bbmax[1], bbmax[2] = bbox1.Get()
                r, g, b, a = shape.styles[0]  # the shape color
                color = Quantity_Color(abs(r), abs(g), abs(b), Quantity_TOC_RGB)
                display.DisplayShape(shape.geometry, color=color, transparency=0.9, update=to_update)[0]
                i += 1
            except:
                continue
    start_display()
```
When converting this sentence:

` iterator = ifcopenshell.geom.iterator(settings, _ifc_file, multiprocessing.cpu_count())`

I used the following code (with ifcopenshell v0.7.0), but it doesn't work and return` E0289 C++ no instance of constructor matches the argument list argument types are: (IfcGeom::IteratorSettings, IfcParse::IfcFile, int)`. 

```
#define IfcSchema Ifc2x3
#include "../ifcparse/IfcFile.h"
#include "../ifcparse/Ifc2x3.h"
#include "../ifcgeom/IfcGeomIteratorSettings.h"
#include "../ifcgeom_schema_agnostic/IfcGeomIterator.h"
using namespace std;

const string ifc_path = "D:/code/bimsc/ifc_model/cottage/cottage.ifc";
IfcParse::IfcFile file(ifc_path);
IfcGeom::IteratorSettings settings;
settings.set(settings.USE_WORLD_COORDS, true);
IfcGeom::Iterator iterator(settings, file, 16);
```
But I indeed pass IfcGeom::IteratorSettings to the IfcGeom::Iterator class. I don't know how to deal with it, hope someone can help me. Thank you.

**Comment by aothms** [comment]
https://ifcopenshell.github.io/docs/rst_files/class_ifc_geom_1_1_iterator.html#_CPPv4N7IfcGeom8Iterator8IteratorERKN7IfcGeom16IteratorSettingsEPN8IfcParse7IfcFileEi

The 2nd argument is IfcFile*, so you `&file`.

**Comment by aothms** [comment]
You'd indeed benefit from converting this to C++, not so much because C++ is faster than python (it is, but in this case your python code doesn't do much computation). The bottleneck is really in `iterator.get()` and `display.DisplayShape(shape.geometry)` which communicate by means of the string serialization of the shape, which is really really slow in open cascade.

**Comment by CrossStyle** [comment]
Thanks for your help. 

Indeed, `display.DisplayShape(shape.geometry)` is very slow. Normally, I would try to avoid running that code. But even if I don't display the model, it still takes 20 seconds to load a 40M model, and those larger models should take a few minutes. So I decided to convert the code from Python to C++.

By the way, do you ever notice when using `ifcopenshell.geom.iterator` to generate entities, it may lose some entities. But using `ifcopenshell.geom.create_shape` doesn't, it's just slower.

```
def visual(ifc_file):
    display, start_display, add_menu, add_function_to_menu = init_display()
    ifc_products = ifc_file.by_type('IfcProduct')
    for i, product in enumerate(ifc_products):
        if product.Representation:
            if product.is_a('IfcSite') or product.is_a('IfcSpace'):
                continue
            try:
                shape = ifcopenshell.geom.create_shape(settings, product)
                # r, g, b, a = shape.styles[0]  # the shape color
                # color = Quantity_Color(abs(r), abs(g), abs(b), Quantity_TOC_RGB)
                color = Quantity_Color(random.random(), random.random(), random.random(), Quantity_TOC_RGB)
                to_update = i % 100 == 0
                display.DisplayShape(shape.geometry, color=color, transparency=0.8, update=to_update)[0]
            except:
                continue
    start_display()
```

**Comment by CrossStyle** [comment]
@aothms It seems weird because I can't find ifcgeom_schema_agnostic.lib in the `IfcOpenshell\_build-vs2019-x64\RelWithDebInfo` directory. So, `#include "../ifcgeom_schema_agnostic/IfcGeomIterator.h"` causes an error.

**Comment by aothms** [comment]
ifcgeom_schema_agnostic/ results in IfcGeom.lib

ifcgeom/ results in IfcGeom_ifc2x3.lib IfcGeom_ifc4.lib ...

**Comment by CrossStyle** [comment]
@aothms After I add the code `#include "../ifcgeom/IfcGeom.h"` in IfcPraseExamples.cpp, it raised two errors.

```
#define IfcSchema Ifc2x3
#include "../ifcparse/IfcFile.h"
#include "../ifcparse/Ifc2x3.h"
//#include "../ifcgeom/IfcGeomIteratorSettings.h"
#include "../ifcgeom/IfcGeom.h"
//#include "../ifcgeom_schema_agnostic/IfcGeomIterator.h"
#if USE_VLD
#include <vld.h>
#endif
int main(int argc, char** argv) {
	if ( argc != 2 ) {
		std::cout << "usage: IfcParseExamples <filename.ifc>" << std::endl;
		return 1;
	}
	// Redirect the output (both progress and log) to stdout
	Logger::SetOutput(&std::cout,&std::cout);

	// Parse the IFC file provided in argv[1]
	IfcParse::IfcFile file(argv[1]);
	if (!file.good()) {
		std::cout << "Unable to parse .ifc file" << std::endl;
		return 1;
	}
	IfcSchema::IfcBuildingElement::list::ptr elements = file.instances_by_type<IfcSchema::IfcBuildingElement>();
	std::cout << "Found " << elements->size() << " elements in " << argv[1] << ":" << std::endl;
	for (IfcSchema::IfcBuildingElement::list::it it = elements->begin(); it != elements->end(); ++it) {
		const IfcSchema::IfcBuildingElement* element = *it;
		std::cout << element->data().toString() << std::endl;
		const IfcSchema::IfcWindow* window;
		if ((window = element->as<IfcSchema::IfcWindow>()) != 0) {
			if (window->OverallWidth() && window->OverallHeight()) {
				const double area = *window->OverallWidth() * *window->OverallHeight();
				std::cout << "The area of this window is " << area << std::endl;
			}
		}
	}
}
```

```

Error	LNK2019	
unresolved external symbol "public: int __cdecl Standard_Transient::DecrementRefCounter(void)const " (?DecrementRefCounter@Standard_Transient@@QEBAHXZ) referenced in function "public: __cdecl opencascade::handle<class Standard_Transient>::~handle<class Standard_Transient>(void)" (??1?$handle@VStandard_Transient@@@opencascade@@QEAA@XZ)	
IfcParseExamples	
D:\code\ifc\IfcOpenshell\_build-vs2019-x64\examples\IfcParseExamples.obj	
1	


Error	LNK1120	
1 unresolved externals	IfcParseExamples	
D:\code\ifc\IfcOpenshell\_build-vs2019-x64\examples\RelWithDebInfo\IfcParseExamples.exe	
1	

```
Then, I add the `IfcGeom.lib` to Linker-Input-Additional dependencies, but it doesn't work.

**Comment by aothms** [comment]
I think you're doing the opposite of what you intent, rather

    #include "../ifcgeom_schema_agnostic/IfcGeomIterator.h"

and make sure you link to add IfcGeom.lib and IfcGeom_ifc___.lib

Don't include IfcGeom.h because it's schema dependent so it expects the ifc schema version selection machinery is setup.

The missing symbols come from open cascade. Also make sure you link to all open cascade libraries. By default IfcParseExamples doesn't because it's only intended to link to IfcParse and not IfcGeom.

**Comment by CrossStyle** [comment]
@aothms It works and thank you very much.

Next, I ran into another obstacle. I don't know how to convert these two sentences from Python to C++.
```
shape = iterator.get()
entity = _ifc_file.by_guid(shape.data.guid)
```
I used the following code, but it is wrong.
```
IfcGeom::IteratorSettings settings;
settings.set(settings.USE_WORLD_COORDS, true);
IfcGeom::Iterator iterator(settings, &file, 16);
if (iterator.initialize()) {
while (iterator.next()) {
	IfcSchema::IfcBuildingElement::list::ptr shape = iterator.get();
	IfcSchema::IfcBuildingElement product = iterator.get()->product();
} 
}
```

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcconvert/IfcConvert.cpp#L1120

~~~C++
IfcGeom::Element* geom_object = context_iterator.get();
serializer->write(static_cast<const IfcGeom::BRepElement*>(geom_object));
~~~

But also add

~~~C++
settings.set(settings.DISABLE_TRIANGULATION, true);
~~~

This is implied when you do USE_PYTHON_OPENCASCADE in python. It switches between returning a mesh (`IfcGeom::TriangulationElement*`) to returning a native brep.

~~~C++
IfcUtil::IfcBaseEntity* product = geom_object->product()
~~~

Keep in mind that C++ is a statically typed language. We don't know which schema the file is in, so we don't know whether it's a Ifc2x3::IfcProduct or a Ifc4::IfcProduct or a ... See http://blog.ifcopenshell.org/2019/12/v060.html for tips

I must say that probably I'd recommend at going this route, it seems you're very familiar with C++ and there is a lot of added complexity. Have look at e.g https://github.com/panda3d/panda3d or just use Blender and stick to the triangulated output of IfcOpenShell, you can eliminate a lot of the performance overhead by skipping the occt serialization.

**Comment by CrossStyle** [comment]
@aothms Thanks for the suggestion, I will definitely give it a try.

Another problem is how to return "TopoDS_Shape", because I need to use the function `BRepBndLib::Add` to get the bounding box.

```
IfcGeom::Element* geom_object = iterator.get();
IfcUtil::IfcBaseEntity* product = geom_object->product();
serializer->write(static_cast<const IfcGeom::BRepElement*>(geom_object));

//serializer->finalize();
//serializer.reset();

Bnd_Box bbox;
BRepBndLib::Add(geom_object, bbox);
```

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/768b754a0b4ccc82e2288037289aa16ce9e26afa/src/serializers/OpenCascadeBasedSerializer.cpp#L40-L46

`compound.Moved(trsf)` would be your topods_shape
