### ISSUE TITLE
Can't run ifcpatch CLI

### ISSUE THREAD

**Issue by hvn74** [IfcOpenShell/IfcOpenShell#2026]
Hello i try to run this in windows command-shell: python -m ifcpatch -i foo.ifc -r OffsetObjectPlacements -a -128900 -1532260 0 90

But i get this error:

`File "C:\Users\Hans\AppData\Local\Programs\Python\Python38\Lib\site-packages\ifcpatch\ifcpatch\__init__.py", line 23, in <module>
    import ifcopenshell
ModuleNotFoundError: No module named 'ifcopenshell'`

Have i copied something wrong to my site-packages directory?

When i try to run this in Visual-Studio Code:

`import ifcpatch

ifcpatch.execute({
    "input": "6272_blok 3 2022-01-12 - kopie.ifc",
    "output": "output.ifc",
    "recipe": "OffsetObjectPlacements",
    "arguments": ['10000 10000 0 45'],
})`

I get error: module 'ifcpatch' has no attribute 'execute'

How do i manage to run the ifcpatch coding? Thnx in advanced.

Greetings: HvN

**Comment by Moult** [comment]
IfcPatch assumes you have IfcOpenShell as a dependency :) You might want to first get IfcOpenShell installed. You can download a Python 38 build from 4 days ago: https://github.com/IfcOpenBot/IfcOpenShell/commit/883b8a523c63027f2f6c91650385d47edba5521b#commitcomment-65879927
