### ISSUE TITLE
build with error : unable to find string literal operator ‘operator"" s’ IfcHierarchyHelper.cpp:394: rep->setRepresentationType("Clipping"s);

### ISSUE THREAD

**Issue by hxboxy-xh** [IfcOpenShell/IfcOpenShell#2027]
I'm not a C++ developer. When I compile IfcOpenShell in Linux, I get the following error:
IfcHierarchyHelper.cpp:394:29: error: unable to find string literal operator ‘operator"" s’
  rep->setRepresentationType("Clipping"s);

 void setRepresentationType(boost::optional< std::string > v);

so, What can I do? 
my gcc version is 4.8.5

**Comment by aothms** [comment]
gcc 4.8 is 8 years old. Apparently from before C++ string (C++14) were properly supported.

v0.7.0 requires a proper C++14 compiler and if we ever find the need we might move to C++17.

If you need to support gcc version that old the only thing you can do is stick to v0.6.0

**Comment by hxboxy-xh** [comment]
![image](https://user-images.githubusercontent.com/32007375/152902246-33d5e065-0348-4503-aace-04a1768e2e61.png)
o, i just follow the readme
readme need to be update
