### ISSUE TITLE
build-deps.cmd fails if Visual Studio 2022 is installed alongside Visual Studio 2017

### ISSUE THREAD

**Issue by ssg3d** [IfcOpenShell/IfcOpenShell#2034]
[ifcopenshellerror.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8031792/ifcopenshellerror.txt)
I have attached a file with the output. Works for blenderbim-220202, where the mpir thingy is not present. After blenderbim-220203, it errors out after cloning mpir.

**Comment by aothms** [comment]
> \msbuild.exe /p:Platform=x64 /p:Configuration=Release /p:"WindowsLIB0SDKLIB0Version=" .\lib_mpir_gc\lib_mpir_gc.vcxproj
> '\msbuild.exe' is not recognized as an internal or external command,

> mpir thingy is not present

It was there, but was recently moved

https://github.com/IfcOpenShell/IfcOpenShell/blame/v0.7.0/win/build-deps.cmd#L213

But I don't see big changes wrt msbuild.bat to how it was previously

https://github.com/IfcOpenShell/IfcOpenShell/blame/b103e0dde54f7f83a69fac5089f26b7e658b73bf/win/build-deps.cmd#L423

Do you know which directory the script is in at that point. Can you add a pwd for that?

**Comment by ssg3d** [comment]
Update: Yes, the mpr thingy does seem to be present in blenderbim-220202, but it is at the end. So my build errored out again, just before the make step with the same error:
```
mpir already cloned.
Checking out mpir revision .
HEAD is now at 33be9007 fix bug in mpz_n_pow_ui that failed for exponents longer than 32 bits
Your branch is up to date with 'origin/master'.
HEAD is now at 33be9007 fix bug in mpz_n_pow_ui that failed for exponents longer than 32 bits
\msbuild.exe /p:Platform=x64 /p:Configuration=Release /p:"WindowsLIB0SDKLIB0Version=" .\lib_mpir_gc\lib_mpir_gc.vcxproj
'\msbuild.exe' is not recognized as an internal or external command,
operable program or batch file.
ERROR: msbuild failed for main project with exit code 9009

An error occurred

Build ended at 20:06:04.93. Time elapsed 0:54:02.13.
```
> Do you know which directory the script is in at that point. Can you add a pwd for that?
I can, but in which file and where?

**Comment by aothms** [comment]
> I can, but in which file and where?

I meant `echo "%CD%"` before

https://github.com/IfcOpenShell/IfcOpenShell/blame/v0.7.0/win/build-deps.cmd#L213

---

But I see now that I actually misread the issue, the IfcOpenShell calls msbuild.bat, which in turn calls msbuild**.exe** here

https://github.com/BrianGladman/mpir/blob/master/msvc/vs17/msbuild.bat#L53

So apparently the msbdir detection doesn't seem to work on your system (probably due to vs_version). It really can't be due to a change in IfcOpenShell

https://github.com/BrianGladman/mpir/blob/master/msvc/vs17/msbuild.bat#L15

What visual studio version are you using?

**Comment by ssg3d** [comment]
Ah, I should have mentioned - I installed VS 2022 Professional to try it out alongside my existing VS2017. I however am executing build-deps.cmd from the VS2017 dev command prompt like before, and calling build-deps.cmd vs2017-x64.

**Comment by ssg3d** [comment]
I did a bit of poking around in msbuild.bat and the !InstallDir! is C:\Program Files\Microsoft Visual Studio\2022\Professional.
Maybe something to do with "-latest -products * -requires Microsoft.Component.MSBuild -property installationPath", which may be picking up 2022. Can something be done about this? msbuild.bat keeps getting overwritten by the main bat so its kinda tricky to try over here.

**Comment by ssg3d** [comment]
In the meanwhile, I uninstalled VS2022 and now the build fails at another point:
```
Build started 10/2/2022 10:13:39 am.
     1>Project "D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr.sln" on node 1 (lib_mpfr target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|x64".
     1>Project "D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr.sln" (1) is building "D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr\lib_mpfr.vcxproj" (2) on node 1 (default targets).
     2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot
       be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solutio
       n, and then selecting "Retarget solution". [D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr\lib_mpfr.vcxproj]
     2>Done Building Project "D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr\lib_mpfr.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr.sln" (lib_mpfr target(s)) -- FAILED.

Build FAILED.

       "D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr.sln" (lib_mpfr target) (1) ->
       "D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr\lib_mpfr.vcxproj" (default target) (2) ->
       (PlatformPrepareForBuild target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v142 (Platform Toolset = 'v142') canno
       t be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solut
       ion, and then selecting "Retarget solution". [D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr\lib_mpfr.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.42

An error occurred

Build ended at 10:13:40.58. Time elapsed 0:00:43.86.
```
Have attached the complete output as well:
[ifcopenshellerror.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8037522/ifcopenshellerror.txt)

**Comment by aothms** [comment]
>  I installed VS 2022 Professional to try it out alongside my existing VS2017. I however am executing build-deps.cmd from the VS2017 dev command prompt like before, and calling build-deps.cmd vs2017-x64.

But that's odd. The mpir detection depends on the `%vs_version%` environment variable.

Also odd is that this page doesn't list it https://renenyffenegger.ch/notes/Windows/development/Visual-Studio/environment-variables/index to begin with, so maybe it's not the most reliable way. Not a lot we can do about it, except for rewriting all of this to use cmake, which I have started, but not the time to complete https://github.com/aothms/mpfr/tree/cmake

Same for `!InstallDir!` apparently. Seems like the vs2017 build prompt got really broken by the vs2022 installation :(

> Project "D:\ifcopenshell\_deps\mpfr\build.vs19\lib_mpfr.sln" ... v142 build tools,

Yes, I think we made a mistake, or at least an oversight:

https://github.com/IfcOpenShell/IfcOpenShell/commit/b103e0dde54f7f83a69fac5089f26b7e658b73bf#diff-5e45e746c416f95cb387193b30fd89dddd0c52c775caeb82573d6b2d1f0855a7R441

`build.vc15` -> `build.vs19`

This should have been conditional.

```
if "%VS_VER%"=="2017" (
set mpfr_sln=build.vc15
) else (
set mpfr_sln=build.vs19
)
```

And then change

    "%DEPENDENCY_DIR%\build.vs19\lib_mpfr.sln"

to

    "%DEPENDENCY_DIR%\%mpfr_sln%\lib_mpfr.sln"


If it works for you please send in a PR. My head is spinning with all the msvc changes related to mpfr and mpir. There is also this 70+ comment issue about it https://github.com/IfcOpenShell/IfcOpenShell/issues/1993

**Comment by ssg3d** [comment]
I discovered that:
1. Uninstalling VS2022 and
2. Checking out and building blenderbim-220121 builds successfully
So at least my main work can continue and I'll try out your suggested fixes (thanks!) in parallel.

**Comment by ssg3d** [comment]
@aothms, the fix worked so I have submitted a PR. Am changing the topic of this issue and closing it. I have uninstalled 2022 for now. I was planning to move to VS2022, is building ifcopenshell supported for 2022? Meaning if I have a machine with ONLY 2022 installed and use the dev prompt for 2022, will it work? (Note that the problem happened when I had 2022 installed, but continued to use 2017).
