### ISSUE TITLE
Sequence of floats not recognized as such when creating IfcCartesianPoint (Python)

### ISSUE THREAD

**Issue by FrankRuis** [IfcOpenShell/IfcOpenShell#2038]
Using IfcOpenShell for 64 bit Python 3.7 in an Ubuntu Docker container.

When I create an IfcCartesianPoint with `ifc.create_entity('IfcCartesianPoint', Coordinates=(9.4, 3.18, 0.0))` I get the error `ValueError: Expected AggregateOfDouble for attribute IfcCartesianPoint.Coordinates, got (9.4, 3.18, 0.0)`.

The error occurs in the `__setitem__` function of the `entity_instance` class in `entity_instance.py`, where an exception is caught when `entity_instance.unwrap_value(value)` is called.
I can trace the error up to the C++ method `setArgumentAsAggregateOfDouble` in `ifcopenshell_wrapper.py`, which throws the error `TypeError: Attribute of type AGGREGATE OF REAL needs a python sequence of floats`, but as far as I know `(9.4, 3.18, 0.0)` is certainly a sequence of floats, and different sequences such as a list or explicitly casting the elements to float does not work either.

The same code works without issues on my own Windows machine, which makes me think that there is some kind of silent dependency issue, but I can't figure out how to continue debugging from here.

**Comment by aothms** [comment]
This puzzles me. Is there anyway you can quickly share your dockerfile maybe with a `python -c '...'` so that I can quickly reproduce?

**Comment by FrankRuis** [comment]
Sorry for the late response, I was not able to reproduce the error in a simple new Dockerfile, but I have figured out the problem in the meantime.

I obtained the coordinates from a TypeDB database as a dictionary of floats, and while `isinstance(n, float)` returns `True`, it still needed to be casted to float explicitly with `float(n)` to work. I thought I had casted everything to float already, but there was a hardcoded 0 for the z dimension that I missed somewhere.

**Comment by aothms** [comment]
Yes, that has also bitten me several times for ex with numpy. There might surely be a better way to handle this. If you're interested feel free to propose something. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcwrap/utils/type_conversion.i#L32-L41
