### ISSUE TITLE
IfcConvert to XML with Material data

### ISSUE THREAD

**Issue by TomBethoule** [IfcOpenShell/IfcOpenShell#204]
Hello,

I would like know is it possible to include the list of material in the xml file ? 
In order to have the name of material associate an element in database. 

Thanks for your help

**Comment by aothms** [comment]
I suppose so, the question would be in which detail and how you want to relate this information. Would you be interested in materials as XML nodes, or only a string literal label associated as an attribute to the elements in the decomposition? And how about compound materials, e.g [1] [2] [3]. in which detail would you want access to these structures?

[1] http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcmaterialresource/lexical/ifcmateriallayerset.htm
[2] http://www.buildingsmart-tech.org/ifc/IFC4/final/html/schema/ifcmaterialresource/lexical/ifcmaterialprofileset.htm
[3] http://www.buildingsmart-tech.org/ifc/IFC4/final/html/schema/ifcmaterialresource/lexical/ifcmaterialconstituentset.htm

**Comment by TomBethoule** [comment]
I would like to have a list of material  with name, per sample : 
```xml
<IfcMaterial id="aaaaaaaaaaaaa">
     <Name>Default Wall</Name>
</IfcMaterial>
```

And on the element le material associate. per sample : 
```xml
<IfcWallStandardCase id="1MBocHRAL1BhRSrmeqjyjg" Name="Basic Wall:Wall 1:2410" ObjectType="Basic Wall:Wall 1:1547" ObjectPlacement="0 -1 0 0 1 0 0 0 0 0 1 0 2432.62 3854.14 0 1" Tag="2372">
            <IfcPropertySet xlink:href="#2CHny$adzDKvcQyaVfPvOx"/>
            <IfcMaterialLayerSet xlink:href="#aaaaaaaaaaaaa"/>
            <IfcWallType xlink:href="#2CHny$adzDKvcQz5FfPvP8"/>
            <IfcPresentationLayerAssignment xlink:href="#A-WALL-____-OTLN"/>
</IfcWallStandardCase>
```

It is possible with IFCOpenshell  (ifcConvert to xml) ?

**Comment by aothms** [comment]
Hi, think it is a good idea. 

~~~xml
<IfcMaterial id="aaaaaaaaaaaaa">
     <Name>Default Wall</Name>
</IfcMaterial>
~~~

would probably become, to stick to the current way attributes are written

~~~xml
<IfcMaterial id="aaaaaaaaaaaaa" Name="Default Wall" />
~~~

It wouldn't be overly hard to add this to the current code base. But I'm short on time these days. If you want to implement it yourself we are here to help, otherwise it might take some time before I get to it.

**Comment by aothms** [comment]
~~~xml
<IfcMaterialLayerSetUsage id="IfcMaterialLayerSetUsage_283" LayerSetName="Compound Ceiling:Gypsum Board" LayerSetDirection="AXIS3" DirectionSense="NEGATIVE" OffsetFromReferenceLine="-0">
    <IfcMaterialLayer Name="Metal - Stud Layer" LayerThickness="0.045"/>
    <IfcMaterialLayer Name="Plasterboard" LayerThickness="0.012"/>
</IfcMaterialLayerSetUsage>
~~~

~~~xml
<IfcCovering id="3bXiCStxP6Fgxdej$yc5T8" Name="Compound Ceiling:Gypsum Board:187149" ObjectType="Compound Ceiling:Gypsum Board" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1" Tag="187149" PredefinedType="CEILING">
    <IfcPropertySet xlink:href="#3lyQME08z6te0feblfjn_M"/>
    <IfcPropertySet xlink:href="#1bGco9JNLDdgabR6_XjU4I"/>
    <IfcPropertySet xlink:href="#3SZTw1sCL6$QjlZyXnYJ6H"/>
    <IfcPropertySet xlink:href="#3zRodmdW16t8c25d5URIMm"/>
    <IfcPropertySet xlink:href="#3JfJUqPLv7oP6eOA39$HLK"/>
    <IfcPropertySet xlink:href="#22inZ6$Nv8GwtErxlDx3Fp"/>
    <IfcPropertySet xlink:href="#0lgIswTCL9Sfg1XXTXzxDd"/>
    <IfcPropertySet xlink:href="#0u5h3RcoXFGeniUQonanTq"/>
    <IfcPropertySet xlink:href="#3SVTOf1YL9QQuNxrONV0_1"/>
    <IfcPresentationLayerAssignment xlink:href="#A-CLNG-SUSP"/>
    <IfcMaterialLayerSetUsage xlink:href="#IfcMaterialLayerSetUsage_283"/>
</IfcCovering>
~~~
