### ISSUE TITLE
Exclusion of BoundingBoxes in IfcConvert

### ISSUE THREAD

**Issue by bdaniere** [IfcOpenShell/IfcOpenShell#2044]
Hi,
I have a problem with IfcConvert 0.7.0 (OCC 7.5.3) on some models.

If an IfcObject has an IfcShapeRepresentation of type "BoundingBox" (in addition to another representation, of type "SweptSolid" for example): both representations will be taken into account in the result of the conversion.  The bounding box will completely hide the geometry of the resulting object.

I'm not sure if this is a bug (because both representations are present in these IFC files) but opening them on different BIM software gives me a result without the BoundingBox representation.

Currently, the only effective solution I could put in place is to remove the problematic representations before launching a conversion 

```
for bbox in [
        rep
        for rep in ifcwrap.ifc.by_type("IfcShapeRepresentation")
        if rep.RepresentationType == "BoundingBox"
    ]:

        ifc_file.remove(bbox)
    ifc_file.write(ifc_path)

```

Is there a "cleaner" way to ignore some IfcProducts (by filtering on their Representation.Representations) ?

**Comment by Moult** [comment]
You can use set_context_ids() in the iterator to specify exactly what geometry contexts you want to approve, but I'm not sure if IfcConvert exposes this.

**Comment by aothms** [comment]
I'm also not against a general purpose flag or something to filter out IfcBoundingBox. Could even be enabled by default if you ask me, because I can't see lot of use for reading bounding boxes unless you're doing something fairly advanced. Would you be interested in wiring up the code for that @bdaniere?

**Comment by bdaniere** [comment]
It would have been a great pleasure
However, I have no skills in c++.

**Comment by theRealSuperMario** [comment]
Having the same problem here. Any thoughts on when it might be addressed?

**Comment by aothms** [comment]
Sorry for the delay on this. With the latest commit the default is now to exclude bounding boxes. There is an option --keep-bounding-boxes to retain the old behaviour. This is implemented by actually going into the file in memory and removing the occurences of bounding boxes as it saves the trouble of propagating the settings all the way through the code base and is authored in a way to prevent error messages.
