### ISSUE TITLE
BB: remove 'remove style'?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2047]
Similar to [this](https://github.com/IfcOpenShell/IfcOpenShell/commit/7ee589cfc2e975533db481af318f21187ce64127) commit, should one of these be deleted as well?
![image](https://user-images.githubusercontent.com/507113/154197745-1b99922d-9d76-4f23-9f31-be4af3aca34d.png)

**Comment by Moult** [comment]
No, because a style can exist independent of a material, and vice versa, it's not like a 1:1 IFC element : Blender Object.
