### ISSUE TITLE
BlenderBIM: relative path to IFC Links and IFC Project Library

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#2049]
This is related to this [previous issue](https://github.com/IfcOpenShell/IfcOpenShell/issues/1750).
It would be nice to have the same functionality for links and libraries as well.

This was implemented for IFC Project. To change to relative path you have to manually change the path text field.
![image](https://user-images.githubusercontent.com/57102715/154345175-f239f724-2908-45f1-b928-aecce830a87c.png)

But for IFC Links and IFC Project Library it is not possible to edit the path field.
![image](https://user-images.githubusercontent.com/57102715/154345225-d2220812-ee39-4157-91eb-451ae8ba2104.png)

**Comment by brunoperdigao** [comment]
Hi @Moult, does this look like an issue that a beginner could solve? I saw the code and I got some idea where things are, but not sure. Would love to contribute.

**Comment by Moult** [comment]
Potentially, I can't remember the code in this part. But I generally try to make everything something a beginner can solve (apart from geometry which is obviously a nasty part of any codebase). My advice would be to start at the project/operator.py then look around from there.

**Comment by brunoperdigao** [comment]
This is what I managed so far:

I made these changes in `module\project\ui.py`. 
![image](https://user-images.githubusercontent.com/57102715/157291762-b4810252-af3b-41ed-8b0c-f4d76d8b2d26.png)


Basically, the file path was showing as label. Now when the item is loaded it shows as label, otherwise it shows as a property, so it is editable:
![GIF 08-03-2022 14-27-01](https://user-images.githubusercontent.com/57102715/157292319-7d2bb625-f698-4802-a20e-634890d78f85.gif)

**Comment by brunoperdigao** [comment]
I started these changes to enable relative path, and it is working so far:
![image](https://user-images.githubusercontent.com/57102715/157292912-4aa02299-9ebe-4c56-83dd-184ce943187c.png)

However, I have to update this to the `unload_link` operator, that's not working properly. I guess it's the same process, just didn't had the time, I realized that later. 
![GIF 08-03-2022 14-32-14](https://user-images.githubusercontent.com/57102715/157293420-822b09a0-5896-42cb-8268-0eed0cd4eb09.gif)

**Comment by brunoperdigao** [comment]
@Moult Noob question. I am trying to create a PR for this issue, and I also have a tiny commit related to this #2055. Should I make them separated PR's?

**Comment by Moult** [comment]
Cheers, sorry for the delay I was not available for hacking but your code was great and yes in the future I'm happy for a PR either merged or separate up to you :)

A note you don't need to manually edit the path, there is a checkbox you can enable "Use Relative Path" when browsing for a while. I've added that checkbox in for this dialog box too.

**Comment by brunoperdigao** [comment]
Hi @Moult, I was testing this in the version 0.0.220321 in Blender 3.1 and I am getting two different errors.
If I check the "Use Relative Path" option before linking it show this error:
```Python: Traceback (most recent call last):
  File "C:\Users\Bruno\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 620, in execute
    filepath = os.path.relpath(filepath, bpy.path.abspath("//"))
  File "D:\Programas\Blender Foundation\Blender 3.1\3.1\python\lib\ntpath.py", line 718, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'D:'

location: <unknown location>:-1

```
If I uncheck it and then manually edit the path to relative I get this error:
```Python: Traceback (most recent call last):
  File "C:\Users\Bruno\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 678, in execute
    with bpy.data.libraries.load(self.filepath, link=True) as (data_from, data_to):
OSError: load:  failed to open blend file

location: <unknown location>:-1
```
