### ISSUE TITLE
BB: small objects missing on import

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2053]
file: https://github.com/OpeningDesign/BIM_Objects/blob/e14b80573684f26940dc8542460103fa407e3f62/IFC_Objects/06%20-%20Wood%2C%20Plastics%2C%20and%20Composites/060523%20-%20W_P_C%20-%20Fastenings%20-%20IFC2X3.ifc

![image](https://user-images.githubusercontent.com/507113/154877368-5350a63a-aad3-45af-94ba-34a19f7307a4.png)
![2022-02-20_20-04-50_BIMcollab_ZOOM_(free_version)_060523_-_W_P_C_-_Fa_BIMcollab_ZOOM](https://user-images.githubusercontent.com/507113/154877372-8d9ec253-8ab3-4bd1-8f7b-07d8b0085587.png)

**Comment by Moult** [comment]
Seems to work here?

Potentially an OpenCascade specific version problem. Can you replicate this @aothms ?

![2022-02-21-135404_1330x810_scrot](https://user-images.githubusercontent.com/88302/154881488-a7ada88e-8336-417a-ac28-ad75cd07a20d.png)

**Comment by theoryshaw** [comment]
Hi, sorry it's over here. :)  The square ones.
![image](https://user-images.githubusercontent.com/507113/154889112-21c2362f-03ab-4279-af3d-31f5553b401c.png)

**Comment by Moult** [comment]
Ah OK, potentially a bug in IfcOpenShell but @aothms is the one who can confirm this.

My interpretation is that the nail head has a width of 0.006 feet (project units are set to feet), and the geometric tolerance of the file is set to 0.0001 so it _should_ work but apparently it doesn't.

Nevertheless if you edit the file to make the geometric tolerance even smaller such as 0.00001 like this:

```
#120= IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,0.00001,#117,#118);
```

Then you reimport it works for me. (note that you may need to purge your cache to see results - in Scene Properties > IFC Quality Control > IFC Debug > Purge HDF5 Cache)

**Comment by theoryshaw** [comment]
bingo that did it!  Had to purge. 
![image](https://user-images.githubusercontent.com/507113/154890230-6356424a-6aec-4c56-ae64-cca07dd7f7a1.png)

**Comment by Moult** [comment]
Cheers, let's keep this open so that we can narrow down any root cause.

**Comment by theoryshaw** [comment]
related to: https://github.com/Autodesk/revit-ifc/issues/426

**Comment by Moult** [comment]
Bump @aothms ?

**Comment by aothms** [comment]
Yes we have a "tolerance tolerance", so the tolerance calculated with is always higher than the one supplied in the file. It's probably an artefact from the past, it's not entirely sure if it's still necessary now that we do multiple boolean op attempts with different precision. You can disable this tolerance tolerance with the STRICT_TOLERANCE settings.

**Comment by Moult** [comment]
Awesome! I just tested with enabling STRICT_TOLERANCE and it indeed fixes the issue. Is there any side effect to keeping this globally enabled? Will it create problems elsewhere? I'm also happy to "wait and see" :)

**Comment by Moult** [comment]
I've found that enabling STRICT_TOLERANCE causes a strange bug when HDF5 caching is also enabled. Prior to the first cache creation, everything works as expected. Once a cache is created, upon subsequent iterations, the process seems to hang. Ideas?

**Comment by aothms** [comment]
@Moult I tested three scenarios in IfcConvert and all three worked as expected:

* delete cache, run with --cache --strict-tolerance, run with --cache --strict-tolerance -> ok
* delete cache, run with --cache, run with --cache -> ok
* delete cache, run with --cache, run with --cache --strict-tolerance -> Error: Settings mismatch (expected)

How can I reproduce your issue?

**Comment by Moult** [comment]
You're absolutely right, I forgot to enable the setting for the cache. I've now enabled it everywhere. Thanks so much!

This may cause hangs for users who have existing caches, so if that happens, purge the cache :)
