### ISSUE TITLE
BB: crash on limited dissolve

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2054]
files: https://www.dropbox.com/sh/lw5y201njd877ri/AAC7deW-exzVtsy1EOGBxpS0a?dl=1

video: https://www.dropbox.com/s/4iswdsyl7y2fn1q/2022-02-20_20-20-59.mp4?dl=0

**Comment by Moult** [comment]
I've got no idea why this is the case - potentially a Blender bug, not sure. Ping @ecke101 or @Gorgious56 who might be able to narrow it down.

If no response would you mind submitting a Blender bugreport and attach this .blend file? 
[crash-limited-dissolve.blend.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8105954/crash-limited-dissolve.blend.txt)

It contains just one object which you can select and press limited dissolve on.

Meanwhile, you can enable the built-in Blender 3D print add-on, select whatever meshes you want to limited dissolve, and prior to limited dissolve, go into the N properties sidebar, go into 3D-Print, and under "Clean Up" click "Make manifold". This will make them manifold solids (which they should be modeled in a manifold way to begin with, so in theory the input data is already pretty poor quality). Then limited dissolve won't crash (or at least didn't when I tested it).

**Comment by Gorgious56** [comment]
Where does this model come from ? At first glance there are a bunch of internal faces which is never good in a model :

![image](https://user-images.githubusercontent.com/25156105/154903307-0f7b874a-e1ea-4519-b290-d70c4894d971.png)

You can select all interior faces with Select > Select all by trait > Interior faces. After deleting the interior faces, there is no longer a CTD.

It's theoretically impossible to create illegal meshes in Blender (for instance, one of the faces references a vertex index which doesn't exist) but it is possible to circumvent it if the mesh was created via script. That includes importing from another file type which relies on addons written in python. Trying to do operations or undoing with CTRL Z usually results in a crash when Blender re-calculates the state of the mesh and finds out it is illegal.

So one could say it is a bug, but I'm 99% sure the developers will argue that this is a know limitation and you can't dissolve a face with 0 area, but it's worth trying to bring it to their attention.

In fact if you only delete the 3 culprit faces, the dissolve won't crash Blender :

![image](https://user-images.githubusercontent.com/25156105/154903919-581225d1-676c-4808-a61c-e95cce8ef8e8.png)

Btw now that I think of it, this mesh is illegal in the sense that it contains faces with only one edge. In the screenshot I selected 2 faces, but I also selected only 3 edges as you can see in the scene statistic : But there are at least 3 edges that are selected, and they are not contiguous. So something's fishy here !

![image](https://user-images.githubusercontent.com/25156105/154904055-8628d57c-1619-4cad-b4c3-7aaad3cd9c1a.png)

**Comment by theoryshaw** [comment]
Thanks @Gorgious56 for the breakdown. 
This was exported out from Revit.
