### ISSUE TITLE
BlenderBIM: Can't assing ifc class from "IfcContext" when working in IFC 2x3

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#2055]
Using versions 0.0.220210
To replicate this: 

- create an IFC 2x3 Project
- select an object > go to object properties > ifc object metadata > ifc class
- in "products" select "IfcContext". All the options disappears.
![BB-issue](https://user-images.githubusercontent.com/57102715/155046213-97d454c9-346f-48cc-b69b-d76b372d6612.gif)

**Comment by Moult** [comment]
This is also a good first issue if you'd like to contribute, basically IfcContext should never show for IFC2X3 as it was introduced in IFC4, so just find a way to omit it from the list of enumerations :)

**Comment by brunoperdigao** [comment]
@Moult Here is my take on this. I changed the file `bim\module\root\prop.py". It seems to be working.

![image](https://user-images.githubusercontent.com/57102715/157244208-1712df28-3454-4953-b08a-fd721e73925c.png)

**Comment by Moult** [comment]
Your solution is correct, however I decided to take the opportunity to refactor this into a data class, but indeed there was nothing wrong with your code :) Thanks so much and sorry for the delay!
