### ISSUE TITLE
BlenderBIM: Possible to Filter IFC based on "Phase" set in Revit?

### ISSUE THREAD

**Issue by garylzimmer** [IfcOpenShell/IfcOpenShell#2057]
I read around that this might be set to "LifecyclePhase" attribute, but I'm not 100% sure how to use the IFC Search feature or if this is something that can be searched and filtered by yet...

**Comment by Moult** [comment]
From memory Revit only ever exports one phase at a time which is annoying. But as long as you've got the common (or all, I forget) psets exported from Revit, you can find it in psets like Pset_WallCommon.Status

**Comment by Moult** [comment]
Is this solved? Revit only exports one phase at a time so there's not much filtering we can do on our end.
