### ISSUE TITLE
BB: automatically create a duplicate class when a mesh is 'seperated' from an object

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2058]
Would be nice, when you separate a mesh from an object, it creates a new GUID with the same class.

**Comment by Moult** [comment]
Yeah :( this is one of those many ways Blender can create new objects - we can't yet hook into all of them, and it's too expensive to check every time. Maybe it auto fixes on export?

**Comment by theoryshaw** [comment]
i suppose the other work around too, would be to duplicate the object first, then delete used meshes.

**Comment by theoryshaw** [comment]
nice 
https://github.com/IfcOpenShell/IfcOpenShell/commit/38f5468f19dbdf2cb42e7de73e941a61175966be
