### ISSUE TITLE
BB: a little script that you can bring up with your quick favorites that both saves and exports the file with one click

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2059]
a little script that you can bring up with your 'quick favorites' that both saves and exports the file with one click.

I export out constantly, to ward off, or catch, corrupted IFC files, as i'm modeling. 

Although I might export out a lot, if the blender crashes, which it does quite frequent, my Blender file is then out of date.

**Comment by Moult** [comment]
In Blender you can right click anything and assign to quick favourites, brought up by the "q" hotkey I think. Also, clicking on the file menu, then using alt hotkeys like "e, i" to (e)xport to (i)fc work quite well, or importing using "i, i" might help?

**Comment by theoryshaw** [comment]
yeah, i know about making quick favorites. but i export out a lot! :)
would nice if both save/export was one motion. :)

harks back to this conv. https://community.osarch.org/discussion/594/

**Comment by Moult** [comment]
By the way, save/export is one motion. The "save project" button in the project panel, which is equivalent to the export IFC button should also save your blend file. Does that solve this issue? You can always add it to quick favourites.

**Comment by theoryshaw** [comment]
oh, very cool.  This works nicely!

**Comment by theoryshaw** [comment]
for passerbys...
it saves and exports at the same time...
![2022-04-14_22-34-22_Blender_blender](https://user-images.githubusercontent.com/507113/163514062-3821093a-25a6-4611-a01a-da0642105766.gif)
