### ISSUE TITLE
[IfcConvert] IfcTask in the xml file

### ISSUE THREAD

**Issue by christt105** [IfcOpenShell/IfcOpenShell#2062]
Hi,
I am using IfcConvert to convert into .glb and .xml, and I want to know if there is a way to get the IfcTasks in the xml file.

Thanks!

**Comment by aothms** [comment]
Currently not. It's also not something I'm extensively familiar with. What kind of output would you expect in XML? Are you interested in working on this (with some assistance from the community if needed)?

**Comment by christt105** [comment]
Maybe. Not in the near future but I can give it a try. I don't have too much experience in IFC in general.

**Comment by Moult** [comment]
@christt105 have you considered exporting IFC to P6 XML or MS Project XML, then using that XML instead? The GUIDs will be retained.

**Comment by aothms** [comment]
i.e for ex https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifc4d/ifc4d/ifc2p6.py

**Comment by christt105** [comment]
Thanks! I would prefer to have it inside the XML with the IfcConvert, as I am currently using it with Unity and C#, but it is a nice solution for now.
