### ISSUE TITLE
Missing parts when using ifcopenshell.geom to extract vertices and faces

### ISSUE THREAD

**Issue by kongsgard** [IfcOpenShell/IfcOpenShell#2065]
I tried to follow the instructions given in this code example (the one using the geometry iterator):
https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#Geometry_processing

I've also added the following settings:
```
settings.set(settings.USE_WORLD_COORDS, True)
settings.set(settings.APPLY_DEFAULT_MATERIALS, True)
settings.set(settings.WELD_VERTICES, False)
```

This seems to parse and process most IFC files, but some geometry is missing.
For instance, for the [wall-with-opening-and-window.ifc](https://github.com/buildingSMART/Sample-Test-Files/blob/master/IFC%204.0/BuildingSMARTSpec/wall-with-opening-and-window.ifc) sample test file, the returned geometry for the wall seems to only be the window and the window frame, but not the wall itself.

Are there any settings that needs to be enabled for correct parsing of geometry?
Using ifcconvert.exe converts these files to meshes as expected.

**Comment by aothms** [comment]
What is your complete script? There's probably a mistake somewhere.

**Comment by kongsgard** [comment]
```
try:
    ifc_file = ifcopenshell.open(ifc_path)
except:
    print(ifcopenshell.get_log())
else:
    settings = geom.settings()
    settings.set(settings.USE_WORLD_COORDS, True)
    settings.set(settings.APPLY_DEFAULT_MATERIALS, True)
    settings.set(settings.WELD_VERTICES, False)
    iterator = geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
    if iterator.initialize():
        while iterator.next():
            shape = iterator.get()
            element = ifc_file.by_guid(shape.guid)
```

(The issue remains with all the `setting.set(...)` lines removed, and then the code would be equal to that provided in the wiki.)

The issue seems to be with the iterator, as the two elements returned are `IfcOpeningElement` and `IfcWindow`. I would expect `IfcWall` instead of `IfcOpeningElement`.

**Comment by kongsgard** [comment]
If I change the iterator to 
```
elements = ifc_file.by_type("IfcBuildingElement")
iterator = geom.iterator(
    settings, ifc_file, num_threads=multiprocessing.cpu_count(), include=elements
)
```
where elements is a list of `IfcWallStandardCase` and `IfcWindow` it seems like `IfcWallStandardCase` is skipped in the iterator.
`IfcWall` also seems to be skipped when `elements = ifc_file.by_type("IfcWall")`.

**Comment by kongsgard** [comment]
That seems to be it. Thanks!
