### ISSUE TITLE
Error trying to export IFC to CSV

### ISSUE THREAD

**Issue by LoRue656Plus10** [IfcOpenShell/IfcOpenShell#2069]
Hi There,

Getting an error when trying to export IFC to CSV:

![image](https://user-images.githubusercontent.com/68364429/155861961-b5630b73-b67d-4c9a-b4f1-5064d0a7093a.png)

The IFC model is from the buildingSMART example [repository](https://github.com/buildingSMART/Sample-Test-Files/blob/master/IFC%202x3/Medical-Dental%20Clinic/Clinic_Architectural.ifc) and is 2x3

Also, I had an error when first installing BB, but after completely uninstalling/reinstalling Blender & BB, it showed up.
Feel free to reach out if you have questions. 

Thanks,

Loren

**Comment by Moult** [comment]
Glad you got it sorted! The reason is because the query string is blank :) We really need to put more descriptive errors or prevent these things.

**Comment by LoRue656Plus10** [comment]
Hi Dion,

Yes, and also it is good to pay more attention to the video tutorial!
 Once I get more familiar with your addon, I will circle back and hopefully
help in some way.
Good stuff!

Best,

Loren
