### ISSUE TITLE
Building ifcopenshell fails on VS2017 when VS2022 is present

### ISSUE THREAD

**Issue by ssg3d** [IfcOpenShell/IfcOpenShell#2070]
From within D: in Visual Studio 2017 Developer Command Prompt v15.9.44, I run:
```
git clone --recursive https://github.com/IfcOpenShell/IfcOpenshell.git ifcopenshell
cd ifcopenshell\win
build-deps.cmd vs2017-x64
```
I get the following error:
```
Build started at 15:02:01.64.

Cloning mpir into D:\ifcopenshell\_deps\mpir.
Cloning into 'D:\ifcopenshell\_deps\mpir'...
remote: Enumerating objects: 55517, done.
remote: Counting objects: 100% (461/461), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 55517 (delta 219), reused 439 (delta 208), pack-reused 55056
Receiving objects: 100% (55517/55517), 20.53 MiB | 13.22 MiB/s, done.
Resolving deltas: 100% (37529/37529), done.
Updating files: 100% (3986/3986), done.
HEAD is now at 33be9007 fix bug in mpz_n_pow_ui that failed for exponents longer than 32 bits
\msbuild.exe /p:Platform=x64 /p:Configuration=Release /p:"WindowsLIB0SDKLIB0Version=" .\lib_mpir_gc\lib_mpir_gc.vcxproj
'\msbuild.exe' is not recognized as an internal or external command,
operable program or batch file.
ERROR: msbuild failed for main project with exit code 9009

An error occurred

Build ended at 15:02:09.72. Time elapsed 0:00:08.08.
```

**Comment by ssg3d** [comment]
Uninstalling VS2022, rebooting and rebuilding on 2017 works.

**Comment by Moult** [comment]
So is this fixed? :)

**Comment by ssg3d** [comment]
No it is not fixed. I am trying to move to VS2022 and before I uninstall 2017 I'd like to see if this works on 2022. And it does not work if both are installed. And I dont want to uninstall VS2017 because there are other software that dont yet support VS2022. So it would be nice if this was fixed, please.

**Comment by ssg3d** [comment]
I got hold of another machine that had 2019, installed 2022 and tried to build using 2022 console, again failure. I uninstalled 2019 and tried again, but again failure. Looks like I cant get it to work on 2022. I can provide detailed logs if anyone wishes to fix this.

**Comment by Undianer** [comment]
I got this issue using VS 2019 latest update. I have no other Visual Studio installed on my machine. Any hints what to do?

**Comment by ssg3d** [comment]
If VS2019 is the only version present, it worked for me just fine when I tested it a few days ago. I didn't check what update it is on, will update to latest 2019 and check.

**Comment by aothms** [comment]
Sorry for the delay in replying. It's on my list. I have created and configured VMs to test, etc. It's just a bit time consuming. I'll get back to you on this.

**Comment by ssg3d** [comment]
Hi @aothms, any updates on this one? To make it simple, I am hoping to compile on VS 2022 only, compatibility with other VSs is secondary.

**Comment by ssg3d** [comment]
Am closing this issue, will open a new one specific to VS2022.
