### ISSUE TITLE
IDS 0.5.10 schema

### ISSUE THREAD

**Issue by atomczak** [IfcOpenShell/IfcOpenShell#2071]
- [ ] add "measure"
- [ ] add "partOf" facet
- [ ] attribute facet (now its together with properties)
- [ ] update API documentation
- [ ] add instructions how to use IDS
- [ ] add tests of new features
- [ ] don't check requirements if fail on applicability

**Comment by atomczak** [comment]
@Moult, @aothms, how about we move IDS code to a separate folder in `src`, to separate it from core `ifcopenshell-python`? I'm also thinking about simplifying the `ids.py` by extracting parts of the code to dedicated files, like `reporting handlers` and maybe even `facets`?

**Comment by Moult** [comment]
I don't have an opinion either way - you know the code better than me and will know whether it is better placed as part of ifcopenshell-python or as a separate "util" :)

**Comment by aothms** [comment]
My preference would be a separate folder in ifcopenshell-python/ifcopenshell

That way it would still get automatically installed correctly when using ifcopenshell.

python modules work by putting an `__init__.py` in the folder. You can also make it executable by putting `__main__.py` into the folder. That way you can do both `import ifcopenshell.ids` and from the command line `python3 -m ifcopenshell.ids ...`.

**Comment by Moult** [comment]
Closing because this is all done now :D
