### ISSUE TITLE
get (list of)materials from IfcBuildingElement in C++

### ISSUE THREAD

**Issue by Fleakad** [IfcOpenShell/IfcOpenShell#2075]
Hi, I am trying to obtain the material/list of materials of an element.
I have seen some code in Python on how to do it, but I cannot make it work in C++
I can use `element->HasAssociations()` and I can see the size of it (which is >0), but I cannot access any information inside it.

How can I obtain the list of materials from and IfcBuildingElement?

Thanks a lot for the help

**Comment by Fleakad** [comment]
ohh thanks a lot!. That helps. Still not the final data that I want to obtain, but getting close.
if I output the content of `rel-as<IfcSchema::IfcRelAssociatesMaterial>()->RelatingMaterial()` using `->data().toString()` it outputs this:
**#946=IfcMaterialLayerSetUsage(#940,.AXIS2.,.NEGATIVE.,145.,$)**

that 940 is where the list of materials is referenced. I am adding the lines around there from the IFC file:
**#936= IFCMATERIALLAYER(#864,102.5,$,'Brick, Common',$,'Materials',$);**
**#937= IFCMATERIALLAYER(#884,75.,$,'Fiberglass Batt',$,'Materials',$);**
**#938= IFCMATERIALLAYER(#899,100.,$,'Concrete Masonry Units _Low Density',$,'Materials',$);**
**#939= IFCMATERIALLAYER(#921,12.5,$,'Plaster',$,'Materials',$);**
**#940= IFCMATERIALLAYERSET((#936,#937,#938,#939),'Basic Wall:Wall-Ext_102Bwk-75Ins-100LBlk-12P',$);**
**#946= IFCMATERIALLAYERSETUSAGE(#940,.AXIS2.,.NEGATIVE.,145.,$);**

Now the question is, from  `rel-as<IfcSchema::IfcRelAssociatesMaterial>()->RelatingMaterial()`, can I go to that list so I can obtain each of the materials in it?
I am trying with `rel->as<IfcSchema::IfcRelAssociatesMaterial>()->RelatingMaterial()->as<IfcSchema::IfcMaterialList>()`, but that is not working. I guess I need an intermediate step

**Comment by aothms** [comment]
Have a look at the schema

http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcRelAssociatesMaterial.htm#5.4.3.47.3-Attributes

RelatingMaterial is of type IfcMaterialSelect

So it could be any of these http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcMaterialSelect.htm

In your case for this particular element IfcMaterialLayerSetUsage not IfcMaterialList

**Comment by Fleakad** [comment]
ok ok, I get it.
Managed to get the list and the individual materials now.
Thanks a lot for you help, very helpful as usual
