### ISSUE TITLE
Not able to re-install BlenderBIM addon

### ISSUE THREAD

**Issue by kickus** [IfcOpenShell/IfcOpenShell#2076]
I was very inspired to test when I saw the video about section plane feature by BlenderBIM. 
https://www.youtube.com/watch?v=CPGFC566Lmc 
However, I've run into several problems - and this has also messed up my model.

1. I downloaded and installed the add-on, and activated it via Blender preferences (I think it was in Blender 3.0).  I struggled quite a while to find any new features, but finally I found the feature.
2. I worked with most of my model hidden, and I had a section plane active.
3. I was unable to remove the section plane, thereby I deleted the object (arrow) that I thought did the section
4. I noticed that the visual section cut still was active, and colored as it had been defined in the add-on
5. I tried to uninstall the addon
6. I tried to remove the addon
7. I noticed in my Blender Outliner that every object had an subitem called Section something.. I tried with removing them
8. I tried to re-enable the addon - that failed
9. I tried to re-install the addon - failed
10. Upgrade Blender --> 3.0.1., and then re-install addon. I'm not able to make the BlenderBIM appear in the Blender Preferences Addons anymore. 

All my objects in my model appear as cut in half (in Object mode). In Edit mode, I can see that all Vertices are ok. 

I did a lot of work with most of the objects hidden, before noticing the damage. Is there any trick to get the objects fully visible again?

<img width="557" alt="image" src="https://user-images.githubusercontent.com/6077094/156640821-190a2bd4-be34-459e-ae23-3caa44e12430.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/6077094/156640985-27ac2721-dfef-42a4-81e9-3f2208505fa2.png">

**Comment by Moult** [comment]
The section cut applies a material shader. As a solution you can edit your material settings, and you will see a new node group for a section cut. Just edit that group to override the nodes so that the input node goes straight to output.

However we should find the underlying error here - why you couldn't remove the section plane.

**Comment by kickus** [comment]
Thanks a lot for hint, that helped me to make my objects fully visible again.
Please let me know if I can help you with pinpointing problems related to removing section planes (or first I would need ability to re-enable the BlenderBIM)

**Comment by Gorgious56** [comment]
Usually if an addon fails to register, an error message is written in the system console. You can check if with Window > Toggle Systme Console. Can you copy/paste the code here ?

**Comment by kickus** [comment]
Under window I found only toggle fullscreen, but perhaps you mean this console output? 
<img width="885" alt="image" src="https://user-images.githubusercontent.com/6077094/157298791-c856d116-7d3b-47d1-a779-57afce3e2c34.png">

**Comment by Moult** [comment]
Sorry for the delay. The message sounds a little weird. You should be installing from a zip file, not an unzipped folder. If that doesn't make sense or things still don't work, can we organise a time to screenshare? I'm available during the Sydney timezone.

**Comment by kickus** [comment]
Thanks, this was obviously my fault. 
I don't know why I extracted the zip file..  now I'm able too re-install the addon without issues. 

I'll close this issue. I might open another if I'm able to reproduce the problem related to removing the section plane.
Thanks a lot!
