### ISSUE TITLE
Remove entity from file doesn't work well

### ISSUE THREAD

**Issue by FragColor** [IfcOpenShell/IfcOpenShell#208]
I would like to remove some entities from an IFC file but I've encountered an issue with some entities. To sum up, let's consider this entity :

`#256= IFCPROPERTYSINGLEVALUE('Keyname',$,IFCINTEGER(3),$);`

From the file, I was able to get the associated object as `IfcUtil::IfcBaseClass*`  and then called `file.removeEntity` on this object. The most part of the `removeEntity` function works well. However, near the end, the following lines throw an exception because of a `BOOST_ASSERT`  :

```
IfcEntityList::ptr entity_attributes = traverse(entity, 1);
for (IfcEntityList::it it = entity_attributes->begin(); it != entity_attributes->end(); ++it) {
    IfcUtil::IfcBaseClass* entity_attribute = *it;
        if (entity_attribute == entity) continue;
        entitiesByReference(entity_attribute->entity->id())->remove(entity);
        if (entitiesByReference(entity_attribute->entity->id())->filtered(weak_roots)->size() == 0) {
            deletion_queue.insert(entity_attribute);
    }
}
```

The first line creates a list of entity from attributes of the given entity. In this case, they are two entities in this list : the entity we want to remove and an entity based on `IfcInteger`. The first one is ignored by `if (entity_attribute == entity) continue;` but the second one isn't. The exception is thrown because of a bad use of `boost::shared_ptr` in `entitiesByReference(entity_attribute->entity->id())->remove(entity);` This issue appears because the entity based on `IfcInteger` isn't in the file by itself on a dedicated line (its id equals to 0).

My guess is `IfcEntityList::ptr()` isn't well initialized as it should be in :

```
IfcEntityList::ptr IfcFile::entitiesByReference(int t) {
	entities_by_ref_t::const_iterator it = byref.find(t);
	return (it == byref.end()) ? IfcEntityList::ptr() : it->second;
}
```

There are several fix I can pull request to help you if necessary. It's possible to fix this issue at different levels : from the pointer initialization to the call of `entitiesByReference` on an entity obviously not in the file. I don't have enough knowledge on the IFCOpenShell code yet to know what is an acceptable fix and what can break almost everything. Let me know what do you think.

**Comment by aothms** [comment]
Many thanks for the detailed investigations. Indeed the use of an unset smart pointer (`IfcEntityList::ptr()`) is error prone at best, but I decided to keep it in order not to affect any of trueness evaluation in other places of the code base.
