### ISSUE TITLE
[C++] convert single element to mesh and save it on disk

### ISSUE THREAD

**Issue by Fleakad** [IfcOpenShell/IfcOpenShell#2080]
Hi, I was wondering if given an element `IfcSchema::IfcBuildingElement* element` it can be converted to a mesh and save it to disk as an OBJ (the name would be the element's UID).
I know you can convert the entire ifc file using IfcConvert, but I don't see if you can do it from the code and for a single element inside the IFC

**Comment by aothms** [comment]
You can evaluate a single `IfcSchema::IfcBuildingElement* element` into a `IfcGeom::Element:BRepElement` using `IfcGeom::Kernel::convert(const IteratorSettings& settings, IfcUtil::IfcBaseClass* representation, IfcUtil::IfcBaseClass* product)`. Then convert to `IfcGeom::Kernel::TriangulationElement` using the constructor. Instantiate a `WaveFrontOBJSerializer` and call `write(IfcGeom::Kernel::TriangulationElement*)`

**Comment by Fleakad** [comment]
Thanks for the help.

This is what I put together so far:

```
IfcGeom::IteratorSettings settingsIterator;
settingsIterator.set(IfcGeom::IteratorSettings::DISABLE_TRIANGULATION, true);
auto convertedKernelElement = kernel.convert(settingsIterator, shapeRepresentation, element);
auto triElem = IfcGeom::TriangulationElement<double>(*convertedKernelElement);
boost::shared_ptr<WaveFrontOBJSerializer> serializer;
serializer->write(triElem);
```

but `serializer->write(triElem)` seems not to allow to pass the argument like that. I guess the error comes before that.
What is it that I am doing wrong here?

Also, can you change the path where the file is written?

**Comment by aothms** [comment]
`&triElem` it takes a pointer

**Comment by Fleakad** [comment]
Sorry, I don't understand the pointer part.
I add the `&` inside the write but it stills throws the error: _no instance of overloaded function "WaveFrontOBJSerializer::write" matches the argument list_

Here is the code again with the change:

```
IfcGeom::IteratorSettings settingsIterator;
settingsIterator.set(IfcGeom::IteratorSettings::DISABLE_TRIANGULATION, true);
auto convertedKernelElement = kernel.convert(settingsIterator, shapeRepresentation, element);
auto triElem = IfcGeom::TriangulationElement<double>(*convertedKernelElement);
boost::shared_ptr<WaveFrontOBJSerializer> serializer("./test.obj", "./prueba.mtl", SerializerSettings());
serializer->write(&triElem);
```

**Comment by Fleakad** [comment]
Is the problem because I am saying the type is `double` instead of `real_t` in `auto triElem = IfcGeom::TriangulationElement<double>(*convertedKernelElement);` ?

I tried to set it to real_t but the kernel returns a double object, so doesn't let me do it

**Comment by aothms** [comment]
I'm confused by this

~~~C++
boost::shared_ptr<WaveFrontOBJSerializer> serializer("./test.obj", "./prueba.mtl", SerializerSettings());
~~~

Does this work?

Did you try?

~~~C++
WaveFrontOBJSerializer serializer("./test.obj", "./prueba.mtl", SerializerSettings());
serializer.write(&triElem);
~~~

**Comment by Fleakad** [comment]
yup, it is the same _no instance of overloaded function "WaveFrontOBJSerializer::write" matches the argument list_ compilation error

**Comment by aothms** [comment]
That's strange. I just pasted the following code block in IfcConvert.cpp and it compiles fine.

~~~C++
	{
		IfcGeom::IteratorSettings settingsIterator;
		settingsIterator.set(IfcGeom::IteratorSettings::DISABLE_TRIANGULATION, true);
		IfcGeom::Kernel k;
		auto convertedKernelElement = k.convert(settingsIterator, nullptr, nullptr);
		IfcGeom::TriangulationElement<double> triElem(*convertedKernelElement);
		WaveFrontOBJSerializer serializer("./test.obj", "./prueba.mtl", SerializerSettings());
		serializer.write(&triElem);
	}
~~~

But you do have to construct `triElem` directly and not use the copy constructor (`auto triElem = ...`). Maybe that's the issue.

**Comment by Fleakad** [comment]
I have added the same includes into the class as in IfcConvert.cpp but still the same problem.

I think that the issue gets resolved if it is a `real_t` instead of `double`, so is there any way of making `k.convert(settingsIterator, nullptr, nullptr);` to return a `real_t` BRep instead of the `double` one?

**Comment by aothms** [comment]
You could define the type similar to what is done here real_t

**Comment by Fleakad** [comment]
sorry for the delay, I have been busy whit other things.

I have added the define, but it is the same problem.

The problem is that one object returns a double and the other is expecting a real_t. I don't see there is any template to be casted, converted, or be dependable of the input.

Is there any other way of getting the mesh and saving it on disk?

I have seen that in the new version of the library the objects are templated, but unfortunatelly, when I tried to compile the library and the dependencies again I got compilation errors in debug mode (I think it is something similar to #2096), so I would like to stay with the current version that I have.

**Comment by aothms** [comment]
Can you share your code somewhere? A typedef is just an alias. They are the same type. E.g the following code compiles fine. Maybe we're looking in the wrong direction.

~~~C++
typedef int my_int;
std::vector<int> a;
std::vector<my_int>& a_ref = a;
~~~

**Comment by Fleakad** [comment]
Here is the code I am using:

```
void convertToOBJ(IfcSchema::IfcBuildingElement* element)
{
	typedef double real_t;
	if (element->hasRepresentation())
	{
		IfcGeom::Kernel kernel;
		IfcSchema::IfcRepresentation::list::ptr representationsList = element->Representation()->Representations();

		for (const auto& shapeRepresentation : *representationsList)
		{
			// conversion settings
			IfcGeom::IteratorSettings settingsIterator;

			// return OpenCASCADE shape
			settingsIterator.set(IfcGeom::IteratorSettings::DISABLE_TRIANGULATION, true);

			// convert
			auto convertedKernelElement = kernel.convert(settingsIterator, shapeRepresentation, element);

			if (convertedKernelElement)
			{
				IfcGeom::TriangulationElement<real_t> triElem(*convertedKernelElement);
				
				WaveFrontOBJSerializer serializer("./test.obj", "./test.mtl", SerializerSettings());
				serializer.write(&triElem);
			}
		}
	}
}
```

I have tried with `typedef double real_t;` and `typedef float real_t;`, and both have problems. It is not that the typedef doesn't let it to compile, is the other objects that don't allow the types. For example, the `kernel.convert` returns a `IfcGeom::BRepElement<double, double>`, and I cannot cast it to something else, but `serializer.write(&triElem);` is expecting a `IfcGeom::TriangulationElement<float>`.
If I set everything to float, then the `kernel.convert()` doesn't compile, if I set everything to double, then the `serializer.write()` doesn't compile.
Remember, I am using 0.6 version.

**Comment by aothms** [comment]
The issue is that when you do

~~~C++
typedef double real_t;
~~~

local to your function definition it doesn't affect the definitions of the function prototypes from the included header files. You need to move the typedef all the way up in the file so that it comes before any includes. Alternatively, define this before any includes:

~~~C++
#define IFCCONVERT_DOUBLE_PRECISION
~~~

**Comment by aothms** [comment]
> IfcGeom::Kernel kernel;

Supply your file to the kernel constructor so that based on its schema it can pick the correct implementation and initialize project units https://ifcopenshell.github.io/docs/rst_files/class_ifc_geom_1_1_kernel.html#_CPPv4N7IfcGeom6Kernel6KernelEPN8IfcParse7IfcFileE

Maybe

~~~C++
public:
    Kernel(IfcParse::IfcFile *file_ = 0)
~~~

should be separated out into

~~~C++
protected:
    Kernel()
public:
    Kernel(IfcParse::IfcFile *file_)
~~~

Because the `Kernel()` constructor is really only supposed to be used in the concrete implementation which inherit from Kernel. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeom.h#L297
