### ISSUE TITLE
Blenderbim will not install on Blender 3.1.0

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2083]
Just upgraded to Blender 3.1.0 and I'm unable to install Blendebim
It loads, but when attempting to activate it produces this error:
![image](https://user-images.githubusercontent.com/78321676/157610836-bde8763f-e70a-47fd-af94-6639f50da183.png)

I've tried it with blenderbim-220309-py39-win & blenderbim-220221-py39-win with the same result

**Comment by Moult** [comment]
Yes correct it requires Python 3.10 version of IfcOpenShell. I _think_ the build bot has 3.10 listed as "3.1" so I just need to bundle it properly.

**Comment by benjamindahl** [comment]
Yes same issue here on macos. Installation of blenderbim-220309-py39-macos in Blender 3.0 worked flawlessly even on M1 Apple silicon but crashes on activation in Blender 3.1

**Comment by theoryshaw** [comment]
> Yes correct it requires Python 3.10 version of IfcOpenShell. I _think_ the build bot has 3.10 listed as "3.1" so I just need to bundle it properly.

I'm i looking in the wrong area? 
https://github.com/IfcOpenShell/IfcOpenBot/search?q=3.10.0

Or is that the locations to change it?

**Comment by brunopostle** [comment]
@theoryshaw It looks like IfcOpenBot is already configured to create the python 3.10 bindings (which it names '310'),

This [Makefile](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/Makefile) is used to assemble the blenderbim bundle, it needs to be modified to pull in 3.10 versions of some other libraries in addition to IfcOpenShell

**Comment by Moult** [comment]
OK a bit of progress on this one, if you check back in a day or so when the builds are auto-triggered you should find a Python 3.10 version available in https://github.com/IfcOpenShell/IfcOpenShell/releases

For now IfcClash won't work on Blender 3.1 yet. See open issue here: https://github.com/humanoid-path-planner/hpp-fcl/issues/272

When it's there, please let me know if it works, and if it's all good, we can do a stable release in the coming week.

**Comment by Moult** [comment]
So we've had a couple of success stories on 3.1 and hpp-fcl builds are now available so I've just added them so things should be working now :)

**Comment by Moult** [comment]
@Plae-Blue-Dot hey there! Great news! We're doing a fundraiser to try and raise 70USD per month (unfortunately yes, a recurring payment, not a one-off) to afford an Apple M1 buildserver which will provide regular builds for Apple M1 devices! If you're still keen, perhaps you can help us out maybe for the price of a cup of coffee or two per month?

Details are here: https://opencollective.com/opensourcebim/projects/apple-m1-build-server - looking forward to when we can provide this with your help!

**Comment by Plae-Blue-Dot** [comment]
Hey @Moult This sounds great! Unfortunately I cant commit to a monthly payment, part of the reason I am so keen for an opensource BIM platform. I don't use macs but it's a big blind spot for BIM programs which is why I think it's important, I made one time contribution! That's the most I can do at the moment, keep up the great work!

**Comment by Moult** [comment]
@Plae-Blue-Dot thank you so much! Every little bit counts. Don't worry, as you can see from the commits we're hard at work and not stopping anytime soon!
