### ISSUE TITLE
Error on export to IFC - "`NoneType` object has no attr..."

### ISSUE THREAD

**Issue by bspreen** [IfcOpenShell/IfcOpenShell#2084]
Problem behavior - export to IFC fails, throwing the following error: 
```
Python: Traceback (most recent call last):
  File "/Users/brookespreen/Library/Application Support/Blender/2.92/scripts/addons/blenderbim/bim/operator.py", line 99, in execute
    webbrowser.open("https://blenderbim.org/")
  File "/Users/brookespreen/Library/Application Support/Blender/2.92/scripts/addons/blenderbim/bim/export_ifc.py", line 18, in export
    
  File "/Users/brookespreen/Library/Application Support/Blender/2.92/scripts/addons/blenderbim/bim/export_ifc.py", line 46, in set_header
    if bpy.context.scene.BIMProjectProperties.is_authoring:
AttributeError: 'NoneType' object has no attribute 'wrapped_data'

location: <unknown location>:-1
```

Behavior was initially observed using IfcBlender. Replacing IfcBlender with BlenderBIM did not resolve the issue.
In both cases, the model was imported from another CAD format (tried with GLTF, OBJ, and DAE).

System info (saved when IfcBlender was still installed, prior to adding BlenderBIM) attached here...
[blender-system-info.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8222240/blender-system-info.txt)

**Comment by Moult** [comment]
"IfcBlender" is pretty old and does not support export - I would not advise using it unless you wanted a minimal import script.

This does not sound like a bug, it sounds like a user error.

I think you are assuming that IFC is just a file format that you can press "export" and it'll work. However, IFC is a bit special, it's not just another format like obj or dae etc that you can export. You need to first create a project, assign data types, and insert your objects into a "spatial hierarchy".

The traceback looks a bit weird, but it sounds as though you've somehow managed to trigger the "export" function without first creating a project. How did you manage this? Which button did you press?

**Comment by bspreen** [comment]
Thanks for taking a look!

IfcBlender did support export at some point. But I'm all for using a newer, better export method.

User error is a little harsh. IFC *can* store all this data that you mention, but I think this exceeds the minimum requirements for a valid file, no? We don't need the extra data - just a valid file that architecture software can import successfully. The geometry here is a component to be used in building models, not a separate project.

I imported the model, then exported to IFC (File -> Export -> IFC). Gotta say, this seems like a pretty basic workflow. If it is user error rather than a bug, it would be worthwhile to have more useful error message.

**Comment by Moult** [comment]
> IfcBlender did support export at some point.

A couple years back the BlenderBIM Add-on codebase was in a directory called "ifcblenderexport" which might've caused this confusion.

> User error is a little harsh. IFC can store all this data that you mention, but I think this exceeds the minimum requirements for a valid file, no?

Sorry, I didn't meant to be harsh, but an IFC project, a class, and some sort of spatial hierarchy actually is the minimum requirement in the BIM world, otherwise it won't export. In theory for a single component you could use an IFC project library plus a class and skip the spatial hierarchy but likely architecture software won't accept it since most are designed to read projects.

> If it is user error rather than a bug, it would be worthwhile to have more useful error message.

Yeah that's the bit I'm puzzled about. I'm assuming you imported an OBJ / glTF/ DAE / something, then you pressed export ... it should've actually blocked you from exporting with this error:

> Error: No IFC project is available for export - create or import a project first.

So I'm not quite sure how you managed to trigger this.

**Comment by Moult** [comment]
Oh, I see now:

> blenderbim (version: (0, 0, 210221), path: /Users/brookespreen/Library/Application Support/Blender/2.92/scripts/addons/blenderbim/__init__.py)

You're using a version that's a year old. Grab a Python 3.7 build from here: https://github.com/IfcOpenShell/IfcOpenShell/releases - they are daily builds so it may not be stable, but one of those builds will probably work.

**Comment by Moult** [comment]
This might also help :) https://blenderbim.org/blenderbim-tutorial.html

**Comment by bspreen** [comment]
Thanks for the tutorial link, and sorry for the delay!
