### ISSUE TITLE
ifcpatch rotating ifc

### ISSUE THREAD

**Issue by hzm74** [IfcOpenShell/IfcOpenShell#2089]
Hello, I'm using ifcpatch and the recipe OffSetObjectPlacements.py to move and rotate ifc's. This works nice (even complicated ifc's). But now I have a problem with a ifc with floor-elements. Not the whole ifc is turned and moved but all individual floor elements are individually turned and moved. See below picture. Why is this happening?

Complicated ifc's don't have this problem?!

![image](https://user-images.githubusercontent.com/58707700/158372636-065d78be-2303-4ab6-bf11-de2506dd64e0.jpeg)

Thnx in advanced.

**Comment by Moult** [comment]
Note there are two modes for offset object placement using the 5th argument. Can you try toggling it and see what happens?

**Comment by Moult** [comment]
Should be fixed with latest commit :)
