### ISSUE TITLE
Issue with entity creation

### ISSUE THREAD

**Issue by FragColor** [IfcOpenShell/IfcOpenShell#209]
Hello again !

After deleting entities from a file without a full success (see [https://github.com/IfcOpenShell/IfcOpenShell/issues/208](https://github.com/IfcOpenShell/IfcOpenShell/issues/208)), I would like to add some of them. Unfortunately, it wasn't a success too.

Let's sum up once again : I would like to create a `IfcPropertySingleValue` using `IfcPropertySingleValue (std::string v1_Name, boost::optional< std::string > v2_Description, IfcValue* v3_NominalValue, IfcUnit* v4_Unit)` in order to link it with a `IfcPropertySet` and then with a `IfcRelDefinesByProperties`.

As my `IfcPropertySingleValue` is a `string`, it seems correct to use a `IfcLabel` as `IfcValue` and no `IfcUnit`. However, I have to use a `IfcUnit` because it is mandatory (shouln't it be optional ?). The problem is that there is no instantiable `IfcUnit`... As `IfcUnit` is `IfcBaseClass` by definition (`typedef IfcUtil::IfcBaseClass IfcUnit;`) I can pick almost everything to fill my `IfcPropertySingleValue` but, not surprisingly, it exports something invalid such as `#1414=IFCPROPERTYSINGLEVALUE('',$,IFCLABEL('Test'),IFCLABEL(''));` where I put an `IfcLabel` as `IfcUnit` just to be able to compil and test.

What do you think ? I may have missed something.

**Comment by FragColor** [comment]
I solved it this morning. I had done so much Javascript these last years that I didn't remember I can use `NULL` as a valid `IfcUnit` pointer.

Sorry :)

**Comment by aothms** [comment]
Well, yeah no worries. I added an example [1] to IfcOpenHouse to illustrate this a bit.

So, these are actually two separate things that hopefully will be addressed at some point. Both scheduled for 0.6:
- No C++ types generated for EXPRESS SELECT types. Just a typedef to the most general abstract class. Using `boost::variant` would be reasonable first step.
- Unclear function signatures for optional pointer types. Optional scalar types are wrapped in a `boost::optional`, but attributes of type entity are not. This creates an unfortunate distinction between attributes being set as null with either `boost::none` or {`0`, `NULL`, `nullptr`}.

[1] https://github.com/IfcOpenShell/IfcOpenShell/commit/d34c3b4b20c65e7856e0ecad649487b950ce45dc#diff-6017059461ea51ae44daa8a8df4b6a42R268
