### ISSUE TITLE
BlenderBIM add-on does not install under macOS arm64 architecture

### ISSUE THREAD

**Issue by dirkolbrich** [IfcOpenShell/IfcOpenShell#2090]
The BlenderBIM add-on is compiled for macOS only for the x86-64 version (Intel Mac), not for the Mac M1 arm64 chips.
The installation was tried with the `blenderbim-220315-py310-macos.zip` release and Blender 3.1.0 / arm64 version.

(sorry for the image, could not copy the error message as text in the Blender -> Preferences -> Add-ons window)

<img width="2202" alt="Bildschirmfoto 2022-03-15 um 14 43 48" src="https://user-images.githubusercontent.com/3765119/158391544-dda17086-271a-43a3-b182-34c74fb76ca1.png">

Maybe related to [Blenderbim will not install on Blender 3.1.0 #2083](https://github.com/IfcOpenShell/IfcOpenShell/issues/2083)?

**Comment by benjamindahl** [comment]
Hey, please look here for complete information about building blenderbim for arm64 on Apple M1 silicon.
#1975

**Comment by Moult** [comment]
Hey @dirkolbrich ! Indeed at this moment you'll need to compile it yourself for arm as @benjamindahl has suggested. Maybe with some money for Mac hardware and time, @aothms might be able to provide IfcOpenShell builds for arm, but for now, the solution is simply to compile it yourself :(

**Comment by dirkolbrich** [comment]
Thank you for the hints. I'm no stranger to compile complex C++/Python projects on macOS arm64 system using Homebrew for dependencies managment (FreeCAD 😏), but this is above my abilities.

I tried to compile from source according to the description in the `readme.md` and the description in https://github.com/IfcOpenShell/IfcOpenShell/issues/1975, but got stuck on activating the add-in.

```zsh
# installing dependencies, most of it was already on the system anyways
# note the use of a versioned bottle for occ
brew install boost swig cmake ftgl cgal gmp libaec opencascade@7.5.3

# clone IfcOpenShell, switch to the source folder and create a build subfolder
git clone --recurse-submodules https://github.com/IfcOpenShell/IfcOpenShell.git
cd IfcOpenShell 
mkdir build && cd build

# prepare cmake - note the changed path to occ bottled version
cmake ../cmake -DOCC_LIBRARY_DIR=/opt/homebrew/lib/ \
      -DOCC_INCLUDE_DIR=/opt/homebrew/Cellar/opencascade@7.5.3/7.5.3/include/opencascade/ \
      -DCOLLADA_SUPPORT=OFF \
      -DCGAL_INCLUDE_DIR=/opt/homebrew/include/ \
      -DGMP_LIBRARY_DIR=/opt/homebrew/lib/ \
      -DMPFR_LIBRARY_DIR=/opt/homebrew/lib/ \
      -DHDF5_SUPPORT=OFF

# prepare make
export CXXFLAGS="$CXXFLAGS -Wl,-flat_namespace,-undefined,suppress"
export CFLAGS="$CFLAGS -Wl,-flat_namespace,-undefined,suppress"
export LDFLAGS="$LDFLAGS -Wl,-flat_namespace,-undefined,suppress"

# build and install
make -j10 -lboost_options
sudo make install
```

I installed the latest release `blenderbim-220316-py310-macos.zip` (this is the x86-64 version), closed Blender without activating this add-in and copied the files from `/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ifcopenshell` (this is the path info given by `sudo make install`) to
` ~/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell`

and I changed line 42 in `~/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/bim/module/drawing/operator.py` according to https://github.com/IfcOpenShell/IfcOpenShell/issues/1975#issuecomment-1067710793 

Start-up Blender again, activation the BlenderBIM add-in results in the following error:

<img width="1333" alt="Bildschirmfoto 2022-03-16 um 12 58 47" src="https://user-images.githubusercontent.com/3765119/158585177-e833d8a0-ed14-417d-b502-dc6842df3930.png">

So, not working and I don't understand why. That makes me 😢 Anyways, keep up the good work and I hope there will be an ARM64 compatible version in the future.

---
Note:
Using Opencascade v7.6.1 (latest Homebrew version) results in an error as mentioned in the beginning of the issue description https://github.com/IfcOpenShell/IfcOpenShell/issues/1975. I switched back to open cascade v7.5.3, but you really should consider to make IfcOpenShell work with occ v7.6, as this version added compilation on arm64 as per the [occ changelog](https://tracker.dev.opencascade.org/changelog_page.php).

**Comment by aothms** [comment]
The error

> Symbol not found in flat namespace '_PyClass_Type'

seems to suggest there is a version mismatch between the python version compiled against and the python 3.10 used in blender.

> # prepare cmake - note the changed path to occ bottled version
> cmake ../cmake -DOCC_LIBRARY_DIR=/opt/homebrew/lib/ \
>       -DOCC_INCLUDE_DIR=/opt/homebrew/Cellar/opencascade@7.5.3/7.5.3/include/opencascade/ \
>       -DCOLLADA_SUPPORT=OFF \
>       -DCGAL_INCLUDE_DIR=/opt/homebrew/include/ \
>       -DGMP_LIBRARY_DIR=/opt/homebrew/lib/ \
>       -DMPFR_LIBRARY_DIR=/opt/homebrew/lib/ \
>       -DHDF5_SUPPORT=OFF

I also don't see you selecting a Python version here.

@benjamindahl used 

> -DPYTHON_EXECUTABLE=~/.pyenv/versions/3.9.9/bin/python3.9 \
> -DPYTHON_INCLUDE_DIR=~/.pyenv/versions/3.9.9/include/python3.9/ \
> -DPYTHON_LIBRARY=~/.pyenv/versions/3.9.9/lib/libpython3.9.a \

installed through pyenv. In your case I guess you need to select a python 3.10 version.

**Comment by dirkolbrich** [comment]
Good tip. You are partially right.
If Python@3.10 is installed via Homebrew, it is automatically linked to `$PATH`. Meaning, the preparing `cmake` command identifies the correct Python executable version with `-- Found PythonInterp: /opt/homebrew/bin/python3.10 (found version "3.10.2")`, see the cmake report:

```zsh
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:28 (cmake_policy):
  The OLD behavior for policy CMP0078 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- BINDIR: bin
-- INCLUDEDIR: include
-- LIBDIR: lib
-- Found LibXml2: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libxml2.tbd (found version "2.9.4")
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: system program_options regex thread date_time
-- Boost include files found in /opt/homebrew/include
-- Boost libraries found in /opt/homebrew/lib
-- Looking for Open CASCADE include files in: /opt/homebrew/Cellar/opencascade@7.5.3/7.5.3/include/opencascade
-- Looking for Open CASCADE library files in: /opt/homebrew/lib
-- Required Open Cascade Library files found
-- Found Threads: TRUE
-- Found SWIG: /opt/homebrew/bin/swig (found version "4.0.2")
-- Found PythonLibs: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libpython2.7.tbd (found version "2.7.18")
-- Found PythonInterp: /opt/homebrew/bin/python3.10 (found version "3.10.2")
CMake Deprecation Warning at /Users/dirkolbrich/Blender/IfcOpenShell/src/svgfill/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at /Users/dirkolbrich/Blender/IfcOpenShell/src/svgfill/CMakeLists.txt:6 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for CGAL include files in: /opt/homebrew/include
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0")
-- Boost include files found in /opt/homebrew/include
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dirkolbrich/Blender/IfcOpenShell/build
```


*BUT* checking the `CMakeCache.txt` file shows that the `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARY` are mismatched to the system installed Python 2.7 version:

```zsh
//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/opt/homebrew/bin/python3.10

//Path to a file.
PYTHON_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/python2.7

//Path to a library.
PYTHON_LIBRARY:FILEPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libpython2.7.tbd

//Path to a library.
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND
```

Will try another approach with the specified paths.

**Comment by dirkolbrich** [comment]
Nope, didn't worked either. With corrected Python paths I get the following error after activating the BlenderBIM add-in:

```zsh
Traceback (most recent call last):
  File "/Users/dirkolbrich/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/__init__.py", line 43, in <module>
    from . import ifcopenshell_wrapper
  File "/Users/dirkolbrich/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: dlopen(/Users/dirkolbrich/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/_ifcopenshell_wrapper.so, 0x0002): symbol not found in flat namespace '__ZN14Approx_Curve3dC1ERKN11opencascade6handleI16Adaptor3d_HCurveEEd13GeomAbs_Shapeii'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/dirkolbrich/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/__init__.py", line 39, in <module>
    import blenderbim.bim
  File "/Users/dirkolbrich/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/bim/__init__.py", line 21, in <module>
    from . import handler, ui, prop, operator, helper
  File "/Users/dirkolbrich/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/bim/handler.py", line 22, in <module>
    import ifcopenshell.api.owner.settings
  File "/Users/dirkolbrich/Library/Application Support/Blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/__init__.py", line 51, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'darwin/64bit/python3.10'
```

**Comment by benjamindahl** [comment]
Maybe it helps, if I share my latest working cmake settings:
And you need to check if clang builds for the arm64 target (maybe you need to reset Xcode Command Line Tools: xcode-select --reset)

from the ifcopenshell base folder
```
cmake -S cmake -B build -D PYTHON_EXECUTABLE=~/.pyenv/versions/3.10.2/bin/python3.10 -D PYTHON_INCLUDE_DIR=~/.pyenv/versions/3.10.2/include/python3.10/ -D PYTHON_LIBRARY=~/.pyenv/versions/3.10.2/lib/libpython3.10.dylib -D OCC_LIBRARY_DIR="/opt/homebrew/lib/" -D OCC_INCLUDE_DIR=/opt/homebrew/include/opencascade/ -D COLLADA_SUPPORT=0 -D CGAL_INCLUDE_DIR=/opt/homebrew/include/ -D GMP_LIBRARY_DIR=/opt/homebrew/lib/ -D MPFR_LIBRARY_DIR=/opt/homebrew/lib/ -D HDF5_SUPPORT=Off

```

Build on macOS 12.2.1

clang --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
benny@mbp1421 ~ %

**Comment by aothms** [comment]
Yes PythonInterp was correct, but not PythonLibs

> -- Found PythonLibs: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libpython2.7.tbd (found version "2.7.18")
> -- Found PythonInterp: /opt/homebrew/bin/python3.10 (found version "3.10.2")

CMake isn't always as smart as it could be I...

> symbol not found in flat namespace '__ZN14Approx_Curve3dC1ERKN11opencascade6handleI16Adaptor3d_HCurveEEd13GeomAbs_Shapeii'

That seems to hint at an issue with open cascade. Probably a mismatch between the header versions and the library.

> -DOCC_LIBRARY_DIR=/opt/homebrew/lib/ \
> -DOCC_INCLUDE_DIR=/opt/homebrew/Cellar/opencascade@7.5.3/7.5.3/include/opencascade/ \

^ are these the same version?

**Comment by dirkolbrich** [comment]
@aothms good catch. I thought about this too after a good nights sleep.
The OOC libraries specified under `/opt/homebrew/lib/` where indeed from the conflicting installed v7.6 OCC version. I changed the path accordingly to point to the v7.5.3 libraries.

The cmake command look like this now:

```zsh
cmake ../cmake \
    -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3.10 \
    -DPYTHON_INCLUDE_DIR=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10/ \
    -DPYTHON_LIBRARY=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib \
    -DOCC_LIBRARY_DIR=/opt/homebrew/opt/opencascade@7.5.3/lib/ \
    -DOCC_INCLUDE_DIR=/opt/homebrew/opt/opencascade@7.5.3/include/opencascade/ \
    -DCOLLADA_SUPPORT=OFF \
    -DCGAL_INCLUDE_DIR=/opt/homebrew/include/ \
    -DGMP_LIBRARY_DIR=/opt/homebrew/lib/ \
    -DMPFR_LIBRARY_DIR=/opt/homebrew/lib/ \
    -DHDF5_SUPPORT=OFF
```

Everything else stayed the same. And it works. Activation of the add-in gives me a nice little tick on the checkbox. 😄 
Thanks for the help.

**Comment by aothms** [comment]
@emadpres I'm not the one in this thread with an arm build, maybe direct your question to somebody else. But as mentioned earlier. The resulting build from this process is not very portable, it's easier to simply follow the procedure outlined in this thread.

**Comment by emadpres** [comment]
Thanks, @aothms for your reply. I managed to build the project for M1 and I left [a comment](https://github.com/IfcOpenShell/IfcOpenShell/issues/1975#issuecomment-1143232540) describing the build process in #1975

**Comment by emadpres** [comment]
@iffies  Here is what I got at `/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ifcopenshell/` location: [ifcopenshell.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9046093/ifcopenshell.zip)

This should replace `~/Library/Application\ Support/Blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/`.

**Note:** <small>(because Github didn't allow me to upload `.7z` I changed the extension to `.zip`. First change it back to `.7z` and then uncompress)</small>

**Comment by Moult** [comment]
@dirkolbrich hey there! Great news! We're doing a fundraiser to try and raise 70USD per month (unfortunately yes, a recurring payment, not a one-off) to afford an Apple M1 buildserver which will provide regular builds for Apple M1 devices! If you're still keen, perhaps you can help us out maybe for the price of a cup of coffee or two per month?

Details are here: https://opencollective.com/opensourcebim/projects/apple-m1-build-server - looking forward to when we can provide this with your help!
