### ISSUE TITLE
BlenderBim Add-ons Fails to Enable

### ISSUE THREAD

**Issue by MichaelArchBlend** [IfcOpenShell/IfcOpenShell#2091]
Can't get a simple plug-in to install. Uninstalled and reinstalled plenty of times to no avail.
Keep getting a whole paragraph worth of errors..
![Screenshot (2)](https://user-images.githubusercontent.com/101685365/158506229-2b538455-efe6-4af6-8a9d-c99b5defc1ac.png)

**Comment by Moult** [comment]
Hey @MichaelArchBlend ! Blender 3.10 support is not yet in the stable release. You can try an unstable version here: https://github.com/IfcOpenShell/IfcOpenShell/releases - pick one of the "py310" versions.

**Comment by MichaelArchBlend** [comment]
Thank you, seems to work now

**Comment by init666** [comment]
Sorry. Not run.
