### ISSUE TITLE
BB: IfcStyles (and perhaps IfcMaterials) are not deleted when the Blender material is deleted.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2094]
Problem detail here... 
https://community.osarch.org/discussion/931/blenderbim-relationship-between-deleted-blender-materials-and-ifc-styles#latest

**Comment by Moult** [comment]
OK as of the latest commit if you remove an IFC presentation style or an IFC material via the "X" button in the properties panel, if the Blender material is no longer linked to IFC, it will also get deleted. This saves you the trip of mucking around in the Blender outliner data, and also better reflects the concept in IFC (which Blender doesn't know about) that BIM has different types of presentation styles and materials. So I guess this may be solved.
