### ISSUE TITLE
Compatibility for python3.10

### ISSUE THREAD

**Issue by PahlawanJoey** [IfcOpenShell/IfcOpenShell#2097]
Will support for the latest python version be added?
ImportError: IfcOpenShell not built for 'windows\64bit\python3.10'

**Comment by aothms** [comment]
You can get recent builds here https://github.com/IfcOpenBot/IfcOpenShell/commit/2985bba157da40030b4b6e2159481ae08cbd603f#comments Note that python 3.10 is listed as Python 31

**Comment by PahlawanJoey** [comment]
That was a quick response, thanks / bedankt!

**Comment by Tokarzewski** [comment]
Can the ifcopenshell for 3.10 be added to the pip? 
This will improve the installation process for newcomers.
