### ISSUE TITLE
not able to install showing some error

### ISSUE THREAD

**Issue by skimtiyaz** [IfcOpenShell/IfcOpenShell#2103]
ifcOpenShell not built for 'windows\64bit\python3.10' error

**Comment by aothms** [comment]
Did you download the appropriate version, e.g:?

https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-31-v0.7.0-2985bba-win64.zip

**Comment by bbrangeo** [comment]
ifcopenshell-python not exit on s3.amazon

**Comment by skimtiyaz** [comment]
my sincere apologies as the website download page clearly instructs "WARNING: Blender version 3.1 requires a developer build with the tag "py310".
