### ISSUE TITLE
BB: InnerFilletRadius & OuterFilletRadius not showing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2105]
@Jesusbill found this error.

files: https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/d2d4c1c91b587c3be2f9eb088fe7fc4e18e8fb99/Random_Tests/Column_HSS/from_Blender

![image](https://user-images.githubusercontent.com/507113/160220098-bd1d4f64-10d3-4252-9311-c9359399ebe2.png)

![image](https://user-images.githubusercontent.com/507113/160220118-3dab655e-429a-4a8b-8db3-59e0c5f0c686.png)

**Comment by Moult** [comment]
This one also seems to be a bug in IfcOpenShell. Attached simple test case for @aothms to inspect.

[rhsprofile.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8354972/rhsprofile.txt)

**Comment by aothms** [comment]
Thanks fixed

**Comment by theoryshaw** [comment]
When I open [this ](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/d2d4c1c91b587c3be2f9eb088fe7fc4e18e8fb99/Random_Tests/Column_HSS/from_Blender/Column_HSS_02.ifc)file, i still get this. Maybe i'm missing something.
blenderbim-220327

![image](https://user-images.githubusercontent.com/507113/160287396-2a72441e-4087-4804-8187-f13c629f0445.png)

**Comment by aothms** [comment]
I haven't started new builds yet. So probably blenderbim is still talking
to an older version of ifcopenshell

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op zo 27 mrt. 2022 16:58 schreef Ryan Schultz ***@***.***>:

**Comment by theoryshaw** [comment]
my apologies, I thought the release bot updated this daily.

**Comment by Moult** [comment]
Yeah whenever a change involves C++ there is a little delay before it trickles into the BlenderBIM Add-on builds.

C++ builds are available here: https://github.com/IfcOpenBot/IfcOpenShell/commits/v0.7.0 whenever you see a comment on a commit. As of writing it's 8 days old. So we wait for a new build, and check whether or not it covers all three OSes (sometimes one or two randomly fail), and only then we can ship it with the add-on.

**Comment by aothms** [comment]
Yes it's a bit unfortunate. The website also hasn't been updated for decades. We also have a thread about in on OSarch. In principal everything is there to be fully automated.

**Comment by Krande** [comment]
Hey, for what it's worth I am almost done with a github actions pipeline for building new conda-builds of ifcopenshell on a daily basis. See the progress on the issue tracker [here](https://github.com/IfcOpenShell/IfcOpenShell/issues/1949). The only remaining obstacle is to make it compile on macOS (as it seems to compile fine for linux and windows). 

I haven't had much time to work on it in the last couple of weeks, but I hope to make another stab at it soon. If anyone has any idea on compiling conda packages for macOS using condabuild I would love to get some help ;) If not I will try to figure it out somehow :)

**Comment by Moult** [comment]
Verified that this is fixed.
