### ISSUE TITLE
BB: duplicating ifcopeningelement and applying it to another object

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2106]
file: https://gitlab.com/openingdesign/101_W_33rd_St/-/blob/84916050ff96c66713011cf4282d14e2166f927e/Models%20and%20CAD/IFC/101_W_33rd_St_Balcony.ifc

video: https://www.dropbox.com/s/y1k1e91la9yzcxl/2022-03-25_22-00-05_Blender_blender.mp4?dl=0

error 
```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 712, in invoke
    return self.execute(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 720, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\ifc.py", line 299, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 747, in _execute
    ifc_exporter.export()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\export_ifc.py", line 46, in export
    IfcStore.update_cache()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\ifc.py", line 103, in update_cache
    os.replace(IfcStore.cache_path, new_cache_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Owner\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons\\blenderbim\\bim\\data\\cache\\2109f958ae5b70f29532604783763837.h5' -> 'C:\\Users\\Owner\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons\\blenderbim\\bim\\data\\cache\\7bfd610e6f4e2788f6105f8d8b1cf628.h5'

location: <unknown location>:-1
```

**Comment by Moult** [comment]
It seems to work for me. I did notice a bug where simply adding / removing voids did not clear the cache, which meant that the next time you loaded the file it would look as though the change wasn't made although it did work. So in the recording you'll see to work around this I manually cleared the cache.

https://www.dropbox.com/s/wohd3gidftgjyt0/ifcopenshell-2106.mp4?dl=0

Note the error you've got sounds unrelated to the opening element issue, it sounds more like the cache is potentially being used in multiple sessions of Blender. Maybe another Blender is open, or the same filename was used with a different purpose, I'm not sure. You can try the purge cache in the debug panel to see if it helps.

**Comment by Moult** [comment]
A note to self that using these types of opening elements to mitre steel sections is not actually semantically correct. I believe this should be done directly in the shape itself using a half space solid clipping or something.

Unfortunately I haven't yet built support for authoring this. When I have, there should be a button where you can click two beams, and auto mitre them and it'll create the junctions properly, just like walls.

Sometimes it's a little overwhelming just how much work it is to build a BIM app :(

**Comment by aothms** [comment]
> Sometimes it's a little overwhelming just how much work it is to build a BIM app :(

Understatement of the year 😄 

But this is also really a crucial part. Ideally these kind of modelling tasks (or however you want to call them), like connect two beams, also make it into the application-agnostic use case implementations. Although I'm also not sure how that would work precisely considering we don't have a lot of means to evaluate geometry there and the round trip from blender geom to ifc definitions to ifcopenshell C++ back to ifc definitions back to blender geom would probably be expensive. It's just so important to have these higher level operations articulated somewhere for things like example files, documentation, but also for the future of IFC if we ever go into more standardized parametric behaviour.
