### ISSUE TITLE
ifcconvert doesn't succeed to generate svg from ifc

### ISSUE THREAD

**Issue by Aurbcd** [IfcOpenShell/IfcOpenShell#2108]
Hello,
Thank you for the work made on this project ! I have an issue when I use ifcconvert on [these files](https://mega.nz/folder/TUBjRZJL#BM3KXnfJbGefqJy1uvCQxw). It works to generate a .obj or .glb but when i try to generate a svg, I have the following message :

>\>ifcconvert -v "rac_basic_sample_project_Formation_IFC.ifc" x.svg
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
Scanning file...
Done scanning file
Parsing input file took 5 seconds
Log:
[Notice] include entities IfcSpace
[Notice] No geometrical elements found or none succesfully converted

Any idea where the problem comes from and how I can correct it ?

**Comment by aothms** [comment]
Default entity filter for SVG is {IfcSpace} probably your model doesn't have spaces. You can try with 

    ifcconvert -v "rac_basic_sample_project_Formation_IFC.ifc" x.svg --exclude entities IfcOpeningElement

Have a look at the command line options. There are a lot of options also specific to SVG such as related to projection

**Comment by Aurbcd** [comment]
> Hello, Thank you for the work made on this project ! I have an issue when I use ifcconvert on [these files](https://mega.nz/folder/TUBjRZJL#BM3KXnfJbGefqJy1uvCQxw). It works to generate a .obj or .glb but when i try to generate a svg, I have the following message :
> 
> > >ifcconvert -v "rac_basic_sample_project_Formation_IFC.ifc" x.svg
> > IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
> > Scanning file...
> > Done scanning file
> > Parsing input file took 5 seconds
> > Log:
> > [Notice] include entities IfcSpace
> > [Notice] No geometrical elements found or none succesfully converted
> 
> Any idea where the problem comes from and how I can correct it ?

Thank you for your respond, I don't understand why ifcconvert doesn't generate all ifcspace of the following public IFC: 
https://github.com/buildingSMART/Sample-Test-Files/blob/master/IFC%202x3/Schependomlaan/Design%20model%20IFC/IFC%20Schependomlaan.ifc
It has 106 IFCSPACE() but only 7 are generated in the svg (which seems empty).
I am not used to C++, could you help me ?

**Comment by aothms** [comment]
It's a big of a strange case. Most of the spaces in that model are 2d
footprints. Some viewers reconstruct 3d from that with the height of the
building story. Ifcopenshell doesn't do that. This will generally not
affect a lot of other models.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op vr 1 apr. 2022 17:33 schreef Aurbcd ***@***.***>:

**Comment by Moult** [comment]
Closing as resolved
