### ISSUE TITLE
IfcElectricalElement in IFC 2x3

### ISSUE THREAD

**Issue by denizmaral** [IfcOpenShell/IfcOpenShell#2110]
According to [BuildingSmart ](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/)it was deprecated in IFC 2x2 and should not be used anymore but it's still possible under IFC 2x3.

`IFC2x2 NOTE: The entity IfcElectricalElement is deprecated and shall no longer be used.`

**Comment by Moult** [comment]
Is this a question about IfcOpenShell or the BlenderBIM Add-on? In general we still allow deprecated elements because although you're not meant to use them, in theory they can still exist.

**Comment by denizmaral** [comment]
It is about BlenderBIM. Since it's deprecated, it sould not be used for any elements.

**Comment by Moult** [comment]
Deprecated means that it may still exist, even though you're not meant to use them. Therefore, we still need to show it as an option in the UI. For example, if you imported an IFC that had it, the UI will let you still manipulate it. If we hid it in the UI, the user would have no ability to manipulate them, change them to different classes, etc.

So not really a bug, I guess.
