### ISSUE TITLE
BB: show how many objects are using the style or material

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2111]
Possible to show how many objects are using the style/material?
Makes it easier to locate and purge the ones that are not in use. 

![2022-03-29_11-43-50_Blender_blender](https://user-images.githubusercontent.com/507113/160666723-d7315e9a-6c66-4bc0-a8cc-02dd4ccd97a6.png)

**Comment by Moult** [comment]
Cheers, always was on the todo list but at the time I couldn't think of an elegant way to jump from shape representations back to products.

By the way every time I implement another aspect of IFC I notice more and more that other implementations actually use way more than we realise (especially ArchiCAD). Like I love seeing Text and Curve Styles being used by ArchiCAD models and annotation coming through.
