### ISSUE TITLE
Error when trying to add BlenderBIM temporary section cutaway 

### ISSUE THREAD

**Issue by Ermgarch** [IfcOpenShell/IfcOpenShell#2117]
Hello, 

I have used the BlenderBIM temporary section cutaway before and it has worked fine on my model. I just went to use it again and am getting the below error message. It still adds a section item but it doesn’t cut anything in the model. 
![0F791CB7-956B-415A-ACB3-A6CC3FBFEF6C](https://user-images.githubusercontent.com/102700598/160938541-387d692e-abd0-4d93-aad8-cc3d01d341b3.jpeg)

I have tried the following: 
- Appending my model into a new file 
- Appending each collection one by one, sometimes this works on certain meshes but not others 
- Removing modifiers 
- Redownloading the latest BlenderBIM and reinstalling (for info I am using Blender 3.0.1, but have also tested on 2.93.5 and having same issue)

I have tested it on a new blank file with a couple of simple meshes and it seems to work, but for some reason on my much larger model it doesn’t. Could it be related to the fact I have appended and linked various items into the model? 

I can’t code so not sure where to start with the error message and what the problem is. 

Any help appreciated - sorry if it’s something obvious. 

Thanks

**Comment by Moult** [comment]
Would you mind trying to edit the `bim/operator.py` file to change the line that looks like this:

```
and n.node_tree.name == "Section Compare"
```

To look like this instead?

```
and n.node_tree and n.node_tree.name == "Section Compare"
```

**Comment by Ermgarch** [comment]
Thanks for quick reply! I tried that and I am now getting a new error message, shown below. Any ideas on how to fix? 

![62E5AD02-3401-4F95-B0F4-26FE33DDC251](https://user-images.githubusercontent.com/102700598/160943574-1420eb0e-e2d9-46b3-9636-266ff5d5da9c.jpeg)

**Comment by Moult** [comment]
Odd, perhaps it's best to try from a clean slate. Hard to debug without seeing the file itself unfortunately.

In the outliner, delete these two node groups. Then go through every single material you have in the Shader editor and make sure the node tree is valid. No missing blocks, no broken links, etc. A single material output. Then try add the section again.

![2022-03-31-101823_343x288_scrot](https://user-images.githubusercontent.com/88302/160946272-64e06210-c257-46c5-99d8-0dc8d088362c.png)

**Comment by Ermgarch** [comment]
I tried to delete the two node groups you suggested, but had different option, no 'Section Compare': 
![image](https://user-images.githubusercontent.com/102700598/161031777-fde23ed9-62ee-4a9a-8693-4d741c4ef2b6.png)

Deleting the two overrides then made lots of the materials in my model go black: 
![image](https://user-images.githubusercontent.com/102700598/161031905-d8ecc8b1-4d67-4f77-884e-ef4acdb590ec.png)

Then I tried adding the section cutaway and got no error message but the section did not cut the model it remained all black. 

Then I deleted all the materials in the model, and tried to do a cut and it did cut the geometry (which is great progress). One issue I then noticed is the the black colour (the section cut colour) was in very random places in the model, see below: 
![image](https://user-images.githubusercontent.com/102700598/161033461-f6657e90-fac9-4b56-9ab4-5ae572b6b458.png)

I rendered it anyway to see if the freestyle line would pick up the black colouring as I thought I could use a line drawing as a back up instead if the textures are playing up, but that seems to not work. I guess freestyle just doesn't work with this plug in as  the section cut works through materials not changing geometry, and freestyle works through geometry, is that right? Don't suppose you know any way of turning the cut into a line drawing?

Do you know why the black colour is appearing in lots of random places?

This is great progress though as I can at least as a back up take a messy cut and use that to trace over, will take some time but much better than where I started! Now I know the problem is in the materials I can get testing on where the issue is - thank you very much

**Comment by Moult** [comment]
Sorry I completely forgot to reply. Correct the section cutaway never modifies geometry, only giving a preview to its internals by rendering a portion of it invisible.

To generate an actual cut drawing you'd want to look at https://github.com/IfcOpenShell/IfcOpenShell/issues/1153
