### ISSUE TITLE
run-cmake.bat:  ADD_SUBDIRECTORI svgfill fails (IfcOpenShell-blenderbim-220330)

### ISSUE THREAD

**Issue by jespa007** [IfcOpenShell/IfcOpenShell#2121]
Hi,

The latest ifcopenshell release (i.e IfcOpenShell-blenderbim-220330), run-cmake.bat it fails because cmake tries to add subdirectory src/svgfill whereas there's no CMakeLists.txt at all.

![image](https://user-images.githubusercontent.com/7852409/161226850-523dae71-b2d9-46db-aa27-d361d916899e.png)

I checked out the directory and, indeed, there's no any CMakeLists.txt,

![image](https://user-images.githubusercontent.com/7852409/161226521-92f26ebb-fd09-489f-9fd9-55cb2c93c90f.png)

If I navigate through github svgfill directory is a link to another project,

![image](https://user-images.githubusercontent.com/7852409/161226732-ea7b6bf2-f3ac-4842-aee5-265b5ddbdccb.png)

I think the source should be included. Isn't it ?  This issue is not explained (or at least I didn't see) on the readme.md placed on win directory. So anybody has to deduce that svgfill has to be downloaded manually from svgfill [repositori](https://github.com/IfcOpenShell/svgfill/tree/01a2fb49434920eb5cce789d14fcb425b9fe82c2).

**Comment by aothms** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/issues/1761

Clone with `git clone --recursive` or now do `git submodule update --init --recursive`

But a lot of people are running into this. If you want to take the time, maybe add a more informative message to the cmake script that tells users what to do in case of failure, or, even better, check if the source dir is a git repo and if git is available in the path and do `git submodule update --init --recursive` directly from cmake when detected that the dir is empty. Pull requests welcome :)

**Comment by jespa007** [comment]
Hey  @aothms ! 
Thanks for your quick response!! I didn't know about to do the "git clone" because I've suposed all was doing through .bat process. I have a doubt. Is the "svgfill" module required or optional for the process generation of the final output of ifcopenshell? In case it's optional may be it could be discarted adding a simple if cmake\CMakeLists.txt and showing the information the respictevely information on run-cmake.bat

**Comment by jespa007** [comment]
I have another question @aothms related with this procedure of clone svgfill module. If I download a old ifcopenshell release, for instance [blenderbim-210319](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-210319), is this sure that svgfill will still work with  [blenderbim-210319](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-210319) ?  I saw that last modification was 8 months ago so I think not, but for future releases may be there's some changes... you know the sofware has a lot of variation over the time ;-)

**Comment by aothms** [comment]
svgfill is used for the drawing generation in blenderbim and `ifcopenshell.draw`. So for some uses it might be optional. Without svgfill you also do not need MPIR MPFR and CGAL, so there's something to say for making it optional. Contributions welcome :)

> you know the sofware has a lot of variation over the time ;-)

That's the reason why we use a submodule and a "mono repo" so that all code is in sync when building. Especially between the layers

IfcOpenShell C++
IfcOpenShell Python 
IfcOpenShell Python API
BlenderBIM

there will be some hard requirements on having the correct version.

For svgfill this is much less of a concern. It's really a minimal API that it provides.

**Comment by jespa007** [comment]
Thomas,
Thanks for the information and its clarification. I hope I contribute something in ifcopenshell in the long of the use. Is really a powerful and big project!
Congratulations
