### ISSUE TITLE
Error Installing Addon

### ISSUE THREAD

**Issue by johntedharvey** [IfcOpenShell/IfcOpenShell#2124]
I get an error when activating the Blenderbim addon version "blenderbim-220130-py39-win".

![image832](https://user-images.githubusercontent.com/14089948/161746248-e2fa91d3-aba6-45d0-91c7-e1e3bf9b61c1.png)

**Comment by Moult** [comment]
You need the py310-win version available here: https://github.com/IfcOpenShell/IfcOpenShell/releases
