### ISSUE TITLE
File won't save changes after edit. (BlenderBIM)

### ISSUE THREAD

**Issue by gschleusner1972** [IfcOpenShell/IfcOpenShell#2125]
I tried this in Version 3.0 of Blender and had the same issues I was experiencing in 3.1.    If I load this file into BlenderBIM, edit the geometry and save I get an error, or the file exported is not edited.

Source File is here.
https://github.com/magnetar-io/ByElementIFC_Data/blob/main/AdvancedSamples/Arch/AR_IfcWall_1fIVuvFffDJRV_SJESOtFR_0c1ba2ba-c7d5-4a2e-99d3-28ae56e83e49.Ifc

Output and Blender File Here.

https://github.com/magnetar-io/ByElementIFC_Data/tree/main/AdvancedSamples/Arch/BlenderEdit

**Comment by Moult** [comment]
Just tested it and it works fine here. I noticed your Blender geometry is not manifold and there is incompatible with the original swept solid geometry. The BlenderBIM Add-on deals with IFC natively and so it actually preserves the geometry types used in IFC. So if your IFC uses swept solids, it expects modifications to also be compatible with a swept solid. (Of course, you can switch geometry types if you wish if you want something arbitrary)

[curtain-wall.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8456688/curtain-wall.ifc.txt)
