### ISSUE TITLE
2D Cuts -> Errors in removing openings

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#2126]
Hello, 

![image](https://user-images.githubusercontent.com/1086380/161793040-3fb68331-d194-4618-8606-3f98f507b7d6.png)

it only happens, if I use 2D cuts.

maybe some shapefixes are helping?

kind regard

[ErrorInWall.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8419758/ErrorInWall.zip)

**Comment by aothms** [comment]
Thanks. ShapeFix_Face would indeed catch it, but I can detect the situation earlier as well preventing an expensive shapefix call.

![afbeelding](https://user-images.githubusercontent.com/1096535/162400101-d6882442-3660-47e4-9bea-261280da5cb9.png)
