### ISSUE TITLE
Report: Error when installing Addon

### ISSUE THREAD

**Issue by laurindominik** [IfcOpenShell/IfcOpenShell#2128]
I know this is not a forum but i did not find one. When installing/clicking (blenderbim-220130-py39-win) the checkbox for Import-Export: BlenderBIM i get an error message as you can see in the picture below.

![image](https://user-images.githubusercontent.com/67796250/162143042-72b4d8dc-8f05-4cb6-b2bd-e33fc88cfaba.png)

Any idea how to resolve this?

Thanks

**Comment by FeCruz05** [comment]
I am having the same problem! 
How can I solve this?

**Comment by Moult** [comment]
For Blender v2.91 you need a py37 version from the releases page:

https://github.com/IfcOpenShell/IfcOpenShell/releases

For Blender v3.1 you need a py310 version from the releases page.

For Blender versions in-between you can use the stable py39 version. Sorry I haven't yet had a chance to do a stable release of the BlenderBIM Add-on.
