### ISSUE TITLE
Crash with incorrect IfcPolygonalBoundedHalfSpace

### ISSUE THREAD

**Issue by shieldh** [IfcOpenShell/IfcOpenShell#2134]
How to reproduce:
Generate the file /tmp/project.ifc with the attached ifcopenshell file "simple_wall_example2.py"
Import project.ifc file in Blender with BlenderBIM.

Observed:
No warning when simple_wall_example2.py script is run.
Blender crashes during the import. Information about the crash can be found in the attached file blender.crash.txt:
`# backtrace`
`0   Blender                             0x000000010bfb8177 BLI_system_backtrace + 55`
`1   Blender                             0x00000001020237b8 sig_handle_crash + 392`
`2   libsystem_platform.dylib            0x00007ff8132dfdfd _sigtramp + 29`
`3   ???                                 0x000070000a1588a8 0x0 + 123145471494312`
`4   _ifcopenshell_wrapper.so            0x000000012d7c257a _ZN7IfcGeom12KernelIfc2x37convertEPKN6Ifc2x328IfcPolygonalBoundedHalfSpaceER12TopoDS_Shape + 346`
`5   _ifcopenshell_wrapper.so            0x000000012d7e0909 _ZN7IfcGeom12KernelIfc2x313convert_shapeEPKN7IfcUtil16IfcBaseInterfaceER12TopoDS_Shape + 2201`
`6   _ifcopenshell_wrapper.so            0x000000012d7c3fbf _ZN7IfcGeom12KernelIfc2x37convertEPKN6Ifc2x316IfcBooleanResultER12TopoDS_Shape + 2879`

Running `python3 -m ifcopenshell.validate project.ifc` indicated that the generated ifc file was not valid.
The reason was a wrong argument type for the Position parameter:
`In #76=IfcPolygonalBoundedHalfSpace(#68,.F.,#69,#75)`
`#69=IfcCartesianPoint((0.,0.,0.)) not valid for <attribute Position: <entity IfcAxis2Placement3D>>`

Expected:

- The ifcopenshell script should fail, indicating that the argument type to create the IfcPolygonalBoundedHalfSpace was wrong.
- BlenderBIM import should not crash Blender.

Additional notes:
"simple_wall_example2.py" is a modified copy of the example script found here: [creating-a-simple-wall](https://academy.ifcopenshell.org/posts/creating-a-simple-wall-with-property-set-and-quantity-information/)
The purpose of this file was to create a simple example of a wall under an inclined roof slab.
The ifcopenshell has been corrected (see simple_wall_example2_corrected.py) and the generated file (/tmp/project.ifc) is now correctly imported in Blender.

IfcOpenShell was compiled from sources (version v0.7.0) with opencascade 7.5.1 (also compiled from sources).
Blender version was 3.0.1 with BlenderBIM add-on version 0.0.220130

Attached files:
[crash_BlenderBim_IfcPolygonalBoundedHalfSpace.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8457874/crash_BlenderBim_IfcPolygonalBoundedHalfSpace.zip)

**Comment by Moult** [comment]
I think this is something for IfcOpenShell @aothms to decide. The BlenderBIM Add-on simply follows the rules of IfcOpenShell.

Right now IfcOpenShell only seems to check primitive data types when creating elements. (e.g. string, null, int, list) It won't stop you creating invalid entity instance attributes as you've done.

If it's invalid at a data type level, I'm personally happy for the import to crash as I consider it a pretty severe error with the input data. After all, that's what the validate tool is for, and only power users will be running into this type of invalid data (we'd hope!).

**Comment by aothms** [comment]
I agree, crashed should not happen, but I also can't reproduce it. At least not on the following script:

~~~
import ifcopenshell
import ifcopenshell.geom

f = ifcopenshell.open("project.ifc")

ifcopenshell.ifcopenshell_wrapper.turn_on_detailed_logging()

it = ifcopenshell.geom.iterator(ifcopenshell.geom.settings(), f, num_threads=2)
for x in ifcopenshell.geom.consume_iterator(it):
    print(x.guid)
    
print("ok")
~~~

It prints:

~~~
[Notice] [2022-04-10 09:16:12] Valid: 1
#63=IfcExtrudedAreaSolid(#61,#54,#62,10.)
[Error] [2022-04-10 09:16:12] Instance of type IfcCartesianPoint cannot be cast to IfcAxis2Placement3D
Failed to convert:
#76=IfcPolygonalBoundedHalfSpace(#68,.F.,#69,#75)
[Error] [2022-04-10 09:16:12] Failed to convert SecondOperand:
#76=IfcPolygonalBoundedHalfSpace(#68,.F.,#69,#75)
[Warning] [2022-04-10 09:16:12] Subtraction yields unchanged volume:
#77=IfcBooleanClippingResult(.DIFFERENCE.,#63,#76)
[Notice] [2022-04-10 09:16:12] Valid: 1
#77=IfcBooleanClippingResult(.DIFFERENCE.,#63,#76)
Done creating geometry (1 objects)
186rkUk4mHx9xGhDv8014Y
ok
~~~

> IfcOpenShell was compiled from sources (version v0.7.0)

What commit sha specifically? Might be something that got solved in the meantime?

**Comment by shieldh** [comment]
> > IfcOpenShell was compiled from sources (version v0.7.0)
> 
> What commit sha specifically? Might be something that got solved in the meantime?

Hi Thomas,
Regarding your question:
`$ git show`
`commit bb832f306a8147a4035e56db2fee0d43a1fd6c53 (HEAD -> v0.7.0)`
But the crash does not happen with IfcOpenShell and I got the same result as you with your script.
The crash happens inside Blender with add-on blenderbim-220130-py39-macos.zip when I try to import the invalid ifc file.

**Comment by shieldh** [comment]
> If it's invalid at a data type level, I'm personally happy for the import to crash as I consider it a pretty severe error with the input data. After all, that's what the validate tool is for, and only power users will be running into this type of invalid data (we'd hope!).

Hi Dion,
I guess you're right and this issue is probably minor.
As a key takeaway (I'm new to ifcopenshell), I will always validate the ifc files that I produce with my scripts. I spent a few hours to understand what was wrong, until I found a comment from Thomas for another issue advising to run the validation script. This is how I finally could find my error. This is because of all the time I spent finding this silly error that I reported this issue.
I think that it would be helpful if blenderbim does not crash and instead reports an error message indicating that there could be a problem with the imported file, and that it could be checked with the validating script.
But if you think this is low priority compared to all the other tasks, this issue can be closed.

**Comment by aothms** [comment]
> But the crash does not happen with IfcOpenShell and I got the same result as you with your script.

Might be very similar than to https://github.com/IfcOpenShell/IfcOpenShell/issues/2081 where we also couldn't understand why specifically blenderbim crashed on a file but regular ifcopenshell python processed the file just fine. So some additional eyes on this might be beneficial.

- What's the behaviour when you disable multi-threading in blender import
- What's the behaviour when you run python script above from within Blender?

**Comment by shieldh** [comment]
> * What's the behaviour when you disable multi-threading in blender import
> 
> * What's the behaviour when you run python script above from within Blender?

Sorry but I did not find how to disable multi-threading in blender import. Can you please tell me how to do that? What I noticed though, is that if I click on "Enable Advanced Mode", Blender does not crash (but no data is imported in Blender, not even the top level elements).

The python script crashes Blender. Attached is the blender crash file. Note that I used `num_threads=1` instead of 2 in the python script (it crashes also with the value 2).
[blender.crash_script_run_in_blender.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8459902/blender.crash_script_run_in_blender.txt)

Before crashing, Blender output is:
`[Debug] [2022-04-10 22:54:19] Begin processing`
`#80=IfcWallStandardCase('30wwTckCiHxAJuhDv8014Y',#5,'Wall','An awesome wall',$,#46,#79,$)
[Debug] [2022-04-10 22:54:19] Begin processing`
`#80=IfcWallStandardCase('30wwTckCiHxAJuhDv8014Y',#5,'Wall','An awesome wall',$,#46,#79,$)
[Notice] [2022-04-10 22:54:19] {30wwTckCiHxAJuhDv8014Y} Valid: 1`
`#63=IfcExtrudedAreaSolid(#61,#54,#62,10.)`

**Comment by shieldh** [comment]
I tried to compare the _ifcopenshell_wrapper.so versions between the one included in the blenderbim add-on and the one compiled from the ifcopenshell sources and installed as a python module. But the 2 are not compiled the same way.
Attached is the result of the "otool -L" command of the 2 libraries.
I just noticed that the libc++ versions differ (the one that does not crash is more recent), 
but I do not know if it is relevant.


[otool_ifcopenshell_wrapper.so_blender_add-on.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8459911/otool_ifcopenshell_wrapper.so_blender_add-on.txt)
[otool_ifcopenshell_wrapper.so_python_module.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8459912/otool_ifcopenshell_wrapper.so_python_module.txt)

**Comment by shieldh** [comment]
> What I noticed though, is that if I click on "Enable Advanced Mode", Blender does not crash (but no data is imported in Blender, not even the top level elements).
> 
> The python script crashes Blender. Attached is the blender crash file. Note that I used `num_threads=1` instead of 2 in the python script (it crashes also with the value 2).

I did the same test on a Linux PC, with the same blenderbim version, but with Blender 2.83.5, and observed the same behavior for the crash during import, the absence of crash with "Enable Advanced Mode" checked, and the crash with the python script.

**Comment by shieldh** [comment]
Thomas,
looking at the stack, and the sources, I suspect that the reason of the crash is in [IfcGeomShapes.cpp](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcGeomShapes.cpp) line 502.
I did not dig into the implementation of the as() method inside Ifc2x3.cpp:
`::Ifc2x3::IfcAxis2Placement3D* Ifc2x3::IfcPolygonalBoundedHalfSpace::Position() const {  return ((IfcUtil::IfcBaseClass*)(*data_->getArgument(2)))->as<::Ifc2x3::IfcAxis2Placement3D>(true); }`
But I suspect that this method performs a cast that will give an unpredictable result if the Position parameter is not of type IfcAxis2Placement3D.
Maybe this can generate a segfault in some context, and none in others?

**Comment by Moult** [comment]
> What I noticed though, is that if I click on "Enable Advanced Mode", Blender does not crash (but no data is imported in Blender, not even the top level elements).

This is by design though perhaps not so intuitive. Enabling advanced mode will only load the file, but no elements. It will then present a panel in the scene properties which allows you to further customise how you want to load elements. You can apply element filters, customise tolerances, or load objects with a particular hierarchy.

**Comment by Moult** [comment]
I've included a minimal import script posted here: https://github.com/IfcOpenShell/IfcOpenShell/issues/2081#issuecomment-1094404953 - I can recreate the segfault with that minimal script on my machine.

**Comment by aothms** [comment]
@shieldh 

>  But I suspect that this method performs a cast that will give an unpredictable result if the Position parameter is not of type IfcAxis2Placement3D.

IfcOpenShell is an exception-heavy code-base, so your case should just raise an exception https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcBaseClass.h#L66-L68 (note that `true` (=do_throw) in the code line you highlighted). That will be caught, quite granularly, so the 2nd operand of the subtraction will fail to convert, so the first operand is used.

In my test script the following line is printed as a result:

    [Error] [2022-04-10 09:16:12] Instance of type IfcCartesianPoint cannot be cast to IfcAxis2Placement3D

But I agree, it is likely somehow related to this.

@Moult 

Thanks for this script, very helpful, it didn't segfault on my machine. Could you quickly dump all related info regarding system and interpreter you used? Thanks.

**Comment by shieldh** [comment]
> note that `true` (=do_throw) in the code line you highlighted

@aothms , thank you for this explanation. As I said, I'm new to ifcopenshell and blenderbim and I have many things to learn! Do you have a possibility to easily use a tool like valgrind on a simple test case? That would be useful it the root cause is a memory corruption.

**Comment by shieldh** [comment]
> Thanks for this script, very helpful, it didn't segfault on my machine. Could you quickly dump all related info regarding system and interpreter you used? Thanks.

It does'nt crash on my machine either.

**Comment by shieldh** [comment]
@aothms , I tried to create a program similar to your python script, but all in c++.
It's possibly not correct because I'm not sure I initialized all the objects correctly, but I would like to share with you my findings.

I modified the IfcParseExamples.cpp file with the following code:
```
IfcGeom::IteratorSettings settings;
settings.set(IfcGeom::IteratorSettings::USE_WORLD_COORDS, false);
settings.set(IfcGeom::IteratorSettings::WELD_VERTICES, false);
settings.set(IfcGeom::IteratorSettings::CONVERT_BACK_UNITS, true);
auto iterator = new IfcGeom::Iterator(settings, &file);
// Not sure it has to be done or not: bool has_more = iterator->initialize();
bool has_more = true;
while (has_more) {
    has_more = iterator->next() != 0;
}
```

When I run this code with the faulty project.ifc file as parameter, I get this:
```
Scanning file...
Done scanning file
IfcDebugCrash: /usr/include/boost/smart_ptr/shared_ptr.hpp:728: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = aggregate_of<Ifc2x3::IfcRepresentation>; typename boost::detail::sp_member_access<T>::type = aggregate_of<Ifc2x3::IfcRepresentation>*]: Assertion `px != 0' failed.
Abandon`
```
The exception is raised here:
```
IfcGeom::IteratorImplementation_Ifc2x3::get_next_task()
ifcgeom/IfcGeomIteratorImplementation.h line 659
```
You can read the complete stack trace here: 
[report_when_settings_initialized.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8477037/report_when_settings_initialized.txt)


If I do not initialize the settings (I do not call `settings.set()`), the program finishes normally, but I can see this error:
```
UninitCondition: Conditional jump or move depends on uninitialised value(s)
```
This error appears here:
```
IfcGeom::KernelIfc2x3::create_brep_for_representation_and_product(IfcGeom::IteratorSettings const&amp;, Ifc2x3::IfcRepresentation*, Ifc2x3::IfcProduct*)
ifcgeom/IfcGeomFunctions.cpp line 2243
```
You can read the complete stack trace here: 
[report_when_settings_not_initialized.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8477047/report_when_settings_not_initialized.txt)


Does that help to understand the issue?

**Comment by aothms** [comment]
Thanks for your continued investigation. You do need to call `initialize()` though before calling `next()`  as in your comment.

~~~C++
IfcGeom::IteratorSettings settings;
settings.set(IfcGeom::IteratorSettings::USE_WORLD_COORDS, false);
settings.set(IfcGeom::IteratorSettings::WELD_VERTICES, false);
settings.set(IfcGeom::IteratorSettings::CONVERT_BACK_UNITS, true);
auto iterator = new IfcGeom::Iterator(settings, &file);
bool has_more = iterator.initialize();
while (has_more) {
    has_more = iterator->next() != 0;
}
~~~

**Comment by shieldh** [comment]
OK. So this is a dead end.

I uncommented the line `bool has_more = iterator.initialize();` and relaunched the test. The assertion has gone. The result is the same wether `settings.set()` is called or not: the program does not crash and finishes normally.

There is still this error (UninitCondition: Conditional jump or move depends on uninitialised value(s)) with the same stack trace in both case. I think that this error has nothing to do with this issue. It is caused by the member variable `force_space_transparency_` in `IteratorSettings` not being initialized. If I initialize it, with a positive or negative value, the error goes away and the program still does not crash.
Is it worth creating another issue for that?

**Comment by shieldh** [comment]
I did another try.
As I could see the crash only in blender, I did a checkout of tag `blenderbim-220130`.
Then I realized that I could not use the _ifcopenshell_wrapper.so lib in blender because I did not activate the HDF5_SUPPORT flag. I recompiled with this flag On.
So I do not know (yet) which actions were necessary to reproduce the segfault, but at least I managed to get one.
There was an invalid read in `IfcGeom::KernelIfc2x3::convert(Ifc2x3::IfcAxis2Placement3D const*, gp_Trsf&amp;)` (ifcgeom/IfcGeomHelpers.cpp line 166).
The complete stack of this invalid read, and the stack when the segfault happened can be seen here: 
[report_with_hdf5.xml.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8485130/report_with_hdf5.xml.txt)

**Comment by aothms** [comment]
Interesting.

`convert(const IfcSchema::IfcAxis2Placement3D* l, gp_Trsf& trsf)` is indeed trying to read the invalid pointer coming there from `if ( ! convert(l->Position(),trsf) ) return false;` in `convert(const IfcSchema::IfcPolygonalBoundedHalfSpace* l, TopoDS_Shape& shape)`

It's also just a nullptr which is should actually be checked as we discussed earlier https://github.com/IfcOpenShell/IfcOpenShell/issues/2134#issuecomment-1094636858

~~~xml
  <event>Access not within mapped region</event>
  <siaddr>0x0</siaddr>
~~~

The stack report you attached is not from Blender. Am I understanding you correctly that enabling HDF5 support in your modified executable caused the segfault to be reproducible, where without HDF5 the segfault did not occur?

That would be odd because there isn't much HDF5 going on here still at this point. 

Also from the assertions earlier can I assume you're using a debug build without optimizations?

**Comment by shieldh** [comment]
> The stack report you attached is not from Blender. Am I understanding you correctly that enabling HDF5 support in your modified executable caused the segfault to be reproducible, where without HDF5 the segfault did not occur?

Yes, you're assuming correctly. This was done with the same test program I used previously. The code is now the one you amended with the call to `iterator.initialize()`.


> Also from the assertions earlier can I assume you're using a debug build without optimizations?

Yes again.

**Comment by shieldh** [comment]
This evening, I will sync to the latest commit to see if the problem has gone (as I said earlier I did a checkout to the tag used for the published blenderbim add-on). It's maybe not worth it to spend time debugging this problem if it is minor.

**Comment by aothms** [comment]
> I did a checkout to the tag used for the published blenderbim add-on

Oh oops, I missed that bit, yes if that's the case than that explains:

The do_throw bit was specifically added in that timeframe

https://github.com/IfcOpenShell/IfcOpenShell/compare/blenderbim-220130..v0.7.0#diff-b3f739c7f6a1b2328a4b61bf3555e5d74975adc5c7ff8dec687670cf7e315d80

**Comment by shieldh** [comment]
Good news. So I will verify tonight that this issue is corrected, and we will be able to close it.

**Comment by shieldh** [comment]
@aothms, I just did the test with the latest commit. There is no error and the program did not crash. This problem has already been fixed. You can close this issue.

**Comment by aothms** [comment]
Great, thanks again for the detailed investigations. Hopefully next time it'll lead to something more concrete :)
