### ISSUE TITLE
BB: SVG drawing scaling does not change when changing scale

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2136]
Using blenderbim-220413-py310-win.zip,

When attempting to change the scale of an exported SVG, scale no longer changes in the output drawing:

model scale 1to100 :
![image](https://user-images.githubusercontent.com/78321676/163143228-26e85904-4062-4954-aad9-de37e83ea720.png)

model scale 1:20:
![image](https://user-images.githubusercontent.com/78321676/163143301-8f095e69-41ec-49db-ab7b-56e939e99523.png)

SVG result for both is the same:
![image](https://user-images.githubusercontent.com/78321676/163143137-be3c0552-f76d-4011-9874-57ff0490256e.png)

previously (even blenderbim-220412-py310-win.zip,) the scale change was working

**Comment by Plae-Blue-Dot** [comment]
Additionally Annotations are only working at 1to100

model plan 1to100
![image](https://user-images.githubusercontent.com/78321676/163147967-743998f8-dc2d-46ee-9206-4db663a8a3ef.png)

Plan SVG 1to100
![image](https://user-images.githubusercontent.com/78321676/163147504-2accc40f-523a-470e-b3a3-73d5adf5bde3.png)

model plan 1to20
![image](https://user-images.githubusercontent.com/78321676/163148102-8441931f-2f06-4175-9fca-cc9e760bf946.png)

Plan SVG 1to20
![image](https://user-images.githubusercontent.com/78321676/163148178-4456a9a6-d15e-4f59-9cd0-3b7efcc6c17b.png)


model elevation 1to100
![image](https://user-images.githubusercontent.com/78321676/163147432-2fd205bf-e6f7-4412-85d7-49a804f986fb.png)

Elevation SVG 1to100
![image](https://user-images.githubusercontent.com/78321676/163147474-b3db7d32-b6f6-41db-9a32-d772b58c460f.png)

model elevation 1to20
![image](https://user-images.githubusercontent.com/78321676/163147845-9bbe55ae-8e62-4c5c-9cb7-56c6a94706c3.png)

Elevation SVG 1to20
![image](https://user-images.githubusercontent.com/78321676/163147707-dddeb488-b889-4e2e-bd45-167208e5acaa.png)


Don't know if this is related or should be a separate issue

**Comment by Moult** [comment]
Sorry, I made a typo that broke a lot of stuff. There is a lack of tests for the drawing module since it is so experimental so thanks a huge amount for helping catch this :)
