### ISSUE TITLE
IfcOpenShell V0.7.0 Anaconda

### ISSUE THREAD

**Issue by Takieddinex** [IfcOpenShell/IfcOpenShell#2137]
Hello ! 
I would like to have ifcopenshell.api which does not exist on the IfcOpenShel 0.6.0 version. I decided to install IfcOpenShell V.0.7.0 but every time I type the command on the conda environment I get this error that I can't solve. 
It would be nice if you could help me please.  
Thank you very much.  

![image](https://user-images.githubusercontent.com/95845810/163179601-602efc95-63da-4b71-8daa-d41a20da6638.png)
![image](https://user-images.githubusercontent.com/95845810/163207609-2ce5ec49-8c32-4426-aff7-44787ec4c800.png)

**Comment by aothms** [comment]
One thing that always seems to work is simply drop the archives downloaded from the website into your site-packages folder http://ifcopenshell.org/python

The packages in anaconda are still under development and currently outdated https://github.com/IfcOpenShell/IfcOpenShell/pull/2132 https://github.com/conda-forge/ifcopenshell-feedstock/

**Comment by Takieddinex** [comment]
Hello! 
Thank you for your answer. I tried to copy and paste the archives in the site-package but it didn't work
I have tried to complete following the instructions https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/readme.md but it didn't work either and since I want to use the pythonocc-core library at the same time as IFCOS only anaconda allows me to do that

**Comment by aothms** [comment]
> but it didn't work

What was the issue then?

Copying to your site-packages also works for anaconda with pythonocc installed.

**Comment by Takieddinex** [comment]
All pythonocc and ifcopenshell libraries work except ifcopenshell.api cannot be found. 

![image](https://user-images.githubusercontent.com/95845810/163568568-2107d279-3468-4583-8f2b-206de39b3de2.png)

**Comment by aothms** [comment]
v0.7 is also available on the web http://ifcopenshell.org/python

**Comment by Takieddinex** [comment]
I'm sorry, I'm a beginner, yes I downloaded it but I don't know how to make it work. I usually clone and run the application inside but I don't know how I can use it if you can show me please?

**Comment by Moult** [comment]
@Takieddinex as of 2 weeks ago IfcOpenShell is now built for Anaconda. Try these instructions :) https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#conda
