### ISSUE TITLE
build-all.py BUILD_CFG vs. BUILD_TYPE mix-up?

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#214]
BUILD_CFG would appear to default to `Build` which doesn't make much sense when the typical values (values provided by default by CMake) are `Release`, `RelWithDebInfo`, `MinSizeRel`, and `Debug`. Also BUILD_TYPE is passed for CMake invocations instead of BUILD_CFG but the info print suggests otherwise.

**Comment by aothms** [comment]
Right, I committed this: https://github.com/IfcOpenShell/IfcOpenShell/commit/4c6ca83528374bfb08fb12d5d317e12a690e75a6#diff-3452a816195514e564474325fd8538e2L242

Does something need to be changed in the win build script as well?

**Comment by Stinkfist0** [comment]
Everything would appear to be in order in build-deps.cmd.

**Comment by aothms** [comment]
Great :)
