### ISSUE TITLE
Impossible to build IfcOpenShell 0.7.0 as a shared library on Windows

### ISSUE THREAD

**Issue by aschvalberg** [IfcOpenShell/IfcOpenShell#2141]
Hello,

my config: VS2022 on Windows 11

when I set the BUILD_SHARED_LIBS option (in order to have IfcParse and IfcGeom built as dlls), I get a linker error for IfcParse project:
**LINK : fatal error LNK1189: library limit of 65535 objects exceeded**

Please note that I am able to build everything as _static_ libraries.

From Microsoft doc, it seems to be a hard limit on the linker: https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1189

I even't don't know exactly how many symbols are exported and are above this limit.
Is there a workaround in order to reduce the number of exported symbols?

Thanks

**Comment by aothms** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/issues/1029#issuecomment-871650453

At some point, changes will have to be made to have various schemas as individual libraries to workaround this limitation. It might bring some advantages having them as some sort of plug-ins. Contributions or ideas welcome.

**Comment by aschvalberg** [comment]
Thanks a lot for your answer.
It works if I set for instance only Ifx2x3, Ifc4 and Ifc4x1 schemas.
Starting with 4 schemas, the limit is reached!

You're right, having separate dll for each schema might be the way to go.
