### ISSUE TITLE
BB: always have to use Purge HDF5 after modifying a file, and then importing again. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2143]
I used [this ](https://github.com/yorikvanhavre/BIM_Workbench/issues/92#issuecomment-1100449520)file, but this happens on other files as well. 

- Import file
- change/move objects
- close, don't save
- try to import same file.
- freezes
- need to use Purge HDF5 before import works again.

video: https://www.dropbox.com/s/ve3taie3ck38u87/2022-04-16_18-09-34_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
I thought this was fixed here: https://github.com/IfcOpenShell/IfcOpenShell/issues/2053#issuecomment-1079877716 - but maybe not? Is your build more recent than 21 days?

**Comment by theoryshaw** [comment]
![image](https://user-images.githubusercontent.com/507113/163694923-92e72ce8-1136-4472-bf60-3c0f33fe24c0.png)
