### ISSUE TITLE
BB: error when modifying an object in a collection instance

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2152]
files: https://www.dropbox.com/sh/r587qhxfnun10s6/AAB0Oz7PMRdKN43UC0U14Xdaa?dl=1

video: https://www.dropbox.com/s/hduet8ap3ym94zr/2022-04-20_22-47-27_Blender_%5BDDropboxTroubleshooting20220420_-_co_blender.mp4?dl=0

**Comment by theoryshaw** [comment]
related to this workflow: https://community.osarch.org/discussion/958/bb-easy-way-to-create-new-guids-for-all-objects

**Comment by Moult** [comment]
Yes collection instances are unsupported so I'm unsurprised this led to sync breaks. I'll take a look nevertheless to see if there's anything I can do.
