### ISSUE TITLE
IfcSchema-definitions.h included in IfcGeom.h not available

### ISSUE THREAD

**Issue by dushyant-basson** [IfcOpenShell/IfcOpenShell#2153]
https://github.com/IfcOpenShell/IfcOpenShell/blob/80d86659928c6b46c23d6f6eeda2b988a741a152/src/ifcgeom/IfcGeom.h#L87

The include file "IfcSchema-definitions.h" is not available in ifcparse. 
ifcgeom/IfcGeom.h(87,10): fatal error C1083: Cannot open include file: '../ifcparse/IfcSchema-definitions.h': No such file or directory

**Comment by dushyant-basson** [comment]
Ok. I'm trying to understand the code structure, and it's still not clear how **IfcSchema-definitions.h** header file gets generated(?) for a specific schema, as per the code:
#define INCLUDE_PARENT_DIR(x) STRINGIFY(../ifcparse/x-definitions.h)
#include INCLUDE_PARENT_DIR(IfcSchema)
as I could not find IfcSchema-definitions.h in the source code.

The reason to use ifcGeom/IfcGeom.h :   
qtviewer/mainwindow.h  (I know it's an old code, not updated for long) required ifcgeom/IfcGeomObjects.h (which is unavailable) . I tried replacing it with ifcgeom/IfcGeom.h , which seemingly, is not a replacement.
If it is needed to use a particular schema, I can go with IFC2x3. What's the best to way to get the existing qtviewer code to compile? I did set it up to use Qt5.

**Comment by aothms** [comment]
>  as I could not find IfcSchema-definitions.h in the source code.

`IfcSchema` is (confusingly perhaps) a preprocessor directive. https://github.com/IfcOpenShell/IfcOpenShell/blob/80d86659928c6b46c23d6f6eeda2b988a741a152/cmake/CMakeLists.txt#L711

> ifcgeom/IfcGeomObjects.h

This more or less evolved into `ifcgeom_schema_agnostic/IfcGeomIterator.h` https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcconvert/IfcConvert.cpp#L39

**Comment by dushyant-basson** [comment]
I understand it's supposed to look for headers like src/ifcparse/Ifc2x3-definitions.h , but the IDE is trying to look for something else:
![image](https://user-images.githubusercontent.com/39452934/164589963-2a7a3d50-1c11-4c0c-86a9-99f2214b816e.png)
${SCHEMA_VERSIONS} has values like "2x3" : https://github.com/IfcOpenShell/IfcOpenShell/blob/80d86659928c6b46c23d6f6eeda2b988a741a152/cmake/CMakeLists.txt#L582
Does CMake need to be passed a schema? 
I'll check  IfcConvert.cpp .

**Comment by aothms** [comment]
>  ${SCHEMA_VERSIONS} has values like "2x3" : 

Yes, and the cmake script sets `-DIfcSchema=Ifc${s}` with `${s}` one of `${SCHEMA_VERSIONS}`

You can also take the approach taken in IfcParseExamples, just manually hardcode a schema at compiletime if you insist on using schema dependent code

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/examples/IfcParseExamples.cpp#L21
