### ISSUE TITLE
Error report when Installing the BlenderBIM add-on

### ISSUE THREAD

**Issue by tutu1313** [IfcOpenShell/IfcOpenShell#2154]
![image](https://user-images.githubusercontent.com/42027147/164450312-e660cef0-f9c1-4c78-ac9a-7c94f3687549.png)
![image](https://user-images.githubusercontent.com/42027147/164450507-6e0074b5-35a8-4cec-9969-5a228460dcb6.png)

Have a problem at the first step of trying this tool. Thank you very much for your help!!

**Comment by Moult** [comment]
For Blender 3.1 you need a py310 version from here: https://github.com/IfcOpenShell/IfcOpenShell/releases

See here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/docs/blenderbim/installation.rst for "Unstable installation" instructions
