### ISSUE TITLE
How to properly add entitites to a storey?

### ISSUE THREAD

**Issue by gkovacsds** [IfcOpenShell/IfcOpenShell#2155]
I'm writing a custom converter to IFC for our app, and ran into a problem.
After adding a 2nd storey to the building, all addBuildingProduct calls don't place the product item into the storey but into the site.
The first storey is OK. 
I create the IfcHierarchyHelper, IfcOwnerHistory, IfcProject, IfcSite, IfcBuilding manually.
Then I create the storey with file.addBuildingStorey

I place the products with:
product->setObjectPlacement(file.addLocalPlacement(storey_placement, objPos[0], objPos[1], objPos[2]));
 where
storey_placement = storey->ObjectPlacement();
 and
storey = file.addBuildingStorey(building, history);

What is the right way of placing a product on a storey?
Can I find an example with source code with multiple storeys?
Thank you!

**Comment by aothms** [comment]
For better or worse, a lot of behaviour in hierarchy helper is dependent on getSingle(), so when the 2nd storey get's added getSingle() no longer returns anything.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcHierarchyHelper.h#L360-L361

addBuildingProduct() takes an optional storey argument defaulted to nullptr. You can use that the explicitly specify the building storey.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcHierarchyHelper.cpp#L231

**Comment by gkovacsds** [comment]
Thanks, setting it as the 2nd parameter at addBuildingProduct works as it should. I missed that.
