### ISSUE TITLE
About deepcopy in IfcOpenShell-Python

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#2157]
When I tried to deep copy the representation of an item, the following error occur. Is there any way to fix this problem? Thank you.

`TypeError: can't pickle SwigPyObject objects`

**Comment by aothms** [comment]
Apparently `copy.deepcopy` depends on `pickle`. Indeed IfcOpenShell entity_instance objects are not pickleable.

IfcOpenShell has it's own implementation https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/element.py#L275

If you have a file `f` and instance `inst`, you can also copy (recursively, following forward attributes) to another file easily with:

~~~py
g = ifcopenshell.file(schema=f.schema)
g.add(inst)
g.write(...)
~~~

**Comment by Moult** [comment]
A note that "copying the representation of an item" depending on the interpretation, could be quite an involved task. What exactly are you trying to do? Perhaps there are existing API / util functions that already do this?

**Comment by CrossStyle** [comment]
@Moult I am going to copy an IfcCovering upward many times.

**Comment by CrossStyle** [comment]
@aothms Thank you very much, that's what I wanted.

**Comment by Martin15135215** [comment]
How can I copy an entire model?

i also first tried with copy.deepcopy... same error.

My workaround is currently like this:

```python
model = ifcopenshell.open("file.ifc")
model_2 = ifcopenshell.open("file.ifc")
```

What I would like would be something like this:
```python
model = ifcopenshell.open("file.ifc")
model_2 = model.copy()
```

And when I add an entity in model, there will be no entity added in model_2, since there are separate objects.

**Comment by Moult** [comment]
Why not just `model_2 = model`?

**Comment by Martin15135215** [comment]
I have two functions that do the same thing, however are differently implemented. So when I write a unit test:

```python
model = ifcopenshell.open("file.ifc")
model_2 = model.copy()

function_craete_somthing_a(model)
function_create_somthing_b(model_b)

assert function_look(model) == function_look(model)
```

and the `function_look`  has an assumption like this:

```python
---snip---
if len(model.by_type("IfcSomthing")) == 1:
    return model.by_type("IfcSomthing").Repesentations.Representation.etc.IfcCartesianValue.Value
else:
    raise Errror("Unclear since {len(model.by_type("IfcSomthing") IfcSomthing found"
```

so if i a dont have different model obejcts i can't use my function_look for assertions

**Comment by aothms** [comment]
Two ways, the first also copies header values and make sure numeric ids remain the same:

```
import ifcopenshell

f = ifcopenshell.open('d.ifc')

g = ifcopenshell.file.from_string(f.to_string())

h = ifcopenshell.file(schema=f.schema)
for inst in f:
  h.add(inst)
```

Note that you can also take 'snapshots' of trees of data with inst.get_info(recursive=True) these are nested dictionaries of python objects that you can also compare for equality.

**Comment by Martin15135215** [comment]
Thank you!
