### ISSUE TITLE
BB: using logic from Schema in IFC text literal

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2161]
There might be a logic reason for this, and if so, please close. 

Intuitively... 
![image](https://user-images.githubusercontent.com/507113/164987458-c4e96264-a7b6-449a-aac9-11af7648a30e.png)

seems like it should be...

![image](https://user-images.githubusercontent.com/507113/164987482-dd31fe65-fd66-43b1-a08e-db1311c0c5fe.png)

That way, it would be easier for the user just to use the schema to know exactly what values to input in this field.

**Comment by theoryshaw** [comment]
just another example...
![2022-04-24_12-03-57_Blender_blender](https://user-images.githubusercontent.com/507113/164989007-41efb481-fc5e-49f7-aecd-7884ba0fade0.png)
![2022-04-24_12-04-36_Blender_blender](https://user-images.githubusercontent.com/507113/164989010-8c75acb9-f7b4-4b18-aca5-b9b54f2b776d.png)

**Comment by Moult** [comment]
The logic is that the schema is actually harder. I had the same idea as you but to truly unambiguously specify the target (e.g. IfcDoorType of what? The type? The connecting element? The related product?) it is apparently very ugly to type.

I experimented with it here https://github.com/IfcOpenShell/IfcOpenShell/issues/2082 and it created this academic issue https://github.com/IfcOpenShell/IfcOpenShell/issues/2098 but essentially there seems to be no practical solution for now.
