### ISSUE TITLE
BB: change material of multiple elements

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#2164]
How can we change material of multiple elements (for example multiple walls) without clicking each element?

**Comment by Moult** [comment]
Typically objects would share a construction type and you'd only need to change the material at the construction type. Unfortunately at the occurrence level it is not possible to do bulk operations right now. What's the usecase? It'll help design the UX for it.

**Comment by vuicBABS** [comment]
ok thanks
