### ISSUE TITLE
BB: duplicate existing ifcgroup drawings

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2169]
In a previous versions there was the following refresh button, that came in quite handy if one duplicated a ifcgroup drawing in the outliner. 

Because a lot of times, new drawings are created from existing drawings.

![image](https://user-images.githubusercontent.com/507113/165670889-51099e31-a250-483b-9f92-7eaa3d24584a.png)

**Comment by Moult** [comment]
Now implemented thanks to the new duplicate drawing feature.
