### ISSUE TITLE
Using add-on with Blender as `bpy` Python module raises exception

### ISSUE THREAD

**Issue by emadpres** [IfcOpenShell/IfcOpenShell#2175]
Hi

We used to use this add-on in our scripts which were run like `blender -b --python <script which uses your addon to load ifc files>` and it works great.

But now we are trying to use Blender [as `bpy` Python module][1], so we basically run a python script which `import bpy`. With this change we are getting an exception when calling `ifc_importer.execute()`  which says: 
>  list.remove(x): x not in list

at the following line:
```py
# /home/bpy/.config/blender/3.2/scripts/addons/blenderbim/bim/__init__.py

def on_register(scene):
    handler.setDefaultProperties(scene)
    bpy.app.handlers.depsgraph_update_post.remove(on_register) # ERROR happens here: "list.remove(x): x not in list"
```

Stack Trace:
```stacktrace
on_register, __init__.py:133
_view_layer_update, ops.py:74
__call__, ops.py:109
clean_mesh, import_ifc.py:1123
execute, import_ifc.py:255
ifcImporter, ifc_converter.py:26
<module>, ifc_converter.py:52
```

Any thoughts on that?

---
OS: Ubuntu
Blender: 3.1
Add-on version: 220330 py310

[1]: https://wiki.blender.org/wiki/Building_Blender/Other/BlenderAsPyModule

**Comment by Moult** [comment]
I'm not familiar with using Blender a bpy, but if you isolate the offending line have you tried wrapping it in a `if not bpy.app.background:` block? If that works let me know happy to add the code in / accept PRs.

**Comment by emadpres** [comment]
Thanks. It fixed the crash. I'll create a PR.

**Comment by Moult** [comment]
@emadpres thanks so much! Will wait for the PR before closing.
