### ISSUE TITLE
BB: error when removing style

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2177]
files: https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/65b768bc766734716434ca69addf18de90bd525a/Random_Tests/IfcAnnotation_Text_Smart_Material

video: https://www.dropbox.com/s/rgn9m7vrjwcmnc0/2022-04-30_20-54-24_Blender_%5BDDropboxGitLabFreeMVD_WorkFlowRando_blender.mp4?dl=0

[blenderbim-220430-py310-win.zip](https://github.com/IfcOpenShell/IfcOpenShell/releases/download/blenderbim-220430/blenderbim-220430-py310-win.zip)
blender 3.1

**Comment by Moult** [comment]
I can't replicate this bug, maybe already fixed as a result of the more fundamental issue discovered and fixed in https://github.com/IfcOpenShell/IfcOpenShell/commit/f54a5cf6e03fd77311fae562833a4a0da9d38bf5 ?

**Comment by Moult** [comment]
Bump?

**Comment by theoryshaw** [comment]
yes, fixed. thx.
