### ISSUE TITLE
Build failed on Mac OS Sierra

### ISSUE THREAD

**Issue by jean-noelp** [IfcOpenShell/IfcOpenShell#218]
Hello,

I'm trying to compile the only one example which interesting me : IfcParseExamples.
(on Mac OS X Sierra)

- I generated project with CMake
- I installed boost library with "brew install boost"
- and now I use "make IfcParseExamples", but the following error is returned :
`In file included from /Users/jean-noel/workspace/IfcOpenShell/src/test/IfcParseExamples.cpp:20:
In file included from /Users/jean-noel/workspace/IfcOpenShell/src/test/../ifcparse/IfcFile.h:29:
In file included from /Users/jean-noel/workspace/IfcOpenShell/src/test/../ifcparse/../ifcparse/IfcSpfHeader.h:26:
In file included from /Users/jean-noel/workspace/IfcOpenShell/src/test/../ifcparse/../ifcparse/IfcWrite.h:31:
In file included from /usr/local/include/boost/variant.hpp:17:
/usr/local/include/boost/variant/variant.hpp:1437:35: error: no matching constructor for initialization of 'internal_T0'
      (aka 'boost::none_t')
        new( storage_.address() ) internal_T0();
                                  ^
/Users/jean-noel/workspace/IfcOpenShell/src/test/../ifcparse/../ifcparse/IfcWrite.h:47:22: note: in instantiation of
      member function 'boost::variant<boost::none_t, IfcWrite::IfcWriteArgument::Derived, int, bool, double,
      std::__1::basic_string<char>, boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >,
      IfcWrite::IfcWriteArgument::EnumerationReference, IfcUtil::IfcBaseClass *, IfcWrite::IfcWriteArgument::empty_aggregate_t,
      std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<double, std::__1::allocator<double> >,
      std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >,
      std::__1::vector<boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >,
      std::__1::allocator<boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> > > >,
      boost::shared_ptr<IfcEntityList>, IfcWrite::IfcWriteArgument::empty_aggregate_of_aggregate_t,
      std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >, std::__1::allocator<std::__1::vector<int,
      std::__1::allocator<int> > > >, std::__1::vector<std::__1::vector<double, std::__1::allocator<double> >,
      std::__1::allocator<std::__1::vector<double, std::__1::allocator<double> > > >, boost::shared_ptr<IfcEntityListList>,
      boost::detail::variant::void_>::variant' requested here
        class IFC_PARSE_API IfcWriteArgument : public Argument {
                            ^
/usr/local/include/boost/none_t.hpp:32:12: note: candidate constructor not viable: requires 1 argument, but 0 were provided
  explicit none_t(init_tag){} // to disable default constructor
           ^
/usr/local/include/boost/none_t.hpp:29:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1
      argument, but 0 were provided
struct none_t
       ^
1 error generated.
make[3]: *** [CMakeFiles/IfcParseExamples.dir/IfcParseExamples.o] Error 1
make[2]: *** [CMakeFiles/IfcParseExamples.dir/all] Error 2
make[1]: *** [CMakeFiles/IfcParseExamples.dir/rule] Error 2
make: *** [IfcParseExamples] Error 2
`

Anyone can help ?

**Comment by aothms** [comment]
Uhm, I am not on Sierra yet, so cannot test now, some thoughts:

* Which boost version did you use, is it compatible with the compiler version in Sierra?
* Is `BOOST_OPTIONAL_USE_OLD_DEFINITION_OF_NONE` known to the preprocessor? Perhaps you can unconditionally set it (i.e remove the if statement here [1]).
* If all this doesn't help, can you try changing the usage of `boost::none_t` to `boost::blank` (and `none` to `blank()`) here [2] [3] [4] [5] and see whether that helps, you might need to include boost/blank.hpp. Thanks for checking.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L469
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcWrite.h#L62
[3] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcWrite.cpp#L304
[4] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcWrite.cpp#L388
[5] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcWrite.cpp#L86

**Comment by ysangkok** [comment]
@aothms I have the same problem on Ubuntu 17.04 with Boost 1.63.

I tried your suggested fix and I get:

```
janus@janus-ThinkPad-T430:~/IfcOpenShell/build$ make
[  2%] Building CXX object CMakeFiles/IfcParse.dir/home/janus/IfcOpenShell/src/ifcparse/IfcWrite.cpp.o
/home/janus/IfcOpenShell/src/ifcparse/IfcWrite.cpp: In member function ‘virtual Argument* IfcWrite::IfcWritableEntity::getArgument(unsigned int)’:
/home/janus/IfcOpenShell/src/ifcparse/IfcWrite.cpp:86:31: error: expected primary-expression before ‘)’ token
   _setArgument(i, boost::blank);
                               ^
```

**Comment by aothms** [comment]
@ysangkok thanks for testing. I'll have a look if the code also behaves the same and merge it in soon.

**Comment by ysangkok** [comment]
By suggested fix I meant the second.

**Comment by jean-noelp** [comment]
I confirm, this one resolve the issue mentioned in this post :

> changing the usage of boost::none_t to boost::blank (and none to blank()) here [2] [3] [4] [5] and see whether that helps, you might need to include boost/blank.hpp. Thanks for checking.

>[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L469
>[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcWrite.h#L62
>[3] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcWrite.cpp#L304
>[4] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcWrite.cpp#L388
>[5] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcWrite.cpp#L86

Thank you !

**Comment by ysangkok** [comment]
On MSVC I also encountered the issue at https://github.com/IfcOpenShell/IfcOpenShell/blob/20c189c321e88cf7782540ee01bd76ef2526e71d/src/ifcparse/IfcWrite.h#L62

**Comment by ysangkok** [comment]
@jean-noelp Could you reopen this since it hasn't been merged yet?

**Comment by jean-noelp** [comment]
@ysangkok : sorry, I didn't know so much access were granted to me !

**Comment by aothms** [comment]
@ysangkok @jean-noelp since you have these changes on your file system, feel free to send in a pull request :)

**Comment by ysangkok** [comment]
see #221

**Comment by aothms** [comment]
Great, many thanks.
