### ISSUE TITLE
Can't export ifc model

### ISSUE THREAD

**Issue by laurindominik** [IfcOpenShell/IfcOpenShell#2182]
Hey, 
when having selected an ifc project and clicking on File --> Export --> Industry Foundation Classes (...) nothing happens. No window pops up
![image](https://user-images.githubusercontent.com/67796250/166417948-9f142497-2bab-47e5-bad0-d2a9cb15adb1.png)

**Comment by Moult** [comment]
That menu item is equivalent to saving a project. It will overwrite the IFC you have loaded, so no window will pop up.

But I agree, this is not intuitive to new users. I will change it so by default it is a "save as".

To save / save as, I'd recommend using these buttons here:

![2022-05-03-173500_337x240_scrot](https://user-images.githubusercontent.com/88302/166418443-0fda54e7-8f3f-4f0c-9e4f-6dae0a1a3668.png)

**Comment by laurindominik** [comment]
Ah okay! Thanks (y)
