### ISSUE TITLE
Instantiated IfcElements from Type Objects with fixed mesh (not empty) have no material assigned

### ISSUE THREAD

**Issue by Jesusbill** [IfcOpenShell/IfcOpenShell#2188]
If I create an IfcElementType with an object with an existing mesh, like a bolt, and I assign a material.
Then when I instantiate an IfcElement the material is not assigned.
This seems to work for "empty" types and the *Set/Usage materials

**Comment by Moult** [comment]
Ah yeah it's not necessary to assign the material because the material is inherited from the type. Latest commit should now display inherited materials.
