### ISSUE TITLE
BlenderBIM Add on 

### ISSUE THREAD

**Issue by hbenzako** [IfcOpenShell/IfcOpenShell#2195]
System Information
Operating system: PC à base de x64
Graphics card: vidia Quadro [T2000]with Max-Q Design

Blender Version
Broken:3.1 release

Short description of error

at step 3 of the installation of BlenderBIM, once the add-on module Import-Export : BlenderBIM is available in the list, and when I check the box I receive um error message
![preview-image](https://user-images.githubusercontent.com/105211402/167404190-456964b1-202d-43f9-9f3a-220b1fca4b4d.png)

**Comment by Moult** [comment]
Yeah this is a sign that I'm overdue to update the stable release. Download a py310 version from here and install that instead: https://github.com/IfcOpenShell/IfcOpenShell/releases

The stable release only supports Blender 3.0. There is a note about it on the download page but alas.
