### ISSUE TITLE
Using mmap 

### ISSUE THREAD

**Issue by jetablejfc** [IfcOpenShell/IfcOpenShell#22]
Hi,
  I changed code in order to use mmap for file handling under linux (not tested under windows).
This should help when communicating with outside programs (bimserver for example).

I'll post the patch later ...

Regards.

**Comment by jetablejfc** [comment]
The following patch should use an mmap'ed file as input  in IfcParse. It replaces the  FILE* stream  used in IfcSpfStream.h by  boost::iostreams::mapped_file_source .....
[IfcOpenShell_mmap_patch.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/89736/IfcOpenShell_mmap_patch.txt)

**Comment by jetablejfc** [comment]
A file mmapped in two processes is shared between the process (less memory is used). See for example the following code in java ....

import java.io.File;
import java.io.RandomAccessFile;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
 

//lsof : IfcConvert 23122  user  mem    REG    8,5 52923163  6034972 BOREL_IFC.ifc

public class Test {
	/*
	 * This Java application should be called with two args :
	 * args[0] is the pathname of IfcConvert
	 * args[1] is the pathname of the file to convert 
	 * 
	 * If the ifc file is big enough you'll see with lsof (lsof -f -p pid)
	 * that the file is mapped in memory in both  java and
	 * IfcConvert. 
	 * Moreover this memory segment is shared between the two processes as 
	 * their address are the same in each process.
	 * Memory is thus allocated only one time in the mmap scenario instead of two in the file/open 
        * one.
	 */
			
	 public static void main(String[] args) throws Exception {
		 RandomAccessFile file =  new RandomAccessFile(args[1],"r");
		 MappedByteBuffer mmap = file.getChannel().map(FileChannel.MapMode.READ_ONLY,0,file.length());
		 
		 
		 Runtime runtime = Runtime.getRuntime();
		 Process p = runtime. exec(args);
		 p.waitFor();
		 System.out.println(p.exitValue());
		 
		 
	 }
  
}

**Comment by aothms** [comment]
Thanks for this! I will have a look and see how the mmap paging impacts performance. Might even be more efficient regardless of other processes using the data.
