### ISSUE TITLE
unicode_literals

### ISSUE THREAD

**Issue by thorade** [IfcOpenShell/IfcOpenShell#220]
When using the Python wrapper on Python 2, unicode u"strings" will break e.g. the open function:

```python
from __future__ import unicode_literals
import ifcopenshell
ifc_file = ifcopenshell.open("./ifc2x3/26_04_2017_rooftop_3_zone_thin.ifc")
```
with TyperError, as also reported here:
https://github.com/swig/swig/issues/620

Is that something that could be easily fixed? 
If not, I will just not use unicode_literals, it is not essential.

**Comment by aothms** [comment]
I see. I can imagine some combination of `type(fn).__name__ == 'unicode'` and `fn.encode("utf-8")` would help here [1]. If this fixes things for you feel free to send in a pull request :)

But you might encounter similar issues in other parts of the code base (?)

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcopenshell-python/ifcopenshell/__init__.py#L59

**Comment by thorade** [comment]
Thanks.
Yes, it also happens for e.g.
`all_walls = ifc_file.by_type("IfcWall")`
or, I assume, basically everywhere where functions have strings as input.
So for now, the easiest solution for me is to just not use `unicode_literals`.
Or, even better, just use Python 3 and drop Python 2....

I'll close this, but it is here in case someone else gets unicode/str related type errors.
