### ISSUE TITLE
Extraction of ifc file classes from geometry 

### ISSUE THREAD

**Issue by Takieddinex** [IfcOpenShell/IfcOpenShell#2203]
Hello, 
I am simplifying my IFC files by keeping only the outer structure and removing everything inside. At first I managed to extract the files from the classes but this is not necessarily what I'm looking for so I'm looking to do this work from the geometry of the 3D objects (Xmin, Xmax, Ymin, Ymax, Zmin, Zmax) because it reassures me that only the exterior will be kept regardless of its class. 

Before i used https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcpatch/ifcpatch/recipes/ExtractElements.py

Thank you in advance 

![keyù](https://user-images.githubusercontent.com/95845810/168983790-80afde68-4065-49df-b18b-8da3005f74f5.PNG)

**Comment by aothms** [comment]
See #1523

**Comment by Takieddinex** [comment]
@aothms Thank you

**Comment by Takieddinex** [comment]
@aothms Hello, I have followed what was recommended by you to do the extraction except that I can not understand how I run with voxec if you can explain please
I remind that I am a beginner
Thank you for your time

**Comment by aothms** [comment]
I added a windows 32bit voxec.exe to the v0.3.0 release https://github.com/opensourceBIM/voxelization_toolkit/releases/tag/v0.3.0

Create a directory with voxec.exe the textfile (e.g voxelfile.txt) with the script and the ifc file(s). Then run from the command line with `voxec.exe voxelfile.txt --size=0.1 --chunk=16` (for example)

**Comment by Takieddinex** [comment]
thank you for your reply
I'm doing this with ubuntu and this is the code I'm trying to do 

![image](https://user-images.githubusercontent.com/95845810/169260025-7857083d-39ce-4977-8175-817ff2c2067e.png)

![image](https://user-images.githubusercontent.com/95845810/169260116-b6b9f4eb-fea4-4452-9e44-305a6a8e8f7a.png)

I also tested with jupyter 

![image](https://user-images.githubusercontent.com/95845810/169260341-7b587357-fe8d-4ec9-b805-74d627717853.png)

**Comment by Takieddinex** [comment]
ok, but I have to clone the whole folder or there is a specific file that allows voxec execution  

![image](https://user-images.githubusercontent.com/95845810/169264380-8c2094ae-fa33-4c71-b188-27d73582585e.png)

![image](https://user-images.githubusercontent.com/95845810/169264477-051a5a33-947e-48dd-b549-0c97f8b728ec.png)

**Comment by aothms** [comment]
Take voxec from here https://github.com/opensourceBIM/voxelization_toolkit/releases/tag/v0.2.3

In the 2nd case the file voxecfile.txt needs to exist in the same directory (or use the correct relative or absolute path)

**Comment by Takieddinex** [comment]
it shows me the same message knowing that I put all the files in a single folder and so I modified the last line by adding x = export_ifc 


![image](https://user-images.githubusercontent.com/95845810/169267401-e9407a3b-3718-442e-8e43-e342fabdb9f7.png)

**Comment by Takieddinex** [comment]
I managed to make it work on windows but the result is not what I'm looking for because it keeps all the interior structure of the building as you see on the screen 

![image](https://user-images.githubusercontent.com/95845810/169274712-6cac481a-514a-4a3d-94c3-f0af28776f1a.png)

![image](https://user-images.githubusercontent.com/95845810/169274928-5808e70a-14a2-4a90-ab0b-7daa23b5b31d.png)

**Comment by aothms** [comment]
You can reduce the voxel size with `--size` 0.1 is indeed a bit large but with 32bit you can't have that much detail. So switch to linux if you want smaller voxel size.

On linux you have `simplifier_ifc` not `simplifier_ifc.txt`

**Comment by Takieddinex** [comment]
I managed to get it to work, for Windows: Don't let the script stop just with the last line, provid 2 empty lines. For Ubuntu : the script must stop right at the last line.

**Comment by Moult** [comment]
Sounds like this can now be closed?

**Comment by Takieddinex** [comment]
yes, you can close it, but otherwise I had a problem with the voxelization extraction https://github.com/opensourceBIM/voxelization_toolkit/issues/9#issuecomment-1134332290
