### ISSUE TITLE
Sectional view by IfcOpenShell C++

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [IfcOpenShell/IfcOpenShell#2204]
Hi, I'm studying the IfcOpenShell C++, and want to extract the sectional view of the model.
Could the IfcOpenShell work?

Thank you for your help

**Comment by aothms** [comment]
Have a look at the SvgSerializer.cpp which uses OCCT hidden line and section algos to derive 2D views (in any orientation) from the 3D IFC model.

If you dare have a look at this monster issue where all the ins and outs are discussed https://github.com/IfcOpenShell/IfcOpenShell/issues/1153

**Comment by SHAWNZHANGSH** [comment]
Thank you very much, aothms!
