### ISSUE TITLE
Cannot compile on *nix

### ISSUE THREAD

**Issue by RedTurkey** [IfcOpenShell/IfcOpenShell#2210]
I have been trying to compile the latest version of IfcOpenShell for the last week now but to no avail (Ubuntu 18).  

I can get up to the make -j step (the cmake step does not send back any warning or error) but it always fail at the svgfill step (approximately at 20%).  

Trying to build svgfill directly (following the cmake options described on its Github page) also fail, stating that it need to link to a library and not a directory.  

Trying to use the python file in the nix folder directly yield a syntax error unfortunately.  

Here are the version of the libraries used to compile :  

Cmake 3.20.2
OCCT 7.6
gcc 7.5.0
g++ 7.5.0
python 2.7.17
python3 3.6.9

Here is the list of packages I install with apt-get (I know a lot might not be useful to my case or in duplicate, but I became desperate and installed every package I could find used in the different bash/python files and sub-modules) :  
- git
- cmake 
- gcc
- g++
- libboost-all-dev 
- libcgal-dev 
- flex 
- bison 
- libsvgpp-dev 
- libpcre3-dev 
- libxml2-dev 
- python-all-dev 
- swig
- build-essential 
- libssl-dev
- libc6-dev 
- libfreetype6-dev 
- mesa-common-dev 
- libffi-dev 
- libfontconfig1-dev 
- libsqlite3-dev 
- libbz2-dev 
- zlib1g-dev 
- liblzma-dev 
- libreadline-dev 
- libncursesw5-dev 
- uuid-dev 
- libgl1-mesa-dev 
- libxext-dev 
- libxmu-dev 
- libxmu-headers 
- libxi-dev
- software-properties-common 
- libtool 
- autoconf 
- automake
- gfortran 
- gdebi 
- gcc-multilib 
- libx11-dev 
- libglu1-mesa-dev 
- libfreetype6
- tcl 
- tcl-dev 
- tk 
- tk-dev 
- doxygen

Here are the steps that diverge from the README :  
- Had to install a more recent version of cmake as the default one (3.10.2) was having some unknown policies error  
- Had to compile the latest Open Cascade myself as the packages on the README were not available for Ubuntu 18  
- Had to get the .hpp file from `https://github.com/nlohmann/json.git`/`single_include` for GLTF support (and copy it into /usr/include)  

And finally, here is the cmake command I used :  
`sudo cmake ../cmake -DOCC_INCLUDE_DIR="/usr/local/include/opencascade" -DOCC_LIBRARY_DIR="/usr/local/lib/" -DOPENCOLLADA_INCLUDE_DIR="/usr/local/include/opencollada" -DOPENCOLLADA_LIBRARY_DIR="/usr/local/lib/opencollada" -DPCRE_LIBRARY_DIR="/usr/lib/x86_64-linux-gnu/" -DCGAL_INCLUDE_DIR="/usr/include" -DGMP_INCLUDE_DIR="/usr/include" -DMPFR_INCLUDE_DIR="/usr/include" -DGMP_LIBRARY_DIR="/usr/lib/x86_64-linux-gnu" -DMPFR_LIBRARY_DIR="/usr/lib/x86_64-linux-gnu" -DHDF5_SUPPORT=Off -DGLTF_SUPPORT=1`  

Here is the resulting log from this command :  
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BINDIR: bin
-- INCLUDEDIR: include
-- LIBDIR: lib
-- JSON for Modern C++ header file found
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.4") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /usr/include (found version "1.65.1") found components: system program_options regex thread date_time chrono atomic 
-- Boost include files found in /usr/include
-- Boost libraries found in /usr/lib/x86_64-linux-gnu
-- Looking for Open CASCADE include files in: /usr/local/include/opencascade
-- Looking for Open CASCADE library files in: /usr/local/lib
-- Required Open Cascade Library files found
-- OpenCOLLADA library files found
-- OpenCOLLADA header files found
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.12")  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9") 
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
CMake Deprecation Warning at /home/vincent_boosten/IfcOpenshell/src/svgfill/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at /home/vincent_boosten/IfcOpenshell/src/svgfill/CMakeLists.txt:6 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for CGAL include files in: /usr/include
-- Found Boost: /usr/include (found version "1.65.1")  
-- Boost include files found in /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vincent_boosten/IfcOpenshell/build
```

Apart from those change, I followed the documentation, using --recursive when cloning the repository (and "git submodule init & git submodule update" just in case too) so I'm at a loss here.  
I also tried with OCE instead of OCCT to no avail.  

Here is the latest log when I use the make command :  
```
liblibsvgfill.a(svgfill.cpp.o):svgfill.cpp:(.text._ZN4CGAL18Arrangement_zone_2INS_24Arrangement_on_surface_2INS_20Arr_segment_traits_2INS_5EpickEEENS_36Arr_bounded_planar_topology_traits_2IS4_NS_16Arr_default_dcelIS4_EEEEEENS_30Arr_inc_insertion_zone_visitorIS9_EEE12compute_zoneEv[_ZN4CGAL18Arrangement_zone_2INS_24Arrangement_on_surface_2INS_20Arr_segment_traits_2INS_5EpickEEENS_36Arr_bounded_planar_topology_traits_2IS4_NS_16Arr_default_dcelIS4_EEEEEENS_30Arr_inc_insertion_zone_visitorIS9_EEE12compute_zoneEv]+0x9a2): more undefined references to `CGAL::assertion_fail(char const*, char const*, int, char const*)' follow
collect2: error: ld returned 1 exit status
svgfill/CMakeFiles/svgfill.dir/build.make:100: recipe for target 'svgfill/svgfill' failed
make[2]: *** [svgfill/svgfill] Error 1
CMakeFiles/Makefile2:1048: recipe for target 'svgfill/CMakeFiles/svgfill.dir/all' failed
make[1]: *** [svgfill/CMakeFiles/svgfill.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 20%] Linking CXX static library libIfcParse.a
[ 20%] Built target IfcParse
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
```

Here are the CMakeOutput.log and CMakeError.log files :  
[CMakeOutput.log](https://drive.google.com/file/d/1obXRA6D7LtGnbdXtzarHn10KP1iNxESE/view?usp=sharing)  
[CMakeError.log](https://drive.google.com/file/d/1MjeuEnxxbTfXx5yUPTCeFO8IIHqndmvY/view?usp=sharing)  

Any idea on what I am doing wrong ?

**Comment by PlumpMath** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/releases

It seems to provide a built version.

**Comment by aothms** [comment]
> 

liblibsvgfill.a(svgfill.cpp.o):svgfill.cpp:(.text.CGAL::Arrangement_zone_2<CGAL::Arrangement_on_surface_2<CGAL::Arr_segment_traits_2<CGAL::Epick>, CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_segment_traits_2<CGAL::Epick>, CGAL::Arr_default_dcel<CGAL::Arr_segment_traits_2<CGAL::Epick> > > >, CGAL::Arr_inc_insertion_zone_visitor<CGAL::Arrangement_on_surface_2<CGAL::Arr_segment_traits_2<CGAL::Epick>, CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_segment_traits_2<CGAL::Epick>, CGAL::Arr_default_dcel<CGAL::Arr_segment_traits_2<CGAL::Epick> > > > > >::compute_zone()[CGAL::Arrangement_zone_2<CGAL::Arrangement_on_surface_2<CGAL::Arr_segment_traits_2<CGAL::Epick>, CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_segment_traits_2<CGAL::Epick>, CGAL::Arr_default_dcel<CGAL::Arr_segment_traits_2<CGAL::Epick> > > >, CGAL::Arr_inc_insertion_zone_visitor<CGAL::Arrangement_on_surface_2<CGAL::Arr_segment_traits_2<CGAL::Epick>, CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_segment_traits_2<CGAL::Epick>, CGAL::Arr_default_dcel<CGAL::Arr_segment_traits_2<CGAL::Epick> > > > > >::compute_zone()] 0x9a2): more undefined references to `CGAL::assertion_fail(char const*, char const*, int, char const*)' follow

> Any idea on what I am doing wrong ?

It's something internally in CGAL. How did you install it? At some point CGAL switched to header only. My guess is CGAL in Ubuntu 18 is not header-only, but the svgfill script assumes so. I don't think it's worth the trouble to try and detect this. Can you install a newer CGAL version or update to a newer Ubuntu?

**Comment by aothms** [comment]
Semi-automated builds are available here https://github.com/IfcOpenBot/IfcOpenShell/commit/1b1fd1e6c5777cb27ca3a65357855421a8e77bf9#comments

**Comment by RedTurkey** [comment]
By compiling and installing the latest version of CGAL instead of using apt-get, it finally worked and we have a working executable.  
Thank you for your help.
