### ISSUE TITLE
IfcConverter doesn't generate any floor

### ISSUE THREAD

**Issue by francesco-gallo** [IfcOpenShell/IfcOpenShell#2211]
Hello, I'm trying to understand why I can't generate any floor using the svg output using the attached model, using the already built version of IfcConverter 0.7.0 (win64).

[This is the model](https://github.com/IfcOpenShell/IfcOpenShell/files/8756145/2021-014_ALA_RM042_ARC_R02.zip).

Launching the converter with the params `IfcConvert 2021-014_ALA_RM042_ARC_R02.ifc -vv output.svg` logs only
```
[Notice] [2022-05-23 17:57:25] include entities IfcSpace
Done creating geometry (0 objects)
[Notice] [2022-05-23 17:57:26] No geometrical elements found or none succesfully converted
```

I tried to google the last message, and corrected the parameters adding `--exclude entities IfcOpeningElement`, I get a lot of warnings like
```
[Warning] [2022-05-23 18:01:24] Face with no boundaries
#60167=IfcFace((#60166))
[Warning] [2022-05-23 18:01:24] Failed to convert face:
#60167=IfcFace((#60166))
[Warning] [2022-05-23 18:01:32] Element not written to SVG due to section heights
#87453=IfcBeam('0i21AZbxf74BcaeLwyEDhg',#20,'STR_SB_SB02:150x160mm:521016',$,'STR_SB_SB02:150x160mm',#87439,#87452,'521016')
```

and the output becomes

```
Done writing geometry (779 objects)
```

but the svg is still empty.

Does it depend on how is the model made? Or are there specific flags that I could use?

Thanks

**Comment by aothms** [comment]
Hm, the issue appears to be the "georeferencing" coords in the model.

~~~
#109=IFCCARTESIANPOINT((289648.66619009263,4640961.3705280647,16.817999999999998));
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#110=IFCDIRECTION((0.92862799370095495,0.37101219564178683,0.));
#111=IFCAXIS2PLACEMENT3D(#109,#9,#110);
#112=IFCLOCALPLACEMENT($,#111);
#113=IFCSITE('1VS$8NKVr3VuJSUXJAk87Z',#20,'Default',$,$,#112,$,$,.ELEMENT.,(42,21,31,181945),(-71,-3,-24,-263305),0.,$,$);
~~~

You can see above the large coordinates (thousands of kilometres) that move the model very far away from the origin. This is fairly typical with models from Revit

Tbh I didn't take the time to figure out exactly why this breaks writing SVG. A quick fix would be to add --site-local-placement to ignore any transformations introduced at the site.

![afbeelding](https://user-images.githubusercontent.com/1096535/169968539-719c28b2-0e8f-4f43-8a30-1a00260a4e9b.png)

(with ` --section-height-from-storeys --bound=1024x1024 --exclude entities IfcOpeningElement`)

**Comment by francesco-gallo** [comment]
Oh, thanks a lot for the detailed explanation!
