### ISSUE TITLE
BCFv3 "get_comments" error

### ISSUE THREAD

**Issue by AToradaIBIM** [IfcOpenShell/IfcOpenShell#2212]
There's an error when you try to get the comments of a topic using the BCF util V3.

The error that is throwing is "KeyError: Topics"  and this is because in the line 649 is trying to parse the element "Topics" instead of "Topic".
Based on the XSD there's no "Topics" element so this must be a missclick.

Here's the code:

```
def get_comments(self, guid):
        comments = {}
        data = self._read_xml(os.path.join(guid, "markup.bcf"), "markup.xsd")
        if "Comments" not in data["Topics"]:
            return comments
```

It's located on [this file](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/bcf/src/bcf/v3/bcfxml.py).

**Comment by aothms** [comment]
Not an active user of this part of the codebase, but I think you are correct. Can you send in a Pull Request (you can just use the edit button in the github web interface for that these days).

**Comment by Moult** [comment]
Thanks so much! Indeed a typo.
