### ISSUE TITLE
element geometry isn't read correctly

### ISSUE THREAD

**Issue by RobinVanTol** [IfcOpenShell/IfcOpenShell#2213]
I found an ifc element that doesnt have its geometry read correctly by ifcopenshell, it looks as though it has no geometry at all. see image below
![Screenshot 2022-05-24 160739](https://user-images.githubusercontent.com/38659478/170057682-059651b6-ea9c-4aba-879c-1ae8aaa0a8f4.png)
however when visualised with solibri it does have geometry.
![Screenshot 2022-05-24 161519](https://user-images.githubusercontent.com/38659478/170057836-61460d8e-d85d-432d-b47b-fd020c5d95bb.png)

here is an ifc file containing the broken element
[broken_element.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8763577/broken_element.zip)

from issue #2208 
Reading the geometry works correctly on the version on master, however after switching to the v0.6.0 branch it no longer works

**Comment by RobinVanTol** [comment]
Is there other information i could provide to make it easier to solve this?

**Comment by aothms** [comment]
Use v0.7.0 and convert with `IfcConvert --strict-tolerance` / `settings(STRICT_TOLERANCE=True)`. We're thinking of making it the default for 0.7 once we have done a proper analysis.

![afbeelding](https://user-images.githubusercontent.com/1096535/171815819-db5557d9-1362-4925-a9c8-2d777474ca2c.png)

**Comment by RobinVanTol** [comment]
Sorry for taking so long to get back to this, i updated to version 0.7.0 which already changed the ouput to this:
![image](https://user-images.githubusercontent.com/38659478/172589576-c5bfd082-2ce8-4078-876e-4da3a680bbe0.png)
Quite the improvement, however, adding the STRICT_TOLERANCE=True had no effect, to clarify i am now using the following settings:
`self.__geom_settings = geom.settings(STRICT_TOLERANCE=True, USE_PYTHON_OPENCASCADE=True, USE_WORLD_COORDS=True)`
Is that an incorrect usage or is it not compatible with other settings?

Just for good measure I am now using the version made by ifcopenbot in this commit https://github.com/IfcOpenBot/IfcOpenShell/commit/e508fb44f25da05c3be9b9552c405b3c0ba58f23#comments

**Comment by aothms** [comment]
Yes, @Moult and I figured out recently that some of the settings didn't work with create_shape() that worked on geom.iterator(). Probably you're seeing this. There isn't a build yet after this commit, but I started one, keep an eye on https://github.com/IfcOpenBot/IfcOpenShell/commits/v0.7.0

**Comment by RobinVanTol** [comment]
I used the new version but still get the same result.

**Comment by Moult** [comment]
Closing as fixed :)
