### ISSUE TITLE
Element with representation type "Body", "CSG" is not correctly extracted

### ISSUE THREAD

**Issue by theRealSuperMario** [IfcOpenShell/IfcOpenShell#2217]
Hello,

I have an element which is described by a CSG Tree

```bash
...
#102112= IFCBOOLEANRESULT(.DIFFERENCE.,#101655,#101675);
#102113= IFCBOOLEANRESULT(.DIFFERENCE.,#102112,#101723);
#102114= IFCBOOLEANRESULT(.DIFFERENCE.,#102113,#101769);
#102115= IFCBOOLEANRESULT(.DIFFERENCE.,#102114,#101821);
#102116= IFCBOOLEANRESULT(.DIFFERENCE.,#102115,#101878);
#102117= IFCBOOLEANRESULT(.DIFFERENCE.,#102116,#101928);
#102118= IFCBOOLEANRESULT(.DIFFERENCE.,#102117,#101979);
#102119= IFCBOOLEANRESULT(.DIFFERENCE.,#102118,#102029);
#102120= IFCBOOLEANRESULT(.DIFFERENCE.,#102119,#102080);
#102121= IFCSHAPEREPRESENTATION(#180,'Body','CSG',(#102120));
...
#102138= IFCWALL('2RwgPuboUoHhEfu_KYpq95',#12,'Wand-003',$,$,#101553,#102134,,.NOTDEFINED.);
```

The problem is that the differences are not actually applied. I found the #2202 issue which might be related, but I am not sure if it is actually the same, hence I opened another issue.

- I also checked if the information in the file is correct by "manually" subtracting the elements from the CSG tree. I made a plot comparing the CSG information with the ifcopenshell output
- I tried it with two different versions, the `0.6.0` and the `v0.70`, which is the most recent one I could find from https://s3.amazonaws.com/ifcopenshell-builds
- A fully-functional file containing only a single example is attached.

It would be great if you could let me know if you are aware of the problem, if it is fixed and when I can respect an `ifcopenshell-python` build that includes the fix. I noticed that the last build on https://s3.amazonaws.com/ifcopenshell-builds is from 3months ago, and other ones were more frequent.

![csg_shape_rep_parsing_problem_ifcopenshell-version_* (HEAD detached at 1b1fd1e6)-1b1fd1e6](https://user-images.githubusercontent.com/6517465/170699880-e266f628-3822-43e3-b859-66fc63a761be.png)

![csg_shape_rep_parsing_problem_ifcopenshell-version_0 6 0b0](https://user-images.githubusercontent.com/6517465/170699893-3392bdb5-3acc-4f4e-8aff-88d9d42e23df.png)

[csg_parsing_bug.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8786705/csg_parsing_bug.txt)

**Comment by aothms** [comment]
For me the file converted ok using my local dev environment, I'll initiate a new build for you to verify.

![afbeelding](https://user-images.githubusercontent.com/1096535/171392408-fa916c44-0542-4f86-bacc-04f028ecaf41.png)

**Comment by theRealSuperMario** [comment]
Very nice, I can confirm that this works now.

Thanks for the quick response

![csg_shape_rep_parsing_problem_ifcopenshell-version_* (HEAD detached at 41990164)-41990164](https://user-images.githubusercontent.com/6517465/171662705-aef465bd-610a-4316-af5d-39e1802af8d9.png)
