### ISSUE TITLE
hole on a slab disappear through ifcConvert

### ISSUE THREAD

**Issue by Ttofuuu** [IfcOpenShell/IfcOpenShell#2220]
Recently I test a .ifc  file with only a slab, and I dig a hole on this slab with IfcOpeningElment:
![image](https://user-images.githubusercontent.com/49158715/171427944-59385e8e-a7fe-4e25-a068-6cac154cced1.png)
Both slab and opening's shapes are defined in Extruded Solid type.
here the origin ifc file:
[temp2.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8815038/temp2.ifc.txt)
but when I drag it into IfcConvert v0.6.0 to get a .obj file, I find the hole disappear:
![image](https://user-images.githubusercontent.com/49158715/171428469-642f072b-d10d-4e24-830a-657e62f34eee.png)
So I wonder will ifcConvert ignore this digging action with IfcOpeningElement, or is something wrong in this ifc file?

**Comment by aothms** [comment]
The opening doesn't have an ObjectPlacement. We check for it here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcGeomFunctions.cpp#L2125

There is a rule that if a representation exists on a product then the placement must also exist

~~~
	PlacementForShapeRepresentation : (EXISTS(Representation) AND EXISTS(ObjectPlacement))
OR (EXISTS(Representation) AND
(SIZEOF(QUERY(temp <* Representation.Representations | 'IFC4X3_DEV_be68a416.IFCSHAPEREPRESENTATION' IN TYPEOF(temp))) = 0))
OR (NOT(EXISTS(Representation)));
~~~

http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcProduct.htm#5.1.3.10.7-Formal-representation

**Comment by Ttofuuu** [comment]
thanks, it works now after adding LocalPlacement of the opening
