### ISSUE TITLE
Windows target missing from latest build

### ISSUE THREAD

**Issue by kongsgard** [IfcOpenShell/IfcOpenShell#2222]
I noticed that builds for Windows were not included in the latest build run: https://github.com/IfcOpenBot/IfcOpenShell/commit/419901649ea613cb5a5411d6f514210d5c14d1dc#comments.

Previously, there was a `Win` column in this overview:
https://github.com/IfcOpenBot/IfcOpenShell/commit/419901649ea613cb5a5411d6f514210d5c14d1dc#comments
 
Any particular reason it's removed? Where can I find corresponding builds for Windows?

**Comment by aothms** [comment]
The windows 2009 image (AMI) on amazon that we use to build expired, so the windows build wasn't properly initiated. Thanks for bringing this to our attention, I've restarted a new build.
