### ISSUE TITLE
BB: How to model IfcReinforcingBar properly?

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#2225]
How to model rebars correctly?
Should we extrude a surface on a Bezier, Nurbs, Path type curve? Or should we do something else?
Thanks in advance.

**Comment by theoryshaw** [comment]
wonder this too, here: https://community.osarch.org/discussion/928/

**Comment by Moult** [comment]
Any curve object with a bevel radius will now export as a swept disk solid. This typically applies to rebar, but also applies to things like cables or piping.

Note that the underlying curve will be treated as a polygonal line, so no smooth bezier falloffs - sharp angles everywhere. I guess now we need to improve the QoL by building filleting and turning tools.

**Comment by vuicBABS** [comment]
Thank you very much!
