### ISSUE TITLE
get elements' properties in different ifc schema

### ISSUE THREAD

**Issue by Ttofuuu** [IfcOpenShell/IfcOpenShell#2229]
currently I have gotten IfcWindows' properties in a Ifc4 file using code below:
```
#define IfcSchema Ifc4

auto rels = iterator->get()->product()->as<IfcSchema::IfcElement>()->IsDefinedBy();
for (auto& rel : *rels) {
    Argument* inst = rel->get("RelatingPropertyDefinition");//argument of IfcPropertySet
    if (inst->isNull()) {
        std::cout << "no relating property of this component: " << iterator->get()->guid() << sed::endl;
    }
    for (int i = 0; i < inst->size(); i++) {
        IfcUtil::IfcBaseClass* ist = static_cast<IfcUtil::IfcBaseClass*>(inst[i]);

        IfcEntityInstanceData* mid_data = new IfcEntityInstanceData(ist->data());
        IfcSchema::IfcPropertySet ifc_property_set(mid_data);

        auto property_list = ifc_property_set.HasProperties();
        for (auto& properti : *property_list) {
            //check every properti
        }
    }
}
```
it works well on Ifc4 file, but when it comes to Ifc2x3 file, it will crash on 
```
auto rels = iterator->get()->product()->as<IfcSchema::IfcElement>()->IsDefinedBy();
```
I wonder can I have a method to get the properties well, on whatever schema the ifc file is?
And is there any method more simple to get the properties?

**Comment by Ttofuuu** [comment]
to use templates I should let the program know which schema the input ifc file is, how can I let it know that?

**Comment by aothms** [comment]
An ugly if statement somewhere like this https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcwrap/IfcGeomWrapper.i#L540 would do the trick. It probably can be wrapped into a function that dispatches to another function based on runtime schema of the file.

**Comment by Ttofuuu** [comment]
good ,it's ugly, but works
