### ISSUE TITLE
Opening subtraction for wall failing

### ISSUE THREAD

**Issue by RedTurkey** [IfcOpenShell/IfcOpenShell#2237]
This model unfortunately fail at the opening subtraction part for the walls, which result in the hole for the window not being here.  
Here is the file for testing :  
[Sample_wall_openings.ifc](https://drive.google.com/file/d/1Rm3vqTd1mDILoQF1V8qOCz6IRRvOSjp5/view?usp=sharing)

**Comment by rajanbrussels** [comment]
As an additional comment: this seems to happen in particular for multi-layered walls with openings (exported from ArchiCAD).

**Comment by rajanbrussels** [comment]
Here is the command and corresponding output. Several options have been used, but with no effect on this matter. Thanks!

```
$ ./IfcConvert-v0.7.0 Sample_wall_openings.ifc Sample_wall_openings.glb
IfcOpenShell IfcConvert v0.7.0-e508fb44 (OCC 7.5.3)
Scanning file...
Done scanning file   
Parsing input file took 12 seconds
Creating geometry...
Done creating geometry (47 objects)                                

Log:
[Error] [2022-06-11 10:36:24] {2uaq6LMSJ_QEOGzsieuBU9} Opening subtraction failed for 44 openings
#254583=IfcWall('2uaq6LMSJ_QEOGzsieuBU9',#12,'MurExt-028',$,$,#254518,#254579,'B8934195-59C4-FE68-E610-F76B28E0B789')
[Error] [2022-06-11 10:36:28] {2uaq6LMSJ_QEOGzsieuBU9} Opening subtraction failed for 22 openings
#254583=IfcWall('2uaq6LMSJ_QEOGzsieuBU9',#12,'MurExt-028',$,$,#254518,#254579,'B8934195-59C4-FE68-E610-F76B28E0B789')
[Error] [2022-06-11 10:36:41] {0aAwmwW1fPWr5NLFh9azGa} Opening subtraction failed for 44 openings
#987041=IfcWall('0aAwmwW1fPWr5NLFh9azGa',#12,'MurExt-028',$,$,#986976,#987037,'242BAC3A-801A-5983-5157-54FAC993D424')
[Error] [2022-06-11 10:36:45] {0aAwmwW1fPWr5NLFh9azGa} Opening subtraction failed for 22 openings
#987041=IfcWall('0aAwmwW1fPWr5NLFh9azGa',#12,'MurExt-028',$,$,#986976,#987037,'242BAC3A-801A-5983-5157-54FAC993D424')
[Error] [2022-06-11 10:37:13] {1eO_PRRHAVLHR6vBH36_Vm} Opening subtraction failed for 66 openings
#1130471=IfcWall('1eO_PRRHAVLHR6vBH36_Vm',#12,'MurExt-028',$,$,#1130406,#1130467,'6863E65B-6D12-9F55-16C6-E4B4431BE7F0')
[Error] [2022-06-11 10:37:16] {1eO_PRRHAVLHR6vBH36_Vm} Opening subtraction failed for 22 openings
#1130471=IfcWall('1eO_PRRHAVLHR6vBH36_Vm',#12,'MurExt-028',$,$,#1130406,#1130467,'6863E65B-6D12-9F55-16C6-E4B4431BE7F0')


Conversion took 1 minute 18 seconds
```

GLB output after IFC-tGLB conversion using IfcConvert-v0.7.0:

![image](https://user-images.githubusercontent.com/107267287/173180514-6b5e3623-ae85-48ad-a9dd-e6f54cbab797.png)

Desired output:

![image](https://user-images.githubusercontent.com/107267287/173181323-9ef2b18f-e79a-4ffa-a52e-25bc3a8061ad.png)

**Comment by aothms** [comment]
> this seems to happen in particular for multi-layered walls with openings

Correct, we already had logic in place for that for IfcBooleanResult in #2202 (26d old) but apparently left out applying the same logic to IfcOpeningElement.

I already said elsewhere I'm not a big fan of this export mechanism (extrusion of compound profile) there are already layersets and element decompositions. This is a third mechanism and I'm not seeing any benefits.
