### ISSUE TITLE
BB: angle dimensions

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2254]
I might be missing something, but intuitively the angle dimension in [this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/commit/d6bab39377873395b144818b9e242e20008dfa40) file, seems like to should look like the last image below. 
![image](https://user-images.githubusercontent.com/507113/177009286-25bbd241-7242-4cb7-918b-860bb6a0574a.png)

![image](https://user-images.githubusercontent.com/507113/177009296-e480f0e3-e884-4277-a60a-575e36e3d0b8.png)

![image](https://user-images.githubusercontent.com/507113/177009316-572b6d72-e383-4481-bd42-96d58e7f9de6.png)

**Comment by Moult** [comment]
Agreed it's not intuitive at all, currently the code logic treats the 3D cursor as the centerpoint of the arc, which leads to that result.

**Comment by Andrej730** [comment]
@theoryshaw is it still an issue?

Tested with new angle operator introduced in d88510b91961dc3e1bef7f40478b2e66bc58d73a, svg print result looks like:


<img src="https://user-images.githubusercontent.com/9417531/211154684-1c743a8b-8746-4590-bf76-6aff3ae18469.png" width=50% height=50%>


tested files:
[Annotation_Dimension_Angle_02.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10366436/Annotation_Dimension_Angle_02.ifc.txt)
[Annotation_Dimension_Angle_01.blend.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10366435/Annotation_Dimension_Angle_01.blend.txt)

**Comment by theoryshaw** [comment]
Very cool... works great!
