### ISSUE TITLE
BB: can't access properties in Pset

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2255]
video: https://www.dropbox.com/s/ba6vmp6o6e01v8k/2022-07-02_13-49-11_Blender_%5BCUsersOwnerDesktopuntitled.blend%5D_blender.mp4?dl=0

blenderbim-220629-py310-win.zip

**Comment by theoryshaw** [comment]
seems to work in blenderbim-220619

**Comment by vulevukusej** [comment]
@theoryshaw - can you share the error message?

**Comment by vulevukusej** [comment]
@theoryshaw I tested in 220703 and it seems to work fine.

**Comment by theoryshaw** [comment]
yep works with 220704.  Thanks @vulevukusej
