### ISSUE TITLE
Error when editing object attributes

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2264]
When trying to edit an attribute, I get an error:
```
Python: Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\attribute\ui.py", line 75, in draw
    draw_ui(context, self.layout, "Object", AttributesData.data["attributes"])
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\attribute\ui.py", line 39, in draw_ui
    blenderbim.bim.helper.draw_attributes(props.attributes, layout, copy_operator="bim.copy_attribute_to_selection")
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\helper.py", line 33, in draw_attributes
    draw_attribute(attribute, row, copy_operator)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\helper.py", line 37, in draw_attribute
    value_name = attribute.get_value_name()
AttributeError: 'Attribute' object has no attribute 'get_value_name'
    draw_attribute(attribute, row, copy_operator)
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\helper.py", line 37, in draw_attribute
    value_name = attribute.get_value_name()
AttributeError: 'Attribute' object has no attribute 'get_value_name'
```

I'm not sure what to make of this one..
![issue](https://user-images.githubusercontent.com/83825269/177264746-8d9aebaf-b49f-4c24-a784-fe81878c60c8.gif)

**Comment by vulevukusej** [comment]
stopping the code just before the error reveals nothing out of the ordinary.  I'm not sure why get_value_name() is missing?
![image](https://user-images.githubusercontent.com/83825269/177265275-db8ff28e-153d-47b7-8a5b-587079ffab16.png)

**Comment by Gorgious56** [comment]
I've been noticing the error too and I can't for the life of me understand why. The `Attribute` instance **should** have a `get_value_name` method. Unless it has been monkey-patched somewhere in the code which I doubt it has been. Or it refers to an instance that somehow didn't get initialized properly with the method members ? I'll try and investigate further.

**Comment by Gorgious56** [comment]
I suspect it has do with [bpy.types.Attribute](https://docs.blender.org/api/current/bpy.types.Attribute.html?highlight=attribute#bpy.types.Attribute) and a name collision but not I'm not sure. I changed the class name to `BimAttribute` to test it out and I still have the error.

**Comment by Gorgious56** [comment]
@vulevukusej It might not be related but this throws an error because `Attribute` doesn't have `enumerated_values` attribute.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/helper.py#L41-L49

Do you by any chance have uncommited code ?

**Comment by vulevukusej** [comment]
maybe i could just change the line to `if len(getattr(attribute, "enumerated_values", [])) != 0`

**Comment by Gorgious56** [comment]
Oooooh Alright I understand. Apparently by inheriting `Attribute` with `IfcSimpleProperty` you erased `Attribute`'s plain old python methods. That's I guess an undocumented quirk of the API. I think in general you don't want to inherit from classes other than the ones that come from `bpy.types`, that way you can avoid this kind of awful bugs.

If I remove the definition of `IfcSimpleProperty`, the code works again.

I think I now understand what you are achieving with the code, but I wonder if it's really necessary to inherit from `Attribute` ? Why not using directly a `CollectionProperty` of Attributes ?

**Comment by Gorgious56** [comment]
I don't really understand how this works to be honest. I just noticed that the error comes from this inheritance, and as you say even regular `Attribute` instances lose the `get_value_name` method which is weird but doesn't surprise me much considering the API is really foggy in this area...

The thing I think, is that attribute regular props are properly serialized so they still function, but every time the code calls one of its methods it fails, so the display can still work on some parts and fail on other parts depending on which methods are called.

**Comment by vulevukusej** [comment]
@Gorgious56 -  Here an example where the "get_value_name" method is called, without causing an error.  I really want to understand why it's working here, but not for the object attributes?  

![image](https://user-images.githubusercontent.com/83825269/177479921-4d6f0524-e794-431c-af97-227fab2ca5ff.png)

**Comment by vulevukusej** [comment]
this appears to be related: https://blender.stackexchange.com/questions/165524/subclassing-property-group-class-problem

**Comment by Gorgious56** [comment]
I think the reason is because `IfcSimpleProperty` does inherit the methods of `Attribute`, but regular `Attribute` classes lose them for some reason.

These display correctly

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/pset/prop.py#L161

These don't 

https://github.com/IfcOpenShell/IfcOpenShell/blob/87f110bae50f2bbbbda4867d1a5493c5fcc5597b/src/blenderbim/blenderbim/bim/module/pset/prop.py#L174

But if you replace `    properties: CollectionProperty(name="Properties", type=Attribute)` with `    properties: CollectionProperty(name="Properties", type=IfcSimpleProperty)` they do.

**Comment by vulevukusej** [comment]
> But if you replace properties: CollectionProperty(name="Properties", type=Attribute) with properties: CollectionProperty(name="Properties", type=IfcSimpleProperty) they do.

Fascinating, I feel a little out of my depth here.  What do you guys suggest I do @Gorgious56 @Moult ?

**Comment by Moult** [comment]
A summary is that the code is now refactored to define its own separate property group for properties instead of inheriting and "bolting-on" the attribute property group. This also is in preparation for future support of other property types like list, tabular, bounded, etc.
