### ISSUE TITLE
Trouble installing Ifcopenshell and PythonOCC in same environment

### ISSUE THREAD

**Issue by LauridsJMikkelsen** [IfcOpenShell/IfcOpenShell#2267]
Hi everybody,

I've tried a couple of different routes now but nothing have seemed to work. Overall I really like Ifcopenshell, but I have numerous IFC models where i need to get the square meters of all the IfcSpaces in the given model. This data are not stored in either a property set or quantity set related to the IfcSpaces, and I can't find any IfcQuantityArea, and the like, in the models. 
So to my best understanding what I need to do is to compute the area from the geometry, and this OCC should be able to do.
The issue though is that every time i try to install PythonOCC in an environment with Ifcopenshell already installed I get a "environment inconsistent" error. The same happens if I install PythonOCC first and then Ifcopenshell.
I've tried the following packages in all the various combinations, every time in a fresh conda environment:

- conda install -c conda-forge pythonocc-core   (v 7.5.1)
- conda install -c pythonocc pythonocc-core      (v 7.4.1)
- conda install -c conda-forge ifcopenshell         (v 0.6.0rc0)
- conda install -c ifcopenshell ifcopenshell          (v 0.7.0)

Also I've notived that pip provides a version 1.0.5:
pip install python-ifcopenshell

Further, I've shortly experimented with the freecad python library, which incidently fails to import IFC for me. I've not spent much time on this package though as I greatly prefer Ifcopenshell, and only tried it out as a last resort.

I general when reading around I've stumbled upon a lot of different hints at where you find the newest build, but I find it really hard to figure what is up and down and which package and version of OCC i should pair the given version with to end out with a consistent environment.

Any help solving this issue would be greatly appreciated, as to how i can create a consistent conda environment that allows me to compute the areas of IfcSpaces. Also, if there exist other solutions than using OCC, that will also be appreciated. The only requirement is that i need to be able to do it programmatically, as the solution have to sit in a data pipeline where i need to get area-data on a lot of IFC models in a run, periodically.

I'm on a Windows 10 64 bit machine with anaconda. 

Thank you so much for the otherwise awesome tool.

**Comment by aothms** [comment]
The freecad guys are working on a new push of ifopsh to conda-forge. I guess that'd solve some issues. https://github.com/conda-forge/ifcopenshell-feedstock/pull/20

What I tend to recommend for the time being is to simply place one of our automated build outputs in your site-packages folder manually https://github.com/IfcOpenBot/IfcOpenShell/commit/e44e03f02e1cf948ad452866da44ba9757d5703b#comments

In practice it doesn't matter much which versions you couple because IfcOpenShell and pythonOCC only communicate by means of string serialization of shapes which hasn't changed until OCC 7.5 (I heard it did change in OCC 7.6 but didn't verify myself).

**Comment by LauridsJMikkelsen** [comment]
Awesome! 

Thank you for the quick response, it has been very helpful. I've now managed to create a working environment with both ifcopenshell and pythonocc-core in it, by using @Krande's line. It seems to be working now, `ifcopenshell.geom.has_occ` returns true and i can `import OCC`. 
Now what I have left is to find a way to calculate the room area from IfcSpace. Unsure whether you'll find it directly related here, but I've tried accomplishing this since you replied. The closest thing I could find is this post: https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/55450b8200/ 
What I've tried so far is:
```
import ifcopenshell, ifcopenshell.geom

ifc_file = ifcopenshell.open(filepath)
spaces = ifc_file.by_type("IfcSpace")
room = spaces[0].Representation.Representations[0]        # returns:  IfcShapeRepresentation(#102,'Body','SweptSolid',(#420))
sett = ifcopenshell.geom.settings.geom(USE_PYTHON_OPENCASCADE=True)
shape = ifcopenshell.geom.create_shape(inst=room, settings=sett)         # returns:  <class 'TopoDS_Compound'>
```
Which I reckon is correct. From here on the progress seems to depends on moving from the IFC schema into OCC territory, which are foreign land to me. This is what I got:

```
from OCC.Core import BRepGProp
from OCC.Core import GProp

tshape = shape.TShape()     # returns:  <class 'TopoDS_TShape'>
gp = GProp.GProp_GProps()  #  returns:  <class 'GProp_GProps'>
br = BRepGProp.brepgprop_SurfaceProperties(tshape, gp) 
```
Which gives me:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\b075863\Anaconda3\envs\testenv\lib\site-packages\OCC\Core\BRepGProp.py", line 409, in brepgprop_SurfaceProperties
    return _BRepGProp.brepgprop_SurfaceProperties(*args)
TypeError: Wrong number or type of arguments for overloaded function 'brepgprop_SurfaceProperties'.
  Possible C/C++ prototypes are:
    BRepGProp::SurfaceProperties(TopoDS_Shape const &,GProp_GProps &,Standard_Boolean const,Standard_Boolean const)
    BRepGProp::SurfaceProperties(TopoDS_Shape const &,GProp_GProps &,Standard_Real const,Standard_Boolean const)
```

I would guess that it's either the wrong way to go about it, or that i need to do something with GProp_GProps before passing it to the function. What I've used for reference is: https://dev.opencascade.org/doc/refman/html/class_b_rep_g_prop.html 

Thanks again.

**Comment by Moult** [comment]
Glancing at the error message it seems the optional args in C++ maybe aren't optional in Python?

**Comment by aothms** [comment]
> optional args in C++ maybe aren't optional in Python?

SWIG should be able to handle default/optional arguments.

But BRepGProp is on the TopoDS_Shape (so `shape`) not `TopoDS_TShape` `tshape`. In general TShape is only an internal construct you generally never have to care about.

>     BRepGProp::SurfaceProperties(TopoDS_Shape const &,GProp_GProps &,Standard_Real const,Standard_Boolean const)

**Comment by Maozerhouni** [comment]
Hi @Krande 

I tried your solution but it didn't work for me. Has anything changed since July ?


Error message : 
PackagesNotFoundError: The following packages are not available from current channels:

  - pythonocc-core==7.5.3

Current channels:

  - https://conda.anaconda.org/krande/win-64
  - https://conda.anaconda.org/krande/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

**Comment by Krande** [comment]
Hi @Maozerhouni,

Yes, we finally got the conda-forge packaging for both pythonocc-core and ifcopenshell using the latest occt up and running (and so I removed the pythonocc-core packages on my personal conda channel). 

Try this:

`conda create -n testenv -c conda-forge ifcopenshell pythonocc-core`

**Comment by Moult** [comment]
@LauridsJMikkelsen glad you got it working! As for your question about areas, there is now a new shape util module. This function should help: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/shape.py#L107

@Maozerhouni are you still experiencing issues? Can we close this bug?

**Comment by Maozerhouni** [comment]
Hi,
Yes it is working for me.
