### ISSUE TITLE
Problems importing Win64 python35 ifcopenshell

### ISSUE THREAD

**Issue by boustrephon** [IfcOpenShell/IfcOpenShell#227]
[I previously posted this question on SourceForge, but I am guessing that this forum is more active now. https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/33519796/?limit=25]

I cannot get Win64 py35 ifcopenshell to import using a Jupyter notebook running the environment created by running the commands suggested in the pythonOCC repository (resulting in a Python 3.6 environment). I cannot find any threads on this, so I have a nasty feeling that I am missing something, but I would appreciate guidance.

I am using an Ananconda3 installation and I have tried to follow the instructions on http://ifcopenshell.org/python.html, which involved downloading the module (ifcopenshell-python35-master-9ad68db-win64.zip), unzipping it and placing it into the site-packages folder. I did this and then did a "sys.path.append" to make the folder accessible. Finally I tried to import - ImportError: DLL load failed: The specified module could not be found.

When I look at the folder, there is no file called ifcopenshell.py or pyd or pyc, whereas when I look at the contents of "ifcopenshell-python2.7-win32.zip" I see the sorts of files that I was expecting to see in the py35 version, namely "ifcopensell.py, .pyc etc. Perhaps the presence of the __init__.py file should make the import work, but so far it is not working for me. Does there need to be some additional sort of compiling or something?

Is something missing from the package or is there something missing from my understanding? Solutions to either problems would be welcome!

(Incidentally, I would really appreciate an authoritative conda package that could be installed using conda. I can find some packages, but it is difficult to know what to trust. Unfortunately I am not yet at the stage where I can compile and set up my own package.)

**Comment by SigveMartin** [comment]
I think I had the same issue using my mac and anaconda set up as you describe. 

I got it to work by checking the [location of my site-packages folder](https://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory) while being in the conda environment. That was another folder than the std. system folder, so when I placed the ifcopenshell folder there according to the instructions on http://ifcopenshell.org/python.html it worked for me.

**Comment by boustrephon** [comment]
I was installing on Windows, but it might well be the same problem. On reflection I don't think I put it in the site-packages directory for the pythonocc environment. I will try that when I get to work.

**Comment by boustrephon** [comment]
OK - I have checked and I find that if I move the files into the pythonocc environment, then it works (so, user-error, sorry).
However, I now get a compatibility error - I am looking for a python 3.6 version of ifcopenshell, since pythonocc is currently on that and I get conflicts at present. Please could the maintainers release a Win64 py36 version? Thanks :-)

**Comment by aothms** [comment]
> Incidentally, I would really appreciate an authoritative conda package that could be installed using conda

> Please could the maintainers release a Win64 py36 version

Both items will eventually be done. The 2nd request sooner than the 1st. For a proper conda release it would make more sense when we are on a more predictable release cycle and when the ifcopenshell module can interface with multiple schemas at runtime rather than compile time.

**Comment by boustrephon** [comment]
Thanks. The second item is what I am looking for now. Thanks for all your work on this.

**Comment by thorade** [comment]
+1 for a python 3.6 package.
Would it make sense to update SWIG to a more recent version for this?

The following SWIG issue might also be interesting to watch:
https://github.com/swig/swig/issues/1009
Once that gets solved, a general Py3 package should be possible.

**Comment by aothms** [comment]
> +1 for a python 3.6 package.

It's coming.

> Once that gets solved, a general Py3 package should be possible.

That would be nice indeed. The actual usage of python in the generated wrapper code is very minimal, so from our point of view a generic py3 package should be possible.

**Comment by Moult** [comment]
As the IfcOpenBot produces builds now, this can be closed?

**Comment by Moult** [comment]
Closing as conda builds now available and py36 also available.
