### ISSUE TITLE
BB:  IfcParameterizedProfileDef not 'remembered' in UI.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2272]
I created a IfcBeamType with IfcParameterizedProfileDef, but when you import the IFC again in BB, and go the settings, even though the correct parameters are there `XDim` and `YDim`, it says `IfcArbitraryClosedProfileDef`.

[Example File](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/c75bcc08239182f663b8ee82f4e4efa8c0cd8344/Random_Tests/Beam_Rectangular/from_BlenderBIM/Beam_Rectangular_02.ifc)

minor bug, but thought i'd report. 

![2022-07-07_13-19-24_Blender_ DDropboxGitLabFreeMVD_WorkFlowRando_blender](https://user-images.githubusercontent.com/507113/177842808-4753889d-4557-4cb8-9877-73e11e8dd1c3.png)
![image](https://user-images.githubusercontent.com/507113/177844878-fb16e5d2-3dc3-404b-bf79-c70ca73f50a7.png)

**Comment by Moult** [comment]
Already fixed from the latest release.
