### ISSUE TITLE
Blender BIM - Additional boolean/void not added to wall and lost at re-open

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#2273]
Adding a second pre-defined object type (door, window etc.) doesn't create a boolean in the target wall. The boolean/void is also lost from the .ifc after saving and re-loadeding.

**Comment by Moult** [comment]
How exactly do you reproduce this? Can you provide step by step instructions? Sorry for the delay been busy.

**Comment by Moult** [comment]
Bump @ChubbyQuark

**Comment by ChubbyQuark** [comment]
Sorry, side tracked again. Just trying to re-create with the latest release and the UI has changed a bit. After loading the demo library I'm not getting the pre-defined types show up in the tool tab?

<img width="1786" alt="image" src="https://user-images.githubusercontent.com/26485679/201033770-d4d87088-889b-4335-b4ae-c2a7598416ae.png">

**Comment by theoryshaw** [comment]
You might know this already, but make sure the wall is selected before you add the void.

**Comment by ChubbyQuark** [comment]
Just tested on the latest build (0.0.221110) and all worked as expected.
Also noticed door swings are also added by default, which is a great time
saver. Great work with the updated UI, amazing progress.
