### ISSUE TITLE
Import-Export: BlenderBIM is not working

### ISSUE THREAD

**Issue by amarkrish108** [IfcOpenShell/IfcOpenShell#2275]
When the BlenderBIM addon is installed, I get this error
![BlenderBIM](https://user-images.githubusercontent.com/64318675/178408350-f80edce2-9ce3-494f-b7a9-3574c776ee91.png)
.

**Comment by Moult** [comment]
Please note installation instructions can be found here: https://blenderbim.org/docs/users/installation.html

You are using Blender 3.0, so you'll need to either upgrade Blender to >= 3.1 or follow the unstable installation as described in the documentation.
