### ISSUE TITLE
BLENDERBIM - Adding custom ifcannotation to groups

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#2277]
No option exposed in UI to add custom made ifcAnnoatations to groups meaning annoatations are missing from drawing when printed: -

<img width="1423" alt="Screenshot 2022-07-12 at 09 44 59" src="https://user-images.githubusercontent.com/26485679/178449518-0224baf5-b657-476c-bd5d-1c1a5fd91896.png">

**Comment by vulevukusej** [comment]
Hi @ChubbyQuark - You need to create a group first in Scene Properties -> IFC Project Setup -> IFC Groups.  After you do that, you'll be able to add your annotation to an existing group.
