### ISSUE TITLE
Error when installing: blenderbim-220711-py39-win 

### ISSUE THREAD

**Issue by NebilHassen** [IfcOpenShell/IfcOpenShell#2281]
Hi, 

Whenever i try to install the Blender Bim Add - through Github, which is the "developer built" (as describes in this video min 1:09, https://www.youtube.com/watch?v=GpnCiIMhWDo&ab_channel=SigmaDimensions: ). I get an "ImportError: DLL load failed while importing  _ifcopenshell_wrapper: The specified module could not be found."

**2 questions.**

**Question 1:** 
Does one even get any benefits by downloading the Blender Bim Addon throught Github as suggested by Sigma Dimensions youtube clip, can one make functions/add ons (ie. make a functionality) within Blender Bim without the "developer built" as the version on Git hub is referred to. Are there any differences between downloading Blender Bim through the website (https://blenderbim.org/) or through Github (https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-220711), the only one i notice is that when i try to download Blender Bim through Github i get the error depicted. But when i try to download Blender Bim through the website (https://blenderbim.org), Blender Bim works but when I write "import openshell" in the scripting tab in blender i get an error. Are there any differences, can one make/code an add-on without downloading Blender Bim through Github?
 
Picture of error in question: 
![Error when downloading Blender Bim through Github](https://user-images.githubusercontent.com/83288449/178738761-13247a1b-bf29-471b-b796-4215564a7c8d.png)

 
**Question 2:** 
Is there a guide anywhere on how to code your own add-on in Blender Bim, maybe like the one C.Claus has made (https://www.youtube.com/watch?v=_ZXUZQkcjlI&list=PLa8TMoQh_y5QpJ95BQ4M7AyO6B6TA_bgN&index=1&ab_channel=C.Claus), or this one by Dion Moult (https://www.youtube.com/watch?v=6Zd5PZtJ3yQ&list=PLa8TMoQh_y5QpJ95BQ4M7AyO6B6TA_bgN&index=4&ab_channel=DionMoult). I would to make an add-on to Blender Bim that makes the the user visibly informed about changes done on a IFC file from the last time the file was saved or changed, almost like a built in version control, that sort of informs the user on changes made, like that Blender Bim points out changes done in a file since the last time it was saved or worked on. 
 
 
 
 

I'm a complete beginner but i think the community is amazing, any help would be greatly appreciated!

**Comment by vulevukusej** [comment]
Hi @NebilHassen - Firstly, did you make sure you downloaded the version corresponding with your version of python? https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-220711

To answer Question 1 - The main advantage to using the daily builds or the files directly from GitHub is that you have acess to the latest features, albeit with the risk that some of these features unkowningly introduced a bug somewhere.  It's most suited to developers who are editing the code and need to be using the latest version.

When I started learning I found the following youtubers helpful - just search for "tutorial" or "python blender":

- https://www.youtube.com/c/JayAnAm
- https://www.youtube.com/user/blengine
- https://www.youtube.com/c/BlenderGuruOfficial
- https://www.youtube.com/c/DarkfallBlender

Also check out the blender stack exchange and forums on https://osarch.org/.  More than likely, if you are stuck or encounter an error someone would've already asked the same question above.  Have fun ;)

**Comment by Moult** [comment]
Question 1: indeed the guarantee of the stable release on the blenderbim.org is that it is "stable", usually defined as no huge bugs and it'll successfully install :) If you choose not to have a stable installation, there is no guarantee, but on the plus side you get to see all of the cool new stuff which happens very quickly.

 - https://blenderbim.org/docs/users/installation.html this guide is for a typical stable installation
 - https://blenderbim.org/docs/devs/installation.html this guide teaches you about unstable installation and who it is recommended for

Question 2: This tutorial will teach you all the basics of doing development with Blender, IfcOpenShell, and the BlenderBIM Add-on: https://blenderbim.org/docs/devs/hello_world.html read through and try the demo module and read the code of the demo module and try edit the code and see what happens.

A great place to reach out for help is https://community.osarch.org forums or https://osarch.org/chat for live chat.
