### ISSUE TITLE
Element range when importing

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#2284]
I don't see [this option](https://blenderbim.org/docs/users/dealing_with_large_models.html#high-number-of-elements) (using 20220711, win, py3.9, blender 3.0). Did I miss something here?

**Comment by vulevukusej** [comment]
@TZwielehner after enabling advanced mode you should see this option under IFC Project Info -> IFC Project

![image](https://user-images.githubusercontent.com/83825269/178919548-5110b5a7-d69a-44f0-bf62-9351aae9ab56.png)


![image](https://user-images.githubusercontent.com/83825269/178919480-54ac0fac-fe4e-496c-8ab9-69ef58d5dd3b.png)

**Comment by TZwielehner** [comment]
Does this only work for IFC4?

**Comment by vulevukusej** [comment]
Interesting, i'll have a look at that specific build and get back to you

**Comment by vulevukusej** [comment]
Weird, I downloaded the exact same version and the UI does not look the same as yours..

**Comment by TZwielehner** [comment]
Maybe because I use 3.0? I tried to install on 3.2 but I get "ifcoepnshell not built for python3.10" error.

**Comment by vulevukusej** [comment]
The thing is, I tried searching the code for "Import and Merge by Material" and it doesn't exist, that's why I'm curious where you downloaded the addon from?  In the current version, that UI element is called "Merge Materials by Colour"

**Comment by TZwielehner** [comment]
Oh wow, big mistake on my side. I one day apparently copied blenderbim to the python directory and blender used that all the time. Argghhh! Now I see it.

**Comment by vulevukusej** [comment]
😁😁 - I did the exact same thing once!  Happy to have helped ;)
