### ISSUE TITLE
api.pset.edit_pset imports distutils

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2288]
I don't know why this file imports distutils, as it isn't used, but it generates this warning:

    /usr/lib64/python3.10/site-packages/ifcopenshell/api/pset/edit_pset.py:19:
    DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12.
    Use setuptools or check PEP 632 for potential alternatives
        from distutils.command.sdist import sdist

**Comment by aothms** [comment]
It's probably a automatic import from an IDE or something based on a typo. @vulevukusej can you comment? https://github.com/IfcOpenShell/IfcOpenShell/commit/c8c9262090212056dc42c3f35b197013103e9126#diff-b42757d4b19482afcb78e61a863a498aace8658be312eee5fd7f83ac79a9c401

**Comment by vulevukusej** [comment]
Yeah that was a typo, but I thought I fixed that?

**Comment by Moult** [comment]
@vulevukusej feel free to delete the line and close this :)

**Comment by vulevukusej** [comment]
Yeah sorry guys, I´ll be a little more diligant from now on!
