### ISSUE TITLE
Selector - handling situations where attribute is None

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2291]
In the following example, am I wrong to expect that all objects are matched?:

.IfcWall[PredefinedType != "non-existent predefined type"]'

Perhaps the following code can be updated to check whether comparison == "not"?
https://github.com/IfcOpenShell/IfcOpenShell/blob/d71ebb8d2519051a59122b49b18a8d505578fc18/src/ifcopenshell-python/ifcopenshell/util/selector.py#L192-L194

**Comment by Moult** [comment]
Great suggestion! More than happy to see this implemented, but please write tests for it to help document the behaviour.
