### ISSUE TITLE
Unable to build IfcOpenShell for AWS Lambda

### ISSUE THREAD

**Issue by Matej80** [IfcOpenShell/IfcOpenShell#2295]
I tried running the latest build of IfcOpenShell 0.7.0 in a AWS Lambda container, but got the following error:
`[ERROR] Runtime.ImportModuleError: Unable to import module 'main': IfcOpenShell not built for 'linux/64bit/python3.9' Traceback (most recent call last):
`

So I tried to build IfcOpenShell to the Linux version that is running on the lambda, but it seems there are some libraries that are missing that are very hard to find for the _"I assume"_ ~~Redhat~~ CentOS distro of Linux that AWS Lambda uses.

I found two threads of people attempting to build IfcOpenShell for an AWS Linux distro, but I couldn't recreate the same results:

[sourceforge.net/p/ifcopenshell/discussion/1782717/thread/5e7882e0bc/?limit=25](https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/5e7882e0bc/?limit=25)

[github.com/IfcOpenShell/IfcOpenShell/issues/1149](https://github.com/IfcOpenShell/IfcOpenShell/issues/1149)

Here is my Dockerfile so far:
```
ARG VARIANT="3.9"

FROM public.ecr.aws/lambda/python:${VARIANT} AS build

RUN yum -y update && yum -y install git
RUN yum -y install wget
RUN git clone https://github.com/IfcOpenShell/IfcOpenShell.git

RUN cd IfcOpenShell && git checkout v0.7.0

RUN yum -y install freetype-devel
RUN yum group -y install "Development Tools"
RUN yum -y install mesa-libGL-devel opencv-devel opencv-python

RUN wget -O cmake-install https://github.com/Kitware/CMake/releases/download/v3.13.0/cmake-3.13.0-Linux-x86_64.sh; \sh cmake-install --skip-license --prefix=/usr --exclude-subdirectory;

RUN cd IfcOpenShell && mkdir build && cd build
RUN cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ -DCOLLADA_SUPPORT=0 -DIFCXML_SUPPORT=0 -DBUILD_IFCGEOM=0 -DBUILD_IFCPYTHON=0 -DBUILD_EXAMPLES=0 -DBUILD_GEOMSERVER=0

RUN cd IfcOpenShell/build/ && make

CMD [ "app.lambda_handler" ]
```

I have tried to install cmake 3.18 manually but the build process fails at other dependancies.

Example:
`Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)`

I was wondering if some has had more luck running IfcOpenShell 0.7.0 on AWS Lambda.
Or whether someone had luck building 0.7.0 for the AWS Lambda Linux 2 image.

Insight into both problems would be appreciated. I apologize if this is the wrong forum to post this issue.

**Comment by Moult** [comment]
Did you try this latest build? https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.7.0-dc67287-linux64.zip

**Comment by aothms** [comment]
*  Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)

Did you try `yum install libxml2-devel`? And then you need to set -DLIBXML2_INCLUDE_DIR= -DLIBXML2_LIBRARIES= appropriately.

This kind of setup is typically not difficult, but it get's a bit easier with some experience. If you just keep posting the errors we'll jointly figure it out.

**Comment by PetterGs** [comment]
> Did you try this latest build? https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-v0.7.0-dc67287-linux64.zip

I did. Same error: `Unable to import module 'main': IfcOpenShell not built for 'linux/64bit/python3.9'`

I got the libxsm2 location via `rpm -ql libxml2`. The build command:

`-DLIBXML2_INCLUDE_DIR=/usr/lib64 -DLIBXML2_LIBRARIES=/usr/lib64/libxml2.so.2.9.1`

I think it's correct. Though now cmake complains about boost. Do I have to set each path explicitly? I do have boost installed via `yum -y install boost` and `-DBOOST_ROOT=/usr/share/doc/boost-1.53.0` in the build command:

`-DBOOST_ROOT=/usr/share/doc/boost-1.53.0`

Is there a way to make cmake find the location automatically? Or is there another location I need to get boost from?

```
-- 'IfcGeom' is required with current outputs
-- BINDIR: bin
-- INCLUDEDIR: include
-- LIBDIR: lib64
-- Found LibXml2: /usr/lib64/libxml2.so.2.9.1 (found version "2.9.1")
-- Found Threads: TRUE
CMake Error at /usr/share/cmake-3.13/Modules/FindBoost.cmake:2103 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:223 (FIND_PACKAGE)

-- Boost include files found in Boost_INCLUDE_DIR-NOTFOUND
-- Boost libraries found in
CMake Error at CMakeLists.txt:281 (MESSAGE):
  Unable to find Open CASCADE include directory, specify OCC_INCLUDE_DIR
  manually.

-- Configuring incomplete, errors occurred!
See also "/var/task/IfcOpenShell/build/CMakeFiles/CMakeOutput.log".
See also "/var/task/IfcOpenShell/build/CMakeFiles/CMakeError.log".
sh-4.2#
```

**Comment by aothms** [comment]
> DLIBXML2_INCLUDE_DIR=/usr/lib64

Typically it'd be /usr/include or /usr/include/libxml2

> DBOOST_ROOT=/usr/share/doc/boost-1.53.0

That seems to be the documentation

Try installing `boost-devel` and see what kind of includes libraries it comes with.

**Comment by Matej80** [comment]
Thank you very much for your help.

I made it this far:

```
ARG VARIANT="3.9"

FROM public.ecr.aws/lambda/python:${VARIANT} AS build

RUN yum -y update && yum -y install git
RUN yum -y install wget
RUN git clone https://github.com/IfcOpenShell/IfcOpenShell.git

RUN cd IfcOpenShell && git checkout v0.7.0

RUN yum -y install freetype-devel
RUN yum group -y install "Development Tools"
RUN yum -y install mesa-libGL-devel opencv-devel opencv-python
RUN yum -y install libxml2-devel
RUN yum -y install boost-devel

RUN wget https://github.com/imageio/imageio-binaries/raw/master/freeimage/libfreeimage-3.16.0-linux64.so

RUN wget http://mirror.centos.org/altarch/7/extras/aarch64/Packages/epel-release-7-11.noarch.rpm
RUN rpm -Uvh epel-release*rpm
RUN yum -y install OCE-devel

RUN wget -O cmake-install https://github.com/Kitware/CMake/releases/download/v3.13.0/cmake-3.13.0-Linux-x86_64.sh; \sh cmake-install --skip-license --prefix=/usr --exclude-subdirectory;

RUN cd IfcOpenShell && mkdir build && cd build

# RUN cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ \
#     -DBOOST_ROOT=/usr/include/boost \
#     -OCC_INCLUDE_DIR=/usr/include/oce \
#     -OCC_LIBRARY_DIR=/usr/lib64/oce-0.17 \
#     -DLIBXML2_INCLUDE_DIR=/usr/lib64 \
#     -DLIBXML2_LIBRARIES=/usr/lib64/libxml2.so.2.9.1 \
#     -DCOLLADA_SUPPORT=0 -DIFCXML_SUPPORT=0 -DBUILD_IFCGEOM=0 -DBUILD_IFCPYTHON=0 -DBUILD_EXAMPLES=0 -DBUILD_GEOMSERVER=0

# RUN cd IfcOpenShell/build/ && make

CMD [ "app.lambda_handler" ]
```

But when I run the uncommented cmake command I get the following report. It appears I am unable to get the Open CASCADE correctly.

Can I substitute OCC with OCE like attempted to do?

**Comment by aothms** [comment]
>  I get the following report

?

> Can I substitute OCC with OCE like attempted to do?

You need to set `-DOCC_INCLUDE_DIR=/usr/include/oce` probably. 

What I see here is that OCE 0.17.1 being available https://centos.pkgs.org/7/epel-x86_64/OCE-devel-0.17.1-1.el7.x86_64.rpm.html which is compatible with OpenCASCADE 6.8. That's 8 years old, you'd miss a lot of worthwhile improvements. 

I don't think that would work anymore (especially with the default 0.7.0 branch of ifopsh, mayby 0.6.0).

Did you try `opencascade-devel`?

**Comment by Matej80** [comment]
> > I get the following report
> ?

Sorry, lol. Actually I'm unable to even install OCE. I get this message:
`Requires: libraw.so.19()(64bit)` I have been unable to find the correct package. My Google-Fu has been too weak.

>Did you try opencascade-devel?
I did. `No package opencascade-devel available.`

**Comment by aothms** [comment]
>  Requires: libraw.so.19()(64bit)

https://centos.pkgs.org/7/centos-x86_64/LibRaw-0.19.4-1.el7.i686.rpm.html

No idea, why that would be necessary, but like I said, it's really better to focus on OCCT directly.

> I guess it's only for OpenSUSE https://pkgs.org/download/OpenCASCADE-devel

Ok, I was confused by this

https://altlinux.pkgs.org/p10/classic-x86_64/opencascade-devel-7.5.3-alt1.x86_64.rpm.html

But it seems to be some very specific distro. You can still probably just download the RPM and fight your way through installing it manually?

Alternatively you'd just have to compile OCCT yourself. It's not harder just takes a while. Like 5m to 1h depending on hardware.

Another alternative is to use the build script which compiles most of the dependencies and then IfcOpenShell https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/nix/build-all.py But it has (as far as I can tell) only been used on Debian-derivatives.

**Comment by Matej80** [comment]
Some fun progress. Thank you all for your help. I think I might be close. I changed the AWS lambda image to the AWS standard image, just to get a less stripped down image.

I apologize for the Dockerfile to be so verbose. I just wanted to make sure I get everything.

```
FROM amazonlinux:2 as build

RUN yum -y update && yum -y install git wget
RUN yum group -y install "Development Tools"

RUN yum -y install boost-devel cmake gcc g++ autoconf bison bzip2 \
    libxml2-devel mesa-libGL-devel opencv-devel opencv-python \
    fontconfig.x86_64 freetype freetype-devel fontconfig-devel libstdc++ 

RUN wget -O cmake-install https://github.com/Kitware/CMake/releases/download/v3.13.0/cmake-3.13.0-Linux-x86_64.sh; \sh cmake-install --skip-license --prefix=/usr --exclude-subdirectory;

#################################################
# Build OCCT

WORKDIR "/dependencies"
RUN git clone https://github.com/Open-Cascade-SAS/OCCT.git
WORKDIR "/dependencies/OCCT"

RUN mkdir occt-build
RUN mkdir occt-install

WORKDIR "/dependencies/OCCT/occt-build"
RUN cmake /dependencies/OCCT \
    -DINSTALL_DIR=/dependencies/OCCT/occt-install \
    -DBUILD_LIBRARY_TYPE=static \
    -DBUILD_MODULE_Draw=0 \
    -DBUILD_RELEASE_DISABLE_EXCEPTIONS=Off
RUN make install

#################################################
# Build CGAL

WORKDIR "/dependencies"
RUN mkdir GMP
WORKDIR "/dependencies/GMP"
RUN wget https://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.bz2
RUN tar xvjf gmp-6.1.2.tar.bz2
WORKDIR "/dependencies/GMP/gmp-6.1.2"
RUN ./configure --disable-shared --with-pic
RUN make && make install

WORKDIR "/dependencies"
RUN mkdir MPFR
WORKDIR "/dependencies/MPFR"
RUN wget http://www.mpfr.org/mpfr-3.1.5/mpfr-3.1.5.tar.bz2
RUN tar xvjf mpfr-3.1.5.tar.bz2
WORKDIR "/dependencies/MPFR/mpfr-3.1.5"
RUN ./configure --disable-shared --with-gmp=/dependencies/GMP/gmp-6.1.2
RUN make && make install

WORKDIR "/dependencies"
RUN git clone https://github.com/CGAL/cgal.git
WORKDIR "/dependencies/cgal"

RUN mkdir cgal-build
RUN mkdir cgal-install

WORKDIR "/dependencies/cgal/cgal-build"
RUN cmake /dependencies/cgal \
    -DGMP_LIBRARIES=/usr/local/lib/libgmp.a \
    -DGMP_INCLUDE_DIR=/usr/local/include \
    -DMPFR_LIBRARIES=/usr/local/lib/libmpfr.a \
    -DMPFR_INCLUDE_DIR=/usr/local/include \
    -DBoost_INCLUDE_DIR=/usr/include/boost \
    -DCMAKE_INSTALL_PREFIX=/dependencies/cgal/cgal-install/ \
    -DCGAL_HEADER_ONLY=On \ 
    -DBUILD_SHARED_LIBS=Off
RUN make install


# #################################################
# Build IfcOpenShell

WORKDIR "/dependencies"
RUN git clone --recurse-submodules https://github.com/IfcOpenShell/IfcOpenShell.git
WORKDIR "/dependencies/IfcOpenShell"
RUN mkdir build
WORKDIR "/dependencies/IfcOpenShell/build"

RUN cmake ../cmake \
    -DGMP_LIBRARY_DIR=/usr/local/lib/libgmp.a \
    -DGMP_INCLUDE_DIR=/usr/local/include \
    -DMPFR_LIBRARY_DIR=/usr/local/lib/libmpfr.a \
    -DMPFR_INCLUDE_DIR=/usr/local/include \
    -DCGAL_INCLUDE_DIR=/dependencies/cgal/cgal-install/include \
    -DBOOST_ROOT=/usr/include/boost \
    -DOCC_INCLUDE_DIR=/dependencies/OCCT/occt-install/include/opencascade \
    -DOCC_LIBRARY_DIR=/dependencies/OCCT/occt-install/lib \
    -DLIBXML2_INCLUDE_DIR=/usr/lib64 \
    -DLIBXML2_LIBRARIES=/usr/lib64/libxml2.so.2.9.1 \
    -DCOLLADA_SUPPORT=0 -DIFCXML_SUPPORT=0 -DBUILD_IFCGEOM=0 -DBUILD_IFCPYTHON=0 -DBUILD_CONVERT=0 -DBUILD_EXAMPLES=0 -DBUILD_GEOMSERVER=0
RUN make install
```

I get the following error:
```
#0 2.231 -- Looking for CGAL include files in: /dependencies/cgal/cgal-install/include
#0 2.231 CMake Error at /dependencies/IfcOpenShell/src/svgfill/CMakeLists.txt:48 (message):
#0 2.231   Unable to find GMP library files, aborting
#0 2.231
#0 2.231
#0 2.235 -- Configuring incomplete, errors occurred!
#0 2.235 See also "/dependencies/IfcOpenShell/build/CMakeFiles/CMakeOutput.log".
#0 2.235 See also "/dependencies/IfcOpenShell/build/CMakeFiles/CMakeError.log".
```

**Comment by aothms** [comment]
Sorry for the late reply.

> Unable to find GMP library files, aborting

> -DGMP_LIBRARIES=/usr/local/lib/libgmp.a

Does the file exist? Because when building MPFR you point to a different gmp install root `--with-gmp=/dependencies/GMP/gmp-6.1.2`

**Comment by Matej80** [comment]
Actually a colleague of mine solved the issue quite elegantly by simple building the Lambda image from the newest AWS linux image.

Here is the dockerfile:
`
FROM public.ecr.aws/amazonlinux/amazonlinux:2022 AS build

ARG VERSION_AND_HASH="v0.7.0-e508fb4"

RUN yum update && yum -y install unzip python pip python-devel gcc g++ make cmake
RUN pip install setuptools 
RUN pip install --target . awslambdaric

RUN curl https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-${VERSION_AND_HASH}-linux64.zip -O && \
    unzip ifcopenshell-python-39-${VERSION_AND_HASH}-linux64.zip && \
    mv ifcopenshell /usr/local/lib/python3.9/site-packages && \
    rm ifcopenshell-python-39-${VERSION_AND_HASH}-linux64.zip

ENTRYPOINT [ "/usr/bin/python", "-m", "awslambdaric" ]
CMD [ "lambda_handler" ]
`

**Comment by zahmadsaleem** [comment]
For some reason @Matej80 's answer didn't invoke the lambda correctly
I modified it to get it working, Thanks @Matej80 

```
ARG FUNCTION_DIR="/var/task"

FROM public.ecr.aws/docker/library/python:3.9 AS build

ARG IFC_OPENSHELL_BUILD="39-v0.7.0-e508fb4"

RUN apt-get -y update && apt-get -y install unzip curl

ARG FUNCTION_DIR

RUN pip install --target ${FUNCTION_DIR} awslambdaric

RUN curl https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-${IFC_OPENSHELL_BUILD}-linux64.zip -O && \
    unzip ifcopenshell-python-${IFC_OPENSHELL_BUILD}-linux64.zip && \
    mv ifcopenshell ${FUNCTION_DIR} &&\
    rm ifcopenshell-python-${IFC_OPENSHELL_BUILD}-linux64.zip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./handlers ${FUNCTION_DIR}/handlers

WORKDIR ${FUNCTION_DIR}

ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD ["handlers.lambda_handler"]
```

**Comment by Moult** [comment]
Sorry for resurrecting @zahmadsaleem and @Matej80 - but this is really useful and I think it might be worth it to add to the installation documentation for other AWS Lambda users: https://blenderbim.org/docs-python/ifcopenshell-python/installation.html

Would either of you be able to help write up a few sentences to include in the documentation, and if you need a Dockerfile hosted somewhere on this repo would you be able to provide a PR? I can help to ensure that the build SHA is always up to date.

**Comment by zahmadsaleem** [comment]
Hey @Moult absolutely! I'll gladly create a PR with more details. Where should the documentation and the Dockerfile sit in the repo?

**Comment by Moult** [comment]
@zahmadsaleem thank you so much! I'm not sure where the Dockerfile should live, @aothms will know though.

The instructions can probably go under section 4 on this page: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/docs/ifcopenshell-python/installation.rst - adjust the introduction paragraph to mention that docker is recommended both for regular docker users as well as AWS Lambda.

**Comment by aothms** [comment]
This would be very cool. I would just create a top level directory either named `aws` or `lambda` and put the dockerfile there. Maybe with a readme or sth. In the future we can create a `vendor` directory or sth and move ` aws`/`lambda`, `conda` and `pyodide` there, but for now simple top level dir will work 👍

**Comment by zahmadsaleem** [comment]
Hey @aothms, sounds good. I'll submit a PR
