### ISSUE TITLE
blenderbim 'separate' operator creates duplicate entities 

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2297]
Steps to reproduce:
1. Create a new IFC project
2. Assign an IFC class
3. Go into edit mode
4. Select a face
5. Press 'p' key, separate selection
6. There are now two elements with the same globalid
7. Select one and change the class
8. Other is still there but now 'Ifc element not found'

**Comment by Moult** [comment]
Duplicate of #2058.
