### ISSUE TITLE
Error when exporting to svg

### ISSUE THREAD

**Issue by GuillaumeNachury** [IfcOpenShell/IfcOpenShell#23]
Hi,
I'd like to export 2D floor plans from IFC files but I'm getting a weird issue when trying to export as a SVG file.

```
./IfcConvert ~/IFC_Sample/SimpleTest.ifc test.svg
Scanning file...
Done scanning file   

Log:
[Error] Unable to parse .ifc file or no geometrical entities found
```

Whereas when converting to OBJ file no error is raised...

Is there something specific to the svg exporter that could break the conversion ?

Thanks

**Comment by Stinkfist0** [comment]
Does the file have any IfcSpaces? Those are required by the SVG conversion. You can try --verbose switch to maybe get some more information.

**Comment by GuillaumeNachury** [comment]
You are right there is no IfcSpace defined in the file. 

Are the IfcSpaces mandatory to get the SVG conversion working or even without these elements I can get a render ? (by using --include entities IfcWall as you pointed)

**Comment by Stinkfist0** [comment]
`./IfcConvert ~/IFC_Sample/SimpleTest.ifc test.svg --include --entities IfcWall` should work

**Comment by GuillaumeNachury** [comment]
I had the chance to give ``` --include --entities IfcWall``` a try and I don't have the error any more.

I converted a sample file (attached below) and even if I use the ```--bounds 512x512``` argument the svg is shrunk

![image](https://cloud.githubusercontent.com/assets/617536/12414795/1a33d062-be98-11e5-9775-33291e2e5f4b.png)

Conversion cmd line : 
```
./IfcConvert SampleFiles/Cabanne.ifc outputs/Cabanne.svg  --include --entities IfcWall --bounds 512x512

```
Sample file : 
[Cabanne.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/95614/Cabanne.zip)

Any idea why ?

Thanks

**Comment by Stinkfist0** [comment]
Personally I'm getting what seems a reasonable result in Inkscape:
![screenshot 2016-01-19 11 48 53](https://cloud.githubusercontent.com/assets/227876/12415153/ad164414-bea2-11e5-8049-473d7b828a60.png)

**Comment by GuillaumeNachury** [comment]
Weird... I tried to open the svg in Safari and Chrome, both render it shrank.

Here is what I get out from IfcConvert
[Cabanne.svg.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/95728/Cabanne.svg.zip)

**Comment by Stinkfist0** [comment]
OK, that file does not look right for me either:
![screenshot 2016-01-19 12 54 30](https://cloud.githubusercontent.com/assets/227876/12416779/1d85cc70-beac-11e5-9a63-901d381fa339.png)

What version of IfcOpenShell are you using? I'm using the latest code from this repository.

**Comment by GuillaumeNachury** [comment]
I'm using v0.5.0

````
./IfcConvert --version
IfcOpenShell IfcConvert 0.5.0-dev
````

I found that settings ```--use-world-coords``` creates an *almost* correct output.

**Comment by Stinkfist0** [comment]
A download from http://www.ifcopenshell.org/ifcconvert.html? There have probably been some tweaks and fixes to the SVG code, that are not yet included in the binary download.

**Comment by GuillaumeNachury** [comment]
Nope I did a ```git clone https://github.com/IfcOpenShell/IfcOpenShell.git```  and followed the **Compiling on *nix** steps.

Last question : 
If I have an IFC file that describes a building how can I export each floor as an SVG ? 
Right now all my floor appear to be stacked in the svg but I have no way to get only the 3rd floor plan.

Thanks

**Comment by Stinkfist0** [comment]
Currently one must use some kind of SVG editor to separate the different floors.

**Comment by aothms** [comment]
Indeed, but within the SVG file, elements are ordered in separate groups (`<g>`) per storey, so separating them is a trivial task that can also be easily automated.
