### ISSUE TITLE
IfcConvert with building local coordinates

### ISSUE THREAD

**Issue by andersgb** [IfcOpenShell/IfcOpenShell#230]
I am using IfcConvert to convert from IFC to OBJ. My IFC files typically have very large X and Y values for the insertion point (the ObjectPlacement) of the `IfcSite` and the axis directions are typically not at right angles with the building walls.

Using `--center-model` or `--model-offset` I can put the OBJ vertices closer to origo, but the orientation will still be according to the global axes.

I essentially want all geometry to be converted with relative placements up to the `IfcBuilding` level, but skip the `IfcSite` level. 

Is this achievable with IfcConvert?

A workaround would be to modify the IFC file by overriding the ObjectPlacement of the `IfcSite` to origo/identity, I guess.

**Comment by aothms** [comment]
> A workaround would be to modify the IFC file by overriding the ObjectPlacement of the IfcSite to origo/identity, I guess.

I guess that's the most viable approach. It's fairly trivial with a small python script. E.g. something like below:

~~~py
import ifcopenshell
f = ifcopenshell.open(...)

for site in f.by_type("IfcSite"):
    if site.ObjectPlacement is not None and site.ObjectPlacement.is_a("IfcLocalPlacement"):
        site.ObjectPlacement.RelativePlacement = f.createIfcAxis2Placement3D(f.createIfcCartesianPoint((0.,0.,0.)))

f.write(...)
~~~

I think it's a fairly common problem though, quite a few authoring tools seem to insert arbitrarily large offsets at some point in the hierarchy, if you want to work on this personally I don't mind a pull request for IfcConvert in C++...

**Comment by andersgb** [comment]
This is my attempt at scripting it in python (I had to edit the fields in-place, if not it doesn't affect the relative placement hierarchy already existing):
```python
from __future__ import print_function
import ifcopenshell
import argparse


def ifc_site_at_origo(ifc_in, ifc_out):
    print("Opening {}...".format(ifc_in))
    ifc = ifcopenshell.open(ifc_in)
    site = ifc.by_type('IfcSite')[0]

    print("Modifying ObjectPlacement...")
    placement = site.ObjectPlacement.RelativePlacement
    placement.Axis.DirectionRatios = (0., 0., 1.) # Z
    placement.RefDirection.DirectionRatios = (1., 0., 0.) # X
    placement.Location.Coordinates = (0., 0., 0.) # origo

    print("Writing new file {}...".format(ifc_out))
    ifc.write(ifc_out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=('Strip away ObjectPlacement of IfcSite in an IFC:\n'
                     'Placing the IfcSite at origo (0, 0, 0) and with identity rotation'))
    parser.add_argument('--ifc-in', dest='ifc_in', required=True)
    parser.add_argument('--ifc-out', dest='ifc_out', required=True)
    args = parser.parse_args()
    ifc_site_at_origo(args.ifc_in, args.ifc_out)
```
I'll consider looking at a IfcConvert feature for this, but not today...

**Comment by aothms** [comment]
Ok, keep in mind that `Axis` and `RefDirection` are optional attributes. They may be set to `None` in which case `placement.Axis.DirectionRatios = (0., 0., 1.)` and below will raise exceptions.

**Comment by andersgb** [comment]
Ok, thanks for your input!
