### ISSUE TITLE
blenderbim chocolatey installer? rfc

### ISSUE THREAD

**Issue by fbpyr** [IfcOpenShell/IfcOpenShell#2300]
For being able to easily deploy blenderbim on win10 machines only from cli, I put together a chocolatey installer package: 

https://github.com/fbpyr/chocolatey_blenderbim_rfc 

@Moult I was wondering if there would be an interest to integrate it into blenderbim build process? 
and/or discussing the pros/cons here..

**Comment by Moult** [comment]
Do it! :D 

PR or directly committing would be awesome! I've never used chocolatey myself, so I can't do much in supporting it, but if you're happy to support it, more than happy for it to be a feature!

**Comment by fbpyr** [comment]
glad to see your positive reaction! 🙂 
direct PR would probably not (yet) help much in its current state, where it is specific for one nightly. 

Ideally I could understand a bit more about blenderbim release mechanics, so I can write something, 
that creates the chocolatey scripts dynamically for each nightly. (?) 
which touches on the subject of the of the release cycle of the chocolatey script - would it be for each nightly? 
I would think that this would be great, if chocolatey supports it.

maybe we can have a short screenshare at some point?

**Comment by fbpyr** [comment]
work continues here: 
https://github.com/fbpyr/IfcOpenShell/tree/choco_releases/choco/blenderbim

* [x] fork ifcopenshell: https://github.com/fbpyr/IfcOpenShell/tree/choco_releases/choco/blenderbim
* [x] divert github actions trigger to fbpyr repo
* [x] conditionally run choco step only on latest py+win
* [x] get sha256sum working
* [x] get repo secrets working
* [x] build choco with mono
  * [x] choco pack, setapikey, push package
* [x] get chocolatey maintainer account
* [x] get automated tests passing
* [ ] get chocolatey moderater review
  * [ ] get package listed
* [x] add blenderbim logo
* [ ] PR branch `choco_releases` to ifcopenshell

**Comment by Moult** [comment]
BTW is there a timeline for chocolatey moderator review?

**Comment by fbpyr** [comment]
@Moult very good question. 🙂  
I have no idea, but I will ping them politely - let's see what the response will be. 
Conversation should be visible on: https://community.chocolatey.org/packages/blenderbim-nightly/

**Comment by fbpyr** [comment]
Apparently there is an auto cleanup after 35 days, in case there was anything wrong with the package and I would not respond: 
https://docs.chocolatey.org/en-us/community-repository/moderation/#maintainer-process 
But clearly this is not the case with blednerbim-nightly, currently it is in `Status: Ready`
