### ISSUE TITLE
Segfault in Blender 3.3 alpha when using num_threads>=1 during iterator initialize()

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2309]
Reported here with full details: https://developer.blender.org/T99900

@aothms any ideas of what might be the cause? A bit stumped here.

**Comment by aothms** [comment]
Oei these things can be nasty. Instead of code changes we have to consider the possibility of config/stdlib/compiler changes as well.

First thing I'd try is to compile blender+ifsoph on same system with debug symbols and see what happens. If it also segfaults we can bisect to the really offending blender commit and probably workaround the issue or notify upstream. If it doesn't segfault, we should try and mimic as much of their build environment as possible until we can reproduce the crash.

Let me know how I can help.

**Comment by brunopostle** [comment]
I can't reproduce with the IfcOpenShell I compiled for fedora.

* I have a snapshot (from yesterday) of IfcOpenShell installed in /usr/lib64, built for python 3.10.5 and opencascade 7.5.0
* I'm using the default fedora radeon graphics
* running the problematic blender (blender-3.3.0-alpha+master.a02992f13138-linux.x86_64-release)
* This returns True and doesn't result in a segfault:

```
import sys
sys.path.append("/usr/lib64/python3.10/site-packages/")
import ifcopenshell
import ifcopenshell.geom
f = ifcopenshell.open('/home/bruno/Downloads/test.ifc')
s = ifcopenshell.geom.settings()
i = ifcopenshell.geom.iterator(s, f, num_threads=3)
i.initialize()
True
```

There is a full build log for this IfcOpenShell [here](https://download.copr.fedorainfracloud.org/results/bpostle/IfcOpenShell/fedora-35-x86_64/04661757-IfcOpenShell/builder-live.log.gz). Configuration is:

```
CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall \
-Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS \
-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong \
-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables \
-fstack-clash-protection -fcf-protection'

/usr/bin/cmake -S . -B redhat-linux-build -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
-DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
-DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 \
-DBUILD_SHARED_LIBS:BOOL=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 \
-DLIBDIR=/usr/lib64 -DINCLUDEDIR=/usr/include -DBINDIR=/usr/bin -DOPENCOLLADA_INCLUDE_DIR=/usr/include \
-DENABLE_BUILD_OPTIMIZATIONS=ON -DLIBXML2_INCLUDE_DIR:FILEPATH=/usr/include/libxml2 \
-DCMAKE_CXX_FLAGS=-lxml2 -DOCC_INCLUDE_DIR=/usr/include/opencascade -DBUILD_SHARED_LIBS=1 \
-DJSON_INCLUDE_DIR=/usr/include -DGLTF_SUPPORT=ON -DHDF5_SUPPORT=ON -DUSE_MMAP=ON \
-DGMP_LIBRARY_DIR=/usr/lib64 -DMPFR_LIBRARY_DIR=/usr/lib64 -DHDF5_LIBRARY_DIR=/usr/lib64 \
-DHDF5_INCLUDE_DIR=/usr/include
-- The C compiler identification is GNU 11.3.1
```

**Comment by Moult** [comment]
@brunopostle so you're saying that an IfcOpenShell you compiled, combined with a downloaded Blender build a02992f13138 works?

What about the IfcOpenBot build combined with a downloaded Blender build a02992f13138?

**Comment by brunopostle** [comment]
@Moult yup, my IfcOpenShell compiled in the fedora infra is fine.

..and installing blenderbim-220722-py310-linux.zip into this blender 3.3 alpha, I see the segfault:

```
# Blender 3.3.0, Commit date: 2022-06-29 10:58, Hash a02992f13138
Modules Installed (blenderbim) from '/home/bruno/Downloads/blenderbim-220722-py310-linux.zip' into '/home/bruno/.config/blender/3.3/scripts/addons'  # Info
bpy.ops.bim.save_drawing_style(index="2")  # Operator
bpy.context.area.ui_type = 'CONSOLE'  # Property

# backtrace
./blender(BLI_system_backtrace+0x20) [0xc22f250]
./blender() [0x11f46ca]
/lib64/libc.so.6(+0x55350) [0x7fadee255350]
./blender(_ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv+0x17) [0x290a5f7]
/lib64/libc.so.6(+0xa4fe8) [0x7fadee2a4fe8]
/home/bruno/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/_ifcopenshell_wrapper.so(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZNSt13__future_base17_Async_state_implINS1_IS2_IJZN7IfcGeom27IteratorImplementation_Ifc410initializeEvEUlvE_EEEEvEC4EOS9_EUlvE_EEEEE6_M_runEv+0x118) [0x7fadb0bc9918]
./blender() [0xc6c13c0]
/lib64/libc.so.6(+0x9fdb2) [0x7fadee29fdb2]
/lib64/libc.so.6(+0x3f9e0) [0x7fadee23f9e0]

# Python backtrace
```

**Comment by Moult** [comment]
Cross posting from the Blender issue:

> Since the change of build environment from ifcOpenShell seems to fix the issue introduced here, that fits well with the theory of symbols incompatibitilies.
> For Blender it's CentOS 7 / GCC 9.3.1 / GLIBC 2.17 and it hasn't changed in between builds lately, do you know what IfcOpenShell build system environment is?

@aothms do you know the answer?

**Comment by aothms** [comment]
We compile on Ubuntu focal (20.04) with GCC 9.3.0.3 and GLIBC 2.31 (I think, I just searched the ubuntu package website)

Should we add a worker on CentOS 7? Is there somebody that could help with updating https://github.com/IfcOpenShell/IfcOpenBot and build-all.py so that it works with yum as well as apt?

**Comment by Moult** [comment]
This is fixed upstream :) Tested with a electrical model with lots of objects, but relatively simple geometry (i.e. no crazy imported manufacturer objects) this is fairly typical for large projects where IfcOpenShell is long finished processing and the bottleneck is Blender:

Number of objects | Stable Blender 3.2 | WIP Blender 3.3 Alpha | New Blender 3.3 Beta
30,000 | 68.1s | 62.3s | 45.2s
60,000 | 262.0 | 237.1s | 157.7s

So the average user who will be switching from stable Blender 3.2 to stable Blender 3.3 will see about 50-65% faster imports! Nice!

Closing bug. Huge thanks to @ecke101 who has been involved with this since the beginning :)
