### ISSUE TITLE
IfcStair From and To Levels

### ISSUE THREAD

**Issue by archids** [IfcOpenShell/IfcOpenShell#2317]
Hi:

Using IfcOpenShell, is there a way to find Stories or slabs that the staircase is connecting between?  In IFC2x3 Schema I see ConnectedTo and ConnectedFrom properties, which was unpopulated for the model exported from Revit.  In IFC4 Schema I don't see those properties listed at all.
For future would be great to have this basic information added to the IfcStair or the IfcStairFlight.

Thanks!

**Comment by aothms** [comment]
These kind of higher level relationships are sometimes hard to recover from an IFC model, which is mostly just elements floating in space. ConnectedTo and ConnectedFrom haven't been removed in IFC4, but I don't think it's usage was intended for this. It's more for physical element connections, such as wall joins.

You can use software such as IfcOpenShell to obtain this kind of information from the geometry. Comparing the stair lowest and highest vertex to the building storey elevations is a pretty straightforward and robust way to derived the info,

**Comment by archids** [comment]
Thanks Thomas!

Yeah it gets little tricky with multi-level staircase and finding intermediate floors.  I was trying to keep this authoring software agnostic but I may just export out from Revit as Pset-StairCommon if it's possible to make my life easier.

Thanks again!

**Comment by Moult** [comment]
Typically the stair should be contained in the lowest storey, and then if done correctly, referenced in all subsequent storeys I believe.

**Comment by archids** [comment]
Hello Moult:

Thanks for your comment.  I know that's how Staircase is represented in IFC.  I know all the great work you are doing with IFC and highly appreciate it.  But one of the biggest frustrations for those in AEC industry is that fundamental information such as how a Staircase is represented in the industry for any stake holders is to know the levels it connects between for design, construction, way-finding or exit analysis, etc.  I think that this should be included in common property set.  This shouldn't be analyzed based on geometry representation.

**Comment by brunopostle** [comment]
@archids could this type of circulation analysis be done with IfcSpaces each of which can be tagged with OccupancyType?

**Comment by aothms** [comment]
In my experience it gets even harder for elevators. Property sets aren't great though for references to to other elements (it exists, but is hardly supported in tools). Spaces could indeed work, but in complex multi-storey situations I guess you'd still need a proper geometric understanding to make sense of all the space connectivity then.

IFC is a generic data model. Functional connectivity information is indeed sometimes hard to recover semantically for doors, beams, columns, signage ... That's why I'd recommend to invest some time in geometric analysis, because it tends to solve these kind of questions fairly generally and the tooling exists to efficiently compute them.

**Comment by Moult** [comment]
@archids analysing the geometric representation is not necessary. The first one, "contained in" refers to a relationship between objects (i.e. the stair object and the storey object), which is supported by pretty much everything. The second one is the issue, the "referenced in" relationship which has relatively poor support by authoring apps. It's actually just as straightforward as the "contained in" just that vendors (including, guilty as charged, myself) are turning a blind eye.

**Comment by aothms** [comment]
I think @archids point is that "Referenced in" does not necessarily mean that the stair also functionally connects (e.g allows people to get off the stair and enter the storey).

**Comment by archids** [comment]
Thanks everyone!

@brunopostle 
This will not work for all use cases unfortunately.  I am representing BIM models as Graph Networks and obviously looking at IFC Relationships are one way to derive edges in the graphs with some massaging.  For example shortest route calculation will not work with occupancy alone.

@aothms 
Thomas you are kinda right in your last post about connection functionality.  If the IfcStairFlight has the information on the two IfcSlabs or other Structure it connects to, I can derive even for multi-storey buildings by IfcContainedInStructure relationship.  Even to find doors for a Room/Space, I can go BoundedBy, get the Walls and get the Openings and get the Door or Windows by FillsVoids.  But for staircase, there is just no such possibility.  For example Slab has an opening where the Stair fills the void.   Btw, the space connectivity can be derived from the network graph without geometric analysis.  I will look in to it also.

@Moult 
ContainedIn relationship doesn't list all the stories that the stair connects to.  Only the Base Storey.  To me IfcRelConnectsElements would be where logically I would look at to see if the Stair connects to say IfcSlabs and from which I can derive the storiess as IfcSlab's IfcContainedInStructure gives me that info.

**Comment by aothms** [comment]
>  Btw, the space connectivity can be derived from the network graph without geometric analysis

This requires space boundaries, which are not always (reliably present). Especially in the case where there is no element in between the authoring tool is supposed to emit an IfcVirtualBoundary, which I also don't always see.

**Comment by archids** [comment]
I see!

So far with all the IFC files generated from Revit and Archicad I didn't come across this issue.  Usually I am able to extract Space's IsBoundedBy elements.

**Comment by Moult** [comment]
@archids I was not referring to the ContainedIn relationship, I was referring to this: http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcRelReferencedInSpatialStructure.htm

**Comment by archids** [comment]
@Moult
Thanks for  the heads-up. That looks promising and hope it gets implemented for the stairs by the vendors, at least the popular ones.

**Comment by Moult** [comment]
For a bit of closure on this bug, can I recommend making it a set of todo items to add support in the ifcopenshell api for the referencing relationship? And of course maybe a GUI for it in the BlenderBIM Add-on so people can visually explore this relationship. It has a lot of uses, more than stairs, also things like service shafts, multistorey columns, lifts, multistorey facade elements, etc.

**Comment by archids** [comment]
@Moult 
That would be great and absolutely a critical relationship to be implemented.  
Thanks!

**Comment by Moult** [comment]
Screenshot showing how a stair now shows the bottom and top levels that it connects to.

![2022-08-22-135025_958x499_scrot](https://user-images.githubusercontent.com/88302/185836209-b673baca-8f4d-493f-9ec5-2749e71872d9.png)

**Comment by archids** [comment]
This is awesome.  one question though?  does the base and top level info work for stair flights also?  in some cases mid-landing is used to access intermediate floors also.

Thanks!

**Comment by aothms** [comment]
I just wanted to quickly pitch in that:

> **IfcStairFlight**
> 
> A stair flight is an assembly of building components in a single "run" of stair steps (not interrupted by a landing)

So what we see here in the image should be an IfcStair decomposed into {IfcStairFlight, IfcSlab}.

Not sure if it has much bearing on the issue, but it may simplify it.

**Comment by Moult** [comment]
@archids yep so as @aothms mentioned stair flights are a part of a stair. So the stair would presumably have the bottom storey as its container, and also reference all other storeys. Then, then stair flights within it would reference the levels they connect to (notice the * symbol next to IfcBuildingStorey/01, which means that it is indirectly contained via its aggregate IfcStair). Similarly, landing slabs can reference the level they're on.

**Comment by archids** [comment]
Thanks both!
