### ISSUE TITLE
Issue regarding trying to download or get a copy of Dion's IFC Diff

### ISSUE THREAD

**Issue by NebilHassen** [IfcOpenShell/IfcOpenShell#2319]
Hello,

Is there anybody thats familiar with the Add on: IFC DIFF. Im sort of in need of the functions that the ADD On would offer, but i cant seem to find it or make it work, and there doesnt sseem to be any documentation of it anywhere either (https://blenderbim.org/docs-python/ifcdiff.html , i might be looking at the wrong place, please someone correct me on this)

And another thing is there anybody here with any experience/knowledge on the topic, there seems to be a group from china that have made an IFC file comparison software, is it the same thing that Dion has made on his website with Api documentation (the linked site over), or are the group from china making something completely else:
https://yushen-liu.github.io/ifcdiff/index.html

Thank you for the help so far! And as always this community is the best!

**Comment by aothms** [comment]
If you're familar with running python code, you can run the code which is available here. It assumes GlobalIds are constant. The code uses Deepdiff to find changes in element hierarchies. It has some great features, but can hard to tweak.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcdiff/ifcdiff.py

There is also this more tutorial style walkthrough. It also compares element trees, but can work without the assumption of constant GlobalIds.

https://academy.ifcopenshell.org/posts/calculate-differences-of-ifc-files-with-hashing/

I would assume the group from Tsinghua uses an independent method (although likely comparable to the above two).

**Comment by NebilHassen** [comment]
Thank you so much for your help @aothms, while you're here, what does Global ids (GlobalIds) mean? Like what are they, and what do they mean?

**Comment by aothms** [comment]
It's the first attribute of the building element that describes a stable unique identifier that comes from the authoring software

~~~
#91=IFCWALLSTANDARDCASE('2O2Fr$t4X7Zf8NOew3FL9r',#1,'Basic Wall:Interior - P...
                         ^^^^^^^^^^^^^^^^^^^^^^
~~~

**Comment by NebilHassen** [comment]
Hi,

Great content with the hashing method, but im afraid im not getting the pictures that illustrate the concept up. Do get them? @aothms 

From: https://academy.ifcopenshell.org/posts/calculate-differences-of-ifc-files-with-hashing/?fbclid=IwAR2xnmJtYJE7MSvzSyE39Y-pmWEnnAKYSEfxteDkDkVCMWi7SgRL7arjPZg


![Pictures are lacking](https://user-images.githubusercontent.com/83288449/182167517-860dc8c6-404e-47dc-964e-f5f78f240053.png)

**Comment by Moult** [comment]
Thanks for the heads up, documentation has been added and recent optimisation has made IfcDiff twice as fast as it was previously, so hopefully things should be all good now :)
