### ISSUE TITLE
IfcSweptDiskSolidPolygonal - FilletRadius

### ISSUE THREAD

**Issue by sbeAAJ** [IfcOpenShell/IfcOpenShell#2322]
The FilletRadius attributes doesnt affect the shape representation, see:
https://sourceforge.net/p/ifcopenshell/discussion/1782716/thread/abf2e3d8fd/

**Comment by aothms** [comment]
This is now implemented. Please test.

[fail-x-300mm-y-500mm-3d-poly.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9594129/fail-x-300mm-y-500mm-3d-poly.ifc.txt)

[pass-x-500mm-y-500mm-2d-indexed.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9594130/pass-x-500mm-y-500mm-2d-indexed.ifc.txt)

![afbeelding](https://user-images.githubusercontent.com/1096535/190910833-7bdc59bd-3061-46bc-bf38-0af437649dba.png)

**Comment by Moult** [comment]
I had to fix these two lines but confirming this works:

```
#26=IFCINDEXEDPOLYCURVE(#21,$,.F.);
#22=IFCSWEPTDISKSOLIDPOLYGONAL(#26,0.01,$,$,$,0.2);
```
