### ISSUE TITLE
BB New Browse construction types panel gives error code when viewing

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2324]
![image](https://user-images.githubusercontent.com/78321676/182132410-5b07765f-e731-4838-a54e-b2918e8a4d9d.png)
It doesnt seem to cause any problems? It still works But it throws up this error when I try to view the construction browser

**Comment by Moult** [comment]
Cheers, I only briefly started refactoring today, I'll continue tomorrow.

**Comment by cvillagrasa** [comment]
I was counting different vertical spacing depending on whether it was the last row of assets or not, so after the refactor of today, `import math` should also be on _ui.py_. But maybe @Moult suggests to avoid all of this, so yeah, @Plae-Blue-Dot , thanks for catching this, but beware that the browser code is going to be unstable for the next couple of days!

**Comment by Plae-Blue-Dot** [comment]
Ok Got it, I'll refrain from posting errors until it's a bit more stable, it's an excellent addition well done!

**Comment by cvillagrasa** [comment]
Now, this particular bug should have been fixed in https://github.com/IfcOpenShell/IfcOpenShell/commit/5cc11a170b23b6260749901cbf022e22794bfcf3

**Comment by Plae-Blue-Dot** [comment]
Seems to be working!
