### ISSUE TITLE
[IfcConvert] Cache : settings mismatch

### ISSUE THREAD

**Issue by ketourneau** [IfcOpenShell/IfcOpenShell#2333]
I woud like to use cache file to convert ifc to dae and svg.

I try to used latest IfcConvert build (https://github.com/IfcOpenBot/IfcOpenShell/commit/dc67287d4b083cabae39ee4f92fa93b6f74cae11#commitcomment-78799114).

First I convert ifc to dae (create geometry cache) :
`IfcConvert walls.ifc walls.dae --cache`

Then I convert ifc to svg (use geometry cache) :
`IfcConvert walls.ifc walls.svg --exclude entities IfcSpace IfcOpeningElement --cache-file walls.ifc.cache.h5`

I got error :
`[Error] [2022-08-03 15:29:04] {0yQzjPp_z7Uw7R8LgQoskT} Settings mismatch`

Is the cache specific to each type of conversion ?
How can we avoid parsing the geometry again for svg conversion ?

[walls.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9251761/walls.ifc.zip)

**Comment by aothms** [comment]
At some point we decided that SVG serialization requires SEW_SHELLS https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcconvert/IfcConvert.cpp#L803

So if you want to reuse geom generation for SVG and DAE you need to call DAE conversion with --orient-shells - we at some point renamed the command line arg, but not the serializer setting... :(

I'm not very impressed with the performance of caching in its current form.

You'll get better results writing a Python script that initializes the serializers and iterators as you please and directly to 1-n files with 1-n serializers without the need for serializing the geometry results to disk.

**Comment by ketourneau** [comment]
Thank you very much for your reply !
