### ISSUE TITLE
BBim: Smart tag cannot reference QUantities PSets or materials, but works with Atributes

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2340]
What the heading says and from the conversation here in detail:

https://community.osarch.org/discussion/1073/blenderbim-smart-tag-get-area#latest

**Comment by theoryshaw** [comment]
maybe? 
https://github.com/IfcOpenShell/IfcOpenShell/pull/2389

**Comment by Moult** [comment]
I think this is now fixed thanks to @theoryshaw.
