### ISSUE TITLE
script obj2ifc: update to ifc4 and collect_faces=False

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2342]
Here is the [script](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/scripts/obj2ifc.py)

On line 77 the default is version="IFC2X3", when i changed it to version="IFC4", the script throws me a error and i don't know how to debug it.

On line 36 the default is collect_faces=True

> collect_faces will collect triangle face data for every mesh. In case faces with more than three vertices are specified they will be triangulated
From [here](https://github.com/pywavefront/PyWavefront)

Because of this behavior it smashes my faces, since my faces are described from more than three vertices. There are triangles, which did not exist before, are additional in my surface.

But if I set collect_fase = "False", the script does not work at all.

I became aware of this script because I wanted to automatically create ifc from obj file, so this script was a huge help, because i didn't how to give to a ifc_entity the geometry from a obj file.

Thank you very much for the work on this script.

**Comment by aothms** [comment]
> when i changed it to version="IFC4", the script throws me a error and i don't know how to debug it.

What's the error?

> On line 36 the default is collect_faces=True

https://github.com/pywavefront/PyWavefront/blob/master/pywavefront/obj.py#L276-L277

It indeed seems faces are not stored without this setting. Triangulation is a sane default for visualization but for conversion to IFC I agree it's not a great.

Not sure on the best course of action. The OBJ format is trivial. I typically do my own parsing for it e.g https://github.com/AECgeeks/ifc-pipeline/blob/voxels/application/simplify_obj.py#L28-L58 (this particularly has a lot of assumptions, but essentially it's also not miles away from something that would work).

Are you interested in working on improving these limitations?

**Comment by Martin15135215** [comment]
Hi Aothms 

1. [Here ](https://github.com/Martin15135215/ifcopenshell_test/blob/5ed01ee7e979944c53530dc77ee7c5d7e5dbb54c/obj2ifc4.py#L77)i changed IFC2X3 to IFC4 and used [this](https://github.com/Martin15135215/ifcopenshell_test/blob/main/cubus.obj) test cube. 

Error message:

```
python obj2ifc4.py cubus.obj

Traceback (most recent call last):
  File "C:\Users\Martin\obj2ifc4.py", line 125, in <module>
    obj2ifc.execute()
  File "C:\Users\Martin\obj2ifc4.py", line 35, in execute
    self.create_ifc_file()
  File "C:\Users\Martin\obj2ifc4.py", line 79, in create_ifc_file
    person.Id = person.GivenName = None
  File "C:\Users\Martin\miniforge\envs\pyifc\lib\site-packages\ifcopenshell\entity_instance.py", line 176, in __setattr__
    self[index] = value
  File "C:\Users\Martin\miniforge\envs\pyifc\lib\site-packages\ifcopenshell\entity_instance.py", line 190, in __setitem__
    method = self.method_list[idx]
IndexError: list index out of range
```

**Comment by Martin15135215** [comment]
2. I like to help out on it. However I have a knowledge gap on how to even assign geometry to an ifc entity.

[Here ](https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples)it has no examples how to add geometry to an Ifc entity. So can you send me links where I can learn this on my own so I can suggest a solution here?

I also asked [here](https://community.osarch.org/discussion/1074/ifcopenshell-python-from-obj-file-to-ifc-file#latest)once, because of my problem to make an ifc file out of an obj.

**Comment by Martin15135215** [comment]
Mabye the solution for the second problem would be, using [pymeshlab ](https://pypi.org/project/pymeshlab/)(last update: Mar 8, 2022) or [open3d ](https://pypi.org/project/open3d/)(last update: Feb 28, 2022) instead of [pywavefront ](https://pypi.org/project/PyWavefront/)(last update: Dec 10, 2020).

The advanteges of pymeshlab for example would be, that it can [supports ](https://pymeshlab.readthedocs.io/en/latest/io_format_list.html) more than just obj. 

For pymeshlab to get vertex and faces:

`````
# create a new MeshSet
ms = pymeshlab.MeshSet()
ms.load_new_mesh(base_path + 'chameleon.pts')

# get numpy arrays of vertices and faces of the current mesh
v_matrix = m.vertex_matrix()
f_matrix = m.face_matrix()
`````

Code found [here](https://pymeshlab.readthedocs.io/en/latest/tutorials/get_mesh_values.html)

**Comment by aothms** [comment]
>   File "C:\Users\Martin\obj2ifc4.py", line 79, in create_ifc_file
>     person.Id = person.GivenName = None

Oh that's for some reason in IFC4 they decided to rename the attribute Id on IfcPerson to Identification

![afbeelding](https://user-images.githubusercontent.com/1096535/184477140-92d15278-8f5f-443e-8640-ac4ac94fefd3.png)

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/schema/ifcactorresource/lexical/ifcperson.htm

It remains the first attribute though, so you can change it to:

    person[0] = person.GivenName = None

(it's a bit ugly, but it saves some try-catch or hasattr inconveniences)

The same applies to `org.Id` a bit later on.

I think it's a great idea to use a more general mesh reading library. A lot of people here are relative newcomers to programming, we're here to help. Hope you find the time to contribute these changes.

**Comment by Moult** [comment]
@Martin15135215 would you be interested in updating the script to use pymeshlab instead? I can help guide on the IFC side of things, and also do pair programming if you'd like. There's a community available live on osarch.org/chat

**Comment by Martin15135215** [comment]
@aothms Thanks for the input. I changed it, and the script works. [Here](https://github.com/Martin15135215/git_ifc_test/blob/16fd77495fdd63fa37d367f4973336ed446c9382/obj2txt_ifc4.py#L77) the changed script. I tried the script on [this cube](https://github.com/Martin15135215/git_ifc_test/blob/main/test_obj_cubus/cubus_d.obj) and [this](https://github.com/Martin15135215/git_ifc_test/blob/main/test_obj_cubus/cubus_d.ifc) is the result.

Why did the created ifc file has this filename -> [FILE_NAME('/dev/null','2022-08-16T20:37:02+02:00',(),(),'IfcOpenShell v0.7.0-cb8cfd79','IfcOpenShell v0.7.0-cb8cfd79','Nobody');](https://github.com/Martin15135215/git_ifc_test/blob/16fd77495fdd63fa37d367f4973336ed446c9382/test_obj_cubus/cubus_d.ifc#L4)

I mean the /dev/null linux inside joke?

Whats the difference between `ifcopenshell.api.run("project.create_file", version="IFC4")` and `ifcopenshell.file(schema='IFC4')`?

**Comment by Martin15135215** [comment]
so i did now a test, how pymeshlab and pywavefront show vertices and faces. the main difference would be pymeshlab uses ndarray. Would this be a problem?

![image](https://user-images.githubusercontent.com/110968398/184961299-2dccfd64-0cff-4571-b93e-dfeb62002a94.png)

![image](https://user-images.githubusercontent.com/110968398/184961387-b2ad9035-d4d8-4c1e-87fa-a2c143a0b154.png)

Here the [jupyternotebook ](https://github.com/Martin15135215/git_ifc_test/blob/main/test_pymeshlab.ipynb)with pymeshlab and pywavefront. I try to change the script obj2ifc to use pymeshlab instead of pywavefront.

**Comment by Martin15135215** [comment]
So i did change [the script](https://github.com/Martin15135215/git_ifc_test/blob/68995a86451db53c155445b797897448e6b86a99/obj2ifc_pymeshlab.py#L36) to use pymeshlab instead of pywavefront. 

i changed also [this ](https://github.com/Martin15135215/git_ifc_test/blob/68995a86451db53c155445b797897448e6b86a99/obj2ifc_pymeshlab.py#L44)and [this](https://github.com/Martin15135215/git_ifc_test/blob/68995a86451db53c155445b797897448e6b86a99/obj2ifc_pymeshlab.py#L50).

i than ran is with [this cube](https://github.com/Martin15135215/git_ifc_test/blob/main/test_obj_cubus/cubus_c.obj) and got a error :(

Here the error output from `python obj2ifc_pymeshlab.py test_obj_cubus\cubus_c.obj`:

```
Traceback (most recent call last):
  File "C:\Users\Martin\git_ifc_test\obj2ifc_pymeshlab.py", line 130, in <module>
    obj2ifc.execute()
  File "C:\Users\Martin\git_ifc_test\obj2ifc_pymeshlab.py", line 50, in execute
    [self.file.createIfcCartesianPoint(vertices[index]) for index in face]
  File "C:\Users\Martin\git_ifc_test\obj2ifc_pymeshlab.py", line 50, in <listcomp>
    [self.file.createIfcCartesianPoint(vertices[index]) for index in face]
  File "C:\Users\Martin\miniforge\envs\pyifc\lib\site-packages\ifcopenshell\file.py", line 276, in create_entity
    e[idx] = arg
  File "C:\Users\Martin\miniforge\envs\pyifc\lib\site-packages\ifcopenshell\entity_instance.py", line 196, in __setitem__
    self.method_list[idx](self.wrapped_data, idx, entity_instance.unwrap_value(value))
  File "C:\Users\Martin\miniforge\envs\pyifc\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4857, in setArgumentAsAggregateOfDouble
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsAggregateOfDouble(self, i, v)
TypeError: Attribute of type AGGREGATE OF REAL needs a python sequence of floats
```
I don't understand, because from my [jupyternotebooktest](https://github.com/Martin15135215/git_ifc_test/blob/main/test_pymeshlab.ipynb), the ouput from pymeshlab should be identical to pywavefront?

**Comment by Moult** [comment]
You need to use `.tolist()` to get the Python sequence of floats that IfcOpenShell needs from the ndarray. I've just committed an updated script which uses meshlab as you recommend: https://github.com/IfcOpenShell/IfcOpenShell/commit/ae2fd672602562d8ab416cf641f42940379f06c0

The pros are:

 - Quads supported
 - More filetypes supported

The cons are:

 - Maybe no materials? Haven't checked
 - It seems as though OBJs are collapsed into a single mesh: https://github.com/cnr-isti-vclab/PyMeshLab/issues/247 - this is a pretty big showstopper I reckon, which is why I've kept the original pywavefront script for now.

**Comment by Martin15135215** [comment]
Hi, thanks for the upgraded script :)

Where do you using the material in the original [script](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/scripts/obj2ifc.py)?

i only saw [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/ae2fd672602562d8ab416cf641f42940379f06c0/src/blenderbim/scripts/obj2ifc.py#L36) that you load the material with the keyword `create_materials=True`, however i don't see where you use it in the script?

Can we just use a  workaround for the problem, that the OBJs are collapsed into a single mesh?

Like writing the different objects in an obj file to several obj files and do this for-loop:
```
for obj_file in obj_files:
    mesh_set.load_new_mesh(obj_file)
        for mesh in mesh_set:
```

**Comment by Moult** [comment]
Yes, I call `create_materials=True` but haven't built anything yet for materials :) It's the thought that counts. I guess in the future material support could be added.

The workaround isn't very pleasant, OBJs could be produced by all sorts of different software where they don't have this control.

**Comment by Martin15135215** [comment]
[testface.obj](https://github.com/Martin15135215/git_ifc_test/blob/main/testface.obj) opened in Blender:

![image](https://user-images.githubusercontent.com/110968398/185103999-c2ce1197-f347-4ea2-ab53-74120e596561.png)


[testface_pywavefront.ifc](https://github.com/Martin15135215/git_ifc_test/blob/main/testface_pywavefront.ifc) created with [obj2ifc4.py](https://github.com/Martin15135215/git_ifc_test/blob/main/obj2ifc4.py) -> it uses the pywavefront module

![image](https://user-images.githubusercontent.com/110968398/185103852-717e2f86-57c6-42cf-9264-c16ee8d0d394.png)


[testface_pymeshlab.ifc](https://github.com/Martin15135215/git_ifc_test/blob/main/testface_pymeshlab.ifc) created with [obj2ifc_meshlab_ifc4.py](https://github.com/Martin15135215/git_ifc_test/blob/main/obj2ifc_meshlab_ifc4.py) -> it uses the pymeshlab module

![image](https://user-images.githubusercontent.com/110968398/185103899-bcf0343c-c374-4312-b35c-9da05e2a05b3.png)

**Comment by Martin15135215** [comment]
Hi all, i also did update the thread [here](https://community.osarch.org/discussion/1074/ifcopenshell-python-from-obj-file-to-ifc-file#latest). Thanks you both for the help!

a litte question: How can i change the color with ifcopenshell-python?

**Comment by Moult** [comment]
I've just updated the script to allow for different schema versions superficially. I've answered how to deal with colours in the forum thread :)

I think we can close this - I'm not too happy with the restrictions on pymeshlab, but until we hear back from them there's not much I can do.
