### ISSUE TITLE
BB: possible to not have to restart BB to see custom psets

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2343]
Is it possible to not have to restart BB to see custom psets. 

Discussed a little here: https://community.osarch.org/discussion/comment/12209

**Comment by vulevukusej** [comment]
This is already possible, i think you're referring to being able to use PsetTemplates without restarting, right?

**Comment by vulevukusej** [comment]
@Moult - is this something that can be fixed by updating data.py in the pset_templates module?

**Comment by Moult** [comment]
Yes I suspect so.

**Comment by Moult** [comment]
I was wrong, it wasn't related to refactoring the data class, but more related to purging the already loaded template cache. However I ended up refactoring the data classes in the meantime too.
