### ISSUE TITLE
Why am I stuck compiling and the progress is not moving

### ISSUE THREAD

**Issue by kingui1106** [IfcOpenShell/IfcOpenShell#2344]
Why am I stuck compiling and the progress is not moving.
I've had several different computers, and they've all been like this.
After compiling started for a while, the computer basically froze.
The compilation will not complete.
Is there a precompiled library that provides c++

The environment:
vs2019

**Comment by aothms** [comment]
You don't give any details on what part of the compilation process you're in, but if you the IDE you might want to try and disable /MP 

![afbeelding](https://user-images.githubusercontent.com/1096535/184623368-dad71040-005e-4c3b-8994-51fda5c2638b.png)

Or `-DMSVC_PARALLEL_BUILD=Off` if you rerun cmake https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/cmake/CMakeLists.txt#L56

**Comment by aothms** [comment]
It seems /MP is not always handled very well, I have disabled it by default, but developers running the IDE are recommended to enable it.

**Comment by Moult** [comment]
@kingui1106 can you confirm whether or not the fix works for you?

If no response I'll assume it's fixed and close the issue in a week :)

**Comment by kingui1106** [comment]
> You don't give any details on what part of the compilation process you're in, but if you the IDE you might want to try and disable /MP
> 
> ![afbeelding](https://user-images.githubusercontent.com/1096535/184623368-dad71040-005e-4c3b-8994-51fda5c2638b.png)
> 
> Or `-DMSVC_PARALLEL_BUILD=Off` if you rerun cmake https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/cmake/CMakeLists.txt#L56

yeah，it is useful
