### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2345]
[This](https://github.com/hypar-io/IFC-gen/blob/c7d3c58cd812ae001795cc35cf36c11984bdee84/lang/csharp/test/models/example.ifc) file w/ BB 0.0.220802

It imports in BIMcollab zoom.

```

Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 531, in execute
    context.scene.BIMProjectProperties.total_elements = len(tool.Ifc.get().by_type("IfcElement"))
AttributeError: 'NoneType' object has no attribute 'by_type'

location: <unknown location>:-1


```

**Comment by Moult** [comment]
The IFC file uses an invalid schema: ifcopenshell.SchemaError: Unsupported schema: IFC4RC4

Rename "IFC4RC4" to "IFC4" and it works :)
