### ISSUE TITLE
Convert .ifcxml to .ifc when running ifcopenshell.open()

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2350]

**Comment by Moult** [comment]
Pinging @aothms on thoughts about this, to allow ifcopenshell.open() to transparently handle ifcxml/ifczip without the user needing to worry about it. Is it OK?

It would be basically upstreaming this bit of code:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/ifc.py#L113-L124

(with maybe more intelligent extension checking than the way I did it)

**Comment by CyrilWaechter** [comment]
@aothms Sorry to bother you but this improvement would be super useful. It would for example allow to run ifcpatch recipes on ifczip files transparently.

**Comment by aothms** [comment]
Looks good to me. Sorry for the delay.

I would say to include a default keyword argument `format=None` where in case of None autodetection happens based on extension (no or unknown extension is spf). Manually specified format means use of that encoding regardless of extension.
