### ISSUE TITLE
IFC Text size not saved with IFC - BlenderBim

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2352]
Testing multiple files, the text size does not save with the IFC on reload it defaults to 2.5mm (which is default)

Text in IFC before closing
![image](https://user-images.githubusercontent.com/78321676/185370584-184d4fc9-905f-444a-9fb4-d29f64117b93.png)

Text in IFC after reloading
![image](https://user-images.githubusercontent.com/78321676/185370664-bbe2c10e-91f4-4871-aeea-77f6b53079a6.png)

**Comment by theoryshaw** [comment]
It doesn't look like that functionality is there yet. 

@Moult does the roapmap include capturing the font size, etc, like this?

```
#160= IFCSTYLEDITEM(#159,(#151),$);
  /*#159= IFCTEXTLITERALWITHEXTENT('1/8" Arial',#157,.LEFT.,#158,'top-left');*/
    /*#157= IFCAXIS2PLACEMENT3D(#155,$,$);*/
      /*#155= IFCCARTESIANPOINT((0.0437004873160288,0.397855078035372,0.));*/
    /*#158= IFCPLANAREXTENT(17.5842684236566,1.65064102564103);*/
  /*#151= IFCPRESENTATIONSTYLEASSIGNMENT((#150));*/
    /*#150= IFCTEXTSTYLE('1/8" Arial',#149,$,#146);*/
      /*#149= IFCTEXTSTYLEFORDEFINEDFONT(#148,$);*/
        /*#148= IFCCOLOURRGB($,0.,0.,0.);*/
      /*#146= IFCTEXTSTYLEFONTMODEL('Text Font',('Arial'),$,$,$,IFCPOSITIVELENGTHMEASURE(1.04166666666667));*/

```

If so, by a small miracle, I could try to tackle it. :grimacing:  I will make no promises, however. ;)

**Comment by Moult** [comment]
Yes, the functionality isn't there yet, specifically because implementing it properly involves building support for IFC font and text styles. I made a start towards implementing it a while ago, in Scene Properties > IFC Geometry > IFC Styles at least now you can see if a text style exists in the project.

**Comment by Moult** [comment]
I debated this quite a bit ... debating between implementing IfcTextStyles vs making it a pure SVG+CSS solution. In the end I ended up with SVG+CSS. It's simpler, and CSS already is a tried and proven technology. I think it is a mistake to include this type of thing in IFC ... IFC should focus on the semantics more than replicating existing standards.

The new solution also doesn't hardcode the font family or font-sizes, so you have more flexibility too.

**Comment by Plae-Blue-Dot** [comment]
Hey Moult thanks for sorting this! I think using CSS is a great idea, my question is now that the IFCText size has been removed here:
![image](https://user-images.githubusercontent.com/78321676/218402557-0d4255b0-5ba5-45d4-9d69-a7fe4265c360.png)

how does one set the text 'type' in the ifc to one of these types? 
![image](https://user-images.githubusercontent.com/78321676/218402515-6ec460b8-b72b-4326-8352-3f75890d57f9.png)

**Comment by Moult** [comment]
@Plae-Blue-Dot it's now in EPset_Annotation you can set the "Classes" property. This works not just for text, but for any annotation. You can set multiple classes separated by whitespace, just like in CSS.

**Comment by Plae-Blue-Dot** [comment]
Thanks @Moult !

Works like a charm:
![image](https://user-images.githubusercontent.com/78321676/218430413-ede8a790-0784-4cfe-8d27-d62253472767.png)
