### ISSUE TITLE
Blenderbim - Error when printing SVG

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2353]
Error when printing SVG from IFc in Blenderbim

![image](https://user-images.githubusercontent.com/78321676/185403610-48408924-be33-4963-b207-99936dc0c447.png)

**Comment by Moult** [comment]
This is a difficult one because the error is not specific enough for me to replicate. Do you have sample steps / sample file to recreate?

**Comment by Plae-Blue-Dot** [comment]
Hey Moult it was the last thing I did last night and it seems to no longer be an issue as of this morning so I cant even replicate it, I'll close the error, apologies for the waste of time

**Comment by Plae-Blue-Dot** [comment]
Error no longer present unable to replicate
