### ISSUE TITLE
[BlenderBim] When by import from ifc the "Enable Adavenced mode" nothing happens?

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2359]
So i use this version:
![image](https://user-images.githubusercontent.com/110968398/186462447-9f421748-3927-46d9-bc0f-469f6e642d3b.png)

When i import an ifc without the "Enable Advanced Mode", its works, however if i toggle this "Enable Advanced mode" -> nothing happens

![image](https://user-images.githubusercontent.com/110968398/186461931-30bb0f47-a60c-43f3-bebe-61646e10faac.png)

**Comment by Moult** [comment]
Advanced mode simply preloads the files then offers a series of settings in the Scene Properties > IFC Project panel which allow you to customise how IFCs are loaded. So nothing happening is actually by design (well technically preloading happens, but you won't see any geometry).
