### ISSUE TITLE
[Feature Request] Add a Commandline setting to move Origin to Center of all Bodies

### ISSUE THREAD

**Issue by Mannshoch** [IfcOpenShell/IfcOpenShell#2360]
Converting IFC to STP works fine. But  several application has Problems if the Origin of the STEP is far away.
Please add a command to move all Bodies to the Center of all volume.
```
--origin-to-center    Precalculate the Boundary of all Body and move the Origin to their center 
                      (Needed by some CAD Appliication that could not handle huge Distant to the Origin)
```

I offer to test a compiled ifcConvert.exe

**Comment by Mannshoch** [comment]
A more enhanced idea:
--origin-to-center [option1,option2]     Precalculate the Boundary of all Body and move the Origin to their center 
                      (Needed by some CAD Appliication that could not handle huge Distant to the Origin)
                      [body] center all body
                      [global] center global coordinate to Volume Center of the whole ifcProject

**Comment by aothms** [comment]
Did you see `--center-model` and `--center-model-geometry`?

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcconvert/IfcConvert.cpp#L282-L286

**Comment by Moult** [comment]
There is also an IfcPatch recipe to fix this: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcpatch/ifcpatch/recipes/OffsetObjectPlacements.py which includes custom XYZ translation and also XYZ rotation support. There's also https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcpatch/ifcpatch/recipes/ResetAbsoluteCoordinates.py

**Comment by Mannshoch** [comment]
Yes. But the resulting STEP has still coordinates distances like 
~~~
X 2654717953 mm
~~~

**Comment by Mannshoch** [comment]
OK the solution was --site-local-plcement In help ther is a limit to dae and obj but it seems wok also for stp.

**Comment by Moult** [comment]
> But the resulting STEP has still coordinates distances

How so? What exactly did you try for the patch recipes and how did they fail? These recipes are used very often on projects so I would love to hear if you've found a bug.

> Please update the help.

Would you like to help contribute? You can press edit on any source file on Github and submit a PR :) It would be a great first contribution!

**Comment by Mannshoch** [comment]
My First Edit 😁

What do you mean with receipes? 
I converted with the settings and opened the step in a Viewer where I selected a point and copied one of the measure as an example.

**Comment by Moult** [comment]
I mean using IfcPatch as recommended here: https://github.com/IfcOpenShell/IfcOpenShell/issues/2360#issuecomment-1226426185 - this gives you a lot of control of exactly how you want to offset coordinates.

**Comment by Mannshoch** [comment]
Currently '--site-local-placement' is my solution. I check this Patch if I run into a problem.
