### ISSUE TITLE
BB: Can't add property sets to type object.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2371]
Using [this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/c5027ffce443bf14fd0e8189117fc4a9b9315e53/Random_Tests/Wall_Types/IFC4/from_BlenderBIM/Wall_Types_2.ifc) file, i was not able to add a Pset to the wall type. 
blenderbim-220829-py310-win.zip

![2022-08-29_10-25-57_Blender_blender](https://user-images.githubusercontent.com/507113/187237205-523d1332-d732-4fe6-86dc-7c693f3c8a28.gif)

**Comment by Moult** [comment]
That's because the Types collection was hidden. Fixed now.
