### ISSUE TITLE
Script obj2ifc-meshlab: append is costly method?

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2373]
https://github.com/IfcOpenShell/IfcOpenShell/blob/ffa3aae132301cd32b216b315be1f9f208ef1cb7/src/blenderbim/scripts/obj2ifc-meshlab.py#L49

From [line 44](https://github.com/IfcOpenShell/IfcOpenShell/blob/ffa3aae132301cd32b216b315be1f9f208ef1cb7/src/blenderbim/scripts/obj2ifc-meshlab.py#L44) we can know with `len(faces)` how many faces there will be. 

Can't we because of that do on [line 47](https://github.com/IfcOpenShell/IfcOpenShell/blob/ffa3aae132301cd32b216b315be1f9f208ef1cb7/src/blenderbim/scripts/obj2ifc-meshlab.py#L47) instead of `ifc_faces = []` do `ifc_faces = [0] * len(faces)` or `ifc_faces = np.zeros([len(faces)], dtype=object)`? Would that not be faster?

**Comment by Moult** [comment]
Yes, it would be faster. PR very welcome :)

**Comment by Martin15135215** [comment]
Easy, can do, however with which method, that with numpy module?

**Comment by Moult** [comment]
No preference. I'm not sure which is faster or if there are any side effects to numpy. I currently use the [0] * foo trick in import_ifc.py, but if numpy is faster happy to go for that.

**Comment by aothms** [comment]
My advise would be to use the numpy approach if it's already a dependency
of the script. A numpy array is consecutive data, which means less memory
consumption and generally faster access due to cache lines.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op vr 2 sep. 2022 08:54 schreef Dion Moult ***@***.***>:

**Comment by Martin15135215** [comment]
So did change the script to use numpy -> https://github.com/Martin15135215/git_ifc_test/blob/main/obj2ifc-meshlab.py and https://github.com/Martin15135215/git_ifc_test/blob/main/obj2ifc.py

I tried to do a `git push`, however it failed.
![image](https://user-images.githubusercontent.com/110968398/188169967-1915dc5f-95f2-43f1-93e7-fb7bc001ca8d.png)

**Comment by aothms** [comment]
How this works generally on github is that you "fork" the repository using
the github web interface, push to that (git remote add - might help) and
then again create a "pull request" using the github web interface.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op vr 2 sep. 2022 16:28 schreef Martin15135215 ***@***.***>:

**Comment by Moult** [comment]
@Martin15135215 Github has an excellent guide on the process: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

For simple changes, you can also skip all of that and just press the edit button and edit the code in your web browser and a few clicks later you're done :) https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/scripts/obj2ifc-meshlab.py - just press the "Edit" icon here.

**Comment by Martin15135215** [comment]
#2377 #2376 That did function

**Comment by Moult** [comment]
PRs merged :) Closing!

**Comment by Martin15135215** [comment]
Cool, however what does PR mean?

**Comment by Moult** [comment]
Pull Request
