### ISSUE TITLE
BB: "Curve2D" axis for all walls that use IfcMaterialLayerSetUsage

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2374]
Might be missing something, but is it possible to automatically provide a "Curve2D" axis for all wall instances that use IfcMaterialLayerSetUsage?

If not, is that in the roadmap?  I could be wrong, but it seems required by the schema.

If planned in the roadmap, is it also in the roadmap to automatically update the "Body" if the "Curve2D" axis is changed?  Which would seem ideal, as programmatically it seems easier to 'get at' and modify the "Curve2D" sometimes over the "Body".

**Comment by Moult** [comment]
The axis is already generated for walls, but first you have to have a Model/Axis/GRAPH_VIEW context created. Upon saving your file, axes will be synced. This is not specific to IfcMaterialLayerSetUsage.

![2022-09-04-164644_746x310_scrot](https://user-images.githubusercontent.com/88302/188301092-4b431fbd-5a95-4b63-a8a1-03406fe2fcb3.png)

**Comment by theoryshaw** [comment]
very cool.  Would it make sense to automatically add the Model/Axis/GRAPH_VIEW context when placing a wall type?

Also, when creating a project anew, does it make sense to include this context by default?

**Comment by theoryshaw** [comment]
also, [per the schema](http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcWall.htm), does this curve need to be "Curve2D" and not a "Curve3D"?
_"The wall axis is represented by a two-dimensional open curve within a particular shape representation. "

**Comment by theoryshaw** [comment]
I could be missing something but doesn't seem like the axis is generated. 
video: https://www.dropbox.com/s/gwxtg4eudwsdi6g/2022-09-06_22-56-10_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
I think this is now fixed.
