### ISSUE TITLE
[IfcPatch] Bug in recipe RecycleNonrottedElements

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2375]
https://github.com/IfcOpenShell/IfcOpenShell/blob/af4cb22756ffd44ebb6eeaf5d6a62d22c75973fb/src/ifcpatch/ifcpatch/recipes/RecycleNonRootedElements.py#L34

Change this `if element.is_a('IfcRoot'):` to this `if element.is_a('IfcRoot') or element.is_a('IfcPropertySingleValue'):`
#2377 

When I use the recipe, suddenly all my objects had the same property. But with the new code this did not happen to me.

**Comment by Moult** [comment]
@Martin15135215 can you give a sample file for me to replicate this? In theory IfcPropertySingleValue should not be excluded here.

**Comment by Martin15135215** [comment]
Here is the jupyter notebook to replicate the problem: https://github.com/Martin15135215/git_ifc_test/blob/main/psets_test.ipynb

the code from class ifc is from [here ](https://github.com/IfcOpenShell/IfcOpenShell/blob/ffa3aae132301cd32b216b315be1f9f208ef1cb7/src/blenderbim/scripts/obj2ifc-meshlab.py#L90)

this script creates test_1.ifc and test_2.ifc and there you should see the anomaly

test_1.ifc:
![image](https://user-images.githubusercontent.com/110968398/188306348-0678cc72-9b1c-4c6d-8851-39a4804cef71.png)

test_2.ifc:
![image](https://user-images.githubusercontent.com/110968398/188306366-58e258b0-09b9-49cd-b9e4-44ebbc743d73.png)

Can you replicate this problem with the jupyter notebook?

**Comment by Moult** [comment]
Excellent catch! I had no idea that IfcLabel('foo') and IfcLabel('bar') would produce the same hash. It's been fixed now.

**Comment by aothms** [comment]
> I had no idea that IfcLabel('foo') and IfcLabel('bar') would produce the same hash

Can you explain?

**Comment by Moult** [comment]
```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> x = f.createIfcPropertySingleValue(NominalValue=f.createIfcLabel('foo'))
>>> y = f.createIfcPropertySingleValue(NominalValue=f.createIfcLabel('foo'))
>>> z = f.createIfcPropertySingleValue(NominalValue=f.createIfcLabel('bar'))
>>> hash(tuple(x))
5892372526342220303

>>> hash(tuple(y))
5892372526342220303

>>> hash(tuple(z))
5892372526342220303
```

**Comment by aothms** [comment]
Thanks for clarifying. I think we should generally fix this, see 2378
