### ISSUE TITLE
Question regarding ifc4x3 support

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2382]
so in the [Main Page](https://github.com/IfcOpenShell/IfcOpenShell) its read:

>  Support for parsing is provided for IFC4x1, IFC4x2, and the IFC4x3 release candidates.

so i wanted to test it, with an simple example:

`import ifcopenshell`
`schema = ifcopenshell.ifcopenshell_wrapper.schema_by_name("IFC4x3")`

That throw me this Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Martin\miniforge\miniforge\envs\pyifc\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 5708, in schema_by_name
    return _ifcopenshell_wrapper.schema_by_name(arg1)
RuntimeError: No schema named IFC4x3
```

So what does support for prasing mean?

My goal is to use for exemple IfcBridge instead of IfcBuilding in an ifc file. I am not asking for support for geometry. Only that i can create ifc file with the right entities instead of IfcBuilidingElementProxy and IfcBuildingStorey.

**Comment by Moult** [comment]
The schema identifier is case sensitive, try `IFC4X3`:

```
>>> import ifcopenshell
>>> f = ifcopenshell.file(schema="IFC4X3")
>>> f.createIfcBridge()
#1=IfcBridge($,$,$,$,$,$,$,$,$,$)

>>> schema = ifcopenshell.ifcopenshell_wrapper.schema_by_name('IFC4X3')
declaration_by_name(schema_definition self, int name) -> declaration
>>> schema.declaration_by_name('IfcBridge')
<entity IfcBridge>
```

**Comment by Martin15135215** [comment]
i saw my problem. i downloaded the ifcopenshell module last month from the BlenderBim zip file, like in this video https://www.youtube.com/watch?v=1g_nrGQO9Kc and the "IFCX3" didn't function.

However i saw there is this new conda-forge package https://anaconda.org/conda-forge/ifcopenshell, so now i did download in an new conda env with `conda install -c conda-forge ifcopenshell` and afterwards it did function 😊

Is this with prupose that the blenderbim zip file doesn't have IFCX3?

**Comment by aothms** [comment]
```
>>> print(ifcopenshell.ifcopenshell_wrapper.schema_by_name("ifC2X3"))
<schema IFC2X3>
>>> print(ifcopenshell.file(schema='iFc4'))
<ifcopenshell.file.file object at 0x000002D3ADD0F8E0>
```

So to confirm, schema identifiers in ifopsh are not case sensitive (express is not case sensitive, hence)

IFC4X3 was only finalized March 7th this year and was only recently added to ifopsh. The IFC4X3_rc1 until IFC4X3_rc4 have been available longer (but will be removed at some point from ifopsh)

**Comment by Moult** [comment]
Ah OK good to know :)

Blender uses the ifcopenbot builds, so potentially you were using an old one.
