### ISSUE TITLE
BB: IFC export not working

### ISSUE THREAD

**Issue by marszulc** [IfcOpenShell/IfcOpenShell#2384]
Hello,
thank you for developing such a powerful tool.
I`m getting started to use blender bim and I created very strangely shaped column.
When I try to export IFC I get this error;
![image](https://user-images.githubusercontent.com/110668180/188631825-7fbee0fa-36e6-492b-8a53-f87a14cf35a5.png)
Am I playing too much with geometry?

**Comment by Moult** [comment]
I don't think this is related to the shape, but instead this is a bug that [was fixed on August 2nd](https://github.com/IfcOpenShell/IfcOpenShell/commit/759e134e3bcede883fc0e957ad174b6c4e35d8b4), I think you are running the stable version which is pretty old now (220516).

Can you update to an unstable version and that should fix it: https://blenderbim.org/docs/devs/installation.html#unstable-installation

**Comment by marszulc** [comment]
Thanks for the quick reply. I was sure that version from https://blenderbim.org/ is the latest as it`s described as alpha software.
With the really latest version I can export the IFC file, but it`s empty and I keep getting another error:

![image](https://user-images.githubusercontent.com/110668180/188637999-d9b048dd-7451-4439-be55-4231e19909bd.png)
I have I named the column and it is stored in a named IFC level.

**Comment by Moult** [comment]
Indeed the version n the website is not the truly latest.

How did you create the level? You can't just create a blender collection and empty and name it using the naming convention, that's not how it works. You need to actually create an IFC spatial element.

https://m.youtube.com/watch?v=28g3TO5bBaw might help?

**Comment by marszulc** [comment]
I created an IFC project using Blenderbim, not a plain, renamed collection. Then I dragged the column onto the level.
I have no idea what is wrong with that file but it keeps producing errors when I try to export it:
![image](https://user-images.githubusercontent.com/110668180/188824996-a2678e8a-d951-4f78-8f94-e60017ecba28.png)

Eventually I created a new file and this time it worked.
Then I changed object class from column to pile, assigned the class and exported IFC. I got model with column and pile in the same place (while having one item on the tree).

**Comment by Moult** [comment]
There are so many questions I have, like how come the column in your screenshot has its own collection, what you mean by "that file" - there is no Blender file, there is only an IFC, so if you save a Blender file and reopen it, that Blender file doesn't have any meaning by itself without the connected IFC data. Also how you are changing object class before assigning a class.

Would you be able to drop into the osarch.org/chat live chatroom and do a screenshare session to show me what you're doing? It sounds like there's something fundamentally wrong here, either with the installation or with how you think it should work (in which case maybe I can help improve the UX).

**Comment by marszulc** [comment]
You are right something is wrong with my model (column with its own collection).
As each of my attempts to create simple IFC with one element produces different outcome, I see I need to work on basics and understand it better.
I think this thread can be closed because it`s rather my fault why I can`t export proper IFC.
If I still have problems I`ll contact you via osarch.org/chat live chatroom.
