### ISSUE TITLE
MacBook Pro  macos 12.5.1 (21G83)  Apple M1 install error

### ISSUE THREAD

**Issue by Hiram-Y** [IfcOpenShell/IfcOpenShell#2385]
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/7044188/188633220-26c037a1-da86-4a54-9ed1-c20f2246d605.png">

**Comment by Moult** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/issues/1702#issuecomment-1236222958

**Comment by Moult** [comment]
Sorry for closing your bug so quickly, we'd love to provide these builds but we can't afford the hardware. If you could help chip in a few dollars a month that would really help!
