### ISSUE TITLE
Support in IFC4X3 for IfcAlignment 

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2392]
I know that in [the main page](https://github.com/IfcOpenShell/IfcOpenShell) it's read:

> Extensive geometric support is implemented for the IFC releases [IFC2x3 TC1](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/) and [IFC4 Add2 TC1](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/)

However the IfcAlignment is critical for Horizontal-Assets, because we can do that for exemple:

> IFC Alignment was critical to establish early on in the journey, in order to extend IFC into the infrastructure sector, enabling linear definition of horizontal assets, such as the centreline of a road, the kerbline or rail track. This allows offsets for associated assets to be defined, as not all positioning in infrastructure is carried out using Cartesian (x, y, z) coordinates. For example, an engineer can place street furniture such as a road sign a set distance to the right of the centreline of the road rather than giving the coordinates. Should the road profile move, the sign (and other elements such as lighting and barriers) can subsequently be repositioned according to that offset, and not by calculation of new cartesian coordinates.

Source: [IFC for infrastructure](https://aecmag.com/collaboration/ifc-for-infrastructure/)

What I would like to know, are there any considerations to support this entity yet? If not, what is the difficulty? (time, money etc)

**Comment by aothms** [comment]
We did some rough prototyping in Python a while back

https://github.com/IfcOpenShell/IfcOpenShell/pull/1480/files

We have been busy actually with maintaining 4.3 itself that we don't really have time for the implementation (besides ifopsh I also maintain the publishing platform of 4.3 https://github.com/buildingSMART/IFC4.3.x-development)

Current status of implementation of the geometry functions is that we're looking for some funding in order that we can really prioritize it.

**Comment by Martin15135215** [comment]
Is it possible to add here on this site https://opencollective.com/opensourcebim under Projects something along the line "IFC4.3  support"? And in the description something along the line with better geometry support, BlenderBIM support etc.?

And add also another tier after Corporate Sponsor? With a name for example Gold Corporate Sponsor with 500 USD/month

![image](https://user-images.githubusercontent.com/110968398/193536152-5353396a-5d3a-4a24-a73e-d8b8293ace9b.png)

I will talk about it with my company soon. Therefore, more options are better than few. But I can't promise anything here if my company can support you.

**Comment by Moult** [comment]
@aothms what do you think? :) Bronze Corporate: 100, Silver Corporate: 250, Gold Corporate: 500, Platinum: 1000 Diamond 10,000 Unobtanium 1,000,000,000 ?

**Comment by aothms** [comment]
@Martin15135215 actually @Moult and I discussed that it'd be better to reduce the amount of specific project funding and rather strive for more continuity. From 100/m I think it's probably better not to think in donations, but rather offer something in return in terms of prioritized support and somebody who picks up the phone. For that to be successful I think we need to invest a lot more first in boring work in increasing the breadth (more languages) and depth (much better docs and release workflows aimed at devs) of developer support.

**Comment by dirkolbrich** [comment]
Can be closed due to commit https://github.com/IfcOpenShell/IfcOpenShell/commit/6026e037fac45431737467f73596e4bc3fc80c61?

**Comment by aothms** [comment]
This issue goes all over the place. Alignment geometry support will come, I don't think its necessary to keep an issue open for it.
