### ISSUE TITLE
BlenderBIM doesn't have IFC4X3 schema

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2398]
So today i downloaded the newest BlenderBIM addon from here: https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-220909
![image](https://user-images.githubusercontent.com/110968398/189399909-3e8e1b73-e604-412f-9262-bbb977e5f3ac.png)

And when i try to create an new ifc file, there is only the option for IFC4 and IFC2X3:
![image](https://user-images.githubusercontent.com/110968398/189399665-3aa36998-ffb8-48a4-bed5-1fbec3629492.png)

However i know from here https://github.com/IfcOpenShell/IfcOpenShell/issues/2382 that parsing IFC4X3 is possible.

Is it possible to add IFC4X3 to BlenderBIM?

**Comment by Moult** [comment]
Sure I can, but not much use without geometry support? :)

**Comment by aothms** [comment]
Well, users could benefit from the added semantics surely?

**Comment by Martin15135215** [comment]
Thanks for the update!

Till IFC4, there were not any semantics for infrastructure. So this is for me a huge help, to create IfcBridge instead of IfcBuilding:

![image](https://user-images.githubusercontent.com/110968398/189545226-dca78719-fc65-42fb-80b0-0de763892379.png)


However i think the list for classes under the product IfcElement is quite big now:

![image](https://user-images.githubusercontent.com/110968398/189545345-a620d9ca-e8bb-4ace-8da9-cc6e34696267.png)
