### ISSUE TITLE
Blenderbim associate blender with IFC files

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2399]
Currently, to open an IFC file, I have to launch blender, delete the default cube, then either use the Import menu or use Scene Properties -> Load Project.

It would be nice to double-click an IFC file in a file manager and have the file IFC open directly.

There is a blender --python-expr command-line option that will run any provided code. So it should be possible to create a wrapper that, given an IFC path, launches blender with an empty scene, and that loads the file, all in one go.

**Comment by aothms** [comment]
Second this.

I've done something similar for Collada and OBJ in the past. Write a little script with `blender -P /usr/opt/blender_import.py $%` and have that script take care of connecting the right operator to the file(s) based on extension.

**Comment by brunopostle** [comment]
Here's a one-liner that loads an IFC file in blenderbim:

    blender --python-expr 'import bpy; bpy.ops.bim.load_project(filepath="/full/path/to/myfile.ifc")'

**Comment by Moult** [comment]
This is great, but  how should we distribute these? Bat files? Sh files? Write a docs page showing people how to edit the blender path?

**Comment by aothms** [comment]
I think this may fit in with the whole Blender Application Templates. Once we have that and a dedicated installer, it makes a lot of sense to have something to associate the extension with directly. For now it's probably ok to document something for users to conveniently tweak.

**Comment by Moult** [comment]
Hmm I tried playing with application templates and it works but basically to distribute it neatly for others you'd want to rebundle the entire Blender package. It's a bit heavy, though I've done it for coworkers.

Maybe the instructions could be as simple as "copy this sh/bat to the blender install dir", since then the Blender executable should be in the cwd.

**Comment by brunopostle** [comment]
> This is great, but how should we distribute these? Bat files? Sh files? Write a docs page showing people how to edit the blender path?

When blenderbim is first run it ahould be able to figure-out the blender executable location. It could then generate a blenderbim.bat or a blenderbim.sh file. But the user would then have to manually associate this with IFC files.

My rpm package installs blenderbim as a system application, so I could install a .desktop file, icon, mime association and all that stuff. But this won't help everyone else who doesn't use fedora.

**Comment by brunopostle** [comment]
So... I have all this working on fedora, files here: [blenderbim-desktop.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9543595/blenderbim-desktop.zip)

The `blenderbim.sh` wrapper script launches blender. If it is given a path to an IFC file it opens that in blenderbim, but with no argument it launches blender with an empty IFC project.

The other files are needed to create a file/mime association and icon for IFC files, and a desktop application icon for blenderbim. On my system I can now just double-click an IFC file:

![image](https://user-images.githubusercontent.com/1747315/189550684-e4be1cb6-a1a4-4376-8a8d-3815395731be.png)

Most of this stuff isn't going to work for a user who has downloaded blender and blenderbim rather than installing them through a package manager, particularly if your blender isn't in your `$PATH`, but maybe they will be useful to somebody.

**Comment by brunopostle** [comment]
The `blenderbim.sh` wrapper wasn't quoting special characters properly, fixed version:

```
#!/bin/sh
if [[ $# -eq 1 && -f "$@" ]]; then
    blender --python-expr 'import bpy; bpy.data.collections.remove(bpy.data.collections[0]); bpy.ops.bim.load_project(filepath="'"$@"'")'
else
    blender --python-expr 'import bpy; bpy.data.collections.remove(bpy.data.collections[0]); bpy.ops.bim.create_project()'
fi;
```

To install these files manually as a local user on linux, it should be enough to do this (you may have to create these folders if they don't exist):

```
cp blenderbim.sh ~/bin/
cp blenderbim.png ~/.local/share/icons/hicolor/128x128/apps/
cp blenderbim.desktop ~/.local/share/applications/
cp blenderbim.xml ~/.local/share/mime/packages/
cp x-ifc_128x128.png ~/.local/share/icons/hicolor/128x128/mimetypes/x-ifc.png

update-mime-database ~/.local/share/mime/
update-desktop-database
```

**Comment by Moult** [comment]
This is really neat! @brunopostle is it possible to ask for a PR? Maybe a new section here https://blenderbim.org/docs/users/installation.html might help?

**Comment by aothms** [comment]
Yes, seconded, this looks really cool. @fbpyr maybe something like this for windows is easy with choco?

**Comment by brunopostle** [comment]
> This is really neat! @brunopostle is it possible to ask for a PR?

Sure where do you want this stuff? Somewhere like `src/blenderbim/desktop/` ?

> Maybe a new section here https://blenderbim.org/docs/users/installation.html might help?

I'll see if I can automate it a bit for Linux users with a Makefile, then see if anyone can get it to work, then write some docs

**Comment by fbpyr** [comment]
directly opening ifc? very nice! 🙂 
@aothms distribution of the mechanism could definitly be added with choco. 
(though I would not know how that .bat mechanism would look like, 
as I use horrible user-disrespecting-win only when I have to.)

settings the association as default, I am a little sceptical about 🤔 : 
**surely I** like blenderbim as ifc default, but maybe other users prefer their current setting?
I surely quite dislike when on my work machine e.g. excel steals my .xlsx association from libreoffice.

what about a first-run-welcome script in blenderbim, that asks the user if the association should be made?

**Comment by aothms** [comment]
> what about a first-run-welcome script in blenderbim, that asks the user if the association should be made?

I like that approach. It could do the .bat/.sh and icon creation in a (for the user) platform agnostic way. I agree it's also less user hostile than hijacking the system without asking (I assumed we could use some choco setting, but your approach would work regardless of installation mechanism).

> I'll see if I can automate it a bit for Linux users with a Makefile

@brunopostle would you consider using Python instead of Makefile so that we can run this from within bbim?

**Comment by fbpyr** [comment]
@aothms @brunopostle  writing the setup script in python would also help with using it similarly cross plattform. 🙂

**Comment by fbpyr** [comment]
@aothms completely agree on being user friendly & asking - choco is a 'no-questions-asked-install-it' mechanism though. 
(which is very nice in its own way, most of the time) so if the tooling for file association convenience could be optionally run 
from within bb, that would also circumvent this 'clash of mindsets'.

**Comment by Moult** [comment]
I dislike the "hey make us your default app" prompts and find them very needy :) More than happy to sneak a button in the add-on preferences dialog though and write about it in the docs.

**Comment by brunopostle** [comment]
I have a nice working Makefile, so I'll include this in the PR because I need some feedback that I have the correct installation locations for all systems.

A hook that does this configuration/file-copying on installation of blenderbim would be ideal, and it does need to be python rather than make. We need a foolproof way of locating the full path of the blender executable from within a blender session.

**Comment by Moult** [comment]
`bpy.app.binary_path`

**Comment by cadgiru** [comment]
@brunopostle On startup file... "....launch blender, delete the default cube, then ....." .... maybe not correct place, but U can have [any file of Your choosing configured as startupfile](https://docs.blender.org/manual/en/latest/getting_started/configuration/defaults.html)

**Comment by brunopostle** [comment]
@cadgiru the current code deletes the first collection before importing the IFC. This will fail if there is no collection at all in the startup file, but most likely startup files will have a collection (this might prove to be a bad assumption, in which case we need some cleverer code).

**Comment by Moult** [comment]
This is how the testcases get a fresh session: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/test/bim/test_feature.py#L56-L63

**Comment by brunopostle** [comment]
> This is how the testcases get a fresh session: 

I'm not sure how we can stuff all this into the one-liner that we give to blender

**Comment by brunopostle** [comment]
It always feels a bit weird that the scene isn't cleared on Load Project, I understand why it would should be retained on Create Project.

Maybe also a top-level menu item under File -> New -> IFC Project would clear the scene and create an IFC project

**Comment by brunopostle** [comment]
Attached, python methods to install and uninstall this file association and launcher icon for linux. I really don't know where to put this in the code or how to hook it into the blenderbim preferences: [file_association.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9583554/file_association.txt)

**Comment by Moult** [comment]
Create a new Operator class here for each button (so you'd need two?): https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/operator.py

Then add your operators to the class list in this init here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/__init__.py#L83

The bl_idname of the class is the Blender identifier, which you can use to add a button in the preferences dialog in the UI file here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/ui.py#L123

**Comment by CyrilWaechter** [comment]
I just discover this issue. I saw all the desktop stuff in source code and added support for `.ifczip` and `.ifcxml` in https://github.com/IfcOpenShell/IfcOpenShell/commit/e5c920864c6e65073b6cc5a5109a1708ec68f8ae. I hope its ok.

By the way this is great to be able to double click on ifcfiles to open it and have ifc icon on gnu/linux ! Thanks @brunopostle

**Comment by brunopostle** [comment]
@CyrilWaechter thanks! Though this is unfinished, the code needs adding to the blenderbim preferences as described above. I think I now have a better understanding of how to do this than I did before, but would be happy for someone else to get it done first.

**Comment by brunopostle** [comment]
I committed a couple of buttons in the preferences to create/remove a blenderbim desktop icon and *.ifc file association. Linux only for now, but it should be easy enough to do the same for Windows.

**Comment by Moult** [comment]
Closing as this is now implemented on Windows too.
