### ISSUE TITLE
SVG serializer match group id to entity id

### ISSUE THREAD

**Issue by Xperi0n** [IfcOpenShell/IfcOpenShell#24]
Hi,
I've been playing a bit with the IfcConverter in order to generate SVG files, but I didn't find how I can link a group that represents a wall to the IFCWALL from the .IFC file.

From what I can seen the id inside the svg are structured like ```product-product-xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-body ``` whereas in the source file I got xxxxxxxxxxxxxxx.

How can I keep the link between the source and the output ?

Thx

**Comment by Stinkfist0** [comment]
See discussion in https://github.com/IfcOpenShell/IfcOpenShell/issues/18
The --use-guides feature is coming at some point, but cannot make any promises about the exact date for now.

**Comment by aothms** [comment]
The IFC files use a compressed globally unique identifier [1]. That page contains code to convert between the uncompressed rfc4122 guid used in IfcConvert output. There is also a Python code available [2].

[1] http://www.buildingsmart-tech.org/implementation/get-started/ifc-guid
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcopenshell-python/ifcopenshell/guid.py#L32

Hope that helps,

Kind regards,
Thomas
