### ISSUE TITLE
Installation not showing in properties

### ISSUE THREAD

**Issue by GeminiWoods2021** [IfcOpenShell/IfcOpenShell#2403]
Familiar with Blender but followed all the instructions for install on Windows 11, Blender 3.1 and tried Blender 3.3 .. same result
No error messages but only see a limited dropdown
![image](https://user-images.githubusercontent.com/112692285/189621516-01d4ab51-669f-4892-98b1-b4eab7f4acdd.png)
![image](https://user-images.githubusercontent.com/112692285/189621584-5cdd7876-d839-4b98-bc5c-76d6be62ae81.png)

**Comment by Moult** [comment]
@GeminiWoods2021 I saw you dropped into the live chat, did you solve it? You need to look in the scene properties. https://blenderbim.org/docs/users/exploring_an_ifc_model.html may help

**Comment by Moult** [comment]
Closing as not actually a bug :)

**Comment by GeminiWoods2021** [comment]
Yes definitely a wetwear problem, thank you for helping

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
