### ISSUE TITLE
RunTimeError : Failed to process shape

### ISSUE THREAD

**Issue by websterhasnoheart** [IfcOpenShell/IfcOpenShell#2404]
[extracted_code.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9549064/extracted_code.zip)

Hey there,  with the following code I get a RunTimeError: failed to process shape
```
def calculate_length(instance):
    shape = geom.create_shape(geom_settings, instance).geometry
    edge_explorer = TopExp_Explorer(shape, TopAbs_EDGE)
    edges = []
    while edge_explorer.More():
        current_edge = topods_Edge(edge_explorer.Current())
        props = GProp_GProps()
        brepgprop_LinearProperties(current_edge, props)
        edges.append(props.Mass())
        edge_explorer.Next()
    return max(edges)
```
Because the ifcopenshell is unable to process the instance we provided
You can find the related ifc file in the attatched zip files
the config setting is ifcopenshell-python-38-v0.7.0-e44e03f.

**Comment by Moult** [comment]
It works for me. Your shape is a 2D plan representation. Have you done geom_settings.set(geom_settings.INCLUDE_CURVES, True)?

**Comment by websterhasnoheart** [comment]
> 

Thank you so much for your reponse, and is there any way we can exclude this 2D plan representation while running the program?

**Comment by Moult** [comment]
Sure, instead of calling create shape manually,use the geom.iterator loop and disable include curves.

**Comment by websterhasnoheart** [comment]
> Sure, instead of calling create shape manually,use the geom.iterator loop and disable include curves.

Thanks, but geom.iterator requires the ifc file as one of the input, we do not prefer that way, is there a way we can filter out all 2D representation in the begining of the program and exclude(skip) them when we are about to run into them?

**Comment by Moult** [comment]
@websterhasnoheart what's wrong with the IFC file as one of the inputs? The geom iterator has lots of benefits like multicore, easy context_id filtering, include/exclude filter, and so on.

If you really want to check, for each element you can explicitly choose which representation you want, like `if ifcopenshell.util.representation.get_representation("Model", "Body", "MODEL_VIEW"): geom.create_shape(element)`.

**Comment by websterhasnoheart** [comment]
> @websterhasnoheart what's wrong with the IFC file as one of the inputs? The geom iterator has lots of benefits like multicore, easy context_id filtering, include/exclude filter, and so on.
> 
> If you really want to check, for each element you can explicitly choose which representation you want, like `if ifcopenshell.util.representation.get_representation("Model", "Body", "MODEL_VIEW"): geom.create_shape(element)`.

Thank you so much, this has been really helpful and I learned a lot from you. Last question, how do you know my shape is a 2D representation in the first place? How does IFC specify 2D representation shapes?

**Comment by Moult** [comment]
I guess there's two concepts here, whether your shape is 2D or 3D (i.e. xy only vs xyz coordinates) and whether your shape contains faces/surfaces or is just a curve/line/polyline/arc/etc. For example, you can have a 3D line.

Any representations that are part of "Model" are 3D, and any representations that are part of "Plan" are 2D. As for whether it contains faces, the Model Body representation is required to contain faces, so that's an easy way to check, but you may also check the RepresentationType for a more granular breakdown.
