### ISSUE TITLE
[BlenderBIM] Why is ["DEMOLITION", "DISMANTLE", "DISPOSAL", "REMOVAL"] in the function animate_output?

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2409]
https://github.com/IfcOpenShell/IfcOpenShell/blob/79bb40092f80f4413e0002a293db92019a17f77a/src/blenderbim/blenderbim/bim/module/sequence/operator.py#L1157-L1167

So @Moult did explain me [here ](https://community.osarch.org/discussion/1131/ifcopenshell-python-ifctask-predefinedtype-construction-demolition-move#latest) about the "ICOM" model that the IfcTask generically follows.

![image](https://user-images.githubusercontent.com/110968398/190156253-1e65ec84-6fa5-4b15-92a1-c79926ed240c.png)

So why is ligne1160 with `elif product_frame["type"] in ["DEMOLITION", "DISMANTLE", "DISPOSAL", "REMOVAL"]:` in the function `animate_output(self, obj, product_frame):` instead of in the function `animate_input(self, obj, product_frame):` ?

**Comment by Moult** [comment]
Because it's "in theory" meant to be an input, but the IFC docs do not (yet?) explicitly make this clear. It is an ambiguity yet to be resolved with buildingSMART.

I'm happy to take the initiative and add it to the animate_input though, would you like to help contribute?
