### ISSUE TITLE
Python tests failing

### ISSUE THREAD

**Issue by ysangkok** [IfcOpenShell/IfcOpenShell#241]
```
~/IfcOpenShell/test$ python3 tests.py
unhandled exception while getting id / type info on #22=IfcPerson('123','','',('John','Matthew'),$,$,$,$)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ifcopenshell/entity_instance.py", line 129, in get_info
    _info["id"] = self.id()
  File "/usr/lib/python3/dist-packages/ifcopenshell/entity_instance.py", line 110, in id
    return self.wrapped_data.id()
  File "/usr/lib/python3/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 1300, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, entity_instance, name)
  File "/usr/lib/python3/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'entity_instance' object has no attribute 'id'
```

It seems like entity_instance has no attributes anymore.

I am building with `cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ -DOPENCOLLADA_INCLUDE_DIR="/usr/local/include/opencollada" -DOPENCOLLADA_LIBRARY_DIR="/usr/local/lib/opencollada" -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ -DCMAKE_BUILD_TYPE=Release -DCOLLADA_SUPPORT=0`

**Comment by aothms** [comment]
It works on py2 [1]. Not sure what could be the deal with py3 for this to fail. Maybe `id` is a reserved word somehow?

[1] https://travis-ci.org/IfcOpenShell/IfcOpenShell/builds/249738121#L2039

**Comment by ysangkok** [comment]
On Python 2 I have another issue:
```
~/IfcOpenShell/test$ python tests.py
No handlers could be found for logger "ifcopenshell.entity_instance"
```

**Comment by aothms** [comment]
> No handlers could be found for logger "ifcopenshell.entity_instance"

I saw that, but thought it was harmless. Apparently it's the same issue, just silenced by the default logging config, which apparently is different between py2 and py3. Thanks for reporting.
