### ISSUE TITLE
BlenderBim -220916 - Millimetres breaks ifc4 libraries

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2416]
File does not load library elements correctly when specifying mm as project units

Loading 200mm wall with project units set to metres: (correct)

![image](https://user-images.githubusercontent.com/78321676/190659798-9e1b1243-ae30-4196-8ba0-e46958d1b136.png)

Loading 200mm wall with project units set to milimetres: (wrong)

![image](https://user-images.githubusercontent.com/78321676/190659438-19b91855-d7e7-4935-ac54-458a7d17915a.png)

This was working until BlenderBim -220916

**Comment by Moult** [comment]
Apologies, in the middle of switching to a new wall engine.

**Comment by Plae-Blue-Dot** [comment]
Using Blenderbim 20220920

Library does not display Ifc library element correctly

![image](https://user-images.githubusercontent.com/78321676/191205164-0d97f6b7-4051-44d8-b5fd-895ec3f3b45a.png)

and once loaded the wall seems to be massive

![image](https://user-images.githubusercontent.com/78321676/191205487-6235753c-f1f1-4b98-bda8-069de69717ad.png)

**Comment by Moult** [comment]
Whoops!

**Comment by Moult** [comment]
I think this is now fixed.

**Comment by Plae-Blue-Dot** [comment]
Funny you should close it now... :D
In the latest release blenderbim-221018

Creating an opening using metres:
![image](https://user-images.githubusercontent.com/78321676/196498347-36162271-a8dc-4ac1-b668-27085f9986ef.png)



Creating an opening using milimetres
![image](https://user-images.githubusercontent.com/78321676/196498499-f25d9ec2-5fd5-41f4-88c9-7239f3a714bc.png)
the wall is in the middle there

![image](https://user-images.githubusercontent.com/78321676/196498554-29aea693-aca0-46f0-b095-a071eed87cc3.png)
The cube opening is so big it's clipping the view.

How can I reopen it? :D

**Comment by Moult** [comment]
Cheers, was an issue in the new "default dimensions" feature which uses project units.
