### ISSUE TITLE
error while saving ifc file

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#2417]
I am getting this error while trying to save the ifc file. How do i resolve this

`Python: Traceback (most recent call last):
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/module/project/operator.py", line 733, in invoke
    return self.execute(context)
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/module/project/operator.py", line 741, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/ifc.py", line 369, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/module/project/operator.py", line 768, in _execute
    ifc_exporter.export()
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/export_ifc.py", line 49, in export
    self.sync_all_objects()
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/bim/export_ifc.py", line 111, in sync_all_objects
    tool.Collector.sync(obj)
  File "/home/arun/.config/blender/3.3/scripts/addons/blenderbim/tool/collector.py", line 32, in sync
    if element.is_a("IfcProject") or element.is_a("IfcGridAxis"):
AttributeError: 'NoneType' object has no attribute 'is_a'
`

**Comment by Moult** [comment]
@arunkvijay it's trying to find a IFC element that used to exist in your model, but no longer does. This means Blender and IFC are no longer in sync. What steps exactly are you doing?

**Comment by arunkvijay** [comment]
i guess its a bug. This is happening when an Ifc project is created using IFC4 Demo Library Template. No error happens when creating the Ifc Project with Blank Project (as template)

i have mentioned steps below
- opened an existing blender file
- created an Ifc Project with IFC4 Demo Library Template
- saved the project (exported as ifc)
- saving the project again throws this error

**Comment by Moult** [comment]
Does that existing Blender model have objects that were from another IFC model? If so, that would be the cause. One Blender model is a snapshot of a one IFC model only. You can't mix multiple IFC projects in a single Blender file.

**Comment by arunkvijay** [comment]
Tried with another existing blender model as well. Same issue. 
And both these blender models dont have any ifc elements pre-existing.
Also, both these existing blender models didnt throw any error when Blank Project Template is used.

**Comment by Moult** [comment]
I just tested and could not recreate the issue.

1. Create fresh Blend file, duplicate the default cube a few random times.
2. Save blend file as untitled.blend
3. Close and reopen Blender, and load untitled.blend
4. Press Create project with the demo library
5. Press Save Project to save an IFC.
6. No error

Are you using the latest unstable version from here? https://blenderbim.org/docs/devs/installation.html#unstable-installation (not the one from the blenderbim.org website which is a few months old)

**Comment by arunkvijay** [comment]
I have checked with today's latest release of 0.0.220918 and have checked on creating a new blender file with default cubes duplicated a couple of times. And this has no problem.
Issue is only with older blender files created a couple of months back with more complex geometry, lights, ... Issue still exists even with the latest blenderbim release. May be its an issue with the existing blender files I guess and not blenderbim. Also, if I delete the IfcProject/My Project Collection (Right click and Delete Hierarchy) and again Create Project, then the issue is not repeated.
