### ISSUE TITLE
BBIM issue loading materials

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#2418]
Scenario: Add material
    Given an empty IFC project
    And I add a cube
    And the object "Cube" is selected
    And I set "scene.BIMRootProperties.ifc_class" to "IfcWall"
    And I add a material
    When I press "bim.add_material(obj='Material')"
    And I save my file.
    And I close my file.
    When I load my file,
    **Unfortunately** : the object material panel doesn't load the assigned material
    
Scenario2: Add material
    Given an empty IFC project
    And I add a cube
    And the object "Cube" is selected
    And I set "scene.BIMRootProperties.ifc_class" to "IfcWall"
    And I add a material
    When I press "bim.add_material(obj='Material')"
    When I press"bim.add_style"
    And I save my file.
    And I close my file.
    When I load my file,
    **Then happy days**

**Comment by theoryshaw** [comment]
I think you may have to apply the IfcMaterial via 'IFC Object Material' in the Object Properties...
https://www.dropbox.com/s/e3gtpve0ql6xtg0/2022-09-21_14-58-19_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
Agreed, it doesn't seem like a bug to me, adding a material doesn't actually assign a material. @myoualid can you screenshare?

**Comment by theoryshaw** [comment]
> can we move the object material panel to the Material's tab rather than the Object Properties? It makes a bit more sense that bit of info in the same area.

agree. 
might address it: https://github.com/IfcOpenShell/IfcOpenShell/pull/2492/commits/556dc709704d6998a1660c2cdfd7a6fc9b180562

**Comment by Moult** [comment]
Reverting since this causes breakages when dealing with non-geometric parametric materials like wall type empties, slab type empties, etc, so I guess it wasn't a good idea to move it to the materials tab.
