### ISSUE TITLE
Blenderbim - no longer seems to be a windows release, last one being 20220916

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2421]
On the releases page the windows version is no longer present:

https://github.com/IfcOpenShell/IfcOpenShell/releases

The last one with a windows release was Blenderbim - 20220916

If this is not the correct place for this kind of query let me know

**Comment by Moult** [comment]
Thanks so much! I completely missed that.
