### ISSUE TITLE
BlenderBim - 20220919 - Error when attempting to activate addon

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2422]
Following the normal process for updating version of BlenderBim, (deactivate, restart, uninstall, install new version, activate new version) when attempting to activate the addon with the checkbox this error appears:

![image](https://user-images.githubusercontent.com/78321676/190976689-e92c5c70-2a11-481f-ba82-0b0420c4faab.png)

**Comment by Moult** [comment]
This is a bit of a tricky one since the error you've screenshotted isn't the actual error. I've given it a shot and please try with the next build after that commit. When testing, make sure the Blender config folder (e.g. 3.3) is fresh just in case there are any stragglers from an old install.

**Comment by Plae-Blue-Dot** [comment]
Thanks @Moult I've just tried to create a completely new install, going to try with the latest build

**Comment by Plae-Blue-Dot** [comment]
It seems to work! no more error and I suppose the clean install got rid of my delete problem aswell. Thanks @Moult !

The new install has a number of issues with millimeters and materials, should I open those as separate issues? Or should I wait a bit until the transition to the new wall engine is bit more complete?

**Comment by Moult** [comment]
Yes, please do report them as bugs, perhaps just reuse this issue I've just reopened since it is a bit of a WIP, but every bugreport helps save dev time so it's incredibly valuable :) https://github.com/IfcOpenShell/IfcOpenShell/issues/2416

**Comment by Plae-Blue-Dot** [comment]
Got it I'll keep posting
