### ISSUE TITLE
[api] project.append_asset duplicates Material Properties and Material Definition Representation

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2424]
If I copy a Material from one file to another, I end up with a single Material but duplicated Material Properties and Material Definition Representation entities in the new file:

    #15=IFCMATERIALPROPERTIES('Pset_MaterialCommon',$,(#16),#14);
    #17=IFCMATERIALPROPERTIES('Pset_MaterialEnergy',$,(#18),#14);
    #19=IFCMATERIALDEFINITIONREPRESENTATION($,$,(#30),#14);
    #31=IFCMATERIALPROPERTIES('Pset_MaterialCommon',$,(#16),#14);
    #32=IFCMATERIALPROPERTIES('Pset_MaterialEnergy',$,(#18),#14);
    #33=IFCMATERIALDEFINITIONREPRESENTATION($,$,(#30),#14);

Attached a test file [one-material.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9602489/one-material.ifc.txt) with a single material.

This script [one-material.py.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9602490/one-material.py.txt)  copies the material to a new file where the entities are duplicated.

**Comment by brunopostle** [comment]
Another aspect of this bug which the test script illustrates: project.append_asset() removes the WorldCoordinateSystem attribute from the Geometric Representation Context in the destination file, failing validation. i.e. this line:

    #12=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#11,$);

..becomes:

    #12=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,$,$);

**Comment by brunopostle** [comment]
These bugs seem to be fixed since a34c0cb

**Comment by brunopostle** [comment]
Reopening. This bug is fixed when importing a single material from a library, but still exists when importing a wall type that has a material.

If I import the wall type from this example library into blenderbim  
[simple_library.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9997417/simple_library.ifc.txt) then I end up with duplicated Material Properties and Material Definition Representation entities

**Comment by Moult** [comment]
@brunopostle I don't think this is a bug since your library invalidly contains two material relationships to the wall type. The wall type has both a material layer set (good) and a material layer set usage (bad). If I delete these two lines it works as expected:

```
#86=IFCRELASSOCIATESMATERIAL('2IkddmjpjFKO$aamv5NdQt',$,$,$,(#65),#87);
#87=IFCMATERIALLAYERSETUSAGE(#69,.AXIS2.,.POSITIVE.,-0.254,$);
```

**Comment by brunopostle** [comment]
I'll investigate some more and produce another test case as I'm still seeing these duplicates and I already purged all these IfcMaterialLayerSetUsage entities from my libraries:

```
For instance:
    #588=IfcMaterial('Timber',$,$)
With inverse:
    HasRepresentation : SET [0:1] OF IfcMaterialDefinitionRepresentation FOR RepresentedMaterial
Value:
    [
      1. #589=IfcMaterialDefinitionRepresentation($,$,(#594),#588)
      2. #1166=IfcMaterialDefinitionRepresentation($,$,(#594),#588)
    ]
Not valid

**Comment by brunopostle** [comment]
I can reproduce this.

The attached library [two-types.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10819349/two-types.ifc.txt) contains a Wall Type and a Roof Type, both of these types have layersets, both layersets share a material 'Plaster'.

1. in blenderbim create a new ifc4 project
2. load the attached IFC as a library
3. import the Roof Type and the Wall Type
4. save the project
5. the project has duplicated IfcMaterialDefinitionRepresentation entities:

```
$ python -m ifcopenshell.validate test.ifc 
Validating test.ifc
For instance:
    #66=IfcMaterial('Plaster',$,$)
With inverse:
    HasRepresentation : SET [0:1] OF IfcMaterialDefinitionRepresentation FOR RepresentedMaterial
Value:
    [
      1. #73=IfcMaterialDefinitionRepresentation($,$,(#84),#66)
      2. #115=IfcMaterialDefinitionRepresentation($,$,(#84),#66)
    ]
Not valid
