### ISSUE TITLE
Geometry bug when changing IFC Construction Type

### ISSUE THREAD

**Issue by lfcastel** [IfcOpenShell/IfcOpenShell#2425]
Picture 1: original situation
![image](https://user-images.githubusercontent.com/73949503/191186568-28e4ef48-6359-4b1e-8b93-d18de0e345e3.png)
Then i change the IFC Construction Type and this happens:
![image](https://user-images.githubusercontent.com/73949503/191186833-e2b29e17-4b86-4938-97ba-d597540594b1.png)
It adds 'random' geometry to the object which i have assigned a different contstruction type...

**Comment by Moult** [comment]
Can you share your file? It is likely the covering has a parametric thickness, and switching types has changed the thickness, and so it is trying to recreate the shape and failing. There is currently work happening over the past week or so to switch to a much more robust shape generation system for wall-like things, and slab-like things (like your covering) is next in queue.

**Comment by lfcastel** [comment]
Not sure if you meant the .blend or .ifc file but here is the ifc: https://we.tl/t-51hw2V6xWm. Let me know if you meant the .blend.
Nice to hear that there is work being done on it.

Thanks

**Comment by Moult** [comment]
The IFC is sufficient. Can you provide the exact object ID that you edited, as well as what construction type you changed it to? I just tested with 18Tr$5r6b7YhBzF1OkevZ0 and changed it to a construction type of Floor:isolation - isolatie PUR 14cm and it works fine here.

**Comment by lfcastel** [comment]
https://www.loom.com/share/274dcd0687db40389c8e36741e084a58

The ID was in fact: 18Tr$5r6b7YhBzF1OkevZ0 and i also changed it to Floor:isolation - islatie PUR 14cm as you see (there are two of these though and for me it goes wrong with both of them.

**Comment by Moult** [comment]
I still can't recreate it. Are you using the stable version from blenderbim.org or the unstable version from Github? If you're using the stable one, can you try switch to the unstable one which is more recent? https://blenderbim.org/docs/devs/installation.html#unstable-installation

**Comment by lfcastel** [comment]
I was running the stable version, it works fine with the latest unstable version that i just installed. Seems that the bug is fixed!

**Comment by Moult** [comment]
Cheers, there's still an upgrade due to for layered slab-like things, so expect more commits and stuff to come in the coming weeks!
