### ISSUE TITLE
Blenderbim20220920 material hatch pattern not showing when wall is split

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2426]
Solid wall 

in model:
![image](https://user-images.githubusercontent.com/78321676/191206713-a8b9105e-f1c6-4652-a012-b198db729173.png)

svg:
![image](https://user-images.githubusercontent.com/78321676/191206677-5efa228b-22c7-4bb6-ae5c-9824528c2627.png)

split wall

in model:
![image](https://user-images.githubusercontent.com/78321676/191206908-2ec71674-1b1b-4b92-8e72-8d1e449a4894.png)

svg:
![image](https://user-images.githubusercontent.com/78321676/191206951-d9c5221d-5cc2-4f9b-9f28-b852612d936b.png)

Split wall part still retains the same IfcMaterial settings et al

![image](https://user-images.githubusercontent.com/78321676/191207108-7e293da5-2b36-46b0-b080-027a13432154.png)

**Comment by theoryshaw** [comment]
was able to reproduce as well. Just to note, if you save, close, and open again, the hatch shows up.  A cache problem?... not sure.

**Comment by Plae-Blue-Dot** [comment]
@theoryshaw I had the same, it reloads with the material applied, 

the split wall without the material seems to be initially missing the camera property set /EPsetDrawing

Wall with material:
![image](https://user-images.githubusercontent.com/78321676/192210237-79c737ef-1f75-4360-8478-ecd4fa151c4e.png)

Wall with just black cut:
![image](https://user-images.githubusercontent.com/78321676/192210512-a95b56c5-c910-4fb2-9fb1-2ba77710937d.png)
