### ISSUE TITLE
Error: Argument is not a list of entity instances

### ISSUE THREAD

**Issue by theRealSuperMario** [IfcOpenShell/IfcOpenShell#2429]
I am getting this error

```
[Error] [2022-09-21 14:01:17] gp_Dir() - input vector has zero norm
#101447=IfcBuildingElementProxy('25jxLMtWzAnfNCalAspOcs',#7,'CL1','',$,#101448,#101453,$,.NOTDEFINED.)
[Error] [2022-09-21 14:01:17] Argument is not a list of entity instances
```

I tested with multiple viewers, and some are working. IfcConvert breaks though.

Tried with:
- `IfcConvert-v0.7.0-4199016-macos64.zip`
- `IfcConvert-v0.7.0-4fb910f-macos64.zip`

Model is attached

[model.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9616325/model.ifc.zip)

any help is appreciated.

**Comment by aothms** [comment]
> Argument is not a list of entity instances

My guess is, relates to (`python -m ifcopenshell.validate` output):

```
For instance:
    #38467=IfcClosedShell($)
                          ^
With attribute:
    <attribute CfsFaces: <set [1:?] of <entity IfcFace>>>
Not optional
```

> input vector has zero norm

My guess is, relates to

```
#101447= IFCBUILDINGELEMENTPROXY('25jxLMtWzAnfNCalAspOcs',#7,'CL1','',$,#101448,#101453,$,.NOTDEFINED.);
#101448= IFCLOCALPLACEMENT(#115,#101449);
#101449= IFCAXIS2PLACEMENT3D(#101450,#101451,#101452);
#101450= IFCCARTESIANPOINT((9.0190000,0.1020000,-0.8080000));
#101451= IFCDIRECTION((0.0000000,0.0000000,1.0000000));
#101452= IFCDIRECTION((0.0000000,0.0000000,0.0000000));
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

So clearly enough issues, but on my end the file does produce a Collada file. What's the exact behaviour on your end and what arguments did you supply to IfcConvert?

**Comment by theRealSuperMario** [comment]
I am running 

```bash
                    IFCCONVERT,
                    local_file_name,
                    tmp_glb_file_name,
                    "-qyv",
                    "--use-element-guids",
                    "--log-format",
                    "json",
                    "--log-file",
                    "log.json",
```

**Comment by theRealSuperMario** [comment]
Sorry, I was not looking correctly into my code.

The problem only occurs when the output format is `XML`

`IfcConvert ifc1.ifc ifc_out.xml -yv`

Geometry creation is fine

**Comment by theRealSuperMario** [comment]
Okay, I figured something out that works. All good now, thx.

**Comment by aothms** [comment]
> Okay, I figured something out that works. All good now, thx.

Care to explain, for others reading along?

**Comment by theRealSuperMario** [comment]
Sure


```python
For instance:
    #38467=IfcClosedShell($)
                          ^
With attribute:
    <attribute CfsFaces: <set [1:?] of <entity IfcFace>>>
Not optional
```

This can be fixed by converting faces to an empty set, rather than none.
```python
#38467=IfcClosedShell(())
```
You can double check this by opening the file, then and get the element by id. in one case, gives you `None`, on the other case its `[]` (empty collection)

There were some other problems related to having optional instead of empty sets, but they did not affect the geometry. Thats why the xml conversion crashed while the glb conversion was ok.

**Comment by Moult** [comment]
`IfcClosedShell($)` is invalid, the IFC spec requires SET [1:?] OF IfcFace, so I guess not a bug in IfcOpenShell?
