### ISSUE TITLE
Inconsistent penetration depth?

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2430]
The results of ifcclash reveal a penetration depth, but the result seems inconsistent (it seems for one contact area it is equal to the height of the wall, in the other it's the 'actual' penetration depth (0-which is correct)):

![image](https://user-images.githubusercontent.com/83825269/191533457-9735a8d2-03bd-46c7-a7e1-55612c7a42b6.png)

```
[
    {
        "name": "New Clash Set",
        "tolerance": 0.009999999776482582,
        "a": [
            {
                "file": "E:\\PORR\\Sample Files for blender\\AC20-FZK-Haus.ifc",
                "selector": "#25fsbPyk15VvuXI$yNKenK",
                "mode": "i"
            }
        ],
        "b": [
            {
                "file": "E:\\PORR\\Sample Files for blender\\AC20-FZK-Haus.ifc",
                "selector": ".IfcWall",
                "mode": "i"
            }
        ],
        "clashes": {
            "25fsbPyk15VvuXI$yNKenK-16DNNqzfP2thtfaOflvsKA": {
                "a_global_id": "25fsbPyk15VvuXI$yNKenK",
                "b_global_id": "16DNNqzfP2thtfaOflvsKA",
                "a_ifc_class": "IfcWallStandardCase",
                "b_ifc_class": "IfcWallStandardCase",
                "a_name": "Wand-Ext-ERDG-3",
                "b_name": "Wand-Ext-ERDG-4",
                "normal": [
                    0.0,
                    0.0,
                    1.0
                ],
                "position": [
                    11.7,
                    0.3000000000000007,
                    2.7
                ],
                "penetration_depth": 2.7 
            },
            "25fsbPyk15VvuXI$yNKenK-1bzfVsJqn8De5PukCrqylz": {
                "a_global_id": "25fsbPyk15VvuXI$yNKenK",
                "b_global_id": "1bzfVsJqn8De5PukCrqylz",
                "a_ifc_class": "IfcWallStandardCase",
                "b_ifc_class": "IfcWallStandardCase",
                "a_name": "Wand-Ext-ERDG-3",
                "b_name": "Wand-Ext-ERDG-2",
                "normal": [
                    -0.7071067811865476,
                    0.7071067811865476,
                    0.0
                ],
                "position": [
                    11.7,
                    9.7,
                    0.0
                ],
                "penetration_depth": 0.0
            }
        }
    }
]

```
File is a sample from BS: https://www.ifcwiki.org/index.php?title=File:AC20-FZK-Haus.ifc

**Comment by Moult** [comment]
If you're using IfcClash right now the depth isn't very important, merely just that "there is or isn't a clash". So both are touching and therefore "clashing". Can you help crosspost this upstream to hppfcl https://github.com/humanoid-path-planner/hpp-fcl and ask them what's the best way to get more meaningful results?

**Comment by vulevukusej** [comment]
Sorry for forgetting about this, I just cross-posted.  So currently, IfcClash doesn't actually consider the tolerance defined in BBIM - is this the reason why?  I added the following code to ifcclash.py, but since the penetration depth is inconsistent, its hit or miss whether this actually reduces the number of generated clashes..
```
if contact.penetration_depth <= clash_set["tolerance"]:
                continue
```

**Comment by aothms** [comment]
`ifcopeshell.geom.tree`  also has `protrusion_distances` when you do `tree.select()`. And is by default already tolerance aware (not blenderbim's but open cascade's internal face tolernace). I wonder if we can make a couple comparisons in terms of performance and fidelity of the results.

**Comment by IbimDesarrollo** [comment]
Hi, any news in this topic? i read response of hpp-fcl in "penetration-depth" topic but i dont know if there are any changes about. I think it is not sufficient in knowing only if two element clashes, a bim manager needs to know penetration depth to rate collisions. @vulevukusej @Moult @aothms thank you

**Comment by Moult** [comment]
No progress has been made here. If you can recreate the example from @vulevukusej and post it upstream at hpp-fcl that would help move things along.

**Comment by Moult** [comment]
@IbimDesarrollo absolutely. hpp-fcl is only used for the narrowphase, so it may be replaced with any other library. Would you like to try?

**Comment by Moult** [comment]
This is now fixed in the latest builds. It's still not perfect (protrusion distance is an inexact science perhaps?) but much better.
