### ISSUE TITLE
IFC Selector - select super class

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#2434]
It would be great to be able to select super classes like IfcBuiltElement or IfcElement for a more general search (e.g. get all elements with a certain material, get all load bearing elements etc.)

**Comment by aothms** [comment]
Can you give an example query that you'd like see supported. I think everything you describe is supported.

**Comment by TZwielehner** [comment]
You are right; it's only missing in the dropdown lists. When entered manually it works.
