### ISSUE TITLE
IFC Selector - Saved Query

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#2436]
It would be really handy to have a panel ("N" in 3D view) that lists the saved queries (like search groups in Navisworks or selection filters in Revit) for quick access

**Comment by vulevukusej** [comment]
This would be pretty handy, I agree!

**Comment by TZwielehner** [comment]
As I recently had a deeper dive into IDS: couldn't we consider searches / filters as the applicability part of an IDS file? In that way we could save queries and reuse them in different projects, just as libraries.
Are there parts that the selector covers that IDS doesn't?

**Comment by vulevukusej** [comment]
@TZwielehner have you generally tried saving the queries?  I haven't had time recently but mmoving them over to the n panel would be a quick job..

**Comment by TZwielehner** [comment]
Not really. The many possible applications of IDS came to my mind in a meeting today; storing such filters in a neutral way sounded like a good idea.

**Comment by Moult** [comment]
That's actually a pretty neat idea, IfcSelector queries are pretty similar to IDS, I suspect we can align them, and still allow "additional" functionality that IDS doesn't have where needed.

**Comment by Moult** [comment]
Saved searches are now available and accessible throughout the interface (e.g. for IfcClash too).
