### ISSUE TITLE
view all IfcClass by scrolling

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#2447]
I am not able to view all the IfcClass for assigning to elements. Inorder to view all the classes, I have to reduce the resolution in Blender Preferences -> Interface -> Display -> Resolution Scale to 0.85. Could this IfcClass menu be done as a scrolling option. 
I am also a beginner with python coding. Dont mind trying to code something to make this change. Any pointers or help in what direction I should look for.
![Screenshot from 2022-09-28 07-21-44](https://user-images.githubusercontent.com/58535690/192670582-2811f3ef-3113-43ce-9bdf-5a5d71204e37.png)
![Screenshot from 2022-09-28 07-21-07](https://user-images.githubusercontent.com/58535690/192670590-8ba24f93-f5f9-4b8b-a2bf-9be325034147.png)

**Comment by Moult** [comment]
Unfortunately when it comes to dropdowns that's all the Blender UI toolkit offers. To help in the process, the little "Search" icon is now available for any long dropdowns.

@Gorgious56 might know a trick?

**Comment by Gorgious56** [comment]
I think the alternative would be a UI list which can fit an indefinite number of items and has some filtering capabilities, but you'd have to fit it in the interface and you'd have to scroll to the wanted items anyway... Also the documentation about UI list is... lackluster :)

**Comment by vulevukusej** [comment]
Just my humble opinion, but I totally prefer using the search option since it's instantaneous.  I suppose the only downside is that you need to know in advance what you're after, but I'd imagine most BB users are powerusers anyway?  I would even go as far as making it the default behaviour, instead of requiring the user to click a button first...

**Comment by arunkvijay** [comment]
Agreed. closing this issue
