### ISSUE TITLE
No ifcopeningelement when adding door, or just opening

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2448]
https://www.dropbox.com/s/byo26auzigx2shd/2022-09-28_07-58-40_KeyShowView_Carnac.mp4?dl=0

as of
01b1b57f7124d6840457cc1afc1cd58ba496bfbf

**Comment by Moult** [comment]
Yeah I'm working my way through (walls, profiles, slabs... then will be openings, then fills like doors and windows).

Though it should work if you have the wall actively selected (e.g. bright orange).

**Comment by theoryshaw** [comment]
> Though it should work if you have the wall actively selected (e.g. bright orange).

Yes, sorry, that was it. 

feature request?

**Comment by Moult** [comment]
Nah let's leave this open since we need to make things more awesome anyway for fills, and when the time comes when I start committing features related to fills and openings we can reuse this issue.

**Comment by Moult** [comment]
Should now be solved.
