### ISSUE TITLE
BlenderBim Unable to activate latest build 20220929

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2453]
When attempting to activate latest built this error appears:

![image](https://user-images.githubusercontent.com/78321676/193024359-683c5584-4cec-41c3-a72b-02881f43b673.png)

**Comment by cvillagrasa** [comment]
Have you seen https://github.com/IfcOpenShell/IfcOpenShell/issues/2449 ?

It'll be probably fixed for Windows on tomorrow's build. One alternative in the meantime is to download a dll file as @theoryshaw

**Comment by Plae-Blue-Dot** [comment]
Ah I did not see that
