### ISSUE TITLE
Create shape on geometric curve set doesn't create circles

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2457]
See attached file, id 1202 has an indexedpolycurve and an ifccircle, but only the curve seems to be created, not the circle?

[test2.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9680294/test2.ifc.txt)

Left is the create_shape result, right is what I think I should see (from the new Blender profile editor)

![2022-09-30-125451_1302x390_scrot](https://user-images.githubusercontent.com/88302/193180480-23c4b6dd-5b93-4720-81d6-805744e38400.png)

**Comment by aothms** [comment]
That looks cool! Yeah, IfcCircle is mapped to a curve and not a wire or edge, but it should be easy to uplift it, I'll have a look.

**Comment by Moult** [comment]
Nice! Thanks :)
