### ISSUE TITLE
Openings using IfcRelVoidsElement is not applied consistently in BlenderBIM

### ISSUE THREAD

**Issue by Krande** [IfcOpenShell/IfcOpenShell#2458]
Hey,

I think I found a bug in BlenderBIM. 

I'm on windows 11 and I've tested the following on BlenderBIM addon v0.0.220928 and on v0.0.220930 and it produces the same results.

So I have created a test model with a single IfcOpeningElement, then applied this to different geometries using multiple IfcRelVoidsElement assignments. See attached dummy model -> [model_03_w_pen_detail.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9683747/model_03_w_pen_detail.zip)

I think I've isolated this to BlenderBIM as it seems IfcConvert (v0.6.0b0 (OCC 7.3.0)) successfully applies the opening when converting to glb (and I've checked Xbim for reference also). I have also performed the IFC quality check in BlenderBIM and it passes without any issues.

BlenderBim
![image](https://user-images.githubusercontent.com/9642232/193262525-296e1db0-07d7-45dc-9da5-cf249feda5bc.png)

Paint3D (after conversion from ifc to glb using ifcconvert)
![image](https://user-images.githubusercontent.com/9642232/193259970-786f121e-29b9-490b-85b7-2f025e77761d.png)

Xbim
![image](https://user-images.githubusercontent.com/9642232/193259172-b7dac33f-aede-4a71-97c7-97429f0a9f4e.png)

While I try poking into the BlenderBIM source code to see if I can spot the issue myself, any help on this is much appreciated!

Best Regards
Kristoffer

**Comment by aothms** [comment]
In the IFC schema, it's not allowed to assign a single opening to multiple elements:

Because the inverse attribute `VoidsElements : IfcRelVoidsElement FOR RelatedOpeningElement;` on IfcOpeningElement has cardinality [1:1]. I assume this might be the reason BlenderBIM dislikes this.

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcproductextension/lexical/ifcopeningelement.htm

**Comment by Krande** [comment]
Okay, thanks for the quick response!

So if I understand correctly I would have to create duplicates of the original `IfcOpeningElement` and connect each of them with a `IfcRelVoidsElement` to the different physical geometries I want the opening to be applied to?

**Comment by Moult** [comment]
> So if I understand correctly I would have to create duplicates of the original IfcOpeningElement and connect each of them with a IfcRelVoidsElement to the different physical geometries I want the opening to be applied to?

Yes and this is a very annoying part of the schema for native IFC modeling :) I have yet to figure out a satisfactory way of creating relationships between them so that native IFC modeling is convenient. Maybe IfcRelDefinesByObject?

**Comment by Krande** [comment]
I see. Well using `IfcRelDefinesByObject` does sound a bit more appealing to me than duplicating the IfcOpeningElement. Would using `IfcRelDefinesByObject` work straight away with openings in BlenderBIM?

**Comment by Moult** [comment]
It won't work now, and if it does, it'd be special to the BlenderBIM Add-on. We're going into uncharted territory here.

**Comment by Krande** [comment]
That's fine. I can just duplicate my IfcOpeningElement then :) Thanks for the quick response. I'll just go ahead and close this then, given it's a classic case of `user error` and not `software bug` :)

**Comment by brunopostle** [comment]
I was considering putting the opening geometry in the Type object using a different representation (reference context maybe), then copying this each time I needed an opening geometry.
I was hoping that maybe it could be mapped to the opening, to save copying, would this be the same as the reldefinesby object idea?

**Comment by Krande** [comment]
Here's a small update! 

I just tried to convert the same IFC model to .`glb` using a newer version of ifcconvert (using the v0.7.0 branch) and I see that the converted IFC using v0.7.0 produces the same result as in BlenderBIM:

Paint3D
![image](https://user-images.githubusercontent.com/9642232/193309834-7f03f1b1-9e28-494d-9e6f-ec1b97ae5bbf.png)

I.e. Both IfcOpenShell and BlenderBIM produces the same correct results according to the IFC schema.

**Comment by aothms** [comment]
Note that another thing you can do that actually works as of now in the schema, is to create an aggregate out of the individual host building elements and assign the opening to the aggregate. This is often done for walls with layers as individual IfcBuildingElementParts. Obviously, if you're doing this for e.g a floor slabs on different stories, it's going to be highly awkward, but in some cases it might be ok.

**Comment by Krande** [comment]
Hey, so I thought I would solve this by way of duplicating the IfcOpeningElement. 
However, as it turns out it didn't solve the root issue :( 

So I was pretty sure the IfcOpeningElement was applied to multiple geometries. 
I created a small test, [cutout_hp.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9724940/cutout_hp.zip), that demonstrated that I am able to cut openings in 2 IfcPlate objects using duplicates of IfcOpeningElements. But unfortunately I wasn't able to cut the IfcBeam. 

![image](https://user-images.githubusercontent.com/9642232/194316608-f40a0dde-8b76-4ce6-b767-1ac22504779e.png)

However, the ability to cut the IfcBeam seems dependent on the size of my IfcOpeningElement cylinder radius. If I reduce the radius sufficiently so that it does not completely sever the IfcBeam geometry into separate geometries, the cut is applied (se updated file here 
[cutout_hp_small_radius.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9725033/cutout_hp_small_radius.zip))

![image](https://user-images.githubusercontent.com/9642232/194319908-4c144681-39f8-4d32-966a-79d1c3eb3bdd.png)

So I would then revise my question: 

Is it possible to apply a negative volume onto my `IfcBeam` (or any IFC geometry for that matter) so that it is severed into 2 separate geometries?
