### ISSUE TITLE
Blender BIM not working

### ISSUE THREAD

**Issue by amarkrish108** [IfcOpenShell/IfcOpenShell#2464]
![image](https://user-images.githubusercontent.com/64318675/193501883-cbd28af8-a4a8-48b8-97ec-1d9f7e0af893.png)

Whenever I try to install Blender BIM, I am getting this message only.

**Comment by Moult** [comment]
You need the latest stable version of blender as mentioned on the website.

If you want an older version you need to follow the unstable instructions: https://blenderbim.org/docs/devs/installation.html#unstable-installation

**Comment by amarkrish108** [comment]
I am using the Latest version of Blender, but it is a portable version.

**Comment by Moult** [comment]
That's doesn't seem to be what your screenshot shows. Your screenshot shows Blender 3.0 whereas the latest Blender is Blender 3.3.

The documentation link explains which Blender versions are compatible with which releases. But if you want something to Just Work, it's best to use the latest version of Blender :)

**Comment by amarkrish108** [comment]
Ok Moult, Thanks.
