### ISSUE TITLE
Support for Beam Cardinality using IfcMaterialProfileSetUsage

### ISSUE THREAD

**Issue by Krande** [IfcOpenShell/IfcOpenShell#2465]
Hey,

I was wondering if I am using the [IfcMaterialProfileSetUsage](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/lexical/IfcMaterialProfileSetUsage.htm) class correctly with respect to offsetting beams by assigning a specific cardinality point and/or if this isn't supported yet by IfcOpenShell/BlenderBIM.

From what I can infer from my test-file: [cardinality.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9695238/cardinality.zip) where I have applied 2 different cardinalities (cardinality of `top centre=8` and `neutral axis=5`), I have either misunderstood how to use it or it seems to not have any effect on the geometry using IfcOpenShell.

Here's how it looks in BlenderBIM

![image](https://user-images.githubusercontent.com/9642232/193517057-2c29657a-7476-4d52-b093-56cfa5583a74.png)

and, here it is how it looks after being converted to .glb using IfcConvert (v0.7.0 latest daily conda build).

![image](https://user-images.githubusercontent.com/9642232/193516841-02bcbe36-5fd0-4ed4-88ce-f16955f41da0.png)

If this isn't supported yet, where would be the appropriate place to begin for adding support for it?

Best Regards
Kristoffer

**Comment by aothms** [comment]
I have never begun to understood this part of the schema, but know that @Moult does :)

I would find it surprising if something on this side of the schema affects geometric output. Although we can do layerset slicing (which is same schema part) I consider that more of the geometric outcome. Using the material section to define translations seems odd to me and would assume the cardinal point here is more like informative meta-data that doesn't affect geometric outcome.

**Comment by Krande** [comment]
Right. So in practice I would translate the beam's geometry in addition to assigning the cardinality of the beam (and I would probably keep the beam axis polyline as-is). That sounds like a reasonable approach for me :)

**Comment by Moult** [comment]
The cardinality merely states what it _should_ be, but expects the geometry to be defined in the right spot. IfcConvert shouldn't be doing any processing, it's the authoring tool that has the responsibility to get it right. You can author these in the BlenderBIM Add-on, of course, to see live what it should be.

A great example of all the cardinalities is produced by @jmirtsch:

[beams.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9695842/beams.ifc.txt)

**Comment by Krande** [comment]
Thank you both for the quick responses! This answers my question :)
