### ISSUE TITLE
BlenderBim 20221003 - Error when attempting to add door in wall

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2467]
![image](https://user-images.githubusercontent.com/78321676/193563029-2b0ef5c3-050a-4150-bb5c-329581ac320e.png)

When adding a door into a wall, this error appears and the Ifc opening does not get created. The door itself is added:
![image](https://user-images.githubusercontent.com/78321676/193563158-833f4be9-d349-4256-b710-623aad553340.png)

Not quite certain how the new openings system works, but this seems like a bug

**Comment by Moult** [comment]
Yep, it's a bug since the openings system is still being rewritten, so I haven't yet gone through the exercise of looking at openings + fills (fills are things like doors / windows / dampers / etc). It might take a couple more days of hacking on openings before I get a chance to look at this. Let's keep this bug open so I can help let you know when the time is right to start testing this aspect again.

**Comment by Plae-Blue-Dot** [comment]
I know it's ongoing but I check it everyday anyway, so I thought I'd just update.

Windows and doors now add properly to the wall with an associated opening.
The error it throws out no longer appears.  However The opening no longer automatically follows the object when moving it:

![image](https://user-images.githubusercontent.com/78321676/194720669-e5ea7cfc-d5c4-4ff9-bcb8-4f45cf12c5ae.png)


From the new openings system it can be done by: 

selecting the host (the wall) 
clicking the "show openings" button
moving the Ifc Opening
reselect the host and clicking "edit openings" (the tick)
![image](https://user-images.githubusercontent.com/78321676/194720741-7c70cb00-8d76-429c-a2ae-aa9fde14115f.png)
results in success:
![image](https://user-images.githubusercontent.com/78321676/194720764-92c68b2e-fd9a-4221-916b-bf24aaec95f6.png)

But is way slower than the old automatic tracking. Dynamic voids doesn't seem to affect it


Also the new IfcOpening "Add void" (Shift O) does not work like the above:
![image](https://user-images.githubusercontent.com/78321676/194720824-d801e85d-37e1-46cb-b5db-bea168acfd63.png)

And after moving any IfcOpening after toggling the Void button (alt O) it's not obvious you need to reselect the host to toggle it off.

**Comment by Plae-Blue-Dot** [comment]
After flipping (shift F) the orientation of the wall (the host) the Instanced Ifcopenings seemed to be moved along the wall axis far away:
![image](https://user-images.githubusercontent.com/78321676/194721338-f346251a-a709-444f-85ae-3ac9075176a3.png)

**Comment by Moult** [comment]
Dynamic voids is being removed, the booleans aren't reliable enough. When you've moved a fill (door / window), do Shift-G to regenerate.

Good report on the flipping I hadn't yet considered that.

**Comment by Moult** [comment]
I think these are all fixed.
