### ISSUE TITLE
pip upload fails because of total file limit

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#2468]
See failing Actions recently.

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Project size too large. Limit for project 'ifcopenshell-python' total  
         size is 10 GB. See https://pypi.org/help/#project-size-limit    
```

**Comment by Moult** [comment]
After a quick search it seems as though twine (the python module which handles uploads to PyPI) doesn't support removing a package so I haven't discovered any API call to clear out the older cruft (maybe I missed one?). I can remove old releases manually via the web dashboard but that's annoying. We'd also hit the limit pretty quick with daily releases.

How about we make the releases once a week or twice a month? Then when we hit the limit I just manually purge via the dashboard?

**Comment by aothms** [comment]
Sounds good to me, you're aware of the cron syntax of GHA I assume https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/.github/workflows/ci-blenderbim-choco.yml#L11

**Comment by Moult** [comment]
OK I've adjusted this to once a month https://github.com/IfcOpenShell/IfcOpenShell/commit/008d6bed5c2ce062671e0fb9b7001d9cc59cbf53 and still struggling with the ifcopenshell namespace so let's keep this bug open until I can publish to ifcopenshell: https://github.com/pypa/pypi-support/issues/2197

**Comment by Moult** [comment]
Closing as now published! https://pypi.org/project/ifcopenshell/

**Comment by aothms** [comment]
Awesome, great job
