### ISSUE TITLE
blenderbim-221003 - UI not showing new ElementType

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#2469]
Hy guys,

In the UI, it is no longer possible to create an instance of an ElementType. The option has disappeared.
![image](https://user-images.githubusercontent.com/40517234/193642479-153af26a-da2d-4868-9ba0-01bc86c08e83.png)

**Comment by Moult** [comment]
You have to enable the BIM Tool (green cube icon left on viewport) then go to the Tool menu (you're currently on the BlenderBIM menu). You will also see it in the top toolbar.

**Comment by vuicBABS** [comment]
Ok it works. After that I tested the button "opening".
It create a cube. I had to assign an opening class. And I tried to add an opening to a wall with CTRL+E. It didn't work. I did it in the UI. It seems it's linked but there is no modifier created and it's not visible.

**Comment by Moult** [comment]
The opening authoring methods are in the process of being rebuilt right now, so it's in a bit of a WIP state.

**Comment by Moult** [comment]
The openings system should be quite a bit more stable now.

 1. Enable BIM tool.
 2. Draw a wall or slab.
 3. Shift-O to create a potential opening. Change the size parameters, or move it to where you want.
 4. Select the potential opening once you're happy, then select the wall/slab, and then Shift-O again to apply it.
 5. Alt-O toggles openings.
