### ISSUE TITLE
Double quotes in string properties of IFC

### ISSUE THREAD

**Issue by leanfm** [IfcOpenShell/IfcOpenShell#248]
There are cases when a double quotes is used to mean inch and appears in some string properties of IFC. When using the IfcConvert andif there are double quotes in the name property of the IFC property, the name is used in the dae XML and cause error.

**Comment by Stinkfist0** [comment]
Good catch, I assume you are using --use-element-names? There is XML escaping code in ColladaSerializer but that is performed only for material names currently.

**Comment by Stinkfist0** [comment]
@leanfm Can you confirm that the problem occurred when using --use-element-names?

**Comment by aothms** [comment]
> Can you confirm that the problem occurred when using --use-element-names?

I can reproduce this.

It's odd, you would expect OpenCollada/libxml2 to handle escaping for us. It's a pain to guarantee all strings are properly escaped (and not more than once ...).
