### ISSUE TITLE
Mac M1 support

### ISSUE THREAD

**Issue by sharon-br** [IfcOpenShell/IfcOpenShell#2485]
Hey,
Current mac builds are only supporting Intel CPUs.
As more and more developers are starting to use the new M1 macs it would be great to release a build suitable for this as well.

Is that something that you are planning on adding?
I would love to hear the current options for this.

**Comment by aothms** [comment]
The latest builds are available on m1 as well https://github.com/IfcOpenBot/IfcOpenShell/commit/fa6bbf2d4a69cb8d1f793b3d4ca86571e9b414e8#comments

(btw we're still looking for some perpetual funding for the costs of the build server specifically for this https://opencollective.com/opensourcebim/projects/apple-m1-build-server)

**Comment by sharon-br** [comment]
When are you expecting to release a new version with the said build included?

**Comment by Moult** [comment]
@sharon-br you might want to check out https://blenderbim.org/docs-python/ifcopenshell-python/installation.html which should contain the latest builds.
