### ISSUE TITLE
Duplicating an opening and applying it, creates an opening in the wrong location

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2489]
Duplicating an opening and applying it, creates an opening in the wrong location
https://www.dropbox.com/s/ydv65dxbrr93lz8/2022-10-08_18-27-50_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
BTW when duplicating an opening, it is not necessary to (re)"apply" to the host, it'll automatically void the same host as the origijnal.
