### ISSUE TITLE
build-deps.cmd fails on Boost (1.63.0 used currently) if user has only VS 2017 and no earlier versions installed

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#249]
```
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src/tools\msvc.jam:834: in generate-setup-cmd
*** argument error
* rule maybe-rewrite-setup ( toolset : setup-script : setup-options : version : rewrite-setup ? )
* called with: ( msvc :  :  : default :  )
* missing argument setup-script
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src/tools\msvc.jam:746:see definition of rule 'maybe-rewrite-setup' being called
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src/tools\msvc.jam:1076: in configure-really
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src/tools\msvc.jam:201: in configure
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src/tools\msvc.jam:153: in msvc.init
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src/build\toolset.jam:43: in toolset.using
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src/build\project.jam:1052: in using
project-config.jam:3: in modules.load
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src\build-system.jam:249: in load-config
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src\build-system.jam:412: in load-configuration-files
C:/Dev/GitHub/Stinkfist0/IfcOpenShell/deps/boost/tools/build/src\build-system.jam:524: in load
C:\Dev\GitHub\Stinkfist0\IfcOpenShell\deps\boost\tools\build\src/kernel\modules.jam:295: in import
C:\Dev\GitHub\Stinkfist0\IfcOpenShell\deps\boost\tools\build\src/kernel/bootstrap.jam:139: in boost-build
C:\Dev\GitHub\Stinkfist0\IfcOpenShell\deps\boost\boost-build.jam:17: in module scope
```
Quick googling gives numerous hits for this problem, I'll look into this in the near future.

**Comment by Stinkfist0** [comment]
Simply updating to 1.64 seems to fix this. 1.65 should be also out very soon - maybe better to wait a week or two and update straight away to the upcoming version?

**Comment by Stinkfist0** [comment]
Also, compiling IfcOpenShell with latest VS 2017 (15.3) seems to generate harmless warnings spam, "Unknown compiler version - please run the configure tests and report the results" - maybe this will be fixed in Boost 1.65.

**Comment by aothms** [comment]
> Do you have a preference which version of Boost (and Visual Studio) to use for the official 0.5.0 release?

Not really, do you see good reasons to prefer one over the other?

> maybe this will be fixed in Boost 1.65.

I'd assume so.

I will get rid of this `BOOST_OPTIONAL_USE_OLD_DEFINITION_OF_NONE` as well. It's just something silly in the IfcOpenHouse example.

**Comment by Stinkfist0** [comment]
I'd guess there's no harm using "the latest and greatest", but it would be nice to have the same version of Boost used for all platforms by default.

**Comment by Stinkfist0** [comment]
Boost 1.65 was released yesterday, I'll give it a go.

**Comment by Stinkfist0** [comment]
Unfortunately the warning spam persists after updating to 1.65.0, but otherwise everything seems fine, as expected.

**Comment by Stinkfist0** [comment]
Boost 1.65 available at the usual download location now.

**Comment by Stinkfist0** [comment]
It would appear that Boost 1.65.1 was released last week which fixes the warning spam.

**Comment by thorade** [comment]
Could it be that build-deps.cmd is currently copying boost to a wrong location after building?
The run-cmake.bat script is complaining that it could not find boost, but I am not sure whether that warning is correct, because at a later step it is also saying that it did find boost.

**Comment by Stinkfist0** [comment]
build-deps.cmd should abort if building Boost fails. Boost is used currently as-is from its extracted location (it's not copied around due to the huge file count).
