### ISSUE TITLE
Cannot delete IFC elements.

### ISSUE THREAD

**Issue by KinzyBogdan** [IfcOpenShell/IfcOpenShell#2496]
BlenderBIM tester.

The floating elements are undeleteable. After deleting them, saving the project, and reopening Blender and the .ifc file, they keep reappearing. I can provide the file if needed.

![image](https://user-images.githubusercontent.com/110157118/195385103-6f138d48-014d-46d9-acae-06d9ecd61ec8.png)

**Comment by Moult** [comment]
Can you please provide the .ifc file?

**Comment by KinzyBogdan** [comment]
This is the file. I was deleting the floating door and the two floating
small walls, then saving the project, opening a new blender file, and
loading the project again.

Thank you for all the work you put into BlenderBIM! :)

**Comment by Moult** [comment]
Sorry, I can't see any attachments, you can rename the file extension to .txt and upload to Github :)

**Comment by KinzyBogdan** [comment]
Here it is

[LearningNativeBIM - BUG Report.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9771127/LearningNativeBIM.-.BUG.Report.txt)

**Comment by Moult** [comment]
I was able to successfully delete all elements without any issues. Perhaps we can screenshare at osarch.org/chat to see exactly what you're doing?

**Comment by KinzyBogdan** [comment]
Ofcourse, just tell me when

**Comment by Moult** [comment]
Anytime, just drop in and ping me, my username is Moult

**Comment by Moult** [comment]
Hey I pinged you a couple times in the chat with no response, would you be available for a screenshare?

**Comment by KinzyBogdan** [comment]
Hello, yes I would love to meet. Would in 2 hours suit you?

**Comment by Moult** [comment]
It'll be getting late (10:30pm) so no guarantees, but if you just ping me in the chatroom during Sydney waking hours I'm sure we can work something out.

**Comment by U-Rod** [comment]
Hi, I've had similar problem that appears after configuring an element, selecting IFC Object Metadata/IFC Class/Unlink Object and configuring the same mesh again. Just the last element is shown in .blend file, but previous ones are shown when exporting to .ifc.

**Comment by Moult** [comment]
Unlink object does not delete an object. It simply unlinks the Blender object from the IFC object. Generally only to be used by advanced users. Maybe you can share your screen in https://osarch.org/chat and I can help?

**Comment by U-Rod** [comment]
[part1.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9843425/part1.txt)
[part2.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9843429/part2.txt)
Hi! I made an example to explain: part1 just generate a wall and save .blend and .ifc, and part2 is forward, after unlink, assign IFC Class again, moving the wall for better view and export .ifc.
Part1 shows one wall, but part2 shows two. It's strange also that file .blend, just from part1, stops recognizing IFC Project created with template IFC4 Demo Library.

**Comment by Moult** [comment]
@U-Rod what you've described is not a bug. Unlinking does not delete, it simply breaks the connection between the Blender object and the IFC element. So if you select the wall, unlink it (the IFC element is still there!), move it (now it is plain Blender geometry you're moving), then assign IFC class again (now the Blender object is linked to a brand new additional IFC element), then save, naturally you end up with two walls.

If you want to delete, just use the delete button or "x" key.
