### ISSUE TITLE
BBIM - BIM Tool door issues

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#2497]
Testing out the BIM Tool, is there a way to tackle the following two things:

### 1/ Door orientation 🙃
- Add a wall from a wall type. Name it "Wall 1"
- Copy Wall 1, and name this new wall as "Wall 2".
- Rotate Wall 2 by 90 degrees.
- Add a door from a door type on wall 1 --> OK .
- Add a door from a doort type on wall 2 --> the door is perpendicular to wall 2.

### 2/ Door movement 💨
- Create a wall,
- Add a door,
- Moving the door does not move the opening created.
(Is there an actual opening being created upon adding a door or window? I can't see any new entity created for openings)

**Comment by Moult** [comment]
1. You have to have both the wall selected, and the 3D cursor on the wall somewhere where the door is to be inserted.
2. Right now it's a manual refresh, after moving, Shift-G to regenerate. Yes, an opening is being created. Toggle openings with Alt-O with the wall selected.

**Comment by myoualid** [comment]
Re-test with success  👍  !
