### ISSUE TITLE
Simple file crashes XBim Xplorer and ODA Open IFC Viewer validation

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2499]
Here's a simple model. In Revit, Blender, IFCJS, no issues at all.

in XBim Xplorer and ODA Open IFC Viewer, it shows a wall with no opening for the door, and any attempt to run the validator for both of those platforms causes a crash.

Is something wrong with this file?

[test2(2).ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9783348/test2.2.ifc.txt)

What XBim sees:

![image](https://user-images.githubusercontent.com/88302/195784772-ca98b036-6767-4042-8b1a-7ece88422f4e.png)

What IFCJS sees:

![image](https://user-images.githubusercontent.com/88302/195784842-15a8eb7a-276b-47e7-8bf9-571dee3f005f.png)

**Comment by aothms** [comment]
I don't see anything. Does XBim support boolean operations (openings) using tesselations?

`python ifcopenshell.validate` shows nothing

`IfcConvert -vv` shows nothing interesting:

```
IfcOpenShell IfcConvert 0.7.0 (OCC 7.5.3)
[Notice] [2022-10-14 09:14:31] exclude entities IfcOpeningElement IfcSpace
Scanning file...
Done scanning file
Parsing input file took 0 seconds
[Debug] [2022-10-14 09:14:31] Begin processing
#184=IfcDoor('35ZC7$4v980QKdbRgkwQcY',$,'Door',$,$,#254,#216,$,$,$,.NOTDEFINED.,$,$)
[Notice] [2022-10-14 09:14:31] {35ZC7$4v980QKdbRgkwQcY} Valid: 1
#93=IfcPolygonalFaceSet(#72,$,(#73,#74,#75,#76,#77,#78,#79,#80,#81,#82,#83,#84,#85,#86,#87,#88,#89,#90,#91,#92),$)
[Notice] [2022-10-14 09:14:31] {35ZC7$4v980QKdbRgkwQcY} Valid: 1
#100=IfcPolygonalFaceSet(#72,$,(#94,#95,#96,#97,#98,#99),$)
Creating geometry...
[Debug] [2022-10-14 09:14:31] Progress 0
[Debug] [2022-10-14 09:14:31] Begin processing
#144=IfcWall('2na59pA_r3z8C4KVOVdjOB',$,'Wall',$,$,#157,#152,$,.NOTDEFINED.)
[Notice] [2022-10-14 09:14:31] {2na59pA_r3z8C4KVOVdjOB} Valid: 1
#182=IfcExtrudedAreaSolid(#176,#180,#181,3.)
[Notice] [2022-10-14 09:14:31] {2na59pA_r3z8C4KVOVdjOB} Valid: 1
#237=IfcPolygonalFaceSet(#236,$,(#230,#231,#232,#233,#234,#235),$)
[Debug] [2022-10-14 09:14:31] {2na59pA_r3z8C4KVOVdjOB} Simplified operand A from 6 to 6
[Debug] [2022-10-14 09:14:31] {2na59pA_r3z8C4KVOVdjOB} Simplified operand B from 6 to 6
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Operand A is manifold
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Operand B 0 is manifold
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Used fuzziness: 0.000010
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Operand A 1/1 is an extrusion
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Operand B 1/1 is an extrusion
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Operand B creates a through hole
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Intersecting boundaries
[Debug] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Simplified operand A from 1 to 1
[Debug] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Simplified operand B from 1 to 1
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Operand A is non-manifold
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Operand B 0 is non-manifold
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Used fuzziness: 0.000010
[Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Processed fully in 2D
[Debug] [2022-10-14 09:14:32] Progress 20
Done creating geometry (2 objects)

Conversion took 1 second
```

This may sounds suspicious:

>     [Notice] [2022-10-14 09:14:32] {2na59pA_r3z8C4KVOVdjOB} Intersecting boundaries

but really isn't. It is just the fact that in 2D the outer boundary of the wall intersects with the opening, which is allowed (and expected for doors), it just means that the 2D boolean op will be performed as a face-face subtraction and not as simply embedding an inner wire onto the face.

![afbeelding](https://user-images.githubusercontent.com/1096535/195787236-cff1daa4-6faa-4f88-9c95-6ac587d58ec2.png)

**Comment by Moult** [comment]
Is boolean operations (openings) using tesselations allowed? I assumed so? :)

**Comment by Moult** [comment]
I extended the opening past the floor of the wall and retested, but still the same results, so perhaps not related to Intersecting boundaries.

**Comment by Moult** [comment]
Changing the opening to a rectangular extrusion will show the opening in XBim but not in ODA's Open IFC Viewer. Both validation crashes though. Odd.

**Comment by aothms** [comment]
Do these validators depend on a project/product?

Otherwise just do:

```
for inst in ifc_file:
  f2 = ifcopenshell.file(schema=ifc_file.schema)
  f2.add(inst)
  f2.write(f'{inst.id():05d}.ifc')
```

and find the smallest file that crashes the validator.

**Comment by Moult** [comment]
Good idea, I'm going to wait for the XBim folks to take a peek first though :)

**Comment by Moult** [comment]
Closing as displays correctly in latest version of XBim. ODA probably has a bug but I don't know any public channels for them.
