### ISSUE TITLE
VS 2017 (15.3) and OCCT 7.1.0: unresolved external symbol 'recv'

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#250]
Probably easiest to fix simply by adding linking to ws2_32.lib.

**Comment by Stinkfist0** [comment]
I will be submitting a fix shortly (after I have tested also Debug build, RelWithDebInfo already tested and compiles fine).

**Comment by Stinkfist0** [comment]
recv() is used in _get_buffer(), a helper function in OSD_File.cxx. IIRC there has been similar stuff there for quite a while, but probably has not bit us until now due to some OCCT build configuration differences.

**Comment by aothms** [comment]
I cannot directly see though what has changed in terms of that. Let's assume it's not important.
