### ISSUE TITLE
Question regarding using numpy in the ifcopenshell.geom.create_shape codebase

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2502]
i am not that well versed in coding, however i know there is a speed increase using numpy ndarray data type over the default python list data type.

And i also saw that Blender ships NumPy package with it.
![image](https://user-images.githubusercontent.com/110968398/195864248-b13e6292-673c-40de-a1e2-d3c1fea83e44.png)

> For the BlenderBIM Add-on and Blender's OpenGL viz, with mesh based visualisation, we use the triangulation function.
From https://github.com/IfcOpenShell/IfcOpenShell/issues/671#issuecomment-1267727787

And from this nice doc https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html#individual-processing i see that the triangulated faces are given in python list data type

![image](https://user-images.githubusercontent.com/110968398/195863805-2e8f01dc-7271-4b10-97ab-4675c4755dbb.png)

So would be adding a create_shape NumPy variant decrease the import time in BlenderBIM?

**Comment by aothms** [comment]
> So would be adding a create_shape NumPy variant decrease the import time in BlenderBIM?

Likely not measurably. The time is likely spent inside opencascade geometry conversion functions. Numpy is especially faster when doing manipulations: `arr[:] * 2.` instead of `[v * 2. for v in my_list]`. We're not doing that. Also it would create a compatibility requirement between the IfcOpenShell and the numpy API because we'd be creating this numpy array in the C++ codebase of IfcOpenShell.

**Comment by Moult** [comment]
The bottlenecks in loading IFCs in Blender seem to be:

 1. High poly meshes, if they exist
 2. Certain scenarios of booleans
 3. Large object counts (IfcOpenShell is long done, but Blender doesn't handle high numbers of objects well)

We actually feed the IfcOpenShell lists directly into Blender without post-processing. The only time we manipulate those returned lists is dealing with material_ids and if there is a false origin applied to actual geometry (as opposed to a false origin applied to placements).

**Comment by Moult** [comment]
Closing this as I don't think there is any action to take.
