### ISSUE TITLE
Installation via PIP

### ISSUE THREAD

**Issue by matpen** [IfcOpenShell/IfcOpenShell#2506]
I normally use PIP to install dependencies and just found [this package](https://pypi.org/project/ifcopenshell/): however, the PYPI entry looks very "unofficial", and I do not see it mentioned in the [installation instructions on the website](http://ifcopenshell.org/python), nor in the [GitHub readme](https://github.com/IfcOpenShell/IfcOpenShell). Further search led to multiple other PIP packages like [this](https://pypi.org/project/python-ifcopenshell/) and [this](https://pypi.org/project/ifcopenshell-python/).

So I am confused: is one of these entries the official one? Is installation via PIP supported?

**Comment by Andrej730** [comment]
It is mentioned on [installation page](https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#pypi)
![msedge_5jVNHhEmlh](https://user-images.githubusercontent.com/9417531/196050925-f983519a-06c1-4e85-8344-37e0edea79fc.png)

and in [readme.md](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/README.md) 

![kkwFXiExeS](https://user-images.githubusercontent.com/9417531/196050938-716c7ed0-16ca-4035-9c51-ba673304c594.png)

so it is official 🙂

**Comment by matpen** [comment]
That is great, thank you very much for the quick response! And sorry for the noise, I completely missed that.
