### ISSUE TITLE
BlenderBim - IfcWindow demo type loads but does not load geometry - from 20221015 onwards

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2510]
![image](https://user-images.githubusercontent.com/78321676/196489948-2231e741-f47a-4ccd-b115-7f934f0e5061.png)
Above window loaded but no geometry

Last working on 20221014

**Comment by Moult** [comment]
Seems to work for me?

 1. Create wall
 2. Place 3D cursor on wall where you want the window (Shift-RMB) ideally with snapping enabled
 3. Select wall (this tells BBIM the window is to be inserted into that particular wall, not just floating in space)
 4. Add window.

**Comment by Plae-Blue-Dot** [comment]
Using latest BlenderBim221018 & Blender 3.2.2

Little video of it not working:
[Window Error - 2022-10-19 09-07-18.mkv.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9817741/Window.Error.-.2022-10-19.09-07-18.mkv.txt)

No error just doesnt load
I'll try 3.3 later today

**Comment by Moult** [comment]
Interesting, I can't replicate that issue. If you're available online on osarch.org/chat we can screenshare and debug it together.

**Comment by Moult** [comment]
Ahh yet another unit conversion bug. So sorry, I've clearly been doing very poor testing and discipline when it comes to units.

**Comment by Plae-Blue-Dot** [comment]
You nailed it, works with metres:
![image](https://user-images.githubusercontent.com/78321676/196624195-ea4c969b-9086-415a-9408-b9251889dd26.png)

I found the window in mm:
![image](https://user-images.githubusercontent.com/78321676/196624493-4ad0af83-1afb-4777-be4f-fd53c1a6e398.png)

it's wayyy above the wall but the right size
