### ISSUE TITLE
BlenderBim request - Can sheets and CSS be saved with IFC file somehow?

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2516]
I am using custom sheets/titleblocks, and custom CSS while testing BlenderBim, 

Whenever I print drawings or sheets on a different project or every time I update or change the the blenderbim version it resets and I lose my sheet layout completely and my line weights. 

At the moment I am aware of it and I am recopying my sheets and CSS every time.

Using one project at a time it works fine for now but is there maybe a way to create a local copy of the templates folder near the Ifc project location? that way it references that and they don't overlap? 

Problem:
Sheets and CSS styles need to be reset

Like the demo file example
Can print the drawings fine:
![image](https://user-images.githubusercontent.com/78321676/196649604-7bdd3c21-d976-424a-b87b-a12003507009.png)

gives a missing sheet error when wanting to print the sheet:
![image](https://user-images.githubusercontent.com/78321676/196649059-46c46d71-4215-4ca5-a758-f30d0afe1706.png)

The same error is given when switching between sheets between projects locally, it loses it

Request: 
sheets and CSS can be saved with IFC file somehow?

**Comment by Moult** [comment]
Yeah there is a partial implementation of this where the sheet URIs are saved with the IFC. But it is definitely incomplete, it's probably due in the next upgrade of the drawings module.

**Comment by Plae-Blue-Dot** [comment]
Hey @Moult just checking in if there has been any progress on this one?

**Comment by Moult** [comment]
Not yet, I forgot about it, thanks for the reminder. I'll add it to the roadmap for the next release.

**Comment by Plae-Blue-Dot** [comment]
Much appreciated! Can't wait, this would be very helpful, I'm switching between 6 or so projects atm and this would be a massive timesaver!

Thanks again Moult!

**Comment by Moult** [comment]
So there are a few things I want to achieve here.

 1. If a drawing, sheet, schedule, titleblock, etc is referenced, I want that URIReference to be in IFC. That way, there is no need for "Magic" paths to be be transferred along with the project. Just the files and that's it.
 2. The paths must be relative. Naturally, this is relative to the IFC. That way you can copy paste and move around projects easily.
 3. The paths may be edited at any time, or have their defaults changed (i.e. the default path to add when creating new ones). The user should not be forced to use the "BlenderBIM Way Of Organising Data Files".
 4. Drawings/schedules are DocumentReferences (i.e. this document exists, but no publishable metadata), whereas sheets are DocumentInformation which then compiles multiple DocumentReferences within them with metadata.

Note that there will likely be a few breaking changes.

**Comment by Moult** [comment]
Warning @Plae-Blue-Dot @theoryshaw this latest commit still needs a few more pieces before it has a semblance of stability. These are breaking changes so if you have any projects you want "upgraded" to the new drawing management system let me know because otherwise you'll lose/corrupt your drawing data.

**Comment by theoryshaw** [comment]
If we're starting anew can we use it?... or better of waiting?

**Comment by Moult** [comment]
Wait until this issue is closed I'd say. Sorry. You can do other stuff just don't create drawings/schedules/sheets.

**Comment by theoryshaw** [comment]
Np, worth pulling this out into a branch instead for testing?

**Comment by Plae-Blue-Dot** [comment]
> want "upgraded" to the new drawing management system let me know because otherwise you'll lose/corrupt your drawing data.

Got it thanks for the warning @Moult Will keep this separate for now

**Comment by Moult** [comment]
Both of those files still exist, as we want to ship assets out of the box. However, once you use an out of the box asset, it gets copied to your configured default folder (e.g. layouts/titleblocks or drawings/*).

**Comment by theoryshaw** [comment]
If I put a custom svg in `...\layouts\titleblocks` should it show up in the following dropdown?  If so, it currently does not. 
![image](https://user-images.githubusercontent.com/507113/231033711-6ff979f5-432f-4c78-8fb5-79c901137490.png)

I put `view-title.svg` in `...drawings\assets\view-title.svg`, but got an error that it could not find this file, as it was looking for it here `C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\data\assets\view-title.svg`, once i put this file here, the error went away.

**Comment by Moult** [comment]
Yeah I should make that dropdown detect titleblocks there, not just the OOTB ones.

You shouldn't need to put view-title anywhere? Doesn't it already exist in C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\data\assets\view-title.svg ? https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/blenderbim/blenderbim/bim/data/assets

**Comment by theoryshaw** [comment]
What if you have a custom `view-title.svg`?

Per the logic, it seems like it should be in `...drawings\assets\` relative path, as is similar to other assets such as...
![image](https://user-images.githubusercontent.com/507113/231038021-cbe4979d-fbef-4cb3-bcd3-4bfa9e2134e9.png)

**Comment by theoryshaw** [comment]
> the view-title is a layout asset, not a drawing asset. So put it in layouts/assets/.

I think that was it!

Thanks for the overview.

**Comment by Plae-Blue-Dot** [comment]
@Moult thanks for the excellent update! This solves a major problem and will save tonnes of time! After testing and reading through your discussion with @theoryshaw I've got a good grasp of this! It's brilliant.

With the new system you now need to copy the folders with the ifc for it to work properly, if you are using default title blocks the only thing you need to copy is the 'layout' folder with the ifc, is it possible to have a file format or option to 'package' that folder and/or the sheets folder with the ifc?

**Comment by Moult** [comment]
If you use the default folder structure suggested in the BlenderBIM Add-on, the folder structure you need to copy is the `sheets`, `layouts`, and the `drawings` folder. You can of course change the structure to put it all in the same folder or same subfolder if you only want to copy one additional folder in addition to the IFC.

There isn't a file format to "package" the IFC with the related documents unfortunately. A ZIP, I guess?

**Comment by brunopostle** [comment]
If you are using Git to manage your IFC project, you would also want to include these resource files in the same repository. So a natural way to pack them all together in a single compressed file is the git 'bundle' format.

**Comment by Plae-Blue-Dot** [comment]
A zip file definitely works, I thought perhaps a .ifczip could be that kind of format but after testing it out it doesn't work without extraction.

**Comment by Plae-Blue-Dot** [comment]
> git 'bundle' format.

That sounds like a winner
