### ISSUE TITLE
Segfault when Python script finishes in particular scenarios due to gc change

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2517]
I run a pretty long script which does a ton of cleaning on work projects. Cleaning involves inserting new elements, reassigning elements, removing elements, and so on. I've noticed that since the gc change when my script finishes it segfaults. If I comment out this line: https://github.com/IfcOpenShell/IfcOpenShell/commit/f41ad0d5de0a82848cf3fecb56b727195135f969#diff-b63197ec4d064fc4387ed3f1b8becdbf26fc1c441afea3a07e701d384134a2f7R120 then it no longer segfaults.

I haven't yet been able to cut it down to a small script (it's a pretty large bespoke script) but thought I'd file this issue first to get the brainstorming juices flowing :)

Note that the script still completes, the segfault seems to occur at the end of the script (presumably when _del_ is being called).

**Comment by aothms** [comment]
Is this with 94ba1a121dcb061773b18a15c08e829a35e66707 and 8dab1810c74082de5c63cd98e3b0d1be8501baa1?

Basically the situation was that before the _ _ del _ _ fixes, no real destructor was ever called. The errors were mostly on shared instances being freed twice.

**Comment by Moult** [comment]
No, it's without that, I'm running https://github.com/IfcOpenBot/IfcOpenShell/commit/fa6bbf2d4a69cb8d1f793b3d4ca86571e9b414e8 from Oct 5 :( is it possible to bump the bot?

**Comment by aothms** [comment]
Started

**Comment by Moult** [comment]
Tested with 'v0.7.0-16b05d99' and still segfaults. I'll try to create a minimal example.

**Comment by Moult** [comment]
Minimal example:

```
import ifcopenshell
import ifcopenshell.api

model = ifcopenshell.open('/home/dion/test2.ifc')
library = ifcopenshell.open("./vicx/lib.ifc")
result = model.add(library.by_type("IfcClassification")[0])
model.create_entity(
    "IfcRelAssociatesClassification",
    GlobalId=ifcopenshell.guid.new(),
    RelatedObjects=[model.by_type("IfcProject")[0]],
    RelatingClassification=result,
)
```

```
$ python segfault.py
[1]    10234 segmentation fault  python segfault.py
```

[lib.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9824957/lib.ifc.txt)

[test2.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9824959/test2.ifc.txt)

**Comment by aothms** [comment]
Should be fixed, bot build started

**Comment by Moult** [comment]
Confirming as fixed! Bumped the builds too.
