### ISSUE TITLE
Errors while building IfcOpenShell in VS

### ISSUE THREAD

**Issue by mlaura1996** [IfcOpenShell/IfcOpenShell#2519]
Dear all, I was building IfcOpenshell in VS, but I am having this type of error: 

![image](https://user-images.githubusercontent.com/99893051/196944143-a3ee7a3d-8850-4947-9ffb-516bfefd81bb.png)

What can it be? Please notice that while configuring on cmake I received this:
![image](https://user-images.githubusercontent.com/99893051/196944463-f664bc73-2c61-4c93-8e5f-823d6fbe258b.png)
![image](https://user-images.githubusercontent.com/99893051/196944526-a4b3ec58-d91d-44ff-9d70-c24b76990e58.png)

**Comment by aothms** [comment]
MSVC 2022 is not supported yet

**Comment by mlaura1996** [comment]
@aothms I am using MSVC 2019 :(

**Comment by aothms** [comment]
@Krande proposed a fix for the boost related regex issues https://github.com/IfcOpenShell/IfcOpenShell/pull/2558#issuecomment-1298368677 Please try with latest v0.7.0.

**Comment by dirkolbrich** [comment]
@mlaura1996 did the proposed try with v0.7.0 compile? Can the issue be closed?

**Comment by Moult** [comment]
Closing as apparently VS builds are working well now https://github.com/IfcOpenShell/IfcOpenShell/discussions/5102
