### ISSUE TITLE
Missing dll exports

### ISSUE THREAD

**Issue by youaresoomean** [IfcOpenShell/IfcOpenShell#252]
Hi,

tiny issue when building as shared library on windows.
IfcParse::read and ::traverse have no IFC_PARSE_API prefix:

```
IFC_PARSE_API IfcEntityInstanceData* read(unsigned int i, IfcFile* t, boost::optional<unsigned> offset = boost::none);

IFC_PARSE_API IfcEntityList::ptr traverse(IfcUtil::IfcBaseClass* instance, int max_level = -1);
```

**Comment by aothms** [comment]
Hi, thanks! You don't want to submit a Pull Request while you're at it? Would be greatly appreciated.

**Comment by youaresoomean** [comment]
Hi, i would but unfortunately i currently dont have git setup (just pulled source via .zip). 
Some more missing exports
```
IFC_PARSE_API void InitStringMap();
IFC_PARSE_API IfcUtil::IfcBaseClass* SchemaEntity(IfcEntityInstanceData* e = 0);
```

**Comment by aothms** [comment]
> Hi, i would but unfortunately i currently dont have git setup

You can also use the github web interface to propose changes. Just hoping to preserve proper author information. If it's too much trouble I will commit the changes. The latter two are in the code generator though: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcexpressparser/templates.py#L51

**Comment by youaresoomean** [comment]
@aothms Sorry that it ended up in two pull requests. But this was the very first time i did this.

**Comment by aothms** [comment]
> Sorry that it ended up in two pull requests

No worries, many thanks!
