### ISSUE TITLE
BlenderBim request - duplicate drawing feature/button

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2520]
At present it is possible to copy a drawing, but it doesn't appear in the drawings tab and it messes up the original drawing. so not an intended feature I think ahah.

In the case of electrical plans, ceiling plans floor layouts, changing scales from 1:100 to 1:50, it's very useful to have a duplicate or a link to a drawing so you don't have to setup CSS, dims, annos, etc again when wanting to create a new one

**Comment by theoryshaw** [comment]
+1
related: https://github.com/IfcOpenShell/IfcOpenShell/issues/2169

**Comment by Moult** [comment]
Just an FYI I'm not ignoring these drawing module bugs just that right now my "headspace" is focused on the modeling module so... :) I'll get there!

**Comment by Moult** [comment]
Whilst implementing this, I've taken the opportunity to make it so that drawings don't load when the project is loaded, but instead on-demand as you activate a drawing. I think this is sensible as even the simplest project will have 8 drawings (plan, 2 sections, 4 elevations, one 3D) at a minimum and it doesn't make sense to saturate the screen with cameras and hundreds of dimensions and labels etc across all drawings.

This naturally has some breakage as portions of the drawing system assumes all drawings are loaded.

**Comment by Plae-Blue-Dot** [comment]
Hey Moult thanks for implementing this! SO excited when I saw the change, I've noticed when duplicating a drawing it does not duplicate the annotations aswell, would it be possible to include them? If I should make this a separate issue, let me know

Also great call on the activating drawings, it will definitely clean up and speed up larger files on first load

**Comment by Moult** [comment]
@Plae-Blue-Dot ah yes, I was debating between duplicating the annotations. I think there should be an option to duplicate with or without annotations. Any suggestions on how to make a nice UI for it? One option is two buttons next to one another but I can't imagine what the other icon would be?

**Comment by Plae-Blue-Dot** [comment]
I think that is a great idea and that 2 buttons would work and if one just had an 'a' on the sheet would clarify the difference for now:

![image](https://user-images.githubusercontent.com/78321676/217463785-bfc8bc92-4f3a-4ec6-92f3-4335ab24cef3.png)

And the tooltip said "duplicate drawing with annotations"

**Comment by Moult** [comment]
For the moment we don't have any custom designed icons (until we find the time to design these icons) so can you suggest any icon from the default blender icon set? (enable icon previews in developer settings in blender then go to the text editor side panel to see icons)

**Comment by Plae-Blue-Dot** [comment]
Oh I see, since you used the copy down icon for the first:
![image](https://user-images.githubusercontent.com/78321676/217475043-31c33b10-af21-4dfd-96e5-3bfa4c35a8b9.png)


 I think this icon would work well as the 'copy with annotations'
 
![image](https://user-images.githubusercontent.com/78321676/217475310-8678a321-25fd-40c1-8e27-e04694b1a0bf.png)

it's called 'file text' I think that conveys the annotation part well even without the arrow, otherwise we could just use 'outliner_data_font' :

![image](https://user-images.githubusercontent.com/78321676/217476494-649ee42f-6ae9-4fd0-8d95-710bb8be9629.png)


I think knowing it is associated with annotations is more important than the arrow

**Comment by Moult** [comment]
I just discovered what I think is an even better solution where it does a little popup where you can toggle annotations with a checkbox :) That way we don't keep on cluttering the UI with more icons.
