### ISSUE TITLE
Slab location not remembered.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2528]
figures [this](https://github.com/IfcOpenShell/IfcOpenShell/pull/2522) PR wasn't going to be that easy. 

location not remember, after move/rotate.
video: https://www.dropbox.com/s/wykfx4i4adkzjyu/2022-10-23_19-33-34_Blender_blender.mp4?dl=0

Not sure what the fix is. :\

**Comment by Moult** [comment]
```
new_matrix = mathutils.Matrix.Rotation(self.x_angle, 4, 'X')
new_matrix.cols[3] = obj.matrix_world.cols[3]
obj.matrix_world = new_matrix
```

**Comment by theoryshaw** [comment]
Thanks @Moult, but unfortunately it still has the same problem.

fyi, I used, `col` instead of `cols`
```
new_matrix = mathutils.Matrix.Rotation(self.x_angle, 4, 'X')
new_matrix.col[3] = obj.matrix_world.col[3]
obj.matrix_world = new_matrix
```

video: https://www.dropbox.com/s/cau57jos8jeivat/2022-10-24_08-45-21_Blender_blender.mp4?dl=0
