### ISSUE TITLE
ImportError: libboost_regex.so.1.58.0: cannot open shared object file on Ubuntu 17.04

### ISSUE THREAD

**Issue by lbj** [IfcOpenShell/IfcOpenShell#253]
Hi. I've followed the instructions under "Compiling on *nix" to build and install ifcOpenShell on my Ubuntu 17.04 machine. I had no error messages during compilation or installation but when I try to import ifcopenshell in python ( 2.7) I get the following error message:

```
>>>import ifcopenshell
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/__init__.py", line 34, in <module>
    from . import ifcopenshell_wrapper
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 28, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_ifcopenshell_wrapper', fp, pathname, description)
ImportError: libboost_regex.so.1.58.0: cannot open shared object file: No such file or directory
----------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/__init__.py", line 40, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'linux/64bit/python2.7'
```

I have the following version of libboost installed:
lrwxrwxrwx 1 root root      24 nov.  12  2016 libboost_regex.so -> libboost_regex.so.1.62.0

Does anyone have some advice for how to resolve the problem? Thanks.

**Comment by aothms** [comment]
> lrwxrwxrwx 1 root root 24 nov. 12 2016 libboost_regex.so -> libboost_regex.so.**1.62**.0

> ImportError: libboost_regex.so.**1.58**.0: cannot open shared object file: No such file or directory

Seems to be two different versions of boost in play here. Does `ldd /usr/lib/python2.7/dist-packages/ifcopenshell/_ifcopenshell_wrapper.so` tell us anything, it doesn't reference both right? Perhaps there is something in `CMakeCache.txt` (in the build directory) that hints at where/which and why these two different boost versions are being picked up.

**Comment by lbj** [comment]
Is there any information I can provide you with to help debugging the problem?

**Comment by aothms** [comment]
Hi, sorry for the late reply. Well those two items mentioned above would certainly help. 

* Output of `ldd /usr/lib/python2.7/dist-packages/ifcopenshell/_ifcopenshell_wrapper.so`
* Contents of `CMakeCache.txt` (in the build directory)

I don't think any of these would contain sensitive matter, but feel free to send them by mail thomas@ifcopenshell.org.

**Comment by lbj** [comment]
Much delayed but perhaps still useful. Here are the files and output you requested. I just made another attempt and the project still compiles and installs fine. When I use python 3 I can import and use ifcopenshell. But it doesn't work under python 2.7.13 so I cannot use it under Freecad (I think). I now get the following error message:

```
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
```
>>> import ifcopenshell
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/__init__.py", line 34, in <module>
    from . import ifcopenshell_wrapper
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 28, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_ifcopenshell_wrapper', fp, pathname, description)
ImportError: libboost_regex.so.1.58.0: cannot open shared object file: No such file or directory
```
```
----------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/__init__.py", line 40, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'linux/64bit/python2.7'
```


Output of `ldd /usr/lib/python2.7/dist-packages/ifcopenshell/_ifcopenshell_wrapper.so`
	```
linux-vdso.so.1 =>  (0x00007ffee0f92000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f065067a000)
	libTKernel.so.10 => /usr/lib/x86_64-linux-gnu/libTKernel.so.10 (0x00007f0650274000)
	libTKMath.so.10 => /usr/lib/x86_64-linux-gnu/libTKMath.so.10 (0x00007f064fe2d000)
	libTKBRep.so.10 => /usr/lib/x86_64-linux-gnu/libTKBRep.so.10 (0x00007f064fb5d000)
	libTKGeomBase.so.10 => /usr/lib/x86_64-linux-gnu/libTKGeomBase.so.10 (0x00007f064f497000)
	libTKGeomAlgo.so.10 => /usr/lib/x86_64-linux-gnu/libTKGeomAlgo.so.10 (0x00007f064ed72000)
	libTKG3d.so.10 => /usr/lib/x86_64-linux-gnu/libTKG3d.so.10 (0x00007f064ea67000)
	libTKG2d.so.10 => /usr/lib/x86_64-linux-gnu/libTKG2d.so.10 (0x00007f064e7f9000)
	libTKShHealing.so.10 => /usr/lib/x86_64-linux-gnu/libTKShHealing.so.10 (0x00007f064e3cc000)
	libTKTopAlgo.so.10 => /usr/lib/x86_64-linux-gnu/libTKTopAlgo.so.10 (0x00007f064df6c000)
	libTKMesh.so.10 => /usr/lib/x86_64-linux-gnu/libTKMesh.so.10 (0x00007f064dcfa000)
	libTKPrim.so.10 => /usr/lib/x86_64-linux-gnu/libTKPrim.so.10 (0x00007f064daa7000)
	libTKBool.so.10 => /usr/lib/x86_64-linux-gnu/libTKBool.so.10 (0x00007f064d51c000)
	libTKBO.so.10 => /usr/lib/x86_64-linux-gnu/libTKBO.so.10 (0x00007f064d15b000)
	libTKFillet.so.10 => /usr/lib/x86_64-linux-gnu/libTKFillet.so.10 (0x00007f064ccaa000)
	libTKOffset.so.10 => /usr/lib/x86_64-linux-gnu/libTKOffset.so.10 (0x00007f064c994000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f064c600000)
	libboost_regex.so.1.58.0 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f064c276000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f064bf6d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f064bd56000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f064b98f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f064b771000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f064b553000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f064b34f000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f064b14c000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f0649695000)
	/lib64/ld-linux-x86-64.so.2 (0x00005569af5d5000)
```


[CMakeCache.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/1475684/CMakeCache.txt)

Is there a way to build only for python 2.7  ?

**Comment by aothms** [comment]
> I've followed the instructions under "Compiling on *nix" 

Well, one option would be to use the build script. It'll take some time building, but everything will be compiled in statically so you'd be free from these kind of issues: `cd nix; python build-all.py`.

> Is there a way to build only for python 2.7 ?

If you use the manual `cmake` `make` combination using packages from your package manager, i.e. the most prominently described option, IfcOpenShell will be compiled for only a single specific python version.

There does not seem to be any reference to `libboost_regex.so.1.58.0` in the CMakeCache file. Did you try simply `make clean` and trying again (or better yet, delete the build directory and start from scratch). There might be some remnants from earlier attempts.

**Comment by Moult** [comment]
Bump @lbj is this still relevant? The build systems and environments have changed significantly since 2017.

**Comment by lbj** [comment]
@Moult This is no longer relevant. My apologies for not closing the issue earlier.
