### ISSUE TITLE
python-ifcopenshell 1.0.5   get_psets missing keyword arguments (linux version)

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2531]

**Comment by vulevukusej** [comment]
probably related to #2532 https://pypi.org/project/python-ifcopenshell/

**Comment by Moult** [comment]
Yeah that version is really ancient and unmaintained.

**Comment by aothms** [comment]
Sorry to reopen, but in response to

> however, the PYPI entry looks very "unofficial"

Source: https://github.com/IfcOpenShell/IfcOpenShell/issues/2506

I tend to agree. Can we copy over the main repo readme.md there somehow?

@sharon-br I see you raised some issues here and you seem to be one of the maintainers of https://pypi.org/project/python-ifcopenshell/

Is there anyway you could see if that repository does still need to be active now that we have https://pypi.org/project/ifcopenshell/ ?

**Comment by Moult** [comment]
Done, I've referenced the top level readme, and also made a proposal to update the readme (prevents duplication of docs, makes clearer the full ecosystem of IOS offerings, etc) in a PR.

**Comment by sharon-br** [comment]
> Sorry to reopen, but in response to
> 
> > however, the PYPI entry looks very "unofficial"
> 
> Source: #2506
> 
> I tend to agree. Can we copy over the main repo readme.md there somehow?
> 
> @sharon-br I see you raised some issues here and you seem to be one of the maintainers of https://pypi.org/project/python-ifcopenshell/
> 
> Is there anyway you could see if that repository does still need to be active now that we have https://pypi.org/project/ifcopenshell/ ?

That repo is no longer needed and I've deleted It to not create confusion.
Thank you for uploading the package to pypi in a more formal way!

**Comment by aothms** [comment]
@sharon-br thanks for the quick action :)
