### ISSUE TITLE
running pip freeze on pip installed ifcopenshell outputs wrong requirement

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2532]
instead of getting "python-ifcopenshell==1.0.5" in the requirements file, we get:

ifcopenshell-python==0.7.0

**Comment by vulevukusej** [comment]
@Andrej730 entirely possible :) - let me recheck and report back

**Comment by vulevukusej** [comment]
ok so you're absolutely right.. so what is "https://pypi.org/project/python-ifcopenshell/" for then?

**Comment by Moult** [comment]
@vulevukusej dunno, it's an unofficial package on pypi and I don't know who created it. I don't recognise any of the three maintainer names. The official one is ifcopenshell.
