### ISSUE TITLE
BlenderBim - IFC4.3 : IfcFixedReferenceSweptAreaSolid Has no Attribut Representations

### ISSUE THREAD

**Issue by jeangual** [IfcOpenShell/IfcOpenShell#2538]
Hi,
when I import with BIMblender the IFC4.3 file attached (Generated by IfcOpenshell)  with a single slab defined by IfcFixedReferenceSweptAreaSolid entity; I have this Error : "IfcFixedReferenceSweptAreaSolid Has no Attribut Representations"
This file has validated by Nist File Analyser and the attribut Representations is not in the Express specifications.

What is wrong? 
[slab.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9868906/slab.ifc.txt)

**Comment by Moult** [comment]
The file is not valid. I've not used the Nist File Analyser before, but it's definitely not valid :)

Here are the validation errors below. You can validate using the IfcOpenShell.validate module (in the BlenderBIM Add-on, just click the "Checkmark" validate icon in the IFC Debug panel. Or you can use https://validate.buildingsmart.org which is also powered by IfcOpenShell so you'd get the same results.

```
2022-10-26 22:37:39,945    ERROR validate.py 342 For instance:
    #20=IfcRelContainedInSpatialStructure($,$,$,$,(#19),#10)
                                          ^                 
With attribute:
    <attribute GlobalId: <type IfcGloballyUniqueId: <string>>>
Not optional

2022-10-26 22:37:39,946    ERROR validate.py 357 For instance:
    #19=IfcSlab('3PUPZxyV5AH9apSmZ4gUHA',$,'Dalle','Dalle rectangulaire',$,#11,#18,$,.FLOOR.)
                                                                               ^^^           
With attribute:
    <attribute Representation?: <entity IfcProductRepresentation>>
Value:
    #18=IfcFixedReferenceSweptAreaSolid(#17,#11,#13,$,$,$)
Not valid

2022-10-26 22:37:39,947    ERROR validate.py 357 For instance:
    #18=IfcFixedReferenceSweptAreaSolid(#17,#11,#13,$,$,$)
                                            ^^^           
With attribute:
    <attribute Position?: <entity IfcAxis2Placement3D>>
Value:
    #11=IfcLocalPlacement($,#3)
Not valid

2022-10-26 22:37:39,947    ERROR validate.py 342 For instance:
    #18=IfcFixedReferenceSweptAreaSolid(#17,#11,#13,$,$,$)
                                                        ^ 
With attribute:
    <attribute FixedReference: <entity IfcDirection>>
Not optional

2022-10-26 22:37:39,947    ERROR validate.py 342 For instance:
    #17=IfcRectangleProfileDef($,$,#16,7.,0.5)
                               ^              
With attribute:
    <attribute ProfileType: <enumeration IfcProfileTypeEnum: (AREA, CURVE)>>
Not optional

2022-10-26 22:37:39,949    ERROR validate.py 342 For instance:
    #8=IfcOwnerHistory($,$,$,$,$,$,$,$)
                       ^               
With attribute:
    <attribute OwningUser: <entity IfcPersonAndOrganization>>
Not optional

2022-10-26 22:37:39,949    ERROR validate.py 342 For instance:
    #8=IfcOwnerHistory($,$,$,$,$,$,$,$)
                         ^             
With attribute:
    <attribute OwningApplication: <entity IfcApplication>>
Not optional

2022-10-26 22:37:39,949    ERROR validate.py 342 For instance:
    #8=IfcOwnerHistory($,$,$,$,$,$,$,$)
                                     ^ 
With attribute:
    <attribute CreationDate: <type IfcTimeStamp: <integer>>>
Not optional
```

**Comment by aothms** [comment]
So in particular, highlighting from the text above

```
2022-10-26 22:37:39,946    ERROR validate.py 357 For instance:
    #19=IfcSlab('3PUPZxyV5AH9apSmZ4gUHA',$,'Dalle','Dalle rectangulaire',$,#11,#18,$,.FLOOR.)
                                                                               ^^^           
With attribute:
    <attribute Representation?: <entity IfcProductRepresentation>>
Value:
    #18=IfcFixedReferenceSweptAreaSolid(#17,#11,#13,$,$,$)
Not valid
```

You're missing a couple of indirections. IfcProduct - IfcProductDefinitionShape - IfcShapeRepresentation - IfcRepresentationItem.

You jump straight from IfcProduct to IfcRepresentationItem

**Comment by jeangual** [comment]
Thanks for the link to Ifcopenshell validate tool. I am looking for the 
good representation entity.
Please where we can find a full Ifcopenshell user guide?
Thanks



Le 31/10/2022 14:39, > notifications a écrit :

**Comment by aothms** [comment]
This is more related to the IFC standard than IfcOpenShell. It's a bit dated but in case you haven't already, this guide might cover some of it https://standards.buildingsmart.org/documents/Implementation/IFC2x_Model_Implementation_Guide_V2-0b.pdf

**Comment by Moult** [comment]
@jeangual have you tried using the IFC Debug tool in the BlenderBIM Add-on? It lets you graphically "step through" the IFC relationships and if you load up an existing IFC it is a great way to learn through practical example how things are defined.
