### ISSUE TITLE
[blenderbim] wall mitre glitch

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2541]
This did work recently, but now every time I try and mitre two walls they get offset like so:

![cube](https://user-images.githubusercontent.com/1747315/198217043-7098e9b0-6460-4c0f-9639-b7afcddc5d10.gif)

[Test file: cube.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9876664/cube.ifc.txt)

**Comment by Moult** [comment]
It's part of the "Generate Digital Twin" feature which thinks your building is too small.
