### ISSUE TITLE
move an ifcwindow/ifcdoor, can the ifcopeningelement move with it?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2542]
dumb question, if you move an ifcwindow/ifcdoor, can the ifcopeningelement move with it?  Doesn't seem so, but I might be missing something. 

If not, is that in the roadmap?

**Comment by Moult** [comment]
Shift-G to regenerate after moving the window/door.

**Comment by theoryshaw** [comment]
hmm... missing something?
https://www.dropbox.com/s/yb69kig4kudjqu1/2022-10-27_20-55-42_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
@theoryshaw did you try regen on the window object, not the wall object?

If that's the case good point we should make regenerating the wall also refresh fills.

**Comment by theoryshaw** [comment]
yep, sorry, silly me.  But yes, i guess regenning the wall, as well, would be nice.
