### ISSUE TITLE
Blenderbim: Opening on sloped wall

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#2543]
When I apply an opening to a sloped wall the wall jumps back to a vertical position.

**Comment by Moult** [comment]
@TZwielehner I can't recreate this bug. What steps are you doing? Here's what I tried.

1. Load demo library
2. Activate BIM tool, choose wall. change slope to 20 degrees, draw wall
3. Click wall, Shift-O.
4. Shift select opening and wall, Shift-O.

Can you try with the latest unstable release? Or perhaps join osarch.org/chat and screenshare?

**Comment by Moult** [comment]
@TZwielehner can you help provide more information?

**Comment by TZwielehner** [comment]
Tried to reproduce it today, but couldn't. Will close it therefore.
