### ISSUE TITLE
Blenderbim : Material Layer editing gets permanently disabled when unassigning a material without first closing the layer editing state

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#2546]
Sorry for the mouthful. I believe this video is self-explanatory :

![Animation2](https://user-images.githubusercontent.com/25156105/198585034-b75b6ad6-f330-4dd9-90e5-e8255be2c15a.gif)

I think closing the edition of a material should also close the edition of its material layer if it's open.

However there is a couple of cases :
- The user validates the edition of the material :
![image](https://user-images.githubusercontent.com/25156105/198585447-cf9e6a6d-1741-4dbd-bd9f-c3ba53d1d535.png)
Should the material layer edition be validated or discarded ?
- The user cancels the edition of the material :
![image](https://user-images.githubusercontent.com/25156105/198585536-6953ab0f-8cc5-492f-9e95-fb16aa14f4c3.png)
Here I think the material layer edition should be discarded.

Happy to work on it if need be.

**Comment by Moult** [comment]
Great catch! I definitely agree with the second where the layer edition is discarded, for the first I'm not sure which. Choose whichever you feel would be more intuitive and go for it!

**Comment by Gorgious56** [comment]
After reflection it seemed logical that all child editors would be validated when the user validates the top level editor, and conversely child editions would be discarded if the user discard the top level one.
