### ISSUE TITLE
Missing attributes in Steel profile IFC library from BOLTS

### ISSUE THREAD

**Issue by Jesusbill** [IfcOpenShell/IfcOpenShell#2556]
Looking at the IFC library from [this work](https://github.com/IfcOpenShell/IfcOpenShell/commit/ebf3cd8909d4869ef4129aa035d0eeef9f2484e0) I notice that [I profiles](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/scripts/generate_steel_profiles_library.py#L71) are missing the "r": "FilletRadius" attribute for all the classes, except for "ibeam_inp" class, which sadly has ["r1 r2 hw f g"](https://github.com/boltsparts/BOLTS/blob/master/data/profile_i.blt#L424) as extra parameters instead of "r". I believe r2 -> FilletRadius and r1-> FlangeEdgeRadius. FlangeSlope attribute should be calculated from a combination of the rest I guess.

**Comment by Moult** [comment]
Also just to add this in it would be good if the ProfileName=prof_name here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/scripts/generate_steel_profiles_library.py#L122

**Comment by Andrej730** [comment]
[03781bd](https://github.com/IfcOpenShell/IfcOpenShell/commit/03781bdf9b68e36e7ac4750589193d8aabc9763b) Fixed profile names and added radius data to the profiles where it was possible
