### ISSUE TITLE
BlenderBIM: aggregated text annotation

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#2561]
Now that I found out about multiline text annotations (using "\n") I wondered if there is a way to create a "bit" more complex ones like this:

https://www.vectorworksforum.eu/uploads/monthly_2012_05/2.jpg.ddc361830998c01b41267604033bafb9.jpg

If each property had a way to identify it in svg (e.g. by passing the originating property as a class) then that would "just" be a matter of css (make room name larger, add prefix?), right?

Edit: prefix is not supported it seems, only in html. Really a pity...

**Comment by Moult** [comment]
@Andrej730 is this one done? If so I'll create a few symbols, I'm thinking a door tag is the obvious one, and a room tag is also obvious (name, longname, or maybe name, longname, grossarea)
