### ISSUE TITLE
Duplication of globalid for a splitted IFC element

### ISSUE THREAD

**Issue by Adeniyi-Bella** [IfcOpenShell/IfcOpenShell#2563]
So, I was trying to split an IFC element (A from the image below), into two separate IFC elements (A1 and A2). 
Splitting was done successfully with the bisect tool in Blender bim. IFC File was exported and imported into a different IFC viewer. Only one of the elements was visible (A1 or A2). Apparently, both A1 and A2 shared the same globalid after the splitting. Manually changing the id does not work as changing one element automatically updates the other element. Any suggestion on how to avoid this behavior?

![IMG_20221028_120134](https://user-images.githubusercontent.com/37347588/199496714-fe7dd028-f867-4a96-87ff-c9ba6f23501c.jpg)

**Comment by Moult** [comment]
If you duplicate an object in blender, then they will be separate objects, which you can then cut each one.

However, if you start with one and use Blender's various ways of splitting (separate, bisect, etc) then you have the responsibility to duplicate the object manually. In the Object Properties > IFC Object Metadata > IFC Class press the "Copy Class" button and that'll make them separate objects.

**Comment by Adeniyi-Bella** [comment]
Thanks for the response. The first option (duplicating the object) solved the problem for me.
