### ISSUE TITLE
Correct definition of IfcDistributionSystem 'HasPorts'

### ISSUE THREAD

**Issue by DaJansenGit** [IfcOpenShell/IfcOpenShell#2566]
We are currently working on the implementation of `IfcDistributionSystem` into a HVAC author software. When exporting the current IFC model and importing it in Python with IfcOpenShell we get the following error:

```entity instance of type 'IfcDistributionSystem' has no attribute 'HasPorts'```

We were not able to find a definition of `HasPorts` inside the IFC Schema. Could you point us to the reason why IfcOpenShell is missing some information in our defined `IfcDistributionSystem`.

A minimal example where the problem occurs can be found [here](https://rwth-aachen.sciebo.de/s/ZwVAbO3PEqcKQXD)

The definition of an `IfcDistributionSystem` can be found in the following line, among others. 

```#29323 = IFCDISTRIBUTIONSYSTEM('3StAs11_jcbqELm66WhPJB', #2, 'Heizung_RL', 'Luftart/Medium', $, $, .HEATING.);```

**Comment by aothms** [comment]
This is not an issue with the model, but an issue with the code. Your code is requesting an attribute HasPorts on an entity instance that doesn't have that attribute.

**Comment by DaJansenGit** [comment]
You are absolutely right 🤦  Sorry for opening the issue. The query is still from the access before the change to `IfcRelNests`.
