### ISSUE TITLE
[blenderbim] Debug panel no longer allows entity browsing

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2569]
With the latest blenderbim, the Debug panel still lists attributes and references for the selected entity, but previously these references had a link to load them in the Debug panel - allowing the user to drill down through the structure of the file.

Now there are no links, the user has to note the step-id and do another search:

![Screenshot from 2022-11-06 10-16-58](https://user-images.githubusercontent.com/1747315/200165677-92767188-be66-4fc9-9dbb-419556cfde82.png)

**Comment by Moult** [comment]
I thought I had already fixed this just before the release. I'll check again tomorrow.

**Comment by brunopostle** [comment]
My build is 0142bfa, but if you fixed it later in cbd9c89 then the bug can be closed

**Comment by Moult** [comment]
Yes, the fix was in that commit: https://github.com/IfcOpenShell/IfcOpenShell/commit/cbd9c898c37bb44500bf3be39c87241cfd8a4fe1#diff-8c3dd5d968cdeffccfd25969c0a45144d36d1f6ea5bae2099ae2be4d0767d637
