### ISSUE TITLE
Parent IfcWindow/Door to IfcWall. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2570]
Think it would be nice to Parent IfcWindow/Door to IfcWall. 

Figured if we put the following [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/model/opening.py#L67), it works.
`filling_obj.parent = voided_obj`

But couldn't figure out where to recreate these parent relationships upon IFC import.  Any hints?  That is, if you think this is a good idea?

**Comment by Moult** [comment]
I don't think this is a good idea because it doesn't scale, parenting thousands of objects is pretty nasty on large models. This is what the Alt-D hotkey in the BIM Tool should solve, if you want to move children along with the parent.

**Comment by theoryshaw** [comment]
Gotcha... thx.  
Would be nice to avoid having to hit alt-d everytime you want to move/rotate a wall that has windows/doors in it. 
wondering if alt-d could be bound somehow, by default, to the move/rotate command.

**Comment by theoryshaw** [comment]
...or use the shift-g(regen) approach after moving the doors/windows?

It would seem, in the future roadmap, that the shift-g would happen automatically after a move/rotate/align.
