### ISSUE TITLE
ifcopeningelement doesn't delete

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2573]
ifcopeningelement doesn't delete...
video: https://www.dropbox.com/s/8lueuil5dxxmcx4/2022-11-07_08-29-20_KeyShowView_Carnac.mp4?dl=0

**Comment by theoryshaw** [comment]
probably related to #2572

**Comment by theoryshaw** [comment]
I narrowed this problem down to CAD_Sketcher. Not sure what the problem is.
should i close?

**Comment by Moult** [comment]
Yes, I think this is another situation of #2645.
