### ISSUE TITLE
BlenderBim : error wheninstalling the latest version of BimBlender

### ISSUE THREAD

**Issue by jeangual** [IfcOpenShell/IfcOpenShell#2574]
Hi
 I have an error when i install the latest version of BimBlender.
The log is attached.
Thank you for your help.

<img width="611" alt="bug Bim blender install latest release" src="https://user-images.githubusercontent.com/116723023/200360597-c8313c58-d81b-4e7f-a2af-3b9fada48394.png">

**Comment by theoryshaw** [comment]
Did you install it via the **unstable-installation** approach?
https://blenderbim.org/docs/devs/installation.html#unstable-installation

**Comment by Moult** [comment]
I just tested on Blender 3.3 and the latest stable release and was not able to recreate your issue. Try renaming your `C:\JUsers\jean.gual\AppData\Roaming\Blender Foundation\Blender\3.3` folder to `3.3backup` or something, and try again (this will ensure a clean setup).

**Comment by jeangual** [comment]
Ok I installed the plugin with this rename.
Thank you verymuch.



Le 08/11/2022 00:08, > notifications a écrit :
