### ISSUE TITLE
Adding new wall

### ISSUE THREAD

**Issue by HaritonovAlexander** [IfcOpenShell/IfcOpenShell#2579]
Adding new walls seemed to work for a while then all of a sudden I get this error message. Reinstall didn't help at all.

[ADDING NEW WALL ISSUE_version0221105.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9959453/ADDING.NEW.WALL.ISSUE_version0221105.txt)

**Comment by Moult** [comment]
Do you have any greasepencil in your scene?

**Comment by HaritonovAlexander** [comment]
none

**Comment by HaritonovAlexander** [comment]
sorry I just checked again. Turns out the measurement object/the default built-in/ looks like indeed a grease pencil object, because after I deleted it the adding works again.

**Comment by Moult** [comment]
Ah OK let's leave this issue open to address that.
