### ISSUE TITLE
duplicate object => duplicates globalID

### ISSUE THREAD

**Issue by stefbulcke** [IfcOpenShell/IfcOpenShell#2583]
when duplicating an object, the ifcdata is duplicated as well, which is a good thing.  However, the exact globalID gets duplicated as well. I assume the exporter only exports only one object per GlobalID  (i.e. missing/disappearing al together).

Would it be possible to create an new GlobalID on duplicating an object in Blender?
Grtz

**Comment by Moult** [comment]
It should already do this.

Do you have other addons enabled, like blender gis? Can you try disabling them and testing with factory settings?

I'll check this out tomorrow.

**Comment by stefbulcke** [comment]
Hi Dion,

I disabled all add-ons and indeed…

I put (some of) them back on and duplication now still works correctly so I can not ‘duplicate’ the situation to tell which add-on could be responsible.  I’ll keep an eye on it…


Thanks for the swift reply.

Stef

**Comment by theoryshaw** [comment]
@stefbulcke, Do you have CAD_sketcher by any chance?

**Comment by Moult** [comment]
Closing as cannot be recreated.
