### ISSUE TITLE
Join not working properly

### ISSUE THREAD

**Issue by Adeniyi-Bella** [IfcOpenShell/IfcOpenShell#2587]
I have this problem when trying to join two elements. I have a slab like in stage 1, and I intend to cut this slab like in stage two. Since I am using the blender bisect tool, i duplicated the object for every cut and I was able to get to stage 3. So this worked pretty fine when I exported in blender to another IFC viewer. In blender, I joined G to E and F to D, so I am back to stage 2 after making this join. I again exported in blender and imported in another IFC viewer, but I still ended up with stage 3. So, in blender I am in stage 2 but in another viewer, I am in stage 3. I am not sure why the join seems not to be working, but can I achieve this differently? 
Thanks
![Untitled Diagram](https://user-images.githubusercontent.com/37347588/201134208-e2716ced-1e8e-48a7-b626-051228d88b54.jpg)

**Comment by theoryshaw** [comment]
Is it possible to either do a videocast of your process, and/or share the ifc file?

Also, Are you using ifcslabs that are connected to an ifcslabtype?

**Comment by theoryshaw** [comment]
also, after using the bisect tool.. do you update the representation?
and make sure your 'new' ifcslabs have different guids?

![image](https://user-images.githubusercontent.com/507113/201530632-1a7eea95-0f66-4277-ad3f-c8fca169f80a.png)

![image](https://user-images.githubusercontent.com/507113/201530717-8727bc45-a5f3-43e1-9e84-12bd2e636c3b.png)

**Comment by Adeniyi-Bella** [comment]
Thanks for the feedback. The update representation button fixed my problem. But, I am not sure if I have to specifically use the update representation button or not every time I bisect. My approach is to create a duplicate of the element I want to bisect which automatically gives it a new globalId. Would that not be the whole purpose of the update representation button or it comes with extra functionalities?

**Comment by Moult** [comment]
Joining has now been implemented :)
