### ISSUE TITLE
IfcConvert svg - Not working when building has no storey

### ISSUE THREAD

**Issue by Francois-Thierry** [IfcOpenShell/IfcOpenShell#259]
Hello everyone,

This is my first intervention here so I will start by congratulate you for all the work that you have done. I'm using ifcopenshell since two months and I'm really found of it.

I have an IFC file that has no storey attached to the building, all the elements are directly related to the building itself. I found that the conversion to svg is not working. As I understand from the source code, ifcconvert is iterating over the decomposing element to find the parent IfcBuildingStorey. Maybe it can find the parent IfcBuilding if there is no IfcBuildingStorey ?

I also have a subsidiary question regarding IfcConvert, I'm using it to convert ifc files to the collada format. For large files it can take quite some time. Would it be possible to accelerate the conversion process using multithreading for instance ?

Thanks in advance, best regards.

**Comment by ylcnky** [comment]
A similar issue I had. In my case, the designer stored the all spaces in a separate IFC file. Basically, the other files (MEP, STRUC, etc.) have IfcBuildingStorey, but no space. When I try to generate SVG file with `--include --entities` in STRUC model, but conversion didn't happen and gave error.
I agree that separating spaces in a different IFC file is not a common practice so maybe the IfcOpenShell development shouldn't be reconfigured based on these individual scenarios.

**Comment by aothms** [comment]
> Maybe it can find the parent IfcBuilding if there is no IfcBuildingStorey

I think that is a reasonable solution. I will implement something like that.

> Would it be possible to accelerate the conversion process using multithreading for instance ?

Work on this is being done here: https://github.com/sanderboer/IfcOpenShell/tree/multithreading

**Comment by aothms** [comment]
Fixed in f64246f. Thanks for reporting this. Are you able to compile and test yourself?
