### ISSUE TITLE
BlenderBIM: seg fault on when changing app template

### ISSUE THREAD

**Issue by canonex** [IfcOpenShell/IfcOpenShell#2593]
Blender crash if BlenderBim is activated when changing application template.

I did a small video showing the issue:
https://user-images.githubusercontent.com/1444378/201642101-15115e2c-6eab-4db9-acee-2090ac854856.mp4

I attach the blender.crash.txt.
[blender.crash.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10002214/blender.crash.txt)

My OS is:
Linux Debian GNU/Linux bookworm/sid
X11, NVIDIA GeForce GTX 1060 with Max-Q Design / Mesa Intel® UHD Graphics 630 (CFL GT2)
The crash is not dependent from video drivers, it crash both on Nvidia and Nouveau.

Thank you,
Riccardo

**Comment by Moult** [comment]
@canonex I can't recreate the issue. Can you try again?

Perhaps ping @myoualid @theoryshaw can you also try recreating this issue?

**Comment by myoualid** [comment]
no bugs for me with an Nvidia

**Comment by canonex** [comment]
Thanks, the bug is quite "old" and I have since updated Debian, Nvidia drivers and BlenderBim version.
I no longer get the error in question, so it is possible for me to close this bug.

Thanks again,
Riccardo

**Comment by canonex** [comment]
No, I have to

**Comment by Moult** [comment]
@canonex can you try on a vanilla blender? (Rename your 3.4 Dir temporarily). If it still breaks, can we organize a screen share to debug? I'm available in the Sydney Australia timezone.

**Comment by canonex** [comment]
Vanilla it works.
I have a very, too, long list of addons. I try to find the culprit...

**Comment by Moult** [comment]
@canonex in that case I think this is a duplicate of this bug: https://github.com/IfcOpenShell/IfcOpenShell/issues/2645
