### ISSUE TITLE
ifcopenshell.geom.create_shape not working for some elements

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#2595]
I tried to create shapes for some elements in [my IFC file](https://github.com/CrossStyle/MEP2BIM/blob/main/demo1/demo1.ifc). I run the following code and encountered some errors. Is it there are problems with my files? BTW, what does 'Token $ at 1124960' mean? Thank you.
```
import ifcopenshell.geom
_ifc_file = ifcopenshell.open('../upload/demo1/demo1.ifc')
elements = _ifc_file.by_type("IfcBuildingElementProxy")
settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, elements[0])
```

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\test\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2022.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\code\cad\src\topology_recognition\tmp.py", line 135, in <module>
    shape = ifcopenshell.geom.create_shape(settings, elements[0])
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ifcopenshell\geom\main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 2315, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Token $ at 1124960 invalid instance name
```

**Comment by Moult** [comment]
At a guess your file may be invalid. Can you share your file or check validity using ifcopenshell.validate? You can also validate it graphically using the BlenderBIM Add-on.

In vim you can use `112490 go` to go to the character at byte 112490, if you copy paste the lines around that we can also take a closer look.

**Comment by CrossStyle** [comment]
@Moult Hi, thanks for your quick response. I have shared my files [in this link](https://github.com/CrossStyle/MEP2BIM/blob/main/demo1/demo1.ifc).

**Comment by aothms** [comment]
ifcopenshell.validate reports many instances of:

```
For instance:
    #22688=IfcShapeRepresentation($,'Facetation','SurfaceModel',(#22687))
                                  ^
With attribute:
    <attribute ContextOfItems: <entity IfcRepresentationContext>>
Not optional
```

Going to character offset 112490  (Notepad++ Ctrl G) points to the same issue.

So indeed the file is invalid, shape representations need to have an associated context.

**Comment by CrossStyle** [comment]
@aothms Thanks for the info. After I modified the IFC files, the function now `ifcopenshell.geom.create_shape` works for every element.
