### ISSUE TITLE
new CharacterDecoder.cpp

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#26]
Hi Thomas,

thanks for your create work.
I just tried the 0.5.dev Version on GitHub.
If i use the last changes in CharacterDecoder.cpp, some Archicad Version 19 Ifc Modells don't work anymore.
Sometimes a lot of IfcProducts are missing, sometimes it can't find anything anymore.

[TPO BIB-Gebaeude - Testdatei CKi_Teilausschnitt.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/104907/TPO.BIB-Gebaeude.-.Testdatei.CKi_Teilausschnitt.zip)

In the same file are some walls which are not correctly clipped. Maybe you know the reason why?

![image](https://cloud.githubusercontent.com/assets/1086380/12581302/0dd88c38-c436-11e5-9466-81219e6327a2.png)

kind regards,

Christian

**Comment by aothms** [comment]
Hi,

Thanks for this. Indeed a blatant bug was introduced. It's fixed here https://github.com/IfcOpenShell/IfcOpenShell/commit/fe70acb541d1fec9685f63d3c00f33033f42ea37

As for issues with wall subtractions. There is are some boolean operands defined that as boundary representations that violate the standard [1]. For example for IfcClosedShell `#96789` the are some intersecting faces and other errors. This confuses Open Cascade up to the extent it is not able to perform the boolean operations. Of course there may be ways to make this more robust, but in this particular case the file is not without flaws.

[1] http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifctopologyresource/lexical/ifcclosedshell.htm

Kind regards,
Thomas
