### ISSUE TITLE
'Apply void' is missing 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2601]
'Apply void' is missing.
https://www.dropbox.com/s/9s3o8p3f6kfbpzr/2022-11-17_08-08-14_Blender_blender.mp4?dl=0

**Comment by Gorgious56** [comment]
You need to 
1. Click the void object to select it
2. SHIFT + Click the wall to add it to the selection and make it active

In that order. Then you will be able to apply the void. Make sure only these two objects are selected or else it won't work.

**Comment by theoryshaw** [comment]
aha!... i'm an idiot, i think i knew this at one point, and forgot. 

> @Moult In order to be less confusing maybe we could make "Add Void" and "Apply void" two separate buttons in the toolshelf.

Agree this would be a good idea. 

Also, for consistently, i think the void should be automatically applied to the wall when spawned, as is the case with ifcwindows/doors.
