### ISSUE TITLE
(util/element.py) get_properties throws an error if prop.EnumerationValues is None

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2602]
When IfcPropertyEnumeratedValue.EnumerationValues is None, then this [line ](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/element.py#L103) throws a TypeError: "NoneType" object is not iterable.

According to [bs](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/schema/ifcpropertyresource/lexical/ifcpropertyenumeratedvalue.htm) EnumerationValues is optional though.  I propose changing the line to something like:

`[v.wrappedValue for v in prop.EnumerationValues] if getattr(prop, "EnumerationValues") else None`

Any objections?

**Comment by aothms** [comment]
No objections. +1 from me.

The getattr is probably not necessary:

    [v.wrappedValue for v in prop.EnumerationValues] if prop.EnumerationValues else None
