### ISSUE TITLE
Annotations not showing in viewport

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#2603]
I'm following the the [Tutorial](https://www.youtube.com/watch?v=xWPLZK_WoS8) from [IFC Architect](https://www.youtube.com/channel/UCnl3Zvy78lNfGIYLBxAu5-g) on youtube and ran into the following issue: 

As soon as i enable viewport annotations, i get a error in the terminal and annotations only show up as lines. 
Annotations look right on the SVG drawing. 

<img width="683" alt="Screenshot 2022-11-17 at 20 13 11" src="https://user-images.githubusercontent.com/67860835/202537703-d8e5fed1-3010-47bc-8b71-29c599440efd.png">

```
ERROR (gpu.shader): pyGPUShader VertShader: 
      | 
   59 |     out vec4 gl_Position;
      | 
      | Error: Regular non-array variable 'gl_Position' may not be redeclared
      | Error: 'gl_Position' already declared within an interface block

Traceback (most recent call last):
  File "~/Library/Application Support/Blender/3.3/scripts/addons/blenderbim/bim/module/drawing/prop.py", line 209, in toggleDecorations
    decoration.DecorationsHandler.install(context)
  File "~/Library/Application Support/Blender/3.3/scripts/addons/blenderbim/bim/module/drawing/decoration.py", line 1609, in install
    handler = cls()
  File "~/Library/Application Support/Blender/3.3/scripts/addons/blenderbim/bim/module/drawing/decoration.py", line 1621, in __init__
    self.decorators = [cls() for cls in self.decorators_classes]
  File "~/Library/Application Support/Blender/3.3/scripts/addons/blenderbim/bim/module/drawing/decoration.py", line 1621, in <listcomp>
    self.decorators = [cls() for cls in self.decorators_classes]
  File "~/Library/Application Support/Blender/3.3/scripts/addons/blenderbim/bim/module/drawing/decoration.py", line 131, in __init__
    self.shader = GPUShader(
Exception: Shader Compile Error, see console for more details
File "~/Library/Application Support/Blender/3.3/scripts/addons/blenderbim/bim/module/drawing/prop.py", line 202, in toggleDecorations

```

Blender version: `3.3.1` and `3.3.2`
BlenderBIM: `blenderbim-221116-py310-macosm1` and `blenderbim-221117-py310-macosm1`

**Comment by theoryshaw** [comment]
can you share the .ifc file, and perhaps do a videocast of the problem?

**Comment by Gorgious56** [comment]
It may be a hardware problem, do you have a dedicated GPU ? I see you're using macOS, it may not be supported on that platform.

**Comment by theoryshaw** [comment]
Thanks @smr02, that video was helpful. 
Unfortunately, I can't replicate your bug on my side. Windows machine.

**Comment by smr02** [comment]
@Gorgious56 i've changed my cpu settings and it does not make any difference. 

<img width="486" alt="image" src="https://user-images.githubusercontent.com/67860835/202843922-b6692c2a-a990-4dda-bb9e-f1dc53fbb4b0.png">

It may be a problem with it being macOS on a mac M1. Maybe someone else on macOS can test it? There is one other comment under the youtube video which seems to describe the same problem. 

How can I test if it's a problem with Blender for Apple Silicon?

**Comment by ChubbyQuark** [comment]
This looks to be a duplicate issue from: [Missing viewport annotation decorations #2251](https://github.com/IfcOpenShell/IfcOpenShell/issues/2251#issue-1289264776)

Running on older mac hardware but same result of annotations not showing within the viewport.

**Comment by JanFilipec** [comment]
I have the same issue, but a different error:
'gl_FragCoord' : gl_FragCoord must be in vec4

![grafik](https://user-images.githubusercontent.com/67052298/210238666-84f52552-5467-47aa-9d12-83ae83db5e37.png)

Win10 Blender 3.4.1.0 (but tested others as well) BBIM 221110 (also tested other ones)

**Comment by ChubbyQuark** [comment]
Hi Dion,
I've just tried with the latest BB (230127) and factory reset but no
change. This is on a M1 MacBook Pro but had the same issue on a previous
Intel based Mac. I also have a windows machine that displays the
annotations as expected.

Steps are:


   - Install Add-on
   - Create new project (with Demo library)
   - Create drawing
   - Activate drawing
   - Add dimension/annotation
   - Enable viewport annotations.


Happy to jump on a call to help bedug.


[image: image.png]

**Comment by Moult** [comment]
@ChubbyQuark adding a dimension/annotation should automatically enable viewport annotations, so that final step shouldn't be necessary. Also, does it matter whether you use the demo library or a blank project?

Yeah, let's organise a call, I'm in the Sydney Australia timezone, is there a time that works for you ideally between 9am and 5pm Sydney time?

**Comment by ChubbyQuark** [comment]
Its the same result without the demo library.

Im in the UK, so 9:00am Sydney time is probably best for me. Tuesday/weds.
Morning (Sydney time) next week anygood?

In the meantime ill share a small test file with you.

**Comment by Moult** [comment]
Sounds good :) How about 9am Tuesday Sydney time? We can meet at https://meet.jit.si/openbim

**Comment by ChubbyQuark** [comment]
Great, see you there. Have a good weekend.

**Comment by Moult** [comment]
Removed the variable definitions which seems to fix it: https://stackoverflow.com/questions/8691849/glsl-global-variables

**Comment by kijensky** [comment]
Unfortunately, the issue still persists on Apple Air M2 (2022). 

What is new, I am not getting any errors in the terminal. 

Annotation (text) is missing in the viewport but is rendered in SVG export. 

<img width="522" alt="image" src="https://user-images.githubusercontent.com/24612994/236760007-aef8b1f0-0d33-4f2a-9050-02e58e4c024e.png">

<img width="456" alt="image" src="https://user-images.githubusercontent.com/24612994/236760995-57a4c1ff-4e58-4f68-a235-171ae8ffa680.png">


Blender 3.5.1
BIM 0.0.230507

Chip:	Apple M2
Total Number of CPU Cores:	8 (4 performance and 4 efficiency)
Memory:	16 GB
System Firmware Version:	8422.100.650 (latest)
Total Number of GPU Cores:	10
Metal Support:	Metal 3

**Comment by Moult** [comment]
@kijensky indeed, that is most likely due to this new issue #2897 in the migration to the new Blender GPU library.
