### ISSUE TITLE
USER DEFINED ifcFURNITURETYPE;  Not being able to save IFC file, only blender File (Blender 3.3)

### ISSUE THREAD

**Issue by R2naizr** [IfcOpenShell/IfcOpenShell#2604]
I've created an ifcFurnitureType, pasted in an ifc object and tried to save it. Unfortunately only the blend. file is saved. the ifc gives a pop up error and doesn't save. I am only able to save the ifc after closing the blend. file and reopening and then saving again.

**Comment by theoryshaw** [comment]
Can you provide a more step by step, or better yet, a video screencast of the problem?... and the error message?

Also, copying and pasting IFC objects from one file to another does not work.  If that's what you did.

**Comment by R2naizr** [comment]
![image](https://user-images.githubusercontent.com/79116991/202610131-9bc4a2f3-dc50-4d8e-b635-8041efc7e3f2.png)
I copy an object from another file

![image](https://user-images.githubusercontent.com/79116991/202610403-3a3107ae-6201-45d0-a330-8476004b2818.png)
I paste the object in another blender file and create an ifcProject

![image](https://user-images.githubusercontent.com/79116991/202610522-168e9dc4-7304-4de6-976c-64d5eb7534d2.png)
I unlink the current class

![image](https://user-images.githubusercontent.com/79116991/202610618-5158c473-f49d-48ef-a826-7f8e53257221.png)
and assign the proper class

![image](https://user-images.githubusercontent.com/79116991/202610798-a1c6cf78-1be7-4b65-a61d-718dcb12eee6.png)
when I click Assign IFC Class, I get this error

![image](https://user-images.githubusercontent.com/79116991/202610942-af5380a8-3061-4dd1-88dc-57ae4b008b1b.png)
and I try to save the IFCproject in a library

![image](https://user-images.githubusercontent.com/79116991/202611171-5d559e1a-c230-4cac-bd23-7d818b299226.png)
after selecting a location (for this example, my desktop) I get this error message and no IFC file is saved

**Comment by theoryshaw** [comment]
Unlink the ifclass 'before' you copy it.

**Comment by R2naizr** [comment]
Thanks, 
that works ok

**Comment by Gorgious56** [comment]
While copy/pasting looks like it is supported, I think you should be using the "Ifc Project Library" subpanel in the scene properties to import external types. Any IFC file can be used as a library. You can then append your type from there.

![image](https://user-images.githubusercontent.com/25156105/202718932-a810c16e-529e-443e-929c-b2d9d51df1d6.png)
