### ISSUE TITLE
Process relation result in translated objects for IFC file from Revit

### ISSUE THREAD

**Issue by ejnaren** [IfcOpenShell/IfcOpenShell#261]
When importing attached ifc file with the "process relations" option checked, all the geometry is translated or not translated to the right position.
Importing without the process relation option gets the position right.

The ifc file is attached as well as the resulting (bugged) blend file.
I have attached a system-info file as well.

The error message reads:
"
Traceback (most recent call last):
  File "C:\Users\Ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_ifc\__init__.py", line 264, in execute
    if not import_ifc(self.filepath, self.use_names, self.process_relations, self.blender_booleans):
  File "C:\Users\Ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_ifc\__init__.py", line 181, in import_ifc
    parent_ob = iterator.getObject(parent_id)
  File "C:\Users\Ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_ifc\ifcopenshell\ifcopenshell_wrapper.py", line 451, in getObject
    return _ifcopenshell_wrapper.iterator_double_precision_getObject(self, id)
RuntimeError: An unknown error occurred

location: <unknown location>:-1
"

[IFC from Revit to Blender.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1320523/IFC.from.Revit.to.Blender.zip)

On all other tests the addon works really great! Thanks for the work.

**Comment by aothms** [comment]
Thanks for reporting this. It seems at some point `getObject()` started throwing exceptions for IfcProject instances, which can be considered the root node of the IFC file hierarchy. This is fixed now and also the name is properly derived from the project, which previously did not happen and went unnoticed.

A new build will be around shortly hopefully. Is this a pressing issue for you, and if so, are you able to build IfcOpenShell from source yourself?

**Comment by ejnaren** [comment]
awesome. thanks Thomas.
no it's not pressing. I found a way to script the things I needed.  but nice that it's fixed.
now IFC is actually the easiest way to get heirarchi from Revit to Blender. 
You are the man.

Best.
Ejnar

**Comment by aothms** [comment]
Thanks, note that in addition a IfcConvert conversion to Collada (.DAE) also retains the same hierarchy now that we have https://github.com/IfcOpenShell/IfcOpenShell/pull/211

**Comment by ejnaren** [comment]
It's just beautiful <3

**Comment by patins1** [comment]
Hi guys, I stumbled across the same bug,  occurring using the IfcBlender addon for blender for most of my IFC files. As I am not a build-expert for visual studio, and the bug is urgent for me, is there a work-around to pre-process the IFC file somehow so to mask out this bug?

**Comment by aothms** [comment]
Hi, a reasonable fix can also be made by just editing the python files in the add-on, i.e without recompilation of the binary code.

~~~diff
--- __init__.py	2017-09-25 13:59:49.712878800 +0200
+++ __init__.py	2017-12-04 11:04:50.383186200 +0100
@@ -175,14 +175,18 @@
     while len(id_to_parent_temp) and process_relations:
         id, parent_id = id_to_parent_temp.popitem()
         
+        bob = None
+        parent_ob = None
+        
         if parent_id in id_to_object:
             bob = id_to_object[parent_id][0]
         else:
-            print(id, parent_id)
-            parent_ob = iterator.getObject(parent_id)
-            if parent_ob.id == -1:
-                bob = None
-            else:
+            try: 
+                parent_ob = iterator.getObject(parent_id)
+                if parent_ob.id == -1: parent_ob = None
+            except: pass
+            
+            if parent_ob is not None:
                 m = parent_ob.transformation.matrix.data
                 nm = parent_ob.name if len(parent_ob.name) and use_names \
                     else parent_ob.guid
~~~

Let me know if you need further guidance on how to apply these changes to your local copy of the ifcblender add-on. If you're not familiar with patch and diff tools, you can simply open the `__init__.py` file and change the bits into the green bits.
