### ISSUE TITLE
BlenderBIM: (Feature request) - Sync drawing creation filter with viewport

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#2613]
When working within the viewport across a multiphase project the view can become cluttered with model elements from various phases and disciplines.

Currently BlenderBIM can filter model elements based on a Pset values when exporting to .SVG. 

Proposal would be for these filtered items to be reflected in the viewport so phases can be clearly displayed and worked upon. This would be linked to drawing/view activation so the model view is filtered to match phasing or other Pset values defined.

**Comment by Moult** [comment]
@Andrej730 Upon activating a drawing, the EPset_Drawing Include/Exclude must be processed.
