### ISSUE TITLE
1.#INF as number

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#2614]
I have an IFC with this row

= IFCQUANTITYLENGTH('Origin height',$,$,1.#INF);

If I try to read this Quantity with the Parser i get an memory access violation error.

It's an Archicad 25 IFC

**Comment by aothms** [comment]
`1.#INF` is not valid, but can you create a minimal file that reproduces the issue?

**Comment by ninichki** [comment]
[Cube.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10076766/Cube.txt)

It seems, it only happens, if IFCQUANTITYLENGTH has only 4 arguments.

**Comment by aothms** [comment]
I cannot reproduce this using both python `ifcopenshell.open()` or IfcConvert. What's the exact steps to reproduce?

**Comment by ninichki** [comment]
You get the error when you try to get the length of this property.

#279= IFCQUANTITYLENGTH('Width',$,$,1.#INF);

**Comment by ninichki** [comment]
IfcSchema::IfcPhysicalQuantity::list::it quantity

double length = (double)((IfcSchema::IfcQuantityLength*)(*quantity))->LengthValue();

**Comment by aothms** [comment]
My C++ workspace is a mess atm so it'll take me a couple of days to reproduce. Looking at things from python it seems things are handled fairly gracefully. Are you fully in sync with the latest ifcparse codebase?

```
>>> import ifcopenshell
>>> f = ifcopenshell.open('Cube.txt')
>>> f[279]
#279=IfcQuantityLength('Width',$,$,$,$)
>>> repr(f[279].LengthValue)
'None'
>>> print(ifcopenshell.get_log())
[Error] [2022-11-28 09:46:51] Entity with name '1.#INF' not found in schema 'IFC4'
[Error] [2022-11-28 09:46:51] Wrong number of attributes on instance with id #279 at offset 7287 expected 5 got 4
```

**Comment by ninichki** [comment]
Ok, my last commit id is 7db96758 3b82bb3c58b998639e4cc5ce43bd4968 from 22.09.2022.
I'm using msvc to compile it.

Do you think, there is something changed since that?

**Comment by ninichki** [comment]
Hello,

I updated our branch and no it's working.

Sorry for your inconvenience
