### ISSUE TITLE
BlenderBIM: IfcSpaceType not available in selector (in new project with ifc4 demo template loaded)

### ISSUE THREAD

**Issue by fbpyr** [IfcOpenShell/IfcOpenShell#2615]
`IfcSpaceType` is missing from the ifc class selector from category `IfcElementType` for assigning an ifc class to object. 
If an ifc project is opened, that had `IfcSpaceType` already, it is available.

( ping @CyrilWaechter )

**Comment by CyrilWaechter** [comment]
Solved by 88093728a795f1da2b55fdd6740b9453a7f80071

**Comment by fbpyr** [comment]
Awesome! 🚀 
Thank you so much @CyrilWaechter
