### ISSUE TITLE
ifcopenshell.file.__getitem__ not working in py3

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#262]
https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcopenshell-python/ifcopenshell/file.py#L43

Due to basestring, see: https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/a30fab74/?limit=25#e14b

Easiest solution probably along the lines of https://github.com/requests/requests/blob/master/requests/compat.py

~~~
is_py3 = sys.version_info[0] == 3
if is_py3:
    basestring = (str, bytes)
~~~

**Comment by thorade** [comment]
Alternative way, using feature detection:
```python
try:
    # Python 2
    basestring
except NameError:
    # Python 3 or newer
    basestring = str
```

https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection

**Comment by aothms** [comment]
> Alternative way, using feature detection:

Even better probably. Will you commit this?

**Comment by thorade** [comment]
not tested, I just copied the code into the file you linked
