### ISSUE TITLE
Changing Blender object origin doesn't update geometry

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#2626]
I've run into a problem when moving object within an existing IFC file. 
As soon as I move the object origin, the element is moved to that location when saving and opening the IFC again. Attached a short video and the  [IFC file](https://github.com/IfcOpenShell/IfcOpenShell/files/10121691/test_1.ifc.txt).

BlenderBim version: blenderbim-221127-py310-macosm1
Blender: 3.3.1

https://user-images.githubusercontent.com/67860835/204760149-a60cab4b-dc7f-43d7-a416-a9e2e2d19b5d.mp4

**Comment by Moult** [comment]
Yeah unfortunately Blender has quite a lot of ways to manipulate geometry and we can't "catch" them all to make sure they do the thing you'd expect in native IFC. This is one of them.

For now you can manually in the Mesh Properties tab > IFC Representation > Update Representation and that'll fix it.

**Comment by smr02** [comment]
@Moult that fixes it, Thank you!

Is it possible to run this automatically when saving to IFC? It's quite discouraging if the exported IFC looks different from what is shown in Blender.

**Comment by Moult** [comment]
Unfortunately I'm not aware right now of an easy way to catch / override this particular Blender function just yet. Let's keep this issue open in case there is a way.

There are a number of Blender functions which do not have an IFC equivalent, over time we'd hope to improve the UX to prevent this type of mismatch.
