### ISSUE TITLE
FlangeEdgeRadius and FlangeSlope for IfcIShapeProfileDef

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2631]
Looks like flange rounding and sloping is not working as expected...

https://community.osarch.org/discussion/1272/flangeedgeradius-and-flangeslope-for-ifcishapeprofiledef

**Comment by Moult** [comment]
Yeah it looks as though this hasn't been implemented in IfcIShapeProfileDef.cpp. Perhaps some code can be taken from IfcUShapeProfileDef.cpp and maybe with a minor tweak it might just work. I have a new computer though so it might be a while until I get a chance to try.

Maybe @aothms can do it with his eyes closed :)

**Comment by Moult** [comment]
Seems to work on my end but given I suck at C++ @aothms should review it :)

![2023-01-08-211218_801x598_scrot](https://user-images.githubusercontent.com/88302/211190735-14f84222-5301-4977-8d69-06bab75d9a9b.png)
