### ISSUE TITLE
ifcConvert symbol look up error with conda installation  

### ISSUE THREAD

**Issue by whathecker** [IfcOpenShell/IfcOpenShell#2633]
Hello!

I'm trying to build a docker image with IfcConvert baked-in, using conda to install the package. 

docker image builds just fine, however, when trying to run IfcConvert inside the container, I get a symbol look-up error as follows.

`IfcConvert: symbol lookup error: IfcConvert: undefined symbol: _ZNK16Standard_Failure14GetStackStringEv`

Any chance to learn why this might be happening? thanks a lot!

**Comment by Moult** [comment]
By the way, a docker image is already provided, does this help? https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#docker

**Comment by aothms** [comment]
You're likely using a different open cascade version when you compile as to when you run.

`Standard_Failure::GetStackString()` seems to have been added in 7.6 https://github.com/Open-Cascade-SAS/OCCT/commit/7fb9d6d573a724049e9c46d9050a85bba72f437f but I'm fully certain.

**Comment by Moult** [comment]
Bump @whathecker did that help?

**Comment by whathecker** [comment]
We used a different approach to download the pre-built binary instead of using conda, which worked nicely. Thanks for helping out!
