### ISSUE TITLE
IFC Selector shoud find walls with IsExternal ="True"

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#2641]
﻿I tried a very simple **IFC Selector** query `.IfcWall[Pset_WallCommon.IsExternal ="True"]` in Blender 3.1.1 with BlenderBIM 0.0.221105. This query does not find any of several walls that have this property.
Is this an error or am I doing something wrong.

I attached a screenshot which shows the query and properties in Blender.
![Bildschirm­foto 2022-12-08 um 11 52 41](https://user-images.githubusercontent.com/1941141/206430729-1214bbcc-f38c-4007-83ac-6a9c45733899.png)

**Comment by Moult** [comment]
I think this is now fixed. https://github.com/IfcOpenShell/IfcOpenShell/commit/145ac1a0f4df7de1a55e0ec3ffd7eef8d32cadd8
