### ISSUE TITLE
pb add-on install 

### ISSUE THREAD

**Issue by flooo51** [IfcOpenShell/IfcOpenShell#2644]
hello! I try to install blender bim but the add-on don't work :(
If anyone knows why it's not working

thanks!

![capture](https://user-images.githubusercontent.com/117521076/206786652-09bc4d13-ab56-474d-9f1e-99a0bb109123.jpg)
![Capture d’écran 2022-10-28 220100](https://user-images.githubusercontent.com/117521076/206787505-8b3e9815-9b16-4495-8753-169c2c2d6478.jpg)

**Comment by flooo51** [comment]
nobody can help me :(

**Comment by CyrilWaechter** [comment]
As written in the error message it is apparently a permission issue. How did you install blenderbim ? Did you installed it from blender (good way) or did you unzip files (risky way if you don't know what you do) ?

**Comment by Moult** [comment]
@flooo51 did you follow the installation instructions here? https://blenderbim.org/docs/users/installation.html

**Comment by aothms** [comment]
_ifcopenshell_wrapper.pyd (the file complained about) is the binary ifcopenshell module. On windows it can't be deleted if it's used (e.g import ifcopenshell). But why is the code trying to do that (shutil.rmtree)? Are you uninstalling?

**Comment by Moult** [comment]
@flooo51 also see uninstallation instructions: https://blenderbim.org/docs/users/installation.html#uninstalling

... and more generically see FAQ number 3: https://blenderbim.org/docs/users/installation.html#faq

**Comment by Moult** [comment]
Bump @flooo51

**Comment by Moult** [comment]
Assume user error as nobody else is having issues and no response from original author.
