### ISSUE TITLE
ObjectPlacement has not proper attributes

### ISSUE THREAD

**Issue by IbimDesarrollo** [IfcOpenShell/IfcOpenShell#2647]
ifcopenshell.util.placement.get_local_placement is a recursive method that use PlacementRelTo inside it. But i get "object has no attribute 'PlacementRelTo'" error because in ObjectPlacement property i dont have it (image is given). I dont know what its wrong. 
![image](https://user-images.githubusercontent.com/93908242/207328931-ee0e7dbb-de05-41e5-8e3a-bf75720af90a.png)

**Comment by aothms** [comment]
What does `ifcxproject.is_a()` return in that case?

Also check with `python -m ifcopenshell.validate` on your file if you it is specific to certain files.

**Comment by IbimDesarrollo** [comment]
I got it¡¡¡ sorry for the inconvinient but i change lately ifcopenshell package outside from my virtual environment and it cause that objects has not all attributes. It could be that some dependencies has not readed properly or similar. The case is that if a return package inside virtual environment all run properly and objects has attributes. Sorry again.
