### ISSUE TITLE
show optional attributes as well with IFC selector

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2649]
Feature request: show optional attributes as well with IFC selector...

for example...
```	
NominalDiameter
NominalLength
```
https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcsharedcomponentelements/lexical/ifcmechanicalfastener.htm

![image](https://user-images.githubusercontent.com/507113/207975430-eeafdf84-5271-4374-986b-b4d2d47de739.png)

**Comment by vulevukusej** [comment]
One thing you could do in the meantime @theoryshaw is generate the query with another attribute and then edit the syntax using the 'manual' toggle
