### ISSUE TITLE
Have IFC selector only work on visible objects only. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2650]
Have IFC selector only work on objects that are not already hidden. 

Let's say a user turns off ifcclass 'x'.

Currently when a user searches and selects ifcclass 'y', ifcclass 'x' will turn on again. 

It would be nice if ifcclass 'x' does not turn on.

Or at the very least have a preference where selection set either applies to everything, or just visible objects.

**Comment by vulevukusej** [comment]
This makes sense!
