### ISSUE TITLE
BlenderBIM No IFC Object Metadata in Object Properties/Debian Bullseye

### ISSUE THREAD

**Issue by Jansolo75** [IfcOpenShell/IfcOpenShell#2654]
![Screenshot from 2022-12-16 22-27-30](https://user-images.githubusercontent.com/75941583/208217335-739bf2e8-3bc6-48b2-8f16-5e725257970a.png)
Hi, Im trying the BlenderBIM Beginner Tutorial Part 1 [https://www.youtube.com/watch?v=kF2k_VW-yrQ&t=347s](url) and some tools doesn't work well. First, IFC properties didn't appear in the Scene Properties, I fixed it keeping BlenderBIM  in the download folder. Now a similar problem occurs in **Object Properties**, because the **IFC Object Metadata** doesn't appear. It seems like a degradation of BlenderBIM through the use.
Regards
![Screenshot from 2022-12-16 22-58-28](https://user-images.githubusercontent.com/75941583/208218149-bf20ccf6-f473-4782-954c-83927e4beaac.png)

-  blender-3.3.1-linux-x64
- BlenderBIM 0.0.221105
- Debian 11 Bullseye

**Comment by theoryshaw** [comment]
Can you be more specific? Perhaps share a video screencast of the problem..  that shows the steps, etc.

**Comment by theoryshaw** [comment]
Also would suggest posting your question here....
https://community.osarch.org/discussion/1240/blenderbim-beginner-tutorial-step-by-step-project-part-1-modelling/

**Comment by Jansolo75** [comment]
> Also would suggest posting your question here....

 .Thanks @theoryshaw . I'll do that.

**Comment by Moult** [comment]
Closing as this seems to be discussed in the forums. The solution seems to be that you've got filter addons enabled which hides the BlenderBIM Add-on UI, and that in the second screenshot you haven't yet assigned it an IFC class and so naturally no IFC properties will show since it isn't an IFC element yet.
