### ISSUE TITLE
Solid model from curve vector

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [IfcOpenShell/IfcOpenShell#2658]
Hi, is there any entities to initialize an IFC solid model using curve vectors with brep.

**Comment by aothms** [comment]
IfcAdvancedBRep? It allows IfcAdvancedFace with a surface and edges with curves. It's not all too well supported in many applications though.

**Comment by SHAWNZHANGSH** [comment]
Thanks Aothms, I`ve found the answer in the example of IfcOpenShell
