### ISSUE TITLE
About initialization IfcEdgeCurve

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [IfcOpenShell/IfcOpenShell#2666]
Hi, I was preparing for the initialization of IfcEdgeCurve.
And the curve is a wholely IfcCircle.
So I'm confused about the 'EdgeStart' and 'EdgeEnd' represented by IfcVertexPoint.
Because it`s the same catesian point.

![image](https://user-images.githubusercontent.com/73410751/210033257-d8ecd444-f03c-4e1a-8b82-4c7229089cb7.png)

**Comment by aothms** [comment]
That's true. In a CAD kernel there would be an associated 2d space on the periodic curve and surface with 0 and 2pi respectively. That way you can distinguish identical points in 3d space, but full parametric curve extent in 2d space. 

I think the solution in IFC would be to use p-curves. As is done in the IfcSeamCurve diagram here http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcSeamCurve.htm But it would be good to have good IfcAdvancedBRep examples of sphere and cylinder we can all get behind and formalize some informal propositions to more precisely define the intended usage of these entities.

**Comment by SHAWNZHANGSH** [comment]
Thanks, aothms
