### ISSUE TITLE
is ifcOpenshell v7 incompatible with pythonocc ?

### ISSUE THREAD

**Issue by Maozerhouni** [IfcOpenShell/IfcOpenShell#2667]
Hi,

I am trying to download ifcOpenShell and pythonOCC.

When I start by installing IfcOpenShell v0.7, installation of pythonOCC detects conflicts. When I start with pythonOCC, conda only proposes ifcOpenShell v0.6. Is there anything I can do yo have IfcOpenShell v0.7 working with pythonOCC ?

**Comment by aothms** [comment]
Let's await discussion here which is more specific https://github.com/IfcOpenShell/IfcOpenShell/issues/2267#issuecomment-1367802786

**Comment by Moult** [comment]
Referenced discussion is resolved, so this may also be closed.
