### ISSUE TITLE
About surface boolean

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [IfcOpenShell/IfcOpenShell#2668]
Hi, I was building a shape of hole using IFC schema.
However, the IfcBooleanResult can't be applied with surface boolean.
The IfcCircleHollowProfileDef is used in the swept area solid.

**Comment by aothms** [comment]
I don't fully understand the question, but indeed, boolean (subtraction) can only be applied to solids in IFC. (So extrude the profiles then do boolean if you have to). Boolean union can to some extent be emulated using IfcCompositeProfileDef.

**Comment by SHAWNZHANGSH** [comment]
It's a shape of hollow cylinder.
Among them, the top/bottom face is the result that the outer circle subtracts the inner circle.

The way I`m using to generate the Brep model is entities initialization instead of OpenCascade.
So is there a proper way to generate this kind face.
![image](https://user-images.githubusercontent.com/73410751/210294505-910e88ed-2915-4e53-b4bb-96a1ade3cee9.png)

**Comment by Moult** [comment]
Just use an arbitrary profile def with voids, with an outer circle curve and one inner circle curve, then extruded it with IfcExtrudedAreaSolid. Here's an example: [test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10334979/test.ifc.txt)

Is there a reason you need to use booleans?

**Comment by aothms** [comment]
Also, are you aware an IfcFace can have multiple bounds, with
non-IfcFaceOuterBounds being the inner boundaries?

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op di 3 jan. 2023 09:04 schreef Dion Moult ***@***.***>:

**Comment by SHAWNZHANGSH** [comment]
> Just use an arbitrary profile def with voids, with an outer circle curve and one inner circle curve, then extruded it with IfcExtrudedAreaSolid. Here's an example: [test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10334979/test.ifc.txt)
> 
> If you want to use booleans you could boolean one extruded area solid with another extruded area solid, but it seems unnecessarily complex.
> 
> Is there a reason you need to use booleans?

Hi Moult, I'm processing the solid model of Parasolid, which is constructed by B-rep instead of extruded or swept.
This why I'm looking for IFC entities to represent the hollow face.
So, maybe arbitrary profile isn't suitable to describe this shape.

**Comment by SHAWNZHANGSH** [comment]
> Also, are you aware an IfcFace can have multiple bounds, with non-IfcFaceOuterBounds being the inner boundaries?

Hi aothms, I've found an example in the IfcOpenShell (IfcAdvancedHouse), which contains both the IfcFaceBound and IfcFaceOuterBound.

......
#84=IFCPOLYLOOP((#80,#81,#82,#83));
#85=IFCFACEOUTERBOUND(#84,.T.);
......
#90=IFCPOLYLOOP((#86,#87,#88,#89));
#91=IFCFACEBOUND(#90,.T.);
#92=IFCFACE((#85,#91));

So, according to the entity definition, maybe IfcFace can have a IfcFaceOuterBound with multiple IfcFaceBound.

......
#84=IFCPOLYLOOP((#80,#81,#82,#83));
#85=IFCFACEOUTERBOUND(#84,.T.);
......
#90=IFCPOLYLOOP((#86,#87,#88,#89));
#91=IFCFACEBOUND(#90,.T.);
#92=IFCFACE((#85,#91));

So, according to the entity definition, maybe IfcFace can have a IfcFaceOuterBound with multiple IfcFaceBound.

**Comment by SHAWNZHANGSH** [comment]
> Also, are you aware an IfcFace can have multiple bounds, with non-IfcFaceOuterBounds being the inner boundaries?

Hi aothms, I've found an example in the IfcOpenShell (IfcAdvancedHouse), which contains both the IfcFaceBound and IfcFaceOuterBound.

......
#84=IFCPOLYLOOP((#80,#81,#82,#83));
#85=IFCFACEOUTERBOUND(#84,.T.);
......
#90=IFCPOLYLOOP((#86,#87,#88,#89));
#91=IFCFACEBOUND(#90,.T.);
#92=IFCFACE((#85,#91));

So, according to the entity definition, maybe IfcFace can have a IfcFaceOuterBound with multiple IfcFaceBound.

**Comment by aothms** [comment]
Yes that is correct

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op wo 4 jan. 2023 06:32 schreef Shihang ***@***.***>:

**Comment by Moult** [comment]
@SHAWNZHANGSH does that solve your problem?

**Comment by SHAWNZHANGSH** [comment]
> @SHAWNZHANGSH does that solve your problem?

Yes, I tested it today, and it works.
Here is a thin circle ring.
![image](https://user-images.githubusercontent.com/73410751/210957172-2f4e83c5-239c-42bd-8103-46d5056cca5e.png)
