### ISSUE TITLE
compile error on Linux Debian Jessie on GCC

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#267]
Have not been tried to compile IfcOS for a while. Gave it a try today and failed on Linux Debian Jessie on GCC on commit:  https://github.com/IfcOpenShell/IfcOpenShell/commit/33220fa78cd21ec708132b8d46593cd6416404e7

`
$ make -j 4
[ 34%] Built target IfcParse
[ 68%] Built target IfcGeom
[ 71%] Swig source
[ 75%] Built target IfcGeomServer
[ 96%] Built target IfcConvert
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/../ifcparse/IfcFile.h:62: Warning 325: Nested class not currently supported (type_iterator ignored)
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/../ifcgeom/IfcGeomTree.h:246: Warning 401: Nothing known about base class 'impl::tree< IfcSchema::IfcProduct * >'. Ignored.
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/../ifcgeom/IfcGeomTree.h:246: Warning 401: Maybe you forgot to instantiate 'impl::tree< IfcSchema::IfcProduct * >' using %template.
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/IfcGeomWrapper.i:78: Warning 509: Overloaded method IfcGeom::tree::select_box(Bnd_Box const &) const effectively ignored,
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/IfcGeomWrapper.i:73: Warning 509: as it is shadowed by IfcGeom::tree::select_box(gp_Pnt const &) const.
[100%] Building CXX object ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o
In file included from /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:3143:0:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/../ifcgeom/IfcGeomTree.h: In member function ‘void IfcGeom::tree::add_file(IfcParse::IfcFile&, const IfcGeom::IteratorSettings&)’:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/../ifcgeom/IfcGeomTree.h:270:77: error: ‘const class IfcGeom::Representation::BRep’ has no member named ‘as_compound’
      add((IfcSchema::IfcProduct*)f.entityById(elem->id()), elem->geometry().as_compound());
                                                                             ^
In file included from /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/../ifcparse/../ifcparse/IfcEntityInstanceData.h:23:0,
                 from /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/../ifcparse/IfcBaseClass.h:31,
                 from /home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:3145:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/../ifcparse/../ifcparse/../ifcparse/ArgumentType.h: At global scope:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/ifcos/src/ifcwrap/../ifcparse/../ifcparse/../ifcparse/ArgumentType.h:25:7: error: multiple definition of ‘enum IfcUtil::ArgumentType’
  enum ArgumentType {

...
hundereds of similar error messages
...
 
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx: In function ‘std::vector<std::basic_string<char> > IfcUtil_IfcBaseClass_getAttributeNames(const IfcUtil::IfcBaseClass*)’:
/home/hugo/Documents/dev/ifcopenshell/ifcopenshell-dev/build/ifcwrap/IfcPythonPYTHON_wrap.cxx:4011:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build.make:62: recipe for target 'ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o' failed
make[2]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:218: recipe for target 'ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all' failed
make[1]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
`

find all log in file attached:
[error.log](https://github.com/IfcOpenShell/IfcOpenShell/files/1371169/error.log)

**Comment by thorade** [comment]
@berndhahnebach you can attach files to your issue, should be more readable to put the big log in a txt file instead of pasting the content in the issue directly
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by berndhahnebach** [comment]
very good idea, done ...

**Comment by berndhahnebach** [comment]
On a clean fresh debian jessie and by the use of jessie oce packages it compiles and runs smooth. If I have time to tackle it down to give more informations I may reopen the issue.

bernd

**Comment by aothms** [comment]
@berndhahnebach I get strange compile errors from other users as well from time to time. And every time I hear that switching to a fresh install fixes the problem, so it must be something local, but that apparently affects multiple users.  If you can get to the bottom of this it would be greatly appreciated.

**Comment by berndhahnebach** [comment]
Thanks Thomas for your answer. I may need to get this to bottom because the fresh installs are just vargrant boxes. My main debian jessy runs a very old ifcos (around a year ago). I'm gone pist any update on this if I find something.

cheers bernd
