### ISSUE TITLE
Blender BIM IfcArbitraryProfileDefWithVoids visualization

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#2671]
Noticed working with IfcArbitraryProfileDefWithVoids that adding inner curves that either lie right on the edge of outer curve (image 2) or go outside the outer curve (image 3) produce artifacts when visualizaed using blender BIM.

+ Original shape (outer curver is rectangle 350x100 + extrusion 25 by z):
<img src="https://user-images.githubusercontent.com/9417531/210249789-eed967db-ebb9-46bb-95fb-c51627438165.png" width=50% height=50%>

+ +rectangle 100x100 shaped inner curve
<img src="https://user-images.githubusercontent.com/9417531/210249925-f5e73802-3a34-4c1e-a8a3-03869aa077fd.png" width=50% height=50%>

+ +inner curve rectangle 50x50 is offseted by (-50, -50).
<img src="https://user-images.githubusercontent.com/9417531/210250044-33b65cc0-5d45-4bbb-b960-8288890a36ac.png" width=50% height=50%>

Isn't correct shape for the last one should look something like this?
<img src="https://user-images.githubusercontent.com/9417531/210250953-cbf26e05-2895-46fa-bd6b-35b2a96d3b27.png" width=50% height=50%>

Ifc file if need to play around with it - [tmp.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10332362/tmp.ifc.txt) (the final shape is `#16`)

**Comment by aothms** [comment]
This is not supported well, because it violates the "Informal Propositions" in the schema.

> The outer curve shall enclose all inner curves.
> 
> No inner curve shall intersect with the outer curve or any other inner curve.

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcprofileresource/lexical/ifcarbitraryprofiledefwithvoids.htm
