### ISSUE TITLE
How to install and import IDS / IfcTester in python

### ISSUE THREAD

**Issue by SigveMartin** [IfcOpenShell/IfcOpenShell#2673]
Hi 

Is IDS or IfcTester part of the pip or conda packages of ifcopenshell? 

I haven't found how to import IDS module (or IfcTester) module after installing ifcopenshell (tested with both pip and conda).

**Comment by Moult** [comment]
Currently it is not part of pip or conda. It probably should be. Would you like to help?

**Comment by SigveMartin** [comment]
Would be happy to help if I can. I have never published pachages for pip or conda, but I can look into it and give it a go when I get the time. 

What are the steps that is needed, as you see it @Moult ?

**Comment by civilx64** [comment]
I ran in to the same issue recently.  I was able to work around it by downloading the source and copying `ifctester` to `site_packages` in my virtual environment.  But my initial instinct was to use `from ifcopenshell.ifctester import ids`.

Per [the poetry documentation](https://python-poetry.org/docs/basic-usage/) I believe all that is needed is to move the `ifctester` folder to reside under `/ifcopenshell-python/ifcopenshell/`.  This would make it an importable submodule similar to `api`, `util` and so on.

I suspect this would also work across conda and Docker although I haven't done any research to confirm.

If there is an organizational reason to keep `ifctester` where it is then I would recommend publishing to pyPI and conda as a separate python package that would then be declared as a dependency for ifcopenshell.

While we are talking reorganization I would also suggest renaming `ifctester` to `idstester` or better yet just `ids`.  Currently it is at the same level as `ifcbimtester` which is a bit confusing IMO. Taking this approach would result in usage looking like `from ifcopenshell.ids import ids` which feels more pythonic.

Happy to submit a PR if all are in agreement.

**Comment by Moult** [comment]
IfcTester used to be part of IfcOpenShell as an `ids` module exactly as you describe. At the time it was a single file.

I was the one responsible for splitting it into its own package. It grew from a single file to the many files you see today including extra scope like generating the documentation test suites for buildingSMART. The intention was that it would have its own set of UIs including a webapp (which you can see half built), a variety of reporting mechanisms (a number already built, but also including BCF, which is already a separate package), and also later on absorb BIMTester's capabilities (and thus not just IDS, but a generic IfcTester) for custom non-IDS checks (so BIMTester will be deleted / merged). I thought that with this scope it was best left separate to IfcOpenShell (after all, IDS is a separate schema with separate XSDs, similar to how BCF is also separated). Over time I've also tried to separate modules that move at different speeds.

But maybe I'm wrong and it should be merged back into IfcOpenShell. It's a bit fluid.

**Comment by civilx64** [comment]
> My gut feel (but no real logic) is that it will continue to grow in scope and it should be left its own package, and this bug should be solved by packaging it for pip.

Agree.  And your explanation on naming makes sense if the long-term roadmap is to absorb BIMTester.

**Comment by civilx64** [comment]
Given the long term roadmap for ifctester and thinking in terms of the Unix philosophy of smaller tools scoped to specific uses I believe there would be merit in breaking out ifctester as a separate repository under the IfcOpenShell organization. This may also encourage more contribution in general as it would be a pure Python codebase. Thoughts?  Do we have an equivalent of the PEP process for IFCOS 😉?

**Comment by Moult** [comment]
By the way the monorepo vs multirepo discussion was brought up earlier here: https://github.com/IfcOpenShell/IfcOpenShell/issues/1497

**Comment by Moult** [comment]
https://pypi.org/project/ifctester/
