### ISSUE TITLE
ImportError: ifcopenshell/_ifcopenshell_wrapper.so: undefined symbol: __gmpq_init

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2674]
I've been trying to compile IfcOpenShell again to see if I could help with the flange slope bug, but ran into this error when trying to import ifcopenshell. Any ideas?

This is my configure and make step:

```
$ ccmake ../cmake -DHDF5_LIBRARIES="/usr/lib64/libhdf5_cpp.so;/usr/lib64/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libsz.so;/usr/lib64/libaec.so" -DHDF5_INCLUDE_DIR="/usr/include"
$ cmake --build . -j 12 --target _ifcopenshell_wrapper
```

![2023-01-06-165622_831x704_scrot](https://user-images.githubusercontent.com/88302/210939612-f8ee4076-9d05-4021-974a-4b8146bfd28c.png)

**Comment by aothms** [comment]
You're missing the gmp and mpfr libraries https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/.github/workflows/ci-py-only.yml#L70-L73

**Comment by Moult** [comment]
Ah I thought I had included it because libGMP and libMPFR in the ccmake UI shows /usr/lib64 ...

Copying them as CLI args makes ccmake show them as /usr/lib64/libgmp.so and /usr/lib64/libmpfr.so so that's much better, I guess they need to be .so files not directories. I have a lot to learn about compiling!

It works now! Thank you :)
