### ISSUE TITLE
IfcClash doesn't work with blenderbim and windows

### ISSUE THREAD

**Issue by Nattefrost666** [IfcOpenShell/IfcOpenShell#2675]
Am I wrong?
![ClashTrouble](https://user-images.githubusercontent.com/51818392/211002003-fef7e983-2020-4f8c-b0f9-748d3911a281.png)

**Comment by Moult** [comment]
There is a new BCF library and not everything has been ported to it yet. So yeah, it's broken and not only on Windows in the latest unstable release :)

**Comment by Nattefrost666** [comment]
ok, thanks for replying.

**Comment by sanzoghenzo** [comment]
I saw the discussion on OSArch forum but didn't take the time to search for related issues here.
@Moult just merged my PR, I hope this fixed the issue. If you are brave enough to clone and test the git version, let me know if there is something wrong!

**Comment by Moult** [comment]
Closing as this is now fixed - the BCF viewer is also updated to view potential BCF results.
