### ISSUE TITLE
IfcOpenShell 0.7.0 tessellation not working

### ISSUE THREAD

**Issue by Alex-Schlachter27** [IfcOpenShell/IfcOpenShell#2676]
Hi, I'm trying to create a TopoDS geometry from an IFC element, change the geometry with pythonOCC and then create an IFC geometry again from the result via the tessellate function to assign it to a new element.

The workflow works in a prebuilt jupyter notebook from Jakob Beetz (https://github.com/jakob-beetz/ifcopenshell-notebooks) with ifcopenshell 0.6.0, but it does not work with my own notebooj, where I'm using ifcopenshell 0.7.0.

I'm using the following settings:
`settings = ifcopenshell.geom.settings()`
`settings.set(settings.USE_WORLD_COORDS, True)`
`settings.set(settings.USE_PYTHON_OPENCASCADE, True)`

And the following simple code:
```
products = kon_model.by_type("IfcProduct")
product_shapes = []

for product in products:
    if product.is_a("IfcOpeningElement") or product.is_a("IfcSite"): continue
    if product.Representation is not None:
        shape = ifcopenshell.geom.create_shape(settings, product)
        
        # Tesselate to generate an IFC geometry from OCC.Core.TopoDS.TopoDS_Compound
        product_shape = ifcopenshell.geom.tesselate(kon_model.schema, shape.geometry, 1.e-3)
```

I'll get the following error:
![image](https://user-images.githubusercontent.com/62239809/211032545-41caea8a-6057-45e3-9089-38c04706f40a.png)

In this post (https://sourceforge.net/p/ifcopenshell/discussion/1782716/thread/aab0660dbd/?limit=25), I've seen that it is also possible to use `USE_BREP_DATA` and `.brep_data`. Using this, I won't get any error. 

Anybody knows if this is a common issue of ifcopenshell 0.7.0 or if I'm missing something here? What is the difference between using  `USE_BREP_DATA` and  `USE_PYTHON_OPENCASCADE`?

Thanks for the help :)

**Comment by Jesusbill** [comment]
Hi @Alex-Schlachter27 do you have `pythonOCC` installed?
That would be a reason to have such an error message (see also #758).

> What is the difference between using USE_BREP_DATA and USE_PYTHON_OPENCASCADE?

I believe with `USE_BREP_DATA` you will get the BRep object whereas with `USE_PYTHON_OPENCASCADE` you will get an OpenCascade BRep
See this part of the documentation that could help (https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html)

**Comment by Alex-Schlachter27** [comment]
Hi @Jesusbill ,

Thanks for the reply and the reference :) 
But unfortunately I don't think it'll hell me much, as I have pythonOCC installed. I do import some things from OCC in the script  before and do not get any error.

**Comment by Moult** [comment]
What are your `settings` set to?

I potentially don't see any issue here, especially if it works with USE_BREP_DATA. You can see what they mean in the documentation here:

https://blenderbim.org/docs-python/ifcopenshell/geometry_settings.html#use-brep-data
https://blenderbim.org/docs-python/ifcopenshell/geometry_settings.html#use-python-opencascade

**Comment by aothms** [comment]
The issue likely is that you're using an OCCT version that is newer than the version IfcOpenShell was built with:

```
>>> list(filter(None, ifcopenshell.geom.occ_utils.serialize_shape(shape.geometry).split('\n')))[0]
'CASCADE Topology V3, (c) Open Cascade'
```

Likely IfcOpenShell's OCCT version only supports V1, V2

That's why BREP_DATA works, because then you rely on the OCCT version compiled into IfcOpenShell to do the serialization for you.

I think you can fix this with `shapes.SetFormatNb(2)` here [0] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/geom/occ_utils.py#L219

If this solves your problem, could you send in a Pull Request? I think V2 has been around for a very long time, and if you run into this problem on your setup others will likely too.

**Comment by Moult** [comment]
Bump @Alex-Schlachter27
