### ISSUE TITLE
Autoapi docs for express module

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2677]
I've discovered that running the Python Sphinx docs are very slow now as the autoapi extension crawls through the ifcopenshell.express.rules namespace https://blenderbim.org/docs-python/autoapi/index.html

As it is autogenerated and basically IFC schema derived, I assume it is safe to exclude this from the docs?

**Comment by aothms** [comment]
Agreed. It's not intended to be ran manually. Instead use rule_executor.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op za 7 jan. 2023 09:32 schreef Dion Moult ***@***.***>:
