### ISSUE TITLE
API new dependencies on blender

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2679]
Since 23c7bc3 `util.representation` depends on `mathutils` provided by Blender.

This is fine, except that `material.assign_material`, `material.assign_profile`, `material.edit_profile_usage` all import `get_representation()` from `util.representation`, resulting in a new Blender dependency for these modules.
 
As a workaround I pasted a copy of `get_representation()` into each of these files, but there is probably a better way to do this.

**Comment by aothms** [comment]
I guess `ShapeBuilder` needs to be moved to a separate file, more or less removing the dependency on mathutils. Can I assign you for this task @Andrej730?

**Comment by Moult** [comment]
By the way mathutils is a standalone lib and doesn't have to be used in Blender. https://pypi.org/project/mathutils/

Agreed, @Andrej730 can you please move to a separate file, and/or lazy / optionally load import mathutil.

**Comment by Andrej730** [comment]
Fixed in cd254e9b000112b6ca447b21db75043a8596bca2

But in the future I'll add `add_window_representation.py` to `/src/ifcopenshell-python/ifcopenshell/api/geometry` that will use `ShapeBuilder`. Wouldn't the same `mahtuils` dependency occurt then?

Or it will only occur if someone is going to actually do `ifcopenshell.api.run("geometry.add_window_representation", self.file, **representation_data)`?

**Comment by Moult** [comment]
It'll only occur if they run the function so all good.

**Comment by cvillagrasa** [comment]
> Or it will only occur if someone is going to actually do `ifcopenshell.api.run("geometry.add_window_representation", self.file, **representation_data)`?

It just happened to me 😂

I ran `ifcopenshell.api.run("geometry.add_door_representation", ...)` in a conda environment outside Blender and the mathutils dependency popped out. Of course it's not a big deal, it was solved by pip installing the standalone lib @Moult mentioned.

Is it worth setting up `mathutils` as a dependency in the conda requirements?

**Comment by Moult** [comment]
I'm not sure, I think we just need to accept that ifcopenshell.api.geometry.* will always contain external dependencies as the nature of the geometry API relies on other geometry kernels. Some will depend on Blender, some on mathutils, some on Sverchok, and there will be more in the future, like FreeCAD, trimesh, etc. We can't ship all dependencies.

**Comment by cvillagrasa** [comment]
> Can conda have optional dependencies? Kind of like how in Gentoo you can configure useflags which enable or disable dependencies?

Maybe [this](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained), but I have no idea about the internals of conda.
