### ISSUE TITLE
run error on Linux ubuntu xenial

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#268]
Tried to compile https://github.com/IfcOpenShell/IfcOpenShell/commit/33220fa78cd21ec708132b8d46593cd6416404e7 on ubuntu xenial. 

cmake ...

sudo cmake ../IfcOpenShell/cmake  \
-DOCC_INCLUDE_DIR=/opt/local/FreeCAD-0.17/include/opencascade  \
-DOCC_LIBRARY_DIR=/opt/local/FreeCAD-0.17/lib  \
-DPYTHON_INCLUDE_DIR=/usr/include/python2.7  \
-DPYTHON_LIBRARY=/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so  \
-DUNICODE_SUPPORT=True  \
-DCOLLADA_SUPPORT=False  \
-DUSE_IFC4=False  \
-DBUILD_IFCPYTHON=True  \
-DBUILD_EXAMPLES=False

build and install runs fine but on import ifcopenshell in python I get ... 

$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/__init__.py", line 45, in <module>
    from . import ifcopenshell_wrapper
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 28, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_ifcopenshell_wrapper', fp, pathname, description)
ImportError: libTKernel.so.7: cannot open shared object file: No such file or directory
----------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ifcopenshell/__init__.py", line 52, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'linux/64bit/python2.7'
>>>

**Comment by berndhahnebach** [comment]
might because I installed occt not inside usr _

$ ls /opt/local/FreeCAD-0.17/lib/libTKernel.so
/opt/local/FreeCAD-0.17/lib/libTKernel.so

**Comment by berndhahnebach** [comment]
by the use of standard xenial oce packages it compiles and runs smooth. I close the issue for now. If I find some time and have more informations I may reopen it again.

bernd

**Comment by aothms** [comment]
Yes probably `/opt/local/FreeCAD-0.17/lib` is not in your `$PATH`, so at runtime the dynamic linker cannot find the libraries. This can be fixed probably with RPATHS and the like, and CMake can probably take care of that automatically (did you `make install` IfcOpenShell or not? that could make a difference). But easiest is to add the directory to your path, or create symlinks to the libraries in e.g. `/usr/lib` or sth.
