### ISSUE TITLE
You could either use `ifcopenshell.geom.tree` and then `.select(extend=0.01)` (or some other small number) to get geometrical neighbours. This requires evaluating all the geometry which is potentially computationally expensive. It also requires some manual filtering of the results because you would get also vertical neighbours which you do not seem interested in. The other alternative is to depend on space boundaries (IfcRelSpaceBoundary) provided by the authoring tool to encode the information of which element bound which space. This can in some cases be less reliable as authoring tools cannot always do this reliably (the geometrical proximity is also easier to compute then defining the geometric bounded surface of the interface) but since this depends on information provided at the authoring stage it's more efficient to compute.

### ISSUE THREAD

**Issue by DprOliv** [IfcOpenShell/IfcOpenShell#2686]
You could either use `ifcopenshell.geom.tree` and then `.select(extend=0.01)` (or some other small number) to get geometrical neighbours. This requires evaluating all the geometry which is potentially computationally expensive. It also requires some manual filtering of the results because you would get also vertical neighbours which you do not seem interested in. The other alternative is to depend on space boundaries (IfcRelSpaceBoundary) provided by the authoring tool to encode the information of which element bound which space. This can in some cases be less reliable as authoring tools cannot always do this reliably (the geometrical proximity is also easier to compute then defining the geometric bounded surface of the interface) but since this depends on information provided at the authoring stage it's more efficient to compute.

_Originally posted by @aothms in https://github.com/IfcOpenShell/IfcOpenShell/discussions/2656#discussioncomment-4440809_

**Comment by Moult** [comment]
This is not a bug, and you've posted 3(?) times? https://github.com/IfcOpenShell/IfcOpenShell/discussions/2656#discussioncomment-4652146
