### ISSUE TITLE
Missing Faces On Some Geometry

### ISSUE THREAD

**Issue by tldddd** [IfcOpenShell/IfcOpenShell#2688]
A number of objects and IFC models do correct import all their faces into BlenderBIM. The objects import as expected in all other IFC viewers I have tested.  I have attached a minimal example with one object.

Using Blender 3.3 and BlenderBIM 230107.

Objects load correctly in BIMVsion (and all other tool BIM viewers test)

![BIMVision-Faces-Exist-1](https://user-images.githubusercontent.com/33082902/211850512-65d9945c-cb25-46e5-aa5a-12f4603de7cc.png)
![BIMVision-Faces-Exist-2](https://user-images.githubusercontent.com/33082902/211850537-8bd1eb8b-f80a-4243-a885-e0f4c141409f.png)

Objects not loading correctly in BlenderBIM, the end faces are missing.

![Blender-Missing-Faces-1](https://user-images.githubusercontent.com/33082902/211851129-eebf7717-1024-4953-8961-b8d5b869ec64.png)
![Blender-Missing-Faces-2](https://user-images.githubusercontent.com/33082902/211851154-f01cd559-6643-4917-ad07-630be7f66de6.png)
[Pour sample_wiped.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/10393902/Pour.sample_wiped.zip)

**Comment by Moult** [comment]
I took a look and couldn't see anything wrong. It seems as though face with step ID 64 cannot be created, but I don't understand why. Ping @aothms.

**Comment by aothms** [comment]
Apparently non-planar face triangulation was malfunctioning after some code restructuring. Should be fine again. Thanks for reporting.

**Comment by tldddd** [comment]
Tested the latest version on a few other models that previously weren't working, and now they are! Thanks for fixing!
