### ISSUE TITLE
*.ifc file parse error using exmaple IfcParseExamples.cpp

### ISSUE THREAD

**Issue by cathty** [IfcOpenShell/IfcOpenShell#269]
error occurs on following line :

#13506= IFCPROPERTYSINGLEVALUE('\X2\00530074006100720074005000740042006F00740074006F006D0045006C00650076\X0\',$,IFCTEXT('\X2\5C425E9568079AD8\X0\'),$);
--

check attachment f3.ifc file 

[f3.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1377706/f3.zip)

**Comment by aothms** [comment]
When I run this file through the latest IfcConvert I get the following error:

~~~
[Error] Unexpected '0' at 85696. Parsing terminated
~~~

Which is on this line:

~~~
#1320= IFCPROPERTYSINGLEVALUE('\X2\00530074006400440072006100770069006E00670073004E0061006D0065\X0\',$,IFCTEXT('\X2\\X0\'),$);
                                                                                                                      ^ here
~~~

And indeed, this is not correct according to the standard:

~~~
EXTENDED2 = REVERSE_SOLIDUS "X2" REVERSE_SOLIDUS
            HEX_TWO { HEX_TWO } END_EXTENDED .
~~~

In  other words there need to be at least two hexadecimal characters of the `\X2\`.

So there is not a lot I can do about this. Other viewers, e.g. Solibri, also object:

![solibri_error_message](https://user-images.githubusercontent.com/1096535/31584905-f1472d38-b1b7-11e7-8008-f41926584b6b.png)


If you want to file a bug report with the originating software feel free to refer to this issue as a reference.

**Comment by cathty** [comment]
aothms,
Thanks very much
