### ISSUE TITLE
Have material operators apply to multiple objects at the same time.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2692]
Have functions such as AssignMaterial, UnassignMaterial, AddConstituent, RemoveConstituent, etc. apply to multiple objects at the same time. 

Is there any reason why this is not the case, currently. If not, i might be able to tackle this one.

**Comment by Moult** [comment]
Assigning / unassigning might make sense, but what about constituents and other set items? Surely you'd just assign to the type and the occurrences will inherit the material?

**Comment by Gorgious56** [comment]
Maybe a "copy material properties to selected" button would be helpful here ?

**Comment by theoryshaw** [comment]
> Maybe a "copy material properties to selected" button would be helpful here ?

Yes, that could be a way forward as well.

**Comment by theoryshaw** [comment]
Took a stab. :)
