### ISSUE TITLE
reassign_class returns new ifc element.

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2701]
This isn't an issue, but rather a question.  I was looking at the API code and realized that the reassign_class api returns a new element with new step-id and global-id.  Is there any plan to offer an option to preserve the original step-id?  My use case for using this function has almost entirely revolved arround correcting misassigned ifc-classes, and as such it makes sense, at least to me, to preserve the original step-id and globalid.

**Comment by Moult** [comment]
Yeah, this was probably written before there was the capability to specify a STEP ID. I think we can do it now. Would you like to try?

**Comment by vulevukusej** [comment]
Oh great, I didn't know you could specify a STEP ID.  Sure, I'll give it a shot.
