### ISSUE TITLE
issue with Transformation matrix

### ISSUE THREAD

**Issue by farazkhalidsiddiqui** [IfcOpenShell/IfcOpenShell#2702]
![image](https://user-images.githubusercontent.com/5821070/212691827-47440d79-aea0-4bdf-89ed-0c39953d5522.png)

**Comment by farazkhalidsiddiqui** [comment]
I am trying to get Transformation matrix based on guid.
Exported data from tekla-structures seems to be correct.
But exporting it from ifcopenshell doesnt seems to work for me.
To make it similar to tekla-structure data the changes i am doing is not consistent. as you can see, switching column 2 and 3 is the only common step.
Is there any way to get Quaternion rotation data from ifcopenshell ? 
I want to use this data in unity 3D.

**Comment by aothms** [comment]
When you say "Python Generated json", did you use `ifcopenshell.util.placement.get_local_placement()`? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/placement.py#L46

**Comment by Moult** [comment]
Also see relevant code example: https://blenderbim.org/docs-python/ifcopenshell-python/code_examples.html#get-the-xyz-coordinates-of-a-element

It's not a quaternion but I guess there are libs like https://pypi.org/project/Quaternion/

**Comment by farazkhalidsiddiqui** [comment]
> When you say "Python Generated json", did you use `ifcopenshell.util.placement.get_local_placement()`? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/placement.py#L46

yes i have used ifcopenshell.util.placement.get_local_placement() to get transformation matrix for both assemblies main part.
But as i have shown in both assemblies the results are not consistent. I have to perform different operations to make it correct.
The operations are switching columns and in some cases multiply certain column by -.

I want to get a consistent transformation matrix that fixes with similar operations performed.

**Comment by farazkhalidsiddiqui** [comment]
> Also see relevant code example: https://blenderbim.org/docs-python/ifcopenshell-python/code_examples.html#get-the-xyz-coordinates-of-a-element
> 
> It's not a quaternion but I guess there are libs like https://pypi.org/project/Quaternion/

yes i have used same method to get transformation matrix by guid.
Is there any way to get transformation matrix regardless of its direction? Maybe inconsistent results are due to different directions?
I want to find rotation that if i apply inverse of that rotation than the model should align to its original rotation. that is aligned to x axis.

**Comment by aothms** [comment]
Placements in IFC are hierarchical. What will likely be the case is that your tekla export contains only the "relative part" (relative to building storey or building or site, depending on the spatial structure). The data you get from the ifcopenshell api is absolute. That explains why the difference is not consistent, maybe in the one case the model (building, building storey) is rotated 90 degrees.

**Comment by aothms** [comment]
Try:

    ifcopenshell.util.placement.get_axis2placement(element.ObjectPlacement.RelativePlacement)

**Comment by farazkhalidsiddiqui** [comment]
> Try:
> 
> ```
> ifcopenshell.util.placement.get_axis2placement(element.ObjectPlacement.RelativePlacement)
> ```

Still same result

**Comment by aothms** [comment]
Then we need more input from you. The local placement calculation is fairly straight forward. So either the export from tekla is doing something funky, or in tekla the assemblies are handled differently when exported to ifc, or maybe you're comparing different nodes in the hierarchy, or something else.

Btw. IIRC the operation you describe on the left, { X, Z, -Y } is a -90d rotation around X, which is the typical transformation from an Z-Up to a Y-Up axis convention. My guess is the operation you show on the right also does that, but also includes a rotation around Z (like I said, I'd really assume it has to do something with a rotation introduced in another place in the hierarchy).

**Comment by farazkhalidsiddiqui** [comment]
> Then we need more input from you. The local placement calculation is fairly straight forward. So either the export from tekla is doing something funky, or in tekla the assemblies are handled differently when exported to ifc, or maybe you're comparing different nodes in the hierarchy, or something else.
> 
> Btw. IIRC the operation you describe on the left, { X, Z, -Y } is a -90d rotation around X, which is the typical transformation from an Z-Up to a Y-Up axis convention. My guess is the operation you show on the right also does that, but also includes a rotation around Z (like I said, I'd really assume it has to do something with a rotation introduced in another place in the hierarchy).

Thank you for the explanation. So is there any way to get global rotation values of the GUID based element?

**Comment by aothms** [comment]
The module linked by @Moult has a `from_rotation_matrix()` function that should take the topleft 3x3 block of the matrix from ifcopenshell.

**Comment by farazkhalidsiddiqui** [comment]
https://we.tl/t-qz5YqEWJ1U
Above link contains:
- Project ifc file
- AssemblyOrientation by Tekla.json
- Tekla Exported models - Rotation issue fixed
- Files with rotation issue (These files need to be fixed with rotation data)

**Comment by Moult** [comment]
Getting back to this @farazkhalidsiddiqui I'm not quite sure what exactly you want to do. I've taken a look at the files. Can you help explain?

As you can see from the screenshot below, in your Project Model.ifc, the element assembly itself is at the origin with no rotation applied (the light orange axes). In addition, every little part of the assembly (the columns, plates, angle beams etc) have all sorts of different locations and rotations relative to the assembly, and there is no way for the computer to know which is the "main" orientation.

![2023-01-25-142233_1920x1080_scrot](https://user-images.githubusercontent.com/88302/214473223-bba1d047-adeb-4a66-8fbc-3844779bb26e.png)

**Comment by aothms** [comment]
@Moult some background: I worked with them earlier, they build this amazing AR app to feed information to welders based on the assembly in IFC.

> and there is no way for the computer to know which is the "main" orientation.

@farazkhalidsiddiqui Moult's comment is spot on for a potential additional source of confusing between the system and Tekla's internal import. My mind was rather fuzzy on all the details (2 years ago). For what individual element in the assembly is designated as the main element. So I had to look it up. We started off with very cleanly organized files with only a single beam/column in the assembly and the rest plates or accessories. In this case it's clear what the main element is, but this constraint was not general enough to work on most files. So it seems later we simply take an arbitrary element from the assembly, prioritizing first beam, then column, member, accessory. I think there needs to be something in place to prioritize also by length/volume of the element (volume is easiest because it's general and probably good enough).

**Comment by farazkhalidsiddiqui** [comment]
Hi,
Lets assume we already know the main part. And based on that we want to get its rotation value. 
Once we have the rotation value, we need to inverse that rotation to make the whole model align on x axis.
Ideal results for assembly 1101 and 2007 are attached. we are getting this results by using transformation matrix generated by tekla.  
![1101-2007](https://user-images.githubusercontent.com/5821070/215120792-954ea6a3-772d-4a80-9676-fc45580d480c.png)

**Comment by Moult** [comment]
Cool, so I guess this is what you're after?

```python
import ifcopenshell
import ifcopenshell.api
import ifcopenshell.util.element
import ifcopenshell.util.placement
import numpy

model = ifcopenshell.open('/home/dion/tmp/Rotation Issue/Project Model.ifc')
for assembly in model.by_type("IfcElementAssembly"):
    parts = [p for p in ifcopenshell.util.element.get_decomposition(assembly)]
    main_part = [p for p in parts if p.Name == "main piece"][0]
    inverted = numpy.linalg.inv(ifcopenshell.util.placement.get_local_placement(main_part.ObjectPlacement))
    for part in parts:
        new_matrix = inverted @ ifcopenshell.util.placement.get_local_placement(part.ObjectPlacement)
        ifcopenshell.api.run("geometry.edit_object_placement", model, product=part, matrix=new_matrix, is_si=False)
model.write('/home/dion/test.ifc')
```

**Comment by rwar33** [comment]
Faraz is traveling at the moment and we will look at this a little closer when he settles in.  In the meantime, here is a description of the JSON export process out of Tekla:

The origin coordinates in the Orientation XML will be in global space in mm's as the base units. The Vectors will all be normalized for a value of 0 to 1 which is pretty common when translating coordinate systems and keeps the file smaller. The vectors are a magnitude in direction in Global Coordinates from the origin of the assembly. Your guys are going to need to translate every point on parts that are in an assembly to Global if they aren't already, then they will need to take my coordinate system in the XML and make a Matrix transformation of all those global part points to my local coordinate system.

The GUIDS exported are the main part and assembly Tekla Microsoft GUIDS. If in your IFC parser you can only look up IFC guid, I will have to go find my code somewhere that converts Tekla Microsoft GUIDS to IFC Guids.

![image](https://user-images.githubusercontent.com/94859771/215608709-ff1a1187-6261-422d-ad88-ddd955c9054a.png)
![image](https://user-images.githubusercontent.com/94859771/215608818-1049ae30-108d-48f4-b4f5-6aebc787cabe.png)
![image](https://user-images.githubusercontent.com/94859771/215608849-0453b08f-2b03-43c4-bfa5-de2c57956108.png)

Randy
Eterio Realities

**Comment by Moult** [comment]
I think it's OK, when I looked at the file again I noticed that all the main pieces were actually named "main piece" so that was enough to detect it - the code snippet I posted seems to do what I think you're after.

**Comment by rwar33** [comment]
I am going to interject my non-technical input here.  :)  We ran the code and it is so tantalizingly close!  What we are seeing in the results are perfect transformations (rotationally or otherwise) for anything originally oriented horizontally (X and Y).  However, when it comes to an assembly that is orientated vertically (Z-axis) (ie a column). The process fails to some degree.  Is there some type of limitation that we are not aware of?  If so, let us know so we can plan for it and create a workaround.  Or are we missing something?  Here is an output example from the attached project:
![image](https://user-images.githubusercontent.com/94859771/216484230-d9a557ab-7899-4bd9-9fb5-4963ac269712.png)
[Demo Project.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/10574576/Demo.Project.zip)

Thanks in advance,
Randy
Eterio Realities

**Comment by Moult** [comment]
That's because fundamentally the column itself is extruded up the Z axis whilst your beams are extruded along the X axis. I'd consider this incorrect, by the way (though it is not illegal), as I would consider all parametric extrusions should go along the Z axis (as per beam standard case).

So you can either fix it by hardcoding that if it's a column, to rotate it to lie flat along the X axis, or the other way around, hardcoding that if it's a beam, rotate it up to face the Z axis.

Here's an example of option 1:

```python
import ifcopenshell
import ifcopenshell.api
import ifcopenshell.util.element
import ifcopenshell.util.placement
import numpy

model = ifcopenshell.open('/home/dion/tmp.ifc')
for assembly in model.by_type("IfcElementAssembly"):
    parts = [p for p in ifcopenshell.util.element.get_decomposition(assembly)]
    main_part = [p for p in parts if p.Name == "main piece"][0]
    inverted = numpy.linalg.inv(ifcopenshell.util.placement.get_local_placement(main_part.ObjectPlacement))
    for part in parts:
        new_matrix = inverted @ ifcopenshell.util.placement.get_local_placement(part.ObjectPlacement)
        if main_part.is_a("IfcColumn"):
            new_matrix = numpy.array([
                [0, 0, 1, 0],
                [0, 1, 0, 0],
                [-1, 0, 0, 0],
                [0, 0, 0, 1],
            ]) @ new_matrix
        ifcopenshell.api.run("geometry.edit_object_placement", model, product=part, matrix=new_matrix, is_si=False)
model.write('/home/dion/test.ifc')
```

**Comment by rwar33** [comment]
That should do it!  Thanks for all of your help, everyone!!
