### ISSUE TITLE
A bug with arrays...

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2708]
A bug with arrays...

https://community.osarch.org/discussion/comment/14251/#Comment_14251

**Comment by theoryshaw** [comment]
This bug was introduced on this release.
https://github.com/IfcOpenShell/IfcOpenShell/commit/0ccea3cef8d0ca5fcf22b95a3d95bcf8e939f3db

**Comment by Moult** [comment]
@myoualid fixed this: https://github.com/IfcOpenShell/IfcOpenShell/commit/1e2ac1fe24c6ba492c8359d805c5902695f77fd4
