### ISSUE TITLE
Sverchok addon starting

### ISSUE THREAD

**Issue by nortikin** [IfcOpenShell/IfcOpenShell#2711]
Expectations - copy addon, activate addon and from addon properties install local pip ifcopenshell lib

Result - cannot activate and try to guess what to do

**Comment by nortikin** [comment]
also 
```bash
\3.4\scripts\addons\blenderbim\bim\helper.py", line 27, in <module>                                                                                                           from ifcopenshell.util.doc import get_attribute_doc, get_predefined_type_doc, get_property_doc                      ModuleNotFoundError: No module named 'ifcopenshell.util.doc' 
```

**Comment by nortikin** [comment]
both, blenderbim and ifcsverchok say the same. what doc is ment?

**Comment by aothms** [comment]
doc.py was added in Oct 14 https://github.com/IfcOpenShell/IfcOpenShell/commits/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/doc.py

But the version published on pip is Oct 13 https://pypi.org/project/ifcopenshell/#history

@Moult

**Comment by aothms** [comment]
You can manually copy the latest ifcopenshell build into your site-packages folder https://github.com/IfcOpenBot/IfcOpenShell/commit/07ee62eb914a24c1326a9cd21164c9b1bfe30895#commitcomment-96660017

**Comment by Moult** [comment]
It seems the Github action to publish to PyPI stopped working as the Python version was no longer supported: https://github.com/IfcOpenShell/IfcOpenShell/commit/49b5bbd5858878a7b01eaf1dcd19d591c33f91c1

This should be fixed in the next release next week.
