### ISSUE TITLE
root.remove_product infinite loop

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2712]
Since b41878e `root.remove_product` has been hanging here. I narrowed it down to this test case involving deleting a building that has a *IfcRelServicesBuildings*:

[test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10473170/test.ifc.txt)

To reproduce:

```
import ifcopenshell
from ifcopenshell.api import run
file = ifcopenshell.open("test.ifc")
building = file.by_type("IfcBuilding")[0]
run("root.remove_product", file, product=building)

**Comment by theoryshaw** [comment]
just a hunch, but think the following might be related, as well. 
https://github.com/IfcOpenShell/IfcOpenShell/issues/2708

**Comment by aothms** [comment]
Hm yes, on 2nd thought that while loop was pretty dangerous. 

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/api/root/remove_product.py#L84-L119

There is no else statement, so in cases where the inverse is not of the preselected list of types, it doesn't get deleted. I would be tempted to replace all of these:

```python
            elif inverse.is_a("IfcRelSpaceBoundary"):
                self.file.remove(inverse)
            elif inverse.is_a("IfcRelFillsElement"):
                self.file.remove(inverse)
            elif inverse.is_a("IfcRelVoidsElement"):
                self.file.remove(inverse)
```

with a simple (at the bottom):

```python
            elif inverse.is_a("IfcRelationship"):
                self.file.remove(inverse)
```

products shouldn't have (many) non-relationship inverses, but I guess it should also be accounted for by then replacing the where condition with:

```python
while inverses := list(filter(lambda i: i.is_a('IfcRelationship'), self.file.get_inverse(self.settings["product"]))):
```

but I don't feel very confident doing so, so I'll wait for @Moult to have a look.

**Comment by Moult** [comment]
The reason the monster ifelse is there is because I feel it's a bit of learning journey to understand what constitutes a safe deletion of a product, at the risk of dangling / orphaned relationships, I'd prefer to one by one address each relationship as it comes along. As I/we get a better understanding of how to safely prune the graph, I'm happy to make it smarter / group things under IfcRelationship etc, but I really don't feel now is the time.

**Comment by aothms** [comment]
This would reopen #2697.

I now see the comment there:

> This is invalid data, so the segfault is acceptable?

I would disagree with that. segfault is never acceptable. It can be lower priority in case we have purely rubbish data, but if we have identified a somewhat sensible case like this, leaving the segfault sit there when we have a reasonable workaround shouldn't be the way to go.

Iterating over a list while modifying it's content (which might also happen in other cases besides mls-mlsu interactions) is bad practice in general.

If you don't want a catch-all relationship removal then a simple solution is to not reiterate over it using another way

```python
ignored = set()
while inverses := set(self.file.get_inverse(self.settings["product"])) - ignored:
    inverse = next(iter(inverses))
    if ...
    
    else:
        ignored.add(inverse)
```

> I'd prefer to one by one address each relationship as it comes along

That's still an option, but maybe we should log this then.

**Comment by Moult** [comment]
Makes sense, I've readded your implementation.

I'll make a mental note to add test cases for every single possible relationship type in the future.

**Comment by brunopostle** [comment]
Here's another infinite loop with `root.remove_product`, removing one of two storeys in this building never completes, it is fine if there is only one storey in the first place:

simple validated [test.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10514365/test.txt) IFC file with 43 entities

```
import ifcopenshell
from ifcopenshell.api import run
file = ifcopenshell.open("test.ifc")
storey = file.by_type("IfcBuildingStorey")[0]
run("root.remove_product", file, product=storey)
