### ISSUE TITLE
Error when saving/export .blend/.ifc files

### ISSUE THREAD

**Issue by raphaelperez** [IfcOpenShell/IfcOpenShell#2723]
Hi, I don't kown if this is the right place to report this, but I am getting some trouble when saving my files.
If I import the .ifc in a blank .blend file and then export, it works ok. But when I try to export this same .ifc from my project .blend file, I get this error message:
![image](https://user-images.githubusercontent.com/35978398/214722346-4f1658b4-4da4-449b-960a-345198b484a1.png)

**Comment by Moult** [comment]
The .blend file doesn't store anything. So if you save a .blend file, then move the original ifc, then try to save/export, it'll fail because the blend file doesn't have any data.

Exactly what steps are you doing?

**Comment by raphaelperez** [comment]
I use uv unwrapping on the ifc objects to then bake textures. Is it ok to do that? I believe this is .blend files features.

**Comment by Moult** [comment]
@raphaelperez as in do you:

 1. Open blender
 2. Load the IFC
 3. ... then what? Do you move files around? Do you delete objects?
 4. Press save/export IFC
 5. Error occurs

**Comment by raphaelperez** [comment]
I use to open the .blend file and the ifc is already loaded. i did append a sofa heavy mesh to a empty ifcfurniture to not overload my ifc file, then I did a mistake on the work schedule set up and try to remove that ifcfurniture. Then I could not save/export anymore.
This part of the ui doesnt show for a while in this project file:
![image](https://user-images.githubusercontent.com/35978398/214725961-789036d1-26d5-4cca-924b-de480174e5d6.png)

Fortunetly, I put the export IFC button on a Quick Favorites of blender.

**Comment by raphaelperez** [comment]
When I try to Save Project on the Quick Favorites or File>export>IFC, this error message shows.

**Comment by Moult** [comment]
> i did append a sofa heavy mesh to a empty ifcfurniture to not overload my ifc file

What exactly do you mean? Appending a regular Blender mesh shouldn't damage the IFC connection. But what do you mean by an empty IfcFurniture? Did you create an empty then assign it as an IfcFurniture class?

**Comment by raphaelperez** [comment]
![image](https://user-images.githubusercontent.com/35978398/214727783-173a6cf1-5b4e-4711-b041-42bced93c1dc.png)

**Comment by Moult** [comment]
Did the sofa object come from another IFC? Or is it a regular Blender mesh that you appended with File->Append?

**Comment by raphaelperez** [comment]
It is a regular Blender mesh that I appended

**Comment by Moult** [comment]
Hmm, shouldn't be an issue.

1. Load IFC
2. Append Blender mesh
3. Add new empty
4. Assign empty to IfcFurniture (or any class)
5. Parent mesh to IfcFurniture
6. Save IFC

Those steps work fine for me. There must be some step you're doing that I'm not aware of.

**Comment by raphaelperez** [comment]
ok, that must be some mess I made. Thanks!

**Comment by Moult** [comment]
If you can recreate it, it would be very valuable, since it is critical to fix these types of bugs.

**Comment by raphaelperez** [comment]
Yes, I am taking another strategy. I'm separating the ifc meshes from the regular Blender meshes that I uv unwrap to export to gltf. This seems to be working better. Thanks a lot!
