### ISSUE TITLE
Using add with a STEP ID cause a segfault

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2726]
Since this commit https://github.com/IfcOpenShell/IfcOpenShell/commit/d9f1cb5525f57e7b2ea78647c730f74d62405032 there is now a segfault for all of these testcases: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/test/api/root/test_reassign_class.py#L24-L44

It segfaults upon calling `ifc_file.add(new_element, element.id())`. Changing it to just `ifc_file.add(new_element)` fixes the segfault, but defeats the purpose of the commit.

Upon reading the commit, indeed it makes no sense to do ifcopenshell.create_entity() (i.e. an entity without an associated file) and then do `replace_attribute` in the context of a file... so I'm kinda not surprised it's segfaulting. Is there a way to "change" the STEP ID after creation? That would be ideal.

Thoughts @aothms ?

**Comment by Moult** [comment]
Also ping @vulevukusej did this somehow work for you?

**Comment by vulevukusej** [comment]
@Moult I don't remember having issues with this.

**Comment by vulevukusej** [comment]
I see what you mean though with replace_attributes.  Shall I reverse those changes? Also interested in a solution for this as well.

**Comment by aothms** [comment]
I don't get a segfault here on my system. But I can try a bit harder to reproduce if I have to on linux.

The only thing I can think of is that you might have to do some very ugly swap. So that you can first assign temp, remove old, add new, then replace, then remove old.

Because indeed, if you already have assigned the element as an attribute value it will effectively be part of the file already.

```python
def reassign_class(ifc_file, element, new_class):
    try:
        new_element = ifcopenshell.create_entity(new_class)
        new_element.GlobalId = element.GlobalId
        
        temp_element = ifcopenshell.create_entity(new_class)
    except:
        print(f"Class of {element} could not be changed to {new_class}")
        return element
    new_attributes = [new_element.attribute_name(i) for i, attribute in enumerate(new_element)]
    
    for i, attribute in enumerate(element):
        try:
            new_element[new_attributes.index(element.attribute_name(i))] = attribute
        except:
            continue
    
    for inverse in ifc_file.get_inverse(element):
        ifcopenshell.util.element.replace_attribute(inverse, element, temp_element)
    
    ifc_file.remove(element)
    ifc_file.add(new_element, element.id())
    
    for inverse in ifc_file.get_inverse(element):
        ifcopenshell.util.element.replace_attribute(inverse, temp_element, new_element)
    
    ifc_file.remove(temp_element)
    
    return new_element
```

If you're worried about the performance of this monstrosity there is still the `get_inverse(with_attribute_indices=True)` trick you can use.

**Comment by Moult** [comment]
BTW here is a minimal snippet that segfaults on my system:

```python
import ifcopenshell

def reassign_class(ifc_file, element, new_class):
    new_element = ifcopenshell.create_entity(new_class)
    ifc_file.remove(element)
    ifc_file.add(new_element, element.id())

file = ifcopenshell.file()
element = file.createIfcWall(GlobalId=ifcopenshell.guid.new())
reassign_class(file, element, "IfcSlab")
```

**Comment by Moult** [comment]
I did an implementation which I think works without the need for a temporary element, but as a tradeoff makes some assumptions that the inverse can either reference the element directly or in an iterable. I think that assumption is safe for IfcElements and IfcElementTypes which you'd want to reassign the class of, but will fail if you use the function for things that it's not intended for, like if you use it for a cartesian point which is used multiple times in an inverse (e.g. the start and end of a polyline), where `get_inverse(with_attribute_indices=True)` only returns the top level index so we don't know how many times its used.

**Comment by aothms** [comment]
I like this, this is good, but I made a quick note on where this would fail https://github.com/IfcOpenShell/IfcOpenShell/commit/c0c6c23fca1007d4f4a8eb38927bfe8c50b1a34f

(also occurrences of reassigned instance within an ordered aggregate (such as IfcRelNests))

**Comment by Moult** [comment]
Thanks! Yeah I suspect in real life scenarios it won't have much of an impact. The ambiguous definition of relnests seems to be that order matters for non-physical things (e.g tasks and subtasks) however for physical things i get the impression that order doesn't matter too much for nesting and nesting seems to denote more of a host parent / child moves with host type relationship.

I really should make it a habit to be documenting as I go instead of waterfall.
