### ISSUE TITLE
Should ifcopenshell_wrapper.py be committed?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2730]
Isn't https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/ifcopenshell_wrapper.py generated? Should it be committed?

**Comment by aothms** [comment]
You're right e92d908063e8683ce22ba4381d419f9540ed4a61
