### ISSUE TITLE
IFC Array throws 'got an unexpected keyword argument 'product'

### ISSUE THREAD

**Issue by otapi** [IfcOpenShell/IfcOpenShell#2731]
I add a new object, e.g. an ifcBeamType, then on the modifier tab of the object try to add IFC Array. At applying the modifier, it throws the error 'got an unexpected keyword argument 'product''. It also creates one duplicate of the original object in the same place with x.001 name, like ifcBeam/Beam.001.
Should make an array, e.g. 10 copies of the original object.

Using Blender 3.4.1, BlenderBIM ver 0.0.230107
![image](https://user-images.githubusercontent.com/31888571/215844788-d60d44be-0000-4afe-b7a7-9a185f9f0e47.png)

**Comment by Moult** [comment]
Arrays make no sense to be added to element types (e.g. IfcBeamType), they can only be added to IfcBeams. Can you test with the latest unstable release? https://blenderbim.org/docs/devs/installation.html#unstable-installation I think this may have already been fixed.

**Comment by otapi** [comment]
The selected object was the ifcBeam, not the ifcBeamType.
Anyway, I installed the version 0.0.230201, it seems this was fixed, and the IFC Array works properly now.
