### ISSUE TITLE
(Flask/FastAPI) Python crashes when adding properties with enumerations

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2732]
So this is a weird one.  Performing the following steps causes python to crash (without a trace log), but only when running on a Flask/FastAPI server:

1. Add a pset to an existing object that includes properties of type IfcEnumerationValue
2. Run utils.get_psets on the object
3. Crash!

In the debug panel just before it crashes, you can see under HasProperties that instead of the properties you see <ifcopenshell.entity..> which I've not encountered before.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/83825269/216347635-447b3ad4-c874-49ed-86a3-7f1e4e8271dc.png">

If i try and expand HasProperties then python and my server crash without any error messages.

**Comment by aothms** [comment]
Can you share some code to reproduce? It's probably something related to
threading. In general keeping a live file open in a situation like this
will be risky, especially with multiple with workers.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 2 feb. 2023 15:15 schreef Vukas Pajic ***@***.***>:

**Comment by vulevukusej** [comment]
@aothms thanks for the quick reply!  Sure - here's the route to handle adding a template to an object:

`
@app.post("/api/addPsetTemplateToObject")
async def add_pset_template_to_object(request: Request):
    global ifc

    request_data = await request.json()
    pset_id = request_data["psetId"]
    selected_step_id = request_data["selectedStepId"]
    ifc_object = ifc.by_id(selected_step_id)

    template_file = ifcopenshell.file.from_string(request.session["pset_template_file"])
    pset_template = template_file.by_id(int(pset_id))

    pset_name = pset_template.Name
    applicable_entity = pset_template.ApplicableEntity
    template_type = pset_template.TemplateType
    property_templates = pset_template.HasPropertyTemplates

    properties = {}

    new_pset = ifcopenshell.api.run("pset.add_pset", ifc, product=ifc_object, name=pset_name)

    for prop_template in property_templates:
        prop_name = prop_template.Name
        prop_template_type = prop_template.TemplateType
        prop_measure_type = prop_template.PrimaryMeasureType
        data_type = value_type_dict[prop_measure_type]

        default_prop_value = {"string": "", "integer": 0, "real": 0.00, "number": 0.00, "boolean": False}[data_type]

        if prop_template_type == "P_SINGLEVALUE":
            properties[prop_name] = default_prop_value
            ifc_value_entity = getattr(ifc, f"create{prop_measure_type}")(default_prop_value)

        elif prop_template_type == "P_ENUMERATEDVALUE":
            enum_values = prop_template.Enumerators.EnumerationValues

            ifc_property_enumeration = ifc.create_entity(
                "IFCPROPERTYENUMERATION",
                Name=prop_name,
                EnumerationValues=enum_values,
            )

            ifc_value_entity = ifc.create_entity(
                "IFCPROPERTYENUMERATEDVALUE",
                Name=prop_name,
                EnumerationReference=ifc_property_enumeration,
                EnumerationValues=(
                    enum_values[0],
                ),  # TODO: EnumerationValues is optional in IFC4, but required in IFC2x3.  Need to handle this based on the current file schema
            )

        ifcopenshell.api.run("pset.edit_pset", ifc, pset=new_pset, properties={prop_name: ifc_value_entity})

    return Response(status_code=200)
    `

**Comment by vulevukusej** [comment]
and then getting the properties after they've been added:

`
@app.get("/api/getObjectMetadata/{stepId}")
def getObjectMetadata(stepId: int, request: Request):
    global ifc

    request.session["selected_step_id"] = stepId
    ifc_entity = ifc.by_id(stepId)
    psets = ifc_tools.get_psets(ifc_entity, psets_only=True)
    qsets = ifc_tools.get_psets(ifc_entity, qtos_only=True)
    element_type = getattr(get_type(ifc_entity), "Name", None)
    element_class = get_type(ifc_entity).is_a() if element_type else None
    # material = get_material(ifc_entity)
    spatial = getattr(get_container(ifc_entity), "Name", None)
    decomposition = get_decomposition(ifc_entity)
    aggregate = get_aggregate(ifc_entity)
    parts = get_parts(ifc_entity)

    attributes = {}
    data = ifc_entity.get_info()
    for key, value in data.items():
        if value is None or isinstance(value, ifcopenshell.entity_instance):
            continue
        attributes[key] = str(value)

    return {
        "psets": psets,
        "qsets": qsets,
        "element_type": {"Element Type": {
            "class": element_class,
            "name" : element_type,
            }},
        "spatial": {"Spatial Container": spatial},
        "attributes": attributes
        }
`

**Comment by vulevukusej** [comment]
I'm using global ifc temporarily as I'm testing.. Perhaps this is where the issue lies?

**Comment by vulevukusej** [comment]
it crashes when calling get_psets, which is a 1:1 copy of the utils.element.get_psets function already in the ifcopenshell library.

**Comment by vulevukusej** [comment]
I tried using threading.Lock() to restrict access to the global "ifc" variable, but unfortunately this didn't solve the problem.

**Comment by aothms** [comment]
Some more effort is required to turn this into something reproducible (ideally full flask code + curl commands or sth). But how sure are you this is really dependent on running it in Flask? We've seen similar cases where loops + api calls can sometimes result in this kind of behaviour:

```
for prop_template in property_templates:
    ...
    ifcopenshell.api.run("pset.edit_pset", ifc, pset=new_pset, properties={prop_name: ifc_value_entity})
```

if pset.edit_pset() somehow affects the values in property_templates the list being iterated over might become invalid. Maybe it's just that in Flask you triggered a different set of interactions?

**Comment by vulevukusej** [comment]
It definitely happens only in flask.  I have the exact same code running in a seperate python file that I just run manually, and there aren't any issues. 

Interestingly, I found a workaround by adding the following two lines after the loop - although these two lines can take quite a while for large files:

```
    ifc_to_string = ifc.to_string()
    ifc = ifcopenshell.file.open(ifc)
```

Could this be a clue as to why this is happening?  I'll prepare a repo to reproduce this issue tomorrow.  Thanks for your help @aothms

**Comment by vulevukusej** [comment]
Ok, lesson learned for the future.  Always try to recreate the problem in the smallest possible form - it makes finding the error so much easier! 😊.  Apparently the problem was saving the template-file to session storage (flask_session extension).  In the recreated version I saved the ifcopenshell-instance of the file to a global variable, similarly to how I did with the ifc file.  No more problems!  Reading a little on it reveals that the session variables are not thread-safe, so perhaps your hunch was right all along @aothms ?

In any case, I consider the issue closed, thanks for your help!

**Comment by Moult** [comment]
FWIW that's the same reason the UI in Blender has data classes which only ever serve up plain Python data types to the UI rather than any entity instances. Otherwise it becomes crashtastic :)

**Comment by aothms** [comment]
@vulevukusej do you have that minimal sample though. I'd still like to understand how this precisely caused the segfault.

**Comment by vulevukusej** [comment]
@aothms sorry for the delay, i was out of action last week.  Here's a link to a minimal example: https://github.com/vulevukusej/ifcopenshell-flask-segfault

Weirdly, I just ran it again and didn't get any issues 😕.  I did change laptops though..

**Comment by aothms** [comment]
Ok thanks, if it doesn't segfault anymore then I propose to leave it be.

There are various things we could try in the future like using a queue [0] to make sure ifc file operations are not executed simultaneously. The issue isn't so much multithreading because python has the GIL, but rather maybe the interleaving of various lower or higher level api calls.

[0] https://stackoverflow.com/questions/18989446/execute-python-function-in-main-thread-from-call-in-dummy-thread
