### ISSUE TITLE
BlenderBim - Issue with drawing scale 

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2735]
When changing a newly made elevation or plan drawing from 1:100 to 1:50, the printed SVG shows annotations at the correct scale but not the model representation

please see reference:
SVG:
![image](https://user-images.githubusercontent.com/78321676/216547188-edd82be3-c822-4c3b-8903-08bcd7c11ebe.png)

Blender:
![image](https://user-images.githubusercontent.com/78321676/216547219-bb66e2a4-1fdd-4fc7-b414-28ba49595484.png)

Using Blender 3.3 LTS
blenderbim-230202

**Comment by Moult** [comment]
Yeah I'm in the middle of fixing a couple things related to scale and representations. For now, does the EPset_Drawing pset on the camera object show the right scale?

**Comment by Plae-Blue-Dot** [comment]
Changing it manually in the EPset worked, thanks Dion
