### ISSUE TITLE
Drawing serialiser shows things see-through if solids are extruded along negative Z

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2736]
I've noticed that if a representation is made out of extruded area solids which are extruded along the negative Z then the generated drawing draws them as see-through / X-ray.

Is a negative Z extrusion direction allowed? I assume it's treating it as some form of backface? I couldn't see anything in the spec explicitly disallowing it, but there is a suggestion that the direction should be generally in the +Z of the position.

Notice how the chair (and the table/chair combo too, but the chair is selected) is see through. The sofa however uses +Z directions and is not see through.

As a side note, there is some coincident edge fighting happening, you can see how a line is missing where the interior wall hits the exterior wall. Not sure if there is any easy solution for this.

[test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10595628/test.ifc.txt)

![2023-02-04-142221_1686x660_scrot](https://user-images.githubusercontent.com/88302/216745666-858022a6-8fc4-4399-a0a7-da9bdf3caa81.png)

![2023-02-04-142646_836x713_scrot](https://user-images.githubusercontent.com/88302/216745686-d202de43-e0f0-4483-949d-92d35b38ddfe.png)

**Comment by Moult** [comment]
Forgot to ping @aothms

**Comment by aothms** [comment]
> see-through

This is likely the `SvgSerializer.setProfileThreshold()` https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/draw.py#L58

This was discussed in #1153 but the the thread is impossible to search now.

As an optimization mechanism you can render dense objects as just a wireframe to dramatically speed things up. This generally looks ok-ish on orthogonal drawings, but doesn't make a lot of sense in this case.

> edge fighting 

I haven't frequently seen this, but I don't generate views like this often. How widespread is this issue? If I look at the global x-coords in blender based on the dae I don't see anything surprising. But not sure if this approach is precise enough to detect any errors on the 64bit math happening inside occt.

```
>>> [bpy.context.object.matrix_world * v.co for v in bpy.context.object.data.vertices if v.select]
[Vector((5.496272563934326, 2.751748561859131, 3.0))]
>>> [bpy.context.object.matrix_world * v.co for v in bpy.context.object.data.vertices if v.select]
[Vector((5.496273040771484, 4.999996662139893, 3.0))]
>>> [bpy.context.object.matrix_world * v.co for v in bpy.context.object.data.vertices if v.select]
[Vector((5.49627161026001, 0.09999990463256836, 3.0))]
```

Judging from the data we can get from occt https://dev.opencascade.org/doc/refman/html/class_h_l_r_b_rep___h_l_r_to_shape.html there doesn't seem to be anything specific to face-face intersections. So based on the severity of this issue we might need to shorten walls connected start/end to path?

**Comment by Moult** [comment]
Ah awesome! Yes I completely forgot about that discussion. Rereading now it makes sense, sorry for the noise.
