### ISSUE TITLE
*.ifc parsing error

### ISSUE THREAD

**Issue by cathty** [IfcOpenShell/IfcOpenShell#274]
ifcparser occurs error in following line:

#1160= IFCPROPERTYSINGLEVALUE('\X2\005300076\X0\',$,IFCTEXT('\X2\\X0\'),$);

the cause is there no data between '\X2\'   and  '\X0\' of  IFCTEXT;

I wonder if this is a  bug or ifcopenshell can handle it ?

thanks very much!

**Comment by aothms** [comment]
Isn't that the same issue as I described in my reply here: https://github.com/IfcOpenShell/IfcOpenShell/issues/269

As I shown with a quote from the standard there do need to be characters between `\X2` and `\X0`.

**Comment by cathty** [comment]
got it， thanks  a lot
