### ISSUE TITLE
UI amendment - Filtering Psets (across all IfcElements) by Phase

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#2741]
Simplify the process of filtering projects by phase. Currently every Pset requires manual filter creation to generate existing, demo, proposed drawings. Global filter by phase required to expedite drawing creation. Current example filtering set-up below: -

![image](https://user-images.githubusercontent.com/26485679/216950150-a7068909-c1f4-4aa0-8fc0-554656bace16.png)

**Comment by Moult** [comment]
IfcCSV has support for wildcard attributes. It would be good to add wildcard pset names support to the selector util, which would solve half this problem. The other half could be solved by a better UI masking the complexity of assigning and managing statuses until buildingSMART cleans up this mess.

**Comment by ChubbyQuark** [comment]
Could groups or presentation layers be used as a workaround? Ive created a few test groups in a demo project but they dont seem to get respected by the 'include' or 'exclude' filters when creating a drawing.

**Comment by Moult** [comment]
Note that wildcards are now supported. I'd like to keep this bug open until we have a good "Phase manager" or something similar.

**Comment by ChubbyQuark** [comment]
Great! Is this accessible via the selector interface?

[image: image.png]

**Comment by vulevukusej** [comment]
@Moult im on holidays until the 17th - If it isn't updated by then I'll add the capability.

**Comment by Moult** [comment]
@vulevukusej 

![4cik6g](https://user-images.githubusercontent.com/88302/232631323-672cbc02-29e3-4e49-bcc8-ca1265937ef0.png)

**Comment by vulevukusej** [comment]
@ChubbyQuark you can utilize @Moult 's regex update immediately, by activating the manual override in the UI:
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/83825269/232692432-6e75b310-5344-4b60-8367-5e1af12a8f93.png">

In the example above, I generated the base query using the UI, then activated the manual override and updated the query to include regex.

So instead of the generated syntax: 
.IfcWall[AC_Pset_Name.Name = "Wand-007"] 
      I instead had
.IfcWall[r"AC_Pset_*"."Name"= "Wand-007"] which just matched any pset starting with AC_Pset_

**Comment by vulevukusej** [comment]
@Moult I kinda prefer this workflow, as opposed to building specific UI around this, since the IfcSelector UI already gets rather cramped horizontally.  I tried adding a regex toggle before the PsetName, PropName and Value but it got ugly..  What do you think? P.S. Don't get all Gimli-like on me and bound me forever ;-)

**Comment by Moult** [comment]
Hehehe yes @vulevukusej you're right, the UI is already pretty complex. I agree that this is advanced usage and should be under the manual toggle as you've already suggested.

That UI needs some work. Not entirely sure how though :)

**Comment by pierremonico** [comment]
> @ChubbyQuark you can utilize @Moult 's regex update immediately, by activating the manual override in the UI: <img alt="image" width="1211" src="https://user-images.githubusercontent.com/83825269/232692432-6e75b310-5344-4b60-8367-5e1af12a8f93.png">
> 
> In the example above, I generated the base query using the UI, then activated the manual override and updated the query to include regex.
> 
> So instead of the generated syntax: .IfcWall[AC_Pset_Name.Name = "Wand-007"] I instead had .IfcWall[r"AC_Pset_*"."Name"= "Wand-007"] which just matched any pset starting with AC_Pset_

@vulevukusej are wildcards also supported in the actual value of the property? I wrote a few test cases but can't seem to match anything, so it seems it doesn't. 

I.e. using the [test file from the docs](https://www.ifcwiki.org/images/e/e3/AC20-FZK-Haus.ifc), this test doesn't pass:
```
    def test_select_by_name_with_wildcard(self):
        selector = Selector()
        query = '.IfcElement[r"Name"="Wand.*"]'
        elements = selector.parse(self.model, query)
        
        self.assertEqual(
            len(elements),
            4
        )
```

**Comment by pierremonico** [comment]
Reading the [source code](https://github.com/IfcOpenShell/IfcOpenShell/blob/3d441b4ad3dd43683468a65cb83d617231bb13ee/src/ifcopenshell-python/ifcopenshell/util/selector.py#L51) I believe the answer to my question to be negative (even though for my particular use case one can write `'.IfcElement[Name*="Wand-Ext-OG"]'`). 

Would support for regexes in values be hard to implement? 

PS: why are the docs instantiating the selector `selector = Selector()` when actually it only has class methods? :)

**Comment by Moult** [comment]
@pierremonico yeah regex values aren't supported yet. Would you mind adding a new bugreport to track that if you want it?

The docs are outdated, would appreciate a PR to fix that :)

**Comment by pierremonico** [comment]
@Moult couldn't find any guidelines on how you guys track bugs, so I hope #3113 is good enough. 

Regarding selector docs happy to contribute but I need some time to figure out the whole syntax, not that easy when mostly relying on reading the source code :) Luckily the [tests](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/test/util/test_selector.py) help with that.
