### ISSUE TITLE
[IfcQuery Syntax] What to do, when in the Psetname is an .

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2745]
For example an ifc file has some random ifc wall with an Pset named OurPropertiesVersion.1

How do then the query?

ExampleCode below from https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#IFC_Query_Syntax

`wall_is_external = selector.get_element_value(wall, "Pset_WallCommon.IsExternal")`

Now with the OurPropertiesVersion.1

`wall_is_heavy = selector.got_element_value(wall, "OurPropertiesVersion.1.isHeavy"`

Now it has two Points

**Comment by vulevukusej** [comment]
One quick workaround would be to rename "OurPropertiesVersion.1" to "OurPropertiesVersion1" using the Bulk Editor Tool, after which you can proceed as normal.

**Comment by vulevukusej** [comment]
If you're not using BlenderBIM and are just running python directly, have a look at the code here and adapt accordingly: [Code](https://github.com/IfcOpenShell/IfcOpenShell/blob/7a3e53a9f84cb3f793c8204a148ee0d26f399959/src/blenderbim/blenderbim/bim/module/pset/operator.py#L504)

**Comment by vulevukusej** [comment]
I've also run into a few fringe cases as well, but more often than not it seems more reasonable to follow best-practice naming standards then to spend time refactoring the code to be more fool-proof.  What are your thoughts  @Moult ?

**Comment by Martin15135215** [comment]
Thanks for the info :)

**Comment by Moult** [comment]
@vulevukusej what other fringe cases have you run into? For "." we could allow escape characters?

**Comment by vulevukusej** [comment]
If I remember correctly, psets starting with a " or # Character would not work.
