### ISSUE TITLE
Unexpected result when trying to extract IfcSpace using "ExtractElements"

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2753]
Sample file (FZK Haus): https://www.ifcwiki.org/index.php?title=KIT_IFC_Examples

Using the "ExtractElements" recipe with the query: ".IfcSpace" this is what I see in blender and in other viewers:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/83825269/217760043-41713ceb-15a7-44b5-bffb-60b387e85bde.png">

What I expect to see is:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/83825269/217760230-580bcf29-0fea-4ad4-8151-0820a3736088.png">

**Comment by aothms** [comment]
The green ring is the IfcSite geometry. In recent years, IfcSite geometry is no longer recommended in favour of using, e.g IfcGeographicElement, for exactly this reason. I can't comment on why the actual sites are not there though... is it a visibility setting or are they really not included in the file?

**Comment by vulevukusej** [comment]
I should be seeing all the rooms in the house, since they are all IfcSpace.  Haven't looked at the file to see if the elements are at all there though, I'll check and report back.

**Comment by vulevukusej** [comment]
@aothms so it appears the IfcSpaces _are_ there, but they aren't visible (neither in BBIM or BimVision)

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/83825269/218330360-73f925f5-25b0-4236-8317-c340acf14fd5.png">

**Comment by vulevukusej** [comment]
[AC20-FZK-Haus - spaces only.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10716902/AC20-FZK-Haus.-.spaces.only.txt)

**Comment by aothms** [comment]
Something quite funky happened

```
>>> import ifcopenshell
>>> f = ifcopenshell.open('AC20-FZK-Haus.ifc')
>>> sp = f.by_type('IfcSpace')[0]
>>> sp
#20909=IfcSpace('347jFE2yX7IhCEIALmupEH',#12,'4',$,$,#20819,#20904,'Schlafzimmer',.ELEMENT.,$,$)
>>> sp.Representation.Representations
(#20878=IfcShapeRepresentation(#118,'Body','Brep',(#20868)), #20886=IfcShapeRepresentation(#375,'Box','BoundingBox',(#20885)), #20901=IfcShapeRepresentation(#20888,'FootPrint','GeometricCurveSet',(#20899)))
>>> g = ifcopenshell.open('AC20-FZK-Haus.-.spaces.only.txt')
>>> g[sp.GlobalId].Representation.Representations
(#1128=IfcShapeRepresentation(#278,'Body','MappedRepresentation',(#1127)), #1137=IfcShapeRepresentation(#280,'Box','MappedRepresentation',(#1136)), #1144=IfcShapeRepresentation(#279,'FootPrint','MappedRepresentation',(#1143)), #1151=IfcShapeRepresentation(#278,'Body','MappedRepresentation',(#1150)), #1158=IfcShapeRepresentation(#280,'Box','MappedRepresentation',(#1157)), #1165=IfcShapeRepresentation(#279,'FootPrint','MappedRepresentation',(#1164)), #1172=IfcShapeRepresentation(#278,'Body','MappedRepresentation',(#1171)), #1179=IfcShapeRepresentation(#280,'Box','MappedRepresentation',(#1178)), #1186=IfcShapeRepresentation(#279,'FootPrint','MappedRepresentation',(#1185)), #1193=IfcShapeRepresentation(#278,'Body','MappedRepresentation',(#1192)), #1200=IfcShapeRepresentation(#280,'Box','MappedRepresentation',(#1199)), #1207=IfcShapeRepresentation(#279,'FootPrint','MappedRepresentation',(#1206)), #1214=IfcShapeRepresentation(#278,'Body','MappedRepresentation',(#1213)), #1221=IfcShapeRepresentation(#280,'Box','MappedRepresentation',(#1220)), #1228=IfcShapeRepresentation(#279,'FootPrint','MappedRepresentation',(#1227)), #1235=IfcShapeRepresentation(#278,'Body','MappedRepresentation',(#1234)), #1242=IfcShapeRepresentation(#280,'Box','MappedRepresentation',(#1241)), #1249=IfcShapeRepresentation(#279,'FootPrint','MappedRepresentation',(#1248)), #1256=IfcShapeRepresentation(#278,'Body','MappedRepresentation',(#1255)), #1263=IfcShapeRepresentation(#280,'Box','MappedRepresentation',(#1262)), #1270=IfcShapeRepresentation(#279,'FootPrint','MappedRepresentation',(#1269)))
``` 

I'm not so familiar though with the recipe, maybe @Moult should have a look.

**Comment by vulevukusej** [comment]
@Moult bump - any update on this.  I'm having the same issue even if I try to extract slabs only.

Below is an output after using ".IFCSLAB" as an argument.  The outputted file has no geometry:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/83825269/ca8d0508-3a27-49eb-828e-2d0149ea5508)


IFC File being used: https://www.[ifcwiki.org/images/9/98/AC20-Institute-Var-2.ifc](https://www.ifcwiki.org/images/9/98/AC20-Institute-Var-2.ifc)

**Comment by Moult** [comment]
This one is sort of a bug. The extract elements recipe internally uses our "append asset" API function ... which is designed to load assets (types, occurrences, profiles, materials, whatever) from a library / other project. Usually this is a good thing since our append asset function is pretty comprehensive.

Except in this scenario the append asset function tries to follow the rules of native valid IFC. One of those rules is that if you have a type with a representation, all occurrences must map that representation. In this case, this IFC has some pretty crazy types with something like 21 representation maps which is probably wrong:

```
#21177= IFCSPACETYPE('2QnhNItpV3SNY2MUrDCSyc',#12,'Allgemeines',$,$,$,(#21185,#21187,#21189,#21546,#21548,#21550,#21903,#21905,#21907,#34037,#34039,#34041,#34450,#34452,#34454,#35022,#35024,#35026,#76476,#76478,#76480),'9AC6B5D2-DF37-C371-7882-59ED4D31CF26',$,.NOTDEFINED.,$);
```

In any case it was attempting to make sense of it and map those 21 representations which led to failure.

I've made it more forgiving, especially as ExtractElements generally deals with wild IFCs.
