### ISSUE TITLE
How to add extended new entities into the ifcopenshell?

### ISSUE THREAD

**Issue by MingmingSJTU** [IfcOpenShell/IfcOpenShell#2754]
I extended the IFC 4 schema with a new entity, "IfcRelationshipChange". How can I add this new entity into the ifcopenshell for parsing this entity?

**Comment by Moult** [comment]
See ifcopenshell.express module:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/tool/debug.py#L33-L34

**Comment by MingmingSJTU** [comment]
I try to parse the IFC4.exp file but I got an error:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/F041202/PycharmProjects/ifcViewer/test.py", line 11, in <module>
    schema = ifcopenshell.express.parse(".\ifcopenshell\express\IFC4.exp")
  File "C:\Users\F041202\PycharmProjects\ifcViewer\ifcopenshell\express\__init__.py", line 37, in parse
    return schema_class.SchemaClass(mapping, schema_class.LateBoundSchemaInstantiator).code
  File "C:\Users\F041202\PycharmProjects\ifcViewer\ifcopenshell\express\schema_class.py", line 478, in __init__
    x.entity_attributes(name, attribute_definitions, is_derived)
  File "C:\Users\F041202\PycharmProjects\ifcViewer\ifcopenshell\express\schema_class.py", line 86, in entity_attributes
    self.declarations[str(name)].set_attributes(attributes, is_derived)
KeyError: 'IfcActuator'

How can I figure this out?

**Comment by Moult** [comment]
What's your code? Can you provide your IFC4.exp file?

**Comment by MingmingSJTU** [comment]
I'm coding this:

> import ifcopenshell.express
> import ifcopenshell
> 
> schema = ifcopenshell.express.parse(".\ifcopenshell\express\IFC4.exp")
> ifcopenshell.register_schema(schema)
> 
> ifc_pipe = schema.declaration_by_name("IfcPipeSegment")
> print(ifc_pipe.all_attributes())

the related IFC4.exp file is in the attachment, which is generated by IfcDoc.
[IFC4.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/10703351/IFC4.zip)

**Comment by aothms** [comment]
I can reproduce the error, try again with the latest code. Somewhere in between of the express rule code generation project we apparently broke the latebound schema parsing simply because a mismatch in what `len()` on the schema represents.

You get an error now related to IfcRelDefinesByProperties.RelatedObjects. You seem to have an error there in your schema (or mismatch between Ifc2x3 Ifc4 IfcRelDefines).

**Comment by MingmingSJTU** [comment]
Thanks a lot. I tried the latest code and it works. In my schema I extended some new entities, I will check its alignment with rules.

**Comment by MingmingSJTU** [comment]
I add four entities as subtypes of IfcPredefinedPropertSet and I add the definition by IfcDoc. When I parsing the extended IFC.exp file, I got an error like this:

 File "C:\Users\F041202\PycharmProjects\ifcViewer\ifcopenshell\express\schema_class.py", line 395, in find_inverse_name_and_index
    raise Exception("No declared type for <%r>" % type)
Exception: No declared type for <ENTITY IfcContext
 ABSTRACT SUPERTYPE OF(ONEOF(IfcProject,IfcProjectLibrary));
    ObjectType : optional IfcLabel;
    LongName : optional IfcLabel;
    Phase : optional IfcLabel;
    RepresentationContexts : optional set[1:?] of IfcRepresentationContext;
    UnitsInContext : optional IfcUnitAssignment;
 INVERSE
    IsDefinedBy : SET OF [0:?] IfcRelDefinesByProperties FOR RelatedObjects;
    Declares : SET OF [0:?] IfcRelDeclares FOR RelatingContext;
END_ENTITY;

I do not know how to solve this problem. Where should I add the extended entities?

**Comment by aothms** [comment]
The error message was not helpful (plain wrong maybe). Update the code (you can just copy paste over this particular file) and you'll get a clearer message https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/express/schema_class.py#L377-L396

**Comment by MingmingSJTU** [comment]
Thanks, I got the error "No attribute named IfcRelDefinesByProperties.RelatedObjects". I want to know where I can add this missing entity in IfcOpenshell. I extended an entity like this:

![图片](https://user-images.githubusercontent.com/34128474/218455463-bb9548ce-9f95-410a-8e08-0bb4c87243dd.png)

I want to parse the extended ".exp" file.

Thanks a lot!

**Comment by aothms** [comment]
The inverse `IsDefinedBy` refers to a non existing attribute:

```
ENTITY IfcContext
 ABSTRACT SUPERTYPE OF (ONEOF
    (IfcProject
    ,IfcProjectLibrary));
	ObjectType : OPTIONAL IfcLabel;
	LongName : OPTIONAL IfcLabel;
	Phase : OPTIONAL IfcLabel;
	RepresentationContexts : OPTIONAL SET [1:?] OF IfcRepresentationContext;
	UnitsInContext : OPTIONAL IfcUnitAssignment;
 INVERSE
>	IsDefinedBy : SET [0:?] OF IfcRelDefinesByProperties FOR RelatedObjects;
	Declares : SET [0:?] OF IfcRelDeclares FOR RelatingContext;
END_ENTITY;
```

```
ENTITY IfcRelDefinesByProperties
 SUBTYPE OF (IfcRelDefines);
	RelatingPropertyDefinition : IfcPropertySetDefinitionSelect;
 WHERE
	NoRelatedTypeObject : SIZEOF(QUERY(Types <* SELF\IfcRelDefinesByProperties.RelatedObjects |  'IFC4.IFCTYPEOBJECT' IN TYPEOF(Types))) = 0;
END_ENTITY;
```

**Comment by aothms** [comment]
I don't think I understand the question, but I think you need to carefully review the definition of `IfcRelDefinesByProperties` in your schema as it doesn't have the `RelatedObjects` attribute anymore.
