### ISSUE TITLE
Build error after adding aud python dependency

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#2759]
Noticed [build error](https://github.com/IfcOpenShell/IfcOpenShell/actions/runs/4150706241/jobs/7180539933) after fa0f484922b8aed54ae5ad00ef072a2fc10ab7dd: `ModuleNotFoundError: No module named 'm2r'`.

I've looked into the error here - https://github.com/zdhoward/aud/issues/32 but I guess it will take some time to get sorted.
In the meantime we can either install `m2r` as well or use fork from my PR with fix - https://github.com/Andrej730/aud

@myoualid

**Comment by myoualid** [comment]
Thanks @Andrej730 !  @Moult 's call - I was refactoring only refactoring the costing module and found this library missing.

I manually placed the library and I laugh at every "🔉 Cha-ching"  now 😆

**Comment by Moult** [comment]
Heh I left it there as an easter egg never intended to ship with it. I'm OK either with it reverting to an optional dependency or using the fork. You guys choose.

**Comment by Andrej730** [comment]
:shipit: with fork 😂

**Comment by Moult** [comment]
Go for it!

**Comment by Andrej730** [comment]
Fixed it in cbc24c3
pip is not allowing to clone repository with `--depth 1` and basically it was trying to clone 20 MB repository when the actual package size is 20 KB so I sticked to repository .zip in that cases
