### ISSUE TITLE
Error when batch updating Pset values

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#2760]
I'm getting the following error when updating Pset values. The value appears to get set but the syntax doesn;t look quite right in the UI:

Python: Traceback (most recent call last):
  File "/Users/xxxx/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/group/ui.py", line 112, in draw
    if not groups_object:
NameError: name 'groups_object' is not defined

![image](https://user-images.githubusercontent.com/26485679/218274814-9f67a631-0923-469f-964f-d66dcb98ddf1.png)

![image](https://user-images.githubusercontent.com/26485679/218274833-8efb1308-7d8b-4a8b-a05b-39f4d20959fd.png)

**Comment by ChubbyQuark** [comment]
Manually adding Psets includes the squate brackets.

![image](https://user-images.githubusercontent.com/26485679/218274861-9753beac-3f7e-480c-9387-00fe41bd9598.png)

**Comment by Moult** [comment]
The group error i think is unrelated to the pset error, but I did find another pset error whilst trying to recreate your issue.

How do you recreate your issue? I tried using the bulk updater (see screenshot) as well as manually adding/editing the pset and it always seems to work fine for me and creates the `['NEW']` result.

Note: notice how in the screenshot I select enumerated value not single value.

![2023-02-12-151149_636x138_scrot](https://user-images.githubusercontent.com/88302/218292676-f804eb1b-15e6-4696-ad95-e178d8192c86.png)

**Comment by ChubbyQuark** [comment]
Yes , i used the bulk updater to create the Pset, manually editing the Pset
has consistently worked for me.

Ill try using the enum value. Also noticed that while the value is created
and respected in the UI visibility (using the .ifc selector) printing the
drawing doesn't excluded the elements assigned a status with the bulk
property updates.

**Comment by Moult** [comment]
Using the enum value is critical, as statuses are an enumeration, and would explain your issue.

I just tested the drawing Exclude filter and it seems to work for me.

![2023-02-13-110108_666x295_scrot](https://user-images.githubusercontent.com/88302/218345101-e662e918-29e4-4d6f-a425-41bae4a3674c.png)

**Comment by ChubbyQuark** [comment]
I think there may some other issues with the .ifc im using. Ill try the
steps here, as im also having issues deleting certain elements.

https://github.com/IfcOpenShell/IfcOpenShell/issues/2645

Will test again with a fresh installl and/or recreate the .ifc elements
that are causing issues.

**Comment by ChubbyQuark** [comment]
Updated with a fresh install and bulk setting Psets is working. I think there are other issues with the .ifc file I have as some of the walls seems to have lost associativity with the .ifc element.

**Comment by Moult** [comment]
Cheers so this is now fixed. Wall losing associativity is a critical bug but unfortunately nothing we can do until we get more details to track it down.
