### ISSUE TITLE
BlenderBim - Error when installing BlenderBim-230215

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2774]
When attempting to Install BlenderBim-230215 on Blender 3.3LTS or 3.4 latest

![image](https://user-images.githubusercontent.com/78321676/219001814-83ff012d-8308-4f77-915d-75bdebebcea7.png)

Still can't install on BlenderBim-230216

**Comment by nilei** [comment]
Same here +1 

I am trying to install on Mac OS Monterey with M1. I am using the blenderbim-230217-py310-macosm1.zip release. Also tried earlier releases with no success. It would be really great to have this fixed soon as I cannot even evaluate it at the moment.

Let me know if can be of any help!

-- Cheers, Nils

**Comment by aothms** [comment]
It's again due to this line. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/Makefile#L208

If you need to fix this urgently, you can simply replace the ifcopenshell module (look at the path of your traceback) with the appropriate build for your platform here https://github.com/IfcOpenBot/IfcOpenShell/commit/476ab506d0c6281f42dbc8bdb36c5cb1d98b525d

**Comment by nilei** [comment]
I have replaced the ifcopenshell directory with the new release (download ZIP from amazonaws, rename old directory, copy new directory from ZIP file), but that is now causing another error:

<img width="805" alt="image" src="https://user-images.githubusercontent.com/3751637/219944492-56356e0a-0ec5-46bb-a9d3-7068ed85d939.png">

Any help for this?

LG, Nils Leideck

**Comment by Moult** [comment]
@nilei sounds like something wasn't copied over quite correctly. Can you try the latest build here which likely has this bug fixed? https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-230219

**Comment by nilei** [comment]
Hi @Moult thanks, but its still the same issue. I removed the older installation in the addons panel and also checked that no files in the scripts/addons/blenderbim directory are left over. After installation of the ZIP file and click on the active checkbox, the following message appears again.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/3751637/219946784-ea9a7cd1-bb8b-44b2-98d3-59306d70c681.png">

LG, Nils Leideck

**Comment by nilei** [comment]
> Hi @Moult thanks, but its still the same issue. I removed the older installation in the addons panel and also checked that no files in the scripts/addons/blenderbim directory are left over. After installation of the ZIP file and click on the active checkbox, the following message appears again.

Never mind, I think I downloaded the wrong blenderbim Python version. After downloading the newest package for Python 3.10 the installation was okay. I will now test around 🙂 

Thanks so much for your support!!! ❤️ 

LG, Nils Leideck
