### ISSUE TITLE
Duplicating objects with Shift+D

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#2776]
@Moult , trying to write a buggy scenario here:
I'm unable to complete it correctly, it goes like this:

```
Scenario: Copy wall instance & join
    Given an empty IFC project
    And I load the demo construction library
    When I set "scene.BIMModelProperties.ifc_class" to "IfcWallType"
    And I add the construction type
    Then the object "IfcWallType/Wall" exists
    And the object "IfcWallType/Wall" is selected
    
    And I press "object.duplicate_move"
    And the object "IfcWallType/Wall.001" is selected
    And I move the object
    And I rotate the object
    And I select both walls
    And I Join them
```

**Comment by Moult** [comment]
What's the issue?

**Comment by myoualid** [comment]
The duplicated object disapears due to the instance not being found. Funky error I didn't want to paste here :D
New wall behaves fine with crl+c ctrl+v though

**Comment by Moult** [comment]
@myoualid can you help me recreate this issue? Did you try disabling other add-ons and trying on a vanilla setup? See https://github.com/IfcOpenShell/IfcOpenShell/issues/2645

**Comment by myoualid** [comment]
@Moult Indeed.. I tried a vanilla set up with Blender 3.5 and got this out of the way 🤣
