### ISSUE TITLE
ifcGeomIterator performance issue

### ISSUE THREAD

**Issue by cathty** [IfcOpenShell/IfcOpenShell#278]
For one ifc file with more than 10000 elements. it costs more than one hour to get geometry data with ifcGeomInterator. VS2015 profile indicates that most CPU time on function create_shape_model_for_next_entity(). 
Is there any way to improve ifcGeomIterator performance, e.g multithread ?

**Comment by aothms** [comment]
> more than one hour to get geometry

Unfortunately this is currently the reality for files with certain characteristics.

> most CPU time on function `create_shape_model_for_next_entity()`

That is indeed where the geometry generation happens.

> Is there any way to improve ifcGeomIterator performance, e.g multithread ?

Multi-threading is being worked on by a separate party, see:
https://github.com/sanderboer/IfcOpenShell/tree/multithreading
