### ISSUE TITLE
BlenderBIM - Error when validating IFC file

### ISSUE THREAD

**Issue by mdjska** [IfcOpenShell/IfcOpenShell#2780]
When trying to validate the ifc file (under IFC Debug panel), I get:

```
.../addons/blenderbim/libs/site/packages/ifcopenshell/express/rule_[executor.py](http://executor.py/)", line 43, in run
from _pytest import assertion
ModuleNotFoundError: No module named '_pytest'
```

Running blenderbim version 230209, Blender 3.4.1 on macos 12.6.

**Comment by mdjska** [comment]
I also get the same issue when using BIMTester

**Comment by Moult** [comment]
Yes, the new where rule validation needs pytest as a dependency, and I naively assumed devs who would use the validator would also have pytest installed. I guess we need to bundle it now.

**Comment by aothms** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/pull/2662#issuecomment-1372003193

**Comment by mdjska** [comment]
I see, I tried just placing pytest in Blender python's site-packages 
`/Applications/Blender 3.app/Contents/Resources/3.4/python/lib/python3.10/site-packages`
and in blenderbim's libraries:
`.../Library/Application Support/Blender/3.4/scripts/addons/blenderbim/libs/site`, but neither work. Do you have a tip for making it work with the bundled python?

**Comment by Moult** [comment]
You need both `pytest` and `_pytest`.

I investigated how complex the function was, and the assertion rewriter class itself is about 500 lines, then it calls various other pytest classes from other pytest modules and even does some importing voodoo, so it didn't seem very easy to isolate. I ended up just bundling pytest.
