### ISSUE TITLE
BlenderBIM - Only the most recently added IFC Classification is available

### ISSUE THREAD

**Issue by mdjska** [IfcOpenShell/IfcOpenShell#2781]
If adding multiple IFC Classifications in Scene Properties...

![issue_1](https://user-images.githubusercontent.com/16716147/219469309-46cb3d71-f290-4c73-a5dd-8abc9b1875fd.png)

...only the most recently added one is available in the Object Properties panel.

![issue_2](https://user-images.githubusercontent.com/16716147/219469321-7ca90403-f56c-4ce7-b208-b506da66a434.png)

**Comment by Moult** [comment]
Yeah the UX clearly is pretty misleading here, but it's not technically a bug. Classifications are added from external classification libraries, so only the "actively loaded external classification library" is shown. I'll improve it.
