### ISSUE TITLE
An BlenderBIM operation made saved file unable to reopen again (Missing RelatingMaterial)

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#2785]
# Description
I used blenderbim for a while on a file and an operation kind of corrupt the ifc as I was not able to reopen it with blenderbim.
# Manual fix used
Hopefully I found a manual fix :tada:  
I used [ifcopenshell.validate](https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples#Inside_a_script) on saved file and identified 2 uncommon issues:
```bash
[{'level': 'error',
  'message': 'Attribute not optional',
  'type': 'schema',
  'instance': #195155=IfcRelAssociatesMaterial('3aRSHhEIzmcx5SXXdBuVRn',#20,$,$,(#175873,#175937,#98333,#98429,#96803,#176867,#98301,#98776),$),
  'attribute': 'IfcRelAssociatesMaterial.RelatingMaterial'},
 {'level': 'error',
  'message': 'Attribute not optional',
  'type': 'schema',
  'instance': #195162=IfcRelAssociatesMaterial('0bEPMhZbdVxjb$ovPtUHPi',#20,$,$,(#98254,#98255,#122784),$),
  'attribute': 'IfcRelAssociatesMaterial.RelatingMaterial'},
 {'level': 'error',
  'message': 'With attribute:\n    <attribute RelatedObjects: <set [1:?] of <entity IfcObjectDefinition>>>\nValue:\n    ()\nNot valid\n',
  'type': 'schema',
  'instance': #193769=IfcRelAssignsToGroup('2qhlocL8ZssjCEsMVVz__2',#20,$,$,(),$,#193768),
  'attribute': 'RelatedObjects'},]
```
Analysing the file using IfcDebug I found that the associated objects had a type with a correct IfcRelAssociatesMaterial so I have deleted the faulty 2 IfcRelAssociatesMaterial.
I have also deleted faulty IfcRelAssignsToGroup but I do not think that it is related as import failed after `create native elements` step:
```bash
Starting import process :: 0.00
Loading file :: 0.00
Calculate unit scale :: 0.00
Calculate model offset :: 0.00
Set units :: 0.00
Create project :: 0.00
Process element filter :: 0.01
Process context filter :: 0.00
Create collections :: 0.02
Create materials :: 0.00
Create styles :: 0.02
Parsing native elements :: 0.16
Done creating geometry
Create native elements :: 0.00
```
and also I haven't touch anything related after last known working saved file.
# Leads
Can't reproduce the error yet… So I have only some leads. During time spent between last known working saved file and faulty one I have been changing some related type but don't remember of editing any material.

Analyzing an old file, I see that a related object has been unlinked:
![image](https://user-images.githubusercontent.com/9622862/219773537-af9d6e29-0f0a-4ebe-80a9-e08bb8b52194.png)
But this object still exist in faulty model with a different type:
![image](https://user-images.githubusercontent.com/9622862/219775577-c972745b-994c-40ac-980b-a0699e397152.png)
My guess is that during changing type process `RelatingMaterial` which is a `IfcMaterialLayerSetUsage` has been deleted. According to IFC documentation an `IfcMaterialSetUsage` should be assign to a single occurrence but a popular software produced the original file.
> The [IfcMaterialLayerSetUsage](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcMaterialLayerSetUsage.htm) is always assigned to an individual occurrence object (and only to relevant subtypes of [IfcElement](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcElement.htm)).

**Comment by Moult** [comment]
> My guess is that during changing type process RelatingMaterial which is a IfcMaterialLayerSetUsage has been deleted.  According to IFC documentation an IfcMaterialSetUsage should be assign to a single occurrence but a popular software produced the original file.

Not reading through in detail yet, I'm pretty sure this is a critical assumption we make ... however if the source file is invalid and from popular software I guess we should be a lot more defensive.
