### ISSUE TITLE
cmake problems with current master

### ISSUE THREAD

**Issue by thorade** [IfcOpenShell/IfcOpenShell#279]
I tried to compile the current master at f64246f7c5a71fc7942445957101ca43c2c4d952 on Windows 10, 64 bit, with Visual Studio 2015 or 2017, but both failed at the `run-cmake.bat` step. I have cmake version 3.9.2 installed. 

The error message when using VS 2105 is this:
[vs2015.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/1409996/vs2015.txt)
and here is the CMakeError.log
[CMakeError.log](https://github.com/IfcOpenShell/IfcOpenShell/files/1410000/CMakeError.log)
As I understand it, there is a problem related to pthread.h

When using VS 2017, I get the following error:
[vs2017.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/1410005/vs2017.txt)
Saying the bitness does not match!?

Any ideas or comments?

**Comment by Stinkfist0** [comment]
I wonder if updating Boost has left some residue causing problems? Did you run the build scripts for a clean checkout or did you have already the older Boost built before running the scripts again after the recent Boost update?

**Comment by thorade** [comment]
Downgrading Boost to 1.63.0 makes it work again, at least with `vs2015-x64`.
So, I think this issue is related to issue #249 and PR #273.

**Comment by thorade** [comment]
I was already writing, so I did not see your comment.
I used `git clean -fdx` to clean up before building.

**Comment by thorade** [comment]
Now that you ask, I am just 95% sure I deleted it. Tried so many different things, maybe I forgot it one time?

**Comment by Stinkfist0** [comment]
I don't have VS 2015 on my current PC but I have it installed at home. I can probably look into this tonight.

**Comment by thorade** [comment]
Thanks. I can also do another test with a fresh and clean checkout, later today.

**Comment by thorade** [comment]
I started compilation yesterday before going home in a fresh clone, using `vs2017-x64` and all steps were successfull.
So, sorry for the confusion, it looks like I did not clean up properly before building.
I will later today start another `vs2015-x64` job and see whether that succeeds, too.

**Comment by Stinkfist0** [comment]
Good to hear. Did not have time to fire up my home PC yesterday. It should be possible to have any VS version IfcOpenShell build trees side by side, so if there' are problems they are worth looking into it still.

**Comment by thorade** [comment]
OK, the CMake step still fails with VS2015, here is the output from the VS Developer Command Prompt:
[vs2015.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/1413755/vs2015.txt)

And the CMakeError.log and CMakeOutput.log:
[CMakeError.log](https://github.com/IfcOpenShell/IfcOpenShell/files/1413756/CMakeError.log)
[CMakeOutput.log](https://github.com/IfcOpenShell/IfcOpenShell/files/1413757/CMakeOutput.log)

**Comment by Stinkfist0** [comment]
How does the contents of IfcOpenShell\deps\boost\stage\vs2015-x64\lib look like?

**Comment by thorade** [comment]
Sorry, all in German
```
C:\Users\mthorade\Documents\git\IfcOpenShell\deps\boost\stage\vs2015-x64\lib>dir
 Datenträger in Laufwerk C: ist BOOTCAMP
 Volumeseriennummer: 46A3-F72B

 Verzeichnis von C:\Users\mthorade\Documents\git\IfcOpenShell\deps\boost\stage\vs2015-x64\lib

2017-10-25  09:34    <DIR>          .
2017-10-25  09:34    <DIR>          ..
2017-10-25  09:34           383.478 libboost_chrono-vc141-mt-s-1_65_1.lib
2017-10-25  09:34           763.572 libboost_date_time-vc141-mt-s-1_65_1.lib
2017-10-25  09:34         1.132.136 libboost_filesystem-vc141-mt-s-1_65_1.lib
2017-10-25  09:34           589.968 libboost_iostreams-vc141-mt-s-1_65_1.lib
2017-10-25  09:34        10.051.384 libboost_program_options-vc141-mt-s-1_65_1.lib
2017-10-25  09:34        16.331.612 libboost_regex-vc141-mt-s-1_65_1.lib
2017-10-25  09:34           100.894 libboost_system-vc141-mt-s-1_65_1.lib
2017-10-25  09:34         1.346.046 libboost_thread-vc141-mt-s-1_65_1.lib
               8 Datei(en),     30.699.090 Bytes
               2 Verzeichnis(se), 966.548.545.536 Bytes frei
```

**Comment by Stinkfist0** [comment]
OK, so `vc141` implies VS 2017 (VC 14.1), for VS 2015 these should be `vc140`. Apparently boost build phase picks up VC 14.1 for compiler instead of VC 14.0.

**Comment by thorade** [comment]
I ran all the commands from the VS 2015 Developer Command Prompt, so the variables should be set. But maybe they are not?

**Comment by Stinkfist0** [comment]
Here it is https://github.com/IfcOpenShell/IfcOpenShell/commit/e4a7d2a1496d32185ae7943bbdfde7370ada4fae#diff-cb6a00136f71142d75bb63be3c9e3c13L177

There might be something wonky with Boost and it picks up the most recent VC compiler of something, if the compiler is not specified explicitly. I think this line could be added back now, but it might become problematic yet again when some future VS version is released and we don't necessarily want to update Boost version each time simply because the compiler is "uknown" to Boost.

**Comment by thorade** [comment]
I would not have found that in a 100 years.

**Comment by Stinkfist0** [comment]
Maybe a decent solution could be (in semi-pseudocode):
```
:: BOOST_VC_VER can be empty for newer VS versions
set BOOST_VC_VER=
if %VS_VER% < 2017 (
    set BOOST_VC_VER=-%VC_VER%.0
)
call .\b2 toolset=msvc%BOOST_VC_VER% ...
```

**Comment by thorade** [comment]
Makes sense to me, but that doesn't mean too much...
Once you have commited something, I can test it on my computer,
unitl then I will just use VS 2017 (I prefer that anyway).

**Comment by Stinkfist0** [comment]
I tested the solution I proposed and it seems to work. I'll provide a PR soon.
