### ISSUE TITLE
blenderbim BCF module should support bcf.v3 

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2790]
This code refers to `topic.topic.reference_link`, `topic.topic.document_reference` and `topic.topic.related_topic`, but the api seems to offer `topic.topic.reference_links`, `topic.topic.document_references` and `topic.topic.related_topics`.

```
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/3.4/scripts/addons/blenderbim/bim/module/bcf/operator.py", line 121, in execute
    for reference_link in topic.topic.reference_link:
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Topic' object has no attribute 'reference_link'. Did you mean: 'reference_links'?
```

**Comment by Moult** [comment]
Yes, I merely updated the BCF UI to support bcf.v2 which is what it supported historically. So there is no support for bcf.v3 yet.

Some bcf.v3 changes are purely superficial like those renames whereas I believe cameras got a bit of an update and needs a pair of fresh eyes (in theory we proposed a lot of those updates so it should be compatible but...)
