### ISSUE TITLE
BlenderBim - When editing window with modifier (project units mm), window appears very far away - BBim 230220

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2792]
Hi All,

When using the window modifier on a window and editing it using the modifier properties while project units are mm, the window appears very far away

![image](https://user-images.githubusercontent.com/78321676/220052279-7714e113-6cf7-4b58-83e8-b60949e3ab7c.png)

After editing not a problem returns to normal

![image](https://user-images.githubusercontent.com/78321676/220052321-68949a58-eb39-43b1-8fa4-72c9d5538fda.png)

I tried with using metres as my unit and this issue does not appear there

![image](https://user-images.githubusercontent.com/78321676/220053119-5d32bcc1-71b3-4ffe-83a4-6dca6861b532.png)

**Comment by Andrej730** [comment]
Fixed.
