### ISSUE TITLE
BlenderBim - features request - 'print all' button and box alignment visual selector

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2794]
Hi all, just listing these as a quality of life requests, if they should rather be elsewhere let me know

Request 1: 'Print all' button

It's often the case after checking every drawing that I would print all of them for a set, when I have 60+ drawings in an IFC that takes quite a lot of time to select and print each drawing, a 'print all' button would help wrap up these kinds of drawing sets

Request 2: Box alignment visual indicator or selector

At present when editing text , it's working but quite a few steps to edit and then adjust the box alignment with written text, if it would be possible a visual indicator or selector of the configuration would be very helpful

These are visually elaborated on in this thread:
https://community.osarch.org/discussion/1085/

**Comment by Andrej730** [comment]
1) c9f52d2f8 currently it's working by shift-clicking print button so it won't be another button. Checked it with adding to quick favorites - it's also working fine with shift-clicking. Also ping @theoryshaw 👀 
2) 3c2ef518e

![image](https://user-images.githubusercontent.com/9417531/225535364-4557b995-d444-447a-b9a0-2fc827bebb10.png)
