### ISSUE TITLE
[ifcopenshell-python] file.remove() on rooted elem without globalid gives error message

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2796]
to reproduce use this code:

```python
import ifcopenshell

ifc = ifcopenshell.file(schema='IFC4')

wall = ifc.createIfcWall()

print("Wall is here")
print(wall)


print("Wall is deleted")
ifc.remove(wall)

print("Wall should be deleted")
print(wall)
print("Is it?")

```

and the error traceback was:

```shell
Wall is here
#1=IfcWall($,$,$,$,$,$,$,$,$)
Wall is deleted
Traceback (most recent call last):
  File "C:\Users\martin\remove_test\remove_test.py", line 19, in <module>
    ifc.remove(wall)
  File "C:\Users\martin\Documents\miniforge\envs\ifcopenshell\Lib\site-packages\ifcopenshell\file.py", line 428, in remove
    return self.wrapped_data.remove(inst.wrapped_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\martin\Documents\miniforge\envs\ifcopenshell\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4497, in remove
    return _ifcopenshell_wrapper.file_remove(self, entity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Invalid cast

```

i found the remove method in the doc, see https://blenderbim.org/docs-python/ifcopenshell-python/hello_world.html

**Comment by Moult** [comment]
I thought I had reported this before but either I didn't or I can't find it, but basically you need a GlobalId to use the remove function.

e.g.

```python
import ifcopenshell
ifc = ifcopenshell.file(schema='IFC4')
wall = ifc.createIfcWall(GlobalId=ifcopenshell.guid.new())
print("Wall is here")
print(wall)
print("Wall is deleted")
ifc.remove(wall)
print("Wall should be deleted")
```

If we can't find the bug I thought I reported let's keep this one open.

**Comment by Martin15135215** [comment]
so with GlobalId remove does function, however i saw another problem after that, if you use this code:

```python
import ifcopenshell
ifc = ifcopenshell.file(schema='IFC4')
wall = ifc.createIfcWall(GlobalId=ifcopenshell.guid.new())
print("Wall is here")
print(wall)
print("Wall is deleted")
ifc.remove(wall)
print("Wall should be deleted")
print(wall)
print("Is it?")
```

After the `print("Wall should be deleted")` line, python dies silently and did not execute the last print statement. Would it not be better if python raises instead a Exception?

**Comment by Moult** [comment]
It would be nice, but perhaps not technically possible, as the object has been deleted. In Blender I think what they do is they have a special "invalid object" object when things like this occur, but I have no idea how this actually works.

**Comment by aothms** [comment]
There is something we can do, but not a lot:

```
>>> import ifcopenshell
>>> ifc = ifcopenshell.file(schema='IFC4')
>>> wall = ifc.createIfcWall(GlobalId=ifcopenshell.guid.new())
>>> print("Wall is here")
Wall is here
>>> print(wall)
#1=IfcWall('1zOzAoBSzDOfP0noLI6LGt',$,$,$,$,$,$,$,$)
>>> ifc.remove(wall)
>>> del wall.wrapped_data.this
>>> wall
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tkrij\miniconda3\envs\ifopsh07\lib\site-packages\ifcopenshell\entity_instance.py", line 250, in __repr__
    return repr(self.wrapped_data)
  File "C:\Users\tkrij\miniconda3\envs\ifopsh07\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4843, in __repr__
    return _ifcopenshell_wrapper.entity_instance___repr__(self)
TypeError: in method 'entity_instance___repr__', argument 1 of type 'IfcUtil::IfcBaseClass const *'
```

Something like ^ this could be done e.g as part of the remove() call.

But there are many situations this doesn't catch, such as simply:

```
import ifcopenshell
ifc = ifcopenshell.file(schema='IFC4')
wall = ifc.createIfcWall(GlobalId=ifcopenshell.guid.new())
same_wall = ifc[1]
ifc.remove(wall)
del wall.wrapped_data.this
same_wall
print("oops")
```

The proper solution is to fix this in the C++ side, it's essentially the shared_ptr weak_ptr paradigm. Just on the C++ side it was never necessary (or maybe it is, maybe it's just that as soon as you do more advanced manipulation which is typically done in python).

For 0.8 I'd probably add back a compilation mode that can be used by the python wrapper to enable storing instances as shared_ptr.

**Comment by Moult** [comment]
@aothms what about the original bug where it requires a GlobalId to remove?

**Comment by aothms** [comment]
That should be fixable, good point

**Comment by Andrej730** [comment]
Came across this issue with removing elements without guids too.
