### ISSUE TITLE
Is there any ifcopenshell inRDF() function?

### ISSUE THREAD

**Issue by hsenol** [IfcOpenShell/IfcOpenShell#2806]
Hello dear community,

Is there any ifcopenshell inRDF() function? I want to parce my ifc file to RDF and I see that inRDF() function. But the code doesn't work because there is no inRDF() function in ifcopenshell 0.7.0 version. Could you suggest any solution for me?

**Comment by Moult** [comment]
https://github.com/pipauwel/IFCtoRDF might be what you're after. There is no functionality in IfcOpenShell that I am aware of to convert to RDF.

**Comment by aothms** [comment]
There are definitely some other 3rd party python ifcopenshell based rdf convertors such as https://github.com/NIRAS-MHRA/IFC2BOT

**Comment by Moult** [comment]
This doesn't seem to be a bug in any existing functionality nor a bite-sized feature request, so closing.
