### ISSUE TITLE
Testing IfcOpenShell C++ library on windows

### ISSUE THREAD

**Issue by dovlamingoX1** [IfcOpenShell/IfcOpenShell#2807]
Hey, 

I could finally compile IfcOpenShell on windows using Visual Studio. I have the following structure: 
    
![image](https://user-images.githubusercontent.com/126277919/221244241-4a8cc24d-9882-4276-b650-24719daf3aea.png)

Inside `include` are the headers and inside `lib` are the normal `*.lib` files.     

How can I now use these built libraries inside other projects? I tried already to include the libraries inside new project in Visual Studio, but many errors are occured due to missing deps (e.g. Boost). The `_deps` directory is also built.  Unfortunately, I am not using CMakeLists.txt files in the new project so I have to include the IfcOpenShell library using Visual Studio. 

Best,

Don

**Comment by aothms** [comment]
Easiest would be to take a look at the targets that create an executable such as the IfcConvert.vcproj. That will show you all include paths and libraries.

**Comment by dovlamingoX1** [comment]
solved
