### ISSUE TITLE
from __future__ import

### ISSUE THREAD

**Issue by thorade** [IfcOpenShell/IfcOpenShell#281]
Some (or all?) of the handwritten python files have the line
```python
from __future__ import print_function
```
at the top.

I suggest to also import absolute_import and division :
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
```

Should be quite harmless and help to avoid regressions.
http://python-future.org/quickstart.html

**Comment by aothms** [comment]
Indeed, especially the integer division differences could cause some headache. Will you send in a PR?

**Comment by thorade** [comment]
I have added the imports to all py files in the `src` directory
https://github.com/thorade/IfcOpenShell/tree/issue281_future_import
using the same three lines in all files

But now I do not know where integer division was used on purpose!?
Those places should be changed to use two slashes `//`
http://python-future.org/compatible_idioms.html#division

Also, PyCharm shows some warnings related to imports, but I am unsure whether these are new.

**Comment by thorade** [comment]
Lines that need to be checked regarding division (numbers might be off a bit):
occ_utils.py line 181
