### ISSUE TITLE
wall error

### ISSUE THREAD

**Issue by Uts-Micke** [IfcOpenShell/IfcOpenShell#2810]
I have a ifc file with a wall that is drawn in other programs, but in blender it only becomes a point
[K31-1512-20-B0000-V0-4030_C ( K ) (EDITED).zip](https://github.com/IfcOpenShell/IfcOpenShell/files/10834013/K31-1512-20-B0000-V0-4030_C.K.EDITED.zip)

**Comment by Moult** [comment]
The only thing I see suspicious is that the second operand (bright orange) is coincident with the bottom edge of the first orange (dark orange). However this is something @aothms needs to take a look at.

![2023-02-27-090635_248x577_scrot](https://user-images.githubusercontent.com/88302/221440379-0eab8a30-3fab-4ef1-93a5-805a2554af79.png)

**Comment by aothms** [comment]
Should work as intended now on the latest codebase.

![afbeelding](https://user-images.githubusercontent.com/1096535/222732957-9949078f-e1ab-45ca-98af-275dae0288ad.png)

The precision on this model is rather high / tolerance rather low:

    #15 = IFCGEOMETRICREPRESENTATIONCONTEXT($, 'Model', 3, 1.E-5, #16, #20);

This can typically cause boolean operation issues and we have a mechanism to keep retrying using a higher "fuziness", but somehow in this case OCCT didn't result in an exception, but rather a warning we have to manually intercept. This is done now and only acted on when the result is completely empty (to be on the safe side).

**Comment by Uts-Micke** [comment]
Installed blenderbim-230304-py310-win.zip and also updated blender to blender-3.4.1-windows-x64

the file only shows a point and no wall?

**Comment by Moult** [comment]
@Uts-Micke the BlenderBIM Add-on ships with a slightly older version of IfcOpenShell (since it takes time to prepare builds for 4 platforms). You'll need to wait until there is a new build available.

**Comment by Uts-Micke** [comment]
Okay. I am waiting
