### ISSUE TITLE
Blender Addon Updater

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#2815]
Just found that there is some tool that can help users update blenderbim from within the blender itself - [blender addon updater](https://github.com/CGCookie/blender-addon-updater). 
Could blenderbim benefit from it? Anyone had prior experience with that updater, any caveats?

I've set it up on a separate branch [blender-addon-updater](https://github.com/IfcOpenShell/IfcOpenShell/tree/blender-addon-updater) if you want to test it.
Note: if you'll install it you need to make sure `addon_updater.py`, `addon_updater_ops.py`, `__init__.py` from the addon root directory will be installed too.

Basically you can set the interval in blender and it will automatically check [releases](https://github.com/IfcOpenShell/IfcOpenShell/releases). 
It will check if there's a release with more recent version tag than current blender addon version and it will notify about the available update. And you can update the addon in one click.
During update process it creates backup of the current addon to make sure things won't go south.

![image](https://user-images.githubusercontent.com/9417531/221351941-ffbbac39-1a29-4336-b7d7-e8c7c3d0d18c.png)

You can also check updates manually and install it. 
![image](https://user-images.githubusercontent.com/9417531/221351844-47d3184b-849f-46f1-ae71-449e45d1b549.png)

There is also an option to add the update notification to some other part of the interface - so it will be easier to notice.
![image](https://user-images.githubusercontent.com/9417531/221352056-574f8fcb-d9d5-49a7-8c9b-83370b6163cc.png)

**Comment by Moult** [comment]
This is super cool! How does it handle the fact that we have multiple py versions and OS specific zips?

It's a little weird though because we have daily builds, so ... every day it'll say "hey there's an update"?

**Comment by Moult** [comment]
Agreed, feel free to implement and integrate :) This may wait for the next release though, I think there are other higher priorities right now.

**Comment by zhukoven** [comment]
Looking forward to seeing this feature!

**Comment by Moult** [comment]
https://twitter.com/BlenderDev/status/1748363626279239831/photo/1

https://devtalk.blender.org/t/2024-01-19-extensions-project/32996

https://code.blender.org/2022/10/blender-extensions-platform/

Looks like Blender is now considering having their own platform to solve this problem. I recommend we wait a little bit and see.

**Comment by Moult** [comment]
Now implemented natively in Blender.
