### ISSUE TITLE
Alignment and flipping should consider offset to reference curve

### ISSUE THREAD

**Issue by ThinkWithPbody** [IfcOpenShell/IfcOpenShell#2818]
With two IfcWallType selected, using the Shift X, Shift C, Shift V shortcut, all three operators produce the same result. 

https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/fOFaUkVQWoIQbmPcDrBXDDQL

**Comment by Moult** [comment]
Correct, because both walls are the same thickness, so naturally if you line them up centrally, and or at either face, the result is identical. If you had two walls of different thickness, you'd see the effect.

**Comment by Moult** [comment]
Reopening since the current implementation of alignment and flipping is not yet complete and has some issues with offset reference curves. I suspect you were interested in the origin changing, which is controlled by the reference curve offset, so let's leave this bug open until that is addressed.

**Comment by Moult** [comment]
All done. For parametric layer set walls, you can set the offset to the reference line (i.e. the origin is at the start of the reference line) via the IFC Object Material properties.

![2023-03-03-115729_882x250_scrot](https://user-images.githubusercontent.com/88302/222604860-9ca3c43b-d1ce-423d-9993-4c0a582cc8ff.png)
