### ISSUE TITLE
Periodic NURBS faces don't mesh, affects adjacent faces

### ISSUE THREAD

**Issue by tsvilans** [IfcOpenShell/IfcOpenShell#2819]
Hi,

I've narrowed down a problem I have been having with faces not showing up in BlenderBIM or the IfcOpenShell IFC online viewer.

It seems that, if there is an IfcCylindricalSurface in a model, it and the faces connected to it will not be imported/meshed/visualized. I use `ifcopenshell.geom.serialise(ifcfile.schema, geo)` to convert the OCC geometry to IFC. If I use `ifcopenshell.geom.tesselate(ifcfile.schema, geo, 1.0)`, it works, but obviously saves the geometry as a mesh instead of keeping the surfaces as required.

I'm attaching a simple .ifc file that illustrates the case. I saw a discussion in issue #2669 that was similar, but didn't look resolved.

![image](https://user-images.githubusercontent.com/6615080/222079238-e15d90fa-6c63-4e5e-918f-09053d49c643.png)
The geometry in Rhino. I tried exporting the geometry to STEP via OCC and importing into Rhino - all faces and surfaces are there.

![image](https://user-images.githubusercontent.com/6615080/222079179-23f21937-597e-45fa-8d0b-edbed0be6844.png)
The geometry in Blender.

![image](https://user-images.githubusercontent.com/6615080/222079487-2c3d2b74-b173-4451-8af6-00931846d0f3.png)
The geometry in `view.ifcopenshell.org`.

[test3d.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10858496/test3d.ifc.txt)
The .ifc for this minimal case.

Any tips would be welcome!

Thanks,

Tom

**Comment by aothms** [comment]
The circular edges in your model are bspline curves and it seems they are not valid.

There are error messages related this:

    [Error] [2023-03-04 14:17:37] {23sSBz5FbEGAS3u2_pogoF} BSpline curve: # Poles and degree mismatch

I didn't dive into in great detail, but seems validate.buildingsmart.org agrees:

```
On instance:
    #32=IfcBSplineCurveWithKnots(1,(#30,#31),.UNSPECIFIED.,.F.,.F.,(2,2),(0.,1000.),.PIECEWISE_BEZIER_KNOTS.)
Rule IfcBSplineCurveWithKnots_ConsistentBSpline:
    (IfcConstraintsParamBSpline(degree,upperindexonknots,upperindexoncontrolpoints,knotmultiplicities,knots))
Violated by:
    False
     +  where False = IfcConstraintsParamBSpline(1, 2, 1, (2, 2), (0.0, 1000.0))
```

See here for the function being violated

https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcConstraintsParamBSpline.htm

I think you can run true it on paper and see where the issue occurs.

Is this a file you generate yourself or does this come out of an authoring platform?

**Comment by tsvilans** [comment]
Thanks for looking at it!

I will go through it as you suggest.

The STEP is an export from Rhino, which I then load with OCC and then serialize and assign to an `IfcMember` with `ifcopenshell`. So I am not constructing the geometry myself. I also tried writing a new STEP from OCC (after loading) just to see if it round-trips, and it the result looks fine - all surfaces show up.

So I wonder if it is something in the `serialise` function which is going wrong... ? OCC seems to read and process it OK...

[beam_98.stp.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10888515/beam_98.stp.txt)


Here is the STEP file, if you'd like to check it.

**Comment by tsvilans** [comment]
> The circular edges in your model are bspline curves and it seems they are not valid.
> 
> There are error messages related this in the IfcConvert output (forwarding an error message from Open cascade).
> 
> ```
> [Error] [2023-03-04 14:17:37] {23sSBz5FbEGAS3u2_pogoF} BSpline curve: # Poles and degree mismatch
> ```
> 
> I didn't dive into in great detail, but seems validate.buildingsmart.org agrees:
> 
> ```
> On instance:
>     #32=IfcBSplineCurveWithKnots(1,(#30,#31),.UNSPECIFIED.,.F.,.F.,(2,2),(0.,1000.),.PIECEWISE_BEZIER_KNOTS.)
> Rule IfcBSplineCurveWithKnots_ConsistentBSpline:
>     (IfcConstraintsParamBSpline(degree,upperindexonknots,upperindexoncontrolpoints,knotmultiplicities,knots))
> Violated by:
>     False
>      +  where False = IfcConstraintsParamBSpline(1, 2, 1, (2, 2), (0.0, 1000.0))
> ```
> 
> (edit looking at the degree, these are not the circular edges)
> 
> See here for the function being violated
> 
> https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcConstraintsParamBSpline.htm
> 
> I think you can run through it on paper and see where the issue occurs.
> 
> Another error reported by validate is:
> 
> ```
> Rule IfcEdgeLoop_IsClosed:
>     ((edgelist[1 - 1].EdgeStart) == (edgelist[ne - 1].EdgeEnd))
> Violated by:
>     (#27=IfcVertexPoint(#26) == #54=IfcVertexPoint(#53))
>      +  where #27=IfcVertexPoint(#26) = #34=IfcOrientedEdge(*,*,#33,.T.).EdgeStart
>      +  and   #54=IfcVertexPoint(#53) = #61=IfcOrientedEdge(*,*,#60,.F.).EdgeEnd
> ```
> 
> On the rule
> 
> ```
> IfcEdgeLoop.IsClosed : (EdgeList[1].EdgeStart) :=: (EdgeList[Ne].EdgeEnd);
> ```
> 
> Where `:=:` is the entity instance equal operator:
> 
> > a :=: b evaluates to true if a evaluates to the same entity instance as b, i.e., the implementation
> > dependent identifiers are the same
> 
> I'd be tempted to say a violation of this rule is less of an issue in ifcopenshell because most of the edge trimming and loop building is based on geometry (vertex position location) in this case.
> 
> Is this a file you generate yourself or does this come out of an authoring platform?

Hi again,

So I tried running IfcConvert on it myself and it doesn't find any geometric entities... The scheme in the file is IFC4, so it looks like the latest built version of IfcConvert doesn't support it? I guess you are using a newer version?

I tried serialising the geometry to different OCC Brep versions, with no luck. 

It is only failing on cylindrical surfaces (or where they meet other faces). If I manually split the cylindrical surface so that it creates 2, then it works fine and outputs the correct geometry.

OCC doesn't give me any errors or problems when I load the STP files or when I save them back out. When I save them and open them in Rhino, the geometry is intact.

I'm a bit stumped.

**Comment by aothms** [comment]
Thank you for the continued investigation. I will have another thorough look at this.

**Comment by tsvilans** [comment]
Amazing!! Thanks very much for the fix, I'm very happy it could be tracked down :) Looking forward to the next release with the fix in it.

**Comment by aothms** [comment]
https://github.com/IfcOpenBot/IfcOpenShell/commit/ddef4820d05632d1e5cd1192df41258b43af8e51#commitcomment-118547865
