### ISSUE TITLE
BlenderBim - Error when printing drawings created in older BlenderBim versions

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2820]
Here is the error:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 177, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 460, in generate_linework
    self.merge_linework_and_add_metadata(root)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 535, in merge_linework_and_add_metadata
    merged_polygons = shapely.ops.unary_union(polygons)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\shapely\ops.py", line 135, in unary_union
    return shapely.union_all(geoms, axis=None)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\shapely\decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\shapely\set_operations.py", line 426, in union_all
    return lib.unary_union(collections, **kwargs)
shapely.errors.GEOSException: TopologyException: unable to assign free hole to a shell at 107.40000000000001 274.5

On Blenderbim-230301
Windows 10
Blender 3.4 & 3.3LTS

It works with BlenderBim-230228 (the previous daily release)

So I can only assume it was one of the commits since then that changed it.

**Comment by Moult** [comment]
Is it possible to share the IFC? dion@thinkmoult.com if private. I'm still learning more about what shapely can handle so this is good learning material.

**Comment by Plae-Blue-Dot** [comment]
It's applicable to 3 different Ifc files I am using, so I've sent one of them now, have a look and hopefully it is helpful. It is a project for a private client so I would appreciate it not being shared

**Comment by Moult** [comment]
@Plae-Blue-Dot OK, see if that commit helps.

**Comment by Moult** [comment]
BTW the merging occurs on material name, which mean if you want them to be merged the layer sets and such need to named the same for now. Unnamed materials (like you have quite a few) are never merged.

**Comment by Plae-Blue-Dot** [comment]
Ah ok noted, I'll keep that in mind, thanks for the lighting quick changes Dion! I'll check them out when the daily release updates

**Comment by Moult** [comment]
Given it's such a small change it might be easier to simply manually edit that file.

**Comment by Plae-Blue-Dot** [comment]
Got it, I made the changes and It seems to work for the ifc file I sent you but the other two ifc's still give errors, would it help to share those aswell?

**Comment by Moult** [comment]
Yes please, sorry for the inconvenience.

**Comment by Moult** [comment]
OK, I think that latest commit might help. Nearly the fill merging needs more tweaking though.

I'm blown away by what you've sent me. Awesome work! I truly hope by the end of the year everyone can see the BlenderBIM Add-on as able to produce a set of drawings for small projects, and so I am truly inspired by your work!

**Comment by Plae-Blue-Dot** [comment]
Hahah thanks, BlenderBim really is there I think, thanks for all your AWESOME work Dion! Without it this would be impossible

I tried to edit the commit myself but messed something up so I'll have a go with the next daily release, and report back, thanks again Dion

**Comment by Moult** [comment]
Seriously _thank you_ (and all other bugreporters too) you have no idea how much time this saves. If it weren't for your testing these bugs wouldn't have turned up until far too late. The work you've done is truly inspirational. At work I only use the BlenderBIM Add-on as post-model-creation tool, never for generating drawings and almost never for even modeling. So it is incredible to see work like yours (and other too) who are pushing the boundaries I wouldn't even imagine Blender could do until I see it.

Let's leave this bug report open for a short while just in case things break in the next release.

There's a mammoth amount of tasks still to be done... hatches in projection, different roof shape generation, sheet revisions, managing titleblocks, section marker tails, hundreds more assets to be bundled, centerline dimensioning ... the list is endless.

**Comment by Plae-Blue-Dot** [comment]
All of them are working now! Thanks @Moult !
