### ISSUE TITLE
BlenderBim - Default dimension text changes size and colour to large red text when printing

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2821]
When creating a new drawing and printing, the default dimension text is now much larger and red instead of black
This changed between BlenderBim-230225 & BlenderBim-230226

BlenderBim-230225 black small text
![image](https://user-images.githubusercontent.com/78321676/222102544-1867fdfc-850c-4ad1-a1f5-95a3a1f9ba86.png)

BlenderBim-230226 red large text
![image](https://user-images.githubusercontent.com/78321676/222102696-49f271c2-1a49-4c1f-9fc9-0adc4a965dda.png)

The red text isn't ideal and not sure if this is intentional or just a side effect of fixing something else

**Comment by Moult** [comment]
Sorry that was my bad I committed random test styles.

**Comment by Plae-Blue-Dot** [comment]
Thank you thank you !
