### ISSUE TITLE
BlenderBim - Wall to roof extrusion & clipping no longer work

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2828]
As the title says, Wall to roof extrusion & clipping no longer work as seen in this video at this timestamp:
https://youtu.be/kF2k_VW-yrQ?t=884

**Comment by Moult** [comment]
Indeed, this was a bit of a WIP from the previous feature where you could extend beams to walls. In the previous system you'd select the roof first then the walls second, which was weird, now it's the other way around which is more natural.

**Comment by Plae-Blue-Dot** [comment]
Ah excellent! I noticed it doesn't work with Ifc covering elements (like roofs) should I make that a separate issue?

**Comment by Plae-Blue-Dot** [comment]
Thanks Dion!
