### ISSUE TITLE
Viewing IFC's through pythonOCC

### ISSUE THREAD

**Issue by andersgb** [IfcOpenShell/IfcOpenShell#283]
I'm trying to do essentially what's described in this dated blogpost: http://ifcopenshell.org/pythonOCC/example1/

This is my attempt at visualizing IFC from latest IfcOpenShell master:
```python
from __future__ import print_function
import ifcopenshell
import ifcopenshell.geom

# Initialize a graphical display window
occ_display = ifcopenshell.geom.utils.initialize_display()
settings = ifcopenshell.geom.settings()
# Open the IFC file using IfcOpenShell
ifc_file = ifcopenshell.open("/home/anders/Downloads/IfcOpenHouse.ifc")

# Display the geometrical contents of the file using Python OpenCascade
products = ifc_file.by_type("IfcProduct")
for product in products:
    if product.is_a("IfcOpeningElement"): continue
    shape = ifcopenshell.geom.create_shape(settings, product)
    if shape:
        display_shape = ifcopenshell.geom.utils.display_shape(shape)
        if product.is_a("IfcPlate"):
            # Plates are the transparent parts of the window assembly
            # in the IfcOpenHouse model
            ifcopenshell.geom.utils.set_shape_transparency(display_shape, 0.8)

print("Finished loading..")
raw_input()
```

This particular code crashes on `Representation` entity not found I think:
```
  File "view.py", line 15, in <module>
    shape = ifcopenshell.geom.create_shape(settings, product)
  File "/usr/lib/python3/dist-packages/ifcopenshell/geom/main.py", line 125, in create_shape
    repr.wrapped_data if repr is not None else None
RuntimeError: Entity not found
```

If I modify the script to e.g. only show `IfcWall` objects (that should have `Representation`), I instead get the following crash:
```
Traceback (most recent call last):
  File "view.py", line 18, in <module>
    display_shape = ifcopenshell.geom.utils.display_shape(shape)
  File "/usr/lib/python3/dist-packages/ifcopenshell/geom/occ_utils.py", line 159, in display_shape
    ais = OCC.AIS.AIS_Shape(shape)
  File "/usr/lib/python3/dist-packages/OCC/AIS.py", line 13110, in __init__
    _AIS.AIS_Shape_swiginit(self, _AIS.new_AIS_Shape(*args))
TypeError: in method 'new_AIS_Shape', argument 1 of type 'TopoDS_Shape const &'
```

Crashes seem to be the same for python2 and python3 btw.

Any ideas?

Btw, if I want to use the built in python viewer app https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcopenshell-python/ifcopenshell/geom/app.py , how do I start it? I tried `python -m ifcopenshell.geom.app` but nothing happens really.

**Comment by thorade** [comment]
Regarding your second question: 
To start the viewer, you place the following two lines in a script and run it.
```python
import ifcopenshell.geom.app
ifcopenshell.geom.app.application().start()
```
https://github.com/IfcOpenShell/IfcOpenShell/commit/1d1fb6d27a5bb1f221aed4dc290c1dc99a324e0f#commitcomment-17161165

**Comment by aothms** [comment]
For some versions you might need to change. For the most recent versions I think both with and without `.geometry` should work though. And without you will get colors derived from the surface styles in the IFC model.

~~~
- shape = ifcopenshell.geom.create_shape(settings, product)
+ shape = ifcopenshell.geom.create_shape(settings, product).geometry
~~~

> RuntimeError: Entity not found

That seems to indicate there is sth wrong with the IFC model. That instances are missing. But there can be products without a representation that would (I think) result in a different error message. You can check for this along the lines of:

~~~
if product.Representation is None: continue
~~~
