### ISSUE TITLE
BlenderBim - text size spacing only works well with 'regular' size text

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2833]
It seems when using a new line in text with '\n' all the text spacing for the line is based on the 'regular' size

It causes overlap on bigger text sizes and huge spacing on small size

Example:
![image](https://user-images.githubusercontent.com/78321676/222885239-6d7dd4ed-3392-4a40-9f6b-1124da24edd9.png)

Example ifc file:
[Text size test file 3 - new line spacing.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10887823/Text.size.test.file.3.-.new.line.spacing.ifc.txt)

remove .txt to open

**Comment by Andrej730** [comment]
Fixed it in the commit above
![image](https://user-images.githubusercontent.com/9417531/225035886-7f67686a-aec6-4dff-89a7-7df378fd417d.png)

**Comment by Moult** [comment]
Whilst the offset is a bug, I'd say don't worry too much about the lack of centering on the door tag, that's purely arbitrary due to the font size and new line. There will be a new feature soon to allow multiple text tags where the placement and contents of the tags can be explicitly located.

**Comment by Andrej730** [comment]
Found some other bug along the way. It's seems box alignment in svg is a bit mixed up - left alignment appear on the right and top allignment appears on the bottom and vice verse 🙃

![image](https://user-images.githubusercontent.com/9417531/225606002-723af8f3-3c5b-40a2-ab61-957fe9bd79b0.png)

**Comment by Andrej730** [comment]
@Plae-Blue-Dot fixed it
