### ISSUE TITLE
Crash when using enable_editing_extrusion_axis

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2835]
Crash when using enable_editing_extrusion_axis
video: https://www.dropbox.com/s/o2chkq1py815sb7/2023-03-04_11-56-32_Command_Prompt_-_blender.exe_cmd.mp4?dl=0

[blender.crash.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10889310/blender.crash.txt)
blenderbim-230304

**Comment by Moult** [comment]
Something I need to keep on reminding myself:

```python
bm = bmesh.new()
bm.from_mesh(me)
bm.to_mesh(me)
bm.free() # Always call free
```

and

```python
bmesh.from_edit_mesh(me)
bmesh.update_edit_mesh(me)
# do not call free
```
