### ISSUE TITLE
Materials not Imported when using IFC File as Library

### ISSUE THREAD

**Issue by cm-wsp** [IfcOpenShell/IfcOpenShell#2837]
@Moult: 

An IFC File with Objects (which have many Materials applied to a Mesh) only imports one Material when using the file as a library.  

![image](https://user-images.githubusercontent.com/94601064/223073845-134a00a5-696c-40eb-8de9-95e88a4bc229.png)

Test file: 
[Export_ERP_v2.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10896570/Export_ERP_v2.ifc.txt)

**Comment by Moult** [comment]
@cm-wsp the file you attached doesn't have any types in it. Can you share the actual file?

**Comment by cm-wsp** [comment]
Hi Moult, sorry. Here the two Files the project where the imported objects come with no materials and the library file.
[Project with Library imported no materials.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11048252/Project.with.Library.imported.no.materials.ifc.txt)
[Library to Import.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11048253/Library.to.Import.ifc.txt)
