### ISSUE TITLE
Mapping of CardinalPoint in IfcMaterialProfileSetUsage - inverted *-left and *-right

### ISSUE THREAD

**Issue by Jesusbill** [IfcOpenShell/IfcOpenShell#2842]
Testing top/mid-depth/bottom with left/right, the latter seems to be implemented in the opposite direction.
For example, I would expect in the case below that the local placement is on the left.

![image](https://user-images.githubusercontent.com/6861582/223358838-84f487ba-781e-496a-a6e5-bf28904fe57b.png)

@Moult I can make the changes to fix this issue, unless I am missing something and it is good like this

**Comment by theoryshaw** [comment]
dumb question, is it just because the view of the 'cube' is from the opposite side? 

![2023-03-07_07-35-15_Blender_blender](https://user-images.githubusercontent.com/507113/223437653-dd6b194c-8d2d-4d83-81d6-0fe0d5df4a26.gif)

**Comment by Jesusbill** [comment]
It is precisely this @theoryshaw thanks. So the convention is set looking __towards__ the extrusion direction, so for columns one would normally see this inverted effect between left and right, in fact the example above was made with a column.
