### ISSUE TITLE
IfcOpenShell - Extract Centerpoint of All Elements in IFC

### ISSUE THREAD

**Issue by tvenas** [IfcOpenShell/IfcOpenShell#2843]
Hi, 

I'm trying to obtain the centerpoint of each element in the IFC file. I've been trying to use the "get_local_placement" definition to get started, but I see that not all elements in the IFC file contain this information, such as IfcSlab, IfcStair, IfcRailing which typicalliy returns a point [0.0, 0.0, 0.0]. Is there another way to achieve this? 

Here's my Python code so far:

![image](https://user-images.githubusercontent.com/127189022/223365784-bf5999e6-5855-4b16-ad1b-afc4f491c92a.png)

`filePath = r'C:\Users\Public\oneWall_V00.ifc'
model = ifcopenshell.open(filePath, format='ifc2x3')

xLocation = []
yLocation = []
zLocation = []

for element in model.by_type("IfcBuilding"):
    elements = ifcopenshell.util.element.get_decomposition(element)
    for element in elements:
        elementPlacement = ifcopenshell.util.placement.get_local_placement(element.ObjectPlacement)
        xLocation.append(elementPlacement[0][-1]) 
        yLocation.append(elementPlacement[1][-1])
        zLocation.append(elementPlacement[2][-1])

points = [[xLocation[i], yLocation[i], zLocation[i]] for i in range(len(xLocation))]
print(points)`

**Comment by Moult** [comment]
A clarification that the stairs and so on do include an object placement, except the exporting application probably incorrectly (lazily?) just places it at 0,0,0 which is not meaningful. What you're after is probably a centroid calculated through the geometry. This function doesn't exist yet, but is pretty simple to add for the "bounding box centroid" in the util.shape module.

**Comment by tvenas** [comment]
Thank you for a very quick response @Moult ! Can you show me how you would use the "bounding box centroid" in the util.shape module? Btw I couldn't find this function in that module.

**Comment by Moult** [comment]
@tvenas that function didn't exist yet, I've just added it :) There are a few ways to get it: either the local centroid of the geometry via `get_bbox_centroid`, or the global centroid via `get_element_bbox_centroid` or `get_shape_bbox_centroid` (which you'd typically use, unless you were doing something funny like picking a particular representation to create_shape on).

You can read more about how geometry creation works here https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html which will teach you how to get the `geometry` argument (from `shape.geometry`).

**Comment by tvenas** [comment]
@Moult thank you so much, you've been great help!

**Comment by tvenas** [comment]
Hi again @Moult , I've been trying the "get_element_bbox_centroid" to get the global centroid of the element geometries. I don't know if I've might have gotten something wrong in the code but it seems to be giving me the local centroids regardless of which method I use to obtain it (get_bbox_centroid, get_element_bbox_centroid gives the same result). Could you show me how you would obtain the global centroids? 

Here's my code:

![image](https://user-images.githubusercontent.com/127189022/223724539-80abe7a8-a521-4c3f-80c5-38c4f6db991a.png)

Output:
![image](https://user-images.githubusercontent.com/127189022/223724700-9b311a9e-4778-41bf-b512-0c20b320dfeb.png)


filePath = r'C:\Users\Public\oneWall_V00.ifc'
model = ifcopenshell.open(filePath, format='ifc2x3')

elements = model.by_type("IfcProduct")

tol = 1e-6
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, model, multiprocessing.cpu_count())
settings.set(settings.USE_WORLD_COORDS, True)

shapes = []
if iterator.initialize():
    while True:
        shapes.append(iterator.get())
        if not iterator.next():
            break

geometry = []
for shape in shapes:
    geometry.append(shape.geometry)

bboxCentroids = []
for g in geometry:
    bboxCentroids.append(ifcopenshell.util.shape.get_element_bbox_centroid(elements[0],g))

**Comment by Moult** [comment]
There seem to be a few issues. `settings.set(settings.USE_WORLD_COORDS, True)` means that the geometry is provided in global coordinates, which means that you should use `get_bbox_centroid` (without the element, since it's the element which has the global matrix) instead of `get_element_bbox_centroid`. Alternatively make USE_WORLD_COORDS false.

Secondly, you are calling `get_element_bbox_centroid` always with the same one element `elements[0]`, instead of the element that corresponds to the geometry you're after. This would give wrong results.

Also some questions of efficiency, just do this:

```
filePath = r'C:\Users\Public\oneWall_V00.ifc'
model = ifcopenshell.open(filePath, format='ifc2x3')

settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, model, multiprocessing.cpu_count())

shapes = []
if iterator.initialize():
    while True:
        print(model.by_id(shape.id))
        print(ifcopenshell.util.shape.get_shape_bbox_centroid(shape, shape.geometry))
        if not iterator.next():
            break
```

**Comment by tvenas** [comment]
Again, thank you so much @Moult ! I finally got it right by using the get_box_centroid with the settings.set(settings.USE_WORLD_COORDS, True).
