### ISSUE TITLE
remove_product rasies AttributeError: NoneType object has no attribute "is_a"

### ISSUE THREAD

**Issue by sanzoghenzo** [IfcOpenShell/IfcOpenShell#2844]
Hi, I made a simple script that removes the elements of an IFC file if they have a parameter with value like one of the specified (here we;re talking about disciplines, but it can be anything).

```
def remove_disciplines(
    pset_name: str,
    parameter_name: str,
    disciplines: Set[str],
    model: ifcfile,
    output_path: Path,
) -> None:
    for element in iterate_elements(model):
        parameter = get_parameter(element, pset_name, parameter_name)
        if not parameter:
            continue
        discipline = get_parameter_value(parameter)
        if discipline in disciplines:
            ifcopenshell.api.run("root.remove_product", model, product=element)
    model.write(str(output_path))
```

`iterate_elements`, `get_parameter` and `get_parameter_value` are common working functions in my toolkit.

When I run it, I get the following error:

```
   File "discipline_remover.py", line 47, in remove_disciplines
    ifcopenshell.api.run("root.remove_product", model, product=element)
  File "ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "ifcopenshell\api\root\remove_product.py", line 92, in execute
    ifcopenshell.api.run("material.unassign_material", self.file, product=self.settings["product"])
  File "ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "ifcopenshell\api\material\unassign_material.py", line 77, in execute
    if rel.RelatingMaterial.is_a() in ["IfcMaterialLayerSetUsage", "IfcMaterialProfileSetUsage"]:
AttributeError: 'NoneType' object has no attribute 'is_a'
```

- `product` is `#3087=IfcWallStandardCase('1AJZCN$of1thvTlc1cqcCF',#20,'Basic Wall:AR_MUR_MuroShelter_0.08:5000506',$,'Basic Wall:AR_MUR_MuroShelter_0.08',#3075,$,'5000506')`
- `rel` is`#43232=IfcRelAssociatesMaterial('1jXekOc70qycrFHCTngH1h',#20,$,$,(#3087),$)`
- `rel.RelatingMaterial` is `None`

In the original file I see that the`rel` has the relating material has the id of a IfcMaterialLayerSetUsage, that was probably removed by a previous iteration.

I don't know if it should simply be solved by checking `rel.RelatingMaterial is not None` or the removal at the first pass should not remove the relating material because it is used by another element...

**Comment by Moult** [comment]
Usages should only ever be used once. If it's used multiple times, it's an invalid file. Can you share your file by any chance (dion@thinkmoult.com) as well as a shortlist of elements to reproduce?

**Comment by sanzoghenzo** [comment]
> Usages should only ever be used once. If it's used multiple times, it's an invalid file. 

The original `rel` has two related objects, which by the [IFC standard](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcproductextension/lexical/ifcrelassociatesmaterial.htm) seems totally fine:

`#43232=IFCRELASSOCIATESMATERIAL('1jXekOc70qycrFHCTngH1h',#20,$,$,(#3049,#3087),#3054);`

I suppose this can be solved by removing the `rel.RelatingMaterial` only after making sure that the `rel.RelatedObjects` contains only one object.

>Can you share your file by any chance ([dion@thinkmoult.com](mailto:dion@thinkmoult.com)) as well as a shortlist of elements to reproduce?

I'll check with my colleagues to see if I can share something.

**Comment by Moult** [comment]
@sanzoghenzo cheers, I'll find some time to look at it, but by the way even though it is not invalid to link the usage multiple times as per the cardinality, it is still invalid though this is only documented in text. See here: https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcMaterialLayerSetUsage.htm

Maybe the model was created in Revit and has this bug? https://github.com/Autodesk/revit-ifc/issues/597

**Comment by sanzoghenzo** [comment]
Yes, this is exactly my case!

**Comment by Moult** [comment]
Are you sure you sent me the right file? I cannot find the GUID 2yA8PzE69FefNmicOYD5Ao that you mentioned in your email.

I also cannot replicate your issue, maybe you have an outdated IfcOpenShell? This fix came in 2 weeks ago that is related to your issue: https://github.com/IfcOpenShell/IfcOpenShell/commit/2429f507adf7e4801e67a13c9abf2fc33cb06ee6

**Comment by sanzoghenzo** [comment]
> Are you sure you sent me the right file? I cannot find the GUID 2yA8PzE69FefNmicOYD5Ao that you mentioned in your email.

I must have messed up with the IFC files and sent you the one with some products already removed :sweat_smile: 
 
> I also cannot replicate your issue, maybe you have an outdated IfcOpenShell? This fix came in 2 weeks ago that is related to your issue: [2429f50](https://github.com/IfcOpenShell/IfcOpenShell/commit/2429f507adf7e4801e67a13c9abf2fc33cb06ee6)

My bad. I'm indeed using the 0.7.0.230218 version, which doesn't have that fix.
#2785 didn't come up in my searches for my specific error.

> Just a side note in general be careful when running remove_product in a loop.

Yeah, I learned that after half an hour of trial and error!
VScode debugger exited with no errors, pycharm one gave me a STATUS_STACK_BUFFER_OVERRUN exit code.

I solved in the same way as you did, and made the collection part into a reusable `get_elements_by_parameter_value` function - win-win!.

**Comment by Moult** [comment]
Yeah I guess extend that warning to any remove operation in a loop. One strategy if you don't have an alternative is to loop through IDs `for step_id in [e.id() for e in elements]:` then `try: e = model.by_id(step_id) except: # already removed`.
