### ISSUE TITLE
Brickschema throws python error on creating the project inside BlenderBIM add-on

### ISSUE THREAD

**Issue by zhukoven** [IfcOpenShell/IfcOpenShell#2849]
Hi! I tried creating Brickschema project from the BlenderBIM add-on, and it throws Python error: 
![blenderbim_brick_pythonError](https://user-images.githubusercontent.com/27201628/224051874-4a7c440d-fc2b-4e74-889c-d25facb9f9fb.png)

**Test environment**:
Windows 11 Pro
Blender 3.4.1
BlenderBIM add-on versions tested: blenderbim-230304-py310-win, blenderbim-230308-py310-win

Tried installing Python 3.10 on my machine; also tested on MacOS, and it also throws the error.

P.S. as a side note, is there any instruction on how to set up Brickschema integration with BlenderBIM? Maybe I missed something during setup?

**Comment by Moult** [comment]
Does blenderbim/bim/schema/Brick.ttl exist?

**Comment by zhukoven** [comment]
@Moult no, it's missing. I found it in the old 3.2 folder (Blender\3.2\scripts\addons\blenderbim\bim\schema), but not in the newest release.

**Comment by zhukoven** [comment]
@Moult so what is the resolution to the issue? The blenderbim install package should be fixed?
