### ISSUE TITLE
IfcSverchok - No module named 'sverchok.utils.logging' 

### ISSUE THREAD

**Issue by andrsbtrg** [IfcOpenShell/IfcOpenShell#2853]
Hello, I tried installing IfcSverchok and I had this message when trying to activate the addin.

I have BlenderBIM and Sverchok installed.

![Screenshot from 2023-03-10 15-14-31](https://user-images.githubusercontent.com/63083862/224441727-b1f0d36d-eb9e-484d-8530-2c0a4eac4815.png)

I tried commenting out and this line:  https://github.com/IfcOpenShell/IfcOpenShell/blob/55036653dfdda0b58aae6f0cc608094de49a20c2/src/ifcsverchok/__init__.py#L32

`from sverchok.utils.logging import info, debug`

and the addin started.

I am running Fedora 37 and Blender 3.4

**Comment by Moult** [comment]
This is a great first issue to debug by figuring out where is the logging used, and why it used to exist, and was it removed or renamed, and what happened to it. Would you like to try @andrsbtrg ? You may need to investigate in the upstream Sverchok codebase which moves pretty fast and check out their history.

**Comment by andrsbtrg** [comment]
@Moult for sure! I will take a try on it.
