### ISSUE TITLE
BlenderBim - Ifc smart tags no longer working BlenderBim-230312

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2856]
Example to reference name in text:
![image](https://user-images.githubusercontent.com/78321676/224548340-dd318a8b-afee-426d-b992-d5917263c2fa.png)

Comes up empty:
![image](https://user-images.githubusercontent.com/78321676/224548382-ebfc29dd-c2e2-41da-85bf-8a2e00578849.png)

**Comment by Moult** [comment]
Yes sorry this is a little WIP as the text editing system gets updated to support multiple texts (e.g. custom multitext tags), multiline texts. I'll quickly do a hotfix for you though.
