### ISSUE TITLE
autopep8

### ISSUE THREAD

**Issue by thorade** [IfcOpenShell/IfcOpenShell#286]
The Python code could be made pep8 compliant using autopep8:
```
python -m pip install -U autopep8
cd src\ifcopenshell-python
autopep8 --in-place --recursive  --max-line-length=200 ifcopenshell
autopep8 --in-place --recursive  --max-line-length=200 --aggressive --aggressive --aggressive ifcopenshell
```
The changes are mostly whitespace, depending on aggressiveness level.

**Comment by aothms** [comment]
Are you planning to submit a PR for this? (probably after all recent PRs are merged)

> --max-line-length=200

Doesn't PEP-8 have a much lower limit on line length? (Which is a bit too pessimistic in my opinion).

> Limit all lines to a maximum of 79 characters.

https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by thorade** [comment]
Exactly, I was waiting until there are no PRs involving py files.
Unless you are not interested in such whitespace/style changes.

Breaking long lines should better be done manually, so using any high number should be ok here.
79 is very short, other tools use 100, github seems to be displaying something like 120 in diffs etc.

**Comment by aothms** [comment]
> Breaking long lines should better be done manually

Ah, I guess you are right.

Great!
