### ISSUE TITLE
Windows and doors are placed relative to the building storey instead of the opening element

### ISSUE THREAD

**Issue by Fabian14027** [IfcOpenShell/IfcOpenShell#2864]
Hi, I’m very new to this community so please feel free to correct me when I’m wrong.
BlenderBIM Version 0.0.230304

I noticed that when I add windows and doors to a wall, they are placed relative to the building storey instead of the opening element.

Here an example:
I created a wall, window and door. 
When I look at the ObjectPlacement-Attribute of the window it says `#417=IfcLocalPlacement(#63,#416)`. 
When I look at the IfcLocalPlacement’s Attribute PlacementRelTo it says `#63=IfcLocalPlacement(#57,#62)`. 
And this is the IfcLocalPlacement of the building storey `#40=IfcBuildingStorey('3ruX_Jmyj4YfsqgocKrvsA',$,'My Storey',$,$,**#63**,$,$,$,$)`.

That means the windows position is relative to the building storeys position. In my opinion in this case it would make much more sense to place the window relative to its opening element it fills. So when the wall moves the window moves too.

When I look at the [buildingSMART documentation](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcLocalPlacement.htm) I see my point kind of approved.
Well, I’m aware it says:
For IfcElement the convention applies that it shall be placed relative:
- to the local placement of its container, either IfcSite, IfcFacility, or IfcFacilityPart
     - it should be the same container element that is referenced by the IfcRelContainedInSpatialStructure containment relationship,

That’s how it is implemented at the moment.

**But it also says:**
- to the local placement of the IfcElement to which it is tied by an element composition relationship
     - for features that are located relative to the main component (such as openings), as expressed by IfcRelVoidsElement and IfcRelProjectsElement;
     - for elements that fill an opening (**such as doors or windows**), as expressed by IfcRelFillsElement;

Furthermore I studied some literature where the way of placing a window relative to the opening element is described. Even when you look at the [sample file](https://blenderbim.org/docs/users/exploring_an_ifc_model.html) you see that’s the way they did it.

Are there any reasons why it is implemented like this at the moment?
The only case I can think of where it makes sense is when a window is free standing and not placed into a wall.

Cheers
Fabian
[WallWindowDoor.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10957971/WallWindowDoor.txt)

**Comment by Moult** [comment]
You're right, this is probably an oversight. I'll look into this.
