### ISSUE TITLE
Python API little bug in material.edit_layer

### ISSUE THREAD

**Issue by cvillagrasa** [IfcOpenShell/IfcOpenShell#2868]
I was taking a look at the API and noticed the following:

According to the code example [in the material.edit layer documentation](https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/material/edit_layer/index.html), the typical line:
`ifcopenshell.api.run("material.edit_layer", model, layer=layer, attributes={"LayerThickness": 13})`

doesn't include a `material=layer.Material` argument, which makes `layer.Material = None` after that call [(link)](https://github.com/IfcOpenShell/IfcOpenShell/blob/cce0867f6365288aa2a0c1963ceee610f96b14d3/src/ifcopenshell-python/ifcopenshell/api/material/edit_layer.py#L66). On the other hand, it wouldn't seem necessary to call `material.edit_layer` if a thickness argument could be passed to `material.add_layer`. That's also in line with the behaviour of `material.add_profile` accepting the profile, without the need to call `material.edit_profile` at first creation.

Am I missing something or it would be a good thing to add more arguments to `material.add_layer`? Perhaps even IsVentilated and so on.

**Comment by Moult** [comment]
Indeed it would better to only edit the material if the material is specified.

As for more arguments to add_layer, the general principle I followed was that "adding" would only include the bare minimum required for valid IFC data (and in some exceptions some really useful defaults like a Name). The rest would be relegated to an edit call. There's no real strong logic behind this, other than making it easier to start coding APIs as this is a learning journey, and having some arbitrary rules on where logic should live.

PRs welcome :)
