### ISSUE TITLE
IfcConvert: Windows binaries and IFC4 unable to find keyword in schema

### ISSUE THREAD

**Issue by pobr1** [IfcOpenShell/IfcOpenShell#2871]
Hi.
Is anybody else having the following problem.
When I try to convert an IFC4 to OBJ using the Windows binaries I get the error:
_[Error] Unable to find find keyword in schema_

When I convert an IFC 2x3 using the Windows binaries it works perfectly!
When I convert an IFC4 using the Linux binaries then it works perfectly!
When I convert an IFC 2x34 using the Linux binaries then it works perfectly!

**Comment by pobr1** [comment]
Edit: I have observed the same behaviour using both version 0.4.0 and 0.5.0 preview 2.

**Comment by Moult** [comment]
0.4 and 0.5 are pretty ancient. Can you make sure you have the latest builds installed from here? https://blenderbim.org/docs-python/ifcconvert/installation.html

Then, if you still have an issue, can you share your IFC?

**Comment by pobr1** [comment]
Thank you very much Dion! I'm not sure how I overlooked that...
The problem is resolved using the 0.7.0 binaries.
I have purged all the old binaries from my pipeline.
Cheers.
