### ISSUE TITLE
BlenderBim - print-all with shift click 'print' prints drawings in last cameras size

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2882]
When printing with 'shift click' all drawings will print the camera size of the last activated drawing
Ground floor plan svg:
![image](https://user-images.githubusercontent.com/78321676/226272942-69814591-0f8b-4a5c-b329-23beccf77b05.png)

Section SVG:
![image](https://user-images.githubusercontent.com/78321676/226272983-ed7a5881-79e3-4cce-b367-541a3b85539f.png)

The ground floor camera uses the section camera size to cut the ground floor and it cuts off half of the drawing

the second issue is that there is no way to turn of 'print all' after shift clicking it will always print all the activated drawings

BlenderBim 230320
Blender 3.3LTS
Windows 10

**Comment by Moult** [comment]
@Andrej730 BTW for the latter issue remember that blender operators always remember their last prop setting. For this reason all UI operators should always specify all props to prevent ambiguity.
