### ISSUE TITLE
BlenderBim - 230320 - text from older Ifc does not print correctly

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2883]
When loading drawings from an ifc file created in a previous version of BlenderBim the text and annotaiotn leader text elements do not print correctly, some do not print at all and some only print the default word 'text'

model:
![image](https://user-images.githubusercontent.com/78321676/226273552-996422b4-1050-4ead-98d6-4ff4e2ff06cb.png)

SVG:
![image](https://user-images.githubusercontent.com/78321676/226273641-c9d746bf-3a3a-4946-a61e-633a98233cfc.png)

BlenderBim 230320
Blender 3.3LTS
Windows 10

**Comment by Moult** [comment]
There were a few text related changes in the past few hours, can you confirm that you have the very latest version?

**Comment by Moult** [comment]
Also is there a test model?

**Comment by Plae-Blue-Dot** [comment]
Hey @Moult just updated to download the latest BlenderBim-230320 and it seems fixed on some files but older files are still not displaying text at all

**Comment by Moult** [comment]
@Plae-Blue-Dot hmm, is there a test model I can use?

**Comment by Plae-Blue-Dot** [comment]
I've it to you via email, it's a private project again so please don't share, thanks @Moult ! 

When printing the ground floor plan the text comes out as blank

**Comment by Moult** [comment]
This is now fixed.

@Andrej730 BTW don't reference `text_obj.BIMTextProperties.value` since there is no guarantee that it is populated (i.e. they have to enable viewport annotations first). That should only be used for the viewport annotations :)
