### ISSUE TITLE
IfcConvert : Failed to convert IfcExtrudedAreaSolid

### ISSUE THREAD

**Issue by ketourneau** [IfcOpenShell/IfcOpenShell#2884]
We try to convert a customer Ifc file to dae but we got error.

[file.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11015291/file.ifc.zip)

Command line we use :
`
IfcConvert -v file.ifc file.dae
`

Output :
`
[Error] [2023-03-20 08:26:11] {226vK0CW100A00d02f0DS0} Failed to convert:
#33=IfcExtrudedAreaSolid(#30,#35,#34,162.179292971921598)
[Notice] [2023-03-20 08:26:11] No geometrical elements found or none succesfully converted
`

If we open it with IFC.js demo (https://ifcjs.github.io/web-ifc-viewer/example/index) we can see geometry and data :
<img width="1089" alt="Capture d’écran 2023-03-20 à 08 43 34" src="https://user-images.githubusercontent.com/39763266/226276595-4bddf839-f082-4062-b31a-44dfda0f1709.png">

**Comment by Moult** [comment]
The file is invalid. You might want to report a bug to IFC.JS if they somehow manage to visualise it in case this misleads users.

The extrusion is of a CHS which has a thickness greater than the radius:

```
#30= IFCCIRCLEHOLLOWPROFILEDEF(.AREA.,$,#31,0.0055,0.011);
```

You can check this by running ifcopenshell.validate which will demonstrate the issue:

```
2023-03-20 19:11:44,698    ERROR rule_executor.py 224 On instance:
    #30=IfcCircleHollowProfileDef(.AREA.,$,#31,0.0055,0.011)
Rule IfcCircleHollowProfileDef.WR1:
    (wallthickness < self.Radius)
Violated by:
    (0.011 < 0.0055)
     +  where 0.0055 = #30=IfcCircleHollowProfileDef(.AREA.,$,#31,0.0055,0.011).Radius
```

**Comment by ketourneau** [comment]
I try with this docker command to validate ifc but we didn't got any output error

`
docker run --platform linux/x86_64 -v /Users/XXX/file.ifc:/file.ifc -it aecgeeks/ifcopenshell:latest python3 -m ifcopenshell.validate file.ifc
`

Output : 
`
Validating file.ifc
`

Is there anything we missed ?

**Comment by aothms** [comment]
To get feedback on the where rule constraints in the schema (what @Moult showed) you need to run with --rules. It's fairly new.

    python3 -m ifcopenshell.validate --rules file.ifc

To elaborate on why and how this fails. The wall thickness is indeed to be subtracted from the outer radius. So in this case you'd arrive at a negative circle radius (native mesh based kernels might construct something out of that [$-r \times cos ( \theta )$]

But open cascade helps us throw an exception [0]. The express rules are not validated in ifcconvert.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcCircleHollowProfileDef.cpp#L59

**Comment by ketourneau** [comment]
@aothms Thank you for your reply.

When I try to use validate command with docker I got error :
```
docker run --platform linux/x86_64 -v /Users/XXX/file.ifc:/file.ifc -it aecgeeks/ifcopenshell:latest python3 -m ifcopenshell.validate --rules file.ifc

Validating file.ifc

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/ifcopenshell/validate.py", line 431, in <module>
    validate(fn, logger, "--rules" in flags)
  File "/usr/lib/python3/dist-packages/ifcopenshell/validate.py", line 413, in validate
    ifcopenshell.express.rule_executor.run(f, logger)
  File "/usr/lib/python3/dist-packages/ifcopenshell/express/rule_executor.py", line 66, in run
    from _pytest import assertion
ModuleNotFoundError: No module named '_pytest'
```

**Comment by aothms** [comment]
Hm the docker image is built from a .deb, so I've add the debian pytest package as a depedency. Maybe it's better through pip. Please test again later today when the image comes up.

**Comment by aothms** [comment]
The docker image is updated https://hub.docker.com/r/aecgeeks/ifcopenshell/tags

**Comment by ketourneau** [comment]
Ok thx a lot !
