### ISSUE TITLE
'apply roof path' doesn't seem to work

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2889]
'apply roof path' doesn't seem to work

https://www.dropbox.com/s/xetj21zrko4iorp/2023-03-21_18-57-27_Blender_blender.mp4?dl=0

**Comment by theoryshaw** [comment]
`bpy.ops.bim.finish_editing_roof_path()`

works though. 
https://www.dropbox.com/s/4ab1txn43pjr7eu/2023-03-21_19-02-50_Blender_blender.mp4?dl=0

**Comment by Andrej730** [comment]
Fixed.
