### ISSUE TITLE
Creating Annotations in 3D Model View

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#2890]

**Comment by theoryshaw** [comment]
Did you mean something like this? https://www.dropbox.com/s/fs2hvo58kk0mjoc/2023-03-22_08-10-17_Blender_blender.mp4?dl=0

Or like 3D annotations that stay put in model space?

**Comment by theoryshaw** [comment]
added context to default project: https://github.com/IfcOpenShell/IfcOpenShell/pull/2895/commits/e5dca46cf2c17b9e74d8b571048e4459b7d5aa39

**Comment by myoualid** [comment]
Exactly ! I didn't know it worked, as it wasn't very intuitive - thanks for the fix !

**Comment by theoryshaw** [comment]
You bet!
