### ISSUE TITLE
python crash when looping with ifcopenshell.api.run("aggregate.assign_object"...)

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2891]
The following code crashes unless I remove the nested api.run call for "aggregate.assign_object": [code example](https://gist.github.com/vulevukusej/3a79a5a052ef5cf8fad1be3d72dae691)

@aothms I remember you telling me once that this could be prone to errors, so I'm wondering if you can recommend another approach?

Also - If I set up a debugger then it shows me that python always crashes on the 2nd iteration of the loop.

**Comment by Moult** [comment]
This is probably not a bug, at a glance I think your `placement` variable cannot be relied upon to be reused as changing the aggregation will modify the placement naturally, hence the crash. Move the instantiation of placement and origin into its own function and use that instead:

```
def get_placement(self):
    origin = file.createIfcAxis2Placement3D(
        file.createIfcCartesianPoint((0.0, 0.0, 0.0)),
        file.createIfcDirection((0.0, 0.0, 1.0)),
        file.createIfcDirection((1.0, 0.0, 0.0)),
    )
    placement = file.createIfcLocalPlacement(None, origin)

# ... then ...

"ObjectPlacement": get_placement(),
```

**Comment by vulevukusej** [comment]
@Moult that did the trick! 👍
