### ISSUE TITLE
Geometry Intersection with IfcSpace

### ISSUE THREAD

**Issue by tvenas** [IfcOpenShell/IfcOpenShell#2893]
Hi, 

I'm trying to tag all elements in an ifc.-file with a "Zone" parameter. I have two separate ifc.-files, one which contains all the elements I want to tag (let's call it Model A), and a "Zone-model" which only consists of IfcSpaces (let's call it Model B). 

I want to check if the objects from Model A intersects with the spaces from Model B and then write the space name they intersect with to a new parameter called "Zone" in Model A. 

I've tried getting the bbox centroids of every element in Model A, and then using the shapely module to check if the point is inside the footprint (using polygons). Unfortunately, as far as i understand, shapely only works in 2D. 

I've tried looking for an "Intersect" function in the IfcOpenShell module, but I don't know if it actually exist or not. 

Any ideas to how I can start solving this problem?

**Comment by Moult** [comment]
If you want to use shapely as your zones are all prismatic (e.g. Revit has a limitation where everything must be prismatic), you can compare the Z coordinate first, then treat XY as a 2D problem.

Otherwise you can use `ifcopenshell.geom.tree`, and use the `select` function to select objects existing at that point. It's effectively an "intersects at a point" function.

**Comment by Moult** [comment]
Bump @tvenas

**Comment by tvenas** [comment]
Hi @Moult , and again thanks for the reply! I couldn't quite get the select function to work, I couldn't understand the arguments the function needed. Do you know what goes inside here? 

![image](https://user-images.githubusercontent.com/127189022/227851999-53124ba8-80da-4993-a1a1-3d682aa5818c.png)

**Comment by Moult** [comment]
@tvenas `ifcopenshell.geom.tree.select((x,y,z), extend=r)` where `r` is a radius around that point.

**Comment by tvenas** [comment]
Hi @Moult, thank you for the quick reply :) One thing I wonder is how does the function know which ifc file to look for the object at that point? 
I tried specifying a point in the ifc file for which I know there's a wall, following your instructions above:

object = ifcopenshell.geom.tree.select((100.873, 37.450, 32.5), 0.5)

But I got an error message saying:

Traceback (most recent call last):
  File "c:\Users\tvenas\folder\Desktop\TESTING\VisualStudioCode_tvenas\VScode\Testing7.py", line 20, in <module>
    object = ifcopenshell.geom.tree.select((100.873, 37.450, 32.5), 0.5)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tvenas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ifcopenshell\geom\main.py", line 163, in select
    return [entity_instance(e) for e in ifcopenshell_wrapper.tree.select(*args)]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tvenas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 2349, in select
    return _ifcopenshell_wrapper.tree_select(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Wrong number or type of arguments for overloaded function 'tree_select'.
  Possible C/C++ prototypes are:
    IfcGeom::tree::select(IfcUtil::IfcBaseClass *,bool,double) const
    IfcGeom::tree::select(IfcUtil::IfcBaseClass *,bool) const
    IfcGeom::tree::select(IfcUtil::IfcBaseClass *) const
    IfcGeom::tree::select(gp_Pnt const &,double) const
    IfcGeom::tree::select(gp_Pnt const &) const
    IfcGeom::tree::select(std::string const &,bool,double) const
    IfcGeom::tree::select(std::string const &,bool) const
    IfcGeom::tree::select(std::string const &) const
    IfcGeom::tree::select(IfcGeom::BRepElement const *,bool,double) const
    IfcGeom::tree::select(IfcGeom::BRepElement const *,bool) const
    IfcGeom::tree::select(IfcGeom::BRepElement const *) const

**Comment by Moult** [comment]
@tvenas try reading through this thread, it shows some example usages: https://community.osarch.org/discussion/comment/8857/#Comment_8857

**Comment by tvenas** [comment]
Thanks @Moult ! I'll read through this and have another go at it.

**Comment by Moult** [comment]
@tvenas sorry I was swamped with life and other things but now revisiting this. I've written a bunch of docs about how to use geometry trees, does this help? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/docs/ifcopenshell-python/geometry_tree.rst

**Comment by tvenas** [comment]
Thank you @Moult for your reply, I've been away from work for quite some time, but I'll give this a go now 👍 Thanks!
