### ISSUE TITLE
BGL to GPU module migration

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#2897]
Since 3.5 Blender consider `bgl` module as deprecated and in 3.7 they plan to remove it completely. So we need to move from `bgl` to `gpu`.

Currently each time `bgl` is called it's spamming something like:
```
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:2656 
BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 3.7 'bgl' will be removed.
```

Is there any caveats to this migration? 
Do we need to keep `bgl` part to maybe support some older Blender versions (seen some other blender addons do that) or `gpu` should got it covered?

Wanted to create this issue so it will be easier to refer to in commits.

UPDATE: turn out they completely removed bgl render for M1 with Metal, so it's not just warning and need to fix it soon.

Some references for the migration process:
- https://projects.blender.org/blender/blender/src/branch/main/source/blender/python/generic/bgl.c
- https://docs.blender.org/api/main/bgl.html
- https://docs.blender.org/api/main/gpu.html

**Comment by Moult** [comment]
Officially we only support the last three major Blender versions: https://blenderbim.org/docs/devs/system_support.html

So please feel free to delete bgl :)

**Comment by Andrej730** [comment]
It's completed but I'll keep the issue opened for a bit - maybe some issues will come up.

**Comment by ChubbyQuark** [comment]
Hey, just testing this on an m1 mac and the viewport annotations fail to display. The same ifc displays the annotations on a windows machine I've also tested on.

**Comment by Andrej730** [comment]
@ChubbyQuark 
1) Any errors in the console?
2) you're using Metal backend or OpenGL?
3) If you create a slab and start profile editing - can you see the custom viewport rendering?

**Comment by ChubbyQuark** [comment]
1. No console erros
2. Using Metal backend
3. What is the custom viewport rendering, the green overlay when the camera cuts elements? This is the slab in edit mode:
<img width="781" alt="image" src="https://user-images.githubusercontent.com/26485679/233562862-eda92561-de7f-41b8-a32a-916320eaa449.png">

**Comment by Andrej730** [comment]
@ChubbyQuark can you please try to create new blend file and run this script? 
(Scripting Tab -> "New" to create new text file -> Copy and paste the script -> Run Script (Triangle button at the top))
Can you see a couple yellow lines at center of the scene?

```python
import bpy
import gpu
from gpu_extras.batch import batch_for_shader


polyline_vert_glsl = """
uniform mat4 ModelViewProjectionMatrix;
uniform vec4 color;

in vec3 pos;

out gpu_shader_3D_polyline_iface{
  smooth vec4 final_color;
  smooth float clip;
  noperspective float smoothline;
}
interp;

void main()
{
  gl_Position = ModelViewProjectionMatrix * vec4(pos, 1.0);

#ifndef UNIFORM
  interp.final_color = color;
#endif

#ifdef CLIP
  interp.clip = dot(ModelMatrix * vec4(pos, 1.0), ClipPlane);
#endif
}
"""

polyline_geom_glsl = """
// solves uniform color not found
#define UNIFORM 1
uniform vec4 color;
uniform float lineWidth;
uniform bool lineSmooth;
uniform vec2 viewportSize;

const int SMOOTH_WIDTH = 1;

/* Interfaces. */
out gpu_shader_3D_polyline_iface{
  smooth vec4 final_color;
  smooth float clip;
  noperspective float smoothline;
}
interp_out;

layout(lines) in;
layout(triangle_strip, max_vertices = 4) out;

/* Clips point to near clip plane before perspective divide. */
vec4 clip_line_point_homogeneous_space(vec4 p, vec4 q)
{
  if (p.z < -p.w) {
    /* Just solves p + (q - p) * A; for A when p.z / p.w = -1.0. */
    float denom = q.z - p.z + q.w - p.w;
    if (denom == 0.0) {
      /* No solution. */
      return p;
    }
    float A = (-p.z - p.w) / denom;
    p = p + (q - p) * A;
  }
  return p;
}

void do_vertex(const int i, vec4 pos, vec2 ofs)
{
#if defined(UNIFORM)
  interp_out.final_color = color;

#elif defined(FLAT)
  /* WATCH: Assuming last provoking vertex. */
  interp_out.final_color = interp_in[1].final_color;

#elif defined(SMOOTH)
  interp_out.final_color = interp_in[i].final_color;
#endif

#ifdef CLIP
  interp_out.clip = interp_in[i].clip;
#endif

  interp_out.smoothline = (lineWidth + SMOOTH_WIDTH * float(lineSmooth)) * 0.5;
  gl_Position = pos;
  gl_Position.xy += ofs * pos.w;
  EmitVertex();

  interp_out.smoothline = -(lineWidth + SMOOTH_WIDTH * float(lineSmooth)) * 0.5;
  gl_Position = pos;
  gl_Position.xy -= ofs * pos.w;
  EmitVertex();
}

void main(void)
{
  vec4 p0 = clip_line_point_homogeneous_space(gl_in[0].gl_Position, gl_in[1].gl_Position);
  vec4 p1 = clip_line_point_homogeneous_space(gl_in[1].gl_Position, gl_in[0].gl_Position);
  vec2 e = normalize(((p1.xy / p1.w) - (p0.xy / p0.w)) * viewportSize.xy);

#if 0 /* Hard turn when line direction changes quadrant. */
  e = abs(e);
  vec2 ofs = (e.x > e.y) ? vec2(0.0, 1.0 / e.x) : vec2(1.0 / e.y, 0.0);
#else /* Use perpendicular direction. */
  vec2 ofs = vec2(-e.y, e.x);
#endif
  ofs /= viewportSize.xy;
  ofs *= lineWidth + SMOOTH_WIDTH * float(lineSmooth);

  do_vertex(0, p0, ofs);
  do_vertex(1, p1, ofs);

  EndPrimitive();
}
"""

polyline_frag_glsl = """

in gpu_shader_3D_polyline_iface{
  smooth vec4 final_color;
  smooth float clip;
  noperspective float smoothline;
}
interp;

uniform float lineWidth;
uniform bool lineSmooth;

const int SMOOTH_WIDTH = 1;

out vec4 fragColor;

void main()
{
#ifdef CLIP
  if (interp.clip < 0.0) {
    discard;
  }
#endif
  fragColor = interp.final_color;
  if (lineSmooth) {
    fragColor.a *= clamp((lineWidth + SMOOTH_WIDTH) * 0.5 - abs(interp.smoothline), 0.0, 1.0);
  }
  fragColor = blender_srgb_to_framebuffer_space(fragColor);
}
"""

from mathutils import Vector
coords = [(-5.55732, -0.297869, 0), (0.320209, 1.505, 0), (-2, -1, 3), (0, 1, 1)]
line_color = (1,1,0,1)
offset_vector = Vector([0,0,1])
coords = [Vector(c) - offset_vector for c in coords]

def draw():
    shader = gpu.types.GPUShader(
        polyline_vert_glsl, 
        polyline_frag_glsl, 
        geocode=polyline_geom_glsl
    )
    batch = batch_for_shader(shader, 'LINES', {"pos": coords})
    shader.bind()

    region = bpy.context.area
    projection_matrix = gpu.matrix.get_projection_matrix()
    model_view_matrix = gpu.matrix.get_model_view_matrix()
    mvp_matrix = projection_matrix @ model_view_matrix

    shader.uniform_float("viewportSize", [region.width, region.height])
    shader.uniform_float("color", line_color)
    shader.uniform_float("lineWidth", 2.0)
    shader.uniform_int("lineSmooth", 1)

    gpu.state.blend_set("ALPHA")
    batch.draw(shader)


bpy.types.SpaceView3D.draw_handler_add(draw, (), 'WINDOW', 'POST_VIEW')
```

**Comment by ChubbyQuark** [comment]
No, nothing is drawn. Scripts runs without errors.

bpy.ops.text.run_script()

**Comment by Moult** [comment]
@ChubbyQuark just a dumb question are you using the latest Blender 3.5? Because I have seen bugs in the GPU module in older versions.

**Comment by Moult** [comment]
Prior to the GPU migration there was also this commit which fixed an issue similar to this on Mac. Maybe its relevant: https://github.com/IfcOpenShell/IfcOpenShell/commit/f9cfd1730323f2db6f550fe5aa0b32bffc74e4ea

**Comment by ChubbyQuark** [comment]
Yes, I'm running 3.5. Just updated to the latest bb version from today,
still no joy

**Comment by Andrej730** [comment]
Created an issue on blender issue tracker - https://projects.blender.org/blender/blender/issues/107332

**Comment by Andrej730** [comment]
We've found some solution that seems reliable. 
I've posted a question on blender stackexchange to make sure we don't miss anything before implementing it.
https://blender.stackexchange.com/questions/291674/migrating-geometry-shaders-to-metal

**Comment by Andrej730** [comment]
@Gorgious56 can you please take a look?

**Comment by Andrej730** [comment]
Finished migrating shaders, tested that it works on M1 Metal now too.

On my machine:
![Screenshot 2023-05-10 180057](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/180a4bc5-f3f4-4d63-9ba9-4a69841bc875)

On Mac M1 Metal (some issues with text scale - not sure if it's related to Mac or it's an issue of displaying text on different monitors):
![Screenshot 2023-05-10 180050](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/613ec0e3-26eb-42ed-8535-dfb8ae6a67ad)

**Comment by ChubbyQuark** [comment]
Great, also working on my m1 machine. If you send me your test file I can
check the scaling.

**Comment by Andrej730** [comment]
@ChubbyQuark attached acrhive with project to test the scaling
[geometry_shaders_project.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11448425/geometry_shaders_project.zip)

**Comment by ChubbyQuark** [comment]
That's odd, only some of the annotations are displayed. I have an existing
file that showed various types of annotation.

[image: image.png]
[image: image.png]

**Comment by ChubbyQuark** [comment]
Loading the .blend and then the .ifc works. Guess some of the annotations
are stored with the .blend?

[image: image.png]

**Comment by Andrej730** [comment]
@ChubbyQuark can't see attached images :\

**Comment by ChubbyQuark** [comment]
Attached again. Third image is after loading the .blend and re-loading hte .ifc

<img width="573" alt="image" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/26485679/97cf0cad-6f8d-4ad9-a4c1-20da7bb14045">


<img width="572" alt="image" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/26485679/662cee6a-e314-401b-b9c4-50566170ef47">


<img width="565" alt="image" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/26485679/2d5bc93f-0042-4c97-9f17-5231ad71beb0">

**Comment by Andrej730** [comment]
Investigated a bit - currently text size is inconsistent between different dpi. 
The one I was using on my machine was 72 dpi and on Mac it was 144 dpi - so on Mac text appered much bigger.
Added to kanban to tackle this issue later - https://github.com/orgs/IfcOpenShell/projects/5/views/1?pane=issue&itemId=27927476

**Comment by ChubbyQuark** [comment]
ok, makes sense regarding the scaling issue.

Seems odd that only some annotations were displayed from the .ifc?

**Comment by Andrej730** [comment]
> Seems odd that only some annotations were displayed from the .ifc?

Tested it now - it's seems fine rn, even if you import just .ifc without .blend.
The issue was probably related to #3090 I've fixed today
