### ISSUE TITLE
text doesn't show when 'viewport annotations' is enabled. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2900]
Using [this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/master/Examples/BlenderBIM%20-%20annotation%20file/Annotation_File.ifc) file, text doesn't show when 'viewport annotations' is enabled. 

![image](https://user-images.githubusercontent.com/507113/227257107-e7e81555-161e-4d81-9be4-f6f70aeb3444.png)

**Comment by Andrej730** [comment]
Fixed but I guess there is still space to improve in synchronising viewport preview with final svg 😬

![image](https://user-images.githubusercontent.com/9417531/227437377-21434b0d-5f39-4346-9eec-fc0467eba813.png)


![image](https://user-images.githubusercontent.com/9417531/227437406-b5f542d8-6ac2-4402-a355-6622ec1fdced.png)
