### ISSUE TITLE
Back geometrical projection from SVG to IFC

### ISSUE THREAD

**Issue by MigVega** [IfcOpenShell/IfcOpenShell#2902]
With IfcConvert I can generate a 2D svg file from a 3D model giving a scale and some boundaries.
Then I use the image to do some computations.
Now I want to do the opposite, project from the SVG coordinate system back to the coordinate system of the 3D model (IFC)

Is there a way to do this?
I did not find any related issue or documentation about it.
The SVG file has a "data-matrix3" is there information that helps to do this inverse projection?
I think here is how the SVG is generated: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/SvgSerializer.cpp
But I have not found functions to do the opposite.

Is there at least a way to go from a point in the coordinate system of the 3D IFC model to the 2D svg? For example to know where the origin (0,0,0) of my model in the svg is?

**Comment by Moult** [comment]
To go from the 3D world to the 2D SVG you should multiply the inverse matrix of the drawing by the 3D point and discard the Z ordinate.

To go from 2D to 3D you need to multiple the matrix of the drawing by the 2D point with a "0" Z ordinate.

**Comment by aothms** [comment]
The function to go from 2d back to 3d is here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/draw.py#L256-L271

To be honest the detail on all of this completely escapes me.

**Comment by MigVega** [comment]
Yes, it seems that the "data-matrix" in the SVG file gives the transformation I was looking for.
Thank you both!
