### ISSUE TITLE
Exclude IfcAnnotation from Drawings

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2903]
This works...
![image](https://user-images.githubusercontent.com/507113/227411806-5cf76291-463c-43a8-8dcf-e79cbfee98f5.png)

But this doesn't
![image](https://user-images.githubusercontent.com/507113/227411842-17af099b-2581-407c-a390-485624eb76a1.png)

I 'might' be able to fix it (but probably not) if you point me to the code that processes this Exclude variable. 

ping @ChubbyQuark, as i think he was looking for ways to filter annotation, too.

**Comment by Moult** [comment]
Indeed, use the selector to filter these `elements`: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/drawing/operator.py#L611

**Comment by theoryshaw** [comment]
Thanks!.. can you point me to the code that Excludes IfcElements from the drawing?.. going to study that to inform myself on how it can be done for IfcAnnotation.

**Comment by Moult** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/tool/drawing.py#L1118

That function should be made reusable. Don't copy paste the code :)

**Comment by theoryshaw** [comment]
will try it keep it DRY up in here. ;)

**Comment by Moult** [comment]
How did this go @theoryshaw ?

**Comment by theoryshaw** [comment]
Not good.  :\
need to level up, before tackling. :)
