### ISSUE TITLE
BlenderBIM - Option to choose between global and local coordinates in IfcArray

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#2905]
I would like to suggest adding an option to choose between global and local coordinates in IfcArray.

This is how the IfcArray works now, using the global coordinates:
![image](https://user-images.githubusercontent.com/57102715/227674733-cbe3526d-8831-4255-a573-043bc5d528b4.png)

This is how it would look like with an option to use local coordinates:
![image](https://user-images.githubusercontent.com/57102715/227674770-1d5be436-e55f-4cfe-b476-99a8ec5dd8db.png)

**Comment by brunoperdigao** [comment]
Hi @Andrej730,

Thanks for taking the time to implement this feature.

I was testing the local space option and there is something weird about its behavior. It works if the object origin is at 0, 0, 0.
![image](https://user-images.githubusercontent.com/57102715/228241655-cb098f8c-2223-45a6-a888-b7b75225e33f.png)


But if I move the object, it seems that it adds up the new location to the child elements:
![image](https://user-images.githubusercontent.com/57102715/228242198-9fc1e94b-4a09-4172-a2ba-a8b00cfa112b.png)

**Comment by Andrej730** [comment]
@brunoperdigao indeed world translation was kind of applied twice in local mode, fixed that
