### ISSUE TITLE
BlenderBim - Feature request - save perspective camera with the Ifc

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2906]
It seems when the Ifc is saved you can only save an orthographic camera, even when setting a 'model' camera to perspective it resets to orthographic on reload. 

Not sure if this conflicts with the schema in anyway but being able to save perspective camera views with the Ifc is useful in many ways especially when modelling between an IFC bim workflow and iterating with an adjacent blender presentation file with destructive modelling workflows.

This is a nice to have and is not essential to any workflow at present but it would be very cool

**Comment by Moult** [comment]
@aothms what do you think? In this case it may not make sense to create a box representation like we do for drawings. Perhaps instead for now we can just put camera parameters in a custom pset?
