### ISSUE TITLE
Handling annotation types

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2908]
Just as there are element types, there are also usecases where annotation types makes sense.

For example, the ability to have a "door tag" managed at a single annotation type (where the type manages the text literals, psets, etc). A lot of text annotations would be type based.

There could also be types of dimensions, for example regular dims vs grid dims which use different styles.

Or types of filled regions.

IFC does not have annotation types. One mitigation is to provide features to propagate settings (e.g. text literals, psets) to all other annotations with a property or object type that matches, or manually specified via object selection ... but it's clearly a bit of a hack.

@aothms would you have any suggestions on the best way to approach this in the schema?

**Comment by aothms** [comment]
Hm, since 4.3 annotations are also used a bit more for annotating various rail/infra semantics https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcAnnotationTypeEnum.htm I can imagine IfcAnnotationType beginning to make even more sense.

It seems IfcTypeProduct is not abstract, so I guess you could use that?

**Comment by Moult** [comment]
> IFC4-CHANGE The entity [IfcTypeProduct](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcTypeProduct.htm) shall not be instantiated from IFC4 onwards. It will be changed into an ABSTRACT supertype in future releases of IFC.

:(

**Comment by Moult** [comment]
It's technically legal to have an IfcAnnotation <- RelDefinesByType -> IfcBuildingElementProxyType (since the WR constraint is on the occurrence) but that would pollute the list of element types which you'd typically query to get a list of products in your building.

Another option is RelDefinesByObject https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcRelDefinesByObject.htm but again it feels like misuse.

**Comment by aothms** [comment]
> :(

Well, It's not abstract now and by the time it will get to be, we'll make sure we have a proper annotation type https://github.com/buildingSMART/IFC4.3.x-development/issues/598 Still think it's the best way forward

**Comment by Moult** [comment]
@aothms one complication with using IfcTypeProduct is that we rely on automatic type to occurrence class mappings for the ability to use the type manager and insert occurrences and so on. E.g. if we insert an occurrence of a pumptype, we know it must be a pump. We'd have to build some special rules to know that if we add a new occurrence of this IfcTypeProduct it comes out as an IfcAnnotation or somesuch.

**Comment by aothms** [comment]
Can still be automated I guess. IfcTypeProduct is the associated type of the first supertype. So you just walk up the inheritance tree and stop when an associated type exists, most typically directly without any walking up.

**Comment by Moult** [comment]
I meant the other way around, going from type to occurrence (e.g. if I want to add a new occurrence of a type in my library).

But yes, it is solvable with some UI guidance. I'll see how far I get.
