### ISSUE TITLE
BlenderBIM, objects move randomly on save

### ISSUE THREAD

**Issue by KaareZ** [IfcOpenShell/IfcOpenShell#2911]
Each time I save my IfcProject in the Blender GUI, some objects will randomly shift their position. This is not visible until I close the Blender project, create a new Blender project and once again load the IfcProject.

![image](https://user-images.githubusercontent.com/12858029/228169146-073bd7d4-d83f-4e6c-be81-63496c7f2786.png)

The highlighted object in the picture above has moved 600mm on the x-axis. It has a width of 600mm. Sometimes  they will shift 1200mm or shift 110mm or 220mm in the z-axis. Other objects, such as the gray beams, may also randomly shift their position on saving the IfcProject. These have other increments of shifting.

The objects are defined as IfcElementTypes with IfcArbitraryClosedProfileDef and IfcArbitraryProfileDefWithVoids.

By manually inspecting the STEP-file, I find that the IfcCartesianPoint related to the IfcLocalPlacement has a wrong value. E.g. the x-coordinate might be 4200 when it was supposed to be 3600 (the example above).

I'm attending a university course, and several other students has the same issue.

It seems like the issue is specific to BlenderBIM. I have made a Python script  (with IfcOpenShell-Python), that attempts to correct these shifts after saving in BlenderBIM. This works as expected.

## Builds
Blender 3.4.1

I have used the following builds of BlenderBIM, Python 3.10-Win:
- blenderbim-230328
- blenderbim-230307
- blenderbim-230306
- blenderbim-230314
- blenderbim-230326
- blenderbim-230321
- blenderbim-230301

**Comment by Moult** [comment]
Is it possible to do a test file / set of instructions to replicate, or do a screenshare to replicate this issue?

**Comment by KaareZ** [comment]
Annoyingly, it's now a bit hard to reproduce reliably. It seems to happen a bit randomly, and not the same each time. It's hard to determine which steps actually influence the outcome, but roughly something like:


## Steps
[Ifc-files-before_and_after.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11101337/Ifc-files-before_and_after.zip)

1. Load Ifc project in the scene pane (use the file named before).
2. Move the highlighted element below `G + x + 600` and `G + z + (-1) 110`, to position it correctly. Do this before activating the BIM-tool
3. Activate BIM-tool and move the rest of the hollowcore elements that needs to be moved.

![Screenshot 2023-03-29 144224](https://user-images.githubusercontent.com/12858029/228541741-2b3ab400-d6eb-48ad-975e-e2080d1f11f1.png)

4. Move the highlighted beam to correct position (-220 z)

![Screenshot 2023-03-29 144328](https://user-images.githubusercontent.com/12858029/228543313-afd8ddd6-7bd5-4e91-9c7a-b77c5e2ef6d8.png)

5. Move the other beams in the same corner into position (some needs to be moved -150 and also in the y-axis)
6. Do a butt-joint `shift + T`:
![Screenshot 2023-03-29 144417](https://user-images.githubusercontent.com/12858029/228543869-181d6cc5-e43d-43f3-b668-619818210df4.png)
7. Undo the butt-joint `ctrl + z`
8. Extend the column to top and bottom beam with `shift + E`:
9. 
![Screenshot 2023-03-29 144417](https://user-images.githubusercontent.com/12858029/228544560-acd0a876-3b1f-41d8-9a0c-ed6b95fa6cfc.png)
10. Do this for another beam and column
11. Save the Ifc-project in the scene pane ("Save Project" button, not "Save As").
12. Create a new Blender file, `ctrl + N` -> general -> don't save
13. In the scene pane, open the same Ifc-file once again
14. Inspect if all hollowcore-elements are in correct position. Some of those that were in correct position in the beginning, might be in the wrong position now:

![Screenshot 2023-03-29 143513](https://user-images.githubusercontent.com/12858029/228547975-d82475bd-7dc4-4567-9ea7-30a0715dcf39.png)


I made the above steps with version `blenderbim-230328`. Sometimes I get only one element moved, and sometimes a bunch.

### Some thoughts:
- When the issue was very present, around 20 elements would move each time I saved. At that time I had my laptop hooked up to two external monitors, and had high memory usage (around 90% of 16GB ram).
- At the time of writing this, memory usage is around 60%, and laptop is not hooked up to external monitors.
- It seems like there is a correlation between how badly it messes up, and how loaded the system is. Considering that it appears to be non-deterministic, could possibly be some multi-threading issue/race condition (that gets worse the less system resources are available)?

**Comment by KaareZ** [comment]
It doesn't appear that this issue persists in recent releases.
