### ISSUE TITLE
ifcpatch import error

### ISSUE THREAD

**Issue by AzathaReddy** [IfcOpenShell/IfcOpenShell#2917]
import os
import ifcopenshell
from ifcopenshell import * 
import ifcopenshell.util.file
import ifcopenshell.util.element
import ifcopenshell.util.pset
import ifcpatch

# Define the input directory and output file path
input_dir = "building"
output_path = "buildingmerged.ifc"

# Get a list of all the IFC files in the input directory
input_files = [os.path.join(input_dir, f) for f in os.listdir(input_dir) if f.endswith(".ifc")]

# Read in the IFC files and merge them using IfcPatch
merged_file = None
for input_file in input_files:
    file = ifcopenshell.open(input_file)
    if merged_file is None:
        merged_file = file
    else:
        result = ifcpatch.execute(
            "merge",
            input_files=[merged_file, file],
            output_file=output_path
        )
        if result != 0:
            print("An error occurred while merging the IFC files.")
            break
        else:
            merged_file = ifcopenshell.util.file.read(output_path)

# Write the merged IFC file to disk
if merged_file is not None:
    ifcopenshell.util.file.write(merged_file, output_path)
    print("The IFC files were successfully merged.") this is my code to merge multiple ifc files in the folder "building" to one file. I can't import ifcpatch module. i have tried different ways to resolve by reinstalling ifcopenshell.

**Comment by aothms** [comment]
See https://blenderbim.org/docs-python/ifcpatch.html

ifcpatch is actually not included when you install ifcopenshell

**Comment by AzathaReddy** [comment]
how can I resolve this ? i tried in pycharm as well. In the list it shows ifcpatch and i installed 0.7.0 version.

**Comment by Moult** [comment]
https://blenderbim.org/docs-python/ifcpatch.html#source-installation shows how to use it from source.

**Comment by Moult** [comment]
Bump @AzathaReddy

**Comment by Moult** [comment]
Closing as user error.
