### ISSUE TITLE
Issues with IFC 7.0 Output

### ISSUE THREAD

**Issue by rwar33** [IfcOpenShell/IfcOpenShell#2921]
Hi All,

We have had IfcConvert embedded in our product for some time with no issues. We recently discovered an issue with the input data from one of our regular software sources, SDS2. They have an IFC export feature that exports their created model in Coordination view 2.0, IFC 2X3 schema. Previously, this was powered by STEP Tools (https://www.steptools.com/sln/ifc/) and was able to be converted to OBJ successfully. However, they have recently switched to ODA (https://www.opendesign.com/products/ifc-sdk) and now we are seeing failed geometry in the OBJ output. I have attached the IFC source file and the output OBJ file from IfcConvert 7.0.

[B1528_Canam.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11036967/B1528_Canam.zip)

Has anyone experienced this type of geometry failure or worked with the ODA SDK before? Any insight would be helpful. Thanks!!

Randy
Eterio Realities

**Comment by Moult** [comment]
Your model has large coordinates. This makes the OBJ very far away from the origin. The data is still correct, but your OBJ viewer may not be capable of viewing it.

![2023-04-01-082734_300x285_scrot](https://user-images.githubusercontent.com/88302/229235074-e356f919-9cfc-42f9-a1f3-2d04c6c40a54.png)

If the SDS2 product is dealing with buildings (as opposed to horizontal projects like roads, rail, etc), you should never have large coordinates and I would file a bug with them. You should use IfcMapConversion (or EPset_MapConversion in IFC2X3). I'm sure there is a way to set this in ODA's SDK.

![2023-04-01-082630_858x743_scrot](https://user-images.githubusercontent.com/88302/229236167-3f414860-116a-4505-92d2-a4d48b5fcabc.png)

You can see examples of how to bypass these large coordinates here: https://blenderbim.org/docs-python/ifcconvert/usage.html

Note your IFC has invalid area and volume units.
