### ISSUE TITLE
Test fails unexpectedly when using PartOf facet

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2930]
When running the following script, I expect that the test passes:

```
ifc = ifcopenshell.file()
element = ifcopenshell.api.run("root.create_entity", ifc, ifc_class="IfcWall")
# element2 = ifcopenshell.api.run("root.create_entity", ifc, ifc_class="IfcSlab")
container = ifcopenshell.api.run("root.create_entity", ifc, ifc_class="IfcBuildingStorey")
   
ifcopenshell.api.run("spatial.assign_container", ifc, product=element, relating_structure=container)

# create new IDS
my_ids = ids.Ids(title="My IDS")

# add specification to it
my_spec = ids.Specification(name="spec", minOccurs=1)
part_of = PartOf(relation="IfcRelContainedInSpatialStructure", entity="IFCBUILDINGSTOREY")

my_spec.applicability.append(part_of)
my_ids.specifications.append(my_spec)


# validate IFC model against IDS requirements:
my_ids.validate(ifc)

# show results:
reporter.Console(my_ids).report()
```

Instead, I get a FAIL in the output:

```
My IDS
[FAIL] (0/0) *spec
    Applies to:
        An element with an IfcRelContainedInSpatialStructure relationship with an IFCBUILDINGSTOREY
```

**Comment by Moult** [comment]
@vulevukusej what happens if you add a requirement?

**Comment by vulevukusej** [comment]
@Moult Same issue.  Updated script:

```
ifc = ifcopenshell.file()
element = ifcopenshell.api.run("root.create_entity", ifc, ifc_class="IfcWall")
# element2 = ifcopenshell.api.run("root.create_entity", ifc, ifc_class="IfcSlab")
container = ifcopenshell.api.run("root.create_entity", ifc, ifc_class="IfcBuildingStorey")
   
ifcopenshell.api.run("spatial.assign_container", ifc, product=element, relating_structure=container)

# create new IDS
my_ids = ids.Ids(title="My IDS")

# add specification to it
my_spec = ids.Specification(name="spec", minOccurs=1)
part_of = PartOf(relation="IfcRelContainedInSpatialStructure", entity="IFCBUILDINGSTOREY")
attribute = Attribute(name="attribute", value="value", minOccurs=1)


my_spec.applicability.append(part_of)
my_spec.requirements.append(attribute)
my_ids.specifications.append(my_spec)


# validate IFC model against IDS requirements:
my_ids.validate(ifc)

# show results:
reporter.Console(my_ids).report()
```

and result:

```
My IDS
[FAIL] (0/0) *spec
    Applies to:
        An element with an IfcRelContainedInSpatialStructure relationship with an IFCBUILDINGSTOREY
```

**Comment by vulevukusej** [comment]
I see, well that makes sense to me.  Updating the code results in the expected output:
 
```
My IDS
[PASS] (1/1) *spec
    Applies to:
        All IFCWALL data
    Requirements:
        An element must have an IfcRelContainedInSpatialStructure relationship with an IFCBUILDINGSTOREY
```

This does however make it rather cumbersome if you want to ensure all your building elements are assigned to an IfcBuildingStorey, since the subtypes are not checked, ie. I can't use "IFCELEMENT" or "IFCBUILDINGELEMENT" in the applicability.  I have to list all the individual classes..

**Comment by Moult** [comment]
https://github.com/buildingSMART/IDS/issues/10 it looks as though entity used to be required, and now it isn't. I guess we'll have to implement support for it.

Unfortunately there isn't a trick. Just a fact that IDS doesn't support inheritance. I personally don't like it. Feel free to voice your concern here https://github.com/buildingSMART/IDS/issues/86 ... regex matching doesn't really help.

**Comment by aothms** [comment]
Wow, at least with this this containment applicability check you'd be limiting yourself to products, but I can imagine people will start to write things like

    <applicability /><requirement><attribute>Name</attribute><requirement>

I.e a value for attribute `Name` must exist. Thinking this would only apply to building elements where in fact it would apply to every conceivable entity instance. 

But yeah, given a world without inheritance, making `<entity>` optional is probably the way to go.
