### ISSUE TITLE
Error if Specification doesn't have requirements.

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2933]
If the specification doesn't have requirements, then the user will get the following error:  `  File "C:\Coding Projects\ifc-server\server\app\ifctester\ids.py", line 175, in parse
    self.requirements = self.parse_clause(ids_dict["requirements"])
  File "C:\Coding Projects\ifc-server\server\app\ifctester\ids.py", line 180, in parse_clause
    for name, facets in clause.items():
AttributeError: 'NoneType' object has no attribute 'items'`

The offending code is here: https://github.com/IfcOpenShell/IfcOpenShell/blob/d7844ee8e82ff32fccd0684948bf3886c8b50daa/src/ifctester/ifctester/ids.py#L175

I would change it myself, but I'm not 100% sure this isn't intended?

**Comment by Moult** [comment]
Yes this is another change we haven't caught up to yet, discussion here: https://github.com/buildingSMART/IDS/issues/90

Not only does that change need to occur, the meaning of it needs to change in the validate function and the test cases should be written. For example:

 1. If the spec is required, and applicability > 0, then pass.
 2. If the spec is required, and applicability = 0, then fail
 3. If the spec is optional, then pass.
 4. If the spec is prohibited, and applicability > 0, then fail
 5. If the spec is prohibited, and applicability = 0, then pass

Would you like to do a PR? Adding some tests for this is also pretty critical as we use it to generate the bSI docs.

**Comment by vulevukusej** [comment]
Yeh I'll get on it.
