### ISSUE TITLE
Remove the array connection for the newly duplicated object.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2935]
Let's say you copy an element from an array, like below. 
Would be nice to have a way to remove the array connection for the newly duplicated object. 
![2023-04-04_17-36-35_Blender_blender](https://user-images.githubusercontent.com/507113/229937613-741670d1-29b4-4586-a347-164138dc7040.gif)

**Comment by theoryshaw** [comment]
nevermind.. found the way. :)
would maybe suggest on button on the modifer panel that removes this pset... 
i can try to figure it out. 
![2023-04-04_17-43-02_Blender_blender](https://user-images.githubusercontent.com/507113/229938327-a3e53faa-9f7c-4067-adcb-709654becff8.gif)

**Comment by Moult** [comment]
It should still be fixed, duplicating an object in an array should definitely clear the array relationship.

**Comment by theoryshaw** [comment]
yeah, makes sense.  You were probably going to do this anyway, but removing the 'duplicate link' connection too, would probably a good idea. 

![2023-04-04_18-40-22_Blender_blender](https://user-images.githubusercontent.com/507113/229946188-c74f47f2-1503-45c0-9753-8d58d757b4e7.gif)
