### ISSUE TITLE
If extrusion length changes in an array, it's not reflected in the array afterward. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2937]
If extrusion length changes in an array, it's not reflected in the array afterward. 
![2023-04-04_20-18-02_Blender_blender](https://user-images.githubusercontent.com/507113/229956845-0716d93a-1e45-4da2-9fde-509758b0de74.gif)

**Comment by brunoperdigao** [comment]
As I understand, this is related to any change in the parent object, not only extrusions. The IfcArray creates a copy of the object, but doesn't recreate the copies when edited. But if you increase the 'count' the new ones will have the changes. The easy solution now would be to reset the count to 1 (so all the copies are deleted), confirm, then edit again and return the count to where it was (it will create new copies). I guess this is done to avoid that deletion and recreation every time you edit something in the array configuration.
I was taking a look at the code, and I think the solution would be to create an operator to update the geometry, that would delete all the children objects and create new copies. If there isn't anyone working on this, I would like to tackle it.

**Comment by Moult** [comment]
@brunoperdigao go for it! I think the best way would be to create a manual "Refresh" button in the IFC Array panel that allows the user to trigger changes to be propagated.

**Comment by theoryshaw** [comment]
Or a toggle, that will either automatically refresh or not.

**Comment by brunoperdigao** [comment]
@Moult I think this made me realize another bug. I don't know if it should be a new issue. But basically, when  the IFC Array deletes children objects, all the deleted copies remains persistent in the IFC file, but not in Blender. This happens by using the Sync Children toggle or by reducing the count.
I noticed this when I tried to go to activate a drawing camera:
```
Python: Traceback (most recent call last):
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 938, in execute
    core.activate_drawing_view(tool.Ifc, tool.Drawing, drawing=tool.Ifc.get().by_id(self.drawing))
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\core\drawing.py", line 305, in activate_drawing_view
    drawing_tool.activate_view(camera)
  File "C:\Users\---\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\tool\drawing.py", line 1251, in activate_view
    obj.hide_viewport = element not in drawing_elements
AttributeError: 'NoneType' object has no attribute 'hide_viewport'
```
Those 'NoneType' are created by `IfcStore.get_element` when used in IfcElements that do not have a Blender object. 
What is the best approach here?
1 - There is a better way to remove the children objects?
2 - Or should I just create a way for the drawing to ignore 'NoneType' objects?

Obs - This bug doesn't happen if I save the file and reopen it, before trying to activate the camera.

**Comment by Moult** [comment]
Deletion right now is a delayed process and only occurs on file save. I guess this isn't actually a smart move :) Please create a new bug but likely this will be solved as we make the change for deletion to happen exactly when you ask it to.
