### ISSUE TITLE
Error on creating drawing after setting EPset_Drawing to value and then to Null

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#2939]
Way to reproduce:
1) Create a new project, add a wall, setup a drawing. 
2) Add some value to "Include" in drawing's EPset_Drawing (For example ".IfcWall" - the drawing will include only walls) and then print the drawing.
3) Mark EPset_Drawing.Include as Null and try to print the drawing again - it will result in the error below.

The only difference in .ifc between steps 2 and 3 is in those 2 lines. 
![image](https://user-images.githubusercontent.com/9417531/230060294-d41e7ffa-b1f8-444f-b60e-85675dbdba7b.png)
Noted that if the last line will be replaced with `IFCPROPERTYSINGLEVALUE('Include',$,IFCTEXT(''),$);` there will be no error.

File with error: 
[bug.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11158045/bug.ifc.txt)

Traceback:
```
Traceback (most recent call last):
  File \Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 164, in invoke
    return self.execute(context)
  File \Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 213, in execute
    linework_svg = self.generate_linework(context)
  File \Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 487, in generate_linework
    self.serialiser.write(elem)
  File \Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1505, in write
    return _ifcopenshell_wrapper.SvgSerializer_write(self, *args)
RuntimeError: Invalid cast
Error: Python: Traceback (most recent call last):
  File \Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 164, in invoke
    return self.execute(context)
  File \Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 213, in execute
    linework_svg = self.generate_linework(context)
  File \Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 487, in generate_linework
    self.serialiser.write(elem)
  File \Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1505, in write
    return _ifcopenshell_wrapper.SvgSerializer_write(self, *args)
RuntimeError: Invalid cast
```

**Comment by Moult** [comment]
Huh, my guess is that this is a C++ bug in `serializers/SvgSerializer.cpp`.

```
		std::map<std::string, std::string> prop_map;
		for (auto& p : props) {
			prop_map[p.pset_name + "." + p.prop_name] = p.value;
		}
		auto pit = prop_map.find("EPset_Drawing.Scale");

```

The prop_map expects a string value, which probably fails when it encounters a null value (which is allowed).

Either don't bother with prop_map and only look at Scale (the rest isn't relevant to C++ right now at least) or check for null before assigning to prop_map. I'll let @aothms make the call.
