### ISSUE TITLE
How to apply a transformation matrix to an entire IFC file

### ISSUE THREAD

**Issue by MarcosCobena** [IfcOpenShell/IfcOpenShell#2940]
Hello,

Thank you in advance for all the hard work put on this library.

We would like to change the position, rotation & scale of an entire IFC file. We think just setting ObjectPlacement property for the top IfcProject could do the job but, cannot find how to achieve it in Python. May you point us to any piece of code which could serve as a starting point? Is this actually possible?

Thank you again!

**Comment by Moult** [comment]
IfcPatch has a recipe that does exactly that: https://blenderbim.org/docs-python/ifcpatch.html

https://blenderbim.org/docs-python/autoapi/ifcpatch/recipes/OffsetObjectPlacements/index.html
