### ISSUE TITLE
IfcConvert SVG output does not XLM encode space names (at least for '&')

### ISSUE THREAD

**Issue by groothuyse** [IfcOpenShell/IfcOpenShell#2942]
When using IfcConvert v0.7.0 to generate an SVG floorplan (great tool btw!), I noticed it will generate an invalid SVG if there are IfcSpace objects that have a name that includes an '&' character.

For example in [this ifc file](https://raw.githubusercontent.com/buildingSMART/Sample-Test-Files/master/IFC%202x3/Medical-Dental%20Clinic/Clinic_Architectural.ifc) 

There are names like: "WTS & MEAS. ROOM" and "CLEAN SUP. & EQUIP." which are put as-is into the SVG like this:

`<tspan x="720.859" dy="-0.65000000000000002em">CLEAN SUP. & EQUIP.</tspan>`

Here the & should have been XML encoded to &amp;. In general the XML encoding is probably missing.

It would be great if regardless of the names, the output would always be a valid svg.

**Comment by aothms** [comment]
Thank you. In this particular case it's likely adding IfcUtil::escape_xml around the argument https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/SvgSerializer.cpp#L1513 Are by any chance you in the position / interested in testing the change and submitting a PR yourself?

In other cases this appears to already be done, but I'm not sure how comprehensively https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/SvgSerializer.cpp#L2272 Writing XML by concatenating strings is always a bad idea :(
