### ISSUE TITLE
BlenderBim - feature request - Create an Include all / Exclude all reference

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2945]
The new drawing phase / sync tool is amazing! Thanks for the constant updates

The issue:
At present to properly exclude/include elements each Pset needs to be individually added to the camera view

So for a small house you need these values to exclude demolished elements:

Walls:
.IfcWall[Pset_WallCommon.Status = "DEMOLISH"] 
Windows:
.IfcWindow[Pset_WindowCommon.Status = "DEMOLISH"] 
Doors:
.IfcDoor[Pset_DoorCommon.Status = "DEMOLISH"] 
Roofs:
.IfcRoof[Pset_RoofCommon.Status = "DEMOLISH"] 
Floors:
.IfcFloor[Pset_FloorCommon.Status = "DEMOLISH"] 

The request:

Is it possible to have a Pset that excludes or Includes ALL elements that have a NEW or EXISTING or DEMOLISH Pset?

With something like .IfcElement[Pset_Status = "NEW"] ?

OR even a toggle that defines the camera as a NEW phase camera or Excludes NEW Elements
Similar to the check box when adding the Common.Status Pset

A Mock up for the UI:

![image](https://user-images.githubusercontent.com/78321676/230311014-337d95de-7b86-40f4-b16e-2adf89b34a23.png)

It's currently all possible at present so this is not essential at all but Having something like that would definitely speed up the drafting process a tonne

**Comment by Moult** [comment]
Have you tried: `.IfcElement[r"Pset_.*Common"."Status"="NEW"]` ?

**Comment by Plae-Blue-Dot** [comment]
It doesnt seem to be working with that one

Model example"
![image](https://user-images.githubusercontent.com/78321676/230314375-27598fe7-0a65-49de-8f93-ecad132c442e.png)
These 2 walls have a NEW Pset

SVG example:
![image](https://user-images.githubusercontent.com/78321676/230314476-07849ceb-5c65-4673-b180-f69ea4ea4d61.png)
When printing or selecting it does not exclude them

**Comment by theoryshaw** [comment]
How do you do boolean operators?

Somthing like `.IfcElement[r"Pset_.*Common"."Status"="DEMOLISH"] AND .IfcElement[r"Pset_.*Common"."Status"="EXISTING"]`
OR
`.IfcElement[r"Pset_.*Common"."Status"="DEMOLISH"] OR .IfcElement[r"Pset_.*Common"."Status"="EXISTING"]`

**Comment by Moult** [comment]
`&` (and) and `|` (or)

**Comment by ChubbyQuark** [comment]
The new wild card filtering is great. As the camera view reflects the include/exclude fileds when toggled it feels this UI area in this thread is starting to converge with the IFC selector feature.  https://github.com/IfcOpenShell/IfcOpenShell/issues/2741

How well does blender handle pop-up dialogue boxes as UI elements? Could it be used to create a filter window similar to the VG in Revit where filters can be applied to cameras or viewport in a single place? Not an essential for creating drawings but would be a good addition to have planned in for a future release.

**Comment by Moult** [comment]
@ChubbyQuark we do plan to handle product types for drawings allowing for the equivalent of Revit's "view templates".
