### ISSUE TITLE
BlenderBim - When giving a text object a tag it does not retain rotation and the tag does not scale with text size

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2946]
When giving a text object a tag it does not retain rotation and the tag does not scale with text size

Regular text with no rotation and a door-tag symbol:
![image](https://user-images.githubusercontent.com/78321676/230313535-72842235-54b0-4a72-b3ec-d26c23850976.png)

Header text with rotation

Model:
![image](https://user-images.githubusercontent.com/78321676/230313763-c65c445e-50dd-4613-9836-9869fa4126a3.png)

SVG:
![image](https://user-images.githubusercontent.com/78321676/230313814-3211da2b-e8cb-4a31-a61a-febd5b36994b.png)

**Comment by Moult** [comment]
I think this is intentional. When a tag is used, the tag is what controls how the text is displayed. That way you can use the full flexibility of SVG styling for tags as opposed to IFC's primitive text styling capabilities.

**Comment by Moult** [comment]
Sorry, I think you're right, the rotation should still have an effect.

Maybe the text classes should be added to the tag, but the tag should still have it's classes as a higher priority so that it can override it.

**Comment by theoryshaw** [comment]
+1 on rotation.

**Comment by Andrej730** [comment]
Added option to rotate and scale text tag (only uniform scale is supported, atleast for now)
