### ISSUE TITLE
BlenderBIM - Blender will crash if you `ctrl/Z` while using IFC Array

### ISSUE THREAD

**Issue by mdjska** [IfcOpenShell/IfcOpenShell#2948]
It can't be seen in the video, but Blender crashes immediately when I click `cmd/Z`. I'm on macos, but I know that the same thing happens on windows.
 
https://user-images.githubusercontent.com/16716147/230475321-c3d97f9e-9bdf-47ef-9eb3-5fc6e1b4493e.mp4

**Comment by Moult** [comment]
FYI @Andrej730
