### ISSUE TITLE
Complex restrictions

### ISSUE THREAD

**Issue by maks2199** [IfcOpenShell/IfcOpenShell#2952]
When I am trying to create a complex restricition (https://github.com/buildingSMART/IDS/blob/master/Documentation/restrictions.md), enumeration in my case, I have an error on this line:
https://github.com/IfcOpenShell/IfcOpenShell/blob/de3dfcdc436eac770aa9083b41f77adc9083a49b/src/ifctester/ifctester/facet.py#L100
![image](https://user-images.githubusercontent.com/55157621/230564986-1a50fbd8-3b09-459d-9623-3dfd28069750.png)

I am using Property facet and trying to create restriction with several possible values, so I am using list() type for "value" parameter:
![image](https://user-images.githubusercontent.com/55157621/230564300-a294cc64-e625-4dc0-b216-8ec948aa82f5.png).

I suppose that the problem is in `to_ids_value()` function. It is trying to use `.base` method from string. 
Also `x = p.asdict()`  on 102 line creates an error for list of strings.

Maybe I shouldn't use list of strings, or maybe there is a bug.

In the end I need to get construction like this:
![image](https://user-images.githubusercontent.com/55157621/230565406-f6f46cb5-f278-40d4-a725-f53a6e50f1c7.png)

**Comment by maks2199** [comment]
Ok guys, I figured it out by experiments.

So, what I need, is to create a Restriction object with dict() as the first parameter. 
The dictionary has structure: "restriction type": "restriction values".

restriction type: enumeration, pattern...
And, for example, in my case, restriction values is a list of strings. So for me, It will be like that:
![image](https://user-images.githubusercontent.com/55157621/230568694-9af6b2f8-c6f8-4aa3-859b-748228a3f726.png)

Tell me please, whether I am doing it right, or there is more propper way to do it, and we can close this issue :)

**Comment by Moult** [comment]
That is correct. You can see many examples of how to create IDSes here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifctester/test/test_facet.py
