### ISSUE TITLE
Save path to Data directory

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2953]
Would be nice if the data directory is remembered from one session to another. 
Currently, i have to assign this anew every time i open blender.
![image](https://user-images.githubusercontent.com/507113/230633086-1f07b1d7-24e9-41b0-82e0-1cae5842026e.png)

**Comment by theoryshaw** [comment]
I have a feeling this data path should be project specific too--that is saved with the IFC file.  Probably relative path, would be best.

**Comment by Moult** [comment]
This is related to #2516 .

**Comment by Moult** [comment]
Solved in https://github.com/IfcOpenShell/IfcOpenShell/commit/2145b2f8e2ea97871b68be4a068c77ad25eb7540
