### ISSUE TITLE
A toggle to create drawing in background

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2954]
Would suggest a toggle of some sort that allows you to create the drawing in the background. 

That is, a majority of times i want to rerun a drawing, i would prefer it does it in the background, and doesn't open it in inkscape or my browser. 
![image](https://user-images.githubusercontent.com/507113/230637443-ea830462-9356-4ee3-bb08-329e211a5b47.png)

**Comment by Moult** [comment]
The premise is sound but I'm not convinced about the UI. There needs to be a long hard think about how the sheets / drawings panel are designed. There's a lot of inconsistency and I don't want to keep on adding buttons and checkboxes.

**Comment by Gorgious56** [comment]
In order to remove at least one, maybe we can remove the "Activate Drawing" button and activate a drawing when its name is clicked in the UI List ? As a user I wouldn't fint it too surprising, unless there is a significant computation cost to this or it has an impact on the ifc file ?

**Comment by Gorgious56** [comment]
Maybe the drawing panel could be split into a "Drawing design" panel with all properties pertaining to what's going on inside Blender and a "Drawing export" panel with all properties related to svg export ?

**Comment by Moult** [comment]
> activate a drawing when its name is clicked in the UI List

It used to behave this way a long time ago but I changed it because I kept on misclicking and it was a little expensive to switch / load :) No impact on IFC though, but slow especially if many objects in the scene.

> Maybe the drawing panel could be split into a "Drawing design" panel with all properties pertaining to what's going on inside Blender and a "Drawing export" panel with all properties related to svg export ?

Having a hard time visualising this, able to scribble up a mockup in paint or something?
