### ISSUE TITLE
IfcOpenShell installation issues

### ISSUE THREAD

**Issue by fotsing365** [IfcOpenShell/IfcOpenShell#296]
Hi every one I am new in IfcOpenShell. I try to install IfcOpenShell but i receive this error
![capture](https://user-images.githubusercontent.com/24406778/32679944-c7a559c6-c668-11e7-8852-4605c84aea59.PNG). I don't know how to fixe it. I tried in vain to find a solution online but. Please could anybody help me. Escuse me for my bad english i' am french speaking

**Comment by aothms** [comment]
Hi,

Probably you are manually linking to the boost libraries and did not use the build script?
https://github.com/IfcOpenShell/IfcOpenShell/tree/master/win

By default IfcOpenShell uses a static runtime library on windows (`StaticRelease`) but the boost libraries you got are compiled against the dynamic runtime (`mt`) [1] you need to have the ones with an `s` in there, compile boost with `runtime-link=static`.

[1] http://www.boost.org/doc/libs/1_55_0/more/getting_started/windows.html#library-naming

Hope that helps,

Kind regards,
Thomas

**Comment by fotsing365** [comment]
Thank Thomas

**Comment by Moult** [comment]
From the response this seems to be resolved, so closing :)
