### ISSUE TITLE
When copying ifcdoortypes, can it copy the BBIM_Door Pset as well. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2974]
Possible to copy the BBIM_Door Pset, when a door type is copied as well?

When you spend a lot of time to create an ifcdoortype with the IFC door modifier and you have to create another type that has similar parameters, it would be nice just to copy the type and a new BBIM_Door Pset would be copied as well. 

This probably applies to ifcwindowtypes, as well as others.

**Comment by Moult** [comment]
I just tested this and the pset is copied?

**Comment by theoryshaw** [comment]
copied as in creating a new pset...

I created 4 types by copying one type, as you can see all the types share the same pset.  So if you change the width in the modifier, if changes all the types.   Hope that make sense. 

https://www.dropbox.com/s/v2rm1sdzif4eexu/2023-04-12_20-51-38_Blender_blender.mp4?dl=0

https://www.dropbox.com/s/a8kbjby85xgvmh0/2023-04-12_20-53-43_Blender_blender.mp4?dl=0

**Comment by theoryshaw** [comment]
They all share this 
```#45550=IfcPropertySingleValue('Data',$,IfcLabel('{"door_type": "SINGLE_SWING_LEFT", "overall_height": 9.0, "overall_width": 4.0, "lining_properties": {"lining_depth": 0.4059999883174896, "lining_thickness": 0.0625, "lining_offset": 0.0, "lining_to_panel_offset_x": 0.0625, "lining_to_panel_offset_y": 0.0625, "transom_thickness": 0.0, "casing_thickness": 0.2083333283662796, "casing_depth": 0.0416666679084301, "threshold_thickness": 0.0}, "panel_properties": {"panel_depth": 0.1148293986916542, "panel_width_ratio": 1.0}}'),$)```
