### ISSUE TITLE
BlenderBim - AU library small basin 2d representation seems rotated

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2976]
Here is the old 2d representation:
![image](https://user-images.githubusercontent.com/78321676/231728036-986bab84-971b-4fb8-97a2-cb8cb7837432.png)

Here is the latest one:
![image](https://user-images.githubusercontent.com/78321676/231728133-4326c01f-21c4-439c-87ae-6d020d148eae.png)

Marking the location of the tap is appreciated but the curved basin should not just be on one side

**Comment by Andrej730** [comment]
Turned out it was both 2d and 3d representations and it also affected toilets.
Now fixed
<img src="https://i.imgur.com/GP4O4W2.png">
<img src="https://i.imgur.com/xgmRIxF.png">

**Comment by Plae-Blue-Dot** [comment]
Thanks so much Andre!
