### ISSUE TITLE
Updates on the v0.8.0 branch

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#2977]
People might have been seeing this on Twitter but I think an update here is also warranted as we're nearing a reasonable state in the v0.8.0 branch.

What you should know:

- v0.8.0 will bring the choice for multiple geometry libraries (ifcopenshell, cgal) for interpretation of the procedural IFC geometry definitions.
- On the python side we're at a near 100% compatibility. The main difference would be an optional new argument to ifcopenshell.geom.iterator and create_shape() where you can add a `"cgal"` or `"opencascade"``  argument to indicate to which geometry library to offload the geometry interpretation / meshing.
- On the C++ side we'll see some needed refactoring (still needs to be applied) to reduce ambiguity between schema constructs and toolkit classes, think like `IfcParse::IfcFile` -> `ifcopenshell::file`. 
- When we're positive there are no major regressions anymore, we'll make v0.8.0 the default branch
- Pull request on the C++ side have stayed open for a long time. Sincere apologies. I will rebase them to v0.8.0 and start applying them.
- Automated builds are coming through now for all platforms: https://github.com/IfcOpenBot/IfcOpenShell/commit/98a73f1646c987b6aa512050ab19ff81c821d72c#commitcomment-108765313

Major features still developed on this branch:

- [ ] A hybrid kernel with CGAL for explicit faceted stuff and opencascade for everything else
- [ ] An option for a statically typed entity instance attribute storage model with parse-time validation. Currently we have a runtime data variant for every attribute value which is rather slow and memory intensive.
- [ ] An option for sub-element based hashing and more minimal geometry outputs
- [ ] An official NPM package with ifcopenshell-wasm (which uses pyodide, currently available as a preview)
- [ ] 👉 Support for IFC4.3 infra geometries https://opencollective.com/opensourcebim/projects/full-infra-geom-implementation 👈

CGAL can be used to export a perfect manifold outer shell of the facade with small gaps auto closed. Developed in collaboration with the [@tudelft3d](https://twitter.com/tudelft3d) group. We can write this to human-friendly CityJSON or OBJ.

![afbeelding](https://user-images.githubusercontent.com/1096535/230918771-bf86a2d7-9aff-463d-b3df-36e591a4a48e.png)

Image is produced with:

𝙸𝚏𝚌𝙲𝚘𝚗𝚟𝚎𝚛𝚝 𝚍𝚞𝚙𝚕𝚎𝚡_𝚊.𝚒𝚏𝚌 𝚍.𝚘𝚋𝚓 --𝚎𝚡𝚝𝚎𝚛𝚒𝚘𝚛-𝚘𝚗𝚕𝚢 --𝚒𝚗𝚌𝚕𝚞𝚍𝚎 𝚎𝚗𝚝𝚒𝚝𝚒𝚎𝚜 𝙸𝚏𝚌𝚆𝚊𝚕𝚕 𝙸𝚏𝚌𝚂𝚕𝚊𝚋 𝙸𝚏𝚌𝚆𝚒𝚗𝚍𝚘𝚠 𝙸𝚏𝚌𝙳𝚘𝚘𝚛 𝙸𝚏𝚌𝙵𝚘𝚘𝚝𝚒𝚗𝚐

(This is a computationally expensive operation and still needs optimizations to make this work on big models).

### Taxonomy

We added a novel intermediate layer between the schema and the geometry library: 'geometry taxonomy'. This simplifies adding a new geometry library to ifcopenshell because only some well known constructs needs to be implemented (reduces compilation time and output binary size):

synonyms:
{IfcClosedShell, IfcTesselatedFaceset}
   → sʜᴇʟʟ

parametrized types:
{IfcIShapeProfileDef, IfcTShapeProfileDef, ...}
   → ғᴀᴄᴇ

schema differences:
{Ifc2x3::IfcExtrudedAreaSolid ... Ifc4x3_add1::IfcExtrudedAreaSolid}
   → ᴇxᴛʀᴜsɪᴏɴ

This taxonomy isolates exactly the information that impacts geometry in a easily comparable and hashable format. So we can cache granularly and efficiently. We're also able to restructure the output to allow more granular reuse in the geometric output formats.

### Performance

Over the past years, IFC has become geometrically more simple and explicit.

IfcOpenShell, sitting on a heavy geometry kernel, was late to adapt to that.

![afbeelding](https://user-images.githubusercontent.com/1096535/230919028-0e2736e0-2f30-46e0-9abb-356e651d7e13.png)

(This trend of IFC becoming simpler, the resulting mismatch in schema complexity and future steps towards a manageable complexity in IFC was part of our presentation to the bSI steering committee.)

![afbeelding](https://user-images.githubusercontent.com/1096535/230919103-ea6d7957-d7d8-4a66-b3ad-7c65a4e9cbb0.png)

[https://speakerdeck.com/aothms/ifc5-ad](https://t.co/y2ws5ETWGi)](https://speakerdeck.com/aothms/ifc5-adequate-complexity-maximum-reliability)

CGAL and OpenCASCADE make very different choices:

*OpenCASCADE:* Associated surfaces and curves also to explicit planar data. Resulting extra indirections in data model and computation of representations in parametric space are costly. Algorithms complex due to tolerances. (A visualization of the indirections in the data model can be seen here https://github.com/IfcOpenShell/IfcOpenShell/issues/2851#issuecomment-1501070534)

*CGAL:* Polyhedral format, no curved surfaces. Algorithms simpler due to exact number types. Number type is compile-time parametric. E.g arbitrarily precise binary trees of operands or machine native double (latter not robust for boolean operations; cgal-simple in IfcOpenShell).

There are a lot of questions in the performance diagram (minimal improvement in multi-threading as mostly IO bound in RV?). Why is cgal-simple actually slower in single threaded mode? But before diving deeper we first still need to do some housekeeping on the v0.8 branch.

> Why is v0.8 opencascade slower than v0.7?
>
> @Moult 

It's likely because of this intermediate layer. It's a two step process now. I'm a bit surprised though at the magnitude of this. The difference is larger than the runtime with cgal altogether. Probably also involves caching which we don't do at the geom lib level anymore.

> would make dependencies and libs also significantly smaller (CGAL < OpenCascade) and brings this smaller backpack e.g. to the WASM table in turn, right?
>
> @jakob-beetz 

My thoughts exactly, but first experiments are not so promising. Being a template library it can actually generate a lot of machine code. We still need to tweak this (maybe only cgal-simple) but first attempt was CGAL > OpenCascade in compiled object size.

**Comment by dirkolbrich** [comment]
I do not want to be a killjoy, but did you checked for license compatibility between IfcOpenshell and Cgal?

The first occurrence of a GPL licensed include I came across is in [/src/ifcconvert/validate_space_boundaries.cpp](
https://github.com/IfcOpenShell/IfcOpenShell/blob/4127247230b1bc9b534faf38a3a5c087c8f557b8/src/ifcconvert/validate_space_boundaries.cpp#L9), which would invalidate the LGPL license of IfcOS.

CGAL/Polyhedron_3.h is part of the [3D Polyhedral Surface library](https://doc.cgal.org/latest/Polyhedron/group__PkgPolyhedronRef.html) which is licensed under GPL.

I am not a lawyer, so please correct me if I'm wrong.

**Comment by aothms** [comment]
@dirkolbrich You're absolutely right, we need to properly document this. CGAL will be an optional dependency. So implementers will have these options:

- Opensource IfcOpenShell+OpenCASCADE(+CGAL)
- Proprietary under LGPL IfcOpenShell+OpenCASCADE
- Proprietary IfcOpenShell(+OpenCASCADE)+CGAL with a commercial CGAL license (not that expensive)

I hope to get to your PR today. I was hoping to rebase everything to v0.8, but I was too optimistic on the effort still required there.

**Comment by dirkolbrich** [comment]
Thanks for your quick response. Your proposed hint to the license options would be a start to mitigate the license problem.

There is another issue regarding GPL/LGPL lurking with the SVGFill library though. Within `src/svgfill/src/scgfill.cpp` there is an include of `#include <CGAL/Arr_segment_traits_2.h>`and `#include <CGAL/Arrangement_2.h>`which are both part of the [CGal 2D Arrangements library]( https://doc.cgal.org/latest/Arrangement_on_surface_2/group__PkgArrangementOnSurface2Ref.html) licensed under GPL.

SVGFill is only excluded with the `MINIMAL_BUILD` option. Maybe we can find a replacement?

**Comment by aothms** [comment]
@Moult already has an alternative  implementation using shapely (bsd) in python

**Comment by Amoki** [comment]
I'm not sure to understand the problem. https://www.cgal.org/license.html says the paid license is only needed if CGAL code is modified. As long as IfcOpenShell only uses CGAL without modifying it, I think it's OK, no?

**Comment by Moult** [comment]
@Amoki I think the issue is that IOS is LGPL whereas portions of CGAL is GPL.

This is totally fine for things like BBIM which is GPL, but if you're building a non-compatible licensed software with IOS (e.g. proprietary) then you either can't use CGAL, or have to pay for CGAL.

 - Your tool is LGPL using LGPL IfcOpenShell+OpenCASCADE
 - Your tool is GPL using LGPL IfcOpenShell+OpenCASCADE+GPL CGAL
 - Your tool is Proprietary using LGPL IfcOpenShell+OpenCASCADE
 - Your tool is Proprietary using LGPL IfcOpenShell+OpenCASCADE+commercial CGAL

**Comment by dirkolbrich** [comment]
Unfortunately it is not that simple.

The GPL license can be basically boiled down to "one drop poisons the well". If ANY of the code dependencies in your project uses a GPL license, your code is GPL as well.

I am not a lawyer, but this is the gist I got from multiple times reading the extensive GNU FAQ on the GPL license model -> [Frequently Asked Questions about the GNU Licenses](https://www.gnu.org/licenses/gpl-faq.html)

With the current status of IfcOpenShell on branch v0.7.0 - **ONLY** - the C++ libraries for IfcParse, IfcGeom and the Serializers are LGPL licensed. **ALL** Python code falls under GPL, as the `src/ifcwrap` code includes the `ifcopenshell/svgfill` submodule, which in turn uses GPL licensed CGAL libraries.
With the changes to the `src/ifcgeom` library in branch v0.8.0, the C++ library for IfcGeom will fall under GPL license as well. Except of course one acquires a commercial license from the CGAL project.

After my remarks on the license I looked through all the IfcOpenShell code and made notes on the used libraries and dependencies. I forgot to post it, so here is the unordered list of my findings:

OpenCascade - LGPL-2.1 license with exceptions
https://github.com/Open-Cascade-SAS/OCCT

Boost - BSL-1.0 License 
https://www.boost.org

bcrypt - BSD-3-Clause license
https://bcrypt.sourceforge.net
Necessary for boost version >= 1.67, bundled with Boost?

libxml2 - MIT license
https://github.com/GNOME/libxml2

openCollada - MIT license
https://github.com/KhronosGroup/OpenCOLLADA

pcre v8.12 - BSD license
https://github.com/KhronosGroup/OpenCOLLADA/tree/master/Externals/pcre
used if Collada support is enabled, bundled with the OpenCollada source

glTF - no license? just a format specification?
https://github.com/KhronosGroup/glTF

nlohman-json - MIT license
https://github.com/nlohmann/json
used if glTF support is enabled
 
gmp - dual licensed LGPLv3 and **GPLv2**
https://gmplib.org

mpfr - LGPLv3 or later license
https://www.mpfr.org

usd - modified Apache 2.0 license
https://github.com/PixarAnimationStudios/OpenUSD

svgfill - LGPL-2.1 license - but is actually GPL as it uses GPL licensed CGALlibraries
https://github.com/IfcOpenShell/svgfill
submodule to IfcOS
- used in:
    - /src/ifcwrap/IfcGeomWrapper.i
    - /src/ifcwrap/IfcPython.i

svgpp - BSL-1.0 License 
https://github.com/svgpp/svgpp
submodule to svgfill

CGAL - dual licensed with LGPL or GPL dependent on package
- in IfcOS v0.7 CGAL is used in:
    - /src/svgfill
    - /src/ifcconvert
    - /src/ifcconvert/cityjson
- in IfcOS v0.8 additionally used in:
    - /src/ifcgeom/kernels/cgal

CGAL 5.6 - 2D and 3D Linear Geometry Kernel - LGPLv3 license
https://doc.cgal.org/latest/Kernel_23/group__PkgKernel23Ref.html

CGAL 5.6 - Number Types - LGPLv3 license
https://doc.cgal.org/latest/Number_types/group__PkgNumberTypesRef.html

CGAL 5.6 - 2D Polygons - LGPLv3 license
https://doc.cgal.org/latest/Polygon/group__PkgPolygon2Ref.html

CGAL 5.6 - 2D Minkowski Sums - **GPLv3 License**
https://doc.cgal.org/latest/Minkowski_sum_2/group__PkgMinkowskiSum2Ref.html
dependency in IfcOSv0.7:
- /svgfill/src/svgfill.cpp

CGAL 5.6 - 2D Arrangements - **GPLv3 License**
https://doc.cgal.org/latest/Arrangement_on_surface_2/group__PkgArrangementOnSurface2Ref.html
dependency in IfcOSv0.7:
- /svgfill/src/svgfill.cpp

Hdf5 - BSD-3-Clause license
https://www.hdfgroup.org/solutions/hdf5/

zlib - custom open license, BSD style without Copyleft
https://zlib.net
used if Hdf5 support is enabled

Qt6 - dual licensed
used if QtViewer is build

Swig - **GPLv3 License** or later
https://www.swig.org
used as a tool to generate IfcOS code, not linked into IfcOpenShell

**Comment by Moult** [comment]
Ah I forgot about svgfill using CGAL. I've edited my post to accommodate that.

**Comment by aothms** [comment]
I agree with @dirkolbrich. Everything GPL needs to be either be available by means of some sort of plug-in architecture or be able to selectively disabled during compilation. Lot's of libraries deal with it that way, e.g libigl. We have been somewhat lazy with this.

> The Libigl code that interfaces with “copyleft” libraries is in include/igl/copyleft. Only include these headers if you are accept the licensing terms of the corresponding external library. For example, using include/igl/copyleft/tetgen requires that you accept the terms of the AGPLv3.
>
> https://libigl.github.io/license/
