### ISSUE TITLE
odd glitch where, when selecting objects, other stuff highlights

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2979]
https://www.dropbox.com/s/9tovymf1oe1l7z1/2023-04-13_11-12-16_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
I believe this issue is mostly an upstream problem (though mitigated slightly with the last commit). Try upgrading to 3.5 (I can recreate your issue on 3.3 on Windows, 3.4 on Linux works fine for me, and 3.5 on Windows works fine for me).

**Comment by Moult** [comment]
Note that this is probably also because we recently upgraded from BGL to GPU since Blender will no longer support BGL in newer versions, so likely Blender was still ironing out some fixes in GPU.
