### ISSUE TITLE
array's not remembered on save. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2980]
array's not remembered on save. 

video1: https://www.dropbox.com/s/83le8fixec07fjf/2023-04-13_14-39-53_Blender_blender.mp4?dl=0
video2: https://www.dropbox.com/s/uswoq6nfoj835ih/2023-04-13_14-41-04_Blender_blender.mp4?dl=0

**Comment by brunoperdigao** [comment]
I did some testing to see if this has anything to do with the recent changes, but I think not. This happens only when reducing the count, so I think the code only removes blender objects, but not the ifc elements.
I think this solves the issue:
![image](https://user-images.githubusercontent.com/57102715/231880674-fe527b5a-d680-41ca-a39c-baed6e9ea56b.png)

@Moult Not sure if this is the best solution. Let me know if it's worth a PR

**Comment by Moult** [comment]
FYI @Andrej730 delete tool is now available in tool.Geometry.delete_ifc_object()

**Comment by theoryshaw** [comment]
I think i still have some syncing problems: 
https://www.dropbox.com/s/r7jg1epmmlfxpcl/2023-04-14_14-24-49_Blender_blender.mp4?dl=0

**Comment by brunoperdigao** [comment]
I think this will solve:
![image](https://user-images.githubusercontent.com/57102715/232146419-883dfae4-aeff-45e7-a070-221277c3a531.png)
