### ISSUE TITLE
Tab an object to `bim.enable_editing_extrusion_profile()`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2983]
Would be boss if you could double click an object to `bim.enable_editing_extrusion_profile()` and once in edit mode, double click in empty space to exit out of edit mode.

**Comment by theoryshaw** [comment]
...and/or use 'tab' to enter `bim.enable_editing_extrusion_profile()`.

**Comment by Moult** [comment]
I like the Tab idea. That would free up Shift-E to be used for something else.

**Comment by Gorgious56** [comment]
I don't think double click fits well with the usual Blender workflow but "tabbing" in and out of edit mode would be way more straightforward.

Would just need to think about a way to inform newbies that they're modifying the profile and not the resulting geometry, to dissipate confusion. Maybe adapting the info message that's currently written when trying to edit a non-mesh object. something like "Entering edition of profile xyz"

**Comment by Gorgious56** [comment]
Should be fixed with #3142
