### ISSUE TITLE
BBIM asks for missing "styles" folder

### ISSUE THREAD

**Issue by haukj** [IfcOpenShell/IfcOpenShell#2985]
BBIM asks for the location Blender\3.4\scripts\addons\blenderbim\bim\data\styles but the contents is located in the assets folder.
Got the same error/bug on both windows and mac M1.

Error comes when trying to edit vector style and the list is empty(because of wrong folder location?)
Error disappears when folder is added.

.
------------------------------------------------------------
Python: Traceback (most recent call last):
  File "C:\Users\KjetilHaughom\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1243, in execute
    bpy.data.texts.load(os.path.join(context.scene.BIMProperties.data_dir, "styles", vector_style + ".css"))
RuntimeError: Error: Cannot read 'C:\Users\KjetilHaughom\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\data\styles\.css': No such file or directory

**Comment by Moult** [comment]
The vector style is a remnant of the old drawing generation system and has now been made obsolete in favour of the stylesheet property. Thanks for catching this!
