### ISSUE TITLE
Change the color/linestyle of SVG linework based on property value? 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2986]
https://community.osarch.org/discussion/1436/change-the-color-linestyle-of-svg-linework-based-on-property-value#latest

**Comment by Moult** [comment]
E.g. put `Pset_Foo.Bar` or more query keys if you want more metadata separated by commas in the Metadata property.

**Comment by theoryshaw** [comment]
I might be doing something wrong, but it looks like all the walls have the pset value, as only some of them should. 

video: https://www.dropbox.com/s/okr48awic790kf5/2023-04-14_23-12-41_Blender_blender.mp4?dl=0

file: https://gitlab.com/openingdesign/clothing_boutique/-/blob/f48bb025dbef3a4d217825a9d36980d2efc479d4/Clothing_Boutique.ifc

**Comment by theoryshaw** [comment]
Could be wrong, but I don't think this is working as intended.

**Comment by Moult** [comment]
Yeah this is a separate bug: #3001. Basically what happens is that when the fills get merged (i.e. by material), they also "combine" their CSS classes.
