### ISSUE TITLE
color of viewport annotations changed relative to the background

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2987]
I could probably do this, just logging here. 

Would be nice if the color of viewport annotations changed relative to the background. 

if a lighter background...
```    
decorations_colour: FloatVectorProperty(
        name="Decorations Colour", subtype="COLOR", default=(0, 0, 0, 1), min=0.0, max=1.0, size=4
    )
```

if darker background...
```    
decorations_colour: FloatVectorProperty(
        name="Decorations Colour", subtype="COLOR", default=(1, 1, 1, 1), min=0.0, max=1.0, size=4
    )
```

**Comment by theoryshaw** [comment]
... or create a preference setting.

**Comment by Moult** [comment]
A preference setting would be preferred, similar to how Blender itself has a bunch of colour / themeing sections in its settings window. We should also add a bunch in our add-on settings windows, to colour the CutDecorator, ProfileDecorator, and BaseDecorator for the annotations.
