### ISSUE TITLE
Have a prop_with_search work with profiles, as well. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2989]
Have a prop_with_search for the profiles, as well. 

![image](https://user-images.githubusercontent.com/507113/232132458-85349d8b-0695-4695-b81b-01d0113ef3a4.png)

![image](https://user-images.githubusercontent.com/507113/232132484-cced16dd-10af-4095-942c-5fce520742a2.png)

**Comment by Moult** [comment]
This is a good beginner task, would you like to have a shot?

**Comment by theoryshaw** [comment]
yes, will try!

**Comment by theoryshaw** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/pull/2996
I appreciate you letting me know this one was easy--please continue to do so, in the future.
