### ISSUE TITLE
Missing colors for IfcMappedItem-geometry

### ISSUE THREAD

**Issue by larsmoa** [IfcOpenShell/IfcOpenShell#30]
I have a case where colors are missing for some geometry. I have not been able to pinpoint the issue, but I have been able to create a minimal example file that reproduces the issue. The file can be opened in e.g. Solibri Model Viewer and here the color is correct. IfcConvert outputs the default gray material - even though there is a keyword IFCCOLOUR which should have been picked up by IfcConvert.

I created an illustration of how the material is associated with the geometry in the failing example, and how it is associated in a working file, see [colormapping.pdf](https://github.com/IfcOpenShell/IfcOpenShell/files/130799/colormapping.pdf).

Note! The file is an exempt from a full model. I cannot share this file here, but if it will help I can send it to you by email.

[GreenOnlyColour.ifc.zip]
(https://github.com/IfcOpenShell/IfcOpenShell/files/130790/GreenOnlyColour.ifc.zip)

**Comment by aothms** [comment]
Hi Lars, thanks for your detailed report. Glancing over the code [1], it does indeed seem this is omitted. More commonly styles would be applied somewhere in the `MappingSource.MappedRepresentation` of the `IfcMappedItem`, but indeed this is an oversight. I will update you on the progress. Would you object to the referenced file being added to the test files [2] to prevent regressions?

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomShapes.cpp#L509
[2] https://github.com/IfcOpenShell/IfcOpenShell/tree/master/test/input

**Comment by larsmoa** [comment]
Thank you for the quick reply! Feel free to add the test file to the tests :)

**Comment by aothms** [comment]
Thanks again. This was a trivial fix. Let me know if you encounter other issues.

**Comment by larsmoa** [comment]
Wow - thanks, that was really fast! I’m happy to say that this improves color handling a lot. Before this file was all grey:


Again, thanks!
