### ISSUE TITLE
User-specified rules for cut fill merging

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3001]
Something to think about in the future. 

If we'd like to differentiate new/existing, for example in the svg drawing, the svg path would have to be different--that is, if we're using metadata to create different svg classes

video: https://www.dropbox.com/s/i8thq6w9yhhnx7z/2023-04-16_09-41-23_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
Done. In addition, the default is now "any object of the same class (e.g. walls and other walls, but not walls and slabs) are joined if they have the same material and same status.

It'll probably still need more refinement over time.
