### ISSUE TITLE
Imbue svg projection paths/etc with metadata classes as well. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3002]
would be nice if svg projection paths/etc were imbued with metadata classes as well.

**Comment by theoryshaw** [comment]
test case includes, for example, changing a demoed door to red/dashed.

**Comment by Moult** [comment]
There are two parts of this bug: semantic projection polygons, and semantic projection edges. The former is used for creating fills/hatches in projection. The latter is for styling edges of those surfaces as well as 2D annotation styling like those 2D doors. I think for the latter, this is something @aothms needs to tackle on his end. For the former, I've made a start and I can do a bit here and there but there will also likely be some heavy lifting in the C++ side sooner or later.

**Comment by Moult** [comment]
OK there's been quite a bit of work done here and at least for simple models, it seems to work (fingers crossed).

For semantic projection polygons, there are two engines which are available, both disabled by default. One uses shapely, another uses svgfill. At the moment from my tests it seems as though shapely is both faster and produces more efficient / clean output but this may change in the future so both engines will be kept for a while. There are two new checkboxes in the camera settings for you to enable one or the other (don't enable both).

If enabled, projections will not just be lines, but polygons with CSS classes that you can add styling to. The shapely engine gives them their own CSS class called "surface" as a layer underneath the lines. Whereas the svgfill engine still uses the "projection" CSS class which combines both lines and polygons all in one. Hard to describe, try it out and see for yourself :)

We'll need to add a few more hatches to the default library for convenience, things like square and rectangular floor tiles, carpet, floorboards, brick elevations, wood?, etc. I recommend trying out using hatch fills and setting fill-opacity: 0.5 to give it a nice grey hatch.

In addition, spaces are now dealt with separately as a new layer. Here's the draw order from bottom to top:

 1. Raster rendering if enabled
 2. Hatch surfaces generated by shapely (in svgfill, this layer doesn't exist)
 3. Projection edges (in svgfill, this also includes polygons)
 4. Section cuts (note, merged cuts are generally above)
 5. Space cuts (useful for highlighting or colour coding rooms)
 6. Annotations (dims, labels, etc).

Some examples with ugly colours and random hatching / borders:

![2023-04-22-235321_715x662_scrot](https://user-images.githubusercontent.com/88302/233789705-d3e6d8aa-d01b-487c-bab0-cae50aa3fe2f.png)
![2023-04-22-234934_604x553_scrot](https://user-images.githubusercontent.com/88302/233789706-2ede938e-7e09-493a-97e2-5712e2b995d0.png)
![2023-04-22-234754_1439x780_scrot](https://user-images.githubusercontent.com/88302/233789707-aa37b128-c09a-4d9c-92c4-bdf6ae1ebda5.png)

**Comment by Moult** [comment]
Woohoo! Thanks to @aothms 's latest setting you can now set the styles of projection polygons independently from projection edges, for example:

```
.IfcSlab.projection { stroke: #F00; }
.IfcSlab.surface { fill: #AEE; }
```

![2023-08-31-123059_97x104_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/f6489620-220a-415a-9ebf-6cfa04fc938f)

**Comment by theoryshaw** [comment]
![giphy](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/28851de2-5264-41cd-b2a6-37a263b7fd7e)
