### ISSUE TITLE
AnnotationType works on one door, but not another.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3009]
[Clothing_Boutique.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11245432/Clothing_Boutique.txt)

video: https://www.dropbox.com/s/1pqc8dsvk6k980l/2023-04-16_20-48-18_Blender_blender.mp4?dl=0

**Comment by theoryshaw** [comment]
might be related to #3007

**Comment by theoryshaw** [comment]
something was wrong with that wall... i remodeled it, and it works now.

**Comment by Moult** [comment]
In this case one door had the property you were trying to tag and the other didn't, hence the error.
