### ISSUE TITLE
Any way to wrap text in schedule?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3010]
Any way to wrap text in a schedule?

file: https://gitlab.com/openingdesign/clothing_boutique/-/blob/43b43177ce39e5c4aacd7f8e05fe942fa8c03690/Clothing_Boutique.ifc

![image](https://user-images.githubusercontent.com/507113/232365309-fcb43990-80f4-4df1-b52c-9f3779eb2e53.png)

**Comment by Moult** [comment]
No, sorry. I think we also need to think about how to handle things like "notes", generic embedded SVGs, legends, stamps, and things like those that aren't schedules.

How about apart from schedules you can just insert arbitrary SVG documents (which you can design yourself)?

**Comment by theoryshaw** [comment]
For sure, that would be a good stopgap. 

...

For schedules, for a future roadmap, what's your thoughts on just using .csv's vs. .ods?... and then put all the presentation stuff in class/svg/html. 

That way, we can version track the csv nicely too.

**Comment by theoryshaw** [comment]
> How about apart from schedules you can just insert arbitrary SVG documents

Also, how about inserting HTML tables into the SVG?

**Comment by theoryshaw** [comment]
https://stackoverflow.com/questions/6987005/create-a-table-in-svg

**Comment by Andrej730** [comment]
Was looking for some way to wrap text, turn out that Inkscape does it manually - I guess it renders text at some point and splits it in banch of spans (though in Inkscape XML Editor it appears as a single tag).
![image](https://user-images.githubusercontent.com/9417531/235643477-bee04a13-9930-499f-957f-2bd0cb45b0d4.png)

ForeignObject can also be used to support text wrap. It does work in browser (Edge, Firefox) but currently have some problems implementing it. But what I've noticed is that it doesn't work in Inkscape. Would it be a dealbreaker for this method?

```xml
<svg>
    <foreignObject  x="225" y="630" width="50" height="50">
      <div xmlns="http://www.w3.org/1999/xhtml" style="width:3cm; word-wrap: break-word;">
            You can put really long lines of text here and they will wrap as you would hope they would.
      </div>
    </foreignObject>
</svg>
```

**Comment by Andrej730** [comment]
Added some text wrapping and multiline text support.
