### ISSUE TITLE
Possible to not suppress the 0" in the dimension string.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3011]
Possible to not suppress the 0", and have it read `12' - 0"` instead.

![image](https://user-images.githubusercontent.com/507113/232387348-b984a5ad-96c0-4432-986f-08b630568c1d.png)

**Comment by Andrej730** [comment]
Is there cases where there is a need to suppress zero inch values or it's very rare and it's more usual to keep them?

**Comment by Moult** [comment]
Specifically should we make this always show the zero, or make it togglable?

**Comment by theoryshaw** [comment]
> Is there cases where there is a need to suppress zero inch values or it's very rare and it's more usual to keep them?

Yes, other BIM programs have a preference 'toggle' to suppress the 0" valuable.

**Comment by Moult** [comment]
@theoryshaw and what should the default be?

**Comment by theoryshaw** [comment]
i guess i'm wrong, revit has `suppressing trailing 0's` if a decimal, and `suppressing 0 feet`, if it's an inch. 

Nothing for suppression of 0", however. 

![2023-04-17_20-51-32_Format_Revit](https://user-images.githubusercontent.com/507113/232649323-228e2bea-5d08-4e38-af6f-f45d8f0985fc.gif)

So if we provide a toggle, would lean toward a default to exposing the 0". 

could call the toggle `Suppress 0 inches`?

**Comment by Moult** [comment]
Cool. Sounds good :) Go for it @Andrej730 !
