### ISSUE TITLE
Issue with Quantity Sets

### ISSUE THREAD

**Issue by mdjska** [IfcOpenShell/IfcOpenShell#3014]
In the past couple of versions, I get an error every time I try to create a normal quantity set for an object.
```
[...]
return get_cost_assignments_by_type(cost_item, filter_by_type)
  File "/Users/[...]/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/cost.py", line 205, in get_cost_assignments_by_type
    for r in cost_item.Controls or []
AttributeError: 'NoneType' object has no attribute 'Controls'
Location: /Applications/Blender 4.app/Contents/Resources/3.4/scripts/modules/bpy/ops.py:113
```
If I try to add the quantity set a second time and ignore the error, it is technically possible to add the qto value. Seems to happen for all building elements.

**Comment by mdjska** [comment]
Oh sorry, is this a duplicate of https://github.com/IfcOpenShell/IfcOpenShell/issues/2969?

**Comment by Moult** [comment]
Yep, duplicate. Ping @myoualid
