### ISSUE TITLE
bim.activate_drawing_style() doesn't change viewport appearance. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3016]
I might be doing something wrong, but activating the drawing style doesn't change the viewport shading. 

![2023-04-17_14-10-10_Blender_blender](https://user-images.githubusercontent.com/507113/232587344-8329bd7c-a9cb-48c5-85e0-67164371bc2f.gif)

**Comment by Moult** [comment]
You have to switch to rendered mode (little sphere top right of the viewport) potentially. I'll take a closer look, the drawing style system is pretty ancient and hasn't had any upgrades for years perhaps.

**Comment by Andrej730** [comment]
But should it really? We can add switching to rendered shading style in viewport on activating drawing style but this could be expensive, so it's not a good option
