### ISSUE TITLE
Misleading failure reason if pset not found

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#3018]
If a requirement is defined such that property "foo" must exist in pset "bar", and an object does not have the pset "bar", the failure reason given is "The entity has no property sets"

https://github.com/IfcOpenShell/IfcOpenShell/blob/30182684d5918ac32728a9d526f64111cfdcd92f/src/ifctester/ifctester/facet.py#L912-L915

Perhaps "The entity has no property sets or the property set does not exist" is more suitable?

**Comment by Moult** [comment]
Agreed. "The required property set does not exist".? Go for it :)
