### ISSUE TITLE
.IfcSpace doesn't seem to obey 'Exludes'

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3021]
file: https://gitlab.com/openingdesign/clothing_boutique/-/blob/6edf9dc30533e5759ecf5a835e6f2e8f7b9cf33e/Clothing_Boutique.ifc

https://www.dropbox.com/s/ewpa65kb4hxn9ke/2023-04-18_13-57-47_Blender_blender.mp4?dl=0

**Comment by theoryshaw** [comment]
I notice IfcSpaces never show on the svg, regardless if they were in the 'Excludes' or not. 

Was this the plan?

If so, there are use cases for showing the ifcspace in the svg.

**Comment by Moult** [comment]
From memory they should be on the SVG, just "hidden" by the default.css:

```
.IfcSpace { fill: none; stroke: none; }
```

**Comment by Andrej730** [comment]
By default they're excluded from drawing elements since we're using type "IfcElement" to figure list of elements to draw.
You can do something like `.IfcElement | .IfcSpace` in Include to add the spaces too but still need to remove/modify `.IfcSpace { fill: none; stroke: none; }` in default.css

**Comment by Moult** [comment]
I think that's OK, having it not show spaces by default but needing to enable it in the includes. Thoughts @theoryshaw ?

**Comment by theoryshaw** [comment]
I guess i would suscept .ifcspaces to the same exclude/include logic as all other entities--just for consistency. 
Let the user decide how to include/exclude and style.
