### ISSUE TITLE
Possible to center space-tag on space?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3023]
Possible to center space-tag on space?  Currently it's off to the side. 

https://www.dropbox.com/s/lxe5r85bvfocym6/2023-04-18_16-30-59_Blender_blender.mp4?dl=0

**Comment by Andrej730** [comment]
Fixed
<img src="https://i.imgur.com/vOqwy3s.png"/>

**Comment by brunopostle** [comment]
I was taught (back in the drawing board days) to never put the room name exactly in the middle because there is likely some bit of the design that needs to go there - such as a light fitting in the RCP
