### ISSUE TITLE
IFC Object Quantity Set, like `Qto_DoorBaseQuantities`, cannot be added to IfcDoorTypes. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3024]
Noticed IFC Object Quantity Set, like `Qto_DoorBaseQuantities`, cannot be added to IfcDoorTypes. 

It seems allowed by the schema.  https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/Qto_DoorBaseQuantities.htm

Doesn't seem to work before [this](https://github.com/IfcOpenShell/IfcOpenShell/issues/2969) bug, either.

**Comment by Andrej730** [comment]
Well, you can but in [IFC4X3](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/Qto_DoorBaseQuantities.htm)

![image](https://user-images.githubusercontent.com/9417531/232993674-d97897fc-288b-467d-af1f-a9461dfebea8.png)

**Comment by Moult** [comment]
Huh, @aothms can you help confirm this behaviour? Was it really the intention in IFC4 for Qto to be `QTO_OCCURRENCEDRIVEN` only?

**Comment by Moult** [comment]
Bump @aothms

**Comment by Moult** [comment]
Now implemented. Backporting from upstream.
