### ISSUE TITLE
If an imperial file, have .bim.calculate_all_quantities() calculate imperial values

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3025]
If an imperial file, have `bim.calculate_all_quantities()` calculate imperial values

Currently if calculates metric values.

**Comment by Andrej730** [comment]
Might be a bit related thing - if we have millimeters project  `bim.calculate_all_quantities()` calculates all values in meters anyway even though [IfcQuantityLength ](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcQuantityLength.htm) should be in project units if no other unit specified in the quantity.

![image](https://user-images.githubusercontent.com/9417531/233001043-4a40c12c-57ba-48ec-afa9-b4b5216406ea.png)

**Comment by Andrej730** [comment]
Created PR #3032
