### ISSUE TITLE
BCF Topic attributes editor in BlenderBIM

### ISSUE THREAD

**Issue by htlcnn** [IfcOpenShell/IfcOpenShell#3026]
@Moult I should've made an issue here instead of posting in chat 😂 

https://github.com/IfcOpenShell/IfcOpenShell/blob/364138d40818268b2e1bede8412d038e35e2684a/src/blenderbim/blenderbim/bim/module/bcf/ui.py#L80-L99

what's the meaning of these `if` lines? Are they meant for external bcf file created by other software so it already has other topic's information like type, status,...?
Because if I create a BCF from inside BlenderBIM from scratch and create a brand new Topic, there won't be data for those information, so there's no way to turn them on for editing.

**Comment by Andrej730** [comment]
Makes total sense, fixed.
