### ISSUE TITLE
Python 3.6 support?

### ISSUE THREAD

**Issue by lafrech** [IfcOpenShell/IfcOpenShell#303]
Hi.

I noticed there is no Python 3.6 package on http://ifcopenshell.org/python.html.

Is there anything missing to support 3.6?

Are there plans to add 3.6 to the next release?

Thanks.

**Comment by thorade** [comment]
Also see 
https://github.com/IfcOpenShell/IfcOpenShell/issues/227
The current master works on python 3.6 but you have to compile yourself. The instructions are quite good.

**Comment by lafrech** [comment]
Oops, sorry. I searched before asking but missed this one.
