### ISSUE TITLE
BB doesn't seem to remember 'Decoration color' preference. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3033]
BB doesn't seem to remember 'Decoration color' preference. 

video: https://www.dropbox.com/s/ww8njqlaoqrs15j/2023-04-19_07-24-08_Blender_blender.gif?dl=0

**Comment by Gorgious56** [comment]
These settings are stored per-scene, which means they're stored in the .blend file, and they can't be shared across blend files. 

A solution is to change the settings in a blank, new file, and go to *File > Defaults > Save Startup File*  which will setup the settings correctly every time you open a new blend file.

I wonder if it would make more sense to store them in the addon preferences ? (Shared across blend files)

**Comment by Moult** [comment]
Agreed that it's best stored in the add-on preferences, is this something you'd like to tackle @Gorgious56 ?

**Comment by Gorgious56** [comment]
Sorry I didn't respond, I was swamped last week. Cheers
