### ISSUE TITLE
Include sheet number in view-title.svg

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3040]
Include sheet number in view-title.svg, as well

something like 4/A100
`{{drawing_number_identification}}/{{sheet_number_identification}}`

![image](https://user-images.githubusercontent.com/507113/233135736-82ee0097-ebfb-4046-9cbe-cd3149dbeeb4.png)

**Comment by Moult** [comment]
`{{SheetIdentification}}`

**Comment by theoryshaw** [comment]
Is it possible to get the following to work?... `{{Identification}}/{{SheetIdentification}}`
verses. 
`{{Identification}}` `/{{SheetIdentification}}`

reason being, when you search a pdf for `1/A100`, for example it can find the value, verses, `1` `/A100`

**Comment by Moult** [comment]
Sure, just update the SVG template with text which has `{{Identification}}/{{SheetIdentification}}`

**Comment by theoryshaw** [comment]
Cool.  I thought i tried this awhile back, but she seems to work now. 🤷

**Comment by theoryshaw** [comment]
Let's say you want to get 'Status' (or any of the following) to show up on view-title.svg. 

I tried `{{SheetStatus}}`, but no love.   Any pointers? 

![Image](https://github.com/user-attachments/assets/b7296d6c-661c-4f12-aae1-520fd38a94cc)

**Comment by theoryshaw** [comment]
nevermind... that was it. Status was actually `null` not `DRAFT`.
