### ISSUE TITLE
material property set assignment is not working

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3041]
I might be doing something wrong, but it seems material property set assignment is not working. 
![2023-04-19_14-06-27_Blender_blender](https://user-images.githubusercontent.com/507113/233175472-b9055883-a71d-42ba-bf0c-1055ffbc4c10.gif)

**Comment by theoryshaw** [comment]
I thought there was stock ones like ...
https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcMaterial.htm#8.10.3.1.4-Property-sets

**Comment by Moult** [comment]
Those apply to IfcMaterial, not IfcMaterial{Layer,Profile,Constituent}Set.

**Comment by theoryshaw** [comment]
Gotcha. Is there a ui for applying these however?

**Comment by Moult** [comment]
Yes, in the Material tab :)

**Comment by theoryshaw** [comment]
:forehead smack:
