### ISSUE TITLE
Is there a way to bring all the Entities IFC has?

### ISSUE THREAD

**Issue by HelloEnavy** [IfcOpenShell/IfcOpenShell#3042]
I would like to first understand the entities that IFC has and then bring information for each entity.
If I know entity and guid, I can import it, but before that, is there a way to extract what entity IFC has?

**Comment by Moult** [comment]
`ifc_file.wrapped_data.types()` is likely what you're after :)

**Comment by HelloEnavy** [comment]
Thank you for your help :)
