### ISSUE TITLE
[Compilation] Swig not found

### ISSUE THREAD

**Issue by meerfrau** [IfcOpenShell/IfcOpenShell#3043]
I've built the sources til 100 % with [this recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ifcopenshell-git), but then SWIG linking fails:
compiler = gcc 12.2, swig = 4.1.1
```
[  0%] Swig compile IfcPython.i for python
:1: Error: Unable to find 'swig.swg'
:3: Error: Unable to find 'python.swg'
./IfcOpenShell/src/ifcwrap/IfcPython.i:50: Error: Unable to find 'stdint.i'
./IfcOpenShell/src/ifcwrap/IfcPython.i:51: Error: Unable to find 'std_array.i'
./IfcOpenShell/src/ifcwrap/IfcPython.i:52: Error: Unable to find 'std_vector.i'
./IfcOpenShell/src/ifcwrap/IfcPython.i:53: Error: Unable to find 'std_string.i'
./IfcOpenShell/src/ifcwrap/IfcPython.i:54: Error: Unable to find 'exception.i'
```

**Comment by Moult** [comment]
Ping @CyrilWaechter who is the package maintainer for AUR :)

**Comment by CyrilWaechter** [comment]
Hello @meerfrau,

I tried to relaunch the recipe with swig = 4.1.1 and gcc = 12.2.1 and it works.
It looks like your system do not find swig. Can you type following in a console to confirm:
```bash
swig -version
```

If you get no issue please check where swig is installed. In Cmake configuration we say that swig is in standard location in Arch based OS.
```cmake
-DSWIG_EXECUTABLE="/usr/bin/swig"
```
Is swig in there ?

You can type following command to figure out:
```bash
which swig
```

I found someone who got a similar issue [here](https://answers.ros.org/question/36890/unable-to-find-swigswg-and-unable-to-find-pythonswg/) and it was about swig install location.

**Comment by meerfrau** [comment]
I'm on vanilla ArchLinux with my own installed Xfce.

swig is at /usr/bin/swig ; downgrading to 4.0.2 worked for me.

**Comment by CyrilWaechter** [comment]
Another lead would be if you already compiled the package at the same place. Did you already compiled it using this recipe before ? If so have you tried to perform a `makepkg -C` aka `makepkg --cleanbuild` ?

**Comment by CyrilWaechter** [comment]
I got the same error as you in my development directory. Cleaning build folder solved the issue. So it is probably a conflict between previously compiled stuff or previously baked cmake files and new version of swig.

**Comment by CyrilWaechter** [comment]
@meerfrau I close this issue as you gave no news I assume it is solved. Do not hesitate to reopen if necessary.
