### ISSUE TITLE
Is there a way to view the entities that IFC files have in a hierarchical structure?

### ISSUE THREAD

**Issue by HelloEnavy** [IfcOpenShell/IfcOpenShell#3048]
Is there a way to see the entities that IFC files have in a hierarchical structure after extraction?

**Comment by Moult** [comment]
What type of hierarchy are you after? By the way, these aren't really bugs, just questions. Perhaps you can use the Discussions tab or https://community.osarch.org ?

**Comment by HelloEnavy** [comment]
All right. Thank you
