### ISSUE TITLE
IfcConvert IFC4 to XML fails

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#305]
Maybe I misunderstood the reference to IFC4 in the Readme.md (Currently supported IFC releases are IFC2x3 TC1 and IFC4 Add1.),
but the conversion under macOS of an IFC4 file created with ARCHICAD 21 fails with following log entries:

```
IfcConvert "./IFC 2x4 RefView.ifc" "IFC 2x4 RefView.xml"

Log:
[Error] File schema encountered different from expected 'IFC2X3'
[Error] Unable to find find keyword in schema
[Error] Unable to find find keyword in schema
...
```

Here is the file
[IFC 2x4 RefView.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1503388/IFC.2x4.RefView.ifc.zip)

**Comment by kurb70** [comment]
Thak you. I tried it with the following change in build-all.py

```
...
run_cmake("", cmake_args=[
    "-DUSE_IFC=On",
    "-DBOOST_ROOT="              "%s/install/boost-%s" % (DEPS_DIR, BOOST_VERSION),
...
```

but unfortunatly still getting after recompiling

```
Log:
[Error] File schema encountered different from expected 'IFC2X3'
[Error] Unable to find find keyword in schema
...
```

**Comment by Stinkfist0** [comment]
Thomas had a typo, the correct switch is `-DUSE_IFC4=On`, https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L28

**Comment by aothms** [comment]
Yep, thanks, sorry about that.

**Comment by kurb70** [comment]
That was it. Thanks.
