### ISSUE TITLE
Text backgrounds

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3051]
Create background fill for text with an associated class, so you can control opacity/transparency/color, for example. 

possible solution: https://stackoverflow.com/questions/15500894/background-color-of-text-in-svg/16873128#16873128

![image](https://user-images.githubusercontent.com/507113/233781226-3cc44b67-152a-4f56-9018-13974fe34836.png)

**Comment by Moult** [comment]
This is already possible. https://github.com/IfcOpenShell/IfcOpenShell/commit/ffea5320a0738a3d889cdccdbae0c4b9987e1baa

**Comment by theoryshaw** [comment]
![aha_coming_to_america](https://user-images.githubusercontent.com/507113/233787766-7c9b6f13-6531-49b1-a767-ffeb057b1ca3.gif)
