### ISSUE TITLE
update to IfcExtrudedAreaSolid/IfcArbitraryClosedProfileDef is borked on this file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3053]
update to IfcExtrudedAreaSolid/IfcArbitraryClosedProfileDef is borked on following file...

[extrusiontest.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11301355/extrusiontest.ifc.txt)

https://user-images.githubusercontent.com/507113/233785161-78e91eea-2900-4859-a577-e376aa43f350.mp4

**Comment by Moult** [comment]
Meshes can be messy (e.g. non manifold) prior to conversion into an extruded solid, so we weld vertices based on a distance threshold, previously set to 1mm. This is a bit silly and arbitrary, so I made it 0.1mm instead.
