### ISSUE TITLE
Drawing references files have problems between Windows and Linux

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#3055]
If i press the button "create drawing" with a drawing created on windows (and i'm on Linux) i get the following error
![image](https://user-images.githubusercontent.com/79401028/233796441-517243b9-5c2f-49b8-823e-a84973c00633.png)
If i look here:
![image](https://user-images.githubusercontent.com/79401028/233796480-601b2ab7-b7b4-477e-9860-6bcf099e0297.png)
i see that the backslash is stored with windows system.
In fact, if i modify the path manually, i solve the error.

The file is the Clothing Boutique ifc https://gitlab.com/openingdesign/clothing_boutique

**Comment by Moult** [comment]
From what I can tell, there are two approaches: prior to storage, or after storage. Prior to storage means we store all paths using /, not \. After storage means we convert any \ to / on non-Windows.

The benefit of prior to storage is that / generally works on any platform, and \ is a valid character on Linux file paths, so it accommodates more cases.

The benefit of after storage is that it accommodates users typing things in using \ and also maybe other IFC software storing document URIs with those characters.

Right now, I'm going for prior to storage.
