### ISSUE TITLE
New files spatial container

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#3057]
I create a new blender file, i press "Create Project" from "IFC Project" menu and correctly IfcSite/IfcBuilding/IfcBuildingStorey are created.
But, is it correct that if i select the IfcBuildingStorey object it is shown that "The object is not spatially contained" in "IFC Spatial Container Menu"?
![image](https://user-images.githubusercontent.com/79401028/233805184-3ab9c917-1d12-4c2e-9a7f-ff3afaaea1d0.png)
Shouldn't it show the "IfcBuilding" in this case?
Also, the same happens with others spaces from others files so i'm curious to know if it is correct...
Massimo

**Comment by Moult** [comment]
This is correct. The building storey is not "contained in" the building. Instead, it is "aggregated" in the building.

**Comment by maxfb87** [comment]
Thanks for explanation! I thought that, in the past, a building storey was contained in a building but i guess i'm wrong.
Thanks again!
