### ISSUE TITLE
IfcTester request - Report "shall not be" for prohibited facets 

### ISSUE THREAD

**Issue by mdjska** [IfcOpenShell/IfcOpenShell#3059]
A small request; it would be nice if when a facet is prohibited (maxOccurs=0) the reporter printed the facet as "The XX shall not be YY" instead of "The XX shall be YY".

**Comment by Moult** [comment]
Great idea! Would you like to have a go at this?

**Comment by mdjska** [comment]
I tried, but it's a bit of a hack
