### ISSUE TITLE
Copy enumerated property not yet implemented

### ISSUE THREAD

**Issue by Kristoffernegendahl** [IfcOpenShell/IfcOpenShell#3064]
Copying properties to all selected elements is not possible for the selected LifeCyclePhase (set)

![image](https://user-images.githubusercontent.com/3524250/234211309-8ad431e9-2a2f-46ef-9052-c833d7f074d8.png)

**Comment by Kristoffernegendahl** [comment]
Thanks, I see the problem is more complicated than pointing to yet another pset value.

**Comment by Moult** [comment]
That said as a workaround in the meantime you can use the bulk property set/add/remove utility just below that. Be sure to choose enumerated property.

**Comment by Moult** [comment]
Duplicate of #2475.
