### ISSUE TITLE
Crash when trying to delete opening

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3066]
Crash when trying to delete opening
file: https://gitlab.com/openingdesign/clothing_boutique/-/blob/0471cb9040c4f29f36555d7eb0d318a97f5c6890/Clothing_Boutique.ifc

https://user-images.githubusercontent.com/507113/234597283-862b930c-a77b-49e4-8f65-ef31c022aaf1.mp4

**Comment by Moult** [comment]
Apologies, the test cases did catch this one but I was caught up chasing other bugs and other features I didn't handle it :(
