### ISSUE TITLE
bim.generate_space doesn't show up #BlenderBIM add-on

### ISSUE THREAD

**Issue by PavlosDem99** [IfcOpenShell/IfcOpenShell#3071]
Hello guys, does anyone know why bim.generate_space doesn't show up ?
<img width="1893" alt="image" src="https://user-images.githubusercontent.com/95135614/235184774-850aa140-490f-46ff-8467-fdf034935e9a.png">

**Comment by Andrej730** [comment]
are you sure there are no errors in console when you start blender with blenderbim enabled?

![image](https://user-images.githubusercontent.com/9417531/235186542-9e5fac21-e144-4d9d-8c44-aed98a141344.png)

**Comment by PavlosDem99** [comment]
As it seems there are not errors.

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/95135614/235189228-91345189-14b0-415f-a4ef-1b073a21d22b.png">


I am using the latest version 230304

<img width="1910" alt="image" src="https://user-images.githubusercontent.com/95135614/235189067-465d8b54-f880-4942-b2e1-544571b3a05d.png">

THANK YOU

**Comment by Moult** [comment]
@PavlosDem99 does this code exist in `blenderbim/bim/module/model/space.py`?:

```
class GenerateSpace(bpy.types.Operator, tool.Ifc.Operator):
    bl_idname = "bim.generate_space"
    bl_label = "Generate Space"
    bl_options = {"REGISTER"}
```

**Comment by Andrej730** [comment]
@PavlosDem99 I mean the errors in the system console (Window -> Toggle System Console)

**Comment by PavlosDem99** [comment]
> @PavlosDem99 does this code exist in `blenderbim/bim/module/model/space.py`?:
> 
> ```
> class GenerateSpace(bpy.types.Operator, tool.Ifc.Operator):
>     bl_idname = "bim.generate_space"
>     bl_label = "Generate Space"
>     bl_options = {"REGISTER"}
> ```

Yes it exists.
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/95135614/235287663-3b6e8685-b3d1-4382-bc7d-773ebcb2ac5c.png">

**Comment by PavlosDem99** [comment]
> @PavlosDem99 I mean the errors in the system console (Window -> Toggle System Console)


https://user-images.githubusercontent.com/95135614/235287901-dedf23b4-4cee-4a10-a5fa-f2881267dc9e.mp4

**Comment by Andrej730** [comment]
@PavlosDem99 can please you restart blender, create empty project and copy full log from console?

**Comment by PavlosDem99** [comment]
> @PavlosDem99 can please you restart blender, create empty project and copy full log from console?

 Read prefs: C:\Users\pavlo\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
addon_utils.disable: blenderbim not disabled
addon_utils.disable: blenderbim not disabled
Modules Installed (blenderbim) from 'C:\\Users\\pavlo\\Downloads\\blenderbim-230304-py310-win.zip' into 'C:\\Users\\pavlo\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons'
<img width="1829" alt="image" src="https://user-images.githubusercontent.com/95135614/235296676-0d17d95e-adc3-40b1-b2ea-dc8e68330fd8.png">

**Comment by Andrej730** [comment]
@PavlosDem99 I see you switched from Blender 3.4 to Blender 3.5 and reinstalled the addon. Still no "bim.generate_space" operator in f3 menu?
If issue persists - can you do a screenshare to debug it? I'm available on https://app.element.io/#/user/%40andrej730%3Amatrix.org

**Comment by PavlosDem99** [comment]
> @PavlosDem99 I see you switched from Blender 3.4 to Blender 3.5 and reinstalled the addon. Still no "bim.generate_space" operator in f3 menu? If issue persists - can you do a screenshare to debug it? I'm available on https://app.element.io/#/user/%40andrej730%3Amatrix.org

Yes  I installed Blender 3.5 to try to fix it, but still the same. Also I noticed that another functions don;t work properly !
Y

**Comment by PavlosDem99** [comment]
> @PavlosDem99 I see you switched from Blender 3.4 to Blender 3.5 and reinstalled the addon. Still no "bim.generate_space" operator in f3 menu? If issue persists - can you do a screenshare to debug it? I'm available on https://app.element.io/#/user/%40andrej730%3Amatrix.org

Yes,  I installed Blender 3.5 to try to fix it, but still the same. Also, I noticed that another functions don;t work properly !
Yes sure

**Comment by maxfb87** [comment]
@PavlosDem99 could you try with another ifc file? Maybe the problem is with this line

 tool.Model.get_usage_type(subelement) == "LAYER2":

From your screenshare, the log seems to show "LAYER2"...

**Comment by Moult** [comment]
Is this resolved? If not I'll also be happy to offer a screenshare in the Sydney timezone at https://meet.jit.si/openbim if we agree a time.

**Comment by Andrej730** [comment]
Solved. 
Turn out without Developer Extras checkbox in Preferences -> Interface non-default operators are not listed in F3 menu.

![image](https://user-images.githubusercontent.com/9417531/235428879-588ffd66-a007-43cf-8728-3daacfedd12b.png)

**Comment by PavlosDem99** [comment]
> Solved. Turn out without Developer Extras checkbox in Preferences -> Interface non-default operators are not listed in F3 menu.
> 
> ![image](https://user-images.githubusercontent.com/9417531/235428879-588ffd66-a007-43cf-8728-3daacfedd12b.png)

THANK YOU SO MUCH Andrey for your help.
