### ISSUE TITLE
Allow other classes with a IfcMaterialLayerSet to have a horizontal profile, like IfcSlabs. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3079]
For an IfcSlab, for example, the layers and 'edit profile' are horizontal. 

Is it possible to achieve this same functionality for other classes, for example a countertop/shelves/ceilings (IfcFurniture, IfcCovering, i'm sure there are more) could be made up of a IfcMaterialLayerSet with a horizontal profile.

**Comment by Moult** [comment]
Sure, just create that type with a material layer set in the type manager and you're done.

**Comment by theoryshaw** [comment]
I might be missing something.  I could not conjure up the profile...

https://user-images.githubusercontent.com/507113/236246134-e9ba3810-0c37-48eb-8498-8cd40b4f03f3.mp4

**Comment by Moult** [comment]
A Pset is used to indicate the preferred default AXIS. Try using the type manager in the BIM Tool and choose horizontal layers.

**Comment by theoryshaw** [comment]
Nice!  That's a new one for me.

For passerbys...
- https://user-images.githubusercontent.com/507113/236363869-d725d03c-bc97-4478-a6a2-9e6e86fc0063.mp4
- https://user-images.githubusercontent.com/507113/236364369-fb6152d1-8787-4c4f-878b-6954148e83d4.mp4
