### ISSUE TITLE
Bulk regen multiple walls connected to (1) IfcSlab

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3083]
If a IfcSlab has (25) walls, for example, connected to it with 'Shift-E', would it be possible to regen all these walls at once if the ifcslab moves up/down?

by just selecting the roof, and hitting 'Shift-G'.

**Comment by brunoperdigao** [comment]
@theoryshaw Could you please test this implementation?

**Comment by theoryshaw** [comment]
25 walls! :)

https://github.com/user-attachments/assets/ad7c45dd-7f0e-4b5a-9680-6653f15b254f
