### ISSUE TITLE
Blender addon not installable on Fedora 38

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [IfcOpenShell/IfcOpenShell#3085]
Hi IFC community,

I tried to install bimblender addon on Fedora 38 for Blender 3.5.0 (official fedora package) and for Blender 3.5.1 downloaded from official blender website, as I have read that official fedora package is not recommended on Stackoverflow.
Then with blender 3.5.1, I get following stacktrace when trying to enable the addon once installed:

```
Traceback (most recent call last):
  File "/home/estebandugueperoux/Téléchargements/blender-3.5.1-linux-x64/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/estebandugueperoux/.config/blender/3.5/scripts/addons/blenderbim/__init__.py", line 39, in <module>
    import blenderbim.bim
  File "/home/estebandugueperoux/.config/blender/3.5/scripts/addons/blenderbim/bim/__init__.py", line 21, in <module>
    from . import handler, ui, prop, operator, helper
  File "/home/estebandugueperoux/.config/blender/3.5/scripts/addons/blenderbim/bim/handler.py", line 23, in <module>
    import blenderbim.tool as tool
  File "/home/estebandugueperoux/.config/blender/3.5/scripts/addons/blenderbim/tool/__init__.py", line 21, in <module>
    from blenderbim.tool.boundary import Boundary
  File "/home/estebandugueperoux/.config/blender/3.5/scripts/addons/blenderbim/tool/boundary.py", line 23, in <module>
    from blenderbim.bim.module.geometry.helper import Helper
  File "/home/estebandugueperoux/.config/blender/3.5/scripts/addons/blenderbim/bim/module/geometry/__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "/home/estebandugueperoux/.config/blender/3.5/scripts/addons/blenderbim/bim/module/geometry/ui.py", line 22, in <module>
    from blenderbim.bim.helper import prop_with_search
  File "/home/estebandugueperoux/.config/blender/3.5/scripts/addons/blenderbim/bim/helper.py", line 27, in <module>
    from ifcopenshell.util.doc import get_attribute_doc, get_predefined_type_doc, get_property_doc
ModuleNotFoundError: No module named 'ifcopenshell.util.doc'
```

I got this stacktrace either with bimblender from:

- https://blenderbim.org/download.html (https://blenderbim.org/builds/blenderbim-230304-py310-linux.zip)
- https://github.com/IfcOpenShell/IfcOpenShell/releases (https://github.com/IfcOpenShell/IfcOpenShell/releases/download/blenderbim-230501/blenderbim-230501-py310-linux.zip)

Do someone have an idea of the issue?

Regards.

**Comment by Moult** [comment]
What does `ifcopenshell.__file__` show you in the Blender console?

Have you also tried with a vanilla Blender (e.g. rename your `/home/estebandugueperoux/.config/blender/3.5` folder temporarily to start afresh)?

If still broken, let me know a time during the Sydney timezone and let's do a screenshare at https://meet.jit.si/openbim

**Comment by EstebanDugueperoux2** [comment]
Hi @Moult 

`>>> import ifcopenshell
>>> ifcopenshell.__file__
'/home/estebandugueperoux/.local/lib/python3.10/site-packages/ifcopenshell/__init__.py'`

I got same stacktrace from a vanilla Blender.

I'm avalaible tomorrow at 8am (Sydney timezone).

Regards.

**Comment by Moult** [comment]
@EstebanDugueperoux2 righto, so it looks as though you have installed ifcopenshell from somewhere (potentially pip) on your system, and Blender is finding that older version instead of the more up-to-date version shipped with the BlenderBIM Add-on.

If you're not using it on your system, feel free to delete `/home/estebandugueperoux/.local/lib/python3.10/site-packages/ifcopenshell/` and you should be good to go. Otherwise, make sure you have the latest version https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#from-source-with-precompiled-binaries

**Comment by EstebanDugueperoux2** [comment]
Indeed it was that.
Then it is a bug from blender itself, which don't prioritize python libs from addons folder on system libs?

Regards.

**Comment by Moult** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/__init__.py#L37 currently prioritises system libs over add-on libs. Maybe we should prioritise add-on libs by inserting it into sys.path at the beginning, but that could have unintended consequences which I'd love a second opinion on. Ping @aothms @Gorgious56 @brunopostle @Andrej730

**Comment by brunopostle** [comment]
I think it should be safe to prepend the bundled libraries, They are more likely to be up to date. For instance fedora 37/38 provides an older shapely that breaks blenderbim, in this case you want to give the bundled version priority.

**Comment by Andrej730** [comment]
Can't come up with an example from top of my head how it may go wrong
But since we're going to edit `sys.path` it'll affect other addons too - so addons may import some other libs version than they expect and it will be a real fun for them to debug how it happened 😅

**Comment by Moult** [comment]
@Andrej730 well that logic works both ways - if two addons expect two different versions of the same dependency, only one will succeed. https://blenderbim.org/docs/devs/system_support.html#add-on-compatibility

**Comment by Andrej730** [comment]
> well that logic works both ways - if two addons expect two different versions of the same dependency, only one will succeed. https://blenderbim.org/docs/devs/system_support.html#add-on-compatibility
True, other addons argument doesn't hold up here and actually becomes an argument in favor of prepending libs to `sys.path` to make addon a bit more stable in some cases.
I think this not big of a change anyway and can be easily reverted, so it's worth trying.
