### ISSUE TITLE
BlenderBIM - crash when deleting drawing

### ISSUE THREAD

**Issue by mdjska** [IfcOpenShell/IfcOpenShell#3086]
When deleting a drawing Blender crashes imminently and BlenderBIM gets uninstalled during the crash.
version: 230501

https://user-images.githubusercontent.com/16716147/235521173-0f4ef2c7-ceb2-4a76-a3f3-2792245282f5.mov

**Comment by Moult** [comment]
I can't recreate this. Can you help share the IFC?

**Comment by Andrej730** [comment]
Can you please send the error message from console that appears on crash?
On mac to open blender system console you need to start it from terminal with something like `"/Applications/Blender 3.4.app/Contents/MacOS/Blender" -con`

**Comment by mdjska** [comment]
@Moult I can't upload .ifc files here, I can share it on matrix. But it's a very simple file with just some walls and windows from the demo library. I made this file though because with another, more complex file, I can't even print the drawings. Then I get this error:

```
Python: Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 167, in invoke
    return self.execute(context)
  File "/Users/.../Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 212, in execute
    linework_svg = self.generate_linework(context)
  File "/Users/.../Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 325, in generate_linework
    svg_path = self.get_svg_path(cache_type="linework")
  File "/Users/.../Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 966, in get_svg_path
    drawing_path = tool.Drawing.get_document_uri(self.camera_document)
  File "/Users/.../Library/Application Support/Blender/3.4/scripts/addons/blenderbim/tool/drawing.py", line 336, in get_document_uri
    if document.is_a("IfcDocumentInformation"):
AttributeError: 'NoneType' object has no attribute 'is_a'
```

@Andrej730 Message from the console is a whole bunch of these AttributeErrors and then a crash at the end
```
Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/drawing/decoration.py", line 1927, in __call__
    verts, edges = self.decorate(context, obj)
  File "/Users/.../Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/drawing/decoration.py", line 1989, in decorate
    if obj.select_get() or context.scene.camera.select_get():
AttributeError: 'NoneType' object has no attribute 'select_get'
Removing drawings: [#1504=IfcAnnotation('04AlRyJiDAiuym59U8G0mF',$,'MY STOREY PLAN',$,'DRAWING',#1539,#1515)]
Writing: /var/folders/zw/gh9jx44552vf7n_lpbbw0c7h0000gp/T/blender.crash.txt
[1]    44231 segmentation fault  ./Blender
```

**Comment by Moult** [comment]
@mdjska are these by any chance drawings with documents from an older version prior to the recent document upgrade? See https://github.com/IfcOpenShell/IfcOpenShell/issues/2978#issuecomment-1510374693

You can share IFCs here by changing their extension to .ifc.txt or alternatively uploading as a zip.

**Comment by mdjska** [comment]
@Moult  When it comes to the 'more complex' file and issue with "IfcDocumentInformation", it's an older file, but I created drawings in it for the very first time yesterday with the 230501 version.
When it comes to the crash, it's a completely new file and I can recreate it with a newly created file as well.
So yea, those are exactly the same issues as in 2978.

[simple_test_file.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11372991/simple_test_file.ifc.txt)
[more_complex_test_file.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11372994/more_complex_test_file.ifc.txt)

**Comment by Moult** [comment]
@mdjska the simple test file contains no drawings, and I was able to add / remove new drawings without issue on my machine.

The complex one exhibits the issue described in #2978 and so I was able to run the upgrade script, and after that, was able to delete without issues.

Perhaps we can organise a screenshare? If you have a time we can meet at https://meet.jit.si/openbim

**Comment by mdjska** [comment]
Sure, I'm available all day
