### ISSUE TITLE
Is it possible to create a wall by specifying the start and end points, thickness and height?

### ISSUE THREAD

**Issue by Theinformatiker** [IfcOpenShell/IfcOpenShell#3089]
Hello and thank you for your effort for the help.
To my question, I am wondering if it is possible to create a wall with 2 points of thickness and the height as input for the wall.  

Below is an example of how I create a wall by specifying the corner points and a height for the addExtrudedPolyline function. 

```cpp
        typedef std::pair<double, double> XY;

	std::vector<XY> wall_points;
	wall_points.push_back(XY(0, 0));
	wall_points.push_back(XY(250, 0));
	wall_points.push_back(XY(250, 50));
	wall_points.push_back(XY(0, 50));

	IfcSchema::IfcWallStandardCase* wall1 = new IfcSchema::IfcWallStandardCase(
		guid(), 			// GlobalId
		0, 					// OwnerHistory
		("South wall"s), 	// Name
		null, 				// Description
		null, 				// ObjectType
		file.addLocalPlacement(GroundFloor->ObjectPlacement()), 					// ObjectPlacement , 0, 1.0, 0.0, 00.0, 0.0, 00.0, 1.0, 0.0
		file.addExtrudedPolyline(wall_points, 300), 					// Representation
		null				// Tag
#ifdef USE_IFC4
		, IfcSchema::IfcWallTypeEnum::IfcWallType_STANDARD
#endif
	);

```
Here is the visual output in Blender 
![image](https://user-images.githubusercontent.com/70950837/235590893-c71e58d0-124d-408d-992d-230ff8f64817.png)

Another possibility for the representation would be to specify the width, length and height with the addBox function.

I think that the start and end point and the thickness and height for the creation of a wall would be good. Especially if you only have two points, thickness and height.

Thanks for the help and the discusinon

**Comment by Moult** [comment]
If you're OK with using Python, there are high level APIs that do this. https://github.com/IfcOpenShell/wasm-preview/issues/4
