### ISSUE TITLE
ICU download exception

### ISSUE THREAD

**Issue by Xsoiou** [IfcOpenShell/IfcOpenShell#309]
I have  problems when running the build-deps.cmd. At first everything looks good but suddenly i get this error: 

Downloading ICU into D:/IfcOpenShell/deps.
Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
At line:1 char:135
+ ... redentials; $webClient.DownloadFile('http://www.npcglib.org/~stathis/ ...
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
An error occurred

Does anyone know how i can fix this issue?

**Comment by Xsoiou** [comment]
UPDATE: npcglib domain is not down anymore, but the link http://www.npcglib.org/~stathis/downloads/%ICU_ZIP% still throws 403: Forbidden error. 
Temporary fix: get your hands on "icu-58.2-vs2017.7z" file and put it in the deps directory. If this file already exists it will not try to download it again.

**Comment by thorade** [comment]
#310 reports the same error and a solution: Switch from http:// to https://
