### ISSUE TITLE
Roof modifier: rafter edge angle

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3092]
Love the roof modifier. 

To put in the roadmap perhaps. 
To change the angle of the edges. 

![2023-05-02_11-01-00_Blender_blender](https://user-images.githubusercontent.com/507113/235721107-35c8b103-2965-4659-bf91-115cf3aa2d70.png)
![2023-05-02_11-00-38_Blender_blender](https://user-images.githubusercontent.com/507113/235721117-3055b576-a6f9-4cfb-9610-d2cf3356f1dc.png)

**Comment by Moult** [comment]
Can I also add the request to be able to configure the thickness of the roof? :)
