### ISSUE TITLE
Rotate the svg symbol too?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3094]
Related to #2946

Would it be possible to rotate the svg symbol too?

![image](https://user-images.githubusercontent.com/507113/235760967-31015ea5-32fe-4c80-bc52-0c2513b47c28.png)

**Comment by Andrej730** [comment]
What do you mean? It should be rotated already. How do I reproduce it?
![image](https://user-images.githubusercontent.com/9417531/235843300-9b8ca818-cf7c-4b8f-8ddb-74e790f061ae.png)

**Comment by Andrej730** [comment]
Found it! It wasn't working for symbols without text templates.
