### ISSUE TITLE
[Feature Request] Adding a CITATION.cff, so that people know how to cite IfcOpenShell and BlenderBIM etc

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#3095]
I found this function here → https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files and https://citation-file-format.github.io/

This might be interesting

Edit: One more link
Edit2: https://citation-file-format.github.io/cff-initializer-javascript/#/ → With this page you can easily create such a file

**Comment by Moult** [comment]
This sounds fun! I wonder if there would be multiple citations, one for each tool within IfcOpenShell, and/or a single one for the umbrella. @aothms would know, he's worked in academia :)

**Comment by Martin15135215** [comment]
I do not know if it is possible to do several citations. I just saw this function yesterday [in this repo](https://github.com/Zettlr/Zettlr). It's pretty cool because Zotero and Zenodo support it.

![image](https://user-images.githubusercontent.com/110968398/236023358-c4b26894-d1a4-4424-a708-460320ab0760.png)

**Comment by aothms** [comment]
Related: We might want to do a submission for https://github.com/openjournals/joss-reviews for blenderbim. I'll do a longer paper on ifopsh some time in the future. I don't know if @Moult/contributors cares abt these kind of vanity metrics like citations, but a JOSS paper is pretty low effort. For comparison have a look at the TUM OIP submission I reviewed https://github.com/openjournals/joss-reviews/issues/3061

I would indeed say multiple. Does the cff format / github / zenodo support that?

**Comment by Moult** [comment]
More than happy to support!

**Comment by Martin15135215** [comment]
In my short research in the [documentation](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md), I did not find anything, how to do multiple.

Maybe ask in an Issue [here](https://github.com/citation-file-format/citation-file-format/), if that's possible 

There is also a chance that I missed the function how to do mutiple

**Comment by Moult** [comment]
@Martin15135215 it seems we have an answer on how to do multiple: i.e. multiple CFFs files with a main CFF file at the root for IfcOpenShell-Core which then references the subprojects. Would you be interested in helping create this as a PR?

**Comment by kevinmatthes** [comment]
There are numerous tools to maintain and interact with CFF files.  For the setup, the official validation Action might be interesting:  https://github.com/citation-file-format/cffconvert-github-action.

It usually takes about 10 seconds to validate or reject one CFF.  Together with the setup on a hosted runner, the Action should not require more than about 30 seconds to finish, so it is rather lightweight.  For multiple CFFs, you can use a workflow matrix to validate them in parallel.

**Comment by Martin15135215** [comment]
@Moult Sure, I will look into it and create an PR to review it

**Comment by Moult** [comment]
Whoops, I closed the wrong one. @Martin15135215 would you be interested in finishing this one off?

**Comment by Martin15135215** [comment]
Sure. I'll have a look at it at the end of the week.
