### ISSUE TITLE
How do I fix IfcDirection?

### ISSUE THREAD

**Issue by erinleeme** [IfcOpenShell/IfcOpenShell#3097]
IfcPatch can give Ifc a new coordinate value, but how can I modify the RefDirection value, which is the attribute information of IFCAXIS2PLACEMENT3D?

For example, I want IfcLocalPlacement to have the following values.
![image](https://user-images.githubusercontent.com/87467958/235817627-4494a336-11d1-469d-9017-e3402883ab96.png)

`python -m ifcpatch -i 01.ifc -o new_01.ifc -r OffsetObjectPlacements -a 181194.632851008 517941.184846197 0 90`

The IFCCARTESIANPOINT value of IFCAXIS2PLACEMENT3D entity and the IFCDIRECTION entity value of the Axis property are as desired, but not the RefDirection property information.

![image](https://user-images.githubusercontent.com/87467958/235817999-8f624d83-9236-4d0f-a2c8-014b793895c0.png)

Is there any way to do it?
I don't know if I should upload it to OSArch Community, so I upload it here.

**Comment by Moult** [comment]
The OffsetObjectPlacements recipe offers up to 6 parameters to also affect angles in all axes: https://blenderbim.org/docs-python/autoapi/ifcpatch/recipes/OffsetObjectPlacements/index.html

**Comment by l-lnaln** [comment]
I know that and put parameter values in various ways, but it comes out differently from the desired value.

`python -m ifcpatch -i C:\Users\user\Desktop\BIMTOGIS\BIMFile\ifc\new\KIT_Institute_ifc\KIT_Institute\KIT_Institute_Arch.ifc -o C:\Users\user\Downloads\KIT_Institute_Arch.ifc_01.ifc -r OffsetObjectPlacements -a 181194.632851008 517941.184846197 0 -0.00698102814946097 0.999975632326097 0`

**Result** 
![image](https://user-images.githubusercontent.com/87467958/235821184-eaa1f7a1-1adf-4f67-b942-1e5d99c43a17.png)

So I don't know how to put parameter values.

**Comment by Moult** [comment]
It seems like you're entering unitised vectors into the patch. That's not how the patch works. The patch offsets (and rotates) existing placements. So you'll need to enter decimal degrees of the rotations as described in the documentation that I linked to.
