### ISSUE TITLE
AttributeError: entity instance of type "IFC2X3.ifcPolyLoop" has no attribute "Name"

### ISSUE THREAD

**Issue by CedricWiwi** [IfcOpenShell/IfcOpenShell#3099]
![Screenshot (44)](https://user-images.githubusercontent.com/132450468/235891941-55529bfe-ca4a-4b9c-8c78-945d1bdc9c5e.png)

Hello,
I have created some cubes for doors or windows. After that I wanted to give them the right IFC Class (like ifcWindow and ifcDoor) but I get this error. I tried everything but all cubes have the same class and it isn't possible to change it.

I hope you can help me, it´s for my Master Thesis of Engineering
Thanks, Cedric

**Comment by Moult** [comment]
Can you share your IFC model? You can either attach it here renamed as a .txt file or email it to dion@thinkmoult.com if private.

**Comment by Moult** [comment]
Thanks for sending your model. Indeed it seems as though you have most likely been saving your Blender file but not saving the IFC. Saving the Blend file does not save the IFC, so you have likely lost your data :(

I recommend in the future to always use this panel to save your model, then load your IFC afresh in a fresh Blender session.

![2023-05-03-211523_296x220_scrot](https://user-images.githubusercontent.com/88302/235901319-3c81af6b-a35c-4fed-977b-f2141257b938.png)

**Comment by CedricWiwi** [comment]
okay:/
so this is also the reason why all cubes always belongs to the same ifc class?

**Comment by CedricWiwi** [comment]
And so I have to start my model from new?

**Comment by Moult** [comment]
Yes, basically the Blend file is trying to grab data from an IFC dataset which ... has no data. Very unfortunately you probably do need to start from scratch. We really do need to fix this usability problem - many users have fallen into this trap and think that the data is in the .blend and they simply "export" an IFC.

Might I recommend https://blenderbim.org/docs/ ?

**Comment by CedricWiwi** [comment]
Okay, if you want you can recommend it. I will try it again and I hope the error won't come again.

**Comment by Moult** [comment]
Cheers, and please don't hesitate to reach out https://blenderbim.org/docs/users/exploring_an_ifc_model.html#what-else-is-there :)
