### ISSUE TITLE
blenderBIM py310_macosM1 version error 

### ISSUE THREAD

**Issue by tati-** [IfcOpenShell/IfcOpenShell#3100]
I have a M1 mac, and Blender version 3.3.  I am trying to install blenderBIM by using the `blenderbim-230304-py310-macosm1.zip` file, but I get a `ImportError: IfcOpenShell not built for ‘darwin/64bit/python3.10`. 

The `blenderbim-230304-py310-macos.zip` seems to work.

**Comment by Moult** [comment]
Our build scripts grab straight from IfcOpenBot, so that sounds really weird. Possibly I fatfingered during the release and named things wrongly in the last stable. What happens if you download a Github release py310 from here https://github.com/IfcOpenShell/IfcOpenShell/releases ?

**Comment by tati-** [comment]
Thanks, the `230503-py310` version works fine (both the `macos` and the `macosm1,` at least for me)

**Comment by Moult** [comment]
Weird :) Anyway the next release will be out soon, so closing bug.
