### ISSUE TITLE
Command to select aggregate by just selecting just (1) related object.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3101]
Would be nice to have something like `bpy.ops.bim.select_decomposition()`, where you can just select a `related` object, in an aggregate, and it selects all the `related` objects inside the immediate `relating` object. 

Maybe if you keep running the command it selects additional objects, in the next level aggregate up. 

Maybe if there's more than one immediate relating aggregate, it prompts you to select which one.

Does it make sense too, to have the relating object be Blender's active object too. 

Just some brainstorming.

**Comment by Gorgious56** [comment]
Hey would you mind sharing a simple example file where I could brainstorm how to tackle that feature ?

**Comment by theoryshaw** [comment]
Sure, we 'just' started [this](https://gitlab.com/openingdesign/highland_haven/-/blob/ed715b78194e319b79b778b1d30b4a4bd972766f/Models_and_CAD/Highland_Haven.ifc) project.  It's a pocket neighborhood. 

Each house is an aggregate because we're using @brunoperdigao sweet [duplicate assembly](https://github.com/brunoperdigao/IfcOpenShell/commits/duplicate-assembly) (typed aggregates) work, as described [here](https://community.osarch.org/discussion/comment/15490/#Comment_15490). 

Would like to eventually dial into more gradualirty here, that is, having aggregates within aggregates.  Can see doing porch, bathroom, wall panel aggregates, for example, and mix and matching them per individual house. 

![2023-05-22_19-13-38_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d98debc6-a798-41c2-8c8a-8ac2761051c2)

![2023-05-22_19-10-49_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/31bae0f7-6c74-4bb4-bd27-68ba9104ba83)

**Comment by lfertig** [comment]
@Gorgious56, did you start working on the issue? in todays chat it came up that i could tackle this one, just want to prevent doing redundant work..

**Comment by Gorgious56** [comment]
Nope, go ahead :)

**Comment by Moult** [comment]
Agreed that selecting siblings is a very common tasks.

How about Alt-S to select siblings and Alt-P for selecting parent?

**Comment by theoryshaw** [comment]
closed via https://github.com/IfcOpenShell/IfcOpenShell/commit/cdd332d1ee345e2751ff9dc08c62d9cc910b7783

**Comment by theoryshaw** [comment]
addressed via: https://github.com/IfcOpenShell/IfcOpenShell/pull/4437
