### ISSUE TITLE
have values such as `X Angle`, `Height`, `Length`, etc. update per the selected object?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3102]
Possible to have values such as `X Angle`, `Height`, `Length`, etc. update per the selected object?

![2023-05-03_16-43-39_Blender_blender](https://user-images.githubusercontent.com/507113/236057031-b45ba25f-9bb3-4cf4-a5d2-970ddad651a3.gif)

**Comment by theoryshaw** [comment]
In the meantime, how does one query these values currently?

**Comment by Andrej730** [comment]
That's a cool idea, implemented it.

>In the meantime, how does one query these values currently?

Not sure if there is other way but I guess currently you can get them from console:

https://github.com/IfcOpenShell/IfcOpenShell/blob/d0526d0ae551dbd143324fd83ca6bc36183e4d48/src/blenderbim/blenderbim/bim/handler.py#L118-L150
