### ISSUE TITLE
BlenderBim - When attempting to add an ODS schedule on a different hardrive to the project it gives an error

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3106]
When attempting to add an ODS schedule to the project it gives this error:

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 82, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\ifc.py", line 410, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1523, in _execute
    filepath = os.path.relpath(filepath, ifc_path)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\python\lib\ntpath.py", line 744, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'D:', start on mount 'C:'

Moving the ODS file to the same drive as the IFC seems to work

**Comment by Moult** [comment]
Yes, because by default it is referenced via a relative path, but if it's on a separate drive, a "relative path" doesn't exist. Can you try disabling the relative path checkbox when you add a schedule?

**Comment by Plae-Blue-Dot** [comment]
Unchecking relative path allows you to add it to the ifc, makes sense, thanks @Moult I think that's just me being the user error apologies

**Comment by Andrej730** [comment]
Where's this relative path checkbox? 🤔

**Comment by Moult** [comment]
In the file browser settings. Let's keep this issue open since we shouldn't be having these types of scary error messages. We should probably fall back on absolute paths.

**Comment by Plae-Blue-Dot** [comment]
> Where's this relative path checkbox?

After clicking "Add Schedule"
![image](https://user-images.githubusercontent.com/78321676/236123189-93476869-f1e1-47bb-8b98-56065186a500.png)


 In the pop up It can be found here:
![image](https://user-images.githubusercontent.com/78321676/236123078-9f5501a6-9a93-4377-b573-e557b0eccb74.png)

**Comment by Andrej730** [comment]
Oh, forgot about operator's parameters in this popup.
Yeah, there should be some fallback in case if drives do not match, I'll add it.
