### ISSUE TITLE
No module named dateutil

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#3107]
Last release shows this error on installation

![IMG_20230504_082513.jpg](https://user-images.githubusercontent.com/79401028/236126722-bc58d8f5-60c5-4518-986e-57f66349da01.jpg)

**Comment by Moult** [comment]
That's not the BlenderBIM Add-on. That's the BlenderBIM spreadsheet?

**Comment by maxfb87** [comment]
Maybe i updated the wrong picture, btw the problem is solved here, thanks :-)

https://github.com/IfcOpenShell/IfcOpenShell/commit/ad9dbce00352e0cec7bbd5d63d5ebbd2eb999cc0
