### ISSUE TITLE
Import IFC with the last version of blenderBIM (blenderbim-230304-py310-win)

### ISSUE THREAD

**Issue by BernardFerries** [IfcOpenShell/IfcOpenShell#3108]
Hello,

I was able to import an IFC file with Release 3.2.2 of Blender and release 0.0.230107 of BlenderBIM.
![Import successfull](https://user-images.githubusercontent.com/114753534/236135861-ac2b9318-a7ae-45cf-aec8-93801dbfa059.png)

With Release 3.5 of Blender and release 0.0.230304 of BlenderBIM, I got the following python message
![Python message](https://user-images.githubusercontent.com/114753534/236136495-f98a51f6-dd2c-40f0-b149-29e07c416cce.png)

Thanks in advance for your help.
Best regards.
Bernard

**Comment by BernardFerries** [comment]
Python message: 
Python : Traceback (most recent call last):
  File "C:\Users\ferri\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\operator.py", line 534, in execute
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Erreur: Python : Traceback (most recent call last):
  File "C:\Users\ferri\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\project\operator.py", line 592, in execute
    ifc_importer.execute()
  File "C:\Users\ferri\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\import_ifc.py", line 237, in execute
    self.create_styles()
  File "C:\Users\ferri\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\import_ifc.py", line 1502, in create_styles
    self.create_style(style, blender_material)
  File "C:\Users\ferri\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\import_ifc.py", line 1530, in create_style
    self.create_surface_style_rendering(blender_material, surface_style)
  File "C:\Users\ferri\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\import_ifc.py", line 1555, in create_surface_style_rendering
    bsdf = blender_material.node_tree.nodes["Principled BSDF"]
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'
Position : C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py:113

**Comment by BernardFerries** [comment]
https://wsi.li/dl/Rm7k5hDbbQXMQaqZj/

**Comment by Moult** [comment]
Loads fine using the latest unstable release (which will be released as stable tomorrow): https://github.com/IfcOpenShell/IfcOpenShell/releases - can you check? If it still doesn't work for you, can we organise a screenshare at https://meet.jit.si/openbim if you pick a time during the Sydney Australia timezone?

**Comment by BernardFerries** [comment]
I checked with the latest unstable release. 
I get the same error when importing IFC, even with sample.ifc you provide on your website.
It is 9:18 am in France and 5:18 pm in Sydney. I am available. Please propose time schedule.

**Comment by Moult** [comment]
@BernardFerries are you available today by any chance? Feel free to drop in at https://osarch.org/chat and ping me :)

**Comment by GoodLuckIce** [comment]
In the src/blenderbim/blenderbim/bim/import_ifc.py file, replace .nodes["Principled BSDF"] with .nodes.new(type="ShaderNodeBsdfPrincipled") in lines 1516, 1543 and 1582 to fix it

In addition, I also observed that other files also have the wording of nodes["Principled BSDF"]. Please confirm whether there are also problems

**Comment by BernardFerries** [comment]
Thanks for your feed back.
I changed import_ifc.py following your instructions
[import_ifc.py.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11495825/import_ifc.py.txt)
But I have a new error message. 
![Python message2](https://github.com/IfcOpenShell/IfcOpenShell/assets/114753534/df9ae78f-39ef-4012-a14a-be563cff944b)

**Comment by GoodLuckIce** [comment]
You made a mistake, you should carefully check the modification content I provided

**Comment by BernardFerries** [comment]
Sorry. I did the changes and the problem is solved.
Thank you very much.

**Comment by Moult** [comment]
@BernardFerries I'm so sorry this dropped off the radar, is it possible to share your file again?

**Comment by Moult** [comment]
Indeed it was a localisation issue. It's been fixed thanks to @Andrej730 !
