### ISSUE TITLE
IfcColumns don't have `X Angle` exposed in the UI.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3111]
IfcColumns don't have `X Angle` exposed in the UI.

![image](https://user-images.githubusercontent.com/507113/236241167-e7278028-bdb1-4999-94c1-ab12c23843fd.png)

**Comment by Moult** [comment]
Have you tried Alt-E?

**Comment by theoryshaw** [comment]
i gotcha!
