### ISSUE TITLE
BlenderBim - 230507 - Weird error where Blenderbim no longer shows in addons tab

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3114]
As described above Blenderbim-230507 no longer shows in addons tab when attempting to load it
Once you attempt to load version  Blenderbim-230507 you can no longer search for Blenderbim in the addons tabs and you can no longer deactivate or activate it, and it does the same for any other installation of Blenderbim afterwards
 
Windows 10
Blender3.5 and 3.3.6
Blenderbim-230507

It works fine with Blenderbim-230506 as long as you have not attempted to install 230507

If it's not just me this could be a very bad bug

**Comment by Moult** [comment]
Can you test on a vanilla config?

**Comment by Plae-Blue-Dot** [comment]
Sorry @Moult My User error, I had "enabled addons only" checked, this is not an error, I'm too quick to file an issue apologies
