### ISSUE TITLE
Anaconda token expired daily conda builds

### ISSUE THREAD

**Issue by Krande** [IfcOpenShell/IfcOpenShell#3119]
Hey @aothms,

I think our daily build IfcOpenShell anaconda token has expired. Can you check? 

https://github.com/IfcOpenShell/IfcOpenShell/actions/runs/4914949207/jobs/8776865680#step:6:11272

**Comment by aothms** [comment]
Indeed. I've created a new token and updated the secret. I think you also have access? https://anaconda.org/ifcopenshell/settings/access

**Comment by Krande** [comment]
Awesome! 

You're right I just couldn't find the access token page from my mobile :) I found it now though with the link you sent me!

Now the new daily builds should start to roll out tomorrow morning! 

FYI: We have finally managed to split the opencascade `occt` conda package into a `novtk` and `all` variant. That means the next wave of ifcopenshell conda packages will have fewer indirect dependencies :) 

I will also try to find some time to look into ways of speeding up the daily conda build process. I think it might be worthwhile to tinker with ccache in our CMakeLists.txt and our daily github actions ci.

**Comment by aothms** [comment]
> FYI: We have finally managed to split the opencascade occt conda package into a novtk and all variant. That means the next wave of ifcopenshell conda packages will have fewer indirect dependencies :)

Wow that will shave off a couple of 100mbs, it's huge. Excellent news!

There's indeed something off with ccache currently. https://github.com/IfcOpenShell/IfcOpenShell/issues/2855

**Comment by Krande** [comment]
Hey @aothms, it seems that our conda builds on windows are failing. 

From what I've gathered so far it seems the `hdf5` conda package on windows changed their lib name frrom `libhdf5_cpp.lib` to `hdf5_cpp.lib` between versions 

* 1.12.2-nompi_h57737ce_101 
* 1.14.0-nompi_h918d9b7_103

I have tried to re-compile locally using hdf5==1.12.2 and I've also tried to rename the lib files. Both solutions solves the compilation issue. However, after the compilation stage is complete when it comes to linking the targets with IfcConvert I end up with a compilation error seemingly related to boost. Any ideas what might be going on?

```
[2/2] Linking CXX executable IfcConvert.exe
FAILED: IfcConvert.exe 
cmd.exe /C "cd . && C:\Users\Kristoffer\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\231.8770.66\bin\cmake\win\x64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\IfcConvert.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x86\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1435~1.322\bin\Hostx86\x64\link.exe /nologo @CMakeFiles\IfcConvert.rsp  /out:IfcConvert.exe /implib:IfcConvert.lib /pdb:IfcConvert.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console  && cd ."
LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1435~1.322\bin\Hostx86\x64\link.exe /nologo @CMakeFiles\IfcConvert.rsp /out:IfcConvert.exe /implib:IfcConvert.lib /pdb:IfcConvert.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console /MANIFEST /MANIFESTFILE:CMakeFiles\IfcConvert.dir/intermediate.manifest CMakeFiles\IfcConvert.dir/manifest.res" failed (exit code 1120) with the following output:
IfcConvert.cpp.obj : error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > boost::program_options::arg" (?arg@program_options@boost@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)
IfcConvert.cpp.obj : error LNK2001: unresolved external symbol "public: static unsigned int const boost::program_options::options_description::m_default_line_length" (?m_default_line_length@options_description@program_options@boost@@2IB)
IfcConvert.exe : fatal error LNK1120: 2 unresolved externals
ninja: build stopped: subcommand failed.
```

I might have something wrong in my env variables.

```
set MY_PY_VER=311
set CONDA_BUILD=ON

set PREFIX=<my_conda_env_path>
set LIBRARY_PREFIX=%PREFIX%/Library
set CMAKE_PREFIX_PATH=%PREFIX%;%LIBRARY_PREFIX%/include;%LIBRARY_PREFIX%/lib;%LIBRARY_PREFIX%/bin

set COLLADA_SUPPORT=OFF
set HDF5_SUPPORT=ON
set BUILD_IFCPYTHON=ON
set BUILD_IFCGEOM=ON
set BUILD_EXAMPLES=OFF
set BUILD_GEOMSERVER=OFF
set GLTF_SUPPORT=ON
set BUILD_CONVERT=ON
set BUILD_IFCMAX=OFF
set IFCXML_SUPPORT=ON
set Boost_USE_STATIC_LIBS=OFF

set JSON_INCLUDE_DIR=%LIBRARY_PREFIX%/include
set OCC_INCLUDE_DIR=%LIBRARY_PREFIX%/include/opencascade
set GMP_LIBRARY_DIR=%LIBRARY_PREFIX%/lib
set MPFR_LIBRARY_DIR=%LIBRARY_PREFIX%/lib
set HDF5_INCLUDE_DIR=%LIBRARY_PREFIX%/include
set HDF5_LIBRARY_DIR=%LIBRARY_PREFIX%/lib
set Boost_LIBRARYDIR=%LIBRARY_PREFIX%\lib
set Boost_INCLUDEDIR=%LIBRARY_PREFIX%\include

set PYTHON_EXECUTABLE=%PREFIX%/python.exe
set PYTHON_LIBRARY=%PREFIX%/libs/python%MY_PY_VER%.lib
```

**Comment by cvillagrasa** [comment]
Hi! I think this might be related. Is it possible that an older version of IfcOpenShell is getting installed on Linux (default Ubuntu from GH Actions)? Today I'm getting [an error](https://github.com/cvillagrasa/IfcOpenHouse/actions/runs/4939319478/jobs/8829950763) stating that `geometry.add_door_representation` cannot be found, although it exists [since February](https://github.com/IfcOpenShell/IfcOpenShell/commits/v0.7.0/src/ifcopenshell-python/ifcopenshell/api/geometry/add_door_representation.py). These actions were working well until Monday.

I'm using `mamba install -c ifcopenshell ifcopenshell=0.7.0`, if that helps. Thanks in advance!

**Comment by Krande** [comment]
@cvillagrasa That might definitively be related to the `occt` dependency now being split into a `all` and `novtk` variant. It all depends on your existing environment.

First. To check what you have in your existing environment do; `mamba list` and share the list of dependencies you have in your environment. 

Then try creating a new environment using `mamba create -n ifc-dev -c ifcopenshell ifcopenshell` and see if the problem persist?

Let us know how it goes?

**Comment by cvillagrasa** [comment]
Thanks @Krande ! I'm using `conda-incubator/setup-miniconda@v2` with Mambaforge to set up the environment, and I'm not so proficient in GH Actions so as to easily do a `mamba list`, but I've replicated it in my local Ubuntu and indeed, I've found the problem is between these two lines of the workflow file:

```bash
mamba install -c ifcopenshell ifcopenshell=0.7.0
mamba install -c conda-forge 'pythonocc-core>=7.7.0'
```

The latter deprecates ifcopenshell to `py311h7f30834_4` on the conda-forge channel. Is there an easy way that pythonocc-core accepts the ifcopenshell channel version as its dependency?

**Comment by aothms** [comment]
> IfcConvert.exe : fatal error LNK1120: 2 unresolved externals

2 is not a lot, also these two particular ones appear rather specific, could it be that there is a mismatch between the boost includes and the boost libraries, perhaps? Do you have the full cmake output?

**Comment by Krande** [comment]
@aothms! I'll check the cmake logs tomorrow morning and let you know :)

**Comment by Krande** [comment]
@aothms I wasn't completely sure which cmake logs you want so I just included the logs from the cmake project load below. 

Let me know if you want the full logs from my local compilation and I'll send them to your email? Or you can just wait until I manage to run a new github action compilation on my branch that hopefully recreates the issue :)

```
C:\Users\kristoffer\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\231.8770.66\bin\cmake\win\x64\bin\cmake.exe -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_MAKE_PROGRAM=C:/Users/kristoffer/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/231.8770.66/bin/ninja/win/x64/ninja.exe -Wno-dev -G Ninja -S C:\work\code\krande-IfcOpenShell\cmake -B C:\work\code\krande-IfcOpenShell\cmake\cmake-build-relwithdebinfo-visual-studio-ifc-cpp
-- The C compiler identification is MSVC 19.35.32217.1
-- The CXX compiler identification is MSVC 19.35.32217.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BINDIR: bin
-- INCLUDEDIR: include
-- LIBDIR: lib
-- JSON for Modern C++ header file found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE  
-- Found Boost: C:/work/mambaforge/envs/ifc-cpp/Library/include (found version "1.78.0") found components: system program_options regex thread date_time chrono atomic 
-- Boost include files found in C:/work/mambaforge/envs/ifc-cpp/Library/include
-- Boost libraries found in C:/work/mambaforge/envs/ifc-cpp/Library/lib
-- Found LibXml2: C:/work/mambaforge/envs/ifc-cpp/Library/lib/xml2.lib (found version "2.10.4") 
-- Looking for Open CASCADE include files in: C:/work/mambaforge/envs/ifc-cpp/Library/include/opencascade
-- Found Open CASCADE library files in: C:/work/mambaforge/envs/ifc-cpp/Library/lib
-- Required Open Cascade Library files found
-- Packaging hdf5 and zlib for conda distribution
-- Found HDF5: C:/work/mambaforge/envs/ifc-cpp/Library/lib/hdf5_cpp.lib;C:/work/mambaforge/envs/ifc-cpp/Library/lib/hdf5.lib (found version "1.14.0") found components: CXX 
-- Found SWIG: C:/work/mambaforge/envs/ifc-cpp/Library/bin/swig.exe (found version "4.1.1")  
-- Looking for Python library file in: C:/work/mambaforge/envs/ifc-cpp/libs/python311.lib
-- Found PythonLibs: C:/work/mambaforge/envs/ifc-cpp/libs/python311.lib (found version "3.11.3") 
-- PYTHON_DEBUG_LIBRARIES not found, defining SWIG_PYTHON_INTERPRETER_NO_DEBUG workaround for IfcWrap.
-- Found PythonInterp: C:/work/mambaforge/envs/ifc-cpp/python.exe (found version "3.11.3") 
-- Looking for CGAL include files in: /usr/include
-- Use CGAL_INCLUDE_DIR to specify another directory
-- Found Boost: C:/work/mambaforge/envs/ifc-cpp/Library/include (found version "1.78.0")  
-- Boost include files found in C:/work/mambaforge/envs/ifc-cpp/Library/include
-- Configuring done
-- Generating done
-- Build files have been written to: C:/work/code/krande-IfcOpenShell/cmake/cmake-build-relwithdebinfo-visual-studio-ifc-cpp

[Finished]

```

**Comment by Krande** [comment]
Closing this as the original issue was resolved
