### ISSUE TITLE
Clean up redundant/duplicate contexts?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3121]
Is there a way to clean up redundant/duplicate contexts?

file: [Highland_Haven.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11425180/Highland_Haven.ifc.txt)

![image](https://user-images.githubusercontent.com/507113/236934784-2eb92a82-5735-483c-8021-f3dfc53be1ea.png)

**Comment by theoryshaw** [comment]
is it possible to manually delete the contexts? or will that have unintended consequences?

**Comment by Moult** [comment]
How did that happen in the first place?

**Comment by theoryshaw** [comment]
I'm not 100% certain, but I think it might have been when I used the merged (2) files with the MergeProject receipt.

**Comment by Moult** [comment]
Thanks, that's pretty critical to fix it at the source. I'll fix that but also provide you with a little patch to fix your file. I would not recommend manually deleting them. You could create some really nasty invalid situations.
