### ISSUE TITLE
Using ifcconvert convert ifc to obj erros

### ISSUE THREAD

**Issue by RoyRichs** [IfcOpenShell/IfcOpenShell#3122]
I have used bimserver api splitted larger ifc file to small ifc file with json file, when using ifcconver (lasted ed.), convert smaller ifc to obj formate, but only 0kb mlf file was generated, no obj file, same people who knows please give me some advices, thanks.
following are the smaller ifc files.
[ifc files.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11426364/ifc.files.zip)

**Comment by aothms** [comment]
```
$ IfcConvert -yv door5.ifc door5.obj
IfcOpenShell IfcConvert 0.7.0 (OCC 7.5.3)

Log:
[Notice] [2023-05-09 10:50:22] exclude entities IfcOpeningElement IfcSpace
[Error] [2023-05-09 10:50:22] No schema named null
[Error] [2023-05-09 10:50:22] No support for file schema encountered (null)
[Error] [2023-05-09 10:50:22] Unable to parse input file 'door5.ifc'
```

> [Error] [2023-05-09 10:50:22] No support for file schema encountered (null)

And indeed from your file:

> FILE_SCHEMA (('null'));

CC @hlg any ideas on how to help @RoyRichs get better partial outputs from bimserver?

**Comment by RoyRichs** [comment]
@hlg @aothms thanks for reply.
attach files were following:
1807_EP_AR_v18.zip: was the orgion ifc format file
all.zip: was downloaded from bimserver, json format
IFCs.zip: splited ifcs files using bimserver api
SJSONs(1-5).zip: json file of each smaller ifc files when splited the orgion ifc file
OBJs folder: using ifcconvert.exe convert ifc to obj format, when error occured, none obj format file was generated, only 0kb mtl file
[SJSONs1.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11437158/SJSONs1.zip)
[SJSONs2.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11437159/SJSONs2.zip)
[SJSONs3.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11437160/SJSONs3.zip)
[SJSONs4.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11437162/SJSONs4.zip)
[SJSONs5.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11437164/SJSONs5.zip)
[all.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11437165/all.zip)
[1807_EP_AR_v18.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11437166/1807_EP_AR_v18.zip)
[IFCs.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11437167/IFCs.zip)
[OBJs.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11437169/OBJs.zip)

**Comment by hlg** [comment]
> IFCs.zip: splited ifcs files using bimserver api

Can you explain how you did that? How did you access the API? E.g. via BIMvie.ws, via the Console application, via external client? In the latter case, which client and programming language? E.g. Java, Javascript, Python; an org.opensourcebim client or a custom client? Which API calls did you use? Can you perhaps share the code for the splitting or the query you used? Did you generate the splitted IFC files from the JSON in all.zip or from the BIMserver database?

It seems to me, that you used the Javascript client aka [BIMserver Javascript API](https://github.com/opensourceBIM/BIMserver-JavaScript-API), connected to BIMserver, downloaded the whole revision as JSON model and did the splitting in Javascript. If that is true, how did you write the SPF in IFCs.zip? Can you share the code? There is an [attribute in the Javascript model](https://github.com/opensourceBIM/BIMserver-JavaScript-API/blob/74b42a77f264a36952e8b7ffe41af99dd0c0c4ca/model.js#LL5C1-L5C24) that should hold the schema. You may want to use that when writing your SPF, but I am not sure if it is populated in your specific dataflow.

**Comment by RoyRichs** [comment]
@hlg  thanks for reply. Splited largrer ifc file to smaller ifc files (door.ifc for example), then convert smaller ifc files to obj format.
Convert larger ifc file to obj directedly some information were lost, so used bimserver do that progress.
Using Java and python, the following paper was the reference:
https://www.mdpi.com/2220-9964/7/10/393

**Comment by RoyRichs** [comment]
@hlg by the way,  edit the schema manually in the IFC files with a text editor, for example FILE_SCHEMA(('IFC4')); or FILE_SCHEMA(('IFC2X3')) did solve the promble, but some smaller ifc files were not convert to obj format, please see the attach files, thanks a lot.

[IFCs.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11457579/IFCs.zip)

**Comment by RoyRichs** [comment]
@hlg thanks for your reply and your advice, I'll trying, may the promble was the server error.

**Comment by Moult** [comment]
Closing as this does not seem to be a bug in IfcOpenShell.
