### ISSUE TITLE
IFC4X3 not working in the Python API

### ISSUE THREAD

**Issue by cvillagrasa** [IfcOpenShell/IfcOpenShell#3126]
By running the following snippet:

```python
import ifcopenshell.api


def create_simple_IFC(version):
    file = ifcopenshell.api.run('project.create_file', version=version)
    project = ifcopenshell.api.run('root.create_entity', file, ifc_class='IfcProject')
    site = ifcopenshell.api.run('root.create_entity', file, ifc_class='IfcSite')
    ifcopenshell.api.run('aggregate.assign_object', file, product=site, relating_object=project)

    pset_site = ifcopenshell.api.run('pset.add_pset', file, product=site, name='Pset_SiteCommon')
    ifcopenshell.api.run('pset.edit_pset', file, pset=pset_site, properties={'TotalArea': 400.})
    return file


assert create_simple_IFC('IFC4')
assert create_simple_IFC('IFC4X3')
assert create_simple_IFC('IFC4X3_TC1')
assert create_simple_IFC('IFC4X3_ADD1')
```

An error is returned for the last two cases:
```
File "./ifcopenshell/util/pset.py", line 49, in __init__
    path = str(folder_path.joinpath("schema", self.templates_path[schema]))
                                              ~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'IFC4X3_TC1'
```

Moreover, in version='IFC4X3', although this simple example works, we're using deprecated IFC4.3.0.0 rc2, which might not be what intended, and leads to [strange validation issues](https://github.com/IfcOpenShell/IfcOpenShell/issues/2685#issuecomment-1519166560).

I believe that even before TC1 becomes ISO, version='IFC4X3' should default to it. The other alternative may be to change equalities to `str.startswith` within the API... but I believe virtually 100% of people creating an 'IFC4X3' version will be looking for the new infra Schema, and not the particular deprecated version IFC4.3.0.0 rc2.

**Comment by cvillagrasa** [comment]
@Moult it seems that [indeed, 'IFC4X3' identifier will forever refer to 4.3.0.0](https://community.osarch.org/discussion/comment/15886/#Comment_15886), so I guess there are a couple of places around the code base to be updated to 4X3 TC1 and ADD1. At a first glance, I see the following:

https://github.com/IfcOpenShell/IfcOpenShell/blob/d3201809abc5714ff1c56e0f86b9d42c3332a5ca/src/blenderbim/blenderbim/bim/ifc.py#L53
https://github.com/IfcOpenShell/IfcOpenShell/blob/d3201809abc5714ff1c56e0f86b9d42c3332a5ca/src/blenderbim/blenderbim/bim/ifc.py#L73
https://github.com/IfcOpenShell/IfcOpenShell/blob/f6e72ec06fbc1cab3ade3e817bfc30dc23c1c799/src/blenderbim/blenderbim/bim/schema.py#L32
https://github.com/IfcOpenShell/IfcOpenShell/blob/f6e72ec06fbc1cab3ade3e817bfc30dc23c1c799/src/ifcopenshell-python/ifcopenshell/util/pset.py#L42
https://github.com/IfcOpenShell/IfcOpenShell/blob/f6e72ec06fbc1cab3ade3e817bfc30dc23c1c799/src/ifcopenshell-python/ifcopenshell/api/project/create_file.py#L36

Also, I'd advocate to set up some kind of warning when "IFC4X3" is selected, since from now on, no one would really want to use 4.3.0.0.

It doesn't seem like a lengthy fix, but I'm not really familiar with all this version management myself. Maybe just adding 'IFC4X3_TC1' and 'IFC4X3_ADD1' to the previous sequences is not enough by itself, and some more logic is required elsewhere.

**Comment by aothms** [comment]
> Also, I'd advocate to set up some kind of warning when "IFC4X3" is selected, since from now on, no one would really want to use 4.3.0.0.

Or how about this. We maintain a mapping somewhere in ifcopenshell that maps IFC4X3 -> IFC4X3_ADD1, IFC4 -> IFC4. And whenever a schema as a string is passed we first do a lookup to translate the human readable schema name to the technical schema name. But we allow a new param `schema_identifier` in case users want to specify the precise version.

```python
schema_mapping = {'IFC4X3': 'IFC4X3_ADD1'}

    def __init__(self, f=None, schema=None, schema_identifier=None):
        schema_name = schema_mapping.get(schema, schema) if schema is not None else schema_identifier
        ...
```

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/file.py#L194

**Comment by Moult** [comment]
> Explicit is better than implicit.

My $0.02 is simply to accept the fact that in the future 'IFC4X3' will not be used as @berlotti mentions and require people to explicitly do ifcopenshell.file() with whatever the schema identifier ends up being.

I'm happy to update the code to not refer to IFC4 and instead follow IFC4X3_whatever the latest is. (IFC4X3_ADD1?)

**Comment by cvillagrasa** [comment]
Ok! My 2 cents as follows.

I like @aothms proposal in general. Although maybe it's true that in the long term, that two args 'schema' and 'schema_identifier' can cause confusion to some users.

@Moult I don't know if we can cite that part of the Zen of Python when we can't decide on schema identifiers and these two facts happen at the same time:
- A vast majority of users may don't fully grasp the nuances between the various 4x3 addendums and corrigendum versions. They just may be wanting to use "the latest IFC", or "the IFC which now includes infrastructure classes".
- The straightforward way that a non-expert would write 4x3 as a string (namely "IFC4X3"), now is the same as an expert would name a deprecated standard (4.3.0.0).

So I don't think it's realistic to expect every user to become a PhD in corrigendums and know straight away that what they want is "IFC4X3_ADD1" instead of "IFC4X3". And since also "simple is better than complex", if we can't make "IFC4X3" to be the go-to identifier, I'd advocate for placing different expertise levels on different layers of abstraction. Let the common user keep passing easy strings to keep things simple, but allow for some other class in which indeed "explicit is better than implicit":

```python
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional
import warnings
import re

@dataclass
class SchemaIdentifier:
    """Industry Foundation Classes Schema Identifier definition in accordance with
    https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/
    """
    major_release: Optional[int]
    minor_release: Optional[int]
    addendum: Optional[int]
    corrigendum: Optional[int]
    expert_mode: bool = False

    def __post_init__(self):
        if self.main_version == (4, 3) and not (self.addendum or self.corrigendum):
            self.auto_bump_to_latest4x3()

    def auto_bump_to_latest4x3(self):
        if self.expert_mode:
            txt = f'\nBeware that identifier "IFC4X3" corresponds to a deprecated standard (4.3.0.0). '
            txt += f'Use "IFC4X3_TC1" or "IFC4X3_ADD1" instead!'
            warnings.warn(txt, DeprecationWarning, stacklevel=4)
        else:
            self.addendum = 1  # IFC4X3 -> IFC4X3_ADD1

    @property
    def main_version(self) -> tuple[int, int]:
        return self.major_release, self.minor_release or 0 

    def to_string(self) -> str:
        identifier = f'IFC{self.major_release}'
        if self.minor_release:
            identifier += f'X{self.minor_release}'
        addendum_corrigendum = ''
        if self.addendum:
            addendum_corrigendum += f'ADD{self.addendum}'
        if self.corrigendum:
            addendum_corrigendum += f'TC{self.corrigendum}'
        if addendum_corrigendum:
            identifier += f'_{addendum_corrigendum}'
        return identifier

    @staticmethod
    def from_string(version: str) -> SchemaIdentifier:
        allowed_majrels, allowed_minrels, allowed_adds, allowed_corrs = '1-5', '0-4', '0-9', '0-9'
        pattern = f'([iI][fF][cC])?([{allowed_majrels}])[.xX]?([{allowed_minrels}])?'
        pattern += f'[_]?(([aA][dD]{{2}})?([{allowed_adds}])?)[_]?(([tT][cC])?([{allowed_corrs}])?)'
        if match := re.search(pattern, version):
            _, major_release, minor_release, _, _, addendum, _, _, corrigendum = match.groups()
        if not match or not major_release or any(
                [arg and not arg.isnumeric() for arg in (major_release, minor_release, addendum, corrigendum)]):
            raise ValueError(f'"{version}" is not a valid IFC version')
        return SchemaIdentifier(
            major_release=int(major_release),
            minor_release=int(minor_release) if minor_release else None,
            addendum=int(addendum) if addendum else None,
            corrigendum=int(corrigendum) if corrigendum else None
        )
```

A class like that lets arbitrarily construct some `sch = SchemaIdentifier.from_string('IFC4X3')` in the various parts of the code cited in the messages above, and then just check for `sch.main_version in [(2, 3), (4, 0), (4, 3)]`. It would be used within the code base and hidden from the basic usage, and things like the silent bump from 4.3.0.0 to 4.3.1.0 (or 4.3.2.0 in the future) will be conveyed to be handled in that single place.

Then, the `__init__` file function pointed by @aothms could accept either the traditional begginer-friendly schema identifier string, or alternatively a SchemaIdentifier object for advanced use. And note that even for advanced use, I've issued a warning because I don't think that even experts are going to willingly use 4.3.0.0.

A bit overkill? What do you think?

**Comment by aothms** [comment]
Another additional concern is that the behaviour is not consistent. "IFC4" means IFC4 Add2 TC1 because bSI decided at that time to keep the schema identifier constant when updating the schema (for better or worse). "IFC4X3" means IFC4X3 period. I side more with @cvillagrasa on this one that end users / new devs should not be bothered with this and that the library should nudge them in the correct direction where possible. We simply don't want people to be generating IFC4X3 files based on a withdrawn schema.

I think maybe the code thing is a bit overkill, but on the other hand it really makes sense to allow people to specify (4,3,1,0) instead of all this corrigendum nonsense from the 80s. And indeed if you would specify (4,3) you would automatically get (4,3,1,0) assigned. I like that as well. 

I probably would go with a (named?) tuple, so that you can just join them into string. I also think the whole corrigendum naming doesn't need to be too explicit.

```
>>> prefixes = ('IFC', 'X', '_ADD', '_TC')
>>> v = (4,3,0,1)
>>>
>>> ''.join(''.join(map(str, t)) if t[1] else '' for t in zip(prefixes, v))
'IFC4X3_TC1'
```

**Comment by cvillagrasa** [comment]
@aothms totally agree!

Yes, definitely the fact that identifier naming criteria changes along versions may not be the best all-time contribution from bSI. It's a recipee for misunderstandings.

The approach I proposed of stablishing a complex class in one place would attempt to compensate for that fact in that single place and nowhere else, hiding this nuance from the rest of the code base and allowing for arbitrarily complex handling of cases, while also providing a consistent way of querying versions for the rest of the library. On that solution, the IFC4 case would again be handled within the class, deciding on when to issue warnings or silently adapt specific cases (even on the `to_string()` to achieve (4.0.2.1) -> 'IFC4' for instance).

Your minimal solution definitely looks great. Would you keep the current schema string as it is when creating a file, or fully migrate towards tuples?

The only drawback I can think of, is some new user seeing somewhere that the tuple can be of length 4, and specifying (4,3,0,0) without being aware of the issues. What do you think of the warnings for deprecated versions?

**Comment by Moult** [comment]
I see your point, I've changed my mind and I agree - "IFC4X3" always pointing at the "intended" version would be great, and some other parameter that accepts either a version tuple or a specific schema identifier would be great.

Does the version tuple on only work with IFC4X3? Is it even possible to get a "sub-version" of IFC4? Is it even worth it in the future to keep non-ISO versions compiled in? Or just let the user load the express at runtime if they're a poweruser who needs it.

**Comment by aothms** [comment]
> Is it even possible to get a "sub-version" of IFC4?

I think similar to having IFC1.5 IFC1.5.1 to IFC2X to IFC2X2 etc. It's "fun" to have access to them, but there is no practical benefit.

Recently it came to our attention that the latest bSI IFC4 is IFC4.0.2.1 but the ISO version is IFC4.0.2.0 so there was an additional bSI TC that didn't make it to ISO. These changes were very minor, but in 4X3 times things are still (!) somewhat actively changing.

> Is it even worth it in the future to keep non-ISO versions compiled in?

Maybe for reading...

I should also really move forward with loading the schemas through some plug-in architecture, so that downstream users have a choice and WASM builds can be a bit lighter.

**Comment by Moult** [comment]
> It's "fun"

My idea of a Friday night plan.

**Comment by cvillagrasa** [comment]
Also, as an alternative minimal solution in lieu of the complex class, since there aren't that many schema versions, an enum may be used:

```python
from enum import Enum, auto

expert_mode = False

def silent_version_handling():
    return {'IFC4X3': 'IFC4X3_ADD1'}

class IfcSchemas(Enum):
    @staticmethod
    def _generate_next_value_(name: str, start: int, count: int, last_values: list[str]) -> str:
        return svh[name] if expert_mode and name in (svh := silent_version_handling()) else name

    IFC2X3 = auto()
    IFC4 = auto()
    IFC4X3 = auto()
```

That allows to play with the name and value (for instance name could be IFC4 and value IFC4_ADD2_TC1), could be set from string without the need of importing the Enum and could be partnered with some general methods like `ge_ifc_4()` or alike. Just another quick idea.
