### ISSUE TITLE
BlenderBim - Ifc created in BBim 230426 wont open in BBim again although does display in BIMVision

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3127]
As stated above an ifc file created in BBim 230426 wont open in BBim again
Not sure what I did to the ifc but it won't open in BBim

When attempting to open it in BlenderBim again it simply displays a loading cursor and does not load
It opens fine in BIMvision to view it though

https://view.ifcopenshell.org/
gives this error:
Oops
There was an error processing your request with ID:
cekmcrlynOMnERXlWiOIDRLFmXfJNUMf

When attempting to open.
The ifc is a private project, so cannot share it here

**Comment by Moult** [comment]
Is it possible to share it to dion@thinkmoult.com ?

**Comment by Plae-Blue-Dot** [comment]
@Moult I've sent it, thankyou

**Comment by Moult** [comment]
Yeah this is an old bug that allowed users to get invalid / incomplete material usages. It's already been fixed, but unfortunately your project already hit it. The good news is that you can run this code to recover it.

 1. Open your project in advanced mode.
 2. Run this script in the text editor. Change the filepath for the patched model.
 3. Open your patched / recovered model

```python
import ifcopenshell
import ifcopenshell.util.element
import blenderbim.tool as tool
f = tool.Ifc.get()
for rel in f.by_type("IfcRelAssociatesMaterial"):
    mat = rel.RelatingMaterial
    f.remove(rel)
    ifcopenshell.util.element.remove_deep2(f, mat)
f.write('/your/patched/model.ifc')
```
