### ISSUE TITLE
Only IfcWalls take on cut class 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3137]
I'm trying to get the following objects in [this](https://gitlab.com/openingdesign/mineral_point_residence/-/blob/ba45758b7a3b73adcde67b4f31bb95962189f5e9/Mineral_Point_Residence.ifc) file... 

![2023-05-10_23-53-40_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/80b90566-670a-4c80-80f1-7e6ccdd53deb)

...to show up as 'demoed' red. 

But only get the following to print red.  The rest are just projection lines, but they are 'cut'.  Am i missing something?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/2823f492-6f13-4be6-8b69-9de5548eeec1)

these are the drawing settings...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/36f0ad75-457f-4b00-a610-dd9cbf376dca)

**Comment by Andrej730** [comment]
At first I opened Mineral_Point_Residence.ifc not from your link but from the latest gitlab commit and noticed there is no issue. Turn out you reclassified toilet and sink as IfcWall to make it work 😄😄

Issues itself related to aefbc13 where it was limited to IfcWall and IfcSlab @Moult

**Comment by theoryshaw** [comment]
ha.. yep...hacking with the best of them. :)

Would it make sense to add a parameter like `CutClasses` to EPset_Drawing, for those classes that will be cut--to give the user more control on this?  Because I can see it not being a one size fits all approach.

**Comment by Moult** [comment]
@theoryshaw is this now fixed? I don't fully understand this issue - it looks to be a duplicate of #3002.

**Comment by theoryshaw** [comment]
It seems it is. 
Might be some lingering issues.  Not sure they're related. https://github.com/IfcOpenShell/IfcOpenShell/issues/3212
