### ISSUE TITLE
Trying to reassign the ifc type of an IfcOpeningElement throws an error

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3138]
I think those three buttons should be grayed out (disabled) when modifying an object's IfcOpeningElements :

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/3581b2cb-0b3e-4ce0-8944-3818482bb7c1)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/80ca7c2f-a39e-41f4-9114-b5e687336c4d)

The leftmost one is OK since it lets the user select every opening of the base object.
The "Copy Class" button seemingly does nothing but in reality it duplicates the opening element, and hides the base element that was used to duplicate the class, so it is misleading.
The "Unlink Object" button bugs out the interface and keeps drawing the opening element even when the user went out of opening edition. It also does not remove the opening.
The "Reassign Class" button immediately throws an error since IfcOpeningElement is not a of valid Ifc class in the type enum, and I don't think it makes sense to be able to reassign an Opening in this context.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/2ec473ef-de4c-4594-89bc-0deb795a5ae0)

I can work on it if you think it's worth it.

**Comment by theoryshaw** [comment]
I think it's a good idea. 

Why do we even have the copy button anymore... isn't that an old vestage?

**Comment by Gorgious56** [comment]
Hehe Fair point. I think it's supposed to duplicate an element, similar to using SHIFT + D ? However I think a callback is missing since the 3D viewport and outliner don't show the new object. Upon saving the file the copied objects that should be displayed are written to the file and show up on new load.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/api/root/copy_class.py#L26-L66

**Comment by theoryshaw** [comment]
I think it was a vestige from back in the day when you shift+d'ed an object, but it did not create a new GUID.  This button would create a new GUID.

**Comment by Moult** [comment]
Note that there are still some usecases for manual copy class, such as if you are using the Blender separate function, or applying particle instances, dupliverts, which you'd then need to manually "copy class". But this is such a poweruser button that you're right we should remove it from there.

Also sooner or later we'll implement an IFC Separate or equivalent for the things that we've missed.
