### ISSUE TITLE
Property set values are always None for .IfcXml files

### ISSUE THREAD

**Issue by an42rus** [IfcOpenShell/IfcOpenShell#3139]
I've used [these files](https://github.com/IfcOpenShell/files) to check this out.

```
import ifcopenshell
from ifcopenshell.util.element import get_pset


file_names = [
    'ifc/wall-with-opening-and-window.ifcxml',  # FIXME: there is an issue with prop values
    'ifc/WallInstance_IFC4Add2.ifc'
]

for file_name in file_names:
    ifcxml_file = ifcopenshell.open(file_name)
    for wall in ifcxml_file.by_type('IfcWall'):
        print(get_pset(wall, 'Pset_WallCommon'))
```

**Comment by aothms** [comment]
You're right, there was a bug in actually not capturing the parsed value. Regardless of that, my general advise is to not invest effort in ifcxml, it simple hasn't matured to something robust and battle tested in industry.

```
>>> import ifcopenshell
>>> file_name = 'wall-with-opening-and-window.ifcxml'
>>> from ifcopenshell.util.element import get_pset
>>> ifcxml_file = ifcopenshell.open(file_name)
>>> ifcxml_file.by_type('IfcWall')
[#21=IfcWall('3ZYW59sxj8lei475l7EhLU',#2,'Wall for Test Example','Description of Wall',$,#83,#86,$,$)]
>>> wall = _[0]
>>> get_pset(wall, 'Pset_WallCommon')
{'Reference': None, 'AcousticRating': None, 'FireRating': None, 'Combustible': False, 'SurfaceSpreadOfFlame': None, 'ThermalTransmittance': None, 'IsExternal': True, 'ExtendToStructure': False, 'LoadBearing': False, 'Compartmentation': False, 'id': 23}
```

The booleans come through now at least (I think these are the only ones that actually have values in this model). The identifiers still come back as `None` instead of `''`, where I guess the latter is more fateful to the file.

**Comment by an42rus** [comment]
@aothms Great! Thanks a lot.
When you plan the next release with the fix?

**Comment by an42rus** [comment]
It still doesn't work in the new release. (ifcopenshell==0.7.0.230518)
```
>>> import ifcopenshell
>>> file_name = 'wall-with-opening-and-window.ifcxml'
>>> from ifcopenshell.util.element import get_pset
>>> ifcxml_file = ifcopenshell.open(file_name)
>>> ifcxml_file.by_type('IfcWall')
[#21=IfcWall('3ZYW59sxj8lei475l7EhLU',#2,'Wall for Test Example','Description of Wall',$,#83,#86,$,$)]
>>> wall = _[0]
>>> get_pset(wall, 'Pset_WallCommon')
{'Reference': None, 'AcousticRating': None, 'FireRating': None, 'Combustible': None, 'SurfaceSpreadOfFlame': None, 'ThermalTransmittance': None, 'IsExternal': None, 'ExtendToStructure': None, 'LoadBearing': None, 'Compartmentation': None, 'id': 23}
```

**Comment by Moult** [comment]
@an42rus we only occasionally trigger a new build (which is necessary whenever C++ changes). Can you try with this build? https://github.com/IfcOpenBot/IfcOpenShell/commit/8f41ae0c1b865e529a13c275dd2723d70ce4822e#commitcomment-114831076

**Comment by an42rus** [comment]
@Moult Yep, it works! Thanks!
When you plan to release it to pypi?

**Comment by Moult** [comment]
There is an automated PyPI release once a month on the 18th day :) It'll come through next month: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/.github/workflows/ci-ifcopenshell-pypi.yml#L11

Thanks for testing!
