### ISSUE TITLE
Should selecting an IfcElementType from an IfcElement instance deselect the instance ?

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3143]
I wonder whether it's intentional that when selecting an instance of a type, the previously selected instance keeps being selected ? 

I find it unfortunate because I would like to use this feature to quickly duplicate a type in the viewport, but since the instance is still selected using SHIFT + D will also duplicate the instance. 
I'd prefer it to only select the type and make it active, discarding the selection of the instance.

I'm talking about this button

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/b7401ae7-4479-40be-9460-4af5ce69f8b6)

**Comment by theoryshaw** [comment]
agreed.

**Comment by theoryshaw** [comment]
I also think [this](https://github.com/IfcOpenShell/IfcOpenShell/pull/2395#issue-1366785922) would be a good idea too, relative to making the type active and isolating the type geometry quickly.

**Comment by theoryshaw** [comment]
[This](https://github.com/IfcOpenShell/IfcOpenShell/issues/3123#issuecomment-1539293637) is somewhat related too. :)

**Comment by Gorgious56** [comment]
Yup you're right I am noticing quite a few of these, I'll look into it after I have modeled a bit more :) Come to think of it I think "Duplicate Ifc Type" found here
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/ada947bc-106f-49ed-8e0a-aa3305624c90)
would also be good here since it would solve my initial problem
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/b22a3e75-f590-45bc-945c-f0030e2e5b67)

**Comment by Moult** [comment]
Closing as resolved via PR
