### ISSUE TITLE
Fall doesn't remember its angle. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3145]
file: 
[Simple.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11468539/Simple.ifc.txt)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/89ee1952-13ec-4597-8a17-eb436d6376ee

**Comment by Moult** [comment]
I believe the correct solution would be to store the annotation in Model/Annotation/TARGET_VIEW instead of Plan/Annotation/TARGET_VIEW. (i.e. just change the context type from Plan to Model). I suspect no other change is needed.
