### ISSUE TITLE
Error when enabling BlenderBIM (230506) on Blender 3.1.0 macos x64

### ISSUE THREAD

**Issue by Sh-ivvy** [IfcOpenShell/IfcOpenShell#3151]
Stderr: 'Xcode-select: note: no developer tools were found at '/Applications/Xcode.app'. Requesting install 

Installing macos command line tools a pre-requisite for BlenderBIM?

**Comment by Andrej730** [comment]
Can you please check the console output - is there any other errors prior to that?

**Comment by Moult** [comment]
That error surprises me. It shouldn't be relevant. @Sh-ivvy would you be available for a screenshare to debug? If you give a time/day during the Sydney timezone I can meet you at https://meet.jit.si/openbim

**Comment by Sh-ivvy** [comment]
Hi - 
I will try to find a screenshot. Unfortunately I got caught in a family health emergency & I am without access to my notebook. 

Thanks for looking this up. I hope to find some resolution to this issue. 

Sent from Yahoo Mail for iPhone


On Tuesday, May 16, 2023, 8:49 PM, Andrej ***@***.***> wrote:




Can you please check the console output - is there any other errors prior to that?

**Comment by Moult** [comment]
Bump, any updates?

**Comment by Moult** [comment]
I think this has been fixed by @brunopostle in making git an optional dependency.
