### ISSUE TITLE
file.add() raises RuntimeError: Unable to map instance to file

### ISSUE THREAD

**Issue by fedelaport** [IfcOpenShell/IfcOpenShell#3152]
We are having an issue with our splitter. It was working fine for two years with plenty of different files exported from Tekla Structures, but now there is a file that breaks it.

Context: The splitter basically splits an IFC into smaller files. One for each IfcElementAssembly found in the input file.

The breaking file has dozens of assemblies. But only one of them throws the exception when `file.add()`.

We made this example file (with only one assembly):

[RO901.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11472444/RO901.zip)

This reproduces the error:

```python
import ifcopenshell

filename = "tmp/RO901.ifc"

ifc = ifcopenshell.open(filename)
assembly = ifc.by_type("IfcElementAssembly")[0]

new_ifc = ifcopenshell.file(schema='IFC2X3')
new_ifc.add(assembly)
new_ifc.add(assembly.IsDecomposedBy[0])  # Actually this is the line that raises the exception.

new_ifc.write("OUTPUT.ifc")
```

Hope somebody can take a look. It seems like an ifcopenshell issue. Or are we wrong?

**Comment by aothms** [comment]
You can check the file with validate.py and it will tell you it has an invalid enumeration value, this is what causes this exception:

```
$ python3 -m ifcopenshell.validate RO901.ifc
Validating RO901.ifc
For instance:
    #11287=IfcBuildingElementProxy('2cdf8O6Df8kxyL2N05Wu2t',#45,'DUMMY','D25',$,#11286,#11283,'IDa69e9218-18da-48bb-bf15-0970058380b7',.NOTDEFINED.)
                                                                                                                                       ^^^^^^^^^^^^
With attribute:
    <attribute CompositionType?: <enumeration IfcElementCompositionEnum: (COMPLEX, ELEMENT, PARTIAL)>>
Value:
    NOTDEFINED
Not valid
```

If you manually fix this before splitting your file you can solve this fairly easily:

```python
ifc = ifcopenshell.open(filename)

for inst in ifc.by_type('IfcBuildingElementProxy'): # <----------
    inst.CompositionType = None                     # <----------

assembly = ifc.by_type("IfcElementAssembly")[0]

# continue
```

The issue is that the parser is really permissive. But when copying to a new file, we cannot store this invalid enumeration value anymore.

This error message is really uninformative though, or should the value just remain unset (or only for optional attributes which is the case here)?

**Comment by fedelaport** [comment]
Thanks for your clear and fast answer. Very nice to know about validate.py, we were not aware of it 😅.

It's true that the error message is uninformative. IMO it should be possible to simply keep invalid data somehow. That would make ifcos more reliable when it comes to tasks like this. Like our use case, where we don't care because we simply keep client uploaded data.

For now we are going to validate files at upload and skip wrong assemblies.
