### ISSUE TITLE
BlenderBim - Schedule builder incorrect formatting & feature request

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3154]
When loading a schedule into BlenderBim and building it there are two possible issues:

1.) The text alignment formatting only preserves the first block and then does not retain the alignment:

In LibreOffice Calc:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/bfee7c12-f943-44d1-ac74-6ef09104f635)

In Blenderbim:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/3f7615c9-5913-4eef-b34d-4b4493bb21a7)

2.) The region imported into BlenderBim is not defined by the printable region, resulting in additional unwanted cells in BlenderBim:

In LibreOffice Calc:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/9a38d5dd-315b-448e-8015-4a741620e43e)

In Blenderbim:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/f07b4128-cf6d-497c-9ad7-b050af0c2341)

2 possible requests ( I thought I would put them here since they relate to the schedule formatting)

1.) Could the schedule somehow retain Text size & Boldness from the ods file?

2.) Would it be possible to reference an image in the ods file into the schedule in BlenderBim? Like for example a symbol from a legend

**Comment by Plae-Blue-Dot** [comment]
I can do here you go:

[03 - Legend.ods](https://github.com/IfcOpenShell/IfcOpenShell/files/11476219/03.-.Legend.ods)

**Comment by Andrej730** [comment]
1) Working on taking into account print range rn, later can add adjusting for text size and boldness.

2) You mean some symbol from the symbols.svg or image that was somehow embedded in ods?

3) About centered text - not really sure what makes other text like "CONCRETE PAVING" centered in LibreOffice (and in Excel too) because those cells doesn't have "text-align" attribute in ods xml, still need to investigate.
[03.-.Legend - Copy.xml.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11478428/03.-.Legend.-.Copy.xml.txt)

**Comment by Andrej730** [comment]
Figured sometimes cells inherit center alignment from the column styles and well, it got better. 
But now found another weird thing I don't understand - "REFERENCE" cell in Calc and Excel is left aligned even though cells itself doesn't have alignment specified and default alignment for second column is set to center.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/168535be-3e43-4af3-8e6b-afdb32c9b924)

**Comment by Plae-Blue-Dot** [comment]
> Figured sometimes cells inherit center alignment from the column styles and well, it got better. But now found another weird thing I don't understand - "REFERENCE" cell in Calc and Excel is left aligned even though cells itself doesn't have alignment specified and default alignment for second column is set to center. ![image](https://user-images.githubusercontent.com/9417531/238603868-168535be-3e43-4af3-8e6b-afdb32c9b924.png)

Great improvement! And that is very strange, first prize would be for it to only reference the cell style, since the columns change all the time and don't necessarily have the same alignment like reference here

**Comment by Andrej730** [comment]
>Great improvement! And that is very strange, first prize would be for it to only reference the cell style, since the columns change all the time and don't necessarily have the same alignment like reference here

Hmm, actually, you are right!) It was surprisingly easy to fix now

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/e932b637-28e8-4d1e-a0f6-f617acb0a46a)

**Comment by Plae-Blue-Dot** [comment]
Whoop whoop!

> > Great improvement! And that is very strange, first prize would be for it to only reference the cell style, since the columns change all the time and don't necessarily have the same alignment like reference here
> 
> Hmm, actually, you are right!) It was surprisingly easy to fix now
> 
> ![image](https://user-images.githubusercontent.com/9417531/238615354-e932b637-28e8-4d1e-a0f6-f617acb0a46a.png)

**Comment by Plae-Blue-Dot** [comment]
The Schedule builder is looking PHENOMENAL
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/faefa7d6-f496-4cb7-9be3-9465f8149827)

Thank you so much @Andrej730 !

**Comment by Moult** [comment]
@Plae-Blue-Dot hey I'm thinking that we should limit the support for schedule for simple styles: width, height, alignment, colspan, rowspan, and background colours (useful for large summary tables on compliance matrixes) but not much more than that.

For legends, we should either create a dedicated legend object which is intelligent that it knows it's a legend and knows a value that it is annotating semantically in IFC and therefore can generate the list of legend values and auto generate the list of legend colours.

For anything more complex (e.g. fancy hatch patterns, symbolic legends) it's a feature request for the future I believe, or we should also support arbitrary SVG documents to be included on sheets. Something like you can design your "legend block" or "notes block" or "stamp block" (or other similar usecases) as a standalone SVG and then just include it on your sheet.

**Comment by Plae-Blue-Dot** [comment]
Hi @Moult I agree with the above, makes sense, I think allowing for arbitrary svgs is probably what will help the most, 

That way it is allowed in Blenderbim and you can do it even if it is not 100% meeting supported requirements like for the tables. 

At the end of the day it can always be added via Inkscape to the output SVG, so it's not stopping work but that ends up being a large exercise with information that is quite useful inside Blenderbim

**Comment by Moult** [comment]
@Andrej730 is this now resolved?

**Comment by Andrej730** [comment]
@Moult yeah, I think it's resolved now after 0fd94d2
