### ISSUE TITLE
BlenderBim - After adjusting drawing camera ratio "raster x & y " Position on layout no longer relates

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3155]
After adjusting drawing camera ratio "raster x & y " 
in the camera property settings

The sheet layout loses track of the correct position of the drawing and the printed SVG position no longer relates to the layout position in Inkscape. This makes it quite difficult to adjust the drawing position on the sheet

Using BlenderBim 230511

Printed SVG lines up with edge of titleblock:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/967cc77c-66b3-408f-87c7-a50eff25dcfb)

SVG open in Inkscape does not lineup:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/be6292c5-61bb-4645-b9c0-f2e0ecda11bc)

**Comment by Andrej730** [comment]
Can you please help recreate this?

**Comment by Plae-Blue-Dot** [comment]
Ofcourse let me make a quick example Ifc file

**Comment by Plae-Blue-Dot** [comment]
Ok so the problem is: 

1) after adjusting the raster value in the camera:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/47cfa4fc-258e-47e3-a83d-22ae8bfe60dc)
2) The printed sheet SVG has a certain position:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/7ad2d882-e945-447e-adfc-3518e8ca39cc)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/71f7c7f6-3d90-4430-b63c-46ffc0779332)
3) And the 'layout' svg shows a different position in Inkscape:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/9dfd7d40-20d5-40f3-9ac4-8a10d7d93a60)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/bf2e27ca-0e52-4751-9722-2eadcd50a751)

---------------------------------------------------------------
They are no longer aligned as they should be
---------------------------------------------------------------
I've attached 2 zipped example files:

This one works as intended:
[Camera adjustment test V1.rar.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11497447/Camera.adjustment.test.V1.rar.txt)

This one I adjusted the camera y & x ratio and has the problem
[Camera adjustment - broken v2.rar.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11497455/Camera.adjustment.-.broken.v2.rar.txt)

Just remove the .txt and unzip

**Comment by Andrej730** [comment]
Thank you, that was helpful to me.
Made some changes. Can you please test if I got the issue right?
<img src="https://i.imgur.com/uiNWhIq.png"/>

**Comment by Plae-Blue-Dot** [comment]
I'll have a go at it this Evening when I have power again, thanks @Andrej730 !

**Comment by Plae-Blue-Dot** [comment]
Hey @Andrej730 just to check, I need to go to the sheeter.py file found in the drawing module and edit that with your commit to check this update?

I made the changes that way 

And it still seems misaligned in the vertical direction:

model view:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/22cc4762-2738-42e2-8d09-21ee2a3bb4ae)


Inkscape (layout)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/3eda9910-384d-4232-96f1-78b78df34c58)

BlenderBIm (Printed SVG)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/51ca324c-16fb-4f93-896c-f6b7833f6b66)

If I change the raster direction back to 1000 it does fix the position, but I want to be able to adjust this

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/7d6f7ce6-a8aa-4358-86c9-07010ea790d5)

BlenderBim (Printed SVG)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/667702a4-7e62-4cce-b952-f1fee9093350)

**Comment by Plae-Blue-Dot** [comment]
OK After I saved, closed & reopened it seems to be working now!

Model:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/6ee07e0e-7b4b-40f2-8691-029bd6397148)

Inkscape:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/d48ac21b-8639-45fa-b192-a1cb5467fa8c)

BlenderBIm:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/756615ab-eb39-48f7-b31d-409b57350ab8)

**Comment by Andrej730** [comment]
> Hey @Andrej730 just to check, I need to go to the sheeter.py file found in the drawing module and edit that with your commit to check this update?
yeah, just need to make sure restart blender after that

glad it worked!)
