### ISSUE TITLE
BlenderBim - When printing SVG of geometry heavy file it prints the wireframe instead of the cut & solid elevation view

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3158]
Model:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/8ab49bf6-3659-4fd0-80ec-7c20123d3b3e)
SVG:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/d30b960b-f95e-4912-b9b5-edd895616c91)

The model is quite complicated so it is pushing BlenderBim to the limits but I didn't expect to get the wireframe in the SVG

Here is the ifc file:
[structure to ifc test.rar.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11481893/structure.to.ifc.test.rar.txt)
just remove the .txt and then unzip

**Comment by aothms** [comment]
This is an optimization hack. We need something like this in place until we have performance better under control.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/drawing/operator.py#L778-L779

It should look better than this though, because it should take some care to select only the edges that are part of the outline of the shape. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/SvgSerializer.cpp#L1139-L1140

I'll look into this.

**Comment by Plae-Blue-Dot** [comment]
"Maybe try separating the structural components into discrete elements ?"

Great idea!
So I took the file and broke in into individual elements, reclassified it and deleted all but one column the result seems to be better:

SVG:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/89afd3cb-0d75-4132-9929-42a1c6e08ad0)

I duplicated that classified column to get the same section and it looks different:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/f44c34fb-8d55-4010-a6ad-97bf6ae1ca17)
Still not ideal but It does look like it is now showing the triangulated faces instead of the wireframe

Performance is way better this prints in close to 4 seconds on my machine,
Here is the file:
[structure to ifc test - broken up.rar.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11508828/structure.to.ifc.test.-.broken.up.rar.txt)

**Comment by Moult** [comment]
@aothms could an equivalent of an Blender's "Edge Split" modifier be used and then only the edges which are boundaries of faces be drawn? That would be a huge clean up to most meshes.

Would it also help somehow if the user could specify which edges are significant on a mesh?

**Comment by Plae-Blue-Dot** [comment]
Any update on this? The reducing the triangulation especially for terrain & IfcGeographic elements, would be really helpful

**Comment by Moult** [comment]
Bumping this as it's mentioned here by @theoryshaw https://github.com/IfcOpenShell/IfcOpenShell/issues/3312#issuecomment-1628026578

> It should look better than this though, because it should take some care to select only the edges that are part of the outline of the shape. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/SvgSerializer.cpp#L1139-L1140

This should mean that it shouldn't triangulate as much, but I guess it does for some reason?

**Comment by Moult** [comment]
@aothms I just compiled with https://github.com/IfcOpenShell/IfcOpenShell/commit/630bb88a152b5d20e1834b4d06579214a859e096 and setUnifyInputs(True) but unfortunately I don't see any difference between True and False. What am I missing?

![2023-08-09-230743_391x261_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/2c38e879-d04a-4b15-86e3-4b9fd910bda4)

**Comment by Moult** [comment]
@aothms just tested with the latest bot build with the same results (i.e. triangulation), so we can rule out oddities in my local compilation :)

**Comment by theoryshaw** [comment]
I'd like to test this too.  Where do i set setUnifyInputs(True) 
I have the [latest bot build](https://github.com/IfcOpenBot/IfcOpenShell/commit/dcc9d0e9cd0b73820b032e17d4c08e38fa83d9a0#comments):

**Comment by Moult** [comment]
In `module/drawing/operator.py` underneath `self.serialiser.setUsePrefiltering(True)` you can add `self.serialiser.setUnifyInputs(True)`. If you can replicate it that's good and means that it isn't just me, so perhaps @aothms might know.

**Comment by theoryshaw** [comment]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/59717ef2-36e5-453a-9ba4-fc84fdcfa820)

**Comment by aothms** [comment]
Please help me reproduce then using a minimal example.

Because if I just create a triangulated cube in blender

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/89499792-c551-4ac1-9b38-1870ff930db7)

Run

    $ python -m ifcopenshell.draw untitled2.ifc untitled2.svg --drawing-guid 3cdF1soQr2zx4N7nj7NyMC

I get this. With or without this setting actually.

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/359b98da-dc44-4ccc-bd23-41e0c3841bc6)

What am I doing wrong/differently?

[untitled2.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12437532/untitled2.ifc.txt)

**Comment by Plae-Blue-Dot** [comment]
Simplest example I can see is with none flat triangulated geometry, 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/7cfa74d4-516c-44ab-9d6c-88d680d5d5eb)


[triangulated geometry test - Copy.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12437691/triangulated.geometry.test.-.Copy.ifc.txt)
just remove the .txt

**Comment by aothms** [comment]
Ah, what's going on?

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/08fd1edf-f414-4b05-81fa-fa142563e281)

I ran

    $ python -m ifcopenshell.draw pale.ifc pale.svg --drawing-guid 3yWMfo_ZjF686EytrWcAtk

**Comment by aothms** [comment]
D'oh it's the IfcBoundingBox. We really need to unify draw.py and blenderbim to get consistently equivalent output. Thanks @Plae-Blue-Dot

**Comment by aothms** [comment]
Thanks for the help. Managed to fix the setting and started a new build.

**Comment by aothms** [comment]
https://github.com/IfcOpenBot/IfcOpenShell/commit/dadcbe61ea432ffde3c46a943e9cac2476f39e69#commitcomment-125553860

**Comment by Moult** [comment]
Whooo! Hooray it works!

![2023-08-26-220422_375x248_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/1465fbc7-676d-4f63-9463-8a1adb38bc83)

**Comment by Moult** [comment]
I checked the original test file and it seems much better. The remaining triangles are not a fault of unify inputs - it's legitimately that the original mesh is faceted and not coplanar.

![2023-08-26-220901_489x445_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/0b21b4af-b716-4867-ad62-29ff19b69527)

**Comment by theoryshaw** [comment]
![NORTH ELEVATION - TOWARD STEET](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3af35ff7-d698-4482-b8af-fd2b635b20cb)

![giphy](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/e5409185-329f-4191-94e6-f7599ffa365d)

**Comment by Gorgious56** [comment]
This is awesome ! A huge step in native drawing generation :)

**Comment by Andrej730** [comment]
In case if anyone else getting the error below now, make sure to update ifcopenshell from https://github.com/IfcOpenBot/IfcOpenShell/commits/v0.7.0

```
Error: Python: Traceback (most recent call last):
  File "\blenderbim\bim\module\drawing\operator.py", line 212, in invoke
    return self.execute(context)
  File "\blenderbim\bim\module\drawing\operator.py", line 263, in execute
    linework_svg = self.generate_linework(context)
  File "\blenderbim\bim\module\drawing\operator.py", line 488, in generate_linework
    self.setup_serialiser(ifc, target_view)
  File "\blenderbim\bim\module\drawing\operator.py", line 856, in setup_serialiser
    self.serialiser.setUnifyInputs(True)
  File "\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1454, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SvgSerializer, name)
  File "\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'SvgSerializer' object has no attribute 'setUnifyInputs'
```
