### ISSUE TITLE
BlenderBim - 230515 - Text size not working

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3159]
Using a test file with different sizes labeled for each text
model:

When changing the text size:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/8b83e7d0-c2e6-4c57-85ba-546730c48510)

The text sizes do not display the correct size and on re editing with the annotation tool It does not save the size change
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/41311788-b4c4-4b90-a1d2-f2aa21c49864)

or print the correct size

SVG:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/56b595f4-b8be-4b9d-8b39-737816bb04aa)

here is the test IFC:
[Text size test.rar.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11486200/Text.size.test.rar.txt)

Just remove the .txt and unzip the file

The error seems to be apparent in BBim 230506 to 230515

Ok I have narrowed it down, it last worked on BlenderBim 230421
And then stopped working in BlenderBim 230422

One of those commits in that time changed how it works

When opening older text with the newer versions it gives this error:

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 167, in invoke
    return self.execute(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 212, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 489, in generate_linework
    self.move_projection_to_bottom(root)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 898, in move_projection_to_bottom
    projection.getparent().remove(projection)
AttributeError: 'NoneType' object has no attribute 'getparent'

**Comment by Andrej730** [comment]
Solved issues with text resize and preview not showing during edit.
Haven't checked .ifc file yet.

**Comment by Plae-Blue-Dot** [comment]
Thanks @Andrej730 seems to be fixed!

One thing is that the text preview is no longer working:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/e266eac8-6e67-440e-9417-b21b9b4df0d0)

But the SVG and size print correctly!
 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/4db1bce0-6103-4062-8c16-8f614a062a19)

**Comment by Andrej730** [comment]
Fixed now. Checked .ifc file you attached - I think it had the same issue.

**Comment by trhyder** [comment]
Hey @Andrej730, thanks for the work you've done on this one. Unfortunately, there still seems to be a compatibility issue with the text size. When I load `text size test.ifc` on a mac, I can see the text in drawing view (which is great), but all the texts are the same size (2.5). Also, when I print to pdf the text sizes all seem to be 2.5. You can see in the below screenshot that the properties panel has only partially recognised the correct text size.


![Image](https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/b66ef491-a756-4f18-9256-e06a128f858f)

![Image](https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/b9424031-0543-4eb8-9eca-f2b60d48294c)

**Comment by trhyder** [comment]
I can manually reset all the sizes and then it both looks correct and prints correctly.

**Comment by Andrej730** [comment]
@trhyder 
example `text size test.ifc` was bugged - as you can see on your screenshot all text sizes there are 2.5 as they are in this ifc file.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/bf7fcd5c-cb5a-4000-8700-7fa82ef74434)

Is any other issues with changing text size you've met?

**Comment by trhyder** [comment]
The thing that alerted me was my own project, where the size looks different on screen compared to printed view.


![Image](https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/a174c3e9-f83a-423c-9cb1-40a927ac60a8)

**Comment by Andrej730** [comment]
@trhyder it's probably issue we have with different dpi's. I've created issue for tracking the progress - #3353.
Can you please share the project for tests?
