### ISSUE TITLE
BlenderBIM - Feature Request: add reuse ElementStatus in Pset_*Common

### ISSUE THREAD

**Issue by marcuspollio** [IfcOpenShell/IfcOpenShell#3160]
Hi there !

Given the growing interest in the reuse of construction components and materials by multiple actors in the construction sector ([governments](https://environment.ec.europa.eu/topics/waste-and-recycling/construction-and-demolition-waste_en), industries, contractors, architects, engineers and individuals) in order to preserve some of the natural resources, and the almost total absence of integration of reuse and circularity issues in current digital tools such as BIM, it seems relevant to ask the following questions :

- Are the users and developers of IFCOpenShell and BlenderBIM concerned with the issues of reuse and circularity of construction components?

- As this is a broad topic, which platform is preferred to discuss the subject with the community and the best possible integration into our FLOSS tools (OSarch.org, this GitHub ticket, etc.)?

- How fixed or changeable are BuildingSmart standards such as IFC? What weight can be expected to change the standards in a certain direction (e.g. by including circularity issues)?

- What do you think about starting by assigning a "reuse" [ElementStatus property via Pset_*Common](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcproductextension/pset/penum_elementstatus.htm) in the IFC Object Property, either in addition to the existing ones, or instead of "Other"?
In the long run, better to have an open discussion and design plan about the workflow of reuse, but maybe we can begin small like this?

![bim_status](https://github.com/IfcOpenShell/IfcOpenShell/assets/131592747/693dff4c-0421-40ab-b351-22857215606e)

**Comment by Moult** [comment]
> Are the users and developers of IFCOpenShell and BlenderBIM concerned with the issues of reuse and circularity of construction components?

Yes.

The current process I'm aware of for the community to submit an item for consideration to bSI in IFC is here: https://github.com/buildingSMART/IFC4.3.x-development/issues - so if you want to add a `REUSE` flag (which I think is a great idea!) you should post an issue there.

Once you've posted, be sure to follow up regularly, or join any subject matter expert groups around that topic, and be sure to:

 1. Be as specific as possible about your proposal: how to change the schema, and impacts it has on compatibility or vendors. Exactly what the data type is, the description, the name it would have, and example usecases.
 2. Try to gauge a timeline. Is this a small isolated change? Is it a large topic that should be part of a broader set of changes / discussion? Can it be included immediately, within a year, or for IFC5?
 3. Please feel free to try to get things working with FOSS tools like IfcOpenShell (which can process at run-time experimental schemas with changes) and the BlenderBIM Add-on to add some weight and credibility and guarantee the usefulness of it. We'll be able to help where we can.

**Comment by marcuspollio** [comment]
Hi Dion !

Thanks for your answer and the interest ! 
I added an issue on [bSI IFC4.4](https://github.com/buildingSMART/IFC4.4.x-development/issues/28) on the matter. Let's see how it goes.
In the mean time, I will try to set a discussion topic on OSArch.org to further investigate theses issues collectively, what do you think ?

Have a good day, cheers.

**Comment by Moult** [comment]
Looks great! I hope it gets approved and added to IFC! And yes please feel free to start a topic on OSArch, I'm sure you will find more like-minded people!
