### ISSUE TITLE
Can't import ifcopenshell.geom.app

### ISSUE THREAD

**Issue by byildiz** [IfcOpenShell/IfcOpenShell#3167]
Hi everyone,

I can't import the package `ifcopenshell.geom.app` and get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/burakyildiz/.pyenv/versions/ifc/lib/python3.9/site-packages/ifcopenshell/geom/app.py", line 87, in <module>
    from .. import get_supertype
ImportError: cannot import name 'get_supertype' from 'ifcopenshell' (/Users/burakyildiz/.pyenv/versions/ifc/lib/python3.9/site-packages/ifcopenshell/__init__.py)
```

I have a macbook with apple silicon and following setup:
Python version is 3.9.
IfcOpenShell version is 0.7.0.230418.
I installed IfcOpenShell with pip.

I think the problem stems from IfcOpenShell version because when I print IfcOpenShell version I expect `0.7.0.230418` but get `(HEAD detached at 476ab506d)-476ab506d` and it is a weird version. So the following line tries to import `get_supertype` because if check is true. I think `get_supertype` is no more exist in IfcOpenShell version `0.7.0.230418`.
https://github.com/IfcOpenShell/IfcOpenShell/blob/ae9372c3d3c0a1389744403b75719f947cb8f62c/src/ifcopenshell-python/ifcopenshell/geom/app.py#L87

Do you have any idea why IfcOpenShell version is related to git commit hash instead of its actual version?

**Comment by aothms** [comment]
Are you interested in properly reworking this? Should be pretty easy to resolve, you can use the following example to look up the supertype in more recent versions of ifcopenshell:

```
>>> ifcopenshell.ifcopenshell_wrapper.schema_by_name('IFC4').declaration_by_name('IfcWall').supertype().name()
'IfcBuildingElement'
```

> (HEAD detached at 476ab506d)-476ab506d

That is indeed a weird version. How did you install ifcopenshell?

**Comment by byildiz** [comment]
Hi @aothms,

I am trying to use the app (https://blenderbim.org/docs-python/autoapi/ifcopenshell/geom/app/index.html#module-ifcopenshell.geom.app) module. I installed the ifcopenshell using pip (https://files.pythonhosted.org/packages/6e/c4/0379ecfdb6a673ea2d4e5c13b07fd1386fcfcebac9047de4f49c61961a3c/ifcopenshell-0.7.0.230518-py39-none-macosx_11_0_arm64.whl) in python 3.9.7. I also tried the pre-build package (https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-v0.7.0-476ab50-macosm164.zip) and it also has the same weird version. Then I tried to compile ifcopenshell from scratch and this time the version gives 0.7.0.

Below is a concrete example. I downloaded pip whl file (https://files.pythonhosted.org/packages/6e/c4/0379ecfdb6a673ea2d4e5c13b07fd1386fcfcebac9047de4f49c61961a3c/ifcopenshell-0.7.0.230518-py39-none-macosx_11_0_arm64.whl) and extracted it and here is how I get the weird version:
```
ifcopenshell-0.7.0.230518-py39-none-macosx_11_0_arm64 $ python
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:24:02)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> ifcopenshell.version
'(HEAD detached at 476ab506d)-476ab506d'
>>> ifcopenshell.ifcopenshell_wrapper.version()
'(HEAD detached at 476ab506d)-476ab506d'
```

I am curious about whether the version problem is only on apple silicon arch or not and I think the problem probably relies on how the pre-build and the pip package because when I build on my laptop the version is normal.

**Comment by Moult** [comment]
I don't have a Mac but I tested with the latest PyPI release for Linux:

```
$ wget https://files.pythonhosted.org/packages/1f/cb/16e9e38f67a7cdc061ec44f7fdcb25956cc105a6ff3e4c716b5d1441bd36/ifcopenshell-0.7.0.230523-py311-none-manylinux1_x86_64.whl
$ unzip ifcopenshell-0.7.0.230523-py311-none-manylinux1_x86_64.whl
$ python
Python 3.11.3 (main, May 11 2023, 12:45:30) [GCC 12.2.1 20230428] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> ifcopenshell.__file__
'/home/dion/tmp/ios/ifcopenshell/__init__.py'
>>> ifcopenshell.version
'v0.7.0-476ab506d'
```

So the version string looks good here. Can you test with similar code on Mac with the latest from PyPI? I see you have conda-forge, so please check with `ifcopenshell.__file__` to guarantee that it's picking up the correct ifcopenshell installation (and not an ifcopenshell from conda instead, for example).

Also, if you're interested in a more maintained graphical interface to IfcOpenShell you might want to install the BlenderBIM Add-on: https://blenderbim.org/

**Comment by byildiz** [comment]
Hi @Moult,
I tested it with the latest pypi release:
```
$ wget https://files.pythonhosted.org/packages/a4/ff/026e84d4ed525d3e04bb9e3e8591b6d2b5301412fff3d174cd9d4e536642/ifcopenshell-0.7.0.230523-py311-none-macosx_11_0_arm64.whl
$ unzip ifcopenshell-0.7.0.230523-py311-none-macosx_11_0_arm64.whl
$ python
Python 3.11.3 (main, May 11 2023, 15:04:50) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> ifcopenshell.__file__
'/Users/burakyildiz/Desktop/ifcopenshell/__init__.py'
>>> ifcopenshell.version
'(HEAD detached at 476ab506d)-476ab506d'
```
The result is the same and I get the same weird version string.

The issue is now unrelated with the title of this issue anymore. It is the version string issue which may cause other issues such as importing `ifcopenshell.geom.app` module because code checks ifcopenshell version.

**Comment by byildiz** [comment]
I think I found the source of the issue. I tracked back to where version comes from when we call `ifcopenshell.version`:

https://github.com/IfcOpenShell/IfcOpenShell/blob/6f39648077090a365f8e0060b1763b69edf2f477/src/ifcwrap/IfcParseWrapper.i#L591

https://github.com/IfcOpenShell/IfcOpenShell/blob/6f39648077090a365f8e0060b1763b69edf2f477/src/ifcparse/IfcParse.h#L33

https://github.com/IfcOpenShell/IfcOpenShell/blob/6f39648077090a365f8e0060b1763b69edf2f477/cmake/CMakeLists.txt#L919

`IFCOPENSHELL_BRANCH` and `IFCOPENSHELL_COMMIT` are defined if `ADD_COMMIT_SHA` option is `On`:

https://github.com/IfcOpenShell/IfcOpenShell/blob/6f39648077090a365f8e0060b1763b69edf2f477/cmake/CMakeLists.txt#L65

If CI uses build-all.py, `ADD_COMMIT_SHA` may become `On` here:

https://github.com/IfcOpenShell/IfcOpenShell/blob/6f39648077090a365f8e0060b1763b69edf2f477/nix/build-all.py#L765

which is conditioned on `ADD_COMMIT_SHA` environment variable:

https://github.com/IfcOpenShell/IfcOpenShell/blob/6f39648077090a365f8e0060b1763b69edf2f477/nix/build-all.py#L77

I am not sure at which step something goes wrong but `ADD_COMMIT_SHA` option becomes `On` while building for mac os in CI. I also looked into github actions files but I couldn't find which one runs build operation for mac os. Maybe you know that?

**Comment by Moult** [comment]
Well `ADD_COMMIT_SHA` should be on, the question is why the branch is not v0.7.0 but instead something like HEAD detached on Mac.

**Comment by byildiz** [comment]
Good question. I assumed branch is not correct but here is related output of `cmake` with `-DADD_COMMIT_SHA=ON` on my mac:

```
-- Found Git: /usr/bin/git (found version "2.39.2 (Apple Git-143)")
git found: /usr/bin/git with version 2.39.2 (Apple Git-143)
-- IfcOpenShell branch: "v0.7.0"
-- IfcOpenShell commit: "6f3964807"
```
So apparently it is correct.

**Comment by byildiz** [comment]
Can it be because of  git version? Maybe because of following line, `(HEAD detached at HASH)` also doesn't match:

https://github.com/IfcOpenShell/IfcOpenShell/blob/6f39648077090a365f8e0060b1763b69edf2f477/cmake/CMakeLists.txt#L908

**Comment by aothms** [comment]
I think the problem is here:

https://github.com/IfcOpenShell/IfcOpenBot/blob/master/nix.sh#L124-L125

We fetch and checkout, but this does not update the tip of the local branch, so when we invoke `git branch --contains` (for some versions of git....??) it will only print 

```
% git branch --contains HEAD
* (HEAD detached at 8f41ae0c1)
```

instead of 

```
>git branch --contains HEAD
* (HEAD detached at 8f41ae0c1)
  v0.7.0
```

what it prints on my windows for me just now.

I think what we need to do is use:

```
% git branch -a --contains HEAD
* (HEAD detached at 8f41ae0c1)
  remotes/origin/v0.7.0
```

And then strip the parts before the `/`.

@byildiz since you already went as far as debugging this are you interested in writing this fix?
