### ISSUE TITLE
BlenderBim - assigning material to custom IfcObject, freezes and crashes Blender

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3169]
This is the process:

1.) Create a new ifc project
2.) add a wall
3.) rename material to 'brick
4.) Print SVG
and we get the brick material printed:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/93be5af8-5e2b-481d-9ec4-dc30a4dff9cf)

The issue is:

1.) Add a blender cube
2.) Classify it as an IfcObject
3.) assign a 'brick' material
4.) Print SVG
and blender freezes and eventually crashes

This was working not to long ago, just going to check which version

it worked last in BlenderBim 230429:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/4b306ff1-ba2a-4b70-a695-1bfa2291c1c3)

And stopped working in BlenderBim 230430:

Edit: it still displays in 230430 but just doesn't show the material:
model:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/cccbe5b6-e9fc-4d5d-99a7-74d7bb8bbe8e)

SVG:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/79b5c4d5-24d8-450b-bd29-49865014970a)

**Comment by Andrej730** [comment]
Couldn't reproduce freeze or crash on Blender 3.5, Windows 11 :\ Can you please send project with crash? Maybe I'm missing something.

What Ifc class you were using? The part where it stopped working for other objects besides walls and slabs was introduced here - aefbc134e @Moult

**Comment by Plae-Blue-Dot** [comment]
I've tested it out and it only crashes in a specific case
1.) Create Cube
2.) Classify as an Ifc wall, print to svg no problem:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/4123a3d2-9bf2-4e56-bf2a-2d81001f1787)
3.) Add a MaterialLayerSetUsage
4.) print to SVG no problem:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/9318c1f0-44a8-4398-b948-d27030e62570)
5) create a IfcMaterial called brick
6) label the MaterialLayerSetUsage to 'brick'
7.) Print to SVG:
And it starts to freeze:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/9902a31b-762f-4e2d-a198-892ee50541a1)
And eventually ask if you want to restart the program, it hasn't actually crashed/closed on it's own

Ok for this for other test I was using IfcBuildingElement Proxy
"What Ifc class you were using? The part where it stopped working for other objects besides walls and slabs was introduced here - https://github.com/IfcOpenShell/IfcOpenShell/commit/aefbc134eaea051e23f54121961a2cdb8a7c9c0b @Moult"

Thanks for the understanding, it's quite useful to be able to give mass's and proxies materials, was this changed because it doesn't align with the IfcSchema?

**Comment by Plae-Blue-Dot** [comment]
Here is the file:
But it also doesn't seem to want to load at all after I labeled the brick material:
[Red material test.rar.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11507519/Red.material.test.rar.txt)

**Comment by Andrej730** [comment]
>Thanks for the understanding, it's quite useful to be able to give mass's and proxies materials, was this changed because it doesn't align with the IfcSchema?

Not sure, need to wait for Dion.

>But it also doesn't seem to want to load at all after I labeled the brick material

Doesn't open for me too but I've found that for me it freezes even on step 3 when I added MaterialLayerSetUsage. If I save the file after adding MaterialLayerSetUsage and will try to reopen it (without .blend, just .ifc) it will freeze.

On drawing creation it freezes at:
https://github.com/IfcOpenShell/IfcOpenShell/blob/c69ead48933f957815ef9c32a39455d5dbd91a0a/src/blenderbim/blenderbim/bim/module/drawing/operator.py#L797
called from
https://github.com/IfcOpenShell/IfcOpenShell/blob/c69ead48933f957815ef9c32a39455d5dbd91a0a/src/blenderbim/blenderbim/bim/module/drawing/operator.py#L459

processing cube in Model/Body/MODEL_VIEW context.

---------------------------------


I've managed to reproduce this freeze outside blender. 
@aothms can you please take a look - what can cause the freeze on `it.initialize()` with the attached file and the snippet below? Object that's processed is just a cube with assigned IfcWall class and added MaterialLayerSetUsage
[sample_test_file.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11508065/sample_test_file.ifc.txt)

```python
import ifcopenshell
import ifcopenshell.geom
import multiprocessing

ifc = ifcopenshell.open(r"sample_test_file.ifc")
geom_settings = ifcopenshell.geom.settings(
    DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True, INCLUDE_CURVES=True
)
body_context = (14,15)
geom_settings.set_context_ids(body_context)
elements = [1067, 1095]
elements = [ifc.by_id(e) for e in elements]

it = ifcopenshell.geom.iterator(
    geom_settings, ifc, multiprocessing.cpu_count(), include=elements
)
it.initialize()
```

**Comment by Andrej730** [comment]
@Plae-Blue-Dot on the step "create a IfcMaterial called brick" you've added it as a layer to IfcMaterialLayerSetUsage or just created a material?
I think I've found the problem - if you have IfcMaterialLayerSet without layers it causes freeze.

So the current problems seems to be:
- UX problem: easy to add IfcMaterialLayerSet without layers that's not valid in IFC and can cause freeze problem with geom iterator
- UX problem: creating Material in Materials section intuitively seems to be like creating Material related to the current object but it's not
- geom iterator freezes with IfcMaterialLayerSet without layers (not sure if there's need for fallback but it probably shouldn't freeze)

**Comment by Plae-Blue-Dot** [comment]
"on the step "create a IfcMaterial called brick" you've added it as a layer to IfcMaterialLayerSetUsage or just created a material?"

Hey @Andrej730 yes if it is just an Ifcmaterial it doesn't crash
