### ISSUE TITLE
conda packages for IfcOpenShell

### ISSUE THREAD

**Issue by tpaviot** [IfcOpenShell/IfcOpenShell#318]
Any plan for official conda packages available from the anaconda.org cloud ?

**Comment by aothms** [comment]
Actually also something I hope to (finally) do within a couple of days. Stay tuned.

**Comment by aothms** [comment]
The recipe is there:

https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/conda

Tomorrow I'll have a go at publishing them

**Comment by tpaviot** [comment]
I see that oce 0.172 is required, whereas the latest available version is 0.18.2. Is it related to https://github.com/tpaviot/oce/pull/685 ?

**Comment by aothms** [comment]
Yes, kind of, but that specific problem I encountered is only applicable to the iges conversion within IfcConvert, so it would not necessarily have to impact the python module.

But expect these things to change anyway, I'm still in the process of discovering what works and not.

**Comment by tpaviot** [comment]
ok I'll check your conda package and report here the result. I did not have time yet to review your oce PR, I'll try to get id done by the end of this week.

**Comment by aothms** [comment]
> I did not have time yet to review your oce PR

Well, keep in mind that it's probably not suitable to be merged, just to open the discussion for me to better understand which headers are in `inc/` and why.

> ok I'll check your conda package and report here the result

Great, thanks!

**Comment by tpaviot** [comment]
I tried to run conda-build over your recipe (Ubuntu machine), but I get strange issues. Before I try fixing them, did you successfully build the package using this recipe ?

**Comment by aothms** [comment]
I just tried on a completely fresh Ubuntu 1604 and the following steps worked for me.

~~~
sudo apt-get update && sudo apt-get install build-essential
wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
chmod +x Anaconda3-5.0.1-Linux-x86_64.sh
./Anaconda3-5.0.1-Linux-x86_64.sh
git clone https://github.com/IfcOpenShell/IfcOpenShell
cd IfcOpenShell
git checkout v0.6.0
cd conda/
~/anaconda3/bin/conda install conda-build
~/anaconda3/bin/conda-build . -c oce -c dlr-sc
~~~

Thanks for checking. What issues are you getting? Conda-build is still a bit new to me.

**Comment by aothms** [comment]
@tpaviot @rainman110 I am running into issues now regarding prefix length, see https://github.com/conda/conda-build/issues/2640

Are you not running into these when building pythonocc?

PS @rainman110 thanks for publishing your tigl conda recipies they have been really helpful.

**Comment by tpaviot** [comment]
no, no issue regarding prefix length. Did you recently update the package ? can I make another try ?

**Comment by aothms** [comment]
Sorry for the late reply. Yes I made changes to the conda recipe and build scripts.

**Comment by tpaviot** [comment]
which conda-build version do you run ? Whether it is on conda-build 2 or 3 the meta.yaml file seems malformed:
```
/IfcOpenShell/conda$ conda build .
Error: bad character '=' in package name dependency 'oce==0.17.2'
```

A space is required before ==

**Comment by aothms** [comment]
I assume, the latest (or close to that). Ok, I've quickly added spaces. Thanks for letting me know.

**Comment by tpaviot** [comment]
The same for >= for swig version.

``` conda info -a ``` for a information regarding your conda installation.

**Comment by aothms** [comment]
> The same for >= for swig version.

Yes I did that.

> conda info -a 

Unfortunately I cannot SSH into the machine I use to build now

**Comment by johannesmichael** [comment]
Hi all
I tried to install ifcopenshell with conda (terminal and navigator) and received the following message:

PackagesNotFoundError: The following packages are not available from current channels:

  - ifcopenshell
  - oce==0.17.3

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/ifcopenshell/linux-64
  - https://conda.anaconda.org/ifcopenshell/noarch

Any ideas what I am doing wrong?

Thanks Johannes
----------
conda info

     active environment : ifcenv
    active env location : /home/johannes/anaconda3/envs/ifcenv
            shell level : 1
       user config file : /home/johannes/.condarc
 populated config files : /home/johannes/.condarc
          conda version : 4.5.0
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /home/johannes/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/ifcopenshell/linux-64
                          https://conda.anaconda.org/ifcopenshell/noarch
          package cache : /home/johannes/anaconda3/pkgs
                          /home/johannes/.conda/pkgs
       envs directories : /home/johannes/anaconda3/envs
                          /home/johannes/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Linux/4.10.0-38-generic linuxmint/18.3 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by thorade** [comment]
You can try to add more channels, temporarily or permanently.

You will need all channels that are also needed for pythonocc-core, see e.g. their readme:
https://github.com/tpaviot/pythonocc-core#downloadinstall-binaries
or this issue:
https://github.com/tpaviot/pythonocc-core/issues/517#issuecomment-374917088

Or you install the dependencies (here: oce) manually first, and then ifcopenshell.

**Comment by aothms** [comment]
If I'm not mistaken you can use `conda install -c conda-forge -c oce -c dlr-sc -c ifcopenshell ifcopenshell`

Conda could be a bit more intelligent autoguessing channels for such obvious channel names identical to packages, if you ask me.

**Comment by aothms** [comment]
> Maybe its possible to change this in the conda channel, where it says:

All packages say that, don't think it can be updated. e.g. https://anaconda.org/pythonocc/pythonocc-core https://anaconda.org/oce/oce

**Comment by Moult** [comment]
Closing as there is now a stable conda build.
