### ISSUE TITLE
use ifcopenshell how to change ifcbuilding height

### ISSUE THREAD

**Issue by 99zhu** [IfcOpenShell/IfcOpenShell#3183]
I want change ifcbuilding height,should I reset while attribute ?   thanks

**Comment by Moult** [comment]
We'll need a bit more detail about what you mean by changing the building height. Do you mean also changing / stretching geometry of walls? Or just the local placement of the building object? Or offsetting the entire project in the Z axis?

**Comment by 99zhu** [comment]
> 我们需要更详细地了解您更改建筑物高度的含义。你的意思是也改变/拉伸墙壁的几何形状吗？或者只是建筑对象的局部放置？还是在 Z 轴上偏移整个项目？

I mean change or stretch geometry of all building's elements of height,not just local placement of the building object or offset the entire project in the Zaixs.
thang you,looking forward your reply.

**Comment by 99zhu** [comment]
> Hello, first there is no need to use capitalized letters to communicate, it is the equivalent of shouting online which is rude.
> 
> Then, please provide a bit more information about your setup, your problem, what you have done to solve it and why it doesn't work. Screenshots are a good way to communicate your setup. Also, maybe share the snippets of code you have used and the name of the visualization software you're using.
> 
> Cheers

sorry for that.
I use bimvision to visualization.I want to change the "boung Bounding Box Height" this element.but it's doesn't work.
thank you for your reply.

**Comment by Moult** [comment]
You'll want to use the BlenderBIM Add-on ( https://blenderbim.org ) which is a graphical Blender-based native IFC authoring app. You'll load in the IFC, then like any other authoring platform make decisions on how to edit walls, windows, etc. Unless you have a simple building or you help share your building for analysis this is not something you should probably do with a script. e.g. if you stretch a wall, does the window move up too, or is the sill height constant? Do you have curtain walls, how should they stretch? etc

**Comment by 99zhu** [comment]
> You'll want to use the BlenderBIM Add-on ( https://blenderbim.org ) which is a graphical Blender-based native IFC authoring app. You'll load in the IFC, then like any other authoring platform make decisions on how to edit walls, windows, etc. Unless you have a simple building or you help share your building for analysis this is not something you should probably do with a script. e.g. if you stretch a wall, does the window move up too, or is the sill height constant? Do you have curtain walls, how should they stretch? etc

I want to use ifcopenshell library to change building's height directly,don't use  BlenderBIM.how can i do that?
thank you.

**Comment by aothms** [comment]
As @Moult said, there is a lot of detail to that question. In IFC a building is composed of a elements, wall, windows, but also windows and storeys (levels). There isn't one parameter in the model you can tweak to have all elements stretch and move accordingly.

**Comment by Moult** [comment]
@99zhu is there a reason you don't want to use the BlenderBIM Add-on? It uses IfcOpenShell under the hood, so if you want to automate it for a lot of similar buildings, you can see which operations are run and convert that to a pure IfcOpenShell script depending on how complex your building is.

If you share your model we can tell you how easy or difficult it is.

**Comment by Moult** [comment]
All your geometry are BReps. In this situation, the best thing to do is absolutely to use the BlenderBIM Add-on. It takes only a few seconds to stretch up the top floor in a short test that I did.

**Comment by Moult** [comment]
I'm closing this as there isn't much we can say here other than if you have a soup of vertices, either you have to manually analyse the topology (via https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html ) and perhaps some hints from util.shape, and shift them programmatically, or just use a visual tool which makes a lot more sense in this context. It isn't really a bug nor is there anything we can really build to aid you.
