### ISSUE TITLE
With aggregates, ifcopeningelements not showing in BB drawings.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3186]
We're using aggregates on [this](https://gitlab.com/openingdesign/highland_haven/-/blob/ed715b78194e319b79b778b1d30b4a4bd972766f/Models_and_CAD/Highland_Haven.ifc) project. 

As you can see from the following, the ifcopeningelement doesn't show in the drawing. 

Is there a relative easy way to correct this?

![FLOOR PLAN - 1ST FLOOR](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/6a323a54-2db2-4a93-9019-4f49333c5ebb)

![2023-05-22_19-13-38_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/de12b0cb-e124-4b0b-8fa6-de16f8cef96e)

**Comment by Andrej730** [comment]
Can you please help me pin down the issue?

Is it drawing problem? For example this door doesn't have any openings in the wall - therefore there are none in the drawing
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/58f45c0c-540a-4be6-b6d9-0bf7c261206c)

**Comment by Moult** [comment]
@theoryshaw I don't quite understand this issue. What's the bug? As @Andrej730 says there aren't any openings there.

Is the bug this: https://www.dropbox.com/s/r1uh6nhag2ejsfm/2023-05-24_08-47-39_Blender_blender.mp4?dl=0 which you posted here: https://community.osarch.org/discussion/comment/15809/#Comment_15809 ? Or is that another bug?

**Comment by theoryshaw** [comment]
> Is the bug this: https://www.dropbox.com/s/r1uh6nhag2ejsfm/2023-05-24_08-47-39_Blender_blender.mp4?dl=0 which you posted here: https://community.osarch.org/discussion/comment/15809/#Comment_15809 ? Or is that another bug?

Yes, i believe that is the bug.

Ping @brunoperdigao, if interested. :)
