### ISSUE TITLE
IFC Viewer

### ISSUE THREAD

**Issue by krosoftware** [IfcOpenShell/IfcOpenShell#319]
Hello
we need to display IFC file in the web-browser and to interact with clicked object (to get object's dimensions and other existing values).
What software is needed to do that?
I saw bimserver but it require java installed and it does not worked for me.
Is there any other options, please?
Thank you.

**Comment by Stinkfist0** [comment]
Personally I don't know any other free and/or open-source options. One can always implement this on her own, but it will be a considerable undertaking.

**Comment by stefkeB** [comment]
What about [BIMSurfer](https://github.com/opensourceBIM/BIMsurfer)?

**Comment by aothms** [comment]
> What about BIMSurfer? I know it uses BIMserver, but it seems to do what you need?

My thoughts exactly. Note that you can use IfcConvert [1] to convert IFC to Collada and XML and use [2] to convert the Collada to glTF. These can be fed directly to BimSurfer as well bypassing the need for a BIMserver installation.

http://opensourcebim.github.io/BIMsurfer/docs/example_glTF.html

[1] http://ifcopenshell.org/ifcconvert.html
[2] https://github.com/KhronosGroup/COLLADA2GLTF

**Comment by Stinkfist0** [comment]
Ah, right, completely forgot about BIMsurfer!

**Comment by Moult** [comment]
In an attempt to close some older bugs that aren't really bugs, now three years later there is IFC-Pipeline, Xeokit and IFC.JS as three options to choose from :)
