### ISSUE TITLE
How can I move all the elements that are in the wall when the wall moves?

### ISSUE THREAD

**Issue by Theinformatiker** [IfcOpenShell/IfcOpenShell#3191]
Is it possible if I have created the wall with an opening element and placed a fixed one there, so that when I move the wall the window also moves. At the moment only the wall with its opening is moved. I use the python api for this, but it would also be interesting to know the whole thing for c++ :-).

```py
        # moves the wall into the edit position for create  opening and window
        run("geometry.edit_object_placement", model, product=wall, matrix=MatOrgin)
        # crate opening
        op = run("root.create_entity", self.model, ifc_class="IfcOpeningElement")
        # crate geometrie
        repsOp = run("geometry.add_wall_representation", model, context=sbody,
                     length=length, height=height, thickness=thickness)
        run("geometry.assign_representation", model, product=op, representation=repsOp)
        matrix = np.identity(4)
        matrix[:, 3] = [x, y, z, 0]

        run("geometry.edit_object_placement", model, product=opening, matrix=matrix)
        # The opening will now void the wall.
        run("void.add_opening", model, opening=opening, element=wall)
        win = run("root.create_entity", model, ifc_class="IfcWindow", name="Window")

        repsWin1 = run("geometry.add_wall_representation", model, context=body,
                       length=length, height=height, thickness=thickness)

        run("geometry.assign_representation", model, product=win, representation=repsWin1)
        run("geometry.edit_object_placement", model, product=win, matrix=matrix)

        # moves the wall into the right position
        run("geometry.edit_object_placement", model, product=wall, matrix=wallMat, should_transform_children=True)

```

If I move the wall back to its correct position at the end, the window still remains in the old position.
How can I solve the problem even if I move the wall in Blender the same problem occurs?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/6c6c6e8c-7aa5-416c-8ad5-b62649014684)

In Blender there is a relation where you can assign the window to the wall.
Isn't there something like that in the Ifcopenshell too?

Thank you for your time and attention.

**Comment by Theinformatiker** [comment]
`#moves the wall into the edit position for create  opening and window
            run("geometry.edit_object_placement", model, product=wall, matrix=MatOrgin)
            #crate opening
            op = run("root.create_entity", self.model, ifc_class="IfcOpeningElement")
            #crate geometrie
            repsOp = run("geometry.add_wall_representation", model, context=sbody,
                                   length=length,height=height,thickness=thickness)
            run("geometry.assign_representation", model, product=op, representation=repsOp )
            matrix = np.identity(4)
            matrix[:,3] = [x, y, z, 0]

            run("geometry.edit_object_placement", model, product=opening, matrix=matrix)
            # The opening will now void the wall.
            run("void.add_opening", model, opening=opening, element=wall)
            win =  run("root.create_entity", model, ifc_class="IfcWindow", name="Window")
            
            repsWin1= run("geometry.add_wall_representation", model, context=body,
                                                   length=length,height=height,thickness=thickness)
            
            run("geometry.assign_representation", model, product=win, representation=repsWin1)
            run("geometry.edit_object_placement", model, product=win,matrix=matrix)
            
            #moves the wall into the right position
            run("geometry.edit_object_placement", self.model, product=wall, matrix=wallMat)`

**Comment by Theinformatiker** [comment]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/e84bdcf7-00e5-4f7b-8104-b8d1df990229)

In Blender there is a relation where you can assign the window to the wall.
Isn't there something like that in the Ifcopenshell too?

**Comment by theoryshaw** [comment]
Not an expert, but maybe the following will provide a hint...

`bim.select_decomposition`
and
`ifcopenshell.util.element.get_decomposition(element)`


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/bec5e2c3-94cb-4b28-ae3b-98ee5703206f

**Comment by theoryshaw** [comment]
This is a BlenderBIM, solution, but most of BB commands are ifcopenshell api commands.  So you can use it to reverse engineer what you're after for a pure ifcopenshell solution--for python, anyway.

Again, not an expert, but this is what I do. :)

**Comment by Moult** [comment]
Assuming it is a valid IFC, you should be able to do it one line of Python:

```python
ifcopenshell.api.run("geometry.edit_object_placement", model, product=wall, matrix=matrix, should_transform_children=True)
```

**Comment by Theinformatiker** [comment]
@Moult  I have try run("geometry.edit_object_placement", model, product=wall, matrix=wallMat, should_transform_children=True) to use , but it has no effect of my objects


![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/90caecc8-f084-4762-9780-fe06d81d28a6)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/48aab8aa-d602-41a8-b2f5-c6f3009fe1a6)

**Comment by Moult** [comment]
No, the reason is because your model does not have the appropriate relative placements that determine children and grandchildren. Notice how your window is not placed relative to your opening (122).

How did you create the model? If you created it with the BlenderBIM Add-on, that would be a bug since it has created an invalid situation and if you give me instructions we should fix it. If you created it with your own script, I can help fix your script.

**Comment by Moult** [comment]
Bump?

**Comment by Theinformatiker** [comment]
@Moult I have create it with my own script.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/c6c3e8ba-296a-4001-93cd-0eadb2ea4fa1)


what is strange is that it works now, but I can only create one opening if I create several openings and assign them, it does not work properly.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/aeb7e90b-457e-4621-87c8-b22a767f009f)

Only the last opening that is called in the script is correctly created and inserted and palced.

**Comment by Moult** [comment]
Without seeing your script it's hard to know what is and isn't right. Have you considered using the IfcOpenShell API for this? It greatly simplifies and reduces the possible error when authoring IFCs programmatically.

**Comment by Theinformatiker** [comment]
Since it is my thesis I would have to ask if I can publish code in advance .
I use IfcOpenShell API on Python

**Comment by Moult** [comment]
I specifically mean the API module e.g. https://blenderbim.org/docs-python/ifcopenshell-python/code_examples.html#create-a-simple-model-from-scratch

For example if you use https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/geometry/edit_object_placement/index.html to set locations, it will automatically handle all relative placements correctly for you.

**Comment by Theinformatiker** [comment]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/f03c2788-d19f-48d8-91e2-2bdd17c64d91)

**Comment by Moult** [comment]
So uh did it work? :)

**Comment by Theinformatiker** [comment]
Yes that what I wanted to do is only if you move the wall manually in Blender. But that could perhaps be a Blender thing.

Why does it only move the wall but not the other objects hmm?

**Comment by Moult** [comment]
I'm not sure I understand your question. In Blender you can choose whether to move only the wall, or all objects, or some objects, etc. You can activate the BIM Tool (green cube icon in the viewport) then do Alt-D to select all decompositions if you want to move all children.

**Comment by Theinformatiker** [comment]
You mean this ?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/9053c9f1-91aa-4771-a10a-96310fafde10)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/5ed04a5f-9acb-4873-9f8d-2cc2eadeee11)

**Comment by Moult** [comment]
No, it looks like you are manually creating parents. In the 3d viewport sidebar (T) you can enable the BIM Tool (Green Cube icon). This gives you access to various hotkeys like Alt-D:

![2023-05-30-222611_417x521_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/8eadeba2-4e83-4fa1-8589-0c78d9bd602a)

**Comment by Theinformatiker** [comment]
This ?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/a15eb862-0924-4c7e-ae47-73790f932981)


![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/ae879a9d-2cb3-4b13-87fe-625280a7a6a6)

**Comment by Moult** [comment]
Yep.

**Comment by Moult** [comment]
Is the issue solved? Is there anything else we can help with?

**Comment by Theinformatiker** [comment]
it is solved :-) 
thank you for your effort and help !!! :-)
