### ISSUE TITLE
[IfcOpenShell-Python] should_purge=True not removing empty properties - ifcopenshell.api.run("pset.edit_pset")

### ISSUE THREAD

**Issue by ragnhmyr** [IfcOpenShell/IfcOpenShell#3197]
Hi!
We're using the Tekla software to create ifc models. However, it exports all properties even though they have not been defined. We want to delete all these empty properties to make the file a bit cleaner and smaller
I have been discovering ifcopenshell (python) and can manage to edit property values etc, but I cant seem to delete single properties.
I do not want to delete a whole property set, as only some properties on some elements are empty..
I read here (https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/pset/edit_pset/index.html) that you can set should_purge=True to delete properties that are None, but it does not seem to be working unfortunately, I've tried many times...
I can e.g set all the empty values to another value, but they are not removed even though I set the value to None and should_purge=True.
Is it a bug or have I done it wrongly?
Thank you so much in advance!

Current code below:
Sorry partly norwegian and english code, it is under development..
```python
ifc = ifcopenshell.open(nysti)
objekter = ifc.by_type("IfcProject")[0]
#print(objekter)
#type=ifcopenshell.util.element.get_types(objekter)
#print(type)
decomposition = ifcopenshell.util.element.get_decomposition(objekter)

count=1
for elem in decomposition:
    egenskap = ifcopenshell.util.element.get_psets(elem)
    #print(egenskap)
    print("ELEMENT NUMBER " + count)
    for pset, property in egenskap.items():
        #print(pset)
        for value in property:
            #print(value,property[value])
            if property[value] is None or property[value]== "":
                 print("Denne er none")
                 print(pset,value,property[value])
                 #lagepset = ifcopenshell.api.run("pset.add_pset", ifc, product=elem, name=pset)
                 #test=ifcopenshell.util.pset.get_by_name(pset)
                 egenskapssett = ifc.by_id(egenskap[pset]["id"])
                 ifcopenshell.api.run("pset.edit_pset", ifc, pset=egenskapssett, properties={value: None}, should_purge=True)
    count+=1
ifc.write(nysti)
```

**Comment by Andrej730** [comment]
Hello! Can you please attach some .ifc example you're trying your code on?

**Comment by ragnhmyr** [comment]
Hi! Sorry seems like github does not support the file type IFC, but I renamed it to a text file and have attached it here.  I also asked in another forum where it actually worked for that user, so it seems strange that it is not working for me?
I have ifcopenshell version 0.7.0.230418
I have installed it through pip install. 
[TomIFC.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11563426/TomIFC.txt)

**Comment by Andrej730** [comment]
Can confirm that both snippets do purge empty properties and have the same result. Just tried with the latest package from pip, python 3.11.
@ragnhmyr can you try to upgrade ifcopenshell with `pip install ifcopenshell -U`?

**Comment by ragnhmyr** [comment]
Thank you so much! still not working even after pip install ifcopenshell -U..
But I tested with a colleague and it worked for him luckily on his computer :) 
So I guess I just have to dig a little deeper into the matter maybe try different python versions, reinstall etc etc...
Please let me know if you have any more suggestions on how I can make it work :)

**Comment by Andrej730** [comment]
It might be that either you updated ifcopenshell for some other python instance not the one you're using to run the script or python is picking ifcopenshell dependency from elsewhere. You can do `import ifcopenshell; ifcopenshell.__file__` in the console to investigate that.

**Comment by Andrej730** [comment]
@ragnhmyr you can try to delete the old one to be sure

**Comment by ragnhmyr** [comment]
oooh I deleted the old one and it seems like it might be working now (takes some time to loop through the files).
Thank you sooo much @Andrej730  and thank you @cvillagrasa again :)
