### ISSUE TITLE
Viewport Annotations Performance

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#3198]
Reported on [BlenderBim - Annotation Performance](https://community.osarch.org/discussion/1491/blenderbim-annotation-performance#latest) that many ifc text annotations are really slowing down the viewport. 

Just tested it on empty file with 500 one-line text annotations (have laptop with 3060rtx, i7-12700H 2.70 GHz 20 threads):
- \> 60 annotations - viewport perfomance it becomes noticeable and it's smooth but it's gradually getting slower and slower
- \> 200 - here I wouldn't call it smooth anymore and it's getting progressively more annoying and harder to work with

Text annotations and fps:
- 175 = 24 fps
- 250 = 19 fps
- 350 = 15 fps
- 512  = 10 fps

PS Haven't found some quick way to measure fps in viewport and was measuring it just by starting animation and checking fps counter.

Test file:
[annotations_performance.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11564067/annotations_performance.ifc.txt)

What experience you had with BBIM annotations performance? 
How many annotations we definitely should support on the screen you think?

**Comment by Plae-Blue-Dot** [comment]
I am not normally in the habit of counting annotations but its really depending on the size of the drawing and no. of annotations in it, Until now it hasn't been an issue but there are quite a few instances of having 2-3000 annotations on screen, especially when dealing with Site plans and Urban plans, 

I think aiming for good performance in that range would probably suffice for now, 5000 would be amazing as a cap and I can't think of many circumstances where more than that would be needed on a single drawing

**Comment by Moult** [comment]
We will easily have hundreds of text annotations on a screen for things like car parks and overall GAs.

**Comment by Andrej730** [comment]
I've found some huge bottleneck we used to have - we used to iterate over all objects for each decorator which was taking a lot of time. Now we're iterating once over all objects.

Tests:

167 dimension annotations
processing annotations time: 0.054 s -> 0.027 s
fps: 17 -> 24 

512 text annotations
processing annotations time: 0.104 s -> 0.0088 s
fps: 9.18 -> 24

**Comment by Andrej730** [comment]
Close it for now until we met some new annotations performance limitation 😄
