### ISSUE TITLE
BlenderBim - Including an IfcWindow does not display the window at all in SVG

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3200]
Here I've got a window I need isolated, previously I have used "include" to only have the window in the drawing.
Now when printing the SVG does not print the window at all.

Here is the model:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/0882e9d7-c7ed-45ae-8aeb-c48a2194b4f4)

Here is the SVG:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/a637c441-274c-4200-826b-b67819af1eee)

For control here is the SVG with nothing included or excluded:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/221d8f16-84ef-470e-9873-a5890c2aba6d)

**Comment by theoryshaw** [comment]
If you only do .IfcWindow does it show up?

**Comment by Plae-Blue-Dot** [comment]
> 

No it doesn't it's just an empty SVG:

Model with different Window:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/8dd20829-78ef-4b3e-b0ea-df4e70e89c6b)

SVG:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/e32dfa23-c36e-4ee5-a3f4-387d1a37bc43)
