### ISSUE TITLE
CSG boolean problem in bridge model

### ISSUE THREAD

**Issue by Baruchware** [IfcOpenShell/IfcOpenShell#3201]
Hello!
I would like to share with you a couple of Ifc files which are causing issues, but I have to share these files confidentially.

One of this file has boolean operations issue, I can share images here:

This is wrong output (got by the ifc file exported with CV2 Geometry)
![immagine](https://github.com/IfcOpenShell/IfcOpenShell/assets/53627894/329e281e-4b9e-4282-b429-07d0e1c06bba)

This is correct output (got by the ifc file exported with SG Geometry)
![immagine](https://github.com/IfcOpenShell/IfcOpenShell/assets/53627894/669a8ca2-6c18-4e13-8913-c3166a438ca2)

Those are the settings I am using:
```
	SerializerSettings serializeSettings;
	serializeSettings.set(IfcGeom::IteratorSettings::APPLY_DEFAULT_MATERIALS, true);
	serializeSettings.set(IfcGeom::IteratorSettings::USE_WORLD_COORDS, false);
	serializeSettings.set(IfcGeom::IteratorSettings::WELD_VERTICES, true);
	serializeSettings.set(IfcGeom::IteratorSettings::SEW_SHELLS, false);
	serializeSettings.set(IfcGeom::IteratorSettings::CONVERT_BACK_UNITS, true);
	serializeSettings.set(IfcGeom::IteratorSettings::DISABLE_OPENING_SUBTRACTIONS, false);
	serializeSettings.set(IfcGeom::IteratorSettings::DISABLE_BOOLEAN_RESULT, false);
	serializeSettings.set(IfcGeom::IteratorSettings::INCLUDE_CURVES, false);
	serializeSettings.set(IfcGeom::IteratorSettings::EXCLUDE_SOLIDS_AND_SURFACES, false);
	serializeSettings.set(IfcGeom::IteratorSettings::APPLY_LAYERSETS, true);
	serializeSettings.set(IfcGeom::IteratorSettings::LAYERSET_FIRST, false);
	serializeSettings.set(IfcGeom::IteratorSettings::NO_NORMALS, true);
	serializeSettings.set(IfcGeom::IteratorSettings::GENERATE_UVS, false);
	serializeSettings.set(IfcGeom::IteratorSettings::EDGE_ARROWS, false);
	serializeSettings.set(IfcGeom::IteratorSettings::SITE_LOCAL_PLACEMENT, false);
	serializeSettings.set(IfcGeom::IteratorSettings::BUILDING_LOCAL_PLACEMENT, false);
	serializeSettings.set(IfcGeom::IteratorSettings::BOOLEAN_ATTEMPT_2D, true);
	serializeSettings.set(IfcGeom::IteratorSettings::VALIDATE_QUANTITIES, true);
	serializeSettings.set(IfcGeom::IteratorSettings::NO_WIRE_INTERSECTION_CHECK, true);
	serializeSettings.set(IfcGeom::IteratorSettings::NO_WIRE_INTERSECTION_TOLERANCE, true);
	serializeSettings.set(IfcGeom::IteratorSettings::STRICT_TOLERANCE, true);
	serializeSettings.set(IfcGeom::IteratorSettings::DEBUG_BOOLEAN, false);


	serializeSettings.set_deflection_tolerance(0.1);
	serializeSettings.set_angular_tolerance(1.6);
	serializeSettings.precision = 2;


	// Redirect the output (both progress and log) to stdout
	//Logger::SetOutput(&std::cout, &std::cout);

	IfcGeom::Iterator geom_iterator_serializer(serializeSettings, &file, 16);
```

I also have another different file which has a lot of geometry, and when I try to parse it and convert it, I can see out of memory errors from the logger, before the iteration begins.
EDIT:
the following line of code is the one where the application goes out of memory:

`IfcParse::IfcFile file(<that ifc file>);`

if possible and if you want to, how can I contact you privately?

If you have questions or doubts, please do not hesitate to ask!
Thank you in advance

**Comment by Moult** [comment]
I'd be happy to take a first look at dion@thinkmoult.com - afterwards if I still cannot help, you might need to send to models@ifcopenshell.org for @aothms to investigate.

**Comment by Baruchware** [comment]
Thank you a lot, Moult! I do really appreciate! 
I sent you an e-mail with more details and the Ifc files I was talking about!

**Comment by Moult** [comment]
Unfortunately I was able to recreate the boolean issue and was not able to spot any obvious problems. You'd need to send the model to models@ifcopenshell.org for @aothms. Alternatively if you're OK with it I can extract just that one object and use that file as a test case.

As for your OOM issue, I don't experience that on my end. Admittedly my settings are a bit different to yours, such as I have layersets turned off. Can you possibly recreate it with a minimal Python script (https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html#geometry-iterator) and just use the default settings?

**Comment by Baruchware** [comment]
Thank you again Moult,
for what concerns the boolean issue, I sent the models also to that e-mail, and yes, you can extract the objects which you need for the test case! 👍 

for the other issue I am getting (the OOM), It is weird, from python it works as expected as you say, but in C++ the geometry Iteration never starts... the program fails just before.. I thought maybe because on c++ I am running on 32 bit, but trying to download the python 32 bit ifcOpenShell (from here: [https://blenderbim.org/docs-python/ifcopenshell-python/installation.html](url) ) it still works as expected.

I tried commenting out every iterator setting, but I still get Out Of Memory issues, do you have any idea on what it could be the reason??

**Comment by Moult** [comment]
Sorry, I don't know how the C++ works :) @aothms will be able to tell but if that's the line that goes OOM I'd guess that it's perhaps to do with the 32bit as you say. Have you considered just writing it in Python instead of C++?

**Comment by Baruchware** [comment]
Hello Moult, I am converting my code from c++ to python, and I can use my own converter with all those files which before gave me OOM error without any issue :) this is weird: seems like the `ifcopenshell.open(ifcfile)` python method is more efficient than the `IfcParse::IfcFile file(ifcfile)` in C++.

I am happy to be back with python, but I would like to know why this happen 😄 

I was using C++ for some reasons, like performance and to _avoid_ decompilation.

Now, except the boolean Issue, I just have to make the conversions faster, as you said in an old Issue, files which come from tekla are slow in the geometry iteration by ifcOpenShell, I have seen in a post here that with the 0.8.0 branch using _cgal_ the iteration is much faster, is it possible to try the 0.8.0 branch with python?

Sorry for the noob question..
And thank you for your help!

**Comment by Moult** [comment]
I agree that it sounds strange, but unfortunately I don't know C++ and can't help :(

From memory Tekla files typically don't have performance issues related to the iterator - they have performance issues in Blender specifically due to high object counts, but that isn't something IfcOpenShell can fix. Tekla files mostly contain lots of simple objects (i.e. extrusions). I'm surprised you're having performance issues.

In contrast, OpenCASCADE is pretty poor at dense tessellations, so if you have mesh heavy models, OpenCASCADE will perform poorly and that's where cgal can really help.

I haven't used the v0.8.0 branch myself, but potentially you can try https://github.com/IfcOpenBot/IfcOpenShell/commit/98a73f1646c987b6aa512050ab19ff81c821d72c#commitcomment-108765313 - I'm not sure what flags to set to use CGAL though. At a glance it looks as though you just set the kernel as the first argument to the iterator (e.g. `cgal`): https://github.com/IfcOpenBot/IfcOpenShell/blob/v0.8.0/src/ifcconvert/IfcConvert.cpp#L1068 but I've never tried so myself.

**Comment by Baruchware** [comment]
Thank you so much Moult, I appreciate!

Sadly I can not make it work, the suggestion of vs code show this:
![immagine](https://github.com/IfcOpenShell/IfcOpenShell/assets/53627894/0efaaae5-2d4b-477a-a415-6e03bc5eb4cf)

which to me seems a bug, maybe cgal has not been implemented python side. what do you think?
I will check with future builds of course 😄 

if you think this too much off topic I can create another one

BTW I will let this issue open for the boolean issue.

**Comment by Moult** [comment]
@Baruchware no issues at all, have you tried simply updating the Python iterator signature?

**Comment by Baruchware** [comment]
Thank you for the suggestion, I don't get what you mean exactly, Do you mean to modify the main.py of geom module?
Here you can see what happens if I try to add geometry_library parameter to the iterator initialization in the console:

`NotImplementedError: Wrong number or type of arguments for overloaded function 'new_Iterator'.
  Possible C/C++ prototypes are:
    IfcGeom::Iterator::Iterator(std::string const &,IfcGeom::IteratorSettings const &,IfcParse::IfcFile *,std::vector< IfcGeom::filter_t,std::allocator< IfcGeom::filter_t > > const &,int)
    IfcGeom::Iterator::Iterator(IfcGeom::IteratorSettings const &,IfcParse::IfcFile *,std::vector< IfcGeom::filter_t,std::allocator< IfcGeom::filter_t > > const &,int)
    IfcGeom::Iterator::Iterator(IfcGeom::IteratorSettings const &,IfcParse::IfcFile *)`

of course I am missing some arguments, that's why.

Here I can see that the first function prototype is the one I would like to call, but I found that other than the 'geometry_library' parameter we also have a vector of geom filters which must be passed, which I don't know how to use in python, is there an example or hint for this?

**Comment by aothms** [comment]
Sorry for the delay, I've managed to take a look. Debugging these kind of geometrical issues is often quite time consuming.

The issue appears to be the profile itself.

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/0c05e2be-ebfa-4951-ad21-515c19ef4d83)

Apparently Open CASCADE considers it self-intersecting where the circular segments hit the linear edge, but our own self-intersection code actually doesn't detect it.

I've implemented a fix to approximate such sharp corners with a linear approximation, making it coarse enough so that the first vertex is a bit away from the other edge.

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/7f887b33-1150-4b6e-a705-7e1e9eb20ba6)

**Comment by Moult** [comment]
@Baruchware there hasn't been a build yet, this is done "once in a while". Maybe in a couple of weeks there'll be another build out.

**Comment by Baruchware** [comment]
Thank you,
@Moult @aothms I appreciate a lot your willingness to help, 
keep it up!

**Comment by aothms** [comment]
https://github.com/IfcOpenBot/IfcOpenShell/commit/b33e58f40b628bb892bc5d987575917453c7bde7

**Comment by Baruchware** [comment]
Thank you @aothms

I tried the py311 package for Win (64 bit) with this last build, 
But during the geometry iteration of that specific ifc file (the bridge with boolean issue), the app keep stopping without throwing exceptions, while with the _v0.7.0-476ab506d_ it was working fine.

I tried to understand which the problem is, but the app stops while iterating on different objects of different type, on different lines of code.

So i tried just this:

```
if iterator.initialize():
        try:
            while True:

                #do nothing
                if not iterator.next():
                    break
        except Exception as e:
            print(e)
```

And I still face the same issue, I really don't have idea how to debug more deeply, I tried to trace the _.py_ but I didn't found something that could help me understand where the problem comes from.

With all the other files still works

**Comment by aothms** [comment]
Thank you for testing. I only tested on the isolated element. My fix was in the right direction, but still misguided on the details. Should be better now. Started a new build.
