### ISSUE TITLE
Blenderbim - Crash to Desktop when going out of edit mode

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3204]
I'm sorry in advance because I haven't been able to pinpoint how to reproduce this bug, so I can't give much information about it. It's happened pretty consistently while modifying meshes in edit mode. I'd say once every half hour on average. I'm pretty certain it's due to the overriden Object Mode toggle operator.

On going out of edit mode, Blender freezes for a split second then crashes to desktop. Running the latest Blenderbim version, on windows.
 
I did notice it almost always happened if I have used CTRL + Z to undo a mesh modification at some point. It might also be related to modifying a typed instance geometry, although it has happened to me in a blend file without an ifc file initialized, while going out of edit mode on a regular blender mesh object.

It might be due to a conflict with another addon, although the ones I'm usually using with Blenderbim are in general pretty minor. I'll investigate though.

I'm posting this to start a conversation and see if other users have witnessed the same types of crash, to hopefully fix it.

**Comment by Moult** [comment]
A minor note that we no longer override object mode, we only override the tab hotkey.

I haven't experienced this before and I just tried to randomly keep on editing a fresh cube and undoing and was unable to replicate.
