### ISSUE TITLE
Hatches don't appear in Drawing with other Element Types, but Walls

### ISSUE THREAD

**Issue by U-Rod** [IfcOpenShell/IfcOpenShell#3205]
I was trying to hatch concrete beams and colums on drawing, but I got it just for walls, editing LayerSetName or IfcMaterial (when no WallType seted yet).
[wall.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11583086/wall.txt)

**Comment by Moult** [comment]
This was fixed yesterday :) https://github.com/IfcOpenShell/IfcOpenShell/commit/00c010e04d1474c1307a7ad52b1f5a0c5a322ca1 sorry about the bug!
