### ISSUE TITLE
Drawing generation performance

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#3207]
With the following file as an example, generating a drawing with linework and 2 annotations takes a good 4 minutes.
[example_simple_house_BBIM.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11584999/example_simple_house_BBIM.zip)

Not sure what's up, but here's the log:

```
Initialize drawing generation process 0.02485560000059195
Generate underlay 2.6900001103058457e-05
sync 0.3217432000092231
Processing body context 1.789761299995007
Processing body context 1.300009898841381e-06
Processing body context 1.00000761449337e-06
Processing body context 3.879824899981031
Processing annotation context 0.014818700001342222
Processing annotation context 2.2999884095042944e-06
Processing annotation context 2.200016751885414e-06
Processing annotation context 0.003015499998582527
Finalizing 202.92570609998074
Generate linework 217.68741549999686
Generate annotation 0.05818680001539178
Combine SVG layers 0.11600750000798143
**Drawing generation process 217.88746989998617**
```

Another issue is the alignement of the annotations, see image below:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79010126/07f375f3-bdb5-4f0c-9464-24d63b47dbed)

**Comment by theoryshaw** [comment]
If you simplify the toilets, it goes a lot faster. 
Perhaps use Plan/Body/PLAN_VIEW context for just a 2D representation of the toilet in plan. 

How to find large meshes...
https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/570d7aa6-845b-450a-9076-e541b3611f44

**Comment by myoualid** [comment]
You are right indeed;  It went down from 4 minutes to 7 seconds...
BlenderKit is both a blessing and a curse :/

I noticed the toiletpan annotation text values do not show up in your video ?

**Comment by theoryshaw** [comment]
> I noticed the toiletpan annotation text values do not show up in your video ?
I deleted the toilets, so the tag had no data to pull from anymore.

**Comment by Moult** [comment]
Indeed, don't just drop in meshes. We'll have to setup a better way to reference high res meshes so that users can include that detail if needed.

**Comment by myoualid** [comment]
Two new issues out of a none issue.. 
- If we delete an object with annotations, annotations referencing this object should be deleted too
- The annotation used here has two text literals overlapping in the .svg

**Comment by theoryshaw** [comment]
> If we delete an object with annotations, annotations referencing this object should be deleted too

I'm a little hesitant on this one.  Could see usecases where you'd want to keep the annotation location/formating, etc, but reapply to another instance.  It's not a strong hesitation, more an inclination. :)

**Comment by Andrej730** [comment]
> I guess by default if no special symbols are used we should just create newlines for them

Are there cases where you would want multiple literals to have same position but different box alignment? 
I thought there might be and I didn't use newlines to separate literals for that reason, thought it shouldn't be a problem since newlines can be created with `\n` anyway.

**Comment by Moult** [comment]
@Andrej730 unlikely. If someone wants that, they should use a symbol.
