### ISSUE TITLE
Compiled version of current development version

### ISSUE THREAD

**Issue by swalter88** [IfcOpenShell/IfcOpenShell#321]
We need some of the added features in IFCConvert (ifc to xml) like IfcMaterial... It seems to complicated for us to compile the source code by ourself..... could someone provide a compiled version for us?

**Comment by Stinkfist0** [comment]
There's a release page, https://github.com/IfcOpenShell/IfcOpenShell/releases, but if those aren't recent enough, maybe Thomas can cook up  a batch at some point. I suspect the current release might include IfcMaterials in the XML output though.

**Comment by swalter88** [comment]
I am using the 0.5.0 preview 2 and no material information will be converted... Special parameter to use?

**Comment by Stinkfist0** [comment]
Ah, sorry, it would appear that the last release was done on 2017-03-16 but materials were not added in the XML until 2017-07-02.

**Comment by swalter88** [comment]
did a compilation on debian stretch, but version only works on debian stretch with dependencies installed... how do you include the dependencies into the compiled version? because to work with the released versions from this repo i did not need to install anything... thank you!

**Comment by aothms** [comment]
The difference is static vs dynamic linking. Most libraries installed through the package manager are dynamic libraries. 

The following script can be used to obtain exactly the release build https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.py

Should be as simple as `python build-all.py`.

**Comment by swalter88** [comment]
Thx! Get a compiled version with a Debian 7.8 Distribution and this python script. But the output executable is 600mb large!!! How can i reduce the size to 50mb like in the releases?

**Comment by aothms** [comment]
I didn't expect it to be that big, it's probably because of debugging symbols. Where did you find the executable (it should be in (I think) `./build/.../install/ifcopenshell/bin` or something, that one is 'stripped'). Also you can try with `BUILD_CFG=Release python build-all.py`, but yeah, then you'll need to start over, easiest to remove the `./build` directory.

**Comment by swalter88** [comment]
Looked in the wrong directory... thx! I think this thread can be closed, but it would be really nice to have builds for Win and Mac too. Maybe you could release a preview3? Thx so far!!

**Comment by aothms** [comment]
Good to hear it's resolveed

> but it would be really nice to have builds for Win and Mac too. Maybe you could release a preview3

I know, it's on the list, things are pretty close now to being fully automated
