### ISSUE TITLE
BlenderBim  - Geometry no longer displays in elevation & section

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3210]
previous: Blenderbim 230517
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/081666ce-2af2-4845-9220-920094660f0f)

new: Blenderbim 230529
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/9c8a8e72-2726-4989-9944-e4cef8611b26)

**Comment by Plae-Blue-Dot** [comment]
I have some exclude filters:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/ba8681fe-5768-4639-8e51-7a85c0491f68)

but i've got the same ones in the plan view and that doesnt have the same error:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/5ffd227d-3b78-4060-85fd-a20d00ff79b9)

After removing the excluded object I still get no geometry in the svg:
model:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/a6f5e2db-2bc7-4f62-87c3-f3699c1a5aaa)

SVG:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/fdf1139d-f32b-4394-ad87-e6b5698822a4)

**Comment by Moult** [comment]
At a guess, can you undo this change if you have it? https://github.com/IfcOpenShell/IfcOpenShell/commit/6f39648077090a365f8e0060b1763b69edf2f477

**Comment by Moult** [comment]
If not, can you share your model (dion@thinkmoult.com) since I can't replicate it here :(

**Comment by Plae-Blue-Dot** [comment]
Hey @Moult I tried the file on Blenderbim 230518 (yesterday's build)

and it printed perfectly:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/c863d60d-84dd-4664-876a-508f11f8acce)

Let me have a look at removing that line from  230529 and see if it is the same

**Comment by Plae-Blue-Dot** [comment]
Hey @Moult That is definitely it,
I removed the line from 230529 and the resulting svg is perfect:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/6c384c63-8734-44d0-92b9-fd809b902eaf)

**Comment by myoualid** [comment]
Mmhh..I find it logical not drawing objects that are hidden from render view. Can't we just make sure all objects we want to print aren't hidden from render view? 
Should we have a bool prop asking the user if objects hidden from view should not be printed? fits well with the sequence animations
