### ISSUE TITLE
*Question* BCF Extensions V2 <-> V3 Differences

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#3220]
I noticed that the bcf library within ifcopenshell handles the project extensions differently across v2 and v3.   V2 seems to just return the schema itself, whereas v3 returns the extension class.  Is there a reason why v2 can't also return the extension class?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/83825269/b8ed23aa-2291-4b84-8b8c-9fa6335eb8b3)

**Comment by Moult** [comment]
In V2 extensions were not implemented originally. I wasn't there for the history on how this evolved over time ping @sanzoghenzo but potentially it could use an upgrade :)

PR welcome unless there is an explanation.

**Comment by vulevukusej** [comment]
Ok, I thought it'd be something along these lines.  Happy to make a PR once confirmed.

**Comment by sanzoghenzo** [comment]
Yeah, I didn't put much effort on the extension part since I didn't have a use case of my own and I was too lazy to look for examples 😅 

The thing is, v2 doesn't have an xsd file for the extension schema, and thats why there is no class and no parsing.
I didn't know how to handle that (and most probably I didn't spent much time looking for a solution, like I said I don'tuse extensions yet)

**Comment by vulevukusej** [comment]
I downloaded the v2.1 release to see what was defined there and saw the following in the markup.xsd file:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/83825269/9f60d413-9490-4d3e-9d11-c4a803d4a5f1)

as well as a way to redefine the types in extensions.xsd:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/83825269/f2efb1b7-8dbb-490b-94d0-4e4ca5114231)

**Comment by sanzoghenzo** [comment]
My bad, I believe I didn't see the "Extension Schemas" folder in the github repo! Im away from the pc until monday, so I will not be able to provide a quick fix.

If you want to try this yourself, you can place the extensions.xsd file in the `bcf\v2\xsd` folder and run `make models` to create the missing dataclasses, then go ahead and fix the bcfxml class! 😉

**Comment by vulevukusej** [comment]
@sanzoghenzo cool, thanks I'll give it a shot :)
