### ISSUE TITLE
(Question) - Why are viewpoints stored in the topic folders?

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#3221]
Crossposting the same question asked at https://github.com/buildingSMART/BCF-XML/issues/362

> I'm curious why the viewpoints aren't simply expected to be in the main bcfzip archive, instead of separately stored inside the topic folders? It seems reasonable to expect a 1:n relationship between viewpoints and topics.

**Comment by Moult** [comment]
Interesting question but not sure what we can do about it here in this repo - it's not exactly a bug or something we can change on our end, that's just how the schema was designed.
