### ISSUE TITLE
When creating a new Plan/Body/PLAN_VIEW context, don't automatically use Model/Body/MODEL_VIEW

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3223]
Let's say you have a pretty complicated tessellation mesh in Model/Body/MODEL_VIEW, and you add a new context Plan/Body/PLAN_VIEW to create a simpler plan representation. 

Currently BB, converts or flattens Model/Body/MODEL_VIEW down to 2D, this process, however, is often quite CPU intensive and is often times too complicated to work with anyway. 

I would like to propose that BB doesn't automatically convert/flatten, and allows the user just to add the necessary geometry they need. 
Or at the very least, BB prompts the user if they'd like to flatten the Model/Body/MODEL_VIEW geometry or start anew.

**Comment by theoryshaw** [comment]
I do like the automation of a 2d plan from 3D, perhaps a process like the following could be hardcodied in BB, to create the outline. 

https://www.youtube.com/watch?v=qqTz_kHIQWc

I've actually manually use this, and converted the grease pencil to a mesh, and then added it to the Plan/Body/PLAN_VIEW context. 
Works pretty well.

**Comment by brunopostle** [comment]
I was creating Profile/ELEVATION representations for windows/doors yesterday, and each time it was taking about ten minutes to generate the new representation (and ultimately it was just a wireframe version of the tessellation).

**Comment by theoryshaw** [comment]
Is there a relatively easy way to turn off the automatic flattening?  This kills my computer, and major productivity suck.
