### ISSUE TITLE
Add a button in the profile editor interface to purge unused profiles

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3225]
Following https://community.osarch.org/discussion/1490/removing-with-ifcopenshell-util-element-remove-deep2#latest

Add a button in the profile editor interface to purge unused profiles.

Similarly, maybe add somewhere in the interface an operator to purge unused representations, unused type definitions, etc. ? Suggestions welcome.

**Comment by Moult** [comment]
I reckon purging types is useful in the type manager (which needs a bit of a design upgrade). Purging other more esoteric things like unused representations might only be useful in the debug panel.

**Comment by theoryshaw** [comment]
> Similarly, maybe add somewhere in the interface an operator to purge unused representations, unused type definitions, etc. ? Suggestions welcome.

my guy says it would fit under the 'IFC Quality Control' panel.... in a new category perhaps, called `Purge`.

**Comment by Gorgious56** [comment]
Completed with a8126a6
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/4447670f-a4cf-46d7-814f-288fa8445fd8)

Other types of purges can go in this sub-panel, I may add them if the need arises while I use bbim. Feel free to otherwise. We can also add a "make this file lighter" button with all the possible purges run automatically ?
