### ISSUE TITLE
To not hide a linked blender/ifc in a drawing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3227]
When you use `bim.link_ifc` to link a blender/ifc file, and then use `bim.activate_drawing` it automatically hides the link even if there's nothing in the `Exclude` property.

**Comment by myoualid** [comment]
Could you try to replicate this again please @theoryshaw ? It no longer happens to me, and it used to. Perhaps it's been fixed in the last commits related to IFC links
