### ISSUE TITLE
Building IfcGeom/IfcParser with /MD

### ISSUE THREAD

**Issue by Kuraperunat** [IfcOpenShell/IfcOpenShell#324]
Has there been any progress on building IfcOpenShell (particularly IfcGeom and IfcParse) with /MD as a DLL? There's an old comment on sourceforge (https://sourceforge.net/p/ifcopenshell/discussion/1782718/thread/16060c7a/) talking about plans to do this, but I can't find anything related in the build scripts.

If it's still in the same state, would it be possible to get some more info on hacking the build scripts for this? The scripts are a bit large to approach via trial & error.

**Comment by Stinkfist0** [comment]
This should get you started:

Dependencies:
- remove `runtime-link=static`: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L185
- set `USE_STATIC_MSVC_RUNTIME=0`: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L237, https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L359
- for ICU, I think the you need to compile and deploy it manually
 
IfcOpenShell:
- comment out line https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L113
 - comment out lines 401-410 https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L401

**Comment by Kuraperunat** [comment]
Thanks for the help, I managed to get the DLLs built. In addition to those I had to build OCCT manually using /MD and copying the libraries over the MT ones. Additionally I changed the cmake file "sicu*.lib" copy commands to use the /MD "icu*.lib" versions and they seem to work fine.

I've encountered a fatal performance issue though. It seems that iterating the _IfcGeom::Iterator<double>_  is running second order magnitudes slower than the prebuilt exe. It's taking at least 15 minutes to iterate the geometry in a file that takes 3 seconds to convert for the prebuilt binaries.

I made sure to use Release configuration for all the dependencies, have played around with the iterator settings and have turned on all the optimizations to no effect. I'll continue to debug this next week, but I imagine just having the code dynamically linked shouldn't have that much of an effect? Or is it possible there are some inline optimizations ignored with dynamic linking?

**Comment by Stinkfist0** [comment]
Does enabling this help https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L26

**Comment by Kuraperunat** [comment]
If I recall correctly I did use that flag, but I'll be returning to this on Monday to double check and do more extensive debugging. At the very least I did make sure /Ob2 /GL /LTCG were on for IfcGeom/IfcParse when testing but they didn't help.

**Comment by aothms** [comment]
Did you use static or dynamic OCCT libs? My premonition is that effective optimization depends on many OCCT calls being inlined, which will likely happen less for dynamic libs.

This mentioned performance difference is bigger than I'd expect though and might indeed hint at optimizations for OCCT/IfcOpenShell/both absent.

**Comment by Kuraperunat** [comment]
I'm using dynamic libs as mixing /MT and /MD doesn't compile and my host application is compiled with /MD. I made sure to enable every optimization in every dependency, but it doesn't seem to be doing much except bloating OCCT libs to 10gb. The performance difference is indeed quite drastic, making me believe the issue could be elsewhere.

The code I'm using for reading is short enough to not leave much room for error.

```
		IfcParse::IfcFile ifc_file;
		if (!ifc_file.Init(filePath)) die("Reading ifc file failed");

		IfcGeom::IteratorSettings settings;
		settings.set(IfcGeom::IteratorSettings::APPLY_DEFAULT_MATERIALS, true);
		settings.set(IfcGeom::IteratorSettings::USE_WORLD_COORDS, false);
		settings.set(IfcGeom::IteratorSettings::WELD_VERTICES, false);
		settings.set(IfcGeom::IteratorSettings::SEW_SHELLS, false);
		settings.set(IfcGeom::IteratorSettings::CONVERT_BACK_UNITS, false);
		settings.set(IfcGeom::IteratorSettings::DISABLE_OPENING_SUBTRACTIONS, false);
		settings.set(IfcGeom::IteratorSettings::INCLUDE_CURVES, false);
		settings.set(IfcGeom::IteratorSettings::EXCLUDE_SOLIDS_AND_SURFACES, false);
		settings.set(IfcGeom::IteratorSettings::APPLY_LAYERSETS, false);
		settings.set(IfcGeom::IteratorSettings::NO_NORMALS, true);
		settings.set(IfcGeom::IteratorSettings::GENERATE_UVS, false);
		settings.set(IfcGeom::IteratorSettings::SEARCH_FLOOR, false);
		settings.set(IfcGeom::IteratorSettings::SITE_LOCAL_PLACEMENT, false);
		settings.set(IfcGeom::IteratorSettings::FASTER_BOOLEANS, true);

		IfcGeom::Iterator<float> context_iterator(settings, &ifc_file);

		if (!context_iterator.initialize()) die("Initializing context iterator failed");

		size_t num_created = 0;

		do {

			IfcGeom::Element<float> *geom_object = context_iterator.get();

			auto obj = static_cast<const IfcGeom::TriangulationElement<float>*>(geom_object);

			...

		} while (++num_created, context_iterator.next());
```

And it's specifically the `context_iterator.next()` causing the slowdown. Is it looking like using /MT is the only way to include IfcOpenShell functionality to a host program?

**Comment by aothms** [comment]
> I'm using dynamic libs as mixing /MT and /MD doesn't compile and my host application is compiled with /MD

Forgive my ignorance, but how does that preclude to compile the OCCT libraries into a `.lib` static library? I thought -MT/D only affects the compiler code generation and not the linker output?

> And it's specifically the context_iterator.next() causing the slowdown.

Yes, that's kind of the onset onto all the geometric operations. Do you think you can provide a more detailed breakdown of the cpu cycles or do your debugging symbols do not allow you to peek inwards? If you're using MSVC 2015 upwards you have pretty comprehensive profiling tools.

**Comment by Kuraperunat** [comment]
> Forgive my ignorance, but how does that preclude to compile the OCCT libraries into a .lib static library? I thought -MT/D only affects the compiler code generation and not the linker output?

My bad, C++ build config lingo still gets me mixed up sometimes. I meant I've used static .lib files with dynamically linked CRT (/MD).

> Yes, that's kind of the onset onto all the geometric operations. Do you think you can provide a more detailed breakdown of the cpu cycles or do your debugging symbols do not allow you to peek inwards? If you're using MSVC 2015 upwards you have pretty comprehensive profiling tools.

I ran quick profiling for the project and it's looking like certain allocators/destructors are taking up most of the time. Here's a screenshot of function listing and call stack for an example run. Let me know if you need more/other details.

[https://i.imgur.com/gcFq2PS.png](url)
[https://i.imgur.com/BaSBZlT.png](url)

I'm starting to lean towards using the IfcConverter or IfcGeomServer exe from my application even though I feel like it's a little bit less elegant solution.

**Comment by aothms** [comment]
Thanks for that.

> I'm starting to lean towards using the IfcConverter or IfcGeomServer exe from my application even though I feel like it's a little bit less elegant solution.

It's what quite a lot of people do. It makes things modular, safe and makes sure there are no resource leaks. But of course there are downsides too.

Over 50% of time is spent in the meshing, it seems. That is surprising, most building models are simple planar structures that require a minimal amount of operation to obtain triangle meshes. Are you testing on a specific exotic model? Do you get similar results for, for example, the duplex model [1] [2]?

[1] http://projects.buildingsmartalliance.org/files/?artifact_id=4278
[2] http://www.nibs.org/?page=bsa_commonbimfiles#project1

If it's really specific to memory allocation, you're not getting a fault tolerant heap [3] or something right for your own application?

[3] https://msdn.microsoft.com/en-us/library/windows/desktop/dd744764(v=vs.85).aspx

**Comment by Kuraperunat** [comment]
Trying the duplex model yielded similar results as before; the iteration goes incredibly slowly.
Profiler: https://i.imgur.com/QejQUrL.png

I'll try disabling FTH tomorrow and if it doesn't work out I'll likely settle with the executables.

**Comment by Kuraperunat** [comment]
Disabling FTH did not have any noticeable impact on the performance. I've started using the executable for conversions and it's working fine so far.

I'm closing the issue as the original issue got solved. Maybe a new one could be in order if someone can replicate the performance issues.

Thanks for the help!

**Comment by aothms** [comment]
Ok, unfortunate that we didn;t get to the root of these issues. Let me know if you encounter other issues.
