### ISSUE TITLE
Exception Handling Error

### ISSUE THREAD

**Issue by ta2x30** [IfcOpenShell/IfcOpenShell#3249]
It appears there is an exception handling error when the BenderBim add-on is enabled.
I am running version 230506 on a MacBook Air M1.
Error log. is captured and attached.
<img width="1256" alt="Screenshot 2023-06-03 at 6 15 24 PM" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/44478995/5c5c3476-57e8-4d49-9a01-e709a24d00a7">

**Comment by Moult** [comment]
Which version did you download and from where?

**Comment by ta2x30** [comment]
It was blenderbim-230506-py310-macosm1 from BlenderBim.org/download.

**Comment by ta2x30** [comment]
I am running Python 3.9.6, but the zip file name seems to suggest 3.10 was built for. I am wondering if it matters in any ways?

**Comment by ta2x30** [comment]
Apparently similar problem with the latest built blenderbim-230603-py39-macos downloaded from https://github.com/IfcOpenShell/IfcOpenShell/releases?page=1
Error log attached
 
<img width="1435" alt="Screenshot 2023-06-04 at 6 58 47 AM" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/44478995/771e0924-a18c-4f61-a3d6-5ccb296aab0a">

**Comment by ta2x30** [comment]
I upgraded python to Python 3.11.3
and used blenderbim-230506-py310-macosm1.zip. It seems to have solved the problem
