### ISSUE TITLE
IFC4X1 support

### ISSUE THREAD

**Issue by JenniferZh** [IfcOpenShell/IfcOpenShell#325]
Hi,

I'm working around an infrastructure project which needs a viewer supporting IFC4X1. I found IfcOpenShell project from your website article(http://academy.ifcopenshell.org/using-ifcopenshell-and-c-to-generate-alignments-through-the-ifc-4x1-schema/).

I've tried to generate ifc4x1 files by IfcExpressparser and build the whole project, and my ifc4x1 test file can be parsed to xml by IfcConverter. However, I guess  some properties of IfcAlignment are missing in the xml file. In addittion, the geometry information of IfcAlignment is not generated.

I wonder if there is any plans about supporting ifc4x1 geometry in the future?  or any suggestions about developing IfcAlignment geometry? 

Thanks a lot!!

**Comment by aothms** [comment]
> However, I guess some properties of IfcAlignment are missing in the xml file

Probably, there's some specific cases being included here: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/XmlSerializer.cpp#L66 What specifically is missing?

> In addittion, the geometry information of IfcAlignment is not generated

So, there's probably three parts to this (a) you need to specifically enable curve geometries to be emitted [1] (b) there's the alignment specific 2d curves that need to get conversion functions similar to [2], note that e.g. clothoid will probably have to be approximated as nurbs/arc/line segments (c) the the pair of horizontal and vertical curves can be converted to 3d using e.g. [3]

It's not a major effort, but I don't have the time to drive this. I can provide feedback and suggestions if needed.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomIteratorSettings.h#L69
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcRegister.h#L107
[3] https://www.opencascade.com/doc/occt-6.9.1/refman/html/class_b_rep_lib.html#ad81df2b9963bb71656df2dd92cf8865c

**Comment by JenniferZh** [comment]
Thanks for your reply! It helps me a lot.
