### ISSUE TITLE
An IFC saved with a relative path, changes back to a absolute path, after opening again, and saving. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3251]
An IFC saved with a relative path, changes back to a absolute path, after opening again, and saving. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/05b7d640-7e86-468a-b7dd-f49563f69d0d

**Comment by Andrej730** [comment]
Fixed.
Turn out blender operators props are reseted every time you reopen .blend file 🙃
Wonder if have similar issues elsewhere.
