### ISSUE TITLE
Boolean results intersection/subtraction inverted

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#3255]
This is a recent IfcOpenShell issue, probably from d7c3b5a

The IfcSpace entities in this model have the ceilings clipped with half-space solids: 
[space-clipping.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11646631/space-clipping.ifc.zip)

Using an IfcOpenShell build from 20th May, the spaces look like this:

![Screenshot from 2023-06-04 21-42-41](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/afdb3960-a0cb-461c-a86b-298ef185dbe8)

..but with an IfcOpenShell build from today, the clipping result is inverted:

![Screenshot from 2023-06-04 21-38-31](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/850e797e-94b2-41ac-9639-ba1fc314d22e)

**Comment by aothms** [comment]
Oops, that was silly, thanks for the clear report.

Somewhat interesting that you use IFCBOOLEANRESULT with INTERSECTION. It's mathematically the same, but IFC has a specific class for the IfcBooleanClippingResult with a halfspace that used to be in IFC2X3 Coordination View, so might have better support in software.

**Comment by brunopostle** [comment]
Thanks, seems to be fixed with a current build, closing..
