### ISSUE TITLE
IfcConvert single material names resolves to element type

### ISSUE THREAD

**Issue by wcoebergh** [IfcOpenShell/IfcOpenShell#326]
Using IfcConvert, it looks like material names used for Collada materials resolve to the Object IfcType when there is a single material:

```xml
<material id="IfcWall">
  <instance_effect url="#IfcWall-fx"/>
</material>
<material id="surface-style-466-hout---vuren-hor.-nerf">
  <instance_effect url="#surface-style-466-hout---vuren-hor.-nerf-fx"/>
</material>
<material id="surface-style-1213-glas---algemeen">
  <instance_effect url="#surface-style-1213-glas---algemeen-fx"/>
</material>
<material id="IfcCovering">
  <instance_effect url="#IfcCovering-fx"/>
</material>
<material id="IfcColumn">
  <instance_effect url="#IfcColumn-fx"/>
</material>
```

All walls, columns and coverings have the IfcType as material.

Also these materials:

```xml
<material id="IfcWall">
  <instance_effect url="#IfcWall-fx"/>
</material>
<material id="IfcCovering">
  <instance_effect url="#IfcCovering-fx"/>
</material>
<material id="IfcColumn">
  <instance_effect url="#IfcColumn-fx"/>
</material>
```

Have an instance effect with color 0.9 0.9 0.9 1 (grey)

This occurs for me with IfcConvert 040 (Linux) IfcConvert 050rev2 (Linux and Mac)

Regards

**Comment by wcoebergh** [comment]
Forgot to mention that also these materials:

```xml
<material id="IfcWall">
  <instance_effect url="#IfcWall-fx"/>
</material>
<material id="IfcCovering">
  <instance_effect url="#IfcCovering-fx"/>
</material>
<material id="IfcColumn">
  <instance_effect url="#IfcColumn-fx"/>
</material>
```

Have an instance effect with color _0.9 0.9 0.9 1_ (grey)

**Comment by Stinkfist0** [comment]
Having the IFC type name as the material name is a sign that the object didn't have material/style assigned and a default material/style is used. BTW if you want to use the actual material names instead of "material IDs" you can pass the `--use-material-names` parameter to IfcConvert.

**Comment by Moult** [comment]
Closing as from the explanation from @Stinkfist0 this seems to be a file data quality issue as opposed to a bug in IfcConvert.
