### ISSUE TITLE
IFC Convert - Json Conversion

### ISSUE THREAD

**Issue by Pourfex** [IfcOpenShell/IfcOpenShell#3264]
Hello,

Wanted to know if there is anything on the Roadmap to convert IFC to JSON with IFCConvert as IFCConvert is doing with xml.
This would be mostly used for accessing properties, hierarchy and structure of IFC.

Thanks in Advance.

**Comment by Moult** [comment]
This already exists and uses ifcopenshell, just not stored in this repository: https://github.com/buildingSMART/ifcJSON/tree/master/file_converters

Note that you can access only properties, hierarchy / structure / relationships using any format including .ifc, .ifcxml, .ifcjson. You don't need to limit yourself to json for that.

**Comment by Moult** [comment]
I've updated the docs to describe the multitude of ways you can use IfcOpenShell to convert to and from various formats.

![2023-06-07-141929_1348x1010_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/388b309d-e12d-46b1-9f7a-544bf2d5026b)

**Comment by Pourfex** [comment]
Thanks ! Update of the doc is really helpfull !

**Comment by aothms** [comment]
In ifc-pipeline / view.ifcopenshell.org we also have a small script that takes the XML and converts it to JSON https://github.com/AECgeeks/ifc-pipeline/blob/master/application/process_xml_to_json.py

**Comment by Moult** [comment]
There's also https://pypi.org/project/xmltodict/ which is pretty awesome and I use it all the time especially on APIs who insist on delivering XML :)

**Comment by Pourfex** [comment]
@aothms Would it be relevant to add this to IFCConvert ? It'll somehow generalize how json is produce for ifc open shell users (we made our own parser when 4.0 came out, and now we want to support 4.3). IFCConvert to json would be the "de facto" standard for ifcopenshell users and it'll follow version. 
Testing both of your lib right now.

**Comment by aothms** [comment]
I wouldn't be opposed to it, if in IfcConvert we can use the logic of the existing Serializer and simply create an abstraction over the serialization between XML and JSON. If we would have to duplicate the full logic of the serializer I think the having it as a post-processing step is more sensible.

So everywhere where we use `ptree` [0] we would have to create an abstraction that selects either `ptree` or `nlohmann::json`. Are you interested in working on this, we are here to support of course.

[0] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/schema_dependent/XmlSerializer.cpp
