### ISSUE TITLE
Quick way to select objects with certain property values

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3268]
Would be nice if there was a select button, like the mock up below, that allowed you to select all the objects in the scene that have that particular property value. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/1b739c67-8300-4b1c-9afc-f5715adf8692)

**Comment by brunoperdigao** [comment]
I'll try that

**Comment by theoryshaw** [comment]
This is awesome!

Seems like there's a couple inconsistent bugs on this file, however...


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/8e6b4021-4497-40b3-b841-9cb664ca09ad

**Comment by theoryshaw** [comment]
On this file, i get more errors, for whatever reason...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ef13c99a-6615-4636-856a-6ad5f08bcb9b

**Comment by brunoperdigao** [comment]
I'm going to check that

**Comment by theoryshaw** [comment]
I would except just the class, not all the classes. 

Although an alt-click, for all of them, would be nice! ha. :)

**Comment by Moult** [comment]
Do these errors still exist? Reopening in case they are. Can you confirm?

**Comment by Moult** [comment]
This is now implemented with the new selector panel.
