### ISSUE TITLE
BlenderBim - Window modifier frames are not Uniform - request/issue

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3271]
When printing generated window to SVG the frames are asymmetrical:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/2f0ffa36-4357-4d2d-80ff-e04112e27fbb)

The expectation is that they are symmetrical / uniform like this:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/43943e53-c62d-4023-94b4-d4532fe45b2a)

**Comment by Plae-Blue-Dot** [comment]
After looking a bit it's actually the outer frames that aren't uniform, which makes sense to some extent but the preference is for uniformity, 

The inner frames should always shown uniformly/ symetrically

**Comment by Andrej730** [comment]
can please send example .ifc?

**Comment by Plae-Blue-Dot** [comment]
Yes here it is
[North Window - 3 panel.rar.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11679820/North.Window.-.3.panel.rar.txt)

**Comment by Andrej730** [comment]
For example here's the default double vertical panel. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/79b081a7-2c45-48d1-8666-f707275d8a54)

Basically what algorithm is doing it's trying to maintain 25 mm offset to the lining:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/b515f906-455f-4416-be16-d7754e597869)

The width of the frame we see behind the lining is:
x offset (25 mm) + panel thickness (35mm) - lining thickness (50 mm) = 10 mm

For the mullion part it's:
25 mm + 35 mm - half mullion thickness (50/2=25mm) = 35 mm. So there goes asymmetry.

Noticed that x offset for mullions should be probably divided by 2, it will get a bit better but still:
12.5 mm + 35 mm - half mullion thickness (50/2=25mm) = 22.5 mm

Not sure what would be the correct way to solve that. Any ideas what I'm missing?

**Comment by Plae-Blue-Dot** [comment]
> And another option is to use 0 offset on mullions (0 mm + 35 mm - 25 mm = 10 mm) but then frames are connected at the back. Does it look correct? ![image](https://user-images.githubusercontent.com/9417531/246801485-4db527e5-1ff7-42e0-8674-92d4757800ad.png)
> 
> Not sure what would be the correct way to solve asymmetry. Any ideas what I'm missing?

This one on the right is like the ideal result, it really comes down to the window construction but as a standard this looks the best, what they look like from the back is fine as a standard the front face is way more important

**Comment by Plae-Blue-Dot** [comment]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/e6d34236-c997-49c6-bed2-1fc5fe1a484d)
Realistically this is how this kind of window would be constructed:
- Outer frame would have 5 pieces
- Inner frames would have 4 pieces
- Then if they are opening it would have another inner frame with 4 pieces , 

but for the purposes of drawing readability we often just don't show that or most of this detail, the inner frames just need to be symmetrical to be honest, so even this:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/e7ef8ca1-fde6-4b0f-a43c-6a301aef0726)

Having a thicker centre mullion would be fine it's just half the inner frames appearing different sizes that is problematic.
Depending on the window material and opening it can be done differently but this is a safe bet and doesn't raise flags

**Comment by Andrej730** [comment]
@Plae-Blue-Dot implemented it, though still need to fix lining going through window frames on transoms and mullions

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/56c85ff3-96b6-4d8e-9549-b8d0f67ec0d0)

**Comment by Plae-Blue-Dot** [comment]
Looks good so far @Andrej730 !
