### ISSUE TITLE
BlenderBim - 230607 - viewport annotations / decorations are not displaying

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3272]
Model:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/f442ae14-5423-4944-939e-4f4cc230d923)

SVG:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/1d332e3f-5d8c-4935-9c99-059890eb2520)

Edited to show annotations was checked

**Comment by Plae-Blue-Dot** [comment]
Yes here it is:
[North Window - 3 panel.rar.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11676169/North.Window.-.3.panel.rar.txt)
I tried it on multiple files with the same result, might just be my install

**Comment by Gorgious56** [comment]
Same problem for me.
