### ISSUE TITLE
BlenderBim - Link to sheet gets broken if drawing is renamed - throws an error

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3273]
If you rename a drawing and it is already on a sheet an error will show up and the drawing will no longer be linked to the sheet

Ideally if you rename a drawing it updates the name and preserves the link on the sheet

I can't get this to repeat now but it happened twice earlier using Blenderbim 230607

**Comment by theoryshaw** [comment]
similar problem.  When i rename a drawing, that's already placed on a sheet, and run the sheet, it uses the old svg name in cache.

**Comment by Moult** [comment]
I can't recreate this but as a complete guess this could be something specific to Windows where Windows "locks" files so you can't move / delete them (which we need to do when a rename occurs). Can you try testing again with this potential fix?

**Comment by chopinregis** [comment]
I tested the potential fix but it didn't work. 
Basically to recreate the bug, you must have the drawings already placed on the sheet and positioned how you need them to be presented on sheet. Once you create the sheet and it opens on the browser and working well, now come back to the drawing and rename the drawing to something else, it will also update the drawing name on the sheet. Now if you do the "Create Sheet" this is when the bug occurs. The only way to get around this is to remove the drawing that the name has been changed, and add it again. So if you make significant changes the drawings and need to rename them often for organization purposes, you'll need to do this process again as placing the drawing on the sheet puts it at a default placement.
