### ISSUE TITLE
Camera Raster X & Y not working. Both same direction?

### ISSUE THREAD

**Issue by macedonianluke** [IfcOpenShell/IfcOpenShell#3281]
Fix to view crop region.

**Comment by Gorgious56** [comment]
Hello, could you add more information and a screenshot or diagram to showcase the problem ? Currently it's a bit of a guesswork. Thank you :)

**Comment by macedonianluke** [comment]
![2023-06-08 17_53_22-Window](https://github.com/IfcOpenShell/IfcOpenShell/assets/77250471/d94b2420-dfd9-4e3a-8d82-235ee247643c)

**Comment by macedonianluke** [comment]
I guess its not acting intuitively. Both x and y are changing only one dimension of the view boundary.   Not sure if actual bug or based on the picture ratio format.  If the latter then think that the raster xy should be more intuitive and work alongside the image ratio maybe with the additional ratio as part of the input.

**Comment by macedonianluke** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/assets/77250471/86d0a041-cc5f-4b2c-a737-46ba291b8dac

**Comment by Moult** [comment]
You're right, it is unintuitive (but working as intended). Raster X and Y affects two things: 1) if you have a raster underlay, it affects the actual pixels and thus resolution of that underlay, and 2) it therefore affects the aspect ratio of the camera.

I'd like to replace the Raster X and Raster Y control with a paperspace size in mm or inches, then include a new slider for DPI with a sensible default (75? 150?) which affects the raster resolution.

**Comment by macedonianluke** [comment]
Cool. Sounds good.  Sorry if rehashing, just running through and bringing up what I bump into as main hurdles from a newbies perspective, which may help as 'fresh eyes' on the workflow and help adoption.

**Comment by Moult** [comment]
This is now superseded with actual drawing dimensions so raster x/y no longer apply.
