### ISSUE TITLE
Is there a case where IfcPatch is not applied?

### ISSUE THREAD

**Issue by erinleeme** [IfcOpenShell/IfcOpenShell#3290]
```
python -m ifcpatch -i test.ifc -o output_test.ifc -r OffsetObjectPlacements -a 181194.632851008 517941.184846197 0
```

It is confirmed that the contents of the file have been changed by executing the command as above, but each vertex point is the same. Why is that?
Even though each entity points to a newly added coordinate LocalPlacement. Can you do this?

The picture below shows IFC file data newly created with IfcPatch.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/87467958/a1aca372-4b86-4ae3-89f3-f7906943e4a9)

The method of knowing that each vertex point has not been changed does not follow the coordinates added by each V attribute information when changing to the OBJ format through IfcConvert.

If you look at the OBJ file information, you can see that it has not changed.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/87467958/9376b27d-1c0b-4a6c-917f-80d56847a847)

**Comment by Moult** [comment]
The OffsetObjectPlacements patch https://blenderbim.org/docs-python/autoapi/ifcpatch/recipes/OffsetObjectPlacements/index.html finds all "top level" local placements and offsets them by your parameters. So it will never change the local coordinates of vertices or other parametric solid definitions. Not only is this allowed, this is normal and preferred because the ObjectPlacement of every object is meaningful.

Keep in mind depending on your IfcConvert parameters, you might've chosen to exclude things like building / site position which would ignore the offset that OffsetObjectPlacement provides.

If you believe it isn't working, could you perhaps share a file?

**Comment by erinleeme** [comment]
Other IFC files have been modified, so I was wondering if only certain files could be problematic
Unfortunately, the problematic IFC file cannot be shared, so I think it will be difficult.
I'm sorry.

**Comment by Moult** [comment]
@erinleeme you can share it privately to dion@thinkmoult.com which will only be used for the purposes of debugging.

If you also don't feel comfortable emailing, we can organise a screenshare and you can watch me debug and then delete your file. I'm in the Sydney, Australia time zone.

**Comment by erinleeme** [comment]
Thank you so much for your help.
I attached the IFC file to the dion@thinkmoult.com mail you told me about.
The file capacity is large, so it was sent to the Google Drive link.

**Comment by Moult** [comment]
@erinleeme I just tested it and used the patch to offset by 10000 in the X direction (it's in millimeters) and it works fine on my end, I don't see any issues. Can you elaborate how to replicate your problem?

**Comment by erinleeme** [comment]
I applied the following command as written above, but few coordinate values were not applied.
IfcLocalPlacement corresponds to IFCCARTSESSICAN POINT (205923).344072733,360075.782314558,0.), so shouldn't vertex points be changed based on low coordinate values?

```
python -m ifcpatch -i test.ifc -o output_test.ifc -r OffsetObjectPlacements -a 181194.632851008 517941.184846197 0
```

**Comment by erinleeme** [comment]
When applying the above command, the IFC file was changed to the value applied with the low coordinate value.

**Comment by Moult** [comment]
@erinleeme what's the IfcConvert command you're running?

**Comment by erinleeme** [comment]
@Moult 
It was developed based on IfcConvert, is that a problem?

**Comment by Moult** [comment]
No, I'm saying that you're using IfcConvert to convert the `output_test.ifc` to OBJ, right? What's the command you use? IfcConvert may choose to disregard certain coordinates depending on the arguments you use.

**Comment by erinleeme** [comment]
@Moult I sent the contents to your email address. Please check it out.

**Comment by erinleeme** [comment]
@Moult 
I think I found something!
Looking at the obj file, I think we can multiply each v by 1000.
Can it change depending on the IFC distance unit?

**Comment by Moult** [comment]
Oh, I think I know what you mean now. IfcConvert by default uses meters. If you want to use the original, specify the `--convert-back-units` flag as described in the example usages and the documentation: https://blenderbim.org/docs-python/ifcconvert/usage.html#example-commands

**Comment by erinleeme** [comment]
Thank you so much!! I think it's because of that.
