### ISSUE TITLE
Option to batch-reload all external IFC styles

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3293]
Following the awesome addition of https://github.com/IfcOpenShell/IfcOpenShell/commit/04fe2bdf2eec4a22b52273a3e2d67ab53d52253b 

Currently AFAIK one has to individually reload all external IFC styles when there has been changed or when the ifc / blend link has been lost.
It would be nice to have the option to automatically load external styles when loading an ifc file, maybe under "Advanced mode" when loading an ifc file

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/f89bd057-10ae-49f9-87b4-1f8e27743da8)

Or directly in the blend file when the ifc file is already loaded, with a button. There is no workspace dedicated to "Material Manager" so it would either need to be in the Material properties or in the Scene Properties inside Ifc Styles ?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/6fc3e716-ad25-406e-b855-40236075393c)

**Comment by Andrej730** [comment]
Currently all styles can be updated by this switch in N-panel
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/a565f9e5-7116-4e85-bbd7-57727eca9fdb)
PS Probably should make it clear in UI that it changes all styles and not just active object style

**Comment by Gorgious56** [comment]
Woot! Nice, yeah it's a bit hidden currently. I'm not sure everyone will be looking for this tool in the Misc. panel. would it be possible to modify the one in the Material panel to act on all materials of all selected objects instead ?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/c7d36197-493c-4a0e-aeb8-f90959f2c5c3)

Also maybe think about making it look like a button, I feel like messing with enum properties rarely have that much of a side effect in Blender and Blenderbim in general, so I don't think the average user will understand what this does under the hood.

**Comment by Andrej730** [comment]
Added reload button, now it's more intuitive. 
Reload button also updates style for selected objects but this is one a bit confusing for me - I mean from Blender UX POV seems that using any buttons from properties section should affect only selected object, not multiple selected objects. But it is useful and we do similar thing somewhere in BBIM already.
