### ISSUE TITLE
IfcDoor and IfcWindow modifiers : Assign different materials to the frame, panel and window

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3295]
Following a suggestion from https://community.osarch.org/discussion/1525/blenderbim-ifcmaterials-on-parametric-ifcwindows#latest which I find interesting.

It would be nice to be able to setup a material for the frame, panel and glass (sorry not an expert on woordworking linguo) separately to be able to style the elements correctly. Currently it's only possible to assign a single material if one wants to keep the object parametric and editable. Would be nice to have somewhere in the modifier properties to assign the materials or styles.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/de24ab74-a15e-403f-8c03-feecb0caf4ba)

**Comment by theoryshaw** [comment]
+1
related: https://github.com/IfcOpenShell/IfcOpenShell/issues/2981

**Comment by Gorgious56** [comment]
Ups sorry I searched for similar issues but didn't go far enough >< That's exactly the same feature request ! Cheers

**Comment by theoryshaw** [comment]
No worries, the more, the merry.

**Comment by Andrej730** [comment]
also requested here - https://community.osarch.org/discussion/1525/blenderbim-ifcmaterials-on-parametric-ifcwindows#latest

**Comment by Andrej730** [comment]
closed as the same issue as #2981
