### ISSUE TITLE
Have the array modifier sync property sets, as well. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3298]
Would be nice if the array modifier synced property sets, as well.

**Comment by brunoperdigao** [comment]
I was checking this and it already works that way. I don't know if it was implemented after the issue, or if I'm missing something.

**Comment by Andrej730** [comment]
I noticed some issue with updating psets for already created array elements.
1) Create a window, add Pset_WindowCommon and set some status
2) Add an array of 2 elements. Created array child element will have similar pset and same status.
3) Change status in array parent.
4) Change number of element in array to 3. Newly created element will have status from step 3, previously created window will still have status from step 1.

@theoryshaw is this the issue what I've described or there was something else also?

**Comment by theoryshaw** [comment]
I think you need to 'Sync Children' for the pset to update. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ba699cbb-ee76-4ab0-8478-00b52c66d391)

If that works for you.  I 'think' this issue is resolved.  I just forgot to follow up on it.

**Comment by Andrej730** [comment]
Oh, missed it. "Sync children" works - so to update psets just need to enable editing array parameters and apply them. 
I'll close this for now then.
