### ISSUE TITLE
Error Logging reporting (geometrical) objects GUIDs.

### ISSUE THREAD

**Issue by iras** [IfcOpenShell/IfcOpenShell#33]
Hi,

The current IfcOpenShell's error log correctly reports the IFC file line numbers where the issue manifested itself while exporting the geometry.

That is fine except that those STEP ids are very local within each (geometrical) object's description in the IFC file and don't match any of the GUIDs/names of the objects exported so there's little room to quickly point at which (geometry) object has been affected by the reported issue (partial or total conversion fail).

It would be quite helpful if the GUID of the object with _internal_ issues was added to the error log too.

Thanks.

**Comment by aothms** [comment]
Hi Ivano, that's a good suggestion, will add it.

**Comment by iras** [comment]
+1

**Comment by iras** [comment]
I had a try [here](https://github.com/iras/IfcOpenShell-1/commit/65a95b409d16edb6f7b457e085a20e2ec23d7942) but some extrude errors seemed to slip out...

**Comment by aothms** [comment]
My idea would be to implement a Logger::SetProduct(boost::optional<IfcSchema::IfcProduct>) method being called here [1] and whenever a log message is actually being emitted, preprint the product in some formatting. Logger should eventually be more versatile and log e.g. to text files / xml and not only stdout/err. This way the applicable product can be in a separate xml node for example.

[1] https://github.com/iras/IfcOpenShell-1/commit/65a95b409d16edb6f7b457e085a20e2ec23d7942#diff-57b7368a1b4282832b5eaad8802b0dc3R363

**Comment by iras** [comment]
It sounds good to me. Would you be up for adding a _temporary_ new branch in github.com/IfcOpenShell/IfcOpenShell called error_logger with the change you proposed so I can test it out on some of my IFC files ?
