### ISSUE TITLE
Segfault on Slab with OCCT 7.2.0 (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#331]
Steps to reproduce:

1. Convert [331--slab--segfault--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/331--slab--segfault--augmented.ifc) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```
3. File opens without warning in Solibri and DDS:
<img width="200" alt="screen shot 2018-02-23 at 16 06 01" src="https://user-images.githubusercontent.com/4601554/36600775-77e1b108-18b3-11e8-99d4-cfd5b3c5bec7.png">

This also happens on 8d0c95a9391f887e262e95cec646dca2c59ceadf (OCCT v7.2.0), ~~but I have not tried on another version of OCCT, yet.~~~

Update: this does not segfault when using with OCCT v7.1.0, so this is seemingly a regression related to use with OCCT v7.2.0 specifically.

**Comment by aothms** [comment]
I don't get a segfault with this (on Windows at least, but I can imagine that depends on all sorts of things including phase of the moon), but I do get failure message on the boolean operand. This file wants to subtract the red volume (moved up a bit) from the green volume. Red is a planar faceset, green an extrusion with curved segments. Other than that the boolean operands are pretty much fitting exactly (intersection is more or less empty). These kinds of operations are really asking for trouble in OCCT.

![2018-03-10 9](https://user-images.githubusercontent.com/1096535/37241539-1bd2ed2e-245b-11e8-99cd-1d9d152dd408.png)

**Comment by johanrd** [comment]
Closing, as this is not reproducible anymore when building from commit 1f68d9d5bcfda6ce6b7ff6e86733faf835247242

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
