### ISSUE TITLE
in C++，why I can't set new coordinate. 

### ISSUE THREAD

**Issue by 99zhu** [IfcOpenShell/IfcOpenShell#3319]
I want modify coordinate,the coordinate show modify ok,but in  .ifc  coordinate is not modify.
it's my means have problem or something else?
thanks.
![coordinate](https://github.com/IfcOpenShell/IfcOpenShell/assets/127181262/871e2faf-76a1-49a5-9860-bfc18d4fe257)

**Comment by aothms** [comment]
The return type is `std::vector< double > /*[1:3]*/ Coordinates() const`; Not `const std::vector< double >&` so with this code you'll likely get some compiler warning about that. So also no need for the const cast.

You need to set the coordinates to update them `location->setCoordinates(coordinates)`.

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/examples/IfcOpenHouse.cpp#L522-L523

**Comment by Moult** [comment]
@99zhu is your issue resolved?

**Comment by 99zhu** [comment]
> 

yes, thanks
