### ISSUE TITLE
IDS Validation Error

### ISSUE THREAD

**Issue by Yoshiyuki-Miyauchi** [IfcOpenShell/IfcOpenShell#3320]
I am checking custom property information in reinforcement data (IfcReinfocingBar) with IDS.
I have specified the custom property information in the reinforcement data (IfcReinfocingBar) in IfcText, but for some reason it throws up the error "The data type IfcText does not match the requirements. " error.

Also, I want it to look at the IfcPropertySet line, but it is looking at the IfcReinfocingBar line and giving me an error that it is not specified in IfcText.

ODA's Open IFC Viewer's IDS validation and ACCA's IDS validation do not cause such an error.

**Comment by Moult** [comment]
@Yoshiyuki-Miyauchi it sounds like the property is IfcText, but your IDS has measure="something" which is not IfcText. Can you share your IDS file? (or just the portion of it with the property facet?)

**Comment by Yoshiyuki-Miyauchi** [comment]
@Moult 
Hi,
For now, the following code describes the IDS.
Please check it out if you would like to see it.

  <ids:specifications>
    <ids:specification ifcVersion="IFC2X3" name="属性情報4_オブジェクト分類名（IfcReinforcingBar）" minOccurs="1" maxOccurs="unbounded" identifier="06" description="オブジェクト分類名の入力確認" instructions="None">
      <ids:applicability>
        <ids:entity>
          <ids:name>
            <ids:simpleValue>IFCREINFORCINGBAR</ids:simpleValue>
          </ids:name>
        </ids:entity>
      </ids:applicability>
      <ids:requirements>
        <ids:property minOccurs="1" maxOccurs="1">
          <ids:propertySet>
            <ids:simpleValue>階層4_属性情報</ids:simpleValue>
          </ids:propertySet>
          <ids:name>
            <ids:simpleValue>オブジェクト分類名</ids:simpleValue>
          </ids:name>
          <ids:value>
            <ids:simpleValue>鉄筋</ids:simpleValue>
          </ids:value>
        </ids:property>
      </ids:requirements>
    </ids:specification>
  </ids:specifications>`

**Comment by Moult** [comment]
@Yoshiyuki-Miyauchi yep, as you can see your IDS file's property element is missing a measure="" attribute. This is mandatory: https://github.com/buildingSMART/IDS/blob/master/Development/ids.xsd#L93 - it's also marked as required in the docs (called Data Type): https://github.com/buildingSMART/IDS/blob/master/Documentation/property-facet.md#parameters

Add something like measure="IfcText" to fix it.

If ODA's Open IFC Viewer's IDS validation and ACCA's IDS validation do not cause such an error, then they have a bug. I'd recommend reporting to ODA / ACCA.

**Comment by Yoshiyuki-Miyauchi** [comment]
@Moult 
Wow...
I didn't notice much from a user's perspective.
Good thing I tried different software to see how IDS behaves.
I would not have noticed these if I had not checked for errors in IfcTester.
Thank you very much.

**Comment by aothms** [comment]
Keep in mind that the IDS schema is still under development, so it's not surprising to see some implementation differences among vendors. In the coming months we'll likely see things mature. Have a look at https://github.com/buildingSMART/IDS-Audit-tool Which will also do validation outside of the schema constraints.
