### ISSUE TITLE
Issue-4D Simulation-IFC Costing and Scheduling Option

### ISSUE THREAD

**Issue by ashwinbim** [IfcOpenShell/IfcOpenShell#3324]
Hi,

Im facing the problem.

In IFC Works Schedules data (Imported by Me XER FILE) initially showing correct and im Assigned the task with IFC ICOM but once saved & close or save as file mean inside imported XER Schedule data missing.

Then Can't modifying the already Assigned task & schedule data.

**Comment by Moult** [comment]
Hey, I don't fully understand your question. Are you sure you actually saved the IFC and not just the blend? How can I recreate your issue?

**Comment by ashwinbim** [comment]
for BlenderBIM in 4D.

In **IFC Works Schedules data** 

Example ,
initally in imported IFC Schema 4 file and imported Schedule file (XER) and I linking task and schedule with **IFC ICOM** 
Once save and reopen/ Saveas means I can't edit and seen my imported xer file.

**Comment by Moult** [comment]
Are you saving and reopening the .blend or the .ifc file? You should save and reopen the .ifc. Do not save and reopen .blend files.

**Comment by ashwinbim** [comment]
I'm reopening in .blender file. how to save the file as IFC and how to open the IFC  file with my saved works

**Comment by ashwinbim** [comment]
Thanks. .ifc file is working
