### ISSUE TITLE
Segfault on wall with OCCT 7.2.0 (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#333]
Steps to reproduce:

1. Convert [333--wall--segfault--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/333--wall--segfault--augmented.ifc) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```
3. File opens without warning in Solibri and DDS:
<img width="200" alt="screen shot 2018-02-23 at 16 50 37" src="https://user-images.githubusercontent.com/4601554/36603116-126ed13c-18ba-11e8-8f40-673f4a79256c.png">

This also happens on 8d0c95a9391f887e262e95cec646dca2c59ceadf (OCCT v7.2.0). ~~Not tried on another version of OCCT.~~ Update: this does not segfault when using with OCCT v7.1.0, so this is seemingly a regression related to use with OCCT v7.2.0 specifically.

**Comment by aothms** [comment]
This is a 2360 count shell with opening elements again align with holes that are already there in the explicit shell.

![2018-03-10 10](https://user-images.githubusercontent.com/1096535/37241720-089e1960-245e-11e8-8f10-48ec4262a4e8.png)

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
