### ISSUE TITLE
Select all objects in array modifier

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3331]
Would be nice if the array modifier had a select all objects in array. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/7747dffc-bfdf-45d0-92cc-45a99b551754)

**Comment by Andrej730** [comment]
but why? I thought the premise of the array is exactly that you work only with the main object and instances just follow

**Comment by Moult** [comment]
It also has other usecases, like selecting to hide / colour / isolate.

**Comment by Moult** [comment]
@brunoperdigao this is a nice straightforward one, would you like to try?

**Comment by brunoperdigao** [comment]
@Moult Yes, I'll take this
