### ISSUE TITLE
If an array modifier is removed gives the user the option to keep all the instances in the scene, or remove them all together. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3332]
Would be nice if an array modifier is removed that it gives the user the option to keep all the instances in the scene, or remove them all together. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/86c812b4-a585-422b-bfe7-1a8c5b7ff9d0)

**Comment by brunoperdigao** [comment]
I can try that if no one is working on it. This is relatively easy if you have only one array, but gets a little complicated with multiple arrays combination.

**Comment by Moult** [comment]
Is this now resolved?

**Comment by theoryshaw** [comment]
feels good to me. :)
