### ISSUE TITLE
A button that would activate the drawing like `bim.activate_drawing`, but does not relocate the camera location. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3333]
Would be nice if there was a button that would activate the drawing like `bim.activate_drawing`, but does not relocate the camera location. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3d5bfabb-ca56-4d97-b3e8-12928870114d)

**Comment by Andrej730** [comment]
what a nice issue number 😁

**Comment by theoryshaw** [comment]
Nice!

**Comment by theoryshaw** [comment]
Hi @Andrej730 
This functionality doesn't seem to work anymore.

**Comment by theoryshaw** [comment]
Thanks @Moult for looking at this, but this doesn't seem work the way it used to. 
It would activate the drawing, but **not** relocate the camera. 
Currently it relocates the camera.

**Comment by Moult** [comment]
Are you sure you gave the latest build and are not mixing up alt and shift? One only shows from the camera view, and the other activates but shouldn't move the camera as you say.

**Comment by theoryshaw** [comment]
i think i do...


https://github.com/user-attachments/assets/b4018134-0fc4-49e3-9883-53aefa31a9b3
