### ISSUE TITLE
Have `bim.activate_drawing` hide/show `Disable in Renders` as well.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3338]
Currently, when `bim.activate_drawing` it hides/shows 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/35b17659-4420-49f5-860b-3ee82d099a94)
an object based on include/exclude.  
Would it be possible for it to hide/show the `Disable in Renders` 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/e71d0b99-af66-4457-bd1e-507487d089b1)
 too? 

files: https://www.dropbox.com/s/1ps5blsxmmw0n3z/Restaurant_Livingston.zip?dl=1

**Comment by Andrej730** [comment]
> Upon further testing, it seems Disable in Renders is turned off correctly w/ bim.activate_drawing, but it doesn't seem to turn on.

Nice catch, that helped
