### ISSUE TITLE
Preferences are not remembered from session to session. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3341]
I might be doing something wrong, but these preferences are not remembered from session to session. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/660945d2-2d4f-4ef1-8e3b-1ab1ba82c9d7)

**Comment by Gorgious56** [comment]
You need to save your preferences if you want these settings to be remembered. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/499353ce-0abe-45aa-a989-3790c62c6af9)
 If Blender crashes it won't automatically remember the preferences as they are overwritten globally when you exit Blender, so it might be why it wasn't remembered ? Also, which version are you using ?

**Comment by theoryshaw** [comment]
Thanks, that was it!

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9dd5704a-d1d5-4821-bba9-9da7d6698aa1)

**Comment by theoryshaw** [comment]
...sorry Blender 3.5
