### ISSUE TITLE
A `fill-bg` classes created a double occurrence when printed. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3342]
when this setting is used...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c28adf9d-1ce2-46a7-8f31-788643fa1b13)

...it creates a double occurrence when printed...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f5a3d8ab-1dc1-4323-af24-fe04ebef7333)

**Comment by Andrej730** [comment]
Well, there should be a double occurence otherwise text appears blurred. But offset between them wasn't intentional 😅
