### ISSUE TITLE
What are the possibilities to create a triangle wall in Ifcopenshell c++.

### ISSUE THREAD

**Issue by Theinformatiker** [IfcOpenShell/IfcOpenShell#3343]
It is posible create with 3 points a triangle WALL  see img

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/4ee00499-c06c-4878-9295-94ff305f1b91)

or with 6 points  like secound img

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/70950837/0a33712e-44b1-4005-920d-e49ec0f019f2) 

The area is a rectangle

Keywords: IfcFacetedBrep  ,ifcpolygonalFace

``` c++

IfcSchema::IfcCartesianPoint::list::ptr points(new IfcSchema::IfcCartesianPoint::list);
	points->push(file.addTriplet<IfcSchema::IfcCartesianPoint>(0,0, 0));
	points->push(file.addTriplet<IfcSchema::IfcCartesianPoint>(6,0, 0));
	points->push(file.addTriplet<IfcSchema::IfcCartesianPoint>(3,0,3));
	file.addEntities(points->generalize());

	Ifc4x2::IfcIndexedPolygonalFace* indexPolygonFace;



```

Thank you for your help and support

**Comment by Moult** [comment]
Sure thing! Have you considered using Python for this? If so, you'll find the util and API module helpful.

https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/geometry/index.html

Depending on how you'd prefer the semantics of the geometry, you might consider [add_profile_representation](https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/geometry/add_profile_representation/index.html) or [add_slab_representation](https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/geometry/add_slab_representation/index.html) for 3 points, or [add_sverchok_representation](https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/geometry/add_sverchok_representation/index.html) if you want to specify all 6 points.

You can also use the shape_builder module by first creating a polyline of the 3 points https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/shape_builder.py#L38 and then extrude https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/shape_builder.py#L491

**Comment by aothms** [comment]
In addition, walls are typically extruded vertically. In order to still have a triangular shape generally the idea is to add half spaces that clip the extrusion using a half space plane. See https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/examples/IfcOpenHouse.cpp#L216-L217

**Comment by Theinformatiker** [comment]
The below code  create fistly a normal Wall and then two cliping opoeration?
´´´c++
IfcSchema::IfcProductDefinitionShape* clipped_wall_body_reps[2];
	for (int i = 0; i < 2; ++i) {
		IfcSchema::IfcShapeRepresentation* body = file.addEmptyRepresentation();
		file.addBox(body, 5000, 360, 6000);
		// The wall geometry is clipped using two IfcHalfSpaceSolids, created from an 
		// 'axis 3d placement' that specifies the plane against which the geometry is clipped.
		file.clipRepresentation(body, file.addPlacement3d(-2500, 0, 3000, -1, 0, 1), false);
		file.clipRepresentation(body, file.addPlacement3d(2500, 0, 3000, 1, 0, 1), false);
		setSurfaceColour(file, body, wall_colour);

		IfcSchema::IfcShapeRepresentation* axis = file.addEmptyRepresentation("Axis", "Curve2D");
		file.addAxis(axis, 5000);

		IfcSchema::IfcRepresentation::list::ptr reps(new IfcSchema::IfcRepresentation::list);
		reps->push(body);
		reps->push(axis);
		clipped_wall_body_reps[i] = new IfcSchema::IfcProductDefinitionShape(null, null, reps);
	}

```

**Comment by Moult** [comment]
@Theinformatiker do you need any more help?

**Comment by Theinformatiker** [comment]
No have managed it

thanks for great supports !!!!
