### ISSUE TITLE
Deleting something via the outliner without hotkey, doesn't remove it from the IFC file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3345]
If you delete something via the outliner, it does remove it from the IFC file...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/cfda9a10-1d73-4840-b157-1598ea946f9e

**Comment by Andrej730** [comment]
To override default blender deletion operator we do not override the operator itself but just override hotkey `X`. Therefore if you call delete operator directly from some menu (or if some other blender operator will call it) then it won't remove the object from IFC. 

So the current workaround is to delete only with hotkey `X`.

**Comment by Moult** [comment]
@Andrej730 is it possible to add the IFC Delete option to the right click menu?

**Comment by Andrej730** [comment]
Added it to outliner and object context menus. Ping me if there are other places missing this.
