### ISSUE TITLE
BlenderBim - new spatial tool, add an option for a regenerate button +hotkey

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3348]
At the moment if you adjust the boundary walls and want to regenerate the space you need to change to the BIM tool to do so,

I think allowing one to regen from the spatial tool makes sense:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/53704b16-4164-44a6-8ff9-c6f86bd4dbd9)

**Comment by Moult** [comment]
Fixed by @maxfb87 :) https://github.com/IfcOpenShell/IfcOpenShell/commit/5764cfcbb98e81b2883f3d4195d0148fa02cf159
