### ISSUE TITLE
BlenderBIM user questions

### ISSUE THREAD

**Issue by imebp85** [IfcOpenShell/IfcOpenShell#3355]
Hi! 
I have some general questions about using BlenderBIM:

1. A general Blender question: When searching an element (in an IFC file saved as .blend) by its global ID, it selects the item, but is it possible to make an automatically focus and zoom into the element? How can I do that so I don't have to look for it manually? 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/122728940/19738957-816e-412d-b9e2-384409ce680a)

For example, if I want to automatically zoom that stair selected.

2. In the BlenderBIM `IFC Clash Sets` tool, when using the "Select IFC Clash Results" button and select the json file, it selects all clash results. Is there a way to select each clash separately? 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/122728940/9e478b2b-cf7a-499d-a4be-130e215b6815)

3. Does the BCF library and the "Create Snapshots" option in the `IFC Clash Sets` tool work in the new BlenderBIM release? I'm using right now the 230325 BlenderBIM release, and it works only with the json library. 

4. Another general Blender question: When I import an IFC architecture model (made in Revit) into Blender, colors are changed. What can I do so colors appear as they appear in Revit or other IFC viewers such as BIMvision? 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/122728940/785bcbef-5f61-41ab-8cf9-0ee973208778)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/122728940/a8f91ee9-5597-4b9d-8224-3406fcd05f41)

5. When importing an IFC file into BlenderBIM, is there a way to hide IFC Spaces without hiding the elements inside them? As they appear as solids in BlenderBIM. You can see the images above where in BlenderBIM the IFC Spaces are solid. 

Thank you so much.
Best regards.

**Comment by Moult** [comment]
1. View > Frame selected, or `.` key on numpad or `\` to isolate. This is covered in the BlenderBIM Add-on beginners tutorial https://blenderbim.org/docs/users/exploring_an_ifc_model.html#navigating-a-model-in-3d
2. Not for JSON. Only for BCF.
3. Unfortunately my dev environment can't run IfcClash right now within Blender so I can't recreate your issue. I'll keep on trying.
4. Colours shouldn't change. Note there are typically two colours: viewport shading colours and rendered diffuse colours. You can always check rendered mode, but if you can provide a sample file along with some screenshots that'll help.
5. Select a single space, in the object properties you can select all of the same class (i.e. IfcSpace) this is covered in the tutorial too https://blenderbim.org/docs/users/exploring_an_ifc_model.html#viewing-element-classes i.e.

> Press the Select Icon to select all objects that are of the same IfcSlab Class. Then, you can isolate these elements by going to Object > Show/Hide > Hide Unselected (hotkey Shift-H). To show all elements again, you can use Object > Show/Hide > Show Hidden Objects (hotkey Alt-H). If you want to hide elements instead, you can use Object > Show/Hidden > Hide Selected (hotkey H).

Hope that helps!

**Comment by imebp85** [comment]
It helped a lot! 
Thank you very much! :)

**Comment by Moult** [comment]
You're right, it seems as though the snapshot feature was disabled in the migration for the BCF library upgrade and we never reimplemented it. It's now been reimplemented. Thanks for the catch!

In addition, your bug has helped prompt investigation and fix into IfcClash crashing on Linux, and now we've also added support for IfcClash on Mac OS M1. Thanks so much!

**Comment by imebp85** [comment]
Perfect! Thank you very much!
