### ISSUE TITLE
BlenderBim - feature request - add version number to the status bar?

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3356]
Hey everyone, would it be possible to add the option to display Blenderbim's version number to the status bar here?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/9c006a79-9ee3-4f56-9f7d-720f636633cc)

Since Blenderbim is constantly updating, changing versions is a very frequently done task, and I have noticed that there tends to be confusion around what version people have installed and it leads to a hurdle for that first step of installing and updating blenderbim.

This is an entirely nice to have but I think having blenderbim's version number listed at the bottom for people will give a kind of clarity that going into the addons menu does not.

If it's possible, but definitely not a priority

**Comment by Gorgious56** [comment]
I don't think an addon can tap into this data with the python API, unfortunately. But I agree that having an immediate look on both Blender version and BlenderBIM version would be helpful when triaging bugs

**Comment by trhyder** [comment]
I agree this would be useful, but not only for files that have published sheets. It would also be helpful to know what version of Blender BIM last saved the IFC file. I wonder if it would be possible, or the right place even, to store the Blender BIM version in the IFC file and display that within the UI?

**Comment by Gorgious56** [comment]
@trhyder Well unless I'm mistaken the Bbim version number is already saved with the ifc. Open an ifc file with a text editor and look at the end of the 4th line. It may be interesting to display it in the File browser when you try to load an ifc file inside Blender though.

**Comment by Andrej730** [comment]
would be nice for debugging to also know the last commit that was used if someone is using dev builds from github
