### ISSUE TITLE
BlenderBIM - image_url resolve convention for IfcImageTexture.URLReference

### ISSUE THREAD

**Issue by wolfboyyang** [IfcOpenShell/IfcOpenShell#3365]
Hi, I'm working on a prototyping project to improve the texture rendering with IFC in blender (for futher VR experience).

I found url for IfcImageTexture seems not work as I expected on MacOS or Windows 11.
To make BlenderBIM version (0.7) resolve the image_url correctly, I need to:
either use the absolve path, which is not convenient to share and prone to write in wrong format,
or
1. make sure the url in ifc file is started with // (relative to blend file folder special to blender, and usually translated as root on MacOS and Linux or network folder on Windows)
2. save the blend file. (otherwise // could not be resolved)
3. load the ifc project.

Here's the possible solution:
```python
from pathlib import Path
...
ifc_path = tool.Ifc.get_path()
if ifc_path:
    image_url = str(Path(ifc_path).parent.joinpath(image_url))
```
This works with absolute and relative url (without //, which will be treated as absolute path and used as it is).
If we want to support the blender path convention, then // should be checked as a special case.

I put the current source code here for your referrence.

[0.7: src/blenderbim/blenderbim/tool/loader.py#L192](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/tool/loader.py#L198)
```python
#L187
            if texture["type"] == "IfcImageTexture":
                image_url = texture["URLReference"]
                ifc_path = tool.Ifc.get_path()
                if ifc_path:
                    image_url = bpy.path.abspath(image_url, start=Path(ifc_path).parent)
```

[0.8: src/blenderbim/blenderbim/bim/import_ifc.py#L1614](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/blenderbim/blenderbim/bim/import_ifc.py#L1614)
```python
#L1610
            if texture.is_a("IfcImageTexture"):
                image_url = texture.URLReference
                if not os.path.abspath(texture.URLReference) and tool.Ifc.get_path():
                    image_url = os.path.join(os.path.dirname(tool.Ifc.get_path()), texture.URLReference)
```

**Comment by Andrej730** [comment]
I've made some changes - now it should respect relative paths and store them in .ifc as posix (similar to how we store drawings paths).
Tested it by moving .ifc project from windows to Mac.

**Comment by wolfboyyang** [comment]
Need first save .blend is acceptable, although not so straight forward for new blender user to get some quick test.

I want to know whether ifc schema need to make it clear that relative path for image url need to be start with //. As a software engineer, I'm more familar with "data/some_image.png" or "./data/some_image.png" patern for relative path. To me, blender's python API bpy.path.abspath requires // for relative path is quite amazing for me.  

Is there any special reason to keep the image_url to the conversion of blender and make it into IFC Standard?

From the [IfcImageTexture IFC4x3 schema](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcImageTexture.htm):

"The texture is provided as an image file at an external location for which an URL is provided."

"The Uniform Resource Locator (URL) is a form of an URI and specified in [RFC1738](http://www.ietf.org/rfc/rfc1738.txt?number=1738) by IETF. "

and in RFC1738:
```
3.1. Common Internet Scheme Syntax

   While the syntax for the rest of the URL may vary depending on the
   particular scheme selected, URL schemes that involve the direct use
   of an IP-based protocol to a specified host on the Internet use a
   common syntax for the scheme-specific data:

        //<user>:<password>@<host>:<port>/<url-path>

   Some or all of the parts "<user>:<password>@", ":<password>",
   ":<port>", and "/<url-path>" may be excluded.  The scheme specific
   data start with a double slash "//" to indicate that it complies with
   the common Internet scheme syntax. The different components obey the
   following rules:

    user
        An optional user name. Some schemes (e.g., ftp) allow the
        specification of a user name.

    password
        An optional password. If present, it follows the user
        name separated from it by a colon.

   The user name (and password), if present, are followed by a
   commercial at-sign "@". Within the user and password field, any ":",
   "@", or "/" must be encoded.
```

While [bpy.path.abspath](https://docs.blender.org/api/current/bpy.path.html#bpy.path.abspath) would
```
Returns the absolute path relative to the current blend file using the “//” prefix.
```

**Comment by Andrej730** [comment]
@wolfboyyang by now it should save to IFC only as `data/some_image.png` or `./data/some_image.png`, no `//data/some_image.png`. - double slash prefix is only for Blender internal use as it's the only way it'll recognize relative paths in the Image Texture node in shader graph.

**Comment by wolfboyyang** [comment]
> Returns the absolute path relative to

OK, clear. Thank you.

**Comment by wolfboyyang** [comment]
After I installed the Daily developer testing build blenderbim-230630, it works as I expected (without //) and you don't have to save the blend file in advance. Cheers! Thank you very much.
