### ISSUE TITLE
Regression on nested loop: Conversion takes over 6h – ends in borked geometry (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#337]
Steps to reproduce:
1. Convert [337--nestedLoop.ifc](https://github.com/IfcOpenShell/files/blob/master/337--nestedLoop.ifc) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0)
2. Experience that the process runs forever.
3. File opens without warning in Solibri and DDS:
<img width="300" alt="screen shot 2018-02-26 at 13 05 08" src="https://user-images.githubusercontent.com/4601554/36670081-54a2fd50-1af7-11e8-8d50-40d34ff99a12.png">

This also happens on 8d0c95a9391f887e262e95cec646dca2c59ceadf (OCCT v7.2.0). ~~Not tried on another version of OCCT.~~ Update: this also happens with OCCT v7.1.0

**Comment by aothms** [comment]
I don't think it's an infinite loop. But in OCCT's `BRepLib_FindSurface()` there's a nested loop going over the face vertices:

~~~C++
    for (iPoint=2; iPoint<=aPoints.Length(); iPoint++)  {
      gp_Vec aDir(aFirstPnt,aPoints(iPoint));
      Standard_Real dfSide=aDir.Magnitude();
      if (dfSide<myTolerance) {
        continue; // degeneration
      }
      for (Standard_Integer iP1=iPoint+1; iP1<=aPoints.Length(); iP1++) {
~~~

For one particular face outer boundary there are 17145 points (which end up being twice that amount of vertices for edge start- end end points). Which doesn't scale well for this O(n^2) algorithm.

I think that's the issue. I wonder whether if IfcOpenShell supplies the underlying surface this expensive call can be eliminated.

**Comment by johanrd** [comment]
Closing, as this is not reproducible anymore when building from commit 1f68d9d5bcfda6ce6b7ff6e86733faf835247242 (conversion finishes successfully after a couple of minutes)

**Comment by aothms** [comment]
I forgot to commit this https://github.com/IfcOpenShell/IfcOpenShell/commit/2eaae2bda89071750f481d673c1ce689f5b73287 to speed op self intersection detection in these cases.

**Comment by johanrd** [comment]
Reopening as the geometry is not as expected (however, this has low priority given the complex input):
<img width="300" alt="screenshot--337" src="https://user-images.githubusercontent.com/4601554/50631727-b5470000-0f45-11e9-8042-9a7fbe6b6d61.png">

Also worth mentioning is that this takes ca 2 minutes on the 0.5.0-branch, and ca 6h 30 min on the 0.6.0 branch.

**Comment by johanrd** [comment]
Closing, as the geometry output is (close to) what is expected when converting with 808ef1a (OCCT 7.5.0)
