### ISSUE TITLE
Certain fills don't show in inkscape

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3373]
When printing a drawing such as `OPTION 2` in [this](https://gitlab.com/openingdesign/milwaukee_st_4429/-/blob/ccc8553fa32d1ec012cafaa9dabc37ba3b079e46/Models%20and%20CAD/Milwaukee_st_4429.ifc) file, the blue of the existing walls, doesn't show up in inkscape, but does in chrome. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9d725bdc-1b79-4938-8a90-5c46255ca2e9)

**Comment by theoryshaw** [comment]
to download the whole model directory: https://gitlab.com/openingdesign/milwaukee_st_4429/-/archive/ccc8553fa32d1ec012cafaa9dabc37ba3b079e46/milwaukee_st_4429-ccc8553fa32d1ec012cafaa9dabc37ba3b079e46.zip?path=Models%20and%20CAD

**Comment by Moult** [comment]
Unfortunately this is a bug in Inkscape (I believe). Inkscape does not have as comprehensive an implementation of CSS in SVG compared to browsers (naturally, browsers are awesome at CSS, and naturally, Inkscape is awesome at SVG).

Your rules here use attribute containment selectors:

```
[class*="PsetCommon-StatusNEW"] { fill: rgb(199, 199, 199); }
[class*="PsetCommon-StatusEXISTING"] { fill: #5D6E7F; stroke: #2C5573; }
[class*="surface"][class*="PsetCommon-StatusEXISTING"]{ fill: #c2ceda; stroke: #2C5573; stroke-width: 0.05px;}
[class*="PsetCommon-StatusEXISTINGDEMOLISH"], [class*="ODOptions-ODOption2D"] { fill: url(#demolish); stroke: red; stroke-dasharray: 2, 1; }
```

I've filed a bug to Inkscape devs to see if they can help: https://gitlab.com/inkscape/inbox/-/issues/8753

In the meantime, unfortunately they need to be spelled out in full. It's pretty annoying.
