### ISSUE TITLE
IfcSlab elements missing when importing ifc (blenderbim)

### ISSUE THREAD

**Issue by ay-ex** [IfcOpenShell/IfcOpenShell#3380]
In an ifc model (~90MB) with many triangular split slabs (https://github.com/IfcOpenShell/IfcOpenShell/issues/2847), from rvt ifc export, 
it seems some IfcSlab objects are not shown in blender, when imported with blenderbim(230705). 
Only an empty collection is visible in the outliner but the triangular parts are missing for some objects:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/127405908/6f09eba4-89c7-4134-b03c-329ec14bfe77)

The triangular pieces can be seen via text search in the ifc file and also in bbim "IFC debug" - 
but it is not possible to select the element from "IFC debug":

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/127405908/b51a9eef-dbec-475c-b4f6-bb3f39e71161)

The error there: `No Blender object found with guid '0nqKhRc3LAoQ9_OZGW27gK'.`

The blender console does not show any errors on import.

If the same revit floor object is exported separately to ifc it all works as expected:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/127405908/ad6dcaea-5d30-4cb4-9412-6ad1bd4d1f97)

@Moult : Maybe you have an idea, how the missing objects could be shown in the main export or how I could debug further?

**Comment by Moult** [comment]
Do you have more than 30k objects? If so, there is an object limit by default. Open the IFC and enable advanced mode to change the limit. https://blenderbim.org/docs/users/general_usage/ifc_project.html#advanced-mode

**Comment by ay-ex** [comment]
Thank you so much for the quick response! 
That could easily be, as rvt splits some of these floors into 1k to 2k of triangles.. 🙄 
I will try increasing the object limit and give feedback once it is done reloading the elements.. 🙂

**Comment by ay-ex** [comment]
yay!! 🎉 that was it - thank you again!!
