### ISSUE TITLE
`fill-bg` to work on dimension strings as well. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3387]
would be nice if `fill-bg` worked on dimension strings as well. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5ef87be1-372e-4c3a-9c7a-74b723d675d2)

**Comment by theoryshaw** [comment]
Awesome!...
small little oddity, order of classes makes a difference on viewport display. 
It prints, correctly however, both ways. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5918c52a-babe-4eb6-8da8-19229ca51f84)


![2023-07-06_11-47-39_Blender_ DDropboxGitLabrestaurant_livingston_Encry_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/664def1a-fc11-4a1c-8a88-4e4da9316227)

**Comment by Andrej730** [comment]
@theoryshaw well, classes are intended to be space separated, this is why oblique dimensions doesnt work with `oblique,` class

**Comment by theoryshaw** [comment]
ah, got it!.. thanks.
