### ISSUE TITLE
Malformed wall – no holes (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#339]
**Steps to reproduce:**
1. Convert [339--wall--missing-subtractions--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/339--wall--missing-subtractions--augmented.ifc) with 5d0c04a (OCCT v7.2.0)
2. Experience that the wall looks like this:
<img width="450" alt="screen shot 2018-02-28 at 13 07 42" src="https://user-images.githubusercontent.com/4601554/36790138-2bb5e1ac-1c94-11e8-90f9-19c5387201f4.png">
3. Open the same file in DDS or Solibri. Experience that the wall looks like this:
<img width="450" alt="screen shot 2018-02-28 at 13 07 30" src="https://user-images.githubusercontent.com/4601554/36790183-4dafa694-1c94-11e8-927c-48148d6965c9.png">

**Comment by aothms** [comment]
I think this is also a fairly straightforward issue in IfcOpenShell that needs to be fixed. There are overlapping openings which apparently does not work in the new n-ary OCCT boolean ops. My suspicion is that this file would work correctly with OCCT 6.8 where only binary boolean ops are supported.

![2018-03-11](https://user-images.githubusercontent.com/1096535/37251637-311f5e56-2514-11e8-86e5-657651004a94.png)

**Comment by johanrd** [comment]
Seems to be fixed by 161f24d8044c608ec7ac369a609ef2b9cc59f691 🎉

**Comment by johanrd** [comment]
Reopening, as the geometry is somewhat borked when building from 12e9f7b (OCCT 7.3.0p3):
<img width="562" alt="Screenshot 2019-06-18 at 15 36 45" src="https://user-images.githubusercontent.com/4601554/59689058-3be35700-91df-11e9-9508-c674e8baeefb.png">

**Comment by johanrd** [comment]
Closing, as this does not have any real-world implications for us. The output obj does however seem to struggle with some big coordinates in meshlab:
![Jul-17-2019 16-32-22](https://user-images.githubusercontent.com/4601554/61384337-af48b900-a8b0-11e9-9243-76efdfaeb9d2.gif)

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
