### ISSUE TITLE
Drawing style doesn't seem to be registering. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3396]
Drawing style doesn't seem to be registering. 
I might be doing something wrong. 

files, if you need them: 
[Restaurant_Livingston.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11971963/Restaurant_Livingston.zip)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a03f4bae-1bf3-478c-9d61-e6721e53d15d

**Comment by Moult** [comment]
You might need to share your `drawings/assets` folder too especially your `shading_styles.json`. I tried to recreate this but it works for me. Also possibly already fixed here https://github.com/IfcOpenShell/IfcOpenShell/commit/3cdad90755a359efa34abcb4a81a745c0d9cb345

**Comment by theoryshaw** [comment]
I might not be understanding how this works, but it doesn't seem to. ha. :)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/7080b7c5-26d4-4af7-8521-84a6bb4703d5

**Comment by Moult** [comment]
Can you share your model including the shading_styles.json?

**Comment by theoryshaw** [comment]
NP...
[Restaurant_Livingston.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11995246/Restaurant_Livingston.zip)

**Comment by theoryshaw** [comment]
In the file, i manually changed
`"scene.display.shading.type": "SOLID"`
to
`"scene.display.shading.type": "RENDERED"`
...and it seems to work. 

Perhaps the `scene.display.shading` value's not being registered.

**Comment by Moult** [comment]
I think this is now fixed.
