### ISSUE TITLE
BlenderBIM - Suffix and Prefix to Level dimensions

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#3399]
Would be great to be able to use prefix and suffix in level dimensions the same way it was implemented in linear dimensions.

**Comment by Moult** [comment]
Would be good if they reused the same pset too.

**Comment by Andrej730** [comment]
Also noticed that we have some inconstistency drawing PLAN_LEVEL and SECTION_LEVEL annotation in svg and viewport.

What would be more correct way to draw it - when the text and symbol are ignoring the direction of the line (how it is currently in SVG) or when it follows it (like in the viewport)?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/7ae35d0c-43ea-429f-9604-159d8b719cfb)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/d63aa97f-7b70-4d35-9bfb-904848b5bdcc)

**Comment by Moult** [comment]
I'd say viewport is correct.

**Comment by brunoperdigao** [comment]
I agree

**Comment by Andrej730** [comment]
fixed in becbfccae9c774f505fc700ee2c94681ec7f5aef
