### ISSUE TITLE
To have `bim.activate_drawing` not affect non-IFC objects. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3402]
When using `bim.activate_drawing`, I would like to propose that it does not affect non-IFC objects. That is, it only has an affect on everything in the IfcProject collection. 

Reason being, when maintaining the blender/ifc connection, there's a lot of non-ifc stuff like procedural entourage, lighting, constraints, etc. that when I switch views, I would like to have remain on, and not turned off automatically.

Or maybe, at the very least, a preference for this functionality.

**Comment by theoryshaw** [comment]
...or a mechanism, like exclude/include that works on these non-ifc objects, as well.

**Comment by theoryshaw** [comment]
This functionality, no longer seems to work.  Perhaps i'm missing something.

**Comment by theoryshaw** [comment]
Is it possible if a non-ifc object was hidden, that it remains hidden when using bim.activate_drawing?
Currently it's turned on.

**Comment by theoryshaw** [comment]
It doesn't seem like this works anymore.

**Comment by Andrej730** [comment]
@theoryshaw 

> Is it possible if a non-ifc object was hidden, that it remains hidden when using bim.activate_drawing?

Implemented in c113061742639a351096078ef416ef14ccdb1c02


> It doesn't seem like this works anymore.

Can you please share some case to reproduce this? Tested it even before c113061 and it seemed to work.

**Comment by theoryshaw** [comment]
Thanks @Andrej730 
Your commit addressed all of this. :)
