### ISSUE TITLE
Create drawing problems

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#3404]
In a new IFC4 file with IFC4 demo library template loaded, if i create a wall and create a new plan drawing, if i press "create drawing" i get this error
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/fd9e4cf3-47f6-4d5e-8b21-5fc86f6fc62c)

**Comment by Moult** [comment]
Do you have a development environment setup perhaps with symlinks as opposed to a fresh install? There has recently been an upgrade of the IfcOpenShell dependency so grab the latest IfcOpenShell binaries from here https://github.com/IfcOpenBot/IfcOpenShell/commit/fc50bdd3a0354cf332ad846f0a336a9bbfd4a769#comments

**Comment by maxfb87** [comment]
Yeah thanks, it was that :-) i close this issue

**Comment by maxfb87** [comment]
But how can i know if there is an upgrade of the IfcOpenShell dependency?

**Comment by Moult** [comment]
This is documented here: https://blenderbim.org/docs/devs/installation.html#live-development-environment

> The downside with this approach is that if a new dependency is added, or a compiled dependency version requirement has changed, or the build system changes, you’ll need to fix your setup manually. But this is relatively rare. Reviewing the Makefile history, [here](https://github.com/IfcOpenShell/IfcOpenShell/commits/v0.7.0/src/blenderbim/Makefile), is one quick way to see if a dependency has changed.
