### ISSUE TITLE
Small ordering glitch with Sheets UI

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3411]
Small UI glitch...

![2023-07-09_22-33-03_Blender_ DDropboxGitLabrestaurant_livingston_Encry_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/cd9788d1-06a9-4164-b6ee-b13c82b9e708)

**Comment by Moult** [comment]
Huh yeah that sorting is built-into blender and I have absolutely no idea how to fix that :)

**Comment by theoryshaw** [comment]
ha.. no worries.

**Comment by Moult** [comment]
Hopefully that helps! I can't imagine when a user _wouldn't_ want sheets ordered alphabetically.

**Comment by Gorgious56** [comment]
FWIW I think you can override the default "order" and "reverse order" buttons from the UI list https://docs.blender.org/api/current/bpy.types.UIList.html

**Comment by Moult** [comment]
@Gorgious56 you are a legend sir that is amazing and opens up a lot of possibilities of putting convenient expand all / hide all and other types of list management buttons!

**Comment by Moult** [comment]
Pinging @myoualid did you know about this `draw_filter` method? Because I reckon that would really help reorganise and declutter the UI for 4D 5D stuff which uses UIList pretty intensively!

**Comment by Gorgious56** [comment]
Hehe thank you but I just RTFM ^^ It's a shame the API for UIList is so hard to use, because it's definitely one of the most powerful interfaces you can create within vanilla Blender.
