### ISSUE TITLE
Loading a project removes all objects from file

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3414]
I like to have some boilerplate vanilla blender objects and collections in my file before I load an ifc file. However with the recent changes clicking on "Load Project" will remove all objects from the file. 

I would expect it not to, or maybe prompt the user beforehand ?

**Comment by Moult** [comment]
Yeah this is another issue of newbie vs poweruser which I seem to have accidentally pushed too far in the opposite spectrum. I previously received questions about why we'd always need to delete the cube/light/camera. What do you think of a solution of either:

 1. Move "purge scene objects" to an advanced loader option, and it purges by default.
 2. or If they choose the Project Wizard from the File > New or Ctrl-N menu then they may choose to disable purging the scene, but otherwise the default is to purge.

or other options?

**Comment by Gorgious56** [comment]
I figured this was the reason, it makes sense ! I think we can do something very dumb like assuming that if the file contains the three base objects and nothing else, we can delete them. If the file contains anything else, let the user decide what they want to do. Newbies won't notice a thing, and power users (who I assume already modified their default startup file to get rid of these 3) either.


```
if len(bpy.data.objects) == 3 and "Cube" in bpy.data.objects and "Camera" in bpy.data.objects and "Light" in bpy.data.objects:
    purge()
```

We can also check if the base file was previously used to store ifc data and purge that also ? Kinda weak but it worked for me when trying to keep a blend file in sync with an ifc file.

```
try:
    bpy.ops.bim.purge_ifc_links()
except AttributeError:
    pass
collection = next((c for c in bpy.data.collections if c.name.startswith("IfcProject")), None)
if collection:
    bpy.data.collections.remove(collection)
bpy.ops.outliner.orphans_purge(do_local_ids=True, do_linked_ids=True, do_recursive=True)
```

**Comment by Gorgious56** [comment]
I'm reopening this issue because it seems there is still something I'm missing here.

So, it doesn't remove the objects if the startup file has been modified by the user, but it does force the startup file to be loaded, which discards any object in the current work file and starts a new file.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/project/operator.py#L597

In the meantime my solution is to run this in the script editor

```
import bpy

bpy.ops.bim.load_project('INVOKE_DEFAULT', should_start_fresh_session=False)
```
