### ISSUE TITLE
Ifc modifiers parameters are not initialized on file load, which revert to default settings after edition

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3416]
[railing_bug.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12003290/railing_bug.ifc.txt)

Simple usecase with a IfcRailing modifier.
- Brand new ifc project
- Create a ifc railing using a modifier
- Change the type to wall mounted
- Validate
- Save File
- Close session
- Load ifc file
- The parameters are not initialized

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/d1b6f3a2-23ef-4727-b9e4-bf3fee2ff697)

If you directly modify the path, the railing reverts back to default parameters

![Animation3](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/08f5ed19-3ee1-4974-b662-04ff5711c5e1)

If you edit and validate the parameters, however it loads the correct settings.

![Animation3](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/4f2b105a-a248-466c-8202-ade1dd65d44f)

**Comment by Gorgious56** [comment]
Greeat, thank you ! :)

**Comment by Andrej730** [comment]
Fixed in 
a72231cb9
d633733d181764e594acc699cb7bf2c1e8d9510b
cd1a81363098a5e8422a0012a15f79c6204228dc
cada2c36e3498e07ba71b37ede5bd0ec11eb3987

**Comment by Gorgious56** [comment]
@Andrej730 So the parameters seem to import correctly, but the geometry still reverts to the default one when doing the steps in my original post

**Comment by Andrej730** [comment]
Fixed it. @Gorgious56 can you please take a look if anything will still catch the eye?

**Comment by Gorgious56** [comment]
Yup this seems to be fixed, thank you :) There is still this one lurking around https://github.com/IfcOpenShell/IfcOpenShell/issues/3262
