### ISSUE TITLE
IfcStairFlight: Setting 1st and last thread widths

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3419]
@brunoperdigao had a good idea to use the IfcStairFlight modifier to create stringers.

I think it would be a good idea both for a stair or a stringer, to be able to set the dimension indicated below. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/98323efa-f457-4742-9df7-a93009241f24)

Conceptually, setting the same corresponding dimension at the base, would be good too. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9e37c5b6-69d9-49b9-a02c-cd584405c5f9)

**Comment by theoryshaw** [comment]
file: https://gitlab.com/openingdesign/mineral_point_residence/-/blob/b6474f4173be9e9269359c49b4ca0d69f28817f0/Mineral_Point_Residence.ifc

**Comment by Moult** [comment]
Oh that's a great idea! Indeed first and last can sometimes be a special case!
