### ISSUE TITLE
Regression: Segfault when converting beam (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#342]
**Steps to reproduce:**
1. Convert [beam--segfault.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1771227/beam--segfault.ifc.zip) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0).

2. Experience error: 
```
FATAL: An error occured, status code 139.
```

There are no errors when converting with `IfcConvert 0.5.0-dev`, so this is seemingly a regression:
<img width="400" alt="screen shot 2018-03-01 at 14 09 43" src="https://user-images.githubusercontent.com/4601554/36846279-5b089820-1d5a-11e8-9a42-3422b6edcd47.png">

**Comment by aothms** [comment]
![2018-03-11 3](https://user-images.githubusercontent.com/1096535/37252076-659d887c-251b-11e8-842b-24797a1dd1b8.png)

Yeah this could be tough one, the red element is subtracted from the green one.

**Comment by johanrd** [comment]
Closing, as this is not reproducible anymore when building from commit 1f68d9d5bcfda6ce6b7ff6e86733faf835247242

**Comment by johanrd** [comment]
Closing again, as this is not reproducible anymore when building from commit fd821d08cddeed253ea50672fce588d4942855aa (not sure if "fixed", though)

**Comment by aothms** [comment]
> not sure if "fixed", though

On MSVC I get different (better) results then gcc. Tricky stuff. There is still one thing I'd like to try though.

**Comment by aothms** [comment]
> There is still one thing I'd like to try though.

Which didn't work out. It's frustrating that it runs well on msvc and fails on gcc, but at least the segfault is resolved. I don't think it's worth it to invest the resources into stepping through this on both ends and see where it differs.
