### ISSUE TITLE
Section and elevation references not referencing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3420]
Sections and elevations are placed on a sheet, but their number/sheet number is not being referenced in the section/elevation tags

The direction of some of the section tags is incorrect, as well. 

files:https://gitlab.com/openingdesign/restaurant_livingston/-/archive/9b1e206ce72e3b06b6e7021207380299a98ad93a/restaurant_livingston-9b1e206ce72e3b06b6e7021207380299a98ad93a.zip?path=Models%20and%20CAD/BB%20Model

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5419dd65-3513-4737-89ad-769db3d0638b)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b5034b1b-4f13-4ec0-abd3-f67070dba0f4)

**Comment by Moult** [comment]
You need to delete the section, then let it regenerate it (it regenerates when you activate the drawing).

**Comment by theoryshaw** [comment]
bingo, thanks!
