### ISSUE TITLE
IfcGridAxis from BB doesn't pass the WR1 check

### ISSUE THREAD

**Issue by VDobranov** [IfcOpenShell/IfcOpenShell#3425]
I’ve started blank IFC-project in BB then’ve created default grid, then’ve saved IFC and sent it to the verification service (https://bim.ispras.ru/verify-ifc)
Got a WR1 errors on every IfcGridAxis:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/190bed8e-9872-4f5c-918a-516dc85be834)

The formal proposition in specs:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/e1566d23-c20e-41c4-8fc3-2e1c3b38aec3)

One of the axes:
```#90=IFCGRIDAXIS('01',#93,.T.);
#91=IFCCARTESIANPOINT((0.,-2.,0.));
#92=IFCCARTESIANPOINT((0.,22.,0.));
#93=IFCPOLYLINE((#91,#92));
```

It seems that the trailing 0. in Points are causing the problem - after I’ve deleted them, the verification was passed.

**Comment by aothms** [comment]
You're assessment is correct.

Site note: Does validate.buildingsmart.org report the same issue? It's a validator implemented using IfcOpenShell. Would be good to test known where rule violations there as well. To validate the validator.
