### ISSUE TITLE
Issue in ifc convert export with version 0.7.0

### ISSUE THREAD

**Issue by farazkhalidsiddiqui** [IfcOpenShell/IfcOpenShell#3429]
Hi,  I have noticed that some holes in the model are missing after exporting ifc from ifc convert version 0.7.0. Interestingly, the previous version, 0.6.0, did not have this problem, and all the holes were properly included. 
I have attached the IFC file and exported .obj and .glb (from v0.6.0 and v0.7.0). These files will help illustrate the discrepancy between the two versions. 
I would appreciate your help in obtaining IFC convert version 0.6.0 for Linux.
Thank you very much for your attention to this matter. I look forward to your prompt response.

[Ifc convert issue.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12031239/Ifc.convert.issue.zip)
![version-0 6 0](https://github.com/IfcOpenShell/IfcOpenShell/assets/5821070/28287191-2bb6-4d29-a9b0-c1c766ccaa89)
![version-0 7 0](https://github.com/IfcOpenShell/IfcOpenShell/assets/5821070/b4f8a9f7-f637-467b-9886-41d252ecb024)

**Comment by farazkhalidsiddiqui** [comment]
Any update on this issue?

**Comment by Moult** [comment]
Sorry, no. I can recreate your issue but this is something that @aothms needs to investigate.

**Comment by farazkhalidsiddiqui** [comment]
V6 has some parts missing and v7 has holes missing for assembly part.
All converted files and ifc file attached.
![comparision](https://github.com/IfcOpenShell/IfcOpenShell/assets/5821070/15ed5a93-8e8f-4361-a8bf-c60f45195e73)
[c13_2.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12090011/c13_2.zip)

**Comment by farazkhalidsiddiqui** [comment]
Any update on this?

**Comment by Moult** [comment]
Sorry no, we'll need to wait until @aothms finds time to investigate this. If you'd like to help us be able to have more resources to respond faster, you can help donate even a small monthly amount here: https://opencollective.com/opensourcebim - we use this to sponsor extra development.

**Comment by aothms** [comment]
Thanks for the structured report, very helpful. Sorry for the delay in replying I was travelling for some extended period of time and didn't have access to all resources and still catching up on work. Luckily this was an obvious bug in our own code, which are typically easier to fix then some of the other boolean operation bugs.

I still have look into an other long standing issue regarding why our automated builds are failing. After that you can download an updated version.

New results:

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/a609dffc-9fda-407e-a4de-6a528f69429e)

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/a5ac9fcb-a262-42da-ae9b-a6eb862cbfde)

**Comment by farazkhalidsiddiqui** [comment]
@aothms 
Thanks for solving the issue. When can we have the version 0.8? Is there any chance to get the current updated version(with this fix) for windows and linux?

**Comment by Moult** [comment]
@farazkhalidsiddiqui you can download new builds here https://github.com/IfcOpenBot/IfcOpenShell/commit/9cc1f5f0e3177e8181dd4a586f61d4aa7b525043#commitcomment-126087495
