### ISSUE TITLE
v0.8 branch with python

### ISSUE THREAD

**Issue by SoftwareMechanic** [IfcOpenShell/IfcOpenShell#3436]
Hello!

I was trying to run branch 0.8 with python in order to see how CGAL performs.

I have seen that in order to create the iterator, I need to pass to the constructor a vector of `IfcGeom::filter` , but I do not understand how that class is translated from C++ to python.

does someone have an hint on this?

Thank you in advance

**Comment by Moult** [comment]
See #4915. 0.8.0 is now the main branch :)
