### ISSUE TITLE
Missing lib folder on Python package?

### ISSUE THREAD

**Issue by femesq** [IfcOpenShell/IfcOpenShell#3438]
Hi everybody,

I'me getting this erro when trying to use the Python BCF package:

```
ImportError: IfcOpenShell not built for 'linux/64bit/python3.10'
```

It seems to be a supported Python Version and Architecture...

the result of [line 57 here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/__init__.py#L57) for me is:

```python
python_distribution = 'linux/64bit/python3.10'
```

So, the [line 58](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/__init__.py#L58) below tries to add the value below to PATH:

```bash
/my/virtual_env_path/lib/linux/64bit/python3.10
```

I have installed the lib using PIP with [theses instructions](https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#pypi).

The contents of "ifcopenshell" installed package (on path site-packages) seems to match the zip files available here: https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#pre-built-packages

In both cases, browsing the files I can't find any `lib` folder inside the package installation folder.

Is there some I'm missing?

**Comment by Moult** [comment]
It's hard to say without knowing what environment you're on, whether or not you have any other Pythons installed, whether you've manually tweaked things or moved things around ... if you want we can organise a screenshare and I can help debug during the Sydney timezone 9am to 5pm?

**Comment by aothms** [comment]
> So, the [line 58](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/__init__.py#L58) below tries to add the value below to PATH:
> 
> /my/virtual_env_path/lib/linux/64bit/python3.10

This is not too related probably. This was only intended for "fat" IfOpSh distributions. So a directory tree of all possible os+bitness binaries and then using sys.path to import the correct one. In all normal downloads you just only download for your platform and you have ifcopenshell/ifcopenshell_wrapper.py and ifcopenshell/_ifcopenshell_wrapper.so in the same directory.

Can you try importing `_ifcopenshell_wrapper` when you are in the ifcopenshell/ directory?

Unfortunately afaict there are very few mechanisms to debug python failing to import a binary module.

You could also try `ldd _ifcopenshell_wrapper.so` to see if there are any missing symbols.

Also what's you distro and version?

**Comment by femesq** [comment]
@Moult 
Thanks for your availability! 
Could no see you message in time due to timezone. If I can't mange to fix the issue, can we arrange this for the next week?

@aothms 

> Also what's you distro and version?

Sorry about the incomplete info... Here is my distro/arch info:

```bash
$ uname -a
Linux debian 4.19.0-24-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64 GNU/Linux

$ python
Python 3.10.12 (main, Jul  2 2023, 20:20:05) [GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

$ pip install ifcopenshell
Requirement already satisfied: ifcopenshell in /home/felipe/venv_3_10_12/lib/python3.10/site-packages (0.7.0.230523)
```

> Can you try importing _ifcopenshell_wrapper when you are in the ifcopenshell/ directory?

```bash
$ cd /home/felipe/venv_3_10_12/lib/python3.10/site-packages/ifcopenshell
$ python

Python 3.10.12 (main, Jul  2 2023, 20:20:05) [GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import _ifcopenshell_wrapper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /home/felipe/venv_3_10_12/lib/python3.10/site-packages/ifcopenshell/_ifcopenshell_wrapper.so)
```

For reference to help other, it seems that Debian 10 (buster) reached it's end-of-life support. So the complain above will persist because last available version of glibc on buster is:

```bash
$ apt-cache policy libc6

libc6:
  Installed: 2.28-10+deb10u2
  Candidate: 2.28-10+deb10u2
  Version table:
 *** 2.28-10+deb10u2 500
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.28-10+deb10u1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages

$ ldd --version
ldd (Debian GLIBC 2.28-10+deb10u2) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.

```

Will try to update my system and will get back reporting the results in the coming days!

Thanks for you help until now!

**Comment by aothms** [comment]
> ImportError: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /home/felipe/venv_3_10_12/lib/python3.10/site-packages/ifcopenshell/_ifcopenshell_wrapper.so)

> it seems that Debian 10 (buster) reached it's end-of-life support

Yes, but that's the thing with the precompiled binaries. We have to compile them on some platform and some parts of the code base depend on modern compiler/C++ language features.

We do set the build machine version stable for the entire lifetime of a branch. So you can probably run v0.6 builds but not v0.7.

Or you have to compile yourself on your machine (it's not that difficult) to be sure it runs.

**Comment by Moult** [comment]
@aothms is this something I can add to the documentation? Something like a minimum glibc requirement?

**Comment by femesq** [comment]
Hey @aothms and @Moult,

Just getting back here to confirm that after upgrading my system, things works fine!

```bash
$ python

Python 3.10.12 (main, Jul 14 2023, 21:41:36) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _ifcopenshell_wrapper
>>>    ## >> Success

```

You can close this issue if you want, or follow on with @Moult docs suggestion on this, instead of opening a new one.

[]'s

**Comment by Moult** [comment]
This is now in FAQ 2  https://docs.blenderbim.org/users/installation.html#faq
