### ISSUE TITLE
BlenderBIM Clash Sets user questions

### ISSUE THREAD

**Issue by imebp85** [IfcOpenShell/IfcOpenShell#3444]
Hi! 

I've got some questions about using the IFC Clash Sets tool in BlenderBIM (I'm currently using the 230325 BlenderBIM release, just in case it has changed in newer releases). 

1. Is soft or clearance clash test working? I'm testing it with a water pipe (.IfcPipeSegment) and a cable tray (.IfcCableCarrierSegment) that are intentationally separated by 19 cm, but have to be separated by 30 cm at least. 

![Pipe_CableCarrier](https://github.com/IfcOpenShell/IfcOpenShell/assets/122728940/97f732b1-3ba9-4254-b4c6-ce49da4ca20d)

I'm trying using a negative value as tolerance (-0.30 m), but it doesn't work, it doesn't detect the soft clash, it just detects other hard clashes between these classes. 

Am I doing something wrong or does BlenderBIM do not support soft clashes?

2. Another question is if there's a possibility to detect hard clashes between two pipes in diferent systems, specifying the type of system. For example, if I want to detect hard clashes between water pipes and  sewage pipes. 

Right now I'm just including the Ifc Classes ".IfcPipeSegment" at both group A and group B, but if want to be more specific having both systems in the same IFC file how would it work? can I add the name of the system after the IfcClass, or how can I do it? 

Thank you very much for your help! 

Best regards.

**Comment by BIMvoice** [comment]
I don't think this changed, but why are you not using a more recent release? The new user interface it's amazing, you should definitely try the latest version.

**Comment by Moult** [comment]
I don't think there has been any IfcClash changes regarding what you're after so upgrading won't help apart from give a nicer UI. I'll let you know when I find the time to test this. From memory soft clashes were never fully tested.

**Comment by Moult** [comment]
The selector now supports groups (including systems) and the latest clash detection system now supports clearance clashes :)
