### ISSUE TITLE
Store absolute and relative paths of images imported as images as planes with transformation stored in IFC

### ISSUE THREAD

**Issue by C-Claus** [IfcOpenShell/IfcOpenShell#3447]
Could  a ```.png or .jpg``` which  be loaded with an ```image as plane``` in Blender be stored? With the relative or absolute path of the file stored in IFC as a propertyset with the scaling, rotation and locationed also saved in an IfcPropertySet. Or maybe there is a way smarter way of doing things?

Related discussions:

https://github.com/IfcOpenShell/IfcOpenShell/issues/3219

https://community.osarch.org/discussion/1365/blenderbim-storing-reference-drawing-with-the-ifc#latest

I made a basic add-on  here:

https://github.com/C-Claus/BlenderScripts/tree/master/BlenderBIM_add_reference_images

![Screenshot 2023-07-14 110322](https://github.com/IfcOpenShell/IfcOpenShell/assets/14906760/82207e5d-0d9a-46d7-91c4-688254e6cafa)

**Comment by Moult** [comment]
I think a reference image is no different to any IfcAnnotation except that it has an image textures. We have all the functionality, just need to build a UI for it. No need to have psets either.

**Comment by C-Claus** [comment]
Just out of curiosity, where can I find ifcopenshell code snippets how to interact with  IfcAnnotation?

**Comment by Moult** [comment]
Assigning but @Andrej730 I'll need to brief you before starting :)

**Comment by theoryshaw** [comment]
+1 :)

**Comment by theoryshaw** [comment]
_    ,-,    _
                 ,--, /: :\/': :`\/: :\
                |`;  ' `,'   `.;    `: |
                |    |     |  '  |     |.
                | :  |     | pb  |     ||
                | :. |  :  |  :  |  :  | \
                 \__/: :.. : :.. | :.. |  )
                      `---',\___/,\___/ /'
                           `==._ .. . /'
                                `-::-'
