### ISSUE TITLE
Regression: Segfault when converting structural connections (2 example files)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#345]
Steps to reproduce:
1. Convert [object--segfault-regression.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1789534/object--segfault-regression.ifc.zip) or [object--segfault-regression2.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1789536/object--segfault-regression2.ifc.zip) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0 or v7.1.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```

There are no errors when converting with 8d0c95a9391f887e262e95cec646dca2c59ceadf (OCCT v7.2.0), so this is seemingly a regression:
<img width="300" alt="screen shot 2018-03-07 at 15 56 30" src="https://user-images.githubusercontent.com/4601554/37099273-2c8802d6-2220-11e8-8c2d-465637cf6c30.png">

**Comment by aothms** [comment]
![2018-03-11 5](https://user-images.githubusercontent.com/1096535/37252149-b7d380fa-251c-11e8-95b4-c20500f80619.png)

The body consists of individual meshes. These would be processed individually when subtracting the openings in red. Not sure where it fails exactly but could be same issue as #341

**Comment by johanrd** [comment]
Closing, as this is not reproducible anymore when building from commit 1f68d9d5bcfda6ce6b7ff6e86733faf835247242
