### ISSUE TITLE
IfcConvert. GTLF Instancing

### ISSUE THREAD

**Issue by enruilo1** [IfcOpenShell/IfcOpenShell#3455]
Hi, 
Firstly, thank you so much for your contribution to improve AEC world tecnology.
I think that implementation of gpu instancing would improve renderization of GLTF (due tu reduce drawcalls) and i dont see any option to configure this in IfcConvert. I think that improve serialization of IFC in GLTF would be a must due to its use in WEB services and other high potencial formats like 3DTiles. I Know that gpu instancing is a vendor extension already (https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing) but it has some implementation in THREEJS (https://github.com/takahirox/three-gltf-extensions/tree/main/loaders/EXT_mesh_gpu_instancing) that would be useful to apply. I think IFCJS due to implement some extension like this or this (https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_mesh_features) instead of create its own memory managers and fragments and soon... and ifcopenshell could be an extraordinary solution to give high GLTF rendering performance files based on open standards. Whats your opinion about this? Is there any posibilities to implement it?

**Comment by enruilo1** [comment]
Sorry, I forget this. There is some optimizer implementation (https://meshoptimizer.org/gltf/) but i tried some time ago and it deleted IFC'GlobalIds of meshes and output wasn't usefull because lost IFC connection.

**Comment by aothms** [comment]
There is also gltf-pipeline https://github.com/CesiumGS/gltf-pipeline with things such as draco. I personally really believe in modular application, not trying to fix everything in one single monolithic application. If there's anything we can do in restructuring the gltf output in order to retain more info in the various pipelines let us know.

**Comment by enruilo1** [comment]
Yes, i think ifcConvert should implement flag to create "instancing" following this standarization https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing.That would be a performance improvement due to reduce de number of drawcalls in GPU.
Also, another option is to implement https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_mesh_features, it is like a index table to search in a merge unique mesh. It should be an incredible performance tool in GLTF too.
Problem is that, nowadays, these are extensions and are not fully supported by THREEJS or other libraries, but soon it will be (like this implementation of instanciation https://github.com/takahirox/three-gltf-extensions/tree/main/loaders/EXT_mesh_gpu_instancing).

**Comment by enruilo1** [comment]
Ok, info mode on, i am trying to improve gltf instancing by other gltf transformers pipelines to finally improve performance in GLTF without lose GUID control. I think, this issue is not corresponding with this repo nowadays and i will close it.

Adjoin issue track in another repo. Thank you for your patience. I hope that in future GLTF provided by IFCOPENSHELL contains these improvements but nowadays these improvementes are not mature yet.

https://github.com/donmccurdy/glTF-Transform/issues/1034
