### ISSUE TITLE
Regression: Segfault when converting slab (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#347]
Steps to reproduce:
1. Convert [347--slab--segfault--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/347--slab--segfault--augmented.ifc) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```

There are no errors when converting with 8d0c95a9391f887e262e95cec646dca2c59ceadf (OCCT v7.2.0), so this is seemingly a regression:
<img width="300" alt="screen shot 2018-03-08 at 09 21 09" src="https://user-images.githubusercontent.com/4601554/37140570-7b27b4bc-22b2-11e8-83d8-93d7d3ca61eb.png">

**Comment by aothms** [comment]
<img width="904" alt="2018-03-16" src="https://user-images.githubusercontent.com/1096535/37513987-e271f380-2906-11e8-8171-4494afce2e5d.png">

This is a slab with polygonal halfspace boolean subtractions. The 5 halfspaces make up for the same footprint as the original slab volume. All halfspace are exactly above the slab so not really subtracting anything. My guess is that with every subtraction tolerance values get changed until eventually some invalid state is reached.

Solutions could be found in filtering redundant subtractions, merging boolean operands in trees of IfcBooleanResult, simplifying IfcPolygonalBoundedHalfSpaces with redundant loops as full half spaces.

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on 808ef1a (OCCT 7.5.0)
