### ISSUE TITLE
Error when executing IFC Clash

### ISSUE THREAD

**Issue by Nattefrost666** [IfcOpenShell/IfcOpenShell#3470]
I got this error: "ImportError: DLL load failed while importing hppfcl"

**Comment by Moult** [comment]
Can another Windows user replicate this? Ping @theoryshaw can you try `import hppfcl` in the Blender console and see if you get any errors?

**Comment by Nattefrost666** [comment]
>>> import ifcopenshell
>>> import hppfcl
Traceback (most recent call last):
File "<blender_console>", line 1, in <module>
File "C:xxxxx\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\hppfcl\__init__.py", line 34, in <module>
from .hppfcl import *
ImportError: DLL load failed while importing hppfcl: Impossibile trovare il modulo specificato.

**Comment by theoryshaw** [comment]
Happy to, but I've never use IFC clash before... not sure how to use it.

**Comment by Nattefrost666** [comment]
Can some Windows user try this
![Procedure](https://github.com/IfcOpenShell/IfcOpenShell/assets/51818392/3c162b11-faf7-47d1-8c39-58989c385069)
and see if it works?
Thanks

**Comment by theoryshaw** [comment]
Can you share the files?

**Comment by Nattefrost666** [comment]
I think Is not a matter of IFC file, you can try with every kind of IFC. Btw i'll drop the files in about an hour
--
Inviato da Libero Mail

**Comment by Nattefrost666** [comment]
[rst_advanced_sample_project.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12112310/rst_advanced_sample_project.txt)
I used this. Should change from .txt to .ifc

**Comment by Moult** [comment]
No need to run IfcClash, just go into the Python console and type `import hppfcl` and see what happens.

**Comment by theoryshaw** [comment]
Thank you for that. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/8fff509c-ef98-4714-8fea-29df0139d8bb)

**Comment by c4rlosdias** [comment]
has anyone fixed this?

**Comment by myoualid** [comment]
Is it a windows issue or Blender issue?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79010126/4fd083c7-19b4-4841-8515-621c3782be01)
