### ISSUE TITLE
Select type does not select type if types are hidden.

### ISSUE THREAD

**Issue by chopinregis** [IfcOpenShell/IfcOpenShell#3471]
when using the select type, it would be useful and handy if it can also select the types object even if that object is hidden. This is usful to avoid having to toggle on the types collection, and all the types in there before the type is discoverable by the types selector.

![Screenshot 2023-07-19 093234](https://github.com/IfcOpenShell/IfcOpenShell/assets/13260872/9bf6547c-75fb-4455-82de-56f83a68b1ff)

**Comment by theoryshaw** [comment]
Agree.  As just a simple first step maybe the types collection is turned on by default, and does not turn off when `bim.activate_drawing` is used.

**Comment by theoryshaw** [comment]
why would you want to delete this beautiful mess? ;)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/6c361eab-9758-4c20-941f-7153fa7c5587)
