### ISSUE TITLE
Erros no Blender BIM - IFC Tester

### ISSUE THREAD

**Issue by andreservino29** [IfcOpenShell/IfcOpenShell#3476]
Prezados, gostaria de saber o que devo fazer sobre uma mensagem de erro que aparece no Blender quando eu utilizo o IFC Tester para verificação re requisitos com um IDS.

Dear all, I would like to know what I should do about an error message that appears in Blender when I use IFC Tester for verification re requirements with an IDS.

```
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\tester\operator.py", line 52, in execute
    specs = ifctester.ids.open(props.specs)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifctester\ids.py", line 35, in open
    get_schema().decode(filepath, strip_namespaces=True, namespaces={"": "http://standards.buildingsmart.org/IDS"})
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\xmlschema\validators\schemas.py", line 2023, in decode
    for result in self.iter_decode(source, path, schema_path, validation, *args, **kwargs):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\xmlschema\validators\schemas.py", line 1940, in iter_decode
    resource = XMLResource(source, defuse=self.defuse, timeout=self.timeout)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\xmlschema\resources.py", line 470, in __init__
    self.parse(source, lazy)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\xmlschema\resources.py", line 732, in parse
    self._parse_resource(resource, url, lazy)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\xmlschema\resources.py", line 704, in _parse_resource
    self._parse(resource)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\xmlschema\resources.py", line 678, in _parse
    for event, node in ElementTree.iterparse(resource, events):
  File "D:\3.1\python\lib\xml\etree\ElementTree.py", line 1254, in iterator
    yield from pullparser.read_events()
  File "D:\3.1\python\lib\xml\etree\ElementTree.py", line 1329, in read_events
    raise event
  File "D:\3.1\python\lib\xml\etree\ElementTree.py", line 1301, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 13, column 0

location: <unknown location>:-1
```

**Comment by Moult** [comment]
It looks like your IDS file may not be valid. Can you attach it here? (Rename to .txt)

**Comment by andreservino29** [comment]
Prezado Moult

Segue abaixo o script XML que estou testando, e que não consegui operacionalizar no BlenderBIM.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ids:ids xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS ids_09.xsd" xmlns:ids="http://standards.buildingsmart.org/IDS">
<ids:info><ids:title>Verificação de RI-Orcamento</ids:title>
	<ids:copyright>André Luis Servino Alvarenga</ids:copyright>
	<ids:version>V0</ids:version>
	<ids:author>andreservino.arq@gmail.com</ids:author>
	<ids:date>2023-07-08</ids:date>
	<ids:purpose>Verificação de RI de espeificações e dados para extração de quantitativos</ids:purpose>
	<ids:milestone>Projeto Básico</ids:milestone>
	<ids:descritiption>Este IDS deve ser utilizado para verificação da existencia de paremetros padrões do modelo visando extração de quantidades.</ids:descritiption>
</ids:info>
<ids:specifications>
	<ids:specification name= "Verificação LABOR" ifcVersion="IFC2X3" descrtiption="Quais elementos são da tabela referencial" minOccurs="1"
		<ids:applicability>
			<ids:entity>
				<ids:name>
					<ids:simpleValue>IFCDOOR</ids:simpleValue>
				</ids:name>
			</ids:entity>
			<ids:attribute>
				<ids:name>
					<ids:simpleValue>Name</ids:simpleValue>
				</ids:name>
				<ids:value>
					<ids:simpleValue>DER_Porta_Mad_Abrir_1F</ids:simpleValue>
				</ids:value>
			</ids:attribute>
		</ids:applicability>
		<ids:requirements>
			<ids:property measure="IfcBoolean" minOccurs="1" maxOccurs="1">
				<ids:propertySet>
					<ids:simpleValue>DER_Serviço LABOR-T</ids:simpleValue>
				</ids:propertySet>
				<ids:value>
					<ids:simpleValue>TRUE</ids:simpleValue>
				</ids:value>
			</ids:property>
		</ids:requirements>
	</ids:specification>
</ids:specifications>
</ids:ids>

**Comment by andreservino29** [comment]
@Moult , Obrigado se puder ajudar.

**Comment by Moult** [comment]
There are a number of problems with your IDS, presumably you have hand-written it:

 1. You are missing `>` on this line: `<ids:specification name= "Verificação LABOR" ifcVersion="IFC2X3" descrtiption="Quais elementos são da tabela referencial" minOccurs="1"`
 2. There is no such thing as `<ids:descritiption>`, you'll need to remove it.
 3. `descrtiption=` is a spelling mistake, it should be `description=`
 4. `measure` has recently been renamed to `datatype`
 5. Your pset facet is incomplete, it needs to filter a name as well as a value. E.g.

```
                    <ids:propertySet>
                        <ids:simpleValue>EPset_Address</ids:simpleValue>
                    </ids:propertySet>
                    <ids:name>
                        <ids:simpleValue>AddressLines</ids:simpleValue>
                    </ids:name>
                    <ids:value>
                        <ids:simpleValue>34 Phillip St</ids:simpleValue>
                    </ids:value>
```

After you fix all this it works :)

**Comment by Moult** [comment]
Ah yes thanks :) Yes IDS is that strict since it uses xs:sequence. I wonder if this was intentional. Reported bug upstream https://github.com/buildingSMART/IDS/issues/175
