### ISSUE TITLE
It seems if a wall has a door in it, that 'joincriteria' does not work

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3479]
It seems if a wall has a door in it, that the 'joincriteria' does not work--circled in blue. 
The joint, circled in red, works. 

files: https://gitlab.com/openingdesign/milwaukee_st_4429/-/archive/1c60f925ef640da9b1f454986205341f5f3dbbbf/milwaukee_st_4429-1c60f925ef640da9b1f454986205341f5f3dbbbf.zip?path=Models%20and%20CAD/BlenderBIM

Drawing: `FLOOR PLAN - 1ST`

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/10752d9f-4bf0-42ef-a48f-e8a96131eeb3)

**Comment by Gorgious56** [comment]
Oh so that would explain why I never managed to make it work ?
