### ISSUE TITLE
IFCMATERIALLAYERSET / IFCRELASSOCIATESMATERIAL missing in XML conversion

### ISSUE THREAD

**Issue by swalter88** [IfcOpenShell/IfcOpenShell#348]
Hey guys, another missing part of IFC2x3. 

The converted IfcMaterialLayerSet is empty in xml file.
```
#96=IFCWALL('3tyH2xrJ16ixGM4w4bKgTF',#5,'Wall-01',$,$,#95,#90,$);
#145=IFCRELASSOCIATESMATERIAL('2PdnYxrJ16ixGM4w4bKgTF',#5,$,$,(#96),#144);
#144=IFCMATERIALLAYERSET((#134,#143),$);
#134=IFCMATERIALLAYER(#126,255.,$); --> der zweite Parameter "255" ist die Materialdicke
#126=IFCMATERIAL('Reinforced_concrete');
```

[WallStandardCase-01_ARCHLINEXP.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1793263/WallStandardCase-01_ARCHLINEXP.ifc.zip)

**Comment by aothms** [comment]
~~~xml
<IfcWall id="3tyH2xrJ16ixGM4w4bKgTF" Name="Wall-01" ObjectPlacement="0 -1 0 0 1 0 0 0 0 0 1 0 420 10080 -2400 1">
    <IfcPropertySet xlink:href="#0gWMEAtDP1wvKHykJ5AXTj"/>
    <IfcPropertySet xlink:href="#0s2jxLE9jCgwZD$XSv7Smb"/>
    <IfcWallType xlink:href="#1ks4wxrJ16ixGM4w4bKgTF"/>
    <IfcPresentationLayerAssignment xlink:href="#WSC1 basement wall"/>
    <IfcMaterialLayerSet xlink:href="#IfcMaterialLayerSet_144"/>
</IfcWall>
~~~

~~~xml
<IfcWallStandardCase id="2_x1HZKvbC$hDRQHfLnjG6" Name="Wall-09" ObjectPlacement="0 -1 0 0 1 0 0 0 0 0 1 0 4353 10080 -2400 1">
    <IfcPropertySet xlink:href="#1AYetG7YL3aQuvPK5_Sf3J"/>
    <IfcWallType xlink:href="#0rqr9ZKvbC$hDRQHfLnjG6"/>
    <IfcPresentationLayerAssignment xlink:href="#WSC1 sample wall"/>
    <IfcMaterialLayerSetUsage xlink:href="#IfcMaterialLayerSetUsage_221"/>
</IfcWallStandardCase>
~~~

IfcOpenShell expects the elements to point to a IfcMaterialLayerSet**Usage** which then includes the layerset. However for this particular case of Wall-01 a link is made to the layerset directly.

I had to look this up, but only for IfcWall**StandardCase** 

> The material of the wall is defined by the IfcMaterialLayerSetUsage

For IfcWall (that is new to me)

> The material of the IfcWall is defined by IfcMaterialLayerSet, or as fallback by IfcMaterial, and it is attached either directly or at the IfcWallType.
> NOTE  It is **illegal** to assign an IfcMaterialLayerSetUsage to an IfcWall. Only the subtype IfcWallStandardCase supports this concept.

It's a small fix in the code. Thanks for reporting this.
