### ISSUE TITLE
Error when create IFC4.3 Project

### ISSUE THREAD

**Issue by Walpa** [IfcOpenShell/IfcOpenShell#3488]
Version:  blenderbim-230721-py310-linux
![2023-07-21 09-47-17](https://github.com/IfcOpenShell/IfcOpenShell/assets/32360904/ebf5dda8-6347-4046-a2b2-8450f6bee39a)

**Comment by Andrej730** [comment]
Related to 5b4010c67da501112d9bfe3eabac3b62e85494b9?
```python
import ifcopenshell
ifcopenshell.file(schema='IFC4X3').schema_name()
# 'IFC4X3_ADD1'
```
