### ISSUE TITLE
Walls taking on incorrect svg pattern

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3490]
With [these](https://gitlab.com/openingdesign/milwaukee_st_4429/-/archive/b65ac6e6aec5c93221b1f16bcad2eea1255c30b3/milwaukee_st_4429-b65ac6e6aec5c93221b1f16bcad2eea1255c30b3.zip?path=Models/BlenderBIM) files, I have the following CSS rule that's intended to assign a 2HR svg pattern to wall types with `Pset_WallCommon.FireRating = 2 HR`

`[class*="PsetCommon-FireRating2HR"] { fill: url(#2HR); }`

The walls circled in blue below, should not take on this pattern. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/68e620a3-5993-4bad-bf71-b95e5fcfc604)

**Comment by Moult** [comment]
I haven't investigated yet but at a glance could this be the issue of SVG not supporting the `*=` CSS selector? Can you try with a simpler CSS?

**Comment by theoryshaw** [comment]
I used the following instead, and got the same result.

`.rPsetCommon-FireRating2HRid782316StatusNEW{ fill: url(#2HR); }`


The classes, in both the correct area and wrong area, are the same, which is the following...

```
`rPsetCommon-FireRating2HRid782347StatusNEW cut rPsetCommon-FireRating2HRid782316StatusNEW 01f1YyjUT0O8BSNYzeBqnB rPsetCommon-StatusNEWid782920 1gdRk5XRHFhRtfhphbzeMA material-327866IfcMaterialLayerSet327862327864327865poche 1QhMrYEAv79e7i0ARFIghL 1K$hbkmKj1NxKf5WHcar6w material-poche rPsetCommon-StatusNEWid740904 17KVcdI0r9BxsP_6AnFvdu 14xr3H$0vEs9w4alECdOsi rPsetCommon-StatusNEWid764439 0Lgjg5L7nF48aEs9DajBcI rPsetCommon-FireRating2HRid782381StatusNEW 1RfFvqxPz07vR$lhP8aGm8 material-378564IfcMaterialLayerSet378563poche IfcWall 2FxjDQ6L929PRka772qOyx rPsetCommon-StatusNEWid740908 rPsetCommon-StatusNEWid780668 rPsetCommon-FireRating2HRid782419StatusNEW 0H0_od7V10JhlMbIqgoWO3 1T7r512pb9hPEjURMceUG1 rPsetCommon-StatusNEWid740954 rPsetCommon-FireRating2HRid783190StatusNEW material-781395IfcMaterialLayerSet781397781398781399poche rPsetCommon-StatusNEWid740970 0kKdq9Psj4WvlDmZHTpwTM`
```

**Comment by Moult** [comment]
I don't think this is a bug. What seems to be happening is that your JoinCriteria does not specify fire rating as a criteria to be checked, so walls are merged and therefore hatching is merged. If you change the criteria to 
`r"Pset.*Common"."Status",r"Pset.*Common"."FireRating"` or `r"Pset.*Common"."Status",type.Name` then it looks correct.

Before

![2023-07-27-221004_980x709_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/a54960fb-5bb1-4b51-802a-360700ea76c4)

After:

![2023-07-27-221010_965x689_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/58a2f963-f004-4161-a46e-d5013c70f70a)
