### ISSUE TITLE
Space regen conflicts with DEMOLISH walls

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3491]
Space regen conflicts with DEMOLISH walls

files: https://gitlab.com/openingdesign/milwaukee_st_4429/-/archive/3a842262ca4fa1c13da843a20e05b1b3751b2492/milwaukee_st_4429-3a842262ca4fa1c13da843a20e05b1b3751b2492.zip?path=Models/BlenderBIM

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d5501bbb-e960-4747-b80a-e617955cd43a

**Comment by maxfb87** [comment]
The problem here is that "generate_spaces_from_walls" considers only selected walls and "regen_space" (that is basically "generate_space") considers all walls, in this case also the demolished ones...

@theoryshaw what do you think if "regen_space" considers only the _visible_ walls?

**Comment by theoryshaw** [comment]
Yes, i think that makes sense. 
Can't think of a use case where it wouldn't.
