### ISSUE TITLE
Array modifier : Lock arrayed objects transforms in the viewport ?

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3492]
I was thinking, in order to prevent moving arrayed instances in the viewport maybe we could lock their transforms ? That way users can't unintentionally move arrayed items, since they're supposed to be placed by the array instancer if I understand coorectly ?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/4e988422-ff16-469e-b7ee-6fe446496fc8)

**Comment by theoryshaw** [comment]
I'm hesitant on this idea, as described [here](https://github.com/IfcOpenShell/IfcOpenShell/issues/3331#issuecomment-1602553775). 

If, however, there was a way, when all the objects in the array are selected, that this lock was turned off automatically, perhaps.

**Comment by Gorgious56** [comment]
Fair point. I think it may be solved with either :
- parenting the instances to the instancer, but parenting can lead to funky behaviour and you can only parent an object to one other object
- Using a Child of constraint on the instances. A nice benefit is you get a dotted line in the interface to communicate the relationship.

![array](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/f99da50e-e3e0-4235-8890-b404edefa28d)

**Comment by theoryshaw** [comment]
yeah, that could work. 
Would be nice, however, in this approach if `bim.select_all_array_objects` made the parent the active object... i think currently, it makes the last object in the array, active.

**Comment by theoryshaw** [comment]
...or when `bim.select_array_parent` is used, that it deselects everything, except the parent.

**Comment by theoryshaw** [comment]
ping @brunoperdigao for thoughts too.

**Comment by Moult** [comment]
I have generally been against Blender parenting or constraints because I've found they don't scale well on large projects. (e.g. people in the past have suggested all objects on a storey be parented to the storey). But this is a smaller usecase and potentially temporary so my usual arguments don't apply.

What's wrong with the lock? Can't the user just see a "Lock Status" in the Array panel and toggle it on/off? Maybe it defaults to on?

**Comment by Gorgious56** [comment]
I think I managed to make something workable. The constraint system turned out to give me some weird results but overall it should be good now. In the end I didn't provide a global lock/unlock button in the interface since IMO there is no need for it now. All children instances are locked. Selecting either all objects in the array or only the parent will move everything when the user uses the transform tool thanks to the constraints.

I also added a "Apply Array" button because the current workflow seemed a bit farfetched :p

Here's a snippet. Please feel free to provide feedback :)

![array2](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/3a8062eb-0994-4cad-9ab3-7b15ab9e0faf)

The biggest problem I see now is performance, it is abysmal when we get into the hundreds of instances. Constraints are not helping I'm sure.

BTW I'm still not sure what "Sync children" does, any clue ?

**Comment by theoryshaw** [comment]
Very cool!

>  BTW I'm still not sure what "Sync children" does, any clue ?
https://community.osarch.org/discussion/comment/16300/#Comment_16300

**Comment by theoryshaw** [comment]
Just a small UI comment, I feel like those (2) icons should be different...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/13fda263-ca86-4747-bb53-072cddbf07c5)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f53bc1b7-c9fd-4424-baeb-858dd9d0f211)

Maybe keep the "CHECKMARK" for one of them, and use either...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/6bc287b7-caa8-4c85-b39e-e533a69c9fd3) for  `bim.apply_array`

or maybe
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/cc936117-a002-48ad-b756-380f880752be) for `bim.edit_array`

**Comment by theoryshaw** [comment]
Just a small UI comment, I feel like those (2) icons should be different...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/13fda263-ca86-4747-bb53-072cddbf07c5)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f53bc1b7-c9fd-4424-baeb-858dd9d0f211)

Maybe keep the "CHECKMARK" for one of them, and use either...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/6bc287b7-caa8-4c85-b39e-e533a69c9fd3) for  `bim.apply_array`

or maybe
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/cc936117-a002-48ad-b756-380f880752be) for `bim.edit_array`

**Comment by Gorgious56** [comment]
Yeah that's been bothering me too after testing it for a bit, and it doesn't help that the two icons are located at the same place in the UI. I followed the convention for the icon used to apply vanilla blender modifiers. But the checkmark is also used in every other BlenderBIM situation where the user needs to validate a change.

But I think following the recent discussions regarding Ifc jargon vs architect jargon vs layman terms vs blender terms the "unlink" icon does make sense for applying an array, and it may benefit from being renamed to something else. "Applying" a modifier is a very blender-y term that I don't know if newcomers will understand what it means.

**Comment by brunoperdigao** [comment]
@Gorgious56 I'm late to the discussion, but I just wanted to say that agree with the improvements.

**Comment by Gorgious56** [comment]
Thank you ! There has been no obvious negative feedback so I'll close this in the meantime.
