### ISSUE TITLE
importing IFC in EC700 - energy analisys

### ISSUE THREAD

**Issue by uilli-github** [IfcOpenShell/IfcOpenShell#3497]
importing IFC4 in other software i've a problem. My ifcSpace is not imported because ifcpolygonalfaceset must be set to "closed". How can I set attribute to closed for my spaces?

**Comment by Moult** [comment]
@uilli-github that's pretty interesting, the closed attribute is optional so I'm surprised if a software uses that as a filter to allow / disallow loading IFCs. In any case, we've now implemented it.
