### ISSUE TITLE
When creating an IfcClass, include other attributes as well, in the UI?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3500]
When creating a new class, does it make sense to...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b273fd8a-e05b-4664-be0e-1c9ddcb5649d)

...include the following in the UI as well? 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/fceccd12-f313-4e3a-927d-33cd12fd97d6)

**Comment by Moult** [comment]
I'm unsure. For types, definitely at a minimum a good name is required and then as a bonus a description is desirable.

Tag is rarely used in native IFC. ApplicableOccurrence only applies to certain things. For occurrence elements, name and description is almost never useful.

Name also comes automatically from the Blender object name.

**Comment by Moult** [comment]
Closing as after giving it more thought I don't think this is a good idea, as name comes from the Blender name, description is only typically used for types, applicableoccurrence is almost never needed except for type products and it'll be less needed in IFC4.4 as new types get introduced and tag doesn't apply in native IFC.
