### ISSUE TITLE
Easy way to select objects with similar attributes...

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3502]
Similar to https://github.com/IfcOpenShell/IfcOpenShell/issues/3268, would be nice to have an easy way to select objects with similar attributes...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/1a6d9945-3321-4261-bfa5-49d60e20e2ca)

**Comment by Moult** [comment]
I'm really not a fan of having these arrow icons on every single property (and here attributes).

What if the Search panel had a "Select Similar" section which had a dropdown already populated with every attribute and property that the active selected object has? So you'd 1) select an object 2) go to search panel 3) select from dropdown say "ObjectType" then 4) press search button? It's two extra clicks though (and potentially a scroll / click to go to the search panel).

Or what if the "Select similar" button only showed up when editing attributes? So 1) Select object 2) Enable editing attributes 3) Click Select Similar. That's one extra click.

**Comment by Gorgious56** [comment]
Or a single cursor icon to toggle the attribute selection mode ? I think it's not so intuitive to have to edit attributes to be able to use this feature.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/abd83c63-1ff0-44cd-9f41-03a0a1798906)


I like the select similar panel idea with dynamically populated choices too.

**Comment by Moult** [comment]
The added benefit of the select similar panel is that we can extend it in the future with more features like select similar based on multiple attributes, or "save similar to search group", "apply colour legend" etc.

**Comment by theoryshaw** [comment]
dumb question, is there any way to just click the value?

![2023-07-26_08-41-32_KeyShowView_Carnac](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d980ee62-9a85-45a0-8789-337128ad18b0)

**Comment by theoryshaw** [comment]
> I like the select similar panel idea with dynamically populated choices too.

but yes, i like this idea too.

**Comment by theoryshaw** [comment]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3a17a672-8e14-4b2f-934c-299af1e6d18d)
this is clever... i like it.

**Comment by TZwielehner** [comment]
This issue is closed, but I would like to add one more comment. Many programs add such commands to a context menu in order to not overload the gui. Another idea (from web development) would be a "on hover" effect. Not sure if blender supports this.

**Comment by Moult** [comment]
Blender doesn't do :hover afaik, and I'm not aware of any right click menus used in the properties UI type - it's probably technically possible but not part of the paradigm.

Yeah indeed I think sooner or later the "Select Similar" panel will link to the "Search" and "Colour By Property" panel so they all speak to one another.

**Comment by theoryshaw** [comment]
The UI might have been clunky here, but I do miss this feature.

**Comment by Moult** [comment]
The feature now exists in its own panel?

**Comment by theoryshaw** [comment]
yes, i know. :)

**Comment by theoryshaw** [comment]
The following PR proposes running bim.select_similar by clicking the values in the pset or attribute panels, for quick, easy access.  

https://github.com/IfcOpenShell/IfcOpenShell/pull/4611
