### ISSUE TITLE
Cant enable blenderbim addon

### ISSUE THREAD

**Issue by dei574** [IfcOpenShell/IfcOpenShell#3505]
Hello I can´t enable the blenderbim addon here is the review, hope someone can help me out

**Comment by dei574** [comment]
![fehlermeldung](https://github.com/IfcOpenShell/IfcOpenShell/assets/140555949/bb970cfa-f588-44a9-ace1-18eea9df701a)

**Comment by Moult** [comment]
Can you follow the uninstall steps here https://blenderbim.org/docs/users/installation.html#uninstalling then try reinstall? If you are downloading from Github, be sure to follow the developer install instructions https://blenderbim.org/docs/devs/installation.html#unstable-installation

**Comment by Gorgious56** [comment]
Maybe https://github.com/IfcOpenShell/IfcOpenShell/issues/3216 will yield some answers ?

**Comment by Moult** [comment]
See https://community.osarch.org/discussion/1583/blenderbim-no-module-named-shapely-lib-error-while-installing-addon#latest

Can you confirm the Blender Python version?

**Comment by dei574** [comment]
PYTHON INTERACTIVE CONSOLE 3.11.3 hope tgis is what you ment by confirm python version...

**Comment by Moult** [comment]
Yep, so you've probably installed Blender from your repos distro which bundles Python 3.11. Unfortunately we don't support that and you'll have to use the blender that comes from Blender.org.

It's unfortunate but we need more developer resources and funding to ship more platforms https://blenderbim.org/docs/devs/system_support.html

**Comment by dei574** [comment]
thank you now it works:) thank you for the great work developing the blenderbim addon
