### ISSUE TITLE
These (3) instances have the same type, but they are not the same.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3506]
These (3) instances have the same type, but as you can see, the one on the left is not the same. 

files, [here](https://gitlab.com/openingdesign/milwaukee_st_4429/-/archive/1953d9bf365458cbf8dcef85189e3b4cb98c3b61/milwaukee_st_4429-1953d9bf365458cbf8dcef85189e3b4cb98c3b61.zip?path=Models/BlenderBIM).

![2023-07-25_21-16-28_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c36c69fa-335b-4b81-9116-1937e601c16a)

**Comment by theoryshaw** [comment]
If you toggle the instance, with another instance, and then back to it's original again, the one-to-many connection is revived.  However if you save, and open the ifc file, it's broken again. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/af788798-acd4-4674-b013-d169b1b7896d)

**Comment by Moult** [comment]
There is something more fundamental at play here that caused these three types to fall out of sync but I don't know what. I checked the assign_type operators as well as the update representation operators but couldn't spot anything. Do you recall anything you did / environment that could make that toilet different from the other two?

For now you can solve it by unassigning the type, then reassigning it back to THIN_TYPE then saving.
