### ISSUE TITLE
Possible for `Qto_BodyGeometryValidation` to be added to `IfcGeographicElement`?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3509]
Possible for `Qto_BodyGeometryValidation` to be added to `IfcGeographicElement`?
Or is there another way to calculate quantities for `IfcGeographicElement`?

![2023-07-26_14-53-43_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/bae20978-5ee0-42aa-8cdd-066d235a16df)

**Comment by aothms** [comment]
Just a quick note that this set is purely defined with implementations in mind to verify they import the geometry correctly. It's not really intended for capturing quantities that are relevant to end users.

**Comment by Moult** [comment]
Completely agree, filed a bug upstream: https://github.com/buildingSMART/IFC4.3.x-development/issues/667
