### ISSUE TITLE
Can't get the spatial's materials

### ISSUE THREAD

**Issue by whsqjss** [IfcOpenShell/IfcOpenShell#351]
I parse IFC file use Ifcopenshell_wrapper to create shape,but can't get the spatial's materials,I wonder if  I use the wrong settings?

![image](https://user-images.githubusercontent.com/35548533/37344647-ea13413c-2705-11e8-9ec8-7b6353be4e7c.png)

**Comment by whsqjss** [comment]
p.s.  After I try to find the material,I  found that if the material's thickness equals zero , the IfcMaterial's property 'HasRepresetation' will be Null.

**Comment by aothms** [comment]
So, IfcOpenShell is probably not as clear as it could be but the data you get from `shape.geometry.materials`  are actually related to the IfcStyledItems associated to the individual representation items.

Now, IfcMaterials and  IfcStyledItems can be linked, indeed, as you mention by IfcMaterialDefinitionRepresentation.

You can probably still get the materials by means of the IfcProduct.HasAssociations.

Is that helpful somehow?

**Comment by whsqjss** [comment]
Thank you for your reply.
The problem that how to get the shape's colours has plagued me for a long time.
Is there any way to get shape's colours by using IfcOpenShell?

Best regard

**Comment by aothms** [comment]
The way above seems appropriate. Does it not work on a general test model such as the Duplex apartment: https://www.nibs.org/?page=bsa_commonbimfiles#project1 "

Portal Login Get Involved Supporters Committees Board About Proceedings Projects & Standards Home     bSa / Projects & Standards / Information Exchange / Common BIM Files and Tools Common Building Information Model Files and Tools by E. William East, PhD, PE - Engineer Research and Development Center, U.S Army, Corps of Engineers  Within This Page  How To Use This Page Project 1. Duplex Apartment Project 2. Office Building Project 3. Medical Clinic Project 4. Barracks 101 Free Software   How To Use This Page The information on this page can assist you to:   Download "information exchange" example files in different file formats   See how model data from different disciplines is organized   Compare files to see model content for different domains   See how exchanges, such as COBie, change over time   Use these common files to evaluate your software's import or export functions   Use these common files to teach building information modeling   Extend these common files for new information exchanges and research   Find and use free tools to help you work with these files   Project 1. Duplex Apartment The duplex apartment model was originally created by a student who  developed this building as part of a design competition. This model was  first used at the Dec 2009 COBie Challenge event. COBie  2012-03-23-Duplex-01-Programming 2012-03-23-Duplex-02-Design 2012-03-23-Duplex-03-ProductSelect 2012-03-23-Duplex-04-ProductInstall 2012-03-23-Duplex-05-Handover  Coordination Model View  2011-09-14-Duplex IFC 2x3 Coordination MVD 2011-09-14-Duplex-IFCAnalyzer 2011-09-14-Duplex-PDF 2011-09-14-Duplex-RVT (as documented in this report and shared parameter information)  Electrical System information exchange (Sparkie) at Design  2012-12-07 IFC 2x3 Sparkie 2012-01-02 Native Model (report in editorial review)  HVAC information exchange (HVACie) at Design  2011-11-24 IFC 2x3 2011-11-24 Native Model (report in editorial review) 2011-11-24 Native Model supplement  Water System information exchange (WSie) at Design  2012-11-13 IFC 2x3 2013-02-01 Native Model (report in editorial review)  Project 2. Office Building The two story office building model was developed based on the  published sample floor plans for a specific type of mid-size office  building built in the United States. COBie Spreadsheet  2012-03-23-Office-COBie  Coordination Model View  2011-09-14-Office IFC 2x3 Coordination MVD 2011-09-14-Office-IFCAnalyzer 2011-09-14-Office-PDF 2011-09-14-Office-RVT (as documented in this report and shared parameter information)  Electrical System information exchange (Sparkie) at Design  2012-12-07 IFC 2x3 Sparkie 2013-02-01 Native Model (report in editorial review)  Water System information exchange (WSie) at Design  2012-12-05 IFC 2x3 WSie 2013-02-01 Native Model (report in editorial review)  Project 3. Medical Clinic The Clinic Model project is based on a medical and dental clinic  building at a location in the South-West United States. The model also  comes with a set of redacted design drawings. A representative set of  redacted operations and maintenance manuals are also provided in COBie  Spreadsheet Format. Please note that vendors' implementations of these  files may be found on the bSa Means and Methods Page. COBie Spreadsheet  2013-03-28-Clinic-Programming-v13 2013-03-28-Clinic-Design-v13 2013-03-28-Clinic-Handover-v13 (ZIP)  COBieLite  COBieLite Clinic Handover Example (ZIP) COBieLite LCie Examples (ZIP)  Construction Drawings  2012-03-27-Clinic-RedactedDrawings  Coordination Model View  2011-09-14-Clinic IFC 2x3 Coordination MVD   2011-09-14-Clinic-IFCAnalyzer  2011-09-14-Clinic-PDF  2011-09-14-Clinic-RVT (as documented in this report and shared parameter information)  Electrical System information exchange (Sparkie) at Design  2012-12-07 IFC 2x3 Sparkie 2013-02-01 Native Model (report in editorial review)  HVAC information exchange (HVACie) at Design  2012-03-30 IFC 2x3 HVACie 2012-03-30 Native Model (report in editorial review) 2012-03-30 Supplemental Native Files  Water System information exchange (WSie) at Design  2012-12-06 IFC 2x3 WSie 2013-02-01 Native Model (report in editorial review)  Project 4. Barracks 101 Barracks 101 is a small building developed from the standard design  of a similar federal government building.  As this model includes  drawings, it would be a very good for use by students and those  conducting initial testing of their software before jumping to the full  size Medical Clinic problem model. COBie Spreadsheet  2013-08-05-Barracks101-Handover   Design Drawings  2013-02-11-Barracks101-DesignDrawings-PDF   AutoCAD files  (coming January 2014)   Free Software The following is a list of free software that you may find helpful  when working with the Common BIM Files.  These products are listed  without endorsement of any kind.  If interested in Commercial software  that can be used with these models please see the information exchanges: Means and Methods page    Product (listed alphabetically) Type Description Applicability   Acrobat Reader Free A free, commercial product that maybe used to view 3D PDF files produced from IFC models using paid products Any "ie"   bimServer.org Open Source An IFC-based model server for life-cycle BIM application Any "ie"   (bimserver-baesd)bimSurfer Open Source An IFC-based model viewer plug-in that works with bimserver.org Any "ie"   (bimserver-based)COBie Tool Kit Open Source A free, model transformation, checking, and reporting a custom build  of the bimserver.org product used in COBie Challenge events. COBie, …   bimServices Commercial Free, prototype for model transformation, checking, and reporting. (Last updated 2010) COBie   DDS-CAD Viewer Free A free, commercial IFC modeling tool Any "ie"   EcoDomus PM Commercial Free, commercial product to help validate design information and deliver construction handover information COBie   Google Docs Commercial An example of how to use free Google tools to create web-based spreadsheet for updating COBie data COBie   IFC File Analyzer Free A free, research prototype product that may be used to summarize and report on the content of IFC model files. Any "ie"   ifcStoreyView Free A free, research prototype that may be used to view IFC model files (Last update 2009) Any "ie"   Onuma System Commercial Free, commercial product to check COBie files COBie   Solibri File Optimizer Free A free, commercial product that may be used to reduce the number of  repeated IFC objects in a model.  The reduction in file size is often  substantial Any "ie"    Back to Information Exchange Projects | Product (listed alphabetically) | Type | Description | Applicability | Acrobat Reader | Free | A free, commercial product that maybe used to view 3D PDF files produced from IFC models using paid products | Any "ie" | bimServer.org | Open Source | An IFC-based model server for life-cycle BIM application | Any "ie" | (bimserver-baesd)bimSurfer | Open Source | An IFC-based model viewer plug-in that works with bimserver.org | Any "ie" | (bimserver-based)COBie Tool Kit | Open Source | A free, model transformation, checking, and reporting a custom build  of the bimserver.org product used in COBie Challenge events. | COBie, … | bimServices | Commercial | Free, prototype for model transformation, checking, and reporting. (Last updated 2010) | COBie | DDS-CAD Viewer | Free | A free, commercial IFC modeling tool | Any "ie" | EcoDomus PM | Commercial | Free, commercial product to help validate design information and deliver construction handover information | COBie | Google Docs | Commercial | An example of how to use free Google tools to create web-based spreadsheet for updating COBie data | COBie | IFC File Analyzer | Free | A free, research prototype product that may be used to summarize and report on the content of IFC model files. | Any "ie" | ifcStoreyView | Free | A free, research prototype that may be used to view IFC model files (Last update 2009) | Any "ie" | Onuma System | Commercial | Free, commercial product to check COBie files | COBie | Solibri File Optimizer | Free | A free, commercial product that may be used to reduce the number of  repeated IFC objects in a model.  The reduction in file size is often  substantial | Any "ie"
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Acrobat Reader | Free | A free, commercial product that maybe used to view 3D PDF files produced from IFC models using paid products | Any "ie"
bimServer.org | Open Source | An IFC-based model server for life-cycle BIM application | Any "ie"
(bimserver-baesd)bimSurfer | Open Source | An IFC-based model viewer plug-in that works with bimserver.org | Any "ie"
(bimserver-based)COBie Tool Kit | Open Source | A free, model transformation, checking, and reporting a custom build  of the bimserver.org product used in COBie Challenge events. | COBie, …
bimServices | Commercial | Free, prototype for model transformation, checking, and reporting. (Last updated 2010) | COBie
DDS-CAD Viewer | Free | A free, commercial IFC modeling tool | Any "ie"
EcoDomus PM | Commercial | Free, commercial product to help validate design information and deliver construction handover information | COBie
Google Docs | Commercial | An example of how to use free Google tools to create web-based spreadsheet for updating COBie data | COBie
IFC File Analyzer | Free | A free, research prototype product that may be used to summarize and report on the content of IFC model files. | Any "ie"
ifcStoreyView | Free | A free, research prototype that may be used to view IFC model files (Last update 2009) | Any "ie"
Onuma System | Commercial | Free, commercial product to check COBie files | COBie
Solibri File Optimizer | Free | A free, commercial product that may be used to reduce the number of  repeated IFC objects in a model.  The reduction in file size is often  substantial | Any "ie"

"

**Comment by aothms** [comment]
> but where is the shape's surfaceStyle?I want to get the shape's surface colour.

Maybe I didn't understand you correctly, but:

> So, IfcOpenShell is probably not as clear as it could be but the data you get from shape.geometry.materials are actually related to the IfcStyledItems associated to the individual representation items.

This is almost five months old, feel free to reopen if you're working on this.
