### ISSUE TITLE
Element occurrences should be able to be appended from another project

### ISSUE THREAD

**Issue by Owuraqu** [IfcOpenShell/IfcOpenShell#3511]
The downloaded manufacturer's IFC products come with the right geometry when opened with the right class assigned to them. 
<img width="1792" alt="ShowerScreens_ClassProblem2" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/33836708/76a3c172-58b4-49a6-9b1b-44c279b143a1">

<img width="1792" alt="ShowerScreens_ClassProblem" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/33836708/d70587c8-e072-4df3-b294-ce2c8f2fa7f9">

However, when loaded into BlenderBIM (using Project Setup > Project Library) do not show the right geometry but defaults to a box geometry when added to the project.

<img width="1792" alt="ShowerScreens_ClassProblem3" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/33836708/4b377328-2631-4082-ab2c-b984e2243aad">

**Comment by Moult** [comment]
Cheers, just rewording this as the issue isn't exactly accurate.

**Comment by Owuraqu** [comment]
> 

Well noted @Moult and thank you very much.

**Comment by Owuraqu** [comment]
Great @Moult . Will download the update and try it out again. Thank you.

**Comment by Owuraqu** [comment]
@Moult Hello, I tried again to import the external ifc library (sanitary, appliances etc.) but still have the same issue.

What could I not be doing right since I used the same process as discussed in the OSArch forum. Thank you.

**Comment by Moult** [comment]
What's the issue you have?

**Comment by Owuraqu** [comment]
I am able to successfully import the downloaded manufacturer's Ifc model into BBIM via Project Setup>>Project Library>>IfcProductType>>IfcFurnitureType. This is after I have converted from the original [IFC2x3 file here](https://www.dropbox.com/scl/fi/1n8sfk5pcog2xtxh104zg/Sanitary_Shower-screens_ODF-Paris_Shower-screen-1-fixed-1-sliding-panel-up.ifc?rlkey=mvyfzr9mgs1pgd97pz0noc0f4&dl=0) to [IFC4 file here] (https://www.dropbox.com/scl/fi/o8xo0i0mq4vwvh5ny6dxa/Sanitary_Shower-screens_ODF-Paris_Shower-screen-1-fixed-1-sliding-panel-up-IFC4.ifc?rlkey=dzdtcm6v7e3ocqqnrepgawv2y&dl=0).

However when I add it using the BIM Tool it still comes as a cube.

**Comment by theoryshaw** [comment]
I'm not sure what happened, but this is how to make it 'work again'. :)
https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b4c8264e-d777-445b-aa12-2d19c70b330f

**Comment by Owuraqu** [comment]
Awesome! Working now except the product dimensions cannot be permanently changed. I am able to change dimensions but anytime I use the 'Activate Drawing' tool they all revert back to the original dimensions they were import with. How do I change that permanently. Thank you.

**Comment by Owuraqu** [comment]
Also how does the importing process work for doors and windows because it's not working for me for all types I have tried.

**Comment by theoryshaw** [comment]
> How do I change that permanently. 

I should save the dimensional change automatically, but try to use 'Manually save Representation', if it doesn't...
https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5fe64a0a-459e-4d47-a347-9ba77ff909e0

> Also how does the importing process work for doors and windows because it's not working for me for all types I have tried.
should be the same approach. 

Should be the same approach.  When you say "not working for me"... can you provide more details?

**Comment by Owuraqu** [comment]
> I should save the dimensional change automatically, but try to use 'Manually save Representation'

Okay will give it a try. 

> Should be the same approach.  When you say "not working for me"... can you provide more details?

When I import the windows and go to Window (under the 'Parametric Geometry' tab) it reads 'No Window Found', and when I click on the '+' button it changes the window and its geometry entirely (changed to I believe BBIM default window).

**Comment by theoryshaw** [comment]
Can you share the file?

**Comment by Owuraqu** [comment]
> Can you share the file?

[File here](https://www.dropbox.com/scl/fi/ub7a6013fh0svq4d7uqct/Ensemble-r-no-horizontal-1-zone-M-O-IFC4.ifc?rlkey=1jnzzjo1gifn7358frnv9lywg&dl=0)

**Comment by theoryshaw** [comment]
It had something to do with the material assignment.  I deleted that, and it came through...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d639b356-f935-415a-831c-d11e648945ef

**Comment by Owuraqu** [comment]
Good but the problem still persists; 'No Window Found' (under the 'Parametric Geometry' on the 'Geometry and Material' tab. Without that I cannot change the window parameters.

**Comment by theoryshaw** [comment]
Did you make this window in another program, and export it as a IFC2x3 and then upgrade it to IFC4, with BB?

**Comment by Owuraqu** [comment]
> Did you make this window in another program, and export it as a IFC2x3 and then upgrade it to IFC4, with BB?

No I downloaded [the IFC file here](https://www.bimobject.com/en/meo/product/meo-f-pf-1vtl-hz)from bimobjects.com and came in as IFC2X3. Then I upgraded it to IFC4 with BB.

**Comment by theoryshaw** [comment]
Although BB uses [IfcWindowLiningProperties](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcWindowLiningProperties.htm) schema properties, the parametric windows in BB, are specific to BB.  That is, I know of no other program yet that can create an parametric window that BB can read, whereby you can edit it's parametric properties in BB.


I see that that `Ensemble réno horizontal 1 zone MéO-IFC4.ifc` file has IFCWINDOWLININGPROPERTIES, but they are all empty `$`.

```
#1493=IFCWINDOWLININGPROPERTIES('18_kecJdT4Gfg3rKk6KHoS',#1398,'Ensemble r\X2\00E9\X0\no horizontal 1 zone M\X2\00E9\X0\OO:Ensemble r\X2\00E9\X0\no horizontal 1 zone M\X2\00E9\X0\OO:339398',$,$,$,$,$,$,$,$,$,$,$,$,$);*/
```

...

BB codifies it Window Lining Properties into a it's own unique property set. 
```
#67=IFCPROPERTYSET('2oyRF$JDbAW8xr2gsOj6oP',$,'BBIM_Window',$,(#68));
  /*#68=IFCPROPERTYSINGLEVALUE('Data',$,IFCLABEL('{"window_type": "SINGLE_PANEL", "overall_height": 0.8999999761581421, "overall_width": 0.6000000238418579, "lining_properties": {"lining_depth": 0.05000000074505806, "lining_thickness": 0.05000000074505806, "lining_offset": 0.05000000074505806, "lining_to_panel_offset_x": 0.02500000037252903, "lining_to_panel_offset_y": 0.02500000037252903}, "panel_properties": {"frame_depth": [0.03500000014901161, 0.03500000014901161, 0.03500000014901161], "frame_thickness": [0.03500000014901161, 0.03500000014901161, 0.03500000014901161]}}'),$);*/
```

...

All this is to say, you can't parametrically modify `Ensemble réno horizontal 1 zone MéO-IFC4.ifc` in BB, you'll have to modify the vertices of it's mesh instead.

**Comment by Owuraqu** [comment]
Well noted and I believe this issue is worth looking at for future possibilities. 

Thank you very and you have been incredibly helpful:).
