### ISSUE TITLE
Error using the draw function

### ISSUE THREAD

**Issue by idoglanz** [IfcOpenShell/IfcOpenShell#3525]
Hi!
I'm trying to use the draw function to generate an svg from an IFC and I'm getting this error:

```
File "~/Library/Caches/pypoetry/virtualenvs/ifc-playground-le_g9z_9-py3.9/lib/python3.9/site-packages/ifcopenshell/draw.py", line 203, in main
    svgfill_context = W.context(W.FILTERED_CARTESIAN_QUOTIENT, 1.0e-3)
AttributeError: module 'ifcopenshell.ifcopenshell_wrapper' has no attribute 'context'
```
I've downloaded the latest build and copied it over to the site-packages, but was I supposed to do anything else? are there any other libraries I need?

I also tried using Pypi but that leads to a different error (`AttributeError: 'SvgSerializer' object has no attribute 'setUsePrefiltering'`)

Thanks!

**Comment by Moult** [comment]
Does this exist?

```
>>> ifcopenshell.ifcopenshell_wrapper.context
<class 'ifcopenshell.ifcopenshell_wrapper.context'>
```

Can you do `print(ifcopenshell.version)`?

The error about prefiltering suggests you have an old ifcopenshell.

**Comment by Moult** [comment]
The easiest installation method is https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#pre-built-packages

Be sure to do `print(ifcopenshell.__file__)` to make sure you have installed it to the right location.

**Comment by idoglanz** [comment]
It seems to be in the right location, is the version I have stable? (`HEAD detached at dc67287d)-dc67287d`)

Aside from extracting the file and adding it to the python path do I need to build anything?

**Comment by Moult** [comment]
Your version is from Jul 18, 2022: https://github.com/IfcOpenShell/IfcOpenShell/commit/dc67287d - that's very, very old. It sounds like the installation isn't right. Have you double checked the install path as well as the Python version?

**Comment by idoglanz** [comment]
Thanks! It indeed was a very old version which I suspect was caused by poetry cache or something. I ended up using conda and it now works 💪

BTW, I don't want to be too greedy, but is there a way to make the export a bit faster...?

Thanks!

**Comment by Moult** [comment]
You mean the SVG export? It really depends on a lot of factors. But admittedly there is still a lot of optimisation work to be done. If you can help by providing simple test cases that demonstrate performance bottlenecks that would be the best way to contribute (apart from code and funding).
