### ISSUE TITLE
BlenderBim - UI feature request - N panel change typical naming to " 'X' tool "

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3527]
The new N-panel icons are brilliant and amazing,

For those of us who use hotkeys especially the quick favourites menu having each tool be labled " create ' x ' "
doesnt quite work intuitively since blender randomly assigns the hotkey
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/ef1e0d16-81c3-400a-ad7e-43d3945df28a)
So it ends up going create wall = c

Would it be possible to change the naming to how it was with the Bim tool?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/3005166e-cf98-4080-ad99-07623a09a2cd)

so 'create wall' becomes "Wall tool"

I think then atleast the automatic hotkey selection will choose those 1st unique letters which make slightly more sense

**Comment by Moult** [comment]
X Tool? What are we, Twitter? :D

**Comment by trhyder** [comment]
@Moult, I believe this issue can be closed
