### ISSUE TITLE
Add new classification library

### ISSUE THREAD

**Issue by movilarq** [IfcOpenShell/IfcOpenShell#3529]
Hi! I am using Blender 3.6.1 (blenderbim add-on v0.0.230725-0d65604), and I am traing to add a new custom classification library but is not working. No error messages. Just nothing.
Thanks !

**Comment by c4rlosdias** [comment]
https://www.dropbox.com/scl/fi/z5k9n4jl4aux99sj9gkay/2023-07-17_11-13-27_github.com_MoultIfcClassification_MoultIfcClassifi_chrome.mp4?dl=0&rlkey=xaqbbr8eyaodnyrnjy05lyp8g

**Comment by Andrej730** [comment]
@movilarq can you please share an example of the clssification library you're trying to add?

**Comment by movilarq** [comment]
Hi,
thanks you for your help!!! I finaly fix the problem installing last
upgrades !!!!
I am very excited because the latest version and upgrade !!!!
It is the best Bim software by far!!
