### ISSUE TITLE
Broken express_parser.py

### ISSUE THREAD

**Issue by frozar** [IfcOpenShell/IfcOpenShell#353]
I'm really new to this project and try to do my best to discover it.

I wonder if it is possible to generate the code to parse the lastest [IFC4_ADD2.exp](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/IFC4_ADD2.exp). In the file "src/ifcexpressparser/README.txt", it is written: 
https://github.com/IfcOpenShell/IfcOpenShell/blob/e87a1a0b32cacbbecb7b3cc428bdb2d3f362e148/src/ifcexpressparser/README.txt#L1-L9

So I download the `IFC4_ADD2.exp` file and naively try the command:
```bash
python bootstrap.py express.bnf > express_parser.py && python express_parser.py IFC4_ADD2.exp
```
 
As an output, I get an error which say:
```
Traceback (most recent call last):
  File "express_parser.py", line 468, in <module>
    ast = syntax.parseFile(sys.argv[1])
[...]
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 779, in wrapper
    ret = func(*args[limit[0]:])
TypeError: <lambda>() takes exactly 1 argument (0 given)
```

Is it possible to generate the code which would be able to handle IFC4X2 files from `IFC4_ADD2.exp`? Or do you process it in an another way?

**Comment by aothms** [comment]
That should totally work. What version of pyparsing are you running. I am on the latest 2.2.0 and am not experiencing issues.

**Comment by frozar** [comment]
Hi,

First of all, I just notice that I used python2.7 when I wrote this issue, so sorry for that.

By the way, I try with python3:
```bash
python3 bootstrap.py express.bnf > express_parser.py && python3 express_parser.py IFC4_ADD2.exp
```

I get the following output:
```
Traceback (most recent call last):
  File "express_parser.py", line 460, in <module>
    import header
  File "/home/frozar/wk/IfcOpenShell/src/ifcexpressparser/header.py", line 24, in <module>
    import documentation
  File "/home/frozar/wk/IfcOpenShell/src/ifcexpressparser/documentation.py", line 51, in <module>
    for oid, name, desc in csv.reader(f, delimiter=';', quotechar='"'):
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 6602: invalid start byte
```

My version of pyparsing under python3 is: 2.0.3

I am on the (updated) master branch and the error doesn't seem to be about pyparsing module. Am I missing something?

**Comment by aothms** [comment]
Hi, the first error you posted is really specific to pyparsing:

~~~
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 779, in wrapper
    ret = func(*args[limit[0]:])
TypeError: <lambda>() takes exactly 1 argument (0 given)
~~~

First thing I'd try is update pyparsing and try again with the python 2 interpreter.


Unfortunately the documentation files from which the code comments are generated do contain some unicode errors, but it depends on py version and platform whether those result into actual exceptions. What you can do is try changing the `open()` calls in documentation.py to `open(..., encoding='utf-8', errors='ignore')`

I don't really want to spend time fixing them as the documentation files are outdated and we should migrate to using IfcDoc.

**Comment by frozar** [comment]
Thank you for the explanation. I update pyparsing with pip and get the version 2.2.0. In this configuration, using python 2 interpretor, it works :+1: 

In python 3, if I do some work about documentation.py, I'll let you know, but for the moment, I keep it as is ^^'
