### ISSUE TITLE
slab and door plan rendering effect.

### ISSUE THREAD

**Issue by chopinregis** [IfcOpenShell/IfcOpenShell#3531]
Currently when we apply the "calculate shapely surfaces, and generate the plan on sheet, the door in red did not render well as did the other doors, which understood that the slab is beneath the door. Instead it rendered as if the door instead carved the slab beneath it.
link to the ifc file on gitlab
https://gitlab.com/openingdesign/salon_studios.git

![Snipaste_2023-07-31_17-26-51](https://github.com/IfcOpenShell/IfcOpenShell/assets/13260872/c0a4838c-8470-4f2f-adfe-2f1ec2e151c1)

**Comment by Moult** [comment]
![2023-08-31-164322_993x740_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/a94da290-1850-4051-bb49-317942444338)
