### ISSUE TITLE
PartOf Facet lacks a fallback "is_pass" value 

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#3532]
https://github.com/IfcOpenShell/IfcOpenShell/blob/4efe198dbba9f131a6750874801e912e999d0882/src/ifctester/ifctester/facet.py#L392C22-L392C22

It's been a while since i've looked at IDS in detail, but am I right to assume that there is a missing is_pass = True line here?

**Comment by Moult** [comment]
I think it's OK because the if statement on the line afterwards should cover all possible scenarios and set the is_pass accordingly. If it doesn't cover all possible scenarios, the part of facet is invalid according to the XSD.

**Comment by vulevukusej** [comment]
Yeah fair enough, I was experimenting with intentionally making the code fail, which is when the lacking is_pass value causes an error.
