### ISSUE TITLE
Wrong annotation position for Wavefront OBJ

### ISSUE THREAD

**Issue by pbbr** [IfcOpenShell/IfcOpenShell#3536]
Hello

If we convert 2d geometries (e.g. IfcAnnotations) with the "--plan" flag to Wavefront OBJ, we get the wrong positions for the 2d geometries (see example attached).

[TestAnno.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12241865/TestAnno.zip)

Expected result:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79220314/2d9431e2-693d-435c-bd58-064801b783ab)

Current result:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79220314/836ecafd-e49a-45c7-ba5b-348c2242c8cf)

Any idea how to solve this? 

Thanks for your support!

**Comment by pbbr** [comment]
@Moult Any idea how to solve this challenge? We found that this doesn't happen for converting to GLB.

**Comment by aothms** [comment]
Just committed a fix for this. Fresh binary builds will take a week or so still. One workaround for now would be to use `--edge-arrows`. For some reason the code for that takes into account the transformations correctly.

**Comment by pbbr** [comment]
@aothms Very nice, thanks a lot! Looking forward to the new build!
