### ISSUE TITLE
Regression: missing cap in spark plug's model with OCCT 7.2.0

### ISSUE THREAD

**Issue by iras** [IfcOpenShell/IfcOpenShell#354]
The model can be found here: http://openifcmodel.cs.auckland.ac.nz/Model/Details/128

![screen shot 2018-03-14 at 09 05 58](https://user-images.githubusercontent.com/773028/37393847-36002be6-276a-11e8-9f33-dee2706d6c8c.png)

The model on the left is a build with OCE 0.16 whereas the right hand side is with OCCT 7.2.0

**Comment by aothms** [comment]
It's not missing on my end. Are you running code prior to this commit?
https://github.com/IfcOpenShell/IfcOpenShell/commit/b04ca74308a4c5bd9d6eb3b372d8a53945a266f2

**Comment by iras** [comment]
No, it was [1a7a4bd](https://github.com/IfcOpenShell/IfcOpenShell/commit/1a7a4bdc3e3534f058123675801e32d113f771b9)

Ubuntu 14.04, OCCT 7.2.0

**Comment by iras** [comment]
Seems fixed now.

**Comment by iras** [comment]
The hole appears if the setting --sew-shells is added. Treble-checked.

**Comment by aothms** [comment]
Ok, see 42c09de. Apparent `BRepBuilderAPI_Sewing.SewedShape()` can return a compound with faces that are not part of a shell (brep is a hierarchy of Solid > Shell > Face > Wire > Edge > Vertex; Compound being any combination of these).

Unfortunately I don't have time to look into

* why sewing this faceset results into a Shell of 17 faces and one loose face. The geometries seem to coincide at first glance
* which of this behaviour changed in 7.2 (is it the compound structure, sewing failure, ...)
* whether the resulting compound with loose faces will cause havoc later on when such compounds are used as boolean ops!

But at least faces are not silently discarded anymore :)

**Comment by iras** [comment]
Many thanks for adding the error logging relative to this issue! I shall leave this issue open for the time being.

**Comment by aothms** [comment]
> Many thanks for adding the error logging relative to this issue

It's not only a message, the loose faces are also added as elements in a compound [1]. If there are still issues with this please reopen.

[1] https://github.com/IfcOpenShell/IfcOpenShell/commit/42c09deb8c413d50ab64584c3ccaaccade6f475f#diff-662210383372f94d2d123befe3de6b95R256
