### ISSUE TITLE
[IfcTester] In the bcf report file, there are no GUID from the ifc 

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#3541]
With the sample file from bSI:

https://github.com/buildingSMART/IDS/blob/master/Documentation/library/sample.ids
https://github.com/buildingSMART/IDS/blob/master/Documentation/library/sample.ifc

i created a little script with IfcTester to test it. 

Here the json output:

![notepad++_GZGisTk2FC](https://github.com/IfcOpenShell/IfcOpenShell/assets/110968398/6934c704-fbec-4273-ba7f-d64f74225b9c)

Here the bcf ouput, one file:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110968398/0bab246e-74cb-473c-b0a2-de70ea39d486)

In the Json ouput there are the GUID from the IFC file, however in the bcf file, i miss them :(

**Comment by Moult** [comment]
Great idea! Would you like to have a shot at implementing this?

**Comment by Moult** [comment]
Alternatively ping @c4rlosdias would you be interested?

**Comment by c4rlosdias** [comment]
Yes, of course! You can leave it with me @Moult

**Comment by Moult** [comment]
@c4rlosdias thanks! I've approved https://github.com/IfcOpenShell/IfcOpenShell/pull/3549 but I think it would be better if the BCF could use the selection / component aspect of BCF such that the object is selected via GUID. Would you like to give that a shot?

**Comment by c4rlosdias** [comment]
Oh get it! I'll try to implement this

**Comment by c4rlosdias** [comment]
I did a test running an IDS and it looks like this aspect of object selection is already working. The add_viewpoint method of topic already increments this.

![Capturar](https://github.com/IfcOpenShell/IfcOpenShell/assets/57261862/30a28ba9-75bc-46b8-9c56-b5212e4bc71a)

**Comment by Martin15135215** [comment]
Hi @c4rlosdias 

i did run those two files:

[buildingSMART/IDS@master/Documentation/library/sample.ids](https://github.com/buildingSMART/IDS/blob/master/Documentation/library/sample.ids?rgh-link-date=2023-08-03T13%3A10%3A58Z)
[buildingSMART/IDS@master/Documentation/library/sample.ifc](https://github.com/buildingSMART/IDS/blob/master/Documentation/library/sample.ifc?rgh-link-date=2023-08-03T13%3A10%3A58Z)

and after that i exportet as a bcf file with this button:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110968398/d03f3f6e-71c2-4ac8-8a3e-2a739382c468)


Wenn i unzip that bcf and look it in a text editor, there are no GUID referencing to the ifc file

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110968398/c142f4d5-0714-424b-a7c7-1de86651c091)

However i am unsure if that is even possible for IfcWallType. I read this https://github.com/buildingSMART/BCF-XML/tree/release_3_0/Documentation#markup-bcf-file and the Markup (.bcf) file did not have any GUID pointing to the ifc file.

Only the Visualization information (.bcfv) file has a IfcGUID pointing to the ifc entity. https://github.com/buildingSMART/BCF-XML/tree/release_3_0/Documentation#visualization-information-bcfv-file

**Comment by c4rlosdias** [comment]
the code does not export viewpoint to IfcElementType, only to IfcElement. I don't know if it makes sense to insert a selection for constructive types without a Viewpoint.

**Comment by Martin15135215** [comment]
I don't know either. I created an issue there: https://github.com/buildingSMART/BCF-XML/issues/365

**Comment by Moult** [comment]
@c4rlosdias you can include a selection for IfcElementTypes. In viewers which support selecting it (like BBIM) we can support this. For other views, they may struggle and that's fine but I think it's allowed in BCF.

**Comment by c4rlosdias** [comment]
Do you think it's worth it @Moult ?

**Comment by Moult** [comment]
Not to me personally. Maybe its worth it to @Martin15135215 ?

**Comment by Martin15135215** [comment]
Not at the moment either, because many of us use IfcElement directly instead of IfcElementType in addition.
