### ISSUE TITLE
Relocate remaining material panels under the `Geometry and Materials` tab. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3542]
This is probably in the roadmap, but tracking here. 

To locate the following under the `Geometry and Materials` and tab. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/61598eb9-7e19-4fd2-9e94-2e8a216550cd)

**Comment by Moult** [comment]
Yes, this is on the roadmap. The delay is because this is quite a bit more complex than other panels and needs a bit of proper redesign (basically we need to reimplement the slots system based on IFC representation items)

**Comment by Moult** [comment]
All done :)
