### ISSUE TITLE
IfcMaterialLayer thickness is not displayed

### ISSUE THREAD

**Issue by lfcastel** [IfcOpenShell/IfcOpenShell#3545]
IfcMaterialLayer thickness is not displayed, the total thickness is though:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/73949503/e4cdffcc-18c0-4401-8ad1-808d36a880c1)

Furthermore, wouldn't it be great to be able to recalculate the layer thicknesses to m2 or m3 which is more useful for contractor then just m thickness? I know this is not provided in the schema, but would be useful tool within blenderbim. Didn't find such a thing, but since the UI is changing so rapidly, might be my mistake..

**Comment by theoryshaw** [comment]
>IfcMaterialLayer thickness is not displayed...

Dumb question,, isn't the following the individual layer thicknesses?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9c5647f3-7d15-479d-a853-cd90ad9170ad)

**Comment by lfcastel** [comment]
Wow can't believe i overlook that, feel so dumb right now. Any suggestion for my second comment about the m2 or m3 of layers (not natively stored in IFC, but like as a blender calculation)

**Comment by Moult** [comment]
m2 and m3 calculation is provided by the Blender Qto calculation engine. Soon we will also provide it for the IfcOpenShell calculation engine :)

**Comment by lfcastel** [comment]
> m2 and m3 calculation is provided by the Blender Qto calculation engine. Soon we will also provide it for the IfcOpenShell calculation engine :)

Ok, thanks!!
