### ISSUE TITLE
Windows not showing correctly with OCCT 7.2.0

### ISSUE THREAD

**Issue by iras** [IfcOpenShell/IfcOpenShell#355]
File: https://github.com/opensourceBIM/TestFiles/blob/master/TestData/data/AC90R1-niedriha-V2-2x3.ifc

**Comment by aothms** [comment]
Again I don't see anything funky. What are your configuration specifics?

**Comment by iras** [comment]
Sorry, here's a screenshot. As you can see the window panes from both an old version of ifcopenshell (left) and a recent one with OCCT 7.2.0 (as in #354) on the right, both have some issues with transparency or belonging to another shape representation.

![screen shot 2018-03-16 at 12 24 50](https://user-images.githubusercontent.com/773028/37520490-33161ede-2915-11e8-9195-34bb0e23ed03.png)

**Comment by iras** [comment]
Relatively minor issue.
