### ISSUE TITLE
Is there an IfcOpenShell viewer that you guys have worked on?

### ISSUE THREAD

**Issue by nathalie-raffray** [IfcOpenShell/IfcOpenShell#3555]
I'm wondering if you guys recommend a workflow to check for easily visible conversion bugs within IfcOpenShell (like for example, mesh vertex positions, etc.)

If I have an .ifc file that has a visually different/unexpected result when I view it with my own software (that uses IfcOpenShell) compared to Autodesk Viewer or BIM Vision for example, is there an IfcOpenShell viewer you recommend I can compare it with? That way, I can make an issue with that .ifc file and I know the issue doesn't lie with my own code.

I know about [ifc-pipeline](https://view.ifcopenshell.org/). Would you recommend I use this?

**Comment by Moult** [comment]
https://blenderbim.org :)

It even comes with an IFC Inspector debug tool and lots of tricks (georef calculators, 2D / 3D shape creators, rendered style inspector, interactive shell.., etc). Imagine your browser's javascript console / web inspector.

**Comment by nathalie-raffray** [comment]
Thanks blenderbim works great!
My software uses your cpp API. I'm guessing the Python API that BlenderBIM uses isn't 100% equivalent. Are there any viewers that use your cpp library?

**Comment by Moult** [comment]
If you want software that uses C++ directly instead of via binding, then IfcConvert :)
