### ISSUE TITLE
CSV-import not working

### ISSUE THREAD

**Issue by FrederikJM** [IfcOpenShell/IfcOpenShell#3556]
The CSV-import function don't work.

I've made a simple structure of wall and slab elements. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/141719608/668cccbc-5a4e-4692-a15f-11d49185bfba)

Export works fine, however, when I try to import the CSV-file I get the following error:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/141719608/03e37756-474d-48cb-bbea-119748530154)

For this example, I have created a csv-file showing Name of the elements, and the width of the slabs.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/141719608/60f4ffd2-7a4c-4b2d-89a9-664534065576)

CSV: [test.csv](https://github.com/IfcOpenShell/IfcOpenShell/files/12289119/test.csv)

IFC: [SCM11.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12293090/SCM11.txt)

I'm running Blender BIM ver. 0.0.230808

**Comment by Moult** [comment]
BTW you can upload by renaming the file to .txt

I suspect we should simply cast to the appropriate data type. Would you like to have a shot at implementing this?

**Comment by FrederikJM** [comment]
Thanks, I've provided the IFC now.
Sorry, I'm no programmer and just started getting into BBIM for a small project at university.

**Comment by aothms** [comment]
I see there are a bunch of empty values in your CSV

```
GlobalId,Name,Qto_SlabBaseQuantities.Width
2PnejsrrzBCP390xTqqTOr,Slab,8000.0
2FrlqV2RHBkAHdrZals4KL,Slab,8000.0
1UAVhkf3r6rgJFjNdBFAZY,Slab,8000.0
0ya5yP$fLBmAQVLGyRM30n,Wall,                # <---
3lUGoFobv389a7VZgAiTqA,Wall,                # <---
0AoJb1bH9FRvNRFtQwjL6W,Wall,                # <---
...
```

I didn't have much of a real look, but I can imagine that might cause issues. What are your expectations for what should happen with these empty values? Contrary to property values (IfcPropertySingleValue.NominalValue), quantity values (e.g IfcQuantityLength.LengthValue) cannot be null. (Not sure why this discrepancy exists...)

**Comment by FrederikJM** [comment]
For my project, it would be preferable to export information regarding walls and slabs in one go. Thereby, some values will be _null_.

However, I tried exporting only information regarding the slabs (i.e. no _null_ values) and got the same error.
