### ISSUE TITLE
Lack of examples

### ISSUE THREAD

**Issue by smarnav2904** [IfcOpenShell/IfcOpenShell#3557]
Greetings, I'm trying to develop an app using the C++ implementation of IfcOpenShell, I got no problems developing the same app for Python due to the number of examples regarding that implementation of the library. I have already look at the C++ API reference guide but still got no idea where to start (maybe this is because I got little experience developing in C++). I know that including "fcParse/IfcFile.h" I can use that class to traverse the different elements within an IFC file, but how am I supposed to open it in first place? If you could provide some sort of examples I will be very thankful.
Thanks in advance.

**Comment by Moult** [comment]
@smarnav2904 unfortunately there is a bit of an imbalance between the amount of Python examples compared to C++ examples. Have you seen https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/examples ?

**Comment by Moult** [comment]
Hmm, ping @aothms I guess?

**Comment by aothms** [comment]
You're probably missing the IfcParse.a in your linker command line. Including the header file only gives you the function signatures (more or less) so you can compile your source files. When you're building (linking) the actual executable you need to have access to the actual binary code generated for those function signatures. These are in the (static [.a] or dynamic [.so]) library files. Using something like CMake or bazel is advisable.

**Comment by smarnav2904** [comment]
Manually linking the files during compilation worked for me. Thank you very much.
