### ISSUE TITLE
IFC file that does not work

### ISSUE THREAD

**Issue by ymhsieh** [IfcOpenShell/IfcOpenShell#356]
Dear Developers,
The attached ifc file (in zip format as required by github) produces the following error message with ifcconvert 0.4 and crashes ifcconvert 0.5 preview 2, both downloaded from http://ifcopenshell.org/ifcconvert.html

[IfcColumn-error.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1816322/IfcColumn-error.zip)

**Comment by aothms** [comment]
Thanks for the report. It appears the file works reasonable on the latest version of the code. Is it an option for you to compile yourself?

**Comment by ymhsieh** [comment]
Hi! 

Glad to know that it is working in the latest version.  I am actually trying to use BIMServer, which seems to use a specialized form/versio of IFCOpenShell, and I am not sure how to build that plugin and am not certain when they will upgrade the plugin to the latest version.... :(

**Comment by swalter88** [comment]
@aothms : current plans to release a new version? 0.5.0-preview2 is older than a year and i think there are some bugfixes that are useful for the community ....

**Comment by aothms** [comment]
@swalter88  This is being worked on. Releases are going to be frequent. There are (almost) automated builds now appearing as commit comments in github, e.g. https://github.com/IfcOpenBot/IfcOpenShell/commit/54d9edfee5785714ba27f9be3f244538a5a70b9a#comments

The BIMserver plug-in will have some mechanism to fetch newer builds as well, ie.. https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/commit/285112899042dd3c78a40acdf90cb5d0fa272a8c but it's work in progress too.

**Comment by swalter88** [comment]
@aothms These are no combined builds? I only can convert IFC2x3 with the binaries from this auto builds, is it possible for you to change it to a combined binary version? currently i need to build a workaround and use my own ifc4 binary... thx!

**Comment by aothms** [comment]
For binaries that support 2x3 and 4 from within the same executable you'll need to look at the 0.6 branch. Binaries available here: https://github.com/IfcOpenBot/IfcOpenShell/commit/175387bd88bdc39569596ca38ad77a7564135c09#commitcomment-30057707

**Comment by aothms** [comment]
> But in 0.6.0 branch the latest bugfixes are not merged

11 commits behind master. I will keep merging periodically.

> the old 0.5.0-preview is a combined binary too

That's not true. If you're lucky you might get reasonable results as the schemas do not deviate tremendously. But the 0.5 branch is only aware of a single schema.
