### ISSUE TITLE
IfcBuildSystem does not appear in the interface

### ISSUE THREAD

**Issue by Walpa** [IfcOpenShell/IfcOpenShell#3564]
Ifc 4.3 - IfcBuildSystem does not appear in the interface

![10-08-2023 11-52](https://github.com/IfcOpenShell/IfcOpenShell/assets/32360904/8e92d059-e54d-48a1-84d9-5befde1b9992)

It seems that icon indication is missing in :
[https://github.com/IfcOpenShell/IfcOpenShell/blob/530d5a4e630210c7ae0c807355de6407d8783962/src/blenderbim/blenderbim/bim/module/system/ui.py#L121](url)
[https://github.com/IfcOpenShell/IfcOpenShell/blob/530d5a4e630210c7ae0c807355de6407d8783962/src/blenderbim/blenderbim/bim/module/system/ui.py#L282](url)
[https://github.com/IfcOpenShell/IfcOpenShell/blob/530d5a4e630210c7ae0c807355de6407d8783962/src/blenderbim/blenderbim/bim/module/system/ui.py#L318](url)

**Comment by theoryshaw** [comment]
seems like 'IfcBuiltSystem' is only in IFC4x3....

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/fb592599-3c60-416b-a33e-e9beb4ff0a77
