### ISSUE TITLE
Regen space, creates new spaces

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3569]
Regen space, creates new spaces...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/7d4a7aba-83d8-4ddf-988c-baa18d0e529c

**Comment by maxfb87** [comment]
Hey :-) can you please share the file?
I noticed that when you regen you are not in "spatial mode"...can you please retry but in "spatial mode"? Thanks

**Comment by maxfb87** [comment]
Nevermind, i tried and it happens also with spatial tool activated.
I try to fix it
