### ISSUE TITLE
Borked geometry on rebar (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#358]
**Steps to reproduce:**
1. Convert [358--reinforcingBar--abort--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/358--reinforcingBar--abort--augmented.ifc) with 93cca8f7b70445eaafa3b05ba699a1a66d37fd2f (OCCT v7.2.0)
2. Experience that conversion is aborted: 
```
Error in 'IfcConvert_2x3': free(): invalid size: 0x00007f70f1971db0
(…)
FATAL: An error occured, status code 134.
```

The file opens without warnings in DDS and Solibri:
<img width="150" alt="screen shot 2018-03-21 at 15 31 24" src="https://user-images.githubusercontent.com/4601554/37715690-f319ec78-2d1c-11e8-8c21-ba44b7e677f7.png">

**Comment by aothms** [comment]
I don't immediately see what could be the issue here. Might have to send this one over to OCCT.

**Comment by johanrd** [comment]
Update: I can confirm that this seems to be a regression related to OCCT:

`OCCT 7.1.0` No segfault
`OCCT 7.2.0` Segfault
`OCCT 7.3.0` Segfault

**Comment by johanrd** [comment]
@aothms I'm not completely sure how to formulate an OCCT bug report for this case. Do you have a feeling on how it should be reported?

**Comment by johanrd** [comment]
Update: When converting with the OCCT patch from 34b3ca3, the conversion is no longer aborted, however there is no geometry output:
```
[Error] {0LcrZy5XD3MRtYFPAsxJwW} Error in: NCollection_Array1::ChangeValue
Failed to convert:
#28=IfcSweptDiskSolid(#29,8.,$,0.,455.)
[Error] No geometrical entities found
```

**Comment by johanrd** [comment]
Reopening, as the geometry is not as expected when converting from 9048ce4 (v.0.5.0) or f24944b (v0.6.0):

<img width="300" alt="screenshot 2019-01-03 at 12 52 27" src="https://user-images.githubusercontent.com/4601554/50636610-04496100-0f57-11e9-8669-fe98753f038b.png">

**Comment by johanrd** [comment]
@aothms I don't seem to have privileges to reopen this issue, so please check if you are able to do it.

**Comment by aothms** [comment]
Seems this is working again, @johanrd can you check?

**Comment by johanrd** [comment]
@aothms:
I've checked now, and it seems like this is still borked when converting from 1a5716287343163d4dc137dea762553f91833ac6 on OCCT 7.3.0p3:
<img width="300" alt="Screenshot 2019-05-29 at 14 23 13" src="https://user-images.githubusercontent.com/4601554/58556915-69ab3080-821d-11e9-888b-f5d0799718be.png">
