### ISSUE TITLE
Update Object Information in properties tab after paste

### ISSUE THREAD

**Issue by DutchSailor** [IfcOpenShell/IfcOpenShell#3580]
When you copy paste an element like a Fill Area or Wall the properties are not updated in the properties tab in BlenderBIM.

Steps:
- Select Fill Area
- Copy
- Paste

Now the properties of the original Fill Area are still displayed in stead of the new one. 
-When you click again on the new pasted Fill Area the id is updated.

Perhaps an idea to add a trigger with update properties after past? 
![BlenderBIMCopyPastUpdate](https://github.com/IfcOpenShell/IfcOpenShell/assets/30430941/3a29d90c-8265-49d7-8341-4bb2a86a281b)

**Comment by Moult** [comment]
I don't think this is a bug. This is just how Blender works. When you paste, the object isn't "active" (i.e. dark orange highlight, not light orange highlight). The object properties only shows active object information.

**Comment by Moult** [comment]
Yep, I just confirmed this behaviour with vanilla Blender. Pasting an object doesn't make it "active", so the stats always show the "prior" element.
