### ISSUE TITLE
An IfcDoorType doesn't provide a `Qto_DoorBaseQuantities` option. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3583]
An [IfcDoorType](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcDoorType.htm) doesn't provide a `Qto_DoorBaseQuantities` option. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3d509104-6a7a-47c5-9333-187d0147f3e9

**Comment by Moult** [comment]
Ah yeah this is a bit of an ambiguity which was clarified in IFC4.3 that base Qtos are meant to be applicable to types. Definitely need to backport this fix.

**Comment by Andrej730** [comment]
This seems to be some general change for ifc4x3 to add types to psets and qtos - https://pastebin.com/8JNwzDCM

**Comment by Moult** [comment]
Yeah it was always the intention prior to IFC4X3, but never explicitly defined in the spec and this was fixed upstream a while ago.

**Comment by Moult** [comment]
FYI https://github.com/buildingSMART/IFC4.3.x-development/issues/22 https://github.com/buildingSMART/IFC4.3.x-development/issues/25

**Comment by Moult** [comment]
@aothms so after rereading bug 22 in the IFC4.3.x repo, I realised this is not quite the same issue.

Bug 22 states that if a pset template is PSET_TYPEDRIVENOVERRIDE and only specifies "IfcWall", then we assume "IfcWallType" is also applicable.

However in this situation, the pset template is QTO_OCCURRENCEDRIVEN and only specifies "IfcWall". There is no logical assumption that "IfcWallType" is also applicable. Despite this, in IFC4.3 all qtos seem to be changed to QTO_TYPEDRIVENOVERRIDE.

Despite this logical discrepancy, I'm in favour of "backporting" the intention of IFC4.3 such that in IFC4, all buildingSMART Qto_* applies to both types and occurrences.
