### ISSUE TITLE
Possible for tags with multiple literals to take on `fill-bg`?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3594]
Possible for tags with multiple literals to take on `fill-bg`?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/67582cd1-3b83-4e50-8242-730db26beca6)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/7d4ac0ba-249d-45b3-be33-686f7804386a)

**Comment by theoryshaw** [comment]
reason being, is that i can chews up alot of real estate when it's applied around the full boundary. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/09ab0fbd-3c00-46ce-b422-15a1a2a6f838)

**Comment by Andrej730** [comment]
@theoryshaw changed it.
Not sure if it should be the default behaviour - it seems more intuitive to apply fill-bg to the entire symbol and have some `fill-bg-only-text` or something to apply it to the text specifically but I'll leave it that way for now until feedback.

**Comment by Plae-Blue-Dot** [comment]
Filling only the text makes more sense from this side aswell, it's generally about clarity, you only want to cover up the minimum amount of the plan in the background
