### ISSUE TITLE
IfcConvert generates DAE that crashes Collada Importers

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#36]
VS 2015 x64 RelWithDebInfo build:
`IfcConvert.exe ..\..\test\input\acad2010_objects.ifc acad2010_objects.dae`
Both ViewFBX and Unity will crash when trying to open the file. The crash seems to occur with all possible input files. OBJ works fine. OpenCOLLADAValidator tells the file to be valid.

I have been using mostly my old SourgeForge-based fork and noticed this now when testing the official repo/fork as I wanted to test the fixes in IfcMappedItem surfaces styles.

**Comment by Stinkfist0** [comment]
OK, the COLLADA generated by current codebase seems to missing <asset> element for some reason and this makes the imported (Autodesk FBX SDK?) crash.

**Comment by Stinkfist0** [comment]
The ColladaSerializer.cpp part of adding asset element seems unchanged so this must an OpenCOLLADA library bug?

**Comment by aothms** [comment]
You think this is because of a recent change? Maybe you can quickly track it down with `git bisect`? That way you can binary search through the commits starting the last working one (your PR maybe) to HEAD. Maybe temporarily build an opencollada shared library so that you don't have to re-iteratively build ifcopenshell to do the test. Sorry cannot really help now, too much swamped with other activities these days.

**Comment by Stinkfist0** [comment]
I'm able to generate proper non-crashing DAE by adding openAsset() and closeAsset() calls to `ColladaSerializer::ColladaExporter::startDocument`:
```c++
    COLLADASW::Asset asset(&stream);
    asset.openAsset();
    // ...
    asset.closeAsset();
}
```
Would this be a proper fix for this instead and the old code has been working accidentally?

**Comment by Stinkfist0** [comment]
OK, found the breaking commit https://github.com/KhronosGroup/OpenCOLLADA/commit/9f62bd6a1b185961bfb1c201ba7a6fc446cb9855

**Comment by Stinkfist0** [comment]
Would it be better for us to fix the used OpenCOLLADA revision or simply assume that latest OpenCOLLADA code is used always and fix as described above.

**Comment by aothms** [comment]
I don't know. I'm a bit lost, and frankly a bit tired of constantly having to browse through their commits (well, actually you doing most of that work). Preferably I would like IfcOpenShell to compile against non-head opencollada commits as well. Most notably e.g package manager versions, e.g [1]
[1] https://packages.debian.org/sid/opencollada-dev . It seems `COLLADASW::Asset::openAsset()` is newly introduced so your change would break that. 

I am guessing our use of their library is simply too trivial. In the end all we need is writing a simple XML file that conforms to the collada schema. Perhaps there are libraries more suitable for this. A generic XML library can in the long run also help us to implement support for IFC-XML if ever decide that'd be needed. For now I would propose to stick to an older opencollada revision. What's your thoughts?

**Comment by Stinkfist0** [comment]
Yeah, let's fix the used revision for now, and, when time permits, let's move to crafting the XML manually and by using some existing XML library.
