### ISSUE TITLE
Opening multiple IFC files via IfcOpenShell-python

### ISSUE THREAD

**Issue by danZib** [IfcOpenShell/IfcOpenShell#360]
I'm trying extract components from multiple IFC files by looping an array of filename. However when accessing said components later in memory, I'm presented with a **segmentation fault**.

Why is that and is there a way around it?

Here is a small code snippet to reproduce the error:

```
import os
import ifcopenshell

DIR_PATH = os.path.dirname(__file__)
ifc_file_names = ['a.ifc', 'b.ifc']

components = []
for ifc_file_name in ifc_file_names:
    ifc_file = ifcopenshell.open(os.path.join(DIR_PATH, ifc_file_name))
    components += ifc_file.by_type('IfcWall')

    print ('Length: {}'.format(len(components)))
    if components:
        print ('First Component: {}'.format(components[0].GlobalId))
```

Output:

> Length: 49
> First Component: 2O2Fr$t4X7Zf8NOew3FNld
> Length: 53
> Segmentation fault: 11

EDIT: 
The IFC files I used are the [ifc open house](https://github.com/aothms/IfcOpenHouse) and the [duplex apartment model](http://openifcmodel.cs.auckland.ac.nz/Model/Details/274)

**Comment by aothms** [comment]
This is a known issue (at least to me, haha)

Simplest work around is not to allow Python to garbage collect the files, for example:

~~~py
...
ifc_file_names = [os.path.join(DIR_PATH, fn) for fn in ('a.ifc', 'b.ifc')]
ifc_files = list(map(ifcopenshell.open, ifc_file_names))
for ifc_file in ifc_files:
    ...
~~~

I'll keep the issue open as a reminder for me to fix this.

**Comment by CyrilWaechter** [comment]
Tested today with 4 files other files (2nd link is dead) using ifcopenshell v0.7.0 (on cabc91dd5e325301c124cdd9342847690f0aca9c). No more issue. I assume it is an old issue which have been fixed at some point. I close the issue but reopen it if necessary with new steps to reproduce.

**Comment by aothms** [comment]
Ah yes thanks, instances should only be accessed when the file is alive.
Recently we have made sure that any instance has carries a link to the file
to prevent GC.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op wo 21 dec. 2022 11:44 schreef Cyril Waechter ***@***.***>:
