### ISSUE TITLE
New IFC facet-based selector syntax returns a sets

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#3604]
Just asking if that is intended, because now i cant do stuff like elemnts[0] because

> You cannot access items in a set by referring to an index or a key.
Source: https://www.w3schools.com/python/python_sets_access.asp

**Comment by Moult** [comment]
It's not wrong, it is a set of items. Where exactly are you doing `elements[0]` in? Is it a particular function in BBIM or your own custom script? If it's your own custom script, I'd say it's not a bug. See https://stackoverflow.com/questions/59825/how-to-retrieve-an-element-from-a-set-without-removing-it

**Comment by Martin15135215** [comment]
it's custom script, what i mean with the old query syntax, you got an list and with the new syntax you got a set.

The old code for example:
```
import ifcopenshell.util
from ifcopenshell.util.selector import Selector

ifc = ifcopenshell.open('/path/to/your/file.ifc')
selector = Selector()
walls = selector.parse(ifc, '.IfcWall') 
The_first_wall = walls[0]
```

and if i want to migrate it to the new query syntax, i can't use indexing. Just asking if that was intended.

**Comment by Moult** [comment]
Yes, it's intended. Just adjust your script to cast to a list, or use next(iter()) if you want to arbitrarily get an element.
