### ISSUE TITLE
Create 'Type' schedules

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3608]
Love [this](https://github.com/IfcOpenShell/IfcOpenShell/commit/e1c7b37d62cc3e32896d04262aaefe3801009bf0) commit!

Would be nice to have a way to create 'Type' schedules, without exporting every instance...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/69c52a8b-5e83-4f7a-89a4-41826963cf49)

**Comment by Moult** [comment]
I know what you mean, we need to add the ability to group (with summing support) and merge unique keys that are type based. Let's leave this open until we build that.

However just in case it helps, you can put IfcDoorType as a filter and it'll pull out types.

**Comment by theoryshaw** [comment]
> However just in case it helps, you can put IfcDoorType as a filter and it'll pull out types.

That could work, if there was a way to only export out types that had instances in the project.

**Comment by Moult** [comment]
You can now group and sum :)
