### ISSUE TITLE
Retain .ods formatting upon re-export. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3609]
Let's say you create an .ods schedule via CSV Import/Export panel. 

You open it in LibreCalc and adjust the column/row widths/heights to your liking. 

Could there be a relatively easy way to, when exporting out the .ods again, that it retains this column/row formatting?

**Comment by theoryshaw** [comment]
For what it's worth: 
https://chat.openai.com/share/06eddbf4-48c9-4f27-8959-0ddf27da88ef

**Comment by Moult** [comment]
Note that as with any "preserve existing formatting" option, there will always be complex scenarios which we cannot handle (e.g. merged cells, formulas). It'll do a best attempt, but the only safe option will always be a fresh spreadsheet.
