### ISSUE TITLE
IFCConvert

### ISSUE THREAD

**Issue by fotsing365** [IfcOpenShell/IfcOpenShell#361]
Hi everybody.
 Please is it possible to use the ifcConvert application to have an Xml file containing parameters such as height, length, thickness, volume and surface of IfcWall or Footing? If yes please can somebody help me?

**Comment by thorade** [comment]
According to this page:
http://ifcopenshell.org/ifcconvert.html
IfcConvert can indeed convert to XML.
Have you tried that? Does the XML file contain what you needed? If not, what would you need instead?

IFC files can be saved as STEP or XML. 
https://en.wikipedia.org/wiki/Industry_Foundation_Classes#File_formats
Would it help you to just convert the .ifc file into an .ifcxml file??

**Comment by Stinkfist0** [comment]
This kind of information should be available already. It might not be an attribute of the actual element but instead can be found from the property sets (example using the Duplex model):
```
						<IfcFooting id="0kF45Qs8L9PAM9kmb1lT5d" Name="Wall Foundation:Bearing Footing - 900 x 300:186596" ObjectType="Wall Foundation:Bearing Footing - 900 x 300" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 0 0 -1.25 1" Tag="186596" PredefinedType="STRIP_FOOTING">
							<IfcPropertySet xlink:href="#2YwwNYXCP5TODJFzS3DAbE"/>
							<IfcPropertySet xlink:href="#2mqwRjnEj7nvtdSIixY3j8"/>
							<IfcPropertySet xlink:href="#3_o6aRM_bCpBvI4GWjOcqu"/>
							<IfcPropertySet xlink:href="#1xEpRIWK50gBAzUADFsID0"/>
							<IfcPropertySet xlink:href="#1vS03_B4v16fY6jHMu9c_E"/>
							<IfcPropertySet xlink:href="#0POQNAwJXF8v2Jc_ap9HfZ"/>
							<IfcPropertySet xlink:href="#29urpggIbFRRI2YtAWQyto"/>
							<IfcPropertySet xlink:href="#3U1Z$j3619rAd0tEjjJ1qi"/>
							<IfcPropertySet xlink:href="#3YV4D49bT0DOYZvOKpvfY6"/>
							<IfcPropertySet xlink:href="#3R_3s9SPH8sPmt0qRrL_TT"/>
							<IfcPropertySet xlink:href="#1vsONLHaf3qvzJPdD$x_3U"/>
							<IfcPresentationLayerAssignment xlink:href="#S-FNDN-FTNG"/>
						</IfcFooting>
```

Here, if we follow the first property set's GUID, we can find:
```
		<IfcPropertySet id="2YwwNYXCP5TODJFzS3DAbE" Name="PSet_Revit_Dimensions">
			<IfcPropertySingleValue Name="Length" NominalValue="17.383"/>
			<IfcPropertySingleValue Name="Width" NominalValue="0.9"/>
			<IfcPropertySingleValue Name="Volume" NominalValue="4.93641"/>
			<IfcPropertySingleValue Name="Elevation at Bottom" NominalValue="-1.55"/>
		</IfcPropertySet>
```

**Comment by aothms** [comment]
> This kind of information should be available already. 

Indeed if you use commercial BIM authoring tools this information is typically exported as part of IfcPropertySets or IfcElementQuantity (sometimes depending on exporter options).

> I generated Ifc file by IfcOpenShell

If you generate the IFC file yourself than that is another story.

With IfcOpenShell and Open CASCADE you do have all the necessary tools to compute these quantities from the product representations and populate that information into the model. Either something like

~~~py
# From: http://www.pythonocc.org/quick-examples/machine-learning-and-building-models/
def calc_volume(shp):
    props = OCC.GProp.GProp_GProps()
    OCC.BRepGProp.brepgprop_VolumeProperties(s.geometry, props)
    return props.Mass()
    
def calc_area(shp):
    props = OCC.GProp.GProp_GProps()
    OCC.BRepGProp.brepgprop_SurfaceProperties(s.geometry, props)
    return props.Mass()

settings = ...
settings.set(settings.USE_PYTHON_OPENCASCADE, True)
shp = create_shape(settings, ...).geometry
...
~~~

~~~C++
IfcGeom::Kernel k;
TopoDS_Compound shp = k.create_brep_for_representation_and_product(...)->geometry().as_compound()
GProp_GProps prop;
BRepGProp::VolumeProperties(shp, prop);
double volume = prop.Mass();
~~~

And then create the IfcElementQuantity yourself.
