### ISSUE TITLE
If you exclude the GlobalId column, and then 'preserve existing' on a 2nd export, it adds some additional null values. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3610]
If you exclude the GlobalId column, and then 'preserve existing' on a 2nd export, it adds some additional null values. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/841b089b-9eec-4fe0-96aa-e073d55a0932)

![2023-08-20_07-29-39_DOOR_SCHEDULE_-_SIMPLE ods_-_LibreOffice_Calc_soffice bin](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f2c3b9a9-37a4-4993-a9be-e9e3791126e6)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/04a470a2-9f6a-4214-b791-5734f7b85231)

![2023-08-20_07-30-12_DOOR_SCHEDULE_-_SIMPLE ods_-_LibreOffice_Calc_soffice bin](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3ee4ea55-d82f-4c30-88eb-271ded01287e)

**Comment by theoryshaw** [comment]
I noticed too, it doesn't change the value...

![2023-08-20_07-39-22_DOOR_SCHEDULE_-_SIMPLE ods_-_LibreOffice_Calc_soffice bin](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/35bae2cc-4e30-4062-9b63-92b8cc0a3200)

... then i changed value...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/df8f5300-5bed-42ba-aeaf-6d78f60e6f3b)


![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/8574052b-afc5-45de-8e70-c280a5e861f4)

**Comment by Moult** [comment]
Can you test it with XLSX too?

**Comment by theoryshaw** [comment]
I don't have excel... or do you mean using librecalc, to open the xlsx?

**Comment by Moult** [comment]
Yep you can use LibreOffice Calc with XLSX.

**Comment by theoryshaw** [comment]
Thanks for the fix...
There's still this:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f4cea7e1-0659-40ed-821b-355e37592f94)
Seems like it shows up if all the values are null. Not sure.
