### ISSUE TITLE
Save ifc file.

### ISSUE THREAD

**Issue by kjell-arne** [IfcOpenShell/IfcOpenShell#3611]
I made a model here and save it, when I load the ifc file it has changed.
[Leilighet-001.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12388186/Leilighet-001.zip)
![Skjermbilde 2023-08-20 144210](https://github.com/IfcOpenShell/IfcOpenShell/assets/73910770/36de9000-b30e-48ab-b9e2-c4d5cabb8663)
What is the problem?

**Comment by Moult** [comment]
I don't see any problems here. Are you sure you are saving the IFC?

If you are using the version from BlenderBIM.org, I highly recommend you upgrade to the latest unstable release here: https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-230820
