### ISSUE TITLE
Create a new relation between an IfcSpace and an IfcDistibutionElement

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#3612]
Hi, it would be good to have an API function that assign the relation between an IfcDamper (or more in general an IfcDistributionElement) and an IfcSpace.
The use case would be to find which IfcDamper element controls the flow of a given room (IfcSpace), like explained [here](https://community.osarch.org/discussion/1615/ifcrelassignstoproduct).
In order to do that, i think it could be helpful to create a new API function, lets say "system.assign_space", that creates the relation between an IfcSpace and an IfcDistributionElement.
After i bit i found that the relation could be an IfcRelReferencedInSpatialStructure.
What do you think?

**Comment by Moult** [comment]
This already exists, through spatial.reference/dereference element :)
