### ISSUE TITLE
Extracting IfcDoor Swing foot print from IFC using IfcOpenshell-python

### ISSUE THREAD

**Issue by danZib** [IfcOpenShell/IfcOpenShell#362]
I'm quite new to IFC and IfcOpenShell so please bear with me.

For the export of a floor plan from IFC, I'm interested in retrieving the foot print of the door swings. I found the [IfcDoorTypeOperationEnum](http://www.buildingsmart-tech.org/ifc/IFC2x4/rc2/html/schema/ifcsharedbldgelements/lexical/ifcdoortypeoperationenum.htm) which seems to hold some useful information.

In my script I'm retrieving IfcDoor elements using the `.by_type` method but I wasn't able to find more Information regarding the opening operation.

The only relevant information was the `OverWidth`, which I used to create a pseudo opening, that doesn't reflect the actual position of the hinges nor type of the door

![screen shot 2018-04-05 at 10 03 11](https://user-images.githubusercontent.com/18422059/38351550-a0330bfa-38b8-11e8-87aa-7fa3a60aaebb.png)

Is there a solution to my problem?

**Comment by Stinkfist0** [comment]
This information should be found from the IfcDoorStyle (2x3) IfcDoorType (2x4) object, e.g. XML output from IfcConvert: `<IfcDoorStyle id="28VDfyq51BtxN68z6Brpvs" Name="1250mm x 2010mm" Tag="146596" OperationType="SINGLE_SWING_RIGHT" ConstructionType="NOTDEFINED" ParameterTakesPrecedence="false" Sizeable="false"/>`

**Comment by danZib** [comment]
Thank you @Stinkfist0,

I was indeed able to extract the IfcDoorStyle via the `.by_type` method.
According to [buildingsmart](http://www.buildingsmart-tech.org/ifc/IFC2x4/rc2/html/schema/ifcsharedbldgelements/lexical/ifcdoortypeoperationenum.htm) the hinges for the OpertationType: "SINGLE_SWING_LEFT" should be: 
> ...on the left side as viewed in the direction of the positive y-axis. 
 
They seem to use a local coordinate system. Is that something I can figure out in my python ifcopenshell environement?

**Comment by Stinkfist0** [comment]
IfcDoor.IsDefinedBy if I'm not mistaken.
