### ISSUE TITLE
Phantom duplication when linking IFC

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3623]
This one is hard to describe.  See video for illustration

files: https://gitlab.com/openingdesign/salon_studios/-/tree/9a2f297b3ebdb42719d3233e9df49a62f2360c79/Models%20and%20CAD/BlenderBIM
scans: https://gitlab.com/openingdesign/salon_studios/-/tree/3ee9f8334384efb21d9c2d14a3ae2459b6922f1f/Existing%20Conditions%20and%20Code%20Research/Existing%20Conditions/Scans

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/70907fcc-7b29-4cc9-b7a7-a88259fb5c3e

And when the file is saved, and opened, the phantom object disappears.

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5e02d335-41ae-4976-b102-9ec84415e6ce

**Comment by Moult** [comment]
Is your quick favourites by any chance linked to the Alt-D hotkey somehow? That's the only thing I can think of.

**Comment by theoryshaw** [comment]
https://matrix.to/#/!ssOmSJysZpXBupsgjO:matrix.org/$d9KFLUjIvt04_zEEhiP272x1rezU5ddaIHD0caVKu_I?via=libera.chat&via=matrix.org&via=crossbach.de
