### ISSUE TITLE
Wall properties doesn't update in the viewport when changing active wall

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3624]
Previously if I remember correctly the wall properties would update when a wall is activated in the UI. Now the properties stay the same, so there is now visual feedback for what is the length and height of a wall.

It was handy to know at a glance the attributes of the selected wall, and to set the same height for two walls by selecting one wall, then another, and clicking on the refresh button next to the field to set the first one to the height of the second one.

https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/d9556c73-3da9-4909-8a0b-34067bac6fdc

Now it is no longer possible. If the behaviour is intended, I think there should be a way to know at a glance the representation properties of the selected object. It may be fine in the "Parametric Geometry" subpanel ?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/bfe932de-10e6-4eab-a745-e0e2f03f219b)

**Comment by theoryshaw** [comment]
+1

would be nice if the type upated too in the type manager.  that way theres an easy way too add a type similar to the previously selected one.

**Comment by Moult** [comment]
I don't understand - it should update the psets / props. Did I miss something?

**Comment by Gorgious56** [comment]
Previously these fields would update depending on the properties of the active wall / entity which would let the user visually know the value at a glance when clicking different walls. Now the value stay the same whichever entity is selected, and AFAIK there is nowhere in the UI that these informations are shown. eg I have a wall and a slightly smaller wall, how can I know the height and the length of the walls without going into the Debug panel to show the representation params ? Granted we have the Dimensions panel and it works for regular walls but for other entities or slanted walls not so much.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/07319bad-9695-4ac3-baf2-30a5663dd970)

**Comment by Andrej730** [comment]
Seems to still work for me - demo library, two walls of different types, different height and length.

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/71ef0ba8-2c22-4ffb-bc10-ebad33a09dfb

@Gorgious56 can you please check if there are any console errors? can you reproduce it in the new project?

**Comment by Andrej730** [comment]
> would be nice if the type upated too in the type manager. that way theres an easy way too add a type similar to the previously selected one.
@theoryshaw implemented in 5a4bc0909b8a13ee08c21c9e876f3b77ba417abd

@Gorgious56 can you test it now? My guess it wasn't working in Wall Tool.

**Comment by Gorgious56** [comment]
@Andrej730 

> Seems to still work for me - demo library, two walls of different types, different height and length.

Oooh I see, my bad. I think I might at times have been in the Door or Window tool and trying to parse properties of a wall. Although for closure I've just reverted to a previous commit and there was indeed a problem in wall mode and https://github.com/IfcOpenShell/IfcOpenShell/commit/13309cb8c402fdeecce7d1066a132e1708e66d65 fixed it.

So is it by design that we can for example modify a wall's toolshelf properties while being in the window tool mode ? 

If not I think we should only show tool properties when the selected object corresponds to the used tool, apart from the general puropose tool. 

If yes I would expect the toolshelf property fields to update whatever the entity is selected, ie if I select a wall in window tool mode, the height and length should update.

Thanks for the quick fix !

@Moult 

> Oh, I didn't realise that behaviour existed. I don't recall that feature ever being implemented :) It's definitely a good idea!

Hehe but it's a great feature ! That I would love to see extended for example to show rectangle extrusion or circle extrusion properties :) So I don't need to go the debug panel to tweak it ><

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/9bed4a82-148d-46cc-87c8-bb94c65934a3)

**Comment by Moult** [comment]
> That I would love to see extended for example to show rectangle extrusion or circle extrusion properties :) So I don't need to go the debug panel to tweak it ><

Yeah to properly implement I'd like to build a new modeling system dedicated to extrusions and solids. All in a good time :)
