### ISSUE TITLE
Editing tools menu not visible when zooming in the modeling space

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3625]
Hi

I just saw that the tools displayed in the modeling space go infinitely to the right if you zoom in the interface scale, like I use to do. I think the most natural way would be them to collapse into a new row maybe? Or have a way to display them as for me right now the only way to get to see and use them is to reset to interface scale 1.0.

![Screenshot 2023-08-22 at 17 22 20](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/c573780a-e95c-42b1-890d-add3531072ae)

**Comment by BIMvoice** [comment]
I just saw for other elements even longer menu wich not even scaling back to 1 helps. Any idea how to access all the tools?

**Comment by brunopostle** [comment]
I've never been able to see all the buttons on this toolbar

**Comment by Andrej730** [comment]
For this toolbar it's possible to scroll it with the mouse wheel but it's very inconvenient and I always end up zooming out the scene.

Currently we have current tool operators scattered in 2 more placed where they are more accessible:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/0a62099f-2c17-423a-ad14-53c59e86a96f)

**Comment by BIMvoice** [comment]
Thank you Andrej!

**Comment by Moult** [comment]
I think we can consider building a "mini version" for this header. But I'd say this is a pretty low priority and one more interface to maintain.

**Comment by Gorgious56** [comment]
Note you can also middle mouse button click + drag left / right to pan the header.

**Comment by BIMvoice** [comment]
Wow now I know many ways to do it. It’s okay to be a lower priority Dion, I was not aware of the other options.
    	Sent from Outlook for iOS
    
  

 From: Gorgious56 ***@***.***>Sent: Monday, August 28, 2023 10:34 AMTo: IfcOpenShell/IfcOpenShell ***@***.***>Cc: Petru Conduraru ***@***.***>; Author ***@***.***>Subject: Re: [IfcOpenShell/IfcOpenShell] Editing tools menu not visible when zooming in the modeling space (Issue #3625) 
Note you can also middle mouse button click + drag left / right to pan the header.
