### ISSUE TITLE
TAB doesn't allow to edit 2d representation

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#3626]
Given a window type, for example, i would want to edit the 2d representation of it.
I switch first to 2d representation and after that i press TAB to modify it but it doesn't allow to do it because it's not a mesh object...

**Comment by theoryshaw** [comment]
i don't get this behavior. 
Can you do a snapshot of the window contexts, like this?...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a4971da6-b8e5-406d-8e73-1ff4ecb32c67)

**Comment by maxfb87** [comment]
here:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/b072266e-e6c4-407b-b10a-b3bdc79088e2)
Last version of bbim...
To recreate the issue: new file, create a new window type (predefined type: WINDOWS, type template: window) and save the type.
After that, select the window type, switch the representation to curve 2d plan view and try to press TAB...

**Comment by maxfb87** [comment]
Ah ok i think this is how it is intended to be....
I can't edit the 2d representation if the window is parametric but if the window comes from the demo library, for example, i can edit it...
So i close this issue :-)
