### ISSUE TITLE
Pointcloud to IFC

### ISSUE THREAD

**Issue by lorenzooliva** [IfcOpenShell/IfcOpenShell#363]
Hi guys,
I am wondering to ask for your feedback about the possibility to convert a pointcloud data (ascii, xyz, ply, ptx..) to a IFC format and to visualize the "Pointcloud.ifc" with the compatible software on the market. The reason is to validate the data trough the foudation classes and Building Smart protocols. Would it be possible? Thanks for sharing!
Lorenzo

**Comment by thorade** [comment]
pythonOCC can at least display .pcd data:
https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_display_point_cloud.py
Not sure whether that helps at all!?

**Comment by aothms** [comment]
Indeed `AIS_PointCloud` is a great idea if you're willing to quickly prototype you're own viewer for mashing up BIM and PC data! Keep in mind that the PCD loading [1] is a bit naive (e.g. assumes ASCII pcd, specific num of header rows and no additional fields per point). 

[1] https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_display_point_cloud.py#L51

**Comment by jf---** [comment]
@thorade's link is an extension ( supporting per vertex color's from .pcd file ) on the `core_display_point_cloud.py` demo
