### ISSUE TITLE
Update BCF-client on PyPI

### ISSUE THREAD

**Issue by c-mellueh** [IfcOpenShell/IfcOpenShell#3633]
Currently the bcf library on [pypi ](https://pypi.org/project/bcf-client/)is outdated. Please update to newest version

**Comment by aothms** [comment]
Indeed the workflows are quite a bit different among the various publishing scripts.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/.github/workflows/ci-bcf.yml#L11
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/.github/workflows/ci-ifctester-pypi.yml#L11-L15

I think the 2nd approach of cron + manual dispatch is much better. Would you be interested in unifying these?

**Comment by aothms** [comment]
Thanks @c-mellueh 

@Moult  currently fails with:

```
 ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         The user 'Moult' isn't allowed to upload to project 'bcf-client'. See  
         https://pypi.org/help/#project-name for more information.    
```

Any idea?

**Comment by Moult** [comment]
Yeah, I guess I'm not the owner of the bcf-client package. I guess you are? https://pypi.org/user/ifcopenshell/

**Comment by c-mellueh** [comment]
@aothms could add @Moult  as Contributor on PyPI or transfer the Project to him: 
https://discuss.python.org/t/transferring-a-pypi-name-to-someone-else/7196/2

**Comment by aothms** [comment]
Done. Sorry I had no idea I once did sth like this.

![Uploading afbeelding.png…]()

**Comment by aothms** [comment]
Still fails due to:

```
 ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         File already exists. See https://pypi.org/help/#file-name-reuse for    
         more information.        
```

@Moult how is the version number determined and applied for the other packages?

**Comment by c-mellueh** [comment]
If i understand it correctly, IfcTester uses a [Makefile](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifctester/Makefile) : 

```
VERSION:=`date '+%y%m%d'`
SED:=sed -i
ifeq ($(UNAME_S),Darwin)
SED:=sed -i '' -e
endif
...
dist:
	rm -rf dist
	$(SED) "s/999999/$(VERSION)/" pyproject.toml
	python -m build
	$(SED) "s/$(VERSION)/999999/" pyproject.toml
```
This allways creates a new version number by date. 
I don't understand the Line 2-4 in the Makefile:
```
SED:=sed -i
ifeq ($(UNAME_S),Darwin)
SED:=sed -i '' -e
```

**Comment by aothms** [comment]
Oh thanks for looking into that 👍 


>  I don't understand the Line 2-4 in the Makefile:

GNU sed is a bit different than OSX sed and takes slightly different parameters. For example -i for inline file modification takes an argument with a postfix to store the backup file, in GNU sed this is optional in OSX sed this is required. These kind of things. I think `-e` is not strictly necessary but doesn't hurt. https://ss64.com/osx/sed.html

I think we can just add this sed manipulation to the github actions workflow
