### ISSUE TITLE
Object shows as 'wireframe' in drawing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3649]
Not sure why that countertop shows as a 'wireframe' in the drawing.

files: https://gitlab.com/openingdesign/restaurant_livingston/-/tree/7fb688d959cfe4bf0a9726d333e34da66c74a930/Models%20and%20CAD/BB%20Model

![2023-08-26_13-42-42_Blender_ DDropboxGitLabrestaurant_livingstonModels_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f2ca7369-551b-4f38-91b7-dc8c234ceb59)
![2023-08-26_13-42-16_Mozilla_Firefox_firefox](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/de46df99-f766-4188-83a0-b1714fea3b70)
![2023-08-26_13-42-35_Mozilla_Firefox_firefox](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f65254bf-1ad4-42cb-b591-faaaecf7a48b)

**Comment by Moult** [comment]
self.serialiser.setProfileThreshold(1000) can you try change this to a higher number, say 10000 in drawing/operator.py?

**Comment by aothms** [comment]
Or maybe the threshold should be based on faces after the unification. Would be cool if you can duplicate that counter top a couple of times and then run with setProfileThreshold(1000) and setProfileThreshold(1000000) and let us know the difference in performance.

**Comment by Moult** [comment]
I think he means to duplicate it but leave it as the same object (i.e duplicate the mesh within the same object)
