### ISSUE TITLE
bimnot installing in blender 3.6.2 but it installed properly in blender 3.3.8 and 4.0 version

### ISSUE THREAD

**Issue by 3456123** [IfcOpenShell/IfcOpenShell#3653]
i tried to remove the previous version but without success but had no problem remove it from other version of blender
![Screenshot 2023-08-27 092231](https://github.com/IfcOpenShell/IfcOpenShell/assets/98235944/7039c4c4-5c34-415a-b246-1aad03117988)

**Comment by 3456123** [comment]
sorry but i remove blender 3.6.2 and reload 3.6.2 with all i have on 3.3.8 and now it works

**Comment by Andrej730** [comment]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/b0430be2-64b3-44a1-964b-58057401aa38)
that's very old blenderbim version though..
