### ISSUE TITLE
IfcAnnotations disappearing from drawing view when not grouped under a drawing 

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#3656]
I create an IfcAnnotation to store a drawing reference which was imported from svg. 
I close the file, and load the file afresh - works fine.
I then create a Drawing, and activate the drawing view.
--> The IfcAnnotation is hidden from view ( probably because it isn't part of any drawing)

**Comment by Andrej730** [comment]
But shouldn't annotation be part of the drawing's group to be printed in the drawing?

**Comment by Moult** [comment]
This is by design. By default, what objects are shown in your view are based on your include / exclude filters. The exception to this are annotations you have explicitly placed on that drawing.

So if you want to include non-drawing specific annotations, use `IfcAnnotation` in your include filter.
