### ISSUE TITLE
Open Recent IFC Project

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#3657]
Since we moved UI to be able to work with IFC even without saving it to .blend file at all, the next step seems to be to add "Open Recent IFC Project" option.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/96898beb-ec55-488c-8b22-3f586af6afa3)

**Comment by theoryshaw** [comment]
+1
