### ISSUE TITLE
If the value of relations is uppercase, an error occurs.

### ISSUE THREAD

**Issue by Yoshiyuki-Miyauchi** [IfcOpenShell/IfcOpenShell#3665]
I checked IDS in IfcOpenShell, and the result is different depending on whether I write IfcRelAggregates or IFCRELAGGREGATES in the PartOf facet.
If I write IfcRelAggregates in the relations, IfcTester works.
However, if I write IFCRELAGGREGATES in relations, IfcTester gives an error.
I checked the contents of the XSD and it says that I have to write IFCRELAGGREGATES for relations. (i.e. all uppercase).
Why does it give me an error if I write it in capitals?

<ids:partOf maxOccurs="unbounded" relation="IFCRELAGGREGATES">

**Comment by Moult** [comment]
This was updated one month ago. If you're IfcTester version is older than that, you'll see this problem. Can you double check to make sure you're using the latest version? (if you're using the BlenderBIM Add-on, you can download the latest daily build)

**Comment by Yoshiyuki-Miyauchi** [comment]
@Moult san
It seems it was a slightly earlier version of IfcTester.
Try downloading a newer version of IfcTester.
Thank you very much.
