### ISSUE TITLE
CMake: update to version ≥ 3.21

### ISSUE THREAD

**Issue by dirkolbrich** [IfcOpenShell/IfcOpenShell#3670]
The current CMake version is 3.1.3 which is quite old. I would propose to update the version to at least v3.21 (v3.21.4 was release October 2021, which is already quite old). This would also allow support of Visual Studio 17 2022.

I'm open to submit a PR.

**Comment by aothms** [comment]
Can we do this on the v0.8.0 branch then? Not sure if ifcopenshell / opencascade 7.5 compiles with vs2022 anyway. And we still have people on versions like 3.13 https://github.com/IfcOpenShell/svgfill/issues/2

**Comment by dirkolbrich** [comment]
closed with https://github.com/IfcOpenShell/IfcOpenShell/pull/3751
