### ISSUE TITLE
CMake: target IFCGeom and Serializer version still at 0.6.0

### ISSUE THREAD

**Issue by dirkolbrich** [IfcOpenShell/IfcOpenShell#3671]
There seems to be an old setting in the `IfcGeom` and `Serializer` target which is set to Version 0.6.0. Shouldn't that be set to 0.7.0?

https://github.com/IfcOpenShell/IfcOpenShell/blob/73d77b8382910183a4f5b329aa92f6fc0d35aa5d/cmake/CMakeLists.txt#L862

https://github.com/IfcOpenShell/IfcOpenShell/blob/73d77b8382910183a4f5b329aa92f6fc0d35aa5d/cmake/CMakeLists.txt#L898

**Comment by aothms** [comment]
Yes, and let's turn that into a variable

**Comment by dirkolbrich** [comment]
The project declaration `project(IfcOpenShell VERSION 0.7.0)` automatically sets the variables `PROJECT_VERSION` and `IfcOpenShell_VERSION`.

I will change the target property statements to use that variable.
