### ISSUE TITLE
Adding Items from project library

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3677]
With a new IFC project, after loading the project library, choose items to add with the paperclip.
You have to click on each item to add it. If you have 10 items, no problem. If you have hundreds of them, just adding them will give you repetitive stress syndrome in the mouse hand.
Maybe make it possible to select by dragging? Or like how it works in Blender with hiding view, by just one time clicking and then dragging the mouse over the icons?

**Comment by myoualid** [comment]
When selecting your library file ( look for the settings icon on top to ensure you have the properties shown as below:)
tick the "Append Entire Library".

Or you can add things by query. Just write the name of the class you want to import 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79010126/4992f0cc-1260-4e1e-b581-d7311fa74718)

**Comment by WeenDwijler** [comment]
Got it! Thanks. I close it.
