### ISSUE TITLE
How to add cost to material

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3679]
BlenderBim 0.0.230828
Blender 3.6.2
OS - Ubuntu 22.04 LTS

Where can I add cost to a material, in such a way it can be used for cost calculations?

**Comment by myoualid** [comment]
There is only element based costing. You can take off a quantity from a product's quantity set, which keeps the parametric relationship.

This is one of the reasons why I don't like walls/slabs that have multiple material layers.

**Comment by WeenDwijler** [comment]
How can I get that to work?

**Comment by Moult** [comment]
I don't think you'd need to hand calculate it, the cost value may be built out of a formula. So you'd simply type in the formula for the component parts.

In the future it would be nice to have what you're describing where you can assign rates for material layers, and they can be auto converted into cost values. But that feature doesn't exist yet. Nor in any other software that I'm aware of.
