### ISSUE TITLE
BlenderBim - Roof modifier and non-coplanar surface unwanted triangulation

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3680]
To follow up on the incredible update from this fix:

https://github.com/IfcOpenShell/IfcOpenShell/issues/3158

There is still a bit of triangulation with roof modifier when you create complex roofs:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/0757155e-6751-4955-93f7-bc8767956b31)

and the general non-coplanar surfaces, it would be ideal to only see the outline of these kinds of geometries (like ifcGeographic elements which tend to be triangulated and non-coplanar)

**Comment by Gorgious56** [comment]
Hehe we've had the same problem at the same time it seems :) https://github.com/IfcOpenShell/IfcOpenShell/issues/3668

**Comment by Moult** [comment]
Agreed, it's a duplicate :)
