### ISSUE TITLE
Suggestion adding annotation object type

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3682]
On larger projects, there often are center points used. There is a point of beginning from which everything else is measured (contractor). When needed more center points are on the drawings if it's a larger project.

Is it possible to add the annotation object type "center point"?

**Comment by Andrej730** [comment]
Can you please show some examples how it looks typically and how it should work?

**Comment by Moult** [comment]
Agreed, there's quite a bit to be done here. We need:

 1. Generic set out points (custom text, such as set out point of ceilings, floor tiles, etc)
 2. The ability to annotate eastings and northings (which may be used in set out points, but also may be used in other annotation situations like control points)
 3. Annotate spot elevations

Note that option 1 already exists, we don't come out of the box with a symbol, but you can define your own type and symbol and put a single empty or annotation point and you can use it as a set out point. To make it easier for new users we should provide a symbol (which you can reuse the one we use for plan spot levels)

**Comment by WeenDwijler** [comment]
This is what it looks like. It's generally used to mark a point on the drawings from where everything can be measured. For example: in Blender, the World Origin is such a point. On drawings that is the "Point of Beginning". When multiple center points are used, control points, they all refer to that point of beginning with X and Y coordinates (generally X xxx.xx inch/cm, Y xxx.xx inch/cm) in a CP location table on the drawing.
The center point looks like this:
![Centerpoint](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/70ed2eac-9562-44d1-be22-c7fa4b32b6d6)
While for control points the elevation marker is often used:
![Elevation Marker](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/2a7f206a-83ee-490e-bc55-18150f139c28)
I hope this helps?

**Comment by WeenDwijler** [comment]
@Dion - Yes, if it somehow would be possible to use an empty and tie a symbol to that. Everyone can use his/her own symbols and name them. I assume IFC already has that sorted out?

**Comment by WeenDwijler** [comment]
Thinking about it.....

What about adding an "S" (for Symbols) to the toolbar? Similar principle to the annotations tool. Users can choose from the list (as in the annotation tool) and add it where they want. The list can start with the most used ones, gradually adding more.
Using vector images so they can be scaled up and down?

**Comment by Moult** [comment]
Here's a first pass. Still needs a bit more polish, but here goes (note the E/N is manual, still need to build that):

![2023-09-02-163355_1071x380_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/c102acea-2675-4515-b7d3-5bb0e9d81742)

**Comment by WeenDwijler** [comment]
Sweet! One use is with a geo reference (E,N,W,S) the other measurement (X,Y) from a point of beginning. I tried to tincker something yesterday evening, but getting the X,Y coordinates into the text tool didn't work. Just know too little of this.
