### ISSUE TITLE
IFC tester possible improvements (personal wishes)

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3685]
Hey @c4rlosdias, you are doing a tremendous job, thank you very much for adding the report from the IDS check within the BBIM interface.

1. It is unbelievable that we can even export to BCF. There is an issue with that though: I think each issue should not only show the GUID of the element it refers to, but the element should also be shown for the whole purpose of BCF to be met. I don't have any idea if there are any limitations about that but that would be amazing. When clicking on each issue, to not see only the text from the report but also the object it refers to. I do not mean only in BBIM, but also in another software that BCF is imported to.

2. For me it would be very useful to have the option to show only the fail or pass tests. Most of the time I want to see only the fails.

3. The number at the beginning of the fail is confusing and unnecessary.

Of all of these, the first one is the most critical and would make the use of this tool so much easier.

Again, thank you very much for all your hard work, I appreciate you!

**Comment by Moult** [comment]
> It is unbelievable that we can even export to BCF. There is an issue with that though: I think each issue should not only show the GUID of the element it refers to, but the element should also be shown for the whole purpose of BCF to be met. I don't have any idea if there are any limitations about that but that would be amazing. When clicking on each issue, to not see only the text from the report but also the object it refers to. I do not mean only in BBIM, but also in another software that BCF is imported to.

Done. Where possible a viewpoint will be created. Where not possible there will still be GlobalIds and Tags as a fallback.

**Comment by BIMvoice** [comment]
Thank you very much!
