### ISSUE TITLE
Reuse detection takes very long time with a big model

### ISSUE THREAD

**Issue by otsoa** [IfcOpenShell/IfcOpenShell#369]
Hello,

We have a big (~900M) Ifc file which we are converting to collada. It seems that reuse detection takes very long time (i left it running for hours on debug and it was still doing 'reuse_ok' calls). If I either set use_woorld_coords flag, which by passes the reuse detection code, or revert to commit just before 6c4fee102 (Color elements by material association. Reimplement reuse detection. Fix #265) the conversion completes in couple of minutes.

**Comment by otsoa** [comment]
It seems that in our case this is also related to heavy use of mapped representations. If I add keep track of reuse_ok results in those cases, so that the somewhat heavy reuse_ok operation is not done multiple times for same 'mapping target', the prosessing times are again reasonable.

```cpp
IfcSchema::IfcRepresentation* representation_mapped_to = kernel.representation_mapped_to(representation);
if (representation_mapped_to) {
    // Check if this represenation has (or will be) processed as part its mapped representation
    representation_processed_as_mapped_item = ok_mapped_representations->contains(representation_mapped_to) || reuse_ok_(kernel.products_represented_by(representation_mapped_to));
}

if (representation_processed_as_mapped_item) {
    ok_mapped_representations->push(representation_mapped_to);
    _nextShape();
    continue;
}
```

**Comment by aothms** [comment]
That's very interesting, thanks for sharing. Naively I had not expect IFC attribute traversal times to be significant wrt geometry interpretation. It might be related to some of the inefficiencies of looking up inverse attributes. Would it be possible to share a pull request?

**Comment by otsoa** [comment]
Indeed the heaviest stacktrace leads to IfcParse::IfcFile::entityById(int). I now also changed entity_by_id_t from map to unordered_map but i need to profile a bit more. I will create a pull request after some more testing.

**Comment by aothms** [comment]
> I now also changed entity_by_id_t from map to unordered_map

That's something I had been considering as well. Alternatively just a vector if you can get a reasonable estimate whether the integer names are somewhat contiguous. Or something like a sparse vector impl https://www.boost.org/doc/libs/1_35_0/libs/numeric/ublas/doc/vector_sparse.htm ?

STEPcode uses judy arrays https://github.com/stepcode/stepcode/blob/master/src/base/judy/src/judy.h

But the real issue might be here (it's a guess), inverse attributes are registered in a map int -> int. But you also need the attribute index, which is not recorded when scanning the file. Which means the attribute value on the relating instance needs to be inspected when the inverse attribute is requested! If these attributes are long aggregates you get many instance id lookups and a linear scan over the aggregate.
https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcParse.cpp#L1899
