### ISSUE TITLE
Elevation mark is upside down. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3690]
Elevation mark is upside down. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/eef7861b-b2c9-409f-a6b6-4985ddc76d49)

file: https://gitlab.com/openingdesign/highland_haven/-/tree/72096b1f67465d81970e55f0f60e74abf3379671/Models_and_CAD/BlenderBIM

**Comment by Moult** [comment]
Annotations like these are directional (e.g. they know their start / end point) so you've got it reversed which leads to it being upside down. You can either rotate it / flip direction / delete it and reactivate the drawing to regenerate it and it should fix itself.
