### ISSUE TITLE
BIM Tools populate the Toolbar, even in workspaces where the addon is not enabled. 

### ISSUE THREAD

**Issue by mcolinp** [IfcOpenShell/IfcOpenShell#3691]
Perhaps this isn't a bug, but it seems to me that the standard blender toolbar on the right of the 3D viewport, should not be overpopulated with BIM tools in workspaces where the BIM addon is not active. There should at least be a way to disable this in the preferences if it is intentional. 
<img width="1920" alt="BIM Capture" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/39318712/1cabfc65-dafc-4bcc-8935-39581f76b3e8">

**Comment by mcolinp** [comment]
I di confirm after posting this, that the tolls do not execute in workspaces where the addon is inactive. Therefore, It seems most likely this is a bug, and that they should not appear in such a case.

**Comment by Moult** [comment]
I think they should appear by default (but power users should be able to turn it off) because the visibility of these icons psychologically offers comfort to new users who go "aha, there's the wall tool, this is clearly BIM software".
