### ISSUE TITLE
Select similar does not catch objects which are "closed eye"

### ISSUE THREAD

**Issue by hjalti-thor** [IfcOpenShell/IfcOpenShell#3694]
Select similar by class, type or container all show this behavior

https://github.com/IfcOpenShell/IfcOpenShell/assets/8538314/f60d8390-0b83-4c9d-8dbd-024f7f204524

**Comment by Moult** [comment]
I think this is ... intended?

**Comment by hjalti-thor** [comment]
Maybe it is. I guess it comes down to UI expectations. I did not expect "hide in viewport" to equate "exclude from selection set".
Will close in a few hours if we're done here
