### ISSUE TITLE
Different IfcFittings for different IfcDuctSegments

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#3695]
Scenario:
- fresh new IFC4 demo file
- create two different IfcDuctSecmentType (ie with a rectangular profile and different dimensions)
- create one parallel IfcDuctSegment for every type
- add fitting between the IfcDuctSegment with shift+F
- the fitting is ok
- now create another two IfcDuctSegment, one for every type
- try to create the fitting between these two IfcDuctSegment
The last created fitting seems to be the same as the first one instead of to follow the last created and selected IfcDuctSegment

**Comment by Andrej730** [comment]
Can you please send .ifc file to reproduce the issue?

**Comment by maxfb87** [comment]
ok
[prova_ifc_systems.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12505232/prova_ifc_systems.ifc.txt)

**Comment by Andrej730** [comment]
Fixed

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/70193e69-36c7-478b-8246-8f81704f0414

**Comment by maxfb87** [comment]
@Andrej730 sorry but i have another error...same file, try to create the fitting with the 2 ducts that haven't a fitting and i get this error
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/fe1362a0-bb71-4a21-beba-1bff98c18d8f)

**Comment by Andrej730** [comment]
@maxfb87 I'm afraid you'd have to remove the previously created transitions and create them again.
Transitions created before bf80e4b don't have information about offset between profiles stored in their BBIM_Fitting and this why it's failing.

**Comment by maxfb87** [comment]
@Andrej730 ah thanks, i had to delete ALL the fittings and after that it worked :-) thanks again
