### ISSUE TITLE
QtViewer displays empty screen

### ISSUE THREAD

**Issue by dirkolbrich** [IfcOpenShell/IfcOpenShell#3697]
I open this issue as I don’t know if this behaviour of the QtViewer is intentional as per the current dev state or if there are indeed errors. 

I build IfcOpenShell from source with the option `BUILD_QTVIEWER=ON` and ran the QtViewer example under `/build/qtviewer/`. The build process runs successful and the viewer starts without problems to an empty screen, see screenshot:

<img width="912" alt="QtViewer on start up" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/3765119/ee4371f3-b471-4091-a659-94a1453775f3">

Then running the `IfcOpenHouse` binary from `/build/examples/` which creates an `IfcOpenHouse.ifc` file. Opening this file in the QtViewer shows a list of IFC element and an otherwise empty viewport, see screenshot:

<img width="912" alt="QtViewer with file IfcOpenHouse.ifc opened" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/3765119/31fe73d5-b2d8-4b07-8b15-3238fa0c6edf">

System: macOS M1
Compiler: llvm clang 16 (homebrew version)
Qt: 6.5.1 (homebrew version)

Referencing this PR which updated Qt to version 6 https://github.com/IfcOpenShell/IfcOpenShell/pull/3574

**Comment by aothms** [comment]
Yes this is all very recent, see https://github.com/IfcOpenShell/IfcOpenShell/pull/3574 cc @dushyant-basson.

**Comment by dirkolbrich** [comment]
Ok, thanks. I thought it had basic viewing functionality and something was broken with my build. After digging deeper into the source I see that currently only stubs exist.

Will try and play with a QML alternative instead of QtWidgets. 🤓 And maybe rename it to IfcViewer? As it views IFC files, not Qt.

**Comment by dushyant-basson** [comment]
Yes, work in progress :)
