### ISSUE TITLE
MinGW support

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#37]
Continuing discussion that originated in SF https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/45f215eb/

**Comment by Fredounet** [comment]
I'm signed up and here now. I'm gone for some days and will get back later on this.
One question: how should I share my experience compiling IfcOpenShell with MSYS2 Mingw-w64? The "issue" section may not be ideal, or is t?

**Comment by Stinkfist0** [comment]
Well, the best way would be simply to start working :) Fork IfcOpenShell and create a branch for your work. The MinGW support should be accomplished by enhancing the exiting build scripts (add "MinGW Makefiles" to the list of supported generators, compile ICU from sources instead of using prebuilt libraries, etc.), and fixing the codebase where necessary. Or if wanted, you can share your knowledge (build steps and instructions) here or at pastebin etc.

**Comment by Fredounet** [comment]
OK. I have forked and will redo all my changes.
Note that I have managed to compile everything and am now just figuring out the changes in IfcOpenShell as my c++ code that uses IfcOpenShell does not compile anymore, e.g. it used IfcGeomObjects which doesn't exist anymore).

**Comment by aothms** [comment]
Should be fairly trivial to migrate. `IfcGeom::Iterator` is more or less equivalent to `IfcGeomObjects`, just no longer a static namespace, but a class one needs to instantiate. See src/ifcgeom/IfcGeomIterator.h. Advantage are obvious such as possibility to open multiple files by the same process, etc.

**Comment by aothms** [comment]
@Fredounet Are there updates on your mingw experiences? Could you by any chance share a working pull request? Would be greatly appreciated.

**Comment by Fredounet** [comment]
Unfortunately not. I've stalled soon after that conversation due to a total lack of time. Maybe I'll manage to make up some time this summer again. Sorry.
I'll definitely share a working pull, once it's done.

**Comment by aothms** [comment]
Ok cool. Thanks for the status update.

**Comment by aothms** [comment]
Fixed as part of: https://github.com/IfcOpenShell/IfcOpenShell/pull/84
Also includes script to build quickly using msys

**Comment by Stinkfist0** [comment]
I'll try some day to make make MinGW part of the Windows/MSVC build scripts so that building IFCOS using MinGW wouldn't necessarily need MSYS2.

**Comment by aothms** [comment]
I guess that would be more straight forward now that you used this `cmake --build` option... Btw. what do you think of the recent Bash for Windows developments? https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by Stinkfist0** [comment]
I'm waiting Bash for Windows eagerly to finally to be able to do "proper" Linux stuff (mostly simply for checking that cross-platform projects build fine) as I've always been simply too lazy to have an additional Linux environment or dedicated PC set up for such activities. :)

**Comment by Stinkfist0** [comment]
FYI, I'm working on a bare-bones MSYS+MinGW build script based on your script in #84 but I'm building OCE from the sources instead of downloading a prebuilt package.

**Comment by Fredounet** [comment]
FYI, this is what I had done originally. The only thing, if I recall properly, is that I had to pass/add `CMAKE_NEED_RESPONSE=YES` to cmake.

**Comment by Stinkfist0** [comment]
As a side note, it would appear that OCE cannot be built as a static library for MinGW for now without patching it - as you can probably remember, there's a large amount of linker warning spam about HashCode() function if building with Visual Studio and MinGW is not able to work around that. I'll probably provide a PR to OCE at some point, it would be nice get rid of those warnings regardless.

**Comment by aothms** [comment]
It wouldn't be a big concern to me if mingw builds are dynamically linked. It would be nice to have the warnings addressed nevertheless, but considering the limited activity in OCE lately we might have start to look elsewhere anyway to get opencascade.

**Comment by aothms** [comment]
6.9 has some improvements that are of importance to IfcOpenShell: fuzzy and multi-arg bools, hence the warning when compiling IfcGeomFunctions.cpp https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomFunctions.cpp#L137

On the other hand official occ 6.9 doesn't come with a build system that suffices our needs (e.g static linking on windows). I didn't check 7.0 yet, but that version probably makes backwards incompatible changes.

Apparently this branch [1] is rather stable and offers 6.9.1 in OCE, but it still doesn't have any status within OCE, while this effort started in Oct 2015. I find this concerning.

[1] https://github.com/tpaviot/oce/pull/589
