### ISSUE TITLE
Problem installing ifcOpenShell

### ISSUE THREAD

**Issue by DeKasClimber** [IfcOpenShell/IfcOpenShell#370]
I used the [Solibri Model Viewer](https://www.solibri.com/products/solibri-model-viewer/) in Windows. I want to have an alternative in Linux. All alternative solutions work with ifcOpenShell.

I have FreeCAD (Python 2.7.12) installed and I try to install ifcOpenShell for some time now. I've troubles installing [OpenCollada](https://github.com/KhronosGroup/OpenCOLLADA/issues/569) so I decided to not include OpenCollada, but I've an error building the application.

Somebody has an idea how to continue?

terminal dump (dutch part = newest version installe allready):
-----------------------------------------------------------------

kasper@XPS-L502X ~ $ $ sudo apt-get install liboce-foundation-dev liboce-modeling-dev liboce-ocaf-dev liboce-visualization-dev liboce-ocaf-lite-dev
$: command not found
kasper@XPS-L502X ~ $ sudo apt-get install liboce-foundation-dev liboce-modeling-dev liboce-ocaf-dev liboce-visualization-dev liboce-ocaf-lite-dev
[sudo] password for kasper: 
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd       
De statusinformatie wordt gelezen... Klaar
liboce-foundation-dev is reeds de nieuwste versie (0.17.1-1ubuntu0.1).
liboce-modeling-dev is reeds de nieuwste versie (0.17.1-1ubuntu0.1).
liboce-ocaf-dev is reeds de nieuwste versie (0.17.1-1ubuntu0.1).
liboce-ocaf-lite-dev is reeds de nieuwste versie (0.17.1-1ubuntu0.1).
liboce-visualization-dev is reeds de nieuwste versie (0.17.1-1ubuntu0.1).
0 opgewaardeerd, 0 nieuw geïnstalleerd, 0 te verwijderen en 26 niet opgewaardeerd.
kasper@XPS-L502X ~ $ sudo apt-get install python-all-dev swig
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd       
De statusinformatie wordt gelezen... Klaar
swig is reeds de nieuwste versie (3.0.8-0ubuntu3).
python-all-dev is reeds de nieuwste versie (2.7.12-1~16.04).
0 opgewaardeerd, 0 nieuw geïnstalleerd, 0 te verwijderen en 26 niet opgewaardeerd.
kasper@XPS-L502X ~ $ cmake -DOCC_INCLUDE_DIR=/usr/include/oce -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/python2.7.so ../ifcopenshell/trunk/cmak^C
kasper@XPS-L502X ~ $ mkdir ifcopenshell-build
kasper@XPS-L502X ~ $ cd ifcopenshell-build
kasper@XPS-L502X ~/ifcopenshell-build $ cmake -DOCC_INCLUDE_DIR=/usr/include/oce ../ifcopenshell/trunk/cmake 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
-- Boost include files found in /usr/include
-- Boost libraries found in /usr/lib/x86_64-linux-gnu
-- Looking for opencascade include files in: /usr/include/oce
-- Use OCC_INCLUDE_DIR to specify another directory
-- Header files found
-- Looking for opencascade library files in: /usr/lib
-- Use OCC_LIBRARY_DIR to specify another directory
-- Library files found
-- No ICU include directory specified
-- No ICU library directory specified
-- ICU libraries found
-- No OpenCOLLADA include directory specified
-- No OpenCOLLADA library directory specified
-- OpenCOLLADA header files not found, continuing without COLLADA support
-- Looking for C++ include limits
-- Looking for C++ include limits - found
-- Looking for C++ include climits
-- Looking for C++ include climits - found
-- Looking for C++ include limits.h
-- Looking for C++ include limits.h - found
-- Looking for C++ include fstream
-- Looking for C++ include fstream - found
-- Looking for C++ include fstream.h
-- Looking for C++ include fstream.h - not found
-- Looking for C++ include iomanip
-- Looking for C++ include iomanip - found
-- Looking for C++ include iomanip.h
-- Looking for C++ include iomanip.h - not found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Looking for C++ include iostream.h
-- Looking for C++ include iostream.h - not found
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.12") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kasper/ifcopenshell-build
kasper@XPS-L502X ~/ifcopenshell-build $ cmake -DOCC_INCLUDE_DIR=/usr/include/oce -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/python2.7.so ../ifcopenshell/trunk/cmake 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
-- Boost include files found in /usr/include
-- Boost libraries found in /usr/lib/x86_64-linux-gnu
-- Looking for opencascade include files in: /usr/include/oce
-- Use OCC_INCLUDE_DIR to specify another directory
-- Header files found
-- Looking for opencascade library files in: /usr/lib
-- Use OCC_LIBRARY_DIR to specify another directory
-- Library files found
-- No ICU include directory specified
-- No ICU library directory specified
-- ICU libraries found
-- No OpenCOLLADA include directory specified
-- No OpenCOLLADA library directory specified
-- OpenCOLLADA header files not found, continuing without COLLADA support
-- Found PythonLibs: /usr/lib/python2.7.so (found version "2.7.12") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kasper/ifcopenshell-build
kasper@XPS-L502X ~/ifcopenshell-build $ make
Scanning dependencies of target IfcParse
[  2%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/Ifc2x3-latebound.cpp.o
[  4%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/Ifc2x3.cpp.o
[  7%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/Ifc4-latebound.cpp.o
[  9%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/Ifc4.cpp.o
[ 11%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/IfcCharacterDecoder.cpp.o
[ 14%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/IfcGlobalId.cpp.o
[ 16%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/IfcHierarchyHelper.cpp.o
[ 19%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/IfcLateBoundEntity.cpp.o
[ 21%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/IfcParse.cpp.o
[ 23%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/IfcSIPrefix.cpp.o
[ 26%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/IfcSpfHeader.cpp.o
[ 28%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/IfcUtil.cpp.o
[ 30%] Building CXX object CMakeFiles/IfcParse.dir/home/kasper/ifcopenshell/trunk/src/ifcparse/IfcWrite.cpp.o
[ 33%] Linking CXX static library libIfcParse.a
[ 33%] Built target IfcParse
Scanning dependencies of target IfcGeom
[ 35%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcGeomCurves.cpp.o
[ 38%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcGeomFaces.cpp.o
[ 40%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcGeomFunctions.cpp.o
[ 42%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcGeomHelpers.cpp.o
[ 45%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcGeomMaterial.cpp.o
[ 47%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcGeomRenderStyles.cpp.o
[ 50%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcGeomRepresentation.cpp.o
[ 52%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcGeomShapes.cpp.o
[ 54%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcGeomWires.cpp.o
[ 57%] Building CXX object CMakeFiles/IfcGeom.dir/home/kasper/ifcopenshell/trunk/src/ifcgeom/IfcRegister.cpp.o
[ 59%] Linking CXX static library libIfcGeom.a
[ 59%] Built target IfcGeom
Scanning dependencies of target IfcGeomServer
[ 61%] Building CXX object CMakeFiles/IfcGeomServer.dir/home/kasper/ifcopenshell/trunk/src/ifcgeomserver/IfcGeomServer.cpp.o
[ 64%] Linking CXX executable IfcGeomServer
[ 64%] Built target IfcGeomServer
Scanning dependencies of target IfcConvert
[ 66%] Building CXX object CMakeFiles/IfcConvert.dir/home/kasper/ifcopenshell/trunk/src/ifcconvert/ColladaSerializer.cpp.o
[ 69%] Building CXX object CMakeFiles/IfcConvert.dir/home/kasper/ifcopenshell/trunk/src/ifcconvert/IfcConvert.cpp.o
[ 71%] Building CXX object CMakeFiles/IfcConvert.dir/home/kasper/ifcopenshell/trunk/src/ifcconvert/OpenCascadeBasedSerializer.cpp.o
[ 73%] Building CXX object CMakeFiles/IfcConvert.dir/home/kasper/ifcopenshell/trunk/src/ifcconvert/WavefrontObjSerializer.cpp.o
[ 76%] Building CXX object CMakeFiles/IfcConvert.dir/home/kasper/ifcopenshell/trunk/src/ifcconvert/XmlSerializer.cpp.o
[ 78%] Building CXX object CMakeFiles/IfcConvert.dir/home/kasper/ifcopenshell/trunk/src/ifcconvert/SvgSerializer.cpp.o
/home/kasper/ifcopenshell/trunk/src/ifcconvert/SvgSerializer.cpp: In member function ‘virtual void SvgSerializer::write(const IfcGeom::BRepElement<double>*)’:
/home/kasper/ifcopenshell/trunk/src/ifcconvert/SvgSerializer.cpp:235:3: error: no matching function for call to ‘gp_Trsf::SetValues(const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, Standard_Real, Standard_Real)’
   );
   ^
In file included from /usr/include/oce/gp_Pnt.lxx:19:0,
                 from /usr/include/oce/gp_Pnt.hxx:189,
                 from /usr/include/oce/gp_Ax1.hxx:13,
                 from /usr/include/oce/gp_Ax3.hxx:13,
                 from /usr/include/oce/gp_Pln.hxx:13,
                 from /home/kasper/ifcopenshell/trunk/src/ifcconvert/SvgSerializer.cpp:28:
/usr/include/oce/gp_Trsf.hxx:207:26: note: candidate: void gp_Trsf::SetValues(Standard_Real, Standard_Real, Standard_Real, Standard_Real, Standard_Real, Standard_Real, Standard_Real, Standard_Real, Standard_Real, Standard_Real, Standard_Real, Standard_Real)
   Standard_EXPORT   void SetValues (const Standard_Real a11, const Standard_Real a12, const Standard_Real a13, const Standard_Real a14, const Standard_Real a21, const Standard_Real a22, const Standard_Real a23, c
                          ^
/usr/include/oce/gp_Trsf.hxx:207:26: note:   candidate expects 12 arguments, 14 provided
CMakeFiles/IfcConvert.dir/build.make:182: recipe for target 'CMakeFiles/IfcConvert.dir/home/kasper/ifcopenshell/trunk/src/ifcconvert/SvgSerializer.cpp.o' failed
make[2]: *** [CMakeFiles/IfcConvert.dir/home/kasper/ifcopenshell/trunk/src/ifcconvert/SvgSerializer.cpp.o] Error 1
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/IfcConvert.dir/all' failed
make[1]: *** [CMakeFiles/IfcConvert.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DeKasClimber** [comment]
Thank you for the quick response.
I'll try to find out a way to build OCCT. But every build I make it feels like I never used a computer before. It's always a struggle for me.

**Comment by aothms** [comment]
But what version of IfcOpenShell are you using? In master `SvgSerializer::write()` does not use `gp_Trsf::SetValues()` anymore https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/SvgSerializer.cpp#L283

The only reference to `SetValues()`  I could find is indeed ifdef'ed for a OCC version change in OCCT 6.8

**Comment by DeKasClimber** [comment]
First I did clone/download of the project. As I had troubles with openOPENCOLLADA I used 
"svn co https://ifcopenshell.svn.sourceforge.net/svnroot/ifcopenshell ifcopenshell " yesterday as explained in the FreeCAD manual [here](https://www.freecadweb.org/wiki/Extra_python_modules#Linux_3).

**Comment by aothms** [comment]
That seems horribly outdated cc @yorikvanhavre

**Comment by DeKasClimber** [comment]
Ok, I'll try again tonight with the version on github.
I'll put an update later on. 

Can you advice me which lines I have to comment out / or parameters I have to change to avoid missing dependencies caused by not being able to install OpenCOLLADA? because that is the reason why I looked for an alternative installation method.

Thank you already for the responses.

**Comment by aothms** [comment]
> I read at the official IfcOpenShell website that extracting the zip file in the site-packages folder will be sufficient to import ifc files...

Yes that's a zip of the compiled binaries. I am not sure if that version is compatible with the FreeCAD importer.

> Can you advice me which lines I have to comment out / or parameters I have to change to avoid missing dependencies caused by not being able to install OpenCOLLADA

When invoking cmake you can add `-DCOLLADA_SUPPORT=Off` to the command line

**Comment by DeKasClimber** [comment]
cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ -DCOLLADA_SUPPORT=Off      -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/

did the job
It is working in FreeCAD

I read the Blender install method. Much easier and better model import result.

Thanks a lot for the effort and for the IfcOpenShell project.

**Comment by aothms** [comment]
> did the job

Good to hear, thanks.
