### ISSUE TITLE
BlenderBIM should properly distinguish between manual and automatic boolean results

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#3709]
This file  [gable.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12516815/gable.ifc.txt) contains a single wall with the top edge clipped using Bounded Half Spaces, it loads as expected in BlenderBIM and validates:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/8cd00346-a8e7-4b54-b707-bce502649ce1)

The Geometry and Materials tab sees six Booleans, and displays them correctly:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/7887d29d-220c-4e68-b98c-98de385a5aef)

However if I Shift-G to regen the wall, the clipping vanishes and the Geometry and Materials tab shows zero Booleans for the Wall:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/99c18aec-6eed-41b4-9c46-09d355cf6e89)

**Comment by Moult** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/pull/3615#issuecomment-1685426526

**Comment by Gorgious56** [comment]
Could a temporary solution be to use IfcOpeningElements ?

**Comment by brunopostle** [comment]
When two walls or beams are mitred, BlenderBIM slices the ends and links them semantically with an IfcRelConnectsElements. This Rel has an optional ConnectionGeometry which could also be generated.

You could assume that if there is an IfcConnectionGeometry coincident with a clipping plane, then this is a Boolean that is is being managed automatically by the editor.

**Comment by Moult** [comment]
@Gorgious56  Opening elements can be used as a temporary solution yes.

@brunopostle Yeah it's slightly more obscure but ideally we'll find a proper solution.

**Comment by Andrej730** [comment]
Related - 05f6f4e, now we have `BBIM_Boolean` pset that lists all ids of manual booleans that element has.

**Comment by Moult** [comment]
There's no way to know automatically what is an intentional boolean vs what is an automatic boolean. I guess we still need a feature to "mark (all?) booleans as intentional".

**Comment by Moult** [comment]
Nice! Great work, I think that's good enough for now until more work is done on the new representation items interface which is slowly emerging.
