### ISSUE TITLE
Grid only gives 3 x 3 can't be changed

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3712]
BB 0.0.230904
Blender 3.6.2
Ubuntu 22.04

Adding a grid has no longer the option to change the amount of gridlines. Copying doesn't work, ifc duplicate shows an error.

**Comment by theoryshaw** [comment]
Can you share the error message?

**Comment by WeenDwijler** [comment]
[Screencast from 06-09-23 00:41:24.webm](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/71723093-8f89-4cf8-a2b2-49145176fac6)

**Comment by theoryshaw** [comment]
I got a different error. I used the shift-d method. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/909ef046-22ab-45e8-8f9f-616eb3ab117d


```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 659, in execute
    context.view_layer.objects.active = self.new_active_obj
RuntimeError: Error: ViewLayer 'View Layer' does not contain object 'IfcGridAxis/03.001'
```

**Comment by theoryshaw** [comment]
Also know, that by default, gridlines are locked upon opening the IFC.
That is not related to this bug, i don't think, however. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/24b44a7a-5e67-4812-a871-6a4bec990e05)

**Comment by WeenDwijler** [comment]
Thanks for sharing. At least I now know how to get these messages from Python in a way I can copy them. Better for the programmers to work with, I hope.

**Comment by WeenDwijler** [comment]
Before you could change the number of gridlines in the small pop-up menu at the left bottom of the 3D view screen. It doesn't do that anymore. So, looks like you only get 3 horizontal and 3 vertical, and no way to get more?

**Comment by WeenDwijler** [comment]
Yeahhhhh! Thanks.
