### ISSUE TITLE
Deleted gridlines keep re-appearing after saving

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3713]
BB 0.0.230904
Blender 3.6.2
Ubuntu 22.04

See pictures. Deleted all gridlines and containers, saved IFC file, and even did a "save as" extra to be sure. When opening the file, all gridlines are again there.

![Screenshot from 2023-09-05 23-17-34](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/56919829-2df8-4b6a-8e2e-9a5a46f132d1)

![Screenshot from 2023-09-05 23-21-51](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/dc0874e7-9c5c-47fd-b445-d6f0cb546d72)

**Comment by theoryshaw** [comment]
Did you use 'Delete Hierarchy' in the outliner?
If so, unfortunately that doesn't work.
You can select them and then hit, 'Delete', which works i think.

**Comment by WeenDwijler** [comment]
> Did you use 'Delete Hierarchy' in the outliner? If so, unfortunately that doesn't work. You can select them and then hit, 'Delete', which works i think.

Yes, I did. I will try it your way. After deleting the lines, do you also delete the container?

**Comment by WeenDwijler** [comment]
Duh! Works like a charm. Gone they are. At re-loading, containers were also gone. I close this one.

**Comment by theoryshaw** [comment]
cool.. yes, you can delete those containers too, if you'd like.

**Comment by WeenDwijler** [comment]
> cool.. yes, you can delete those containers too, if you'd like.

They were removed automatically. :-)
