### ISSUE TITLE
BlenderBIM openings only appear after Shift-G regen

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#3717]
This wall [openings.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12528888/openings.ifc.txt) has a single manually defined opening, and four windows and doors that have their own openings.

On loading the file, only the single opening appears:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/f35fe270-6a4b-4f7e-8394-1c7c629a9e23)

If I shift-G regen the wall, all the window/door openings appear as expected:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/faaf5671-4b89-4f0e-85ec-8860c0fdead7)

**Comment by Moult** [comment]
Working in latest v0.8.0 :)

![2024-06-09-225925_710x498_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/a3a75dd0-6c79-4c1b-a188-667f4d819436)
