### ISSUE TITLE
Drawings - Some views crash others don't

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3719]
![Screenshot from 2023-09-06 11-48-47](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/de3096e3-276f-499b-bb8d-1e282e740d63)

![Screenshot from 2023-09-06 11-45-45](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/b4c3c8c4-2aa9-4609-a00b-b8582d2220c0)

![Screenshot from 2023-09-06 11-46-57](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/a80197d0-207c-4809-a338-f4f119c8b183)

**Comment by WeenDwijler** [comment]
The problem is with plan views and elevation views. All have the same crash code.

**Comment by Moult** [comment]
It sounds like you're online. Would you like to join https://meet.jit.si/openbim ?

**Comment by WeenDwijler** [comment]
Not today. The roof is leaking after the storm last night, have a serious problem with it. Need to fix it. Waiting for someone now.

**Comment by Moult** [comment]
OK. I can't recreate the problem with the IFC you sent me. Can you send me the latest version of your IFC?

**Comment by WeenDwijler** [comment]
Yep!

**Comment by WeenDwijler** [comment]
The file is rather large 7.9 Mb, much more than the other.... hope it goes through. Please confirm.

**Comment by WeenDwijler** [comment]
It seems as soon I move the camera away from 0, the crashing appears.

**Comment by Moult** [comment]
Ping @aothms :)

Thanks for the model. The culprit object is this one here, the wall by the door:

![2023-09-06-164918_572x341_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/c02aae99-7fc3-49ef-bb80-91548944ca86)

As you can see the wall has 600 non-manifold edges which I'm unsurprised has caused problems in drawing rendering. Technical drawings have to rely on either manifold solids to product sensible cuts, otherwise behaviour becomes a bit undefined. This problem is generally throughout your model (I spot checked a bunch of your panels and they all had non manifold geometry) but significantly much more in this object, which caused IfcOpenShell to fall over.

If you remodel this properly with manifold geometry the issue goes away.

I suspect we could do work to improve the forgiveness for non-manifold situations. I've isolated the element, anonymized the model, and produced a test sample for @aothms to investigate here:

[wallbug.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12534682/wallbug.ifc.txt)

**Comment by WeenDwijler** [comment]
Is this about the model I just send you?

**Comment by WeenDwijler** [comment]
I just checked, I see what you mean. No idea how that is possible, since I've cleaned everything up in Blender before using it for IFC.

**Comment by WeenDwijler** [comment]
This is from the original Blender file.

![Screenshot from 2023-09-06 14-49-06](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/de343a96-26ef-4486-8482-7bcb81c14b5f)

**Comment by Moult** [comment]
Can you share your original Blender file?

**Comment by WeenDwijler** [comment]
> Can you share your original Blender file?

You've got mail.

**Comment by WeenDwijler** [comment]
I've cleaned up all geometry as well as possible. Problem persists.

**Comment by WeenDwijler** [comment]
I did a test with 2 panels. Cleaned them up, to the minimum of non-manifolds and zero area faces. Saved the .ifc file. Reopened it and.... voila, everything was back to before. All non-manifold edges and zero area faces are back again. What's happening here?

**Comment by Moult** [comment]
There's not much else to do here until @aothms can test with the sample file provided here https://github.com/IfcOpenShell/IfcOpenShell/issues/3719#issuecomment-1707821794

If you could share just the original Blender model of the problematic base panel I could see if I can recreate the failing element.

**Comment by WeenDwijler** [comment]
Is there a problem with the NDA?

**Comment by Moult** [comment]
Yes. Sorry, it's a dense 5 page legal document that I'd prefer not to have to try and decipher. One option is for you to share just one panel. Another is that we can book a voice call where I can screen share and you can watch as I debug and delete your file after the debugging session.

**Comment by WeenDwijler** [comment]
1. In edit mode select all and merge by distance

![After Merging distance](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/6c1a816c-c0a8-4595-bdaf-2f5b50ab2595)

2. Next back to object mode, then to edit mode and find that the merged were all back.

![Before starting clean up](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/ccdf4ec7-43a3-4b79-8259-24c233901df2)

3. After cleaning and before saving .ifc file

![After cleaning before saving](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/2b067f82-fb81-4ddc-8012-0dcc5599095e)

4. Saved the .ifc file, closed Blender, and re-open the .ifc file. And, it's back again.

![After re-opening](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/7b350e62-b466-4d07-881a-7b0dd55b754c)

It looks like the changes are not saved or not registered in any way.

**Comment by WeenDwijler** [comment]
Although this is about drawings crashing, the issue of saving changes, which did not get saved apparently, is another one. I've got a hunch why the original problem happens (crashing drawings) and investigating it now. I think the team has at least already some idea of this. But I hope to drill down as much as possible in my layman's work.

**Comment by WeenDwijler** [comment]
@Moult I can see your concerns about the hinges (lado), the same goes for the door lock. This kind of geometry is not a mesh, but a mess. The door itself is pretty clean.

**Comment by WeenDwijler** [comment]
OK. After cleaning up the geometry, made a new .ifc, tried the plan and elevation views and everything seemed to go smoothly. No problems or errors like before. What was forgiven in Blender for rendering, wasn't in BlenderBim. Maybe it is a good idea to mention in the future that a clean geometry is essential to get proper results. Or as suggested, being more forgiving with non-manifolds. I didn't look at the saving or not problem again. I feel slightly ashamed that my geometric chaos caused this stir. A good learning exercise to do better.
