### ISSUE TITLE
"ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found" when deploying to GAE using docker and flask

### ISSUE THREAD

**Issue by jadeid91** [IfcOpenShell/IfcOpenShell#3722]
```
backend_1  | Usage: flask run [OPTIONS]
backend_1  | Try 'flask run --help' for help.
backend_1  |
backend_1  | Error: While importing 'app.main', an ImportError was raised:
backend_1  |
backend_1  | Traceback (most recent call last):
backend_1  |   File "/opt/python3.7/lib/python3.7/site-packages/ifcopenshell/__init__.py", line 61, in <module>
backend_1  |     from . import ifcopenshell_wrapper
backend_1  |   File "/opt/python3.7/lib/python3.7/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>  
backend_1  |     from . import _ifcopenshell_wrapper
backend_1  | ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /opt/python3.7/lib/python3.7/site-packages/ifcopenshell/_ifcopenshell_wrapper.so)
backend_1  |
backend_1  | During handling of the above exception, another exception occurred:
backend_1  |
backend_1  | Traceback (most recent call last):
backend_1  |   File "/opt/python3.7/lib/python3.7/site-packages/flask/cli.py", line 234, in locate_app
backend_1  |     __import__(module_name)
backend_1  |   File "/home/vmagent/app/main.py", line 202, in <module>
backend_1  |     import integrations.ifc.checker.webhooks as ifc_checker_webhooks
backend_1  |   File "/app/integrations/ifc/checker/webhooks.py", line 3, in <module>
backend_1  |     import integrations.ifc.checker.functions as ifc_checker_functions
backend_1  |   File "/app/integrations/ifc/checker/functions.py", line 5, in <module>
backend_1  |     import ifcopenshell
backend_1  |   File "/opt/python3.7/lib/python3.7/site-packages/ifcopenshell/__init__.py", line 69, in <module>
backend_1  |     raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
backend_1  | ImportError: IfcOpenShell not built for 'linux/64bit/python3.7'
```

Any help is appreciated

**Comment by EstebanDugueperoux2** [comment]
Hi @jadeid91 ,

I think the issue comes from that pypi provides python wheels for linux using old manylinux tag which doesn't ensures compatibility for GLIBC version, see https://peps.python.org/pep-0600/#legacy-manylinux-tags.
Then to workaround that I suggest to use  a more recent docker image.

Regards.

**Comment by EstebanDugueperoux2** [comment]
Indeed in https://pypi.org/project/ifcopenshell/#files we see manylinux1 tag use while in similar python module as numpy having C/C++ extension module, i.e. https://pypi.org/project/numpy/#files, we see manylinux_2_17 tag.
2_17 corresponding to an old GLIBC corresponding to RedHat7 for example, see https://sourceware.org/glibc/wiki/Release.

**Comment by aothms** [comment]
In addition to this: do you have the option to select a newer base image with a later glibc version? Alternatively you can use the 0.6 branch (latest build here https://github.com/IfcOpenBot/IfcOpenShell/commit/721fe4729aa5302efe1602971aae2558934ad098#comments) which built on an older linux version so has a earlier glibc version (don't remember the exact version).

**Comment by jadeid91** [comment]
re: @EstebanDugueperoux2, thank you for your answers. I will check if we can move to a later docker image with our dev team.
re: @aothms thank you for the suggestion, I will try to fetch the version number and add it to our requirements.txt file and test if it works.
