### ISSUE TITLE
Select all elements button at the right hand side

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3726]
I love this feature, and I would love to have a select elements button on the right-hand side. Like for example if I select IfcSlab and click on that button to select all in the model space all the slabs. This feature is already present in many other places, so maybe it does not take too much time to implement. Maybe having the same outcome if double-clicking in one category of elements could also be useful.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/be2e770c-6b20-4b6f-9816-a62a6e069fcd)

THank you!

**Comment by theoryshaw** [comment]
cool... seems to be addressed w/
https://github.com/IfcOpenShell/IfcOpenShell/commit/d092fd45ba1d081acbbe08b3faf2e8b8693c6861

**Comment by BIMvoice** [comment]
Amazing, thank you very much!
