### ISSUE TITLE
Be able to `bim.activate_drawing` a drawing listed in the sheets UI, as well.  

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3728]
Would be nice to be able to `bim.activate_drawing` a drawing listed in the sheets UI, as well.  

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/2dbc7a48-fa90-462d-a9c7-42f97cfc68e9)

**Comment by milinddethe15** [comment]
the logic for checking drawing needs to be repeated in sheet UI?? can we import it from drawing?

**Comment by Moult** [comment]
The logic does not need to be repeated, you can reuse the operator.

**Comment by milinddethe15** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/28099ddc8fedde30182b10d13f847539dc4737a6/src/blenderbim/blenderbim/bim/module/drawing/ui.py#L280-L283
The logic i mean is for checking active drawings
