### ISSUE TITLE
Error Enabling BlenderBIM on Fresh Install

### ISSUE THREAD

**Issue by jallard-reframe** [IfcOpenShell/IfcOpenShell#3730]
I was unable to Enable BlenderBIM on a clean install of Blender and Blenderbim. I had never installed either package on this Mac. I followed the instructions on https://blenderbim.org/docs/users/installation.html. The error message when I clicked the Enable checkbox is captured in the attached screenshot.

Computer: MacBook Pro running Ventura 13.5.1
Blender: blender-3.6.2-macos-arm64.dmg
BlenderBIM: blenderbim-230902-py310-macos.zip

Looking forward to trying it when I get past these issues. Cheers, Jim

<img width="1559" alt="Screenshot 2023-09-07 at 11 54 49 AM" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/139792246/f61b6be2-c22c-40c6-8f64-86f6d770278b">

**Comment by theoryshaw** [comment]
Hi. 
See [FAQ 1.](https://blenderbim.org/docs/users/installation.html#faq) 

and 
https://blenderbim.org/docs/devs/installation.html#unstable-installation

**Comment by Moult** [comment]
I think Macbook Pros use an M1/M2? chip.

You'll need to download the version called M1 on this page: https://blenderbim.org/download.html

I know very little about Mac, but I can see how "Download for M1" is a confusing title. What might be a better label for that download button to prevent issues like this in the future?

**Comment by Moult** [comment]
Buttons renamed to Mac Silicon and Mac Intel, and silicon is now the first button as it's more common for new devices.
