### ISSUE TITLE
Potential bug inside the shader nodes for Temporary Section Cutaways

### ISSUE THREAD

**Issue by Ta-b** [IfcOpenShell/IfcOpenShell#3736]
When using Temporary Section Cutaways with IfcBuildingElementProxies in the model - the section cut leaves behind a fuzzy black shape:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/130040537/46a17e33-7a2c-44c5-9fba-19fcfec78b5e)

I am no expert with geometry and shader nodes, but by fiddling around, I spotted that this node seems unnecessary:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/130040537/56b483bb-91d5-4e44-9203-678a03b7f47e)

By removing it, it seems to fix the fuzziness:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/130040537/49b9adaa-cbbb-499f-bda9-c5c064da73ce)

**Comment by Andrej730** [comment]
Is this automatically generated BBIM shader? Can you please share the .ifc to reproduce the issue?

**Comment by Ta-b** [comment]
This was on my work PC. I've just tried to emulate on my personal and failed. The Mix Shader I highlighted is necessary and is designed to have the Line Decorator plugged into it. I can only think that this has been fixed already or potentially I managed to break it myself...
I'll try again on Monday to see if I can recreate on the most recent release on my work PC but until then I'll close the issue. Thanks.

**Comment by schroef** [comment]
I actually also noticed this on some parten like particles systems and some other objects.

Also noticed some options don't work, like use selected only. I haven't used this addon in a while and was glad to see they already added collections as well. Was about to add it myself.
I'll check tomorrow again if you tip is indeed the solution for me as well
