### ISSUE TITLE
IFCCSV Cannot export properties with whitespace in their name 

### ISSUE THREAD

**Issue by marszulc** [IfcOpenShell/IfcOpenShell#3740]
Hello,
I am struggling with exporting an IFC to CSV/XLSX with a property whose name contains a whitespace.
I can export all properties from the pset as dictionary, but I want to have them organised in separate columns.

The error I got (trying to use quotation marks):
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110668180/8068a4bd-121f-4345-8326-9af1cbb68544)

**Comment by Moult** [comment]
Try double quotes.

**Comment by marszulc** [comment]
Works, thanks!
