### ISSUE TITLE
Separation lines to create non closed IfcSpaces

### ISSUE THREAD

**Issue by maxtillberg** [IfcOpenShell/IfcOpenShell#3749]
Often my models are not fully closed by walls, especially internal walls are often missing so it would be useful to have some temporarily object like Revit room separation lines to help BlenderBIM determine IfcSPaces.

**Comment by Moult** [comment]
These are known as IfcVirtualElements in IFC. Just create a plane (not a line) and it should work.

**Comment by Owuraqu** [comment]
> These are known as IfcVirtualElements in IFC. Just create a plane (not a line) and it should work.

I have been trying to do this for sometime but not successful. Maybe a short demonstration screencast or video would be very much helpful. Thanking you in advance:).
