### ISSUE TITLE
[ifcopenshell-python] Bump version mapping from IFC4X3_ADD1 to IFC4X3_ADD2 for IFC4X3

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#3759]
https://github.com/IfcOpenShell/IfcOpenShell/blob/f0e03c79df4fe2ee4d4a778bc0402258871426b9/src/ifcopenshell-python/ifcopenshell/file.py#L243

see https://github.com/buildingSMART/IFC4.3.x-development/commit/524daac53ca682e0649d240ace87f4cd7baff6e7

**Comment by Moult** [comment]
If @aothms can confirm this change (e.g. I believe geometry is only supported for certain schemas) then PR very welcome :)

**Comment by aothms** [comment]
We haven't even generated code yet for the add2 schema. I'd like to wait with that until it passes the iso review.

**Comment by Martin15135215** [comment]
In the last stable release for BlenderBIM 231104:

> There is also now support for IFC4X3 ADD2, which is one more step towards the final ISO version of IFC4X3.


The last release of IfcOpenShell in PyPI is 231118. So I thought when I do this:

```
version: str = "IFC4X3"
ifcopenshell.file(schema=version)
```

I would get IFC4X3 ADD2, however, I got IFC4X3 ADD1.

How can I manually force IfcOpenShell to use IFC4X3 ADD2?
