### ISSUE TITLE
How do you permanently delete IfcGrid?

### ISSUE THREAD

**Issue by Owuraqu** [IfcOpenShell/IfcOpenShell#3762]
I have not been able to permanently delete IfcGrid once created. 

I have experienced it before and thought the problem had to do with the file I was working with sometime ago. But I am currently working on a new file now experiencing the same issue again.

I am able to delete but after closing and reopening the file the IfcGrid appear again. I have tried several times but the same issue.

**Comment by theoryshaw** [comment]
this problem? 
https://community.osarch.org/discussion/comment/17085/#Comment_17085

**Comment by Owuraqu** [comment]
@theoryshaw Thank you very much ☺️. The selection process was key.
