### ISSUE TITLE
 No module named 'ifctester' 

### ISSUE THREAD

**Issue by SamiIRT** [IfcOpenShell/IfcOpenShell#3765]
Hi everyone,

I am attempting to run the "How to use it" example from this link: https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/ifctester. However, when I try to execute it, I receive the following error: "No module named 'ifctester'."

I have installed the 'ifcopenshell' package using pip.

Has anyone figured out a way to resolve this issue?

Thanks in advance for any help.

**Comment by Martin15135215** [comment]
Try `pip install ifctester`

and if there is a problem with bcf module missing:

`pip install bcf-client`
