### ISSUE TITLE
Regression: Conversion takes over 16h on slab (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#377]
**Steps to reproduce:**
1. Convert [377--slab--segfault--accept-errors.ifc](https://github.com/IfcOpenShell/files/blob/master/377--slab--segfault--accept-errors.ifc) with c748c8d (OCCT v7.2.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```

When converting with e87a1a0 (OCCT v7.2.0) there are warnings about `Failed to convert:` `Invalid face`. However, e87a1a0 does not segfault so this is seemingly a recent regression.
<img width="300" alt="screen shot 2018-04-24 at 10 07 14" src="https://user-images.githubusercontent.com/4601554/39174212-598a7302-47a7-11e8-8193-59f8202bb9b4.png">

**Comment by johanrd** [comment]
Here is another file that segfaults with latest commit (6ee283dbae2f8597880882635d94d84eb8461cc3), but does not segfault with e87a1a0b32cacbbecb7b3cc428bdb2d3f362e148, thus a recent regression:
[socket--segfault.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1974679/socket--segfault.ifc.zip)

**Comment by johanrd** [comment]
Closing – not reproducible anymore when building from commit 08557c2 :tada:

**Comment by johanrd** [comment]
Reopening, as this now takes over 16 hours on f24944b (v.0.6.0)

**Comment by johanrd** [comment]
@aothms Do you have any idea about what causes this conversion to now run "infinitely" (>16h) on the 0.6.0 branch? (compared to ca 6 seconds on 0.5.0)

**Comment by aothms** [comment]
@johanrd There was some pending work on removing unnecessary processing bits. That has been completed in 68151b970a6cb34b200f64e67c470ae87b28f4de and now 0.6 is also back to a couple of seconds. This is a bit of an odd file, not entirely sure why it performed so asymptomatically.

**Comment by johanrd** [comment]
Thanks! I can verify that this is now fixed with 68151b9 🎉

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
