### ISSUE TITLE
When using Duplicate Aggregate it does not duplicate the wall connections. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3770]
When using [Duplicate Aggregate](https://github.com/IfcOpenShell/IfcOpenShell/pull/3328) it does not duplicate the wall connections. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c92ba887-bca2-4c6f-9e2c-002c6b812f79

**Comment by brunoperdigao** [comment]
It seems that `blenderbim.core.root.copy_class()` copies the `IfcRelConnectsElements` but not the `IfcRelConnectsPathElements`. @Andrej730 could you point me to where I can find the source of this problem in the code?

**Comment by brunoperdigao** [comment]
I just found that this is the intended behavior. As stated in IfcOpenShell documentation (https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/root/copy_class/index.html?highlight=copy_class):
> Path connectivity is not copied, as there is no guarantee that the connections are still valid.

The IfcOpenShell api is beyond my knowledge right now 😕

**Comment by Andrej730** [comment]
@brunoperdigao you're right, it does not but copying wall connections sounds very similar to how we copy some other relationships during duplication by storing them

https://github.com/IfcOpenShell/IfcOpenShell/blob/6c9e130ca831838b4e22361a606940a41c55031f/src/blenderbim/blenderbim/bim/module/geometry/operator.py#L755

and then recreating them

https://github.com/IfcOpenShell/IfcOpenShell/blob/6c9e130ca831838b4e22361a606940a41c55031f/src/blenderbim/blenderbim/bim/module/geometry/operator.py#L810

So, perhaps we can extend `tool.Root.get_decomposition_relationships` and `tool.Root.recreate_decompositions` to store connections too? Currently it works only for fills.

**Comment by brunoperdigao** [comment]
@Andrej730 Thanks, I'll take a look at this.

**Comment by brunoperdigao** [comment]
@theoryshaw This should be fixed after merging #3969.

**Comment by theoryshaw** [comment]
Yes, this looks good to go!
