### ISSUE TITLE
Deleted sheet templates keep showing up in drawings and documents making a new sheet

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3771]
BBIM 0.0.230919
Blender 3.6.2
Ubuntu 22.04 LTS
Inkscape 1.2

Directory with title blocks has only 3 templates in it, yet, the ones I deleted keep showing up in drawings and documents when making a new sheet.

**Comment by Andrej730** [comment]
Can you please send some example to reproduce the issue?

**Comment by WeenDwijler** [comment]
> Can you please send some example to reproduce the issue?

1. Screenshot 1 from the 3 .svg files testfield.
![Screenshot from 2023-09-19 19-03-43](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/530383cf-cb3d-4a60-930f-3bc2667c5969)
2. Screencast of how they are visible among a long list of other .svg files  in BBim.
[Screencast from 19-09-23 19:06:09.webm](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/153658c4-03b9-4725-832b-2c5c5e4354d9)
3. screenshot of how the 3 .svg files were no longer present (I deleted them).
![Screenshot from 2023-09-19 19-07-55](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/0d902562-e554-467b-9fe8-94ab8ffdf357)
4. screencast of how they are still visible in the list of templates
[Screencast from 19-09-23 19:09:21.webm](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/7b27b0b3-e7a6-4d75-94ba-d24ac1186504)

Except for the A1.svg, A2.svg, and A3.svg (which come with BBim standard) all other .svg were tests to design my own sheets. Some I took from the original templates of BBim, modified them (graphically), saved them and placed them in the title block directory so they can be used by BBim.
They all work fine with BBim, but when I deleted them, they stayed in the list and even worked, despite being deleted. Looks like a copy of them is somehow stored in BBim?

**Comment by WeenDwijler** [comment]
An other issue related to this: if I have a couple of custom title blocks in that directory, and I install a new version of BBim, all are deleted and replaced for the standard 3 of BBim. Happy I did not put final versions in there, or the work would have been lost. I now keep the originals somewhere else and after installing a new version of BBim, copy them back in that directory. But this adds a lot extra work to installing and requires the user to be very aware of this, if they don't want to loose that awesome title block they created.

**Comment by Moult** [comment]
When a titleblock is used on a project, it will be copied to your relative directory (which you can configure in the add-on settings) but defaults to `layouts/titleblocks/`. This is relative to your IFC project. This is a feature, not a bug.

**Comment by WeenDwijler** [comment]
I see now, I didn't know that. Awesome. So, do I understand correctly, if I want to use custom-made templates, I just put them in the project directory, and they will appear on the list in BBim to choose from?

**Comment by Moult** [comment]
Yep :) And if you have multiple projects in multiple locations you can have assets tailored to each project. This also allows you to "package" up a project including all of its assets.
