### ISSUE TITLE
BlenderBim 230920 - IFC file association not working on Windows

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3778]
It's very exciting! Although I am not sure when this update came to windows previously it was greyed out and said 'only available for linux'

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/e3d14644-bdc5-4df0-8175-a275ec91b277)

Now when attempting to associate Ifc with BlenderBim it gives this instruction:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/e9372638-cb25-4bfc-a350-7871553889d8)

After pressing 'OK' it says:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/e2b82dde-bc6c-40e3-9ce8-30bb1476ce74)

But the command console does not pop up, and the files are not associated

attempting to paste it in CMD myself gives this error:

C:\Users\user-pc>"ASSOC .IFC=BLENDERBIM"
'"ASSOC .IFC=BLENDERBIM"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by brunopostle** [comment]
You need it without the quote marks, just:

    ASSOC .IFC=BLENDERBIM

**Comment by Plae-Blue-Dot** [comment]
Thanks @brunopostle 
I'm not sure if this is user error but I recieve this error when typing it in:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/fdd4e12f-2f51-40b9-bd8e-4f17a7ba272e)

My user is the admin for the pc

**Comment by Plae-Blue-Dot** [comment]
Running it as admin results in this:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/f731de1b-24e8-4f1a-8684-8d62d19df2eb)

But the file association is still not going through

**Comment by brunopostle** [comment]
Afraid I can't help, I don't have Windows admin permissions, so Access Denied is expected here

**Comment by Plae-Blue-Dot** [comment]
No stress, Thanks for the assistance so far Bruno!

**Comment by Andrej730** [comment]
> But the command console does not pop up, and the files are not associated

Can you please check system console for errors?

**Comment by Plae-Blue-Dot** [comment]
Hi @Andrej730 

I'm not certain how to see the command console's history?
It always just launches empty:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/8dfa57c9-51ab-405a-b46f-162603281008)


In Blender this is what's shown:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/45ab4641-f743-4452-ad5b-687ba82b1a25)

**Comment by aothms** [comment]
I had to look this up as well, but `assoc` only associates an extension to a filetype, not to an executable. You need to use `ftype` [0] to associate the filetype to the executable.

[0] https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ftype

**Comment by Plae-Blue-Dot** [comment]
Hey @aothms thanks for the info!

So would that command look like this?

FTYPE .IFC=BLENDERBIM

?

**Comment by aothms** [comment]
I've never tried. But I think this:

```
assoc .ifc=ifcmodel
assoc .ifczip=ifcmodel
assoc .ifcxml=ifcmodel

ftype ifcmodel="C:\Program Files\Blender Foundation\Blender\blender.exe" "%1"
```

But the others need to pitch in on what the actual command invocation for blenderbim to open an IFC model is. Because I doubt you can just pass an IFC model directly as argv[1] to blender?

**Comment by Plae-Blue-Dot** [comment]
Thanks @aothms much appreciated, I'll give this a go!
I always vote for automation, but I think this is a very nice to have !

**Comment by Andrej730** [comment]
> I'm not certain how to see the command console's history?
> It always just launches empty:

I mean Blender system console, you can open it in Window > Toggle System Console

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/d8f16e66-0fec-4987-85e7-940f39995ebb)

>but assoc only associates an extension to a filetype, not to an executable. You need to use ftype [0] to associate the filetype to the executable.

After user running "Associate BlenderBIM with ifc files" it should open system console, that defines the ftype and then user can type `ASSOC .IFC=BLENDERBIM` in that console. Not sure why system console is not showing in some cases though 🤔

I'd like to automate it completely but when I was trying on my system for some reason `ASSOC .IFC=BLENDERBIM` only worked when it was explicitly typed in system console by user, this is why it's now kind of semi-automatic.

FTYPE command we're using:
```
"FTYPE BLENDERBIM=""$BlenderPath"" --python-expr ""import bpy; bpy.ops.bim.load_project(filepath=r'%1')""",
```
https://github.com/IfcOpenShell/IfcOpenShell/blob/9e4702c102c37c74db7fb89a21cb9f80f5fcc250/src/blenderbim/blenderbim/libs/desktop/windows_bbim_association.ps1#L9C5-L9C5

**Comment by Andrej730** [comment]
@Plae-Blue-Dot did it worked?

**Comment by Plae-Blue-Dot** [comment]
It did not work sadly, but I did get an error in the blender system console:

File C:\Users\user\AppData\Roaming\Blender
Foundation\Blender\3.6\scripts\addons\blenderbim\libs\desktop\windows_bbim_association.ps1 cannot be loaded because
running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
Info: Associations established.

**Comment by Andrej730** [comment]
@Plae-Blue-Dot I've blocked powershell on my computer to get the same message and found a workaround to make it work. Can you please try again after 78aba1c?

**Comment by Plae-Blue-Dot** [comment]
Hi @Andrej730 

I've tried it this morning after the fix, I am pleased to say it opens the cmd window

but after typing in:
ASSOC .IFC=BLENDERBIM

it just does this:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/4e327454-5dea-4f53-8aae-74754d190db9)

And nothing else, my ifc's stil aren't associated

**Comment by Andrej730** [comment]
@Plae-Blue-Dot was it opening some registry change before it opened cmd?

**Comment by Plae-Blue-Dot** [comment]
Hi Andre,

No nothing prior I think? 
Thats how it is when you click the associate with ifc button
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/43c4eeb8-7cd1-4e62-9f6f-59c635b4edd1)

You click ok:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/9e32f196-2476-4f92-8511-11a113519c39)

Then it opens the cmd window:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/c29ddc9a-49b4-44d5-871f-4b58f30ed1b2)


Here is what Blender's console says:
'C:\Users\user-pc\AppData\Roaming\Blender' is not recognized as an internal or external command,
operable program or batch file.
Info: Associations established.

**Comment by Andrej730** [comment]
@Plae-Blue-Dot can you please try with the latest build? I've forgot to commit the .reg file and this is why it was throwing `is not recognized as an internal or external command`. Tested it also on friend's PC (Windows 10), should work.

**Comment by Plae-Blue-Dot** [comment]
It worked!

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/b6fdd77c-0e8a-451f-8fd0-5539fb83c2b9)

This is sooo cool! I tested and all runs as expected!

Thankyou so much for the effort @Andrej730 I know it's been a slog!
You are amazing!
