### ISSUE TITLE
build-deps fails on Win10 with Visual Studio 2017 x64

### ISSUE THREAD

**Issue by MirkoWeber** [IfcOpenShell/IfcOpenShell#378]
This is the error I got:
///////////////////////////////////////////////
Build started at 10:15:09,12.

Boost 1.65.1 already downloaded. Skipping.
Boost 1.65.1 already extracted into C:\newLibraries\IfcOpenShell\deps\boost. Skipping.
Building Boost 1.65.1 --with-system --with-regex --with-thread --with-program_options --with-date_time --with-iostreams --with-filesystem Please be patient this will take a while.
Der Befehl ".\b2" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
(.\b2 could not be found)

An error occurred

Build ended at 10:15:10,53. Time elapsed 0:00:01.41.
///////////////////////////////////////////////
I also got an access denied error when "bootstrap msvc" was executed by the build-deps script on a previous run of the script, even though i have run this script using visual studio x64 developer cmd with admin rights.
I have retried running this script 3 times now and this error always persists.
I also made sure to erase the boost folder under deps before rerunning this script.

I really need to build the libraries for Windows and vs2017, can anyone help me on this?

**Comment by aothms** [comment]
Those errors are likely related, `bootstrap msvc` [1] IIRC is what generates the `b2` engine. What is the exact message of this "access denied error". You can also try to replicate the steps [1] manually. It's just the basically the common instructions to build boost [2].

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L170
[2] https://www.boost.org/doc/libs/1_65_1/more/getting_started/windows.html

**Comment by MirkoWeber** [comment]
How can I get more information on this access denied error? 
I only got those warnings before I got this access denied error 
/////////////////
cl : Befehlszeile warning D9035 : Die Option "GZ" ist veraltet und wird in einer der nächsten Versionen entfernt.
(option GZ is deprecated and will be removed in the next versions)
cl : Befehlszeile warning D9036 : "RTC1" anstelle von "GZ" verwenden
(warning use rtc1 instead of gz )
cl : Befehlszeile warning D9002 : Unbekannte Option "/MLd" wird ignoriert.
(warning unknown option "/MLd" will be ignored)
Zugriff verweigert
(access denied)

Bootstrapping is done. To build, run:

    .\b2

To adjust configuration, edit 'project-config.jam'.
Further information:

    - Command line help:
    .\b2 --help

    - Getting started guide:
    http://boost.org/more/getting_started/windows.html

    - Boost.Build documentation:
    http://www.boost.org/build/doc/html/index.html
Building Boost 1.65.1 --with-system --with-regex --with-thread --with-program_options --with-date_time --with-iostreams --with-filesystem Please be patient this will take a while.
/////////////////

**Comment by MirkoWeber** [comment]
Fixed it by moving all files into my personal folder instead of working on c:\ directly
