### ISSUE TITLE
(Question) Required and optional specifications and facets

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#3780]
According to the [IDS Docs](https://github.com/buildingSMART/IDS/blob/master/Documentation/specifications.md#required-and-optional-specifications-and-facets), specifying minOccurs and maxOccurs for entity facets is allowed.  When I look at the code though, it's omitted https://github.com/IfcOpenShell/IfcOpenShell/blob/dee4cf591e734ca5ec193bde593dfb26052663f2/src/ifctester/ifctester/facet.py#L120-L131

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/83825269/3e0d43f1-de26-4b1a-af9f-dab9ef46e5d8)

**Comment by vulevukusej** [comment]
After looking at the schema it seems that both the Entity and Attribute facets are not allowed the minOccurs, maxOccurs attributes.  Can you confirm I've understood that correctly? If yes then I will update the classes to reflect this.  

p.s. This is what was causing the issue in #3779

**Comment by Moult** [comment]
It's not allowed, but it's being debated and may be changed soon.
