### ISSUE TITLE
Does IfcOpenShell support dynamic link library compilation (*.dll)?

### ISSUE THREAD

**Issue by Jozoooooo** [IfcOpenShell/IfcOpenShell#3785]
Hi, I am using IfcOpenShell in the software I am developing.

Currently the compiled *.lib static library is used. The resulting exe executable is very large in size (139MB) and takes a long time to compile and run each time. When I disable IfcOpenShell related features, the *.exe executable file size is 4.53 MB. This shows that the IfcOpenShell static library takes up a lot of storage space in my software.

Does IfcOpenShell support compilation into dll dynamic link library (*.dll), or how to optimize to solve this problem? Thanks.

**Comment by aothms** [comment]
With some caveats, yes.

See https://github.com/IfcOpenShell/IfcOpenShell/issues/1029

Long-term we'll provide more of a plug-in infrastructure to lazily load dlls when a file of a certain schema is read.

**Comment by Jozoooooo** [comment]
Thanks for your helpful reply. According to #1029, because my software only involves IFC2x3 and IFC4, I tried to set MINIMAL_BUILD and WASM_BUILD in CMakeLists.txt to ON, and recompile to generate a static library.
After using the above static library, my software size was successfully reduced to 26.7MB.

I tried setting BUILD_SHARED_LIBS in CMakeLists.txt to ON to compile the dynamic link library.There are many error messages like `error LNK2001: unresolved external symbol "__declspec(dllimport)`.Only IfcParse.dll is generated.

**Comment by aothms** [comment]
`WASM_BUILD` is something completely different. That's web assembly. I think you're trying to limit the amount of schema versions, but you can just do that directly. `-DSCHEMA_VERSIONS=2x3;4`. Like we do on many of the CI scripts. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/.github/workflows/ci.yml#L78

**Comment by Jozoooooo** [comment]
OK, I regenerated and compiled according to your suggestion, and generated IfcParse.dll, IfcGeom.dll, IfcGeom.lib, IfcGeom_ifc2x3.lib, IfcGeom_ifc4.lib and IfcParse.lib, and they work normally in my program. Thanks again for your suggestions and answers.
