### ISSUE TITLE
Linker Errors When trying to include IFCOpenshell

### ISSUE THREAD

**Issue by MirkoWeber** [IfcOpenShell/IfcOpenShell#379]
Hello, I have a project where I use IFCOpenshell and Opencascade Community Edition.
I have built the IFCOpenshell libs without an error.
I include ifcparse/IfcFile.h and ifcgeom/IfcGeom.h 
plus gp_Quaternion.hxx from OCE.

But when I try to compile my project in Visual Studio x64 under Windows ( the configuration I used to build and compile the libraries ) I get a ton of linker errors ( LNK2001 ) where it complains about unresolved external symbols.

Mostly like this:
///////////////////////////////////////////////////////////////////
Error LNK2001 not resolved external symbol ""public: virtual class opencascade::handle<class Standard_Type> const & __cdecl Standard_Transient::DynamicType(void)const " (?DynamicType@Standard_Transient@@UEBAAEBV?$handle@VStandard_Type@@@opencascade@@XZ)".	ifcconverter	somepath\IfcGeom.lib(IfcGeomHelpers.obj)
////////////////////////////////////////////////////////////////////////////
Which is confusing since I have builded all the dependencies and ifcopenshell 
could also be build without problems. ( Well some warnings, but no errors )

Any Info how to setup visual studio with IFCOpenshell libs would be highly appreciated.
Thanks in advance.

**Comment by MirkoWeber** [comment]
I reduced the LNK errors drastically by adding opencascade libs in the installed build folder to the projects linker addidtional dependencies. The only errors I have left now are of this kind in IfcParse.lib:
///////////////////////////////////////////////////////////////
Fehler	LNK2001	not resolved external symbol "ucnv_flushCache_58".	ifcconverter	C:\somePath\ifcconverter\IfcParse.lib(IfcCharacterDecoder.obj)	1	
///////////////////////////////////////////////////////////////////////////////

**Comment by aothms** [comment]
Yes those would be in icuuc and icudt.lib and relate to ICU. You can run IfcOpenShell cmake with -DUNICODE_SUPPORT=Off.

**Comment by MirkoWeber** [comment]
Thats really strange, I thought when compiling it statically (MT) , I do not need 
to include the dependencies of IFCOpenshell in my project.

**Comment by Stinkfist0** [comment]
I think you need need to add this to your project: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L247

**Comment by Stinkfist0** [comment]
As as side note, it would be great to have an example project available that would demonstrate how to include and link IfcOpenShell and its dependencies to users' own projects.

**Comment by MirkoWeber** [comment]
Thank you, 
however there is a new problem, and I don know if it relates to IFCOpenshell or to OCE.
I have compiled IFCOpenshell with OCE instead of OCCT, 
then I tried those generated libs in my project.
Everything compiled file, 
but the statically linked .exe needs the following libs now to run:
TKBO.DLL
TKBOOL.DLL
TKBREP.DLL
TKERNEL.DLL
TKFILLET.DLL
TKG2D.DLL
TKG3D.DLL
TKGEOMALGO.DLL
TKGEOMBASE.DLL
TKMATH.DLL
TKMESH.DLL
TKOFFSET.DLL
TKPRIM.DLL
TKSHHEALING.DLL
TKTOPALGO.DLL
Has this been observed before? I try to ask this question 
in the OCE boards as well,
if this is not an IFCOpenshell issue, I beg your pardon, and this topic can be closed.

**Comment by Stinkfist0** [comment]
This is actually exactly same issue (and silly business) for OCE/OCCT as well: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L214

**Comment by aothms** [comment]
> As as side note, it would be great to have an example project (external to the main IfcOpenShell repository)

Yeah that's right. CMake modules, akin to [1] would also be really nice to provide.

[1] https://github.com/3drepo/3drepobouncer/blob/master/cmake_modules/FindIFCOPENSHELL.cmake

**Comment by aothms** [comment]
> Yeah that's right. CMake modules, akin to [1] would also be really nice to provide.

Created a new issue for that #437. Closing this one.

**Comment by Moult** [comment]
Closing as no longer relevant. https://github.com/IfcOpenShell/IfcOpenShell/discussions/5102
