### ISSUE TITLE
Inches units shows 12" as 1'-0"

### ISSUE THREAD

**Issue by dm82858** [IfcOpenShell/IfcOpenShell#3792]
![Dimensions](https://github.com/IfcOpenShell/IfcOpenShell/assets/145897181/17f7ba8c-98b6-44f7-8486-49209470fc4a)

Units set to Inches
shows 12" as 1'-0"
Problem is only with 12"

**Comment by theoryshaw** [comment]
@dm82858 I think this is fixed, let me know otherwise.
