### ISSUE TITLE
Blenderbim Addon Error

### ISSUE THREAD

**Issue by sabromeo1961** [IfcOpenShell/IfcOpenShell#3807]
My Blender version is 3.6.1

I did a git pull to update Blenderbim and the BIM Layout was no longer visible. When trying to re-enable the addon there was a different error message (no copy Taken. Re downloaded the addon and installed **_blenderbim-230902-py310-win_**. When Trying to Activate I got the following Error with no BIM TAB.

Restarted Blender several times.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/106636978/f560c68e-dfcf-4b79-834c-e3453c9fe832)

**Comment by Andrej730** [comment]
@sabromeo1961 can you please check - are there more error messages in the system console? 
You can access in Blender -> Window -> Toggle System Console.

**Comment by sabromeo1961** [comment]
Read prefs: "C:\Users\samromeo\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\samromeo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\__init__.py", line 40, in <module>
    import blenderbim.bim
ModuleNotFoundError: No module named 'blenderbim.bim'

**Comment by sabromeo1961** [comment]
# BlenderBIM Add-on - OpenBIM Blender Add-on
# Copyright (C) 2020, 2021 Dion Moult <dion@thinkmoult.com>
#
# This file is part of BlenderBIM Add-on.
#
# BlenderBIM Add-on is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BlenderBIM Add-on is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with BlenderBIM Add-on.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import site

bl_info = {
    "name": "BlenderBIM",
    "description": "Author, import, and export data using the Industry Foundation Classes schema",
    "author": "IfcOpenShell Contributors",
    "blender": (2, 80, 0),
    "version": (0, 0, 230718),
    "location": "File > Export, File > Import, Scene / Object / Material / Mesh Properties",
    "tracker_url": "https://github.com/IfcOpenShell/IfcOpenShell/issues",
    "category": "Import-Export",
}

if sys.modules.get("bpy", None):
    # Process *.pth in /libs/site/packages to setup globally importable modules
    # This is 3 levels deep as required by the static RPATH of ../../ from dependencies taken from Anaconda
    # site.addsitedir(os.path.join(os.path.dirname(os.path.realpath(__file__)), "libs", "site", "packages"))
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "libs", "site", "packages"))

    import blenderbim.bim

    def register():
        blenderbim.bim.register()

    def unregister():
        blenderbim.bim.unregister()

**Comment by Andrej730** [comment]
are you sure you uninstalled the addon according to the instructions in preferences?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/efc620bc-2378-421b-9211-86f0306e9602)

**Comment by sabromeo1961** [comment]
Thanks for your help, no I didn't uninstall the addon according to the instructions in preferences.

**Comment by Andrej730** [comment]
@sabromeo1961 there are definetely different BlenderBIM versions mixed up.

`__init__.py` you sent is from version 230718, not from 230902.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/4dc182ba-2a77-4b11-9c5e-919f93ef9fe3)
