### ISSUE TITLE
Packaging Problem

### ISSUE THREAD

**Issue by c-mellueh** [IfcOpenShell/IfcOpenShell#3808]
I need to package the ifcopenshell python library with pyinstaller.
Packaging works so far.
Whe I try to run the .exe File i get the following error:
```
Traceback (most recent call last):
  File "som_gui\__main__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "ifcopenshell\express\__init__.py", line 29, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'path\\to\\.exe\\_internal\\ifcopenshell\\express\\express_parser.py'
```

if i understand correctly, these lines in [\__init__.py](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/express/__init__.py) are the problem because pyinstaller won't catch the absolute import.:

```python
d = os.path.abspath(os.path.dirname(__file__))
sys.path.append(d)
```

**Comment by aothms** [comment]
I think you can use `hiddenimports` or in your own script explicitly import the optional functionality you need. These in-function imports are there because they rely on pyparsing which is really only needed in rare cases in ifcopenshell usage.

**Comment by c-mellueh** [comment]
It works when adding 
```python
a = Analysis(
     ...
    datas=[('venv/Lib/site-packages/ifcopenshell/express','ifcopenshell/express'),],
    ...
)
```
to my main.spec
But I'm not sure if this is the most pythonic way to solve this problem...

**Comment by aothms** [comment]
Thanks for sharing. I'm also not familiar with these kind of tools
