### ISSUE TITLE
[BlenderBIM] Migration from IFC4 to IFC4X3

### ISSUE THREAD

**Issue by loicgillioz** [IfcOpenShell/IfcOpenShell#3812]
Hello,

First, thanks a lot to all developers, this project is awesome.
I wanted to migrate a project from IFC4 to IFC4x3 to benefit from the new element types (excavations in my case).
I've seen this [tutorial](https://www.youtube.com/watch?v=oLerN4-p76s) where it's shown for upgrading 2x3 to 4. I don't see such option when opening an IFC4 project (migrating to IFC4X3).
That would be a nice addition.

**Comment by aothms** [comment]
From IFC4 to IFC4X3 backwards compatibility was extensively considered. This means that your IFC4 model is likely a valid IFC4X3 model as well (with maybe some optional attributes added at the end of certain types). You could try simply renaming the schema identifier in the header of you model before importing. It's more efficient than trying to programmatically recreating instances using the new schema.

**Comment by loicgillioz** [comment]
I just found the `Quality and Coordination` -> `Quality Control` -> `Patch` -> `Recipes`:`Migrate`. However, specifiying `IFC4X3` as for the field `schema` returns an error : 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/18118854/1af8f6e8-9c21-4752-8f3a-ae6028a9feec)

**Comment by loicgillioz** [comment]
> From IFC4 to IFC4X3 backwards compatibility was extensively considered. This means that your IFC4 model is likely a valid IFC4X3_ADD1 model as well (with maybe some optional attributes added at the end of certain types). You could try simply renaming the schema identifier in the header of your model before importing. It's more efficient than trying to programmatically recreating instances using the new schema.

Thanks a lot for the answer, will try and let you know

**Comment by loicgillioz** [comment]
So this seem to work well. Thanks for the support !

**Comment by loicgillioz** [comment]
Hi there, I just noticed the work schedule somehow disappeared after the migration to IFC4X3 schema (modified in the file as mentioned above). Any idea why ? 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/18118854/ec172cd6-f610-4989-81f1-7a7c59cd4815)

**Comment by Moult** [comment]
Some work schedule properties have changed in IFC4X3. We haven't yet gone through to updating these.

**Comment by Moult** [comment]
The work schedules have now been updated and work for IFC4X3.
