### ISSUE TITLE
How to batch add storeys by scripting?

### ISSUE THREAD

**Issue by htlcnn** [IfcOpenShell/IfcOpenShell#3816]
Hi,
I want to batch add storeys by scripting. I can see there's `bpy.ops.bim.add_building_storey` but it seems to be only executed by clicking the UI button. If I run `bpy.ops.bim.add_building_storey` in Python console, it adds something like `IfcActuatorType/Unnamed.001`. Is there any way to do this by scripting? For a highrise building, I often have storeys' name and elevation ready somewhere in a spreadsheet (or extracted from a dwg drawing), so I want to batch add all storeys once.
Thanks.

**Comment by theoryshaw** [comment]
might give a hint: https://community.osarch.org/discussion/comment/12135/#Comment_12135

**Comment by htlcnn** [comment]
Thanks @theoryshaw . I can see there's `create_building_storeys` here: https://github.com/C-Claus/BlenderScripts/blob/8f00777187ec1761a025999ba5893612f3e91835/BlenderBIM_create_objects/create_grid/create_grid_with_slabs_and_building_stories.py#L130 . It uses `ifcopenshell.file().createIfcBuildingStorey`. I wonder should I use that or is there another "BlenderBIM" way to do it?

**Comment by theoryshaw** [comment]
you could do something like.. 
`self.storey = run("root.create_entity", self.model, ifc_class="IfcBuildingStorey", name="Ground Floor")`
https://sourcegraph.com/github.com/IfcOpenShell/wasm-preview/-/blob/examples/model.py?L36

>  or is there another "BlenderBIM" way to do it?
I don't think there's an automated way to do it in BB, via the UI.

**Comment by htlcnn** [comment]
I was hoping there's something like `create_storey(building, storey_name, storey_elevation)` (returning `{"FINISH"}` is ok in this case) , or `create_storey(building, storey_name) that returns the new storey itself, then I would be able to set the elevation. Is there any kinda "API" for similar tasks?

**Comment by Andrej730** [comment]
> I mean a stable way to do tasks like this. How do I know when to use `ifcopenshell`, or `blenderbim`, or `bpy.ops`?

Some operators (`bpy.ops.`) work only hand-in-hand with UI, some can work independently. It's hard to tell which one is which without looking up [operator's code](https://github.com/IfcOpenShell/IfcOpenShell/blob/5438331fe16598e392685984e75b6334a342b763/src/blenderbim/blenderbim/bim/module/spatial/operator.py#L230C1-L248). For example, `bim.add_building_storey` is working based on currently active container in spatial manager UI.

`ifcopenshell` in 99% of cases designed to work without using BlenderBIM/Blender objects. There are few exceptions like creating representations and styles.

`blenderbim` - I guess you're referring to `blenderbim.tool`. Generally those methods are much more independent from UI than operators..


Currently not sure if there is any better way to do it besides reusing lines below from `bim.add_building_storey`
```python
        blenderbim.core.aggregate.add_part_to_object(
            tool.Ifc,
            tool.Aggregate,
            tool.Collector,
            tool.Blender,
            obj=obj,
            part_class=self.part_class,
            part_name="Unnamed",
        )
```

**Comment by htlcnn** [comment]
@Andrej730 `blenderbim.core.aggregate.add_part_to_object` still needs a StringProperty `part_class` of the operator. `blenderbim` has many reusable modules/functions, so I prefer using it.

**Comment by Andrej730** [comment]
> `blenderbim.core.aggregate.add_part_to_object` still needs a StringProperty `part_class` of the operator.

Typically it's just a string with value "IfcBuildingStorey"

**Comment by htlcnn** [comment]
Thank you @Andrej730 . I'll stick with `blenderbim`
