### ISSUE TITLE
After update to Blender 3.6.4 LTS can't open .ifc with BlenderBim anymore

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3818]
Blender 3.6.4 LTS
BB 230927
Ubuntu 22.04

Before I could just click the .ifc file and it opened in BlenderBim (separate from session in Blender). After the update to Blender 3.6.4 LTS and updating BB to 230927 this doesn't work anymore. I can open it in Blender by using Load Project, and things seem to work normal.
Looks like BlenderBim disappeared, because I can't start it anymore from the menu either.

**Comment by brunopostle** [comment]
Guessing that the path to blender has changed.

In the BlenderBIM preferences click on the 'remove file association' button, then click on the 'associate BlenderBIM with IFC files' button (I can't remember the exact names).

Let us know if this works or doesn't work.

**Comment by WeenDwijler** [comment]
Yep! That is the solution. Everything works again. Thank you.
