### ISSUE TITLE
Apply array doesnt work with Sync Children

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3822]
Apply array doesn't seem to work consistently. 

Doesn't seem to work with a new file...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/578b03f2-f111-4500-80ff-187c6ec78d60

But it works in [this ](https://gitlab.com/openingdesign/highland_haven/-/blob/78326c7db1eb7b9d7e1a2308bce0ffaab9e4c434/Models_and_CAD/BlenderBIM/Highland_Haven.ifc)file. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3feb72ad-eaf2-4b96-8101-a856eb37d4e9

**Comment by theoryshaw** [comment]
Take that back, somewhat... i didn't work on the other ridge line...


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ea141c0a-4348-4b75-8e25-edd52b93bfa7

**Comment by Gorgious56** [comment]
After a short test it seems it's caused by the "Sync Children" option. A workaround is to disable it before applying the array.
