### ISSUE TITLE
Moving an opening in a wall changes the position of other openings too

### ISSUE THREAD

**Issue by carlopav** [IfcOpenShell/IfcOpenShell#3829]
In the reference attached ifc file, moving the central opening also changes the position of the other two openings:
1 - show openings in the wall
2 - move the central opening
![immagine](https://github.com/IfcOpenShell/IfcOpenShell/assets/47068848/0b012165-c7df-428f-8d08-db19fe28d1fa)
3 - apply the opening with the tick next to the Add Void button in the N panel
4 - show openings again
![immagine](https://github.com/IfcOpenShell/IfcOpenShell/assets/47068848/8eed9826-036d-4d25-9e9e-af0b9871fb2b)

[demo.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12774483/demo.zip)

Tested with release 230902 and 230929

**Comment by Gorgious56** [comment]
I can concur, it happened to me too, it's a bit... surprising :) 
Using latest dev version. Openings were created in a version a few weeks prior if that can help (maybe unrelated).
