### ISSUE TITLE
Wall height resets to default 3,00 m once a half space clip is used as a boolean

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3831]
I've encountered a bug recently (pretty critical in my workflow :) ), Blender 3.6.3 - Bbim v 0.0.999999-9461bf2

![animation](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/a78e1db3-af29-4ff7-a269-4e463825e588)

It's not visible in the video but the height defaults to 3,00m. User can change the height in the debug panel but the height resets back to 3,00 m afterwards on regen. I've confirmed it happens when at least one manual half clipping plane is used and reverts to normal when all manual half clipping planes are removed. 

test file

[bug_half_clip_plane.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12778141/bug_half_clip_plane.ifc.txt)

**Comment by Gorgious56** [comment]
Maybe reated to ? https://github.com/IfcOpenShell/IfcOpenShell/issues/3709

**Comment by Andrej730** [comment]
This bug occured after after 0044ef5 closing #3615 after d26a258 solving #3605 which all is indeed part of #3709 😅

**Comment by Gorgious56** [comment]
Haha this is a commit-ception ! :) Or the unintended downstream consequences of changing a single line of code >< Thank you for the fix.

Cheers

**Comment by theoryshaw** [comment]
Just a hunch, i think this issue was fixed too! :)
https://github.com/IfcOpenShell/IfcOpenShell/issues/3715
