### ISSUE TITLE
System Connect Port references wrong element

### ISSUE THREAD

**Issue by taylorhorwood** [IfcOpenShell/IfcOpenShell#3832]
Example in documents references the wrong element on these lines. It references duct instead of the fitting element.

https://github.com/IfcOpenShell/IfcOpenShell/blob/9461bf21291a11e82ae4713eb68a74f119e48437/src/ifcopenshell-python/ifcopenshell/api/system/connect_port.py#L85C1-L86C89

**Comment by Andrej730** [comment]
Nice catch!
