### ISSUE TITLE
build VS Solution

### ISSUE THREAD

**Issue by KSpeiser** [IfcOpenShell/IfcOpenShell#384]
Hi,

I'm new to IfcOpenShell and still trying to build it correctly. I followed the given steps:
                   cd IfcOpenShell\win
                   build-deps.cmd
                   run-cmake.bat
After that I opened the Visual Studio Solution and built the "INSTALL".
I'm not sure if everything worked. Anyways, How can I use IfcOpenShell now?
I know that's basics stuff, but I am quite new to all the programming. 
Thanks a lot!

**Comment by aothms** [comment]
> How can I use IfcOpenShell now?

You'll likely have a bunch of executable (notably IfcConvert.exe) somewhere on your hard drive, a python ifcopenshell module, software libraries to build other apps (IfcParse -Geom.lib).

What would you want to do with them?

**Comment by KSpeiser** [comment]
Yes. in the "installed" folder I can find .lib, .exe and quite a few of cpp Header files. 
I want to select multiple items of an ifc file, read information and change information and ideally return an ifc-file containing the selectes instances only.

**Comment by Moult** [comment]
Closing as the question seems to be answered and there are lots of tutorials and content now out there for IfcOpenShell-Python
