### ISSUE TITLE
Documentation Outdated

### ISSUE THREAD

**Issue by smarnav2904** [IfcOpenShell/IfcOpenShell#3841]
I'm testing the Selector Util that you provided and testing this exact example: 
`import ifcopenshell
import ifcopenshell.util.selector

model = ifcopenshell.open("model.ifc")
# Get all concrete walls and slabs.
ifcopenshell.util.selector.filter_elements(model, "IfcWall, IfcSlab, material=concrete")`

Throws this error: 
`Traceback (most recent call last):
  File "/home/santi/IfcSemanticInfo/materials.py", line 6, in <module>
    ifcopenshell.util.selector.filter_elements(model, "IfcWall, IfcSlab, material=concrete")
AttributeError: module 'ifcopenshell.util.selector' has no attribute 'filter_elements'`

However, thanks to my IDE it tells me tring to use ifcopenshell.util.selector.Selector which is a class defined in that module that got that same exact method, but using a query as provided on the example still doesn't work as intended.
The error it throws is the next one:
`Traceback (most recent call last):
  File "/home/santi/IfcSemanticInfo/materials.py", line 9, in <module>
    sel.filter_elements(model, model.by_type("IfcElement"), "material=concrete")
  File "/home/santi/.local/lib/python3.10/site-packages/ifcopenshell/util/selector.py", line 140, in filter_elements
    key = filter_rule.children[0].children[0]
AttributeError: 'str' object has no attribute 'children'`

Could you provide further instructions on how to use the selector correctly?

**Comment by Moult** [comment]
It sounds like you have an outdated version of ifcopenshell. The documentation is correct. How did you install it?

**Comment by smarnav2904** [comment]
Downloading the prebuilt package from your website to my corresponding Python version, 3.6 in my particular case.

**Comment by Amoki** [comment]
Python 3.6 is really outdated and I doubt IfcOpenShell still builds for Python 3.6.
https://devguide.python.org/versions/

**Comment by smarnav2904** [comment]
I'll try with other computer that I got with a recent Python version and let you kwow

**Comment by Moult** [comment]
The problem is that our download page docs need refreshing. Not sure why I missed this. I'll check in detail tomorrow.

For now you can download from here https://github.com/IfcOpenBot/IfcOpenShell/commit/f0e03c79df4fe2ee4d4a778bc0402258871426b9#commitcomment-127480286
