### ISSUE TITLE
Some odd subpanels in the 'Geometry and Materials' panel. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3842]
I'm not sure how it happened but there's some odd subpanels in the 'Geometry and Materials' panel. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/93bdc55e-b265-41c2-8c7a-cc30f364926e)

I have been working with the Cloth modifier as of late, and keeping the blender/ifc file connection in sync.

**Comment by Gorgious56** [comment]
Those are indeed vanilla simulation panels. I guess they either haven't been taken into account in the unregister / register hack for the bbim panels or their are dynamically re-registered when you create a simulation ? Do they keep coming back if you close / reopen the blend file ?

**Comment by theoryshaw** [comment]
> Do they keep coming back if you close / reopen the blend file ?

Yes they do. 

They do not, if the ifc file is opened anew.

**Comment by Moult** [comment]
I can't recreate this. That panel only ever shows up in my Physics tab. Are you able to recreate it with a minimal file with step by step and / or share the blend?

**Comment by theoryshaw** [comment]
I can't either, it seems. I'll keep my eyes open though.

**Comment by theoryshaw** [comment]
some more odd panels showed up. :)  Not sure how, again. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/64e330dc-70ba-4cdb-bbee-0e0f332a6a5c)
