### ISSUE TITLE
`material.Category` doesn't seem to work in EPset_Drawing's `Metadata` parameter. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3844]
`material.Category` doesn't seem to work in EPset_Drawing's `Metadata` parameter. 

That is, it doesn't seem SVG classes are created with the material categories.

**Comment by theoryshaw** [comment]
`material.Name` doesn't seem to work either.

**Comment by theoryshaw** [comment]
upon investigating this further, `material.Category` and `material.Name` seem to work if the object material is applied as an `IfcMaterial`, but does not when it's applied as a `IfcMaterialLayerSetUsage`.

**Comment by Moult** [comment]
If you use `mats.Name` it will turn up as things like `matsName-Testy1MaterialTesty2Material` and `matsName-Testy1Material`.
