### ISSUE TITLE
FileNotFoundError for report.html in to_string() function when installing IfcTester via pip 

### ISSUE THREAD

**Issue by SigveMartin** [IfcOpenShell/IfcOpenShell#3852]
I have installed IfcTester via pip in a python 3.9 environment. 

I can see that templates/ is missing from the ifctester module. This causes the to_string() function of the reporter.py: 

```python    
def to_string(self):
        import pystache

        with open(os.path.join(cwd, "templates", "report.html"), "r") as file:
            return pystache.render(file.read(), self.results)
```
To error out as it checks for the template in '{...}.venv/lib/python3.9/site-packages/ifctester/templates/report.html'

**Comment by aothms** [comment]
Ah yes, I recently added the .xsd which was missing as well, but the same would apply to .html. Restarted the publishing workflow.
