### ISSUE TITLE
Slabs are reloated after running `bim.refresh_aggregate()` and opening blender file again. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3855]
This one's a strange one. 

I'm currently syncing Highland_Haven.blend/Highland_Haven.ifc

After running `bim.refresh_aggregate()` on the various child aggregates everything seems to have worked okay. 

But if I close the blender file, and open it again, a certain number of slabs are located incorrectly.  Highlighted in the image below. 

If, however, I open the IFC anew, the slabs are in the correct position. 

files here: https://gitlab.com/openingdesign/highland_haven/-/tree/c5f5cf1b5598ddb8115fbbb7aa4407f23844f180/Models_and_CAD/BlenderBIM

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ecae65ed-69e4-403a-9d82-fbb09d5841e4)

**Comment by Andrej730** [comment]
Is there some simpler way to reproduce this on smaller project?

**Comment by Andrej730** [comment]
Some objects have animation keyframes on their location, this is why they are keep coming back to their keyframed location.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/13c34aed-ab51-45ed-ba1b-57e8425c29ee)


Clear keyframes:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/e6a9678c-8965-480f-8457-ceb5ead336aa)

**Comment by theoryshaw** [comment]
aw yes  silly me. thanks @Andrej730!
