### ISSUE TITLE
Constructing corrugated roof with IfcOpenShell

### ISSUE THREAD

**Issue by khuongtran78** [IfcOpenShell/IfcOpenShell#3865]
Hi,

Thanks very much for open source this package. I am learning to use the library and trying to use it to create a corrugated roof as in the link. [https://wiki.freecad.org/File:Arch_panel_wave.jpg](url). I would like to ask if there is any hint on how this can be achieved?

Regards,

**Comment by Moult** [comment]
This is done either using a profile (if you have a fixed profile such as when you know that each roof sheet is exactly X width) https://blenderbim.org/docs-python/ifcopenshell-python/geometry_creation.html#profile-representations or using a custom representation if you just want an arbitrary custom extrusion https://blenderbim.org/docs-python/ifcopenshell-python/geometry_creation.html#custom-representations
