### ISSUE TITLE
installing blenderbim

### ISSUE THREAD

**Issue by Magnus952** [IfcOpenShell/IfcOpenShell#3882]
Hello.

I have installed blender  3.6.4. 

Then i want to install the blenderbim add on. Im currently trying to install blenderbim 231012.
When i  try to install it, im not getting the import-export blenderbim. I only get system:blenderbim.
Have anyone got the same issue?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/147736464/34381ad7-9f69-4911-81e0-356408ad38f7)

**Comment by theoryshaw** [comment]
I think this is indented, and has been changed awhile ago. 

Where did you see `import-export blenderbim`?

If a BB beginner, would recommend asking questions on https://community.osarch.org/categories/general

**Comment by Magnus952** [comment]
> I think this is indented, and has been changed awhile ago.
> 
> Where did you see `import-export blenderbim`?
> 
> If a BB beginner, would recommend asking questions on https://community.osarch.org/categories/general

Hello.

I have seen it on every install video i have looked up. I still cannot import IFC files. 

Thanks, i will ask the question over there also
