### ISSUE TITLE
Insert IFC at specific coordinates into another IFC

### ISSUE THREAD

**Issue by yacsha** [IfcOpenShell/IfcOpenShell#3886]
It is possible to Insert an IFC inside another IFC, specifying the insertion coordinates x, y, z with respect to the destination IFC?

If possible, will there be some example code to do it for c++?

Best regards

**Comment by Moult** [comment]
In Python, you can use IfcPatch https://blenderbim.org/docs-python/ifcpatch.html to first OffsetObjectPlacements https://blenderbim.org/docs-python/autoapi/ifcpatch/recipes/OffsetObjectPlacements/index.html and then MergeProject https://blenderbim.org/docs-python/autoapi/ifcpatch/recipes/MergeProject/index.html to combine them.
