### ISSUE TITLE
IFC file header with null 'name' field in FILE_NAME section

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#389]
Hi, we encountered a file that had null value for `name` in the `FILE_NAME` section: `FILE_NAME($,...);`. It would appear this is not explicitly disallowed by the specification. Currently when doing XML output with IfcConvert it crashes on uncaught exception here: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/XmlSerializer.cpp#L357 I wonder what would be the preferred way to handle this? In any case, IMO, in case of a null value, omitting the field completely instead of writing it with empty string would be the way to go, regardless of implementation.

**Comment by aothms** [comment]
Some of the older versions of Tim Chipman's example files indeed had this problem. But in principle this can happen anywhere there is a non-optional attribute set as null, e.g. a `GlobalId`. The only real solution is to validate instances. IfcOpenShell has all the required latebound schema knowledge to implement this (not for header entities though, these only have early bound type information). I plan to work on this for the 0.6.0 release. The quickest fix now it to wrap everything (individually?) in a try-catch statement :( ?

**Comment by CyrilWaechter** [comment]
Issue still occurs. Steps to reproduce with [WallInstance_IFC4Add2.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/10367711/WallInstance_IFC4Add2.ifc.zip):
```shell
IfcConvert WallInstance_IFC4Add2.ifc WallInstance_IFC4Add2.xml
```

Error message:
```
IfcOpenShell IfcConvert 0.7.0 (OCC 7.6.3)
Scanning file...
Done scanning file   
Parsing input file took 0 seconds
Writing XML output...
Done! Conversion took 0 seconds

Log:
[Error] [2023-01-08 05:20:40] Failed to get ifc file header file_name name, error: 'Token $ at offset 1265 invalid string'
```
File is validated without issue.

**Comment by Moult** [comment]
Slightly different error with v0.8.1:

[Error] [2024-10-11 10:38:04] Failed to get ifc file header file_name name, error: 'Type held at index 0 is 5Blank and not NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'

**Comment by aothms** [comment]
This is fixed. An error is logged, but that's just for informative purposes, because the file is invalid. The XML file is produced correctly.

```
IfcOpenShell IfcConvert 0.8.0 (OCC 7.8.1)
Scanning file...
Done scanning file
Done resolving references
Parsing input file took 0 seconds
Writing XML output...
Done! Conversion took 0 seconds

Log:
[Error] [2024-10-11 09:05:50] Failed to get ifc file header file_name name, error: 'Type held at index 0 is class Blank and not class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >'
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<ifc xmlns:xlink="http://www.w3.org/1999/xlink">
	<header>
		<file_description>
			<description>ViewDefinition [ReferenceView_V1.0]</description>
			<implementation_level>2;1</implementation_level>
		</file_description>
		<file_name>
			<author/>
			<organization/>
			<time_stamp>2019-06-05T07:56:53</time_stamp>
			<preprocessor_version>The EXPRESS Data Manager Version 5.02.0100.07 : 28 Aug 2013</preprocessor_version>
			<originating_system>20180328_1600(x64) - Exporter 19.0.1.1 - Alternate UI 19.0.1.1</originating_system>
			<authorization/>
		</file_name>
		<file_schema>
			<schema_identifiers>IFC4</schema_identifiers>
		</file_schema>
	</header>
```
