### ISSUE TITLE
BCF module installation problem and functionality of it?

### ISSUE THREAD

**Issue by korayinal** [IfcOpenShell/IfcOpenShell#3891]
Hi,

When i try to use the bcf module, i get a error as following: 

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> Cell In[4], line 35
>      32 # show results:
>      33 reporter.Console(my_ids).report()
> ---> 35 reporter.Bcf(my_ids).to_file("my_bcf")
> 
> File ~\anaconda3\lib\site-packages\ifctester\reporter.py:334, in Bcf.to_file(self, filepath)
>     333 def to_file(self, filepath):
> --> 334     from bcf.v2.bcfxml import BcfXml
>     336     bcfxml = BcfXml.create_new(self.results["title"])
>     337     for specification in self.results["specifications"]:
> 
> ModuleNotFoundError: No module named 'bcf.v2'
> 
How do i install these extra modules?

And after that, how can i find more information about the bcf module? such as how to use it? how to create bcf files and so.

**Comment by aothms** [comment]
The library is called `bcf-client` https://pypi.org/project/bcf-client/  https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/bcf/pyproject.toml#L9

Usage instructions https://blenderbim.org/docs-python/bcf.html

**Comment by korayinal** [comment]
Thank you very much, Thomas!
