### ISSUE TITLE
IfcConvert v0.7.0 : Obj file no materials?

### ISSUE THREAD

**Issue by seghier** [IfcOpenShell/IfcOpenShell#3896]
Hello, the output obj file generated by the new version 0.7.0 can't imported with assigned materials, I test it in Rhino and Blender,
is there any option can fix that?

**IfcConvert 0.5.0**
```
./IfcConvert --use-element-names sample.ifc sample.obj
IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev
Scanning file...
Done scanning file
Creating geometry...
Done creating geometry (351 objects)
Conversion took 3 seconds

-----------------------------------------------------------------------

# File generated by IfcOpenShell 0.5.0-dev
newmtl IfcPlate
Kd 0.8 0.8 0.8
newmtl IfcMember
Kd 0.65 0.6 0.6
newmtl IfcMechanicalFastener
Kd 0.7 0.7 0.7
newmtl IfcBeam
Kd 0.75 0.7 0.7
newmtl IfcColumn
Kd 0.7 0.7 0.7
```
**IfcConvert v0.7.0**
```
./IfcConvert --use-element-names sample.ifc sample.obj
IfcOpenShell IfcConvert v0.7.0-f0e03c79d (OCC 7.5.3)
Scanning file...
Done scanning file
Parsing input file took 0 seconds
Creating geometry...
Done creating geometry (351 objects)

-----------------------------------------------------------------------

# File generated by IfcOpenShell v0.7.0-f0e03c79d
newmtl IfcPlate
Kd 0.8 0.8 0.8
newmtl IfcMember
Kd 0.65 0.6 0.6
newmtl DefaultMaterial
Kd 0.7 0.7 0.7
newmtl IfcBeam
Kd 0.75 0.7 0.7
```
[sample.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12920775/sample.zip)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/6026588/2ad8345d-7ed6-4905-b57c-7bc00c4663e5)

**Comment by aothms** [comment]
Judging from the .mtl files you pasted there are only default materials used (they are identified by the IFC entity name instead of a surface style name from the model). It's likely some change in the default colors (you can supply them yourself in .json btw). This is a very old model, these days almost every element has dedicated surface styles, I don't think this is an actual defect in the software.

**Comment by Moult** [comment]
Agreed, there are actually no colours in the model at all, so this is not a bug. The colours you saw before as @aothms says were probably just IfcOpenShell applying arbitrary "default IFC object class colours".

![2023-10-20-134451_301x74_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/be92bf7b-aedd-460d-a49a-d0061134446d)

**Comment by seghier** [comment]
Thanks but there is something wrong with this version.
Previous versions like IfcConvert 0.6.0 works as expected.

**Comment by Moult** [comment]
I've just double checked and nothing is wrong in this version. Previous versions simply used a different default colour. That default colour is an artificial colour introduced by IfcConvert - it does not exist in the IFC. IfcConvert still creates default materials and you can configure the colours using JSON if you'd like.

![2023-10-20-204229_890x650_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/156be212-07a8-4659-af2f-c522f0ea6023)
![2023-10-20-204221_910x669_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/a3dc2b4c-3bc3-47a9-b925-554b7af8fa38)
