### ISSUE TITLE
Simple file only containing IfcOpeningElement seems to trigger endless loop

### ISSUE THREAD

**Issue by rubendel** [IfcOpenShell/IfcOpenShell#390]
Bimserver version:|1.5.101 (and older from sporadic tests)
-- | --
Render engine name | IfcOpenShell
Render engine version | IfcOpenShell-0.5.0-dev-2
Render engine plugin version | 0.5.26

One of the intermediate IFC files generated by BIMserver seems to trigger an endless loop (with memory increasing). The file is attached. It's a file with 10 IfcOpeningElement objects. It could of course be the case that the file is invalid, but this should not result in an endless loop.

Original issue on BIMserver tracker: https://github.com/opensourceBIM/BIMserver/issues/760

**Comment by rubendel** [comment]
[IfcOpeningElement-error-5.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/2044460/IfcOpeningElement-error-5.ifc.txt)

**Comment by aothms** [comment]
I can indeed reproduce this, not sure if it's infinite though. The issue with these huge cylinders (radius=150m) is that the meshing in IfcOpenShell uses an absolute deflection so you end up using a lot of triangles with the default of 1mm. Almost 50k triangles per cylinder. Not sure whether that's desirable, but I am also not convinced that elements with these radii have a meaningful place in IFC? When linking against newer version of OCC, which will happen for the newer builds, the generation is pretty much instantly.

Oh after I was typing this, my guess is you simply forgot to add the unit information. There is also no IfcProject in this file :)

**Comment by rubendel** [comment]
Ah thanks @aothms, my bad (again). The problem was that for IfcOpeningElements, I could not rely on a decomposes path up to IfcProject because there is none. New code will use the decomposes path of the "voided" object.
