### ISSUE TITLE
IfcZones BlenderBIM UI integration

### ISSUE THREAD

**Issue by bsmithuk** [IfcOpenShell/IfcOpenShell#3905]
Using the example IFC files from Prairie Consulting (https://prairieskyconsulting.com/examples - Shared under CC BY-SA 4.0 license) when models with 'Zones' are loaded into BlenderBIM the 'Zones' or IfcZone/IfcSpatialZones are not visible within the interface.  This can be recreated on non-CC BY-SA 4.0 projects in both Architectural and Building Services models. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/858b7f62-fccd-403f-a518-c8bd8fd56663)
vs Properiatary tools that do identify IfcZones:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/8f0ff8a3-70f5-4d3a-b909-45f963f2f7c3)

**Comment by Moult** [comment]
I'd like to keep this open since although this is a good short term solution, ideally we shouldn't mix distribution systems and zones. They are two different things with different purposes.

**Comment by Moult** [comment]
Resolved here https://github.com/IfcOpenShell/IfcOpenShell/commit/f3b541f00a184238f552471ece59fe7eb285ea34
