### ISSUE TITLE
[ifcopenshell-python] Mypy error: Skipping analyzing "ifcopenshell": module is installed, but missing library stubs or py.typed marker

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#3909]
So I wanted to use type hints for my code and [Mypy](https://mypy.readthedocs.io/en/stable/) to control it. This was my following test code in the ifcopenshell-mypy.py file:

```
import numpy as np
import ifcopenshell

print(type(np.arange(10)))
print(type(ifcopenshell.file()))

correct_example: np.ndarray = np.arange(10)
false_example: np.ndarray = 10

test_example: ifcopenshell.file = ifcopenshell.file()
test_false_example: ifcopenshell.file = 12
test_false_type_example: int = ifcopenshell.file()
```

And when I did,`mypy ifcopenshell-mypy..py` this was the message on my terminal:

```
ifcopenshell-mypy.py:2: error: Skipping analyzing "ifcopenshell": module is installed, but missing library stubs or py.typed marker  [import-untyped]
ifcopenshell-mypy.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
ifcopenshell-mypy.py:8: error: Incompatible types in assignment (expression has type "int", variable has type "ndarray[Any, Any]")  [assignment]
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by Andrej730** [comment]
resolved after 722201a

**Comment by Martin15135215** [comment]
Thanks! One little question: Should one not change the pyproject.toml to add py.typed to be included in the distribution?

**Comment by Andrej730** [comment]
Given the current pyproject.toml settings it's probably is included already and will be added after the next time we update package on pypi.

https://github.com/IfcOpenShell/IfcOpenShell/blob/bc72c927c1d6737730a2db1391e5b4a9e4de21d3/src/ifcopenshell-python/pyproject.toml#L24-L30
