### ISSUE TITLE
A utility to remove unused Materials and Styles

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3914]
Would be nice to have a utility to remove unused Materials and Styles.

**Comment by Andrej730** [comment]
You can try "Purge unused elements by class" - it's not very clever, it just works in similar way to "Purge Unused Profiles", it's removing elements that are not referred by any other elements.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/91814fc9-7452-465e-bb7b-7b81bb176c66)

**Comment by theoryshaw** [comment]
@Andrej730 thank you for suggesting. 

I ran some tests, it seems running `IfcMaterial` and `IfcSurfaceStyle` does not work but if you run `IfcMaterialDefinitionRepresentation` it removes all the unused IfcMaterials and IfcSurfaceStyles.

Will run some more tests. 
Thanks!

**Comment by theoryshaw** [comment]
I noticed it seems overly aggressive when purging `IFCSTYLEDITEM`s.  It removes styles that are used in the file. 
Here's a test file. 
[20231212 - material and style purge test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13650048/20231212.-.material.and.style.purge.test.ifc.txt)

**Comment by Andrej730** [comment]
Yeah, this utility is kind of low level. You can print stats for unused elements in your project to get the idea about elements it's able to delete.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/d04eb9a2-72e7-4ea1-b0f7-5eb53bb3ace8)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/f77ff866-2262-4b3a-b034-c91cd0101ada)


> I noticed it seems overly aggressive when purging IFCSTYLEDITEMs. It removes styles that are used in the file.

If you want to remove styles you're probably looking for [IfcSurfaceStyle](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcSurfaceStyle.htm). `IfcStyledItem` is just an entity that connects styles (e.g. `IfcSurfaceStyle`) and styled items (e.g. IfcExtrudedAreaSolid), like `IfcRelAssociatesMaterial` connects some `IfcElement` to `IfcMaterial`. But what I've noticed is that relationship is usually is not referred by any other elements - so I'll hide it from "unused elements stats", so it won't draw any attention.

**Comment by theoryshaw** [comment]
This is awesome @Andrej730 

Dumb question perhaps... i ran this utility.  As a random example below, i would assume these materials and styles with zero users, would be deleted.   Or am i using this incorrectly? 

![image](https://github.com/user-attachments/assets/57215247-3467-43be-9c8f-23cd1357417d)

**Comment by Andrej730** [comment]
> Dumb question perhaps... i ran this utility. As a random example below, i would assume these materials and styles with zero users, would be deleted. Or am i using this incorrectly?

They should be purged. Can you share some example .ifc?

**Comment by Andrej730** [comment]
I was wrong about those numbers - they're showing not all material/style uses but number of elements/element types using them. If material is part of some material set that's not assigned to any elements it will also show 0. But anyway for materials if this number is 0 then purge should always remove them.

But they should be purged now after the latest commits - it will now try to purge materials multiple times, so after it removes an unused material set, it will also remove IfcMaterials that became unused too. There also was an issue when it wouldn't purge materials that either have material style / material properties.

Regarding the styles it's a bit different - if style is assigned to a material that's not used anywhere, then this number will be 0 but this style won't be purged as it's still used by a material. So, purging materials first and then purging the styles should remove all styles with 0 elements (unless it's something weird with IFC file).

Investigating your project I've found an issue in IOS when removing object wasn't removing IfcShapeAspects so they were left orphaned and it was preventing some styles from being purged, should be fixed now.

I've wrote a script to remove all unused shape aspects and their representation. But this script reduces filesize from 42MB to 17MB(!) so I feel like it's either I'm missing something or it's really a lot of garbage representations. Can you please take a look at the model after running script (might take a bit, you can see the progress in the console) - does it look okay, anything missing?

```python
import bonsai.tool as tool
import ifcopenshell.api.geometry
import ifcopenshell.api.layer

ifc_file = tool.Ifc.get()

reps = set()
shape_aspects = []
for shape_aspect in ifc_file.by_type("IfcShapeAspect"):
    if shape_aspect.PartOfProductDefinitionShape is None:
        representations = shape_aspect.ShapeRepresentations
        ifc_file.remove(shape_aspect)
        for rep in representations:
            for layer in rep.LayerAssignments:
                ifcopenshell.api.layer.unassign_layer(ifc_file, [rep], layer)
            assert ifc_file.get_inverse(rep) == set()
            reps.add(rep)

n_reps = len(reps)
for i, rep in enumerate(reps, 1):
    ifcopenshell.api.geometry.remove_representation(ifc_file, rep)
    print(f"{i}/{n_reps} representations removed.")
```

**Comment by theoryshaw** [comment]
will do.. will look at it monday. Have a good weekend!

**Comment by theoryshaw** [comment]
This is holding so far!  :)
Thank you.
