### ISSUE TITLE
Different between reading geometry ifcopenshell, web-ifc and XBIM

### ISSUE THREAD

**Issue by RyugaRyuzaki** [IfcOpenShell/IfcOpenShell#3922]
I try reading geometry in ifcopenshell and comparing with other libraries, it seems it might be slower than web-ifc and XBIM, Here is the comparison: 
![ifcopenshell](https://github.com/IfcOpenShell/IfcOpenShell/assets/89787521/1dc597ca-7f72-4362-b6a1-dacff743d6e7)
![web-ifc](https://github.com/IfcOpenShell/IfcOpenShell/assets/89787521/2bdd711e-afa7-4ad3-b976-d98972bd1361)
![xbim net](https://github.com/IfcOpenShell/IfcOpenShell/assets/89787521/249b944c-69c8-4f0e-9981-77b32bf16c6e)
You can test repo :https://github.com/RyugaRyuzaki/ifc-parser-compare

**Comment by Moult** [comment]
@aothms I find this particularly interesting because XBIM also uses OCC, so I'm surprised if there is a significant difference.

**Comment by RyugaRyuzaki** [comment]
Here is file :https://drive.google.com/file/d/1m32o4TfIh_WxytzdaSmOeWw-jwm_xXxo/view?usp=share_link

**Comment by aothms** [comment]
It appears the IfcOpenShell test is the only one that writes the data to
console. Keep in mind that that is very slow, especially on windows.

Your web-ifc run seems to emit an error. Can it actually find the model?

IfcOpenShell does a lot of preprocessing and validation and logging. This
comes with a performance cost.

Is multi threading configured in the same way for each?

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op za 21 okt. 2023 13:29 schreef RyugaRyuzaki ***@***.***>:

**Comment by RyugaRyuzaki** [comment]
Your web-ifc run seems to emit an error. Can it actually find the model? @aothms did you install package node_module before run dev? place your model on ./src!  xbim i just figured out that i just only call read lines not all vertices and face.

**Comment by aothms** [comment]
I mean the following from your own output:

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/ae2840df-d1fa-4abb-8377-243317c9153f)

**Comment by RyugaRyuzaki** [comment]
> I mean the following from your own output:
> 
> ![afbeelding](https://user-images.githubusercontent.com/1096535/277131869-ae2840df-d1fa-4abb-8377-243317c9153f.png)

well, it's just wrong directory,then i fix, you can see the below

**Comment by aothms** [comment]
Oh wait, and perhaps more importantly. Are you sure this actually evaluates geometry, and not just parses the instances from the model:

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/495fce63-b18a-43b1-9560-f7b2f043a202)

Before comparing performance I would really be sure that you get equivalent output from the various tools.

**Comment by Moult** [comment]
@RyugaRyuzaki similarly can you confirm that the snippet for web-ifc actually returns verts / edges / faces / materials / shape matrixes?

**Comment by RyugaRyuzaki** [comment]
> Oh wait, and perhaps more importantly. Are you sure this actually evaluates geometry, and not just parses the instances from the model:
> 
> ![afbeelding](https://user-images.githubusercontent.com/1096535/277152811-495fce63-b18a-43b1-9560-f7b2f043a202.png)
> 
> Before comparing performance I would really be sure that you get equivalent output from the various tools.

no, no, this is my mistake, it only filters out 1 row without the conversion process into vertices, faces ..What I want to find out is clearly as shown below, the 2 columns it has are the same geometry but different matrix, is it possible to read geometry only once and the matrix is ​​different, then I can convert each geometry to its correct matrix 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/89787521/6d9067a3-388b-4194-a4e0-73333e236bf4)
Obviously the two columns have the same IFCREPRESENTATIONMAP , is it possible to read it once?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/89787521/7049b9fb-10db-4453-9b62-6f071245a161)

**Comment by RyugaRyuzaki** [comment]
> @RyugaRyuzaki similarly can you confirm that the snippet for web-ifc actually returns verts / edges / faces / materials / shape matrixes?
> 
> The reason I ask is because testing locally, Blender takes 10 seconds to open the file, whereas https://platform.thatopen.com/app which is the web-ifc equivalent takes 45 seconds.

@Moult   No, it only has matrix and vertices without faces and edges 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/89787521/52e9797c-7c79-4695-9c61-7d3348f810ad)
https://github.com/RyugaRyuzaki/ifc-parser-compare/blob/main/web-ifc_vs_ifcopenshell/src/IfcLoader.ts#L55

And I just read more IfcSpace without IfcOpening
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/89787521/d85c6428-64e8-4c0e-b87e-e52114e6db31)
https://github.com/RyugaRyuzaki/ifc-parser-compare/blob/main/web-ifc_vs_ifcopenshell/src/IfcLoader.ts#L41

**Comment by Moult** [comment]
> no, no, this is my mistake, it only filters out 1 row without the conversion process into vertices, faces ..

Agreed, the XBim snippet looks as though it's not doing any geometry processing at all.

> What I want to find out is clearly as shown below, the 2 columns it has are the same geometry but different matrix, is it possible to read geometry only once and the matrix is ​​different, then I can convert each geometry to its correct matrix

Internally, the IfcOpenShell geometry iterator will only read shared geometries once. The `shape.geometry.id` result of the iterator will let you know if you can reuse the geometry - shapes with the same geometry.id are shared but with different matrixes (shape.transformation.matrix).

Like this:

```python
geometry_cache = {}
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
if iterator.initialize():
    while True:
        shape = iterator.get()
        matrix = shape.transformation.matrix.data
        mesh = geometry_cache.get(shape.geometry.id, None)
        if not mesh:
            geometry_cache[shape.geometry.id] = your_create_geometry_function(shape.geometry.verts, shape.geometry.faces)
        apply_matrix_to_mesh(matrix, mesh)
```

>  No, it only has matrix and vertices without faces and edges

What's the purpose of only getting matrix and vertices? You can't visualise that.

**Comment by RyugaRyuzaki** [comment]
> > no, no, this is my mistake, it only filters out 1 row without the conversion process into vertices, faces ..
> 
> Agreed, the XBim snippet looks as though it's not doing any geometry processing at all.
> 
> > What I want to find out is clearly as shown below, the 2 columns it has are the same geometry but different matrix, is it possible to read geometry only once and the matrix is ​​different, then I can convert each geometry to its correct matrix
> 
> Internally, the IfcOpenShell geometry iterator will only read shared geometries once. The `shape.geometry.id` result of the iterator will let you know if you can reuse the geometry - shapes with the same geometry.id are shared but with different matrixes (shape.transformation.matrix).
> 
> Like this:
> 
> ```python
> geometry_cache = {}
> settings = ifcopenshell.geom.settings()
> iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
> if iterator.initialize():
>     while True:
>         shape = iterator.get()
>         matrix = shape.transformation.matrix.data
>         mesh = geometry_cache.get(shape.geometry.id, None)
>         if not mesh:
>             geometry_cache[shape.geometry.id] = your_create_geometry_function(shape.geometry.verts, shape.geometry.faces)
>         apply_matrix_to_mesh(matrix, mesh)
> ```
> 
> > No, it only has matrix and vertices without faces and edges
> 
> What's the purpose of only getting matrix and vertices? You can't visualise that.

Here :https://github.com/IFCjs/components/blob/main/src/fragments/FragmentIfcLoader/src/geometry-reader.ts#L56-L66
The reason I think is that the threejs Buffergeometry version only needs vertices and indices to render objects without needing faces. As for rendering to Edge, after having geometry, they will use another function to render.

**Comment by RyugaRyuzaki** [comment]
The reason I ask is because testing locally, Blender takes 10 seconds to open the file, whereas https://platform.thatopen.com/app which is the web-ifc equivalent takes 45 seconds. @Moult I think that in addition to reading Geometry and rendering, they also have to read its data, so I think it might take longer
https://github.com/IFCjs/components/blob/main/src/fragments/FragmentIfcLoader/index.ts#L79-L82 
And this is where they read the data :https://github.com/IFCjs/components/blob/main/src/fragments/FragmentIfcLoader/src/data-converter.ts

**Comment by Moult** [comment]
> The reason I think is that the threejs Buffergeometry version only needs vertices and indices to render objects without needing faces.

Indices sounds like faces to me.

I'll do some testing with cgal and see what happens.

**Comment by Moult** [comment]
With CGAL this is now significantly faster. It takes 2.25 seconds to open and 2.4 seconds on my machine to process all the geometry.

**Comment by RyugaRyuzaki** [comment]
> With CGAL this is now significantly faster. It takes 2.25 seconds to open and 2.4 seconds on my machine to process all the geometry.

Hi i upgrade version 0.8.0 then run this code. 
```
import ifcopenshell
import ifcopenshell.geom
import ifcopenshell.util.shape
import multiprocessing
import pandas as pd
import time
import psutil

settings = ifcopenshell.geom.settings()
settings.set(settings.APPLY_DEFAULT_MATERIALS, True)
columns = [ "Faces", "Edges", "Verts"]

def run(filePath):
    before = time.time()
    
    # open IFC
    file = ifcopenshell.open(filePath)
    
    iterator = ifcopenshell.geom.iterator(settings, file, multiprocessing.cpu_count())
    geometry_length = 0
    
    if iterator.initialize():
        while True:
            shape = iterator.get();
            geometry_length+=1;
            if not iterator.next():
                break
                
    print(geometry_length)
    
    print(f'CPU count: {multiprocessing.cpu_count()}')
    
    print(f'Time: {time.time() - before}s')

print(f"IfcOpenShell version: {ifcopenshell.version}")

cpu_freq = psutil.cpu_freq()
cpu_count = psutil.cpu_count(logical=False)
cpu_logical_count = psutil.cpu_count()

print(f"CPU Frequency: {cpu_freq.current:.2f} MHz")
print(f"Number of CPU Cores: {cpu_count} (Physical)")
print(f"Number of Logical Cores: {cpu_logical_count} (Logical)")

mem = psutil.virtual_memory()
print(f"Total Memory: {mem.total / (1024 ** 3):.2f} GB")
print(f"Available Memory: {mem.available / (1024 ** 3):.2f} GB")

run("./CenterConference.ifc")
```
And here is result 
```
IfcOpenShell version: 0.8.0
CPU Frequency: 1200.00 MHz
Number of CPU Cores: 16 (Physical)
Number of Logical Cores: 32 (Logical)
Total Memory: 95.97 GB
Available Memory: 72.41 GB
6830
CPU count: 32
Time: 50.75439810752869s
```
Did i make something wrong?Many thank

**Comment by Moult** [comment]
You need to use the latest build here: https://github.com/IfcOpenBot/IfcOpenShell/commit/7692b910f4b24997177501f41299318857af4c19#commitcomment-147147583 and also specify the geometry library:

```python
iterator = ifcopenshell.geom.iterator(settings, file, multiprocessing.cpu_count(), geometry_library="hybrid-cgal-simple-opencascade")
```

**Comment by RyugaRyuzaki** [comment]
> You need to use the latest build here: [IfcOpenBot@7692b91#commitcomment-147147583](https://github.com/IfcOpenBot/IfcOpenShell/commit/7692b910f4b24997177501f41299318857af4c19#commitcomment-147147583) and also specify the geometry library:
> 
> ```python
> iterator = ifcopenshell.geom.iterator(settings, file, multiprocessing.cpu_count(), geometry_library="hybrid-cgal-simple-opencascade")
> ```
> 
> Also in 0.8 you can remove `settings.set(settings.APPLY_DEFAULT_MATERIALS, True)`

Cool with
```
 iterator = ifcopenshell.geom.iterator(settings, file, multiprocessing.cpu_count(),geometry_library="hybrid-cgal-simple-opencascade")
```
it faster than 2.5 time, here is result
```
IfcOpenShell version: 0.8.0
CPU Frequency: 1200.00 MHz
Number of CPU Cores: 16 (Physical)
Number of Logical Cores: 32 (Logical)
Total Memory: 95.97 GB
Available Memory: 72.60 GB
6830
CPU count: 32
Time: 18.488686323165894s
```
But can you please tell me how to install latest build without pip?Many thank also!

**Comment by Moult** [comment]
A manual installation is basically this: https://docs.ifcopenshell.org/ifcopenshell-python/installation.html#zip-packages - but instead of downloading the latest stable zip, you can download the zip from IfcOpenBot.

We release to pip every ~2 months, so in a month it'll be updated.

Can you help rerun your script with a time check after the open() function and after the initialize() function? That would help see where the bottleneck is.

**Comment by RyugaRyuzaki** [comment]
> A manual installation is basically this: https://docs.ifcopenshell.org/ifcopenshell-python/installation.html#zip-packages - but instead of downloading the latest stable zip, you can download the zip from IfcOpenBot.
> 
> We release to pip every ~2 months, so in a month it'll be updated.
> 
> Can you help rerun your script with a time check after the open() function and after the initialize() function? That would help see where the bottleneck is.
> 
> I'm still surprised at how slow it is for you. You seem to have a monster of a machine with lots of CPU cores and RAM yet my (supposedly much weaker) machine is still 10x faster than you?

Hi here is "the time after open" :
```
import ifcopenshell
import ifcopenshell.geom
import ifcopenshell.util.shape
import multiprocessing
import pandas as pd
import time
import psutil


tree = ifcopenshell.geom.tree()
settings = ifcopenshell.geom.settings()
columns = [ "Faces", "Edges", "Verts"]

def run(filePath):
    before = time.time()
    
    # open IFC
    file = ifcopenshell.open(filePath)
    
    print(f'Time after open: {time.time() - before}s')
    
    iterator = ifcopenshell.geom.iterator(settings, file, multiprocessing.cpu_count(),geometry_library="hybrid-cgal-simple-opencascade")
    geometry_length = 0
    
    if iterator.initialize():
        while True:
            geometry_length+=1;
            if not iterator.next():
                break
                
    print(geometry_length)
    
    print(f'CPU count: {multiprocessing.cpu_count()}')
    
    print(f'Time: {time.time() - before}s')

print(f"IfcOpenShell version: {ifcopenshell.version}")

cpu_freq = psutil.cpu_freq()
cpu_count = psutil.cpu_count(logical=False)
cpu_logical_count = psutil.cpu_count()

print(f"CPU Frequency: {cpu_freq.current:.2f} MHz")
print(f"Number of CPU Cores: {cpu_count} (Physical)")
print(f"Number of Logical Cores: {cpu_logical_count} (Logical)")

mem = psutil.virtual_memory()
print(f"Total Memory: {mem.total / (1024 ** 3):.2f} GB")
print(f"Available Memory: {mem.available / (1024 ** 3):.2f} GB")

run("./CenterConference.ifc")
```
And result 
```
IfcOpenShell version: 0.8.0
CPU Frequency: 1200.00 MHz
Number of CPU Cores: 16 (Physical)
Number of Logical Cores: 32 (Logical)
Total Memory: 95.97 GB
Available Memory: 72.07 GB
Time after open: 12.872642755508423s
6830
CPU count: 32
Time: 19.975434064865112s
```
As you can see my CPU has 1.2Ghz

**Comment by Moult** [comment]
Here are my results. 12.8 seconds just for opening vs 2.28s on my machine sounds like a big difference. It's only 68MB. Thoughts @aothms ?

```
IfcOpenShell version: 0.0.0
CPU Frequency: 2057.82 MHz
Number of CPU Cores: 6 (Physical)
Number of Logical Cores: 12 (Logical)
Total Memory: 30.50 GB
Available Memory: 16.73 GB
Time after open: 2.2841579914093018s
6830
CPU count: 12
Time: 4.740019798278809s
```

**Comment by RyugaRyuzaki** [comment]
Btw so this 
```
  shape = iterator.get()
  matrix = shape.transformation.matrix.data
  faces = shape.geometry.faces
  edges = shape.geometry.edges
  verts = shape.geometry.verts
  materials = shape.geometry.materials
  material_ids = shape.geometry.material_ids
```
will those deprecated ?

**Comment by Moult** [comment]
That's all still there.

**Comment by Moult** [comment]
@RyugaRyuzaki can you confirm you are using this build https://github.com/IfcOpenBot/IfcOpenShell/commit/7692b910f4b24997177501f41299318857af4c19#commitcomment-147147583 ? It looks suspicious that your output says `IfcOpenShell version: 0.8.0` where it should say version 0.0.0.

**Comment by RyugaRyuzaki** [comment]
> @RyugaRyuzaki can you confirm you are using this build [IfcOpenBot@7692b91#commitcomment-147147583](https://github.com/IfcOpenBot/IfcOpenShell/commit/7692b910f4b24997177501f41299318857af4c19#commitcomment-147147583) ? It looks suspicious that your output says `IfcOpenShell version: 0.8.0` where it should say version 0.0.0.

Hi here is full test for web-ifc@0.058 and IfcOpenShell version: 0.8.1-alpha240925;
1- IfcOpenShell version: 0.8.1-alpha240925:
```
IfcOpenShell version: 0.8.1-alpha240925
CPU Frequency: 1200.00 MHz
Number of CPU Cores: 16 (Physical)
Number of Logical Cores: 32 (Logical)
Total Memory: 95.97 GB
Available Memory: 78.59 GB
Time after open: 11.148876190185547s
Total geometries: 6830
CPU count: 32
Time: 18.445350646972656s
```
2 web-ifc@0.0.58:
```
CPU Model: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Number of CPU Cores: 32 (Physical)
Total Memory: 95.97 GB
Available Memory: 77.64 GB
Time after open: 0.10
Geometries Length:16073
Time :6.5610691999999995s
```

**Comment by Moult** [comment]
I just tested on another very old Windows machine (apart from the beefy RAM, it's not a powerful machine):

```
IfcOpenShell version: 0.8.1-alpha240925
CPU Frequency: 3000.00 MHz
Number of CPU Cores: 4 (Physical)
Number of Logical Cores: 8 (Logical)
Total Memory: 63.88 GB
Available Memory: 49.81 GB
Time after open: 3.7867109775543213s
6830
CPU count: 8
Time: 13.633314371109009s
```

How are you running Python @RyugaRyuzaki ? Is it some Visual Studio plugin or something? Can you try running it in the Blender script editor? or better yet run it as a vanilla system Python?

**Comment by RyugaRyuzaki** [comment]
> I just tested on another very old Windows machine (apart from the beefy RAM, it's not a powerful machine):
> 
> ```
> IfcOpenShell version: 0.8.1-alpha240925
> CPU Frequency: 3000.00 MHz
> Number of CPU Cores: 4 (Physical)
> Number of Logical Cores: 8 (Logical)
> Total Memory: 63.88 GB
> Available Memory: 49.81 GB
> Time after open: 3.7867109775543213s
> 6830
> CPU count: 8
> Time: 13.633314371109009s
> ```
> 
> How are you running Python @RyugaRyuzaki ? Is it some Visual Studio plugin or something? Can you try running it in the Blender script editor? or better yet run it as a vanilla system Python?
> 
> Is it a drive issue? What happens if Python, the script, and the IFC is all on the C drive in a regular folder?

I ran in Visual Studio plugin. I downloaded bonsai-0.8.1-alpha240925 , i created env, then install ifcopenshell-0.8.1-alpha240925.whl, then create a script likes a wrote upper named run.py.I placed my file in root directory. I installed python 11 on C://.. , my workspace on E://....  After all i :
```
python run.py
``` 
From my blenderBIM as issue with socket in VScode, i can not run in blender anymore.

**Comment by Moult** [comment]
@RyugaRyuzaki can you try run it as a plain system Python or just in Blender itself (no VSCode involved)? This will help rule out any funny quirks with running Python with debugging or whatever else VSCode might do.

**Comment by Moult** [comment]
For the record, numbers from @Andrej730 on Windows.

```
Time after open: 3.0738027095794678s
6830
CPU count: 20
Time: 6.768131256103516s
```

Again similar to my numbers and significantly different to yours oddly enough.

**Comment by Moult** [comment]
OK after a call it seems things take twice as long when run from VS Code. However when it comes to geometry processing, from the small tests we did it seems IfcOpenShell is roughly the same as web-ifc (ifcopenshell was ~10% faster) but no more drastic difference in numbers.

There is still a drastic difference in file open, but that's discussed in #5026.
