### ISSUE TITLE
Some issues with the Type Manager

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3930]
I tried many different ways to make a type out of this, and no matter what I do, when I add this element to the model it becomes 1000 times larger.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/4e12a8c8-e54c-485b-9f17-6e5eba779571)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/8bb59043-24e5-4e3d-85ad-2ed8be563331)

Another annoying small thing is that when I write the name of a type, even if the cursor shows that I am typing if I click on save it will save, and most of the time I click 2 times because I think the cursor is still only active for the text field. I don't think this is usual, because if you want to click ANY other place outside that box interface you cannot do it. I think it would be cool at least to change the coursor from I back to the click to be aware of this.

![2023-10-24_10-24-58](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/1f176356-0a48-432f-a0ae-772ad5c441fc)

**Comment by Andrej730** [comment]
> I tried many different ways to make a type out of this, and no matter what I do, when I add this element to the model it becomes 1000 times larger.

it very much depends on the object's geometry. can you share an example?

> Another annoying small thing is that when I write the name of a type, even if the cursor shows that I am typing if I click on save it will save, and most of the time I click 2 times because I think the cursor is still only active for the text field. I don't think this is usual, because if you want to click ANY other place outside that box interface you cannot do it. I think it would be cool at least to change the coursor from I back to the click to be aware of this.

I think it's general Blender UI issue, reported it to [Blender](https://projects.blender.org/blender/blender/issues/114311), you can subscribe to it there.
