### ISSUE TITLE
Slow to find all objects inside or near an object

### ISSUE THREAD

**Issue by Amoki** [IfcOpenShell/IfcOpenShell#3938]
I'm trying to fetch all objects "near" an object.
For example, all objects inside an IfcSpace and walls on its sides, or find spaces and slabs touching a wall.

I'm using `geom.tree()` and the `select()` method but if I add an `extend` parameter to find close objects, the process time is multiplied (from milliseconds to seconds per object). 

 ```python
 if ifc_object.is_a("IfcProduct"):
    nearby_instances = [
        i.GlobalId for i in ifcwrap_bvh.select(ifc_object, extend=1.1)
    ]
 ```
Is this the right way to do it or am I in the wrong direction?

**Comment by aothms** [comment]
I guess it depends on the model. Extending by 1.1m I guess could make the number of objects to consider go up exponentially. If ifc_object is complex (which means computing distances from it takes some time). Regardless of that I think "seconds per object" is definitely on the slow side. Would be good to have a model + guid so that I can run it in the profiler.

**Comment by Amoki** [comment]
```python
import ifcopenshell
from ifcopenshell import geom
import multiprocessing

from ifcopenshell.util.selector import Selector


selector = Selector()

ifc_file = ifcopenshell.open("MarcAntoinePetit.ifc")


# Construct BVH with ifcopenshell.geom()
bvh_tree = geom.tree()
settings = geom.settings()
exclude_elements = selector.parse(ifc_file, ".IfcSpace | .IfcOpeningElement")

iterator = geom.iterator(
    settings,
    ifc_file,
    multiprocessing.cpu_count(),
    exclude=exclude_elements,
)

if iterator.initialize():
    while True:
        bvh_tree.add_element(iterator.get_native())
        if not iterator.next():
            break

# Retrieving nearby Ifc instances
nearby_instances = {}
for ifc_product in ifc_file.by_type("IfcProduct"):
    nearby_instances[ifc_product.GlobalId] = [
        i.GlobalId for i in bvh_tree.select(ifc_product)  # , extend=0.1)
    ]
```
[MarcAntoinePetit.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13189768/MarcAntoinePetit.zip)

Without `extend`: 164 sec (95% of the time is on `bvh_tree.select(ifc_product)`)
With `extend=0.1`: I gave up after 1 hour

With only the first 500 products:

```python
nearby_instances = {}
for ifc_product in ifc_file.by_type("IfcProduct"):
    if len(nearby_instances) > 500:
        break
    nearby_instances[ifc_product.GlobalId] = [
        i.GlobalId for i in bvh_tree.select(ifc_product)
    ]
```
Without `extend`: 29 sec
With `extend=0.1`: 1434 sec

Some objects are way slower than others.
```
1T2hYTZj1EsBZaf4hQmbLI (IfcWallStandardCase)
3RLTfSMBXE_BWgA7Wbvfa1 (IfcSlab)
0dWoULYUH3zPg8qJpTnRTP (IfcWallStandardCase)
0dWoULYUH3zPg8qJtTnRTP (IfcWallStandardCase)
3SsBdsN_n49RzlgartcT0T (IfcBuildingElementProxy)
```
take more than 60 seconds each with `extend`

The slowest is the IfcBuildingElementProxy `3SsBdsN_n49RzlgartcT0T` (it's always them)
It takes 0.005 sec without `extend` and 90.207 sec with `extend`.

**Comment by Moult** [comment]
This is now fixed with the new clash detection features. The clearance clash is also much, much faster.
