### ISSUE TITLE
Error on importing ifc in REVIT on property set label length

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3939]
So I don't know if this has ever been brought up, and I don't find it particularly bothersome but I've had a bunch of "recoverable" errors spewn out when importing an ifc on Revit, after investigating the log it seems the property sets for railings contains too many characters for Revit.

eg

```
/*  13284 */ #75359=IFCPROPERTYSINGLEVALUE('Data',$,IFCLABEL('{"railing_type": "FRAMELESS_PANEL", "height": 0.3059999942779541, "thickness": 0.019999999552965164, "spacing": 0.0, "path_data": {"edges": [[0, 1], [1, 2]], "verts": [[-1.9964238405227661, -2.5877671241760254, -2.6829349994659424], [-1.9964238405227661, 0.09222077578306198, 0.0], [-1.9964238405227661, 0.6320043206214905, 0.0]]}}'
*** Error in column number: 381 ***
*** Recoverable Error: 
Failure during storing attribute: Length of string exceeds defined maximum string length. *** on line 13284.
```

Is it worth investigating or is it a revit problem ?

Cheers

**Comment by Andrej730** [comment]
Didn't know that IfcLabel is actually limited to 255 symbols.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/46a74dcd-2745-48c3-920f-3a7b52286be5)

But shouldn't IFC validation raise an error in this case? Tested on this file [railing.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13201184/railing.ifc.txt), validation runs without errors though there is IfcLabel 870 symbols long.

@aothms can you please take a look?
