### ISSUE TITLE
Ability to copy / paste an IFC Array

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#3940]
Similar to the vanilla Blender modifier it would be nice ot be able to "copy" the properties of an array modifier to another object 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/f373686e-697b-41b8-b148-a13d23bbc02e)

**Comment by theoryshaw** [comment]
+1
related: https://github.com/IfcOpenShell/IfcOpenShell/issues/3802

**Comment by theoryshaw** [comment]
took a stab: https://github.com/IfcOpenShell/IfcOpenShell/pull/4743
