### ISSUE TITLE
Error on geometry iterator

### ISSUE THREAD

**Issue by Bright-Brave** [IfcOpenShell/IfcOpenShell#3942]
Hi, all
I use ifcopenshell iterator to get geometry data from ifc. All files are fine except [this one](https://github.com/IfcOpenShell/IfcOpenShell/files/13176418/multiple-mapped-shape-with-transformation.txt), which miss one shape item.
After debug, I find that it is related to the setting of `USE_WORLD_COORDS`. The issue happens when this setting was true. You can reproduct this using following code.

```python
import ifcopenshell
import ifcopenshell.geom

ifc_file = ifcopenshell.open("multiple-mapped-shape-with-transformation.ifc")

settings = ifcopenshell.geom.settings()
settings.set(settings.USE_WORLD_COORDS, True)

iterator = ifcopenshell.geom.iterator(settings, ifc_file)
if iterator.initialize():
    while True:
        shape = iterator.get()
        if not iterator.next():
            break
```

**Comment by Andrej730** [comment]
What shape item does it miss?

**Comment by Bright-Brave** [comment]
Thanks for your concern.
It is the shape of `IfcBuildingElementProxy` named `P-0`, and its guid is `1kTvXnbbzCWw8lcMd1dR2o`.

**Comment by Bright-Brave** [comment]
BTW, `create_shape` works well.
```python
settings = ifcopenshell.geom.settings()
settings.set(settings.USE_WORLD_COORDS, True)
entity = ifc_file.by_guid('1kTvXnbbzCWw8lcMd1dR2o')
shape = ifcopenshell.geom.create_shape(settings,entity)
```

**Comment by Moult** [comment]
The file is invalid.

```
2023-10-27:13:57:18,974 ERROR   [rule_executor.py:250] On instance:
    #5100=IfcShapeRepresentation(#202,'Body','SweptSolid',(#5021))
Rule IfcShapeModel.WR11:
    (sizeof(self.OfProductRepresentation) == 1) ^ (sizeof(self.RepresentationMap) == 1) ^ (sizeof(ofshapeaspect) == 1)
Violated by:
    ((1 == 1 ^ 1 == 1) ^ 0 == 1)
     +  where 1 = sizeof((#1029=IfcProductDefinitionShape($,$,(#5100)),))
     +    where (#1029=IfcProductDefinitionShape($,$,(#5100)),) = #5100=IfcShapeRepresentation(#202,'Body','SweptSolid',(#5021)).OfProductRepresentation
     +  and   1 = sizeof((#5010=IfcRepresentationMap(#5011,#5100),))
     +    where (#5010=IfcRepresentationMap(#5011,#5100),) = #5100=IfcShapeRepresentation(#202,'Body','SweptSolid',(#5021)).RepresentationMap
     +  and   0 = sizeof(())
```

If you fix this validation error the shape will be processed:

```
#1029= IFCPRODUCTDEFINITIONSHAPE($,$,(#51001));
#51001= IFCSHAPEREPRESENTATION(#202,'Body','SweptSolid',(#5021));
```

**Comment by Bright-Brave** [comment]
Thanks, @Moult .
But, [the rule](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcShapeModel.htm) is not corresponding with the formula for validation.
```
(SIZEOF(SELF\IfcRepresentation.OfProductRepresentation) = 1) XOR 
(SIZEOF(SELF\IfcRepresentation.RepresentationMap) = 1) XOR
(SIZEOF(OfShapeAspect) = 1)
```

Shouldn't it be `(1 == 1) ^ (1 == 1) ^ (0 == 1)` instead of `((1 == 1 ^ 1 == 1) ^ 0 == 1)`?

And `(1 == 1) ^ (1 == 1) ^ (0 == 1)`  returns true.

**Comment by Andrej730** [comment]
> Shouldn't it be `(1 == 1) ^ (1 == 1) ^ (0 == 1)` instead of `((1 == 1 ^ 1 == 1) ^ 0 == 1)`?

@Bright-Brave Isn't the same thing that returns false? 
`(1 == 1) ^ (1 == 1) ^ (0 == 1)` => `1 ^ 1 ^ 0` => `0 ^ 0` => `0`

**Comment by Bright-Brave** [comment]
@Andrej730 chartgpt says it was true.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/35648311/9e3dcf2d-544c-4fd6-9fb3-9447fb768834)

**Comment by Bright-Brave** [comment]
@Andrej730 Forgive my ignorance. I misunderstand the XOR calculation of three items.
Thanks again.

**Comment by Bright-Brave** [comment]
@Moult @Andrej730 Sorry for bothering you again.
In order to avoid raising an invalid issue like this, I also would like to validate the file before questioning, and I find this code in the api documentation, but I got nothing from `json_logger.statements` when validating this wrong file.
```python
import ifcopenshell
import ifcopenshell.validate

ifc_file = ifcopenshell.open("multiple-mapped-shape-with-transformation.ifc")
json_logger = ifcopenshell.validate.json_logger()
ifcopenshell.validate.validate(ifc_file, json_logger)
print(json_logger.statements)
```

**Comment by Andrej730** [comment]
@Bright-Brave 
```python
ifcopenshell.validate.validate(ifc_file, json_logger, express_rules=True)
```
