### ISSUE TITLE
IfcTester - PartOf facet is working incorrectly

### ISSUE THREAD

**Issue by MennoMekes** [IfcOpenShell/IfcOpenShell#3948]
Hi,

I've made an IDS to check wether or not an element is poart of an IfcSystem. This can be done with PartOf, IFCRELASSIGNSTOGROUP.
This works in an older version, 0.0.230602.

From the offical release v0.0.230902 on it stopped working, the relationship is checked with en IfcWall instead of IfcSystem.
This is also the case for the latest build 0.0.231028

screenshots and the IDS are in the doc:
[PartOf issue.docx](https://github.com/IfcOpenShell/IfcOpenShell/files/13195100/PartOf.issue.docx)

Thanks!

**Comment by BIMvoice** [comment]
@Moult or @Andrej730 can you do anything about this please?

**Comment by BIMvoice** [comment]
Thank you very much @Moult!

**Comment by MennoMekes** [comment]
Thanks @Moult! it works just like before.
