### ISSUE TITLE
Error copying grids

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3949]
Error copying grids

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/37902e32-0d97-48b4-b0df-adb7f6803258

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 719, in execute
    return OverrideDuplicateMove.execute_duplicate_operator(self, context, linked=False)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 730, in execute_duplicate_operator
    context.view_layer.objects.active = self.new_active_obj
ReferenceError: StructRNA of type Object has been removed

```

**Comment by theoryshaw** [comment]
Ping @Andrej730 
I think it was introduced at 6887210a1a4305a62ef98b86f22eea37229b4fc4

**Comment by Owuraqu** [comment]
> Error copying grids
> ...
> 
> ReferenceError: StructRNA of type Object has been removed
I am still not able to duplicate the IfcGridAxis. 

Thank you.

**Comment by theoryshaw** [comment]
Are you getting an error, or you just can't duplicate? 

If you can't duplicate, they might be locked.

**Comment by Owuraqu** [comment]
> Are you getting an error, or you just can't duplicate? 

Now I an duplicate after updating to the new version, however when I duplicate (both the axes and it's annotation) and activate the floor plan one of the axes don't come with a Grid annotation. How do I associate an annotation to an axes?

**Comment by theoryshaw** [comment]
Only duplicate the axes, not the grid annotation.  The grid annotation is automatic.  That is, if you duplicate the axes, and then refresh the drawing, the grid annotation should show up.
