### ISSUE TITLE
Segfault on beams (example files)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#395]
**Steps to reproduce:**

1. Convert any of the following files with fd821d08cddeed253ea50672fce588d4942855aa (OCCT v7.2.0):
• https://github.com/IfcOpenShell/files/blob/master/395--beam--segfault--1.ifc
• https://github.com/IfcOpenShell/files/blob/master/395--beam--segfault--2.ifc
• https://github.com/IfcOpenShell/files/blob/master/395--beam--segfault--3.ifc

2. Experience segfault: 
```FATAL: An error occured, status code 139.```
3. Files open without warning in Solibri, DDS and SimpleBIM:
<img height="150" alt="screen shot 2018-05-31 at 13 17 52" src="https://user-images.githubusercontent.com/4601554/40779894-eee30454-64d6-11e8-918f-ac77267fea0c.png"> <img height="150" alt="screen shot 2018-05-31 at 13 18 59" src="https://user-images.githubusercontent.com/4601554/40779905-f813e886-64d6-11e8-97a9-c20670097ebb.png"> <img height="150" alt="screen shot 2018-05-31 at 13 18 35" src="https://user-images.githubusercontent.com/4601554/40779914-ffd6cae8-64d6-11e8-8d9f-cfc0baf4190b.png">

**Comment by aothms** [comment]
Same as #444
