### ISSUE TITLE
`material.item.0.Name` selector doesn't return anything

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3951]
it seems `material.item.0.Name` as outlined in the [docs](https://blenderbim.org/docs-python/ifcopenshell-python/selector_syntax.html#getting-element-values "docs"), doesn't return anything.

see:
https://community.osarch.org/discussion/comment/17975/#Comment_17975

**Comment by mdjska** [comment]
@theoryshaw are you after `material.item.Name.0`like outlined here https://wiki.osarch.org/index.php?title=BlenderBIM_Add-on/BlenderBIM_IFCCSV? This will give you the name of the first material item (single material, layer or constituent)

**Comment by theoryshaw** [comment]
`material.item.Name.0` only seems to work with IfcMaterial assignments. 

If you're trying to pull a name out of a IfcMaterialLayer, i think it's...
`material.item.Material.Name.0`

**Comment by mdjska** [comment]
No `material.item.Name.0` works for all types of materials, the difference is that `material.item.Name` gets the name of the material layer/constituent/profile itself and `material.item.Material.Name` gets the name of the associated material. `material.item.Name.0` is the same as `material.MaterialLayers.Name.0`, it just works for all material types. 

| class   | Name                        | material.item.Name                   | material.item.Name.0 | material.item.Material.Name | material.item.Material.Name.0 | material.MaterialLayers.Name         | material.MaterialLayers.Name.0 |
| ------- | --------------------------- | ------------------------------------ | -------------------- | --------------------------- | ----------------------------- | ------------------------------------ | ------------------------------ |
| IfcWall | Wall_w_constituent_material | ['Constituent1', 'Constituent2']     | Constituent1         | ['Material1', 'Material2']  | Material1                     | N/A                                  | N/A                            |
| IfcWall | Wall_w_single_material      | Material1                            | Material1            | N/A                         | N/A                           | N/A                                  | N/A                            |
| IfcWall | Wall_w_profile_material     | ['Profile1', 'Profile2']             | Profile1             | ['Material1', 'Material2']  | Material1                     | N/A                                  | N/A                            |
| IfcWall | Wall_w_layered_material     | ['MaterialLayer1', 'MaterialLayer2'] | MaterialLayer1       | ['Material1', 'Material2']  | Material1                     | ['MaterialLayer1', 'MaterialLayer2'] | MaterialLayer1                 |

**Comment by theoryshaw** [comment]
>material.item.Name.0 only seems to work with IfcMaterial assignments.

whoops sorry, when i wrote `material.item.Name.0`, I meant. `material.item.0.Name`

**Comment by Moult** [comment]
`mats.Name` :)
