### ISSUE TITLE
Split for 'cad line', as well. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3956]
similar to #3941 and #3804, would be nice to have a split for 'cad line', as well. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/e93068e3-b725-4e30-8f6d-c6fe9fcdbaff)

**Comment by SavuGust27** [comment]
Is it not alredy posible with the rip region tool in blender? i guess you could just subdivide and rip region

**Comment by theoryshaw** [comment]
This is true, thanks. 
Closing.
