### ISSUE TITLE
bug with seperate selection (p command in edit mode). Breaks the sheet files generator aswell.

### ISSUE THREAD

**Issue by chopinregis** [IfcOpenShell/IfcOpenShell#3963]
There is a bug that appears when you edit an ifcvirtualelement. When you duplicate a face and seperate the selection with p command it creates a bug. This bug also seems to affect the sheet generation. See video for more details

Project link
https://hub.openingdesign.com/OpeningDesign/Monica_Residence/src/commit/1bac436dc1c526b73d2c2c2d57886e0462dcd1e3/Models/BlenderBIM

https://github.com/IfcOpenShell/IfcOpenShell/assets/13260872/93d9ac5f-ef33-4cd5-8781-6065791e92c0

**Comment by Moult** [comment]
You should not use the built-in P separate operator, you should instead use the Mesh > IFC Separate equivalent. Note this only works on meshes.

**Comment by theoryshaw** [comment]
seems that this error should be handled, still though. that is not allowing the user to do it.

**Comment by chopinregis** [comment]
> You should not use the built-in P separate operator, you should instead use the Mesh > IFC Separate equivalent. Note this only works on meshes.

I used the IFC Separate and this is the error I got.

![Snipaste_2023-11-01_09-38-04](https://github.com/IfcOpenShell/IfcOpenShell/assets/13260872/002b3318-41f3-4080-8d24-a23bc1093f87)

**Comment by Moult** [comment]
We can't remove native Blender functionality but we can override common hotkeys, so now the P is overridden to show both Blender and IFC options.

That second error looks as though you're trying to run the IFC separate on a non-IFC element (i.e. regular Blender object). I've adjusted the operator to ignore those situations.
