### ISSUE TITLE
If a user chooses `USERDEFINED` as the PredefinedType, should another field show itself where they can enter the value?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3965]
I might be missing something, but if a user chooses `USERDEFINED` as the PredefinedType, should another field show itself where they can enter the value?

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/38dcaaac-a303-4964-8d49-2ba085ee8fcd

**Comment by Moult** [comment]
The "ElementType" field is where you should enter in a value if you select USERDEFINED.
