### ISSUE TITLE
IfcConvert --use-element-hierarchy: IfcProject node missing, --use-element-names/guids ignored for IfcSite, IfcBuilding, and IfcBuildingStorey

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#397]
`IfcConvert.exe Duplex_A_20110907.ifc dup-hierachy.dae --sew-shells --use-material-names --use-element-guids --use-element-hierarchy`:
![image](https://user-images.githubusercontent.com/227876/41019537-b833d15a-6967-11e8-916b-c02b97a26467.png)
`product-7b7032cc-b822-417b-9aea-642906a29bd7` is the IfcSite so IfcProject appears to be is missing.

I can probably look into this soon.

**Comment by aothms** [comment]
Are you sure this is not the result of the tool you used for importing. If I look at the XML output in a text editor, I do get some reference to a project node.

~~~xml
    <visual_scene id="IfcOpenShell">
      <node id="project" name="project" type="NODE">
        <matrix>1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1</matrix>
        <node id="product-7b7032cc-b822-417b-9aea-642906a29bd7" name="product-7b7032cc-b822-417b-9aea-642906a29bd7" type="NODE">
          <matrix>1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1</matrix>
          <node id="product-7b7032cc-b822-417b-9aea-642906a29bd4" name="product-7b7032cc-b822-417b-9aea-642906a29bd4" type="NODE">
~~~

Would be nice though, if it would carry over the original IfcProject name:

~~~lua
#23515=IFCPROJECT('1xS3BCk291UvhgP2a6eflL',#1,'0001',$,$,'Duplex Apartment','Project Status',(#3,#5137),#24098);
~~~

That's probably due to this code: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomElement.h#L141

Adding one higher level root node to encapsulate the project is also fine of course if it helps importing tools to preserve the metadata.

**Comment by Stinkfist0** [comment]
![image](https://user-images.githubusercontent.com/227876/41097484-c800aec4-6a60-11e8-95c6-0bf403a01c89.png)

I ended up removing the rather arbitrary "append names to types for element with children" logic - @https://github.com/Skyndia does this look OK for you?

**Comment by Stinkfist0** [comment]
Yup, adding a dummy root node, will make the project node appear.

**Comment by Stinkfist0** [comment]
I did a quick test on an Open Asset Importer based solution (Urho3D) and it could create the hierarchy properly (though it failed to create some meshes, but didn't have really the time to look into that) without dummy node.

**Comment by Stinkfist0** [comment]
@aothms @Skyndia seems not to respond, what's your opinion on ^^^.

**Comment by aothms** [comment]
@Stinkfist0 thanks for picking this up. Is there a reason why you don't move `differentiateSlabTypes()` to `GeometrySerializer` as well? (and the type prefix logic as well perhaps?).

**Comment by Stinkfist0** [comment]
If wanted, I can do that. However, I'm not really a fan of this option as the IDs are not even remotely unique - would e.g. a typical SVG or OBJ importer handle non-unique IDs ok? Unity manages to handle these OK (it appends a running number to the name/ID when it encounters a duplicate ID) but e.g. this VS Code 3D Viewer extension I tried fails to open models that use `--use-element-hierachy`.

**Comment by aothms** [comment]
Ah I see, I didn't consider that. Ideally this would all be replaced by a gnu find `printf` or `docker --format`. I'll add an issue for that and then we just move on with this issue as proposed by you.

**Comment by Stinkfist0** [comment]
Yeah. Somewhat related: https://github.com/Stinkfist0/IfcOpenShell/commit/26c0af9c33509cf5bf17aa917b1cebfbccda9b37 I made this almost a year ago but forgot about it... I think I got "scared" by the heavy refactoring of 0.6.0 and though this kind of stuff would be better done after it.

**Comment by aothms** [comment]
> I think I "got scared" by the heavy refactoring of 0.6.0

I can imagine. I still need to bring back the filtering there anyways. I rushed 0.6 out to get the python version going as there the multiple schemas are most painful (and unnecessary as it's dynamically typed language).

> E.g. --use-element-names could be --name-elements IfcRoot.Name and --use-element-guids could be --name-elements IfcRoot.GlobalId.

That sounds great. With a format string you can keep this prefixing with type if that's somehow useful. I'll work on this at some point keeping your commit in mind. Thanks!

**Comment by Stinkfist0** [comment]
I'll provide a PR for this now. I'll leave the dummy node required by Unity out of the scope. Perhaps we can document in under known issues at wiki or something.
