### ISSUE TITLE
BlenderBIM Aggregates with representations

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#3973]
It seems that IFC allows an element that aggregates other elements to have its own representations, eg. "[In some cases it may be useful to also expose an own explicit representation of the aggregate.](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcproductextension/lexical/ifcelementassembly.htm)".

..but BlenderBIM won't let me aggregate an element to another element that already has a representation (though it is happy doing this with spatial elements).

If I delete the `if relating_obj.data: return false` [section here](https://github.com/IfcOpenShell/IfcOpenShell/blob/8cd9fb901535da65e0c763edca32b6798cd98e00/src/blenderbim/blenderbim/tool/aggregate.py#L32), BlenderBIM lets me create an aggregate with a representation, the file validates, it re-opens ok in BlenderBIM, and I can edit/remove the aggregations without anything breaking.

**Comment by Moult** [comment]
Huh, wow. I missed that detail. There seems to be contradicting evidence. Posted here: https://github.com/buildingSMART/IFC4.3.x-development/issues/721
