### ISSUE TITLE
Assistance Required for Extracting Data from IFC Files Exported with Different Versions of Revit's IFC Exporter

### ISSUE THREAD

**Issue by santiagoayerbe** [IfcOpenShell/IfcOpenShell#3978]
Hi Everyone!

I'm working on a Python script that utilizes ifcopenshell to extract information from IFC files and then export this data to Excel files. The goal is to process all the IFC files within a given directory and create an Excel sheet for each that includes parameters associated with desired IFC entities.

I am encountering inconsistent behavior depending on the version of Revit's IFC Exporter used to generate the IFC files. When exporting files with version 22.1 of Revit's IFC Exporter, the script functions as expected, but using version 22.6, I face an altered data structure that my current script cannot handle properly.

Specifically, some key properties and parameters are not being extracted or are structured differently in the files generated with the newer version. The properties in question include, but are not limited to, COBie properties and custom NEOM parameters like NEOM_Operations_Class, NEOM_BOQ_Cost_Code, NEOM_Target_LOD, and NEOM_Clash_Test_Code.

Here is a snippet of the script responsible for property extraction:

```python
import ifcopenshell
import os
from openpyxl import Workbook

desired_ifc_types = desired_types = [
        "IfcBuilding","IfcFlowTerminal", "IfcDistributionControlElement", 
        "IfcElementAssembly", "IfcBeam", "IfcFlowFitting", 
        "IfcFlowSegment", "IfcEnergyConversionDevice", 
        "IfcColumn", "IfcCovering", "IfcCurtainWall", 
        "IfcDoor", "IfcFlowMovingDevice", 
        "IfcFlowController", "IfcFooting", 
        "IfcFurnishingElement", "IfcBuildingElementProxy", 
        "IfcPlate", "IfcSlab", "IfcSpace", 
        "IfcStair", "IfcStairFlight", "IfcWallStandardCase", "IfcOpeningElement"
    ]

desired_parameters = [
    "Omniclass_Entities_by_Form_Number", "Omniclass_Entities_by_Form_Title",
    "Omniclass_Entities_by_Function_Number", "Omniclass_Entities_by_Function_Title",
    "Ifc_Entity", "Ifc_Enumeration", "Uniclass_2015_Pr_Code", "Uniclass_2015_Pr_Title",
    "Uniclass_2015_Ss_Code", "Uniclass_2015_Ss_Title", "Uniclass_2015_SL_Code", "Uniclass_2015_SL_Title",
    "COBie.Facility.Name", "COBie.Facility.Description", "COBie.Floor.Name", "COBie.Floor.Description",
    "COBie.Space.Name", "COBie.Space.Description", "COBie.Type.Name", "COBie.Type.Description",
    "COBie.Type.NominalLength", "COBie.Type.NominalWidth", "COBie.Type.NominalHeight", "COBie.Type.Size",
    "COBie.Type.Colour", "COBie.Type.Material", "COBie.Component.Name", "COBie.Component.Description",
    "COBie.System.Name", "COBie.System.Description", "NEOM_Type_Name", "NEOM_Type_NominalLength",
    "NEOM_Type_NominalWidth", "NEOM_Type_NominalHeight", "NEOM_Type_Size", "NEOM_Type_Material",
    "NEOM_Component_Name", "NEOM_Component_Description", "NEOM_Floor_Name", "NEOM_Floor_Description",
    "NEOM_Operations_Class", "NEOM_Specification_Code", "NEOM_Specification_Title", "NEOM_Risk_Class",
    "NEOM_BOQ_Cost_Code", "NEOM_Target_LOD", "NEOM_Clash_Test_Code", "NEOM_RoomSpace_Type",
    "NEOM_Design_Occupancy", "NEOM_Designed_Lux_Level", "NEOM_Designed_Temperature", "NEOM_Floor_Area"
]


def extract_desired_properties(entity):
    properties = {}
    for rel_def in entity.IsDefinedBy:
        if rel_def.is_a("IfcRelDefinesByProperties"):
            prop_def = rel_def.RelatingPropertyDefinition
            
            if prop_def.is_a("IfcPropertySet"):
                for prop in prop_def.HasProperties:
                    if prop.Name in desired_parameters:
                        properties[prop.Name] = prop.NominalValue.wrappedValue if prop.NominalValue else None
            
            elif prop_def.is_a("IfcElementQuantity"):
                for quantity in prop_def.Quantities:
                    if quantity.Name in desired_parameters:
                        # The value may be in different attributes depending on the quantity type
                        # Adjust according to your needs
                        value = getattr(quantity, 'NominalValue', None) or getattr(quantity, 'LengthValue', None)
                        properties[quantity.Name] = value
    
    return properties

def process_ifc_file(ifc_path, output_path):
    
    print(f"Processing: {ifc_path}")
    
    ifc_file = ifcopenshell.open(ifc_path)
    
    workbook = Workbook()
    sheet = workbook.active
    sheet.append(["Entity Type", "GlobalId"] + desired_parameters)
    
    for ifc_type in desired_ifc_types:
        for entity in ifc_file.by_type(ifc_type):
            properties = extract_desired_properties(entity)
            row_data = [entity.is_a(), entity.GlobalId] + [properties.get(param, "") for param in desired_parameters]
            sheet.append(row_data)
    
    workbook.save(output_path)
def process_directory(directory_path):
    for root, dirs, files in os.walk(directory_path):
        for file in files:
            if file.lower().endswith(".ifc"):
                ifc_path = os.path.join(root, file)
                output_path = os.path.join(root, os.path.splitext(file)[0] + '.xlsx')
                process_ifc_file(ifc_path, output_path)

try:
    directory_path = input("Please enter the directory path you wish to process: ")
    process_directory(directory_path)
except Exception as e:
    print(f"An error occurred: {str(e)}")
finally:
    input("Press Enter to close the program...")
```

I need guidance on modifying my script to handle the variation in the IFC file structure generated by different versions of Revit's IFC Exporter. How can I adapt extract_desired_properties or other parts of my script to ensure that all necessary properties are extracted regardless of structural differences between versions?

Any help with this issue would be greatly appreciated, especially if anyone has faced and overcome similar challenges while working with IFC files from different software versions.

Additionally, I am attaching two example IFC files of the same architectural model exported using the different versions of Revit's IFC Exporter for reference. The first file is exported using version 22.1 and the second using version 22.6. These files should provide clear examples of the inconsistencies in question. I encourage you to run the script with both files to observe the differences in the extracted data firsthand. Any insights into how to adjust the script to accommodate these differences would be invaluable.

[EXAMPLES.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13294567/EXAMPLES.zip)

Thanks in advance!

**Comment by Andrej730** [comment]
Hello! Haven't looked through the example files - what are the differences in the structure?

**Comment by Moult** [comment]
@santiagoayerbe I would discourage you from writing such raw code to interact with IFC - ifcopenshell provides a bunch of utilities that resolves a bunch of stuff on your behalf. I would instead use `ifcopenshell.util.element.get_psets()`.

https://blenderbim.org/docs-python/autoapi/ifcopenshell/util/element/index.html#ifcopenshell.util.element.get_psets

You may also be interested in IfcCSV which can do exactly what you're after (just use wildcards for the pset name).

https://blenderbim.org/docs-python/ifccsv.html#source-installation

(docs are a bit outdated I need to regenerate them)

**Comment by santiagoayerbe** [comment]
HI @Moult  Im going to give it a try at both of your aproach and ill let you know how it goes. Thanks!

**Comment by santiagoayerbe** [comment]
hi @Moult  im using the IfcCsv Aproach, and i can get it running with the minimal example and its getting the data. but when i try to adjust it to get specific information from the IFC file its not working. 
Can you give me an idea on how to aproach this?

**Comment by Andrej730** [comment]
> when i try to adjust it to get specific information from the IFC file its not working

any specific example?

**Comment by santiagoayerbe** [comment]
@Andrej730  yes, i want to retrive data from specific parameter such as Ifc_Entity, Ifc_Enumeration or  NEOM_BOQ_Cost_Code.

**Comment by santiagoayerbe** [comment]
if you run my code with the 22.1 file youll see that data comes trought but with the 22.6 file it doesnt.

**Comment by Andrej730** [comment]
> yes, i want to retrive data from specific parameter such as Ifc_Entity, Ifc_Enumeration or NEOM_BOQ_Cost_Code.

I mean the example of code using ifccsv that's not working.

**Comment by Moult** [comment]
To fetch a property, you need to specify both the name of the property set and the property (or regex wildcard).

```
attributes = ["Name", "Description", "Pset_Name.Ifc_Entity"]
# or 
attributes = ["Name", "Description", "/.*/.Ifc_Entity"]
```
