### ISSUE TITLE
Binary of IfcGeomServer

### ISSUE THREAD

**Issue by jddaigle** [IfcOpenShell/IfcOpenShell#398]
Hi, where can I get the latest compiled version of the IfcGeomServer?
tks!

**Comment by aothms** [comment]
The 'latest' is right here: https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/v0.5.0-preview2

We currently don't really have the infrastructure setup yet for automatically building and distributing recent binaries. I highly recommend to look into the build scripts yourself as it should make compilation from source as easy as a single command:

Windows: https://github.com/IfcOpenShell/IfcOpenShell/tree/master/win
Unix / macOS: https://github.com/IfcOpenShell/IfcOpenShell/tree/master/nix

**Comment by aothms** [comment]
New builds available here https://github.com/IfcOpenBot/IfcOpenShell/commit/ba5049a7ebac112d540f752dad67309da9f47b0f#commitcomment-30047068
