### ISSUE TITLE
IfcGeom/ConversionResult.h incorrect function signature

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#3992]
@aothms 

This function returns `bool` but the actual return values are pointers (L104 and L106).

Should the return type be `OpaqueNumber*`?

https://github.com/IfcOpenShell/IfcOpenShell/blob/73abb25fc33520b6f34e855909b6fb2ba709f92c/src/ifcgeom/ConversionResult.h#L100-L108

I'm getting build errors in Visual Studio 2022 for this function.

**Comment by RickBrice** [comment]
@aothms Also having build issues with the following

1)
https://github.com/IfcOpenShell/IfcOpenShell/blob/73abb25fc33520b6f34e855909b6fb2ba709f92c/src/ifcgeom/kernels/cgal/nef_to_halfspace_tree.h#L1154

The error is

~~~
4>F:\IfcOpenshell\src\ifcgeom\kernels\cgal\../../../ifcgeom/kernels/cgal/nef_to_halfspace_tree.h(1154,23): error C2275: 'CGAL::Lazy_kernel_generic_base<EK_,AK_,E2A_,Kernel_>::FT': expected an expression instead of a type
4>        with
4>        [
4>            EK_=CGAL::Simple_cartesian<CGAL::Gmpq>,
4>            AK_=CGAL::Simple_cartesian<CGAL::Interval_nt_advanced>,
4>            E2A_=CGAL::Cartesian_converter<CGAL::Simple_cartesian<CGAL::Gmpq>,CGAL::Simple_cartesian<CGAL::Interval_nt_advanced>,CGAL::NT_converter<CGAL::Gmpq,CGAL::Interval_nt<false>>>,
4>            Kernel_=CGAL::Epeck
4>        ]
4>F:\IfcOpenshell\src\ifcgeom\kernels\cgal\../../../ifcgeom/kernels/cgal/CgalConversionResult.h(263,23): message : see reference to function template instantiation 'std::unique_ptr<halfspace_tree<Kernel_>,std::default_delete<halfspace_tree<Kernel_>>> build_halfspace_tree_decomposed<Kernel_,Kernel>(CGAL::Nef_polyhedron_3<Kernel_,CGAL::Default_items<Kernel>::Items,bool> &,std::list<CGAL::Plane_3<Kernel_>,std::allocator<CGAL::Plane_3<Kernel_>>> &)' being compiled
4>        with
4>        [
4>            Kernel=Kernel_,
4>            Kernel_=CGAL::Epeck
4>        ]
~~~

if I change this to the following, Visual Studio 2022 is happy

`std::array<Kernel::FT, 3> abcd{it->plane().a(), it->plane().b(), it->plane().c()};`

2)

https://github.com/IfcOpenShell/ifc-to-cityjson/blob/eddef60fbae2f0fe43cbc05acce40583ef68cd6d/processing.cpp#L164

The error is 
`F:\IfcOpenshell\src\ifcconvert\cityjson\processing.cpp(164,15): error C2440: 'type cast': cannot convert from 'std::shared_ptr<IfcGeom::ConversionResultShape>' to 'ifcopenshell::geometry::CgalShape *'`

I'm haven't been able to figure this one out.

**Comment by aothms** [comment]
Thanks for these and sorry for the inconvenience. I will slowly migrate to vs2022 as well.

1. return type should be bool, but function body adapted
2. I thought both should be ok to initialize an array, but either way is fine, thanks!
3. this has been fixed as well
