### ISSUE TITLE
Can't change the name of a custom property

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#3997]
It should be possible to change the name of a self-created property.
Only the value can be changed.

BTW The only reason it is not the default name is because I experimentally changed it with an editor in the IFC file. I also see no possibility to add another property.

https://github.com/IfcOpenShell/IfcOpenShell/assets/1941141/f49bafa2-eefb-482e-95c0-f99b6d788daa

**Comment by theoryshaw** [comment]
Do you know about 'Property Set Templates'?

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b6d5519a-bcf1-438a-896d-1937a8391fc6

...

As you can see in the video, however, it seem BB should accommodate the renaming of the property.  As you can see the old property name remains.

**Comment by kurb70** [comment]
Yes, I know about the [IfcPropertySetTemplate](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcPropertySetTemplate.htm).

Thanks for the example. This way seems to me to be a tedious workaround if "only" one property is to be added to an element.

If this way is the one that the makers of BlenderBIM see as the most suitable, then I can live with it. At first glance, it looked like a bug to me.

**Comment by DaJansenGit** [comment]
I came around the same problem today, as I also wanted to just add one property. 

As there is the option to add a new property and a new custom PSet through the Object Information tab, I would agree that it should also be possible to give these attributes a name.
Currently, only the name of the PSet and the value of the attribute (numeric or string), but not the name of the property itself can be changed as you can see in the screenshot attached.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/27726960/c0017ef0-7419-4a88-ba0d-45f3578c2d38)

**Comment by kurb70** [comment]
I checked it again after a long time. The issue can be closed as it works with Bonsai v0.8.1-alpha241004-99b1f5e at the latest.
