### ISSUE TITLE
Improvements to 3dsmax cmake script

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#40]
Follow up of https://github.com/IfcOpenShell/IfcOpenShell/pull/35 and https://github.com/IfcOpenShell/IfcOpenShell/issues/13
- [ ] Apparently the 3dsmax installer sets some environment variables: ADSK_3DSMAX_SDK_20x0 (only for newer 2015 and up it seems?).
  Use a simple for loop in CMake to see what is set in case no dir is explicitly set by the user.
- [ ] Therefore the hardcoded path set to THREEDS_MAX_SDK_HOME in run-cmake.bat would no longer be necessary. 
  Propose to rename to ADSK_3DSMAX_SDK_ROOT for users to set a specific path.
- [ ] Error out when doing a 32bit build and 3ds max > 2013
- [ ] Set correct libraries for 32bit build if possible
- [ ] Check existence of Max.h and maxutil.lib library, else error out
- [ ] Add INSTALL target based on ADSK_3DSMAX_x86_2013 / ADSK_3DSMAX_x64_2013 install path

**Comment by Stinkfist0** [comment]
Great, didn't know about ADSK_3DSMAX_SDK_20x0 (I'm a complete 3ds Max SDK noob). BTW do you happen to have a 32-bit SDK on your computer? Is the lib path lib/Win32 or lib/x86?

**Comment by aothms** [comment]
On my PC the path for 64bit libs is `.\x64\lib\`. For 32bit it's just `.\lib\`.

**Comment by aothms** [comment]
I don't think we need to do this anymore. Nobody complained about IfcMax not being part of the v0.5.0-preview2 release. An intermediate conversion to DAE gives more conversion options to end-users. The trouble of building maintaining and testing IfcMax is not worth the 50 [1] monthly downloads. There seems no official way to obtain the SDK without obtaining a license to the product, which I am no longer willing to do.

[1] https://sourceforge.net/projects/ifcopenshell/files/0.5.0-preview1/IfcMax-0.5.0-preview1-win64-3dsMax2015.zip/stats/timeline?dates=2017-01-01+to+2017-07-03
