### ISSUE TITLE
Assign Horizontal Layers type with a project defined in mm creates a wrong geometry

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#4004]
Follow this steps:

1. Create a new empty file in millimeter (this is important because in meter it works correctly)
2. Create a new mesh cube
3. Assign the IfcCovering class to the cube
4. Create a new IfcCoveringType with predefined type=flooring and with horizontal layers. The default material should be 100 mm thick
5. Assign the IfcCoveringType to the cube: the cube will be extruded to 100000mm instead of 100 ...

I tried to solve this bug but with no success, i think that the problem is that somewhere it takes the 100 in meters instead of millimeters ...
Also, if you try to modify the material thickness and reassign for example 100, it extrudes the object correctly ...

**Comment by Andrej730** [comment]
Nice catch! It wasn't related to coverings, it was occuring if you'd regenerate slabs from types or layers.
