### ISSUE TITLE
Changing the color of an object with the RepresentationType "MappedRepresentation"

### ISSUE THREAD

**Issue by MeIoX** [IfcOpenShell/IfcOpenShell#4005]
The problem is that if I change the color of an object with the RepresentationType "MappedRepresentation", all associated objects are also colored. 

If I delete the Constructiontype of objects in Blender beforehand (see picture), the coloring of individual objects works. Is there a way to color the objects without deleting the type?
Or is there a code for Python with which I can delete the type in the script without going the detour via Blender.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/149197111/75cb3c6f-9e16-4869-bc1c-240bb257e4b2)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/149197111/3469af1c-f38a-40eb-b98b-45819ab1a553)

**Comment by theoryshaw** [comment]
I don't think this is possible.  You can remove the type, and then change the color, but the geometry will lose the 1:many relationship.  

Might want to ask on https://community.osarch.org/, as there's more users there, that might have an idea.

**Comment by MeIoX** [comment]
Okay, too bad. I'll give it a try there then.

**Comment by Andrej730** [comment]
Styles connected to the representation items and if type object has representation then all the occurences share the same representation with the same representation items but with "MappedRepresentation" RepresentationType.



If you want to delete the type object from script you can do
```python
import blenderbim.tool as tool
tool.Geometry.delete_ifc_object(bpy.data.objects["IfcDoorType/DT01"])
```

**Comment by MeIoX** [comment]
This code only works within Blender right? Not in an external Python script? 

There is an error like: ModuleNotFoundError: No module named 'bpy'

When I try to install the module, it says it only works with Python 3.7 or 3.8. But I'm using Python 3.11...

**Comment by Andrej730** [comment]
Yes, it's blenderbim's method that deletes blender object, so it's used within blender.
If you want to remove type object just in IFC, without loading it to blender you can use [root.remove_product](https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/root/remove_product/index.html)
