### ISSUE TITLE
Have the 'clone opening' feature work with window/doors. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4007]
related to #3600. 

Would be nice if the 'clone opening' feature worked with the ifcopeningelements that were associated with window/doors.

**Comment by maxfb87** [comment]
Also related https://github.com/IfcOpenShell/IfcOpenShell/issues/3834

**Comment by maxfb87** [comment]
@theoryshaw hey, do you mean that would be helpful to have the same workflow but with a window or a door selected instead of an opening?

**Comment by theoryshaw** [comment]
Eerie, i was 'just' using your cloning tool. :)

> @theoryshaw hey, do you mean that would be helpful to have the same workflow but with a window or a door selected instead of an opening?

Not necessarily, although that would be nice too. 

I was just saying that it would be nice if you could clone the opening attached to the window and door, as well. 

As you can see, from the following video, the cloned opening attached to the window's original opening is not synced.  As witnessed, when the window is moved and both walls are regenerated.


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ff2dc7d5-11c1-4438-a0b4-b775de6b78d8

**Comment by maxfb87** [comment]
@theoryshaw ok, does it work if you regen also the second wall?

**Comment by maxfb87** [comment]
@theoryshaw does it work now also on your side now that i merged the PR?

**Comment by theoryshaw** [comment]
Seems to work great! Thanks @maxfb87
