### ISSUE TITLE
ifcfile.create_entity() crashes kernel if 'type' unknown

### ISSUE THREAD

**Issue by themmes** [IfcOpenShell/IfcOpenShell#401]
The first tutorial of `IfcOpenShell`  (http://academy.ifcopenshell.org/creating-a-simple-wall-with-property-set-and-quantity-information/) contains the following line:

`ifcfile.createIfcPropertySingleValue("Reference", "Reference", ifcfile.create_entity("IfcText", "Describe the Reference"), None),`

The following part of this line `ifcfile.create_entity("IfcText", ... )` crashes the kernel ungracefully, the `type` probably should be `IfcTextLiteral` and the function should probably return an error.

[EDIT]:

It actually seems as if `IfcText`, `IfcReal`, etc. are the correct type names. However, maybe I am missing the correct IFC version/specification?

In my opinion the kernel should not crash when specifying an unknown type, therefore leaving this issue open.

**Comment by aothms** [comment]
> In my opinion the kernel should not crash when specifying an unknown type, therefore leaving this issue open

Definitely!

My guess is you're using the 0.6 version, i.e. from anaconda? There's a similar discussion going on here: https://sourceforge.net/p/ifcopenshell/discussion/1782718/thread/f6bfd26f/

This has been fixed now in the 0.6 branch, your options are (a) compile yourself (b) wait for a new release the be pushed or (c) switch to the older 0.5 version for the time being: https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/v0.5.0-preview2 which is likely more stable at the expense of now support for multiple schemas at runtime.

**Comment by themmes** [comment]
To install `IfcOpenShell` version `0.5.0` within my conda environment as you suggested I used:

`pip install git+git://github.com/IfcOpenShell/IfcOpenShell.git@v0.5.0-preview2`

However, this results in the following error:

```
Collecting git+git://github.com/IfcOpenShell/IfcOpenShell.git@v0.5.0-preview2
  Cloning git://github.com/IfcOpenShell/IfcOpenShell.git (to revision v0.5.0-preview2) to /tmp/pip-req-build-180lwqp9
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/tom/anaconda3/envs/pcenv/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-180lwqp9/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-180lwqp9/
```

I tried various methods to solve this like:

`pip install --upgrade pip`
`pip install --upgrade setuptools --ignore-installed`
`pip install --upgrade ez_setup --ignore-installed`

Do you know how to solve these installation issues?
Why is conda suggested as an installation method if there is no stable version on conda? Would it be possible to add 0.5.0 to conda?

**Comment by aothms** [comment]
IfcOpenShell is not that deeply integrated into the pip/pypi indexes. You'll just have to download the appropriate zip file from the github release archives

https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/v0.5.0-preview2

> Do you have a time indication on the waiting alternative?

Most energy now is directed at stability issues with the latest versions of Open CASCADE 7.2 and 7.3. I am not able to give a meaningful estimate. Compiling yourself is really effort less. Just run a single script [1] or [2].

[1] https://github.com/IfcOpenShell/IfcOpenShell/tree/master/win
[2] https://github.com/IfcOpenShell/IfcOpenShell/tree/master/nix

> Why is conda suggested as an installation method if there is no stable version on conda? Would it be possible to add 0.5.0 to conda?

It's not a perfect world. Most users use IfcOpenShell to consume IFC data so are not affected. The 0.5 version is dependent on a compile-time schema definition and conda does not have a mechanism to switch between such different versions. So that version is not suitable.

**Comment by themmes** [comment]
I see, thank you for your detailed response. I will give it a try ;-)!

**Comment by themmes** [comment]
Oops, did not mean to close this issue.

**Comment by Moult** [comment]
Closing some of these older issues as this has been fixed for some time now :)

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> f.create_entity('IfcText', 'asdf')
IfcText('asdf')

>>> f.create_entity('IfcTextFoobar', 'asdf')
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 264, in create_entity
    e = entity_instance((self.schema, type), self)
  File "/home/dion/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 107, in __init__
    e = ifcopenshell_wrapper.new_IfcBaseClass(*e)
  File "/home/dion/.config/blender/3.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 4431, in new_IfcBaseClass
    return _ifcopenshell_wrapper.new_IfcBaseClass(schema_identifier, name)
RuntimeError: Entity with 'IfcTextFoobar' not found
```
