### ISSUE TITLE
adding quantity takeoff to IfcSlab (predefinedtype ROOF) and IfcDoor gives wrong quantities. 

### ISSUE THREAD

**Issue by motjokk** [IfcOpenShell/IfcOpenShell#4011]
![IfcDoor](https://github.com/IfcOpenShell/IfcOpenShell/assets/33512457/6a2428fd-8a0b-4e51-838e-51b1cad9b5a5)
![IfcSlab](https://github.com/IfcOpenShell/IfcOpenShell/assets/33512457/7276f963-d597-464c-b2df-f71dd8d94173)

**Comment by maxfb87** [comment]
@motjokk could you share the ifc file?

**Comment by motjokk** [comment]
[Uploading 327706_Skjetlein videregående skole_Bygg F_ARK.txt…]()

**Comment by motjokk** [comment]
[Uploading 327706_Skjetlein videregående skole_Bygg F_ARK.txt…]()

**Comment by maxfb87** [comment]
@motjokk well, about the roof quantities, i committed a fix so now the qto calculator should be more precise in calculating IfcRoof quantities ...
On the contrary, about the door, it is pretty difficult to calculate the quantities for an object with this shape:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/5d1ea54b-37e8-419c-a3b4-a389ecf06f9e)
Please remember that the algorithm behind "calculate all quantities" button ties to calculate the quantities from the object shape...in this case there is the door frame that modify significantly the calculus ... so i think it is pretty impossible to automate this case ...
I think the best way to proceed, in this case, is to assign the quantities by hand to the type, so every instance of that type inherit them ...
Thanks for the reporting!
