### ISSUE TITLE
Wrong calculation of quantity takeoff for IfcDoor and IfcSlab using BlenderBIM

### ISSUE THREAD

**Issue by motjokk** [IfcOpenShell/IfcOpenShell#4016]
We are using BlenderBim v0.0.231104.

![IfcDoor](https://github.com/IfcOpenShell/IfcOpenShell/assets/33512457/f3e6ddd7-a508-4dcb-bfe5-a5279609f031)
![IfcSlab](https://github.com/IfcOpenShell/IfcOpenShell/assets/33512457/5c278601-5660-455b-bd54-e4c5e5f3fa58)

**Comment by maxfb87** [comment]
@motjokk isn't it the same issue reported here https://github.com/IfcOpenShell/IfcOpenShell/issues/4011 ?

**Comment by motjokk** [comment]
My mistake, I will close this one :)
