### ISSUE TITLE
Debug build linker problems with multiple projects using HDF library

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#4017]
When building IFCOS with the Debug target, I get linker errors in the following projects. The HDF lib files are not correct.

- IfcAdvancedHouse
- IfcOpenHourse
- _ifcopenshell_wrapper
- IfcConvert
- IfcGeomServer

The problem is the lib files need `_D` to be appended.

~~~
F:\IfcOpenshell\_deps-vs2022-x64-installed\HDF5-1.8.22-win64\lib\libhdf5_cpp_D.lib
F:\IfcOpenshell\_deps-vs2022-x64-installed\HDF5-1.8.22-win64\lib\libhdf5_D.lib
F:\IfcOpenshell\_deps-vs2022-x64-installed\HDF5-1.8.22-win64\lib\libzlib_D.lib
F:\IfcOpenshell\_deps-vs2022-x64-installed\HDF5-1.8.22-win64\lib\libsz_D.lib
F:\IfcOpenshell\_deps-vs2022-x64-installed\HDF5-1.8.22-win64\lib\libaec_D.lib
~~~

I have zero-experience with CMake - if someone knowledgeable can help me figure out how to make the appropriate changes, that would be great.

In the meantime, in Visual Studio, I manually append the `_D` to get the projects to link

**Comment by aothms** [comment]
We did seem to try to account for that, but the postfix we use is `_debug` and not `_D`.

Did you have the _debug postfix in your earlier config or were they without any postfix?

**Comment by RickBrice** [comment]
There was no postfix at all.

**Comment by RickBrice** [comment]
Same as #4584
