### ISSUE TITLE
BlenderBIM Crash

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4018]
![Skermskoot (46)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/66b4a6ea-42d9-4429-9418-4e44a7280885)

In Belnder 3.6, BIM
When I select an object under TYPE, then go to the 
-Object Information
-Object Metadata
-Reassign IFC Class to "IFCtrasnportelement"
-Select user defined type
-Add a value
Then Blender crashes

As per the attcached screen shot
![Skermskoot (46)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/66b4a6ea-42d9-4429-9418-4e44a7280885)

**Comment by aothms** [comment]
Something went wrong upload the screenshot it seems

**Comment by Ave-5D** [comment]
Hi Thomas

Thanks for coming back.

I don’t know why I am new to Github, I tried it again and it looked the same.

I updated my BlenderBIM with the yesterday’s release this morning.

 

Please find attached.

 

Kind regards

 

Roel

**Comment by Andrej730** [comment]
@Ave-5D Hello! Can't reproduce the issue. 

Can you please attach tht .ifc file you're using and specify what element exactly you were changing? Note that you won't be able to attach .ifc file here directly but you can add `.txt` extension at the end of the filename to make it uploadable.

Previously you attached the screenshot but I guess there was an issue (typically this one occurs if you send the message before the image finish uploading to Github):
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/2c7cb01d-166d-4edd-af36-44accbe7907f)

**Comment by Ave-5D** [comment]
[2130 AIR BAG LEVELER IFC.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13412316/2130.AIR.BAG.LEVELER.IFC.txt)

Hi, I tried again after updating the BlenderBIM addon, and I still got the same problem.
Please find attached the file as requested.
Thanks
Roel

**Comment by Andrej730** [comment]
@Ave-5D issue is fixed, you can try it in the new build.

**Comment by Ave-5D** [comment]
Thank you :-)
