### ISSUE TITLE
bSDD suggestions

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4019]
1. There are many duplicate libraries: 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/0d55d147-be94-4e26-b14b-5be3b324aafd)

2. There are libraries that don't show up on the bSDD oficial webpage and showing in BBIM.

3. It would be cool to have a way to filter the Active standards from the one ones that have the status Preview.

**Comment by c4rlosdias** [comment]
Perhaps it would be interesting if only active domains were loaded!

**Comment by BIMvoice** [comment]
I think it's okay to have the option to load both of them. Maybe someone wants to publish a classification system and test it before making it active.

**Comment by c4rlosdias** [comment]
I can arrange it, what do you think of that @Moult ?

**Comment by Moult** [comment]
@c4rlosdias go ahead :)
