### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vserge** [IfcOpenShell/IfcOpenShell#402]
Good time.

When I try convert the IFC file with model of heating camera to DAE with any IfcConverter options It seems like a exploded camera.
<img width="728" alt="2018-06-14 17 30 46" src="https://user-images.githubusercontent.com/7705393/41424097-cc5ce672-7005-11e8-9972-a4e825a4d18a.png">
Opening the file in solibri shows a different result.
<img width="590" alt="2018-06-14 17 29 30" src="https://user-images.githubusercontent.com/7705393/41424098-cc892700-7005-11e8-8df1-2a0d70057738.png">

The IFC file prepared by Revit and can be downloaded from link https://drive.google.com/open?id=19C2HGEumjgJ_Q0cmwMtN7xpHYFdVRGkb

Do you have any suggestion on what is happening, is there anything I can do to fix this?
Before you have same issue #8

**Comment by aothms** [comment]
You're likely using an older version. Try the preview2 release https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/v0.5.0-preview2

This has probably been fixed in 00215867c06269b28a11acffb32baa730812a728

**Comment by aothms** [comment]
New builds available here https://github.com/IfcOpenBot/IfcOpenShell/commit/ba5049a7ebac112d540f752dad67309da9f47b0f#commitcomment-30047068

Closing for now, feel free to reopen and provide more information.
