### ISSUE TITLE
Object is in IFC, but doesn't show in SVG

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4022]
This one is a strange one I haven't experienced before.   Best way to show, is via a video. 

file: https://hub.openingdesign.com/OpeningDesign/Monica_Residence/src/commit/5cf0a22fdeedbccfdebf9f788f25459f1501f7ec/Models/BlenderBIM/Monica_Residence.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d1f63c16-80c8-48ed-a503-f2542a8536a1

**Comment by theoryshaw** [comment]
nevermind, it has something to do with the css. :\

**Comment by theoryshaw** [comment]
Sorry, i'm reopening, as this is still strange to me. 

If you delete the following rule. 
`.matsCategory-wood1 { fill: url(#wood); stroke: black; stroke-width: 0.0; }`

... that trusses shows up again. 

assets: https://hub.openingdesign.com/OpeningDesign/Monica_Residence/src/commit/5cf0a22fdeedbccfdebf9f788f25459f1501f7ec/Models/BlenderBIM/drawings/assets

**Comment by aothms** [comment]
If you open the SVG in e.g firefox and use the developer tools you can get a very good idea of the computed/inherited style, positioning, draw order, etc. Are you familiar with that?

**Comment by theoryshaw** [comment]
Thanks @aothms.  I use chrome to do some of this, will try Firefox too.  Thank you for the suggestion.

**Comment by theoryshaw** [comment]
whoops, i see what i did i think.  :)
