### ISSUE TITLE
BlenderBIM adding representation to an empty object

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#4025]
If I have an empty object without a representation, such as a Building, or a Type created with the `bim.add_empty_type()` operator; it doesn't seem to be possible to add a representation to this object.

Under *Geometry and Materials > Representations > +*, I see options for *Trace Outline*, *Bounding Box* and *Full Representation*, the first two just give an error: `expected 'Mesh' type found 'NoneType' instead`, and the third does nothing.

The expectation is that the '+' button should add a simple cube or square representation (depending on the context) that can then be edited by the user.

**Comment by Andrej730** [comment]
Resolved after cc6d254
