### ISSUE TITLE
BlenderBIM Representation Items surface style misreported

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#4028]
This object
[two-surface-styles.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13405061/two-surface-styles.ifc.txt) has two Representation Items, each with a named Surface Style. In Geometry and Materials > Representations > Representation Items; only one of the Surface Styles is shown regardless of which Item is selected: 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/8f63fc80-1224-4bf6-b9cb-50a9b8d08357)

**Comment by Andrej730** [comment]
Fixed that one but found similar issue is still present in other places of UI data `data.py` modules where we use some UI index and the information is not getting updated as we don't update `data.py` on every UI index change.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/042235b4-efaf-4d4d-aa07-141624ccab4b)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/ad1875f1-8474-47e1-bafc-f9f7d4f5f6c7)

**Comment by Moult** [comment]
Dealing with UIList updates is a case by case scenario, sometimes we need an update trigger on the active_x_index, or sometimes a solution like this one is suitable. Closing as this one is resolved.
