### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by ger08061959** [IfcOpenShell/IfcOpenShell#403]
/home/ger/IfcOpenShell/src/ifcgeom/IfcGeomFunctions.cpp: In member function ‘bool IfcGeom::Kernel::boolean_operation(const TopoDS_Shape&, const TopTools_ListOfShape&, BOPAlgo_Operation, TopoDS_Shape&, double)’:
/home/ger/IfcOpenShell/src/ifcgeom/IfcGeomFunctions.cpp:3105:11: error: ‘class BRepAlgoAPI_BooleanOperation’ has no member named ‘SetNonDestructive’
  builder->SetNonDestructive(true);

**Comment by aothms** [comment]
Thanks, apparently `SetNonDestructive` does not exist prior to occt 7.0. 4cfb2f102797cf563107c1939e48e6fcd4d7e9d0
