### ISSUE TITLE
BlenderBIM: Activating BCF Viewpoint hides selected objects

### ISSUE THREAD

**Issue by semhustej** [IfcOpenShell/IfcOpenShell#4031]
When activating BCF Viewpoint, selected objects are switched to hidden state. I am not sure if this is a bug or feature, but to me it seems more like a bug. Hidden objects can be easily with unhidden with unhide command.
I was able to reproduce the behavior with multiple BCF projects.  The behavior is visible in recorded video: https://youtu.be/Yc--84cDmH0

Sample dataset from the video:
[BCF-viewpoint.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13418135/BCF-viewpoint.zip)

**Comment by Andrej730** [comment]
Thanks for reporting this! Fixed
