### ISSUE TITLE
[BlenderBIM] feature request: setting option to disable BIM workspace as default

### ISSUE THREAD

**Issue by dirkolbrich** [IfcOpenShell/IfcOpenShell#4036]
The BlenderBIM add-on introduces a new dedicated `BIM` workspace, which is activated by default. Meaning, on startup of **any** `.blend` file, the workspace `BIM` is active. This is kind of inconvinient if I want to use Blender for other stuff than BIM/IFC work.

Is there a way to add an add-on setting option to deactivate this default switching to the `BIM` tab?

**Comment by Gorgious56** [comment]
Hello ! I agree that this is quite disruptive in non-bim related workflows. I remember a discussion over on OsArch chat about this kind of subject and I am personnaly not sure about hiding the addon features. 

The BlenderBIM addon is an extensive addon that completely changes the way Blender is used. It adds a bunch of overhead properties to each and every object, which will cause to unnecessarily bloat the file size if they're not used. It overhauls, extends and changes a certain number of vanilla shortcuts and operators. It completely changes some parts of the UI. I think users should be reminded at all times that they're using the BlenderBIM addon.

I'd suggest rather temporarily disabling the addon in the preferences. That way users need to make a conscious effort to enable or disable the addon when they want to switch workflows. I'd be happy to read other people's point of view. 

Cheers

**Comment by dirkolbrich** [comment]
Hi,
I disagree here.

1. My feature request is not about hiding the BlenderBIM add-on and its functionality. But just to make it optional (via an add-on setting, just like the `Should setup Workspace layout for BIM` setting) that Blender automatically switches to the BIM workspace on start-up. I would like to have the option to keep the default start-up view.

2. An add-on which does not respect the default behaviour of an app is IMHO invasive, I would even go that far and call it assaultive (even though that's a strong word).
I use Blender in a lot of different ways, not just BIM. So it shouldn't make workflows outside of BIM unnecessarily difficult or foreign to the user. But I also want to have BIM capabilities easily available at a fingertip. So this excludes a deactivation of the add-on every time I don't need it. I know `BIM` is available as the workspace tab is always in view. Just like the `Scripting` or `Animation` tab. The difference is, these tabs don't alter my default workflow.

I have seen another Issue https://github.com/IfcOpenShell/IfcOpenShell/issues/3691 which mentions, that BlenderBIM tools populate (pollute?) the Toolbar even in workspaces where they are not functional. I agree with this issue. I think all BlenderBIM tools should only be visible in the `BIM` workspace. Make tolls visible without functionality is very confusing.

**Comment by Moult** [comment]
I'm not exactly sure what you're after, if you disable the `Should setup Workspace layout for BIM` setting, then the BIM workspace is not created and isn't switched to it. You get the default "Layout" workspace like vanilla Blender.

**Comment by dirkolbrich** [comment]
I would like to have the extra BIM tab with the altered view layout and property editor created (added to the workspace tabs row). To work on BIM when I need to.
I just don’t want to switch to this tab by default. If Blender starts, the default tab should still be Layout.

> the BIM workspace is not created and isn't switched to it

This should be 2 separate options.

**Comment by Moult** [comment]
I disagree because there is nothing special about the "BIM workspace". A workspace in Blender is merely a layout of panels. That's it. Different people want different panel layouts for different tasks - the "BIM workspace" is a nice default for simple model browsing, but is completely inappropriate for 4D scheduling for example. Users can create their own layouts.

If a user is an advanced user, they can disable the "Should setup Workspace layout for BIM" and they can create their own workspace layout (which you can call "BIM" if that makes you happy) can save it as a preset. That's be design how Blender is meant to be used.

**Comment by dirkolbrich** [comment]
Everything you said is correct and I agree with it, the BIM workspace is nothing special.

I just would like to have the option, that with an installed and activated BBIM add-on (which creates all the cool BIM functions and panels), on start-up the default Layout workspace is active, not the BIM workspace. I don’t know how to describe it any other way. Maybe a mock-up helps:

<img width="553" alt="mock-up of BlenderBIM add-on settings with option to activate the BIM workspace on program start-up" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/3765119/34d86334-65b8-43fd-9eeb-95362f3c6529">

Maybe also the comments in my second answer further up got a bit mixed up and thus caused some misunderstanding. Only no. 1 is relevant for this feature request. My answer no. 2 is completely out of scope for this feature request and was only meant as an answer to @Gorgious56  question to hear others point of view. This is basically just my view on how a Blender add-on should be a responsible citizen in the Blender society. This would be a good discussion topic for the forum, but maybe not for this issue here.
