### ISSUE TITLE
Failling to find a property in a Pset in IfcTester.facet

### ISSUE THREAD

**Issue by cvoivret** [IfcOpenShell/IfcOpenShell#4039]
In the facet.py, the function get_pset don't do his job.
```python
def get_pset(element, pset):
    return ifcopenshell.util.element.get_pset(element, pset)
```
I believe I have fixed it with 
```python
def get_pset(element, pset):
    return ifcopenshell.util.element.get_psets(element)[pset]
```
In the first version, it cast pset as a bool and returns a dictionnary of psets.
In the second one, it returns the asked pset.

If it is the correct intention of the function ?
Cheers

**Comment by Andrej730** [comment]
@cvoivret 
hello!

can you please give an example case where `facet.get_pset` is presumably failing?

It was added in the commit 8e59282 and it's seems to be intended to work exactly as `ifcopenshell.util.element.get_pset` except it's has `@lru_cache` wrapper for optimization.

**Comment by cvoivret** [comment]
Hi, sorry to not have provided context.
The complete story...
I want to validate a ifc with a IDS that is generated trough a script. Both file are in the archive. 
[test_pset.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13445872/test_pset.zip)

With Open IFC Viewer, **I valid my IFC file with the generated ids.**. I assume then that the problem do not comes from my file. Since I'm new to ids, maybe I'm wrong.

I use the v.0.7.0 branch on commit 8cd9fb901535da65e0c763edca32b6798cd98e00 
When I run the script, I first get the error : 
`AttributeError: module 'ifcopenshell.util.element' has no attribute 'get_pset'`

I'm guessing that 
`def get_pset(element, pset):
    return ifcopenshell.util.element.get_pset(element, pset)`
is made to extract a Propertyset of name pset in the dictionnary returned by `ifcopenshell.util.element.get_psets`.
The naming seem consistent.

Moreover this snippet produces a dict of dict of pset in my case : 
https://github.com/IfcOpenShell/IfcOpenShell/blob/df2a50b335d70f9cfcc8ba1f29d78fc597c42934/src/ifctester/ifctester/facet.py#L604C1-L609C82
I feel that one level of dict is useless and comes from the implementation of the `get_pet `function.
The subsequent lines do not find the requested property since it is in a level down in the dict nesting.

The initial proposition fix the problem and make sense (too me at least :-) )

Cheers

**Comment by Moult** [comment]
I ran your code and don't get any errors:

```
RTAA DOM
[PASS] (1/1) Project Location
    Applies to:
        All IFCSITE data
    Requirements:
        The RefLatitude shall be provided
        The RefLongitude shall be provided
        The RefElevation shall be provided
[PASS] (10/10) Opening porosity
    Applies to:
        All IFCWINDOW data
    Requirements:
        porosite data shall be provided in the dataset Pset_rtaadom_porosite
[PASS] (0/0) Opening porosity
    Applies to:
        All IFCDOOR data
    Requirements:
        porosite data shall be provided in the dataset Pset_rtaadom_porosite
```

Do you get errors? If so, can you check `ifcopenshell.__file__` to make sure you are actually getting the version of ifcopenshell you think you are?

**Comment by cvoivret** [comment]
Hi @moult, I use Anaconda but to use ifctester I import a cloned version of IfcOpenshell.

```
In [3]: ifcopenshell.__file__
Out[3]: 'C:\\Users\\cvoivret\\AppData\\Local\\anaconda3\\envs\\rtaa_ifc\\lib\\site-packages\\ifcopenshell\\__init__.py'
```

**Comment by Moult** [comment]
Can you try `import ifcopenshell.util.element` then `print(ifcopenshell.util.element.get_pset)`? That function should exist. Also check your `print(ifcopenshell.util.element.__file__)` and see if you can see a `def get_pset` in there.

**Comment by cvoivret** [comment]
```
In [4]: import ifcopenshell.util.element

In [5]: print(ifcopenshell.util.element.get_psets)
<function get_psets at 0x000001CED3C18B80>

In [6]: print(ifcopenshell.util.element.get_pset)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 print(ifcopenshell.util.element.get_pset)

AttributeError: module 'ifcopenshell.util.element' has no attribute 'get_pset'

In [7]: print(ifcopenshell.util.element.__file__)
C:\Users\cvoivret\AppData\Local\anaconda3\envs\rtaa_ifc\lib\site-packages\ifcopenshell\util\element.py

In [8]: dir(ifcopenshell.util.element)
Out[8]:
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'copy',
 'copy_deep',
 'get_aggregate',
 'get_container',
 'get_decomposition',
 'get_elements_by_material',
 'get_elements_by_representation',
 'get_elements_by_style',
 'get_grouped_by',
 'get_layers',
 'get_material',
 'get_parts',
 'get_predefined_type',
 'get_properties',
 'get_property_definition',
 'get_psets',
 'get_quantities',
 'get_referenced_structures',
 'get_type',
 'get_types',
 'has_element_reference',
 'ifcopenshell',
 'remove_deep',
 'remove_deep2',
 'replace_attribute']

In [9]:
```

**Comment by Moult** [comment]
Looks like your ifcopenshell is outdated. See https://blenderbim.org/docs-python/ifcopenshell-python/installation.html for installation options. I'm not familiar with Conda so I'm not entirely sure how updated it is. If you do print(ifcopenshell.version) it'll give you a commit hash.

**Comment by cvoivret** [comment]
If it all resume to that, I'm sorry to have bother you with that...
I investigate with a fresh environement and up to date ifcopenshell package.
I let you know the results.
Cheers

**Comment by cvoivret** [comment]
Hi, problem solved with an udpate of my conda environement (and ifcopenshell).
Thanks for the support !
