### ISSUE TITLE
util.representation.ClippingInfo creates invalid IfcAxis2Placement3D

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#4052]
[This line](https://github.com/IfcOpenShell/IfcOpenShell/blob/58414777be599593bfdb1e04347699719af20140/src/ifcopenshell-python/ifcopenshell/util/representation.py#L138) creates an IfcAxis2Placement3D with a Location, an Axis, but no RefDirection:

            axis_placement = file.createIfcAxis2Placement3D(location, direction, None)

This is generating validation errors for me:

```
On instance:
    #1818=IfcAxis2Placement3D(#1816,#1817,$)
Rule IfcAxis2Placement3D.AxisAndRefDirProvision:
    (not exists(axis) ^ exists(refdirection))
Violated by:
    not (True ^ False)
     +  where True = exists(#1817=IfcDirection((-0.707106781186547,0.,0.707106781186547)))
     +  and   False = exists(None)
```

Which I *think* means that you are not supposed to have an Axis without a RefDirection.

**Comment by cvillagrasa** [comment]
I see this by pure chance. This was coming from me. From here:
https://matrix.to/#/!ssOmSJysZpXBupsgjO:matrix.org/$HWtR3MUsaK1rABKKX12IN0qOyyuqQwYf-etVBR7FnWo?via=libera.chat&via=matrix.org&via=crossbach.de

And then here:
https://github.com/IfcOpenShell/IfcOpenShell/pull/3774 / https://github.com/IfcOpenShell/IfcOpenShell/pull/3774/commits/f7fbb621e8e2c9691dd21a376f0d1999371574f9

And then no one seeing it on time 😅

I see I missed this line on the Express definition of IfcAxis2Placement3D:
`NOT ((EXISTS (Axis)) XOR (EXISTS (RefDirection)))`

I don't fully understand the reasoning behind it. It looks like low hanging fruit to reduce the file size, saving a line per plane defined. But it's the standard, and the benefit of it being written in stone is far greater than any small improvements like this.

PS: I feel like a bit more cross-referencing could be beneficial in general, specially if there's a recent commit/PR on the topic and the author is not aware of the issue. In particular, I have this bug all over my own code also, and if I hadn't seen this issue, I wouldn't have noticed until much later, when running validation tests.
