### ISSUE TITLE
When using an external surface styles, it doesn't seem to pull in material settings from the external material. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4053]
When using an external surface styles, it doesn't seem to pull in the following material settings from the external material. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a01dd853-23ff-46b3-8ed0-eea96f6acb81)

**Comment by Andrej730** [comment]
Resolved in 8270367
