### ISSUE TITLE
Can't delete object that are/were part of an array.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4058]
I can't seem to delete any of these beams.  They are/were part of an array.   Not sure how this situation was created in the first part. 

file: https://hub.openingdesign.com/OpeningDesign/Monica_Residence/src/commit/632ff22ea3f483350cfff81e999b8ee2c7c28666/Models/BlenderBIM/Monica_Residence.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9749cb02-b682-4019-b456-9aa10df1d571

**Comment by Andrej730** [comment]
It looks like some array children were removed even though they were part of an array and BBIM is now failing to find them. The simplest solution would be just to remove BBIM_Array pset from all affected elements, so BBIM won't recognize them as array elements anymore and then you'll be able to delete them.

Not sure if there is anything to fix until we know how to reproduce it as fixing anything might hide the actual cause of the issue.

**Comment by theoryshaw** [comment]
Thanks @Andrej730 I'll close this until we figure out how that parent can be deleted.

**Comment by Andrej730** [comment]
This one below looks similar. Though it was about issues with former array children elements, not the parent element.
https://community.osarch.org/discussion/1831/duplicating-failed-for-array-items-after-apply-array#latest
