### ISSUE TITLE
`bim.load_search` function in the drawing filters

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4068]
Would be nice to have the `bim.load_search` function here, as well.  Maybe i'm missing something.

![2023-11-30_22-58-23_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/837decbf-1ba2-4394-8cf6-2ec51d7d40ec)

**Comment by Moult** [comment]
I couldn't recreate this unfortunately :( I also downloaded this file: https://hub.openingdesign.com/OpeningDesign/Restaurant_Sun_Prairie/src/branch/main/Models/BlenderBIM/Restaurant_Sun_Prairie.ifc
