### ISSUE TITLE
When drawing is activated, `IfcAnnotation/IMAGE` turns off. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4076]
When drawing is activated, `IfcAnnotation/IMAGE` turns off. 

Would assume, it would turn on. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d74b2ef3-1247-4c03-a31f-f4b632921d39

**Comment by Moult** [comment]
Got a sample file?

**Comment by theoryshaw** [comment]
Also, it's not just `IfcAnnotation/IMAGE`, but other iIfcAnnotations as well.

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a8c110f6-477e-4ca7-ab3b-37aa8321f318
