### ISSUE TITLE
Cmake:Install target "ifcopenshell_wrapper" doesnot exist

### ISSUE THREAD

**Issue by Pravesh-Jamgade** [IfcOpenShell/IfcOpenShell#408]
I am building the IfcOpenShell on the windows system. While configuring the cmake,it gives me the following error:
  **CMake Error at C:/conversion/IfcOpenShell-0.4.0/src/ifcwrap/CMakeLists.txt:157 (INSTALL):
  INSTALL TARGETS given target "_ifcopenshell_wrapper" which does not exist
  in this directory**
The complete output log of cmake is as follows:
```
Boost include files found in C:/local/boost_1_67_0
Boost libraries found in C:/local/boost_1_67_0/libs
Looking for opencascade include files in: C:\Work\OpenCASCADE-build\inc
Use OCC_INCLUDE_DIR to specify another directory
Header files found
Looking for opencascade library files in: C:\Work\OpenCASCADE-build\win64\vc14\libd
Use OCC_LIBRARY_DIR to specify another directory
Library files found
No ICU include directory specified
No ICU library directory specified
ICU libraries found
No OpenCOLLADA include directory specified
No OpenCOLLADA library directory specified
OpenCOLLADA header files found
PYTHON_DEBUG_LIBRARIES not found, defining SWIG_PYTHON_INTERPRETER_NO_DEBUG workaround for IfcWrap.
CMake Error at C:/conversion/IfcOpenShell-0.4.0/src/ifcwrap/CMakeLists.txt:157 (INSTALL):
  INSTALL TARGETS given target "_ifcopenshell_wrapper" which does not exist
  in this directory.


Configuring incomplete, errors occurred!
See also "C:/conversion/IfcOpenShell-build/CMakeFiles/CMakeOutput.log".
See also "C:/conversion/IfcOpenShell-build/CMakeFiles/CMakeError.log".
```

**Comment by aothms** [comment]
Your path seems to indicate you're using IfcOpenShell 0.4.0, but that CMakeLists does not even have 157 lines [1]. Can you indicate a bit more detailed what you're doing. What were the steps exactly resulting into this?

I would recommend switching to the master branch. It's fairly stable and much more current then 0.4.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.4.0/src/ifcwrap/CMakeLists.txt

**Comment by simena86** [comment]
@Pravesh-Jamgade did you find the source of error here? I'm struggling with the same problem

**Comment by aothms** [comment]
@simena86 can you explain exactly what steps lead up to this?

**Comment by simena86** [comment]
@aothms This happens when I cloned repo, and tried to build from master (also tried to checkout commit ef7eee411b29a82b55e3eec308baa20b8d3987c6).

After re-installing cmake (downgraded from 3.12 to 3.10) on my Ubuntu 18.04 machine it worked fine. (Not entirely sure cmake was the culprit though, as I was doing some other stuff as well)
