### ISSUE TITLE
Parof Facet error

### ISSUE THREAD

**Issue by Yoshiyuki-Miyauchi** [IfcOpenShell/IfcOpenShell#4082]
I used Partof Facet with the following IDS and PartOf does not work properly.
A reference to the default value, IFCWALL, appears in the message during verification.
How should this be handled?

`    <ids:specification ifcVersion="IFC2X3" name="New Specification" minOccurs="1" maxOccurs="unbounded" description="N/A">
      <ids:applicability>
        <ids:entity>
          <ids:name>
            <ids:simpleValue>IFCBUILDING</ids:simpleValue>
          </ids:name>
        </ids:entity>
      </ids:applicability>
      <ids:requirements>
        <ids:partOf relation="IFCRELAGGREGATES" minOccurs="1" maxOccurs="unbounded">
          <ids:entity>
            <ids:name>
              <ids:simpleValue>IFCSITE</ids:simpleValue>
            </ids:name>
          </ids:entity>
        </ids:partOf>
      </ids:requirements>
    </ids:specification>`

**Comment by Moult** [comment]
I think this was fixed on Nov 2, can you check? https://github.com/IfcOpenShell/IfcOpenShell/commit/2f951d352b93fcc029b37fc73ab458db62eb81b9

**Comment by Moult** [comment]
Tested and works in latest

![2023-12-07-141657_1864x383_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/e5e31394-331c-4dcc-a92d-f05eafb11d7b)

**Comment by Yoshiyuki-Miyauchi** [comment]
@Moult san

Thank you very much. I have confirmed that it can be done successfully.
I have to update my IfcopenShell regularly.

**Comment by lfcastel** [comment]
I'm facing this same problem again in ifcopenshell 0.8.2 (using pypi)
