### ISSUE TITLE
Linux AArch64 support

### ISSUE THREAD

**Issue by lanjoni** [IfcOpenShell/IfcOpenShell#4089]
Hey! I hope everything is ok!

I would like to know about IfcOpenShell support for AArch64 architectures on Linux in general, considering that there is already a distributed model already compiled for M1 MacBooks.

Thank you very much in advance!

**Comment by aothms** [comment]
For the time being I would recommend compiling yourself, which is fairly trivial by just running the `pyton nix/build-all.py` build script.

**Comment by Krande** [comment]
Fyi: The conda forge distribution of IfcOpenShell now supports linux_aarch64 thanks to https://github.com/conda-forge/ifcopenshell-feedstock/pull/45
