### ISSUE TITLE
`bim.purge_unused_profiles` doesn't seem to work on the following file. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4096]
`bim.purge_unused_profiles` doesn't seem to work on the following file. 

It has 150 unused profiles. 

https://www.dropbox.com/scl/fi/uot7eis63kzft901cdbss/test.ifc?rlkey=0dbz0sfpr5v61iap21j2csr0g&dl=1

**Comment by Andrej730** [comment]
They are not completely unused. They are used in 39 IfcMaterialProfiles and 124 IfcExtrudedAreaSolids.
