### ISSUE TITLE
DISCUSS: product-level info extraction

### ISSUE THREAD

**Issue by deliciousteas** [IfcOpenShell/IfcOpenShell#4098]
# product-level info extraction 
I utilize `ifcopensehll-python` , as ifcwall for an example, I focus on  its product-level info  : **Representation and its objectplacement** ,of course itself.
so I do recursive method and then I got a new ifc [ file](https://github.com/IfcOpenShell/IfcOpenShell/files/13622577/newFile.zip)(you can look through it here)
while I want to add it to show up by `open IFC Viewer`，it tell me like this: 
![ad93c47d3cdc964e41a50ad2d860940](https://github.com/IfcOpenShell/IfcOpenShell/assets/107855849/802993d2-dc98-492d-9fe9-33bbee2a04f0)
actually I extracte all info from its product-level info, until it do not has any reference to other instances.
I have tried to append some basic info such as `IFCPROJECT、 IFCSITE、 IFCBUILIDNG、 IFCBUILDINGSTOREY` instance，but they do not work well.,if anyone has ideas, My pleasure to receive reply.

**Comment by Moult** [comment]
Your file is invalid in many ways. It is not compliant STEP code or syntax (i.e. not all uppercase entity names and missing ID references). It says that it was generated by ODA's toolkit, which also sounds wrong and off-topic here. Can you share your Python code and what you're trying to achieve?

**Comment by deliciousteas** [comment]
> Can you share your Python code and what you're trying to achieve?  

sure ,I just want to visualize `ifcwall`, meanwhile I only focus on this entity's **ObjectPlacement and Representation property** (not inverse property or quantity property)  
so I extrate one of its instances as sample,and **save its al  relavent id in a list**,called the new_ifclist:[170,20,131,169.....]  
> #170=IfcWall('2nruR8WJTFIBooKwoBOktT',#20,'ǽ : ����ǽ : 200����ͨǽ',$,'����ǽ:200����ͨǽ',#131,#169,'417619',.NOTDEFINED.)  

then, I can get the info from new_ifctest by `ifcopenshell.by_id(int(new_ifclist[i])` method,and instantly write it to an *.ifc file.

` all_key=list(relationship.keys())  
    all_values = [val for sublist in relationship.values() for val in sublist]  
    new_ifclist=list(set(all_key+all_values))  
    #print(new_ifclist)  
    with open("D:\IFCOpenshell_python_version\Anaconda_ifc\IFC-source\\newFile.ifc", 'a') as new_file:  
        new_file.write("\n")  
        new_file.write("DATA;\n")  
        for i in range(0,len(new_ifclist)):  
            instance=str(model.by_id(new_ifclist[i]))  
            new_file.write(instance+'\n')  
        new_file.write("\n")  
        new_file.write("ENDSEC;\n")  
        new_file.write("END-ISO-10303-21;")`

**Comment by deliciousteas** [comment]
my outputfile is here, under my discussion with my partner, we thought it might be we forget to **add spatial relationship**, lacking of **IFCPROJECT、IFCSITE、 IFCBUILIDNG AND IFCBUILDINGSTORE**  and their relationship，so i will try to intoduce some info about this.
[newFile.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13623349/newFile.zip)

**Comment by aothms** [comment]
Instead of writing the file as strings, you better try:

``` 
new_model = ifcopenshell.file(schema=model.schema)`
...
instance = model.by_id(...)
new_model.add(instance)
new_model.write(file_path)
```

or

instead of `str(instance)` use `instance.to_string()`

**Comment by Moult** [comment]
You might want to use the API for this instead: https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/project/append_asset/index.html#module-ifcopenshell.api.project.append_asset

**Comment by deliciousteas** [comment]
ohhh! Thanks for your recommend.😁😁😁😁
In fact I solve this issue by looking through **IFC4 documentation**.  
Lacking of `IfcRelReferencedInSpatialStructure` instance and `IfcRelAggregates` instance causes my file could not be open is Third-Party  IFCViewer application.
So I just utilize **IFCOPENSHELL-PYTHON** to obtain entities'inverse proerty:**IsDecomposedBy、Decomposes and ReferencedInStructures.**
all in all ,Your responses do motivate me to figure out solution.👍👍👍👍👍
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/107855849/5fe50c5f-9e85-48a0-b965-9df4bcb30a05)

@aothms @Moult
