### ISSUE TITLE
New object added to the aggregate is not propagated to the other 'linked aggregates'. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4099]
ping @brunoperdigao 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/2ef04e08-c94f-4ed1-a2a1-05fa6c0e7e58

**Comment by brunoperdigao** [comment]
@theoryshaw I think it's a bug with the "assign_object" operator. It puts the new object in the same collection of the element assembly, so it gives the impression that it worked. But if you select the new object again, you can see that it was not added to the aggregate. @Moult, I assume it is related to this commit: https://github.com/IfcOpenShell/IfcOpenShell/commit/1b35ea122ea4d38700e53669407913782dd75c5c

**Comment by brunoperdigao** [comment]
Hi @Moult and @Andrej730. I think this is the issue: the nest module that was added has the functions `assing_object` and `unassign_object` with the same name as the aggregate module. So, in when the UI for the aggregates call these functions, it's actually calling the nest functions.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/a6768235-5d5b-4124-805e-eb9170b27e17)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/c00f97d8-9971-4860-885b-d734cb53b308)

**Comment by Andrej730** [comment]
@brunoperdigao this indeed was it, added prefix to the names 👍
