### ISSUE TITLE
Approve errors in the IDS report

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4101]
I don't know how this would work but I just wanted to start this conversation: in Solibri, for example, you can mark an error as approved, because you know that error will not be fixed, are it is not worth being reported, so I would like to do the same. The reason for that is so that it won't show as an error when I send it to the modeler, to distract them from the main tasks. 

Yes, I know I can manually edit html reports, but that would be way too much manual work, so it must be in the UI a quick way to mark the errors. An alternative would be to have that in the BCF manager, but the problem is not all the other popular tools read 100% of the BCF exports from BlenderBIM.

@Moult @c4rlosdias any good ideas for this?

**Comment by vulevukusej** [comment]
I'm curious, what's missing from the other tools regarding BCF exports from BlenderBIM? To me BCF seems the interface for what you're describing.  I would first suggest reporting bugs/lack of support for BCF in the other tools first..

**Comment by Moult** [comment]
I generally don't think this is a good idea for IDS. I'd say a better approach is for the specifier to improve their applicability filters. If necessary they can have a "ExcemptFromRequirements" property or similar.
