### ISSUE TITLE
IFC for Sverchok Install error 

### ISSUE THREAD

**Issue by Dayo9174** [IfcOpenShell/IfcOpenShell#4104]
Just tried installing IFC for Sverchok Install and it returned this error when ever i tried to click the check box to apply the add on. 
```
Traceback (most recent call last):
x
File "C:\Users\bigsh\OneDrive\Attachments\Documents\Blender - Bim\blender-3.6.5-windows-x64\blender-3.6.5-windows
mod = import_(module_name)
File "C:\Users\bigsh\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ifcsverchok\_init _. py", line 32, in
from sverchok.utils.logging import info, debug
ModuleNotFoundError: No module named 'sverchok.utils.logging'
```

I am currently using Blender 3.6, I have "sverchok-master" installed and my Blender BIM version is 231124

**Comment by aothms** [comment]
It seems this should have been fixed by https://github.com/IfcOpenShell/IfcOpenShell/pull/2860/commits/30e35170a8fa1850ff0465766ebe6d22b522e1c3 You might want to manually make that change or investigate why your version is running slightly behind.

**Comment by Andrej730** [comment]
@Dayo9174 
yeah, it seems you're using some old version of ifcsverchok. You can find the latest version of the addon in https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcsverchok/README.md
