### ISSUE TITLE
GltfSerializer and ObjSerializer don't seem to be functional from Python

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4109]
Here's a test script - note that if DISABLE_TRIANGULATION=True the segfault disappears and no errors appear but the resultant obj/gltf is empty.

```python
import multiprocessing
import ifcopenshell
import ifcopenshell.geom

ifc_file = ifcopenshell.open('/home/dion/untitled.ifc')

# settings = ifcopenshell.geom.settings()
settings = ifcopenshell.geom.settings(
    DISABLE_TRIANGULATION=False, STRICT_TOLERANCE=True, INCLUDE_CURVES=True, USE_ELEMENT_GUIDS=True
)
#iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
iterator = ifcopenshell.geom.iterator(settings, ifc_file)
b = ifcopenshell.geom.serializers.buffer()
s = ifcopenshell.geom.serializers.gltf('/home/dion/untitled.glb', settings)
#s = ifcopenshell.geom.serializers.obj('/home/dion/a.obj', '/home/dion/a.mtl', settings)
s.setFile(ifc_file)
s.setUnitNameAndMagnitude("METER", 1.0)
s.writeHeader()

def yield_from_iterator(it):
    if it.initialize():
        while True:
            yield it.get()
            if not it.next():
                break

for elem in yield_from_iterator(iterator):
    print(type(elem))
    s.write(elem) # segfault :(

s.finalize()
```

**Comment by aothms** [comment]
Add `APPLY_DEFAULT_MATERIALS=True`.

It's a little bit unfortunate in terms of API. Previously these were an internal thing, so the code would make sure the correct settings are passed. But now exposing this to the user we don't do any validation yet.

**Comment by Moult** [comment]
Awesome that works! Is there any difference between doing this in Python vs using IfcConvert? (naturally in Python the goal is to use the flexibility to set_context_ids and include/exclude filters in an easier way than CLI args)

**Comment by aothms** [comment]
I would say it's more or less the exact same code being called, no difference

**Comment by Moult** [comment]
That's really great to hear :) I'll write some docs about this and close this bug.
