### ISSUE TITLE
Segfault on walls (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#411]
**Steps to reproduce:**
1. Convert [411--walls--segfault--accept-errors.ifc](https://github.com/IfcOpenShell/files/blob/master/411--walls--segfault--accept-errors.ifc) with 5359e88 (OCCT 7.3.0 or 7.2.0)
2. Experience segfault:
```FATAL: An error occured, status code 139.``` 
3. File opens without warnings in DDS, SimpleBIM and Solibri:
<img width="250" alt="screen shot 2018-07-11 at 23 35 49" src="https://user-images.githubusercontent.com/4601554/42600888-3c1b9530-8564-11e8-8eeb-2ffd158ae040.png">

**Comment by aothms** [comment]
The openings on these walls are a bit odd.

![2018-09-19 1](https://user-images.githubusercontent.com/1096535/45760927-7bb6e700-bc2b-11e8-9169-0f503a10d450.png)

I actually managed to prevent the segfault by filtering the boolean operands first by means of a bounding box overlap. Which is a bit surprising, but apparently a good addition in general. Could be that this just hides the underlying issue though.

**Comment by johanrd** [comment]
Hehe, yes. I can verify that 622853d fixes this, and that general testing hat not indicated any regressions 🎉

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
