### ISSUE TITLE
Orthographic Scale not changing 

### ISSUE THREAD

**Issue by aaronsgithub** [IfcOpenShell/IfcOpenShell#4113]
I'm using v0.0.231104 and I'm following along with the a tutorial by IFC Architect here:  
https://youtu.be/tpQjRjB1wnU?si=ISgnZOM1cnWT7lsc&t=595

When I attempt to change the orthographic scale as shown in the video, it remains at 50 and I cannot seem to change it. No error is given.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/5004394/bbb6ae14-0165-4056-b293-a6cbf1d04c1d)

Not sure if this is a bug or if its something I'm doing wrong.

Any help would be appreciated.

I love this project.

If anyone can point me in the direction of any guidelines on how best to format issues and bug reports I'll be happy to try add more details.

**Comment by theoryshaw** [comment]
Welcome.
perhaps this? https://community.osarch.org/discussion/1834/

If relatively new to BB, would recommend asking questions on the https://community.osarch.org/ community.

**Comment by aaronsgithub** [comment]
Thanks!

Yep, I can control the camera in the active drawing panel so that solves my original problem.

I'll leave it to the members to decide if this issue should be closed. 

Perhaps some documentation could be added, or some feedback from the UI when the user tries to edit Orthographic Scale directly for a drawing camera.

Thank you for the forum link also!
