### ISSUE TITLE
ifcopenshell error reading file description if it's empty

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4119]
Noticed that opening files with empty header description in BlenderBIM produces error below. By empty description I mean `FILE_DESCRIPTION($,'2;1');` entity in the header.

```
  File "\blenderbim\bim\module\project\ui.py", line 101, in draw
    self.draw_project_ui(context)
  File "\blenderbim\bim\module\project\ui.py", line 199, in draw_project_ui
    mvd = "".join(IfcStore.get_file().wrapped_data.header.file_description.description)
  File "\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4215, in description
    return _ifcopenshell_wrapper.FileDescription_description(self, *args)
RuntimeError: Argument is not a list of strings
```

Can be reproduced with code:
```python
import ifcopenshell
ifc_file = ifcopenshell.open(filepath)
print(ifc_file.wrapped_data.header.file_description.description)
```

Found it opening file from sample models (https://github.com/buildingSMART/IFC4.3.x-sample-models/issues/11). Just wanted to put it out there - not sure if it actually needs a fix since IFC standard requires description not to be empty.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/e358fd37-f51a-4647-a898-95d4cd71cd88)

**Comment by aothms** [comment]
I worked so hard on getting these sample models in good shape, still invalid on the 3rd line already 😢

Would you be so kind to submit a PR to the sample files repo to fix those files? Just an empty string is fine I guess.

It's an exception that can be caught. If it's not too intrusive in the code, you can just try catch it maybe in a fairly high level and alert the user something general like 'error parsing header'.

**Comment by Andrej730** [comment]
Sure, submitted a PR to solve this issue in sample models. I guess we can keep this case unhandled in BBIM since we don't know any other sources that can produce .ifc with this kind of issue.

Another thought - should `ifcopenshell.validate.validate` catch errors in header? Since there is a express specification for the entities in the file header, then maybe it can help catch similar errors in .ifc models.

**Comment by aothms** [comment]
> Another thought - should ifcopenshell.validate.validate catch errors in header? Since there is a express specification for the entities in the file header, then maybe it can help catch similar errors in .ifc models.

I think we have it on the roadmap somewhere...
