### ISSUE TITLE
IfcOpenShell Installation on windows

### ISSUE THREAD

**Issue by Pravesh-Jamgade** [IfcOpenShell/IfcOpenShell#412]
I am trying to install IfcOpenShell on windows platform.I needed IfcOpenShell for running with another project and the author of the other project suggested to use IfcOpenShell-0.4.
I have successfully configure the cmake .But facing problem while building in Visual Studio.
Errors are related to standard libraries of windows and library linking problem.
**I am using Windows 10, VS 2017,VS 2010,VS 2015 build tool (tried all of them),Windows SDK 10,Windows SDK 8.1.**
please guide me with building the application.
**Screenshot:**
![screenshot 13](https://user-images.githubusercontent.com/27573314/42570304-1d0ad6b6-8531-11e8-972c-a31f20b3bb92.png)

![screenshot 14](https://user-images.githubusercontent.com/27573314/42570608-1110c392-8532-11e8-83e8-4fac7eee4abb.png)

**Comment by aothms** [comment]
Hi,

The last commit in the 0.4 branch is over three years old / 821 commits behind. I would recommend against using that. These issues however are related to updates in boost and might be fairly easy to resolve. You might want to add this [1] to the CMakeLists file and see if the situation improves.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L505

Kind regards,
Thomas

**Comment by Pravesh-Jamgade** [comment]
I tried with the above link and configure the cmake correctly but it has given few warnings in Cmake:
![screenshot 16](https://user-images.githubusercontent.com/27573314/42614758-dd75a55a-85c4-11e8-940b-39fe18fabac6.png)
While building with VS2010 and VS2017,it gave me following errors:
![screenshot 17](https://user-images.githubusercontent.com/27573314/42614990-d92c80c6-85c5-11e8-9dfd-729b72332f1e.png)

**Comment by aothms** [comment]
I meant to only add the `add_definitions(-DBOOST_OPTIONAL_USE_OLD_DEFINITION_OF_NONE)` to the old 0.4 version of CMakeLists.txt.

Hope that helps,

**Comment by Pravesh-Jamgade** [comment]
hey I added the line in cmake.
Got the cmake configuration and here the build result in VS2017:
![screenshot 20](https://user-images.githubusercontent.com/27573314/42803897-fc8284aa-89c4-11e8-8ef1-f58650467435.png)
There are few Link error(LNK1104).What do you think of it?

**Comment by Stinkfist0** [comment]
This should help: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/cmake/CMakeLists.txt#L392

**Comment by Pravesh-Jamgade** [comment]
@Stinkfist0 it did work for me.
But it now arise with LNK1104 for python.lib  and boost lib.
![screenshot 21](https://user-images.githubusercontent.com/27573314/42867878-6ff6236e-8a8e-11e8-84e4-1ed617f4d50b.png)

**Comment by Pravesh-Jamgade** [comment]
Hello,
cmake is asking for linking directory.
Here's the warning message:

> WARNING: Target "IfcConvert" requests linking to directory "D:/boost_1_67_0/boost/program_options/".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "IfcConvert" requests linking to directory "D:/boost_1_67_0/boost/program_options/".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "IfcConvert" requests linking to directory "D:/boost_1_67_0/boost/program_options/".  Targets may link only to libraries.  CMake is dropping the item.
> WARNING: Target "IfcConvert" requests linking to directory "D:/boost_1_67_0/boost/program_options/".  Targets may link only to libraries.  CMake is dropping the item.

I tried it giving the requested directory(using link_directory command in cmake file) path but still not working.

**Comment by Stinkfist0** [comment]
Sorry, but 0.4.0 branch is so old I cannot bother to look into these in more detail. I'd recommend using the master (0.5.0) or 0.6.0 branches.

**Comment by Pravesh-Jamgade** [comment]
I build it successfully.
I did search for the libraries , the cmake was looking for and then I gave it to target_link_library() for the  respective project .
Thanks @Stinkfist0 and @aothms .
