### ISSUE TITLE
Costing and Scheduling UI bug?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4132]
I cannot do anything in this UI, it is not showing everything. I use the daily build on the latest Blender version 4.0.2.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/92f7946a-42ee-48c3-b439-d14dd5c7c5fe)

It is supposed to show like this:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/a3740eeb-5247-4615-90c3-0a907c612843)

**Comment by BIMvoice** [comment]
I think I know why.... IFC2x3.

**Comment by myoualid** [comment]
Indeed ! You'd need to upgrade to IFC4.
