### ISSUE TITLE
How can I change the color of one entity in an ifc file?

### ISSUE THREAD

**Issue by noamdor1** [IfcOpenShell/IfcOpenShell#4133]
Im trying to change the color of an entity

**Comment by theoryshaw** [comment]
Via BlenderBIM UI, or using code?

**Comment by noamdor1** [comment]
using code

**Comment by Andrej730** [comment]
@noamdor1 you'll need to create surface style and assign it to the representation or it's items, here's the example - https://blenderbim.org/docs-python/autoapi/ifcopenshell/api/style/assign_material_style/index.html
