### ISSUE TITLE
Installation fails - AWS Lambda

### ISSUE THREAD

**Issue by vcarrasc** [IfcOpenShell/IfcOpenShell#4136]
Hi,

I'm trying to follow the installation steps for Ifcopenshell for[ AWS lambdas](https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#aws-lambda) but when running the command for the docker file in  `IfcOpenShell/Dockerfile`

```
docker build -t lambda-ifcopenshell .
```

The error below occurs. I wonder if you know the location of the `*.deb` files that are needed for building Ifcopenshell.

```
#11 [7/7] RUN dpkg -i /home/IfcOpenShell/*.deb
#11 0.242 dpkg: error: cannot access archive '/home/IfcOpenShell/*.deb': No such file or directory
#11 ERROR: process "/bin/sh -c dpkg -i /home/IfcOpenShell/*.deb" did not complete successfully: exit code: 2
------
 > [7/7] RUN dpkg -i /home/IfcOpenShell/*.deb:
0.242 dpkg: error: cannot access archive '/home/IfcOpenShell/*.deb': No such file or directory
------
Dockerfile:35
--------------------
  33 |     COPY . /home/IfcOpenShell/
  34 |     RUN ls -lrtR /home/IfcOpenShell
  35 | >>> RUN dpkg -i /home/IfcOpenShell/*.deb
  36 |
  37 |     USER IfcOpenShell
--------------------
ERROR: failed to solve: process "/bin/sh -c dpkg -i /home/IfcOpenShell/*.deb" did not complete successfully: exit code: 2
```

Does anyone know how to fix this?

**Comment by aothms** [comment]
Do you have the right dockerfile? I don't see anything regarding .deb in the aws one. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/aws/lambda/Dockerfile If there are bits in the docs that are unclear, a PR to improve would be highly appreciated.

**Comment by vcarrasc** [comment]
@aothms thanks for your reply. 
I'm using this file -> [https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/Dockerfile](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/Dockerfile) is it the wrong one? I'm trying to run it in my local.

**Comment by aothms** [comment]
See above message for the link to the dockerfile in `aws/lambda/Dockerfile`
