### ISSUE TITLE
Problem running ifcopenshell in Docker container for AWS Lambda

### ISSUE THREAD

**Issue by CodingAudrey2** [IfcOpenShell/IfcOpenShell#4142]
I'm trying to follow the example here (https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/aws/lambda/Dockerfile), but when I try to import ifcopenshell, this happens: 

Traceback (most recent call last):
  File "/var/task/ifcopenshell/__init__.py", line 61, in <module>
    from . import ifcopenshell_wrapper
  File "/var/task/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: /var/task/ifcopenshell/_ifcopenshell_wrapper.so: cannot open shared object file: No such file or directory

I have confirmed that that file is definitely present.

**Comment by aothms** [comment]
I can't reproduce this. Maybe clean and try again?

What I did:

```bash
git clone https://github.com/IfcOpenShell/IfcOpenShell
cd IfcOpenShell/aws/lambda/
docker build .
```

and that succeeded just fine, I added a line to test whether the module could be imported:

```
diff --git a/aws/lambda/Dockerfile b/aws/lambda/Dockerfile
index fcffa1e87..fe64d754c 100644
--- a/aws/lambda/Dockerfile
+++ b/aws/lambda/Dockerfile
@@ -31,6 +31,8 @@ COPY ./example_handler ${FUNCTION_DIR}/example_handler
 # Set the working directory
 WORKDIR ${FUNCTION_DIR}

+RUN /usr/local/bin/python -c 'import ifcopenshell'
+
 # Set the entrypoint for the Lambda function
 ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
```

**Comment by CodingAudrey2** [comment]
The issue persists on my Mac, but I've gotten it to work on Linux and Windows.
