### ISSUE TITLE
IfcTester - propertySet restriction in Property facet 

### ISSUE THREAD

**Issue by isma3lMB** [IfcOpenShell/IfcOpenShell#4143]
Complete wild cards (**.*** or **.+**) on Pset/Qset name don't seem to be handled 

``` xml
...
<propertySet>
    <xs:restriction base="xs:string">
        <xs:pattern value=".+" />
    </xs:restriction>
</propertySet>
...
```

**Comment by Andrej730** [comment]
@isma3lMB Hello! Can you please share small .ids + .ifc example to reproduce the issue?

**Comment by isma3lMB** [comment]
Hi @Andrej730,

Here are some sample files 

[property_facet_pset_name_sample.ifc](https://github.com/isma3lMB/BSI_IDS_TESTS/blob/main/property_facet_pset_name_sample.ifc)

[fail-property_facet_pset_name_complete_wildcard.ids](https://github.com/isma3lMB/BSI_IDS_TESTS/blob/main/fail-property_facet_pset_name_complete_wildcard.ids)

[pass-property_facet_pset_name_partial_patern.ids](https://github.com/isma3lMB/BSI_IDS_TESTS/blob/main/pass-property_facet_pset_name_partial_patern.ids)

**Comment by Andrej730** [comment]
@isma3lMB thank you for the provided examples. 

In this IDS pattern `T.+` it means "all psets starting with `T` should have property `BIM_LOT`.
If we change pattern to `.+`, doesn't it mean that the requirement now is "all psets with any name should have property `BIM_LOT`? Since `.+` now also matches `Foo` pset and it doesn't have `BIM_LOT` property and it fails as intended.

```xml
<ids xmlns="http://standards.buildingsmart.org/IDS" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS/ids_05.xsd">
    <info>
        <title>Matching property in any property sets</title>
    </info>
    <specifications>
        <specification name="Matching property in any property sets" ifcVersion="IFC2X3 IFC4" minOccurs="1" maxOccurs="unbounded">
            <applicability>
                <entity>
                    <name>
                        <simpleValue>IFCWALLSTANDARDCASE</simpleValue>
                    </name>
                </entity>
            </applicability>
            <requirements>
                <property datatype="IfcLabel" minOccurs="1" maxOccurs="1">
                    <propertySet>
                        <xs:restriction base="xs:string">
                            <xs:pattern value=".+" />
                        </xs:restriction>
                    </propertySet>
                    <name>
                        <simpleValue>BIM_LOT</simpleValue>
                    </name>
                </property>
            </requirements>
        </specification>
    </specifications>
</ids>
```

**Comment by isma3lMB** [comment]
@Andrej730 thx for the clarification.

This is indeed the expected behavior according the [all-matching-property-sets-must-satisfy-requirements](https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-property.md#fail-all-matching-property-sets-must-satisfy-requirements-23) testcase.

Does this mean that requiring a property regardless of the property set (`BIM_LOT` in `any` property set) is not supported ?

**Comment by aothms** [comment]
> Does this mean that requiring a property regardless of the property set (BIM_LOT in any property set) is not supported ?

It seems so, according to the current schema. https://github.com/buildingSMART/IDS/blob/master/Development/ids.xsd#L70 Default value for minoccurs equals 1.  I guess the reasoning is that allowing a value in an unspecified property set makes it hard to actually locate the information in downstream applications (that's the goal after all), it's potentially also confusing when such property occurs in multiple property sets with potentially conflicting values.

**Comment by isma3lMB** [comment]
Ok that makes sense !
