### ISSUE TITLE
Opening geometry

### ISSUE THREAD

**Issue by expertegorov** [IfcOpenShell/IfcOpenShell#4148]
Greetings. Looks like there's some kind of geometry error.
Wall with IfcOpeningElement in BlenderBIM:
![01](https://github.com/IfcOpenShell/IfcOpenShell/assets/123471482/ad7a2cc4-79bf-421c-8f84-ce8f20ef778d)
![02](https://github.com/IfcOpenShell/IfcOpenShell/assets/123471482/6550d3a7-cbc8-4d2e-b551-08809ec57d99)
Wall with IfcOpeningElement in BIMcollab ZOOM:
![03](https://github.com/IfcOpenShell/IfcOpenShell/assets/123471482/55326edf-1caf-4a90-ba5e-69455f49ed58)
![04](https://github.com/IfcOpenShell/IfcOpenShell/assets/123471482/deb8089c-afb1-496a-8dbc-217b08deede9)
IFC file:
[Opening.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13773059/Opening.zip)

**Comment by aothms** [comment]
The file you attached has that failed opening subtraction as the wall geometry in the file. I don't know how much you speak the details of IFC, but if you look at the content, the wall geometry is this:

```
#34819=IFCINDEXEDPOLYGONALFACEWITHVOIDS((3,4,1,2),((8,5,6,7),(10,11,12,9)));
#34824=IFCINDEXEDPOLYGONALFACE((24,23,9,12));
#34826=IFCINDEXEDPOLYGONALFACE((25,24,12,11));
#34828=IFCINDEXEDPOLYGONALFACE((2,1,13,18,17,16));
#34830=IFCINDEXEDPOLYGONALFACE((3,2,16,15));
#34832=IFCINDEXEDPOLYGONALFACE((26,25,11,10));
#34834=IFCINDEXEDPOLYGONALFACE((13,1,4,14));
#34836=IFCINDEXEDPOLYGONALFACE((4,3,15,14));
#34838=IFCINDEXEDPOLYGONALFACE((23,26,10,9));
#34840=IFCINDEXEDPOLYGONALFACE((20,19,5,8));
#34842=IFCINDEXEDPOLYGONALFACE((21,20,8,7));
#34844=IFCINDEXEDPOLYGONALFACE((22,21,7,6));
#34846=IFCINDEXEDPOLYGONALFACE((19,22,6,5));
#34848=IFCINDEXEDPOLYGONALFACEWITHVOIDS((14,15,16,17,18,13),((24,25,26),(20,21,22,19)));
#34853=IFCCARTESIANPOINTLIST3D(((0.,-99.9999999999984,0.),(6659.99999999993,-99.9999999999987,0.),(6659.99999999993,-99.9999999999987,2800.),(0.,-99.9999999999984,2800.),(5309.99999999997,-99.9999999999996,1615.),(5559.99999999997,-99.9999999999986,1615.),(5559.99999999997,-99.9999999999986,1365.),(5309.99999999997,-99.9999999999996,1365.),(4759.99999999995,-99.9999999999995,1615.),(5009.99999999995,-99.9999999999986,1615.),(5009.99999999995,-99.9999999999986,1365.),(4759.99999999995,-99.9999999999995,1365.),(0.,100.000000000002,0.),(0.,100.000000000002,2800.),(6659.99999999992,100.000000000001,2800.),(6659.99999999992,100.000000000001,0.),(5909.99999999994,100.000000000001,0.),(5709.99999999994,100.000000000002,0.),(5309.99999999997,100.,1615.),(5309.99999999997,100.,1365.),(5559.99999999997,100.000000000001,1365.),(5559.99999999997,100.000000000001,1615.),(4759.99999999995,100.,1615.),(4759.99999999995,100.,1365.),(5009.99999999995,100.000000000001,1365.),(5009.99999999995,100.000000000001,1615.)));
#34881=IFCPOLYGONALFACESET(#34853,.T.,(#34819,#34824,#34826,#34828,#34830,#34832,#34834,#34836,#34838,#34840,#34842,#34844,#34846,#34848),$);
```

without going into two much details, you can already see that there are two IFCINDEXEDPOLYGONALFACEWITHVOIDS with two inner bounds, which is exactly the geometry you visualized. If you visualize the points and edges you get:

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/03f0ca4f-ed72-44df-b8f1-005f397fa459)

In a non-referenceview IFC you expect the wall geometry itself to be unaltered, but rather the subtractions imposed as openings.

So I think something went wrong here in creating the model. How did you obtain that wall representation?

**Comment by theoryshaw** [comment]
Looks like you might have changed the 'OffsetFromReferenceLine', but did not regen (shift+g) the model afterword.

Would probably be good to tweak the code to regen automatically after the 'OffsetFromReferenceLine' is changed.

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/838d01e9-187f-4daa-b533-4d6a3257c605

**Comment by Andrej730** [comment]
And another problem is that when you import .ifc with that wall it's different from when you import it and regenerate it, though no changes were made.

**Comment by expertegorov** [comment]
Thanks everyone!
This is not my model. I don't know how it was created. It looks like this is a special model. Only this model has many problems with openings. IfсСlash finds many false intersections. I decided to report this here, because other programs do not have this problem.
BBIM:
![05](https://github.com/IfcOpenShell/IfcOpenShell/assets/123471482/e432e10e-365b-4bff-b343-8c0cc645e3f1)
![06](https://github.com/IfcOpenShell/IfcOpenShell/assets/123471482/884d7994-f911-427c-a6cc-6d9bfb500a02)
BIMvision:
![07](https://github.com/IfcOpenShell/IfcOpenShell/assets/123471482/756fc9f5-dfb9-4e29-af4e-c174ec5203d7)
Open IFC Viewer:
![08](https://github.com/IfcOpenShell/IfcOpenShell/assets/123471482/7d4142fb-0068-4bb9-9eba-b00d86a6eefd)

**Comment by Moult** [comment]
I'd agree that this seems to be a problem in the software creating the geometry, creating really weird geometry such that the boolean operations fail. There isn't much we can do I suspect because the raw data is messed up. Other viewers probably are mesh based and are more lenient, but this problem will still manifest elsewhere (e.g. in quantity take off data, the gross vs net will be wrong).

I also agree that the original software did not correctly implement OffsetFromReferenceLine. They need to have -100, not +100.

The reason regen can fix it is because it does still define all the material layer set parameters so we can recreate the "correct" wall geometry (i.e. without openings, and with the offset properly interpreted).

I wonder if this model was created with a much older version of BBIM because I know there was a time when we didn't implement OffsetFromReferenceLine and we dealt with opening voids in a bad way. In any case these should be fixed now (as shown by regen).
