### ISSUE TITLE
BB should not show unexisting property

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#4153]
When opening the attached small (and admittedly unusual) IFC file, BB displays a property set with the property "IsExternal", which does not exist in the file.
In the file, however, there is a Pset_WallCommon with the property but a different value.

[awrhhi02a-03-xx.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13794338/awrhhi02a-03-xx.ifc.zip)

Here a screenshot from v0.0.231104

![Screenshot 2023-12-29 15 28](https://github.com/IfcOpenShell/IfcOpenShell/assets/1941141/c3236c69-f613-45be-bb72-fec7487fd7fa)

**Comment by theoryshaw** [comment]
>  BB displays a property set with the property "IsExternal", which does not exist in the file.

I seems like it's in the file. 

```
#147 = IFCRELDEFINESBYPROPERTIES('0e7n5KzQnMghauaYOrrMuQ', #25, 'Object to Properties', $, (#43), #148);
  /*#43 = IFCWALL('0ydpqwkk4Hvw46051MdJZb', #25, 'WandInstanz', $, $, #12, #42, '3c9f3d3a-bae1-11e7-a106-0050569d38e5', .NOTDEFINED.);*/
  /*#148 = IFCPROPERTYSET('0sVLpeU2zLA8HXVyOYNU_7', #25, 'Pset_DoorCommon', $, (#149));*/
    /*#149 = IFCPROPERTYSINGLEVALUE('IsExternal', $, IFCBOOLEAN(.F.), $);*/
```

**Comment by kurb70** [comment]
What a shame. You are absolutely right. I was so sure it was not in the file. I must have been looking for something else. Thank you.
