### ISSUE TITLE
Bugs in express.parse() and file.create_entity() methods

### ISSUE THREAD

**Issue by protectione055** [IfcOpenShell/IfcOpenShell#4159]
## Description
I am trying to convert IFC to tables in a relational database, and I need to get the entity names, attribute names, and attribute types of all entities. I tried to use the `parse()` method in `ifcopenshell.express` to parse `IFC4.exp`, but I get a "pointer double free error" after running for a while. I suspect that there is a problem with some C++ code. 

I can't solve this problem, so I'm trying another method: 
1. Read all ENTITY NAME from IFC4.exp 
2. Create an empty model 
3. Use the `create_entity()` method to create an instance for each ENTITY 
4.  Read attribute information from the instance.

While trying this method, I encountered another problem. Some ENTITY always fail to be created, and the error message shows that the `entity_instance.py` module has thrown a `RecursionError`. 

Is there a way to solve this problem, or are there other alternative solutions to read all ENTITY information from the IFC schema? Thanks.

## Environment
* Python 3.9.18
* ifcopenshell==0.7.0.231218
* Ubuntu 22.04 jammy
* Intel Core i9-10900X @ 20x 4.5GHz

## ERROR Message

```text
ERROR when compiling IfcLoop...
An unknown error occurred
Exception ignored in: <function entity_instance.__del__ at 0x7f4c6ad504c0>
Traceback (most recent call last):
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 135, in __del__
    self.wrapped_data.file = None
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 146, in __getattr__
    attr_cat = self.wrapped_data.get_attribute_category(name)
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 146, in __getattr__
    attr_cat = self.wrapped_data.get_attribute_category(name)
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 146, in __getattr__
    attr_cat = self.wrapped_data.get_attribute_category(name)
  [Previous line repeated 993 more times]
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 145, in __getattr__
    INVALID, FORWARD, INVERSE = range(3)
RecursionError: maximum recursion depth exceeded in comparison

Successfully compiled 745 entities.
Failed to compile 21 entities.
Failed entities: ['IfcBoundedCurve', 'IfcBoundedSurface', 'IfcCartesianPointList', 'IfcConnectionGeometry', 'IfcCurve', 'IfcExternalInformation', 'IfcGeometricRepresentationItem', 'IfcLoop', 'IfcMaterialDefinition', 'IfcMaterialUsageDefinition', 'IfcObjectPlacement', 'IfcPoint', 'IfcPreDefinedProperties', 'IfcPresentationItem', 'IfcPropertyAbstraction', 'IfcRepresentationItem', 'IfcSolidModel', 'IfcSurface', 'IfcTessellatedItem', 'IfcTopologicalRepresentationItem', 'IfcVertex']
```

## My Code

```python
            with open(exp_file, 'r') as f:
                ifc_classes = []
                regex = re.compile(r'ENTITY\s+(\w+);?')
                for line in f:
                    match = regex.match(line)
                    if match:
                        ifc_classes.append(match.group(1))
                
                create_sql = []
                failed_classes = []
                ifc_model = ifcopenshell.file()
                result_path = f"create_table_{os.path.basename(exp_file).split('.')[0]}.sql"
                if os.path.exists(result_path):
                    os.remove(result_path)
                with open(result_path, 'a') as r:
                    for ifc_class in ifc_classes:
                        try:
                            entity = ifc_model.create_entity(ifc_class)
                            create_sql.append(self.__get_create_table_sql(entity))
                            r.write(create_sql[-1] + '\n')
                        except Exception as e:
                            failed_classes.append(ifc_class)
                            print(f"ERROR when compiling {ifc_class}...")
                            print(e)
                    print(f"Successfully compiled {len(create_sql)} entities.")
                    print(f"Failed to compile {len(failed_classes)} entities.")
                    print(f"Failed entities: {failed_classes}")
```

**Comment by aothms** [comment]
There is a lot to digest in your post, but I think the most useful answer is that IfcOpenShell does have all schema information in a latebound fashion. It just never really got neatly exposed and documented. It's currently only available by interfacing with the binary wrapper module directly:

```
>>> import ifcopenshell
>>> w = ifcopenshell.ifcopenshell_wrapper
>>> s = w.schema_by_name('IFC4')
'IfcActionRequest'
>>> print(s.entities()[0].all_attributes())
(<attribute GlobalId: <type IfcGloballyUniqueId: <string>>>, <attribute OwnerHistory?: <entity IfcOwnerHistory>>, <attribute Name?: <type IfcLabel: <string>>>, <attribute Description?: <type IfcText: <string>>>, <attribute ObjectType?: <type IfcLabel: <string>>>, <attribute Identification?: <type IfcIdentifier: <string>>>, <attribute PredefinedType?: <enumeration IfcActionRequestTypeEnum: (EMAIL, FAX, NOTDEFINED, PHONE, POST, USERDEFINED, VERBAL)>>, <attribute Status?: <type IfcLabel: <string>>>, <attribute LongDescription?: <type IfcText: <string>>>)
```

**Comment by protectione055** [comment]
> There is a lot to digest in your post, but I think the most useful answer is that IfcOpenShell does have all schema information in a latebound fashion. It just never really got neatly exposed and documented. It's currently only available by interfacing with the binary wrapper module directly:
> 
> ```
> >>> import ifcopenshell
> >>> w = ifcopenshell.ifcopenshell_wrapper
> >>> s = w.schema_by_name('IFC4')
> 'IfcActionRequest'
> >>> print(s.entities()[0].all_attributes())
> (<attribute GlobalId: <type IfcGloballyUniqueId: <string>>>, <attribute OwnerHistory?: <entity IfcOwnerHistory>>, <attribute Name?: <type IfcLabel: <string>>>, <attribute Description?: <type IfcText: <string>>>, <attribute ObjectType?: <type IfcLabel: <string>>>, <attribute Identification?: <type IfcIdentifier: <string>>>, <attribute PredefinedType?: <enumeration IfcActionRequestTypeEnum: (EMAIL, FAX, NOTDEFINED, PHONE, POST, USERDEFINED, VERBAL)>>, <attribute Status?: <type IfcLabel: <string>>>, <attribute LongDescription?: <type IfcText: <string>>>)
> ```

Thank you very much! This is exactly what I need. 

Sorry for posting the  code, here is the simplified version:

```python
ifc_model = ifcopenshell.file()
entity_names = ['IfcActionRequest', ...]
for ifc_class in entity_names:
    entity = ifc_model.create_entity(ifc_class)
    # or
   from ifcopenshell.api import run 
   entity = run("root.create_entity", ifc_model, ifc_class=ifc_class)
```

Here is what I really did, and this issue occurs under both invocation methods.

My problem has been resolved, thank you for the tools you have developed, this issue can be closed at any time.

**Comment by Andrej730** [comment]
@protectione055 on what ifc classes the error below occurred? Or it was some invalid class names?
```python
Traceback (most recent call last):
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 135, in __del__
    self.wrapped_data.file = None
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 146, in __getattr__
    attr_cat = self.wrapped_data.get_attribute_category(name)
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 146, in __getattr__
    attr_cat = self.wrapped_data.get_attribute_category(name)
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 146, in __getattr__
    attr_cat = self.wrapped_data.get_attribute_category(name)
  [Previous line repeated 993 more times]
  File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 145, in __getattr__
    INVALID, FORWARD, INVERSE = range(3)
RecursionError: maximum recursion depth exceeded in comparison
```

Reproduced it with the exact snippet below when it's trying to create an entity using invalid ifc class `...` (ellipsis).
```python
ifc_model = ifcopenshell.file()
entity_names = ['IfcActionRequest', ...]
for ifc_class in entity_names:
    entity = ifc_model.create_entity(ifc_class)
    # or
   from ifcopenshell.api import run 
   entity = run("root.create_entity", ifc_model, ifc_class=ifc_class)
```

---

As for failed entities like those:
```
Failed entities: ['IfcBoundedCurve', 'IfcBoundedSurface', 'IfcCartesianPointList', 'IfcConnectionGeometry', 'IfcCurve', 'IfcExternalInformation', 'IfcGeometricRepresentationItem', 'IfcLoop', 'IfcMaterialDefinition', 'IfcMaterialUsageDefinition', 'IfcObjectPlacement', 'IfcPoint', 'IfcPreDefinedProperties', 'IfcPresentationItem', 'IfcPropertyAbstraction', 'IfcRepresentationItem', 'IfcSolidModel', 'IfcSurface', 'IfcTessellatedItem', 'IfcTopologicalRepresentationItem', 'IfcVertex']
```

The error below indeed occurs but it makes sense since `root.create_entity` has `root.` prefix and this method is used to create only IfcRoot based entities (therefore it's failing trying to provide `OwnerHistory` and `GlobalId` to the entity when it's class doesn't have those attributes). Since `IfcBoundedCurve` and all other do not inherit from IfcRoot they cannot be instantiated with this method and can be created with `ifc_model.create_entity`.

```python
Traceback (most recent call last):
  File "\test_ifc.py", line 360, in <module>
    test_case()
  File "\test_ifc.py", line 357, in test_case
    entity = run("root.create_entity", ifc_model, ifc_class=ifc_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                             File "C:\Software\Python311\Lib\site-packages\ifcopenshell\api\root\create_entity.py", line 74, in execute                                                                                                                                                             element = self.file.create_entity(                                                                                                                                                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                 File "C:\Software\Python311\Lib\site-packages\ifcopenshell\file.py", line 337, in create_entity                                                                                                                                                                    
    e[idx] = arg
    ~^^^^^
  File "\ifcopenshell\entity_instance.py", line 259, in __setitem__
    method = self.method_list[idx]
             ~~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range
```

**Comment by protectione055** [comment]
> @protectione055 on what ifc classes the error below occurred? Or it was some invalid class names?
> 
> ```python
> Traceback (most recent call last):
>   File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 135, in __del__
>     self.wrapped_data.file = None
>   File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 146, in __getattr__
>     attr_cat = self.wrapped_data.get_attribute_category(name)
>   File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 146, in __getattr__
>     attr_cat = self.wrapped_data.get_attribute_category(name)
>   File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 146, in __getattr__
>     attr_cat = self.wrapped_data.get_attribute_category(name)
>   [Previous line repeated 993 more times]
>   File "/home/zzm/miniconda3/envs/ifc-test/lib/python3.9/site-packages/ifcopenshell/entity_instance.py", line 145, in __getattr__
>     INVALID, FORWARD, INVERSE = range(3)
> RecursionError: maximum recursion depth exceeded in comparison
> ```
> 
> Reproduced it with the exact snippet below when it's trying to create an entity using invalid ifc class `...` (ellipsis).
> 
> ```python
> ifc_model = ifcopenshell.file()
> entity_names = ['IfcActionRequest', ...]
> for ifc_class in entity_names:
>     entity = ifc_model.create_entity(ifc_class)
>     # or
>    from ifcopenshell.api import run 
>    entity = run("root.create_entity", ifc_model, ifc_class=ifc_class)
> ```
> 
> As for failed entities like those:
> 
> ```
> Failed entities: ['IfcBoundedCurve', 'IfcBoundedSurface', 'IfcCartesianPointList', 'IfcConnectionGeometry', 'IfcCurve', 'IfcExternalInformation', 'IfcGeometricRepresentationItem', 'IfcLoop', 'IfcMaterialDefinition', 'IfcMaterialUsageDefinition', 'IfcObjectPlacement', 'IfcPoint', 'IfcPreDefinedProperties', 'IfcPresentationItem', 'IfcPropertyAbstraction', 'IfcRepresentationItem', 'IfcSolidModel', 'IfcSurface', 'IfcTessellatedItem', 'IfcTopologicalRepresentationItem', 'IfcVertex']
> ```
> 
> The error below indeed occurs but it makes sense since `root.create_entity` has `root.` prefix and this method is used to create only IfcRoot based entities (therefore it's failing trying to provide `OwnerHistory` and `GlobalId` to the entity when it's class doesn't have those attributes). Since `IfcBoundedCurve` and all other do not inherit from IfcRoot they cannot be instantiated with this method and can be created with `ifc_model.create_entity`.
> 
> ```python
> Traceback (most recent call last):
>   File "\test_ifc.py", line 360, in <module>
>     test_case()
>   File "\test_ifc.py", line 357, in test_case
>     entity = run("root.create_entity", ifc_model, ifc_class=ifc_class)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "\ifcopenshell\api\__init__.py", line 66, in run
>     result = usecase_class(ifc_file, **settings).execute()
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                             File "C:\Software\Python311\Lib\site-packages\ifcopenshell\api\root\create_entity.py", line 74, in execute                                                                                                                                                             element = self.file.create_entity(                                                                                                                                                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                 File "C:\Software\Python311\Lib\site-packages\ifcopenshell\file.py", line 337, in create_entity                                                                                                                                                                    
>     e[idx] = arg
>     ~^^^^^
>   File "\ifcopenshell\entity_instance.py", line 259, in __setitem__
>     method = self.method_list[idx]
>              ~~~~~~~~~~~~~~~~^^^^^
> IndexError: list index out of range
> ```

Yes, I made a mistake. The Python api documentation has stated that root.create_entity creates entities that inherit from ifcroot, which I am misusing here. Thanks for your reply.
