### ISSUE TITLE
Error when adding Blenderbim addon

### ISSUE THREAD

**Issue by js855** [IfcOpenShell/IfcOpenShell#4164]
Hello everyone,
Could you please help with this issue I experience when adding the latest blenderbim addon (blenderbim-231228-py310-linux) to Blender 3.41 under the latest Debian 12 fully up to date?
![screen1](https://github.com/IfcOpenShell/IfcOpenShell/assets/155461569/d197d6d5-e392-4023-a708-b011bae4101a)
![screen2](https://github.com/IfcOpenShell/IfcOpenShell/assets/155461569/2e920a0e-c217-413d-a453-51c17ab133c6)
![screen3](https://github.com/IfcOpenShell/IfcOpenShell/assets/155461569/a24af0be-70d8-4fb6-ad84-24d2661c9a3b)

**Comment by CyrilWaechter** [comment]
@js855 Can you check python version in script tab please ?

**Comment by js855** [comment]
Thanks for the answer.
PYTHON INTERACTIVE CONSOLE 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Should I downgrade do 3.10?

**Comment by CyrilWaechter** [comment]
@js855 No, we need to add 3.11 to blenderbim releases. I am working on it.

**Comment by js855** [comment]
That's great, I am looking forward to give it a try. Thank you for help.

**Comment by js855** [comment]
This version is loading up with no errors now. Many thanks.
