### ISSUE TITLE
IfcRelSpaceBoundary: Prevent creation of overlapping or already existing boundaries

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#4173]
Following work on 64c711a02a00de47aca47e89b867d80bb8b4885f it is now possible to create almost all boundaries by selecting an `IfcBuildingStorey` collection and an `IfcSpace` but it also creates more than wanted. eg. footprint of a wall on space slab side face. I wonder what would be the best solution to avoid that.
![Screenshot_20240103_163050](https://github.com/IfcOpenShell/IfcOpenShell/assets/9622862/43dbb1a7-80dc-4497-9343-18c01e89f1f0)
Also currently if you launch bim.add_boundary operator multiple time it recreates even existing ones. I wonder what's the best way to prevent that.

Also see meta issue for IfcRelSpaceBoundary #1676

**Comment by Moult** [comment]
Have you got a sample model / steps to reproduce? Sorry I've lost familiarity with how the boundary tools work and I tried to recreate it with an internal wall but couldn't get the same artefact that you're getting.

**Comment by CyrilWaechter** [comment]
# Steps to reproduce case 1 : extra unwanted boundaries created
1. Open [TestCase_TooMuchBoundaries.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13894763/TestCase_TooMuchBoundaries.zip)
2. Select the building storey
3. Select the space
4. Use `Add Boundary` in spatial tools
## Current result
3 unwanted boundaries created because currently when detecting building element it cast a ray from space face centroid so also bottom face of walls and side face of slabs are also detected.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9622862/4cb0ede9-b00e-472c-9017-2483c899198b)

# Steps to reproduce case 2 : already created boundaries are created again
1. Reproduce steps in case 1
## Current result
All boundaries are created again which means you have twice of each.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9622862/c6211053-5b9f-44b8-b153-4d5ecc7050d3)

**Comment by Moult** [comment]
For case 1, isn't the horizontal slab boundary correct? Doesn't IfcRelSpaceBoundary2ndLevel describe that you need a boundary whenever there is a change of material?

For the internal wall, I guess I can understand why a boundary shouldn't be created, if it is totally encompassed by the space.

**Comment by Moult** [comment]
OK I've thrown together a new approach. It no longer isolates checks to the current storey and also uses the geometry tree to check nearby possible relating elements. I suspect if this new approach is more successful, it can be built upon to then implement 2nd level boundaries (e.g. by projecting neighbouring spaces and boolean differentiating the remainder).

The code is pretty messy right now but I threw in a bunch of comments about the general approach and I haven't removed the old approach in case this attempt is even worse. Can you test on a bunch of models and let me know what you get?

**Comment by Moult** [comment]
Edit: this is only tackling problem 1 (and incomplete and horrible code and note to self I forgot to free the bmesh objects). The problem 2 about recreating existing boundaries still exists.
