### ISSUE TITLE
Made changes to a Type but it does not save

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4175]
Hi, I created a Type and changed the geometry before allocating it under "Edit Mode" but when the file is saved the goemetry change is not saved.

![Skermskoot (76)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/379f0010-ffee-43fd-8a3d-fc456622bd72)
Simple creation of a Type object.

![Skermskoot (77)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/5840ec33-c90b-4227-beed-61318c098e2c)
Allocateded new Type object into IFC Building and saved IFC file.

![Skermskoot (78)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/c38ef092-2df2-437f-99fc-966539ed00d8)
Opended IFC file and geomertry was not saved.

Attached is my IFC file

Thanks for your support, may 2024 be a great year.
[3bd hous.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13839171/3bd.hous.txt)

**Comment by Moult** [comment]
I can't recreate the issue. Can you be more specific in what steps you are doing?

**Comment by Andrej730** [comment]
@Ave-5D hi! 
Are you sure you're confirm saving the geometry exiting edit mode? 
The other possibility of the similar issue if you're switching to edit mode and back not with tab key but with viewport's mode menu.

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/022fc718-571c-4acd-a552-59778042a91d

**Comment by Ave-5D** [comment]
Hi Deon and Andre

I did not use the "tab" key but the screen edit/view port option. 
I did not get an option for saving the geometry when exiting edit mode?

I will try to be more specific in what steps I am doing. 
I did the editing under the type before adding it into the project/site/building.

**Comment by Andrej730** [comment]
> I did not use the "tab" key but the screen edit/view port option.

Then it's probably the issue as we currently don't handle switching from EDIT mode from the viewport menu. Can you please try to do it with Tab hotkey to see if it solves the issue for you?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/62312f97-0335-48a0-ac28-1c5f9c424b50)

**Comment by Moult** [comment]
We used to have a mode change handler, but over time I've found that it's less powerful than actually overriding the hotkey, and having a separate IFC UI to the built-in one makes it clear what is IFC functionality and what is Blender functionality (e.g. weight paint, vertex paint, etc). There is now a new mode dropdown on the top right.
