### ISSUE TITLE
BsDD baseURL

### ISSUE THREAD

**Issue by c-mellueh** [IfcOpenShell/IfcOpenShell#4184]
Hi,
why are we using "https://bs-dd-api-prototype.azurewebsites.net/" as baseurl and not "https://api.bsdd.buildingsmart.org/api/"?

**Comment by aothms** [comment]
Old version. Should be updated I guess. Feel free to send a PR, but not entirely sure if the API is 100% the same on those end points.

**Comment by c-mellueh** [comment]
ok. I checked the endpoints, they're not the same. I'll rework the bsDD and add the new calls + deprecation warnings to existing functions.
