### ISSUE TITLE
Custom pset templates in the `psets` folder are not available to assign

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4194]
It seems custom pset templates in the `psets` folder are not available to assign to an object/type.

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/281c0c55-ba42-4850-ba84-eb474e93c2c7

**Comment by Moult** [comment]
I can't recreate this. Are you sure that in the add-on preferences, the pset_dir is correct relative to your IFC location?

**Comment by theoryshaw** [comment]
Hm, i can't seem to anymore either.  Maybe it was a cache thing. 
Thanks.

**Comment by theoryshaw** [comment]
This seems to happen with a project where i'm syncing the .blend/.ifc files.  If I open the .ifc anew, they are made available again. 
Is there trick to not having to do this?
