### ISSUE TITLE
When `bim.build_schedule` would be nice if there was an option to turn off the `GlobalId` column. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4196]
When `bim.build_schedule` would be nice if there was an option to turn off the `GlobalId` column. 

I know about `row.prop(props, "include_global_id")`, this feature request is more to streamline steps. 

I might be able to code this up.

**Comment by Moult** [comment]
So I think the idea is now that you'd use IfcCSV to generate the schedule, and save the JSON settings wherever you want. The JSON settings now also remembers your settings like output format or include_global_id. There is also now a new setting to generate an SVG alongside the spreadsheet.

This means you can build your schedule as you re-export your spreadsheet.
