### ISSUE TITLE
Can't add a Schedule to a Sheet

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#4204]
I am looking for the correct workflow to put a schedule (Beam Schedule) on a sheet.

After failing miserably in the Costing and Scheduling tab, I found the Export IFC to XLSX in the Quality and Coordination tab and was successfully able to export a schedule. In the Drawings and Documents tab I was able to add my schedule from the XLSX file. I then tried to add the schedule to a sheet, however an error message said I first had to generate the schedule. So I clicked on Build Schedule but I got a KeyError message "There is no item named 'META-INF/manifest.xml' in the archive"

What am I doing wrong here?

**Comment by trhyder** [comment]
A workaround is to Export IFC to ODS.

The error remains with XLSX files and can be reproduced by adding BeamSchedulesXLSXTest.xlsx to Schedules in the Drawing and Documents tab.

[BeamScheduleTest.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13910792/BeamScheduleTest.zip)

**Comment by Moult** [comment]
You weren't doing anything wrong - we simply only had support for ODS :) Now we support XLSX too. It isn't completely feature parity with ODS (e.g. no print region support) but close enough and ready for battle testing.
