### ISSUE TITLE
using ifcconvert to export obj from ifc,the model rotation 90 degrees

### ISSUE THREAD

**Issue by 9lovingly** [IfcOpenShell/IfcOpenShell#421]
When I used ifcconvert to export obj from ifc，the model rotation 90 degrees.I don't know why,and I just input "ifcconvert.exe xxx.ifc" without any other parameter

**Comment by aothms** [comment]
90 degrees around which angle? The convention used in IfcOpenShell is that the Z-Axis is pointing upwards. Other modelling tools might use the Y-Axis as upwards, causing a -90 degree rotation around the X-Axis. Is that what you are describing?

Importing applications typically have settings to govern this, as the OBJ file (contrary to for example Collada) has no method of specifying which convention is used. There is no setting for this in IfcOpenShell, Z is always up (contributions are welcome to specify this behaviour from the command line)
