### ISSUE TITLE
Export IFC to ODS produces unexpected results

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#4210]
I have noticed two errors when exporting IFC to ODS.

The attached screenshot shows the BlenderBIM settings on the left, the export to XLSX in the middle, and the export to ODS on the right.

<img width="3248" alt="Screenshot 2024-01-13 at 10 06 07 AM" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/a1710787-f7bd-42f2-84a3-756c2d36bd5a">

I was expecting the exports to be identical. Instead, the XLSX appears correct but the ODS export has incorrect values.
The type.Name attribute appears to be showing the type.Description attribute, and the type.Description attribute appears not to show the full value.

**Comment by Moult** [comment]
Have you got a test file to replicate?

**Comment by Andrej730** [comment]
Couldn't reproduce this, need example .ifc + .blend or .ifc + .json with table export settings.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/7cd93466-9d7b-473e-ab5c-ea0896dcfcc9)

**Comment by trhyder** [comment]
I can't reproduce this again either. Maybe it has been fixed, or maybe it was a cache issue.
