### ISSUE TITLE
API Docu. Clarify contradictory statements about quantities association for types

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#4211]
If I understand correctly, there are two contradictory statements in the class documentation of https://github.com/IfcOpenShell/IfcOpenShell/blob/83d364574a8bf76e768d4c6c81a00274dc31cfe2/src/ifcopenshell-python/ifcopenshell/api/pset/add_qto.py 

`Products, such as physical objects or types in IFC may have quantities associated with them.`
versus
`Quantities can only be assigned to occurrences, not types.`

**Comment by Moult** [comment]
Yeah there was a bug upstream in IFC that lead to the understanding that bSI Qtos were only occurrence driven. This is no longer correct and I've backported the fix. See #3583.

Can you help submit a PR that removes the second sentence?
