### ISSUE TITLE
Drawing panel does not work

### ISSUE THREAD

**Issue by SavuGust27** [IfcOpenShell/IfcOpenShell#4213]
I have a second window with the properties panel and in scene tab in the BlenderBim interface.  i tried to create a drawing and it does only creates the camera and i cannot go to that view. Do the same thing inside the main window (how it normally is done) create a drawing and it works perfectly. So basically the drawing generator is nor working if you try to create it from a second window.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/148299517/e90d4de9-f929-4e2e-80be-bc1251ad25e3)

**Comment by Gorgious56** [comment]
Yup, the code checks if there is an open 3D viewport in the current screen, which in your case there is not. I think a solution is to iterate over `bpy.data.screens` and pick the first 3D view it finds. But there will always be corner cases like this since users can modify the UI as they wish.

**Comment by Moult** [comment]
@SavuGust27 / @Gorgious56 would either of you like to help do a PR?
