### ISSUE TITLE
IfcOpenShell Python 0.7.0 serialization not working

### ISSUE THREAD

**Issue by nickger** [IfcOpenShell/IfcOpenShell#4216]
I am trying to creare Ifc elements with geometries from OpenCascade. Tesselation works - corresponding Ifc Brep representation is ok, but I would like to avoid that because I need to process the geometry further and tesselation is not a good option. 
When I try using Serialize it returns None. Even the AdvancedHouse example does not work in Python. 

```python
from ifcopenshell import ifcopenshell_wrapper
from OCC.Core.gp import gp_Pnt
from OCC.Core.BRepPrimAPI import BRepPrimAPI_MakeBox
from OCC.Core.BRepAlgoAPI import BRepAlgoAPI_Cut

outer =   BRepPrimAPI_MakeBox(gp_Pnt(-5000., -180., -2000.), gp_Pnt(5000., 5180., 3000.)).Shape()
inner =   BRepPrimAPI_MakeBox(gp_Pnt(-4640.,  180.,     0.), gp_Pnt(4640., 4820., 3000.)).Shape()
window1 = BRepPrimAPI_MakeBox(gp_Pnt(-5000., -180.,   400.), gp_Pnt( 500., 1180., 2000.)).Shape()
window2 = BRepPrimAPI_MakeBox(gp_Pnt( 2070., -180.,   400.), gp_Pnt(3930.,  180., 2000.)).Shape()
building_shell = BRepAlgoAPI_Cut(
		BRepAlgoAPI_Cut(
			BRepAlgoAPI_Cut(outer, inner),
			window1
			),
		window2
	)
ifcgeom.main.serialise("IFC2X3", building_shell, False) #returns None
```

**Comment by Moult** [comment]
Don't know what the answer is, but grepping in the FreeCAD codebase shows me this: https://github.com/FreeCAD/FreeCAD/blob/fa0a25a777e7b5495afaa24ffd4c545b4d443351/src/Mod/Arch/exportIFC.py#L2163

**Comment by nickger** [comment]
Line 2172 doesn't work in this case. String representation of Brep Shape is not None, I've checked, but Ifc serialization doesn't work.

**Comment by Moult** [comment]
Ping @aothms

**Comment by aothms** [comment]
For me the following code works:

```python

import ifcopenshell
import ifcopenshell.geom

from OCC.Core.gp import gp_Pnt
from OCC.Core.BRepPrimAPI import BRepPrimAPI_MakeBox
from OCC.Core.BRepAlgoAPI import BRepAlgoAPI_Cut

outer =   BRepPrimAPI_MakeBox(gp_Pnt(-5000., -180., -2000.), gp_Pnt(5000., 5180., 3000.)).Shape()
inner =   BRepPrimAPI_MakeBox(gp_Pnt(-4640.,  180.,     0.), gp_Pnt(4640., 4820., 3000.)).Shape()
window1 = BRepPrimAPI_MakeBox(gp_Pnt(-5000., -180.,   400.), gp_Pnt( 500., 1180., 2000.)).Shape()
window2 = BRepPrimAPI_MakeBox(gp_Pnt( 2070., -180.,   400.), gp_Pnt(3930.,  180., 2000.)).Shape()
building_shell = BRepAlgoAPI_Cut(
		BRepAlgoAPI_Cut(
			BRepAlgoAPI_Cut(outer, inner).Shape(),
			window1
			).Shape(),
		window2
	).Shape()
    

f = ifcopenshell.file(schema='IFC2X3')
f.add(ifcopenshell.geom.serialise("IFC2X3", building_shell, False))

```

Which is the same, just added .Shape() to the boolean op calls to actually evaluate.

There are two thing you can try:

- serialize to ifc4 or higher. IFC2X3 is very limited with regard to curved surfaces. So as soon as anything non-planar is there it will give up on the 2x3 schema and return none.
- inspect the faces of the solid you're trying to serialize. I imagine there can be cases where OpenCASCADE decides to encode a planar surface as a 1-degree nurbs surface.

**Comment by nickger** [comment]
Oh, you are right, pretty stupid mistake... Unfortunately, it makes the problem even worse. In my code I use BOPAlgo_CellsBuilder() class, not Cut directly:

`def difference(sh1, sh2):
    shps = TopoDS_ListOfShape()
    shps.Append(sh1)
    shps.Append(sh2)
    cb = BOPAlgo_CellsBuilder()
    cb.SetArguments(shps)
    cb.SetFuzzyValue(0.005)
    cb.Perform()
    shps_to_add = TopoDS_ListOfShape()
    shps_to_add.Append(sh1)
    shps_to_avoid = TopoDS_ListOfShape()
    shps_to_avoid.Append(sh2)
    cb.AddToResult(shps_to_add, shps_to_avoid, 1, False)
    cb.RemoveInternalBoundaries()
    cb.MakeContainers()
    usd = ShapeUpgrade_UnifySameDomain(cb.Shape())
    usd.Build()
    result = usd.Shape()
    return result`

and in this case the code returns the result which cannot be serialized:

`outer = BRepPrimAPI_MakeBox(gp_Pnt(-5000., -180., -2000.), gp_Pnt(5000., 5180., 3000.)).Shape()
inner = BRepPrimAPI_MakeBox(gp_Pnt(-4640.,  180.,     0.), gp_Pnt(4640., 4820., 3000.)).Shape()
window1 = BRepPrimAPI_MakeBox(gp_Pnt(-5000., -180.,   400.), gp_Pnt(500., 1180., 2000.)).Shape()
window2 = BRepPrimAPI_MakeBox(gp_Pnt(2070., -180.,   400.), gp_Pnt(3930.,  180., 2000.)).Shape()
building_shell = geom_funcs.difference(
		geom_funcs.difference(
			geom_funcs.difference(outer, inner),
			window1
			),
		window2
	)
ifcgeom.main.serialise("IFC4", building_shell, True)  #still returns None as well as 2x3`

In the attachments are string representations from BRepTools_ShapeSet.WriteToString(), if it helps. Line-to-line comparison shows some differences but I have no idea how to interpret them. Would highly appreciate the help.
[CellsBuilder.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13948108/CellsBuilder.txt)
[Cut.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13948109/Cut.txt)

**Comment by nickger** [comment]
Aha... I see. Actually, particularly this shape is not a CompSolid, TopExp_Explorer returns an empty shape of that type, but it formally exists in the structure. But in general, are there other requirements to shapes? Manifold(ness)? Single-solid only? Self-touch? Anything else..?

**Comment by aothms** [comment]
In principle the OCCT data model is modelled closely off of STEP, which is also the foundation for the brep module in IFC, so at least conceptually there are very few issues.

**Comment by nickger** [comment]
Could you show me how to combine (concatenate) several solids into a single representation? I would like to keep explicit geometries for material layers in walls, so each solid should have its own material and a set of solids represent a wall.

**Comment by aothms** [comment]
> so each solid should have its own material 

It seems to me that if you want that you'd better not concatenate in the representation, but rather create an element level decomposition:

```
IfcWall <-- IfcRelAggregates -> IfcBuildingElementPart+ -> IfcProductDefinitionShape -> IfcShapeRepresentation -> ...
                                         ^
                                         |
                               IfcRelAssociatesMaterial
                                         |
                                         v
                                     IfcMaterial
```

Otherwise (untested):

```python

combined = None
for solid in solids:
    pdef = file.add(ifcgeom.main.serialise("IFC4", solid, True))
    if combined:
        combined.Representations[0].Items += pdef[0].Items
    else:
        combined = pdef

# @todo placement
file.createIfcWall(Representation=combined)
```

**Comment by nickger** [comment]
Good idea. Thank you so much.

**Comment by aothms** [comment]
I agree. It's a bit unfortunate as None is also a valid state for IfcProduct.Representation. Pull requests very welcome :)

**Comment by Moult** [comment]
Bump @nickger would you be interested in helping submit a PR to close this?

**Comment by nickger** [comment]
I am new to C++. As I see, this happens in Serialization.cpp lines 585-587. I can try, but cannot promise. 
BTW, line 602 about shells: the answer is no - shells are stored in order of creation, not their topological sense. So, the outer shell must be explicitely defined. I do it brutforce - calculate a bounded volume and sort shells descending. Cannot estimate the complexity of this approach, but as you know, topologically outer shell and "void" shell are indistinguishable, so we have to use some geometry.

**Comment by aothms** [comment]
> shells are stored in order of creation, not their topological sense

Those are great insights, I expected the same, it's just lazyness (and the fact that aren't that many interior shells in IFC). Would be great to have more people involved with your level of OCCT experience. 

I just came accross this though https://dev.opencascade.org/doc/refman/html/class_b_rep_class3d.html#a57ca5bc0e38a7cd75166eb59322ab62a They do seem to have an API for it.

Sort by bounding volume would probably work in the majority of cases, but in case of curved surfaces it probably depends on triangulation (maybe the OCCT api above does so too).

**Comment by nickger** [comment]
Well, thank you, but I mostly fight with OCCT rather use it efficiently :) And this is a good example, why on Earth there is a separate class with just 2 functions to check shells, jeezes... But the method is much more elegant - they check whether a shell space division contains the infinity point.

**Comment by aothms** [comment]
Yes, it's analogous to their https://dev.opencascade.org/doc/refman/html/class_b_rep_top_adaptor___f_class2d.html for detecting wire orientation. 

I understand your sentiment, but there is an inherent amount of fighting involved with any complex piece of engineering, also the commercial alternatives. The outskirts of the OCCT API are a bit more poorly documented and there are sometimes some surprising limitations that you wouldn't understand from just the API definitions, but it seems you got quite far :)
