### ISSUE TITLE
Missing IFCObject Metadata in the Object Properties

### ISSUE THREAD

**Issue by JoMiGe** [IfcOpenShell/IfcOpenShell#4219]
Hi

Based on the [documentation ](https://blenderbim.org/docs/users/creating_an_ifc_model.html), I was expected to have access to the IFCObject Metadata to categorize my object, but this section is missing in my case.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/99641771/88ada9c3-fc1f-479b-bf0a-42de1005e714)

The add-on is correctly installed and activated, I'm able to create IFC project.
I'm using Blender 4.2 and I tried with the following add-on:
- blenderbim-231104-py310-win
- blenderbim-240115-py310-win

Maybe I miss something in my setup ....

**Comment by Andrej730** [comment]
@JoMiGe images in the documentation wasn't updated yet :\
Most of BBIM properties were migrated to the Scene section. E.g. object data can be accessed through Object Informtation tab.


![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/37f7b401-9b1f-4d1c-b279-1aedfbb243db)

**Comment by JoMiGe** [comment]
Than you for the clarification !
