### ISSUE TITLE
Segmentation fault with Import Cost Schedule CSV

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#4221]
Step to reproduce:
1. open an existing IFC file (no matter which)
2. under "costing and scheduling" tab, press "import cost schedule CSV" and remember to select "Is Schedule Of Rate"
3. select the file [EPU_prezzario2013.csv](https://github.com/IfcOpenShell/IfcOpenShell/files/13940221/EPU_prezzario2013.csv) 
4. bum it crashes!

If you delete the last row, it does work correctly, but i don't think the reason is because of the last line, the reason seems to be too much rows to handle... but 57 shouldn't be too much i guess...
Also, the file is created from another made by about 30.000 rows so ...

**Comment by Moult** [comment]
The last row has no cost value / quantity. The import expects a valid cost schedule to have a cost value or quantity (unless it is a category, but not in your case as in your case the last row is a leaf). Crashing is a bit harsh, so now it skips these "invalid" rows.
