### ISSUE TITLE
PartOf.asdict missing "clause_type"

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#4226]
Just checking before I commit (I'm hesitant to commit directly when I haven't worked on the library in a while):  https://github.com/IfcOpenShell/IfcOpenShell/blob/c92f607a151f4a7023fa337ff7ad3fb66bd2deaa/src/ifctester/ifctester/facet.py#L408-L409

The PartOf.asdict method should be modified to be:

```
def asdict(self, clause_type):
        results = super().asdict(clause_type)
```

**Comment by Moult** [comment]
You're absolutely right. PR welcome?
