### ISSUE TITLE
Get Elements Inside a Space

### ISSUE THREAD

**Issue by Pushover-1** [IfcOpenShell/IfcOpenShell#4230]
Hey, I am new to ifcopenshell, I have five different spaces in my IFC file!
I want to get all the elements present inside the space as well as the wall, slab, door, and windows attached to it, the file returns null on space.BoundedBy, so is there any other way this can be done.

**Comment by aothms** [comment]
See https://community.osarch.org/discussion/comment/8857/#Comment_8857

**Comment by Moult** [comment]
Also see https://blenderbim.org/docs-python/ifcopenshell-python/geometry_tree.html

**Comment by Pushover-1** [comment]
> Also see https://blenderbim.org/docs-python/ifcopenshell-python/geometry_tree.html

I tried this technique, but I got a null return for the types that I tried. 
```
spaces = ifc_file.by_type("IfcSpace")
walls = ifc_file.by_type("IfcWall")
tree = ifcopenshell.geom.tree()
settings = ifcopenshell.geom.settings()
print(tree.select_box(spaces[0])) ---------> Null 
print(tree.select_box(walls[0]))---------> Null 
```

Also tried to get the bounding box of the element, and tried to see which elements are contained within that bounding box as well, but also got zero elements.

**Comment by Pushover-1** [comment]
> You need to actually add elements to the tree. See the code snippet on https://blenderbim.org/docs-python/ifcopenshell-python/geometry_tree.html

Thank you!!! 
This does help!! 

I have another question, even though it is a design decision. Is there a method to extract only the section of a slab that corresponds to a specific room when the entire floor is represented as a single slab element?

**Comment by Moult** [comment]
Do you have an IfcSpace that represents the footprint of the room? If so you can just use https://blenderbim.org/docs-python/autoapi/ifcopenshell/util/shape/index.html?highlight=get_footprint_area#ifcopenshell.util.shape.get_footprint_area

Or do you mean you actually want to boolean the slab to get just that portion? You can do that using IFC itself by creating an IfcBooleanResult with a boolean difference using the room's profile as a cutting volume (offset, or a new extrusion based on it), or via opencascade, or tessellating it before/after and dealing with it as a mesh, or... :) there are lots of methods.

**Comment by Pushover-1** [comment]
I meant the second part, where I want to boolean the slab. But looks like it should be done with an authoring tool like Blender, opencascade, or some ifc editing file. Are there any methods, where I can do that using just IfcOpenshell!!

**Comment by aothms** [comment]
As @Moult said you can construct an IFC instance graph that describes the intersection of the two geometries look into IfcBooleanResult and use IfcOpenShell to evaluate that. You can do that programmatically, but it requires quite some understanding of IFC probably to get it done. We as a community are here to help with advise or comments if you're stuck.

**Comment by Pushover-1** [comment]
> Member

Ah okay! Thank you. Will look into it :)

**Comment by Pushover-1** [comment]
> As @Moult said you can construct an IFC instance graph that describes the intersection of the two geometries look into IfcBooleanResult and use IfcOpenShell to evaluate that. You can do that programmatically, but it requires quite some understanding of IFC probably to get it done. We as a community are here to help with advise or comments if you're stuck.



> As @Moult said you can construct an IFC instance graph that describes the intersection of the two geometries look into IfcBooleanResult and use IfcOpenShell to evaluate that. You can do that programmatically, but it requires quite some understanding of IFC probably to get it done. We as a community are here to help with advise or comments if you're stuck.

Thank you!! Will look into it :)
