### ISSUE TITLE
Support for IFC 4x3

### ISSUE THREAD

**Issue by Noranius** [IfcOpenShell/IfcOpenShell#4232]
IFC 4x3 has been standardized and will be published in April [https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/). Are there any plans to include IFC 4x3 in IfcOpenShell?

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/issues/842
