### ISSUE TITLE
Load IFC from console/script

### ISSUE THREAD

**Issue by OrionSehn** [IfcOpenShell/IfcOpenShell#4233]
Hello!

I was having issues loading a specific IFC from a console or from a script. Fairly simple to reproduce:

```py 

import bpy

print("trying to load project")
bpy.ops.bim.load_project(
                filepath= r"D:\my_ifc.ifc",
                should_start_fresh_session = True
                )


```

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/96adfbb3-ed9d-4708-b231-71d95af73f98)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/48f72709-772b-4bae-981d-1c27e0811127)

Will not load in the relevant IFC, closes scripting window and moves to BIM window. 

We want to do this for when we want to run analysis on a single ifc, I tried to see if there was some blenderbim function I could call instead of an operator, but I couldn't see a way how to.

blenderbim/blender version:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/4807f5f4-5771-4ea3-bfc9-4d3fb8e478ab)

Edit added details

**Comment by Moult** [comment]
I just tried it and it works for me?

```
import bpy
bpy.ops.bim.load_project(filepath= r"/home/dion/test_assembly.ifc", should_start_fresh_session = True)
```

Can you try with the latest builds? https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-240119

**Comment by OrionSehn** [comment]
Can confirm that this works on the latest build, looks like it was an unknown issue with a previous version.

Thanks for the verification and the prompt response <3
