### ISSUE TITLE
IFC Reload in menu and scene should behave the same

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#4236]
I'm pretty sure that both commands are supposed to do the same thing. The button in scene does not reload but opens a file selection dialogue

![BlenderBIM Screenshot 2024-01-19](https://github.com/IfcOpenShell/IfcOpenShell/assets/1941141/c78554fb-ec66-46e0-a341-b1fd10fdc0d8)

**Comment by Moult** [comment]
The revert IFC project starts a completely fresh session from scratch. This is very safe and is just a shortcut to Open IFC project for the current IFC model.

The reload IFC project detects changes and only updates those changed objects. This is relatively dangerous but has the benefit that it preserves any Blender specific changes like non-IFC Blender objects or random Blender session rendering settings or textures.

Thoughts @theoryshaw @Plae-blue-dot ?

**Comment by Plae-Blue-Dot** [comment]
These are different commands, I think the wording for the description should be different, both starting with "reload Ifc..." can be confusing for users.

**Comment by Gorgious56** [comment]
The file > revert ifc one is fine by me, it mimicks the blender vanilla revert function. However I would change the tool tip to say revert instead of reload. The other one I still don't really understand what it does and I never used it.
