### ISSUE TITLE
Loosing Geometry representation for blender mesh object

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#4237]
I have 2 blender mesh objects (Cubicle & Chair-01) that I want to assign ifc class of `IfcFurnitureType`. However, I have noticed that after assigning the ifc type, saving the ifc file and reopening the ifc file, the tessellation representation for 1 of the object ('Cubicle') is lost and only the bounding box representation is retained.
I have attached the individual blender files and the ifc file (all renamed to .txt) along for reference.
I'm wondering what are the don'ts for mesh modelling to avoid such loss of tessellation representation.
[Geometry_Test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13996740/Geometry_Test.ifc.txt)
[Cubicle.blend.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13996742/Cubicle.blend.txt)
[CHAIR-01.blend.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13996744/CHAIR-01.blend.txt)

**Comment by Moult** [comment]
This isn't really something we can solve on our end, it's more a GIGO issue. If the mesh is messy, like zero edges, zero faces, intersecting faces, and so on, there starts to become a chance that we cannot parse the geometry. Unless you're modeling yourself, I'd advise using the built-in 3D print toolbox to inspect your objects prior to turning them into IFC objects.

For example, if you merge by distance (say 1mm) then the cubicle works. The 3D print toolbox mentions lots of problems with your mesh.

**Comment by arunkvijay** [comment]
Thanks Moult. This works well
