### ISSUE TITLE
Wall miter/butt/extend acting weird with certain wall type

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4239]
Wall miter/butt/extend acting weird with certain wall type

file: https://codeberg.org/OpeningDesign/Loftsgordon_Residence/src/commit/d16e4d504c1350808cc9c2f7b3a058a1d6e3fd8c/Open/Models/BlenderBIM/Loftsgordon_Residence.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d42faab9-a84d-4a24-8cd4-1b2020a516d9

**Comment by Moult** [comment]
Uh. How did you create this file?

This file has three IfcProjects in it. This breaks a pretty fundamental assumption and causes all sorts of things to go wrong :)

**Comment by theoryshaw** [comment]
Thanks Dion.  I think we may have accidently copied over the ifcproject, not sure. 

https://matrix.to/#/!agAlHiaduSunfNGRLo:matrix.org/$baxcJQqDRl-QM4JAuz0N3Q2rwT2LgYonJ3tgKXjaPtg?via=matrix.org

**Comment by theoryshaw** [comment]
Not sure, if in your latest commits, you wanted to prevent this too. 


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/92676a05-9250-4787-b161-d022953a9cb1
