### ISSUE TITLE
SVG Plan View show tessellation along with profile curve

### ISSUE THREAD

**Issue by arjun1panda** [IfcOpenShell/IfcOpenShell#4248]
![Screenshot 2024-01-23 185212](https://github.com/IfcOpenShell/IfcOpenShell/assets/58388022/bb379718-b043-4f74-ad6a-403c9c32cb8a)
![Screenshot 2024-01-23 185300](https://github.com/IfcOpenShell/IfcOpenShell/assets/58388022/b27e542a-4490-418a-b943-7c2c9463b5bd)

The ifc file format having a separate 2d representation but a plan view **SVG shows tessellated mesh lines along with the profile**. Sometimes the tessellated mesh not automatically switch to a 2d profile when we switch form model view to plan view.

**Comment by theoryshaw** [comment]
can you upload a test file?... just add an `.txt` to the end of the ifc file, to upload here.

**Comment by Moult** [comment]
Responded here: https://community.osarch.org/discussion/comment/18987#Comment_18987
