### ISSUE TITLE
Convert Ifcfile to mesh file

### ISSUE THREAD

**Issue by Pushover-1** [IfcOpenShell/IfcOpenShell#4249]
I want to convert an ifc element into a respective mesh file, so that I can sample points from the surface. pytorch3d.ops.sample_points_from_meshes provides that functionality but requires meshes as input. I looked but could not find proper documentation on it.

**Comment by Moult** [comment]
If you need a mesh format file: https://blenderbim.org/docs-python/ifcconvert.html

If you want tessellations or OpenCASCADE geometry directly: https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html

**Comment by Pushover-1** [comment]
IfcConvert does not recognize IfcFurniture or ifcFurnitureElement in mtl file. It is named as DefaultMaterial! Even though the elements are there in the obj file,

**Comment by Moult** [comment]
Have you got a sample file and/or screenshots of what materials you expect vs what you see?

**Comment by aothms** [comment]
> IfcConvert does not recognize IfcFurniture or ifcFurnitureElement in mtl file

What you are observing here is just a very old fallback behaviour for elements without an explicit material association in the model. These days you will hardly find elements without materials/surface styles. In such a scenario there is a bunch of default materials that gets assigned based on the type of the element, but this is in no way intended to be exhaustive.

https://github.com/IfcOpenShell/IfcOpenShell/blob/7a7fde0a2afaeba25fe9050589996a02475c2f47/src/ifcgeom_schema_agnostic/SurfaceStyle.cpp#L15-L55
