### ISSUE TITLE
IfcAdvancedHouse fails to build

### ISSUE THREAD

**Issue by nickger** [IfcOpenShell/IfcOpenShell#4253]
```
[build] [100%] Linking CXX executable IfcAdvancedHouse.exe
[build] C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../libIfcParse.a(IfcGlobalId.cpp.obj): in function `boost::uuids::detail::random_provider_base::get_random_bytes(void*, unsigned long long)':
[build] C:/msys64/mingw64/include/boost/uuid/detail/random_provider_bcrypt.ipp:80:(.text$_ZN5boost6random6detail19seed_array_int_implILi32ELy624ENS_5uuids6detail15random_providerEjEEvRT1_RAT0__T2_[_ZN5boost6random6detail19seed_array_int_implILi32ELy624ENS_5uuids6detail15random_providerEjEEvRT1_RAT0__T2_]+0x46): undefined reference to `BCryptGenRandom'
[build] C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../libIfcParse.a(IfcGlobalId.cpp.obj): in function `boost::uuids::detail::random_provider_base::random_provider_base()':
[build] C:/msys64/mingw64/include/boost/uuid/detail/random_provider_bcrypt.ipp:44:(.text$_ZN5boost5uuids22basic_random_generatorINS_6random23mersenne_twister_engineIjLy32ELy624ELy397ELy31ELj2567483615ELy11ELj4294967295ELy7ELj2636928640ELy15ELj4022730752ELy18ELj1812433253EEEEC1Ev[_ZN5boost5uuids22basic_random_generatorINS_6random23mersenne_twister_engineIjLy32ELy624ELy397ELy31ELj2567483615ELy11ELj4294967295ELy7ELj2636928640ELy15ELj4022730752ELy18ELj1812433253EEEEC1Ev]+0xf7): undefined reference to `BCryptOpenAlgorithmProvider'
[build] C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../libIfcParse.a(IfcGlobalId.cpp.obj): in function `boost::uuids::detail::random_provider_base::destroy()':
[build] C:/msys64/mingw64/include/boost/uuid/detail/random_provider_bcrypt.ipp:97:(.text$_ZN5boost5uuids22basic_random_generatorINS_6random23mersenne_twister_engineIjLy32ELy624ELy397ELy31ELj2567483615ELy11ELj4294967295ELy7ELj2636928640ELy15ELj4022730752ELy18ELj1812433253EEEEC1Ev[_ZN5boost5uuids22basic_random_generatorINS_6random23mersenne_twister_engineIjLy32ELy624ELy397ELy31ELj2567483615ELy11ELj4294967295ELy7ELj2636928640ELy15ELj4022730752ELy18ELj1812433253EEEEC1Ev]+0x16c): undefined reference to `BCryptCloseAlgorithmProvider'
[build] C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/include/boost/uuid/detail/random_provider_bcrypt.ipp:97:(.text$_ZN5boost5uuids22basic_random_generatorINS_6random23mersenne_twister_engineIjLy32ELy624ELy397ELy31ELj2567483615ELy11ELj4294967295ELy7ELj2636928640ELy15ELj4022730752ELy18ELj1812433253EEEEC1Ev[_ZN5boost5uuids22basic_random_generatorINS_6random23mersenne_twister_engineIjLy32ELy624ELy397ELy31ELj2567483615ELy11ELj4294967295ELy7ELj2636928640ELy15ELj4022730752ELy18ELj1812433253EEEEC1Ev]+0x292): undefined reference to `BCryptCloseAlgorithmProvider'
```
Any idea?

**Comment by RickBrice** [comment]
Using Visual Studio, I have had to explicitly add bcrypt.lib to the linker settings. Missing lib files are a common reason for unresolved external functions

**Comment by nickger** [comment]
It works for you in Visual Studio?! I waisted 2 days trying to make it work - nothing, CMake always complains. With MinGW I have a chance to start a buid - but it can never finish it. Any 100% installation receipe?

**Comment by aothms** [comment]
The vast majority of our C++ users in MSVC. Let us know if you encounter any issues.

I do see in our cmake script that the addition of bcrypt is MSVC specific. Maybe this ought to be Windows specific. @nickger if you try wrapping this in a windows specific if statement and it works, would be great if you can send in a PR.

https://github.com/IfcOpenShell/IfcOpenShell/blob/51b5a507cf0aca7f18baf602ca061396bc0ba45a/cmake/CMakeLists.txt#L266

**Comment by RickBrice** [comment]
I'm traveling this week so I don't have access to all my build notes. @nickger, if the problem persists, please ping me next week.

**Comment by nickger** [comment]
I am affraid I need another couple of years to practice with C++... I am a programmer, not software developer. All these supercomplicated configurations of CMake do not make sense for me :( @RickBrice , the issue is still there, if you have time, I highly appreciate any help.
@aothms is there a reason why by default OpenCascade is supposed to be build from the source (build-deps.sh)? For me it is a veeeery optimistic approach...

**Comment by RickBrice** [comment]
@nickger open the solution file in visual studio. Right click on the project in the solution explorer and pick Properties. Go to the linker settings. Pick the input option. Add bcrypt.lib to the Additional Dependency settings.

**Comment by nickger** [comment]
Ok, just to close the issue. On windows only one option worked for me out-of-the-box: installation of official OpenCascade files and specifying the paths to it in CMake with option MinimalBuild to exclude everithing else. Compilation from the source code or using MinGW environment fail.
I keep on programming on Ubuntu - there works everithing fine except, again, manual activation of MinimalBuild (the default value does not work for some reason)
