### ISSUE TITLE
unnecessary '=' in saved filters

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#4265]
Additional prefix '=' in saved formulas causes 0 search results.

![2024-01-29 003614](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/d56f4b5b-3a51-4ed2-9392-3f1055382c22)

BB 0.0.240126

**Comment by BalrajDhakad** [comment]
Hey,
I want to work on this issue can you Please guide me towards the first step

**Comment by theoryshaw** [comment]
Does the following provide any hints? 
https://github.com/search?q=repo%3AIfcOpenShell%2FIfcOpenShell+bim.load_search&type=code
