### ISSUE TITLE
Locked IfcWindow and IfcDoor elements in export

### ISSUE THREAD

**Issue by roehroeh** [IfcOpenShell/IfcOpenShell#4268]
Hi there,

I've encountered the following issue when working with geometries that I've built via ifcopenshell and would like to find out if it's a current shortcoming in the software or my usage thereof.

## What's the issue?

Whenever I try to import and edit a window that I've created via ifcopenshell into Archicad (or Revit and BricsCAD as far as I could verify with aquaintances), the width and height of the window are locked to the values I set during creation.
This makes a combined workflow of ifcopenshell with other software currently harder than it might have to be, as I'd like to be able to edit my models after creation.

As far as I can tell, there should be an option to set the export to a DesignTransferView, which I haven't been able to see while project creation, that could help me along here.

Another idea was to use the IfcWindowStandardCase as it refers to its parameters more often and seems to be constrained enough to be easily represented by some few values.

Is this a known quirk so far or have I simply misued the package? In which case I'd like to say sorry for bothering you.

**Comment by Moult** [comment]
This is not an issue with IfcOpenShell. This is a limitation in ArchiCAD and Revit - they simply have no way internally to handle something like a "parametric window" (or any of the IFC window standard case properties). Even setting the MVD to "DesignTransferView" won't help (indeed, they mostly treat that value as decoration, MVD doesn't mean much in practice).

Your best bet is to ensure that your window is built using extruded solids (use the IfcOpenShell shape builder module) and in that scenario Revit at least will let you change the extrusion depth and profile. However ArchiCAD to my knowledge will still treat it as a mesh.
