### ISSUE TITLE
Blender crash on drawing activation / bisecting meshes

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4273]
Noticed that sometimes Blender crashes when you activated drawing and it's trying to bisect mesh to draw viewport decorations during the line below:
https://github.com/IfcOpenShell/IfcOpenShell/blob/3d7e8d7c6c4502defce0b472ba6a99e649647ab2/src/blenderbim/blenderbim/bim/module/drawing/decoration.py#L1759

Way to reproduce it:
1) Open example file in BlenderBIM: [trees.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14108126/trees.ifc.txt)
2) Activate `PLAN_VIEW` drawing.
3) Unhide IfcGeographicElements
4) Try to move them by Z axis. Doing it for the two smallest trees will cause Blender to crash.

Can reproduce it ouside BBIM completely, reported issue to Blender - https://projects.blender.org/blender/blender/issues/117666

**Comment by Gorgious56** [comment]
Seems like the mesh generation for the tree produces invalid meshes.
Copy / pasting the answer from Philipp Oeser :

> The input object seems to be corrupted already
> 
> C.active_object.data.validate(verbose=True) gives
> 
> ERROR (bke.mesh): source/blender/blenkernel/intern/mesh_validate.cc:604 BKE_mesh_validate_arrays: 	Poly 960 has duplicated vert reference at corner (2)
> ERROR (bke.mesh): source/blender/blenkernel/intern/mesh_validate.cc:604 BKE_mesh_validate_arrays: 	Poly 6518 has duplicated vert reference at corner (2)
> ERROR (bke.mesh): source/blender/blenkernel/intern/mesh_validate.cc:755 BKE_mesh_validate_arrays: 	Loop 2880 is unused.
> ERROR (bke.mesh): source/blender/blenkernel/intern/mesh_validate.cc:755 BKE_mesh_validate_arrays: 	Loop 2881 is unused.
> ERROR (bke.mesh): source/blender/blenkernel/intern/mesh_validate.cc:755 BKE_mesh_validate_arrays: 	Loop 2882 is unused.
> ERROR (bke.mesh): source/blender/blenkernel/intern/mesh_validate.cc:755 BKE_mesh_validate_arrays: 	Loop 19554 is unused.
> ERROR (bke.mesh): source/blender/blenkernel/intern/mesh_validate.cc:755 BKE_mesh_validate_arrays: 	Loop 19555 is unused.
> ERROR (bke.mesh): source/blender/blenkernel/intern/mesh_validate.cc:755 BKE_mesh_validate_arrays: 	Loop 19556 is unused.
> 
> The above call also fixes the mesh, running your script afterwards seems to work fine.
> 
> Do you have an idea how the mesh got into this corrupted state?
> Unless there are clear instructions on how to reproduce it from scratch we cannot debug this any further.
> 
> Things that may cause mesh corruption: Importers, development versions of Blender, modeling tools.

**Comment by Andrej730** [comment]
Yeah, it seems there is some problem generating IfcSphere. Managed to find `duplicated vert reference at corner (2)` issue in the data from `ifcopenshell.geom.create_shape` but not sure about `Loop xxxx is unused` errors, maybe those appeared after Blender tried to fix duplicated verts references.


@aothms can you please take a look? Basically generating shape with `ifcopenshell.geom.create_shape` for representation that has `IfcSphere` is resulting in some triangles in `shape.faces` using same vertex twice - Blender considers this kind of geometry invalid and crashes trying to process it sometimes. Is it a bug, is there any workaround?

Script and .ifc to reproduce the issue:

[invalid_geometry.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14139005/invalid_geometry.ifc.txt)


```python
from pathlib import Path
import ifcopenshell
import ifcopenshell.geom
import numpy as np

filepath = Path(__file__).parent / "invalid_geometry.ifc"
ifc_file = ifcopenshell.open(filepath)

# 880=IFCCARTESIANPOINT((0.,0.,1130.));
# 881=IFCDIRECTION((0.,0.,1.));
# 882=IFCDIRECTION((1.,0.,0.));
# 883=IFCAXIS2PLACEMENT3D(# 880,# 881,# 882);
# 884=IFCSPHERE(# 883,670.);
# 885=IFCSHAPEREPRESENTATION(# 15,'Body','CSG',(# 884));
element = ifc_file.by_id(885)
settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, element)
verts, faces = shape.verts, shape.faces

triangles = np.array_split(faces, len(faces)/3)
for tris in triangles:
    if len(set(tris)) != 3:
        print(f"Not a triangle: {tris}")

# Not a triangle: [487   1   1]
# Not a triangle: [3240    0    0]
```

**Comment by aothms** [comment]
This only affects WELD_VERTICES=True,  because apparently the poles are constructed in two halves with a degenerate vertex connecting them.

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/f34092fa-8fb6-47ad-848d-80f7b40afae0)

I have a hunch this kind of thing could be different in different versions of occt, I hadn't seen it before (but there also aren't that many full spheres exchanged in IFC models).

Anyway, it's trivial to just filter out the degenerate triangle, this shouldn't have any side effects. Note that this only affects WELD_VERTICES=True, because we only check the indices not vertex coords.
