### ISSUE TITLE
Improve viewing of large federated models inside Blender

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4279]
Blender is poor at showing scenes with many objects. This can be partially overcome through multiple blends and linking, but still falls short on massive projects. There was an effort to overcome this through object merging strategies. The advanced mode allows uses to choose a merge mode which merges objects by type, class, or material. This drops the object count drastically at the expense of much longer first-load times (merging objects in Blender is slow!) and complete loss of BIM metadata since there is no longer a 1:1 Blender Object <-> IfcElement map.

Solving the many objects issue in Blender is not happening super soon. Ideally there is a dedicated "viewing" app, but at the same time it's super nice to have as much as possible inside Blender so you can have portions of the model as "inactive" and portions as active.

If this is solved, the BlenderBIM Add-on can be used for much more model coordination tasks on huge projects where full model context is important.

So I'm thinking of building features that:

 - Allow loading models as pure streams of triangles and colours (no materials / styles) that can be split into N objects per X triangles or similar. This is purely for viewing, not for editing. The geom iterator needs to be modified for this since this is very slow on the Python side.
 - Allow saving out the geom tree (upgraded to a BVH tree) alongside the blend to be read later.
 - Instead of using Blender objects to break things down, we can raycast the pointer click (or 3D cursor at first), fetch object(s) from the (earlier saved) tree and let users see the properties of it case by case in the properties menu.
 - Allow saving out pure dumb properties (not fetched live from the IFC in memory which is slow) similar to the preprocessing done in https://github.com/IfcOpenShell/xeokit-metadata-ios - it's more than likely good enough for coordination tasks.
 - Doing some sort of viewport culling that changes objects to bounding box view when not in view. This significantly speeds up the Blender viewport.
 - Ideally automate the saving and loading of .blend files as right now it's a pain to manage them alongside IFCs.

**Comment by marwiss** [comment]
It seems like this is a feature of blender.

I was wondering if there could be a feature request about this on https://projects.blender.org/blender/blender/issues.

I am thinking if there could be a "fast view render mode" in blender.

**Comment by Moult** [comment]
Sort of, it's half and half. Blender is pretty aware of their limitations about large object counts. Those links your posted unfortunately don't apply in the base case scenario. I've played with almost every viewport setting out there, but it's not just the viewport, things like selection and click-raycasting also tends to fail. Blender has some baked in assumptions like unique object naming that also slows things down. I'd love for this to be fixed in Blender but it may not happen anytime soon. (We've also recently had conversations with Blender devs talking about this issue again)

The other half is that IfcOpenShell itself only has the hdf5 option for a geometry cache but that filesize is pretty huge, and the memory requirements in loading an IFC are pretty steep. So for large projects where you easily get at least 2GB of models you want to load in, things don't go so well. See #2025 for details. In addition the HDF5 doesn't store the geometry tree, so other coordination tasks still need processing again.

**Comment by brunopostle** [comment]
BlenderBIM could potentially support opening multiple IFC file objects, and even make them all editable. This would eat lots of memory, but it wouldn't necessarily be a performance problem unless the geometry is shown in blender. I think it is ok to say that big BIM requires lots of physical memory (and the sqlite experience is that this can be mitigated with database cache techniques).

If the issue is that ten thousand blender objects fails badly, then could the 'Load Project Elements' functionality in 'Advanced Mode' simply create a single blender object representing all filtered elements?

**Comment by Moult** [comment]
Complementary to the work done in #4282 I'm really excited to say that if an IFC is first converted to HDF5, you can load those HDF5 as a chunked stream of triangles and this is very, very fast.

I tested a 360MB IFC with 62,000 elements. Just loading it as an IFC model took 280 seconds (4.67 minutes). Note that merely doing ifcopenshell.open() takes 12 seconds. Navigation in the Blender viewport is ~3.5fps which qualitatively feels really painful. I forgot to measure the memory, but for example in another test 200MB took up 8.5GB so I'm pretty sure this'll be at least 10GB which is a strain on my 32GB memory computer. In reality on large projects, you don't just want to load one of these models, you want to load up to 10x this dataset (this model was only electrical).

Note that my computer has a pretty beefy CPU.

In contrast, a IFC2H5 converter and H5 loader both written in Python (a lot of these operations may be multithreaded and it should be much faster in C++) in total takes only 140 seconds. (100 to ifcopenshell.open, then geometry iterator, then convert to H5, and 40 to load into blender). It also only takes 1GB of memory and has a smooth 30FPS with no visible lag during viewport navigation.

So curious to see how much I could push it I linked in the same file again and again up to 5 times, which should be a reasonable expectation for huge projects.

Filesize | Objects | Viewport FPS
--- | --- | ---
360 | 62k | 30 (no lag)
720 | 124k | 15-20
1,080 | 186k | 12-15
1,440 | 248k | 10-13
1,800 | 310k | 10

Note that you can instantly push viewport FPS back up to 30fps if you toggle visibility on these linked models. Even at 10fps it's honestly more responsive than proprietary software like Navisworks.

I'm really excited because when this is fully implemented (note that due to the lack of geometry tree data and data extraction we only see geometry, no data at this point) this means that Blender can be a viable alternative on huge projects for coordination tasks to proprietary tools like Navisworks, Revizto, Solibri, BIMCollab, etc.

**Comment by Moult** [comment]
@Krande yep! Basically IfcConvert can already convert to H5, this is merely a variant of H5 that is even more compressed / efficient (but contains the same data, minus the OCC breps). Then Blender can load those triangles but instead of creating meshes that are shared between objects, it simply converts to world coordinates and every arbitrary X triangles (10,000 seems to be sensible after testing) it then moves on to the next object.

I haven't done it yet, but you're right that the raycast will return a face index, and each object should in theory hold a list of GlobalIds and start/end indices. After discussing with @aothms the data can potentially be stored in a sqlite db (thus reusing the sqlite conversion code I wrote previously). (For viewing, you're generally interested in a few key properties and relationships, not everything)

**Comment by Moult** [comment]
Note that with the latest commit you can now read chunked triangles directly from IFC instead of needing to create a H5 file first :) This is useful if you only need viewing (and/or just produce a blend) and don't need to do additional geometry processing later (e.g. clash detection, custom tree queries, other scripting such as QTO, etc).

Just for a note to myself this chunking is also useful for feeding into light simulation where I've experienced feeding in monolithic models tends to fail.
