### ISSUE TITLE
IfcPatch ExtractElements based on GlobalId fails

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#4280]
I'm getting the following error while trying IfcPatch ExtractElements based on GlobalId
`Error : IFCPatch <module 'Optimise' from '/home/arun/.config/blender/4.0/scripts/addons/blenderbim/libs/site/packages/ifcpatch/recipes/Optimise.py'> could not load because : No module named 'toposort'
No MySQL support`

**Comment by arunkvijay** [comment]
IfcPatch is working though. Closing the issue

**Comment by Moult** [comment]
How did you actually trigger this error? What did you press?

**Comment by arunkvijay** [comment]
I am getting the output of a new file. I'hv done this through Blenderbim and selecting the patch as ExtractElements
However, I did notice that following attributes are missing in the newly extracted ifc file
`f.by_type('IfcGeometricRepresentationContext')[0].WorldCoordinateSystem` return none instead of IfcAxis2Placement3D and
`f.by_type('IfcGeometricRepresentationSubContext')[0].TrueNorth` returns error instead of IfcDirection
