### ISSUE TITLE
Is SWIG workaround for Python 2.x still necessary?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4281]
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcwrap/IfcPython.i#L21-L38

**Comment by aothms** [comment]
I don't know to be honest. I never use a debug build, but I'm not sure if this is solely applicable to python2. Does every python3 distribution come with debug builds? I would just leave it in there tbh.
