### ISSUE TITLE
I just want to know how to specified a input-file when i run ifcconvert?

### ISSUE THREAD

**Issue by Febfire** [IfcOpenShell/IfcOpenShell#429]
I'm a novice,i translate this storehouse.
when i run ifcconvert,i got an error：input file not specified.
what should i do to specify an input file?
thanks advance.

**Comment by Stinkfist0** [comment]
```
>IfcConvert.exe
IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 6.9.1.oce-0.18)
[Error] Input file not specified
Usage: IfcConvert [options] <input.ifc> [<output>]
...
```

So. e.g. `IfcConvert.exe myfile.ifc` (this defaults to OBJ output).

**Comment by Febfire** [comment]
forgive my ignorant...
where to run this code?
i want to debug the source code of ifcconvert.

**Comment by Febfire** [comment]
i can convert ifc to obj from run ifcConvert.exe at cmd
but what i want is to debug the source code of ifcConvert item,what should i do?
thanks very much.

**Comment by Stinkfist0** [comment]
I assume you are using Windows and Visual Studio? Open up IfcOpenShell.sln, make sure Debug configuration is chosen, locate first line of main function in IfcConvert.cpp and insert a break point there and hit F5. You probably want to specify the input file, Project Properties -> Configuration Properties -> Debugging -> Command Arguments. For more information, see e.g. https://msdn.microsoft.com/en-us/library/bb384844.aspx and other online resources.

**Comment by Febfire** [comment]
thanks very much.

**Comment by Febfire** [comment]
If it possible to convert ifc to json directly?
Could you give some tips?
thanks in advance.

**Comment by Febfire** [comment]
That's a bad news for me.
But thank you any way,your tips is useful for me.

**Comment by aothms** [comment]
> If it possible to convert ifc to json directly?

Also keep in mind there is currently quite a few JSON idiom's. Off the top of my head, Jon Mirtshin has worked on one, BIMserver.org has one, Chuck Eastman's / Dennis Shelden's group proposed one in an academic paper.

Using IfcOpenShell Python you can get something customizable very quickly as well. See e.g. https://github.com/IfcOpenShell/IfcOpenShell/pull/176#issuecomment-269911003
