### ISSUE TITLE
Decimal separator in ifcCsv

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#4290]
Feature proposal

It would be nice to be able set decimal separator to comma ',' , not dot '.' when exporting data to csv. I understand it can couse some conflicts with Concat Value, or CSV Delimeter.
Depending on regional settings in Excel, value with comma can be interpreted as float, when values with dot is text. That is my case, I'm in Poland. That settings is fixed to interface language so it is not easy to tweak it in Excel. Today I do some workaround transforming data types in Power Query.
Problem I described is not crucial but that smal fix could save few clicks.
Exporting to xlsx and ods works fine.

![decimal_separator](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/c1a1ab06-e039-4cc9-a214-45ee5749d4f0)

**Comment by Moult** [comment]
Good idea, in addition we should also support dialects (e.g. excel or excel_tab or unix) https://docs.python.org/3/library/csv.html#csv.Dialect
