### ISSUE TITLE
[BlenderBIM] Error adding WorkingTimes/ExceptionTimes to IfcWorkCalendar

### ISSUE THREAD

**Issue by Walpa** [IfcOpenShell/IfcOpenShell#4295]
The error appears when I try to add WorkingTimes or ExceptionTimes

Python: Traceback (most recent call last):
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/bim/module/sequence/ui.py", line 938, in draw
    SequenceData.load()
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/bim/module/sequence/data.py", line 48, in load
    cls.load_work_times()
  File "/home/wal/.config/blender/4.0/scripts/addons/blenderbim/bim/module/sequence/data.py", line 131, in load_work_times
    data["Start"] = ifcopenshell.util.date.ifc2datetime(data["Start"]) if data["Start"] else None
KeyError: 'Start'

![create_work_times_error](https://github.com/IfcOpenShell/IfcOpenShell/assets/32360904/c2a9f4f6-d69c-45e3-b7cd-979f934f4907)

Blender 4.0.2
BlenderBim-240130

**Comment by Andrej730** [comment]
Similar to #4294, couldn't reproduce it.

**Comment by Walpa** [comment]
Thanks for the answer.
In a new file the problem does not appear.
In my file, if you try to create WorkTimes without saving first, the spreadsheet and calendar disappear from the interface (they no longer appear even when closing and reopening the .blend file), but they appear in the ifc file.
The problem is in the file...

**Comment by Walpa** [comment]
After testing a lot of things I discovered that the problem is not in the file.
It happens with the IFC 4x3 scheme, for IFC 4 the problem does not appear in any of my tests.
See the video below.

https://github.com/IfcOpenShell/IfcOpenShell/assets/32360904/528c644b-c0bf-4ba0-9b37-6d3467116998

**Comment by Andrej730** [comment]
There indeed was an issue occurred after some attributes were renamed in IFC4X3, fixed.

Thank you for taking your time reproducing this and reporting it 👍
