### ISSUE TITLE
No access to IFC properties in the properties pannel

### ISSUE THREAD

**Issue by BernardFerries** [IfcOpenShell/IfcOpenShell#4296]
Hi,

I don't see the tabs of Properties pannel and I cannot access to IFC properties
I am using the last release of blenderBIM (0.0.231104) on Blender 3.6 (the same occurs with 4.0 release).

Thanks for your help.

![Capture](https://github.com/IfcOpenShell/IfcOpenShell/assets/114753534/ce5b00be-663c-4d5f-a43f-44b8eedfb298)

**Comment by Walpa** [comment]
Perhaps...

![Captura de tela de 2024-02-05 12-13-29](https://github.com/IfcOpenShell/IfcOpenShell/assets/32360904/ca954771-9484-4ccb-a1ae-bdc370fe1a0c)

**Comment by theoryshaw** [comment]
https://www.youtube.com/watch?v=tpQjRjB1wnU&t=2s

**Comment by Moult** [comment]
Was there any official documentation (e.g. on https://blenderbim.org) which still has outdated pictures referring to the old location?
