### ISSUE TITLE
Models are incorrectly generated with IFCconvert 

### ISSUE THREAD

**Issue by MonishVinceant1506** [IfcOpenShell/IfcOpenShell#4297]
Hi team,
The following model looks correct in the external IFC viewer and inside its native detailing software **(Bentley with ProStructures)**, however, when converted GLB using IFC convert, it looks wrong as the parts that should be round (i.e. bolts) are square, and the plates are not cut, as shown in the image below.
 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110485123/9fdaeace-b95b-42dd-88f2-f0a7c27aed26)

Please find the attached models. Please let us if, something missing in here.
[Model.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14170922/Model.zip)

Regards,
Monish

**Comment by Moult** [comment]
See #2044 and https://github.com/IfcOpenShell/IfcOpenShell/pull/4032

**Comment by MonishVinceant1506** [comment]
@Moult ,
Excluding the bounding box resolved the issue
