### ISSUE TITLE
Wall not extending all the way to the slab

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4298]
I'm not sure why this wall doesn't want to extend all the way to the ifcslab?

file:  https://codeberg.org/OpeningDesign/Loftsgordon_Residence/src/commit/94610c118569cf0db410b89d0ab8260681f0ad8f/Open/Models/BlenderBIM/New-Loftsgordon_Residence.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b74a5588-ffb6-44f3-a072-aa214aec9dc2

**Comment by Plae-Blue-Dot** [comment]
Had the same issue on the first few extension attempts , after adjusting the roof angle up and back down it seemed to work?

**Comment by theoryshaw** [comment]
Did seem to work for me.. maybe i miss understood you...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a41dd0d5-cb27-456a-b0c4-158af76eb865

**Comment by theoryshaw** [comment]
Here's another test file...

[Verona_3_Season_Porch.ifc.txt](https://github.com/user-attachments/files/17547756/Verona_3_Season_Porch.ifc.txt)

https://github.com/user-attachments/assets/3b10f905-30bc-4e9a-861c-2a9a28b58723

**Comment by theoryshaw** [comment]
It seems if a wall was extended to a slab, and the subsequently moved down, Shift+G doesn't work. 

Even if you remove all the connections, a new Shift+E doesn't seem to work. 

Here's a simple troubleshooting file. 
[not extending to slab.ifc.txt](https://github.com/user-attachments/files/17547835/not.extending.to.slab.ifc.txt)



https://github.com/user-attachments/assets/745a2429-ee35-43e7-bff8-fa827b2cb69e
