### ISSUE TITLE
[BlenderBIM] select IfcSpace by IfcBuildingStorey in Grouping and Filtering

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#4300]
Selecting IfcSpace elements in a model cannot be achieved using the `Location` filter since that particular class does not live in a Spatial Container but it is aggregated to it.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/abfe2f4f-d646-4502-8740-dc19b65e4709)

It would be easier to allow IfcSpace to be filtered by IfcBuildingStorey for data extraction and other purposes

**Comment by ppaawweeuu** [comment]
Hi,
I had similar thoughts. I would suggest to add new search facet/category - 'Agregated by' or 'Part of'. Just becouse, as you mentioned, according to ifc schema, we are talking about two different relationship types. We canot use IfcBuildingStorey as spatial container for IfcSpace, so we should not use Location facet to find IfcSpace, I think.

![agregated_by](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/a4a3a4c1-2060-418e-8fef-a7921dac009c)

--
I believe that Selector can also be way to go, when it evolve into something less experimental (I cross fingers):

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/e8e0b607-2d92-4998-a5e7-89a3a415e198)

I found interesting introduction to Selector power, by Vukas Pajic @ BimVoice:

https://youtu.be/GjEDbn7W_ns?si=I3Ij2n6k-nme_IFm

**Comment by ppaawweeuu** [comment]
I think there is some bug in Selector to group description workflow. I created separate issue #4306
