### ISSUE TITLE
Selector not working as expected

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#4306]
Hi,
I used Selector to find all Walls. Query syntax: `.IfcWall`
Selection button works fine (A).
I added query to IFC Group, group 'walls' was created. I see autogenerated group description: `*selector*.IfcWall*selector*`
I followed steps I saw on BimVoice video with Vukas Pajic https://youtu.be/GjEDbn7W_ns?si=aXaEVS6ihX0qwsus&t=493 
**Group selection button doesn't work (B).**
Is it bug or just early stage of development of experimental feature?

![selector 2024-02-09 001011](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/10102d3c-8c3a-42bd-85cb-4baad4d3061b)

Blender 4.0.1 BlenderBIM 24.01.26

**Comment by Moult** [comment]
This was the older query selector which I think is completely superseded. The newer syntax and interface is simpler, but also supports query keys as an advanced mode (which gives the capabilities of the older query method). I think this function should be just removed in lieu of the new Search / Grouping panels.

**Comment by ppaawweeuu** [comment]
thanks for explanation
