### ISSUE TITLE
BBim - temporary selection cutaway gives an error and does not work

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#4308]
When adding a temporary selection cutaway

It creates this error:

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\operator.py", line 371, in execute
    self.create_section_compare_node()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\operator.py", line 407, in create_section_compare_node
    group.inputs.new("NodeSocketFloat", "Value")
AttributeError: 'ShaderNodeTree' object has no attribute 'inputs'

The arrow is added
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/86ef9e81-2d5d-4e5f-a823-ba952bdacdd0)

but it does not cut the objects
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/1af7c0ca-11b7-4dcf-ac00-dbb94b392fea)

**Comment by Gorgious56** [comment]
I took the liberty to auto-assign this since it's mainly re-arranging nodes and updating the API, and the code is a gentle spaghetti mess I created so I don't want to make others lose too much time trying to make sense of it :)
