### ISSUE TITLE
BBim - UI Object Information panel feature request

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#4312]
The labeling within the Object Information panel's Object Metadata dropdown could be clearer and more intuitive. This can be achieved by addressing two key aspects:

1. Object Metadata Dropdown Labeling: The sub-dropdowns under Object Metadata currently start with the word "Object," which is redundant given their location within the Object Information tab and under the Object Metadata dropdown. To enhance clarity and streamline the interface, the labels should be adjusted as follows:
- "Object Property Sets" should be changed to "Property Sets"
- "Object Quantity Sets" should be changed to "Quantity Sets"
2. Inherited Psets Labeling and Icon Improvement: The labeling and icon for "Inherited Psets" could be improved for better comprehension and visual consistency. The suggested improvements are:
- Replace the up arrow icon associated with "Inherited Psets" with the linked icon. Currently, the arrow icon is misleading and directs the eye up rather than down. This would help the user understand that the property sets below are linked, and that changes to these will affect all others with the same link.
- Revise the label from "Inherited Psets" to "Type Linked:" to communicate that the property sets belong to their object's "type" and are not an inherited copy but a direct link.

<img width="343" alt="Screenshot 2024-02-10 at 12 11 59 PM" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/ec313bba-3313-47fa-858c-b69c43ca727d">

**Comment by theoryshaw** [comment]
Conceptually i like it. 

How about?...

"Object Property Sets" --> `Property Sets - Instance`
"Inherited Psets" --> `🔗 Property Sets - Type`
"Object Quantity Sets" --> `Quantity Sets - Instance`
"Inherited Qsets" --> `🔗 Quantity Sets - Type` 

note, the UI for "Inherited Qsets" doesn't exist currently.  Any Type Qsets, go under "Inherited Psets", which I think is not intended.

**Comment by trhyder** [comment]
Nice, I like the use of "Instance" and "Type", I think it would help a lot. What about using "Instance" and "Type" as sub-headings under the Property Sets toggle?

## Property Sets
Instance:
* BBIM_Array
* EPset_Parametric
Type:
* Pset_CoveringCommon

## Quantity Sets
Instance:
Type:

**Comment by trhyder** [comment]
Or we could do without the sub-headings altogether. There could be a toggle link/unlink icon next to the enable edit and remove icons. The unlinked icon would mean the Pset is on the instance, and the linked icon would mean the Pset is on the type. Then a user could move a PSet from an instance to type and visa versa just by toggling the icon. The hover text could say `move to instance` on the linked icon, and `move to type` on the unlinked icon.

**Comment by Andrej730** [comment]
New labeling makes sense. Would like to create a PR for this?

**Comment by trhyder** [comment]
I would be happy to do this on the weekend.

**Comment by trhyder** [comment]
Hey @Andrej730, I am having a go at my first PR.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/0abc2141-741a-4f4a-bdbf-2b9140f1bfa3)

I have been able to successfully modify the labeling, however, I am a bit stuck on how to fix the filtering so that inherited/typed Qtos don't appear with the Psets.

Below is an extract from the data.py file for psets:

`class ObjectPsetsData(Data):
    data = {}
    is_loaded = False

    @classmethod
    def load(cls):
        cls.data = {
            "psets": cls.psetqtos(tool.Ifc.get_entity(bpy.context.active_object), psets_only=True),
            "inherited_psets": cls.inherited_psets(),
            "pset_name": cls.pset_name(),
            "qto_name": cls.qto_name(),
        }
        cls.is_loaded = True

    @classmethod
    def inherited_psets(cls):
        element = tool.Ifc.get_entity(bpy.context.active_object)
        if element.is_a("IfcTypeObject"):
            return
        element_type = ifcopenshell.util.element.get_type(element)
        if element_type:
            return cls.psetqtos(element_type)`

Any pointers for a newby on how to filter out qto's from the `inherited_psets(cls)` def? I think then I will be able to apply the reverse to Quantities.
