### ISSUE TITLE
BBim Help - Ifc structure and all geometry has dissapeared

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#4313]
When I open my project file there is no IFC structure in the outliner and all geometry has disappeared.

This is for a small but real project, so I would greatly appreciate some help fixing my file.

I think I was exploring Surface Styles when I noticed an error, I then clicked Revert IFC Project but my project appeared empty:

<img width="1264" alt="image" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/7422a349-4747-4269-8ce5-30c900f289da">

[my project.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14230748/my.project.zip)

When I run my file through the building smart validator I get the following errors:
<img width="594" alt="image" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/6f601ea8-5814-47f0-8168-ad3773a5860e">

**Comment by trhyder** [comment]
I was able to gain access to my file by deleting the line  #342142=IFCRELNESTS('0fpfSnCSf0yO3PRAGWUqmF',$,$,$,$,(#342156));

I think I was exploring what nests were for and after a while, I tried to remove them from the UI.

After I finish my project I can do some more tests to try and reproduce the error, if that would be helpful. Or this issue can just be closed out.

**Comment by Andrej730** [comment]
Hi! If project doesn't load you can check console for errors for clues what's wrong with the file (console is available in Window -> Toggle System Console). 

The problem indeed was with the line `#342142=IFCRELNESTS('0fpfSnCSf0yO3PRAGWUqmF',$,$,$,$,(#342156));` - IfcRelNests was missing necessary RelatingObject. Though it has some related object - `#342156=IFCWALL('08TmtUc2T7i8mc_vAKcvIM',$,'Wall',$,$,#342411,#342167,$,$);`. 

Any ideas what could have created IfcRelNests relationship with that wall? It seems relating object was removed but relationship wasn't properly cleaned up.

Met similar issue before, previous time it seemed to be related to cost items (https://community.osarch.org/discussion/comment/19196#Comment_19196) but this time its different.

**Comment by Andrej730** [comment]
Found the issue that IfcRelNests wasn't always removed if you'd remove the RelatingObject, probably should solve this.
