### ISSUE TITLE
Have something like an 'edit on github' button on both BlenderBIM and IfcOpenShell docs.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4318]
For both BlenderBIM and IfcOpenShell doc, it would be nice to have something like an 'edit on github' button like buildingsmart has, in order to encourage more contribution. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/4a332585-4406-4ef5-bdfc-62d671b68fc9)

related convo: https://matrix.to/#/!ssOmSJysZpXBupsgjO:matrix.org/$HqBGr8mFDj1llAkKJlaTGn1kYD0ChiztzhhYVCE1V_Y?via=matrix.org&via=fozyjoln.dedyn.io&via=infeeeee.duckdns.org

**Comment by aothms** [comment]
I agree, I'm quite sure this greatly increases the awareness and intent around contributions to the docs.

Something like this?

https://docs.readthedocs.io/en/stable/guides/edit-source-links-sphinx.html
