### ISSUE TITLE
Less Geometry data while convert ifc to xml?

### ISSUE THREAD

**Issue by Febfire** [IfcOpenShell/IfcOpenShell#433]
I have a perplexity.
When i convert ifc to xml by ifcconvert.exe,i found that the xml less of Geometry data such as points and so on.
Is it a bug?
thanks in advance.

**Comment by aothms** [comment]
Well, perhaps this could have been documented clearer, but the IfcConvert XML conversion does not result in IFCXML. It is only the `Property definitions and decomposition tree` [1] and designed to accompany the geometrical formats (DAE / OBJ / glTF) to provide enough information for a high level BIM viewer.


[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/IfcConvert.cpp#L73

**Comment by Febfire** [comment]
So,Can you tell me how to get Geometry information of ifc file?
thanks,hope your reply @aothms

**Comment by Stinkfist0** [comment]
Use e.g. OBJ or DAE format: `IfcConvert myfile.ifc myfile.dae`.
