### ISSUE TITLE
USDZ or dotbim to ifc converter manually 

### ISSUE THREAD

**Issue by Isaina** [IfcOpenShell/IfcOpenShell#4334]
Hi,

can you add one more future in roadmap, apple LiDAR Scanner has room plan api to scan to usdz or we can convert to dotbim, usdz or dotbim can be opened in blender, can blenderbim has one mode when we import this file convert into ifc elements manually, to have tool like magic wand when we click to element like wall and choose ifc element like ifcwall, ifcdoor and can be edited as saved as ifc .

best regards

**Comment by Moult** [comment]
You can already do this, right? Just click on your objects, then assign them as IfcWall or whatever. If you want a "magic wand" tool just assign it to the `q` quick commands shortcut.
