### ISSUE TITLE
Compilation error error: ‘max_element’ is not a member of ‘std’; did you mean ‘tuple_element’

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4335]
I was updating my system (potentially including opencascade/boost/blah blah) and IOS started to failing to build.

```
/home/dion/Projects/ifcopenshell/src/ifcparse/IfcCharacterDecoder.cpp:202:56: error: ‘max_element’ is not a member of ‘std’; did you mean ‘tuple_element’?
  202 |                                         auto it = std::max_element(builder_.begin(), builder_.end());
      |                                                        ^~~~~~~~~~~
      |                                                        tuple_element
```

Fixed by adding `#include <algorithm>` - does that sound sensible? Happy to commit.

**Comment by aothms** [comment]
> Happy to commit

Please do :)

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op ma 19 feb. 2024 00:58 schreef Dion Moult ***@***.***>:
