### ISSUE TITLE
Location query not working when filtering IfcSpace

### ISSUE THREAD

**Issue by pederlh** [IfcOpenShell/IfcOpenShell#4338]
It seems that the selector from `ifcopenshell.util.selector` is not able to find the floor where IfcSpace objects are located.

Using the [sample IFC house](https://www.ifcwiki.org/images/e/e3/AC20-FZK-Haus.ifc), I'd expect that

```python
import ifcopenshell
import ifcopenshell.util.selector

house = ifcopenshell.open(path=Path("/Users/.../IFC_House.ifc"))
floors = [storey.Name for storey in house.by_type("IfcBuildingStorey")] # ['Erdgeschoss', 'Dachgeschoss']

spaces_ground_floor = ifcopenshell.util.selector.filter_elements(
        house, f'IfcSpace, location="Erdgeschoss"'
)
```
worked, but only an empty set is returned. It does work if I use the same query but with a built element type like IfcWall.

**Comment by ppaawweeuu** [comment]
Tip I learned few weeks ago: IfcSpace is not in IfcStorey spatial container. Space is aggregated by Storey. Just different type of ifc relation. That's why Location doesn't work here.
Similar thread here #4300

**Comment by pederlh** [comment]
Closing as a duplicate of #4300

**Comment by pederlh** [comment]
Fixed in https://github.com/IfcOpenShell/IfcOpenShell/commit/2c9e4434258caf4c0a2c441b51f8dbbb64e4ae46
