### ISSUE TITLE
[BlenderBim] Errors with sequence module - attributes renamed in IFC4X3

### ISSUE THREAD

**Issue by Walpa** [IfcOpenShell/IfcOpenShell#4342]
As in [#4295](https://github.com/IfcOpenShell/IfcOpenShell/issues/4295).

Bugs in: [1](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7930c5c895e2f136d55ccf3f561fc90468d6ee/src/ifcopenshell-python/ifcopenshell/util/sequence.py#L183), [2](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7930c5c895e2f136d55ccf3f561fc90468d6ee/src/ifcopenshell-python/ifcopenshell/util/sequence.py#L184), [3](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7930c5c895e2f136d55ccf3f561fc90468d6ee/src/ifcopenshell-python/ifcopenshell/util/sequence.py#L189), [4](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7930c5c895e2f136d55ccf3f561fc90468d6ee/src/ifcopenshell-python/ifcopenshell/util/sequence.py#L190), [5](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7930c5c895e2f136d55ccf3f561fc90468d6ee/src/ifcopenshell-python/ifcopenshell/util/sequence.py#L210), [6](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7930c5c895e2f136d55ccf3f561fc90468d6ee/src/ifcopenshell-python/ifcopenshell/util/sequence.py#L216)

Thanks

**Comment by Andrej730** [comment]
thanks for the bug report!
