### ISSUE TITLE
BlenderBIM add-on qto of all selected objects

### ISSUE THREAD

**Issue by fkaufm** [IfcOpenShell/IfcOpenShell#4343]
In the qto functions of the BlenderBIM add-on some methods calculate the requested quantity of all selected objects e.g., 

[Calculate object volumes](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7930c5c895e2f136d55ccf3f561fc90468d6ee/src/blenderbim/blenderbim/bim/module/qto/operator.py#L105)

However, there are other functions that only calculate the quantity of the first of the selected objects e.g., 

[Calculate net footprint area](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7930c5c895e2f136d55ccf3f561fc90468d6ee/src/blenderbim/blenderbim/bim/module/qto/operator.py#L111C22-L111C35)

This is not the expected behaviour when multiple objects are selected. For any qto tasks it would even be beneficial to calculate the quantities of all selected objects immediately. 

An easy fix would be in [Calculate net footprint area](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7930c5c895e2f136d55ccf3f561fc90468d6ee/src/blenderbim/blenderbim/bim/module/qto/operator.py#L111C22-L111C35) (untested, side-effects maybe):
```
elif props.qto_methods == "NetFootprintArea":
            for mesh_obj in selected_mesh_objects:
                result += QtoCalculator().get_net_footprint_area(mesh_obj)
```
The other qto routines would have to be changed accordingly. 

I might be able to work on this if there are not any concerns.

**Comment by Moult** [comment]
Calculations are now done consistently on all selected objects in the calculator so this is now fixed :)
