### ISSUE TITLE
Parsing IFC4.x and IFC2x3 in same executable

### ISSUE THREAD

**Issue by jonganej** [IfcOpenShell/IfcOpenShell#4351]
I'm trying to parse IFCs of different schemas without having to use preprocessor directives and knowing what schema each IFC uses and I haven't found out how to do that yet. Is that possible to begin with?

I stumbled across a really old issue [ #49](https://github.com/IfcOpenShell/IfcOpenShell/issues/49) and wondered if that was implemented in v0.7.0. If so, is there an example of how to use it? So far, my only understanding of how to parse IFC is from `src/examples/IfcParseExamples.cpp` and that requires knowing what schema the file in question has.

Otherwise, thanks for your effort on this extensive set of IFC tools @aothms!

**Comment by aothms** [comment]
See the *Writing schema agnostic code* section at http://blog.ifcopenshell.org/2019/12/v060.html

**Comment by Moult** [comment]
@jonganej would you also be interested in helping contribute to a Hello World beginners C++ tutorial in the docs?

**Comment by jonganej** [comment]
> @jonganej would you also be interested in helping contribute to a Hello World beginners C++ tutorial in the docs?

Sure, I would be interested. What parts of the IFCOpenShell C++ API specifically would you see getting covered? As suggested by @aothms, I managed to use templates for schema agnostic IFC parsing and got some learnings out of it. Might be helpful for others.

**Comment by Moult** [comment]
@jonganej anything is better than nothing :) As you can see here we currently have only 4 pages: https://blenderbim.org/docs-python/ifcopenshell.html
