### ISSUE TITLE
BBim UI bug -  Quantity sets inherited from their type incorrectly appear under the Psets.

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#4353]
Quantity sets inherited from their type incorrectly appear under the Property Sets.
Instead, they should appear under Quantity Sets.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/91804df1-d001-4f14-8948-7ff110082037)

See also https://github.com/IfcOpenShell/IfcOpenShell/issues/4312

**Comment by Andrej730** [comment]
That's very simple to solve, labeled it if anyone want to contribute.

Basically need to fetch only psets for inherited psets in https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/pset/data.py so it will avoid quantity sets but also need add fetching inherited_qsets in data.py and add similar simple UI to `BIM_PT_object_qtos.draw()` to display them (similar to `BIM_PT_object_psets`).

**Comment by milinddethe15** [comment]
`inherited_psets = cls.psetqtos(element_type, psets_only=True)`
will it exclude quantity sets?
Similarly, `inherited_qsets = cls.psetqtos(element_type, qtos_only=True)` for only quantity sets?

**Comment by Andrej730** [comment]
> `inherited_psets = cls.psetqtos(element_type, psets_only=True)`
> will it exclude quantity sets?
> Similarly, `inherited_qsets = cls.psetqtos(element_type, qtos_only=True)` for only quantity sets?

Yes and yes.
