### ISSUE TITLE
Add slab -> edit profile => BIM tool crashes and types from library are no longer valid -> error message

### ISSUE THREAD

**Issue by Bernd-GMS** [IfcOpenShell/IfcOpenShell#4362]
This is the error message I get, when the BIM tool in BlenderBIM crashes:

Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\model\slab.py", line 628, in _execute
    bpy.ops.wm.tool_set_by_id(tool.Blender.get_viewport_context(), name="bim.cad_tool")
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109

**Comment by theoryshaw** [comment]
can you share the .ifc file, or a pared-down version of it?

**Comment by Andrej730** [comment]
Hi! Issue was fixed in this commit 48b237a, you can try it out in any of the latest builds from [releases](https://github.com/IfcOpenShell/IfcOpenShell/releases/).
