### ISSUE TITLE
Bug when updating information in bulk?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4367]
I am trying to update more balcony spaces from INTERNAL to EXTERNAL, but when I do that only one gets updated and not the rest.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/4c1fa927-1a82-430c-a400-3e40e5da9a88)

Is this a bug? 

Could it be fixed?

Thank you!

**Comment by Andrej730** [comment]
@BIMvoice Hi! How you do you change the property, through Attributes -> Edit? Are you sure you're using "Copy Attribute To Selection"?

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/87dd7b10-146f-4b5a-b0d6-2ff7bba30cf1

**Comment by BIMvoice** [comment]
Awesome point Andrej. I was not doing that. I was just editing the name and saving, so now it makes sense, I was skipping the last step, to propagate the information to all the objects in the selection.

Thank you!
