### ISSUE TITLE
Clean up of dependencies

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4368]
So, uh, apparently you can't do something like `pip install --no-tests foo` :( https://stackoverflow.com/questions/54743853/installing-a-package-without-including-test-code

Uncompressed, the tests dir for pandas is 35MB (!!!) https://github.com/pandas-dev/pandas/issues/30741

There are a number of dependencies which need cleaning up for a leaner, faster download and install for users. Our `libs/site/packages` folder on Windows is 367MB uncompressed. Yikes!

 - Manually purge test files especially for Pandas if no alternative exists.
 - Question whether Augin is still needed. It's generally unmaintained and not sure if it has any real benefit to people using it. The AWS Botocore library is 55MB uncompressed!
 - Ping @gtfierro about whether Brickschema can be pared down a bit. `topquadrant_shacl` is 48MB uncompressed and ontologies v1.1 and v1.2 are shipped (are they necessary? We actually grab a nightly Brick.ttl) SQLAlchemy is 18.9MB. Abstraction is nice, but ... surprisingly heavy in this case - I think only sqlite is used after all.
 - Remove `hppfcl` et friends as part of the new clash features.
 - Don't ship all express rules for IfcOpenShell, only ISO standards.
 - Question whether or not we should still maintain and support BIMTester + Behave et friends. As IDS matures it is increasingly a niche tool.

**Comment by gtfierro** [comment]
@Moult please try out `brickschema==0.7.6a1` version, for which the topquadrant SHACL stuff is an optional package. Not sure what I could do about SQLAlchemy's size. I'll look into compressing the older ontologies too

**Comment by Moult** [comment]
@gtfierro oh sorry I think there was a miscommunication, it's about [this topquadrant folder](https://github.com/BrickSchema/py-brickschema/tree/reduce_size/brickschema/topquadrant_shacl).

**Comment by gtfierro** [comment]
Strange! I definitely meant to remove it. I'll take a look soon

**Comment by gtfierro** [comment]
Please try 0.7.6a2! I forgot to remove the jar files from the actual repository

**Comment by Moult** [comment]
Nice!

```
$ pip install "brickschema[persistence]==0.7.6a1" --target foo/
$ pip install "brickschema[persistence]==0.7.6a2" --target bar/
$ du -sh foo
104M    foo
$ du -sh bar
56M     bar
```

Thanks so much!
