### ISSUE TITLE
how to load xml files(*.xml) by ifcopenshell 

### ISSUE THREAD

**Issue by jlh104** [IfcOpenShell/IfcOpenShell#4370]
Through the ifcopenshell, we can achieve
1. read and write IFC file(.ifc) by parse.dll,Serializers.dll
2. write other files(.obj、.hdf)

but how i load a *.xml to an IfcParse::IfcFile object

**Comment by aothms** [comment]
There is a `parse_ifcxml()` function https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/parse_ifcxml.cpp But

**Comment by Moult** [comment]
Alternatively if you're using Python `ifcopenshell.open('your_ifc.ifcxml')` should work.
