### ISSUE TITLE
Blender crash when re-assigning class/type

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4371]
I just experienced this today. Windows, latest BBIM version.

Video has sound.

https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/deda7d9f-5e14-4f02-b019-512313887317

**Comment by Andrej730** [comment]
Was able to reproduce it, will look into it.

**Comment by BIMvoice** [comment]
Alright, I'm done trying to use it for today :( Way too frustrating with this crashes :(

**Comment by Andrej730** [comment]
@BIMvoice the issue occurred when you would try to reassign class for multiple elements of the same type. 

Though there is no need to select all elements manually in this case - it can be accomplished by just reassigning class for just 1 element of the type - it will automatically change the type's class and it's occurrences.

**Comment by Andrej730** [comment]
It should never crash, agreed, this is fixed, you can try it out.

**Comment by BIMvoice** [comment]
I just experienced the crash again, when editing the Type this time :(

**Comment by Andrej730** [comment]
How do I reproduce the crash with assigning types?

**Comment by BIMvoice** [comment]
I will try to help out when it will reoccur. I did not manage to replicate it myself again.
