### ISSUE TITLE
Blender 4.2 migrate legacy add-on to extension

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4373]
No action required yet, but just for tracking purposes in Blender 4.2 there will be a new approach to handling "extensions".

The relative imports and providing wheels could be complex.

https://docs.blender.org/manual/en/4.2/extensions/addons.html#legacy-vs-extension-add-ons

**Comment by Andrej730** [comment]
Just to put it out there - instructions for installing older BBIM versions in Blender 4.2:

> 0.0.240602 doesn't work with Blender 4.2 as an extension, only BBIM versions after 1fc56585dd3b157f71fc4625d006ceebed1ef73e do.
> So you can either install newer build (though daily builds are a bit broken atm, you can see when they will start working again in #4924) or install 0.0.240602 as a Legacy Blender addon.
> 
> How to install BBIM as a Legacy Blender addon in Blender 4.2
> (legacy install is hidden and we'll need to locate it through Blender search):
> 1) Preferences -> Interface -> Developer Extras (make sure it is checked)
> 2) F3 (or Edit - Menu Search) -> Type "install addon" and select it
> ![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/b69484c1-ae5e-4f4e-91de-747dc6363d70)
> 3) Select .zip with BBIM addon and install it
> 4) Preferences -> Addons -> Find "BlenderBIM" and enable it.
> 
> ![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/3134bf5e-bb36-4834-b44d-8244c6077567)

**Comment by Moult** [comment]
A status update:

 1. We've submitted an alpha release in the approval queue for the official Blender extension repo: https://extensions.blender.org/approval-queue/blenderbim/
 2. The current unstable releases ONLY support Blender 4.2. Support for <=4.1 has been dropped.
 3. There are a number of uncertainties still with how wheels are handled so things may change a lot.
 4. There are known critical bugs that affect upgrading / uninstalling for Windows which defeats the whole purpose of auto-upgrade. These are reported upstream and referenced in the approval queue submission.

**Comment by Moult** [comment]
Upstream has resolved the upgrade / uninstall bugs https://projects.blender.org/blender/blender/issues/125049 - so potentially the workarounds on our end can be removed too (ping @Andrej730 )

**Comment by Moult** [comment]
An update that we're now approved on the store. https://extensions.blender.org/add-ons/bonsai/

**Comment by Andrej730** [comment]
Looks resolved!
