### ISSUE TITLE
Error in BlenderBIM due to Attribute name change in IfcWorkTime 

### ISSUE THREAD

**Issue by chocolatecocoa6492** [IfcOpenShell/IfcOpenShell#4381]
We are trying to utilise the scheduling capabilities of BlenderBIM to build a 4D model within the IFC 4.3 model.
However, when I import the scheduling data created in Primavera, I get the error 'IFC4.3.IfcWorkTime has no attribute start'.
When I checked, I found that there are some changes in the Attribute name of IfcWorkTime between IFC4 and IFC4.3.
This is probably causing a bug within BlenderBIM.
Also, if I open an IFC 4.3 model in BlenderBIM and try to edit the WorkCalender, the tab disappears.
This is also thought to be a bug caused by the same reason.

We hope to have this resolved as soon as possible.

**Comment by Moult** [comment]
What import feature are you using? XML or XER? Can you provide a sample model?

**Comment by chocolatecocoa6492** [comment]
I`m using xml file exported from primavera.

I think that is not important thing, because the same error occurs when adding WorkCaender within BlenderBIM without importing the xml file.

**Comment by Moult** [comment]
You might want to upgrade to the latest development version https://blenderbim.org/docs/devs/installation.html#unstable-installation and see if that helps. I know that some of these issues have already been fixed.

By the way, it would really help us get more resources to keep up with the requests if you could help us financially here: https://opencollective.com/opensourcebim

**Comment by chocolatecocoa6492** [comment]
Checking this community, I found a similar question in September 2023, where a similar phenomenon occurred. 
Hopefully this has been corrected since then.

**Comment by Andrej730** [comment]
Should be fixed in current daily builds after c1cd228, please report if there are still some way to reproduce this.

**Comment by chocolatecocoa6492** [comment]
After updating to the latest BlenderBIM add-on, it can be done!
Thank you very much.
