### ISSUE TITLE
running `make dist PLATFORM=linux PYVERSION=py310`, got python: not found 

### ISSUE THREAD

**Issue by milinddethe15** [IfcOpenShell/IfcOpenShell#4387]
building the package blenderbim locally on linux https://blenderbim.org/docs/devs/installation.html#bundling-for-blender
Got Error: 
```bash
python scripts/bbim_translations.py -i "dist/working" -o "dist/blenderbim"
/bin/sh: 1: python: not found
make: *** [Makefile:547: dist] Error 127
```
`python` should be replaced to `$(PYTHON)` here
https://github.com/IfcOpenShell/IfcOpenShell/blob/48d6cc8a286f076e9f75abbdab8ee7b25d704115/src/blenderbim/Makefile#L701

**Comment by Moult** [comment]
That looks correct. Please make a PR :)
