### ISSUE TITLE
It's too slow when i convert ifc to dae

### ISSUE THREAD

**Issue by Febfire** [IfcOpenShell/IfcOpenShell#439]
Convert an ifc(20 M) to dae,expense almost 30 minutes.
Is it normlised?it's too slow...
Can i do something to Improve efficiency?
thanks in advance.

**Comment by aothms** [comment]
It really depends on the type of file. Some type of boolean operations or detailed meshes are not handled efficiently in Open CASCADE. Multi-threading is being worked on [1], but not by me. You can also for example process parts of the file simultaneously and merge the results, see [2] for pointers on the `traverse` option for example.

[1] https://github.com/sanderboer/IfcOpenShell/commits/multithreading
[2] https://github.com/IfcOpenShell/IfcOpenShell/pull/159
