### ISSUE TITLE
no import-export function

### ISSUE THREAD

**Issue by Multilal** [IfcOpenShell/IfcOpenShell#4396]
i have only "System:BlenderBIM" in preference, and can not import or export ifc either
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/162145067/5d0bb845-e22c-4adc-a288-ac424c4f9cec)

**Comment by theoryshaw** [comment]
hi...
https://github.com/IfcOpenShell/IfcOpenShell/issues/4287
