### ISSUE TITLE
IfcDiff on type relationships

### ISSUE THREAD

**Issue by JordanMcManusHoC** [IfcOpenShell/IfcOpenShell#4402]
The IfcDiff code that compares types reports changes even if their are no type changes.

This is because the comparison isn't done on the type id's but on the objects returned by get_type()

Current code:
```
            if relationship == "type":
                if ifcopenshell.util.element.get_type(old) != ifcopenshell.util.element.get_type(new):
                    self.change_register.setdefault(new.GlobalId, {}).update({"type_changed": True})
                    return True
```

Proposed code:
```
            if relationship == "type":
                if ifcopenshell.util.element.get_type(old) is not None and ifcopenshell.util.element.get_type(new) is not None:
                    if ifcopenshell.util.element.get_type(old).GlobalId != ifcopenshell.util.element.get_type(new).GlobalId:
                        self.change_register.setdefault(new.GlobalId, {}).update({"type_changed": True})
                        return True
                elif ifcopenshell.util.element.get_type(old) != ifcopenshell.util.element.get_type(new):
                    self.change_register.setdefault(new.GlobalId, {}).update({"type_changed": True})
                    return True
```

I do realise that this proposal is naive because the id of the type might not change while the type information does. Perhaps compare the string representation of the type?

**Comment by Moult** [comment]
Completely agree, can you 1) move ifcopenshell.util.element.get_type(foo) out of the if statement otherwise it gets evaluated unnecessarily twice 2) merge the nested if and 3) submit a PR :)

**Comment by JordanMcManusHoC** [comment]
I can.

I am currently testing a few approaches. I will setup a git environment on my home computer and get a PR soon.
