### ISSUE TITLE
BBim Selector syntax predefined_type key

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#4407]
The selector syntax key `predefined_type` always returns the inherited value from the "type". While the description of  `predefined_type`  mentions that the inherited value is taken "into account" I don't believe it should override a value from the instance. Instead, it should be the other way around - the "instance" values, if they exist, should always override the "type".

This can be seen when creating the below CSV Attributes on a small file that consists of one IfcColumnType and two IfcColumns, where one IfcColumn has a different PredefinedType value to its "type", and the other IfcColumn does not.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/6a1875b0-29b5-4cd7-bd7d-9cca734c9706)

The exported output:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/c946c0cc-46ef-43f9-acbe-c5da4304c37c)

In this example, I would expect cell B2 to say "PILASTER"

Am I understanding the hierarchy of instances and types correctly? Should "instance" values always override "type" values?

**Comment by Moult** [comment]
Unlike properties where you are correct, the predefined type follows different rules, presumably to help prevent unnecessary computation when selecting objects filtered by type.

From the docs:

> If the object is typed by an [IfcTypeObject](http://localhost:8000/HTML/lexical/IfcTypeObject.htm), then the PredefinedType at the [IfcObject](http://localhost:8000/HTML/lexical/IfcObject.htm) occurrence shall only be used if the PredefinedType at [IfcTypeObject](http://localhost:8000/HTML/lexical/IfcTypeObject.htm) is set to NOTDEFINED.

**Comment by trhyder** [comment]
Thanks @Moult, is there a way to create custom keys and use them in BBim?
