### ISSUE TITLE
Add MacOS support on Travis

### ISSUE THREAD

**Issue by femesq** [IfcOpenShell/IfcOpenShell#441]
Instructions for specific MacOS support [here](https://docs.travis-ci.com/user/reference/osx/) and steps to support multi-OS [here](https://docs.travis-ci.com/user/multi-os/).

Will try to look at it when I can if you guys think it worths it...

**Comment by aothms** [comment]
Any improvement in that regard is welcome. But to find the errors your reported in #432, IfcConvert should be ran on some test files and the results compared to known good outcomes. This is not entirely trivial as many differences in output are perfectly valid (different triangulations, vertex orders ...)

I have this on my list actually, but I will probably output something like numerical validation quantities for the geometries (e.g. mass, surface area, location, ...) and then make sure that differences in these get recorded.

That's independent from running CI on OSX as well, which would always be a good idea I guess. The current travis file is very much tailored to ubuntu. Open CASCADE (community edition) is obtained from the package manager. Compiling that from source would take too much time, so there is also that you need to take into account.

**Comment by femesq** [comment]
Nice.. Maybe the way to go is with `brew` instead... See the [top of this page](https://github.com/tpaviot/oce/wiki/Build-(Mac-OSX))...

**Comment by aothms** [comment]
If you can find something that works sure, but those brew/science taps are
deprecated. You can probably also get the headers and libraries from conda.

Op vr 24 aug. 2018 17:09 schreef Felipe Mesquita <notifications@github.com>:

**Comment by Moult** [comment]
Closing as Travis is no longer used and Github Actions now powers builds including a variety of channels (conda/pip).
