### ISSUE TITLE
AttributeError: entity instance of type 'IFC4X3.IfcWorkTime' has no attribute 'Start'

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#4415]
From what I can see the attribute names for IfcWorkTime (and probably other time related entities) have changed between 2x3 and 4.  As a result, loading an IFC2x3 file will result in an AttributeError during this function: https://github.com/IfcOpenShell/IfcOpenShell/blob/6e8de292c6cb21262eb9916d009d14c08ec8a9f3/src/ifcopenshell-python/ifcopenshell/util/sequence.py#L180C1-L198C31

**Comment by vulevukusej** [comment]
Or perhaps the intention is to only support schedules from 4x3 onwards?

**Comment by myoualid** [comment]
We don't support IFC 2x3 for 4D... I'm not even sure it's worth trying to support 2x3

**Comment by Moult** [comment]
We should start supporting IFC4X3 as it is now an ISO standard so let's make the effort.

IFC2X3 isn't worth it given the scarce resources. There are too many things missing in 2x3 related to 4d.

**Comment by vulevukusej** [comment]
Ok, well im currently battle testing the 4D functionality.  I'll start contributing towards support for 4x3 when I'm done.

**Comment by Andrej730** [comment]
> AttributeError: entity instance of type 'IFC4X3.IfcWorkTime' has no attribute 'Start'

This error looks similar to #4295 (occurred after attributes were renamed in IFC4X3) and should have been fixed after c1cd228. Are you sure you're on the latest version of IfcOpenShell?

**Comment by myoualid** [comment]
I read 2x3 not 4x3 :D. 
I'll start implementing any changes in for IFCF4X3 this month  !

**Comment by Moult** [comment]
Indeed this should be fixed. I just updated the implementation to be a little lighter since these util functions are called many, many times. https://github.com/IfcOpenShell/IfcOpenShell/commit/0bc83fedae2c23815a08cce6575968c469cd2a9d
