### ISSUE TITLE
MSP2IFC - Additional metadata as property set

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#4425]
In the MSP2Ifc class, the xml parser only retrieves the following [metadata ](https://github.com/IfcOpenShell/IfcOpenShell/blob/8dbeb928e3cd4cc520c9858d2dffd82a15c6f990/src/ifc4d/ifc4d/msp2ifc.py#L94C1-L107C14).  I propose that we retrieve all the other potentially juicy metadata, or provide an optional list of arguments to the execute function, so the user can specifically take what they need.  What are your thoughts @myoualid ? 

edit:  we could save this extra metadata in a property set.

**Comment by myoualid** [comment]
You are right, not everything is being imported atm which is a shame. Do you have a file we can use that contains juicy metadata and then we'll figure out where to map this in IFC?

**Comment by vulevukusej** [comment]
Did you check out the PR #4425 ?  So far this approach has worked nicely in my limited testing (putting the extra metadata in a property set assigned to the task).
