### ISSUE TITLE
IfcTester - Not appropriate valus in Warning column (html report)

### ISSUE THREAD

**Issue by marszulc** [IfcOpenShell/IfcOpenShell#4427]
Hello,
I am validating my models in IfcTester and I use html reports (.ods should be better btw., but they produce an error when opening in excel :( ).
I`ve noticed that values in Warning column are completely mismatched to values in rest of the columns. 
The set of entity classes entitled in Warning column is ok, but the order is wrong.

Please have in mind that I changed the hardcoded value of max. 100 rows in report (100 rows in to little, maybe if I can show only unique Names that would be okay).

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110668180/bd26f536-1faa-432f-9fed-38ab96ea4482)

Second thing, in the other specification, the column names are wrong. because ObjectType is stored in column named "Predefined Type":
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110668180/332ed5b8-3db1-4cc8-8a79-0443103313a6)

**Comment by Andrej730** [comment]
You mean you generate html report and trying to open it in Excel? I think there always will be some problems during import as .html document wasn't designed for this. If you need table data then it's probably better to use .ods.


> (.ods should be better btw., but they produce an error when opening in excel :( ).

What errors? Can you please share some .ifc + .ids to reproduce them?

**Comment by marszulc** [comment]
Sorry, this .ods thing was just a side remark (my Excel doesn`t like odses from IfcTester).

Html is a sufficient report format for me for now, but it is somehow destroyed...
Please look at the screenshots, for example in 3rd row, we have Ifcfurnishingelement but the 5th column says its a IfcCovering.

**Comment by Andrej730** [comment]
But what issues Excel have with importing .ods? Perhaps we can fix them in .ods as using .ods is more straightforward if you need tabular data.

**Comment by marszulc** [comment]
Ok, so we went a little off-topic, but nevermind.

So I don`t have any option to extract the Traceback. But I can attach the .ods.
The problem appears only with some ids reports. It says:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110668180/12e391d3-f93c-41ee-a5ba-b2107bbcd67f)

[NSO_21_PB_AB_TM_MED_MI_WI_22902_Model wyp med ruchomego AB_00IDS2.ods](https://github.com/IfcOpenShell/IfcOpenShell/files/14587151/NSO_21_PB_AB_TM_MED_MI_WI_22902_Model.wyp.med.ruchomego.AB_00IDS2.ods)

Please remember about the problem in html because we like how it looks and its interactivity.

**Comment by Andrej730** [comment]
Can you please share .ifc + .ids to investigate any further?

**Comment by marszulc** [comment]
Hello,
It seems that the mixed values in html tables are repaired, I can`t reproduce the error.
Unfortunately, I still experience some strange behavior when opening .ods in excel:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110668180/37bc9718-a5ae-4279-a42e-f1d0d406bc57)
I can ignore the error but then some worksheets are recovered:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110668180/907fda17-342f-4e1d-a391-e2a6ec571470)

When I use an IDS with only 2 specifications, I get no error but one of the worksheets is recovered:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110668180/5b70db84-da90-4b44-aeae-9a472478ab44)

**Comment by Andrej730** [comment]
> t seems that the mixed values in html tables are repaired, I can`t reproduce the error.
> Unfortunately, I still experience some strange behavior when opening .ods in excel:

Need some example .ids + .ifc to investigate the issue.

**Comment by marszulc** [comment]
Can I send them not publicly?

**Comment by marszulc** [comment]
I sent them to @Andrej730  using wetransfer

**Comment by Moult** [comment]
@Andrej730 did you manage to recreate the issue?

**Comment by Andrej730** [comment]
The problem was spreadsheet names coming from specification names, they didn't follow Excel requirements - https://support.microsoft.com/en-us/office/rename-a-worksheet-3f1f7148-ee83-404d-8ef0-9ff99fbad1f9

Now there is `excel_safe` option after 89d29cf13 that will show warnings meeting this kind of spreadsheet names and will try to fix them to make sure those spreadsheet names won't get completely lost opening .ods in Excel.
