### ISSUE TITLE
OCC compatibility with IFCOPENSHELL

### ISSUE THREAD

**Issue by keshavanarayan** [IfcOpenShell/IfcOpenShell#4429]
Hi,

I think the occ library recently has significantly changed and this is causing issues with ifcopenshell.geom library in general and also other code that is dependant on the occ code.

I was trying to find the version of occ required for ifcopenshell but was unsuccessful. 
Nevertheless, I submitted this as an issue since ifcopenshell needs to be updated I think.

Any guidance on this would be great.

Regards,
K

**Comment by Moult** [comment]
OCC 7.5 :)

Dion Moult

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Moult** [comment]
That we use 7.5 is now added to the docs.
