### ISSUE TITLE
`Cntl+D` created a 'Linked Aggregate'

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4430]
I duplicated `Cntl+D` (not a `Shift+Ctrl+D`) the aggregate in the following video. As you can see it says it's a 'Linked Aggregate'.  I would assume it would not be. 

file: https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/97c36c51f17ff06a7e5e06390e11743bbb949016/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9add4b19-6056-4dc7-b894-a285cccde698

ping @brunoperdigao

**Comment by brunoperdigao** [comment]
@theoryshaw But the aggregate that you tried to copy is a linked aggregate, right? If so, I think I know what might be causing this bug.

**Comment by theoryshaw** [comment]
Yes, it is.
I guess i would assume a `Cntl+D` on a linked aggregate would not make it a linked aggregate again. 

...

If this is not the approach, how do you easily convert a linked aggregate to a dumb one? :)

**Comment by brunoperdigao** [comment]
You're right, it should work as you described.

For now, please check if it works to select all the objects and press the "X" button on Linked Aggregates panel.

**Comment by theoryshaw** [comment]
Yes, that seems to work.... 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/0446d491-3748-4970-a34a-682a48296643

**Comment by theoryshaw** [comment]
Cool, if i remove it on one, they all get removed.  That's nice. 


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/2f61d79a-527c-49ce-a364-8a4f52a94ee8
