### ISSUE TITLE
IfcCsv Import of coordinates.

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#4439]
Awesome that you jumped on board on this!

However, it doesn't work for me. I tried with ObjectPlacement... and with x / y / z as CSV attributes. There is no error, The value seems to change: if I export again, the new (z) coordinate is shown in the csv. But there is no "movement" in blender.

BTW x/y/z are global coordinates, the ObjectPlacement.RelativePlacement.etc. should be the "last coordinate system", do I understand that correctly?

**Comment by TZwielehner** [comment]
Maybe the elements have to be "redrawn"?

**Comment by TZwielehner** [comment]
Now I'm into this, can we integrate the rotation as well?

**Comment by Moult** [comment]
@Andrej730 can you:

 1. add a check whether or not the new value is close to the old value (within a tolerance) and if so, don't edit anything
 2. element.ObjectPlacement may be null, so check for that scenario.

@TZwielehner x/y/z are absolute coordinates. Running the patch will not move things in Blender, that is expected. You will need to reopen the IFC to see the changes.

**Comment by TZwielehner** [comment]
Is there a way to force a reload? If I reopen the blender file I still get the old positions.

**Comment by Andrej730** [comment]
@TZwielehner you need to reload .ifc file, not .blend.
