### ISSUE TITLE
Segfault on beam (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#444]
1. Convert [444--beam--segfault.ifc](https://github.com/IfcOpenShell/files/blob/master/444--beam--segfault.ifc) with 6c1ad47 
2. Experience segfault:
```FATAL: An error occured, status code 139.``` 
3. Expected geometry from Solibri and SimpleBIM:
<img width="250" alt="screen shot 2018-08-25 at 15 02 12" src="https://user-images.githubusercontent.com/4601554/44618565-a609c480-a878-11e8-886d-a6d56ad13e92.png">

**Comment by aothms** [comment]
It has a face without a boundary. Naturally this is not allowed, sadly cardinalities are never really enforced anywhere. Added a manual check in bf4b5928dd066be4ecda370340e6372c26aa7030

~~~
ENTITY IfcFace
Bounds 	 :  	SET [1:?] OF IfcFaceBound;
~~~

~~~
[Warning] {1iMiKr1Xv1PP9O06B9yap1} Failed to convert face:
#41=IfcFace(())
~~~
