### ISSUE TITLE
python:Unable to get repr for <class 'ifcopenshell.geom.main.settings'>

### ISSUE THREAD

**Issue by deliciousteas** [IfcOpenShell/IfcOpenShell#4441]
# Unable to get repr for <class 'ifcopenshell.geom.main.settings'>
**Description**
I create an wall instance to my model,it could visualize well in bimvison.
But while I want to utilize the code in [Geometry processing code example](https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html),it shows me a misunderstanding warning,like this:
**Unable to get repr for <class 'ifcopenshell.geom.main.settings'>**
my Code is here:
## create_instances
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/107855849/18f2d461-cbb4-4671-bf8f-901b42986264)

## geometry processing
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/107855849/809578c5-554f-4231-b0aa-30e2978dfbcc)

**Comment by aothms** [comment]
repr() can be used in python to get a somewhat formalised textual
representation of something. Such representation is not necessary for the
geometry settings, but might be something requested by your development
environment. I don't think it impacts evaluation of the code. Can you
clarify?

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op di 19 mrt 2024 10:33 schreef deng ***@***.***>:

**Comment by deliciousteas** [comment]
Okay, I admit that the issue I raised was a bit hasty.
 In fact, I spent the whole afternoon reviewing the API documentation and got a bit confused.

I have reorganized my question as follows,

# objective:

1. Obtain the points, edges, and faces of an element from an IFC file.
2. Create a new element of type IfcWall in the IFC file and then extract its points, edges, and faces.

## Geometry_method:

I followed the method provided in the official documentation's code example.
 [[Geometry processing](https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html)](https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html)

`

```python
ifc_file = ifcopenshell.open('model.ifc')
element = ifc_file.by_type('IfcWall')[0]
settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, element)
verts = shape.geometry.verts
edges = shape.geometry.edges
faces = shape.geometry.faces
```

# Create_element_method:

I followed the method provided in the official documentation's code example.
 [[Geometry creation](https://blenderbim.org/docs-python/ifcopenshell-python/geometry_creation.html)](https://blenderbim.org/docs-python/ifcopenshell-python/geometry_creation.html)

`

```python
storey=model.by_type("IfcBuildingStorey")[0]
wall = run("root.create_entity", model, ifc_class="IfcWall")
matrix = numpy.eye(4)
matrix[:, 3][0:3] = (random.uniform(0,15),random.uniform(0,10),random.uniform(0,2))
run("geometry.edit_object_placement", model, product=wall1,matrix=matrix,is_si=True)
context = run("context.add_context", model, context_type="Model")
body = run("context.add_context", model, context_type="Model", context_identifier="Body", target_view="MODEL_VIEW",parent=context)
representation = run("geometry.add_wall_representation", model, context=body, length=random.uniform(0,10), height=random.uniform(0,15), thickness=random.uniform(0.1,1))
run("geometry.assign_representation", model, product=wall1, representation=representation)
run("spatial.assign_container", model, relating_structure=storey, product=wall1)
model.add(wall1)
model.add(body)
model.add(representation)
model.add(context)
-------
model.write("D:\\CimTestFile\\test_copy_wall.ifc")

```

`

# issue and problem

✅ Object one works well. I am able to extract the points, edges, and faces of any existing elements.

❌Object two, after using the aforementioned **Create_element_method** to create a new IfcWall element in the IFC file, I encountered an issue when attempting to extract the data for points, edges, and faces of this **newly created element**. The extraction process fails, and an error is thrown.After debugging, I found that an error occurs at the line 
`shape = ifcopenshell.geom.create_shape(settings, element)`.
 The error message received is:

`Unable to getreprfor<class'ifcopenshell.geom.main.settings'>`

**Comment by aothms** [comment]
Can you attach the model for which create_shape() fails. I guess using random numbers can create quite a bit of invalid configurations: a zero-depth extrusion is invalid. But it seems unlucky if that's the reason.

**Comment by deliciousteas** [comment]
I followed your instruction and modified the random function to start from positive numbers, avoiding the possibility of creation failure.

Actually, after further debugging, I found that there seems to be a bug in `by_type`🤔🤔:
## Create_IfcWall✅
> In the following code, I created instances of IfcWall, added them to the file, and obtained their points, edges, and faces without any issues. Moreover, they can run normally in IFC visualization software like bimvision.

```
wall = model.by_type("IfcWall")[0]
wall_type = ifcopenshell.util.element.get_type(wall)

storey=model.by_type("IfcBuildingStorey")[0]
**#Create an IfcWall element**
wall1 = run("root.create_entity", model, ifc_class="IfcWall")
matrix = numpy.eye(4)
matrix[:, 3][0:3] = (random.uniform(1,15),random.uniform(1,10),random.uniform(1,2))
run("geometry.edit_object_placement", model, product=wall1,matrix=matrix,is_si=True)
context = run("context.add_context", model, context_type="Model")
body = run("context.add_context", model, context_type="Model", context_identifier="Body", target_view="MODEL_VIEW",parent=context)
representation = run("geometry.add_wall_representation", model, context=body, length=random.uniform(1,10), height=random.uniform(1,15), thickness=random.uniform(0.1,1))
run("geometry.assign_representation", model, product=wall1, representation=representation)
run("spatial.assign_container", model, relating_structure=storey, product=wall1)
**#add new element to file**
model.add(wall1)
**#check create well or not**
wall_list=model.by_type("IfcWall")
for i in range(len(wall_list)):
    print(wall_list[i])
    data_dict={}
    settings = ifcopenshell.geom.settings()
    shape = ifcopenshell.geom.create_shape(settings, wall_list[i])
    shape_type = str(shape.type)
    element_id = wall_list[i].id()
    element_GlobalId = wall_list[i].GlobalId
    matrix = list(shape.transformation.matrix.data)
    faces = list(shape.geometry.faces)
    edges = list(shape.geometry.edges)
    verts = list(shape.geometry.verts)
    location = matrix[-3:]
**#write to a new IFC fiel**
model.write("D:\\CimTestFile\\WallOnly_copy.ifc")
```
## ReCheck new IFC file❌
> After reopening the newly created IFC file, I noticed that the number of IFC walls was less than before. It turned out that the newly created IFC wall instances were not recognized by the `by_type` method.

```
element=model1.by_type("IfcWall")#here is a bug in by_type() method
for i in range(len(element)):
    settings = ifcopenshell.geom.settings()
    shape = ifcopenshell.geom.create_shape(settings, element[i])
    shape_type = str(shape.type)
    element_id = element[i].id()
    element_GlobalId = element[i].GlobalId
    matrix = list(shape.transformation.matrix.data)
    faces = list(shape.geometry.faces)
    edges = list(shape.geometry.edges)
    verts = list(shape.geometry.verts)
    location = matrix[-3:]
    new_verts = []
```
## ScreenShot
1. Create an IFcwall instance that can be correctly identified by the `by_type()` after `model.add` and before `model.write`.The **85** is newly created.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/107855849/331d7e89-7c02-4a25-8601-5772fe4c9f0e)
2. `model.write`, and found that the newly created Ifcwall instance was not recognized by the `by_type()` method
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/107855849/42cae113-4fa8-408f-8c7d-5b8c8e18bf5c)
## accessory
> here is my test file. **WallOnly.ifc** is origin file,**WallOnly_copy.ifc** is file after creating a new Ifcwall.
I'd appreciate it if you could check for this bug.👋

[wall_test.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14680744/wall_test.zip)

**Comment by aothms** [comment]
When opening this file from disk, both walls are retrieved. What are the exact steps you undertook. Are you sure you read from the altered model?

```
>>> import ifcopenshell
>>> f = ifcopenshell.open('WallOnly_copy.ifc')
>>> f.by_type('IfcWall')
[#45=IfcWall('3Ep4r0uuX5ywPYOUG2H2A4',#2,'Wall xyz','Description of Wall',$,#46,#51,$), #85=IfcWall('32oa_uq95FDxtAFo3oVUjA',#84,$,$,$,#117,#111,$)]
```

**Comment by deliciousteas** [comment]
I've just realized a small oversight in my Code Path. Thank you so much for your prompt and helpful response!!!

**Comment by deliciousteas** [comment]
I've just realized a small oversight in my Code Path. Thank you so much for your prompt and helpful response!!!
