### ISSUE TITLE
Search group by GlobalId working as intended?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4446]
Hi,

I try to export some elements from the model and it does not really work as I hoped. 

I am not sure, but it looks like only one GlobalID is added to my query. 

Is this a bug or is there any other way I can create the query including more objects?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/d58c2fe8-7c6c-4d9f-b77d-7a91419794b3)

**Comment by BIMvoice** [comment]
I think I found the reason. I think there is a limit on how many objects you can select. This is a real issue for me because I want to split a tunnel model that has over 1500 parts. Any advice?

**Comment by ppaawweeuu** [comment]
Hi,
@BIMvoice - how do you use text file while searching GlobalID? Is there some list of GUIDs?
Can you write something more?

**Comment by BIMvoice** [comment]
I don't use any text file... I just select with my mouse random amount of objects, and I copy the query you can see in the picture.

**Comment by ppaawweeuu** [comment]
Thx.
That Value: `bpy.data.text['TextBlockName']` just seems to be Blender API path to text file embeded in .blend file.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/ff1d5325-b3c1-4043-86c9-09cd4c399480)

**Comment by ppaawweeuu** [comment]
I have no problem with selecting, saving and loading filetr for ~15k elements.
As I see, blender saves very long list of GUIDs in internal text file. That is the reason we see that `bpy.data.text...` path.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/31066c19-fa40-4d23-811d-10a8c9fedd22)

**Comment by ppaawweeuu** [comment]
@BIMvoice  Maybe if that list of objects is saved as blender embeded text file (in blend file) then it is not saved/stored in ifc file.

**Comment by BIMvoice** [comment]
> I have no problem with selecting, saving and loading filetr for ~15k elements. As I see, blender saves very long list of GUIDs in internal text file. That is the reason we see that `bpy.data.text...` path.
> 
> ![image](https://private-user-images.githubusercontent.com/61344631/314648404-31066c19-fa40-4d23-811d-10a8c9fedd22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDE5NzQsIm5iZiI6MTcxMTAwMTY3NCwicGF0aCI6Ii82MTM0NDYzMS8zMTQ2NDg0MDQtMzEwNjZjMTktZmE0MC00ZDIzLTgxMWQtMTBhOGM5ZmVkZDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2MTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNjQ2MzQyNmFhNTMwMzg3ZGJiNTI1ZmI1NDMzMWQ4Y2UwOGE5N2ZkZDlmMzg5NjdjYTIxZWM3MTQ2YzU0MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I1uyTNtIzPzrvNKb-OITCfsER9Nh5hEE4vxPEkAQJgo)
> 
> I'm not sure if it helps in your case. I found it interesting.

Thanks for this. I did not know you could see the list using this trick. I appreciate it!

**Comment by Andrej730** [comment]
Indeed creating a query for more than 50 elements stores it in the Text data-block inside Blender and query is referring to that data-block, this is why "it looks like only one GlobalID is added to query".

Any issues with the search or this can be closed?

**Comment by BIMvoice** [comment]
Well I think we should have something in place, that a newbie can figure it out by himself where he can get the full list of Guids from. Any viable options?

**Comment by Andrej730** [comment]
This info message should cover it:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/be1ee733-aaa7-4fa0-b7ed-ea55d5065a5c)

**Comment by BIMvoice** [comment]
It is a step in the right direction, thank you very much! 

That being said, not many people will know how to open that list.

**Comment by Andrej730** [comment]
I don't think we should include Blender manual to find where text editor is in Blender 😄

**Comment by BIMvoice** [comment]
I get what you say. I still see this as a hindrance for BlenderBIM users who will use it to check models. Most of them, don't know much about how Blender works. They look at the structure of their IFC model, and they want to run operations where they might need to use these lists. I don't think I overreact when I say that many will think that this is a bug, and it just does not work. 

Isn't possible to remove that 50-object limit?

**Comment by Andrej730** [comment]
Not sure why this would be considered a bug since if they deselect elements and select them using the generated query it would still work. So it's more like "this query has a weird syntax and it's something different about it but it still works".

I think Blender doesn't actually have limits for string property length, so it's possible to store string with large amount of guids and this is how we store it in IfcGroup if query is saved to IFC. @Moult

**Comment by ppaawweeuu** [comment]
I would prefer not to change that, just my opinion.
I prefer to have acces to that list (<100k character one-liner, or more) in text editor. I can see it at least.
As long as list of GUIDs is stored in ifc file in form of veeery long string - I see no bug.
I expect that there is some limitation in string type or RAM.
