### ISSUE TITLE
HTML IDS report to CSV, XLSX or JSON?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4449]
This is not a bug, just a question. Are there any ways to convert the IDS HTML report into any other formats that can be imported in PowerBI?

Or maybe having an option to generate the report directly in these formats, and have a checkbox to choose if you want it or not?

**Comment by BIMvoice** [comment]
I see .ods there now.

**Comment by Andrej730** [comment]
We don't have .xlsx export for IDS reports, only .ods.

**Comment by Moult** [comment]
We support JSON.
