### ISSUE TITLE
Wrong geometry - incomplete subtraction on wall (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#445]
1. Convert [445--wall--missing-subtractions.ifc](https://github.com/IfcOpenShell/files/blob/master/445--wall--missing-subtractions.ifc) with b13c912c4794ec46ad478c0886d0873f621e3daa (OCCT 7.3.0)
2. Experience that the wall does not have a complete subtraction:
![445](https://user-images.githubusercontent.com/4601554/44721666-2d924600-aaba-11e8-8c94-01a49f07b697.gif)

3. Expected geometry from Solibri:
<img width="250" alt="screen shot 2018-08-28 at 11 51 44" src="https://user-images.githubusercontent.com/4601554/44721393-4a7a4980-aab9-11e8-93ad-0190e0196cff.png">

**Comment by aothms** [comment]
It seems IfcOpenShell is correct here, sorry.

<img width="903" alt="2018-09-12 2" src="https://user-images.githubusercontent.com/1096535/45434021-b6f66a80-b6ad-11e8-9611-684c9c54cb6a.png">

For some reason this profile of the boolean subtraction is shifted a tiny amount, but still well under the precision threshold. Not sure what we can do here without opening a whole new can of worms.

~~~
#45 = IFCCARTESIANPOINT((3070.0002255748, -1.20789315551519E-2, 2190.));
#19 = IFCGEOMETRICREPRESENTATIONCONTEXT($, 'Model', 3, 1.E-5, #20, $);
~~~

**Comment by johanrd** [comment]
OK, thanks for checking! Closing.
