### ISSUE TITLE
SVG SvgSerializer finalise error

### ISSUE THREAD

**Issue by Cynthia-Line** [IfcOpenShell/IfcOpenShell#4450]
Hello, I'm still having trouble with the spaces, two of them won't create. WC and corridor. I've tied the walls together, but I don't understand. I've tried alt-A as I was advised last time, with the 3D cursor in the room, but this time it doesn't work either. Thanks in advance, have a nice day. 

P.S: When I open my ifc with blender, it's completely empty, but when I open it with a viewer, I have my project.
[LesBalconsDuMidi.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14692499/LesBalconsDuMidi.zip)

**Comment by ppaawweeuu** [comment]
i had no problem, sorry
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/780bae4f-2a97-47b7-ba36-f98a7b8cece8)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/b15b751a-77f5-4282-bb46-e7e35091eea3)

[LesBalconsDuMidi(2).zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14706993/LesBalconsDuMidi.2.zip)

**Comment by ppaawweeuu** [comment]
I just selected four bounding walls and pressed "generate space from walls'

**Comment by Andrej730** [comment]
> I'm still having trouble with the spaces, two of them won't create. WC and corridor. I've tied the walls together, but I don't understand. I've tried alt-A as I was advised last time, with the 3D cursor in the room, but this time it doesn't work either.

Can you please share some example with .ifc and short video demonstration?

> When I open my ifc with blender, it's completely empty, but when I open it with a viewer, I have my project.

There appears some invalid IFC in the file - IfcMappedItems empty MappingSources. Any ideas when they appeared?
It could be some actions related to the element `#325754=IFCPIPESEGMENT('3BPLhplDP9Ww9Q_8ZVGBq$',$,'PipeSegment',$,$,#325759,#325781,$,$);`.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/2eca8aa3-aee2-4710-8356-7a94fdb91e86)

**Comment by Cynthia-Line** [comment]
Hello, thanks
we use the latest lts version. My version of BlenderBim is the most recent. 
I'm trying to make two videos, so I'll get back to you.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/164325360/29c6c20b-fdf7-4c66-abd7-515fa3cc9527)

**Comment by Cynthia-Line** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/assets/164325360/52b74d35-806e-42a1-b805-3bdfbd857f16

**Comment by Andrej730** [comment]
> we use the latest LTS version. My version of BlenderBim is the most recent.

If you met some issue with BlenderBIM you can try it out the latest latest build (link was above) because maybe issue is already fixed.

> soucis.pieces.mp4

need some example .ifc to reproduce it and can you please try it out in the newer BlenderBIM version?

> When I open my ifc with blender, it's completely empty, but when I open it with a viewer, I have my project.

You can fix it by
1) Opening Blender, Scripting tab
2) Creating new text file ("New" button in text editor)
3) Paste script below
4) Adjust path to the file in the script (line `filepath = r"..."`)
5) Run the script

Then you'd be able to open the .ifc file.

```python
import ifcopenshell
import ifcopenshell.api

filepath = r"C:\path\to\LesBalconsDuMidi-complet34.ifc"

ifc_file = ifcopenshell.open(filepath)
items = ifc_file.by_type("IfcMappedItem")
representations = set()
for item in items:
    if item.MappingSource is None:
        print("invalid ifc item", item)
        inverses = ifc_file.get_inverse(item)
        for inverse in inverses:
            if inverse.is_a("IfcShapeRepresentation"):
                representations.add(inverse)


for representation in representations:
    ifcopenshell.api.run("geometry.remove_representation", ifc_file, representation=representation)

ifc_file.write(filepath)
```

It seems something happened to this IfcPipeElement. Any clues what led to this can help reproducing it and avoiding this issue in the future.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/bd9b8669-ae84-4933-b098-dc3649d5738f)

**Comment by Cynthia-Line** [comment]
Thanks Andrej !!! 

I upgraded to blender version 4 and updated Bbim, the parts work :)

I managed to follow your instructions to repair the ifc, it's perfect :)

There's one last problem, when I want to print a drawing, when I click on Activate draving it works fine, but as soon as I click on create drawing I get this error:


> Python: Traceback (most recent call last):
>   File "C:\Users\cynth\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 263, in execute
>     linework_svg = self.generate_linework(context)
>   File "C:\Users\cynth\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 538, in generate_linework
>     self.serialiser.finalize()
>   File "C:\Users\cynth\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1577, in finalize
>     return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
> RuntimeError: An unknown error occurred
> 

When i want create a CSV File, i have this error : 

> Python: Traceback (most recent call last):
>   File "C:\Users\cynth\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\csv\operator.py", line 200, in execute
>     ifc_file = ifcopenshell.open(props.csv_ifc_file)
>   File "C:\Users\cynth\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 138, in open
>     raise exc(msg)
> OSError: Unable to open file for reading

Really thanks

**Comment by Andrej730** [comment]
> There's one last problem, when I want to print a drawing, when I click on Activate draving it works fine, but as soon as I click on create drawing I get this error:

> When i want create a CSV File, i have this error :

Hard to tell without a way to reproduce those errors.

**Comment by Cynthia-Line** [comment]
The trouble is, I don't know exactly when it started. When I only have one finished building, it works. Then I duplicated that building to get 3. According to the saves, that seems to be when the problem started.

**Comment by Andrej730** [comment]
> The trouble is, I don't know exactly when it started. When I only have one finished building, it works. Then I duplicated that building to get 3. According to the saves, that seems to be when the problem started.

I mean we need atleast sample .ifc files to investigate the errors.

**Comment by Cynthia-Line** [comment]
[LesBalconsDuMidi avant apres bug.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14740583/LesBalconsDuMidi.avant.apres.bug.zip)

sorry, here are 2 ifc, the first one works, the second one doesn't, these are the two backups closest to the bug I have

**Comment by Moult** [comment]
For the second error, you will need to enable `Load From Memory` so that it picks up your active session's IFC. Alternatively you need to browse to an IFC on disk.

The first error is unfortunately another instance of a SvgSerializer error that I think @aothms might know how to debug. Here's a minimal script:

[untitled.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14814328/untitled.ifc.txt)

Run with:

```
python standalone_drawer.py /home/dion/tmp/spacetroublebug/untitled.ifc 2tH4oOqI1B1eCwu1CzYXE8 '2tFE8Cju91AgUCMK2oOSeT,1LCX$ZEBP5i8mpqEedpEsO' out.svg
```

```python
import sys
import ifcopenshell
import ifcopenshell.geom
import multiprocessing
from typing import NamedTuple, List

# python standalone_drawer.py model.ifc guid_of_drawing guids,of,bad,elements output.svg


class LineworkContexts(NamedTuple):
    body: List[List[int]]
    annotation: List[List[int]]


class Drawer:
    def execute(self):
        ifc = ifcopenshell.open(sys.argv[1])
        self.camera_element = ifc.by_guid(sys.argv[2])
        # Don't use draw.main() just whilst we're prototyping and experimenting
        # Get all representation contexts to see what we're dealing with.
        target_view = ifcopenshell.util.element.get_psets(self.camera_element)["EPset_Drawing"]["TargetView"]
        contexts = self.get_linework_contexts(ifc, target_view)
        drawing_elements = set([ifc.by_guid(g) for g in sys.argv[3].split(",")])

        self.setup_serialiser(ifc, target_view)

        tree = ifcopenshell.geom.tree()
        tree.enable_face_styles(True)

        self.serialize_contexts_elements(ifc, tree, contexts, "body", drawing_elements, target_view)
        self.serialize_contexts_elements(ifc, tree, contexts, "annotation", drawing_elements, target_view)

        if self.camera_element not in drawing_elements:
            # The camera must always be included, regardless of any include/exclude filters.
            geom_settings = ifcopenshell.geom.settings(DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True)
            # geom_settings.set_deflection_tolerance(0.0001)
            it = ifcopenshell.geom.iterator(geom_settings, ifc, include=[self.camera_element])
            for elem in it:
                self.serialiser.write(elem)

        self.serialiser.finalize()
        results = self.svg_buffer.get_value()
        print("results", results)

        with open(sys.argv[4], "w") as svg:
            svg.write(results)

    def get_linework_contexts(self, ifc, target_view) -> LineworkContexts:
        plan_body_target_contexts = []
        plan_body_model_contexts = []
        model_body_target_contexts = []
        model_body_model_contexts = []

        plan_annotation_target_contexts = []
        plan_annotation_model_contexts = []
        model_annotation_target_contexts = []
        model_annotation_model_contexts = []

        for rep_context in ifc.by_type("IfcGeometricRepresentationContext"):
            if rep_context.is_a("IfcGeometricRepresentationSubContext"):
                if rep_context.ContextType == "Plan":
                    if rep_context.ContextIdentifier in ["Body", "Facetation"]:
                        if rep_context.TargetView == target_view:
                            plan_body_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            plan_body_model_contexts.append(rep_context.id())
                    elif rep_context.ContextIdentifier == "Annotation":
                        if rep_context.TargetView == target_view:
                            plan_annotation_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            plan_annotation_model_contexts.append(rep_context.id())
                elif rep_context.ContextType == "Model":
                    if rep_context.ContextIdentifier in ["Body", "Facetation"]:
                        if rep_context.TargetView == target_view:
                            model_body_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            model_body_model_contexts.append(rep_context.id())
                    elif rep_context.ContextIdentifier == "Annotation":
                        if rep_context.TargetView == target_view:
                            model_annotation_target_contexts.append(rep_context.id())
                        elif rep_context.TargetView == "MODEL_VIEW":
                            model_annotation_model_contexts.append(rep_context.id())
            elif rep_context.ContextType == "Model":
                # You should never purely assign to a "Model" context, but
                # if you do, this is what we assume your intention is.
                model_body_model_contexts.append(rep_context.id())
                continue

        body_contexts = (
            [
                plan_body_target_contexts,
                plan_body_model_contexts,
                model_body_target_contexts,
                model_body_model_contexts,
            ]
            if target_view in ["PLAN_VIEW", "REFLECTED_PLAN_VIEW"]
            else [
                model_body_target_contexts,
                model_body_model_contexts,
            ]
        )

        annotation_contexts = (
            [
                plan_annotation_target_contexts,
                plan_annotation_model_contexts,
                model_annotation_target_contexts,
                model_annotation_model_contexts,
            ]
            if target_view in ["PLAN_VIEW", "REFLECTED_PLAN_VIEW"]
            else [
                model_annotation_target_contexts,
                model_annotation_model_contexts,
            ]
        )

        return LineworkContexts(body_contexts, annotation_contexts)

    def serialize_contexts_elements(
        self, ifc, tree: ifcopenshell.geom.tree, contexts: LineworkContexts, context_type, drawing_elements, target_view
    ):
        drawing_elements = drawing_elements.copy()
        contexts = getattr(contexts, context_type)
        for context in contexts:
            if not context or not drawing_elements:
                continue
            geom_settings = ifcopenshell.geom.settings(
                DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True, INCLUDE_CURVES=True
            )
            # geom_settings.set_deflection_tolerance(0.0001)
            if ifc.by_id(context[0]).ContextType == "Plan" and "PLAN_VIEW" in target_view:
                offset = ifcopenshell.ifcopenshell_wrapper.float_array_3()
                # A 2mm Z offset to combat Z-fighting in plan or RCPs
                offset[2] = 0.002 if target_view == "PLAN_VIEW" else -0.002
                geom_settings.offset = offset
            geom_settings.set_context_ids(context)
            it = ifcopenshell.geom.iterator(geom_settings, ifc, multiprocessing.cpu_count(), include=drawing_elements)
            processed = set()
            for elem in it:
                processed.add(ifc.by_id(elem.id))
                self.serialiser.write(elem)
                tree.add_element(elem)
            drawing_elements -= processed

    def setup_serialiser(self, ifc, target_view):
        self.svg_settings = ifcopenshell.geom.settings(
            DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True, INCLUDE_CURVES=True
        )
        # self.svg_settings.set_deflection_tolerance(0.0001)
        self.svg_buffer = ifcopenshell.geom.serializers.buffer()
        self.serialiser = ifcopenshell.geom.serializers.svg(self.svg_buffer, self.svg_settings)
        self.serialiser.setFile(ifc)
        self.serialiser.setWithoutStoreys(True)
        self.serialiser.setPolygonal(True) # Always get back polygon output
        # self.serialiser.setUseHlrPoly(True)
        self.serialiser.setUseHlrPoly(False)
        # Objects with more than these edges are rendered as wireframe instead of HLR for optimisation
        self.serialiser.setProfileThreshold(10000)
        self.serialiser.setUseNamespace(True)
        self.serialiser.setAlwaysProject(True)
        self.serialiser.setAutoElevation(False)
        self.serialiser.setAutoSection(False)
        self.serialiser.setPrintSpaceNames(False)
        self.serialiser.setPrintSpaceAreas(False)
        self.serialiser.setDrawDoorArcs(False)
        self.serialiser.setNoCSS(True)
        self.serialiser.setElevationRefGuid(self.camera_element.GlobalId)
        self.serialiser.setScale(1 / 50)
        self.serialiser.setSubtractionSettings(ifcopenshell.ifcopenshell_wrapper.ALWAYS)
        self.serialiser.setUsePrefiltering(True)  # See #3359
        # self.serialiser.setUsePrefiltering(False)  # See #3359
        self.serialiser.setUnifyInputs(True)
        self.serialiser.setSegmentProjection(True)
        if target_view == "REFLECTED_PLAN_VIEW":
            self.serialiser.setMirrorY(True)


Drawer().execute()
```

**Comment by aothms** [comment]
Finally, an easy fix :) Started a build.

**Comment by Moult** [comment]
How could an empty bounding box occur?

**Comment by aothms** [comment]
> How could an empty bounding box occur?

I think in this case it's a leftover of the bounding box removal in IfcConvert, which works well on boundingboxes contained in representations directly associated to a product, but leaves some artefacts when these boxes are wrapped in mapped representations. Not very elegant, but seems to be relatively harmless for now. I've left a todo note.

**Comment by Moult** [comment]
Thanks so much! Confirming this is fixed!

**Comment by Cynthia-Line** [comment]
> Pour la deuxième erreur, vous devrez activer `Load From Memory`afin qu'il récupérait l'IFC de votre session active. Vous devez également naviguer vers un IFC sur un disque.
> 
> La première erreur est malheureusement une autre instance d'une erreur SvgSerializer que je pense que 'aothmes pourrait savoir comment déboguer. Voici un scénario minimal :
> 
> [untitled.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14814328/untitled.ifc.txt)
> 
> Courir avec:
> 
> ```
> python standalone_drawer.py /home/dion/tmp/spacetroublebug/untitled.ifc 2tH4oOqI1B1eCwu1CzYXE8 '2tFE8Cju91AgUCMK2oOSeT,1LCX$ZEBP5i8mpqEedpEsO' out.svg
> ```
> 
> ```python
> import sys
> import ifcopenshell
> import ifcopenshell.geom
> import multiprocessing
> from typing import NamedTuple, List
> 
> # python standalone_drawer.py model.ifc guid_of_drawing guids,of,bad,elements output.svg
> 
> 
> class LineworkContexts(NamedTuple):
>     body: List[List[int]]
>     annotation: List[List[int]]
> 
> 
> class Drawer:
>     def execute(self):
>         ifc = ifcopenshell.open(sys.argv[1])
>         self.camera_element = ifc.by_guid(sys.argv[2])
>         # Don't use draw.main() just whilst we're prototyping and experimenting
>         # Get all representation contexts to see what we're dealing with.
>         target_view = ifcopenshell.util.element.get_psets(self.camera_element)["EPset_Drawing"]["TargetView"]
>         contexts = self.get_linework_contexts(ifc, target_view)
>         drawing_elements = set([ifc.by_guid(g) for g in sys.argv[3].split(",")])
> 
>         self.setup_serialiser(ifc, target_view)
> 
>         tree = ifcopenshell.geom.tree()
>         tree.enable_face_styles(True)
> 
>         self.serialize_contexts_elements(ifc, tree, contexts, "body", drawing_elements, target_view)
>         self.serialize_contexts_elements(ifc, tree, contexts, "annotation", drawing_elements, target_view)
> 
>         if self.camera_element not in drawing_elements:
>             # The camera must always be included, regardless of any include/exclude filters.
>             geom_settings = ifcopenshell.geom.settings(DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True)
>             # geom_settings.set_deflection_tolerance(0.0001)
>             it = ifcopenshell.geom.iterator(geom_settings, ifc, include=[self.camera_element])
>             for elem in it:
>                 self.serialiser.write(elem)
> 
>         self.serialiser.finalize()
>         results = self.svg_buffer.get_value()
>         print("results", results)
> 
>         with open(sys.argv[4], "w") as svg:
>             svg.write(results)
> 
>     def get_linework_contexts(self, ifc, target_view) -> LineworkContexts:
>         plan_body_target_contexts = []
>         plan_body_model_contexts = []
>         model_body_target_contexts = []
>         model_body_model_contexts = []
> 
>         plan_annotation_target_contexts = []
>         plan_annotation_model_contexts = []
>         model_annotation_target_contexts = []
>         model_annotation_model_contexts = []
> 
>         for rep_context in ifc.by_type("IfcGeometricRepresentationContext"):
>             if rep_context.is_a("IfcGeometricRepresentationSubContext"):
>                 if rep_context.ContextType == "Plan":
>                     if rep_context.ContextIdentifier in ["Body", "Facetation"]:
>                         if rep_context.TargetView == target_view:
>                             plan_body_target_contexts.append(rep_context.id())
>                         elif rep_context.TargetView == "MODEL_VIEW":
>                             plan_body_model_contexts.append(rep_context.id())
>                     elif rep_context.ContextIdentifier == "Annotation":
>                         if rep_context.TargetView == target_view:
>                             plan_annotation_target_contexts.append(rep_context.id())
>                         elif rep_context.TargetView == "MODEL_VIEW":
>                             plan_annotation_model_contexts.append(rep_context.id())
>                 elif rep_context.ContextType == "Model":
>                     if rep_context.ContextIdentifier in ["Body", "Facetation"]:
>                         if rep_context.TargetView == target_view:
>                             model_body_target_contexts.append(rep_context.id())
>                         elif rep_context.TargetView == "MODEL_VIEW":
>                             model_body_model_contexts.append(rep_context.id())
>                     elif rep_context.ContextIdentifier == "Annotation":
>                         if rep_context.TargetView == target_view:
>                             model_annotation_target_contexts.append(rep_context.id())
>                         elif rep_context.TargetView == "MODEL_VIEW":
>                             model_annotation_model_contexts.append(rep_context.id())
>             elif rep_context.ContextType == "Model":
>                 # You should never purely assign to a "Model" context, but
>                 # if you do, this is what we assume your intention is.
>                 model_body_model_contexts.append(rep_context.id())
>                 continue
> 
>         body_contexts = (
>             [
>                 plan_body_target_contexts,
>                 plan_body_model_contexts,
>                 model_body_target_contexts,
>                 model_body_model_contexts,
>             ]
>             if target_view in ["PLAN_VIEW", "REFLECTED_PLAN_VIEW"]
>             else [
>                 model_body_target_contexts,
>                 model_body_model_contexts,
>             ]
>         )
> 
>         annotation_contexts = (
>             [
>                 plan_annotation_target_contexts,
>                 plan_annotation_model_contexts,
>                 model_annotation_target_contexts,
>                 model_annotation_model_contexts,
>             ]
>             if target_view in ["PLAN_VIEW", "REFLECTED_PLAN_VIEW"]
>             else [
>                 model_annotation_target_contexts,
>                 model_annotation_model_contexts,
>             ]
>         )
> 
>         return LineworkContexts(body_contexts, annotation_contexts)
> 
>     def serialize_contexts_elements(
>         self, ifc, tree: ifcopenshell.geom.tree, contexts: LineworkContexts, context_type, drawing_elements, target_view
>     ):
>         drawing_elements = drawing_elements.copy()
>         contexts = getattr(contexts, context_type)
>         for context in contexts:
>             if not context or not drawing_elements:
>                 continue
>             geom_settings = ifcopenshell.geom.settings(
>                 DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True, INCLUDE_CURVES=True
>             )
>             # geom_settings.set_deflection_tolerance(0.0001)
>             if ifc.by_id(context[0]).ContextType == "Plan" and "PLAN_VIEW" in target_view:
>                 offset = ifcopenshell.ifcopenshell_wrapper.float_array_3()
>                 # A 2mm Z offset to combat Z-fighting in plan or RCPs
>                 offset[2] = 0.002 if target_view == "PLAN_VIEW" else -0.002
>                 geom_settings.offset = offset
>             geom_settings.set_context_ids(context)
>             it = ifcopenshell.geom.iterator(geom_settings, ifc, multiprocessing.cpu_count(), include=drawing_elements)
>             processed = set()
>             for elem in it:
>                 processed.add(ifc.by_id(elem.id))
>                 self.serialiser.write(elem)
>                 tree.add_element(elem)
>             drawing_elements -= processed
> 
>     def setup_serialiser(self, ifc, target_view):
>         self.svg_settings = ifcopenshell.geom.settings(
>             DISABLE_TRIANGULATION=True, STRICT_TOLERANCE=True, INCLUDE_CURVES=True
>         )
>         # self.svg_settings.set_deflection_tolerance(0.0001)
>         self.svg_buffer = ifcopenshell.geom.serializers.buffer()
>         self.serialiser = ifcopenshell.geom.serializers.svg(self.svg_buffer, self.svg_settings)
>         self.serialiser.setFile(ifc)
>         self.serialiser.setWithoutStoreys(True)
>         self.serialiser.setPolygonal(True) # Always get back polygon output
>         # self.serialiser.setUseHlrPoly(True)
>         self.serialiser.setUseHlrPoly(False)
>         # Objects with more than these edges are rendered as wireframe instead of HLR for optimisation
>         self.serialiser.setProfileThreshold(10000)
>         self.serialiser.setUseNamespace(True)
>         self.serialiser.setAlwaysProject(True)
>         self.serialiser.setAutoElevation(False)
>         self.serialiser.setAutoSection(False)
>         self.serialiser.setPrintSpaceNames(False)
>         self.serialiser.setPrintSpaceAreas(False)
>         self.serialiser.setDrawDoorArcs(False)
>         self.serialiser.setNoCSS(True)
>         self.serialiser.setElevationRefGuid(self.camera_element.GlobalId)
>         self.serialiser.setScale(1 / 50)
>         self.serialiser.setSubtractionSettings(ifcopenshell.ifcopenshell_wrapper.ALWAYS)
>         self.serialiser.setUsePrefiltering(True)  # See #3359
>         # self.serialiser.setUsePrefiltering(False)  # See #3359
>         self.serialiser.setUnifyInputs(True)
>         self.serialiser.setSegmentProjection(True)
>         if target_view == "REFLECTED_PLAN_VIEW":
>             self.serialiser.setMirrorY(True)
> 
> 
> Drawer().execute()
> ```

Hello Moult, i'm sorry i don't understand what I have to do with this code :/
Thanks
