### ISSUE TITLE
`file.add(entity)` crashes ifcopenshell for entities with circular references

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4454]
Debugging #1478 I've found that `file.add(entity)` crashes ifcopenshell if entity has circular references with some other entity.

I don't think I've met cases with valid ifc that has circular references so maybe there is no need to support it - could recreate it only by manually tweaking IFC file.

Just wanted to put it out there for anyone who will meet this crash on `file.add(entity)` in the future.

Example:
```python
import ifcopenshell

source_file_str = """ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('',''),'');
FILE_NAME('','',(''),(''),'','','');
FILE_SCHEMA(('IFC4'));
ENDSEC;

DATA;
#1= IFCPROJECT('0PJ607Qb5DWA6JDLqlvSVn',#2,'001',$,$,'',$,$,$);
#2= IFCOWNERHISTORY(#1,$,$,.NOCHANGE.,$,$,$,0);
ENDSEC;

END-ISO-10303-21;
"""

ifc_file = ifcopenshell.file()
source = ifcopenshell.file().from_string(source_file_str)

print('script started')
ifc_file.add(source.by_id(1))
print('script finished') # never printed because of the crash
```

Technical detail - it goes to infinite recursion trying to obtain forward references on the line:
https://github.com/IfcOpenShell/IfcOpenShell/blob/05f6ed10843cbb6485ab5a52fc080924cfc2a35f/src/ifcparse/IfcParse.cpp#L1869

**Comment by aothms** [comment]
> I don't think I've met cases with valid ifc that has circular references

I agree. It's a bit hypothetical, but let's solve it when there is a need

**Comment by Moult** [comment]
Cheers in that case closing but it's in the search results so we can reopen if needed.
