### ISSUE TITLE
Not able to select Project/Site/Building/Storey Empty in latest version

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#4457]
I'm not able to select the Empty for Project/Site/Building/Storey in the latest BlenderBIM addon. Earlier I could select any of these and do an Alt-D to select its child elements. This doesn't work now. Is this a bug?

However, I'm able to select any other Empty objects (like aggregate) and then use Alt-D to select its child elements though.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/58535690/3ffa6b06-f505-40cb-9bab-7608136a09c2)

**Comment by Andrej730** [comment]
Spatial elements imported from .ifc were made unselectable from viewport by default in 976eeae to avoid accidentally selecting them when selecting elements and project/site/building are often located at the same point and it's hard to select one of them in particular.

Current options are:
- make objects selectable by checking "selectable" icon in outliner
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/59cab6a4-a89e-46c1-ab9c-c351025291b0)
- select them from outliner
- select their children from spatial manager

**Comment by Moult** [comment]
Agreed, I think this is a good move. Selecting / moving a spatial element is a very meaningful and significant authoring step. E.g. if you move the site, building, or storey, and you are the architect, it's a big change! If you're not the architect, it's a big argument :)

**Comment by Andrej730** [comment]
related #4563
