### ISSUE TITLE
Documentation on how to build documentation

### ISSUE THREAD

**Issue by jonganej** [IfcOpenShell/IfcOpenShell#4461]
I'm looking to contribute a simple tutorial as mentioned on #4351 on how to use the basic functionalities of the core C++ library but I'm currently getting stumped at how to get started with compiling the RST files that seem to be scattered everywhere. Running `docs/generate_docs.py` fails on a missing Doxyfile in the root of `docs`, despite me having installed all required dependencies.

Would appreciate some help here ;)

**Comment by Moult** [comment]
Thank you so much! It's a little confusing right now for sure. The [C++ autogenerated API reference docs](https://ifcopenshell.github.io/docs/rst_files/library_root.html) use Doxygen, however the [guidebook-style written docs](https://blenderbim.org/docs-python/) for everything (both C++ and Python) use Sphinx. (Yes, the URL is very misleading, it says `docs-python` but it includes C++ ... [this](https://blenderbim.org/docs-python/ifcopenshell.html) is the C++ section with 4 subpages right now)

The code is [here](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/ifcopenshell-python/docs) and you run `make html` which will generate it. You can edit [the autoapi dirs](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/docs/conf.py#L69) to less things or an empty list if you want to generate it faster locally which will skip generating the Python API docs.
