### ISSUE TITLE
ImportError: IfcOpenShell not built for 'windows\64bit\python3.7'

### ISSUE THREAD

**Issue by evertravel** [IfcOpenShell/IfcOpenShell#4463]
I use python 3.7.8.  And I use pip install ifcopenshell.
when i want run the code, it gose wrong:
![error](https://github.com/IfcOpenShell/IfcOpenShell/assets/141131579/c4574891-3289-469a-968f-ba83925e30df)

**Comment by Moult** [comment]
How did you install this? https://pypi.org/project/ifcopenshell/#files reveals there is actually nothing available for Python 3.7 for Windows on PyPI.

**Comment by Moult** [comment]
BTW Python 3.7 is EOL, the oldest we support is Python 3.9.
