### ISSUE TITLE
build-deps.cmd Broken link for freetype

### ISSUE THREAD

**Issue by IanVinkHub** [IfcOpenShell/IfcOpenShell#4464]
When building on windows using the build-deps.cmd it crashes with the following error:

```
Downloading FreeType into C:\Users\ivink\coding\repos\IfcOpenshell\_deps.
Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"
At line:1 char:230
+ ... redentials; $webClient.DownloadFile('http://download.savannah.gnu.org ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException


An error occurred

Build ended at 14:19:25,20. Time elapsed 0:10:14.84.
```

After looking in to this I found out the download url is broken. (http://download.savannah.gnu.org/releases/freetype/ft271.zip).

I fixed this by changing
`call :DownloadFile http://download.savannah.gnu.org/releases/freetype/%FREETYPE_ZIP% "%DEPS_DIR%" %FREETYPE_ZIP%`

to

`call :DownloadFile https://sourceforge.net/projects/freetype/files/freetype2/2.7.1/%FREETYPE_ZIP%/download "%DEPS_DIR%" %FREETYPE_ZIP%`

**Comment by aothms** [comment]
Thank you. A pull request would be greatly appreciated!

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op ma 25 mrt 2024 14:48 schreef Ian ***@***.***>:
