### ISSUE TITLE
Issues running IDS 0.9.7 in IfcTester

### ISSUE THREAD

**Issue by fbosche** [IfcOpenShell/IfcOpenShell#4465]
I have the attached IDS (renamed with TXT to enable upload) that fails with the current addon. The errors thrown are strange:

- minOccurs and maxOccurs now allowed
- cardinality not allowed
- "dataType" must be entered "datatype"

I find this all strange actually and didn't have these issues before. Any idea why?

[IDS_Project01.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14744593/IDS_Project01.txt)

**Comment by MennoMekes** [comment]
I was here for the same reason.
ACCA UsBIM uses IDS version 0.9.7.
Maybe this has not been implemented in BlenderBIM.

On the IDS side someone also posted something about it:
https://github.com/buildingSMART/IDS/issues/259

**Comment by Andrej730** [comment]
BlenderBIM comes with IDS 0.9.6. 
0.9.7 was commited on IDS repository last month and it's labeled as "not to use in production" yet. So, I'm not sure if we should update now.
https://github.com/buildingSMART/IDS/blob/6d71cdf3547a0383c6cfbbead81a7cef7521ac3a/Development/ids.xsd

Also, same issue as #4466 ?

**Comment by fbosche** [comment]
Thanks a lot. I suppose, if 0.9.7 is still for review, it's fair that it's not supported by IfcTester and ACCA usBIM seem to have jumped the gun here. I've emailed them about it.

**Comment by MennoMekes** [comment]
ACCA is not reverting to 0.9.6.
They said 0.9.6. was also on 'Draft' when everybody implemented it so being 'Not for production' is not a valid reason not to update for them. I like their style of being the first to update. The changes are minor according tp them.

Maybe there is a simple way of editting the xml-files to work with 0.9.6.

**Comment by Moult** [comment]
ACCA is correct, we need to catch up. I had a brief look through the XSD changes and there are a number of changes we need to update to. I'll tackle this ASAP.

**Comment by fbosche** [comment]
@MennoMekes  ACCA haven't got back to me. If you are in touch with them, you may want to suggest to them to coordinate with @Moult for a joint(ish) release of 0.9.7

**Comment by MennoMekes** [comment]
> @MennoMekes ACCA haven't got back to me. If you are in touch with them, you may want to suggest to them to coordinate with @Moult for a joint(ish) release of 0.9.7

I am, my previous comment was a summary of our communication.

As you can see here Dion Moult is going to update this so you can resume your teachings soon. 
I had a similar issue since I offer an IDS course that works with ACCA and BlenderBIM. (That I might need to update as well)

**Comment by BIMvoice** [comment]
Amazing reaction once again, Dion. Thank you VERY VERY much for this!

**Comment by andreaaielloALMA** [comment]
At ACCA we are trying to support the development of IDS as much as possible. So we updated the software with the new version as soon as possible.

**Comment by Moult** [comment]
@andreaaielloALMA  Can I just say a huge kudos to ACCA. It's an absolute pleasure seeing other devs being proactive and implementing upcoming standards quickly.

**Comment by andreaaielloALMA** [comment]
> @MennoMekes ACCA haven't got back to me. If you are in touch with them, you may want to suggest to them to coordinate with @Moult for a joint(ish) release of 0.9.7. The sad thing for me is that I am in the middle of teaching IDS to 50 engineering students and the carpet was pulled under my feet at the last minute :)

I am sorry for that. Meanwhile BlenderBIM is updated, you can use usBIM.IDS for validation. It is free for 3 months .

**Comment by stefkeB** [comment]
Ifctester on pypi is still at IDS version 0.9.6 (which seemed to work with the current rule in Solibri).

It's very unfortunate that there are such breaking changes between 0.9.6 and 0.9.7 (minor as they may be in themselves). I'm teaching to 40 students this week and I cannot seem to be able to properly integrate BIMcollab Nexus, Solibri and ACCA. The ACCA IDS interface builder is nice, but I cannot use the output with BIMcollab nor Solibri.

**Comment by fbosche** [comment]
I find ACCA is excellent to build IDS and also can be used for IDS validation of IFC files. The outputted files now also work with IfcTester on BlenderBIM, no? Or is @Moult or somebody else still working on this?

**Comment by Moult** [comment]
@stefkeB PyPI updates once a month on the 18th. That's tomorrow. Is that OK?
