### ISSUE TITLE
Have section/elevation tags be more persistent, and not related to rerunning the drawing.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4478]
Let's say you have 100 section/elevations cuts on a floor plan. 

During a blender session, you create a drawing for each of these sections, by doing so, the section/elevations tags show up on the floor plan when printed. 

If, however, you close blenderbim, and reopen the file, and print the floor plan again, all the section/elevations tags are missing. You need to rerun all 100 section/elevations for them to show again on the floor plan.

Would be nice, if we didn't have to rerun all these section/elevations for them to show up on the floor plan.

**Comment by theoryshaw** [comment]
Thanks @Andrej730!

Is there a way for BB to remember the 'extent' of these tags?

If I stretch the tag like this, if I reopen the file, it defaults back it's original position. 


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/44d844cc-4384-4c1e-a97b-204ea42ed811

**Comment by Andrej730** [comment]
@theoryshaw should be fixed
