### ISSUE TITLE
BlenderBIM - mesh edit accessed through drop down is not saved to IFC

### ISSUE THREAD

**Issue by semhustej** [IfcOpenShell/IfcOpenShell#4479]
When accessing editing mode of an IFC element created from a mesh through drop down, the changes to the mesh are not saved to the IFC file. Also, when leaveing the edit mode through the drop down, there is no pop-up window with IFC Mode Set Object options.

The behavior is shown in this video: https://youtu.be/a4TZ8ARJ7ok

This seems like a bug to me. 
Tested on Blender 0.0.231104. 
Another user reported the same issue.

**Comment by Moult** [comment]
Unfortunately there are many things which we cannot override in the Blender UI. In the future when we have enough resources to provide custom Blender builds or if Blender enables it we'll be able to hide these types of things. Other examples include things like joining or splitting meshes.

The best we can do right now is 1) override the hotkey, most Blender work is hotkey driven and 2) provide an alternative UI for people to press.

For example in the latest builds you will see this UI in the top right indicating the IFC "editing mode" (in the future the IFC editing modes will also become more advanced with CSG modeling, editing subshapes, profile edit mode vs brep edit mode, etc).

![2024-03-29-181102_1312x183_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/8829fe11-4640-4d15-a589-26c6a5ac6c9d)
