### ISSUE TITLE
build-deps.cmd failing for windows

### ISSUE THREAD

**Issue by AntoineRoca** [IfcOpenShell/IfcOpenShell#448]
Hi,

While building the dependencies I got an error.
It occurred during the checking out of OpenCascade. The error states:

>can't open patch 'D:/Git2/IfcOpenShell/win/patches/V7_3_0.patch' : No such file or directory

I give you a screenshot of the error, and the current project state (after error) in my computer:

![error](https://user-images.githubusercontent.com/25299440/44792454-424b0880-aba4-11e8-85c6-4705c80ff650.PNG)
![files](https://user-images.githubusercontent.com/25299440/44792560-6e668980-aba4-11e8-8795-83ebcadc099b.PNG)

**Comment by TimFelice** [comment]
I am having the same issue

**Comment by Stinkfist0** [comment]
Apparently Thomas did not commit some required file(s)? As a workaround, try `git checkout 891448e902b4f3087fe95ceccca5458f99c844cf` or `set IFCOS_USE_OCCT=0` before running `build-deps.cmd`.

**Comment by TimFelice** [comment]
Setting IFCOS_USE_OCCT=FALSE created another error:

> The system cannot find the batch label specified - GitCloneAndCheckoutRevision

This error follows a successful build of OpenCOLLADA.

![gitcloneandcheckoutrevision](https://user-images.githubusercontent.com/38086427/44809167-f6946100-ab9b-11e8-8978-2574bdadb0df.png)

**Comment by AntoineRoca** [comment]
I also tried the `set IFCOS_USE_OCCT=FALSE` workaround, but it worked except in Visual studio, where I got an error for _ifcopenshell_wrapper : 

> D:\Git2\IfcOpenShell\build-vs2015-x86\ifcwrap\CMakeFiles\_ifcopenshell_wrapper.dir\IfcPythonPYTHON_wrap.cxx(202): fatal error C1083: Impossible d'ouvrir le fichier include : 'Python.h' : No such file or directory

Now, I guess this has nothing to do with this issue or maybe due to the flag (I have no python built).

**Comment by Stinkfist0** [comment]
@TimFelice hmm, cannot tell right off the bat what's wrong there. Did you try rerunning the script?
@AntoineRoca pass `-DBUILD_IFCPYTHON=1` for the `run-cmake.bat`, e.g. `run-cmake.bat vs2017-x64 -DBUILD_IFCPYTHON=0`.

**Comment by AntoineRoca** [comment]
@Stinkfist0  It was more for your knowledge (if it would be issue-worthy or not), as I don't use that part of the IfcOpenShell.

**Comment by Stinkfist0** [comment]
OK, in any case, I'd suspect `git checkout 891448e902b4f3087fe95ceccca5458f99c844cf` is the best way for now. Remember to `set IFCOS_USE_OCCT=FALSE` so that you same considerable amount of time as you probably have OCE now successfully build.

**Comment by TimFelice** [comment]
@Stinkfist0 I did try running the script again. I can't tell whats wrong either. It is yelling at me for a custom label, which was being used before I set `set IFCOS_USE_OCCT=FALSE`. I will clone again and `git checkout 891448e902b4f3087fe95ceccca5458f99c844cf` right away to see if that works.

**Comment by aothms** [comment]
> Apparently Thomas forgot to commit some required file(s)?

As always. Sorry folks.

It's a shame the build scripts are not ran on CI after every commit, but none of the free services allow this kind of runtime.

**Comment by Stinkfist0** [comment]
Yeah. I wonder if it would be feasible to zip and use prebuilt dependencies for Windows/MSVC CI (AppVeyor?). BTW #449 can be closed too.

**Comment by aothms** [comment]
> prebuilt dependencies 

One option might be to use anaconda https://anaconda.org/oce/oce It's geared towards python, but should include the libs and include files.

Not sure whether it adds much though if we don't run through the full chain. I primarily develop on MSVC, missing source files would be caught on the travis gcc build.
