### ISSUE TITLE
Can't Not Build Dependents | No Patch File For Open CASCADE

### ISSUE THREAD

**Issue by TimFelice** [IfcOpenShell/IfcOpenShell#449]
Hello,

I am running "build-deps.cmd "Visual Studio 15 2017 Win64" Release Rebuild" in the Developer Command Prompt for VS 2017.

The process gets to checking out Open CASCADE 7.3.0 revision v7_3_0 then throws an error.
```
error: can't open patch 'Desktop/IFCOpenShell/IfcOpenShell/win/patches/V7_3_0.patch': No such file or directory
```

How can I fix this? Can I build Open CASCADE by itself and use the binaries?

Picture of the error:

![ifcopenshellerror](https://user-images.githubusercontent.com/38086427/44795993-00a56800-ab7a-11e8-9b44-1541226b0499.png)

Thanks

**Comment by Stinkfist0** [comment]
See #448
