### ISSUE TITLE
still unnecessary '=' in saved filters

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#4492]
Despite fix in commit adc5bea , issue #4265 there is still bug when loading saved group filters.
Unnesesary '=' is loaded and search doesn't work.
My BlenderBIM 0.0.20240401, Blender 4.0.1
Facets with problem: Attribute, Material, Classification, Location, Type, Group

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/5439c35d-9a19-48f9-b27a-7e95874e3b71)

**Comment by theoryshaw** [comment]
i can confirm this, as well.

**Comment by Moult** [comment]
The bug occurs when you save a search query. The extra "=" sign is stored in the search query, so when you load it, you can see it. So the fix only applies to newly saved queries. Older queries prior to fix will still contain the extra = signs.

Just remove the signs and resave over them and that should fix it.

**Comment by theoryshaw** [comment]
> Just remove the signs and resave over them and that should fix it.

Yep, works for me. thanks!

**Comment by theoryshaw** [comment]
Whoops, spoke too soon. 


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/6d026733-bc34-4da1-ac53-cb74cdd186dd
