### ISSUE TITLE
Remove `\n`'s if exported to an .ODS. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4497]
Would be nice if the `\n` would be removed, if exported to an .ODS. 

Either that, or have the newline show in the .ODS.
Not sure the best approach. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/98a4a3e9-3862-4f03-9664-bde82c302248)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/873faa38-e4c5-486f-85ab-5398cfbfff98)

**Comment by Moult** [comment]
This is a bit of a more subtle bug. Firstly, let's say an IFC text attribute contained a new line (e.g. `Foo\nbar`). Previously, that would be completely invisible to the user so the user would only ever see `Foobar` in Blender. After https://github.com/IfcOpenShell/IfcOpenShell/commit/bcc67ecb31ab312d209a23993aec03d87ea31af1 the user will now see `Foo\nbar`. Nice! The user can remove the new line or add new lines or whatever.

Now let's say you actually have a new line in your data. Will that be exported into ODS? Nope. We use Pandas' `to_excel()` function which uses `odfpy` which ... [has a bug](https://github.com/eea/odfpy/issues/114) where newlines are ignored. But hey, at least it results in one of the possible desired scenarios in this bug. Note that if you export as Excel you will get a true newline.

In the future we can build our own ODS exporter like we already do in IfcFM and add the `p` tags necessary for new lines. That way xlsx and ods behaviour will be consistent.

Now the next issue ... your material names never had new lines in it. In fact, you actually had the literal `\n`, i.e. in IFC your material name would be ``Foo\\nbar`` (notice the double slash). The Blender live viewport annotations would treat this fake `\\n` as a new line which is not quite correct. So after https://github.com/IfcOpenShell/IfcOpenShell/commit/bd5fd3539ace1b80e119a09d240ee9acd9e56fde your existing fake `\\n` will no longer cause newlines and only true newlines will cause newlines.

What a mouthful. In short, run this script which'll convert your fakes to real newlines.

```python
import ifcopenshell
f = ifcopenshell.open('/path/to/your/model.ifc')
for e in f.by_type("IfcMaterial"):
    e.Name = e.Name.replace("\\n", "\n")
f.write('/path/to/fixed.ifc')
```

**Comment by theoryshaw** [comment]
Thanks @Moult!

I extended the script to catch the following too...

```
import ifcopenshell
f = ifcopenshell.open('/path/to/your/model.ifc')
for e in f.by_type("IfcMaterial"):
    e.Name = e.Name.replace("\\n", "\n")
for s in f.by_type("IfcSurfaceStyle"):
    s.Name = s.Name.replace("\\n", "\n")
for t in f.by_type("IfcTextLiteralWithExtent"):
    t.Literal= t.Literal.replace("\\n", "\n")
f.write('/path/to/fixed.ifc')

```

**Comment by Moult** [comment]
Huh, I can only imagine the type of exception there to be if the literal was null, which shouldn't occur. There must be another hidden bug somewhere.
