### ISSUE TITLE
More feedback on the offending object from SvgSerializer errors

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4500]
I get the following error quite a bit when running drawings. 

To troubleshoot, i move the camera around until i don't get the error, and then move the camera incrementally back, until i get the error again.  I then deduce which geometry might be causing the problem. 

This takes quite a long time, to troubleshot. 

Am wondering, if there could be an output of some kind that tells you which objects are causing the error, so you can dial into them quickly and fix them, if possible. 

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 212, in invoke
    return self.execute(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 263, in execute
    linework_svg = self.generate_linework(context)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 538, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1577, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
RuntimeError: An unknown error occurred
```

**Comment by Andrej730** [comment]
Can you please send some example triggering "RuntimeError: An unknown error occurred"? Got some idea for a script that will help narrowing it down.

**Comment by theoryshaw** [comment]
Yes, try and run `R - ELEVATION - EAST`, in the following. 
https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/bd2401ded7db8bf456ac958f74531fed5aca9f79/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc

The offending object is called out below...
`0p2EG2ddXF_RDiEon9Jrik`

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5b992b7d-4430-4ea3-8c1a-7473178ffe28)

**Comment by Moult** [comment]
I haven't found a fast way to reliably pick up the source of the error. I have a hacky script which slowly culls elements until it finds a broken combination.

**Comment by Andrej730** [comment]
I added some debug operator that can help. in 797e2e4

Making it I've learned that in large projects we actually have a bottle neck in syncing elements before drawing creating. In my case creating 1 drawing took ~25 secs and ~20 secs of them was syncing objects. 

Syncing iterates over all available blender objects, so it's expensive on large projects. Since all objects are synced already after first run, there is no point syncing them again for each drawing if printing multiple drawings at once, so printing multiple drawings should get faster after 5c36599.

But still need to do something about that syncing process to optimize is. The syncing method is https://github.com/IfcOpenShell/IfcOpenShell/blob/5c365990b9248b6a0443f54b0ead734affab1235/src/blenderbim/blenderbim/bim/export_ifc.py#L90

and the most expensive part is running `tool.Collector.sync(obj)` for each object. Here's some profiling to get the idea what takes time in the `collector.sync`:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/656caefc-f78e-4e34-a231-be48c64f4c96)

**Comment by theoryshaw** [comment]
This is awesome!

So the offending object was `0p2EG2ddXF_RDiEon9Jrik`, but why is the `0p2EG2ddXF_RDiEon9Jrik` object under the print out that says `Excluding element didn't fixed the drawing:`? Seems confusing.  Maybe i'm not reading this correctly.  

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d06c92f2-33f3-4b7a-8ea7-566f9e2a349f)

**Comment by Andrej730** [comment]
> So the offending object was `0p2EG2ddXF_RDiEon9Jrik`, but why is the `0p2EG2ddXF_RDiEon9Jrik` object under the print out that says `Excluding element didn't fixed the drawing:`? Seems confusing. Maybe i'm not reading this correctly.

I thought it could be useful in some cases. When operator couldn't narrow down the set of elements any further it ends up with 2 elements that are failing - drawing any of them just by themselves doesn't produce errors but drawing them together produces an error:
```
Couldn't narrow it down any further.
It's some of the 2 elements:
[#4015211=IfcWall('0p2EG2ddXF_RDiEon9Jrik',$,'Wall',$,$,#4500162,#4015228,$,$), #4017076=IfcWall('0KFw8bcCf0ZAIJqgcRgSfh',$,'Wall',$,$,#4100304,#4017096,$,$)]
```

So it could be either one of them is failing or both of them or combination of them (they fail only when they are both present).
Excluding just one of them will help in the case if it's just 1 element failing: 
```
Excluding element fixed the drawing:
#4017076=IfcWall('0KFw8bcCf0ZAIJqgcRgSfh',$,'Wall',$,$,#4100304,#4017096,$,$)
```

But knowing that excluding some of the elements that fail together doesn't fix the issue could also be useful - in cases when they are both failing / failing when they are present together.
```
Excluding element didn't fixed the drawing:
#4015211=IfcWall('0p2EG2ddXF_RDiEon9Jrik',$,'Wall',$,$,#4500162,#4015228,$,$)
```

Full output from operator without noise:
```
processing 462 elements
processing 231 elements
processing 115 elements
processing 57 elements
processing 29 elements
processing 15 elements
Will try to reshuffle elements and try again, attempt 1/10
processing 15 elements
Will try to reshuffle elements and try again, attempt 2/10
processing 15 elements
Will try to reshuffle elements and try again, attempt 3/10
processing 15 elements
processing 8 elements
Will try to reshuffle elements and try again, attempt 1/10
processing 8 elements
processing 4 elements
Will try to reshuffle elements and try again, attempt 1/10
processing 4 elements
Will try to reshuffle elements and try again, attempt 2/10
processing 4 elements
Will try to reshuffle elements and try again, attempt 3/10
processing 4 elements
processing 2 elements
Couldn't narrow it down any further.
It's some of the 2 elements:
[#4015211=IfcWall('0p2EG2ddXF_RDiEon9Jrik',$,'Wall',$,$,#4500162,#4015228,$,$), #4017076=IfcWall('0KFw8bcCf0ZAIJqgcRgSfh',$,'Wall',$,$,#4100304,#4017096,$,$)]
Let's test excluding them...

Excluding element fixed the drawing:
#4017076=IfcWall('0KFw8bcCf0ZAIJqgcRgSfh',$,'Wall',$,$,#4100304,#4017096,$,$)
```

**Comment by aothms** [comment]
Is there something I can look into here?

**Comment by Andrej730** [comment]
> Is there something I can look into here?

@aothms This one is resolved in the current build 👍

**Comment by theoryshaw** [comment]
Thankful for this functionality.
