### ISSUE TITLE
Trackball error on enabling addon

### ISSUE THREAD

**Issue by kalpit3d** [IfcOpenShell/IfcOpenShell#4502]
I have tried to install addon just like usual procedure of installing by zip file but when i click on enable it gives lots of error. I tried it in 3.6 and 4.0 version both. Please anyone suggest me alternative ways to do it.

**Comment by theoryshaw** [comment]
what does the error say?...

also make sure you download the correct release relative to the Blender version...

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/docs/devs/installation.rst#unstable-installation

**Comment by theoryshaw** [comment]
Is your problem, the same as what's discussed here?: https://community.osarch.org/discussion/comment/19988/#Comment_19988

**Comment by Moult** [comment]
The latest version needs Blender 4.1. If you want to use less than that, you need to download the py3.10 builds. See https://blenderbim.org/docs/users/installation.html
