### ISSUE TITLE
BlenderBIM, linked models, add ifc as linked model if it is dropped into BlenderBIM window

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#4505]
I do not know if it would possible, but it would be very helpful if a model would be linked if its icon was dropped from the file manager into the BlenderBIM window.

**Comment by berndhahnebach** [comment]
IMHO intuitively it shlould link it, because open a ifc for authoring happen sometimes (for me less than 10 times a day if BlenderBIM is used) but linking for me happens all the time ... If BlenderBIM is used it happens 10 to 100 times a day. Thus it would speed things up very much.

**Comment by aothms** [comment]
There are modifier keys you can press with drag'n'drop https://ux.stackexchange.com/a/83769

**Comment by Andrej730** [comment]
Implemented in 75e6495

**Comment by Moult** [comment]
I think linking makes more sense as a default personally, is it possible to change the default?
