### ISSUE TITLE
IfcConvert on Google Colab

### ISSUE THREAD

**Issue by zwh988** [IfcOpenShell/IfcOpenShell#4508]
Hi kind people, is there anyway that I can use IfcConvert library on Google Colab environment. I need to convert some .ifc files into .obj. Thank you

**Comment by Moult** [comment]
https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#google-colab

https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html#geometry-serialisation

**Comment by zwh988** [comment]
Issue when converting IFC to OBJ. Code snippet below.

```
settings = ifcopenshell.geom.settings()
settings.set(settings.STRICT_TOLERANCE, True)
settings.set(settings.INCLUDE_CURVES, True)
# Setting element GUIDs is optional, but useful to uniquely identify objects in non-semantic formats.
settings.set(settings.USE_ELEMENT_GUIDS, True)
# Note that applying default materials is required in glTF serialisation.
settings.set(settings.APPLY_DEFAULT_MATERIALS, True)

# serialiser = ifcopenshell.geom.serializers.gltf("output.glb", settings)
# Alternatively, this is an example for OBJ
serialiser = ifcopenshell.geom.serializers.obj(obj_output_path, mtl_output_path, settings)
serialiser.setFile(ifc_file)
serialiser.setUnitNameAndMagnitude("METER", 1.0)
serialiser.writeHeader()

iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
if iterator.initialize():
    while True:
        serialiser.write(iterator.get())
        if not iterator.next():
            break
serialiser.finalize()
```

The input ifc file consists of a few IfcSlabs and IfcWalls in 3 storeys. After running the conversion, the elements in the .obj file appears to have defaulted to the origin location. Screenshots attached below.

![SS ifc file](https://github.com/IfcOpenShell/IfcOpenShell/assets/133757959/93e85c2b-e638-4ba2-b0e6-b4c32ae1542d)
![SS obj file](https://github.com/IfcOpenShell/IfcOpenShell/assets/133757959/d649fcf4-a6f5-435f-aa63-755c2b759d2e)

**Comment by aothms** [comment]
If you use OBJ output you have to set settings.USE_WORLD_COORDS to true.
There are some hard dependencies between serializers and settings from
before these were accessible by public api.

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op do 4 apr 2024 08:02 schreef zwh988 ***@***.***>:

**Comment by emmyxth** [comment]
hello! it seems like this library documentation is not working for me: https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#google-colab

is it my computer or is the site down?
<img width="979" alt="Screenshot 2024-04-05 at 9 31 12 AM" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/93239069/20175c5e-cf34-4247-8090-a9a2f0570167">
