### ISSUE TITLE
Spreadsheet import/export problem

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#4509]
Step to reproduce
- open one new BBim fresh file with Demo library IFC4
- create a wall
- go to quality and coordnation - > collaboration -> spreadsheet import/export
- add just 1 attribute clicking on "add csv attribute"
- click on "Export IFC to CSV"
- select the path
It throws this error (on linux and on windows)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/f07ef72a-1d48-4162-bdbe-199b8567a699)

**Comment by theoryshaw** [comment]
dumb question, did you add a search group first?

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/8a5043b6-f6a8-4d2d-b94b-935606ca3bec)

**Comment by maxfb87** [comment]
@theoryshaw actually no, so this is the problem :-)
I thought it selects all entities if no search was defined but it makes sense to have to insert a search query.
Thanks for the feedback!
