### ISSUE TITLE
IfcConvert Version 0.7 .obj output file is missing the "mtllib" line

### ISSUE THREAD

**Issue by RacingTadpole** [IfcOpenShell/IfcOpenShell#4514]
I have downloaded both `IfcConvert-v0.6.0-721fe47-macos64/IfcConvert` and `IfcConvert-v0.7.0-f0e03c7-macos64/IfcConvert` and run them both on `src/ifcpatch/test/files/basic.ifc` as follows:
```sh
IfcConvert  --use-world-coords --angular-tolerance=0.5 basic.ifc output.obj
```

Version 0.6 produces a file that begins
```
# File generated by IfcOpenShell 0.6.0b0
mtllib output.mtl
g product-805ed948-c11e-48e4-939c-72ef818960b0-body
s 1
v 1 1 1
```

Version 0.7 produces a file that begins
```
# File generated by IfcOpenShell v0.7.0-f0e03c79d
g product-805ed948-c11e-48e4-939c-72ef818960b0-body
s 1
v 1 1 1
```

The line `mtllib output.mtl` is missing in version 0.7. 

That matters because [obj2gltf](https://github.com/CesiumGS/obj2gltf/tree/main) requires that line to see the `.mtl` file.

**Comment by Moult** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/commit/532869a48ae06086a7043cd72040862dd8e97153
