### ISSUE TITLE
Error when I press the checkbox to enable the Add-on

### ISSUE THREAD

**Issue by claudiuiancic** [IfcOpenShell/IfcOpenShell#4515]
I have a MacBook Pro 16 inch 2021 with M1 Max and 64 GB memory, macOS 14.4.1.
I just installed Blender 4.1.0 and blenderbim-240402-py310-macosm1.
When I try to enable BlenderBIM from the checkbox I got this:
<img width="844" alt="Screenshot 2024-04-05 at 07 40 24" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/58459582/c0eefb53-404d-4442-a5f5-d8b52efef7fc">
What should I do?
Please help me.

**Comment by Moult** [comment]
You need py311 not py310

**Comment by claudiuiancic** [comment]
I have Python 3.11 but still got the same error :(

**Comment by Moult** [comment]
https://docs.blenderbim.org/users/installation.html#faq See FAQ number 4?
