### ISSUE TITLE
Wheel package on pypi for windows does not want to install version for py312

### ISSUE THREAD

**Issue by piotr-smolira** [IfcOpenShell/IfcOpenShell#4518]
I'm not sure if it has something to do with requirements, but I can't install package on python 3.12.

**Comment by Moult** [comment]
This was literally just updated earlier today, can you try again? See the packages here https://pypi.org/project/ifcopenshell/#files

**Comment by piotr-smolira** [comment]
I've checked before submitting the issue. On pypi's page the requirement is <3.12 and this is what it pops out when trying to actually install.
`Ignored the following versions that require a different python version: 0.7.0.240405 Requires-Python <3.12,>=3.6`

I believe marking it as <=3.12 could solve it but I don't really know if it is as a much more than that.

**Comment by piotr-smolira** [comment]
I also downloaded wheel package and tried to install it directly. The same error.

**Comment by Moult** [comment]
I think it's because I forgot the update the pyproject.toml metadata. Can we wait 1 day for it to try and build again tomorrow?

**Comment by piotr-smolira** [comment]
Of course! I'm comfortable with 3.11. I was browsing through the source code trying to find what file I should change to update the info, almost got there :D

**Comment by Moult** [comment]
@piotr-smolira cheers, can you help try again?

**Comment by piotr-smolira** [comment]
It works. Thanks @Moult !
