### ISSUE TITLE
Feature request: Support for line segments

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#452]
1. Convert any of the following files:
https://github.com/IfcOpenShell/files/blob/master/452--line-segment-straight.ifc
https://github.com/IfcOpenShell/files/blob/master/452--line-segment--curved.ifc
2. Experience that the conversion ends with no output geometry from IfcOpenShell:
```No geometrical entities found```
3. Experience that the same line segments are visualized in Solibri with a width of ca 1 cm:
<img height="200" alt="screen shot 2018-09-03 at 22 45 02" src="https://user-images.githubusercontent.com/4601554/45001253-e03b3a80-afcb-11e8-84e4-ca002b66a318.png"><img height="200" alt="screen shot 2018-09-03 at 22 45 35" src="https://user-images.githubusercontent.com/4601554/45001254-e03b3a80-afcb-11e8-86be-e595effd69e6.png">

––––––––––––––––––––––––––––––

I am not sure whether this is within the core functionality of IfcOpenShell, however I think it can be a quite useful feature. Either enabled by default or behind a flag. Use cases span from visualizing IfcAxisGrid to visualizing electrical cables:

<img width="500" alt="screen shot 2018-09-03 at 22 23 01" src="https://user-images.githubusercontent.com/4601554/45001270-095bcb00-afcc-11e8-84f0-42478dc20eaa.png">

**Comment by aothms** [comment]
This exists!

You can invoke this with `IfcConvert --plan`. If you want both lines and surfaces you'll need to call `IfcConvert --plan --model`.

The lines are written as actual line segments in the DAE / OBJ file. Rather inefficient actually it seems in DAE, but they are there.

~~~xml
<source id="representation-30319-positions">
          <float_array id="representation-30319-positions-array" count="132">66300 83035 -100 66319.56742999999 83232.79872999999 -100 66319.56742999999 83232.79872999999 -100 66409.75281 83411.07678 -100 66409.75281 83411.07678 -100 66532.36682999999 83567.76935 -100 66532.36682999999 83567.76935 -100 66700.81592999999 83674.97410999999 -100 66700.81592999999 83674.97410999999 -100 66886.11388 83746.90789 -100 66886.11388 83746.90789 -100 67085.97659 83750 -100 67085.97659 83750 -100 67285.97659 83750 -100 67285.97659 83750 -100 67485.97659 83750 -100 67485.97659 83750 -100 67685.97659 83750 -100 67685.97659 83750 -100 67885.838 83754.83093999999 -100 67885.838 83754.83093999999 -100 68083.00652999999 83787.17978999999 -100 68083.00652999999 83787.17978999999 -100 68272.93227 83849.22884999999 -100 68272.93227 83849.22884999999 -100 68451.37192 83939.17863999999 -100 68451.37192 83939.17863999999 -100 68626.53422 84035.52637999999 -100 68626.53422 84035.52637999999 -100 68818.28243 84089.93179 -100 68818.28243 84089.93179 -100 69017.2719 84085.28912 -100 69017.2719 84085.28912 -100 69200.87858 84009.07302999999 -100 69200.87858 84009.07302999999 -100 69358.52151 83886.10126999999 -100 69358.52151 83886.10126999999 -100 69534.46249 83792.31037999999 -100 69534.46249 83792.31037999999 -100 69729.18111999999 83749.45462999999 -100 69729.18111999999 83749.45462999999 -100 69929.11848 83747.10826999999 -100 69929.11848 83747.10826999999 -100 70046.75269999999 83747.10826999999 -100</float_array>
          <technique_common>
            <accessor source="#representation-30319-positions-array" count="44" stride="3">
              <param name="X" type="float"/>
              <param name="Y" type="float"/>
              <param name="Z" type="float"/>
            </accessor>
          </technique_common>
        </source>
        <vertices id="representation-30319-vertices">
          <input semantic="POSITION" source="#representation-30319-positions"/>
        </vertices>
        <lines material="IfcFlowSegment" count="2">
          <input semantic="VERTEX" source="#representation-30319-vertices" offset="0"/>
          <p>0 1 </p>
        </lines>
        ...
~~~

E.g. blender can import them nicely. Note that these two particular files do not have unit information so they end up approx 1000 times too big.

<img width="903" alt="2018-09-05" src="https://user-images.githubusercontent.com/1096535/45084720-470d4080-b0ff-11e8-94d0-ee8c3184dd05.png">

**Comment by johanrd** [comment]
Oh, nice:) thanks! 👍
