### ISSUE TITLE
Unsupported syntax for Python 3.9

### ISSUE THREAD

**Issue by KaareH** [IfcOpenShell/IfcOpenShell#4522]
In commit 8aecee583677ab999a549f40436fd2711ab13fa1 the union operator `|` is used, which is only supported in Python > 3.9.

If one tries to `import ifcopenshell.util.unit`, `TypeError: unsupported operand type(s) for |: 'type' and 'type'` is raised.

Using `ifcopenshell==0.7.0.240405` and `Python==3.9.10`.

**Comment by sebphi** [comment]
I believe this is a duplicate of #4520

**Comment by KaareH** [comment]
> I believe this is a duplicate of #4520

Yes, indeed. You were one minute ahead of me, closing this.

**Comment by sebphi** [comment]
Yeah, slightly. :)
However, i believe the text from your issue would add more insight into the issue. Would you like to add a comment there?
