### ISSUE TITLE
IfcConvert silently ignores --include when output format is IFC

### ISSUE THREAD

**Issue by wlinna** [IfcOpenShell/IfcOpenShell#4525]
I'm trying to select only two components with given GlobalIds. It works for glTF output, but it doesn't work for IFC. Instead, IfcConvert exports the whole IFC model. At the very least, a warning should be given that IFC export ignores `--include`. W

You can test this by downloading the following IFC

https://raw.githubusercontent.com/andrewisen/bim-whale-ifc-samples/main/BasicHouse/IFC/BasicHouse.ifc

And then running the following command

```
./IfcConvert  -v --include attribute GlobalId 1yETHMphv6LwABqR4Pbs5g attribute GlobalId 1yETHMphv6LwABqR0Pbs5g --use-element-guids <Path/to/BasicHouse.ifc> ./BasicHouse_roof.ifc
```

My version of IfcConvert: `IfcConvert-v0.7.0-f7c03db-linux64`

**Comment by Moult** [comment]
My guess is that this is out of scope for IfcConvert. Getting a filtered list of elements in IFC is a bit trickier, as you need to decide what happens to shared materials, types, profiles, construction resources, cost items, task activities, spatial tree, and so on.

Instead you can use IfcPatch: https://docs.ifcopenshell.org/ifcpatch.html

**Comment by wlinna** [comment]
Okay, thanks for the tip :)

as for IfcOpenShell and this feature, it might be out of scope, but I do think that this should be mentioned in the IfcConvert CLI help to save the trouble in the future. It might make sense to keep this issue open until that.

Of course, keeping issue tracker clean is important as well

**Comment by aothms** [comment]
I agree it can be confusing. It came up before. Maybe you'd be interested in contributing to check a couple of arguments to be unset https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcconvert/IfcConvert.cpp#L752

In the long run we should really couple the program options to specific serializers.

**Comment by wlinna** [comment]
Yeah, I suppose I could give it a go

**Comment by wlinna** [comment]
I'm trying to follow the compilation instructions for Linux. They didn't work out of the box, and I had to modify the `cmake `-command for example:

(Notice that I had to leave OCC dirs out of this command because the automatic search seemed to work while the ones in instructions failed)

```
cmake ../cmake \
      -DBUILD_IFCPYTHON=Off \
      -DCOLLADA_SUPPORT=Off \
      -DHDF5_SUPPORT=Off \
      -DCGAL_INCLUDE_DIR=/usr/include \
      -DMPFR_INCLUDE_DIR=/usr/include \
      -DMPFR_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu
      -DGMP_INCLUDE_DIR=/usr/include \
      -DGMP_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu 
```

When I finally got  to the compilation phase, I get this error. Sorry for the Spanish — I like immersing myself to my targuet language. It says: The file or directory does not exist

```
IfcOpenShell/src/ifcgeom/../ifcgeom_schema_agnostic/IfcGeomTree.h:65: fatal error: H5Cpp.h: No existe el archivo o el directorio
   65 | #include "H5Cpp.h"

```

I'm not going to pursue this further on my own, because IfcOpenShell is only tangentially related to what I'm doing. My goal is to actually produce a simplified model so that I can report an issue in [ThatOpen/engine_components](https://github.com/ThatOpen/engine_components). However, if there's an easier way to compile this, I will gladly continue.

**Comment by wlinna** [comment]
In case someone finds this issue trying to create an IFC with just the included set of components, you can do it with IfcPatch like so:
```
python3 -m ifcpatch -i BasicHouse.ifc -o BasicHouse2Pieces.ifc -r ExtractElements -a "1yETHMphv6LwABqR4Pbs5g,1yETHMphv6LwABqR0Pbs5g"   
```

Make sure your Python environment has `shapely`, `lark`, `ifcopenshell` a recent version of `numpy` installed.

The selector syntax is documented here
https://docs.ifcopenshell.org/ifcopenshell-python/selector_syntax.html#filtering-elements
