### ISSUE TITLE
Property search fails when regex is in the first index

### ISSUE THREAD

**Issue by OrionSehn** [IfcOpenShell/IfcOpenShell#4534]
Property search fails when regex is in the first index:

# Example 1 - Works as expected
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/19eff825-ef96-4bad-8e49-273c37f926dd)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/60c3cdb2-1c45-41e4-892c-b80aaf046a03)

# Example 2 - Works as expected
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/889c79e2-15a4-42de-91f6-6a9bac99a223)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/79bdec0c-404e-426c-bd87-935fd78b368f)

# Example 3 - Fails
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/519274ce-d1e9-4866-862d-051c7cd5dea8)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/b12f8171-7d25-4260-85b8-71e5971381cc)

Looks like it might be a problem with IFCOpenShell

**Comment by Moult** [comment]
Your regex is invalid. See https://regex101.com/

The `*` token is a quantifier, which means that it says "any quantity of the thing before it". If you don't have a thing before it, then it is invalid.

**Comment by OrionSehn** [comment]
Thanks for the reference! Sorry for the misdirection
