### ISSUE TITLE
Typo error: 'gtlf' mistakenly used instead of 'gltf'

### ISSUE THREAD

**Issue by alperkantarci** [IfcOpenShell/IfcOpenShell#4535]
I'm getting `AttributeError: type object 'serializers' has no attribute 'gltf'` error in the latest version.

I think at [this line](https://github.com/IfcOpenShell/IfcOpenShell/blob/24716a008916f48fdaf017912093fc2f291c83d2/src/ifcopenshell-python/ifcopenshell/geom/main.py#L316) appears to be a typo error where '**gtlf**' is used instead of '**gltf**'

**Comment by Moult** [comment]
@alperkantarci awesome! Would you be interested in fixing this? Just go to that line you linked to and Github will have an edit button that will guide you through the process
