### ISSUE TITLE
Question: Why are older versions of IfcOpenShell on PIP not available?

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#4545]
I tried installing requirements from a requirements.txt file, but was hit with an error:

`ERROR: No matching distribution found for ifcopenshell==0.7.0.230818`

I looked over at https://pypi.org/project/ifcopenshell/#history  and noticed that, indeed the version no longer existed.  I'm curious why this is?

**Comment by Moult** [comment]
PyPI has a filesize limit of 10GB or something. After we hit this, we have no choice but to either petition to PyPI or delete older entries.

**Comment by vulevukusej** [comment]
I see, thats interesting.  Thanks for the quick reply.

**Comment by MarcosCobena** [comment]
@Moult may you be aware whether we could find those deleted packages for referencing them locally? We depend on 0.7.0.230329 but cannot find it anywhere. Thank you in advance.

/cc @gabrielgt

**Comment by Moult** [comment]
@MarcosCobena https://github.com/IfcOpenShell/IfcOpenShell/releases ?

**Comment by MarcosCobena** [comment]
> @MarcosCobena https://github.com/IfcOpenShell/IfcOpenShell/releases ?

By around March 3rd, 2023, there are no releases matching the same versioning schema, but others like 0.7.0-??? in the form of prereleases.

**Comment by Moult** [comment]
I think the date should be good enough. What exactly do you need from that particular version that doesn't exist now?

**Comment by MarcosCobena** [comment]
I need support for Python 3.7 which was dropped after, and the following imports:

![imagen](https://github.com/IfcOpenShell/IfcOpenShell/assets/1142782/0b0b9ae9-882f-4a71-a17c-a19764fc107e)

**Comment by Moult** [comment]
You should be good to just grab any release about that date which has py37 in the name.
