### ISSUE TITLE
Issues building IfcOpenShell library when target architecture is 'x64'

### ISSUE THREAD

**Issue by SoftwareMechanic** [IfcOpenShell/IfcOpenShell#4557]
Hello everyone,
I was building IfcOpenShell in order to create my program on top of it, but I found that when I try to build with target architecture set to x64 (with following command -> ...\myrepo\IfcOpenShell\win> '.\build-deps.cmd vs2019-x64 ') I got a lot of errors, most of them seems related to sqlite3.

and of course the build fails.

after run that command I end up with a folder structure like the following:

--_deps-vs2019-x64-installed
----sqlite3
------bin
--------sqlite3.exe
------include
--------sqlite3.h
------bin
--------sqlite3.lib

and nothing more in the folder.

I tried also on VS2022 but I got a similar results.

I've seen similar issues but if I am not wrong I don't see a solution to those issues.

Do you know some workarounds ?

someone faced something like this?

CMakeError.log :
```Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/user/repo/IfcOpenShell/cmake/out/build/x64-Debug/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_ec0f3 && [1/2] Building C object CMakeFiles\cmTC_ec0f3.dir\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_ec0f3.dir/CheckIncludeFile.c.obj 

C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_ec0f3.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_ec0f3.dir\ /FS -c CheckIncludeFile.c

CheckIncludeFile.c(1): fatal error C1083: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.
```

 the issue could be pthread.h

I am facing lots of error like this:

```
    21>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1074,5): error MSB6006: "link.exe" end with code -1073741502. [C:\Users\user\source\repos\IfcOpenshell\_deps\proj-9.2.1\_build
       -vs2019-x64\src\apps\binproj.vcxproj]
```

Thank you in advance

OS: Windows10
IDE: VisualStudio 2019 16.11.21

**Comment by aothms** [comment]
> CheckIncludeFile.c(1): fatal error C1083: 'pthread.h': No such file or directory

This is not an error. CMake just checks whether pthread.h exists to configure the compilation. On windows this is supposed to 'fail'. I wish CMake was a bit clearer on this, I got similar questions before, but it comes a bit from the autoconf days where users would see ton of checks on the compilation environment to configure the build.

> 21>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1074,5): error MSB6006: "link.exe" end with code -1073741502. [C:\Users\user\source\repos\IfcOpenshell\_deps\proj-9.2.1\_build

This is unfortunately not something we likely can fix on our side. This appears to be an internal error in the MS linker. Can you try and update MSVC? Maybe it runs out of memory? Do you have more output of the log that come in front of this?

**Comment by SoftwareMechanic** [comment]
SOLVED:

I Have been able to build dependencies for x64 architecture within Visual Studio 2022, I just had to install 'proj' using vcpkg, otherwise the build-deps.cmd will fail (at least on my pc).

I keep this issue opened just for reference in case you want to test and fix this issue when building deps, but for me can be closed.

**Comment by justZZY** [comment]
> SOLVED:
> 
> I Have been able to build dependencies for x64 architecture within Visual Studio 2022, I just had to install 'proj' using vcpkg, otherwise the build-deps.cmd will fail (at least on my pc).
> 
> I keep this issue opened just for reference in case you want to test and fix this issue when building deps, but for me can be closed.

I have the same compile error but when I try to use `x64 native tools command` in VS that everything is ok.
