### ISSUE TITLE
BlenderBIM created IFC windows and doors are not shown in Web IFC viewer

### ISSUE THREAD

**Issue by vivenHu** [IfcOpenShell/IfcOpenShell#4559]
Thanks for the great tool. I'm new to IFC model and got some problem using blenderBIM to generate IFC model

I tested to create a door and a window on a simple wall using the types from IFC4 demo template. 
I try to show it on the web viewer from ThatOpen/engine_web-ifc demo viewer:
 the window and door are flickering on the wall
![blenderbim_web_viewer_demo_template](https://github.com/IfcOpenShell/IfcOpenShell/assets/85647844/ec11dedc-f1aa-4cbf-98e5-d76711e75315)
I created the templates based on the demo, and It turn out to be okay
![blenderbim_web_viewer_my_template](https://github.com/IfcOpenShell/IfcOpenShell/assets/85647844/84f1f437-8a30-4c52-853e-3d05e9467446)

I also tested with the old ifc.js viewer, the IFC demo template created IFC is still flikcering.
the IFC model using  new created templates even dont have the window showing and the door only show on one side. 
![blenderbim_ifc js_viewer_my_template](https://github.com/IfcOpenShell/IfcOpenShell/assets/85647844/e58eb48d-734a-48c9-963e-60dbf1c8bf44)

There maybe some problem with the viewer, but I want to know if there's anything witht the IFC file I created? Thank you for you help and i really need some help for this. 

IFC file used are attached 
[test_ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15001515/test_ifc.zip)

**Comment by Moult** [comment]
There's nothing wrong with the file (well the one called "test_my_templates.ifc" has objects outside the spatial tree which isn't ideal, but not technically invalid) you created and I tested your files on https://platform.thatopen.com/app and they seem to work fine.

BTW you can always use the validate functions in the BlenderBIM Add-on to check. This is the same validation that powers the buildingSMART validation.

If it doesn't work on your particular version of IFCJS I guess it's a problem on your end or a bug with IFCJS.

![2024-04-18-220603_379x326_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/68e8f863-07a9-4571-af38-be20b2b350c2)
![2024-04-18-220554_715x571_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/20e42607-4e32-4061-b17f-8692692445ce)

**Comment by vivenHu** [comment]
Thank you very much for the quick reply, and Thank you very much for your huge effort put in this addon, it's amazing how much it can achieve. 
Just tested using Thatopen viewer you mentioned, it's shown perfectly. Seems the demo viewer provided in Thatopen's github page is not so updated. For the IFC.js I used, I agree there is bug or it's outdated, thank you for your confirmation.

I just know that BlenderBIM also have the validation tool, thanks, that's really useful information.
