### ISSUE TITLE
Error when try to use ifcopenshell.api.run("spatial.assign_container")

### ISSUE THREAD

**Issue by jaymeandretta** [IfcOpenShell/IfcOpenShell#4562]
Im getting this error when I try to use ifcopenshell  module run("spatial.assign_container"... in **terminal installed by pip**

```
File "C:\XX\XX\AppData\Local\Programs\Python\Python312\Lib\site-packages\ifcopenshell\api\__init__.py", line 67, in run
    result = usecase_class(ifc_file, **settings).execute()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Usecase.__init__() got an unexpected keyword argument 'product'
```

The error doesn't happen when I run the module **using the python environment on BlenderBIM**.

Is this something related to modules dependencies?

**Comment by Moult** [comment]
Sorry this is in the middle of being changed. For a quick fix, use products (notice the s at the end) giving an iterable of products. In the next PyPI release we'll support both product and products, but product will be deprecated in the future (in favour of batch calls which are more efficient).
