### ISSUE TITLE
Have a preference to set if spatial elements are selectable or not upon opening an ifc file. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4563]
Have a preference to set if spatial elements are selectable or not upon opening an ifc file. 

note to self: https://github.com/IfcOpenShell/IfcOpenShell/commit/976eeaef20e591400a7e992d77c2646bdb382d27

**Comment by theoryshaw** [comment]
convo: https://matrix.to/#/!ssOmSJysZpXBupsgjO:matrix.org/$x7h3zfJbfSeiwuFECxFks_ZAfyupjVccz54fmILAdNA?via=matrix.org&via=fozyjoln.dedyn.io&via=infeeeee.duckdns.org

**Comment by vitorhpmartins** [comment]
@theoryshaw  I found how to set the default for the “selectable” option to always be active 
![blender_wWfCNQoXQg](https://github.com/IfcOpenShell/IfcOpenShell/assets/116745805/bbb7512d-7353-4906-ba97-fcfe422c50d3)
