### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by antalvarenga-ic** [IfcOpenShell/IfcOpenShell#4572]
The current version of the PyPI package, 0.7.0.240418, still has the dateutil error. I saw that the fix has been made but the PyPI package has not been updated yet.
Please update the PyPI package.

**Comment by Andrej730** [comment]
ifctester?

**Comment by antalvarenga-ic** [comment]
Sorry maybe I wasn't clear, I was referring to IfcOpenShell: [https://pypi.org/project/ifcopenshell](url).

when doing `poetry add ifcopenshell` it returns
`Because ifcopenshell (0.7.0.240418) depends on dateutil (*) which doesn't match any versions, ifcopenshell is forbidden.
So, because neom-be depends on ifcopenshell (0.7.0.240418), version solving failed.`

**Comment by Andrej730** [comment]
Updated it too.

**Comment by antalvarenga-ic** [comment]
Thanks! All good now.
