### ISSUE TITLE
Error to add new Custom Pset to selected elements via "Bulk add/edit Custom Properties"

### ISSUE THREAD

**Issue by jaymeandretta** [IfcOpenShell/IfcOpenShell#4574]
I am trying to add to select elements **a custom pset value** to filter them on extraction via **csv export**.

To do this, I tried the "Bulk add/edit Custom Properties"

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/43808639/0c94ed41-0db3-4aad-a986-890157c04bda)

But im getting an error.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/43808639/5a84be5e-3ae4-4d43-b99b-c1b793764a6a)

Am I doing something wrong or it is a bug?

Tks in advance.

**Comment by theoryshaw** [comment]
It might be. 
You might know this already, but I like to use the following for applying a pset value in bulk. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/4765f411-024b-40f3-9470-bca42cf967cc)

**Comment by jaymeandretta** [comment]
> It might be. You might know this already, but I like to use the following for applying a pset value in bulk.
> 
> ![image](https://private-user-images.githubusercontent.com/507113/324972082-4765f411-024b-40f3-9470-bca42cf967cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDMyOTksIm5iZiI6MTcxMzkwMjk5OSwicGF0aCI6Ii81MDcxMTMvMzI0OTcyMDgyLTQ3NjVmNDExLTAyNGItNDBmMy05NDcwLWJjYTQyY2Y5NjdjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMDA5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWJhN2U5ZDFhNTc1OGM5MGIyZDNlODY1YThmNWJhMGFjYmM1MDU5ZDM5OTFhYjhmMDI1ZDdhMzY3NGVjOGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1SgdfYklJfGZ_9WnZOxSePHoHGwEYNJjnUh9IJQSUPA)

Yeah. I know this approach. The downside of this option is that you need to have the Pset previosly createad on the elements to copy the value.

I thought that by "Bulk add/edit Custom Properties" I could take a shortcut. Create the custom pset and set the values at the same time. 

Furthermore, "Bulk add/edit Custom Properties" allows creating a custom pset by selection, (I don't know any other tool on BB that allows to do that by selction).

But thanks for your help @theoryshaw !

**Comment by Andrej730** [comment]
Thanks for the report. It wasn't related to the "Bulk add/edit Custom Properties" in particular - it was failing on any operation that would try to create owner history and if there wasn't any IfcPersonAndOrganization in the ifc2x3 project.
