### ISSUE TITLE
An option to select all drawings and deselect all drawings

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4577]
Would be nice to have an option to select all drawings and deselect all drawings

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/20c1fa1d-0822-4b54-9e74-2d7bee5f400d)

**Comment by brunopostle** [comment]
I think there is already, or at least I think I fixed it in 579c72f

**Comment by theoryshaw** [comment]
🤦 
dooo.. thank guys!
