### ISSUE TITLE
Section reference numbers don't show anymore

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4586]
after https://github.com/IfcOpenShell/IfcOpenShell/commit/3ef823db239843bdd1104055f2229336d824cc9a or https://github.com/IfcOpenShell/IfcOpenShell/commit/fc5bb230a9807f99ebc825b866a4e2830a6a52fc the sections references did not have their reference number.  Ping @brunopostle 

![2024-04-25_12-28-53_chrome1ST_FLOOR_RCP svg_-_Google_Chromechrome](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5a37998d-084e-413a-814c-62b290af78dc)

Before those commits it looked like this. 
![2024-04-25_12-30-32_chrome1ST_FLOOR_RCP svg_-_Google_Chromechrome](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5427b33f-ed7d-45da-a6cf-72ee347246dc)

**Comment by theoryshaw** [comment]
files if you need them. 

 Restaurant_Pewaukee.blend	
 Restaurant_Pewaukee.ifc

I'm syncing the .blend/.ifc file, but i don't think that's related. 

https://hub.openingdesign.com/OpeningDesign/Restaurant_Pewaukee/src/commit/bb5e70bcd5fc4aa857c76e4a24f04563366a7079/Open/Models/BlenderBIM

**Comment by brunopostle** [comment]
Oops, will look. My recent changes are _supposed_ to only have effect when there is no sheet/layout already, ie. this code shouldn't be running for you.

**Comment by brunopostle** [comment]
Can you confirm that reverting blenderbim to before these changes restores the tags? or the new blenderbim has altered the SVG?

Are these tags usually filled in the `drawings` SVG files, or are they only filled in the generated `sheets` SVG files? (I have never used them). ie. how do I reproduce?

I've cloned your repo, but having difficulty opening any of your SVG files, they have href links that look like this:

```
    <image
       xlink:href="titleblocks%5C22x34.svg"
       x="0"
       y="0"
       width="863.59998"
       height="558.79999"
       id="image1" />
```
Note the `%5C` encoded backslash, these files don't open on my Linux system. I don't think this is the current problem, but it does indicate that BlenderBIM SVG files are not portable.

The SVG files generated here by BlenderBIM/Inkscape look like this:
```
    <image
       xlink:href="titleblocks/A2.svg"
       x="0"
       y="0"
       width="594.0"
       height="420.0"
       id="image1" />
```

**Comment by theoryshaw** [comment]
> Can you confirm that reverting blenderbim to before these changes restores the tags? 

yes, if I reset BB to before these commits, it restores these tags. 

> Are these tags usually filled in the drawings SVG files, or are they only filled in the generated sheets SVG files?

If i'm following you correctly, they are 'in' the drawing, not the sheet. 
https://hub.openingdesign.com/OpeningDesign/Restaurant_Pewaukee/src/commit/9560d936e45be24319f2b7654723853cf1b6adb9/Open/Models/BlenderBIM/drawings/1ST%20FLOOR%20RCP.svg

**Comment by brunopostle** [comment]
3ef823d and fc5bb23 only really affect layout generation, they shouldn't bother drawing generation.

There are some more recent commits by @Andrej730, e14d96e and f41fbf2, these make lots of changes to drawing generation and drawing references etc..

[edit] I can confirm that the current code generates the RCP with missing numbers in the section tags, but if I roll back to 716a33f then the tags are ok.

**Comment by theoryshaw** [comment]
@brunopostle, you're right it does happen on https://github.com/IfcOpenShell/IfcOpenShell/commit/e14d96e6ee2a12dff7c3526ebe9cde548c8f5bab and not on the previous commit before this one.   Sorry Bruno, i thought I narrowed it down more than that. 

@Andrej730 here's a quick troubleshooter file, if you need one. 
https://www.dropbox.com/scl/fo/8lxx9yv3q4j1dbvniuaje/AH_BbyxxNFNsGybIvj3sSWw?rlkey=yj1mequau0j7uz0dovyc2doea&dl=0

**Comment by Andrej730** [comment]
Thanks for the reporting and narrowing it down, it was a typo :\
