### ISSUE TITLE
Error installing BlenderBIM on MacBook Air M1 with Big Sur 11.7.10 (20G1427)

### ISSUE THREAD

**Issue by Bram1118** [IfcOpenShell/IfcOpenShell#4587]
I have been trying to install BlenderBIM on my MacBook Air M1 with Big Sur 11.7.10 (20G1427), in different versions of Blender, but it gives me errors.

Has anyone else had or been able to solve this problem?

Attached screenshots:

<img width="862" alt="Captura de Pantalla 2024-04-25 a la(s) 12 12 07" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/120762131/d908722f-809d-4489-a4be-7eb91ecd6e09">
<img width="850" alt="Captura de Pantalla 2024-04-25 a la(s) 12 18 43" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/120762131/8e6ae7ad-177e-4a50-83d2-544fab37314c">

One is with the Blender 3.6 version and the other is with the Blender 4.0 version, respectively.

**Comment by Andrej730** [comment]
@Bram1118 

What version of BBIM you're installing? If you're using Blender <4.1 then you need to use Python 3.10 version, which is available on [Releases](https://github.com/IfcOpenShell/IfcOpenShell/releases) page, also need to make sure to use MACOS M1 version and not just MACOS.

**Comment by Bram1118** [comment]
I tried to install the versions from the link you shared with me, but it still gives an error:

<img width="896" alt="Captura de Pantalla 2024-04-29 a la(s) 19 16 51" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/120762131/a1b42601-6c66-4d0f-a89e-5c4b20e53cf3">
<img width="752" alt="Captura de Pantalla 2024-04-29 a la(s) 19 18 19" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/120762131/7a02ea2e-143d-451c-8c51-fc782ef885d2">
<img width="749" alt="Captura de Pantalla 2024-04-29 a la(s) 19 18 53" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/120762131/c73a38ca-2cb5-4b06-93de-34630df2ad8d">

The version of Blender that I have installed is 4.0.2, since versions 4.1 do not start after installing.

I have a few versions of Python 3 installed, 3.10, 3.11 and 3.9

<img width="939" alt="Captura de Pantalla 2024-04-29 a la(s) 19 14 40" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/120762131/d82bc83f-b7e4-4a7e-94e1-ed73794635f4">

**Comment by Moult** [comment]
The Python you have installed on your computer does not matter. What matters is the Blender version you have (which comes with Python bundled).

First follow FAQ 4 to ensure you have a clean environment: https://docs.blenderbim.org/users/installation.html#faq

Then follow https://docs.blenderbim.org/devs/installation.html#unstable-installation to choose the correct Python version (e.g. Blender 4.0 with py310, or Blender 4.1 with py311) and OS (macosm1 for you, unless you are using Steam for Blender in which case you need to use macos, not macosm1).

**Comment by Bram1118** [comment]
I have Blender 4.0 installed, and I installed "blenderbim-240510-py310-macosm1". Now the checkbox has been checked, but it doesn't work. Gives an Error. I share the image: 

<img width="1360" alt="Captura de Pantalla 2024-05-10 a la(s) 12 23 15" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/120762131/e51f5310-ddcf-4632-ad41-40fcd16cda5e">

**Comment by Moult** [comment]
Can you share the error message too? You need to press the button to copy the error message, then paste it here.

**Comment by Bram1118** [comment]
Yes, I share it below:

os: Darwin
os_version: Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_ARM64_T8101
python_version: 3.10.13
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 4.0.2
blenderbim_version: 0.0.240510
last_actions: 
last_error: Traceback (most recent call last):
  File /Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/__init__.py, line 88, in <module>
    import blenderbim.bim
  File /Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/__init__.py, line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File /Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/handler.py, line 25, in <module>
    import blenderbim.tool as tool
  File /Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/tool/__init__.py, line 30, in <module>
    from blenderbim.tool.document import Document
  File /Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/tool/document.py, line 23, in <module>
    from blenderbim.bim import import_ifc
  File /Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/import_ifc.py, line 43, in <module>
    from blenderbim.bim.module.drawing.prop import ANNOTATION_TYPES_DATA
  File /Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/drawing/__init__.py, line 20, in <module>
    from . import ui, prop, operator, handler, gizmos, workspace
  File /Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/drawing/operator.py, line 49, in <module>
    from lxml import etree
ImportError: dlopen(/Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/lxml/etree.cpython-310-darwin.so, 2): Library not loaded: @rpath/libxslt.1.dylib
  Referenced from: /Users/abrahamsm/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/libs/site/packages/lxml/etree.cpython-310-darwin.so
  Reason: image not found

**Comment by Moult** [comment]
We recently fixed up the lxml packaging. I think (hope?) this is now solved.

**Comment by Bram1118** [comment]
Hello, I finally updated my computer's operating system to the latest one and now BlenderBIM works fine. Thank you very much for the help.
