### ISSUE TITLE
Missing window content "Representations" in ifc 2x3 when editing a type object.  

### ISSUE THREAD

**Issue by jsaarane** [IfcOpenShell/IfcOpenShell#4592]
When trying to edit the 2D appearance of a type object in 2x3 ifc I noticed that the properties window is missing the options. Then If you place an object and go edit that you have those options. They are only missing in the typeobject. 
<img width="1283" alt="question" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/13415484/4ca1ff66-5b59-432a-9cfe-c60c820fb888">

**Comment by Andrej730** [comment]
thanks for the bug report, you can test the fix in the daily build from github releases page
