### ISSUE TITLE
BlenderBIM Ifc2Sql Patch/Export Fails

### ISSUE THREAD

**Issue by bsmithuk** [IfcOpenShell/IfcOpenShell#4599]
I've tried running the Ifc2sql patch on the Prairie models (Link: https://prairieskyconsulting.com/examples) within BlenderBIM. The model is loaded into memory however I've also tried exporting without the model in memory but get the same error regarding the export:

```
Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcpatch\recipes\[Ifc2Sql.py](http://ifc2sql.py/)", line 466, in insert_data
self.c.executemany("INSERT INTO psets VALUES (?, ?, ?, ?);", pset_rows)
sqlite3.ProgrammingError: Error binding parameter 4: type 'list' is not supported
```

I've attached the error logs and happy to provide further testing if bug is resolved.
![2](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/21c38454-9181-49c9-af72-dbaa2cd46ac0)
![1](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/13b2a51f-4069-414c-ab70-820b382afef8)

**Comment by Andrej730** [comment]
Thank you for the bug report, resolved in the latest build available on github releases.

**Comment by bsmithuk** [comment]
Thanks Andrej!
