### ISSUE TITLE
Fragmentation of geometry after IFC join

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4600]
Intuitively, I feel like this should work, but perhaps I'm missing something. File: [join.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15188182/join.ifc.txt)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/46e58845-fa62-4f3b-a680-6c7150fa33ae

**Comment by Gorgious56** [comment]
Is the small one a rectangular extrusion or a tesselation ?

**Comment by theoryshaw** [comment]
tesselation. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/95b5be72-f6db-40bd-9d80-6f033deb5e75)

**Comment by theoryshaw** [comment]
yeahhh
