### ISSUE TITLE
IfcCSV - importing enumerated values doesn't work

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#4608]
When we export enumerated values from e.g. Pset_WallCommon.Status we get list of list of values. Properties separated by `;` (semicolon) and enumerated string values separated by `,` (comma). But when we import that csv file, using the same settings, enumerated values stay with no changes, error in console.

Enumerated values:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/a0f778e3-85e1-463f-bff7-5008f9faaa95)

Export setting:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/fcd41a27-ed6f-4758-b508-6245a59c8f69)

Csv before changes:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/5822edec-7547-4270-9b1b-e10b171ea09d)

Csv after changes:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/4dcfd2a3-dc8a-402f-a6bf-2872c2c2b049)

Console after importing csv:
```
Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\prop.py", line 86, in get_attribute_enum_values
    data = json.loads(prop.enum_items)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\prop.py", line 83, in get_attribute_enum_values
WARN (bpy.rna): C:\Users\blender\git\blender-v400\blender.git\source\blender\python\intern\bpy_rna.cc:1349 pyrna_enum_to_py: current value '0' matches no enum in 'Attribute', '', 'enum_value'
```

**Comment by Andrej730** [comment]
@ppaawweeuu 

> Console after importing csv:
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This error seems to be unrelated to importing csv. Can you show a way to reproduce this?


Regarding support for importing enumerated values - I've created a PR https://github.com/IfcOpenShell/IfcOpenShell/pull/4626 but not sure about it, it is kind of hacky - it's relying on the underlying ValueError with a specific error message (though we can add a test to make sure that text won't change unexpectedly). Analyzing each attribute to make sure it's pset's enum seems to be overkill. Any other ideas?

**Comment by ppaawweeuu** [comment]
Thanks
Somehow I cannot reproduce that kind of error message. I tested few version of bbim and result is very similar - no enum data imported, no error message. I haven't tested the most recent versions yet (I noticed some changes). I will test #4626 PR.
I attach set of files I used.
[11 csv export import.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15244838/11.csv.export.import.zip)

I used BBIM 240414, Blender 4.0.1

**Comment by ppaawweeuu** [comment]
@Andrej730 I tested for few minutes PR #4626 in bb 240514 - seems to work, awesome. Thank you.
If it is not related to #4728 - let's merge it.

**Comment by Andrej730** [comment]
@steverugi

**Comment by steverugi** [comment]
@Andrej730 is it going to be implemented in a new release today?

**Comment by Andrej730** [comment]
@steverugi yes, check releases after the commit referenced above.

**Comment by steverugi** [comment]
@Andrej730 All works fine now, thank you very much!
