### ISSUE TITLE
Building IfcOpenShell on linux, step 5: unable to set paths

### ISSUE THREAD

**Issue by apwbd7** [IfcOpenShell/IfcOpenShell#461]
Hi! I am unable to figure out how to set the environment variables for setting the dependencies' paths while building IfcOpenShell. For example, this message shows up- 

Looking for Open CASCADE include files in: /usr/local/include/oce/inc
-- Header files found
-- Looking for Open CASCADE library files in: /usr/local/include/oce/build/Unix/x86_64-Release-64
CMake Error at CMakeLists.txt:201 (MESSAGE):
  Unable to find library files, aborting

Any guidlines on how to set these paths for CMake?

Thank you!

**Comment by aothms** [comment]
With CMake you can either choose to set them as command line arguments prefixed with `-D`, so `cmake ... -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/`

Or you can use environment variables `OCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ cmake ...` or `export OCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu; cmake ...`

The paths in the output you posted seem a bit odd though, the lib files are probably not in `/usr/local/include/...`

Maybe you can post your directory structure and command to invoke cmake so that we can help you better.

**Comment by apwbd7** [comment]
Thanks you for replying, Thomas :) As you can tell by my query, I don't have much experience in this subject. From what I understand, if I use the following as a command line argument with CMake:

`cmake ... -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/`

The computer would expect to find Open Cascade library files in `/usr/lib/x86_64-linux-gnu/`, correct? 
But I don't have a folder called `x86_64-linux-gnu` inside `/usr/lib/`. Here's my directory structure (I'm not sure if this is what you asked for):

`/usr
├── bin
├── games
├── include
├── lib
├── libx86_64-linux-gnu
├── local
├── locale
├── sbin
├── share
└── src`

Here's the CMake command I used:
`cmake ../cmake -DOCC_LIBRARY_DIR="/usr/local/include/oce/build/Unix/x86_64-Release-64" \
      -DOCC_INCLUDE_DIR="/usr/local/include/oce/inc"\
      -DOPENCOLLADA_INCLUDE_DIR="/usr/local/include/opencollada" \
      -DOPENCOLLADA_LIBRARY_DIR="/usr/local/lib/opencollada"  \
      -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/`

And here's the error message again:

> Looking for Open CASCADE include files in: /usr/local/include/oce/inc
> -- Header files found
> -- Looking for Open CASCADE library files in: /usr/local/include/oce/build/Unix/x86_64-Release-64
> CMake Error at CMakeLists.txt:201 (MESSAGE):
> Unable to find library files, aborting

Similarly I could only find the OCC_INCLUDE files here: `oce/inc` i.e. in the folder I cloned from git, but not anywhere in `/usr`
I just followed the steps 1-through- 4 verbatim. Did I do something wrong? 

Thanks again for your patience :)

**Comment by apwbd7** [comment]
So, I was able to solve this problem by looking at the log printed on the terminal window after executing `sudo make install` in step 2.b); it showed me where the OCC library files would be on my computer and edited the path in step 5) accordingly.

**Comment by aothms** [comment]
Great. If there are things you'd like to clarify in the readme file feel free to send in a pull request.
