### ISSUE TITLE
bpy.ops.bim.select_type() throws error

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#4610]
If you click on the button "Select Type" from this menu
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/cee0b607-aba3-4f71-b388-b5786e68e3d6)
occurs this error
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/10926b56-517b-45b4-9115-02240d74a94e)
This occurs with all the types...

And if you click on the other menu
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/1e5992f4-defe-4235-817f-1f41e816b09a)
it works ok...

**Comment by ppaawweeuu** [comment]
Can't corfirm. I don't see error message. I use Blender 4.0.1 and BlenderBIM 240419

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/c5f741b5-61f0-43de-b6fa-30e67e9fbc51)

**Comment by theoryshaw** [comment]
Was most likely from [this](https://github.com/IfcOpenShell/IfcOpenShell/commit/080f325557deddd3eca54c94722c75a78a4e13c6). Will try to fix.
