### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'splines' #BlenderBIM

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#4615]
1. Created an Ifc-object from blender-object under "object information":
2. Added representation "Model/Profile/ELEVATION_VIEW" under "Geometry and material".
3. Chose "Full representation" in "Add Representation" dialog.

This results in error:

AttributeError: 'Mesh' object has no attribute 'splines'.

If I choose "Trace outline" instead of "Full representation" then there is no error.

If "Full representation" is an invalid option, then maybe this option should not be available in the "Add representation" dialog?

**Comment by Moult** [comment]
Indeed, it is an invalid option, but it is not known until we actually try to create it, so the dropdown option will stay there (in some scenarios, it will work). There are a lot of geometry types in IFC and lots of contexts, and lots of permutations :)
