### ISSUE TITLE
Beeing able to set object data properties for geometric representations #BlenderBIM

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#4616]
If a blender object also is an ifc object with serveral geometric representations, then each representation has its own mesh data.

You can change the mesh data for a blender object in the object data properties, but it does not affect the mesh data of any geometric representation. If you reload the mesh for a geometric representation then it has not changed.

It would be nice to be able to change (to be able to manually set) the mesh data to use for each geometric representation, even after it has been created.

**Comment by Andrej730** [comment]
> You can change the mesh data for a blender object in the object data properties, but it does not affect the mesh data of any geometric representation.

@marwiss Can you show an example?

If you mean something like changing object's scale and then applying it, or using modifiers and then applying them you can use "Manually Save Representation" to overwrite active representation with current object mesh.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/8cb73898-158d-479f-b3af-0ac33bacd485)

**Comment by Moult** [comment]
You can do this right now by switching to that representation in the Representations panel, then editing the mesh.

**Comment by marwiss** [comment]
Thanks for the feedback.

I eventually found out that I should have used the "Manually Save Representation"-button, to save the edited mesh for the active representation. I did not imediately find this feature because it is marked as "for advanced users only" and I did not see any documentation on what will happen if you push this button.

Maybe it could be possible to select the mesh data for the representation from a list of all the available mesh datas loaded in memory (until purged). Just like you are able to change mesh data for each blender object from a list of all mesh datas available in memory (in "Object properties").

**Comment by Moult** [comment]
I think we're missing something. You shouldn't need to use that button. You also shouldn't be manually changing the data block. What exact steps are you doing and what is the objective?

**Comment by marwiss** [comment]
The objective is to create a new representation Model/Profile/ELEVATION_VIEW.

But I wanted a different shape then the standard default traced outline. Because I wanted these shapes to appear in my ELEVANTION_VIEW with annotations.

I was trying to copy some shapes from the body (the blender object) and scale them into zero ie. into 2D.

Then I was trying to copy this mesh into the representation for the ELEVATION_VIEW and delete the default outline mesh.

I was able to do this, but when I reloaded the mesh of the ELEVATION_VIEW representation then the default traced outline would always reappear. It seems like my edits were never saved.

However, when I pressed the button "Manually save representation" under "Representation utilities" it finally worked.

However. It would be easier if one could just swap the data for each representation. Just like when it is possible to browse for a mesh data to use under "Data/Object Data Properties".

![bild](https://github.com/IfcOpenShell/IfcOpenShell/assets/935375/96a1acb8-5158-44fb-91c4-f659bff4732a)

**Comment by Moult** [comment]
Thanks it makes sense. Indeed, BBIM assumes that the add-on controls the data blocks for any IFC object, so the moment the user manually changes it, that assumption is broken and strange behaviour can occur.

I think the best thing to do is to add a new option "From object" when adding a representation. Right now that feature just doesn't exist.

**Comment by Moult** [comment]
Sorry, to clarify Model/Profile/ELEVATION_VIEW is probably not what you're looking for if you want your shape to appear differently in an elevation.

When an element is visualised in a drawing, two contexts are drawn: the Body is drawn, and then in addition the Annotation is drawn on top. So if you want the object to look differently in an elevation view only, then you should create a Model/Body/ELEVATION_VIEW representation. If you simply want to add extra annotation for that object that only appears in an elevation view, create a Model/Annotation/ELEVATION_VIEW representation.

The Profile representation has a specific purpose in IFC: it's to outline the profile of a shape. This profile currently is only ever really used in determining how to create automatic voids if you try to insert one element into another. For example, if you insert a window into a wall, the window's Profile/ELEVATION_VIEW context is used to determine how to cut out that void in the wall to insert the window. As far as I am aware, there is no other documentation in IFC describing how software would use a Profile apart from that specific scenario.

**Comment by marwiss** [comment]
Thanks for the info!
