### ISSUE TITLE
Error switching representation in EDIT mode

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#4617]
If you load a geometric representation by clicking on the "Switch representation" data mesh button, under "Geometry and materials" "Representations" ... while in EDIT MODE you get an error.

Exception: user_remap is not supported for meshes in EDIT mode.

I assume this is correct behaviour. But not very userfriendly.

**Comment by Gorgious56** [comment]
I think it should be disallowed altogether to switch representations while in edit mode. It would straightforward to disable the buttons and add a tooltip prompting the user to go out of edit mode while hovering the disabled button. 

Any thoughts ?

**Comment by Moult** [comment]
Agreed the functionality should be disabled in edit mode.

Dion Moult

Sent from Proton Mail mobile

-------- Original Message --------
