### ISSUE TITLE
Copying objects between blender projects

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#4619]
Let's say you create an Ifc object in a BlenderBIM Ifc project. For example an IfcWindow.

Then you copy the blender object to a new blender project in a new blender window.

When you create an Ifc project in this new blender window, it is not possible to assign an ifc object to the copied blender object.

Under "Object information" and "Object metadata" there is just a message "IFC Element Not Found".

It seems like the copied blender object is still associated with the old Ifc object that does not exist in the new blender project / window.

**Comment by marwiss** [comment]
To solve the problem practically you can:

1. Create a new blender object in the new project. For example a cube.
2. Copy the mesh data from the old object that was once copied from the old ifc project - to the new blender object.
3. Separete the data blocks by saving them separately for each object.
4. Delete the old ifc object.

Now you can create a new ifc element for the new object in the new blender project - without getting message "IFC Element Not Found".

**Comment by Andrej730** [comment]
I think it was mostly designed for that case:
1. Copy blender object from Ifc Project A
2. Paste it in separate Blender session with Ifc Project B. It will be pasted as unlinked object
3. You will be able to assign it.

Though it's possible to unlink the pasted Blender object and then it will be possible to assign class to it, I've added unlinking to work even without IFC file active to make it more safe.

**Comment by Moult** [comment]
I vaguely recall there was code intended to make it so that when pasting an object using control v it would auto completely purge everything (I.e. pure blender object), no mention of ifc links at all.

Can this be reopened to investigate?

Dion Moult

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Andrej730** [comment]
> I vaguely recall there was code intended to make it so that when pasting an object using control v it would auto completely purge everything (I.e. pure blender object), no mention of ifc links at all.

I think it is the OverridePasteBuffer changed in https://github.com/IfcOpenShell/IfcOpenShell/commit/8f7f6223de6dbe6287652fed12b7a8a46db2ca4f
