### ISSUE TITLE
OpenCascade 7.8.0: Missing STEPConstruct_PointHasher 

### ISSUE THREAD

**Issue by waarmond** [IfcOpenShell/IfcOpenShell#4620]
OpenCascade 7.8.0 has removed the following headers:

STEPConstruct_PointHasher.hxx
STEPConstruct_PointHasher.lxx
StepToTopoDS_CartesianPointHasher.hxx
StepToTopoDS_PointPairHasher.hxx

I'm not getting as far as linking like Adrián from https://github.com/IfcOpenShell/IfcOpenShell/issues/4393

```
[  4%] Building CXX object CMakeFiles/IfcGeom_ifc4x2.dir [..]/IfcOpenShell/src/ifcgeom/IfcGeom.cpp.o

In file included from ./IfcOpenShell/src/ifcgeom/IfcGeom.cpp:140:
/home/papa/aur/_3d_cad/ifcopenshell-git/src/IfcOpenShell/src/ifcgeom/../ifcgeom_schema_agnostic/IfcGeomTree.h:62: fatal error: STEPConstruct_PointHasher.hxx: No such file or directory
   62 | #include <STEPConstruct_PointHasher.hxx>
      | 
```

--

Completely fixed by removing
`#include <STEPConstruct_PointHasher.hxx>`
from IfcGeomTree.h

**Comment by aothms** [comment]
@waarmond doesn't seem used indeed in our codebase, could you send in a PR? thanks in advance, much appreciated :)
