### ISSUE TITLE
SWIG generated wrapper for piecewise function object

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#4629]
I'm trying to optimize the handling of piecewise functions by:
- computing length once and caching the result
- assuming monotonic evaluation of the set of spans and caching the last span used, reducing the number of searches

To make this work, I need to make the `spans` vector private to avoid random access to it. This necessitates some new functions `add_span` and `append` that adds spans and appends piecewise functions together. Whenever these methods are called, the cached length "current span" are invalidated.

The problem is then the wrapper functions for the piecewise_function class generated in the IfcPythonPYTHON_wrap.cxx file don't compile. They want direct access to the `spans` class member.

I've never used SWIG before, but do have some experience with boost::python and pybind11. Any advise on how to get the python wrapper class to generate correctly if `spans` is a private member of the class? @aothms

**Comment by RickBrice** [comment]
> So instead of add_span() did you consider passing these once in the constructor?

Good idea - I can easily implement that way

> I think what happened is that SWIG didn't rerun ...

You've told me that before - sorry.

**Comment by aothms** [comment]
> You've told me that before - sorry.

Don't remember that, no problem :)
