### ISSUE TITLE
Use occt 7.3 in Travis

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#463]
IfcOpenShell uses Travis CI to test the code base (mostly for compilation errors) and a few tests written in Python. Currently a rather old version of Open CASCADE Community Edition (OCE) is linked against. In recent unstable debian versions the much newer OCCT 7.3 is also available. Some code paths are different based on version of OCCT, so preferably test both on Travis.

* Travis CI yaml file: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/.travis.yml
* Python test cases: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/test/tests.py
* OCCT 7.3 package: https://packages.debian.org/sid/libocct-foundation-dev
* Conditional code paths e.g: https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomFunctions.cpp#L474

**Comment by CyrilWaechter** [comment]
Fixed in 4821226ec268f4a9f4d52a085591aaf565858880
