### ISSUE TITLE
Incorrect warning description?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4630]
I get this warning message for a requirement I use dataType IFCTEXT: The property's data type "IfcAreaMeasure" does not match the required data type of "IFCTEXT". And it does not really make sense.

In this case the correct data type should be IfcAreaMeasure, and the warning is far from explaining that.

IDS code:

<ids:property dataType="IFCTEXT" cardinality="required">
          <ids:propertySet>
            <ids:simpleValue>X</ids:simpleValue>
          </ids:propertySet>
          <ids:baseName>
            <ids:simpleValue>X_Area</ids:simpleValue>
          </ids:baseName>
 </ids:property>

Or am I missing something?

**Comment by Moult** [comment]
Your IDS asks for IfcText. Your model provides IfcAreaMeasure. That makes sense to me?

**Comment by BIMvoice** [comment]
I think what is confusing to me is "the required" part. I think "it's required by what is in the model". Could there be any way to explain this in a way that makes easier sense for non native English speakers? To make it clearer, what is required in IDS and what do you have in the model.

**Comment by Moult** [comment]
> The property's data type "IfcAreaMeasure" does not match the required data type of "IFCTEXT".

The property has a data type of IfcAreaMeasure, this does not meet your requirements of an IfcText data type.
