### ISSUE TITLE
after 5a8209e2ad6873374452dada313fed6259e43b39, selecting stuff is very laggy. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4633]
after 5a8209e2ad6873374452dada313fed6259e43b39, selecting stuff is very laggy. 

file: https://hub.openingdesign.com/OpeningDesign/Restaurant_Pewaukee/src/commit/c618f4361b24b86f92c6ff871899f17e29ef8711/Open/Models/BlenderBIM/Restaurant_Pewaukee.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a6434ebe-8985-4613-8079-9c74d4ee1557

**Comment by Gorgious56** [comment]
I guess `bpy.context.scene.DocProperties.should_draw_decorations = bpy.context.scene.DocProperties.should_draw_decorations` is the culprit, it forces uninstalling and reinstalling the decoration handler.

**Comment by Plae-Blue-Dot** [comment]
@Moult thank you for this fix! Amazingly better. For a week I thought the issue was my pc ahhahaah
