### ISSUE TITLE
BBim Feature Request - Filter by aggregate

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#4638]
Creating a search filter capable of selecting all elements within a user-definable aggregate would be very helpful for producing drawings of an individual assembly made from multiple elements.

**Comment by theoryshaw** [comment]
+1
I've bastardized many of a `IfcBuildingStorey` in the past. :)

**Comment by steverugi** [comment]
thanks @Moult for the fix, really appreciated
now a `Parent` filter is added, great!
can we get its name value attribute as well? I tried parent.Name but didn't work
thanks again for your fantastic help
