### ISSUE TITLE
Regarding the issue of using Blender Bim

### ISSUE THREAD

**Issue by jingyangking** [IfcOpenShell/IfcOpenShell#4642]
Can I export the imported IFC format model to FBX, OBJ, and GLTF formats in Blender after installing the Blender BIM plugin

**Comment by Moult** [comment]
Yes. Just File > Export in Blender. Alternatively, you can use IfcConvert to bypass Blender: https://docs.ifcopenshell.org/ifcconvert.html

**Comment by jingyangking** [comment]
thank you for your reply.
