### ISSUE TITLE
Cannot activate drawing of a hidden ViewLayer

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#4647]
I don't know if this is an error or not.

But if you go to "Drawings and documents" and click on the "Camera icon button" to activate an existing drawing.

Then you get an error if the correlated blender object (i.e. Views -> IfcAnnotation/SOUTH ELEVATION) is hidden.

But if it is not hidden, then there is no error, and the drawing can be activated.

This is the error:

![bild](https://github.com/IfcOpenShell/IfcOpenShell/assets/935375/4319579e-09b5-4f85-96e6-bf6caf1e4aeb)

**Comment by Moult** [comment]
In the past given how alpha things were / and kept on changing we didn't really bother doing much error handling but now is a good chance to start introducing better error catching. In this scenario, the user has explicitly unloaded the camera, so we should pop up with a recoverable error message.
