### ISSUE TITLE
ValueError on "Activate Model"

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#4648]
Under "Drawings and Documents".

I am in "Camera Orthographic view" (after pressing the "Activate Drawing" camera button).

I want to go back to "Model view" and press the "Activate Model" button.

Then the following error occurs:

![bild](https://github.com/IfcOpenShell/IfcOpenShell/assets/935375/f749f69c-327c-4cdb-bece-a881593c3b2c)

Maybe this error is related to:

https://blender.stackexchange.com/questions/305388/valueerror-1-2-args-execution-context-is-supported-on-call-to-bpy-ops-outlin

**Comment by marwiss** [comment]
I don't know if there are any earlier steps that is the cause to this error, because there was a lot of earlier steps.

But I can't get back to model view now.

**Comment by Moult** [comment]
Fixed in unstable release: #4026.
