### ISSUE TITLE
pre 2018 Allplan ifc exports crash during creating geometry

### ISSUE THREAD

**Issue by Xylexis** [IfcOpenShell/IfcOpenShell#465]
When trying to convert models exported from an older Allplan version the creation of geometry stops and does not give any error messages as to why it stopped.
I'll send the models to the models@ifcopenshell.org adress.

**Comment by aothms** [comment]
Thanks for reporting this and sorry for the delay in responding. I ran the file through a recent version of IfcConvert and it seems now proper error messages are generated and conversion continues.
