### ISSUE TITLE
Aggregates: BB UI info should not contradict each other

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#4651]
IFC4: An IfcWall consisting of 4 IfcBuildingElementPart should not display two (at least for me) contradictory pieces of information in the BlenderBIM user interface. "No aggregates" and immediately in the line below "4 Parts".

Or am I misinterpreting the UI information?

[SimplyTwoRooms ARC -- IFC4 RV BIMt.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15273412/SimplyTwoRooms.ARC.--.IFC4.RV.BIMt.ifc.zip)

![Screenshot 2024-05-10 at 11 07 07](https://github.com/IfcOpenShell/IfcOpenShell/assets/1941141/a7ea8a9f-f2ca-4a16-83a6-e3b2f86d19af)

**Comment by Moult** [comment]
Aggregate refers to the parent, part refers to the child. So it has no parent, and 4 children. Another word the IFC documentation uses is "Whole" vs "Part". how does "No Whole" sound?

**Comment by kurb70** [comment]
Do I understand correctly that you are suggesting replacing UI text "No Aggregate" with "No Whole"? I think that would be more meaningful in this case and would give an indication of where to start with the fix. 

Perhaps even a little more detailed like "No Whole relation defined"

**Comment by Moult** [comment]
Yep

**Comment by kurb70** [comment]
Would be great. 🙂

**Comment by Moult** [comment]
This is a great beginner change to make. Would you be interested to help make this change? You can right click anywhere on the BlenderUI and click Edit Source, then edit the file online here on Github to submit a PR :)

**Comment by kurb70** [comment]
I would like to try that. Unfortunately, this "Edit Source" is not displayed for me. Or am I looking in the wrong place?

![Screenshot 2024-05-10 at 14 06 03](https://github.com/IfcOpenShell/IfcOpenShell/assets/1941141/a73b6a6f-31b4-4f76-b1db-59cbeef1b9cf)

**Comment by Moult** [comment]
Edit > Preferences > Interface > Enable Developer Extras.

Then right click on something in the properties sidebar. It'll open in a text data block. Switch to the Blender text editor to see the file.

**Comment by trhyder** [comment]
I struggle to understand what the Aggregates section in the UI is doing. For me, I think the biggest barrier is that the UI is used for both parents and siblings and is directional depending on what is selected. I am not sure changing the text to "No whole" is any clearer. Are you trying to communicate the selected object has no parent?

**Comment by theoryshaw** [comment]
how about...
`Not Aggegated`
and
`Aggregated in <name of aggreate>`

**Comment by kurb70** [comment]
> Edit > Preferences > Interface > Enable Developer Extras.
> 
> Then right click on something in the properties sidebar. It'll open in a text data block. Switch to the Blender text editor to see the file.

I found the preference checkbox and checked it, but this shortcut menu item does not appear.

**Comment by theoryshaw** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/1b9e56cd-74aa-4a23-af35-86b591dabdc3

**Comment by kurb70** [comment]
@theoryshaw Thank you. That short film helped a lot.
@Moult I pushed a PR. My first one ;)

**Comment by Moult** [comment]
Cheers :) I don't see a PR?

**Comment by kurb70** [comment]
Uuups … it seems I did not finish the process. No I did. Thx.
