### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tchichi** [IfcOpenShell/IfcOpenShell#4656]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/169443456/71d18987-474d-4d4a-8801-a78540916ad8)

**Comment by tchichi** [comment]
small mistake I thougt it was the error "copied to clipboard" but it seems that nothing has been copied, only the last screenshot I did

**Comment by Moult** [comment]
What's the error?

**Comment by Moult** [comment]
Closing due to no feedback. Most likely user error that can be resolved by checking out the troubleshooting docs.
