### ISSUE TITLE
Converting IFC to DAE, parts of the mesh are missing after geometry creation

### ISSUE THREAD

**Issue by Xylexis** [IfcOpenShell/IfcOpenShell#466]
I'm converting an IFC file to DAE and the conversion gives no errors.
But the resulting mesh that can be seen in the Unity screenshot seems to miss parts of the mesh.
The right side should be similar to the left side of the image. 
My guess is that it has to do with overlapping vertices or something like that.
I'll send the model to models@ifcopenshell.org
![mesh errors](https://user-images.githubusercontent.com/197950/45555277-a6263000-b838-11e8-93e8-05bf88f58c76.PNG)

**Comment by Xylexis** [comment]
The missing bars where mirrors of the bars on the left. This might be something that the IFCconvert tool cannot handle correctly. We corrected it for now by copying the bars on the left to the right.
But this might be something worth looking into because I think mirroring is used quite frequently.

**Comment by aothms** [comment]
The missing bars turned out not to be defined as mirrored items in IFC. The problem was caused by a more low level modelling error in Open CASCADE. The geometry is generated correctly now in recent versions of IfcOpenShell. Thanks for taking the time to report this, and again sorry for the delay.
