### ISSUE TITLE
not showing drawing button

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4664]
![Screenshot 2024-05-14 164449](https://github.com/IfcOpenShell/IfcOpenShell/assets/140309875/67ed8bed-b0ab-41d6-bb2a-c6eb410b3a03)

**Comment by Andrej730** [comment]
Can you please provide an .ifc file to reproduce this?

**Comment by theoryshaw** [comment]
This might be an .ifc/.blend syncing problem. 
See common issues: https://docs.blenderbim.org/users/troubleshooting.html#common-issues

**Comment by Moult** [comment]
See #4671. Looking at the .blend save file in the top of your screenshot, I'm almost certain this is the issue. If this is really confusing, please join the [OSArch chat](https://osarch.org/chat) and we're more than happy to screenshare and explain exactly how BBIM is meant to work. Please also take some time to read the documentation.
