### ISSUE TITLE
View layerset thicknesses in feet and inches format 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4665]
If project is in Imperial Units, would be nice to see the following dimensions in feet and inches format (Example: 0' - 0 3/16") inches, perhaps rounded to the closest 1/16" or 1/32"

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c0acf230-d889-450d-a08a-b91cdc6c5e55)

...

Additionally, if the measurement is less than an inch, it suppresses the zeros. 

`0' - 0 3/16"` =  `3/16"`

or less than a foot, it suppresses the zero, as well. 

`0' - 7 3/16"` =  `7 3/16"`

**Comment by theoryshaw** [comment]
@RickBrice  Although I like that it's pinned.  I have a feeling you didn't indent it. :)  Is that correct?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/1ed343e8-2fd0-4798-a2bf-d53f3eddf24d)

**Comment by RickBrice** [comment]
@theoryshaw I didn't realize pinning an issue was a global setting. I thought it was just for my account. I was thinking after I got a few things off plate I would take a look at implementing this so I pinned it to keep track of the issue. Sorry about that.

**Comment by theoryshaw** [comment]
No worries!  I'm excited that you're interested in tackling.   Feels lonely sometimes, in the imperial domain. :)

**Comment by theoryshaw** [comment]
@RickBrice Hope i didn't steal your thunder. :)

![2024-07-05_22-20-08_blenderalignment_of_walls_ DDropboxTroubleshooting2024062blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/0e59ed82-018e-4473-8452-e7fd01d8d28d)
