### ISSUE TITLE
Boolean operation using pythonOCC

### ISSUE THREAD

**Issue by apwbd7** [IfcOpenShell/IfcOpenShell#467]
Hi!

I tried doing the following Boolean CUT operation using shapes of IfcDoor and IfcWall instances:

Case 1.:
`settings = ifcopenshell.geom.settings()` 
`settings.set(settings.USE_PYTHON_OPENCASCADE, True)`
`mold = OCC.BRepAlgoAPI.BRepAlgoAPI_Cut(mold, ifcopenshell.geom.create_shape(settings, ifc_file.by_type("IfcDoor")[0]).geometry).Shape()`

Case 2.:
`settings = ifcopenshell.geom.settings()` 
`settings.set(settings.USE_PYTHON_OPENCASCADE, True)`
`mold = OCC.BRepAlgoAPI.BRepAlgoAPI_Cut(mold, ifcopenshell.geom.create_shape(settings, ifc_file.by_type("IfcWall")[0]).geometry).Shape()`

here mold is just a big box shape created using `OCC.BRepPrimAPI.BRepPrimAPI_MakeBox `

The trouble is: while in the case of an IfcWall instance, the CUT operation is successful; for IfcDoor, it gets stuck and my display window just freezes forever. I don't know why this happens.. maybe it has something to do with what IfcOpenShell returns in `ifcopenshell.geom.create_shape(settings, ifc_file.by_type("IfcDoor")[0]).geometry` that makes it difficult for pythonOCC to work with?

Can someone shed some light in this, please? thank you :)

**Comment by aothms** [comment]
> maybe it has something to do with what IfcOpenShell returns in ...

Probably. First of all you might want to try with `settings.set(settings.SEW_SHELLS, True)`. To save time, creating proper manifold solids for IFC facesets is not attempted by default. This setting does that so that there is a proper orientable manifold that can be used in boolean operations.

But secondly, wall geometries are just much simpler typically. If your door geometry is very complex (like detailed doorknobs e.g.) or simply invalid from a topological kind of view (which happens more often then you would want in these kind of more symbolic IFC geometries) you might be out of luck and you might need to check/validate/fix/simplify your geometries prior to using them in generic boolean operations.

**Comment by apwbd7** [comment]
Thanks, Thomas. 
> you might want to try with `settings.set(settings.SEW_SHELLS, True)`
This helped and IfcWindow-shapes can now be used for Boolean operations, but IfcDoors are still a problem.
I was wondering if I can use IfcOpeningElement instances in place of doors or windows? Because they don't have complex geometry. I tried this and this too didn't work. Could you please also shed some light on this.

Thanks :)

**Comment by aothms** [comment]
> I was wondering if I can use IfcOpeningElement instances in place of doors or windows?

Probably. Or you can create a new shape with based on the semantics [1]. Or find the large faces in the window geometries and extend them to the solid of the opening. All sorts of approaches are possible.

> I tried this and this too didn't work. Could you please also shed some light on this.

How did it not work? Can you elaborate?

[1] http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcsharedbldgelements/lexical/ifcwindowliningproperties.htm

**Comment by apwbd7** [comment]
> How did it not work? Can you elaborate?

The viewer window stops responding and the program just hangs there without showing any error messages.

**Comment by aothms** [comment]
Not sure about that. You can always also set `settings.DISABLE_OPENING_SUBTRACTIONS` to have wall geometries without the openings. If I understand your approach complexity as much as possible. When boolean operations fail you might want to dump both shapes to a file (`BRepTools::Dump()` in C++) and see if there are any irregularities (such as tiny edges or a weird hierarchy).

I can also have a look at the files specifically if you share them (publicly here, or privately models@ifcopenshell.org)

**Comment by aothms** [comment]
Great. None of these other settings matter if you're using PythonOCC output.

> WELD_VERTICES

When not using pythonocc, discard normals and join vertices that belong to different faces

> USE_WORLD_COORDS

When not using pythonocc, multiply ObjectLocation matrix into geometry vertex positions

> USE_BREP_DATA

Implied when using pythonocc. Generates a string representation of the geometry that is deserialized into a pythonocc shape

> DISABLE_TRIANGULATION

Implied when using pythonocc, do not triangulate.

**Comment by Moult** [comment]
Closing as this seems to now be more of an OpenCASCADE / general geometric quality issue as opposed to something specific to IfcOpenShell.
