### ISSUE TITLE
Export and load a template for Spreadsheet export

### ISSUE THREAD

**Issue by deedend** [IfcOpenShell/IfcOpenShell#4673]
Hi,

I think it would be great to be able to export and re-import the settings of the "Spreadsheet Import/Export", so we can create a template to use in multiple models with similar property sets. For example, the attached image is a simple extraction table for quantities, but we currently have to replicate it manually for every new file. The export/import should be user-friendly, maybe with an option just on top of the "Add Search Group" button.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/6630884/affcc82e-7d2a-446a-a0c9-2cc1ca7bc69b)

**Comment by Andrej730** [comment]
@deedend hi! It's already implemented:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/7eac171d-a545-4457-af6f-3ff4f11efead)
