### ISSUE TITLE
Loading Models Off Center

### ISSUE THREAD

**Issue by OrionSehn** [IfcOpenShell/IfcOpenShell#4677]
Hello, 

I have a bit of an unusual edge case, where I have a model which exists almost exactly 1000m from origin. When I try and load in the model, without setting the distance limit in the advanced menu, it loads in the half of the model which is within 1000m of the origin, then loads the other half near the origin. 

I didn't really want to push my users into using the advanced menu, when I believe the purpose of having the limit was to allow users to only load in some of the model, in cases where the model was large.

Can we just bump this a little for now?
I increased this distance in: https://github.com/IfcOpenShell/IfcOpenShell/pull/4634

I think the best case scenario would be to not have the default behavior filter by distance at all, and try to load in everything it can, then allow a way for them to filter by distance.

Probably by re-working:
https://github.com/IfcOpenShell/IfcOpenShell/blob/bc72c927c1d6737730a2db1391e5b4a9e4de21d3/src/blenderbim/blenderbim/bim/import_ifc.py#L314

To return False if that distance limit is set to None? or inf? I'm not sure.

**Comment by Andrej730** [comment]
Does it filter out the elements completely for you or they are just loaded at the wrong position?

That's how it works currently - at first it's trying to figure in `get_offset_point`, whether model should be imported with an offset:
 https://github.com/IfcOpenShell/IfcOpenShell/blob/9969de58cb3ad433ce0227a22d688ab4f8652429/src/blenderbim/blenderbim/bim/import_ifc.py#L687

Then it checks for each element individiully whether it's far away and if so, it loads them with an offset.

https://github.com/IfcOpenShell/IfcOpenShell/blob/9969de58cb3ad433ce0227a22d688ab4f8652429/src/blenderbim/blenderbim/bim/import_ifc.py#L741-L746  

Not sure but maybe we should just offset all elements in case if we decided in `get_offset_point` that model does have an offset.

**Comment by OrionSehn** [comment]
So, very strangely, it doesn't filter out elements completely, and they are loaded at the wrong location. 

Elements <1000m away from origin are loaded in where they are defined by the IFC model, but elements > 1000m from the origin are loaded AT the origin (or very near the origin) 

I don't think its exactly what we want to break apart renderings that arbitrarily fall on that 1000m line. Seems kinda janky.

Why don't we set that default limit to be `inf` and allow the user to configure it in the advanced menu if they want to limit that maximum distance.

**Comment by Andrej730** [comment]
> Why don't we set that default limit to be `inf` and allow the user to configure it in the advanced menu if they want to limit that maximum distance.

Because it was designed to auto detect projects that are far away from the origin to make sure they are loaded with an offset, so it be easier to work with them. Without a limit all objects will be imported at their actual positions which can be very very far away.

**Comment by OrionSehn** [comment]
Hmmm, its just a bit awkward when the model falls exactly on that 1000m line, and half your model loads in, and the other half loads in 1000m away. 

I wonder if there's any way we could detect and handle that, or at least provide a warning?

**Comment by Andrej730** [comment]
Currently I think the best solution might be this

> maybe we should just offset all elements in case if we decided in `get_offset_point` that model does have an offset.

just looking for a second opinion if there are cases when this would be undesirable.

**Comment by OrionSehn** [comment]
In our use case, we want to render in a model where it is as specified way by the IFC. 

I don't see how loading those models closer to the origin makes it easier to work with those models? Can you explain why that is?

If we do set it to load with an offset by default, can we have an option to load without an offset, and load at the location specified in the IFC file? I'm not super convinced having different coordinates of the blender location and the coordinates specified in the IFC file is sensible, and I'm curious to see how this adds value. 

In our use case, we want to compute against that IFC outside of blender, and then render objects and those specified coordinates. If you want to compute against the IFC without rendering, and generate some coordinates to create objects, then render them in context of the IFC, then you'd have to render those objects with the same offset behavior that you implement here.

**Comment by Andrej730** [comment]
The issue should be resolved after commit above as it shouldn't now mix up objects with and without an offset on the scene (if some offset is found, it will be applied to the all elements). Though there are exceptions for non-geometrical objects at exactly (0,0,0), they'll never get an offset.

> I don't see how loading those models closer to the origin makes it easier to work with those models? Can you explain why that is?

Besides any convenience working with smaller coordinates it's a techincal requirement for Blender as it's not designed to work with such large models and it starts to lose number precision when coordinates are far away from the origin. If you want to disable it, you can set distance limit to a larger number but it's not recommended as you might experience those number precision issues.

**Comment by OrionSehn** [comment]
Thank you for the explanation and your hard work @Andrej730! Its appreciated!
