### ISSUE TITLE
changing IFC file after first export

### ISSUE THREAD

**Issue by Svel89** [IfcOpenShell/IfcOpenShell#4684]
Hello, 

i created my project with autocad and Blender and now with Blenderbim for export. 
With try and error i get to my first export and the other people in the project are happy with my blenderbim ifc even if they work with other professional software. 

(we are in the design phase of the project - for this stage blenderbim works, i am not sure if it will work in a more detailed phase too and maybe will switch to other program, but for now i am very happy with blenderbim!)

Now i startet working on the file in more Detail. My problem is that all the time i change something blenderbim asked me if i want to save the .ifc. 
And than i get an error that you can see in the attached file.

![bugreport1](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/1894f559-d0cf-498a-bada-db9c68a81b5f)

I understand it like this that there is a difference between the .blend file and the .ifc file and i need to update the representation (shift+e and than 6). 

But than i get the second python error i attachedE

![bugreport2](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/3f516e6f-bace-45a9-8e3c-7c04fb0ed96b)

One Info:
I am working in eviroment and BIM is not very developed in this area - so its more important to get an ifc file than to get the correct naming. At the moment most of the stuff is a .ifc slap or proxy.

![Object-info](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/5a9a2584-22f2-47e4-a2cf-e5274b2ce409)

I really enjoy working with blender and blenderbim. 
Maybe you can help me how to handle this problem.

Best regards
Sven

**Comment by Andrej730** [comment]
1) 
> And than i get an error that you can see in the attached file.

The first error from seems like the one resolved in eaa80ad08a6ceb77f933a37a31eeffcf83200246, try the latest build from Github Releases.

2) 
> I understand it like this that there is a difference between the .blend file and the .ifc file and i need to update the representation (shift+e and than 6).

Hard to tell without an example files and steps to reproduce the issue. But it seems like you opened .blend file and it couldn't find the ifc file (maybe it's moved else or something) - you need to make sure IFC file is loaded in Project Overview tab:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/eb52c9e4-9a20-45e6-830b-2faae2ab6ed0)

 If it's not, then change the path to the existing .ifc file. If issue stays please describe how to reproduce it.

**Comment by Svel89** [comment]
Hello Andrej, 

this works very well! I was able to make an .ifc out of the new design! :) 

Thanks!
