### ISSUE TITLE
Annoying "IFC Mode Set Object" window manager

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#4689]
Is there somewhere we can place the boolean "Should Save" for IFC Mode Set Object such that it is clicked once?

Incredibly annoying to have the window pop up on your face when you're doing native IFC

**Comment by theoryshaw** [comment]
related :)
https://github.com/IfcOpenShell/IfcOpenShell/issues/3174

**Comment by Moult** [comment]
Closing as duplicate.
