### ISSUE TITLE
OpenGost Type B TT Font and Scandinavian characters in blenderbim

### ISSUE THREAD

**Issue by jsaarane** [IfcOpenShell/IfcOpenShell#4690]
Would it be possible to have a font with support for Ä and Ö ?

![Näyttökuva 2024-05-18 151708](https://github.com/IfcOpenShell/IfcOpenShell/assets/13415484/1f33020c-de62-45b2-9dba-d996b6878a5a)

**Comment by Moult** [comment]
A few things to note about this fix:

 1. Fonts are stored in bim/data/fonts
 2. This is only the viewport font, not the same as your CSS font. You will need to set your CSS yourself.

**Comment by Moult** [comment]
Sorry, I actually completely misinterpreted this issue. This is about configurable fonts in generated schedules. Will deal with it.
