### ISSUE TITLE
Null properties should not be created in pset by default

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4696]
Currently, if a property is set to null in a standard pset, it is still added as a null property. This creates a lot of cruft.

**Comment by theoryshaw** [comment]
This fix works on other files, but for some reason it doesn't seem to work on this file. 

file: https://hub.openingdesign.com/OpeningDesign/Restaurant_Pewaukee/src/commit/7067727018868fb6035b514319c27a1dde3a5e05/Open/Models/BlenderBIM/Restaurant_Pewaukee.ifc

try `IfcElectricApplianceType/#28`



https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/044de32f-3a91-49d8-82bc-1d50409bea2e

**Comment by theoryshaw** [comment]
I just noticed, if there's a psets folder relative to the file, it doesn't give the option to null out that pset.  If, however, there's not psets folder, the option to null, is available. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b6486658-6474-48b4-ac8a-55f69a422391)
