### ISSUE TITLE
Import Cost Schedule | problem with sorting imported cost items

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#4698]
with latest BBIM release (240520) I noticed that when importing a .csv file as cost schedule the items are imported in a different order compared to the one in the imported file

Using Identification with progressive order doesn't seem to help, this is a snapshot of the csv file

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/d07e0955-aec1-4036-968d-d8b551753b7f)

and this is the result (2 building should come before 3 Platform)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/c6d96fc8-2326-46f1-8165-0d32ef973288)

I used the same model and .csv on a 240520 version and it was OK

**Comment by Andrej730** [comment]
@steverugi 

Thanks for the bug report! Can you please try now?

At first I thought that we should just sort items by Identification but it seems that [IfcRelNests](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcRelNests.htm).RelatedObjects is the only relationship to which order of RelatingObjects is important and I've overlooked it in 97db950 and 06b84cf (so it should have been broken prior to 240520).

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/a3a9c6ad-7b7e-44c1-aee1-aede8af5a5f4)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/3dc99906-c2d8-4efc-bf58-efd6d53c37a6)

I was testing it on this csv:
```csv
Hierarchy,Identification,Name,Quantity,Unit
1,1.0.0.0,The Works,10,Meters
2,2.0.0.0,Building,10,Meters
3,2.1.0.0,Earthworks,10,Meters
4,2.1.1.0,300mm Compacted material under slab,10,Meters
4,2.2.0.0,Concrete Works,10,Meters
5,2.2.1.0,Foundations,10,Meters
5,2.2.1.1,100mm Blinding under pads,10,Meters
5,2.2.1.2,500mm RC isolated pads,10,Meters
5,2.2.1.3,250x350mm RC starter columns,10,Meters
5,2.2.1.4,100mm RC base for cable trough,10,Meters
5,2.2.1.5,100mm RC wall for cable trough,10,Meters
4,2.2.2.0,Ground Floor,10,Meters
5,2.2.2.1,250x300 RC beams,10,Meters
5,2.2.2.2,250x350mm RC columns,10,Meters
4,2.2.3.0,Roof level,10,Meters
5,2.2.3.1,250x400mm RC beams,10,Meters
5,2.2.3.2,150mm RC slab,10,Meters
5,2.2.3.3,120x950mm RC roof perimeter beam,10,Meters
5,2.2.3.4,150mm sloped screed,10,Meters
4,2.3.0.0,Masonry,10,Meters
5,2.3.1.0,"200mm Hollow block wall, external",10,Meters
5,2.3.2.0,"200mm Hollow block wall, internal",10,Meters
5,2.3.3.0,"100mm Hollow block wall, internal",10,Meters
3,2.4.0.0,Floors,10,Meters
```

And here's the result:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/46e5d7e9-9d95-4afb-9111-af5b06f6b282)

Before fix:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/19225965-0afa-4fc6-8dc0-a13c81bd0f44)

**Comment by Moult** [comment]
Just for the record (not something we need to solve now), in addition to the order of nesting non-geometric entities being special, we should also allow for sorting overrides in the UI similar to the task hierarchy in work schedules.

**Comment by steverugi** [comment]
Hi @Andrej730 thanks for the quick fix, I am truly impressed and grateful
cheers
