### ISSUE TITLE
Rotated drawing camera not saved in the IFC in 2X3

### ISSUE THREAD

**Issue by jsaarane** [IfcOpenShell/IfcOpenShell#4700]
When you create a drawing and you want to make the drawing rotated. The camera rotation values are not saved in the IFC. I tested that the rotation values where saved when using IFC4.  

![rotation_bug](https://github.com/IfcOpenShell/IfcOpenShell/assets/13415484/2b782fd9-70ce-4407-83ce-d84abaf19c5d)

**Comment by jsaarane** [comment]
OK. Tested this a few times now with another simple model and it works. Must be something with that specific file.

**Comment by theoryshaw** [comment]
You might know this already, but it doesn't save the location/extent of the camera(drawing), until you run a drawing.  So that might have been it.

**Comment by jsaarane** [comment]
Absolutely right. This was the case.
