### ISSUE TITLE
ifcopenshell-0.7.0.240518 throws an error on import

### ISSUE THREAD

**Issue by VladislavDubrovenski** [IfcOpenShell/IfcOpenShell#4701]
error:

import ifcopenshell
07:45:10   File "/home/****/.local/lib/python3.10/site-packages/ifcopenshell/__init__.py", line 85, in <module>
07:45:10     from .file import file
07:45:10   File "/home/****/.local/lib/python3.10/site-packages/ifcopenshell/file.py", line 179, in <module>
07:45:10     class file:
07:45:10   File "/home/****/.local/lib/python3.10/site-packages/ifcopenshell/file.py", line 382, in file
07:45:10     def __getattr__(self, attr) -> Union[Any, Callable[..., ifcopenshell.entity_instance]]:
07:45:10   File "/usr/lib/python3.10/typing.py", line 1206, in __getitem__
07:45:10     return self.__getitem_inner__(params)
07:45:10   File "/usr/lib/python3.10/typing.py", line 312, in inner
07:45:10     return func(*args, **kwds)
07:45:10   File "/usr/lib/python3.10/typing.py", line 1212, in __getitem_inner__
07:45:10     result = _type_check(result, msg)
07:45:10   File "/usr/lib/python3.10/typing.py", line 176, in _type_check
07:45:10     raise TypeError(f"{msg} Got {arg!r:.100}.")
07:45:10 TypeError: Callable[args, result]: result must be a type. Got <module 'ifcopenshell.entity_instance' from '/home/****/.local/lib/python3.10/site-packages/ifco.

**Comment by Andrej730** [comment]
Thanks for the bug report, issue is resolved in 7c6c01e, you can try the latest build from Github releases page.

**Comment by ctrlmaniac** [comment]
is this published to the pypi or we have to wait?

**Comment by Andrej730** [comment]
@ctrlmaniac thanks for noting, updated pypi as it is critical for python <3.11
