### ISSUE TITLE
Error Add IfcRoofType Template Roof

### ISSUE THREAD

**Issue by S59-Koara** [IfcOpenShell/IfcOpenShell#4702]
When trying to add an IfcRoofType, select Type Template as Roof, and the button will be “Add HIP_ROOF” regardless of the Predefind Type selection. When the “Add HIP_ROOF” button is pressed, a Python Report Error is displayed.
blenderbim-240520
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/116019052/8a69ef46-c651-4d6c-bb62-745107719238)

**Comment by Andrej730** [comment]
@S59-Koara couldn't reproduce this - can you please take a look what I'm missing?

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/4affb81d-fc6c-4f43-a0b5-b24546242a32

**Comment by S59-Koara** [comment]
Sorry, I misunderstood. Roof has nothing to do with it.
I selected Create Slab, not Crate Element as you did, which is what caused the error.
I changed to something other than IfcSlabType in Create Slab, be it IfcRoofType or any other Type, the Add Type Instance to the model operation is what causes the error.

**Comment by Andrej730** [comment]
Thanks for the bug report, I'll comit a fix today, you'll be able to try it in the latest build from Github releases page.
