### ISSUE TITLE
BBIM | Cost item in BoQ value not zero when no quantity

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#4704]
If a cost item in a BoQ has zero quantity I think its `amount` should be zero and not like it is multiplied by 1 x `rate`

now I have the following:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/9c3ec488-2c01-4eed-b36f-f51c69a42601)

since `quantity` x `rate` = `amount` shouldn't it give 0  ? or I  am doing something wrong?
this is particularly important when quantities are calculated by importing a .csv pre-compiled cost schedule with queries

thanks

**Comment by Andrej730** [comment]
@steverugi can you please share an example .csv to reproduce this?

**Comment by steverugi** [comment]
[BoQ zero value.csv](https://github.com/IfcOpenShell/IfcOpenShell/files/15388478/BoQ.zero.value.csv)

**Comment by Andrej730** [comment]
I think it is correct, see [IfcCostItem documentation](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcCostItem.htm) below - when quantities are not provided, then values indicate total costs and not costs per quantity.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/f15e495b-8eaf-4923-b38a-823e22230d1e)


Therefore we just assume quantity = 1 in case if no quantities provided.
https://github.com/IfcOpenShell/IfcOpenShell/blob/9122f006c7056d802f5a0230427dcfba51b15fe0/src/blenderbim/blenderbim/bim/module/cost/data.py#L139

**Comment by steverugi** [comment]
Hi @Andrej730 
the statement "if CostQuantities is provided.. otherwise values indicate total cost" I assume refers to a Schedule of Rates, where in fact you do not have quantities

the way I understand it, in a BoQ the cost items and summary need to reflect the amount for each work as qty * rate, summed up in the summary item
please see image below

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/46c6cf17-988e-4458-8ad5-46d90ae105a2)

you would agree that the total should not be 495 but 375 since the only work that was, or to be, carried out is "item 1"

In a scenario where the BoQ is from created from a .csv file with queries, possibly a template to be used with different models, some cost items may have 0 quantity because not matching elements in the particular IFC/Project.

If BBIM were to be used professionally total items can be in the hundreds and those with the error (i.e. rate amount part of summary but no quantity) can be substantial and difficult to catch

I am going to have a chat with @maxfb87  on this, if you don't mind
thanks again for your assistance

**Comment by Moult** [comment]
@Andrej730 is correct that the IFC definition states that if no quantity is provided, the value is the total cost.

However, I think the real bug here is that we don't allow a quantity of 0. It should be valid to have a 0 quantity, and in that case 0 * value = 0.

**Comment by steverugi** [comment]
I like the solution proposed by @Moult ! thanks for stepping in :p

**Comment by steverugi** [comment]
thank you for fixing it, amazing job

**Comment by steverugi** [comment]
WOW thank you so much @Andrej730 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/27952e13-ed4e-40eb-b62c-b8f4dfc03c2a)


now 0 quantities and summary are well fixed, truly amazing!
