### ISSUE TITLE
BlenderBim-240520 - Request: make default window openings thicker / editable with modifier

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#4710]
Using this version:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/1e1f3628-262e-43f1-829c-ddcded2349ed)
on Windows 10

When placing a window along the edge of a wall, the IfcOpening that comes with it will often not puncture all the wall through.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/988d360f-890d-4f12-a75d-4951fc9864d7)

Would it be possible to make the default opening a bit thicker?

Or even make the opening  editable in the window modifier?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/6536432d-47f2-4f84-aa35-f8d85e4d3607)

When trying to edit the opening itself, it is now demarcated by a profile but the thickness does not seem accessible?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/62eab1cc-eb6a-4159-a5b0-bf9c1f6e246f)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/176fcf17-1787-4636-8dc4-df463501f3cd)

1st prize would be for the opening to detect the wall thickness and adjust automatically but at the moment we cant even edit the thickness/depth

**Comment by Moult** [comment]
@Andrej730 the reason it is 1.2 is because if you start off by inserting it in a thin wall, then later on in a thick wall, the void may not be sufficient. Surely 1.2m is thick enough for any wall? There must be another bug involved.

Certainly in the screenshot that wall isn't 1.2m thick.

Also the way it works is once you _manually_ edit the void, it will "remember" that manual edit. So if you manually make the opening less deep, then in the future if you put it in a thick wall this scenario can occur, but we assume its intentional since it was manually edited.

**Comment by Andrej730** [comment]
> @Andrej730 the reason it is 1.2 is because if you start off by inserting it in a thin wall, then later on in a thick wall, the void may not be sufficient. Surely 1.2m is thick enough for any wall? There must be another bug involved.

I've got lost with the units then :\ Is there any real life cases when there actually would be a 0.6m thick wall? If so, we can keep it as `max(wall_thickness, 1.2 meters)` to cover it.

> Also the way it works is once you _manually_ edit the void, it will "remember" that manual edit. So if you manually make the opening less deep, then in the future if you put it in a thick wall this scenario can occur, but we assume its intentional since it was manually edited.

This is probably the catch then, maybe some other window of the same type has the small opening and it's now getting copied.
@Plae-Blue-Dot can you please investigate other windows of the same type? Any ideas if any of them were manually edited to make opening smaller?

**Comment by Moult** [comment]
1.2m means that unless the wall is 1.2m too, it's big enough. There are
definitely walls 600mm thick, and even more, like cinema walls. However
1.2m is, uh, pretty rare (e.g. start thinking radiation bunkers in
hospitals).

If he edited the void manually, I'd say it's not a bug.

**Comment by Andrej730** [comment]
> 1.2m means that unless the wall is 1.2m too, it's big enough. There are definitely walls 600mm thick, and even more, like cinema walls.

But the way opening is positioned it will only cover 0.6m.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/7b353769-8d31-4582-98c9-2097307b5d7b)

**Comment by Moult** [comment]
Oh yes. Probably still rare enough not to matter I'd say. Probably cinema walls, heritage masonry, bunkers, that kind of stuff. The window may also be centered or inset often, or the wall broken down into its parts not as a huge single layerset wall.

Dion Moult

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by brunopostle** [comment]
My house has stone walls that are about 650mm thick!

**Comment by Plae-Blue-Dot** [comment]
@Andrej730 
none of the windows have been edited, I made the file from scratch natively in Blenderbim

**Comment by Plae-Blue-Dot** [comment]
I think I actually know what the issue is, 

the 1st instance of the window type was placed in a thinner wall and the 2nd instance was placed in a thicker wall. 
For some reason it seems that initial default generated opening thickness is saved with the type?

I've put in a new window type starting with the thicker wall and can replicate the same issue with an even thicker wall:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/d9887651-d941-4c6a-91ce-b6189f5fee0d)

file attached:
[window opening test - Copy.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15392131/window.opening.test.-.Copy.txt)

**Comment by Plae-Blue-Dot** [comment]
> @Andrej730 the reason it is 1.2 is because if you start off by inserting it in a thin wall, then later on in a thick wall, the void may not be sufficient. Surely 1.2m is thick enough for any wall? There must be another bug involved.
> 
> Certainly in the screenshot that wall isn't 1.2m thick.

It was not and it seems that it was not using the 1.2m thickness here but the actual wall thickness but I was certainly using BBIM-240520

> 
> Also the way it works is once you _manually_ edit the void, it will "remember" that manual edit. So if you manually make the opening less deep, then in the future if you put it in a thick wall this scenario can occur, but we assume its intentional since it was manually edited.

**Comment by Andrej730** [comment]
> Hi @Andrej730 thankyou for the commit,
> Unfortunately in some cases, I am still seeing this issue,

This commit wasn't intended to fix this, was fixing something I broke in 4fb34c0 😅

> If I use the default WT1 and dont add the modifier it seems to work as intended:

Was testing it a bit now too and I think this is the cause, window modifier is using different way to define opening thickness (based on the current voided object) and later that opening is copied. So we should unify it to use the default min 1.2m opening. Same issue for the doors.

**Comment by Andrej730** [comment]
Should be fixed after this commit.

**Comment by Plae-Blue-Dot** [comment]
It's worked on BBIM-240526! Much appreciated
