### ISSUE TITLE
BlenderBim Support Freestyle SVG export for fast drawing generation

### ISSUE THREAD

**Issue by carlopav** [IfcOpenShell/IfcOpenShell#4711]
ref: https://community.osarch.org/discussion/comment/20620/#Comment_20620

Turns out that on Blender 4.1 Freestyle svg export is super fast and quite accurate in exporting SVGs.

As a reference this is a part of a complex model that was instantly exported to svg:
![wcfl8czuy2zd](https://github.com/IfcOpenShell/IfcOpenShell/assets/47068848/d0c1950f-7f6f-47f0-a0e1-e0f51a90ce1e)

Would be useful to have it integrated in BlenderBim Drawings generation.

**Comment by Moult** [comment]
Implemented in 1d62f6f
