### ISSUE TITLE
segfault on create_shape() for zero-length segment of alignment representation

### ISSUE THREAD

**Issue by civilx64** [IfcOpenShell/IfcOpenShell#4713]
@RickBrice @aothms 

Steps to reproduce:

```
s = ifcopenshell.geom.settings()
model = ifcopenshell.open("model_with_alignment_representation.ifc")
comp_curve = model.by_type("IfcCompositeCurve")[0]
for seg in comp_curve.Segments:
    shape = ifcopenshell.geom.create_shape(s, seg)
```
(Seg fault thrown when the last segment is reached)
[FHWA_Bridge_Geometry_Alignment_Example_Python.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15395625/FHWA_Bridge_Geometry_Alignment_Example_Python.ifc.txt)

**Comment by RickBrice** [comment]
I could not reproduce the segfault using a jupyter notebook or IDLE. I whipped up a little c++ code and still no segfault, but did discover a divide by zero problem when generating number of evaluation points for the zero-length segment. My guess is divide by zero results in undefined behavior so it magically didn't segfault for me.

~~~
	IfcParse::IfcFile file("FHWA_Bridge_Geometry_Alignment_Example_Python.ifc");
	ifcopenshell::geometry::Settings settings;
	settings.get<ifcopenshell::geometry::settings::PiecewiseStepType>().value = ifcopenshell::geometry::settings::PiecewiseStepMethod::MAXSTEPSIZE;
	settings.get<ifcopenshell::geometry::settings::PiecewiseStepParam>().value = 1.0;

	auto mapping = ifcopenshell::geometry::impl::mapping_implementations().construct(&file, settings);

	auto ccs = file.instances_by_type<Schema::IfcCompositeCurve>();
	auto cc = (*ccs->begin())->as<Schema::IfcCompositeCurve>();
	auto segments = cc->Segments();
	for (auto segment : *segments)
	{
		auto mapped_item = mapping->map(segment);

		auto implicit_item = ifcopenshell::geometry::taxonomy::dcast<ifcopenshell::geometry::taxonomy::implicit_item>(mapped_item);
		auto pwf = ifcopenshell::geometry::taxonomy::dcast<ifcopenshell::geometry::taxonomy::piecewise_function>(implicit_item);
		pwf->evaluate(pwf->length());

		ifcopenshell::geometry::taxonomy::loop::ptr loop = ifcopenshell::geometry::taxonomy::dcast<ifcopenshell::geometry::taxonomy::loop>(pwf->evaluate());
   }
~~~

I fixed the divide by zero problem
https://github.com/IfcOpenShell/IfcOpenShell/blob/a976e63def3e196ae754495bb9c334c4a8af15e3/src/ifcgeom/taxonomy.cpp#L476
Now the last segment is evaluated and a loop with two points at the exact same location is created by `pwf->evaluate()`. Running the revised code in a jupyter notebook, there is now an error. Not sure if it is the same as you were seeing. This looks like something in the python code so I'm going to punt to @aothms. Though, there is something about Representation=None in the error message so maybe it's now an issue with the IFC model itself?

~~~
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_6956\567717572.py in ?()
      5 model = ifcopenshell.open("F:/IfcAlignmentDriver/TestFiles/FHWA_Bridge_Geometry_Alignment_Example_Python.ifc")
      6 comp_curve = model.by_type("IfcCompositeCurve")[0]
      7 for seg in comp_curve.Segments:
      8     print(seg)
----> 9     shape = ifcopenshell.geom.create_shape(s,seg)

F:\Python\Python312\Lib\site-packages\ifcopenshell\geom\main.py in ?(settings, inst, repr)
    276                 print("Shape creation failed")
    277     """
    278     return wrap_shape_creation(
    279         settings,
--> 280         ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
    281     )

F:\Python\Python312\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py in ?(*args)
   6157     create_shape(Settings settings, entity_instance instance, entity_instance representation=None, char const *const geometry_library) -> boost::variant< IfcGeom::Element *,IfcGeom::Representation::Representation *,IfcGeom::Transformation * >
   6158     create_shape(Settings settings, entity_instance instance, entity_instance representation=None) -> boost::variant< IfcGeom::Element *,IfcGeom::Representation::Representation *,IfcGeom::Transformation * >
   6159     create_shape(Settings settings, entity_instance instance) -> boost::variant< IfcGeom::Element *,IfcGeom::Representation::Representation *,IfcGeom::Transformation * >
   6160     """
-> 6161     return _ifcopenshell_wrapper.create_shape(*args)

RuntimeError: An unknown error occurred
~~~

**Comment by aothms** [comment]
There is something consistent going on here as per our previous conversation:

> 1. Segfault for Vertical Clothoids.  Based on the issue you raised I suspect this is an issue with the synthetic input dataset (specifically clothoid constant A = 0) and not with your implementation.

A = 0. Somehow it seems divide by zero consistently crashes in the case of @civilx64.

Is there something funky on your system @civilx64. Normal floating point exceptions don't trigger segfaults. Did you somehow configure floating point exceptions? E.g https://linux.die.net/man/3/feenableexcept

**Comment by aothms** [comment]
The unknown error is that the start and end point for the last segments are coincedental and therefore opencascade refusing to create an edge out of it @

>	_ifcopenshell_wrapper.pyd!`anonymous namespace'::curve_creation_visitor::operator()(const std::shared_ptr<ifcopenshell::geometry::taxonomy::edge> & e) Line 172	C++

`((std::shared_ptr<ifcopenshell::geometry::taxonomy::point3>*)&((ifcopenshell::geometry::taxonomy::edge*)curve._Ptr)->start.storage_.data_)`

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/0634cc0c-3246-47e0-aa25-f872f40aee59)

What would be the appropriate way to handle this? One thing we could do, but is fairly elaborate, map to taxonomy::point3 in this case, handle that in the occt kernel as a conversion to TopoDS_Vertex. Handle that in the triangulation as a single vertex, no edges, no face indices. At some point we need to handle point representations anyway... even if nobody asked for it up until now.

**Comment by civilx64** [comment]
I am running in a [Docker container](https://github.com/civilx64/dev-ifcopenshell-4x3-infra/blob/main/Dockerfile) based on python:3.11-bookworm image.  Test data and local repo are attached in the [Makefile](https://github.com/civilx64/dev-ifcopenshell-4x3-infra/blob/main/Makefile)

Happy to test with ubuntu:latest or other starting image if that would be helpful for the discussion.

**Comment by civilx64** [comment]
> The unknown error is that the start and end point for the last segments are coincedental and therefore opencascade refusing to create an edge out of it 

That confirms my hunch.

> What would be the appropriate way to handle this? One thing we could do, but is fairly elaborate, map to taxonomy::point3 in this case, handle that in the occt kernel as a conversion to TopoDS_Vertex. Handle that in the triangulation as a single vertex, no edges, no face indices. At some point we need to handle point representations anyway... even if nobody asked for it up until now.

My initial thought was to return a single vertex but I can understand the complexity of casting amongst various data structures.

> Edit: but ifcopenshell.geom.create_shape() ultimately isn't what we will end up using, because it forgets the tangents (I guess)?

For segments as well as the overall alignment curve ideally we expose the C++ `evaluate(u)` to python to allow for calculating the 4x4 transform at any point of interest along an overall alignment or individual alignment segment.  `ifcopenshell.geom.create_shape()` is still useful as the quickest way to get XYZ of IfcCompositeCurve, IfcGradientCurve, or IfcSegmentedReferenceCurve.

**Comment by RickBrice** [comment]
> For segments as well as the overall alignment curve ideally we expose the C++ evaluate(u) to python to allow for calculating the 4x4 transform at any point of interest along an overall alignment or individual alignment segment.

This makes a lot of sense for evaluating alignment geometry. There is also `evaluate(ustart,uend,nsteps)` to create a loop over a sub-range of the alignment. Also `evaluate2()` and `evaluate2(ustart,uend,nsteps)` that returns a pair containing the loop and a vector<double> with the u value corresponding to each point in the loop. Hopefully that can be exposed on the python side as well, otherwise "distance along" needs to be approximated with linear segments between points along the loop.

> `ifcopenshell.geom.create_shape()` is still useful as the quickest way to get XYZ of IfcCompositeCurve, IfcGradientCurve, or IfcSegmentedReferenceCurve.

`create_shape` for these curve types doesn't care about the zero-length segment. Perhaps `create_shape` might return a null object (null pointer, or whatever it is on the python side) for the zero-length IfcCurveSegment - that is, the zero-length segment doesn't have a shape. Though, that might make looping over the `Segments` container more difficult than necessary because you'd always have to check for a null object. It probably isn't a good idea to assume the zero-length segment exists (even though it is a requirement) and loop over n-1 elements. Some of the IfcRailRoom synthetic test cases don't have the zero-length segment.

Next steps are unclear to me - tell me what you need on the C++ side and I'll work on it. If there is something on the taxonomy or python sides that are easy, I could try those as well.

> I still have not reached the top of Mt. Everest that is getting the whole project to compile locally for Win

I've got a friend trying to build the C++ from source. Everything builds ok, but gets segfaults in code using IfcParse when creating a new file. I had the same problem early on but it magically went away after a lot of clean rebuilds. Here are the build instructions I've been using for the 0.8.0 branch for Win. https://github.com/RickBrice/PGSuperIfcExtensions/blob/1d44b6117e339b1a44b4154f7540ec61e049b42a/devdocs/Dependencies.md. They work for me, your milage may vary.

**Comment by civilx64** [comment]
I see two next steps:

1. Revise the C++ to return something null-like for `create_shape()` on the zero-length final segment.  In python this would be `None`.
2. Wrap `evaluate(u)` and its cousins for both segments and overall alignment so it is exposed on the python side.  This gets us the desired single point on the final zero-length segment - which is its exact purpose.

> It probably isn't a good idea to assume the zero-length segment exists (even though it is a requirement) and loop over n-1 elements

Good point in the spirit of being flexible in the input data that is accepted.  The specific task I'm working on now is comparing the calculated end point of segment `n` to the provided start point of segment `n + 1`.  This would involve comparing the results of `evaluate(L)` for segment `i` to `evaluate(0.)` of segment `i + 1` which works regardless of how long the final segment is.

Thanks for the tips on C++.  I'll give it a shot later today.

**Comment by RickBrice** [comment]
> Wrap `evaluate(u)` and its cousins

I think we get this for "free". Looking through ifcopenshell_wrapper.py that SWIG generates, there appears to be wrapper functions.

I'm not sure how to get at them from python.

**Comment by civilx64** [comment]
Here's how you get to it.  

``` python
Python 3.11.8 (main, Mar 12 2024, 11:41:52) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ifcopenshell import ifcopenshell_wrapper as wrapper
>>> pwf = wrapper.piecewise_function()
>>> pwf
<ifcopenshell.ifcopenshell_wrapper.piecewise_function; proxy of <Swig Object of type 'ifcopenshell::geometry::taxonomy::piecewise_function *' at 0x7fb948d5fd20> >
>>> pwf.evaluate
<bound method piecewise_function.evaluate of <ifcopenshell.ifcopenshell_wrapper.piecewise_function; proxy of <Swig Object of type 'ifcopenshell::geometry::taxonomy::piecewise_function *' at 0x7fb948d5fd20> >>
>>> pwf.evaluate()
Segmentation fault
```
I can't work out how to utilize it in python but I suspect it's something like [IfcCompositeCurve.cpp#L79](https://github.com/IfcOpenShell/IfcOpenShell/blob/579768c35fe3b3ffa44092727488f0c87b8f34a1/src/ifcgeom/mapping/IfcCompositeCurve.cpp#L79).

**Comment by RickBrice** [comment]
In c++ we would map the IfcCompositeCurve, IfcCurveSegment, etc to an implicit item pwf with a mapping object. There must be a way to create the mapping object in python. 

~~~
IfcParse::IfcFile file("FHWA_Bridge_Geometry_Alignment_Example_Python.ifc");
ifcopenshell::geometry::Settings settings;
settings.get<ifcopenshell::geometry::settings::PiecewiseStepType>().value = ifcopenshell::geometry::settings::PiecewiseStepMethod::MAXSTEPSIZE;
settings.get<ifcopenshell::geometry::settings::PiecewiseStepParam>().value = 1.0;

auto mapping = ifcopenshell::geometry::impl::mapping_implementations().construct(&file, settings);

auto ccs = file.instances_by_type<Schema::IfcCompositeCurve>();
auto cc = (*ccs->begin())->as<Schema::IfcCompositeCurve>();
auto segments = cc->Segments();
for (auto segment : *segments)
{
auto mapped_item = mapping->map(segment);
auto pwf = ifcopenshell::geometry::taxonomy::dcast<ifcopenshell::geometry::taxonomy::piecewise_function>(mapped_item);
Eigen::Matrix4d p = pwf->evaluate(pwf->length());

ifcopenshell::geometry::taxonomy::loop::ptr loop = ifcopenshell::geometry::taxonomy::dcast<ifcopenshell::geometry::taxonomy::loop>(pwf->evaluate());
}
~~~

**Comment by aothms** [comment]
I pushed a commit to implement the "Wrapping of mapping" using Swig. It's not really finished yet, so you there's quite a few `ifcopenshell_wrapper` and `.wrapped_data` in there. But other than that it seems to work. This really took a lot more boilerplate than I had hoped if we can replace this with something from the current century at some point I would be very happy. cc @Krande.

```
>>> import ifcopenshell, ifcopenshell.geom
>>>
>>> pt = f.by_type('IfcCartesianPoint')[3]
>>> pt
#21=IfcCartesianPoint((2142.237995,1436.01482))
>>> ifcopenshell.ifcopenshell_wrapper.map_shape(ifcopenshell.geom.settings(), pt.wrapped_data)
point3 652.954 437.697 0

>>> f.by_type('IfcLine')[0]
#31=IfcLine(#28,#30)
>>> ifcopenshell.ifcopenshell_wrapper.map_shape(ifcopenshell.geom.settings(), _.wrapped_data)
line
    matrix4 0 0 1 0 0 -1 0 0 1 0 0 0 0 0 0 1
>>>
>>> f = ifcopenshell.open('FHWA_Bridge_Geometry_Alignment_Example_Python.ifc')
>>> f.by_type('IfcCompositeCurve')[0]
#102=IfcCompositeCurve((#34,#43,#52,#61,#70,#79,#88,#97),.F.)
>>> inst = _
>>> pwf = ifcopenshell.ifcopenshell_wrapper.map_shape(ifcopenshell.geom.settings(), inst.wrapped_data)
piecewise_function

>>> pwf.evaluate(0.0)
((0.8392527899703554, 0.5437414408769802, 0.0, 152.4), (-0.5437414408769802, 0.8392527899703554, 0.0, 762.0), (0.0, 0.0, 1.0, 0.0), (0.0, 0.0, 0.0, 1.0))
```

**Comment by civilx64** [comment]
> This really took a lot more boilerplate than I had hoped if we can replace this with something from the current century at some point I would be very happy.

Perhaps this is an opportunity to investigate [pybind11](https://pybind11.readthedocs.io/)?

**Comment by aothms** [comment]
That's what I was alluding to :) or the alternative from the same author.
Currently the wrapper code is huge and complex. I don't think it'll happen
anymore in 0.8.

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op do 23 mei 2024 15:14 schreef Scott Lecher ***@***.***>:

**Comment by Krande** [comment]
@aothms FYI: I am almost done with porting Code Aster (which uses pybind11 btw) to MSVC. 

After that I'll look into ifcopenshell and nanobind/pybind11. My plan was that I'll start exposing the parts of the C++ API specific to geometry handling and tessellation using nanobind. After that we can take a look at how that works and how we might use it to expose the rest of the api? 

IIRC I did  to set up a minimal nanobind example for ifcopenshell last time I tried. But I think the CGAL implementation in the v0.8 branch wasn't quite ready at the time (it is a long time ago). I guess v0.8 is more stable now? It would definitively give me a running start if you have any working C++ examples of constructing some simple geometries (IfcSphere and maybe fcExtrudedAreaSolid?) and calling CGAL/OpenCasCade to tessellate.

Ideally as a start I'd like a way to efficiently pass in bulk to c++ tons of geometry definitions and let c++ efficiently convert that to tessellated geometries :)

**Comment by aothms** [comment]
Build for the latest commit is up https://github.com/IfcOpenBot/IfcOpenShell/commit/90ae7091563348c42623220ea914c42d70485c03#commitcomment-142335267

@Krande great to hear

> examples of constructing some simple geometries 

They are here:

Construction:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcgeom/mapping/IfcExtrudedAreaSolid.cpp

Constructing the kernel:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcgeom/AbstractKernel.h#L75

(with `"cgal"` or `"opencascade"` or `hybrid-...` for geometry library)

Converting to native brep/polyhedra:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcgeom/Converter.cpp#L43

Triangulation:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcgeom/kernels/opencascade/OpenCascadeConversionResult.cpp#L34

**Comment by civilx64** [comment]
Closing this issue as there is no need to call `create_shape()` for a segment since we can `evaluate(u)` at any point of interest.
