### ISSUE TITLE
Discrepancy in the model generated by IFC convert

### ISSUE THREAD

**Issue by MonishVinceant1506** [IfcOpenShell/IfcOpenShell#4714]
Hi Team, 
The following model looks correct in the external IFC viewer and inside its native detailing software **(Bentley with ProStructures)**, however, when converted GLB using IFC convert, it seems it is having the following discrepancies.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110485123/56183428-1ff5-449f-9bea-64df008ac178)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/110485123/dfc6702c-0a3f-4402-970c-a6369da58992)

1. The holes are missing
2. Angle cut is not generated properly
3. Extension of the plates is not visible.

Please find the attached models. Please let us if, something missing in here.
[Models.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15396030/Models.zip)

Regards,
Monish

**Comment by Moult** [comment]
You should enable the `--strict-tolerance` flag. In general, this should always be enabled I think. Ping @aothms how about making it enabled by default in 0.8.0?

https://docs.ifcopenshell.org/ifcopenshell/geometry_settings.html#strict-tolerance

```
IfcConvert --strict-tolerance model.ifc out.glb
```

**Comment by aothms** [comment]
> how about making it enabled by default in 0.8.0?

It is. That is to say, the setting doesn't exist anymore as such.  https://github.com/IfcOpenShell/IfcOpenShell/issues/4565#issuecomment-2095469588

**Comment by MonishVinceant1506** [comment]
@Moult ,
Thank you, using the strict tolerance resolved the issue.
