### ISSUE TITLE
Problems with alignment geometry

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#4715]
Now that @civilx64 and @aothms are starting to make use of the IfcCurveSegment mapping, and mapping individual segments rather than full IfcCompositeCurves, several problems in the alignment geometry implementation come to mind. I didn't expect individual segments to be mapped and used in isolation.

Problems are:

- The piecewise_function for individual segments doesn't have the results in the correct positions in the 4x4 matrix. Example - vertical segments are modeled in the "distance along","elevation" plane so the resulting 4x4 matrix is really a 2D set of data in the x-y plane. The conversion to the 3D coordinate space is done in the mapping function for IfcGradientCurve. The conversion to 3D space should happen at the curve segment level. https://github.com/IfcOpenShell/IfcOpenShell/blob/a976e63def3e196ae754495bb9c334c4a8af15e3/src/ifcgeom/mapping/IfcGradientCurve.cpp#L54-L66

- Similar problem for cant and IfcSegmentedReferenceCurve. https://github.com/IfcOpenShell/IfcOpenShell/blob/a976e63def3e196ae754495bb9c334c4a8af15e3/src/ifcgeom/mapping/IfcSegmentedReferenceCurve.cpp#L50-L63

- For several of the cant segments, the cant values "drift" compared to the results posted in the https://github.com/bSI-RailwayRoom/IFC-Rail-Unit-Test-Reference-Code repo. I know what is causing the problem, but don't have a solution yet.

I'll get to work on cleaning this up. Just wanted to make you aware of some potential pitfalls.

**Comment by RickBrice** [comment]
I got the problem with cant drift resolved (See 579768c35fe3b3ffa44092727488f0c87b8f34a1), but I think it comes at the expense of messing up the Axis vector defining the cross slope between railheads.

The https://github.com/bSI-RailwayRoom/IFC-Rail-Unit-Test-Reference-Code only lists U,V for cant. Do you know where there may be positioning vectors for cant?

**Comment by civilx64** [comment]
> I got the problem with cant drift resolved (See [579768c](https://github.com/IfcOpenShell/IfcOpenShell/commit/579768c35fe3b3ffa44092727488f0c87b8f34a1)), but I think it comes at the expense of messing up the Axis vector defining the cross slope between railheads.

Agreed, great job!, VS Code has a nice diff view of the matplotlib png output showing the fix: 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/26513472/9d9c31b2-cea6-4fd3-8249-5991b84569d6)

 > The https://github.com/bSI-RailwayRoom/IFC-Rail-Unit-Test-Reference-Code only lists X,Y,Z for cant. Do you know where there may be positioning vectors for cant?

Assuming you are talking about pre-computed values for cant rotation to be used for our testing purposes - no, I am not aware of any.

> @civilx64 What cant results are you looking at? I'm using https://github.com/bSI-RailwayRoom/IFC-Rail-Unit-Test-Reference-Code/tree/master/alignment_testset/ToolboxProcess-C/CantAlignment.

Yes, I'm using these as well.

**Comment by civilx64** [comment]
>    The piecewise_function for individual segments doesn't have the results in the correct positions in the 4x4 matrix. Example - vertical segments are modeled in the "distance along","elevation" plane so the resulting 4x4 matrix is really a 2D set of data in the x-y plane. 

IMO this is not a bug but a feature!

> The conversion to the 3D coordinate space is done in the mapping function for IfcGradientCurve. The conversion to 3D space should happen at the curve segment level.

Nah, I say keep it as-is.  We can always use the "distance along" to get to world coordinates but it's harder to go the other direction!

**Comment by Moult** [comment]
Is this still something that needs fixing?

**Comment by civilx64** [comment]
Nope, thus far in testing the calculations for 4x4 transform at a given distance along a segment are returning the expected results.
