### ISSUE TITLE
IfcTester: Issue with comparison of negative numbers

### ISSUE THREAD

**Issue by SteezoTheEngineer** [IfcOpenShell/IfcOpenShell#4716]
Hi,

First of all, many thanks for this great library.

Unfortunately, I faced an issue with the ifcTester module. If I want to check if negative values are equal, the comparison will fail. Here are the two lines which cause the problem:

https://github.com/IfcOpenShell/IfcOpenShell/blob/69c197c1a4f047791befbae11e890be64026b7e7/src/ifctester/ifctester/facet.py#L335
https://github.com/IfcOpenShell/IfcOpenShell/blob/69c197c1a4f047791befbae11e890be64026b7e7/src/ifctester/ifctester/facet.py#L861

If I were to come up with a solution, I would add and subtract the tolerance or work with absolute values:
` if value < cast_value - 1e-6 or value > cast_value + 1e-6:`
or 
` if abs(value) < abs(cast_value) * (1.0 - 1e-6) or abs(value)> abs(cast_value)* (1.0 + 1e-6): `

Here you can see the issue and the possible solutions:
```
>>> cast_value = -4
>>> value = cast_value
>>> value < cast_value * (1.0 - 1e-6) or value > cast_value * (1.0 + 1e-6)
True
>>> value < cast_value - 1e-6 or value > cast_value + 1e-6
False
>>> abs(value) < abs(cast_value) * (1.0 - 1e-6) or abs(value)> abs(cast_value)* (1.0 + 1e-6)
False 
```
If you need further information about my issue, please let me know.

Best regards,
Stefan

**Comment by aothms** [comment]
Hi Stefan. In fact this is rather in line with my recommendation in the IDS group. Feel free to voice your opinion there as well. https://github.com/buildingSMART/IDS/issues/78#issuecomment-2011869359

**Comment by SteezoTheEngineer** [comment]
@aothms, thank you for the quick response. I have also left a comment on https://github.com/buildingSMART/IDS/issues/78#issuecomment-2011869359.
