### ISSUE TITLE
[IfcConvert] Excessive Vertex generation (ifc => glb)

### ISSUE THREAD

**Issue by ketourneau** [IfcOpenShell/IfcOpenShell#4718]
Hi,

We try to convert ifc to glb with IfcConvert and we see that glb conversion looks to generate some excessive output vertex.
It seems COLLADA2GLTF it more efficient to convert dae to glb than IfcConvert (https://github.com/KhronosGroup/COLLADA2GLTF).

Pipeline 1 
```
./IfcConvert 02_ep.ifc 02_ep.glb
```

Pipeline 2
```
./IfcConvert 02_ep.ifc 02_ep.dae
./COLLADA2GLTF/COLLADA2GLTF-bin -b 02_ep.dae 02_ep.glb
```

And then we compare the result with https://github.khronos.org/glTF-Validator/
Pipeline 1 
```
Vertex count: 11985
Triangle count: 7703
```

Pipeline 2
```
Vertex count: 8095
Triangle count: 7703
```

Why IfcConvert generate more vertex than Collada2Gltf ?

[02_ep.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15405404/02_ep.ifc.zip)

**Comment by Gorgious56** [comment]
Hello, since the triangle number is the same in both pipelines I suspect pipeline 1 creates "disjointed" vertices for each triangle whereas the second one merges them. Maybe there is a setting in IfcConvet for merging vertices ?

**Comment by ketourneau** [comment]
Thanks for your reply !

We try with `--weld-vertices` option in IfcConvert, we got less vertex but we see some unwanted shading artefacts in our rendering application (like option description say).

```
--weld-vertices                       Specifies whether vertices are welded,
                                        meaning that the coordinates vector
                                        will only contain unique xyz-triplets.
                                        This results in a manifold mesh which
                                        is useful for modelling applications,
                                        but might result in unwanted shading
                                        artefacts in rendering applications.
```

Output :
```
Vertex count: 5244
Triangle count: 7703
```

**Comment by Moult** [comment]
So is this a bug? It sounds like its working as designed, and that welded vertices may result in shading artefacts? Maybe disable vertex normal smoothing (smooth shading) in your rendering app?

**Comment by ketourneau** [comment]
Ok so we will continue to use Collada2Gltf to convert dae to glb because it's more robust for us without weld-vertices parameter.
Yes, we apply draco compression at the end of our pipeline.

I thought it might give you an idea for ifc to glb conversion improvement with IfcConvert.
