### ISSUE TITLE
AttributeError: module 'ifcopenshell' has no attribute 'util'

### ISSUE THREAD

**Issue by andzejsp** [IfcOpenShell/IfcOpenShell#4720]
Windows 10
Newest blender 4.1.
Blender addon blenderbim

Does not work, throws a long list: at the end
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/80409979/82422f15-90e9-4099-ac7e-750fbc982c1b)

**Comment by Moult** [comment]
Is this an installation problem? If so, try following https://docs.blenderbim.org/users/troubleshooting.html#installation-issues

**Comment by andzejsp** [comment]
> Is this an installation problem? If so, try following https://docs.blenderbim.org/users/troubleshooting.html#installation-issues

I guess there should be a warning on the docs page tht if you had previous blender versions on windows atleast, after installing it will copy over garbage to the new version.

Deleting this folder and opening blender 4.1 all over again fixed it
```
C:\Users\{YOUR_USER}\AppData\Roaming\Blender Foundation\4.1\
```
