### ISSUE TITLE
IFCRailing Type-Custum- add voids give error

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4722]
Please help, not sure if this is the correct form, I have the attached problem and don't know how to fix it.

Thanks

os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.0.240523
last_actions: 
# operator: BIM_OT_override_mode_set_object
# operator: BIM_OT_update_representation
# ifcopenshell.api: geometry.add_representation
>>> {"context": {"cast_type": "entity_instance", "value": 15, "Name": null}, "blender_object": "<bpy_struct, Object(\"IfcRailingType/Palaside 1600\") at 0x0000022ACFF5CF08>", "geometry": "<bpy_struct, Mesh(\"15/15237\") at 0x0000022ACFF26B08>", "coordinate_offset": "None", "total_items": "1", "should_force_faceted_brep": "False", "should_force_triangulation": "False", "should_generate_uvs": "False", "ifc_representation_class": "None", "profile_set_usage": "None", "text_literal": "None"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 15228, "Name": "Palaside 1600"}, "representation": {"cast_type": "entity_instance", "value": 15240, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 15240, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 15228, "Name": "Palaside 1600"}}
# ifcopenshell.api: style.assign_representation_styles
>>> {"shape_representation": {"cast_type": "entity_instance", "value": 15259, "Name": null}, "styles": "[]", "should_use_presentation_style_assignment": "False"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 15228, "Name": "Palaside 1600"}, "representation": {"cast_type": "entity_instance", "value": 15237, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 15237, "Name": null}}
# operator: BIM_OT_add_opening
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\void\operator.py", line 84, in _execute
    for opening in [r.RelatedOpeningElement for r in element1.HasOpenings]:
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 219, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IFC4.IfcRailingType' has no attribute 'HasOpenings'

ifc: HFCC-Chrech Toilet.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240523-edfd446
[HFCC-Chrech Toilet.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15415327/HFCC-Chrech.Toilet.txt)

**Comment by Moult** [comment]
Thanks for your report! The error is now fixed. It's not allowed to apply openings to things like type elements ... only occurrences are allowed.
