### ISSUE TITLE
Schedule of Rates export error

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#4723]
Step to reproduce:
1 create a "schedule of rates" under Costing and Scheduling tab
2 click export in order to export it to a spreadsheet

it raises this error
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/4084e539-6153-441f-82d6-94645b715abd)

I think it is related with latest commits..

**Comment by Andrej730** [comment]
@maxfb87 Hi! Can't reproduce this, can you please share sample .ifc file?

**Comment by steverugi** [comment]
I tried it with Win10 - 4.1.0 / 240526 export of schedule of rates seems fine

**Comment by maxfb87** [comment]
@Andrej730 actually it works with a new fresh file, but it still doesn't work with this file
[sor_problem.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15464967/sor_problem.txt)
So maybe is just this file that is corrupted (and it is absolutely not important) but if can be helpful i've attached it.
Cheers!

**Comment by Andrej730** [comment]
Thanks for the bug report. The issue was unrelated to the latest changes - it occurred if there was a cost item without quantities but with controlled objects with quantities.
