### ISSUE TITLE
Schedule columns don't delete

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#4724]
If you add a "schedule column" under a cost schedule, they are impossible to delete
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/8da951dd-2a59-47d0-9701-6c7a7280f884)
and also if i create a new "cost schedule", there are the same added columns

**Comment by Andrej730** [comment]
Fixed yesterday in e4aa970
