### ISSUE TITLE
[IfcTester] - IfcMapConversion.Xaxis[...] attributes cannot be read ?

### ISSUE THREAD

**Issue by Zdeniso** [IfcOpenShell/IfcOpenShell#4726]
Hi,
I'm having a few problems with the results from BBIM's ifctester module.

1) In the IFCMAPCONVERSION entity I am trying to validate the ‘XaxisAbscissa’ and ‘XaxisOrdinate’ data. Even with the data integrated from BBIM or hardcoded in the ifc file, ifctester displays an empty value.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/82089944/6826fb46-9a42-4934-9124-26f3163feae3)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/82089944/4c9e3f7f-7575-43e4-b023-c4e4eacf7cfd)

2) I don't know how to make a reference from another ifcEntity as a value, tried to put a pattern with the entity itself but doesn't work. Since it's only the id referenced by the attribute in the ifc file, i have no idea how to overcome this. Does anyone have an idea ?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/82089944/a2247040-2701-4fa4-a7e3-fc6580b820aa)

3) Some pattern doesn't match but should function. I tested theim on regex101 and they are working there, but not with Ifctester. Is it because the datatype attented here is a list of Ifclabel and not a simple ifclabel ?
<img width="968" alt="image" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/82089944/30e7d7e1-0ea2-44af-a575-d8e2436d84b4">

I'll be thankfull for anyhelp.

Have a great day.

Denis

**Comment by Moult** [comment]
1. At a glance, the "a" in Axis should be capitalised.
2. This is a limitation in IDS and cannot be done. IDS cannot traverse relationships.
3. This is a limitation in IDS and cannot be done. IDS cannot check list/set attributes.

**Comment by Zdeniso** [comment]
Hi @Andrej730 and @Moult and thanks a lot for your answers !

I think @Moult resolved this "issue" (which was just a lack of understanding from me about the IDS possibilities) but here it is @Andrej730 :

ifc : [MAQ_DEMO_01 - Copie.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15442363/MAQ_DEMO_01.-.Copie.txt)
ids : [DP_IDS_Dictionnary copy.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15442364/DP_IDS_Dictionnary.copy.txt)
xsd 1.0 : [IDS_1.0.0 copy.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15442368/IDS_1.0.0.copy.txt)

I'll try to overcome this limitation with python and ifcopenshell.

Again thank you very much both of you.
