### ISSUE TITLE
BBIM Feature Request | add "Category" box when creating a new Material

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#4729]
on creating a new material the UI does not show its future category, only the name

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/b4478dfc-f9a5-48a9-a6fb-3f1dc856463a)

it would be handy to have that option instead of editing the same material after

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/cd7eebe9-f157-45b1-be88-12343e76ed96)

thanks

**Comment by theoryshaw** [comment]
I can tackle this, i think.

**Comment by steverugi** [comment]
wow
that was fast

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/2fcc3af1-7172-4799-91b1-cb44017c3693)

thank you!
