### ISSUE TITLE
Linked ifc files into drawings?

### ISSUE THREAD

**Issue by jsaarane** [IfcOpenShell/IfcOpenShell#4730]
Hi There,
We are soon finishing our first big project with blenderbim and I need to hand in drawings very urgently. We are working with our own discipline model of Lighting design. I need to make the drawings with at least the architectural model visible (maybe even MEP). Currently the use of linked files in drawings isn't supported. I discussed with Dion today and heard there might be a solution for this.

**Comment by theoryshaw** [comment]
+1
related: https://github.com/IfcOpenShell/IfcOpenShell/issues/3847

**Comment by Moult** [comment]
Oh right @theoryshaw this is a duplicate :)
