### ISSUE TITLE
Failed to process subtractions on walls (example file) 

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#474]
1. Convert [474--walls--missing-subtractions--1--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/474--walls--missing-subtractions--1--augmented.ifc) with 92f4d76
2. Experience error when converting:
```
[Error] {a} Flattening face boundary
#166=IfcFaceOuterBound(#167,.T.)
[Warning] {a} Failed to sew faceset
[Error] {a} Failed to process subtraction:
#155=IfcBooleanResult(.DIFFERENCE.,#156,#163)
[Error] {a} basic_string::substr: __pos (which is 2) > this->size() (which is 1)
[Warning] {b} Failed to sew faceset
[Error] {b} Failed to process subtraction:
#304=IfcBooleanResult(.DIFFERENCE.,#305,#341)
[Error] {b} basic_string::substr: __pos (which is 2) > this->size() (which is 1)
[Error] {c} Flattening face boundary
#440=IfcFaceOuterBound(#441,.T.)
[Warning] {c} Failed to sew faceset
[Error] {c} Failed to process subtraction:
#386=IfcBooleanResult(.DIFFERENCE.,#387,#423)
[Error] {c} basic_string::substr: __pos (which is 2) > this->size() (which is 1)
[Warning] {d} Failed to sew faceset
[Error] {d} Failed to process subtraction:
#639=IfcBooleanResult(.DIFFERENCE.,#640,#648)
[Error] {d} basic_string::substr: __pos (which is 2) > this->size() (which is 1)
[Error] {e} Self-intersections with 2 cycles detected
#783=IfcPolyLoop((#784,#785,#763,#762,#786,#28,#787,#788,#789,#790,#791,#792,#793,#794,#795,#796,#797,#798,#799,#797,#800,#801))
[Error] {e} Self-intersections with 2 cycles detected
#808=IfcPolyLoop((#809,#810,#811,#812,#813,#814,#815,#816,#817,#818,#819,#820,#765,#764,#805,#821,#822,#823,#824,#825,#826,#824))
[Error] {e} Failed to process subtraction:
#734=IfcBooleanResult(.DIFFERENCE.,#735,#741)
[Error] {e} basic_string::substr: __pos (which is 2) > this->size() (which is 1)
```
3. Experience that the walls look like this:
<img width="509" alt="screen shot 2018-09-24 at 12 43 05" src="https://user-images.githubusercontent.com/4601554/45948336-d9667d00-bff7-11e8-9bbd-aea49b58982c.png">

4. Expected geometry from SimpleBIM and Solibri:
<img width="606" alt="screen shot 2018-09-24 at 12 43 35" src="https://user-images.githubusercontent.com/4601554/45948342-dd929a80-bff7-11e8-9403-b4afdd95c544.png">

This seems related to #471, which is also originally an export from Archicad 21

**Comment by johanrd** [comment]
Adding a new case to this issue:
1. Convert [474--walls--missing-subtractions--2.ifc](https://github.com/IfcOpenShell/files/blob/master/474--walls--missing-subtractions--2.ifc) with 3102a1c
2. Experience that the walls are not cut at the roof angle:
<img width="300" alt="screen shot 2018-09-25 at 16 17 14" src="https://user-images.githubusercontent.com/4601554/46020999-f1193080-c0df-11e8-9147-467944bbd8fa.png">

3. Expected geometry from SimpleBIM and Solibri:
<img width="300" alt="screen shot 2018-09-25 at 16 18 15" src="https://user-images.githubusercontent.com/4601554/46020957-d6df5280-c0df-11e8-85a2-c57dffcabad0.png">

**Comment by aothms** [comment]
2nd file appears correct now (on v0.6.0)

![afbeelding](https://user-images.githubusercontent.com/1096535/50518811-fe1b3680-0ab7-11e9-8625-6bae8e128b8d.png)

**Comment by johanrd** [comment]
@aothms yes, it is definitely an option to switch to v0.6.0 soon. 

We've done some initial testing, and there seems to be some regressions between v0.5.0 and v0.6.0, so 0.5.0 appears more stable at this point still:

#358
#377
#457
#458
#422
#426 
#451
#459

**Comment by aothms** [comment]
![afbeelding](https://user-images.githubusercontent.com/1096535/58329768-a0580400-7e35-11e9-9751-2f6015a62cff.png)

![afbeelding](https://user-images.githubusercontent.com/1096535/58329843-d0070c00-7e35-11e9-9e55-44169eca0bf7.png)

Looks ok to me now on the 0.6 branch

**Comment by johanrd** [comment]
Closing, as this seems to be working on 98bf6c2d9549c78a62257dda69546a92693a6b85 (OCCT 7.3.0p3) 🎉

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
