### ISSUE TITLE
C++, how do I get the unit and/or measure of a property?

### ISSUE THREAD

**Issue by SoftwareMechanic** [IfcOpenShell/IfcOpenShell#4742]
I am creating my own serializer inspired by XmlSerializer, but even when creating XML through the XmlSerializer, I found that property sets, exports only properties, without reference to the measures/units.

in python, I am able to do something like the following:
```
for prop in ifc_property_set.HasProperties:

    if prop.is_a('IfcPropertySingleValue'):
        nominal_value_info = prop.NominalValue.get_info() if prop.NominalValue is not None else dict()
        wrapped_value = str(nominal_value_info.get("wrappedValue"))  or ""
        value_type = nominal_value_info.get("type") or ""
        value_unit = ""

        if value_type.endswith('Measure'):
            value_unit =  self.from_measure_to_unit(value_type)
```

but I need to be able to do it in c++ and here is what I tried:

```
IfcSchema::IfcProperty* p = *it;
if (p->declaration().is(IfcSchema::IfcComplexProperty::Class())) {
      IfcSchema::IfcComplexProperty* complex = p->as<IfcSchema::IfcComplexProperty>();
      format_properties(complex->HasProperties(), node);
}
if (p->declaration().is(IfcSchema::IfcPropertySingleValue::Class())) {
      std::cout << p->Name() << std::endl;
      std::cout << p->declaration().attribute_by_index(2) << std::endl;
      std::cout << p->data().getArgument(2)->type() << std::endl;
      std::cout << p->data().toString() << std::endl;
      
      format_entity_instance(p, node);
}
else {
      format_entity_instance(p, node);
}
```

in the second 'if' statement, if I print the `property->data().toString()` I can see the whole Ifc element, like the following:

`#114229=IfcPropertySingleValue('property X',$,IfcLengthMeasure(3.9116000000000009),$)`

so I tried to get the third argument and manage it but I can not get any readable data.

I got something like this:
`
0000028352DED200`
or
`9`

I would need to be able to get, for this example, the 'IfcLenghtMeasure' string value, so I can map it to the project units (in this case LENGTHUNIT), if the unit from the NominalValue returns null. 
otherwise I cannot map properties to their units.

EDIT:

I found that by doing this:

```
IfcSchema::IfcPropertySingleValue* singleValueProp = p->as<IfcSchema::IfcPropertySingleValue>();
std::cout << singleValueProp->data().getArgument(2)->toString() << std::endl;
```

I can see a string result like this: `IfcVolumeMeasure(7.3043165588533308E-05)`
so here I could take everythinig before the first round bracket, but I don't like this solution to be honest, I will use this only if there is no a more clean way to get the measureType.

do you have some hint for that?

**Comment by SoftwareMechanic** [comment]
SOLVED:

I had to do something like this to get only the measure type string value.

```
IfcSchema::IfcValue* ifcValue = singleValueProp->NominalValue();
bool isIfcValueNull = ifcValue == nullptr;

if (!isIfcValueNull) {
std::cout << ifcValue->data().type()->name();
}
```

**Comment by Moult** [comment]
A minor note for anybody attempting this in Python, you can just do property.NominalValue.is_a() to get the data type.

Note that from the data type you then need to get the unit. Python has a handy function for this `ifcopenshell.util.unit.get_property_unit` which handles situations where the unit doesn't exist, or fallback to a project default, or non single properties (enumerations, list, bounded, etc).

**Comment by SoftwareMechanic** [comment]
thank you @Moult for the hint, despite now I am working on C++ side this is very helpful as I usually use both C++ and Python depending on the task/project.
I will update my python code 😄

**Comment by Moult** [comment]
Cheers, there are lots of useful unit related things you can do with
`ifcopenshell.util.unit`. You might also like to use `verbose=True` with
`ifcopenshell.util.element.get_psets` which gets extra data like units
and IDs.
