### ISSUE TITLE
Add IfcSite to the existing project

### ISSUE THREAD

**Issue by EdwardWinter** [IfcOpenShell/IfcOpenShell#4750]
Opening an IFC file which is not produced by Blender BIM, I want to supply the IfcSite below the IfcProject in the Schema.

For more detail: the IFC is produced from Autodesk Civil 3D into IFC4x3. The file is missing the IfcSite class right below the IfcProject class. Although it seems not to be a reuirement to have an IfcSite below the IfcProject, according to the latest IFC4x3 schema, it would be fine to have it. Read: the possibility to add it. Because other vendor software are checking against this schema structure. If it does not have it, it qualifies it as a wrong schema.

See attached IFC4x3 file for reference:
[Alignment_Corridor.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15453821/Alignment_Corridor.zip)

**Comment by Andrej730** [comment]
Example:

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/5269639b-f5f4-48ff-b2b8-ceabeeb3b519

Note that there is currently a bug in #4434 if you would try to assign IfcRoad to IfcSite through "Aggregates" panel but it works by moving collections.

**Comment by EdwardWinter** [comment]
Hi Andrej,Thanks for the quick respond and given solution for me.I’ve followed your instruction video and tested it and it works!Many thanks, and keep up the good work!Best regards, EdwardVerstuurd vanaf mijn iPhoneOp 27 mei 2024 om 15:48 heeft Andrej ***@***.***> het volgende geschreven:﻿
Example:
https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/5269639b-f5f4-48ff-b2b8-ceabeeb3b519
Note that there is currently a bug in #4434 if you would try to assign IfcRoad to IfcSite through "Aggregates" panel but it works by moving collections.
