### ISSUE TITLE
BBIM RFI | Selector Syntax for IfcElementAssembly

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#4756]
I need to add, if possible, the related IfcElementAssembly name of elements to be used in a schedule or selection
what is the syntax to use in `Grouping and Filtering` > `Search` or `Spreadsheet Import/Export` query?
thanks

**Comment by theoryshaw** [comment]
+1
related: https://github.com/IfcOpenShell/IfcOpenShell/issues/4638

**Comment by Moult** [comment]
Implemented - see duplicate bug

**Comment by Moult** [comment]
I misread this. It's not a duplicate. This also requests for it to be a element query key.

**Comment by steverugi** [comment]
Hi @Moult I tried it after update to this morning's but parent.Name does not return a value in the spreadsheet export, kindly advise when you can, thanks

**Comment by Moult** [comment]
Thanks, I messed up and didn't commit everything. Please try again :)

**Comment by steverugi** [comment]
sorry, now it returns the name of the element

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/328ea3ff-fccf-43b7-965b-b923ba206c05)


generates

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/46449330/33c988c6-6dfa-4cfe-a877-017047d76c6a)

..am I doing something wrong?

**Comment by Moult** [comment]
My brain is switched off today clearly

**Comment by steverugi** [comment]
@Moult  now your brain is back, it's woking! 
thank you so much

ciao
