### ISSUE TITLE
Ifctester: Adding PredefinedType to applicability

### ISSUE THREAD

**Issue by sacredshine0** [IfcOpenShell/IfcOpenShell#4757]
Hello everyone,
I have been trying to add predefinedType to applicability in this manner:
`spec.applicability.append(ids.Entity(name="IFCSLAB", predefinedType="BASESLAB"))`
but to no avail. Am I doing it wrong?
Checking an ids like this passes with no applicable entities found. On this screen before validating I get the info for the only Slab in the project to see that it is really there and has predefinedType"BASESLAB".
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/151446156/276eac9f-42a2-46b2-85d0-0f63c62291e6)
Attaching the relevant ifc 
[ifcexample1.8.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15467047/ifcexample1.8.zip)

Would be really glad for any help on this

**Comment by Moult** [comment]
Did you mispell IFCSLAB?

**Comment by Moult** [comment]
I had a look at your model and IfcTester is correct. In IFC, the predefined type cannot be overridden by the occurrence. So if your IfcSlab's predefined type is BASESLAB but the IfcSlabType's predefined type is LANDING, then the IfcSlabType takes priority. See https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Object_Attributes/Object_Predefined_Type/content.html

> If the object is typed by an [IfcTypeObject](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcTypeObject.htm), then the PredefinedType at the [IfcObject](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcObject.htm) occurrence shall only be used if the PredefinedType at [IfcTypeObject](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcTypeObject.htm) is set to NOTDEFINED.

So your data is invalid, the actual predefined type is LANDING.
