### ISSUE TITLE
BCF from IDS

### ISSUE THREAD

**Issue by VitalijTetervov** [IfcOpenShell/IfcOpenShell#4758]
Hi there,

it seems that BCF is not exporting failed entities from the IFC Tester results. 

![bcf 2](https://github.com/IfcOpenShell/IfcOpenShell/assets/47089424/fbcb79a3-896c-486d-8f1d-3fdd3b3a6bf2)
![bcf](https://github.com/IfcOpenShell/IfcOpenShell/assets/47089424/1718a69a-f904-49e5-b16e-eb5fd340dbc1)

**Comment by Andrej730** [comment]
Hi! Can you please try the latest build from Github Releases? Seems like a duplicate of #4640

**Comment by VitalijTetervov** [comment]
Thank you. That worked.
