### ISSUE TITLE
Query on Determining Point Inclusion Within Geometry Elements

### ISSUE THREAD

**Issue by smarnav2904** [IfcOpenShell/IfcOpenShell#4759]
I would like to know if there is a way, using your library, to determine whether a given point in global XYZ coordinates is inside the geometry of any element.

Expected Feature: A function or method that can take XYZ coordinates as input and return a boolean indicating whether the point is inside any geometric element and if possible, know which one.
Use Case: This feature would be particularly useful for spatial queries and collision detection within the application I am currently developing.

**Comment by Andrej730** [comment]
@smarnav2904 python or c++?
https://docs.ifcopenshell.org/ifcopenshell-python/geometry_tree.html#selecting-elements-using-precise-geometry

**Comment by smarnav2904** [comment]
Currently developing in Python, that solves everything for me. Thank you very much.
