### ISSUE TITLE
Object that is not in the Blender-Model is in the .ifc file

### ISSUE THREAD

**Issue by Svel89** [IfcOpenShell/IfcOpenShell#4761]
Hello,  

Blenderbim is still exporting in the .ifc objects that are still not any more in the .blend file. 
I am really not sure how to handle this. I understand that i need to unlink objects in Blenderbim before i delete them,
but if i delete an object in Blenderbim before i did that i have no chance to get it out of my .ifc file. 
![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/cd02af0a-eb1f-47b8-a4a1-9693bb2bfc5a)

So now if i send this file to the architect i am working with he is telling me there is an old object flying around. 
I can see it than i open it with Bimcollab viewer. 

Do i need to save the project to a new file? 
Or is there anything like a refrech .ifc file? 

Here is a screenshot of the situation in Bimcollab. 
(I dont want to show or send the file in detail in an open forum.)
![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/cfc64ad1-9816-48eb-9f7c-128b7257740d)

Best regards 
Sven

**Comment by Moult** [comment]
Don't unlink the object :) and don't use .blend files :)

Unlinking the object is for advanced users or those who no longer need to modify the IFC and are doing some hybrid workflow (e.g. CG viz). It breaks the Blender-IFC connection. You should just load IFCs, delete objects, and save IFCs.

**Comment by Andrej730** [comment]
> I understand that i need to unlink objects in Blenderbim before i delete them,

Why unlinking objects before deleting them? 
It's safe to delete IFC objects with X hotkey (it's overridden by BBIM) or IFC Delete, though using default Blender delete operation with result in unlinking it without removing IFC element.


Unlinking objects from IFC with "Delete IFC Element" unchecked (![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/0e7d54f8-681b-4e1c-bde5-8bec4986733c)) will always lead to some unsafe BBIM behaviour because the object is still present in IFC though not available in the Blender scene and only way to fix it would be to reopen IFC project (not the .blend) or you can use revert IFC project as a shortcut for this. 

Though I think it is generally safe to unlink IFC element with "Delete IFC Element" checked if you want to remove object from IFC but keep it's geometry in current Blender session to something with it.

**Comment by Svel89** [comment]
Hello Moult,
thanks for the answer! I installed the newest version from Blenderbim from Github, uninstalled the old version first and than installed the new version. I explain this because i got an python error than i try to open the file.

![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/db686e57-de7f-42ab-b5db-18a3c0219815)

Do you have an idea how to handle this? 
I think i do a hybrid workflow: I use the model to make a 3D Visualisation of the project with much more models and infos and use the basic mesh ob the project for the objects that are only important in the .ifc.

**Comment by Andrej730** [comment]
> Do you have an idea how to handle this?

@Svel89 It looks like your IFC project is missing IfcProject element. Where this model comes from?

**Comment by Svel89** [comment]
Hello Andrej,

wich shortcut is this revert ifc project? 

I tried shift+E and didn´t find it. 

I am not really sure if i made some problems with my try and error working that destroyed this project :D but if i say safe .ifc it safes the ifc well

![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/1727395f-e884-4793-a068-f625220d0c23)

**Comment by Andrej730** [comment]
> wich shortcut is this revert ifc project?

There is no keyboard shortcut, it's just available option in File menu:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/488a567d-f1de-4bb7-a7e0-aef3ea26e7fe)

**Comment by Svel89** [comment]
hmmmm..... if i press this blender imidiatly goes to an empty file and shows this error: 

![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/4e2b175c-4324-43f8-a25b-151c5712a0e4)

**Comment by Andrej730** [comment]
> hmmmm..... if i press this blender imidiatly goes to an empty file and shows this error:

It's the same error you've shown above - it seems you've removed IfcProject from the file.

**Comment by Svel89** [comment]
hmmm... ok it´s very possible that i made this misstake. 
What can i do to get it back or to delete bim in the project and set it up again?

Than i click x button 
![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/90b3043a-f8e6-4d07-9534-0a7eb80c3678)
create a new project and than save the file i have two projects in the outliner and i am very confused there the objects are stored. 

Maybe i need to watch some more tutorials....

**Comment by Andrej730** [comment]
> What can i do to get it back or to delete bim in the project and set it up again?

It's hard to tell what else could break in the process. Better just start a new project if you can.


> Than i click x button

Why use it? This button basically unloads IFC file from Blender, leaving all objects in Blender session.
You can restart Blender / open new Blender session and create a new IFC project.

**Comment by Svel89** [comment]
Ok i startet a new file and created a new project. 
Now i want to copy the stuff from the existing project in the new file and get allways this message: 
![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/06410f84-add1-4370-941f-a2923753af12)

copy one by one and give it .ifc informations again. 
Do you think this is a working workflow?

**Comment by Andrej730** [comment]
>Now i want to copy the stuff from the existing project in the new file and get allways this message:

Should be fixed after cf9f792a3, try the latest build for github releases.

It should work but not when you'll be copying objects and they will be pasted as just Blender objects and you will need to reassign IFC classes to them.

**Comment by Svel89** [comment]
so i createt a completely new file, made a new .ifc model. 
In the old file i deleted the .ifc information from each object. 
Renamed everything back to the normal names and now i wanted to reassign an IFC Class. 

This is what i want to Assign:

![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/756b41f3-5fea-4087-b157-6939fa761d72)

Now i get this error :(

![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/a1dffbe7-6b90-43c6-817b-654d8b05cdb8)

**Comment by theoryshaw** [comment]
In other words, it's suggested not use the following, unless you're an advanced user.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/a76c34e1-062e-4026-a05c-ce143fae14d3)

**Comment by Svel89** [comment]
I startet Blender completely new -> created a competely new Ifc project -> created a cube -> assigned an ifc class 
it worked! :)

i copied one of the files that were in a not working .blend ifc wrong saved etc. file into this file... 

i get this error: 
![334828450-ef130d05-81f0-4e74-8b19-0f9b4ae3af97](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/e16c8ac6-ab46-4057-b83d-bf1fa1083a9d)

**Comment by Andrej730** [comment]
I assume you're trying to start a new IFC project in the broken .blend file. I think It will be easier to just consider this .blend file corrupted and that it shouldn't be used for starting new IFC projects.

The way you it can work:
1) Open corrupted .blend file in 1 blender session
2) Open 2nd Blender session and start new IFC project
3) Copy object from session 1 to session 2. By copying I mean Ctrl-C and Ctrl-V, not appending them or anything else.
4) Assign a class to the object.

**Comment by Svel89** [comment]
[File with working and not working object1.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15486695/File.with.working.and.not.working.object1.zip)

I am very sure i did exactly what you said. 
The .blend file is attached. 
If you create a new .ifc project copy the object on the right in it you can try it yourself....
Would be intresting if you find a way to make it work. I will send the architect an .fbx this is ok for him he said. 
It looks like i need to redraw everything in blender to create an .ifc file and this is too much effort.

![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/23142880/e8f57c8a-0e91-43ac-aad1-6e88bde2f79d)

**Comment by theoryshaw** [comment]
The file wasn't totally purged, from the ifc connection.  Here's how to fully purge it...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/bbe59d4d-c2c7-447e-81d5-60ab98ccf51c

**Comment by Andrej730** [comment]
> The file wasn't totally purged, from the ifc connection. Here's how to fully purge it...

I think it should have worked without it too, since when you paste an object to Blender, BBIM should ensure that object is unlinked from IFC as it will be unsafe keeping old IFC connections in the new IFC project.

**Comment by Gorgious56** [comment]
I had this error happen because of a material that was previously defined in an ifc file. Remove the material from your object if it has one, it should fix the error. Hopefully

**Comment by Svel89** [comment]
Hello, 
thank you all for all your help :) 
Now it is working again
