### ISSUE TITLE
 Using the “void” tool to covering instances.

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4762]
```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.0.240528
last_actions: 
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
# operator: BIM_OT_add_opening
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcOpeningElement", "predefined_type": "OPENING", "name": "Opening"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 18203, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[-7.434687177010346e-06, 1.0, 0.0, 1.1359548568725586], [-1.0, -7.434687177010346e-06, 0.0, -2.009199619293213], [0.0, 0.0, 1.0, 0.3400000035762787], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "True"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 18203, "Name": "Opening"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\void\operator.py", line 66, in _execute
    FilledOpeningGenerator().generate(obj2, obj1, target=obj2.matrix_world.translation)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\model\opening.py", line 154, in generate
    representation = self.generate_opening_from_filling(
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\model\opening.py", line 341, in generate_opening_from_filling
    shape_builder.rectangle(size=opening_size),
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\shape_builder.py", line 214, in rectangle
    return self.polyline(self.get_rectangle_coords(size, position), closed=True)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\shape_builder.py", line 193, in get_rectangle_coords
    position + size * id_matrix[non_empty_coords[0]],
IndexError: list index out of range

ifc: HFCC-Chrech Toilet.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240528-80c4c13
```
![Skermskoot (109)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/0ff75e60-fd74-4d79-8c17-efdc57833946)
[HFCC-Chrech Toilet.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15483194/HFCC-Chrech.Toilet.txt)

I have model a 25mm plaster as an IfcCovering-Cladding, then I used the void from the door opening in the wall to create an opening in the plaster, this works to create the opening in the IfcCovering-Cladding element but when I save my IFC file the opening in the wall is lost. 
I then tried to create a void in the IfcCovering-clading by selecting both the wall and ifcCovering (25mm plaster) and applied the void but then I got this error message.
The reason why I am not creating a wall type which includes plaster as a layer is that I want to manage this element separately (not same resource and time), paint will be the next element to be added.
Please find attached my IFC file as txt attached.
Thanks for your effort.

**Comment by Ave-5D** [comment]
![prent](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/86a54938-8738-41fb-a4e8-554091a3e048)
[HFCC-Chrech Toilet.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15504353/HFCC-Chrech.Toilet.txt)

Thanks it kind of worked, as you can see in the attached screen shot, the door also got removed but it came back when I saved and re-opened the file. My problem now is that the option to edit the void is lost so now a section of my floor is missing.
I am sure this is not a bug but my lack of experiance.

Thanks in advance.

**Comment by theoryshaw** [comment]
select the aggregate first, then the 'eye'. 


https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/928ed053-b4e3-4406-a55e-94843470917c

**Comment by theoryshaw** [comment]
One caveat, however, is that you'll run into problems if the window/doors are in the same aggregate the void is applied to.  Conceptually it's voiding itself. 
To fix move the window/door out of the aggregate that the void is applied to.

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f308cf7a-7f2a-4b46-8cef-9b891e6cf001
