### ISSUE TITLE
Error activating Stable / Unstable  Add-on in Blender 4.1.1 on Manjaro 24.0

### ISSUE THREAD

**Issue by Projekt-43** [IfcOpenShell/IfcOpenShell#4768]
I am getting the following error while activating the stable version `blenderbim-240402-py311-linux.zip` on a clean environment:

```python
Traceback (most recent call last):
  File "/usr/share/blender/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/__init__.py", line 41, in <module>
    import blenderbim.bim
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/tool/__init__.py", line 30, in <module>
    from blenderbim.tool.document import Document
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/tool/document.py", line 23, in <module>
    from blenderbim.bim import import_ifc
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 42, in <module>
    from blenderbim.bim.module.drawing.prop import ANNOTATION_TYPES_DATA
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/module/drawing/__init__.py", line 20, in <module>
    from . import ui, prop, operator, handler, gizmos, workspace
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/module/drawing/ui.py", line 31, in <module>
    from blenderbim.bim.module.drawing.prop import ANNOTATION_TYPES_DATA
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/module/drawing/prop.py", line 27, in <module>
    import blenderbim.bim.module.drawing.decoration as decoration
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/module/drawing/decoration.py", line 25, in <module>
    import shapely
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/shapely/__init__.py", line 1, in <module>
    from shapely.lib import GEOSException  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'shapely.lib'
```

The Unstable version `blenderbim-240530-py311-linux.zip` activates without error on clean environment but I get a Fatal Error short after, like when deleting the base cube, with the following message:

``` python
os: Linux
os_version: #1 SMP PREEMPT_DYNAMIC Mon May 27 03:56:18 UTC 2024
python_version: 3.12.3
architecture: ('64bit', 'ELF')
machine: x86_64
processor: 
blender_version: 4.1.1
blenderbim_version: 0.0.240530
last_actions: 
last_error: Traceback (most recent call last):
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/__init__.py", line 96, in <module>
    import blenderbim.bim
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/tool/__init__.py", line 30, in <module>
    from blenderbim.tool.document import Document
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/tool/document.py", line 23, in <module>
    from blenderbim.bim import import_ifc
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/bim/import_ifc.py", line 38, in <module>
    import ifcopenshell.util.shape
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/util/shape.py", line 19, in <module>
    import shapely
  File "/home/projekt-43/.config/blender/4.1/scripts/addons/blenderbim/libs/site/packages/shapely/__init__.py", line 1, in <module>
    from shapely.lib import GEOSException  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'shapely.lib'
```

I believe my issue is that BlenderBIM is NOT yet compatible with `python 3.12`. If that's correct, when is `python 3.12` support expected to go out of the pipelines?

Otherwise what would be my best options to get a working BlenderBIM while avoiding managing several `python` versions?

Thanks already!

**Comment by Moult** [comment]
The error message looks suspicious, it should fail earlier than that talking about incompatibilities between IfcOpenShell and Python 3.12 if you are truly on Python 3.12 (note that if you have downloaded Blender from Blender.org instead of using your package manager's Blender, then it should be on Python 3.11, since it bundles its own Python).

In any case we now support Python 3.12. This is untested :) Have fun!

**Comment by Projekt-43** [comment]
Wow, you are amazing @Moult ! Thank you for the fast update!

Will test it as soon as it passes the build :)

**Comment by Moult** [comment]
Sorry for giving false hope I have no idea why I closed this. There are quite a few more things to check.

**Comment by Andrej730** [comment]
Just curious, why use Python 3.12 for Blender? 
I'm not sure if Blender itself is completely Python 3.12 compatible.

**Comment by brunopostle** [comment]
> Just curious, why use Python 3.12 for Blender? I'm not sure if Blender itself is completely Python 3.12 compatible.

The blender that ships with fedora has been 3.12 for a while, BlenderBIM (built for 3.12) works fine

**Comment by Moult** [comment]
@brunopostle by any chance do you or someone else package BBIM for Fedora? I think especially after we clean up our act with versioning it would be nice to include install instructions per distro.

**Comment by Moult** [comment]
Builds are now up.

**Comment by Projekt-43** [comment]
Thanks @Moult !! Tested and .. working like a charm :tada: :
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/7765467/f5e558bd-c3fe-4085-b0f7-aee51be3dffc)

> The blender that ships with fedora has been 3.12 for a while, BlenderBIM (built for 3.12) works fine
Same goes for Arch / Manjaro packages using usually the system installed `python`.

> I think especially after we clean up our act with versioning it would be nice to include install instructions per distro.
Totally support this. and up to help on the Arch / Manjaro instructions part :)

**Comment by brunopostle** [comment]
> @brunopostle by any chance do you or someone else package BBIM for Fedora? I think especially after we clean up our act with versioning it would be nice to include install instructions per distro.

I do, it's mainly an exercise in ensuring that it is 'packageable'. It is nice having the same IfcOpenShell available both as a system library and in blender. It is also really easy to install and user updates are automatic: https://copr.fedorainfracloud.org/coprs/bpostle/IfcOpenShell/

Though I'm currently pushing the builds out manually, I need to automate it nightly.

I'm a full fedora packager, so I could introduce this as a base package, but everything BlenderBIM is moving so fast, I don't think users would be served well by the time lag. I think a goal for an eventual 'stable' release would be to have something that distributions would want to provide. At the moment the bimonthly releases are more of a stocktaking and stabilising exercise than something you actually want users to use.

Not everything about the Hugin project is great, but switching from meaningless release numbers (we were on 0.8.0) to date based numbering (2024.0.0, 2024.2.0 etc.. with odd numbers for unstable snapshots, 2024.1.0 etc..) works really well, users know exactly where they are.

**Comment by Moult** [comment]
Actually @aothms and I were discussing for this to be the last 0.0.YYMMDD release for BBIM. Going forward, the next release for everything, not just BBIM, but for IOS-Python (across all channels, incl. PyPI, Conda, Docker, etc), IfcClash, IfcDiff, etc will all share the same version number of 0.8.0, and then we will continue having a release schedule of ~every 2 months where we increment the number to 0.8.1, 0.8.2, etc.

It's not "meaningful", but at least it's better than absolutely no release number at all, and at least we sync across distribution channels unlike right now where each channel has its own rhythm.

But yes, it would continue to be a stocktaking exercise. For BBIM, we'd still recommend the unstable branch ... but that said, for IfcOpenShell, I'd say a 2-month window is "stable enough" for most users.

Thoughts?

**Comment by brunopostle** [comment]
A detail we found useful is to have stable releases with even numbers, ie:

Stable releases: 0.8.0, 0.8.2, 0.8.4 etc.. release candidates obviously also have even numbers.

At all other times the main branch has odd number version strings: 0.8.1, 0.8.3 etc.. so a snapshot always has a higher number than the last stable release, but has a lower number than the next stable release.

The daily snapshot can have a date appended and it won't screw up version resolution code: 0.8.1_20240930.etc..

**Comment by Moult** [comment]
Agreed that daily builds can still have the date appended :)

I'd love to follow the odd-even convention but I feel as though at least for BBIM everything is always equally stable/unstable :) and hard to line up with version releases.

**Comment by brunopostle** [comment]
The even/odd thing isn't so much about stable/unstable, it is saying "here is a 'release', go package and share it", and being able to distinguish one of these from a random snapshot. This is more relevant to IfcOpenShell than BlenderBIM, since having BlenderBIM in Linux distributions or Microsoft Store would just cause trouble at this point.

A medium term goal could be that BlenderBIM snapshots only use the most recent bimonthly IfcOpenShell 'release' - this wouldn't preclude pushing out an intermediate release if necessary.

**Comment by Andrej730** [comment]
Even-odd thing sounds nice since you'll be able to tell the release version from a random snapshot by a glance but appending a date seems to have the similar benefit, e.g. release is "0.8.1" and any other snapshot will be "0.8.1.xxxxxx".

**Comment by brunopostle** [comment]
> Even-odd thing sounds nice since you'll be able to tell the release version from a random snapshot by a glance but appending a date seems to have the similar benefit, e.g. release is "0.8.1" and any other snapshot will be "0.8.1.xxxxxx".

That will work ok as long as the version is only incremented at release time. 0.8.1.20241230 will generally appear to be newer than 0.8.1 to dependency resolvers in automatic package updates etc..
