### ISSUE TITLE
expand/contract all the material categories at one time. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4771]
Would be nice to have a way to expand/contract all the material categories at one time. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/2968e8bb-7a18-4590-9397-3e1075a73baf)

**Comment by manuvarkey** [comment]
Works just fine. Just one minor detail. The description is shown repeated.
![WhatsApp Image 2024-06-01 at 11 09 43 AM](https://github.com/IfcOpenShell/IfcOpenShell/assets/4415312/47772716-5c4b-4287-abd8-cefe34133b16)
![WhatsApp Image 2024-06-01 at 11 09 41 AM](https://github.com/IfcOpenShell/IfcOpenShell/assets/4415312/59a8455f-3062-40de-970a-494c284fa33b)

**Comment by theoryshaw** [comment]
This one doesn't seem to work for me anymore.
