### ISSUE TITLE
Error when trying to change a material name

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4773]
Get the following error when trying to change a material name

file: https://hub.openingdesign.com/OpeningDesign/2917_International_Ln/src/commit/a34fb916dc5c023c6fd6257322800fa7a2dfa25d/Open/Models/BlenderBIM/2917_International_Ln.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/73c3d953-d0b8-48bc-8b0d-a52080b5f2c3

**Comment by Moult** [comment]
Wow, this was a pretty fundamental bug. This emphasizes why it was a bad decision to try to map Blender materials to _both_ IFC materials and IFC styles. In the future, this type of complexity will be reduced when we make the switch to Blender Material = IFC style only.
