### ISSUE TITLE
[IfcTester] - reporter.Json and <xs:restriction> values in requirements.

### ISSUE THREAD

**Issue by Zdeniso** [IfcOpenShell/IfcOpenShell#4775]
Hi !
After couple of tests with ifctester trying exports results from ids/ifc validation in JSON format, it seems like reporter.Json encounter some difficulties to read or write xs:restriction values in requirements element.

The writting process just stop at the first encounter.

However, xs:restriction values seem to be fine in applicability and ids:simpleValue are just fine too.

<img width="742" alt="image" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/82089944/fdcf214d-7bd4-4ac7-8d98-ee1eeaf26624">

With the debugguer it says : TypeError: Object of type Restriction is not JSON serializable

Here some file if anyone wanna test it :
IDS : [DP_IDS_Dictionnary2 - Copie.txt](https://github.com/user-attachments/files/15510388/DP_IDS_Dictionnary2.-.Copie.txt)
IFC : [MAQ_DEMO_01 - Copie.txt](https://github.com/user-attachments/files/15510394/MAQ_DEMO_01.-.Copie.txt)
JSON_Reporter : [DP_JSON_Reporter.txt](https://github.com/user-attachments/files/15513041/DP_JSON_Reporter.txt)

Have a great day

**Comment by Zdeniso** [comment]
After some deep work, it seems like dictionnary dataType can't be reported. (I'm a beginner in Python, i'm not used to debug)
To bypass the problem i just forced the value as string type so dictionnary could at least be exported.
I'm sure this is not a great answer but it works :)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/82089944/c86f5e63-045e-4422-ad3e-3dfa720f3cb8)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/82089944/db79caa3-1d22-4709-b78f-541002aecbac)

**Comment by Moult** [comment]
Fixed in 7ac117c
