### ISSUE TITLE
Regression: Failed to process face boundary loop on walls (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#478]
1. Convert [478--walls-missing-subtractions.ifc](https://github.com/IfcOpenShell/files/blob/master/478--walls-missing-subtractions.ifc) with 3102a1c17942c28646acfb62b132954c876ddb96
2. Experience that only some of the openings are applied:
<img width="300" alt="screen shot 2018-09-25 at 15 05 48" src="https://user-images.githubusercontent.com/4601554/46016344-d1303f80-c0d4-11e8-88c9-14bd8eb999d8.png">

```
[Warning] {d} 1 edges removed for:
#13561=IfcPolyLoop((#2205,#295,#2218,#294,#2982,#2203,#2219,#2220))
[Warning] {d} 1 edges removed for:
#10182=IfcPolyLoop((#309,#294,#2218))
[Error] {d} Not enough edges for:
#10182=IfcPolyLoop((#309,#294,#2218))
[Error] {d} Failed to process face boundary loop
#10182=IfcPolyLoop((#309,#294,#2218))
[Warning] {d} Failed to convert face:
#2072=IfcFace((#6469))
[Warning] {d} 1 edges removed for:
#10190=IfcPolyLoop((#295,#309,#2218))
[Error] {d} Not enough edges for:
#10190=IfcPolyLoop((#295,#309,#2218))
[Error] {d} Failed to process face boundary loop
#10190=IfcPolyLoop((#295,#309,#2218))
[Warning] {d} Failed to convert face:
#2081=IfcFace((#6478))
[Error] {d} Opening subtraction failed:
#48=IfcWallStandardCase('d',#1,'',$,'',#2184,#9925,'')
[Error] {d} basic_string::substr: __pos (which is 2) > this->size() (which is 1)
[Error] {e} basic_string::substr: __pos (which is 2) > this->size() (which is 1)
[Warning] {f} Subtraction yields unchanged volume:
#9880=IfcBooleanClippingResult(.DIFFERENCE.,#10013,#10016)
[Warning] {f} Subtraction yields unchanged volume:
#3136=IfcBooleanClippingResult(.DIFFERENCE.,#9880,#10017)
[Error] {f} basic_string::substr: __pos (which is 2) > this->size() (which is 1)
[Error] {g} basic_string::substr: __pos (which is 2) > this->size() (which is 1)
```
3. Experience that more (but not all) of the openings are applied when converting from 6c1ad47:
<img width="300" alt="screen shot 2018-09-25 at 15 29 56" src="https://user-images.githubusercontent.com/4601554/46019260-f4122200-c0db-11e8-9672-9ca1b34db2e2.png">
4. Expected geometry from SimpleBIM and Solibri:
<img width="300" alt="screen shot 2018-09-25 at 15 59 57" src="https://user-images.githubusercontent.com/4601554/46019306-1310b400-c0dc-11e8-8463-e8b6c26ffe0a.png">

**Comment by aothms** [comment]
Not sure if you realized, but besides the obvious rectangular openings there are a whole bunch of detailed meshes being subtracted as opening elements, these are the trouble makers here.

![openings](https://user-images.githubusercontent.com/1096535/48939619-1a561180-ef15-11e8-8fbe-36939e241f87.png)

I now process the openings in increasing order of complexity. There's two benefits to this: You get partial results. You can tailor the precision/fuzziness parameters better to the individual operands. Unfortunately that second benefit didn't pay off here. These meshes have detail in the same order of magnitude as the modelling precision of the file. That doesn't work well, but at least these people can look out of the window now. Leaving the issue open.

![wall](https://user-images.githubusercontent.com/1096535/48939839-dd3e4f00-ef15-11e8-9432-8e470008ce44.png)

**Comment by johanrd** [comment]
Ah, clever! Makes sense to prioritise openings by complexity, as long as modeling practices and maturity varies as much as it does.

I can verify that this works as intended. Thanks!

**Comment by aothms** [comment]
With the small fixes in https://github.com/IfcOpenShell/IfcOpenShell/commit/4936ea3ac3ad977b3e3999d937856ef1ca256ce4 the smaller openings process correctly as well now. On the v0.6.0 branch at least.

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)
