### ISSUE TITLE
Doesn't seem like `...drawings\assets\schedule.css` overrides `...Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\data\assets\schedule.css`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4780]
I could be wrong but it doesn't seem like `...drawings\assets\schedule.css` overrides `...Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\data\assets\schedule.css`

**Comment by Moult** [comment]
It doesn't. The CSS needs to be alongside your schedule file. This is documented currently in schedule.css:

```
/**
 * You may copy this `schedule.css` template alongside your input schedule
 * document with the same filename. For example if you have a schedule called
 * `door_types.ods`, you can create a `door_types.css` in the same folder to
 * style that schedule.
 */
```

**Comment by theoryshaw** [comment]
Is there a way, to have one schedule.css apply css to multiple schedules?  
Would be a lot of administrative overhead to have a different .css file per each schedule.
