### ISSUE TITLE
Whole-parts relationship for IfcSolarDevice should be able to be defined in BB

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#4787]
I have tried to bring an IfcSolarDevice into a whole-parts relationship with another SolarDevice via Aggregates. Unfortunately this fails with the following error.

```
os: Darwin
os_version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
python_version: 3.11.7
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 4.1.0
blenderbim_version: 0.0.240526
last_actions: 
# operator: BIM_OT_save_project
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 30, "Name": "My Site"}], "relating_object": {"cast_type": "entity_instance", "value": 1, "Name": "My Project"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 36, "Name": "My Building"}], "relating_object": {"cast_type": "entity_instance", "value": 30, "Name": "My Site"}}
# ifcopenshell.api: aggregate.assign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}], "relating_object": {"cast_type": "entity_instance", "value": 36, "Name": "My Building"}}
# ifcopenshell.api: spatial.assign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 66, "Name": "Cube"}], "relating_structure": {"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}}
# ifcopenshell.api: spatial.assign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 91, "Name": "Cube"}], "relating_structure": {"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 91, "Name": "Cube"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 3.2077476978302], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 91, "Name": "Cube"}}
# operator: BIM_OT_enable_editing_aggregate
# operator: BIM_OT_aggregate_assign_object
last_error: Traceback (most recent call last):
  File "/Users/kuba/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kuba/Library/Application Support/Blender/4.1/scripts/addons/blenderbim/bim/module/aggregate/operator.py", line 51, in _execute
    assembly = element.Decomposes[0].RelatingObject
               ~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range

ifc: AggrSolarDevice.ifc
schema: IFC4
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240526-9ec8035
```

[AggrSolarDevice.ifc.txt](https://github.com/user-attachments/files/15522253/AggrSolarDevice.ifc.txt)

![Screenshot 2024-06-01](https://github.com/IfcOpenShell/IfcOpenShell/assets/1941141/37987ca0-5d7d-4219-bbc6-de21950e6859)

**Comment by kurb70** [comment]
BTW An error also occurs in v0.0.240602-47704b1.

<img width="545" alt="Screenshot 2024-06-02" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/1941141/2260853f-5fdc-470b-b015-e408ccdba139">

**Comment by Moult** [comment]
The error is correct, but this latest update should make it clearer: you cannot aggregate to a parent which has a body representation. The parent should not have any body, only the children parts can have a body.

**Comment by kurb70** [comment]
Thank you very much. Sounds very logical. :)

But when I remove the geometry, the blender cube is automatically reinserted. How can I remove the geometry so that it is not reinserted?

**Comment by Moult** [comment]
@kurb70 sorry, I don't understand. I can remove the geometry without issues. What are you doing?

**Comment by kurb70** [comment]
@Moult I made a little screencast


https://github.com/IfcOpenShell/IfcOpenShell/assets/1941141/f2a68304-b077-4aeb-a5b1-ded4125e4890

**Comment by Moult** [comment]
Ah ok, so firstly never manually toggle edit mode from that drop down. That's Blender's edit mode (which we cannot remove). IFC's edit mode is on the top right, or just hit the Tab hotkey (which will intelligently choose either IFC edit if it is an IFC element).

Secondly, you're attempting to create a zero vertex mesh, which is invalid, which why it reverts back to its previous incarnation (i.e. back to a cube). If you truly want to remove the representation, in the Geometry and Representations tab, see the Model / Body / MODEL_VIEW representation and click the X.

**Comment by kurb70** [comment]
Thank you so much for this explanation, it helped. I was able to build the whole-part relationship :)
