### ISSUE TITLE
Can't `bim.assign_container` any IfcSpaces

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4791]
I can't `bim.assign_container` any IfcSpaces in this file. 
It works, however, if i drag and drop IfcSpaces into another spatial container. 

file: https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/49333953b90f32634c8697bb9b76a3730860c18a/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/bf0827db-c7ea-4d9c-ab0b-1fe64ad66714

**Comment by Moult** [comment]
Spaces are aggregated to other spatial structures, not contained.
