### ISSUE TITLE
[BlenderBIM] IfcElementAssembly does not want to be under IfcRailwayPart

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#4796]
See video:

https://github.com/IfcOpenShell/IfcOpenShell/assets/110968398/75dc26e1-346f-49b2-b26c-d8d3bb3bfcbe

This is the IFC File:

[Schwelle.ifc.txt](https://github.com/user-attachments/files/15536520/Schwelle.ifc.txt)

**Comment by Moult** [comment]
For now, use the panel I'd say.

I'm counting as a vote towards bypassing the outliner. The complexity and disadvantages are starting to outweigh the initial appeal of using the outliner for the spatial tree.
