### ISSUE TITLE
install issue blenderbim

### ISSUE THREAD

**Issue by MichelBohms** [IfcOpenShell/IfcOpenShell#4801]
when i install belnderbim there is no import-export:Belnderbim as in doc but only system:Blenderbim.
even when enabled:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/22189872/fc215c63-c879-4d79-9709-1e2e852f3594)
there is no new/open ifc....

**Comment by theoryshaw** [comment]
Hi. 
https://github.com/IfcOpenShell/IfcOpenShell/issues/4287
