### ISSUE TITLE
global redirect from `https://blenderbim.org` to `https://docs.blenderbim.org`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4803]
possible to put a global redirect on url links like...

https://blenderbim.org/docs/users/exploring_an_ifc_model.html

to...

https://docs.blenderbim.org/users/exploring_an_ifc_model.html

There's a lost of these links out there in the wild.

**Comment by Andrej730** [comment]
See #4519, so we can't setup a redirect. 
Got another idea - if 404 page customizable we could try to add a new url there.

**Comment by theoryshaw** [comment]
cool.. makes sense!
