### ISSUE TITLE
BlenderBim  0.0.240605 can not load IFC elements, whilst solibri can

### ISSUE THREAD

**Issue by olemariussvendsen** [IfcOpenShell/IfcOpenShell#4809]
I have a interesting bugg. I wanted to load a project file from our client, and run the diff tool. However, when loading the latest file i can only view the geometry in Solibri. BlenderBim seems to only load slabs and IFC Spaces. IFC-file is in the link under the images.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/135004477/bb10a5ab-4e02-4a8e-91dc-0055dd7587d6)

https://wetransfer.com/

**Comment by Moult** [comment]
Did you forget to attach the IFC? Can you try again? or send to dion@thinkmoult.com if private.

**Comment by Moult** [comment]
Seems alright here? Is this something you experienced only with 240605? Potentially just an issue in-between builds?

![2024-06-05-180711_822x429_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/f04ce4ce-e1fc-459c-834c-7a999588fdbc)

**Comment by olemariussvendsen** [comment]
Interesting. Only on this project i have experienced this bug. i am using blender 4.1, and latest python. Are you using blender 4.1 or 4.0 with the outdated python?

**Comment by Moult** [comment]
I'm using Blender 4.1 from blender.org (i.e. Python 3.11). No error messages on your end?

**Comment by olemariussvendsen** [comment]
No i do not get any error. When looking at the system consol log, this is what i get:

Read prefs: "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
System PySide6 not found
System Matplotlib not found
System Kivy not found
Setting library paths
qt.qpa.window: SetProcessDpiAwarenessContext() failed: The operation completed successfully.
Qt's default DPI awareness context is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2. If you know what you are doing, you can overwrite this default using qt.conf (https://doc.qt.io/qt-6/highdpi.html#configuring-windows).
VI-Suite: Using built-in libraries
'docker' is not recognized as an internal or external command,
operable program or batch file.
No psutil: No module named 'psutil'
Warning: brickschema not available.
Failed to load BIMTester. Try disabling other add-ons, in particular Blender-OSM. See bug #1318.
Starting import process :: 0.00
Loading file :: 0.00
Calculate unit scale :: 0.00
Process context filter :: 0.00
Calculate model offset :: 0.00
Predict dense mesh :: 0.04
Set units :: 0.00
Create project :: 0.01
Process element filter :: 0.17
Create collections :: 0.07
Create materials :: 0.00
Create styles :: 0.03
Parsing native elements :: 1.07
Done creating geometry
Create native elements :: 0.00
250 / 4565 (5% created, 7% preprocessed) elements processed in 0.29s ...
500 / 4565 (11% created, 12% preprocessed) elements processed in 0.30s ...
750 / 4565 (16% created, 19% preprocessed) elements processed in 0.26s ...
1000 / 4565 (22% created, 24% preprocessed) elements processed in 0.12s ...
1250 / 4565 (27% created, 32% preprocessed) elements processed in 0.22s ...
1500 / 4565 (33% created, 46% preprocessed) elements processed in 0.29s ...
1750 / 4565 (38% created, 62% preprocessed) elements processed in 0.28s ...
2000 / 4565 (44% created, 71% preprocessed) elements processed in 0.25s ...
2250 / 4565 (49% created, 81% preprocessed) elements processed in 0.27s ...
2500 / 4565 (55% created, 92% preprocessed) elements processed in 0.27s ...
2750 / 4565 (60% created, 99% preprocessed) elements processed in 0.33s ...
3000 / 4565 (66% created, 100% preprocessed) elements processed in 0.18s ...
3250 / 4565 (71% created, 100% preprocessed) elements processed in 0.19s ...
3500 / 4565 (77% created, 100% preprocessed) elements processed in 0.19s ...
3750 / 4565 (82% created, 100% preprocessed) elements processed in 0.20s ...
4000 / 4565 (88% created, 100% preprocessed) elements processed in 0.19s ...
4250 / 4565 (93% created, 100% preprocessed) elements processed in 0.21s ...
Done creating geometry
0 / 101 elements processed ...
Create elements :: 4.80
250 / 683 (37% created, 100% preprocessed) elements processed in 0.42s ...
500 / 683 (73% created, 100% preprocessed) elements processed in 0.26s ...
Done creating geometry
Create annotations :: 1.03
Create grids :: 0.00
250 / 1453 (17% created, 100% preprocessed) elements processed in 0.58s ...
500 / 1453 (34% created, 100% preprocessed) elements processed in 0.22s ...
750 / 1453 (52% created, 100% preprocessed) elements processed in 0.21s ...
1000 / 1453 (69% created, 100% preprocessed) elements processed in 0.24s ...
1250 / 1453 (86% created, 100% preprocessed) elements processed in 0.26s ...
Done creating geometry
0 / 43 elements processed ...
Create spatial elements :: 1.95
Create structural items :: 0.00
Create element types :: 0.68
Place objects in collections :: 0.89
Add project to scene :: 1.35
Setting default context :: 0.12
Setup arrays :: 2.26
Import finished in 15.13 seconds

**Comment by Moult** [comment]
Oh wait now I see what you mean. There are a bunch of spaces very far from origin (which you are looking at), and some very close to origin. I'll investigate.

**Comment by Moult** [comment]
For now, enable advanced mode and change the distance limit to something like 5000 instead of 1000m. Your model is "borderline" :)

**Comment by olemariussvendsen** [comment]
Perfect, thank you. :)
