### ISSUE TITLE
Strange behaviour when importing ifcopenshell and OCC in python 3.10

### ISSUE THREAD

**Issue by romanavyzn** [IfcOpenShell/IfcOpenShell#4810]
Hello!

I'm not sure whether this issue is related to pythonOCC or ifcopenshell, but I'm posting it here just in case:

I noticed some strange behavior in a code snippet when importing ifcopenshell. When I import ifcopenshell after certain imports from OCC, the boolean operation at the end of the code works fine.

```
from OCC.Core import BRep
from OCC.Core import BRepAlgoAPI
from OCC.Core import BRepTools
from OCC.Core import TopoDS
import ifcopenshell
...
fuse = BRepAlgoAPI.BRepAlgoAPI_Fuse(A, B)  # ok
``` 

Yet, if I import ifcopenshell before the OCC imports
```
import ifcopenshell
from OCC.Core import BRep
from OCC.Core import BRepAlgoAPI
from OCC.Core import BRepTools
from OCC.Core import TopoDS
...
fuse = BRepAlgoAPI.BRepAlgoAPI_Fuse(A, B)  # fails
```
This fails with the error: 
libc++abi: terminating due to uncaught exception of type Standard_ConstructionError

**Gist:**
Here is the gist to reconstruct the error:
https://gist.github.com/romanavyzn/1712f9c0427093e8d7d0f495d15085fc

**Screenshot:**
Terminal output running the python files in the gist:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/117177043/68294d51-e9fe-4e79-ba32-82c0ca1d7da3)

**Desktop:**
 - OS: macOS 14.5 (23F79)
 - Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:53:34) [Clang 16.0.6 ] on darwin
 - OCC.Version 7.7.2 ((installed via conda)
 - ifcopenshell Version: 0.7.0.240521 (installed via pip)

**Comment by aothms** [comment]
The ifcopenshell version on pip uses a statically linked in open cascade version (7.5). What you're likely experiencing here is some form of symbol collision that OCCT 7.7 routines jump to 7.5 routines, which can fail due to a variety of reasons.

I hope there is an easy fix by installtion ifcopenshell through conda as well, which should get you the same (dynamically linked) open cascade version. Depending on the phase of the moon installation through conda can be challenging due to dependency conflicts.

**Comment by Moult** [comment]
@aothms can conda be configured to build against 7.5?

**Comment by romanavyzn** [comment]
@aothms , thank you! yes you are right: the problem can be fixed by installing ifcopenshell from conda

**Comment by aothms** [comment]
That's a question for @krande but it could be there is no equivalent
pythonocc or other conflicts (vtk... ) . In general this can be rather
brittle. With this many dependencies the matrix is usually not complete.

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op vr 7 jun 2024 13:15 schreef Dion Moult ***@***.***>:

**Comment by Krande** [comment]
@aothms and @Moult, while it is possible to compile against that version, the conda-forge build matrix for ifcopenshell is already quite large wrt. the current support of OpenCascade compiled with/without VTK enabled against python versions 3.8-3.12 and different OS's (which is in total 50 packages today!). 

We could of course modify the current build matrix by adding limited support (ie. say occt=7.5 and ifcopenshell only for python 3.12 and not all python versions). 

But I think an alternative would be to add support for these types of "special compilations" by adding these to our `ifcopenshell` channel (or make a new one dedicated to compatibility and not conflict with our daily builds). That way if a user wants to use ifcopenshell with older variant of opencascade they can simply do 
`mamba create -n my-ifc-env ifcopenshell pythonocc-ore occt=7.5 -c ifcopenshell -c conda-forge`.

For example if a user wants to use opencascade 7.5, we can have compiled variants of ifcopenshell and pythonocc-core in that channel (and upon request add more related projects).

**Comment by aothms** [comment]
But isn't it also so that a ifcopenshell compiled against 7.5 should be usable with 7.7 assuming OCCT follows reasonable semver which they do. Maybe just set a runtime requirement on `opencascade<8` and build against 7.5. Or am I being super naive again?

**Comment by Krande** [comment]
@aothms, I faintly recall reading about some breaking changes in a past minor or patch version of opencascade forcing the conda-forge package of occt to be pinned down to the exact patch version. Not sure if that is a reoccurring problem, or if it was just a one-time issue though.
