### ISSUE TITLE
blenderbim operations

### ISSUE THREAD

**Issue by robc3po** [IfcOpenShell/IfcOpenShell#4812]
managed to get blenderbim 024402 to work with blender 4.1 and have the latest archipack 2.8 and things looked like they might work, however, it would not save a ifc file.  after going thru that so many times i tried to find another answer.however
blender 4..1 would not allow me to remove that bim version.
i did download the latest at this time, 240602
so
tried to download another version blender 3.6 and 4.2alpha
4,2 would not work instal etc. only about half
3.6 i have but it wont work with blenderbim
and nowhere can i find a way to uninstall blender  but still working on that too
i also tried running as administrator to be able to remove bim 402 from blenderr 4.1 but did not work
i am still pursuing uninstalling,  other than that, probably have to wait till blender comes up with new versions. or some point down the road.  let me know if any ideas pop up on this dead end
thanks rob

**Comment by theoryshaw** [comment]
Screenshoots or videocasts of the steps are helpful too, if possible.

**Comment by theoryshaw** [comment]
Also, what is your operating system? and version?

**Comment by robc3po** [comment]
well not sure about walking thru on that tried to uninstal blender 4.1 from the blender installler for that and then reinstalled it, also thru it in the trash before as well,  but has the same issues on the bim same version haha
not sure if i can get it to work if i turn it on.
i did however try opening the blender 4.0 and it has the 602 version of bim oddly enough. however even tho the rest seems to be working the bim does not.
also have the the rest of the files arkpak 2.8

will explore this 4.1 again.  basically it would seem to be operational however if i tried to save as ifc file there was nothing on my directory.  now i could save  a blender format,   but not an ifc format
operating sys window 11  puter acer predatotrinton 300se

have 4.0 blender open at the moment will look around a bit then try that 4..1 versaion again

**Comment by theoryshaw** [comment]
see common issue `#1`: https://docs.blenderbim.org/users/troubleshooting.html#common-issues

might help.

**Comment by robc3po** [comment]
well unable to even open 4.1 anymore and the errors it gives i cant copy

uninstalled 4.1 from windows uninstal   and then reinstalled from original download, even tz the trash yet there it is the 402 blenderbim still there wont open wont let me delete it
even installed it on another terribyte drive.
shows its an init script on the main drive
appdata blenderbim init scripts
looking for it

**Comment by theoryshaw** [comment]
Does any of the following troubleshooting measures work for you? 
https://docs.blenderbim.org/users/troubleshooting.html#installation-issues

**Comment by robc3po** [comment]
i give up, cant even type in the directory on this os.   ridiculous,  most cumbersome os ever
the path is.
C::users\Robert Clements\AppData\Roaming\Blender\4.1\scripts\add ons\blenderbim\_init_py
ridiculous
should of been able to delete that in minites, can't even find it with microsofts shell
nuts so unproductive

**Comment by robc3po** [comment]
ill check the docs out in  a minute a bit frustrated at the moment

**Comment by robc3po** [comment]
ok got it done found the roaming files deleted it opened up and installed the latest bim
will check it soon to see if it will save an ifc file

**Comment by robc3po** [comment]
wellm ok it did save a file but none of the stuff i created with archpak 
but at least it saved and loaded an ifc file
now the files i saved as a blender file did come back in with stuff i created with archpak
and 
i also the noticed it did not automatically change the archpak modules to ifc in the organizer window.

but at this point looks like its more about learning how to use this

**Comment by theoryshaw** [comment]
Great, Would also suggest https://community.osarch.org/categories/general for general user questions.

**Comment by robc3po** [comment]
thx will check it out a little more relaxed now
