### ISSUE TITLE
PIP: Stable version

### ISSUE THREAD

**Issue by jgs-fhnw** [IfcOpenShell/IfcOpenShell#4823]
Hello:)

I install IfcOpenShell via pip install. And because i want to be conscious about any changes to the code i install it by using a specific version number. While developing with this library i encountered a problem multiple times. The specified ifcOpenShell version vanished. So when i wanted to install my code in another environment (lets say a docker container) where the specified version was not cached, i was forced to update my version. Maybe thats a good thing in some cases, but in other cases i don't have the resources to do and understand an update. I don't  understand why there is no stable version published on pip additionally to the daily builds. Is there any reason for that. Or how is the workflow intendet to be?

Thanks

**Comment by Moult** [comment]
Unfortunately there is no such thing as a "stable" version really currently. The best we can do is "this is a point in time when we did a release" - it's neither stable nor unstable, it just "this is a point".

That said, in the next couple of months we will switch to a more predictable numbering scheme, e.g. 0.8.0, 0.8.1, 0.8.2, etc released approximately once every two months. There's no "guarantee" of stability either still, but at least there is a version number that is consistent across PyPI and other release channels.

Another issue is that PyPI has a filesize limit and we release lots of versions for lots of platforms so we hit the filesize limit every so often so we have no choice but to purge old releases. I guess we can request a filesize limit increase to PyPI, but when we change from a monthly release to an every-two-months release we'd also get double the time before we need to do a purge (say a purge every year?)

**Comment by jgs-fhnw** [comment]
Ok, that sounds reasonable. Thank you for the information!
