### ISSUE TITLE
BlenderBim 240605 Quantifying all objects "IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed".

### ISSUE THREAD

**Issue by olemariussvendsen** [IfcOpenShell/IfcOpenShell#4826]
Tried to see if the quantity all objects works. the error code "IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed" comes up.

File used:
https://we.tl/t-5pCynly4Gz

**Comment by Moult** [comment]
So sorry, the file transfer has expired, do you remember what file this was named? I might've downloaded it but I forgot the filename. Alternatively can you reupload it?

**Comment by olemariussvendsen** [comment]
Hi, i am trying to invstegate what file it was, appolegiz if i can not find it.

If you have downloaded it, it should have a date stamp such as 20240mdd where the dd is the date and y is the month.

**Comment by olemariussvendsen** [comment]
Found it i belive! Seem to yield the same error. Uploaded a new link

Internal name is Eik (refferance for myself)

https://we.tl/t-8xyWP8TkRO

**Comment by Moult** [comment]
This should now be fixed.

Note that I recommend the IfcOpenShell engine over the Blender engine, although not as comprehensive (yet) it is much, much faster.
