### ISSUE TITLE
Fail to download ifctester from "pip install ifctester"

### ISSUE THREAD

**Issue by Xema-Pastor** [IfcOpenShell/IfcOpenShell#4837]
Hello.

I tried to download ifctester from "pip install ifctester", but, during installation, I got this error:

```
...
Using cached shapely-2.0.4-cp312-cp312-win_amd64.whl (1.4 MB)
Building wheels for collected packages: mathutils
  Building wheel for mathutils (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'mathutils' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mathutils
  Running setup.py clean for mathutils
Failed to build mathutils
ERROR: Could not build wheels for mathutils, which is required to install pyproject.toml-based projects
```

Any idea to solve it? 

Will be a self-extractring file like you've done with ifcopenshell?

Thanks

**Comment by Moult** [comment]
mathutils is currently a mandatory dependency on PyPI. This is probably not a good idea and we should make it an optional dependency.

mathutils doesnj't ship for your platform, which is why it's trying to compile it, but it can't, and so it requires Microsoft Visual C++ 14.0.

**Comment by Moult** [comment]
It's now optional, but in the long term I'd like to swap out mathutils for numpy. I think the way we're using it, they both do the exact same thing, it's probably just out of convenience since Blender comes with mathutils.

**Comment by aothms** [comment]
> but in the long term I'd like to swap out mathutils for numpy

Very much in favour of that (now that Blender ships with numpy they should actually do the same?). This is a very clear project with measurable outcomes, would be a good first project for a new 'hire'.

**Comment by sabinslash** [comment]
It still doesn't work, even though I have MS Visual C++ 15.0.
