### ISSUE TITLE
v0.8.0 install target misses some libraries

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#4842]
I'm running make and make install on linux. These files are built but not installed:

    libgeometry_kernel_cgal.so
    libgeometry_kernel_cgal_simple.so
    libgeometry_kernel_opencascade.so

..otherwise build seems to be ok with opencascade 7.6.3 and 7.8.1, and the arm build now takes two hours instead of eleven!

**Comment by aothms** [comment]
Thanks. Should be fixed now!

> and the arm build now takes two hours instead of eleven

Thanks for posting that. Amidst all this chaos it's nice to hear there is some value to all the refactoring we've been doing.

The main culprit at this point I think is `taxonomy.h` and the schema headers. If we would use precompiled headers / some sqlite like "amalgamation" / brutally reduce complexity of the headers even further. I'm sure we can get the compile times down much more.

**Comment by brunopostle** [comment]
`make install` is ok now.

The 'fedora review' linter is grumbling that these three libraries are unversioned, but I don't think this is very important.
