### ISSUE TITLE
v0.8.0 python settings.INCLUDE_CURVES

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#4847]
I have some old code that reads a profile:

    profile = ifcopenshell.util.representation.get_representation(
        element_type, "Model", "Profile", "ELEVATION_VIEW"
    )
    settings = ifcopenshell.geom.settings()
    settings.set(settings.INCLUDE_CURVES, True)
    shape = ifcopenshell.geom.create_shape(settings, profile)
    verts = shape.verts
    edges = shape.edges

..but apparently `INCLUDE_CURVES` isn't a thing in v0.8.0:

    File "/usr/lib64/python3.12/site-packages/ifcopenshell/geom/main.py", line 175, in __getattr__
    raise AttributeError("'Settings' object has no attribute '%s'" % k)
    AttributeError: 'Settings' object has no attribute 'INCLUDE_CURVES'

If I comment this out my test suite passes (good), but then I don't get any vertices.

#4832

**Comment by Moult** [comment]
The equivalent in v0.8.0 is:

```
settings.set("dimensionality", ifcopenshell.ifcopenshell_wrapper.CURVES_SURFACES_AND_SOLIDS)
```

**Comment by aothms** [comment]
This is a result on a unification of the settings throughout the codebase. In the user facing settings we had include_curves -surfaces, in the processing logic we had one field for dimensionality 2d, 3d, 2d+3d.
