### ISSUE TITLE
Missing escape apostrophe in string value after saving model to ofstream

### ISSUE THREAD

**Issue by arzezniczak** [IfcOpenShell/IfcOpenShell#485]
I've got a IFC file from Revit. I'm parsing it using IfcOpenShell, then I'm adding some informations to model and later I'm saving modyfied model to ofstream using << operator. I've found that escape apostrophes in string values are missing after saving.

I have this line in Revit IFC file:
`#152= IFCBUILDINGSTOREY('2VB4lMYST0RQttNYiQ0Ab$',#42,'Poziom 0''',$,$,#151,$,'Poziom 0''',.ELEMENT.,63.0000000000003);`
Note 'Poziom 0'''
But after parsing, modyfing and saving this model again I'm getting this file instead:
`#152= IFCBUILDINGSTOREY('2VB4lMYST0RQttNYiQ0Ab$',#42,'Poziom 0'',$,$,#151,$,'Poziom 0'',.ELEMENT.,63.0000000000003);`
Note missing apostrophe in 'Poziom 0'' string. After this you can't parse this file correctly (wrong parameters number exception).

You can simply reproduce it using latest IFCOS version and IfcAdvancedHouse example. Change this line:
`file.getSingle<IfcSchema::IfcProject>()->setName("IfcOpenHouse");`
to this (simply add apostrophe somewhere in string value):
`file.getSingle<IfcSchema::IfcProject>()->setName("Ifc'OpenHouse");`
and as a result after running IfcAdvancedHouse.exe you will got IFC file with line:
`#12=IFCPROJECT('1bv_eeqArDwR4adDFgma1Z',#5,'Ifc''OpenHouse',$,$,$,$,(#207,#218),#11);`
string value with missing escape apostrophe.

**Comment by aothms** [comment]
Hi,

I cannot reproduce this using your IfcAdvancedHouse test. I did as you said on both the master branch and 0.6 branch and got `Ifc''OpenHouse` with double apostrophe in both cases (so does the output you pasted btw, is that a mistake?)

A also tested importing this `#152` building storey instance and writing it back after changing an attribute. Also that maintained the correct escaped apostrophe.

There is this 'human readible' output mode. For example when using python `__repr__`. In which (among other things) entity class names are not uppercased and strings are not encoded. But I don't think that is what's we're talking about here. See illustration below.

~~~
>>> import ifcopenshell
>>> ifcopenshell.version
'0.6.0a0'
>>>
>>> f = ifcopenshell.file()
>>> f.createIfcPerson("O'hara")
#1=IfcPerson('O'hara',$,$,$,$,$,$,$)
>>>
>>> f.write("ohara.ifc")
>>> with open("ohara.ifc") as f:
...   print(f.read())
...
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2018-10-15T10:57:43',(),(),'IfcOpenShell 0.6.0a0','IfcOpenShell 0.6.0a0','');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCPERSON('O''hara',$,$,$,$,$,$,$);
ENDSEC;
END-ISO-10303-21;
~~~

**Comment by arzezniczak** [comment]
Hi,
sorry, this example with IfcAdvancedHouse is indeed wrong, my bad.
Unfortunetly I cannot reproduce it now somehow... Maybe something changed in our application code.
If I will encounter this again I will report back, but for now I'm closing it.
