### ISSUE TITLE
geometry processing and visualization : python

### ISSUE THREAD

**Issue by deliciousteas** [IfcOpenShell/IfcOpenShell#4852]
# Goal
Obtain correct instances' **coordinates and orientation** from an *.ifc file using ifcopenshell.
# Issue1：geometry processing 
**The extracted components have a position offset.** The figure on the left shows the IFC file opened in the BIMvision software, while the picture on the right shows it opened using PythonOCC in the PyCharm environment.
<img width="1023" alt="872c8b5bb574cced04620d35078d637" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/107855849/ba7d1c93-d72b-4c9e-80b1-0ca8f9a558d5">
# To address this, I conducted the following tests:
1. **Experiment** : I tested with two different models and found that both exhibited inaccurate position extraction.So it must be my code problem.
2. **Consideration**:IFCopenShell0.7.0 documentation has a example code about geometry processing, I have noticed the matrix variable here. In my code, I account for the change in floor height by adding it to the component.However, I do not consider the rotation angle. Could this omission be causing the issue? 
##  code example：geometry processing
```
def extract_data(element):
    data_dict = {}
    settings = ifcopenshell.geom.settings()
    element_GlobalId = element.GlobalId
    shape = ifcopenshell.geom.create_shape(settings, element)
    shape_type = str(shape.type)
    matrix = list(shape.transformation.matrix.data)
    faces = list(shape.geometry.faces)
    edges = list(shape.geometry.edges)
    verts = list(shape.geometry.verts)
    location = matrix[-3:]
    new_verts = []
    for x in range(len(verts) // 3):
        new_verts.append(
            [verts[x * 3] + location[0], verts[x * 3 + 1] + location[1], verts[x * 3 + 2] + location[2]])

    data_dict["GlobalId"] = element_GlobalId
    data_dict["shape_type"] = shape_type
    data_dict["verts"] = new_verts
    data_dict["faces"] = faces
    data_dict["edges"] = edges
    return data_dict 
```
# Issue 2：visualization
I noticed that the official ifcopenshell documentation mentions that geometric information extraction will always be a **triangular mesh**. So I extracted the IFC data, saved it as TXT file, and then visualized it in a triangulation network based on PythonOCC. 
<img width="608" alt="image" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/107855849/0d91fee0-1ac1-4f7e-9707-92f8e4454fa4">
However, the visualization does not match the expected view, **as shown in the first figure above**, and the result is unsatisfactory.
So,I would like to know if there is any better visualization method In particular, I need to save the geometric coordinates for the subsequent study of the geometric topological relationship?

## code example： visualization

```
def create_face(vertices, face_indices):
    

    polygon = BRepBuilderAPI_MakePolygon()
    for idx in face_indices:
        vertex = vertices[idx]
        polygon.Add(gp_Pnt(vertex[0], vertex[1], vertex[2]))
    polygon.Close()
    return BRepBuilderAPI_MakeFace(polygon.Wire()).Face()

def create_mesh(vertices, faces):
    
    mesh = TopoDS_Compound()
    builder = BRep_Builder()
    builder.MakeCompound(mesh)
    for face_indices in faces:
        face = create_face(vertices, face_indices)
        builder.Add(mesh, face)
    return mesh
```

**Comment by Moult** [comment]
If you're after a viewer, use https://blenderbim.org/ - it's a fully featured graphical front-end to IfcOpenShell.

You can also write your own code then visualise using Blender. But why recreate the wheel? The code already exists.

You're also not using the iterator. I highly recommend using the iterator.

Alternatively you can serialise to another format (e.g. OBJ, DAE, glTF) and get vertices from that, but not knowing what your purpose is, I'm not sure what to recommend.

If you want to get it programmatically, you're correct to suggest that omiting the rotation of the matrix is causing mistakes. In general, what you're doing is highly inefficient - instead of using instancing, you're applying the matrix transformation to get global coordinates. It works, but is inefficient.

I also highly recommend using the util module.

I also notice you're grouping verts instead of keeping in flat. This may be unnecessary depending on your goals.

So putting this into practice, if you _really_ want global coordinates, try this:

```python
import multiprocessing
import ifcopenshell
import ifcopenshell.geom

ifc_file = ifcopenshell.open('model.ifc')

settings = ifcopenshell.geom.settings()
settings.set(settings.USE_WORLD_COORDS, True)
iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
if iterator.initialize():
    while True:
        shape = iterator.get()
        faces = ifcopenshell.util.shape.get_faces(shape.geometry)
        edges = ifcopenshell.util.shape.get_edges(shape.geometry)
        verts = ifcopenshell.util.shape.get_vertices(shape.geometry)
        # ... write code to process geometry here ...
        if not iterator.next():
            break
```

**Comment by chunibyo-wly** [comment]
`settings.set(settings.USE_WORLD_COORDS, True)` solve the this issue, thanks for the contibuting and help

**Comment by deliciousteas** [comment]
**util module** does well! Thanks for community contribution and help!
