### ISSUE TITLE
External styles don't seem to be working

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4860]
I'm on blenderbim-240605, and external styles don't seem to work. 

files: [20240613 - printing materials.zip](https://github.com/user-attachments/files/15820765/20240613.-.printing.materials.zip)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c8fc29e2-fe1f-408d-abde-e20072093511

**Comment by theoryshaw** [comment]
Upon further investigation, it seems part of the problem is maybe the 'relative path' wasn't working. 

However, there seems to be another issue, that is, the 'full texture' defintion doesn't come through... only the overall color seems to come through....

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b962995d-2d37-4fa9-a444-7d80d32d4499

**Comment by theoryshaw** [comment]
Sorry, my material definitions were wrong.

**Comment by jiangxiaoyuyu** [comment]
Excuse me, I seem to have encountered a similar problem to yours, how should I solve it
