### ISSUE TITLE
Error with not completely initialized swig wrapper (e.g. RecursionError) #4832 

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4861]
@aothms 

I've noticed a really weird error and I couldn't find any way to actually narrow down the case to reproduce it besides opening BBIM and loading creating new project with a demo template:

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/40562965-bd6b-499a-93b3-164678c013b8

After that in the Blender system console appears a wall of ignored exceptions.
```python
Exception ignored in: <function entity_instance.__del__ at 0x00000288876E04A0>
Traceback (most recent call last):
  File "\libs\site\packages\ifcopenshell\entity_instance.py", line 168, in __del__
  File "\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 8582, in <lambda>
  File "\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 71, in _swig_setattr
  File "\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 63, in _swig_setattr_nondynamic
RecursionError: maximum recursion depth exceeded while calling a Python object
Exception ignored in: <function entity_instance.__del__ at 0x00000288876E04A0>
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
RecursionError: maximum recursion depth exceeded while calling a Python object
Exception ignored in: <function entity_instance.__del__ at 0x00000288876E04A0>
```

Since exceptions are ignored and `__del__` involved I assume it's something happens when garbage collector is removing some entities. Couldn't attach any breakpoints to `__del__` as they are ignored during garbage collection but adding bunch of print statements suggested that `_swig_setattr` and `_swig_setattr_nondynamic` were never called actually 🤔🤔

Narrowing down to where this errors actually start to occur I've found that it happens when it's trying to initialize one of the `geom.settings`.

In ifcopenshell_wrapper when it's initializing `Settings` it's trying to access setting's attribute `this` in `self.this.append(this)`.
```python
class Settings(_object):
    """Proxy of C++ ifcopenshell::geometry::Settings class."""

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Settings, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Settings, name)
    __repr__ = _swig_repr

    def setting_names(self):
        """setting_names(Settings self) -> StringVector"""
        return _ifcopenshell_wrapper.Settings_setting_names(self)

    def __init__(self):
        """__init__(ifcopenshell::geometry::Settings self) -> Settings"""
        this = _ifcopenshell_wrapper.new_Settings()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
```

And since we override `__getattr__` in `settings_mixin` 

https://github.com/IfcOpenShell/IfcOpenShell/blob/9d7ef6ff471b2d3fee9b50df21f27c1d630b6706/src/ifcopenshell-python/ifcopenshell/geom/main.py#L171-L175

it's accidentally calling `_ifcopenshell_wrapper.Settings_setting_names` when settings are not yet initialized (`this` is not yet set) and `Settings_setting_names` then tries to get attr `this` in `SWIG_Python_GetSwigThis` to continue, and we're back to `__getattr__` -> `setting_names` -> `super().setting_names` and it should go infinitely but it seems to break at some point without any errors. No idea why, `Settings.__init__` just finishes though it never gets to any error - I assume it should have got to RecursionError but it doesn't, maybe it's some bug in swig. 

Maybe this weird recursion with swig is producing an UB somehow and later one of those attempts to initialize therefore garbage collection breaks something even more - therefore this werid garbage collector traceback unrelated to the actual issue 🤔

I've found a fix that seems to work - 99338187d. Any ideas if I got it right and where this issue also can occur? I've checked other classes that inherit from wrapper's classes - iterator, tree, we don't override `__getattr__` there, so it shouldn't be an issue.

**Comment by aothms** [comment]
> I've found a fix that seems to work - https://github.com/IfcOpenShell/IfcOpenShell/commit/99338187de1565521612481255342dc412794274

Honestly, I have nothing to add.. It's indeed a bit of a messy circular dependency loop that is being created that you have been able to resolve one way or another 👍

**Comment by Moult** [comment]
Close?
