### ISSUE TITLE
Where to find examples of creating building and individual elements (doors, windows, etc.)?

### ISSUE THREAD

**Issue by meugeny** [IfcOpenShell/IfcOpenShell#4863]
Hello, I’m new to working with the ifсopenshell library, I’m faced with the task of creating a script for creating a building with the necessary parameters.
Unfortunately, in the documentation and on other sites I did not find examples of creating individual elements in a library on Python; there are only examples of creating a wall.
Where can I get examples of creating windows, doors, roofs, etc.? Or entire buildings.

**Comment by Moult** [comment]
- https://docs.ifcopenshell.org/ifcopenshell-python/code_examples.html#create-a-simple-model-from-scratch
 - https://docs.ifcopenshell.org/ifcopenshell-python/geometry_creation.html#custom-representations
 - https://docs.ifcopenshell.org/ifcopenshell-python/geometry_creation.html#custom-representations
 - https://docs.ifcopenshell.org/ifcopenshell-python/geometry_creation.html#wall-representations
 - https://docs.ifcopenshell.org/ifcopenshell-python/geometry_creation.html#profile-representations

**Comment by theoryshaw** [comment]
and maybe?
https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.8.0/src/blenderbim/scripts

**Comment by Moult** [comment]
Also see https://docs.ifcopenshell.org/autoapi/ifcopenshell/api/geometry/index.html - it's unfortunately not documented but you can see the function signatures and make a good guess :)

It includes doors, windows, railings, wall from 2 points, slabs, and general profiles (columns, beams, etc).

**Comment by meugeny** [comment]
Thank you for answering, very useful links :)
