### ISSUE TITLE
BlenderBIM Default UI?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4872]
Hey @Moult,

I want to set up my BlenderBIM startup user interface to look like this from the get-go:

![Untitled design](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/c7c4f35a-8cde-418e-9d84-c2f10434fc0b)

The reason why I cannot right you, is because the Object Information tab is grayed out before loading or creating a project.

Why not enable it and have it empty like it is when you create a new IFC project?

It is a natural way, and a habit I would guess for more of us, to have a window that will show the information of the selected object/s.

Let's not even mention that it will make Revit users to feel more like home.

Anyway, even if you don't like it as default startup UI for everyone, I would love to have that OI tab enabled, so I can use it myself.

Thank you in advance for considering this :)

**Comment by Tudjack** [comment]
Well.. you can save any UI in Blender to default startup configuration. File -> Defaults -> Save Startup File

**Comment by Andrej730** [comment]
I think showing all the BlenderBIM sections when project is not loaded may distract the users. Even the available "Project Overview" is incomplete until project loaded and not all sections are available.

You can start an empty project, setup startup file as you wish, then unload the project and remove all collections and objects you don't need in the startup file.

> It is a natural way, and a habit I would guess for more of us, to have a window that will show the information of the selected object/s.

If IFC project is not loaded therefore user is working with just Blender objects and Blender has it's own Object properties for this.

**Comment by BIMvoice** [comment]
> I think showing all the BlenderBIM sections when project is not loaded may distract the users. Even the available "Project Overview" is incomplete until project loaded and not all sections are available.
> 
> You can start an empty project, setup startup file as you wish, then unload the project and remove all collections and objects you don't need in the startup file.
> 
> > It is a natural way, and a habit I would guess for more of us, to have a window that will show the information of the selected object/s.
> 
> If IFC project is not loaded therefore user is working with just Blender objects and Blender has it's own Object properties for this.

Hi Andrej, thank you for your feedback. I'll try to see how your proposed solution works.

**Comment by BIMvoice** [comment]
For now, I decided to use this layout. Thanks for the feedback.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/c88a5bcf-2130-41be-ad0a-d4da509945eb)
