### ISSUE TITLE
Issue with Missing "Screencast Keys, BlenderBIM, BIM Documentation" Panel

### ISSUE THREAD

**Issue by Elen2024** [IfcOpenShell/IfcOpenShell#4873]
Hi!

I have installed the BlenderBIM add-on but the "Screencast Keys, BlenderBIM, BIM documentation" panel does not appear. The panel should be located on the right side of the screen. I have attached a screenshot for reference. Additionally, I am working on a Mac.

Do you know what the problem might be? Thank you in advance!

<img width="1506" alt="Screenshot 2024-06-14 at 12 27 48 PM" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/172769141/691f7dfa-788e-442d-9a5a-4288f1d06eea">

**Comment by Moult** [comment]
I think you're just looking at an outdated screenshot. Also the screen cast keys is a separate Add-on.

**Comment by Elen2024** [comment]
Hi!

Thank you for the quick response.

To clarify, I'm currently using the latest version of Blender and the BlenderBIM add-on. The screenshot I sent you is not outdated, I recorded my screen a few minutes ago. 

Additionally, I understand that "Screencast Keys" is a separate add-on. Could you also provide instructions on how to find the correct link for the installation?  Is this one correct? https://github.com/nutti/Screencast-Keys/releases

Thank you again for your assistance!

Best regards,
Eleni

**Comment by Andrej730** [comment]
@Elen2024 

Basically everything from N-panel in the current version was moved to the scene properties BlenderBIM tabs.
E.g. operators from "BIM Documentation" were moved to the "Drawings and Documents" tab in the scene properties and also to the Annotation Tool (in the tool box on the left).

Don't remember what was in the "BlenderBIM" but it's in one of the tabs too (there is also a search located at the top of the properties section).


> Additionally, I understand that "Screencast Keys" is a separate add-on. Could you also provide instructions on how to find the correct link for the installation? Is this one correct? [nutti/Screencast-Keys/releases](https://github.com/nutti/Screencast-Keys/releases)

That should work, see [readme](https://github.com/nutti/Screencast-Keys?tab=readme-ov-file) for any installation details.

**Comment by Elen2024** [comment]
Your guidance was really helpful. 

Thanks again!
