### ISSUE TITLE
Refactoring Suggestion: Project Info Panel Modes

### ISSUE THREAD

**Issue by Vanuan** [IfcOpenShell/IfcOpenShell#4876]
I've been [documenting](https://github.com/IfcOpenShell/IfcOpenShell/pull/4875) and reviewing the code for the Project Info panel and noticed that there are different modes or states that the panel can be in, based on the project loading state. I think it would be beneficial to refactor the code to make these states more explicit and easier to understand.

Currently, the [`BIM_PT_project`](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7d80e6f1c7d1cf34c4d0a14ced7cadb03b8bbf/src/blenderbim/blenderbim/bim/module/project/ui.py#L89-L103) class, which represents the "Current Project" panel (a child of the [Project Info panel](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7d80e6f1c7d1cf34c4d0a14ced7cadb03b8bbf/src/blenderbim/blenderbim/bim/ui.py#L430)), handles the different states in its `draw` method:

- If `pprops.is_loading` is true, it calls `draw_load_ui`, representing the "Advanced Mode Loading State".
- If `self.file` or `props.ifc_file` is true, it calls `draw_project_ui`, corresponding to either the "Saved and Loaded State" or "Not Saved State", depending on whether the file exists or not (see [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/1f7d80e6f1c7d1cf34c4d0a14ced7cadb03b8bbf/src/blenderbim/blenderbim/bim/module/project/ui.py#L204-L218)).
- If none of the above are true, it calls `draw_create_project_ui`, corresponding to the "Not Created or Loaded State".

To make the code more readable and maintainable, I propose the following changes:

1. Rename the states in the documentation:
   - "Not Created or Loaded State" -> "Project Setup Mode"
   - "Not Saved State" -> "Project Unsaved Mode"
   - "Saved and Loaded State" -> "Project Loaded Mode"
   - "Advanced Mode Loading State" -> "Advanced Loading Mode"

2. Refactor the methods:
   - Rename `draw_create_project_ui` to `draw_project_setup_ui`
   - Extract a new method `draw_unsaved_project_ui` from `draw_project_ui`
   - Extract a new method `draw_loaded_project_ui` from `draw_project_ui`
   - Rename `draw_load_ui` to `draw_advanced_loading_ui`

The resulting `draw` method would look like this:

```python
def draw(self, context):
    # ...
    if pprops.is_loading:
        self.draw_advanced_loading_ui(context)
    elif self.file or props.ifc_file:
        if props.ifc_file:
            self.draw_loaded_project_ui(context)
        else:
            self.draw_unsaved_project_ui(context)                
    else:
        self.draw_project_setup_ui(context)
```

These changes will make the code more self-explanatory and easier to navigate for both developers working on the code and users trying to understand the different states of the Project Info panel.

What do you think? Let me know if you have any suggestions or concerns regarding this refactoring proposal.

**Comment by Moult** [comment]
This is great! Completely agree with all suggestions. Would you like direct commit access to make it easier instead of submitting PRs?

**Comment by Vanuan** [comment]
I think submitting PRs still has value as it makes sure CI workflows pass. In addition to sanity and traceability. Maybe I can get access reviewing/approving PRs if such distinction exists?

**Comment by Moult** [comment]
By the way, I think the advanced mode settings will need to be made reusable. For example, you may want to specify the settings when linking in models. Right now, it's not possible to set filters or special settings on linked models but it will be possible in the future, so that UI needs to be reused.

**Comment by Vanuan** [comment]
So, it would not be merely a file loading mode of "Project Info" panel, but rather some kind of Filter/Preprocessing Config?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/361985/15d15692-6316-40a2-b3fd-8047e9ac43f5)

**Comment by Moult** [comment]
Yeah, it's kinda murky and ambiguous right now. Time will tell. The latest commits start to make this a reality. PR very much appreciated!
