### ISSUE TITLE
Further documentation refactoring suggestion

### ISSUE THREAD

**Issue by Vanuan** [IfcOpenShell/IfcOpenShell#4890]
Currently, the user documentation seems kind of random.

I'm thinking of grouping current documentation items into logical and ordered chapters.

Rough idea:

> 
> 1. **Introduction and Getting Started**
>    - Understanding BIM: Concepts and Terminology (previously: Introduction to BIM)
>    - Overview of BlenderBIM (previously: Things you can do)
>    - Installation and Setup (previously: Installation)
>    - Introduction to the BlenderBIM Interface (previously: some sections of Exploring an IFC model, user reference reworked into a guide format)
>    - Setting Up Your First BIM Project (previously: some bits of Creating an IFC model, tutorialized Project Info reference, mentions file menus, shortcuts, but omits some advanced options, skips IFC-related stuff, pointing to the next chapter)
> 
> 2. **Modeling and Creating IFC Models**
>    - Understanding IFC (explains IFC Schema, basic spatial objects, mentions  buildingSMART, references IfcOpenShell, mentions other bSI/ISO standards and formats, links to "Other Addons" to point out the importance of interoperability and what is the benefit of IFC)
>    - Importing and Viewing IFC Models (previously: Exploring an IFC model)
>    - Inspecting and Querying Models
>    - Starting a New IFC Project (more or less the same as Setting Up Your First BIM Project, but now more IFC specific and some advanced options)
>    - Basic Modeling Techniques (new sections on creating Walls, Doors, Windows, Slabs, Profiles, Rooms, Spaces, etc)
>    - Advanced Modeling Techniques (new sections on Custom Parametric Wall Types, Furniture, Fixtures, Structural Elements, Multi-Story and Complex Structures, etc)
> 
> 3. **Drawing Generation**
>    - Generating 2D Drawings (new)
>    - Adding Annotations and Custom Title Blocks (new)
>    - Dimensioning and Line Work (new)
>    - Hatch Patterns and Line Weights (new)
> 
> 4. **Advanced Use Cases**
>    - Georeferencing and Site Data (could be expanded to be everything related to the site rather than building)
>    - Working with Large Models (existing)
> 
> 5. **Tutorials and Real-World (Imaginary) Projects** (new project-specific tutorials, each focusing on different level of detail)
>    - Project 0: Designing a Room (basic walls and openings, slabs, MEP, basic furniture, basic floor plan drawings) 
>    - Project 1: Designing a Flat (advanced walls and openings, profiles, rooms and spaces, furniture/fixture libraries, elevation/section drawings)
>    - Project 2: Building a Bungalow (roof, advanced foundation, structural elements, roof openings, underground services, running services in subfloor space, drawing details, basic costing and scheduling)
>    - Project 3: Multi-Storey Single-Family Home (templating, types, complex roofs, complex fixtures e.g. solar panels, complex HVAC, plumbing, electrical, basic site landscaping)
>    - Project 4: Terraced/Town Houses/Duplexes (shared walls, shared roofs, complex landscaping, duplicating units, basic parametric floor plans, generating drawings parametrically, clash detection, coordination with other stakeholders)
>    - Project 5: Apartment Block (multiple levels, typical floor, shared amenities and common areas, elevators, parametric services, complex structural elements, advanced exporting, merging, coordination, analysis, advanced costing and scheduling, external tools)
> 
> 7. **User Interface Reference**
>    - Workspace/Customizing the Interface
>    - Toolbars and Menus
>    - Outliner
>    - Property Panels (Scene properties, Object properties, etc)
>    - Keyboard Shortcuts and Preferences
>    - ...
> 
> 8. **Appendix**
>    - Troubleshooting and Support (Common Issues and Solutions, Getting Help and Community Resources)
>    - Version Control with Git
>    - Integration with Other Tools
>    - Data Exchange and Compatibility
>    - Other Add-ons
> 

The main thing currently not existing is tutorials (and probably functionality to implement them). I'm thinking that tutorials should be about projects, coordination of multiple tasks to achieve a specific result, being a combination of just a model, drawings, calculations, bill of materials/take off, etc. More specific tasks using multiple UI elements could be placed in the use cases / "general guide" or dedicated section (e.g. IFC authoring, drawings, MEP, etc). And a detailed description of UI elements could be in User Interface Reference. Then, things unrelated to BlenderBIM (relevant to a more broader BIM industry) could be mentioned in the beginning of each chapter/section. Things that can't be fit in any category could be put into Advanced Use cases or Appendix.

Does it sound like a good plan? Any suggestions/alterations?

**Comment by Moult** [comment]
This is fantastic! I strongly believe that there should be a tutorial section at the beginning. There should be two tutorials: 1) for users who are opening and viewing an existing model and 2) for users who are creating a model.

These tutorials are intended to be a one-pager guide to all of the most important concepts (even if that does mean jumping aroudn the place a bit) for those two usecases. For example, for viewing, it's important to 1) see the schema version, see the spatial breakdown, see object properties, isolate / hide objects, navigate in 3D, and measure things (don't assume any Blender knowledge). For creating a model, jump straight into creating 4 walls, a slab, a roof, a door and a window, and a plan and section.

After the one-page tutorials when it's whet their appetite, it can go into the more formulaic / structured approach.

**Comment by Vanuan** [comment]
I see your point. Sounds tricky without duplication.

Maybe something like this:

0. **Quickstart**
   * **Install**
   * **Explore a Model**
   * **Create a Model**

But the quickstart tutorial would just list the sections of the documentation to read?

For example, the "Explore a Model" section might look like this:

```markdown
## Explore a Model

* [Open an existing IFC model](link-to-section)
* [Navigate the spatial breakdown](link-to-section)
* [Inspect object properties](link-to-section)
* [Isolate and hide objects](link-to-section)
* [Navigate in 3D view](link-to-section)
* [Measure distances and dimensions](link-to-section)
```

And the "Create a Model" section could be structured similarly:

```markdown
## Create a Model

* [Set up a new BIM project](link-to-section)
* [Create walls, slabs, and a roof](link-to-section)
* [Add doors and windows](link-to-section)
* [Generate a plan and section view](link-to-section)
```

I think functionality to transclude sections would've been great in this case. It looks like a custom sphinx module is required for that.

**Comment by BIMvoice** [comment]
This looks very solid! Go ahead, do it! - Thank you for your contribution. 

P.S. I could make videos for many chapters listed in there.

**Comment by Moult** [comment]
Avoiding duplication in general is a good idea, except for this - it's a special scenario.

Like how most projects have a "quick start" or "tl;dr", I strongly believe in a "one-page", hand-held walk through that immediately touches on the 80% most common tasks immediately so a user gets an idea. At the end of it, it should have a "now what? where should i read next?"

The reason the donut tutorial is so popular is because it goes straight into production. You're producing something, you're creating materials, you're doing a render, all within 5 minutes. We need a text (and video too) equivalent :)

**Comment by Vanuan** [comment]
I have a bit of a dilemma here. Quickstart section at the top would mean the installation should be explained before that. And presenting the installation guide before explaining what BlenderBIM is is confusing. So what BlenderBIM can do should be explained first. Then, there's BIM concept that should be explained before that. And now we end up with the same "Getting Started" structure.

So, for the quickstart to make sense, user should have some vague knowledge about BlenderBIM and have it installed, don't you think?

How about this structure:


> 1. Introduction and Getting Started
> - Overview of BlenderBIM
> - Understanding BIM: Concepts and Terminology
> - Installation and Setup
> - Quickstart Guide: Explore and Create Models
> - Introduction to the BlenderBIM Interface
> - Setting Up Your First BIM Project

Where Quickstart Guide could be two subpages:

> - Explore a Model (5-minute guide)
> - Create a Model (10-minute guide)

Where does Blender puts their donut tutorial? Don't see it anywhere here: https://docs.blender.org/manual/en/latest/

**Comment by aothms** [comment]
I think @Moult means this one: https://www.blenderguru.com/tutorials/2022/1/27/how-to-use-blender

My 2 cts is that in this day and age of HTML the linear order in which content is laid out is of lesser importance than the demarcation into clear sections with informative headings. People can find their way if links and headings are clearly labelled. So I wouldn't worry too much about where to place the installation instructions.

**Comment by Vanuan** [comment]
Doesn't look like a one pager 5-minute tutorial to me :)
More of a 6 hours dive-in before I even know if Blender is for me.

**Comment by Moult** [comment]
What's wrong with keeping the current first four pages as the Quickstart section with these "timeframes" as a guide?

 - [Intro to BIM](https://docs.blenderbim.org/users/introduction_to_bim.html) - 2 minute read
 - [Installation](https://docs.blenderbim.org/users/installation.html) - 5 to 10 minute process
 - [Explore a model](https://docs.blenderbim.org/users/exploring_an_ifc_model.html) - 15 minutes from beginning to end
 - [Create a model](https://docs.blenderbim.org/users/creating_an_ifc_model.html) - 20 minutes from beginning to end

**Comment by Vanuan** [comment]
Ok. Here's what I've got

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/361985/b989903d-ec32-435f-9e32-1fb9f5fecbfb)

Does it look like a good plan for the documentation index page?

**Comment by Moult** [comment]
That's really beautiful! Over time, I expect the `Sections` section to evolve. Most likely it will probably align with the tabs in the UI (e.g. Object Information, Geometry and Materials, Drawings, Systems, Structural, Cost/Scheduling...) because each one of these topics is a beast in its own right, and also reflect the types of users (i.e. each with a different background / discipline).

**Comment by Moult** [comment]
This seems underway, so closing.

**Comment by Vanuan** [comment]
I've stumbled across this: https://diataxis.fr/
![image](https://github.com/user-attachments/assets/8fc88b52-897f-4590-bef7-4d80a7a69022)

It's a framework on how to write technical documentation. 
It looks like what we have now is very similar to the framework. We have tutorials and we have reference. Other sections are how to guides intermixed with explanations.

So the only thing that's missing from that model is clearer separation between "Understanding" articles and "How to" articles. Currently, the idea is to have introductory chapter to each big section (modeling, drafting, advanced) that explains basic concepts or refers to more information elsewhere. But maybe it should be the other way around, first provide a guide on how to achieve something and then discuss and explain why this is the way and what other ways are possible, what's on roadmap and what's out of scope.

The earlier version of diataxis had "Explanation" named as "Discussions". So the idea is that "How to model a wall" should not discuss all the possible approaches to creating a wall. It should be problem oriented and have only one solution, so should rather be named "How to create a wall using arbitrary shape (assign IfcWall to a cube)", "How to create a straight wall segment (set length and height, click add)", "How to create a curved wall segment", "How to connect wall segments using polyline (not implemented yet)", "How to connect wall segments using mitre/butt/extend" rather than having a long list of all possible ways a wall can be modeled in IFC none of which are implemented. After these how to articles, there can be a section "Best practices when modeling a wall" which can discuss on where would you use each method of modeling, explain IFC concepts, provide downloadable IFC examples, and maybe compare BBIM with other architectural software in this regard.

**Comment by Moult** [comment]
That's really insightful! Thanks for the share!
