### ISSUE TITLE
Assign properties working only for the last selected object

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4892]
As in the title, and I believe this is a bug.

Here is what I try to do:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/cba565c0-a12c-4c81-9409-645c70bdaee0)

After assigning it, the slab gets the property and Pset, but not the wall.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/fe8fbea6-15bf-4f0f-a2a9-8e3e70c9a61c)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/7dcb6928-0bda-4131-a680-a49f19f67c5e)

**Comment by ppaawweeuu** [comment]
@BIMvoice I'm not sure if i understand your problem correctly but it seems to be normal that properties are assigned to Active object (the one last selected, brighter outline).
Did you try Copy Property To Selection button? It means match properties from Active object (one) to Selected objects (many).

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/84725e6c-3cce-4517-9d67-b8bc6787f693)

It is core concept for linking or copying materials, geomety, modifiers, actions etc. in pure Blender.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/61344631/f8039f88-9ed7-462a-a983-7787161f2ef1)

**Comment by BIMvoice** [comment]
> @BIMvoice I'm not sure if i understand your problem correctly but it seems to be normal that properties are assigned to Active object (the one last selected, brighter outline). Did you try Copy Property To Selection button? It means match properties from Active object (one) to Selected objects (many).
> 
> ![image](https://private-user-images.githubusercontent.com/61344631/342454696-84725e6c-3cce-4517-9d67-b8bc6787f693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjY5NjEsIm5iZiI6MTcyMDQyNjY2MSwicGF0aCI6Ii82MTM0NDYzMS8zNDI0NTQ2OTYtODQ3MjVlNmMtM2NjZS00NTE3LTlkNjctYjhiYzY3ODdmNjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MjgzYjcxYTZjYzA2YTI0NjNmYjJmNzQ4MDMyODJkOTk0MzFmMmQyM2FlMTIyZTQ3ODM3M2Y3YWZmMjQxYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oITHfDCVkk71XghB-AVAz36hAMVFKMCNHhEtpxidP8Y)
> 
> It is core concept for linking or copying materials, geomety, modifiers, actions etc. in pure Blender.
> 
> ![image](https://private-user-images.githubusercontent.com/61344631/342458865-f8039f88-9ed7-462a-a983-7787161f2ef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjY5NjEsIm5iZiI6MTcyMDQyNjY2MSwicGF0aCI6Ii82MTM0NDYzMS8zNDI0NTg4NjUtZjgwMzlmODgtOWVkNy00NjJhLWE5ODMtNzc4NzE2MWYyZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3N2Y3Y2IyNTM2YTBmZDk4MjNhYTU0Mzk4MmRiZWI5YjRhOTY0NTRhZWE5ZjUzODM5ZjRiOGMxNDRlYTI5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JskzSxfoShsu59XXVYEzECh9sA3NoB10bs2J9yLdnOA)

You are right! I always forget about this concept in Blender, it works if I click on that symbol to copy the properties to all selected objects.

Thank you very much!
