### ISSUE TITLE
IfcTester is not checking Boolean values correct (or the problem is ACCA usBIM)

### ISSUE THREAD

**Issue by MennoMekes** [IfcOpenShell/IfcOpenShell#4893]
When I create a specification in ACCA usBIM v1.0.77 where I check LoadBearing in the Pset_ColumnCommon to be true it provides me a 100% pass. But when I copty the specification and ask for LoadBearing to be false, I get the same 100% pass. This is not possible.
Also, the export from ACCA write true/false without a capital T/F. But in all software, I see True/False represented with capitals. 
After editing the file and replacing true with True and false with False, the result remains the same.
When I try another file in Ifc4x3 I get a similar result only everything fails.
Ofcourse I will send a link to this issue to ACCA so they can have a look as well since I cannot tell where the problem is.

[Boolean issue.zip](https://github.com/user-attachments/files/15897266/Boolean.issue.zip)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/66679121/03c71111-a41e-459a-8b23-eb1e4353e831)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/66679121/0e538ff8-260f-4810-a5df-2d293bd9348e)

Blender 4.1 with blenderbim-240602-py311-win

Thanks a lot!

**Comment by Moult** [comment]
Thanks! The lowercase behaviour is correct. It changed on May 6P https://github.com/buildingSMART/IDS/issues/290
