### ISSUE TITLE
IDS Version 1 Support

### ISSUE THREAD

**Issue by Judithlourde** [IfcOpenShell/IfcOpenShell#4896]
Hi IfcOpenShell team,

Are there any plans to support IDS Version 1 validation in IfcOpenShell? 

Thanks for your great work!

Best,
Judith

**Comment by BIMvoice** [comment]
It just works for me right now. Running my 1.0 IDSs created with ACCA usBIM.IDS editor works without any problems. Did you try something specific that did not work?

**Comment by Judithlourde** [comment]
Hi,

I tried using an IDS created from Plannely in BlenderBIM, but it doesn't work. I received the following error message:

![Snag_2d7e9a46](https://github.com/IfcOpenShell/IfcOpenShell/assets/81017429/7cfe85db-26a6-49ec-a13e-a50d39d5d33a)

**Comment by aothms** [comment]
The minOccurs/maxOccurs has been removed from the IDS spec prior to 1.0. So this is not an IDS v1. https://github.com/buildingSMART/IDS/pull/209/files#diff-0870e5662f7cffd0bbc15225f000b7d85d718c42e82e5ce56a9d6191921f7184L114

**Comment by Moult** [comment]
I think this is not what the error report is referring to. It's referring to minOccurs on the applicabilityType, which is allowed: https://github.com/buildingSMART/IDS/blob/7171c00871b29ce56e667e7669f926c1a1d7f0da/Development/ids.xsd#L66

@Judithlourde can you check your `ifctester/ids.xsd` to see whether it has that line in it?

**Comment by Judithlourde** [comment]
Thanks for reporting this issue. I can share the IDS file that was created from Plannerly. Please find the file attached below:

[IDS-Plannerly.txt](https://github.com/user-attachments/files/15910411/IDS-Plannerly.txt)
Note: The IDS file was converted to a .txt format because the original format is not supported for upload.  

From the link you provided, it appears that the `minOccurs` and `maxOccurs` attributes have been moved from the specification to the applicability section. This change matches how these attributes are used in the file generated by Plannerly.

**Comment by Moult** [comment]
See my comment above :)


That was added 4 months ago: https://github.com/buildingSMART/IDS/commit/314e0a717e9965c0a7c9df139de6e7462ca3b978#diff-0870e5662f7cffd0bbc15225f000b7d85d718c42e82e5ce56a9d6191921f7184R73 - it's possible that you have an old version of IfcTester / BlenderBIM Add-on.

In any case I've also bumped support up to v1.0 (there were a few minor changes) so we're good now :)

**Comment by Moult** [comment]
Note that the IDS from Plannery seems to have a couple of invalid issues:

 - Booleans should be specified as lowercase strings.
 - dataType must be all uppercase

I've fixed your IDS and attached a compliant version here. 
[IDS-Plannerly.txt](https://github.com/user-attachments/files/15910600/IDS-Plannerly.txt)

**Comment by BIMvoice** [comment]
Yep, Plannerly IDS works well within the platform, still a way to go to fix them for download and use them in BlenderBIM.

**Comment by Judithlourde** [comment]
I found that I am using PyPI to update it, which is why my version is a little bit outdated at version 0.9.7.
Thank you for your assistance.

**Comment by Moult** [comment]
Ah OK, yes PyPI is a bit outdated. We'll be doing a few releases in the coming month.

**Comment by Judithlourde** [comment]
Thank you:)
