### ISSUE TITLE
Openings Not visible

### ISSUE THREAD

**Issue by avinash-218** [IfcOpenShell/IfcOpenShell#4899]
I have scripted a code that creates wall and add openings on the wall. The geometry of the opening is swept disk solid. I need this kind of opening in the use case of a wire passing through a wall.

Below is the code : 

```import ifcopenshell
import ifcopenshell.util.shape_builder
from ifcopenshell.api import run

# Create a blank model
model = ifcopenshell.file()
sb = ifcopenshell.util.shape_builder.ShapeBuilder(model)

# Create owner history
person = model.create_entity("IfcPerson", FamilyName="Doe", GivenName="John")
organization = model.create_entity("IfcOrganization", Name="My Organization")
person_and_organization = model.create_entity("IfcPersonAndOrganization", ThePerson=person, TheOrganization=organization)
application = model.create_entity("IfcApplication", ApplicationDeveloper=organization, Version="1.0", ApplicationFullName="My Application", ApplicationIdentifier="APP-001")
owner_history = model.create_entity("IfcOwnerHistory", OwningUser=person, OwningApplication=application, ChangeAction="ADDED")

# Create IFC Project element
project = model.create_entity("IfcProject", Name="My Project")
project.OwnerHistory = owner_history

# Add units
length_unit = run("unit.add_si_unit", model, unit_type="LENGTHUNIT", prefix="MILLI")
area_unit = run("unit.add_si_unit", model, unit_type="AREAUNIT")
run("unit.assign_unit", model, units=[length_unit, area_unit])

# Create context
context = run("context.add_context", model, context_type="Model")
body_context = run("context.add_context", model, context_type="Model", context_identifier="Body", target_view="MODEL_VIEW", parent=context)

# Create site, building, storey
site = model.create_entity("IfcSite", Name="My Site", OwnerHistory=owner_history)
building = model.create_entity("IfcBuilding", Name="Building A", OwnerHistory=owner_history)
storey = model.create_entity("IfcBuildingStorey", Name="Ground Floor", OwnerHistory=owner_history)

model.create_entity("IfcRelAggregates", OwnerHistory=owner_history, RelatingObject=project, RelatedObjects=[site])
model.create_entity("IfcRelAggregates", OwnerHistory=owner_history, RelatingObject=site, RelatedObjects=[building])
model.create_entity("IfcRelAggregates", OwnerHistory=owner_history, RelatingObject=building, RelatedObjects=[storey])

# Create wall entity
wall = run("root.create_entity", model, ifc_class="IfcWall", name="Wall1")
wall.ObjectType = "Wall"
wall_representation = sb.extrude(sb.polyline([(0.0, 0.0), (0.0, 1000.0), (1000.0, 1000.0), (1000.0, 0.0)], closed=True), 1000)
run("geometry.assign_representation", model, product=wall, representation=sb.get_representation(body_context, wall_representation))
run("spatial.assign_container", model, relating_structure=storey, products=[wall])

# Create opening element
opening = run("root.create_entity", model, ifc_class="IfcOpeningElement", name='Opening1')
opening_curve = sb.polyline([(500.0, 500.0, -500.0), (500.0, 500.0, 1500.0)])
opening_swept_curve = sb.create_swept_disk_solid(opening_curve, 30)
run("geometry.assign_representation", model, product=opening, representation=sb.get_representation(body_context, opening_swept_curve))

model.create_entity("IfcRelVoidsElement", GlobalId=ifcopenshell.guid.new(), OwnerHistory=owner_history, RelatingBuildingElement=wall, RelatedOpeningElement=opening)
```

I can see the opening in Bimvision and when the ifc is imported in revit. but i can't visually see the opening in blenderbim but in the object property i can see the opening is assigned.

Anyone could help? Thanks in advance.

**Comment by Moult** [comment]
If you are simply wanting to visualise the opening in Blender, with the BIM Tool activated, click on the wall then do Alt-O or Toggle Openings in the toolbar.

**Comment by Moult** [comment]
BTW there is an API for voiding and managing owner histories, users, apps, people/orgs you might be interested in which can simplify your code.

**Comment by avinash-218** [comment]
> BTW there is an API for voiding and managing owner histories, users, apps, people/orgs you might be interested in which can simplify your code.

got it thanks !!

**Comment by Moult** [comment]
Can you attach a sample IFC file where you don't need to toggle openings? There seem to be a number of bugs in that script on that website (e.g. add_wall_representation signature is incorrect, and a slab variable that doesn't exist).

If I test the script (fixing those errors) I get the expected behaviour (i.e. I have to toggle openings and they show in blue)

![2024-06-24-105536_624x461_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/0ba94f13-de31-4f5b-97bb-70d09c58e43d)

**Comment by avinash-218** [comment]
@Moult 
Here is the file.
[Void.zip](https://github.com/user-attachments/files/15949510/Void.zip)

**Comment by Moult** [comment]
Looks fine to me. (here is how it comes in by default with no openings - I can then toggle them on later).

![2024-06-24-134500_759x495_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/0f03fd00-b3ef-444c-b2ea-a7ad0604275e)

**Comment by avinash-218** [comment]
Yes but this file don't. I have to toggle voids in this file.

[ifc_wire_through_wall.zip](https://github.com/user-attachments/files/15949538/ifc_wire_through_wall.zip)

**Comment by Moult** [comment]
Oh. Now I get what you mean. You're not talking about the opening element being visible, you're saying the _void_ from the opening is not visible.

The reason is because your file is invalid. Invalid files run into undefined behaviour - some viewers might make some assumptions, and others... won't :) The reason is that you have a wall / opening with representations but no placements. This is not allowed in IFC - the rule is that if there is a representation, there must be a placement.

I've attached a fixed version if your model with these placements and now I think it gets what you're after.

[fixed.txt](https://github.com/user-attachments/files/15950569/fixed.txt)

![2024-06-24-161217_489x505_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/9cce8698-b92b-47e7-aaf4-864f49dcae8e)

**Comment by avinash-218** [comment]
> Oh. Now I get what you mean. You're not talking about the opening element being visible, you're saying the _void_ from the opening is not visible.
> 
> The reason is because your file is invalid. Invalid files run into undefined behaviour - some viewers might make some assumptions, and others... won't :) The reason is that you have a wall / opening with representations but no placements. This is not allowed in IFC - the rule is that if there is a representation, there must be a placement.
> 
> I've attached a fixed version if your model with these placements and now I think it gets what you're after.
> 
> [fixed.txt](https://github.com/user-attachments/files/15950569/fixed.txt)
> 
> ![2024-06-24-161217_489x505_scrot](https://private-user-images.githubusercontent.com/88302/342221164-9cce8698-b92b-47e7-aaf4-864f49dcae8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTAyMzksIm5iZiI6MTcxOTIwOTkzOSwicGF0aCI6Ii84ODMwMi8zNDIyMjExNjQtOWNjZTg2OTgtYjkyYi00N2U3LWFhZjQtODY0ZjQ5ZGNhZThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA2MTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOTk4OTczZjJhMGI2M2EyNDQ5MDYxOGVlNWQ3MDdmN2RjNGQ3ZjRmNmRkZGUwZmRiMmQ1M2JjYjUyMzg5OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J3QDg4gdpZ83bilkxR3VrG1A94dKWwah8fDNJlcTyuc)

thank you so much.
