### ISSUE TITLE
Allow Ifc2x3 and Ifc4 conversion from the same executable / library

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#49]
As of now, whether to link to the 2x3 or 4 schema is a compile time option. This is inconvenient for users as they need to be aware of the schema of their model and have two executables ready. IFC4 is mostly a superset of 2x3, but there might be some incompatibilities (nobody really knows it seems).

One possible approach would be to have multiple separate static/dynamic libraries for the different schemas, that are built from the same source, with the same preprocessor directives that there are now. In run-time geometry interpretation can then be delegated to the respective library based on the schema identifier in the model file.

**Comment by Fredounet** [comment]
Great idea. I had compiled IFC4 to realise I actually shouldn't have. When I say the cmake "option", I thought it would do 4 on top of 2x3, not instead. Great to see it on the todo list for future release.

**Comment by johnfoundations** [comment]
Can someone think of a quick / best  way to add a suffix to the IfcParse:: namespace (as it appears in the symbol table, not source code)? Most of the .so symbol table is already instantiated as ifc type specific.

**Comment by aothms** [comment]
@johnfoundations Sorry, I am not following you. You want to prefix everything in the `IfcParse` namespace for both schemas? How will the appropriate code be selected based on the schema identifier encountered in the file?

**Comment by johnfoundations** [comment]
I was looking at the symbol tables, and thinking about hacking the source so both builds create entirely 2x3 namespace or 4 namespace, so both libraries can be linked.

**Comment by aothms** [comment]
Well perhaps a template argument to the `IfcFile` class that accepts a schema identifier somehow is more or less enough to make this happen?

**Comment by BoobsAreBait** [comment]
Is is a thing still to have only 1 executable for both IFC2X3 and IFC4? That would be highly appreciated :)

**Comment by aothms** [comment]
> Is is a thing still to have only 1 executable for both IFC2X3 and IFC4? That would be highly appreciated :)

Oh definitely. I guess this can be closed. This is all implemented in the 0.6 branch: https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0

not everything in 0.5 is fully ported to 0.6 yet though

You can compile yourself or get a prebacked binary here

https://github.com/IfcOpenBot/IfcOpenShell/commit/6e8f5c84e6a928cd5a0839b9373bbe87f695ac14#commitcomment-30394420
