### ISSUE TITLE
Queries not working

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4900]
When using IfcWall, IfcSlab, IfcWindow in Query, everything in the model is selected instead of only the inteded elements. I use the last version from 6th of June, macos m1.

<img width="1496" alt="Screenshot 2024-06-20 at 16 05 05" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/b437dbb1-680a-47fb-bc31-7753d03f5cb6">

**Comment by theoryshaw** [comment]
Yeah, it seems that query shouldn't select anything. 

You might know this already, but when selecting certain IFC classes, i think the following is the method...

![2024-06-20_10-18-56_blender_(Unsaved)_-_Blender_4 1blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/7aa11ca9-ab75-40b4-80b4-a33a5747da7d)

**Comment by steverugi** [comment]
hi @BIMvoice 
to select IfcWindows using the `Query` box type `class` in the left and `IfcWindow` in the right one
but as you wrote it seems a bit confused when the query is not properly typed..
