### ISSUE TITLE
Project duplicated

### ISSUE THREAD

**Issue by R2naizr** [IfcOpenShell/IfcOpenShell#4902]
Blender Version : 4.1.1
BBIM Version : v0.0.240602-4770b1

I believe the project hierarchy should be only generated once a new project is created.
I've noticed that the project hierarchy is already generated once blender is open and once a new project is created, a new project hierarchy is created with the suffix ".001". Shouldn't the outliner be empty prior to the creation of a new ifc project, seems like the duplication is a mistake.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79116991/8442f675-1870-49cc-955e-bbacc7e9fcbe)
shown above is the new blender file opened. The project hasn't been created yet, but shows a ifcproject hierarchy already generated.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79116991/90924896-5cff-464e-9de5-4a079b3cb85f)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79116991/566a5750-1557-4b2a-9d7b-1aaf64310baa)
shown above the result of creating a new ifcproject, with the addition of a new ifproject/myproject.001. All modifications done to the spatial manager affects myproject.001, so I assume the initial hierarchy (ifproject/myproject) is just an error.

Thanks
Atu

**Comment by theoryshaw** [comment]
I didn't 100% follow you, but if you do this...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c0877ded-d9a7-40eb-9d6b-94a039f370de)

Do you see this?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/5309e6c1-7154-4d1e-8bf3-6e631faed9a4)

If so, i think that's the problem--the startup file should not have any ifc hierarchy in it.

**Comment by R2naizr** [comment]
Yes when I open blender, there's a hierarchy already established, which shouldn't be the case until I create a project.

**Comment by theoryshaw** [comment]
Yeah, it seems you might have accidently saved this hierarchy into your 'startup file'. 

Here's how to reset your startup file..
https://chatgpt.com/share/d811393c-5cea-4dea-b66a-26d7519a8743

**Comment by R2naizr** [comment]
Ahh yes, that makes sense. Thank you
