### ISSUE TITLE
"Unable to find find keyword in schema"

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#491]
Note the duplicate "find". While at it, it would be nice to report the actual keyword which was not recognized.

**Comment by aothms** [comment]
Ow oops. Thanks. Maybe if we're at it also create some different exception subclasses.

**Comment by Moult** [comment]
I looked at the code for this. This string is in _many_ places in `ifcparse/`, which makes me suspect some ^C^V'ing :)

Do you mind if I just do a mass replace? I also notice the error message is quite generic whereas sometimes the "keyword" could be an enum, but not necessarily. Maybe when reporting the keyword, we should make the error message more specific.

If this sounds good to you I can start preparing a PR.

**Comment by Stinkfist0** [comment]
These can be found from the buildingSmart website, however, I'm not completely sure which of these should be used now: http://www.buildingsmart-tech.org/mvd/IFC4Add2TC1/

**Comment by aothms** [comment]
@Moult were you planning to commit a fix for this?

**Comment by Moult** [comment]
I guess this can be closed :)
