### ISSUE TITLE
CGAL testing - multiprocessing OCC + CGAL is slower than 0.7.0

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4915]
I'd like to start testing CGAL. Things like is it faster, does it solve the very old bug about slow breps, can I finally delete the pure Blender mesh implementation, how does it work (I.e. write documentation) how does CGAL + OCC fallback or prioritization work... And of course find any potential bugs :)

Unfortunately I have no idea how to get started :) @aothms how do I enable it or set prioritization and callbacks in Python, and what should I look out for? (Is it a drop in replacement or does it change things)

**Comment by aothms** [comment]
It is probably a bit early for that. We'd better focus on correctness first. We can probably write some CI/CD to convert using occt and then cgal and compare for "equivalentness" (I guess simplest is just randomly sampling points on the mesh, closest point on other mesh and check for correspondence, then vice versa).

Here's some numbers I obtained on duplex, which is not very mesh heavy.

```
>>> import timeit, ifcopenshell, ifcopenshell.geom
No stream support: No module named 'lark'
>>> f = ifcopenshell.open('d.ifc')
>>> timeit.timeit(lambda: list(map(lambda x: x.geometry.verts, ifcopenshell.geom.iterate(ifcopenshell.geom.settings(), f, geometry_library='cgal'))), number=2)
6.6753165000118315
>>> timeit.timeit(lambda: list(map(lambda x: x.geometry.verts, ifcopenshell.geom.iterate(ifcopenshell.geom.settings(), f, geometry_library='opencascade'))), number=2)
4.020119499997236
>>> timeit.timeit(lambda: list(map(lambda x: x.geometry.verts, ifcopenshell.geom.iterate(ifcopenshell.geom.settings(), f, geometry_library='hybrid-cgal-simple-opencascade'))), number=2)
1.8601449999259785
```

The reason plain cgal is slow is that it uses a very bruteforce approach for 'fuzzy' bools or rather dilated bools. I have some other strategies, but they too experimental to seriously consider now. So if we still use occt for any bool, but try first with the simple-cartesian-number-type cgal variant (cgal-simple) we already get some rather nice outcomes.

Note that as soon as you use another geometry_library than opencascade all non-triangulated serializers will segfault :/

**Comment by Moult** [comment]
Correctness-wise, if I use CGAL all the advanced breps seem to disappear. Is this expected?

![2024-06-25-115519_459x425_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/de623907-2218-44a0-a681-cfb6f1fcc268)

Otherwise at a glance pretty equivalent. Haven't done detailed checks yet.

Some speed tests - it seems as though v0.8.0 across the board is significantly slower :(

Model | Size | v0.7.0 | Hybrid | OCC | CGAL
--- | --- | --- | --- | --- | ---
racbasicsampleproject | 10M | 1.14 | 2.25 | 2.43 | 3.34
PP-H | 185M | 29 | 46 | 48 | 74

**Comment by aothms** [comment]
> Correctness-wise, if I use CGAL all the advanced breps seem to disappear

Probably, although the polyhedral ones we can easily get to work.

> Some speed tests - it seems as though v0.8.0 across the board is significantly slower :(

First thing to take a look at would be compilation settings. What's your CMAKE_BUILD_TYPE or do you have a line from the `make VERBOSE=1`?

**Comment by Moult** [comment]
Tested with the bot build, `ifcopenshell.ifcopenshell_wrapper.version()` is `0.7.9-39cd98000`, and times are the same (i.e. OCC is 2.45 for rac and 48 for PP-H).

**Comment by Andrej730** [comment]
The results I've got:
```
0.8.0 https://github.com/IfcOpenBot/IfcOpenShell/commit/39cd980008100162ab469505524e40c4bde16489
racbasicsampleproject.ifc (from here https://github.com/jul-ls/sample-ifc-files)
cgal 16.21118909999859
opencascade 26.29157110000233
hybrid-cgal-simple-opencascade 4.361587400002463

v0.7.0-c7830e9e5
racbasicsampleproject.ifc
24.977520899999945
```

snippet:
```python
import timeit, ifcopenshell, ifcopenshell.geom, ifcopenshell.ifcopenshell_wrapper
print(ifcopenshell.ifcopenshell_wrapper.version())

filepaths = [
    r"racbasicsampleproject.ifc"
]

def test(f, geometry_library):
    t = timeit.timeit(
        lambda: list(
            map(
                lambda x: x.geometry.verts,
                ifcopenshell.geom.iterate(ifcopenshell.geom.settings(), f, geometry_library=geometry_library),
            )
        ),
        number=2,
    )
    print(geometry_library, t)

for filepath in filepaths:
    f = ifcopenshell.open(filepath)
    print(filepath)
    test(f, "cgal")
    test(f, "opencascade")
    test(f, "hybrid-cgal-simple-opencascade")
```

**Comment by aothms** [comment]
Thanks @Andrej730 

```
v0.7.0-c7830e9e5
24.977520899999945

0.8.0
opencascade 26.29157110000233
hybrid-cgal-simple-opencascade 4.361587400002463
```

^ This is exactly what I was expecting / hoping for. 10% penalty for occt is not nice, but we can probably shave some of that off still, but offloading the meshes to cgal-simple makes up for a large part of it :) As long as you don't need to do e.g SvgSerialization.

```
0.8.0
racbasicsampleproject.ifc (same file as Dion)
opencascade 6.874530900000536

v0.7.0-c7830e9e5
racbasicsampleproject.ifc (same file as Dion)
12.204742499998247
```

^ This is a bit suspicious. Maybe there are things missing. I guess the difference is one of `RAC` with CoordinationView and when is `RAC` with DesignTransfer with advanced breps.

Actually, in theory it's indeed possible that actually v0.8 adv brep does better now because polyhedral advanced breps take the same codepath as non-advanced breps, which is more optimized (the faceset_helper thing). Most of the adv breps for the walls are actually polyhedral / planar so maybe that makes sense.

---

So the main question is. Why are @Moult 's results so different? Is het just unlucky? Is it a Windows / Linux thing? Or is it multi-threading?

**Comment by Moult** [comment]
Interesting, with the script I get same results (gee I have a fast computer?)

```
v0.7.0-c7830e9e5
/home/dion/racbasicsampleproject.ifc
6.0922968609957024

0.7.9-39cd98000
/home/dion/racbasicsampleproject.ifc
cgal 2.2419935149373487
opencascade 3.314860632061027
hybrid-cgal-simple-opencascade 2.3930823949631304
```

But in Blender if I test Blender loading a scene using the last BBIM 0.7.0 branch vs the last 0.8.0 branch I get:

```
v0.7.0-c7830e9e5
...
0 / 13 elements processed ...
Create elements :: 0.75
...
Import finished in 1.24 seconds

0.7.9-39cd98000
0 / 13 elements processed ...
Create elements :: 2.14
...
Import finished in 2.57 seconds
```

So maybe there is something that the Blender loader is doing that the simple script isn't that makes a big difference? Like setting a context ID, include filter, setting deflection...

It's almost midnight maybe I'm staring at numbers too long and missing something obvious.

**Comment by Moult** [comment]
I think it's multithreading. I changed one line:

```
ifcopenshell.geom.iterate(ifcopenshell.geom.settings(), f, multiprocessing.cpu_count(), geometry_library=geometry_library)
```

Now the result I get is:

```
v0.7.0-c7830e9e5 MULTITHREADED
/home/dion/racbasicsampleproject.ifc
1.1754209259524941

0.7.9-39cd98000 MULTITHREADED
/home/dion/racbasicsampleproject.ifc
cgal 3.8782874209573492
opencascade 4.2969447780633345
hybrid-cgal-simple-opencascade 4.0143126079346985
```

... yes, the time actually _increases_ in v0.7.9?

**Comment by aothms** [comment]
Hm, I've been breaking my head over this.

I think what we may be seeing is two aspects:

- https://github.com/IfcOpenShell/IfcOpenShell/blob/675e1982ee4baf847e73cbc11f0ecdf1f44a54bf/src/ifcgeom/Iterator.h#L181C1-L181C16

  Apparently on rac2 completing the mapping goes from 1s to 2s when disabling the cache. That is more than I expected (both relative and absolute). This phase is currently not multi threaded because I assumed it'd be just fighting over the lazy loaded file resource. But maybe this needs to be revisited (and IfcFile should be made lock free after parsing anyway).

- logging. v0.8 is a bit clumsy in all sorts of crap it logs (and also logs some valid stuff because it doesn't understand curved adv brep yet). This logging goes through a mutex which is somewhat expensive. I've already been removing some of the unnecessary log messages and at least on my side I think the situation improved a bit, but maybe I'm hallucinating.

If you want to help testing

1. Run before and after https://github.com/IfcOpenShell/IfcOpenShell/commit/675e1982ee4baf847e73cbc11f0ecdf1f44a54bf and see if there is any improvement on multi threading.

2. Take note of the times reported in https://github.com/IfcOpenShell/IfcOpenShell/commit/76b7748be181087ba6951a7d8c4684e7a4ba25e9 (`ifcopenshell.ifcopenshell_wrapper.turn_on_detailed_logging()`  if using py otherwise just `-v`) on the latest version and compare single and multi threads.

---

I also have some more fun stuff:

```diff
diff --git a/src/ifcgeom/AbstractKernel.cpp b/src/ifcgeom/AbstractKernel.cpp
index a82e7c164..0fc7028ce 100644
--- a/src/ifcgeom/AbstractKernel.cpp
+++ b/src/ifcgeom/AbstractKernel.cpp
@@ -204,6 +204,15 @@ ifcopenshell::geometry::kernels::AbstractKernel* ifcopenshell::geometry::kernels
 }

 bool ifcopenshell::geometry::kernels::AbstractKernel::convert_impl(const taxonomy::collection::ptr collection, IfcGeom::ConversionResults& r) {
+       using std::chrono::high_resolution_clock;
+       std::array<std::chrono::high_resolution_clock::time_point, 2> time_points;
+       time_points[0] = high_resolution_clock::now();
+       using std::chrono::duration;
+
+       std::ostringstream oss;
+       oss << std::this_thread::get_id();
+       auto osss = oss.str();
+
        auto s = r.size();
        for (auto& c : collection->children) {
                convert(c, r);
@@ -216,6 +225,15 @@ bool ifcopenshell::geometry::kernels::AbstractKernel::convert_impl(const taxonom
                        r[i].setStyle(collection->surface_style);
                }
        }
+
+       time_points[1] = high_resolution_clock::now();
+
+       duration<double, std::milli> ms_double = time_points[1] - time_points[0];
+       if (collection->instance) {
+               auto S = osss + "|" + std::to_string(duration<double>(time_points[0].time_since_epoch()).count()) + "|" + std::to_string(collection->instance->as<IfcUtil::IfcBaseClass>()->data().id()) + "|" + std::to_string(ms_double.count());
+               Logger::Error(S);
+       }
+
        return r.size() > s;
 }

```

```python
import sys
import matplotlib.pyplot as plt

rs = sorted((r.rsplit(' ', 1)[1].strip().split('|') for r in list(open(sys.argv[1])) if r.count('|') == 3), key=lambda t: float(t[1]))
t0 = min(map(float, [r[1] for r in rs]))
threads = sorted(set(r[0] for r in rs))

for threadid, start, _, duration in rs:
    start, duration = map(float, (start, duration))
    plt.plot([start - t0, start - t0 + duration / 1000.], [threads.index(threadid)] * 2)

plt.savefig(sys.argv[1] + ".png")
```

But these seem to indicate multi threading is at least doing something

![r2st txt](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/06373170-27e1-4e7a-9e7a-09464cf04ca4)

![r2 txt](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/9790b1ca-be6d-4527-bc18-40591d7298d2)

**Comment by Moult** [comment]
Uh:

```
0.8.0 0357d15ce
/home/dion/racbasicsampleproject.ifc
cores: 1 cgal 3.9651195369660854
cores: 12 cgal 4.149534211028367
cores: 1 opencascade 5.942258195951581
cores: 12 opencascade 4.555333557073027
cores: 1 hybrid-cgal-simple-opencascade 4.397451326018199
cores: 12 hybrid-cgal-simple-opencascade 4.233980680117384

0.8.0 675e1982e
/home/dion/racbasicsampleproject.ifc
cores: 1 cgal 3.9689609750639647
cores: 12 cgal 4.387642340036109
cores: 1 opencascade 6.0446474340278655
cores: 12 opencascade 4.797830427996814
cores: 1 hybrid-cgal-simple-opencascade 4.557551332982257
cores: 12 hybrid-cgal-simple-opencascade 4.58081852295436
```

Testing with:

```python
import timeit, ifcopenshell, ifcopenshell.geom, ifcopenshell.ifcopenshell_wrapper
import multiprocessing
print(ifcopenshell.ifcopenshell_wrapper.version())
# ifcopenshell.ifcopenshell_wrapper.turn_on_detailed_logging()

filepaths = [
    r"/home/dion/racbasicsampleproject.ifc"
]

def test(f, geometry_library, core_count):
    t = timeit.timeit(
        lambda: list(
            map(
                lambda x: x.geometry.verts,
                ifcopenshell.geom.iterate(ifcopenshell.geom.settings(), f, core_count, geometry_library=geometry_library),
            )
        ),
        number=2,
    )
    print(f"cores: {core_count}", geometry_library, t)

for filepath in filepaths:
    f = ifcopenshell.open(filepath)
    print(filepath)
    cpu_count = multiprocessing.cpu_count()
    test(f, "cgal", 1)
    f = ifcopenshell.open(filepath)
    test(f, "cgal", cpu_count)
    f = ifcopenshell.open(filepath)
    test(f, "opencascade", 1)
    f = ifcopenshell.open(filepath)
    test(f, "opencascade", cpu_count)
    f = ifcopenshell.open(filepath)
    test(f, "hybrid-cgal-simple-opencascade", 1)
    f = ifcopenshell.open(filepath)
    test(f, "hybrid-cgal-simple-opencascade", cpu_count)
```

**Comment by Moult** [comment]
Is there a reason I see the numbers twice? It's almost as if it's running it twice.

**Comment by aothms** [comment]
Thanks!

It is running it twice because of `number=2` timeit takes the average. So unfortunately that's not it.

But this is weird. These numbers don't add up. We'll figure it out. At least it's reassuring that the first two numbers make sense. Is it mining bitcoins in the meantime?

```
[Notice] [2024-07-02 18:48:04] Performing mapping took 618.506534ms
[Notice] [2024-07-02 18:48:04] Geometry interpretation took 1309.135095ms
cores: 1 cgal 3.991869969991967

[Notice] [2024-07-02 18:48:57] Performing mapping took 1756.316151ms
[Notice] [2024-07-02 18:48:57] Geometry interpretation took 264.971103ms
cores: 12 cgal 4.285267588915303
```

**Comment by Moult** [comment]
> It is running it twice because of number=2 timeit takes the average.

Oh. Yeah :)

I ran it again for `## 0.8.0 0357d15ce BEFORE` and here are the full untruncated logs if it helps: 
[cgalallcores.txt](https://github.com/user-attachments/files/16066565/cgalallcores.txt)
[cgal1core.txt](https://github.com/user-attachments/files/16066570/cgal1core.txt)

**Comment by Moult** [comment]
Confirming it segfaults with cgal too.

**Comment by Moult** [comment]
Bump - is there anything I can do to help debug this for the upcoming release?

**Comment by aothms** [comment]
yeah.. I typed myself up in a bit of a nasty refactor https://github.com/IfcOpenShell/IfcOpenShell/compare/v0.8.0...tfk-unify-variant-storage There's some commercial clients really pushing for better performance of the parser. Which is good this benefits us all. And the timing is also not bad. It's just a bit much all...

**Comment by Moult** [comment]
I was just typing up release notes going through commits one by one and I noticed this: https://github.com/IfcOpenShell/IfcOpenShell/commit/c2efcda7bb404d2c9139872bae0f81c160aebd7a

I this... what I think it is? It is relevant?

**Comment by Moult** [comment]
No longer segfaults with latest bot build. Here are the numbers now:

```
0.7.11-cd411e1f1
/home/dion/racbasicsampleproject.ifc
cores: 1 cgal 5.152987572015263
cores: 12 cgal 4.613600737997331
cores: 1 opencascade 7.367320151999593
cores: 12 opencascade 5.136453438026365
cores: 1 hybrid-cgal-simple-opencascade 3.266322393959854
cores: 12 hybrid-cgal-simple-opencascade 4.3777073250385
```

Seems to be improving, except for the last number?

**Comment by aothms** [comment]
> This seems odd, I'd expect the hybrid to fall back to opencascade when shapes fail with cgal

Actually the shape is not failing. But the configuration of outer vs inner bounds in the respective faces is just very peculiar. And over time the OCCT kernel has became a bit more resilient against this. The CGAL kernel is still a bit more gullible.

This is the Roof btw, which is horrible topology wise. Only 1 face with an inner bound. There should be 4, since there are two window openings baked into the brep.

```
(#17438=IfcFaceOuterBound(#17437,.T.),)
(#17454=IfcFaceOuterBound(#17453,.T.),)
(#17464=IfcFaceOuterBound(#17463,.T.),)
(#17475=IfcFaceOuterBound(#17474,.T.),)
(#17487=IfcFaceOuterBound(#17486,.T.),)
(#17498=IfcFaceOuterBound(#17497,.T.),)
(#17510=IfcFaceOuterBound(#17509,.T.),)
(#17520=IfcFaceOuterBound(#17519,.T.),)
(#17531=IfcFaceOuterBound(#17530,.T.),)
(#17541=IfcFaceOuterBound(#17540,.T.),)
(#17552=IfcFaceOuterBound(#17551,.T.),)
(#17558=IfcFaceBound(#17557,.F.),)
(#17569=IfcFaceOuterBound(#17568,.T.),)
(#17577=IfcFaceBound(#17576,.F.),)
(#17588=IfcFaceOuterBound(#17587,.T.), #17594=IfcFaceBound(#17593,.F.))
(#17606=IfcFaceOuterBound(#17605,.T.),)
(#17615=IfcFaceOuterBound(#17614,.T.),)
(#17623=IfcFaceBound(#17622,.F.),)
(#17636=IfcFaceOuterBound(#17635,.T.),)
```

> Seems to be improving, except for the last number?

If there's any improvement it's likely due to the parser rewrite which makes a bit more multi-thread friendly.

**Comment by aothms** [comment]
@Moult I've started a new build with both some more face bound lenience as well as some multi-threading rework.

**Comment by Moult** [comment]
AWESOME! Here are some tests purely in Blender:

Model | 0.7.0 | 0.8.0 OCC | 0.8.0 Hybrid
--- | --- | --- | ---
rac | 1.1 | 1.4 | 0.85
LA (62M) | 4.37 | 5.35 | 4.0
ME (98M) | 9.4 | 10.87 | 8.3
AR (342M) | 24.57 | 29.79 | Segfault with message "intersection not inside"

**Comment by Moult** [comment]
Here is the latest set of numbers. I think some Hybrid numbers have gone up because CGAL is passing more work to OCC. It seems models are either on par, or the Hybrid has a drastic improvement - perhaps this is due to the presence of dense-meshlike geometry in those models. All in all really exciting and almost getting to a state where we can enable Hybrid as the default option!

What's significant in these numbers is that from our long-standing favourite bug #841 if you remember you helped create a Blender-only geometry creator that used `get_info_2(recursive=True)` and has quite a bit of clever code that handles faceted breps, polygonal face sets, face based surface models, etc etc. For these numbers, I disabled this "Blender" native mesh code. Do you think this means that #841 can be closed once this is tested a bit more?

Model | 0.7.0 | 0.8.1 Hybrid a51ed6e
--- | --- | ---
RAC (11MB) | 1.1 | 1.1
EL (80MB) | 3.66 | 3.6
HY (82MB) | 13.37 | 4.65
LA (88MB) | 11.3 | 5
AR (117MB) | 6 | Segfault
FS (112MB) | 7.38 | 7.5
ME (151MB) | 9.44 | 9.8
AR (338MB) | 39.9 | 14.1
AR (380MB) | 22.2 | 21.8

**Comment by aothms** [comment]
> For these numbers, I disabled this "Blender" native mesh code. Do you think this means that https://github.com/IfcOpenShell/IfcOpenShell/issues/841 can be closed once this is tested a bit more?

I hope so. I think @Andrej730 brought up something valid as well. That if we disable meshing (still need to do that for faces with innerbounds probably) where possible and use the new TRIANGULATION_OUTPUT setting for ngons we might be able to shave off even more. Note that currently CGAL does not support TRIANGULATION_OUTPUT yet, but it's trivial to add there because ngons is already their datamodel anyway. Another technicality there is that we can also forgo then the conversion back from Nef to Poly which would shave off another bunch of secs when there is boolean operations involved. Question though is whether there is an efficient API in Blender to consume non-triangulated meshes?

Maybe we were too pessimistic know though in that CGAL should be able to handle adv brep with only planar underlying face surfaces. So that I committed.

Did you ever send "AR (117MB)" to me to reproduce the segfault?

**Comment by Moult** [comment]
> Question though is whether there is an efficient API in Blender to consume non-triangulated meshes?

There is. Here's how we load in to a Blender mesh below. You'll notice the hardcoding of the number 3 in a few spots because they are all tris. The closer IfcOpenShell provides something akin to this datamodel, the easier it'll be :)

```python
            num_vertices = len(geometry.verts) // 3
            total_faces = len(geometry.faces)
            loop_start = range(0, total_faces, 3)
            num_loops = total_faces // 3
            loop_total = [3] * num_loops
            num_vertex_indices = len(geometry.faces)

            mesh.vertices.add(num_vertices)
            # co [x y z x y z x y z ...]
            mesh.vertices.foreach_set("co", verts)
            mesh.loops.add(num_vertex_indices)
            # vertex_index [i i i i i ...]
            mesh.loops.foreach_set("vertex_index", geometry.faces)
            mesh.polygons.add(num_loops)
            # loop_start [0 3 6 9 ...] (for tris)
            mesh.polygons.foreach_set("loop_start", loop_start)
            # loop_total [3 3 3 3 ...] (for tris)
            mesh.polygons.foreach_set("loop_total", loop_total)
```

**Comment by Moult** [comment]
~40% improvement on average across a variety of models! Hooray!

![2024-10-11-093106_769x756_scrot](https://github.com/user-attachments/assets/3d8861b1-203b-42b7-81d7-66d271fc91b0)
