### ISSUE TITLE
Handling "#469368=IFCCARTESIANPOINT((-1.#IND,-1.#IND));"

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#492]
So, encountered such entity in a file (`IFC file generated by GRAPHISOFT ARCHICAD-64 21.0.0 INT FULL Windows version (IFC add-on version: 7000 INT FULL)`).  "#IND" doesn't look like a valid entity? These entities caused "Unable to find find keyword in schema" spam which got my attention. What would be the best way to handle these gracefully?

**Comment by hypirion** [comment]
This isn't actually an entity, but rather an attempt by the exporter to print out floating points that are NaN (`-1.#IND` or `1.#IND`). And yes, it's not legal STEP-21.

We've seen them from time to time from old Revit exporters, but they happen so rarely that it's usually easier to ask people to export with other parameters or a newer version of the exporter.

Typically there's no sensible way to recover the object that contains NaN's, except erroring out/warning and move on. There are some theoretical exceptions, e.g. if a single point is broken, you can remove the faces that contain the point and hope the result is somewhat useful. I haven't tried that, but it sounds scary to emit only "good" parts of objects.

**Comment by aothms** [comment]
> ARCHICAD-64 21

ArchiCAD 21 is just one release behind the most recent one I think. Might be worthwhile to file a bug report somewhere with them. Contrary to e.g. Revit they don't use Jotne EDM or so perhaps they have their own floating point formatting routine and apparently delegate this to MSVC's implementation of `sprintf()`.

> but it sounds scary to emit only "good" parts of objects.

That's not so different from what happens in IfcOpenShell and the other implementations. At least IfcOpenShell does so with sufficient log messages. I think a strict mode would be nice to have, but would leave output for most files empty I think.

The `#` probably trips up the lexer (IfcOpenShell does not really have one, but rather some heuristics to read through the file efficiently). A better error message can probably be generated as `#` should always follow some digits (`ENTITY_INSTANCE_NAME := "#" <DIGIT> (<DIGIT>)*`), but not sure if this is worth the effort.

**Comment by Moult** [comment]
Closing as this is a bug not in IOS but instead in someone else's software producing fundamentally invalid data.
