### ISSUE TITLE
Upgrading IFC4 into IFC4.3 file using Blender to use IFCRoad and related classes

### ISSUE THREAD

**Issue by bimpain** [IfcOpenShell/IfcOpenShell#4921]
Hello,

Can anyone please help me how can I introduce IfcRoad and related classes instead of painful "BuildingElementProxy" to my IFC model?Can I upgrade the IFC in BlenderBIM using some Python code, as it give me option but shows some python error while doing so?
I beleive If can upgrade then I can edit the class and access all of IfcRoads.
Or is there any other way to do so? PS- My IFC4 models are exported from DesiteMD Pro tool.

 Thanks in advance.
@IfcOpenBot

**Comment by Moult** [comment]
In the file open dialog when you select an IFC model you'll be given the option in the sidebar to upgrade to IFC4X3. After upgrading you can use all of IFC4X3's classes.

**Comment by bimpain** [comment]
Thank you for your Answer, I treid that before as well, but it gives me the error shown in attachment. Am I missing some patch, add-on etc.? Please help me resolve it. 
![Screenshot 2024-06-26 012205](https://github.com/IfcOpenShell/IfcOpenShell/assets/173852016/3d0b678a-6d3e-4951-a416-eb2abfee958c)

**Comment by Moult** [comment]
Can you attach your model (or share to dion@thinkmoult.com) if private?

**Comment by bimpain** [comment]
sure they are private and I just sent you two models namely: 
ifc4x3FromCivil3d
ifc4fromDesite 
the second one needs to be migrated.
