### ISSUE TITLE
enum entities in enum attributes validation

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4927]
Was noticed a failing test becase IFC4X3_RC2 schema wasn't available in v0.8.0 build and noticed that passing enum entity like `IfcBridgePartTypeEnum('DECK')` to the `IfcBridgePartTypeEnum` is considered invalid. Assigning `IfcBridgePartTypeEnum('DECK')` to the element.PredefinedType also will fail. Previously validation wasn't failing because in IFC4x3_RC2 this attribute has type `IfcFacilityPartTypeSelect` which is compiled from bunch of enums. 

And my question is - are those enum entities allowed in IFC only for attributes with a select type (where they might be necessary to prevent name clashes) or they are allowed for any enum attributes in general too and we should support them?

```python
import ifcopenshell

def validate_ifc_file(ifc_file: ifcopenshell.file, use_json=False) -> None:
    import ifcopenshell
    import ifcopenshell.validate
    import logging
    logger = logging.getLogger("validate")
    logger.setLevel(logging.DEBUG)
    ifcopenshell.validate.validate(ifc_file, logger, express_rules=False)


ifc_str = """
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2023-04-13T10:27:43',(),(),'IfcOpenShell v0.7.0-198fa67cc','IfcOpenShell v0.7.0-198fa67cc','');
FILE_SCHEMA(('IFC4X3_ADD2'));
ENDSEC;
DATA;
#1=IFCBRIDGEPART('0DYKeUG9993PtW$2icoR4v',$,$,$,$,$,$,$,$,.LATERAL.,IFCBRIDGEPARTTYPEENUM('DECK'));
#2=IFCPROJECT('3BXOBpFEDFqgWztkubS_w3',$,'My Project',$,$,$,$,$,$);
#3=IFCRELAGGREGATES('3BXOBpFEDFqgWztkubS_w4',$,$,$,#2,(#1));
ENDSEC;
END-ISO-10303-21;
"""
ifc_file = ifcopenshell.file.from_string(ifc_str)

print('validating ifc4x3_add2')
"""
For instance:
    #1=IfcBridgePart('0DYKeUG9993PtW$2icoR4v',$,$,$,$,$,$,$,$,.LATERAL.,IfcBridgePartTypeEnum('DECK'))
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
With attribute:
    <attribute PredefinedType?:
<enumeration IfcBridgePartTypeEnum: (ABUTMENT, DECK, DECK_SEGMENT, FOUNDATION, PIER, PIER_SEGMENT, PYLON, SUBSTRUCTURE, SUPERSTRUCTURE, SURFACESTRUCTURE, USERDEFINED, NOTDEFINED)>>
Value:
    IfcBridgePartTypeEnum('DECK')
Not valid
"""
validate_ifc_file(ifc_file)

ifc_str = """
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2023-04-13T10:27:43',(),(),'IfcOpenShell v0.7.0-198fa67cc','IfcOpenShell v0.7.0-198fa67cc','');
FILE_SCHEMA(('IFC4X3_RC2'));
ENDSEC;
DATA;
#1=IFCBRIDGEPART('0DYKeUG9993PtW$2icoR4v',$,$,$,$,$,$,$,$,IFCBRIDGEPARTTYPEENUM('DECK'),.LATERAL.);
#2=IFCPROJECT('3BXOBpFEDFqgWztkubS_w3',$,'My Project',$,$,$,$,$,$);
#3=IFCRELAGGREGATES('3BXOBpFEDFqgWztkubS_w4',$,$,$,#2,(#1));
ENDSEC;
END-ISO-10303-21;
"""

ifc_file = ifcopenshell.file.from_string(ifc_str)
print('validating ifc4x3_rc2')
validate_ifc_file(ifc_file)
```

**Comment by aothms** [comment]
> or they are allowed for any enum attributes in general too and we should support them?

This is indeed a bit of SPF serialization detail leaking into the way the code base is structured which is unfortunate. But this kind of syntax is **only valid** when it is a SELECT type that involves a simple type or enum. In IfcOpenShell simple types are immediately flattened to their literal values and don't have a "boxed" schema type around them, unless in this specific case when they are a select in the schema, such as the IfcValue in IfcProperty, or this one of snapshot in time when the Facility PredefinedType was actually a SELECT of ENUM. https://github.com/buildingSMART/IFC4.3.x-development/issues/90

**Comment by Andrej730** [comment]
Turned out this is a very rare case and there is just 1 similar attribute with a select type + enum across ifc2x3, ifc4 and ifc4x3 and it's `IfcPresentationStyleAssignment.Styles` and I've migrated the test to use it instead of ifc4x3_rc4.
