### ISSUE TITLE
windows compile script, error in powershell on downloading boost

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#493]
on executing the compile script on windows I got on downloading boost the following powershell error. I have no glue. Since I normaly use bash an Linux shell it is quite difficault to debugg ... 

If this matters, I am on win 7 ultimate in a virtual machine on VirtualBox

`
C:\Users\nutzer\Desktop\ifcos\ifcosdev\win>build-deps.cmd "Visual Studio 15 2017 Win64"

This script fetches and builds all IfcOpenShell dependencies

build-type-cfg.cmd: Warning: BUILD_CFG not specified - using the default RelWithDebInfo

Script configuration:
* CMake Generator       = `Visual Studio 15 2017 Win64`
  - Passed to CMake -G option.
* Target Architecture   = x64
  - Whether were doing 32-bit (x86) or 64-bit (x64) build.
* Dependency Directory  = C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps
  - The directory where IfcOpenShell dependencies are fetched and built.
* Installation Directory = C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps-vs2017-x64-installed
  - The directory where IfcOpenShell dependencies are installed.
* Build Config Type     = RelWithDebInfo
  - The used build configuration type for the dependencies.
    Defaults to RelWithDebInfo if not specified.
* Build Type            = Build
  - The used build type for the dependencies (Build, Rebuild, Clean).
    Defaults to Build if not specified. Rebuild/Clean also uninstalls Python (if it was installed by this script).
* IFCOS_USE_OCCT        = TRUE
  - Use the official Open CASCADE instead of the community edition.
* IFCOS_INSTALL_PYTHON  = TRUE
  - Download and install Python.
    Set to something other than TRUE if you wish to use an already installed version of Python.
* IFCOS_USE_PYTHON2     = TRUE
  - Use Python 2 instead of 3.
    Set to TRUE if you wish to use Python 2 instead of 3. Has no effect if IFCOS_INSTALL_PYTHON is not TRUE.
* IFCOS_NUM_BUILD_PROCS = 1
  - How many MSBuild.exe processes may be run in parallel.
    Defaults to NUMBER_OF_PROCESSORS. Used also by other IfcOpenShell build scripts.

Requirements for a successful execution:
 1. Install PowerShell (preinstalled in Windows >= 7) and make sure 'powershell' is accessible from PATH.
  - https://support.microsoft.com/en-us/kb/968929
 2. Install Git and make sure 'git' is accessible from PATH.
  - https://git-for-windows.github.io/
 3. Install CMake and make sure 'cmake' is accessible from PATH.
  - http://www.cmake.org/
 4. Visual Studio 2008 or newer (2013 or newer recommended) with C++ toolset.
  - https://www.visualstudio.com/
 5. Run this batch script with Visual Studio environment variables set.
  - https://msdn.microsoft.com/en-us/library/ms229859(v=vs.110).aspx

Warning: You will need roughly 8 GB of disk space to proceed (VS 2015 x64 RelWithDebInfo).

If you are not ready with the above: type 'n' in the prompt below. Build proceeds on all other inputs
>

Build started at 20:19:35.76.

Downloading Boost 1.67.0 into C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps.
Ausnahme beim Festlegen von "SecurityProtocol": "NULL kann aufgrund von ungültigen Enumerationswerten nicht in den Typ "System.Net.SecurityProtocolType" konvertiert werden. Geben
Sie einen der folgenden Enumerationswerte an, und versuchen Sie es erneut. Mögliche Enumerationswerte sind "Ssl3, Tls"."
Bei Zeile:1 Zeichen:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; $webClient = new-object System.Net.WebClient; $webClient.Proxy.Credentials =
 [System.Net.CredentialCache]::DefaultNetworkCredentials; $webClient.DownloadFile('https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.7z', 'boost_1_67_0.7z')
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Ausnahme beim Aufrufen von "DownloadFile" mit 2 Argument(en):  "Die zugrunde liegende Verbindung wurde geschlossen: Unerwarteter Fehler beim Senden.."
Bei Zeile:1 Zeichen:253
+ [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; $webClient = new-object System.Net.WebClient; $webClient.Proxy.Credentials = [Syst
em.Net.CredentialCache]::DefaultNetworkCredentials; $webClient.DownloadFile <<<< ('https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.7z', 'boost_1_67_0.7z')
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

An error occurred

Build ended at 20:19:37.06. Time elapsed 0:00:01.30.

C:\Users\nutzer\Desktop\ifcos\ifcosdev\win>
`

**Comment by berndhahnebach** [comment]
ahh ok I will update the powershell and report back.

bernd

**Comment by Stinkfist0** [comment]
Great to hear. We should probably add the discussed PowerShell version check to to the build script at some point.

**Comment by aothms** [comment]
> add the discussed PowerShell version check

@Stinkfist0 Do you still remember where that was written down?

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/commit/116de5daec696b36edfc9135519506f9bbdc44fc
