### ISSUE TITLE
IfcGeom::Kernel::fold_layers: How to handle "other_wall" without Axis representation

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#494]
Currently `IfcConvert --enable-layerset-slicing` crashes to null pointer access in https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomFunctions.cpp#L1833on my test file (can provide it if needed).

What would be proper way to handle this? Log error and `continue`? The root cause might be #492 however.

**Comment by aothms** [comment]
Yuk, null pointers.

> Log error and continue?

Yeah this is in `fold_layers()` so that means at that point they won't make a connection to that wall.

https://github.com/IfcOpenShell/IfcOpenShell/commit/4ed9166e8a12db693fc5b789f2345ef3c6eede22

**Comment by Stinkfist0** [comment]
Thanks!
