### ISSUE TITLE
IFC-Tester - possible issue regarding Regex-Codes in ids checks

### ISSUE THREAD

**Issue by don-matteo** [IfcOpenShell/IfcOpenShell#4944]
1) open the attached ifc-file named "**IDS Test.ifc**"

2)as you can see, that's an ifc file (Ifc 2x3) with two walls, both do have the custom pset Pset-LH and a "Typname"
the first wall is named correctly "**WA-I-NTR-GKB-151**"
the second is not named correctly "**WA-NTR-GKB-151**"

then there are 4 ids files, I checked the ifc file with all of them.

Because I wasn't sure about the correctness of my Regex-Codes I did cross check the codes on https://regex101.com

Here the results of the ids-checks, expected result and achieved result:
**PSet-LH-check-Typname-exact-code.ids**
checks if the Typname is named "WA-I-NTR-GKB-151"
expeted 50%
result: 50%

**PSet-LH-check-Typname-exact-start.ids**
checks if the Typname is named like "^WA-.*" which means, that the Typname has to start with "WA-"
expected: 100%
achieved 0%

**PSet-LH-check-Typname-simple.ids**
checks if the Typname is named like "^[A-Z]{2}-.*" which means, that the Typname has to start with "??-"
expected 100%
achieved 0%

**PSet-LH-check-Typname.ids**
checks if the Typname is named like "^[A-Z]{2}-[A-Z]-[A-Z]{3}-[A-Z]{3}.*" which means, that the Typname has to start with "??-?-???-???"
expected 50%
achieved 0%

[Archiv.zip](https://github.com/user-attachments/files/16028168/Archiv.zip)

**Comment by Moult** [comment]
Your IDS is invalid. Regex patterns have to use the "Restriction" capability in IDS, something like this:

```
                        <xs:restriction base="xs:string">
                            <xs:pattern value="Foo.*" />
                        </xs:restriction>
```

Whereas your IDS has just simple values:

```
<ids:simpleValue>^WA-.*</ids:simpleValue>
```

**Comment by don-matteo** [comment]
so <xs:restriction base="xs:string"><xs:pattern value="[A-Z]{2}-[A-Z]-[A-Z]{3}-[A-Z]{3}.*" /></xs:restriction>
will be checking all codes whicht are like **??-?-???-???***  ?

**Comment by don-matteo** [comment]
which IDS Editor would you recommend me for not having to write the xml-code by myself?

**Comment by Moult** [comment]
Maybe @bimvoice can recommend a platform? If you're OK with writing code, IfcTester can generate IDS XML for you. There is a current GSoC project underway to create a web UI to author and edit IDS but expect to wait another few months before its ready.

**Comment by BIMvoice** [comment]
I use and recommend ACCA. If they have a bug in the generated IDSs, this is a good opportunity for them to improve. I'll forward it to them.

**Comment by don-matteo** [comment]
Brilliant Petru, @BIMvoice, in fact I did upload the ids file with the modifications Dion told me on ACCA. There the ids-file has been declared as faulty. So that might be an ACCA usbim-issue.

**Comment by don-matteo** [comment]
thank you @giuseppeverduciALMA 
What does that mean to me?
1) I have to consider special things, when I want to create a requirement in usBIM which containts Regex?
2) I have to wait until I can create requirements with Regex im usBIM?

**Comment by giuseppeverduciALMA** [comment]
No, just to suggest that you need to add the data type to the property facet and to inform you that we will improve regular expression checking in future versions.

thanks

**Comment by don-matteo** [comment]
seems to work again, no problems any more

**Comment by Moult** [comment]
That error means that you didn't select or didn't browse to an IFC model. Maybe the file path was wrong or similar. I've also hit that issue when downloading IFCs from Autodesk Cloud - they give downloads with permissions blanked out on Linux so `chmod 644` fixes it (maybe relevant to Mac too?) - no idea where to report ACC bugs though.

**Comment by don-matteo** [comment]
yeah, had an empty ifc file because I made some tests to a vectorworks-ifc-export issue, that's been the reason

unfortunately i replaced the ifc file with a new one and blenderbim got that change only after restarting blender (seams to me)
