### ISSUE TITLE
Draw wall and wall polyline tool

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4954]
This is a good issue for a new developer and can be built isolated from BBIM at first.

After 5 years we don't have a tool where you can click a point, click another, and a wall appears between those two points (or click many points to create a polyline where walls are created and auto join to neighbouring walls etc). This is embarassing :)

This is a pure UI exercise to design an interface that allows this tracking of "has clicked point", "has clicked second point" to allow users to draw a single wall or chain of walls. There should be decorators that show that you are in "select point" mode, as well as angle snapping (with custom angles), snapping to existing elements in the model, auto join, snap to Z value of active container (walls are based on 2D axes), etc.

In theory, all the components are there to do this. We have functions for wall creation, wall extension, wall from 2 point, wall joins, etc. We also have decorators which can largely be copy pasted. We don't have any snapping code.

Anybody tackling this give me a buzz before starting so we can chat :)

**Comment by hydromac** [comment]
It would be good if it was a tool not only for drawing walls, but also for any type of linear object, e.g. pipelines, HVAC ducts, electrical lines, etc. I suggest that already at this stage we consider that it should be a class extending the class of a given object with the possibility of drawing it either:
1. from point to point,
2. 2. after clicking a line/polyline;
; and depending on the type of object in which it is implemented, it should have, among others, the functions mentioned, such as for walls, snapping Z (wall height) to the ceiling or roof and automatic generation of a space object (ifcSpace) when walls with floor and ceiling form a closed body, in the case of pressure pipes, drawing them along the pipe axis, in the case of gravity flow pipes, the baseline is the inner bottom of the pipe and additionally drawing with a specified slope for a given standardized pipe diameter, etc. Such modified tools would be more user-friendly when modeling BIM objects using Bonsai.

**Comment by Moult** [comment]
Indeed, it will be coded in a way that is generic and reusable to be then used across a range of tools (slabs, beams, roofs, measurement tools, MEP segments, space boundary drawings, etc) - drawing walls is just the first implementation.

**Comment by Moult** [comment]
Closing as this is now implemented. Other separate bugs now track individual improvements.
