### ISSUE TITLE
windows compile script, command ".\b2" not known, error in powershell on building boost

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#496]
new problem arises ... in follow up of https://github.com/IfcOpenShell/IfcOpenShell/issues/493

If you are not ready with the above: type 'n' in the prompt below. Build proceeds on all other inputs
>

Build started at 20:46:13.61.

Boost 1.67.0 already downloaded. Skipping.
Boost 1.67.0 already extracted into C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps\boost_1_67_0. Skipping.
Building Boost build script.
Building Boost.Build engine
cl : Befehlszeile warning D9035 : Die Option "GZ" ist veraltet und wird in einer der nächsten Versionen entfernt.
cl : Befehlszeile warning D9036 : "RTC1" anstelle von "GZ" verwenden
cl : Befehlszeile warning D9002 : Unbekannte Option "/MLd" wird ignoriert.

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

Building Boost 1.67.0 --with-system --with-regex --with-thread --with-program_options --with-date_time --with-iostreams --with-filesystem Please be patient this will take a while.
Der Befehl ".\b2" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

An error occurred

Build ended at 20:46:20.92. Time elapsed 0:00:07.31.

C:\Users\nutzer\Desktop\ifcos\ifcosdev\win>

**Comment by aothms** [comment]
I am quite clueless as to why this would happen, but seems more people are running into this e.g. https://github.com/Microsoft/vcpkg/issues/3412 https://svn.boost.org/trac10/ticket/13157 

Do you get the same issue if you upgrade the boost version to 1.68 here https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L152 ?

**Comment by berndhahnebach** [comment]
@thomas, no thats not the problem. 

> Der Befehl ".\b2" ist entweder falsch geschrieben oder
> konnte nicht gefunden werden.
> 
> An error occurre

I neither do know what the command .\b2 should do nor why this is not known by my Powershell.

Might be this line in build script:
https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L194

**Comment by berndhahnebach** [comment]
ahh the error means:
The command  ".\b2" is missspelled or could not be found. An error occurre

**Comment by aothms** [comment]
> no thats not the problem.

The source of the problem are these messages before that e.g. `Failed to build Boost.Build engine.` and probably these unknown options are indicative of that. I.e. the problem is here [1]

> command .\b2 should do nor why this is not known by my Powershell

b2 is the Boost.Build engine and should have been created by this `bootstrap` command.

That's why I suggested to try a more recent boost version as perhaps it got fixed from their side, but I didn't hear back whether that had helped.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L179

**Comment by berndhahnebach** [comment]
thanks thomas for explaining this ... 

> Do you get the same issue if you upgrade the boost version to 1.68 here https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L152 ?

yes ...

`
If you are not ready with the above: type 'n' in the prompt below. Build proceeds on all other inputs
>

Build started at 21:15:37.21.

Downloading Boost 1.68.0 into C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps.
Extracting Boost 1.68.0 into C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps.
Building Boost build script.
Building Boost.Build engine
cl : Befehlszeile warning D9035 : Die Option "GZ" ist veraltet und wird in einer der nächsten Versionen entfernt.
cl : Befehlszeile warning D9036 : "RTC1" anstelle von "GZ" verwenden
cl : Befehlszeile warning D9002 : Unbekannte Option "/MLd" wird ignoriert.

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

Building Boost 1.68.0 --with-system --with-regex --with-thread --with-program_options --with-date_time --with-iostreams --with-filesystem Please be patient this will take a while.
Der Befehl ".\b2" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

An error occurred

Build ended at 21:18:14.11. Time elapsed 0:02:36.90.

C:\Users\nutzer\Desktop\ifcos\ifcosdev\win>
`

**Comment by Stinkfist0** [comment]
Hmm, I have a faint recollection that when I encountered this problem https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L155 the output might have looked similar.

**Comment by aothms** [comment]
In #515 was reported that building boost failed on a path with spaces. Turns out `DEPENDENCY_DIR` was getting quoted twice and somehow that caused the build to fail only if there were spaces in the path. Well, quoting in the windows shell is known have it's peculiarities. For lack of a better idea, can you quickly check @berndhahnebach if https://github.com/IfcOpenShell/IfcOpenShell/commit/a8f4f0270a5ef550fc384d593b0b9bc17d740b0b also affects your usage?

**Comment by berndhahnebach** [comment]
more informations ...

I only have VS 2017 community installed.

Tried with latest master, a0f37cf (which includes the commit you mentioned thomas), same problem, tried with boost 1.68 too, same problem.

Should I try to install an older compiler? Are there precompiled library packages available? This would make all this compiling a lot easier. Like on Linux. There I only need to compile IfcOpenShell, all other packages could be installed precompiled. 

bernd

**Comment by aothms** [comment]
> I only have VS 2017 community installed.

Me too.

I recently updated my MSVC. Which made me able to reproduce some more issues others were having. I will have another look at your too.

There are precompiled boost libraries available for Windows: https://sourceforge.net/projects/boost/files/boost-binaries/1.68.0/

But you'll have to manually adjust the build scripts to skip boost and set the correct directories for CMake.

You're probably looking for the IfcOpenShell-Python packages. Not sure if you intend to make changes to the source yourself. Note that there are also (almost) daily builds available: https://github.com/IfcOpenBot/IfcOpenShell/commit/a0f37cf9ea0059c73783f1995b633e811a846373#commitcomment-31688901

**Comment by aothms** [comment]
I get somewhat similar output, but still the process is successful 

~~~
Building Boost.Build engine
cl : Command line warning D9035 : option 'GZ' has been deprecated and will be removed in a future release
cl : Command line warning D9036 : use 'RTC1' instead of 'GZ'
cl : Command line warning D9002 : ignoring unknown option '/MLd'

Bootstrapping is done. To build, run:

    .\b2
~~~

Did you ever take a look at this bootstrap.log mentioned in your output? (`Please consult bootstrap.log for further diagnostics.`)

At the end of the day this is really just the Boost build script. There's only so much I can do.

**Comment by aothms** [comment]
> I recently updated my MSVC

Btw. maybe something for you to try as well. Seems there is tremendous differences now between minor subsequent msvc releases.

**Comment by berndhahnebach** [comment]
> You're probably looking for the IfcOpenShell-Python packages. Not sure if you intend to make changes to the source yourself. Note that there are also (almost) daily builds available: [IfcOpenBot@a0f37cf#commitcomment-31688901](https://github.com/IfcOpenBot/IfcOpenShell/commit/a0f37cf9ea0059c73783f1995b633e811a846373#commitcomment-31688901)

Yes I am. My development for IfcOpenShell takes place on Linux only. I only need them for FreeCAD because the ones we gone deliver with FreeCAD for windows are more than two years old already. I did not know such a Bot exists. This is excellent. This really helps a lot to use uptodate IfcOpenShell on FreeCAD windows. 

Ahh happy new year Thomas.

cheers bernd

**Comment by berndhahnebach** [comment]
bootstrab.log

`
###
### Using 'msvc' toolset.
###

C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine>if exist bootstrap rd /S /Q bootstrap 

C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine>md bootstrap 

C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine>cl /nologo /GZ /Zi /MLd /Fobootstrap/ /Fdbootstrap/ -DNT -DYYDEBUG kernel32.lib advapi32.lib user32.lib /Febootstrap\jam0  command.c compile.c constants.c debug.c execcmd.c execnt.c filent.c frames.c function.c glob.c hash.c hdrmacro.c headers.c jam.c jambase.c jamgram.c lists.c make.c make1.c object.c option.c output.c parse.c pathnt.c pathsys.c regexp.c rules.c scan.c search.c subst.c timestamp.c variable.c modules.c strings.c filesys.c builtins.c md5.c class.c cwd.c w32_getreg.c native.c modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c modules/order.c 
command.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
compile.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
constants.c
debug.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
execcmd.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
execnt.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
filent.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
frames.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
function.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
glob.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
hash.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
hdrmacro.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
headers.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
jam.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
jambase.c
jamgram.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
lists.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
make.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
make1.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
object.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
Code wird generiert...
Kompilieren...
option.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
output.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
parse.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
pathnt.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
pathsys.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
regexp.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
rules.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
scan.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
search.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
subst.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
timestamp.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
variable.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
modules.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
strings.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
filesys.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
builtins.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
md5.c
md5.c(55): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "string.h": No such file or directory
class.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\strings.h(11): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "stddef.h": No such file or directory
cwd.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
w32_getreg.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\jam.h(71): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "ctype.h": No such file or directory
Code wird generiert...
Kompilieren...
native.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\strings.h(11): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "stddef.h": No such file or directory
set.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\strings.h(11): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "stddef.h": No such file or directory
path.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\strings.h(11): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "stddef.h": No such file or directory
regex.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\modules\../mem.h(67): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "stdlib.h": No such file or directory
property-set.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\strings.h(11): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "stddef.h": No such file or directory
sequence.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\strings.h(11): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "stddef.h": No such file or directory
order.c
c:\users\nutzer\desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine\modules\../mem.h(67): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "stdlib.h": No such file or directory
Code wird generiert...

C:\Users\nutzer\Desktop\ifcos\ifcosdev\deps\boost_1_68_0\tools\build\src\engine>exit /b 2 

`

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=39&t=32895

**Comment by aothms** [comment]
@berndhahnebach Judging from the error message, I think this issue is close to what you are experiencing: https://stackoverflow.com/a/42258579/1556435

Copy pasting from the various answers it seems like you need to reinstall MVSC 2017 and the "Windows Universal CRT SDK" component.

**Comment by berndhahnebach** [comment]
Ahh cool, I may give it another try anyway :)
