### ISSUE TITLE
IfcArcIndex is inverted in v0.8.0

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4960]
Here's a sample file:

[slab.txt](https://github.com/user-attachments/files/16054091/slab.txt)

It should look like this (v0.7.0)

![2024-07-02-000926_373x366_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/e78118af-62ce-486d-9c1a-ffdd59dc1741)

But it looks like this:

![2024-07-02-000550_456x435_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/d007070b-e756-4d04-aa69-b5924dc9c3b8)

**Comment by Moult** [comment]
Oh, whoops I might have an old bot build. I think it is fixed now? Or is it intermittent?

**Comment by aothms** [comment]
Yes this looks ok on my end.

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/272edb77-0ff0-4a07-b800-f4b073e2eaf4)
