### ISSUE TITLE
 Has ifcopenshell 0.8.0 become the official version?

### ISSUE THREAD

**Issue by Pdongjaelee** [IfcOpenShell/IfcOpenShell#4963]
Has ifcopenshell 0.8.0 become the official version?

I'm waiting to use ifcconvert, which changes 0.8.0's ifc to cityjson.

**Comment by Moult** [comment]
It is now the official version :)

**Comment by Pdongjaelee** [comment]
Oh, congratulations on the official version.

Is it possible to download the newly updated 0.8.0 version of ifcconvert as an exe file like the link below?
https://github.com/IfcOpenBot/IfcOpenShell/commit/0d3c73de822d1b11ebc31e21d3b946e2df15d30b#commitcomment-139858841

**Comment by Moult** [comment]
https://github.com/IfcOpenBot/IfcOpenShell/commit/c18e4ea6ced759a9b09ef99fb590b5b4d12fd5a0#comments

**Comment by Pdongjaelee** [comment]
Converting ifc to cityjson still doesn't work well.


2024년 7월 9일 (화) 오전 10:24, Dion Moult ***@***.***>님이 작성:
