### ISSUE TITLE
Problems with Quantity take offs.

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4964]
![Skermskoot (126)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/e8a1050c-c2d1-45f0-9746-509392e3b600)
![Skermskoot (127)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/4cde2cbb-725a-4ba4-b9e8-79a330861cb8)
[HFCC-Chrech Toilet.txt](https://github.com/user-attachments/files/16064176/HFCC-Chrech.Toilet.txt)
Please find attached the two screenshots from the attached IFC file.
I am trying to get a Budget for this small project but not all the quantities are correct. Could you please advise what I am doing wrong?
I am using blenderbim-0.7.9.240701-py311-win with Blender 4.1, this problem was also with the stable version 240602.

I don't know why but I also lost all my aggregations between 240602 and 240701?

Thanks for your assistance and effort, stay strong.

**Comment by Moult** [comment]
How did you run your calculations? Keep in mind qto calculations are not live-updated, you need to explicitly run a qto calculation to update the values. For example, if I click that wall and do Shift-Q I get the correct quantities.

(Note I did find a minor bug in the latest unstable which I will fix shortly)

Also your aggregates haven't been lost. They just aren't shown in the outliner that way. We'll be building a new way to visualise aggregates. The outliner will now be flattened.

**Comment by Ave-5D** [comment]
\0/ thanks, knew I was doing something wrong.

I am still doing something wrong-got this error message, will try again after closing Blender
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.7.9.240701
last_actions: 
# ifcopenshell.api: pset.edit_qto
>>> {"qto": {"cast_type": "entity_instance", "value": 34708, "Name": "Qto_FootingBaseQuantities"}, "name": "Qto_FootingBaseQuantities", "properties": "{'Length': 0.0, 'Width': 0.0, 'Height': 0.0, 'CrossSectionArea': 0.0, 'OuterSurfaceArea': 0.0, 'GrossSurfaceArea': 0.0, 'GrossVolume': 0.0, 'NetVolume': 0.0, 'GrossWeight': 0.0, 'NetWeight': 0.0}"}
# operator: BIM_OT_disable_pset_editing
# operator: BIM_OT_toggle_pset_expansion
# operator: BIM_OT_toggle_pset_expansion
# operator: BIM_OT_edit_pset
# ifcopenshell.api: pset.edit_qto
>>> {"qto": {"cast_type": "entity_instance", "value": 13847, "Name": "Qto_WallBaseQuantities"}, "name": "Qto_WallBaseQuantities", "properties": "{'Length': 1764.047, 'Width': 220.0, 'Height': 3009.803, 'GrossFootprintArea': 0.388, 'NetFootprintArea': 0.388, 'GrossSideArea': 5.3094, 'NetSideArea': 5.2575, 'GrossVolume': 1.1681, 'NetVolume': 1.1567, 'GrossWeight': None, 'NetWeight': None}"}
# operator: BIM_OT_disable_pset_editing
# operator: BIM_OT_perform_quantity_take_off
# ifcopenshell.api: pset.edit_qto
>>> {"qto": {"cast_type": "entity_instance", "value": 13847, "Name": "Qto_WallBaseQuantities"}, "properties": "{'GrossSideArea': 0.44101172513901504, 'GrossVolume': 0.09702257953058331, 'Height': 250.0, 'Length': 1764.04690055606, 'NetSideArea': 0.44101172513901504, 'NetVolume': 0.09702257953058331, 'Width': 220.0}"}
# operator: BIM_OT_perform_quantity_take_off
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\qto\operator.py", line 163, in _execute
    results = ifc5d.qto.quantify(ifc_file, elements, rules)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifc5d\qto.py", line 46, in quantify
    calculator.calculate(ifc_file, filtered_elements, qtos, results)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifc5d\qto.py", line 190, in calculate
    formula_functions[formula](shape.geometry), IfcOpenShell.raw_functions[formula].measure
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'get_max_xy'

ifc: HFCC-Chrech Toilet.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.9.240701-0f8f641
```

**Comment by Moult** [comment]
Yeah that was the bug I was referring to - fixed now. Should only affect the unstable release. Slowly adding more quantities :)

**Comment by Ave-5D** [comment]
Thanks Deon, I tried the new realise and both the W310 and W311 does not create a BIM tab in Blender, I will be using an older release and try again later.
Once again thanks for the effort.
