### ISSUE TITLE
无法打开python.h

### ISSUE THREAD

**Issue by liaoweiqi1997** [IfcOpenShell/IfcOpenShell#497]
![image](https://user-images.githubusercontent.com/31244684/48055355-5cc7e080-e1ea-11e8-9ca4-3705d76c9f9f.png)

**Comment by aothms** [comment]
When you generate the project files using CMake, CMake will take care of finding the Python libraries and include directory. Did you use the windows build script [1]? Then there is likely a Python installation in `\deps-vs2017-x64-installed\Python34`. Is there?

[1] https://github.com/IfcOpenShell/IfcOpenShell/tree/master/win
