### ISSUE TITLE
Parametric Geometry-Array

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4973]
Hi

I have a question regarding the array.

Why does the model Y direction not equal the Geometry Y value but the X value?
As per the attached screen shot.

Once again, many thanks for your effort.

![Skermskoot (131)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/e5be1e0f-0c7a-428a-9e3b-3042e6b5e9ac)

**Comment by theoryshaw** [comment]
uncheck this so it uses 'world space'. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9c7b56be-91da-42bf-ad7b-904adb0aa235)

**Comment by Ave-5D** [comment]
:-), thanks
