### ISSUE TITLE
IfcTrimmedCurve with BasisCurve IfcTrimmedCurve

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#498]
Hi and thanks for the great work.

i have a model from revit 2019. They use an IfcTrimmedCurve as a base curve of IfcTrimmedCurve. In my opinion it dosn't make sense.

But revit do it. And it is IFC conform.

So the question is, why in IfcOpenshell IfcTrimmedCurve creates a wire instead of a  Geom_TrimmedCurve?

XBIM handles it like this way:

 void XbimCurve::Init(IIfcTrimmedCurve^ curve)
		{
			Init(curve->BasisCurve);
			if(IsValid)
			{
				//check if we have an ellipse in case we have to correct axis
				IIfcEllipse^ ellipse = dynamic_cast<IIfcEllipse^>(curve->BasisCurve);
				bool rotateEllipse = false;
				
				bool isConic = (dynamic_cast<IIfcConic^>(curve->BasisCurve) != nullptr);					
				double parameterFactor = isConic ? curve->Model->ModelFactors->AngleToRadiansConversionFactor : 1;
				double precision = curve->Model->ModelFactors->Precision;
				bool trim_cartesian = (curve->MasterRepresentation == IfcTrimmingPreference::CARTESIAN);
						
				double u1;
				gp_Pnt p1;
				bool u1Found, u2Found, p1Found, p2Found;
				double u2;
				gp_Pnt p2;
				for each (IIfcTrimmingSelect^ trim in curve->Trim1)
				{
					if (dynamic_cast<IIfcCartesianPoint^>(trim))
					{						
						p1=XbimConvert::GetPoint3d((IIfcCartesianPoint^)trim);						
						p1Found = true;
					}
					else if (dynamic_cast<Xbim::Ifc4::MeasureResource::IfcParameterValue^>(trim))
					{					
						u1 = (Xbim::Ifc4::MeasureResource::IfcParameterValue)trim;
						if (isConic) u1 *= parameterFactor; //correct to radians
						u1Found = true;
					}
				}
				for each (IIfcTrimmingSelect^ trim in curve->Trim2)
				{
					if (dynamic_cast<IIfcCartesianPoint^>(trim))
					{
						p2 = XbimConvert::GetPoint3d((IIfcCartesianPoint^)trim);
						p2Found = true;
					}
					else if (dynamic_cast<Xbim::Ifc4::MeasureResource::IfcParameterValue^>(trim))
					{
						u2 = (Xbim::Ifc4::MeasureResource::IfcParameterValue)trim;
						if (isConic) u2 *= parameterFactor; //correct to radians
						u2Found = true;
					}
				}
				if(trim_cartesian) //if we prefer cartesian and we have the points override the parameters
				{
					if(p1Found)	 GeomLib_Tool::Parameter(*pCurve, p1, precision,u1);
					if(p2Found)  GeomLib_Tool::Parameter(*pCurve, p2, precision, u2);
				}
				else //if we prefer parameters or don't care, use u1 nad u2 unless we don't have them
				{
					if (!u1Found)  GeomLib_Tool::Parameter(*pCurve, p1, precision, u1);
					if (!u2Found)  GeomLib_Tool::Parameter(*pCurve, p2, precision, u2);
				}
				//now just go with
				*pCurve = new Geom_TrimmedCurve(*pCurve, u1, u2, curve->SenseAgreement);
			}
		}

kind regards

Christian

**Comment by ninichki** [comment]
Hi,
sorry for my late replay.
But I tried to get the shape as own model.
The whole model is a model from our customers. So I can't make it public. But the customer told me to give me a small model.

kind regards,

Christian

**Comment by aothms** [comment]
>  The whole model is a model from our customers. So I can't make it public. But the customer told me to give me a small model.

I understand. Created something myself [1] but would still be great if at some point you can share something.

Created a quick fix for this approximating the BasisCurve as a bspline.

[1] https://github.com/IfcOpenShell/files/blob/master/trimmed_polyline.ifc

**Comment by ninichki** [comment]
Oh nice,
I will check it out, how it works.
thank you
