### ISSUE TITLE
IFCOPENSHELL Installation error

### ISSUE THREAD

**Issue by sabinslash** [IfcOpenShell/IfcOpenShell#4983]
Hi, While installing ifcopenshell, it doesn't allow me to install ifcopenshell. I am having 'mathutils' error and says MS Visual C++ 14.0 or greater is required even though I have MS Visual C++ 15.0.

![ifcopenshell](https://github.com/IfcOpenShell/IfcOpenShell/assets/115484368/13c81c57-2e29-4b1e-a675-68d2e0ae4995)
Can anyone help me with this issue?

**Comment by steverugi** [comment]
it happens on my computer too, it would be useful to understand why

**Comment by Moult** [comment]
This is an issue with mathutils, and for now we've made it an optional dependency but haven't yet bumped the build. Still waiting on chocolatey's workflow (ping @ay-ex ) to be finished and then we can do a test release across all channels.

**Comment by sabinslash** [comment]
Thank you Dion for the reply, hopefully it gets fixed soon.

**Comment by Moult** [comment]
This should now be fixed
