### ISSUE TITLE
IfcTester check ifc version?

### ISSUE THREAD

**Issue by Kickdak** [IfcOpenShell/IfcOpenShell#4986]
Hey,

Is there a way to make a check for the IFC version with the ids?
I have run the IDS on a 2x3 file, im trying to check that the file is in IFC4 but cant find any paramters that stores the value.
Since the data is specified in the metadata, maybe the tester can check for it and generate it into the html?

```
<ids:specifications>
    <ids:specification ifcVersion="IFC4" name="Check IFC version (IFC4)" description="Beskrivelse: IFC4 is an extension of 2x3" instructions="Veiledning: Add something here">
      <ids:applicability minOccurs="1" maxOccurs="unbounded">
        <ids:entity>
          <ids:name>
            <ids:simpleValue>IFCPROJECT</ids:simpleValue>
          </ids:name>
        </ids:entity>
      </ids:applicability>
      <ids:requirements>
        <ids:property dataType="IFCTEXT" cardinality="required">
          <ids:propertySet>
            <ids:simpleValue>FILE_SCHEMA</ids:simpleValue>
          </ids:propertySet>
          <ids:baseName>
            <ids:simpleValue>schema_name</ids:simpleValue>
          </ids:baseName>
          <ids:value>
            <ids:simpleValue>IFC4</ids:simpleValue>
          </ids:value>
        </ids:property>
      </ids:requirements>
    </ids:specification>
```

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/44496037/e7b72ac1-5966-42f0-8ff6-b558c6847427)

**Comment by Moult** [comment]
The current behaviour of IDS is that the version is metadata and doesn't affect pass / fail results:

https://github.com/buildingSMART/IDS/blob/development/Documentation/testcases/ids/pass-specification_version_is_purely_metadata_and_does_not_impact_pass_or_fail_result.ids

https://github.com/buildingSMART/IDS/blob/development/Documentation/testcases/ids/pass-specification_version_is_purely_metadata_and_does_not_impact_pass_or_fail_result.ifc

That said, we can indeed show a warning. Will do :)
