### ISSUE TITLE
ShapeBuilder.polyline problem

### ISSUE THREAD

**Issue by VDobranov** [IfcOpenShell/IfcOpenShell#4989]
Hi!
I’ve found an issue with the polyline function of the ShapeBuilder class: if one wants to get a closed polyline that ends with an arc, the fucntion gives erroneous results.

For example, I need to have this polyline:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/2d5caaef-5d14-47c9-8f37-4a0a549d71c2)
I am feeding the ShapeBuilder.polyline with all the points and the indexes of arcs’ middles: 4 and 8.
Then expect to get this result (see the last arc uses the 1st point):
```ifc
#92=IFCCARTESIANPOINTLIST2D(((1000.,2000.),(3000.,2000.),(3000.,300.),(2787.86796564404,212.132034355964),(2700.,0.),(0.,0.),(0.,1000.),(292.893218813453,1707.10678118655)));
#93=IFCINDEXEDPOLYCURVE(#92,(IFCLINEINDEX((1,2,3)),IFCARCINDEX((3,4,5)),IFCLINEINDEX((5,6,7)),IFCARCINDEX((7,8,1))),.F.);
```

But current version gives this:
```ifc
#92=IFCCARTESIANPOINTLIST2D(((1000.,2000.),(3000.,2000.),(3000.,300.),(2787.86796564404,212.132034355964),(2700.,0.),(0.,0.),(0.,1000.),(292.893218813453,1707.10678118655)));
#93=IFCINDEXEDPOLYCURVE(#92,(IFCLINEINDEX((1,2,3)),IFCARCINDEX((3,4,5)),IFCLINEINDEX((5,6,7)),IFCARCINDEX((7,8,9)),IFCLINEINDEX((8,1))),.F.);
```

It connects the last arc to non-existent point and adds an unnecessary IfcLineIndex to close the polyline.

I've located the issue in the code ([lines 125-139](https://github.com/VDobranov/IfcOpenShell/blob/410fff6ee9f847eb8966c34e660b09ad3b86b5c7/src/ifcopenshell-python/ifcopenshell/util/shape_builder.py#L125C9-L139C46)):
```python
        # if curve is closed or we have arc points
        # then we do need to create segments
        segments = []
        cur_i = 0
        while cur_i < len(points) - 1:
            cur_i_ifc = cur_i + 1
            if cur_i + 1 in arc_points:
                segments.append((cur_i_ifc, cur_i_ifc + 1, cur_i_ifc + 2))
                cur_i += 2
            else:
                segments.append((cur_i_ifc, cur_i_ifc + 1))
                cur_i += 1

        if closed:
            segments.append((len(points), 1))
```
...and've made corrections that solved the issue for me:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/83d432df-b76f-4267-8356-9f2b6f3735ac)
If they are ok, I’ll send the PR.

Moreover, I don’t know if it the same source of issue or not, but BBIM seems having troubles with such "arc-ending" polys too:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/77ccc247-acb9-4165-90b1-ec5ca0bd3f49)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/8bd4cbe6-220a-4c0c-a7c4-88685c15361a)
(the last one is from official docs: https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/annex_e/building-elements/beam-extruded-solid.html)

**Comment by VDobranov** [comment]
Correction on BBIM part: troubles are on the profile editor side. The solids turn out perfectly normal:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/8d829bcc-6dd3-4298-9ec1-483978158060)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/112861900/7c1a1d95-8c3b-4512-922c-f8d8d0d84873)

**Comment by Moult** [comment]
Yes, this is a known bug (at least to me) and at a glance your fix looks alright. I'll take a closer look during the week :)

**Comment by Moult** [comment]
The profile editor now has a bunch of upgrades and handles arcs at the end, consecutive arcs, etc.
