### ISSUE TITLE
blenderbim 240402 fails to install

### ISSUE THREAD

**Issue by epeter-** [IfcOpenShell/IfcOpenShell#4991]
today blenderbim refused to start. i uninstalled blender and blenderbim.
reinstalled blender 4.1
reinstalled blenderbim 240402
errormessage:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\kop-p\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 41, in <module>
    import blenderbim.bim
ModuleNotFoundError: No module named 'blenderbim.bim'

**Comment by Andrej730** [comment]
Hi! Can you please try 240602 - https://blenderbim.org/download.html? It's the latest release.

**Comment by Andrej730** [comment]
Okay. 
Are you sure you tried to uninstall BlenderBIM by the instructions - https://docs.blenderbim.org/users/installation.html#uninstalling ?

Can you please try to remove it manually by removing `blenderbim` folder from `%appdata%\Blender Foundation\Blender\4.1\scripts\addons` and try to install it again?

**Comment by Ave-5D** [comment]
![Skermskoot (134)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/6e15c93d-8c66-4d85-90c7-d664ca1a8323)
![Skermskoot (135)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/9de0adea-1290-4777-a9c6-059b45bd9439)

I have the same problem, removed BB manually and could not load BB240708

**Comment by theoryshaw** [comment]
i think anything after BB240602 is unstable at this time.

**Comment by Moult** [comment]
@Ave-5D can you try with a clean environment? See instructions here: https://docs.blenderbim.org/users/troubleshooting.html#installation-issues

Your screenshot seems suspiciously like it did install, but just didn't fully activate, or something? Not sure.

@epeter- did you get any visual error message (e.g. the new red panel) where you can copy paste the full error message?

If either of you are online during the Sydney timezone today feel free to drop by https://osarch.org/chat and we can screenshare to debug.

@theoryshaw it's unstable, but it should be installable and models should load, non-graphical features should work, and it should be almost at a state where it's ready to be used again (a few more things to polish, I think materials/styles are almost wrapped up, drawings need a bit more testing...)

**Comment by Moult** [comment]
BTW for the latest unstable there was a problem with the Windows builds in particular (see https://github.com/IfcOpenShell/IfcOpenShell/issues/4924#issuecomment-2210785104) which I've just updated a few moments ago to the latest build so hopefully it's OK now.

**Comment by Ave-5D** [comment]
Hi Dion

 

Attached is the screen shots, I tried to import the 8hr ago “blenderbim-0.7.9.240708-py311-win” release and got the same result. 

I deleted the old BB via appdata and renamed the file as mentioned.

**Comment by Moult** [comment]
I don't see any screenshots? Also if you're online we can screenshare to debug together.

**Comment by Ave-5D** [comment]
Yes, I am online what do you want to use to screenshare so that I can down load it.

**Comment by Moult** [comment]
I'll be hanging out in https://meet.jit.si/openbim

**Comment by Ave-5D** [comment]
This one works
![Skermskoot (143)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/c42297cf-5811-4a7e-bb47-53877b12680b)
This does not work
![Skermskoot (144)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/b047cddb-2466-46b0-b685-8037d5d14bc9)

**Comment by Andrej730** [comment]
@Ave-5D can you please try the new build on Blender 4.0 after this commit 86fa24a? (daily build is already updated)

If issue persists please copy the entire console output (Window - Toggle System Console) after trying to enable the addon.

**Comment by Ave-5D** [comment]
Thank you got it working, Blender 4.0 = Py 3.10 and Blender 4.1 = Py 3.11

**Comment by Andrej730** [comment]
@epeter- does issue still persists for you? If so, please share the full console output:

> If issue persists please copy the entire console output (Window - Toggle System Console) after trying to enable the addon.
