### ISSUE TITLE
Arcs in i-beam profile not processed correctly

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4993]
It seems the 2D arcs aren't quite correct with the latest bot build.

[beam.ifc.txt](https://github.com/user-attachments/files/16135833/beam.ifc.txt)

![2024-07-09-110905_408x506_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/a83bcb61-3036-48e4-afe8-7760b4ae68d3)

**Comment by smr02** [comment]
I'm having the same issue. 
The same file is displayed correctly with Version 0.0.240602 (On Ubuntu)
However, displayed incorrectly with Version 0.7.10.240717 (On MacOS M1)

Attached the file
[test_beam.ifc.txt](https://github.com/user-attachments/files/16311622/test_beam.ifc.txt)


<img width="1120" alt="Screenshot 2024-07-19 at 13 58 11" src="https://github.com/user-attachments/assets/7acdf23a-1d32-4669-a811-6bd376c06144">

![Screenshot from 2024-07-19 13-55-41](https://github.com/user-attachments/assets/56d3f5f3-f1a7-4eaa-ad17-018a390c9e4f)

**Comment by aothms** [comment]
Embarassing. Should be fixed e88bd3af80c4f792712cc695a08a679e2d70f1a8
