### ISSUE TITLE
Grouping / Aggregates

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#5001]
Attached are screenshots.
 
I tried to create an object group
1.	Roof

    a.	Roof Structure (all the IfcBeams-Timber)
    b.	Roof Covering (all the IfcCovering-corrigated iron)

As usual I am doing something wrong, as per the attached text file when I move the one Object into the My Story and save the IFC file, when I open it again it reverts back to the original groupings.

Object in the wrong "group"
![Skermskoot (139)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/e87d5e99-5676-4771-ba41-e071f2163229)

Moved Object out of the "group"
![Skermskoot (140)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/82622e73-b89f-43a2-8db9-2672a01419a9)

Saved changes and opend it again, object back in the "group"

![Skermskoot (141)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/bed60b52-ce95-4d84-bec3-997783cd39b3)

Once again thanks for your help, I am finding this whole Ifc “grouping/aggregate ” thing very challenging.

[1bd house-240708.txt](https://github.com/user-attachments/files/16157552/1bd.house-240708.txt)

**Comment by theoryshaw** [comment]
Does this help?...
https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/6f40f1a4-76c1-4c65-a288-bc48d1a4a54e

If a relative noobie at BB, would recommend asking questions on https://community.osarch.org/categories/general 
Github is more for feature requests and bug reports.

**Comment by Ave-5D** [comment]
Thank you that is very staight forward

**Comment by Ave-5D** [comment]
Sorry this is a bug, when I try to delete the "Unsorted" file it just comes back when I open the IfcProject again. I also tried your process and it does not work... I am using BB 240708 (1st release) on Blender 4.1
Just trying to help

**Comment by theoryshaw** [comment]
could be related to this?
https://docs.blenderbim.org/users/troubleshooting.html#common-issues

**Comment by Moult** [comment]
Unsorted means that the object is not in your spatial tree. In the latest version, don't drag and drop in the outliner. Use the Spatial Container panel to place your unsorted in the spatial tree.
