### ISSUE TITLE
Issue with adding new geometries to IFC from Vectorworks

### ISSUE THREAD

**Issue by DaivaMarcinkeviciute** [IfcOpenShell/IfcOpenShell#5002]
I have a script snippet that takes an IFC file, creates a covering using an existing space geometry and writes a new IFC file with the covering added. I'm using ifcOpenShell with pythonOCC. PythonOCC is necessary, as i perform other operations on the shape in the full version of the script.

This script works perfectly with many IFC files exported from ArchiCAD and Revit. However it fails with the IFC files exported from Vectorworks.

I include the example files:
[example_ifc_files.zip](https://github.com/user-attachments/files/16157759/example_ifc_files.zip)

- archicad_file.ifc (file made with ArchiCAD): the exported file contains the new geometry as expected (in the original size and position).
- vectorworks_file.ifc: the new geometry is created at point 0,0,0 and is very small.
- vectorworks_file2.ifc: the export of the ifc fails with following error message: 
      Exception has occurred: RuntimeError
      Reading outside of file limits.

Please change the file paths to your local paths.
Please comment the unnecessary 'importedFilePath' variables out.

Could anybody help me to find out why this happens and how to fix it?

```
import ifcopenshell
import ifcopenshell.geom

#Please change the file paths to your local paths
#Please comment the unnecessary 'importedFilePath' variables out.
importedFilePath = 'archicad_file.ifc'
importedFilePath = 'vectorworks_file.ifc'
importedFilePath = 'vectorworks_file2.ifc'

exportedFilePath = 'exported.ifc'

#open file
ifcFile = ifcopenshell.open(importedFilePath)

#get site, context and owner history
site = ifcFile.by_type('IfcSite')[0]
ownerHistory = ifcFile.by_type("IfcOwnerHistory")[0]
context = ifcFile.by_type("IfcGeometricRepresentationSubContext")[0]

#create a covering
#use a shape of an existing GF space
settings = ifcopenshell.geom.settings()
settings.set(settings.USE_PYTHON_OPENCASCADE, True)
settings.set(settings.SEW_SHELLS, True)
settings.set(settings.STRICT_TOLERANCE, True)
space = ifcFile.by_type('IfcSpace')[0]
shape = ifcopenshell.geom.create_shape(settings, space).geometry
print('globalId:', space.GlobalId)

#create a placement
point = ifcFile.createIfcCartesianPoint((0.0, 0.0, 0.0))
dir1 = ifcFile.createIfcDirection((0.0, 0.0, 1.0))
dir2 = ifcFile.createIfcDirection((1.0, 0.0, 0.0))
axis2placement = ifcFile.createIfcAxis2Placement3D(point, dir1, dir2)
placement = ifcFile.createIfcLocalPlacement(site.ObjectPlacement, axis2placement)

#create an entitiy
newEntity = ifcFile.create_entity('IfcCovering', GlobalId=ifcopenshell.guid.new(), Name='testCovering')
newEntity.ObjectPlacement = placement

#create the representation
ifcRepresentation = ifcopenshell.geom.tesselate(ifcFile.schema, shape, 1.0)
for rep in ifcRepresentation.Representations:
    rep.ContextOfItems = context
ifcFile.add(ifcRepresentation)                    
newEntity.Representation = ifcRepresentation

# Relate to the site
ifcFile.createIfcRelContainedInSpatialStructure(ifcopenshell.guid.new(), ownerHistory, "Building Storey Container", None, [newEntity], site) 

#write the file
ifcFile.write(exportedFilePath)

print('done')

```

**Comment by Moult** [comment]
Your vectorworks_file2.ifc contains a reference to a STEP ID that doesn't exist. That shouldn't be possible with IfcOpenShell, it sounds like the file was possibly edited in a text editor or similar.

There are also a number of potential bugs and non-optimal code in your snippet. For example, you assume the 0th context is the body context. You also create a second contained relationship instead of reusing existing relationships. Have you checked out the IfcOpenShell API?

 - https://docs.ifcopenshell.org/autoapi/ifcopenshell/api/project/index.html#ifcopenshell.api.project.create_file
 - https://docs.ifcopenshell.org/autoapi/ifcopenshell/api/root/index.html#ifcopenshell.api.root.create_entity
 - https://docs.ifcopenshell.org/autoapi/ifcopenshell/api/spatial/index.html#ifcopenshell.api.spatial.assign_container
 - https://docs.ifcopenshell.org/autoapi/ifcopenshell/util/shape_builder/index.html#ifcopenshell.util.shape_builder.ShapeBuilder.create_axis2_placement_3d

**Comment by DaivaMarcinkeviciute** [comment]
Hi Moult,

Thank you so much for your input!
The api functions seam very user friendly, but i am not able to import / use them (on this project i am using IfcOpenShell 0.7.0)

I have the following issue:

```
import ifcopenshell

# Start a new model.
model = ifcopenshell.api.project.create_file()
```

Error: AttributeError: module 'ifcopenshell' has no attribute 'api'


```
from ifcopenshell.api.project import create_file 
 
# Start a new model.
model = create_file()
```

Import is sucessful, but i get an error on row4:  TypeError: 'module' object is not callable

Do you happen to know what i am doing wrong?

**Comment by Moult** [comment]
It looks like you have an outdated version of ifcopenshell. Can you update to the latest?

**Comment by DaivaMarcinkeviciute** [comment]
The entire (and very long) code is written in IfcOpenShell 0.7.0 and i assume i might create multiple bugs if i update.
If i do, i would probably also have to update pythonOCC to match the new IfcOpenShell version, right?

**Comment by Moult** [comment]
We're slowly upgrading to v0.8.0, so right now yes there will be a few bugs especially if you're dealing with geometry. However once it's stable it's mostly a drop-in replacement with only a few tweaks.

I think PythonOCC shouldn't be affected.

That said, just replace ifcopenshell.api.foo.bar(...) with ifcopenshell.api.run("foo.bar", ...) which is equivalent in v0.7.0.

**Comment by DaivaMarcinkeviciute** [comment]
Thanks again! It seams to work with the "run" option :)

**Comment by DaivaMarcinkeviciute** [comment]
In case anyone else has the same problem, here is the solution:
Archicad- and Revit-IFCs have meters as units, Vectorworks-IFCs have milimeters.
When creating settings for geometry import, a following additional setting should be made:

```
settings.set(settings.CONVERT_BACK_UNITS, True) 
```
