### ISSUE TITLE
Feature: Add "total cost" to parent Cost Item based on its parts on BlenderBIM

### ISSUE THREAD

**Issue by fg55b** [IfcOpenShell/IfcOpenShell#5004]
Greetings!

A useful feature for cost visualization would be to display the "total cost" of cost items nested within other cost items, if the parent cost item does not have quantities and cost values associated originally. If possible, this would facilitate the cost visualization for each cost decomposition layer, as well as the total cost of the project.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/129398445/9d9321b6-bb46-4232-a122-62582c2709a8)

**Comment by Moult** [comment]
You can already do this. Just add a sum cost value. You can also subtotal specific categories and use formulas.

![2024-07-10-233208_518x431_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/17f95c7d-a4fd-4e8e-9647-e85647544de7)

**Comment by fg55b** [comment]
Perfect Dion, thanks for the reply!
