### ISSUE TITLE
Entity with name 'IfcExtendedMaterialProperties' not found in schema 'IFC4'

### ISSUE THREAD

**Issue by amitca71** [IfcOpenShell/IfcOpenShell#5005]
I use schema IFC2X3, getting the following error:
 Entity with name 'IfcExtendedMaterialProperties' not found in schema 'IFC4'

was greping the all repo, and couldnt find any reference for IfcExtendedMaterialProperties

**Comment by Andrej730** [comment]
@amitca71 Hi! Can you please show a way to reproduce the issue?

**Comment by amitca71** [comment]
sorry, it was an issue with the driver i used (https://github.com/amitca71/IFC-Neo4j-converter.git). 
closing. thanks
