### ISSUE TITLE
Cannot install ifcopenshell with pip

### ISSUE THREAD

**Issue by jsammer-ode** [IfcOpenShell/IfcOpenShell#5006]
When running `pip install ifcopenshell`, installation fails with the following error

```bash
Building wheels for collected packages: mathutils
  Building wheel for mathutils (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'mathutils' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mathutils
  Running setup.py clean for mathutils
Failed to build mathutils
ERROR: Could not build wheels for mathutils, which is required to install pyproject.toml-based projects
```

The problem occurs with my colleagues' Windows 11, x64 machine, where we have manually installed Microsoft Visual C++ 15. On a different machine, with Windows 10 OS (but in an WSL Ubuntu terminal) the problem doesn't occur.
I have tried installing different ifcopenshell versions (0.7.0.240521; 0.7.0.240627 both from pypi), but the error still appears.
Not sure if it's related to this issue here: https://github.com/IfcOpenShell/IfcOpenShell/issues/4837

**Comment by Andrej730** [comment]
Which python version?

**Comment by Moult** [comment]
This has already been fixed, we're slowly removing mathutils from the main utils and it is now no longer a mandatory dependency. We just haven't released a new version yet. I'll do it later today or tomorrow.

**Comment by Moult** [comment]
OK did a release, can you please try again?

**Comment by VDobranov** [comment]
There is still an import of mathutils in https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcopenshell-python/ifcopenshell/util/shape_builder.py
Does it still count as an issue? (I am struggling with pip installing ifcopenshell on Win10 right now)

**Comment by Andrej730** [comment]
@VDobranov it's a separate issue - https://github.com/IfcOpenShell/IfcOpenShell/issues/5192

> I am struggling with pip installing ifcopenshell on Win10 right now

What error? `pip install ifcopenshell` should install it without `mathutils` or you do need shape_builder module?

**Comment by VDobranov** [comment]
You are right, the problem is not with the installation itself, but with the using of shape_builder.
