### ISSUE TITLE
Where is the multithreaded code, please?I can't find

### ISSUE THREAD

**Issue by liaoweiqi1997** [IfcOpenShell/IfcOpenShell#501]
It is said that the new code refers to multithreading technology, but I can't find information related to multithreading throughout the project.Can you tell me where the relevant code is?I mean multi-threading in the ifc-convert parse submodule，thanks.

**Comment by aothms** [comment]
It's work in progress:

https://github.com/sanderboer/IfcOpenShell/commits/multithreading
