### ISSUE TITLE
Compiling v0.8 [C++] and visual studio error in CMAKE

### ISSUE THREAD

**Issue by SoftwareMechanic** [IfcOpenShell/IfcOpenShell#5017]
Hello!

I have seen that v0.8 is the new branch!
that is amazing for me so I can try CGAL hoping for faster conversions and better memory management during geometry conversion.

I am trying to build it for windows (x64), but whenever I run 'run-cmake.bat' I face the following error:
```
CMake Error at C:/Users/myuser/IfcOpenshell/src/ifcwrap/CMakeLists.txt:81 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES called with incorrect number of arguments.
```

I checked and it seems that in this line

`SET_TARGET_PROPERTIES(${SWIG_MODULE_ifcopenshell_wrapper_REAL_NAME} PROPERTIES SUFFIX ${PYTHON_EXTENSION_SUFFIX})`

seems that the variable `${PYTHON_EXTENSION_SUFFIX}` is null.

sadly I am still not confident with CMake and I don't have any idea on how I can solve this...
I am sorry if this a stupid error...

hope you can help me understand better what could be the cause of this issue.

thank you in advance

**Comment by Andrej730** [comment]
@SoftwareMechanic Hi! Thank you for the report. Is there some other output before this error?

Lines below in cmake suppose to run your python and get platform specific extension suffix, e.g. for windows and python 3.11 it's ".cp311-win_amd64.pyd".

```
    EXECUTE_PROCESS(
        COMMAND ${PYTHON_EXECUTABLE} -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))"
        OUTPUT_VARIABLE PYTHON_EXTENSION_SUFFIX
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
```

If `PYTHON_EXTENSION_SUFFIX` is `""` then it means something goes wrong here. You can try to replace those lines with something like the snippet below to get more verbose output.

```
    MESSAGE(STATUS "PYTHON_MODULE_INSTALL_DIR ${PYTHON_MODULE_INSTALL_DIR}")
    MESSAGE(STATUS "PYTHONINTERP_FOUND ${PYTHONINTERP_FOUND}")
    MESSAGE(STATUS "PYTHON_EXECUTABLE ${PYTHON_EXECUTABLE}")
    EXECUTE_PROCESS(
	    COMMAND ${PYTHON_EXECUTABLE} -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX')); "
	    OUTPUT_VARIABLE PYTHON_EXTENSION_SUFFIX
	    OUTPUT_STRIP_TRAILING_WHITESPACE
	    ECHO_OUTPUT_VARIABLE
	    COMMAND_ERROR_IS_FATAL ANY
	    COMMAND_ECHO STDERR
    )
    MESSAGE(STATUS "PYTHON_EXTENSION_SUFFIX ${PYTHON_EXTENSION_SUFFIX}")
    MESSAGE(FATAL_ERROR "------")
```

**Comment by SoftwareMechanic** [comment]
thank you  @Andrej730, I tried to modify the file according to your suggestions, and this is the output I get:

```
-- PYTHON_MODULE_INSTALL_DIR
-- PYTHONINTERP_FOUND TRUE
-- PYTHON_EXECUTABLE C:\Users\...\IfcOpenshell\_deps-vs2019-x64-installed\Python311\python.exe
'C:\Users\...\IfcOpenshell\_deps-vs2019-x64-installed\Python311\python.exe' '-c' 'import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX')); '
CMake Error at C:/Users/.../IfcOpenshell/src/ifcwrap/CMakeLists.txt:79 (EXECUTE_PROCESS):
  EXECUTE_PROCESS failed command indexes:

    1: "Abnormal exit with child return code: no such file or directory"



-- Configuring incomplete, errors occurred!
```
The problem was probably that I disabled the Python module when building dependencies.

Thank you so much!!!!
