### ISSUE TITLE
I would like to ask about the conversion efficiency of the ifc-convert tool.

### ISSUE THREAD

**Issue by liaoweiqi1997** [IfcOpenShell/IfcOpenShell#502]
About the ifc convert tool, what is the fastest conversion efficiency on your side?How long does it take for a ifc file size of 500MB to be converted into an obj or dae file?For large files (1 GB), does the configuration of the computer make a big difference?Looking forward to your reply, thanks.

**Comment by aothms** [comment]
It varies based on the contents of the IFC file. IfcOpenShell is especially not very efficient when it comes to explicit connected face sets.

> does the configuration of the computer make a big difference

Not a lot. IfcOpenShell doesn't use multiple cores (yet) or the GPU for example.
