### ISSUE TITLE
ifcpatch Migrate error: 'Migrator' object has no attribute 'preprocess'

### ISSUE THREAD

**Issue by campog424** [IfcOpenShell/IfcOpenShell#5022]
Hi

I was trying to migrate an ifc from IFC2X3 to IFC4 and I have encountered an issue when launching the Migrate recipe with ifcpatch:
![imagen](https://github.com/user-attachments/assets/2e0ad7c3-b7a7-4c15-a3e4-2edeeb195791)

Here is the code snippet that I executed:
```
import ifcpatch
import ifcopenshell
def upgradeIFCVersion( path: str, outPath,version = "IFC4"):
    model = ifcopenshell.open(path)
    output = ifcpatch.execute({"input": path, 
                "file": model,"recipe": "Migrate", "arguments": [version]})
    ifcpatch.write(output, str(outPath))
```
The issue seems to be related to this commit: https://github.com/IfcOpenShell/IfcOpenShell/commit/48d058a32a9f960de781193b043fe6d9cf7009eb
- Here are the dependencies of IfcOpenShell and IfcPatch:
ifcopenshell==0.7.0.240521
ifcpatch==0.7.10

Here is the example file I was testing with(Its a clean file with some random elements):
[in_test.zip](https://github.com/user-attachments/files/16251555/in_test.zip)

**Comment by Moult** [comment]
Fixed due to new release.
