### ISSUE TITLE
Ifc File works properly on BlenderBIM, but it doesn't correctly show the objects in the right position in IfcConvert

### ISSUE THREAD

**Issue by csritter** [IfcOpenShell/IfcOpenShell#5031]
Hi, I got the last commit running on Windows or Ubuntu, and gives me this:

IfcConvert with Windows Viewer3D:
![image](https://github.com/user-attachments/assets/0ff1d56e-97c8-49dd-83bf-a3e8fc1aaa2e)

But BlenderBIM gives me the correct behavior:

BlenderBIM:
![image](https://github.com/user-attachments/assets/18edca64-67da-441c-84d6-c72173019312)

Is there something that BlenderBIM makes that works that IfcConvert doesn't?
I can send an email with the project if needed because it is private.

**Comment by Moult** [comment]
What version of IfcConvert are you using, vs what version of the BlenderBIM Add-on?

**Comment by csritter** [comment]
IfcConvert Revision: 798cc6069f98f9b1cde388c96697daab81c40369
BlenderBIM: 240602

**Comment by aothms** [comment]
From the look of the artefacts this could be a large offset introduced somewhere in the placement hierarchy that BlenderBIM circumvents with its false origin procedure. With some luck `--building-local-placement` does something similar in IfcConvert by ignoring all placements in the hierarchy from the building and up.

**Comment by Moult** [comment]
Also happy to investigate if you send a model to dion@thinkmoult.com

**Comment by csritter** [comment]
@aothms, I tried to set --building-local-placement and without success.

I sent the project to dion email and model@ifcopenshell.org too. Thanks for looking at it.

**Comment by Moult** [comment]
As @aothms suggested this model has large coordinates specified at the site so `--building-local-placement` should be sufficient. I ran `./IfcConvert --building-local-placement ~/project_problem_with_positions.ifc ~/out.glb` no issues with an older version of IfcConvert from 0.7.0 but I can confirm with IfcConvert from the latest bot build at least the argument no longer works as advertised.

Something for @aothms to investigate :)

But just FYI it is still converting correctly, just your viewer isn't capable of showing these large coordinates (Blender has some clever code to create a false origin).

**Comment by csritter** [comment]
From what I understand, we have a very large coordinate in IfcSite.
I used ifcopenshell in Python and it returned this value:
`#137=IfcCartesianPoint((20038180.362440906,85078873.213484794,39176.275140431346))`

I'm just thinking of a way for this not to affect files when creating federated projects because IfcOpenShell runs on a fixed server in the cloud when we receive a project from someone, then the ideal would be not to use this because we had projects that had one project with different IfcSite, and when we used --ifc-site-localplacement it didn't match correctly
If you have any suggestions on how to resolve this, you are welcome.

Anyway, thanks @Moult and @aothms for looking at it.
I'm closing this issue.

**Comment by Moult** [comment]
@csritter it's not mathematically wrong to have a large coordinate in the IfcSite, or anywhere else for that matter. And I have come across all sorts of funky situations with large coordinates in odd spots that things like `--building-local-placement` won't catch.

The short answer is that to properly address this you should preserve those coordinates (don't apply `--building-local-placement` et al) and instead fix your viewer software to handle large coordinates (either actually supporting double precision like Xeokit does or creating a false origin like the BlenderBIM Add-on does).

The longer answer is that you need to ideally nominate some sort of consistent false origin (even if that origin happens to be 0, 0, 0). This may either be automatically determined by the first file you receive that is part of a project, or nominated specifically by the user, etc. Then, you also need to parse any georeferencing data and ensure that the projected CRS is identical (to mix CRSes, reprojection is required), and then you need to accommodate any coordinate operation done between local and map coordinates. There's all sorts of toys here https://docs.ifcopenshell.org/autoapi/ifcopenshell/util/geolocation/index.html which can handle this. This helps you federate multiple models which have different false origins, different project norths, different units, and in IFC4X3 even different scaling factors and display them correctly relative to one another.

To my knowledge nobody apart from the BlenderBIM Add-on does this correctly. This is also a bit hard to explain without demonstration files (you can see our test cases).

**Comment by aothms** [comment]
What IfcConvert in v0.7 used to offer is --center-model, which would write the transformation to stdout and then you could apply that same offset to --offset-model on subsequent models in the same project context. So this usecase was envisioned in IfcConvert. I don't think anybody was aware of this besides the author who contributed this. So it's not yet reintroduced in v0.8. Also because now that we have such a powerful Python API I'd anything that requires this kind of logic is better handled in a scripting language. In Python it's really easy to overwrite this offset (if you know where it's introduced, but that's the site in 99% of the cases) and store it in the DB so that you can apply the same offset in subsequent models. I think in a web context I wouldn't advise to send doubles to the client (also not for the matrices).

**Comment by aothms** [comment]
Correct. Indeed I don't think there are a lot of other tools that handle multiple map conversions correctly.
