### ISSUE TITLE
Material is missing when creating a Beam/Column

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#5032]
When creating a beam (e.g. in the DemoProject), material seems to be missing

<img width="803" alt="Screenshot 2024-07-18 at 00 41 47" src="https://github.com/user-attachments/assets/ce587ff4-047d-4f04-b305-6c03232fea20">

**Comment by Moult** [comment]
This is correct, because the beam has no (surface) style.

**Comment by theoryshaw** [comment]
you might know how to do this already...

https://github.com/user-attachments/assets/5cf56b4b-9a95-4f3a-9aaa-76945865ee5e
