### ISSUE TITLE
IFC Import

### ISSUE THREAD

**Issue by big-arch** [IfcOpenShell/IfcOpenShell#5034]
Before that, it was possible to import the IFC file into the project. Now there is no such function, I do not need to create it new Project..... I just want to add a one file, there is no information on the website in the Importing and Viewing IFC Models section.
How fix it?

**Comment by Moult** [comment]
File > Open IFC Project :)

**Comment by Moult** [comment]
What website are you looking at? I'm pretty sure our basic tutorial shows this at the beginning. https://docs.blenderbim.org/users/quickstart/explore_model.html

**Comment by big-arch** [comment]
funny but my quastion was how Import one file to another ptoject , if i did File > Open IFC Project , my file opened in another file i don`t want that , i want function Import 
![Screenshot_2](https://github.com/user-attachments/assets/caa81ceb-662c-416c-a9f1-e331d3b681a2)

**Comment by big-arch** [comment]
And how i can did that ?

**Comment by Gorgious56** [comment]
You can't have two active ifc projects at once inside a single blend file. You may want to link the other ifc inside your project ?

![image](https://github.com/user-attachments/assets/0af2e90a-6960-46a9-8487-d7f29bab5d48)

If you want to import only the geometry, you need to load the ifc project into a new blend file, save the blend file, and then in the first blend file append the geometry with File > Append

**Comment by Andrej730** [comment]
I think this functionality was was readded to File - Import, so this can be closed.

![image](https://github.com/user-attachments/assets/7b226750-1d62-48e0-be42-39bcfce8edcf)
