### ISSUE TITLE
Error BlenderBIM

### ISSUE THREAD

**Issue by PhamKhai26391** [IfcOpenShell/IfcOpenShell#5037]
How to fix it
![image](https://github.com/user-attachments/assets/177de14b-acd0-4e7f-9b7c-294a8dfd79c7)

**Comment by big-arch** [comment]
Hi, I don`t know 
this happend when i try open new ifc file, but if i opened old which created in last week is opennig good
I suppuse this is truble with new update blender bim

**Comment by Moult** [comment]
There are a few ongoing issues, but this particular bug is to do with this menu showing when it shouldn't (after a discussion in the live chat)

![image](https://github.com/user-attachments/assets/c886f107-39e3-4b4c-be52-a9904830daba)
