### ISSUE TITLE
Decimals in count are annoying :)

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5039]
As in the title:

![image](https://github.com/user-attachments/assets/e745cbda-855b-4c1d-827d-6a0a00156aa3)

This is also the case for other things when rounding.

**Comment by Moult** [comment]
Probably best solved by adding a new `int()` function as part of our formatting functions.

**Comment by steverugi** [comment]
Hi @BIMvoice 
to avoid decimals in count I use `metric_length({{value}},1,0)` in the formatting column

![image](https://github.com/user-attachments/assets/5d176ccc-426c-4b27-b7f4-123bbc5654b2)

**Comment by theoryshaw** [comment]
took a stab: https://github.com/IfcOpenShell/IfcOpenShell/commit/ab97f23b478d91eff0a26986fa63a224ad5f6f28
