### ISSUE TITLE
Generate code for the IFC4X1 schema

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#504]

**Comment by atibaut** [comment]
Is this issue still needed since in the 0.6.0 we already have added support for IFC4X2 DRAFT in that merge request #628?

**Comment by aothms** [comment]
@atibaut Even if 4X2 is a superset of 4X1, if there are ifc files with IFC4X1 in the schema header, IfcOpenShell won't be able to infer it can select 4X2 to parse the file. So yes, better to keep the issue open. Feel free if you have the time :)

> since in the 0.6.0 we already have added support for IFC4X2 DRAFT

Note that I still need to do a little bit work to tie things together. IfcOpenShell is currently not smart enough to autodetect the added files.

**Comment by atibaut** [comment]
Ok, in that case we would need to include support for IFC4X1 as well right? For those that would use IFC4X1....
And then schema auto-detection can be implemented.

**Comment by aothms** [comment]
> include support for IFC4X1 as well right?

Yes

>  And then schema auto-detection can be implemented.

yes there are a couple of things regarding that. Right now the loaded schemas are hardcoded to 2x3 and 4. 

* (a) We can update the hardcoded references, since we're only talking about a handful of schemas at most.
* (b) We can also detect the schema files in CMake and let in generate appropriate loading code.
* (c) Alternative is to compile every schema into a DLL and load schemas at runtime like plugins. More flexible and more work.
* Then there is the work to enable geometry handling (d1) there is some work needed to reuse the shared definitions among schemas.
* (d2) And of course the novel geometry forms in terms of horizontal and vertical alignments etc.

I'll see if I can get some funding for this, but otherwise I guess I'll stick to just (a) for the immediate future.

**Comment by atibaut** [comment]
@aothms it is reasonable to add hardcoded support for 4x1 and 4x2 (a) and invest time to (d1) and (d2).
My team (Uni Maribor) would be very interested to contribute to (d1) and (d2) as I have a Phd student focusing to IFC Road.

**Comment by atibaut** [comment]
Hi @aothms I will take the task of preparing the code for IFC4x1 on the 0.6.0 version.

**Comment by atibaut** [comment]
@aothms Pull Request created for IFC4x1 support.

**Comment by aothms** [comment]
> @aothms it is reasonable to add hardcoded support for 4x1 and 4x2 (a) and invest time to (d1) and (d2).
> My team (Uni Maribor) would be very interested to contribute to (d1) and (d2) as I have a Phd student @Sara-GO focusing to IFC Road.

With my latest commit you should have a pretty good basis to start working on infra geometries https://github.com/IfcOpenShell/IfcOpenShell/commit/839b5a269937c385777be30bba3160d62a7ca4ca

For the alignment pairs, I would consider something like the following:

* For the horizontal alignments `BRepAdaptor_CompCurve`
* Use that to create a vertical extrusion with `Adaptor3d_SurfaceOfLinearExtrusion`
* `BRepBuilderAPI_MakeEdge` from a vertical 2d curve and the surface
* `BuildCurve3d` to create the 3d curve from the combination of surface and 2d curve

At some point OCCT will just convert everything to nurbs, so you can also handle it like that explicitly.

I have not yet thought about how to handle clothoids.

Let me know if you have questions. I'm quite interested in moving this forward, just don't have a lot of hours to spend.
