### ISSUE TITLE
Two issues with BlenderBim

### ISSUE THREAD

**Issue by Elen2024** [IfcOpenShell/IfcOpenShell#5042]
To whom it may concern, 

I am writing this email to inform you about two issues I've encountered with BlenderBim. While I was drawing in BlenderBim, the software abruptly stopped functioning properly and exited unexpectedly. I've had the same issues many times over the last few days. You can view the screenshot I've attached. To mention the version that I am currently using, it is vo.240602-47704b1.  Could you please help me on this issue?

Generally, from watching numerous tutorials on YouTube, it appears that the version I've installed isn't operating smoothly. Specifically, as you can see in the second screenshot, when I am drawing the walls, there is an option to create a new project on the right side of the screen, even though I have already started one.

Could you please help me on these two issues?

Thank you in advance for your time.

Best Regards, 
Eleni Matinopoulou. 

![Screenshot 2024-07-19 at 3 42 05 PM](https://github.com/user-attachments/assets/3dfe755e-72b0-46b1-89c0-d5e674585acc)
![Screenshot 2024-07-19 at 3 43 22 PM](https://github.com/user-attachments/assets/f8fcc146-334f-492d-b15f-b9f5a279415f)
![Screenshot 2024-07-19 at 3 49 00 PM](https://github.com/user-attachments/assets/d9fc642f-29c9-4f1a-a6b3-a6820bee28d3)

**Comment by Moult** [comment]
Are you loading and saving Blend files?

**Comment by Moult** [comment]
Bump

**Comment by Moult** [comment]
Closing due to lack of feedback.
