### ISSUE TITLE
BBIM installation errors

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#5045]
Just a note on getting latest snapshot running. On blender 4.0 I had to reinsert the bl_info stuff:

``` diff
diff -r src/blenderbim/blenderbim/__init__.py /usr/share/blender/4.0/scripts/addons/blenderbim/__init__.py
39a40,52
> # NOTE: bl_info is superseded by blender_manifest.toml
> # if addon is installed as an extension (Blender 4.2+)
> bl_info = {
>     "name": "BlenderBIM",
>     "description": "Transforms Blender into a native Building Information Model authoring platform using IFC.",
>     "author": "IfcOpenShell Contributors",
>     "blender": (3, 1, 0),
>     "version": (0, 0, 0),
>     "location": "File Menu, Scene Properties Tab. See documentation for more.",
>     "doc_url": "https://docs.blenderbim.org/",
>     "tracker_url": "https://github.com/IfcOpenShell/IfcOpenShell/issues",
>     "category": "System",
> }
```

..and since I'm using system packages for everything, and the new light module has a long chain of dependencies that may take me a while to supply, I disabled the light module like so:

``` diff
diff -r src/blenderbim/blenderbim/bim/module/light/operator.py /usr/share/blender/4.0/scripts/addons/blenderbim/bim/module/light/operator.py
24c24,27
< import pyradiance as pr
---
> try:
>     import pyradiance as pr
> except ImportError:
>     print("Warning: Light module not available.")
diff -r src/blenderbim/blenderbim/bim/module/light/prop.py /usr/share/blender/4.0/scripts/addons/blenderbim/bim/module/light/prop.py
21c21,24
< import tzfpy
---
> try:
>     import tzfpy
> except ImportError:
>     print("Warning: Light module not available.")
```

**Comment by Moult** [comment]
Given the large number of changes for B4.2, I don't think we can really support <4.2 anymore from this point onwards that easily.

**Comment by brunopostle** [comment]
If supporting < 4.2 isn't easy then drop it, limited resources are better spent elsewhere. I hope the new add-on system is well thought out, blender is stuck with it for the next two years because of the LTS thing.

4.0 with the bl_info stuff patched back-in _seems_ to be ok, though I noticed that blenderbim fails badly if the Sun position add-on isn't enabled - hopefully the new 4.2 add-on system allows you to require other add-ons.
