### ISSUE TITLE
Segmentation fault on 0.8.0, but in 0.7.0 works properly

### ISSUE THREAD

**Issue by csritter** [IfcOpenShell/IfcOpenShell#5046]
Hi, I trying to use IfcConvert to convert an IFC File which throws an error in this last version:

`Exception thrown at 0x00007FF6A0CFB360 in IfcConvert.exe: 0xC0000005: Access violation reading location 0x0000000000000030.
`
![image](https://github.com/user-attachments/assets/85d59e68-6c05-4250-9074-745e822fe1de)

IfcConvert 0.8.0 version commit 8f2e8ec64da31de81d72fc63ad2569bc5a3d328b gives the error
IfcConvert 0.7.0 version commit bc318e1f6699bdbc51f3dc0be13d156bd1fb59dd works properly

If you want, I can send you the project for your email to check.

**Comment by aothms** [comment]
Please send to model@ifcopenshell.org. Full stack trace is probably also sufficient. There isn't really a definitive settlement on mapping the various optionality of certain placements and how that maps to our new taxonomy and assumptions in code.

**Comment by csritter** [comment]
Hi, I sent an email with the project.

**Comment by aothms** [comment]
Thanks should be fixed again

**Comment by csritter** [comment]
Tested and working. Closing this issue.
Thanks.
