### ISSUE TITLE
Order types alphabetically

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5047]
Would be nice if the types were ordered alphabetically ... 
![image](https://github.com/user-attachments/assets/c5e31087-5bad-4a94-b278-379c4167da2d)

**Comment by aothms** [comment]
Since these types might involve numbers, could consider natural sorting, which groups consecutive sequences of digits into numbers. So that `beam 1` < `beam 11`. This is what (windows) file explorer does.

https://github.com/SethMMorton/natsort

**Comment by theoryshaw** [comment]
yes, great idea!
started a new issue here: https://github.com/IfcOpenShell/IfcOpenShell/issues/5050
