### ISSUE TITLE
IfcLinearPlacement of signal shows signal at origin

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5049]
https://github.com/buildingSMART/IFC4.3.x-sample-models/tree/main/models/alignment-geometries-and-linear-positioning/linear-placement-of-signal

```python
import ifcopenshell
import ifcopenshell.geom
import numpy as np
start = time.time()
ifc_file = ifcopenshell.open('/home/dion/tmp/linear-placement-of-signal.ifc')

settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, ifc_file.by_id(3020)) # signal
print(np.array(shape.transformation.matrix))
```

```
[ 9.39398720e-01  3.42826551e-01  8.82874350e-17  0.00000000e+00
 -3.42826551e-01  9.39398720e-01  0.00000000e+00  0.00000000e+00
 -8.29371035e-17 -3.02672768e-17  1.00000000e+00  0.00000000e+00
  4.52600861e+05  4.53952782e+06  7.50000000e+00  1.00000000e+00]
```

The XYZ is 0, 0, 0.

![2024-07-20-111251_817x661_scrot](https://github.com/user-attachments/assets/41a8db7f-1eae-4d1b-b728-98c9660a0104)

**Comment by RickBrice** [comment]
Is there a mistake in my understanding of the 4x4 matrix?

In the c++ code I compute a matrix for the placement in the form
[vxx,vyx,vzx,x]
[vxy,vyy,vzy,y]
[vxz,vyz,vzz,z]
[0,0,0,1]

The transpose is listed.

**Comment by Moult** [comment]
Oh whoops I see now the matrix is flipped let me investigate why it turns up at the origin in Blender.

**Comment by Moult** [comment]
Sorry this is not a bug - just my blurry Saturday morning mind still waking up :) Everything works as expected.

Blender creates an auto-offset if it detects large coordinates, and it happened to choose the signal as the false origin which misled me into thinking it was at 0,0,0. I now see there are multiple signals and they are at correct looking spots.
