### ISSUE TITLE
Natural sorting of types

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5050]
as @aothms mentions [here](https://github.com/IfcOpenShell/IfcOpenShell/issues/5047#issuecomment-2240806663). 

> Since these types might involve numbers, could consider natural sorting, which groups consecutive sequences of digits into numbers. So that beam 1 < beam 11. This is what (windows) file explorer does.
https://github.com/SethMMorton/natsort

**Comment by theoryshaw** [comment]
If someone wants to add this library to ifcopenshell, i can try and take a stab at updating the relevant sorting code for types. 

...just don't know how to add libraries, yet.

**Comment by Moult** [comment]
It may not be necessary to pull in another dependency. There seem to be a few options to copy paste from here https://stackoverflow.com/questions/4836710/is-there-a-built-in-function-for-string-natural-sort
