### ISSUE TITLE
compile 50e5d5f on Debian Buster with -DUNICODE_SUPPORT=True results in Error

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#506]
the title says anything ... it is a clean Debian Buster. If -DUNICODE_SUPPORT is set to False it works. Attached the error:

`
$

$ make

[  2%] Building CXX object CMakeFiles/IfcParse.dir/home/vagrant/Documents/ifcos/IfcOpenShell/src/ifcparse/IfcCharacterDecoder.cpp.o

/home/vagrant/Documents/ifcos/IfcOpenShell/src/ifcparse/IfcCharacterDecoder.cpp: In member function ‘void IfcParse::IfcCharacterDecoder::addChar(std::stringstream&, const UChar32&)’:

/home/vagrant/Documents/ifcos/IfcOpenShell/src/ifcparse/IfcCharacterDecoder.cpp:84:3: error: ‘UnicodeString’ was not declared in this scope

   UnicodeString(ch).extract(extraction_buffer,5,destination,status);

   ^~~~~~~~~~~~~

/home/vagrant/Documents/ifcos/IfcOpenShell/src/ifcparse/IfcCharacterDecoder.cpp:84:3: note: suggested alternative:

In file included from /home/vagrant/Documents/ifcos/IfcOpenShell/src/ifcparse/IfcCharacterDecoder.cpp:74:

/usr/include/unicode/unistr.h:289:20: note:   ‘icu_63::UnicodeString’

 class U_COMMON_API UnicodeString : public Replaceable

                    ^~~~~~~~~~~~~

make[2]: *** [CMakeFiles/IfcParse.dir/build.make:89: CMakeFiles/IfcParse.dir/home/vagrant/Documents/ifcos/IfcOpenShell/src/ifcparse/IfcCharacterDecoder.cpp.o] Error 1

make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/IfcParse.dir/all] Error 2

make: *** [Makefile:130: all] Error 2

$ 
`

bernd

**Comment by berndhahnebach** [comment]
as recomended adding icu_63:: works great ...

I will go for a PR later on ...

**Comment by aothms** [comment]
`icu::` should work as well to make the namespace not version specific. I think ICU recently turned off the automatic `using` statement.

See: http://userguide.icu-project.org/howtouseicu#TOC-C-Namespace

**Comment by berndhahnebach** [comment]
it does :-)
