### ISSUE TITLE
Move BIMTester to the Sandbox area?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5060]
I have no idea if someone is using this tool, but I know it is confusing to have it under IFC Tester. I'm sure many people have no idea what it does.

Wouldn't it make sense to move it to the Sandbox area, to avoid unnecessary confusion?

![image](https://github.com/user-attachments/assets/d4042046-5e0f-4507-99ab-413ba76664f0)

**Comment by Moult** [comment]
Already removed https://github.com/IfcOpenShell/IfcOpenShell/commit/71575905cb0301e14c68d61bc534aa205ebb794c
