### ISSUE TITLE
Import! IFC

### ISSUE THREAD

**Issue by big-arch** [IfcOpenShell/IfcOpenShell#5065]
Before that, it was possible to **_import_** the IFC file into the project. Now there is no such function, I do not need to create it new Project..... I just want to add a one file, there is no information on the website in the Importing and Viewing IFC Models section.
How fix it?
if i did File > Open IFC Project , my file opened in another file i don`t want that , i want function **_Import_**
![Screenshot_2](https://github.com/user-attachments/assets/7bac753d-83d4-4ad0-be8a-9e861b26a83d)
And how i can do that ?

**Comment by Moult** [comment]
In Quality and Coordination > Debug > click Convert to Blender File. Then back in Project Overview you can press Load Project again to load more projects. Note that you will lose IFC data in the process and it'll just be basic geometry.

**Comment by big-arch** [comment]
description it is better to back up the photo, before that the functionality with import was more convenient
![Screenshot_4](https://github.com/user-attachments/assets/775591fd-1fe8-4dbe-80b4-48b6c4479030)

**Comment by big-arch** [comment]
before that, the ifc (import) model stood up at the same coordinates, but now you don't understand what

**Comment by Tudjack** [comment]
Regarding the coordinates it happened to me yesterday on a model. Also that specific model was scaled up by 1000 times in Blender. 
The funny thing is, after saving the model, the coordinates and scale were saved correctly. I think it has something to do with internal ifc length units which were set to millimetres, not being converted correctly into Blender.
I was using Blender 4.2 and the daily development build of BBim.

**Comment by big-arch** [comment]
I remain of the opinion that now it is impossible to add an ifc file to the project (just import) so that it stands at the same coordinates as it was unloaded from another program. We have to use this resource (https://convert3d.org ) to convert from ifc to fbx, to insert it into an open project and then edit it as I need

**Comment by Moult** [comment]
@Tudjack can you share what model you were using that you think has coordinate issues? It is possible that the reason is simply that their georeferencing data is wrong, but I'd like to check.

@big-arch I don't understand what you mean by stood up at the same coordinates. You can always disable georeferencing in advanced mode when loading projects or linking projects if you only want to consider local coordinates (e.g. your georeferencing data is wrong). We can have a screenshare session too if that helps? https://osarch.org/chat

**Comment by Tudjack** [comment]
I can't upload the ifc file here due to very strict NDA, but I will join the osarch.org chat and maybe we can have a screenshare when you are available
