### ISSUE TITLE
Regression: Opening subtraction fails on wall (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#507]
**Steps to reproduce:**
1. Convert [507--opening-subtraction-failed.ifc](https://github.com/IfcOpenShell/files/blob/master/507--opening-subtraction-failed.ifc) with e64d875 (OCCT 7.3.0)
2. Experience that the conversion outputs geometry, but that no openings are subtracted from the wall:
<img width="300" alt="screenshot 2018-11-19 at 15 28 54" src="https://user-images.githubusercontent.com/4601554/48713462-9e0bb780-ec10-11e8-9ce9-fb8b83cc7eca.png">

```
[Error] {2H080rBBb77ApRk4hb6mlR} Opening subtraction failed:
#26=IfcWallStandardCase('2H080rBBb77ApRk4hb6mlR',#8,'Basic Wall:BIV Betong 200mm :1138057',$,'Basic Wall:BIV Betong 200mm :1086064',#343,#27,'1138057')
``` 

3. Convert the same file with 6c1ad47 – experience no errors and that the openings are subtracted correctly:
<img width="300" alt="screenshot 2018-11-19 at 15 27 30" src="https://user-images.githubusercontent.com/4601554/48713520-cc899280-ec10-11e8-9df2-e27a1145a2c4.png">

There seems to be a regression – possibly related to #478.

**Comment by aothms** [comment]
This was related to the handling of halfspaces actually, indeed somewhat recently introduced. There was a silly mistake there actually moving the halfspace plane rather than expanding it to cover for tolerance and fuzziness. Hopefully this closes some of the other open issues as well.

https://github.com/IfcOpenShell/IfcOpenShell/commit/4afd104f3dac3242f47c5b8c671222e8f811d645

**Comment by johanrd** [comment]
Thanks. verified – 4afd104 seems to do the trick. Testing also indicates that #471 is in somewhat better shape. 

#478, #474, #456, #425, #380 and #392 does not seem to be affected by this fix, though.

**Comment by johanrd** [comment]
Should be reopened, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)
