### ISSUE TITLE
Feiled installation of BlenderBIM add-on

### ISSUE THREAD

**Issue by Ri-chardG** [IfcOpenShell/IfcOpenShell#5070]
I have downloaded blenderbim-240602-py311-win.zip and followed the installation guide https://docs.blenderbim.org/users/quickstart/installation.html#installation-location.

I get the following error msg from blender after the installation:

os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
blender_version: 4.2.0
blenderbim_version: 0.0.240602
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\richard.garner\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\__init__.py", line 96, in <module>
    import blenderbim.bim
ModuleNotFoundError: No module named 'blenderbim'

![2024-07-23 22_53_01-New Issue · IfcOpenShell_IfcOpenShell og 6 sider til – Arbeid – Microsoft​ Edge](https://github.com/user-attachments/assets/9f4b166a-a17f-4160-a740-febc790ffcba)

**Comment by Moult** [comment]
See #4373
