### ISSUE TITLE
bSDD assigning problem

### ISSUE THREAD

**Issue by chkwong02151949** [IfcOpenShell/IfcOpenShell#5073]
Currently I want to assign a bSDD to a IFC2x3 model, but something got wrong.
Can somebody help me? My version is blender 4.1.1 with blenderbim add_on v0.0.240602
![image](https://github.com/user-attachments/assets/9aa8cebe-1c4c-4aa1-9973-94647893d61c)

**Comment by Andrej730** [comment]
@chkwong02151949 
Fixed in the latest build, thank you for the bug report.
