### ISSUE TITLE
Extra unit assignment causes units to default to meters

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5074]
In the attached file (with lots of fun weird invalid data) there are two IfcUnitAssignment entities. Although the second one is orphaned (not referenced from the project) and although they both define millimeter length units, it seems as though if the second one exists, IfcOpenShell will treat the length unit as meters.

[2HPX1265AC1N1A-purged_data.ifc.txt](https://github.com/user-attachments/files/16360646/2HPX1265AC1N1A-purged_data.ifc.txt)

In 0.7.0 apparently the behaviour was that it would still (intuitively) treat it as millimeters.

```
# Delete this line to see the change in behaviour
#1513=IFCUNITASSIGNMENT((#1514,#1515,#1516,#1517,#1518,#1519,#1520,#1521,#1522,#1523,#1524));
```

```python
import ifcopenshell
import ifcopenshell.geom
start = time.time()
ifc_file = ifcopenshell.open('/home/dion/tmp/2HPX1265AC1N1A-purged_data.ifc')

settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, ifc_file.by_id(1))
print(max(shape.geometry.verts)) # 5500.00000000047

ifc_file.remove(ifc_file.by_id(1513))
shape = ifcopenshell.geom.create_shape(settings, ifc_file.by_id(1))
print(max(shape.geometry.verts)) # 5.500000000000471
```

**Comment by aothms** [comment]
Should be fixed,, I think another one of these cases where the old monster IfcGeom.cpp was not properly merged back.
