### ISSUE TITLE
Launching bbim, recent unstable builds

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#5079]
Hi,
I see some problems with launching bim addon in recent daily releases (unstable).

1. In all cases bbim can be installed successfully
2. Sometimes, after installation, it is not listed. In that cases installation file has ~75MB, I used to see ~105MB. Maybe  something is missing.

![image](https://github.com/user-attachments/assets/4dbc1974-0365-42bd-9eae-5dde5f3e7e09)

3. Sometimes, if listed, it can't be launched - some errors occurs, details below.

I tested bunch of recent releases, I use Blender 4.1.1, 64-bit

---

**[release title: blenderbim-0.7.11-alpha240724 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.11-alpha240724)**
installation file name: blenderbim_py311-0.7.11-alpha240724-windows-x64.zip
installation file size: 75.4 MB
installation: ok
bbim listed: no
can be launched: no

---

**[blenderbim-0.7.11-alpha240723 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.11-alpha240723)**
blenderbim_py310-0.7.11-alpha240723-windows-x64.zip
75.3 MB
installation: ok
bbim listed: no
can be launched: no

---

**[blenderbim-0.7.11-alpha240722 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.11-alpha240722)**
blenderbim_py310-0.7.11-alpha240722-windows-x64.zip
75.4 MB
installation: ok
bbim listed: no
can be launched: no

---

**[blenderbim-240722: whoops](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-240722)**
blenderbim-240722-py311-win.zip
84.7 MB
installation: ok
bbim listed: yes
can be launched: no, error:

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240722
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 96, in <module>
    import blenderbim.bim
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\__init__.py", line 30, in <module>
    from blenderbim.tool.document import Document
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\document.py", line 23, in <module>
    from blenderbim.bim import import_ifc
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 44, in <module>
    from blenderbim.tool.loader import OBJECT_DATA_TYPE
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\loader.py", line 42, in <module>
    class Loader(blenderbim.core.tool.Loader):
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\loader.py", line 59, in Loader
    def get_mesh_name(cls, geometry: ifcopenshell.geom.ShapeType) -> str:
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ifcopenshell.geom' has no attribute 'ShapeType'
```

---

**[blenderbim-0.7.11-alpha240721 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.11-alpha240721)**
blenderbim_py311-0.7.11-alpha240721-windows-x64.zip
75.4 MB
installation: ok
bbim listed: no
can be launched: no

---

**[blenderbim-0.7.11-alpha240720 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.11.240720)**
blenderbim_py311-0.7.11-alpha240720-windows-x64.zip
75.4 MB
installation: ok
bbim listed: no
can be launched: no

---

**[blenderbim-0.7.10-alpha240719 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.10.240719)**
blenderbim_py311-0.7.10-alpha240719-windows-x64.zip
75.4 MB
installation: ok
bbim listed: no
can be launched: no

---

**[blenderbim-0.7.10-alpha240718 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.10.240718)**
blenderbim_py311-0.7.10-alpha240718-windows-x64.zip
75.3 MB
installation: ok
bbim listed: no
can be launched: no

---

**[blenderbim-0.7.10.240717 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.10.240717)**
blenderbim-0.7.10.240717-py311-win.zip
108 MB <------------
installation: ok
bbim listed: yes
can be launched: **yes!** <------------

---

**[blenderbim-0.7.10.240716 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.10.240716)**
blenderbim-0.7.10.240716-py311-win.zip
108 MB <------------
installation: ok
bbim listed: yes
can be launched: no, error:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 176, in register
    import blenderbim.bim
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 96, in <module>
    modules[name] = importlib.import_module(f"blenderbim.bim.module.{name}")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\light\__init__.py", line 20, in <module>
    from . import ui, prop, operator
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\light\ui.py", line 20, in <module>
    from blenderbim.bim.module.light.data import SolarData
ModuleNotFoundError: No module named 'blenderbim.bim.module.light.data'
```

---

**[blenderbim-0.7.10.240715 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.10.240715)**
blenderbim-0.7.10.240715-py311-win.zip
102 MB <------------
installation: ok
bbim listed: yes
can be launched: **yes!** <------------

---

**[blenderbim-0.7.9.240714 (unstable)](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-0.7.9.240714)**
blenderbim-0.7.9.240714-py311-win.zip
102 MB <------------
installation: ok
bbim listed: yes
can be launched: **yes!** <------------

--

I hope it will be useful, somehow.

**Comment by Moult** [comment]
The latest releases are all "no" because they should only work on Blender 4.2. Can you test on Blender 4.2?

**Comment by ppaawweeuu** [comment]
> Can you test on Blender 4.2?

yes, that was my problem. thank you.
I installed Blender 4.2 and...

---
blenderbim-0.7.11-alpha240726 (unstable)
blenderbim_py311-0.7.11-alpha240726-windows-x64.zip
OK

---
blenderbim-0.7.11-alpha240725 (unstable)
blenderbim_py311-0.7.11-alpha240725-windows-x64.zip
OK

---
blenderbim-0.7.11-alpha240724 (unstable)
blenderbim_py311-0.7.11-alpha240724-windows-x64.zip
OK

---
blenderbim-0.7.11-alpha240723 (unstable)
blenderbim_py311-0.7.11-alpha240723-windows-x64.zip
OK

---
blenderbim-0.7.11-alpha240722 (unstable)
blenderbim_py311-0.7.11-alpha240722-windows-x64.zip
75.4 MB
OK

---
blenderbim-0.7.11-alpha240721 (unstable)
blenderbim_py311-0.7.11-alpha240721-windows-x64.zip
75.4 MB
OK

---
blenderbim-0.7.11-alpha240720 (unstable)
blenderbim_py311-0.7.11-alpha240720-windows-x64.zip
75.4 MB
OK

---
blenderbim-0.7.10-alpha240719 (unstable)
blenderbim_py311-0.7.10-alpha240719-windows-x64.zip
75.4 MB
OK

---
blenderbim-0.7.10-alpha240718 (unstable)
blenderbim_py311-0.7.10-alpha240718-windows-x64.zip
75.3 MB
OK
