### ISSUE TITLE
Error on creating BCF report because of numpy version 2

### ISSUE THREAD

**Issue by ClimenteA** [IfcOpenShell/IfcOpenShell#5080]
Hi,

I was trying to create a BCF report, but it seems numpy version 2 has broken some of the functionality of ifctester package.

Pinning it to version 1 would fix this issue for now (until you get some time to update the package):

`dependencies = ["ifcopenshell", "python-dateutil", "xmlschema", "numpy==1.26.4"]`

Thank you!

**Comment by Moult** [comment]
Thanks for the report! Can you provide a bit more details on what the error is? Would you be able to help submit a PR?

**Comment by ClimenteA** [comment]
In numpy v2 they added a lot of breaking changes. It failed because of a numpy type: ``float_

**Comment by Andrej730** [comment]
Can you please provide the error traceback?

**Comment by ClimenteA** [comment]
Sorry, just ended my contract with that company. I don't have access to the code anymore 😅. 

Create an BCF report with IDS as an input - you'll get a traceback related to numpy float types (np.float_ is not available anymore).
