### ISSUE TITLE
Columns showing as crosses only

### ISSUE THREAD

**Issue by EdgarWesterhoven** [IfcOpenShell/IfcOpenShell#5081]
Ok in version 4.0 the columns were displaying as columns. Because they had no IfcColumnType I started my journey to add this. Because of errors in 4.0 I moved to 4.2 and the latest IfcOpenshell. 

In 4.2 there is a great new panel telling me that I have untyped colums. 

![image](https://github.com/user-attachments/assets/7018cb89-262d-4c75-bdd5-40cc37756766)

![image](https://github.com/user-attachments/assets/8a09434c-10a8-41b1-a3b8-480fe3b429e1)

My thinking was I first need to create a couple of ColumnTypes through the modelling too. Though this works totally fine in a new model. When I try adding a colum in an existing file I get an error.

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
blender_version: 4.2.0
blenderbim_version: 0.7.11-alpha240724
blenderbim_commit_hash: 8b29e50
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 72, "Name": "Column"}}
# ifcopenshell.api: pset.add_pset
>>> {"product": {"cast_type": "entity_instance", "value": 72, "Name": "Column"}, "name": "EPset_Parametric"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: pset.edit_pset
>>> {"pset": {"cast_type": "entity_instance", "value": 93, "Name": "EPset_Parametric"}, "properties": "{'Engine': 'BlenderBIM.DumbProfile'}"}
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_add_default_type
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_enable_add_type
# operator: BIM_OT_add_type
last_error: Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\model\product.py", line 106, in _execute
    props.type_predefined_type = "COLUMN"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "COLUMN" not found in ()

ifc: 240715.ifc
schema: IFC4X2
preprocessor_version: 3DEXPERIENCE Platform3DEXPERIENCE R2024x HotFix 4.6
originating_system: 3DEXPERIENCE Platform IFC4X2
```

**Comment by Moult** [comment]
The missing columns could be due to a bug in v0.8.0. It may actually already be fixed, just that the IfcOpenBot builds are a bit outdated (ping @aothms ?) Can you share your IFC so that I can check it? dion@thinkmoult.com if private

> When I try adding a colum in an existing file I get an error.

This is because your model coming is using a non official IFC schema (e.g. a work in progress, or development version). You need to file a bug with 3DEXPERIENCE, but in the meantime you might get a bit more support if you manually edit the file and change IFC4X2 to IFC4X3. Note that this is only a quick fix and some things still may break depending on what data is in the file and if it is incompatible with the actual IFC4X3.

**Comment by EdgarWesterhoven** [comment]
Tried the text, but same model distortion appears.

Let me take that info to 3DEXPERIENCE.

**Comment by EdgarWesterhoven** [comment]
The crosses instead of the columns as shown in the picture. No worries I will wait for the latest Alpha.

**Comment by EdgarWesterhoven** [comment]
With blenderbim_py311-0.7.11-alpha240730-windows-x64 I no longer have this issue. 

Please close :-)
