### ISSUE TITLE
"blenderbim couldn't load" I get this error when tried download blenderbim addon to blender 4.2 ... any help??

### ISSUE THREAD

**Issue by albezreh** [IfcOpenShell/IfcOpenShell#5083]
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
blender_version: 4.2.0
blenderbim_version: 0.0.240602
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\aalbe\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\__init__.py", line 96, in <module>
    import blenderbim.bim
ModuleNotFoundError: No module named 'blenderbim'

**Comment by Moult** [comment]
See #4373

**Comment by albezreh** [comment]
it works now, thank you so much
