### ISSUE TITLE
IDS Checking problem

### ISSUE THREAD

**Issue by chkwong02151949** [IfcOpenShell/IfcOpenShell#5085]
Dear community
I am now trying to do IDS checking to the on my model, but I try many time, I can only can with Pset_ManufacturerTypeInformation, for Pset_ManufacturerOccurrence, no mattter what data type it is , I can not check it.  Also I can not check the RefLatitude and RefLongitude. Can anybody help? I am using blender4.1 with add_on240206 wins py11
Here is the screenshot for the info, and the ids code
![image](https://github.com/user-attachments/assets/6767d749-fc41-4fea-90e8-a8697835466c)
![image](https://github.com/user-attachments/assets/3b1d93ec-de43-4a57-9c5a-01b5ebaf0a15)
![image](https://github.com/user-attachments/assets/60108d3b-5478-46ac-a4e2-ed74a55f94b4)
![image](https://github.com/user-attachments/assets/ca7e9d54-a5d3-407c-b2d9-3bf504f84372)
[tst.txt](https://github.com/user-attachments/files/16385844/tst.txt)

**Comment by chkwong02151949** [comment]
Here is the ids code:
<ids:ids xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS http://standards.buildingsmart.org/IDS/1.0/ids.xsd" xmlns:ids="http://standards.buildingsmart.org/IDS">
  
  <ids:info>
    <ids:title>BIMBASIC</ids:title>
    <ids:author>123@gmail.com</ids:author>
  </ids:info>
  <ids:specifications>
    <ids:specification ifcVersion="IFC4" name="site" description="Sustainability Assessment site">
      <ids:applicability minOccurs="1" maxOccurs="unbounded">
        <ids:entity>
          <ids:name>
            <ids:simpleValue>IFCSITE</ids:simpleValue>
          </ids:name>
        </ids:entity>
      </ids:applicability>
      <ids:requirements>
        <ids:attribute cardinality="required">
          <ids:name>
            <ids:simpleValue>Name</ids:simpleValue>
          </ids:name>
          <ids:value>
            <ids:simpleValue>Chung Hau St, Ho Man Tin</ids:simpleValue>
          </ids:value>
        </ids:attribute>
        <ids:attribute cardinality="required" instructions="location of site">
          <ids:name>
            <ids:simpleValue>RefLatitude</ids:simpleValue>
          </ids:name>
          <ids:value>
            <ids:simpleValue>(22, 18, 31)</ids:simpleValue>
          </ids:value>
        </ids:attribute>
        <ids:attribute cardinality="required" instructions="location of site">
          <ids:name>
            <ids:simpleValue>RefLongitude</ids:simpleValue>
          </ids:name>
          <ids:value>
            <ids:simpleValue>(114, 10, 52)</ids:simpleValue>
          </ids:value>
        </ids:attribute>
        <ids:attribute cardinality="required" instructions="length">
          <ids:name>
            <ids:simpleValue>RefElevation</ids:simpleValue>
          </ids:name>
          <ids:value>
            <ids:simpleValue>5</ids:simpleValue>
          </ids:value>
        </ids:attribute>
      </ids:requirements>
    </ids:specification>
    <ids:specification ifcVersion="IFC4" name="IFCROOF1" description="Sustainability Assessment to Manufacturing">
      <ids:applicability minOccurs="0" maxOccurs="unbounded">
        <ids:entity>
          <ids:name>
            <ids:simpleValue>IFCROOF</ids:simpleValue>
          </ids:name>
        </ids:entity>
        <ids:attribute>
          <ids:name>
            <ids:simpleValue>Name</ids:simpleValue>
          </ids:name>
          <ids:value>
            <ids:simpleValue>Basic Roof:IC_ROOF_1:384505</ids:simpleValue>
          </ids:value>
        </ids:attribute>
      </ids:applicability>
      <ids:requirements>
        <ids:property dataType="IFCIDENTIFIER" cardinality="required">
          <ids:propertySet>
            <ids:simpleValue>Pset_ManufacturerTypeInformation</ids:simpleValue>
          </ids:propertySet>
          <ids:baseName>
            <ids:simpleValue>GlobalTradeItemNumber</ids:simpleValue>
          </ids:baseName>
          <ids:value>
            <ids:simpleValue>123456789</ids:simpleValue>
          </ids:value>
        </ids:property>
        <ids:property dataType="IFCIDENTIFIER" cardinality="required" instructions="datetime">
          <ids:propertySet>
            <ids:simpleValue>Pset_ManufacturerOccurence</ids:simpleValue>
          </ids:propertySet>
          <ids:baseName>
            <ids:simpleValue>BatchReference</ids:simpleValue>
          </ids:baseName>
          <ids:value>
            <ids:simpleValue>polyuIC</ids:simpleValue>
          </ids:value>
        </ids:property>
        <ids:property dataType="IFCLABEL" cardinality="required" instructions="datetime">
          <ids:propertySet>
            <ids:simpleValue>Pset_ManufacturerOccurence</ids:simpleValue>
          </ids:propertySet>
          <ids:baseName>
            <ids:simpleValue>AssemblyPlace</ids:simpleValue>
          </ids:baseName>
          <ids:value>
            <ids:simpleValue>FACTORY</ids:simpleValue>
          </ids:value>
        </ids:property>
        <ids:property dataType="IFCIDENTIFIER" cardinality="required" instructions="datetime">
          <ids:propertySet>
            <ids:simpleValue>Pset_ManufacturerOccurence</ids:simpleValue>
          </ids:propertySet>
          <ids:baseName>
            <ids:simpleValue>BarCode</ids:simpleValue>
          </ids:baseName>
          <ids:value>
            <ids:simpleValue>123123</ids:simpleValue>
          </ids:value>
        </ids:property>
        <ids:property dataType="IFCIDENTIFIER" cardinality="required" instructions="datetime">
          <ids:propertySet>
            <ids:simpleValue>Pset_ManufacturerOccurence</ids:simpleValue>
          </ids:propertySet>
          <ids:baseName>
            <ids:simpleValue>SerialNumber</ids:simpleValue>
          </ids:baseName>
          <ids:value>
            <ids:simpleValue>321321</ids:simpleValue>
          </ids:value>
        </ids:property>
      </ids:requirements>
    </ids:specification>
  </ids:specifications>
</ids:ids>

**Comment by Moult** [comment]
> I can only can with Pset_ManufacturerTypeInformation, for Pset_ManufacturerOccurrence, no mattter what data type it is

You have spelled Pset_ManufacturerOccurrence wrong in your IDS. It should have two Rs.

> Also I can not check the RefLatitude and RefLongitude

This is a limitation of IDS. IDS cannot check these values because they are not simple primitive types.

**Comment by chkwong02151949** [comment]
Thx for your ans, really helpful. I have one more question, can IDS check the classification of the bSDD that assign to a specific element?
![image](https://github.com/user-attachments/assets/03413648-14f0-412b-836e-85f694e4b597)
![image](https://github.com/user-attachments/assets/6337d79b-6f69-4e32-9dd0-06a8c7c03f31)
<ids:ids xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS http://standards.buildingsmart.org/IDS/1.0/ids.xsd" xmlns:ids="http://standards.buildingsmart.org/IDS">
  
  <ids:info>
    <ids:title>tst_classification</ids:title>
    <ids:author>123@gmail.com</ids:author>
  </ids:info>
  <ids:specifications>
    <ids:specification ifcVersion="IFC4" name="Classification">
      <ids:applicability minOccurs="1" maxOccurs="unbounded">
        <ids:attribute>
          <ids:name>
            <ids:simpleValue>Name</ids:simpleValue>
          </ids:name>
          <ids:value>
            <ids:simpleValue>Basic Roof:IC_ROOF_1:384505</ids:simpleValue>
          </ids:value>
        </ids:attribute>
      </ids:applicability>
      <ids:requirements>
        <ids:classification cardinality="required">
          <ids:value>
            <ids:simpleValue>ZCP Asset Information for Architectural Components (Design Stage)</ids:simpleValue>
          </ids:value>
          <ids:system>
            <ids:simpleValue>ReferencedSource</ids:simpleValue>
          </ids:system>
        </ids:classification>
        <ids:classification cardinality="required">
          <ids:value>
            <ids:simpleValue>https://identifier.buildingsmart.org/uri/bimnity/ZlP_LOD-I_300_AR/1.0.0/class/ROF</ids:simpleValue>
          </ids:value>
          <ids:system>
            <ids:simpleValue>Location</ids:simpleValue>
          </ids:system>
        </ids:classification>
      </ids:requirements>
    </ids:specification>
  </ids:specifications>
</ids:ids>

**Comment by Moult** [comment]
No, IDS can only check the classification identification code, it cannot check the location.

**Comment by chkwong02151949** [comment]
noted
