### ISSUE TITLE
assign which ifc classes display as wireframe (wire) upon opening the ifc file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5086]
Would be nice to be able to assign which ifc classes display as wireframe (wire) upon opening the ifc file

![image](https://github.com/user-attachments/assets/c017ff57-45ba-491a-9b65-671f34de3520)

**Comment by Moult** [comment]
I'd prefer more control in the new spatial tree panel - buttons for quick visibility settings similar to other viewers

**Comment by theoryshaw** [comment]
Is that something we'd have to set every time we open an ifc file?

**Comment by Moult** [comment]
Yes but I think the default should be that spaces and virtual elements are hidden anyway as in 99% of cases that's the first thing I do (and everybody else too I assume)
