### ISSUE TITLE
Segfault when trying to create shape for wall with boolean clipping

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5087]
This seems to work on v0.7.0 but segfaults now it seems:

[segfault.txt](https://github.com/user-attachments/files/16386948/segfault.txt)

```python
import ifcopenshell
import ifcopenshell.geom
start = time.time()
ifc_file = ifcopenshell.open('/home/dion/segfault.ifc')

settings = ifcopenshell.geom.settings()
print(ifc_file.by_id(129))
shape = ifcopenshell.geom.create_shape(settings, ifc_file.by_id(129))
print(max(shape.geometry.verts))
```

**Comment by Moult** [comment]
I think this is another file exhibiting the same issue, but not sure.

[segfault.txt](https://github.com/user-attachments/files/16422018/segfault.txt)


```
import ifcopenshell
import ifcopenshell.geom
ifc_file = ifcopenshell.open('/home/dion/segfault.ifc')

settings = ifcopenshell.geom.settings()
print(ifc_file.by_id(84))
shape = ifcopenshell.geom.create_shape(settings, ifc_file.by_id(84))
settings.set("keep-bounding-boxes", True)
print(max(shape.geometry.verts))
print(max(shape.geometry.edges))
print(max(shape.geometry.faces))
```

**Comment by aothms** [comment]
Cannot reproduce, neither file on neither win nor linux. The 2nd file doesn't return geometry on my end, but neither does e.g bimvision. Do you have a stacktrace just to get a rough idea what's going on?

**Comment by Moult** [comment]
Hmm yeah I can't recreate the segfault on the first file now. Maybe it got fixed between the previous bot build and the latest bot build.

Yeah the second doesn't return geometry for me.

**Comment by Moult** [comment]
Reopening because this seems to be happening on a large number of objects, see https://github.com/IfcOpenShell/IfcOpenShell/issues/5114#issuecomment-2265365150
