### ISSUE TITLE
Online IFC Doc links broken

### ISSUE THREAD

**Issue by ppaawweeuu** [IfcOpenShell/IfcOpenShell#5092]
In 20240726 build all "Online IFC Documentation" links seem to be broken.
Instead of a web browser and the ifc website, a new file browser window opens.
I use Blender 4.2, Windows 10 Pro, 64bit

![image](https://github.com/user-attachments/assets/2605d760-d0be-4cce-8ffb-541e0c354534)

20240725 build works fine.

![image](https://github.com/user-attachments/assets/688a1484-af1b-45ef-9b40-f30360e29baa)

**Comment by Andrej730** [comment]
thank you for reporting the issue!
