### ISSUE TITLE
search-ifc-class should be a link in docs.blenderbim.org

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#5097]
It's not clear to me how to navigate to https://blenderbim.org/search-ifc-class.html from blenderbim.org.

I looked for it in BlenderBIM Documentation https://docs.blenderbim.org/ but couldn't find it. Should it be located in the Quickstart section?

![image](https://github.com/user-attachments/assets/0b4cc2d2-f327-4d71-afca-fb10f525221f)

**Comment by Moult** [comment]
It's mentioned briefly here https://docs.blenderbim.org/users/quickstart/explore_model.html#viewing-element-classes

But yeah we need to find a proper place (not in the docs, but perhaps the main site?) to link to it.
