### ISSUE TITLE
Respect the assumptions of the buildingSMART online validation service

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#5098]
I have tried the validation service at [https://validate.buildingsmart.org/](https://validate.buildingsmart.org/) with a new IFC4 file created with BlenderBIM (without further content). The service criticises that the industry practices are not adhered to because the ‘correct’ context identifiers are not used: GEM052 - Correct geometric subcontexts

The expected ([valid_RepresentationType_IFC4.csv](https://github.com/buildingSMART/ifc-gherkin-rules/blob/f7dcaac762beb0c613d46f29fe94ca8aa778f9dd/features/resources/valid_RepresentationType_IFC4.csv#L4)) are listed under [https://github.com/buildingSMART/ifc-gherkin-rules/tree/f7dcaac762beb0c613d46f29fe94ca8aa778f9dd/features/resources](https://github.com/buildingSMART/ifc-gherkin-rules/tree/f7dcaac762beb0c613d46f29fe94ca8aa778f9dd/features/resources).

I consider it desirable that the validation does not fail here. Unfortunately, I cannot judge whether the listing of the expected designations is useful.

![Screenshot 2024-07-28 at 16 58 15](https://github.com/user-attachments/assets/9565e30f-7862-4465-894a-ff00db21095f)

**Comment by Moult** [comment]
I think this is a bug in the validation service, our files should be good. I've posted a fix here: https://github.com/buildingSMART/ifc-gherkin-rules/pull/249
