### ISSUE TITLE
IfcCurtainWall materialises as IfcPlate

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#510]
1. Convert [510--curtainWall.ifc](https://github.com/IfcOpenShell/files/blob/master/510--curtainWall.ifc)
2. Experience that the material output file indicates that this is an object of type IfcPlate:
```
# File generated by IfcOpenShell 0.5.0-dev
newmtl IfcPlate
Kd 0.623 0.588 0.588
```
3. Open the same file in Solibri, SimpleBIM or DDS, and experience that the object is identified as an IfcCurtainWall:
<img width="500" alt="screenshot 2018-11-23 at 16 57 01" src="https://user-images.githubusercontent.com/4601554/48952179-8d757d00-ef41-11e8-9845-0eac880d0b8c.png">

Why and how Solibri, SimpleBIM and DDS Viewer identifies this object as IfcCurtainWall, whereas IfcOpenShell does not, is an open question. We suspect this to be because the Representation field for the IfcCurtainWall (16) is empty, whereas the Representation field for the IfcPlate (17) is not. ?

```
#16 = IFCCURTAINWALL('1B_7AJ4KzDCA75nn0euTas', #8, '', $, '', #178, $, '4BF87293-494F-4D30-A1C5-C71028E1D936');
#17 = IFCPLATE('1gFYXDFmv588C4tPGaUJCB', #8, '', $, '', #181, #18, '6A3E284D-3F0E-4520-8308-DD942479330B');
```

**Comment by aothms** [comment]
In Solibri you can also still go down to the level of IfcPlates and IfcMembers, but only in the tree view [in which selection is not synced with 3d :( ]

In IfcOpenShell you can get this hierarchy if you convert to .DAE with `--use-element-hierarchy` or convert to .XML.

In the end I think this is a matter of UI and not so much of the converter. The current way IfcOpenShell works I think is the most sensible default. Grouping geometry for decomposing elements can be added as an option, but it will likely make detecting geometrical instances more difficult.

**Comment by johanrd** [comment]
Ok, I think we can close this as an issue then. Makes sense. Thanks for checking.
