### ISSUE TITLE
Python package of ifcopenshell is broken on Red Hat 9.x and derivatives and Ubuntu 20.04

### ISSUE THREAD

**Issue by saprykin** [IfcOpenShell/IfcOpenShell#5111]
Starting from the version 0.7.10, it seems that `ifcopenshell` Python packages are being compiled using a newer version of glibc 2.35, while some stable Linux distributions like Red Hat 9.x and its derivatives (Alma Linux, Rocky Linux, etc.) still use glibc 2.34. The last changes in the `ifcopenshell` package break compatibility with the stable versions of these Linux distributions. Is there any way to keep the compatibility of provided packages?

**Comment by aothms** [comment]
I think you raise a valid point. RHEL-9.4 is still 8 years until end of life. We should probably support that in the builds. If you can recommend a linux distro that is compatible with rhel 9.4 that is available free of charge as an Amazon AMI (because that's what we use for our builds) that is able to run the nix/build-all.py (or submit improvements so that it does) than I'm 100% in favour of making the necessary changes to our build infra.

**Comment by saprykin** [comment]
AlmaLinux and Rocky Linux should be binary compatible with Red Hat, and both are freely available. I tested on Rocky Linux, and it also has glibc 2.34, and recent versions of `ifcopenshell` fail there.

**Comment by Moult** [comment]
Blender follows the VFX Reference Platform - I don't know if this is something IfcOpenShell also wants to follow: https://vfxplatform.com/

**Comment by Andrej730** [comment]
Currently available from bot builds starting from https://github.com/IfcOpenBot/IfcOpenShell/commit/68062f54d8d8163d97d58ad2879c8545565cd479#commitcomment-148395598, will be fixed for pip after the next release.

**Comment by SigveMartin** [comment]
Think I get the same issue trying to compile on streamlit cloud:

```
ImportError: IfcOpenShell not built for 'linux/64bit/python3.11'

ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found 

(required by 

/home/adminuser/venv/lib/python3.11/site-packages/ifcopenshell/_ifcopenshell_wrapper.cpython-311-x86_64-linux-gnu.so)
```

Latest version on PyPI now is 0.8.0. I guess the 0.8.1 version is coming soon and should fix this. Adding this for future reference.

**Comment by adthoms** [comment]
> Currently available from bot builds starting from [IfcOpenBot@68062f5#commitcomment-148395598](https://github.com/IfcOpenBot/IfcOpenShell/commit/68062f54d8d8163d97d58ad2879c8545565cd479#commitcomment-148395598), will be fixed for pip after the next release.

@Andrej730 is there a new target release date for 0.8.1?
