### ISSUE TITLE
Remove all the failed shapes, in bulk. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5114]
After running 'Test All Shapes' it would nice if there was a utility that you could use to remove all the failed shapes, in bulk.

**Comment by steverugi** [comment]
please how do you run 'Test All Shapes'? thanks

**Comment by Andrej730** [comment]
Are there that many failing shapes currently? :\

@steverugi 
![image](https://github.com/user-attachments/assets/0ce9e03c-0e90-4d96-bc6e-ef7fd54daa9d)

**Comment by steverugi** [comment]
thanks @Andrej730, not really, at least for now :)

**Comment by Moult** [comment]
The issue is that the tool doesn't differentiate between shapes failing because the shape is invalid, or shapes failing because IfcOpenShell has a bug :)

That said yes we should add it.

**Comment by theoryshaw** [comment]
> Are there that many failing shapes currently? :\

Here's an example of a lot of failing shapes...
https://hub.openingdesign.com/OpeningDesign/Rae_Living_Room_Ext/src/commit/06ae2f09ecb9d7d008cc6f7d6908e1a186405f48/Open/Models/BlenderBIM/Rae_Living_Room_Ext.ifc

Not sure what happened. :\

**Comment by Moult** [comment]
So back in the last stable release it would report 117 failed shapes, and same right now, so there's no change.

Also actually there are no failed shapes. The code is pretty dumb in that it attempts to create shapes for elements which have no shapes (and then fails) and then it reports it as a failure when actually it's just an object which legitimately has no shape. So the actual number is zero.
