### ISSUE TITLE
compile error C2664

### ISSUE THREAD

**Issue by vipcxj** [IfcOpenShell/IfcOpenShell#512]
https://github.com/IfcOpenShell/IfcOpenShell/blob/747ddeb20cc9083ba4281d7ddb283ac0e1bd0e12/src/ifcwrap/IfcParseWrapper.i#L89

`$self->types_begin()` and `$self->types_end()` are iterator of `std:pair<Ifc4::Type::Enum, IfcEntityList::ptr>`. And the sig of `IfcSchema::Type::ToString` is `const std::string& Type::ToString(Ifc4::Type::Enum v)`. It caused the compile error.

**Comment by aothms** [comment]
`types_begin()` and `_end()`  are of type `IfcParse::IfcFile::type_iterator` [1] which dereferences to `first` of the pair [2]. Compilation is successful [2] on Travis and my local MSVC machine. What compiler are you using?

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcFile.h#L44
[2] https://travis-ci.org/IfcOpenShell/IfcOpenShell/builds/458749007

**Comment by vipcxj** [comment]
the latest vs2017

**Comment by vipcxj** [comment]
F:\cxj\software\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\algorithm(1443): error C2664: “const std::string &(Ifc4::Type::Enum)”: 无法将参数 1 从“const std::pair<const _Kty,_Ty>”转换为“Ifc4::Type::Enum”[F:\cxj\project\java\IfcOpenShell\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]

**Comment by aothms** [comment]
The project name `ifcwrap_ifcopenshell_wrapper.vcxproj` differs from standard CMake usage. How did you generate the project? How do you invoke SWIG?

Instead of doing things manually, running [1] from the VS 2017 Developer Command Prompt will take care of everything in a tested and reliable way.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd

**Comment by vipcxj** [comment]
I run `build-all.cmd vs2017-x64 RelWithDebInfo -DUSE_IFC4=1 -DENABLE_BUILD_OPTIMIZATIONS=1` in the  VS 2017 Developer Command Prompt. Not manually.
My windows sdk version is 10.0.17763.0
My visual studio version is 15.9.2

**Comment by vipcxj** [comment]
@aothms If you give me a email address, I can send you my `build-vs2017-x64` directory. `deps` and `deps-vs2017-x64-installed` is too big to upload. Or I upload it to a [net disc](https://pan.baidu.com/s/1xIBbQte58sMZGB3dO4lR9w) , password: w8rj

**Comment by e3dEF** [comment]
Maybe I forgot some step? This was my chain:

- set IFCOS_INSTALL_PYTHON=FALSE in build-deps.com
- .\buid-deps.cmd
- edit BuildDepsCache-x64
GEN_SHORTHAND=vs2017-x64
OCC_INCLUDE_DIR=E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\deps-vs2017-x64-installed\opencascade-7.3.0\inc
OCC_LIBRARY_DIR=E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\deps-vs2017-x64-installed\opencascade-7.3.0\win64\lib
PY_VER_MAJOR_MINOR=35
PYTHONHOME=E:\Programme\Miniconda3_4.2.12_Py3.5
- .\run-cmake.bat
- .\install-ifcopenshell.bat

Is there another way, that I could try?
Thank you for your help and kind regards!

**Comment by vipcxj** [comment]
@aothms 
have send

**Comment by aothms** [comment]
Thanks. It seemed you cleaned the project / solution at some point. All I can see is the output from the Clean command (_ifcopenshell_wrapper.Build.CppClean.log). If you open the solution (IfcOpenShell.sln) in Visual Studio, select `RelWithDebInfo` as the configuration and just build the _ifcopenshell_wrapper project. Can you give me the full output from the build log? Thanks.

**Comment by aothms** [comment]
> Can you give me the full output from the build log? Thanks.

It's not necessary anymore.

>  My visual studio version is 15.9.2

I updated Visual Studio and can now reproduce the issue. My version was rather old, but it's odd that a minor version update can cause such discrepancies. It seems there are people running into similar issues with custom iterators, e.g. https://developercommunity.visualstudio.com/content/problem/343613/compilation-error-when-using-custom-iterator-with.html

Probably IfcFile::type_iterator doesn't match the expectations of MSVC anymore. It's quite hackish anyway. Probably inheriting from std::map::iterator was a bad idea, as MSVC now picks up something from the base class. I won't be able to get to this anymore this week. Probably next week. Feel free to have a look yourself if interested.

**Comment by aothms** [comment]
Should be fixed now, thanks for reporting.

**Comment by Stinkfist0** [comment]
Hi, can you pick this commit also to master? I'm getting the same problem now also after updating VS.

**Comment by aothms** [comment]
@Stinkfist0 oops, I thought this thing was 0.6 only. Thanks! https://github.com/IfcOpenShell/IfcOpenShell/commit/bb154468226d7b49c6a9daea8c524874ebbbcb3d
