### ISSUE TITLE
Is there any way I can get an overall output?

### ISSUE THREAD

**Issue by jiangxiaoyuyu** [IfcOpenShell/IfcOpenShell#5120]
I noticed that IfcConvert gets the geometry or brep information for each section and outputs it through the serializer->write () loop. Is there any way to combine all the parts into a whole, to get a unique meshset?

**Comment by aothms** [comment]
I would say this is something best applied in a separate process. E.g blender can join meshes (and can be ran non headlessly). If you write an OBJ file you can just write a regex to skip the `g` or `o` lines.

**Comment by Moult** [comment]
If you'd like to see how we chunk portions of a mesh together in Blender (but still reuse instances to preserve memory where the total_vertices:total_instances ratio makes sense) check out: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/blenderbim/blenderbim/bim/module/project/operator.py#L1424-L1592

**Comment by jiangxiaoyuyu** [comment]
Thank you very much. I'll go study

**Comment by jiangxiaoyuyu** [comment]
![0001](https://github.com/user-attachments/assets/cdafe383-afe8-4e83-8f34-3d67ef4a5db7)
My job involves converting ifc files like the one in the picture into mesh, and then processing them with my professional knowledge.
Take the ifc file in the image as an example. During the conversion process using ifcconvert, it is divided into five entities, which are independently converted into five sets of points, lines, and surfaces.
This process will result in overlapping areas (the areas I circled in red) with overlapping points and some difficult to deal with.
The best conversion result is to integrate all the parts together and directly convert a complete manifold surface.
Do you have any good suggestions about this? Thank you very much!

**Comment by Moult** [comment]
This seems out of scope of IfcConvert. IfcConvert takes the geometry as-is defined in IFC. This seems to be a further post-processing of the geometry which unions them together. If you use C++ or Python, you can run the equivalent of IfcConvert but in code, and then also get the shapes defined using OpenCASCADE and then perform union operations on them.

**Comment by jiangxiaoyuyu** [comment]
Thank you very much!

**Comment by aothms** [comment]
@jiangxiaoyuyu You can have a look at https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.8.0/src/exterior-shell-extractor and https://github.com/IfcOpenShell/ifc-to-cityjson which attempt to do that. The first based on aligning halfspaces second on boolean union of dilated volumes, see https://speakerdeck.com/aothms/ifcopenshell-at-fosdem-2024?slide=10 Both highly experimental.

**Comment by jiangxiaoyuyu** [comment]
Thank you very much :)
