### ISSUE TITLE
how to build ifcopenshell on Arch Linux?

### ISSUE THREAD

**Issue by szbgwr** [IfcOpenShell/IfcOpenShell#5124]
I'm a Linux newbie. I can't install the IfcOpenShell and IfcOpenShell-git packages directly through Aur. So, I'm wondering how I can compile and install IfcOpenShell using Cmake on ArchLinux, or if there are any good Samaritans who can repackage and maintain it on Aur.On the official website of Ifcopeshell, only the compilation method for Ubuntu is provided, which is not feasible. So, what should I do to use Ifcopeshell on Arch Linux?

**Comment by Moult** [comment]
I'm on Gentoo, and after installing the dependencies through Gentoo's portage, I then use this command to configure cmake (in this scenario I had opencascade manually compiled but feel free to change to suit your situation):

```
ccmake \
    -DGLTF_SUPPORT=off \
    -DCITYJSON_SUPPORT=off \
    -DEIGEN_DIR=/usr/include/eigen3 \
    -DCGAL_HEADER_ONLY=On \
    -DCGAL_INCLUDE_DIR=/usr/include \
    -DOCC_INCLUDE_DIR=/home/dion/drive/opencascade/opencascade-7.5.0/inc \
    -DOCC_LIBRARY_DIR=/home/dion/drive/opencascade/opencascade-7.5.0/build/lin64/gcc/lib \
    -DHDF5_LIBRARIES="/usr/lib64/libhdf5_cpp.so;/usr/lib64/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libsz.so;/usr/lib64/libaec.so" \
    -DHDF5_INCLUDE_DIR="/usr/include" \
    -DGMP_INCLUDE_DIR=/usr/include \
    -DMPFR_INCLUDE_DIR=/usr/include \
    -DGMP_LIBRARY_DIR=/usr/lib64 \
    -DMPFR_LIBRARY_DIR=/usr/lib64 \
    -DPYTHON_EXECUTABLE=/usr/bin/python3.11 \
    -DPYTHON_INCLUDE_DIR=/usr/include/python3.11 \
    -DPYTHON_LIBRARY=/usr/lib64/libpython3.11.so \
    ../cmake
```

Then I run this to compile (specifically I only compile the Python wrapper in this target):

```
cmake --build . -j 12 --target _ifcopenshell_wrapper
```

BTW it's also worth mentioning that you don't need to compile anything if you just want to use IfcConvert or use the python wrappers / etc.

**Comment by szbgwr** [comment]
> I'm on Gentoo, and after installing the dependencies through Gentoo's portage, I then use this command to configure cmake (in this scenario I had opencascade manually compiled but feel free to change to suit your situation):
> 
> ```
> ccmake \
>     -DGLTF_SUPPORT=off \
>     -DCITYJSON_SUPPORT=off \
>     -DEIGEN_DIR=/usr/include/eigen3 \
>     -DCGAL_HEADER_ONLY=On \
>     -DCGAL_INCLUDE_DIR=/usr/include \
>     -DOCC_INCLUDE_DIR=/home/dion/drive/opencascade/opencascade-7.5.0/inc \
>     -DOCC_LIBRARY_DIR=/home/dion/drive/opencascade/opencascade-7.5.0/build/lin64/gcc/lib \
>     -DHDF5_LIBRARIES="/usr/lib64/libhdf5_cpp.so;/usr/lib64/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libsz.so;/usr/lib64/libaec.so" \
>     -DHDF5_INCLUDE_DIR="/usr/include" \
>     -DGMP_INCLUDE_DIR=/usr/include \
>     -DMPFR_INCLUDE_DIR=/usr/include \
>     -DGMP_LIBRARY_DIR=/usr/lib64 \
>     -DMPFR_LIBRARY_DIR=/usr/lib64 \
>     -DPYTHON_EXECUTABLE=/usr/bin/python3.11 \
>     -DPYTHON_INCLUDE_DIR=/usr/include/python3.11 \
>     -DPYTHON_LIBRARY=/usr/lib64/libpython3.11.so \
>     ../cmake
> ```
> 
> Then I run this to compile (specifically I only compile the Python wrapper in this target):
> 
> ```
> cmake --build . -j 12 --target _ifcopenshell_wrapper
> ```
> 
> BTW it's also worth mentioning that you don't need to compile anything if you just want to use IfcConvert or use the python wrappers / etc.

Thank you, but I cannot directly use your compilation parameters. I am not familiar with Linux and CMAKE. This is really frustrating

**Comment by Moult** [comment]
Yes you're not meant to have those paths verbatim, you should probably see where Arch installs those dependencies and adjust the paths accordingly. Is there a particular part you're confused about?

There's also https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/nix/build-all.py but I think that builds all deps from source (which you can skip if you get them from your package manager).

**Comment by sukanka** [comment]
Hi, you can try the PKGBUILD I wrote.( just extract the tarball `ifcopenshell.tar.gz`)
 Also, there is a prebuilt package. You can find it at https://dl.askk.cc/local_pub/aur

**Comment by szbgwr** [comment]
> Hi, you can try the PKGBUILD I wrote.( just extract the tarball `ifcopenshell.tar.gz`) Also, there is a prebuilt package. You can find it at https://dl.askk.cc/local_pub/aur

爱你哟,苏博士 :D
