### ISSUE TITLE
Geometry gets tweaked in v0.08

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5138]
The table object looks like the following in v0.07...
[table.ifc.txt](https://github.com/user-attachments/files/16483204/table.ifc.txt)

![2024-08-03_18-17-24_blender_(Unsaved)_-_Blender_4 1blender](https://github.com/user-attachments/assets/f5ed8a43-27c6-4a18-99a9-47c5113bbd8c)

and looks like the following in v0.08.0...

![2024-08-03_18-18-11_blender_(Unsaved)_-_Blender_4 2blender](https://github.com/user-attachments/assets/f85751a3-9364-42eb-a326-28e61e045cc1)

**Comment by Moult** [comment]
I think already fixed just no bot build

**Comment by theoryshaw** [comment]
I have 4.2.0 Bonsai vO.7. I I -alpha240822-cabffdc and still getting this.  Is it still a bot build thing?

**Comment by aothms** [comment]
That's beautiful! Can confirm the table looks like before in latest (unbuilt?) version. Still clearly not complete though. Does it look better in other viewers?

![afbeelding](https://github.com/user-attachments/assets/edd11b92-b18a-4f77-97b5-d6413bac04b0)

**Comment by Moult** [comment]
Similar glitchy look on ThatOpenEngine 
![2024-08-23-193248_613x419_scrot](https://github.com/user-attachments/assets/3308524c-01f9-4948-afbc-66907b66ab92)
