### ISSUE TITLE
Max to IFC export

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [IfcOpenShell/IfcOpenShell#514]
I found that IFC to max available but Max to IFC available or not ?

**Comment by aothms** [comment]
No, an IFC files has quite rigid requirements in terms of structure and geometrical representations. It would be a tremendous effort to get data out of 3ds max that conforms to these requirements. If you want to get polygonal meshes into IFC, perhaps an approach using Blender and FreeCAD would work.

**Comment by MuhammadFaizanKhan** [comment]
okay, is there any else solution ? if the ifcopenShell is not supporting this feature.

**Comment by aothms** [comment]
Not that I know of
