### ISSUE TITLE
Live development environment: Blenderbim requires Blender to restart

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5142]
- install fresh blenderbim_py311-0.7.11-alpha240803-windows-x64.zip
- ran [bat](https://github.com/IfcOpenShell/IfcOpenShell/blob/596ffb093be8687d6e73f35e37338c63f9c05dbc/src/blenderbim/scripts/installation/dev_environment.bat). 
- when bb is opened, get follow error. 
![image](https://github.com/user-attachments/assets/5ea9edec-288c-4c08-83ec-b1070b10f217)

**Comment by Andrej730** [comment]
Couldn't reproduce this.

Is it always occurs when you start bbim or just occured in that one session?

For this error to occur addon should be registered atleast 2 times - first time it remembered the version "0.0.0" and then the second time, after addon was disabled+enabled/reinstalled/updated, it remembered the second version "0.7.11-alpha24081". So it should never occur when you just open bbim.

**Comment by theoryshaw** [comment]
This doesn't seem to happen anymore. :)
