### ISSUE TITLE
Avoid websocket server connection error on macOS arm64

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#5143]
I have installed blenderbim_py311-0.7.11-alpha240727-macos-arm64 on Blender 4.2.0 macOS-14.6-arm64-arm-64bit.

When running BlenderBim "Connect/Start websocket server" a web browser window (Firefox) opens but I also get the following exception immediately

````
Python: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.2/python/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.2/python/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/kuba/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/blenderbim/tool/web.py", line 332, in sio_connect
    await sio.connect(url, transports=["websocket"], namespaces="/blender")
  File "/Users/kuba/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/socketio/async_client.py", line 161, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Connection error
````

**Comment by Moult** [comment]
Can try with a more recent build? There were similar issues on Linux which have been addressed now.

**Comment by kurb70** [comment]
I tried blenderbim_py311-0.7.11-alpha240804-macos-arm64 and the exception is gone.

Unfortunately, the data is not displayed in the web browser. However, the data can be exported as a CSV file. I have attached a screenshot. Perhaps this will help to narrow down the problem.

<img width="1265" alt="Screenshot 2024-08-05 at 18 35 33" src="https://github.com/user-attachments/assets/e90d4939-f12c-4bf4-af84-d5284a290d88">

**Comment by kurb70** [comment]
<img width="944" alt="Screenshot 2024-08-05 at 18 48 52" src="https://github.com/user-attachments/assets/6d8badb9-9a7c-49e7-837f-c9352922bc82">

**Comment by Ziad-I** [comment]
@kurb70 Did you choose the web output format before exporting data? After choosing the web format, and specifying the attributes you want you need to click Export IFC to WEB

For the CSV data and work schedule Gantt charts, you will need to explicitly export the data either through
- choosing web format and clicking Export IFC to WEB for the CSV 
- clicking generate Gantt chart for the work schedules Gantt charts

**Comment by kurb70** [comment]
No, unfortunately I have not selected this. After I have changed it, the data appears. Thank you.
