### ISSUE TITLE
Installation failure, prompting my windows system problem, how to solve it?

### ISSUE THREAD

**Issue by zhiaguai** [IfcOpenShell/IfcOpenShell#5147]
os: Windows os_version: 10.0.22621 python_version: 3.10.9 architecture: ('64bit', 'WindowsPE') machine: AMD64 processor: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD blender_version: 3.5.1 blenderbim_version: 0.0.240602 last_actions:  last_error
![image](https://github.com/user-attachments/assets/84e981c4-9e3c-4d6f-a9bc-3a0e70986b84)

**Comment by Andrej730** [comment]
Copy error message here?

**Comment by Andrej730** [comment]
@zhiaguai Feel free to reopen if issue persists.
