### ISSUE TITLE
Building IfcOpenShell on Windows: SyntaxError occurs by using build-deps.cmd

### ISSUE THREAD

**Issue by Antoine333** [IfcOpenShell/IfcOpenShell#515]
Hi,
i am trying to build IfcOpenShell on Windows 7 (64 bit) by using Visual Studio.

Previous installations:
- Visual Studio 2017 + Visual Studio Build Tools 2017
- Git (Git-2.19.2-64-bit)
- CMake (cmake-3.13.1-win64-x64)
- PowerShell (PowerShell-6.2.0-preview.2-win-x64)
- Clang (LLVM-7.0.0-win64)

After setting the Visual Studio environment variables i tried to run "build-deps.cmd".
But as you can see below, there occurs a syntax error after downloading Boost 1.67.0.

![screen1](https://user-images.githubusercontent.com/45664425/49640362-b6037980-fa0d-11e8-9f71-5f52c557b6a1.png)
![screen2](https://user-images.githubusercontent.com/45664425/49640365-b7cd3d00-fa0d-11e8-96e9-c8c8f4a62f55.png)

Would be grateful for any help.

Antoine

**Comment by Antoine333** [comment]
Found a solution:

extract the "boost_1_67_0.7z" manuell and scipp the extraction in "build-deps.cmd":
::call :ExtractArchive %BOOST_ZIP% "%DEPS_DIR%" "%DEPENDENCY_DIR%"

**Comment by aothms** [comment]
Likely cause for this is the space in your path. I thought spaces were accounted for, but perhaps we overlooked something.

Glad you resolved this for yourself for the time being.
