### ISSUE TITLE
AdvancedBRep corruption in v0.8.0

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5173]
See attached file. First picture is from 0.7.0 and the second is the latest bot build.

[chair.ifc.txt](https://github.com/user-attachments/files/16573477/chair.ifc.txt)
![2024-08-11-211804_422x560_scrot](https://github.com/user-attachments/assets/407991bf-5514-48fd-bae4-477ef47ae285)
![2024-08-11-211742_399x591_scrot](https://github.com/user-attachments/assets/5fb6457b-bf97-4ba9-8684-37a6dcebcfb0)

**Comment by Moult** [comment]
Issue persists with latest bot build.

**Comment by Moult** [comment]
Closing as now fixed in latest bot build.

**Comment by aothms** [comment]
Ohh 🎉 . I didn't look into this one yet though, not sure what caused it neither what fixed it. But always good to have some self-solving bugs to appear productive.

Thanks for keeping an eye on it @Moult !
