### ISSUE TITLE
File - Open IFC reloads currently opened model

### ISSUE THREAD

**Issue by zhukoven** [IfcOpenShell/IfcOpenShell#5175]
The latest alpha build `v0.7.11-alpha240812-0c8048c` on Blender `4.2.0` introduces the bug with **File > Open IFC Project** menu. When I have loaded an IFC model in BBIM, and then want to open another one, I press on **File > Open IFC Project** and BBIM simply reloads the currently opened IFC file without showing the dialog box.

**Comment by Andrej730** [comment]
Can confirm this issue occurs if project is loaded through "Open IFC Project" UI and not with drag'n'drop/file association.

**Comment by Andrej730** [comment]
Should be fixed now, thank you for the bug report.

**Comment by zhukoven** [comment]
@Andrej730, thank you for the quick fix!
