### ISSUE TITLE
Change STEP ID of element

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5176]
Stumbled across a bizarre bug in ArcGIS yesterday. Apparently ArcGIS Pro only reads the first X bytes/lines/something to check for IfcProjectedCRS / IfcMapConversion. This means that if your geolocation data is at the bottom of the file or midway etc in a larger file (with a big enough STEP ID, haven't bothered to find the exact threshold), ArcGIS will not read georeferencing data and your IFC will come in wrongly.

I know, I know.

A quick fix is in notepad to just cut and paste the projectedcrs/mapconversion and move it to the top of the file. Is there a way to do this with code perhaps that isn't string editing? I _could_ delete and then recreate 4 entities with explicit STEP IDs (two from the bottom, two from the top to swap them) and redo the inverses but it sounds overkill.

**Comment by aothms** [comment]
These days there is a somewhat feasible way to just print the file manually.

```python
import ifcopenshell
f = ifcopenshell.open(...)
with open('out.ifc', 'w') as f:
    for inst in sorted(f, key=lambda inst: (not inst.is_a('IfcCoordinateReferenceSystem'), inst.id())):
        print(inst.to_string(), end=';\n')
```

This misses the header and the endsec stuff though. Maybe easiest to do with a couple python fstrings for now, but I also don't mind wiring up the C++ code to do so.

**Comment by Moult** [comment]
It's OK, this is an obscure workaround for an obscure bug, so no biggie. But good to know :)
