### ISSUE TITLE
BB Georeferencing indicator should use project data after switching IFC files

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#5177]
When I switch from a georeferenced IFC file, in which the visualisation of the georeference is displayed, to another georeferenced IFC file, the displayed indicator should correspond to the current project.

At the moment, the indicator of the previous project is displayed. The indicator is only updated when the georeferencing is opened in the UI.

![000 Indicator after switching from other IFC](https://github.com/user-attachments/assets/6ae8349c-45ff-478b-987d-f659c67280bd)
![001 Indicator after entering Georeferencing](https://github.com/user-attachments/assets/7df78173-d7d5-4d2c-b153-205ad2101a39)

**Comment by Moult** [comment]
What do you mean by "Switch"?

**Comment by kurb70** [comment]
I meant opening one IFC file and then another IFC file with a different georeferencing. Here are the two files I am using. Both have different georeferencing.

[001 bim4bipv-model georeferenced.ifc.txt](https://github.com/user-attachments/files/16595999/001.bim4bipv-model.georeferenced.ifc.txt)
[002 amaze2-model georeferenced.ifc.txt](https://github.com/user-attachments/files/16596000/002.amaze2-model.georeferenced.ifc.txt)
