### ISSUE TITLE
Transition BlenderBIM -> Bonsai

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#5178]

**Comment by RickBrice** [comment]
You probably already know this, but https://[docs.bonsaibim.org](https://docs.bonsaibim.org/)/ doesn't work.

**Comment by Andrej730** [comment]
> You probably already know this, but https://[docs.bonsaibim.org](https://docs.bonsaibim.org/)/ doesn't work.

Works for me.

**Comment by RickBrice** [comment]
Weird - works from my phone, but not from my computer. Looks like it's my problem. Thanks for checking.

**Comment by Moult** [comment]
We didn't have force https redirect before, I just enabled it. Maybe relevant.
