### ISSUE TITLE
Performance of function: min_vertex_edge_distance

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#518]
Hi,

I have a model with a lot of vertexes and edges.
The function has a runtime of o^2.
That means, that the most time to do boolean operations is spent in this function.

Is there a better way to get min vertex edge distance?

kind regards

**Comment by aothms** [comment]
You're absolutely correct.

> Is there a better way to get min vertex edge distance?

Yes, there is. For example `IfcGeom::impl::tree` is used for wire_intersection [1] and vertex clustering [2] to speed up searching. Something similar can **and should** be used for the function you identified as well. Is this something you would like to work on?

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomFunctions.cpp#L3118
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomFunctions.cpp#L3601

**Comment by ninichki** [comment]
Oh, thank you. 

I was thinking about to do it, but I had a lot of work at the moment.

kind regards

**Comment by aothms** [comment]
No problem, thanks for identifying this.
