### ISSUE TITLE
[BlenderBIM] AttributeError: module 'ifcopenshell.api' has no attribute 'pset_template'

### ISSUE THREAD

**Issue by ZiruiHong** [IfcOpenShell/IfcOpenShell#5189]
# Issue Descirption
I'm trying to create pset_template entity in BlenderBIM but it gives me an error. 

```
>>>template = ifcopenshell.api.pset_template.add_pset_template(model, name="UTC")
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: module 'ifcopenshell.api' has no attribute 'pset_template'
```

And trying an auto-complete shows no 'pset_template' .

![image](https://github.com/user-attachments/assets/68b0a4e3-3bbf-4512-adc0-c2b0b11fcd57)

# My Configurations
- python: 3.11
- ifcopenshell: 0.7.11-alpha240809
- Blender: 4.2

# How I tracked the issue
Here is the work path of the imported 'ifcopenshell.api' module
```
>>> print(ifcopenshell.api.__file__)
C:\Users\zirui\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\api\__init__.py
```

I went to the 'api' folder and found the 'pset_template' was actually there.

![image](https://github.com/user-attachments/assets/34ceb44a-d31b-41d5-a6f5-eb8cb741e2db)

![image](https://github.com/user-attachments/assets/db9f4cbf-d583-41f8-b0c9-9c9d8cba080a)

I don't know why this 'pset_template' cannot be recognized by 'ifcopenshell.api' module. Can anyone help?

**Comment by Moult** [comment]
Did you do `import ifcopenshell.api.pset_template` first?

**Comment by ZiruiHong** [comment]
No. I didn't. I try ```import ifcopenshell.api.pset_template``` and it does resolve the issue... 

Can I know why it needs a seperate ```import``` operaiton?

**Comment by Andrej730** [comment]
> Can I know why it needs a seperate `import` operaiton?

Because `pset_template` is a separate module with it's own methods, the design is that importing just `ifcopenshell.api` shouldn't import all available modules (as there are many) and their dependencies if user don't need them.

**Comment by ZiruiHong** [comment]
Thanks for the answer.
