### ISSUE TITLE
blenderBIM could not load

### ISSUE THREAD

**Issue by Jorgut** [IfcOpenShell/IfcOpenShell#5190]
os: Darwin
os_version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
python_version: 3.11.7
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 4.2.0
blenderbim_version: 0.0.240602
last_actions: 
last_error: Traceback (most recent call last):
  File "/Users/aj/Library/Application Support/Blender/4.2/extensions/user_default/blenderbim/__init__.py", line 96, in <module>
    import blenderbim.bim
ModuleNotFoundError: No module named 'blenderbim'

**Comment by Moult** [comment]
See #4373.
