### ISSUE TITLE
Request for open-file method to accept byte-streams as arguments

### ISSUE THREAD

**Issue by raj-open** [IfcOpenShell/IfcOpenShell#5193]
The method `open` which returns a `file` (`ifcopenshell_wrapper.file`) object forces users to have the ifc file stored as an actual file on their system. One can only enter a _path_ to the `open` method.

This is quite burdensome in the scenarios, where, for example, many ifc-files are stored remotely. In these circumstances it would be much more convenient to simply have the `open` method work on a bytes-stream, otherwise developers are forced to download every single ifc-file locally.

**Request:** Would it be possible to implement this?

Or is there something that fundamentally rules out prevents the underlying C++ code from working with a bytes-stream?

Thanks for your interest!

## Configuration ##

- `ifcopenshell==0.8.0`
- `python==3.11`
- OS - any

## Relevant part of Code ##

Lines 119--161 in [src/ifcopenshell-python/ifcopenshell/\_\_init\_\_.py](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcopenshell-python/ifcopenshell/__init__.py#L119):

```py
def open(
    path: Union[os.PathLike, str], # <- forced to enter path, not stream
    format: Optional[str] = None,
    should_stream: bool = False
) -> file:
    """
    Loads an IFC dataset from a filepath

    You can specify a file format. If no format is given, it is guessed from
    its extension. Currently supported specified format: .ifc | .ifcZIP |
    .ifcXML.

    You can then filter by element ID, class, etc, and subscript by id or guid.

    Example:

    .. code:: python

        model = ifcopenshell.open("/path/to/model.ifc")
        model = ifcopenshell.open("/path/to/model.ifcXML")
        model = ifcopenshell.open("/path/to/model.any_extension", ".ifc")

        products = model.by_type("IfcProduct")
        print(products[0].id(), products[0].GlobalId) # 122 2XQ$n5SLP5MBLyL442paFx
        print(products[0] == model[122] == model["2XQ$n5SLP5MBLyL442paFx"]) # True
    """
    path = Path(path)
    if format is None:
        format = guess_format(path)

    if format == ".ifcXML":
        f = ifcopenshell_wrapper.parse_ifcxml(str(path.absolute()))
        if f:
            return file(f)

        raise IOError(f"Failed to parse .ifcXML file from {path}")

    if format == ".ifcZIP":
        with tempfile.TemporaryDirectory() as unzipped_path:
            with zipfile.ZipFile(path) as zf:
                for name in zf.namelist():
                    if Path(name).suffix.lower() in (".ifc", ".ifcxml"):
                        return open(zf.extract(name, unzipped_path))

                else:
                    raise LookupError(f"No .ifc or .ifcXML file found in {path}")

    if format == ".ifcSQLite":
        return sqlite(path)

    if should_stream:
        return stream(path)

    # part of the code that typically gets called in my case:
    f = ifcopenshell_wrapper.open(str(path.absolute()))
    # can ifcopenshell_wrapper.open be extended to accept bytes?

    return file(f)
```

**Comment by aothms** [comment]
There is `ifcopenshell.file.from_string()`. It's not a stream because these things are harder to pass around between python - c++, but at least it's fully in memory.

**Comment by Andrej730** [comment]
We can implement `file.from_stream` in Python but are there any benefits to this instead of using just `ifcopenshell.file.from_string(s.read())`?

```python 
import ifcopenshell
import io
from typing import Union


def from_stream(s: Union[io.TextIOBase, io.BufferedIOBase]) -> ifcopenshell.file:
    if isinstance(s, io.TextIOBase):
        ifc_str = s.read()
    else:
        ifc_str = s.read().decode("utf-8")
    return ifcopenshell.file.from_string(ifc_str)


with open(r"test.ifc", "r") as fi:
    f = from_stream(fi)
    print(f)

with open(r"test.ifc", "r") as fi:
    contents = fi.read()

f = from_stream(io.StringIO(contents))
print(f)

with open(r"test.ifc", "rb") as fi:
    f = from_stream(fi)
    print(f)

with open(r"test.ifc", "rb") as fi:
    byte_contents = fi.read()
f = from_stream(io.BytesIO(byte_contents))
print(f)
```

**Comment by aothms** [comment]
> but are there any benefits to this instead of using just ifcopenshell.file.from_string(s.read())?

No exactly, I would not expose a from_stream() API that is not actually streaming in nature.

In the future we probably will get something like that though, or we can more deeply integrate the lark-based streaming parsers.

**Comment by Andrej730** [comment]
@raj-open so, `ifcopenshell.file.from_string` covers your case and this can be closed?

**Comment by raj-open** [comment]
@Andrej730 yes, thank you! I think this is sufficient for now
