### ISSUE TITLE
Update from Get Extensions not working properly

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5198]
Hey guys, this thing right here is not working properly for me. I'm on Windows using the 18th of August version while there is a 19th of August build.

![image](https://github.com/user-attachments/assets/275fd315-a0bf-49e5-83b5-0f071a6cb3aa)

This also happened yesterday, but weirdly enough it showed up after pressing that refresh button. Today that doesn't do anything.

![image](https://github.com/user-attachments/assets/b82efbbc-3c77-4145-b814-0ed6b937a552)

This is the link I have for the repository:

`https://raw.githubusercontent.com/IfcOpenShell/bonsai_unstable_repo/main/index.json`

Am I doing something wrong, @Andrej730 ?

**Comment by Andrej730** [comment]
On https://github.com/IfcOpenShell/bonsai_unstable_repo it still had only build for 18 aug. 

![image](https://github.com/user-attachments/assets/bffa3c5b-ca20-4206-be1a-317508e8f09a)

Yestarday github workflow that updates builds on this repo failed for some reason (looks like some network delay or something).

Restarted it, repo is now updated.

**Comment by BIMvoice** [comment]
Oh - it's great to hear then that it was only this. Thank you for updating it!
