### ISSUE TITLE
Build script fails under OS X El Cap

### ISSUE THREAD

**Issue by shsteven** [IfcOpenShell/IfcOpenShell#52]
Building under OS X El Cap (10.11) fails with the follow error:

```
Undefined symbols for architecture x86_64:
  "_lzma_auto_decoder", referenced from:
      _xz_head in libxml2.a(xzlib.o)
  "_lzma_code", referenced from:
      _xz_decomp in libxml2.a(xzlib.o)
  "_lzma_end", referenced from:
      ___libxml2_xzclose in libxml2.a(xzlib.o)
  "_lzma_properties_decode", referenced from:
      _is_format_lzma in libxml2.a(xzlib.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

I've made a PR to fix this issue:
#51

**Comment by shsteven** [comment]
#51

**Comment by shsteven** [comment]
The above error is fixed.

However build still fails with the following error:

```
[ 64%] Building CXX object CMakeFiles/IfcGeom.dir/Users/SZ/Downloads/IfcOpenShell/src/ifcgeom/IfcRegister.cpp.o
Undefined symbols for architecture x86_64:
  "boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)", referenced from:
      boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::assign(char const*, char const*, unsigned int) in libIfcParse.a(IfcUtil.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [examples/IfcParseExamples] Error 1
make[1]: *** [examples/CMakeFiles/IfcParseExamples.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
1 warning generated.
[ 67%] Linking CXX static library libIfcGeom.a
[ 67%] Built target IfcGeom
make: *** [all] Error 2
 
```

Has anyone encountered the same issue?

**Comment by aothms** [comment]
With the recent merge (https://github.com/IfcOpenShell/IfcOpenShell/commit/5c1ac39f193251436e9443aba70edef33c386141) the required boost components changed. I forgot to updated this. Thanks for reporting and thanks for the pull request! Please check with the latest commit https://github.com/IfcOpenShell/IfcOpenShell/commit/5b30dfc5807d0e04e7c55b807b48e90c4be0364d

**Comment by aothms** [comment]
Probably before running the script you have to clear the boost install with an `rm -rf ~/Downloads/IfcOpenShell/build/Darwin/x86_64/install/boost-1.55.0` (or similar).

**Comment by Stinkfist0** [comment]
Ah yes, the new required Boost components are missing. AFAIK I have added and committed them a while back but they seem gone (removed in some merge accidentally?: `regex` (and `date_time`, a dependency for regex IIRC) and potentially `system` should be added.

**Comment by shsteven** [comment]
@aothms @Stinkfist0 Thanks for the quick reply!
The commit fixes that issue, and now it fails with some different boost errors:

<img width="1483" alt="screen shot 2016-03-24 at 9 15 07 am" src="https://cloud.githubusercontent.com/assets/96500/14005733/102a36d8-f1a1-11e5-9ce7-f61a017cd9ce.png">

**Comment by shsteven** [comment]
Here's a new PR: #53 

Fixes the issue mentioned above.

**Comment by shsteven** [comment]
@aothms works very well now. Thanks!

**Comment by aothms** [comment]
Thank you for the fixes and testing.

**Comment by shsteven** [comment]
@aothms no worries

**Comment by aothms** [comment]
@shsteven Minor thing though. It seems github does not recognize your commits when merged here (see https://github.com/IfcOpenShell/IfcOpenShell/commit/7d145a5f69fd36325002cd4a3f92f09c949e934f). Can you associate your email address with your github account? Thanks.

**Comment by shsteven** [comment]
@aothms sure.
