### ISSUE TITLE
Branch 0.6 parse_ifcxml.cpp includes even with IFCXML_SUPPORT FALSE

### ISSUE THREAD

**Issue by stephassoria** [IfcOpenShell/IfcOpenShell#520]
When running cmake on branch 0.6 (visual c++ win64 build) with those settings : 

set(UNICODE_SUPPORT FALSE)
set(COLLADA_SUPPORT FALSE)
set(BUILD_IFCPYTHON FALSE)
set(BUILD_EXAMPLES FALSE)
set(IFCXML_SUPPORT FALSE)
set(BUILD_GEOMSERVER FALSE)
set(BUILD_CONVERT FALSE)
set(USE_VLD FALSE)
set(USE_MMAP FALSE)
set(BUILD_IFCMAX FALSE)
set(BUILD_SHARED_LIBS FALSE)
set(ENABLE_BUILD_OPTIMIZATIONS TRUE)

I need to remove parse_ifcxml.cpp from generated vcxproj because it generates a compile error : 
Cannot open include file: 'libxml/parser.h': No such file or directory

  regards,
 Stephane

**Comment by aothms** [comment]
Hi,

You are very correct. The way this is handled in IfcOpenShell is to use guards similar to [1], a preprocessor statement is already generated by cmake [2], so it's just a matter of adding an `#ifdef` to the .cpp file.

Would be wonderful if you can provide a PR for this.

For reference, the build options Travis uses to find libxml are [3]

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/serializers/ColladaSerializer.cpp#L20
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/cmake/CMakeLists.txt#L150
[3] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/.travis.yml#L35

Kind regards,
Thomas

**Comment by stephassoria** [comment]
PR done.

Stéphane

**Comment by aothms** [comment]
Many thanks
