### ISSUE TITLE
crash opening file exported from Vectorworks

### ISSUE THREAD

**Issue by don-matteo** [IfcOpenShell/IfcOpenShell#5213]
Hi,

BonsaiBIM 240821: Blender 4.2 crashes after opening the file "69_TIDE_GESAMTMODELL_20240815_v2024.ifc" I sent both Dion and Andrej via E-Mail.

I've got an "older machine" (MB Pro 2019 16" with 16GB Ram) However, it shouldn't crash IMO.

thank you, Matteo

**Comment by Moult** [comment]
This IFC has all sorts of weird stuff inside of it. I see in the header it was created by Vectorworks, but was it edited in any way? It's good invalid behaviour galore. Incorrect IFC4X3 schema, it has sporadic lowercase STEP names and enums (e.g. `#2= ifcactorrole(.architect.,$,$);` instead of `#2= IFCACTORROLE(.ARCHITECT.,$,$);`), duplicate GlobalIDs, duplicate STEP IDs ... I wouldn't trust this IFC at all. I don't understand how it can break this badly.

The thing causing the crash is you've got stuff in it like this:

```
#5763= IFCLENGTHMEASURE(0.);
#5764= IFCLENGTHMEASURE(0.);
#5765= IFCLENGTHMEASURE(0.);
#5766= IFCAREAMEASURE(0.);
```

**Comment by Moult** [comment]
That said, we can edit it to fix it, and I think @aothms always likes to have no crashes, so let's keep this open until @aothms decides how to address this.

I've emailed you the fixed (well, only some issues fixed, others remain) file.

![2024-08-22-083932_428x300_scrot](https://github.com/user-attachments/assets/e2477dc1-59c9-4d32-b6aa-7f8c25613f0b)

**Comment by RickBrice** [comment]
The buildingSmart validation service is a great way to get a first level check on an IFC file.

**Comment by Moult** [comment]
@RickBrice this will probably crash the validation service which runs on IfcOpenShell :)

**Comment by RickBrice** [comment]
LOL - be you are right but that could generate some $$$ for @aothms to get it fixed.  :)

**Comment by don-matteo** [comment]
@Moult might be possible, that the ifc-file has been edited by the Vectorworks Datamanager, (an inside Vectorwork-Datamapping-tool) I migrated our settings lately from ifc 2x3 to ifc 4x3.
So, that could be a Vectorworks issue maybee?!

**Comment by Moult** [comment]
No idea, sorry :)

**Comment by aothms** [comment]
I created a file

```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2024-08-23T11:21:18',(),(),'IfcOpenShell 0.8.0','IfcOpenShell 0.8.0','');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#2= ifcactorrole(.architect.,$,$);
#5763= IFCLENGTHMEASURE(0.);
ENDSEC;
END-ISO-10303-21;
```

And checked with my latest parser rework #5118. No crashes anymore.

- The lower case entity name is accepted, no error raised. We can probably address that.
- The lower case enum literal is not accepted. Error in log. Attribute set to $. Can easily be changed to case normalize.
- The non-entity instance is not retained. Error in log.

```
[Error] [2024-08-23 11:24:00] Unable to find keyword in schema: architect
[Error] [2024-08-23 11:24:00] Non entity type IfcLengthMeasure at offset 260
```

I'll close this for now.

**Comment by don-matteo** [comment]
Sorry, now it's a year later, but, I still am asking myself, what to do...
I still got ifc-models crashing bonsai and I'm not sure what to do.

Which basical terms should I take into account, when I get in trouble again with an ifc file crashing blender?
What are the most basic things an ifc-file should have? And, which questions could I ask a LLM in order to understad better, what I need to know?

1) consistency of upper and lower case code (imho all the code sensitive part should be upper case? need to check, wether lower-case code gets generated by the ifc-export)
2) avoid redundant GUIDS and STEP IDs
3) IFCLENGTHMEASURE,  IFCAREAMEASURE????
4) fortunately the ifc-validation service is getting more and more important, mainly for authoring-software developers...
.... still working on that post...

**Comment by aothms** [comment]
>  I still got ifc-models crashing bonsai and I'm not sure what to do.

Would be good to know if they crash IfcConvert as well. If so, it helps to send them my way at models@ifcopenshell.org (the process of receiving private models is not very streamlined yet on our end).

**Comment by don-matteo** [comment]
None of my ifc files did crash IfcConvert. Even the 1.07GB file didn't do.
I will have a short chat in my studio. When I get clearance I will send you some of my "Blender-crashing" files. Thanks for the mail-address.
