### ISSUE TITLE
ModuleNotFoundError: No module named 'bl_ext.blender_org.bonsai'

### ISSUE THREAD

**Issue by SavuGust27** [IfcOpenShell/IfcOpenShell#5214]
started a new project from the drop down menu and tried saving on the unstable release, and it shows this error.
I can see that it says "No module named 'bl_ext.blender_org.bonsai'" but in not sure how to fix it
```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
blender_version: 4.2.0
bonsai_version: 0.7.11-alpha240821
bonsai_commit_hash: 473d0ae
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 66, "Name": "Cube"}}
# ifcopenshell.api: spatial.assign_container
>>> {"products": [{"cast_type": "entity_instance", "value": 66, "Name": "Cube"}], "relating_structure": {"cast_type": "entity_instance", "value": 42, "Name": "My Storey"}}
# ifcopenshell.api: aggregate.unassign_object
>>> {"products": [{"cast_type": "entity_instance", "value": 66, "Name": "Cube"}]}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 66, "Name": "Cube"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 66, "Name": "Cube"}}
# operator: BIM_OT_save_project
# operator: BIM_OT_save_project
# operator: BIM_OT_save_project
# operator: BIM_OT_save_project
last_error: Traceback (most recent call last):
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 1317, in _execute
    ifc_exporter.export()
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\export_ifc.py", line 48, in export
    self.set_header()
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\export_ifc.py", line 88, in set_header
    self.get_application_name(), tool.Blender.get_bonsai_version()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 947, in get_bonsai_version
    bbim = cls.get_bbim_extension_package()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rodas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\blender.py", line 1125, in get_bbim_extension_package
    return importlib.import_module(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bl_ext.blender_org.bonsai'

ifc: Unsaved
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.11-alpha240821
originating_system: IfcOpenShell 0.7.11-alpha240821
```

**Comment by Andrej730** [comment]
@SavuGust27 
Hi! 
1) Can you consistently reproduce this?
2) Can you please open Blender, open "Scripting" tab and in the Python Console paste this code, run it: `from pprint import pprint; pprint(bpy.context.preferences.addons.keys())` and send here the output?
3) Can you also please send a screenshot of Bonsai from Preferences - Addons? Need to type in "bonsai" in the search and send the screenshot of bonsai's that appear there. For example:
![image](https://github.com/user-attachments/assets/819b2937-4f98-4911-83d8-b84228d291ac)
4) Were there any other errors that might be related to this (maybe something during the bonsai installation)? Can you try to disable / enable extension and try again?

**Comment by SavuGust27** [comment]
not sure what hapend. i think somthing happen when i tried the new install fro the repository as desribed here 
https://github.com/IfcOpenShell/bonsai_unstable_repo
so i installed the most recent build the old fashion way, downloading and the adding the addon from the addon panel and installing from disk. it now does not throw that error and i can save.
The only thing is that in the  camera view, after i add a plan view, I can not see the annotations decorators, is thats something thats being work on or is it a bug?

**Comment by SavuGust27** [comment]
i think it a bug, will do a report

**Comment by Andrej730** [comment]
Interesting case! Looking at the console output it seems you have 2 instances of Bonsai installed - one from blender extensions and one from unstable repo. I guess the one from blender extensions was removed manually and it probably appears in "Missing Add-ons":

![image](https://github.com/user-attachments/assets/543b75da-27ff-42a4-a109-9e04dda139f1)

I was able to reproduce this by installing 2 instances of bbim, then enabling one, removing it's folder from `extensions\user_default` and enabling second instance:

![image](https://github.com/user-attachments/assets/3b5634ba-9ada-4671-972b-e71a3a524f68)

![image](https://github.com/user-attachments/assets/6ada07d6-4d11-435a-a797-85f5aa1b5c8c)

So, I'll look for a fix tomorrow. Thank you very much for reporting this issue.

> The only thing is that in the camera view, after i add a plan view, I can not see the annotations decorators, is thats something thats being work on or is it a bug?

Please report it as a separate issue.
