### ISSUE TITLE
Outliner not showing layers in Bonsai extension

### ISSUE THREAD

**Issue by Slackking1** [IfcOpenShell/IfcOpenShell#5215]
In the recent bonsai extension, eg. downloaded and installed through blender 4.2, the outliner "flattens" everything. 
Im still learning bonsai/blenderbim, but im quite sure this is a bug.

This is in 4.1 and the old blenderbim release
![image](https://github.com/user-attachments/assets/7fc26d30-6cb9-442b-8080-c2557b4b1f36)

This is in 4.2 and with bonsai
![image](https://github.com/user-attachments/assets/dd8e9b6b-1382-44e5-8dfb-87c6731c83bd)

**Comment by Moult** [comment]
This is not a bug. The outliner has been flattened to optimise syncing functions during save, drawing generation, and also allow people to make use of Blender collections to create arbitrary session groups, and also use multiple collections per group.

To see the hierarchy, there is a new Spatial Decomposition panel with smart selection and visibility settings.
