### ISSUE TITLE
Drawing decorator not showing up in camera view

### ISSUE THREAD

**Issue by SavuGust27** [IfcOpenShell/IfcOpenShell#5216]
How to reproduce
1. Create a new file
2. Create a drawing from the drawing panel
3. Add a annotation, any type
4. Annotation decorator dont show
5. Annotation are added to ifcBuildingStory collection instead of being added at the ifcAnnotation collection 
![Screenshot 2024-08-22 134227](https://github.com/user-attachments/assets/b2b7bbb2-2152-44b7-ad1d-d00b655986dc)

If I move the annotation objects to their annotation collection, the decorators show

![Screenshot 2024-08-22 134647](https://github.com/user-attachments/assets/481eac2b-924a-45eb-92d6-85c09af72e63)

**Comment by Plae-Blue-Dot** [comment]
Can confirm having the same issue on 
![image](https://github.com/user-attachments/assets/17425882-6e25-4650-a8a9-566c6693950f)

**Comment by Andrej730** [comment]
Thank you for bug report, issue is fixed.
