### ISSUE TITLE
IfcConvert works only with single thread (doesn't works with -j) and has a HUGE memory allocation in a project

### ISSUE THREAD

**Issue by csritter** [IfcOpenShell/IfcOpenShell#5222]
Hi, maybe this can be related to the issue #5077.
I have a project (has 400~450MB) and this is causing a "Killed" on process.
I made some tests (converting to GLB):

Running IfcConvert with -j 17:
With 60GB RAM: 
![image](https://github.com/user-attachments/assets/9c17fa6f-f4df-425b-885c-143b5af658c1)
The terminal freezes and stops working.

With 128GB RAM:
![image](https://github.com/user-attachments/assets/8952c2ab-e36f-422b-b464-d231f705a9ba)
There were times when it reached 120 GB, and after a while, it was forever at 0% CPU usage and 60GB.

Running only IfcConvert:
With 30GB RAM:
![image](https://github.com/user-attachments/assets/beb9d704-36ae-4ab2-9601-0b8ac2ec6d58)
The terminal freezes and stops working too.

With 64GB RAM:
![image](https://github.com/user-attachments/assets/9652c0f9-8aa2-4c0d-b5c8-e3ad37245b8f)
Finish with success and convert.

IfcConvert version 0.8.0, commit 45be17c25ae405b4df121ee05e5f2b1b2499f757
@aothms, I will send an email with the project.
I hope you don't mind.

**Comment by Moult** [comment]
I found this recently, not sure if relevant https://github.com/IfcOpenShell/IfcOpenShell/issues/4915#issuecomment-2306857869

**Comment by csritter** [comment]
Interesting...
and from what I saw we had improvements on the last build.
I will pull and test.

**Comment by Moult** [comment]
@csritter did you get a chance to test with CGAL hybrid?

**Comment by csritter** [comment]
Hi, now I little busy. But maybe tomorrow or beginning of next week I can test.

**Comment by csritter** [comment]
Hi @Moult, running IfcConvert -j 17 with 32 GB still crashes this IFC file, I want to try later or another day with more ram or cpu

**Comment by Moult** [comment]
Can you try with a lower -j number?
