### ISSUE TITLE
Preview spreadsheet output in Blender before export?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5225]
Is there any chance something like this can be implemented at any point? I feel I'm wasting too much time with exporting multiple times to see the output of my export filters. That's the reason I cannot use ONLY bonsai for this. Solibri has a big edge here: preview + easy adjustments, even drag and drop. Same with Trimble Connect -> Data table.

**Comment by theoryshaw** [comment]
Have you tried to play around with this yet..
https://community.osarch.org/discussion/comment/21344/#Comment_21344

**Comment by BIMvoice** [comment]
> Have you tried to play around with this yet.. https://community.osarch.org/discussion/comment/21344/#Comment_21344

No, not yet. Thank you for pointing this to me - I'll give it a go.

**Comment by Moult** [comment]
Closing as now possible in web UI.
