### ISSUE TITLE
Bonsai-240826 - Weird bug where scene properties panel disappears

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#5226]
As described:
![image](https://github.com/user-attachments/assets/a4003bd9-78ed-409b-8517-2d3d561514cf)

Versions:
![image](https://github.com/user-attachments/assets/0fa45763-24f9-4dda-8b66-5911ca6a6c06)

On first installation it displays the properties panel but once closing and reopening Blender it disappears and does not come back unless Bonsai is uninstalled

**Comment by Andrej730** [comment]
@Plae-Blue-Dot can you please check system console for errors? Window - Toggle System Console.

**Comment by Plae-Blue-Dot** [comment]
Let me have a look

**Comment by Plae-Blue-Dot** [comment]
I just restarted my PC and now testing, it seems to be working perfectly, I can't replicate it again ahhaha.
Apologies, it was maybe a windows update that needed to happen at restart that was conflicting with Blender.

I'll close this issue thanks for the reply @Andrej730
