### ISSUE TITLE
No model offset in v0.8.0 (affects window/ door plan symbols)

### ISSUE THREAD

**Issue by manuvarkey** [IfcOpenShell/IfcOpenShell#5231]
When a drawing with window/ door plan symbols is created, following error message is being displayed.

```
Python: Traceback (most recent call last):
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 267, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/drawing/operator.py", line 564, in generate_linework
    self.serialiser.finalize()
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 3574, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred

```

To reproduce error, try rendering drawing `MY_STOREY_PLAN` under Plans in the following IFC file.

[svg_error_test.zip](https://github.com/user-attachments/files/16760851/svg_error_test.zip)

**Comment by manuvarkey** [comment]
Error is also caused for certain furniture and landscape objects with 2D plan representation.

**Comment by theoryshaw** [comment]
i 'think' this is fixed with https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/bonsai-0.7.11-alpha240829

@manuvarkey ?

**Comment by manuvarkey** [comment]
@theoryshaw For fresh models I could not reproduce the error. 

However for existing IFC files, although error is now not raised while generating drawings certain 2D representations which show up fine in blender is missing in rendered SVG file. Please see screenshot below.

![Screenshot from 2024-08-29 10-33-09](https://github.com/user-attachments/assets/3f1ba301-bb93-4f86-8f41-e0d5398b7456)

The strange thing is some instance of the same element (D1 door) is drawn while other instances are discarded!

Model file:
https://github.com/user-attachments/files/16762216/Karayatta.House.zip

**Comment by Moult** [comment]
It looks as though the `offset` iterator setting option was dropped in v0.8.0. This is how we solve z-fighting. @aothms ideas?

**Comment by Moult** [comment]
Ah yes, it was dropped and I'm not sure what the easy workaround for this might be: https://github.com/IfcOpenShell/IfcOpenShell/issues/4832#issuecomment-2172270979

**Comment by manuvarkey** [comment]
@Moult Seems to be working now after https://github.com/IfcOpenShell/IfcOpenShell/commit/711c59706593a3ea9391a67d43fe329e376a4a18

**Comment by Moult** [comment]
Let's keep this open as this is something better done in the iterator.

**Comment by aothms** [comment]
Yeah.. I've been a bit lazy. But should be back operational again. I didn't do the IfcConvert option --center-model yet, because that needs some more rework.

```
import ifcopenshell, ifcopenshell.geom, numpy
f = ifcopenshell.open('AC20-FZK-Haus.ifc')
s1 = ifcopenshell.geom.settings()
s2 = ifcopenshell.geom.settings(MODEL_OFFSET=(1.,0.,0.))
w = f.by_type('ifcwall')[0]
m1 = numpy.array(ifcopenshell.geom.create_shape(s1, w).transformation.matrix).reshape((4,4))
m2 = numpy.array(ifcopenshell.geom.create_shape(s2, w).transformation.matrix).reshape((4,4))
assert (m1[3][0:3] + (1.,0.,0.)).tolist() == m2[3][0:3].tolist()
```
