### ISSUE TITLE
Model view not properly restored after activating drawing view.

### ISSUE THREAD

**Issue by manuvarkey** [IfcOpenShell/IfcOpenShell#5232]
After activating drawing view to display a drawing, clicking on activate model to exit view do not fully restore the model view. Please see following images.

![Screenshot from 2024-08-27 17-25-10](https://github.com/user-attachments/assets/aae0e2e5-5b69-441c-ae9d-f04e7980afa4)
![Screenshot from 2024-08-27 17-25-24](https://github.com/user-attachments/assets/b567e490-af9f-4185-8863-49425da0995c)

**Comment by manuvarkey** [comment]
Sample IFC file used in the screenshots.

[Karayatta House.zip](https://github.com/user-attachments/files/16762216/Karayatta.House.zip)

**Comment by manuvarkey** [comment]
@Andrej730 Model view is now restored properly. However the drawing annotations are still visible after enabling model view. Is this the correct behavior ?

**Comment by Andrej730** [comment]
> However the drawing annotations remain visible after enabling model view. Is this the correct behavior ?

I think atleast it is the way it worked before it broke. But I agree, there seems to be no way to return from drawing mode and bim.activate_model should be covering this. Pushed a commit with this change.
