### ISSUE TITLE
How do you judge the same object

### ISSUE THREAD

**Issue by liaoweiqi1997** [IfcOpenShell/IfcOpenShell#524]
I found that there are many same objects in a building, they are just in different positions.Is there any way to tell this kind of object?I want to do some merging.

**Comment by aothms** [comment]
If you're lucky they share the same IfcShapeRepresentation (usually through the usage of IfcMappedItem). They may also share the some of their propery sets. If done properly, they will also have the same IfcTypeObject.

If you're not so lucky, there are no semantic relations between visually similar objects. Depends on the file.

What IfcOpenShell functionality are you using? If you're converting to Collada .DAE files under some conditions the Collada nodes will share the same Collada mesh.

**Comment by liaoweiqi1997** [comment]
@aothms 
     I used IfcConvert to convert ifc into dae, and found that for some ifc materials, it was possible to merge Shared materials, but for others, it was not possible.
    Can you tell me where to put the code that handles this?I'd like to try to analyze it. 
Thank you very much

**Comment by aothms** [comment]
> matrix calculation

What do you mean precisely? The matrix calculation that puts the geometrical instances in their eventual space in world coordinates is done by the importing tool. The matrix is an attribute of the Collada node.

Other than that you're basically looking at the entire code base, but a central function would be [1]

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomFunctions.cpp#L1414
