### ISSUE TITLE
types_with_super no longer available?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5243]
Ping @aothms the unify variant PR seems to have commented this out:

https://github.com/IfcOpenShell/IfcOpenShell/blame/8a57a5294934f192d29cb961077e105ddc5bcb08/src/ifcwrap/IfcParseWrapper.i#L189-L197

Is there a reason for it? It's used in two spots - once in opencde and another in building a hierarchy for appending library elements from another IFC.

For today's release I'll do a workaround :)

**Comment by aothms** [comment]
Sorry about that. I've cut down on the amount of maps to use in the parser. In this particular case, the supertype map accounts for roughly the same amount of megabytes in RAM as the file occupies on disk. Assuming on average 4 supertypes (so 5 entries) per instance and 64bit points (so 8 bytes per ref).

```
>>> import os, ifcopenshell
>>> fn = 'duplex_a.ifc'
>>> f = ifcopenshell.open(fn)
>>> os.path.getsize(fn)
1656151
>>> len(list(f)) * 5 * 8
1101160
```

If you want we can bring it back where we exand the types **without supertype** map on the fly based on the schema info we have.

**Comment by aothms** [comment]
Also a reminder perhaps that we should really create a proper documented version in python of the schema utils...
