### ISSUE TITLE
Enable display of type geometry again

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#5256]
I am trying to display the geometric representation of a self-created type (IfcSolarDeviceType). Unfortunately, the type object cannot be made visible. Some time ago, this was still possible with BlenderBIM without any problems.

It should be possible again to make the geometry of the type visible.

BTW I have noticed that, contrary to the description at https://docs.bonsaibim.org/users/quickstart/explore_model.html#checking-construction-types, there is no ‘Types’ node in my project, but there is an IfcTypProduct node.

Please find attached the Ifc file with which I took the screenshot.

[bim4bipv-model.ifc.txt](https://github.com/user-attachments/files/16802805/bim4bipv-model.ifc.txt)

![Screenshot 2024-08-29 at 19 05 19](https://github.com/user-attachments/assets/e5607645-7fd5-4c84-8058-54cc4c0098de)

**Comment by theoryshaw** [comment]
It's a little cumbersome, but this is how you do it now...

https://github.com/user-attachments/assets/c916f8d1-be58-46a4-96eb-c85695492b7c

I did like it how it automatically turned on the type before, and then automatically turned it off, if you 'opened' another type. 

Sounds like @Moult might introduce the same functionality in the future...
https://github.com/IfcOpenShell/IfcOpenShell/commit/73f546aab1b803b414632f1d89d740cad8b499c5#commitcomment-143694316

**Comment by Gorgious56** [comment]
Blender devs chose to hide the viewport disable state (monitor icon) by default in new files, only showing the temporary hidden state (eye icon). Think Freeze / Thaw versus Enable / Disable (snowflake vs lightbulb) in Autocad layer system. This severely limits the possibility of dynamic and more complex hiding features.

Fortunately these can be modified via python. https://blender.stackexchange.com/questions/246147/how-can-i-change-the-outliner-restriction-toggles-with-python

I suggest Bonsai enforces enabling the monitor icon when the BIM workspace is created at startup.

And maybe remove the camera icon, which is not used by the addon (AFAIK) and doesn't bring much value to newcomers.

**Comment by Moult** [comment]
I don't like the idea of using the collection hide_viewport (monitor icon). It's quite a hidden feature of Blender, and even if we show it by default, other workspaces won't. Most of our visibility controls within the add-on are pretty sophisticated now and use Python scripts (e.g. within the new spatial decomposition panel). I'm changing the code to use layer collection hide_viewport (the eye icon). Especially now we have a flat hierarchy, it becomes much cheaper.

Beginners can click the eye and it does what it expects, and Alt-H ignores collection visibility (hence all types are invisible). Advanced users who want to use collection hide_viewport can still do so.

The add-on does use the hide_render camera icon when doing underlays.
