### ISSUE TITLE
IfcElementAssembly does not create a collection

### ISSUE THREAD

**Issue by Jumalvelho** [IfcOpenShell/IfcOpenShell#5262]
Creating a IFCElementAssembly does not create a collection and place aggregate assebly parts in that collection, am I missing something or was this feature removed? Now they all are listed below each other inside spatial collection in outliner.

Running blender 4.2.1 LTS and BonsaiBim 0.7.11-alpha240814

**Comment by theoryshaw** [comment]
short answer: https://github.com/IfcOpenShell/IfcOpenShell/issues/5215#issuecomment-2304242250

longer answer: https://github.com/IfcOpenShell/IfcOpenShell/issues/4763
