### ISSUE TITLE
voids with multiple profiles, not working in 0.8.0

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5267]
file: [void with multiple profiles.ifc.txt](https://github.com/user-attachments/files/16825376/void.with.multiple.profiles.ifc.txt)
How it the file looks w/ 0.7.0...

![2024-08-31_11-20-14_blender(Unsaved)_-_Blender_4 1blender](https://github.com/user-attachments/assets/be64528f-5859-4c77-a7e4-d39c9230cffd)

How the file looks w/ 0.8.0...
![2024-08-31_11-20-23_blender_(Unsaved)_-_Blender_4 2 1_LTSblender](https://github.com/user-attachments/assets/8a65fea8-8034-40de-861e-9c8b18441f3a)

bonsai-0.7.11-alpha240831 (unstable)

**Comment by VDobranov** [comment]
I have the same issue with booleans.

BlenderBIM 0.0.230602:
![image](https://github.com/user-attachments/assets/8001ae06-4177-484c-a0fa-2c851d320789)
Bonsai 0.8.0:
![image](https://github.com/user-attachments/assets/04a3e928-121e-4c2e-9dc8-20f5a54ca839)

The booleans are cuts to the half of the plate thickness.

Things to note:
- Not all booleans are problematic - the blue ones are just fine;
- The booleans are still there, they could still be visualised:
![image](https://github.com/user-attachments/assets/9ee6284a-81ce-46ac-9cd7-4f1d12d7e3b9)

The file itself: 
[SKYLARK250_CORNER-L_cnc.ifc.txt](https://github.com/user-attachments/files/16838824/SKYLARK250_CORNER-L_cnc.ifc.txt)

**Comment by aothms** [comment]
@theoryshaw not sure why this works in v0.7 and it might definitely be that we still encounter issues with composite openings, but this is not one.

```
#1313=IFCARBITRARYPROFILEDEFWITHVOIDS(.AREA.,$,#1315,(#1316));
#1314=IFCCARTESIANPOINTLIST2D(((-0.820209973753281,0.820209973753281),(-0.820209973753281,-0.820209973753281),(0.820209973753281,-0.820209973753281),(0.820209973753281,0.820209973753281),(2.17419244798775,4.20319869762331),(2.17419244798775,2.56277875011674),(3.81461239549432,2.56277875011674),(3.81461239549432,4.20319869762331)));
#1315=IFCINDEXEDPOLYCURVE(#1314,(IFCLINEINDEX((6,5)),IFCLINEINDEX((5,8)),IFCLINEINDEX((8,7)),IFCLINEINDEX((7,6))),.F.);
#1316=IFCINDEXEDPOLYCURVE(#1314,(IFCLINEINDEX((2,3)),IFCLINEINDEX((3,4)),IFCLINEINDEX((4,1)),IFCLINEINDEX((1,2))),.F.);
```

```
![afbeelding](https://github.com/user-attachments/assets/ace0361a-1d98-49fe-a0e2-79bb0e645876)
```

This is not an profile def with voids, these boundaries are two independent loops.

**Comment by Ave-5D** [comment]
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.1-alpha240905
bonsai_commit_hash: 56428eb
last_actions: 
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 20554, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 1818.220615386963], [0.0, 1.0, 0.0, 295.85152864456177], [0.0, 0.0, 1.0, 2293.210983276367], [0.0, 0.0, 0.0, 1.0]]}, "is_si": "False"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 20554, "Name": "Opening"}}
# ifcopenshell.api: void.add_filling
>>> {"opening": {"cast_type": "entity_instance", "value": 20554, "Name": "Opening"}, "element": {"cast_type": "entity_instance", "value": 20274, "Name": "2090x1500 sliding"}}
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
# operator: BIM_OT_edit_openings
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 20554, "Name": "Opening"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.31822073459625244], [0.0, 1.0, 0.0, 0.29585152864456177], [0.0, 0.0, 1.0, 2.293210983276367], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 20554, "Name": "Opening"}}
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
# operator: BIM_OT_edit_openings
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
# operator: BIM_OT_hotkey
# operator: BIM_OT_show_openings
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\opening.py", line 790, in _execute
    element = tool.Ifc.get_entity(obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\ifc.py", line 103, in get_entity
    props = obj.BIMObjectProperties
            ^^^^^^^^^^^^^^^^^^^^^^^
ReferenceError: StructRNA of type Object has been removed

ifc: 1bd240828.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240905
originating_system: Bonsai 0.8.1-alpha240905-56428eb
```
I am not sure if this is part of the same discussion, but it is related to void.
I got the following error code when I tried to create a void in a IfcCoverType (Horizontal layer) for a window, the void “jumped” by 180.
I then tried to create an void in the IfcCovering geometry with “Tab” but no editing option appeared. 
Please find attached the project for your information.
Once again thanks for your efforts
[1bd240828.txt](https://github.com/user-attachments/files/16904372/1bd240828.txt)

**Comment by Moult** [comment]
Previously, when toggling "tab" to edit a profile, it would always assume you were editing a single profile. I.e. a single outer curve, with optional inner curves that represent holes in the profile.

Now, you can create multiple curves. Curves within curves will automatically determine whether they are outer or inner curves depending on the even-odd rule.

**Comment by aothms** [comment]
Great work as always!

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op ma 9 sep 2024 06:46 schreef Dion Moult ***@***.***>:

**Comment by Ave-5D** [comment]
Thanks Dion, it works but for me it does not save, when I save as Ifc and open again the voids are lost except the last applied void.

**Comment by Moult** [comment]
@Ave-5D can we do a screenshare or can you provide a screen recording or sample file and exact steps to recreate?

**Comment by Ave-5D** [comment]
Hi Dion yes we can, will you send the invite, I am no so clued up with all the screen recordings and screenshare functions.

**Comment by Moult** [comment]
Cheers, can you send me an invite for sometime in Sydney timezone?
