### ISSUE TITLE
Applying void using other object rotates object, removes shading styles and creates wrong size void as a result

### ISSUE THREAD

**Issue by Jumalvelho** [IfcOpenShell/IfcOpenShell#5269]
When applying a void using another object to wall object, or a custom IfcBuildingElementPart object, it rotates the object, removes styles from it and creates an opening not resembling the original shape intended. 

When applying a void to IfcElementAssebly with aggregates that include IfcWall made with wall tool and custom objects made in blender and assigned Ifc-classes, same thing happens and one object usually disappears.

Running blender 4.2.1 LTS and BonsaiBim 0.7.11-alpha240814

**Comment by theoryshaw** [comment]
can you upload an .mp4 screencast of the problem?

**Comment by Jumalvelho** [comment]
I was unable to reproduce the rotating, probably restart fixed that but objects still lose styles and geometry does go wonky.
This is when applying void to IfcElementAssembly:

https://github.com/user-attachments/assets/fe9e6521-6515-44cd-a24a-ca20f24fd885

This is applying it to custom object:

https://github.com/user-attachments/assets/e22ed1ff-2267-4ac9-9835-9bc60319a406

**Comment by Moult** [comment]
Sorry I'm still a bit confused to how to recreate this. Can you help share your file (or a smaller simpler one) with steps to reproduce?

**Comment by Jumalvelho** [comment]
Hi, sorry the original model contains some confidential data, so I cannot share it. I tried to make an smaller file to reproduce that, but I cannot get it to reproduce that problem. 

But here are steps I did in that model, I traced it to be somekind of problem between ifc object geometry and what geometry Blender shows me, since the openings started to work like they are supposed after I unlinked the probematic obejcts and reassigned them an ifcClass. 

Steps 
1: Create IfcWall object using wall tool in bonsaibim
2: create framing by creating the shape from cube in blender and then assign it IfcBuildingElementPart Class,
3; Create insulation same way as framing and assign it IfcBuildingElementPart class.
4: Modify framing and insulation objects by going to edit mode and stretching then in z direction.
5. Create an aggregate (IfcElementAssembly class) and assing wall, framing and insulation to that. 
6. Crate a cube in blender and position it inside that assembly. Select the cube and assembly "empty" object and add a void through geometry menu
7. What happens now is showed on those clips I posted earlier. 

As I wrote, I suspect it has something to do with me modifying the geometry of those two objects after assigning them an ifcClass. After I unlinked them, deleted their IfcObjects and reassigned them an ifcClass, and added them to Assembly, the openings worked like they are supposed to work. I tried pressing the "Edit object placement" button as well but that did not change the behaviour.

**Comment by Moult** [comment]
Although I still am unsure about your exact issue, there are two most likely reasons I can guess that you're experiencing what you're experiencing.

Possibility 1) you are editing IFC geometry by scaling. IFC does not support scaled geometry (long story short). Adding a void to scaled geometry will result in the wrong void size. (depending on how you scale it, you'll get different results - possibly voids that are larger or smaller - maybe even so large as to cut off the object)

https://github.com/user-attachments/assets/b5c4f4c3-eca7-4160-af3d-5d3ffa091cf4

Possibility 2) you are editing IFC geometry by manually changing the Blender edit mode via the top left dropdown instead of changing the IFC edit mode or hitting tab. This means your geometry changes are reverted when adding a void.


https://github.com/user-attachments/assets/ca7f3d9d-164d-40bd-be13-c4ec759d7224

**Comment by Jumalvelho** [comment]
Yes, I did the second one, I edited IFC geometry by Blender edit mode, hitting tab. Is there any way to make it "apply" changes made in blender edit mode without unlink + reassigning ifc class to geometry?

**Comment by Moult** [comment]
@Jumalvelho hitting tab is ok. Manually selecting the dropdown in the top left is not. Which did you do?

**Comment by Jumalvelho** [comment]
I hit tab.

**Comment by Moult** [comment]
That isn't the issue, then. There must be something else. I'm also not sure why you're pressing the unlink button - that shouldn't be something most users would use, it's a bit of an advanced feature.

I'm going to close this, but if you do manage to come across it again, please do report it and let's reopen this.

Also make sure you're only opening and saving IFC files. Do *not* open and save .blend files. That might be another possibility.
