### ISSUE TITLE
Getting decomposition gets duplicate elements in the case of voids / fills relationships

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5271]
looking at the numbers corresponding to an element in the lower panel of Spatial Decomposition I realized it counts the actual number of that element twice, on expanding it elelments are also listed twice, thanks

![image](https://github.com/user-attachments/assets/b973f473-f7ac-48b3-aaf8-352b67064604)

**Comment by Moult** [comment]
I came across this before and when I checked it was because the model was invalid and had associated the element to the spatial tree twice. Can you share your model or info about where the model came from?

**Comment by steverugi** [comment]
hi @Moult thanks for the reply
OK let me try with a new model from scratch..

**Comment by steverugi** [comment]
file [doublecounting - Copy.txt](https://github.com/user-attachments/files/16828187/doublecounting.-.Copy.txt)
