### ISSUE TITLE
Section displayed in perspective view

### ISSUE THREAD

**Issue by carlopav** [IfcOpenShell/IfcOpenShell#5275]
Section drawing is displayed in the wrong scale in the perspective drawing:
![immagine](https://github.com/user-attachments/assets/63700fdc-b351-461a-aa0f-3b5b5b08bc87)

@Moult suggests to turn off the section cut.

**Comment by brunopostle** [comment]
There is some history of combined perspective and cross-section drawings, both perpendicular to the camera axis, and with arbitrary cuts.

![DP808439~2](https://github.com/user-attachments/assets/6de2dd95-65c7-4564-9f66-9c214241a50f)

![2](https://github.com/user-attachments/assets/70bc97d8-8969-4ac7-a91b-90ca97ad4366)

**Comment by Moult** [comment]
Yes, and they are really beautiful :) just not something supported right now. Right now the camera plane + near clip = section plane. To support this we need to decouple the section plane with the camera fustrum.
