### ISSUE TITLE
Problem in openings substraction

### ISSUE THREAD

**Issue by larakirachidd** [IfcOpenShell/IfcOpenShell#529]
Hello,

I have got a problem with a file in an Ifc conversion to dae, where some openings are not subtracted from Walls.
The problem is hapening with IfcConvert 0.5 release, but when I do it with 0.4 release with (Merged boolean operands), it works perfectly.

The problem is that I need to use (use-element-guids option) that exists only in 0.5 release, so I can not use 0.4 release.
I also tried the latest release in the link below https://github.com/IfcOpenBot/IfcOpenShell/commit/161deeb4e057279cf80645fe1a6cd88cf911fe49#commitcomment-31768103

The Ifc model : https://we.tl/t-7jRLMX3VEF

Thank you very much for your help.

**Comment by aothms** [comment]
Sorry, finally managed to find time to look into this, but the wetransfer link expired. Can you please send again?

**Comment by aothms** [comment]
@larakirachidd Sorry, finally managed to find time to look into this, but the wetransfer link expired. Can you please send again?

**Comment by aothms** [comment]
@larakirachidd ping

**Comment by Moult** [comment]
Closing after no response despite multiple pings.
