### ISSUE TITLE
Cost Schedule export to web problems

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#5296]
Step to reproduce:
- create a fresh new demo file
- create a new cost schedule, for example a simple priced bill of quantities
- insert a couple of cost items
- save the file
- start the websocket
- click on "export to web browser" button with the cost schedule selected

It shows nothing under costing schedule..i tried multiple times but it doesn't work...
Spreadsheet web export works so i guess it is not a problem related to the socket.

Thanks,
Massimo

**Comment by maxfb87** [comment]
It's strange because sometimes it works and sometimes it doesn't..
If i keep the web browser open with the costing tab opened it works but if i click on "schedule" tab and after switch to "costing" tab it doesn't work

**Comment by steverugi** [comment]
same here, at times to make it work I click on the 'export to browser' twice

**Comment by maxfb87** [comment]
@myoualid

**Comment by myoualid** [comment]
It's now been fixed by this commit 83be26e1960346bceed6b78e0c7e1b6301d21676
