### ISSUE TITLE
(python) Iterating over geometry with cache fails

### ISSUE THREAD

**Issue by Grosskopf** [IfcOpenShell/IfcOpenShell#5299]
Good morning, I hope all is going well with the new release so far, was positively surprised by a few changes that made me find errors in my code I previously didn't notice :)

was a bit of figuring out to find the right settings for exporting everything similar to how I did back before 0.7.10 :D

there are some errors in the ifcopenshell-python 0.8.0 left though, so this is one I found:

when I use geom.iterate with the hdf5 cache file, I get the following error:

python3.11/site-packages/ifcopenshell/geom/main.py", line 485, in iterate
    hdf5_cache = serializers.hdf5(cache, settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HdfSerializer.__init__() missing 1 required positional argument: 'settings'

I assume this is an easy one to fix for someone who understands the new system with the two settings objects better than I do :) maybe optional parameters would be awesome in cases like this but that might be too much to ask of a wrapper :D

I can work without cache for a bit, and wold be awesome to get some more hints on how to exchange the various settings that were removed, but I'll do my best to dig into the c++ code for this a bit more later :)

Have a wonderful day

**Comment by Andrej730** [comment]
@Grosskopf Thank you for the bug report, `iterate` was missing `serializer_settings` argument, fixed now.

https://docs.ifcopenshell.org/ifcopenshell/geometry_settings.html is not fully updated yet, you can find some hints for the new settings either from https://github.com/IfcOpenShell/IfcOpenShell/issues/4832 or you can search 0.7.0 codebase (https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0 or https://github.com/Andrej730/IfcOpenShell_v0.7.0 for github search) and check the current code base to see how the settings was replaced.

**Comment by Grosskopf** [comment]
Awesome :) there is also an occurence of `INCLUDE_CURVES` in app.py in the python code, `INCLUDE_CURVES` seems among the removed settings but I haven't had that line of code run yet :)

I replaced `DISABLE_TRIANGULATION=True` with `ITERATOR_OUTPUT=ifcopenshell.ifcopenshell_wrapper.NATIVE` after reading through https://github.com/IfcOpenShell/IfcOpenShell/commit/65e874c67f07acdde3d8e08fd7aa33cf141f4d5d

my code contained a reference to `INCLUDE_CURVES` before, but now it seems to run without that setting :) awesome, what an amazing day of learning how to read and understand those settings changes
