### ISSUE TITLE
Display Message: fit and allign a message into a Face

### ISSUE THREAD

**Issue by JPMertens** [IfcOpenShell/IfcOpenShell#530]
Hello,

i am trying to display the despription for each product on the 2D plan using this example: http://academy.ifcopenshell.org/using-ifcopenshell-and-pythonocc-to-generate-cross-sections-directly-from-an-ifc-file/

Right now I have got it working that it displays the product names in the middle of the products' face using DisplayMessage(point, text_to_write, height=None, message_color=None, update=False)

props = OCC.GProp.GProp_GProps()
OCC.BRepGProp.brepgprop_SurfaceProperties(face, props)
p = props.CentreOfMass()
occ_display.DisplayMessage(p, product.Name, update=False)

The strings are always horizontal in the viewer, no matter how one changes the position/angle of the 2D plan.
What I want to achieve is to fit the description inside the faces and parellel to the longest edge of each face.

Using the DisplayMessage function how can set the direction of the string to be fixed in the direction of the longest edge of the face and fix the height of the message no matter how far i zoom in or out?

Thanks in advance

**Comment by aothms** [comment]
Hi,

I understand you want a solution for this, but this is the exact same questions as asked here https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/6aef0fe571/?limit=25#8ad7

And again, this is not really related to IfcOpenShell in the first place, but rather the viewer component from Open CASCADE.
