### ISSUE TITLE
"Your model may be outdated" leads to a 404 docs page

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5310]
Currently having a bug where my IfcBuilding disappeared from the outliner and I guess Bonsai understood that something is missing, I'm presented with this message

![image](https://github.com/user-attachments/assets/d32384d6-45a5-4b06-9bff-6b5b1f1af589)

But the link goes to https://docs.bonsaibim.org/users/troubleshooting.html#saving-and-loading-blend-files which is a 404 (or I don't have the rights ?)

**Comment by Moult** [comment]
This has been fixed, new url is https://docs.bonsaibim.org/guides/troubleshooting.html#saving-and-loading-blend-files
