### ISSUE TITLE
Git feature softlock when deleting the git folder

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5311]
Steps to reproduce : 

- Create a new ifc file
- Commit once to create the git folder
- Delete the git folder
- Save the file
- The Git panel reduces back to that
![image](https://github.com/user-attachments/assets/f35a1304-dafc-45ce-b6f4-73eb037ee68b)
```
-   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\git\repo\base.py", line 998, in _get_untracked_files
    finalize_process(proc)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\git\util.py", line 504, in finalize_process
    proc.wait(**kwargs)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\git\cmd.py", line 834, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git status --porcelain --untracked-files
  stderr: 'fatal: not a git repository (or any of the parent directories): .git
```

I don't mind getting an error since the git folder was deleted but I would expect a button to either purge the git data from the ifc file or re-create a blank git repository.

Just to elaborate I'm sharing both the blend file and ifc file to a member of my team but I don't want to share the .git folder alongside it. But that workflow softlocks the git features from the Blender file.

**Comment by Moult** [comment]
Ping @brunopostle

**Comment by brunopostle** [comment]
I see this. It should be easy enough to recover in this situation (I'm suffering from fix a bug, uncover two more syndrome at the moment)
