### ISSUE TITLE
Measure tool should allow previous measurements to stay on screen until user clears them

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5315]

**Comment by brunoperdigao** [comment]
This was implemented in the latest commits. To erase the measurements, the user must press "E" while using the measure tool.
The measurements are also part of the snapping system, meaning they can be used as construction lines.
@Moult I used the white color, but maybe they should be dark gray? What are your thought on that?

**Comment by Moult** [comment]
Although semantically measurements can be seen as "construction lines" in the background, I think they're more important than that. Imagine users taking measurements then taking screenshots to show to others. They really need to stand out on the screen. So perhaps even the "special" colour (i.e. blue) makes more sense.
