### ISSUE TITLE
Area measurement tool

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5316]

**Comment by brunoperdigao** [comment]
@Moult For the measure tool, I think we could use the small header icons to choose between modes, like in the Blender Select Box example below. That way we could have icons for single measure, polyline measure and area measure. So, "Shift+M" would trigger the corresponding operator based on what icon is selected. What do you you think?

![Image](https://github.com/user-attachments/assets/902d6e0f-a13c-4926-ae7b-7e92133aedb7)

**Comment by Moult** [comment]
Great idea!

**Comment by brunoperdigao** [comment]
@Moult Here is a demonstration of the UI. What do you think?

Single measure with x, y, and z axis:
![blender_DyAr6SjSI6](https://github.com/user-attachments/assets/931060e4-d4ee-454d-8bed-181732ea9f0e)

Area measure:
![blender_lAU52nfRXb](https://github.com/user-attachments/assets/5a40ab12-1b85-4383-ac2f-858bf5fc2c98)

**Comment by Moult** [comment]
Looks absolutely beautiful!

**Comment by brunoperdigao** [comment]
I think this can be closed. I just fixed the last bug I had found.

**Comment by Isaina** [comment]
@ brunoperdigao, Hi Bruno can you give a look attached link bellow is possible to make this type model for 3D duct and pipes you have experience in finding object and make 3d path in xyz space 

https://youtu.be/3hnOVpwxGKs?feature=shared

**Comment by brunoperdigao** [comment]
Hi @Isaina, thanks for the reference. The main idea is to improve all the modeling tools to work with the polyline tool. I'm not familiar yet with how the MEP tools work in Bonsai, but it should be possible to create something similar in the long run. I would say that there are still a few things to improve with walls and slabs. Luckily, it will be easier to work in other tools after that.

**Comment by brunoperdigao** [comment]
@Isaina feel free to open another issue with your idea as a feature request.
