### ISSUE TITLE
Allow replacement of numbers when typing in for wall polyline tool

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5317]
When typing in a number when first "focusing" (i.e. tab) on a parameter, for convenience it should replace the existing number (e.g. distance). The exception if they press backspace (or = symbol?), in that case it should modify the existing number.

**Comment by brunoperdigao** [comment]
This was implemented recently. It will replace the existing number, unless you press "=", which will trigger expression, or "Backspace", which will delete the last character.

**Comment by brunoperdigao** [comment]
![blender_vlCE2y4aNl](https://github.com/user-attachments/assets/82353bbc-6dcb-43c6-ac83-627a57b4f88c)
