### ISSUE TITLE
Allow custom angle snapping in polyline tool

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#5323]

**Comment by Moult** [comment]
What do you think about changing the angle snap to 15 increments, then also supporting reading the current Blender axis (that thing top middle of the viewport?)

**Comment by brunoperdigao** [comment]
I agree. However I don't know if every option of axis is actually useful, maybe only world, local, cursor and custom?

**Comment by brunoperdigao** [comment]
My current solution for this was implemented in 48784ba834d88324ab379ef7880cf18e2e323b76.
I experimented with the idea of the user typing the desired angle, but it got confusing with the current way the input UI works. So I thought this way was going to cover most use cases. 
It still on the roadmap to use Blender Orientation Transform Orientation

**Comment by brunoperdigao** [comment]
@theoryshaw @Moult Have you tried this? Would love your feedback.

> - Press "L" while the tool is active to lock axis to the current angle.
>- Press "Shift" + "Mouse Wheel" up or down to adjust the angle.
>
>If using with the measure tool it will only work if you have a plane method selected.

**Comment by theoryshaw** [comment]
for sure... 
ran into this error, however, when trying to initiate the tool. 

```
bpy.ops.bim.measure_tool()
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 2426, in modal
    self.handle_instructions(context)
TypeError: PolylineOperator.handle_instructions() missing 1 required positional argument: 'custom_instructions'

```

**Comment by brunoperdigao** [comment]
@theoryshaw should be fixed now

**Comment by theoryshaw** [comment]
awesome. 

> Press "Shift" + "Mouse Wheel" up or down to adjust the angle.

i couldn't get this to work... maybe i'm missing how to activate it. 

Also, using `A` doesn't seem to work.

**Comment by brunoperdigao** [comment]
I actually assigned "L" to lock to an angle. After you lock you can use "Shift" + "Mouse Wheel" to adjust.
