### ISSUE TITLE
Improve polyline tool snap symbols to work like Blender snap symbols

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#5325]

**Comment by Moult** [comment]
Really nice!

**Comment by Plae-Blue-Dot** [comment]
Amazing tool thankyou Bruno!

Some feedback on one issue with the snaps
 
When snapping to an empty (for instance creating the 1st wall in the whole project) the results of the geometry are super inconsistent:
![image](https://github.com/user-attachments/assets/753dcaed-186b-4ef5-abcd-a2dfd9eb03a6)

When I click the origin is not on the point I thought it was:
![image](https://github.com/user-attachments/assets/7841476c-061d-44d8-b839-9adf27eb2c4b)

And the end result is a wall that is off centre:
![image](https://github.com/user-attachments/assets/b89c4174-e2d9-4efe-9151-a5a0d607da38)


The end result is that every time I think I am snapping to an empty I get a different result

This does not seem to be an issue when snapping to geometry (example other walls)

SO my current work flow is add my 1st project wall the old fashioned way with Shift A -> adjust the length

Then use the wall as my starting point for the wall polyline tool

**Comment by brunoperdigao** [comment]
Hi, @Plae-Blue-Dot, thanks for the feedback. This issue should be fixed by the commits below. Let me know if you find any other issues.
https://github.com/IfcOpenShell/IfcOpenShell/commit/3c2a0c9bf3b3aa7980b96de7a094c4b24787149f
https://github.com/IfcOpenShell/IfcOpenShell/commit/98d767988e087b7a6752b15225800ca1c20dce13

**Comment by Plae-Blue-Dot** [comment]
Working perfectly @brunoperdigao! and looking amazing!
