### ISSUE TITLE
after opening `bim.launch_type_manager()` and using the `search for property` I would expect the type manager to stay open. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5333]
This is a UI thing.... after opening `bim.launch_type_manager()` and using the `search for property` I would expect the type manager to stay open. 

https://github.com/user-attachments/assets/db708c33-c39c-457e-a7eb-32525cfdef41

**Comment by Gorgious56** [comment]
Hehe I'm always surprised by the music in your video snippets >< Hmm, that is indeed a UX papercut. However I'm not sure it's doable due to how it's currently implemented. Blender really doesn't like having and dealing with multiple popup windows.
