### ISSUE TITLE
Issues with grid management

### ISSUE THREAD

**Issue by manuvarkey** [IfcOpenShell/IfcOpenShell#5337]
Following issues are found in dealing with grids.

1. Editing grid tag is not reflected immediately in workspace. Saving IFC and loading the file reflects the modified tag.
2. While going into edit mode (Tab) for editing grid (moving end points), the green selection highlight and annotations are visible which makes it hard to select the vertices and make modifications.
3. Once a grid is added, it is not possible to remove the last two grid lines (in each perpendicular directions).

**Comment by Moult** [comment]
Note that deleting the last two grid lines is blocked on purpose because it is not allowed in IFC - you need a minimum of 2 axes (one U and another V). Instead, just delete the IfcGrid itself.
