### ISSUE TITLE
Unable to modify elevation in spatial decomposition manager

### ISSUE THREAD

**Issue by manuvarkey** [IfcOpenShell/IfcOpenShell#5341]
Once elevation values are edited in spatial decomposition manager, new values are shown as modified but reverts to old value on clicking `Load Container Manager` (refresh icon).

**Comment by theoryshaw** [comment]
I think you have to save the ifc, for it to 'stick'.

**Comment by manuvarkey** [comment]
> I think you have to save the ifc, for it to 'stick'.

Yes saving works. But current behaviour seems a bit confusing. User may click on refresh after creation of spaces for ex. and will have the modifications done to elevations lost.
