### ISSUE TITLE
What are the replacements for Argument and getArgument()

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#5343]
Some of my code has broken due to IfcOpenShell updates. The type `Argument` is no longer exists. There was also a function called `getArgument`.

What are the replacements for these?

I think changes are in commit d80bcd1a

**Comment by Andrej730** [comment]
@RickBrice There is some example in IfcParseWrapper.i if it is the one.

![image](https://github.com/user-attachments/assets/413673d8-0a57-4e10-a0d1-f568b3c4230a)

https://github.com/IfcOpenShell/IfcOpenShell/commit/d80bcd1a94906b46851e998d2bdce20439fe9745#diff-b7d615e0dc5ac4d04c30da425e5405ff52e354b48282e61435a145a62911cd91

**Comment by aothms** [comment]
Sorry about the braking changes. I assumed you were (mostly?) using the typed schemas which didn't change.

Access by name:

https://github.com/IfcOpenShell/IfcOpenShell/blob/795d2c371e6051bb437f5b09bd7cbd0d1d7db25c/src/ifcparse/IfcBaseClass.h#L150-L156

Access by index (use `.data()` to go from instance to data):

https://github.com/IfcOpenShell/IfcOpenShell/blob/795d2c371e6051bb437f5b09bd7cbd0d1d7db25c/src/ifcparse/IfcEntityInstanceData.h#L183

Setting:

https://github.com/IfcOpenShell/IfcOpenShell/blob/795d2c371e6051bb437f5b09bd7cbd0d1d7db25c/src/ifcparse/IfcBaseClass.h#L112-L118

Converting `AttributeValue` to concrete types is the same as `Attribute*`, accept for the fact that you no longer need to dereference the pointer.

**Comment by RickBrice** [comment]
Thanks for the info. Perhaps I'm doing something incorrectly (or could be doing it better)

I'm trying to get the conversion factor for an IfcConversionBasedUnit. This is what I figured out. Any suggestions?

https://github.com/RickBrice/PGSuperIfcExtensions/blob/d0fe227ab6aa3c78ce430ca2773be1a3454e4709/IfcAlignmentConverter.cpp#L134-L154

**Comment by aothms** [comment]
Maybe this helps:

```C++
	if (conversion_based_unit) {
		auto measure_with_unit = conversion_based_unit->ConversionFactor();
		auto unit_component = measure_with_unit->UnitComponent()->as<typename Schema::IfcSIUnit>();
		Float64 conversion_factor;
		try {
			auto value_component = measure_with_unit->ValueComponent();
			ATLASSERT(value_component); // not dealing with anything but simple conversion factors
			conversion_factor = static_cast<Float64>(value_component->data().get_attribute_value(0));
		} catch (IfcParse::IfcInvalidTokenException& e) {
			// Was expecting something like 
			// #15 = IFCMEASUREWITHUNIT(IFCLENGTHMEASURE(3.28083333333333), #16);
			// where the expected token is IFCLENGTHMEASURE, but instead found something like
			// #15=IFCMEASUREWITHUNIT(3.28083333333333,#16);
			// we'll just get the value and keep going
			TRACE(e.what());
			auto pArgument = measure_with_unit->get("ValueComponent");
			ATLASSERT(pArgument.type() == IfcUtil::Argument_DOUBLE);
			conversion_factor = double(pArgument);
		}
	}
```

**Comment by RickBrice** [comment]
Thanks
