### ISSUE TITLE
IfcOpenShell compiled with IFC4 doesn't read IFC2x3 anymore?

### ISSUE THREAD

**Issue by yorikvanhavre** [IfcOpenShell/IfcOpenShell#536]
Hi Thomas,

It looks like IfcOpenShell, when compiled with IFC4 support, doesn't read IFC2x3 files anymore?
Example with this file: https://github.com/OpeningDETAIL/Newport_Beach_CA_Residence/blob/master/Models%20%26%20CAD/BIM/IFC%20sections/Sections%20B.ifc

```
Python 3.7.2 (default, Jan  3 2019, 02:55:40) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> f=ifcopenshell.open("Sections B.ifc")
>>> f[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ifcopenshell/file.py", line 79, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key))
  File "/usr/lib/python3/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 1781, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Instance #1 not found
```

If I open the file with a text editor, and replace IFC2X3 with IFC4:

```
Python 3.7.2 (default, Jan  3 2019, 02:55:40) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> f=ifcopenshell.open("Sections B.ifc")
>>> f[1]
#1=IfcPerson($,$,'Yorik van Havre',$,$,$,$,$)
```

I'd be happy to try to fix this if you point me in the right direction... Looking at the code in IfcParse, it looks to me that things are pretty separated, it's one schema or the other, but I think to remember it used to work before, no?

Cheers
Yorik

**Comment by aothms** [comment]
In terms of the python api, the 0.6 branch is very similar to current master.

While it's true that a different schema then the source code was previously silently accepted. It's really not recommended. IFC4 is not a strict supertype of 2x3. Some deprecated classes have been removed for example. Accessing IFC4 attributes on a 2x3 dataset would also of course not work.

0.6 will be the current master in the pretty near future, so I think it'd be wise for freecad to have a look.

It's odd though that you don't get any exception about opening a file with different schema. That should probably be changed.

**Comment by yorikvanhavre** [comment]
Thanks folks! I hadn't realized the 0.6.0 branch was ahead of master, silly me, freecad bad habit :) Will give it a test spin, indeed it's a good idea to check it with freecad ahead... Happily closing this then!
