### ISSUE TITLE
Exporting STEP File with Labels Associated to IfcShapeAspect – Location Issue

### ISSUE THREAD

**Issue by mlaura1996** [IfcOpenShell/IfcOpenShell#5363]
I’m trying to export the geometry of IfcElements from my IFC file into a STEP file while maintaining the division of 'shape aspects'. For each solid corresponding to a IfcShapeAspect, I want to associate a label in the STEP file that corresponds to the material of that shape aspect.

I have managed to associate the labels with the materials, but when I export to the STEP file, all the IfcElements appear to be placed in the same location (see attached picture).
![image](https://github.com/user-attachments/assets/242d6a92-540e-40a5-ac21-893afb1320e4)

While the relative positions of the 'items' within each IfcElement are correct, it seems that the global location of the elements is not being considered during the export.

I suspect that the transformation matrices or placements of the elements are not being accounted for properly (see the original IFC pic below).
![image](https://github.com/user-attachments/assets/77fb3d8a-9e77-4b99-a390-49f661126fd7)

Attachments:
Code snippet (for context)

```
import ifcopenshell
import ifcopenshell.geom
from OCC.Core.STEPControl import (STEPControl_AsIs, STEPControl_Writer)
from OCC.Core.Interface import Interface_Static_SetCVal
from  OCC.Core.STEPConstruct import *
from OCC.Core.TCollection import TCollection_HAsciiString
from OCC.Extend.DataExchange import read_step_file_with_names_colors


#Geometry of IFC
settings = ifcopenshell.geom.settings()
settings.set(settings.USE_PYTHON_OPENCASCADE, True) #generalinfo

#StepWriter
schema = 'AP203'
assembly_mode = 1
writer = STEPControl_Writer()
fp = writer.WS().TransferWriter().FinderProcess()
Interface_Static_SetCVal('write.step.schema', schema)
Interface_Static_SetCVal('write.step.unit', 'M')
Interface_Static_SetCVal('write.step.assembly', str(assembly_mode))

ifc_file = ifcopenshell.open('./Models/MultimaterialDoorV3.ifc')
elements = ifc_file.by_type('IfcBuildingElement')

shapes = []
labels = []

doors = ifc_file.by_type("IfcDoor")
for door in doors: 
    label = []
    shapes = []
    doorTypeRels = door.IsTypedBy
    for doorTypeRel in doorTypeRels:
        doorType = doorTypeRel[5] 
 
        for repMap in doorType.RepresentationMaps:
            MappedRepresentation = repMap.MappedRepresentation
            ShapeAspects = repMap.HasShapeAspects

            for shapeAspect in ShapeAspects:
                label = shapeAspect[1]

                print(label)
                shapeOfshape = []
                labels.append(label)
                for rpr in shapeAspect[0]:
                    #print(rpr)
                    items = rpr[3]

                    for item in items:
                        shape = ifcopenshell.geom.create_shape(settings, item)                        
                        print(shape)

                        Interface_Static_SetCVal('write.step.product.name', label)
                        status = writer.Transfer(shape, STEPControl_AsIs)

                        item = stepconstruct_FindEntity(fp, shape)
                        item.SetName(TCollection_HAsciiString(label))

writer.Write('ex5.step'), read_step_file_with_names_colors('ex5.step')
```
(In the zip file attached my ifc example and step)

[IfcOpenShellIssue.zip](https://github.com/user-attachments/files/16943277/IfcOpenShellIssue.zip)

**Comment by Moult** [comment]
I think you can just use the built in step serialiser - that's what IfcConvert uses too: https://docs.ifcopenshell.org/ifcopenshell-python/geometry_processing.html#geometry-serialisation - note that the docs don't show it as a particular example but you might be able to get it working. Also it looks as though your version is outdated?

**Comment by aothms** [comment]
> I suspect that the transformation matrices or placements of the elements are not being accounted for properly 

Correct. Not accounted for at all. Because that's how the IFC schema works. 

You traverse `door.IsTypedBy[].RelatingType.RepresentationMaps[]...` but the actual door placement is at `door.ObjectPlacement` which is not assessed in anyway.

And I must say we also don't have a really good API for this. To evaluate a placement as a native OCCT Trsf/Location in Python.

So you can use `ifcopenshell.util.placement` to evaluate `door.ObjectPlacement` as a 4x4 numpy matrix. Convert these to gp_Trsf (the 3x3 vectorial part + the 1x3 translation part). And then to TopLoc_Location and mutliply that into `shape.Location`. Or you use `ifcopenshell.geom.create_shape(settings, door)` which gives you a TopoDS_Compound from which you can extract the Location and assign to shape or create an `TopoDS_Shape.EmptyCopied()` from that compound and then use BRep_Builder to add the shapeaspect shape under that 'empty' (but retaining the location) compound.

I hope this is somewhat clear. These things are complex to figure out, but it seems you already got quite far.

And yes, it would also be really cool if you see some improvements you can make to the STP serializer in ifcopenshell. Very few people in the community got to the level where you are. Quite some people in the community are interested in the STP serializer (even some tekla addin used ifcconvert for STP export (in the past or still, don't know)) but the ifcopenshell STP serializer is very limited and not flexible at this point.

**Comment by mlaura1996** [comment]
Thank you for your hints!

I am using an older version of ifcopenshell because I was having some issues exporting the shapes :( I don't know if this has to due with the recent upgrade of open cascade. 

Now I manage to move the shapes, but I am still figuring how to rotate them appropriately. 
![image](https://github.com/user-attachments/assets/b7bf6442-c032-4d15-ae2d-f3eb3e9487c3)

`import ifcopenshell
import ifcopenshell.geom
from OCC.Core.STEPControl import (STEPControl_AsIs, STEPControl_Writer)
from OCC.Core.Interface import Interface_Static_SetCVal
from  OCC.Core.STEPConstruct import *
from OCC.Core.TCollection import TCollection_HAsciiString
from OCC.Extend.DataExchange import read_step_file_with_names_colors
import OCC.Core.TopoDS
from OCC.Core.STEPControl import (STEPControl_AsIs, STEPControl_Writer)
from OCC.Core.Interface import Interface_Static_SetCVal
from  OCC.Core.STEPConstruct import *
from OCC.Core.TCollection import TCollection_HAsciiString
from OCC.Extend.DataExchange import read_step_file_with_names_colors
import OCC.Core.AIS
import OCC.Core.XCAFDoc
import OCC.Display.SimpleGui
from OCC.Core.IFSelect import IFSelect_RetError
from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_Sewing
from OCC.Core.TopExp import TopExp_Explorer
from OCC.Core.TopAbs import TopAbs_FACE
from OCC.Core.BRep import BRep_Builder
from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeSolid
from OCC.Core.TopoDS import TopoDS_Compound, topods
from OCC.Core.BRep import BRep_Builder
from OCC.Core.TopLoc import TopLoc_Location
from OCC.Core.TopAbs import TopAbs_SHAPE
from OCC.Core.TopoDS import TopoDS_Compound, topods
from OCC.Core.TopExp import TopExp_Explorer
from OCC.Core.TopAbs import TopAbs_COMPOUND

from OCC.Core.BRep import BRep_Builder

import Translation

from OCC.Core.gp import gp_Trsf, gp_Pnt, gp_Vec
from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_Transform
from OCC.Core.TopLoc import TopLoc_Location

#Geometry of IFC
settings = ifcopenshell.geom.settings()
settings.set(settings.USE_PYTHON_OPENCASCADE, True) #generalinfo

#StepWriter
schema = 'AP203'
assembly_mode = 1
writer = STEPControl_Writer()
fp = writer.WS().TransferWriter().FinderProcess()
Interface_Static_SetCVal('write.step.schema', schema)
Interface_Static_SetCVal('write.step.unit', 'M')
Interface_Static_SetCVal('write.step.assembly', str(assembly_mode))

ifc_file = ifcopenshell.open('./Models/MultimaterialDoorV3.ifc')
elements = ifc_file.by_type('IfcBuildingElement')

shapes = []
labels = []

def create_empty_compound_at_location(shape):
    # Create an empty compound
    builder = BRep_Builder()
    compound = TopoDS_Compound()
    builder.MakeCompound(compound)

    # Get the location (TopLoc_Location) from the existing shape
    shape_location = shape.Location()

    # Apply the location to the compound
    compound_location = shape_location
    compound.Move(compound_location)

    return compound

def merge_compounds(compounds):
    # Create a new empty compound
    builder = BRep_Builder()
    unified_compound = TopoDS_Compound()
    builder.MakeCompound(unified_compound)
    
    # Loop over the list of compounds
    for compound in compounds:
        # Extract each shape in the current compound
        explorer = TopExp_Explorer(compound, TopAbs_SHAPE)
        while explorer.More():
            shape = topods.Shape(explorer.Current())
            # Add the shape to the new unified compound
            builder.Add(unified_compound, shape)
            explorer.Next()

    return unified_compound


doors = ifc_file.by_type("IfcDoor")
for door in doors:
    AllShapes = []
    shape = ifcopenshell.geom.create_shape(settings, door)
    shape = OCC.Core.TopoDS.TopoDS_Iterator(shape.geometry).Value() #This is the shape of the door
    location = shape.Location() #This is the location of the main door compound

    

    locationXYZ = location.Transformation().TranslationPart()
    locationPoint = gp_Pnt(locationXYZ)
    #Create a empty compound at the location of the shape
    EmptyCompound = create_empty_compound_at_location(shape)
    label = []
    shapes = []
    doorTypeRels = door.IsTypedBy
    for doorTypeRel in doorTypeRels:
        doorType = doorTypeRel[5] 
 
        for repMap in doorType.RepresentationMaps:
            MappedRepresentation = repMap.MappedRepresentation
            ShapeAspects = repMap.HasShapeAspects

            for shapeAspect in ShapeAspects:
                label = shapeAspect[1]
                print(label)
                shapeOfshape = []
                labels.append(label)
                for rpr in shapeAspect[0]:
                    #print(rpr)
                    items = rpr[3]

                    
                    for item in items:
                        shape = ifcopenshell.geom.create_shape(settings, item)                         
                        AllShapes.append(shape)                   
                        #print(shape)


    print(AllShapes)

    mergedCompounds = merge_compounds(AllShapes)
    #print(merged)
    mergedLocation = mergedCompounds.Location()
    mergedLocationXYZ = mergedLocation.Transformation().TranslationPart()
    mergedLocationPoint = gp_Pnt(mergedLocationXYZ)
    print(mergedLocationPoint)
    generalTranslationVector = gp_Vec(mergedLocationPoint, locationPoint)

    trsf = gp_Trsf()
    trsf.SetTranslation(generalTranslationVector)

    for solid in AllShapes:
        #FirstTranslation
        transformer = BRepBuilderAPI_Transform(solid, trsf)
        moved_solid = transformer.Shape()

        #NewTransformation
        solidOriginalLocation = solid.Location()
        solidXYZ = solidOriginalLocation.Transformation().TranslationPart()
        solidPoint = gp_Pnt(solidXYZ)
        localVector = gp_Vec(mergedLocationPoint, solidPoint)
        LocalTrsf = gp_Trsf()
        LocalTrsf.SetTranslation(localVector)
        transformer = BRepBuilderAPI_Transform(moved_solid, LocalTrsf)
        FinalSolid = transformer.Shape()

        
        Interface_Static_SetCVal('write.step.product.name', "label")
        status = writer.Transfer(FinalSolid, STEPControl_AsIs)

        item = stepconstruct_FindEntity(fp, FinalSolid)
        item.SetName(TCollection_HAsciiString(label))


writer.Write('example.step'), read_step_file_with_names_colors('example.step')`

(for now I will ignore the labeling, then I will create a dictionary to associate the label with the shape)

Once I will figure better how to work with the orientation maybe I can add these new functions to the step serialiser :)

**Comment by aothms** [comment]
> Now I manage to move the shapes, but I am still figuring how to rotate them appropriately.

Yes, because you're explicitly calculating the `Transformation().TranslationPart()`. But you can compute on the full Transform/Matrix as well. Location().Transformation() gives you a gp_Trsf. These can be combined with PreMultiply or Multiply https://dev.opencascade.org/doc/occt-6.9.1/refman/html/classgp___trsf.html#ad5bf2f3a18d9cf1345b4222dce987c5f That would combine the full location+orientation.

> Once I will figure better how to work with the orientation maybe I can add these new functions to the step serialiser :)

:)
