### ISSUE TITLE
IfcTriangulatedFaceSet not accessible with python wrapper

### ISSUE THREAD

**Issue by hlg** [IfcOpenShell/IfcOpenShell#537]
I am using the Python 2.7 v0.5.0 Linux 64bit release and try to access the geometry in this [test file](http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/annex/annex-e/tessellated-item.htm). 

    file = ifcopenshell.open("tessellated-item.ifc")
    repr = file.by_type("IfcRepresentation")[0]   # there is only one
    repr.ContextOfItems
    repr.Items

Everything works well unless I try to access the items, then I get this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/python2.7/site-packages/ifcopenshell/entity_instance.py", line 43, in __getattr__
    self.wrapped_data.get_argument(self.wrapped_data.get_argument_index(name)))
  File "/path/to/python2.7/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 1379, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Entity not found
```

This does not happen with other examples with other representation types, e.g. IfcExtrudedAreaSolid.

**Comment by hlg** [comment]
I realize that this version is not compiled with IFC4 support. Tried an automated build from the branch 0.6.0 which does automatic recognition and that works fine.

**Comment by aothms** [comment]
> I realize that this version is not compiled with IFC4 support

Indeed. More recent versions of the 0.5 branch will no longer silently accept a different schema to prevent this confusion in the first place. Glad that you resolved it.
