### ISSUE TITLE
Fix in ifcclash.py to export bcf viewpoints

### ISSUE THREAD

**Issue by MakeDrive** [IfcOpenShell/IfcOpenShell#5377]
https://github.com/IfcOpenShell/IfcOpenShell/blob/e3c23072a57017f74c6ba93f9aa8de51046d2505/src/ifcclash/ifcclash/ifcclash.py#L162

This should be np.array(clash["p1"]) to work with the output of the clash function

![image](https://github.com/user-attachments/assets/b5c9048d-f648-4b39-8fc9-8e80b32b3d79)

**Comment by Andrej730** [comment]
Thanks for the bug report, should be fixed.
