### ISSUE TITLE
Be able to duplicate IfcSpaces

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5379]
This might be in the roadmap anyway, but with recent changes, IfcSpaces cannot be duplicated, even after unlocking, etc. 

Would be nice to regain this functionality.

**Comment by Andrej730** [comment]
Are there any errors in the console? Seems to work for me.

https://github.com/user-attachments/assets/98a72fb2-89da-4212-9581-470480427ded

**Comment by theoryshaw** [comment]
file if you need it: https://hub.openingdesign.com/OpeningDesign/2917_International_Ln/src/commit/c030130ffced43b47550d6e8724ea625e0a04d48/Open/Models/BlenderBIM/2917_International_Ln.ifc


https://github.com/user-attachments/assets/a3bbc03e-b95b-453f-ad0f-cbdd353881c3

**Comment by Andrej730** [comment]
It's a different lock - you need to check this one in the spatial manager:

![image](https://github.com/user-attachments/assets/22239f23-2300-4dc4-8a0a-f0c5cdd763c6)

**Comment by theoryshaw** [comment]
Got it! thanks!
