### ISSUE TITLE
Blender 4.2: Failing to load

### ISSUE THREAD

**Issue by MichaelDalsgaard** [IfcOpenShell/IfcOpenShell#5383]
Bonsai BIM failing to load in Blender 4.2. Unsure if the version is supported.

Said it was supported here. https://extensions.blender.org/add-ons/bonsai/

Error message:
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
blender_version: 4.2.0
blenderbim_version: 0.0.240602
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\mpd\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\__init__.py", line 96, in <module>
    import blenderbim.bim
ModuleNotFoundError: No module named 'blenderbim'

**Comment by Moult** [comment]
How did you install this? The name "blenderbim" has been removed from the source code. Can you try with a fresh 4.2 and follow https://docs.bonsaibim.org/quickstart/installation.html ?

**Comment by Andrej730** [comment]
> blenderbim_version: 0.0.240602

@MichaelDalsgaard This an old version that doesn't have support for Blender 4.2, try the latest release - https://bonsaibim.org/download.html

**Comment by MichaelDalsgaard** [comment]
@Moult Thank you. This solved my issue. I was just downloading it from one of the first search results in Google. Followed the guide and it worked.
