### ISSUE TITLE
Advanced mode loading objects that are not selected

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5385]
I experienced this with more models. For example, I choose to load only IfcCovering entities but I end up with spaces, doors, etc.

Not with only one model, so I guess there is a glitch somewhere when using advanced mode now.

**Comment by Moult** [comment]
Can you provide a sample model and the query you're using?

**Comment by Moult** [comment]
Bump?

**Comment by BIMvoice** [comment]
It's been a while so I don't know which model I used. 

Try this one, the spaces are coming along if you select only other classes.

[12345_123456_1234567_ARK_0_0.zip](https://github.com/user-attachments/files/17291975/12345_123456_1234567_ARK_0_0.zip)
