### ISSUE TITLE
Problem linking ifc from shared folder on Windows

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#5386]
Step to reproduce:
- create a fresh new IFC blank file
- geolocate it and save it as for example "external area.ifc" and exit
- create a fresh new IFC demo file
- geolocate it with the same coordinate system as the first model, but, for example, about 10m displaced
- create four walls
- save the file as "building1.ifc" and exit
- open the model "external area.ifc" and try to link "building1.ifc", it doesn't load the file and show this error:
![image](https://github.com/user-attachments/assets/f99ad0a3-49db-4583-acc2-4eec7f2cf8be)

**Comment by Andrej730** [comment]
@maxfb87 can you please attach example .ifc files?

**Comment by maxfb87** [comment]
Thanks @Andrej730 i attach the two files here (please rename .txt to .ifc)
[building1.txt](https://github.com/user-attachments/files/17491880/building1.txt)
[external_area.txt](https://github.com/user-attachments/files/17491882/external_area.txt)

**Comment by Andrej730** [comment]
@maxfb87 does it breaks on the latest version of Bonsai? Couldn't reproduce this:

![image](https://github.com/user-attachments/assets/bcdd09b9-c502-4ff8-a711-984517697325)

**Comment by maxfb87** [comment]
@Andrej730 yeah, it breaks also with today release... maybe i'm missing something but i just press link and load the .ifc file, without saving also the .blend file...

**Comment by maxfb87** [comment]
Maybe it's beacause the files are stored in a lan shared folder?

**Comment by maxfb87** [comment]
@Andrej730 yeah, i confirm you that the problem it is because the files are stored in a shared folder in the file server...if i copy/paste the files into a local folder, it works ok...

**Comment by Andrej730** [comment]
Was able to reproduce this by creating a shared folder, turned out it doesn't require setting up a server or something. Resolved now. A tricky issue, haven't seen this one before, see commit description for the details.
