### ISSUE TITLE
Outliner text display intermittent weirdness

### ISSUE THREAD

**Issue by 4nigel** [IfcOpenShell/IfcOpenShell#5387]
Bonsai v0.8.1-alpha240913-aa3a362 Blender 4.2.1 Windows 10 64
![image](https://github.com/user-attachments/assets/9bcadacd-6b90-4d53-b260-f1d49ba25535)

selecting any object can cause this display weirdness, moving the mouse cursor into the Outliner window causes normal display

**Comment by kurb70** [comment]
I also observe this behaviour on macOS. However, I cannot determine under what circumstances it occurs.

**Comment by Moult** [comment]
I think this is related to the use of bfl.shadow. It's probably an upstream bug.

If you're OK with commenting out code, can you comment out all of these lines:

```
./bonsai/bim/module/model/decorator.py:        blf.enable(self.font_id, blf.SHADOW)
./bonsai/bim/module/model/decorator.py:        blf.shadow(self.font_id, 6, 0, 0, 0, 1)
./bonsai/bim/module/model/decorator.py:        blf.enable(self.font_id, blf.SHADOW)
./bonsai/bim/module/model/decorator.py:        blf.shadow(self.font_id, 6, 0, 0, 0, 1)
./bonsai/bim/module/drawing/decoration.py:        # blf.enable(font_id, blf.SHADOW)
./bonsai/bim/module/drawing/decoration.py:        # blf.shadow(font_id, 5, 0, 0, 0, 1)
./bonsai/bim/module/drawing/decoration.py:        # blf.shadow_offset(font_id, 1, -1)
./bonsai/bim/module/geometry/decorator.py:        blf.enable(font_id, blf.SHADOW)
./bonsai/bim/module/georeference/decorator.py:        blf.enable(self.font_id, blf.SHADOW)
./bonsai/bim/module/georeference/decorator.py:        blf.shadow(self.font_id, 6, 0, 0, 0, 1)
./bonsai/bim/module/spatial/decorator.py:        blf.enable(font_id, blf.SHADOW)
```

And see what happens?

**Comment by manuvarkey** [comment]
@Moult The issue was resolved after disabling the blf shadow setting after drawing the text. Pull request raised with this change.
https://github.com/IfcOpenShell/IfcOpenShell/pull/5421

**Comment by Moult** [comment]
Thank you so much! That makes complete sense. Can you also help change the drawing decoration shadow to be also blf.shadow(self.font_id, 6, 0, 0, 0, 1) to be consistent (with no offset) like all the rest of the text?
