### ISSUE TITLE
Weirdly rotated assemblies (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#539]
1. Convert [539--rotated-studs.ifc](https://github.com/IfcOpenShell/files/blob/master/539--rotated-studs.ifc) with 16cafb9
2. Experience that a lot of the studs are rotated by 90 degrees  (see especially the nearest side of the building):
<img width="350" alt="screenshot 2019-01-16 at 14 33 16" src="https://user-images.githubusercontent.com/4601554/51252791-fc4ce080-199c-11e9-94db-03a3ea626f36.png">
3. Open the same file in SimpleBIM, DDS or Solibri, and experience that the studs appear as expected:

<img src="https://user-images.githubusercontent.com/4601554/51253226-08856d80-199e-11e9-9680-c2c94a833b7c.png" width="350" alt="SimpleBIM">
<img src="https://user-images.githubusercontent.com/4601554/51253227-08856d80-199e-11e9-90ed-13eae576afa7.png" width="350" alt="DDS">
<img src="https://user-images.githubusercontent.com/4601554/51253228-08856d80-199e-11e9-80fb-775e136128b5.png" width="350" alt="Solibri">

Is there any plausible explanation for this? To me it seems like there are some objects that are being rotated as part of an assembly. There are some references to `IFCPLANEANGLEMEASURE(1.570796326794897)` in the model, but that seems to be more of an object property than something that should affect the geometry output?

**Comment by johanrd** [comment]
Adding a minimal reproducible file of one of the assemblies here: [539--rotated-studs--minimal-reproducible.ifc](https://github.com/IfcOpenShell/files/blob/master/539--rotated-studs--minimal-reproducible.ifc)

<img width="257" alt="screenshot 2019-01-17 at 09 53 48" src="https://user-images.githubusercontent.com/4601554/51306571-f0fdc180-1a3d-11e9-9444-d331bff83c69.png">

As there are no planeanglemeasures in the minimum reproducible file, I'm starting to suspect some hiccups in the interpretation of some of the defined ifcdirections, e.g. 
```
#8442=IFCDIRECTION((-1.,6.123233995736766E-17,0.));
#8536=IFCDIRECTION((0.,-1.,0.));
```

**Comment by aothms** [comment]
The issue is with this line in the minimal file.

~~~
#5531=IFCAXIS2PLACEMENT3D(#8535,#8536,$);
~~~

While the standard tells us:

> AxisAndRefDirProvision: Either both, Axis and RefDirection are not given and therefore defaulted, or both shall be given.

So the 3rd attribute cannot be null if the 2nd isn't.

So let's first wave our finger at this file for being invalid. I'm a bit surprised though that the other viewers all agree on the result. The only solution for a possible default value for `refDirection` (the X-axis) is to look at the express file, but that seems to initialize it to the (1 0 0), unless the `axis` attribute already equals that. The other viewers all seem to end up with (0 0 1).

Anyway, I just adapted the code to match what we're seeing in the other viewers, but I'm not very confident we're doing the right thing here.

~~~
FUNCTION IfcFirstProjAxis
	(ZAxis, Arg : IfcDirection)
	: IfcDirection;
  LOCAL
    XAxis : IfcDirection;
    V     : IfcDirection;
    Z     : IfcDirection;
    XVec  : IfcVector;
  END_LOCAL;
  
    IF (NOT EXISTS(ZAxis)) THEN
      RETURN (?) ;
    ELSE
      Z := IfcNormalise(ZAxis);
      IF NOT EXISTS(Arg) THEN
        IF (Z.DirectionRatios <> [1.0,0.0,0.0]) THEN
          V := IfcRepresentationItem() || IfcGeometricRepresentationItem () || IfcDirection([1.0,0.0,0.0]);
        ELSE
          V := IfcRepresentationItem() || IfcGeometricRepresentationItem () || IfcDirection([0.0,1.0,0.0]);
        END_IF;
      ELSE
        IF (Arg.Dim <> 3) THEN
          RETURN (?) ;
        END_IF;
        IF ((IfcCrossProduct(Arg,Z).Magnitude) = 0.0) THEN
          RETURN (?);
        ELSE
          V := IfcNormalise(Arg);
        END_IF;
      END_IF;
      XVec  := IfcScalarTimesVector(IfcDotProduct(V, Z), Z);
      XAxis := IfcVectorDifference(V, XVec).Orientation;
      XAxis := IfcNormalise(XAxis);
    END_IF;
    RETURN(XAxis);
END_FUNCTION;

FUNCTION IfcBuildAxes
	(Axis, RefDirection : IfcDirection)
	: LIST [3:3] OF IfcDirection;
  LOCAL
    D1, D2 : IfcDirection;
  END_LOCAL;
    D1 := NVL(IfcNormalise(Axis), IfcRepresentationItem() || IfcGeometricRepresentationItem () || IfcDirection([0.0,0.0,1.0]));
    D2 := IfcFirstProjAxis(D1, RefDirection);
    RETURN ([D2, IfcNormalise(IfcCrossProduct(D1,D2))\IfcVector.Orientation, D1]);
END_FUNCTION;
~~~

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)
