### ISSUE TITLE
Importing types with duplicate material names results in missing properties/styles

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#5391]
These two IFC files each contain a single Wall Type. The types have different names, but they both reference a material called 'Masonry'. Each of these two material definitions has Psets and a surface style:

[type-a.ifc.txt](https://github.com/user-attachments/files/17005661/type-a.ifc.txt)
[type-b.ifc.txt](https://github.com/user-attachments/files/17005672/type-b.ifc.txt)

If I create a new project and import both types then I end up with two materials: 'Masonry', and 'Masonry'. This is expected, I don't want materials to be automatically shared between two types just because the materials have the same names.

The bug is that the material from the second type is not imported with its Psets and surface style.

If I manually change the material name in one of the files, then all Psets and surface styles are imported as expected.

Somehow, the type import realises that there is already a material called 'Masonry' and then only does a partial material import.

Probably related: If I create a new project and import 'Masonry' from the first library, then try and import 'Masonry' from the second library, Bonsai seems to think it is already imported.

**Comment by brunopostle** [comment]
Note this bug appeared some time around the 0.8.0 switch. I thought it was a bug in the Homemaker add-on, but it looks like it is somewhere in `api.project.append_asset`

**Comment by Andrej730** [comment]
It's a bug that it appends duplicated IfcMaterial (I guess the same issue as #5446). 

Added an option to avoid reusing materials by name that resolves the current issue and second IfcMaterial also has a pset and a style.

**Comment by brunopostle** [comment]
Great, if I alt-click in bonsai when appending the types from each file, I get duplicate materials each with their own styles and psets, as expected:

![image](https://github.com/user-attachments/assets/b99c9ae5-91c5-4406-b562-fede9beb85ee)

Though I still see the original bug: if I append a wall type from each file in turn (without alt), I get duplicate materials but the material from the second file has no style or psets:

![image](https://github.com/user-attachments/assets/39aa205f-c1ed-47a5-8e54-f3702156490b)
