### ISSUE TITLE
Bonsai v0.8 - Error when printing SVG - sometimes does not select camera before printing

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#5395]
Windows 10 using these versions:
![image](https://github.com/user-attachments/assets/9884beb4-e22a-420d-bbe5-5bfb32c89754)

When printing drawings I am often editing in 2d camera preview and then printing the SVG to check the results
even when activating the drawing and printing to SVG it will sometimes still have the last edited object selected and then throw an error

I get this error:

Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 272, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 721, in generate_linework
    [cache.remove(guid) for guid in invalidated_guids]
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 721, in <listcomp>
    [cache.remove(guid) for guid in invalidated_guids]
     ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'remove'

This happens very frequently, to get it to print correctly you need to select the camera in the outliner, activate and reprint SVG and sometimes it takes a few trys.

This does not break the Ifc file to my knowledge but it does create lots of interruptions that feel like the file is breaking as printing is a fairly common activity. I probably run into this 15 - 20 times a work session

To get the error,
1) activate a drawing
2) In 2d preview add a wall and add a door and window to the wall
3) activate the drawing and print to SVG
it should give the same error

here is the Ifc to test:
[SVG print error - Copy.ifc.txt](https://github.com/user-attachments/files/17007414/SVG.print.error.-.Copy.ifc.txt)

**Comment by Moult** [comment]
I've definitely hit this bug before but had no idea how it could be triggered. It seems @Andrej730 has added some logging in the console to see what happens to the cache. I can't recreate it with your instructions. If you can recreate it, can you try with the latest build and see what the console says? https://github.com/IfcOpenShell/IfcOpenShell/commit/8bb78959ef65b2d60c691d5dbbe4032d7316cab9

**Comment by Plae-Blue-Dot** [comment]
It's reproducing pretty reliably for me, happy to check it, is the console logging the python console and only in the newer version of Bonsai?

**Comment by Plae-Blue-Dot** [comment]
Just the blender Info log my bad, here it is:

bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.bim.load_type_thumbnails(ifc_class="IfcBeamType", limit=9, offset=0)
bpy.ops.bim.load_project_elements()
bpy.ops.bim.load_project(filepath="C:\\Users\\user-pc\\OneDrive\\Work\\012 - Experiments\\038 - camera error test\\Camera error test.ifc", use_relative_path=False, should_start_fresh_session=True)
bpy.ops.bim.override_object_delete(is_batch=False)
bpy.ops.bim.set_tab(tab="DRAWINGS")
bpy.ops.transform.translate(value=(-0.0826435, -0.255443, 0), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=False, snap=True, snap_elements={'VERTEX', 'EDGE', 'FACE', 'EDGE_MIDPOINT', 'EDGE_PERPENDICULAR'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False, cursor_transform=True, release_confirm=True)
bpy.ops.bim.load_drawings()
bpy.context.scene.DocProperties.location_hint = '43'
bpy.ops.bim.add_drawing()
bpy.context.area.ui_type = 'CONSOLE'
bpy.ops.bim.expand_target_view(target_view="PLAN_VIEW")
bpy.context.scene.DocProperties.active_drawing_index = 2
bpy.ops.object.hide_view_set(unselected=False)
bpy.ops.object.hide_view_set(unselected=True)
bpy.ops.bim.update_representation(obj="IfcAnnotation/MY STOREY PLAN", ifc_representation_class="")
bpy.ops.bim.activate_drawing(drawing=1250)
bpy.ops.transform.translate(value=(-0.942946, -0.0304176, -0), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=False, snap=True, snap_elements={'VERTEX', 'EDGE', 'FACE', 'EDGE_MIDPOINT', 'EDGE_PERPENDICULAR'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False, cursor_transform=True, release_confirm=True)
bpy.ops.bim.add_constr_type_instance()
bpy.ops.bim.hotkey(hotkey="S_A", x=0.5, y=0.5, z=0.5)
bpy.ops.transform.translate(value=(0.14669, 0.0440069, 0), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=False, snap=True, snap_elements={'VERTEX', 'EDGE', 'FACE', 'EDGE_MIDPOINT', 'EDGE_PERPENDICULAR'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False, cursor_transform=True, release_confirm=True)
bpy.ops.bim.hotkey(hotkey="S_E", x=0.5, y=0.5, z=0.5)
bpy.ops.transform.translate(value=(-2.28836, 0.800317, 0.517082), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=False, snap=True, snap_elements={'VERTEX', 'EDGE', 'FACE', 'EDGE_MIDPOINT', 'EDGE_PERPENDICULAR'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False, cursor_transform=True, release_confirm=True)
bpy.ops.bim.assign_class(obj="Door", ifc_class="IfcDoor")
bpy.ops.bim.add_filled_opening(voided_obj="IfcWall/Wall.001", filling_obj="IfcDoor/Door")
bpy.ops.bim.add_constr_type_instance()
bpy.ops.bim.hotkey(hotkey="S_A", x=0.5, y=0.5, z=0.5)
bpy.ops.transform.translate(value=(0, 0.506937, -0.517082), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=False, snap=True, snap_elements={'VERTEX', 'EDGE', 'FACE', 'EDGE_MIDPOINT', 'EDGE_PERPENDICULAR'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False, cursor_transform=True, release_confirm=True)
bpy.ops.bim.assign_class(obj="Window", ifc_class="IfcWindow")
bpy.ops.bim.add_filled_opening(voided_obj="IfcWall/Wall.001", filling_obj="IfcWindow/Window")
bpy.ops.bim.add_constr_type_instance()
bpy.ops.bim.hotkey(hotkey="S_A", x=0.5, y=0.5, z=0.5)
bpy.ops.object.hide_view_set(unselected=False)
bpy.ops.object.hide_view_set(unselected=True)
bpy.ops.bim.activate_drawing(drawing=1250)
Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 272, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 721, in generate_linework
    [cache.remove(guid) for guid in invalidated_guids]
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 721, in <listcomp>
    [cache.remove(guid) for guid in invalidated_guids]
     ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'remove'

**Comment by Plae-Blue-Dot** [comment]
Here it is using the original versions this error was posted on

![image](https://github.com/user-attachments/assets/d52a9d12-a66c-4039-9bf0-543767760081)


bpy.ops.bim.override_object_delete()
bpy.context.scene.BIMProjectProperties.template_file = 'IFC4 Demo Template.ifc'
bpy.ops.bim.select_library_file(filepath="C:\\Users\\user-pc\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\.local\\lib\\python3.11\\site-packages\\bonsai\\bim\\data\\templates\\projects\\IFC4 Demo Template.ifc")
bpy.ops.bim.append_library_element(definition=953)
bpy.ops.bim.append_library_element(definition=956)
bpy.ops.bim.append_library_element(definition=959)
bpy.ops.bim.append_library_element(definition=962)
bpy.ops.bim.append_library_element(definition=965)
bpy.ops.bim.append_library_element(definition=968)
bpy.ops.bim.append_library_element(definition=971)
bpy.ops.bim.append_library_element(definition=974)
bpy.ops.bim.append_library_element(definition=977)
bpy.ops.bim.append_library_element(definition=980)
bpy.ops.bim.append_library_element(definition=1001)
bpy.ops.bim.append_library_element(definition=1022)
bpy.ops.bim.append_library_element(definition=1037)
bpy.ops.bim.append_library_element(definition=1064)
bpy.ops.bim.append_library_element(definition=1079)
bpy.ops.bim.append_library_element(definition=1094)
bpy.ops.bim.append_library_element(definition=87)
bpy.ops.bim.append_library_element(definition=92)
bpy.ops.bim.append_library_element(definition=72)
bpy.ops.bim.append_library_element(definition=77)
bpy.ops.bim.append_library_element(definition=82)
bpy.ops.bim.append_library_element(definition=38)
bpy.ops.bim.append_library_element(definition=42)
bpy.ops.bim.append_library_element(definition=48)
bpy.ops.bim.append_library_element(definition=153)
bpy.ops.bim.append_library_element(definition=59)
bpy.ops.bim.append_library_element(definition=54)
bpy.ops.bim.append_library_element(definition=63)
bpy.ops.bim.append_library_element(definition=67)
bpy.ops.bim.append_library_element(definition=21)
bpy.ops.bim.append_library_element(definition=26)
bpy.ops.bim.append_library_element(definition=30)
bpy.ops.bim.append_library_element(definition=34)
bpy.ops.bim.append_library_element(definition=96)
bpy.ops.bim.append_library_element(definition=210)
bpy.ops.bim.load_type_thumbnails(ifc_class="IfcBeamType", limit=9, offset=0)
bpy.ops.bim.create_project()
bpy.context.space_data.recent_folders_active = 2
IFC Project "Camera error test.ifc"  Saved
bpy.ops.bim.save_project(filepath="C:\\Users\\user-pc\\OneDrive\\Work\\012 - Experiments\\038 - camera error test\\Camera error test.ifc", should_save_as=True, save_as_invoked=True)
bpy.ops.bim.add_constr_type_instance()
bpy.ops.bim.hotkey(hotkey="S_A", x=0.5, y=0.5, z=0.5)
bpy.ops.bim.set_tab(tab="DRAWINGS")
bpy.ops.bim.load_drawings()
bpy.context.scene.DocProperties.location_hint = '43'
bpy.ops.bim.add_drawing()
bpy.ops.bim.expand_target_view(target_view="PLAN_VIEW")
bpy.context.scene.DocProperties.active_drawing_index = 2
bpy.ops.object.hide_view_set(unselected=False)
bpy.ops.object.hide_view_set(unselected=True)
bpy.ops.bim.update_representation(obj="IfcAnnotation/MY STOREY PLAN", ifc_representation_class="")
bpy.ops.bim.activate_drawing(drawing=1250)
bpy.data.cameras["15/1287"].BIMCameraProperties.height = 10.39
bpy.data.cameras["15/1287"].BIMCameraProperties.width = 10.39
bpy.ops.object.hide_view_set(unselected=False)
bpy.ops.object.hide_view_set(unselected=True)
bpy.ops.bim.update_representation(obj="IfcAnnotation/MY STOREY PLAN", ifc_representation_class="")
bpy.ops.bim.activate_drawing(drawing=1250)
bpy.ops.transform.translate(value=(-0.243407, 0.0695448, 0), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=False, snap=True, snap_elements={'VERTEX', 'EDGE', 'FACE', 'EDGE_MIDPOINT', 'EDGE_PERPENDICULAR'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False, cursor_transform=True, release_confirm=True)
bpy.ops.bim.add_constr_type_instance()
bpy.ops.bim.hotkey(hotkey="S_A", x=0.5, y=0.5, z=0.5)
bpy.ops.bim.hotkey(hotkey="S_E", x=0.5, y=0.5, z=0.5)
bpy.ops.transform.translate(value=(-0.346752, 0.231816, 0.614927), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=False, snap=True, snap_elements={'VERTEX', 'EDGE', 'FACE', 'EDGE_MIDPOINT', 'EDGE_PERPENDICULAR'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False, cursor_transform=True, release_confirm=True)
bpy.ops.bim.assign_class(obj="Door", ifc_class="IfcDoor")
bpy.ops.bim.add_filled_opening(voided_obj="IfcWall/Wall.001", filling_obj="IfcDoor/Door")
bpy.ops.bim.add_constr_type_instance()
bpy.ops.bim.hotkey(hotkey="S_A", x=0.5, y=0.5, z=0.5)
bpy.ops.transform.translate(value=(-0.359315, 0.173862, -0.614927), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', mirror=False, snap=True, snap_elements={'VERTEX', 'EDGE', 'FACE', 'EDGE_MIDPOINT', 'EDGE_PERPENDICULAR'}, use_snap_project=False, snap_target='CLOSEST', use_snap_self=True, use_snap_edit=True, use_snap_nonedit=True, use_snap_selectable=False, cursor_transform=True, release_confirm=True)
bpy.ops.bim.assign_class(obj="Window", ifc_class="IfcWindow")
bpy.ops.bim.add_filled_opening(voided_obj="IfcWall/Wall.001", filling_obj="IfcWindow/Window")
bpy.ops.bim.add_constr_type_instance()
bpy.ops.bim.hotkey(hotkey="S_A", x=0.5, y=0.5, z=0.5)
bpy.ops.object.hide_view_set(unselected=False)
bpy.ops.object.hide_view_set(unselected=True)
bpy.ops.bim.activate_drawing(drawing=1250)
Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 272, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 721, in generate_linework
    [cache.remove(guid) for guid in invalidated_guids]
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 721, in <listcomp>
    [cache.remove(guid) for guid in invalidated_guids]
     ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'remove'

**Comment by Plae-Blue-Dot** [comment]
For more detailed process from scratch:

1) Create Ifc project with Ifc4 demo library
2) save the Ifc
3) Add a plan drawing at My storey
4) activate the drawing
5) Print to SVG to test
6) In 2d preview add a wall, and add a door or window to the wall
7) with the last object still selected, press the activate drawing button and print to SVG button

it should give the same error

**Comment by Moult** [comment]
Nope, still can't recreate. I also don't see any messages in your output about the cache. Are you sure you're getting the messages from the system console? (e.g. Window > Toggle System Console on Windows) because not all messages will show up in the Blender "Info" panel.

You can also edit `bonsai/bim/ifc.py` and change these lines:

```python
    @staticmethod
    def get_cache():
        if IfcStore.cache is None and IfcStore.path:
```

... to this which adds another print statement so we can see what the state is:

```python
    @staticmethod
    def get_cache():
        print('getting cache', IfcStore.cache, 'and', IfcStore.path)
        if IfcStore.cache is None and IfcStore.path:
```

**Comment by theoryshaw** [comment]
Just wanted to confirm--i can replicate.


https://github.com/user-attachments/assets/a6adee7b-779d-42f9-951d-20d43f0445a1

**Comment by theoryshaw** [comment]
with code snippet...

https://github.com/user-attachments/assets/cf1d9f34-cb80-4c3b-a450-1bccd7a18cdf
