### ISSUE TITLE
bonsai fatal error

### ISSUE THREAD

**Issue by Sebionz** [IfcOpenShell/IfcOpenShell#5396]
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
blender_version: 4.2.0
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\SEBI\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\__init__.py", line 81, in <module>
    from . import ifcopenshell_wrapper
ImportError: cannot import name 'ifcopenshell_wrapper' from partially initialized module 'ifcopenshell' (most likely due to a circular import) (C:\Users\SEBI\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SEBI\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\bonsai\__init__.py", line 225, in <module>
    import ifcopenshell.api
  File "C:\Users\SEBI\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\__init__.py", line 83, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'windows\64bit\python3.11'

binary_file_name: _ifcopenshell_wrapper.cp311-win_amd64.pyd
binary_python_version: 3.11

**Comment by Andrej730** [comment]
Hi! Can you please open system console (Window - Toggle System Console) and copy here the entire output? There might be some other related errors leading to this.

**Comment by Moult** [comment]
Please also follow the instructions here https://docs.bonsaibim.org/quickstart/installation.html with a fresh install of Blender 4.2.

**Comment by Andrej730** [comment]
@Sebionz closing this for now, please reopen if there will be any additional information.
