### ISSUE TITLE
Parametric types are shown on non-applicable entities in the type manager

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5398]
Re #5397
I think when creating a type using the type manager, the template dropdown should only show parametric types that are applicable. eg only window for IfcWindowType, railing for IfcRailingType, etc.

![image](https://github.com/user-attachments/assets/8624211b-56e3-4bd2-8b5f-6e2a707da2d7)

I would gladly offer to try and fix it but I have yet to be able to sucessfully run a dev environment for bonsai extension in Blender 4.2 so I won't be able to atm.

Cheers

**Comment by Moult** [comment]
> I have yet to be able to sucessfully run a dev environment for bonsai extension

Anything we can help with? :) Error messages? Batch / shell scripts that don't work?

**Comment by Moult** [comment]
@Gorgious56 I'm curious is the VS Code extension works with Bonsai - because we do a dirty little trick where we bundle the add-on itself as ... a wheel :)

**Comment by Gorgious56** [comment]
@Moult  Hehe, righto, I didn't expect it to work out of the box :) So typing the previous message made me want to make it work. So this is indeed dirty, and mildly annoying. We're derailing the subject of this issue but here's how I did it :

- Install and Activate the unstable release of bonsai extension using https://docs.bonsaibim.org/guides/development/installation.html#unstable-installation (because https://github.com/IfcOpenShell/IfcOpenShell/releases/ no longer ships with the python modules)
- Copy / paste the modules from `...AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages` to `...Blender\4.2\python\lib\site-packages`
- Delete the bonsai directory from `...Blender\4.2\python\lib\site-packages`
- Create a simlink between my local repo of ifcopenshell `...\dev\ifcopenshell\src\bonsai\bonsai` to `...Blender\4.2\python\lib\site-packages\bonsai`
- De-activate the unstable release of bonsai extension, which deletes everything from `..AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages`
- Quit Blender
- Launch VS code extension from `...\ifcopenshell\src\bonsai\bonsai` 
- ... profit ?

I didn't manage to make it dynamically reload with VS code so I have to quit & restart Blender everytime I make a change. So in the end I'm not really making use of the VS code extension, rather only using VS code for the debugging capabilities. Annoying :) If there's a easier way to make it work for a non linux-savvy dirty windows user I might take it ><

**Comment by Moult** [comment]
Fantastic! I'm sure it'll help someone :) Now you can join the never ending bug squashing session!

**Comment by theoryshaw** [comment]
Dumb question, why not use the .bat file to create your symlinks? 
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/bonsai/scripts/installation/dev_environment.bat

It seems the [Live development environment](https://docs.bonsaibim.org/guides/development/installation.html#live-development-environment) needs to point to these .bat files... it used to. 

...

Also might be worth reading [this](https://community.osarch.org/discussion/comment/17160)thread, if you haven't already, there's some tricky tricks to not have to restart blender.

**Comment by Gorgious56** [comment]
Well that's not dumb at all, the reason I guess is because I didn't know it existed :p
