### ISSUE TITLE
[Error] Expected a single IfcProject?

### ISSUE THREAD

**Issue by Febfire** [IfcOpenShell/IfcOpenShell#540]
I convert ifc to xml using IfcConvert,got an error : [Error] Expected a single IfcProject.
what this mean?
this is my ifc file.
[SampleHouse.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/2794526/SampleHouse.zip)

**Comment by Febfire** [comment]
hi aothms,sorry for my late reply.
the version of binary is ifcopenshell 0.6.

**Comment by aothms** [comment]
Yes thanks for reporting. There was in issue with registering the correct code based on schema version. Fixed now in latest version of the code. New builds will be provided within a couple of days.
