### ISSUE TITLE
Is there a way to prevent committing to ifcgit changing the object colors ?

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5402]
The visual representation of new / modified / deleted items using ifcgit is great. (white / green / red)
However the tool destructively changes object colors which may be used to communicate other things in other workflows, and right now it looks like there is no way to opt out of it. It also destructively changes the object color transparency and changes the viewport overlay to *Object Color* which may not be intended by the user when committing.

I think an option maybe in the preferences to not automatically change the object colors and viewport overlays when committing to ifcgit would be great.

There are specific buttons to display the changes the user can click on if they want to see the information.

@brunopostle I think.

Cheers

**Comment by brunopostle** [comment]
Yes, committing shouldn't switch between Object and Material color. Only the display_revision() operator probably should do this sort of thing.

I don't think anything other than display_revision() sets object colours, so any user set colours should survive a commit?

Also note that various IfcGit operations, such as switch_revision() and merge() do a full ifc import, so any object colours and transparency set by the user are going to vanish here anyway.
