### ISSUE TITLE
bpy.ops.bim.load_project : use_relative_path is not working

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5407]
When trying to load a project with a relative path, it doesn't seem to work. Thus running         
`bpy.ops.bim.load_project("EXEC_DEFAULT", should_start_fresh_session=False, filepath=relative_path, use_relative_path=True)` silently fails

https://github.com/IfcOpenShell/IfcOpenShell/blob/53a619285845df6a1f2ddfa48ec99ff65091cdd3/src/bonsai/bonsai/bim/module/project/operator.py#L653

EDIT : edited initial issue because it does look like it is implemented but it failed on my file. https://github.com/IfcOpenShell/IfcOpenShell/blob/53a619285845df6a1f2ddfa48ec99ff65091cdd3/src/bonsai/bonsai/bim/ui.py#L52-L58

Re-EDIT : Maybe because it misses some forward-slashing replacements ? I use windows which is infamous for these. See how it's done there https://github.com/IfcOpenShell/IfcOpenShell/blob/53a619285845df6a1f2ddfa48ec99ff65091cdd3/src/bonsai/bonsai/bim/module/project/operator.py#L952

**Comment by Andrej730** [comment]
Should be fixed. Note that `use_relative_path` is a bit different thing, it's a flag for storing ifc filepath as relative. But loading project using relative path should work even with `use_relative_path == False`.
![image](https://github.com/user-attachments/assets/8ad4763c-c585-419d-9b48-ebc043abd517)
