### ISSUE TITLE
Rotating a wall of a fraction of a degree doesn't register on file save

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5408]
I have FINALLY pinpointed this. This has been *no pun intended* bugging me for months.

Wall rotations for values < 0.5° are not registered on ifc save. Ths is extremely wicked because the blend file and ifc file then immediately become desynchronized, which may lead to further bugs down the line.

Steps to reproduce :

Brand new file
Add a new wall type
Add a new wall occurrence
Save IFC
Rotate wall by 0.4° around Z
Save IFC
Load IFC in a new blend file
The wall rotation is back to 0°

Current workaround : add a bigger rotation to the wall, save ifc file, then subtract this rotation and add the original wanted small rotation, save ifc file.

**Comment by Moult** [comment]
> **Me:** Ah nobody will be rotating their models by a fraction of a degree anyway, our matrix sync is fine.
> **Gorgious56**: Hold my beer

**Comment by Gorgious56** [comment]
Haha I can't be the only one working with real life measurements that need to be adjusted to the millimeter ><

If that's really a limit of the engine I don't really mind TBH, but user should be either prevented to rotate with very small values or a warning should be issued when it happens :)
