### ISSUE TITLE
IfcConvert outputs "Killed"

### ISSUE THREAD

**Issue by swalter88** [IfcOpenShell/IfcOpenShell#541]
Hey,

i just want to convert an IFC file with IfcConvert to an XML file... These are the output lines:
IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 7.3.0)
Scanning file...
Done scanning file   
Writing XML output...
Killed

What does that "killed" mean? What can i do? Thx!

**Comment by aothms** [comment]
This is probably the Linux kernel killing the process because it's taking too much memory. Is it a big file?

**Comment by swalter88** [comment]
Input file is about 200mb. In MacOS the conversion was successfull. Output file is about 240mb. Is there something i can do say Linux not to kill the process?

**Comment by aothms** [comment]
Maybe this helps https://serverfault.com/questions/141988/avoid-linux-out-of-memory-application-teardown
