### ISSUE TITLE
IfcSolidStratum not supported in IFC4X3 and IFC4X3_ADD2 ?

### ISSUE THREAD

**Issue by legnad** [IfcOpenShell/IfcOpenShell#5414]
When trying to open a IFC file with `IfcSolidStratum `entities in it, these entities are missing from the file.

When trying to create arbitrary entities with
```
ifc.create_entity('IfcGeotechnicalStratum')
ifc.create_entity('IfcSolidStratum')
```

And exception is raised at the 2nd line only:

`RuntimeError: Entity with name 'IfcSolidStratum' not found in schema 'IFC4X3'`

No difference when using IFC4X2_ADD2:

`RuntimeError: Entity with name 'IfcSolidStratum' not found in schema 'IFC4X3_ADD2'`

Note how `IfcGeotechnicalStratum` seems to be ok.

As of my understanding of the [documentation of Class Ifc4x3_rc1::IfcGeotechnicalStratum](https://ifcopenshell.github.io/docs/rst_files/class_ifc4x3__rc1_1_1_ifc_geotechnical_stratum.html) both `IfcGeotechnicalStratum` and `IfcSolidStratum` should be supported, right?

**_IfcOpenShell 0.8.0 installed via `pip` on Python 3.12 (Windows 11)._**

**Comment by Andrej730** [comment]
> As of my understanding of the [documentation of Class Ifc4x3_rc1::IfcGeotechnicalStratum](https://ifcopenshell.github.io/docs/rst_files/class_ifc4x3__rc1_1_1_ifc_geotechnical_stratum.html) both `IfcGeotechnicalStratum` and `IfcSolidStratum` should be supported, right?

@legnad 
Ifc4x3_rc1 is a release candidate version, it's not the final accepted ifc4x3 schema - not all changes are making to the final version. You should refer to official ifc releases from https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/.
ifc4x3 release is indeed missing IfcSolidStratum - see https://[standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/IFC4X3_ADD2.exp

**Comment by legnad** [comment]
Thank you very much.

**Comment by aothms** [comment]
IfGeotechnicalStratum did make it back in the IFC4.4 proposal from the infra room:

https://github.com/bSI-InfraRoom/IFC-Specification/actions/runs/10113298286

with `SOLID` as a predefined type.

While this is not  an official bSI standard yet, it could be something to keep an eye on.

**Comment by Moult** [comment]
IfcGeotechnicalStratum and SOLID is part of the official IFC4X3(_ADD2) standard. I've used it recently.

It's probably worth mentioning that it seems as though stratum are typically used within a IfcGeotechnicalAssembly (e.g. bore hole).

**Comment by aothms** [comment]
> IfcGeotechnicalStratum and SOLID is part of the official IFC4X3(_ADD2) standard. I've used it recently.

Derp 🥴

Thanks for the correction
