### ISSUE TITLE
BlenderBIM - IFC 4x3 Alignment - Clothoid problem

### ISSUE THREAD

**Issue by Pourfex** [IfcOpenShell/IfcOpenShell#5418]
Hello ! 

We've been doing experiments with IFC 4x3 files into BlenderBim, congrats for the geometry that is really good.
The alignements however are quite messy, mainly when there is a IFCAlignmentHorizontal that contains a Clothoid.

See on those files : 
[IFC_Clothoid.zip](https://github.com/user-attachments/files/17055527/IFC_Clothoid.zip)
![Formation_Plateforme_BlenderBim](https://github.com/user-attachments/assets/03a9f0fa-dc5f-440a-90a9-e3fedc7c2118)

![Route_43_BlenderBim](https://github.com/user-attachments/assets/fbe4a57d-d3e9-4e03-a73f-e4236bffa4f8)

I would think that geometry for alignment is not well done for clothoid. Thanks again

**Comment by Pourfex** [comment]
For info : 

For Route43.ifc in USBIM
![Route_43_usBIM](https://github.com/user-attachments/assets/eb4719f7-e79b-4083-80d4-2140cf93af81)

and in ifcviewer from RDF.bg
![Route_43_ifcviewer](https://github.com/user-attachments/assets/1669badd-1617-4e8b-ab8f-e8703e06d8cd)

**Comment by RickBrice** [comment]
Thanks for the report. I'll take a look at it.
Running the Route43.ifc file through the validation service, there are lots of errors.
I'll see what I can do to make the geometry code a bit more resilient

**Comment by RickBrice** [comment]
Based on the official IFC 4x3 ADD 2 schema definition, I think IfcOpenShell has the geometry of [8.9.3.19 IfcClothoid](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcClothoid.htm) implemented correctly.

Specifically, u is a parameter value and s is an arc length
![image](https://github.com/user-attachments/assets/87cec1fa-6c78-4bd2-96eb-631609a8d1bd)

From the Route43.ifc file the two "incorrect" looking curve segments are, 
~~~
#131= IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE.,#132,IFCPARAMETERVALUE(-30.),IFCNONNEGATIVELENGTHMEASURE(30.),#135);
#135= IFCCLOTHOID(#136,94.868329805051374);

#191= IFCCURVESEGMENT(.CONTSAMEGRADIENTSAMECURVATURE.,#192,IFCPARAMETERVALUE(-50.),IFCNONNEGATIVELENGTHMEASURE(50.),#195);
#195= IFCCLOTHOID(#196,-122.47448713915891);
~~~

Considering `#131 IfcCurveSegment`, the start of the curve is at a parameter value of -30.

The length of the curve from the origin to the start point is then $s = Au\sqrt\pi = (94.868)(-30.0)\sqrt\pi = -5044.47$

The curve segment progresses from that point forward by 30 units. 

At -5044.47 from the origin is where the spiral is looping back around itself rapidly. This is why the curve segment looks like a corkscrew.

If the intent is to start the spiral at -30 units from the origin, the correct parameter value should be $-30 = (94.868)u\sqrt\pi$ so $u = -0.1784$

Based on your screenshot, clearly other implementers are not interpreting the parameterization of a clothoid in the same way.

I will post to the buildingSmart Implementers Forum asking if the documentation is correct.

**Comment by RickBrice** [comment]
@Pourfex the problems seem to be with your file. Please see discussion at https://github.com/buildingSMART/IFC4.x-IF/issues/165. usBIM and RDF use the same geometry engine, and the developer is suggesting it will be changed to handle clothoid parameters correctly in a future release. Currently the RDF engine is using a threshold value of 7 to interpret IfcParameterValue as either a true parameter or as a length measure.

I recommend you change all the IfcParameterValue to IfcLengthMeasure based on Informal Proposition 1 for [8.9.3.28 IfcCurveSegment](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcCurveSegment.htm). Be careful with the curve segments that use IfcCircle as the parent curve, simply replacing IfcParameterValue with IfcLengthMeasure wont do the trick, the length measure is Parameter*Radius. It's probably also a good idea to run your files through the bSI validation service.

@aothms Do you have any thoughts or concerns about leaving IfcOpenShell as is for IfcClothoid?

**Comment by aothms** [comment]
@RickBrice yes I wouldn't introduce wrong behaviour in the code based on old sample models. You already see the confusion this caused on our end when comparing to the implementation of RDF engine. If this really remains an issue that hinders adoption of ifcopenshell or ifc4.3 in the future we can introduce a setting like `--clothoid-parameter-threshold=7`.

**Comment by Moult** [comment]
Closing as this is invalid data.

**Comment by Pourfex** [comment]
Thanks @aothms and @Moult we've the same feedback from OpenDesignAlliance forum members. We'll try to push forward on our design software (Covadis/Mensura to handle them correctly). Have a nice day.
