### ISSUE TITLE
Feature Request: BlenderBim to Bonsai migration guide for a clean setup

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#5422]
Hello,

I'm trying to keep myself up to date and I noticed the recent changes about the renaming of the former BlenderBIM add-on to **[Bonsai](https://bonsaibim.org/)**.

First of all, thanks for having shared [the history and the steps which conducted to those changes](https://github.com/IfcOpenShell/IfcOpenShell/issues/772) with the community, this is really nice in a world were transparency is more than ever needed. And congratulations about the integration as a true Blender add-on 🚀🥳 ! Also good luck for changing the name everywhere... especially inside screenshots and images (e.g. here https://docs.bonsaibim.org/guides/development/hello_world.html or throughout the IFCOpenShell website).

By the way, I recently updated Blender to `4.2.1` and discovered that the BlenderBIM add-on I had installed a few months ago was no longer activated. Worse still, it wasn't listed in the “Blender Preferences > Add-ons” tab, even though the add-on files are still present on disk:
```
/home/<username>/.config/blender/4.1/scripts/addons/blenderbim
/home/<username>/.config/blender/4.1/scripts/addons/blenderbim/libs/desktop/blenderbim.xml
/home/<username>/.config/blender/4.1/scripts/addons/blenderbim/libs/desktop/blenderbim.desktop
/home/<username>/.config/blender/4.1/scripts/addons/blenderbim/libs/desktop/blenderbim.png
/home/<username>/.config/blender/4.1/scripts/addons/blenderbim/libs/desktop/blenderbim
```
In order to correctly remove this BlenderBIM add-on, I first tried to "re-install" it properly using the file I downloaded some months ago: `blenderbim-240501-py311-linux.zip`.
I was able to reinstall it but I noticed that the file was installed in a slightly different folder structure:
```
/home/<username>/.config/blender/4.2/extensions/user_default/blenderbim
/home/<username>/.config/blender/4.2/extensions/user_default/blenderbim/libs/desktop/blenderbim.xml
/home/<username>/.config/blender/4.2/extensions/user_default/blenderbim/libs/desktop/blenderbim.desktop
/home/<username>/.config/blender/4.2/extensions/user_default/blenderbim/libs/desktop/blenderbim.png
/home/<username>/.config/blender/4.2/extensions/user_default/blenderbim/libs/desktop/blenderbim
```
In addition, it is no longer possible to activate it by checking the box:

![image](https://github.com/user-attachments/assets/8209011d-2a5b-485d-a62d-5d1c6913f68d)

I'm now wondering if it wouldn't be enough to simply delete the files listed above? Or do I need to take some other action?

In order to have a clean Bonsai installation, publishing somewhere a kind of official “migration guide” for people in the same situation would be a great help.

Thanks for your kind help and the amazing work done around Bonsai and IfcOpenShell!

Warm Regards.

**Comment by Andrej730** [comment]
@swiss-knight 

Old versions do not support Blender 4.2, use the latest releases. See https://docs.bonsaibim.org/quickstart/installation.html

Folders you can remove to make sure nothing will get in the way:
1) addons/blenderbim addons/bonsai
2) extensions/user_default/blenderbim extensions/user_default/bonsai
3) Preferably extensions\.local\lib\python3.11\site-packages but you may need to restart some other extensions after this (disable and enable), if you have any other extensions installed that have dependencies in this folder.

**Comment by Moult** [comment]
Not just for Bonsai, but for all add-ons, the safest way to migrate is to start with a fresh 4.2 installation. All locations of where Bonsai exists are documented here: https://docs.bonsaibim.org/guides/troubleshooting.html#where-is-the-add-on-installed
