### ISSUE TITLE
Live development environment

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#5429]
The script files in the live development environment are no longer in the documentation. https://docs.bonsaibim.org/guides/development/installation.html

My guess is that they are no longer applicable with the new Blender 4.2 extensions

So my question is, now do I set up a live development environment now? More specifically, I'm working on the C++ side for the recent alignment issue (#5418). After I compile I need to copy the new ifcopenshell_wrapper.pyd file somewhere. I can't find it in the Bonsai installation folders.

What do I need to do?

**Comment by Moult** [comment]
Sorry the scripts we incorrectly embedded in the docs and this has been fixed:

https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.8.0/src/bonsai/scripts/installation
