### ISSUE TITLE
Bonsai - Staircase Pset replaced modifier issues

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#5432]
With the Stair dumb modifier essentially moved into the Stair Pset, there are a number of things that are not clear or perhaps don't work? 

![image](https://github.com/user-attachments/assets/9c8461a8-971e-4612-8e35-897d5af6b915)

Issue 1:

Updating Stair Pset does not change the geometry

Issue 2:
There does not seem to be a value to adjust the stair width or height

Issue 3:
There is no longer an option to change the stair profile shapes (previously: concrete, timber & standard)

Please see an attached Ifc file to test:
[Bonsai stair test - Copy.ifc.txt](https://github.com/user-attachments/files/17073627/Bonsai.stair.test.-.Copy.ifc.txt)

My assumption is that the stair modifier has been moved into the Pset but I might be just wrong, If I am please let me know where we can adjust these elements.

Previously it made sense tat this was in with parametric geometry, I don't mind it being part of the Pset but this way of interacting and adjusting stairs seems less intuitive and less responsive at the moment

**Comment by theoryshaw** [comment]
It's located in the following.   I do agree, however, that intuitively it would be nice if one value drove the other. 

https://github.com/user-attachments/assets/b4275dd3-c3a8-4b76-8623-65052615040d

**Comment by Plae-Blue-Dot** [comment]
Oh my bad I've used the IfcStair Type instead of the Stair flight type

It seems the IfcStair type does not have the modifier
IfcStair Type:
![image](https://github.com/user-attachments/assets/547f6c36-eb72-4ee5-86f2-c9b7785c1227)

IfcStairflight type:
![image](https://github.com/user-attachments/assets/12607552-7535-47a8-b048-ff351cdb8151)

I read this comment on the updates and thought the modifier wasn't there anymore:
"Deprecate old dumb stair tool and pie menu"

[Stair vs Stairflight - Copy.ifc.txt](https://github.com/user-attachments/files/17075560/Stair.vs.Stairflight.-.Copy.ifc.txt)

But yes it would be great if this info passed 2 ways hhaha from the pset to the modifier

**Comment by Gorgious56** [comment]
My interpretation of [the docs](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/schema/ifcsharedbldgelements/lexical/ifcstair.htm) is that IfcStairs should be able to use the parametric stair modifier ?

```
 The IfcStair shall either be represented:

    as a stair assembly entity that aggregates all parts (stair flight, landing, etc. with own representations), or
    as a single stair entity without decomposition including all representation directly at the stair entity.

```
