### ISSUE TITLE
Why does my .ifc file does't load?

### ISSUE THREAD

**Issue by leonstrr** [IfcOpenShell/IfcOpenShell#5442]
Hey friends,

I'm relatively new in programming and new to GitHub. For my master thesis I am doing research in BIM and so I am using ifc format. 
I wanted to create the .ifc file for an IfcFacetedBrep from the official documentation (see https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcFacetedBrep.htm). 

1. However, my file doesnt seem to work. I have the guess, that my faces are defined wrong maybe. the front and back faces have a whole (void face), which i defined as IfcFaceBound and then as an IfcFace. I defined the 4 inner faces (the ones that "form" the whole inside the body) as IfcFaceOuterBound. For me that seems more logic than to define them as void faces?
2. And can u tell me what ifc classes i have to assign minimally to create a working ifc file? I put some i found in another file to make it running.
3. Do you have a (free) software where I can choose the geometric representation? I don't know how (and even if) it's possible in blender bonsai.
4. Is there a tool where I can "scan" ifc files for errors or something?

I hope I receive an answer, looking forward hearing from u <3 

xoxo

PS: Hello world :)

[faceted_brep_test.txt](https://github.com/user-attachments/files/17089026/faceted_brep_test.txt)

**Comment by leonstrr** [comment]
One more question haha:
Is there an output from the console in bonsai python? i found where I can paste my python code, however there is no console output? 
thanks

**Comment by aothms** [comment]
There's quite some mistakes that are easy to resolve. The other points i'll leave to the people more familiar with Bonsai.

Try https://validate.buildingsmart.org

- Use uppercase entity names
- `//` is not a valid comment. Use `/* ... */`

**Comment by Moult** [comment]
It looks like you're writing the file by hand. This is great for learning but will probably cause quite a bit of grief over small formatting mistakes :)

1. For creating a "mesh" (prioritises tessellations, will fallback to faceted breps in IFC2X3) IfcOpenShell has the `add_mesh_representation` API: https://docs.ifcopenshell.org/ifcopenshell-python/geometry_creation.html#mesh-representations - however more recently (especially if grabbing IfcOpenShell from Git) I'd recommend using the shape builder which is more granular and offers quite a bit of control: https://docs.ifcopenshell.org/ifcopenshell-python/geometry_creation.html#custom-representations - for example this is all the code required to turn a Blender mesh object into either a faceted brep or meshlike (priortises tessellations):

```python
                builder = ifcopenshell.util.shape_builder.ShapeBuilder(tool.Ifc.get())
                unit_scale = ifcopenshell.util.unit.calculate_unit_scale(tool.Ifc.get())
                verts = [v.co / unit_scale for v in obj.data.vertices]
                faces = [p.vertices[:] for p in obj.data.polygons]
                if item.is_a("IfcAdvancedBrep"):
                    new_item = builder.faceted_brep(verts, faces)
                else:
                    new_item = builder.mesh(verts, faces)
```

2. Minimally? Completely minimally I think technically you only need an IfcProject and that's it. It's not very useful though :) This is a more practical example: https://docs.ifcopenshell.org/ifcopenshell-python/code_examples.html#create-a-simple-model-from-scratch

3. Bonsai now has support for editing and adding representation items granularly. Not all items can be edited, but swept solids and meshy things can. Non-supported items can be cast into meshy things if necessary.

4. As mentioned the validate website, or you can use it offline in the debug panel in Bonsai.

5. Window menu > Toggle system console

**Comment by leonstrr** [comment]
Hey Guys,

thanks so so much for your help. You help me so much <3!
I will check this all out now. And I feel a extra blessed the big @Moult answered me. I saw a few posts from you and you and the other guys are like my IFC idols hahaha. Thanks a lot again also @aothms ofc <3

**Comment by leonstrr** [comment]
Hey guys, thanks again. I managed to bring it to the stage that it looks fine in x-ray. however when i toggle it, the whole in my block "disappears". my first thought was that it could be because of the IfcClosedShell but i guess that's not right. Do you have an idea?
![image](https://github.com/user-attachments/assets/20cb7898-eb62-427d-ae9e-8e16ca8cbf50) -> object mode
![image](https://github.com/user-attachments/assets/addda098-06ae-4bbc-9654-d9fe0e024922) -> edit mode
![image](https://github.com/user-attachments/assets/ca49fcc7-51f1-469e-b680-a837d11a95a6) -> x-ray toggled

**Comment by Moult** [comment]
Can you share your model?

**Comment by leonstrr** [comment]
Oh sure, thanks Moult!

[faceted_brep_test_v.0.1.txt](https://github.com/user-attachments/files/17094448/faceted_brep_test_v.0.1.txt)

**Comment by Moult** [comment]
Sorry for the delay. There isn't an IfcOpenShell bug here, it's legitimately how you've defined your shape. You can see for yourself by doing:

```python
import ifcopenshell
import pprint
f = ifcopenshell.open('/home/dion/tmp/loadbug/faceted_brep_test_v.0.1.ifc')
e = f.by_id(42)
pprint.pprint(e.get_info(recursive=True))
```

I trimmed the output a bit but you can see your result here. You'll notice you have only rectangular outer bound faces. If you want a hole, you need to either 1) adjust your faces such that they stop short of the hole and design a new polyhedron for that, or 2) add a new inner boundary in the face with a rectangular shape for that hole.

```
{'CfsFaces': ({'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (0.0, 0.0, 0.0),
                                                 {'Coordinates': (1000.0, 0.0, 0.0),
                                                 {'Coordinates': (1000.0, 1000.0, 0.0),
                                                 {'Coordinates': (0.0, 1000.0, 0.0),
              {'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (0.0, 0.0, 2000.0),
                                                 {'Coordinates': (1000.0, 0.0, 2000.0),
                                                 {'Coordinates': (1000.0, 1000.0, 2000.0),
                                                 {'Coordinates': (0.0, 1000.0, 2000.0),
              {'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (0.0, 0.0, 0.0),
                                                 {'Coordinates': (1000.0, 0.0, 0.0),
                                                 {'Coordinates': (1000.0, 0.0, 2000.0),
                                                 {'Coordinates': (0.0, 0.0, 2000.0),
              {'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (1000.0, 0.0, 0.0),
                                                 {'Coordinates': (1000.0, 1000.0, 0.0),
                                                 {'Coordinates': (1000.0, 1000.0, 2000.0),
                                                 {'Coordinates': (1000.0, 0.0, 2000.0),
              {'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (1000.0, 1000.0, 0.0),
                                                 {'Coordinates': (0.0, 1000.0, 0.0),
                                                 {'Coordinates': (0.0, 1000.0, 2000.0),
                                                 {'Coordinates': (1000.0, 1000.0, 2000.0),
              {'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (0.0, 1000.0, 0.0),
                                                 {'Coordinates': (0.0, 0.0, 0.0),
                                                 {'Coordinates': (0.0, 0.0, 2000.0),
                                                 {'Coordinates': (0.0, 1000.0, 2000.0),
              {'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (250.0, 0.0, 750.0),
                                                 {'Coordinates': (750.0, 0.0, 750.0),
                                                 {'Coordinates': (750.0, 1000.0, 750.0),
                                                 {'Coordinates': (250.0, 1000.0, 750.0),
              {'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (750.0, 0.0, 750.0),
                                                 {'Coordinates': (750.0, 1000.0, 750.0),
                                                 {'Coordinates': (750.0, 1000.0, 1250.0),
                                                 {'Coordinates': (750.0, 0.0, 1250.0),
              {'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (750.0, 1000.0, 1250.0),
                                                 {'Coordinates': (250.0, 1000.0, 1250.0),
                                                 {'Coordinates': (250.0, 0.0, 1250.0),
                                                 {'Coordinates': (750.0, 0.0, 1250.0),
              {'Bounds': ({'Bound': {'Polygon': ({'Coordinates': (250.0, 1000.0, 750.0),
                                                 {'Coordinates': (250.0, 0.0, 750.0),
                                                 {'Coordinates': (250.0, 0.0, 1250.0),
                                                 {'Coordinates': (250.0, 1000.0, 1250.0),
```
