### ISSUE TITLE
v0.8 open vs v0.7 open is much (~5x) slower

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5444]
LA.ifc is 85MB. This is the code I'm running:

```python
import time
import ifcopenshell
f = '/home/dion/drive/LA/LA.ifc'
s = time.time()
m = ifcopenshell.open(f)
print(time.time()-s)
```

In v0.7.0 this takes 2.45 seconds.

In v0.8.0 this takes 13.21 seconds.

For another file, 323MB, v0.7.0 takes 10.8 seconds whereas 0.8.0 takes 65.9 seconds.

Anything else I can do to debug? Interestingly it doesn't occur on all files. For example I have a 112MB file where both v0.7.0 and v0.8.0 take ~3.4 seconds.

Tested with both 0.8.1-e0095cd44 and 0.7.11-fea8e3a5c

**Comment by aothms** [comment]
It would be interesting for me to know the ratio rooted/nonrooted instances. v0.7 parsed lazily and skipped over all non-rooted instances. v0.8 just reads everything and then closes the file. The reason for this is that I'm getting ready for no-gil python and then you don't want this granular locking going on. Also, especially access to aggregates of instances will already be faster in return. If you can share one of these models where 0.8 is so dramatically slower would be great though. You know how to reach me if it's private.

**Comment by Moult** [comment]
Sent to models@ifcopenshell.org

Ratio:

```
>>> len(list(f))
1452605
>>> len(f.by_type('IfcRoot'))
1362
```

**Comment by aothms** [comment]
Ok. I guess I officially don't know what I'm doing anymore.

I would have assumed my commit above would compile to the same code, but apparently it's 10x faster (on my local dev setup, let's see how this holds up in the bot builds).

Would be interesting to do some sort of non-trivial benchmark after this. So not only ifcopenshell.open() but something like below to also actually retrieve some data.

```
f = ifcopenshell.open(...)
sum(np.array(inst.Coordinates).sum() in f.by_type('IfcCartesianPoint')
```

**Comment by Moult** [comment]
Awesome! On all counts 0.8 open and data retrieval is faster. Hooray! Closing bug :)

```python
import time
import ifcopenshell
import numpy as np
f = '/home/dion/LA-85mb.ifc'
#f = '112mb.ifc'
#f = '323mb.ifc'
s = time.time()
m = ifcopenshell.open(f)
print(time.time()-s)
a = sum(np.array(inst.Coordinates).sum() for inst in m.by_type('IfcCartesianPoint'))
print(a)
print(time.time()-s)
```

Filesize | 0.7 Open | 0.8 Open | 0.7 Get Data | 0.8 Get Data
--- | --- | --- | --- | ---
85mb | 2.8 | 2.35 | 2.7 | 1.87
112mb | 3.95 | 3.3 | 2 | 1.6
323mb | 12.65 | 9.8 | 5.6 | 4.12

**Comment by aothms** [comment]
Thanks for verifying this. I thought I was doing the right thing (eliminating deeply nested virtual function calls) so it was weird to not see it materialize. Your model pushed me in the right direction for the fix.

Memory usage should be less as well btw. Mostly due to not storing less supertypes in the maps, but also a bit more compact attribute storage which is a little bit counteracted by not using lazy loading anymore.
