### ISSUE TITLE
'Shift +D' doesn't seem to work. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5448]
'Shift +D' doesn't seem to work. 

file: 
[wall layers.ifc.txt](https://github.com/user-attachments/files/17090367/wall.layers.ifc.txt)

https://github.com/user-attachments/assets/d6b8efc4-232e-45ec-ae78-4365f89765a4

manual 'IFC Duplicate Objects' works though...

https://github.com/user-attachments/assets/0230f12e-118b-4e86-af22-1bb982019ac2

**Comment by trhyder** [comment]
@theoryshaw , did shift-D ever "IFC Duplicate Objects", I think it may have only ever "Blender Duplicate Objects"?

The below image is from an old version of BlenderBIM (Blender on 4.1)
![image](https://github.com/user-attachments/assets/9e11251b-3190-4c18-a2ae-ed951a5d82fc)

**Comment by theoryshaw** [comment]
> @theoryshaw , did shift-D ever "IFC Duplicate Objects"

yes it did.

**Comment by theoryshaw** [comment]
I think this was a fluke... i can't seem to reproduce this again.  Closing for now.
