### ISSUE TITLE
update objects name changing name from the spatial manager

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5449]
This is a UI nicity. 

Would be nice if you changed the name of the spatial container in the Spatial Decomposition UI, that it would change the name in the outliner as well. 

Or is the outliner, as a tool, going to be abandoned? 

file: [wall layers.ifc.txt](https://github.com/user-attachments/files/17090490/wall.layers.ifc.txt)

https://github.com/user-attachments/assets/424bb84b-ab8f-400c-a4e5-e0ec29bd8275

**Comment by Gorgious56** [comment]
Hehe 6 minutes to close an issue, I think that's a world record :) Even if it was dupe. Cheers
