### ISSUE TITLE
Layerset slicing reverses order of materials on some walls

### ISSUE THREAD

**Issue by Alhetus** [IfcOpenShell/IfcOpenShell#545]
I have encountered an issue with layerset slicing that makes materials on some walls reversed in generated collada files. In archicad the walls have the same materials and the order is correct.

![image](https://user-images.githubusercontent.com/10682799/52476699-206c9d80-2ba8-11e9-93dc-4f2d15639d81.png)

Output viewed in Unity. The colors should be in the same order on both walls.

The sample file used: 
[Hansaviertel 17-12 (2 wall sample).zip](https://github.com/IfcOpenShell/IfcOpenShell/files/2844952/Hansaviertel.17-12.2.wall.sample.zip)

Material layerset usages in the IFC:
```
#256= IFCMATERIALLAYERSET((#222,#239,#255),'405 Insulated Concrete Single Plastered');
#261= IFCMATERIALLAYERSETUSAGE(#256,.AXIS2.,.POSITIVE.,-0.);
#359= IFCMATERIALLAYERSETUSAGE(#256,.AXIS2.,.NEGATIVE.,0.);
```

#509 might be the same issue.

**Comment by aothms** [comment]
Indeed, must be the same as #509. Was hoping @ninichki to send a PR since he pretty much laid out the fix.
