### ISSUE TITLE
Stair Duplication or New Stair Creation bug

### ISSUE THREAD

**Issue by chopinregis** [IfcOpenShell/IfcOpenShell#5451]
So upon duplicating the stairs, it looses it Representation - Tesselation properties and is not editable. The same thing happens when you create a new Stair. It also doesn't generate a error or bug report.
File link 
https://hub.openingdesign.com/OpeningDesign/Lake_Kegonsa_Renovation/src/commit/e4bdf7f131451bedc11174efde64a90c350f28a8/Open/Models/BlenderBIM/Lake_Kegonsa_Renovation.ifc

https://github.com/user-attachments/assets/6978d9e5-0da3-4e5f-bc63-e389abf3a680

https://github.com/user-attachments/assets/93fbfaae-5b34-4436-8ccc-f9ce25a1e8b2

**Comment by theoryshaw** [comment]
I think the bug in your 2nd video has been fixed. 

I can replicate, however, the bug in your first video.

**Comment by Gorgious56** [comment]
FWIW if you enable and validate the stair parametric modifier in the stair before you duplicate it, it seems the bug doesn't appear anymore.

**Comment by chopinregis** [comment]
> FWIW if you enable and validate the stair parametric modifier in the stair before you duplicate it, it seems the bug doesn't appear anymore.

yes that works. Thanks a bunch

**Comment by theoryshaw** [comment]
Maybe makes sense to keep this issue open, however, since it's a UI type of bug.

**Comment by chopinregis** [comment]
> Yup the underlying bug should be fixed. It might have something to do with differences in how the stair modifier is dealed with by Bonsai, there has been some additions over the past months. Was this model created long ago ?

not quite long ago but it was started before Bonsai.
