### ISSUE TITLE
AdvancedBrep with surface of revolution (commonly used in lollipop trees from Revit) creates circle with CGAL

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5453]
OCC produces (correct):
![2024-09-23-082052_234x307_scrot](https://github.com/user-attachments/assets/46def8bb-9fba-4c86-ab73-456c68876639)

CGAL / CGAL-Simple produces:
![2024-09-23-082023_191x289_scrot](https://github.com/user-attachments/assets/f16441b9-78e6-4b31-bd4c-fabe152eb52a)

File: 
[tree.ifc.txt](https://github.com/user-attachments/files/17091469/tree.ifc.txt)

```python
import faulthandler
import os
import sys
import numpy as np
import time
import multiprocessing
import ifcopenshell
import ifcopenshell.geom
import ifcopenshell.ifcopenshell_wrapper as wrapper
faulthandler.enable()

wrapper.turn_on_detailed_logging()

ifc_file = ifcopenshell.open('/home/dion/tree.ifc')
settings = ifcopenshell.geom.settings()
e = ifc_file.by_type("IfcGeographicElement")[0]
shape = ifcopenshell.geom.create_shape(settings, e, geometry_library="opencascade")
print('OCC', len(shape.geometry.verts))
shape = ifcopenshell.geom.create_shape(settings, e, geometry_library="cgal")
print('CGAL', len(shape.geometry.verts))
shape = ifcopenshell.geom.create_shape(settings, e, geometry_library="cgal-simple")
print('CGAL-Simple', len(shape.geometry.verts))
shape = ifcopenshell.geom.create_shape(settings, e, geometry_library="hybrid-cgal-simple-opencascade")
print('CGAL-OCC', len(shape.geometry.verts))
sys.exit()
```

**Comment by aothms** [comment]
Ok, yes, this shouldn't be attempted at all in the cgal kernel because we have no mechanism there (yet?) to handle curved surfaces. I'll close this issue as it will take some time (if ever) to get to this. `"hybrid-cgal-simple-opencascade"` should work now.
