### ISSUE TITLE
Segfault on beam (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#546]
1. Convert [546--beam--segfault--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/546--beam--segfault--augmented.ifc) with 6a5bfef (OCCT 7.3.0)
2. Experience segfault:
```FATAL: An error occurred, status code 139.```
3. Expected geometry from DDS, SimpleBIM and Solibri:
<img width="300" alt="screenshot 2019-02-12 at 14 15 50" src="https://user-images.githubusercontent.com/4601554/52637843-bf5b0780-2ed0-11e9-8162-e9d942e6854a.png">

SimpleBIM seems to show some artefacts in one of the corners, which may be a clue to what is causing the segfault:
<img width="300" alt="screenshot 2019-02-12 at 14 15 57" src="https://user-images.githubusercontent.com/4601554/52637875-dd286c80-2ed0-11e9-9105-e434decbba7b.png">

**Comment by aothms** [comment]
I can work around the segfault by applying all boolean operations at once. IfcBooleanResults are a binary tree basically, so I now walk the tree first and put second operands in a list. It's a nice performance improvement as well. Not entirely sure about the reason for the segfault though, there are over 20 boolean subtractions applied to this beam, at some point the data got corrupted it seems.

![afbeelding](https://user-images.githubusercontent.com/1096535/52700050-701be200-2f77-11e9-9c31-ddf5b13bbb2e.png)

**Comment by johanrd** [comment]
Nice - thanks! I can verify that this now works after 4822b57 🎉

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
