### ISSUE TITLE
'Shift + D' representation item, when in 'edit mode'. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5466]
Sorry this is probably in the roadmap as well... just exicited. :)

Would be nice to 'Shift + D' a representation item, when in 'edit mode'. 

![2024-09-23_16-08-47_blender_(Unsaved)_-_Blender_4 2 1_LTSblender](https://github.com/user-attachments/assets/f5048c0e-656b-49b8-abf4-f8c22e52b15b)

**Comment by Moult** [comment]
Yes, other related known incomplete features are duplicate, join, and split.

**Comment by theoryshaw** [comment]
very cool. 

One UI suggestion would be, if there's only one representation item, that `tab` brings you directly to the edit mode of the mesh or profile. .. verses having to tab in twice to edit the geometry.

**Comment by Moult** [comment]
@theoryshaw yes, I did consider that, but right now that makes the code a bit complicated. I'd rather keep it consistent and working first, and then introduce that as a QoL. It's a big change touching lots of parts - essentially completely deleting the way we used to handle geometry.
