### ISSUE TITLE
Position handling broken for IfcSurfaceCurveSweptAreaSolid

### ISSUE THREAD

**Issue by dleverton** [IfcOpenShell/IfcOpenShell#548]
The Position attribute is effectively ignored for IfcSurfaceCurveSweptAreaSolid due to a mixup with variables (the Position is decoded into a different gp_Trsf than the one that's actually applied to the shape).  GitHub is broken and won't let me create a pull request, but it's fixed in my branch at https://github.com/dleverton/IfcOpenShell.

**Comment by aothms** [comment]
Thanks. Great catch. I merged your commit. https://github.com/IfcOpenShell/IfcOpenShell/commit/bf1623975c6451baf3e2a1af9f32e9306d235b3f
