### ISSUE TITLE
Running ifcopenshell.api in pycharm

### ISSUE THREAD

**Issue by leonstrr** [IfcOpenShell/IfcOpenShell#5487]
Hello, I want to run the api in pycharm. However when I try to install the bpy module it says I need python version 3.7. However, ifcopenshell 0.8.0 is not available for python 3.7, is that right? At least I can't install it via pip.

Thanks in advance

**Comment by Andrej730** [comment]
@leonstrr 
Hi! What API methods? I believe there's just one method requiring bpy - `add_representation`. If you don't need it, then you can just skip this dependency.

Use of `bpy` usually means that this API method supposed to be called from Blender. Though `bpy` is [generally available in pip](https://pypi.org/project/bpy/) it's untested. Btw, what Python version you're using? Current version of `bpy` is available only for Python 3.11 - if it's asking for Python 3.7 then it seems it's trying to install some very old `bpy` version.

> However, ifcopenshell 0.8.0 is not available for python 3.7, is that right?

Yes:
https://github.com/IfcOpenShell/IfcOpenShell/blob/61151442cf445c34cfa797b095c79ffb51447f7b/src/ifcopenshell-python/pyproject.toml#L13

**Comment by Moult** [comment]
Agreed, most of ifcopenshell.api does not rely on bpy. There is a very little bit which does use bpy but this is only really used by Bonsai and it's not really meant to be a public API - we'll likely use less and less of it in the future.

**Comment by leonstrr** [comment]
Ok thanks a lot. am using Python 3.12 and was trying to go to 3.7 in order to use the bpy dependencies but then i figured out that there is no openshell for 3.7. But I will look if I can work around those methods using bpy. Thanks!

**Comment by leonstrr** [comment]
thanks @Moult :)
