### ISSUE TITLE
Bonsai - Blender crashes when editing copied text annotation on larger files?

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#5489]
This is difficult to replicate, I can't at the moment but very frustrating on larger files

Essentially when editing a copied Annotation Blender will crash and on restart Bonsai will be deactivated

The steps are simple:

1) Create a text annotation
2) Copy/duplicate the text
3) Edit the copied text

And it crashes

But it won't do it on command so not sure what is missing

**Comment by Moult** [comment]
Isn't there another bug here by you or someone who reported general crashiness during text editing? I'm almost certain that bug wasn't resolved and is due to the (bad) way the annotation decorator works for text values.

**Comment by Plae-Blue-Dot** [comment]
Absolutely duplicate of a much earlier issue from myself hahah:
https://github.com/IfcOpenShell/IfcOpenShell/issues/4699

I'm going to close this one
