### ISSUE TITLE
IFC Item mode feedback

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5491]
I have got some feedback to offer about the new item mode, maybe some of it is already on the roadmap / being fixed or has already been discussed, in which case please disregard :)

I'm wondering about wether setting the objects to display "In Front" is the right call, the geometry is already overlayed on top of other geometry with some transparency using a gpu shader. Also even though it makes the items pop up it does make their position relatively to the other objects in the scene harder to decipher. Also, it's particular to my workflow but it hides the points from the Point Cloud Visualizer addon, which makes things awkward :)

![image](https://github.com/user-attachments/assets/28ba8f8f-bc2b-4df4-9f7e-a999c27a1fcf)

Also it may be nice to setup some geometry caching or garbage collection since repeateadly going in and out of edit mode creates orphaned geometry which creates a memory leak (albeit fixed with quitting and rebooting the file)

![image](https://github.com/user-attachments/assets/f5994fd1-033c-4e4a-8921-e069b7af9ff2)

Edit: forgot to add this is awesome and I love how it looks like it's going to be implemented into Blender.

**Comment by Moult** [comment]
One of the downsides of this GPU shader translucent blue colour is that it's expensive dependent on the number of faces. When an object has a large number of faces, currently I just disable the shader and only use the bounding box highlight, but it doesn't look very good. I'm still exploring options to visually make these items "pop" so the user knows they are editable items and can easily spot and select them amidst a busy scene. Ideas?

**Comment by Gorgious56** [comment]
Maybe automatically select the representations items when switching to IFC edit mode and an IFC entity is selected ? Since the names are overlayed over the representation items one could see them at a glance, and the outline should be drawn on top of geometry even if it's hiding it ?

Also I noticed if you have a very dense representation item and a lightweight item, if you only edit the lightweight item it seems to recaculate everything and take some time when going out of "Blender" edit mode

**Comment by Moult** [comment]
> Also I noticed if you have a very dense representation item and a lightweight item, if you only edit the lightweight item it seems to recaculate everything and take some time when going out of "Blender" edit mode

Correct. In the past, firstly it was not even possible to edit just that single lightweight item. You had to edit the whole thing. If it were a mesh, it would:

 1. if it has an opening, recalculate the whole mesh without openings
 2. toggle edit mode
 3. ... you do whatever ...
 4. delete the whole previous geometry
 5. add a whole new geometry
 6. If it has an opening, then it would also recalculate the whole mesh with openings

Now, it will:

 1. always recalculate the whole mesh without openings, split into individual items (slower)
 2. set decorators and lock state and whatever (not significant time added)
 3. toggle edit mode
 4. ... you do whatever ...
 5. Delete just the small item (faster)
 6. Add just the small item (faster)
 7. Always recalculate the whole mesh regardless of openings (slower)

So I guess in theory faster to edit huuuuge meshes (step 5 and 6). Note that you're probably still on OpenCASCADE - with the new CGAL-OCC Hybrid the time taken to recalculate meshes drops significantly.

We can optimise this by not recalculating the whole mesh if there are no openings (step 1), and only recalculating the changed portion if there are no openings (step 7).

It's not hard to do and I actually started with that, but unless we take a lot of care there is always a risk of IFC-Blender mismatch if we skip recalculations.
