### ISSUE TITLE
bpy.ops.bim.file_associate() raises a FileNotFoundError

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#5494]
Hello,

when clicking on the button "Associate Bonsai with *.ifc files" in the Blender Preferences window (Blender 4.2.2 / Ubuntu 22.04.5 LTS) 

![image](https://github.com/user-attachments/assets/4847c9d7-0d7a-4471-8dd2-498ce3027af2)

there is this Python error showing up: 

```py
bpy.ops.bim.file_associate()
Python: Traceback (most recent call last):
  File "/home/<username>/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/operator.py", line 276, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/operator.py", line 283, in execute
    self.install_desktop_linux(src_dir=src_dir, destdir=destdir, binary_path=binary_path)
  File "/home/<username>/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/operator.py", line 330, in install_desktop_linux
    with open(os.path.join(src_dir, "bonsai"), "r") as wrapper_template:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/<username>/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/../libs/desktop/bonsai'
``` 

Bonsai version: `0.8.0`

Thanks.

**Comment by brunopostle** [comment]
Have you replaced your username with '<username>' for the bug report, or is this the actual output of the error message?

**Comment by swiss-knight** [comment]
It's a placeholder, the current username is used in place. But still, that path doesn't seem to exist.

**Comment by brunopostle** [comment]
Have you installed Bonsai from the official Blender Extensions site, or the daily [unstable version](https://docs.bonsaibim.org/guides/development/installation.html#unstable-installation), or both?

What are the contents of these folders:

    /home/<username>/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/libs/desktop/
    /home/<username>/.config/blender/4.2/extensions/blender_org/bonsai/libs/desktop/

**Comment by swiss-knight** [comment]
Yes Bonsai was installed under the "Get Extension" tab of the Blender Preferences window, so it comes from [extensions.blender.org](https://extensions.blender.org/add-ons/bonsai/ )

Here is the content of the two folders:

```sh
$ ls -1 ${HOME}/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/libs/desktop/
bonsai.desktop
bonsai.png
bonsai.xml
README.md
windows_bbim_association.ps1
windows_bbim_association.reg
x-ifc_128x128.png
x-ifc_512x512.png
```

and:
```sh
$ ls -1 ${HOME}/.config/blender/4.2/extensions/blender_org/bonsai/libs/desktop/
bonsai
bonsai.desktop
bonsai.png
bonsai.xml
Makefile
README.md
windows_bbim_association.ps1
windows_bbim_association.reg
x-ifc_128x128.png
x-ifc_512x512.png
```

**Comment by brunopostle** [comment]
Thanks, it looks like this file doesn't get added to the bonsai wheel because it doesn't have a file extension.

The bug is here: https://github.com/IfcOpenShell/IfcOpenShell/blob/d581174513979e8c8d621b66861622f44032bb9a/src/bonsai/pyproject.toml#L30

This line should look something like this:

    "*" = ["*.*", "libs/desktop/bonsai"]

It also looks like this line is redundant (at least for the linux package): https://github.com/IfcOpenShell/IfcOpenShell/blob/d581174513979e8c8d621b66861622f44032bb9a/src/bonsai/Makefile#L230

Untested (I won't get a chance to fix this this week)

**Comment by brunopostle** [comment]
Workaround is:

    cp ${HOME}/.config/blender/4.2/extensions/blender_org/bonsai/libs/desktop/bonsai \
    ${HOME}/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/libs/desktop/
