### ISSUE TITLE
IfcConverter: Obj file referencing the wrong mtl file

### ISSUE THREAD

**Issue by shsteven** [IfcOpenShell/IfcOpenShell#55]
Currently the file reference in .obj is

```
# File generated by IfcOpenShell 0.5.0-dev
mtllib BIMhouse.mtl.tmp
```

It should not include the .tmp extension at the end.

**Comment by Stinkfist0** [comment]
This bug is caused by my recent work. Fix coming soon.

**Comment by shsteven** [comment]
@aothms Wow! Thanks for the quick fix!
