### ISSUE TITLE
Osarch: I don't receive the verification mail

### ISSUE THREAD

**Issue by leonstrr** [IfcOpenShell/IfcOpenShell#5503]
Hey Moult, I created an acoount on osarch (wiki and community). When I log in to the community and want to make a post, I read in the bottom that I have to verify (normal process). However, I don't receive the mail, even not when I request to send me a new one. My mail ist 100% right and working. 
Mail: leon.streicher@web.de
Acoount: Leonstrr
thanks in advance

**Comment by Moult** [comment]
I've just manually confirmed your account, it's probably best if you reach out in the osarch live chat, not in Github - this is a separate project :)
