### ISSUE TITLE
 IfcCShapeProfile not displaying in V0.8.1

### ISSUE THREAD

**Issue by Dayo9174** [IfcOpenShell/IfcOpenShell#5509]
Hi Team,

I am following up on my question in the live chat regarding an issue with the IfcCShapeProfile in Bonsai.

**Issue Description:**
I created an IfcCShapeProfile using Bonsai V0.8.1 (bonsai-0.8.1-alpha240927). However, the profile does not display a shape representation in the 3D viewer. See the screenshot below for reference:
![image](https://github.com/user-attachments/assets/f9d1c80c-d33a-4938-ae48-ef61bffe7dd8)
bonsai-0.8.1-alpha240927

Interestingly, when I open the same file in Blender 3.6 with Bonsai V0.0.240606, the profile is correctly represented in the 3D viewer:

![image](https://github.com/user-attachments/assets/75097177-ddb6-4ae7-acdd-2a982e5d8fe2)
blenderbim-240606

Not sure why this is happening hence the bug report

**Attachments:**
[Test File](https://drive.google.com/file/d/1-uKKpKVm9edDnZbICsbwS-FK7UWaSC-Y/view?usp=sharing) showcasing the issue.

Please let me know if further information is needed or if you would like me to test potential fixes.

Thanks in advance for your assistance.

os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64

**Comment by Moult** [comment]
Looks like a glitch in v0.8. Marking as something for @aothms to look at.

**Comment by aothms** [comment]
Thanks for the report. Tricked by python:

```
>>> -1 % 5
4
```

But in C++ this is `-1`.

I should have know this by heart because we looked into exactly this when we added MODELO to the schema in IFC4X3.

Should be fixed.

**Comment by Dayo9174** [comment]
Thanks @aothms will test it out in the next build.

**Comment by Dayo9174** [comment]
Hi All, 
Hi All,

I conducted some additional tests and discovered that the shape representation fails when InternalFilletRadius is set to 0.002:

![image](https://github.com/user-attachments/assets/c5d7f5bb-af73-4389-9adb-83b4dae933ea)

However, when InternalFilletRadius is set to 0, the shape displays correctly:

![image](https://github.com/user-attachments/assets/bf0de1db-f533-4d8e-b33b-fd1287a6feae)

Additionally, whenever I attempt to edit the profile with InternalFilletRadius = 0.002, I encounter the following error below, even without making any changes:

I’m unsure of the cause behind this behaviour, thanks for your assistance so far.

[Download the test file](https://drive.google.com/file/d/1oPKKigZG-0yzefKfmmCmSTo7yy7pFVJl/view?usp=sharing)

```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
blender_version: 4.2.2 LTS
bonsai_version: 0.8.1-alpha240930
bonsai_commit_hash: 5d83c49
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_edit_profile
# ifcopenshell.api: profile.edit_profile
>>> {"profile": {"cast_type": "entity_instance", "value": 97, "Name": null}, "attributes": "{'ProfileType': 'AREA', 'ProfileName': 'Test with R', 'Depth': 0.4099999964237213, 'Width': 0.029999999329447746, 'WallThickness': 0.0020000000949949026, 'Girth': 0.009519999846816063, 'InternalFilletRadius': 0.0019000000320374966}"}
# ifcopenshell.api: geometry.add_axis_representation
>>> {"context": {"cast_type": "entity_instance", "value": 16, "Name": null}, "axis": "[Vector((-4.964719124700423e-08, 4.773848044572083e-15, -1.2758079037666903e-09)), Vector((-6.157208076729148e-08, 2.6090130964408036e-14, 3.0))]"}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 173, "Name": "Member"}, "representation": {"cast_type": "entity_instance", "value": 183, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 183, "Name": null}}
last_error: Traceback (most recent call last):
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\profile\operator.py", line 136, in _execute
    model_profile.DumbProfileRegenerator().regenerate_from_profile_def(profile)
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\profile.py", line 165, in regenerate_from_profile_def
    DumbProfileRecalculator().recalculate(objs)
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\profile.py", line 841, in recalculate
    joiner.recreate_profile(element, profile)
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\profile.py", line 456, in recreate_profile
    bonsai.core.geometry.remove_representation(tool.Ifc, tool.Geometry, obj=obj, representation=old_axis)
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\geometry.py", line 169, in remove_representation
    geometry.delete_data(data)
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 98, in delete_data
    bpy.data.meshes.remove(data)
ReferenceError: StructRNA of type Mesh has been removed

ifc: IfcCshapeprofile - Test file - 006.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell 0.8.1-alpha240929
originating_system: Bonsai 0.8.1-alpha240929-275d615
```

**Comment by Moult** [comment]
Tested with latest bot build, seems to be fixed.
