### ISSUE TITLE
Compute each IfcElement bounding box and write the reslut in xml 

### ISSUE THREAD

**Issue by wq8806** [IfcOpenShell/IfcOpenShell#551]
I'm trying to get each IfcElement's boundingbox  and write the reslut in xml with IfcConvert, 
When I use context_iterator.bounds_min() and bounds_max(), the reslut is not same as dae model. 
Is there any way to get the correct bounding_box which is same as the reslut computed by Blender?

Thanks for your early reply.
Best Regards

**Comment by aothms** [comment]
Oh I can see now how that might be confusing, but `bounds_min() - max()` are the global bounds of the scene computed from the product placement positions. It doesn't vary as the individual elements are returned.

If you already have this iterator setup, just iterate over the individual elements returned by `get()` and take the min-max values of the `geometry().verts()` vector (this is a flattened vector of `[x0, y0, z0, ... xn, yn, zn].)

If you use the WORLD_COORDS settings then the product placement will be multiplied into the verts vector (which essentially means you get global axis aligned bounding boxes). Without WORLD_COORDS set, you'll get vert positions within the placement coordinate system (which is already written to XML).

**Comment by wq8806** [comment]
Thank you for your quick reply, I have got the specified GlobalId element's minX/Y/Z maxX/Y/Z by geometry().verts().  But the relsult is not the same as Blender.
I wonder if I need to multiply the vector [minx,miny,minz] by the transform matrix which is defined as ObjectPlacement ,then get the correct result ?

**Comment by aothms** [comment]
Yes probably, or use WORLD_COORDS setting to give you an AABB.

**Comment by wq8806** [comment]
Thanks! Your guidance has helped me a lot.

**Comment by mlaura1996** [comment]
Hi, I am trying to get the bounding box of each Ifc element. Could you please share an example of how to do it? I am not understanding if I have to import blender ...

**Comment by Moult** [comment]
@mlaura1996 you can get the max/min of all the verts from the geometry. You can see how to get all the verts in this sample code: https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html

Alternatively you can help add your vote on this issue :) https://github.com/IfcOpenShell/IfcOpenShell/issues/1040
