### ISSUE TITLE
How do I delete a locked element ? (IfcSpace)

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5514]
In a brand ifc project, create an IfcSpace.
Try deleting it with *X*.
An error appears in the footer of Blender that says *Element 'IfcSpace/Space' is locked and cannot be deleted*.

How do I delete an IfcSpace ? How do I unlock it ? What is the concept of a locked entity ? So many questions ><

**Comment by Moult** [comment]
Locked elements are elements that are typically rarely updated in the course of regular modeling. I.e. you typically don't want to accidentally select and copy grids, buildings, rooms etc.

For this reason they are locked by default. In the project information tab you can toggle the lock state if you do want to edit these things.

Dion Moult

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Gorgious56** [comment]
Okay, that makes sense, thank you. However sorry but I don't see where in the interface I can unlock an IfcSpace ?

**Comment by Moult** [comment]
See next to the visibility icon for grids/spatial decomposition.

![2024-10-01-200722_330x393_scrot](https://github.com/user-attachments/assets/a000d7f2-ea17-4b18-9223-b524dec514a9)

**Comment by Gorgious56** [comment]
Ah, okay thank you I assumed it was a property on individual occurrences rather than a projectwide property.

So to make something actionable out of this issue, I would say adding a hint in the error message would be a good nudge in the direction for newcomers ? Something along 

*Element 'IfcSpace/Space' is locked and cannot be deleted. Spatial elements can be unlocked from the Spatial panel in the project overview tab.*

Also would it make sense to have an unlock-override on spatial elements on individual occurrences or in hierarchies of particular spatial elements ? Maybe when I'm working on Storey A I want its spaces to be editable, but I want spaces in stories B and C to remain locked.

**Comment by Moult** [comment]
Agreed, if you can come up with a good short message (so it fits in the status bar) PR very much appreciated :)

Not sure about more granular locking. Maybe there is a more generic way to solve this in the future. I'd prefer to wait until this "lock" concept matures a bit more and see how people use it.

**Comment by Gorgious56** [comment]
I guess this is solved since the main problem here was that I didn't find where I could unlock the space elements.
