### ISSUE TITLE
Should IfcSpaces collections be linked to a main IfcSpace collection ?

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5515]
Would it make sense to put all IfcSpace/Space.xxx in a parent collection under the IfcProject/ main collection ? Currently creating many IfcSpaces clutters the interface by creating many collections under the main one, it would be IMO easier to manage.

To be clear I'm suggesting that

![image](https://github.com/user-attachments/assets/fb755895-548a-41fa-ae0a-479849f5a9f0)

instead of that

![image](https://github.com/user-attachments/assets/b2826574-67d0-4e0f-aceb-dbb29df69a1b)

**Comment by Moult** [comment]
I think this is generally a good idea. IfcSpaces are a bit special compared to other things. Let's see if there are any objections by others.

**Comment by steverugi** [comment]
+1 !
