### ISSUE TITLE
Question: Tolerant or strict regarding contexts?

### ISSUE THREAD

**Issue by yorikvanhavre** [IfcOpenShell/IfcOpenShell#5522]
This is more a discussion than an issue, and is mainly for @Moult I guess, but anyone else please give opinions too :)

There are places like in https://github.com/IfcOpenShell/IfcOpenShell/blob/2a9301ead229bba45087f985871beff019e41185/src/bonsai/bonsai/tool/drawing.py#L688 where Bonsai looks for representations in a very strict context. For example in this case, Bonsai will look for a specific Model -> Body -> MODEL_VIEW representation context for a DRAWING annotation. If the exact context is not found, no representation is retrieved and the operation fails.

Is this a desired behaviour to be strict (if the context is not right, we bail out), or would it be interesting to accomodate "wrong" contexts ? Ex: If Model -> Body -> MODEL_VIEW is not available, look for Model -> Body, if not available, look for Model only, if not, look for just any representation in any context

Just trying to decide what to do in FreeCAD, if we need to fix or create additional subcontexts, or if we just go with what's in the file already...

**Comment by Andrej730** [comment]
I think it makes sense to create the exact subcontexts that are needed - otherwise the information about what context specifically is implied is getting lost and later someone working with IFC model will have two kind of problems: 
1) interpreting what non-specific context exactly mean
2) fixing the model and moving representation to the correct subcontext might get tricky e.g. if different type of subcontexts will be mixed up using just Model context instead of more accurate Model/Body/MODEL_VIEW and Model/Box/MODEL_VIEW.

**Comment by yorikvanhavre** [comment]
I agree we need to define contexts well, I'm basically following what's in https://docs.ifcopenshell.org/autoapi/ifcopenshell/api/context/index.html for now.

But indeed this question arises from the same problem: What to do when some entities in a file are not in the correct context, ex: Everything in a single Model context. The IfcOpenHouse example that comes with IfcOpenShell is doing that...

**Comment by Moult** [comment]
Tolerant when it doesn't matter, and strict when it does. :)

For example when we load a model, typically people want to see the "3D Body" geometry. So we prioritise showing 3D bodies, and fall back to non-bodies, then fallback to 2D, then fallback to miscellaneous, etc. See https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcopenshell-python/ifcopenshell/util/representation.py#L180

We do a similar "tolerant" fallback when generating drawings where we prioritise the target view that matches the camera, and fall back to MODEL_VIEW.

However, we are strict when it does matter, like for drawings we only generate bodies, and annotations are specifically layered on top.

Let me know if you come across a particular scenario where you come to a different conclusion about the tolerant / strict choice :)

**Comment by yorikvanhavre** [comment]
Okay, that pretty much gives me a good direction to go :) Thanks guys!
