### ISSUE TITLE
when I use `bpy.ops.bim.unlink_object(should_delete=False)` it still has a connection to the other instances. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5527]
I could be missing something, but when I use `bpy.ops.bim.unlink_object(should_delete=False)` it still has a connection to the other instances. 

I don't remember it acting this way before. 

file: https://hub.openingdesign.com/OpeningDesign/Verona_3_Season_Porch/src/commit/43190496e77c392dc27e7f5a94098063fe4b6d99/Open/Models/BlenderBIM/Verona_3_Season_Porch.ifc

https://github.com/user-attachments/assets/a335d268-8eda-4c44-978b-442c976b4834

**Comment by theoryshaw** [comment]
having gone back through a couple version, i guess this has always been the behavior.  It seems, however, it shouldn't work this way.  Maybe i'm missing something.

**Comment by Gorgious56** [comment]
Hello, after parsing a bit the source code it seems this argument is used (set to false) when an ifc element was somehow corrupted and the link from Blender to ifc was lost ? https://github.com/IfcOpenShell/IfcOpenShell//commit/a65c6b6d3f9c2d57e930e30d823df0edc73ead0b

Could you expand on what you wish to happen in this case and what should be the difference with keeping the checkbox on ?

**Comment by theoryshaw** [comment]
To be honest i'm not 100% certain what the two modes do. 

I do know, if I use `(should_delete=True)` it duplicates the styles, which sometimes I don't want, as sometimes I unlink to create a new new type/instance (to fix corrupt geometry,or other reasons) from the existing geometry, but want to keep the style names.. not duplicate them.

**Comment by Moult** [comment]
Unlinking converts an IFC object back into a regular Blender object. This means that it's now a regular Blender object and any IFC styles it used to have now become just regular Blender materials too.

During the unlinking process, you have two choices:

 1. Delete the IFC element that the object used to represent. This is the intuitive option. After all, no objects in your Blender session now represents the IFC element.
 2. Keep the IFC element. This means that the element still exists in IFC, but there is now nothing in Blender that shows it - it is uneditable and invisible until you decide to reload the IFC.
