### ISSUE TITLE
Hit ESCAPE to return to IFC Object Mode ?

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5529]
I'm just wondering about a UX papercut with the new IFC Object / items modes. 

Currently when in the Item mode with an entity that has representations one can use the shortcut TAB to return to Object mode, but there needs to be no representation item selected. So the user can either
- Press 2 times on A to deselected everything, then TAB
- Or click into the void to clear the selection, then TAB
First solution is IMO time consuming and workflow disrupting, and second solution is not always possible, for instance if my viewport camera is inside a room I may not have access to an area where I don't have any geometry.

I naturally found myself hitting ESCAPE assuming it would go out of item mode towards Object mode, so I'm wondering what people think about it. It isn't currently used for anything particular in this context, and it felt right to me.

**Comment by brunopostle** [comment]
+1 I used tab-tab to edit a mesh this morning and couldn't figure out how to get back to object mode. I was going to ask on matrix, but got there eventually (after trying Esc and looking for an operator).

Alternatively my initial expectation was that the tab sequence would be a cycle: tab to switch from object to representations mode, tab again to edit a representation, tab to go back to representations mode, and tab again to go back to object mode.

This wouldn't let you edit representations one after another without going back to object mode, but at least the user will never get stuck not knowing what to do.

**Comment by Moult** [comment]
I've been using Alt-A to deselect.

How would tab cycling work? First tab goes into Item mode, then if you tab again which item will it edit?

I like the escape idea.

**Comment by Moult** [comment]
A note that implementing escape is a bit tricky. Options are:

 1. Use a modal operator that runs on startup, that passes through the event safely otherwise. This is the option I went with.
 2. Create a keybinding in a BIM Tool. This only works in the BIM tool, and has the same problems with option 3.
 3. Register a new hotkey Escape in the keymap. This can bork use of the Escape key in other built-in situations.

**Comment by brunopostle** [comment]
When i got stuck with this, the first thing I tried was the tab key to get back to object mode, but it just went back to mesh editing. I guess I thought that the tool would remember which 'direction' I was going: drilling down into the details, or exiting editing.

I can see that this cycling workflow would slow complex tasks that involved editing several representation items

**Comment by Andrej730** [comment]
Kind of confusing when you're in Item Mode and you're using Shift+D and then hit Esc to quit from moving mode after duplication and you end up exiting Item Mode.

**Comment by Andrej730** [comment]
One more confusing thing about it is when you open a enum property dropdown and then want to close the dropdown using the keyboard.

https://github.com/user-attachments/assets/87a61d23-b4e2-4f51-b9d9-b50af97d543b

**Comment by theoryshaw** [comment]
Having thought about this for awhile, to be consistent with other UI approaches, it seems `ESC` should be used to exit a command, so you don't save anything.

In this scenario, 'ESC' currently exits edit mode, and saves the modified representation. 

...

What about adding a new UI approach in this scenario?  Maybe space bar?

**Comment by theoryshaw** [comment]
Any maybe space bar exits all the way out, even if you're nested deep in edit land.

**Comment by theoryshaw** [comment]
or use 'Enter'.... similar to how 'Enter' works when using the polyline tool.
