### ISSUE TITLE
High memory usage converting file

### ISSUE THREAD

**Issue by RyanHow** [IfcOpenShell/IfcOpenShell#553]
Hi!

I'm trying to convert an IFC4 file. I've tried building the master branch with IFC4 support, and also tried a few of the automated builds from the 0.6.0 branch.

In all cases the memory usage of the IfcConvert command is very high. around 2500MB and the conversion takes an hour or so then ends up in a segfault.

The IFC file in question is only 17MB.

Is there a way to figure out what is happening here?

The model opens fine in Solibri

Thanks! :)

**Comment by aothms** [comment]
IfcOpenShell is not always very efficient in terms of processing time or memory usage. This appears very extreme though. Is there a way to share they file, either here publicly or confidentially at models@ifcopenshell.org ?

**Comment by RyanHow** [comment]
I'm not sure what I did. But it managed to complete this time in 30 minutes. However, the resulting Collada file is 2GB! And the memory usage still spiked to 1.6GB.

I'm not sure what changed between my last few attempts.

I haven't been able to open or convert the Collada file. So I am guessing it is not usable.

I'm running Windows, 64bit version of the 0.6.0 branch, commit 33cbcc2.

I've emailed the file.

Thanks so much! :)

**Comment by aothms** [comment]
Reason for the excessive processing time and file size is a bug in the processing of cylindrical surfaces. The length unit was not accounted for, resulting in huge triangle meshes as the deflection tolerance is constant. I get a good result now in 2 minutes. Thanks for reporting this. Cylindrical surfaces are an addition in IFC and not heavily used yet (for example some other viewers don't seem to even show the trees).


I committed this in master and didn't manage to merge into v0.6 yet. There are a lot of conflicts from some other commits, but you can easily cherry pick the commit onto v0.6 yourself locally.

**Comment by RyanHow** [comment]
Thanks so much! :)
