### ISSUE TITLE
Bonsai can not load in walls, windows and other elements from IFC file but solobri can read it without issues.

### ISSUE THREAD

**Issue by olemariussvendsen** [IfcOpenShell/IfcOpenShell#5536]
Im experiencing a weird issue, where Bonsai 241004 (tried an older one as well) can not load in walls, windows and a lot of other elements from an IFC file. As shown in the image below, Solibri has no issue showcasing the information.

IFC file used:
https://we.tl/t-uFfJ6PtNV9

![2024-10-04_09-10-17](https://github.com/user-attachments/assets/e6e3e118-677a-410f-9d3c-c15625390e32)

**Comment by Andrej730** [comment]
There is a limit that by default allows only 30000 elements loaded, you can load project in advanced mode (File - Open - Enable Advanced Mode on the right panel) and then set Element Range to some larger range (e.g. 0-50000, currently your project has around ~45k elements).

I've added a warning so at least there will be some communication to user that project wasn't loaded completely.

![image](https://github.com/user-attachments/assets/a19be2b6-7054-492c-a273-b3e93f1c3705)

**Comment by Moult** [comment]
Slight tweak - instead of loading and _then_ seeing the warning that stuff is missing, it now warns you prior to loading and gives you the option to filter (but now defaults to loading everything).
