### ISSUE TITLE
Measuring tool: `1'5/8"` should read like `1' - 0 5/8"`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5545]
minor formatting comment...

`1'5/8"` should read like `1' - 0 5/8"`
ping @brunoperdigao 

https://github.com/user-attachments/assets/cc360b98-1b12-4be3-b785-86d14a505515

**Comment by brunoperdigao** [comment]
@theoryshaw Is this correct?
![Image](https://github.com/user-attachments/assets/28a259ad-b798-497f-99ae-2858626ae030)

**Comment by theoryshaw** [comment]
on my side, it seems to round too aggressively now....

https://github.com/user-attachments/assets/3e5f69d6-29cc-40c1-9887-4b6f8428e22b

**Comment by theoryshaw** [comment]
i think the over rounding, happened here: 481e6b8a8db4ce8454031972f6dfb3b99b9e33e7
