### ISSUE TITLE
Show object preview while adding with polyline/insertion point.

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#5551]
This should follow #5324 implementation

**Comment by brunoperdigao** [comment]
Initial implementation here: 97ed3bb0d5e8cbe64f114f3daa5e8a58f1fd2d66

![Image](https://github.com/user-attachments/assets/18d6b385-0548-4988-9ea8-c5a3ed59da08)

**Comment by sboddy** [comment]
I know this sounds a bit like a dumb question, but have you tried this on a wall aligned along the Y axis? The door doesn't rotate in preview. On clicking it adds the door/window in the correct orientation, but the preview being 90 deg. out is a bit confusing.

**Comment by brunoperdigao** [comment]
@sboddy Thanks for testing. It's a bug, I'll try to fix this soon.

**Comment by brunoperdigao** [comment]
> @sboddy Thanks for testing. It's a bug, I'll try to fix this soon.

This should be fixed.

**Comment by sboddy** [comment]
Nice!

**Comment by brunoperdigao** [comment]
Implemented preview for beams and columns.

**Comment by theoryshaw** [comment]
very cool!

one glitch, it seems...

https://github.com/user-attachments/assets/70fc5bd7-8bfe-464d-b158-19b79c929adb

**Comment by sboddy** [comment]
That's just American units where y'all measure everything in terms of something else. "It was as long as 15 football pitches, Bob!" Bruno is just using beams as a unit of measurement. 😉

**Comment by brunoperdigao** [comment]
The issue should be fixed now. Imperial units are hard enough, we don't another units system :)
