### ISSUE TITLE
Allow Diacritical Marks in Typenames, such as é, for Linking IfcInstance and IfcCostItem

### ISSUE THREAD

**Issue by Rick-de-Blom** [IfcOpenShell/IfcOpenShell#5561]
When importing a CSV file that contains special characters such as accented letters (e.g., é, à, è) into the cost schedule of Bonsai, an error occurs. Specifically, rows containing these characters are left empty after the import, despite the fact that these characters work correctly when used directly in other parts of the system, such as the "Grouping and Filtering" search function and the "Spreadsheet Import/Export" feature. This issue seems isolated to CSV imports for the cost schedule.

![Afbeelding uit Bonsai](https://github.com/user-attachments/assets/2e97ddb7-fc64-42fe-8788-a65f41fce8b6)

**Comment by Moult** [comment]
Can you help provide a sample CSV?

**Comment by Rick-de-Blom** [comment]
[Test budget reduced - Cost_schedule.csv](https://github.com/user-attachments/files/17342423/Test.budget.reduced.-.Cost_schedule.csv)
