### ISSUE TITLE
Please create an .exe file for this latest version of IfcConvert.

### ISSUE THREAD

**Issue by Pdongjaelee** [IfcOpenShell/IfcOpenShell#5574]
Please create an .exe file for this latest version of IfcConvert.

https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.8.0/src/ifcconvert

**Comment by Andrej730** [comment]
@Pdongjaelee see the comments in ifcopenbot repository - https://github.com/IfcOpenBot/IfcOpenShell/commits/v0.8.0/

![image](https://github.com/user-attachments/assets/33818ce6-ee5f-4a66-b984-11909c7d6bac)
