### ISSUE TITLE
Wrong style get applied to objects, when `bim.update_current_style` is run

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5576]
When following the exact steps in the video, the wrong style gets applied to the objects

[20241001 - material and styles (2).zip](https://github.com/user-attachments/files/17382652/20241001.-.material.and.styles.2.zip)

https://github.com/user-attachments/assets/a25daa64-1997-4e1c-ab06-04e691aaf47c

**Comment by theoryshaw** [comment]
I have a feeling it's related to this glitch too: 
https://community.osarch.org/discussion/2556/glitch-where-all-objects-in-scene-take-on-one-material#latest

**Comment by theoryshaw** [comment]
Yes, it seems so...

https://github.com/user-attachments/assets/a8568117-96b8-4053-a5b6-4bcd5d5aa0e5

**Comment by Andrej730** [comment]
> I have a feeling it's related to this glitch too:

Yeah, it's the same bug. Will be fixed in the next commit.
