### ISSUE TITLE
Switching stair types do not update.

### ISSUE THREAD

**Issue by chopinregis** [IfcOpenShell/IfcOpenShell#5577]
In a simple Ifcfile experiment the stair types updated naturally as it should, but for some unknown reason, in this project file, it doesn't behave as expected. Currently the observed behavior is that, when you change the stair type, you have to first hit edit stair parameters in the parametric geometry of the stair before it regenerates the assigned stair property. Video attached. 

https://github.com/user-attachments/assets/59fb645a-b5cc-4e34-8eb0-7da0d0a5b3a0

[https://hub.openingdesign.com/OpeningDesign/Lake_Kegonsa_Renovation/src/commit/4570c0a554346d949c609b51ef917cc59bba0720/Open/Models/BlenderBIM/Lake_Kegonsa_Renovation.ifc](url)

Issue could potentially be related to this other issue. 

https://github.com/IfcOpenShell/IfcOpenShell/issues/5451#issue-2541243248

**Comment by Andrej730** [comment]
@chopinregis same issue as before - all stair types for some reason don't have any representations, therefore changing type for occurrence doesn't change it's representation.

![image](https://github.com/user-attachments/assets/ef9d5589-689d-4e9a-93fc-24274168dffa)

Seems like a bug that was already fixed as currently creating a stairtype with stair representation doesn't create element types without representations:

![image](https://github.com/user-attachments/assets/11262f08-911f-4b31-9174-043db89d956a)

![image](https://github.com/user-attachments/assets/ffe2071e-792a-49d6-ba35-5b0e0212e2c8)

I guess the way to solve it for the projects affected by the bug would be to recreate the stair types and stair occurrences.

**Comment by chopinregis** [comment]
Thanks a bunch @Andrej730 I'll do that.
