### ISSUE TITLE
Bonsai not active after new "Update" - No module named 'bonsai' (Microsoft Store Blender)

### ISSUE THREAD

**Issue by Owuraqu** [IfcOpenShell/IfcOpenShell#5582]
Today, I updated Bonsai with the "Update" button in the Blender Add-ons. After that, I clicked on the "Restart Blender" pop-up, and the Blender closed but could not restart. I manually started Blender, but I could see Bonsai checked in the "Extensions" and "Add-ons" in the Blender preferences. However, the "BIM" workspace didn't appear, and there was no Bonsai in Blender.
I had to uninstall and re-install Bonsai for it to work again.

**Comment by Andrej730** [comment]
It's hard to tell what's happened, need some errors logs (they're available in Window - Toggle System Console).

**Comment by Owuraqu** [comment]
I just did an update and the same problem has re-occurred. You can find the logs in the attached image.
![BonsaiFailedLoad](https://github.com/user-attachments/assets/a3e5178b-3af9-4e1c-9640-5df45d572c9c)

Blender failed to restart and when I manually started it Bonsai showed up in the Extensions and Add-ons in the Blender Preferences but nothing Bonsai in the workspace as can be seen in the attached image.
![BonsaiAdd-ons](https://github.com/user-attachments/assets/be508ff0-5aab-4c76-bb3b-cbf9028c3e78)
![BonsaiExtensions](https://github.com/user-attachments/assets/e1cc0a97-80ad-4820-9862-7cbc564f80ed)

**Comment by Andrej730** [comment]
@Owuraqu Hi! Does this issue still persists? If so, can you please send error logs in console after update failed? 
Logs you posted before seems to be after update failed and Blender restarted, need the logs before the restart.

**Comment by Owuraqu** [comment]
> @Owuraqu Hi! Does this issue still persists? If so, can you please send error logs in console after update failed? Logs you posted before seems to be after update failed and Blender restarted, need the logs before the restart.

Hi @Andrej730, I just updated so kindly find the screenshot below;
![UpdateErrors](https://github.com/user-attachments/assets/0c47d4a7-f8b3-48bc-851f-8d777eeb3476)

When I click the 'Restart Blender' button, just when it seems like Blender is restarting, it abruptly shuts down. But when I manually restart again, Bonsai shows up nicely with all the Workspace buttons. What is left now is the Restart working.
Thank you.

**Comment by Andrej730** [comment]
@Owuraqu so update does work fine now but only restart doesn't work properly?

Then can you please try to run "Blender Restart" from Debug section? It doesn't work too?
![image](https://github.com/user-attachments/assets/2471ebbf-b95f-4e11-996b-a2babdc310aa)

If it doesn't work, can you also start Blender from console and try to restart it using the restart button and send the full traceback when it fails? You can also check `blender.crash.txt` in `%temp%` that should be created on unexpected shutdown and check Windows Event Viewer - Windows Logs - Application entries.

**Comment by Owuraqu** [comment]
> @Owuraqu so update does work fine now but only restart doesn't work properly?
YES. Everything works now except that the 'Restart Blender' doesn't work properly so I have to always start it again after the update.
>Then can you please try to run "Blender Restart" from Debug section? It doesn't work too?
I will try that on the next update and give you the feedback.

> If it doesn't work, can you also start Blender from console and try to restart it using the restart button and send the full traceback when it fails? You can also check `blender.crash.txt` in `%temp%` that should be created on unexpected shutdown and check Windows Event Viewer - Windows Logs - Application entries.
Okay will do that. Thank you.

**Comment by Owuraqu** [comment]
> @Owuraqu so update does work fine now but only restart doesn't work properly?

YES. Everything works now except that the 'Restart Blender' doesn't work properly so I have to always start it again after the update.
>Then can you please try to run "Blender Restart" from Debug section? It doesn't work too?

I will try that on the next update and give you the feedback.

> If it doesn't work, can you also start Blender from console and try to restart it using the restart button and send the full traceback when it fails? You can also check `blender.crash.txt` in `%temp%` that should be created on unexpected shutdown and check Windows Event Viewer - Windows Logs - Application entries.

Okay thank you.

**Comment by Andrej730** [comment]
> I will try that on the next update and give you the feedback.

I mean there's no need for pending update, you can run it any time, I'm trying to narrow down if it's just an issue about restart button in general or it's something about pending update too.

**Comment by Owuraqu** [comment]
> I mean there's no need for pending update, you can run it any time, I'm trying to narrow down if it's just an issue about restart button in general or it's something about pending update too.

I run the "Restart Blender" from the Debug tab and it failed. Blender couldn't restart.
I am trying to run Blender 4.2.3 from the console but cannot find the path. Kindly help me with the console code so I can run it from there.
Thank you.

**Comment by Andrej730** [comment]
> I am trying to run Blender 4.2.3 from the console but cannot find the path. Kindly help me with the console code so I can run it from there.

You need to open `cmd` and drag'n'drop `blender.exe` to it, it will add path like "c:\path\to\blender.exe" that you'll be able to run it. Or you can drag'n'drop the blender shorcut you use, should work the same, the path will be like "c:\path\to\blender.lnk"

**Comment by Owuraqu** [comment]
I just tried opening my Blender 4.2.3, but a dialogue appeared saying the shortcut could not be found. And when I did a window search I realised it had updated itself to Blender 4.3.0 but Bonsai was not installed, so I may have to reinstall it again.
Can you tell me where to find the Blender 4.3 shortcut? I can't seem to find it.
Thank you.

**Comment by Andrej730** [comment]
> I just tried opening my Blender 4.2.3, but a dialogue appeared saying the shortcut could not be found. And when I did a window search I realised it had updated itself to Blender 4.3.0 but Bonsai was not installed, so I may have to reinstall it again.
> Can you tell me where to find the Blender 4.3 shortcut? I can't seem to find it.
> Thank you.

I don't know where Blender installed on your computer, you can just search for blender.exe.

**Comment by Owuraqu** [comment]
This is the path to Blender 4.3.0 on my PC "C:\Users\tepay\AppData\Roaming\Blender Foundation\Blender\4.3\config". The "config" folder is the only but empty. What's going on?

**Comment by Andrej730** [comment]
> This is the path to Blender 4.3.0 on my PC "C:\Users\tepay\AppData\Roaming\Blender Foundation\Blender\4.3\config". The "config" folder is the only but empty. What's going on?

It's not the path you need to start Blender from cmd, you need the one that has blender.exe.

**Comment by Owuraqu** [comment]
The search for blender.exe doesn't show up anything. I am confused now as to why nothing shows up even though I can open Blender.

**Comment by Andrej730** [comment]
> The search for blender.exe doesn't show up anything. I am confused now as to why nothing shows up even though I can open Blender.

That's a mystery! You can open Blender, then find blender.exe in task manager processes and in the context menu for it, you can open it's location. Or you can open Blender and in Python Console (Scripting tab) and type `bpy.app.binary_path` to get blender.exe path.

How did you install Blender, by they way? Microsoft Store?

**Comment by Owuraqu** [comment]
Oh my! This is where I found it "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.3.0.0_x64__ppwjx1n5r4v9t\Blender". How could I have known this? However when I run the command I get the following error;
![Screenshot 2024-11-21 143702](https://github.com/user-attachments/assets/a6e7b6f6-9435-4ae9-80ba-36167ef8b575)
What could be wrong?

**Comment by Owuraqu** [comment]
> How did you install Blender, by they way? Microsoft Store?

Yes. Blender 4.2 and since then it has been automatically updating itself up to the 4.3. Thank you

**Comment by Andrej730** [comment]
@Owuraqu "Restart Blender" should work now after the latest commit, please test, when you'll have a chance to update.

Microsoft Store is kind of tricky indeed as app directory is private and it doesn't allow executing `blender.exe` directly.

Heads up to someone else also trying to setup Bonsai dev environment on MS Store Blender - it's not possible with default extensions folder in AppData and symlinks leading to other disk than the one that AppData comes from (https://github.com/python/cpython/issues/89873), example error traceback:
```
# Traceback (most recent call last):
#   File "\Blender\4.3\extensions\raw_githubusercontent_com\bonsai\__init__.py", line 314, in draw
#     binary_py = get_binary_info().get("binary_python_version")
#                 ^^^^^^^^^^^^^^^^^
#   File "\Blender\4.3\extensions\raw_githubusercontent_com\bonsai\__init__.py", line 191, in get_binary_info
#     binary = next((i for i in lib.glob("_ifcopenshell_wrapper.*")), None)
#              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "\Blender\4.3\extensions\raw_githubusercontent_com\bonsai\__init__.py", line 191, in <genexpr>
#     binary = next((i for i in lib.glob("_ifcopenshell_wrapper.*")), None)
#                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.3.0.0_x64__ppwjx1n5r4v9t\Blender\4.3\python\Lib\pathlib.py", line 953, in glob
#     for p in selector.select_from(self):
#              ^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.3.0.0_x64__ppwjx1n5r4v9t\Blender\4.3\python\Lib\pathlib.py", line 320, in select_from
#     if not is_dir(parent_path):
#            ^^^^^^^^^^^^^^^^^^^
#   File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.3.0.0_x64__ppwjx1n5r4v9t\Blender\4.3\python\Lib\pathlib.py", line 1250, in is_dir
#     return S_ISDIR(self.stat().st_mode)
#                    ^^^^^^^^^^^
#   File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.3.0.0_x64__ppwjx1n5r4v9t\Blender\4.3\python\Lib\pathlib.py", line 1013, in stat
#     return os.stat(self, follow_symlinks=follow_symlinks)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# OSError: [WinError 649] The create operation failed because the name contained at least one mount point which resolves to a volume to which the specified device object is not attached: 
# 'C:\\Users\\xxx\\AppData\\Roaming\\Blender # Foundation\\Blender\\4.3\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell'
```

**Comment by Owuraqu** [comment]
@Andrej730  I just updated and the "Restart Blender" was not successful.

**Comment by Andrej730** [comment]
> I just updated and the "Restart Blender" was not successful.

@Owuraqu Try "Restart Blender" from Debug panel.

**Comment by Owuraqu** [comment]
> @Owuraqu Try "Restart Blender" from Debug panel.

From the Debug panel the "Restart Blender" was successful.

**Comment by Andrej730** [comment]
> From the Debug panel the "Restart Blender" was successful.

Then it should work during the next update - "Restart Blender" itself needed a restart to update.

**Comment by Owuraqu** [comment]
Dear @Andrej730, I just updated Bonsai and everything is perfect now. For now, I believe this issue is closed. 
Thank you and well done:).
