### ISSUE TITLE
@ Symbol in naming sheet causes rendering to break. 

### ISSUE THREAD

**Issue by chopinregis** [IfcOpenShell/IfcOpenShell#5589]
Some interesting thing i noticed is that when i write out the name of my sheet without using a special symbol such as @, it renders well, but when i put @ in the name as a short cut for "at" as we sometimes do in architectural naming, it breaks. 
so name it like this **EAST SECTION THROUGH STAIR** works, but naming it like this **EAST SECTION @ STAIR** will break. 

View of naming without @ and it's rendering.
![Snipaste_2024-10-16_21-55-23](https://github.com/user-attachments/assets/f6e39eec-77e6-4bc7-8c43-93045ab432b6)
![Snipaste_2024-10-16_21-58-10](https://github.com/user-attachments/assets/6b80cb76-96de-4a6f-8508-0e4d6d3bd08d)

View of naming with @ and it's rendering
![Snipaste_2024-10-16_21-58-57](https://github.com/user-attachments/assets/3c67f379-c10f-4b95-a95f-86370c4e41ed)
![Snipaste_2024-10-16_21-58-16](https://github.com/user-attachments/assets/d37803a2-e74b-45ab-8f3a-fead23ec18d4)

example on another sheet. 
![Snipaste_2024-10-16_22-01-29](https://github.com/user-attachments/assets/eb518a59-42ee-4c3e-bc08-7e6b1f2a4623)
![Snipaste_2024-10-16_21-26-00](https://github.com/user-attachments/assets/74331c65-0efb-4b91-87c2-7c4a5d4ee7b1)
![Snipaste_2024-10-16_21-49-31](https://github.com/user-attachments/assets/4c996f9c-07c5-4aa2-b503-977ca3f22756)

**Comment by Andrej730** [comment]
Fixed, will need to regenerate the drawings.
