### ISSUE TITLE
SurfaceStyles on Representation Items not working for existing files after update to 241019

### ISSUE THREAD

**Issue by sboddy** [IfcOpenShell/IfcOpenShell#5604]
Blender 4.2.2, Bonsai 0.8.1-241019 (just upgraded from 241016)

I previously assigned surface styles to the representation items for all the walls in my model. Blue for rubblestone walls, green for breezeblock. It was a bit easier on the eyes distinguishing items. I updated to 241019 from 241016 and reloaded the ifc file. All of the assigned surface style assignments to representation items are now missing in the UI. Saving the file does not remove the lines in the ifc file that previously set these, so I believe the information is all still there:
![image](https://github.com/user-attachments/assets/e6cb27e7-15cb-460d-ae02-9acac309b3c7)

Select by style selects the walls that were assigned these styles. Odd. So internally the Bonsai still considers the walls styled. Just not shading them, or showing the appropriate value in the UI.

If I attempt to assign a surface a walls representation item again, it takes the value in the interface, but it does not use the colour in the 3D view:
![image](https://github.com/user-attachments/assets/db716fd3-161f-4e74-a08f-880176dbd4ca)

The value persists across reloads, but still does not shade in 3D view as expected.

If I create a simple test file from scratch, the colour _does_ appear in the 3D view:
![image](https://github.com/user-attachments/assets/15f0e3a7-b887-423b-8753-76fd31acd8b7)

**Comment by sboddy** [comment]
@Andrej730 I see in the commit log that you were touching the styling stuff quite a bit on the 16th. Unfortunately I don't know if my working 241016 build was before or after your commits, but possibly something you changed/optimized is causing this?

**Comment by Andrej730** [comment]
@sboddy no idea, please share an example file.

**Comment by sboddy** [comment]
[5604_stripped_down.ifc.zip](https://github.com/user-attachments/files/17446737/5604_stripped_down.ifc.zip)
Here you go. I stripped it back a fair bit, but the issue is still there.

**Comment by sboddy** [comment]
Aha. I figured it out. The problem styles have NEGATIVE set for the sides. If I change it to BOTH, the items are shaded once again. I'm not sure if that would still qualify this as a bug, but it is confusing when all the shades disappear.

**Comment by sboddy** [comment]
Edit the styles to be BOTH, save the file, then reopen it, and the vulgar colour scheme is back.
![image](https://github.com/user-attachments/assets/25337ea9-3b77-47d4-b3b8-27876e7cd906)

**Comment by Andrej730** [comment]
@sboddy 

1. Styles with negative IfcSurfaceStyle are not supported, started a separate issue #5618

2. I think it's a bug that when you change Side in Style attributes it wasn't updating the representation and was requiring manual update / Bonsai restart, will be fixed in the last commit.

3. Where are those NEGATIVE values for Side are coming from - were they assigned intentionally? Is there some software that does support them?

4. Regarding the style for representation item - you wouldn't be able to see since, judging from the attached files, it's not assigned to the representation item directly but through material and it's style. Though, even if it was assigned directly, you wouldn't be able to see it in the UI since it's assigned not to IfcBooleanClippingResult but to it's subitem IfcExtrudedAreaSolid. This UI is still limited and doesn't show subitems.

![image](https://github.com/user-attachments/assets/9e750978-a2cf-49a5-b03e-3d55b717e170)

**Comment by sboddy** [comment]
You know how when developing software the easiest way to see all the things that never occurred to you because it never crosses your mind that someone would try to do that, is to give it to an idiot user? I'm your idiot user in this scenario. :-)

Early on when just starting with this file I was clicking around like an untrained monkey. I'm pretty sure I remember playing around with that setting and picking NEGATIVE, and not seeing any visible effect. I think I was trying to get different surface styles on the interior and exterior of a wall, and flailing around in the UI. It just bit me in the butt when updating, because I didn't change it back to BOTH and something, somewhere in the code started behaving differently resulting in my pretty colours disappearing.

**Comment by Andrej730** [comment]
Makes sense, that's the way I learn lots of stuff too by just poking everything unknown and seeing where/if/how it breaks ☺️

I guess it's a chain of happy accidents - this issue made me curious why representations appeared different for you in 241016 and in 241019 but there were no changes directly connected to the Side thing and it helped uncover and fix another issue.
