### ISSUE TITLE
Blender model exploding at ifc export

### ISSUE THREAD

**Issue by GBWbim** [IfcOpenShell/IfcOpenShell#5607]
I am building a model with BlenderBim, but having difficulties with the resulting ifc model. Walls elements are losing their thickness and some but not all elements (buttresses and associated mouldings) are not located as shown in the blend file: Can anyone explain where I am going amiss? The only difference I could spot between the correct and incorrect elements appears to be the origin when clicked.
Here is the screenshot in church.blend:
![church_blender_241020](https://github.com/user-attachments/assets/112721a4-c558-4eec-ad51-83bfa9203175)
and here in the church.ifc file:
![church_ifc_241020](https://github.com/user-attachments/assets/a522eb0a-c230-48a2-bfc6-4f8d8f285c1d)
confirmed in Solibri:
![church_solibri_241020](https://github.com/user-attachments/assets/668c6864-c5bb-404e-883e-798c6682b5b2)

**Comment by theoryshaw** [comment]
related: https://community.osarch.org/discussion/comment/22629/#Comment_22629

**Comment by GBWbim** [comment]
Hi,

 

thank you for taking time to show how to make a type “Buttress”. These are extruded dxf polylines, but how do I make a library of construction types for selecting in the type manager. Must I first place individual (100 mm) walls, extrude and save them as types as you indicate for the buttresses? Seems odd. Why can’t the types be edited in the manager?

 

The original comment trail has become too diffuse and off-topic to repeat my original question at the end of the issue.

Regards,

 

 

: Ryan Schultz ***@***.***> 
Gesendet: Sonntag, 20. Oktober 2024 19:08
An: IfcOpenShell/IfcOpenShell ***@***.***>
Cc: GBWbim ***@***.***>; Author ***@***.***>
Betreff: Re: [IfcOpenShell/IfcOpenShell] Blender model exploding at ifc export (Issue #5607)

 

related: https://community.osarch.org/discussion/comment/22629/#Comment_22629

**Comment by theoryshaw** [comment]
Here's how to do a custom wall type:
https://www.youtube.com/watch?v=jTL3a6QwckA

I would watch his other videos to... here's one on profiles...
https://www.youtube.com/watch?v=n87fF1rF6nk

**Comment by theoryshaw** [comment]
The interface might have changed since these videos, but the concepts are there.  Just poke around the UI, you'll find them.
