### ISSUE TITLE
segfault with missing ')' character

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#5608]
This IFC file has a missing bracket here:

    #200=IFCCARTESIANPOINT((0.,0.);

[library.ifc.txt](https://github.com/user-attachments/files/17450069/library.ifc.txt)

This causes IfcOpenShell to segfault:

```
$ IfcConvert library.ifc
IfcOpenShell IfcConvert 0.8.0 (OCC 7.6.3)
Scanning file...
Done scanning file   
Segmentation fault (core dumped)
```

This is with a git snapshot from 2024-10-11

**Comment by aothms** [comment]
Thanks. Yeah the C++ parser is a bit weird, the error messages you get now for this file give a nice insight in how it permissively tries to chug along. The segfault is fixed though.

**Comment by brunopostle** [comment]
Maybe fuzzing IFC files would turn up some more segfaults..

**Comment by luzpaz** [comment]
> Maybe fuzzing IFC files would turn up some more segfaults..

Should this be a separate ticket ?

**Comment by brunopostle** [comment]
> > Maybe fuzzing IFC files would turn up some more segfaults..
> 
> Should this be a separate ticket ?

Ok, created a separate fuzzing ticket #5679 closing
