### ISSUE TITLE
Segfault on wall (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#561]
1. Convert [561--wall--segfault.ifc](https://github.com/IfcOpenShell/files/blob/master/561--wall--segfault.ifc) with 42e0058
2. Experience segfault:
```
FATAL: An error occurred, status code 139.
```
3. Opening the file in Solibri gives some hints to why:

![wall](https://user-images.githubusercontent.com/4601554/54423625-5b1aa600-4711-11e9-9bfc-29fc84475548.gif)

**Comment by YouYue123** [comment]
It converts well with IfcOpenShell IfcConvert 0.6.0a1 (OCC 7.2.0) in Ubuntu 16.04 to OBJ.

**Comment by johanrd** [comment]
Ok, interesting – thanks for checking. Still segfult on 4792fd9efe2aafdd7b6ad4d54067328041668f10 with OCCT 7.3.0.

**Comment by johanrd** [comment]
Closing, as this does not seem to segfault on 0cb2c812274d7501a5df4552f3931313280f5253 (v0.7.0) OCCT 7.3.0p3
