### ISSUE TITLE
IFC converted from DWG has issues trying to convert to XML

### ISSUE THREAD

**Issue by csritter** [IfcOpenShell/IfcOpenShell#5626]
Hi, we have projects that is a converted dwg file to ifc using ACCA Software (https://www.accasoftware.com/en/ifc-viewer)

When we try to convert to an xml, it throws an exception:
```
Scanning file...

Done scanning file   
Parsing input file took 1 second
Writing XML output...

Log:
[Warning] [2024-10-22 19:03:51] Precision lower than 0.0000001 meter not enforced
[Error] [2024-10-22 19:03:51] Type held at index 2 is 5Blank and not St6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE
```

I don't know why it's throwing exceptions, but these projects have little info.
I will send some projects with this problem to your email @aothms and @Moult.

I have not tested in Bonsai yet to see what happens.

**Comment by aothms** [comment]
Problem is the header fields with missing data such as:

```
FILE_NAME ($, '2024-10-22T13:32:58', (), (), 'ACCA_IFC.dll Version 400', $, $);
```

This is not allowed, but should still be gracefully handled. Fixed.

**Comment by csritter** [comment]
Thanks for investigate and handle it.
