### ISSUE TITLE
python-ifcopenshell in python36

### ISSUE THREAD

**Issue by bdamay** [IfcOpenShell/IfcOpenShell#563]
Hi, 

I would like to use python-ifcopenshell in a python 36 app (on windows as well a remote ubuntu server) and i can't really figure out how to do. 
Do you plan to provide a Python36 package on your download page ?  or can you tell me where to start to generate the package by myself ? (i'm not so familiar with make and Visual Studio or mingw) 

Thanks for helping

Benoit

**Comment by aothms** [comment]
The latest automatic builds include py36 versions:

master:
https://github.com/IfcOpenBot/IfcOpenShell/commit/bf1623975c6451baf3e2a1af9f32e9306d235b3f#commitcomment-32346507

v0.6.0:
https://github.com/IfcOpenBot/IfcOpenShell/commit/33cbcc25104b1084b6d184feab181b91a764eefa#commitcomment-32347576

**Comment by bdamay** [comment]
Thank you!
