### ISSUE TITLE
Error installing ifcopenshell on linux with glibc <2.35

### ISSUE THREAD

**Issue by francianeax4b** [IfcOpenShell/IfcOpenShell#5636]
Hi guys,

I was trying to install the ifcOpenShell lib using python 3.12, but it always gives this error:
ImportError: IfcOpenShell not built for 'linux/64bit/python3.12'

Are there any problems with the python version? Could anyone help me?

IfcOpenShell: 0.7.10 or 0.8.0

**Comment by Andrej730** [comment]
@francianeax4b Hi! How you installed ifcopenshell?

**Comment by Andrej730** [comment]
Tried to install it from this docker image
```
docker pull public.ecr.aws/docker/library/python:3.12-bullseye
docker run -it --name ifc_test -v "%cd%:/app" public.ecr.aws/docker/library/python:3.12-bullseye /bin/bash
cd /app
pip install -r requirements.txt
```

and got the error too, here's the full traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ifcopenshell/__init__.py", line 81, in <module>
    from . import ifcopenshell_wrapper
  File "/usr/local/lib/python3.12/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/local/lib/python3.12/site-packages/ifcopenshell/_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/ifcopenshell/__init__.py", line 83, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'linux/64bit/python3.12'
```


glibc version on this image:
```
> ldd --version
ldd (Debian GLIBC 2.31-13+deb11u11) 2.31
> ldd _ifcopenshell_wrapper.cpython-312-x86_64-lin
ux-gnu.so
./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so)
./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so)
./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so)
./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so)
./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so)
./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./_ifcopenshell_wrapper.cpython-312-x86_64-linux-gnu.so)
        linux-vdso.so.1 (0x00007fff4f570000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc792b15000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc7929d1000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc7929b7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc7927e3000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc79c16a000)
```

Though glibc version doesn't match, ifcopenshell successfully installed from pip since the wheel name suggests that it does support 2.31+. 
![image](https://github.com/user-attachments/assets/0a72daf4-a27d-4194-ab2a-55c037891dca)

So, there are 2 issues:

1) Generated wheel name is incorrect, can be updated here
https://github.com/IfcOpenShell/IfcOpenShell/blob/e27058345141f44c9a1f11bfb099cac526e61038/src/ifcopenshell-python/Makefile#L43

2) Our build don't support glibc <2.35 anymore. Testing builds from pypi, it seems that first time it occurred is in https://pypi.org/project/ifcopenshell/0.7.10/#files (when we made switch to 0.8). Not sure what happened, whether we switched to new Ubuntu version or something else. Ping @aothms 

Though now there's a caveat that if we drop support for some older version <2.35, `pip install ifcopenshell` will misleadingly install broken build on platforms using older glibc instead of throwing an error that there is no supported build or installing some old version of ifcopenshell that does support this platform,

**Comment by aothms** [comment]
> Not sure what happened, whether we switched to new Ubuntu version or something else. Ping @aothms

Yes, likely due to some feature of the code base requiring a newer gcc and I just picked an os. But likely Ubuntu is a poor choice as a build machine anyway.

Same as https://github.com/IfcOpenShell/IfcOpenShell/issues/5111

**Comment by francianeax4b** [comment]
> > Yes, likely due to some feature of the code base requiring a newer gcc and I just picked an os. But likely Ubuntu is a poor choice as a build machine anyway.
> 
> Same as [#5111](https://github.com/IfcOpenShell/IfcOpenShell/issues/5111)


In this case, Ubuntu is not a good choice. Which operating system would you recommend? Or do I wait for the release on 2024-11-02?

**Comment by aothms** [comment]
Builds succeeded and appear to be successful:

```
$ objdump -T IfcConvert | grep -Po 'GLIBC_[\w\.]+' | sort -Vu | tail -n1
GLIBC_2.27
```

https://github.com/IfcOpenBot/IfcOpenShell/commit/68062f54d8d8163d97d58ad2879c8545565cd479#commitcomment-148395598

**Comment by aothms** [comment]
Full build matrix available here https://github.com/IfcOpenBot/IfcOpenShell/commit/92b63a0ef24455e89836d02b4c9bb011b0006f2e

**Comment by Andrej730** [comment]
Can confirm that it's working on 2.31 and even on 2.28 but it does fail on 2.27, see below. But that's probably too old version to support now.

```
ldd _ifcopenshell_wrapper.cpython-310-x86_64-linux-gnu.so
./_ifcopenshell_wrapper.cpython-310-x86_64-linux-gnu.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./_ifcopenshell_wrapper.cpython-310-x86_64-linux-gnu.so)
        linux-vdso.so.1 (0x00007fff31572000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5fc2e00000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5fc2bf8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5fc29f4000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5fc266b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5fc22cd000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5fc20b5000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5fc1cc4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5fcbeee000)
```

**Comment by zaranaramani** [comment]
Release date mentioned is 2024-11-02, when will be the fix available on PyPI ?
