### ISSUE TITLE
ifcopenshell.geom.create_shape(settings, product) raises exception

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#564]
From time to time I get ifc files from Architects which have some objects which does not return a brep. 
in such cases ifcopenshell.geom.create_shape(settings, product) raises exception. Since these are special projects I am not allowed to share the ifc files not even only to the developer (project policy from the customer). But what I could is extract just this one object and send this or save it somehow to come back to this later. Such opjects I even could made public for debugging. But how do I extract the representation data. Or how is it possible to create a new ifc which contains just of one object and its representation? Is this somehow possible?

cheers bernd

**Comment by Stinkfist0** [comment]
I think someone made even a simple application/script just for this very purpose, let's see if I can find it.

**Comment by aothms** [comment]
It's actually pretty simple. You need to add the project first to a new file to get the global settings and units and then add as many elements as you like.

For example (for 0.6 branch, for master remove the `schema=` and `file(` become `open(`.

~~~
f = ifcopenshell.open(...)
g = ifcopenshell.file(schema=f.schema)
g.add(f.by_type("IfcProject"))
for x in f.by_type("IfcBuildingElement"):
   try:
       ...
   except:
       g.add(x)
g.write("errors.ifc")
~~~

**Comment by berndhahnebach** [comment]
thanks guys. This looks very very promising :) I will come back in a few days ...

**Comment by berndhahnebach** [comment]
works great! Where is best to post an ifc with such an object, here or in the forum?

bernd

BTW: sarted to use 0.6

**Comment by berndhahnebach** [comment]
> It's actually pretty simple. You need to add the project first to a new file to get the global settings and units and then add as many elements as you like.

thomas this is just awesome ... 

> ```
> g.add(f.by_type("IfcProject"))
> ```

I had to use
> ```
> g.add(f.by_type("IfcProject")[0])
> ```

**Comment by berndhahnebach** [comment]
> Where is best to post an ifc with such an object, here or in the forum?
>

**Comment by berndhahnebach** [comment]
I have one with 

`Warning: triangulateLoops, face_loops.size() == 0, IFC entity: #1941=IfcExtrudedAreaSolid
`

Which makes ifcopenshell crash with segmentation fault.

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=39&t=41600&p=354486#p354483

**Comment by aothms** [comment]
@berndhahnebach preferred place is here https://github.com/IfcOpenShell/Files/

**Comment by berndhahnebach** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/issues/744
