### ISSUE TITLE
Bonsai Error: Your model may be outdated

### ISSUE THREAD

**Issue by pimxd** [IfcOpenShell/IfcOpenShell#5641]
I cannot recover the ifc file I was working on. I was trying to copy a drawing using a dxf file as a base.
I am frustrated with the tools and interface for modeling. It would be desirable to have as soon as possible a stable version that allows modeling without losing the work done. 
Thanks for the effort to all involved!
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.8.1-alpha241024
bonsai_commit_hash: 99dc479
last_actions: 
# operator: BIM_OT_save_project
# operator: BIM_OT_save_project
# operator: BIM_OT_save_project
last_error: Traceback (most recent call last):
  File "C:\Users\JP\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 418, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JP\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 1392, in _execute
    if not scene.DocProperties.ifc_files:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'DocProperties'

ifc: R3D-ARQ-ZZZ_v0104.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha241024
originating_system: Bonsai 0.8.1-alpha241024-99dc479
```

![a](https://github.com/user-attachments/assets/210a2777-bd05-403c-81a6-117e7c993271)

**Comment by Andrej730** [comment]
Hi! It is recommented for new users not to save .blend file and just use .ifc and reload it each session. Therefore there's a warning about model going out of date, see https://docs.bonsaibim.org/guides/troubleshooting.html#saving-and-loading-blend-files

It's hard to tell when something might have gone wrong and file gone out of sync - if you have some consistent way to reproduce it, when you make a change, save file but change is not saved - please report, those issues are very important.

> AttributeError: 'Scene' object has no attribute 'DocProperties'

This kind of error typically shouldn't occur if Bonsai was enabled correctly. Are you sure there are no errors when you launch Blender with Bonsai (you can check system console in Window -> Toggle System for more details)?

**Comment by Gorgious56** [comment]
It looks like Bonsai's UI did not register correctly, I agree this looks like an addon registration problem rather than a corruption with the file

**Comment by pimxd** [comment]
Thank you for your prompt reply!
The error started when I tried to save the ifc file in blender format. I understand that to avoid errors I should only save the files in ifc format.
I reinstalled Bonsaibim and everything is working again!
