### ISSUE TITLE
IfcOpenShell not up-to-date on wikidata

### ISSUE THREAD

**Issue by luzpaz** [IfcOpenShell/IfcOpenShell#5644]
Per [![Wikidata item](https://repology.org/badge/version-for-repo/wikidata/ifcopenshell.svg)](https://repology.org/project/ifcopenshell/versions)  
Source: https://www.wikidata.org/wiki/Q67197059  

Maybe a project representative can update it ?

**Comment by piotr-smolira** [comment]
I've updated IfcOpenShell version on WikiData and set as preferred. I'm not sure how the update in repology is done.

**Comment by luzpaz** [comment]
@piotr-smolira no need to do anything else since repology automagically pulls wikidata on a daily basis. Changes will show up soon. Thanks for that. 

Closing.
