### ISSUE TITLE
Memory access out of bounds when loading IFC

### ISSUE THREAD

**Issue by monemati** [IfcOpenShell/IfcOpenShell#5646]
Hello!
I am creating a simple house using ifcopenshell-python. Below is a part of my script. Everything is okay in OpenIFCViewer but I can not load the IFC in IFCLoader or online ifc viewers. The problem is when I have 4 walls I can load IFC in IFCLoader but when I add just one more element, either wall or door or window etc, then I get memory access out of bounds and when I remove that 5th element everything is fine again. Am I missing something?

```python
def create_ifc_wall(model, body, wall_info, wall_point_left, wall_point_right, storey, wall_id):
    wall = ifcopenshell.api.root.create_entity(model, ifc_class="IfcWall" , name=str(wall_id))
    representation_wall = ifcopenshell.api.geometry.create_2pt_wall(model, element=wall, context=body, p1=(wall_point_left[0], wall_point_left[1]), p2=(wall_point_right[0], wall_point_right[1]), elevation=0, height=float(wall_info[0]), thickness=0.02)
    ifcopenshell.api.geometry.assign_representation(model, product=wall, representation=representation_wall)
    ifcopenshell.api.spatial.assign_container(model, products=[wall], relating_structure=storey) 

project = ifcopenshell.api.root.create_entity(model, ifc_class="IfcProject")
site = ifcopenshell.api.root.create_entity(model, ifc_class="IfcSite")
building = ifcopenshell.api.root.create_entity(model, ifc_class="IfcBuilding")
storey = ifcopenshell.api.root.create_entity(model, ifc_class="IfcBuildingStorey")
context = ifcopenshell.api.context.add_context(model, context_type="Model")
body = ifcopenshell.api.context.add_context(model, context_type="Model",
              context_identifier="Body", target_view="MODEL_VIEW", parent=context)

ifcopenshell.api.aggregate.assign_object(model, products=[site], relating_object=project)
ifcopenshell.api.aggregate.assign_object(model, products=[building], relating_object=site)
ifcopenshell.api.aggregate.assign_object(model, products=[storey], relating_object=building)

# Create walls
for wall in data['walls']:
          wall_info = [wall['height'], wall['width']]
          create_ifc_wall(model, body, wall_info, wall['leftmost_point'], wall['rightmost_point'], storey, wall['id'])
```

**Comment by Andrej730** [comment]
@monemati 

Please attach example .ifc files - the one that's crashing and the one that works.
It only breaks with IFCLoader? Not sure which IFC Loader you're referring to, can you please share a url and steps to reproduce the issue?

**Comment by monemati** [comment]
@Andrej730 Thank you for the reply.
Here is my ifc file (generated by ifcopenshell-python). It has 8 walls and a floor. I can open it in OpenIFCViewer but not in [IFC.JS](https://github.com/ThatOpen/engine_components) or [here](https://viewer.sortdesk.com/). 
[model-8walls.zip](https://github.com/user-attachments/files/17540646/model-8walls.zip)

**Comment by monemati** [comment]
@Andrej730 
Here is another ifc file which has 4 walls and a floor (generated by ifcopenshell-python). This one is okay in OpenIFCViewer and IFC.JS, but when I add just one more wall or door, etc, it wont open in IFC.JS.
[model-4walls.zip](https://github.com/user-attachments/files/17540700/model-4walls.zip)

**Comment by monemati** [comment]
Is it related to object placement? Because when I use `add_wall_representation` instead of `create_2pt_wall`, I can load 8 walls in IFC.JS but their origin is 0,0 and stacked together, and then when I use 'edit_object_placement' to move them (like `create_2pt_wall`??), it wont load in IFC.JS.

**Comment by monemati** [comment]
@Andrej730 
I think I found the problem by comparing my ifc file with [this](https://www.ifcwiki.org/images/e/e3/AC20-FZK-Haus.ifc). If I just change 
`#9=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#8,$);`
from [model-8walls.zip](https://github.com/user-attachments/files/17540646/model-8walls.zip)
to this
```
#198=IFCDIRECTION((0.0,0.0));
#9=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#8,#198);
```
it will load fine in OpenIFCViewer and IFC.JS.
Can you please tell me the reason? and can you please tell me how can I add something like this using ifcopenshell-python file?


I got the idea from here: (AC20-FZK-Haus.ifc)
```
#60= IFCDIRECTION((0.766044443119,0.642787609687));
#62= IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.00000000000E-5,#59,#60);
```

Am I on right track? why this IFCDIRECTION((0.0,0.0)); does not have 3 elements and just 2?

**Comment by Andrej730** [comment]
@monemati 

The last attibute is TrueNorth, see https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcGeometricRepresentationContext.htm for the description.

As you can see from the description, it is optional and IFC specify the default value that should be used if it's not provided. No idea what's the underlying issue and why it's required by IFCJS - I think you can report this to IFCJS as a bug.

>it will load fine in OpenIFCViewer and IFC.JS.

It seems to load fine in OpenIFCViewer 24.7 even without explicitly providing TrueNorth. But it still fails in https://viewer.sortdesk.com/. Couldn't test with IFCJS.

> and can you please tell me how can I add something like this using ifcopenshell-python?

I believe you can use `georeference.edit_true_north`

**Comment by monemati** [comment]
@Andrej730 Thank you so much for the information.
When I modify ifc file manually it works, but when I use `ifcopenshell.api.georeference.edit_true_north(model, true_north=(0.0,0.0))` it crashes again. In which part of code should I use `ifcopenshell.api.georeference.edit_true_north`?

**Comment by Andrej730** [comment]
> When I modify ifc file manually it works, but when I use `ifcopenshell.api.georeference.edit_true_north(model, true_north=(0.0,0.0))` it crashes again. In which part of code should I use `ifcopenshell.api.georeference.edit_true_north`?

@monemati You mean ifcopenshell crashes or ifcjs? What's the difference between files if you add it manually and when you do it using api call?

**Comment by monemati** [comment]
@Andrej730 No I meant online viewer crashes.

I just added this `ifcopenshell.api.unit.assign_unit(model)` and now I can see my ifc in online viewers too, but my windows and doors looking weird, only my door handle is visible and my window looks very small. I used is_si=True.

ps: sorry if I'm asking obvious questions.
![Screenshot from 2024-10-28 16-58-49](https://github.com/user-attachments/assets/7efa235d-8f7a-4ffe-a437-b9907717f460)

**Comment by monemati** [comment]
This is from [here](https://www.ifcwiki.org/images/e/e3/AC20-FZK-Haus.ifc)
#13= IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#14= IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#15= IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
#16= IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.);
#17= IFCMEASUREWITHUNIT(IFCPLANEANGLEMEASURE(0.0174532925199),#16);
#18= IFCDIMENSIONALEXPONENTS(0,0,0,0,0,0,0);
#19= IFCCONVERSIONBASEDUNIT(#18,.PLANEANGLEUNIT.,'DEGREE',#17);
#21= IFCSIUNIT(*,.SOLIDANGLEUNIT.,$,.STERADIAN.);
#22= IFCMONETARYUNIT('EUR');
#23= IFCSIUNIT(*,.TIMEUNIT.,$,.SECOND.);
#24= IFCSIUNIT(*,.MASSUNIT.,$,.GRAM.);
#25= IFCSIUNIT(*,.THERMODYNAMICTEMPERATUREUNIT.,$,.DEGREE_CELSIUS.);
#26= IFCSIUNIT(*,.LUMINOUSINTENSITYUNIT.,$,.LUMEN.);
#27= IFCDERIVEDUNIT((#30,#32,#34),.THERMALCONDUCTANCEUNIT.,$);
#29= IFCSIUNIT(*,.POWERUNIT.,$,.WATT.);
#30= IFCDERIVEDUNITELEMENT(#29,1);
#31= IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#32= IFCDERIVEDUNITELEMENT(#31,-1);
#33= IFCSIUNIT(*,.THERMODYNAMICTEMPERATUREUNIT.,$,.KELVIN.);
#34= IFCDERIVEDUNITELEMENT(#33,-1);
#35= IFCDERIVEDUNIT((#38,#40,#42),.SPECIFICHEATCAPACITYUNIT.,$);
#37= IFCSIUNIT(*,.ENERGYUNIT.,$,.JOULE.);
#38= IFCDERIVEDUNITELEMENT(#37,1);
#39= IFCSIUNIT(*,.MASSUNIT.,.KILO.,.GRAM.);
#40= IFCDERIVEDUNITELEMENT(#39,-1);
#41= IFCSIUNIT(*,.THERMODYNAMICTEMPERATUREUNIT.,$,.KELVIN.);
#42= IFCDERIVEDUNITELEMENT(#41,-1);
#43= IFCDERIVEDUNIT((#46,#48),.MASSDENSITYUNIT.,$);
#45= IFCSIUNIT(*,.MASSUNIT.,.KILO.,.GRAM.);
#46= IFCDERIVEDUNITELEMENT(#45,1);
#47= IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
#48= IFCDERIVEDUNITELEMENT(#47,-1);
#49= IFCUNITASSIGNMENT((#13,#14,#15,#19,#21,#22,#23,#24,#25,#26,#27,#35,#43));

How can I have this kind of units using ifcopenshell-python?
The difference between my ifc and AC20-FZK-Haus.ifc is this units and TrueNorth.

ps: AC20-FZK-Haus.ifc opens perfectly in online viewers like IFC.JS

**Comment by monemati** [comment]
I just checked my wall and it is 12000 meters instead of 12 meter. I know it is related to `ifcopenshell.api.unit.assign_unit(model)` but if I remove this, my ifc wont open in IFC.JS.

**Comment by Andrej730** [comment]
> I just checked my wall and it is 12000 meters instead of 12 meter.

I guess it's defined in millimeters and your file is using meters as the main unit.

**Comment by monemati** [comment]
@Andrej730 Now I used
```
length = ifcopenshell.api.unit.add_si_unit(model, unit_type="LENGTHUNIT")
area = ifcopenshell.api.unit.add_si_unit(model, unit_type="AREAUNIT")
ifcopenshell.api.unit.assign_unit(model, units=[length, area])
```
instead of `ifcopenshell.api.unit.assign_unit(model)` and everything is okay for now. (the previous hat MILLI as prefix)
Thank you for your guidance. Please close this issue.

**Comment by Andrej730** [comment]
@monemati please report the issues to ifcjs to help other people in the community who stumble upon this, the issues you uncovered: project fails to load without TrueNorth set and without units assigned.
