### ISSUE TITLE
Improvements to the Sheets and Drawings panes [Enhancement]

### ISSUE THREAD

**Issue by sboddy** [IfcOpenShell/IfcOpenShell#5651]
As mentioned [here](https://community.osarch.org/discussion/2562/is-it-ok-to-ab-use-sub-storeys-to-show-hide-elements#Comment_22555) I see a few areas where consistency, and ease of use could be improved. I've created this mockup for discussion, although I have edited my local files to make a number of these changes already, and it already feels better :-)
![confusingicons](https://github.com/user-attachments/assets/73edb4e3-a114-46a8-8bb4-4288c38ec2e1)
The goal is to:
1. Eliminate inconsistencies
Button position and order consistent between Sheets and drawings, divided into logical blocks
Use duplicate icon as used elsewhere
Double click in the Drawings list edits the title. Double clicking in the Sheets list does nothing. These should be aligned.
2. Use distinct icons that more clearly imply what they do
Eliminate using the same icon for different actions, and using different icons for essentially the same action
I switched the DXF icon to the outline drawing as whenever I remember seeing someone open DXF in AutoCAD it always looks outline-y to me.
3. Improve the usability (yeah, somewhat subjective)
Tuck the delete and uncommon stuff off to the left (I really didn't like the delete button next to the create sheet button.)
The blocks on the right work from left-to-right - Misc, Edit, Output, and are split using spacers.
4. Add quality-of-life improvements
On my system creating the drawings creates windows popping up and stealing focus, and are a pain to continuously shut down. This was especially true with my PDF viewer that was creating a new taskbar icon for each drawing. So I aim to make creating drawings and viewing drawings a separate button.
Also, adding selection checks to the Sheets list, and Shift-click on the Create Sheet button to create multiple sheets

Hopefully the picture is worth a thousand words too.

I can _probably_ do all of this myself, but I'd like to see if anyone has objections or prefers the way it currently works, or better suggestions.

**Comment by Andrej730** [comment]
Thanks for the image, that's really helpful. In general looks good to me. 

Though 'Mark All Drawings' icon is a bit confusing - this checkmark is usually used to confirm the changes started with the icon that's used for 'Edit Selected Drawing Title'.

What affects active drawing indicator - "Activate Selected Drawing" or "View Selected"? The icon suggests that it's "View Selected" but "View Selected" seems be just the thing that opens the drawing in the browser and it seems like "Activate Drawing" should trigger the indication.

And what 'Edit Selected Drawing Title' does? Isn't what name double-click does?
What 'Edit Sheet Layout With Command' does?

**Comment by sboddy** [comment]
> Though 'Mark All Drawings' icon is a bit confusing - this checkmark is usually used to confirm the changes started with the icon that's used for 'Edit Selected Drawing Title'.

I just thought it was more representative than SELECT_SUBTRACT. Perhaps CHECKBOX_HLT as used in the list? I only chose the CHECKMARK because I thought it would look better.
 
> What affects active drawing indicator - "Activate Selected Drawing" or "View Selected"? The icon suggests that it's "View Selected" but "View Selected" seems be just the thing that opens the drawing in the browser and it seems like "Activate Drawing" should trigger the indication.

The "active drawing" is effectively the active camera, but it isn't currently indicated anywhere. So the idea is that clicking the "Activate Selected Drawing" will set the Show Active Drawing indicator. Now you point it out, it is blindingly obvious that I've broken my own rule of overloading icons LOL. Better to make the indicator a camera icon.

An alternative is not to put the indicator in the list, and have the drawing title under the "Active Drawing" pane. I also now realise that "Create Selected / Marked Drawing(s)" should actually be "Create Active / Marked Drawing(s)"
 
> And what 'Edit Selected Drawing Title' does? Isn't what name double-click does? What 'Edit Sheet Layout With Command' does?

"Edit Selected Drawing Title" is actually a new button (it should have had an asterisk). I was trying to align how you edit the title entries between the two lists. It could be either a) add the edit button to both list panes, removing the double-click drawing title change, or b) Remove the edit button from sheets, and change it to pop up on double-clicking entries to do edits like for drawings. The key point is to be consistent across the interface. Having to learning multiple ways to do something can make an interface irritating. It's why HIG's get written.

"Edit Sheet Layout With Command" is "Open Sheet Layout" - the URL icon next to the edit icon in the original. It should probably just be "Edit Sheet Layout". It calls the "Layout SVG Command" from the prefs. It's a bit ambiguous what this does. If the command isn't set, then it uses the system default viewer, which for me is just a viewer. But the only purpose to open the layout is to edit it. Surely anyone using Bonsai seriously has set this to use Inkscape (or similar) to edit the layouts. I think there is a strong argument to be made that this button is disabled unless Layout SVG Command is set, and the tooltip changes to direct them to setting the preference.

![confusingicons](https://github.com/user-attachments/assets/c7726b67-9f91-42fa-8c0d-19e5f770bea0)

Better?

**Comment by theoryshaw** [comment]
Generally this looks good too. 

---

One question, let's say you have 60 drawings, and 30 drawings are 'checked', but you only want to run(create) one drawing?  How do you do it? 

---

Would recommend moving this here, as it's used a lot and it's consistent with the sheets layout above.

![image](https://github.com/user-attachments/assets/0d5b3690-1214-4c4f-b5f0-9527cea7c7fc)

**Comment by steverugi** [comment]
@sboddy thanks for your work, remarkable stuff
I am more into data-oriented use of Bonsai, not much into drawings, but your points look good to me
it's also encouraging others to come forward with practical ideas for improvements with mockups like you did, cheers

**Comment by sboddy** [comment]
> Generally this looks good too.
😁
> One question, let's say you have 60 drawings, and 30 drawings are 'checked', but you only want to run(create) one drawing? How do you do it?

Like now, if you left-click the button it draws the single drawing. If you Shift-left-click it draws all the selected drawings. It'll be the same for the sheets when I'm done.
 
> Would recommend moving this here, as it's used a lot and it's consistent with the sheets layout above.

I only put them (activate drawing/activate model) that way around because that was the original ordering. What you say makes sense, and I have no objection to that. Consider it done.

**Comment by sboddy** [comment]
OK, 
So here is the list of what I've done, fixed, and is all working:

[DONE] Decoupled creating and viewing drawings/sheets to avoid focus stealing popups polluting display on long batch runs.
[DONE] Added checkmarks to Sheets plus a checkmark all/none button, to do batch ops on sheets.
[DONE] Changed icons to be more consistent.
[DONE] Change button order and spacing for better usability.
[DONE] Icons set their enabled/disabled state intelligently depending on what is selected.
[DONE] All operators are now documented with standardised language and terms.
[DONE] As many operators as possible now use polling to set enabled/disabled state.
[DONE] When an operator is disabled it says why it is disabled in the tooltip.
[DONE] Add the Shift+click power move to Open Sheet.
[DONE] Add active camera indicator to the Drawing list.
[DONE] Rename core open_sheet, operator OpenSheet/bim.open_sheet to better reflect what it actually does, i.e. open_layout.
[DONE] Remove the superfluous Create and Open buttons from the Active Drawing pane.
[DONE] Add the Shift+click power move to Create Sheet.
[DONE] Add status bar Info messages for feedback on create tasks that now don't have visual feedback.
[DONE] Moved Bonsai Web UI button up to sheets toolbar.
[FIXED] Schedules and references are not incrementing the ID number properly.
[FIXED] Shift-clicking SVG-DXF conversion doesn't work - only converts selected item.

The diff is a bit beefy. Not sure if that is acceptable, or if you want me to push each thing as individual changes. I'd have to deconstruct it into discrete patches for that.

I have to say, it is much nicer with some nice power moves. :-)

There are a few things I would have like to have added, but I need to draw a line under this and get the first cut pushed.
The one thing outstanding I don't think I have the understanding for is implementing a core.duplicate_sheet function. I've looked at the duplicate_drawing function and I'm pretty certain that I don't understand the IFC stuff enough to replicate that bit for sheets. Could anyone help with that?

Here's what it looks like now:
![image](https://github.com/user-attachments/assets/3ac70fc9-caa4-4ead-adfb-9eb0bc9a8f9a)

**Comment by theoryshaw** [comment]
very cool.. is there a branch somewhere, where i can test?

**Comment by sboddy** [comment]
OK, just for you, I've pushed it into a personal branch here: https://github.com/sboddy/IfcOpenShell/tree/improve-drawing-ui

[Edit] I'm created a second "proper" branch cleverly called ui-drawing-improvements where I'm trying to break the patch down into individual commits. Nothing extra, just easier for review and merge. I'll create a pull request when I've finished teasing it apart.

**Comment by sboddy** [comment]
I found an irritating issue, but it was like that before I touched it! :-)

Whenever you expand or contract an entry in the sheet list, all the checkmarks get reset to their default (True) value. Same if you stop editing the sheets, then reopen them, although that is less of a usability issue.

The same is true of the drawing list, and I even checked without any of my changes. Still happens. I'm getting a suspicion that when the expand/contract functions call `core.load_sheets` (in turn calling `drawing.import_sheets`), it looks like that function clears all the sheets and rebuilds from the IFC representation. This is nuking the stored checkmark value.

I have no idea how to fix that. Separate bug report for someone else to look at?

**Comment by sboddy** [comment]
Never mind my last message. Was a bit tired, but fresh eyes, and taking a few minutes to properly reading import_sheets and import_drawings, it was a fairly simple fix in the end. Pushed it to the branch in the Pull Request. @theoryshaw It's not in the linked branch I first pointed you to. If you want the better behaviour test the branch in the Pull Request instead.
