### ISSUE TITLE
Launching Blender/Bonsai with an ifc file on command line exits with error.

### ISSUE THREAD

**Issue by sboddy** [IfcOpenShell/IfcOpenShell#5654]
I tried to launch Bonsai enabled Blender with an IFC file as an argument. It fails to launch with an error. Is this supposed to work?
My command is:
```
BLENDER_USER_RESOURCES=/home/steve/.config/blender/4.2bonsai /snap/bin/blender_bonsai Mill\ Cottage\ Renovations.ifc
```
This produces the error:
```
2024-10-29 16:25:23,618 INFO xmlschema Resource 'XMLSchema.xsd' is already loaded
Error: File format is not supported in file "/home/steve/Documents/Blender/BonsaiBIM/Mill Cottage Renovations/Mill Cottage Renovations.ifc"
Error: file could not be loaded, exiting! /home/steve/Documents/Blender/BonsaiBIM/Mill Cottage Renovations/Mill Cottage Renovations.ifc
Exception in module unregister(): '/home/steve/.config/blender/4.2bonsai/extensions/raw_githubusercontent_com/bonsai/__init__.py'
Traceback (most recent call last):
  File "/snap/blender/5438/4.2/scripts/modules/addon_utils.py", line 537, in disable
    mod.unregister()
  File "/home/steve/.config/blender/4.2bonsai/extensions/raw_githubusercontent_com/bonsai/__init__.py", line 262, in unregister
    bonsai.bim.unregister()
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/__init__.py", line 285, in unregister
    mod.unregister()
  File "/home/steve/.config/blender/4.2bonsai/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/geometry/__init__.py", line 162, in unregister
    km.keymap_items.remove(kmi)
RuntimeError: Error: KeyMapItem 'BIM_OT_override_object_join' not found in KeyMap 'Object Mode'
```
Blender exits, and there is no Blender window.

Nearly all of that is an exception seen whenever exiting Blender/Bonsai normally, as something fails in the exit process. I think the only relevant bits are the first two "Error:" lines.

If I omit the filename, Bonsai starts and I can open the file manually.

```
os: Linux
os_version: #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024
python_version: 3.11.7
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.2.3 LTS
bonsai_version: 0.8.1-alpha241026
bonsai_commit_hash: fc57a7b
last_actions: 
last_error: None
```

**Comment by Andrej730** [comment]
@sboddy No, it shouldn't. Use something like `blender --python-expr "import bpy; bpy.ops.bim.load_project(filepath=r'/content/roof_edit_segfault.ifc');`.

**Comment by Gorgious56** [comment]
I believe custom keymaps are not loaded in headless mode, it makes sense because you don't need key shortcuts if you don't have an interface. Maybe add a guard clause on unregistering keymaps ?

**Comment by Andrej730** [comment]
> I believe custom keymaps are not loaded in headless mode, it makes sense because you don't need key shortcuts if you don't have an interface. Maybe add a guard clause on unregistering keymaps ?

But it seems in the first post Blender is started not in background. And there also no issues unregistering keymaps in background mode on windows/linux for me.

**Comment by brunopostle** [comment]
This is a snap package, where did this come from?

    /snap/bin/blender_bonsai

**Comment by sboddy** [comment]
@Andrej730 Yes, it was a normal (headed?) startup.

As a thought, the other error could be a shortcut conflict with some other add-on. I'll try a process of elimination to see if I can confirm. Maybe the unregister needs to fail a bit more gracefully.

I think the passed python command might need tweaking for the desktop file., and is a bit hard to remember everytime. Using it as is in the Exec command will need to also work when _not_ passed a file. Something like (not tested):
```
blender --python-expr "filepath=r'%f'; if filepath: import bpy; bpy.ops.bim.load_project(filepath=filepath);"
```

@brunopostle 
> This is a snap package, where did this come from?
> 
> ```
> /snap/bin/blender_bonsai
> ```

```
blender_36lts                         3.6.17                      5437   3.6lts/stable    blenderfoundation✓  classic
blender_42lts                         4.2.3                       5438   4.2lts/stable    blenderfoundation✓  classic
blender_bonsai                        4.2.3                       5438   4.2lts/stable    blenderfoundation✓  classic
blender_edge                          4.4.0                       5486   latest/edge      blenderfoundation✓  classic
blender_stable                        4.2.3                       5438   latest/stable    blenderfoundation✓  classic
```
Yes, I have FOMO (Fear Of Missing Out). Snaps allow you to have multiple installs of versions, just by passing the --name parameter. I wanted the ability to run vanilla 4.2 LTS so I installed two instances of it, calling one of them blender_bonsai. In the end it turns out that that is _probably_ redundant. I could just have copied the desktop icon of 4.2 and added the BLENDER_USER_RESOURCES environment variable to the normal exec line. This would have kept the two configurations completely separate too.

**Comment by Andrej730** [comment]
> I think the passed python command might need tweaking for the desktop file., and is a bit hard to remember everytime. Using it as is in the Exec command will need to also work when _not_ passed a file. Something like (not tested):

You might want to check out this
![image](https://github.com/user-attachments/assets/941c54b7-7347-4ff9-8a03-2f2d2de5771f)

**Comment by brunopostle** [comment]
Ah, I saw 'blender_bonsai' and thought it was a snap that bundles blender *and* bonsai (which might be a thing some day).

The register operation should support multiple parallel blender installs, but the registration itself should only ever point to one of them at any time.
