### ISSUE TITLE
Bug: Elevation in IfcBuildingStorey at Panel Spatial Decomposition

### ISSUE THREAD

**Issue by hardhiraf** [IfcOpenShell/IfcOpenShell#5655]
I was creating IfcBuildingStorey using Panel Spatial Decomposition and changing the Elevation. But after I create another IfcBuildingStorey, the elevation is reset to 0

https://github.com/user-attachments/assets/65c772d0-bd32-4fbe-a8fd-0ee317b7841f

**Comment by sboddy** [comment]
What version are you running? I'm using the nightlies and this is working for me. I recall it was an issue in 0.8.0.

**Comment by hardhiraf** [comment]
yes, I'm using version 0.8.0 because I just installed it from Blender repository website.

**Comment by hardhiraf** [comment]
Closed. Installing the extension using the bonsai GitHub repository, not the extension.blender website
