### ISSUE TITLE
Convert using cgal causes segmentation fault - opencascade works

### ISSUE THREAD

**Issue by csritter** [IfcOpenShell/IfcOpenShell#5665]
Hi, I tried to convert a file with cgal, but kills the process and throws a segmentation fault.
Running with opencascade works normally.
@aothms, I will send the file with this issue in private.

Let me know if I can help with anything else or if you need more info.

**Comment by Moult** [comment]
BTW you can share privately at this link: https://forms.gle/4awba717Ne17BSr16 so all devs working on C++ in IfcOpenShell can access it privately.

**Comment by csritter** [comment]
Hi @Moult, thanks for sharing this, I sent the file through the link.

**Comment by csritter** [comment]
I sent another file that throws the exception early.

**Comment by aothms** [comment]
For me it didn't crash, but got stuck processing a self-intersecting really strange (non-polygonal!) polygonal halfspace. Hope that was the issue.

**Comment by csritter** [comment]
Maybe I didn't get the last commits. 
Takes a little time, but yes, works.
I close this issue for now.
