### ISSUE TITLE
Convert a file has infinite process on cgal and opencascade

### ISSUE THREAD

**Issue by csritter** [IfcOpenShell/IfcOpenShell#5672]
Hello, I will send a file in which the process does not finish. I sent it there through the form.

**Comment by csritter** [comment]
I sent another file and in addition to sending it to the forms, I sent the models to the email.

If you could take a look, I would appreciate it.

Update:

1 - Sorry, the 15MB file throws an exception and does not have an infinite process

In a software returns
Line 87378 Non optional member set as null on attribute AssemblyPlace.
But still, opens the file.
Is there a way to avoid this or change the file to work on the IfcConvert?

2 - Getting the last commits, the 85MB file still has an infinite process

**Comment by aothms** [comment]
>  Line 87378 Non optional member set as null on attribute AssemblyPlace.

That wouldn't come from IfcConvert.

> 2 - Getting the last commits, the 85MB file still has an infinite process

Yes, that was an interesting problem tripping up the shared representation detection. Can't say that the file works particularly well now, memory usage and processing time is quite high, but it improved a bit.

**Comment by csritter** [comment]
It has been tested and works now. Thanks, @aothms!
Closing this issue.
