### ISSUE TITLE
Bonsai IfcSite RefLatitude/RefLongitued cannot be saved

### ISSUE THREAD

**Issue by andreas0123** [IfcOpenShell/IfcOpenShell#5678]
Hi,
I wanted to try the new sun position feature. I understand that I should store the Long/Lat values as IfcSite Attributes for the tool to pick them up. When trying to enter and save the attribute values (tried different formats like 49.01.14 or 49,01,14 or 49'01'14) they just vanish after the save. Reopening the IfcSite Attributes again shows the fields empty again. This can be observed in a newly created Ifc project as well as existing ones. All other attributes can be changed and saved, though. Am I doing something wrong here or is this an issue with Bonsai?
Below picture shows the panel after saving and reopening with the coordinate values missing.
![image](https://github.com/user-attachments/assets/f73884a6-9646-4ae1-b705-b78bb8776cd1)

**Comment by sboddy** [comment]
The format is:
```
[degrees, minutes, seconds]
```
Each number should have the same sign. i.e. If you are west of UTC, all numbers must be negative.
(If you right click an element it has a link to the IFC documentation often which is where I found this info.)

**Comment by andreas0123** [comment]
Hi sbody,
thanks for your kind response. I didn't realize before that I have to input the brackets as well. Sorry to bother you with this misunderstanding.
Best regards
Andreas
