### ISSUE TITLE
file.py, function file.add(inst) to a new ifc file, id in tuple can't be transformed

### ISSUE THREAD

**Issue by hypotenuse345** [IfcOpenShell/IfcOpenShell#568]
Hello! I have some problem with ifc generation. When I was trying to extract the geometry of elements like wall from a existing ifc file to a new ifc file, I used the function ifcfile.add(wall) but some mistakes appeared in the output ifc. I checked the file and found out that some id numbers of the entity had been changed successfully while the id numbers in tuples could't be changed. Has anyone of you guys had this problem before?

**Comment by aothms** [comment]
What version of IfcOpenShell are you using? I vaguely remember some issues with that in the past, but recent versions like [1] hopefully no longer have this issue. So try with the latest version, if the issue persist please provide more detailed steps to reproduce.

[1] https://github.com/IfcOpenBot/IfcOpenShell/commit/bf1623975c6451baf3e2a1af9f32e9306d235b3f#commitcomment-32346507

**Comment by hypotenuse345** [comment]
> What version of IfcOpenShell are you using? I vaguely remember some issues with that in the past, but recent versions like [1] hopefully no longer have this issue. So try with the latest version, if the issue persist please provide more detailed steps to reproduce.
> 
> [1] [IfcOpenBot@bf16239#commitcomment-32346507](https://github.com/IfcOpenBot/IfcOpenShell/commit/bf1623975c6451baf3e2a1af9f32e9306d235b3f#commitcomment-32346507)

Thanks for your advice!! I try the latest version of ifcopenshell and it works eventually ^_^.
