### ISSUE TITLE
infinite processing time

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#5684]
The attached IFC files cause IfcConvert to process forever (created with fuzzing see #5679).

[timeouts.zip](https://github.com/user-attachments/files/17607719/timeouts.zip)

Note that these fuzzed files each have multiple syntax errors

**Comment by aothms** [comment]
Thanks for this @brunopostle

What was eventually happening was:

```
#193=IFCDIRECTION((0.));
```

- causing a singular matrix
- causing nan values in edge vertices
- causing an infinite recursion in opencascade trying to orient the vertices
