### ISSUE TITLE
Measure tool - Add visual feedback to plane lock

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#5690]
The Measure tool has a feature that locks the mouse to a plane, similar to Blender's transformation behavior when using Shift + X, Y, or Z. However, currently, it lacks visual feedback. The Measure tool should mimic Blender's behavior by highlighting the axes that correspond to the locked plane.

**Comment by brunoperdigao** [comment]
Besides the highlight, the plane method for measure tool is now working with object snap:


https://github.com/user-attachments/assets/bfe8617a-92a6-4c37-8061-11af5c703e28

**Comment by theoryshaw** [comment]
works great!

Let's say you lock to the XY plane, how do you turn it off, mid operation?

**Comment by brunoperdigao** [comment]
I can't test right now, but it should be by pressing "shift + z" again.
