### ISSUE TITLE
Costing and Scheduling malfunctioning with 241104 release

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5692]
https://github.com/user-attachments/assets/a713f6d2-cb77-497e-a988-dd71b931e95f

thanks

**Comment by BIMvoice** [comment]
Hey @Andrej730 do you have any idea why this is happening? Is it difficult to fix?

**Comment by Andrej730** [comment]
Should be fixed after 534355c.

**Comment by steverugi** [comment]
@Andrej730 just installed the latest and now everything is back to normal
much appreciated
