### ISSUE TITLE
Resource usage decimals - Cost calculation  

### ISSUE THREAD

**Issue by DimitriosThe** [IfcOpenShell/IfcOpenShell#5693]
Say we have a Labor resource tha is as follows:
Code   - Description                                                              - U.M. - Quantity
19931 - Labor Assembly Construction service worker cat.3  - hr    -  0.003
has 0.003 hrs of usage but if you place that value in the resource base quantity
![image](https://github.com/user-attachments/assets/479303c4-e300-43e6-9a71-003da0034298)

the result will be a 0

![image](https://github.com/user-attachments/assets/2ca6ad34-6cc1-4fa6-a0cd-f1a3b6e19807)

and by updating the resource in the cost schedule:

![image](https://github.com/user-attachments/assets/afa05cdb-6827-4be5-b4c2-1f95de385b5d)

the result is again 0

Blender 4.2.3/ Bonsai 0.8.0

**Comment by DimitriosThe** [comment]
Merged to #5706

**Comment by Andrej730** [comment]
Same issue as #5706
