### ISSUE TITLE
Error when opening BuildingSmart test files (Unsupported schema: IFC4X3_RC2)

### ISSUE THREAD

**Issue by argenos** [IfcOpenShell/IfcOpenShell#5694]
Trying to open any file in the [BuildingSMART test files IFC4x3](https://github.com/buildingSMART/Sample-Test-Files/tree/master/IFC%204.3) causes an error:

```
os: Darwin
os_version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:00:32 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6030
python_version: 3.11.7
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 4.2.3 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_activate_external_style
# operator: BIM_OT_load_type_thumbnails
last_error: Traceback (most recent call last):
  File "/Users/argen/Library/Application Support/Blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/project/operator.py", line 746, in finish_loading_project
    context.scene.BIMProjectProperties.total_elements = len(tool.Ifc.get().by_type("IfcElement"))
                                                            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'by_type'
```

**Comment by piotr-smolira** [comment]
Same here on Windows:

```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.2.3 LTS
bonsai_version: 0.8.1-alpha241104
bonsai_commit_hash: 6729739
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 780, in finish_loading_project
    context.scene.BIMProjectProperties.total_elements = len(tool.Ifc.get().by_type("IfcElement"))
                                                            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'by_type'
```

**Comment by csritter** [comment]
In the last build on IfcOpenBot\IfcConvert, it throws me this exception:
![image](https://github.com/user-attachments/assets/4b929185-834f-4426-82c6-37212732852a)

And the 0.7.0 conversion works but...

This is the BimVision mesh:
![image](https://github.com/user-attachments/assets/ec912bdd-a18b-4756-8c9a-0ce5ed2867e3)

This is the IfcConvert mesh result:
![image](https://github.com/user-attachments/assets/49de736a-3704-407a-9986-25347c615dbd)

File tested is UT_Tin_1.ifc

**Comment by RickBrice** [comment]
Many of these files don't have a valid schema. If you change the schema to IFC4X3_ADD2, you can get some of the files to load.
bSI should go through an effort to update these files.

**Comment by csritter** [comment]
@RickBrice throws an error which IFCSOLIDSTRATUM not found
![image](https://github.com/user-attachments/assets/9eaf8abb-1972-4205-a610-9acbff577489)

In Bonsai works?

**Comment by RickBrice** [comment]
@csritter IfcSolidStratum isn't part of IFC4X3_ADD2 - not all files can be easily fixed by simply changing the schema designation.

It looks like IfcSolidStratum was replaced with IfcGeotrchnicalStratum.PredefinedType = IfcGeotechnicalStratumTypeEnum.SOLID

RC4 and ADD1 files usually have good luck. RC2 and RC3, ok but some problems. RC1 - it's a bit harder since there were more changes.

**Comment by Andrej730** [comment]
The full error also have
```
Failed to load file ../UT_GeoRef_1.ifc. Error details: Unsupported schema: IFC4X3_RC2
Failed to load file ../UT_GeoRef_1.ifc. Error details: Unsupported schema: IFC4X3_RC2
```

Indeed, building smart files are using one of the release candidate schema and it's not included in ifcopenshell. Changing it manually to `IFC4X3_ADD2` might work for some cases but it all depends on the changes that buildingsmart added/reverted towards the release.
