### ISSUE TITLE
Bonsai simple wall opening doesn't work

### ISSUE THREAD

**Issue by mmujicPCAD** [IfcOpenShell/IfcOpenShell#5695]
Tried to load an IFC project into blender with bonsai addon, however none of the wall openings seem to work. I narrowed it down to a single wall and opening and attempted to manually change certain parts of file to see if I can get it to work, however no luck. It does seem to detect the IfcOpeningElement but it doesn't have any geometry. Tried other software as well and there it works without problems. Any idea what the problem is?

[single_wall_opening.zip](https://github.com/user-attachments/files/17634525/single_wall_opening.zip)

**Comment by Andrej730** [comment]
@mmujicPCAD this IFC is invalid, from what software does it comes from?

You can run ifc validation on this file
![image](https://github.com/user-attachments/assets/0fd3db0e-7b39-4c31-a5b8-db3c45f8a850)

And it shows that opening's representation is missing the context which is required in IFC, therefore this representation is not recognized.
```
2024-11-06:11:23:16,799 ERROR   [rule_executor.py:251] On instance:
    #41774=IfcShapeRepresentation($,'Body','Brep',(#41819))
Rule IfcShapeRepresentation.WR21:
    ('ifc2x3.ifcgeometricrepresentationcontext' in typeof(self.ContextOfItems))
Violated by:
    ('ifc2x3.ifcgeometricrepresentationcontext' in set())
     +  where set() = typeof(None)
     +    where None = #41774=IfcShapeRepresentation($,'Body','Brep',(#41819)).ContextOfItems
Info: Check validation results in the system console.
```

As a one-time-solution you can change the line in ifc file to this, to make it use model/body/model_view context.
```
#41774=IFCSHAPEREPRESENTATION(#111,'Body','Brep',(#41819));
```

But the real question is how file got invalid in the first place. If it's some other software issue, it should be reported there, to avoid this issue occurring in the future. Maybe there is some setting that needs to be changed exporting IFC from that software.

**Comment by mmujicPCAD** [comment]
Sorry for the late reply, it was from an external software. I reported it and they fixed it. Thanks for the info on the validation feature!
