### ISSUE TITLE
support for IFC Alignment

### ISSUE THREAD

**Issue by jjkaelin** [IfcOpenShell/IfcOpenShell#570]
I work in civil engineering infrastructure and am exploring the use of IFC Alignments for getting data from CAD/BIM into the python ecosystem for spatial and data analysis. Will ifcOpenShell be supporting IFC Alignments in the near future? 
(I get 
RuntimeError: Unable to find find keyword in schema
for
file.by_type("IfcAlignment")
)
Thanks in advance for your advice.

**Comment by aothms** [comment]
Starting from the 0.6 branch arbitrary schemas can be selected at runtime. So yes, I do envision that at some point these schemas get added. I know that @SigveMartin did some tests with IFC4X2, i.e. bridge in #505. Apart from generating the code from the schema, which is mostly an automated process, the most effort of course is in mapping the geometry definitions to code paths (which might not be what you need for your usecase, if you just need parsing it'll be a whole lot simpler). Since the geometries are quite different from regular step (which Open CASCADE is modelled after to a large extent) that might be a little bit more involved. I will happily offer assistance and merge the all work towards infrastructure schema support into the codebase, but I will likely not drive this effort myself.

**Comment by jjkaelin** [comment]
Thanks for the quick response! I am optimistic that we can get Alignment working with IfcOpenShell.
My needs are only for parsing with IfcOpenShell.
Just a quick response for now to get me pointed in the right direction:

1) I have been bumping into some confusion with the IFC Express versions. 
https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/EXPRESS/IFC4x1.exp
-> includes IFC Alignment
you reference (which looks equally valid to me) is
http://www.buildingsmart-tech.org/ifc/IFC4/Add1/IFC4_ADD1.exp
-> does not include IFC Alginment 
I just pass this along to try and sort out the associated version confusion with IFC4.

2) "Starting from the 0.6 branch arbitrary schemas can be selected at runtime"
Does this refer to the  python bootstrap.py .....  procedure used in #505 ? 
Or am I missing something and there is a python way to select the IFC schema?? 
Or do you mean something else?

3) If I only need to build IfcOpenShell (I am trying to avoid ;) as it's been quite some time since I have used make, but should be manageable), what are the prerequisites? Do I need to build OCE first (sounds like more effort)?

Thanks for any help you can pass my way.

**Comment by aothms** [comment]
1. This can indeed be confusing, but IFC4_ADD1 is not at all the same as IFC4X1.

2. Indeed that's the procedure. The difference between master and 0.6 is that in master there can only be one schema in the binary a schema which is built using the python code generator. But the code generation procedure using python is more or less the same,

3. You can use the build-script https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.py to have a fully automated build of all dependencies (single command but takes a while indeed) or use the package manager, e.g. occt 7.3. from https://launchpad.net/~freecad-community/+archive/ubuntu/ppa

**Comment by jjkaelin** [comment]
Thanks, that is all quite helpful.

1. ok, sorted it out
    for anyone interested, see  
    http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0.1/html/link/ifc4-add1-to-ifc4x1.htm

3. I installed icfopenshell on ubuntu 16.04 using the package manager at the ppa you referenced. It installed without errors and appears to run (e.g. IfcConvert runs, python -> import ifcopenshell is ok).
As I understand this is a 0.6 beta installation.

2. I am stuck however, as to how I can select the IFC4 ADD1 to IFC4x1 schema at runtime for ifcopenshell. The python bootstrap.py ..... procedure used in #505 requires the source file, which I do not yet have. 
Am I missing something?
Or do I indeed need to go the build-script route you mentioned, if I want to use the IFC4 ADD1 to IFC4x1 schema?

**Comment by aothms** [comment]
> requires the source file

Which source file do you mean?

The code generator takes the .exp as input and generates a whole bunch of .cpp and .h files. These have to be provided at compile time (and the resulting code can be selected at runtime). It's not the case that you can provide the actual .exp file at runtime.

**Comment by Noranius** [comment]
I want to work with the new ifc 4x2 draft (https://buildingsmart.sharefile.com/share/view/s619ceb7623d4b099/fod4202e-f039-49d7-8e4e-cddabe6efd3c) I could manage to build the cpp and header files, which are in the ifcexpressparser directory now. How can i build now ifcOpenShell with that additional code? Shall i move them somewhere or need the compiler a additional parameter?

Thank you in advance for you help.

**Comment by aothms** [comment]
> Shall i move them somewhere or need the compiler a additional parameter?

Getting them to compile is actually trivial, the CMake script just has a glob [1] which means that whatever you put in the src/ifcparse/ directory will be picked up.

What is not entirely working yet is a variable amount of schemas in the codebase. Right now the amount of schemas is hardcoded to the 2x3 and 4 schemas [2]. So this you'll need to adapt this manually for the time being (there's also a couple of places in ifcgeom/ and CMake itself, but maybe save that for later, as there are no geometry conversion functions in ifcgeom for alignments now anyway).

It shouldn't be that hard to have CMake generate the necessary bits of code for this and send them as preprocessor directives to the compiler. For that CMake should be able to inspect the header files in ifcparse and see which ones are IFC schemas. I will reserve some time for that next week.

Is this enough to help you move forward on this for the time being?

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/cmake/CMakeLists.txt#L550
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcSchema.cpp#L65

**Comment by Noranius** [comment]
Thank you. I could successfully build ifcOpenShell with the new IFC 4x2.

As you mentioned I edited the src/ifcparse/ifcScheme.cpp to add the additional header files.

**Comment by SigveMartin** [comment]
@Noranius could you share the python package from the build? Do you have it for python 3?

**Comment by Sara-GO** [comment]
Hi @Noranius ,
Ph.D. student working on IFC for infrastructure, currently trying to be able to use IfcOpenShell - IFC 4x2 inside FreeCAD. 
I really enjoyed following this discussion and in your last post you mentioned you got it!! 
So I was wondering (pretty please) if you can share here the Python Package also asked by @SigveMartin.  We'll pay in coffee :)
Sara

**Comment by atibaut** [comment]
Hi all (@Sara-GO, @Noranius, @SigveMartin),
I would really support the idea of sharing the Python package with all of us.

**Comment by atibaut** [comment]
Hi all (@Sara-GO, @Noranius, @SigveMartin),
with the help from
http://academy.ifcopenshell.org/using-ifcopenshell-and-c-to-generate-alignments-through-the-ifc-4x1-schema/
using the command
python3 bootstrap.py express.bnf > express_parser.py && python3 express_parser.py IFC4x2.exp
I have compiled the IFC 4x2 schema to generate the necessary C++ files:
Ifc4x2-latebound.cpp
Ifc4x2-latebound.h
Ifc4x2.cpp
Ifc4x2enum.h
Ifc4x2.h
available in the zip file 
[ifc4x2.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/3298719/ifc4x2.zip)
Now, I have a problem to o build the IfcOpenShell on my Mac OS X. Perhaps one of you can do it on Windows and then share the Python package.

**Comment by aothms** [comment]
> Perhaps one of you can do it on Windows and then share the Python package.

That won't work. The python module is mostly a compiled c++ binary. Tell
you what: if you create a pull request to add those files into the ifcparse
folder of the 0.6 branch, I will tie thing together and provide builds.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op ma 17 jun. 2019 22:28 schreef Andrej Tibaut <notifications@github.com>:

**Comment by atibaut** [comment]
Hi @aothms,
yes, you are right, the binary is platform dependent and the one built for Windows wont work on i.e. my  Mac OS X. I will create a pull request for that. Great, than we can download builds for our platforms.

**Comment by atibaut** [comment]
Pull request created.

**Comment by Noranius** [comment]
Sorry guys fo the long abstinence :(
I created the pull request, too.

**Comment by atibaut** [comment]
Thanks @Noranius, I am glad we woke you up. :-)

**Comment by Moult** [comment]
Alignments are now supported https://github.com/IfcOpenShell/IfcOpenShell/discussions/5102
