### ISSUE TITLE
Installation of Bonsai in Blender on Linux (Blender with Python 3.12)

### ISSUE THREAD

**Issue by akagohary** [IfcOpenShell/IfcOpenShell#5704]
hello people, an architect here trying to tryout bonsai.

i've tried to install the extention through the extention manager in blender and it shows this

![image](https://github.com/user-attachments/assets/e6c290b6-62ad-4f00-a115-877c6994bff9)

- i tried to uninstall blender and all its dependencies deleted all things related to blender in my .cache and .local folder, installed it again it didn't work

- i tried to manually install ifcopenshell in /usr/lib/python3.12/site-packages/ifcopenshell that didn't work either

- i tried to manually install ifcopenshell in ~/.local/lib/python3.12/site-packages/ifcopenshell that didn't work

- i tried to manually install ifcopenshell in /home/$USER/.config/blender/4.2/extensions/.local/lib/python3.12/site-packages/ that didn't work but i could import ifcopenshell and query its version in blender python

![image](https://github.com/user-attachments/assets/2a9ee900-7f26-4529-88e8-b0e4ce41cf0f)

![image](https://github.com/user-attachments/assets/f6dbde33-fc63-4c1c-8e8b-58df1cc556bb)

**Comment by Gorgious56** [comment]
Blender 4.2 supports python 3.11, not 3.12 AFAIK

**Comment by akagohary** [comment]
> Blender 4.2 supports python 3.11, not 3.12 AFAIK

the screenshot i posted is from blender python scripting tab, it says 3.12.7 or does that indicate my system's python version?

+ it says expected 3.12 got 3.11, if that was the case it should be happy with it being 3.11 lol.

**Comment by brunopostle** [comment]
It looks like you are using the blender that comes with your Linux distribution (which has a newer python). The Bonsai extension works with the blender that you can download from blender.org

**Comment by Andrej730** [comment]
You can either use Blender from Blender.org that will use Python 3.11 (the one that comes with Blender by default and the only one supported by Blender extensions) or keep Blender with Python 3.12 and use one of the Python 3.12 releases from https://github.com/IfcOpenShell/IfcOpenShell/releases.

**Comment by akagohary** [comment]
> You can either use Blender from Blender.org that will use Python 3.11 (the one that comes with Blender by default and the only one supported by Blender extensions) or keep Blender with Python 3.12 and use one of the Python 3.12 releases from https://github.com/IfcOpenShell/IfcOpenShell/releases.

Thank you, i installed the zip file and installed form local file and it worked.

but i just wanna say i tried the repo to get the unstable version through blender and it installed i believe the py311 one since it didn't work, how about adding a mechanism of some sort to check for the python version and install py312 or py311 accordingly

also when i added the addon it installed but gave me a message that shapely.lib is missing, although i do have python-shapely installed through my distro's package manager, what would be the cause of that?.

**Comment by Andrej730** [comment]
@akagohary 

> but i just wanna say i tried the repo to get the unstable version through blender and it installed i believe the py311 one since it didn't work, how about adding a mechanism of some sort to check for the python version and install py312 or py311 accordingly

I've changed the error message so it will be more clear but we cannot modify the way Blender extensions work - they only support 1 Python version.

> also when i added the addon it installed but gave me a message that shapely.lib is missing, although i do have python-shapely installed through my distro's package manager, what would be the cause of that?.

Share the exact error message please. Please include more logs before/after error message, they also can be related.

**Comment by akagohary** [comment]
> Share the exact error message please. Please include more logs before/after error message, they also can be related.

i tried to recreate it by disabling renabling the addon, didn't popup, now i tried to uninstall and delete config then reinstall but i got another error but this time once again making the addon unable to be enabled unlike the shapely.lib which allowed the addon to be active

`module 'ifcopenshell.util.schema' has no attribute 'IFC_SCHEMA'`

fyi, my distro just pushed a blender update during me trying this so maybe a new blender version is bricking the addon in a new way.

also i tried to fetch you more info but thats all i get from the GUI like error log in blender "info" tab, idk how to dig deeper for more error info, if you have a clue i'd be grateful, thank you.

**Comment by Andrej730** [comment]
> module 'ifcopenshell.util.schema' has no attribute 'IFC_SCHEMA'

There should be a full traceback to these errors, it would give us more clues.
Also, please try the clean environment. E.g. you can rename your `4.2` Blender's folder with all extensions and settings to `x.x` and try to install Bonsai to see if there are still any issues.

**Comment by akagohary** [comment]
> > module 'ifcopenshell.util.schema' has no attribute 'IFC_SCHEMA'
> 
> There should be a full traceback to these errors, it would give us more clues. Also, please try the clean environment. E.g. you can rename your `4.2` Blender's folder with all extensions and settings to `x.x` and try to install Bonsai to see if there are still any issues.

i started blender with --log-level 2 from cmd

this is what i get when i install the addon

```
/usr/lib/python3.12/site-packages/ifcopenshell/file.py:412: SyntaxWarning: invalid escape sequence '\d'
  reg = "".join(f"(?P<{s}>{s}\d+)?" for s in prefixes)
/usr/lib/python3.12/site-packages/ifcopenshell/express/bootstrap.py:207: SyntaxWarning: invalid escape sequence '\('
  print("""
Exception in module register(): /home/gohary/.config/blender/4.2/extensions/user_default/bonsai/__init__.py
Error: module 'ifcopenshell.util.schema' has no attribute 'IFC_SCHEMA'

```

EDIT: hmmm i deleted /usr/lib/python3.12/site-packages/ifcopenshell and the addon is now working fine without any complains

**Comment by Andrej730** [comment]
> EDIT: hmmm i deleted /usr/lib/python3.12/site-packages/ifcopenshell and the addon is now working fine without any complains

For now but I assume you have some older ifcopenshell version installed in `/usr/lib/python3.12/site-packages` which was the reason `module 'ifcopenshell.util.schema' has no attribute 'IFC_SCHEMA'`. You need to ensure to use the same ifcopenshell version Bonsai is using in it's build to avoid further issues.

**Comment by akagohary** [comment]
> > EDIT: hmmm i deleted /usr/lib/python3.12/site-packages/ifcopenshell and the addon is now working fine without any complains
> 
> For now but I assume you have some older ifcopenshell version installed in `/usr/lib/python3.12/site-packages` which was the reason `module 'ifcopenshell.util.schema' has no attribute 'IFC_SCHEMA'`. You need to ensure to use the same ifcopenshell version Bonsai is using in it's build to avoid further issues.

oh good tip, thank you so much for helping. please feel free to close the issue or do as you see fit, i believe all my questions are now answered, hope i can be back soon to contribute to this cool project both on the ifcopenshell and bonsai fronts.

also, if you could point me towards where to find the same ifcopenshell version lets say for the latest unstable py312 version where would i look to find the latest ifcopenshell to match with the bonsai one, thank you.

**Comment by Andrej730** [comment]
> also, if you could point me towards where to find the same ifcopenshell version lets say for the latest unstable py312 version where would i look to find the latest ifcopenshell to match with the bonsai one, thank you.

@akagohary zip release files for Bonsai have a folder with wheels, it's probably the most straightforward way to find the best build for the current version. You can also find one in https://github.com/IfcOpenBot/IfcOpenShell commit comments but sometimes it might be not exactly the one that comes with Bonsai.
