### ISSUE TITLE
Duplicating the member of an array with SHIFT + D causes an error and an un-deletable duplicated arrayed element

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#5705]
Brand new file
Add element
Add an array
Duplicate the arrayed element
Error
The duplicated element can't be deleted since it is still linked to the source element

Test file :

[untitled.ifc.txt](https://github.com/user-attachments/files/17648914/untitled.ifc.txt)

Solution : Prevent user from duplicating an arrayed element OR sever the link to the source of the array

**Comment by theoryshaw** [comment]
I like the idea of 'severing' the link. 

This used to be possible...
https://github.com/IfcOpenShell/IfcOpenShell/issues/2935

**Comment by Andrej730** [comment]
Will be fixed in the next commit.
