### ISSUE TITLE
BONSAI - 5D - Resource cost calculation discrepancy

### ISSUE THREAD

**Issue by DimitriosThe** [IfcOpenShell/IfcOpenShell#5706]
Say we have a Crew resource that is as follows:

![image](https://github.com/user-attachments/assets/e261c124-2da6-4d50-9a78-7825ba6cd462)

We assign the constituent resources included in that crew resource in a cost article:

![image](https://github.com/user-attachments/assets/9e36a522-870e-4163-8eab-9893fde462d0)

as seen the total of the sums of the constituents after assigning is 2,62 but in the resource panel it is 

![Crew Resource 2024-11-06 171319](https://github.com/user-attachments/assets/7728724e-8308-49d8-a960-c139f0271ee7)
 3,58!

I ve double checked the numbers within the resource panel (quantity and cost assignments)

**Comment by DimitriosThe** [comment]
I believe the value in the "calculate_cost_item_resource_value.py" from api>cost has to be modified in the section 

```
quantity = ifcopenshell.util.resource.get_quantity(resource)
        if not cost or not quantity:
            continue
        if unit and "day" in unit:
            quantity = quantity / 8  # Assume 8 hour working day - TODO implement resource calendar
        **`quantity = round(quantity, 5)`**
```

**Comment by Andrej730** [comment]
@DimitriosThe hi! Can you please share the project for debugging? If you don't want to share it publicly, you can send it privately to my email from the profile.

**Comment by DimitriosThe** [comment]
Hi Andrej,

after using the comment from above where 

> I believe the value in the "calculate_cost_item_resource_value.py" from api>cost has to be modified in the section
> 
> ```
> quantity = ifcopenshell.util.resource.get_quantity(resource)
>         if not cost or not quantity:
>             continue
>         if unit and "day" in unit:
>             quantity = quantity / 8  # Assume 8 hour working day - TODO implement resource calendar
>         **`quantity = round(quantity, 5)`**
> ```

the issue was resolved. that means that the resource schedule is calculated correctly but when transposed to the cost schedule it has to be through the use of the decimals rounding.  

here is the resources total cost when inserted one by one 

![image](https://github.com/user-attachments/assets/904cdbc1-ef62-4947-b869-c71bca76e423)

Here you can see the details (the calculation of quantity resource * resource cost is now with updated decimals according to the "solution above") 

![image](https://github.com/user-attachments/assets/5ba06dec-1b8a-4f33-a37f-3cf37bf0a3e6)

and bellow is the total cost calculated from the resource schedule 

![image](https://github.com/user-attachments/assets/3f65410b-36e1-41d6-8cc0-891d3c19109d)

The rounding depends on the units and quantities expressed and is project specific but I believe that there should be an option for user override. 

I again this is not the solution kindly revert so I can send you the necessary files.

**Comment by Andrej730** [comment]
> I again this is not the solution kindly revert so I can send you the necessary files.

I don't know, it's hard to tell without IFC example.
Also found something perhaps related - counter in resource section is considering no quantity as quantity = 1 but counter in the cost schedule section ignoring the values if there is no quantity present.

**Comment by DimitriosThe** [comment]
Inbox

**Comment by Andrej730** [comment]
Thanks for the report, too much rounding indeed was the issue. 

Though I'm not sure if there should be any rounding for quantities at all.
E.g. when quantities comes from the time associated with the resource (IfcConstructionResource.Usage) then I guess it's okay to round it up 
![image](https://github.com/user-attachments/assets/c31457a3-1d68-4590-8faf-99848e35230e)

But if quantity was explicitly assigned by some user then we should just keep it the way it is to prevent similar data loss. Any opinions? @DimitriosThe @steverugi
![image](https://github.com/user-attachments/assets/fbdf52eb-2712-4a29-a1c0-bc6b436841db)

**Comment by steverugi** [comment]
HI @Andrej730 
thanks for your reply
in my personal opinion it's better to apply rounding only to the output (BoQ style/Spreadsheet) than in the calculation at any level

**Comment by DimitriosThe** [comment]
Hi @Andrej730,

Thank you for the reply and clarifying.

Rounding is really tricky when it comes to contractual/ financial documents.
I agree that no rounding should be applied to the "Resource Base Quantity" or the "Resource Base Cost" for that matter. 
The last document for contractual Annexing may contain rounding on the quantities and unit prices as Steve mentions,  but attention has to be provided on the difference from the "unrounded" variation , though this I believe is out of the scope of BONSAI.
Another issue is that when applying these values you have to keep in mind the units that you are making calculations as these inputs are at the moment "unit agnostic" especially for the "Labor resource" where you have both components when calculating resource base cost in which, monetary value of the resource is inexplicitly referenced to a day/hour (user choice) based on what "Resource base Quantity" is inexplicitly used/ entered, at which the correct use of these in both fields provide correct calculation.

P.S. I have made a modification in my branch but the pull request failed for some reason.

![image](https://github.com/user-attachments/assets/20bbc695-06d0-4401-a9f8-92ea1af32d61)

**Comment by DimitriosThe** [comment]
I believe this can be considered as closed

**Comment by Andrej730** [comment]
Okay, thanks for the feedback, I'll remove the rounding to preserve the data from the original quantities.

> P.S. I have made a modification in my branch but the pull request failed for some reason.

Thanks for the PR. It was showing formatting errors (we use [black formatter](https://black.readthedocs.io/en/stable/getting_started.html) to keep the code formatting consistent) but since the error wasn't related to the file you modified, it's safe to ignore it.
