### ISSUE TITLE
Chinese encode in IFC

### ISSUE THREAD

**Issue by oxaza** [IfcOpenShell/IfcOpenShell#571]
hello, I'd like to ask you a question, which Chinese encoding pattern do you use in IFC generation? I tried utf-8 but it still have messy code.  Thank you!

**Comment by aothms** [comment]
I don't think I understand the question. IFC / STEP has an encoding by which you can encode unicode into the model files and IfcOpenShell supports this encoding. But compilation mode and settings might have an influence on how unicode is handled throughout the codebase. Can you share a little bit more of what you tried that is not working?

**Comment by Stinkfist0** [comment]
FWIW, I have managed to output UTF-8 encoded XML with Chinese characters using IfcConvert just fine.

**Comment by Moult** [comment]
Seems to be a non-issue.
