### ISSUE TITLE
Issue rendering with non-tangent space normal texture map

### ISSUE THREAD

**Issue by sboddy** [IfcOpenShell/IfcOpenShell#5710]
I've been playing with textures and have an issue that affects both IFC type texture and External types.

1. Open attached example
[texture_normal_maps_issue.zip](https://github.com/user-attachments/files/17655824/texture_normal_maps_issue.zip)
2. Switch to textured mode
3. See this uglyness:
![image](https://github.com/user-attachments/assets/fbe9cb32-53e1-4614-97ac-927b74a0f570)
4. Go into the styles pane and apply PanelOK to the object.
5. See this:
![image](https://github.com/user-attachments/assets/b7a3cd38-d118-4b8b-9c82-63a29f5b630b)

PanelOK was cloned from PanelERR and the normal map deleted. That is the only difference. Somehow the normal map causes this weirdness. It looks a lot like the face normals are flipped, but the face orientation overlay in the blender menu shows everything blue (facing the camera) so I don't know why this is happening. It also happens if using an externally defined Blender material with a Normal map fed into a Principled BSDF shader, meaning normal maps are off-limits as there is no alternative or workaround.

~~One _possible_ clue is that the faces appear to have split normals. This could be the source, although why applying a normal map to a surface would start messing with the normals is a mystery. (I used the trick of selecting the item and switching to UV Editing tab which lets me look at the geometry of a non-editable item like a covering.)~~ Edit: Took a second closer look, and maybe not split normals.

**Comment by Gorgious56** [comment]
You need to set the normal map to World Space.

![image](https://github.com/user-attachments/assets/3330e80d-ef65-4a35-8a41-5c25da43f055)

**Comment by Andrej730** [comment]
No idea if IFC if is capable of storing what space texture map is using in some way. I think this kind of use would be a usecase for external shader styles.

https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcSurfaceTexture.htm

**Comment by sboddy** [comment]
Thanks to you both. I'm happy with the answer with respect to my usage, but I'll leave it to you to decide to close or not. As per blender it looks like tangent is the default:

> **Space**
> 
> The input RGB color can be in one of three spaces: Tangent, Object and World space. Tangent space normal maps are the most common, as they support object transformation and mesh deformations. Object space normal maps keep sticking to the surface under object transformations, while World normal maps do not.

Something about the meshes in Bonsai do not work well with the default Tangent space. I still think there must be something "off" about the created meshes, and as this is default and baked into the Texture Style it's going to be rear it's head in the future I think.

Of course, externals give ultimate control, and are better in this case anyway as I can do the [neat shader](https://community.osarch.org/discussion/2550/aligning-shingles-on-intelligent-hip-roof#latest) posted by @theoryshaw which aligns and scales the texture to the roof planes.

**Comment by Andrej730** [comment]
Since tangent space normal maps are probably the most common type of normal maps, its okay to keep tangent space as a default. Maybe in the future if styles will be used more widely, then we may consider setting up some mechanism to store additional styles settings but for now it's fine to just delegate all complex styles to Blender.
