### ISSUE TITLE
Spatial Decomposition doesn show all spatial elements after merging projects

### ISSUE THREAD

**Issue by KevinSchnippkoweit** [IfcOpenShell/IfcOpenShell#5713]
After merging two ifc files the spatial decomposition tab only shows the object structure of one file. 
[MAT-TAES-FB-B-Fahrbahn-01_koord.zip](https://github.com/user-attachments/files/17662613/MAT-TAES-FB-B-Fahrbahn-01_koord.zip)

**Comment by Andrej730** [comment]
Thank you for the report, will be fixed in the next commit.
