### ISSUE TITLE
ifcopenshell - No module named 'bpy'

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#5718]
Hello,

when installing `ifcopenshell` 0.8.0 using `pip` it seems there's a non-resolved dependency with the `bpy` package:

```py
Python 3.12.7 (main, Oct 19 2024, 01:09:09) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import ifcopenshell
>>> import ifcopenshell.api.context
Note: API not available due to missing dependencies: geometry.add_representation - No module named 'bpy'
Note: API not available due to missing dependencies: grid.create_axis_curve - No module named 'bpy'
```

Could the `bpy` package be automatically installed if missing when installing `ifcopenshell`?

Please, note that manually installing this package doesn't seem to work:

```py
$ pip install -U bpy

ERROR: Ignored the following versions that require a different python version: 2.82.1 Requires-Python >=3.7, <3.8
ERROR: Could not find a version that satisfies the requirement bpy (from versions: none)
ERROR: No matching distribution found for bpy
```

But this error is obviously not directly related to `ifcopenshell`.

OS: Debian 12.7

Thank you!

Warm Regards.

**Comment by Andrej730** [comment]
@swiss-knight `bpy` module is optional and it's required only for methods that are suppose to be executed from Blender. There is standalone `bpy` module (https://pypi.org/project/bpy/) but it's supporting only the same version that Blender currently does (Python 3.11) and it's untested.

**Comment by swiss-knight** [comment]
Okay, but does this mean that when we want to write/debug/run Python scripts involving `ifcopenshell` we have to do it from the Blender scripting Text data-block?

Because it's unfortunately not a full-fledged Python development environment; it lacks almost all the tools a developer likes to work with.

**Comment by Andrej730** [comment]
> Okay, but does this mean that when we want to write/debug/run Python scripts involving `ifcopenshell` we have to do it from the Blender scripting Text data-block?

99% `ifcopenshell` capabilities are available without Blender. If you want to write Blender scripts - search for VS Code + Blender setups.

**Comment by Dahrmun** [comment]
i'm having the same problem. I'm running the minimal example of ifcDiff  from here https://docs.ifcopenshell.org/ifcdiff.html 
i am using python 3.12.8 in docker
ifcdiff==0.8.0
ifcopenshell==0.8.0

and i get the warning 
```
Note: API not available due to missing dependencies: geometry.add_representation - No module named 'bpy'
Note: API not available due to missing dependencies: grid.create_axis_curve - No module named 'bpy'
```

Would be cool to not have the bpy dependency for this
