### ISSUE TITLE
Question related to function reuse_ok_()

### ISSUE THREAD

**Issue by YouYue123** [IfcOpenShell/IfcOpenShell#572]
I found the `geometry_reuse_ok_for_current_representation_ = reuse_ok_(ifcproducts);` will always return **FALSE** in my case. Even thought from IFC file, all of the object is pointing to the exact same geometry entity.  The geometry entity is as below

```
#27 = IFCAXIS2PLACEMENT2D(#28, #29);

#28 = IFCCARTESIANPOINT((0., 0.));

#29 = IFCDIRECTION((1., 0.));

#56 = IFCBEAM('0a7Xmvs7j0zBglcWdOocTZ', #9, 'BEAM', 'HEA260', 'HEA260', #790157, #57, 'A0(?)');

#57 = IFCPRODUCTDEFINITIONSHAPE($, $, (#58));

#58 = IFCSHAPEREPRESENTATION(#16, 'Body', 'Clipping', (#59));

#59 = IFCBOOLEANCLIPPINGRESULT(.DIFFERENCE., #60, #64);

#60 = IFCEXTRUDEDAREASOLID(#61, #62, #34, 3999.38);

#61 = IFCISHAPEPROFILEDEF(.AREA., 'HEA260', #27, 260., 250., 7.5, 12.5, 24.);

#62 = IFCAXIS2PLACEMENT3D(#63, #32, #33);

#63 = IFCCARTESIANPOINT((3999.37887091439, 0., 0.));

#64 = IFCHALFSPACESOLID(#65, .F.);
```

May I know why it is the case and what is the logic in checking whether a geometry is reusable or not? Should it be checked via `product->declaration().index_in_schema()`

Thanks

**Comment by aothms** [comment]
> May I know why it is the case

it's probably easiest to step through the function and see when and why it returns false.

There are some pretty specific constraints, some that could also be alleviated with some additional implementation effort and some are about e.g. openings that mutate the geometries outside of the actual representation item definitions.
