### ISSUE TITLE
[IfcConvert] incorrect objects hiearchy and locations

### ISSUE THREAD

**Issue by SamiraOSU** [IfcOpenShell/IfcOpenShell#5720]
I want to export a file from Revit as an IFC and import it into Unity using [IfcImporter ](https://assetstore.unity.com/packages/tools/utilities/ifc-importer-162502#publisher) plugin, but when I do so, the hierarchy of objects does not retain the structure as the original ifc. I've attached screenshots of the door position in both Unity and IfcViewer showing the position and hierarchy. 
![image](https://github.com/user-attachments/assets/2c7a4e3b-94f4-4746-ae43-b94a7aa662f0)
![image](https://github.com/user-attachments/assets/b41068cf-b558-4f61-9c44-e74cd0f402ad)
 
Based on what I found the plugin uses the below command;
`IfcConvert.exe -y -j 32 "D:\Unity\TestIFC\Assets\IfcImporter\Facade_Windows2.ifc" "D:\Unity\TestIFC\Assets\IfcImporter\Resources\Facade_Windows2_dae.dae" --use-element-guids --element-hierarchy > "D:\Unity\TestIFC\Assets\IfcImporter\Resources\Facade_Windows2_dae_log.txt"`

**Comment by aothms** [comment]
Without the model we can't do much, you can attach it here as a text file.

Also from the link you shared it seems that the plug-in is over a year old. You might want to try with our latest version of IfcConvert https://github.com/IfcOpenBot/IfcOpenShell/commit/e70bc049150c29904e9711252ec752089c3ed828#commitcomment-148793233

**Comment by SamiraOSU** [comment]
Tried the latest IfcConvert, and it worked perfectly. Fixed all the locations. Thanks for the tip!
