### ISSUE TITLE
Can't edit the horizontal layers of an ifcfurnture class

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5727]
Can't tab into, and edit the horizontal layers of an ifcfurnture object.

[axis3 ifcfurniture.ifc.txt](https://github.com/user-attachments/files/17684925/axis3.ifcfurniture.ifc.txt)

https://github.com/user-attachments/assets/b9682fff-e013-4ce2-9571-0487d04fc9cb

**Comment by brunoperdigao** [comment]
@theoryshaw This should be fixed. However, for the file you provided, the furniture is already saved as AXIS2. You have to manually change that in "object materials" panel to AXIS3
