### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable" when editing empty Pset in Bonsai 0.8.0

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#5730]
Hello,

I added standardized IFC 4X3 Psets (e.g. `Pset_Risk` and `Pset_Warranty`) to an element Type using [`ifcopenshell.api.pset.add_pset()`](https://docs.ifcopenshell.org/autoapi/ifcopenshell/api/pset/add_pset/index.html) in IfcOpenShell `0.8.0` (installed with pip on Python 3.11):

```py
pset_risk = ifcopenshell.api.pset.add_pset(
    model,
    product=whatever_element_type,
    name="Pset_Risk",
)
pset_warranty = ifcopenshell.api.pset.add_pset(
    model,
    product=whatever_element_type,
    name="Pset_Warranty",
)
```
This works great.

Let's say I added some values using [`ifcopenshell.api.pset.edit_pset()`](https://docs.ifcopenshell.org/autoapi/ifcopenshell/api/pset/edit_pset/index.html) to `Pset_Risk`:
```py
ifcopenshell.api.pset.edit_pset(
    model,
    pset=pset_risk,
    properties={
        "foo": 10,
        "bar": 20,
    },
)
```

But I added **nothing** to `Pset_Warranty`.

When I open the resulting IFC file in Blender with Bonsai `0.8.0`, it shows me this under the `Type properties` section of the `Scene > Object Information` panel of my element Type:

![image](https://github.com/user-attachments/assets/1568978b-44c5-4fc7-be80-1f603f6fb2d1)

By clicking on the little pencil attached to the `Pset_Risk` (depicted in a green frame in the above picture), it shows me [all the IFC 4X3 standardized keys](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/Pset_Risk.htm) for the `Pset_Risk` along with the values I added:

![image](https://github.com/user-attachments/assets/90952150-d411-4914-b225-fa9b8c679471)

And this is really amazing !

But for the `Pset_Warranty`, where I added no properties, clicking the little pencil (depicted in a red frame in the above picture) raises the following error:

```py
Error: Python: Traceback (most recent call last):
  File "/home/me/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/pset/operator.py", line 61, in execute
    core.enable_pset_editing(tool.Pset, pset, self.pset_name, self.pset_type, self.obj, self.obj_type)
  File "/home/me/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/core/pset.py", line 86, in enable_pset_editing
    pset_tool.import_pset_from_existing(pset, props)
  File "/home/me/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/pset.py", line 108, in import_pset_from_existing
    for prop in sorted(pset_props, key=lambda p: p.Name):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```
Even if the Pset is empty in the IFC file, could it show all standardized properties for the current IFC schema when opened in Blender/Bonsai?    
Or do I need to do some extra within `ifcopenshell` in the Python code to make the standardized properties available in Bonsai when they are all empty (`None`)?

I'm using Blender 4.2.2 LTS on Ubuntu 22.04.5

Thanks 🙏
Warm Regards.

**Comment by Andrej730** [comment]
> Even if the Pset is empty in the IFC file, could it show all standardized properties for the current IFC schema when opened in Blender/Bonsai?
> Or do I need to do some extra within ifcopenshell in the Python code to make the standardized properties available in Bonsai when they are all empty (None)?

@swiss-knight It's invalid IFC. `IfcPropertySet.HasProperties` should have some properties otherwise this pset is invalid. Add some prop to it to make IFC valid and then it will load props from templates when you edit it from Bonsai.

https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcPropertySet.htm
![image](https://github.com/user-attachments/assets/b75f7e96-2713-472d-b54e-f90b52e0d3a6)
