### ISSUE TITLE
Debug build broken - libsvgfill

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#5731]
@aothms the Debug build of libsvgfill is broker.

To fix, add

~~~
#ifdef _DEBUG
#include <nlohmann\json.hpp>
#endif
~~~

at the top of graph_2d.h just after the include guard.

I was having trouble committing the change because this is a submodule

**Comment by aothms** [comment]
Thanks, also renamed _DEBUG to SVGFILL_DEBUG
