### ISSUE TITLE
ifcopenshell.util.pset.PsetQto("IFC4X3") -> KeyError: 'IFC4X3'

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#5732]
Hello,

in `ifcopenshell` 0.8.0 / Python 3.11: 

```py
import ifcopenshell.util.pset

print(ifcopenshell.util.pset.PsetQto("IFC2X3"))
# <ifcopenshell.util.pset.PsetQto object at 0x721348062712>

print(ifcopenshell.util.pset.PsetQto("IFC4"))
# <ifcopenshell.util.pset.PsetQto object at 0x72134818df12>

print(ifcopenshell.util.pset.PsetQto("IFC4X3"))
#Traceback (most recent call last):
# File "<stdin>", line 1, in <module>
#  File "/usr/local/lib/python3.11/site-packages/ifcopenshell/util/pset.py", line 51, in __init__
#    path = str(folder_path.joinpath("schema", self.templates_path[schema_identifier]))
#                                              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
# KeyError: 'IFC4X3'
```

How could I use the IFC 4X3 schema in order to get the available `Pset` and `Qto` here?

Thanks 🙏!

**Comment by Moult** [comment]
You need to use the exact schema identifier. IFC4X3_ADD2. This is so that IfcOpenShell can support development versions of IFC.

**Comment by swiss-knight** [comment]
Okay, I got it and it's indeed working with `"IFC4X3_ADD2"`.  👍 Thanks!

But then may I suggest this behavior to be harmonized all over the `ifcopenshell` library?

Indeed, for example, `schema = ifcopenshell.ifcopenshell_wrapper.schema_by_name("IFC4X3")` is also working whereas it didn't with `ifcopenshell.util.pset.PsetQto()`. That's what got me confused about referencing the IFC schema.

**Comment by Andrej730** [comment]
> But then may I suggest this behavior to be harmonized all over the `ifcopenshell` library?
> 
> Indeed, for example, `schema = ifcopenshell.ifcopenshell_wrapper.schema_by_name("IFC4X3")` is also working whereas it didn't with `ifcopenshell.util.pset.PsetQto()`. That's what got me confused about referencing the IFC schema.

`ifcopenshell.util.pset.PsetQto` expects `schema_identifier`, not `schema`, so `IFC4X3_ADD2` should be provided, not `IFC4X3`. `IFC4X3` you get from `schema_by_name` is a different schema than `IFC4X3_ADD2`.

But I'll add an exception to implicitly interpret `IFC4X3` as `IFC4X3_ADD2`, the same exception we do in `ifcopenshell.schema_by_name` and `ifcopenshell.file`.
