### ISSUE TITLE
IfcCovering not working as expected (241111 release)

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5735]
adding an IfcCovering both vertical or horizontal mesh does not allow further editing
it returns "parametric LAYER2 elements cannot be edited directly"
if the layer thickness of a horizontal layer is changed it affects the Y axis, not the Z axis

please see video below

https://github.com/user-attachments/assets/6082487a-dd4c-4b88-a85d-de253fe806e5

vertical layer covering does not allow to edit it on the z axis, so it cannot be created

thanks

**Comment by steverugi** [comment]
EDIT
vertical layer cladding does not allow editing but behaves like a wall so please disregard this comment, only the horizontal layer has some issue with editing and thickness, cheers

**Comment by theoryshaw** [comment]
Probably related...
https://github.com/IfcOpenShell/IfcOpenShell/issues/5727

**Comment by steverugi** [comment]
@theoryshaw yes, looks like something affecting horizontal layers..

**Comment by fjieikkdddsll** [comment]
I had a similar issue. I created a sidewalk as a civil element type with horizontal layers and got the message "parametric LAYER2 elements cannot be edited directly" as above posts. A possible workaround: I selected the object, clicked on "convert to tessellation" on under "representation utilities" on the geometry and materials tab. This allowed me to edit my object. I don't know if there are any downsides to this method though. It seems to have worked for my purposes.

**Comment by steverugi** [comment]
@fjieikkdddsll 
yes of course you can convert it to a mesh/tassellation but probably we miss the opportunity to have an element rendered from an XY polyline extruded on Z axis, the same we currently have with the slab, which is more efficient I think?
I might be wrong but it seems to me that Y and Z are swapped in this specific horizontal layer, causing the error, cheers

**Comment by brunoperdigao** [comment]
@steverugi I created a fix for #5727, could you please test if it also solves your issue?

**Comment by brunoperdigao** [comment]
Please test with a fresh object. 
For existing ones, the problem is that they are already saved as AXIS2. You have to manually change that in "object materials" panel to AXIS3.

**Comment by steverugi** [comment]
thanks @brunoperdigao 
will do it shortly and revert
