### ISSUE TITLE
Option/Alt + D duplicating objects like Shift + D instead of selecting all the enclosed elements in that space

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5739]
Before when pressing Alt + D you could select all the objects within a space, but now it's just duplicating the space itself, exactly like what Shift + D does.

Is this a bug?

**Comment by Andrej730** [comment]
@BIMvoice Are you sure space is selected? Spatial elements are unselectable by default:
https://github.com/user-attachments/assets/45549eda-adc5-43ee-9264-18f1c5122edf

If it's not selected I believe Alt+D never worked in that case. I've made a change in the last commit so it now also considers the active object which perhaps can help.

**Comment by BIMvoice** [comment]
Of course, I'm sure. I visually selected it, and I checked in the information tab and it was selected.

We saw this in a video Dion recorded in December 2023 and he used that shortcut to do it as screencastkeys have shown.

@Moult still using that?

**Comment by Andrej730** [comment]
> Of course, I'm sure. I visually selected it, and I checked in the information tab and it was selected.

If it's visually selected and you can see the information, it doesn't mean it's "selected", it means it's "active". 
Selected objects have orange outline in the viewport / orange text in the outliner, see the video I've attached above.

**Comment by steverugi** [comment]
Sorry guys for me being slow
can we select items in a space now? how?
thanks

**Comment by Andrej730** [comment]
@steverugi 
![image](https://github.com/user-attachments/assets/9adb0f9b-8617-445d-bdd5-eda7c6736a4b)

**Comment by steverugi** [comment]
@Andrej730 @BIMvoice 
OK the trick is that Alt+D works when **"Multi Object Tool" icon is selected**, then you can select the IfcSpace and the elements contained with Alt+D
cheers!
