### ISSUE TITLE
Regression in the branch v0.6.0: A part of the wall disappeared

### ISSUE THREAD

**Issue by wlinna** [IfcOpenShell/IfcOpenShell#574]
A part of the wall disappears now when I convert a model on v0.6.0 . See the picture below:

![regression](https://user-images.githubusercontent.com/1473454/56344176-6c9a1680-61c5-11e9-86df-a2dc13fededd.PNG)

and the log below:

```
Log:
[Error] {35tjICbuFsH96fh5T0lv5d} No operation defined for:
#534=IfcBoundingBox(#535,1074.,1856.,1987.)
[Error] {1MAnWSI7E6HxhGNGPX7bwi} No operation defined for:
#3323=IfcBoundingBox(#3324,1074.,760.,1987.)
[Error] {1RIrpTW2EQJANw7sZ8lCXm} Failed to process subtraction:
#3434=IfcBooleanResult(.DIFFERENCE.,#3435,#3443)
[Error] {1RIrpTW2EQJANw7sZ8lCXm} No operation defined for:
#3541=IfcBoundingBox(#3542,2500.,839.,2500.)
[Error] {1RIrpTW2EQJANw7sZ8lCXm} No operation defined for:
#3557=IfcBoundingBox(#3558,7400.00004161,809.000000649,6754.36841482)
[Error] {1lpDDUbFGfH8wjlZs_ht7b} Failed to process subtraction:
#3740=IfcBooleanResult(.DIFFERENCE.,#3741,#3749)
[Error] {3H9c31gBj1HQmX9mjkG$ik} Failed to process subtraction:
#3909=IfcBooleanResult(.DIFFERENCE.,#3910,#3917)
[Error] {3H9c31gBj1HQmX9mjkG$ik} No operation defined for:
#3963=IfcBoundingBox(#3964,2499.99999999,340.000000649,2500.)
[Error] {3H9c31gBj1HQmX9mjkG$ik} No operation defined for:
#3974=IfcBoundingBox(#3964,2499.99999999,340.000000649,2500.)
[Error] {0eS$AIYffMJenrKGH3sCFM} No operation defined for:
#1014=IfcBoundingBox(#1015,1074.,900.,1987.)
```

The commit that causes the problem is this: 013b7a763d928187e220df28db27bff1cd6f642f

After reverting that commit, the wall appears again (as it should).

As a side note, there are also parts that shouldn't be there, but are there.

![ConversionProblem](https://user-images.githubusercontent.com/1473454/56344371-e8945e80-61c5-11e9-989d-8f451b817c44.png)

Here's the problematic IFC in question:
[problematicroof.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/3093248/problematicroof.zip)

**Comment by aothms** [comment]
Thanks. There was indeed an oversight in how triangulating non-planar faces affected the topological connection to neighbouring faces. The wall that disappeared is back with the latest commit.

The other two walls that extend beyond the roof I think are not a regression. Can you confirm that? The boolean operand used there for the subtraction appears to be invalid and I haven't found a way for occt to fix them.

**Comment by wlinna** [comment]
Indeed, the two protruding roofs are not a regression. In fact, they've gotten better. I just mentioned them, because I wasn't sure how to report them, because there are already some closed issues about it.

https://github.com/IfcOpenShell/IfcOpenShell/issues/6
https://github.com/IfcOpenShell/IfcOpenShell/issues/163

Btw is there somewhere an overview on how the 0.6.0 branch differs from the master branch? IfcConvert on this branch seems to be able to handle both IFC2x3 and IFC4 without recompilation.

**Comment by aothms** [comment]
> because there are already some closed issues about it.

In case of geometry, seemlingly similar cases can be very different. In those cases the issues were related to IfcPolygonalBoundedHalfSpaces, in your case the second boolean operands are explicit IfcFacetedBReps. The problem with that second approach is that the geometries need to be valid manifolds, i.e. every edge used exactly two times in different directions, no intersecting edges or faces.

> Btw is there somewhere an overview on how the 0.6.0 branch differs from the master branch? IfcConvert on this branch seems to be able to handle both IFC2x3 and IFC4 without recompilation.

That is one of the considerable differences. The other difference is in the handling of these connected face sets. There is a vertex clustering step and topological orientation is now implemented in more efficiently. In master every face is processed in isolation. In v0.6.0 pairs of edges are already generated by IfcOpenShell so that OCCT does not need to do an exhaustive search to later reconstruct these edge pairs based on geometry.

**Comment by Moult** [comment]
A little 2022 update, still seems to have one protruding roof:

![2022-09-03-214300_809x548_scrot](https://user-images.githubusercontent.com/88302/188268871-fa15da7d-8b8a-44b4-a6c2-9dd392ec4d25.png)

**Comment by aothms** [comment]
Thanks for checking. The 2nd operand of the subtraction of that one protruding wall is hard to make sense of.

It has overlapping edges

![afbeelding](https://user-images.githubusercontent.com/1096535/188440903-3a13fb50-22b7-435c-92ed-8ed7c13bbf4e.png)

and other weird detail

![afbeelding](https://user-images.githubusercontent.com/1096535/188440992-5bbac52b-05f9-4b85-bd16-a126a51eb645.png)

(close up of)

![afbeelding](https://user-images.githubusercontent.com/1096535/188441062-1eb95cc6-a1eb-4925-af9f-fde1d6ed38db.png)

So it's understandable OCCT get's confused I'd say. I'm closing this issue.
