### ISSUE TITLE
material resource value not calculated based on quantity of work

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5744]
### using 4D & 5D in Bonsai
it is possible to assign elements to a task in a work schedule
then resources can be allocated to carry out the work

#### time resource
when I use a time resource like labor it correctly calculates the cost using its productivity (m²/h) and the hourly cost ($/h) of the resource multiplied by the units (m²) from the elements' quantity
if the work is 15m², the resource's rate is 25$/h and its productivity is 2m²/h the corresponding cost is 15/2 = 7.5h * $25/h=  $187.5

![image](https://github.com/user-attachments/assets/a3167a5a-01f2-431e-83ae-6af0ee32cb21)
![image](https://github.com/user-attachments/assets/91ecb072-fb32-4f03-8d9b-566a9720acdb)

all good so far, no issue and the calculated cost of such task properly shows in the cost schedule (1U x 187.50 = 187.50)

#### material resource
![image](https://github.com/user-attachments/assets/cedc6888-b348-4280-bb31-84af446df0a5)

when I assign a material resource like blocks to a different task, having the same elements as the above one

![image](https://github.com/user-attachments/assets/3f5417d0-ed00-429f-9caa-7123bf435b74)

 the cost remains the one per rate of blocks and not the product of blocks $/m²  x m²

![image](https://github.com/user-attachments/assets/6377f8ee-7aa0-4d80-8d83-9bd4a4b1ed34)

cost of task when a material resource is used does not have productivity and it returns the resource cost instead of calculating it based on the total work

thanks

**Comment by steverugi** [comment]
### NOTE
once a resource is assigned to a task it does not inherit its rate, if possilble it would be a useful feature
thanks again

**Comment by Andrej730** [comment]
@steverugi 
Added option to calculate material resource quantity - see demo in 9f49cbe0c description.



> once a resource is assigned to a task it does not inherit its rate, if possilble it would be a useful feature

Can you show some example?

**Comment by steverugi** [comment]
Hi @Andrej730 
I have a labor resource with cost of 25 per unit
![image](https://github.com/user-attachments/assets/4f148674-4472-4e32-9811-7a1731ccf218)

I add the resource to a task
![image](https://github.com/user-attachments/assets/3edda2f8-9ad0-4f64-8442-0d1cd94b58fb)

which creates an allocated resource item but no value is carried out from its 'parent' (25 per unit)
![image](https://github.com/user-attachments/assets/cbf547bc-e0eb-437f-8d6f-8e4dd8f506e6)

does it make sense now? thanks for your assistance

PS it would be awesome if the .csv import method to load resources along with their info were clarified, what @myoualid showed in his video on 4D did not enter into details..

**Comment by steverugi** [comment]
> @steverugi Added option to calculate material resource quantity - see demo in [9f49cbe]

I just installed today's release, where is the option refresh button going to be? thanks

**Comment by Andrej730** [comment]
> I just installed today's release, where is the option refresh button going to be? thanks

@steverugi See the video demo in commit description - 9f49cbe0c9429db9bd76a84a503508ebc76d242c

**Comment by steverugi** [comment]
thanks @Andrej730 very useful feature, so much appreciated

**Comment by Andrej730** [comment]
> which creates an allocated resource item but no value is carried out from its 'parent' (25 per unit)

Yes, it doesn't duplicate the quantity from the parent but why it's an issue?

**Comment by Andrej730** [comment]
> PS it would be awesome if the .csv import method to load resources along with their info were clarified, what myoualid showed in his video on 4D did not enter into details..

See https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifc4d/ifc4d/resource_spreadsheet.csv for a reference. 

Note that not all columns are actually going to be loaded to IFC, only few are supported:
https://github.com/IfcOpenShell/IfcOpenShell/blob/d0b3ecad42f234430b6a6385994ca932b0697af2/src/ifc4d/ifc4d/csv2ifc.py#L45-L54

**Comment by steverugi** [comment]
thanks @Andrej730, very kind as usual

I had that .csv, I meant some more info as to how implement it in a real life, at the moment it's like trial-error to do so, but it's OK, 
I believe there are more important issues with the development of Bonsai.

The reason why I asked it is because I am preparing some videos showing how to use Bonsai in 4D for Petru
cheers

**Comment by steverugi** [comment]
> > which creates an allocated resource item but no value is carried out from its 'parent' (25 per unit)
> 
> Yes, it doesn't duplicate the quantity from the parent but why it's an issue?

1. imagine you have tens and tens of tasks where the same resource is allocated to, creating the same number of resource-allocated item in the resource panel, currently you need to manually set the rate for each and every one 
2. for rate revision the same applies, not a big issue for a small building but for anything more it can be tedious
thanks

**Comment by Andrej730** [comment]
> I had that .csv, I meant some more info as to how implement it in a real life, at the moment it's like trial-error to do so, but it's OK,
> I believe there are more important issues with the development of Bonsai.

The csv export for resources looks simple enough, I'll try to add it soon.

> * imagine you have tens and tens of tasks where the same resource is allocated to, creating the same number of resource-allocated item in the resource panel, currently you need to manually set the rate for each and every one
> * for rate revision the same applies, not a big issue for a small building but for anything more it can be tedious

But then again, what if you assigned the same resource to 10 tasks, it's duplicated the original quantities and then you decide to change it - you'd have to change it 10 times instead of just changing the parent resource. So it should inherit the rate (if it's own rate is not specified) during calculations, not just duplicate it. Are there any places where it doesn't work currently?

**Comment by steverugi** [comment]
sorry, at the moment I do not understand your answer, will try again tomorrow
thanks a lot for your precious help

**Comment by steverugi** [comment]
> > which creates an allocated resource item but no value is carried out from its 'parent' (25 per unit)
> 
> Yes, it doesn't duplicate the quantity from the parent but why it's an issue?

@Andrej730 
I meant to inherit its **value** not the quantity, I tried and the rate is not inherited from the main resource to the allocated one, thanks

**Comment by Andrej730** [comment]
> I meant to inherit its **value** not the quantity, I tried and the rate is not inherited from the main resource to the allocated one, thanks

@steverugi Oh, sorry, I meant the value too, called it quantity by accident. 
It should inherit already - can you please show an example where it doesn't work?

**Comment by steverugi** [comment]
This is the resource 'labor1' ha a value of 27.5, the allocated one doesn't have it

![image](https://github.com/user-attachments/assets/c74a910c-6fd3-4707-8116-f2eec50a36b8)

the same resource is allocated to the task 'labor'

![image](https://github.com/user-attachments/assets/622639e4-b8a5-4e0d-bbb9-a7e411ea6cda)

the same is used in the BoQ

![image](https://github.com/user-attachments/assets/9bcdf114-f877-4eb5-84d5-1d32c1395ce2)

but clicking on the 'disc' on top of the right pane does not produce any rate in the BoQ

### adding value to allocated resource

![image](https://github.com/user-attachments/assets/823fd89f-1af2-4f2d-bf96-a35fa35feb8d)

now when I click on the disc the BoQ correctly reports its rate

![image](https://github.com/user-attachments/assets/03308207-84bc-4874-9818-a8d1d2b06a3f)

thanks

**Comment by Andrej730** [comment]
> but clicking on the 'disc' on top of the right pane does not produce any rate in the BoQ

Makes sense, it's a bug. Will fix it in the next commit.
