### ISSUE TITLE
After you add a beam, the type manager doesn't appear again

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5746]
After you add a beam, the type manager doesn't appear again...

https://github.com/user-attachments/assets/e465318f-64d6-4dde-9516-f12c42ae7a81

**Comment by sboddy** [comment]
Just to add, I think this is more generically "Once you click away from the first use of the type manager, it doesn't appear again." I don't even have to add anything. Just click a wall so the view/tool changes, and the type manager is history.

**Comment by sboddy** [comment]
Found the regression commit: 5913fe8

@Andrej730 This commit causes this problem.
