### ISSUE TITLE
ConvertPropertiesToQuantities, TypeError: add_qto() got an unexpected keyword argument 'Name'

### ISSUE THREAD

**Issue by epeter-** [IfcOpenShell/IfcOpenShell#5747]
the object causing the error message is an IfcBuildingElementProxy, 
`#599=IFCBUILDINGELEMENTPROXY('3jGwUdci17efVupo2oN7kV',#18,'Unterwasserbetonsohle',$,'Unterwasserbetonsohle',#598,#595,'2176347',.NOTDEFINED.);`

the property to be converted is "Volumen" in pset "xxxset_Geometrie"

```
#633=IFCPROPERTYSINGLEVALUE('Volumen',$,IFCVOLUMEMEASURE(3080.4),$);
#634=IFCPROPERTYSINGLEVALUE('Flaeche',$,IFCAREAMEASURE(0.),$);
#635=IFCPROPERTYSINGLEVALUE('Laenge',$,IFCLENGTHMEASURE(170.),$);
#636=IFCPROPERTYSINGLEVALUE('Hoehe',$,IFCLENGTHMEASURE(1.2),$);
#637=IFCPROPERTYSINGLEVALUE('Breite',$,IFCLENGTHMEASURE(0.),$);
#638=IFCPROPERTYSET('1D1rQ2TabxHYSuyYSdIRzt',#18,'xxxset_Geometrie',$,(#633,#634,#635,#636,#637));
```
...
`#645=IFCRELDEFINESBYPROPERTIES('1PhpLhmwCHf2uGhkThIPDX',#18,$,$,(#599),#638);`

the target is "NetVolume" existing in "Qto_BuildingElementProxyQuantities"

**Comment by epeter-** [comment]
@Andrej730 tried the fix. received a KeyError: 'IFC4X3'

**Comment by Andrej730** [comment]
> tried the fix. received a KeyError: 'IFC4X3'

@epeter- You need to update ifcopenshell code too, you need this commit ecff798.
