### ISSUE TITLE
Retrieving recycled properties from PropertySet of Entity

### ISSUE THREAD

**Issue by legnad** [IfcOpenShell/IfcOpenShell#5748]
I'm currently trying to understand how PropertySets work and are handled in ifcopenshell.

I wrote a function to extract a property from an entity by _property name_ and I figured that for some entities the properties are not being retrieved and I discovered something odd.

Within the IFC File a PropertySet is defined as follows **(see line 290**):

```
...
#287=IFCAXIS2PLACEMENT3D(#286,$,$);
#288=IFCLOCALPLACEMENT(#190,#287);
#289=IFCBUILDINGELEMENTPROXY('1lXu$sznLB5f2NojBA$LZI',#6,'KST',$,$,#288,#284,$,$);
#290=IFCPROPERTYSET('0xG3fuf7HDKPNBRIeX1Qbn',#6,'Attributes',$,(#80,#45,#94,#47,#48,#49,#167,#96,#66));
#291=IFCRELDEFINESBYPROPERTIES('1V$yce8tX0HecxKzTRMquG',#6,$,$,(#289),#290);
#292=IFCEXTRUDEDAREASOLID(#21,$,#20,0.30000000000001137);
#293=IFCSHAPEREPRESENTATION(#10,'Body','SweptSolid',(#292));
#294=IFCPRODUCTDEFINITIONSHAPE($,$,(#293));
...
```

However, when exploring the issue with the Python PyCharm Debugger it seems like the PropertySet is not properly being represented in ifcopenshell:
![grafik](https://github.com/user-attachments/assets/ca52ce25-206e-42b7-be39-0d49778da38d)

At the bottom at the red arrow, shouldn't there be the references `"#80,#45,#94,#47,#48,#49,#167,#96,#66"` be listed inside the parantheses? The `HasProperties` property of the `RelatingPropertyDefinition` is of zero length.

**I know that these properties that are referenced here have been oringally defined for another/earlier defined entity and those properties are being recycled here as they have the same value, which means that those `IfcPropertySingleValue` have been used before in other PropertySets.** But still, shouldn't they be listed there so I can reference them from this entity?

**Comment by Andrej730** [comment]
@legnad are you sure file is not edited during the script and properties are not removed?
Can you please share the .ifc file and short script to reproduce the issue without PyCharm debugger?

**Comment by legnad** [comment]
While trying to compile the minimum example I indeed figured that I modified the file in a loop by removing propertysets and recursively deleting the references properties as well, wether or not they were referenced by other propertysets.

As a result I'm closing this as I am stupid enough. :) Thank you anyways!
