### ISSUE TITLE
Bonsai identifies Python version incorrectly on Gentoo Linux

### ISSUE THREAD

**Issue by aefxc** [IfcOpenShell/IfcOpenShell#5755]
I have two separate Gentoo linux computers, both are throwing the following error after installing Bonsai:

![image](https://github.com/user-attachments/assets/f19a0f9f-0690-42d2-b32c-250a1414c594)

Full error message: 

> os: Linux
> os_version: #1 SMP PREEMPT_DYNAMIC Fri Nov  8 10:16:09 EST 2024
> python_version: 3.12.7
> architecture: ('64bit', 'ELF')
> machine: x86_64
> processor: AMD Ryzen 7 6800H with Radeon Graphics
> blender_version: 4.2.1 LTS
> bonsai_version: 0.8.0
> bonsai_commit_hash: None
> last_actions: 
> last_error: Traceback (most recent call last):
>   File "/home/matthew/.config/blender/4.2/extensions/.local/lib/python3.12/site-packages/ifcopenshell/__init__.py", line 81, in <module>
>     from . import ifcopenshell_wrapper
>   File "/home/matthew/.config/blender/4.2/extensions/.local/lib/python3.12/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
>     from . import _ifcopenshell_wrapper
> ImportError: cannot import name '_ifcopenshell_wrapper' from partially initialized module 'ifcopenshell' (most likely due to a circular import) (/home/matthew/.config/blender/4.2/extensions/.local/lib/python3.12/site-packages/ifcopenshell/__init__.py)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/matthew/.config/blender/4.2/extensions/blender_org/bonsai/__init__.py", line 225, in <module>
>     import ifcopenshell.api
>   File "/home/matthew/.config/blender/4.2/extensions/.local/lib/python3.12/site-packages/ifcopenshell/__init__.py", line 83, in <module>
>     raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
> ImportError: IfcOpenShell not built for 'linux/64bit/python3.12'
> 
> binary_file_name: _ifcopenshell_wrapper.cpython-311-x86_64-linux-gnu.so
> binary_python_version: 3.11

Both computers have Python 3.12 installed and don't have Python 3.11 installed. Both computers have Blender compiled with the Python 3.12 targets and with Python 3.11 targets deselected.

![image](https://github.com/user-attachments/assets/fb2d2469-98e5-4dce-b78e-b0790c19a928)

Python 3.12 is observable in Blender's internal python console:
![image](https://github.com/user-attachments/assets/f2e71d9e-17e9-428b-a0cc-3621a74f9f26)

Output of "emerge --info" (Gentoo system information):

> 

> Portage 3.0.66.1 (python 3.12.7-final-0, default/linux/amd64/23.0/desktop/plasma/systemd, gcc-13, glibc-2.40-r5, 6.11.6-gentoo x86_64)
> =================================================================
> System uname: Linux-6.11.6-gentoo-x86_64-AMD_Ryzen_7_6800H_with_Radeon_Graphics-with-glibc2.40
> KiB Mem:    15589108 total,   3824524 free
> KiB Swap:   20971516 total,  20886112 free
> Timestamp of repository gentoo: Tue, 05 Nov 2024 15:00:00 +0000
> Head commit of repository gentoo: 8e4c015ebf4a0b5e74cf1a1f866181af2d5b892c
> Timestamp of repository guru: Tue, 05 Nov 2024 11:03:43 +0000
> Head commit of repository guru: f2f5eaf00a7ab1c5e6d1d75b34d3b0279b116208
> 
> Timestamp of repository riru: Mon, 14 Oct 2024 12:50:33 +0000
> Head commit of repository riru: 38fdbe9e2f4f6be40cb546ca099ef4aba086ceeb
> 
> Timestamp of repository steam-overlay: Tue, 08 Oct 2024 15:50:59 +0000
> Head commit of repository steam-overlay: c802c22bb423cb84d975b3fc9cfe6bc9410d22cd
> 
> Timestamp of repository waffle-builds: Mon, 14 Oct 2024 12:50:43 +0000
> Head commit of repository waffle-builds: 92c103d7b22d99c54f34661ae2ec1d771270e8ed
> 
> Timestamp of repository xarblu-overlay: Tue, 05 Nov 2024 11:03:45 +0000
> Head commit of repository xarblu-overlay: 451710e28c67fe524e308d30c1db5693360d5ada
> 
> sh bash 5.2_p37
> ld GNU ld (Gentoo 2.42 p6) 2.42.0
> app-misc/pax-utils:        1.3.7::gentoo
> app-shells/bash:           5.2_p37::gentoo
> dev-build/autoconf:        2.72-r1::gentoo
> dev-build/automake:        1.16.5-r2::gentoo
> dev-build/cmake:           3.30.5::gentoo
> dev-build/libtool:         2.4.7-r4::gentoo
> dev-build/make:            4.4.1-r1::gentoo
> dev-build/meson:           1.5.2::gentoo
> dev-lang/perl:             5.40.0::gentoo
> dev-lang/python:           3.12.7_p1::gentoo, 3.13.0::gentoo
> dev-lang/rust-bin:         1.81.0::gentoo
> sys-apps/baselayout:       2.17::gentoo
> sys-apps/sandbox:          2.39::gentoo
> sys-apps/systemd:          256.7::gentoo
> sys-devel/binutils:        2.42-r2::gentoo
> sys-devel/binutils-config: 5.5.2::gentoo
> sys-devel/clang:           18.1.8::gentoo
> sys-devel/gcc:             13.3.1_p20241025::gentoo
> sys-devel/gcc-config:      2.11::gentoo
> sys-devel/llvm:            18.1.8-r1::gentoo
> sys-kernel/linux-headers:  6.6-r1::gentoo (virtual/os-headers)
> sys-libs/glibc:            2.40-r5::gentoo
> Repositories:
> 
> gentoo
>     location: /var/db/repos/gentoo
>     sync-type: rsync
>     sync-uri: rsync://rsync.gentoo.org/gentoo-portage
>     priority: -1000
>     volatile: False
>     sync-rsync-verify-max-age: 24
>     sync-rsync-verify-jobs: 1
>     sync-rsync-verify-metamanifest: yes
>     sync-rsync-extra-opts: 
> 
> guru
>     location: /var/db/repos/guru
>     sync-type: git
>     sync-uri: https://github.com/gentoo-mirror/guru.git
>     masters: gentoo
>     volatile: False
> 
> riru
>     location: /var/db/repos/riru
>     sync-type: git
>     sync-uri: https://github.com/gentoo-mirror/riru.git
>     masters: gentoo
>     volatile: False
> 
> steam-overlay
>     location: /var/db/repos/steam-overlay
>     sync-type: git
>     sync-uri: https://github.com/gentoo-mirror/steam-overlay.git
>     masters: gentoo
>     volatile: False
> 
> waffle-builds
>     location: /var/db/repos/waffle-builds
>     sync-type: git
>     sync-uri: https://github.com/gentoo-mirror/waffle-builds.git
>     masters: gentoo
>     volatile: False
> 
> xarblu-overlay
>     location: /var/db/repos/xarblu-overlay
>     sync-type: git
>     sync-uri: https://github.com/gentoo-mirror/xarblu-overlay.git
>     masters: gentoo
>     volatile: False
> 
> Binary Repositories:
> 
> gentoobinhost
>     priority: 1
>     sync-uri: https://gentoo.osuosl.org/releases/amd64/binpackages/23.0/x86-64
> 
> ACCEPT_KEYWORDS="amd64"
> ACCEPT_LICENSE="@FREE"
> CBUILD="x86_64-pc-linux-gnu"
> CFLAGS="-march=native -O2 -pipe"
> CHOST="x86_64-pc-linux-gnu"
> CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
> CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/sandbox.d"
> CXXFLAGS="-march=native -O2 -pipe"
> DISTDIR="/var/cache/distfiles"
> ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GDK_PIXBUF_MODULE_FILE GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
> FCFLAGS="-march=native -O2 -pipe"
> FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync merge-wait multilib-strict network-sandbox news parallel-fetch pid-sandbox pkgdir-index-trusted preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
> FFLAGS="-march=native -O2 -pipe"
> GENTOO_MIRRORS="https://mirrors.mit.edu/gentoo-distfiles/"
> LANG="en_US.utf8"
> LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs"
> LEX="flex"
> MAKEOPTS="-j8"
> PKGDIR="/var/cache/binpkgs"
> PORTAGE_CONFIGROOT="/"
> PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
> PORTAGE_TMPDIR="/var/tmp"
> SHELL="/bin/bash"
> USE="X a52 aac acl acpi activities alsa amd64 bluetooth branding btrfs bzip2 cairo cdda cet crypt cups dbus declarative dri dts dvdr encode exif ffmpeg flac gdbm gif gles2 gpm gui iconv icu ipv6 jpeg kde kf6compat kwallet lcms libinput libnotify libtirpc mad mng mp3 mp4 mpeg mtp multilib ncurses networkmanager nls ofono-headset ogg opengl openmp pam pango pcre pdf pipewire plasma png policykit ppds pulseaudio qml qt5 qt6 readline screencast sdl seccomp semantic-desktop sound spell ssl startup-notification svg systemd test-rust tiff truetype udev udisks unicode upower usb vorbis vulkan wayland widgets wxwidgets x264 xattr xcb xft xml xv xvid zlib" ABI_X86="64" ADA_TARGET="gcc_12" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_anon authn_dbm authn_file authz_dbm authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir env expires ext_filter file_cache filter headers include info log_config logio mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax navcom oceanserver oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 tsip tripmate tnt ublox" GUILE_SINGLE_TARGET="3-0" GUILE_TARGETS="3-0" INPUT_DEVICES="libinput evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz glk hd44780 lb216 lcdm001 mtxorb text" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php8-2" POSTGRES_TARGETS="postgres16" PYTHON_SINGLE_TARGET="python3_12" PYTHON_TARGETS="python3_12" RUBY_TARGETS="ruby32" VIDEO_CARDS="amdgpu radeonsi" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipp2p iface geoip fuzzy condition tarpit sysrq proto logmark ipmark dhcpmac delude chaos account"
> Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, PYTHONPATH, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS
>

**Comment by brunopostle** [comment]
The Bonsai download is built for python 3.11 only. This is because the precompiled Blender download from blender.org is built for 3.11.

It is possible to rebuild Bonsai for your distro blender and python (I do this for fedora), maybe you could create a Gentoo ebuild and share it?

**Comment by aefxc** [comment]
It is trivial to recompile Blender for Python 3.11 in Gentoo. 

This issue seems to be the language of the error. "Expected 3.12, Got 3.11"  on a Bonsai error dialog made me Bonsai was expecting 3.12 but got 3.11, which seemed to contradict my actual system. Perhaps the error's 'voice' is not what I understood it to be, and is the voice of Blender as it interacts with Bonsai. 

If this error is spoken in the voice of Blender, then perhaps the defect of unclear language belongs to Blender not Bonsai.

**Comment by aefxc** [comment]
Resolved by recompiling Blender 4.2 with Python 3.11 single target in Gentoo.
