### ISSUE TITLE
Moving objects in the Scene collections doesn't update the IFC

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#5757]
I created a grid in the wrong place in the spatial decompositition. The grid was created in a IfcBuildingStorey. I wanted the grid to be located in the IfcSite. When I move the IfcGrid from IfcBuildingStorey (in the scene collection) to the IfcSite, save the IFC, and open it again. Then nothing have happened. The IfcGrid is still located in IfcBuildingStorey.

I cant find a way to move my IfcGrid from IfcBuildingStory down the spatial hierarchy to IfcSite.

**Comment by Andrej730** [comment]
@marwiss 
Collections don't represent the hierarchy and assigning different collection doesn't assign object to another spatial element.

To move grid to IfcSite, select IfcGrid and change it's spatial container:
![image](https://github.com/user-attachments/assets/65af4b2b-d984-428e-89cb-e6d26af6b83d)
