### ISSUE TITLE
Borked edgecurves (example files)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#576]
We have a 40Mb IFC file that ends up with over 1GB obj output and a lot of very large and very borked objects. The objects that are borked seems to all have geometry defined by IfcEdgeCurve, but not sure wether the edgecurves are the offending part:

|File|[576--door--wrong-geometry--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/576--door--wrong-geometry--augmented.ifc)|[576--railing--wrong-geometry--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/576--railing--wrong-geometry--augmented.ifc)|[576--buildingElementProxy--wrong-geometry--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/576--railing--wrong-geometry--augmented.ifc)|
|-|-|-|-|
|SimpleBIM|<img width="150" alt="Screenshot 2019-04-24 at 23 08 08" src="https://user-images.githubusercontent.com/4601554/56693923-dc3c6400-66e5-11e9-93b4-42a300aed4be.png">|<img width="150" alt="Screenshot 2019-04-24 at 23 10 00" src="https://user-images.githubusercontent.com/4601554/56694052-29b8d100-66e6-11e9-9566-d9c7e62360cd.png">|<img width="150" alt="Screenshot 2019-04-24 at 23 10 18" src="https://user-images.githubusercontent.com/4601554/56694115-50770780-66e6-11e9-951b-c775f6b72106.png">|
|IfcOpenShell|<img width="150" alt="Screenshot 2019-04-24 at 23 19 01" src="https://user-images.githubusercontent.com/4601554/56694603-62a57580-66e7-11e9-96df-403be8b4ee30.png">|<img width="150" alt="Screenshot 2019-04-24 at 23 20 25" src="https://user-images.githubusercontent.com/4601554/56694761-bd3ed180-66e7-11e9-96c7-37864218720c.png">|<img width="150" alt="Screenshot 2019-04-24 at 23 21 02" src="https://user-images.githubusercontent.com/4601554/56694776-c62fa300-66e7-11e9-88e7-731865c1ba4c.png">|

**Comment by aothms** [comment]
This might be a duplicate of #553 
Do you by any chance miss this commit? https://github.com/IfcOpenShell/IfcOpenShell/commit/e4fdfd2eb38048523ba5be99430fe7772f2dc2ed

**Comment by johanrd** [comment]
Ah, that is correct. Sorry for the confusion. Thanks

**Comment by johanrd** [comment]
Reopening, as 576--door--wrong-geometry--augmented.ifc segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as 576--door--wrong-geometry--augmented.ifc does not segfault on `OCCT 7.5.0`
