### ISSUE TITLE
OpenCascade face serialization is wrong

### ISSUE THREAD

**Issue by nickger** [IfcOpenShell/IfcOpenShell#5763]
Serialization.cpp function convert_to_ifc(const TopoDS_Face& f, IfcSchema::IfcFace*& face, bool advanced) lines 538-539 assume that the first found wire in face topology is external. This is wrong, it has nothing to do with the order in which the wires are saved (we've had a similar discussion about shells). The save way to get outer bound is to use BRepTools::OuterWire(const TopoDS_Face &F). Please, correct.

**Comment by aothms** [comment]
True. Thanks for directing my attention to this.
