### ISSUE TITLE
Construction Sequencing in Browser

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5764]
Using the output in a browser of a work schedule, selecting `Day` view it shows weeks, `Week` shows months and so on

![image](https://github.com/user-attachments/assets/8d54a30d-7ca5-48c2-9953-c63d189d416d)

MS Edge, Blender 4.2.3 Bonsai 0.8.1 241118

thanks

**Comment by steverugi** [comment]
I think it was fixed in 241120, thanks @Andrej730

**Comment by Andrej730** [comment]
Haven't touched it 😅

**Comment by steverugi** [comment]
:)  well we can close the issue anyway (it might have been due to some glitch of the session)
