### ISSUE TITLE
Opening titleblock via sheets UI panel

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5770]
@sboddy 
Before your UI changes to the drawing/sheets panel we could open the titleblock for editing.  See video below. 
Is this possible anymore?

https://github.com/user-attachments/assets/2c08de66-90ad-42eb-9746-7f7c8141998d

**Comment by sboddy** [comment]
Any reason for the dup here? I'm not seeing the reason for what looks like the same report.

Edit: never mind. I see the diff now I'm awake.

**Comment by sboddy** [comment]
Raised a pull request to fix this. Just be sure to use the right icon once merged:
![image](https://github.com/user-attachments/assets/49a9fe6d-aa5b-4e84-b32c-985934f14750)
