### ISSUE TITLE
The measure tool doesn't snap to the 2d objects in drawing view

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5782]
If you open `FLOOR PLAN - 1ST FLOOR` drawing, the measure tool doesn't snap to the 2d equipment. 

https://hub.openingdesign.com/OpeningDesign/Restaurant_MPM/src/commit/2df5569b12d276d02b45e3462cc9c00090d788c9/Open/Models/BlenderBIM/Restaurant_MPM.ifc

https://github.com/user-attachments/assets/d840aaa6-0faa-40a3-8bfb-b2ce27738585

ping @brunoperdigao

**Comment by brunoperdigao** [comment]
@theoryshaw could you test if it's working after https://github.com/IfcOpenShell/IfcOpenShell/commit/99ad9ac3058ed5a82ef594550abac49b64926928 ?

**Comment by theoryshaw** [comment]
Seems to work great! Thanks.
