### ISSUE TITLE
Can't create an elevation drawing

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#5783]
![blender_3Q4hYgwsul](https://github.com/user-attachments/assets/496d342f-1bcf-4580-91e6-207eed3eeb92)
[Simple 1 bed 241118.txt](https://github.com/user-attachments/files/17868162/Simple.1.bed.241118.txt)

Not sure if it is my Model/lack of Bonsai know how or a glitch.

I tried to create an elevation drawing using Blender 4.3 Bonsai 241120, attached is the model, assistance is truly appreciated.

Thanks in advance

**Comment by sboddy** [comment]
The camera origin is behind your geometry. You need to move it in front of  your geometry.

**Comment by Ave-5D** [comment]
Thanks and so we learn
