### ISSUE TITLE
Could you guys add the possibility to load IFC-data from In-Memory bytes (BytesIO)?

### ISSUE THREAD

**Issue by RobinWitzschke** [IfcOpenShell/IfcOpenShell#5784]
Hello Everyone,

I would be intrested in a way to load ifc-data into the ifcopenshell.open() statement with in-memory data, like with BytesIO. 

Currently, you can only load local like data, which means in a webserver like enviroment i have to save my ifc-files as temporary files and then load them into ifc. This feels quite bulky...

**Comment by aothms** [comment]
See `ifcopenshell.file.from_string()`

**Comment by RobinWitzschke** [comment]
Hey Thomas,
thanks for your fast reply, could you link me to some kind of documentation of it?

**Comment by Andrej730** [comment]
@RobinWitzschke see #5193.

**Comment by RobinWitzschke** [comment]
Thanks!
