### ISSUE TITLE
[ENH] Adding a "latest" release

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#5785]
Hello,

it's always a good practice to have a latest release having a fixed name which doesn't have to be constructed dynamically.    
Especially for developers who need to script stuff.

Therefore, do you mind _adding_ a release simply named "latest"?

Because building the filename by hand, e.g. `bonsai_py311-0.8.1-alpha${date_pattern_to_build}-linux-x64.zip` may be prone to error if for whatever reason the naming convention changes in the future.

A fixed filename pattern for the latest releases would be much more convenient, for example:
- bonsai_py311-0.8.1-latest-linux-x64.zip
- bonsai_py311-0.8.1-latest-macos-arm64.zip
- bonsai_py311-0.8.1-latest-macos-x64.zip
- bonsai_py311-0.8.1-latest-windows-x64.zip
- bonsai_py312-0.8.1-latest-linux-x64.zip
- bonsai_py312-0.8.1-latest-macos-arm64.zip
- bonsai_py312-0.8.1-latest-macos-x64.zip
- bonsai_py312-0.8.1-latest-windows-x64.zip

Or:
- bonsai_py311-latest-linux-x64.zip
- bonsai_py311-latest-macos-arm64.zip
- bonsai_py311-latest-macos-x64.zip
- bonsai_py311-latest-windows-x64.zip
- bonsai_py312-latest-linux-x64.zip
- bonsai_py312-latest-macos-arm64.zip
- bonsai_py312-latest-macos-x64.zip
- bonsai_py312-latest-windows-x64.zip

Of course, this doesn't have to replace the actual pattern using a date.

Thanks!

**Comment by Andrej730** [comment]
@swiss-knight 

This would make things more confusing as 'latest' can be different any day, any hour - release archives would be unidentifiable.

Depends on your usecase you can either get latest release from github releases using github API or refer to index.json from https://github.com/IfcOpenShell/bonsai_unstable_repo, it's the json Blender unstable repo is using to figure out whether Bonsai needs to be updated when users start Blender.

**Comment by Andrej730** [comment]
Also, if you working on a script that installs Bonsai you can use Blender command line arguments that take working with index.json - https://docs.blender.org/manual/en/latest/advanced/command_line/extension_arguments.html
