### ISSUE TITLE
ifcopenshell.api.geometry.add_slab_representation, list [ifcopenshell.util.data.Clipping] parameter

### ISSUE THREAD

**Issue by tibohu** [IfcOpenShell/IfcOpenShell#5792]
### Discussed in https://github.com/IfcOpenShell/IfcOpenShell/discussions/5712

<div type='discussions-op-text'>

<sup>Originally posted by **tibohu** November  7, 2024</sup>
ifcopenshell.api.geometry.add_slab_representation
--------------------------------------------------------
Hi! Could anyone help me by providing an example of this function?
I want to clip the slab with two planes. For simplicity let's say by the zy and zx planes.
How to use the clippings: list [ifcopenshell.util.data.Clipping] parameter?(https://docs.ifcopenshell.org/autoapi/ifcopenshell/util/data/index.html#ifcopenshell.util.data.Clipping)</div>

**Comment by Andrej730** [comment]
added example, see the method description in the last commit

**Comment by tibohu** [comment]
Thank you for being so helpful.
