### ISSUE TITLE
Profile creation | IfcArbitraryClosedProfileDef

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5796]
I really enjoyed the new feature where a mesh object can be used to create an arbitrary profile
an alert would be useful to inform user that
* select an object using the eyedrop
* the object must be a closed mesh
* It must have a face (Edit > A > F) 

currently it says

![image](https://github.com/user-attachments/assets/1eb93ae8-f3a8-46e0-ac2d-b70be27c02ff)

which, in my opinion, is not very intuitive, especially given the  _technicalese_ style of it ;))
thanks

**Comment by Andrej730** [comment]
See UI after https://github.com/IfcOpenShell/IfcOpenShell/commit/29f9f04d928f21f8e0063bee0b22a77f12c05fce, that should cover it.
