### ISSUE TITLE
IfcCovering | Horizontal layer Issues

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5797]
as of 241123 IfcCovering presents some issues
* horizontal layer's polyline not possible to edit it once object is created 
* change of thickness affects its Y dimension, not its Z
* Z is editable via top menu `H`, which is maybe not appropriate?

thanks

**Comment by brunoperdigao** [comment]
@steverugi Could you please test if https://github.com/IfcOpenShell/IfcOpenShell/commit/4f6e2586e122eeed46323a46fac4c36e14ec3405 solves all those issues?

**Comment by steverugi** [comment]
hi @brunoperdigao 
all works well, many thanks for your assistance

**Comment by brunoperdigao** [comment]
@steverugi Great. I'll close this now, feel free to reopen if you find other issues.
