### ISSUE TITLE
Entity Inheritance in ifcopenshell and ifctester 

### ISSUE THREAD

**Issue by astridvdl** [IfcOpenShell/IfcOpenShell#5804]
ifcopenshell honours entity inheritance where ifctester appears not to.

Given an .ifc file with an IfcSlab and IfcWallStandardCase with the necessary properties and property sets

and an ids test:
```
The model MUST contain entities that have
IFC class IFCELEMENT
that MEET the following requirements
MUST HAVE property CustomProperty of PSet CustomPSet
```

ifcopenshell will correctly return 2 elements with the line below:
`ifcopenshell.util.selector.filter_elements(file_name, "IfcElement")`

where ifctester will validate the above ifc and ids as 
`Fail 0/0`

**Comment by aothms** [comment]
ifctester conforms to the IDS spec, where it was decided *not* to incorporate inheritance in the evaluation of the entity facet: https://github.com/buildingSMART/IDS/issues/356

**Comment by astridvdl** [comment]
Thanks for the link, it seems as though it is still an open discussion. 
From a programming point of view, IFCs include inheritance, so it caught me off guard that it is intentionally not honoured in IDS.

**Comment by aothms** [comment]
It's open for discussion to some extent, but not for the already published
ids v1.0 :)

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op di 26 nov 2024 14:09 schreef astridvdl ***@***.***>:
