### ISSUE TITLE
Feature request: Choose profile for new profile based types

### ISSUE THREAD

**Issue by jes-r** [IfcOpenShell/IfcOpenShell#5814]
Hi,

When you add an extruded profile based type, e.g. a new beam, I believe it takes the first (alphabetical) profile as default. 

Then you have to add an instance to the project and then edit it to change to the profile type you want.

Would it be an idea to add another button here or under the others that pops up when you select 'Extruded Profile', where you select which profile?

![image](https://github.com/user-attachments/assets/41bdb15a-e601-4d8b-a0a7-aaf609aa88ec)

**Comment by theoryshaw** [comment]
love it.

**Comment by steverugi** [comment]
solid YES please
