### ISSUE TITLE
Group selecting not working for specific Type name

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#5823]
Attached is my IFC file, when selecting all the element with the same name does not work as attached video, for other elements it does work, I don’t know what my error is.
Thanks in advance.
![dP8R60oo8v](https://github.com/user-attachments/assets/74440f9f-7e68-4ed4-8ea7-1cfba7e2f7d3)
[Simple 1 bed Today.txt](https://github.com/user-attachments/files/17947362/Simple.1.bed.Today.txt)

**Comment by sboddy** [comment]
All of your copper pipes have a different name though. They have been numbered, so xyz.002, or in some cases (pun intended) the case is different, i.e. cu versus Cu.
The ones where it works, the elements somehow have the same name under attributes, but a different name in the organiser.

**Comment by Ave-5D** [comment]
Thanks for the feedback, 
I did not create the number it was done by Bonsai, I selected the element and then added a name and applied it for all the selected elements, Bonsia then adds the numbering.
Followed the same proces for my other Types and it worked. 
Thought it could be due to the space in the name that is why I started changing the Name to "15mm-cu-Hot", before it was "15mm Copper Hot"
Don't know how the name in attributes and orginiser differ, I was busy imputing elements into a BoQ and changing some element names.
Hope this helps, thanks for your effort

**Comment by theoryshaw** [comment]
Quick way to fix...

https://github.com/user-attachments/assets/bd85db26-937f-4e50-a9f1-b0b5af2674c2

**Comment by Ave-5D** [comment]
Hi Ryan, thanks a million for your feedback.

[Simple 1 bed Today.txt](https://github.com/user-attachments/files/17955487/Simple.1.bed.Today.txt)
I have attached a video to show what I have done, and I still can’t get it to worknow the group selection does not select another element

I hope this helps.

Kind regards and your accomplishments with pushing BIM to its real function is a ray of light.

Stay strong.
![6xNE2VXkyf](https://github.com/user-attachments/assets/fc956adc-b916-4584-94fa-ea7b079c876d)
