### ISSUE TITLE
Wrong information in model space

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5825]
Picture explains it pretty well, the object belongs to the 2nd floor but in the 3d space it's always showing 1. There is a disconnect between that information.
<img width="1473" alt="Screenshot 2024-11-28 at 16 24 24" src="https://github.com/user-attachments/assets/1f509a0e-f57d-4a98-8a7b-fdded8140853">

**Comment by Andrej730** [comment]
@BIMvoice Blender viewport is showing currently active collection which is unrelated to the currently active object, so there's no contradiction. See video below.


https://github.com/user-attachments/assets/a42f1b62-99dc-4cf3-940a-e080d12f7e53
