### ISSUE TITLE
Help in installing v0.8.0 for aws lamda

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#5826]
Hi,
I'm trying to install ifcopenshell v0.8.0 for aws lamda.
The [docker file ](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/aws/lambda/Dockerfile#L16) however points to ifcopenshell build of "39-v0.7.0-476ab50". 
Could anyone point me to the IFC_OPENSHELL_BUILD for v0.8.0

**Comment by aothms** [comment]
https://builds.ifcopenshell.org/
