### ISSUE TITLE
version confusion between 0.5, 0.6, 0.7

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#583]
Hi Thomas,

AFAIK IfcOpenShell 0.5 is not official released. There is no 0.5 branch. But 0.6 and 0.7 development have started already. Means there are three versions developed at once ? 

I am a bit lost here? The last entry on http://blog.ifcopenshell.org/ is 3.5 years old. The one before is the one from 0.4 version.

Would it be possible to bring some light in my darkness.

BTW: the master branch (which is dev branch for 0.5 AFAIK) works great on FreeCAD on Windows, OSX and Linux :-) For Windwos and OSX we gone take IfcOpenBot builds.

cheers bernd

**Comment by aothms** [comment]
> Means there are three versions developed at once ?

Unfortunately basically yes. In general, the lower the version number, the more stable, but less features. I get different outside contributions with uncertain timelines. I also have my own commercial consultancy projects. This code then needs to be parked somewhere.

v0.6: multiple schemas at runtime, some geometry handling improvements related to facesets, binary glTF serializer (soon: multi-threading)

v0.7: CGAL geometry handling

**Comment by berndhahnebach** [comment]
Thanks for the information Thomas. Got the point. Is there a timeline for 0.5 release? Might be time to do a release. 0.4 is years back!

bernd

**Comment by aothms** [comment]
Yes, 0.5 release is imminent. An additional preview for 0.6 as well!

**Comment by berndhahnebach** [comment]
Offtopic Thomas. Do you know what is IfcOpenBot (https://github.com/IfcOpenBot/IfcOpenShell/commits/master) based on? Is there some information about this available?

**Comment by aothms** [comment]
It's just synced with IfcOpenShell/IfcOpenShell whenever a new build is started. Is that what you mean?

**Comment by berndhahnebach** [comment]
No, how does it works. AFAIK Github has not a build server. Means somewhere else the builds must be done and than uploaded to github. This seams not to bo done by a human. This seams to be done by a script or whatever. This whatever is what I am interested in.

bernd

**Comment by aothms** [comment]
Oh right, I have a machine with a bunch of VMs that are configured to build everything. It's fully automated, I just need to power on the machine and run a script and that's what's causing the delays.

**Comment by berndhahnebach** [comment]
wow thomas souns cool. Do you use vagrant? It is what I use for similar stuff and Linux VMs. Is the github upload done in the script too?

 Would you give some more information? May be a blog entry, or academy entry or forum entry or ... Are the scripts open source? This might be interesting for FreeCAD too. Native builds are done manually. What is automated are conda builds for all three major plattforms.

**Comment by berndhahnebach** [comment]
BTW:
FreeCAD runs flawless with IfcOpenShell 0.5 on the three major plattforms! Ifc import and export wprks great except the usual smaller problems with all the different spreaded ifc around.

**Comment by aothms** [comment]
> wow thomas souns cool. Do you use vagrant? It is what I use for similar stuff and Linux VMs. Is the github upload done in the script too?

> Would you give some more information? May be a blog entry, or academy entry or forum entry or ... Are the scripts open source? This might be interesting for FreeCAD too. Native builds are done manually. What is automated are conda builds for all three major plattforms.

It's all custom built using just bash / ssh. Cygwin on Windows. It runs on tiny Mac Mini for the license restrictions on virtualized OSX. I have been meaning to write about it, just busy. Thanks for the encouragements. The basis is just the build scripts in the repository, so to a large extent this is all due to @Stinkfist0 magnificent work on the win build scripts.

**Comment by berndhahnebach** [comment]
Thanks Thomas.

**Comment by berndhahnebach** [comment]
Thomas, would you recommend to use 0.6 in official FreeCAD releases?

**Comment by aothms** [comment]
Most people that communicate with are using 0.6. BIMserver for example and the guys reporting here https://github.com/IfcOpenShell/IfcOpenShell/issues/595#issuecomment-497629035

It's not unlikely that there will be files that fail on 0.6 and work on master, but my guess is that the number is smaller than the other way around. Combined with the benefit of multiple schemas, I'd say go for it :)

The biggest problem with 0.6 that's stopping me for merging it into master is that there are still some issues building shared libraries on Windows.

**Comment by berndhahnebach** [comment]
and there is ifcopenbot as well for 0.6 ...

FYI: I will for the following suggestion on FreeCAD Forum. For just released FreeCAD 0.18.2 stay with 0.5 and for FreeCAD 0.19 switch to 0.6 

cheers bernd

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=39&t=36754

**Comment by berndhahnebach** [comment]
Any updates for the timeline if there will be a 0.5 or even 0.6 release

**Comment by aothms** [comment]
0.5 is now at RC. A couple commits came in after that I'll likely jump to final immediately.

0.6 is pretty stable but there are a couple of features from external contributors that may come in. Also multi-threading is a bit rough still.

0.7 something stable is at least 1/2 - 1 year away.

**Comment by berndhahnebach** [comment]
> 0.5 is now at RC. A couple commits came in after that I'll likely jump to final immediately.
> 

haha business as usual ...

thanks for the informations. On FreeCAD dev packages we jumped to 0.6 because it is pretty stable already and saves us a lot off headache because people try to import both IFC2x3 and IFC4 files into FreeCAD anyway.

cheers bernd

**Comment by berndhahnebach** [comment]
It seams current development does take place in 0.7.0 branch. Is this true?

How about the 0.6 release? Will there ever be a 0.6 release? Will this just be omitted? Is ifcopenshell switching to a rolling release?

cheers bernd

**Comment by aothms** [comment]
Yes, true.

If there is a interest in the community in a 0.6 final or rc then I don't mind. But then I really need some help with figuring out which commits to backport and to do the testing. The thing is that nobody really seems to care...

**Comment by berndhahnebach** [comment]
I do not care either. Since I have not been here for a while, I just wanted to know. 

I upgraded to 0.7.0 already 

cheers bernd
