### ISSUE TITLE
Why different element number?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5833]
Guys, what's happening here? Why is it showing 324 elements when there are only 255 actually? Is it including all the spaces and other stuff or what's the explanation for this?

<img width="607" alt="Screenshot 2024-12-01 at 07 49 45" src="https://github.com/user-attachments/assets/8da267d6-479d-4b55-86cc-47b9141df1ba">

**Comment by Andrej730** [comment]
324 elements are including the elements directly assigned to the IfcBuilding, not through nested relationship with it's storeys.
