### ISSUE TITLE
Error when editing the header information

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5834]
I get this error when I edit the Heard Information in the section Project Info under the Project Overview Tab. I use Blender 4.3 with latest Bonsai build.

```
Python: Traceback (most recent call last):
  File "/Users/petru/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/project/operator.py", line 596, in execute
    props.authorisation = self.file.wrapped_data.header.file_name.authorization
    ^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: BIMProjectProperties.authorisation doesn't support None from string types
```

**Comment by Andrej730** [comment]
Run validation on the IFC file, this file's header appears to be invalid. I assume your file has invalid "authorization" field - it's supposed to be some string (at least an empty string `''`), not none (not `$`).

I've added a workaround as we do handle similar `None` values in other header fields, though they are invalid too.
