### ISSUE TITLE
Types imported from custom library don't have geometry

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5835]
I am importing some object types using a custom library and I get only the definitions without any geometry.

Any idea why?

This is the model I try to bring the types from:

[12345_123456_1234567_RIB_0_0.ifc.zip](https://github.com/user-attachments/files/17968115/12345_123456_1234567_RIB_0_0.ifc.zip)

**Comment by Andrej730** [comment]
Types in the provided library have no geometry, so there's nothing to append to the other project.

![image](https://github.com/user-attachments/assets/f94040d7-3715-4cfc-8151-a195340aaf53)
