### ISSUE TITLE
ifcTester ignores specification's ifcVersion

### ISSUE THREAD

**Issue by Miyate2** [IfcOpenShell/IfcOpenShell#5836]
Problem：Passes the verification even if the IFC version and IDS version are different
IFC version: IFC4X3_ADD2
IDS version: IFC2X3
sampleData
[sample (2).zip](https://github.com/user-attachments/files/17972279/sample.2.zip)

If you do not control the version, there is no point in specifying the version in IDS, so please fix this.

**Comment by aothms** [comment]
I don't know what the latest consensus is for IDS 1.0. I know it has been under discussion. But given the test case in the IDS repo it seem to me that IfcTester is correct. The IFC version in IDS is only meta-data and not intended to be checked against.

https://github.com/buildingSMART/IDS/blob/development/Documentation/ImplementersDocumentation/TestCases/ids/pass-specification_version_is_purely_metadata_and_does_not_impact_pass_or_fail_result.ids

**Comment by Andrej730** [comment]
Closing until https://github.com/buildingSMART/IDS/issues/103 is resolved.
