### ISSUE TITLE
GV_PRECISION too strict on non-planar outer_face_bounds?

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#584]
1. Convert [584--wall--outer_face_bound--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/584--wall--outer_face_bound--augmented.ifc)  and experience that two of the faces are not converted:
<img width="350" alt="Screenshot 2019-05-10 at 11 02 45" src="https://user-images.githubusercontent.com/4601554/57515534-2b53dd00-7313-11e9-9c1a-59bf9b8ea5fb.png">

`Error: Failed to process face boundary`

The reason seems to be because the y values are not on the same plane :
```
#75943= IFCFACEOUTERBOUND(#75942,.T.);
#75942= IFCPOLYLOOP((#75838,#75837,#75862,#75855,#75854,#75938,#75849,#75844));
#75837= IFCCARTESIANPOINT((6.65895640850067E-08,-125.,-534.998456855255));
#75862= IFCCARTESIANPOINT((6.65895640850067E-08,-125.,-1500.));
#75938= IFCCARTESIANPOINT((6.65895640850067E-08,-125.,1500.));
#75849= IFCCARTESIANPOINT((0.00445566582493484,-125.001743464498,-334.998456855255));
#75838= IFCCARTESIANPOINT((700.004456683761,-125.001726375893,-534.998456855255));
#75844= IFCCARTESIANPOINT((700.004456683761,-125.001726375893,-334.998456855255));
#75854= IFCCARTESIANPOINT((6549.99998592678,-124.999996509869,1500.));
#75855= IFCCARTESIANPOINT((6549.99998592678,-124.999996509869,-1500.));
```

`GV_PRECISION` is derived from `IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#10,$);`, which technically makes IfcOpenShell correct, I guess.

Changing the precision to `1.E-04` converts the faces without complaints:
<img width="350" alt="Screenshot 2019-05-10 at 11 14 05" src="https://user-images.githubusercontent.com/4601554/57516304-c39e9180-7314-11e9-83af-be863d12f1c0.png">

2. Open the same file in Solibri, SimpleBIM, DDS, BIMVision etc. and see that basically all viewers are "forgiving" regarding this modeling precision:
<img width="350" alt="Screenshot 2019-05-10 at 11 13 08" src="https://user-images.githubusercontent.com/4601554/57516238-a073e200-7314-11e9-8f52-53db3b177304.png">

This makes me question wether it could be wise to be more forgiving than `GV_PRECISION` when converting outer_face_bounds. May it be an idea to multiply `getValue(GV_PRECISION)` by `10` (or `100`)  [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/944813146ebb31bc7c4274b1c8316f382d7fde11/src/ifcgeom/IfcGeomFaces.cpp#L253)?

**Comment by aothms** [comment]
There is a partial solution already implemented (triangulate the non-planar faces, because high tolerances can cause issues later on) but it does not fully work yet with inner boundaries which is the case here. I'll try to finish up on that next week.

**Comment by aothms** [comment]
This is fixed now in https://github.com/IfcOpenShell/IfcOpenShell/commit/1d5e560e667a300470a93f0ed1c53d57bd80482b

![afbeelding](https://user-images.githubusercontent.com/1096535/57922346-d4647f80-789f-11e9-8191-f245e0bab2ee.png)

Note: This is probably going to be the last significant code change I can do in the v0.6.0 branch as I really need to freeze that with several companies waiting for me to give it an official release status. So naturally the issues you are reporting are still welcome, but if they require extensive changes they'll likely be part of 0.7

**Comment by johanrd** [comment]
Thanks, verified – this now works after 1d5e560

Ok, I understand. We can continue reporting from the v0.7.0 branch. However, we need to have the performance regressions sorted out before we can use v0.7.0 as standard (or even latest 0.6.0). At the moment we have pinned 42e00581cd187309ebea1aba585fae06dd7dd13f (later versions are prone to timeout).

**Comment by johanrd** [comment]
Reopening, as this file segfaults on OCCT 7.4.0 (with e37c882)

**Comment by johanrd** [comment]
closing, as this converts successfully on `OCCT 7.5.0`
