### ISSUE TITLE
[Regression] IfcConvert - Incorrect values on object placement 

### ISSUE THREAD

**Issue by Pourfex** [IfcOpenShell/IfcOpenShell#5840]
Hello,

While trying to update to latest 8.1 version (IfcOpenShell IfcConvert 0.8.1-0b0e417 (OCC 7.8.1)); we found several regression in our tests pipelines which are both testing macOS m1 and Linux version of IfcConvert.

The smallest example is there : 
[BuildingSmart-IFC4X1.ifc.zip](https://github.com/user-attachments/files/18004742/BuildingSmart-IFC4X1.ifc.zip)

Using our current IfcConvert version : IfcOpenShell IfcConvert 0.7.11-03935a91d (OCC 7.5.3)

We have for xml conversion (using /IfcConvert --use-element-guids *.ifc *.xml) :

`<?xml version="1.0" encoding="utf-8"?>
<ifc xmlns:xlink="http://www.w3.org/1999/xlink">
	<header>
		<file_description>
			<description/>
			<implementation_level>2;1</implementation_level>
		</file_description>
		<file_name>
			<author/>
			<organization/>
			<name/>
			<time_stamp>2019-03-20T15:56:21</time_stamp>
			<preprocessor_version>BuildingSmart IfcKit by Constructivity</preprocessor_version>
			<originating_system>IfcDoc 12.0.0.0</originating_system>
			<authorization/>
		</file_name>
		<file_schema>
			<schema_identifiers>IFC4X1</schema_identifiers>
		</file_schema>
	</header>
	<units>
		<IfcSIUnit UnitType="LENGTHUNIT" Prefix="MILLI" Name="METRE" SI_equivalent="0.001"/>
		<IfcConversionBasedUnit UnitType="PLANEANGLEUNIT" Name="degree" SI_equivalent="0.017453293000000002"/>
	</units>
	<connections/>
	<properties/>
	<quantities/>
	<work>
		<schedules/>
		<plans/>
	</work>
	<calendars/>
	<types/>
	<layers/>
	<groups/>
	<materials/>
	<decomposition>
		<IfcProject id="0xScRe4drECQ4DMSqUjd6d" Name="proxy with brep">
			<IfcBuilding id="2FCZDorxHDT8NI01kdXi8P" Name="Test Building" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1" CompositionType="ELEMENT">
				<IfcBuildingElementProxy id="1kTvXnbbzCWw8lcMd1dR4o" Name="P-1" Description="sample proxy" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 1000 0 0 1"/>
			</IfcBuilding>
		</IfcProject>
	</decomposition>
</ifc>
` 

and for the latest 8.1 version (applies also to 7.1 latest version) : 
`<?xml version="1.0" encoding="utf-8"?>
<ifc xmlns:xlink="http://www.w3.org/1999/xlink">
	<header>
		<file_description>
			<description/>
			<implementation_level>2;1</implementation_level>
		</file_description>
		<file_name>
			<author/>
			<organization/>
			<name/>
			<time_stamp>2019-03-20T15:56:21</time_stamp>
			<preprocessor_version>BuildingSmart IfcKit by Constructivity</preprocessor_version>
			<originating_system>IfcDoc 12.0.0.0</originating_system>
			<authorization/>
		</file_name>
		<file_schema>
			<schema_identifiers>IFC4X1</schema_identifiers>
		</file_schema>
	</header>
	<units>
		<IfcSIUnit UnitType="LENGTHUNIT" Prefix="MILLI" Name="METRE" SI_equivalent="0.001"/>
		<IfcConversionBasedUnit UnitType="PLANEANGLEUNIT" Name="degree" SI_equivalent="0.017453293000000002"/>
	</units>
	<connections/>
	<properties/>
	<quantities/>
	<work>
		<schedules/>
		<plans/>
	</work>
	<calendars/>
	<types/>
	<layers/>
	<groups/>
	<materials/>
	<decomposition>
		<IfcProject id="0xScRe4drECQ4DMSqUjd6d" Name="proxy with brep">
			<IfcBuilding id="2FCZDorxHDT8NI01kdXi8P" Name="Test Building" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 7.9544568980440694e-322 4.7996643521799739e-316 0 1" CompositionType="ELEMENT">
				<IfcBuildingElementProxy id="1kTvXnbbzCWw8lcMd1dR4o" Name="P-1" Description="sample proxy" ObjectPlacement="1 0 0 0 0 1 0 0 0 0 1 0 8.5142332747822017e-320 0 0 1"/>
			</IfcBuilding>
		</IfcProject>
	</decomposition>
</ifc>`

Notice how 0 becomes *e-3** values and even some values are wrong (0 instead of 1000).
We find that previous behaviour was correct.

Happy to discuss on this, we have several other examples.

**Comment by aothms** [comment]
Wow that was an obvious issue.

I know we're not best in class in terms of test case coverage. It doesn't help that we have such as extensive ecosystem of modules, serialization formats, use cases. But hope we can catch up over time.

If you have internal test cases, why not run them on our pipelines?

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/.github/workflows/ci.yml

It'll probably save time for both of us because it cuts out the communication layer and helps us to catch issues when we introduce them and you have test coverage for the things that matter. Apparently this ObjectPlacement interpretation in XML is not used that much...
