### ISSUE TITLE
Blender BIM Bonsai PSet Properties

### ISSUE THREAD

**Issue by qwertylf** [IfcOpenShell/IfcOpenShell#5842]
Hello! I'm trying to get all properties of an object through the code. My object has different classes of Occurrence Properties and I want  to get all of them. It's not important whether it will be in one list or it will be separated. I'm using blender BIM Bonsai to create an IFC project and I get all the commands from blender interface (I didn't find bonsai python API). Here is an image of how classes of my object looks like:
![1](https://github.com/user-attachments/assets/cf92f2cb-375e-475e-b139-e3a50ef7065e)
I'm trying to get properties with def:

```
def GetPreviousValues(curObj):
    prevValues = []
    for value in bpy.data.objects[curObj.name].PsetProperties.properties:
        if (value.metadata.is_null):
            prevValues.append(None)
        else:
            if (value.metadata.string_value != None):
                prevValues.append(value.metadata.string_value)
            elif (value.metadata.float_value != None):
                prevValues.append(value.metadata.float_value)
            else:
                prevValues.append(None)
    return prevValues
```
But the list bpy.data.objects[curObj.name].PsetProperties.properties contains only properties of the last class. Even if I try to delete this class and get properties of next class it doesn't work properly, the list contains only "None" values. 
Can anyone explain what am I doing wrong? I scratched my head with this problem

**Comment by Andrej730** [comment]
@qwertylf Hi! Blender attributes just store the data when it's needed for display, you should access IFC data directly.

You can get IFC entity from any Blender object using `tool.Ifc.get_entity` (see the snippet below) and then use it with https://docs.ifcopenshell.org/autoapi/ifcopenshell/util/element/index.html#ifcopenshell.util.element.get_psets

```python
import bonsai.tool as tool
import bpy

element = tool.Ifc.get_entity(bpy.context.active_object)
```

**Comment by qwertylf** [comment]
@Andrej730 thank you, it was very helpful! I finally get how to acces to ifcopenshell in code, everything is much clearier now. Thanks for fast response!
