### ISSUE TITLE
Current version of GLIBC 2.38 in IfcConvert doesn't work on EC2 Amazon Linux last version (2023.6.20241121)

### ISSUE THREAD

**Issue by csritter** [IfcOpenShell/IfcOpenShell#5847]
Hi, I did a build using nix/build-all.py with BUILD_CFG in Release and I got the next error:
```
./IfcConvert: /lib64/libc.so.6: version `GLIBC_2.38' not found (required by ./IfcConvert)
./IfcConvert: /lib64/libm.so.6: version `GLIBC_2.38' not found (required by ./IfcConvert)
```

The Amazon Linux has the version 2.34.
Is there something I can do to run on this machine on the IfcConvert config side?

**Comment by aothms** [comment]
Not easily. Change your build machine. We build on rocky 8 now. https://github.com/IfcOpenShell/IfcOpenShell/blob/c4ffc06a8871b9e2caa3d8d69e08af2761ca517a/.github/workflows/build_rocky.yml#L12

You might not need to build your own version anyway:

https://builds.ifcopenshell.org/

**Comment by csritter** [comment]
Hi @aothms, I changed the build machine to a Ubuntu 24.04.
It was a headache to change the machine and redo the system, but now it's working 100%.

Thanks for the tips, I'll close this issue.
