### ISSUE TITLE
Loading index maps takes long time opening IFC file

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5848]
This IFC file gets hung up when opening in Bonsai.  
https://hub.openingdesign.com/OpeningDesign/212_s_henry_street/src/commit/4a0e31b2def24f7c866187fbe897f7f8b10ea790/Transfer/20241206%20-%20to%20owner%20-%20review%20of%20stair%20design%20-%20Copy/IFC%20files/212_S_Henry_St_Existing.ifc

**Comment by Andrej730** [comment]
It wasn't really hanging, it was just taking too long. Should work better after updates but still takes time.

**Comment by theoryshaw** [comment]
very cool.. thx!
