### ISSUE TITLE
Assigning textures to the IFC materials.

### ISSUE THREAD

**Issue by Anton-Des** [IfcOpenShell/IfcOpenShell#5853]
Hello. I made the project in IFC format and then saved it in blender format. In it, I can't assign the IFC texture to the objects, it doesn't display correctly (just a solid color). Everything is fine with the new objects. Blender 4.3.2 Bonsai v0.8.0
I used this video as an instruction, in it the author succeeds (from 52 minutes) https://www.youtube.com/watch?v=ZyRzAX4x-FQ&t=3195s
<img width="1274" alt="Знімок екрана 2024-12-07 191448" src="https://github.com/user-attachments/assets/7feeee51-0d86-4354-a64e-724fc67ba8dc">
<img width="685" alt="Знімок екрана 2024-12-07 192529" src="https://github.com/user-attachments/assets/b4a45b67-e543-4dfd-aee1-8f212765fe61">

**Comment by Andrej730** [comment]
@Anton-Des your objects have no UV, therefore objects sample first pixel of the texture everywhere. 

You can use "Generated" in "Texture Coordinate" node instead, it will use autogenerated UV:
![image](https://github.com/user-attachments/assets/ae9f077f-7f88-44c8-82f3-a472eb20d1e5)

No idea why it works in the video - could be that materials in the video were using generated UV by default. It's also possible to save UV to IFC but it's more complicated topic and it's not usually done for simple walls.

**Comment by Anton-Des** [comment]
@Andrej730 Thank you. Not everything is as fast as the author of the video, but by playing with UV, you can get the desired result.
<img width="540" alt="Знімок екрана 2024-12-09 193825" src="https://github.com/user-attachments/assets/0f21a408-c3f1-4a04-acd4-a32c27e6f0a0">
