### ISSUE TITLE
IfcSweptDiskSolid does not apply InnerRadius correctly, resulting in missing hole

### ISSUE THREAD

**Issue by tkato2024** [IfcOpenShell/IfcOpenShell#5859]
It seems that the `InnerRadius` attribute of `IfcSweptDiskSolid` is not correctly interpreted by IfcOpenShell. When visualizing the attached IFC file, the expected hole in the swept disk solid is not rendered in Blender, which relies on IfcOpenShell for geometry processing. However, the same file displays correctly in BIMvision, indicating that the issue lies in how IfcOpenShell handles the `InnerRadius` attribute.

![image](https://github.com/user-attachments/assets/e118a32e-31ab-4288-a11e-920e6e0bc7a6)

The IFC file used is as follows:

```ifc
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition[DesignTransferView]'),'2;1');
FILE_NAME('/dev/null','2024-12-09T22:41:23+09:00',(),(),'IfcOpenShell 0.8.0','IfcOpenShell 0.8.0','Nobody');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCPROJECT('3wP9LK8X97LR1czmoSXC0h',$,'My Project',$,$,$,$,(#10),#5);
#2=IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);
#3=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#4=IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
#5=IFCUNITASSIGNMENT((#4,#2,#3));
#6=IFCCARTESIANPOINT((0.,0.,0.));
#7=IFCDIRECTION((0.,0.,1.));
#8=IFCDIRECTION((1.,0.,0.));
#9=IFCAXIS2PLACEMENT3D(#6,#7,#8);
#10=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#9,$);
#11=IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Body','Model',*,*,*,*,#10,$,.MODEL_VIEW.,$);
#12=IFCSITE('2QylkfCa90RRBs$7zm_6VO',$,'My Site',$,$,$,$,$,$,$,$,$,$,$);
#13=IFCBUILDING('11gKVmPST0UfNIutf2zdMo',$,'Building A',$,$,$,$,$,$,$,$,$);
#14=IFCBUILDINGSTOREY('321Z9tdQD4Xuupd7KZYSYx',$,'Ground Floor',$,$,$,$,$,$,$);
#15=IFCRELAGGREGATES('0$EPCbtn141v_Y$zkh1MUy',$,$,$,#1,(#12));
#16=IFCRELAGGREGATES('0$cJeEfgv8M9XpyuwJwkMK',$,$,$,#12,(#13));
#17=IFCRELAGGREGATES('2cprXWZiv8ZhQ1uvaqgm_n',$,$,$,#13,(#14));
#18=IFCBUILDINGELEMENTPROXY('13FI_7CeD8vh3_fVpUdyLg',$,$,$,$,#34,#28,$,$);
#24=IFCCARTESIANPOINTLIST2D(((0.,0.),(300.,0.)));
#25=IFCINDEXEDPOLYCURVE(#24,$,$);
#26=IFCSWEPTDISKSOLID(#25,50.,40.,$,$);
#27=IFCSHAPEREPRESENTATION(#11,'Body','AdvancedSweptSolid',(#26));
#28=IFCPRODUCTDEFINITIONSHAPE($,$,(#27));
#29=IFCRELCONTAINEDINSPATIALSTRUCTURE('3pWQZrr0jF6OvJsxww1t$S',$,$,$,(#18),#14);
#30=IFCCARTESIANPOINT((0.,0.,0.));
#31=IFCDIRECTION((0.,0.,1.));
#32=IFCDIRECTION((1.,0.,0.));
#33=IFCAXIS2PLACEMENT3D(#30,#31,#32);
#34=IFCLOCALPLACEMENT($,#33);
ENDSEC;
END-ISO-10303-21;
```

Let me know if additional information are needed. Thank you for your support in resolving this issue.

**Comment by aothms** [comment]
Thanks @Andrej730 

@tkato2024 for some geometric forms Bonsai has its own custom handling using Blender's built-in functionality and does not depend on ifcopenshell's core shape processing routines in C++ relying on cgal or opencascade.

**Comment by tkato2024** [comment]
@aothms 
Thank you for your response. However, I believe this issue lies within IfcOpenShell's core shape processing rather than Bonsai's custom handling. I have attached additional information and examples, including an image and the code used to create it, to demonstrate that the `InnerRadius` attribute of `IfcSweptDiskSolid` is not being correctly interpreted by IfcOpenShell itself, as the issue persists when using IfcOpenShell directly.

![newplot](https://github.com/user-attachments/assets/268f1b47-9c06-439c-b190-0337795fb114)

```py
import plotly.graph_objects as go
import numpy as np
import ifcopenshell.geom
import ifcopenshell

model = ifcopenshell.open("SweptDiskSolid.ifc")
settings = ifcopenshell.geom.settings()

meshes = []
iterator = ifcopenshell.geom.iterator(settings, model, 1)
if iterator.initialize():
    while True:
        shape = iterator.get()
        verts = shape.geometry.verts
        verts = np.array(verts).reshape(-1, 3)
        faces = shape.geometry.faces
        faces = np.array(faces).reshape(-1, 3)

        mesh = go.Mesh3d(
            x=verts[:, 0],
            y=verts[:, 1],
            z=verts[:, 2],
            i=faces[:, 0],
            j=faces[:, 1],
            k=faces[:, 2],
            flatshading=True,
            lighting=dict(ambient=1, diffuse=0),
        )
        meshes.append(mesh)

        if not iterator.next():
            break

fig = go.Figure(data=meshes)
fig.update_layout(scene_aspectmode="data")
fig.write_html("SweptDiskSolid.html", include_plotlyjs="cdn", full_html=True)
```

Could you please consider reopening this issue for further investigation?

**Comment by Andrej730** [comment]
Can confirm the same issue using the latest ifcopenshell build if I disable importing swept disk solids as Blender curves:
![image](https://github.com/user-attachments/assets/0028ba29-60c5-457c-8d80-e24a7c574227)

**Comment by aothms** [comment]
Thanks both, I was a bit lazy. Should be correctly implemented now.

![afbeelding](https://github.com/user-attachments/assets/8f886ee8-f6de-4578-8224-bf12540bf8f5)

**Comment by Andrej730** [comment]
Can confirm it's working now for me too. Can't update build in Bonsai - OSX build for IfcOpenShell seems to be failing.

**Comment by tkato2024** [comment]
Thank you for the update. I was able to confirm on my end as well—InnerRadius is now displayed correctly after building on Windows 11. 
![スクリーンショット 2024-12-12 235337](https://github.com/user-attachments/assets/2b04fa18-1a3f-40cc-bf78-b3df2cc4d73a)

**Comment by aothms** [comment]
Thanks for cross checking :)
