### ISSUE TITLE
Void cannot be used, Apply Void missing _blender 4.3.1, Bonsai v0.8.0 , windows os

### ISSUE THREAD

**Issue by Arunarchitect** [IfcOpenShell/IfcOpenShell#5875]
Cant apply void to walls, Apply Void is missing and the opening not working. Windows Operating system 
![issuevoid](https://github.com/user-attachments/assets/678429ba-b5f3-4954-9a39-4c72d5323e83)

**Comment by theoryshaw** [comment]
Did you select the opening first, than then shift select the wall second, so they are both selected?

**Comment by Arunarchitect** [comment]
Firstly, I didn't do this, but now it worked (selected the opening, then shift selected the wall, then apply void)—huge relief! thanks @theoryshaw

**Comment by Arunarchitect** [comment]
Firstly, I didn't do this, but now it worked (selected the opening, then shift selected the wall, then apply void)—huge relief! thank you @theoryshaw 
![issue2](https://github.com/user-attachments/assets/02e94aea-e891-4085-b76b-8bbc405bf317)
