### ISSUE TITLE
be able to 'apply void' no matter which order you select the wall (or any other class object) and void. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5876]
Would be nice to be able to be able to 'apply void' no matter which order you select the wall (or any other class object) and void. 

![image](https://github.com/user-attachments/assets/5e330cca-4209-44fe-a751-ebd804bbdd1e)

**Comment by Arunarchitect** [comment]
I am able to apply void, (1) firstly selecting  opening and then shift select wall  & (2) firstly selecting wall and then shift select opening. 

https://github.com/user-attachments/assets/92d0a752-2aa6-4bd7-97de-5435a5e4ff4e

**Comment by theoryshaw** [comment]
Interesting, this functionality seems to have gotten lost in the latest versions.

**Comment by theoryshaw** [comment]
@trhyder, is this related your work with the UI?

**Comment by Arunarchitect** [comment]
The version I have used is Blender 4.3.1 and Bonsai v0.8.0

**Comment by trhyder** [comment]
I think it would be better to introduce a dedicated “IFC Void Mode” where users can apply voids without needing to select anything - just tab out when done. The mode could activate either through the mode dropdown or automatically when a void is added to a selected object.

![image](https://github.com/user-attachments/assets/3bb97e97-3089-43ec-834d-4b8c5d2d5912)

**Comment by theoryshaw** [comment]
Yes, that sounds interesting.
