### ISSUE TITLE
[Bonsai] Cant Regen (Shift+G) the Wall after Duplicating a Window/Door. Blender 4.3.1 and Bonsai v0.8.0

### ISSUE THREAD

**Issue by Arunarchitect** [IfcOpenShell/IfcOpenShell#5878]
It would be great if this feature is available. Otherwise, we have to select each door from the library an then use Shift A, its time consuming, Actually, BIM editing is possible for a wall after duplication now.

https://github.com/user-attachments/assets/19ee668e-ee35-46cf-a9f1-9256fa8c7bbd

**Comment by theoryshaw** [comment]
If you duplicate a window or door you have to apply the void again to the wall

**Comment by Arunarchitect** [comment]
Yes, it worked, thank you @theoryshaw , but it would be much more easier , if the void is automatically generated.

**Comment by theoryshaw** [comment]
Yes, agreed. Would suggest creating a feature request.
