### ISSUE TITLE
shape_builder -> def profile has unknown attribute "Position

### ISSUE THREAD

**Issue by fertegi** [IfcOpenShell/IfcOpenShell#5882]
Hello all!
Its my very first issue, so please be patient with me :)
I am a very big fan of ifcopenshell and love the capabilities. I am currently using ifcopenshell 0.8. .
I am using a script to load an arbitrary ifc file and add simple geometries to them. 

To create the geometry I am using the shape_builder. 
But if I try to extrude the created polyline ,  I get the following error:
`ValueError: entity instance of type 'IFC2X3.IfcArbitraryClosedProfileDef' has only 3 attributes but 4 attributes were provided.`
I realized that the function `[profile](https://github.com/IfcOpenShell/IfcOpenShell/blob/07cf701e90ea1cd760655817038979ac7b18b03b/src/ifcopenshell-python/ifcopenshell/util/shape_builder.py#L344)` proposes a "Position" as an attribute of [IfcArbitraryClosedProfileDef](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcprofileresource/lexical/ifcarbitraryclosedprofiledef.htm) which is not present in the scheme IFC2x3 (which is my file).
Strangely i cannot see this line in the official repo, but in the release. 
I used a workaround and create the profile itself, and then extrude it.

I hope it help other people, who get the same problem.

Thank you all for the great work!

**Comment by Andrej730** [comment]
@fertegi hi! It's fixed in 545431d, pip is not yet updated, please use one of the latest builds from https://builds.ifcopenshell.org/ for now.
