### ISSUE TITLE
Recipe: 'ExtractElements' not extracting all shared PSets for all elements

### ISSUE THREAD

**Issue by PahlawanJoey** [IfcOpenShell/IfcOpenShell#5890]
Not all PSets are being copied to the new elements, however it seems for some elements it does work.

Guids used to extract: 0F4GqvEtv9kv0SP_IKgKiY, 1LEDBmQffEwQBOuKcjgBnL

Bug seems to happen on Guid: 1LEDBmQffEwQBOuKcjgBnL

Source object
![image](https://github.com/user-attachments/assets/42edb2f4-8fec-4c84-96c8-5100c72402cf)

Result:
![image](https://github.com/user-attachments/assets/47b1d117-c6d0-46f1-b151-1eeb4197219e)
[DYC_BDOR_blok 11-13_beganegrondvloer.ifc.txt](https://github.com/user-attachments/files/18201973/DYC_BDOR_blok.11-13_beganegrondvloer.ifc.txt)

**Comment by Andrej730** [comment]
Thanks for the bug report and narrowing it down. Issue is fixed.
