### ISSUE TITLE
Fillet not working properly

### ISSUE THREAD

**Issue by dopszli** [IfcOpenShell/IfcOpenShell#5893]
Hi in the recent releases the fillet function in the profile editor is working rather like the 3 point arc, no option to control the fillet radius. Is it under construction?

**Comment by Andrej730** [comment]
@dopszli hi! We already have it, it's shift+f hotkey and then do F9 to adjust the radius. But there was in issue when it was misleadingly displayed in UI as shift+v (same hotkey as 3 point arc), should be fixed now in the latest release. Thanks for reporting this.
