### ISSUE TITLE
Window model is invalid after changing its parameter. #Bonsai#

### ISSUE THREAD

**Issue by JTIRAT** [IfcOpenShell/IfcOpenShell#5896]
After changing the window parameters, model is invalid. Its frame is shifted up or may be increased its size.

[bonsai-0.8.1-alpha2412202043 (unstable)] 
<img width="192" alt="image" src="https://github.com/user-attachments/assets/a63af720-5c78-48e7-9a4d-2e6565949242" />

**Comment by steverugi** [comment]
@JTIRAT can you send a sample of your file where the window is invalid?
did you try a new Bonsai session with a simple wall + window then modify it to see if the problem remains?

**Comment by Andrej730** [comment]
Fixed, thank you for the bug report.
