### ISSUE TITLE
Have an IFC file save its linked IFC files

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5899]
It would be nice if an IFC file saved its linked IFC files

- `Referencing.ifc`
  - `foo.ifc`
  - `bar.ifc`

if you used `bim.link_ifc` to link  `foo.ifc` and `bar.ifc` inside `Referencing.ifc`, it would be nice if these links stay intact the next time you opened `Referencing.ifc`.

**Comment by steverugi** [comment]
nice one @theoryshaw 
but would `Referencing.ifc` be IFC compliant?

**Comment by theoryshaw** [comment]
Not 100% certain. 

...

Maybe could use entities like `IfcRelAssociatesDocument` and `IfcDocumentReference` to reference external .IFC files.

...

Or get bold, and explore: https://github.com/IfcOpenShell/IfcOpenShell/issues/668
