### ISSUE TITLE
Implement remaining (not frequently used) IFC2x3 and IFC4 representation items

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#59]
These are all non-abstract subtypes of IfcRepresentationItem. Most of them implemented, details follow.
## IFC2X3
- [x] IfcAxis1Placement
- [x] IfcAxis2Placement2D
- [x] IfcAxis2Placement3D
- [x] IfcBlock
- [x] IfcBooleanClippingResult
- [x] IfcBooleanResult
- [x] IfcCartesianPoint
- [x] IfcCartesianTransformationOperator2D
- [x] IfcCartesianTransformationOperator2DnonUniform
- [x] IfcCartesianTransformationOperator3D
- [x] IfcCartesianTransformationOperator3DnonUniform
- [x] IfcCircle
- [x] IfcClosedShell
- [x] IfcCompositeCurve
- [x] IfcCompositeCurveSegment
- [x] IfcConnectedFaceSet
- [x] IfcCsgSolid
- [x] IfcCurveBoundedPlane
- [x] IfcDirection
- [x] IfcEdge
- [x] IfcEdgeCurve
- [x] IfcEdgeLoop
- [x] IfcEllipse
- [x] IfcExtrudedAreaSolid
- [x] IfcFace
- [x] IfcFaceBasedSurfaceModel
- [x] IfcFaceBound
- [x] IfcFaceOuterBound
- [x] IfcFaceSurface
- [x] IfcFacetedBrep
- [x] IfcFacetedBrepWithVoids
- [x] IfcGeometricSet
- [x] IfcHalfSpaceSolid
- [x] IfcLine
- [x] IfcMappedItem
- [ ] IfcOffsetCurve2D
- [ ] IfcOffsetCurve3D
- [x] IfcOpenShell
- [x] IfcOrientedEdge
- [ ] IfcPath
- [x] IfcPlane
- [ ] IfcPointOnCurve
- [ ] IfcPointOnSurface
- [x] IfcPolyLoop
- [x] IfcPolygonalBoundedHalfSpace
- [x] IfcPolyline
- [x] IfcRectangularPyramid
- [x] IfcRectangularTrimmedSurface
- [x] IfcRevolvedAreaSolid
- [x] IfcRightCircularCone
- [x] IfcRightCircularCylinder
- [ ] IfcSectionedSpine
- [x] IfcShellBasedSurfaceModel
- [x] IfcSphere
- [x] IfcStyledItem
- [x] IfcSubedge
- [x] IfcSurfaceCurveSweptAreaSolid
- [x] IfcSurfaceOfLinearExtrusion
- [x] IfcSurfaceOfRevolution
- [x] IfcSweptDiskSolid
- [x] IfcTrimmedCurve
- [x] IfcVector
- [ ] IfcVertexLoop
- [x] IfcVertexPoint

No support planned:
- Ifc2DCompositeCurve (DEPRICATED, removed from IFC4, supertype supported)
- IfcBezierCurve (DEPRICATED, removed from IFC4)
- IfcBoundedSurface (No attributes, made abstract in IFC4)
- IfcBoundingBox
- IfcBoxedHalfSpace (supertype supported, no meaningful behaviour added)
- IfcGeometricCurveSet (supertype supported, no meaningful behaviour added)
- IfcLoop (No attributes, [should be abstract?](http://jira.buildingsmart.org/browse/IFR-1075))
- IfcVertex (No attributes, should be abstract?)
- IfcRationalBezierCurve
- IfcAnnotationFillArea
- IfcAnnotationSurface
- IfcDefinedSymbol
- IfcFillAreaStyleHatching
- IfcFillAreaStyleTileSymbolWithStyle
- IfcFillAreaStyleTiles
- IfcOneDirectionRepeatFactor
- IfcPlanarBox
- IfcPlanarExtent
- IfcTextLiteral
- IfcTextLiteralWithExtent
- IfcTwoDirectionRepeatFactor
- IfcAnnotationCurveOccurrence
- IfcAnnotationFillAreaOccurrence
- IfcAnnotationSurfaceOccurrence
- IfcAnnotationSymbolOccurrence
- IfcAnnotationTextOccurrence
- IfcDimensionCurve
- IfcDimensionCurveTerminator
- IfcProjectionCurve
- IfcTerminatorSymbol
- IfcAngularDimension
- IfcDiameterDimension
- IfcDimensionCurveDirectedCallout
- IfcDraughtingCallout
- IfcLinearDimension
- IfcRadiusDimension
- IfcStructuredDimensionCallout
- IfcLightSourceAmbient
- IfcLightSourceDirectional
- IfcLightSourceGoniometric
- IfcLightSourcePositional
- IfcLightSourceSpot
## IFC4
- [x] IfcAdvancedBrep
- [x] IfcAdvancedBrepWithVoids
- [x] IfcAdvancedFace
- [x] IfcAxis1Placement
- [x] IfcAxis2Placement2D
- [x] IfcAxis2Placement3D
- [x] IfcBSplineCurveWithKnots
- [x] IfcBSplineSurfaceWithKnots
- [x] IfcBlock
- [x] IfcBooleanClippingResult
- [x] IfcBooleanResult
- [ ] IfcBoundaryCurve
- [ ] IfcBoundingBox
- [ ] IfcBoxedHalfSpace
- [x] IfcCartesianPoint
- [ ] IfcCartesianPointList2D
- [ ] IfcCartesianPointList3D
- [x] IfcCartesianTransformationOperator2D
- [x] IfcCartesianTransformationOperator2DnonUniform
- [x] IfcCartesianTransformationOperator3D
- [x] IfcCartesianTransformationOperator3DnonUniform
- [x] IfcCircle
- [x] IfcClosedShell
- [x] IfcCompositeCurve
- [ ] IfcCompositeCurveOnSurface
- [x] IfcCompositeCurveSegment
- [x] IfcConnectedFaceSet
- [x] IfcCsgSolid
- [x] IfcCurveBoundedPlane
- [ ] IfcCurveBoundedSurface
- [x] IfcCylindricalSurface
- [x] IfcDirection
- [x] IfcEdge
- [x] IfcEdgeCurve
- [x] IfcEdgeLoop
- [x] IfcEllipse
- [x] IfcExtrudedAreaSolid
- [x] IfcExtrudedAreaSolidTapered
- [x] IfcFace
- [x] IfcFaceBasedSurfaceModel
- [x] IfcFaceBound
- [x] IfcFaceOuterBound
- [x] IfcFaceSurface
- [x] IfcFacetedBrep
- [x] IfcFacetedBrepWithVoids
- [ ] IfcFixedReferenceSweptAreaSolid
- [x] IfcGeometricCurveSet
- [x] IfcGeometricSet
- [x] IfcHalfSpaceSolid
- [x] IfcIndexedPolyCurve
- [x] IfcLine
- [ ] IfcLoop
- [x] IfcMappedItem
- [ ] IfcOffsetCurve2D
- [ ] IfcOffsetCurve3D
- [x] IfcOpenShell
- [x] IfcOrientedEdge
- [ ] IfcOuterBoundaryCurve
- [ ] IfcPath
- [ ] IfcPcurve
- [x] IfcPlane
- [ ] IfcPointOnCurve
- [ ] IfcPointOnSurface
- [x] IfcPolyLoop
- [x] IfcPolygonalBoundedHalfSpace
- [x] IfcPolyline
- [x] IfcRationalBSplineCurveWithKnots
- [x] IfcRationalBSplineSurfaceWithKnots
- [x] IfcRectangularPyramid
- [x] IfcRectangularTrimmedSurface
- [ ] IfcReparametrisedCompositeCurveSegment
- [x] IfcRevolvedAreaSolid
- [ ] IfcRevolvedAreaSolidTapered
- [x] IfcRightCircularCone
- [x] IfcRightCircularCylinder
- [ ] IfcSectionedSpine
- [x] IfcShellBasedSurfaceModel
- [x] IfcSphere
- [x] IfcStyledItem
- [x] IfcSubedge
- [x] IfcSurfaceCurveSweptAreaSolid
- [x] IfcSurfaceOfLinearExtrusion
- [x] IfcSurfaceOfRevolution
- [x] IfcSweptDiskSolid
- [ ] IfcSweptDiskSolidPolygonal
- [x] IfcTriangulatedFaceSet
- [x] IfcTrimmedCurve
- [x] IfcVector
- [ ] IfcVertex
- [ ] IfcVertexLoop
- [x] IfcVertexPoint

No support planned:
- IfcAnnotationFillArea
- IfcFillAreaStyleHatching
- IfcFillAreaStyleTiles
- IfcPlanarBox
- IfcPlanarExtent
- IfcTextLiteral
- IfcTextLiteralWithExtent
- IfcLightSourceAmbient
- IfcLightSourceDirectional
- IfcLightSourceGoniometric
- IfcLightSourcePositional
- IfcLightSourceSpot

**Comment by jf---** [comment]
IfcOpenShell does not implement  IfcOpenShell 👻  
@aothms , on a more serious note, last year we've dabbled with IFC4, specifically nurbs support.
seems that the current master does not support this?

```
ifc.ifcopenshell_wrapper.schema_identifier()
Out[4]: 'IFC4'
```

**Comment by jf---** [comment]
we did manage to support `ifc4_nurbs_files/120605 curved beam ifc2x4.ifc` for sure, and `131116 non-planar panel.ifc` IIRC. see:
[ifc4_nurbs_files.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/502927/ifc4_nurbs_files.zip)

I'd like to help out finalizing IFC4 support; here's some function I 

```python

def list_to_occ_type(occ_type, li):
    if "Array1" in str(occ_type):
        pts = occ_type(0, len(li) - 1)
        for n, i in enumerate(li):
            pts.SetValue(n, i)
    elif "Array2" in str(occ_type):
        pts = occ_type(0, len(li) - 1, 0, len(li[0]) - 1)
        for n1, i in enumerate(li):
            for n2, j in enumerate(i):
                pts.SetValue(n1, n2, j)
    else:
        raise TypeError("expected class with Array1 / Array2, but got {0}".format(occ_type.__class__.__name__))
    return pts


def bspline_surface_from_ifc_advanced_face(ifc_face):
    """ reconstruct the bspline surface stored in the `ifc_face` IfcBSplineSurfaceWithKnots

    """
    from OCC.gp import gp_Pnt
    from OCC.TColgp import TColgp_Array2OfPnt
    from OCC.TColStd import TColStd_Array1OfReal, TColStd_Array1OfInteger
    from OCC.Geom import Geom_BSplineSurface

    assert ifc_face.is_a() == "IfcAdvancedFace"

    surface = ifc_face.FaceSurface

    # construct control point lists
    control_points = []
    for li in surface.ControlPointsList:
        control_points.append([gp_Pnt(*vert.Coordinates) for vert in li])

    # make sure that all sublists are of equal length
    control_list_length = map(len, control_points)
    for i in control_list_length:
        assert i == control_list_length[0], "control list must be of equal length... expected {0}, got {1}" \
            .format(i, control_list_length[0])

    poles = list_to_occ_type(TColgp_Array2OfPnt, control_points)

    u_knots = list_to_occ_type(TColStd_Array1OfReal, surface.UKnots)
    v_knots = list_to_occ_type(TColStd_Array1OfReal, surface.VKnots)

    u_mult_knots = list_to_occ_type(TColStd_Array1OfInteger, surface.UMultiplicities)
    v_mult_knots = list_to_occ_type(TColStd_Array1OfInteger, surface.VMultiplicities)

    try:
        srf = Geom_BSplineSurface(poles,
                                  u_knots,
                                  v_knots,
                                  u_mult_knots,
                                  v_mult_knots,
                                  surface.UDegree,
                                  surface.VDegree,
                                  surface.UClosed,
                                  surface.VClosed
                                  )
    except RuntimeError:
        warnings.warn("could not reconstruct surface from {0}".format(ifc_face))

    else:
        return srf


def edges_from_ifc_advanced_face(ifc_face):
    """ build TopoDS_Edge's from the edges described in the IfcEdgeLoop, contained in `ifc_face`

    ifc_face -> IfcAdvancedFace

    ifc_face.Bounds -> IfcFaceOuterBound

    for edg in


    :param ifc_face:
    :return:
    """

    from OCC.gp import gp_Pnt
    from OCC.TColStd import TColStd_Array1OfReal, TColStd_Array1OfInteger
    from OCC.TColgp import TColgp_Array1OfPnt
    from OCC.Geom import Geom_BSplineCurve
    from OCCUtils.Construct import make_edge

    assert ifc_face.is_a() == "IfcAdvancedFace"

    # can't image more than a single bound???
    _edges = []

    for bnd in ifc_face.Bounds:
        for edg in bnd.Bound.EdgeList:
            edg_geom = edg.EdgeElement.EdgeGeometry
            poles = list_to_occ_type(TColgp_Array1OfPnt,
                                     [gp_Pnt(*pt.Coordinates) for pt in edg_geom.ControlPointsList])
            knots = list_to_occ_type(TColStd_Array1OfReal, edg_geom.Knots)
            multiplicities = list_to_occ_type(TColStd_Array1OfInteger, edg_geom.KnotMultiplicities)
            degree = edg_geom.Degree
            periodic = edg_geom.ClosedCurve
            try:
                spl = Geom_BSplineCurve(poles, knots, multiplicities, degree, periodic)
            except Exception:
                warnings.warn("could not construct edge from {0}".format(edg_geom))
            else:
                edge = make_edge(spl.GetHandle())
                _edges.append(edge)

    return _edges


def construct_spline_surface_from_ifc(ifc_face):
    assert ifc_face.is_a() == "IfcAdvancedFace", "expected an IfcAdvancedFace instance, got a {0}" \
                                                 "".format(ifc_face.is_a())

    surface = ifc_face.FaceSurface

    # segfaults grrrrrrr....
    bspline_surface_from_ifc_advanced_face(ifc_face)
    edges_from_ifc_advanced_face(ifc_face)



def render_nurbs_surface():
    path = "/Users/jelleferinga/Downloads/IfcBSplineSurface.ifc"
    ifc_file = ifc.open(path)

    # iterator = ifc.geom.iterator(settings, path)
    # if iterator.initialize():
    #     while True:
    #         iterator.get()
    #
    # print "OK"
    # print iterator.getLog()

    walls = ifc_file.by_type("IfcWall")
    face = walls[0].Representation.Representations[0].Items[0].FbsmFaces[0].CfsFaces[0]

    # construct_spline_surface_from_ifc(face)

    edges = edges_from_ifc_advanced_face(face)
    srf = bspline_surface_from_ifc_advanced_face(face)

    from OCCUtils.Construct import make_face, make_wire
    wi = make_wire(edges)
    # dont do nu'thin?
    fc = make_face(srf.GetHandle(), wi)
    # this one does...
    fff = make_face(srf.GetHandle(), 0.01)

    display.DisplayShape([wi, fc, fff])


```

**Comment by iras** [comment]
@jf--- Did you by any chance try to import textures in IFC4 format?

**Comment by jf---** [comment]
@iras , nope, can you add a .zip file here?

**Comment by aothms** [comment]
Thanks @jf--- . By now there is similar code in IfcOpenShell [1]. So part of the confusion here is that it takes time to tick all these check boxes, this has simply not been done yet for IFC4. Some of the files in your zip work well. I will have a more in depth look at the others. There is also [2]: 

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/aebb9e324b0128503dde95bf9eb166c0ff9fb470/src/ifcgeom/IfcGeomFaces.cpp#L1015
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/test/input/advanced_brep.ifc

![1](https://cloud.githubusercontent.com/assets/1096535/19012356/23b0a55e-87b3-11e6-87fb-57cbb592027b.png)
![2](https://cloud.githubusercontent.com/assets/1096535/19012357/23d15e98-87b3-11e6-8101-371761673866.png)
![3](https://cloud.githubusercontent.com/assets/1096535/19012377/d99fa69e-87b3-11e6-83bd-25efae3975d8.png)

**Comment by iras** [comment]
@jf--- I'm afraid I couldn't find any IFC4 files using textures.

@TLiebich could you please point us to minimal examples of IFC4 files with internal and external (referenced) textures for implementation purposes in IfcOpenShell. If you don't know of any already available on the web, would you be so kind to put together a couple of such minimal examples that we can then use as unit/performance tests? Many thanks.

**Comment by aothms** [comment]
@iras there are a couple here: http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/tessellation-with-blob-texture.htm

**Comment by jf---** [comment]
@aothms , thanks Thomas, my comment was a bit harsh / unspecific indeed. will follow up next week with more detailed feedback. that said, the very useful list mentioned here is not in a correct state? for instance, since the files above can be loaded, its fair to assume that `IfcBSplineCurveWithKnots` is implemented?

**Comment by aothms** [comment]
I am done with this. The others are likely too obscure, but can be implemented later on might a need arise.
