### ISSUE TITLE
Installing live dev environment causes Bonsai to not load

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#5904]
Installing live development environment on a mac causes Bonsai to not load on Blender startup.

I did the following steps:
- Downloaded Blender 4.3.2
- Installed the Bonsai extension in Blender from the repository https://raw.githubusercontent.com/IfcOpenShell/bonsai_unstable_repo/main/index.json
- added local paths for REPO_PATH and BLENDER_PATH in the dev_environment.sh
- ran dev_environment.sh

Everything seemed to run correctly except copying over the complied IfcOpenShell files and I got the following response in the terminal:

`cp: /Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/*_wrapper*: No such file or directory`

When I open Blender, Bonsai doesn't load and I get the following error message:

```
os: Darwin
os_version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
python_version: 3.11.9
architecture: ('64bit', '')
machine: arm64
processor: arm
blender_version: 4.3.2
bonsai_version: 0.8.1-alpha241222
bonsai_commit_hash: cb0fdbe
last_actions: 
last_error: Traceback (most recent call last):
  File "/Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/__init__.py", line 84, in <module>
    from . import ifcopenshell_wrapper
  File "/Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: cannot import name '_ifcopenshell_wrapper' from partially initialized module 'ifcopenshell' (most likely due to a circular import) (/Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tim/Library/Application Support/Blender/4.3/extensions/raw_githubusercontent_com/bonsai/__init__.py", line 225, in <module>
    import ifcopenshell.api
  File "/Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/__init__.py", line 86, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'darwin/64bit/python3.11'

binary_error: Couldn't find ifcopenshell wrapper binary.

```

**Comment by Andrej730** [comment]
@trhyder 

The `ifcopenshell/*_wrapper*: No such file or directory` error is critical as later there might be no compiled wrapper files in the symlinked directory.

Are you sure wrapper files are there before you start dev_environment script? There should be two files `ifcopenshell_wrapper.py` and `_ifcopenshell_wrapper.cpython-311-darwin.so`. Try to run this `cp` command that has `*_wrapper` manually to see if there's maybe something else that gets in the way.

**Comment by trhyder** [comment]
Thanks @Andrej730. I don't seem to have `_ifcopenshell_wrapper.cpython-311-darwin.so` in my directory. 

```
ls "/Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell"           
__init__.py             alignment.py            draw.py                 express                 geom                    ifcopenshell_wrapper.py py.typed                settings.py             sql.py                  template.py             validate.py
__pycache__             api                     entity_instance.py      file.py                 guid.py                 mvd                     requirements.txt        simple_spf              stream.py               util
```

I suspect the `*_wrapper*` might be expecting more than one file which is why it might be copying `ifcopenshell_wrapper.py` but then returning an error.

I ran the following lines separately:
`cp: /Users/tim/repos/IfcOpenShell/src/ifcopenshell-python/ifcopenshell/ifcopenshell_wrapper.py and /Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py are identical (not copied).`

`cp: /Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/_ifcopenshell_wrapper.cpython-311-darwin.so: No such file or directory`

**Comment by Andrej730** [comment]
> I don't seem to have `_ifcopenshell_wrapper.cpython-311-darwin.so` in my directory.

You mean now - when Blender doesn't start - or after clean reinstall of Bonsai? 
If Blender doesn't currently start because of the error you attached above, then ifcopenshell folder was symlinked without this file and it probably was lost.

**Comment by trhyder** [comment]
I mean now, when Bonsai doesn't load on a Bender start.

**Comment by trhyder** [comment]
Bonsai did start before on a fresh install of the unstable daily build

**Comment by Andrej730** [comment]
> I mean now, when Bonsai doesn't load on a Bender start.

Then you need to reinstall Bonsai and 1) check if .so file is present; 2) try to run `cp` command manually to reproduce the error and see if anything else can be done about it.

**Comment by trhyder** [comment]
I reinstalled Bonsai and checked for the files. They are present

```
ls "/Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell"
__init__.py                                     alignment.py                                    entity_instance.py                              geom                                            py.typed                                        sql.py                                          util
__pycache__                                     api                                             express                                         guid.py                                         requirements.txt                                stream.py                                       validate.py
_ifcopenshell_wrapper.cpython-311-darwin.so     draw.py                                         file.py                                         ifcopenshell_wrapper.py                         settings.py                                     template.py
```

I executed the sh script down to the cp line but I get the same terminal message:
                                                                                                                       
`cp: /Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/*_wrapper*: No such file or directory`

The files still seem to be there:

```
ls "/Users/tim/Library/Application Support/Blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell"
__init__.py                                     alignment.py                                    entity_instance.py                              geom                                            py.typed                                        sql.py                                          util
__pycache__                                     api                                             express                                         guid.py                                         requirements.txt                                stream.py                                       validate.py
_ifcopenshell_wrapper.cpython-311-darwin.so     draw.py                                         file.py                                         ifcopenshell_wrapper.py                         settings.py                                     template.py
```

**Comment by Andrej730** [comment]
> I executed the sh script down to the cp line but I get the same terminal message:

Can you please post the full `cp` command here it's executing? Anything looks wrong abut it?
Are you sure the second part of `cp` command is an existing folder? 
Try to type .so name explicitly to the `cp` command without wild cards and see if there's a similar error.

**Comment by trhyder** [comment]
here is the script down to the cp line:

```
REPO_PATH="/Users/tim/repos/IfcOpenShell"
BLENDER_PATH="/Users/tim/Library/Application Support/Blender/4.3"
PACKAGE_PATH="$BLENDER_PATH/extensions/.local/lib/python3.11/site-packages"
BONSAI_PATH="$BLENDER_PATH/extensions/raw_githubusercontent_com/bonsai"
cd "$REPO_PATH"
cp "${PACKAGE_PATH}/ifcopenshell/*_wrapper*" "${PWD}/src/ifcopenshell-python/ifcopenshell/"
```

I also tried `cp "$PACKAGE_PATH/ifcopenshell/*_wrapper*" "$PWD/src/ifcopenshell-python/ifcopenshell/"` with the same result

I'll try and type .so name explicitly now

**Comment by trhyder** [comment]
Ok so if I split the cp line into two, the full script works and Bonsai loads when Blender starts up.

```
cp "$PACKAGE_PATH/ifcopenshell/ifcopenshell_wrapper.py" "$PWD/src/ifcopenshell-python/ifcopenshell/"
cp "$PACKAGE_PATH/ifcopenshell/_ifcopenshell_wrapper.cpython-311-darwin.so" "$PWD/src/ifcopenshell-python/ifcopenshell/"
```

**Comment by Andrej730** [comment]
@trhyder

It seems wild cards are not supported inside quotation marks as described here - https://superuser.com/questions/173287/cp-command-not-working-with-wildcards-on-mac-os-x/

And this issue already occurred before in https://github.com/IfcOpenShell/IfcOpenShell/issues/5475#issuecomment-2375814646

Actually was able to reproduce it with Shell on Windows and Linux shell I had from Colab - it fails when wild cards are inside quotation marks and placing them outside seems to resolve the issue, so I guess it should be safe to just move them outside the quotation marks. 

Please try it with the line below:
```sh
cp "${PACKAGE_PATH}/ifcopenshell/"*_wrapper* "${PWD}/src/ifcopenshell-python/ifcopenshell/"
```

**Comment by trhyder** [comment]
Thanks I'll give it a go. Sorry, I forgot about that issue.
