### ISSUE TITLE
New_user

### ISSUE THREAD

**Issue by raouajaraib** [IfcOpenShell/IfcOpenShell#591]
Hello, I'm a new user of ifcopenshell, I'm trying to access to the material of a product.
>>>f=ifcopenshell.open("/home/jaraib/Documents/stage/ifc_test/mur_beton_low.ifc")
>>>material=f.by_type("IFCMATERIAL")
>>>print(meterial[0])
>>>#190=IfcMaterial('beton')
My objective is to have acces to 'beton', I tried material[0] but it dosn't work, do you have any idea? thank you

**Comment by SigveMartin** [comment]
If you want to filter the list of IfcMaterial type objects in the return from f.by_type("IfcMaterial") then you could filter based on the Name attribute of that object ref. http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcmaterialresource/lexical/ifcmaterial.htm 

eg. particular_material = [material for material in materials if material.Name == "beton"]

This will return a list of all IfcMaterial objects that has that name. A list with one object if there is only one object with that name. Then you could do particular_material[0] to get the object. 

If you just need to print the Name attribute of the object you could use print(particular_material[0].Name)

**Comment by SigveMartin** [comment]
ref.  particular_material = [material for material in materials if material.Name == "beton"]

given that you have materials = f.by_type("IfcMaterial"). Have done som drodling in the attached pdf. 
[IfcMaterial-handling.pdf](https://github.com/IfcOpenShell/IfcOpenShell/files/3207179/IfcMaterial-handling.pdf)

**Comment by raouajaraib** [comment]
thank you for your answer, but I already tried it but it didn't work for me
>>>f=ifcopenshell.open("/home/jaraib/Documents/stage/ifc_test/mur_beton_low.ifc")
>>>material=f.by_type("IFCMATERIAL")
>>>material_0=material[0]
>>>print(material_0)
>>>print(material_0.Name)
reponse
>>>#190=IfcMaterial('raoua') 
ps: raoua is just a name of a material that I created on revit, I'm using jupyter .

**Comment by raouajaraib** [comment]
I tried also in the shell:
>>> import ifcopenshell
>>> f=ifcopenshell.open("/home/jaraib/Documents/stage/ifc_test/mur_beton_low.ifc")
>>> material=f.by_type("IFCMATERIAL")
>>> material_0=material[0]
>>> print(material_0)
#190=IfcMaterial('raoua')
>>> print(material[0].Name)
��������a缾񢃐
It's weired cause it supposed to be 'raoua' .

**Comment by aothms** [comment]
There is no particular order in the materials contained in an IFC file. What @SigveMartin suggests is to inspect all of them to match the name you are looking for. What version of IfcOpenShell are you using?

**Comment by raouajaraib** [comment]
I didn't quite understand your answer, when you say there is no order, you mean that it's wrong to use material_0=material[0]? but that isn't the problem cause he show me #190=IfcMaterial('raoua'), that means he's capable of detecting the order, my problem is that I can't access to the attribute 'Name' of "ifcMaterial", all I want is to access to 'raoua', I need it to show me 'raoua'.

[mur_beton_low.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3208152/mur_beton_low.ifc.txt)

**Comment by johltn** [comment]
Hi, this code should solve your issue: 

```
import ifcopenshell 

file = ifcopenshell.open(PATH_TO_YOUR_FILE)
materials = file.by_type('IfcMaterial')

for material in materials:
	print(material.Name)
```
Getting the following ouput: 
`raoua`

**Comment by raouajaraib** [comment]
@johltn it exactly what I did, but I didn't work but I think it's related to the fact that I'm using python2, So I used python3 with the last version of ifcopenshell and it's worked. thank you for you help

**Comment by aothms** [comment]
Ok, that explains probably. There is an often overlooked compilation setting in Python version before 3.3 that controls how unicode information is stored. Later builds of IfcOpenShell always include both a narrow and wide version. You can find the configuration of your python interpreter by looking at sys.maxsize and that determines whether you need the version for 2.7 or 2.7u. I forgot the details.

**Comment by raouajaraib** [comment]
@aothms thank you for your answer, now it's work for me using the version ifcopenshell35, you can mark this issue as resolved, by the way, I have an issue using IFCconvert #593, if you can give it a look, thank you
