### ISSUE TITLE
exception on bounding box values

### ISSUE THREAD

**Issue by mhdfahadCS** [IfcOpenShell/IfcOpenShell#592]
I am working with IFC4 and using IfcOpenShellPlugin-0.5.24, I need to generate bounding boxes. When I ran the ifc open shelle engire, my program shows that Took 28,09 seconds to obtain representations for 564 entities, but after there was an null pointer exception when I need to collect geometry by getting bounding boxes ...
double wMaxX = wall.getGeometry().getMaxBounds().getX();
								double wMaxY = wall.getGeometry().getMaxBounds().getY();
								double wMaxZ = wall.getGeometry().getMaxBounds().getZ();

debug output is as follows..
14:14:18.132 [main] DEBUG org.ifcopenshell.IfcOpenShellEngine - Initializing IfcOpenShell engine
14:14:55.788 [main] DEBUG org.ifcopenshell.IfcOpenShellModel - Took 28,09 seconds to obtain representations for 564 entities

 total no of walls are : 522

I was looking at wall.getRepresentation().getRepresentations().get(i).getRepresentationType() 
and check that it has some sort of represenations...

 wall ID = 1UHQtBYC1FFvssapdOv$ce
0...representation.......Curve2D
1...representation.......Clipping
 wall ID = 1UHQtBYC1FFvssapdOv$dw
0...representation.......Curve2D
1...representation.......Clipping
 wall ID = 3j7ZcrARP1eeaxjkzRbLsh
0...representation.......Curve2D
1...representation.......Clipping
 wall ID = 3j7ZcrARP1eeaxjkzRbLtr
0...representation.......Curve2D
1...representation.......SweptSolid

thanks in advance for your help

**Comment by aothms** [comment]
It's not impossible that conversion of an element fails, that it is invalid, or that yields an empty geometry. Without looking at the model we can only speculate.

**Comment by mhdfahadCS** [comment]
For example if we talk about this model exemple_ifc_wiseBIM_2x4.ifc, (remove .txt extension) it shows
09:37:26.021 [main] DEBUG org.ifcopenshell.IfcOpenShellEngine - Initializing IfcOpenShell engine
Here is #104
09:37:29.090 [main] DEBUG org.ifcopenshell.IfcOpenShellModel - Took 2,03 seconds to obtain representations for 204 entities
 total no of walls are : 51
But null pointer exception on getting bounding box values. Any solution how can I get these min and ma x values ? 
[exemple_ifc_wiseBIM_2x4.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3210828/exemple_ifc_wiseBIM_2x4.ifc.txt)

**Comment by mhdfahadCS** [comment]
I have solved it myself, there was some conflict between jars which lead to null geometry instances, Thanks alot I have fixed it
