### ISSUE TITLE
Wall geometry sticking out

### ISSUE THREAD

**Issue by MarcinKoziuk** [IfcOpenShell/IfcOpenShell#6]
There seems to be a problem with walls consisting of multiple IfcPolygonalBoundedHalfspace boolean clipping results. The entity id of the wall with the problem is `#9151`.

IfcOpenShell             |  Solibri
:-------------------------:|:-------------------------:
![clipping wall](https://cloud.githubusercontent.com/assets/22248/10818156/93a41f18-7e3f-11e5-93e7-6d1ea6ce23f5.png) | ![correct wall](https://cloud.githubusercontent.com/assets/22248/10818161/9632363e-7e3f-11e5-9bf3-ed1edeef765b.png)

Additionaly, the IfcStyledItem (`#1453`) of an IfcExtrudedAreaSolid (`#1418`) used in the geometry of wall `#1460` doesn't get applied, so the default material is used.

You can download the IFC file [here](http://ogdbview.nl/public_ifc/447104_Type_A.ifc). We are using the latest master version. Thanks in advance for taking a look at this :)

**Comment by aothms** [comment]
Hi.

Thanks for the report. I will try to investigate soon.

Kind regards,
Thomas

**Comment by iras** [comment]
I partially reproduced the issue on ifcopenshell r339 (March '15). Only the left hand side wall sticking out.

<img width="776" alt="screen shot 2015-12-03 at 15 07 59" src="https://cloud.githubusercontent.com/assets/773028/11564232/16cc7092-99d0-11e5-9d52-a1512490802f.png">

but in Ifcopenshell r269 it looks fine as in Solibri's Model Viewer.

**Comment by aothms** [comment]
Hi,

Thanks for checking. This way of modelling is sensitive to precision issues. The polygonal boundary that bounds the subtraction volume overlaps with the original wall volume. This overlap is never completely accurate and hence there is some tolerance employed in this subtraction. This tolerance has been tweaked many times, hence the different results observed.

I am working on making this more robust by not relying on a generic boolean subtraction, but special-casing the polygonal halfspace subtraction and identifying the faces that overlap prior to the subtraction.

Anyway, just a message from my side to let you know your issue is being worked on.

Kind regards,
Thomas
IfcOpenShell

**Comment by iras** [comment]
+1

**Comment by jf---** [comment]
@aothms , 

have you seen the progress on OCC dev wrt [fuzzy boolean operations](http://dev.opencascade.org/index.php?q=node/1056)?

Could be very relevant...

**Comment by aothms** [comment]
I agree, I have seen but not checked yet. Somehow I always thought this should be covered by tolerance management.

**Comment by jf---** [comment]
@aothms , I think so too ( tolerance ), but I also think that's exactly what fuzzy bools provides ;)

**Comment by aothms** [comment]
@jf--- was right. The new fuzzy boolean ops seem to do the job. Note that you need a recent version of OCC for which unfortunately no Open Cascade Community Edition version has been released yet. 

Fix for the styled item is in as well.

You can check the code here https://github.com/aothms/IfcOpenShell. Will merge to upstream later.

**Comment by jf---** [comment]
@aothms , excited to hear so... thanks for sharing that finding...

Are you tracking performance for IfcOpenShell? 
Bool ops were known to be pretty slow, I was thrilled to see the fuzzy bool ops to be both more robust and more than an order of magnitude quicker...

**Comment by aothms** [comment]
@jf-- the main improvement in terms of boolean ops for IfcOpenShell will be the new multiple operands feature. Wall openings are defined as subtraction volumes in IFC. For walls with many openings (sometimes e.g ~100), applying them one-by-one can lead to astronomical processing times. Each boolean op increases the complexity for the operands of the boolean op for the following opening subtraction.

Hopefully now this can be linear in terms of number of openings. I have not benchmarked this yet. Will keep you posted.

**Comment by jf---** [comment]
@aothms , thanks, I'm following this with great interest...
