### ISSUE TITLE
Timeout / performance regression on wall (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#600]
1. Convert [600--wall--timeout--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/600--wall--timeout--augmented.ifc) with 42e00581cd187309ebea1aba585fae06dd7dd13f (v0.6.0 from Feb 6 – OCCT 7.3.0p3) and experience that the conversion finishes successfully after 3 min: (the output size is indeed large at 18.8 Mb, though)
<img width="259" alt="Screenshot 2019-05-29 at 13 17 32" src="https://user-images.githubusercontent.com/4601554/58553096-5051b680-8214-11e9-9e22-b828807ac1b0.png">

2. Convert the same file with any recent commit on v0.6.0 and experience that the conversion is not finished after 16 h.

**Comment by aothms** [comment]
There were duplicate faces in the input geometry, which resulted in many many boolean operands. The file now processes successfully in a couple of seconds.

**Comment by johanrd** [comment]
thanks! verified – this now seems to process nicely after 826316c 🎉(the output size of 275 kb is also more as expected)

**Comment by johanrd** [comment]
Reopening, as this file segfaults on OCCT 7.4.0 (with e37c882)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
