### ISSUE TITLE
IFC4 ADD2

### ISSUE THREAD

**Issue by LEILX** [IfcOpenShell/IfcOpenShell#604]
Hi, i meet some problems when I convert a IFC4 ADD2 model to DAE model, the version of converter is : 1a57162

I got some error messages when I was converting the IFC model, the error message looks like : 
[Error] {37cU2nGL100xirW00wMfms} No operation defined for:
#483=IfcPolygonalFaceSet(#463,.T.,(#438,#443,#445,#447,#449,#451,#453,#455,#457,#459),$)

So some objects missed in the DAE model generated.

Could you give some suggestions to resolve this problem?
Thanks a lot.

**Comment by aothms** [comment]
>     HISTORY  New entity in IFC4 Addendum 2.

We just recently updated the schema, not all entities in Add2 have implemented geometry conversions.

Are there actually tools creating these already? Can you provide a test file (preferably an isolated instance added to https://github.com/IfcOpenShell/files)?

**Comment by LEILX** [comment]
Hi, thank you very mush for your response.
In fact, i think i dont have access to upload files to  https://github.com/IfcOpenShell/files

I put 2 models in this link : https://v2.fangcloud.com/share/95cb26f5af7a6cf149c13ff0d0
- One model is a IFC4 ADD2 model which has conversion problem
- One model is a IFC4 ADD2 instance which has conversion problem

The type of error that I got is : 
Log:
[Error] {37cU2nGL100xirW00wMfmm} No operation defined for:
#280=IfcPolygonalFaceSet(#236,.T.,(#183,#186,#188,#190,#192,#198,#204,#206,#208,#210,#212,#214,#216,#218,#220,#222,#224,#226,#228,#230,#232,#234),$)

I saw in IFC4 ADD2 documentation that IfcPolygonalFaceSet is a new entity for IFC4 ADD2, maybe that this the problem. You can see this in 'Change logs' in this link : https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/

Thanks.

**Comment by LEILX** [comment]
Hi, I put the 2 models in https://github.com/IfcOpenShell/files
They are : 
1. TestModel_IFC4Add2.ifc
2. WallInstance_IFC4Add2.ifc

**Comment by Moult** [comment]
I believe IfcPolygonalFaceSet now works, so closing bug.
