### ISSUE TITLE
faces in .dae have inverted/missing faces after conversion from .ifc 

### ISSUE THREAD

**Issue by MassMachinery** [IfcOpenShell/IfcOpenShell#609]
I was converting the model attached below with an outdated version of IfcOpenShell and experienced missing elements, probably relating to #466 so I updated to the latest version of IfcOpenShell but then I discovered that some elements seem to be inverted (see screenshots below). I added the model as .ZIP file. 

As clarification, in the older version of IfcOpenShell the inverted elements were showing correctly.
Could you please have a look at what could cause this issue? Thanks in advance!
 
Couch
![image](https://user-images.githubusercontent.com/7532951/59104137-03b35d00-8931-11e9-9cc0-94650cbbd14c.png)

Cupboards
![image](https://user-images.githubusercontent.com/7532951/59104097-e8e0e880-8930-11e9-8f98-414790ff58bd.png)

[Duplex_A_20110907_optimized.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/3265864/Duplex_A_20110907_optimized.zip)

**Comment by aothms** [comment]
What version of IfcOpenShell are you using exactly? My recommendation is the head of v0.6.0 and invoke IfcConvert.exe with `--orient-shells` to fix faces incorrectly oriented in the file.

**Comment by MassMachinery** [comment]
Awesome! Using  --orient-shells fixed it. This didn't seem necessary in older versions though. I was using  v0.6.0. Thanks for the speedy reply!

**Comment by aothms** [comment]
> This didn't seem necessary in older versions though. I was using v0.6.0.

There was a couple of months time window in which this was indeed enabled by default. But it turned out too invasive still in case of extremely detailed meshes (see https://github.com/IfcOpenShell/IfcOpenShell/issues/578)
