### ISSUE TITLE
Properties of materials

### ISSUE THREAD

**Issue by raouajaraib** [IfcOpenShell/IfcOpenShell#610]
I was wondering if I can add a material and properties of materials using ifcopenshell, per example a wall of concrete with some properties. thank you

**Comment by aothms** [comment]
IfcOpenShell gives you access to the entire IFC schema, so the answer is yes. Perhaps this tutorial is useful http://academy.ifcopenshell.org/creating-a-simple-wall-with-property-set-and-quantity-information/

**Comment by raouajaraib** [comment]
@aothms  yes it is thank you

**Comment by Moult** [comment]
The API can also now do this with add_pset and edit_pset functions :) Marking as closed.
