### ISSUE TITLE
IFC 4.0.2.1 / IFC4 ADD2 TC1 support

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#611]
https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/ lists 4.0.2.1 | IFC4 ADD2 TC1 as being the latest official ISO publication. It seems as though the version that IfcOpenShell supports in the README (IFC4 Add1) is retired.

Time for a version bump? Or maybe the readme is out of date?

**Comment by aothms** [comment]
> Or maybe the readme is out of date?

It was. See https://github.com/IfcOpenShell/IfcOpenShell/commit/ef7eee411b29a82b55e3eec308baa20b8d3987c6 and updated in https://github.com/IfcOpenShell/IfcOpenShell/commit/491dc57098b919135c5984a0084265291af8c77a
