### ISSUE TITLE
IFC4 ADD2 support

### ISSUE THREAD

**Issue by LEILX** [IfcOpenShell/IfcOpenShell#613]
Hi, I would like to know if there is a solution for the problem mentioned in the issue : https://github.com/IfcOpenShell/IfcOpenShell/issues/604

Thanks a lot.

**Comment by aothms** [comment]
Hi, this is an open source software project, issues reported by the community are sincerely appreciated (especially with test files like yours), but cannot always be picked up within a matter of days. Thank you for your patience. Adding support for new geometry types like these is relatively straight forward, if you are in urgent need for this, you can also write the conversion functions yourself with help from the community.
