### ISSUE TITLE
Enable option to build Python from source in windows build script

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#62]
The default now, to use the official Python.org installers, can be disruptive to users that have the same Python version already installed on their system as it uninstalls that pre-existing version. Also makes it difficult/impossible to have multiple copies of the IfcOpenShell build system on the same system. There doesn't seem to be another way to get official Python binaries (except for say portablepython and the like), so the only alternative seems to be to build from source. This is what the *nix build system does now.

@Stinkfist0 is this observation correct? thoughts?

**Comment by Stinkfist0** [comment]
Building Python from the sources feels a bit of an overkill, although it would have some advantages (e.g. proper debug build, if a need ever rises to dive really deep). For me it would feel best/simplest to make installing Python an (optional for now) prerequisite: this could be fully manual or additionally we could provide a batch script that downloads the latest/desired (configurable) Python installer and shows user the normal installer GUI for doing the installation.

**Comment by Moult** [comment]
Is this still relevant with the more modern build systems?

**Comment by aothms** [comment]
It is, but I can't say that I still care.
