### ISSUE TITLE
--calculate-quantities sets IfcChangeActionEnum in ownerhistory as string

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#621]
1. Convert a file with `--calculate-quantities` on v0.6.0
2. Experience that the IfcChangeActionEnum in IfcOwnerHistory is set as a string `'MODIFIED'`.
e.g. ```#3080718=IFCOWNERHISTORY(#3080716,#3080717,$,'MODIFIED',$,$,$,1560775317);```
3. Expected as enum: 
```#3080718=IFCOWNERHISTORY(#3080716,#3080717,$,.MODIFIED.,$,$,$,1560775317);```

**Comment by aothms** [comment]
Oh thanks, good catch https://github.com/IfcOpenShell/IfcOpenShell/commit/ecb0fee0cda9b17fe1f9f0c2ba24b7d6e99d96fe
