### ISSUE TITLE
Missing subtractions on wall

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#624]
1. Convert [624--wall--missing-subtractions.ifc](https://github.com/IfcOpenShell/files/blob/master/624--wall--missing-subtractions.ifc) with 12e9f7b941e0fca8d4f5ee97e5204c2c5c9eb30c (v0.6.0 June 15 OCCT 7.3.0p3) and experience that the wall looks like this:
<img width="246" alt="Screenshot 2019-06-18 at 17 09 07" src="https://user-images.githubusercontent.com/4601554/59696202-db0e4b80-91eb-11e9-9725-0eb4bfcf44f6.png">

``` 
[Error] {07EGBo7Vr7HPWB6BjQao7K} Not enough points retained from:
#2222947=IfcPolyline((#9,#2222941,#2222943,#2222945,#9))
[Error] {07EGBo7Vr7HPWB6BjQao7K} Failed to convert:
#2222964=IfcPolygonalBoundedHalfSpace(#2222956,.T.,#2222963,#2222947)
[Error] {07EGBo7Vr7HPWB6BjQao7K} Failed to convert SecondOperand:
#2222964=IfcPolygonalBoundedHalfSpace(#2222956,.T.,#2222963,#2222947)
[Notice] {07EGBo7Vr7HPWB6BjQao7K} Boolean operation yields non-manifold result
[Notice] {07EGBo7Vr7HPWB6BjQao7K} Boolean operation yields non-manifold result
[Notice] {07EGBo7Vr7HPWB6BjQao7K} No longer attempting boolean operation with higher fuzziness
[Error] {07EGBo7Vr7HPWB6BjQao7K} Opening subtraction failed for 6 openings
```

2. Expected geometry from Solibri:
<img width="283" alt="Screenshot 2019-06-18 at 17 09 22" src="https://user-images.githubusercontent.com/4601554/59696223-e497b380-91eb-11e9-84c5-09e89706e46b.png">

Possibly related to #511 and #423

**Comment by Moult** [comment]
Seems to work now.

![2023-03-05-125433_409x480_scrot](https://user-images.githubusercontent.com/88302/222937414-c446e3a2-91fc-4a26-a5e6-25a9bafceacb.png)
