### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by atibaut** [IfcOpenShell/IfcOpenShell#626]
I encountered the UnicodeDecodeError when creating support for the IFC 4.2 schema with the command:
$ python3 bootstrap.py express.bnf > express_parser.py && python3 express_parser.py IFC4x2.exp

Error:
Traceback (most recent call last):
  File "express_parser.py", line 460, in <module>
    import header
  File "/IfcOpenShell/src/ifcexpressparser/header.py", line 24, in <module>
    import documentation
  File "/IfcOpenShell/src/ifcexpressparser/documentation.py", line 53, in <module>
    for oid, name, desc in csv.reader(f, delimiter=';', quotechar='"'):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 6602: invalid start byte

I implemented a workaround with modifying the line:
`    with open(fn) as f:`
to
`   with open(path, encoding="utf8", errors='ignore') as f:`
in the 
/IfcOpenShell/src/ifcexpressparser/documentation.py (line 50).
With the change I successfully created support for IFC 4x2 Draft (5 C++ files).

I have not created new pull request for that because I want to discuss the change with you. 
My system is Mac OS X.

**Comment by aothms** [comment]
> I have not created new pull request for that because I want to discuss the change with you.

I think it's a good approach. I know these files are invalid, but let's not think about it for too long. These are the old documentation dumps from the MS Access DB, since then bS moved to the "baselines" in IfcDoc and is now transitioning to an XML structure hosted on github.

So a quick fix for the encoding issues is very welcome.

**Comment by atibaut** [comment]
Pull request created for that.
