### ISSUE TITLE
0.6.0b0 Arch package : Compile error

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#632]
Hi,
I'm trying to compile on manjaro linux to update the AUR package : https://aur.archlinux.org/packages/ifcopenshell/

I get following error. I don't know how to solve it : 
```make
make[2]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build.make:63: ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:414: ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all] Error 2
make[1]: *** Attente des tâches non terminées....
[ 95%] Built target IfcAdvancedHouse
[ 97%] Linking CXX executable IfcOpenHouse
[ 97%] Built target IfcOpenHouse
[ 98%] Linking CXX executable IfcConvert
/usr/bin/ld : libIfcParse.a(parse_ifcxml.cpp.o) : dans la fonction « IfcParse::parse_ifcxml(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) » :
parse_ifcxml.cpp:(.text+0x347) : référence indéfinie vers « xmlSAXUserParseFile »
collect2: error: ld a retourné le statut de sortie 1
make[2]: *** [CMakeFiles/IfcConvert.dir/build.make:169: IfcConvert] Error 1
make[1]: *** [CMakeFiles/Makefile2:79: CMakeFiles/IfcConvert.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…
```
Many errors appears while building IfcAdvancedHouse.cpp.o : 
```make
Scanning dependencies of target IfcConvert
Scanning dependencies of target IfcAdvancedHouse
Scanning dependencies of target _ifcopenshell_wrapper
Scanning dependencies of target IfcOpenHouse
[ 89%] Building CXX object CMakeFiles/IfcConvert.dir/home/cyril/AUR_PKGBUILD/ifcopenshell/src/IfcOpenShell-0.6.0b0/src/ifcconvert/IfcConvert.cpp.o
[ 91%] Building CXX object examples/CMakeFiles/IfcOpenHouse.dir/IfcOpenHouse.cpp.o
[ 92%] Building CXX object ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o
[ 94%] Building CXX object examples/CMakeFiles/IfcAdvancedHouse.dir/IfcAdvancedHouse.cpp.o
/home/cyril/AUR_PKGBUILD/ifcopenshell/src/IfcOpenShell-0.6.0b0/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:2999:38: error: « attribute » dans l'espace de noms « IfcParse » ne nomme pas un type
  PyObject* pythonize(const IfcParse::attribute* t)   { return SWIG_NewPointerObj(SWIG_as_voidptr(t), SWIGTYPE_p_IfcParse__attribute, 0);          }
                                      ^~~~~~~~~
/home/cyril/AUR_PKGBUILD/ifcopenshell/src/IfcOpenShell-0.6.0b0/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:3000:38: error: « inverse_attribute » dans l'espace de noms « IfcParse » ne nomme pas un type
  PyObject* pythonize(const IfcParse::inverse_attribute* t) { return SWIG_NewPointerObj(SWIG_as_voidptr(t), SWIGTYPE_p_IfcParse__inverse_attribute, 0); }
                                      ^~~~~~~~~~~~~~~~~
```
There is some warning at the beginning I didn't get in previous version (0.6.0a1) : 
```make
-- Configuring done
WARNING: Target "IfcConvert" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Serializers" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "IfcParse" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "IfcGeom" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Serializers_ifc4" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "IfcGeom_ifc2x3" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "IfcGeom_ifc4" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Serializers_ifc2x3" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "_ifcopenshell_wrapper" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "IfcOpenHouse" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "IfcAdvancedHouse" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "IfcParseExamples" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
```

**Comment by aothms** [comment]
Oh, thanks, I wasn't aware of that package.

> /usr/bin/ld : libIfcParse.a(parse_ifcxml.cpp.o) : dans la fonction « IfcParse::parse_ifcxml(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) » :

Yes, I think we made some mistakes in how the XML parsing support is selected. Your options are either:

* Disable IfcXML parsing support with `-DIFCXML_SUPPORT=Off`. The IfcXML schema is not really stable anyway so it's a bit premature to offer support for it.
* Properly configure the inclusion and linking to libxml2 with (`LIBXML2_INCLUDE_DIR` `LIBXML2_LIBRARIES`) 

The errors you mentioned are not about IfcAdvancedHouse (the lines are probably a bit interleaved due to the multi-threaded compilation.

~~~
/home/cyril/AUR_PKGBUILD/ifcopenshell/src/IfcOpenShell-0.6.0b0/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:2999:38: error: « attribute » dans l'espace de noms « IfcParse » ne nomme pas un type
  PyObject* pythonize(const IfcParse::attribute* t)   { return SWIG_NewPointerObj(SWIG_as_voidptr(t), SWIGTYPE_p_IfcParse__attribute, 0);          }
                                      ^~~~~~~~~
/home/cyril/AUR_PKGBUILD/ifcopenshell/src/IfcOpenShell-0.6.0b0/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:3000:38: error: « inverse_attribute » dans l'espace de noms « IfcParse » ne nomme pas un type
  PyObject* pythonize(const IfcParse::inverse_attribute* t) { return SWIG_NewPointerObj(SWIG_as_voidptr(t), SWIGTYPE_p_IfcParse__inverse_attribute, 0); }
                                      ^~~~~~~~~~~~~~~~~
~~~

At an earlier point these classes were nested inside as IfcParse::entity::attribute. That's the only thing I can think of. Is your entire working tree clean?

**Comment by CyrilWaechter** [comment]
No matter what I set. I get the same error : 
* with `-DIFCXML_SUPPORT=OFF` [PKGBUILD_XML_OFF.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3327302/PKGBUILD_XML_OFF.txt)
* with `-DLIBXML2_INCLUDE_DIR=/usr/include/libxml2` and `-DLIBXML2_LIBXML2_LIBRARIES=/usr/lib` [PKGBUILD_XML_ON.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3327340/PKGBUILD_XML_ON.txt)

```shell
make[1]: *** [CMakeFiles/Makefile2:457: ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all] Error 2
make[1]: *** Attente des tâches non terminées....
[ 92%] Built target IfcGeomServer
[ 94%] Linking CXX executable IfcOpenHouse
[ 94%] Built target IfcOpenHouse
[ 95%] Linking CXX executable IfcConvert
/usr/bin/ld : libIfcParse.a(parse_ifcxml.cpp.o) : dans la fonction « IfcParse::parse_ifcxml(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) » :
parse_ifcxml.cpp:(.text+0x347) : référence indéfinie vers « xmlSAXUserParseFile »
collect2: error: ld a retourné le statut de sortie 1
make[2]: *** [CMakeFiles/IfcConvert.dir/build.make:169: IfcConvert] Error 1
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/IfcConvert.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…
```
>  Is your entire working tree clean?

I think so. A build folder is created during the process.

> Properly configure the inclusion and linking to libxml2 with (LIBXML2_INCLUDE_DIR LIBXML2_LIBRARIES)

It seems to find it properly. If not it fails at 22%.

**Comment by aothms** [comment]
It could be related to cmake's caching. The script does `mkdir -p build` but doesn't delete the build directory. For most config settings this wouldn't be necessary, but for ifcxml support it might be necessary to either `rm build/CMakeCache.txt` or `rm -rf build/`. Could you try that?

**Comment by CyrilWaechter** [comment]
Thanks for your answer. I unfortunately don't understand it.

When I start the script the `build` folder do not exist so there is no CMakeCache.txt. I delete `src` folder which contains build folder between each try. `makepkg` build the package in a fakeroot and package manager like pacman build it in /tmp folder by default so everything is erased at each restart. I simulate this by manually deleting created folders.

So I don't understand where in the script I should add `rm -rf build/`.

Additional information : 
- Looking at `CMakeCache.txt` It looks like `-DIFCXML_SUPPORT=OFF` has been correctly parsed :
```shell
//Build IfcParse with ifcXML support (requires libxml2).
IFCXML_SUPPORT:BOOL=OFF
```
- I tried on my laptop. Error message appear slightly later and is slightly different : 
```shell
[ 95%] Linking CXX executable IfcAdvancedHouse
make[2]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build.make:63: ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:457: ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all] Error 2
make[1]: *** Attente des tâches non terminées....
[ 95%] Built target IfcGeomServer
[ 95%] Built target IfcAdvancedHouse
[ 97%] Linking CXX executable IfcOpenHouse
[ 97%] Built target IfcOpenHouse
[ 98%] Linking CXX executable IfcConvert
[ 98%] Built target IfcConvert
make: *** [Makefile:130: all] Error 2
```

I saw that IfcOpenBot is building IfcOpenShell at each commit. Is there a way to automatically fetch last IfcOpenBot build ? (like it is possible to fetch last github release with a specific url). Would it be a good workaround until we find a better solution ?

**Comment by CyrilWaechter** [comment]
As libxml2 is a C library. Is there any interest for you to use libxmll++ which is a C++ binding for libxml2 ?
(I saw this while investigating on my issue)

I tried to  used cmake + make outside of make package to avoid any potential overridden flag issue and also used make without using multicore. Result : 
-  with IFCXML_SUPPORT=OFF : 
```make
[ 90%] Building CXX object ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o
/home/cyril/AUR_PKGBUILD/ifcopenshell/src/IfcOpenShell-0.6.0b0/build/ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx:2999:38: erreur: « attribute » dans l'espace de noms « IfcParse » ne nomme pas un type
 2999 |  PyObject* pythonize(const IfcParse::attribute* t)   { return SWIG_NewPointerObj(SWIG_as_voidptr(t), SWIGTYPE_p_IfcParse__attribute, 0);          }
___ many other errors ___
make[2]: *** [ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/build.make:63: ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/CMakeFiles/_ifcopenshell_wrapper.dir/IfcPythonPYTHON_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:489: ifcwrap/CMakeFiles/_ifcopenshell_wrapper.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
- with IFCXML_SUPPORT=ON : 
```make
[ 87%] Linking CXX executable IfcConvert
/usr/bin/ld: libIfcParse.a(parse_ifcxml.cpp.o): référence au symbole non défini « xmlSAXUserParseFile@@LIBXML2_2.4.30 »
/usr/bin/ld : /usr/lib/libxml2.so.2 : erreur lors de l'ajout de symboles : DSO manquant dans la ligne de commande
collect2: erreur: ld a retourné le statut de sortie 1
make[2]: *** [CMakeFiles/IfcConvert.dir/build.make:169: IfcConvert] Error 1
make[1]: *** [CMakeFiles/Makefile2:394: CMakeFiles/IfcConvert.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Does the `@@LIBXML2_2.4.30` means that something is looking at libxml2 2.4.30 version which is from [Dec 12 2002](http://www.xmlsoft.org/news.html) ?

**Comment by aothms** [comment]
> As libxml2 is a C library. Is there any interest for you to use libxmll++ which is a C++ binding for libxml2 ?

Thanks. Could be, it's not a big concern for me, basically we only call `xmlSAXUserParseFile()` so I don't expect it to be a big difference.

Is there anyway I can reproduce this locally? I'm not familiar with Arch.

**Comment by CyrilWaechter** [comment]
> Is there anyway I can reproduce this locally? I'm not familiar with Arch.

I prepared a VirtualBox image (.vdi) for you with manjaro, all ifcopenshell dependencies and distro updates already installed. I also removed some unnecessary packages and change keyboard default to dutch according to your pro website address. 
- Link : http://pythoncvc.net/iso/IfcOpenShellBuild.tar.xz
- User : ifcopenshell
- Password : ifcopenshell (also for root rights if needed use sudo)

To reproduce errors : 
1. Open a terminal
2. Go to ifcopenshell_git repo folder
3. Use `makepkg` (It will download ifcopenshell sources from github and try to build using cmake/make)
4. Once `makepkg` ran once you have all source in `src` folder and you can use cmake/make as in any other distro.

Corresponding commands : 
```shell
cd git/ifcopenshell
makepkg
cd src/IfcOpenShell-0.6.0b0/build
cmake ../cmake \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_CXX_STANDARD=11 \
      -DOCC_INCLUDE_DIR=/usr/include/opencascade \
      -DOCC_LIBRARY_DIR=/usr/lib \
      -DOPENCOLLADA_INCLUDE_DIR=/usr/include/opencollada \
      -DOPENCOLLADA_LIBRARY_DIR=/usr/lib/opencollada \
      -DPYTHON_INCLUDE_DIR=/usr/include/python${_pythonver:7:3}m \
      -DPYTHON_LIBRARY=/usr/lib64/libpython${_pythonver:7:3}m.so \
      -DSWIG_EXECUTABLE=/usr/bin/swig \
      -DLIBXML2_INCLUDE_DIR=/usr/include/libxml2 \
      -DLIBXML2_LIBRARIES=/usr/lib
make
cmake ../cmake \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_CXX_STANDARD=11 \
      -DOCC_INCLUDE_DIR=/usr/include/opencascade \
      -DOCC_LIBRARY_DIR=/usr/lib \
      -DOPENCOLLADA_INCLUDE_DIR=/usr/include/opencollada \
      -DOPENCOLLADA_LIBRARY_DIR=/usr/lib/opencollada \
      -DPYTHON_INCLUDE_DIR=/usr/include/python${_pythonver:7:3}m \
      -DPYTHON_LIBRARY=/usr/lib64/libpython${_pythonver:7:3}m.so \
      -DSWIG_EXECUTABLE=/usr/bin/swig \
      -DIFCXML_SUPPORT=OFF
make
```
I wish I could help more.

**Comment by AECgeeks** [comment]
Many thanks for this. Very comprehensive! It's still on my list to look into this.

**Comment by aothms** [comment]
I haven't been very successful in running the image

Using the default boot options I get:

![afbeelding](https://user-images.githubusercontent.com/1096535/62358671-7007a280-b515-11e9-9bf5-1720296323c5.png)

If I go into advanced settings I can select another kernel, which proceeds a bit further, but it's taking 10 minutes now for man-db indexing. Is that expected?

Are there any settings I need to keep in mind when configuring the VM?

**Comment by CyrilWaechter** [comment]
I am not very experimented with VM transfer. I naively thought that just sending the .vdi would work. Let me test this on another computer and do some research. What OS do you use ?

**Comment by aothms** [comment]
> What OS do you use to host VirtualBox ?

Typically Windows.

![afbeelding](https://user-images.githubusercontent.com/1096535/62362192-c5937d80-b51c-11e9-99eb-07f616d0646e.png)

Not sure if it is related to the .vdi, googling around seems like more people sometimes get stuck at this step.

**Comment by CyrilWaechter** [comment]
I succeeded to launch it on my laptop running windows 10. Steps : 
1. Launch VirtualBox (6.0.10)
2. Create a new VM with options : 
    - Linux / Other Linux (64 bits) -> Next
    - Default memory values -> Next
    - Copy .vdi file into my new VM folder
    - Select use an existing virtual disk and choose file above -> Create
3. Launch VM -> Fail
4. Click on VM configuration : 
    - In System : 
        - Motherboard : Increase RAM allocation to about 5000 MB
        - Processor : Increase processor nb to 4
    - In Display : 
        - Increase video memory to 128 MB
    - In Storage : 
        - Delete empty IDE controller
5. Launch VM -> Works

Tell me if it helps

**Comment by aothms** [comment]
Thanks! It actually did. It's probably mostly in updating VirtualBox and perhaps the video memory. Everything behaved very differently with the newest VB, bigger screen, mouse support, ... 

I will be looking into the actual problem now

**Comment by aothms** [comment]
Your file with IFCXML disabled seems to be working for me. What can we do next?

https://github.com/IfcOpenShell/IfcOpenShell/files/3327302/PKGBUILD_XML_OFF.txt

![afbeelding](https://user-images.githubusercontent.com/1096535/62380764-2eddb580-b54a-11e9-8caa-d1a34135f9ee.png)

**Comment by CyrilWaechter** [comment]
I am confused. I was certain that I tested with both IFCXML_SUPPORT ON and OFF before sending the VM. Now I get the same result as you do. IFCXML_SUPPORT ON still fails.

- for IFCXML_SUPPORT OFF : I'll try to reset my make/makepkg flag to default just in case. But I tried on 2 different computer 1 running an intel CPU, 1 running an AMD CPU. I heard that some error cannot be catch in a VM but I don't know that much about it. I'll investigate.
- for IFCXML_SUPPORT ON : If you have any idea of why it fails with IFCXML_SUPPORT ON I am taker. (PKG file with is in `~/git/ifcopenshell`)

**Comment by aothms** [comment]
> -DLIBXML2_LIBRARIES=/usr/lib

Sorry, I should have spotted that earlier. This requires full paths to the libraries, it's a bit inconsistent with the other arguments, but reasoning is that libxml depends on a whole lot of other libraries often that vary based on distro, for example on Travis we have `-DLIBXML2_LIBRARIES="/usr/lib/x86_64-linux-gnu/libxml2.a;/lib/x86_64-linux-gnu/libz.so.1;/lib/x86_64-linux-gnu/liblzma.so.5;/usr/lib/x86_64-linux-gnu/libicuuc.so.55;/usr/lib/x86_64-linux-gnu/libicudata.so.55"`. So something like this we'll need to construct for manjaro as well.

based on `ldd /usr/lib/libxml2.so.2` I'd try with `-DLIBXML2_LIBRARIES="/usr/lib/libxml2.so.2;/usr/lib/libicuuc.so.64;/usr/lib/libz.so.1;/usr/lib/liblzma.so.5;/usr/lib/libicudata.so.64"`

> WARNING: Target "IfcConvert" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.

This is related to that.

**Comment by CyrilWaechter** [comment]
Nice compilation successful with LIBXML2 on my laptop !
I still need to figure out why it fails on my main computer.

**Comment by CyrilWaechter** [comment]
I'll close this issue as even if successfully compiled it doesn't work (python version issue corrected in git version). I'll give it another try on next release.
I used version compiled by ifcopenbot to get last updates and it works (is there a way to automatically get last compiled version by ifcopenbot ? If so I'll create a package based on this.)

**Comment by aothms** [comment]
> is there a way to automatically get last compiled version by ifcopenbot ? If so I'll create a package based on this.

There is. But I would recommend against it. Not every commit in the working branches is guaranteed to be perfectly stable. Also the json-file based query is not stable. The update is likely not atomic and the file might be absent or wrong in case of build failures. 

https://s3.amazonaws.com/ifcopenshell-builds/v0.6.0.json

> if successfully compiled it doesn't work (python version issue corrected in git version). I'll give it another try on next release.

I don't fully understand, is there something I can look into?

**Comment by CyrilWaechter** [comment]
Good news. Both v0.6.0b0 and git version master and v0.6.0 can be on Archlinux thanks to the original packager mickele and another Arch user skrat.
In case you are interested. It was mainly a SWIG version issue. SWIG3 works, SWIG4 doesn't.
* [Patch applied for v0.6.0b0](https://aur.archlinux.org/cgit/aur.git/commit/?h=ifcopenshell&id=f1c02b7e7a7f94a9477d41713c4a22f13e5edd2d)
* [Patch applied for git master](https://aur.archlinux.org/cgit/aur.git/commit/?h=ifcopenshell-git&id=6367b128ab6cc6b9349a2bc23273cac6355b5154)
* [New git v0.6.0 package](https://aur.archlinux.org/packages/ifcopenshell-v0.6.0-git/)
