### ISSUE TITLE
No operation defined for IfcArbitraryClosedProfileDef(.CURVE.)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#642]
1. Convert [576--buildingElementProxy--wrong-geometry--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/576--railing--wrong-geometry--augmented.ifc) with b4ce5be
2. Experience error:
```
[Error] {3Q6fhvP4L6Uhrx1GmvPNSt} No operation defined for:
#2281=IfcArbitraryClosedProfileDef(.CURVE.,'Revolved Face Profile Curve',#2282)
[Error] {3Q6fhvP4L6Uhrx1GmvPNSt} Failed to create face.
[Error] {3Q6fhvP4L6Uhrx1GmvPNSt} Failed to convert:
#2280=IfcSurfaceOfRevolution(#2281,$,#2285)
```

**Comment by Moult** [comment]
Seems to work now.

![2023-03-05-125350_537x534_scrot](https://user-images.githubusercontent.com/88302/222937399-f7fd2b64-5ade-4f5d-a366-e10fa64abee9.png)
