### ISSUE TITLE
materials

### ISSUE THREAD

**Issue by raouajaraib** [IfcOpenShell/IfcOpenShell#645]
hello 
I need to exact an object(like a wall) with his material(like concrete) is there any function that I can use to determine the relationship with the wall and concrete?, thank you

**Comment by aothms** [comment]
https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/ifcproductextension/lexical/ifcrelassociatesmaterial.htm

So that's the `HasAssociations` attribute of the wall.
