### ISSUE TITLE
Reading outside of file limits exception

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#646]
PEBKAC.

**Comment by aothms** [comment]
The IfcOpenShell v0.6.0 IfcConvert has something for this. It can convert IFC to IFC and will actually sort the instances. It will also format it with only a single newline after the entity instance definitions, so perhaps more suitable for text-based processing.

For text-based sort, the first things to think of are newlines in the instance definitions and the header entities.
