### ISSUE TITLE
Unable to find instance ID due to numeric name sort

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#647]
According to http://www.steptools.com/stds/step/IS_final_p21e3.html it seems that entity instance ordering should not actually matter (exact quote: `The entity instances need not be ordered in the exchange structure. `). However, I presume the ordering does matter for optimising lookups.

I found an issue when trying to parse an IFC file with the following content:

```
[ ... snip ... ]
#20121= IFCSHAPEREPRESENTATION(#109,'Body','MappedRepresentation',(#20119));
#20123= IFCPRODUCTDEFINITIONSHAPE($,$,(#20121));
#20125= IFCCARTESIANPOINT((30.25,10.5833333333333,2.83333333333309));
#20127= IFCAXIS2PLACEMENT3D(#20125,#19,#13);
#7723094= IFCRELVOIDSELEMENT('1eau$aP6HFEuMvq$O5uasi',#41,$,$,#3339761,#7723091);
#20129= IFCCARTESIANPOINT((30.25,10.5833333333333,2.83333333333309));
#20131= IFCAXIS2PLACEMENT3D(#20129,#19,#13);
#20132= IFCLOCALPLACEMENT(#298,#20131);
[ ... snip ... ]
```

As you can see the `IFCRELVOIDSELEMENT` is not ordered. When I have that element in IfcOpenShell and I try to do `element.RelatingBuildingElement.id()`, IfcOpenShell tells me it cannot find the element with ID `3339761`. I should note that this element _does_ exist but is defined further down the file.

If it helps with debugging, the element is defined as follows:

```
#3339761= IFCWALLSTANDARDCASE('063rd4jBL4sOxpIeS08bc6',#41,'Basic Wall:COMPOSITE SIDING/DECKING:1922866',$,'Basic Wall:COMPOSITE SIDING/DECKING',#3339741,#3339759,'1922866');
```

If I edit the IFC file by hand and sort it numerically (tested with Vim's `:sort n`) then IfcOpenShell no longer has this problem.

**Comment by aothms** [comment]
> However, I presume the ordering does matter for optimising lookups.

Not really for IfcOpenShell, everything goes into one big mapping. 

Is there a way you can share the file with these issues? I'd like to understand what's going on.

**Comment by Moult** [comment]
Hmm, I am struggling to recreate a simple test case for this bug. I tried with this code, but it succeeds without any issue:

```
>>> for r in f.by_type('IfcRelVoidsElement'):
...     print('{}, {}'.format(r.RelatedOpeningElement.id(), r.RelatingBuildingElement.id()))
```

So it seems that indeed order doesn't matter.

As I was editing some of this IFC by hand, I suspect that perhaps there were some parsing errors. I will close this issue as PEBKAC until I can recreate it.
