### ISSUE TITLE
Branch 0.6.0b0 : Compilation error

### ISSUE THREAD

**Issue by JeanValjean2** [IfcOpenShell/IfcOpenShell#648]
Hi,

first of all, congratulations for your software ! I use it to generate gltf files and floorplans from IFC files and it's nothing short of amazing.
I'd like to ask you for some consultancy work since I'm doing all this professionally but I guess I'll do it in private.

What I want to highlight here is something I needed to do to be able to compile the 0.6.0b0 branch on my system (Debian 9, OCE 0.18.3).

The file [src/ifcgeom/IfcGeomFunctions.cpp](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomFunctions.cpp#L466) wouldn't compile and threw errors about unknown methods in OCC's ShapeUpgrade_UnifySameDomain class around line 466.

What I ended up doing was commenting out the 3 lines below to allow the compilation to continue :

```
	TopoDS_Shape unify(const TopoDS_Shape& s, double tolerance) {
		tolerance = (std::min)(min_edge_length(s) / 2., tolerance);
		ShapeUpgrade_UnifySameDomain usd(s);
//		usd.SetSafeInputMode(true);
//		usd.SetLinearTolerance(tolerance);
//		usd.SetAngularTolerance(1.e-3);
		usd.Build();
		return usd.Shape();
	}
```

I commented out these 3 calls because I couldn't find any kind of mentions of these 3 methods in OCC.

I guess my versions of IfcOpenShell and OCC are not aligned but I don't know (i.e. too lazy to find) which OCC version I should check out.
Can you enlighten me ?

Note : I also had to disable inclusion of libxml2, as indicated in #632

**Comment by aothms** [comment]
Thanks, for a large time, IfcOpenShell has been compatible with OCE / OCCT 6.9.x, but I think we're slowly gravitating towards requiring OCCT 7+. Not sure when those methods got added though. I'll probably correct this with an ifdef over time (or feel free to provide a PR if interested)

For now better get your OCCT here https://git.dev.opencascade.org/gitweb/?p=occt.git;
 V7_3_0p3 is the branch I'm recommending.

Also have a look at the build script https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/nix/build-all.py#L540

**Comment by JeanValjean2** [comment]
Thanks a lot for these two links, everything is clearer now.

I was able to use the SVG conversion to obtain nice floorplans and my web app starts to take shape.

Thanks again.
