### ISSUE TITLE
Provide a --layerset-first to option to get surface style from multiple material layerset without boolean ops

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#649]
1. Convert [649--wall--wrong-color--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/649--wall--wrong-color--augmented.ifc) with baf5f1891f47eed61c66a43400580b0a9e29db6b and experience that the wall turns out all grey:

```
newmtl IfcWallStandardCase
Kd 0.9 0.9 0.9
```
<img width="250" alt="Screenshot 2019-07-31 at 16 30 49" src="https://user-images.githubusercontent.com/4601554/62223086-a679dc00-b3b4-11e9-9c8b-8453e496e5c2.png">

2. Open the same file in Solibri or SimpleBIM and experience that the wall is yellow (as expected from Archicad):
<img width="250" alt="Screenshot 2019-07-31 at 16 23 48" src="https://user-images.githubusercontent.com/4601554/62223149-c0b3ba00-b3b4-11e9-87c5-be84ea60e4df.png">

There seems to be some missing link when colours are defined from `IfcMaterial`, – I've tried to diagnose the expected behaviour here:  [649--colormapping-diagnosis.pdf](https://github.com/IfcOpenShell/IfcOpenShell/files/3452537/649--colormapping-diagnosis.pdf)

**Comment by aothms** [comment]
This is a wall with multiple material layers

~~~
#54397=IFCMATERIAL('');
#54398=IFCCOLOURRGB($,1.,1.,0.);
#54399=IFCSURFACESTYLERENDERING(#54398,0.,IFCNORMALISEDRATIOMEASURE(0.81),$,$,$,IFCNORMALISEDRATIOMEASURE(0.09),$,.NOTDEFINED.);
#54400=IFCSURFACESTYLE('',.BOTH.,(#54399));
#54402=IFCPRESENTATIONSTYLEASSIGNMENT((#54400));
#54404=IFCSTYLEDITEM($,(#54402),$);
#54406=IFCSTYLEDREPRESENTATION(#189,$,$,(#54404));
#54408=IFCMATERIALDEFINITIONREPRESENTATION($,$,(#54406),#54397);
#54412=IFCMATERIALLAYER(#54397,13.,.U.);
#54413=IFCMATERIALLAYER(#672,48.,.U.);
#54414=IFCMATERIALLAYERSET((#54412,#54413),'');
~~~

If you invoke IfcConvert with `--enable-layerset-slicing`. The colors are (hopefully) correctly processed

![afbeelding](https://user-images.githubusercontent.com/1096535/62793906-01a58000-bad3-11e9-8ce9-929422b3f308.png)

Elements with a single layer or direct material association will get the corresponding surface style from their material association even when `--enable-layerset-slicing` is not set.

**Comment by johanrd** [comment]
Ok, thanks for looking into it!

`--enable-layerset-slicing` is a powerful feature indeed. However, this may be overkill in many situations (which is also why it is not enabled by default, I guess)

Solibri seems to select the "first" material and render the complete object with the first material. This may be a good default to consider also for IfcOpenShell (instead of the fallback greu when running without `--enable-layerset-slicing`).

Further, I did run into some problems with the edges of `--enable-layerset-slicing` in the edges of IfcRelConnectsPathElements. See #654

**Comment by aothms** [comment]
> In the case of multi-layered objects with no direct material association, Solibri seems to apply the "first" material as fallback. This may be a good default to consider also for IfcOpenShell with layerset-slicing disabled (instead of the setting the fallback to grey).

First seems very arbitrary to me. Also, on a geometrical level there can still be a style assigned to the complete representation item.

Maybe then introduce some additional flags like --layerset-first or --layerset-thickest?

**Comment by johanrd** [comment]
"First" may be as arbitrary as "last", but in the case of a sandwitch-layered object (paint -> plaster, -> insulation ->plaster -> paint), you would expect "outer" layers to dominate the outer appearance, not the "thickest". 

It does seem like solibri picks the "first".

**Comment by aothms** [comment]
I agree, thickest does not make a lot of sense. This day and age, insulation is probably thickest quite frequently. 

> "First" may be as arbitrary as "last",

Unless there is somehow a convention that first is supposed to be the interior/exterior. I don't know though.

I'll reword the issue title. Is anybody in your company interested in picking this up, or are you leaving this for me?

**Comment by johanrd** [comment]
Ok, thanks. 

We don't have any immediate plans on picking this up ourselves, but would be happy to support the development if you have a path in mind.

**Comment by johanrd** [comment]
Hi. We have a fix ready for this, where we argue it is not necessary with a `--layerset-first` option. Picking the first material (when running without `--enable-layerset-slicing`) should be the default behavior, as the 'first' material in the IfcMaterialLayerSet is in most cases a better fallback color than outputting the fallback of "no known material". This is also how Solibri behaves:


1. Convert [649--wall--wrong-color--augmented--2.ifc](https://github.com/IfcOpenShell/files/blob/master/649--wall--wrong-color--augmented--2.ifc) with `--enable-layerset-slicing` in IfcOpenShell:
<img width="300" alt="Screenshot 2020-02-24 at 17 04 49" src="https://user-images.githubusercontent.com/4601554/75170848-00fcd000-572b-11ea-904e-ce63ee28b5c8.png">

2. Convert the same file without `--enable-layerset-slicing` in IfcOpenShell, and experience that the output is fallback grey:
<img width="300" alt="Screenshot 2020-02-24 at 17 06 47" src="https://user-images.githubusercontent.com/4601554/75170668-bed38e80-572a-11ea-8beb-0a373bd8f234.png">

3. Open the same file in Solibri and experience that the wall appears all yellow:
<img width="300" alt="Screenshot 2020-02-24 at 17 18 55" src="https://user-images.githubusercontent.com/4601554/75170027-c5153b00-5729-11ea-87d2-a05f6a98ceea.png">

4. To check that Solibri picks the first material, chage the order of materials in line `#54414` to e.g:

```
#54414=IFCMATERIALLAYERSET((#54412,#54411,#54413),'');
```

5. When opening the edited file in Solibri, the wall now appears all red:
<img width="300" alt="Screenshot 2020-02-24 at 17 24 39" src="https://user-images.githubusercontent.com/4601554/75170550-92b80d80-572a-11ea-9733-2022c28790da.png">

PR coming soon.

**Comment by AlaaB2020** [comment]
PR #799 is created for this issue
