### ISSUE TITLE
Unable to explicitly close files opened with IfcOpenShell

### ISSUE THREAD

**Issue by anders-lundgren** [IfcOpenShell/IfcOpenShell#650]
The IfcOpenShell Python wrapper lacks an explicit close() method, and also an implementation of the __exit__() method used for with statements.
This means that when creating a large number of IFC files from a script, eventually the script will fail due to the number of open files. 
Error message: 
```
OSError: [Errno 24] Too many open files
```
Attached sample script that reproduces the error. 
[IfcSplit.py.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3455488/IfcSplit.py.txt)

Tested with the Office MEP coordination model from http://projects.buildingsmartalliance.org/files/?artifact_id=4284 but should be possible to reproduce with any sufficiently large file (containing more products than the OS file handle limit, on my machine this means >2000 products).

**Comment by cadgiru** [comment]
Probably same issue. When running ifcdiff on a bunch of file from a script. Each time a file is fed to ifcdiff, memory usage increases. Eventually runs out of memory and crashes.

**Comment by aothms** [comment]
It's not necessary to explicitly close files. I've added the necessary fix in the C++ code. Note that ifcopenshell.open() keeps a file handle open (but basically also only for historic reasons that should be abolished). ifcopenshell.write() already just wrote to disk and then immediately closed the file.

So the issue wasn't so much in the write() which you might have assumed but in the way you used a tempfile to initialize the file to be written. There are better ways to do that, such as ifcopenshell.template which uses (ifcopenshell.file.from_string)

@cadgiru this is probably another issue.

Did you try recently after the build for https://github.com/IfcOpenShell/IfcOpenShell/issues/1692#issuecomment-992047291

Could still be small memory leaks though, would be good if we can track them down. For that it'd really help if we get minimal example to reproduce, so preferably not complex scripts such as ifcdiff.

**Comment by YaroslavKormushyn** [comment]
I've encountered an issue with Python actually reclaiming memory from an opened file loaded into memory.
I'm using Python 3.8 with ifcopenshell 0.7.0 from PyPI.
A snippet from a function in my case:
```python
ifcopenshell_settings = ifcopenshell.geom.settings()
ifcopenshell_settings.set(ifcopenshell_settings.USE_WORLD_COORDS, True)
ifcopenshell_settings.set(ifcopenshell_settings.USE_BREP_DATA, True)
ifcopenshell_settings.set(ifcopenshell_settings.USE_PYTHON_OPENCASCADE, True)

ifc_file = ifcopenshell.open(ifc_filename)

# this doesn't affect garbage collection
xAxisOrdinate, xAxisAbscissa = ifc_file.by_type("IfcProject")[0].RepresentationContexts[0].TrueNorth.DirectionRatios

site = ifc_file.by_type("IfcSite")[0]

# this line prevents memory reclaim and the ifc_file stays in memory indefinitely
conversion_pset = ifcopenshell.api.run("pset.add_pset", ifc_file, product=site, name="ePSet_MapConversion")
```

After running this snippet multiple times (e.g. in a loop), I'm seeing a memory leak, where the `ifc_file` doesn't get unloaded. After some time this crashes the host (OOM).

Maybe there's something I'm overlooking when opening or using the file? After removing the last line from the snippet - the memory leak is gone.

**Comment by aothms** [comment]
@YaroslavKormushyn since this is so specific to the API I would assume this is better treated as a new issue. What does `import gc; gc.get_referrers(ifc_file)` tell say?

**Comment by YaroslavKormushyn** [comment]
@aothms referrers before `ifcopenshell.api.run`:
![image](https://user-images.githubusercontent.com/11539004/193752200-c0c63587-52b3-46fb-a95d-cabe01fe3737.png)
Referrers after:
![image](https://user-images.githubusercontent.com/11539004/193752275-48d0edb8-6157-455f-8d15-46acf087bfad.png)

The logging module didn't let me just dump these as JSON, so let me know if I could be of more help with the reporting.

**Comment by YaroslavKormushyn** [comment]
Confirming the file memory gets released now. No more comments from me on this issue.
