### ISSUE TITLE
IfcBlender reuses meshes from previous import

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#661]
https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcblender/io_import_scene_ifc/__init__.py#L101

**Comment by elmopl** [comment]
What would be preferred behaviour here?
I can think of either:
 - when importing file overwriting mesh already in Blender (which is a bit destructive and has potential to replace meshes entirely unrelated to import)?
 - generate new name if a clash with pre-existing (pre-import start) exists?

Second option seems like a safer one, especially if you load multiple IFC files that have some shared names.

It could always be an option/checkbox for import to switch between the two (I think default should be second).

**Comment by aothms** [comment]
I agree. I think during import we could have a dict from IfcOpenShell geom name to bpy.data.mesh just as a local variable. That way we can just depend on Blender's name postfixing for non-unique names. And we'd never share geometrical instances between subsequent imports which I think is (almost) never desired.

**Comment by elmopl** [comment]
Uh, I just realised I am missing one crucial line from above.
Currently I removed sharing of mesh instances entirely.
I am missing:

    project_meshes[mesh_name] = me

Somewhere inside of that if after we've created mesh object.
I will try to create a fix PR in hopefully not too distant future.
