### ISSUE TITLE
IfcOpenShell convert IFC to COBie spreadsheets

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#663]
I could not find an open source IFC to COBie converter or COBie related checking apart from xBIM, which I'd rather stay away from due to its .NET nature. Does this exist in IfcOpenShell, or would it be easy to implement? I think it would definitely be desirable ... but I haven't found yet any computer interpretable descriptions of the IFC<->COBie relationships, so it may be a bit of a mapping by-hand, without much of a guarantee that your mapping is the same as someone else's mapping.

Related post: https://forums.buildingsmart.org/t/cobie-and-ifc-mapping/1796

**Comment by aothms** [comment]
I honestly don't know a lot about cobie. I think the intention is for it to become a MVD (https://github.com/opensourceBIM/python-mvdxml/ a submodule in ifcopenshell as well) but not sure where that stands currently.

**Comment by Moult** [comment]
Extraction is now complete for the "Contacts" portion of the spreadsheet! More to come!

**Comment by aothms** [comment]
Great :)

A couple year ago we wrote a data extraction utility, from IFC to CSV or RDF using something like a Domain Specific Language (a python subset actually).

https://github.com/DURAARK/pyIfcExtract

It probably doesn't run anymore on recent versions of IfcOpenShell and never found the time to update it, but the idea of a higher level syntax to specify a mapping from IFC literals to other data formats is still pretty powerful in my eyes.

**Comment by Moult** [comment]
Ooh, that's very cool! Certainly, a DSL can make these mappings much more concise and readable. I will have a play.

Off-topic, but if this DSL could be extended to describe tests (like unit tests, but for buildings) kind of the same way developers use Gherkin syntax to write tests, that would be cool.

Waiting for the day I can write:

"The building "too" must comply to Australian building codes" - All tests pass... :)

**Comment by aothms** [comment]
If I recall correctly this student thesis does something similar https://research.tue.nl/files/51166982/Weerink_2016.pdf

Convert readable requirements into mvdXML and use a tool to check whether the IFC conforms.

**Comment by Moult** [comment]
Closing this issue as the basic implementation is there - it needs a lot of polish, to be sure, but that will come with time!
