### ISSUE TITLE
Can the IfcOpenShell geometry viewer show polylines?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#665]
I have generated a small test IFC which contains just a few polylines to test a "wireframe" view. I think it would be useful when certain objects don't need a full solid representation. However, when I open it up using `ifcopenshell.geom.app`, I cannot see the lines. Is the viewer able to render the lines?

[output.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3583825/output.ifc.txt)

**Comment by aothms** [comment]
By default polylines are not processed as root representation items.

You can try adding `setting.set(setting.INCLUDE_CURVES)` here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/geom/app.py#L480

Not entirely sure if it would work directly, but there shouldn't be anything fundamentally in the way of getting this to work either.

**Comment by Moult** [comment]
It works! Awesome, thanks!
