### ISSUE TITLE
IFC 4 release request

### ISSUE THREAD

**Issue by amirmakan** [IfcOpenShell/IfcOpenShell#666]
Please support IFC 4, I made Interactive BIM automated from IFC files. For swing and  doors, windows and elevators and lighting fixtures.
 
Windows x64
Thanks 
Amirianfar

**Comment by Moult** [comment]
Good morning Amirianfar! IfcOpenShell certainly does support IFC4. If you are using the master branch, please compile IfcOpenShell with the USE_IFC4=on. Alternatively, you can compile the v0.6.0 branch, which supports multiple IFC versions with the ability to switch at run-time.

**Comment by amirmakan** [comment]
Thanks dear Dion.
Can you tell me how can I change name of family subcategory object in the
code , where?
I am new. Just because changing name of subcatory elements like this
parentId-subcategoryName.

Thanks in advance
Amirianfar

**Comment by Moult** [comment]
I'm not sure what you mean by family subcategory, sorry. IFC does not have the concept of families or subcategories. Do you want to change the predefined type of an IFC product? E.g. set an IfcMember.PredefinedType = STUD?

Perhaps this introductory article can help: https://thinkmoult.com/using-ifcopenshell-parse-ifc-files-python.html

**Comment by Moult** [comment]
Closing bug as IFC4 is indeed well and truly out :)
