### ISSUE TITLE
Simplifying geometric representation of ifc object

### ISSUE THREAD

**Issue by romainhild** [IfcOpenShell/IfcOpenShell#669]
Hi, I have a ifc file with complex objects, such as door handle for example, and I'm trying to simplify it to be able to use finite elements method on it. So my goal is to copy elements of my original file into a new one where doors are transformed into simple cubic forms and windows are transformed into simple surfaces.

For now I manage to create a new file, with the site, project and building from the original file, and to copy a wall into it by using [1] and [2].
But I have two problems:
- how to get local placement of objects right in the new ifc file ?
- is there a way to simplify the geometry when using the `tesselate` function ? maybe by using some tolerance ?

Any help is welcome !

[1] https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/9c6995ab/
[2] http://academy.ifcopenshell.org/wp-content/uploads/2015/07/simple_wall_example.py

I am on debian, I used the build-all script on the v0.6.0 branch and python 3.6.

**Comment by Moult** [comment]
Do you have many complex objects? If not, it might be a good idea to convert it to a mesh, and clean it up using a tool like Blender or Meshlab, which has lots of tools for mesh simplification, which can then be exported into formats for use in finite element analysis.

**Comment by romainhild** [comment]
The problem is that the whole geometry is very big and there is indeed a lot of complex objects. Most of the tools that I used fails to mesh it.
And another idea that we have is to use the materials properties defined inside the ifc for the finite element analysis, so we would like to be able to keep some infos in the output file.

**Comment by Moult** [comment]
The blender plugin does exactly what you are describing, that is, read a brep (from Blender) and create a representation for it. See this portion of code:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/export.py#L1019

In that function it also describes how to export purely curves / wireframe.

I hope the code makes sense. It's been growing quite rapidly and I should start splitting it up.

**Comment by Moult** [comment]
Oh, and thanks to @aothms the IfcOpenShell IFC viewer will now display these pure wireframe / curve representations.

I have tested with many other viewers, and although they do not crash, they do not display the wireframes. I am currently in discussions with some of the vendors to fix this bug.

**Comment by Moult** [comment]
Closing as question answered and tools for writing representations have improved significantly since 2019.
