### ISSUE TITLE
IfcMaterialLayerSet as RelatingMaterial is not supported in layerset slicing

### ISSUE THREAD

**Issue by otsoa** [IfcOpenShell/IfcOpenShell#677]
According to 2x3 schema IfcMaterialLayerSet is a valid option for IfcMaterialSelect . Currently only IfcMaterialLayerSetUsage is supported in layerset slicing. At least Revit 2020 exports extrusion profile roofs like this.
https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/ifcmaterialresource/lexical/ifcmaterialselect.htm

I can provide example files if needed.

**Comment by Moult** [comment]
From the docs:

> In case of assigning the [IfcMaterialLayerSet](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcMaterialLayerSet.htm) directly to an element or element type, the individual layers are stacked according to their position within the list of MaterialLayers **without providing information on how to spatially relate the material layer information to the shape representation of the element or element type**.

So this is as intended.
