### ISSUE TITLE
get list of all ifc types in from an ifc file

### ISSUE THREAD

**Issue by halmsx** [IfcOpenShell/IfcOpenShell#679]
hi

im using 0.5.0-preview2 ifcopenshell-python35

how do i get list of all ifc types used in an ifc file?

thanks in advance.

**Comment by aothms** [comment]
`types()` was added in v0.6.0

for 0.5.0 the only way is to use the bruteforce approach:

~~~
f = ifcopenshell.open(...)
types = set(i.is_a() for i in f)
~~~

**Comment by halmsx** [comment]
great reply! thanks so very much!
