### ISSUE TITLE
Wavefront OBJ serializer outputs low precision

### ISSUE THREAD

**Issue by larsmoa** [IfcOpenShell/IfcOpenShell#68]
In commit 43f5d446ec098b3f6c548753cb475b98ae188266 `WavefrontObjSerializer.cpp` was refactored. One of the changes was to remove line `obj_stream << std::setprecision(std::numeric_limits<double>::digits10);`. This causes the precision of the OBJ files to be too low in certain cases, typically in IFC files with huge offsets or very large coordinates.

**Comment by Stinkfist0** [comment]
Thanks for the catch. This removal was unintentional.

**Comment by aothms** [comment]
Could have also been me messing up the merging at some point, but indeed, thanks for the catch!

**Comment by larsmoa** [comment]
Great, thanks!
