### ISSUE TITLE
What's the difference between geom.iterator and geom.create_shape?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#682]
For the Blender importer, it iterates through `ifcopenshell.geom.iterator(settings, ifc_file)`. I can access the product via `iterator.get().product`. However, how is this different from doing:

```
for e in ifc_file.by_type('IfcElement'):
    shape = ifcopenshell.geom.create_shape(e)
```

One difference I can see is that the geom iterator gives a `.progress()` function, which is nice. I suspect the geom iterator only iterates through geometry, whereas the by_type can iterate through anything - but is there an speed difference between iterating just through the geometry? Will I lose out on optimisations?

What other differences are there? What's the advantage of doing one over the other? I am looking to implement the ability to "selectively" import a file (e.g. only doors on ground floor), but I'm afraid that relying on the geom.iterator() will have limitations, such as if I wanted to import all types which may not have shape representations.

**Comment by aothms** [comment]
Sorry somehow I missed this question. It's a good question that ought to be documented somewhere! I'd say there are three differences:

* Filtering functionality implemented, based on entity attribute, hierarchical (but as you said it might be too limited)
* Ultimately, geometry conversion happens in this IfcGeom::Kernel class in C++. the iterator approach instantiates one kernel for the entire process, which means it can do some caching (for better or worse actually)
* Most importantly it will sort out the IfcMappedItem geometry reuse and process these only once. While taking care of per-product alterations (such as openings, and material assignments).

**Comment by Moult** [comment]
One of the benefits of create_shape is that I can first check the element before passing it to create_shape. This allows me to do something like this:

```
if element.GlobalId == 'foo':
    ifcopenshell.geom.create_shape(element)
```

... or any other filters, like doing `elements = file.by_type('IfcWall')` to only import walls. Doing filters this way is very efficient if we are only interested in certain things, such as IfcSpace for building energy analysis, or IfcFurniture if I'm setting up proxy objects for a CGI render.

However, the only way I'm aware of doing filtering for the geom iterator is by doing something like:

```
should_skip_shape = False
while True:
    if not should_skip_shape:
        shape = iterator.get()
    should_skip_shape = False
    next = iterator.next()
    if not iterator.next():
        break
    if next == ... blah blah blah:
        should_skip_shape = True
```

Is there a better way?

In addition, is there a way to specify, ideally for the iterator (if it is the preferred approach for downstreams to process geometry) to specify which geometric representation contexts / subcontexts to process, or process multiple and know which shape belongs to which context?

**Comment by Moult** [comment]
Just to add, in my little snippet for how to filter the geom iterator, it doesn't seem possible to check the first object. Perhaps I missed something?

**Comment by aothms** [comment]
Also note that this *does* evaluate the full geometry for skipped elements. Something related to the early design decision that we did not want the iterator to return errors.

I prefer not to drastically mess with this iterator class anymore in the 0.6.0 branch. Would it be an option to pass a list of products to be skipped at construction of the iterator?

**Comment by Moult** [comment]
Oh, I thought it evaluated geometry when `get()` is called, that's why in my snippet it checks upon the result of `next()`. 

Passing a list of products to be skipped or included at construction is definitely an option, but what would it look like? At the moment there are two usecases I have: 1) filter by is_a() ifc type, and 2) filter by guid from a list. The filters can either be a blacklist or a whitelist approach. Is that possible without too much mucking around with the iterator?

**Comment by Moult** [comment]
Just checked, you are right, my snippet which attempts to skip elements in the iterator does not work :(

For now, perhaps just being able to do `iterator(settings, ifc_file, whitelist=foo)` or `iterator(settings, ifc_file, blacklist=bar)` would be good solutions, where `foo` and `bar` are a list of IFC GlobalId strings. No need to do by type, as everything can be reduced to IDs :) This would allow me to use the iterator whenever I want to process a filtered subset instead of create_shape!

Related to #748 - I wonder if in a future version someting like `iterator(settings, ifc_file, filter='IfcWall[PredefinedType="PARTITIONING"]')` might be considered, where filter is a string compliant with the IFC selector syntax (whatever flavour it happens to be - just gave a CSS-style example for now). Or similarly, in addition to `by_id()`, `by_guid()`, and `by_type()` there might be `by_filter()`.

**Comment by Moult** [comment]
Would it be possible to do `iterator(settings, ifc_file, filter_callback)`, where `filter_callback` is a python function which gets passed the IFC element, which can then decide whether or not to process it?

This issue cropped up again recently on import of rebar files. Rebar (which is thousands of IfcSweptDiskSolid) is more efficiently parsed by just parsing the profile curve and not converting it into a faceted brep. The modeling package (both FreeCAD and Blender) can handle extruding the circle along the profile, which is almost always what the end-user desires. If somehow the iterator could _just_ get the profile curve, that would be another very, very cool feature.

**Comment by Moult** [comment]
Closing issue as fixed with the new include and exclude features :)
