### ISSUE TITLE
IfcPerson and IfcOrganization has no Identification attribute

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#683]
If `foo` contains an `IfcPerson`, I can do `foo.Id`, but if I do `foo.Identification` I get `AttributeError: entity instance of type 'IfcPerson' has no attribute 'Identification`.

The spec renamed the attribute:

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcperson.htm

**Comment by Moult** [comment]
This applies to `IfcOrganization` too.

**Comment by aothms** [comment]
In 2x3 it's called Id http://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcactorresource/lexical/ifcperson.htm So somehow you're working on an IFC2X3 file :)

**Comment by Moult** [comment]
Ah yes. Of course! Whoops. Thanks!

Closed.

**Comment by Moult** [comment]
Is there a way, after doing ifcopenshell.open('foo.ifc') to check what schema version foo.ifc is?

**Comment by aothms** [comment]
~~~
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> f.schema
'IFC4'
~~~

When creating an empty file there is also a keyword arg to specify the schema, default is IFC4

~~~
>>> g = ifcopenshell.file(schema=f.schema)
~~~

On 0.5 there is only the global

~~~
ifcopenshell.schema_identifier
~~~

**Comment by Moult** [comment]
Thank you :)
