### ISSUE TITLE
Unable to initialize ifcopenshell-python's `geom.iterator` using ifcopenshell 0.6.0b0

### ISSUE THREAD

**Issue by nsaikiran** [IfcOpenShell/IfcOpenShell#684]
Hi,
I'm trying to use latest IfcOpenShell-python. This is downloaded from https://github.com/IfcOpenBot/IfcOpenShell/commit/b4ce5be86d293246dd84f59891e2d5d7f2240284 .

Our sample code is(inspired from IfcBlender):

    settings = ifcopenshell_geom.settings()
    settings.set(settings.DISABLE_OPENING_SUBTRACTIONS, blender_booleans)
    iterator = ifcopenshell_geom.iterator(settings, ifc_file_name)
    valid_file = iterator.initialize()
    if not valid_file:
        return False

    while True:
        ob = iterator.get()

        .... our code goes here ...

        if not iterator.next():
            break

The error we are facing is :
![Screenshot 2019-10-04 at 4 20 44 PM](https://user-images.githubusercontent.com/12473490/66202273-f6319800-e6c2-11e9-9851-a31d5c4a44f4.png)

My platform is macOS 10.14.6 (18G95).
![Screenshot 2019-10-04 at 4 24 31 PM](https://user-images.githubusercontent.com/12473490/66202488-7eb03880-e6c3-11e9-88d3-eb695dfed90b.png)

**Comment by aothms** [comment]
Sorry for the late reply. We probably need to change this back for backwards compatibility but as the error mentions the function prototype was dropped which takes a string. You'll need to `ifcopenshell.open(ifc_file_name)` the file manually now and pass that to the iterator.
