### ISSUE TITLE
Regression: Invalid newline in mtl output (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#685]
1. Convert [685--wall--invalidMaterialFormat--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/685--wall--invalidMaterialFormat--augmented.ifc)  with 32588c63eb39ec3647c6a5be743e7e2e5fdbdd36
2. Experience that the .mtl output has an invalid newline in the name statement:
```
# File generated by IfcOpenShell 0.6.0b0
newmtl surface-style-1269357-no_konstruksjon---isolert(-type-a1,-densitet-min-26-kg/m3
-og-smeltepunkt->-1000-°c))
Kd 0.498039215686275 0.498039215686275 0.498039215686275
Ks 0.5 0.5 0.5
Ns 64
```

**Comment by aothms** [comment]
Hm, indeed, `#1269354=IFCMATERIAL('NO_Konstruksjon - Isolert( type A1, densitet min 26 kg/m3\X4\0000000A\X0\ og smeltepunkt > 1000 \X4\000000B0\X0\C))');` `0x0a` is a newline.

Fixed in f231db0aff88923233097c2d3d4325b4b2472761
