### ISSUE TITLE
How to resolve global location/rotation of object?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#688]
I can get a single object's relative location (and similarly, rotation) via `foo.ObjectPlacement.RelativePlacement.Location`, but the rules required to derive its actual global location require traversing the `PlacementRelTo` tree up to the `IfcProject` level (and, actually, optionally applying a GIS map conversion). Is there a helper function somewhere that does this, or do I need to write my own function?

**Comment by aothms** [comment]
It's really an omission that this is currently not exposed in the Python bindings. I have the following in Python w numpy. Since Blender comes with it's own blenderutils.Matrix math you can rewrite it to use that. Instead of np.dot you can use the `@` operator in python 3.7.

np.eye(4) is equivalent to mathutils.Matrix() for starters. The matrix indexing is a bit unreadable but boils down to getting something that resembles, with x y z the direction vectors and t the translation.

~~~
[ x0  y0  z0  t0 ]
[ x1  y1  z1  t1 ]
[ x2  y2  z2  t2 ]
[  0   0   0   1 ]
~~~

~~~
import ifcopenshell
import ifcopenshell.geom

import numpy as np
import json

S = ifcopenshell.geom.settings() 
S.set(S.USE_WORLD_COORDS, True)

def a2p(o,z,x):
    y = np.cross(z, x) 
    r = np.eye(4) 
    r[:-1,:-1] = x,y,z 
    r[-1,:-1] = o 
    return r.T
    
def axis2placement(plc): 
    z = np.array(plc.Axis.DirectionRatios if plc.Axis else (0,0,1)) 
    x = np.array(plc.RefDirection.DirectionRatios if plc.RefDirection else (1,0,0)) 
    o = plc.Location.Coordinates 
    return a2p(o,z,x) 
    
def local_placement(plc):
    if plc.PlacementRelTo is None: 
        parent = np.eye(4)
    else:
        parent = local_placement(plc.PlacementRelTo)
    return np.dot(axis2placement(plc.RelativePlacement), parent)
~~~

PS I had to copy paste this from a PDF, indentation might be messed up.

**Comment by Moult** [comment]
Thanks @aothms - it's _almost_ there, but not quite. I'm not exactly sure where it goes wrong.

In short, usually I create a shape and then the location in Blender is derived from this matrix:

```
shape = ifcopenshell.geom.create_shape(settings, element)
m = shape.transformation.matrix.data
# ... a little matrix reformatting
```

Because `create_shape` is a rather expensive operation, if two `IfcProduct` shared the same shape representation, I was hoping to only calculate shape once, and then reuse the geometry. This works fine for the geometry itself, but to figure out its position I still needed the data from `shape.transformation.matrix.data`, and that would usually be different for each `IfcProduct`. That's why I asked the above question, hoping I can get the matrix purely by traversing the locations without first having to `create_shape()`. See [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/io_export_ifc/import_ifc.py#L167-L168).

I tried your code, but `m = local_placement(element.ObjectPlacement)` and `m = ifcopenshell.geom.create_shape(settings, element).transformation.matrix.data` seem to not always give the same result (after reformatting the matrix, that is). I'm not sure why - it seems to work on some objects, and not for others. I don't really see the pattern. See [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/io_export_ifc/import_ifc.py#L189-L214).

**Comment by Moult** [comment]
A bit of debugging later, I spot that if the `element.ObjectPlacement` has a `RelativePlacement` of `IfcAxis2Placement3D(#6,$,$)`, where `#6` is basically `(0, 0, 0)`, then `m = local_placement(element.ObjectPlacement)` will give a correct matrix.

If the `element.ObjectPlacement` has an `IfcAxis2Placement3D` of some other translation / rotation axis, then the matrix will be different to that which is returned by `shape.transformation.matrix.data`.

I don't understand why this is, though, since your code looks correct.

**Comment by Moult** [comment]
I've created a minimal test case for this.


[Project1.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3754196/Project1.ifc.txt)
[testcase.py.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3754197/testcase.py.txt)

Results from running testcase:

```
$ python .\testcase.py
Checking element #240=IfcColumn('3VhlTiCLj5LxzlyyxpcfHF',#41,'UC-Universal Columns-Column:UC305x305x97:217191',$,'UC-Universal Columns-Column:UC305x305x97',#238,#229,'217191')
#134=IfcAxis2Placement3D(#6,#19,#132)
[[ 0.93969262  0.34202014  0.          0.        ]
 [-0.34202014  0.93969262  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
#31=IfcAxis2Placement3D(#6,$,$)
[[ 0.93969262  0.34202014  0.          0.        ]
 [-0.34202014  0.93969262  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
#121=IfcAxis2Placement3D(#6,$,$)
[[ 0.93969262  0.34202014  0.          0.        ]
 [-0.34202014  0.93969262  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
#237=IfcAxis2Placement3D(#233,#19,#235)
[[ 1.56434465e-01  9.87688341e-01  0.00000000e+00 -1.52273868e+03]
 [-9.87688341e-01  1.56434465e-01  0.00000000e+00  4.76219771e+03]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Matrices are not the same.
Matrix(((0.15643446147441864, 0.9876883625984192, 0.0, 0.19786123931407928),
        (-0.9876883625984192, 0.15643446147441864, 0.0, 4.995809555053711),
        (0.0, 0.0, 1.0, 0.0),
        (0.0, 0.0, 0.0, 1.0)))
Matrix(((0.15643446147441864, 0.9876883625984192, 0.0, -1.5227386951446533),
        (-0.9876883625984192, 0.15643446147441864, 0.0, 4.762197494506836),
        (0.0, 0.0, 1.0, 0.0),
        (0.0, 0.0, 0.0, 1.0)))
Checking element #286=IfcColumn('3VhlTiCLj5LxzlyyxpcfHI',#41,'UC-Universal Columns-Column:UC305x305x97:217210',$,'UC-Universal Columns-Column:UC305x305x97',#285,#278,'217210')
#134=IfcAxis2Placement3D(#6,#19,#132)
[[ 0.93969262  0.34202014  0.          0.        ]
 [-0.34202014  0.93969262  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
#31=IfcAxis2Placement3D(#6,$,$)
[[ 0.93969262  0.34202014  0.          0.        ]
 [-0.34202014  0.93969262  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
#121=IfcAxis2Placement3D(#6,$,$)
[[ 0.93969262  0.34202014  0.          0.        ]
 [-0.34202014  0.93969262  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
#284=IfcAxis2Placement3D(#6,$,$)
[[ 0.93969262  0.34202014  0.          0.        ]
 [-0.34202014  0.93969262  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
Same matrix.
```

**Comment by Moult** [comment]
Fixed.

I think the order should be `return parent @ get_axis2placement(plc.RelativePlacement)` not `return get_axis2placement(plc.RelativePlacement) @ parent`

Awesome! Thanks @aothms ! This now speeds up imports of large files significantly!
