### ISSUE TITLE
Can not init Geom's settings

### ISSUE THREAD

**Issue by whsqjss** [IfcOpenShell/IfcOpenShell#689]
When I execute these:
  ```
  from Ifcopenshell import geom
  geom.settings()
```
It raise the error
` AttributeError: 'settings' object has no attribute 'convert_back_units'`

AnyBody knows the reason?

**Comment by aothms** [comment]
What version is this? Why is `ifcopenshell` with a capital I? Can you explain where you got the module or what's in the module directory?

**Comment by whsqjss** [comment]
Sorry, I make a mistake in writing `ifcopenshell `  by 'Ifcopenshell'
I got this module by clone lastest source code and compile it on Windows x64.

**Comment by aothms** [comment]
and how did you assemble the complete module? you need the files in ifcopenshell-python directory in the repo, the generated ifcopenshell_wrapper.py from swig and the compiled ifcopenshell_wrapper.pyd.

**Comment by whsqjss** [comment]
here is the files in my python34 repo
![ifcopenshell](https://user-images.githubusercontent.com/35548533/66553442-b57fc600-eb7d-11e9-8db8-c1797e3e35e3.jpg)

**Comment by aothms** [comment]
Sorry for the late reply. Actually it seems I get the same behaviour on your usage.

But the import without `from` works flawlessly. I hadn't imagined there would be a difference between these two modes in Python. But stick to the 2nd way then.

~~~
>>> import ifcopenshell
>>> from ifcopenshell import geom
>>> geom.settings()
...
AttributeError: 'settings' object has no attribute 'convert_back_units'
>>>
>>> import ifcopenshell.geom
>>> s = ifcopenshell.geom.settings()
~~~

**Comment by whsqjss** [comment]
Thank you very much for your help
