### ISSUE TITLE
Incomplete opening subtractions from Archicad 21 (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#690]
1. Convert [690--wall--incomplete-subtractions--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/690--wall--incomplete-subtractions--augmented.ifc) with 0.6.0
2. Experience that the wall looks massive from the front on one of the window openings, but not the other:
![Oct-11-2019 14-33-52](https://user-images.githubusercontent.com/4601554/66651777-31d4e080-ec34-11e9-874d-8a5b2f74ec1b.gif)

3. Convert the same file without the opening between the windows (#1245595), and experience that the window openings themselves are applied correctly:
<img width="338" alt="Screenshot 2019-10-11 at 14 31 19" src="https://user-images.githubusercontent.com/4601554/66651643-d3a7fd80-ec33-11e9-921d-88ee7014292a.png">

It seems like such a combination of three openings side-by-side cause problems. This is a very frequent issue with exports from Archicad 21, thus a quite high-priority issue.

(the subtractions are applied correctly when lowering the modelling precision from 1.E-5 to 1.E-1 mm, so that may indicate that there is something going on with the order and combination of subtractions when they are close)

**Comment by johanrd** [comment]
Curiously, when converting with 0.5.0, it is the other opening that is blocked:
![Oct-11-2019 15-16-58](https://user-images.githubusercontent.com/4601554/66654352-4fa54400-ec3a-11e9-81ce-b949a4353d95.gif)

**Comment by aothms** [comment]
It's a rather interesting configuration of openings again. 5 boxes distributed over 3 opening elements.

![afbeelding](https://user-images.githubusercontent.com/1096535/66826563-006a5680-ef4d-11e9-8faa-df866fcc07ca.png)

It's actually surprisingly hard to detect this invalid result. The only thing I managed to do was increase the face-face distance check threshold to some arbitrary value.

503029733c7beff4b191167d50ca35b726c6abc7

**Comment by johanrd** [comment]
Thanks, I can verify that 5030297 fixes this🎉Closing. 

(the complex opening definitions are also reported to Archicad – let's hope they can simplify for future releases)
