### ISSUE TITLE
Move Dockerfiles into this repo

### ISSUE THREAD

**Issue by FreakTheMighty** [IfcOpenShell/IfcOpenShell#691]
I would like to see the Dockerfiles from [IfcOpenShell/Dockerfile](https://github.com/IfcOpenShell/Dockerfile) to be brought into this repo. This would allow us to setup automated builds on Dockerhub.

I started work on this a while back, but got stuck on build issues. I may give it another try, but wanted to capture the request here.

**Comment by aothms** [comment]
I would be totally open to that, but we probably need to figure out sensible defaults for some of the options: base image, shared/static libs, occt version, package manager / everything from source, components IfcConvert python ..., compiler flags debug release sse ... Do you have opinions?

Another approach probably would be to keep (multiple options of) Dockerfile in a separate repo and create submodules of the IfcOpenShell source within them.

**Comment by FreakTheMighty** [comment]
I’m not that familiar with the options we would want to support. My personal needs are around IfcConvert. 

With that said, multiple configuration can be supported by using multiple Dockerfiles. Automated builds allow you to specify which directory to look for the file. This is the way your current repo is structured.

I would also put a docket-compose at the root of the repo to make local building super east.

**Comment by FreakTheMighty** [comment]
@aothms, what do you think about picking a single base image? ATM, there's an image for ubuntu, debian, and fedora. I think choosing one would make it easier to maintain. The `ubuntu` image currently is the most downloaded on Docker Hub, but I think we could pick any of them.

**Comment by aothms** [comment]
I agree.

I usually do something like this:

~~~
WORKDIR /
RUN apt-get -y update && apt-get -y install autoconf bison build-essential git make wget python bzip2 libfreetype6-dev mesa-common-dev libgl1-mesa-dev python-pip libftgl-dev cmake unzip libffi-dev
RUN git clone https://github.com/IfcOpenShell/IfcOpenShell.git && cd IfcOpenShell && git checkout v0.6.0
WORKDIR /IfcOpenShell/nix
RUN CXXFLAGS="-O3" BUILD_CFG=Release python build-all.py IfcConvert
~~~

Note that the build will take several hours. `-march=native` can be added to CXXFLAGS to make the executable more performant but tied to the processor architecture used for building.

It takes several GBs of data to build.  So multi staged builds should probably be used to eliminate that in the final image.

**Comment by FreakTheMighty** [comment]
I don't understand what you mean by multi-stage builds. My current docker file looks like this, based on the old Dockerfiles and the build instructions in the README.  Note, we'd remove the `git clone`, as these builds would be happening from within the current repository. This would allow us to setup builds based on tags and branches.

```
FROM ubuntu:16.04

MAINTAINER yilativs@gmail.com

ENV REFRESHED_AT 2015-03-03

RUN apt-get -y update && \
    apt-get -y install git swig cmake gcc g++ libftgl-dev libtbb2 libtbb-dev libboost-all-dev libgl1-mesa-dev libfreetype6-dev liboce-modeling-dev opencollada-dev liboce-foundation-dev libpcre3-dev && \
    rm -rf /var/lib/apt/lists/*

COPY . /opt/sources/ifcopenshell

WORKDIR /opt/sources/ifcopenshell

RUN mkdir build && cd build && \
    cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ \
      -DOPENCOLLADA_INCLUDE_DIR="/usr/include/opencollada" \
      -DOPENCOLLADA_LIBRARY_DIR="/usr/lib/opencollada"  \
      -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ && \
    make -j
```

**Comment by aothms** [comment]
> I don't understand what you mean by multi-stage builds

That's a recent docker feature https://docs.docker.com/develop/develop-images/multistage-build/ that enables you to build in a 'temporary' image and only copy some of the resulting files into the final image to reduce image size.

> `liboce-modeling-dev`

That's the Open CASCADE Community Edition, which is rather old. If using the approach of the package manager, we better switch to the ppa maintained by @kkremitzki at https://launchpad.net/~freecad-community/+archive/ubuntu/ppa

**Comment by FreakTheMighty** [comment]
@aahoo funny, I read about multi-stage builds for the first time yesterday. That sounds like a plan.

**Comment by FreakTheMighty** [comment]
Aah, I see now that `build-all.py` also installs the required dependencies. I think that's a great way of managing things. I've just embarked on this many hour build.

One thing that occurs to me is that it would be helpful to have a `install-deps` distinct from `build-all.py`. This would allow us to cache the results. As it is now, the docker image will need to rebuild all the dependencies even if none have changed. A separate script would allow us to do something like

```
COPY ./nix/install-deps.py /opt/sources/ifcopenshell/nix/
RUN python /opt/sources/ifcopenshell/nix/install-deps.py
COPY . /opt/sources/ifcopenshell
RUN python build-all.py
```
By going in this order, the dependencies cache is only invalidated when the install-deps.py script changes.

**Comment by Moult** [comment]
Is that dockerfile repo still relevant? Can it be deleted and this closed as the `cd` github action pushes to Docker?

**Comment by aothms** [comment]
We have automated builds now using github actions. So this can be closed
and the Dockerfile repo should probably be deleted or archived

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op vr 2 sep. 2022 07:38 schreef Dion Moult ***@***.***>:

**Comment by Moult** [comment]
Archived for now :) Feel free to delete if needed.
