### ISSUE TITLE
Timeout on boiler (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#695]
1. Convert [695--boiler--timeout.ifc_](https://github.com/IfcOpenShell/files/blob/master/695--boiler--timeout.ifc_) and experience that the conversion never finishes.
2. Expected geometry from Solibri:
<img width="250" alt="Screenshot 2019-10-17 at 14 58 57" src="https://user-images.githubusercontent.com/4601554/67010919-e36d8900-f0ee-11e9-80d1-5319d4954fe2.png">

**Comment by johanrd** [comment]
Update: All commits I've tried on the 0.6.0 branch result in timeout, however converting with IfcOpenshell 0.5.0 (OCCT 7.3.0) does not timeout:
```
IfcOpenShell IFC4 IfcConvert 0.5.0-dev (OCC 7.3.0)
Scanning file...
Done scanning file   
Creating geometry...
Done creating geometry (1 objects)                                
Conversion took 52 seconds
Done.
```

**Comment by aothms** [comment]
Thanks for this and the other files @johanrd I'll try to have a look asap. End of this week probably.

**Comment by Moult** [comment]
Confirming that this is now fixed.
