### ISSUE TITLE
Latest version of IFCconvert

### ISSUE THREAD

**Issue by Oskutin** [IfcOpenShell/IfcOpenShell#696]
Hey, 

I've been trying to compile the latest version of IFCConvert for Windows by following the tutorial in readme.md, but build-deps.cmd constantly keeps ending into this issue:  #400 ,regardless of any visual studio version (2015 and 2017) i tried, admin priviliges, intallation folder...

Attempts with MSYS2 end in error2 with the build-deps.sh.

Can anybody provide me downloadable windows version of the IFCconvert.exe with version higher than 0.6.0?

Alternatively, can I convert .ifcfiles to .dae with hierachy with Anaconda IFCOpenShell package?

**Comment by aothms** [comment]
> Attempts with MSYS2 end in error2 with the build-deps.sh.

Hm yeah the MSYS2 setup is perhaps not the most up to date.

> keeps ending into this issue: #400 

I never understood what causes that issue. I don't mind to work on it more, but I do need to be able to reproduce it. One thing I just noticed was the command is referenced as `utils\cecho.cmd`. Not a windows .bat script expert but that probably means the current directory needs to be the `win` folder. Is that the case?

> version higher than 0.6.0

I think the latest is https://github.com/IfcOpenBot/IfcOpenShell/commit/b4ce5be86d293246dd84f59891e2d5d7f2240284#comments What do you need?

> Alternatively, can I convert .ifcfiles to .dae with hierachy with Anaconda IFCOpenShell package?

Previously the serializers where defined inside the IfcConvert executable, now they're in a separate library, but they are unfortunately still not accessible from Python.

**Comment by Moult** [comment]
Closing as there are now a variety of channels where IfcConvert can be installed from https://blenderbim.org/docs-python/ifcconvert/installation.html
