### ISSUE TITLE
Convert ifc file to svg floor plans

### ISSUE THREAD

**Issue by joyjo** [IfcOpenShell/IfcOpenShell#697]
Hello,
I'd like to export 2D floor plans from ifc but I'm getting this result.

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
</svg>
`
here is my ifc file

`ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('inp.ifc','2019-10-21T04:45:52',('Joyjo'),('jjjj'),'IfcOpenShell','IfcOpenShell','');
FILE_SCHEMA(('IFC2X3'));
ENDSEC;
DATA;
#1=IFCPERSON($,$,'JoyJo',$,$,$,$,$);
#2=IFCORGANIZATION($,'jjjj',$,$,$);
#3=IFCPERSONANDORGANIZATION(#1,#2,$);
#4=IFCAPPLICATION(#2,'0.6','IfcOpenShell','');
#5=IFCOWNERHISTORY(#3,#4,$,.ADDED.,$,#3,#4,1571633152.4152875);
#6=IFCDIRECTION((1.,0.,0.));
#7=IFCDIRECTION((0.,0.,1.));
#8=IFCCARTESIANPOINT((0.,0.,0.));
#9=IFCAXIS2PLACEMENT3D(#8,#7,#6);
#10=IFCDIRECTION((0.,1.,0.));
#11=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#9,#10);
#12=IFCDIMENSIONALEXPONENTS(0,0,0,0,0,0,0);
#13=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#14=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#15=IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
#16=IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.);
#17=IFCMEASUREWITHUNIT(IFCPLANEANGLEMEASURE(0.017453292519943295),#16);
#18=IFCCONVERSIONBASEDUNIT(#12,.PLANEANGLEUNIT.,'DEGREE',#17);
#19=IFCUNITASSIGNMENT((#13,#14,#15,#18));
#20=IFCPROJECT('2fBXUSyxqHwPff5zzKiCTu',#5,'jjjj',$,$,$,$,(#11),#19);
#21=IFCCARTESIANPOINT((0.,0.,0.));
#22=IFCDIRECTION((0.,0.,1.));
#23=IFCDIRECTION((1.,0.,0.));
#24=IFCAXIS2PLACEMENT3D(#21,#22,#23);
#25=IFCLOCALPLACEMENT($,#24);
#26=IFCSITE('2fBgaoyxqHwPff5zzKiCTu',#5,'Site',$,$,#25,$,$,.ELEMENT.,$,$,$,$,$);
#27=IFCCARTESIANPOINT((0.,0.,0.));
#28=IFCDIRECTION((0.,0.,1.));
#29=IFCDIRECTION((1.,0.,0.));
#30=IFCAXIS2PLACEMENT3D(#27,#28,#29);
#31=IFCLOCALPLACEMENT(#25,#30);
#32=IFCBUILDING('2fBhJCyxqHwPff5zzKiCTu',#5,'Building',$,$,#31,$,$,.ELEMENT.,$,$,$);
#33=IFCCARTESIANPOINT((0.,0.,0.));
#34=IFCDIRECTION((0.,0.,1.));
#35=IFCDIRECTION((1.,0.,0.));
#36=IFCAXIS2PLACEMENT3D(#33,#34,#35);
#37=IFCLOCALPLACEMENT(#31,#36);
#38=IFCBUILDINGSTOREY('2fBhn_yxqHwPff5zzKiCTu',#5,'Storey',$,$,#37,$,$,.ELEMENT.,0.);
#39=IFCRELAGGREGATES('2fBh$GyxqHwPff5zzKiCTu',#5,'Building Container',$,#32,(#38));
#40=IFCRELAGGREGATES('2fBiB8yxqHwPff5zzKiCTu',#5,'Site Container',$,#26,(#32));
#41=IFCRELAGGREGATES('2fBiMEyxqHwPff5zzKiCTu',#5,'Project Container',$,#20,(#26));
#42=IFCCARTESIANPOINT((0.,0.,0.));
#43=IFCDIRECTION((0.,0.,1.));
#44=IFCDIRECTION((1.,0.,0.));
#45=IFCAXIS2PLACEMENT3D(#42,#43,#44);
#46=IFCLOCALPLACEMENT(#37,#45);
#47=IFCCARTESIANPOINT((0.5,0.14,0.));
#48=IFCCARTESIANPOINT((12.58,0.,0.));
#49=IFCPOLYLINE((#47,#48));
#50=IFCSHAPEREPRESENTATION(#11,'Axis','Curve2D',(#49));
#51=IFCCARTESIANPOINT((0.5,0.14,0.));
#52=IFCDIRECTION((0.,0.,1.));
#53=IFCDIRECTION((0.,1.,0.));
#54=IFCAXIS2PLACEMENT3D(#51,#52,#53);
#55=IFCCARTESIANPOINT((0.,-0.25,0.));
#56=IFCCARTESIANPOINT((12.58,-0.25,0.));
#57=IFCCARTESIANPOINT((12.58,0.25,0.));
#58=IFCCARTESIANPOINT((0.,0.25,0.));
#59=IFCCARTESIANPOINT((0.,-0.25,0.));
#60=IFCPOLYLINE((#55,#56,#57,#58,#59));
#61=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,$,#60);
#62=IFCDIRECTION((0.,0.,1.));
#63=IFCEXTRUDEDAREASOLID(#61,#54,#62,2.);
#64=IFCSHAPEREPRESENTATION(#11,'Body','SweptSolid',(#63));
#65=IFCPRODUCTDEFINITIONSHAPE($,$,(#50,#64));
#66=IFCWALLSTANDARDCASE('2fBkJiyxqHwPff5zzKiCTu',#5,'Wall','An awesome wall',$,#46,#65,$);
#67=IFCQUANTITYLENGTH('Length','Length of the wall',$,12.58);
#68=IFCQUANTITYAREA('Area','Area of the front face',$,25.16);
#69=IFCQUANTITYVOLUME('Volume','Volume of the wall',$,12.58);
#70=IFCELEMENTQUANTITY('2fBkqqyxqHwPff5zzKiCTu',#5,'BaseQuantities',$,$,(#67,#68,#69));
#71=IFCRELDEFINESBYPROPERTIES('2fBl0iyxqHwPff5zzKiCTu',#5,$,$,(#66),#70);
#72=IFCMATERIAL('wall material');
#73=IFCMATERIALLAYER(#72,0.5,$);
#74=IFCMATERIALLAYERSET((#73),$);
#75=IFCMATERIALLAYERSETUSAGE(#74,.AXIS2.,.POSITIVE.,-0.1);
#76=IFCRELASSOCIATESMATERIAL('2fBlUiyxqHwPff5zzKiCTu',#5,$,$,(#66),#75);
#77=IFCPROPERTYSINGLEVALUE('Reference','Reference',IFCTEXT('Describe the Reference'),$);
#78=IFCPROPERTYSINGLEVALUE('IsExternal','IsExternal',IFCBOOLEAN(.T.),$);
#79=IFCPROPERTYSINGLEVALUE('ThermalTransmittance','ThermalTransmittance',IFCREAL(2.569),$);
#80=IFCPROPERTYSINGLEVALUE('IntValue','IntValue',IFCINTEGER(2),$);
#81=IFCPROPERTYSET('2fBm5SyxqHwPff5zzKiCTu',#5,'Pset_WallCommon',$,(#77,#78,#79,#80));
#82=IFCRELDEFINESBYPROPERTIES('2fBmGsyxqHwPff5zzKiCTu',#5,$,$,(#66),#81);
ENDSEC;
END-ISO-10303-21;
`

using ifcopenshell 0.6.0b0

thank you

**Comment by joyjo** [comment]
solved,

i forgot this line
`ifcfile.createIfcRelContainedInSpatialStructure(create_guid(), owner_history, "Building Storey Container", None, [wall], building_storey)`

**Comment by aothms** [comment]
Yes currently the SVG generation is very much based on relationships to the buildingstorey but we might change that at some point.

**Comment by Abhicode5** [comment]
Hi @joyjo 
I also want to convert ifc to svg format using ifcopenshell . But i dont know much about ifcOpenshell . Could you please help 
me how to convert ifc to svg file format. 
Could you please share me the code that will help me

Thanks

**Comment by jlph92** [comment]
You can try ifctoolbox from microsoft store. It is build on top of xBIM and IfcOpenShell.
