### ISSUE TITLE
powershell version 5 or higher required

### ISSUE THREAD

**Issue by dalihao** [IfcOpenShell/IfcOpenShell#698]
Some computer can not download Windows Management correctly,because of windows update.I find a method to download powershell skip this.But cmd can not find the power shell 6.2.3.And I modify build-deps.cmd,89line powershell to pwsh.because of powershell/6/pwsh,not powershell.And then there is some errors.I saw someone solved the problem by this way.Is there anyone did the same method as me?could you please give me a help,thanks.

**Comment by aothms** [comment]
> And then there is some errors

Which is?

Otherwise you're not required to use the build scripts. You can compile the dependencies manually as well. Or download e.g. the precompiled Open CASCADE package from their website.

**Comment by Moult** [comment]
@dalihao bump :) A little ping that you can find install instructions for Windows here: https://blenderbim.org/docs-python/ifcopenshell/installation.html - if you're still having issues let us know perhaps with screenshots or error messages that you are facing so we can help.

If no response this bug will be closed in a week.
