### ISSUE TITLE
UTF-8 issues making a written file unreadable bu IFC software (f.ex Solibri)

### ISSUE THREAD

**Issue by Tmagga** [IfcOpenShell/IfcOpenShell#699]
I have an issue with editing an IFC file with IfcOpenShell.
If the file contains an character from f.ex the skandinavian alphabet (æ ø å) it reads it just fine, but writes it differently and the file becomes unreadable.

Read parameter (unicode = D\X2\00F8\X0\r = Dør) :
`2921= IFCBUILDINGELEMENTPROXYTYPE('3QPADpsq71CHeCe7e3GDm5',#32,'D\X2\00F8\X0\r',$,$,$,$,'DA64A373-DB41-C131-1A0C-A07A0340DC05',$,.NOTDEFINED.);`

Its Printed as Dør so it decodes it fine.

It writes the same element as 
`2921=IFCBUILDINGELEMENTPROXYTYPE('3QPADpsq71CHeCe7e3GDm5',#32,'D\X4\000000F8\X0\r',$,$,$,$,'DA64A373-DB41-C131-1A0C-A07A0340DC05',$,.NOTDEFINED.);`

word is "Dør"
so the read vs written is ; `'D\X2\00F8\X0\r'` vs `'D\X4\000000F8\X0\r'`
the written is unreadable for the IFC software i've tried and makes the .ifc file "corrupt"

i've tried this to sort this out, but my skills with coding just isnt good enough yet and the workaround i used was to convert the values i added to the file. Open the same .ifc file as txt, then pasted the old file ontop, so that i had the "old" file with the new additions.
This however does not work when trying to change exsisting values. 

Any suggestions? i'm loosing my hair over this....

**Comment by aothms** [comment]
Ultimately the `X2` encoding is just as valid as the `X4` encoding and I'm tempted to believe the issue is elsewhere.

It's indeed possible to make IfcOpenShell select `X2` where possible. Something like seeing `std::max_element()` of the string is greater than 0xffff should be enough to determine this for the entire string.

**Comment by Tmagga** [comment]
I found that " std::max_element()" in a comment elsewhere, but does that work for python? I'm using python 3.5.
My reason for strongly beliving that its related to the \X4\ is that while troubleshooting i did the following
`import ifcopenshell
file = 'Dummy_Model_test.ifc'
ifcfile = ifcopenshell.open(file)
newfile = file.replace('.ifc','_new.ifc')
print (newfile)
ifcfile.write(newfile)
`

Here the file doesnt get the same error, but it doesnt read it correctly either.
From original file :
#115= IFCBUILDING('0r2vuadh92ZfSDFx7ipIca',#41,'\X\C5s',$,$,#32,$,'',.ELEMENT.,$,$,$);
\X\C5s = 'Ås'   <-- Correct
From new file:
#115=IFCBUILDING('0r2vuadh92ZfSDFx7ipIca',#41,'\X4\000000C5\X0\s',$,$,#32,$,'',.ELEMENT.,$,$,$);
'\X4\000000C5\X0\s' = 'b' (in this case) and is wrong. I do agree taht it looks valid though. Maybe the softwares used dont do 32 bit? i dont know.

Picture of Models in Solibri attached:

![7e573bed-3c7d-4656-831f-dcbe4e981cb1](https://user-images.githubusercontent.com/50455111/67853528-05afcf80-fb0f-11e9-8fd7-62f2189362b9.jpg)

**Comment by Tmagga** [comment]
After having a talk with a programmer, telling her about the issue, she came to the conclusion that the software used to read the ifc files dont accept X4, but do accept X and X2. 16 bit is all they accept it seems, and that  would explain " Error! Index error out of range :17"

**Comment by Tmagga** [comment]
I did make a workaround converting all X4 to X2 after writing the ifc file wth ifcopenshell. Needs some testing before concluding though.

**Comment by aothms** [comment]
Added some code for this. Are you familiar with compiling yourself to test?

**Comment by Tmagga** [comment]
I'm afraid i'm not familiar with compiling, no.

**Comment by Moult** [comment]
Tested and seems to work on my end now.
