### ISSUE TITLE
Lack of colors in version 5

### ISSUE THREAD

**Issue by klokoy** [IfcOpenShell/IfcOpenShell#7]
IfcConvert v5 has a lot less colors than in v4.  Is there a way to fix this? And if I include space they are not transparent, as they are in v4.

version 4
![screen shot 2015-11-18 at 11 05 43](https://cloud.githubusercontent.com/assets/973082/11238211/60634d4a-8de4-11e5-8a6b-40e0c78b15cd.png)
version 5
![screen shot 2015-11-18 at 11 05 28](https://cloud.githubusercontent.com/assets/973082/11238210/6061259c-8de4-11e5-857f-16722e05d1d6.png)

**Comment by Stinkfist0** [comment]
The gray space is blocking the house? If you move the space away does the house look as it used to be?

**Comment by klokoy** [comment]
No, here is a shot from version 5 without spaces.  
Windows are transparent as expected.

![screen shot 2015-11-18 at 14 09 53](https://cloud.githubusercontent.com/assets/973082/11241829/228f7eb6-8dfe-11e5-8cb2-2f1ecfc9c11a.png)

**Comment by Stinkfist0** [comment]
OK. For me the model seems fine when converted to obj or dae.
![image](https://cloud.githubusercontent.com/assets/227876/11241937/66abd08c-8e07-11e5-9740-61491eb246c7.png)

**Comment by aothms** [comment]
For me as well. Is this something specific to your importing application? Can the output be improved to be better understood by a wider set of applications? Otherwise, closing the issue.

Kind regards,
Thomas

**Comment by klokoy** [comment]
It sems to be a problem with the quickview in osx. When we take the collada further in the pipeline the final output is fine.
