### ISSUE TITLE
AttributeError: type object 'object' has no attribute '__getattr__' when using geom.settings()

### ISSUE THREAD

**Issue by jappoz** [IfcOpenShell/IfcOpenShell#715]
Hi, 
I am using IfcOpenShell with python. 
I do not know why I am getting this error 
```
AttributeError: type object 'object' has no attribute '__getattr__'
```
every time I try to set the settings.

The code that generates that error is very simple:
```python
import ifcopenshell
from ifcopenshell import geom
settings = ifcopenshell.geom.settings()
settings.set(settings.USE_PYTHON_OPENCASCADE, True)
```

Is anyone else getting this error? I tried to recompile IfcOpenshell but nothing changed...

**Comment by aothms** [comment]
It's not as obvious as it should be, but this happens when you do not have pythonOCC installed. So `import OCC` will also fail.

**Comment by jappoz** [comment]
Thank you for your quick answer.
Anyway I am actually able to import OCC (import OCC does not give me any error) and I have instead installed it after compiling it from scratch. When I build IfcOpenshell I see as well cmake finding the correct paths...

**Comment by aothms** [comment]
Ok, this is actually dependent on `OCC.BRepTools`. Does that import also succeed?

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/geom/main.py#L32

Otherwise, what version of IfcOpenShell are you using?

**Comment by jappoz** [comment]
I see. 
That import gives me this error:
`ImportError: libTKBRep.so.11: cannot open shared object file: No such file or directory`

I cloned the master branch from this repo, not sure which version actually is.

It looks like I am missing that libTKBRep library

**Comment by aothms** [comment]
Right, pythonOCC depends on Open CASCADE Community Edition and it can't find those libraries at runtime. They are probably there because you compiled successfully. Not sure how you set this all up, but it's not an IfcOpenShell issue at least.

**Comment by jappoz** [comment]
Yes! 
In fact is an issue related to OCE. 
For those who might concern, I post the link of the
