### ISSUE TITLE
IfcOpenShell viewer (geom iterator) creates the same geometry for a flipped shape representation

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#724]
The attached file should look like this:

![2019-11-17-203712_420x279_scrot](https://user-images.githubusercontent.com/88302/69005707-1323e100-097a-11ea-9565-c094d0bc4c8d.png)

I have confirmed that this result is achieved with other IFC viewers like XBim.

But I think the geometry iterator only creates one representation. As a result, I only see one pyramid as shown here:

![2019-11-17-203913_294x216_scrot](https://user-images.githubusercontent.com/88302/69005732-51b99b80-097a-11ea-9447-231d187a588a.png)

[test.blend.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3855438/test.blend.ifc.txt)

**Comment by aothms** [comment]
You're using your representation in a product def and in a representation map. This is not allowed.

~~~
WR11 : (SIZEOF(SELF\IfcRepresentation.OfProductRepresentation) = 1) XOR
(SIZEOF(SELF\IfcRepresentation.RepresentationMap) = 1) XOR
(SIZEOF(OfShapeAspect) = 1);
~~~

> WR11: The IfcShapeModel shall be used by an IfcProductRepresentation, by an IfcRepresentationMap or by an IfcShapeAspect.

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcrepresentationresource/lexical/ifcshapemodel.htm

Admittedly though we should emit a warning for this.

**Comment by Moult** [comment]
Aha, so if I read that correctly, a shape representation cannot be used in multiple ifc product defs? Is there a warning for that one too?

**Comment by aothms** [comment]
I guess so, although that would not affect IfcOpenShell's functioning (I think). Added more warnings.

**Comment by Moult** [comment]
I see. I seem to have broken this rule in BlenderBIM :) I will add it to the list of things to fix! Thanks!
