### ISSUE TITLE
Unicode characters in IfcConvert's XML output

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#73]
I think something has changed during the past year or so regarding IfcConvert's Unicode handling. In some older files generated by IfcConvert e.g. `J\X2\00E4\X0\tehuone` in IFC file has resulted in `J\u00e4tehuone` in XML. However, in more recent XML files I'm seeing `Jätehuone`. Any ideas what might have changed? How does these behave for you other users?

**Comment by aothms** [comment]
The default encoder has changed during that time: https://github.com/IfcOpenShell/IfcOpenShell/commit/a58b2ede63e927b6e28afb58d508bebcb5d98728#diff-2
I think UTF-8 is a more natural default than this escaped unicode notation.

**Comment by Stinkfist0** [comment]
OK, agreed in general it's better to have them human-readable straight away, although the escaped notation was more handy for my further processing. But I can escape these on my own no problem.

**Comment by aothms** [comment]
Well, feel free to create a command line option. I'm sure there are others as well that prefer their output to be ASCII-safe.

**Comment by Stinkfist0** [comment]
Yeah, command-line option could be nice.

**Comment by Stinkfist0** [comment]
If/when this is made an option, it would be nice that the behavior would be consistent for all IfcConvert's output formats (XML, DAE, SVG, etc.), possible restrictions applied.

**Comment by iras** [comment]
A command line option is a great idea. Tripped up by the line below:

`#11= IFCSURFACESTYLE('\X2\00C70130\X0\ZG\X2\0130\X0\-RRR',.BOTH.,(#10));`

**Comment by Stinkfist0** [comment]
@aothms Doing this now. Do you have preferences what the command-line argument would be called?

**Comment by aothms** [comment]
Well, maybe we need to think for a second what the meaningful options are, e.g. for the input `J\X2\00E4\X0\tehuone`. I can think of:

- `J\X2\00E4\X0\tehuone` (verbatim IFC)
- `J\u00e4tehuone` (old behaviour)
- `Jätehuone` (current behaviour when compiled with ICU)
- `J_tehuone` (current behaviour when compiled without ICU)
- `Jatehuone` (not sure if this is meaningful, Americans might think so, maybe Finnish people would disagree?) [[1](http://stackoverflow.com/questions/2992066/code-to-strip-diacritical-marks-using-icu#answer-13071166), [2](https://github.com/andrewrk/node-diacritics/blob/master/index.js)]

If these are all meaningful, perhaps something like the following: `--unicode=step|escape|utf8|substitute|fold`?

Anyway, in this way, this is getting more into a feature request than an issue. I can take care of the first and last (i.e the ones that require extra work) if it is beyond what you were trying to accomplish.

[1] http://stackoverflow.com/questions/2992066/code-to-strip-diacritical-marks-using-icu#answer-13071166
[2] https://github.com/andrewrk/node-diacritics/blob/master/index.js

**Comment by Stinkfist0** [comment]
OK, no objection for multiple choices, was simply going initially for a switch that would've used the old format. Personally I don't find the last option useful as e.g. 'a' and 'ä' are totally different characters.

**Comment by aothms** [comment]
Actually I agree. Anyway that last option doesn't solve anything as there are still many characters for which no folding rule can be given and would need to be encoded in any of the other options.

**Comment by Stinkfist0** [comment]
@aothms So - I should we proceed with this? Do you take over or should begin working with this?

**Comment by aothms** [comment]
I assumed you started working on it from your earlier comment, but I am fine with both. Atm I am occupied with https://github.com/IfcOpenShell/IfcOpenShell/issues/59, I can do this afterwards. I don't think it is particularly difficult, probably it is easiest though to do this somewhere on the `IfcGeom::Element`s so that it works independently of the serializer?

I am planning to wrap up the 0.5.0 tickets soon, so that we can move forward. Given the unclarity around OCCT 7 I didn't feel a lot of time pressure for some time, but now things are more clear, I prefer to push things out soon. So any help is appreciated :)

**Comment by Stinkfist0** [comment]
For now I simply did a simple hack/solution (basically `if ("--no-unicode-decoding") IfcCharacterDecoder::mode = IfcCharacterDecoder::JSON;`). I can start looking into more comprehensive solution soon.

**Comment by Stinkfist0** [comment]
FYI, got caught up with some other work and this task is still pending. I plan to start working with this and another batch of IfcConvert enhancements next week.

**Comment by aothms** [comment]
Sounds good. No worries on the delay, I haven't really been able to invest significant time into IfcOpenShell myself either lately unfortunately.

**Comment by Stinkfist0** [comment]
OK, `--unicode=escape|utf8` is straightforward, but how about `substitute`? Should I add a new value, `SUBSTITUTE` to `IfcCharacterDecoder::ConversionMode` for this behavior?

**Comment by Stinkfist0** [comment]
@aothms ping ^

**Comment by aothms** [comment]
Ah I see, `substitute` is the default behaviour when compiled without ICU, there is currently no mode for that in the enumeration. Frankly I don't have too strong of an opinion, if takes too much effort to fight your way around the current `#ifdef` structure feel free to leave it out. Since nobody asked for that behaviour, I guess we are all unicode aware these days. If it is useful to you of course feel free to add this mode :)

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/pull/179/files#diff-57b7368a1b4282832b5eaad8802b0dc3R308
