### ISSUE TITLE
No XML serializer registered for IFC4X1

### ISSUE THREAD

**Issue by AdriScho** [IfcOpenShell/IfcOpenShell#734]
Hi !

I'm getting an error when I'm trying to convert a file with IFC4X1 schema.
This is the error message : "No XML serializer registered for IFC4X1".

It refers to : 
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/serializers/XmlSerializer.cpp line 21.

Did I miss something here or is there an issue with IFC4X1 file schema ?

Environment : 
- CAD software : Civil3D 2019
- IfcConvert-v0.6.0-9bcd932 from IfcOpenBot ([IfcOpenBot](https://github.com/IfcOpenBot/IfcOpenShell/commit/9bcd932bed48486bf5b5f48d24b49329c280462f))
- Ubuntu 16.04 LTS 
- args : `--use-element-guids` and `--generate-uvs`.
- Conversion Geometry Format : .glb

For confidentiality reason, I can't share the original file, but I'm having the same result as this attached file (contains no data) : [test-file.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/3923017/test-file.zip)

**Comment by aothms** [comment]
That's a valid issue. For some reason in the file you referenced only two of the four schemas are initialized. This might be the case in other parts of the code base as well. I'll fix this soon, unless you are somebody else beats we to it. It's basically just copying `init_XmlSerializerIfc2x3` to `init_XmlSerializerIfc4x1` and `-4x2` and so on.

**Comment by AdriScho** [comment]
Ok ! 
I'll try to submit a PR about it this week-end.
