### ISSUE TITLE
conda version conflict

### ISSUE THREAD

**Issue by thorade** [IfcOpenShell/IfcOpenShell#735]
Is it documented anywhere which versions of ifcopenshell work well with which versions of pythonocc-core and oce?
If I want to/need to use pythonocc-core 0.18.1, what version of ifcopenshell should I use?

https://anaconda.org/search?q=pythonocc-core
https://anaconda.org/search?q=ifcopenshell

And, do I still need OCE?

**Comment by aothms** [comment]
I think OCE is always a dependency of pythonocc-core, but I'm not sure. In general there is no hard dependency on the IfcOpenShell-Python module and PytonOCC. They only interface by means of string serialization so there is no binary dependency. If you get dependency conflicts in conda you can always install outside of conda a statically linked IfcOpenShell binary from IfcOpenBot. https://github.com/IfcOpenBot/IfcOpenShell/commit/9bcd932bed48486bf5b5f48d24b49329c280462f#comments

**Comment by Moult** [comment]
Ping @Krande any ideas about closure on this bug with your recent Conda builds?

**Comment by Krande** [comment]
The Ifcopenshell (daily and stable conda-forge) builds are compiled against OCCT v7.6.2.

OCCT being the official opencascade version while OCE was the community branch of it. OCE is no longer maintained given that some time ago Opencascade opened more of their official code base. See https://github.com/tpaviot/oce/issues/745.

Coincidentally, I recently helped the pythonocc-core (which is a python SWIG wrapper around the OCCT c++ code base) with adding support for OCCT v7.6.2. So now pythonocc-core and ifcopenshell (and GMSH btw) are aligned wrt. to OCCT conda dependencies. 

So with respect to conda conflicts in the past, I think this issue can be closed.
