### ISSUE TITLE
Conflict with OCE 7.4.0 in geom module

### ISSUE THREAD

**Issue by derbosper** [IfcOpenShell/IfcOpenShell#736]
There is a function `has_occ()` in geom/main.py that checks if OCC is installed in the environment, which tries to `import OCC.BRepTools` and returns `False` when `ModuleNotFoundError` occurs. Now it failed even if I had the OCC installed. It seems like the old import structure is deprecated and now it supports only `import OCC.Core.BRepTools`.  I've updated all the necessary imports by adding the `.Core` and it basically solved the problem, but I wanted to let you know here :)

**Comment by aothms** [comment]
Great thanks for reporting. Do you think this is something that can made compatible? We'll probably need to use `import * from OCC.Core.gp` kind of imports for both with and without `Core` with `try catch`. What do you think? Pull requests welcome but don't feel obliged.

**Comment by mieszk** [comment]
Yes, if we want to support the old version, they both can be wrapped (with double `try-catch` for sure, maybe there is another possibility). Also, I can submit a PR.

**Comment by aothms** [comment]
try-catch is probably the 'pythonic' way to do this. Personally I would probably have a preference for something `importlib.import_module()` to have import based on dynamic strings, i.e. with and without `.Core.`.

**Comment by CyrilWaechter** [comment]
@derbosper Seeing related merges. Should this issue be closed now ?

**Comment by derbosper** [comment]
@CyrilWaechter Yes, I guess, seems like it's no longer an issue.
