### ISSUE TITLE
ifcopenshell python wrapper does not support SWIG 4

### ISSUE THREAD

**Issue by tpaviot** [IfcOpenShell/IfcOpenShell#739]
In the latest SWIG 4 release, the ````__swig_getmethods__```` dictionary no longer exists. See for instance https://github.com/swig/swig/commit/866429d0f7df5068f78951e3280fddbfaa7f462a

This dictionary is used here https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcwrap/IfcParseWrapper.i

Since it is enclosed between ```%pythoncode %{}```brackets, compilation works fine but import fails.

**Comment by sanderboer** [comment]
As far as I can tell the __swig_getmethods__ and __swig_setmethods__ lines can be removed as-is. It is very hard to find comprehensive documentation about these dictionaries, but from I can glean, these dictionaries are superfluous. I have branched v0.6.0-swig4 with __swig_etc removed and as far as I can tell no functionality has been impacted.

**Comment by tpaviot** [comment]
I confirm this can be safely removed.

**Comment by sanderboer** [comment]
@tpaviot As an aside, what is your view of swig vs pybind11 vs Boost::python ?

As I see it Swig it looks like it has the longest running history, pybind11 is header only and Boost::python is Boost, a primary citizen of this project and highly regarded in c++ land. 
Personally I am not too stoked on the documentation of swig, but other than that and a preference for header only libs I don't have a real view on the matter.

How do you feel about these libs and do you see a compelling reason to move away from swig ?

**Comment by CyrilWaechter** [comment]
@tpaviot On my machine ifcopenshell python compile with swig 4. Is it correct to say that this issue can now be closed ?

**Comment by aothms** [comment]
This has been addressed in https://github.com/IfcOpenShell/IfcOpenShell/commit/861dab0d9e516f0936e5d8e74a901c77434dc871 thanks all
