### ISSUE TITLE
geom.iterator with num_threads >= 2 seems to not process some shapes

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#741]
I notice that I can pickle the results of create_shape, but I can't pickle an IfcOpenShell file.by_id('foo'). This makes multiprocessing quite tricky in Python (which could make imports, exports, cutting sections, etc much faster)

Is it possible to call something to IfcOpenShell that will do multiprocessor processing, or things which can be done to improve pickling?

**Comment by aothms** [comment]
Three remarks:

* Pickling would be complicated (what parts of the graph to add...? Most of the IfcOpenShell functionality would require the complete underlying file.). But if you want to multiprocessing on non-mutated IFC files. The filename and the instance id can uniquely identify the instance.
* In the recent version of the v0.6.0 branch. `iterator()` has a num_threads argument.
* You can use `entity_instance.get_info(recursive=True)` to convert the instance attribute values recursively to native Python types that you can Pickle. But again, IfcOpenShell itself cannot really consume the data anymore.

**Comment by Moult** [comment]
I tried using the iterator with the `num_threads`, but I noticed some odd behaviour with a file (I'll send the file to you via email, as it is not meant to be public, please do not reshare).

In short, when I use `num_threads`, some of the elements are not processed - during an import in Blender, this means that a bunch of objects are missing in the import.

Here's a minimal test case which demonstrates the problem. When you uncomment the iterator line without num threads, the `if shape.guid` line will trigger. When `num_threads` is 2, the `if shape.guid` line will not trigger.

```
import ifcopenshell
import ifcopenshell.geom
f = ifcopenshell.open('/home/dion/sonni.ifc')
iterator = ifcopenshell.geom.iterator(ifcopenshell.geom.settings(), f, 2)
#iterator = ifcopenshell.geom.iterator(ifcopenshell.geom.settings(), f)
iterator.initialize()
n = 0
while True:
    print(n)
    shape = iterator.get()
    if shape.guid == '1CjwPynNHApwFBiToXmJbx':
        print('This element does not occur when num_threads is provided')
        break
    n += 1
    if not iterator.next():
        break
```

**Comment by aothms** [comment]
This is was a silly typo, but with profound effects, thanks for reporting.

**Comment by Moult** [comment]
Fantastic! Thank you! It would be great to get an IfcOpenBot build of this, since the benefits of multicore import is huge!

**Comment by htlcnn** [comment]
Could we please have a progress bar to see how much of ifc are imported or how many percent of geometries are created, instead of a timing/rolling mouse cursor?

**Comment by Moult** [comment]
A progress bar used to exist, but was removed for various temporary reasons, but it will come back :) Can you please create a new bug for this?
