### ISSUE TITLE
create_shape in ifcopenshell python crashes on wall containing IFCBOOLEANRESULT

### ISSUE THREAD

**Issue by DanielTrosten** [IfcOpenShell/IfcOpenShell#742]
When trying to create a shape from a wall containing IFCBOOLEANRESULT, the program crashes without any output.

- OS: Windows 10

- Example code:
```
import ifcopenshell
import ifcopenshell.geom

settings = ifcopenshell.geom.settings()
settings.set(settings.USE_PYTHON_OPENCASCADE, True)

ifc_file = ifcopenshell.open("wall.ifc")
walls = ifc_file.by_type("IfcWall")
shape = ifcopenshell.geom.create_shape(settings, walls[0])
print(shape)
```

- Conda environment:
```
name: ifc
channels:
  - defaults
  - conda-forge
  - dlr-sc
  - pythonocc
dependencies:
  - ifcopenshell
  - pip
  - python=3.6
  - pythonocc-core
  - pythreejs
```
- IFC file: [wall.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/3961445/wall.ifc.txt)

**Comment by Moult** [comment]
Works fine here, probably fixed since bug was originally reported.

![2023-03-05-125007_532x528_scrot](https://user-images.githubusercontent.com/88302/222937278-b264576c-0b79-463d-bd35-73ab3cebc3c2.png)
