### ISSUE TITLE
Can iterator.initialize() specify why a file is invalid?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#745]
For this snippet of code:

```
iterator = ifcopenshell.geom.iterator(settings, file)
valid_file = iterator.initialize()
    if not valid_file:
    return False
```

Instead of just a true/false result, can it log why it might think a file is invalid?

**Comment by Moult** [comment]
Or if it can't specify, what might be the potential reasons for a file to be invalid, that the validate() function does not catch?

**Comment by aothms** [comment]
ifcopenshell.file has a good() function which is (a) was the file readable (b) of a supported schema.

iterator initialize() returns not so much whether the file is valid, but whether there was an element that matches the inclusion filter settings and can be processed succesfully.

I think there should be something in ifcopenshell.get_log() in this case

**Comment by Moult** [comment]
Thanks and makes sense :) Closing bug!
