### ISSUE TITLE
How can i add my own Attribute?

### ISSUE THREAD

**Issue by dronov-dmitry** [IfcOpenShell/IfcOpenShell#749]
I can add only 6 attributes
![изображение](https://user-images.githubusercontent.com/9892891/71771034-9ce53900-2f3d-11ea-8792-a6f1ed0e81d6.png)
how can i add my own attributes
for example the Mass

**Comment by Moult** [comment]
I just deleted the Moult/blender-bim-ifc repo, as BlenderBIM is now hosted with IfcOpenShell. This is the correct place to report issues.

Attributes are a fixed set of values that can be set based on the IFC specification to an element. You are not allowed to add custom ones.

If you would like to add your own properties / metadata to an object, this requires setting a new custom property set (or pset in IFC lingo). BlenderBIM allows you to assign psets based on the folder names and CSV files in the `data/pset/` folder. The data folder by default is in the same place the Blender add-on is installed (`AppData/Roaming/Blender Foundation/2.81/scripts/addons/blenderbim` on windows, or `~/.config/blender/2.81/scripts/addons/blenderbim` on Linux, not sure on Mac).

In the `data/pset` folder you will find two psets that come with the add-on, a `Pset_DoorCommon` and a `Pset_FurnitureCommon`. You can create your own folder in here named whatever you want, like `Dmitry_CustomProperties`, and that represents a selection of custom properties. In that, using the others as an example, you can create a CSV which contains key value pairs for the property name and the property value.

Once they've been added, you'll find the options to assign them in the BlenderBIM interface.

**Comment by dronov-dmitry** [comment]
Ok
I see that page not found https://github.com/Moult/blender-bim-ifc

**Comment by Moult** [comment]
Correct, I just deleted that repo.

BlenderBIM installs into Blender's add-on directory - see [here](https://blender.stackexchange.com/a/35600) for where to find the add-on folder depending on your OS.

Inside the blenderbim folder there is a `data` folder, which allows you to create data presets related to your project. Property sets are in CSV format, because spreadsheets are a much better interface to manage these datasets than Blender.

**Comment by dronov-dmitry** [comment]
1) Ok. I see that blenderbim is error 404 now https://github.com/Moult/blender-bim-ifc
In what folder of ifcOpenShell it is now located?
2) I found pset folder but how it can be added to blender? I can't see the dropdown list like in attributes...
![изображение](https://user-images.githubusercontent.com/9892891/71771578-11bc7100-2f46-11ea-9eb2-e634d35bf7d9.png)

**Comment by dronov-dmitry** [comment]
1) Ok. Understand. Now i just need to download blender from official site and blenderbim addon is implement inside package. Ok. Thanks

**Comment by Moult** [comment]
Yep install from the official website. Uninstall anything you currently have first.

In the scene properties, not the object properties, there is a "assign pset" button somewhere. You will notice the values correspond to the CSV files in your `data/pset` folder. You can create your own psets in CSV format :)

**Comment by dronov-dmitry** [comment]
Ok it work
![изображение](https://user-images.githubusercontent.com/9892891/71771868-43cfd200-2f4a-11ea-9527-2839eaa6cc7d.png)
and how can i hide the name of pset-folder inside attribute name?
it is not very big problem but it will be more clearly..

**Comment by dronov-dmitry** [comment]
and where i can find blenderbim on github to look how it leaving and growing?

**Comment by Moult** [comment]
Github link: https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src

Also blenderbim.org shows the latest updates on the homepage and on IRC the ##architect channel shows it too https://blenderbim.org/community.html

I sometimes post updates on various forums.

**Comment by Moult** [comment]
If that's how revit imports it, there's not much I can do, that's a limitation of revit. The data, however, should be correctly assigned in IFC.

By the way, there are restrictions on what psets apply to what objects. For example, a furniture pset can't be assigned to a roof object. However, at the moment BlenderBIM doesn't guide you on this. This needs to be improved and will be in the future :)

**Comment by Moult** [comment]
Can this bug be closed as you have figured out how to add properties to an object?

**Comment by dronov-dmitry** [comment]
yes. Thx
