### ISSUE TITLE
I cannot import ifcopenshell

### ISSUE THREAD

**Issue by keleisi2001** [IfcOpenShell/IfcOpenShell#754]
I used  Anaconda to install ifcopenshell, input conda install -c conda-forge -c oce -c dlr-sc -c ifcopenshell ifcopenshell, and it showed "All requested packages already installed."

But I opened the IDLE and VSCODE, they showed " No module named 'ifcopenshell'"

I don't know if I really installed it successfully. How to solve it?

If someone needs screenshot, I can send an email to him！Thank you！

**Comment by Moult** [comment]
I'd assume that your IDLE program and VSCODE are not using the Anaconda Python and instead using a different python. Can you check that they are the same Python version, and that the values of `sys.path` are both the same? In your `sys.path` you should be able to find the ifcopenshell folder.

**Comment by keleisi2001** [comment]
> I'd assume that your IDLE program and VSCODE are not using the Anaconda Python and instead using a different python. Can you check that they are the same Python version, and that the values of `sys.path` are both the same? In your `sys.path` you should be able to find the ifcopenshell folder.

OK. I tried again but the questions could not resolve.

Now I only use python 3.7, and Anaconda is also python 3.7 version. 

Using Anaconda to install Ifcopenshell, it is OK.

But the python 3.7 IDLE and PyCharm still show "No module named ifcopenshell"

I don't know where is wrong...

**Comment by keleisi2001** [comment]
> I'd assume that your IDLE program and VSCODE are not using the Anaconda Python and instead using a different python. Can you check that they are the same Python version, and that the values of `sys.path` are both the same? In your `sys.path` you should be able to find the ifcopenshell folder.

You can see my screenshot from this link:
https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/ff35f3cc4d/?limit=25
