### ISSUE TITLE
Create documentation for IfcOpenShell, BlenderBIM, et all

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#755]
I have just started a Sphinx docs for BlenderBIM: https://github.com/IfcOpenShell/IfcOpenShell/commit/e927ac49ac4afaed6a58c4fbad4a27d025f7e045

I will need to write docs for BlenderBIM's various features. However, I will also need to write documentation on how to use utilities like IfcClash, IfcDiff, IfcCOBie, BIMTester... so I figured maybe it is worthwhile proposing that instead of me just creating documentation for these alone, I should create a new Sphinx docs for IfcOpenShell, with subcategories for BlenderBIM, IfcMax, IfcConvert, IfcClash, BIMServer-plugin, IfcOpenShell-python, etc - then the IfcOpenShell website could be updated with a link to this central documentation location, and people can start contributing.

Thoughts? Good / bad idea to combine docs? Should docs be hosted on `ifcopenshell.org/docs/`?

In addition, I'm not sure where the source code is for the IfcOpenShell.org site, perhaps it could be updated with IfcBlender changed to "BlenderBIM" and linking to blenderbim.org to prevent confusion?

**Comment by aothms** [comment]
Sphinx is only Python (am I correct?) but obviously a great starting point. Or are you suggesting to use https://breathe.readthedocs.io/en/latest/ ? 

> IfcBlender changed to "BlenderBIM" and linking to blenderbim.org to prevent confusion?

I will.

**Comment by Moult** [comment]
I guess there's two aspects - there's code documentation and user documentation. For user documentation, Sphinx just parses `.rst` files which you write yourself. There is a ton to write about from a user perspective for BlenderBIM and its utilities. This is what I had started to write.

For code documentation, Sphinx I believe out of the box parses docstrings which is Python only, but yes the Breathe project looks like a very cool Sphinx extension that parses doxygen output. That would help document the C++ side of things :)

If you think it is a good idea to start writing these docs I can get started :) Also let me know if you think it's a good idea to combine all apps under IfcOpenShell's umbrella into a single Sphinx-based docs, or keep them separate?

**Comment by Moult** [comment]
Docs hosted now on https://blenderbim.org/docs/ (still work-in-progress)

If you think it makes sense to combine the docs into a single master doc, I can restructure the pages and it makes more sense to host it on the ifcopenshell website, not the blenderbim website.

**Comment by htlcnn** [comment]
Excuse me, I don't know where to ask for BlenderBIM. I installed both IfcBlender and BlenderBIM. Now I have 2 **File -> Import -> Industry Foundation Classes (.ifc)** menu entries. Which should I choose? Thanks.

**Comment by Moult** [comment]
@htlcnn sorry for the confusion - the IfcBlender plugin on the ifcopenshell.org website is an older version and has been superseded with a new plugin which has both import and export. My advice is to uninstall both to be sure, and you can go to https://blenderbim.org/ to download the latest (a new version was released just a few minutes ago!) You can catch me on IRC for help too https://blenderbim.org/community.html

**Comment by aothms** [comment]
Great, I thinks it's best to combine things. I think many users have a
choice, write bespoke code, use ifcconvert output or script things in
blender bim. If we have uniform documentation it can guide them best.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op wo 8 jan. 2020 11:17 schreef Dion Moult <notifications@github.com>:

**Comment by Moult** [comment]
I've just merged the documentation structure for all IfcOpenShell docs. When you're ready @aothms feel free to move the files from `src/ifcblenderexport/docs/` to, uh, I guess just `docs/` and set up something on the IfcOpenShell.org website so that it can be accessed and built on a commit hook (I assume?)

Feel free to close the issue when docs are deployed :) Also when the BlenderBIM link on the IfcOpenShell site is updated to prevent confusion :)

I'll continue writing docs here and there in the meantime.

**Comment by aothms** [comment]
Great starting point thanks! I'll work on those things, not sure yet if I'm going to setup travis to deploy the docs to S3 or run something on my webserver.

Pardon my ignorance, but how does this work together with source code comments?

**Comment by Moult** [comment]
I just added "autodoc" for the pages for IfcOpenShell-python - assuming ifcopenshell is in the Python path (therefore, if Travis or your webserver generates it, it needs to have IfcOpenShell in the path with the latest docs) so that Sphinx's conf.py can load it, it will load ifcopenshell, and detect the docstrings, and document them [here](https://github.com/IfcOpenShell/IfcOpenShell/commit/f80e7009978b985df18ed855d11206b26d9e8cf5#diff-259d507ff871f12dff37f1f292c29ad8).

See picture below :)

For C++, I think first you need to generate Doxygen XML, and then Sphinx can read it using the Breathe plugin. But perhaps this is more your domain :)

![2020-01-21-213629_643x957_scrot](https://user-images.githubusercontent.com/88302/72797925-1c8d3a80-3c96-11ea-993e-b578495723e3.png)

**Comment by Moult** [comment]
Closing this, as most public facing functions are now documented, and work is underway in the OSArch wiki to provide more user tutorials / guides :)
