### ISSUE TITLE
Can someone help me with getting this module to work on Python 3.8.1) :)

### ISSUE THREAD

**Issue by Kickdak** [IfcOpenShell/IfcOpenShell#757]

**Comment by aothms** [comment]
I hope to be able to add it to the build matrix for the next set of builds.

**Comment by keleisi2001** [comment]
you know 3.7.6 is not very ok，so I argue that it will be developed for several months

**Comment by lgtrombetta** [comment]
Hi there. Any news on this?

**Comment by CyrilWaechter** [comment]
Hi,
It would be great if you could add python 3.8 to IfcOpenBot.

**Comment by aothms** [comment]
For the time being you can also try to get ifcopenshell builds from conda-forge. They're bz2 archives that should work in regular python distributions as well.

https://anaconda.org/conda-forge/ifcopenshell/files

**Comment by CyrilWaechter** [comment]
Yes. This is what I did until now. Using conda forge build perfectly work but v0.6.0b0 it is a bit old now and some known bugs have been fixed.

**Comment by aothms** [comment]
The master build just came in https://github.com/IfcOpenBot/IfcOpenShell/commit/3c355b4848e939fdb3da7872a1bcbb60d76ef11b#commitcomment-37874088

Hopefully same for v0.6.0 in a couple hours 

Conda forge update is also in the making https://github.com/conda-forge/ifcopenshell-feedstock/pull/7
