### ISSUE TITLE
Storing point clouds in IFC

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#760]
Since Blender supports point clouds, I plan to write a feature where a point cloud can be read/written in an IFC file. From a theoretical point of view, this seems straightforward, as IFC as a point cloud representation which is a bunch of cartesian points. Two questions:

1. Where would RGB or other scalar data be stored?
2. What are the currently known strategies around efficient storage (clearly IFC is _not_ efficient) and retrieval? Would this be related to HDF5?

**Comment by aothms** [comment]
https://www.sciencedirect.com/science/article/abs/pii/S1474034617301313

Without paywall:

https://research.tue.nl/files/60197483/krijnen_beetz_ifc_pointclouds.pdf

In short, yes, HDF5, attributes like normal colour and intensity, quantisation and other compression, partial retrieval.

But for us academics most interesting perhaps the association of point cloud segments to building elements and the additional semantics that can be derived from that re material characteristics, exact placement, structural deviation, ...

**Comment by chri7928** [comment]
In addition to HDF5, you might look at LEPCC which is open and freely usable as well, plus it's used in the OGC I3S Point Cloud Scene Layer format which _might_ make it then easier to use I3S with what you're considering in IFC.

https://github.com/Esri/lepcc

**Comment by Moult** [comment]
Just to keep this issue updated, commit a200310 implements the ability for Blender to export a point cloud into IFC. Only the XYZ is exported. RGB and other scalar data cannot currently be stored in the IFC4 spec and so the data is lost.

Thanks for the paper @aothms ! I am slowly reading it.

**Comment by EAzari** [comment]
Please check these three too, maybe helps:
- [FlatBuffers](https://en.wikipedia.org/wiki/FlatBuffers) from Google
- [blazingSQL](https://blazingsql.com)
- [SQLite](https://en.wikipedia.org/wiki/SQLite)
- so on (maybe you found something more better. Personally I see HDF5 has some significant cons)

**Comment by Moult** [comment]
Closing this issue as the IFC entities related to point clouds are not yet in the official spec, so this is a non-issue.
