### ISSUE TITLE
No materials or surface styles found for IfcColumn (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#764]
1. Convert [764--column--no-materials-or-surface-styles-found.ifc](https://github.com/IfcOpenShell/files/blob/master/764--column--no-materials-or-surface-styles-found.ifc) with 71f836d013b0daa7f8094337db0f124ff75402bc (OCCT 7.3.0p4).
2. Experience that no materials or surface styles are found, and that the output object is fallback grey:
```[Warning] {0woQUa3rt9owQbyP5HckVg} Subtraction yields unchanged volume:
#8926=IfcBooleanResult(.DIFFERENCE.,#8921,#8925)
[Warning] {0woQUa3rt9owQbyP5HckVg} No material and surface styles for:
#8930=IfcColumn('0woQUa3rt9owQbyP5HckVg',#5,'','','',#8889,#8929,'')
```
<img width="355" alt="Screenshot 2020-01-14 at 12 46 26" src="https://user-images.githubusercontent.com/4601554/72342049-0b5b9100-36cc-11ea-86e8-a01f94b53ab6.png">

3. The expected color to be picked up is "Light magenta", but the color is lost somewhere on the way here:

```
#8890= IFCCOLOURRGB('Light Magenta',0.686274509803922,0.505882352941176,0.752941176470588);
#8891= IFCSURFACESTYLERENDERING(#8890,0.,$,$,$,$,IFCNORMALISEDRATIOMEASURE(0.00390625),IFCSPECULAREXPONENT(10.),.NOTDEFINED.);
#8892= IFCSURFACESTYLE('STEEL/S355',.POSITIVE.,(#8891));
#8893= IFCPRESENTATIONSTYLEASSIGNMENT((#8892));
#8928= IFCSTYLEDITEM(#8897,(#8893),$);
#8897= IFCEXTRUDEDAREASOLID(#8894,#8896,#9,7165.);
#8905= IFCBOOLEANRESULT(.DIFFERENCE.,#8897,#8904);
#8913= IFCBOOLEANRESULT(.DIFFERENCE.,#8905,#8912);
#8917= IFCBOOLEANRESULT(.DIFFERENCE.,#8913,#8916);
#8921= IFCBOOLEANRESULT(.DIFFERENCE.,#8917,#8920);
#8926= IFCBOOLEANRESULT(.DIFFERENCE.,#8921,#8925);
#8927= IFCSHAPEREPRESENTATION(#12,'Body','CSG',(#8926));
#8929= IFCPRODUCTDEFINITIONSHAPE($,$,(#8927));
#8930= IFCCOLUMN('0woQUa3rt9owQbyP5HckVg',#5,'','','',#8889,#8929,'');
```
Expected color trace mapped out in this pdf: 
[IfcColumn--no-materials-or-surface-styles-found.pdf](https://github.com/IfcOpenShell/IfcOpenShell/files/4059020/IfcColumn--no-materials-or-surface-styles-found.pdf)

Expected color from Solibri and SimpleBIM:
<img width="369" alt="Screenshot 2020-01-14 at 12 47 15" src="https://user-images.githubusercontent.com/4601554/72343303-d0a72800-36ce-11ea-9fff-25c820b89fd3.png">

**Comment by aothms** [comment]
We do pick up the style associated to the first operand of the boolean op. But somehow this was only done for `IfcBooleanClippingResult` and not the more general `IfcBooleanResult`. Thanks for reporting.

**Comment by johanrd** [comment]
Thanks! I can verify that d9805185eeba151b256df54c3dcc3f71fd3416f2 fixes this:tada: Closing.
