### ISSUE TITLE
Number of vertices for columns / circles / curves

### ISSUE THREAD

**Issue by michalkubis** [IfcOpenShell/IfcOpenShell#766]
_Apology, this isn't exactly an issue, it's a question with suggestion._

Is there a way to change the number of generated vertices for columns / circles / curves please?

![image](https://user-images.githubusercontent.com/47777142/72439929-2b608280-37a8-11ea-8cfc-d0008deb3fcf.png)

If yes, could this be part of the command line arguments?

**Comment by aothms** [comment]
Yes, this is the `--deflection-tolerance` of IfcConvert, the max linear distance. So a higher value will result in fewer segments. Unfortunately there is also an angular value, but that one is currently hard coded. So at very high deflection the angular will be dominant.

**Comment by michalkubis** [comment]
That's great! Thank you. I was actually playing with this param already, but ended up with value 1.0 thinking it does not work. I can see now that higher values work, but columns have still too many polygons. It would be amazing, if we could set also that hard coded angular value from command line. It could save lot of polygons for huge MEP models.

Here's a screen from BIM Vision and I was looking for something similar in IfcConvert.

![image](https://user-images.githubusercontent.com/47777142/72458005-0ed44280-37c8-11ea-82dd-13976e2ed104.png)

**Comment by Moult** [comment]
In addition, can this be controlled from the geom iterator?

**Comment by michalkubis** [comment]
Would it be too complicated to add that hard coded value into command line params? Is it just single value? Could you please provide more details?

**Comment by Moult** [comment]
Bumping issue, as I'm getting a question from a user on how they can adjust the faceting level of detail.

**Comment by aothms** [comment]
I've added angular tolerance. In python you should be able to call `set_deflection_tolerance(v)` and `set_angular_tolerance(v)` on the settings object. I didn't extensively test this how this affects the circular column.

**Comment by Moult** [comment]
Closing, as I think this is fixed :) wooo!
