### ISSUE TITLE
All 4 vertices of an element

### ISSUE THREAD

**Issue by khyatiip** [IfcOpenShell/IfcOpenShell#767]
Hello,

I'm trying to find all 4 vertices of an element in the global coordinate system.
```
import ifcopenshell
import ifcopenshell.geom
from OCC.Core import BRep
from OCC.Core import BRepTools
from OCC.Core import TopAbs
from OCC.Core import TopoDS
from OCC.Core import TopExp
settings = ifcopenshell.geom.settings()
settings.set(settings.USE_PYTHON_OPENCASCADE, True)

ifc_file = ifcopenshell.open('untitled1.ifc')
    
spaces = ifc_file.by_type('IfcWindow')[0]

product = ifcopenshell.geom.create_shape(settings, spaces)
shape = TopoDS.TopoDS_Iterator(product.geometry).Value()
trsf = shape.Location().Transformation()
print (trsf.TranslationPart().Coord())
```

This only gives me one coordinate. How do I get all the vertices/coordinates? Can someone help me here with an example?

**Comment by Moult** [comment]
Converting back to the global coordinate system is quite tricky as IFC can have a long hierarchy of relative transformations. Hopefully this helps:

https://github.com/IfcOpenShell/IfcOpenShell/issues/688

**Comment by twut** [comment]
You will only get one coordinate of a vertex of IfcWindow[0] in your code.

Try the following code. It will give you the coordinates of all the vertices of IfcWindow[0]

`exp = OCC.Core.TopExp.TopExp_Explorer(shapes.geometry, OCC.Core.TopAbs.TopAbs_VERTEX)
while exp.More():
    vertex = OCC.Core.TopoDS.topods_Vertex(exp.Current())
    pnt = OCC.Core.BRep.BRep_Tool_Pnt(vertex)
    print(pnt.X(), pnt.Y(), pnt.Z())
    exp.Next()`

**Comment by khyatiip** [comment]
> You will only get one coordinate of a vertex of IfcWindow[0] in your code.
> 
> Try the following code. It will give you the coordinates of all the vertices of IfcWindow[0]
> 
> ```python
> exp = OCC.Core.TopExp.TopExp_Explorer(shapes.geometry, OCC.Core.TopAbs.TopAbs_VERTEX)
> while exp.More():
>        vertex = OCC.Core.TopoDS.topods_Vertex(exp.Current())
>        pnt = OCC.Core.BRep.BRep_Tool_Pnt(vertex)
>        print(pnt.X(), pnt.Y(), pnt.Z())
>        exp.Next()
> ```

I tried this but for some reason it gives me rotated geometry and the walls have gaps in between them (10mm-30mm)

**Comment by Moult** [comment]
@khyatiip that will give you the local coordinates. You need to transform it by the object's matrix. You can use this to get the matrix:

```
matrix = ifcopenshell.util.placement.get_local_placement(spaces)
```

Then you need to use the matrix to multiply the coordinates you get from that shape.

If you don't want to use that matrix, you can use this setting:

```
settings.set(settings.USE_WORLD_COORDS, True)
```

Closing issue as does not seem to be a bug :) You might like to try https://community.osarch.org/ for more of these types of questions. Hopefully the tips help!
