### ISSUE TITLE
IfcConvert --threads crashing

### ISSUE THREAD

**Issue by michalkubis** [IfcOpenShell/IfcOpenShell#769]
When I'm using IfcConvert with --threads it does not seem to be stable. It fails quite randomly. No problem when I omit this param. I tried multiple times, multiple computers, same results.

**Comment by Moult** [comment]
Potentially related to these two other bugs to do with multicore processing: #741 and #746 ?

Can you supply a test file?

**Comment by michalkubis** [comment]
Sorry for the delay. I can't provide original files, but now I tested with random IFC and it seems to fail too. See attached zip. There's a bat file which calls IfcConvert every 5 seconds. It fails quite often on my side.

[Test.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4110262/Test.zip)

![sample](https://user-images.githubusercontent.com/47777142/73097272-0b873800-3ee7-11ea-9496-e7f3d833cafd.png)

**Comment by Moult** [comment]
I tried to replicate this using this in bash:

```
for i in {1..10}
do
    ./IfcConvert Duplex_A_20110505.ifc Duplex_A_20110505.dae --yes --thread 12
    sleep 5
done
```

It works fine here without issues. Can you try recreate it using the latest IfcConvert? https://blenderbim.org/docs-python/ifcconvert/installation.html

**Comment by michalkubis** [comment]
Tested with the latest IfcConvert (0.7) and confirming it works.
