### ISSUE TITLE
Define export symbol to have IfcGeom as a dynamic lib

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#77]
As per https://github.com/IfcOpenShell/IfcOpenShell/pull/76#issuecomment-222358392

**Comment by Stinkfist0** [comment]
I could take care of this. Do you have preferences for the file and macro names for IfcGeom's import/export business?

**Comment by aothms** [comment]
Well, there are some acronyms established as how to refer to IfcOpenShell: `IFCOS_`, `IOS_`, etc. You personally seem to use `IFCOS_`. What would your opinion be on simply `IFC_`? Similar to ICU uses `U_`. People hopefully wouldn't use multiple IFC libraries in their project.

Copying ICU once again, we would get `IFC_STATIC_IMPLEMENTATION`. Possibly `IFC_PARSE_STATIC_IMPLEMENTATION` and `IFC_GEOM_STATIC_IMPLEMENTATION` if two separate ones make sense (no clue, could be conditionally derived from one project-wide macro). It's a little lengthy, I am fine with `IFC_*_STATIC_LIB` for example as well.

Thoughts?

**Comment by Stinkfist0** [comment]
IFC_STATIC_* sounds good. However, as building IFCOS libs as static libraries has been and currently is the default behavior and linking to static libraries requires no macro gymnastic, it would feel more natural to have the definition for the special case, i.e. IFC_DYNAMIC/SHARED_* which requires all these tricks. Also, I think it would be nice not to require client code the add the IFC_WHATEVER definition when using IFCOS, but instead when IFCOS is deployed, we would deploy a small configuration header which automatically has these definitions baked in. A quick pseudo draft:
```c++
// ifc_build_config.h
#pragma once
#define IFC_STATIC_BUILD
#define IFC_SCHEMA_2X3
// and so on...
```

**Comment by jobermayr** [comment]
Why was it neccessary to build ifcparse SHARED and ifcgeom STATIC?

I introduced it with commit 4218890 vice versa since SHARED ifcgeom super lib worked on openSUSE ...

**Comment by jobermayr** [comment]
Maybe you want to use a version-script:
https://cmake.org/pipermail/cmake/2008-August/023202.html

**Comment by aothms** [comment]
@jobermayr problem is that we use `-fvisibility=hidden` in our build script [1], so `IfcGeom` would be built without any exported symbols. AFAICT this is the recommended way to build binaries on *nix. On windows this is the default, so for the time being it has to be dynamic there. For `IfcParse` we have the exported symbols defined now in code [2], but this still remains to be done on account of the issue we are commenting on now.

We chose the quickest route to have things build for now. If it is important to have this working for you now on the master branch prior to this issue being fixed, feel free to commit either in the build script or cmake something so that, as long as we're not on windows either `-fvisibility=hidden` is detected and only in that case force `IfcGeom` to be dynamic, or `-fvisibility=hidden` is removed specifically for `IfcGeom`.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.sh#L241
[2] https://github.com/IfcOpenShell/IfcOpenShell/commit/b5c4eb3b6f6af3aeeaa50b683638c18c3cb6c255#diff-13

**Comment by Stinkfist0** [comment]
Doing this now.
