### ISSUE TITLE
Can geom iterator or create_shape understand representation context?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#771]
Is it possible to have the geom iterator or a create shape return only the shape from a representation that is part of a specific context/subcontext/target view, say Model/Body/MODEL_VIEW, or Model/Clearance/MODEL_VIEW, etc? Or perhaps when it processes the shapes, I can tell which is which?

With this ability, I can make the import script distinguish between contexts and build features to let users isolate contexts.

**Comment by Moult** [comment]
To clarify on this issue, I note that it is possible to do create_shape on a particular item in a representation, this allows me to achieve this.

Similar to this issue, is it possible to use the geom iterator to pull out individual representation items? For example, if item 1 has style A, and item 2 has style B, then when I iterate, I want to be able to distinguish which item has which style. I understand that the geometry iterator returns a shape which has `shape.geometry.materials`, but I am actually parsing materials myself to handle situations like material layers, material sets, and distinguishing between styles assigned to objects and styles assigned to materials (which can be represented in Blender).

I'd like to just use the geometry iterator, not create_shape, since it supports multicore ideally.

**Comment by aothms** [comment]
You can use create_shape on an individual representation item. But indeed within the returned mesh, the provenance to individual items is not retrievable. We could add another array for that similar to the material_ids. What do you propose?

The context name is appended to the mesh id. Often as e.g. `-body`. And indeed as you say you can call create_shape() with the representation and track their provenance to context based on the inverse attribute on the context or forward attribute on the rep.

Overall this is something I hear more. On the one hand the ease of use of the iterator on the other hand more granular and detailed return types. But it's not trivial due to the product level modifications that can occur, such as openings, layers and materials.

**Comment by Moult** [comment]
If another two properties were added, e.g. `shape.geometry.representations` (which would hold things like `Model/Body/MODEL_VIEW` (note that Body alone is not enough, since all three are required for the user to apply filtering in the viewer), and then `shape.geometry.representation_ids` that would resolve the issue.

I don't mind not using iterator, but the three showstoppers for create shape currently are:

 1. Unable to filter elements (sometimes, like a partial import, I only need to iterate through a subset)
 2. I have to manually work out the local -> global coordinate conversion when placing an object, which since IfcOpenShell doesn't expose it in Python, I need to redo it, and I've made mistakes, and doubt I've caught all my mistakes :)
 3. Multicore - super, super, important when I need to import 1GB of models every week.

**Comment by Moult** [comment]
@aothms Can I ask what the logic is for determining the shapes to build in the geometry iterator?

The behaviour I would expect, is that the geometry iterator would look _only_ for the Model Body context, and only build the shapes for that. (Perhaps in the future it could be configurable, but for now, only body)

In practice, especially when "include curves" is enabled, I have seen the geometry iterator process Axis geometry. Then I have both body and axis geometry. I have also seen in some IFC files that an axis is created, but then the body is lost.

In the BlenderBIM Add-on, until it is configurable, I would prefer a default of only model body, and then if I wanted something else I can trigger a feature that extracts the other representations.

**Comment by aothms** [comment]
This the set of contexts we look at: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomIteratorImplementation.h#L256 indeed depending on two settings (Axis is added when INCLUDE_CURVES, but if you don't need it there isn't really a lot of processing time spent here)

I think ultimately the only way to cleanly solve this is either rewrite iterator do processing after `next()` and provide a `skip()` or similar. Or use a callback function in Python (apparently rather complex https://stackoverflow.com/questions/12392703/what-is-the-cleanest-way-to-call-a-python-function-from-c-with-a-swig-wrapped)

**Comment by Moult** [comment]
@aothms is it possible to get it to _only_ process model body and nothing else? Keeping in mind that the model body can contain purely curve geometry (e.g. 3D wireframes). I'm running into an issue where the iterator would process axis geometry and ignore the body. Just as a working solution until the iterator is rewritten to be more flexible in regards to targeting a context.

**Comment by aothms** [comment]
I guess not, but you could always rearrange the shape representations in
the file, using ifcfile.remove or relabel the identifiers prior to feeding
it to the iterator.

Op vr 5 jun. 2020 om 12:18 schreef Dion Moult <notifications@github.com>:

**Comment by Moult** [comment]
Cheers - I will do that then - not ideal, but as a workaround until future updates :)

Thanks for all the help!

**Comment by Moult** [comment]
Closing as fixed :)
