### ISSUE TITLE
Branding and use of the name "BlenderBIM"

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#772]
It is uncertain whether use of the word "Blender" is acceptable by the Blender Foundation, as it is their trademark.

The following email was sent to the Blender Foundation. This issue has been created for public transparency.

```
Good morning!

My name is Dion and I am the main developer of a free and open source Blender
add-on which adds BIM authoring capabilities to Blender, as well as various
BIM-related utilities which integrate with Blender. This add-on is named
"BlenderBIM".

This originally began from a plugin called "IfcBlender", which is part of a
project called "IfcOpenShell", which has been around for many years, developed
by Thomas Krijnen (https://ifcopenshell.org).

BIM stands for Building Information Modeling - these add-ons allow people to use
Blender in the architectural, engineering, construction, facility management,
building operations, surveying, and quantity take-off industries, among others.
IFC stands for Industry Foundation Classes, which is an ISO open-data standard
to exchange BIM data in software.

The end-goal is to enable people to have a 100% free and open-pipeline in the
design and construction of buildings and our built environment, in compliance
with ISO open data standards, in an industry that is currently dominated by a
few proprietary monopolies.

Community feedback has been surprisingly positive and after one person called
the series of extensions "BlenderBIM", I decided to register
https://blenderbim.org/ and set up a website, and also referred to the project
as "BlenderBIM". This has been going on for about half a year.

Another community member recently pointed me to
https://www.blender.org/about/logo/ where it says that the use of the name
Blender is not recommended, so I decided to send this email.

To clarify:

 - I am not redistributing Blender itself. Only the add-ons are being
   distributed. This is not a fork of Blender.
 - No services are being offered. We do not offer BIM modeling or rendering or
   construction documentation or even support services. There is only the add-on
   and a series of utilities.
 - There is no organisation or company behind BlenderBIM, just open source
   contributors.
 - Along with the main add-on which has organically called itself "BlenderBIM"
   by the building community, there are some other utilities distributed which
   are independent, but can integrate with the BlenderBIM add-on. These have
   names like "BIMTester", and "IFCDiff", etc. They do not have the word
   "Blender" in their name as they do not depend on Blender. Instead they have
   words like "IFC" if they relate to IFC only, and words like "BIM" if they are
   only related to BIM.
 - I have always personally said that BlenderBIM is simply an add-on to Blender
   that adds BIM capabilities, not advertised it as being Blender itself.

Ideally, as I have already purchased the domain name and users do not seem to
have any misunderstandings currently about the relationship between Blender and
BlenderBIM, I would like to keep on using the name, but I understand completely
if the Blender foundation forbids it. There has been a lot of positive feedback
from both the building industry and Blender community about the project. I also
believe that the name accurately connotes that it is an extention to Blender
that provides BIM capabilities, where most people traditionally consider Blender
to be an artists tool and not able to author BIM data. I believe the name of
"BlenderBIM" would be similar to other projects like "BlenderXR"
(https://www.marui-plugin.com/blender-xr/) which adds VR capabilities to
Blender, or "MechanicalBlender" (http://www.mechanicalblender.org/) which adds
mechanical engineering and CAD tools to Blender.

Perhaps another good thing to do, regardless of the use of the word "Blender" in
the name of the add-on, is to get BlenderBIM recognised as an official add-in
packaged with Blender, although I am not sure what the process is for this.

Looking forward to your thoughts, and hoping that the name is acceptable to the
Blender Foundation.

Kind regards,
-- 
Dion Moult
```

**Comment by Moult** [comment]
Reponse from Ton:

```
   Hi Dion,

   Thanks for connecting.

   I think you will understand that we are developing a bit more strict
   and clear guidelines for the Blender brand. It's important to not
   confuse the audience. I also want to have fair guidelines to prevent
   freeriders to jump the bandwagon by selling Blender branded products.

   Firefox wrote (imho) friendly and fair guidelines, mostly to give a
   level playfield for everyone. They have as a rule that addon names (for
   example) should not start with the word "Firefox".

   The BlenderXR people have been contacted by me last year already about
   their confusing web presentation...

   Obviously I don't want to put cool initiatives like yours in a bad
   light or frustrate it. I don't even have time (nor staff) to go after
   all these cases!

   I hope we can agree on some kind of transition period:

   - Just keep using the url

   - Make it clear to everyone that you offer a Blender Addon; call it
   "BlenderBim Addon". Use that word consistently. Preferably update the
   logo this way too. Even better is to introduce it as "Addon to support
   OpenBIM in Blender". Currently on your front page it is not mentioned
   that you provide an addon.

   - Add a credit in the footer "Blender is Free Software made by the
   community of blender.org". (with url link)

   For as long your intiative is clearly about the add-on (not a
   business), and it's offered free/gratis, made by a community, you won't
   hear me complain soon.

   All the best,

   -Ton-
   ----------------------------------------------------------------------
   Ton Roosendaal - [1]ton@blender.org - [2]www.blender.org
   Chairman Blender Foundation, Director Blender Institute
   Buikslotermeerplein 161, 1025 ET Amsterdam, the Netherlands
```

**Comment by Moult** [comment]
Reply by me:

```
Good morning Ton!

Thank you for your understanding and kind support! I have:

 - Kept the URL blenderbim.org unchanged.
 - I have updated the site already to ensure that it is consistently referring
   to it as the BlenderBIM add-on.
 - I have added a credit in the footer.
 - The add-on will always be free software and community-made.
 - Always refer to it as the BlenderBIM Add-on in all future content.

You mention a "transition" period, do you still expect the name to change in the
future, or are the steps taken above adequate?

I will copy this email reply to the issue tracker so that others are aware of
the agreement: https://github.com/IfcOpenShell/IfcOpenShell/issues/772

Please let me know if you would like anything else changed on the website.

As an aside, would you be interested in learning more about BIM, IFC (and other
OpenBIM data formats), and using Blender in the AEC (arch/eng/construction)
industry for more than just concept/viz? I wonder what could be achieved if
there was tighter integration and a few more CAD-like features out-of-the-box in
a vanilla Blender - it would certainly go a very, very long way. Who would be
the right person to speak to?
```

**Comment by Moult** [comment]
Response from Ton. Issue will now be closed.

```
   Hi,

   Fantastic reply, thanks a lot. You set an example for many others :)

   Transition period - I more of mean the period during which we will ask
   people who provide Blender based products/forks/addons/tutorials/etc to
   become more aware of proper use of the brand. I don't expect everyone
   radically changing right away.

   To allow community initiatives more leeway than commercial ones will be
   a good guideline for the future as well.

   Laters,

   -Ton-
   ----------------------------------------------------------------------
   Ton Roosendaal - [1]ton@blender.org - [2]www.blender.org
   Chairman Blender Foundation, Director Blender Institute
   Buikslotermeerplein 161, 1025 ET Amsterdam, the Netherlands
```

**Comment by Moult** [comment]
An update that Blender is now stricter about this with the launch of their new extensions website. Under https://extensions.blender.org/terms-of-service/ it has a section called Branding which states:

> Do not include the name "Blender" in your extension.
> Do not use the Blender logo or icon in the extension thumbnail, icon or gallery.
> When in doubt, consult the [Blender logo guidelines](https://www.blender.org/about/logo/).

I asked the Blender Foundation about this and got this response:

> Hi Dion,
> 
> As general branding guidelines for products or services, we recommend third parties to avoid using the name ‘Blender', especially not as first part of the name. Blender Foundation wishes to distinguish official products or services that way. For example: Blender Conference, Blender Extensions, Blender ID, etc.
> Instead, using your own name or brand is always preferred and will work in the long run much better for yourself as well.
> 
> Exceptions apply though. For brands that have been well established for a long time already (for example blenderartists.org), Blender Foundation will specifically not complain when it’s about free/open/gratis products or services that fully align with (and support) Blender’s mission.
> 
> For content that is published on the official Blender Extensions Platform, we are applying the trademark guidelines more strictly. In order to publish your add-on there, some form of rebrand would be needed.
> 
> A similar conversation happened with BlenderDMX, you can find it here: https://extensions.blender.org/approval-queue/open-stage-blender-dmx/.
> 
> I understand that in the case of BlenderBIM, a long-established product, it might not be very practical or desirable to perform a rename. However, I encourage you to think of ways to do it. The goal is not to frustrate your project, but ensure brand diversity and sustainability in the extensions and services ecosystem that is growing around Blender.
> 
> I’m available to contribute feedback, suggestions or ideas for a rebrand if you are interested. 
> 
> Thank you for understanding.
> 
> Best regards,
> Francesco

I responded with:

> G'day!
> 
> Thanks Francesco for the clear reply! I completely understand that it's important to distinguish official products and services from community-led initiatives. I hope we can probably take a similar route to BlenderDMX - that preserves the established name as much as possible but still makes it clear it is part of the community ecosystem.
> 
> Is this a possibility?
> 
>  - On extensions.blender.org, we'll publish under the name "BIM" (just as BlenderDMX is now just DMX)
>  - Does the BlenderBIM.org domain name need to change as well?
>  - On the BlenderBIM.org website, do we keep the name and tagline (last changed in the last conversation with Ton) "BlenderBIM Add-on, An add-on for beautiful, detailed, and data-rich OpenBIM with Blender"? I noticed that the BlenderDMX Add-on website still continues to refer to the add-on as "BlenderDMX". Can we do the same and continue to refer to it elsewhere as the "BlenderBIM Add-on" (which we currently already do) (or, maybe add a space, so that it's Blender BIM Add-on?).
>  - Alternatively, on the BlenderBIM.org website, we currently say "BlenderBIM Add-on", this will be renamed to "BIM Add-on for Blender" or "BIM for Blender". This will be changed throughout whenever it is mentioned (e.g. docs, etc)
>  - Do we need to change our Twitter account? https://x.com/BlenderBIM - that would be quite painful as we'd lose the followers I think.
>  - Do we need to change our LinkedIn account? https://www.linkedin.com/company/blenderbim-add-on/ - I checked and it seems to be able to change this easily.
>  - Do we need to change our LinkedIn group? https://www.linkedin.com/groups/13761286/ - I checked and it seems as though we can change this without losing members, which is great.
>  - There's a lot of hashtags, forum tags, forum posts, academic papers, etc all referring to "#BlenderBIM" or similar, can we continue to refer to it this way, or do we need to change it to something like "#BIMForBlender"
>  - In the source code, our Python modules are all referenced as "blenderbim" which I guess can always change and this is the easy bit because it's not public facing, but we do have it all GPL licensed with the license text boilerplate all currently using the name "BlenderBIM Add-on". Do we change that too? To something like "BIM for Blender"?
> 
> Sorry for the long email, I wasn't quite sure if it was just a matter of keeping the name unambiguous on the extensions.blender.org website or everywhere else as well (it seems BlenderDMX only changed it on the Blender website but maybe this is because it's not yet updated).
> 
> Or maybe I'm just overthinking it and the BlenderBIM Add-on community actually wants a rebrand 🙂 I'll also reach out to the community and ask for their thoughts in the meantime. Changing the name is not a decision I can make myself - it's a big community! I've CC'd a couple of other core devs.
> 
> Kind regards,
> Dion

This is the response:

> Hi Dion,
> 
> Thank you for the kind reply, and for your openness to discuss this. I’ll try to answer all your points. 
> 
>  - On the extensions platform you could rename to “BIM" or “BIM Tools”
>  - When it comes to the website, social media handles (twitter - you won’t lose followers, LinkedIn, etc) and the overall brand, I’d suggest that you align with the new name, as it will reduce confusion. It might be good to check with your community for input on a rename.
>  - "BIM for Blender” would be ok for the website, the code, etc, but as I mentioned, if you pick something else it might be better to have consistency there.
>  - It’s great that you have your own logo already
> 
> Let me know if I can help you further with this. 
> 
> Best regards,

Francesco

**Comment by aothms** [comment]
Just to put this out there: One additional thing that was always confusing was that we have blenderbim being developed within the ifcopenshell repository. One way to resolve both sides of this is to rename blenderbim to "IfcOpenShell Editor" or similar alternatives.

But tbh I think a rename at this point is rather painful. There's quite some awareness and recognition already among users (ifcopenshell is more recognized among devs I guess).

**Comment by Moult** [comment]
Agreed - it's all pretty painful but early is better than later and Blender has the rights for their name, the least painful rename is the rename to just "BIM" Add-on, and keep the domain name, but I'm unsure if that's acceptable by the Blender Foundation.

Slightly less painful to drop it altogether and just make it IfcOpenShell, but mixing the domains is painful. IfcOpenShell has a dev audience, and Joe the BIM Modeler wants to see a picture of walls and pipes, not C++ compilation instructions :) Maybe https://ifcopenshell-blender.org/ or something? Dunno. Let's keep the name suggestions to https://community.osarch.org/discussion/2436/rebranding-the-blenderbim-add-on-vote-for-a-new-name/

**Comment by aothms** [comment]
Ah sorry, I missed that link. Yeah I agree at the very least it would be need to be a subdomain, like `construct.ifcopenshell.org` or `editor.ifcopenshell.org`. But I also agree an actual "name" probably resonates better with the audience and also is more flexible in the long run as it's not tied to another product.

**Comment by cvillagrasa** [comment]
Hi! I just wanted to say that I agree with Thomas in that a rename would be very painful...

It's understandable that Blender wants to keep their official branding separate from uncontrolled addons taking advantage of the Blender trademark. However, I believe there will need to be exceptions, and due to the way they are phrasing their new requirements (not enforcing), I'd say they might be open to it. Have we conveyed the importance of the AEC industry, the fact that BlenderBIM has the potential to compete against Autodesk Revit (3000$ license per year), that we're using OpenBIM / IFC? and the fact that from our side, we would be totally in for a deeper collaboration with Blender Core?

I deem this is a good moment to bring back [the section cut proposal](https://blender.community/c/rightclickselect/W3fbbc/), which hasn't been attempted in 4 years. Maybe we could propose to divert resources to Core for them to develop these kind of things?

Also, looking at other examples, such as [DMX](https://extensions.blender.org/approval-queue/open-stage-blender-dmx/), it looks like they are just renaming from BlenderDMX to DMX extension, while keeping their domain [blenderdmx.eu](blenderdmx.eu)... are we less "official" than DMX? why are we rushing to buy new domains / ask community for a new name? Has the last question to Francesco / Blender Foundation, asking for clarification regarding the [blenderbim.org](blenderbim.org) domain, been answered?

Maybe by handling this slightly differently with the Blender Foundation, we could keep the colloquial BlenderBIM naming, while officially being the BIM extension for Blender ;)

**Comment by Moult** [comment]
> I deem this is a good moment to bring back [the section cut proposal](https://blender.community/c/rightclickselect/W3fbbc/)

Slightly offtopic but this has been implemented now in BBIM in the Explore Tool.

> Has the last question to Francesco / Blender Foundation, asking for clarification regarding the [blenderbim.org](https://github.com/IfcOpenShell/IfcOpenShell/issues/blenderbim.org) domain, been answered?

No answer yet.

**Comment by cvillagrasa** [comment]
> Slightly offtopic but this has been implemented now in BBIM in the Explore Tool.

Supercool! But Alt + B in Core Blender hasn't changed, has it? I just tried it and it works in Solid and Wireframe viewport shadings. Amazing guys, no idea how you have done it.

I don't think it is offtopic, though. The thing is that 4 years ago, BlenderBIM could have had a massive benefit if Blender Core had broadened the possibilities of Alt + B, and arguably, had that feature been developed, Blender itself would have improved in other fronts as well. And the result is that we have not been able to fully convey the importance of this to the Core team (and/or they don't have resources for everything, sure, which is why I always suggest bounties for these features). And for 4 years, you guys have dedicated effort to the shader trick and so on, which was never a definitive solution. A better connection with the Blender Foundation could have prevented that.

> No answer yet.

Ok Dion, but then I don't understand why everyone's choosing a name at the rebranding thread at OSArch. If I'm allowed to read between the lines, my take is that the Blender Foundation would be open for BlenderBIM to keep the domain, as it appears that will happen with DMX. But maybe they just need that we ask for it with strong arguments supporting it (GOTO the 2nd paragraph of my previous comment ;).

**Comment by Moult** [comment]
> If I'm allowed to read between the lines, my take is that the Blender Foundation would be open for BlenderBIM to keep the domain, as it appears that will happen with DMX.

I have asked about this option, but I don't have an answer yet. My interpretation is that although they might turn a blind eye to it and be OK with it, it's not ideal for them. I'll give more thoughts in the forum thread to keep this issue more spartan with email records.

**Comment by Moult** [comment]
Response from Francesco :)

> Hi Dion,
> 
> As we work to improve the communication of Blender's trademark guidelines, there might be a statement that discourages using the name “Blender” in a domain name. We won’t be getting out of our way to prevent people from doing this, but if you ask about it, I’d be pointing to the guideline. I would not complain about bimforblender.org.
> 
> However I’d be very happy if you manage to pick an original name together with your community!
> 
> Best regards,
> Francesco

**Comment by danielraziel** [comment]
> > I deem this is a good moment to bring back [the section cut proposal](https://blender.community/c/rightclickselect/W3fbbc/)
> 
> Slightly offtopic but this has been implemented now in BBIM in the Explore Tool.
> 
> > Has the last question to Francesco / Blender Foundation, asking for clarification regarding the [blenderbim.org](https://github.com/IfcOpenShell/IfcOpenShell/issues/blenderbim.org) domain, been answered?
> 
> No answer yet.

I came here to suggest BBIM name which you already mentioned. it keeps the logo the same, has the essence of blender in it and shows the BIM functionality as well.

**Comment by volkerkrieger** [comment]
would BIM4Blender do it?

**Comment by volkerkrieger** [comment]
@Dion: that would be easier to explain to our clients that we have gained just lately......

**Comment by dion** [comment]
Don't care, I quit this project, remove me now
