### ISSUE TITLE
IfcOpenshell - Compiling on *nix

### ISSUE THREAD

**Issue by adurukan** [IfcOpenShell/IfcOpenShell#773]
Hello,
I feel like I am missing out sth extremely simple but here goes nothing:
I have created a conda environment and were doing all the builds with this environment activated. My systems is Ubuntu 16.04. I have completed steps 1, 2b, 3, and 4 under compiling on nix. In step 5, it says to go to the ifcopenshell folder. I simply download IfcOpenShell-python for python 3.7 64bit Linux which is 0.6.0 version from [http://ifcopenshell.org/python](url). My question is when I go to ifcopenshell folder and run 
```
cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ \
      -DOPENCOLLADA_INCLUDE_DIR="/usr/local/include/opencollada" \
      -DOPENCOLLADA_LIBRARY_DIR="/usr/local/lib/opencollada"  \
      -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/
```
I get an error saying that 

> CMake Error: The source directory "/home/alpay/Documents/hiwi2/cmake" does not exist. 

In anyways, the ifcopenshell folder that I have do not contain CMakeLists.txt file as well. I have tried to follow the way it was listed in the readme file. So for me,
I have ifcopenshell and oce folders under hiwi2 and under oce/build, I have OpenCOLLADA.
Can anyone point me in the right direction? I feel like downloading the ifcopenshell folder isn't the way but I do not simply get an ifcopenshell folder in my site-packages.

Also, my ultimate goal is to be able to use IFC 4 files with ifcopenshell. If the error above is fixed, do I just need to modify 
`cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ \
      -DOPENCOLLADA_INCLUDE_DIR="/usr/local/include/opencollada" \
      -DOPENCOLLADA_LIBRARY_DIR="/usr/local/lib/opencollada"  \
      -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/`
as
`cmake ../cmake -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ \
      -DOPENCOLLADA_INCLUDE_DIR="/usr/local/include/opencollada" \
      -DOPENCOLLADA_LIBRARY_DIR="/usr/local/lib/opencollada"  \
      -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/ \
      --DIFC4=On -DCOLLADA_SUPPORT=Off`
?? Appreciate the help guys.

**Comment by jrojoCI3** [comment]
Hi @adurukan,
It's just a fast try, but I would say there's nothing wrong with your lines and what seems to fail is the actual direction of cmake. You should be executing the command when inside the build folder, somewhere like `/home/alpay/Documents/hiwi2/IfcOpenshell/build/` (you will likely have to create it), so when you call `cmake ../cmake/` it refers to `/home/alpay/Documents/hiwi2/IfcOpenshell/cmake`, which actually exists (or at least should).

**Comment by adurukan** [comment]
I was simply in the wrong path.
