### ISSUE TITLE
No path created when converting to SVG

### ISSUE THREAD

**Issue by ayblaq** [IfcOpenShell/IfcOpenShell#775]
Hi, 
I tried to convert ifc to svg using IfcOpenshell, however no paths are generated. The Ifc file consist of ifccontrollers and ifcterminals I can send the IFC file confidentially if need be.

**Comment by Stinkfist0** [comment]
Hi. The FAQ section probably answers your question: https://github.com/IfcOpenShell/IfcOpenShell/wiki
