### ISSUE TITLE
Geometry has wrong units from IfcPolygonalFaceSet

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#776]
Attached is a series of small minimal test cases. When I use the geom iterator to get a shape, I get the results in meters, which is what I expect - except for a particular IfcPolygonalFaceSet - where the results are in millimeters (all other objects still return meters).

[testcases.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4137705/testcases.zip)

Attached image shows what the correct output should be (walls floating over the perimeter of an irregularly shaped IfcSite plane):

![correct-result](https://user-images.githubusercontent.com/88302/73514416-c5c9f280-4445-11ea-8f40-092232e3aadd.PNG)

Shown below is what is seen in Blender (site is 1000 times larger, so it extends off the screen):

![image](https://user-images.githubusercontent.com/88302/73514461-f578fa80-4445-11ea-9fff-062f7d4085f7.png)

The code below allows you to replicate the issue without needing a graphical viewer - it just prints out the verts, and you will see that the vert coordinates of the IfcSite are still in MM.

```
import ifcopenshell
import ifcopenshell.geom

f = ifcopenshell.open('ifc4-broken.ifc')
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, f)
iterator.initialize()

def process_shape(shape):
    shape = iterator.get()
    element = f.by_id(shape.guid)
    print(element)
    print(shape.geometry.verts)
    print('\n\n')

while True:
    process_shape(iterator.get())
    if not iterator.next():
        break
```

I checked a few other viewers and they display correctly, so I think this is a bug in IfcOpenShell, not the IFC file.

**Comment by aothms** [comment]
> so I think this is a bug in IfcOpenShell, not the IFC file.

Absolutely correct, thanks for reporting.
