### ISSUE TITLE
One question comes from IfcOpenShell-Python beginners.

### ISSUE THREAD

**Issue by keleisi2001** [IfcOpenShell/IfcOpenShell#787]
I have already studied the cases described in Mr. Dion's blog.  I don’t have any more study materials at the moment.

Has anyone other articles about IfcOpenShell-Python? I would like to learn more cases and operations.

**Comment by keleisi2001** [comment]
Two weeks have passed. Does anyone want to give me some advice?

**Comment by Moult** [comment]
If you had a specific question, perhaps we could try to answer it here, or on the IfcOpenShell forums? Other potentially related places to ask a specific question might be the https://community.osarch.org/ or the buildingSMART forums?

**Comment by keleisi2001** [comment]
> If you had a specific question, perhaps we could try to answer it here, or on the IfcOpenShell forums? Other potentially related places to ask a specific question might be the https://community.osarch.org/ or the buildingSMART forums?

OK I try to ask in OSARCH. Thx
