### ISSUE TITLE
Colors of some elements are not displayed correctly after conversion

### ISSUE THREAD

**Issue by MassMachinery** [IfcOpenShell/IfcOpenShell#789]
Hello,

I am experiencing problems with retaining the colors of the original .ifc after conversion to .dae.
As depicted in the images some of the colors are still correct, however some are lost and displayed as black.
For us this is important because our customers sometimes need the correct colors because they might indicate the diameter of bars or other relevant information.
Is this a bug or are there specific requirements for colors to be correctly converted? If the latter is true what specifically are those requirements so that we can communicate those to our customers.

I have also sent the model to models@ifcopenshell.org

Thanks in advance!
![bim_vision_x64_9E7HjdM5sX](https://user-images.githubusercontent.com/7532951/74335238-11f92900-4d9c-11ea-867f-9938048224a8.png)
![Unity_nkogBQ5tPf](https://user-images.githubusercontent.com/7532951/74335240-1291bf80-4d9c-11ea-8c3a-8bea9773c73f.png)

**Comment by MassMachinery** [comment]
Has there been any progress on this issue?

**Comment by Moult** [comment]
Can I get a test file so I can test it? dion@thinkmoult.com

**Comment by Moult** [comment]
@MassMachinery do you by any chance still have the file for us to test? If not, we'll close this bug in a week.
