### ISSUE TITLE
 No schema named IFC20_LONGFORM

### ISSUE THREAD

**Issue by yafeearun** [IfcOpenShell/IfcOpenShell#792]
Hi 

I tried to convert a ifc file,but it returns

Log:
[Error] No schema named IFC20_LONGFORM
[Error] No support for file schema encountered (IFC20_LONGFORM)
[Error] Unable to parse input file 'building.ifc'

kindly help me to short out this

and i'm using
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)

**Comment by aothms** [comment]
Supported schemas in IfcOpenShell are IFC2X3 and IFC4. With parsing only for 4X1 and 4X2. Your `IFC20_LONGFORM` is a schema from 1999 and not supported. Likely not in any of the software currently around. You can try to rename the schema definition in the file to IFC2X3 and see if part of the file converts successfully.

**Comment by yafeearun** [comment]
hi @aothms

may i know the supported schema types?

**Comment by Moult** [comment]
@yafeearun  did this answer it?

> Supported schemas in IfcOpenShell are IFC2X3 and IFC4. With parsing only for 4X1 and 4X2.

**Comment by yafeearun** [comment]
@Moult the mentioned schemes are works but  not IFC20_LONGFORM schema, may i know list of supported schemas, it'll useful for me and i can convey it to my team.

**Comment by Jesusbill** [comment]
@yafeearun the answer to your question has been given already twice.

You asked for the supported schemas. The supported schemas are: IFC2X3 and IFC4

 IFC20_LONGFORM  is not a supported schema so it will not work

**Comment by yafeearun** [comment]
@Jesusbill thanks
