### ISSUE TITLE
ifcconvert not working

### ISSUE THREAD

**Issue by yafeearun** [IfcOpenShell/IfcOpenShell#794]
./IfcConvert: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./IfcConvert) ./IfcConvert: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./IfcConvert)

getting this while run ifcconvert 

how to fix this

**Comment by Moult** [comment]
Perhaps you have an old version of GCC on your distro (RHEL, perhaps? They are usually quite old)

If you compile a newer version, you can then update your `LD_LIBRARY_PATH` value and then try run IfcConvert again.

On Gentoo, this is where I can find my `libstdc++.so.6`, and verify that it supports the 1.3.8 ABI:

```
$ strings /usr/lib64/gcc/x86_64-pc-linux-gnu/9.2.0/libstdc++.so.6 |grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_1.3.10
CXXABI_1.3.11
CXXABI_1.3.12
CXXABI_TM_1
CXXABI_FLOAT128
```

I hope it helps - I'm not an expert in this.

**Comment by yafeearun** [comment]
@Moult thanks for your support, fixed by updating g++ version
