### ISSUE TITLE
how to use ifcconvert in server

### ISSUE THREAD

**Issue by yafeearun** [IfcOpenShell/IfcOpenShell#795]
i tried to run IfcConvert in server but getting
/home/XXXXX/public_html/uploads/models/2/46bb1a56188cfcc943358010e3c82782.ifc: line 1: ISO-10303-21: command not found /home/XXXX/public_html/uploads/models/2/46bb1a56188cfcc943358010e3c82782.ifc: line 2: HEADER: command not found /home/XXXXX/public_html/uploads/models/2/46bb1a56188cfcc943358010e3c82782.ifc: line 3: /0: Permission denied /home/XXXX/public_html/uploads/models/2/46bb1a56188cfcc943358010e3c82782.ifc: line 4: syntax error near unexpected token `(' /home/XXXXX/public_html/uploads/models/2/46bb1a56188cfcc943358010e3c82782.ifc: line 4: ` * from STEP Tools, Inc. (www.steptools.com) '

**Comment by Moult** [comment]
How are you running IfcConvert? At a glance it looks as though you are trying to execute the IFC file itself. Instead, the IFC file should be given as a parameter to IfcConvert, like so:

`IfcConvert /home/XXXXX/public_html/uploads/models/2/46bb1a56188cfcc943358010e3c82782.ifc`

Ensure that the IFC file is not executable, i.e.:

`chmod -x /home/XXXXX/public_html/uploads/models/2/46bb1a56188cfcc943358010e3c82782.ifc`

**Comment by yafeearun** [comment]
thanks @Moult . it's works
