### ISSUE TITLE
Encoding issues in file name

### ISSUE THREAD

**Issue by BalintBende** [IfcOpenShell/IfcOpenShell#797]
Hello,

We are trying to use IfcConvert and invoke it from command line. In case of special character in names for example Chinese or Cyril characters occurs a `COLLADASW::StreamWriterException`.

Could you recommend a solution for this? Or should we avoid these kinds of characters?

`IfcConvert -v -y --use-element-guids "$IFCPATH" "$OUTPUT_FOLDER/$FILENAME.dae"`

Thanks in advance,
Cheers, Balint

**Comment by Moult** [comment]
If I'm reading the referenced issue correctly, it was later determined to be a docker mounting problem, so I guess this can be closed. Feel free to reopen if it isn't the case.
