### ISSUE TITLE
Latest build of BlenderBIM Add-on

### ISSUE THREAD

**Issue by lgtrombetta** [IfcOpenShell/IfcOpenShell#800]
Hi there,

First, let me thank you for the great work on this add-on. It's looking good!

Which is the preferred way for getting the latest build? In https://blenderbim.org/builds/ I see the latest available one is from over a month ago (Jan 23 2020), but a lot of commits happened since then which I would like to test. 

Cheers.

**Comment by Moult** [comment]
Just released a new build today :)

When #755 is solved the documentation will explain how to patch your install if you want to try the bleeding edge stuff. It's all just Python so you can simply replace the files from the master branch.

**Comment by lgtrombetta** [comment]
Great, thanks!
