### ISSUE TITLE
convert to xml  <IfcElementQuantity> have two same attribute

### ISSUE THREAD

**Issue by veyvin** [IfcOpenShell/IfcOpenShell#802]
[CBM.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4273810/CBM.zip)

![image](https://user-images.githubusercontent.com/6776758/75651973-e4b1e380-5c94-11ea-8f14-380c1076d2ff.png)

<IfcElementQuantity> have two same attribute

**Comment by aothms** [comment]
You're right for some reason the code for that was duplicated. Thanks for reporting.
