### ISSUE TITLE
Exception thrown when running the IfcOpenHouse example

### ISSUE THREAD

**Issue by StefanSkrobanski** [IfcOpenShell/IfcOpenShell#805]
Hi, 

I'm not having any luck running the IfcOpenHouse example. An exception is thrown in  `IfcFile::addEntity(IfcUtil::IfcBaseClass* entity)` which states that the entity schema is IFC2x3 but the file schema is IFC4.

Am I doing something wrong?

Thanks

**Comment by aothms** [comment]
Sorry for the late reply. You're fully correct, not sure how long that must have been broken. Fixed in https://github.com/IfcOpenShell/IfcOpenShell/commit/3e55297eb0e79f48f1589e3a31212154e73a3522

**Comment by StefanSkrobanski** [comment]
Thank you!
