### ISSUE TITLE
When will a new version be pushed to Conda?

### ISSUE THREAD

**Issue by lawsonAGMT** [IfcOpenShell/IfcOpenShell#809]
The most recent version of ifcopenshell in conda-forge (v0.6.0b0, py38h67e710d_5, MacOS) is not able to mesh a simple ifc file. However, the release on the website [IfcOpenShell-python for python 3.7 64bit OSX](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.6.0-e44221c-macos64.zip) works great.

**Comment by aothms** [comment]
@looooo is the maintainer there, see https://github.com/IfcOpenShell/IfcOpenShell/issues/582 I'm fine with tagging the current v0.6.0 head if that helps.

**Comment by lawsonAGMT** [comment]
Thanks for the quick response! That would be helpful.

@looooo is there anything else that needs to be done?

**Comment by looooo** [comment]
just trying to update ifcopenshell 0.6.0 for conda-forge and running into various build issues. Maybe somomne from ifcopenshell can help fix them:
https://github.com/conda-forge/ifcopenshell-feedstock/pull/11

**Comment by looooo** [comment]
seems like a libxml2 linking error:

```
ImportError: /home/conda/feedstock_root/build_artifacts/ifcopenshell_1599731259205/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.7/site-packages/ifcopenshell/_ifcopenshell_wrapper.so: undefined symbol: xmlSAXUserParseFile
```

@aothms

**Comment by looooo** [comment]
windows fails at cmake-configuration:
```
CMake Error at D:/bld/ifcopenshell_1599731489154/_h_env/Library/lib/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package):
  Found package configuration file:

    D:/bld/ifcopenshell_1599731489154/_h_env/Library/lib/cmake/boost_system-1.72.0/boost_system-config.cmake

  but it set boost_system_FOUND to FALSE so package "boost_system" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * boost_system.lib (shared, default on Windows is static, set
  Boost_USE_STATIC_LIBS=OFF to override)
```
