### ISSUE TITLE
Error on Import 

### ISSUE THREAD

**Issue by CarpgianeDS** [IfcOpenShell/IfcOpenShell#810]
Have created exported IFC in Revit and Imported it into Blender 

Get errors on import and building is partially imported.

I'm added the error log from Blender.

I'm on Blender 2.82

[Import Error.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4337962/Import.Error.txt)

**Comment by aothms** [comment]
Thanks for reporting. My guess is this is fixed by @Moult in https://github.com/IfcOpenShell/IfcOpenShell/commit/8008ad16b1acf6a5699bfb9d4e2aaeee1d6e1a92 It's just a matter of providing new builds or you can update your code locally yourself according to the changes in that commit.

**Comment by Moult** [comment]
Yes, sorry for the build with the bug :) I'll release a new version soon!
