### ISSUE TITLE
Python meshing difference with 0.6.0 latest and version on website

### ISSUE THREAD

**Issue by lawsonAGMT** [IfcOpenShell/IfcOpenShell#811]
Hey, it's me again.

I thought I had narrowed down the problem to a difference between 0.6.0 on the [website](http://ifcopenshell.org/python) and 0.6.0b0 in conda-forge. However, now that 0.6.0 is in conda, I'm still running into the same problem (described below).

Given [this](https://github.com/IfcOpenShell/IfcOpenShell/files/4350033/complex_geom.ifc.zip) ifc file, I attempt to convert it to a single triangle mesh using an adapted version of the blender importer. [code here](https://gist.github.com/lawsonAGMT/bf29562e0358f0ac498f2e68c912dddc)

When using [IfcOpenShell-python for python 3.8 64bit OSX](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-38-v0.6.0-4df2fea-macos64.zip) hosted on the ifcopenshell website, I get the following, expected, result:
<img width="791" alt="Screenshot 2020-03-18 12 09 20" src="https://user-images.githubusercontent.com/59849832/76981839-7c5c3680-6911-11ea-8c6d-b633703db57d.png">

However, when I use 0.6.0 or 0.6.0b0 in conda-forge, I get this:
<img width="671" alt="Screenshot 2020-03-18 12 09 43" src="https://user-images.githubusercontent.com/59849832/76981828-78c8af80-6911-11ea-9617-d36bf569540b.png">

Does anyone have any idea what is going on or where I might look to narrow down the source?
Tagging @looo as well

**Comment by Moult** [comment]
If it helps at all, the master branch of the Blender add-on works as expected. (by the way, the Blender importer on the website, is very outdated, the newest version is https://blenderbim.org/ - and I will release a new build today)

The BlenderBIM Add-on uses the latest build from the IfcOpenBot/IfcOpenShell repo: https://github.com/IfcOpenBot/IfcOpenShell/commit/e44221c9c2f65f062e3f9aa7af28c22cce655bc5

**Comment by lawsonAGMT** [comment]
That looks like an interesting tool, thanks for pointing it out.

Just to clarify though, I'm not writing a Blender importer, I'm trying to integrate mesh conversion in a standalone python application being used for other purposes. I need more control than the ifcconvert app provides out of the box.

**Comment by Moult** [comment]
That sounds cool :) Feel free to steal some code [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/import_ifc.py) :)

To package the BlenderBIM Add-on, I use the IfcOpenBot builds (not Conda) for IfcOpenShell, and then I use Conda builds for other deps like Python-OCC, and OCE. [This Makefile](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/Makefile) might help. I have not personally tried the Conda build of IfcOpenShell, but just thought I'd add my 0.02$ :)

**Comment by lawsonAGMT** [comment]
Hmm I tried modifying my script slightly to do it more like yours to no avail.

There must be something different in the build between the conda version and IfcOpenBot builds.

**Comment by aothms** [comment]
The IfcOpenBot builds have a static version of occt (7.3.0p3) compiled into it. The conda builds rely on external dynamic libraries. First thing to check would be what occt version you are using and if up/downgrading helps. Second, for debugging, it'd be good to know if when using the PythonOCC viewer you get similar results as when using the meshes.

**Comment by lawsonAGMT** [comment]
Thanks I will look into those suggestions and let you know

**Comment by Moult** [comment]
@lawsonAGMT there are now updated Conda builds which may help too: https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#conda

Closing as v0.7.0 is significantly later that what was reported here, and I tested again with the latest version and the geometry is all processed correctly.
