### ISSUE TITLE
Can I get a usage example of IfcConvert --model-offset ? 

### ISSUE THREAD

**Issue by xeolabs** [IfcOpenShell/IfcOpenShell#815]
Hi, can I get an example of how to use ````IfcConvert```` option ````--model-offset````?

This gives "input file not specified", which makes sense:

````./IfcConvert -v -y  --model-offset=-10000.0;100.0;100.0 input.ifc output.dae````

This gives "Invalid use of --model-offset":

````./IfcConvert -v -y  input.ifc output.dae --model-offset=-10000.0;100.0;100.0````

I'm not sure what's invalid there.

Thanks

**Comment by Stinkfist0** [comment]
I don't have IfcConvert available right now but I think you must use `IfcConvert input.ifc output.dae --argument1 --argument2...`

**Comment by aothms** [comment]
My guess is that this is a locale issue. `--model-offset=-10000.0;100.0;100.0` looks correct to me. Are you on a German speaking laptop @xeolabs? Can you try with commas instead so `--model-offset=-10000,0;100,0;100,0`. If this is indeed the issue we should either document users to use their current locale or make the code locale independent.

**Comment by xeolabs** [comment]
Yeah I'm on a German locale, at least this is what ubuntu locale command tells me:
````
locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
````
However
````bash
./IfcConvert -v -y  --use-element-guids input.ifc output.dae --model-offset=-10000,0;100,0;100,0
````
Still gives me
````
[Error] Invalid use of --model-offset
````

Actually BTW what I'm likely to use instead is either the ````--site-local-placement```` or ````--building-local-placement````, which are working nicely, or maybe ````ifcPatch```` if ````IfcConvert```` struggles with big models (so this is not a pressing issue for me BTW).

**Comment by xeolabs** [comment]
(Accidentally close this issue)

**Comment by Moult** [comment]
@xeolabs trying to get a bit of closure on this, perhaps it is your shell? Have you tried putting in quotes to make sure its treated as one argument? E.g. `--model-offset="-10000.0;100.0;100.0"`

**Comment by katSchmid** [comment]
Does work for me on obj, ignored for glb?

**Comment by aothms** [comment]
@katSchmid I just checked converting both to glb and obj with --model-offset and imported in Blender. The result was the same. Can you elaborate?

**Comment by xeolabs** [comment]
@Moult this works for me, thanks, I'll close.
 
--model-offset="-10000.0;100.0;100.0"

**Comment by katSchmid** [comment]
Interesting let me re-try glb
