### ISSUE TITLE
SweptSolid missing faces

### ISSUE THREAD

**Issue by FreakTheMighty** [IfcOpenShell/IfcOpenShell#816]
Apologies for [double posting](https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/7a7839a1ba) from the forum, but I think it makes more sense to track this as an issue as I've found some existing tickets that seem related.

---

## Overview
I'm finding that an IfcBeam is missing faces. It should be a U shape, but `create_shape` is generating an L instead. I've tested with `IfcConvert` 0.6.0 as well as through some custom python code.

`IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)`

## Sample Images
Here's what it looks like with the missing faces:
![Missing Faces](https://i.ibb.co/6YT6cnb/Annotation-2020-03-26-085454-tif.jpg)

And this was generated using assimp and contains the full geometry.
![Correct Model](https://i.ibb.co/3rGnjrq/Capture.png)

## Logs
```
[Notice] exclude entities IfcOpeningElement IfcSpace
[Warning] {00i6wSobrD$B7A4a3x0PB8} Self-intersections with 2 cycles detected
[Warning] {00i6wSobrD$B7A4a3x0PBA} Self-intersections with 2 cycles detected
[Warning] {00i6wSobrD$B7A4a3x0Qri} Self-intersections with 2 cycles detected
[Warning] {00i6wSobrD$B7A4a3x0Qrk} Self-intersections with 2 cycles detected
[Warning] {00i6wSobrD$B7A4a3x0Qs3} Self-intersections with 2 cycles detected
[Warning] {00i6wSobrD$B7A4a3x0Qs5} Self-intersections with 2 cycles detected

```
## Sample IFC
[small-framing.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4394406/small-framing.zip)

**Comment by FreakTheMighty** [comment]
I'm not sure if these are related, but there seems to have been recent issues related to `wire_intersections`. In this issue, nothing crashes, but it does seem like intersection detection may not be handling things in an ideal way.

Two things come to mind.

1. When it detects an intersection, it grabs the "largest" section. Is there a way it could process both section?
1. Is it possible that these elements are so thin that it is detecting an intersection where there it shouldn't?

https://github.com/IfcOpenShell/IfcOpenShell/issues/768

**Comment by FreakTheMighty** [comment]
Commenting out the `wire_intersection` fixes the bottom tracks in the sample file above ☝️ . I don't see any side effects, but obviously it serves some purpose.

https://github.com/IfcOpenShell/IfcOpenShell/blob/d9805185eeba151b256df54c3dcc3f71fd3416f2/src/ifcgeom/IfcGeomFunctions.cpp#L1081-L1084

Do you have a repo of sample files to test against? I imagine that there's a lot of whack-a-mole when it comes to fix these sort of problems - what works for one file breaks another.

**Comment by FreakTheMighty** [comment]
@aothms I bumped into your [commit](https://github.com/IfcOpenShell/IfcOpenShell/commit/df81490f86798153f253d55cfec9231cf5a5fabe) that seems to begin to address the bug in this issue. Giving it a test, it didn't quite fix the problem in my sample. I've stripped the sample down to just a single offending track. [single-bottom-track.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4472816/single-bottom-track.zip)

Stepping through the code I see that for some portions of the curve, the `IsParallel` check is true. However, it seems that for other portions it is *nearly* true. For example, if I'm reading this correctly the `u11` and `u22` values are exactly the same and thus parallel.
![image](https://user-images.githubusercontent.com/247092/79180446-96cde680-7dcf-11ea-869d-3fdf45391aac.png)

However, for this portion, they are off by 1/1000th and so are not parallel.
![image](https://user-images.githubusercontent.com/247092/79180485-b49b4b80-7dcf-11ea-8c78-fcfaec4d1e81.png)

---

I see that `ecc.Extrema()` has a `SetTolerance` method, [here](https://www.opencascade.com/doc/occt-7.0.0/refman/html/class_extrema___ext_c_c.html#afe778b0348a697b77d451409bb684e7d
). I wonder if this could be adjusted to relax the `IsParallel` check.

**Comment by aothms** [comment]
> Do you have a repo of sample files to test against? I imagine that there's a lot of whack-a-mole when it comes to fix these sort of problems - what works for one file breaks another.

Yes that's very true. Sorry for the delay in replying. Thanks for the detailed investigations.

The issue that triggered this whole wire_intersection thing is https://github.com/IfcOpenShell/IfcOpenShell/issues/297 and was later made more aggressive (in the sense that a rather large tolerance value is used to flag almost-intersections as intersections) in https://github.com/IfcOpenShell/IfcOpenShell/issues/376 (and probably a couple more)

The thing is that OCCT is also evolving and some fixes for issues made in the past, might in fact be no longer necessary in more recent versions. Unfortunately this is something we don't actively track.

You bring up a valid point. Why only once cycle is kept. It's simply only because that's how the API is structured. A single face is expected. But we also since then have introduced triangulation for non-planar face boundaries in which case the result is also a compound of multiple faces. So we should look into doing that in this case as well.

**Comment by FreakTheMighty** [comment]
@aothms no worries on the delay. As always, thanks for taking the time and building this sweet tool!

Thank you for linking those other issues in. It does seem like your change improved things for many of the bottom tracks in the file.

If you had to guess, which way would you take this? Would you remove the `wire_intersection` check with the hope that OCCT has improved, continue to make the `wire_intersection` more clever or leave things as is treating artifacts in the bottom track as a "lesser of many evils"?

**Comment by aothms** [comment]
> You bring up a valid point. Why only once cycle is kept. It's simply only because that's how the API is structured. A single face is expected. But we also since then have introduced triangulation for non-planar face boundaries in which case the result is also a compound of multiple faces. So we should look into doing that in this case as well.

As it turned out, multiple faces was not so prohibitive in this case as there is also for example an IfcCompositeProfileDef. So in case of IfcArbitraryClosedProfileDef we can also keep multiple.

**Comment by FreakTheMighty** [comment]
Ah, very cool! I may have a chance to test this soon. When I've got results I'll update you here.

**Comment by FreakTheMighty** [comment]
@aothms it seems like that hasn't fixed this particular case. I grabbed the build from [here](https://github.com/IfcOpenBot/IfcOpenShell/commit/c15fdc7fa92df959cd563a1f151cdb3b399e1b72) and it's still missing one side of that bottom track and one lip of the vertical frame.

![image](https://user-images.githubusercontent.com/247092/91462055-5ab39380-e84f-11ea-9b46-0536869ae0e2.png)

**Comment by FreakTheMighty** [comment]
Not sure why, but the bottom track does indeed seem to be fixed now, don't know how I missed that. I am still, however seeing missing faces on the vertical frame. 
![image](https://user-images.githubusercontent.com/247092/106041369-53fca700-60a1-11eb-9b24-571de284cc8f.png)

Do we still need to perform that `wire_intersections` check? When I remove that, things seem to work nicely. I get this result.
![image](https://user-images.githubusercontent.com/247092/106041540-8ad2bd00-60a1-11eb-8bc0-a2ec9ba5ca67.png)
