### ISSUE TITLE
Compiling on *nix instructions

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#83]
The README doesn't mention the `nix/build-all.sh` script. Should it or is the script considered to be experimental/w.i.p. currently?

**Comment by Stinkfist0** [comment]
The script seems to be building 5 different Python versions which is probably an overkill for the regular user at least.

**Comment by aothms** [comment]
Yep. The windows and nix build scripts have different main purposes, the latter primarily intended to do the release builds for the website in one go. This is also the main reason why it's not advertised yet in the readme.

Ideally both scripts would be similar in their operation and I agree the main objective should be to facilitate new developers to get a workspace up and running quickly.

**Comment by Stinkfist0** [comment]
Can be closed for now, more fine-grained *nix build scripts are a separate issue.
