### ISSUE TITLE
Exclude entities problem js

### ISSUE THREAD

**Issue by Alex-VH** [IfcOpenShell/IfcOpenShell#833]
### Overview
Hello, I am having a trouble using **IfcConvert 0.6** on my Ubuntu machine.
I am developing a web app with nodejs(12.16.1) and don't manage to use the following option : 
`--exclude=entities IfcOpeningElement`
The command works in a shell but not  when i call it in my script.

### Log
```
Error: Command failed: /path/to/IfcConvert/binary/IfcConvertbinary --use-element-guids /path/to/ifc/file/Test-Maison.ifc /path/to/dae/file/Test-Maison.dae --exclude=entities IfcOpeningElement
[Error] Invalid usage of '--exclude': the argument for option '--exclude' is invalid
```

### Example used:

[Test-Maison.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4456068/Test-Maison.zip)

If details are needed about the script I can give them.

**Comment by Moult** [comment]
Try `--exclude entities IfcOpeningElement` ?

**Comment by Alex-VH** [comment]
When I try `--exclude entities IfcOpeningElement` I got this message:
```
Error: Command failed: /opt/IfcConvert/IfcConvert --use-element-guids /home/alex/Documents/sensor-bim_dev/public/db/convert/IFC/Test-Maison.ifc /home/alex/Documents/sensor-bim_dev/public/db/convert/DAE/Test-Maison.dae --exclude entities IfcOpeningElement
[Error] Unknown option '--exclude entities IfcOpeningElement'
```

**Comment by Alex-VH** [comment]
I find the problem.
As I am using this fonction `execFile(ifcConvertPath, args)` which takes the path to the IfcConvert binary and the arguments of the function in an Array of strings.
The string `'--exclude=entities IfcOpeningElement'` must be divided into two strings as it is two arguments like that : ` '--exclude=entities'` and `'IfcOpeningElement'`.
So the Array looks like : `['pre-arg1','pre-arg2','src','dest','post-arg1','post-arg2']`

Thank you for your time
