### ISSUE TITLE
Support for read and write .ifczip

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#834]
It would be good to start adding different file handler supports for IFC formats - a nice easy one to start with is IFCZIP - it would be great to do `ifcopenshell.open('foo.ifczip')` and `foo.write('bar.ifczip')` and have it all Just Work (TM) :)

... and in the future, ifc{xml,json,sqlite,hdf...} :)

Stephen Leger has some sample code for a quickie implementation on the Python side.

**Comment by s-leger** [comment]
```python
        # filepath is full filename including path and .ifczip extension
        filename, ext = os.path.splitext(os.path.basename(filepath))
        tmp_name = "%s.ifc" % filename
        # temp folder
        tmp_file = os.path.join(tmp_dir, tmp_name)
        with zipfile.ZipFile(filepath, mode='w', compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
            zf.write(tmp_file, tmp_name)
        os.remove(tmp_file)
```

**Comment by aothms** [comment]
Note that ifcxml is supported for reading https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcFile.h#L221 but it's not well tested (is it exposed in Python?). IfcXML is different for ifc2x3 and ifc4 and not really standardized, I think it's mostly hypothetical and not really used in software. But if any of you want to experiment with it, it'd be great.

I think IfcZIP support would be great. Best would be in C++ of course, as then it'd probably mean that we can stream through it and no copy has to be made. For now a tempfile in Python is probably indeed a way to go. Great!

Note that there are some utilities in `import tempfile` for generating tempfile names and getting the system temp dir. `compresslevel=9` is probably too CPU intensive for what it's worth.

In ifcopenshell.parse we can probably autodetect the archive format e.g https://github.com/h2non/filetype.py/blob/master/filetype/types/archive.py#L55

**Comment by Moult** [comment]
Oooh, I'd love to test out IFCXML. I'm not sure if it's exposed in Python.

How easy is it to implement IFCZIP in C++? If you think it might take a while, I'll do the Python workaround for now.

**Comment by aothms** [comment]
> Oooh, I'd love to test out IFCXML. I'm not sure if it's exposed in Python.

Quickly added something, only to `ifcopenshell_wrapper` feel free to connect it to `ifcopenshell.open()` based on extension or in some other form.

https://github.com/IfcOpenShell/IfcOpenShell/commit/42fedf81c4e49f1cb4f3934a0ed9dd2049fad84b

> How easy is it to implement IFCZIP in C++?

Not hard. But don't count on me doing this anytime soon as we have pretty good work arounds. IfcConvert users can just use `unzip` etc.

**Comment by Moult** [comment]
Cheers :) I've put in the workarounds, we can perhaps keep this bug open as a reminder to implement.

I'll wait for the bot build to test IFCXML :)

**Comment by Moult** [comment]
@aothms  just tested out ifcxml - I couldn't get it to work. Am I doing something wrong?

    >>> import ifcopenshell
    >>> import ifcopenshell.ifcopenshell_wrapper
    >>> ifcopenshell.ifcopenshell_wrapper.parse_ifcxml('/home/dion/wall.ifcxml')
    Traceback (most recent call last):
      File "<blender_console>", line 1, in <module>
      File "/home/dion/.config/blender/2.82/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 2398, in parse_ifcxml
        return _ifcopenshell_wrapper.parse_ifcxml(fn)
    RuntimeError: An unknown error occurred

Where `wall.ifcxml` is this file: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/annex/annex-e/wall-with-opening-and-window.ifcxml

I also tested with this file, which resulted in a segfault: https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/brep-model.ifcxml

**Comment by aothms** [comment]
In `wall-with-opening-and-window.ifcxml` there is a:

```
<IfcThermalTransmittanceMeasure-wrapper>0,24</IfcThermalTransmittanceMeasure-wrapper>
```

So it seems the wrong decimal separator is used there.

Then further down in the file. I'm under the impression that when you include a inverse attribute you cannot omit the type name of the entity pointed to. So in IfcOpSh this will work:

```
<IsDefinedBy>
    <IfcRelDefinesByProperties GlobalId="29JB4VSyHEhx7go0x$VxZ2">
        <OwnerHistory xsi:nil="true" href="i2" />
```

But later we encounter:

```
<HasOpenings GlobalId="1nwVYC$VTDeuSc8zbOa89u">
    <OwnerHistory xsi:nil="true" href="i2" />
```

So the relationship node (`IfcRelVoidsElement` in this case) has been completely omitted and immediately starts with attributes.


The other file had a different schema location `http://www.buildingsmart-tech.org/ifc/IFC4x1/final` instead of something under `http://www.buildingsmart-tech.org/ifcXML`. And IfcOpenShell was not expecting a lower case `x` there either (not sure what's valid).

It's also a 4X1 file and the geometry iterator has not been wired up correctly for that. 

Anyway neither of the files crash now anymore, but I think as a community we're pretty far away from reliable ifcXML exchange especially in the IFC4 'dialect'. Feel free to follow up on this with other in the forum or sth.

**Comment by Moult** [comment]
Thanks @aothms ! I will mark this thread as solved (and look forward to retesting once the build bot gets up to it :) ) I'm also following up on the forums for more modern ifcxml examples - I think @jmirtsch wrote an IFC XML exporter, but I could be wrong.
