### ISSUE TITLE
Segfault when iterating geometry through GUINNESS.ifc

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#835]
Not entirely sure how to debug this one, as I can't seem to figure out which element is causing it to segfault. I've emailed the file to @aothms as it isn't to be shared publicly.

Edit: there is a known issue about lacking a IfcSurfaceStyleShading Transparency attribute, but I don't think that it causing the segfault.

**Comment by aothms** [comment]
@Moult if this issue still persists can you send me the file one more time, sorry.

**Comment by Moult** [comment]
Cheers - emailed the download link again.

**Comment by Moult** [comment]
Closing as I have no idea where this file is anymore :)
