### ISSUE TITLE
[Wishlist] 3D Associative Text

### ISSUE THREAD

**Issue by EAzari** [IfcOpenShell/IfcOpenShell#838]
Hi Dion @Moult and Thomas @aothms, I shared this before but it's better I write it here as wishlist

Reference from STEP AP242, which hope Thomas' experience in [STEPcode](https://github.com/stepcode) helps to develop it in IFC too

https://www.cax-if.org/documents/3D-assoc_textRPGv4_a4.pdf

Cheers,
Ehsan

**Comment by aothms** [comment]
Interesting, but what's your rationale for this to prefer this over BCF? As I think community sees IFC mostly as (let's say) physical model and BCF for annotations.

**Comment by Moult** [comment]
I think this is for construction documentation annotation - not BCF which is more issue management I believe. I think associative text can be implemented with https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/schema/ifcpresentationdefinitionresource/lexical/ifctextliteralwithextent.htm - and then associated with any object.

I plan to implement storing documentation annotation in IFC, and so this is something that I will implement sooner or later I believe.

**Comment by EAzari** [comment]
@Moult You're totally right, and it seems that even in STEP AP242 there's `TextLiteralWithExtent` plus some other entities that may be IFC4 has (I'm not sure, so needs investigation)

**Comment by Moult** [comment]
3D text has now been implemented in the BlenderBIM Add-on, allows association to an IFC object, and exports as `IfcTextLiteralWithExtents`.

Closing bug.
