### ISSUE TITLE
Importing ifcopenshell

### ISSUE THREAD

**Issue by glshayaz** [IfcOpenShell/IfcOpenShell#844]
The link http://ifcopenshell.org/python.html is not found to import ifcopenshell now, is there another way to import it?

**Comment by Moult** [comment]
http://ifcopenshell.org/python ?

I don't quite understand the question? Btw, IfcOpenBot also has routine builds of IfcOpenShell python, and the BlenderBIM Add-on also ships with IfcOpenShell python.
