### ISSUE TITLE
IfcDiff - DeepDiff

### ISSUE THREAD

**Issue by e3dEF** [IfcOpenShell/IfcOpenShell#845]
Hi, 
in the IfcDiff.py the try-statement in the diff_element_geometry function always fails, because DeepDiff does not accept the arguments terminate_on_first and skip_after_n. I use the current DeepDiff 4.3.2.

**Comment by e3dEF** [comment]
Nevermind, I just saw that this will added as Enhancement.

**Comment by Moult** [comment]
@e3dEF It uses Moult-flavoured deepdiff: https://github.com/Moult/deepdiff
