### ISSUE TITLE
Section Doesn't Cut Certain Features

### ISSUE THREAD

**Issue by baswein** [IfcOpenShell/IfcOpenShell#846]

**Comment by baswein** [comment]
Sorry I think this was the wrong site to post this.

**Comment by Moult** [comment]
@baswein this was reported and fixed :) https://community.osarch.org/discussion/55/section-cut-not-cutting-certain-objects#latest

**Comment by baswein** [comment]
Thanks. Sorry for the confusion. So I should post issues about BlenderBIM here?

**Comment by Moult** [comment]
Whichever you prefer :)
