### ISSUE TITLE
Segfault of create_shape processing some elements

### ISSUE THREAD

**Issue by RazYo** [IfcOpenShell/IfcOpenShell#849]
In the attached file there are multiple elements that causes segmentation fault, toilets, furniture and more.

their GUIDs:
2bU46R5RT198CoJdWSDvb8
2bU46R5RT198CoJdWSDbTl
2HAjWfo2LCqRaBxs1JcayX
2HAjWfo2LCqRaBxs1JcaXB
2HAjWfo2LCqRaBxs1Jcls6
3ItQQVTGHB$hTW_$8jFHsv
3ItQQVTGHB$hTW_$8jFIKj
3ItQQVTGHB$hTW_$8jEhHz

We are using ifcopenshell for python, version 0.6.0a0.

For our purposes, all we want is not to crash, we have no problem failing the process
or skipping the elements. Until this problem is fixed is there a way to not crash and skip the problematic elements? 

[furniture_partial.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4620949/furniture_partial.zip)

**Comment by aothms** [comment]
Sorry for the late reply. Thanks, I can confirm there are issues with the transfer of some of the surfaces. On my quick test I didn't see any segfaults. What are the exact details of your configuration?

**Comment by aothms** [comment]
Edit: in particular if you're compiling Open CASCADE yourself on Linux be sure to enable exception handling.

**Comment by Moult** [comment]
I cannot replicate any segfaults, tested with latest BlenderBIM:

![image](https://user-images.githubusercontent.com/88302/85075157-124d7900-b201-11ea-9017-c0f2c86fad9c.png)

**Comment by Moult** [comment]
Tested again and still no segfault and no feedback so assuming fixed.
