### ISSUE TITLE
IfcConvert installation bug

### ISSUE THREAD

**Issue by chloesun** [IfcOpenShell/IfcOpenShell#850]
Hello Dev team, I downloaded the IfcConvert for windows (0.6.0 IfcConvert 64bit Windows)  from http://ifcopenshell.org/ifcconvert, and error happened during installation
![bugg](https://user-images.githubusercontent.com/13730281/81857319-19150c00-9530-11ea-9ca1-2297e12a5a71.PNG)

I also downloaded the 0.5.0 version, and same thing happened. 

Has this happened to other users before? I'd be grateful to receive some support to understand the situation. THANK YOU!

**Comment by aothms** [comment]
Hi please try a more recent version such as https://github.com/IfcOpenBot/IfcOpenShell/commit/81b3711c33ae9f0851fad9024ea2a611465e7e1e#comments

**Comment by chloesun** [comment]
@aothms  Thanks for the update, I tried with the latest version and encountered the same issue
![0 6 0](https://user-images.githubusercontent.com/13730281/82365133-3e959000-99de-11ea-9ff2-740afa4788a7.PNG)

**Comment by aothms** [comment]
Seems you execute directly from the zip file? Can you extract the file
first into a normal directory where you have permissions?

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op di 19 mei 2020 20:37 schreef Chloe Sun <notifications@github.com>:

**Comment by Moult** [comment]
Ping @chloesun :) Any updates? Did you try extracting from the ZIP? If no response, assume that the zip was the issue and we'll close this issue in a week.
