### ISSUE TITLE
Code generation procedure of Ifc4x3 

### ISSUE THREAD

**Issue by hu-stefan** [IfcOpenShell/IfcOpenShell#853]
i´m faceing a problem regarding the generation of cpp data with the .exp data.
i execute following command on the command line:
python bootstrap.py express.bnf > express_parser.py && python express_parser.py IFC4x3.exp 
with out an error message, but the only data i obtain is "IFC4x3.exp.cache.dat" and no .cpp nor .h data.
I´m using the python version 3.4.3.
[ContentCach.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4633190/ContentCach.txt)

Any idea were the error could be?

**Comment by aothms** [comment]
In the v0.6.0 branch you need to specify the code generation outputs now. So typically you need to add `header implementation schema_class definitions`

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcexpressparser/README.txt

**Comment by hu-stefan** [comment]
Thank you!
It works fine for the header an the implementation but i guess not for the schema and definitions. There is non such data in the folder.
i get this Error:
Traceback (most recent call last):
  File "express_parser.py", line 481, in <module>
    mdl.Generator(mapping).emit()
AttributeError: 'module' object has no attribute 'Generator'

**Comment by aothms** [comment]
You're right, committed just now 64c0679a7ebf23ffaec1fcb3595b47f3889f80a1

Apparently you're the first to run code gen since these changes were made 2 months ago 481c6165caf81d65773d4ea989c19c7e07e2c5d3

**Comment by hu-stefan** [comment]
Thank you for your help!
