### ISSUE TITLE
please support swig4.0

### ISSUE THREAD

**Issue by haraldg** [IfcOpenShell/IfcOpenShell#855]
Hi,

after compiling recent git master with swig4.0 I get the following error:
```
>>> import ifcopenshell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ifcopenshell/__init__.py", line 47, in <module>
    from . import ifcopenshell_wrapper
  File "/usr/lib/python3/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 1088, in <module>
    class FileDescription(HeaderEntity):
  File "/usr/lib/python3/dist-packages/ifcopenshell/ifcopenshell_wrapper.py", line 1112, in FileDescription
    __swig_getmethods__["description"] = description
NameError: name '__swig_getmethods__' is not defined
```

After a web search it seems the recommended workaround is to build against swig3.0 instead. However, by now swig3.0 has been removed from many popular distributions like debian testing. So this workaround is not viable any longer.

**Comment by aothms** [comment]
There is this: https://github.com/IfcOpenShell/IfcOpenShell/commit/861dab0d9e516f0936e5d8e74a901c77434dc871#diff-64d910603262e9f0a9f6c26e328c4db7

You're probably on master. Have a look at the v0.6.0 that's were most of the development effort has gone towards in the last two years.

**Comment by haraldg** [comment]
Yes, indeed. Thanks for the pointer.

If v0.6.0 is what is actually used, maybe you should set it as default branch on github ...

**Comment by aothms** [comment]
> If v0.6.0 is what is actually used, maybe you should set it as default branch on github ...

That's a good suggestion. Done.
