### ISSUE TITLE
blenderbim 0.0.200511 assumes presence of numpy

### ISSUE THREAD

**Issue by DuncanLithgow** [IfcOpenShell/IfcOpenShell#860]
blenderbim install assumes presence of numpy python module which apparently isn't a blender dependency.

ModuleNotFoundError: No module named 'numpy'

**Comment by Moult** [comment]
I just checked in the latest install of Blender and found `blender-2.82a-linux64/2.82/python/lib/python3.7/site-packages/numpy` - so it looks like it does exist? What triggers this error and makes you think this is an issue?

**Comment by DuncanLithgow** [comment]
problem is with the ubuntu package. see launchpad https://bugs.launchpad.net/ubuntu/+source/blender/+bug/1781637

would be great if the installer could handle this by providing some information and maybe options.

**Comment by Jesusbill** [comment]
Are you using Blender 2.79? If yes, that would be the problem I think, I remember in another post Dion saying that it works for Blender > 2.80.
By the way I am using it also in Ubuntu (19.10) with Blender 2.82a and have no similar problem

**Comment by DuncanLithgow** [comment]
problem is ubuntu blender package 2.82.a+dfsg-1 for ubuntu 20.04
 we've just talked this through with Dion and Stephen on freenode ##architecture

**Comment by Moult** [comment]
I'd like to wrap this issue up - this error happens on install time, right? I think the appropriate thing to do is to detect the error, and point the user to the BlenderBIM Add-on installation documentation website. The website would include that, as well as other issues which may crop up.

I started up some docs [here](https://blenderbim.org/docs/blenderbim.html). @DuncanLithgow would you be interested in updating [this page](https://blenderbim.org/docs/blenderbim/installation.html) to include perhaps a Common Problems section, which can talk about it? Another thing which could be added is the lack of the fcl module on Macs which prevents running clash detection.

That page is also completely outdated, as the installation, update, and remove procedure has now been simplified to "just work" with the Blender Add-on protocols. Needs a rewrite :)

Doc code is [here](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcblenderexport/docs/blenderbim).

I was planning on simply disabling the relevant features if numpy isn't found, but I realised this is an increasing amount of features including documentation generation, IFC clash detection, and in the future when the IfcOpenShell utility classes grow, they will use numpy as Blender's mathutils won't be shared with FreeCAD and other apps, for example. I'm now of the opinion that it is better to just ask users to install numpy, and point them at the installation docs.

**Comment by DuncanLithgow** [comment]
I just saw this and will get to it when I have a chance. Otherwise ping me. But if the whole page needs a re-write there are others better suited than me for that.

**Comment by Moult** [comment]
Documented [here](https://wiki.osarch.org/index.php?title=How_to_install_the_BlenderBIM_Add-on).

Closing bug.
