### ISSUE TITLE
A shape representation without items will cause the geometry iterator to halt and not process further shapes

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#861]
A BlenderBIM Add-on user has a file created from ArchiCAD with the following snippet:

```
#1044= IFCSHAPEREPRESENTATION(#142,'Body','',$);
#1046= IFCPRODUCTDEFINITIONSHAPE($,$,(#1044));
#1049= IFCSLAB('1gIP_CAQ93Tw4$83$eAov6',#12,'SLA - 268',$,$,#1043,#1046,'6A499F8C-29A2-4377-A13F-203FE82B2E46',.FLOOR.);
```

As far as I am concerned, this is _invalid_ IFC, as the `Items` attribute of the `IfcShapeRepresentation` is [blank](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcshaperepresentation.htm).

However, when the geometry iterator (i.e. calls iterator.next() in python` comes across this invalid element, it then just stops. It doesn't segfault, nor error, but just will no longer process later elements. This gives the user the impression that the file has only imported a very small quantity of elements, with no error message.

A better behaviour would be to treat that object as without any geometry, and move on to the next one. Ideally, Graphisoft should fix the error too, assuming this error occurs in other Graphisoft IFCs, but as they are a large vendor IfcOpenShell should probably accommodate them for the time being.

When tested in XBim, XBim will disregard the invalid element, and process the remainder of the elements.

Hopefully an easy fix?

**Comment by aothms** [comment]
Yep you're right. Ultimately it's a bit of a flaw in IfcOpenShell that there is no validation during parsing so every later call can fail...

**Comment by aothms** [comment]
The IfcConvert error log for this file will now read something like:

```
Log:
[Error] Argument is not a list of entity instances
[Error] {2idn0Sq3SHvuvRW1aqWGIT} Argument is not a list of entity instances
Failed to convert:
#29=IfcShapeRepresentation(#11,'Body','SweptSolid',$)
```

**Comment by archiiso** [comment]
In the case with IfcOpenShell happens this:
I have an apartment A: walls, floor and ceiling & B furniture
1. I've tried to export by parts, for example just A and it worked, it was imported in Blender without any problem.
2. I've exported just a part of B, the hallway furniture a wardrobe and it worked.
3. When I want to import all the furniture, it gives an error.

If I can help with anything else please tell me.

[ifc archicad.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4656167/ifc.archicad.zip)

**Comment by Moult** [comment]
@archiiso I've just tested your files, and indeed they work, and @aothms has fixed the issue with importing all the furniture.

You may also be hitting a bug which has been fixed since the last release (the last release contained a few bugs as there were many new features).

I would advise to replace your `import_ifc.py` file with the latest version [here](https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/v0.6.0/src/ifcblenderexport/blenderbim/bim/import_ifc.py). The file on windows is usually in C:/Users/Foo/AppData/Roaming/Blender/2.82/scripts/addons/blenderbim/bim/.

Then ensure you have this option enabled when importing. It is a temporary workaround until the next version where @aothms 's fix will be available:

![image](https://user-images.githubusercontent.com/88302/82502748-2edf8e00-9b3b-11ea-8dd9-74395f59a8fc.png)

**Comment by archiiso** [comment]
Thank you all!
