### ISSUE TITLE
IfcTriangulatedFaceSet performance improvements

### ISSUE THREAD

**Issue by FreakTheMighty** [IfcOpenShell/IfcOpenShell#862]
In an effort to speed up our IfcOpenShell conversion we've changed our export to generated `IfcTriangulatedFaceSet` rathern than faceted breps. What we've found is that this is even slower than the faceted brep representation. The results on my computer look like this:

| IfcFacetedBrep  | IfcTriangulatedFaceSet  |
| ------------- | ------------- |
| 4 seconds  | 6 seconds  |

----

I suspect this is because the triangulated face set is still using the brep under the hood. I wonder though, perhaps this representation can really be handled in a different and more simple fashion. I'm not entirely clear what the `closed` parameter indicate in `IfcTriangulatedFaceSet`, but other than that, it seems to be a 1 to 1 mapping to a triangular mesh. It seems like that should be an extremely quick conversion.

Here are some simple repro files. They should contain the same content with the two different representations. I believe there are a total of 3 products, so performance wise I would expect these to export in substantially less than a second.
 
[FaceSetVsFacetedBrep.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4658582/FaceSetVsFacetedBrep.zip)

This issues relates to #841.

**Comment by aothms** [comment]
Yes this is sound analysis. It's just a matter of plumbing. There is in the current v0.6.0 infrastructure no way to bypass the pipeline from IfcRepresentationItem -> TopoDS_Shape -> Triangulation. And IfcTriangulatedFaceSet can still be part of boolean operations (although that is being discussed wihtin bSI).

This is also complicated by some of the serializers implemented in OCCT (such as the SVG serializer that slices OCCT primitives to obtain floor plans). So downstream processing also assumes full blown OCCT objects.

As said elsewhere the long term aim is for some sort of hybrid processing options. We have OCCT and CGAL, but probably as you say for this case there can also be a passthrough or simple model that just supports triangulation in case of IfcPolygonalFaceSet.

**Comment by Moult** [comment]
In Blender, there is no such thing as a face with a void, and it supports ngons. Is it possible to also have an optimisation that would allow importing this data to be really fast? Basically, just read the data and ignore the create shape for any triangulated faceset as well as polygonal faceset and faceted brep?

**Comment by aothms** [comment]
Yes, I've been thinking for a long time btw to have more kind of element serializations: we now have mesh and full blown brep, but some kind of polyhedra with different constrains (with or without inner bounds) would be nice to have. Either derived from brep or inferred from mesh. And later maybe more directly tied to IFC output.

The CGAL branch of IfcOpenShell is getting quite good https://github.com/tudelft3d/IfcOpenShell/tree/cgal/ It has an intermediate geometry representation called `taxonomy` that sits between the various IFC schemas and the geometry libraries. There is no longer a compilation target for every geometry engine times geometry library. But only [ifc schema]+ -> taxonomy -> [geometry library]+. Taxonomy will also do a bit of interpretation, e.g. parametrized profiles to face boundary loop, so the overall implementation effort for a geometry library is reduced. As discussed with @Moult I think it would make a nice GSoC project to add a geometry library solely based on Eigen and a triangulation library (maybe CGAL, maybe something like [0]). If we keep dependencies small, we can even compile to Web Assembly.

[0] https://github.com/artem-ogre/CDT

**Comment by Moult** [comment]
Finally resolved :) See #4915.
