### ISSUE TITLE
IfcConvert early exit when converting IfcGrid for .glb

### ISSUE THREAD

**Issue by harrycollin** [IfcOpenShell/IfcOpenShell#864]
I've been trying to get IfcGrid elements in my .glb conversions but haven't had any luck. I am left with tmp files and the conversion finishes early. This is my console output: 

./IfcConvert s-office.ifc s-office.glb --plan
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
Scanning file...
Done scanning file
Parsing input file took 3 seconds
Creating geometry...
[############################################## ]

I believe this to be a bug as when converting to .dae it works without any issues.

**Comment by aothms** [comment]
Thanks for reporting. This is fixed now in https://github.com/IfcOpenShell/IfcOpenShell/commit/603cf011c31866bea39c91bd8d30c529b9355e7f

It will take a while to be published on the website. Probably a couple of days. You can track build progress here https://github.com/IfcOpenBot/IfcOpenShell/commits/v0.6.0

**Comment by harrycollin** [comment]
@aothms No problem, glad to see it fixed :)
