### ISSUE TITLE
Documentation around shape.geometry.id / material.name naming scheme?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#866]
If `shape = iterator.get()`, is the naming scheme for `shape.geometry.id()` documented anywhere? Similarly, for `geometry.materials[i].name` or `geometry.materials[i].original_name()` ?

**Comment by aothms** [comment]
Not really. 

The first is just used to as a quick shorthand to check whether two processed geometries are identical. The generation starts here [0], so `IfcShapeRepresentation.id{-layerset-LayerSet.id}{-material-Material.id}{-openings-[Opening n.id ...]}{-world-coords}`


IIRC geometry.materials[i].original_name is either `surface-style-{SurfaceStyle.name}` or the entity class name in case of a default assigned style.  name is the same, but in case of the first, all non-alphanum characters are replaced with - {SurfaceStyle.name} [1].

[0] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomFunctions.cpp#L1668
[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom_schema_agnostic/IfcGeomRenderStyles.h#L56

**Comment by Moult** [comment]
Thanks :) I've put a small note about this in the [OSArch wiki](https://wiki.osarch.org/index.php?title=IfcOpenShell_code_examples), where I will continue to document how to use IfcOpenShell and hopefully help others too!
