### ISSUE TITLE
Segfault on multicore geometry iterator (single core works) for GEOBIM benchmark Savigliano.ifc

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#867]
https://3d.bk.tudelft.nl/projects/geobim-benchmark/

Apparently the Savigliano.ifc file segfaults when I try to import it using multicore. Shared file via Google drive.

**Comment by aothms** [comment]
I can't reproduce this using IfcConvert -j 8. How can I reproduce this?

**Comment by Moult** [comment]
Running this minimal example segfaults on my computer. Using ifcopenbot build ifcblender-python-37-v0.6.0-0d93633-linux64.zip - hopefully you can reproduce it?

```
import ifcopenshell
import ifcopenshell.geom
import multiprocessing
f = ifcopenshell.open('Savigliano.ifc')
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, f, multiprocessing.cpu_count())
valid_file = iterator.initialize()
while True:
    shape = iterator.get()
    if not iterator.next():
        break
```

**Comment by aothms** [comment]
Thanks, this was actually a pretty obvious issue. Not sure why I wasn't able to reproduce it initially. This is addressed in 724d8c405b8971cdcc47dfddd1410945f9596661.

**Comment by Moult** [comment]
Great job @aothms ! Will wait for the bot build to test.

**Comment by Moult** [comment]
Closing issue.
