### ISSUE TITLE
[BlenderBIM] Issue reporting route unclear

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#868]
Had to ask where to report issues with BlenderBIM and was directed here. This is unintuitive and should be resolved through better documentation at https://blenderbim.org/community.html

**Comment by Moult** [comment]
There is a button on that page that says "Report bugs"?

**Comment by globalcitizen** [comment]
Right you are. I was expecting a same-project-name Github project and am slightly sleep deprived for enhanced idiot testing!

**Comment by Moult** [comment]
Closed.
