### ISSUE TITLE
[BlenderBIM] Not possible to add Pset or Qto

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#869]
With a default cube, I was able to generate a `GlobalId` but unable to add a `Pset` or `Qto` and it is unclear why this is. See screenshots.

<img width="315" alt="Screen Shot 2020-06-04 at 09 46 51" src="https://user-images.githubusercontent.com/505366/83699856-8bb56b00-a648-11ea-8226-b085ba3d0f96.png">
<img width="329" alt="Screen Shot 2020-06-04 at 09 47 04" src="https://user-images.githubusercontent.com/505366/83699859-8d7f2e80-a648-11ea-8c34-f605e6113d86.png">

**Comment by Moult** [comment]
Property sets and quantity sets are applicable to specific IFC classes. You are required to first assign an IFC class to your cube, then the applicable property sets or quantity sets will display.

**Comment by globalcitizen** [comment]
Yep figured this out after scrolling over to the scene view interface tabs. Could be nice for new users to enhance the display to be disabled / greyed out with an appropriate message if none are defined. Or even add a define new Pset / Qto button right there in the input lists, which is a common UX paradigm.

**Comment by Moult** [comment]
Defining a new pset/qto is complex. The whole point of iSO-compliant structured BIM is not to create properties arbitrarily as key value pairs. There is a psets panel in the scene tab which makes an effort at authoring these.

Your suggestion is good. In fact, the entire panel doesn't apply until a class is first assigned, as everything depends on the class. I've fixed this by prompting for a class assignment and simply not showing the rest of the features until a class is assigned.

![image](https://user-images.githubusercontent.com/88302/83702745-de932080-a650-11ea-83f6-7d3a718159fc.png)
