### ISSUE TITLE
[BlenderBIM] Adding Representation clears scene. No button to remove.

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#870]
After adding a `Representation` record on an object the scene is cleared and the object disappears.

<img width="309" alt="Screen Shot 2020-06-04 at 09 50 39" src="https://user-images.githubusercontent.com/505366/83700022-ff577800-a648-11ea-83a4-0876433b7f33.png">

There is apparently no button to remove it.

**Comment by Moult** [comment]
The representation will disappear, since you will be editing the new blank representation.

A button is required to remove it.

**Comment by Moult** [comment]
Fixed.
