### ISSUE TITLE
Is it possible to do by_type('Ifc...') that only checks that exact class but no child classes? 

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#873]
Nevermind ;)

**Comment by aothms** [comment]
I assume you mean parent classes?

You can do `inst.is_a() == 'IfcWall' ` maybe ought to be added to the docs
if this wasn't clear.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 4 jun. 2020 02:18 schreef Dion Moult <notifications@github.com>:

**Comment by Moult** [comment]
Ah yes now I remember why I created this issue... it's about  `by_type`, not `is_a` :)

**Comment by aothms** [comment]
Hm yes we have this in cpp. I just added a directive in SWIG to have this a bit more accessible in Python. But perhaps you can do the final plumbing in the handwritten file to your liking. I think added a keyword argument like incl_subtypes=True is fine. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/file.py#L130 And then based on that call `self.wrapped_data.by_type()` or `self.wrapped_data.by_type_excl_subtypes()`

https://github.com/IfcOpenShell/IfcOpenShell/commit/a17b211983ba9114097ae0919de8658ffba0ca44

**Comment by Moult** [comment]
Thanks! I'll wait for the bot build, then will do the plumbing.

**Comment by Moult** [comment]
Just experimented with it, but I get an error:

```
>>> [ifcopenshell.entity_instance(e) for e in f.wrapped_data.by_type("IfcGeometricRepresentationContext")]
[#21=IfcGeometricRepresentationContext($,'Model',3,1.E-05,#17,$), #22=IfcGeometricRepresentationSubContext('Body','Model',*,*,*,*,#21,$,.MODEL_VIEW.,$)]
>>> [ifcopenshell.entity_instance(e) for e in f.wrapped_data.by_type_excl_subtypes("IfcGeometricRepresentationContext")]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 1322, in by_type_excl_subtypes
    return _ifcopenshell_wrapper.file_by_type_excl_subtypes(self, arg2)
TypeError: in method 'file_by_type_excl_subtypes', argument 2 of type 'IfcParse::declaration const *'
```

Did I so something wrong?

**Comment by aothms** [comment]
> Did I so something wrong?

No, sorry, I had only looked at the wrapper code, but the actual C++ did not have a string variant of this function implemented. See https://github.com/IfcOpenShell/IfcOpenShell/commit/803cc66abbc6a244be87b2f5cbace423524a1a6e

**Comment by Moult** [comment]
Thanks :) Works in the latest bot build - I've added the new argument!
