### ISSUE TITLE
[BlenderBIM] Owner History

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#875]
Unclear how to (impossible to?) define people or organizations.

<img width="260" alt="Screen Shot 2020-06-04 at 10 43 17" src="https://user-images.githubusercontent.com/505366/83702516-4301b000-a650-11ea-95ae-95227aa4fd3c.png">

**Comment by Moult** [comment]
Currently in Blender add-ons dir, `blenderbim/bim/data/owner/` in JSON.

No UI designed yet. Would you like to try?

**Comment by globalcitizen** [comment]
Looking at doing a pull request for some minor UI stuff now.

If that works I'll get more creative.

**Comment by Moult** [comment]
Just a heads up that the UI terminology is designed to reflect the ISO standard terminology ;)

**Comment by cccplex** [comment]
Also to note. I changed the organisation.json and put in my own details but then I got an error. 
`  File "/home/cccplex/.config/blender/2.83/scripts/addons/blenderbim/bim/export_ifc.py", line 1238, in create_owner_history
    developer_organisation = [o for o in self.ifc_parser.organisations if o['ifc'].Name == 'IfcOpenShell'][0]['ifc'] IndexError: list index out of range`
So you have to append your own details to that file and keep ifcOpenShell for the developer_organisation attribute.

**Comment by Moult** [comment]
Ah yeah, at the moment, IfcOpenShell is hardcoded as the developer organisation. I guess that's the correct approach?

**Comment by cccplex** [comment]
From a user perspective I would say, add another property (and json file) for the developer organisation.

**Comment by globalcitizen** [comment]
Other possible strategies:
- Detect computer system local username from the OS layer ... for example using the home directory name on unix-likes, but allowing an override
- Include a local user setting within some sort of configuration dialog
- Combine the above, so that a reasonable default is autodetected.

**Comment by Moult** [comment]
@cccplex to clarify, you can append to the `organisation.json` to include your own organisation, and then select it in the UI, but you cannot remove the "IfcOpenShell" one, since that one is hardcoded to be the "developer organisation". The "developer organisation" is used to defined the authoring IfcApplication, which should always be developed by IfcOpenShell. I can't quite see in what scenario a user might want to redefine the application's organisation.

@globalcitizen I'll make some time today to build a basic UI, and perhaps include some auto-detection of username in there.

**Comment by globalcitizen** [comment]
Fundamentally, if we are going for reasonable ease of use, editing files should not be required.

There is a concern about re-inventing version control though ... so many systems do that.

Maybe a zoom-out view of overall workflow could be considered, such that owner data could be pulled from git history (etc).

**Comment by Moult** [comment]
Agree that re-inventing VCS is a bad idea. I believe that the owner details in IFC stem from legislation requiring certain metadata to be tied to the model. I'm not a lawyer, so although from a technical perspective I see it much more desirable to link to to a VCS and scrap all of it, I don't know what it means legally.

It is on the roadmap to tie model / IFC management better to Git (for now, and other VCSes in the future) in the add-on. But yes, kind of off-topic for this bug.

**Comment by globalcitizen** [comment]
How about making this an export option instead? Would that make more sense?

**Comment by Moult** [comment]
Closing bug - new UI is done, and export system now reads from the Blender data instead of the JSON.
