### ISSUE TITLE
[BlenderBIM] Section plane != Creating a view. Semantic fix.

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#879]
From #878

> The section plane feature is not the same as creating a view - they are two separate features. Misleading, I know. 

Maybe revised terminology would be one approach to clarifying here.

## Temporary / inspection one

Options could include:
 * Use of the word 'temporary' or 'realtime'
 * Use of another prefix like 'inspection' as a prefix
    * Potentially hyphenated for additional delineation from other uses of the same noun, ie. 'inspection-view' or 'inspection-section'
 * Use of an alternate for-purpose noun, like 'cutaway', 'plane-view' or 'xsection' or 'cross-section'
 * The whole hog (all or most of the above) like: "realtime inspection-view cutaway" or "temporary inspection cross-section"

## Documentation / permanent one

Options could include:
 * Use the IFC terminology for a drawing (view / sheet?)
 * Use revised, IFC-suggestive terminology for a drawing with some kind of blenderesque compound noun (view-camera / sheet-camera)
 * Use other words from the traditional drafting world, while trying to minimize semantic collisions with blender objects (semantic collisions with programming structures are however fine, since users don't see them!). This could be quite problematic. I am thinking of words like projection, plane, orthographic, orthogonal, view-plane, drawing-view, drawing.
 * Something completely novel with a ballpark similar semantic, like "docview" or "autosection" 
   * Care should be taken not to destroy existing/planned semantics with respect to non-sectioned views and their associated cameras/objects
 * Something else?

**Comment by Moult** [comment]
I like "Temporary section cutaway".

View/Sheet is not IFC terminology. IFC does not specify sheets or views. They store annotation, but the view bounds are unspecified. There is a long story behind this, which I won't go into now. The closest (soon-to-be ISO) terminology is that of the BCF standard, which has the concept of "Viewpoints". Personally, I think maybe Viewpoint is a nice name - it connotes a camera, is similar to "View" for those coming from other CAD/BIM software, and is the same as the BCF standard.

Sheets should remain to be called sheets. That's what they are and always have been for decades. It's a sheet of paper :) There is no Blender camera associated with sheets, it is a pure SVG file with multiple embedded SVGs for all of the view(points) placed on the sheet.

**Comment by Moult** [comment]
Can this bug be closed?

**Comment by globalcitizen** [comment]
Change has been merged.
