### ISSUE TITLE
[BlenderBIM] Object/Documents vs. Output/Documentation confusingly similar

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#881]
These two need clearer delineation.

## Objects/Documents

<img width="293" alt="Screen Shot 2020-06-05 at 21 00 26" src="https://user-images.githubusercontent.com/505366/83869365-d251b500-a76f-11ea-8d65-a5058b69794d.png">

This seems like it is something to do with IFC document references?

## Output/Documentation

<img width="289" alt="Screen Shot 2020-06-05 at 21 00 53" src="https://user-images.githubusercontent.com/505366/83869369-d382e200-a76f-11ea-9db6-1c59f0086848.png">

This seems like, from your description of functionality at #878, that it actually creates and manages projections/drawings/cameras/sheets/something.

## Thoughts

There needs to be a clearer terminology adopted to break these two functions apart.

The second (creating actual cameras/views/section drawings) might be most usefully considered as part of the portion of the add-on that is of high value to other users without an interest in IFC. Which is to say, terminology should perhaps be encouraged to diverge from and remain unique to that of IFC. I guess some functionality users may want in managing a regular project's views/drawings would be:
- See a list of view/drawings
- Know what kind of drawings they are
- Title and rename them
- Regenerate them
- Switch to that view (optionally setting a preview mode which provides a rendered view in Blender as similar as possible to the output view)
- Possibly add changes/version numbers to them
- Set any stylistic properties specific to that view/drawing, such as which collections of objects should be visible, rendering settings, resolution settings (see @kevancress camera-specific resolution module), maybe a drawing template (such as fact boxes in margin; this could be from SVG), etc.

I assume currently there is a subset available.

**Comment by Moult** [comment]
As per your PR, the panels in your first screenshot have been renamed to denote how they are specific to IFC. This is a good thing.

The panels in the second screenshot, as you've identified, are agnostic of IFC.

What exactly is the bugreport here requesting? I didn't quite understand.

There is a list of view/drawings in the views/sheets dropdown. Not ideal, it should be a UIList, but for now it's a dropdown. They have a name, which you can rename manually at the moment. The buttons next to the dropdown let you switch to the view.

There is no UI currently for revision control. It needs to be added.

There is no system, nor UI for stylistic properties. This needs to be developed. The only "system" is the SVG/CSS styles which you can define yourself from any SVG program. For example, you can change the default titleblock by editing it in Inkscape.

**Comment by globalcitizen** [comment]
> As per your PR, the panels in your first screenshot have been renamed to denote how they are specific to IFC. This is a good thing.

OK, guilty as charged I need to update my Blender to use the local source version instead of the downloaded version of the add-on.

> The panels in the second screenshot, as you've identified, are agnostic of IFC.

Right.

> What exactly is the bugreport here requesting? I didn't quite understand.

Basically the title 'documentation' for the panel is too vague.

It has issues on a few levels.

## Popular use

The term 'documentation' it is not really in alignment with popular use in my understanding.

It is my understanding that in the modern history of engineering drawings for the construction industry, roughly nobody outside of corporate outfits have really used the term 'documentation'. Instead, most people have called the set of drawings for a job 'plans' and many people have called them 'drawings'. Certainly all the builders, subcontractors, engineers and regulators I have spoken to have used these terms, with 'plans' clearly the most popular.

## Actual utility encompassed

The term 'documentation' is directly and clearly meaningful and within its popular understood scope of meaning as applied to the output files. However, it is not meaningful as applied to a list of cameras/views, and functionality related to those like add, name, co-associate.

These functionalities would perhaps be best termed something else, like "Views and sheets" for example.

## Vague .... and close to other uses

Being a vague term it could apply to many other things, for example the other pane mentioned (although as you rightly point out this has been since clarified in part).


## Suggestion

Too tired to make a clear suggestion right now.

**Comment by Moult** [comment]
I have always heard it called documentation, perhaps because I've always worked in corporate outfits. I am against calling them "plans", as to me, a "plan" is one particular type of view, in contrast to a section, RCP, elevation, axonometric ... Drawings, I am not particularly fussed about, I see them as synonyms, though one could argue that a documentation could contain a drawing, but could equally contain schedules, key/legends, and so on.

If you feel it is a usability improvement to rename it to "Drawings", or "Sheets", go ahead :)

**Comment by globalcitizen** [comment]
Terminology is very important because it comes with expected and unexpected baggage, done right prevents misunderstanding and creates clarity.

*There are only two hard things in Computer Science: off by one errors, cache invalidation and naming things.* - Phil Karlton

Maybe we can bring this up in the meeting.

**Comment by Moult** [comment]
I completely agree with the importance of naming, as with that quote. You will notice I have been very careful with most of the names so far. I named it documentation, from my own professional experience. That experience may not be representative of the full industry, and so I am open to changes.

I will cite some very large platforms, such as Oracle Aconex, who refers to it as documentation, and BIM360, which also refers to it as documentation. Same with iTwoCX. But again, these platforms are used by corporate outfits, and not by smaller players. Hence, probably, the naming discrepancy.

**Comment by Moult** [comment]
Renamed it to "Drawings and Sheets". A "Sheet" contains a collection of "Drawings", "Schedules" and other things, but since we don't have any schedule panel (yet) for now it's just Drawings and Sheets.

I haven't renamed it in the code yet, so in the code the old names are there, but that's OK since in the future a lot of this stuff will be be merged into Measure-It-ARCH's code.

Closing bug.
