### ISSUE TITLE
[BlenderBIM] Pressing undo after creating a DIM crashes Blender

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#883]
- Blender version v2.83.
- Platform OSX Mojave.
- BlenderBIM version 0.0.200525

**Comment by Moult** [comment]
I cannot replicate it on Blender v2.82. It sounds more like a Blender bug.

The operator it executes is [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/operator.py#L2695), called [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/ui.py#L611).

I would isolate that into a standalone Python script to run in Blender, and see if you can create a minimum working example of your issue.

**Comment by globalcitizen** [comment]
It yields a segfault. I guess I should report it upstream.

**Comment by Moult** [comment]
Will leave this open for 2 weeks to give time for upstream to comment, after which, if it is unrelated to the BlenderBIM Add-on, it will be closed.

**Comment by globalcitizen** [comment]
Created [upstream bug report](https://developer.blender.org/T77537).
