### ISSUE TITLE
[BlenderBIM] Sheet output scale unclear or unsupported

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#884]
It is unclear what the output scale is for the SVG files generated.

In general, in my understanding, drawings within the construction industry have scale expressed as 1:X where X is typically a whole number like 1:20, 1:100, 1:200, 1:1000, etc.

Currently the only scale I can see related to a particular view is the orthographic scale associated with the camera object.

<img width="291" alt="Screen Shot 2020-06-05 at 21 46 39" src="https://user-images.githubusercontent.com/505366/83873143-9110d380-a776-11ea-9765-c079015241ce.png">

Given that it's apparently possible to assign multiple views to a single sheet (ie. output drawing), it is very unclear what the scale might be, since multiple views of the same object would then be subject to multiple camera-associated orthographic scales which may theoretically differ. It is even more unclear how it may be set.

I assume, then, that is is unsupported.

This is quite a bug, since it is very common that a certain scale is required, as indeed it is in my case.

While a temporary workaround may be to manually alter the scale of each object within the output SVG, a final solution seems like it would not be too hard to implement and would benefit all users.

A related issue may be "how big can you make the various views while still fitting them on the sheet?" which begs the question of sheet size, which one would assume should also affect font size.

**Comment by globalcitizen** [comment]
Hrrm just noticed there is a scale on the output. How does this work with multiple drawings or things that don't fit on a sheet? Can it be specified?

<img width="635" alt="Screen Shot 2020-06-05 at 22 14 31" src="https://user-images.githubusercontent.com/505366/83875239-15b12100-a77a-11ea-85ed-bfee1c4c7369.png">


Anyway I am too tired now, continue tomorrow.

**Comment by Moult** [comment]
Each view has an associated camera. Each camera has its own scale setting, currently supporting the metric standards (1:{1,2,5}{0}+). Custom scales are not yet supported.

![image](https://user-images.githubusercontent.com/88302/83930186-a703b000-a7d9-11ea-8519-5bcb1b0a783f.png)

All drawings are output with the correct scale. If you have a 1m x 1m cube, set your view (camera) scale to 1:100, then you will output an SVG where the cube is 10mm x 10mm. If you print it out, you will measure it with a ruler as 10mm x 10mm. If you place it on a sheet (note: the default titleblock is an A1 sheet of paper), it will still be 10mm x 10mm.

The feature is  supported, though perhaps not intuitive to discover. Suggestions welcome.

**Comment by globalcitizen** [comment]
Oh awesome! That's really great. You have already finished so much awesome work, it's consistently impressive.

**Comment by Moult** [comment]
Closing issue, unless I missed an actionable item. I recognise the UX is poor, and will welcome suggestions to improve it.

**Comment by globalcitizen** [comment]
Yes, quite right, the feature was pre-existing. Thanks again for your patience.
