### ISSUE TITLE
Suggestions to iterator to support more native element round-tripping

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#885]
In addition to #771, where I hope for a context filter in the iterator, I'd like to propose a few more changes to the iterator to improve native element round-tripping.

In #865, there is a requirement to preserve the extruded area solid geometries, instead of turning them into meshes. This requirement has been brought up in the past before by users like @theoryshaw - so there is a need for it.

Therefore, I need to write some code which will:

 1) Isolate the representations of a particular context of each product
 2) See if any of those representations contain items which are something I can "retain" its parametric data, like an IfcExtrudedAreaSolid
 3) Loop through each of those items, for each item, if it is something I can parse natively, I write custom Blender code which builds up Blender geometry + data for it. If I cannot parse it natively, I then want to run it through create_shape() and get myself a basic mesh.
 4) During this process, keep track of any cartesian transformations and offset mapped origins applied during mapped representations.
 5) During this process, keep track of any styled by relationships for materials, since I can no longer rely on `shape.geometry.materials` and `shape.geometry.material_ids`.
 6) During this process, keep track of already processed representation item STEP ids, since they may or may not be reused.
 7) During this process, keep track of what belongs to what item, at what level of the mapping ... 
 8) Merge all of the created shapes into a single Blender object.

This is quite a bit of work! The end result, however, is that in Blender I can select an object, and see what representation items it has, and for each item, potentially modify it without losing its parametric data.

However, this work is necessary if Blender is to become a fully-fledged BIM authoring tool. Otherwise, input geometry would always be reduced into meshes.

Edit: I mention Blender here, but the exact same logic would need to be done to FreeCAD.

I wonder if there are ways to improve this situation. Current thoughts:

 - Geometry iterator should only look for a particular context/subcontext/target view filter (as mentioned previously in #771 )
 - Geometry iterator should have an include / exclude of particular representation item types.
 - Geometry iterator should return `items` and `item_ids`. The former being a list of `IfcRepresentationItem` classes, and the latter being a polygon<->items map, similar to `materials` and `material_ids`.
 - Some util function for resolving mapped geometry transformations. There is plenty of opportunity to get it wrong.
 - I think I recall you saying that the iterator caches things where create_shape doesn't, so perhaps create_shape should have a caching option?

Thoughts?

**Comment by aothms** [comment]
My long long long ago plan is that I'd like to represent the return of  `create_shape()` or `iterator.get()` as some sort of tree structure that developers can navigate themselves. 

Let's say:

![afbeelding](https://user-images.githubusercontent.com/1096535/83964982-befa3300-a8b0-11ea-9139-5e750e015db1.png)

At every level you can get the meshed representation as soon as you don't understand (cannot represent) an operation node in the tree.

In the v0.7.0 branch I made some progress with this https://github.com/aothms/IfcOpenShell/blob/v0.7.0-rewrite/src/ifcgeom/taxonomy.h

Would this be something you can work with?

**Comment by Moult** [comment]
Yes. Yes. Yes. Yes. Yes! That would be beautiful! Then we can go through the tree, parse anything we can parse, and meshify everything we can't.

I completely understand if it's a ton of work and won't be ready for a while, but as soon as there's any small function available, I'm going to keep a close watch because I'm writing a lot of this stuff in the BlenderBIM Add-on right now.

**Comment by Moult** [comment]
Closing bug, as actually I reckon after #1222 this kinda is starting to work out without even needing this level of granularity in the return value.
