### ISSUE TITLE
[IfcBlender] Exception when importing

### ISSUE THREAD

**Issue by thomiel** [IfcOpenShell/IfcOpenShell#886]
See screenshot. This is Blender 2.83 LTS on Windows 10 2004 64 bit.

![screenshot](https://user-images.githubusercontent.com/11477743/83941946-9cecac00-a7ef-11ea-896e-47b88b5f061c.png)

**Comment by Moult** [comment]
The old IfcBlender is no longer supported, please uninstall and download the latest from https://blenderbim.org/

@aothms time to update the website, perhaps?

**Comment by aothms** [comment]
The important error is `IfcOpenShell not built for Windows\64bit\Python3.7` you probably a version that does not match the Python version or 32/64 bit used in blender. You need the python37 one it seems.

@Moult I added a message on the website

![afbeelding](https://user-images.githubusercontent.com/1096535/83964796-ac332e80-a8af-11ea-827a-d33d320dc4fa.png)

**Comment by Moult** [comment]
Thanks @aothms :)

@thomiel FYI all of the BlenderBIM Add-on builds include the appropriate IfcOpenShell version, so it should work out of the box.

**Comment by thomiel** [comment]
Thanks.
