### ISSUE TITLE
[BlenderBIM] View auto-naming

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#890]
Following on from discussions in #882 it would be good to generate meaningful titles for views automatically.

I propose assuming (for overall views):
- If there is a configured (site is geopositioned + oriented) 'Lighting: Sun Position' add-on then we should attempt to use the cardinal points.
- Otherwise, there is a 'front' (drop-down configurable betwen X+, X-, Y+, Y-) and we can use the terms front, rear, left, right.

For more specific views, a similar approach could be taken but using the collection name as the basis, eg. 'Utility Block West Elevation' where 'Utility Block' is the collection name.

The user should be able to overwrite and manually specify drawing names anyway.

The above should ideally be internationalized (#889), with the output language defaulting to the interface language, but optionally different.

**Comment by Moult** [comment]
This bug is on hold indefinitely until #1153 and related more fundamental aspects of the drawing system are more polished.

**Comment by Moult** [comment]
Chipping away slowly at this, added storey-based elevation when creating plans. Note that it is unnecessary to look at site georeferencing, project north is always +Y, project east is always +X, so we will use project terminology North South East West.
