### ISSUE TITLE
[BlenderBIM] Sheet-linked camera field of view configuration unclear

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#892]
When viewing the orthographic camera created by the 'create sheet' button the initial field of view is insufficient for displaying the entire model.

<img width="1018" alt="Screen Shot 2020-06-09 at 05 43 39" src="https://user-images.githubusercontent.com/505366/84073693-a014b180-aa14-11ea-9254-27fdfe72f4ee.png">

Normally with a camera in Blender you have two options to obtain different field of view:
1. Alter the camera settings
2. Move the camera

## Alter the camera settings

With normal cameras you alter lens or sensor size. 

After inspecting the camera, it has a setting called 'Orthographic scale' set to `6.0`.

Altering this scale to a larger value resolves the problem.

<img width="292" alt="Screen Shot 2020-06-09 at 05 43 24" src="https://user-images.githubusercontent.com/505366/84073748-bc185300-aa14-11ea-96d7-45bf1244212d.png">

<img width="1059" alt="Screen Shot 2020-06-09 at 05 43 32" src="https://user-images.githubusercontent.com/505366/84073744-b884cc00-aa14-11ea-92e8-02df51693ea1.png">

However, after adding the view to a sheet and generating the sheet, the drawing title and scale values are then unfilled.

<img width="716" alt="Screen Shot 2020-06-09 at 05 43 13" src="https://user-images.githubusercontent.com/505366/84073792-cfc3b980-aa14-11ea-9290-7e38c0bf6208.png">

## Move the camera

I also tried manually moving the camera up on the Z axis but this made no difference.

<img width="1106" alt="Screen Shot 2020-06-09 at 05 43 52" src="https://user-images.githubusercontent.com/505366/84073902-00a3ee80-aa15-11ea-9950-e5615b0b55af.png">

## Version note
Note that I am still not on the git master. I will look to fix that now.

**Comment by Moult** [comment]
This is normal behaviour. Orthogonal cameras look into infinity, therefore moving the camera has no impact. The appropriate way to see more things is to increase the orthographic scale.

The orthographic scale does not impact the drawing scale. Orthographic scale refers to how much the camera captures, and drawing scale refers to the scale at which it displays on a sheet. At 1m x 1m cube at 1:100 will display as 10mm regardless of the orthographic scale.

The generate sheet function _should_ fill out the scale. If it doesn't, that is a bug. Keep in mind that the generated sheet is a _different_ SVG to the regular sheet. The button I've highlighted will open the generated sheet:

![image](https://user-images.githubusercontent.com/88302/84086921-546e0200-aa2c-11ea-9839-4705ac7b6e2d.png)

**Comment by Moult** [comment]
Closing, unless a test case can be put together to demonstrate the sheet generation not filling out the scale.
