### ISSUE TITLE
How to add ifc-type when extracting ifc model? (c++)

### ISSUE THREAD

**Issue by haelue** [IfcOpenShell/IfcOpenShell#893]
We are extracting and triangulating ifc-entities with ifcOpenShell (c++). But in some cases we need to extract type of IfcSpace while the default tutorials not given. 
How to do that? Many thanks!

[cite] we are using this function:
IfcGeom::Iterator<real_t> *getGeom(path_t input_filename,int num_threads=1);

**Comment by Moult** [comment]
Is this about having the geometry iterator go through IfcTypeObjects? If so, I have this question too (albeit in Python) - right now, I'm having to use create_shape separately on them, which isn't ideal (the whole threads = 1) problem.

I have a hunch that perhaps the the `include` argument may help, but I haven't tested it yet.

**Comment by aothms** [comment]
Ah, you mean for project library type of things? Yes that wasn't on my radar when designing this iterator thing. I can think about it, but most of the iterator logic does not apply to this (like detecting mapped item usage amongst products). So it'd require some thinking.

**Comment by Moult** [comment]
@aothms not just project library type things. I believe in IFC the type objects can have a totally different representation compared to the regular objects. This creates a few interesting scenarios:

 1. if the type object has no representation, it suggests that the element objects are all context specific, such as walls, where every wall is different.
 2. If the type object has a representation, and all regular objects are mapped to it, then we know it is a standard product we can purchase and plonk in without considering context
 3. If the type object has a representation, it offers the ability for us to model one representation for the type, and another for the objects. For example, this is used for wall types: the type representation contains a detailed 3D model demonstrating typical junctions shown in a wall types schedule and wall details page. The regular object representations contain a simplified extruded solid model and the builder can figure out the build-up of the wall, taking hints from the type representation.

Admittedly, I don't know any other vendors doing these funky things... but :) Let's trailblaze!

**Comment by aothms** [comment]
Not sure if I agree on 3. Probably IfcConnectionGeometry can be used for that instead (or IfcRelProjectsElement) Different representations in places where tools expect them to be same might cause further discrepancies between implementations where one tool will show the element reps, the other will show the type reps? It also seems to contradict 1.

**Comment by Moult** [comment]
@aothms makes sense. I have disabled type geometry creation on import by default now in the BlenderBIM Add-on, assuming that people would only want to enable it for project library scenarios. Consider it a low priority :)

I didn't realise it was off-topic when I first mentioned it in this bugreport, so feel free to close this bugreport if the OP's question has been resolved.

**Comment by haelue** [comment]
My partner solve this problem, using code:
```
entity_filter.entity_names.insert("IfcSpace");
...
filter_funcs.push_back(boost::ref(entity_filter));
```
All your suggestions are meaningful. Thank you!
