### ISSUE TITLE
[SIGSEGV] using geom iterator

### ISSUE THREAD

**Issue by e3dEF** [IfcOpenShell/IfcOpenShell#894]
Hi,

in the current version 0.6.0b0 for Linux 64bit (only version I tested), the geom creator interrupts when using more than 2 processes: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV). I can use all threads in other python code when using multiprocessing.

**Comment by aothms** [comment]
Thanks, this was actually a pretty obvious issue. Not sure why I wasn't able to reproduce it initially. This is addressed in 724d8c405b8971cdcc47dfddd1410945f9596661. You can wait for the next automated build or compile yourself.
