### ISSUE TITLE
Call to iterator.progress() for progress bar possibly needs optimisation?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#895]
The UpTown.ifc file, part of https://3d.bk.tudelft.nl/projects/geobim-benchmark/ - seems to exhibit a strange behaviour.

In particular, it seems that calls to `iterator.progress()` take a long time. Since I make this call to show a progress bar during import, it creates the funky scenario where it is actually the progress bar that causes this file to take hours to import :)

Without the `iterator.progress()` call, it takes 10 minutes to import. (Edit: this excludes Blender mesh creation, which adds a bunch of time on top)

Sample code where it works well:

```
import time
import multiprocessing
import ifcopenshell
import ifcopenshell.geom
start = time.time()
#ifc_file = ifcopenshell.open('/home/dion/drive/bim/UpTown.ifc')
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, self.file, multiprocessing.cpu_count())
valid_file = iterator.initialize()
total = 0
checkpoint = time.time()
while True:
    total += 1
    if total % 250 == 0:
        print('Processed {} in {}'.format(total, time.time() - checkpoint))
        checkpoint = time.time()
    shape = iterator.get()
    #print(ifc_file.by_id(shape.guid))
    self.create_product(self.file.by_id(shape.guid), shape)
    if not iterator.next():
        break
print('All done in {}'.format(time.time() - start))
```

Sample code where it takes forever:

```
import time
import multiprocessing
import ifcopenshell
import ifcopenshell.geom
start = time.time()
ifc_file = ifcopenshell.open('/home/dion/drive/bim/UpTown.ifc')
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
valid_file = iterator.initialize()
total = 0
checkpoint = time.time()
old_progress = -1
while True:
    total += 1
    progress = iterator.progress() // 2
    if progress > old_progress:
        print("\r[" + "#" * progress + " " * (50 - progress) + "]", end="")
        old_progress = progress
    if total % 250 == 0:
        print('Processed {} in {}'.format(total, time.time() - checkpoint))
        checkpoint = time.time()
    shape = iterator.get()
    #print(ifc_file.by_id(shape.guid))
    #self.create_product(self.file.by_id(shape.guid), shape)
    if not iterator.next():
        break
print('All done in {}'.format(time.time() - start))
```

**Comment by aothms** [comment]
Wow bizarre. Well to rule out the obvious thing, I think we'd have to eliminate that extra print call in the 2nd script. Printing to the console can sometimes be excessively slow.

The code path for progress checking is different using multiple cores https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomIteratorImplementation.h#L533. It involves a `std::atomic<int>` which apparently could be slow. https://stackoverflow.com/questions/51846894/what-is-the-performance-of-stdatomic-vs-non-atomic-variables I'd be surprised though if it'd be measurably slow wrt to the processing of shape geometries. I can't optimize much (besides https://en.cppreference.com/w/cpp/atomic/memory_order). If it really is slow I guess we just have to call progress() within the `total % 250` block?

**Comment by Moult** [comment]
Closing bug as I can't seem to replicate this outside Blender ... maybe there is something funny going on with how Blender scripts print to the Blender console ... my sample code I wrote works fine outside Blender ...

Will reopen if I ever re-discover this :) For now, it's solved!
