### ISSUE TITLE
IfcConvert Performance Curve

### ISSUE THREAD

**Issue by LQKLXR** [IfcOpenShell/IfcOpenShell#897]
Do you have a performance curve about the model size and time? I need to predict the transformation time of a model. What kind of mathematical function is it?

**Comment by LQKLXR** [comment]
When converting to obj + MTL

**Comment by aothms** [comment]
> What kind of mathematical function is it?

Linear. But that's only theoretical. Actual performance is more based on individual elements that sometimes take extraordinary amount of processing.

Explicit meshes are a bit slower in IfcOpenShell because they are reinterpreted into OCCT BRep model, as noted in #841

**Comment by Moult** [comment]
Question seems to be answered, so closing.
