### ISSUE TITLE
extract all the geometric representations of ifc files

### ISSUE THREAD

**Issue by universeteng** [IfcOpenShell/IfcOpenShell#899]
Hi, we want to extract all the geometric representations of ifc files before triangulation with ifcopenshell(C++), how should we do this?thanks

**Comment by Moult** [comment]
@universeteng can you just get all of the IfcProductDefinition, or IfcShapeRepresentation entities? (depending on how you plan to slice and dice it)

**Comment by universeteng** [comment]
I want to get all IfcShapeRepresentation entities and triangulate them myself. Can you give me a simple example

**Comment by Moult** [comment]
I cannot help with C++, I'm sorry, @aothms may be able to help give an example.

**Comment by aothms** [comment]
Getting instances by type is described here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/examples/IfcParseExamples.cpp You can read more here about writing schema agnostic code in C++ http://blog.ifcopenshell.org/2019/12/v060.html

A unsolicited word of advise. IFC geometry is only polyhedral definitions, so triangulation is not the only geometric conversion taking place. There are boolean operations under a tolerance value / fuzziness and complex sweeps such as IfcSurfaceCurveSweptAreaSolid that you do not want to implement without a good continuous BRep data model.

If you do want to use OCCT and only bypass BRepMesh_IncrementalMesh() you can use settings.USE_BREP_DATA for the geometry conversion and get native serialization of OCCT compounds.
