### ISSUE TITLE
BlenderBIM svg is not recut on model change

### ISSUE THREAD

**Issue by JanFilipec** [IfcOpenShell/IfcOpenShell#901]
When the model is cut for svg documentation with "Cut Section" button, changed and cut again, the exported polygons are not updated as expected.

The original model:
![Bl cut 1](https://user-images.githubusercontent.com/67052298/84891925-f761f400-b09c-11ea-80d4-9f9ab7bb8eaa.JPG)

Objects exported in an ifc file, loaded in "Output Properties" IFC #1 and cut:
![Svg cut 1](https://user-images.githubusercontent.com/67052298/84891989-1a8ca380-b09d-11ea-9074-07e8976160af.JPG)

Changed model:
![Bl cut 2](https://user-images.githubusercontent.com/67052298/84892022-25473880-b09d-11ea-9a6a-72b685206103.JPG)

Obejcts re-exported as ifc, overwriting the loaded ifc file and cut:
![Svg cut 2](https://user-images.githubusercontent.com/67052298/84892109-4d369c00-b09d-11ea-98de-20e50b525164.JPG)

The rendered image (grey) is changed correctly, but the svg polygons (black) stay un-updated. The svg cut is correct again only when the ifc is exported with a new name and loaded as IFX#1 instead of the old one.

Also, is there any way to bypass the need to manually export the ifc file after each change to the model to get an updated cut? It was my understanding, that the checkbox "should recut" would force the ifc model to be re-exported before the cut is performed, however that doesn't seem to be so.

**Comment by Moult** [comment]
At the moment, it is required to manually export the IFC file. There is no code written that auto exports.

However, the "should recut" option _should_ cause it to update the black section cut. Are you absolutely sure that you exported it to the same location that is specified in the "IFC #1" IFC file?

**Comment by JanFilipec** [comment]
Checked it again, just to be sure. The section is not updated, even if I change the path to the file (exported it again to a different folder and selected the new path as IFC #1), but the name stays. First when I change the name and load it again, it updates.

**Comment by Moult** [comment]
Fixed. There is also now a new option:

 - Should recut: Enabled

This will recalculate the cut of all shapes. Like a force refresh. Expensive.

 - Should recut: Enabled
 - Should recut selected only: Enabled

Note: both enabled. This will recalculate the cut of only selected shapes, and will reuse cached cuts of all other shapes where possible.
