### ISSUE TITLE
BlenderBIM : issue with non ascii character in file name on ifc export

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#902]
There is probably an utf-8 encoding issue somewhere. Exporting giving filename `Modèle.ifc` become `ModÃ¨le.ifc` on disk.
BlenderBIM 0.0.200525

**Comment by Moult** [comment]
Thanks to @s-leger pointing to https://www.i18nqa.com/debug/utf8-debug.html - also note that this behaviour happens on Windows - I can replicate on Windows, but cannot replicate on Linux.

Ping @aothms I _think_, not sure, but I think this could be an IfcOpenShell issue in the write function. See this minimal test case which is run agnostic of Blender:

```
f = ifcopenshell.file()
f.createIfcPerson()
f.write('C:/Users/you/Documents/Modèle.ifc')
```

It will produce the filename `ModÃ¨le.ifc`.

**Comment by aothms** [comment]
Yes I can also reproduce this, which is embarrassing considering the amount of unicode handling in IfcOpenShell :(

~~~
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> f.write("Modèle.ifc")
>>> import glob
>>> glob.glob("*.ifc")
['ModÃ¨le.ifc']
~~~

See 436eb3a6379fa7d2414fa089ec699fa3ef224cd5

**Comment by Moult** [comment]
Thanks @aothms!

@CyrilWaechter I'll wait for the next automatic IfcOpenShell build, and bundle it with the BlenderBIM Add-on - that should resolve your issue! Will close this bug once its bundled.

**Comment by Moult** [comment]
@aothms is IfcOpenBot sleeping by any chance? I just noticed the last build is almost a month ago...

**Comment by aothms** [comment]
Rebooted, let's see..

**Comment by aothms** [comment]
She get's slower and slower. The 4x3 schema yet again increased build times. And the python version build matrix is also impressive. The nix build script does not reuse build outputs for parse and geom when building the wrapper, this also needs to change I guess.

**Comment by CyrilWaechter** [comment]
I confirm it is now fixed. Thanks.
