### ISSUE TITLE
ifcopenshell-python segfaults when creating geometry (several versions affected)

### ISSUE THREAD

**Issue by haraldg** [IfcOpenShell/IfcOpenShell#904]
Here is the example file: https://friends.ccbib.org/lambda/segfault.ifc
I tried to produce a minimal file, that only contains the offensive instance, but then it works fine. It's one of those bugs ... :-(

Here is the transcript to reproduce:
```
Python 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> from ifcopenshell import geom
>>> f = ifcopenshell.open("segfault.ifc")
>>> settings = ifcopenshell.geom.settings()
>>> cr = ifcopenshell.geom.create_shape(settings,f[2513103])
Speicherzugriffsfehler
```

I have tried precompiled versions from the website and a local build of 8962e3bcf4f406bac9ac02f59e64974dfbe60192.

**Comment by aothms** [comment]
Yes, can confirm, appears to be an error calculating edge length of a bspline curve edge during boolean operation preprocessing. I'll have a look, might not be easy.

**Comment by aothms** [comment]
See discussion at #914 this is easily fixed by detecting this is a IFC4 Reference view with precalculated boolean subtractions

**Comment by Moult** [comment]
Tested with latest IfcOpenShell-python and all geometry is created fine without any segfaults :)
