### ISSUE TITLE
AttributeError: 'Geom_Surface' object has no attribute 'GetObject'

### ISSUE THREAD

**Issue by Alikhuder** [IfcOpenShell/IfcOpenShell#909]
Hi,
I'm trying to run this code (http://academy.ifcopenshell.org/using-ifcopenshell-and-pythonocc-to-construct-new-geometry/) (the new code-pythonOCC 0.16.0), and I set everything correctly, but I'm getting this error :

![ali](https://user-images.githubusercontent.com/68009811/86913796-0d505b00-c117-11ea-8a31-3d2052879aee.PNG)

I'm using :
Python 3.7.6
Anaconda
pycharm
opencascade-7.4.0
ifcopenshell-v0.6.0
Is there a workaround for this issue? Thank you in advance.

**Comment by aothms** [comment]
> opencascade-7.4.0

The tutorials were written for an earlier version, you can either downgrade pythonOCC anything before 7.4 should work. Or change the code (would be great if you can share them with the community if so). Everywhere where you see GetObject and GetHandle I think they can be removed for opencascade-7.4.0

**Comment by Alikhuder** [comment]
Hi @aothms,
Thank you for your quick response. I will see what approach I'm going to follow. if I'm changing the code, I will be more than happy to share it with the community. 
Can you provide me with a short example on how to replace/ remove the code lines marked in the attached picture? Thank you in advance

![aasasa](https://user-images.githubusercontent.com/68009811/87067410-e758b280-c20b-11ea-8ad0-3cc454a67cbe.PNG)

Another question, does ifcopenshell support IFC 4X3 version?

**Comment by aothms** [comment]
I currently don't have pyocc 7.4 installed, so it will require some experimentation from your side. But my understanding is that simply all GetObject() calls can be removed. There are some Surface and DownCast examples here https://github.com/tpaviot/pythonocc-demos/blob/3094f5545d000025bb7481182e270ce0e7df9d70/examples/core_topology_local_ops.py#L52

> Another question, does ifcopenshell support IFC 4X3 version?

Yes, for parsing, but there no implementation for representation items from 4X1 and upwards, but people are working on it e.g. https://github.com/IfcOpenShell/IfcOpenShell/issues/842
