### ISSUE TITLE
Changes made for MSVC 2013 and throw exception

### ISSUE THREAD

**Issue by sf8321** [IfcOpenShell/IfcOpenShell#910]
Hallo,
we made same changes for MSVC 2013 and throw exception

1. ifcparse/IfcHierarchyHelper.h, addRelatedObject line 175-186
....
T* rel = *i;
try {
   if (
....
       found = true;
       break;
     }
 }
catch (...) { /* */ }
....

exception comes from 

ifcparse/IfcHierarchyHelper.h line 176 get_parent_of_relation(rel)
if (get_parent_of_relation(rel) == relating_object) {

ifcparse/IfcHierarchyHelper.h line 47
IfcUtil::IfcBaseClass* get_parent_of_relation(IfcUtil::IfcBaseClass* t)

ifcparse/IfcSchema.h
ptrdiff_t attribute_index(const std::string& attr_name) const {

ptrdiff_t index = -1;

-1 return but  getArgument(..) Parameter is unsigned int 
in the methode -1 is ca. 42123423423423 and throw IfcParse::IfcAttributeOutOfRangeException
we catch this exception and all works as expected and before in 0.5-rc1

2. ifcparse/IfcSIPrefix.cpp line 77-...

old
-------------------------
template double IfcParse::get_SI_equivalent<Ifc2x3>(typename Ifc2x3::IfcNamedUnit* named_unit);
template double IfcParse::get_SI_equivalent<Ifc4>(typename Ifc4::IfcNamedUnit* named_unit);
template double IfcParse::get_SI_equivalent<Ifc4x1>(typename Ifc4x1::IfcNamedUnit* named_unit);
template double IfcParse::get_SI_equivalent<Ifc4x2>(typename Ifc4x2::IfcNamedUnit* named_unit);
template double IfcParse::get_SI_equivalent<Ifc4x3_rc1>(typename Ifc4x3_rc1::IfcNamedUnit* named_unit);

new
--------------------------------------
template double IfcParse::get_SI_equivalent<Ifc2x3>(Ifc2x3::IfcNamedUnit* named_unit);
template double IfcParse::get_SI_equivalent<Ifc4>(Ifc4::IfcNamedUnit* named_unit);
template double IfcParse::get_SI_equivalent<Ifc4x1>(Ifc4x1::IfcNamedUnit* named_unit);
template double IfcParse::get_SI_equivalent<Ifc4x2>(Ifc4x2::IfcNamedUnit* named_unit);
template double IfcParse::get_SI_equivalent<Ifc4x3_rc1>(Ifc4x3_rc1::IfcNamedUnit* named_unit);

**Comment by aothms** [comment]
Hi, thank you, can you submit this as a pull request please https://github.com/IfcOpenShell/IfcOpenShell/pulls ? It'll avoid interpretation errors and track authorship.

**Comment by Moult** [comment]
Seems to be resolved https://github.com/IfcOpenShell/IfcOpenShell/discussions/5102
