### ISSUE TITLE
BlenderBIM: missing 2D object property documentation tags 

### ISSUE THREAD

**Issue by JanFilipec** [IfcOpenShell/IfcOpenShell#912]
Is there already a concept for object property tags? To create a complete professional project documentation we need a way to label our model objects to show the I part of BIM in 2d. The property tag should read any property of the linked object and display it (similar to dimensions reading the linked curves length and showing it as text) and be as universal and customizable as possible.
Most common uses:
-Room tags (with number, name, area, floor material, ...)
-Fire ratings
-Materials, structure composition 
-Parametric object (door, window) sizes
-Ids
-Staircase tags

**Comment by Moult** [comment]
This feature exists.

See https://peertube.social/videos/watch/021a6574-b175-4c43-b83d-6a133c54a199 - around 30:00 onwards, I demonstrate how to associate text with objects and read parameters.

To read an attribute, just type its name properly, e.g.: `GlobalId` or `Name`.

To read a pset, you need both the psetname and property name, like `Pset_WallCommon.Reference`

To read a Qto, you need both the qto name and property name, like `Qto_WallBaseQuantities.Length`

You can apply extra functions with Python, like `round({{BaseQuantities.GrossFloorArea}},1)`

Hope it helps!

**Comment by JanFilipec** [comment]
Ah, great, I'll look into it, thanks!
