### ISSUE TITLE
Is it possible to interrogate the IFC schema without needing to create a file object?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#913]
Is it possible in Python, to ask IfcOpenShell what are the attributes of an IFC entity, say IfcPerson, without needing to create a file object and an IfcPerson entity object?

That would allow me to generate some of the Blender data models without needing to hardcode them.

**Comment by aothms** [comment]
Yes, but it's only available yet in `ifcopenshell.ifcopenshell_wrapper.` so it's a bit rough, but workable. Best example of its usage is in validate.py https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/validate.py#L77

**Comment by Moult** [comment]
Awesome! Thanks!
