### ISSUE TITLE
IfcStyledItem with no IfcPresentationStyleAssignment breaks material detection

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#915]
According to [here](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcstyleditem.htm), IfcPresentationStyleAssignment has been deprecated.

I have two tiny files, which are almost identical and only contain a single object which has two cubes, each its own representation item. The only difference is one has the assignment, and the other doesn't, which directly goes to the IfcPresentationStyle.

![image](https://user-images.githubusercontent.com/88302/87220083-5bc65980-c3a4-11ea-969d-4cb91b18f7b4.png)

[color-no-assignment.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4906497/color-no-assignment.ifc.txt)

[color-with-assignment.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4906498/color-with-assignment.ifc.txt)

The following minimum code demonstrates the issue:

```
import multiprocessing
import ifcopenshell
import ifcopenshell.geom
ifc_file = ifcopenshell.open('/home/dion/color-with-assignment.ifc') # Change this line
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
valid_file = iterator.initialize()
while True:
    shape = iterator.get()
    print(shape.geometry.materials)
    if not iterator.next():
        break
```

When run on the "with assignment" file, you will see a tuple returned with 2 items of `ifcopenshell.ifcopenshell_wrapper.Material`, one representing "red" and the other "blu", as expected. However, when run on the "no-assignment" file, a blank tuple will be returned instead.

I'm a little puzzled since I thought I had tested this in the past, so I'm not sure if it is a recent regression or if I'm missing something completely.

**Comment by aothms** [comment]
Thanks these are very useful. I had no idea. Definitely not something that has ever worked. I added them here https://github.com/IfcOpenShell/files/commit/3ebc369438d7c918a40e60b7f69822e8465f0546 and https://github.com/IfcOpenShell/IfcOpenShell/issues/915 should fix this

**Comment by Moult** [comment]
Thanks :) Just a heads up that although it is deprecated, some vendors (Revit) still export IFC4 with the presentation style assignment. Therefore, IfcOpenShell should (for the moment) support both variants - I'm not familiar enough with the codebase to know if your commit does this :)

**Comment by aothms** [comment]
It does. That's why I never encountered it probably. It's really messy to
handle both the different schemas and code paths in the same function.

Thomas


Op za 11 jul. 2020 om 11:56 schreef Dion Moult <notifications@github.com>:

**Comment by Moult** [comment]
Cheers :) I'll wait for the bot to wake up and I'll test again on both files to confirm it works before closing.

Thanks again!

**Comment by Moult** [comment]
Fixed in latest bot build! Thanks so much!
