### ISSUE TITLE
Unable to open multiple BSi example files (IFC4x1)

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#917]
Hi,
I was looking for a proper example of IfcMaterialProfileSetUsage for OSArch wiki in IFC documentation and have been unable to open any of the IFC documentation beam examples.
# Version
ifcopenshell git freshly compiled on commit 20303ed
# Step to reproduce
```python
import traceback
import requests
import ifcopenshell

urls = (
"https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/beam-standard-case.ifc",
"https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/beam-revolved-solid.ifc",
"https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/beam-extruded-solid.ifc",
)

for url in urls:
    try:
        file = requests.get(url)
        ifc = ifcopenshell.open(file.content.decode())
    except IOError as err:
        print(f"\n{url}")
        traceback.print_exc()
```
# Error message (output)
```python
https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/beam-standard-case.ifc
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3.8/site-packages/ifcopenshell/__init__.py", line 67, in open
    raise IOError("Unable to open file for reading")
OSError: Unable to open file for reading

https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/beam-revolved-solid.ifc
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3.8/site-packages/ifcopenshell/__init__.py", line 67, in open
    raise IOError("Unable to open file for reading")
OSError: Unable to open file for reading

https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/beam-extruded-solid.ifc
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3.8/site-packages/ifcopenshell/__init__.py", line 67, in open
    raise IOError("Unable to open file for reading")
OSError: Unable to open file for reading
```

**Comment by aothms** [comment]
Yeah these things are frustrating. The schema identifier in these files is `IFC4x1`. With a lower case `x`. Not sure if that should be treated case-insensitively (I think there is a reasonable chance it should be, but these things are so tedious to lookup), but for the time being the supported schema is `IFC4X1` with capital `X`.

**Comment by aothms** [comment]
Oh, it's easy to lookup, and IfcOpenShell's treatment is correct. At least according to the 2016 version (which we do not use)

> 8.2.4 file_schema
> 
> The file_schema entity identifies the EXPRESS schemas that specify the entity instances in the data sections. The attribute schema_identifiers shall consist of a list of strings, each of which shall contain the name of the schema optionally followed by the object identifier assigned to that schema.
> 
> If the name of a schema contains small letters, such small letters shall be converted to the corresponding capital letters. **Only capital letters shall occur in strings of the schema_name**. 

(emphasis mine)

**Comment by CyrilWaechter** [comment]
I can't find quotation source. I suppose it is in IFC Documentation but where ?

**Comment by Moult** [comment]
@CyrilWaechter https://standards.buildingsmart.org/documents/Implementation/ImplementationGuide_IFCHeaderData_Version_1.0.2.pdf

https://technical.buildingsmart.org/resources/ifcimplementationguidance/

**Comment by aothms** [comment]
It's the ISO 10303 21 standard. Not freely available

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op za 18 jul. 2020 12:07 schreef Cyril Waechter <notifications@github.com>:

**Comment by CyrilWaechter** [comment]
Many topics on BS forum about it :smile: ([FILE_SCHEMA vs. Schema Version](https://forums.buildingsmart.org/t/file-schema-vs-schema-version/2750), [Versioning in the IFC-file](https://forums.buildingsmart.org/t/versioning-in-the-ifc-file/2796), [About IFC Header section](https://forums.buildingsmart.org/t/about-ifc-header-section/2522/9)). I saw some of them before but now I see consequences.

I tried to find some way to make a pull request to correct examples but even 4.3 branch on IFC repo is 'IFC4' and file seems to be produced from IfcKit from I don't know where. Even in IfcKit folder from [IfcDoc repo](https://github.com/buildingSMART/IfcDoc) it is 'IFC4' no matter the branch.

**Comment by aothms** [comment]
Thanks for you effort in trying to fix this. 

So there are schema versions and addenda/corrigenda, so IFC4 has the same identifier as IFC4 Add1 and IFC Add2 TC1. That's indeed potentially problematic when you have very strict importers, but in practice I don't think it'll lead to real issues as the compatibility with file based exchange is well considered for these updates.

But IFC4X1 is a completely different version from IFC4, so it's not really related to the discussions on the forums and indeed as you say should definitely not get IFC4 as the schema identifier in the file.

I don't know anything about IfcKit, but yeah the approach using branches for schema versions is problematic. Extra odd is that for example there appear to be no differences between the 4X1 and 4X2 branches. I wouldn't spend too much effort in trying to fix this https://github.com/buildingSMART/IfcDoc/compare/IFC4x1...IFC4x2

But perhaps a PR to fix the ifc files in the repos is a good idea.

**Comment by Moult** [comment]
BTW, here's a "freely available" version of ISO 10303-21 :) http://www.steptools.com/stds/step/IS_final_p21e3.html

I've got the actual version, and on brief comparison with the online link above, it is almost identical I think, but I haven't checked in detail.

**Comment by Moult** [comment]
Closing as non-issue in IfcOpenShell :)
