### ISSUE TITLE
[BlenderBIM] TBB usage ?

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#918]
I don't see any usage of TBB. Can you tell me why it is included in makefile ?
https://github.com/IfcOpenShell/IfcOpenShell/blob/20303ed6a83a91ff2a7c73b10203b7f8891f5b80/src/ifcblenderexport/Makefile#L15

**Comment by aothms** [comment]
The conda builds of occt are probably compiled with TBB enabled. Since @Moult get's them from conda, he needs to get their dependencies.

**Comment by Moult** [comment]
@aothms correct :)

**Comment by CyrilWaechter** [comment]
So I don't need to add it as a dependency. Thanks !
