### ISSUE TITLE
ifcclash fcl dependency not available for python 3.8

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#919]
I am very much interested in ifcclash but I am a little worried about python-fcl dependency :
* No python 3.8 wheel is available from pypi for [python-fcl](https://pypi.org/project/python-fcl/)
* Building python-fcl from source is complicated as it depends on fcl 0.5.0 (current version is 0.6.1 see issue https://github.com/BerkeleyAutomation/python-fcl/issues/19).
* python-fcl seems to be inactive since june 2019.

On the good side there is 2 PR to port it to fcl 0.6 but they were made in march and april but non have been merged at the moment : 
* https://github.com/BerkeleyAutomation/python-fcl/pull/21
* https://github.com/BerkeleyAutomation/python-fcl/pull/20

**Comment by Moult** [comment]
FCL is also not distributed for Mac :(

I wish I had a solution :(

**Comment by CyrilWaechter** [comment]
For mac you might try to use : https://anaconda.org/jf/python-fcl/files
A build is available for python 3.8 : https://anaconda.org/jf/python-fcl/0.6.0/download/osx-64/python-fcl-0.6.0-py38h39e3cac_1.tar.bz2
I assume it was made by @jf--- whom I saw also around pythonocc, pyOCCT etc…

**Comment by Moult** [comment]
@CyrilWaechter I'm looking for Python 3.7, since the Python version must match the version used by Blender. But thanks for the link :)

**Comment by CyrilWaechter** [comment]
I have been able to compile python-fcl thanks to [DmitryNeverov fork](https://github.com/DmitryNeverov/python-fcl) with a small fix https://github.com/DmitryNeverov/python-fcl/pull/1.
It depends on fcl 0.6.1. I used [fcl AUR package](https://aur.archlinux.org/packages/fcl) but fcl is really easy to compile it should be simple to reproduce on any platform.

Can you explain briefly how ifcclash works in blender so I can test if it works without issue ?
I created 2 cubes of class IfcAirTerminal and tried this config :
![image](https://user-images.githubusercontent.com/9622862/88335476-a98f7a00-cd33-11ea-972d-1de2d93170d8.png)
I see a .json file but it apparently without any clash inside.

**Comment by Moult** [comment]
What you've done looks correct. I have just tested with two files of the default cube and I do indeed get a clash result. The resulting JSON file created by executing IFC clash should look something like the following:

```
[
    {
        "name": "New Clash Set",
        "tolerance": 0.009999999776482582,
        "a": [
            {
                "file": "/home/dion/drive/bim/a.ifc",
                "selector": ".IfcBuildingElementProxy",
                "mode": "i"
            }
        ],
        "b": [
            {
                "file": "/home/dion/drive/bim/b.ifc",
                "selector": ".IfcBuildingElementProxy",
                "mode": "i"
            }
        ],
        "clashes": {
            "0x4qYS0_DAPuPscMo8tRsN-2I1UDajiL3IfFIlUGmbYYK": {
                "a_global_id": "0x4qYS0_DAPuPscMo8tRsN",
                "b_global_id": "2I1UDajiL3IfFIlUGmbYYK",
                "a_ifc_class": "IfcBuildingElementProxy",
                "b_ifc_class": "IfcBuildingElementProxy",
                "a_name": "Cube",
                "b_name": "Cube",
                "normal": [
                    -1.0,
                    0.0,
                    0.0
                ],
                "position": [
                    -1.0,
                    -1.0,
                    1.0
                ],
                "penetration_depth": 2.0
            }
        }
    }
]
```

**Comment by CyrilWaechter** [comment]
I get result like yours running it from full packaged blender bim addon on windows without issue. Issue apparently comes from a type input change inside fcl.Transform :
```python
python ifcclash.py "/home/cyril/Documents/Blender/clash_test.json" --output="/home/cyril/Documents/Blender/clash_test.json"
Creating collision manager a ...
Loading files a ...
Purging unnecessary elements a ...
Creating collision data for a ...
[#########################                         ]Creating object #84=IfcAirTerminal('1pW0h7YWP4O8PXtP5Xbd1x',$,'Cube',$,$,#75,#83,$,.DIFFUSER.)
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
Exception ignored in: 'fcl.fcl.numpy_to_mat3d'
Traceback (most recent call last):
  File "/home/cyril/.config/blender/2.83/scripts/addons/blenderbim/libs/site/packages/collision.py", line 195, in add_object
    t = fcl.Transform(transform[:3, :3], transform[:3, 3])
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
Exception ignored in: 'fcl.fcl.numpy_to_vec3d'
Traceback (most recent call last):
  File "/home/cyril/.config/blender/2.83/scripts/addons/blenderbim/libs/site/packages/collision.py", line 195, in add_object
    t = fcl.Transform(transform[:3, :3], transform[:3, 3])
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
Creating collision manager b ...
Loading files b ...
Purging unnecessary elements b ...
Creating collision data for b ...
[#########################                         ]Creating object #84=IfcAirTerminal('0_sCMOjkr8hfXc12UIa2AS',$,'Cube',$,$,#75,#83,$,.DIFFUSER.)
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
Exception ignored in: 'fcl.fcl.numpy_to_mat3d'
Traceback (most recent call last):
  File "/home/cyril/.config/blender/2.83/scripts/addons/blenderbim/libs/site/packages/collision.py", line 195, in add_object
    t = fcl.Transform(transform[:3, :3], transform[:3, 3])
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
Exception ignored in: 'fcl.fcl.numpy_to_vec3d'
Traceback (most recent call last):
  File "/home/cyril/.config/blender/2.83/scripts/addons/blenderbim/libs/site/packages/collision.py", line 195, in add_object
    t = fcl.Transform(transform[:3, :3], transform[:3, 3])
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```
I don't know numpy a lot. I'll investigate more later.

**Comment by aothms** [comment]
From the looks of it, wrapping `transform` in a `numpy.float64()` might fix
that

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op za 25 jul. 2020 17:07 schreef Cyril Waechter <notifications@github.com>:

**Comment by CyrilWaechter** [comment]
> From the looks of it, wrapping `transform` in a `numpy.float64()` might fix that

@aothms you were absolutely right. Thanks.

**Comment by Moult** [comment]
Closing bug, as the BlenderBIM Add-on is Python 3.7 based, and so getting fcl distributed for Python 3.8 should be an upstream issue.
