### ISSUE TITLE
Question on using options with IfcConvert

### ISSUE THREAD

**Issue by pump-kin** [IfcOpenShell/IfcOpenShell#92]
I am trying to convert an ifc to either obj or dae and am having problems with the --include, --exclude and --entities options with version 0.5.0. I am trying to extract spaces only but when I run the command no errors are formed and no output is created (tried --include --entities IfcSpace and --exclude --entities IfcOpeningElement and --include --entities IfcWall). Tried on Windows and on Mac OS. The ifc I'm using has spaces, walls, and several other types. I'm able to convert to obj and dae without specifying any options. Any solutions out there?

**Comment by aothms** [comment]
This seems to be identical to #93? Have a look there for a solution.
