### ISSUE TITLE
ifcopenshell.geom.iterator generates duplicated shapes when initialize() is called more than once

### ISSUE THREAD

**Issue by mieszk** [IfcOpenShell/IfcOpenShell#921]
When I create an `ifcopenshell.geom.iterator` in Python with multiprocessing support and call `initialize()` more than once, iterator generates duplicated shapes. This happens only when using multiple threads, with `num_threads=1` everything works OK.

Here is a table which shows what happens for one IFC file. `num_threads` is the number of threads used in iterator and `num_inits` is the number of times `iterator.initialize()` was called before retrieving shapes.

| num_threads | num_inits | created shapes | processing time |
|-------------|-----------|----------------|-----------------|
| 1           | 1         | 28             | 7s              |
| 1           | 2         | 28             | 7s              | 
| 2           | 1         | 28             | 4.5s            |
| 2           | 2         | 84             | 12s             |
| 3           | 2         | 84             | 11s             |
| 2           | 3         | 168            | 23s             |

I used the latest version (f1ed9d5b) of IfcOpenShell with opencascade 7.4.0.

**Comment by aothms** [comment]
Ok, I can see how this happens as there are internal lists of representations and products filled during `initialize()`. What do you see as the solution? A simple boolean flag that is set so that a 2nd call to `initialize()` would return immediately? Throw an exception? Reinitialize to pick up potential changes is in the file? Or just document properly?

**Comment by mieszk** [comment]
@aothms I encountered it when I called `iterator.initialize()` first and then used `for x in iterator`, which initialized it again in the `__iter__()` method. Regarding solutions that you mentioned, in my opinion:
- boolean flag `is_initialized`: will prevent cases similar to mine, but as you point out, someone may want to re-initialize the file
- re-initialization is OK, it may cause some overhead for large files but I don't know if it will be that much
- throwing an exception may be not necessary and documentation will be useful but don't solves the problem

I'd go for re-initialization, or maybe re-initialize the iterator when `initialize()` is called explicitly and keep a boolean flag `is_initalized` for `__iter__()` (and other) purposes. What do you think?

**Comment by aothms** [comment]
I will do the boolean flag, the reinitialization is error-prone as the iterator class keeps a lot of state and it not very well written.

**Comment by mieszk** [comment]
Fixed, thanks
