### ISSUE TITLE
use entity STEP id for naming elements upon serialization in IfcConverter

### ISSUE THREAD

**Issue by ifcwebserver** [IfcOpenShell/IfcOpenShell#923]
Dear Thomas,
is it possible to add a new parameter "--use-element-stepid" for  naming elements upon serialization in IfcConverter, or maybe this is already possible? 
This option is available in the IfcBlender as alternative to using the object names

                                       f

**Comment by Moult** [comment]
@ifcwebserver just a heads up that the option is no longer available in Blender - the IfcBlender you see is a bit outdated.

Why is this function useful? I would think GUIDs are more useful, as the STEP ID is only STEP specific, and so should not be treated as semantic data?

**Comment by ifcwebserver** [comment]
@Moult & @aothms 
Thank you for the quick response

I use the STEP ID for low level geometry inquiring & extraction, for example to filtering out a small part of the whole model (through recursive fetching of related STEP IDs ) and also for database management of element properties.

With GUIDs in Blender I faced some problem when saving the model into other formats like COLLADA that special characters like $ can not be saved (they will be replaced with "_" ) or with GUIDs which start with a number, the first number will be replaced with "_"

**Comment by Moult** [comment]
@ifcwebserver have you used the latest version at https://blenderbim.org/

If it is useful to you, I can add a feature to import using STEP IDs.

**Comment by aothms** [comment]
> With GUIDs in Blender I faced some problem when saving the model into other formats like COLLADA that special characters like $ can not be saved (they will be replaced with "" ) or with GUIDs which start with a number, the first number will be replaced with ""

**Comment by Moult** [comment]
Closing as implemented.
