### ISSUE TITLE
blenderbim / luxcore 2.4 libtbb conflict

### ISSUE THREAD

**Issue by s-leger** [IfcOpenShell/IfcOpenShell#926]
When installed, 
libtbb.so.2 conflict with luxcore render 2.4 libtbb.so.2 version and prevent luxcore installation. (missing symbol)

**Comment by Moult** [comment]
Closing as workaround is documented in Wiki. I don't yet feel safe to steal their TBB.

https://wiki.osarch.org/index.php?title=BlenderBIM_Add-on_installation#Known_issues
