### ISSUE TITLE
No normals are generated when calling geom.create_shape

### ISSUE THREAD

**Issue by sharon-br** [IfcOpenShell/IfcOpenShell#927]
Hey,
I'm pretty new with the IFC format and the IfcOpenShell library so I'm not sure if I'm doing something wrong or just missing something.
I'm trying to get the faces of some element + get the normal vector for each of those faces.
Since I think the regular triangulation is good enough for me I'm not setting the USE_PYTHON_OPENCACSE settings and just working with the default one.

I've tried writing the following code:
```
import ifcopenshell
from ifcopenshell import geom

ifc_file = ifcopenshell.open('file.ifc')
element = f.by_id('...')
geom_settings = geom.settings()

# Also tried geom.settings.set(geom_settings.NO_NORMALS, False) just to be sure

shape = geom.create_shape(geom_settings, element)
```

When printing shape.geometry.faces, and shape.geometry.verts I get valid data.
When printing shape.geometry.normals I get an empty tuple - What am I missing here? Is there a different way to get the normal for each face?

**Comment by aothms** [comment]
Yes, this is not properly documented (feel free to make a note somewhere about this in the examples or documentation). The default is that vertices are 'welded' based on their position - as this made most sense for import in modelling applications. In that case I think vertex normals don't make a lot of sense (although we could compute them as an average of the face normals that the vertex belongs to).

So what you need to do is `geom_settings = set(geom_settings.WELD_VERTICES, False)`.

**Comment by sharon-br** [comment]
So after changing this settings I can what appears as the vertices normals and not the faces normals right?
To get the triangle normal should I just average the normals of the three vertices?
Do triangles with the same normal are defining a face?

I'm thinking about the case of a cube, the triangulation doesn't really return the triangles of each of the 6 faces separately but rather all the triangles of the elements - so how do I separate an element into its individual faces? what about a more spherical element?

**Comment by aothms** [comment]
> So after changing this settings I can what appears as the vertices normals 

indeed

> so how do I separate an element into its individual faces?

With `WELD_VERTICES=False` triangles with shared vertices are derived from the same original face. This is the case for planar as well as non-planar faces.

**Comment by sharon-br** [comment]
> > So after changing this settings I can what appears as the vertices normals
> 
> indeed
> 
So how do I get the triangle normal? averaging the 3 vertices normals seems a bit strange since the vertex normal is calculated by averaging all the shared triangles normals if I under it correctly.

> > so how do I separate an element into its individual faces?
> 
> With `WELD_VERTICES=False` triangles with shared vertices are derived from the same original face. This is the case for planar as well as non-planar faces.

Not really sure what you mean here

**Comment by aothms** [comment]
> vertex normal is calculated by averaging all the shared triangles normals if I under it correctly.

No that's not what I meant. I meant we **could** compute them by averaging when WELD_VERTICES=True. There is no averaging in the computation. Just sampling the Face surface at the UV position of the vertex.

> Not really sure what you mean here

If you have triangle indices `[{0,1,2}, {0,2,3}, ...]` you know the triangles are part of the same face because the numeric indices are shared. In the case of `[{0,1,2}, {3,4,5}, ...]` the triangles are from distinct faces.

**Comment by Moult** [comment]
@Jesusbill accidental pin? :)

**Comment by Jesusbill** [comment]
Oops, yes :)

**Comment by Moult** [comment]
I think this can be closed, https://blenderbim.org/docs-python/ifcopenshell/geometry_settings.html#weld-vertices already documents how weld vertices naturally discards normals.
