### ISSUE TITLE
IfcConvert geometry deformation

### ISSUE THREAD

**Issue by ghost** [IfcOpenShell/IfcOpenShell#928]
IfcConvert was working until IfcConvert-v0.6.0-9bcd932 but now deforms the geometry of an element (with latest official 0.6.0 release and latest commit on 0.6.0 branch).

Here is the test file (sorry about the file size, we've had trouble to isolate the element) :
[object.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4964833/object.ifc.zip)

Expected visual (preview of ifc in a viewer) :
![expect](https://user-images.githubusercontent.com/49783526/88267964-e9257a00-ccd1-11ea-8351-9088f457a25b.png)

Result from IfcConvert-0.6.0b0-4baec57 (glb and dae) :
![result](https://user-images.githubusercontent.com/49783526/88268634-0c9cf480-ccd3-11ea-905e-11bc0d2ef68d.png)

**Comment by aothms** [comment]
Thanks. I think the commit message speaks for itself. I think this was broken longer than you indicate though. I uploaded the file here https://github.com/IfcOpenShell/files/blob/master/928-column.ifc

**Comment by Blocovin** [comment]
It's work ! Thanks a lot for the fix !

**Comment by Blocovin** [comment]
@aothms We got the same problem with another IfcColumn (geometry was deformed) with ifcConvert v0.6.0-3440dd4.
[ifc_column.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5226145/ifc_column.ifc.zip)

**Comment by Moult** [comment]
Looks fine here with the latest release :)

![2022-09-03-203416_237x502_scrot](https://user-images.githubusercontent.com/88302/188266643-58868145-8632-4ed3-a280-fa4c915ccdcc.png)
