### ISSUE TITLE
Segmentation fault on closed loop swept disk solid

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#939]
See attached tiny IFC file which demonstrates this issue. Sample code will cause crash. XBim screenshot displays it correctly.

[grease.blend.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4998655/grease.blend.ifc.txt)

![image](https://user-images.githubusercontent.com/88302/88878656-be0bcf00-d26b-11ea-9189-d4ab8e6c9fc6.png)

```
import ifcopenshell
import multiprocessing
import ifcopenshell.geom

f = ifcopenshell.open('grease.blend.ifc')
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, f, multiprocessing.cpu_count())
iterator.initialize()

def process_shape(shape):
    shape = iterator.get()
    element = f.by_id(shape.guid)

while True:
    process_shape(iterator.get())
    if not iterator.next():
        break

print('Done')
```

**Comment by aothms** [comment]
Is that what I think it is? Grease pencil? That's cool, the file processes now, but the triangulation is a bit weird.

**Comment by Moult** [comment]
@aothms good spot!

Read more here: https://community.osarch.org/discussion/143/3d-concept-sketching-with-greasepencil-and-ifc/p1?new=1

Might be fun :)

**Comment by Moult** [comment]
Just tested with the latest bot build, and I get an empty `geometry.faces`, `geometry.edges`, and `geometry.verts`, though there is no segfault. Ideas?

**Comment by aothms** [comment]
Hm can confirm. I had 7.4.0 in my local dev env. As I said the triangulation was weird, but there was something. But indeed for 7.3.0 the triangulation fails altogether. I have added yet another preprocessing step to the sweep wire. The closed loop is now simply split into two parts. So there is some small artefacts where at two places the sweep is not nicely joined, but at least it works.

The difference with xBim is that IfcOpenShell uses another OCCT transition mode, "StraightCorners" vs "Transformed" in xBim and frankly this has caused quite a bit of issues. I don't want to change now though, so I'd rather work around it.

**Comment by Moult** [comment]
Closing and confirming as fixed :)
