### ISSUE TITLE
BlenderBim - Missing "Assign Shortcut" operator on Import\Export IFC

### ISSUE THREAD

**Issue by Krande** [IfcOpenShell/IfcOpenShell#942]
Hello,

I seem to be missing the option for assigning hotkeys for the "import" and "export" option for IFC files using the BlenderBim addon. I remember in the early builds this was possible, but this option is no longer available (latest addon version I have tested is BlenderBim 0.0.200722). 

**Import**
![image](https://user-images.githubusercontent.com/9642232/89029726-50c17200-d32f-11ea-9b36-9a89edfa39f0.png)

**Export**
![image](https://user-images.githubusercontent.com/9642232/89029839-8b2b0f00-d32f-11ea-9de3-47545c74a2e0.png)

**For reference**
Here is an example of the "Assign Shortcut" option for the FBX import.
![image](https://user-images.githubusercontent.com/9642232/89029984-d2b19b00-d32f-11ea-80af-1f32d920fb99.png)

To test if this is just a bug on my pc, I have tried installing the addon on multiple pc's with Blender 2.83.3 + BlenderBim 0.0.200722 installed and all of them seem to be missing the assign shortcut option. I also tried digging into the code for the FBX import\export addon and see if I could spot any obvious differences (compared to BlenderBim) that would explain the missing Assign shortcut operator (but so far I haven't found anything specific).

As you would expect, this is not a big deal, but I find myself having to use the import and export options quite often, and having the option to assign a hotkey would improve my current work flow quite a bit! So in the hopes that this might be a "quick fix" I would surely appreciate having this option "re-enabled" :)

Best Regards
Kristoffer

**Comment by Moult** [comment]
Quirky one! Fixed: https://github.com/IfcOpenShell/IfcOpenShell/commit/8ad9c215af672bdc5ff034ac1ec48536fc7249dd

Ping @s-leger - this fix may bork things up in Archipack.
