### ISSUE TITLE
Can ifcopenshell.file.remove() be faster?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#944]
I've been working on IFC files of approximately 100MB and above. On these files, running the `remove(element)` function is a relatively slow procedure, especially when looping on many thousands of elements.

Is there a faster way? What if I have already removed all references to the entity so it doesn't need to check?

**Comment by aothms** [comment]
It has to do a lot of stuff. Update all the mappings (id, guid, type, inverse pointing to deleted and inverse reachable from deleted) especially inverse is slow. It might be faster to actually build up a new file. My colleague @johltn is working on a tutorial using that approach also for optimization. It should be up soon.

**Comment by Moult** [comment]
@aothms I tried building up a new file but found my little workaround for my particular usecase to be more efficient. I'll close this bug, as it isn't particularly constructive - was just hoping I missed something. If you or your colleague @johltn has any clever tricks on optimising IFCs, would be glad to hear it too :) 

Here's my "quick" attempt, with known shortcomings:

https://github.com/IfcOpenShell/IfcOpenShell/blob/277786771cb8c7dc0b40cccefbbed15b600067f6/src/ifcpatch/recipes/RecycleNonRootedElements.py

https://community.osarch.org/discussion/151/new-ifc-optimiser-tool - a thread describing the initiative and comparing to Solibri's optimiser.
