### ISSUE TITLE
IndexedPolyCurve for opening element not rendered

### ISSUE THREAD

**Issue by Krande** [IfcOpenShell/IfcOpenShell#945]
Hello,

I am testing a couple of negative extrusions applied on a IfcBeam and found that one of the details are not rendered in Blender (using BlenderBim v200722) but is (strangely enough) rendered using XBim. I think this could just as likely be caused by errors in my Ifc file, so I have attached that as well.

[penetrations_mix_ifc_file.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5040182/penetrations_mix_ifc_file.zip)

Image from XBim showing the desired result:
![image](https://user-images.githubusercontent.com/9642232/89625276-ea40d480-d897-11ea-9f0c-e19663e3ad42.png)

Image from Blender with missing negative extrusion on the farthest left:
![image](https://user-images.githubusercontent.com/9642232/89625286-edd45b80-d897-11ea-8d45-d5be3a260504.png)

Xbim gives following validation warning\error messages:

	Entity #5 (IfcOwnerHistory) has validation failures.
		Issue of type EntityWhereClauses on IfcOwnerHistory.CorrectChangeAction.
	Entity #11 (IfcGeometricRepresentationContext) has validation failures.
		Issue of type EntityWhereClauses on IfcGeometricRepresentationContext.North2D.
	Entity #74 (IfcIndexedPolyCurve) has validation failures.
		Issue of type EntityWhereClauses on IfcIndexedPolyCurve.Consecutive.
	Entity #75 (IfcArbitraryClosedProfileDef) has validation failures.
		Issue of type EntityWhereClauses on IfcArbitraryClosedProfileDef.WR1.
	Entity #81 (IfcExtrudedAreaSolid) has validation failures.
		Issue of type EntityWhereClauses on IfcExtrudedAreaSolid.ValidExtrusionDirection.
	Entity #92 (IfcIndexedPolyCurve) has validation failures.
		Issue of type EntityWhereClauses on IfcIndexedPolyCurve.Consecutive.
	Entity #93 (IfcArbitraryClosedProfileDef) has validation failures.
		Issue of type EntityWhereClauses on IfcArbitraryClosedProfileDef.WR1.
	Entity #99 (IfcExtrudedAreaSolid) has validation failures.
		Issue of type EntityWhereClauses on IfcExtrudedAreaSolid.ValidExtrusionDirection.
	Entity #110 (IfcIndexedPolyCurve) has validation failures.
		Issue of type EntityWhereClauses on IfcIndexedPolyCurve.Consecutive.
	Entity #111 (IfcArbitraryClosedProfileDef) has validation failures.
		Issue of type EntityWhereClauses on IfcArbitraryClosedProfileDef.WR1.
	Entity #117 (IfcExtrudedAreaSolid) has validation failures.
		Issue of type EntityWhereClauses on IfcExtrudedAreaSolid.ValidExtrusionDirection.
	Entity #153 (IfcArbitraryClosedProfileDef) has validation failures.
		Issue of type EntityWhereClauses on IfcArbitraryClosedProfileDef.WR1.

I will continue try to make sense of this myself, but any help along the way would be much appreciated!

Best Regards
Kristoffer

**Comment by Moult** [comment]
A unrelated issue, but thought I'd mention it, in BlenderBIM you can run an IfcOpenShell validation, which will print the results in the console. IfcOpenShell doesn't check the WHERE rules like XBim does, so XBim will return more things that IfcOpenShell won't. When I ran it, it came up with this issue:

```
2020-08-07 20:25:23,015    ERROR validate.py 91 In #39=IfcRelContainedInSpatialStructure('0KO0yNs8OHweMg66RQ4Ggf',#5,'Physical model',$,(),#26)
() not valid for <attribute RelatedElements: <set [1:?] of <entity IfcProduct>>>
```

It doesn't relate to your missing void I believe, but perhaps worth noting.

Here's how you run the validate feature:

![image](https://user-images.githubusercontent.com/88302/89636976-d4a9ca00-d8ec-11ea-8b2b-70cee138eaf1.png)

**Comment by aothms** [comment]
```
#73=IFCCARTESIANPOINTLIST3D(((0.1,-0.1,-0.1),(0.2,-0.1,-0.1),(0.15,-0.1,0.),(0.1,-0.1,-0.1),(0.2,-0.1,-0.1)));
#74=IFCINDEXEDPOLYCURVE(#73,(IFCLINEINDEX((1,2)),IFCLINEINDEX((2,3)),IFCLINEINDEX((3,4)),IFCLINEINDEX((4,1))),$);
```

The last lineindex (4,1) is degenerate. Both 1 and 4 are (0.1,-0.1,-0.1). There's a 5th unreferenced point. Keep in mind indices in EXPRESS are 1-based.

Keep the issue open please. I'll fix this. But in the mean time you can correct it in your file as well.

**Comment by Krande** [comment]
Ah, you are absolutely correct.

My intention in the IFC file was most likely this:

	#73=IFCCARTESIANPOINTLIST3D(((0.1,-0.1,-0.1),(0.2,-0.1,-0.1),(0.15,-0.1,0.)));
	#74=IFCINDEXEDPOLYCURVE(#73,(IFCLINEINDEX((1,2)),IFCLINEINDEX((2,3)),IFCLINEINDEX((3,1))),$);

which is rendered as expected

![image](https://user-images.githubusercontent.com/9642232/89639783-81b12200-d8ae-11ea-8ebb-df635ccc69d0.png)

Thanks a lot for this, that solved things on my end! Ready to close when you are.

**Comment by aothms** [comment]
Cool, yeah just put in a commit to step over the degenerate edges. Other ifc rep types have more extensive checking enabled still though, but that's not coming in v0.6 anymore.
