### ISSUE TITLE
Segmentation fault converting ifc to dae

### ISSUE THREAD

**Issue by htlcnn** [IfcOpenShell/IfcOpenShell#947]
I'm using IfcConvert to convert IFC to DAE. Conversion failed:
```
$ IfcConvert --use-element-guids --site-local-placement DHCT_MEP.ifc DHCT_MEP.dae
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
Scanning file...
Done scanning file
Parsing input file took 14 seconds
Creating geometry...
[###########################                       ][1]    12761 segmentation fault (core dumped)  IfcConvert --use-element-guids --site-local-placement DHCT_MEP.ifc
```
Here's IFC file zipped: https://drive.google.com/file/d/1fBHIdfHqM2AfUWfcyKfaEhQAJV3MBwQu/view?usp=sharing

**Comment by aothms** [comment]
The file converts ok here, after a quick check on Windows at least. My guess is you ran out of memory. Do you use a 64bit version?

**Comment by htlcnn** [comment]
I used latest IfcOpenBot build for linux 64-bit, ran on WSL UBUNtu 18.04. Conversion succeeded. Last time BlenderBIM addon succeeded. That may be due to old IfcConvert version. Thanks!
