### ISSUE TITLE
IfcSpace, assignment

### ISSUE THREAD

**Issue by edwinguerra** [IfcOpenShell/IfcOpenShell#948]
In the Scene tools, you have to specify if you want to import IfcSpace elements. I have done so and successfully loaded a file, however, I am unable to isolate, interact or export to CSV. It is a use case that IfcSpaces could be created even if not in the source file, similarly, it would be useful to be able to export them via CSV exporter tool.

**Comment by Moult** [comment]
Exporting IfcSpaces works to CSV in my test just now. Type `.IfcSpace` (note: there is a `.` prefix). See example:

![image](https://user-images.githubusercontent.com/88302/90194937-b28fda80-de0b-11ea-938a-f2bad486cf69.png)

**Comment by edwinguerra** [comment]
Yes. Thank you Dion. I missed it and was working all along. However, I can't seem to find a way to assign geometry to IfcSpace. Is this possible?

**Comment by Moult** [comment]
@edwinguerra by "assign", perhaps you mean create a "contained in" relationship? If so, this is what you're looking for - an object will then be "inside" the "space". You can use the eyedrop function to easily pick the space object.

![image](https://user-images.githubusercontent.com/88302/90195775-ae64bc80-de0d-11ea-9f4c-2013a85a1cf0.png)
