### ISSUE TITLE
IfcConvert on Linux

### ISSUE THREAD

**Issue by bowerta** [IfcOpenShell/IfcOpenShell#949]
Hello

I am having some issues with converting from .ifc to .dae using IfcConvert.

I have an IFC2x3 file, which converts successfully in the Windows version.

The same file, when run the following through the Linux version,

> IfcConvert -v -y --use-element-guids /ifc/input/hello_wall/test1/hello_wall.ifc /ifc/output/hello_wall/test1/tmp/scene.dae

I get the following error: 

> Unable to write output file '/ifc/output/hello_wall/test1/tmp/scene.dae', see '/ifc/output/hello_wall/test1/tmp/scene.dae.tmp.ifcopenshell.QEUZIRGW.tmp.' for the conversion result.Creating directory: /ifc/output/hello_wall/test1

This creates a temporary file which ends in a dot. I am unable to delete or rename this temporary file, but copying it to scene.dae does seem to produce a valid file.

Any help on this would be greatly appreciated. Cheers.

**Comment by Amoki** [comment]
`/ifc/input/hello_wall/test1/hello_wall.ifc` is an absolute path, which propably doesn't exist.
Try with `./ifc/input/hello_wall/test1/hello_wall.ifc` ou just `ifc/input/hello_wall/test1/hello_wall.ifc`

**Comment by bowerta** [comment]
Thanks Hugo, unfortunately this did not fix the issue. The path is correct:

```
root@id:/ifc/input/hello_wall/test1# pwd
/ifc/input/hello_wall/test1
root@id:/ifc/input/hello_wall/test1# ls
hello_wall.ifc
```

IfcConvert does process the file, and does seem to produce a valid .dae file. However, it ends in .tmp.


```
root@id:/ifc/output/hello_wall/test1/tmp# pwd
/ifc/output/hello_wall/test1/tmp
root@id:/ifc/output/hello_wall/test1/tmp# ls
scene.dae.tmp.ifcopenshell.MDLKPDNB.tmp.
```

I cannot rename or delete this file, I think it relates to the filesystem, as files ending with a dot are generally forbidden.

```
root@id:/ifc/output/hello_wall/test1/tmp# mv scene.dae.tmp.ifcopenshell.MDLKPDNB.tmp. scene.dae
mv: cannot move 'scene.dae.tmp.ifcopenshell.MDLKPDNB.tmp.' to 'scene.dae': No such file or directory
root@id:/ifc/output/hello_wall/test1/tmp# rm scene.dae.tmp.ifcopenshell.MDLKPDNB.tmp. scene.dae
rm: cannot remove 'scene.dae.tmp.ifcopenshell.MDLKPDNB.tmp.': No such file or directory
```

I can, however, copy the file to the appropriate extension and go on to use it in subsequent conversions to .xkt
```
root@id:/ifc/output/hello_wall/test1/tmp# cp scene.dae.tmp.ifcopenshell.MDLKPDNB.tmp. scene.dae
root@id:/ifc/output/hello_wall/test1/tmp# ls
scene.dae  scene.dae.tmp.ifcopenshell.MDLKPDNB.tmp.
```

**Comment by aothms** [comment]
Hm yeah there was indeed a trailing dot in the temp file name. Somehow on Windows this was removed silently and didn't cause issues. I've removed it.

**Comment by bowerta** [comment]
Excellent, thanks Thomas
