### ISSUE TITLE
Implement express logical values as a boost::tribool

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#95]
Currently an EXPRESS LOGICAL type is mapped simply to BOOL, with (`.F.`, `.U.`) mapped to `false` and `.T.` to `true`. This is obviously wrong, but nobody ever seemed to be interested in actually supporting this. Recently these unclear semantics broke the parser (#94).

This can be implemented using a boost::tribool

http://www.boost.org/doc/libs/1_55_0/doc/html/boost/logic/tribool.html

**Comment by Moult** [comment]
Can this bug be closed?
