### ISSUE TITLE
BlenderBIM: Importing and maintaining multiple representation contexts

### ISSUE THREAD

**Issue by MaximilianFranz** [IfcOpenShell/IfcOpenShell#952]
### Problem 
- When roundtripping a model (import, export, import the exported model again), IfcShapeRepresentations that were in the original model are lost, as only the Body Representation is loaded into blenderBIM. 

- The same behaviour seems to occur for IfcRelConnectsPath Elements (i.e. connections between walls) and IfcRelVoidsElements, but this is a next step. 

### Discussion 
- For some use-cases the alternative representations can be loaded and kept in the background. When The geometry is changed, they are invalidated, but if it isn't, the representations are kept and exported again.

**Comment by Moult** [comment]
Sorry, just bumping this - I haven't ignored it, it's just a problem that requires a lot of work to fix, and warrants careful consideration of how to implement.

I've [started work](https://github.com/IfcOpenShell/IfcOpenShell/commit/6cc4ce46c20cd3050070e8c63306a767bf36016b) on a new native element roundtripping feature, which will effectively redesign how I go about importing and exporting. When this feature is complete, it will retain all representation contexts.

**Comment by Moult** [comment]
By the way, `IfcRelConnectsPath` is not yet supported. However, `IfcRelVoidsElements` is supported, but you have to enable the "Import Openings" option.

Also coplanar booleans is a bit unhappy in Blender, but hopefully with 2.91 this'll improve.

**Comment by Moult** [comment]
It's now fixed, so long as you enable the experimental "Roundtrip Native Representations" mode. Over time as it stabilises, it'll be enabled by default.
