### ISSUE TITLE
Is it possible to query the schema itself with IfcOpenShell?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#953]
Can I, with Python bindings, ask IfcOpenShell to give me a list of all of the subclasses of IfcElement or IfcRoot, etc? Or, given a particular class, like IfcWall, ask it what the valid values are for the PredefinedType attribute? Or ask it what attributes are possible on an IfcWall?

**Comment by aothms** [comment]
Yes, but it was never added to the handwritten wrapper. See here for it's usage: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/validate.py#L77

You get a latebound schema definition object back, see here for the C++ signature to give you an idea how to use it in Python: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcSchema.h#L424

Most importantly things like `declaration_by_name()` and then get an entity and and then get `subtypes()` https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcSchema.h#L305 or it's `supertype()` https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcSchema.h#L381

**Comment by EAzari** [comment]
@aothms do you have any plan to map EXPRESS types and entities and their types (attributes) to JSON or JS/TS? 
Personally I don't care about supertypes and subtypes, I just want to have a list of all types and entities and their types in JSON

**Comment by aothms** [comment]
@EAzari no plans, but it'd be relatively easy to extract from Python. Maybe when Dion has developed his schema inspection tool it's easy to dump it do json data later. But don't the IfcJSON guys not have a JSON Schema you can use?

**Comment by Moult** [comment]
@aothms thanks - that's exactly what I needed. I'll be sure to document it in the OSArch wiki so that others can discover it easily!
