### ISSUE TITLE
Simple cube IfcPolygonalFaceSet has a weird shape

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#955]
[test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/5107342/test.ifc.txt)

A supposedly simple polygonal face set is shown in the above file:

```
#13=IfcIndexedPolygonalFace((0,4,6,2))
#14=IfcIndexedPolygonalFace((3,2,6,7))
#15=IfcIndexedPolygonalFace((7,6,4,5))
#16=IfcIndexedPolygonalFace((5,1,3,7))
#17=IfcIndexedPolygonalFace((1,0,2,3))
#18=IfcIndexedPolygonalFace((5,4,0,1))
#19=IfcCartesianPointList3D(((1.,1.,1.),(1.,1.,-1.),(1.,-1.,1.),(1.,-1.,-1.),(-1.,1.,1.),(-1.,1.,-1.),(-1.,-1.,1.),(-1.,-1.,-1.)))
[#20=IfcPolygonalFaceSet(#19,$,(#13,#14,#15,#16,#17,#18),$)]
```

Upon create_shape, I get this funky shape. Geometry.verts shows a vertice at 0,0,0. Not sure what is wrong :(

![image](https://user-images.githubusercontent.com/88302/90863081-c7530c00-e3d1-11ea-836e-c9ff833b5317.png)

**Comment by aothms** [comment]
They are 1-indexed. So increment all indices with one. ;)

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op vr 21 aug. 2020 09:14 schreef Dion Moult <notifications@github.com>:

**Comment by Moult** [comment]
Ah yes :) Whoops! Thanks!
