### ISSUE TITLE
BlenderBIM: roadmap for imperial ```diagram_scales_enum```?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#956]
Curious, what's the roadmap look like for imperial ```diagram_scales_enum```?

**Comment by Moult** [comment]
Can you teach me how imperial scales work? What are the standards?

e.g. for metric, it's 1, 2, 5, and multiples of 10 of those, and on rare occasions it's "custom". What's the rule for imperial?

**Comment by theoryshaw** [comment]
Sure, does this help? http://www.complicad.com/CADScale.htm

**Comment by Moult** [comment]
That's both fascinating and frightening :) I'll see what I can do!
