### ISSUE TITLE
BlenderBIM: Guess quantity GrossFootprintArea

### ISSUE THREAD

**Issue by JanFilipec** [IfcOpenShell/IfcOpenShell#958]
Blender 2.83.5, BlenderBIM 0.0.200810

Trying to calculate quantities of a simple box, all other work, but footprint returns 0, works only for a mesh plane.

![grafik](https://user-images.githubusercontent.com/67052298/91325626-b9333000-e7c3-11ea-9f7b-7f54628bbc6f.png)

**Comment by Moult** [comment]
This was fixed on the 15th of August, so it should be already fixed in the master branch: https://github.com/IfcOpenShell/IfcOpenShell/commit/a1e5135a9ea93bef24de293dc182171d18f8e61e
