### ISSUE TITLE
BlenderBIM: MeasureIt support

### ISSUE THREAD

**Issue by JanFilipec** [IfcOpenShell/IfcOpenShell#959]
Blender 2.83.5, BlenderBIM 0.0.200810

How is the MeasureIt compatability supposed to work? I don't recieve any extra output from the dimensions.

![grafik](https://user-images.githubusercontent.com/67052298/91325914-06170680-e7c4-11ea-92f3-fb0360c4187f.png)
![BlenderBIM_SvgHatch_01](https://user-images.githubusercontent.com/67052298/91325938-0c0ce780-e7c4-11ea-9082-d25cb74f9dbd.JPG)

**Comment by Moult** [comment]
The MeasureIt support relies on having the latest MeasureIt-Arch version. One thing you need to check is that your MeasureIt-Arch version comes from their latest master, and that the name is `MeasureIt_ARCH` with an underscore, not a hyphen.

**Comment by JanFilipec** [comment]
Brilliant, after removing the "-master" from the folder name as suggested in the readme it works.
