### ISSUE TITLE
Add cardinal direction indicator to generated plans

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#962]
This can be added to output drawings.

I will upload a series of a few dozen screenshots showing example north indications from actual commercially produced plan views taken from Australian Development Application literature later today.

**Comment by Moult** [comment]
Cheers. Usually this arrow is added to the titleblock, not an individual drawing. I will think of how to implement this - there are a few approaches.

**Comment by globalcitizen** [comment]
- Even if it is physically within the titleblock it has to change on a per-drawing basis as elevations would generally not have them, only plan views.
- It would be an unduly restrictive limitation in this day and age to disallow the creation of rotated plan views which may be required eg. to emphasize boundary features, to demonstrate long shadow casting, in case of unique topographic components such as cliffs, any particularly long constructions, etc.

**Comment by globalcitizen** [comment]
Here are the results of my survey of northpoint indications from ~30 different sets of plan documents.

![north-18](https://user-images.githubusercontent.com/505366/91648773-e8d98500-eaae-11ea-9693-55024216479b.png)
![north-19](https://user-images.githubusercontent.com/505366/91648774-e9721b80-eaae-11ea-9923-0179d1a3fe28.png)
![north-20](https://user-images.githubusercontent.com/505366/91648775-ea0ab200-eaae-11ea-8c1d-d0208dce0fdf.png)
![north-21](https://user-images.githubusercontent.com/505366/91648776-eaa34880-eaae-11ea-9d45-7511576b8b86.png)
![north-1](https://user-images.githubusercontent.com/505366/91648777-eb3bdf00-eaae-11ea-9127-cb400d6c3bb4.png)
![north-2](https://user-images.githubusercontent.com/505366/91648778-eb3bdf00-eaae-11ea-8afc-f5b8cff15679.png)
![north-3](https://user-images.githubusercontent.com/505366/91648779-ec6d0c00-eaae-11ea-913e-beb13ebd44ec.png)
![north-4](https://user-images.githubusercontent.com/505366/91648780-ed9e3900-eaae-11ea-9573-569e9682ed5b.png)
![north-5](https://user-images.githubusercontent.com/505366/91648781-ee36cf80-eaae-11ea-9768-9ae079938773.png)
![north-6](https://user-images.githubusercontent.com/505366/91648782-eecf6600-eaae-11ea-81e8-dbe9fd024876.png)
![north-7](https://user-images.githubusercontent.com/505366/91648783-ef67fc80-eaae-11ea-9d14-6e4a7b3f7787.png)
![north-8](https://user-images.githubusercontent.com/505366/91648784-f0009300-eaae-11ea-81aa-a5394ea322cb.png)
![north-9](https://user-images.githubusercontent.com/505366/91648785-f0992980-eaae-11ea-9313-5ffa48a1b170.png)
![north-10](https://user-images.githubusercontent.com/505366/91648786-f131c000-eaae-11ea-8309-6bddfbf0501a.png)
![north-11](https://user-images.githubusercontent.com/505366/91648787-f1ca5680-eaae-11ea-81c6-c5859e9a5556.png)
![north-12](https://user-images.githubusercontent.com/505366/91648789-f262ed00-eaae-11ea-9bf9-564c3ba1f2c4.png)
![north-13](https://user-images.githubusercontent.com/505366/91648790-f262ed00-eaae-11ea-90b1-c9a53f537b06.png)
![north-14](https://user-images.githubusercontent.com/505366/91648791-f3941a00-eaae-11ea-8f9e-a88e88ae75d4.png)
![north-15](https://user-images.githubusercontent.com/505366/91648792-f42cb080-eaae-11ea-8da3-2be8529f8c2e.png)
![north-16](https://user-images.githubusercontent.com/505366/91648793-f4c54700-eaae-11ea-9b9e-59bdf3ce550b.png)
![north-17](https://user-images.githubusercontent.com/505366/91648794-f55ddd80-eaae-11ea-8b19-79541d308537.png)

**Comment by globalcitizen** [comment]
In terms of overall conclusions, I think we can state categorically that:
- There is no standard northpoint indicator
- Some of the indicators show:
   - 'truth north'
   - magnetic north
   - north for specific purposes
   - undefined
   - some combination of the above
- Some indicators also show:
   - number of degrees by which the angle is offset
   - additional visual references for east and west
   - summer and winter sunrise and sunset positions
 - Indicators are positioned roughly 50% of the time either:
   - Opportunistically within the main drawing
   - Within the title block

With regards to i18n:
 - We can assume that in some languages the indicator for north may be used that is not N.
    - For example, in Chinese, Japanese and Korean the symbol 北 may be used. In Arabic, perhaps الشمال.
 - There may be cultures or projects in which north is not to be indicated, and instead south is indicated.
    - For example, in historical contexts, Chinese used south (南) rather than north, leading to the Chinese word for compass (指南针 "south-determining needle").
 - I imagine that it is a possibility that this may be a politically charged question and/or regulatory requirement in some cases.

For a 'quick solution' I think N with an arrow up is fine. However, longer term it may be best to allow the user to specify an input SVG to be used as the cardinal direction indicator, and to define a set of standard text substitutions that will be run against any such input file before use. For example:
 - ``{{NORTH}}`` may be replaced with `North` in the specified human language.
 - ``{{TRUE NORTH}}`` may be replaced with `True north` in the specific human language.
 - ``{{NORTH_DEGREES}}`` may be replaced with `-23.45°`
 - ... and so on.

I will look at authoring some simple SVGs based on the cardinal indicators above to provide example templates for this purpose to facilitate development of this feature.

**Comment by globalcitizen** [comment]
Uploaded SVGs [over here](https://github.com/globalcitizen/cardinal-direction-indicators). Font is OpenGost in all cases. I believe centering replaced text may present an issue: apparently InkScape does not allow you to store text alignment preference owing to SVG not supporting it.

**Comment by Moult** [comment]
Fixed https://github.com/IfcOpenShell/IfcOpenShell/commit/8cc4edf60f8849b0aef2a7a2a08364c589c6ca9b
