### ISSUE TITLE
Sync Blender-bundled "Lighting: Sun Position" add-on's North and IFC north

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#963]
If there is a configured (site is geopositioned + oriented) **Lighting: Sun Position** add-on or an IFC imported north then we should attempt to obtain north from or sync north to that source.

Previous discussions:
- #808 discussed this need.
- #882 mentioned this, but is now closed.

Issues that depend a finished strategy for this data:
- #890 depends on it. (automatically name views)
- #962 depends on it. (show north on generated plans)

**Comment by Moult** [comment]
Definitely needs to be done. Absolutely correct.
