### ISSUE TITLE
cove.tool export

### ISSUE THREAD

**Issue by edwinguerra** [IfcOpenShell/IfcOpenShell#967]
I have tried exporting a project, and am unable to get covetool to recognize. covetool support claims everything is coming through except the roof. Additionally. it would be useful to have a dialog confirmation of the upload, i.e. # walls, windows, shades, etc exported.
https://assoceng-my.sharepoint.com/:u:/g/personal/guerrae_ae_ca/EeHZgPkLzhdJjdwqT1cvEAEBrzOiBQRFw6Pxl9ZcVVpPSQ?e=6SRM9r

**Comment by Moult** [comment]
Revit likes to export roofs as aggregates. Just "Explode Aggregate" and reassign it (usually an IfcSlab) as an IfcRoof.

Hope it helps.

**Comment by edwinguerra** [comment]
Thanks. It appears that my areas are now coming in blank. Are these coming from net/gross area from the IFC qto?

**Comment by Moult** [comment]
@edwinguerra to my knowledge the add-on should not submit any areas. It only submits geometry to covetool.

When I initially built this - I tested it on feasibility stage shapes which used single planes for walls, roofs, and windows - not walls with thicknesses like in your model. I wonder if that is what is causing the issue? Have you tried with a model without thicknesses?

Otherwise, I'd better have a chat with the covetool guys and figure out what's going on.

**Comment by edwinguerra** [comment]
Hi Dion, do you by chance have the file you used to test? It might be worth testing if it still works, and maybe having cove.tool add it to their documentation.

**Comment by Moult** [comment]
Just revisiting this now, my trial has expired on cove.tool so I've requested an extension so I can recheck it and provide some sample files too.

**Comment by Moult** [comment]
Confirming that the feature is a bit spotty right now. I've got rather mixed results from my tests. Have pinged the covetool guys to help debug together. Will keep this issue posted.

**Comment by Moult** [comment]
Tested and all works :) - I forgot to assign a roof, which was a required element, hence the first time it didn't work for me, but now it works :D

![2021-07-21-085519_798x724_scrot](https://user-images.githubusercontent.com/88302/126405524-f681e018-4661-4a45-a9bd-84f136060905.png)

![2021-07-21-085504_480x536_scrot](https://user-images.githubusercontent.com/88302/126405529-e7f79f8d-bf67-490f-a878-c4ff4d39e483.png)

![2021-07-21-085436_813x582_scrot](https://user-images.githubusercontent.com/88302/126405531-72479f12-95a1-4cc3-8c25-b026398f1b9f.png)
