### ISSUE TITLE
IfcSweptDiskSolid with non-bounded curve not displayed correctly

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#968]
Just for the record from this thread: https://forums.buildingsmart.org/t/ifcsweptdisksolid-is-not-displayed-correctly-in-any-of-the-viewers-i-tried/2915

Not a high priority for me personally but just thought I'd include it in the buglist in case others stumble across it.

**Comment by aothms** [comment]
Looking at the forum, seems quite a bit of tools updated the code for this. Oh, the pressure.

**Comment by Moult** [comment]
Closing as fixed! :)

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/commit/fcc056e204d9825304d82545dd5fbf913bc8aa8b
