### ISSUE TITLE
Is there a way to modify shapes in a ifc file?

### ISSUE THREAD

**Issue by JosephLZD** [IfcOpenShell/IfcOpenShell#969]
I'm currently working on a project which is to modify shapes in a ifc file, then to export this as a new ifc file.

Unfortunately, I realized that it is Brep shape that in the ifc file, and Brep model seems to have abandoned all the information and parameters. Although I can do some basic functions like translation and rotation on models, I cannot change the shape parameters such as radius and length...

I'm almost hopeless. Please comment ur thoughts. Any help would be appreciated!

**Comment by Moult** [comment]
Is this a question about the BlenderBIM Add-on?

If it is, the BlenderBIM Add-on by default converts all shapes into a Brep upon import, and all the parametric information is lost about the original geometry.

However, if the "Import Native Representations" option is enabled, during import, a few shapes will retain their parametric information. At the moment, these include only extruded profiles for rectangles, polylines, and circles, and faceted breps. That's not much, though, but it covers most basic objects that come out of other apps: slabs, columns, roofs... Once it's in, you can edit it almost like a regular mesh, but upon export, it'll generate new parameters.

If you provide your file and let me know which object you want to retain parametric native geometry for, I can attempt to add support for that shape. Some are easier, and some are much, much harder :)

![image](https://user-images.githubusercontent.com/88302/92044642-0fa2fe80-edc2-11ea-8d46-d56adc96650c.png)

**Comment by aothms** [comment]
Yes, another option is FreeCAD's importer. In essence that's what they do, they still rely on IfcOpenShell for parsing, but retain more parametric information by mapping extrusions/circles to native parametric constructs in Blender/FreeCAD. Technically this would allow making changes and then re-exporting.

It also depends on the amount of changes that are required. If you just need to change a couple of circle radii you might just do that without an evaluation of the geometry and just rely on the parser, change the parameters and rewrite in just plain IfcOpenShell. You can optionally later reevaluate the geometry for example to calculate quantities such as volume.

**Comment by JosephLZD** [comment]
@aothms  I really appreciate ur reply!

**Comment by JosephLZD** [comment]
@Moult  @aothms  I really appreciate your help!
I know that we can export IFC files with parametric models on FreeCAD, but how to do change on models without FreeCAD? I’ve tried using IfcOpenShell to change parameters and export it as a new IFC file. However, importing this new file works well on FreeCAD app as the shape is changed automatically while the shape remains the same by IfcOpenShell and PythonOCC even the parameter is different.

Here's the code for changing parameters of the ifc file:
```
class metadata_dictionary_edit(object):
    def __init__(self, file):
        self.file = file
        self.cache = {}

    def process_edit(self, i):
        if i.is_a("IfcRelDefinesByProperties"):
            # print("IfcRelDefinesByProperties")
            return self[i.RelatingPropertyDefinition]
        elif i.is_a("IfcPropertySingleValue"):
            # wrappedValue is an IfcOpenShell specific-attribute
            # to obtain the value SELECT-based simple type
       
			**# Here to change radius
            if i.Name == 'FreeCAD_Radius':
                i.NominalValue.wrappedValue = 0.006**
            return i.Name, i.NominalValue.wrappedValue
        elif i.is_a("IfcPropertyEnumeratedValue"):
            return i.Name, tuple(map(operator.attrgetter('wrappedValue'), i.EnumerationValues))
        elif i.is_a("IfcPhysicalSimpleQuantity"):
            # IfcPhysicalSimpleQuantity has many subtypes, with each
            # a different attribute name, but the same index (3).
            return i.Name, i[3]
        # TODO: Not all subtypes of IfcProperty currently implemented

    def __getitem__(self, i):
        id = i.id()
        if id in self.cache:
            return self.cache[id]

        # Dynamically resolve the relevant attribute based on entity type
        attrs = {
            "IfcObject": "IsDefinedBy",
            "IfcPropertySet": "HasProperties",
            "IfcElementQuantity": "Quantities"
        }

        for entity_type, attribute_name in attrs.items():
            if i.is_a(entity_type):
                # Process the aggregate of properties, quantities
                # or sets and convert into a dictionary
                props = dict(filter(None, map(self.process_edit, getattr(i, attribute_name))))
                if not i.is_a("IfcObject"):
                    props = i.Name, props
                self.cache[id] = props
                return props

    def __iter__(self):
        for object in self.file.by_type("IfcObject"):
            yield object.GlobalId, self[object]
```

Here’s the code for displaying shape of ifc files:
```
filepath = "new_test_2.ifc"
print("Opening IFC file %s" % filepath, file=sys.stderr)
ifc_file = ifcopenshell.open(filepath)
print("file opened.", file=sys.stderr)

metadata = metadata_dictionary(ifc_file)

products = ifc_file.by_type('IfcProduct')
products_to_display = []
for product in products:
    if (product.is_a("IfcOpeningElement") or
            product.is_a("IfcSite") or product.is_a("IfcAnnotation")):
        continue
    if product.Representation is not None:
        products_to_display.append(product)
print("Products to display: %i" % len(products_to_display))
# For every product a shape is created if the shape has a Representation.
print("Traverse data with associated 3d geometry")
idx = 0
product_shapes = []

for product in products_to_display:
    # display current product
    shape = ifcopenshell.geom.create_shape(settings, product).geometry
    product_shapes.append((product, shape))
    idx += 1
    print("\r[%i%%]Product: %s" % (int(idx * 100 / len(products_to_display)), product.get_info()))
    print(metadata[product])

    itemName = [str(product), str(metadata[product])]
    parentItem = self.treeViewRoot
    item = QTreeWidgetItem(parentItem, itemName)
    item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
    item.setCheckState(0, Qt.Checked)

# # Initialize a graphical display window
# print("Initializing pythonocc display ...", end="")
# display, start_display, add_menu, add_function_to_menu = init_display()
# print("initialization ok.")
# then pass each shape to the display
nbr_shapes = len(product_shapes)
idx = 0
for ps in product_shapes:
    uid = self._currentUID + 1
    self._currentUID = uid
    # display.DisplayShape((ps[1]))
    # Update dictionaries
    self._partDict[uid] = ps[1]
    self._nameDict[uid] = ps[0]
    c = OCC.Display.OCCViewer.rgb_color(169. / 255., 169. / 255., 169. / 255.)  # default color
    self._colorDict[uid] = c
    self.activePartUID = uid  # Set as active part
    self.activePart = ps[1]
    self.drawList.append(uid)  # Add to draw list
    idx += 1
    # progress bar
    print("[%i%%] Sending shapes to pythonocc display." % int(idx * 100 / nbr_shapes))

self.redraw()
self.fitAll()
```

I import the new file on FreeCAD, do nothing and export it as another new ifc file. Then I import this file by ifcOpenShell and PythonOCC, it surpisingly shows the changed shape as wish. I have no idea what’s going on here…

**Comment by aothms** [comment]
That's because you're changing a FreeCAD specific property `FreeCAD_Radius`. Propertysets like this are collections of application-specific key-value pairs. So it's expected that only FreeCAD would respect that.

For general purpose modifications you need to look at the actual geometry definitions. For example, maybe there is a IfcCircleProfileDef http://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcprofileresource/lexical/ifccircleprofiledef.htm somewhere in the file. Geometry is the Representation of the element, so follow that instead. Propertysets are just meta-data (that applications can give specific meaning to).

**Comment by JosephLZD** [comment]
@aothms  So do you mean FreeCAD somehow builds a kind of relationship between meta-data and geometry? How? I re-import the IFC file with modified meta-data and FreeCAD shows me the modified geometry model as wish. Is there a way for us to find and study that method? 
Thx for ur patience!

**Comment by Moult** [comment]
@JosephLZD IFC stores some geometry in a parametric manner. E.g. it may store a circle as a center + a radius. Therefore, by adjusting the radius in the IFC file, you can modify the circle.

FreeCAD supports even more parametric geometry - some of these overlap with IFC's parametric capabilities (e.g. the radius of a circle), and others do not (e.g. array, mirroring). IFC lets you store arbitrary properties associated with an object, called "property sets". FreeCAD has chosen to store some of its own FreeCAD-specific parametric geometry instructions in these property sets. These property sets are FreeCAD-specific and will not work in other IFC viewers.

There has been discussion on how to standardise some of these extra parametric behaviours where the parametric capability is shared between FreeCAD / Blender / Revit / etc - but so far to my knowledge these have only been discussions and haven't turned into working code yet.

**Comment by Moult** [comment]
I think this question has been answered, so closing. Later version of the BlenderBIM Add-on offer quite advanced geometry editing capabilities and this is continuing to grow over time.
