### ISSUE TITLE
Is it possible to query applicable psets in the schema?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#971]
Right now, I'm parsing the pset template definitions provided by buildingSMART, to know that a Pset_WallCommon applies to an IfcWall and not to an IfcColumn. Is there a better way of doing this? Is there a way to check this within IfcOpenShell?

Is it worth adding, if only to validate IFCs?

If not, that's OK, just wondering.

**Comment by aothms** [comment]
There's currently nothing in IfcOpenShell for this, but I think it makes a lot of sense to store the xmls somewhere in the repo and provide some utility functions for them in the utils module. Not a big fan of doing this in C++ as it's much less flexible, but maybe later.

**Comment by Moult** [comment]
Cheers - I'll add it to my to-do list to add it to the utility module in Python. When that's done I'll close this bug :)
