### ISSUE TITLE
BlenderBIM: error upon drawing export

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#972]
Video: https://www.dropbox.com/s/34lf2sx17uu504v/2020-09-03_17-46-35.mp4?dl=0

Test Files: https://github.com/OpeningDesign/OD_Library/tree/a9858a8d9dc6c86eb7d57a1ee03e34de460f2280/BIM/BlenderBIM

"version": (0, 0, 200829)

**Comment by Moult** [comment]
At the moment, if you use the MeasureIt Add-on, it has to be the latest version, and the addon folder needs to be renamed to use an underscore, not a dash. I think @kcress has fixed this in newer releases.

In the meantime, just disable the measure it add-on temporarily.

**Comment by theoryshaw** [comment]
nice.. good to know.
