### ISSUE TITLE
Error compiling - libxml/parser.h

### ISSUE THREAD

**Issue by motjokk** [IfcOpenShell/IfcOpenShell#974]
Hi,

Trying to compile. Getting this error after doing `$ make -j 4`

`fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
          ^~~~~~~~~~~~~~~~~
`

who`s to blame? me or it?

**Comment by motjokk** [comment]
Worked fine after checking out master.

**Comment by aothms** [comment]
v0.6.0 is recommended probably for most purposes. The XML part is not greatly configured in IfcOpenShell. When running cmake you can add `-DIFCXML_SUPPORT=Off`. To disable parsing of IfcXML. Probably this should be the default. IfcXML is pretty broken across applications anyway.
