### ISSUE TITLE
BlenderBIM: error when adding drawing to sheet

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#975]
Video: https://www.dropbox.com/s/smjpnsn3q9ee93n/2020-09-04_10-36-41.mp4?dl=0

File: https://github.com/OpeningDesign/OD_Library/blob/145a759e5aa5062cbbb04207d30ac60f92d103f3/BIM/BlenderBIM/OD_BlenderBIM_Template.blend

Error:

```
Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 2267, in execute
    props.sheets[props.active_sheet_index].name)
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\sheeter.py", line 52, in add_drawing
    view_tree = ET.parse(view_path)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\xml\etree\ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ryan\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons\\blenderbim\\bim\\data\\diagrams\\FLOOR PLAN - 1ST FLOOR.svg'

location: <unknown location>:-1
```

**Comment by Moult** [comment]
You need to create a drawing before it can be added to a sheet. I'll commit a change that doesn't pop up this scary error message.

**Comment by theoryshaw** [comment]
Maybe I'm missing something, but I thought this file has a drawing already...

![2020-09-04_17-14-25_blenderBlender_ DDropboxGitHubOD_LibraryBIMBlenderBblender](https://user-images.githubusercontent.com/507113/92288289-17ea5f00-eed2-11ea-905b-68402a95a313.png)

**Comment by theoryshaw** [comment]
That's the error I get when i try to add that drawing to the sheet.

![image](https://user-images.githubusercontent.com/507113/92288357-4a945780-eed2-11ea-83bf-3c302577e4ac.png)

**Comment by Moult** [comment]
This was resolved over a video call - but for the record, creating a drawing is done in the camera tab -> create drawing.

**Comment by theoryshaw** [comment]
Thanks Dion for the tutorial.
This problem, however, was related to: https://github.com/IfcOpenShell/IfcOpenShell/issues/972#issuecomment-686882235

I disabled 'measure it' and was able to create a drawing again.
