### ISSUE TITLE
Segfault when create_shape on boolean difference geometry

### ISSUE THREAD

**Issue by giovannivelludo** [IfcOpenShell/IfcOpenShell#977]
The [file](https://github.com/IfcOpenShell/IfcOpenShell/files/5177437/endplate.txt) in question. I had to change the extension to .txt because otherwise GitHub wouldn't let me upload it. I personally haven't noticed any errors in it, and the library I'm using to create the file automatically checks all the WHERE clauses from the IFC specification. The file is opened without any issues by other applications.

Here is the debug log from Blender:
```
/home/giovanni/.config/blender/2.90/scripts/addons/blenderbim/bim/__init__.py:285
/home/giovanni/.config/blender/2.90/scripts/addons/blenderbim/bim/__init__.py:285
Switching to fully guarded memory allocator.
Blender 2.90.0
Build: 2020-08-31 20:26:32 Linux Release
argv[0] = blender
argv[1] = --debug
Read prefs: /home/giovanni/.config/blender/2.90/config/userpref.blend
read file 
  Version 280 sub 39 date unknown hash unknown
/run/user/1000/gvfs/ non-existent directory
Warning: class BIM_OT_copy_attributes_to_selection contains a property which should be an annotation!
    assign as a type annotation: BIM_OT_copy_attributes_to_selection.prop_base
    assign as a type annotation: BIM_OT_copy_attributes_to_selection.prop_name
    assign as a type annotation: BIM_OT_copy_attributes_to_selection.sub_props
    assign as a type annotation: BIM_OT_copy_attributes_to_selection.collection_element
Warning: class BIM_OT_add_annotation contains a property which should be an annotation!
    assign as a type annotation: BIM_OT_add_annotation.obj_name
    assign as a type annotation: BIM_OT_add_annotation.data_type
Info: Deleted 1 object(s)

Writing: /tmp/blender.crash.txt

```
And here is [blender.crash.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/5177441/blender.crash.txt)

**Comment by Moult** [comment]
I think this is an IfcOpenShell geometry creation issue. Ping @aothms

**Comment by Moult** [comment]
By the way, there is now a STEP ID create_shape utility in Blender for helping to debug these.

Minimum working example to reproduce crash:

```
import ifcopenshell
import ifcopenshell.geom

f = ifcopenshell.open('endplate.ifc')
element = f.by_id(37)
print(element)
settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, element)
print(len(shape.verts))
```

The boolean (step ID 37) fails on these two shapes. The two shapes are a squashed sphere (34) and a slightly smaller squashed sphere (36):

![image](https://user-images.githubusercontent.com/88302/92296431-0f4c6400-ef78-11ea-946d-70f8d87f9f04.png)

**Comment by giovannivelludo** [comment]
I'm getting a similar issue with this [file](https://github.com/IfcOpenShell/IfcOpenShell/files/5190091/valve.txt), Blender doesn't crash but geometries are not shown.
[debug log](https://github.com/IfcOpenShell/IfcOpenShell/files/5190100/blender-2020-09-08-error.log)

**Comment by giovannivelludo** [comment]
Closed because both files causing the issue do not comply with the IFC specification, they both contain instances of IfcRevolvedAreaSolid where Axis intersects the interior of SweptArea, like in #1030 .
