### ISSUE TITLE
BlenderBIM: Pset_WallCommon variables not working in text tags

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#984]
![image](https://user-images.githubusercontent.com/507113/92407778-2d919b80-f101-11ea-9cb1-4420bf18d916.png)

![image](https://user-images.githubusercontent.com/507113/92407806-47cb7980-f101-11ea-90c0-0ff53cce5abc.png)

```
Traceback (most recent call last):
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 2232, in execute
    ifc_cutter.cut()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\cut_ifc.py", line 193, in cut
    self.get_template_variables()
  File "C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\cut_ifc.py", line 245, in get_template_variables
    pickle.dump(data, text_file, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle SwigPyObject objects

location: <unknown location>:-1


```

files: https://github.com/OpeningDesign/OD_Library/tree/1e0da36846d53129435702692146de16dba780c8/BIM/BlenderBIM

**Comment by Moult** [comment]
This works for me. I think you are hitting a bug that was fixed 3 days ago: https://github.com/IfcOpenShell/IfcOpenShell/commit/0522ea61f6537ccddcd93bec65c082e906c428b6

In that commit, src/ifcopenshell-python/ifcopenshell/util/element.py was changed. Maybe [download the latest of that file](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/util/element.py) and replace it in `C:\Users\ryan\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\`.

**Comment by theoryshaw** [comment]
Bingo, that was it. thx!
