### ISSUE TITLE
BlenderBIM: toggle on/off a 'temporary section cutaway' per each 'SVG Drawing' view.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#985]
Would be nice if you could toggle on/off a 'temporary section cutaway' per each 'SVG Drawing' view.

**Comment by theoryshaw** [comment]
This is nice, but was thinking something like this...
Where you can toggle on/off the section cut.
That is, it doesn't create a separate 'section cut' object in the model, but the view object of the camera is the section cut... that is if you moved the camera, the visual section cut would go with it. 

![image](https://user-images.githubusercontent.com/507113/92529850-e1258900-f1f0-11ea-8dc4-03ba443b0d9c.png)

**Comment by theoryshaw** [comment]
As I UI, i could see subsuming the 'temporary section' cut into the UI of the SVG Drawing list.

**Comment by Moult** [comment]
I see value in both approaches.

For example, when I'm auditing a model, but not authoring, often I don't want to create a drawing, but instead just have multiple section cuts and constantly move (usually more than one) of them around.

I'd prefer not to change this for the time being, and let it "mull" over whilst trying it out in workflows. It can be revisited in the future.
