### ISSUE TITLE
BlenderBIM - objects beyond not showing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#990]
I might be missing something (although it has worked in the past), but the objects beyond are not rendering. 

![image](https://user-images.githubusercontent.com/507113/92487376-c8967e00-f1b2-11ea-90c3-fe283da46dd9.png)

![image](https://user-images.githubusercontent.com/507113/92487418-d77d3080-f1b2-11ea-9cb2-2a82986e37e8.png)

files: https://github.com/OpeningDesign/OD_Library/tree/9ddd1a560afd395a8af374321475610c812d49c0/BIM/BlenderBIM

**Comment by Moult** [comment]
This is not related to the BlenderBIM Add-on, I believe. I think you may have accidentally deleted the output compositor node (maybe whilst playing around with a material setting?) Either re-add it (switch to a compositor window, and you'll see it's a blank canvas), or disable compositing:

https://blender.stackexchange.com/questions/42607/no-render-output-node-in-scene

**Comment by theoryshaw** [comment]
..and we're back.. Thx!


![image](https://user-images.githubusercontent.com/507113/92634763-6618ad00-f29a-11ea-9d0d-82facce810b2.png)

![image](https://user-images.githubusercontent.com/507113/92634820-79c41380-f29a-11ea-9dd5-fae6fc054904.png)
