### ISSUE TITLE
Regression: Wrong location of IfcGrid

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#991]
1. Convert [991--grid--wrongLocation.ifc](https://github.com/IfcOpenShell/files/blob/master/991--grid--wrongLocation.ifc) with 3e9fff6c198f04d7a90f1b82a89fd2f82d3ef731
2. Convert it again with 3b0585ae4bc0751ec99a30b2b4159c9ff7e5a925
3. Open both output files in the same viewer, and experience that they are not located at the same place:
![Sep-08-2020 22-49-21](https://user-images.githubusercontent.com/4601554/92527056-b48c6400-f226-11ea-9db0-e23cf3835f91.gif)

The output from 3b0585ae4bc0751ec99a30b2b4159c9ff7e5a925 (Feb 3) has the expected location, thus there must have been a regression on the way to 3e9fff6c198f04d7a90f1b82a89fd2f82d3ef731 (Jun 23).

**Comment by johanrd** [comment]
Closing, as this seems to convert successfully with 808ef1a (OCCT 7.5.0)

**Comment by johanrd** [comment]
Reopening, as this is still an issue after all.

**Comment by Moult** [comment]
This seems to work in v0.8.0. See #4832.
