### ISSUE TITLE
Regression in material layers sets slicing

### ISSUE THREAD

**Issue by Francois-Thierry** [IfcOpenShell/IfcOpenShell#996]
Hello,

I was playing with the `--enable-layerset-slicing` flag of IfcConvert and I noticed that it doesn't behave as well as previously (in 2017/2018 it was working well, similarly to http://blog.ifcopenshell.org/2015/10/separating-elements-by-their-material.html).

Now it produces errors and the folding of layers around corners where connecting walls meet does not work.

![Screenshot from 2020-09-11 09-12-22](https://user-images.githubusercontent.com/7921372/92886201-c121df80-f413-11ea-8e4c-ced13f6c6376.png)
```
Done writing geometry (236 objects)                                

Log:
[Error] Unable to map layer geometry to material index
[Error] Unable to map layer geometry to material index
[Error] Unable to map layer geometry to material index
[Error] Unable to map layer geometry to material index
[Error] Unable to map layer geometry to material index
[Error] Unable to map layer geometry to material index
[Error] Unable to map layer geometry to material index
```
It would be great if this feature was reinstated as IfcOpenShell is, to my knowledge, the only tool that offer this functionality.
Thanks for all the hard work on IfcOpenShell, it is really an amazing tool for the OpenBIM ecosystem.

**Comment by aothms** [comment]
Thanks I'll have a look end of this week.

**Comment by aothms** [comment]
There where two issues. Somehow the thickness calculation was done on integers. Thickness was used to determine whether wall layers needed to be "folded". This explains why in your image some joins are not properly handled. Secondly, apparently after a version upgrade, OpenCASCADE will return CompositeSolids in some cases (not sure why only in some cases, but it's not necessarily incorrect). This is now properly handled. This explained the `Unable to map layer geometry to material index` messages where the CompSolid was not properly explored.

**Comment by Francois-Thierry** [comment]
Thank you so much for re-enabling this feature !

On the model from before I have now a single error  `[Error] Unable to map layer geometry to material index`  but the folding around corners seems to work. I couldn't see any representation error visually :+1: (with OCCT 7.3.0p4)

For your information, I conducted an extensive study and converted 125 models with layerset slicing and it seems to be OK for most of the models converted (I didn't found any visual error after a quick look).
I'll report below some of the files that output errors related to the `--enable-layerset-slicing` flag.
Those errors seem to be of two kind :
- `[Error] Unable to map layer geometry to material index` that is the most common error, I found it in 25/125 models that I tested. It is related to the version of OCCT that I used as I understand from your explanations.
    - Ex : http://openifcmodel.cs.auckland.ac.nz/_models/20190104WestRiverSide%20Hospital%20-%20IFC4-Autodesk_Hospital_Metric_Architecture.ifc (264 errors)
- `terminate called after throwing an instance of 'Standard_TypeMismatch'` that I found in 5/125 models
    - Ex : SGD_HiTOS_Arch.ifc from https://tib.eu/data/duraark/BuildingData/01_IFC/SGD_HiTOS_ifc.zip

With OCCT 7.4.0p1 the single error of the model from before is gone but I hit the same `terminate called ... 'Standard_TypeMismatch'` on the second model that I tried, any ideas where that could come from ?
I will conduct the same study with OCCT 7.4.0p1 to see if it removes the `[Error] Unable to map layer geometry to material index` errors and I'll let you know.

But it is a very nice feature to have for visualization, thank you for taking the time to address this issue.
I will update this comment today or tomorrow with OCCT 7.4.0p1 results but feel free to close the issue if you want.
Have a nice day !

**Comment by aothms** [comment]
`Standard_TypeMismatch` should be easy to solve, that just means we're casting an OCCT shape to the wrong type. Do you have a line number for that by any chance. Otherwise I'll have a look later.

**Comment by Francois-Thierry** [comment]
I don't have a line number, it segfaults. I'll write the output in command_line mode below.
Interesting, on SGD_HiTOS_Arch.ifc it is only thrown when using `--threads` :
```
IfcConvert /media/francois/grosDISK/Models/SGD_HiTOS/SGD_HiTOS_ARC.ifc ~/Downloads/test.glb --use-element-guids --threads 8 --enable-layerset-slicing --include entities IfcObject --exclude entities IfcOpeningElement -y 
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
Scanning file...
Done scanning file   
Parsing input file took 3 seconds
Creating geometry...
[######                                            ]terminate called after throwing an instance of 'Standard_TypeMismatch'
[1]    20105 abort (core dumped)  IfcConvert /media/francois/grosDISK/Models/SGD_HiTOS/SGD_HiTOS_ARC.ifc    8
```
Without the `--threads` flag :
```
IfcConvert /media/francois/grosDISK/Models/SGD_HiTOS/SGD_HiTOS_ARC.ifc ~/Downloads/test.glb --use-element-guids --enable-layerset-slicing --include entities IfcObject --exclude entities IfcOpeningElement -y 
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
Scanning file...
Done scanning file   
Parsing input file took 2 seconds
Creating geometry...
Done creating geometry (343 objects)                                

Log:
[Error] {2eeX4yStT8lPdXztbq6ZOF} Unable to map layer geometry to material index
[Error] {04BmmW9UP27AJe6pw9b27z} Unable to map layer geometry to material index
[Error] {26zE_fD1b18BQb7PndYG8T} Unable to map layer geometry to material index
[Error] {0vK4x3F_TFCvhxKY6OGSyL} Unable to map layer geometry to material index
[Error] {3pgW082Cj3$xzGx3gBwOJH} Unable to map layer geometry to material index
[Error] {2l7JpGqSn8SgepBY4lcOC3} Unable to map layer geometry to material index
[Error] {2k4Flll2LEj8o$w$Oi_JzU} Unable to map layer geometry to material index
[Error] {0t93UO6Hf7IuALyo96Xr4N} Unable to map layer geometry to material index
[Error] {2Z$WdjLrD05x$7KeIbouLp} Unable to map layer geometry to material index
[Error] {240H_jJJj72ALcJef1MbJu} Unable to map layer geometry to material index
[Error] {1NCmfeC9585gB3$$oXr53b} Unable to map layer geometry to material index
[Error] {2Bt5Uqcwv6$80WcOVIAt9c} Unable to map layer geometry to material index
[Error] {0js9tjxwTDP8c2Gk60DrSW} Unable to map layer geometry to material index
[Error] {35mIL9qRf61xHHauPjXIIJ} Unable to map layer geometry to material index
[Error] {2Zx5wzKFz0VumcIeqfmX9e} Unable to map layer geometry to material index
[Error] {0ssUS3TKT7lfBV85TPopWr} Unable to map layer geometry to material index
[Error] {1aUDLN5Gb6mw0000D5Evia} Unable to map layer geometry to material index
[Error] {3Vuir8cc11Kg3h8BhhhtLk} Unable to map layer geometry to material index
[Error] {3zJwsN4O51LuK5Z81AppvW} Unable to map layer geometry to material index
[Error] {258mNkeujEaOKA22Kp4imL} Unable to map layer geometry to material index
[Error] {3heWuSVwv8DOjo2sFSYcf1} Unable to map layer geometry to material index
[Error] {3HxtUhUPn5bPIceShV6cfm} Unable to map layer geometry to material index
[Error] {15SGW8HfjC0vzetVDfT87M} Unable to map layer geometry to material index
[Error] {3X0q1Fnfr6GR15cn6IanVh} Unable to map layer geometry to material index
[Error] {1cnrk0ufH3c84foPrWp8jc} Unable to map layer geometry to material index
[Error] {3iMOfpXTjEvwjbUmLWbu2s} Unable to map layer geometry to material index
[Error] {01JHXZlO50Fes409BCeGuo} Unable to map layer geometry to material index
[Error] {2YGnD5amD8ZugcUY_NwG0Q} Unable to map layer geometry to material index
[Error] {3EIyWTes94bubRO2JwOR4I} Unable to map layer geometry to material index
[Error] {3KDUTb9XD7p8hj5zgCpX3Z} Unable to map layer geometry to material index
[Error] {3CsVzMy_PA1Q9SVippxRWV} Unable to map layer geometry to material index
[Error] {1H_UWtJAnDVeI7Ykf6BI1O} Unable to map layer geometry to material index
[Error] {1yCJ$zPSnE_uZyHYuWBge_} Unable to map layer geometry to material index
[Error] {0dej0eTEDEGuiD5UIfXEIU} Unable to map layer geometry to material index
[Error] {0OvQxl6Hv8nOLkex9_hxBt} Unable to map layer geometry to material index
[Error] {2E7c6Bbp13GOVexD8ggJXS} Unable to map layer geometry to material index
[Error] {3THtb2ByTC4wqIheEngdCl} Unable to map layer geometry to material index
[Error] {3b8_PuUeP76AWzZAVx79CO} Unable to map layer geometry to material index
[Error] {0PGDcBJn53fwZ6_8_UBO_M} Unable to map layer geometry to material index
[Error] {3OEnInpob5NwBizCTmZFeh} Unable to map layer geometry to material index
[Error] {0dsVMAOYD0fOV9FF_zUdEv} Unable to map layer geometry to material index
[Error] {3rLOqPDCr5mhkeYY_FBDNR} Unable to map layer geometry to material index
[Error] {17LwSJFQzBAOXTHoPcsIpw} Unable to map layer geometry to material index
[Error] {3NnsCyhXnBGRYeNjiumJ43} Unable to map layer geometry to material index
[Error] {1HMS02iMbBGgzgltcBAgQF} Unable to map layer geometry to material index
[Error] {1ZFDVGXDP1SRZ2bD1bRV6$} Unable to map layer geometry to material index
[Error] {3s3R2wdYLBmBikhIUKhKSJ} Unable to map layer geometry to material index
[Error] {2ttouoK5j3OP6_bD2KasSs} Unable to map layer geometry to material index
[Error] {14uKFyB894ofJyUVxrkn9x} Unable to map layer geometry to material index
[Error] {3xc3ZKkln6TOBKHW9hxCQ4} Unable to map layer geometry to material index
[Error] {0fRqvaPsbBGOMpuwtp6edO} TopoDS::Shell


Conversion took 15 seconds
```

**Comment by Francois-Thierry** [comment]
I managed to evade all the segfaults during conversion with `--enable-layerset-slicing` with OCCT7.3.
I am closing this issue for now.
Thanks again for the swift correction on folding of layers around corners.
